### ISSUE TITLE
Give sheets more applications

### ISSUE THREAD

**Issue by railmonkey** [CleverRaven/Cataclysm-DDA#10071]
Random idea that occurred to me. One of those things that I thought, "Wait, why isn't this already a thing?" Throwing sheets at a monster should give a high percent chance to blind and "web" them if they are hit. The idea is that you throw the sheet over the monster rather than at them. It's a desperation measure, obviously, but it could be effective at a bottleneck, with a broken window being both a prime example and the place where you're sure to find them. While I'm thinking about it, what about sheet traps? Place it in a likely area and examine it when a monster is standing on it to attempt to pull it out from under them and down them. Would be a Str roll, of course. In my mind's eye, I can see a survivor taking advantage and running an unfortunate zed through in either scenario.
##

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
