### ISSUE TITLE
Search by name when selecting item from inventory

### ISSUE THREAD

**Issue by Suseika** [CleverRaven/Cataclysm-DDA#10098]
I think it would be great to be able to select an item not by typing a letter assigned to it, but rather by entering some "search mode" and typing its name. Searching for various items with your eyes takes too much time. It would be much better to just type _screwdriver_ than remembering that it is not a weapon, but a tool, locating the letter with your eyes... _Damn, it's an uppercase left hand pinky finger key!_ You know the drill. Once I found out you can search by a name of a crafting recipe, I immediately thought there may be the same feature in the inventory, but sadly there wasn't.  For now inverntory searching is the number one feature I'd like to see. Please-please implement.

And thank you for your hard work.
##

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
