### ISSUE TITLE
Computer & Hacking Updates

### ISSUE THREAD

**Issue by DavidKeaton** [CleverRaven/Cataclysm-DDA#10158]
Howdy all, I have been tinkering with a new branch (now that I am tracking vache's new_computer_refactor branch) that will provide some updates/reworking of the current computer/hacking system and a few other neat things. Not sure when I will get this done, as I plan on giving some sweet love to my medicinal_revamp branch, but I will pop back and forth for sure.

Ideas/Plans:
-Add networking to computers (have to look into how this will really be used, but a neat idea).
-Add software other than just the games you play on that ol' GameBoy of yours.
-Make the laptop usable (and split broken and working laptops into different items).
-Hacking software to help with more complex security systems (perhaps making them required for some higher end systems?).
-Add more to what computers can _do_. (For instance, especially with electrical systems and cables becoming more of a reality, a house security rigged to a central terminal where you can lock doors and close blinds from that terminal or in the some programmed event by the user.)
-Neat junk I want to throw in because I live in a free country.

Any and all ideas or criticism welcome, bring it on!
-Davek

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
