### ISSUE TITLE
Morale penalty for butchering humans  and certain zombies

### ISSUE THREAD

**Issue by erzett** [CleverRaven/Cataclysm-DDA#10157]
Butchering in the game seems to be a pretty thourough process. A human corpse is reduced to just a few chunks of meat ready for consumption. Realistically, if you're not a cannibal, that should be a fairly traumatizing thing to do. Even someone like the medical resident, who would be familiar with autopsies, doesn't usually cut humans up into meat. Anyone else probably couldn't even bring themselves to cut a human open.

Now "disassembling" a skeleton corpse into bones shouldn't be too bad for someone who's survived an apocalypse, but most other zombies are human-like enough for butchering them to be depressing. I know C:DDA zombies are pretty much all blob inside but there seems to be enough structure left to produce distinguishable pieces of tainted meat. To me, that means they're not sufficiently different from humans on the inside.

From a gameplay balance perspective, butchering right now is almost always superior to smashing. The decision involved is really simple: Is the nearest zombie too close? Smash now, butcher later. Otherwise butcher now. Either way, it's free survival skill. And butcher all (which is a great addition, don't get me wrong) has just removed the last bit of tedium that would otherwise have made me prefer stacking bodies and just smashing them in a single action.
If butchering had a morale penalty, you might still do it sparingly to increase survival but it wouldn't be as much of an obvious choice.
##

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
