### ISSUE TITLE
Rebreather probably shouldn't be craftable

### ISSUE THREAD

**Issue by ryvn** [CleverRaven/Cataclysm-DDA#10151]
Assuming it's the same thing I'm thinking of - James Bond's mouthpiece-sized CO2 scrubber - it's firmly in the realm of fantasy-tech. Most of the other improbable items - power armor, teleporters, and such - are uncraftable by design. I'm not opposed to their existence - they're really cool - but making a CO2 scrubber which recycles air as fast as you can breathe it and fits in your pocket is Advanced Technology. Probably a rare find in labs and sporting goods stores, and maybe a very rare drop from swimmer zombies.

On the other hand, a rebreather system with a back-mounted tank is perfectly practical, and looking at Wikipedia, Henry Fleuss' design looks like something a skilled survivor could put together. It doesn't have any electronic parts - it would be Mechanics, I think. Item name would probably be "makeshift rebreather," and it would add 1 torso encumbrance.
##

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
