### ISSUE TITLE
Leash for pets

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#10256]
Brought up by Tnx on IRC.
The feature would allow you to craft a leash (or possibly just use a rope directly) which you can attach to a pet (zombie or dog, doesn't matter).  When attached, the leash would prevent the pet from moving more than n squares away from the player, and if the player moves more than that distance away from the pet, it would drag the pet.

Robustness:
Player should drop the leash if vehicle motion or forced movement moves them out of range.
Pet should be able to navigate stairs, possibly just by arriving at the bottom of the stairs at the same time as the player.

Optional features:
Strength check for pet dragging player or vice versa.
Have the pet navigate stairs properly instead of being teleported.
Allow multiple leashed pets, which ties (ha) back into the strength check thing.
Offensive use of a leash, such as a lasso type effect allowing use on hostile creatures.
##

**Comment by mugling** [comment]
Does the pet carrier provide enough of a solution?

**Comment by kevingranade** [comment]
I'm not totally sure, if the pet is expected to fight with you it does not,
if the pet is supposed to stay passive but protected the pet carrier is
sufficient.
Also a leash will work with much larger pets than a pet carrier will.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
