### ISSUE TITLE
Better messages when trying to weld

### ISSUE THREAD

**Issue by drbig** [CleverRaven/Cataclysm-DDA#10309]
Another issue that's probably known: you have your welder in check, batteries/fuel/whatever present. You try, but you can't. You look up what you need: [screenshot](http://i.imgur.com/q0hhehX.png) (courtesy of `Meyar` on IRC) - you've got it all!... But you forgot to put on your welding goggles.

In short: UI should tell the player exactly what (s)he is missing. This may also apply to things other than welding.

If this is intentional please tell (I'll have arguments against current vague/lack of proper messages).

**Comment by slitherrr** [comment]
Just popping in to :+1: DavidKeaton and drbig, ran into this last night (it turned out I'd moved the goggles from the welding rig when I was offloading after a loot run), and spent a good while trying to determine if it was a bug with the rig going from Brin to Cooper before I figured out the real problem.

**Comment by Rivet-the-Zombie** [comment]
I like this idea. I've seen far too many people get confused over why they can't weld, when a simple message at the time would have answered their questions.

**Comment by drbig** [comment]
This is done. (cleaning own issues for now)
