### ISSUE TITLE
Suggestion: starting city destruction

### ISSUE THREAD

**Issue by ogoid** [CleverRaven/Cataclysm-DDA#10316]
Isn't funny that the vehicles start damaged, but the towns neat and clean?

How about creating new worlds with some broken windows and doors, collapsed buildings, trash, blood and other signs of earlier chaos?
##

**Comment by sparr** [comment]
> a method in the master mapgen function that randomly applies some different effects to submaps after generation.

I don't know where it is, but don't we already have this? I've seen lava cracks in random buildings, and large areas of rubble, etc.

**Comment by Rivet-the-Zombie** [comment]
Yeah, but Vache's plan was for buildings to sometimes have blood/damage on them, broken windows/doors, smashed furniture, being partially burned, stuff like that.

We'd likely have it already if not for the fact that the PR got bogged down by the addition of a bunch of similar, but unnecessary other stuff, like pre-triffidized buildings and such.

**Comment by kevingranade** [comment]
The existing code overwrites terrain like a giant stamp, the proposal is to
e.g. turn walls to rubble so it looks like a partially wrecked hous instead
of a big hole in the ground.

**Comment by sparr** [comment]
I'm confused. I swear I saw a garage with a lava fissure through it, and I assumed "add a lava fissure" was an overlay somewhere.

**Comment by Zireael07** [comment]
Umm, linky to vache's PR? I know which one is being discussed here, but can't find it, search is not up to par.
I'm sure Coolthulthu or acidia could restart the idea in a cleaner way :)

**Comment by Rivet-the-Zombie** [comment]
The original PR in question:   https://github.com/CleverRaven/Cataclysm-DDA/pull/7892

**Comment by MattAmmann** [comment]
@sparr The lava spawning inside buildings is a map extra. I actually had this same question not too long ago: https://github.com/CleverRaven/Cataclysm-DDA/issues/11393

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
