### ISSUE TITLE
Idea - multiple wiring circuits for vehicle lights

### ISSUE THREAD

**Issue by NaturesWitness** [CleverRaven/Cataclysm-DDA#10320]
An issue that keeps coming up is interior vehicle lighting.  The way I see it, the problem isn't so much the lights themselves, but the fact that ALL lights on a vehicle are on the same circuit and have to all be on or off at the same time.

My question is, how hard would it be to have, say, four lighting circuits in the vehicle system?  When you install a light, you get a prompt to assign it to one of the circuits.  When you go to the vehicle controls and select "toggle lights", you get prompted to pick which circuit you want to toggle.

This system would give us a lot of flexibility; you can just switch on interior lights, police cars can have their flashers on their own circuit, you could even have hi/low beams and hazard lights.

Ideally, the vehicle examine menu would give you the option to assign a name to each circuit, but I don't know if that's feasible.
This would require a few new fields in vehicle.json; each vehicle would have an entry listing what each circuit's default name was, and each light part would have a field listing what circuit it was on.

Is this doable?
##

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
