### ISSUE TITLE
DeathCam Updates

### ISSUE THREAD

**Issue by DavidKeaton** [CleverRaven/Cataclysm-DDA#10366]
The following issues will be addressed:
- [x] SCT should stop updating for sure! [PR: #10459]
- [x] Pain counter should halt. [PR: #10459]
- [x] Robots continue to attack player post death.
- [ ] NPCs consider your corpse target practice.
- [ ] Animals should prefer not to deal with easy prey.
- [ ] Prevent NPCs from chatting with you when dead. [Found this one out the other night]
- [ ] Fix LOS issues on monster special attacks.

Zombies, on the other hand, should stay the same, IMHO. I am open to discussion on anything else!

Edit: I am going to update these via separate issues, as these may or may not expand.
##

**Comment by MattAmmann** [comment]
Various status effects on the player's sight radius affect the DeathCam. E.g., if the player is 'Blinded' when they die, the sight radius affects the DeathCam as well. Same thing with being 'Boomered'.

**Comment by KA101** [comment]
One thing, now that I look at it: zeds should realize that the PC is down, and stop pummeling (don't pulp their new ride!).

**Comment by DavidKeaton** [comment]
Interesting find guys. Will look into this at some point (may not be soon as they don't seem game breaking)

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
