### ISSUE TITLE
Some Item drops, when smashing animal corpses. or generic sharp rock

### ISSUE THREAD

**Issue by FireCrow1973** [CleverRaven/Cataclysm-DDA#10391]
So there you are, a unlucky shower victim, right smack dab in the middle of the forest.
You finally killed the Bobcat/Cat or whatever you found, your standing over it hungry and slightly wild 
Q: what do you do?
A: you lay down and die!

You can not:
Eat it raw.
Ripp it apart with your teeth.
Or, butcher it....without a knife.

Easy fix, make a knife, however you need: 
small string OR 20x sinew OR 20x thread OR 20x plant fibre.

but you cant get these things in the forest without a knife.
so your stuck, her is some solutions:
make some sort of Awkward_Stone_Knife or a Stone_Knife_Edge
Without the fancy wood and string handle.

if you have that capability you could in theory go from wearing nothing but a upside down smile.
to live of the land with your bow and your comfy animal skin clothing.
##

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
