### ISSUE TITLE
Scrapes and bruises -- more medical (mal)practice

### ISSUE THREAD

**Issue by narc0tiq** [CleverRaven/Cataclysm-DDA#10444]
As suggested by **Dragoonseal** in IRC, there should be more opportunities for scrapes, bruises, minor cuts, etc., which could show up as status effects and would provide targets for the first aid system (bandage your finger, whatever).
- Critically failing a craft might result in you cutting your hand or a finger.
- SHARP terrain's cuts might show up as status effects for this.
- Getting knocked down might bruise and/or scrape.
- Getting thrown around by a hulk or brute should be obvious.
- Combat, in general, should have a high chance of leading to these.

Untreated cuts/scrapes could open the way to infection (as zombie bites do), or tetanus, or might just heal on their own even if they're not minded (but decrease the hidden health stat in the process). Not sure if there's much you can do about bruises other than applying ice.
##

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
