### ISSUE TITLE
After trade NPC appears to stop following

### ISSUE THREAD

**Issue by ArikVhedrovix** [CleverRaven/Cataclysm-DDA#10447]
I am using Windows experimental 8b38e05.
I convinced a NPC to follow me around. We both went back to my shelter and I saved and quit. Then when I reload the save she is no longer following me. I also have lower chance to convince her to follow again for some reason.
##

**Comment by Ygdrad** [comment]
This bug is still present. Doesn't happen all the time, but often enough. After a trade, be it successful or cancelled, you get a dialogue window as if you met this npc for the first time. You can exit this window with the "bye" option and sometimes the npc will remain fine and sometimes it gets broken with 0% chance of you convincing it to do anything.
