### ISSUE TITLE
Dissection (first aid practice on corpses)

### ISSUE THREAD

**Issue by narc0tiq** [CleverRaven/Cataclysm-DDA#10443]
Initially proposed by **JENPOCALYPSE** on IRC, the proposal is for a new task, dissection, which would take a much longer time than butchery does, but would exercise your medical skill (first aid) in return. The primary reasoning being that first aid is relatively hard to improve outside of reading books.
- The end result of dissection would be a "dissected [whatever] corpse", which would give reduced returns on butchery products because they were 'damaged from experimentation'.
- Dissecting should give good returns on CBM extraction (once past a minimal skill level), in combination with which we could raise the minimum level for bionic extraction for butchery -- effectively transferring CBM extraction to the dissection operation unless you have very high survival skill.
- It is assumed that a typical dissection of a typical human-sized corpse would be approximately an hour long, obviously altered by the size of the corpse actually being dissected.
- It is further proposed that dissecting multiple of the same kind of creature lead to diminishing returns in terms of medical experience. For best results, dissect many kinds of things!
- On the other hand, increased dissection experience with a certain creature type could give you a chance to obtain bonus materials (leather, meat, etc.) when butchering those creatures, as you can target the desired parts better.
- This could also tie in to a small bonus when fighting creatures you've dissected before -- probably a small increase in the chance of obtaining critical hits, limited by your skill with the weapon (must know both where the weak spots are and how to control your weapon so that it hits it).
- Dissecting non-humans should lead to much reduced exercise of the medical skill (won't learn much about human anatomy from dissecting a giant ant), but the butchery and damage bonuses may make up for this.
##

**Comment by railmonkey** [comment]
Maybe, but I'm personally of the opinion that we have plenty of traits already. How viable would it be for the penalty to keep diminishing until it became a small morale bonus instead? Maybe cap it at ~+5.

**Comment by Stretop** [comment]
For every game mechanic there are traits which fine-tune it (hunger, thrist, guilt, reading, skill-training - to name a few). It is simply how this game rolls =)

And reverting diminishing malus into increasing bonus is unrealistic: when human do something again and again - he does not start to feel better and better about it, he tend to simply stop caring.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
