### ISSUE TITLE
Auto-pickup: "cotton*" does not auto-pickup plastic bag of cotton balls.

### ISSUE THREAD

**Issue by Griffinhart** [CleverRaven/Cataclysm-DDA#10570]
`cotton*` tests properly (i.e. testing has `cotton balls` as one of the results), but does not actually auto-pickup the item "plastic bag of cotton balls".

`*cotton*` will auto-pickup "plastic bag of cotton balls". It looks like the container is considered part of the item name for things in plastic bags~~, which is inconsistent with other container behavior (e.g. `lye powder` will auto-pickup "small plastic bottle of lye powder")~~.

e: Whoops. I thought `lye powder` was working on "small plastic bottle of lye powder", but it turns out I also have `*powder` as an APU rule. I'll try testing `lye powder` without `*powder` and see if this still happens.

**Comment by BevapDin** [comment]
> cotton*  tests properly (i.e. testing has  cotton balls  as one of the results), but does not actually auto-pickup the item "plastic bag of cotton balls".

Of course not, the item on the ground is a plastic bag (that contains cotton balls), that's absolutely correct behavior.

If you want that behavior, use "\*cotton balls\*".

> It looks like the container is considered part of the item name for things in plastic bags,

The name of the container **is** the used for autopickup, the content is only "accidentally" included in the check because it happens to be part of the container name. This would not work at all with gunmods: add a brass catcher to a gun, drop the gun, add "\*brass catcher\*" to the rules, a plain brass catcher will be picked up, but the gun with it won't.

This works exactly the same for other items and other containers.

> I'll try testing  lye powder  without  *powder  and see if this still happens.

Written 4 months ago. I just tested: "\*lye powder\*" picks up contained lye and non-contained lye, as does "\*lye powder". "lye powder" only picks up the non-contained lye, not the bottle of it, same as "lye powder\*".

In my opinion, this works fine and nothing here is a bug. If there is something wrong, it should be stated explicitly, because the current issue is (in a nutshell): "The autopickup does not pickup if only the item in a container matches, but not the container name itself" (works as intended) and "It looks like the container is considered part of the item name for things in plastic bags, which is inconsistent with other container behavior." (it's consistent, all containers behave that way).

----

I'm wondering what the shelter NPC thought about my character walking around in the shelter, repeatedly dropping and picking up the lye - she probably expected to see my characters head explode any minute (-:

**Comment by KA101** [comment]
Fair enough.
