### ISSUE TITLE
Filling Wooden Keg with rotten cider results in fresh cider in keg.

### ISSUE THREAD

**Issue by Hague** [CleverRaven/Cataclysm-DDA#10605]
It's just like the title says. I recently placed some rotten cider inside a keg to consolidate it all for vinegar production. A message read upon filling: You fill the wooden keg with apple cider (fresh)

I can assure you I had no fresh cider on me at the time and it pulled all the rotten cider from various containers. Upon examination it said: "It contains apple cider (fresh) (23), 3% full"

It seems the keg doesn't save the spoilage of liquids it pulls from the player inventory.

Edit: Explored a little further it does appear that any liquid stored using the Wooden keg's interface will reset its spoilage to fresh: Orange juice, Ketchup, Mayonnaise, were some I tested.
##

**Comment by kevingranade** [comment]
I'm guessing @mafagafogigante had it, but I lost track of this for too long, sorry.
The message was based on a freshly created item, which means it was fresh, after a single turn passing though it became rotten.  Also, the same happened to fresh perishables, since the item was set with a birthday of 0 (pre-cataclysm age).

**Comment by mafagafogigante** [comment]
@kevingranade I would be lying if I said I remember anything I found out when investigating this. I hope you can figure out what caused this.
