### ISSUE TITLE
Basements on the 'newer' homes?

### ISSUE THREAD

**Issue by EkarusRyndren** [CleverRaven/Cataclysm-DDA#10612]
Is there any reason the new, fancy looking homes don't generate basements? It seems like an oversight really but I'm more or less thinking outloud.

By "Newer" homes I'm referring to the various non cube five room homes that generate with something of a decorative layout and use of non-standard materials. Things like the stone house, the house with a pool, and so on.
##

**Comment by Snaaty** [comment]
Where are the basements even defined and where is it defined if/where they're supposed to spawn?

**Comment by BevapDin** [comment]
Overmap ares generated in overmap.cpp, the function `house` is used to return the overmap terrain representing a house, it returns "house_north" (no basement) or "house_base_north" (with basement) randomly.

The code later (in `overmap::generate_sub`) adds a "basement" terrain under the houses with a basement.

**Comment by vache** [comment]
Houses with type "house_base" tell the game to place a basement under the house.  When placing houses, the game selects about an even mix between houses with and without basements. Right now I think all the basements are hard coded in mapgen or mapgen_functions, and there exists no method to ensure a house always spawns with a given basement except for the special system, which doesn't spawn in town currently

**Comment by Snaaty** [comment]
I can't seem to find the said code in mapgen.cpp, are you sure it's there?

**Comment by KA101** [comment]
>all the basements are hard coded in mapgen or mapgen_functions

mapgen_functions.cpp is the way to go.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.

**Comment by Leland** [comment]
Closing in favor of #15914 which more succinctly describes the issue.
