### ISSUE TITLE
Clothing role mechanic discussion

### ISSUE THREAD

**Issue by Shoes01** [CleverRaven/Cataclysm-DDA#10679]
So, I found these interesting articles:
 - http://cradpdf.drdc-rddc.gc.ca/PDFS/zba6/p144967.pdf
 - http://en.wikipedia.org/wiki/Thermal_comfort#Factors_influencing_thermal_comfort
  - http://en.wikipedia.org/wiki/Clothing_insulation

I have been meaning to ensure that our clothing warmth system accurately reflects reality. In reality, what happens is that you have 3 layers of clothing; (1) an inside layer that absorbs sweat. (2) an outer layer that protects from wind. (3) a layer between the last two that allows you to build up warm air. If you're missing layer 1, you're sweating. If you're missing layer 2, you're touching your outer layer which is cold. If you're missing layer 3, you're unable to build up warmth.

Our system isn't bad; clothing that is made from plastic/leather/etc blocks wind very well; it's our (2), however there is no penalty for wearing an outer layer with no middle layer. Anything made from cotton/wool would then be our (3), but needs to be nerfed hard. At the moment, you could wear three layers of cotton and block as much wind as a wind breaker. We don't have a (1) layer.

So changes I propose are the following.
  - Nerf cotton/wool wind resistance hard. (easy)
  - Nerf warmth values of certain "wind breaker" items (some items, like a winter coat or other down filled items, work as their own (2) and (3) layers. (easy)
  - Create a need for a (1) layer. (???)

That last point is where a discussion needs to take place. Here are my thoughts on the (1) layer:
  - This is an opportunity to create a hygiene system; your inner clothing can get dirty and create scent and morale problems.
  - Body wetness is already tracked per body part, this might be able to be used to track sweat... and it already affects body warmth in regards to wind. Code could be added to increase rate of heat exchange due to being wet.

I feel like there's potential here, but I feel like my two ideas might sacrifice fun in the name of reality. 

I would love to hear your thoughts!

**Comment by i2amroy** [comment]
Hygiene as usually gets a big "ehhhh....." from me, but yeah, dampness sounds like a definite good idea.

That said keep in mind that sweat amounts are kinda dependent on the person as well. Personally I never really need an inner layer since I don't sweat like, ever, so the need to wick away moisture isn't really that important (assuming my outer layer is stopping the rain). On the other hand I know people that freeze without an inner layer, since they sweat buckets the instant they start to do any sort of work. Just something to keep in mind.

**Comment by kevingranade** [comment]
Not really, we're going to model the median, and people are going to have
to deal with it not necessarily working like they're used to.

**Comment by Stretop** [comment]
I feel obligated to remind you all that in this "realistic" game we have mutagens and CBMs. And lizards do not sweat. And birds do not sweat. And insects, spiders and plants do not sweat. And slimes, fish and cephalopods do not sweat - they excrete slime. And survivors with armor-plated bodies or Internal Climate Control most probably do not sweat. Are you going to account for this too?

Also, for furry mutants their own fur should be that "first, inside layer". Are you going to track dampness of something that is not even equipment per se?

**Comment by QuantumInvictus** [comment]
Stretop brings up an important point, I feel - fur, feather, bark, and scales would all complicate things immensely, especially when one considers the currently piecemeal mutation system. For instance, dogs don't sweat - they pant. If we tie the body temperature system into this new sweating system (which I can't see any way of avoiding), then that means the player always need some way to get rid of their body heat. As a base human this means sweating, but if one has a mutation which prevents them from sweating and lacks one that gives them another way to dissipate body heat quickly, then they'll be in a great deal of trouble.

In most cases, I operate on the assumption that mutations gives one whatever required secondary superpowers - to borrow a term from TVTropes - they need to not be inherently fatal when that is not the goal (e.g. mutations that change your anatomy in drastic ways would also give you a circulatory system that can handle the changes adequately). Here, however, these secondary aspects would be pretty much mutations in their own right - birds dissipate heat through their bills, but that is a very major change, and a specific one at that. Dogs pant, but their anatomy (specifically their snouts and long tongues) makes it far more efficient than it is for a human. Even those birds that radiate heat from their skin do so more efficiently than humans, due to having body temperatures that would be fatal or at least severely debilitating to us.

And then there's the problem of having multiple heat-dispersion mechanisms. If the player gets a bill, yet can still sweat perfectly fine, how much do they sweat? Off the top of my head, I could think of a couple possibilities:
1) The bill dissipates all the heat it can, while the player sweats the rest away. This doesn't make a whole lot of sense in the first place, and furthermore implies that just a bill wouldn't be enough to cool a player down. This has the potential, as I mentioned above, to turn a number of currently innocuous mutations deadly.
2) The body tries to distribute heat equally between them, giving half of the body's heat to the bill and sweating off the other half. This also doesn't make much sense in the first place, though is probably the most workable of these possibilities.
3) The two systems have equal portions of their "capacities" used, where half the bill's heat-dispersion-capacity is used, and half of one's ability to sweat heat away is used. This one's a bit more complicated, but the idea would be for each heat dispersion system to have defined with it a maximum "rate" at which it could disperse heat, and these capacities are used equally. The problem with this is that it would only differ from the second possibility if different systems had different capabilities to disperse heat which, while significantly more realistic (in reality, a human-sized bill could not disperse one's body heat anywhere near as well as full-body sweating), would share the first possibility's problem of turning innocuous mutations deadly.
None of these strike me as being particularly workable, except perhaps the second, and then only with very careful balancing - warm, mutation-fitting garb is not exactly common, and having a bill on your face would necessitate something to keep it warm so you don't just freeze to death.

**Comment by Stretop** [comment]
"these secondary aspects would be pretty much mutations in their own right "
"And then there's the problem of having multiple heat-dispersion mechanisms."

Well, I can offer simplier solution - add some significance to thresholds.

Currently as long as survivor is essentially human, all mutations are considered superficial. So let's give the whole mutation-category-appropriate heat regulation system to survivor right when he passes mutation threshold and stops being human.

This would allow us to avoid all "mixed heat regulation system" problems.

However, this method presents some problems on its own: what are heat regulation systems of chimera? Or elf? Or alpha-human? Or medical?

As for getting pre-threshold beaks - well, you can have "Reptilian Eyes" without "Reptilian IR" and "Feline Eyes" without "Feline vision". Same story here.

**Comment by QuantumInvictus** [comment]
So then a beak would only be for show, pre-threshold? I suppose that makes some amount of sense. It'd be there, just not integrated with one's systems - "inactive", in a way.

But that solves only half the problem - currently, most skin mutations are pre-threshold, such as scales, bark, and (if memory serves), feathers. It's kind of hard to imagine how one can sweat through scales pre-threshold, but not post-threshold.

Even more important of a factor is internal consistency - many mutations, like I said above, outright ignore any required secondary superpowers (again to borrow a term from TVTropes) they might need, leading one to assume that such is simply taken care of, like Superman and his inertial dampening. One doesn't ever need to worry about the skeletal/muscular problems a prehensile tail poses, nor about the strain of pumping blood through their newly-acquired tentacles. This is especially evident when it comes to the slime category, since a number of those mutations are... strange, to put it lightly. The reason this poses a problem for consistency is that even superficial changes have significant consequences we must account for - even a very small change, such as being covered in paint, can be very dangerous due to not allowing one to dissipate heat fast enough, and something like scales or feathers would be even worse. So long as we ignore how one gets rid of heat, we don't need to worry about all the rest of this stuff. As soon as we make the character need to get rid of heat in a specific way that affects the world around it, however, we have to account for it all, simply maintain internal consistency and plausibility.

**Comment by KA101** [comment]
And that's why some (but by no means all) effects take multiple mutations, since they require internal changes.

I'm in favor of presuming heat-exchange is included in mutations that would require it, though I'm not sold on the need for sweating either.  Much of this aspect of DDA runs on B-movie science, and that's how we like it.

**Comment by Stretop** [comment]
"It's kind of hard to imagine how one can sweat through scales pre-threshold, but not post-threshold."

Hard? Actually... Not at all: pangolins (https://en.wikipedia.org/wiki/Pangolin) can sweat all right. And fish can excrete slime as well. Sweating is more about presence or absence of skin glands (lizards and birds do not have them) than presence or absence of scales. 

So when survivor passes appropriate threshold - it is not about his scales changing, it is about his skin glands atrophying as his body switches from one type of heat regulation to another.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
