### ISSUE TITLE
Show (and enforce?) layers in armor sorting.

### ISSUE THREAD

**Issue by narc0tiq** [CleverRaven/Cataclysm-DDA#10701]
When the [+] screen was added, layers weren't a thing yet, and now it's become fairly normal to put your underwear on the outside of your pants (while still getting the skintight layer bonus from them).

Similarly, it's fairly hard to tell currently which of multiple layers on a given body part is being over-layered to the point of getting an encumbrance malus.

I propose that both of these issues can be fixed if:
- layers are enforced on armor sorting (so all skintight clothes always go first, all normal go second, etc.); and
- the [+]armor sorting screen was able to display the layers, perhaps as groups with (non-selectable) headers.

At that point, it becomes almost trivial to flip to your torso display and notice that you have **three** bras on your skintight layer, finally explaining where that 0+1 torso encumbrance was coming from.
##

**Comment by kevingranade** [comment]
I was against this previously, but now that there are in-game effects for
layering things a certain way, enforcing it makes sense.
There's another option, which is removing the layering bonus if the article
is in an invalid location.
Also we can just default to placing an article appropriately when worn, and
if you don't mess with the ordering manually it will stay in the right
layer.

**Comment by Rivet-the-Zombie** [comment]
>There's another option, which is removing the layering bonus if the article is in an invalid location.
Also we can just default to placing an article appropriately when worn, and if you don't mess with the ordering manually it will stay in the right layer.

I like both of these ideas a **lot**.

**Comment by QuantumInvictus** [comment]
I have an issue I would like to raise here - a lot of activatable apparel is worn on the outer layers, which would mean under the current system that they would be further down the main inventory list. Being able to order things as one wishes allows one to have the keybindings for these things right in front of them when they open their inventory screen, which is very convenient. As such, I would recommend that if this is implemented then the ability to reorder the "master" clothing list independently from the body-part-specific ones should also be implemented, in order to have the best of both worlds.

**Comment by Griffinhart** [comment]
>Being able to order things as one wishes allows one to have the keybindings for these things right in front of them when they open their inventory screen

Does reassigning hotkeys (default keybind `=`, if memory serves) not solve this problem already?

**Comment by narc0tiq** [comment]
@kevingranade 
> [...] removing the layering bonus if the article is in an invalid location.

Yeah, I like that. The only question is how would one make it obvious to the player that the layering bonus isn't applying, and perhaps hint how to fix it?

--

@Griffinhart 
> reassigning hotkeys

It's not about setting the keybinds, it's about being able to see what they are without ~~scrolling~~ paging through the list.

--

@QuantumInvictus 

Regarding activatable clothing, I would propose two changes:

- float activatable clothing to the top of the list (or color it? bold it? all three?); and
- filter the worn items when the main inventory listing is filtered.

To expand on the second point, note that when you press the [a]ctivate key, the inventory is filtered to show only activatable items (similar filters work for the [E]at, [R]ead, and [W]ear actions). This filter does not currently apply to the worn items list, whereas having it do so would allow for very quickly finding only activatable clothing.

**Comment by kevingranade** [comment]
> Yeah, I like that. The only question is how would one make it obvious to the player that the layering bonus isn't applying, and perhaps hint how to fix it?

Color coding, display a message about, "article of clothing is more encumbering than it would be if it were on it's correct layer"?

**Comment by jbytheway** [comment]
With #26017, we are now in the position that players who do not manually rearrange their clothing will never have layers out-of-order.  So at this point it seems reasonable to introduce penalties for having unusual clothing ordering.

I propose the following, which I claim is simple and should dissuade strange ordering without forbidding it entirely:

When counting how many items are in a particular layer for the purpose of the stacking penalty, count not only the items of that layer, but also any items outside of them which would normally be inside of them.

For example, suppose a character is wearing (innermost-first): shirt, jacket, backpack, shirt.  Both shirts count towards the regular layer as happens currently.  The second shirt also counts towards the outer and strapped layers because it is outside of items in those layers but would normally be inside.  Thus, we count two items in each of three layers and the total stacking penalty is 2+2+2=6 encumbrance (rather than the current 2).

There remains the question of how best to communicate what's going on in the UI.

**Comment by kevingranade** [comment]
The penalty sounds reasonable, as for ui, how about highlighting out-of-layer clothes in the sorting menu to draw attention to them?

In general I'm thinking that giving layering feedback just in the armor layering menu is reasonable, since that's the only place they can get out of order.
