### ISSUE TITLE
adding "square font" checkbox in the options menu.

### ISSUE THREAD

**Issue by FireCrow1973** [CleverRaven/Cataclysm-DDA#10706]
I prefer to play with square pixels, that means having to go to /data/fontdata.json
and change the values.

would be better to have a check-box in the options menu.
##

**Comment by stormsson** [comment]
I must say that editing that file is quite difficult, i had to do a lot of trial and error to get the sizes i wanted: i am playing on a television,therefore having the correct sizes was mandatory, otherwise everything was unreadable.

What about having some different  json configuration examples in a folder instead ? 
so that changing the sizes is just a matter of replacing / renaming the file ?

**Comment by FireCrow1973** [comment]
i wanted that from the beginning to, but i figured id see if anyone else was interested.

i guess giving a aspect ratio "box" or sliders would give more precise options.
i think it should be called "pixel aspect"

**Comment by narc0tiq** [comment]
It helps to use the right terminology: this has nothing to do with pixels,
except in as much as you want your glyphs (characters of type of a given
font) to be displayed in a grid with square-shaped cells whose sizes are
given in pixels.

To that end, I would point out that different fonts have different draw
sizes when asked for, say "font size 12" -- one font may fill a 16x16 pixel
cell (or even overfill it), while another might only fill half of it. While
a config option could easily just force the cells to be square-sized (i.e.
by picking the largest of "fontwidth" and "fontheight", and using that for
both), this is not usually what players seem to want. For myself, I will
only say that while this: <http://i.imgur.com/Wz0BPtG.png> seems to look
all right, I am rather displeased with how much of my window I am giving up
to the sidebar (and it's even worse with the wide sidebar: <
http://i.imgur.com/mwKHXU7.png>).

--

I'd also like more information about the difficulty in editing
config/fonts.json -- the possible stumbling block that comes to mind is the
fact that you are effectively configuring two different things: the width
and height of each cell of the terminal grid, and the font and requested
font size to be rendered inside those cells.

To wit, as long as "fontwidth" and "fontheight" both refer to the same
number, you have square grid cells by definition. The only parameters
remaining are the font and its size, needing to be adjusted such that the
font fills as much of the cell as you desire, presumably without being so
large the glyphs get clipped.

This can be done in a few instances of trial and error, needing only to
adjust the values and restart the game -- the main menu is rendered using
the same method, so by ensuring the main menu looks correct, you can be
assured it will look correct in-game, as well.

**Comment by stormsson** [comment]
@narc0tiq  Well, it's not a practical difficulty: i am actually a VERY newbie in cataclysm world, and the file contains actually 3 configurations ( i must use memory because i don't have the game here)
one is the map configuration, one is the game window and one the menu (unsure of this one).
So this first, when not knowing what you'll find ahead is a bit of a grey area.

for each configuration 3 parameters are necessary: the "font size" is the less intuitive one, because as you said a certain font can fill a 16x16 square where another doesn't, and this causes a second grey area.

Since i didn't find a real explanation on how to edit those file to achieve what i wanted ( basically speaking: "a font that i could read from a television while staying on the couch 3 meters away" ) i needed to try a lot of proportions and combinations to achieve that, by doing exactly what you said: but i really used at least 1,5 hours to configure everything as i wanted because i had to check at every restart

**Comment by narc0tiq** [comment]
Well, uh, there's really no better way to do it within these limitations --
presets that work for one person won't usually work for another. Asking a
member of the general public to mess around with files like this is already
a recipe for disaster.

The best we could do is bring those settings into a graphical interface
(ideally with some kind of preview!), which seems to me like it would help
a lot more than a checkbox or set of presets of uncertain value.

**Comment by kevingranade** [comment]
I think it would be a little better yet to have a square font (and perhaps a few other alternatives) packaged with the game and have that be selectable in the game.

**Comment by FireCrow1973** [comment]
a nice graphic way of editing, and a square font would be peachy!
perhaps a narrower side-bar would also be in order.

**Comment by KA101** [comment]
>perhaps a narrower side-bar would also be in order. 

We have enough problems fitting everything in as is!  :-(

**Comment by FireCrow1973** [comment]
@KA101 yes i suppose its is quite compact, how about adding different modes.
easily switching mods with Tab or something.
i don't  need to see the "action log" all the time, one of these modes could be only the stats at the top, using the space taken by the log at the bottom.
it would be super slim!

**Comment by kevingranade** [comment]
There are already different modes, and they're a huge pain in the ass to
maintain already without adding more variants.  If you're messing with font
sizes already, you can set the sidebar and map to use different fonts or
font sizes.

**Comment by FireCrow1973** [comment]
@kevingranade so you don't like my idea of a semi transparent side bar overlay with scrolling text??? ;-)

**Comment by BFG1992** [comment]
I think it would be the best to make map and game in square fonts, and menus and sidebar in normal. Because text in squared Terminus - with awfully big spaces between letters - isn't nice looking and harder to read.
But I think that would be impossible in Curses :(

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
