### ISSUE TITLE
Confusing Arrow Recipes

### ISSUE THREAD

**Issue by vache** [CleverRaven/Cataclysm-DDA#10733]
Since the unfletched arrows are no longer fireable, the arrow recipes should be changed from a multistage process to just one recipe of "stick + arrowhead material + fletching", instead of the two step "stick + arrowhead" then "half arrow + fletching"

**Comment by Chaz-Moth** [comment]
Agreed here, the current recipe for making arrows is a bit obtuse, and lead to a lot of confusion and frustration in the IRC when I tried to explain that a Field Point Arrow was not the full arrow, and needed to be made into a Fletched Field Point Arrow to be usable.

Changing the recipes so that you create the arrow shafts and fletching and then create a full arrow from there may make the process less confusing

**Comment by bpwatts** [comment]
What these two find gentleusers said ^^

**Comment by KA101** [comment]
I'm open to either a name-change PR or a recipe-redesign.

**Comment by kevingranade** [comment]
Addressed by #10737
