### ISSUE TITLE
Thin walls.

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#10863]
I'm mulling over an idea derived from something Llamageddon brought up in reference to handling rotated walls a while back.  The suggestion was to have two separate wall checks per vehicle tile instead of one to try and catch open corners created by vehicle rotation.  I'm not sure that will do what we want with respect to that problem, but it got me thinking.

This is a semi-crazy idea, I'm probably not going to work on it any time soon, and I'm not sure whether it's a good idea or not, but I wanted to put it down somewhere

If we tracked LOS blockage not at the center of tiles, but rather at the sides, there would be some interesting effects.
First, current walls would be essentially unchanged.  They would effectively have an opaque border on each side of the square, and we'd use the current system where the game draws the glyph or tile of the terrain that blocks sight, so the walls are visible.
What would be changed is it would allow for new directional walls, which only block vision along one to three borders of their square.  Much like walls that occupy a square, when you see one it would draw a wall glyph or tile to indicate what is blocking your vision, but unlike solid walls, the location where that glyph/tile is drawn changes based on where you view the wall from.
A simple example:

```
%%%####  #%%####  #####%%  #####%%  #####%%
#%%#..#  #.%#..#  #...#%#  #...#%%  #...#%%
#.%#..#  #..#..#  #...#.#  #...#.#  #...#%#
#....@#  #...@.#  #..@..#  #.@...#  #@....#
#.....#  #.....#  #.....#  #.....#  #.....#
#.....#  #.....#  #.....#  #.....#  #.....#
#######  #######  #######  #######  #######
```

The room is unchanged, as the player walks past the thin wall it "flips" to it's new apparent orientation.  The '%' symbol shows shadowed areas.

Implementation-wise, it's pretty straightforward, we would use two different arrays to encode sight blocking, one for horizontal rays and one for vertical ones, and each entry would represent the sum of the opacity of the bordering tiles (or the average, it doesn't matter which).  As we traverse through an area, we'd check these arrays as we cross from tile to tile instead of the current array that matches the map layout.  For monsters that's all there is to it, they don't care why sight is blocked, just that it is.  For players we'd need to just mark tiles so they derive their glyph from the wall that blocked sight rather than the glyph indicating open space.

Probably the worst hit is mapgen, we'd need tile types that encode all the usual data, and also enumerate which directions they block sight in (including "none" and "all", there are I think 16 combinations).

May go without saying, but this would also apply to vehicles, allowing for more compact ones, say 2 squares wide instead of 4 for a typical car.  IMO this is the biggest payoff, and might be the only place it would be worthwhile to implement.
##

**Comment by Rivet-the-Zombie** [comment]
Looks like it might be spatially confusing from the player side.

**Comment by DavidKeaton** [comment]
How so? This seems to emulate light casting better than it is currently. Not only that, not everything in RL is aligned in perfect squares, thus giving greater dimension due to LOS blockage. Given all sides are taken into account, it seems coding the behaviour for diagonal movement would then be able to differentiate "legal" diagonal movements.

**Comment by Rivet-the-Zombie** [comment]
I'm thinking it would take some serious getting used to, as I don't think I've ever seen such a thing in a RL before, and some folks might mistake it for a bug when walls appear to move.

**Comment by KA101** [comment]
Yeah, seeing the wall tile appear to jump is gonna be disconcerting.  I'm thinking this will generate a LOT of player confusion.  Where *exactly* is your wall/vehicle?  (Even if this doesn't apply to the vehicle-construction screen, it'll still throw folks off.)

I'm not sure this is worth the implementation work and player learning curve.  Sorry, Kevin.

**Comment by DavidKeaton** [comment]
I see what you are referring to now. My apologies. :-)

**Comment by Shoes01** [comment]
I like this idea, I think it would be a great way to have narrow dividers, but I agree it would be weird to _show_ it. If there would be way to like ... spread apart the glyphs a bit to make room... or having a "  |" glyph adjacent to a "|  " that the player would be able to walk on ... but that would require being able to print two glyphs on one tile, the "@" and the "  |".

**Comment by KA101** [comment]
Unless you have them alternate, nope, one glyph per tile is it.  Blinking @ / | might be a bit much.

**Comment by DavidKeaton** [comment]
This still seems applicable even if we ditch the thin walls part. Would still add a benefit to LOS stuffs.

**Comment by Xynon7** [comment]
What if you had an option to use different tiles from different viewpoints?

**Comment by i2amroy** [comment]
I think thin walls would be a great thing to have, but we'd need some easy way to display it that doesn't involve dancing walls IMO, which would be the hard thing to do terminal wise.

**Comment by werkritter** [comment]
What about connecting the ideas of Shoes01 and Kevin? So, instead of using "#", [Block elements](http://en.wikipedia.org/wiki/Block_Elements) could be used. Here's Kevin's example with block symbols for "moving" walls:

```
%%%####  #%%####  #####%%  #####%%  #####%%
#%%▕..#  #.%▕..#  #...▏%#  #...▏%%  #...▏%%
#.%▕..#  #..▕..#  #...▏.#  #...▏.#  #...▏%#
#....@#  #...@.#  #..@..#  #.@...#  #@....#
#.....#  #.....#  #.....#  #.....#  #.....#
#.....#  #.....#  #.....#  #.....#  #.....#
#######  #######  #######  #######  #######
```

I think it doesn't look too confusing.

**Comment by narc0tiq** [comment]
That does look better, and [poking around with Google](http://www.alanwood.net/unicode/block_elements.html) (because the wikipedia listing didn't show it clearly enough for me), we have all four of the critically necessary orientations:
- `.▏.` -- Left one-eighth
- `.▕.` -- Right one-eighth
- `.▔.` -- Upper one-eighth
- `.▁.` -- Lower one-eighth

The only problem I see is no composites -- the corners would probably be good to have, and I don't see them. If we can live without them, though, so much the better.

I'm also wondering about how the interface to doing this on vehicles would work: where does the player install the thin wall so that it shows up between the correct two tiles? And how do we display it in the vehicle interface, which has omni-vision? Relative to the selected tile?

**Comment by KA101** [comment]
Oops, lower one-eighth comes up as no-character here.  Presuming Terminus, Square, etc would have that?

**Comment by DavidKeaton** [comment]
Odd, it's basically an under score lol (albeit it's raw character code isn't)

**Comment by DavidKeaton** [comment]
I like your examples narc, you make a lot of orientation issues sorta... fixed.

**Comment by DavidKeaton** [comment]
Also, you could sorta fake corners with the other fractions, make it seem like the wall cuts of midtile.

**Comment by kevingranade** [comment]
Yea, it does make building walls and building vehicles a bit more
complicated, I assume we could just install one wall component at a time,
selecting square then orientation.  Slightly more tedium for some squares,
but fewer squares to install to in total.

**Comment by narc0tiq** [comment]
Fonts have variable support for non-word glyphs (and our copy of Terminus doesn't have any of the block characters). That'll have to be dealt with somehow.

I poked around with this corner setup, and it gave me one position where a wall just disappears:

```
#####%%  ####%%%  ###%%%%  #%%####  %%%####
#...▏%%  #...%%%  #..%%%#  #.%▕..#  %%%▕..#
#.@.▏%%  #..▁▏%#  #..▁▏.#  #..▕..#  %%%▕@.#
#..▔%%%  #.@...#  #..@..#  #...@.#  %%%▔..#
#...%%%  #.....#  #.....#  #.....#  %%%%..#
#....%%  #.....#  #.....#  #.....#  %%%...#
#####%%  #######  #######  #######  %%%####
```

At position 4, the horizontal wall would have to draw in the same tile as the lower vertical wall. Otherwise I think it works okay (though note my line-of-sight approximation might not be terribly good).

**Comment by DavidKeaton** [comment]
The dynamics this would add (and require lots of changes for) would be amazing.

**Comment by Shoes01** [comment]
Could we use a custom font, Terminus-DDA, or would that require installing the game plus the font^

**Comment by KA101** [comment]
We already ship it with the game, so a new font wouldn't be a dealbreaker.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
