### ISSUE TITLE
directed explosions?

### ISSUE THREAD

**Issue by esavier** [CleverRaven/Cataclysm-DDA#11014]
Currently game code do not support it (no flags or behavior). This is only idea to consider, but why don't create some kind of direction charges? I am talking about breach charges to take care of precisely one segment of wall ( or double wall if its thicker - especially metal wals) or even combat oriented charges or traps (like claymore mine) that could spray fragments on  enemies in chosen direction leaving other things ( presumably you? ) relatively safe
##

**Comment by kevingranade** [comment]
Claymores for base defense would also be great, it's on my list to add but
never got around to it.
The two tricky parts are giving it a direction when you plant it and
storing that direction, traps don't have anywhere to stash metadata, they
just have their identity as a trap of a particular kind.

**Comment by DavidKeaton** [comment]
Could add it to the itype unique_ptr islot stuff?

**Comment by Barhandar** [comment]
Does adding trap direction mean things like spear-walls, which you can't pass without a chance of damage from one side, but can walk over freely from the others, will become possible?

**Comment by Esavier** [comment]
those and a lot more :) Imagine piston walls, spear traps, shotgun traps, explosive traps, claymore mines, blade traps and a lot more :feelsgood:

**Comment by KA101** [comment]
This would also work admirably for LAW rockets and other HEAT shells.

**Comment by Barhandar** [comment]
>This would also work admirably for LAW rockets and other HEAT shells.

Uncanny Dodging tankbot projectile by stepping next to it because it'll explode the other way? Sure, I'm all for it.

**Comment by KA101** [comment]
>Uncanny Dodging tankbot projectile by stepping next to it because it'll explode the other way?

Probably would still get some shrapnel, but more or less.

**Comment by Griffinhart** [comment]
>they just have their identity as a trap of a particular kind

You could possibly fake directed claymores by having multiple claymore trap types (e.g. in the same way CDDA obfuscates good/bad mushrooms by making them identical in every way except under the hood).

Visually differentiating them would be difficult though (e.g. in case you want to denote facing). You can get the four cardinals with `^`, `v`, `<`, and `>`, but I'm not sure what glyphs would be appropriate for diagonals.

**Comment by kevingranade** [comment]
Yes, we could add 8 different traps for each directional trap type, which
kind of sucks, but it might suck less than bolting things onto the submap
that aren't really necessary.  We could hide that though by putting the
logic to create the directional versions in the json loader for trap types.
I'm not sure different glyphs are called for, the description could
indicate the direction, an you just need to examine a trap to tell which
way it's facing.

**Comment by Barhandar** [comment]
>the description could indicate the direction, an you just need to examine a trap to tell which way it's facing.

Only works for claymores and is guaranteed to generate YASDs by walking up to it from the wrong side.

**Comment by kevingranade** [comment]
I don't understand why it would only work for claymores, or how it's any
more likely to kill you (the warning for stepping on a trap you know is
there should still apply, for one thing).

**Comment by DavidKeaton** [comment]
And for that you could just a flag to the tile, non?

**Comment by Rivet-the-Zombie** [comment]
Remember, the back side of a claymore explosive charge is still incredibly dangerous. That back-blast is why they warn you to affix them to a tree or other obstacle.

**Comment by DavidKeaton** [comment]
Ah interesting. I knew it was an issue with rocket-propelled weapons, but not a coned anti-personnel mine. Good to know! :-)

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
