### ISSUE TITLE
Subsonic Rounds

### ISSUE THREAD

**Issue by Nerezza** [CleverRaven/Cataclysm-DDA#11024]
I'm moving a suggestion from the forums to here, because I feel Github would be a better home for it:

[Copy/pasta ahead:]
First off, I found an M1911 yesterday, to replace a .45 revolver I couldn't suppress and a .22 Mosquito that was quieter than a pin drop but incredibly weak. I was pretty excited because the .45 ACP I had for the M1911 is a subsonic ammunition, and with a suppressor on the gun I should've been looking at a nice and quiet zombie slaughterer!

Nope, just as 'Bang!' as a .308 even with the suppressor on. It kinda made me feel a little sad inside, but I'm well aware that sound is based off of damage output for the gun. However, I think this early in development I might be able to propose a workaround that would keep this 'automated' system for generating balanced sound output and allow things like subsonic rounds to exist!

Applying a sound modifier to the round itself, is my suggestion. Subsonic rounds don't have a report in flight as they don't break the sound barrier, so the only noise is the impact it makes and the gasses escaping the gun. This can be reflected by applying a '-x sound' stat via a 'SUBSONIC_ROUND' flag or something similar to the round, and working that bonus into the same code used for the suppressor functions.

Yes, this would change the balance of ammo types, but I searched both "real" and "balance" in the C:DDA Design Outline and Real wins 21:1. I believe introducing subsonics to the ammunition would definitely fit the design outline's plan for reality-based simulation.
[!copy/pasta]

Original thread: http://smf.cataclysmdda.com/index.php?topic=9122.0
##

**Comment by kevingranade** [comment]
As best as I can tell from what I've read on the subject, the magnitude of
the sounds from the gun report and the crack from the bullet in flight are
similar.
As such I could see adding a 'subsonic' flag to ammo (if that makes sense,
is some ammo subsonic in some guns and supersonic in others?) That has a
similar effect as a noise suppressor, but it only kicks in if the round is
subsonic and the gun has a suppressor.  Alternately split the effect of
subsonic and having a suppressor, possibly with a larger effect if you have
both.

**Comment by Nerezza** [comment]
Subsonic rounds are made based off of how much - please excuse me, I'm not savvy with the terms I should be using for this - powder is put into them, making them fly slower.

Basically, no matter what gun you put the rounds into, these rounds fly under the speed of sound. It might be a good idea to see if Youtube has a few videos of suppressed and unsuppressed .45 ACP rounds being fired. I'm on a 3G connection at the moment, so I can't pull any up myself.

**Comment by kevingranade** [comment]
Youtube videos of people firing guns tells me next to nothing about the
actual sound levels.

**Comment by Nerezza** [comment]
Hmm, yeah, I suppose I shouldn't have expected random Youtube videos to be useful. My bad!
Wikipedia has some decent articles I think, if you're willing to look into them. The .45 ACP would probably be a good starting point. In a bit, I can try to dig up some articles (not from Wikipedia) to link to on the OP

**Comment by Midaychi** [comment]
I dunno. Seems like it might be better to stop focusing on the nits between the guns and just make one function of the ai for handling silenced weapons. 

Maybe make firing un-silenced and silenced guns produce a light flash depending on the damage, and have silenced weapons drop the distance the sound travels? 

Then have the target ai have a chance to mis-interpret the direction the sound came from in a radian arc depending on the damage and distance if the gun was silenced but not fired in visual range? 

My reasoning: a zombie could probably hear most moderate calibre weapons even if they were silenced; The biggest change would be the masking of the noise into a new unfamiliar noise and the extra difficulty in locating the direction of the sound, and possibly a shorter range of the sound to travel. At night even, a silencer might be counter productive vs zombies because it would still produce a flash of light that would allow zombies to see where you were, whereas a flash suppressor would allow you more time to relocate between shots while the zombies were relying mostly on sound.

**Comment by Griffinhart** [comment]
>Youtube videos of people firing guns tells me next to nothing about the actual sound levels.

Actually, they can be very elucidating, even if they don't give you hard numbers.

https://www.youtube.com/watch?v=socgmULGVOA

There is a huge, noticeable difference between the supersonic and  subsonic rounds. Moreover, it also demonstrates one of the issues of using subsonic/cold-load ammo: weapons that rely on the gas pressure of a discharged round to cycle don't cycle so well with subsonic/cold-load ammo.

Additional, relevant wiki article: http://en.wikipedia.org/wiki/Suppressor#Subsonic_ammunition ("[...] .308 subsonic rounds decreased the volume at the muzzle 10 to 12 dB when compared to the same caliber of suppressed supersonic ammunition.")

Also, I don't think you'd need a subsonic flag for ammo; a simple noise modifier variable would serve, and be more flexible as well.

**Comment by mugling** [comment]
> Also, I don't think you'd need a subsonic flag for ammo; a simple noise modifier variable would serve, and be more flexible as well.

This is possible since #15583

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.

**Comment by BorkBorkGoesTheCode** [comment]
I may rework the loudness of .45 ammunition along with others.
