### ISSUE TITLE
rodent explosion in enclosed areas

### ISSUE THREAD

**Issue by nuklearwanze** [CleverRaven/Cataclysm-DDA#1102]
i was staying in my car next to one of those enclosed playgrounds (fences all around) for a couple of days (just reading, eating and sleeping). upon exiting the vehicle i saw that nearly every tile in the playground was occupied by some small animal.
the animals could not excape the playground and stayed in there.
i dont know the code that is responsible for spawning new wildlife - but it seems that there was some kind of hotspot that attracted all those new spawns.
this could of course be considered a feature (breeding of animals for meat).....
##

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
