### ISSUE TITLE
Option to spawn item groups when furniture matches a specified type

### ISSUE THREAD

**Issue by John-Candlebury** [CleverRaven/Cataclysm-DDA#11057]
For an example lets say you are making a large hospital style bedroom, and want beds to spawn with pillows and sheets, and the tables next to them to spawn with assorted medicine.

 Instead of having to add an entry for every bed and table, you could instead just write:

 { "item": "bed", "if_furn": "bed", "chance": 90, "x": [ 0, 23], "y": [ 0, 23] },
 { "item": "drugs", "if_furn": "table", "chance": 50, "x": [ 0, 23], "y": [ 0, 23] },

Would also come handy for rapidly making houses in bulk, instead of having to count tiles to find where you placed dressers ovens beds and fridges, you could simply write the above lines with the appropriate changes.

**Comment by KA101** [comment]
One issue with random-generation is that it's likely to create Chaos: the beds and tables are all over the room rather than set up in rows/columns with a table for each bed.

If I'm reading this right, that's what you're looking for, and it might not work well unless you want to say that the room got in a total mess yet all the sheets/pillows/drugs are neatly in place.

**Comment by John-Candlebury** [comment]
Hmm seems like I didnt wrote it well in that case. The beds and tables would already be placed by the in the normal way, "if_furn" would check only if the given furniture existed in any tile of the specified tile interval, if it does, it proceeds to spawning the items, if it doesn't, it skips the tile and checks for the next one.

It wouldnt actually add furniture to the map.

**Comment by KA101** [comment]
OK, then I wasn't reading it right.  Sorry.  That seems like it'd be a bit easier, I suppose.
