### ISSUE TITLE
Multi-tile Shoggoth

### ISSUE THREAD

**Issue by AlchemistExMachina** [CleverRaven/Cataclysm-DDA#11067]
So I got to thinking, why destroy fungal spires if they don't even try to kill you? Then I thought, shoggoths sure are annoying, eating all your stuff. Also, malls are really cool with different parts for each tile, like food courts and stuff. Since there's not enough endgame content for an OP character, why don't we make an OP boss like a giant shoggoth? It would reproduce like a breather, eat items like a shoggoth, and chase after you with its tentacles. What do you all think?
##

**Comment by Rivet-the-Zombie** [comment]
>why destroy fungal spires if they don't even try to kill you?

It drastically reduces the fungal patch's spawn rate.

**Comment by AlchemistExMachina** [comment]
Well yeah, but it doesn't have any directly adverse effects to you if you don't destroy it. I'm not saying we should replace it, just add something a bit more lethal.

**Comment by Barhandar** [comment]
>Well yeah, but it doesn't have any directly adverse effects to you if you don't destroy it.

A solid carpet of spores and fungaloids isn't an adverse effect now?

**Comment by AlchemistExMachina** [comment]
Okay I'll stop comparing it to a fungal infestation. Still, the point is making a good endgame enemy, not bashing fungus.

**Comment by KA101** [comment]
Shoggoths are probably the best candidate for multitile critter in the game, since they're more or less internally-equivalent Blobs which can change up their configuration (jaw, GI tract, etc) on the fly as needed.

I'm not opposed.

**Comment by kevingranade** [comment]
Same here, Shoggoth is the best option for a multi-tile right now.
Maybe I'll take another crack at making a colony monster (first try was the
brain blob).

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
