### ISSUE TITLE
Mutations and traits are a global list

### ISSUE THREAD

**Issue by narc0tiq** [CleverRaven/Cataclysm-DDA#11143]
So, I just looked into how mutations work and discovered the following (possibly old news to some of you):
- all mutations that can exist are placed in a global `std::map<std::string, trait> traits` (in `src/player.cpp`). This is the only place `trait` objects exist.
- all characters have `list<std::string> my_traits` and `list<std::string> my_mutations`, which are lists of **mutation IDs** -- i.e. references into the global `traits` map.
- when a player activates a mutation, they activate it for **all** characters that have that mutation in the current instance of the game. Technically, this means that if both you and an NPC have, say... Retractable Claws, you both turn them off and on at the exact same time.
- the global list of mutations is never saved (naturally), therefore all mutations will be inactive upon the next load regardless of their current state.
- key assignments to specific mutations are kept in a per-`character` `std::map<std::string, char> trait_keys;`

While this may have made sense when mutations were purely static things with nothing but names, prerequisites, etc., it no longer does.

I propose that the global list of traits should be a list of `mutation_type`s instead. Analogously to `itype`s, you'd keep the static parts of mutations in there, which would allow you to store simpler `mutation` objects in the characters. These `mutation` objects would include the invlet assignment, whether the mutation was currently turned on, and whether it's in cooldown (and for how much longer). Of note, this is also analogous to the bionics implementation.

The benefit of this system is that you could then store the lighter `mutation` objects in the savegame, which I shan't bother enumerating the implications of.

**Comment by kevingranade** [comment]
Yep, sounds like a good idea.  When the system was built there was no state
in mutations at all, and we missed this when they were made active.

**Comment by KA101** [comment]
All yours.

**Comment by BevapDin** [comment]
@KA101 I came across some ... things:

There is `Character::toggle_mutation` (mutation.cpp) which is called for example from iuse (the whole marloss stuff) and it toggles the mutations, but it does not toggle the base trait. That means it would allow one to have base traits X but not mutation X. I though that a base trait means one always has that mutation and it can not be lost. So is it possible to loose a base trait mutation? That means is it possible to have base trait X, but not mutation X?

`player::suffer()`: right at the beginning `trait::cooldown` is reduced, but cooldown is never stored in the save. It is loaded from the json data every time the game is loaded. What does that mean?

Traits and mutations are the same, right? At least from the code perspective, because `load_mutation` creates one entry for each in both `traits` and `mutation_data` for every loaded mutation.

**Comment by KA101** [comment]
OK.
A "trait" is a mutation you started with.  You *can* lose it via mutating, BUT it's on that separate list so if you un-mutate whatever cancelled the trait, you'll get the trait back rather than reverting to (no mutation/trait).

All traits are mutations, but not all mutations are traits: traits have the "starting_trait" set true, or are specifically permitted via start scenario, and then you pick ones to apply to the char at that point.  Chosen traits have the reversion as mentioned above, and are not counted for purposes of mutant-category strength or Threshold breaching.  I'd like to break that out so only traits with "starting_trait" set true (therefore, within normal human genetics) would not be counted towards mutant categorization.

It is possible to have a base trait X but not currently have the mutation X, correct.  This is why we need those separate checks in the mutation-cancellation PR I've had no luck with.

Cooldown is likely not properly implemented: BeigeSand wrote those and I was pleased enough to finally have 'em in that I didn't drill for every possible problem.  It's there to provide an amount of time an active mutation can stay active without paying the active-cost, IIRC, so "duration" might be a better name for it.
