### ISSUE TITLE
Unending corpse smashing

### ISSUE THREAD

**Issue by Mattamue** [CleverRaven/Cataclysm-DDA#11159]
![lol?](http://i.imgur.com/vOLwckf.gif)

Goes quick at the start, but I'm wielding a scabbard and smash the zombie corpse to the west. This is a re-creation. Wielded a scabbard rather than drawing the weapon on accident and smashed a corpse. Smashing went until the corpse stood back up again without finishing.

Glad I recorded this because I can't always get it to repeat. Scabbard seems to be the culprit where a sheath could smash stuff fine.

First time it happened I panicked and couldn't remember that 5 or . stops constant actions. If this isn't a bug could this be a suggestion for an enhancement for a reminder somewhere during constant actions that there's "keybind" to cancel?

**Comment by ejseto** [comment]
Smashing won't work with a weapon that has less than 0 cutting damage. Sheaths have 0 while scabbards have -4. Pulping power is multiplied by sqrt((double)(cut_power + 1)). Although I think it's intended that something that blunt can't pulp corpses (whether it makes sense or not), it would appear the formula doesn't take into account the possibility of negative cutting damage since sqrt isn't defined for negative arguments. Not exactly sure what's happening in this case, but clearly you weren't intended to smash corpses with something that dull just from looking at the formula.

**Comment by KA101** [comment]
Then it needs to specify that and bail out.
