### ISSUE TITLE
Balance: should nail gun and nail rifle require battery or pressure tank?

### ISSUE THREAD

**Issue by pipehat** [CleverRaven/Cataclysm-DDA#11166]
Right now, this magical device launches nails using explosive fairy dust or something. Shouldn't it require a power source to fire?
##

**Comment by Rivet-the-Zombie** [comment]
It could use a UPS, at one charge per shot.

**Comment by Barhandar** [comment]
I agree unless they will be using it for actual crafting as stand-in for hammer - making nailgun kinda useless as a tool (IRL it's used because it's faster - but there's no difference in CDDA). UPS charge or need to repressurize it via requiring similar components to pneumatic rifles (simulated by much longer reload time, perhaps? Until there's a possibility of several ammunition types).

**Comment by Rivet-the-Zombie** [comment]
>need to repressurize it via requiring similar components to pneumatic rifles (simulated by much longer reload time, perhaps?

This is a very good possibility.

**Comment by NaturesWitness** [comment]
My vote would go toward the UPS approach, as it feels more realistic given Cata's setting.  But I also like the idea of having hand-pump pneumatic being an option.

A good solution would be have found nail guns use the UPS system, and have a crafting recipe to add the needed parts to convert them to hand-pump if desired (no UPS needed, but longer reload time needed to pump up pressure).
Bonus points if the "upgraded" model has an iuse function to switch modes when desired.

Ideal, but more complex idea; instead of drawing power every shot, tool has internal air tank that is charged by an integral UPS powered compressor.  When you reload the nails, UPS power is drawn to refill the air tank.  This would be more realistic, running an air compressor on-demand for each shot would be massively inefficient, not to mention illogical, compressors just don't work that way.  It also means we aren't stuck requiring a strict one-to-one air-to-nail ratio.  Maybe 2 or 3 units of UPS charge is enough to fire an entire clip.  Also makes the upgraded hand-pump models much easier to use; instead of some weird mode switching system, we have two reloads.  Standard reload uses UPS to reload, "use item" calls for hand-pump reload; takes longer, but no power needed.

**Comment by ValidAQ** [comment]
Correct me if I'm wrong, but wasn't UPS supposed to be used primary by military? It would be strange if ordinary nail guns required it for operation, in that case.

**Comment by NaturesWitness** [comment]
I'm not really sure at this point.  I think that's what it started as, but as we've been steadily adding more gear that uses it, I think we're sort of moving towards it being more commonplace.

Also, I can't really think of another way to make this work.  Without support for equipment using multiple ammo types simultaneously, RL types of cordless nail guns, like Paslodes, simply aren't possible.  They can't be hand-pump tools by default, such a design would NEVER be practical for actual construction use.  And making them conventional air tools, run with a standing compressor, would render them unusable as trying to make a code base for air hoses and compressors would be an even BIGGER nightmare than the current UPS system, which we only started fixing a few months ago.

**Comment by KA101** [comment]
I don't think we can reliably drain partial-charges from a UPS as they're integers.  Making the drain a one_in could emulate it but would necessarily be unreliable.  So cost-per-shot would be at least 1.

Cost-per-reload might work, though AFAIK we don't actually do that anywhere else in the code.

**Comment by NaturesWitness** [comment]
The problem is we can't make them use batteries, rechargeable or otherwise, because we have no way of making items use multiple types of ammo.
The best scenario would probably be to give them internal rechargable batteries, in addition to being loaded with nails.  But I just assume this kind of functionality would take ages to code, and isn't a high priority.
Absent that, our options are limited.  With our current code, UPS drain is the only way to achieve dual ammo use that I know of.  I was trying to think of a solution that had as little intensive hard-coding as possible.

The only alternative I can think of is to state that all found nail guns are designed to be used with dedicated compressors; ie are completely nonfunctional when found, and must be upgraded via crafting to have a manual air pump before being useful as anything more than a blunt object.

On a related note, it might be worth considering adding the option to have guns use UPS charge on reload.  Even if UPS technology isn't in civilian use, it's very much in survivor use, and it's quite likely survivors would incorporate it into higher-tier crafted weapons.  I can easily picture characters upgrading the existing pneumatic guns to be UPS assisted, and installing UPS-powered cocking mechanisms onto the superheavy crossbows.

**Comment by kevingranade** [comment]
Another option is loading them with .22 blanks, but of course that has the
same problem as the batteries.

**Comment by NaturesWitness** [comment]
Good catch, forgot about percussion nailguns.  Although if we're going to include them, I recommend that they REQUIRE crafting modification before they can be used as a ranged weapon at all.  They should be fairly uncommon as well, as it's not a commonly used tool (Percussion nail guns are specifically designed for putting nails in concrete).

**Comment by aierce** [comment]
Don't make nail gun require UPS, that's coilgun.

this is a game world, there's no point trying to apply real world logic

**Comment by nulman** [comment]
we could just assume (update the description) that the nailgun has a small pneumatic pump attached to it. we already have magic pumps on the spraycan flamethrower, and we can just increase the reloading time to simulate pumping air in. the nail is so low end that adding a little metal tank to simulate a larger air reservoir makes it too hard to make. possibly add a plastic bottle as a component to the rifle.
youtube confirms that a plastic bottle makes a serviceable pressure tank.

**Comment by NaturesWitness** [comment]
On further thought, I think you're right.  The nail gun just isn't powerful enough to justify complicating it with batteries and other stuff.  After all this is a zombie survival game, not a simulator for construction equipment.  The purpose of pneumatic nail guns in RL is speed in performing tasks like framing walls and installing trim, tasks which are not present in our project.  For us, a nail gun is just a peashooter for practicing how to hit the broad side of an evac shelter, or maybe annoying a recalcitrant squirrel.  Let's just add a line to the description saying it has a hand pump for use in remote locations, add a second to the reload time, and call it a day.

**Comment by KA101** [comment]
>performing tasks like framing walls and installing trim

There's no reason we couldn't add drywall panels and do modern US housing.

(Aside from the fact that drywall panels are frickin' large/heavy and couldn't be carried in inventory, period.  Wielded or in a cargo tile.)

**Comment by ejseto** [comment]
>this is a zombie apocalypse world, there's no point trying to apply real world logic

The idea of a zombie apocalypse is not illogical. The zombies are the premise. The apocalypse is what logically follows from that premise. The laws of physics should still be obeyed unless you can reasonably expect them to be violated due to that or related premises, or it's really really un-fun.

I don't see what would be wrong with requiring a few batteries to reload the thing. I also don't see anything wrong with simply making the nail gun non-reloadable. It's not like real ones can just be reloaded with a pile of nails you pulled out of old furniture.

**Comment by Barhandar** [comment]
>I don't see what would be wrong with requiring a few batteries to reload the thing.  I also don't see anything wrong with simply making the nail gun non-reloadable.

Except for the "it's really really un-fun" part, which applies to obeying laws of physics where they shouldn't be as well! Also, see the "cannot have several ammo types in one gun yet".

**Comment by NaturesWitness** [comment]
Yeah, basically the issue is the multi-ammo thing; we just don't have the infrastructure for it yet.  While I'm sure it will get done someday, I doubt it will happen in the near future; our poor devs are overworked as it is.  Once we DO have code support for multi-ammo, this will probably be implemented; if anything, it'll be the proof of concept/test dummy for the feature.

Until then, it probably makes the most sense to give this little plot-hole some spackle in the form of changing the description to say it has a hand-pump or lever-action spring or something.

**Comment by ejseto** [comment]
It could simply require charges to reload. It wouldn't keep track of them as ammo, just a simple check and removal of x charges of batteries upon reload, prorated to the proportion of ammo missing, refunded upon unload (obviously there will be some roundoff error, but that's better than magical fairy dust powered nails). I don't see how it's un-fun to require that, it's not like batteries are particularly hard to find. I don't see why it shouldn't obey the laws of physics. Is there nanite/alien organism/lovecraftian goo inside it?

**Comment by AndrasZodon** [comment]
My thoughts on this is that while it does, somewhat unrealistically, not seem to need any sort of ammo besides magical fairy dust and nails, it is not a good weapon to being with. I think that requiring more than nails and elbow grease to fire it ventures into the domain of "what's the point of using it then?".

**Comment by graysage1** [comment]
I haven't had a desire to make a nail gun in any of my games.  If I want a ranged weapon, throwing and archery are imo better early game options than nail guns.  I see nail guns mostly as flavor curios.  I don't think of "nail gun" when I want to get things done in CDDA.  Nail guns can barely hurt a fly and they're so short ranged.  So what if the ammo is common?  Rocks, pebbles, wood for arrows or throwing sticks, all that is common too.  Just my 2c.

**Comment by Hague** [comment]
You have different kinds of nail guns: percussion cap nail guns and pneumatic pressure release nail guns.

If you want to rewrite the entire pneumatic weapon code so that pressurized atmosphere sources are required  either via attachable canister mods or attachable hoses, that would make it work properly. Clone the vehicular power sources so air-compressors (acting like alternators) turn E-power into Pressurized Air that goes into Tanks then add dolley compressor-tank combos to construction sites and garages. Attach a pneumatic hose to the tank and you can move around and use the pneumatic weapon within a certain distance of the vehicle, move beyond that and you pull the weapon out of your hand or you get prompted to drop the item. Putting it in your inventory disconnects the hose (taking additional time) This is obviously a lot of work.

As for nails in general, pneumatic nail guns aren't loaded individually, they are loaded into coiled belts that are slipped into a drum loaded behind the barrel for roofing or in a magazine-like stick with plastic sabots for spacing and accuracy to hold framing nails (these are likely the ones used in Cataclysm). 

Percussion cap nail gun nails are basically bullets. They use a small powder charge to propel the nail. Since there's already means of manufacturing player bullets, nailgun cartridges should be easy enough to find and unloaded, reloaded like regular ammo. They load in magazines similar to the pneumatic framing guns.

**Comment by Rivet-the-Zombie** [comment]
If we were to add powder actuated nail guns, then they'd have to make some noise (all of them I've ever operated use blank cartridges that look like necked-down .22LR) and possibly do bonus damage - I've used them to drive nails into concrete before.

**Comment by mugling** [comment]
Since this was open we have gained magazines and alternative ammo types. Multiple concurrent types is a goal but currently low priority
