### ISSUE TITLE
Destoyed wooden cart dropped unexpected loot

### ISSUE THREAD

**Issue by CosmicKobal** [CleverRaven/Cataclysm-DDA#11192]
I was chopping down trees, and one fell on my home made cart which is just a simple wooden frame, and a floor trunk. the destroyed cart dropped a few splintered wood bits, 4 or 5 each of scrap metal, lump of steel and steel chunk, and most surprisingly, 700 nails.

Something in that doesn't quite add up. lol

**Comment by Coolthulhu** [comment]
Related to how destroyed aisles with lights, small electric motors and similar parts can spawn hundreds of units of copper wire.

The problem is caused by vehicle system spawning items in stacks of (default_size * number), making it impossible to spawn less than default stack of items. In case of nails, default stack is 100. In case of copper wire, it's 200.

**Comment by Dozed12** [comment]
Is there any good reason to use that system?

**Comment by Coolthulhu** [comment]
Not really, it's probably an oversight.

**Comment by DavidKeaton** [comment]
I was about to say I didn't put a whole lot of copper in aisle lights...
