### ISSUE TITLE
Alpha stat mutations cause permanent stat loss on removal

### ISSUE THREAD

**Issue by Voker57** [CleverRaven/Cataclysm-DDA#11282]
Alpha stat mutations are 'lossy': on addition, if 7 < STR <= 14, STR = 15. And on removal if your STR is 15, it's 8 regardless of previous value.

**Comment by i2amroy** [comment]
Yeah, they've been this way since they were implemented. There isn't really an easy way to "fix" this without adding some extra "stat storage" areas that would be totally useless except in these rare cases.

Personally I'd mark this as a "will not fix", simply because I don't see a good way to do it under the current system.

**Comment by KA101** [comment]
Intended.  Once you get Prime stats, perhaps you shouldn't be messing around with your genetics, hm?
