### ISSUE TITLE
Crash when NPC is hit by zombie

### ISSUE THREAD

**Issue by FredZeppelin** [CleverRaven/Cataclysm-DDA#11286]
I'm using 0.B Brin, on Mac, with tiles, but tried it without and it still crashes.

Basically, when an NPC gets attacked, the game crashes. I have a save game where I can reproduce this problem, and I've had it happen with a different game.

Let me know what I can do to help, logs, debug data, etc...

**Comment by KA101** [comment]
We're quite a ways past 0.B stable--in fat, we're looking at 0.C stable in a month or so--so bug reports from 0.B are outdated and not terribly useful.

That said, since you're on Mac, there's not much you can do in terms of reproducing in latest experimental.  Sorry you have the crash, and here's hoping 0.C clears it up.  :-(

**Comment by FredZeppelin** [comment]
No problem. I'll cross my fingers for it to clear up in 0.C.

**Comment by Rivet-the-Zombie** [comment]
As is often the case, 0.B stable wasn't quite as stable as we'd hoped. If you can play the experimental build, it's always better.

Also, @FredZeppelin wins the award for having the most amusing Github name I've seen all day.
