### ISSUE TITLE
how to convert shallow water to deep. [(not a) bug report]

### ISSUE THREAD

**Issue by jcd000** [CleverRaven/Cataclysm-DDA#11318]
1. Extract clay mound (only possible in shallow water)
2. Break the mound -> Terrain changes to deep water.

Is this WASD?

I mean, sure, when digging into shallow water, it deepens. But this does not happen by just getting ~10 lumps of clay = 10 bricks.

If it's not intended, i'd propose to change it so that there is a chance of the terrain changing to deep water afterwards but not every time we obtain clay.
##

**Comment by KA101** [comment]
Intended, though the chance-to-change is worth considering.

**Comment by Zireael07** [comment]
+1 for chance to change.

**Comment by KA101** [comment]
OK, let's talk about how much of a chance.  I'm thinking one_in 3 or so, but that's a quick guesstimate and open to discussion.

**Comment by kevingranade** [comment]
The question is how much clay you expect to get out of a given area of
random river or creek shore.  I'm not an expert, but imagined that there is
a good bit of sand and such mixed in with the clay, so it's not a matter of
excavating the entire area to a certain depth, but rather extracting the
clay from it.  Also every single shallow water tile is clay-bearing, so
adjust for all the areas that will just be sand and instead have an
'average' amount of clay in each tile.

**Comment by KA101** [comment]
Yeah, I didn't expect to get much out of a given square meter or three, but then I don't routinely go clay-hunting.

**Comment by jcd000** [comment]
Lets etablish first that we are not distinguishing between clays (earthenware vs stoneware)

I'm also not an expert but IRL (to my limited experience) there would be clay-bearing areas that would have significant amounts of clay and non clay-bearing, where one would not try to get clay from (too low concentrations, bad material).

Adding a new terrain (with clay tiles having a small chance to become non-clay at excavation - maybe 1:10) and some mapgen code (converting some shallow waters to clay-bearing) could be a way to implement this correctly.

Another way to do it, consistent with what @kevingranade points out, is having both a small chance to get clay and a small chance to make the tile undiggable (deep water). I slightly dislike this since it would force the player to try again and again in order to get clay from the same tile (some grinding)

Finally, by keeping the current simplistic system, the only balanced way to do this is to give a chance for the tile changing. 1:1 as is now is a bit excessive but 1:3 as @KA101 said sounds reasonable.

**Comment by kevingranade** [comment]
You summed up the approaches nicely, but said nothing about the actual
question, which is how much recoverable clay you expect to find on average,
that is what determines whether 1:1 or 1:3 is reasonable.

**Comment by jcd000** [comment]
I got to say this is why i love talking about cata: It gets so diverse and i always like to learn new stuff.

What i digged is not much (not a geologist sadly):
I could not find figures about local clay areas, most of what follows is about mining clay for mines (where its concentration is big enough) but it may act as a reference.

The following confirms that New England clay was extensively used around 1900
https://brickfrog.wordpress.com/2011/06/13/brick-making-in-new-england-circa-1900/
"Clay deposits from which building bricks are made are found in the neighborhood of the Connecticut River Valley, and extend up the valley from the neighborhood of New Haven over and beyond the Canadian line."

I read some more documents, like http://pubs.usgs.gov/imap/i-2789/i-2789_p.pdf and http://pubs.usgs.gov/bul/0708/report.pdf
but i am a bit lost and i could not find real figures in them. Besides, these are old documents.

I don't know where to go from here on the question of recoverable clay. Maybe someone else knows more?

Either way, it seems incorrect to change the terrain just for taking ~0.5m^3 of clay from it.
Even if this is the max clay to be gotten from that area, the terrain would still stay shallow_water.
For it to change, a lot more dirt would have to be excavated (won't go into 3d cata tile -> m^3 conversions).
Finally, if it does become deep_water, maybe the adjacent dirt/grass tiles should become shallow_water themselves?

**Comment by KA101** [comment]
>taking ~0.5m^3 of clay

That's a handy figure to keep in mind.  Deep water is deep enough to sink stuff, so at least 2m/7ft deep, I'd guess.  Shallow is legs-high, so more like 1 meter/3ft.

So extracting a cubic meter of clay (two extractions) ought to create enough room to deepen the water.  one_in(2) would get pretty close to that whilst not requiring terrain to remember its extraction-status.

As for creating shallow water, I'm not totally opposed but that's a significant game-changer (create moats, channels, etc) and something that deserves its own discussion.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
