### ISSUE TITLE
portable sawmill

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#11341]
I was looking at sawmills (don't judge me) and came across this http://www.northerntool.com/shop/tools/product_200316891_200316891
seems like this would be a good template for taking apart a felled tree into boards.
you can also make planks from logs with an axe, but that wastes more wood, takes longer, and is a much more skilled thing to do.
##

**Comment by KA101** [comment]
Yeah, seems like something that could be a conversion kit for a chainsaw (off) easily enough.

**Comment by Zireael07** [comment]
Great idea!

**Comment by Inkognyto** [comment]
my father has one of these.  He makes log chairs, tables etc for fun.

Add an option for 2 circular saws for this recipe also.   It's basically a double table saw, but multiple would mean your cutting from both sides. You would stagger them probably a blade width apart so you can have like an overlap.

This gives the circular saws another use.

**Comment by nrfowler** [comment]
I will work on this. This will be my first Cataclysm issue. 

My plan is to have the Chainsaw Mill Attachment be a separate item (I'm assuming this is what you mean by conversion kit?).  The Portable Chain Saw Mill will be able to be disassembled into a Chainsaw and a Chainsaw Mill Attachment.

**Comment by kevingranade** [comment]
Yea, that's what I was getting at.  With that in place, we'd probably have
it have higher yields of cutting logs into planks (twoxfours) and operate
significantly faster, and probably have using hand tools directly have
lower yields.

**Comment by nrfowler** [comment]
Having looked into this again, it seems like we would need to add a new Item Quality: Milling. Tree Cutting quality includes chopping down trees, which this can't do, and the Wood Sawing quality also includes things this can't do (at least I assume so. I take wood sawing to be fine cuts to wood, which a chainsaw can't do.) We could have the recipe require either a Milling or Tree Cutting quality, and the Milling Quality is faster.

**Comment by nrfowler** [comment]
@Inkognyto: 
If we go with the Milling quality, basically what you are describing could be called a "improvised band saw." It could take either a chainsaw or two circ. saws as ingredients.
Such a bandsaw would have a small cutting length and would be not as tough as an actual mill. FYI here is an actual logging mill with two circ. saws:

http://www.alibaba.com/product-detail/DC3000-Electric-Double-Circular-Blade-Round_60018903129.html

**Comment by nrfowler** [comment]
@kevingranade
Having looked into this again, it seems like we would need to add a new Item Quality: Milling. Currently it appears that Tree Cutting fells trees and also makes planks, whereas the chainsaw mill could only make planks. We could have the recipe for making planks require either a Milling or Tree Cutting quality, and the Milling Quality is faster.

**Comment by BorkBorkGoesTheCode** [comment]
The game features agriculture, so SAWMILL may be a better name.

**Comment by nrfowler** [comment]
That is probably what I will do. The chainsaw with attachment will be SAWMILL 1, and with [this](http://www.northerntool.com/shop/tools/product_200326312_200326312?cm_mmc=Google-pla&utm_source=Google_PLA&utm_medium=Logging%20%3E%20Saw%20Milling%20%2B%20Accessories&utm_campaign=Granberg&utm_content=11880&gclid=CM7Mkfag7M0CFQ6oaQodmyMHIA) it will be SAWMILL 2.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
