### ISSUE TITLE
Expanding waterways

### ISSUE THREAD

**Issue by KA101** [CleverRaven/Cataclysm-DDA#11340]
jcd000 raised the possibility of clay-extraction causing adjacent tiles to collapse into shallow water in our discussion in #11318.  I think that's an interesting point and being able to thusly expand waterways is a game-changer.

Here's an issue to kick around whether/how we ought to enable folks to convert non-water tiles into water tiles.

**Comment by Zireael07** [comment]
I say yay.

**Comment by kevingranade** [comment]
This has come up several times before, and the problem is if you have a
situation where digging a trench next to water results in a water tile, you
immediately have a problem where the water 'should' fill a pre-dug trench,
which runs into propagation issues like filling the entire trench in one
turn no matter the volume, pushing items/monsters around, extending off the
map, etc.
In other words, it's a can of worms I see little benefit to opening, this
is not DF or minecraft, it's not about building things, it's about survival.

**Comment by jcd000** [comment]
Game mechanics making this problematic makes sense. This is not DF with the map pre-loaded and everything taking place on that map as time passes.

Coding water movement through waterways on the map could be possible though. We could just have any deep pit convert to shallow water over time, the time being dependent on the amount of deep and shallow water tiles directly linked to it. (ommiting the indirectly linked tiles to avoid reality bubble troubles)
The water would eventually reach everything valid inside the bubble, and slowly move when the player causes the bubble to move. (similar to fire limitations)


On the subject of what cata is:
Initially the game is about survival, sure. This is the core of the mecanics and the game's "heart".

But why limit in scope such a free game? (free in the sense that a great many different approaches are possible in the game)

Also, what happens when the player solves his survival needs?
Get bored and restart?
This is why there are frequent talks about the end-game content and partly the cause for so many new constructions being available. Large scale building is mostly end-game content (with much less potential benefit that factions and NPC's, i'll admit -> choosing between the two, i'd prefer NPC's, hands down)

So, i'd support such a thing, if its possible to be implemented with not much trouble/side-effects.

**Comment by kevingranade** [comment]
That's exactly my point, it would be a lot of trouble, and there would be a
lot of side effects.  I'm not against it in principle, it just comes out
poorly in a cost/benefit analysis.

**Comment by KA101** [comment]
Yeah, moats and such would be Nifty but we aren't built on a physics engine.  :-(

**Comment by mugling** [comment]
> it just comes out poorly in a cost/benefit analysis.

No obvious path to resolution
