### ISSUE TITLE
extended spider craft "Rope Webs"

### ISSUE THREAD

**Issue by hunakos57** [CleverRaven/Cataclysm-DDA#11397]
The mutation "Rope Webs" gives the ability to the player to has his own "short rope" supply, that means he can use it in any crafts. The short rope can be disassembled to long strings and the long string can be disassembled to ...etc.

In short, we have this now: long rope <= short rope => long string => short string => thread

The idea is to add more recipes to the player to be able to craft things straight away when he have this mutation to prevent all the disassemble with their "mini freezes" that slow down the gameplay.

For exemple: If I want to make 1 rag I have to create a long rope (because can't get small rope just by itself) turn that into thread (4 disassemble happened) than I can make my 1 rag and l also have a tons of leftovers from it which is annoying.

I think it would be better to give the long string, short string and thread to this supply, IF this mutation "adding and removeing" recipe is problematic.
##

**Comment by KA101** [comment]
I know that I had to short-circuit the construction code to get the original Rope Webs to work, so whilst I'm not totally opposed to your idea, I'm not sure how feasible it'd be to implement.  Sorry.  :-/

**Comment by hunakos57** [comment]
I don't know how to feel about that spinnerets would not give you short rope, because that was the main reason i choose this mutation line, but than when you mentioned the "possible balance issues" I realised that it maybe would be overpowered. 

Hm.... Maybe with spinnerets the player is not able to wear leg cloth and armors or It could slow down the player because of the new big unsupported bodypart,

**Comment by kevingranade** [comment]
Making the player bulkier is one way to balance it (though a contentious
one).  Another is making the hit to hunger very steep.
As for the rationale, I thought we had recipes to skip some of the steps?
That seems like a reasonable-ish thing to do, but I feel liked I'm missing
something.

**Comment by KA101** [comment]
Short rope would be fine, short *strings* is the problem.  The idea is that the webbing is enough to support the PC's weight, so it's not going to be extremely small and easy to work with direct from your spinnerets.  Post-processing needed.

Hunger hit for web-spinning is intentionally low to encourage players to spin webs.  Construction use currently doesn't add any at all.

Thought: Making Rope Webs activatable and drain X nutrition to generate a rope item, rather than automatically handling rope in the code, would solve the cost problem.  Theoretically we could make it a menu for how long the web-rope needs to be and go from there, even.

**Comment by hunakos57** [comment]
What about saying that the spinnerets is a tool that can be used in 5 crafts which is added to the player when he gets the "Rope Webs" mutation. With this method the player can avoid all disassembles and generating leftovers from it, but since it's a craft the "Post-processing" is still there.

The 5 recipes are simple:
-Craft "Long Rope" need: spinnerets + X nutrition 
-Craft "Short Rope" need: spinnerets + X nutrition 
-Craft "Long String" need: spnnerets + cutting tool + X nutrition 
-Craft "Short String" need: spnnerets + cutting tool + X nutrition 
-Craft "Thread" need: spnnerets + cutting tool + X nutrition

**Comment by kevingranade** [comment]
Having the crafting code cross-reference the mutation code, not a fan of
that.  How is that different from the mutation just letting you make them
directly?

**Comment by hunakos57** [comment]
"Rope Webs" still only gives the "Short rope", tool required for Post-processing, length of crafting time (sum of disassemble time). It's like a multipled disassemble without sideproducts and easier to handle.

**Comment by KA101** [comment]
I'm thinking activation is the way to go.  Works OK with vines, "silk rope" can be whipped up post-0.C.

Leastwise once Mozilla and I sort out whatever broke Firefox on the dev machine.  >_<

**Comment by KA101** [comment]
Misclick, my mistake.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
