### ISSUE TITLE
Big vehicles visibly spawning at the edge of the bubble

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#11418]
This probably isn't easily fixable nor a big problem. I'm reporting it mostly so that it's not blamed on me during z-level migration.

Big vehicles centered outside the reality bubble don't exist even if many of their tiles are in the bubble. They will visibly spawn when the map shifts to include them and despawn when it shifts away.

Didn't see it cause any debugmsg-s about boarding/unboarding, because most of the vehicles that are big enough are pileups.
##

**Comment by KA101** [comment]
Uh, yeah, if your vehicle is big enough that you can be "boarded" on it and still have its origin point outside the reality bubble, you've earned your game-breaker.  @EkarusRyndren might have an RMCC  long enough to test, but apart from that I'm not worried.

**Comment by kevingranade** [comment]
Yea, the last time I looked at this I though it was "impossible", but after dealing with various other issues I could see loading one or two more "rings" of submaps around the active grid in service of streaming load/save, and when doing that we could pretty cheaply load vehicles into the vehicle cache, so they wouldn't "pop".  I'm not at all sure it's worthwhile to go to such lengths though.
The far more noticeable issue is if their headlights are on >_<
In that case taking one step can illuminate a significant chunk of the map because the vehicle got loaded.

**Comment by Skidborg** [comment]
The headlight part of this issue is a big deal.  It kinda ruins a midnight sneak through the horde if you suddenly are illuminated by a headlight beam that appeared out of nowhere.
