### ISSUE TITLE
Never mind! [$25]

### ISSUE THREAD

**Issue by VoidSpaceCdda** [CleverRaven/Cataclysm-DDA#11462]
Guess I'm not cool enough for Cataclym!!!

**Comment by KA101** [comment]
Frankly, I'm opposed to a bounty going in before we've considered the idea.  (Those Kevin posts are most likely a bot.)

You don't buy into DDA dev with cash.  (Time and effort plz.)

As for the general concept, it's not mergeable as written, because it's pretty much a game-derailer.  A turn is 6 seconds of game time, so you're talking lethal in a few hundred turns, that's 10-30 minutes.

**Comment by vache** [comment]
Looks like someone is overly sensitive...

**Comment by VoidSpaceCdda** [comment]
Yup rejected by the kool kommunity of furries back to having a life I guess forgive my foray into your sacred garden!11!

**Comment by KA101** [comment]
This didn't seem like it'd had serious discussion, or if it had, I didn't see any forum or issue topics that looked immediately relevant.  If there are such topics, link plz.

Bounties are for things that have dev support as "good ideas" already and need time & effort to implement, not "whatever someone with money wants to see in the game".

**Comment by VoidSpaceCdda** [comment]
So will you close this down so I can initiate a refund with bounty source or is this going to be to be some kind of an issue as well?

**Comment by Rivet-the-Zombie** [comment]
Github isn't the place for this sort of troll crap. If you've got complaints take it to the forums.
