### ISSUE TITLE
Issue with mansion layout

### ISSUE THREAD

**Issue by Snaaty** [CleverRaven/Cataclysm-DDA#11502]
Most recent build, at some corner of the mansion I could simply walk in without having to break any windows or doors because the wall was missing.

**Comment by drbig** [comment]
Could this be related to #11500?

**Comment by Snaaty** [comment]
Hm, I was thinking there might be a bug  in the mapgen of the mansion, but it's possible that something about mapgen for those large structures in general is a little off.

**Comment by sparr** [comment]
I'd love to see a save, or even a screenshot with the map revealed, of this.

**Comment by drbig** [comment]
@sparr I can do a screenshot for a broken hospital, will that be helpful?

**Comment by sparr** [comment]
Sure, that would be a good start.

**Comment by drbig** [comment]
NE:
http://i.imgur.com/zzuE1b4.png
http://i.imgur.com/AwEsHJo.png

NW:
http://i.imgur.com/aGwZHOH.png
http://i.imgur.com/6rW4rip.png

I can pick up items from the 'wall-fused furniture' but only if I Examine it (i.e. not via AIM); can't move into the tiles (i.e. they act like a wall). This world has been generated right around 0.C release, and AFAIR all the hospitals I've visited were broken exactly like that. I also believe similar off-by-one placement errors happen within the hospital (will upload a screenshot when I see one).

**Comment by sparr** [comment]
@drbig wrong thread? this one is about missing walls, not overlapping walls and furniture. Probably related, but separate GH issues for now.

**Comment by drbig** [comment]
@sparr yeah that's more for my #11500. I'll paste it there too.

**Comment by sparr** [comment]
I do not believe that #11500 is related to this bug, sadly.

**Comment by sparr** [comment]
I haven't managed to reproduce this, while fixing the furniture bug. A screenshot would be helpful, here. Or a description of the mansion (which corner, and describe the rooms near that corner).

**Comment by Snaaty** [comment]
I'd have to look for the save, which I can't seem to find...

Still, I remember it was the bottom right corner. (Not neccessarily of the mansion, but of the room.) I also remember that there was a potted plant right on the other side of it, therefore at first I didn't realize I could go in there. Outside was a row of bushes, IIR. I came from the left side of the mansion (not sure which way the mansion was oriented), desperately looking for an entrance, when I noticed that there was no wall on the place I described. That made surviving a lot easier though.

**Comment by KA101** [comment]
This is a known issue, yeah.  Should be a screencap floating around on the issue tracker but I couldn't find it in a search for "mansion".  :-/

**Comment by mugling** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
