### ISSUE TITLE
In-game achievements

### ISSUE THREAD

**Issue by Snaaty** [CleverRaven/Cataclysm-DDA#11519]
So, more and more games come with in-game achievements that you can collect over the course of all your playtime. 
I believe C:DDA could benefit greatly from those achievements due to its more sandbox-y nature. 

I couldn't find an issue about this, so I am wondering, what is the devs stance on this?

I can't estimate the work that has to be put into coding it, but I could help with coming up with ideas, if anyone feels like doing this. 
##

**Comment by Zireael07** [comment]
I believe it was discussed on the forums several times but the devs didn't say anything (or at least not anything conclusive)

**Comment by kevingranade** [comment]
Mildly for it, but not enough to drop my other projects and work on it ;)
We have something similar in the memorial system, but it's hardcoded in the
game. What would be nice would be a ton of hooks that run when various
things happen and a way to add watchers to them with json data or lua. Then
adding achievements would be very low-overhead.

**Comment by KA101** [comment]
Marginal oppose as it makes certain things more important than others.  I'd probably merge the system Kevin describes, but I can't be bothered to work on it.

**Comment by Rivet-the-Zombie** [comment]
Something like the memorial file I've seen in other roguelikes:

-Bettie the Punk Rock Girl survived for 12 days-
She slew 3 Jabberwocks during her life after the cataclysm.
She descended to the bottoms of 2 science labs during her life after the cataclysm.
She mutated 9 times, and purified 2 times during her life after the cataclysm.
She saved the inhabitants of the survivor shelter from certain doom.
She returned the little boy's lost puppy.
She encountered actual cannibal Shia LeBouf but did not slay him.
She once drove a /vehicle name/ over 150 mph.
She was killed in a pharmacy by a zombie moose at 6:19 PM.
Her last words were, "Curse you, zoose!"

Etc.

**Comment by KA101** [comment]
>She saved the inhabitants of the survivor shelter from certain doom.
She returned the little boy's lost puppy.

That's doable with the current system, just add a memorial log entry on quest completion.

**Comment by bkentel** [comment]
Expanding on what @Rivet-the-Zombie said, how about a conduct system a la nethack? i.e. self imposed challenges / handicaps.

**Comment by KA101** [comment]
>nethack

Ew, nethack.  -1.

As I kinda said already, I'd rather we not have folks competing and one-upping with conducts, etc.  Tends to create elitism, etc and IMO is a liability.

**Comment by bkentel** [comment]
Come on now, nethack is a classic :+1: is the -1 because you haven't ascended :stuck_out_tongue: ?

Re: elitism and what comes with it, I tend to agree (I've never been a huge fan of achievements personally either).

**Comment by kevingranade** [comment]
I don't see any reason to put conducts in a meta-game level, it seems
sufficient to just make traits that impose those limitations.

**Comment by Snaaty** [comment]
Hm, for some reason I find conducts also not very appealing. I am seeing achievement differently than KA101, though, think of it more like in minecraft, so not so much elitist. 
Perhaps a couple of "easy" achievements could be for newer players, just to give them some sort of feedback that they are doing awesome, for example. (e.g. killing your first zombie brute, installing a bionic, mutating yourself). Of course we would also need more advanced achievements that players have to plan for a longer time for, if they want to get them. 

I am also mildly opposed to the idea of rivet, as such a file will most likely lead to what KA101 doesn't want to happen, and is also rather bland, imho.

Generally though I think achievements could (if they're well designed) provide some sense of purpose to the players, while not forcing them to pursue a certain goal. That way the players get the best of both worlds. (sandbox gaming and "scripted" gaming)

**Comment by Zireael07** [comment]
+1 for "killed your first brute", "mutated for the first time", "installed a bionic for the first time" ideas.

**Comment by KA101** [comment]
I'm not averse to logging quest/mission results in the memorial.  Logging stuff between playthroughs, not so fond of that.

(Basically, I'm not confident that we could design the achievements well.  But then I'm more used to a distinction between achievements and unlocks, the latter of which makes things worse.)

**Comment by sparr** [comment]
> I don't see any reason to put conducts in a meta-game level, it seems sufficient to just make traits that impose those limitations.

This eliminates the possibility of being tempted to change your conduct mid-game by an extraordinary situation. As a low to medium skill player, that was always the trickiest part of conducts for me in nethack. I could be 4 hours into an atheist game and *really* need to pray.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
