### ISSUE TITLE
Tossing bullets in a fire

### ISSUE THREAD

**Issue by John-Candlebury** [CleverRaven/Cataclysm-DDA#11532]
I had this thought while using rat shot as sharpnel mines:
Shouldn't throwing bullets in a campfire actually produce two pieces of shrapnel (the projectile and the casing) instead of just one. I mean, without a chamber to hold the casing shouldnt it just go flying away on a random direction as well? Physics' laws and that.

Pretty unimportant, but would make a decent "the devs thought of everything" moment.

**Comment by aierce** [comment]
actually no, only the casing flies away (at non-lethal speed that can still bruise)

mythbusters did an episode on this

**Comment by KA101** [comment]
So the problem is that bullet shrapnel is too lethal, I take it?

**Comment by John-Candlebury** [comment]
Well I woulnt say that, burning ammo in a fire is already a pretty high level desperation attack. No real need to nerf it from my point of view.

I was just wondering if (bigger) bullets exploding should make two units of shrapnel instead of one

**Comment by maxmurder** [comment]
The reason only the casing flies away is because it has significantly less mass than the bullet. I would assume that higher caliber ammunition would have less chance of launching the bullet, as the bullet has even more mass relative to the casing. I could see shotgun shells possibly firing their ordinance when heated/burned, but IRL they would likely melt before going off or just blow apart when thrown in a fire.

**Comment by Rivet-the-Zombie** [comment]
>I could see shotgun shells possibly firing their ordinance when heated/burned, but IRL they would likely melt before going off or just blow apart when thrown in a fire.

From RL experience I can tell you that they go **pop** really loud and the halfway-melted case flies out of the fire.

**Comment by mugling** [comment]
How and when ammo should apply `COOKOFF` will be addressed in #15239
