### ISSUE TITLE
Issues with character creation points

### ISSUE THREAD

**Issue by railmonkey** [CleverRaven/Cataclysm-DDA#11551]
I updated to 2856 on another machine and copied in my templates folder. Loading any of the templates shows that the traits are as they were saved, but navigating to the traits tab shows that none of them are selected even though the points are accounted for. Possibly related, but I've also found that after messing around with the character creation screen for a while, it seems to manufacture creation points from whole cloth. In the end, I've managed to create templates that use way more than the vanilla 6 points plus 12 flaw points. By how much more depends, but after trying to recreate one of them, the count looks to be up to as high as 16 points over limit, even with the bonus 10 from the lab scenario.

EDIT: Specifically, screwy things seem to happen when you edit a presaved template.

**Comment by mugling** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
