### ISSUE TITLE
vibrator fatigue error is non-intuitive

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#11567]
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/iuse.cpp#L5908

In the context of the source and the error above, this is funny. However, a player won't have that context when they get the message, and it might be confusing. It should probably be rephrased.
##

**Comment by KA101** [comment]
At that point the fatigue display should read "Dead Tired" (or worse), so that's where I'd anticipate the context on player-side.

For the record, not being able to use a vibrator when that fatigued is intended behavior, not an error.

**Comment by graysage1** [comment]
I think it's supposed to be witty, but I can see how possibly, maaybe it could confuse some people.  I've not used a vibrator yet so never had to face the issue.  Would anyone who *was* confused by this raise their hand?

**Comment by illi-kun** [comment]
For the record: link from initial message shifted to unrelated piece of code but we're probably talking about this piece of code:
```
    if (p->fatigue >= DEAD_TIRED) {
        p->add_msg_if_player(m_info, _("*Your* batteries are dead."));
        return 0;
```

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
