### ISSUE TITLE
Automatically determine profession point costs

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#11573]
My initial thought was that profession costs aren't very well balanced currently. Survivalist starts with 9 points of skills and what looks like a better inventory than Survivor, but only costs 3 points. I understand that a skill package is less valuable than points to spend on skills, but not 2/3 less.

What if the cost for a profession was calculated automatically? Give items a usefulness rating (which might be useful in other areas as well), ditto for bionics and addictions, add on the point values for traits and skills, maybe apply a multiplier (because a package is less valuable than freely-spent points), and you've got the point cost for the profession (relative to Survivor being the baseline zero).

(this is meant to be a Suggest [Discuss] issue)
##

**Comment by ejseto** [comment]
Think survivalist is bad? Blackbelt costs 8 and gives 48 points worth of skills.

You can also put a single point into a skill to get +2, then take a profession that boosts it. Since skill costs increase nonlinearly, that one extra point can actually be worth a LOT (for Blackbelt, one extra point spent in a profession skill is effectively worth NINE points). While you have a point that professions should get a bonus because they're not as versatile as spending the points yourself, the sheer number of professions has pretty much eliminated that penalty. On the other hand, the game is probably somewhat balanced around taking a profession that is worth more points than it should be.

**Comment by sparr** [comment]
@ejseto if the under-priced 5-8 point professions are balanced with each other, then skill points in general are over-priced, as are the -2 to +1 point professions, and probably stats too. Something needs to be the reference point for the others.

**Comment by KA101** [comment]
Lots of the balance things take into account what *isn't* started with, not just what's there.  For example, Blackbelt justifies the significant amount of skills in part thanks to the theme, but also because it has negligible clothing, no carry-volume, and no access to fire or a cutting implement.

As for the idea of automatically generating values, things are situational so we'd require a manual-override field.  With that in mind, sure, have fun setting point costs for all the gear.

You'll be a while at it, if our experience with the JSON price audits is any indication.  ;-)

**Comment by ejseto** [comment]
Considering how often the starting NPC gives you a lighter if asked, access to fire isn't really a significant balance point.

**Comment by sparr** [comment]
@ejseto I'm new around here. NPCs are off by default. Are they considered turned on for balance decisions?

**Comment by ejseto** [comment]
I'm pretty sure it's not a balance decision. NPCs used to cause segfaults left and right. They don't anymore, but I guess nobody bothered to turn them back on.

**Comment by KA101** [comment]
OK, so NPCs need rechecked as well.  Lovely.

**Comment by ejseto** [comment]
Isn't it more a matter of "turn them back on by default and see if people complain?" That said, there are definitely still placeholders in their dialog, "Someone forgot to code this..." and so on.

**Comment by KA101** [comment]
>Isn't it more a matter of "turn them back on by default and see if people complain?"

Uh, if the PR hopper was more around 30-40 PRs, sure.  Bit backlogged now.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
