### ISSUE TITLE
Rework of butchering code

### ISSUE THREAD

**Issue by tivec** [CleverRaven/Cataclysm-DDA#11615]
While I have been working with adding stomachs to corpses, I found that the whole butchery activity is pretty clunky. I'd like to put in a a suggestion to move this to JSON.

Much like crafting uses a `"components"` list in the recipes, I suggest that we add a `"butcher"` list to monsters. It could either be a butchery group, or a list. I am not sure if it is possible to have both in the same tag, or if we'd need `"butcher"` and `"butcher_group"`.

Here is an example of how it could be defined:

```
"butcher": [
   [ "meat", 5 ],
   [ "stomach", 1 ],
   [ "feather", 12 ],
   [ "bones", 2 ]
]
```

The number after the item name is the maximum amount of items that can be produced from the corpse. This is similar to the way it is defined in the code right now, which I think is a bad way of doing it:

```
case MS_TINY:
    pieces = 1;
    skins = 1;
    bones = 1;
    fats = 1;
    sinews = 1;
    feathers = 2;
    break;
```

Anyhow, I'm leaving this here to someone who is more versed with both C++ and adding JSON functionality, I suspect I couldn't make a proper attempt at adding it without botching it completely.
##

**Comment by DavidKeaton** [comment]
I very much like this idea, and if expanded to items or tiles, could make a simple `can_be_butchered` check for testing it. Thus, making things JSONable for butchering. :-)

**Comment by BevapDin** [comment]
> Much like crafting uses a  "components"  list in the recipes, I suggest that we add a  "butcher"  list to monsters. It could either be a butchery group, or a list. I am not sure if it is possible to have both in the same tag, or if we'd need  "butcher"  and  "butcher_group" .

With group you mean item groups (those that are used for mapgen as well)? They could be used, but it's a bit complicated / un-intuitive how they scale according a skill factor (skill and butcher tool quality).

Why not use a system similar to the "base terrain/furniture/vehicle part" results: a list of items with min/max count. Multiply the min/max count with the skill factor and chose a random value in that range. Additionally you might want a "one item, with one_in(chance)" for items that appear at most once (e.g. the skull).

**Comment by tivec** [comment]
I agree, @BevapDin. That's how I envision it. I just thought pairs would be easier to work with, but it can probably be along the lines of `{ "result": "meat", "min": 0, "max": 1 }`

With that, we could probably also add requirements (any CUT tool, any CUT tool with quality > 5 etc) :)

**Comment by tivec** [comment]
@DavidKeaton If I am understanding it right from your comment on #11649, you're going to take a look at this?

**Comment by DavidKeaton** [comment]
I am prob gonna tweak it in after I finish up this minor encumbered patch.

**Comment by DavidKeaton** [comment]
looking into it now

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
