### ISSUE TITLE
Prevent furniture from spawning on stairs

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#11610]
In labs, in particular. It's very inconveniently to manually search for stairs hidden under some table or chair tile by tile.

**Comment by Snaaty** [comment]
Yes please!

**Comment by sparr** [comment]
Can you post a screenshot of a situation where this happened? Preferably with the map revealed through the debug map editor. Labs have a lot of layouts, and I'm guessing only one of them exhibits this problem.

**Comment by KA101** [comment]
I'm thinking a check for terrain = t_stairsup/down, and if so removing the furniture.

**Comment by sparr** [comment]
That means a map designer can never intentionally put furniture on stairs. I think furniture on stairs has a very legit zombie-defense feel to it, in the same way that a lot of the buildings have furniture piled up in front of doors.

I suspect the instances in question here are just random furniture spawn areas that happen to occasionally overlap stairs, not by any intention of the map maker.

**Comment by KA101** [comment]
Exactly, so in random mapgen, implement the check.  JSON'd mapgen is exactly as designed and therefore should not need this check, because a blocked-off stairway should otherwise be discoverable through intelligent exploration.

**Comment by sparr** [comment]
How do we differentiate between "random mapgen" and "mapgen that's procedural but doesn't place furniture randomly, and the designer wanted a table on the stairs"?

**Comment by KA101** [comment]
If a designer wants a table on the stairs the designer can stipulate that in the design; separate commands, IIRC.

**Comment by Night-Pryanik** [comment]
![default](https://cloud.githubusercontent.com/assets/11132525/6703357/9eeef0aa-cd4b-11e4-9277-3827897de1d9.png)

**Comment by KA101** [comment]
OK, if you want the check reversed, then say so.

**Comment by Night-Pryanik** [comment]
All I want is to make stairs visible in case of overlapping. If making stairs spawn on top of the furniture, not the vice versa, is easier to implement, then it'll do.

**Comment by BevapDin** [comment]
> All I want is to make stairs visible in case of overlapping. If making stairs spawn on top of the furniture, not the vice versa, is easier to implement, then it'll do.

Stairs are terrain, furniture is furniture. They exists separately and independent, furniture is drawn over terrain because it usually sits on top of the terrain, but you can set the terrain and the furniture separately in any order you like (the games does not store any order there). Furniture is *always* drawn over the terrain.

The mapgen code for the science labs does this:
```C++
int sx, sy;
do {
    sx = rng(lw, SEEX * 2 - 1 - rw);
    sy = rng(tw, SEEY * 2 - 1 - bw);
} while (ter(sx, sy) != t_rock_floor);
ter_set(sx, sy, t_stairs_up);
```
It only looks for a rock floor (t_rock_floor is terrain) and replaces it with stairs (t_stairs_up is also terrain). The furniture there (if any) is completely ignored and unaffected by this.

Btw. this is the place where you would want to add a check for furniture. If there is furniture (`map::has_furn`), continue the search. Or (not recommended, but possible) remove the furniture from the stairs using `map::furn_set` and `f_null`.

Btw. this clearly shows that the stairs should appear at a random point (which does not take furniture into account).
Code like the following would indicate that the stairs should indeed spawn at the exact same spot as the table:
```C++
int x = ...;
int y = ...;
ter_set( x, y, t_stairs_up );
furn_set( x, y, f_table );
```

**Comment by sparr** [comment]
I think there's a function in map called simply set() that can do `set( x, y, t_stairs_up, f_null );` in a single step.
