### ISSUE TITLE
Turn on USE_HOME_DIR by default?

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#11697]
I recognize that making the game installation "portable" by storing config and saves alongside the game binaries and data is appealing to some people, but it feels very archaic to me. I was excited to discover the USE_HOME_DIR option when I went to implement that feature myself. I feel that it should be the default. I think modern gamers are used to having saves go in the appropriate user data locations (~/.xxx, Library/Application Support/xxx, AppData\xxx, etc), and not having their configuration overwritten when they reinstall/update the game.
##

**Comment by Griffinhart** [comment]
Personally, I'd rather keep the portable install, because that's what I'm used to, even if it cleaves closer to standards to use the home directory.

It's a pain in the rear to have to go to one directory to deal with some stuff with a given program, when the entire rest of the program is in some other directory.

**Comment by sparr** [comment]
Maybe this should be a game option instead of a compile option? And if you start the game with the option set to X but you already have saves in place Y then it prompts you?

**Comment by BevapDin** [comment]
> Maybe this should be a game option instead of a compile option? 

Do you mean the command line option `--userdir`?

**Comment by sparr** [comment]
@BevapDin I was thinking an option in the game options menu. Command line options are fraught with peril for most people. Although thanks, I didn't know about that either :)

Is there a list of build flags and/or command line parameters somewhere outside the source?

**Comment by BevapDin** [comment]
Run the game binary with the `--help` flag. That is the usual way of getting all the command line options. It only works for people that know how to run it that way, but those are exactly the same people that can use them.

> outside the source?

I don't known, but I assume that documentation is terrible outdated.

**Comment by KA101** [comment]
For my part, I despise games that hide their files.  Everything in the one folder & its subfolders works fine by me.

*KA101 doesn't let stuff install to Program Files either*

**Comment by kevingranade** [comment]
The friendly way to do this is to make a little wrapper script that
launches the game with the appropriate flag, possibly dynamically
configured based on install options.

**Comment by Griffinhart** [comment]
>KA101 doesn't let stuff install to Program Files either

That doesn't stop things from saving data to e.g. `C:\Users\YourUserName\Appdata\Roaming`. Like, I don't install anything to Program Files either, and I don't even actually keep my own user account's Documents on my C:\ partition (hell, I even have a separate AppData\Local directory on an entirely different partition), but C:\Users\Griffinhart\AppData is filthy with crap.

**Comment by KA101** [comment]
Win post-XP, sure.  But then I'm pretty bad at giving microsoft money.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
