### ISSUE TITLE
Idea: supplement vehicle direction X with highlighting tiles vehicle will occupy next

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#11719]
The X is nice, but when I'm weaving a motorcycle through a dense area I'd like to have more information. Would it be feasible/acceptable to add a third option (in addition to no-X and X) to highlight the tiles the vehicle will occupy on the next move?
##

**Comment by KA101** [comment]
Not sure about feasible, but if it is, that'd make a nifty perk for folks with 5+ Driving.

**Comment by sparr** [comment]
Now you've got me thinking the X should be less accurate for lower Driving skill, too...

**Comment by narc0tiq** [comment]
I like both of these ideas.

**Comment by KA101** [comment]
Low Driving is already penalized with the control-fumbling.  High-end Driving only (in theory) makes you better at firing personal weapons while driving, possibly better at not skidding and/or getting out of a skid more easily, and how many folks routinely do that?

**Comment by sparr** [comment]
one thing I do frequently that driving should probably help with is leaning out of the car to pick up items from the ground while in motion :)

**Comment by KA101** [comment]
Yeah, that'd be likely to cause skids.

**Comment by sparr** [comment]
It's usually effect-free. I think because the grab takes less than one turn, so the vehicle doesn't move? I haven't tried grabbing lots of stuff.

**Comment by kevingranade** [comment]
I have no problem with anything that's been mentioned so far, driving could
definitely use some more of this kind of thing :)

**Comment by Zireael07** [comment]
I like all of those ideas :)

**Comment by KA101** [comment]
>leaning out of the car
>It's usually effect-free.

Yeah, that's an Exploit. Even at 9 MPH opening the door and leaning out of a moving vehicle should require a skill check to avoid bumping the controls.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
