### ISSUE TITLE
Add vehicle funnel

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#11725]
Having looked at the weather code for filling funnels, I see that it's very dependent on funnels being traps. Nonetheless, I think it would be great if there was a funnel vehicle part, to fill the vehicle's water tank. Feedback here will determine whether I try to tackle this or not.

**Comment by Rivet-the-Zombie** [comment]
So long as we've got a tank that can hold untreated water, and some means of processing it within the vehicle (flip a switch and the vehicle transfers untreated water through a purifier into a clean water tank at the cost of energy) this would be great.

**Comment by BevapDin** [comment]
This would be very much appreciated, it comes up on the forum every once in a while:

http://smf.cataclysmdda.com/index.php?topic=9191
http://smf.cataclysmdda.com/index.php?topic=4610
http://smf.cataclysmdda.com/index.php?topic=9623

It might also use the generic vehicle tank system from #10832 in case you don't want or don't need clean water (many recipes will work with non-clear water).

**Comment by Coolthulhu** [comment]
Generic vehicle tank system is a bit unfinished. I could get it to work if needed, but it would be rather heavily buggy for a while. For now a temporary hack would probably be better.

The problem with dirty water storage is that all stored liquids need a corresponding ammo type. In this case `"water"` is taken, so it would need to be something like `"water_dirty"`. Care would need to be taken so that it doesn't suddenly purify/dirty the water.
Plus, water's `poison` stat would need to be set in few places.

The funnel function itself wouldn't be hard, but it would have a disadvantage over trap-type funnels: it won't work retroactively.

**Comment by sparr** [comment]
Maybe a vehicle funnel could require a powered filter, and only work if the filter is on. Then we don't have to worry about storing unclean water, for now.

**Comment by drbig** [comment]
Vehicle funnel = funnel + water purifier. Works only when enabled, and only when there is electricity.

**Comment by BevapDin** [comment]
Implemented in the linked PR.
