### ISSUE TITLE
No tool other than a knife has inscribe / cauterize / salvage use?

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#11734]
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/item_factory.cpp#L1350-L1366

It looks like there are three specific item "use" types that could be assigned to non-knife tools, but I can't find any items with those types. Looking at tools.json I wanted to make the toolbox usable for salvage, since it's got all the right stats, but it already has a use_action for repair. Is there some way to make a tool capable of salvage/incribe/cauterize in addition to the uses they already have?
##

**Comment by sparr** [comment]
I've found the support for an array of use_actions and will submit a PR shortly.

**Comment by sparr** [comment]
... nope. I can assign two use_action by making them an array, but then item_factory expects there to be a matching iuse function. Seems like maybe use_action got overloaded a bit too much?

**Comment by BevapDin** [comment]
(I'm not sure what the problem is.) Maybe you want to do something like the `firemachete_off` (search for it in data/json/tools.json). It has two use functions in an array and looking at the code in item_factory.cpp, any number of use_functions in that array should be supported. `firemachete_on` has even three functions there.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
