### ISSUE TITLE
Make child professions mechanically different

### ISSUE THREAD

**Issue by John-Candlebury** [CleverRaven/Cataclysm-DDA#11814]
An idea that I think would make child professions considerably more interesting.

-A different max attribute cap at chargen. Perhaps 8 for strength and 9 for dex, the defaults for both would be 6.
-A mixed bag kid trait that included: A negative version of fleet footed, flimsy (without the reduced health regen) bad back, fast healer, good hearing.  
##

**Comment by KA101** [comment]
Only problem with kid traits is that, by rights, the kid should eventually grow up and lose the traits.  Last I checked, the only way to track years lived/birthday would be a straight count with correction for SEASON_LENGTH.

**Comment by sparr** [comment]
If we're going to have kids grow up, adult characters should get older, too.

**Comment by drbig** [comment]
I'd say: You can always Role-Play a kid character - exactly by capping your stats, selecting appropriate traits etc. I don't think an in-game infrastructure for that would bring much value versus the cost of coding and maintenance.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
