### ISSUE TITLE
Building buildings question/problem/???

### ISSUE THREAD

**Issue by drbig** [CleverRaven/Cataclysm-DDA#11835]
Is there any, preferably good, reason I can't build a roof south to where I'm standing:

![Why no roof](http://i.imgur.com/6RRyzM6.png)

The same problem was with the shelter wall where I had to replace reinforced boarded up windows with wood wall (which also doesn't align with the rest of the wall, but that's another issue)... As if adjacent non-wall construction makes roof (+ plus the free floor) impossible to build, even when it's a window, or a door.

In case anyone has doubts: I do have all the tools, materials, skills, and the SW tile is already roofed.

Also it seems to be impossible to paint a wooden wall...
##

**Comment by BevapDin** [comment]
The closed door does not have the `SUPPORTS_ROOF` flag. You can only build a roof if 2 of the 4 adjacent squares have that flag.

Painting (you have my respect for doing that, I never found enough paint) is implemented as another terrain type. The standard walls are duplicated with equal stats, but different color. This has just not been done for the other walls.

**Comment by drbig** [comment]
> The closed door does not have the SUPPORTS_ROOF flag. You can only build a roof if 2 of the 4 adjacent squares have that flag.

Where 2 of 4 make some sense, but then doors and windows should have the flag, otherwise it's pretty much impossible to sanely extend a structure.

I think I'll try to build a wall north from where I'm standing, make a roof over where I am, then roof south and then bash the wall down... Wonder if the roof will collapse :)

> This has just not been done for the other walls.

Yeah I was thinking along these lines.

And also: the rastafari scheme was only because I couldn't find enough damn paint to paint the whole place one color ;)

**Comment by Rivet-the-Zombie** [comment]
>doors and windows should have the flag

This causes buildings to collapse when you break a window.

**Comment by drbig** [comment]
@Rivet-the-Zombie I believe I do see the underlying problem now... :S

**Comment by Rivet-the-Zombie** [comment]
We need separate flags for ````SUPPORTS_ROOF```` and a theoretical ````CAUSES_COLLAPSE````, we just don't have any.

**Comment by drbig** [comment]
My first idea would be to have a new flag for constructions then. I'm certainly against introducing the idea of load bearing, but I'd like to have fun with what is already available (at least). I'd also like to see a '(material) column' construction that ideally would be able to support roof tiles farther than just the adjacent tiles.

**Comment by drbig** [comment]
@Rivet-the-Zombie Addressing just my initial issue: new flag like `CAN_ROOF_AROUND` - just better named. I'd leave the `SUPPORTS_ROOF` as is.

With the above I'd be satisfied even with columns being 'a wall, but you can sort-of see through them, and elements work too'.

No idea about any of that code-wise though.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
