### ISSUE TITLE
too many .h dependencies cause unnecessary recompiles

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#11860]
I touch map.h occasionally, and this is almost equivalent to `make clean`. If we could split the headers up more, so that the more depended-on files change less often, we could improve our patch build times. I'm not sure of all the appropriate ways to do this, though. I'm thinking that the map class declaration could be split in half, public methods in a file that more things depend on, private methods in a file that just map.cpp depends on.

**Comment by Coolthulhu** [comment]
I did some (3?) cleanups like that. The worst part is not that headers are too big, it's that headers include more headers. Headers should only include the bare minimum of other headers, with only .cpp files including the rest.

Worst offenders are headers like map.h and game.h. Not just because they're included everywhere, but because they do have a great deal of own includes. And those includes are often big themselves (for example, game.h->map.h->vehicle.h->item.h).

Not sure if you can just split a class in C++. You mean like create an adapter, some stripped-down "mini-map" class?

Please delay major map.h overhauls for a while. I'm doing the 3D rework right now and I'll be changing great deals of the file. Adding and removing lots of overloads. We'd be getting in each other's way a lot.

**Comment by sparr** [comment]
I didn't realize you couldn't split up a class declaration between two files. I'm a bit sad about that.

I won't be taking this one on myself, I'm just hoping I can incite someone to look at it. For now my modifications to map.h will be single new functions and members.

**Comment by kevingranade** [comment]
This is a known problem with large c++ problems in general, no need to open
an issue about it.

**Comment by sparr** [comment]
It's a reach but here's a crazy idea...

map.cpp: `#include map.h`

game.cpp: `#include map.h`

map.h:

    class map {
        public:
            int foo(bar);
    #include map_private.h
    }

map_private.h:

    private:
        int baz();

Then in the Makefile, after we `-MMD` to get map.d and game.d, we remove map_private.h from game.d (and every other .d except map.d).

**Comment by BevapDin** [comment]
No need to fiddle with the Makefile, just this:

```C++
class map {
    public:
        int foo(bar);
#if defined(IN_MAP_CPP)
#include "map_private.h"
#endif
};

// map.cpp:
#define IN_MAP_CPP
#include "map.h"
```

But this is really, really, really ugly. Did I mention that it's an ugly solution?

**Comment by sparr** [comment]
That's the least ugly solution I've seen so far, by some combination of metrics. It's a lot simpler than my idea with Makefile/dependency modifications.

Are we willing to make the code a bit uglier to speed up builds significantly? @KA101 was complaining recently about how much build time we spend on trivial code changes.

**Comment by sparr** [comment]
freenode #c++ has pointed out to me that any of these approaches will lead to problems any time something other than map.cpp tries to do anything that relies on the size of a map object, so I guess I'll abandon this idea for now.

**Comment by KA101** [comment]
KA101 has tracked the 78-min compile thing to problems with memory usage: having Thunderbird (with several years of e-mail in his inbox) open at the same time as the compiler.  That's been resolved.

Having to switch to -w64 every time is a separate complaint.
