### ISSUE TITLE
We need a cardio skill.

### ISSUE THREAD

**Issue by Rivet-the-Zombie** [CleverRaven/Cataclysm-DDA#11887]
Now that fighting and sprinting costs stamina and low stamina messes up your performance, we need a skill to represent your progress from a soft and slow civilized person of variable physical fitness into a _lean, mean, post-apocalyptic zombie slaying/running away from machine_.

Something to improve your overall stamina pool/usage efficiency/stamina regeneration rate with practice. I think raising melee skill should probably reduce the amount of stamina used in melee combat, so that would be an easy place to start.
##

**Comment by KA101** [comment]
Hmm.  Might also push back if you're not actively working out (construction projects might qualify?), hence why civilized folks got soft & slow to begin with.

**Comment by kevingranade** [comment]
'running' or 'athletics' would be a skill that influences your ability to
run, cycle, fight, climb, etc, allowing faster actions and less stamina
drain.
For increasing your stamina reserves and stamina recovery rate, I want an
endurance stat.
Stats you can increase is its own bag of worms, so let's do a separate
issue for that (or hash it out elsewhere, that discussion is likely to run
pretty long) and discuss 'athletics' here, which I'm all for and can be
added quickly.

**Comment by Shoes01** [comment]
I think I agree with Kevin. Stats should be like a genetic property of the player, and thus can't be improved through practice. An Endurance stat, along with a very general athletics skill, could be used instead. 

This reminds me of some of the weirder skills you can level in Dwarf Fortress; things like leadership and observation. A post apocalyptic survivor would have developed a great sense of observation, but not through reading a book or crafting glasses. (Watchmaking however...)

**Comment by Coolthulhu** [comment]
Athletics wouldn't work well with current skill system. It's not something you can grind up once and then keep up from rotting by making a single check every n hours.

With current skill system, it would contribute to the problems the system already has: every survivor can easily become a master of all trades.
And current skill rot doesn't help - when it's on, it simply requires executing (trivial but tedious) "skill rot prevention dance" every n hours. It only really works during sleep and long crafting, but in this case it also affects the masters of just one trade, is heavily unrealistic and can be prevented by regular uptake of (preferably atomic) coffee.

**Comment by Frost-wood** [comment]
In my military training book, I have at home, it says that your physical attributes gained from training start to deteriorate after 78 hours, so having a check after 78 hours would be fine.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
