### ISSUE TITLE
Bug with json mapgen item spawning 

### ISSUE THREAD

**Issue by John-Candlebury** [CleverRaven/Cataclysm-DDA#11910]
I entered one of the office towers I recently added and noticed that instead of having the office items all randomly thrown around in the desk area, (like it happened a few days ago) all the items spawned in a single gigantic pile somewhere in the desk areas.

**Comment by BevapDin** [comment]
That seems to be cause by the change in dcd096ddf2d2c136087ae8f237c1fb531eb08695, to make the whole system more consistent:
The repeat factor defines how often the location (based on x,y) is rolled, this defines the place *where* to do things.
The item and chance define *what* to do: place items from the group, the amount of which is decided by chance.

The same mechanics is used for the other things: e.g. for monsters, specials like vending machines, or fields.

----

It could be fixed by changing the spawn lines to something like
```JSON
"place_items": [
    { "item": "office_mess", "repeat": [1, 4], "chance": 20, "x": [ 15, 20], "y": [ 11, 19 ]}
]
```

Or add a mapping:
```JSON
"items": {
    "C": { "item": "office_mess", "chance": 50 }
},
```
That will have a chance of spawn items from the group on every "C" square (according to the "ter" map), basically the same as adding an entry with fixed coordinates in "place_items" (one for each "C" in the "ter" map). "C" is mapped to "f_desk", so the items would spawn on the desks. "chance" is still applied there, in this example, only 1/2 of all desk would actually have items on it.

**Comment by John-Candlebury** [comment]
Sorta related, the barn of the abandoned farm used to spawn a single instance of the cabin_suicide collection, using this:

                { "item": "cabin_suicide", "chance": 100, "x": [ 4, 4], "y": [ 15, 15] },

This now results in the game spawning the collection several times, which is not really supposed to happen. 

Anyway I can restore the original functionality?

Have already tried to map it to the specific tile and reducing the chance to no avail, the game keeps spawning the corpse+ gear several times.

**Comment by BevapDin** [comment]
> This now results in the game spawning the collection several times, which is not really supposed to happen.

It works fine for me. But it is affected by "Item spawn scaling factor" option. If it's set to above 1, it can spawn the items several times.

So basically we need another mapgen option: spawn items without being affected by that option?

**Comment by John-Candlebury** [comment]
Oh whoops I double checked, you are right my spawn number was at 1,5, real sorry.

> So basically we need another mapgen option: spawn items without being affected by that option?

This would be fantastic, "add" kinda does this already but wont recognize item groups IRC.

All this mapgen work you have done is pretty great actually, I can make houses about thrice as fast :D

**Comment by John-Candlebury** [comment]
Was never really a bug.
