### ISSUE TITLE
City Mapgen Improvements Discussion

### ISSUE THREAD

**Issue by Frost-wood** [CleverRaven/Cataclysm-DDA#11911]
A thing that is missing from city mapgen is the ability to have more than one square buildings, which affects the ability to place specials in the city core. I was wondering what the best way to go around adding "specials" to the mapgen would be.

Currently the mapgen places roads in the four directions and then randomly splits into different streets based on the city size, placing buildings as it goes.

Would it be better to do a block at a time?
How do we account for different size buildings in a 'block' or do we loop a road around the 'special' structure and continue from there?
Would it be better to zone stuff like in sim-city(residential, commercial, industrial) and place the buildings that way?
Do we load the buildings from the current json format or do we do something that is happens in regional_map_settings.json?
##

**Comment by DavidKeaton** [comment]
Blocks are _usually_ square or rectangular in nature. One would just need to start off with randomly sized buildings and fill in the gaps there, using unusable space as lots or alleys. IMO of course.

**Comment by kevingranade** [comment]
It all comes down to implementation details, those might be worthwhile, or
not, it completely depends on how it's done.

**Comment by DavidKeaton** [comment]
truth

**Comment by vache** [comment]
There is a currently unimplemented city type that was supposed to control the general layout of cities.  Using regional map settings seems like it would be the better choice in the long run if we want to support other regions like deserts and whatnot.

**Comment by Frost-wood** [comment]
Where exactly is it in the code?

**Comment by vache** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/overmap.h#L91

Again, completely unused, but ideally it should support this so multiple types of layouts can be supported.  Also a lot of layouts should only apply to larger cities (grid system + suburbs on outskirts).

Also, my plans for the multitile buildings for when they were able to be generated inside cities were to use some of the flags and parameters there to control their placement.  These parameters get read right now, but aren't used at this point.  

````"locations":["inner_city", "outer_city"]```` control where inside cities they could spawn, think slum apartments in inner city, wal marts in outer city
````"city_sizes":[3,8]```` control what size cities the structure can spawn in (in this case from sizes 3 to 8), think no international airports in size 2 cities
````"unique":true```` only one allowed in a city, think town hall
````"required":true```` if true, this structure MUST spawn in any valid size cities, think town hall again.

Unique and required may be moved to flags since only city buildings will need them.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
