### ISSUE TITLE
Failing to make a wearable flashlight, can destroy the flashlight.

### ISSUE THREAD

**Issue by FireCrow1973** [CleverRaven/Cataclysm-DDA#11922]
Hi, i just wanted to know what everybody's opinion was here.
I had just hit the flashlight mother lode:
flashlight,
extended battery mod,
battery.

having instaled everything and finished my victory dance.
i decided to go for broke and make it wearable, i failed and the flashlight disappeared.

now, i'm not sure if you are rewiring the thing or sewing a nice pouch for it, but it seams strange that it just vanishes.

if you are making some sort of strap or pouch for it, it should just waste the rags and string.

if you are re wiring it though, seams you would need a soldering iron first of all.
but also if you fail it should be a small pile of circuits, battery and scrap aluminium.

just my 2 cents.
##

**Comment by DavidKeaton** [comment]
I believe that some items should be flagged as destroyable, sure.

**Comment by Rivet-the-Zombie** [comment]
Currently the game doesn't track which items/recipes would make sense to be destroyed on critical failure; all recipes stand a chance of having this happen.

**Comment by Darkyhard** [comment]
Actually, similar problem exists with failing pretty much all recipes. For example, if you fail to make a meat soup, you would get something that won't taste good, but you still could eat it.

I would suggest to add something like "you hit your finger with a hammer" or "you burn yourself with the soldering iron" type of fails that won't waste your items but may cause other undesirable effects if you don't use proper pieces of clothing for the task.

**Comment by DavidKeaton** [comment]
Or...! _Another_ flag for items! :^P

**Comment by facepalm** [comment]
>destroyed on critical failure

That's supposed to be a __critical__ failure?  It happens pretty often with a default 8 intelligence.  Looking at the code, it can happen if one's skill_roll is as little as 10% less than the difficulty_roll.

**Comment by DavidKeaton** [comment]
Damn.

**Comment by nonymous** [comment]
I failed making ammunition and destroyed lead.  It was completely unrecoverable.

**Comment by kevingranade** [comment]
If someone wants to add an optional 'not-destroyed-in-crafting' flag
(hopefully with a shorter name <_< ) and annotate the items where
destruction due to crafting doesn't make sense, they're welcome.  If there
are fewer destructable items, that way is fine too, but that one needs to
be done all at once where the indestructable flag could be added a few
items at a time.

**Comment by Oskar636** [comment]
@kevingranade (Yup, appeared out of nowhere ;p) Just my few cents, if it were a flag going straight to items, then it'd be kinda weird. Because an item can be "destroyable" in one recipe and not destroyable in another. Like you have a stick, and in one recipe you make a mop which is just rags + strings + TEH STICK, and in another one you have like, the blowgun, which is a bunch of cutting I guess.

**Comment by FireCrow1973** [comment]
yes to both.
this "flags" sounds like a good idea.
and of course items should be destroy-able some times and not others.

we are so good at finding solutions!

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
