### ISSUE TITLE
LMOE should have included atomic lights

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#11923]
How rare are atomic lamps and nightlights, lore-wise? It seems like that's something a well prepared LMOE would have put in their shelter.
##

**Comment by FireCrow1973** [comment]
who rights the lore?

**Comment by DavidKeaton** [comment]
I'd see them having a generator with stapled wires hanging from the ceiling with bulbs every so often, like a mine (it already is a bit rubbled up in a few areas). IMO of course. :-)

**Comment by KA101** [comment]
LMOE is already pretty good, no need to make it a complete base-on-a-platter.  I'm opposed on balance grounds.  (The lore in this case could vary dramatically between shelters.)

**Comment by Rivet-the-Zombie** [comment]
>they're generally Expensive, the sort of thing that's available in high-end boutique shops/catalogs for discerning individuals of wealth and taste. (And the military probably has more than a few atomic coffeemakers.)

All this right here.

Think Nordstrom/high-end Macy's selection.

**Comment by sparr** [comment]
Hmm, ok, so thematically they would be appropriate, for someone who has bought land and built a bunker and such. That leaves @KA101's balance concern.

To be honest, I think I'll care a lot less about actual lighting if #11808 ever lands

**Comment by KA101** [comment]
That's one possible LMOE.  Others include X group getting together and pooling resources/time, someone owning land but being cash-poor, someone *not* owning land but adversely possessing, etc.

**Comment by sparr** [comment]
Ooh, now you've given me the idea for a LMOE-in-a-cave...

**Comment by vache** [comment]
It is very possible to add multiple LMOE layouts, and there could be a small chance to spawn one with a light...

**Comment by sparr** [comment]
I actually already added a second one, because I was bored with the first. A couple more are on my to-do list.

@KA101 how do you feel about medium probability atomic nightlight near the bed, low probability atomic lamp somewhere like the workshop, in one or two of the to-be-four LMOEs?

**Comment by Zireael07** [comment]
I think that is reasonable.

**Comment by vache** [comment]
I would use the utility light terrain tile instead of the atomic nightlight item, reason being that the utility light can't be carried around with you.

**Comment by DavidKeaton** [comment]
LMOE in a cave = 2dope

**Comment by KA101** [comment]
I'm with vache: atomic lights are portable so I'd want to see some other downside to the atomic-lit LMOE.  Cave might suffice for the utility-light (no external door = stuff can follow you down) but fewer items/spawns would be a lot more persuasive for atomics.

And, obviously, simply finding a LMIC* shelter should be good on its own: caves are pretty common and low-reward and/or med-risk-variable-reward ATM.

*Last Man In Cave

**Comment by Labtop-215** [comment]
Perhaps with static NPC's enabled, a static NPC that is usually hostile and armed with a higher end gun and the atomic lamp or nightlight in their inventory might be more workable.  At least once the game can remember the inventories of NPC's.

A working lightsource seems like something you'd take with you if you decided to go out for a bit.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
