### ISSUE TITLE
Dead zombies getting stuffed into vending machines.

### ISSUE THREAD

**Issue by Rivet-the-Zombie** [CleverRaven/Cataclysm-DDA#11932]
[From the forums:](http://smf.cataclysmdda.com/index.php?topic=9152.msg229469#msg229469)

>This seems legit...not relay a game breaking bug but...if I'm killing zombies and they die in a window next to a vending machine there corpses will land in it and it will sell the corpses to me.

**Comment by DavidKeaton** [comment]
I see no bug. Life has its value.

**Comment by Lain-** [comment]
lol the mental image of a vending machine dispensing a (very dead) zombie.

**Comment by vache** [comment]
Vending machines seem like another sort of thing that could benefit from a "mapgen placement only" type tag (along with gas pumps)

**Comment by DavidKeaton** [comment]
I would love to pull the handle on a gas pump and watch *zombie a la mode* come out.

**Comment by stk2008** [comment]
LOL this is a rather funny bug tbh :P

**Comment by Frost-wood** [comment]
Sometimes you need to buy a dead zombie... for mutagen.

**Comment by DavidKeaton** [comment]
Or companionship, but that may be against what _was_ their moral guidelines.

**Comment by KA101** [comment]
.>_<

And I was rather enjoying my headache-free status after working up an idea to punish a certain insolent modder.  Thanks for that, DavidKeaton.

**Comment by DavidKeaton** [comment]
Awww I was merely joking. :-)

**Comment by mugling** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
