### ISSUE TITLE
Latinize non-Latin mutation categories

### ISSUE THREAD

**Issue by slitherrr** [CleverRaven/Cataclysm-DDA#11952]
To fit the pattern of the other categories, because consistency is nice. Also, they should all be adjectival, rather than a mix of adjectival and nominal.

"Lizard" -> "Reptillian"
"Bird" -> "Avian"
"Fish" -> "Piscine"
"Beast" -> "Bestial"
"Cattle" -> "Bovine"
"Insect" -> "Insectoid"
"Plant" -> "Botanical"
"Slime" -> This one is actually pretty difficult. There's probably a biological word that will fit, but I can't find anything immediately, mostly because "slime" doesn't really refer to a real animal with a taxonomy, but kind of a fantasy composition of slime-like attributes.
"Cephalopod" -> "Cephalopodal"
"Rat" -> "Murine" [source](http://boards.straightdope.com/sdmb/archive/index.php/t-291011.html)
"Chimera" -> "Chimeral"
"Raptor" -> "Saurine" (note that "raptors" includes Hawks and the like--there might be a more specific word than "Saurine", but "Raptorial" will typically mean modern birds rather than dinosaurs, and is probably less appropriate a replacement for that reason)

Note that there's some inconsistency here--"Bovine", "Ursine", "Feline" and the like all refer to families, but "Piscine", "Cephalopodal", and "Saurine" are all rooted in other levels of taxonomy.
##

**Comment by Rivet-the-Zombie** [comment]
How about Slime -> Protozoan?

**Comment by facepalm** [comment]
> "Beast" -> "Bestial"

Moreauvian

> "Insect" -> "Insectoid"

Arthropodal

>"Slime" -> This one is actually pretty difficult.

Amoeboidal

>"Chimera" -> "Chimeral"

Chimeric

>"Feline"

Jesus Christ it's a lion, get in the car

**Comment by KA101** [comment]
Aside from working around the id strings, sure, I could probably work this in, though I'm not particularly bothered by the difference ATM.

Raptor kinda needs to stay raptor ("raptor" in quotes, at least) as it's specific to that type of saurian, IMO.  *KA101 thinks "saur" and envisions a critter with multi-tile neck and tail*

**Comment by facepalm** [comment]
"Dromaeosaurid" would work.

**Comment by KA101** [comment]
FWIW, a major function of these names is to let players immediately get some handle on what the mutagen's going to accomplish.  ;-)

**Comment by ArikVhedrovix** [comment]
Slime => Ameboid ?

**Comment by karols146** [comment]
Amoeba have a consistence most close to slim, and sound good too.

**Comment by Zireael07** [comment]
+1 for Ameboid.

**Comment by drbig** [comment]
I do support this issue. **Consistency** is *the thing*.

**Comment by i2amroy** [comment]
Yeah, I like consistency too, but I feel that a major point of the names is to let the players know what the heck the category is supposed to be. I don't know about you, but if I saw something like "Murine mutagen" in the game I'd have no idea WTF that item was supposed to be mutating me into, where "Rat mutagen" is rather obvious what I'm going to be changing into.

**Comment by KA101** [comment]
> but if I saw something like "Murine mutagen"

Immediate reaction: The Few The Proud **The Murines**

XD but probably not what we're looking to achieve.

**Comment by bumpkindda** [comment]
I think this is a great idea, just want to note that you could use Greek as well without a consistency issue, since science does that all the time.

- If 'Raptor' changes into some kind of sauron-derived word, I'd suggest "Rapax" (latin, predator) or "Therion" (greek, beast) for the Beast mutagen.

- Murine could always be Rodentia, there are no other rodents vying for the name.

Suggestions for unmentioned humanlike chains, and please correct my doubtlessly terrible Latin grammar/tenses...

Alpha ; Homo Alpha 
Elf-A ; Homo Sylvan 
Medical ; Homo Remedia
Troglobite ; Homo Subterrenus

**Comment by chaosvolt** [comment]
Troglobite: Homo Uristus Alcoholicus.

Also, the recipes referencing these mutagens are titled as PE-0XX with the mutation category in quotes afterward, so it seems reasonable to allow inconsistencies if they avoid confusion. They seem to be descriptive of the category characteristics rather than official nomenclature for them.

**Comment by slitherrr** [comment]
Right, but in that case it's nerdy scientists generating the names, and category descriptions with Latinate (or Greek) names would be just fine as jargon within that crowd.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
