### ISSUE TITLE
Animals aggro to you once aggroed by zombies/ other factions

### ISSUE THREAD

**Issue by Headjack** [CleverRaven/Cataclysm-DDA#11969]
like it says. Presumably extends beyond animals.
##

**Comment by kevingranade** [comment]
Monsters only have one anger number, so once it's increased by interacting
with one thing and that thing is gone, it transfers to the next closest
target.
This isn't a bug though, if you make an animal angry it will be angry in
general, it won't suddenly calm down just because one target is gone.
'aggro' is a gaming concept that is used to make team fights more
interesting, and while it might be worthwhile to add it at some point
before we have functional NPC teams, it won't remove the effect you're
seeing here, which is if something makes a default-passive animal angry, it
will tend to lash out at anything nearby.

**Comment by Headjack** [comment]
If you say so, all I experienced was a Moose suddenly shoot at me like a rocket from across the feild once a crawler tapped him. Felt irritating he wouldn't go after more zombies instead, or just run off.

**Comment by Coolthulhu** [comment]
I have some ideas on how to further develop the monster AI. Mostly animal AI, but also robot and alien AI. Not sure about zed AI, because I don't know how much of it they should have.

1. Faction-dependent anger/fear stats. That way a creature could be angry in general, angry at zombies, but still neutral to squirrels and cats.
Separately for at-spawn anger/fear and for incoming anger/fear. Say, half the anger value going towards general anger, half towards faction anger.
So a moose angry at zeds would be still quicker to get angry at the player, but not necessarily angry enough to charge.

2. Making hostility (and fear) depend not just on mood, but also on some other factor - probably distance.
This way an angry moose from the example above could see the player standing far away and not charge, but attack the same player who then comes closer.

3. Having "dominant mood" and "per-faction mood" cover both anger and fear at the same time.
This way a bear (afraid of fire) could stay away from the player wielding a torch, but still maul a zed kid standing in the way of escape. Or just too near.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
