### ISSUE TITLE
dead vehicle engine kills brakes

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#11987]
When the engine dies, I should still be able to brake the vehicle, rather than having to coast to a stop.

**Comment by Rivet-the-Zombie** [comment]
Yeah, brakes should be losing a good bit of their efficacy when the engine dies (no vacuum system means no brake booster power) but they certainly shouldn't stop functioning entirely.

**Comment by Coolthulhu** [comment]
The `thrust` function is supposed to allow braking. Quite quickly at that: easily 20% of current velocity per turn of braking with no engine, with a lower cap of 10km/h drop per turn.

For some reason it doesn't trigger. It's probably a rounding error somewhere, because most of the code executes (it properly outputs "there is no engine" when trying to thrust), it just doesn't do the things it is supposed to do.

**Comment by nonymous** [comment]
If your brake booster goes out, your brakes still work the same as ever, but you're going to have to push a lot harder on the pedal to make them work. Just like with a loss of power steering, the car is still totally drivable, and stoppable, that is if you're strong enough.  Fun fact: brake vacuum boosters were introduced in 1928, and took a while to catch on, so there's __a lot__ of old vehicles that never had them.

**Comment by sparr** [comment]
Well, if we want to simulate it another step more realistically, full braking power would persist for some braking after the engine goes off, while the hydraulics are still primed, then it would decrease in effectiveness after that.

In a large truck I don't think it's possible to press the pedal hard enough to produce the same braking force that the hydraulic brakes do. You'd break the pedal or a cable first.
