### ISSUE TITLE
Possible new sound implementation(s)?

### ISSUE THREAD

**Issue by i2amroy** [CleverRaven/Cataclysm-DDA#12056]
I was speaking with GroverCurseHouse on the IRC about possible ways to deal with sound muffling over distances that would still be efficient even with larger number of sounds, and the idea of a "sound map" came up. The basic idea would be that rather than alerting each monster manually to sounds we could instead build a sound map each turn and then have monsters process it similar to the way they handle scent. This could possibly allow for more realistic sound handling where things like footsteps don't go through walls near as well as they would through open air without too much of a slow down.

Other thoughts? Other Ideas? Concerns?
##

**Comment by Rivet-the-Zombie** [comment]
Very clever. I've always thought it odd how sound travels through solid material like it wasn't even there.

**Comment by Coolthulhu** [comment]
Scent map is quite expensive. While the idea itself is good, I can't think of how to efficiently generate the sound map.

How would sounds propagate? Letting it "flood" outward from the point of creation would be really expensive.
The best solution I can think of would be populating the sound map with all sounds (just the volumes in the place where they're emitted) and having it do something like Dijkstra pathfinding with the emission points as starting open set. Always picking the point with highest value, adding it to closed set, then adding its neighbors to the open set with values equal to [own value - cost of getting there].

But this would involve essentially doing something as costly as a Dijkstra pathfinding run on the entire reality bubble each time turn in which a loud sound is emitted.
I played with Dijkstra pathfinding a bit and it wrecks performance on my CPU when 3 medium-sized (1/4 of reality bubble) runs are done per turn. Though this was with actual pathfinding using `map::ter_at` and the like rather than operating on a cache that doesn't need looking up submaps.

**Comment by KrazyTheFox** [comment]
I have no idea how the current sound code works or how tiles are accessed on the map, but a rather unoptimized Java implementation of A* with early bailout when sounds are no longer hear-able processes quiet sounds (~10 sound) in ~1-2ms (with 2000 entities) on a reality-bubble-sized map.

The same implementation runs into major slowdowns when processing louder sounds that more things can hear. I can process 2000 entities on the same map in ~8 seconds for a noise value of 150. 

Bringing the entity count down to 150 for a noise value of 150 takes ~800ms. At 10 noise, 150 entities process in well under half a millisecond.

I account for sound absorbency in this implementation for tiles (ex, walls could be 50, open air is 1) as well.

I'll see if I can't tweak this a bit, as I think I have a good starting point. At the very least, it's many times faster than Djikstra pathfinding. I can work up some pseudocode if anyone's interested.

**Comment by Coolthulhu** [comment]
> This is done with a diagonal shortcut heuristic.

You mean regular 8-direction or some more advanced jump point thing? If regular 8-direction then it applies here. Something more advanced would first need to be analyzed for whether it is OK to use with our weird many-to-many pathfinding.

I used Dijkstra rather than A* because with many targets the choice of heuristic isn't obvious. I could have used distance to the centroid of targets, but didn't think of it back then.

A great deal of the slowdown was certainly the result of me not caching the data and operating on public methods from `map` class, resulting in tons of extra bounds checks and submap lookups. Because of that your findings may be better than mine, provided caching itself doesn't get too expensive.

**Comment by KrazyTheFox** [comment]
After some testing, it looks like I'll need to go back to the beginning and think of more ways to optimize this. With either Dijkstra or A*, pathfinding takes far longer on loud, but not excessively louder noises as it attempts to path through many parts of the terrain instead of a direct route. This ends up taking minutes instead of fractions of seconds, making it obviously unusable.

Diagonal shortcut being this:
```java
int xDistance = Math.abs(x - end.x);
int yDistance = Math.abs(y - end.y);
if (xDistance > yDistance) {
	return 14 * yDistance + 10 * (xDistance - yDistance);
} else {
	return 14 * xDistance + 10 * (yDistance - xDistance);
}
```

Even though this looks good, it took about 4 minutes to calculate:
![pathfinding2](https://cloud.githubusercontent.com/assets/3086301/7220815/79b6c094-e6a3-11e4-9a55-607a72274710.png)

Whereas this took less than 3 seconds:
![pathfinding](https://cloud.githubusercontent.com/assets/3086301/7220825/b03b0328-e6a3-11e4-9327-21feb6cb5cd4.png)

**Comment by kevingranade** [comment]
It's currently using a clustering algorithm to cut down on processing, we
might be able to use clustering with A* to get the best of both worlds.

**Comment by i2amroy** [comment]
Note on optimizing as well, but you might look into nonadmissable/inadmissable A* heuristic as well to speed things up. The paths nonadmissable A* heuristic generates are very similar to the absolute shortest path (and are actually closer to the way that people pathfind in the real world), as well as requiring much less processing in most situations:

Some comparison pictures:
Cells checked:
![cells checked](https://takinginitiative.files.wordpress.com/2011/05/chapter-5-figures.jpg)
Two paths (The green one isn't the shortest, but I know if I was walking that's the way I'd have gone).:
![path comparison](https://takinginitiative.files.wordpress.com/2011/05/sp.jpg)

I mean you can easily see results of up to 50% timesavings (and a nice realism bonus) at only a tiny loss in path length.

**Comment by i2amroy** [comment]
Just a note, but there are a few other high level tricks you could probably use to speed that up as well. Since we're using a grid-based map with a very high branching factor you might want to look into just using a standard linked list or something similar for your storage instead of the usual priority queue. Also you might look into is early exploration of successors with similar or lower F costs to save yourself some more costly open list operations.

**Comment by Coolthulhu** [comment]
> It looks like there should be a way to cache the paths already generated and branch off a nearby path 

That's pretty much mandatory.
You certainly don't want to run pathfinding on every pair of sound cluster<->listener. That gets unbearably slow very quickly.

For my pathfinding tests, I had a bit easier problem - many-to-one pathfinding (many monsters trying to track down player). To solve it, I started pathfinding from the target (the player) and searched until the set of points to find was empty. Every n cycles I'd go through the set of points to find to check if any of them are in closed set (ie. have been found) and removed them.

In the many-to-many problem, the solution could be very similar to what I did. Since we're doing "area finding" rather than regular pathfinding, points would be prioritized not by how close they are to the starting point, but how high is their value. Value would decrease rather than increasing the further it gets from the starting point.

I see it like this:
* Add all sound emitting points to open set with value (essentially "inverted distance") equal to volume
* Create a set of destinations from the positions of all listeners
* Pathfind for a while
* Once in a while (good heuristic required for what is "a while") check if all destinations are in the closed set. If not, go back to pathfinding
* If all destinations are closed or if no points are in the open set, end the algorithm

**Comment by kevingranade** [comment]
Is this what was meant by flood-fill?
At the end of each turn:
Sort the sounds by volume (descending).
For each sound, flood-fill, bounded by obstacles and previous louder sounds
with a simple vector pointing toward the source.
That sounds somewhat tractable, the key simplification is that each monster
only cares about the single loudest noise, so the sounds don't need to
overlap, so you can do a lot of early termination.

**Comment by Coolthulhu** [comment]
Flood fill would have one trait that could be considered undesirable:
The loudest sound would easily drown out all others, even at large distance. For example, zombies bashing down a car (volume 12) would completely silence a nearby walking player (volume 6) as long as he'd stay within the area flooded by the bashing sound.

By "completely silence" I mean even the creatures that couldn't hear the bashing would be totally incapable of hearing the player, due to player's footsteps being unable to get out of the area bounded by previous, louder sound.

**Comment by i2amroy** [comment]
It also leads to problems where the corner overlaps near the source. It's conceivable a flood fill could "pass through" squares that had already been looked at but still have enough strength to carry out the far side.

**Comment by Coolthulhu** [comment]
Having current flood fill overwrite the previous passes when it carries more volume could easily lead to situation where a lot of sounds overwrite each other at the edges. Depending on the number of sounds, it could easily be slower than the pseudo-pathfinding.

For a low number of sounds, it would probably be faster, though.

**Comment by kevingranade** [comment]
> The loudest sound would easily drown out all others, even at large distance. For example, zombies bashing down a car (volume 12) would completely silence a nearby walking player (volume 6) as long as he'd stay within the area flooded by the bashing sound.

That's not undesirable, that's intended.  The player can discern different sounds and chose among them, but monsters will just go after the loudest sound.

> It's conceivable a flood fill could "pass through" squares that had already been looked at but still have enough strength to carry out the far side.
> Having current flood fill overwrite the previous passes when it carries more volume could easily lead to situation where a lot of sounds overwrite each other at the edges

That's why I said to apply the loudest sounds first, progressively more and more of the map would become impenetrable to new sounds.

**Comment by Coolthulhu** [comment]
> The player can discern different sounds and chose among them, but monsters will just go after the loudest sound.

Here's an mspaint diagram to show what I'm talking about:
![sound diagram](https://cloud.githubusercontent.com/assets/1878860/7245704/5f2b6402-e7f0-11e4-8d88-63f61acc6d16.png)

The silent sound will not be able to reach anyone, not even those closer to it than to the loud sound source.

Say, 3 critters are in line: loud (position 0), silent (position 98) and listener (position 101).
Loud one produces 100 volume. Silent one produces 99 volume. Listener is 3 tiles from a noise source that produces 99 volume, but hears absolutely nothing due to the way flood fill muffles noises.

**Comment by kevingranade** [comment]
Thanks for the illustration, that made my mistake clear. I'm assuming a
degenerating flood-fill that decays the magnitude with distance from the
caller, but I never said so.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
