### ISSUE TITLE
Can we do away with dynamic spawn mode yet?

### ISSUE THREAD

**Issue by Rivet-the-Zombie** [CleverRaven/Cataclysm-DDA#12064]
It's seriously deprecated, and it's silly.

Discuss.
##

**Comment by Headjack** [comment]
I'm assuming dynamic spawn is the opposite of static spawn, so if that's wrong just ignore this.

One of the best experiences I've ever had in Cata was one time when I was living out of a farmhouse shortly after hordes went in. I had fortified it with spiked pits all around and in strategic formations nearby. A massive horde swung by and I spent about a whole gameday fighting them off, dodging around pits, and ducking inside to get food and supplies. 

If there's no way for zeds to aggressively come around and threaten you then the game is far too static. Even with hordes on now only a few trickle toward my base at a time, since they no longer seek out light if I recall the changes. One of the issue's I had noticed then was that the hordes spawned mobs wherever you were near them, then those zeds stood around that area forever. The ideal system would have individual horders moving through the world in the same way as NPCs, so they might miss you and move on. That's probably hard to make; not my field.

I don't know about coding and I don't know what changes have or haven't been made already, but my opinion is that we need some way for base-builders to be threatened after already having cleaned out an area. Zombies need to remain threatening, and give you a reason to fortify a base and set up traps, because it's very thematic as well as so thoroughly supported by what's possible as to make little sense if outside attacks are rare.

**Comment by Zireael07** [comment]
I don't see a point to dynamic spawn anymore, now that we have (optional) wander spawns and the upgrade zombies functionality. The upgrade does pretty much everything that dynamic spawn did (provide increasing danger as time passes) without the annoying 'Zs out of hammerspace' effect.

**Comment by kevingranade** [comment]
Pretty sure Rivet means the dynamic spawn option, which has nothing to do
with hordes.  Dynamic spawn is the old way zombies were spawned such that
they would appear near you if you were in a 'zombie zone'.
Hordes is a separate feature where zombies or other monsters move around at
large scales.

**Comment by Zireael07** [comment]
I know about the zone thing, that's why I mentioned the 'Z out of hammerspace' effect.

Still I suppose wander spawns (if one uses them) and upgrade zombies feature make dynamic spawn near obsolete.

I think the main selling point of the dynamic was the fact that it spawned harder monsters later from the start, instead of all at once, so you simply couldn't encounter a mi-go in the first two or three days. But the Z out of hammerspace effect annoyed many players, me included.

**Comment by Parahacker** [comment]
Question: does this all reference the 0.C stable? That's the one I'm using, and I've been a bit mystified as to which worldbuild options to use. I want traps to be relevant, and I don't want to feel too safe after killing all the Z's in an area - sure, for a week or two, but after that... so I'm using static zombies = false, wander spawns = true. Would static zombies = true, wander spawns = true achieve the effect I'm looking for?

**Comment by Rivet-the-Zombie** [comment]
Yeah, I'm referring to the dynamic spawn world parameter, not the spawn system used for wander spawns.

Wander spawns are awesome, and they pretty well accomplish what dynamic spawn is supposed to do (sure they still need a bit of work, but they're already far better than dynamic-materializing zeds in locked closets) without the weird side effects brought about by dynamic spawn.

**Comment by Parahacker** [comment]
so... yes? 0.C stable, static & wander both set to true will keep traps relevant even in areas cleared out?

**Comment by Rivet-the-Zombie** [comment]
@Parahacker Yeah, static spawn and wander spawn both set to true gives you a world filled with zombies that stay gone when you exterminate them, with additional groups of zeds wandering around and keeping things interesting.

**Comment by Headjack** [comment]
I think that sounds about right, except that my experience with wander spawns is underwhelming. Is there some way to work in actually threatening roamer hordes you'd want to hide from or prepare for?

**Comment by Coolthulhu** [comment]
Due to the way hordes spawn once and then don't ever despawn, there's no way to hide from hordes at the moment.
Threatening hordes will come naturally with buffed zeds.

**Comment by sparr** [comment]
I was always under the impression that this was an option in the same way that NPCs are an option... meant to be turned on fwen the feature is stable and complete, temporarily turned off by default for development.

**Comment by kevingranade** [comment]
You got it Sparr, and yea, it's about time to get rid of it, it hasn't
worked right in a long time.

**Comment by graysage1** [comment]
>It's seriously deprecated, and it's silly.

I was just about to try it.  Why is it deprecated, I don't understand?  The idea that the world should sometimes be an unpredictable and self-regenerating place is not an outdated idea, is it?  I don't think it makes any sense for resources to permanently disappear unless they're finite.  So deer have sex and make more deer.  Even if you kill some, they should continually spawn unless you go on some explicitly genocidal effort or something.

What about zombies?  If I understand the mythos of CDDA, people have sex and make babies, and the alien goo or spores or what have you, keeps infecting more people, hence, zombies should constantly spawn.  Zombies should not be a finite resource that disappears after a short time.  Newly infected people should appear on the scene.

So maybe the way dynamic spawns are implemented is not a good one, but the idea behind a world that's always renewing and self-maintaining is not wrong in my view.  So if you clear out a cave, maybe 3 months later when you were long absent, some raiders moved in and claimed it for themselves.  Why can't this happen?  This needs some kind of dynamism when it comes to spawning unless you want to implement sex and reproduction and infection simulations in great detail.  Dynamic spawn is just a shortcut for reproduction and possibly new infections.  That way we just assume reproduction happens, and don't simulate it, but instead just ad-hoc spawn more deer here and there, more roving bands, new zombie arrivals, and so on.

>Wander spawns are awesome, and they pretty well accomplish what dynamic spawn is supposed to do (sure they still need a bit of work, but they're already far better than dynamic-materializing zeds in locked closets) without the weird side effects brought about by dynamic spawn.

I see.  Then maybe we're all on the same page.  I think some optional dynamism is great.  If you think some particular implementation of it doesn't live up to the promise, yea, why not get rid of it.  Initially I thought you were against dynamic and self-renewing environments.

**Comment by Rivet-the-Zombie** [comment]
>What about zombies? If I understand the mythos of CDDA, people have sex and make babies, and the alien goo or spores or what have you, keeps infecting more people, hence, zombies should constantly spawn. Zombies should not be a finite resource that disappears after a short time. Newly infected people should appear on the scene.

~99% of everyone is already dead, so human population growth is pretty negligible at this point.

>So maybe the way dynamic spawns are implemented is not a good one, but the idea behind a world that's always renewing and self-maintaining is not wrong in my view. So if you clear out a cave, maybe 3 months later when you were long absent, some raiders moved in and claimed it for themselves. Why can't this happen?

The problem is that dynamic spawn doesn't do any of this; it automagically materializes zombies in weird places like closets in response to the player making noise.

**Comment by graysage1** [comment]
@Rivet-the-Zombie 

>~99% of everyone is already dead, so human population growth is pretty negligible at this point.

You probably mean the humans.  There is a ton of wildlife in the game.  So at least wildlife and the ecology appears pretty robust, so wildlife should continue respawning.  If anything, taking the humans out has probably helped prevent the global warming and other human-made ecological disasters.

On the other hand, maybe the aliens are continuing with their invasion.  So may, just maybe, as the numbers of zombies decline thanks to your character's efforts, the aliens keep arriving through their portals or space ships.

>The problem is that dynamic spawn doesn't do any of this; it automagically materializes zombies in weird places like closets in response to the player making noise.

I'll agree that this is probably a bad implementation of a very good general idea.

**Comment by Zireael07** [comment]
Wildlife continues respawning regardless of the dynamic/static setting - the setting only affects Zs.

**Comment by i2amroy** [comment]
That said I would like to eventually move everything to a pseudo-static system. Wildlife and whatnot would be tracked in static groups that can move around the map, and then would make occasionally rolls for population growth/zombifications/etc. The result is a static system that makes sense, yet can still grow and move around the map.

Personally I'd be fine if we wanted to do away with Dynamic spawn now, but I'd really prefer it if we could get at least some of Hordes 2.0 in prior to wiping it off the menu completely.

**Comment by graysage1** [comment]
>That said I would like to eventually move everything to a pseudo-static system. Wildlife and whatnot would be tracked in static groups that can move around the map, and then would make occasionally rolls for population growth/zombifications/etc. The result is a static system that makes sense, yet can still grow and move around the map.

It sounds interesting, but I am still in favor of some dynamism, because a world that's slowly becoming useless and lifeless is not a fun thing to have, imo.  Granted, the CDDA maps are so huge that before one runs out of new territory to explore I can even imagine how much time would pass.  So maybe it's not that big of a problem.

So I like your idea for a more precise simulation, but to my mind as great as that idea is, it shouldn't compete with the idea of dynamic hordes and so on.  They're two great ideas which are great for different reasons.

Also, if you're going to track animal population growth and decline, you may want to consider doing the same for human population growth and decline as well.  And, maybe, allow the player a slim chance of reversing the population decline by take extraordinary actions, like maybe, building some kind of energy barrier towers around some huge tract of land to protect it from bad influences, and decisively clearing that tract off zombies and oozes and so forth.

Maybe "protect humanity" can be an optional and super-difficult goal for the player.  Just a thought.  So if we do end up with a static system, I think it should not be a fatalistic scenario.  There should be some ray of hope there, imo.

**Comment by Rivet-the-Zombie** [comment]
>It sounds interesting, but I am still in favor of some dynamism, because a world that's slowly becoming useless and lifeless is not a fun thing to have, imo.

The problem with dynamic spawn is that it **does not** prevent this. Dynamic spawn **does not** simulate moving groups of zeds, or any other moving groups (wander spawns does, kinda sorta). It **does not** simulate populations of creatures which go up or down in response to the environment. It magically creates zombies out of thin air whenever the player makes noise - *and that's all it does*.

**Comment by graysage1** [comment]
@Rivet-the-Zombie I agree 100%.  I think it's mostly a language issue because when I say "dynamic spawn" I don't necessarily mean the obsolete game mode.  Sorry about that.  I mean it in very general terms as spawns that are regularly introduced into the world, periodically.  Nothing more.

I am not defending any implementation that is widely agreed to be obsolete or bad.  I understand there are *very* good reasons for why the old dynamic spawn game mode is becoming obsolete.

I wish there was a way to talk about dynamism without implying something about an obsolete game mode.  I don't like to create confusion.

**Comment by Rivet-the-Zombie** [comment]
Yeah, the terminology available to this discussion leaves a lot to be desired.

Improved wander spawns would go a long way toward keeping the game-world exciting, and the spawn system for some of the wildlife (I'm looking at you, fish) could use improvement as well.

**Comment by graysage1** [comment]
@Rivet-the-Zombie I agree completely.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
