### ISSUE TITLE
Additional Mutation Categories: Need Help/Balancing Suggestions

### ISSUE THREAD

**Issue by Camkitsune** [CleverRaven/Cataclysm-DDA#12060]
So I'm working on adding a set of additional mutations and categories to go with them...

```
So far, I've drawn up the following five catgories:
```

VULPINE 
   Some similarities to Lupine set; omnivorous, benefits are broader, but less pronounced.
PROCYON (AKA Raccoon)
   Heavily specialized for Dex and subterfuge at the expense of Strength and HP.
SIMIAN
   Less extreme parallel to the PROCYON line; a lot of negative effects relate to crafting.
MUSTELID (AKA Badger)
   Carnivore alternative to the Ursine line; faster, but not as tough.
TETSUDINOID (AKA Tortoise)
  Ultra-slow, tough, and tanky herbivore.

   I also have JSON objects for the following mutations
TAIL_BUSHY (Bushy Tail)
  Gives a dodge bonus between LONG and FLUFFY versions, can be used to warm hands similarly to pockets.

TAIL_HANDY (Prehensile Tail)
   Gives a dodge bonus between LONG and FLUFFY versions, provides bonus reduction to hand encumbrance.

TAIL_RINGED (Ringed Tail)
   Identical to FLUFFY version, essentially just an alternate aesthetic.

MUZZLE_VULPINE (Vulpine Muzzle)
   Alternate version of the Lupine muzzle; bites happen more often but are less damaging.

MUZZLE_MUSTELID (Broad Muzzle)
  Aesthetic variant of the MUZZLE_LUPINE mutation.  May have the inverse effect of the VULPINE variant when implemented.

VULPINE_FUR (Vulpine Fur)
   Aesthetic variant of the LUPINE_FUR mutation.  May provide camouflage benefits with less damage reduction.

PROCYON_FUR (Patterned Fur)
   Variant of other fur mutations; gives less of a defensive bonus but provides camouflage in the dark.

STRIPED_FUR (Striped Fur)
  Variant of other fur mutations; gives less insulation vs. cold.

VULPINE_EARS (Fox Ears)
  Aesthetic variant of LUPINE_EARS.  Also has CANINE version as prerequisite, but has a slightly weaker effect.

PROCYON_EARS (Triangular Ears)
  Aesthetic variant of FELINE_EARS.  Effect is identical.

DIGITGRADE (Digitgrade Feet)
   Post-threshhold evolution of Padded Feet/Raptor Talons; provides a 20% speed boost while feet are unencumbered, but makes 'rigid' footgear unwearable.  

HEAVYBROW (Heavy Brow)
   Negative mutation. Adds a base encumbrance of 5 to the head.

CUTE1, CUTE2 (Cute, Adorable)
   Appearance modifiers, mutually exclusive with Terrifying and Pretty/Ugly lines; work as inverse to Growling Voice.

SMALL (Small)
   Mutually exclusive with LARGE & co, reduces strength but increases dex.  

LITHE (Narrow Frame)
   Mutually exclusive with BURLY; reduces hp but provides small bonus to dodge.

BURLY (Broad Frame)
   Mutually exclusive with LITHE; reduces evasion modifier but
increases melee damage.

ANALYTICAL (Analytical)
   Mutually exclusive with SCATTERBRAINED; makes it slightly easier to learn recipes.

SCATTERBRAINED (Scatter-brained)
  Inverse of ANALYTICAL; makes it slightly harder to learn recepies

CONCENTRATION (High Concentration)
  10% buff to concentration gain.

DISTRACTABLE (Short Attention Span)
  Concentration gain reduced by 10%.

INVENTIVE1/2 (Inventive, Wunderkind)
  Crafting-related; tasks take less time, and have a lower failure rate.  INVENTIVE2 sometimes results reenforced items

CRUDE1/2 (Poor Design Sense, Abysmal Design Sense)
  Inverse of INVENTIVE, makes crafting take a bit longer, and increases failure rates.  CRUDE2 often results in damaged products.

PRESTIDIGITATION 
  Pretty much obligatory with the addition of Raccoons and Monkeys;  reduces the time required for non-crafting manual tasks by 25%, increases success rate of lockpicking

I had the following questions:
1) Do any of these things have any immediately obvious balancing problems?  For the ones with no listed degree of effect, what seems like a good ballpark figure?
2) For the implementation of the Digitgrade effect, would the most effective route be to add an additional tag ('SUPPLE' perhaps) to 'flexible' footgear?  
3) Are there any additional effects that people would want to see added in? 
##

**Comment by i2amroy** [comment]
Honestly I think if you are going to be making new categories they really need to have more that defines them from the others than "is basically X, but with cosmetic differences". I mean maybe if we get subcategories or something I could see it, but it seems fairly overkill when the only difference between two categories is that that one has carnivore instead of TOUGH3, and their fur is a different color. I think we'd need something to that ensures that a category is unique before we separate it out from the others. (In addition categories with lots of overlap are much more difficult to actually breach the threshold for, URSINE actually gets a hardcoded bonus to it's thresh rolls to account for this).

As for the actual mutations that you've come up with:
>TAIL_BUSHY (Bushy Tail)
Gives a dodge bonus between LONG and FLUFFY versions, can be used to warm hands similarly to pockets.

To me this seems like it should work more like an extra warmth bonus while sleeping than magic pockets.

>TAIL_HANDY (Prehensile Tail)
Gives a dodge bonus between LONG and FLUFFY versions, provides bonus reduction to hand encumbrance.

Prehensile tails are cool, but I'm not seeing how it helps you with most of the tasks that hand ENC performs since it's behind you. It's not going to help you with something like shooting a gun or something similar. If I had to name an effect I'd probably go for a crafting speed increase personally, but eh.

> camouflage

I'm not really seeing a good way to implement something like this mechanics wise.

>DIGITGRADE (Digitgrade Feet)
Post-threshhold evolution of Padded Feet/Raptor Talons; provides a 20% speed boost while feet are unencumbered, but makes 'rigid' footgear unwearable.

For 20% I'd probably say block all footwear entirely.

>PRESTIDIGITATION 
Pretty much obligatory with the addition of Raccoons and Monkeys; reduces the time required for non-crafting manual tasks by 25%, increases success rate of lockpicking

This would be:
1) Extremely difficult to code
2) Very prone to breaking on new code addition
Most of the time-based stuff for tasks is handled right where the task is done. This would mean that you would need to add a check for the mutation into every single manual task location. Even assuming you found an easy way to do this on the code side I'd probably prefer a number of more around 10%, maybe with a 5% "Nimble Fingers" mutation. Monkeys might have clever hands, but normal old human hands are just as good or better a lot of the time.

**Comment by Headjack** [comment]
You should talk to KA101 before you put too much effort toward that.

**Comment by i2amroy** [comment]
>You should talk to KA101 before you put too much effort toward that.

1) At this point we currently have no idea if KA101 is coming back or not.
2) Asking questions here is always fine regardless. Though one dev may often focus on a particular area, that doesn't mean that input is confined to just them. :P

**Comment by Frost-wood** [comment]
I feel these categories need to have more "unique" traits as a lot of these categories overlap with mutations already in the game(Cute-pretty).

**Comment by Rivet-the-Zombie** [comment]
These are all just repainted versions of existing MUTCATs. Is it really so objectionable that somebody's DDA character has a 'fluffy tail' whose descriptive text doesn't perfectly match the appearance of their furry internet avatar?

I'd be behind this if they were actually different from the stuff we've currently got, but as it stands this is the same stuff we already have, just with slightly different descriptions tied to it.

**Comment by Headjack** [comment]
Wait, what? Did he leave or something?

**Comment by Rivet-the-Zombie** [comment]
>Did he leave or something?

That's how it looks right now. Sorry I don't have better intel than that.

**Comment by Headjack** [comment]
Shiiiit, this is just like when Freezerbunny went weird and vanished, right when we were gonna play that DnD campaign. Maybe there's a cuuuurse.

But yeah, point being, this sounds like mod material, honestly.

**Comment by DeNarr** [comment]
I'm not a big fan of mutations that are just aesthetic variations on one another. Especially because with random mutations it would increase the chance of lame results, like losing fluffy tail to get a ringed tail.

Also, heavy brow should provide minor glare resistance.

**Comment by graysage1** [comment]
I notice all your suggested categories are Earthly.  Considering the world of CDDA is under the influence of an alien invasion, some mutations should be alien too, imo.  So we shouldn't try to create mutations that blindly mimicked Earth animals.  I imagine the boffins researching mutations would be interested in something better than raccoons.  There would be completely devastating and unnameable mutation types that are alien-inspired and are completely experimental and artificial and have little to nothing to do with the Earth life.  One example of this already in CDDA is the goo/ooze mutation.

>Honestly I think if you are going to be making new categories they really need to have more that defines them from the others than "is basically X, but with cosmetic differences". 

I strongly agree.

**Comment by i2amroy** [comment]
>Considering the world of CDDA is under the influence of an alien invasion, some mutations should be alien too, imo.

Actually "aliens from the stars" (like UFO's and stuff) is one of the small handful of things that we specifically have stated is *not* going to be showing up in the C:DDA universe. :P Nether creatures and similar stuff is something we'd probably put in, but no green men from the stars.

>goo/ooze mutation

Mutations are caused by the goo. You getting a goo mutation is just them working on reverting you to their default state. :P

**Comment by graysage1** [comment]
@i2amroy I think all CDDA mutations can be divided into two categories. Spontaneous and designer.  Spontaneous mutations can be animalistic and they can be bad for the player.  Designer mutations should probably rarely be animalistic, they should be more along the lines of bio-weapons, super-firefighters, super-doctors, super-scientists, etc.  I just can't imagine a team of boffins working on turning their patients into racoons except as a preliminary stage for something greater.  Becoming a racoon wouldn't be the goal of research, imo.

So I think designer mutations can be bad ass because they're intentionally designed to minimize bad traits and maximize good ones.

>Nether creatures and similar stuff is something we'd probably put in, but no green men from the stars.

Sounds great to me.  I just don't know what to call creatures like mi-go.  I chose the word "alien."  It's not from this Earth maaaann. :)  What do you call mi-go?  It's not a zombie.  It's not an animal.  I call anything weird that I don't know what it is "alien."

**Comment by i2amroy** [comment]
It's a Nether denizen, technically, but you could also call it a "minor nether faction", since it's one of those as well. Nather denizen is probably what you are looking for in a case like this.

**Comment by Camkitsune** [comment]
Apologies for the delay in responding, work's been a b*tch lately.  Will try to get each thing in turn.

When I was originally coming up with new mutations I was strictly applying them to the new categories I was implementing; for some of the more generalized ones this struck me as a bit...  well, BAD, for some reason.  Most of the lines DO have at least some unique/semi-unique traits to them, though if anyone has some good suggestions for additions I'm all ears.
Additionally, since URSINE_EARS, ELFA_EARS and FELINE_EARS were all already things...  I was operating under at least the partial understanding that some mutations WERE expected to be aesthetic reskins.  That said I can certainly ditch several of them.

VULPINE:
No, I will not deny that doing this one was at least partly motivated by my being a furry.  That being said, this WAS an attempt to fill a niche that as far as I'm aware hasn't really been fleshed out, namely the side of the game that deals with crafting and things that deal with Int.  I tried to make the 'variant' mutations be a bit more than purely cosmetic.  For the tail and the fur, the idea was that they didn't provide as great of a benefit as the LUPINE set's, but had an additional utility effect that made them unique.  The ears could probably be taken out, though.  Aside from these, the Fox and Cephalopod lines are the only two to get the Wunderkind mutation.  It also makes use of INT_UP_2, which was until now only used as a stepping-stone for the Cephalopod's INT_UP_4.  

MUSTELINE:
The only one without any mutations specific to it, will remove unless someone can come up with a reason to justify having it.

PROCYON:
While I originally didn't have as clear of a concept for this one, it's basically evolved into a blink-tank.  On the one hand, it has a lot of drawbacks associated with it that affect pretty much everything associated with strength.  On the other hand, it gets DEX_UP_4.
Since the suggestion to split up PRESTIDIGITATION into two stages makes a lot of sense, this line will end up as the one that gets the second stage in its line.

SIMIAN:
This one is unique in that it's supposed to represent at least a partial regression of some of the things that make Humans unique.   It gets several of the negative traits related to crafting (in at least one case exclusively), and is the only line that picks up Prehensile Tail - which really does need to be a thing even if the implementation of it needs work - and potentially an acquirable version of the Parkour Expert (if it doesn't just use Parkour Expert; see questions at the end).  Could probably also include a 'long arms' mutation that makes grappling easier.
It also occurred to me that the line might include a couple of mutations relating to mutant's mind regressing to a more primitive state, reducing Int but raising Dex (IE your brain becoming less wired towards 'thinking' and more towards reacting quickly), thoughts?

TETSUDINOID:
This is the other of the two I-didn't-really-think-this-one-through categories, so much so that I haven't even really started working it in.  It's just that SHELL2 is already apparently in the dataset - and not presently covered by any of the other lines, IIRC - as are all of the other things that it would need.  It does lack anything truly unique about it, though...

i2amroy:
-Your suggestion for Bushy Tail's secondary effect makes more sense, will use instead.
-Regarding the Prehensile tail, while I agree that the fact that it's behind you and lacks fingers does mean that you're not exactly going to be wielding another gun with it, having a crafting speed bonus as its only bonus wouldn't really be enough to justify its existence.  On the other hand, it DOES occur to me that it would take some getting used to in order to make full use of - should probably have a second stage similar to LARGE/HUGE where its bonuses actually start to apply.
-I had originally planned to base the implementation for this off of how Inconspicuous was being handled; since I haven't had the chance to properly comb through the program yet, this may end up getting dropped if it isn't tenable.
-20% is a bit excessive; 15% would probably be better.  This actually relates more to a problem I have with how being 'bare-footed' is handled than anything, since I don't think that having nothing but a pair of socks on should either cancel the bonuses from Padded Feet/Digitigrade OR the penalty from going barefoot under ordinary circumstances.  It could simply be handled via  having checks against Padded Feet/Digitigrade/Barefooted ignore skintight-layer clothing.  Digitigrade would obviously also need the whole 'can accommodate mutated anatomy' thing as an additional requirement to being able to wear something.
-The numbers you've given for Prestidigitation make more sense.  As far as what tasks it would actually work with, the scope should probably be more specific; I had only originally seen it as applying to purely manual tasks, namely lock-picking and reloading times.

Frost-wood:
-Cute is supposed to work a bit differently than Pretty, in that - as far as I'm aware - the latter doesn't have negatives associated with it.  It was conceived as having an effect inverse to the Growling/Snarling/Hissing voice traits; making it mutually exclusive with Pretty and its extensions seemed necessary to prevent their effects from stacking to potentially ludicrous levels.

Head-Jack:
-Originally this was going to be just a mod; the problem is that having a bunch of mutations without being able to define their effects would result in a bunch of mutations that the game wouldn't know what to do with, in turn meaning that they had no actual effect other than canceling out the ones that DID do something.  This does give me an idea, though...  Will possibly start another issue related to it tomorrow when I have more time.

Graysage:
-Regarding the practicality, I had planned on introducing a separate lab journal for the mutagens of 'dubious practicality': apparently written by one of the junior scientists, and covered in red ink comments noting the enthusiasm but berating the lack of practical applications.  Considering it isn't abnormal to find cocaine in the dormitories of the labs, it wouldn't be too much of a stretch, I think...
-Nether-critter style mutations could be interesting, did you have any suggestions for possible candidate mutations?


Lastly, a couple of additional questions while I'm here...
1) Does the "valid" attribute for JSON mutation objects denote that the mutation won't be selected randomly - IE, that it will potentially appear in the 'potential mutations' pool for its listed MUTCATs, but nowhere else?  Or does it mean that it won't appear at all?
2) Is there a functional difference between "changes_to" and "leads_to"?

**Comment by graysage1** [comment]
@Camkitsune 

>did you have any suggestions for possible candidate mutations?

Sadly my knowledge of lore is not particularly well developed in that area.  I don't want to make silly suggestions.  I'm going to leave this one to people who know better than me.  There are people out there who love the lore about Nether creatures, so they're in a better position to give ideas than I am.

**Comment by BevapDin** [comment]
>  Is there a functional difference between "changes_to" and "leads_to"?

Yes. Both control what new mutation one may get, but "changes_to" replaces the original mutation, while "leads_to" will add the listed mutation.

For example M_SKIN (which has entries for both) will change into M_SKIN2, which replaces M_SKIN (both mutations are thereby mutually exclusive). But it can also lead to getting M_DEFENDER (which does not interfere with M_SKIN, both can exist at the same time).

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
