### ISSUE TITLE
You succumb to the infection.

### ISSUE THREAD

**Issue by Rivet-the-Zombie** [CleverRaven/Cataclysm-DDA#12085]
This message is randomly popping up now. No ill effects, no infections anywhere, it seems to have no genesis.

**Comment by i2amroy** [comment]
That message shows up literally one time in the whole codebase, and it's behind a rather strict wall that hasn't been changed codewise for several months now, nor can I replicate it at all. I'd say something went wrong with your build somewhere, but barring that the only thing I could see this being is a strange memory read error.

**Comment by Rivet-the-Zombie** [comment]
I've had it happen to me once, and I was reminded when I saw it happen to a let's player tonight, so I know it's happened to more people than just me.

**Comment by i2amroy** [comment]
In that case I can honestly tell you that whatever the heck this bug is it's not something normal. Literally the only way to have this happen is to have the "infected" effect with a duration of greater than 14400. And then two lines later (the immediate next one being the memorial log entry) the game deals 500 damage to all of your body parts and kills you.

Unless somebody put that message in a mod somewhere we're looking at something reading that by pure chance (the chances of which are astronomical).

**Comment by Rivet-the-Zombie** [comment]
Sounds like we've got a mystery on our hands!

**Comment by Coolthulhu** [comment]
Possibly translation related. A bad string lookup could cause gettext to read garbage. If the message isn't `m_bad` (usually in red), it's probably a bad string lookup somewhere.
Things like this can happen if someone tries to translate an empty string.

If it doesn't cause a memorial log entry (in file save/worldname/[random symbols].log), it's certainly not executing the infection succumbing code.

**Comment by facepalm** [comment]
Can NPCs become infected and die?  I once had this message, then I noticed my starting NPC had died off, and attributed it to that.

**Comment by BevapDin** [comment]
@i2amroy ever since the monster infight update they will target and attack NPCs, that can easily lead to an NPC being infected. You found the source of that message, it's printed there with the *global* `add_msg`, which will print the message regardless which player (or NPC) is infected. All other messages there use `add_msg_if_player` or similar.

What probably happens is that an NPC is infected by an attacking monster and later  recheas that infection state where the message is printed.

**Comment by Rivet-the-Zombie** [comment]
It also seems to be tied to messages to the effect of 'you feel nauseous, but your stomach is empty', which is probably more messages intended for the NPCs.

**Comment by i2amroy** [comment]
>Bevapdin

Ah, good point. That would definitely do it.
