### ISSUE TITLE
bad AIM (advanced item menu) sort order stability during movement

### ISSUE THREAD

**Issue by graysage1** [CleverRaven/Cataclysm-DDA#12108]
In most of the recent builds when I use aim to move one item from a stack in a dragged vehicle to another location, the stack will often jump suddenly so that I can no longer just hit "enter" and reliably watch the stack count decrement.  At any time during the decrementing process the stack can "jump out of" being selected.  I believe while this problem happens at other times, when I notice it most is when I move things to and from a dragged vehicle.  I notice often the item selection jumps to a different location long before its count of items has been depleted when holding down "enter" to move it.

In essence, moving items from pane to pane should never affect the sort order.  But now it appears to do so.  If it matters, I tend to use 'c'ategory sort order.

**Comment by Coolthulhu** [comment]
Could be solved by moving the last item from the stack first rather than the first item.

In default sort order and category sort order, item order is determined by the first item of the type.
For example, skewer,rock,rock,skewer will have skewer before rock. After moving the first skewer, rock x2 is now before the second skewer.
By moving the last item first, the first item of the type would remain in its position and so order would be preserved.

**Comment by Ishindri** [comment]
Yeah, before the recent AIM overhaul, items were alphabetical under category sort.  Maybe that could be reverted, or switched to a toggle?

**Comment by Coolthulhu** [comment]
Two-pass sort will be easy, will restore.

**Comment by Coolthulhu** [comment]
It is supposed to be fixing them alphabetically too. Not sure why doesn't it work.
The sort function used is `std::stable_sort`, it first sorts by category and then lexicographically.

Categories are inserted and sorted as if they were items, so no way to maneuver there.

Any ideas?

**Comment by graysage1** [comment]
I'm happy to say in 0.C-3068 cb7dabb this issue appears to be resolved, or at least, I can no longer trivially duplicate it.

**Comment by Coolthulhu** [comment]
Oops, I merged BevapDin's fix, but forgot to close the issue.
