### ISSUE TITLE
Fungaloid spores are fungaloids

### ISSUE THREAD

**Issue by SarahJohnson489** [CleverRaven/Cataclysm-DDA#12106]
Playing Cataclysm 0.C build 3035

For some reason, rather than spores being spawned it spawns fungaloids as seen here when I rammed my way out. 

![untitled](https://cloud.githubusercontent.com/assets/5564796/7269131/1e982fdc-e87d-11e4-8b6a-2ade89120b00.png)

**Comment by tyrael93** [comment]
Fungaloids and dynamic spawning, especially post-spring, are fucked beyond the point of no return.
I'm still waiting for a crutch mod to remove fungaloids and zombie animals, like rivet was planning to do a while ago, since removing dynamic spawns seems to be a concept too far in the future to even hope it will be made.

**Comment by i2amroy** [comment]
Actually the problem here is with the new upgrade code failing to properly set the last check date for new fungus. I'll see about taking a look into it sometime today/tomorrow.

**Comment by tyrael93** [comment]
The problem still stands though.

**Comment by Headjack** [comment]
Confirming, they just should be popping into spores, but are multiplying instead.
