### ISSUE TITLE
It's currently hard to UI-manage bulky and heavy items

### ISSUE THREAD

**Issue by graysage1** [CleverRaven/Cataclysm-DDA#12120]
So I understand why game balance requires that certain items be bulky and heavy.  However, the UI should not be burdened by this fact.  Here's what I mean.

Suppose I just made a bunch of charcoal, and charcoal is both heavy and voluminous, which is fine.  Now I also have a charcoal food smoker, which again is heavy and voluminous.  So how do I reload it?  Right now I am required to pick up both charcoal and the smoker, which I think is not whatsoever reasonable.  This means I can only "afford" to pick up a tiny amount of charcoal in addition to holding the smoker in my hands, up in the air, straining under its weight.  This isn't right.  This is absurd from the UI point of view.  I realize that reloading the smoker can be slow in terms of game stats, but why should the UI be so tortured to perform such a trivial task?

Instead why can't I reload anything that's on the ground, using any available resources from any nearby tile?  In terms of game balance I am perfectly fine with this taking more time than reloading a small thing with another small thing that's in your inventory.  So this isn't about game stats.  This is about menu input.  You know, the keystroke count?  I've been harping on it recently.

So in the end yea, I can reload my charcoal smoker, but I have to do it 10 charcoal at a time sometimes, unless I want to dump my whole inventory just to reload the smoker faster, which I don't think is reasonable at all.  The end result is unnecessarily slow and tortured keystroke input that makes something simple, like reloading an appliance, into the player typing a small poem into the CDDA.

There are lots of things like this in the game.  It's not just the charcoal.

Another example.

I have a giant water drum on the ground with 450 charges of water in it.  It's huge.  I want to get some of that water into my canteen.  Right now if I want a convenient way of doing this, I have to first empty the tank onto the ground, then mount the tank to a frame, then I can 'e'xamine the frame and 'd'rain its water into my canteen.  But why???  Why can't I siphon and drain any container that's on the ground?  Why do I have to pick them up first?  It seems unreasonable.  Even in real world terms, if I were taking a water from a huge drum, I wouldn't be holding it in my hands.  I'd be siphoning from it using a rubber hose anyway.

So my point is, moving bulky stuff around should be way easier than it is.  Maybe you'll want to require a rubber hose and other tools for this?  But generally I think it should **not** be a strict requirement that the player first have the item in the inventory before manipulating that item.

Another example.

I have a makeshift welder in my wheelbarrow.  I want to reload it.  Why do I have to take both the welder and the battery stack out first?  Why can't they just sit in the cart while I reload them?

I can go on.  But I hope the point is clear by now.  I think if you want such actions to take long in-game-time like 1 6-second round per 100 batteries, or 1 6-second round per 10 charcoal or per 10 units of liquid, I don't mind.  I don't mind paying that kind of game balance price, so long as the UI input is simple and convenient to me as a player.
##

**Comment by Coolthulhu** [comment]
> Instead why can't I reload anything that's on the ground, using any available resources from any nearby tile?

Up until quite recently, searching both the current inventory and the ground at the same time wasn't nicely unified and required a big, ugly block of copy+paste to achieve it. For this reason most of the code only considers the inventory.

The two functions that can view both the inventory and the ground are: liquid container selection (the original function that did it) and eating.

So there's no real reason not to do it, only for why isn't it done yet.

**Comment by graysage1** [comment]
>So there's no real reason not to do it, only for why isn't it done yet.

Awesome. :)  So I will keep my fingers crossed to see it in one of the upcoming builds one of these days.

**Comment by sparr** [comment]
The compare-items ("I") interface also looks at inventory and ground.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
