### ISSUE TITLE
Vehicle Physics (Speed,Breaking)

### ISSUE THREAD

**Issue by stk2008** [CleverRaven/Cataclysm-DDA#12136]
I think I have mentioned this before but I really don't see why these cars can travel at speeds of 500mph+ and then stop in an instance.

I was told its not an easy fix?.

Some info on vehicle stopping distance

http://www.csgnetwork.com/stopdistcalc.html

Not sure if this would help at all?.

Maybe we could have another vehicle part added that you place on each wheel you want breaking force on

Brake disk and caliper.

http://www.aa1car.com/library/disc_brake_operation.jpg

I don't know if this would help with vehicle speeds or why the cars in CDDA are so fast as I can't read code but

https://wahiduddin.net/calc/calc_speed_rpm.htm

I do apologies for posting links even more so if there no use but I think having real vehicle physics etc would be awesome :).

We could get really deep into vehicle construction how cool would it be to actually have an engine construction screen then add that engine to a vehicle LOL :O
##

**Comment by graysage1** [comment]
I like the idea of requiring various types of breaks to even allow any breaking at all.  Even bicycles have breaks.  The only exception to this is a shopping cart or a wheelbarrow, which don't require breaks to stop.  How is a car without breaks supposed stop?  From then on, it's only natural that better and worse performing break systems may exist in the game.

**Comment by narc0tiq** [comment]
*brakes

**Comment by stk2008** [comment]
Maybe for shopping carts etc we could do a check for if your feet are touching the floor and use them as breaks.

But as for cars,bikes etc yeah we should have a bike brake part and a car brake part with different performing brakes :).

I would love to see moddable engines say you find a super charger and place it on the same tile as the engine to gain performance ( I am a mechanic and its not this simple in real life LOL we need intercoolers retuning etc etc)

But from a game point of view it could be cool.

Or we could find turbos,remampped ECU`s etc etc.

**Comment by Oskar636** [comment]
as for bikes, if this is possible, maybe the higher the speed is, it'd damage the shoes, or the feet if there are no shoes on your character

**Comment by graysage1** [comment]
@stk2008 

I strongly agree with all your ideas here.

**Comment by tvm1** [comment]
Brakes are complicated.

There are mainly two variants of brakes (drums/disc), but if this had to be implemented, then it would be sensible to aim for other things too. In current state, you magically take a 30" wheel from truck and add it to small car without any problems (or add it somewhere, just to have more wheels). Drum brakes or regular disc brakes require certain compatibility with the wheel, chassis, brake cylinder, hoses, etc.

Good compromise would be to have a wheel with brake as a single item (which could be upgraded/disassembled) via recipes to something else (eg., wheel with drum brake, disc brake, ceramic brake or electromagnetic brake}.

The car braking performance would depend one the sum of braking power available on the installed wheels/brakes.

Moddable engines would be also fun, but I think that it would make only little sense in larger context. In game, where you have to struggle hard to boil your water, you just don't magically attach/remove/adapt turbos, intercoolers or custom ECUs (from salvaged parts). This would be days of work even for experienced workshops which are skilled/specialized in such car tuning.

Also, I've checked briefly, the car engines seem to be way too light. Single inline-4 should be at least 150kg, if not more (70kg currently). Even simple automatic transmission is hell to install for two people with _proper_ tools in real life. Perhaps the engine hoist could be added as a required tool to remove and install engine ?

Just my two cents.

**Comment by Rivet-the-Zombie** [comment]
>Also, I've checked briefly, the car engines seem to be way too light. Single inline-4 should be at least 150kg, if not more (70kg currently). Even simple automatic transmission is hell to install for two people with proper tools in real life. Perhaps the engine hoist could be added as a required tool to remove and install engine ?

I've always wondered about this, but chalked it up to the game taking place in the 2040s; maybe most cars use aluminum engine blocks by then.

**Comment by graysage1** [comment]
@tvm1 

I don't think CDDA should go the Forza/Gran Turismo route in terms of vehicle modding complexity, so maybe we can assume that all wheels have brakes on them, just as you say?  If so, maybe wheels can be differentiated not just by width, radius and weight, but also by their built-in breaking properties?  This could be a nice solution that I hope is not overly hard to implement.  If I understand your suggestion correctly, it seems to be a good one to me. :)

**Comment by tvm1** [comment]
@Rivet-the-Zombie 

In fact, you are probably right. They can build state-of-the-art all aluminum engines that are near this weight right now, but that would apply for engines - say up to 3.0L. Anything above that (or truck engines) are heavy things. Currently the V12 is only at 165kg.

Point is, that if you install engine, you need to remove it somehow  out of the car, grab the new engine and put it into place (that means, tighten the screws, couple it with clutch/transmissions, join the drive train while the engine remains at certain position, where it has little support, until it's fastened against all these other things). This act is currently technically impossible without hoist, unless the engine is very small (motorbike) or you use some kind of other support (bricks, logs, whatever).

Another option would be to make the removal/installation without the hoist *very* lengthy (like 10x normal time needed to do the task with hoist).

@graysage1 

I agree completely. That's why my rather simple "wheel with drum brake / wheel with disc brake" would probably work and could be easily implemented. Wheel with brake could be disassembled to disc brake and wheel. You could use wheel without brake too, bit it wouldn't provide any braking power. In fact, when I think about it, it could be fun. Imagine finding a badly smashed car without working brakes!

**Comment by graysage1** [comment]
@tvm1 

This hoist device you speak of, is it something stationary?  It doesn't sound very portable to me.  I mean you can't put it in your backpack, right?

**Comment by tvm1** [comment]
@graysage1 

It would be something like [this](http://www.northerntool.com/images/product/2000x2000/144/144847_2000x2000.jpg). The hoists need to be heavy duty to support the engine weight. The weight would be around, say 125kg. Player could carry it with his hands and put it inside his vehicle, but it should have large volume. The item could be spawned at public works, fire stations, etc.

**Comment by graysage1** [comment]
@tvm1 A picture sometimes is worth a thousand words. :)  So this thing is very roughly like an industrial sized shopping cart on casters, in a sense.  It should be draggable.  It's a vehicle.  It can't be folded and it can't be put into your backpack.

>Player could carry it with his hands and put it inside his vehicle, but it should have large volume.

I can see this thing going into the back of a pickup truck.  I can't imagine stuffing it into some small sedan.

**Comment by tvm1** [comment]
@graysage1 

Agreed. It should be the only thing that allows you proper engine change, IMHO.

**Comment by stk2008** [comment]
Hi all sorry for the lack of replies I have been busy.
so many great ideas in

an engine crane is what your talking about and yes I think that would be really good to have in cdda.

if we do implement braking we will need to give tyres friction im not sure they have that now? so we could simulate braking in all kind of weather conditions :) and also allow us to have high performance tyres and low end tyres that perform better in different situations.

**Comment by i2amroy** [comment]
Tires have this interesting value that basically represents a combination of friction and area IIRC.

**Comment by stk2008** [comment]
i2amroy 

Ah I did not know that as I am no programmer I have not looked at the code as I would have zero idea what I am looking at any way LOL.

Well this is good to know any way :).

**Comment by Coolthulhu** [comment]
Braking is currently hard-coded. It's values haven't been balanced properly due to the code being broken for years and also effectively over-written by the engine - most braking right now uses the engine, which may not be perfectly realistic in combustion engines (pretty sure electric engines do support this, though).

Implementing some simple differences in braking wouldn't be hard, but someone would have to provide real data, compare it with in-game values etc.

**Comment by stk2008** [comment]
Cool well engine braking in real life off course is real hence why you shift to say 1st or 2nd to help slow you down when going down hills etc but its not as good as it makes it out to be like it is in CDDA LOL.

As for electric motors in real life when u lift of the throttle and the car is cruising it will charge the batterys up as the motor will act like a genorator this to is what happens in real life but in CDDA it does not.

I shall look for some real world data and post it here as soon as I can :)

**Comment by kevingranade** [comment]
The main thing missing here is traction values for wheel/terrain
combinations.  When braking, we could apply a certain amount of
deceleration per wheel, per square crossed based on the type of terrain
crossed, it would range from dry pavement, to turf, to wet pavement, to icy
pavement, etc.  I'm not sure if it would be better to give different
wheel/terrain combinations different properties, or just have a range of
traction values for each and just add them together.

Also, when braking player skill could factor into how quickly the vehicle
decelerates, and adjust the chance of the vehicle skidding.
Likewise acceleration should be traction dependent.  In the extreme case
certain vehicles should have a chance of getting stuck if they aren't on
pavement.

This all assumes we have brakes on all wheels, making brakes separate items
would be a different issue, but I'd be fine with having them.

**Comment by tvm1** [comment]
Since there are are no ECUs and such details in CDDA, can't we just assume that cars in 2040 had some sort of ABS/ASR/ESP or whatever 80's system ?

It's de facto standard now that the currently built cars are able to distribute their braking power and do their best to stop the car at shortest possible distance while maintaining the original direction and preventing skid. It could be assumed that if weather == snow || rain, the braking performance could be nerfed a bit.

Adhesion, speed and vehicle mass are the main factors when determining the braking distance. Technically the biggest IRL factor is the condition and pattern of the tyres and their compound. The longer you are able to decrease the kinetic energy of vehicle effectively while not skidding, the shorter will be the braking distance.

When I think about it, it makes the previous brake variants idea kinda of redundant.

**Comment by ejseto** [comment]
I find it odd that in this discussion of vehicle realism nobody mentioned how ~10 mph = 1 tile/turn ~= 1m/6s = 10m/min = 600m/h = 0.6 kph. The braking distances look a lot more realistic when you consider the ~27 discrepancy factor here. It's never going to seem realistic until this discrepancy is cleared because there will always be something inconsistent.

**Comment by i2amroy** [comment]
Course then we run into problems where a player driving on a road at even a little over a decent speed (say 70 MPH or so) is going to run into the problem where it becomes literally impossible for them to stop before hitting obstacles because they can't see them in time due to the reality bubble edge.

As such I'd probably say drop the discrepancy factor to one much closer to reality, but still leave in at least some of a factor to account for our ultimate sight range imposed by the reality bubble.

**Comment by ejseto** [comment]
The time scale is just too large to have any kind of realistic driving that's also consistent with the rest of the game world. Just imagine if you could only steer/brake/etc. once every 6 seconds while driving. Either  you have to pretend (or ideally, change) the timescale is a much more realistic one, or you have to pretend the distances are much greater than 1m/tile ONLY while driving, there's no other way to reconcile it.

**Comment by kevingranade** [comment]
It's going to be a pain in the ass, but at some point I'm going to switch
around the timescale to be one second instead of 6.

**Comment by Leland** [comment]
Vehicles have changed a *ton* since the last comment here. Is this worth keeping open? Can this be closed?
