### ISSUE TITLE
Crash when loading old save

### ISSUE THREAD

**Issue by stk2008** [CleverRaven/Cataclysm-DDA#12135]
Win7 64 bit
Mshock tiles x32

CDDA version the save was created on dev 3041 x64 bit
CDDA version the save will not load on dev 3050 x64 bit

Error

http://i60.tinypic.com/1znohgh.png

I cant load my old save game crashes :(

Thanks for taking the time to look into this for me :)

**Comment by Coolthulhu** [comment]
Upload the save somewhere.

Meanwhile you can try changing the tileset until this is resolved. Also, this may be just a wrong installation. Unpack the 3050 to a new directory and copy only config and save directories from the old one.

**Comment by stk2008** [comment]
Hi Coolthulhu thanks for replying :).

BTW I love your contributions to CDDA mate I see a lot of Z level work and every time I get excited about it...Not that I have any idea what it means LOL but none the less I get excited :).

Here is my save file :)

https://www.sendspace.com/file/pe9w69

Thanks for the help

**Comment by Coolthulhu** [comment]
OK, managed to replicate it, but it only happens in 64 bit version. Play in 32 bit for now.

Totally no idea what could cause it.

**Comment by stk2008** [comment]
Ohhh thanks so much mate :) 

Will play in 32bit for now woooot :)

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
