### ISSUE TITLE
Suggestion: improving non-AIM inventory lists

### ISSUE THREAD

**Issue by graysage1** [CleverRaven/Cataclysm-DDA#12140]
AIM is generally great for item management, but I can't help thinking how simple item list screens are outside AIM and whether or not it's a good thing.  So I have some basic ideas:
1. Currently when you view items on the ground via 'g' (or comma) or 'e', the individual items do not stack, resulting in lists that are in some cases hard to manage.  I'd rather see something like "splintered wood (30)" then a list of 30 individual splintered wood entities.  In this case, there will probably need to be a similar method for selecting a number of items like we already have in the item menu 'i'.
2. Searching with '/' or 'f' like in AIM.
3. Sorting similar to AIM.

With luck, maybe AIM's code can be reused to avoid code duplication.  It would be nice if 'e' and 'g' item lists were not so bare bones.  AIM will always be needed because of its two pane ability.  I don't see that ever going away.  But that doesn't mean other item lists have to stay so bare bones.  I guess it just encourages the player to use AIM more often than is strictly necessary.

AIM is so good, that I sometimes use it instead of the 'i'nventory screen.  Consider: in the 'i'nventory screen to enable autopickup, I have to select the item then hit right arrow or enter, then plus, anndddd the item list is autoclosed, which isn't always a good thing.  By contrast with AIM, I select the item and hit 'p', and the list stays open.  I often prefer this.  AIM allows me to do anything the inventory screen lets me do and sometimes it does it even better.

So the 'i'nventory screen appears in better shape than the 'e' and 'g' item lists.  It has a sort by category, which is a nice default sort.  And it stacks similar items together, which again is very nice.  It's an improvement over the 'e' and 'g'.  I think adding other sort orders and searching functionality to the 'i'nventory screen would enhance it further.

If the AIM searching and sorting code is generic, it seems like a waste not to use it in more places outside AIM.  I mean, the code is already there, right?  Why not use it for 'i'nventory, 'e'xamine and 'g'rab item lists?   Just an idea.
##

**Comment by sparr** [comment]
I think one way to accomplish this would be to break the 'list of items' panel code out. The AIM would call it twice, the , menu would call it once, the ;V menu would call it once, etc.

**Comment by graysage1** [comment]
I'm closing this issue due to low interest.

**Comment by DavidKeaton** [comment]
not low interest, I see where you are going, just too busy to comment something worth salt

**Comment by Rivet-the-Zombie** [comment]
Yeah these are good ideas.

**Comment by Zireael07** [comment]
+1 from me, very good ideas.

**Comment by graysage1** [comment]
I'm leaving a note here for posterity, when/if anyone starts to touch non-AIM item lists.  There is a weird discrepancy between how the different lists are printed.  I notice that 'i'nventory prints a nice wide list with plenty of room for longer item descriptions such that I can see I am wearing a plastic canteen with clean water (6).  When I use 'a'pply, the same spacious item list appears and I can see what's what.  However, when I use 'E'at, then for some reason the list appears narrowed, all of it moved to the left, and now there is not enough room to print full descriptions for items with longer descriptions.  So when I try to 'E'at, I can't see how much water I still have left in my plastic canteen because it now gets cut off.  Of course I can find this out beforehand by using 'i', but that's kind of tedious.  This was still true as of build 0.C-3090 da97264.

**Comment by BevapDin** [comment]
> I'm leaving a note here for posterity, when/if anyone starts to touch non-AIM item lists. 

I leave a note for that case as well:

The code is probably using the wrong inventory UI function. There are two main functions for the inventory UI:
- one for single item selection - it has two columns: the main inventory and the worn/wielded items.
- another for selecting several items at once (e.g. for dropping them) - it has a third column: the list of selected items.

Both functions give each of the displayed columns the same width, more columns therefor means less space for each of them.

**Comment by Coolthulhu** [comment]
The eat menu has been changed relatively recently and it is its own function.
It is based on liquid container selection menu, repurposed to be generic.

**Comment by BevapDin** [comment]
Ah, yes, and that function is derived from the "compare items" function, which lists the selected first item to be compared in the third column (like multi-selection, only multi means 2 in this case and selecting the second item leaves shows the comparison and de-selects it).

**Comment by DavidKeaton** [comment]
in addition to my item PR, I could look into all this as well, as I would like to rework inventory ui to show contained items better.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
