### ISSUE TITLE
Science Lab overmap walls upgrade, underground Z levels fix

### ISSUE THREAD

**Issue by tyrael93** [CleverRaven/Cataclysm-DDA#12144]
Science labs are a very interesting place, especially now that the Labstart challenge has been introduced, but there are still some small problems that require a quick fix from someone more competent at coding than I am. As you all remember, before concrete walls we only had regular "walls" that worked for every building in the game, science labs too. They can be smashed with a weapon with at least 20 bashing and give splintered wood, nails and sometimes some rocks. You can light them on fire with a single lighter charge, as you would with a skewer. Now, there's a weapon, the homewrecker, that requires fabrication 0 to craft and that is very simple to do on your first or second day of the challenge.  Before it was the quarterstaff but after I addressed the problem someone changed the damage output from 20 bashing to 19 bashing, with some screenshots of a character "winning" the challenge repeatedly by just taking two points in fabrication and two in bashing weapons, quarterstaff, bash, out.

Getting out of the lab after not even a day is extremely underwhelming and in my opinion not worth 8 points at character generation, plus more mutations than with a regular character at chargen, especially when you count that you can just throw chuks of steel or two by fours at the turret around midnight, standing just outside of its line of sight, to make it explode without being shot back. 

I propose to upgrade the science lab's overmap walls to concrete,  and also to fix these random drywall-hallways in the underground levels (shown in the picture), with priority to the overmap walls.
![screenshot from 2015-04-23 20 42 29](https://cloud.githubusercontent.com/assets/5557920/7307097/b67e9f84-e9f9-11e4-8ae2-173eb170f302.png)

**Comment by Coolthulhu** [comment]
Yeah, escaping from labs is way too easy. This would make escaping from labs more of a RNG thing instead of a certainty.

Replacing the walls would be basically just going to mapgen.cpp, finding the entries for labs and replacing t_wall with t_concrete_wall there. Not hard at all, but moderately tedious, as labs still use the old mapgen code.

**Comment by Zireael07** [comment]
Even more reason to upgrade labs to new mapgen.

**Comment by graysage1** [comment]
>This would make escaping from labs more of a RNG thing instead of a certainty.

I believe no legitimate challenge should ultimate be an RNG thing.  It can be very difficult.  It can take 30 days and some sacrifices along the way.  But for a very skilled player solving a challenge should still be a certainty in my opinion.  If that's not the case, then it's not a challenge, but a gamble.

**Comment by Coolthulhu** [comment]
@graysage1 
Lab challenge is and will for a longer while be pretty necessarily RNG-bound for a while due to lack of mechanics preventing the RNG.

You can spawn with a turret in the room. You can spawn in a cage (sometimes with a shoggoth next to you). You can get a lab without proper food sources (human corpses or royal jelly to cure poison from tainted meat). Lab configuration could prevent some builds from ever going forward (low str + blocking turret = no progress).

Even with concrete walls, there will still be one semi-guaranteed way: deconstructing teleport traps for teleports and using those on z-level 0.

The idea of setting fire to the walls and waiting out the fire or just smashing the walls with a homewrecker was probably never intended. The latter wasn't even possible before a significant wall nerf.
Since the lab challenge is supposed to be challenge, it should be challenging.

There could be multiple sensible ways of escaping:
* Manufacturing some explosives or thermite or whatever and lighting it up (would require buffing explosives against static stuff)
* Dropping more jackhammers in the lab - a quest for jackhammer would be a good challenge
* Adding a second card scanner, this time inside. Or just moving the one outside so that it's accessible from both sides. Then cards inside the lab would have to be made rare. This is probably the easiest and most sensible solution to implement and could be easily made as a part of this issue
* Adding a portal to hell/Xen/whatever. This could easily open a portal to programming hell, though. So unless anyone knows really well how to handle that nicely, it won't happen.
* Adding a wall chipping feature and allowing a determined enough survivor to spend 3 days ramming a spike into the wall until it breaks

**Comment by graysage1** [comment]
@Coolthulhu 

>[RND can punish you instantly through bad initial placement of your character]

Is it possible to generate one guaranteed deliberately safe room in every lab, and then the challenge would always use that room when starting?

>Lab configuration could prevent some builds from ever going forward (low str + blocking turret = no progress).

I believe this can be legitimate because it tests your strategic judgement by demanding you create a proper build that's suitable for the challenge.

All scenarios shouldn't be obliged to support all builds.  As long as there is a reasonable variety of scenarios for every build, we're OK I think.  So if I am hung up on playing some build I'll have my pick of scenarios, but if I am hung up on a challenge, I may be asked to narrow down the builds I can create.

>Dropping more jackhammers in the lab - a quest for jackhammer would be a good challenge

You don't even have to drop them.  You can instead drop the occasional materials for those, and then ask the player to survive long enough to raise their mechanics skill to the appropriate level.  Gasoline jackhammer requires a small 1-cylinder engine, which you can hide on a deep floor guarded by strong opponents all around that floor.

>Adding a wall chipping feature and allowing a determined enough survivor to spend 3 days ramming a spike into the wall until it breaks

This doesn't sound too exciting.  It's realistic, I give you that.

**Comment by graysage1** [comment]
@Coolthulhu 

Can we consider a possibility for a character with high speaking/bartering skills to talk their way out of confinement?  It doesn't have to be so obvious as "Let me out of here."  "Yes, OK, here you go, you're out now."  Maybe it's that NPC who eventually gives you that 1 cyl engine you need for the jackhammer.

In any case, it's probably too difficult to brainstorm on this at the moment, so I'm abandoning this topic for now.  In closing I think the Lab challenge is a great idea and I like the idea of making it challening, but I don't like the idea of making it overly RNG dependent.  Some RNG dependency is inescapable, and that's fine.  But a resourceful and strategic player should have a huge upper hand in the challenge, imo.  The challenge should reward good play, imo.

**Comment by tyrael93** [comment]
I'm just saying that it's ridiculously simple to escape as of now and making the z0 walls concrete would fix the challenge. You're bound to find a teleporter or learn how to make an explosive, unless you find those labs that only go down two z levels, and even then you could find some way out.
Hell, I already have 3 teleporters and I have only started in a 3 z level lab. 
I don't know how updating the mapgen works, but for now I'll just turn my map's walls into concrete with the power of debug.

**Comment by vache** [comment]
Updating labs to the new mapgen (assuming you mean json) would be incredibly obnoxious in some places and impossible (currently) in others.

The big problem with a lot of solutions is that mapgen needs to get a lot smarter to accommodate them.  Labs actually have several potential ways to escape that are less obvious than blowing up the wall or teleporting outside.  Labs that intersect with sewers have a sewer entrance, there are instances of anthills that dig into labs, and so on, but these are too unreliable to actually be considered as possible means of escape.

A way to get around the randomness in the time being might be to add a static NPC nearby for the scenario that gives a mission to escape.  The start of mission setup could examine the conditions of the map and use the NPC to give the player some relevant item to escape, like some way of getting into a lab armory, a hacksaw to get into the sewers, an oxy torch to cut through the lab door, and so on.  This only works for players with static NPCs though, and it's a little gamey, though better a little gamey than putting the player in an impossible situation.

**Comment by Frost-wood** [comment]
Moving the labs to regular mapgen probably won't happen until we get computers json-fied.

**Comment by Zireael07** [comment]
Nice ideas with the NPC :)
