### ISSUE TITLE
Suggestion: mouse interaction in the 'm'ap mode can be comparable to normal view

### ISSUE THREAD

**Issue by graysage1** [CleverRaven/Cataclysm-DDA#12172]
In the normal game view, I can hover the mouse cursor over the terrain to see what everything is really quickly.  But when I switch to the 'm'ap mode, I now have to use the keyboard to move the blue cursor around the 'm'ap.  Mousing around is no longer an option.  I think it would be nice to be able to mouse around the 'm'ap the same way I can currently mouse around in the normal terrain view just to get a look at the things.
##

**Comment by graysage1** [comment]
Doesn't look like there is interest.  Closing for now.

**Comment by kevingranade** [comment]
It's totally valid, possibly so obviously valid there was nothing else to
add.

**Comment by DavidKeaton** [comment]
what he said, p straightforward, no arguments IMHO.

**Comment by graysage1** [comment]
Valid?  Alright, I'll reopen it then.  It's hard to know what people think if there is silence.

**Comment by DavidKeaton** [comment]
This is true, but with different time zones and the possibility of us clacking away or doing work things, hard to respond at times. :-)

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
