### ISSUE TITLE
Burst fire is broken.

### ISSUE THREAD

**Issue by Rivet-the-Zombie** [CleverRaven/Cataclysm-DDA#12244]
Just what it says on the tin.

Enable burst mode and fire; you'll only ever fire one shot.

Build 3088.

**Comment by ejseto** [comment]
In ranged.cpp, there are 2 overloaded versions of player::fire_gun(). They have different parameter types. The bool variable burst is being converted to an int, "burst_size," before being passed to the overloaded function. Since bool to int converts true to 1, the burst size is always 1, i.e. no burst.
