### ISSUE TITLE
"Athlete"-profession trait

### ISSUE THREAD

**Issue by Snaaty** [CleverRaven/Cataclysm-DDA#12242]
I am posting this issue because I want to create a profession trait for all (most) athletes but first want to see if other people would like to see that too, or if some of you have better ideas. 

I imagine a profession trait for all the professional athletes, that makes you burn less stamina when running and/or burn less (regenerate more) stamina when walking or resting. 

If you think that idea is good, tell me, if you have a better idea, tell me as well so I can do that instead.

**Comment by sparr** [comment]
There have been other discussions about an athletics skill to produce this sort of result.

**Comment by kevingranade** [comment]
There's already a 'expends stamina more slowly' trait that was either PRed
or possibly merged already.

**Comment by Rivet-the-Zombie** [comment]
>There's already a 'expends stamina more slowly' trait that was either PRed
or possibly merged already.

It was actually a 'has a 25% higher maximum stamina rating' PR; I've plans to touch the various bits of code where stamina is expended, and make it so relevant skills reduce the rate of burn by a bit (see: https://github.com/CleverRaven/Cataclysm-DDA/pull/12245).

**Comment by Snaaty** [comment]
Yes, I am aware of rivets traits, but as she said those affect maximum stamina, and not the recharge rate. I figured having as many profession traits as possible is a good thing while they should ideally include several professions, and athlete really seemed predestined for that.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.

----

See related discussion in #11887.
