### ISSUE TITLE
Lakes

### ISSUE THREAD

**Issue by AlchemistExMachina** [CleverRaven/Cataclysm-DDA#12253]
I've noticed that there's no actual large circular bodies of water in this game. With the boats mod and fishing, wouldn't it be nice to have lakes to cruise around in while you fish and slay zombie sharks? We could include islands with special island buildings, too.
##

**Comment by Voker57** [comment]
That's probably not the decided effect but sometimes there are

![lake](https://cloud.githubusercontent.com/assets/22776/7424688/29cf6726-efad-11e4-8001-531a148ec0f5.png)

**Comment by graysage1** [comment]
I like this idea.  One of the challenge scenarios can be to escape the island where you've been stranded.

**Comment by AlchemistExMachina** [comment]
Stranded island scenario would be so cool! It shouldn't be to hard to code lakes, just generate river tiles or a new type of water tile in a circular fashion akin to the city generation code. The only time we see lakes nowadays is when a river decides to end quickly, being as long as it is wide.

**Comment by John-Candlebury** [comment]
If it were possible to adjust the numbers of rivers in the original overmap, you could easily get some sort of archipielagos by setting it to a high number. Actually this can already happen if you manage to get lucky when new over maps are generated, but it requires a great deal of luck.

**Comment by graysage1** [comment]
Right now there is an unimplemented feature in the options called "Default region type" and it's set to "default" with the option for "desert_test."  Maybe later on this can be expanded to include an archipelago type environment.

**Comment by DavidKeaton** [comment]
already thought of a spooky overmap special.

**Comment by vache** [comment]
It already is possible to get some very interesting river/lake combinations from overmap generation, but it usually requires many times more exploration than the average survivor gets to see.

**Comment by graysage1** [comment]
>but it usually requires many times more exploration than the average survivor gets to see.

Maybe one should be able to pay an NPC to go explore a part of the map for you?  Wouldn't that be cool?  NPCs can in principle do lots of handy things.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.

**Comment by codemime** [comment]
@illi-kun Please, don't close Mapgen issues. They are a minority (27 for now), but I'm interested in most of them.

**Comment by illi-kun** [comment]
@codemime Okay, it's great you're interested in them. I've re-opened most of recently closed issues. Please let me know if you need some other issues to be open.

**Comment by codemime** [comment]
@illi-kun Thanks.

**Comment by Leland** [comment]
It's worth noting that there are ponds in the game, but they're insanely rare. I've only ever come across 1 or 2. Also see unmerged PR #18884

**Comment by Leland** [comment]
With the most recent overmap special overhaul in #21212 ponds are actually spawning now. There are more _lakes_ as well but they're not visibly marked as such and their mapgen is a little wonky. They basically just look like weird, orphaned rivers. The issue for that, however, is https://github.com/CleverRaven/Cataclysm-DDA/issues/18583

Closing - @codemime not trying to step on any toes, of course. Feel free to reopen if there's more to be done here.
