### ISSUE TITLE
Arm/hand encumbrance does not affect melee 

### ISSUE THREAD

**Issue by tyrael93** [CleverRaven/Cataclysm-DDA#12265]
Just like it says on the tin, this is something that has bugged me for a while. Bindles are just free storage if you're not planning to go ranged, same goes with briefcase(s) and shopping bags.
BIndle volume: 20 (can wear two in hand slot and still use any weapon of choice, can be crafted at very start of the game for 40 units of volume with virtually no drawbacks)
Briefcase volume: 24 (can wear two in hand slot and still use any weapon of choice, encumbers hand & arm slot, harder to find but when you do it's 48 more volume.)
Shopping bag volume 20 ( can wear two in hand slot and still use any weapon of choice, hand slot, 40 volume for free)

Basically my survivor is going around with two bindles taped to his hands, two briefcases and two shopping bags. 

And he still hits without any penality whatsoever to his attack speed or melee skill. Not only this is silly by default, but it's also very overpowered, since melee can carry you though all the game as of now, except against turrets (but if you don't disable survivor armor and wear heavy survivor armor you can take on even rivtech-tier turrets with a simple knife)

The solutions I propose are different.
A) make it so that you need to actually wield the bindle/briefcase/bag. This could be problematic since there are no items as of now that work that way and also annoying.
B) Add a malus for hand and arm encumbrance which works exactly like torso encumbrance does. This is more viable. A survivor could wear all of those AND decide it's a great idea to attack that zombie with his knife, only to see every attack fail as the zombie slowly eats his face.
C)Limit a survivor to only one bindle/briefcase/shopping bag & implement solution B. This is more drastic.

I'm partial to B honestly, mostly because the current arm/hand system is bonkers.

**Comment by Coolthulhu** [comment]
Now that we have stamina in game, arm encumbrance could penalize melee attack stamina.

Not sure what to do with hand stamina. Gloves shouldn't make it harder to swing an axe. Hand-only storage clothing (currently shopping bags and baskets) is stupid, but that should be addressed by extending the encumbrance to arm rather than nerfing gloves.

Limiting number of "worn" items would also be good, but not as strict as at-most-1. I'd say 100 encumbrance limit on any body part. That would allow 2 bindles, but not 2 bindles+briefcase.

**Comment by graysage1** [comment]
+1 to @Coolthulhu 's answer.

**Comment by vache** [comment]
To me, forcing wield of the hand-container makes the most sense.  Unfortunately, without a containerized inventory, it would also be the most annoying.  It could open up interesting possibilities if there were a dual wielding system though.  A rugged briefcase could be used to shove away zombies and block attacks, while a knife follows in the other hand.

**Comment by graysage1** [comment]
I don't like the idea of managing multiple containers.  I like how in the current system containers just add volume.  So we still simulate the carry capacity limit without any of the hassle of actually micromanaging what stuff is in what container.  We've moved slightly away from that by allowing holsters, but because holsters only store or or two items, that's not so bad.

**Comment by DeNarr** [comment]
Would it make sense to move shopping bags to give arm encumbrance? Because while you do technically hold it with your hands, it doesn't really stop fine manipulations, which is what gloves do. Meanwhile, it would make moving your arms around quickly much more difficult.
