### ISSUE TITLE
Removing the battery wont disable a car's alarm

### ISSUE THREAD

**Issue by John-Candlebury** [CleverRaven/Cataclysm-DDA#12277]
Well I've never stole a car before, but I'm pretty sure that removing a car's battery should make the alarm stop, if not instantly at least eventually.

Perplexingly, removing the horn does make the alarm stop, even though most car alarms don't rely on the horn exclusively.
##

**Comment by stk2008** [comment]
Disconecting a cars battery SHOULD not disable alarm,

Most alarms even cheap ones have a battery back up for that very reason.

But yes removing the horn should NOT disable alarm as you say.

**Comment by John-Candlebury** [comment]
The backup wont last forever though, its probably only got juice for a pair of hours at the most.

**Comment by stk2008** [comment]
Totally agree I'm not sure how long the battery backup lasts possibly 1hr?

**Comment by stk2008** [comment]
As a matter of fact 

A friend of mine had an alarm that would sound when the car battery was actually low.

It was a high end alarm.he left the car stood for a long time while he was away and the alarm kept going off due to the actual cars battery being low

Maybe we could add this to a few cars in cdda.

I enter a town and hear an alarm from the north its a car alarm it would attract monsters etc.

Or maybe monsters knocking into cars could set them of :)

**Comment by Oskar636** [comment]
In build 5868 windows 64bit console, removing a car horn from a vehicle doesn't stop the alarm, and @stk2008 said that removing the battery shouldn't stop the alarm.
