### ISSUE TITLE
Socks as gloves? :)

### ISSUE THREAD

**Issue by stk2008** [CleverRaven/Cataclysm-DDA#12295]
Hi all while watching my bro play he woke up with freezing cold hands and we could not find gloves.

We did see how ever some socks and he said could we not put them on our hands to keep them warm.

I think this would be a great idea and off course balance it out with huge ENCUMBRANCE making it really only practical for when you sleep or last resort.

Suggestions?

**Comment by FireCrow1973** [comment]
you can also cut of the front of the sock, and make them in to wrist warmers.
that's what i do with my old wool socks!

**Comment by stk2008** [comment]
Ha good idea.

This is meant to be a survival simulator after all we need more optoins.

at the end of the day we would do this in real life if need be be :p

**Comment by jcd000** [comment]
I like it. More options for the creative survivor.

**Comment by FireCrow1973** [comment]
i'm wondering if we could do some sort of mode change, or something.
you could flip some sort of a switch, turning socks in to mittens!
that way we would avoid another crafting recipe, and you could switch it right back again.

i agree it should be hard to do stuff with sockttens.
(like your hands are numb, but there not!)
but you could throw them on when your traveling or sleeping.

**Comment by Coolthulhu** [comment]
Scarves already have a mode change, but it doesn't cause them to change armor slot. This would require a separate check or else you could bypass some limits.

**Comment by stk2008** [comment]
Scarves have that function?

What's the scarves do mate Mate I'm intrigued? :)

**Comment by Coolthulhu** [comment]
They get their warmth and environmental protection halved. This isn't a hardcoded scarf-only thing, they simply transform into loose scarves.

**Comment by illi-kun** [comment]
I don't really think we need to allow such mess up with clothing. Allowing this, we will receive further requests like "mittens as socks", "balaclava as gloves", "pants as muff",  "pants as socks" (just drop it till the ankles!) and so on.

**Comment by FireCrow1973** [comment]
yes, we should all be careful and not get too trigger happy. 
but, you can say that about absolutely everything in this game.
i feel this is a good idea because its so easy to do, it requires no thread, no needle and no skill.
making or finding gloves that fits you should be difficult, but everyone has socks, and they all fits your hands.
some socks only goes a little bit over your wrists, and others go all the way up to the elbow.
keeping your extremities warm is super important.

**Comment by kevingranade** [comment]
I can see a slippery slope here where bizarre combinations are requested,
but at the very least if your hands are freezing and you have socks but no
gloves, putting socks on your hands is totally reasonable.

As for making it reasonable to use, instead of manually transforming
'socks' into 'sock mittens', it might be better to add a command to 'wear
on alternate body part'.  Then on the sock item you'd add a field like
"alternate-body-part": {"target":"hands", "item": "sock-mittens"} that
would automatically 'transform' the item when it's worn on an alternate
body part.
The command could be standalone, or worked into the 'W'ear menu.

**Comment by stk2008** [comment]
I agree with the comment about when do we stop allowing clothes for different things but as you stated Kevin.

Wearing socks as mittens is a pretty obvius optoin.

Its not like I am asking say

Wear trousers as hat or some thing.

Socks as mittens is a pretty obvius use for them :).

**Comment by FireCrow1973** [comment]
i think, a extension of the 'W'ear menu would be easiest to us and discover for now users.

**Comment by Zireael07** [comment]
+1 to wear on alt body part idea.

**Comment by Shoes01** [comment]
I wonder if there would be a more general solution instead of the "alternative body part" code injection. As a white list or a black list, I can see it being a bit tedious to add to most clothing. Perhaps a hard coded general case "torso > arms = legs > feet = hands = head", where items can be worn down the line but not up, with some code to allow exceptions to that rule (in the case of weird socks that can be worn on the arms or something).

But I think this is definitely the way to approach wearing socks on your hands.

**Comment by Coolthulhu** [comment]
I don't see the problem with a whitelist.
It's not like a lot of the stuff can be worn on alternative body parts. It's basically just socks.

For example, there's no way you'd wear boots on your hands in the DDA sense of wearing. You could wield them (and there could be bonus warmth from that), but then you couldn't wield anything else.

Pants on head would also require special casing to change all of its stats, because it certainly wouldn't have 90% coverage used that way. And worn on mouth it wouldn't have 0 encumbrance.

The general case would probably require far more work than a whitelist, both source and json work.

**Comment by Shoes01** [comment]
It's true most cases would be ludicrous to consider. I would expect a huge encumbrance penalty for wearing anything alternatively, except hands and feet (and head/mouth?), and legs and arms. Maybe the coverage% could also decide the encumbrance; trousers on head would be less encumbering than pantaloons on head because the coverage% would be less.

**Comment by Ram-Z** [comment]
With a whitelist you could also easily change the encumbrance `"alternate-body-part": {"target":"hands", "item": "sock-mittens", "encumbrance": "1"}`

But if I can wear my socks on my hands, I'd expect to also be able to cut them with a pair of scissors (cutting level 1) and transform them into wrist warmers with 0/1 encumbrance as @FireCrow1973 mentioned.

**Comment by kevingranade** [comment]
It really needs to be separate item definitions, with that implementation
all we need code wise is something to trigger the transformation, otherwise
we'd need an ever-expanding set of overrides to the item definition based
on what needs to be different about the item based on body part.

**Comment by stk2008** [comment]
Thank you to all who implemented this :)
