### ISSUE TITLE
Monster upgrading might not be entirely balanced

### ISSUE THREAD

**Issue by John-Candlebury** [CleverRaven/Cataclysm-DDA#12313]
Just reached late autumn with my current character, and it seems that there is at least one hulk or zombie predator in every single town block I visit. I have enough ammo to kill them, but their presence pretty much throws the risk/reward ratio of cities to the trash. Theres little point in attempting to loot cities for food or ammo if you have to continuously chew through 10 shotgun slugs every turn of the corner.

Also, there seem to be considerably less  zombies around, due to the  stronger zombies spawning more commonly I would guess. Which actually makes the game easier if you are a ranged character, as you don't get surrounded as easily.
##

**Comment by graysage1** [comment]
It may be better if the distribution of Zed types were not uniform, I think.  That way you could still meet dangerous Zeds early on, but you'd also know that most towns wouldn't have such Zeds, because they'd only appear in somewhat rare towns.

This can be done in addition to timing the Zed upgrades.  It doesn't have to be one method or the other.  It's possible to start a game where every town will be relatively low risk during the first say 50 days (season and year length can vary for different worlds), and then *some* towns will upgrade up one path, other towns will upgrade up a different upgrade path, and some towns won't upgrade at all.  

Of course it's not zero or one.  There is a continuum of danger.  One hulk in every town is probably OK too.  This gives the newbs something to fear and run from.  5 or more is probably annoying if every town is like that.

>Which actually makes the game easier if you are a ranged character, as you don't get surrounded as easily.

With the addition of stamina and running getting surrounded should be next to impossible, unless you're asleep at the wheel.  The only exception I can currently think of is the predator Zed.

**Comment by kevingranade** [comment]
I don't have any bright ideas for the hulk problem at the moment, something
that makes upgrade paths clump a bit, so you end up with different flavors
of upgrades in different areas sounds promising.
The plan once zombies are consistently upgrading is to remove everything
but base types at game start, and crank the default zombie density up.

**Comment by i2amroy** [comment]
I'm actually laying out some groundwork documentation on my end (now that finals are over) for some possible zombie upgrade "categories", but (like the master/necro PR) it's on a bit of a hold for the next little bit. My normal laptop's wireless card has apparently decided it's time to start giving up the ghost, so it'll be in for repairs for the next week or so most likely. Once that's out it's on the top of my current list of things to do though.

**Comment by SarahJohnson489** [comment]
It's totally fine as is. You'll spot it during your daytime scouting then skitter away. After that you have all the time in the world to get your pit circuit, burn patches, and molotovs together along with a bow or repeating crossbow. You'll put it down like the punk ass bitch it is. The game isn't blowing your risk/reward ration, you are with your poor choices.

**Comment by John-Candlebury** [comment]
Point is that it might be a little overdone because in most cases you won't get anything worth or resembling the in game resources or (IRL) time you spent. You can conceive  all sort of elaborate and probably simpler plans to clear the place street by street, but in the end it simply isn't practical to bother fighting the stuff at all, you are much better ignoring the whole thing and looting the few valuable gun stores or other stuff at night, so you stock resources for the times when you actually want to mess around.

Sure, you'll end up making the traps and other things because you'll otherwise get no further enjoyment out of the game, but having to do it or every single town or big structure you visit starts becoming more tedious than fun after a few times. 

For reference, the issue was opened after I met  nothing less than three hulks, four predators, and several necros; the moment  I set foot in an far of the city center suburb, in all honesty the RNG is not that evil most of the time, it usually prefers to place some2-4 predators and an occasional hulk every city block.

Im all for increased difficulty and more engaging late game, a blanket of may instant kill you in melee monsters does make the game considerably more dangerous, but I don't really find it a particularly engaging solution.

Would be much better to make the basic zombies more capable in group combat  and give them a better group intelligence  overtime. As in my opinion the late game is considerably better if you simply disable the scaling option, bump the number of zombies to x4 or similar and eschew the "makes you invulnerable to normal zombies" armors.

**Comment by SarahJohnson489** [comment]
Well I will admit the trench warfare from the cataclysm days did dull the pain of it for me. If you're bothered by it you can save a huge amount of time with a few cargo carriers of bear traps, spike boards shotgun traps, and crossbow traps. A foldable bike will let you truck in large amounts from your ride to the staging area on the outskits and you can alternate offset shallow pits, trap, empty space with a renewable ranged weapon like a reflex recurve or of the crossbow line to clear much faster than going full spike pit circuits. It's all pretty easy to make if you explored a bit in spring to get a ride then have your welding or forging gear by autumn so you can lay in a buckwheat farm regardless of your map rng helping o hurting your accumulation of permafood.

As much as people like to knock thorough looting you'll often get a couple nice things every few blocks with good basement or rare layout spawns providing exceptional things you sorely want.

I get what you're saying but I feel that it's a better move than trivial smart hordes of mid-ranged zombies speckled with a few highs. Either have affordable easy solutions to break them in half regardless.

**Comment by Coolthulhu** [comment]
I think the solution is more about player than the zombies. Flattening the dexterity curve and nerfing the best armors so that they're more in line with the rest.

You can easily stab a hulk to death with a pointy stick at respectable dexterity, but with low (10) or very low (8) dexterity, you may have problems hitting dogs. 4 dexterity is intentional challenge, unlike 4 perception or 4 intelligence.

**Comment by graysage1** [comment]
>Point is that it might be a little overdone because in most cases you won't get anything worth or resembling the in game resources or (IRL) time you spent. 

OK, but the fun of the game isn't 100% solely in how much stuff you can loot off some place.  Just the encounters, the dangers, the narrow escapes, the strange lab journals and weird portals (which I think we should be able to explore and learn about), all that adds fun and flavor to the game.  Loot *is* fun, yes, but if you measure your level of fun only by how big your pile of loot is when done, that, imo, is not a good way to think and to have fun in the game.

**Comment by Cat09** [comment]
longer monster upgrade chains could help out a little, making a slower progression. perhaps flagging some monsters to upgrade and some to simply not upgrade for a spread of types
variable stats within monster types, could up the !FUN! factor a little :)
a few changes to player mechanics could help make the game more challenging w/o hulks everywhere such as dynamic encumberance with volume and weight, speed and stamina loss scaling by encumberance and weight, tweaks like that could make a lot of situational difference.

**Comment by jokermatt999** [comment]
I'm with John Candlebury on this one. The predators and hulks and corrosive zombies are more damaging, but we need a bit more variety when running into multiple hulks/necros is routine. I think making the master/necros rare and powerful is a very good step in the right direction.

There's been a lot of good suggestions for upgrade on the Drawing Board topic, but most of them would require some additional coding. I'd say we either need to have basics upgrading into an actual threat (even if just via stats and not special attacks) or an armor nerf.

Has anyone discussed tentative numbers on armor? I don't really know the melee code enough to know what needs to be tweaked.

**Comment by Coolthulhu** [comment]
The biggest problem with armor is that monsters generally have no way of piercing it or going around it.
It could be solved by making zombies use more armor-independent abilities that could only be dodged, giving zeds passive armor piercing or nerfing all high-coverage armor either by dropping its coverage, dropping its armor or removing environmental protection.

Armor pieces like the survivor gear are total no-brainers with 100% coverage, incredible resistances and gargantuan environmental protection.
Cotton armor is a bit too light, but it got hit quite hard with the layering changes. Leather armor is fine - it has moderately-high armor values, but also high encumbrance and low coverage. Metal armor is like leather but (funnily enough) weaker than it where it matters.

**Comment by Cat09** [comment]
some slightly more realistic chemistry against armor materials, and more common chemical damage sources might help some (zombie goo being slightly corrosive?)
organ damage by rapid accel/decel and twisting of limbs causing damage could also help with armor protection being too high. I kind of disagree w/ environmental being reduced on the high teir stuff w/100% coverage, the coverage and materials it is made of are why it works that way... although env. protect eventually needs to define type I think. spores =/= fire =/= acid, etc.
knocking down could stand to be more common too, swarms would be a lot scarier if they could overwhelm and push you to the ground. stability like when aiming ranged seems applicable to close quarters.

**Comment by Coolthulhu** [comment]
Coverage for damage and for "environment" are different things. IRL a plate armor is amazing against kinetic force (could easily stop light firearms), but would do nothing against corrosive gas.

No armor should be a master of all trades. Survivor armors currently are.

**Comment by Rivet-the-Zombie** [comment]
>No armor should be a master of all trades. Survivor armors currently are.

This is intentional. If you can gather all the required materials and skills to produce the stuff, you deserve the reward.

It's all been nerfed way down, armor value-wise, repeatedly; its function now is to provide variably-decent armor combined with good storage capacity and that all-important environmental protection.

**Comment by Coolthulhu** [comment]
It doesn't really make sense that a random dude with a welder could make an armor way better than anything produced in a high-tech factory. (This gets far worse when we add tailor's kit to the equation, but that's a separate issue)

And from a gameplay perspective it is even worse, because it trivializes everything weaker than a hulk that doesn't have an acid/lightning attack. (Same here with tailor)

And on top of that, it is rather cheap to produce from semi-common ingredients. The only challenge is grinding up the skill.

Finally, it is yet another giant nail stuck in the coffin of "scavenging rather than manufacturing" theme when it comes to armors. With the exception of scavenging survivor armor from survivor zeds.

**Comment by kevingranade** [comment]
I think it would help with the armor discussion to be more concrete about
it, such as 'monsters with strength x should be able to deal light damage
through armor with rarity y and full coverage', something similar to what
we tried to do with melee weapons (not sure how successful that was, I
think it helped).  Or a different take on it, 'tier 1 armor shouldn't be
immune to damage from regular zombies, tier 2 armor shouldn't provide
immunity to feral hunters, etc...'

**Comment by Rivet-the-Zombie** [comment]
Very good points, @kevingranade. Armor should be able to completely block damage from certain attacks; that's the entire point of wearing armor.

Producing armor that can prevent damage from the flailing, uncoordinated blows and bites of most mundane zombies isn't really that big of a task; the majority are still no stronger than a normal human.

**Comment by Cat09** [comment]
this is veering a bit off topic... but I thought coverage was simply a measure of what % of given body part gear actually affected, and all stats were representative of applying to that %. if a body part is hit by something then roll vs coverage % of gear in layer order to see what it hits regardless of acid or zombie bite, just check acid resist for acid, cut for cut, etc.
So I guess this topic is kind of veered to: How to make the game challenging without throwing too many high teir zombies at once
But on topic: should monster scaling be toned down a bit (hulks are irritating to encounter a lot) before other difficulty changes are made?

**Comment by Coolthulhu** [comment]
> But on topic: should monster scaling be toned down a bit (hulks are irritating to encounter a lot) before other difficulty changes are made?

As zombie evolution gets padded with more types, hulks will become less common. The reason for hulk hordes is that zombies keep evolving until they become a form that can no longer evolve. Tough zeds have to become brutes which have to become hulks.

**Comment by kevingranade** [comment]
In particular, we want some set of top-end zombies that are interesting to
play against once the upgrading has run its course.
This can be with a large number of 'final form' zombies and/or with a flag
at each level that gives the zombie a chance of stalling permanently
instead of upgrading, we should in principle be able to tune the frequency
of appearance of each monster type by controlling decay rates like this,
e.g. by reinstating the 0.0001 appearance rate of hulks, though I would
argue that number should be higher since it is not reached at the start of
the game.

**Comment by drbig** [comment]
So there *is* an issue about this!

So today's early discussion with @tivec made me look deeper into the code.

First of all, the real player-facing issue is: seeing a plain old Zombie is now *very rare*. If you start anytime later than spring it's even *more rare*.

Now the `update_check()` needs love regardless, but my findings are that:

 - The `MONSTER_UPGRADE_FACTOR` being 0.0 - 100.0 is completely useless. With highest `upgrade_min` at 14 it's enough to set it to 15 to have *every upgradable monster* upgrade on first load. The remaining 85 range is useless. And the factor as it is now doesn't mean "will upgrade X times faster/slower" at all.
 - First upgrade chances are between 67% - 95%, skewed toward ~ 80%. Almost every monster will upgrade on first load.
 - The current `upgrade_min` approach means that after the initial period monsters will try to upgrade on every load - once per day. So there will be cases where the player basically triggers the updates all the time.
 - There is code for both 'half-life' based upgrades and 'basic' upgrades; the latter code will never run, as there are no monsters with just `base_upgrade_chance` set

It seems to me that the rarity of plain zombies is due to both monster upgrades and monster spawn factors (but that needs proper testing).

And back to monster upgrades, I think we need:
 - Better `MONSTER_UPGRADE_FACTOR` scaling, perhaps taking into the account season length and/or starting season
 - I'd propose for monsters to have a chance of update only in intervals, e.g. instead of "always past `upgrade_min`" have "every `upgrade_min` period"; adding the above scaling to that should make the upgrades much smoother overall
 - Have an option for a monster to "throw" never_upgrade; so on each check the options are "upgrade/no upgrade/never upgrade"

I think I'm going to PR a simple, basic fix for at least the upgrade factor, as all of the above are a matter of consensus.

**Comment by kevingranade** [comment]
I'm not a fan of having things tied to season length, it should only mean
'how long is a season', nothing else.  If you change season length and want
monster upgrade rate to match, you should just change upgrade rate too.
If updates are triggering every tick past some threshold, that's a bug.
Monsters should definitely have a chance to 'dead end' at their current
state.

**Comment by Vzor-** [comment]
I believe this punishes slower play styles too much (ie. a farmer's start). You may slowly make a home for yourself chopping trees and sewing seeds only to find that when you finally feel like it is time to loot towns, you immediately die to corrosive zombies and hulks. Something similar happened to me. Even now with another char I don't want to do more interesting projects because I am afraid of falling behind the curve.

I feel the problem is more fundamental than finding the right shape for the monster upgrade curve. The ramp should be based on something more organic and player tailored, like the amount of zombies killed in a specific town.

On a side note I also agree that even at late game you should see every type of zombie, not just final form ones.

**Comment by Coolthulhu** [comment]
> The ramp should be based on something more organic and player tailored, like the amount of zombies killed in a specific town.

Limiting it to per-city would defeat the purpose of it being in game: trying to keep up the difficulty with player's growth.
Tying it to player's kills would lead to scumming zeds so that someone else deals the last hit.
Tying it to zombie deaths would make it jarring when after a big fight zombies become noticeably stronger and could easily lead to optimizing combat training to keep kills low compared to skill levels gained.

Tying it to combat skills would make picking them at spawn counter-productive, instead leading to optimizing weapon selection.

Good player centric scaling would need some complex formula and would make the game "IVAN-like". Things like scaling it with player's armor, strongest weapon carried etc. Oh and it would need to take player's stashes into account too.

For now just pure time scaling sounds better than anything I can think of.

**Comment by kevingranade** [comment]
I'm fundamentally opposed to player-centric scaling. As Coolthulu points
out, it becomes a mechanic to manage instead of something to overcome,
which isn't the intent of having scaling.
On a more thematic level, the game world doesn't care about you, you aren't
the chosen one, you're just someone who's trying to survive.

We might add scaling mechanisms that trigger on large-scale changes caused
by the player, for example wiping out one monster faction in an area might
cause the remaining factions to expand and/or strengthen. Pulling survivors
together to form a large settlement might attract attention from enemies.
These would not replace monster evolution though, it's here to stay.

As for your specific use case, it seems a bit odd to say you want to play
the game a certain way, and it isn't working so the game should change.  If
your approach isn't working, either figure out how to make it work or do
something else.  If you want to adjust the difficulty, go ahead, there are
a number of options to adjust difficulty and monster evolution.

**Comment by Vzor-** [comment]
>Limiting it to per-city would defeat the purpose of it being in game: trying to keep up the difficulty with player's growth.

I am not for keeping it on just per city, I would say a hybrid would work best; Perhaps even one that includes time based scaling.
>Tying it to player's kills would lead to scumming zeds so that someone else deals the last hit.

I have not played with npc's. If npc's can be "followers", track it, otherwise that would be very hard to orchestrate on a scale that matters.

>Tying it to zombie deaths would make it jarring when after a big fight zombies become noticeably stronger and could easily lead to optimizing combat training to keep kills low compared to skill levels gained.

One could say after a big fight like that the player is ready for more of a challenge. If the player avoids kills and uses stealth that is his decision, once the player starts killing things then the game will adapt and become hard. 
 

>I'm fundamentally opposed to player-centric scaling. As Coolthulu points
out, it becomes a mechanic to manage instead of something to overcome,
which isn't the intent of having scaling.
On a more thematic level, the game world doesn't care about you, you aren't
the chosen one, you're just someone who's trying to survive.

I would argue that scaling is more a restrictive force than anything if it is time based. It means if you are not making and finding better weapons and armor, you will fall behind the curve and lose.

>We might add scaling mechanisms that trigger on large-scale changes caused
by the player, for example wiping out one monster faction in an area might
cause the remaining factions to expand and/or strengthen. Pulling survivors
together to form a large settlement might attract attention from enemies.
These would not replace monster evolution though, it's here to stay.

My point here is to point out a problem with the philosophy, not to suggest a fix, the one I proposed was purposely simple and not a serious suggestion. Monster evolution railroads the player to being a combat oriented player and to progress at a rate that does not allow him to undertake projects or focus on non combat skills.

>As for your specific use case, it seems a bit odd to say you want to play
the game a certain way, and it isn't working so the game should change.  If
your approach isn't working, either figure out how to make it work or do
something else.  If you want to adjust the difficulty, go ahead, there are
a number of options to adjust difficulty and monster evolution.

I would like to say that this is not how I want to or intend to play the game, but that it is a way that could previously lead to a very fun experience that now only leads to frustration. Farming, building and tool creation are (largely) only useful early game. As it stands farmer (and blacksmith) is still a starting condition, and it now stands to be nothing more than a way to trick a new player into spending a lot of time building a coffin.

I Apologize for the long reply and although I may come off as passionate about this, I am very much happy with dda and the direction it has been taking.

**Comment by Coolthulhu** [comment]
> One could say after a big fight like that the player is ready for more of a challenge.

Or more likely desperately trying to find a first aid kit to patch an infected wound (while having constant 30 pain).

With the way focus works, a big battle doesn't grant much more combat experience than a short one.

**Comment by kevingranade** [comment]
> I would argue that scaling is more a restrictive force than anything if
it is time based. It means if you are not making and finding better weapons
and armor, you will fall behind the curve and lose.

It is, and it is intended to be.  You either need your firepower to keep up
with the power curve, or have superior tactics.

> My point here is to point out a problem with the philosophy, not to
suggest a fix, the one I proposed was purposely simple and not a serious
suggestion. Monster evolution railroads the player to being a combat
oriented player and to progress at a rate that does not allow him to
undertake projects or focus on non combat skills.

This seems to be the core distinction.  Cataclysm is a survival game, not a
building game.  If you're building things that don't help you survive,
you're probably going to get yourself killed, that's intended.  If you want
to turn it into a builder game, adjust the difficulty options to give
yourself breathing room.

> Farming, building and tool creation are (largely) only useful early game.
As it stands farmer (and blacksmith) is still a starting condition, and it
now stands to be nothing more than a way to trick a new player into
spending a lot of time building a coffin.

Nobody said the professions are optimal, you're intended to figure out
whether a profession is going to work for you yourself.

**Comment by Night-Pryanik** [comment]
Closing as per lack of discussion.
