### ISSUE TITLE
Underground monster infighting has effects on the surface.

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#12362]
Make a world with the z-level option on and visit a lab, you'll almost certainly see shell casings appear out of nowhere and receive messages about monsters fighting underground.

**Comment by kevingranade** [comment]
As noted in the PR, looks like player::sees(monster) or something it calls isn't handling inter-level interactions right, so if you can see the square above a monster its special attack is displayed.

**Comment by Midaychi** [comment]
As a possibly useless and frivolous addendum, I've noticed that blobs can split vertically now in addition to horizontally.

 Maybe this is intentional, but one character I made walked past like 2 blobs and broke into a house nearby, and during the rather short period of looting I noticed footstep icons appearing around in plain sight with no noticeable origin.

 I ignored it, until it increased to the point where I thought I was in a dancing instruction diagram, and found to my dismay that blobs had started to descend through the roof like rain.

**Comment by Kadian** [comment]
There was, at least in one of the older experimental builds (from the..~15th I think?) also the issue that not only Casings appear out of nowhere, but corpses and their loot as well. This is especially troubling if you happen to sleep near a lab, because all the 'dead' zombies will just stand up again after a while and the player will be surrounded by undead Scientists (and, as Midaychi said, the occasional blob).

**Comment by Zireael07** [comment]
@Kadian: update, this bug is since fixed.

**Comment by Coolthulhu** [comment]
Monster deaths occur where they should now.
Pretty sure turrets should now attack only the targets on their own z-level and blood sprays should occur on the same level.
Most monster abilities are now restricted to their own z-level because sight doesn't work on different z-levels yet.

Now, NPCs are still mostly 2D. I'm working on an update for those.

**Comment by Midaychi** [comment]
"the occasional blob"
https://dl.dropbox.com/s/qgnhcv1i1qhuzgi/soundfrombelow.png
Here's standing outside of a mansion (to the north east slightly out of minimap range). I investigated this on day one and there was only one blob and no underground noises.
