### ISSUE TITLE
Rezed zeds can upgrade instantly

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#12439]
`add_zombie` checks zed for update unconditionally.

Most of the time it's not too dangerous, but occasionally results in a regular zed raising as a brute (or even a hulk), which can be a nasty surprise.
##

**Comment by BevapDin** [comment]
"Funny" is it when you move one step south, triggering a map shift (which unloads a monster), and immediately move back north. The monster gets loaded again and updates itself.

Or even more fun: save a game being surrounded by some normal zombies. Reload it and suddenly there are some special zombies in place of the normal ones. Do this repeatedly (without consuming a single turn) and all of them will have updated.

**Comment by i2amroy** [comment]
>Or even more fun: save a game being surrounded by some normal zombies. Reload it and suddenly there are some special zombies in place of the normal ones. Do this repeatedly (without consuming a single turn) and all of them will have updated.

The update check includes a check if there was already a roll on the current day, and if so, returns without actually rolling for an upgrade. If this is happening it's a bug that somebody brought back.

To be a bit more clear, calling the update zed function checks to see if the zed needs to update, and if so updates it, but it's perfectly possible for a zed to not need to update after the function has been called (and thus not update). It makes all of the update checks be self-contained inside the update function in one spot in-case we ever need to call the update check elsewhere (like in the master zombie special code).

**Comment by ipcyborg** [comment]
>The update check includes a check if there was already a roll on the current day

Can't find this specific check.
On revive there is a new creature monster from the corpse type. It has `upgrade_time = -1`, so when `on_load` is called, it can be upgraded immediately.  
Btw, strange thing is that `on_load` is not called right after reviving a monster. Is that correct?

I think this issue could be fixed by inheriting `upgrade_time` from the corpse (if possible). 

Or just re-roll it right after the revive, which seems logical: it was dead not so long ago, so it must have been damaged. The upgrade process must be restarted, right?

**Comment by kevingranade** [comment]
I agree inheriting upgrade_time via the corpse is the way to go here, nothing should be leaving it at -1 except mapgen.
