### ISSUE TITLE
Idea: Quality value representing item's overall condition

### ISSUE THREAD

**Issue by macrosblackd** [CleverRaven/Cataclysm-DDA#12437]
There has been talk lately of item's having some sort of 'quality' value. My understanding is this would allow a single item to have a larger fluctuation in attributes - without needing to create definitions of said items in JSON.

(Quality will be referred to as QL from this point)

Brainstorming:
- Crafted items would have a QL that is derived from some combination of skill roll, tool and material QL.
- Exceptional items could have QL > 100%
- Repairing an item will permanently reduce QL by some amount based on skill roll
- Items in the world could have QL reduced over time from being exposed to the elements
- Items with spoil timers could represent spoilage over time via QL reduction
##

**Comment by DavidKeaton** [comment]
I like this idea, however, is this different than the item's health?

**Comment by macrosblackd** [comment]
The item's health represents its current physical condition. Quality would represent, I can't really think of a better word but, overall craftsmanship or something along those lines.

**Comment by DavidKeaton** [comment]
ah gotcha gotcha.

**Comment by macrosblackd** [comment]
Some ideas on how QL would affect items would be:
* Reducing protection from armor/clothing
* Reducing damage from weapons
* Reducing light strength from stuff like flashlights
* Increasing fuel/ammo consumption (ammo like batteries, not necessarily guns)

**Comment by Coolthulhu** [comment]
Some quality rating to make factory-made items better than player crafted ones could be useful, but having to constantly change clothing due to damage would be even more annoying than current item damage from scratches.

QL doesn't make sense for items that can be easily recrafted, unless the factory-made items were guaranteed to have higher QL than the player could make.
For example, capping player and zombie drop QL at 100%, but allowing clothing stores to spawn 200% quality items.

**Comment by macrosblackd** [comment]
QL reduction from repairing doesn't have to be large, nor would
reducing QL to 0.1% render the item useless. My thoughts on how QL
affects things like armor and weapon damage would be to make QL adjust
50% of the attribute.

**Comment by macrosblackd** [comment]
Anyone have any more comments regarding this? Is it an idea worth developing further?

**Comment by Zireael07** [comment]
I like it a lot, as a matter of fact have something similar sitting in my notes for my own RL :)

**Comment by DavidKeaton** [comment]
I like it.

**Comment by kevingranade** [comment]
I can't opine with the level of vagueness this has, it could be great, it
could be terrible, there's no detail.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
