### ISSUE TITLE
AIM doesn't move the 'D'ragged vehicle pane to the opposite side when 'd' is used twice

### ISSUE THREAD

**Issue by graysage1** [CleverRaven/Cataclysm-DDA#12433]
Looks like AIM generally respects the convention of moving the pane to the opposite side when the same selection is used twice except when that selection is 'd' for 'D'ragged vehicle, in which case AIM seems to do nothing once 'd' is selected in any pane (even if it's selected in the opposite pane) and you hit 'd' again.  Expected behavior: once 'D' is selected, hitting 'd' again should flip the panes around, similar to how other selectors behave (1,2,...9).
##

**Comment by DavidKeaton** [comment]
noted :-)

**Comment by DavidKeaton** [comment]
this can be closed :-)

**Comment by graysage1** [comment]
While the issue as described appears to be fixed in the latest build, a very similar issue is still present.  Namely, if I have a vehicle in 2, and I select 2, from then on I can't use 2 to flip the panes.  This is regardless whether or not I press v to select the vehicle that's in 2.

**Comment by DavidKeaton** [comment]
interesting. I'll add that to the fixes i have open currently.

**Comment by Oskar636** [comment]
The issue is a bit stranger than @graysage1 described, it works as follows ( and only on tiles with volume ):
You select a vehicle with 2, then on a diffrent panel you select 2. One panel gives you the insides 
( a box for example ) the other gives you the floor, it works good. But then you can't flip panels which you should be able to.

Another issue is if you select a normal tile with ( for example ) 5 and a vehicle tile with volume with
 ( for example ) 2 you can only flip using the 5, which is the empty tile.
Flipping works normally on vehicle tiles with no volume. 

Build 5864 windows 64bit tiles

**Comment by wapcaplet** [comment]
Still reproducible in 0.E-9603-g42468f6cab
