### ISSUE TITLE
Resting

### ISSUE THREAD

**Issue by CIB** [CleverRaven/Cataclysm-DDA#12455]
So one thing that seems weird to me is that there is only sleeping and waiting. If you have a warm bed and want to pass the night by, you could repeatedly try to sleep. But apparently this decreases tiredness so that it'll prevent you from entering the kind of sleep that heals you. Or you could wait, but this will not make use of the bed (you'll get frostnip and all).

My suggestion: Merge sleep and wait into "rest". When starting to rest, you can specify two things: How long do you want to rest, and do you intend to try to keep awake?

Either way, you'd make use of any source of warmth on the ground like when sleeping. Depending on level of tiredness, you might fall asleep with either choice, though sleep would be much shorter and lighter if you intend to keep awake. The system could later be extended to allow for automatic consumption of drink/food and morale boosting stuff (if desired by the player).
##

**Comment by Zireael07** [comment]
Good idea.

**Comment by DavidKeaton** [comment]
+5

**Comment by FireCrow1973** [comment]
This would be, a fantastic feature to have.
especially the part about, sleeping when you can.
And eating, drinking, reading books and all the other stuff.
its would be, nice not having to micro manage things from time to time.

**Comment by DavidKeaton** [comment]
as in to queue up things for when you rest?

**Comment by BevapDin** [comment]
That an interesting idea. It could include reading and be a solution for #1197. Depending on the book, it could increase or decrease the chance to fall asleep. Very tired characters can still move around and do manual work, but would probably fall asleep over reading a(n uninteresting) book.

One caveat: waiting can be canceled, sleeping (and lying down) obviously not. If you try to sleep, you close your eyes and wont see approaching monsters. If you try to stay awake, you have your eyes open (seeing monsters and allowing you to cancel the waiting to react) until you actually fall asleep. That would need some specific handling.

There might be other longer actions that can be handled that way, maybe even some crafting (when you don't need to walk around, e.g. soldering small electronic, sewing), ACT_VIBE, ACT_START_FIRE (?). Through they would probably not allow falling asleep at all.

**Comment by DavidKeaton** [comment]
ACT_VIBE may actually do with a bonus to staying awake! ;-)

**Comment by Cat09** [comment]
somewhere it has been commented that making use of piles of clothing should probably be automatic with simply being on a tile with them while cold, given more than 1 turn there.

**Comment by Snaaty** [comment]
I am not sure about automatic warmth from clothing on the floor, as you in fact might be busy assemblying the latest CBMs or firing your crossbow, which is kinda exclusive with using clothes on the floor for warmth. 
Not sure as well how much of a gain queuing stuff would pose.

**Comment by Barhandar** [comment]
>I am not sure about automatic warmth from clothing on the floor, as you in fact might be busy assemblying the latest CBMs or firing your crossbow, which is kinda exclusive with using clothes on the floor for warmth. 

Doesn't exclude wrapping up your legs in clothes or putting them on your shoulders.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
