### ISSUE TITLE
Add extended_firestarter to lighters and matchbooks

### ISSUE THREAD

**Issue by tyrael93** [CleverRaven/Cataclysm-DDA#12467]
Let's face it, lighters/matchbooks can light up trees, walls, two by fours and shrubs in less than a turn. That does not make any sense now that we have a extended_firestarter function, which works remarkably well and scales with survival.
I edited my .json tool file so that lighters and matches behave the same way a fire drill works, because

A)balance issues: you can drop a skewer or anything flammable under any zombie and then light it on fire. This takes a single turn and kills everything fairly easily (except brutes and hulks that send you flying away). This fixes it.
B)More realism: I get that we're in the future, but 2050's lighters aren't going to be  quantum flamethrowers that create small fires on walls if you just use a single charge in less than a second. This also makes lighters more useful right now since you end up disassembling most of them for pilot lights without even using them, given that they only use one charge and they're extremely common. 
C) Lighting up cigarettes/klins etc only takes one charge and the same time it'd take if the lighter didn't have the "extended_firestarter" function so there are no tedious and silly messages like "at your skill level it will take 60 minutes to light a cigarette."

I'd do the pull myself but I have no idea how to do this. 
At Survival 0 it takes 60 minutes to light up a fire (which makes sense since someone that has never lit a fire in his life wouldn't know where to begin and waste a lot of time and charges trying to do it), while at survival 1 it takes 29 minutes, survival 2 13 minute, survival 3 8 minutes and so forth, same as a regular fire drill.

If anyone wants to discuss or merge this, feel free. I've opened this issue just for that.
##

**Comment by Zireael07** [comment]
60 minutes to use a lighter is fairly ridiculous imho. Any person can use a lighter in 5-10 mins max with no survival experience.
I have two ideas, both requiring a small_firestarter function or flag:
a) change the scaling to go from 10 mins at survival 0 to 8 mins at 1, 6 at 2 etc.
b) allow lighting only skewers/sticks/plants and the like and not walls or 2x4s.

**Comment by DavidKeaton** [comment]
what a lighter should do is produce a flame slower the larger the volume. not to mention a lighter taking _10 minutes_? it doesn't take long to light an object ablaze with one, but it does take some time, perhaps a few or so.

**Comment by Coolthulhu** [comment]
It would be relatively easy to add a quality setting to extended firestarter json.
Or maybe even two or three: base time, time deducted by skill level (or other scaling factor) and lower cap.

Current extended firestarter has a hard-coded time depending only on survival and (in case of lens) daylight.

This would lead to a new problem, though: the lack of ability to light up gasoline without spending a few minutes of time fiddling with it. This would probably require a test if the target tile has some items with fire resistance 0 - those burn really well (paper, gas/diesel, powder - not sure what else has 0 resistance).
Though then we could easily go back to where we started, as paper wrappers are paper... We could possibly sum the total volume/weight of 0 fire res items - that way starting fires instantly would require entire books rather than wrappers or skewers.

**Comment by tyrael93** [comment]
Honestly right now the glaring problem is the fact you can set things ablaze in less the a second, which also makes burning houses and luring zombies in very simple and effective. 
Never thought the most deadly weapon for a survivor would be his lighter.
Extended firestarter qualities seems like a quick fix that would work just fine, even though I've always wanted to actually have a working fire starting mechanic in which you needed to light skewers/paper/splintered wood for the fire to start instead of just lighting a bunch of two by fours. 
For gasoline and paper I have no idea how to work that out easily though.

**Comment by kevingranade** [comment]
Another solution to this I was working on a while ago but got sidetracked
from is adding a new 'tiny fire' set of fields to represent a fire that is
just being lit that have to consume fuel (and spend time) in order to reach
a size where it would be dangerous to something,  A very small fire might
sit smoldering for minutes before enlarging with particularly poor fuel,
likewise a single paper wrapper would ignite fast, but not provide enough
fuel to make the fire grow to the point where it is either dangerous or
useful.  So if you want a big fire fast, the only solution is to provide a
lot of fast-burning fuel.

**Comment by DavidKeaton** [comment]
Kevin's approach +10

**Comment by chaosvolt** [comment]
It's also possible to adjust how much time the normal firestarter action takes, like I did with the ember carrier in More Survival Tools.

Though I'd say the real issue here is that a "small fire" from a burning skewer is as nasty in turns of damage-over-time as a "small fire" from a burning bush.

If fires had to start as a minor fire or smouldering embers effect instead, that did less or no damage to stand in, that would also help solve the issue of burning zombies with single inches/centimeters/linii of thread or mere skewers.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
