### ISSUE TITLE
Encumbrance stacking penalty edge cases

### ISSUE THREAD

**Issue by ejseto** [CleverRaven/Cataclysm-DDA#12492]
Certain clothing combinations suffer encumbrance stacking penalties where it doesn't make sense, for example: shorts + knee-high boots, or panties + stockings. These items don't seem like they should have any overlap, so it doesn't make sense that they would incur a stacking penalty.

**Comment by kevingranade** [comment]
I agree it doesn't make sense, but it'll require extending the definition
of encumbrance quite a lot to handle it, so it has down sides.
Is this *breaking* something that should work, or is it just that it would
be nice for it to be consistent?

**Comment by ejseto** [comment]
Wouldn't call it "breaking" since you can just wear something else. Panties and stockings are both almost useless and knee-high boots suck regardless of the extra penalty. How much trouble would it be to add another body slot, diving legs into groin + leg or upper leg + lower leg? It probably wouldn't be worth the trouble just to fix these examples, but it might enable more diverse items.

**Comment by mugling** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
