### ISSUE TITLE
Crafting armor doesn't ask which ingredient to use

### ISSUE THREAD

**Issue by molkemon** [CleverRaven/Cataclysm-DDA#12517]
If you craft like a survivor belt, which can have drop leg pouches as ingredients, it will apparently default to the pouches you are wearing, even if you have spare pouches in your inventory or lying around nearby. Very annoying, especially if you had upgraded the pouches you'd equipped. 
##

**Comment by kevingranade** [comment]
I agree starting with the ones you're wearing isn't good, but I don't think
prompting for every item is the right answer.  We probably want to use
inventory then nearby items then wielded then worn last, and possibly a
confirmation for worn or wielded.  Not sure how easy this will be to do.

**Comment by DeNarr** [comment]
Personally, I would always prefer to use nearby items over items in my inventory. Though if this is a thing that people have different preferences on, perhaps it could be an option we could set. So hoarders like me can use stuff lying around first, while people who like to travel light might choose to always use inventory first.

**Comment by DavidKeaton** [comment]
I would agree using a worn/wielded with prompt would suffice.

**Comment by eliotcougar** [comment]
Personally, I would prefer prompting for every ingredient, even if there is only one ingredient to choose from...
1. It would give me the chance to cancel crafting if I see that the only ingredient for crafting is actually rotten or upgraded, or renamed, or worn...
2. When I'm doing a lot of repairs with a welder, until it has enough charges it would ask me if I want to use ducttape, but when the amount of charges drops too low it will use ducttape without asking... Even worse if you have oxytorch nearby, since repairing drains a lot of acetylene in one go... If you display the only item/tool to use, it gives you a chance to avoid this potentially unwanted waste of resources (you just recharge the welder with batteries and keep going)

**Comment by Leland** [comment]
Closing due to lack of discussion. Anyone interested in keeping this around for purposes of discussion of development, just ping me here and will reopen.

 Alternatively, (since this is an old issue) feel free to create a new issue linking here.
