### ISSUE TITLE
Refugee center merchant mission crash

### ISSUE THREAD

**Issue by ejseto** [CleverRaven/Cataclysm-DDA#12514]
The quest after investigating the caravan to "consult with the foreman" causes a crash upon accepting.

**Comment by jokermatt999** [comment]
Was there a message associated?

**Comment by ejseto** [comment]
Went back and compiled a debug build.

```
#0 00DD0D3D	std::string::assign(std::string const&) () (??:??)
#1 09F0EB40	?? () (??:??)
#2 009E674E	npc::load_npc_template(this=0x168a8e90, ident=...) (C:\Cata\src\npc.cpp:126)
#3 00872866	map::place_npc(this=0x9f0ebc4, x=16, y=15, type=...) (C:\Cata\src\mapgen.cpp:11476)
#4 0092BEF6	mission_start::start_commune(this=0x9f0ecef, miss=0x16865908) (C:\Cata\src\mission_start.cpp:625)
#5 00906797	mission::assign(this=0x16865908, u=...) (C:\Cata\src\mission.cpp:165)
#6 00A561E6	talk_function::assign_mission(p=0x134a8c00) (C:\Cata\src\npctalk.cpp:2999)
#7 00E61C07	std::_Function_handler<void (npc*), void (*)(npc*)>::_M_invoke(std::_Any_data const&, npc*)(__functor=..., __args#0=0x134a8c00) (C:/mingw-w64/i686-4.9.0-win32-sjlj-rt_v3-rev2/mingw32/i686-w64-mingw32/include/c++/functional:2039)
#8 00DAEC85	std::function<void (npc*)>::operator()(npc*) const(this=0x9f0eea4, __args#0=0x134a8c00) (C:/mingw-w64/i686-4.9.0-win32-sjlj-rt_v3-rev2/mingw32/i686-w64-mingw32/include/c++/functional:2432)
#9 00A5D2A0	talk_response::effect_t::apply(this=0x9f0ee7c, d=...) (C:\Cata\src\npctalk.cpp:3744)
#10 00A5DD6D	dialogue::opt(this=0x9f0f00c, topic=...) (C:\Cata\src\npctalk.cpp:3828)
#11 00A218FB	npc::talk_to_u(this=0x134a8c00) (C:\Cata\src\npctalk.cpp:637)
#12 005B4540	game::chat(this=0x12142420) (C:\Cata\src\game.cpp:11528)
#13 00560447	game::handle_action(this=0x12142420) (C:\Cata\src\game.cpp:2565)
#14 0055069C	game::do_turn(this=0x12142420) (C:\Cata\src\game.cpp:1203)
#15 0076D783	main(argc=0, argv=0x3b1894) (C:\Cata\src\main.cpp:441)
```

**Comment by mugling** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
