### ISSUE TITLE
Tazing from your shoe!

### ISSUE THREAD

**Issue by Soyweiser** [CleverRaven/Cataclysm-DDA#12554]
When you put a tazer in your shoe you can use it without getting it out using the % Item Action Menu. Uses only 100 time units.

Saved my ass, but still, seems off and a bug. It is pretty odd that you can put the tazer in a boot anyway.

**Comment by Sirbab** [comment]
I'm imagining it something like this lol: http://richardsalmanac.us/wp-content/uploads/krebsshoe.jpg

**Comment by Coolthulhu** [comment]
Tazer works from the backpack too, so I don't really see the problem here.
Until we get something like variable item use cost based on item's location, boot tazers will probably keep working. Unless someone decides to special case it, but I don't think it's worth the effort. Or to make tazers require to be wielded before use - that would actually make sense.

**Comment by DavidKeaton** [comment]
When I get back to my item update, you'd have to unpack to use it anywho.

**Comment by Soyweiser** [comment]
Was not aware you could use it from your inventory. That is quite useful

**Comment by DavidKeaton** [comment]
'a' key :-)
