### ISSUE TITLE
Additional uses for BURST_ONLY flag.

### ISSUE THREAD

**Issue by chaosvolt** [CleverRaven/Cataclysm-DDA#12593]
I recall quite some time go posting on a forum thread suggesting we add a feature like this for full-auto-only weapons, and now it's used for...a minigun. Derp.

I recall trying to discern which guns would warrant being burst-only, and posted it...hell if I can recall where, and which guns. All I remember is the M249 at least should be full-auto-only, and briefly remember suggesting the M2 Browning before remembering that it actually DOES have a fire selector switch.

In addition the new guns will need to account for this. The Sten if I recall is full-auto only, some models of Thompson might be selective-fire. The BAR is a special case, as the models varied in fire control options. Most models of it were full-auto-only, but the model most known for its use in World War II and the Korean War, the M1918A2, had a fire-rate reducer that gave it two options for full-auto fire.

EDIT: And if anyone finds that thread and page I posted a list of suggested full-auto guns in, link me. Forgetful dragon is forgetful. :V

**Comment by Coolthulhu** [comment]
I don't really like the idea of having to choose only between "single fire" and "full burst". Full burst is 6 seconds of holding the trigger.

Currently even the burst will stop if the creature is killed with the first shot, negating any rationale in forcing the burst on (except trigger-happy).

A better way to do this would be to force a minimum burst size (possibly scaled with marksmanship and/or the weapon skills), which would be respected even once there are no targets left. Say, 3 shots for a Sten, but 10 (or more) for a minigun.

The burst-only flag is currently only working with vehicle-mounted weapons. You can single fire that minigun just fine when on foot.
And a semi-minor bug: weapons with UPS cost will not complain about no UPS, just fire 0 shots. This still trains weapon skills.

**Comment by chaosvolt** [comment]
Hmm. That really sounds more like derpiness caused by the burst fire feature in general. I merely mean adding the newer BURST_ONLY flag to certain weapons.

**Comment by kevingranade** [comment]
I specifically added BURST_ONLY for the minigun, which you cannot fire if not mounted on a vehicle, and which has a firing rate of 2 - 6 *thousand* rounds per minute, putting it's 100 round burst at 1 - 3 seconds of firing, and even that only happens if you don't run out of targets.  It needs to be beefed up a bit code-wise before it can be applied to other weapons.  I only patched it in because I considered it a blocker for merging the minigun PR.
Before attaching it to other weapons I'd like to overhaul the burst firing infrastructure a bit to do what Coolthulu outlines, effectively giving each weapon a rate of fire instead of a "burst size", (although we might leave burst size as a weird upside-down definition of firing rate for a while), and probably having several sub-settings for burst, like "short burst" (as quick a trigger pull as you can manage, probably only a handful of rounds, or possibly as low as one with slow firing guns), "long burst" (half-second or so of firing), "full auto" (several seconds of firing), "two-round burst" and "three-round burst" (a gun-enforced burst, only available on some guns).  How some of these behave and even whether you can use them might be based on gun skills and attributes.
Side issue, "double-tap", "triple-tap", and "bump firing" are real techniques, some guns might support them at some level of skill.

Also see #5609

**Comment by chaosvolt** [comment]
Ah right. Makes sense that the minigun would be the most likely gun to get that trait, yes.

Still, so long as we have a way to officially distinguish between selective-fire and purely full-auto weapons, I'm happy.

Still, I recall suggesting a "no single shots for full-auto-only guns" thing ages ago so it's kinda weird to see it now exist for a different purppose. o3o

**Comment by Griffinhart** [comment]
>"double-tap", "triple-tap", and "bump firing" are real techniques

Mmm, [Mozambique](http://en.wikipedia.org/wiki/Mozambique_Drill).

**Comment by chaosvolt** [comment]
Though we could just add a double-tap or similar option to the aim-and-fire menu instead of as a burst. :V

**Comment by kevingranade** [comment]
That's pretty much what I meant, specific firing modes you can select, not
some kind of modified burst.  From the ui point of view at least, it seems
likely we'd model a double-tap as a 2 round burst in the code.

**Comment by chaosvolt** [comment]
Maybe, hmm.

Still, the fact you can reliably fire single shots with full-auto-only guns is somewhat derpy when we now have a way to curtail that. o3o

**Comment by mugling** [comment]
`BURST_ONLY` was deprecated and replaced with `modes`
