### ISSUE TITLE
The new light attenuation code removes the ability to craft in the dark with night vision

### ISSUE THREAD

**Issue by Makrond** [CleverRaven/Cataclysm-DDA#12640]
I don't know if this is intentional or just something missed in testing, but since the crafting/reading/sewing checks call player::fine_detail_vision_mod(), and the mutation modifiers in that method were removed, every character is effectively returning a value of 5.0, meaning it's impossible to craft in the dark even if you have debug vision.

**Comment by kevingranade** [comment]
Intentional, night vision in reality does not work like daytime vision and
in most cases people cannot read or do detail work in very low light
conditions.  Animals with more extensive night vision probably don't have
the acuity to do either in the first place, so mutating in that direction
wouldn't help either.

**Comment by Makrond** [comment]
Fair enough then.
