### ISSUE TITLE
Segmentation fault in Mint 17.1 KDE after compiling the tiles version

### ISSUE THREAD

**Issue by slyscorpion** [CleverRaven/Cataclysm-DDA#12650]
CDDA version: "0.C-3716-g5ff3af4"

System info (please let me know if there's anything else I need to provide): 

Linux Mint 17.1 KDE 3.13.0-37-generic 64-bit.

Pastebin of the terminal output whem I compiled the game using "sudo make TILES=1": 

http://pastebin.com/iawHXQ0Z

After running ./cataclysm-tiles I get

mint@root:/home/Cataclysm-DDA > ./cataclysm-tiles
Segmentation fault 

No other error messages appear. Also, when using "sudo make TILES=1 RELEASE=1" I get the same "segmentation fault" message in terminal.

Thanks for reading :)

**Comment by slyscorpion** [comment]
Using "sudo make TILES=1 NATIVE=linux64" also results in a segmentation fault when using ./cataclysm-tiles.

**Comment by slyscorpion** [comment]
OK, I figured out the problem with this. Apparently, after compiling the game you have to run it with

sudo ./cataclysm-tiles

and then the game will work as advertised.

Not sure why the game requires sudo but at least I can run the game after compiling it.

**Comment by DavidKeaton** [comment]
Proper rights.

**Comment by narc0tiq** [comment]
So, you compiled it under root's credentials (which isn't necessary, nor recommended), so I guess the binary then needed root credentials for something sufficiently basic that it bailed out when it couldn't do it.

If you're willing to go at it with `strace` and/or `gdb` and figure out what it's trying to do, I'd be fairly curious, but otherwise -- try compiling as a regular user rather than as the superuser.

**Comment by DavidKeaton** [comment]
good catch narc, didn't notice the `sudo` on `make`. This is it.
