### ISSUE TITLE
Chemical reactions

### ISSUE THREAD

**Issue by cogreaper** [CleverRaven/Cataclysm-DDA#12688]
Currently in the game chemical reactions are not supported openly in the world.
ex. pouring a container of bleach and then a container of ammonia into the same location such as a sink will not cause a cloud of mustard gas to be created.
Would it be possible to create item interactions such as this in the game?
##

**Comment by Rivet-the-Zombie** [comment]
Mixing bleach and ammonia will produce a nasty reaction with lots of unpleasant products, but sulphur mustard is not one of them.

**Comment by cogreaper** [comment]
I apologize for making such a careless mistake but could/will such things be implemented?

**Comment by Coolthulhu** [comment]
Having items react with each other would require quite a bit of extra checks.

The best solution I can think of right now would be making a special field to handle reactive substances and trying to place it whenever a liquid item is placed on the map. This field would then check items under it for reactive substances and invoke appropriate reactions if it found anything.

Doesn't look very difficult, but it could be a lot of work. Someone would have to implement a reaction class with a list of reactions, implement results of those reactions, some loading system for them etc.

Overall I'd say it would take medium effort. Meaning it would require at least medium amount of stuff to gain from it.
I don't see how would a reaction system more advanced than "acid spilled on the ground creates acid field" benefit the game.

**Comment by Rivet-the-Zombie** [comment]
>I apologize for making such a careless mistake but could/will such things be implemented?

I'm sorry for snapping at you like that. I'm a bit of a chemistry and warfare nerd and I hear folks say stuff like 'mixing substance X and substance Y produces mustard gas' a lot, and it's one of my pet peeves.

Full disclosure: I once gave an impromptu five minute explanation to the rest of one of my college classes when somebody said 'burning freon produces mustard gas' - it actually produces phosgene, which is still really nasty, but not quite the *same* sort of nasty as sulfur mustard. The instructor was sufficiently impressed that he allowed me to do so and then asked me about it after class and we ended up spending about an hour discussing dangerous chemicals and the first World War.

So yeah, sorry for jumping on you for a common mistake; I'm far, far too pedantic about stuff like this.

**Comment by DavidKeaton** [comment]
I'm also a warfare nerd. Greetings.

**Comment by cogreaper** [comment]
Honestly I guess that I should no longer trust what I see on reddit and I took no offense to your correcting me honestly it was interesting to hear about but maybe instead of being a world check it could be a use function of various chemical items where it would do a reactant check and if those items are possessed they can be used to trigger a rection. For example while holding x chemical A will bring up a menu of options and it could be implemented there which may be less code intensive.

**Comment by cogreaper** [comment]
Also if you are looking for a benefit now you could make meth to sate your addiction or say that you actually found sulfur dichloride and ethylene you could now have a powerful biochemical weapon making science related skills useful. It would also be cool to see things like thorium igniting because of the pyrophoric nature of thorium dust allowing for unique railgun/throwing weapons. I am unsure of the viability of defining such properties of a material like that in cataclysm would be interesting. Thorium and similar substances could be implemented through means such as a reactor where you may find a thorium engine which explodes when handled improperly/upon crashing. This thread was somewhat meant to encompass all substance reactions though it may be difficult to obtain all of those. I also meant for it to be something to think about/build upon.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
