### ISSUE TITLE
Built in weapon mods or multiple firing types.

### ISSUE THREAD

**Issue by DeadLeaves** [CleverRaven/Cataclysm-DDA#12690]
I'm trying to make a mod adding new weapons. However as far as I can tell, there is no way to have 2 weapons in one. Like a rifle with a grenade launcher built in.

I think the easiest way to do this is by allowing weapons to have hidden built in mods. or define alternative firing modes. 

I am not familiar enough with the source to do this myself at the moment, so if anyone know they could easily implement this it'd be great.

**Comment by FireCrow1973** [comment]
so like single fire, burst fire and auto?

**Comment by Coolthulhu** [comment]
You could have fake unremovable mods, but then you'd have to handle the cases where the main weapon is destroyed. It would still probably be way easier than other options.

Having weapon contain ammo rather than having it as charges would be relatively simple, but there could be lots of cases to handle.
However this would have a major advantage of making it easy to add rechargeable batteries to things.

Having weapons with two charge types at once would require some major rewrites.

**Comment by DeadLeaves** [comment]
@FireCrow1973  I was thinking more of having permanent under-slung weapons like grenade launchers and shotguns. 

@Coolthulhu I was also thinking fake mods is probably easiest. If a mod were to drop when a weapon is destroyed, you could begin by simply having so the dropped mod cannot be attached to any weapon type. (Easily done in the json already) Then later implementing having the fake-mod being turned into scrap pieces. 

I'm considering putting a bounty on this, since you have more insight into the code-base, what do you think is an appropriate amount?

**Comment by kevingranade** [comment]
Seems like simply adding an 'unremovable' flag to the mod, then enforcing
it in the mod removal function, and adding its parts in the item destroy
functions would work.
Altering how it is described would be nice, but not essential.

**Comment by DeadLeaves** [comment]
@kevingranade Yeah, that seems like a clean elegant solution. Still would require some way of adding the mod though the json in the first place.

**Comment by DeadLeaves** [comment]
Almost done with this. :)

**Comment by DeadLeaves** [comment]
More or less completed
