### ISSUE TITLE
Activating finger-mounted laser appears to cause infinite loop

### ISSUE THREAD

**Issue by mikegogulski** [CleverRaven/Cataclysm-DDA#12694]
This has happened twice now.

Background:
Finger-mounted laser is bionic "f"
Armed with longbow and ~60 arrows in quiver
Fighting lots of enemies

So, I'm killing off a huge number of fungaloids and spore clouds in an area, and just spamming the keys "f" (fire ranged weapon) followed by "p" (precise aim) repeatedly. When I run out of arrows, "f" gives "out of ammo" and "p" then brings up the bionics menu. Hitting "f" again activates the finger-mounted laser bionic, and at this point the game appears to enter an infinite loop, using 100% CPU on the core it's running on.

This does NOT happen when I activate the finger-mounted laser for mundane things like burning down houses.

Screenshot attached.

![screenshot - 06172015 - 06 42 47 am](https://cloud.githubusercontent.com/assets/118625/8199835/1fe45b02-14bc-11e5-9ae6-3a0d8d756579.png)

**Comment by mikegogulski** [comment]
Oh, the workaround here is to kill the game and load a save.

**Comment by mikegogulski** [comment]
Another workaround: reassign the finger-mounted laser bionic to a different hotkey.

**Comment by mugling** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
