### ISSUE TITLE
Unit tests rebuild every time make test or make check is run.

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#12715]
My make-fu has failed me, I can't for the life of me figure out what I'm doing wrong, probably a misplaced target or something.

**Comment by BevapDin** [comment]
The .o files are removed because make seems them as intermediate files files:
```
$ make -n -d checks
...
Invoking recipe from Makefile:32 to update target `check'.
./line_test; ./shadowcasting_test; ./map_iterator_test;
Successfully remade target file `check'.
Removing intermediate files...
rm obj/line_test.o obj/shadowcasting_test.o obj/map_iterator_test.o
```

This change "fixes" it, but it's ugly. It adds the dependencies directly on the final target (check), which is the same logic used in the main Makefile (`$(TARGET): $(ODIR) $(DDIR) $(OBJS)`). Now the "_test.o" files are not intermediate files anymore but directly required. Alternatively, the files could be persevered (not tested) by marking them as `.SECONDARY`

```diff
@@ -22,15 +22,15 @@ CXXFLAGS += -I../src -Wno-unused-variable
 
 LD := $(CROSS)g++
 
 tests: $(TESTS)
 
-%_test: $(ODIR) $(DDIR) $(OBJS)
+%_test: $(ODIR) $(DDIR)
    $(LD) $(W32FLAGS) -o $@ $(DEFINES) $(ODIR)/$@.o $(CATA_LIB) $(CXXFLAGS) $(LDFLAGS)
 
 # Iterate over all the individual tests.
-check: $(TESTS)
+check: $(OBJS) $(TESTS)
    $(foreach exe,$(TESTS),./$(exe);)
 
 clean:
    rm -f $(TESTS) *.d $(ODIR)/*.o $(ODIR)/*.d
 
```

**Comment by kevingranade** [comment]
aah, I'm not concerned about non-gnu make compatibility, so .SECONDARY is what I'm looking for, thanks!
