### ISSUE TITLE
Two different booby trap recipes

### ISSUE THREAD

**Issue by Soyweiser** [CleverRaven/Cataclysm-DDA#12722]
A booby trap has two different recipes. http://cdda-trunk.estilofusion.com/boobytrap/craft

One requiring cutting and the other not requiring cutting.

And seems the "The Compleat Trapper" has a small typo in the name.

http://cdda-trunk.estilofusion.com/textbook_traps

Both should be an easy fix.
##

**Comment by Rivet-the-Zombie** [comment]
From the .json entry of 'The Compleat Trapper`:

````"comment": "The spelling is intentionally archaic, as this form is commonly used in the titles of books.",````

**Comment by narc0tiq** [comment]
Neither of these seem to be actual issues, so I'm going to close this, but here's the reasoning:

Aside from the aforementioned intentional use of an archaic term, two recipes for one item is perfectly valid (in this instance, they have tags mentioning that one is for a trap made from "open cans, such as food", the other from "closed cans, such as drinks"). The latter, as seen in the item browser link, requires a tool with the cutting quality.

**Comment by Soyweiser** [comment]
That is then the only recipe that makes a difference between tin and alu cans. Seems inconsistent.

**Comment by narc0tiq** [comment]
Maybe it is, and the distinction doesn't seem worthwhile to me, personally -- I'd just merge them and include the tool requirement on the result. Let's reopen this and see if anyone wants to change it.
