### ISSUE TITLE
"Salvaged X patchs" should be "Salvaged X patches"

### ISSUE THREAD

**Issue by slyscorpion** [CleverRaven/Cataclysm-DDA#12720]
As the topic says it's a minor misspelling. I also noticed that "patchs" occurs just about everywhere: when picking them up or dropping them and not just when you salvage leather patches.

**Comment by wmafie** [comment]
It's not really a "local" localization issue, but a "global" localization. The way it is, if any item with quantity >1 is being picked up, or dropped, there will be an automatic addition of "s" at the end of the word. This has been my observation so far.

I don't suppose we have 2 sets of strings for each item/object/etc. for when it is singular or plural. I may be wrong.

**Comment by BevapDin** [comment]
#12511

> I don't suppose we have 2 sets of strings for each item/object/etc. for when it is singular or plural. I may be wrong.

Plural is done via `ngettext`, wrapped in a proper item function: `item::tname(quantity)` or `item::display_name(quantity)`. They return the properly plural form of the name, according to the quantity.

**Comment by narc0tiq** [comment]
> I don't suppose we have 2 sets of strings for each item/object/etc. for when it is singular or plural.

In fact, we do, and it looks like [the item](http://kaer.eu.org:8112/#blob:GENERIC/leather) already has the necessary tag (`name_plural`) (and, according to [blame](https://github.com/CleverRaven/Cataclysm-DDA/blame/master/data/json/items/melee.json#L156), the tag has been there since at least Sep 12, 2014).

It is almost certainly the case that a display function is not showing the correct data. 

In very brief testing:
- I am seeing the correct display ("10 leather patches") in a list on the ground ("You see here 10 leather patches") and in my inventory ("n - 10 leather patches").
- Dropping them seems to result in "You drop your leather patch on the grass. x 10" and picking them up is similarly doing "You pick up: 1 leather patch [n] x 10".
- Applying a pair of scissors to a leather apron gave me "Salvaged 9 leather patchs", which reproduces the issue.

Conclusion: the salvage code isn't pluralizing properly.

**Comment by wmafie** [comment]
Alright, thanks guys! I have much to learn ;)
