### ISSUE TITLE
Massive explosion effect from even the smallest explosives.

### ISSUE THREAD

**Issue by DeadLeaves** [CleverRaven/Cataclysm-DDA#12735]
It seems that even small explosives like 40mm frag gives of massive explosion effects covering a big part of the screen. Presumably not intended. It also seems the explosions ignore walls and obstacles and just draws right on-top of them. It seems the explosions don't actually do any damage either.

I'm running Windows Tiles built yesterday.

**Comment by Coolthulhu** [comment]
Tiles or console mode?

Tiles mode doesn't draw magnitude of the blast (and doesn't draw the blast nicely). The explosion is big, but way weaker near the edges. In non-tiles mode, the power is color-coded, so you can easily see how affected the area is.
The effect is intended, because old grenades were very predictable - you never needed to take any sort of cover when the range of all effects was neatly limited to x tiles.

Explosions are drawn on top of unpassable tiles to show that it "tried" to destroy them. Could remove it if it's confusing.

**Comment by DeadLeaves** [comment]
I'm running windows tiles. But one I talked to in IRC also said the win curses version of the explosions seems a tad excessive. 

About the effect, i like that they're more unpredictable. However the fact that it's drawn over and though impassable terrain is weird. Maybe limit it to only draw on the first impassable tile and not through them.

**Comment by DeadLeaves** [comment]
Also think it's sad that the tiles version gets so little love. While I realize most devs here play in curses, I think having a solid tile version is what is going to attract the game to more players.

**Comment by Coolthulhu** [comment]
> However the fact that it's drawn over and though impassable terrain is weird.

If it's drawn through the unpassable terrain, it may be a bug. I may have missed a case there.
On 0 z-level or below? In z-levels mode or 2D?

>Also think it's sad that the tiles version gets so little love.

It gets love too, just that adding anything graphical to tiles requires from 3 to 30 times more work than adding it to console builds. If I added variable explosion display to tiles back then, at the moment all explosions would look like a bunch of "no tile available", because tilesets don't have appropriate tiles.

**Comment by Coolthulhu** [comment]
As for excessive size: I could skip drawing the weakest part of the explosion or make the range scaling harder, but I'd need someone to provide good data on what is expected from what kind of explosive.

Something like a table of: item type, total range, damage at 50% of the range. For 3-4 items, from the weakest (grenade) to the strongest (ANFO).

**Comment by DeadLeaves** [comment]
Just tested a little, the explosions look great in experimental z-levels(It respects impassables etc), without it however, it looks pretty bad.

About the explosives data, I'm afraid I'm not big enough gun-nut to provide such a thing.

**Comment by Coolthulhu** [comment]
Will check it out then. Looks like I focused too much on testing the z-level version of explosions.

I don't mean realistic explosion data, just what would "look good". The numbers I picked are semi-arbitrary.

Though if it's mostly drawing, it should probably be solved with just changes to drawing.

**Comment by DeadLeaves** [comment]
I would say wait with changing any values before the drawing is corrected. Maybe just adding more transparency to the tiles the further out they are would fix it.

**Comment by kevingranade** [comment]
I think not drawing over impassable tiles that aren't destroyed would end up looking better, I suspect one effect that people are seeing is blasts spreading out from an exit point like a door, and if there is explosion on both sides, the two parts get joined together.

**Comment by DeadLeaves** [comment]
I agree, Great point, I think that would be an improvement.

**Comment by Griffinhart** [comment]
I noticed this as well; lab turrets now explode big enough to nearly cover the entire room they're in (if it's one of the smaller quarter-size rooms); occasionally the explosion will go outside of the room (i.e. through a doorway, which is actually a pretty cool effect) depending on the exact room size and doorway location.

Also the explosion animation is white instead of red, though I don't know if that's a bug or working as intended.

**Comment by kevingranade** [comment]
That's the extent of the affected area, but at the edge it's very weak, for
example it may or may not break windows at the edge.  The blast is
color-coded for strength, white means it's relatively weak.

**Comment by Griffinhart** [comment]
Well, it's more like previously, lab turret explosions weren't big enough to even reach the terminal that's usually nearby them.

But if this is working as intended, then it's (tautologically) not an issue.

**Comment by Eldhelion** [comment]
linking the threadon on the forum http://smf.cataclysmdda.com/index.php?PHPSESSID=WkuKnps1bAPIO8GCMGd2d1&topic=10696.30

**Comment by Chase-san** [comment]
It just seems strange, maybe a different tile used for under 50% damage, and under 25%.
