### ISSUE TITLE
Active items crash (debug mode, linux x64)

### ISSUE THREAD

**Issue by bdragon28** [CleverRaven/Cataclysm-DDA#12743]
Somehow v->active_items is being corrupted during construction somehow.

This set of instructions worked me to reproduce consistently.

new world
new game (random char)
safemode off
walk south out of shelter (four squares south of door or so)
wish for:
welder, welding goggles, wrench, steel frame, battery x 5
reload welder
set skills to 10
spawn car
open car door and stand in doorframe
spawn 2 raw hide (fresh)
drop to adjacent tile one of them to the left and the other to the right
examine car and weld the steel frame to it. (I tested below the bottom left corner, didn't seem to matter where though)

**Comment by bdragon28** [comment]
This was against head at the time. (205b560fe9aaffde17c979450b3a68976af5e2e8)

**Comment by bdragon28** [comment]
Starting to suspect compiler/libstdcxx bugs. I'm on g++ (Debian 4.7.2-5) 4.7.2 and I'm starting to doubt how well my debugging containers are working in c++11 mode.

**Comment by bdragon28** [comment]
This is the same crash as #11108 and I see in that issue they were also on 4.7 debug containers. After trying with GCC 4.9 on a different machine, I was unable to get it to crash.

**Comment by bdragon28** [comment]
Additionally, copying over the cataclysm executable from the 4.7 machine made it start crashing on the 4.9 machine.

So it appears that libstdc++ 4.7 container debugging has a bug in it that was since fixed.

**Comment by narc0tiq** [comment]
That is good to know! I have a curiosity -- does this reproduce with the latest Jenkins binary for [Linux_x64/Curses](http://dev.narc.ro/cataclysm/jenkins-latest/Linux_x64/Curses/)? That's compiled with:
```
+/www/virt/dev.narc.ro/htdocs/cataclysm/mainline-build.zsh:63> ccache g++-4.7 --version
g++-4.7 (Ubuntu/Linaro 4.7.3-12ubuntu1) 4.7.3
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

```
-- (via http://ci.narc.ro/job/Cataclysm-Matrix/Graphics=Curses,Platform=Linux_x64/3332/console)

The C++ stdlib is `lib64stdc++6-4.7-dev.deb`, with matching version number.

**Comment by mugling** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
