### ISSUE TITLE
Battery weights, stacking charges

### ISSUE THREAD

**Issue by DavidKeaton** [CleverRaven/Cataclysm-DDA#12764]
So, I've been thinking on this for a while. It seems odd that batteries increase weight so drastically for an item. It gets even more bonkers when one considers rechargeable items. I understand that this is probably due to the way batteries are an "ammo," but a rechargeable battery being fully charged adding several units of weight seems a bit much!

Discuss? :-)
##

**Comment by Cat09** [comment]
this may be related to the kind of linbo identity of what batteries ARE, last I checked you could make batteries with a tin can or similar, yet it fits inside a flashlight, and can be split in half and seperated. additionally, as they are used, batteries just evaporate into thin air.
if the charge is representative of a number of items, weight should be linear with charge, if it represents the electrical content of an item then weight should do nothing, though theorhetically there could be some sort of liquid that as it reacts it vaporizes.... sounds odd though.
Question is, how hard would it be to make items use charges of an item they contain? Psuedocode: flashlight{battery{charges=24}} or flashlight{battery_rechargeable{charges=24}}
you might be able to use the casings of old batteries to make new -homemade- ones? (might take 2 old ones, and the result might be ~75 charges)

**Comment by Coolthulhu** [comment]
> Question is, how hard would it be to make items use charges of an item they contain?

I thought about it and it looks easy at the first glance, but it isn't a small task.
We'd have to replace basically every single reference to "charges" of an item that is a tool or a gun.

This could be good in the long run, because working with charges is quite limiting, though. We could have things like rechargeable batteries without it being a mod, batteries that keep charge rather than stacking "video game gun magazine style" and charge-less items consuming charges from nearby vehicles.

**Comment by kevingranade** [comment]
Remind me, what's 'drastically'?
Generally though, the options are:
Item weight factors in batteries, I.e. assume there are always dead
batteries in it even if discharged.
Make anything that holds batteries have two weights, empty and full, based
on some estimate of how much battery is needed to represent the max
capacity of the item.
Scale weight from batteries based on current number of charges. (I think
this is what we do now)
Make batteries discrete items with a weight, disallow merging them outside
of a charger item or similar.  Tools would have a capacity in # of
batteries instead of # of charges. (I'd like to do this eventually)

**Comment by DavidKeaton** [comment]
drastically to me is a PDA with 1 battery vs 100. The discrepancy is the weight between the two.

**Comment by ArikVhedrovix** [comment]
There is an equally strange situation with battery volume. For some small electronics, it makes more sense to have them loaded with batteries to save volume. For example, I usually carry extra tazers if I have a lot of batteries bc they store 500 charges which is 5 volume in a tazer that is 1 volume.

**Comment by DavidKeaton** [comment]
They just need a bit of a rework, as it being an extension of charges is what's causing the issues. I don't right off know any approach that is non-hacky to fix this.

**Comment by narc0tiq** [comment]
> Item weight factors in batteries, I.e. assume there are always dead batteries in it even if discharged.

I honestly would prefer that as a relatively quick fix for sanity's sake, but transferring battery charges as if they were a liquid is something that's always rubbed me the wrong way.

As a somewhat saner future plan, I'd like to see battery items with their own separate charge levels, and some kind of crafting system to transfer charge between them (with some small loss along the way). This is basically @kevingranade's preferred last option.

**Comment by Xpyder** [comment]
just to hop in here on the weight balance

empty storage battery: 330.7 lbs
full storage battery: 418.9 lbs

That's almost a 100lb difference between empty and full

**Comment by Leland** [comment]
@Coolthulhu was this fixed by #21340?
