### ISSUE TITLE
Pouring containers into themselves

### ISSUE THREAD

**Issue by tvm1** [CleverRaven/Cataclysm-DDA#12781]
A naked man stands in the middle of the forest, holding sealed jar of human broth.

But now it's time to do it! Shivering naked man unseals the jar and pours it into itself!!

![screenshot from 2015-06-25 20 00 47](https://cloud.githubusercontent.com/assets/12072674/8361742/025d3512-1b75-11e5-8444-320c782b50ef.png)
##

**Comment by Coolthulhu** [comment]
It simplifies things a bit. Currently when you pour something in to a container too small to contain it, you essentially take out the content, pour some of it into the new container, then pour the rest back into the old container.

**Comment by ArikVhedrovix** [comment]
+3 Bonus points for good issue presentation

**Comment by drbig** [comment]
Maybe a guard on such case so you get something like "You decide not to pour %s anywhere."?

**Comment by karlnp** [comment]
or an Infocom-esque "You slosh the container around until you get bored."

**Comment by drbig** [comment]
> "You slosh the container around until you get bored."

I've learnt a new word today, thank you :)

**Comment by Headjack** [comment]
I like those wry, sarcastic responses parsers sometimes have, +1. 

Did anything ever get worked out for the situation where you can have a pot, a bottle of dirty water, and a fire, yet be unable to boil it because you dont have a suitable second container, despite the fact you'd necessarily pour the bottle into the pot to boil it, thus leaving it a suitable receptacle?

**Comment by ArikVhedrovix** [comment]
Yes, I often find myself without an extra bottle.

**Comment by tvm1** [comment]
@Headjack Yep, happened to me several times

That should be also fixed.

**Comment by drbig** [comment]
> Did anything ever get worked out for the situation where you can have a pot, a bottle of dirty water, and a fire, yet be unable to boil it because you dont have a suitable second container, despite the fact you'd necessarily pour the bottle into the pot to boil it, thus leaving it a suitable receptacle?

Yeah been annoyed by that too. The only logical explanation for it would be "your pot can't hold all that water", but that's a weak excuse anyway.

I guess this falls into the 'Long-term' category of stuff to rework/fix.

**Comment by Oskar636** [comment]
The issue works only if you have only one container that isn't filled to the max.
And now since the most common case because of that system is gone, ( when you boil something you need to have something to contain it, and now almost* anything that has a contain tag can contain liquid ) , this can get reworked I guess.
build 5864 windows 64bit console
*didn't check how many actually, but know for a fact that pots can store liquid now
