### ISSUE TITLE
Do away with item::burnt, make fire damage items instead

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#12806]
Currently fire damage to items is tracked totally separately from everything else in the `item::burnt` member. It has three effects: when it accumulates enough (multiple of item volume), the item is destroyed, some materials stop being flammable at high `burnt` (for example wood - logs stop being flammable after few turns in fire) and burnt corpses have lower chance of reanimating.

If needed, those effects could be reasonably replicated without an explicit `burnt` variable - for example by making dense wood objects stop being flammable (they could still fuel fires, just not be used to start them) and by making fire just cause damage to items.

The disadvantages of having this `burnt` variable are as follows:
- It can't be removed from an existing item in any way
- It doesn't change item stats in any way
- Disassembling burnt items treats them as 100% fine
- Display of this variable is a bit problematic: it can be long ("badly burnt" prefix), it can't be removed from the object due to that lack of repair part
- Corpse reanimation - current handling of it is confusing: badly burnt bodies have 0% chance of reanimating, but are still active until they attempt to reanimate
- Armor damage code doesn't understand it, players' clothing will get cut in fire rather than burned

Advantages of keeping it would be:
- It has higher granularity than damage. This makes fuel values more constant than `one_in` would be
- Partially broken items don't lose their fuel value (not all that realistic when we consider destroyed item which do lose their fuel value)
- A tiny bit more information: any "burnt" item was in fire and didn't just spawn burnt

While the current code more or less works, the handling of burnt object makes it harder to implement proper fire protection stat for armor, which is why I'd like to get rid of `burnt` variable.
##

**Comment by Rivet-the-Zombie** [comment]
Since we don't even use the descriptive adjective item damage system by default, the burnt tag seems doubly superfluous. I wouldn't mind seeing it get the axe in order to achieve a more simplified system of item damage type(s).

**Comment by vache** [comment]
I like the idea of burned items.  Also, I don't think it makes sense in most cases for burnt items to be repairable.  I could see dropping the burn level system, combining burn level with damage with some toggle if its burnt, then just having burnt items be irreparable damage with different descriptions.

So, you have two pairs of jeans, you wear one and get whacked by a zombie a few times, that pair of jeans is now tattered, with damage level 4 (just guessing).  You take that one off and put another pair on and accidentally walk in a fire.  That pair also gets damage level 4, but since the source was fire, they become "badly burnt jeans".  Now you have badly burnt jeans and tattered jeans, you repair your tattered jeans with a sewing kit, but the burnt pants are too destroyed to repair.

Some situations I can see this won't quite hold, you probably could repair your pants with enough patches, but things like electronics probably wouldn't hold up to fire well.  Maybe there could be a generic "damage_source" type variable that holds what caused the worst damage to the item?  That way you can keep the damage system but you can add a little more description to it, like "corroded" for acid damage, "burnt" for fire, and so on.

**Comment by DavidKeaton** [comment]
As I was reworking items I did exactly this, change fire to it's own damage type instead of burnt, and added a method to damage an item with a `damage_type`.

**Comment by i2amroy** [comment]
If granularity is a problem we could always just increase the granularity of the damage system itself. By adding just one tile in the menu (and changing to have multiple levels of reinforced clothing) we could have as many as 9 damage levels plus the fully destroyed one.

**Comment by Cat09** [comment]
as items are damaged it currently works like ||| to ||/ to ||\ to ||. right?? I forget the progression, but the last icon could progress in color before switching symbol, then reset color at that point and progress for each (unless we can't use color there)
not very clear, but... ah well

**Comment by i2amroy** [comment]
Honestly if we really wanted to granularize it we could just grab one additional tile and do the symbol progression as ```.->:->/->|->!```, with ```^``` as the reinforced tile. That lets us have 13 different levels of damage displayed in 3 tiles, and then another three various "reinforced" stages on top of that (```!!^```, ```!^^```, and ```^^^```) for a grand total of 16 damage steps total.

**Comment by BevapDin** [comment]
Or we could keep the current amount of visible damage levels and just change the internal representation to a higher precisions. Instead of having 5 damage levels (0-4), we could internally use 20 levels (0-19), but for presentation just divide by 4. Internal damage 0-4 appears as undamaged, 5-9 appears as one damage and so on.

**Comment by i2amroy** [comment]
Psh, well if you want to do something like that then yeah!

(That's definitely another good idea as well. :P)

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
