### ISSUE TITLE
Turbo

### ISSUE THREAD

**Issue by Chase-san** [CleverRaven/Cataclysm-DDA#12830]
I have for some time run a small mod where I add turbos into the game. Basically, they can be installed on any vehicle exactly the same way as an alternator, but provide extra engine power instead.

My idea for these is for the turbos to give a percentage boost to engine power rather than a flat boost (so a turbo charged 1-cylinder engines doesn't equal a 4-cylinder or something silly like that). Say, 10%, 20%, and 40% boost to engine power for an eco, standard and racing turbo.

In DDA these would basically be items that magically increase engine power. There are down sides and annoyances in real life, but those cannot be easily emulated in DDA.
##

**Comment by kevingranade** [comment]
From what I understand of turbos they should increase both power and fuel
consumption, though a slight increase in efficiency is reasonable as well.

**Comment by Chase-san** [comment]
It's a good bit more complicated then that but, what isn't. Basically it depends on how the turbo is tuned (intake vs exhaust turbine size, ar ratio, psi, etc) and the configuration of the engine for what a turbo will do.

Some turbos are setup for economy, and improve overall gas milage with a very mild increase in horsepower, where as racing turbos have a massive increase in power and a pretty nice big hit in the mileage as well. Then there are the middle of the road turbos that give you more horsepower without really effecting your mileage at all.

**Comment by Cat09** [comment]
shoulnd't this be in PR or discussion? not really an "issue" is it?

**Comment by Chase-san** [comment]
That's a good idea. I might make up a pull request for this over the weekend.

**Comment by Coolthulhu** [comment]
Wikipedia says that turbocharging is "common" and that most diesel vehicles (also heavy machinery, ships etc.) are turbocharged. It also mentions disadvantages, such as "turbocharger lag". I didn't read into it much more than that.

So, what exactly would the turbochargers change? If most diesel engines have it installed, assuming that all of them do simplifies things without any real loss in functionality.
If it is just to provide a flat or percentage boost, it may as well be considered fully integrated into any engine for which it would be reasonable to be turbocharged.

Customization? I assume that sports car would come with a different (or at least differently configured) turbocharger than a hippie van - performance vs fuel economy.
But then, currently non-electric engines don't allow changing fuel economy at all. It would have to be implemented to make a separate turbocharger part make sense.

**Comment by Chase-san** [comment]
First, a hippie van wouldn't have one at all (stock anyway). Turbos were restricted to mostly sports cars until more recent days.

Basically, these might be found in garages, sports cars, small modern cars (like the mini), and a number of diesel vehicles (turbo diesels).

**Comment by Coolthulhu** [comment]
OK, maybe not every car. But still:

DDA takes place somewhere around year 2040. If many "regular" cars are produced with turbochargers today, it can be assumed that at least that many (by percentage) cars will have turbochargers.

A bit more research:
http://www.forbes.com/sites/jimhenry/2013/04/30/most-engines-could-be-turbocharged-some-day-taking-diesels-and-gasoline-into-account/
This article states that diesels with no turbochargers are rare outside developing nations and that 75% of new cars in Europe have turbochargers. Didn't say about US

http://www.autoblog.com/2014/10/06/turbochargers-double-us-over-next-five-years/
Here it's 66% for Europe, but not just for new cars, but cars on roads.
For US, it's 20% of new cars.

Even if we ignore the company's optimistic projections (40% of new cars in US by 2019) and assume the market stagnated, pretty much all the diesel vehicles and many of the gasoline ones should have the turbochargers, meaning they wouldn't be by any means uncommon and hard to find.

The system for turbochargers should offer more difference in gameplay than just adding another no-brainer part to install on every vehicle the player customized. If it was just a +x bonus to power, it may as well be considered integrated in the engine.


So: what would turbochargers actually add?

**Comment by Rivet-the-Zombie** [comment]
A turbocharger uses exhaust gas pressure to operate - thus, no loss in engine efficiency but a lower air intake compression force, whereas a supercharger uses crankshaft power to create a much higher air intake compression. Since the game is taking place 25+ years in the future it would be safe to assume that most engines have a built-in turbocharger already.

Naming this part 'supercharger' would make more sense, as superchargers are not likely to become a standard engine system any time soon, and they pretty much work as stated - causing a small drag on fuel economy while boosting all other aspects of engine performance.

**Comment by Chase-san** [comment]
That's certainly acceptable, and superchargers are pretty rare. I say probably only only stock on sports cars. But a lot easier to remove and add than an engine.

**Comment by Cat09** [comment]
if this is the plan, then all the -car and up- (motorcycles???) engines should have their power/fuel stats adjusted to assume turbos

**Comment by Chase-san** [comment]
No need for that really. Though I feel Cata doesn't need to be very historically accurate, this kind of thing should be rare so I'll mock up a "classic sports car" for the game, and give it a supercharger.

**Comment by Rivet-the-Zombie** [comment]
>engines should have their power/fuel stats adjusted to assume turbos

What would be the point of this? We can say 'they've already got turbochargers' and leave everything as-is.

**Comment by kevingranade** [comment]
To the best of my knowledge the fuel consumption and power figures are only
very roughly based on reality in the first place, if anything the larger
engines need to be toned down a lot, just dropping a big engine in a car is
not going to get you a 300MPh racecar.

**Comment by Rivet-the-Zombie** [comment]
>just dropping a big engine in a car is not going to get you a 300MPh racecar.

And even if it did, you'd never make 300 mph unless it's in a car that's specifically designed to go fast like that, and on an absolutely ideal surface. We really need a cap on those speed ratings.

**Comment by drbig** [comment]
> We really need a cap on those speed ratings.

Indeed.

**Comment by i2amroy** [comment]
If we don't want to do a hard cap we could just give an ever-increasing chance of spinning out of control. As pointed out near the bottom of [this xkcd what-if](https://what-if.xkcd.com/61/), most cars will suffer from "liftoff" between 150-300 miles per hour where they generate enough lift to literally flip themselves off of the pavement. Eventually we should just have it actually flip your car, but until then we could potentially look into just having it make you spin out more and more until your car becomes nigh-impossible to control.

**Comment by drbig** [comment]
Honestly? The top-speed figures make no sense given earthly physics. And 300 mph (482.80 km/h) is more of a cursing small/mid air plane speed than anything that can go roads, regardless of their quality :)

**Comment by kevingranade** [comment]
Keep in mind that the squares/turn to MPH conversion is also fairly
arbitrary, if at any point the game balance seems fine but the stated speed
is nonsensical, consider just rescaling the speed displayed.

**Comment by Cat09** [comment]
the cataclysm has caused space/time to destabalize, making the very fabric of reality unreliable!
on a side note we might not want too hard coded a limit for the sake of remote controlled flying !funmobiles!   ;]

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
