### ISSUE TITLE
Adderall should boost your focus

### ISSUE THREAD

**Issue by narc0tiq** [CleverRaven/Cataclysm-DDA#12842]
I'd like some opinions on this, but it seems to me that Adderall, being an anti-ADHD drug, should probably have some direct effect on your mental focus.
##

**Comment by FunnyMan3595** [comment]
My opinion is that Adderall should lock your focus to a specific value.  Say, 80.  That way, it's super-useful if your focus is low, but harmful if you're already in good shape.

We can keep doing the usual math in the background, and just lock the display and function to 80.  That way, if you do a lot of high-focus stuff while the Adderall is in effect, you'll crash to a very low focus after it wears off.

**Comment by DavidKeaton** [comment]
Oh man, can I tell you ALL about this drug.

Focus would be better at a 90, possibly 95. You FOCUS. It has an after effect that can last another hour or two. Your appetite comes as soon as your 12 hours are up (XR). Otherwise, you don't feel the urge to eat. You can't sleep, even another 2 or 3 hours later sometimes.

**Comment by FunnyMan3595** [comment]
Yeah, I'd love to see more realistic side-effects for drugs.  As-is, addiction and withdrawal are about it.

**Comment by kevingranade** [comment]
If we're making a drug reflect the RL effects more, we also need to shed
the effects not based in reality (I'm thinking of the speed boost here).

**Comment by Rivet-the-Zombie** [comment]
The speed boosts from stimulants have already been heavily nerfed. If you're flying on enough of them to reach speed +10, you may already be on your way to an overdose.

**Comment by Coolthulhu** [comment]
It's really hard to overdose with a cap on stimulant change. Taking a stimulant can only bring the stim value up to 3 times the item's stim. Overdose happens below -200 and above 250 stim, meaning thorazine (-30), adderal (24) and any kind of alcohol is safe to drink in any quantity.

Also, there's a bug with this cap: cap only cares about absolute value, meaning once you get maximum saturation of thorazine, adderal won't bring stim up until it drops to 3*-24.

**Comment by Cat09** [comment]
Real Life drug effects would probably help show the incredibly depressing effects drug abuse can have

**Comment by DavidKeaton** [comment]
should the caps for overdose be lowered in light of the swim cap? Adderall is fairly easy to OD on.

**Comment by Rivet-the-Zombie** [comment]
>should the caps for overdose be lowered in light of the stim cap?

This sounds like a good idea to me, unless there's something in the math that I'm not aware of.

**Comment by Coolthulhu** [comment]
Death overdose, stim effects soft overdose or both?

Here's a sample of the stims with the highest absolute value:
* Strong alcohols: -12 to -14
* coffee 12
* caffeine pill 12
* sewagas inhaler -12
* fancy hobo -15
* moonshine -18
* cocaine 20
* low-grade methamphetamine 20
* methacola 20
* pink tablet 20
* sewer brew -20
* Adderall 24
* atomic coffee 25
* atomic energy drink 27
* Thorazine -30
* crack 40
* tainted tornado -60

Under current system (3*stim cap), it is not possible to make strong alcohols cause an overdose without also making tainted tornado kill anyone not stimed up.

Also, if someone is to work on overdoses, it would be nice to address the whole stimulant vs depressant overdose thing, so that vodka won't save you from meth overdose.

**Comment by karlnp** [comment]
I already have a fork with some drug-related typo and grammar fixes (mostly plurals), so I can take a pass at the Adderall thing and think about wider systems interaction concerns with drugs. (If I'm coding, I'm on Adderall, so I am Quite Familiar with the drug & related compounds.)

**Comment by DavidKeaton** [comment]
@karlnp Yep, ADD duder here too. I'm always on the junk.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
