### ISSUE TITLE
NPC killing zombie child causes guilt based morale penalty.

### ISSUE THREAD

**Issue by DodgingRain** [CleverRaven/Cataclysm-DDA#12878]
http://i.imgur.com/ixxYGga.png

I didn't land the killing blow.

**Comment by karlnp** [comment]
I've been thinking about whether or not to fix this on my fork. I kind of get it from an "oh, the humanity!" sort of perspective - you're culpable whether or not you land the killing blow, and the existing desensitization makes sense in that regard too. It might just be as simple as changing the copy for when an NPC kills a zombie child to be about horror rather than personal guilt.

**Comment by Coolthulhu** [comment]
Looks like the guilt code simply isn't checking for the killer. Making it do so would prevent car ramming from giving the penalty, but thats minor considering NPCs don't give one either.

**Comment by ejseto** [comment]
If it's horror rather than guilt, you should feel it upon *seeing* them, not killing them, like the wildling woman in Game of Thrones who lets the kid zombies eat her. I think morale modifiers based on what you see would be pretty interesting. You could also get a bonus from, say, seeing a majestic deer, like Coral from TWD.

**Comment by karlnp** [comment]
Yeah. That's the kind of thing I like anyway - I did a test implementation of horror & traumatic sights/memories associated with landmarks in RimWorld, for example - so add it to my plate as another planned mod, I guess. The more pertinent question is whether this behaviour is a bug or a feature.

**Comment by drbig** [comment]
> Looks like the guilt code simply isn't checking for the killer

This seems to be a relatively common case which will need to be addressed to get 'proper' NPCs.

On the other hand, I do like the approach of "seeing horror / beauty" as the root for morale penalties/boosts.

**Comment by i2amroy** [comment]
I'd say just fix up the killer check. If we do decide to have some penalty for just seeing it then it should probably be more like an 80/20 split, since sure you might feel guilty, but not as guilty as you would be to actually deal the final blow.
