### ISSUE TITLE
Early onset symptoms for drug OD.

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#1291]
Currently you have 0 warning before a death from drug overdose occurs, which as has been pointed out in http://www.cataclysmdda.com/smf/index.php?topic=390.30 this is both unrealistic and confusing.
Add various early-onset indicators and symptoms for various drugs, not so much to get people to back off, as it's often too late, but for a less confusing experience and possibly to educate players about the dangers of drugs with near-misses.
##

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.

**Comment by kevingranade** [comment]
I consider this a ui bug.  unless it's supplanted with another solution to the same problem I'd like it to stay open.

**Comment by sxmichaels** [comment]
I can try to implement this, but I'm not sure what the consensus is on a few points:
* What kinds of warnings are preferred? Should they be textual warnings only, or actual status effects? For effects at both extremes of the `stim` spectrum, my cursory research produced the following, possibly all of which can stack as things get more serious.
    * **Stimulants:** feeling cold -> shaking -> hypervigilance/paranoia -> hallucinations
    * **Painkillers:** sleepy -> dizzy -> winded -> blackouts/fainting
* What level of `stim` is considered "high but still normal", i.e. when should the warnings start? Right now death occurs at +250 and -200 respectively (or 240 for painkiller level).
* Where should these checks be placed? `player::suffer()`, where Chemical Imbalance and addiction checks occur? `player::check_needs_extremes`, where the "your heart stops" check occurs?

**Comment by Night-Pryanik** [comment]
> What kinds of warnings are preferred? Should they be textual warnings only, or actual status effects?

Both.

> What level of stim is considered "high but still normal", i.e. when should the warnings start? Right now death occurs at +250 and -200 respectively (or 240 for painkiller level).

I'd say +75/-60 for `stim` and 130 for `pkill`.

**Comment by kevingranade** [comment]
To put it another way, the minimum needed for 0.D is messages, in order to let people know that it's dangerous.
A nice to have is intermediate symptoms that cover a wider range of symptoms.

As for levels, functionally there are a few:
* symptoms for "higher than recomnended dosage"
  * give early warning that multiple doses have consequences
  * can be cosmetic or low impact
* symptoms for very high dosage
  * reinforce that high doses are dangerous
  * should have noticeable impact
* symptoms that occur before death.
  * final warning before death
  * should be nearly incapacitating

**Comment by sxmichaels** [comment]
Here's another thought: should `e`xamining medications that can kill you display an automatically-generated "maximum safe doses" line in the interface? You could just take e.g. `floor(STIM_LEVEL_THAT_KILLS_YOU / stim)`, and it would make sense that meds would be labeled with that information in the game world.

**Comment by Night-Pryanik** [comment]
Character shouldn't know how much `stim` he has at the moment.

**Comment by sxmichaels** [comment]
Oh, I meant the `stim` property of the medication itself (it's called that
in JSON at least, not sure about the code), i.e. how much your stim changes
upon taking one dose.

2017年12月6日 07:44，"Anton Burmistrov" <notifications@github.com>寫道：

Character shouldn't know how much stim he has at the moment.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/CleverRaven/Cataclysm-DDA/issues/1291#issuecomment-349678868>,
or mute the thread

**Comment by kevingranade** [comment]
Medicines aren't normally labelled with lethal dosage levels, they usually
have a recommended dosage and a max dosage that's considered safe (if that,
prescription medicines will just have a dosage with no additional info),
but that is the dosage before you're expected to encounter side effects,
not anything related to lethality.

**Comment by Zireael07** [comment]
Display max dosage then (= dosage for the first level of messages outlined in the PR)?
