### ISSUE TITLE
Add ways of giving orders to npc to make up for poor AI

### ISSUE THREAD

**Issue by RafeHaab** [CleverRaven/Cataclysm-DDA#12935]
Suggestion: Telling them to not pick up items, to sleep now, to actually to hide in a spot silently, or to equip certain item yhey have on their inventory would make them more useful.
##

**Comment by Soyweiser** [comment]
I agree, what ever happened to the 'no pickup' zone thing. I got the idea that never worked for npcs.

**Comment by narc0tiq** [comment]
I am under the impression that there was a zone type specifically for
preventing NPCs from picking stuff up. My email history suggests it came
around with PR #12742.

**Comment by Coolthulhu** [comment]
What's wrong with no pickup zone? It worked fine last time I looked at it - NPCs would not consider picking up items in the zone.

**Comment by Soyweiser** [comment]
Lol, my bad I guess. Think I didn't use it correctly then. Or something else. (might even be that I had already killed the npcs before it was implemented).

Consider my remark retracted.

**Comment by kevingranade** [comment]
it only works on friendly NPCs, hostile NPCs don't care what you've
claimed, as intended.

**Comment by RafeHaab** [comment]
I think we need a way to order our followers to not pick up items. That way, we can take them into looting trips and just give them whatever we think we need, instead of having them pick up trash all the time.

**Comment by Soyweiser** [comment]
Yeah we already have a system where you can designate areas of no pickup. A system telling a npc not to pick up anything could easily enough be coded. With the no guns system already in place.

ill add the no pickup areas to the wiki later when im back at a pc.

**Comment by Coolthulhu** [comment]
I think we should drop the whole "NPCs are individuals with own goals" thing. It could be added later on, but for now it causes NPCs to be a good target for murder/"accidents" (being kited into a horde of zombies) to grab their items (typically a firearm+ammo).

Instead, allying difficulty should depend on NPC's wealth and abilities (possibly including a payment of some sort), but once that's achieved, the NPC should act more like a minion. This would make NPCs more valuable and actually improve their lifespan because now the player would want to keep them alive.

**Comment by RafeHaab** [comment]
Coolthulhu is right. Smart npc can be added later. For now, just minions is an improvement over what we have. If someone could make a few more orders, like "stay in this exact spot and guard it", "follow me closely/mid-distance/a bit far" and "do not pick up anything", they would be useful as we guide them to a long life/doom.

**Comment by Oskar636** [comment]
I think you can tell some orders but since I don't play with npcs can somebody take a look at this?

**Comment by illi-kun** [comment]
@Oskar636 no need to bump issues. It's better to focused on issues you able to reproduce and provide save files for simplification of further work.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
