### ISSUE TITLE
Player does not die in "watch yourself die"

### ISSUE THREAD

**Issue by nrfowler** [CleverRaven/Cataclysm-DDA#12956]
Enemies continue to attack and player does not die, the game does not end or respond until I press q.

I am using version c963912, tileset.

**Comment by drbig** [comment]
This sounds interesting...

**Comment by Rivet-the-Zombie** [comment]
What do you mean 'player does not die'? The expected behavior when you select Y at the deathcam prompt is that the game will continue to show what happens after your death. This usually entails all the nearby monsters gathering around your body to gang-beat it to bits. Nothing should be ending until you press q to tell it to stop. Is this what's happening in your case, or is it something different?

**Comment by drbig** [comment]
I'm apparently completely oblivious to how deathcam works...

**Comment by nrfowler** [comment]
It isn't explained that the player is dead, it just says "watch your last moments?" It was not clear to me whether the PC has actually died or not at that point. The right panel does not indicate the player is dead either, the health stays above 0. It might be good to just change the prompt to something that explains it is a deathcam or set the health to zero while the deathcam plays.

**Comment by drbig** [comment]
> health to zero while the deathcam plays

At least that.

**Comment by drbig** [comment]
Update: this is another one of the SDL redraw bugs, as we do have a message shown while in deathcam mode how to exit :( And it works in curses.

**Comment by nrfowler** [comment]
My apologies I should have tested it in curses.

**Comment by drbig** [comment]
@nrfowler No need to apologise. It's still a bug, though the real reason is much deeper unfortunately. And btw. have a look at the (new) [ISSUES.md](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/ISSUES.md).
