### ISSUE TITLE
Dirty/Clean/Sealed CBMs

### ISSUE THREAD

**Issue by FunnyMan3595** [CleverRaven/Cataclysm-DDA#12964]
For some CBMs, like those found in a lab, it's reasonable to assume that they're packaged in some sort of sterile package, and are therefore fairly safe to install (given sufficient skill).

On the other hand, it's entirely possible to cut a CBM out of a zombie and install it in yourself, without even a rag to wipe the grime off of it.

To reflect this, CBMs should have a contamination system, much like water does.  A Sealed CBM is the equivalent of clean water: it's been cleaned, disinfected, and sealed to prevent accidental contamination (i.e. no change from current).  A Dirty CBM is still covered in zombie bits, dirt, or other unpleasantness, and is likely to cause serious problems (infections, etc), even if you install it properly.  A Clean CBM is halfway between: you've had a chance to wash it off, but there could still be some microscopic nastiness clinging to it, so it's got a lower chance to cause issues.
##

**Comment by kevingranade** [comment]
Sounds good to me, your butchering check could factor into this, with
mistakes yielding badly contaminated bionics instead of outright breaking
them.

**Comment by tyrael93** [comment]
That's a very nice idea because of all the burnt-out bionics you get when butchering corpses, even at insanely high- debugged survival skill and a perfect butchering tool. 
I did some tests a while back and it doesn't seem like having more than 3 survival and a pocket knife instead of 20 survival and a hunting knife changes anything when salvaging CBMs from a corpse. You folks know more about the actual code than me so I don't rightly know, but anyway.

How about every CBM taken from a corpse is labeled as "dirty X" and then you have to use disinfectant and clean water to make it "clean" and then use a vacuum sealer to make it a regular CBM? Or add a single recipe  with all these three or skip the vacuum sealer part? It'd be easy to add a couple recipes , the only thing I don't have any idea how to do is to make it so getting dirty CBMs when butchering a corpse, that's sourcecode work.

**Comment by Zireael07** [comment]
I like both @tyrael93 's idea and the original.

**Comment by FunnyMan3595** [comment]
Harvested CBMs should be dirty by default, definitely.  I'm OK with variable contamination levels depending on skill, as Kevin said.  (This is a parallel to the water system where "dirty" water remembers how clean its source was, so it can do different rolls for different sources.)

As far as recipes go, my basic thinking is:

* Clean CBM: Dirty CBM, 4 units clean water, rag/towel (tool)
* Sealed CBM: Clean CBM, 4 units alcohol OR (1 unit disinfectant OR bleach + 4 units clean water), rag/towel (tool), vacuum sealer (tool)

Alternatively, there could be a step between clean and sealed that gives a Disinfected CBM with a short spoil timer (e.g. 5 minutes), after which it reverts to being Clean.  So you can install it right away without a vacuum sealer.

**Comment by tyrael93** [comment]
Oh man I totally forgot about alcohol and bleach, that would make it a lot better actually since disinfectant is pretty hard to come by. No idea how the five minutes thing would work unless we pretend it's "spoiling" like a comestible. 
Wouldn't that add the [old] tag after a minute or two though? That'd be weird.

**Comment by FunnyMan3595** [comment]
If we don't already have a system for changing an item's type after a delay (and I think we do), it'd be useful to write.

**Comment by narc0tiq** [comment]
I think at the moment there's a requirement for something to be a
comestible in order to spoil in the first place, but the rotting code could
handle non-comestibles just fine.

Alternately, and likely closer to the desired implementation, we also have
the example of wet towels that dry out over time -- I seem to recall those
use a method other than rotting for "decaying" into their dry selves,
possibly just a part of their active item handling. This should work for
disinfected CBMs just fine.

A further point to add to the discussion -- each CBM is its own item type,
so it would be good to avoid (manually) adding new itypes for the
dirty/clean/disinfected/sealed ones. Either derive them from the existing
ones, or (better) fit them all into a single itype and use item flags to
derive their current state.

**Comment by macrosblackd** [comment]
I'm fairly certain you could utilize the active item functionality to do this.

**Comment by kevingranade** [comment]
I was thinking of an additional level of failure where you nick the CBM
casing and contaminants get into the mechanism itself, either irrevocably
contaminating it, or destroying the CBM mechanism itself.

By the way, when someone actually looks into the butchering code for this,
they can use a similar mechanism for producing 'contaminated meat' or
similar when butchering regular animals. IIUC a common cause of lost meat
when butchering is accidentally cutting open the digestive system,
contaminating a lot of the meat.

**Comment by BevapDin** [comment]
The unclean/clean/disinfected thing should be implemented as item property, not as item type property. There are currently about 88 CBM item types in the game, adding a clean and an unclean item type for each CBM triples that count, without any gain.

Reverting a disinfected CBM to clean ("rotting") can be done by making it active and adding a special `process_*` function to the item class, like it's already done for wet towels.

----

> How about every CBM taken from a corpse is labeled as "dirty X" and then you have to use disinfectant and clean water to make it "clean" and then use a vacuum sealer to make it a regular CBM?

I image a "real" CBM (fresh from the factory) has some package, tools and notes how to use (making it easy to install for everyone). Those things can not be generate with just a vacuum sealer. Also, the only time somebody would disinfect the item is when they are about to install it, otherwise the disinfected status would time out quickly and the whole action was for nothing.

Why not implicitly use the disinfecting item (whatever the character has available) when you try to install a clean (but not packed) CBM. Ask the player whether to "disinfect the CBM with ... before installing it" and if the player does not have any suitable disinfect, warn them. This can also take the quality of the disinfection into account.

**Comment by Soyweiser** [comment]
I myself was thinking of creating some sort of CBM installing system (the 10 volume thing surrounding the CBM) and have the butchered CBMs only contain the bionics. To make a working CBM you needed some sort of skill, bionics, a casing, disinfectant, painkillers. (As I also wanted the CBM to cause pain when installed, it autoinjects the painkillers).

This could work well with what you suggest. But would make it even more complicated.

So labs have working sterilezed complete CBMs, some bionics (perhaps also sterilized) and other CBM crafting materials around. And butchering Z's with CBMs gives the rotten, poisoned bionics without a casing.

(Casings would be reusable for various CBMs, being made out of high tech microprocessors and surgical equipment).

One bonus, disinfectants now have not much use late game. As you hardly get infected bites with good armor. And, you can make disinfectant: http://cdda.estilofusion.com/disinfectant/craft

**Comment by FunnyMan3595** [comment]
I thought about that, yeah.  The term "CBM" implies that it's more than just the bionic itself.  I'm all in favor of adding that as another complicating factor.

Could mean we can make bionics themselves less rare, since you need other components to make a CBM and be able to install it (mostly) safely.  I like the idea of giving the player several bionic modules, and only one installer kit, so they have to prioritize what they want to install now, instead of installing everything they can.

**Comment by SunshineDistillery** [comment]
As far as "CBM installing systems", would it be possible to make a portable version and a stationary version similar to a CVD machine or stem cell treatment? If an auto-doc like machine gave a bonus for installing damaged/advanced bionics, that would give the player a reason to dive labs.

**Comment by karlnp** [comment]
I would really like it if you had to convince NPCs to install them in you and balance the potential rewards with putting yourself at another's mercy.

**Comment by kevingranade** [comment]
A CBM installer deep in a lab would indeed be a nice reward, possibly with
sub-quests around repairing it.
If we add a portable CBM installer, that would most likely supplant the
concept of them installing themselves.  There'd still be room for there to
be multiple varieties of such though.

**Comment by railmonkey** [comment]
First, let me say that I really like this idea. On the other hand, I would think that if technology has advanced far enough to have viable portable bionics, then CBMs would be treated to be implicitly antimicrobial, specifically by using organosilanes. It's common sense and cost effective in the long run. (https://en.wikipedia.org/wiki/Antimicrobial_surface) That's not to say they shouldn't be at least cleaned off first. Just because the surface is antimicrobial shouldn't mean you can just install it, clinging zombie viscera and all. But if it's just that, it removes the need for there to be sealed CBMs. Dirty, clean, and that's it, with clean being no different from the current implementation.

**Comment by Cat09** [comment]
while that sounds really nice in theory, the real world is usually more complicated than that. even invisibly small bits of dirt and dust can contain many infectious agents that would be very bad to get inside a surgical wound, you absolutely need to sterilize an item - even an antimicrobial one - because of the inevitable particles removing bacteria, etc. from contact.
It would certainly help consierably though, to have such a coating. it would reduce the infection rates with and without sterilization procedures.
One also needs to sterilize the skin thoroughly prior to operation, although I would imagine some bionics could be installed laproscopically. any sterilization procedures success should depend on first aid and perception
a stat could potentially be added to items to reflect grime levels, and another (invisible stat) for infection levels

**Comment by pingpong2011** [comment]
On the subject of "installers", why not have them? A basic kit could be the normal CBM thing, it's just a tool required for using it, like you use the tool, an option is "install CBM", and you select from CBMs in your menu. Perhaps an "enhanced" kit could have an option to remove CBMs (if not increase install chance), and there could be a very rare tool, the one-time-use self-installing kit. 100% chance of installation, with possibly auto-infecting you if you use dirty CBMs or a chance of other nasty effects from imperfect CBMs.

Having classes could also vary the pain/skills used. Trying to install a module without a kit or only a basic might work for power modules, but it'd hurt like hell. There could be like 1 auto installer per lab (perhaps even a boss/challenge drop), and it otherwise doesn't hurt.

**Comment by Coolthulhu** [comment]
I don't like the idea of guaranteed installers. The survivor is often a mutant, possibly wounded, doesn't know all the procedures of installing metal stuff in own body and possibly doesn't even know where is the given bit supposed to go.

Instead I'd like to see it like this:
* Give NPCs the ability to assist in CBM installation - could be as abstract as NPCs helping with crafting
* Turn CBM installation into a long action that would cause a ton of pain and some damage during the installation
* Said pain would cause penalties to installation rolls of the player, but not the bonus granted by NPCs (because they aren't hurt)
* Installer would act just like another NPC, with high skills and really good stats

**Comment by pingpong2011** [comment]
Coolthulu, that's kinda the point of there being, at most, one per lab, at the bottom or after a challenge. Is there any loot from any of the other things, like ending a growth of Triffids, or getting through radioactive areas?

AFAIK NPCs installing CBMs was always a thing, or was always supposed to be a thing. Ever since early NPC builds they advertised that certain NPCs would have the ability to do it.

**Comment by kevingranade** [comment]
There is a NPC that will install CBMs for you, they arrive as part of the
hospital quest line in the farm area. It's still not guaranteed, but they
have decent skills and get a large bonus due to it not being a self surgery.
I think the separation of the installer and the installed module is a
totally reasonable thing to do.

**Comment by Man-animal** [comment]
The issue I have with "dirty" CBMs is that it seems like the sort of thing that would just further contribute to the mid/late game drudgery without actually making it more difficult.  If you can clean them, it's just a pointless set of time-wasting steps (my time, not my character's time).  If you can't, and if harvested CBMs can have unavoidable negative effects, then chances are players just won't risk using them.  You'd be better off searching for clean CBMs.

As it stands you need fairly high INT and skills just to reliably install all but the easiest CBMs; maybe it's just me, but by the time I even really start to think seriously about bionics, I'm already well-situated, so it's not like I'm shoving these things in my body out of desperation.

If corpse butchering is producing too many CBMs, why not just reduce the chances of successfully harvesting them?

**Comment by Coolthulhu** [comment]
> The issue I have with "dirty" CBMs is that it seems like the sort of thing that would just further contribute to the mid/late game drudgery without actually making it more difficult.

That's a valid point for temporary effects (infections) - those don't affect high-level players.
>  If you can't, and if harvested CBMs can have unavoidable negative effects, then chances are players just won't risk using them. You'd be better off searching for clean CBMs.

Depends on CBM. UPS bionic would be worth tanking squeaky ankles or self-locking thumbs for.
Early toolset could be a game changer. Nanobots with infinite energy mean infinite healing.
Later you could just get rid of the faulty bionic and go back to hunting a clean one.

This would do a lot to slow down the power stacking, which is one of the primary reasons of active bionics not just not being balanced, but not being balance-able.

**Comment by Man-animal** [comment]
How often are those scenarios actually relevant, though?  I've had what may have been game-saving lucky breaks like medieval armor/weapon spawns in mansions, or large ammo spawns in gun stores, but I've never been in a situation where a salvaged CBM changed everything.  Partially because of the high risk of failure at low skill levels (which also costs you the CBM), and partially because you have zero control over the CBMs you salvage (or the effects of a botched install).  Sure, you could luck into salvaging a power source, enough power storages, and the exact CBMs you need... or, far more likely, you could get a bunch of random junk you have no immediate use for, or wind up a crippled wreck.

By the time power stacking becomes a problem, the player is probably at the point where - bionics or not - they'll only die to a dumb mistake anyways.  If I have to travel more to find more CBMs because salvaged ones are no longer safe, then that's exactly what's going to happen: I'll just spend more time driving from lab to lab.

**Comment by Coolthulhu** [comment]
> I've never been in a situation where a salvaged CBM changed everything.

I had toolsets drop before any welder spawned. Sometimes before hacksaws or wrenches.
> Partially because of the high risk of failure at low skill levels

By introducing partial success (success + negative side effect) and giving it some of the probability roll, early good bionics could become a thing. Early meaning without a stack of strong stims.
> you have zero control over the CBMs you salvage

This one is a problem. Best early game CBMs only drop from bio-ops and become useless by the time player can install them. While bio-ops become harmless.
Could be improved by adding them (bio-ops) as a rare spawn, then giving them a buff (an evolution?).

**Comment by AppleConnoiseur** [comment]
Would really love this to make it into the game. Then i would not just install every power storage CBM i recover from butchered corpses :P.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.

**Comment by DracoGriffin** [comment]
Closed by #32013.
