### ISSUE TITLE
Long-term weather trends

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#1297]
System design by lumikant.

Generate weather by moving weather fronts. 8 types of weather fronts that interact with each other when they meet to create the in-game weather conditions. 

Warm - High Pressure - Dry
Warm - High Pressure - Wet
Warm - Low Pressure - Dry
Warm - Low Pressure - Wet
Cold - High Pressure - Dry
Cold - High Pressure - Wet
Cold - Low Pressure - Dry
Cold - Low Pressure - Wet

A front will last d4 days, after which a front is rolled on a d8. If the front remains the same on this random roll, the current weather continues with no change to the player. If it is a new front the local weather changes, a d4 is rolled to determine length, then randomization in the new pattern is done.

High pressure is generally fewer clouds and less inclimate weather. Low pressure makes for more precipitation and clouds. 

Wet fronts present a chance of rain for the entire front period. Dry fronts may start with rain, but will generally be zero to low chance of precipitation.

Cold fronts are low to average temperature. Warm fronts are average to warm temperatures. Multiple warm fronts will raise the temperature farther, where as multiple cold fronts will lower the temperature below the normal range.

Thunderstorms and severe weather are generally a function of a cold front displacing a warm air mass. This is true to a lesser extent for warm fronts displacing cool air masses.

Interaction example:

current: warm - high - dry | incoming: Cold - Low - Wet front

A line of heavy thunderstorms, followed by a short period of rain. First 6 hours a chance of thunderstorms or rain showers. Past six hours is a moderate chance of precipitation with cold to average temperatures.
##

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
