### ISSUE TITLE
Certain aggressive mobs AI bug

### ISSUE THREAD

**Issue by DodgingRain** [CleverRaven/Cataclysm-DDA#12972]
Some aggressive mobs will stop attacking you when down to moderately injured and dance around you while "tracking" (though will flee when they are heavily injured).  Currently I see this behavior displayed on the mi-go, wolf, and moose (not bear).
##

**Comment by drbig** [comment]
Ok so this seems like it was mentioned on IRC and there aren't any actual issues about it here (unless I've missed something, there are so many of'em...).

So I did encounter it too but assumed it was 'normal' with Mi-gos. AFAIR it's not as it's currently exhibited (e.g. moderately injured and 'dancing').

**Comment by karlnp** [comment]
When you're down to moderately injured or when the mob is? I had a migo smash apart half a shelter in an attempt to run away & get killed by a rain of canned tuna, but I figured we'd just got to it in time.

**Comment by drbig** [comment]
> When you're down to moderately injured or when the mob is?

The mob.

**Comment by i2amroy** [comment]
This is almost certainly just caused by the clunkiness of our "attitude" system as a whole. Right now there are very distinct thresholds that are almost (but not quite) impossible to trip that can result in going from "kill everyone" to "fleeing in a panic" or "dancing in circles around you" without any sort of gradual change between the two or way to revert.

**Comment by karlnp** [comment]
*adds it to the pile*

**Comment by Coolthulhu** [comment]
It works like this: when you hit a mob, it can get scared, angry or placated (less angry). "Tracking" is the state animal is in when it is scared and angry, but not too scared and not too angry.

We could probably get rid of the tracking state altogether. All it does is making animal act like angry from afar, but scared up close. It would make sense in "kiting" creatures with ranged attacks, but all of those are always angry at the moment.

**Comment by i2amroy** [comment]
Necromancers, masters, and fungal fighters all currently depend on the tracking system to keep them close to the player while not actively engaging them (fungal fighters only do it after slightly wounded). What we really need is a graduated system that ranks all of the way from "fleeing in terror" to "full yolo smackdown" to "circle the player shooting darts at them" and everything in between, all of which gradually can shift from one into another instead of just having flat cutoffs.

**Comment by Leland** [comment]
Not a bug – this is the current system. Feel free to open a PR as a suggestion regarding changing it, however.
