### ISSUE TITLE
DEBUG: the survivor zombie at (66,62,0) was not found in the tracker

### ISSUE THREAD

**Issue by dholmes215** [CleverRaven/Cataclysm-DDA#13011]
I entered a basement, turned on my flashlight, saw a bunch of zombies and survivor zombies, and went back up the stairs.  Now every step I get the message:

DEBUG: the survivor zombie at (66,62,0) was not found in the tracker

I'm playing a build based on 3723355.  I can upload the save, though it probably won't load without some json changes I have.

**Comment by Coolthulhu** [comment]
Not sure if save can help, because save+load tends to clear cache-related bugs.

Does the zombie position change each turn? Do you have z-levels (in options, not mods) on or off?

**Comment by dholmes215** [comment]
I had tried saving and loading to see if it would work and it seemed to the first time, but now it doesn't :|

I don't think the position changed, but I'm not 100% sure.  Z-levels are off.

**Comment by DanmakuDan** [comment]
I was able to generate a similar event, a zombie is bouncing around stunned adjacent to the top of a stairway, because the other zombies on the stairs are pushing it every turn. Some debugging indicated that critter.staircount was -39 (and decreasing by -4 each turn) for the zombies "located" on the stairs tile. It looks like the stair_monsters are not accounted for properly when more than one is trying to reach the top of the stairs. 
Most of them are located on the stairway in the same location but are invisible to the player. I have a save https://www.dropbox.com/s/fvmg84ghmlmut9c/save.zip?dl=0 where a zombie and a survivor zombie are waiting to climb the stairs. In some cases, this will trigger the debugmsg spam because they exist in the stair_monsters group but not in the ingame map that usually has the monsters. The occurrence of the bug is pretty random, since the positioning of monsters on the stairs/shoving location is randomized. You should be able to get a reaction from the attached save by going downstairs, and luring the zombies already nearby to the stairway and climbing back up.
