### ISSUE TITLE
Additive movement modifiers - Order of operations

### ISSUE THREAD

**Issue by aparent** [CleverRaven/Cataclysm-DDA#13068]
Why are these values added to move cost here?
Order of operations will affect the result, should they instead be added at the top where the other additive bonuses are taken care of?

This lines in question are here:

https://github.com/CleverRaven/Cataclysm-DDA/blob/446df8bc40f33b93ed247dcb81f5919ed03b8964/src/player.cpp#L1682
##

**Comment by Coolthulhu** [comment]
There doesn't seem to be a clear additive vs. multiplicative order. Possibly because the function didn't get a good code quality review in a while (it is quite ugly).
If we want a clear additive vs. multiplicative order, I'd rather change it to multiplicative before additive, because fleet of foot, padded feet etc. shouldn't help with broken legs or heavy shoes.

Looking at the function, I discovered an even bigger problem: 2D coordinates in player class, meaning NPCs on other z-levels have movecosts from the current one. This could result in them being unable to move (or teleporting, not sure which).

**Comment by drbig** [comment]
Hmm, this seems like something we would like to sort out at some point.

**Comment by kevingranade** [comment]
Very misc code quality issue, worth sorting out, but not worth pinning an issue open indefinitely.
