### ISSUE TITLE
Crashing on loading save, 0.C-3450 or 1cf3307 or whatever tiles and a few experimentals up to 3467

### ISSUE THREAD

**Issue by versusSA** [CleverRaven/Cataclysm-DDA#13070]
Save folder: http://puu.sh/jdIlv/e3fd945912.zip

I crashed while playing, and I have almost always crashed when I try to load the autosave. The one time I've managed to load into my autosave so far, I crashed when I hit @. 

I'm on Windows 8.1 64 bit.

**Comment by DanmakuDan** [comment]
You've got brainworms in your game save, and they are preventing you from loading your save without crashing. In the meantime, you could edit your .sav file in your save folder and remove the disease while it's in the process of being fixed. (The "brainworms" part followed by a set of brackets { }. )

**Comment by drbig** [comment]
Brainworms? Sounds like an awful... bug.

**Comment by drbig** [comment]
@DanmakuDan any idea what the source of it really is? Me going the other way around with `gdb` points to `effect::decay` not clamping `intensity` properly.

**Comment by DanmakuDan** [comment]
The code is setting the "brainworms" disease which is rarely obtained from eating raw meat. effects.json has it as "brainworm". When the game saves and the effect doesn't have a match in the effects.json, the effect_type value in the JSON save will be stored as "". The game will reload the effect_type as "", but that doesn't match with an effect, and the effect values will be uninitialized to some random value. The part where it crashes in effect::decay is because the intensity values aren't initialized, and the modified intensity is now probably a large negative value, which is being used as an index in an array. The reason that it might not crash when loading is because the uninitialized integers might occasionally be small enough that the out of bounds index might not crash the program. I was still working out a better check for the problem, since "" might be recognized as an effect type, but is not valid for something like decay. The main part of the fix is just making sure "brainworms" is used consistently in the code and json. This has probably been breaking saves for a while, since it's pretty rare that people would get brainworms from eating raw meat.

**Comment by BevapDin** [comment]
@versusSA your save will still not load properly because the real effect id was not stored at the expected place. You may edit the file "save/Hohenwald/#dmVyc3Vz.sav" (use some text-editor), change line 1210 from `"eff_type" : "",` to `"eff_type" : "brainworms",` (insert the word `brainworms`) to make it work.

**Comment by drbig** [comment]
Fixed.

@versusSA you can try the save you shared with 3499 build (0.C-4954-g835283a) or newer and it should just work™ (don't mind the mild debug spam on save load).
