### ISSUE TITLE
Big slowdown shortly after game load (overmap loading)

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#13077]
When the save loads, only local overmap tiles are accessed. Shortly after that, something processes all of them (horde movement?), causing a big lag spike.

It seems that "touching" all the tiles during game load (or just before displaying the game screen to the player) would help with usability.

During normal gameplay it isn't too bad (still, it is alarming because the spike is big; looks like crash), it's much worse during debugging due to required constant restarts and the giant extra cost debugger places on json loading.
##

**Comment by DanmakuDan** [comment]
The game save seems to be loading slower on the Windows Tiles builds since the save updated to the JSON format. Since I have hordes off, loading the map screen is what triggers loading the rest of the overmap for me.

**Comment by Coolthulhu** [comment]
This lag spike occurs even without hordes enabled. I'm guessing it's hordes because those might affect the entire overmap, but it happens in horde-less worlds just the same.

**Comment by kevingranade** [comment]
Some mission related stuff does overmap scans as well.

**Comment by Nandorianen** [comment]
The game in general becomes slower and slower for me after 0.A. I return every few months to check what's new and it's very noticeable.
Using 0.C-37** and 0.C-38** it's especially clear. Now I got big lags very frequently.
Haven't changed any hardware or OS since 0.A.

Examples.
1. After loading save and opening a map (once).
2. After loading save and trying to drive (once on the first turn the vehicle actually moves).
3. When moving around I often get 3-5 seconds of lag. It seems that weather change or overmaps are the case.
4. When something explodes. Zombies stepping on land mines = wait 5 seconds. Failing to disarm land mine = wait 5 seconds.
5. When getting my ass kicked hard in one turn (multiple damaging attacks, damaged clothes). Especially if I die after that. I suspect this is connected with the one above.

Using windows-32 version. Tried curses and tiles (without actual tiles). Tried software and hardware rendering, turning animation options on and off.
Playing with hordes and Z-levels off.

**Comment by Nandorianen** [comment]
It seems these random lag spikes are related at least partially to NPC placement. I am playing with NPCs on (both static and dynamic), with 1.0 spawning rate. After such random lag spikes I noticed newly generated NPCs few tiles away from me.

**Comment by kevingranade** [comment]
FYI, if you report a slowdown in this issue and we address the originally
reported issue, we will close this issue and most likely never look at what
you reported again.

**Comment by Nandorianen** [comment]
This one doesn't look closed. I am confused. Should I make a new issue?

**Comment by Zireael07** [comment]
@Nandorianen: I guess so. The original issue is related to submap loading, yours seems to be NPC spawning.

**Comment by DanmakuDan** [comment]
This is still an issue, as overmap scans for random NPC mission assignment can cause a large period of freezing (5-10 seconds on a decent computer) since the game is processing the overmap loading.

**Comment by Night-Pryanik** [comment]
Is this still an issue? I don't see any noticeable lag after the game load.

**Comment by GGgatherer** [comment]
I only see a slight lag - approx 3-5 seconds - when first opening overmap after loading, but after that even crossing OM section borders does not result in any noticeable lag.

**Comment by Night-Pryanik** [comment]
I suppose as this is a very old issue and as we've done many performance tweaks from that time, this issue is safe to close.
