### ISSUE TITLE
Ouch! Something hurts! Or: unnecessary interference to actions from (negligible) pain.

### ISSUE THREAD

**Issue by Barhandar** [CleverRaven/Cataclysm-DDA#13084]
**Any** pain (starting at irrelevant itching) is sufficient to cause this _prompt_ to appear, pausing the dropping/reading. And it's not nor can be made ignorable, because ignore only persists for a single action of dropping, not for the whole queue (as proven by noises).

I don't understand why was this prompt added in the first place. Sources of pain either prompt separately (enemy approaching, for example), or are known beforehand (damage, weight limit, etc). For me, it adds nothing but interference and requirement to hold (Shift+) N while doing action-queues like dropping and reading. Or being opiate junkie, I guess.
##

**Comment by drbig** [comment]
Yeah, the pesky interrupts pop-up frequently. This one just adds more... pain.

**Comment by i2amroy** [comment]
Are you running the latest experimental? The pain v sleep thing that was merged just a day or two back should have raised the threshold for action prompting from 1 pain up to 2, thus stopping the vast majority of things that would cause this to prompt.

**Comment by Barhandar** [comment]
>Are you running the latest experimental?

It seems to not prompt with just pain/torso damage anymore. I need a debug "give a disease" thing though because, say, a flu was pretty reliable way to cause the prompt.

In either case, while the problem might be fixed, complaint about interference doesn't become invalid. _Why_ does this particular prompt even exist? Please do elaborate on the reason, because currently I believe it is "to annoy players through pausing the game for superfluous information".

**Comment by Coolthulhu** [comment]
> I need a debug "give a disease" thing

This can be done with Lua command from debug menu. Requires learning a bit of Lua syntax, but only the most basic stuff.

> Why does this particular prompt even exist?

Probably a bit of paranoia here, like with weather change prompt, except less nonsensical - stacked pain, especially coupled with extreme cold/heat, can be dangerous if anything sneaks up or even just when it extends the action a lot due to low speed.

I'd say it should get the same treatment as noise interruptions: ask once, but allow the player to just say "don't interrupt me for pain without damage until I finish this action". Though that might require a rework of how action interruptions work, because as far as I recall, noise interruptions are hardcoded rather than just being a separate kind of interruptions.

**Comment by i2amroy** [comment]
I believe a big part of the early reason was because it was implemented back in the days of acid rain, which caused pain without any real damage, and was before the "the weather changed" prompt ever existed. The result was that without something prompting you to stop acid rain could come down and end up pushing your pain up to like 100 without you ever getting a chance to say "stop".

**Comment by Leland** [comment]
Hasn't been active discussion on this one in over two years - closing. Feel free to let me know if want this reopened.
