### ISSUE TITLE
Alarm-clock fails to wake you up most of the time

### ISSUE THREAD

**Issue by HeadWar** [CleverRaven/Cataclysm-DDA#13094]
I've been playing for a bit in 0.C-3376, and only once has an alarm-clock managed to wake me up like it should, and that was in a brightly lit room, and less than an hour before I would normally have woken up anyway. That time there was a message of "Beep-beep" and "You are woken by a noise." or something similar.

Every other time, I've woken up by myself, and can see a message "You turn off your alarm-clock." some time (the correct one, as far as I can tell) during the night.

While I personally (IRL) have been known to turn off an alarm-clock and go back to sleep on a few occasions, this level is a bit silly, and also makes the function rather pointless if you want to use it for waking up for a night raid or just setting your day-night-cycle to something reasonable while living in a cave.

**Comment by drbig** [comment]
Did your character had any traits that might be of influence here? (heavy sleeper, poor hearing comes to mind, probably more).

**Comment by DavidKeaton** [comment]
Heavy sleeper def makes you sleep through them lol.

**Comment by HeadWar** [comment]
Unless there is a hidden stat for poor hearing (I've fired a few rounds here and there without hearing protection), no, hearing should be fine, and no sleep disorders. Nothing that shows up in the traits list at least.

**Comment by DavidKeaton** [comment]
hmmm

**Comment by drbig** [comment]
"Confirmation Needed". Things that depend on the `rng()` are inherently difficult to tell whether it's "just statistics" or an actual bug.

**Comment by i2amroy** [comment]
Looking into this for a non-heavy sleeper the current chance of waking up is only ~25%, meaning 75% of the time they will go on to at least one snooze 10 minutes snooze. Here's the approximate chances for waking up on a given snooze:

num of snoozes (10 min each) - Cumulative chance to have woken by a given number of snoozes
0 - 24.4%
1 - 42.9%
2 - 56.9%
3 - 67.4%
4 - 75.4%
5 - 81.4%
6 - 85.9%

I'd say that yeah, that's probably a little extreme, since I'd say I have a bit better chance to wake up from my alarm going off than 24.4%. Here's the same statistics if we raise the volume of the alarm clock up to 16:

0 - 46.7%
1 - 71.6%
2 - 84.8%
3 - 91.9%
4 - 95.7%
5 - 97.7%
6 - 98.8%

That would give us a near guaranteed chance to wake in the first hour, with a very good chance of waking either right away or after only a single snooze, which I feel is fairly realistic (though if we wanted to be really realistic we would factor remaining tiredness into the equation instead of just a flat 2d15 < X).

Therefore fast solution: Change the volume for the "alarm_clock" sound in player::hardcoded_effects() from 12 up to 16.

**Comment by drbig** [comment]
> Therefore fast solution: Change the volume for the "alarm_clock" sound in player::hardcoded_effects() from 12 up to 16.

Sounds sane to me. After all it's not cosy Saturday-maybe-wake-up-or-not environment.

**Comment by HeadWar** [comment]
Wait, does it actually do those six snoozes already? Because those numbers aren't anywhere near what I have seen, though admittedly that could just be the RNG messing with me, after the one successful attempt I had I thought that remaining tiredness factored into it, so I started to set it to a time only a little before when I would have woken up anyway.
