### ISSUE TITLE
Advanced Inventory Menu simplification

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#13090]
* Make it so that the left panel is always the source and the right one the destination
* Drop filters on panel swap

Having "floating" source/destination panels can be confusing and I don't think it serves any role. Having it always go from left to right would simplify both usage and possibly the code.

Panel swap preserving filters can be annoying. It makes the menu behave differently when selecting the same area than when selecting a new one.
Alternatively, there could be a dedicated swap key that would preserve filters, with the default swap not doing so.

**Comment by DavidKeaton** [comment]
I always use right for inventory, whether it be source or destination.

**Comment by narc0tiq** [comment]
Likewise, I use the left and right panes as source and destination
interchangeably. The source is the currently selected pane (which is
helpfully highlighted -- maybe the highlight isn't sufficiently visible?).
The destination is the other one. This seems very simple to me, but maybe
I've just been using Norton Commander-alikes for too many years.

I'm not sure what operation the phrase "panel swap" implies -- just
changing the location displayed in an AIM pane? Swapping the left and right
pane? If the latter (which seems reasonable), there isn't a single key that
performs the operation.

For my own play-throughs of Cata, it would be helpful if the AIM filters
were utterly ephemeral -- going away as soon as I've changed the location
displayed, or even just closed AIM (clearing the filter is a two-key
operation I have to remember to do: /, [Esc]). I can't assume my use cases
are the only ones, though -- someone who had more storage tiles than can
fit in a 3x3 area would prefer to keep the filter between glances at AIM in
search of that elusive bottle of acid.

**Comment by Barhandar** [comment]
I agree with the other two comments - I'm using one side for inventory regardless of it being source or destination. Having them flip all the time would _increase_ the confusion, not decrease it.

**Comment by Coolthulhu** [comment]
OK then, so no panel change.

What about the filter part?
Having automatic swapping preserve filters leads to the case where pressing a direction key sends the filters from the source to the destination (or from the destination to source).
I can't really think of a case where this would be useful and it is quite annoying, as it makes direction keys function differently if the selected direction happens to be the one on the other pane.

**Comment by narc0tiq** [comment]
I just had to test this to figure out what the current behaviour is (which should tell you how much impact changing it would have on me). As far as I can tell, the filter is being illogical -- sometimes it's tied to the left or right pane (as happens when you just change the location targeted by the current pane, without causing a swap), whereas other times it's tied to the location (as happens when you do cause a swap to happen).

There are three possible behaviours I can think of:
1. The filter is tied to the left or right pane, period. If the panes swap, assume this was intentional, and **do not** make the filter follow the swap.
2. The filter is tied to the location, period. If the location in the pane changes, retrieve the last filter that location had and set that. If the panes swap, the filter follows the swap.
3. The most drastic approach: the filter is ephemeral and resets automatically whenever the location changes.


I believe option 1 was the original implementation of AIM filters, and it makes the most sense -- you use a filter to find things in the current pane, changing the pane's location or closing AIM and moving your character in the world to change what tiles you're searching.

Option 2 is not entirely sane because the meaning of a location (e.g., north) can and will change between AIM sessions, as the player character walks around. Further, we do **not** want the filter to be attached to coordinates in the world -- that's a lot of metadata to keep for something that almost certainly doesn't match players' expectations.

Option 3 might work best as a slightly weaker version: the filter resets when it's no longer on the selected pane. Normally, if you're filtering a pane, it's the active pane, and you're using the filter to find specific items so that you can move them to the other pane. It would make sense to reset the filter when you switch focus to the other pane -- both because it should no longer be needed, but also because filtering will give you the wrong idea of how full the target location is.

**Comment by DavidKeaton** [comment]
The highlight should be more obvious with the darkening of the destination pane. I can illustrate it more if needed.

**Comment by DavidKeaton** [comment]
I'd also prefer to keep the plane's filter, and agree with narc that 1 is the most sane.

**Comment by narc0tiq** [comment]
I'd honestly prefer if the filter reset whenever the pane being filtered is no longer the active one, but I'm not sure how that would affect people's play style. For that matter, we have the option of having a single filter that follows the active pane -- you'd have to hit [r]eset when you were done, but otherwise it would apply only to your source.

**Comment by DavidKeaton** [comment]
perhaps we could have both options present?

**Comment by narc0tiq** [comment]
I'm not sure it's worth the extra complexity. A filter for each pane seems like the best way to go about it.
