### ISSUE TITLE
Pharmacies predominantly spawn snacks

### ISSUE THREAD

**Issue by Barhandar** [CleverRaven/Cataclysm-DDA#13104]
I don't know about USA, but real European pharmacies predominantly have drugs and medicine-related things like hand sanitizers, vitamins, and the like. They don't have any regular snacks - the only kinds of snacks they've got, maybe 5% of overall shelves, are sugar-free and vitamin-fortified ones for diabetics and kids.

Which is reversed in the game: there are 11 shelves that can _occasionally_ spawn medicine, and **32** shelves, plus 7 refrigerators, that can spawn mostly snacks with occasional dayquil/nyquil.
##

**Comment by vache** [comment]
Well.  An average pharmacy here, like a Walgreens or a CVS, would have about 3 aisles and a set of fridges/freezers for groceries, one aisle for snacks, 4 aisles for OTC medicine, one aisle for supplies for things for chronic conditions (like diabetes), one aisle for like mobility issues (canes, walkers, etc), half an aisle for toys, an aisle for feminine products and condoms and whatnot, 2-3 aisles for beauty supplies and perfume, and usually one aisle for seasonal items.  If you exclude the back pharmacy area, the OTC medicine and medical supplies are really only like... 20% of the entire store.

**Comment by Barhandar** [comment]
Which is still more medicine and medicine-related things (chronic medicine, mobility issues, and sex-related stuff are such) than groceries and snacks.

**Comment by Headjack** [comment]
Pharmacies should probably more often have a secure backroom with extra drugs and whatnot. Hitting pharmacies is usually not much better than a few houses when you need a first aid kit or some pills.

**Comment by Barhandar** [comment]
>Hitting pharmacies is usually not much better than a few houses when you need a first aid kit or some pills.

In my experience, it's better to hit _grocery stores_ than pharmacies. Grocery stores often have much more medicine.

**Comment by Sacrez** [comment]
Well indeed, where I am from for example pharmacies are packed full of medicine and drugs with virtually no snacks and while things may be different in US it doesn't impact the fact that either way, the highly valuable medicine such as med kits, strong painkillers or antibiotics would be looted most of the time while object of lesser interest will have not. Think of it this way, you don't go to the pharmacy to eat, you go there to get medicine so that's the thing you'll be getting first and foremost. So shelves ought to be fairly clear of that but still have some snacks. I haven't visited any pharmacy in game for a while but I do support SOME of them having a locked backdoor made of metal perhaps with a few more drugs. I'd imagine if it was made of wood people would kick it down regardless.

**Comment by ArikVhedrovix** [comment]
Most mid sized grocery stores where I live in the US seem to have an actual pharmacy in a corner of the store, with a metal door on the side and those retractable, flexible metal gates over the counter area. I think most pharmacies would be locked up with the gates down if the power hadn't gone out beforehand. If I were a pharmacist and I saw people start to violently riot (as they turned) I would drop that gate straight away for my own safety.

**Comment by Barhandar** [comment]
>So shelves ought to be fairly clear of that but still have some snacks.

To pretend it's been looted it needs more broken windows, damaged shelves, and acid-rain-melted corpses outside. Until that's done, I cannot suspend my disbelief enough to have groceries (which are also prime looting targets) have more medicine than pharmacies.

**Comment by Headjack** [comment]
If we ever have building state variations that would make sense, to increase the likelihood of it being trashed. At this point it's just an imbalance in the expected loot. It should probably be akin to those rooms in hospitals with medicine.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
