### ISSUE TITLE
Quality of Life: allow sickle/scythe to harvest and collect farmplants on player's tile

### ISSUE THREAD

**Issue by Barhandar** [CleverRaven/Cataclysm-DDA#13117]
Like hoe makes mounds under you, but harvesting and collecting plants instead.

Maybe, if it's even doable, have it's 'a' work as now, regular cutting-tool menu, but 'A' ("activate wielded item") harvest without any prompts and tell you "nothing to harvest" if you're not over a ripe plant - so it doesn't have to lose its regular abilities and yet works without prompts when necessary.
##

**Comment by drbig** [comment]
I would very much like to see a scythe/sickle to (long-action) harvest from all tiles around the player (including the one the player is standing on, so a 3x3 square). This could make farming far less tedious.

I would even argue for it/them to work on plants that one would just pick - it's a game after all.

**Comment by Barhandar** [comment]
Sickle can do one tile and auto-collect items straight to inventory while scythe does 3x3 and leaves items on the ground, so the ways of harvest aren't mutually exclusive.

**Comment by drbig** [comment]
> Sickle can do one tile and auto-collect items straight to inventory while scythe does 3x3 and leaves items on the ground, so the ways of harvest aren't mutually exclusive.

I like that. I'm of general opinion that making farming more of a thing would be a nice addition. Having actual tool rack that is useful would be a great first step.

**Comment by Headjack** [comment]
Harvest Moon enhancements are ++. I'd really like to see cow milking though, we tried to work out a way in IRC last night to no avail; the cows only give bruises. I want to make cheeeese.

**Comment by Barhandar** [comment]
> I'd really like to see cow milking though, we tried to work out a way in IRC last night to no avail; the cows only give bruises.

Cows require to have offspring before they'll be milkable, so making them so requires either gross simplification (a-la Minecraft) or implementing animal husbandry nearly whole, with feeding (and hay collection for winter - it helps if scythe can do the harvest!) and breeding and general care. Opens up another way to make fertilizer, too, if Kevin is not as against manure as he is against other excrement.


>Also, it would be really helpful if there were a way to cultivate yeast from scratch.

The problem is that commercial yeast is pure-strain, all natural yeasts are a mix and would have different results.

Yeasts are collectable from grapes, plums, and other fruit/berries that have a whitish film on them when ripe. Medieval beer, and afterwards bread, -making pretty much hinged on the success of winemakers to get started out, then they could multiply their own stock.

Also, current process to multiply yeast is annoying as all hell. Why can't I breed them in a 3l jar so that I wait a week and then come back to over a hundred yeast instead of paltry 10?

**Comment by Rivet-the-Zombie** [comment]
>if Kevin is not as against manure as he is against other excrement

It's not just him; it's the rest of us too.

**Comment by Barhandar** [comment]
>It's not just him; it's the rest of us too.

I remember Kevin as author of suggestions FAQ post on the forums, so...

**Comment by kevingranade** [comment]
And yea, manure is fine, it's just having the player manage defecation
that's pointless.

**Comment by Barhandar** [comment]
In the same vein, if vehicles could interact with/modify terrain, this would allow plows (drag/move, they form a trail of dirt mounds), and mechanized seeders/fertilizers/harvesters.

And traplayers. And road removers/placers. Really, vehicles generically interacting with terrain opens up a lot of prospects.

**Comment by ArikVhedrovix** [comment]
I would hate having to manage player bathroom stuff. On the other hand, if some (living) monsters left scat near their lairs, it could be a really good warning sign. Probably not worth it for it's own sake, but if cows pioneer the way for the sake of farming, maybe other creatures could reuse similar code.

**Comment by Barhandar** [comment]
>maybe other creatures could reuse similar code

And this is why I'd rather not implement it at all.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
