### ISSUE TITLE
Item dropping bug then items disappearing

### ISSUE THREAD

**Issue by pingpong2011** [CleverRaven/Cataclysm-DDA#13126]
windows experimental graphical version 0a526bf

I was in a mansion (everything otherwise going fine) and I dropped some stuff before fighting a zombie. I don't think the items I tried to 'D'rop included my lighter, a lit cigarette, and one butt. The following inventory message appeared on my screen, and the game continued after:

20:23:15.576 : src/inventory.cpp:47 Attempted to access stack 7 in an inventory (size 7)

I picked the items back up, continued on my way, but it appears my lighter vaporized after a few turns. It's not in my inventory, and it's nowhere on the ground around me. A pretty painful bug as a smoker. There should not have been any mods active, and "Harbor" was the name of the world.

**Comment by Coolthulhu** [comment]
Did you lose carrying capacity during dropping? For example, dropping a backpack.

Inventory overflow can happen after you drop a worn item container.

It seems that drop function uses inventory indices rather than something that would identify them uniquely. When inventory capacity changes mid-drop, the indices become scrambled.

Dropping functions will probably have to be rewritten...

**Comment by pingpong2011** [comment]
Oh, that would easily explain it, as I was quite literally dropping my worn backpack and a bunch of items to fight less encumbered. I swore I normally could drop backpacks and items at the same time, and never had the issue before. I assume it would be a huge issue with melee chars too? Is it recent?

**Comment by Coolthulhu** [comment]
Quite recent - got in with the inventory overflow.

If you want to stay on the safe side, don't drop inventory and containers in the same multidrop. You can safely drop the backpack, which will cause some of the items to fall out of the inventory in the next turn, you can safely drop two worn backpacks, you can safely drop lighter and cigs, but dropping worn backpack and lighter in the same drop can cause the bug.

Having less capacity than you carry will drop random items (preferring the biggest ones), so the old issue of losing backpack and having to manually drop 30 items while attacked and having 30 encumbrance on all body is no longer here.

**Comment by drbig** [comment]
Seems to me that using pointers to actual items would solve/help more than one problem.

As for this bug here I assume replicability is going to be 'statistical' at best.

**Comment by kevingranade** [comment]
If coolthulu's speculation about the problem is correct, it should just be
a matter of filling up your inventory to capacity and then dropping a
container and a bunch of other items in the same action.

Since it's a long action, it's hard to store pointers to items, which is
why we're doing the index thing in the first place.  If you want to switch
to using pointers, you'll need to adjust the save/load code for long
actions to convert pointers to items to some serializable reference (like
an offset into an array), and convert them back on load.
A simpler fix would be to suppress autodrop from being overloaded if
dropping items is in progress.
