### ISSUE TITLE
is it possible to make a friendly monster command menu?(and also about mounts)

### ISSUE THREAD

**Issue by vipches** [CleverRaven/Cataclysm-DDA#13198]
I know this game have a friendly monster which it will helping you attack enemy, but I think mabye some one can improve this friendly monster system, change the "Chat with NPC" to "Chat with something" so will you have friendly monster nearby you may command them to stay or ignore the enemy and keep distance? also, is any one is planing to make a mounts? so you can tame a big monster so they will carry you and items traveling with you? I saw KKND doing this and doing just fine, but first we need to have a multi tiles monster first, and the last thing is, can we just have some item that can scatter a gas or smoke? so we can take care that toxic gas from mine shaft, this will not stop toxic gas spread, but at least it wont block player's vision, explore into a toxic gas could be painful, gas mask or not.

**Comment by BevapDin** [comment]
There is one menu like that, it is shown when you character is adjacent to a friendly monster with the "pet" effect and you `e`xamine the square of the monster.

The "pet" effect can be gained with dog food and by making a zombie slave. The menu is not shown for monster without the effect.

**Comment by vipches** [comment]
But what about others? what about the dermatik larva that hatch on the player body? what about the insects that spawn by artifacts? what about reprogram robot?

**Comment by illi-kun** [comment]
A couple notes:
- Forum is better place for feature requests (especially, requests described in such general manner).
- Merging a bunch of requests about absolutely unrelated things in one issue is also not good, since we need to implement _all of your requests_ from that issue for closing it.
Sorry for saying that.

BTW, I'm not sure how it works in the game but maybe IR-devices allow to scan thru the smoke? (it should be if we're not talking about heated gases or special smoke used for IR-masking).

**Comment by kevingranade** [comment]
Please restrict issues to one topic each as Illi-kun says, and make them specific, this issue can't be addressed per se, so I'm closing it.
