### ISSUE TITLE
Gunpowder recipe broken

### ISSUE THREAD

**Issue by CallidusD** [CleverRaven/Cataclysm-DDA#13270]
The recipe for modern gunpowder for use with reloaded ammunition currently requires medieval weaponsmith skillbook and inappropriate materials.

**Comment by sztosz** [comment]
There should be no steel or leather used. 
Gunpowder is made of saltpeter, charcoal, and sulfur. 

We have saltpeter, charcoal and sulfur in game already, and those should be ingredients. About 7 pieces of of saltpeter, 2 of charcoal, and 1 of sulfur are the somewhat correct proportions. You also don't need no anvil or forge, all you need is mortar and pestle. 

Since we don't have mortar and pestle in game we can consider adding it as an item, or use copper pot (steel, or iron is inadvisable due to the sparking effect that can occur) and stone or some tool to use as grinder.

**Comment by CallidusD** [comment]
Check the recipe again. http://cdda-trunk.estilofusion.com/gunpowder/craft
shows the current indev version as having an issue. From what I understand
this site pulls from the gamefiles, so there could be an issue here.

**Comment by kevingranade** [comment]
That's an issue for the website, the game doesn't even have a recipe for modern gunpowder anymore.
Please check the json before filing issues.

**Comment by CallidusD** [comment]
My bad. I thought the website was pulling from jsons since that is how I
would do it : P

Ill check on my end next time instead of a third party.

**Comment by sztosz** [comment]
Nevertheless we could still add a proper modern gunpowder recipe ;)
