### ISSUE TITLE
Cygwin x86: new threads constantly being created

### ISSUE THREAD

**Issue by Griffinhart** [CleverRaven/Cataclysm-DDA#13300]
Version: 0.C-5399-g84abdc1

1. Start CDDA.
2. Wait a few seconds (~30s). Or do something, I don't actually think it matters.
3. A new thread starts (message will appear to the effect of `[New Thread 12792.0x2a94]`
4. UI no longer responds, inputs appear as character literals written on screen (e.g. trying to navigate a menu with `j` or `k` will write "j" or "k" to the screen).
5. Game still running and you can still do stuff, it's just entirely unplayable. (As far as I can tell, at this point the game only processes one input at a time, and you have to follow each input with `Enter`. Then again, I've been stuck navigating around the Options menu so far, so I can't tell what the behavior is beyond the Options menu.)
6. Eventually, another new thread message will pop up.

gdb output after I managed to quit the game cleanly (having invoked this bug on the game start screen):

```
$ ./run
GNU gdb (GDB) 7.8
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "i686-pc-cygwin".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from cataclysm...done.
Starting program: /cygdrive/d/Development/git-repositories/Cataclysm-DDA/cataclysm
[New Thread 12792.0x2a94]
[New Thread 12792.0x54dc]
[New Thread 12792.0x2a1c]
[New Thread 12792.0x3934]
[Thread 12792.0x12d8 exited with code 0]
[Thread 12792.0x3934 exited with code 0]
[Thread 12792.0x4e78 exited with code 0]
[Thread 12792.0x54dc exited with code 0]
[Thread 12792.0x2a1c exited with code 0]
[Inferior 1 (process 12792) exited normally]
```

**Comment by BevapDin** [comment]
New threads are started from the sound effects system, but that should only happen if you have compiled it with `SOUND=1`, which implies `TILES=1`, which implies you're not playing in the console. So just to make sure: how did you compile it? And you forgot to mention the version.

**Comment by Griffinhart** [comment]
```
git pull
make clean
make
```

ncurses build on Cygwin x86, running inside a mintty terminal. Version: 0.C-5399-g84abdc1 (I'll edit that into the original bug report as well).

**Comment by BevapDin** [comment]
> I'm assuming this is because SOUND=0 TILES=0 still defines those variables, they just happen to have the value 0, and the makefile checks to see if the variables were defined, not if their values are 1.

Yes, being defined is all that's needed, the value can be anything. Btw. the variables are also inherited through environment variables from the system. But as you obviously don't have a suitable SDL2 version install, the working build definitively doesn't use it, so the threads don't originate from there.

**Comment by Griffinhart** [comment]
Hrm. This might be a client-side issue, actually. I'm no longer getting repeated "New Thread" messages after recompiling.

Thing is, previous recompiles didn't fix this error, and I didn't do anything different this time either...

**Comment by mugling** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
