### ISSUE TITLE
Petrified eye mine finale not properly triggering

### ISSUE THREAD

**Issue by Rainboww** [CleverRaven/Cataclysm-DDA#13310]
Windows, tiles, Latest experimental (3577), the petrified eye mine finale doesn't "trigger" (summon wyrms, tremors, screaming) until you examine the pedestal a second time after succesfully removing the eye, making it trivial to leave the mine with it as long as you don't go out of your way to trigger it.
##

**Comment by int-ua** [comment]
Is that finale still in the game? I've just teleported to about a dozen of mines and all of them were spiral caverns. Maybe that's another issue.

**Comment by anothersimulacrum** [comment]
Spiral caverns seem to always spawn under mines, no matter if they are accesible or not. Are you teleporting to the final `M` room, or to the spiral caverns and not looking up?

**Comment by int-ua** [comment]
Still relevant on build 11388.

**Comment by actual-nh** [comment]
Ping: @Night-Pryanik?

**Comment by Night-Pryanik** [comment]
The bug occurs because of the following.

1. Game spawns "wyrms" mine finale room.
2. Game spawns a pedestal in the center of that room.
3. Game places petrified eye on the pedestal.
4. Player examines the pedestal. Code says that iexamine function should do nothing if there's any item on the pedestal:

```
if( !here.i_at( examp ).empty() ) {
    none( p, examp );
    return;
}
```

This includes petrified eye! So nothing happens at all.
5.Player safely takes the eye from the pedestal.
6. Player examines pedestal once again. There's no items on it, so "wyrms" event triggers.

Also player could completely bypass the whole event by using `g` to get the eye from the pedestal (or use AIM) rather than examine it because event triggers only on examining. To this fix the bug we somehow need to forbid player from taking off petrified eye by any means except by examining it. 

To fix the bug in the OP we probably need to remove the check for emptiness of the pedestal or rework it somehow so it should behave properly.
