### ISSUE TITLE
Lab - turret doors blue in curses- but not in tiles-version

### ISSUE THREAD

**Issue by tsaber** [CleverRaven/Cataclysm-DDA#13356]
In the lab it is very easy to dodge the turret rooms in the ncurses version because their doors are in cyan and you see the range radius. 
In the tiles version you "only" see the adjacent walls outside your nightvision.
##

**Comment by kevingranade** [comment]
The bug is on the curses side, the light shouldn't be visible through a
door.

**Comment by drbig** [comment]
So do I understand it correctly: in curses the lighting code changes ("highlights") the doors in the lab due to the light coming from the turrets?

**Comment by kevingranade** [comment]
Also, the bug is more visible in curses, but in tiles if you disable any
light and nightvision you have (and stand more than a square away from it),
the door will only be visible because it's illuminated from the other side.
The underlying problem is that the lighting and vision code is
direction-agnostic, a given tile is either illuminated or it isn't, so if a
wall is illuminated, it's visible from all directions.  I have a few
brute-force workarounds in mind, but I'm not sure they won't cause even
more lighting artifacts, and they're bound to slow down the dynamic
lighting code.

**Comment by drbig** [comment]
I see. Yeah that makes sense all around.
