### ISSUE TITLE
Need treetaps

### ISSUE THREAD

**Issue by Zaweri** [CleverRaven/Cataclysm-DDA#13363]
So, I can't get the funnel code to work to make a treetap, so I ask for you guys to make the treetap. It should take oak sap from the good ol default tree, birch sap from birch, pine sap from pines and maple sap from maple trees.

**Comment by drbig** [comment]
I assume the idea is that you 'attach' a treesap plus put some container under it and it should collect sap over time? (i.e. not be an immediate action)

**Comment by Rivet-the-Zombie** [comment]
>I assume the idea is that you 'attach' a treesap plus put some container under it and it should collect sap over time? (i.e. not be an immediate action)

Yeah the sap just sort of leaks out slowly:

![tap](https://cloud.githubusercontent.com/assets/5084581/9415688/a268083a-4806-11e5-98ca-4bf8ab0ddeea.png)

Also, tree-tapping output would have to be affected by season, as it is in real life.

**Comment by drbig** [comment]
Aye. No sap during winter for sure (and probably most of spring too).

Unless I've missed some decent code changes the tree-tap (that wording also makes more sense to me) would work exactly like a funnel - a trap code-wise for the purpose of it updating its state (time passed since application) for the purpose of calculating the amount of sap extracted.

**Comment by Coolthulhu** [comment]
Funnel-like yeah, but actually a fair bit simpler, because you don't need to analyze weather and thus don't need to make it a trap.

One thing that may be harder is placement: trees have the no-item flag, which means that placing stuff on them isn't as straightforward as just dropping stuff - it has to be done more "explicitly".
This creates an issue: how do we attach container to the tap? It could be done with the same examine function and that's probably the best way to solve it. This would restrict it to 1 tap + 1 container per tree, but it makes sense.

**Comment by drbig** [comment]
@Coolthulhu: Have the funnel at an tree-adjacent tile and valid containers are all the containers on the same tile as the tree-tap (so it mimics funnel in that regard). And I'll be all for it not needing to be a trap (I assume on reality-bubble-entry code will suffice).

**Comment by Coolthulhu** [comment]
> Have the funnel at an tree-adjacent tile

But that would prevent different sap types, unless it was hacked around somehow. Imagine a "ring" of trees with a tap in the middle. Which tree is tapped?

> valid containers are all the containers on the same tile as the tree-tap (so it mimics funnel in that regard)

Funnel takes only the biggest valid container, not all of them.

**Comment by drbig** [comment]
> But that would prevent different sap types, unless it was hacked around somehow. Imagine a "ring" of trees with a tap in the middle. Which tree is tapped?

Aye. Need to ask for a direction when being applied.

> Funnel takes only the biggest valid container, not all of them.

Aye. Same should work here (or in other words I'm for making it as synchronous with how funnels work for consistency).

**Comment by Coolthulhu** [comment]
> Need to ask for a direction when being applied.

I mean once the tap is placed.
In my solution (placing it directly on the tree), it is obvious that tap on the tree is installed properly.

How would you tell apart a lying tap vs. installed tap vs. tap installed on tree north-west from here?

**Comment by drbig** [comment]
@Coolthulhu how to draw a tap at a tree? With tiles that could/should be both easy and immediately obvious (and look cool too). With curses though? Colour? New symbol for a tapped tree? Etc.

Yeah it's an issue. My 'easy' ideas are: 1) just make it like a funnel, if the player can't track his own taps then his crappy farmer (or whatever); 2) make the tapped tree show in some examine description etc. (what I would actually prefer).

**Comment by Coolthulhu** [comment]
With curses, trees with items on them would be highlighted.

> 1) just make it like a funnel, if the player can't track his own taps then his crappy farmer

It's not about player tracking it, but the code itself. How do you intend to tell apart a funnel installed into the NW tree and one installed into the NE tree? What if they're both on the same tile, like this:
```
7.7
.V.
```
With 'V' being 2 taps - one attached to left tree, the other to the right.

**Comment by drbig** [comment]
I concur. Taps on trees then.

**Comment by Zaweri** [comment]
@drbig I don't get why did you leave me a note saying to reply? I don't have anything constructive to add to this.

**Comment by dholmes215** [comment]
> Aye. No sap during winter for sure (and probably most of spring too).

IRL, I believe spring is really the only time you can tap trees.  Sap flows in the spring when the temperature is fluctuating between non-freezing and freezing temperatures.

**Comment by yowshi** [comment]
you can kind of tap year round but trees actually store the non water materials for sap in the root system. they use it in the spring to fuel early leaf development. so while you can tap year round you get more sap in the spring then any other season because thats when the tree is moving it;s stores around.

**Comment by BevapDin** [comment]
Implemented by #16190.
