### ISSUE TITLE
Advanced inventory management ('/' key) can lead to duplicate item key assignments

### ISSUE THREAD

**Issue by cwc** [CleverRaven/Cataclysm-DDA#13368]
I had an item of clothing that was assigned the letter 'q' at some point. I moved the clothing into a vehicle, did some fighting, and wound up picking up a spear, which was assigned 'q'. I soon used the AIM interface to wear the clothing again, and it retained its original 'q' letter assignment. Using 'q' to select an item will only refer to the spear.

Minor bug, but might be worth looking into. This occurred on Linux, HEAD at e3d6c2267c463c28c9e55d416dc31b4d38cb22d1.
##

**Comment by drbig** [comment]
Came across this:

Assign `l` to flashlight. Play a bit, move crap using AIM.... Discover your flashlight now has `y` assigned for no apparent reason... I went back and got all the flashlights from the car - and `2 flashlights (off) (100)` have `l` properly assigned (it's in yellow).

So... is that somehow a bug in the assignment (as in: "assigned key to `flashlight (off) (100)`")? This doesn't make sense - last time I checked assignment was per item ID, so charges can't have anything  to do with it. Did I miss anything?

Screenshot:
![Inventory](http://i.imgur.com/KRDnKfS.png)

**Comment by BevapDin** [comment]
Well, this is quite easy to reproduce, but it's more an artifact of how inventory letters behave and has nothing to do with AIM:

1. Get several flashlights (they all appear as 1 stack in the inventory), assign letter 'l' to them.
2. Activate the stack. Only the first flashlight is activated, but it does not stack with the other flashlights anymore (it also has a different type). It keeps the letter, and the other items get into a new stack, getting a new letter.
3. Drop the active flashlight.

Now you have the remaining stack of flashlights with a different letter. If you pickup another flashlight that does not stack with any existing stacks (an empty flashlight would work in this example), it *will* get assigned the correct letter 'l'.

This is actually very similar to the #10165, same thing happens there: the stack of 2 cans of cola is change to one stack of 1 can of cola and another stack of 1 (empty) can. The letter stays with the second (new) stack. And this is correct because the second stack is the one containing the very same item that has been selected for eating via it letter.

In the end it boils down to those rules:
- If an item in the inventory already has a letter (either manually assigned or automatically), that letter is never changed automatically, only through explicit user actions.
- If an item from a stack (usually the first one) is changed so does not stack with the remaining items, it is moved into another item stack. If there is a matching stack, the item is just added to it. Otherwise a new one is created and the items *keeps* its current letter (which becomes the letter of the new stack).

**Comment by drbig** [comment]
So... not a bug then? :D
