### ISSUE TITLE
Monster Upgrade Factor

### ISSUE THREAD

**Issue by i2amroy** [CleverRaven/Cataclysm-DDA#13395]
So I looked into the code for this and it seems we've got two different directions going on.

In monster.cpp we have this:

``` c++
scaled_half_life = type->half_life * ACTIVE_WORLD_OPTIONS["MONSTER_UPGRADE_FACTOR"];
```

i.e. higher number = longer half-life = longer time between upgrades

Meanwhile in mongroup.cpp we have this:

``` c++
starts = mon.get_int("starts") / ACTIVE_WORLD_OPTIONS["MONSTER_UPGRADE_FACTOR"];
ends = mon.get_int("ends") / ACTIVE_WORLD_OPTIONS["MONSTER_UPGRADE_FACTOR"];
```

i.e. higher number = sooner start/end = faster upgrades of monstergroups

They can't both be right. They both need to be going the same way, and we need to make a clear note of which direction that is in the options menu, because right now the text is _very_ ambiguous.
##

**Comment by kevingranade** [comment]
I think, "bigger numbers means more upgrading" is easier to understand.

On Sun, Aug 23, 2015 at 5:19 PM, Christian Buskirk <notifications@github.com

**Comment by drbig** [comment]
I think we should have monster upgrades either on per-monster basis or per-mongroup basis - not both. The per-monster basis seems to be more flexible as it can already use mongroup as targets.

> `scaled_half_life = type->half_life * ACTIVE_WORLD_OPTIONS["MONSTER_UPGRADE_FACTOR"];`
i.e. higher number = longer half-life = longer time between upgrades

Because default `half_life` is within 10 - 28. Doing it with `/` means you would pack "default - insane" within 1 - 28, but "default - very very slow but still sane" into 0.99 - 0.01. You could even argue that with `/` the upper bound should be the lowest default `half_life` e.g. setting it to 10 means already some monsters will upgrade on first sight. The way it is now it's easy to make sense when you want the upgrades to scale with the season length you use, e.g. twice the default? - then set the factor to 2.0 etc.

> `starts = mon.get_int("starts") / ACTIVE_WORLD_OPTIONS["MONSTER_UPGRADE_FACTOR"];
ends = mon.get_int("ends") / ACTIVE_WORLD_OPTIONS["MONSTER_UPGRADE_FACTOR"];`
i.e. higher number = sooner start/end = faster upgrades of monstergroups

Looking at monstergroups.json `starts` is about within 72 - 2160 - yep, that's pretty obviously "incompatible" with 10 - 28 of `half_life` regardless of whether the factor is `*` or `/`.

Also does `starts` and `ends` here mean "time span when the mongroup will spawn monsters", or "time span when the mongroup will upgrade/do something else"?

**Comment by NickGrease** [comment]
From just a plain users perspective, this option needs cosmetic work too. I would say remove the word 'half life' (from the UI text), as it only confuses the option. The numeric value of the option is meaningless without some context; does 1.0 mean monsters will upgrade everyday? every 'half' day?, some arbitrary number of days that isn't shown to the user? How many 'upgrade' levels do monsters go through? If it's only say, 3, then I might want the upgrades to happen once a month, if there are many upgrade levels, then maybe upgrades once a week would suffice.

On  "bigger numbers means more upgrading". I took it as bigger numbers means more time between upgrades, for what it's worth.

Pretty much all of that can be addressed in the option tip section I guess.

**Comment by drbig** [comment]
> On "bigger numbers means more upgrading". I took it as bigger numbers means more time between upgrades, for what it's worth.

That's how it is now for per-monster upgrades, and that's what the description was meant to convey (I guess it worked...).

The problem with current approach is that it can't actually be fully described in a couple (say 2 ~ 4) short sentences. Believe me, I still *try*.

Now what @i2amroy has pointed to is a new thing for me. Didn't see it (I assume it was there) when working on the rework...

Given the monster upgrades are both a *good idea* and a very nice mechanic per-se - this still isn't anywhere near finished. I'm sure though we'll converge on a decent solution in due time :D

**Comment by NickGrease** [comment]
> Because default half_life is within 10 - 28.

Somehow I missed that part. Can I read that as 'With a default value of 1.0, monsters will upgrade between every 10 to 28 days'?

**Comment by drbig** [comment]
> Somehow I missed that part. Can I read that as 'With a default value of 1.0, monsters will upgrade between every 10 to 28 days'?

"Exactly" (but it might still be more subtle than that). But note that the 10 - 28 span is *not known to the player*. And it's meant to be like that. (And you *can* always read the source (or ask on IRC) to get properly spoiled)

**Comment by drbig** [comment]
Actually, if we continue on the path of radioactive decay (or any other similarly complex one) a proper Wiki article is a *must*.

**Comment by NickGrease** [comment]
I can appreciate keeping the 'technical' value hidden (eg. 10 to 28). That being said, this is a user option, and if the user has no idea if s/he is scaling hours, days, weeks, months, years etc. it makes the option kinda hard to use. 

Another option might be to change the values to 'slow, average, fast, insane' or something. That keeps the actual values secret(slow:28-36,average:10-28, etc.), while giving the user a (somewhat) meaningful understanding of how the option works.

**Comment by kevingranade** [comment]
Veeeeery stale issue.
