### ISSUE TITLE
Suggestion: Infrared lights / nightvision cameras

### ISSUE THREAD

**Issue by cwc** [CleverRaven/Cataclysm-DDA#13455]
https://www.reddit.com/r/cataclysmdda/comments/3iymxy/security_cameras/

I don't know if you'd want to add a special kind of nightvision camera, as it might make standard cameras pointless (other than not being able to scavenge / craft the better model). Maybe infrared lights instead? Cameras would be able to see anything lit by them, in the same green hue as NVGs.
##

**Comment by Zireael07** [comment]
Nice idea!

**Comment by stk2008** [comment]
I like this idea I think the best thing would be to add infrared LED arrays and have them manually activatable :).

Or just assume (like most securty cams that the LED array is built into the camera but just reduce the range at night to reflect the limited range of the LEDs,

**Comment by kevingranade** [comment]
Sounds reasonable and relatively easy, when we're doing FoV calculations in
lightmap.cpp, process NV cameras just like regular cameras, but mark what
they see on a NV array instead of the normal vision array, then when
drawing what the player can see, use the NV array as a fallback if the
player can't see the quare some other way.

**Comment by BorkBorkGoesTheCode** [comment]
This idea is greatly needed for the armored vehicles in Tank mod.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
