### ISSUE TITLE
Reflex recurve bows aren't a thing

### ISSUE THREAD

**Issue by AlexanderUlanH** [CleverRaven/Cataclysm-DDA#13478]
A recurve bow curves away from the user at the tips.
A reflex bow curves away from the archer all along the limb, including at the tip.
If you try to combine those, you just get a reflex bow, because the tip of the limb is already bent.
Visuals/explanation: http://allaboutarchery.tumblr.com/post/32356244081/traditional-recurve-reflex
My immersion is ruined.

**Comment by Night-Pryanik** [comment]
https://en.wikipedia.org/wiki/Bow_shape, and, for example, pic from there:
![hun_bow](https://cloud.githubusercontent.com/assets/11132525/9653609/3a321f36-522d-11e5-85ea-6d50166417c2.jpg)
Its tips are curved away from the user, so it's recurve.
Its arms are curved away from the user, so it's reflex. 
Altogether it's reflex recurve bow.

**Comment by sztosz** [comment]
Actually, @AlexanderUlanH is right. Reflex bows are just an "advanced" form of recurve bows. Recurve bows have their tips curved away from the wielder. Reflex bows have their arms, not only tips of arms, but also including tips curved away from the wielder. 

In other words, a reflex bow might be considered a  kind of recurve bow (because its tips are curved away from wielder), but no bow can be recurve - reflex. Let's look at analogy. Ape's are mammals, gorillas are mammals too. Gorilla is an ape, but there is no such thing as gorilla - ape mammal.

**Comment by macrosblackd** [comment]
I'm really not sure what the point of this issue is.  Are you an enthusiast archer and want to help create a more realistic lineup of archery equipment?

**Comment by Night-Pryanik** [comment]
![fleetwood_monarch_take_down_youth_recurve_bow_1312215_1_og](https://cloud.githubusercontent.com/assets/11132525/9661778/eede0b66-5264-11e5-9985-0cbd01ae2a30.jpg)
Here we can see bow with straight arms and curved tips - recurve.
![attila_hungarian_recurve_bow_32](https://cloud.githubusercontent.com/assets/11132525/9661796/09ba82ac-5265-11e5-953d-3a9a186ee27f.jpg)
Here we can see bow with curved arms and straight tips - reflex.
Combination of these two is reflex recurve.

**Comment by sztosz** [comment]
Yep, sorry for my last comment. I did not know back when i wrote it that bows can be reflex/deflex and also recurve/decurve. Those are just traits of the bow that can coexist. I feel slightly embarrassed, for my previous comment.

**Comment by AlexanderUlanH** [comment]
Oh, huh.  I was looking for a source that showed a distinction between the two, and I couldn't find one, but I managed to miss the mention on Wikipedia.  I'd been thinking what was in sztosz's post, and that the pictured reflex bow would also be considered as having a recurve.
