### ISSUE TITLE
Make the game playable on HiDPI screens

### ISSUE THREAD

**Issue by svenstaro** [CleverRaven/Cataclysm-DDA#13482]
Currently, CataDDA (graphical version) is hardly playable on HiDPI screens. Even if the tiles were large enough, the text is illegible. The proper solution would be to make its in render size independent of the window size. This would work as follows:

- The in game viewport would show as many tiles as configured in the options, always
- Resizing the window scales the whole game up/down as required but it wouldn't change how many tiles are shown, it simply makes everything larger/smaller

Since CataDDA uses SDL2 for rendering, my suggested changes should be rather easy to implement but we still need to talk about it before I make a patch.

I suggest not making a bigger font/bigger tile set hacky fix. This doesn't really solve the fundamental problem that currently windows viewport size and render size are fixed to one another.

**Comment by tyrael93** [comment]
Why on earth would you play a roguelike with tiles

**Comment by macrosblackd** [comment]
@tyrael93 How about not deriding the way other plays choose to play a game?

**Comment by svenstaro** [comment]
How do you guys think this technical issue should best be handled?

@tyrael93 You can make an issue here in github and suggest the removal of tiles if you feel that way. I'm strongly for keeping them though.

**Comment by kevingranade** [comment]
I assume you're suggesting rendering to a back buffer sized as per the
options and tile size, and then blitting to a display buffer that's scaled
as per the window size.
The alternative, adjusting scaling for each render operation, would be
strictly worse since we render a number of layers, and it would defeat any
tile caching we do.
I'm a bit concerned that pervasive rescaling is going to cause performance
issues on some systems, so at a minimum any such system needs to have an
option to disable it.  Specifically we support systems that fall back to
software rendering, and scaling while blitting is really expensive in
software.

Please ignore tyrael, and rest assured that we ignore him already.

**Comment by svenstaro** [comment]
Yes, the backbuffer stuff is very much what I suggest. SDL2 makes this trivial using [SDL_RenderSetLogicalSize](https://wiki.libsdl.org/SDL_RenderSetLogicalSize) function. On hardware accelerated systems, this will not cause a slowdown. In the case of software rendering, we could use [SDL_BlitScaled](https://wiki.libsdl.org/SDL_BlitScaled).

**Comment by dustinlacewell** [comment]
Very very very much please this. +1

**Comment by svenstaro** [comment]
Ok guys, please test.
