### ISSUE TITLE
Make unbalanced vehicles not scrape when dragged

### ISSUE THREAD

**Issue by md000** [CleverRaven/Cataclysm-DDA#13525]
I think it would make sense only for vehicles completely without wheels to scrape when dragged. A good example would be the real life wheelbarrow, which clearly isn't balanced on its single wheel yet can be moved around without problems.
The balancing (no pun intended) factor could be the reduction of max weight allowed to be dragged compared to balanced vehicles, since you would always have to keep a part of the vehicle lifted.
I've no idea how hard would it be to implement this, but I guess that a good part of the infrastructure is already in place with the vehicle examine screen differentiating between wheelful, wheelless and unbalanced vehicles.
##

**Comment by kevingranade** [comment]
Can you give an example of an in-game vehicle where this is a problem? I
think you can make a wheelbarrow with a single wheel, frame, and cargo
carrier all on the same square and everything works as you describe, but
this obviously isn't the case with a multi-tile vehicle, and it shouldn't.

**Comment by md000** [comment]
Just went into the game and made a vehicle from a wooden frame, a wooden cart wheel and a box to check if I was not mistaken and it scraped when dragged around. Realistically this shouldn't be the case. Even if one more wooden frame was added to the vehicle without adding another wheel I think you should be able to keep that frame lifted from the ground while dragging the vehicle around, with weight limitations of course. Again - that's how wheelbarrows work in real life, not by being perfectly balanced on a single wheel.
I also noticed that the single wooden cart wheel vehicle was seen by the game as lacking wheels and not as unbalanced, so that might be part of the problem.
Now I wasn't using the most recent experimental, but it was less than 2 weeks old and I am pretty sure from following the pull feeds that nothing was changed in that regard during that time.

**Comment by drbig** [comment]
> I also noticed that the single wooden cart wheel vehicle was seen by the game as lacking wheels and not as unbalanced, so that might be part of the problem.

I wonder if this is intentional (i.e. you need two wooden wheels?)

**Comment by faerindel** [comment]
Aren't all vehicles with one wheel declared as lacking wheels (despite being single tile) unless it's a unicycle or wheelchair wheel?

**Comment by md000** [comment]
I believe they are, though I don't think they should be. Also, casters and wheelbarrow wheels are also stable.

**Comment by i2amroy** [comment]
Maybe calculate if it should scrape by calculating the center of balance like we do already with cars and pretending the player is another wheel location? Then if the center of balance is in the "good" area then it doesn't scrape, and if it isn't it does.

I mean that's basically what's happening in real life anyways.

**Comment by Rivet-the-Zombie** [comment]
That sounds like the best solution, @i2amroy.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
