### ISSUE TITLE
Necromancer's ability cooldown increase

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#13524]
Maybe I'm just unlucky, but in my last game I encountered necromancers only in groups of two and three. That makes them somewhat hard to kill, because when I'm just done chopping one to death, the others resurrect it right now. So I can't even stand on its corpse to prevent resurrecting. The same with ranged no-burst-fire-able weapons. And even if I need only three (approx.) blows to kill it, other necromancers seems to have enough time to restore their superpowers, and this dance of macabre starts over and over again.
If there is some cooldown in using of their ability to resurrect, maybe we should rise it a little? Interval like the one that have spitters and shockers using their own abilities, for instance.
##

**Comment by smmck** [comment]
That would be very helpful. I think that I had to put the same Hulk down 3 or 4 times in the dark before the Necromancer came close enough that I could find him. I kept trying to butcher the Hulk but it got back up before I could do so.

**Comment by kevingranade** [comment]
The last time we discussed this we were talking about adding some stat to
the necromancer that could run out in addition to the special interval, the
idea being the necro could have a burst of activity, but if you put down
several creatures in a row it would run out and you'd have time to kill the
necro.  Also adjusting the cooldown based on how tough the target is would
be reasonable, with a short cooldown for regular Zs, and a long one for
hulks and other necros.

**Comment by i2amroy** [comment]
>The last time we discussed this we were talking about adding some stat to
the necromancer that could run out in addition to the special interval, the
idea being the necro could have a burst of activity

Unless someone changed them this is already how Necromancers work, they burn their own speed stat whenever they revive someone, and have to take time to recover their speed before they are able to do future revives. As such necromancers might be able to revive each other back and forth for a little while, but after a bit they will run out of speed and stop being able to revive each other unless given some time for it to recover.

**Comment by Night-Pryanik** [comment]
> unless given some time for it to recover.

That's the point. At least in my last game necros were never strolling alone. Maybe that was because I play with hordes turned on, but usually there were tons of zeds around them. You just made an opening in the horde to get to the necros, and voila - all of them slain zeds are "alive" again, blocking your way to the necros. They have plenty of time to recover by supporting each other and restoring the wall of zeds.
I'm not complaining - fighting them is hard, but fun. I think all we need is some balancing of timing.

**Comment by kevingranade** [comment]
OK, you need to be a bit more concrete about the issue then, how many
necros, how many supporting zombies, how fast are they reviving supporters,
how long is it taking you to drop a zombie, etc.

If we're talking two necros and 20 regular zombies, yea I expect the necros
to be able to revive zombies as fast as you kill them, but just for a
little while, then they burn out and you can start making progress.  And
yes, this implies that if you can't kill zombies fast enough and for long
enough, you might not be able to take out that group, that's not
necessarily a problem.

What I'm looking for is a scenario where you 'should' be able to take out
the group, but you can't.  Then it'll be a matter of whether we agree with
both parts of that.

**Comment by Night-Pryanik** [comment]
Okay, I'll try to be more concrete.
In fact, there were very few true regular zombies in the horde. Approx. 20% of it in sum were "special" zombies, like corrosive, spitters, shockers, smokers and hulks; 70% were regular, but tougher versions, like brutes, hunters and grapplers; 10% were true regular zombies.
I remember 4 hordes with necros - one time it was 5 necros in it, two times it was 4 necros, and one time it was three necros.
On average I need three melee hits to kill "average" zombie. When necros were close enough to me chopping some enemy, in most cases slain zombie was resurrected right after I killed it. Because in all cases necros tend to group with each other, it was hard to understand, which one is reviving in question.

**Comment by kevingranade** [comment]
So one critical thing was missing there, how many zombies in total?
Let me put it this way, I need to be able to re-create the horde you're
describing to reproduce your issue, so I need the actual numbers.

**Comment by Night-Pryanik** [comment]
Oh, I forgot about it, sorry. I didn't count them precisely, but I think there was at least 30 zombies of all species in total.

**Comment by Night-Pryanik** [comment]
![1111111111](https://cloud.githubusercontent.com/assets/11132525/10393876/20f9a3fa-6e9c-11e5-8e75-ddb581c8bf20.png)
I don't know how to effectively get rid of this necromancers party. There are twice the number of necros to the left of this screen.

**Comment by Coolthulhu** [comment]
I'll also bring up the fact that necros can now revive pulped corpses. This should probably be reverted to old behavior. Or better yet: have a "could ever revive" function check corpse type, flag, damage and burnt to make sure the behavior is consistent across all reanimation methods.

As for the cooldown: instead of reviving immediately, necro could just decrease time to revive, similar to how master decreases time to evolve.

**Comment by BevapDin** [comment]
> Or better yet: have a "could ever revive" function check corpse type, flag, damage and burnt to make sure the behavior is consistent across all reanimation methods.

You mean `item::ready_to_revive`. It checks age, damage and burnt factor, but it has a bit of randomness in it.

**Comment by Coolthulhu** [comment]
> You mean item::ready_to_revive.

Something like this, except without checking if the corpse is of legal age.
Unless we go with the idea of necros just decreasing time to rez, then it would work with `ready_to_revive`.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
