### ISSUE TITLE
Possible optoin to make NPC`s shut doors after them

### ISSUE THREAD

**Issue by stk2008** [CleverRaven/Cataclysm-DDA#13546]

**Comment by stk2008** [comment]
Basically as per title.

I get into my car so does NPC he leaves the bloody doors open every time.

Is there a possiblity we can have an optoin in the g menu to close doors behind them :)

**Comment by chaosvolt** [comment]
Same as with building doors, I'd like if they knew how to close them. I mean maybe add a check for prioritizing "kill the zombie right next to you" over niceties like door-closing, but that's probably as complex as it needs to get.

One possible option for refining this would be allowing "do not enter" zones, with NPCs also ignoring doors in the zone's borders. Also useful if you want your allies to sleep outside because you're a jerk. o3o

**Comment by mugling** [comment]
@Coolthulhu I think your recent PR covered this?
