### ISSUE TITLE
Pack of firecrackers doesn't disappear after booming

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#13582]
After saying its last "bang!" it remains in "(lit) (active) (0)" state for ever and doesn't disappear, like single firecracker does.

0.C-3693, Win 10, tiles.

**Comment by Night-Pryanik** [comment]
![111](https://cloud.githubusercontent.com/assets/11132525/9939740/850ba7aa-5d74-11e5-9b5c-f94910f76c8b.png)
Hope it understandable in Russian.

**Comment by chaosvolt** [comment]
Quite understandable enough. Issue here is the fact that the firecrackers in the pack are treated as ammo or charges, and the firecracker action has no code in place to remove the item when it runs out of charges.

Also related, you can't dismantle a pack into its component firecrackers because the recipe would have to either treat the pack as a tool (draining 25 "charges" of firecracker and leaving an empty pack), or by treating it as a component (which ignores how many firecrackers are in the pack).

**Comment by Night-Pryanik** [comment]
I think devs just didn't checked this issue after I loaded these screenshots.

**Comment by chaosvolt** [comment]
True, and @drbig added that label before you posted the screenshots from the looks of it.

**Comment by drbig** [comment]
I slap "Confirmation Needed" on vast majority of bug reports to indicate "would be nice someone else than the original poster replicated this" out of a principle (because we have 3 platforms × 2 UI versions × the number of actual versions people play ;)). It's also to maybe get people involved (don't code? don't do JSONs? well, you can check bug reports and confirm they're (still) the case).

**Comment by chaosvolt** [comment]
Understandable, yeah. ^^"

I'm wondering what would be the best way around this. I assume adding a "remove on deactivation" function to the lit pack of firecrackers?
