### ISSUE TITLE
Show explosives damage?

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#13590]
Player know melee weapons damage, ranged weapons damage. But at the moment player doesn't know, what is more destructive, for example, match head bomb or pipe bomb.
Is it possible to player to know how much damage given explosive will deal? Maybe average or maybe range.

**Comment by kevingranade** [comment]
Something I'm planning on doing in the future is rebalance a lot of the
weaponized explosives around published lethality range for a similar
explosive.  It would be meaningful to expose that number to the player.
FYI the definition of 'lethal range' for this purpose is 'the range at
which there is a 50% chance of the explosion causing a lethal wound to an
exposed person'.  Safe range, if any is much further away, and still not
100% safe, just 'acceptably safe' :)
A damage number isn't going to tell you much because the actual damage
inflicted varies based on a lot of different variables.

**Comment by chaosvolt** [comment]
Feedback on explosive damage would also be more useful if the explosives available to projectiles was expanded.

Explosive shotshells, 40mm concussion rounds, M72 LAW rockets, even 120mm shells all use the same explosion.

**Comment by drbig** [comment]
MythBusters do a lot of such tests and they usually base the results on pressure at distance X, Y, Z etc. with some threshold for "lethality". My still-sleepy opinion is: for the purpose of the game some general number that scales with the explosives should be enough (i.e. not trying to tie it to any RL measure, simply something that will tell the player a match bomb is less than C4 which is less than a mininuke).

**Comment by Night-Pryanik** [comment]
> simply something that will tell the player a match bomb is less than C4 which is less than a mininuke
That'll be great!

**Comment by mugling** [comment]
Recently committed to mater with more updates to follow
