### ISSUE TITLE
Directional Graffiti for Walls

### ISSUE THREAD

**Issue by vache** [CleverRaven/Cataclysm-DDA#13594]
Right now, graffiti has some serious limitations to the point where most people would never know it existed.  It can only be placed on the ground, and as far as I can tell, can only be read when walked over.  One big thing to make it worthwhile would be to adjust it so that it can be placed on walls, but this brings up the issue that it would be visible on the wall from any orientation (so if you sprayed a message on the outside of a doctor's office and then went inside, it would be visible from the other side).

An idea I had would be to attach some sort of facing data to graffiti, so that it keeps track of which direction it is facing.  An example might be if you were standing to the north of a wall and painted a message on it:

```
 @ 

---
```

The graffiti would be stored with a facing of north, so that it is visible only when viewed in a northern (northeast, north, northwest) direction.  One difficulty is with graffiti in corners:

```
 |
-+
   @
```

If there were graffiti on the eastern and southern side of that corner, they would both be visible at that location, which may or may not be a problem.  Also, if the player tried to place graffiti there, it's assumed that there would be no southeast face, so they might have to be prompted which face to actually paint on.

The real difficulty here I would think lies in the changes to fov and determining how to draw a tile depending on the fov.  I have no idea how any of these calculations work, nor how much it would affect the performance of them to tack on extra things to take into account.

The benefits could be extended past graffiti, it would allow for things like simple signs inside buildings (ex. "Office 101 - Dr. Johnson", "Surgery Ward", "Cloning Chambers", etc.) without having to dedicate a square for the sign furniture, graffiti during mapgen for flavor reasons (ex "Don't dead, open inside"), and it could be extended to things like paintings on walls.

Steps:
1.  Extend graffiti to include orientation and description/text
2.  Extend submaps to allow more than one instance of graffiti per square, or at least one for each orientation
3.  Allow graffiti to be displayed when examining terrain
4.  Extend fov code to determine when to render a tile as having graffiti
##

**Comment by Coolthulhu** [comment]
1 and 2 could be solved by splitting graffiti into 4 graffiti flags (graffiti_n, _s, _w, _e)

Performance impact (during drawing) on graffiti-less tiles should be a concern. Could be achieved by marking a tile as having any graffiti and checking only for that first and only then checking for directional ones.

3 would require some good display. Our current "'l'ook" menu is often quite lackluster (small window, mostly filled already). Maybe allow viewing details with some extra keypress?

4 could be easily (though not necessarily perfectly) solved by checking for the visibility of the adjacent tiles and checking the angle of player to relevant axes. For example:
```
.,..@
,+,..
.,...
```
`+` is the viewed graffiti, `,` is an adjacent tile to check. We'd eliminate south and west by an angle check, then check for visibility of the tiles at north and east. Depending on how strict we'd want to be, we could also eliminate north (by angle) in the example. East graffiti would be visible because `,` to the right of `+` is seen and because the slope of the line leading to it from player's position is quite low.


If someone has a different solution involving actual FoV calculations, I'd prefer it to wait until I get 3D FoV running.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
