### ISSUE TITLE
Expanded digging.

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#136]
Add a t_hole terrain type that can be used as the base for building palisades instead of using t_pit.

T_hole would go on the continuum of digging, t_dirt <-> t_hole <-> t_shallow_pit <-> t_pit.

Dropping items in a hole/pit and filling it would instead create t_disturbed_ground, which acts as a container for the items, and would prevent accessing the items like crates do unless dug up.
##

**Comment by Chase-san** [comment]
We would finally be able to bury the bodies of our fallen characters.

**Comment by Zireael07** [comment]
Necro-comment much?

**Comment by Chase-san** [comment]
Well that's how you bring life to old issues.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
