### ISSUE TITLE
Realistic nutrition

### ISSUE THREAD

**Issue by illusionofchaos** [CleverRaven/Cataclysm-DDA#13649]
Don't you think that nutrition should be made more realistic?

The values of the existing "nutrition" and "quench" properties can be made optional and be used to reflect changes to the perceived levels of thirst and hunger. But the real nutrition and hydration variables can be represented by two new item parameters - "calories" and "water percentage" (the percentage of water in the item's weight).

The character then should have "energy" (in calories) and "hydration" (in ml of water) properties, which should affect the body physically, while hunger and thirst should have a psychological effect and give player a rough estimation of real energy and hydration levels. These values can be decreased every turn taking into the account current weather, activity, weight, etc.

These properties will also make items' descriptions more realistic. The following:

```
Nutrition: 50
Quench: 12
````

can be replaced by

```
543 Calories
This item contains 250ml of water.
```

or (if the water percentage value is negative)

```
This item causes dehydration. Your body will lose 500ml of water.
```

Right now you can survive on zero protein (or the opposite - consume nothing but meat and feel great). This can be fixed by having a full-featured nutrition system that tracks the basic nutrients and vitamins. And the proposed changes can serve as the foundation for such system.

Another proposed change is to provide contents for items like this:

````
"contains" : {
    "alcohol":40,
    "caffeine":1,
    "orange juice":19,
    "water":40
}
```

and process effect, addiction and nutrition for each item recursively.

**Comment by drbig** [comment]
I remember we had a rather long discussion about this on IRC. There was also that issue about fasting for 5 days and then having to eat 5 days worth of food :) In any case I'll maybe try to read this over the weekend (just being honest).

**Comment by Coolthulhu** [comment]
Changing nutrition display to calories sounds good to me, because then new players could quickly figure out how much food per day do they need.

Water content sounds rather unintuitive to me, because of the whole dehydration thing. It would need some really clever wording.
Instead I'd use the same unit for nutrition and water content for a while. "Water calories", except with some better name.

As for recursive content: that sounds like a lot of work and thus would require a good justification.

**Comment by kevingranade** [comment]
My primary objection to a system like this (the 'comprehensive nutrition'
part) is the large amount of annotation that would need to happen across
all the foodstuffs in the game, followed by a new set of requirements for
any new foods that are added going forward.  It's a large amount of
additional work for a very moderate benefit.

Separating perceived hydration from actual hydration in particular seems
like a ton of effort that will mostly go unnoticed, if I'm understanding
correctly all this will do is ambush people by reinforcing their
misunderstanding that all fluids cause net increase in hydration, and hide
whether the food is hydration positive or negative.  It's better to just
reveal the objective hydration value.  As for whether the values are the
current timer-based units or Calories and ml of water, I'm ambivalent, if
someone wants to rescale them to be the latter and adjust the code, that's
fine with me.

What I would be interested in would be a very streamlined system that adds
few or no more mandatory food values and tries to cover as many common
malnutrition causes as possible.  Ideally there would be some very common
defaults, and only food that departs from these defaults needs to be
annotated.  E.g. only eating meat is problematic, but we could just give
pure meat items an optional flag or value to reflect this, and everything
else does not need to be updated.  Likewise other foods that are
specifically deficient in some way could be annotated with those
deficiencies, or if some nutrient is particularly rare, only foods that
provide it would need to be updated.

**Comment by illusionofchaos** [comment]
@drbig, I believe this issue can be solved by limiting the volume of human stomach to 1 kg of food and digesting 0.5 kg food per hour. Some mutations should increase the digestion rate or the volume of your stomach. There should also be a parameter which increases by 1 point every turn when your energy(calories) equals zero. If this parameter increases above the certain value, you die from hunger (the energy won't ever fall below zero). While your energy is above zero, that parameter will decrease by 1 point every 10 turns.

@kevingranade, I've just had another idea. We can specify the percentage of macronutrients and calculate the calories using the following rules:

```
Carbohydrate = 4 calories per gram 
Protein = 4 calories per gram 
Alcohol = 7 calories per gram 
Fat = 9 calories per gram
```

It's not necessary for the percentages to sum up to 100.
So if we take the following item:
```
{
    "weight": 250,
    "contains" : {
        "carbohydrate":12,
        "alcohol":10,
        "protein":5,
        "water":40
    }
}
```
we can calculate the calories as 250\*12%\*4 + 250\*10%\*7 + 250\*5%\*4 = 345 calories.
The alcohol effect can also be [precisely calculated](http://en.wikipedia.org/wiki/Blood_alcohol_content#Effects_by_blood_alcohol_content) based on 25g of alcohol.

As for perceived hydration, there is an issue with the sports drink that has quench value higher than water, because it won't look good if the description of 0.5L bottle says if contains 0,6L of water. Apart from that, the perceived hydration serves no purpose.

We can also keep a separate json with all micronutrients and drugs, containing their default units (g, mg, µg). Any item can optionally specify its micronutrient contents, vitamins should contain the daily recommended intake of all micronutrients. This will allow to create the comprehensive system without much effort.

For example, if we separate THC and CBD into different drugs, we can create various strains of weed with different potency and effects. 

@Coolthulhu, I think it's easier to keep in mind that you should drink about 3 liters of water per day. If it's hot and you sweat a lot, you need to drink more.

About dehydration, for example, if an item that weighs 250g has water content of -200, its description should reflect the following instead of the water volume:

```
To account for dehydration caused by consuming this item, you should drink an additional 500ml of water.
```
If that value is positive, it is simply converted to ml and displayed next to the calories. (It will be like "water calories").

The recursive comestibles can be rather simple. Here is the example of pseudo-code:

```
void func consumeItem(item, int modifier = 1) {
    processEffect(item.effect) //any stuff not dependent on weight
    if item.childItems.isEmpty {
        processNutrition(item.nutrition * modifier) //any stuff dependent on weight
    } 
    else for (childItemId,percentage) in item.childItems {
        var childItem = getItemById(childItemId)
        consumeItem(childItem, item.weight * percentage / 100 / childItem.weight)
    }
}
```

The benefit would be in the very simple addition of new items without thinking about their effects and nutrition. All you need is to specify item's weight and child items' proportions.

**Comment by Coolthulhu** [comment]
> We can specify the percentage of macronutrients and calculate the calories using the following rules

Those rules do not adequately represent what nutrition does represent right now.
For example, chugging oil would give you lots of calories.

> The benefit would be in the very simple addition of new items without thinking about their effects and nutrition.

I don't see how would that result from a change that actually introduces complexity.

Consider flour and oil vs johnnycakes.
Just going by macroingredients should give equal values on both sides. So instead of just balancing nutrition in game terms, you'd have to figure out how to properly represent increasing nutritional value in cooked food.

Most food items aren't just mixtures or sandwiches. Cooked meat is made from raw meat, but doesn't contain any raw meat.

**Comment by illusionofchaos** [comment]
@Coolthulhu, well, in real life chugging oil also gives you a lot of calories.

I proposed macronutrients as the minimal required properties for any food item. Their intake should be balanced and protein consumption should be sufficient. It should be possible, but completely optional to manually specify calories and micronutrient contents of any item. But the main source of micronutrients in 2040 are probably vitamin pills.

Even now a single vitamin pill contains all required micronutrients for a whole day. Other than that, a person needs 0.8-2g of protein per kg of body mass daily, and everything else should be balanced between fat and carbs. The perfect balance is consumed energy = spent energy. 

So it's possible for the daily menu to look like this:
* a vitamin pill
* 200g of meat / a vial containing a mixture of amino acids
* oil and starch/sugar

And when I said about complex food, I didn't mean that all comestibles should contain child items, only the ones that are combined without further processing (mixtures, sandwiches, salads, alcoholic cocktails).

Also, judging from [this article](http://blogs.discovermagazine.com/crux/2011/12/08/why-calorie-counts-are-wrong-cooked-food-provides-a-lot-more-energy/#.VgRvL7z5ikg), the macronutrient calorie values mentioned by me are valid for cooked or otherwise processed foods, so it's possible to use "raw" flag and decrease effective calorie value by 25-50%. As for micronutrients, there are actually [big losses from cooking](http://nutritiondata.self.com/topics/processing). 

All in all, this is just a discussion. I'm not advocating these changes, but it would be great for the game mechanics to be more realistic. I also think that complexity is a good thing for a roguelike.

**Comment by Headjack** [comment]
I think food needs a rebalance in some fashion, and I'm not opposed to this more simulationist kind of thing. One aspect I do feel strongly about is the value of superior recipes versus how worthwhile they are to bother making. In the current system, there are only a few higher-tier recipes that actually benefit you in any real way; it's only economical to eat cooked meat, biscuits, etc from a standpoint of maximizing Hunger restoration. There are things like wastebread, which let you use otherwise worthless ingredients, and things like soups that let dehydrated meat sub for fresh to allow stockpiling, but besides the big, brief morale boosts that lasagna and s'mores gives, almost all recipes are worthless.unless they convert spoiling foods into stable ones. Pelmeni, for example, isn't worth the flour or the meat to make when compared to Bread or Cooked Meat. 

If cooking is reworked, morale boosts should extend over a long period, similar to shaving/haircuts, to represent 'living well' in the post-apocalypse. Some manner of rolling buff, seen when eating good food for a long period of time, such as 1% speed up or a constant morale increase would make better cooking worthwhile for the survivor. I'd even go so far as including dinnerware and a table in the equation; I'll make the effort to act civil if I had the time for it in the end of the world.

Cata food is intentionally a little weird and cartoony. Instead of Potions Of Speed we have Atomic Coffee. I think letting Spaghetti Al Pesto give you happy feelings and a spring in your step is in line with that philosophy.

**Comment by tyrael93** [comment]
One thing is discussing about a complete food rebalance that is not .json editing, the other is actually working on it. Can you actually make this yourself or do you need help with it? Because since it looks like a trivial, but of course interesting, change, this looks like one of the hundreds of brainstorming issues or threads in the lab that end up not being able to get off the ground.
So, you have the skills or not? Do you have a friend that can help you do that or not? 'Cause all the good coders are doing other stuff.

**Comment by adrianrieck** [comment]
It would be interesting if the player could become fat and slower as a result of fat but be able to use that fat later when the stomach is empty and then burn said fat.

**Comment by Zireael07** [comment]
@kevingranade commented on another PR that nutrition should relate to calories 1:1. Anyone know a good source on calories as far as our in-game foods are concerned?

**Comment by mugling** [comment]
Effectively this is the vitamins system
