### ISSUE TITLE
Damage message ignores damage from mutations

### ISSUE THREAD

**Issue by md000** [CleverRaven/Cataclysm-DDA#13655]
![damage_bug](https://cloud.githubusercontent.com/assets/12977811/10104450/5765be64-63b2-11e5-8ebe-6610e47dcfb2.png)

Seems that the messages think my fangs are not doing damage, yet they obviously are killing stuff.

**Comment by drbig** [comment]
Looks OK to me. You get the mutation flavor messages, you get the hit score with the usual messages (for the style, I think).

**Comment by md000** [comment]
Huh, so it's intended? Ok then, just figured it was supposed to show the damage done like with all the other attacks. Not sure if I see the reason why it is this way though.

**Comment by Coolthulhu** [comment]
I think it would be a good idea to also describe the damage from mutations.
The character can see the results, but the player has to guess, which also stops anyone from trying to balance it (how many people know that at 10 str, toe talon is 40 damage?).
It wouldn't be hard to add either.

**Comment by vache** [comment]
It looks like this is an order of operations issue as well.  You attack the zombie child, the fangs land their attack and kill it before your main weapon attack, so it should bail out before it displays the "you hit the zombie child but do no damage" because it's already dead.

**Comment by chrahunt** [comment]
Is "[original text] for %d damage." alright with everyone?

**Comment by drbig** [comment]
So given #13789 this seems more like a (deeper) problem with multiple/chained attacks, the silly message being just a symptom.

**Comment by chrahunt** [comment]
@drbig I was under the impression that solving this would just be a matter of making the change that @Coolthulhu brought up, adding the amount of damage done to the message to avoid the misconception that mutation attacks aren't doing damage. It seems like the order of the attacks is separate, or at least that both are issues and it could be easier to at least knock out adding the damage indication and addressing the potential mechanics change separately.

**Comment by drbig** [comment]
To be completely honest recent times I neither play nor read everything top-to-bottom here.

What I have on mind is that an attack _action_ should stop the moment the target is dead (unless we want special cases, but this seems to be the sanest default) - otherwise we'll run into bugs like e.g. a special effect of a primary weapon executing even though the mutation attack already killed the target.

Or in other words this now seems to me that the "but do no damage" message is just a symptom of not stopping the attack chain.

**Comment by drbig** [comment]
> Do you think it would be easier to knock out the damage indication here and then address the potential mechanics change separately?

I think that if we correct the mechanics there won't be any need to change any messages :)

**Comment by chrahunt** [comment]
> Or in other words this now seems to me that the "but do no damage" message is just a symptom of not stopping the attack chain.

I see where you're coming from. I think I was kind of vague before, let me know if this helps. From my perspective there's two issues:

1. @md000 thought that mutation attack messages had a bug because they did not contain any damage feedback, even though the mutation attack was obviously doing damage. The original post and the title of the issue both mention the "messages" disregarding the damage. Here is what is being referenced, compare

    `"You tear into the zombie child with your saber teeth!"`

    with

    `"You tear into the zombie child with your saber teeth for 29 damage."`.

    @Coolthulhu said it would be easy to add the damage information text to the mutation attack messages and it was tagged as an Easy-fix.
2. @vache notes, based on the original image, that melee attacks go through even after the target has died. This is not @md000's original complaint, and is the mechanics change we're talking about.

**1** requires no additional discussion and could be implemented easily, as mentioned before. **2** probably could use some more discussion, but it doesn't seem right to hold up **1** when **2** could be addressed separately.

Does that make sense? Maybe @Coolthulhu could chime in, since I'm really going off of their comment for my understanding here.

**Comment by Coolthulhu** [comment]
Handling the second point should also be quite easy. Just changing the order in melee.cpp and bailing out if after any of the attacks if the target dies would be one solution.
Could also require stopping using special attacks if the target is far from the player (for example due to knockback).

Thinking about this, I also realized that there's another, tangentially related bug:
When performing a reach attack, mutation attacks are used too.
