### ISSUE TITLE
Disappearing Folded Vehicle

### ISSUE THREAD

**Issue by DodgingRain** [CleverRaven/Cataclysm-DDA#13662]
If you fold a vehicle that is over 4000 volume / 550 kg, it will display message of the vehicle folded but it disappears instead of a folded (vehicle) object on the floor under you.

Windows 8 Tiles.  v3720
##

**Comment by BevapDin** [comment]
Yes, of course it vanishes, the default maximal volume that can be put on a single tile is 4000, some furnitures allow more (like locker/display rack). If the item does not fit on the place it was put, it is moved to a nearby tile where it fits, but if there's no suitable tile nearby, it an not be placed and therefor vanishes.

Vehicle as big as that should probably not be foldable at all.

**Comment by drbig** [comment]
I think there should be a limit on folding vehicles (one tile, two tiles? something else?).

**Comment by kevingranade** [comment]
I *strongly* suspect that the mod extending foldability to all kinds of
vehicle parts is in use here, in which case it's not a bug, the mod you're
using broke the game.

**Comment by Coolthulhu** [comment]
The mod marks more parts as foldable, but it can't cause the bug on its own.
Theoretically a huge "deathmobile" (not actually mobile) made of foldable parts could exist in the core game, it's just that it's way less likely to happen.
It could also happen if a small vehicle got stuck in some weird place full of NOITEM terrain or filled with items.

While not really a major bug, it could easily be handled more gracefully by checking if the item was actually created before destroying the vehicle.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
