### ISSUE TITLE
Slimes have odd mega-replicating behaviour if z-level is enabled

### ISSUE THREAD

**Issue by Midaychi** [CleverRaven/Cataclysm-DDA#13676]
Last tested ea94807 on ubuntu 32bit but unknown when it started.

How to test: Visit various towns on a map started with zlevels on until you see tiny blobs running around. You'll know specifically if the area is connected to this issue when you also notice lots/occasional sounds underground underneath said blobs. Then either wait around for a while or wade into them kicking and punching and screaming.

Expected result: Slimes not actually being grey goo, and respecting solid objects

Actual result:
These two pictures were taken after a rather desperate attempt to run away from one such blob-swarm. The blobs started to the south, too far to see on the minimap, around the northern section of a town. The pictures are an ingame hour apart. Attempts to kill blobs just ended up in more appearing from thin air, and an increasing intensity/frequency of sounds being heard underground.

https://dl.dropboxusercontent.com/s/95pixbg0ezavbu1/slime1.png

https://dl.dropboxusercontent.com/s/ez84oaq3q8n2ci8/slime2.png

Halp, blobs op, plz glorf.

**Comment by Midaychi** [comment]
Fun additional fact to those images: It took me said hour to actually get where I was in slime2.png. I did manage to get into the car, but then spent another five minutes desperately punching blobs out of the car and watching them appear inside of it spontaneously in other parts, then just screwing it and flooring it and ending up with a half broken police cruiser down the road.

**Comment by drbig** [comment]
This sounds... intriguing :D

**Comment by DodgingRain** [comment]
Two things that I like to comment that might (or not) relate to this issue.

1.  When you use arc cannon/chain lightning on the blobs on the surface, it sometimes jump downwards to kill blobs at the level below it.  You can kind of confirm this when you shoot one blob, it sudden jumps to unknown targets and sometimes suddenly teleport hitting blobs at the surface again.  This also happens if you zap rats in the rat cave.  I'm not sure if the two bugs are related.

2. Related to 1.  Sometimes when you hit f fore fire, the initial targeting suddenly targets a seemingly empty square it is it because it is targeting a suitable target at the floor below that is closer to you (and you can actually damage them!).  Unconfirmed if this happens if z-level is off.

3.  Killing blobs at the level below should curb the spawning at the surface but I have not done this enough to fully confirm this.

**Comment by Midaychi** [comment]
Looking more into this, it seems connected with slime pits. The slimes ignore zlevels and pretend like they're on the surface when they split and replicate, and also aggro-horde you if there's a big blob on a lower zlevel.

**Comment by kevingranade** [comment]
Hah, the second part we might want to keep.

**Comment by scorpion451** [comment]
Possibly related: found a vault by the spammed "crashing sound from X and below" messages. Upon entry was  immediately swarmed by (literally) hundreds of irradiated wanderers and charred watchamacallums. Upon further exploration (enabled by a little help from the debug menu because I really wanted to see what was going on here)  I discovered most of the furniture in the place had been totally trashed, apparently due to numerous large rooms having been filled shoulder-to-shoulder with said occupants (checking the map in debug mode after I figured this out confirmed the clown car issue).

**Comment by Midaychi** [comment]
Yeah. Zlevels cry havok with some of the replicating features of monsters for sure.

**Comment by DanmakuDan** [comment]
In `game::monmove()`, the destination for monsters that are unable to move properly is set to the player's z-level, instead of the monster's z-level. This is what is causing blobs to "multiply" on the surface when you remain in an area near a slime pit long enough (slime pits extend pretty far away from the top level entrance).

`tripoint dest( x, y, get_levz() );`

I think there should also be some sound dampening between z-levels to reduce the chance of hearing critters tiptoeing under you.
