### ISSUE TITLE
Custom explosion animation not drawing in tiles build. Windows 10

### ISSUE THREAD

**Issue by John-Candlebury** [CleverRaven/Cataclysm-DDA#13694]
Neither flashbangs, EMP grenades, nor scrambler grenades are drawing explosion animations, even though code (with the flashbang) or json definitions (with the electric grenades), states that they should.
##

**Comment by chaosvolt** [comment]
This implies that the idea of a non-exploding grenade appearing to explode but NOT exploding was recognized as a weird thing, then fixed. The issue here is thus in the code comments referencing their former illusory explosions, which obviously should be removed. >.>

If an item description states outright it should explode, then that's just a simple json tweak. Either remove the text implying explosives, or add explosive properties to it.

**Comment by John-Candlebury** [comment]
I fear I dodnt explain myself properly then, the bug im reporting here is that: there is actual code (like not comments) that clearly states that flashbangs  should be drawing the explosion effect, and that the json fields:
 "draw_explosion_radius"
 "draw_explosion_color"

Are not working.

**Comment by chaosvolt** [comment]
Oh. That is odd, actually. If it's more than just comments, then it's presumably something relating to the code being set to draw the effect if the actual explosion power and such stats are set, but not if the visual property is set?

Not sure how old that issue is, but a likely guess would be when lower grades of explosion effect were added.

**Comment by BevapDin** [comment]
Needs more information. Works fine in curses and tiles. What are your values for "Animations" and "Animation delay" options? Are you using tiles or curses?

**Comment by chaosvolt** [comment]
Hmm, very odd.

![owie](https://cloud.githubusercontent.com/assets/11582235/10341842/0bc8e0ca-6cdc-11e5-9e3b-2d0e9ecfb488.png)

Since I've had my animation settings at the defaults, I'll have to play around with settings some. This is an outdated build though, 3725. =w=

**Comment by John-Candlebury** [comment]
Windows 10
Tiles build
Tileset  option set to false.
Animations are set to true and delay of 10
No explosions

The explosions are drawn in the curses build, however.

**Comment by John-Candlebury** [comment]
This has been fixed.
