### ISSUE TITLE
In addition to reinforce for more enc, allow lighten for less enc

### ISSUE THREAD

**Issue by canlo** [CleverRaven/Cataclysm-DDA#13698]

**Comment by Coolthulhu** [comment]
Someone would need to think up penalties for lightening. How much armor, coverage, environmental protection and storage capacity would it cost.

Then items for which it doesn't make sense would need to be special cased. Things like waterskins or wearable guns.

Sounds exploit prone too.

Overall I don't think it's worth the effort.

**Comment by kevingranade** [comment]
If anything, I'd say items that can be adjusted for lower encumbrance (or
lower warmth) would be the exception rather than the rule, so they would
get a flag indicating it.
In general though, I'm more likely to rip out the whole clothing
modification system rather than extend it.  It makes several things more
complicated, introduces inconsistencies, doesn't really make sense in the
first place and I'm not convinced it has any real benefit.

**Comment by kevingranade** [comment]
Closing as not particularly workable.
