### ISSUE TITLE
visual disruptor cbm has very bad curses performance when triggered

### ISSUE THREAD

**Issue by canlo** [CleverRaven/Cataclysm-DDA#13697]
very slow slows framerate to tiny
##

**Comment by Nymall** [comment]
Is this a mod item? I just booted up the latest exparimental and cannot find a Visual Disruptor CBM. The closest I could find is the Artificial Night Generator, which creates a negligible slowdown. What mods do you have enabled, and which version?

Version: f29320c Curses

**Comment by Rivet-the-Zombie** [comment]
It's not a mod; it's the result of a failed CBM installation.

**Comment by Coolthulhu** [comment]
It's probably `game::hallucinate`.

For every tile on the screen (whether visible or not), it rolls a random number, then (for 10% of the tiles) it gets a terrain type with all the bounds checks and the like and prints it at a nearby location on the screen.
Finally it forces a full game screen refresh.

It could be optimized by batching the terrain checks to avoid bounds check and submap retrievals, then optimized once again by rolling tiles to skip instead of "should this tile be affected".

But I don't think it's worth it. Hallucinations are a pure interface screw, can be easily bypassed by using the look command (it describes things as they are, not as they look) and as far as I recall, don't work on tiles at all.
I'd just change hallucinations to a big perception penalty and remove the graphical effect.
