### ISSUE TITLE
Build error in linux under file mondeath.cpp

### ISSUE THREAD

**Issue by heema** [CleverRaven/Cataclysm-DDA#13723]
using arch linux 64

while compiling with the command 
make CLANG=1 CCACHE=1 RELEASE=1 TILES=1 SOUND=1 LUA=1

i get the error
src/mondeath.cpp:737:23: error: rvalue reference to type 'const tripoint' cannot bind to lvalue of type 'const tripoint'
    for( const auto &&roachp : g->m.points_in_radius( z->pos(), 1 ) ) {
^           ~
1 error generated.

![errcomp](https://cloud.githubusercontent.com/assets/287527/10338694/bc5f4264-6d07-11e5-8f51-98026c14f2e5.jpg)

**Comment by tvm1** [comment]
I can confirm that. Pulled latest today and got same error.

**Comment by kevingranade** [comment]
Since I don't see a reason for it to be a rvalue reference in the first place, and I *do* see a reason for it to be const, I'm downgrading it to a regular reference, sorry for the noise.  If someone can explain a pressing need for it to be a rvalue reference, please enlighten me. (I'll get replies even with this issue closed)
