### ISSUE TITLE
Clothing pockets and hoods work sporadically, if at all

### ISSUE THREAD

**Issue by Midaychi** [CleverRaven/Cataclysm-DDA#13809]
49c6fa8
The save is here
https://dl.dropbox.com/s/h8idv634hihaqhm/Cold%20Springs.zip

You'll probably need the statsthroughskills II and artyom's mod from this zip to load the save without errors. (the latter is stats through skills modified by "Zombies-R-Us" on the forums to be slightly less op.)
https://dl.dropbox.com/s/9ifhkqqsg84a1gp/3rdprtymods.zip

The issue: Clothing with pockets only occasionally work properly, and sometimes just trigger once every couple hundred turns. 
Through observation, it might be the character sensing that their hands are cold, putting them in pockets, then seeing they're warm and instantly taking them back out? Idk.

Also, either I'm thick or this winter coat's hood doesn't function, if at all.

How to test the two above stipulations: Load the save and walk around, observing the hand warmth. Then take the turban off and figure out how to get the winter coat to cover your head. 

This save was created for testing a few things, so I have bird mutations. I guess maybe the beak is somehow interfering with a hood? Are they putting it on backwards? Sounds like something a bird would do.

**Comment by chaosvolt** [comment]
Basically...yeah, they automatically hit you with a brief burst of warmth when the relevant body part hits chilly levels.

You SHOULD be hitting the hood bonus though, as last time I messed with it, it seemed not to mind having some gear worn on the head.

Most hooded gear (like cloaks) already covers the head via normal methods, which is a separate mechanism from the hood bonus. Hell if I know how you can cover your head briefly with a hood while the hood is permanently up, though. Winter coats, however, are one of the unlucky few hooded items that don't also cover the head.

**Comment by drbig** [comment]
So to be honest I don't really get what this is all about, but then I don't play that much. Having someone who gets this replicate it (best without mods and on the latest commit) and comment here seems to be the next best step.

**Comment by Coolthulhu** [comment]
The check for whether to put hands in pockets etc. looks roughly like this:
```
convergent_temperature + bonus_heat < HOT || current_temperature + bonus_heat < COLD
```

Meaning that very warm clothing (warm enough to put convergent temperature below COLD to above HOT) will not be used for bonus heat until the body part actually gets cold.

As far as I recall, this restriction was so that when you put on warm clothing on cold body, you try to warm it up as fast as possible, so it bumps the convergent temperature by entire bonus heat value rather than just to comfortable.

We could just change it like that:
```
if( convergent_temperature < COMFORTABLE && current_temperature < HOT ) {
    convergent_temperature += bonus_heat;
} else if( convergent_temperature + bonus_heat > COMFORTABLE && current_temperature < HOT ) {
    convergent_temperature = max( convergent_temperature, COMFORTABLE );
}
```

That way it would still heat up at full speed, but only to comfortable. Then it would keep the temperature at stable comfortable. Unless something put it over comfortable (it can't prevent overheating).

**Comment by kevingranade** [comment]
Concerning severity of the issue, is there a situation where you have cold
*penalties* when you should not?  If so it's a relatively big deal, if not
it's just a mildly confusing UI issue.

**Comment by Midaychi** [comment]
Fortunately it looks like in this sort of situation, the fluctuation happens quickly enough that the cold penalties reset to comfortable levels before anything significant takes hold. I suppose it's just a weird ui issue.

Also something of note in the provided example in OP, both the wool scarve and the winter coat were providing pocket bonuses at the same time. Taking off either the scarf or the winter coat made the hands stop getting warm and let them stay at comfortable.

**Comment by chaosvolt** [comment]
Hmm. With me, I just make underclothes until I get comfy.

There is one related issue though. The transform use_action does not allow you to change what body parts a clothing item covers.

For cloaks, sometimes I want to wear a helmet plus a fur cloak, which is often impractical due to the cloak's high warmth.

**Comment by Leland** [comment]
Discussion's been stalled here for years. Closing.
