### ISSUE TITLE
New Military Building Suggestion (FOB)

### ISSUE THREAD

**Issue by IOSYN** [CleverRaven/Cataclysm-DDA#13802]
# The FOB -- Forward Operating Base.

If you've got an idea, constructive criticism, tips or anything it's all good, let us know. 
The more suggestions and feedback the better. Might not even end up as an FOB. 
Maybe a National Guard Outpost or something? who knows, you decide.
I'll list the primary ideas right now.
- Either a Long Term, permanent base (Concrete buildings, Motor pool, armory etc)
- or a temporary one (Tents/Canvas, sandbags. Kinda like the FEMA camp, etc)
- Size. 2x2, 3x3? **4x4 looking like the best option**
- Replace the current military outpost or keep it? we can decide this later.
- Mid-High level. Plenty of soldier zeds, some bio-operators, odd survivor/technician etc.
  - Turrets, minefields, manhacks, a tank drone or two maybe, etc.

Edit:
## Initial Design Layout

This will be the long term/permanent station option.
Chainlink fence > Mines / Turrets > Inner wall.

Strge/Med  |   Cmd / Comms |  Armory
Mess/PX    |    Drill Square    |_Barracks
Grge/Mtrpl |   Mtrpl/ Security | Entr/Security.

It's gonna be a real tight squeeze, so much so that it might be worth making it a 4x4 simply for the outer defense zone. if anyone wants to suggest an alternative layout I'm listening. 
Entrance security will be a large hairpin L going through Entrance/ Motorpool 1 to the Drill square, although switching the Entrance to the south square and just boosting the defense on it would be an option if we went 4x4.

**Comment by Rivet-the-Zombie** [comment]
I like this a lot.

**Comment by chaosvolt** [comment]
I like the ideas that have been thought of so far on the forums, as well as here.

As for the existing military outposts, I might suggest just beefing them up a bit, as much as their 1x1 space allows. Enough that they won't stand out as so bare-bones when contrasted with any future additions. Merging the two variants by combining the barracks, storeroom, and generator would be a good start.

Bunkers, meanwhile, seem to be less like an actual place you're supposed to occupy and more of a glorified supply point, so they might not need much tweaking.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
