### ISSUE TITLE
Drawing items in stack

### ISSUE THREAD

**Issue by Mshock777** [CleverRaven/Cataclysm-DDA#13824]
Just an idea: wouldn't it be more logical to draw item with biggest volume instead of the last item in stack? ( it's done in cata_tiles::draw_field_or_item)

Also why are we drawing item_highlight when there are items on furniture?

**Comment by Coolthulhu** [comment]
> wouldn't it be more logical to draw item with biggest volume instead of the last item in stack?

Could be (depending on the situation), but that would slow down drawing unless biggest items on each of the stacks were cached. Last item on the stack can be accessed in constant time.

**Comment by Mshock777** [comment]
Yeah, I figured it was not done for performance sake. I was just thinking how bodies are generated in things like mx_drugdeal, when corpse is generated first and you only see underwear/drugs. (I can't actually find code that handles this, I found some corpses in mapgen and mapgen_functions, but no dead college kids)

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
