### ISSUE TITLE
Add minor acid damage to items

### ISSUE THREAD

**Issue by Colesad** [CleverRaven/Cataclysm-DDA#13848]
I haven't been in Cataclysm for a while and now I am missing acid item damage. While it is good that everything in acid does not melt into nothing now, however, I think it is a bit unrealistic that  CDDA's acids make no damage to items at all, which also forbids player from using certain strategies like using acid zombies to damage packs of other zombies' corpses and using acid to clean location from trash.

Speaking about acid damage to zombie' corpses: even though zombies should be more acid resistant than simple humans they are still "human corpses reanimated with blobs" as far as I remember the world setting, meaning they should be damaged by acid, probably, except those, who evolved to withstand acid: Acid Zombie, Corrosive Zombie, etc.  

I suggest to add some damage to items in acid, scaled depending on acid resistance. I also think is it possible to cap the damage, so items won't melt into nothing while still being damaged.

I apologize for my bad English, it is not my native language.

**Comment by Skidborg** [comment]
I have to second this.  The acid mechanics make no sense since item damage was removed.

Standing in acid will burn your feet.  Acid will not burn rubber boots.  Rubber boots are supposed to keep liquids out.  So far so good.
However: Wearing rubber boots and standing in acid can burn your feet clean off, without damaging the rubber boots.  How does that work?

**Comment by Coolthulhu** [comment]
The acid burns legs, not just feet.
I assume it forms fumes or sizzles a lot.

**Comment by Skidborg** [comment]
Then shouldn't the tile be described as "mountain of acidic foam" rather than "pool of acid"?  If it's just spitting up flecks of acid that shouldn't be enough to remove limbs in a matter of seconds.  

And can't that just be extended to gear which gives waterproofing to the rest of the body and should easily keep out the acid completely?

And you can carve up human flesh and drop it in a pool of acid where it takes no damage, raising even more questions about this mysteriously foamy but selective liquid.

**Comment by Coolthulhu** [comment]
Acid doesn't melt limbs, it only damages them, making them unusable as limbs.
If acid was to melt entire chunks of flesh in seconds, it would be much stronger than it is now.
Acid burns are very painful and disfiguring, but like fire, they still kill by disrupting bodily function (for example, by causing bleeding, necrosis and poisoning) long before they actually remove significant amount of mass.

Changing the description to acidic foam could work.

Waterproofing isn't complete. It protects from water hitting the body parts this item covers, not getting there from other parts. Deep water bypasses waterproofing completely.
Environmental protection is used for scaling long term acid damage.

**Comment by Skidborg** [comment]
The issue may be that we haven't decided on *which* acid is spat by zombies, so there's no way to fix on what the effects of the acid ought to be.

**Comment by Colesad** [comment]
Why not make two acid types, one of which does damage to items and another is not?
As example, make another acid zombie with stronger acid or add item-damaging properties to evolved acid one, likewise same can be done with player acid grenades.

**Comment by Murumuru** [comment]
I am interested in this too. Missing the acid destroying items.

**Comment by kevingranade** [comment]
There is no possible acid that would dissolve whole zombie corpses yet not
be instantly fatal to a human, possibly at range. This feature is not
coming back.

**Comment by Coolthulhu** [comment]
And even just disabling zombies with acid would probably be much slower than jumping on them repeatedly with steel-toed boots on.
