### ISSUE TITLE
JSONization of NPC classes (skills, NC handling, etc)

### ISSUE THREAD

**Issue by chaosvolt** [CleverRaven/Cataclysm-DDA#13844]
So, this is one thing I was pondering might be a useful feature for future endeavors, but not really a must-have for me.

The way NPC classes are handled is currently (mostly) source-only. It rolls for total skill point allotment, assigns set bonuses to certain skills, alters AI personality properties, and tells it what NC itemgroups to use for weapons, clothing, and other starter gear.

It would be useful if these could be handled by JSON files, but I'm unsure how complex that would be. It might need to be handled in steps, I assume. Just expanding on the partially-JSONized NC files would be a good first step. The item groups themselves are accessible to be edited, but being able to have an NPC (or NPC class) reference other item groups would be a useful feature as well.

**Comment by drbig** [comment]
The long-term thread (e.g. #13783) of `lets export it to JSON`.

**Comment by chaosvolt** [comment]
Ah right. This is also another long-term JSONinzation thing. Could possibly shift this over to that other issue if the issue opener wishes,

**Comment by vache** [comment]
Honestly, NPC things would be much easier to move to json than mutations and bionics.  NPCs for the most part are a combination of stats, while mutations and bionics are abilities that DO something.

**Comment by chaosvolt** [comment]
Possibly, at least I would hope so.

We'd need to actually JSONize the code that does the "roll this many points of random skills, then add these bonuses" and "build the inventory via these item groups" effects JSONized though.

**Comment by vache** [comment]
Basically IMO there should be two systems: an NPC archetype definition that can be used to create generic characters, like bandit thug, bandit pyromaniac, old guard private, old guard lieutenant, electronics merchant, scrap merchant, scavenger, scientist, etc. And a specific NPC definition for one off characters that can also reference an archetype.

**Comment by chaosvolt** [comment]
Possibly. Though the same system could be used for both characters. Far as I can tell, the arsonist NPC is about the only unique NPC that has a class dedicated to it, though I assume it's possible for some random NPCs to spawn with it too.

Though being able to fine-tune the system inside an NPC definition would also wok, maybe. We'd need a system for telling it to skip the NPC class building, as setting class to null uses the "generic random crap" setting.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.

**Comment by chaosvolt** [comment]
Closure for incorrect reason, NPC classes are implemented inn JSON now. :V
