### ISSUE TITLE
Vehicle speed indicator missing in "wider" sidebar mode

### ISSUE THREAD

**Issue by ejseto** [CleverRaven/Cataclysm-DDA#13854]
Seems to be replaced by the new moon phase indicator.

**Comment by Night-Pryanik** [comment]
Not only vehicle speed indicator, but also player speed, move points and mood indicator. Not to mention that moon phase and lightning weren't supposed at all to show in wide sidebar.

**Comment by drbig** [comment]
Confirmed at d8f0546. Visuals: [outside vehicle](http://i.imgur.com/tn0ixvF.png) vs. [driving off a bridge](http://i.imgur.com/5lJY2EQ.png) (also the message log overflows...).

In general the sidebar (both wide and narrow) needs a UX revamp since the introduction of stamina (if not earlier). With this it's _past_ the point of `lemme squeeze this in too`.

**Comment by kevingranade** [comment]
The revamp might just be "get rid of one of the modes", it's absurdly
restrictive and confusing to try and support both.

**Comment by drbig** [comment]
Uh, yes making the same stuff show up on both is rather tedious.

We have a separate window for the message log so I'd say this part should give way. In terms of narrow-wide IMO narrow wins as smaller window sizes are the limiting factor here. We could extend narrow by a few characters if needed.

**Comment by Theundyingcode** [comment]
After updating to 3861 I wanted to report that it was cutting off the entire bottom row since stats no longer show up but this seems it was already reported here in a more limited fashion.  Would it be possible to at-least temporarily shrink the message log by a row to reclaim the space?

**Comment by remyroy** [comment]
I'll fix this overlapping issue for the wider siderbar.
