### ISSUE TITLE
Hoarder trait bug

### ISSUE THREAD

**Issue by Oskar636** [CleverRaven/Cataclysm-DDA#13851]
Even though I stay at maximum volume for a long period of time, the - 2 morale modifier doesn't go away. I think I remember this bug from the past. Experimental version 3829 / edit : I guess the modifier depends on how much stuff you can carry, but with maximum volume filled ( 118 ) I still always have - 9 morale.

**Comment by chaosvolt** [comment]
Now that you can't go over max volume anymore, this trait seems a tad hard to live with anyway, even without glorious bugs.

**Comment by kevingranade** [comment]
Bump it to 'within x% of max volume' or 'within x volume of max capacity'?

**Comment by chaosvolt** [comment]
That might mitigate it, yes.

Though another option would be bring back a limited version of the "over max volume penalty" as well, until you hit X% or X volume over the volume limit, at which point dropping ensues.

Though I suspect there was a specific reason autodropping was added, so this likely wouldn't be a good solution.

**Comment by kevingranade** [comment]
There's simply no reason to allow 'you can carry a little more, but with a
penalty'.  It was the #1 cause of people dying early game for no good
reason, because it was so easy to either pick up too much stuff or lose
volume capacity without noticing, and it was a punishingly high penalty.
It was just a bad game mechanic to have.

**Comment by chaosvolt** [comment]
Hmm. True, the reasoning there is understandable, though I have had issues with auto-dropping important things. It causes it own annoyances, but overall is likely better for players due to the disadvantages it displaces.

Also, it would've been downright hilarious if that accidental PR reference wound up citing something related to volume mechanics.

**Comment by illi-kun** [comment]
So, it seems that actual bug was fixed in #13884, and the only reason to keep this issue open is mention that hoarder trait is imbalanced and should be buffed.

**Comment by kevingranade** [comment]
Open it as a new issue if needed.
