### ISSUE TITLE
Gasoline and diesel spawn in jerrycans

### ISSUE THREAD

**Issue by namarrgon** [CleverRaven/Cataclysm-DDA#13850]
Diesel and gasoline now spawn in jerrycans even in situations that don't make sense.
This can happen during worldgen, where spilt diesel/gas is generated, e.g. around gasstations,
![](http://i.imgur.com/lckvrrJ.png)
or when vehicle parts, like tanks, are damaged and start leaking filled jerrycans.

This is most likely related to #13812

**Comment by drbig** [comment]
(`Confirmation Needed` because "please replicate". I think I've seen this somewhere...)

**Comment by chaosvolt** [comment]
Aw hell. I'd tested whether that PR would break anything, didn't see that occur. o.O

**Comment by Midaychi** [comment]
Just happened for me. I came across a hilarious amount of gas. 
![uhhhh](https://cloud.githubusercontent.com/assets/1968809/10836813/4b461f0c-7e6f-11e5-94b6-03fc35f3e84a.png)

**Comment by chaosvolt** [comment]
And after all my futile efforts in the past to crack open that storage tank, it's foiled by a bug. :V

**Comment by Oskar636** [comment]
Happened to me yesterday

**Comment by Zireael07** [comment]
Is this bug common? Wondering whether to upgrade my experimental...

**Comment by DanmakuDan** [comment]
It mostly affects that one hardcoded gas station mapgen with the sealed tank (it's hardcoded to "spawn_item" gasoline, which means a container appears by default), and the leak_fuel method in vehicle.cpp when a gas tank is destroyed (uses "spawn_item" also). Fuel leaking from a gas tank in a slow manner due to partial damage is handled correctly (generates a liquid object and drops it with m.add_item_or_charges).
