### ISSUE TITLE
Adding response conditions that check for worn item/trait

### ISSUE THREAD

**Issue by chaosvolt** [CleverRaven/Cataclysm-DDA#13865]
Apologies for opening an issue to suggest this, but this is something I started toying around with attempting, but quickly found myself unable to implement. I kinda just hit a brick wall and spent two hours staring at the code trying to puzzle out how to format what I was intending to do.

Put simply, I was attempting to add conditions for conversation responses. Whereas the two available simply have identifiers like "has_assigned_mission" and such, this would've had two parts to it. The actual ID, and the item or mutation ID it's looking for. In the former case, it would work like the u_is_wearing check for dynamic lines, and thus add the response to that topic if the player is wearing the right item at the time.

For the latter, it would check for whether the player has the relevant mutation, then add that response to the selected topic if so.

Optionally, being able to define the INVERSE, where a response only appears if the condition is NOT satisfied, would be useful as well.

These additions would've complimented an expansion of dynamic lines to allow checking for traits, which I have PR'd elsewhere ( https://github.com/CleverRaven/Cataclysm-DDA/pull/13867 ). I had that one closer to figured out compared to these other ideas.

**Comment by chaosvolt** [comment]
Hmm. Not sure how to even begin attempting this. I've still found myself trying and failing at this. @_@

**Comment by chaosvolt** [comment]
I've taken yet another attempt to look at how to code such a thing, and still just as stumped as I was before. >.<

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.

**Comment by chaosvolt** [comment]
Hmm. Unfortunate. :V

**Comment by BorkBorkGoesTheCode** [comment]
@chaosvolt :V

**Comment by chaosvolt** [comment]
I still wish I'd made the effort to try and make this idea a reality, but I never got far in the attempt.

**Comment by chaosvolt** [comment]
If I'd put in the effort I could've eventually figured it out, which is just another "should've, would've, could've" on my list. There were countless minor clever ideas, fixes, and improvements that likely would've never been added if I hadn't made the effort, and just as many that would've taken far longer to come about otherwise because no one else was available to attempt it.

That isn't really the part that bugs me. It's that I recall my willingness to drunkenly stumble my way through ideas that no one else wants to bother with was something that bugged certain people on here. Over-reaching, if I recall the phrase used. It was just...disheartening.

**Comment by mugling** [comment]
Mass issue closure is painful in enough in producing lots of notifications. The closure notes give some guidance as to possible next steps which don't include bumping. Comments that consist only of emojis tend to cause annoyance when they are emailed to contributors.

**Comment by chaosvolt** [comment]
Yes, I know. Granted, the next steps aren't really an option, given submitting a PR isn't an option even if I knew how to implement it, and no one seemed interested in the idea enough to look into discussing it.

This does gimme a question though. Were you following this issue beforehand? There was literally no discussion on implementation until it was closed.

**Comment by mugling** [comment]
Developers are by default subscribed to all issues and some contributors have also selected that option. For this reason try and avoid non-productive comments as they result in notifications (and often emails) that disrupt a lot of people without there being any realistic intention to progress on an issue.
