### ISSUE TITLE
Nightmares

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#139]
Very rarely when sleeping, save the game, spawn a bunch of monsters, wake the player up, and then upon their death or a timer running out, restore the previous save and wake them up with a vague message about waking up from a nightmare.

Complications: Player attempting to save or exit during the dream sequence.
##

**Comment by sparr** [comment]
maybe mental stats could improve in a dream?

implementation idea: use all the existing save code, but direct it to a memory structure instead of a file. If you real-save during a dream, that structure goes with you, embedded as a [huge] block within the save. dream within a dream left as an exercise for the compiler :)

**Comment by Dalenacio** [comment]
How about lowering stats and morale if they "fail" the dream? That would be proper incentive, I'd say.

Also, maybe make the dream differ based on how the player acts in "real life"? Like, say, the killed a bunch of zombie kids, now those kids come back to haunt them. So too with the NPCs they've killed and so on. Plus make things not quite "right". Zombies move faster if you're moving away from them (No running away in a dream!), they hit harder if there's emotion attached to them, like guilt to the children, or fear to enemies that have dealt a lot of damage to player, etcetera. And player damage should be based on morale, either when they are dreaming, either when they head to sleep (note: maybe this could also affect the probability of a nightmare happening), to make sleeping off massive morale debuffs a bit more risky.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
