### ISSUE TITLE
Improving item screen readability

### ISSUE THREAD

**Issue by Nandorianen** [CleverRaven/Cataclysm-DDA#13941]
Take a fully modded reflex recurve bow.
It is a ranged weapon, so it has about two dozens parameters related to that.
It's also a clothing item, so it has another dozen stats about that.
Then five lines of item description.
Then half a screen of text about mods.
All of this barely formatted with no easy hooks for the eye to navigate.

I'd like to suggest something like this.
1. Basic color-coding. Stat names should be of different color than the values. That alone would make it much easier to look over stats of any given item.
2. Advanced color-coding. Maybe stat names should have different colors depending on their type. For example, grey for generic ones (price, material), reddish for combat ones, greenish for armor ones, blueish for comestibles ones, etc.
3. Bullet points. Something like a colored [*] to indicate that this line is about some new property and not a continuation of previous text. Maybe a word for a category, like [mod:] before text regarding installed mod, [container:] for container description text, [item:] for item description, etc.
4. Better structure. Stats -> container description text -> damage when used as a weapon -> item description text doesn't look like a good structure.

Any thoughts?

**Comment by MehMuffin** [comment]
Maybe just a better organization here? Something like:

(Item name) (vol, weight, quantity, basic stats that are universal)
(Description)
(As clothing... Armor stats)
(As a melee weapon...)
(As a ranged weapon...)

With each section other than the first two only showing if it's actually relevant. Maybe for items with weapon and armor specific tags (sturdy, etc) those sections could be prioritized instead of always having armor stats last or whatever. Color coding wise, maybe just shade value names a little darker so the actual values stand out, maybe color each section differently but I dunno how I feel about that many colors.

**Comment by Zireael07** [comment]
The team is opposed to using colors too much because of colorblind players AND devs.
That said, pinging @Rivet-the-Zombie to see what she has to say about those ideas.

**Comment by Rivet-the-Zombie** [comment]
I think an improved format structure/markers would be the best route to take here, though colored text can be okay so long as we're not doing weird stuff with it like countershading the background or requiring the player to differentiate between similar colors to determine important information.

**Comment by OzoneH3** [comment]
@Nandorianen I opened a PR for this #14057. Maybe you could give some input.
