### ISSUE TITLE
Broken weather generation

### ISSUE THREAD

**Issue by tinoreo** [CleverRaven/Cataclysm-DDA#13965]
Weather generation seems to be broken in https://github.com/CleverRaven/Cataclysm-DDA/commit/16041b8b46820ca48f006bcfe07020392fc68cfb and newer.
It's always Flurries/Drizzle. No Perlin noise is generated, as you can see using «Display weather» tool in debug menu.
Savefile: https://mega.nz/#!Q50ChCIS!I4i6aLNZUsVF-gkjJeGAucycxtWrpCubyeYBoQo9My4
Mirror: https://yadi.sk/d/saY3OOWNkM6ai
Previous versions handle it well, creating dynamic weather.

I have tested different seed values in *.weather savefile.
If I change it to something like 10000, all works perfectly, but as it approaches to 100000000, non-drizzle areas become smaller and then disappear completely.
My build on GNU/Linux has MAX_RAND=2^31-1, so seed is nearly always greater than 100000000. Windows builds are not affected by this issue; it looks like they use MAX_RAND=2^15-1 and will never generate such seed. But if you load Linux-generated world in Windows client, you'll see the same constant Drizzle weather.
Tested on Debian 8 (g++ 4.9) curses and latest Windows curses/SDL builds from http://dev.narc.ro/cataclysm/jenkins-latest/Windows/

Simple fix in game.cpp:
```diff
- weatherGen.set_seed( rand() )
+ weatherGen.set_seed( rand() % 32767 )
```
I'm not sure if this is a good idea as I can't understand why large seed values was acceptable before this commit, but not after.

**Comment by DanmakuDan** [comment]
The Simplex noise generation is being skewed hard by large seed values. The other factors used in the noise generation are x-y coordinates and calendar time, where at game start the coordinate factors have a value between 0-2 (global position / 2000), and the calendar is around a modified factor of 100. The random seed factor needs to be lower, so that the other factors have some influence on the generated value.

It should probably be applying the same mod 32767 on game load also, to deal with previous saves.

I'm not sure if that commit is responsible for the problem, the code has been using the same seed factor for a while.

**Comment by kevingranade** [comment]
If it's behavior of the simplex noise generator, the generator should be
controlling what it accepts.  That might be what you're saying, it's hard
to talk about this stuff clearly sometimes :)

**Comment by DanmakuDan** [comment]
Some of the algorithm treats the values in a way that looks scaled relative to the 4 different inputs it gets. The seed could be modded by 32k or scaled by RAND_MAX at the point of input to the noise function, but it would cause inconsistent weather behavior if the save is moved between different OS's.
