### ISSUE TITLE
Builds on windows with MSYS2 (and possibly MinGW) can only use a constant version value.

### ISSUE THREAD

**Issue by remyroy** [CleverRaven/Cataclysm-DDA#13998]
There is a problematic preprocessor instruction in `version.cpp` on line 1 from [this commit](https://github.com/CleverRaven/Cataclysm-DDA/commit/6ef3034a):

```c
#if (defined _WIN32 || defined WINDOWS || defined MINGW) && ! defined GIT_VERSION && ! defined CROSS_LINUX && !defined _MSC_VER
```

It prevents MSYS2 and possibly MinGW builds on Windows from ever using the version value from `version.h`. The MSYS2 build will properly rewrite version.h to contain a good version value from inspecting the git repository.

It seems like it was added for CMake support. If some of the people working with CMake could help me with this, it would be appreciated.

My initial gut feelings tell me to revert the changes to `version.cpp` so it looks like this:

```c
#include "version.h"

#include "get_version.h"

const char *getVersionString()
{
    return VERSION;
}
```

but I might be wrong.

**Comment by remyroy** [comment]
This also begs the question. Where should the version number come from when we build? What is the unique source for that? Is it in the source code? Is it in the build process (Makefile currently has a variable `VERSION = 0.C`) ? Is it in the git repository tags/branches/info? Should it be manually enter by the person doing the build?

**Comment by kevingranade** [comment]
The cannonical source for versioning is git, see the makefile's version
target which uses 'git describe' to generate a version string.

**Comment by drbig** [comment]
Hmm, had no problems building on MSYS2... But then I tried that a couple of months ago.

**Comment by remyroy** [comment]
There is not any major problem with building using MSYS2 with the current source and instructions except that it does not support sound and the version number you get will always be `0.C`. #13995 improvises this with sound support and easier instructions.

**Comment by karlnp** [comment]
Hi, I did the CMake stuff. You should be able to construct the Git string from MSYS2 as well - this constant is actually for cross-platform Makefile/etc support as a fallback. I haven't looked at your new stuff though - if you did introduce a Makefile provision for Windows then you should be able to construct a version number in that context and add it as a compilation flag.

I initially made this change because we kept having bug reports from WIndows users who all had the same constant 0.C, but they were actually using experimentals with varying feature sets. This helped that issue a little.
