### ISSUE TITLE
Rifle range/hit chance need rebalancing?

### ISSUE THREAD

**Issue by qurvax** [CleverRaven/Cataclysm-DDA#14096]
I did some LR rifles testing testing yesterday, in the following environment: PERC10. ENC HANDS 20, ARMS 11, EYES 0. Skills: Rifles 8, Marksmanship 6. Lighting: brightly. Weather: clear.  To reliably hit a target (green Z) with a Barret rifle (with bi pod, extended barrel and suppressor attached) i had to close in to ~15 tiles.  It's seems a little to close, IMO, because Barret has like 135 (AFAIR) range with standard issue ammo. Other rifles seem to have similar issues too. I haven't tested advanced sights, but at medium range (2-3x handgun's effective range) there should be no problem hitting stuff using plain iron sights, even with arms encumbered by winter gear.

**Comment by sparr** [comment]
Despite the stat descriptions being misleading, Dex is just as important as Per for using ranged weapons. What was your Dex?

**Comment by kevingranade** [comment]
This is intended, but open to discussion.  If we set effective gun ranges
realistically, especially for rifles, there are two problems that will
occur, one is that the effective ranges for everything will be roughly the
same, which is max sight range.  The second problem is it makes guns
amazingly overpowered, since you can then hit consistently from a totally
safe distance, and just progressively retreat as much as needed to deal
with the entire threat you're facing.
That having been said, we could at least rescale effective ranges to use
the entire available space in the reality bubble.

**Comment by qurvax** [comment]
I think this should be closed, as there is 17643 now, with much more detail.
