### ISSUE TITLE
Persistent iterators

### ISSUE THREAD

**Issue by mugling** [CleverRaven/Cataclysm-DDA#14128]
As raised by @Coolthulhu in #13153 we don't currently have a mechanism for referring to an item across turns:

> The only real problem I see here would be extended actions, because the item can disappear. That said, the same problem already exists with extended actions in inventory due to inventory overflow.

We do have `item_location` but this is only guaranteed to be valid until the turn ends. An ideal **persistent** iterator:

1. Functions identically for items in the inventory, on the ground or within a vehicle
2. Can be queried to return the items specific location eg. `INVENTORY`, `MAP` or `VEHICLE`
3. Remains valid when an item is moved within one of the above locations
4. Remains valid when an item is moved between one of the above locations
5. Returns `NO_ITEM` when the referenced item has been destroyed
6. Persists across save/load

It would seem `item_location` already provides some of this functionality, certainly (1), probably (3) and implementation of (2) would be trivial.

We could gradually extend `item_location` to provide the missing functionality and start to use this in place of `item *` or `position`. The first steps could be:

- [ ] Implement `item_location::where()` returning `INVENTORY`, `MAP` or `VEHICLE`
- [ ] Implement copy constructor for `item_location`
- [ ] Returns `NO_ITEM` after the turn ends as validity cannot be guaranteed

In a series of merges we could then gradually reduce the circumstances in which we need to return `NO_ITEM` until we have completely fulfilled criteria (4).

In this way we can gradually correct the existing problem noted by @Coolthulhu and provide new functionality (eg. #13153 and #13907) without either breaking anything or having to change all of the inventory, map and vehicle code simultaneously.

Thoughts?

**Comment by Robik81** [comment]
Does persistent across turns means also persistent between save / load? Because it seems that item_location stores the item as a pointer.

**Comment by mugling** [comment]
@Robik81 yes, that would be a required behavior so I've added it above

**Comment by kevingranade** [comment]
My main question is whether it's necessary, it would certainly be convenient sometimes, but the use cases you give don't require it. #13153 *should* function by picking up the item, reading it, then either dropping it to holding on to it.  The convenience feature of dropping the book in the location it was retrieved from just needs to track the source location, not a reference to the item itself.  #13907 just treats target containers like any other crafting ingredient, I don't see how it needs persistence of references.

The other question is how you intend to implement tracking, any solution using pointers or std iterators will be incredibly fragile and when it fails it would introduce hard to track down crashes.
In particular, satisfying the requirement that it returns NO_ITEM instead of attempting to access the item is extremely difficult.  Your current heuristic of current turn isn't even safe in general, code using these iterators has to be carefully crafted to avoid invalidating them even within the same action.

**Comment by mugling** [comment]
> #13153 should function by picking up the item, reading it, then either dropping it to holding on to it

Fair enough, I'll implement it that way. Probably the same method would also work for reloading guns using ammo from the ground.
