### ISSUE TITLE
Add noise reduction between experimental z-level floors

### ISSUE THREAD

**Issue by DanmakuDan** [CleverRaven/Cataclysm-DDA#14123]
It's strange that you can hear stuff shuffling around underground, I feel like the dirt/concrete/etc should be reducing what can be heard from the surface. Could noise reduction be applied by overmap type?

**Comment by chaosvolt** [comment]
Are you sure that it isn't (also) loud noises being randomly positioned down a z-level? ._.

**Comment by Rivet-the-Zombie** [comment]
You can definitely hear stuff between levels way too easily right now, but I expect that will be addressed as Z-levels are further developed.

**Comment by Griffinhart** [comment]
This is *very* noticeable if you're standing over a lab (or, apocalypse forbid, a vault).

**Comment by nornagon** [comment]
Since the sound code doesn't take into account any terrain at all, there's not any obvious place to differentiate between "an NPC on the 2nd floor of a building with an open window" and "a soldier ant with 6 feet of dirt between it and the surface".

Given almost all sounds from another level right now are in the latter category, more or less, would it make sense to simply count each Z level difference between the source of the sound and the player as something like 20 tiles of X/Y distance?

I've made a PR that implements this approach, but I'm not sure if this is the right way to do it (or if 20 is the right number, I just kind of pulled that out of a hat).

**Comment by Leland** [comment]
@nornagon can you copy/paste that note into your PR? That's the appropriate place to discuss implementation details.

**Comment by nornagon** [comment]
Done.
