### ISSUE TITLE
Vehicles rotate around fairly arbitrary points

### ISSUE THREAD

**Issue by mutability** [CleverRaven/Cataclysm-DDA#14168]
Vehicles appear to rotate around the (0,0) point, which if I read things correctly is the first placed frame, regardless of the shape/size of the vehicle.

So it's possible to have two visually identical vehicles that steer completely differently.

Here's two bikes travelling left-to-right immediately adjacent to the centreline markers. The top one had the leftmost (rear) frame placed first, the bottom one had the rightmost (front) frame placed first. Both have turned counterclockwise one step. The top one has pivoted on the rear wheel, the bottom one has pivoted on the front wheel.

![vehicle-rotation-problem](https://cloud.githubusercontent.com/assets/3055062/11399041/abd319f2-937c-11e5-8651-bd9d47167e4b.png)

While working out where the vehicle should rotate around is a tricky problem (maybe we just need a pseudopart that can be placed to control the pivot point) it should at a minimum be _consistent_. Maybe centre of mass as a default?

If this is along the right lines I'll have a play with the code and see what I can come up with.

**Comment by Griffinhart** [comment]
>maybe we just need a pseudopart that can be placed to control the pivot point

I would actually *really* like a way to move the center/pivot point of a vehicle, if only to satisfy my OCD. (Most vehicles have their "center" on the driver's seat, which is really annoying on, say, 5-wide vehicles with an *actual* center.)

**Comment by mutability** [comment]
I have a prototype of this which works by translating the current pivot to (0,0) before rotating (so the pivot is always at (0,0) in the precalc arrays, and the nominal vehicle position is the pivot position)

Then there is a fixup needed for the case where the pivot moves. To avoid having stuff shift around unexpectedly, we only actually apply the new pivot (and the fixup) when the vehicle is next displaced e.g. when moving under power or when dragged.

It currently uses the center of mass as the pivot but it'd be easy to make it use arbitrary other points.

**Comment by Zireael07** [comment]
@mutability: Plz make a PR for that!

**Comment by mutability** [comment]
Sure, see #14185

**Comment by kevingranade** [comment]
I think I outlined this on the forums a while back, but I can't be bothered to find it, so why should you be? :)

Basically what you want for the pivot point is the er... "center of traction", in the case of a car with front steering, you want to pivot on the point in between the rear wheels, in the case of a semi cab, you want the "center of mass" of the rear tires.  The simplifying assumption is that the steering wheels are free to pivot (in reality they aren't but otherwise you really can't drag cars around, so let's make them work that way) and that non-steerig wheels are all parallel to each other and the dominant movement direction of the vehicle.

In a vehicle with all-wheel steering, it's a bit more complicated, in reality these vehicles switch modes, at low speed the front and rear wheels turn in opposite directions to reduce turning radius, at higher speed they turn in the same direction for lane shifting.  I don't think we want anything that complicated, so perhaps if all wheels are steering wheels set the pivot point at the center point among those wheels (the average coordinate)

This requires that you label certain wheels as "steering" or vice versa, so it's quite a bit more involved than your current approach, and I think your current approach is an improvement on the current code, but as far as I can determine the above is the best option that we should be working toward long-term.

**Comment by mutability** [comment]
The main issue (vehicle steering depending on their build order) has been fixed by #14185 so I'll close this. Another PR to do some stuff with steering to follow..
