### ISSUE TITLE
Repairing vehicles takes too many keypresses and is generally annoying

### ISSUE THREAD

**Issue by ZombiesAreUs** [CleverRaven/Cataclysm-DDA#14174]
Is it too far fetched to ask for new keybinding (maybe 'R'epair All) that would go through all the repairable parts and repair them one by one, interruptible as normal repairing?

**Comment by chaosvolt** [comment]
We've already had not one, but two general "this annoys me" suggestions shot down because @kevingranade doesn't want more options to be added.

**Comment by Griffinhart** [comment]
Protip: you can just hold down `r` (or whatever you have bound as "repair") and the interface will iterate over everything that needs to be repaired and repair it.

(This assumes you have the materials to repair any broken parts, and that you're fine with repairing using whatever tool the interface defaults to. I *think* installed vehicles welding rigs have highest tool priority.)

**Comment by Coolthulhu** [comment]
This could be relatively simple to write. Just pressing 'r' over and over almost-works, meaning most functions are already implemented. All it would take would be a long action doing this stuff.
And maybe interface, but I'd say "full repair" could be the default option since partial repair only makes sense when low on resources/time or at low skill (when you can't repair everything).

@chaosvolt Don't start this shit...
Going all "but Kevin doesn't want the game to be fun" won't fix anything. There are other people who will shoot down ideas that don't fit/are hard to implement properly/etc. For example, me (when I have the time).
If you've got problems with Kevin's decisions, explain your ideas more clearly, compare what we have to what we "should" have, explain what would we gain from it etc.

**Comment by chaosvolt** [comment]
Sorry about that. ._.

**Comment by ZombiesAreUs** [comment]
I already have an AutoHotkey script that I use to press 'r' every 150ms, but it's useless if there is a damaged part that cannot currently be repaired - I was just wondering if it would be feasible to check for stuff like this in the game, and make the whole process less tedious.

**Comment by chaosvolt** [comment]
Regardless, to get back on topic, it would be less awkward if replacing a broken part was split off into a different command. This would allow the whole "hold down r all day long" solution to ignore parts that are too far gone to be repaired.

**Comment by ZombiesAreUs** [comment]
However, there is also the issue of not having sufficient mechanics skill to repair parts in the early game, and 'ignore broken part' would not fix that one.

**Comment by Nandorianen** [comment]
Game could check for that and give parts you have inusfficient skill to repair lowest priority. That way when you get to any such parts you know you've repaired all you could.
However, there is a problem of being unable to manually select exact part in the exact tile if you try to at least partially automate this. So another button is still required. Something like "repair fixable" for general-purpose repairing (select highest priority non-broken damaged part) and "targeted repairs" (current "repair" button).

**Comment by mugling** [comment]
Appears to be stalled
