### ISSUE TITLE
Allow mods to override existing data entries (duplicate IDs)

### ISSUE THREAD

**Issue by Nandorianen** [CleverRaven/Cataclysm-DDA#14250]
Mods can add stuff or blacklist stuff. But what if I want to make a mod that just tweaks existing stuff?
Right now if I want to, say, tweak a bionic power cost, I have to alter core game files. What's worse, I have to do it every time I upgrade to a new build. That's pretty often, and these tweaks add up.
Such tweaking mods also can't be distributed easily, as they are essentially patches to dynamic content.

It would be nice if game could override core data with mod data when it encounters duplicate IDs instead of giving an error and ignoring this mod data completely.

Better yet if it could override on a per-variable basis. So that game could read, continuing above example, data for a given bionic, then encounter mod that says:
"id": "bio_lighter",
"act_cost": 75,
find existing "bio_lighter" chunk of data, find "act_cost" inside, override it with "75", leave everything else vanilla.
This would allow for a much long-lived mods than if Cata would just find existing "bio_lighter", delete everything you read about it, and then make a new entry with this "bio_lighter" data.
The latter would mean you have to copypaste all this data even if you only wanted to change one value, and then have this mod lag behind any core changes until you copypaste it again.

**Comment by sparr** [comment]
The current appropriate way to do this is with Lua code.

However, I do support the idea for partial overrides in json mods.

**Comment by chaosvolt** [comment]
I'm not fully sure what your issue is proposing, but I think I get it. Most items can be overridden, but have to overridden in full. Thing is, if multiple mods override the same thing, they compete with each other.

However, SOME entries have partial ability to add content without adding a full override. Item groups, both for normal item spawns and monster drops, are the first and foremost example of this.

Mutations also have a very specific, limited form of this. If it adds a list of martials arts, and a mod offers an override for that trait, any martial arts defined in the mod's version will be ADDED to that list, rather than overriding the old one.

This can be seen in the medieval mod. It contains overrides for Melee Weapons Training and Martial Arts Training. The first adds Medieval Swordsmanship, the second adds Pankration, but both work (and indeed HAVE to work) without re-listing the martial arts the traits offer by default.

**Comment by Nandorianen** [comment]
Competing mods is not a new problem. The solution is overriding mod content with mod content in a particular order, be it last modified date or a list user creates manually.
Martial arts example provoked another thought: it's good that we can add more to the list, but it may also be desireable to remove something.
Maybe data entries could have another property? "Override: true / false". If set to true, all set properties in this entry, including lists, will override core ones. If not, then lists will add up, other values override as normal.

**Comment by chaosvolt** [comment]
Thing is, the "load mod content in a particular order" idea solves very little at all.

For example, say you have two mods that alter solar panels. One makes them foldable (like one of the existing mods we have), the other makes them output more power. Both override the same vehicle part, but the end result will NOT be a foldable solar panel with increased output. One mod's change will overwrite that of the other.

**Comment by Nandorianen** [comment]
Not if you use per-property override that I am suggesting. Load order is only for situations when they both mod the same property.

**Comment by chaosvolt** [comment]
Hmm. That might work. If this was further supplemented by the option to ADD to a vanilla entry, if it's in list format.

Excellent example, the lists of weapons permitted by martial arts. If mods could have the option to add to that list without overriding it, I wouldn't have had to update the martial art overrides in Arcana mod, in response to the light-stick being added. Likewise, I'd have the option to add medieval mod weapons to existing martial arts without them conflicting with the same alterations made in arcana mod.

**Comment by remyroy** [comment]
Here is an idea. Take it for what's it's worth.

Instead of replacing item, what about adding the possibility of disabling an item and adding an equivalent item (which can be used in the same way, with the same recipes, same disassembling, same construction, same activating). It might already be possible to do that by blacklisting the original item, copying it and tweaking the copy. This way if mod A wants to replace item X, it can add an item X1 and if mod B wants to replace the same item X, it add an item X2.

One of the somewhat hard part would be to add an alternate item to every crafting recipes that use the original item, to the world generation items, monster drop, etc. Maybe that could be eased with utility functions for mod authors. An alternative would be to use something like what minecraft mods are doing which is called `ore dictionary` where equivalent items are added to a table and can be used in various places like crafting or loot tables.

**Comment by mugling** [comment]
The `copy-from` syntax is a 90% solution to this. It needs only extending slightly to be able to fully support this

**Comment by mugling** [comment]
For example the following would double the capacity of the acetylene torch:

```
"id": "weldtank",
"copy-from": "weldtank",
"type: "MAGAZINE",
"proportional": {
    "capacity": 2.0
    "count": 2.0
}
```

**Comment by mugling** [comment]
Following #19020 this is now pretty much complete
