### ISSUE TITLE
Ignore noises while reading a book.

### ISSUE THREAD

**Issue by lekto** [CleverRaven/Cataclysm-DDA#14272]
If I'm reading book and I hear noise, I press 'i' (ignore). If I hear noise again after message 'You learn a little about...', I must press 'i' again. After message I must press 'i' over and over again.

**Comment by drbig** [comment]
This seems to belong to the long-term thread of "more flexible ignore of interruptions".

**Comment by sparr** [comment]
we already have this level of flexibiity in some other interruption prompts, so I'm not sure we need a new feature here, just getting that feature available in all interruptions?

**Comment by scorpion451** [comment]
I'd call this one sort of a necessary annoyance, like having to toggle safe mode all the time. When I'm in a place I know for sure is safe but noisy (say, reading to pass the time while my turret-studded deathmobile thins out a horde) I'll just pop in a pair of earplugs. If I'm not 100% sure I'm safe, I'd rather hit return a bunch of times than die because I didn't get alerted about that new, different sound from the west.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
