### ISSUE TITLE
Forestry skill

### ISSUE THREAD

**Issue by RafeHaab** [CleverRaven/Cataclysm-DDA#14276]
I noticed there are a few parks and empty areas inside the cities, where a player could plant trees to later obtain wood.

It could be added to the skill list, along with a few more books, or a class to go with it.

**Comment by Coolthulhu** [comment]
I'm against making it an entire skill (it would be a very empty skill, useless for vast majority of characters), but planting trees itself could be an option.

The problem with growing trees is that we'd have to make it "unrealistic" because we have to pick one of the options:
* Growing trees would be a separate terrain type. Trees not planted by the player would never grow
* Young trees would grow and within few months of gameplay no young trees would exist
* The above, plus adult trees randomly reverting into young trees. This would screw young/adult tree ratio and make some fruit trees inaccessible at random.

**Comment by chaosvolt** [comment]
Hmm. If trees could die off and reproduce on their own, we could have option two without resorting to option three. But while I'm in favor of that idea, two caveats.

One, I'm not sure it warrants a separate skill. Unless it was rolled up into a planting/farming skill in general, but that would have to be fleshed out in logical ways, like having it allow players to estimate how old a growing plant is based on their understanding of the crop being grown. Even then, unsure if it'd warrant a skill.

Second, trees might be one instance where we'll want longer, multi-seasonal growth. Farming as it is is still impractical because not many characters survive to see it into completion, and it's often better to resort to a hunter-gatherer existence at the moment. Tree growth would be skewed even more, especially as trees are abundant in the wilderness and wood doesn't rot.

**Comment by sparr** [comment]
Have trees disperse seeds, so forests can spread on their own. I'm thinking the life cycle might be at least a few game years.

**Comment by chaosvolt** [comment]
Yeah. Seasons would be a bare minimum, 

One workaround would be to have young trees set to grow after a certain certain, using the same mechanics as berry bushes/fruit trees becoming harvestable again over time. However, at a bare minimum you'd want to split up young trees into multiple variants, so each seasonal hit to it advances it until an arbitrary number of cycles.

As for seeds being spread by trees...maybe we could simulate reproduction by adapting the fungal terrain or the haze-creating creatures, except instead you use a field that drifts and alters the terrain if it's over a suitable spot upon deciding to stop drifting.

Ideally, the FIRST cycle would be just a planted seed, that advances into the first cycle of young tree next year.

After that, we'd need mechanics to allow trees to die off, and for them to avoid gradually choking all available dirt in saplings.

**Comment by Coolthulhu** [comment]
> As for seeds being spread by trees...maybe we could simulate reproduction by adapting the fungal terrain or the haze-creating creatures, except instead you use a field that drifts and alters the terrain if it's over a suitable spot upon deciding to stop drifting.

No, that would be too much overhead.
It would need to be something built around terrain, overmap etc.
Things like comparing tree counts of neighboring overmap tiles, counting eligible grass tiles.

> However, at a bare minimum you'd want to split up young trees into multiple variants, so each seasonal hit to it advances it until an arbitrary number of cycles.

That would be messy as fuck. Having 30 terrain types just to represent growth stages would be hard to maintain (if anything changes) and ugly.

**Comment by chaosvolt** [comment]
True. Those would be overall rather messy workarounds really. ^^"

**Comment by sparr** [comment]
We could just add a couple of bitflags to TER_BITFLAGS. Two flags gets us four tree growth stages if we wanna be complicated with it, or three stages if we just want "TFLAG_YOUNGTREE" / no flag / "TFLAG_MATURETREE". This would replace the existing distinction between young and not-young trees as separate terrain types.

Then trees can grow at random, on a global timer. If there are 3 stages after being planted as a seed and we simply upgrade each tree with 20% probability once per season then the average tree will become mature in 12 seasons, with <1% of trees maturing in 3 seasons or >45 seasons.

**Comment by Coolthulhu** [comment]
> We could just add a couple of bitflags to TER_BITFLAGS.

That would still require adding 30 terrain types just for growing trees.

**Comment by sparr** [comment]
Only if you want JSON mappers to be able to create trees of each type and age. C++ mapgens could set the flags in code.

Or we could extend the json map format to allow those flags to be specified.

**Comment by Coolthulhu** [comment]
How do you want to mark a tree as growing without a separate terrain id for it?
You can't set a flag to terrain instance, only to an entire terrain type.

**Comment by kevingranade** [comment]
The question then is whether it's easier to handle that in the drawing or
interaction code or by increasing terrain types.
Either way I'm skeptical that it would be worthwhile to display anything
beyond 3-4 age categories per tree type. (Sapling, young tree, mature tree)

**Comment by sparr** [comment]
@Coolthulhu ahh, I got confused about terrain instances vs terrain types.

On that front, the data would have to live in the map, and that's getting into a big can of worms.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
