### ISSUE TITLE
Allow some recipes to be crafted in the dark, with enough skill

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#14285]
This idea was spawned on IRC by Soadreqm.

I can fold an origami crane in the dark. I've assembled a piece of IKEA furniture with my eyes closed on a dare. There are a few factors in what makes this possible, that shouldn't be impossible to represent simply in the game.

First is how good you are at the craft in question. I'm thinking this would be represented by simply bumping up the skill level requirements. A fabrication 1 recipe during the day is fabrication 2 in low light and fabrication 3 in the dark.

Second, and a more strict filter, is to simply identify which recipes are possible at all without being able to see what you're doing. Off the top of my head, I would put these in two categories, identified as flags or members of the recipe struct.

BLIND_EASY recipes are the ones that can be done from muscle memory alone, without even slowing down. These are the things your crafty friends do while they are conversing with you, without even looking down at their work. Stirring food together, knitting, etc.

BLIND_HARD recipes are the ones where you have to replace seeing with feeling. You're using your fingers to line up holes, find edges, etc. This is me folding origami in the dark. These would suffer a time penalty in low light and dark conditions, probably a significant one.

Comments, suggestions, objections welcome.

**Comment by kevingranade** [comment]
As long as it's a whitelisting approach like you're suggesting, I have no
objections.
We can hash out which recipes go where with a small number of examples.

**Comment by Coolthulhu** [comment]
Rather than tag, a floating point modifier on crafting speed in darkness could be better. It would make things less hardcoded and more obvious for players.

**Comment by Soadreqm** [comment]
I think a whitelist approach might be better. At least if we're going for realism, and not convenience. Like, a lot of recipes look like they probably involve measuring precise distances, or amounts. Those should be flat out impossible to even attempt in pitch darkness. You can't do chemistry if you can't see what you're mixing.

And on the flipside, some look like they'd be relatively easy. Like knitting a scarf. If you know how to knit, you don't really need to see what you're doing once you get started. It'd be harder blind, but the time increase would be smaller than expected, since the bulk of the work is just repeating the motions. Or making a rock-in-a-sock. If you have a rock and a sock in your inventory, in such a way that you can reliably locate them both, you're basically done.

Besides the rock-in-a-sock, my picks for the EASY category would be hand-rolled cigarettes and joints. I'm also thinking of some metalcrafting recipes, where the tools you're using to melt down the steel should also provide the light.

**Comment by sparr** [comment]
it looks like recipes don't currently have flags. should we start a new trend, or should the easy/hard/impossible go into a new field for recipes?

**Comment by kevingranade** [comment]
Since it's not a core stat of a recipe, I'm leaning toward a flag.
