### ISSUE TITLE
JSON Mapgen Suggestion

### ISSUE THREAD

**Issue by vache** [CleverRaven/Cataclysm-DDA#14293]
It would be interesting if we could wrap some probability checks in JSON mapgen and group features together based on some random chance, something like:

```
"chance": {
    "one_in": 4,
    "place_items": [
        { "item": "tons_of_guns", "x":3, "y":3, "chance":100 }
    ],
    "place_furniture": [
        { "furniture": "gun_safe_locked", "x":3, "y":3 }
    ]
}
```

or

```
"chance" : {
    "x_in_y": [ 3, 20],
    "place_monsters": [
         { "monsters": "big_dog", "x":10, "y":11 }
    ],
    "place_furniture": [
        { "furniture" : "dog_house", "x":12, "y":9 }
    ],
    "place_signage": [
        { "signage": "Beware of Dog!", "x":14, "y":14 }
    ]
}
```

This way, we could let JSON mappers specify alternate features without having to create entirely new mapgens.

**Comment by sparr** [comment]
There have been a few other discussions about this previously. The general approach to making this work would be to add functionality to the core Json data types (JsonObject, JsonArray, etc) that would perform the random weighting as soon as they are instanciated, so the randomness would be transparent to the functions reading the contents.

**Comment by vickio** [comment]
I like this idea. Would be great to see more ways to add random variation within maps. A lot of the bigger structures are great, but feel static after you see them a couple times.

I'd also like to see something like the syntax you're describing for probability (`"one_in":` and `"x_in_y":`) added to existing JSON spawn declarations. Currently **individual items**, **liquids**, and **monster groups** are one in x (making it impossible to specify 51-99% probability). **Vehicles** are x in 100 chance to spawn. **Individual monsters** are always 100%, with no probability option. And **item groups** are x in 100 chance that a loop will continue to spawn items from the group (which itself may spawn multiple items or not depending on its type and item probabilities, which themselves have different probability specs depending on the group type), unless the chance is 100, in which case it will trigger the item group spawn exactly 1 time. It's kind of a pain.

**Comment by kevingranade** [comment]
The json types have no business knowing about that. It might seem or
actually be easier to conflate that functionality, buy it is the wrong
thing to do.

**Comment by sparr** [comment]
What if we make a set of wrapper types around the json types?

RandomJsonObject
RandomJsonArray
etc?

Having written that out, it's probably the wrong layer at which to apply the logic anyway. We don't want to change how every hospital looks at load time for the json file. We want to change it when each hospital tile is generated.

I guess a better solution would be to use weighted_list and some sort of random_or_null_list for these situations, similar to what I did for random sprites?

**Comment by kevingranade** [comment]
Yea, that sounds reasonable.  I just had a knee-jerk reaction to bundling
semantics with the json code.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
