### ISSUE TITLE
Implement compression of saved games

### ISSUE THREAD

**Issue by ZombiesAreUs** [CleverRaven/Cataclysm-DDA#14307]
Is it necessary to have so much fragmentation in the save folder? Backing up old saves is a nightmare, it takes forever to copy or zip them.

**Comment by sparr** [comment]
40000 files suggest you've explored most of a 200x200 OMT area of the map?

**Comment by IronyBeMyShield** [comment]
Well, they did say *old saves* and IIRC roads maps and such will generate maps. I somehow have a day old save with 4k files in it already.

**Comment by kevingranade** [comment]
While not absolutely necessary, it would be extremely painful to change,
requiring every save to be migrated. Also I'm not at all sure that simply
increasing the file size by 2x to 4x is going to fix the problem you're
seeing. (More than that could lead to the game becoming unresponsive due to
having to handle larger files).
Something we might be able to do is compress map data that is far from the
player. The nearest 4-9 overmuch worth of map data could stay as they are,
and the rest could be concatenated and compressed into one file per overmap.

**Comment by Zireael07** [comment]
Compressing the data that's far from player is a good idea, Kevin.

**Comment by Vsevolod-Shustov** [comment]
May I suggest using something more advanced than files for storing saves? NoSQL DB looks like a natural choice for thousands of JSONs.

**Comment by sparr** [comment]
Find a NoSQL db that builds quickly on all the platforms cataclysm is played on and we'll talk.

On a more realistic note, sqlite might be viable.

Or, even less divergent from what we have now, there are drop-in libraries for treating a zip file as a folder, reading and writing files in it directly.

**Comment by mutability** [comment]
I have no problems with a 7k-file save here (Linux), it backs up in a couple of seconds, and it's certainly simpler to just have it direct on the filesystem.

```
$ time zip -r test.zip save/Kimberly
[...]
real    0m2.006s
user    0m1.738s
sys     0m0.221s
$ find save/Kimberly -type f | wc -l
6843
```

@ZombiesAreUs: What OS/filesystem are you using that you see problems with? How long is "forever"?

**Comment by kevingranade** [comment]
Adding a database is one of those solutions that ends up with, "now you
have two problems". Turning the saves into a database would require
rewriting all our serialization and deserialization code, make saves
unreadable without installing tools, add build and deploy dependencies and
require developers to learn how to use whatever database. On the plus
side... no idea, I'm not at all confident it would speed anything up, and
I'm certain it would increase the disk usage.

Fundamentally, what databases are good at is concurrent access to data, we
don't have any concurrency, so a database has tradeoffs that we don't take
advantage of.

I suspect the problem is windows' crappy filesystems.

**Comment by sparr** [comment]
To be fair, various linux and osx tools also behave poorly when pointed at directories containing tens of thousands of files.

How about something like these?

http://users.telenet.be/tfautre/softdev/zfs/
https://github.com/fgenesis/ttvfs

**Comment by kevingranade** [comment]
If we want to compress the saves, that's trivial, and bundling them would
be fairly easy, I don't see where an external dependency is necessary.
Any particular reason the 100 or so LOC solution I outlined wouldn't work?
I'm favoring a targeted solution here, not overhauling the whole save
infrastructure.

**Comment by pouar** [comment]
> To be fair, various linux and osx tools also behave poorly when pointed at directories containing tens of thousands of files.

I used to have this problem with some graphical file managers in the past, but not anymore

**Comment by DanmakuDan** [comment]
Minecraft switched to a region-based file format a few years ago (32x32 chunks, chunks usually being 4-5kb compressed files of 16x16 tiles) because of similar issues with Windows being slow in handling thousands of 4-5kb files.

**Comment by ZombiesAreUs** [comment]
@mutability 
Yep, my OS in Win7 and I use winrar so that's probably part of the problem. "Forever" is about 10 minutes.

**Comment by remyroy** [comment]
@ZombiesAreUs Compressing your save folder could still be faster and a good workaround until another solution is found. I would try using [7zip](http://www.7-zip.org/). Compression is also a good idea for archiving which seems to be the purpose of this backup.

When compressing, there could be less I/O operations than copying which could make the whole process faster. Different compression settings might yield different speedup. Even using a compression level which only `store` the files (not compressing them) could be faster. I would try many compression levels and compare them with the time it takes to copy the files using the regular windows copy. High compression levels could even be faster if files are even more compressible and if your CPU/memory is quite faster than your disk I/O operations.

It is not uncommon for memory access to be 80x faster than disk access for HDD. Using normal compression settings, I was able to compress a 12.1 MB save folder to a 336 KB file. In my example, writing a 336 KB file should be much faster on a slow HDD than bunch of files with a total size of 12.1 MB. In my case, it's so fast I can't even tell the different but I'm using a good SSD drive.

**Comment by Vsevolod-Shustov** [comment]
> winrar

Eww. I found out that 7zip on any setting other than "store", ie ones with actual compression, is lightning fast compared to store or just copying folder. There is also "update and add" mode that makes backups even faster.

**Comment by Malkeus** [comment]
I'm a fan of the way it turns 90mb saves into 3mb zip files.

**Comment by Coolthulhu** [comment]
It's all plaintext.
Adding a simple compression would allow making the files smaller, but reducing their number would take some more creative approach.

**Comment by SeanMirrsen** [comment]
I like the "compressing stuff far away from the player" thing. Maybe do it like Bethesda games and split the world into reasonably-sized chunks (10x10 overmap tiles, for instance), and compress all chunks the the player isn't in. Make it a tiered sort of thing, so that the whole of the overmap isn't unpacked and repacked when the "decompression bubble" needs to shift.

**Comment by illi-kun** [comment]
Superseded by new discussion thread.
