### ISSUE TITLE
Melee technique for adjacent targets

### ISSUE THREAD

**Issue by mugling** [CleverRaven/Cataclysm-DDA#14314]
Large bladed weapons should be able to attack multiple adjacent targets (similar to axes in DCSS).

This would help to further differentiate piercing and cutting weapons in that the former would be more useful for engaging a single monster and **some** of the latter for crowd control.

The mechanics would be that on a successful hit monsters adjacent to both the player and target would also take 10-20% of the usual damage output. For balance this would be best applied to slower weapons.

If there's general consensus this is an interesting idea I'll implement the code and then we can start adding it to suitable weapons and address also balancing.

**Comment by Coolthulhu** [comment]
Wide strike does that.
It's just that it's really bad because it has a move cost penalty attached, making it more risky than hitting the targets separately.
Plus, only heavy weapons have it and multiplicative move cost penalty on heavy, slow weapons is ultra-bad.
Finally, slow, heavy weapons (the only things that have wide strike) are currently quite bad, to the point where using fists over fire axes is a good idea if you ever intend to dodge.

Just buffing wide strike and heavy weapons would be enough, no need to add extra mechanics where ones that are supposed to do it already exist (just don't do what they're supposed to do).

**Comment by mugling** [comment]
> Wide strike does that.

That I didn't know. I'll start work with the fire axe then.

**Comment by mugling** [comment]
@Coolthulhu by any chance did your recent PR fix this?

**Comment by Coolthulhu** [comment]
I think it should make it better.
Still, many weapons that could have AoE attacks don't have them. Axes without wide strike etc.
