### ISSUE TITLE
See the origin of objects. (Mods, Vanilla etc)

### ISSUE THREAD

**Issue by DeadLeaves** [CleverRaven/Cataclysm-DDA#14328]
It would be great if there were a way to tell where an object originates from. Is that item from a mod, if so which? Is that monster from a mod... etc. 

I discussed it a bit in IRC and the few active people seemed to like the idea, we came to the conclusion (But clearly it could use more discussion) that the most elegant way would be to append "[Added by mod x]" to the end of an objects description during mod loading. 

And while I think it's a great idea, some people might not. So an option would probably be the best IMO. (Although people seem to dislike more entries in options)

**Comment by etmoonshade** [comment]
Options are just that - you set 'em once and forget 'em. Default it to off so it doesn't break immersion for the sort of people who are into that thing, but I'd love to have the option.

**Comment by kevingranade** [comment]
Why not add a source field to the item class instead?
Adding to the description field would invalidate all the item translations.

**Comment by etmoonshade** [comment]
The general thought, as we discussed it, was to avoid adding any fields unless necessary. The beauty of appending to the description is that (in theory) it doesn't require any extra variables/fields/whatever that would need to be handled.

That said, the reason I was thinking of that in the first place (yeah, I'll cop to the idea of appending to the description) is that I recall talking about how adding fields to map data would bloat things. This is obviously a far smaller scale, but every little bit presumably counts. Obviously I didn't consider the translation thing.

**Comment by sparr** [comment]
The mod name could/should be added post-translation.

**Comment by illi-kun** [comment]
For me, such info should not be important for player. This is kind of debug info and I think we need option (off by default) or any other (better) way to hide it from the end-user who just play and don't care about internal structure of the game.

**Comment by Coolthulhu** [comment]
Items get some extra info when viewed with debug mode on.
This could also be shown like that.

**Comment by Zireael07** [comment]
This is a good candidate for debug mode info indeed.

**Comment by DeadLeaves** [comment]
While I agree that it's useful for debugging, I belive end-users would appreciate it aswell (I consider myself more as a player than dev for sure, and as far as I understood so does etmoonshade) because its very easy to simply not know what mod adds what once you run few of them. Especially in a game like CDDA where there is a massive amount of items, and items from mods periodiaclly gets added to the core game. (See suvival tools mod)

**Comment by kevingranade** [comment]
There are two things getting conflated here. One is adding fields to the
item json entries.  The other is aging a field to the item itself
(specifically to the itype object).
Adding a field to the itype object does not mean we have to add a field to
the item json entry. We void Stull infer it from the Liang process.

**Comment by sparr** [comment]
@illi-kun this isn't just internal structure. Consider this: A player wants to start a new world with different mods than their previous world. They are surprised when their new world doesn't contain some item or skill that the old world did, because they didn't know it came from a mod.

@kevingranade Some of us are talking about implementing this without adding a field to either place.

**Comment by kevingranade** [comment]
Let me be clear then. We will not be appending anything to the description.

**Comment by illi-kun** [comment]
@sparr For me, such kind of info just kills atmosphere of the game. Various properties & description of the item shown on your screen it is what _your protagonist_ knows about this item.

**Comment by DeadLeaves** [comment]
So, just leave the option on "off"?

**Comment by sparr** [comment]
OK. Kevin has spoken, so it's not going in the description. That leaves a new field on the item class.

Should this be a string, or something more complicated?

If it's a string, should it just be the normal name of the mod, or something else?

**Comment by kevingranade** [comment]
It could easily be a pointer to the structure holding the mod data, short
of that it's string I'd that can be used for looking it up.  There's no
good reason to store any mod data in the item.

**Comment by sparr** [comment]
I like the idea to point to a structure for the mod data. I'm gonna try to tackle that, I think.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
