### ISSUE TITLE
some vehicle parts take up more space than they should

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#14320]
A lot of vehicle parts take up the "center" location when that doesn't seem really appropriate. The one I have in mind immediately is the water purifier. It's a handheld battery powered device. In real life such devices are the size of a couple of liter canteen (and include a canteen). That's the sort of things I should definitely be able to stick into a spare corner of my vehicle without it blocking whatever else I'm doing there. Notably, it should easily fit in the same square with a funnel and a water tank.

I'd like to look into an audit of vehicle part locations in general. If there's support for this idea, I'll come back with a longer list of concerns.

**Comment by kevingranade** [comment]
Sounds good, I don't think you're going to be stepping on any toes, the
current settings are pretty ad-hoc, especially the accessory type things.

**Comment by sparr** [comment]
ok, before I get started, would it be appropriate to contemplate upgrading the "location" field to a list, so that a single item can fill multiple locations? this might somehow merge with vehicle part flags; would there be a reason to have an item fill the "roof" location without also triggering all the behaviors of the "ROOF" flag?

**Comment by mugling** [comment]
As part of your audit you might consider restricting each engine to one alternator rather than allowing therm to stack, especially now that #14202 is merged

**Comment by kevingranade** [comment]
Re: list, you'd pick a part to install, then pick a location?
Seems like it'd get complicated to juggle locations around to get what you
want out of a vehicle layout.
Just to mention it, one of the previous suggestions was to have vehicle
slots have variable capacity.  This would be a more flexible way to manage
installation limits, and lessen the conflation of location and capacuty.

**Comment by sparr** [comment]
nah, I wouldn't ask the player to pick a location. it would still work as it does now, disallowing placing of components that both fill the same location. however, I'd make the locations a bit more fine grained, and maybe add the ability for some locations to hold N items. no item would have a choice about which locations to fill, though. that's still not perfect, but it's a lot closer than now, I think;

**Comment by scorpion451** [comment]
I'd personally like to see a combination of the two ideas, where parts are layered based on vertical  volume, sort of like how clothing works for the player.

If you look at, say, "cargo space" equivalents in vehicles in the real world, there are a bunch of ways to have a flatbed-type "empty space with ways to strap stuff down" type storage area. You can have them on the floor inside a cargo trailer, or raised above smaller "box" type storage spaces on a flatbed truck, or on the reinforced roof of a military transport, or slung underneath a bus like a cargo bay...in extreme cases like some military transports you can even have an internal cargo area and a second one on the roof. 

The real limiting factors are that anything taller than it is wide is going to have stability problems, and at a certain point you start hitting the structural limits of the materials. (ie, you can put cargo rails on the roof of a Fiesta and strap a full sized sofa to it, but good luck with that when hitting a pothole on the highway.)

The maximum for standard road vehicles seems to be ~15 ft for vehicles to safely fit under overpasses and through tunnels, and it seems like self-powered things top out at ~25 ft with [[https://en.wikipedia.org/wiki/Crawler-transporter NASA's crawler-transporter]] (not counting the arms on cranes or what have you), so that + the height of a cargo space could be the "hard limit" for how much you can cram onto a single tile.

**Comment by Coolthulhu** [comment]
Having parts take variable spot could be a pain to implement, unless it would be just about duplicating entries with different locations.

If we're fixing parts being too big, it could be a good idea to fix parts being too small. Currently there is no reason not to fill all internal tiles with batteries, plating etc.
Having a strict part volume limit per tile could prevent stuff like the infamous cargo carrier unicycle.

**Comment by mugling** [comment]
Implementing an `INSIDE` vs `OUTSIDE` property for `CARGO` parts would be interested but I have no idea as to how practical this would be to implement.

**Comment by Leland** [comment]
Has been stalled for yonks, closing. As ever, if there's still an interest in discussion/development feel free to ping me to reopen!
