### ISSUE TITLE
[Suggestion] Bulk/Batch disassemble

### ISSUE THREAD

**Issue by etmoonshade** [CleverRaven/Cataclysm-DDA#14330]
When you've got hundreds of lumps of steel and need a pile of scrap metal for wires instead, disassembling it all gets... tedious, to put it politely.

I can think of two ways this could be done; either wrap it into the "B"utcher menu, or add something to advanced inventory that will let you "B"atch disassemble a pile.

The "B" menu already seems to have a similar functionality - you can "cut up all you can" when you're over a pile. Just add "disassemble all you can" and you'd be sorted.

Sticking it into advanced inventory lets you limit it to only disassembling a single item type at a time, and could also presumably limit your batch size like crafting batches. Still though, hitting a set of keys 5 times instead of 100 times is a huge improvement.

**Comment by Coolthulhu** [comment]
There are some problems with mass disassembly. Nothing critical, but still:
* Marking what to disassemble: going by item indices should work most of the time, but it will always have cases where it will not
* Option spam, like in mass crafting (that is, having to confirm you want to use "soldering iron (nearby)" rather than one on your person)
* Disassembling stuff on the ground - especially not under the player - could lead to cases where a NPC, fire or something like that removes the item. This can happen already so it's not a big deal, but it would be nice if didn't get worse

There are also three separate ways to handle mass disassemble:
* Batch disassemble. Disassembling multiple copies of the same item. It isn't implemented in any way, so this one would be quite hard.
* Disassemble EVERYTHING on this tile. This one would be easiest to implement: simply disassemble the first item on the pile until the pile is empty.
* Disassemble everything here just once. This one would require tracking what is to be disassembled.

Batch disassembly (disassembling multiple copies in one "pass") would probably be quite prone to problems, so I'd say the other two options would be preferable.

**Comment by Griffinhart** [comment]
How does batch butchering work currently? Seems like that mechanic is good enough to clone for batch disassembly for now.

**Comment by Coolthulhu** [comment]
Batch butchering doesn't exist yet.
Batch salvage (cutting) works like the "disassemble EVERYTHING" - it picks the first salvageable thing, cuts it up, waits and then restarts the process. It ends when no salvageable thing exists.

If you could cut things down more using salvage, it would always reduce the whole stack into the simplest materials. For example, if rags could be cut into threads (they have to be disassembled now, so it's not a problem), using "cut all" on a stack of clothing would cut it to rags and then those rags to threads.

**Comment by Nymall** [comment]
Really? From my experience, the butcher all option only reduces any item on the tile to the first level of salvageable thing. It doesn't cursively reduce [Shirt->rags->string], it only goes to rags, until the next butcher command.(Exp 3995)

While on a slightly different topic, I'd also love a way to unload everything from a stack. Would make producing yeast a less button-intensive task.

**Comment by Griffinhart** [comment]
>Shirt->rags->string

Don't think `rag` is butchered into `string`; it disassembles.

**Comment by Nymall** [comment]
Sorry about that. You're right. I seem to remember accidentally butchering rags with "butcher everything you can", but apparently that's wrong.

**Comment by Coolthulhu** [comment]
You can, however, butcher thread for rags (it is a bug).

**Comment by mugling** [comment]
@Coolthulhu did you not recently implement bulk disassemble?

**Comment by Coolthulhu** [comment]
Yeah. There is no batch disassembly yet (opposite of batch crafting), but I guess it can be considered solved.

If not, then reopen.
