### ISSUE TITLE
[Suggestion] Make rainwater clean after some time

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#14341]
Main reason for making rainwater dirty nowadays is industrial and agricultural pollution. After the Cataclysm struck there is obviously no pollution from these means. I'd say that after first season length in the game the rainwater can be considered clean - practically no bacteria or viruses and no chemical pollution.
This might ruin the game balance, of course, if all that survivor needs to get clean water is a container, funnel, and some rainy day. But I think that if this survivor manages to survive for one season, then finding clean water is no problem for him.

**Comment by remyroy** [comment]
I don't think this is an interesting reason to make rainwater clean. Current water usage/crafting/gathering is good.

**Comment by Coolthulhu** [comment]
There were acid rains in the game not that long ago. I'd say that it implies there is something else polluting the environment now.
The pollutants in water are implied to be of organic nature, because just boiling the water is enough to kill them. And massive fungal infestation would probably make it worse.

It would be a bit weird on the mechanics side (like vehicle funnels redirecting to clean water tanks), but that's excusable.
No problems on the balance and code sides, I think. It doesn't sound hard to implement and by second season water is no longer a problem.

**Comment by Night-Pryanik** [comment]
>I don't think this is an interesting reason to make rainwater clean. Current water usage/crafting/gathering is good.

It's not much of interest, but of realism. Our ancestors two centuries ago used to drink raw rainwater, because our atmosphere and soil were much cleaner than now.

>There were acid rains in the game not that long ago. I'd say that it implies there is something else polluting the environment now.

Is there something lore-friendly I missed that is causing them?

>The pollutants in water are implied to be of organic nature, because just boiling the water is enough to kill them. And massive fungal infestation would probably make it worse.

To my knowledge, there is virtually no amount of organic pollutants in water that is condensed high in the sky.

**Comment by IFailAtGaming** [comment]
there actually is a lore reason for the rain if i remember right/ it wasn't retconned.
some of the portals started spewing out chemicals after the bombings/ self destruct/ whatever thing that made them go boom happened

**Comment by narc0tiq** [comment]
I believe @IFailAtGaming has it right -- if I recall correctly, the acid rains are meant to be caused by (some of?) the otherworldly portals. I definitely recall there were, at one point, future plans to bring back acid rains while keeping them to the region near said portals.

Thus, on a similar note, we could claim the contamination of rainwater to be caused by The Blob, which is the agent of the zombie part of the Cataclysm to begin with, and known to be omnipresent in the post-Cataclysm world.

As to the suggestion itself, if we want to implement it, I'd suggest a year feels like a better timeline to clean rainwater -- in game terms, surviving one's first year sounds like a good achievement for which to reward players with easier-to-acquire clean water. Not that it's hard to obtain in the first place.

Which brings me to my big question: is this worthwhile? We're talking about, at minimum, some code to gradually decrease the toxicity of rainwater (not very high in the first place) and behave sanely once the rainwater reaches clean water level -- code which introduces opportunities for new bugs, and which must be maintained -- the reward for this doesn't seem worth it. The dirty/clean water mechanics currently extant are not intended to be particularly cumbersome to players, while still being an interesting resource to manage.

**Comment by etmoonshade** [comment]
An interesting read someone linked me to on the wiki: http://www.wiki.cataclysmdda.com/index.php?title=Timeline

In short, @IFailAtGaming has it right - the portals are actively spitting varying degrees of gunk into the air. Presumably not enough for regular rain to kill you from skin contact, but probably enough that drinking a serving of it would introduce enough toxins into your system to make you sick.

**Comment by Night-Pryanik** [comment]
@narc0tiq No, it's not worthwhile in terms of gradually decreasing dirtiness of rainwater. Simply "make rainwater clean after X amount of time" should be enough imo.

All my idea was "little coding for little realism". If it's big or potentially buggy coding, it's definitely should be ignored.

**Comment by chaosvolt** [comment]
Hmm. I would agree that yeah, just setting it to turn rainwater from dirty to clean would be infinitely simpler than making the sickness chance taper off beforehand.

That said, if the main assumption is that blob contamination is also part of the reason for the water being non-potable, this leads to lore question as to whether blob in the water can contaminate the rain cycle via evaporation. Airborne blob and clouds of ooze actually sounds like something way more terrifying than how things seem in-game, though. Like "evil clouds from Dwarf Fortress" levels of Fun.

**Comment by Skidborg** [comment]
There are reasons to filter rainfall beyond just human pollution.  Any large collection system is going to catch natural debris/insects/bird droppings/dead mice.  Our ancestors did drink unfiltered rainwater, but they also died from completely preventable water-borne diseases.

**Comment by chaosvolt** [comment]
True. Which means realisim-wise, the more annoying code involving scaling down the sickness chance might be the more plausible addition, but that goes beyond the issue's original intent of a "small change for small dose of realism" suggestion. ;w;

**Comment by Coolthulhu** [comment]
Sickness chance scales with a `poison` variable. Changing it with time would be very easy.
The problem is, the vast majority of the game doesn't respect this variable properly. When adding more water to existing water, the poison value of the existing water is used, with no scaling. A single mouthful of almost-clean water could decontaminate a whole tank of sewer water that way.

**Comment by chaosvolt** [comment]
Ah right. Hmm. How did the addition of acid rain to normal water work? Not sure if the whole "diluted acid water" code can be repurposed into any sort of code for "diluting" water's poison chance. I doubt it could be adapted for that purpose, but it could give a starting point for coding such a thing.

**Comment by Night-Pryanik** [comment]
Freshly collected (in clean container!) rainwater is empty from

>natural debris/insects/bird droppings/dead mice.

Water, evaporating and ascending to the skies, did not take all these pollution with it. It is virtually clean, I repeat it again and again. 
When our ancestors

> died from completely preventable water-borne diseases. 

, that was because of pathogens got in containers of already collected rainwater, not from rainwater itself.

**Comment by Skidborg** [comment]
Collecting water from the sky collects /everything/ that falls from the sky.  The things I mentioned are things that I've pulled out of rainwater collection systems.  Some level of filtration is required to get guaranteed clean water.  

It would really make more sense just to add some passive filters for rainwater to the game.  Players will have those set up months before the rain from the sky goes clean, making the clean rain redundant by that stage of the game anyway.

**Comment by kevingranade** [comment]
Reiterating, cataclysm does not take place in a post-civilization utopia,
it tales place in a post-apocalyptic world filed with things that want the
player dead. If anything I'd expect inputting water to get more dangerous
over time instead of less.

**Comment by chaosvolt** [comment]
You mean in time the blob would learn to fly? ;w;

**Comment by kevingranade** [comment]
Or emit toxins or spores into the air.
Also, just think of all the factory and warehouse fires that are going to
happen in the first few years, plus any wars that crop up, malfunctioning
power plants, chemical plants burning down, the list goes on and on.

**Comment by chaosvolt** [comment]
True. That just makes me think we should have randomly-generated clouds of Fun develop as the year goes on. o3o
