### ISSUE TITLE
[Suggestion] change AIM category sort on Worn location to show slots instead of item types

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#14369]
When using the AIM and viewing my 'W'orn items, I'd like to be able to sort by which body part(s) they cover. Sorting by category here doesn't seem very useful (almost everything is clothing or armor). What if the category sort here was coopted to perform a sort by body part? I can probably code this if it's a welcome idea.

**Comment by mugling** [comment]
How do you want to handle items covering multiple body parts?

**Comment by sparr** [comment]
Maybe show items twice, like the layering screen does. Maybe just show them under the "biggest" body part they cover.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
