### ISSUE TITLE
Should sinkhole trap and mining/digging into lava function more similarly?

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#14371]
While working on #14278 I saw a comment saying the code had originally been copied from the sinkhole trap. Since then the two sections have diverged. Most notably, you can save yourself from lava by throwing a rope or a grapnel, and that is processed automatically. You can save yourself from a sinkhole by throwing a rope or a grapnel _or a bullwhip_, and you're prompted for which item to try throwing.

Should these be further consolidated so they function more similarly? If so, which behavior is preferred?

**Comment by Coolthulhu** [comment]
> Should these be further consolidated so they function more similarly?

Would be nice.

> If so, which behavior is preferred?

Sinkhole version of safety rolls, rest can stay as is.
All the checks for safety rolls are basically copies of each other with only numbers and strings changed. Wrapping this up into a function should be trivial.
They aren't tightly balanced, so in this case readability is more important than preserving functionality.

**Comment by chaosvolt** [comment]
Ahem. Sinkholes used to drop you a whole z-level, whereas now they're just pits. That's why the code used to be similar. It was changed presumably because getting dumped (harmlessly, unlike teleportation) into solid rock only to be stick permanently due to lacking a rope was considered damned annoying, compared to a quick death that, unlike a suddenly-revealed trap, gives you adequate warning when you attempt to go down the stairs.

**Comment by Leland** [comment]
Closing - old and no movement. Feel free to ping me here if there's still interest, or make a new issue.
