### ISSUE TITLE
Touchscreen\Hybrid pad friendly movement

### ISSUE THREAD

**Issue by AppleConnoiseur** [CleverRaven/Cataclysm-DDA#14449]
After playing this game for a bit though with quite bad performance i noticed how hard it was to play without a keypad for movement. A way to alleviate the keypad less situation would be to allow players to move the character by touching (clicking) on the screen.

It moves the character into a direction by checking where it is in relative of where it was clicked, so if the click is mostly upwards it move up. (Like a funnel)

This picture illustrates how it would work.
![](https://dl.dropboxusercontent.com/u/547140/touchscreen_friendly.png)

**Comment by SeanMirrsen** [comment]
You may want to look into an onscreen keyboard with a good numpad, I think. You can already move around by tapping/left-clicking on terrain (twice - once to preview path, once more on the same spot to start moving), but all other actions, including combat, are going to be pretty much impossible without an onscreen keyboard anyway.

**Comment by nanovad** [comment]
Note that clicking sets the examine target in both terminal and graphical builds. This would bork that system.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
