### ISSUE TITLE
Electric fields should have a chance to start a fire

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#14463]
A shocker zombie shoots at me with lighting bolts across a library and nothing catches on fire? I am dubious.

**Comment by Dalenacio** [comment]
This is not in the game yet? There's a shocker!

On a non-joke note, I think it should mostly be for things that catch on fire very easily, as it'd be a spark rather than a steady source of flame. Gasoline, for example. Perhaps the dry paper pages of books. But not 2x4s or things like that.

**Comment by Coolthulhu** [comment]
I'm against, at least until we have a fire rebalance (to add "tiny fires" that don't burn), fire resistance or at least a way to stomp out small fires without extinguishers.

Also, books probably wouldn't catch fire from the sparks. Gasoline or gunpowder, maybe cloud of flour or shredded paper, but not stacked books.

**Comment by aeoo** [comment]
@sparr I agree.

More generally at a very low survival skill level certain fire starting methods (especially the easy and powerful ones, like matches and lighters) should possibly produce undesirable fires as well, simulating clumsiness and poor preparation (maybe take dex and per into account), thus potentially setting your own pants on fire or the neighboring bush and a tree, thus potentially leading to a forest fire.  Fire takes some skill and preparation to control properly.  Someone who's never dealt with open fire can easily cause an unintended fire.  It shouldn't be a huge problem though.  I figure by the survival skill level 3 or so, or with high dex/per, open fire should be pretty much under control.

**Comment by sparr** [comment]
@Coolthulhu lightning that can jump 10+ meters doesn't produce "small" fires ;)

**Comment by hitbutton** [comment]
Lightning strikes don't tend to start fires unless they happen to hit something very easily combustible (thin dry vegetation, housing insulation) and those strikes are jumping distances a lot further than 10m. With dense objects like books it's pretty hard to start sustaining combustion, even though the individual pages would burn very easily if you seperated them. I agree with Coolthulu that without a much more complex system to determine how easily things burn, this would have unrealistic results.

All that said, it's difficult to argue about relative plausibiliity of the effects of shocker zombie attacks, when the attack itself doesn't seem to be grounded in reality to begin with. I think we'd need a better description of the duration/energy/heat involved in order to make those judgements :)

**Comment by kevingranade** [comment]
Grounded :D

**Comment by RadaRadaRada** [comment]
Fire seems to be out of control in game. Not sure if it is good idea to add more sources for it.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
