### ISSUE TITLE
Use Furniture to Block Stairs

### ISSUE THREAD

**Issue by nanovad** [CleverRaven/Cataclysm-DDA#14464]
On latest build (0.C-8282) I cannot move furniture to the top of the stairs. It just "collides with something."
Ideally I'd like to be able to block creatures using furniture.

**Comment by sparr** [comment]
What is the expected behavior when you climb up those stairs later? Should you be on the same tile as the furniture?

**Comment by nanovad** [comment]
I'd expect it to be something like "There's furniture in the way!" or, if you have enough strength, push the furniture out of the way when climbing the stairs.

**Comment by Dalenacio** [comment]
If you don't have enough, gg, game over? Maybe just make the time it takes vary depending on character strength, like for dragging furniture around. Much longer of course, makes a lot of noise, and a zombie above ground might just decide to interrupt you while you're doing that, but it's one way.

**Comment by sparr** [comment]
When it's working, Z-level bashing will allow you to smash the furniture at the top of the stairs.

**Comment by chaosvolt** [comment]
Z-level bashing seems like the most logical way. An alternative would be allowing a player with the right tools to deconstruct it.

Both of these are solutions that are just as applicable in the event someone traps themselves in a ring of furniture they can't push.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
