### ISSUE TITLE
NPC didn't use it's moves!

### ISSUE THREAD

**Issue by Rojersm** [CleverRaven/Cataclysm-DDA#14460]
As I have been playing the latest experimental 0.C-7949-gc1d5f78 I have been getting an error roughly like this every time I befriend an NPC (so far just my starting static ones as I only play with static NPCs)  which causes them to throw their weapon down and act normally but also turns on debug mode and forces me to kill said NPC and live the rest of this characters life alone. I wasn't sure if this was a resolved issue since I hadn't seen anything about it on the forums but I thought I would bring it to the table nonetheless.

**Comment by chaosvolt** [comment]
This is an ancient bug that occurs every so often, no idea if it has a set cause or if it's unpredictable. No idea if it's been reported or not.

**Comment by scorpion451** [comment]
In my experience you can basically ignore this error. Just flip debug mode back off and carry on. If they want their weapon back and you let them pick up items they'll take it back.

**Comment by Coolthulhu** [comment]
"NPC didn't use moves" isn't a bug, it's a message signifying that there may be a bug somewhere.
It happens whenever in a single "AI pass" a NPC executes only actions that cost no moves.
In addition, if 10 such turns happen during a single actual game turn, the NPC will die ("<npcname>'s head explodes").

Looking at the wield code, it seems to consume no actions whenever the NPC drops a wielded weapon. It might be the cause of the bug here.

Now, I'm not sure whether to just hack around the "didn't use actions" or to find a different solution to the problem that doesn't involve making NPCs have to consume at least 1 move per turn.

**Comment by chaosvolt** [comment]
So an NPC can die from being unable to act? So basically Quick Man. o3o
