### ISSUE TITLE
vehicle_part rotation tiles

### ISSUE THREAD

**Issue by hitbutton** [CleverRaven/Cataclysm-DDA#14488]
many of the vehicleparts are split into different types depending on rotation.
e.g. "vp_board_vertical" and "vp_board_horizontal"
Those parts can then have multiple rotations defined for them as tiles.

It is logical that those parts are split, as the shape of the vehicle can be defined manually by the player. You can make every quarterpanel on your vehicle a northeast corner, if that's what you desire.

However this does make defining rotational tiles for the vehicle parts a very repetitive process. See this section from a tileset_config I'm working on:

```
    {
      "id": "vp_board_nw",
      "multitile": true,
      "fg": [104, 105, 106, 107]
    },
    {
      "id": "vp_board_sw",
      "multitile": true,
      "fg": [105, 106, 107, 104]
    },
    {
      "id": "vp_board_se",
      "multitile": true,
      "fg": [106, 107, 104, 105]
    },
    {
      "id": "vp_board_ne",
      "multitile": true,
      "fg": [107, 104, 105, 106]
    },
```

It seems like the logic here could be improved. If I rotate my vp_board_nw ninety degrees anti-clockwise, I think it's safe to assume I want it to look the same as a vp_board_sw.

**Comment by sparr** [comment]
In isometric mode we can't just assume that a tile sprite can be rotated. However, what we CAN do here is make this system work with the additional-tiles mechanic used for other types of sprites, so you'd specify 1-4 rotated versions of the sprite once and the rest would Just Work.

**Comment by hitbutton** [comment]
> In isometric mode we can't just assume that a tile sprite can be rotated.

Agreed, but to clarify:
If I rotate my vp_board_nw ninety degrees anti-clockwise [in the game world], I think it's safe to assume I want it to [use the same tile as] a vp_board_sw.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
