### ISSUE TITLE
Melatonin as a non-addictive sleeping drug

### ISSUE THREAD

**Issue by theglock** [CleverRaven/Cataclysm-DDA#14480]
https://sleepfoundation.org/sleep-topics/melatonin-and-sleep

Melatonin would be a really good alternative to the other habit-forming sleep drugs. I personally use it every night, and knocks me out about an hour after taking it.

To balance it in the game and make the other drugs still viable, maybe there can be a 40%-50% chance of getting your sleep disrupted with a spasm every time you take one? 
In the real world a common side effect is restless leg syndrome, where your legs (or other parts of your body) feel like there are ants running up and down inside your body, which can disturb sleep.

**Comment by Coolthulhu** [comment]
Disrupting sleep is quite annoying, because it requires the player to issue the "lay to sleep" command once again. It is also inconsequential, unless you have the "Insomniac" trait and you wake up shortly after losing the "tired" level of sleepiness.

I wouldn't give it the ability to cause tiredness like full-blown sleep drugs. Instead it should only make falling asleep easier, working like depressants in this regard, without the ability to sleep for longer time (and thus regenerate more hp).

**Comment by theglock** [comment]
That's sounds like a good compromise, using it as something to help get rid of the "tired" symptom without any other benefits is still useful but doesn't overshadow the other drugs.

**Comment by nanovad** [comment]
Does the game allow a distinction between giving tiredness and making falling asleep easier? I think sleep drugs just add a certain amount of "tired" to the invisible stat. Normally that's enough to take the char from normal-feeling to tired. Perhaps it could only affect it a little bit? Also, what would happen if you took a lot of them?

**Comment by Coolthulhu** [comment]
> Does the game allow a distinction between giving tiredness and making falling asleep easier?

There is tiredness and stimulants. Stimulants make it harder to fall asleep if positive, easier if negative.
Alcohol will make it easier to fall asleep when not tired by lowering stim value, Ambien will cause both tiredness and lower stim value.

**Comment by kevingranade** [comment]
Alternately we could just add a sleep aid effect and not intetesting with
any of the other stats.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
