### ISSUE TITLE
Can craft "clean water" from toilet's "water" indefinetely

### ISSUE THREAD

**Issue by niglow** [CleverRaven/Cataclysm-DDA#14490]
0.C-8329-g7d321be, Windows, tiles.

Set up a brazier near a toilet and craft clean water as long as you want - water in the toilet will never decrease unless the toilet is broken or water is stored somewhere else.

**Comment by Rivet-the-Zombie** [comment]
All the toilet water you can drink!

**Comment by remyroy** [comment]
I can confirm this in the latest experimental. The default toilet should hold 6 liters of water or 24 charges. I was able to craft 100 charges of clean water out of one I found in a regular house.

**Comment by remyroy** [comment]
The issue is that `player::consume_items` is called trying to consume the water from the map but it uses the location of the player and calls g->m.use_charges with an incorrect location.

The location of the component should probably be added to `comp_selection`. In `player::consume_items`, the proper location of the component could than be used.

**Comment by remyroy** [comment]
My bad. The problem comes from `use_charges_from_furn` in map.cpp and its inability to use the water from the toilet. I'm looking for a solution.
