### ISSUE TITLE
Game lockup whilst exploring lab

### ISSUE THREAD

**Issue by drayath** [CleverRaven/Cataclysm-DDA#14499]
Walking round lab when game locked up (not responding, max cpu for 5+ minutes), nothing special seemed to be happen at the time. Forced memory dump attached.
Does not appear to repeat if load from save.

Version: 4047 (zlevels on), Windows-SDL

[Memory dump](https://github.com/CleverRaven/Cataclysm-DDA/files/67458/cataclysm-tiles.4047-lockup.exploring.lab.-.zlevels.on.zip)

[Save a few minutes before](https://github.com/CleverRaven/Cataclysm-DDA/files/67457/pre.lockup.save.zip)

**Comment by drayath** [comment]
Happened again in same lab. Forced memory dump attached.


[cataclysm-tiles.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/67504/cataclysm-tiles.zip)

**Comment by DanmakuDan** [comment]
It appears to work fine for me by completely replacing the Blaze mod folder with the latest version. Separately, updating to 4068 appears to avoid crashing for a different reason. Some debugging tests (not the exact version tested) noted "solar_array" was missing when a car got loaded into the game somewhere, which was fixed by updating the Blaze mod.

**Comment by mugling** [comment]
Presumably resolved in `master`. @drayath please re-open if this remains a problem for you
