### ISSUE TITLE
Toggle Explored in overmap

### ISSUE THREAD

**Issue by joneskun** [CleverRaven/Cataclysm-DDA#14507]
Should be pretty easy, I was thining a list of submaps the player has actually entered in the character file, then just mark them with a blue hash or something when toggled.

**Comment by BevapDin** [comment]
You can do this manually in the overmap, the key binding is `E` (not sure, press `?` there to see the key bindings). The overmap terrain will be display in gray when it's marked as explored.

**Comment by sparr** [comment]
[E] is a great tool for keeping track of buildings you've cleaned out (of items or zombies or both).

As to keeping track of which submaps you've literally "explored", check out #14383 which is based on the existing code for revealing an OMT on the overmap based on tiles-seen rather than just on being nearby.

**Comment by joneskun** [comment]
Ah, wasn't aware that functionality was present, I'll have to play with it.

No particular use case. I spend most of my time rolling for difficult starts, then tend to leave semi-established characters laying around. Every so often I'll go back to develop one and find my usual cryptic or no notes at all :)

I'll leave this open for further comments for a bit.

**Comment by codemime** [comment]
Can be closed.
