### ISSUE TITLE
Vehicle windows are displayed as "

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#14521]
This is pertinent now because tiles folks designing isometric tiles are troubled by windows not having a facing. It has previously bothered me, after I noticed that t_wall_glass is drawn with blue lines instead of blue quotes. I'd like to let the player select a direction/shape for vehicle windows in the same way that they do for frame pieces. Would that be a welcome change?

**Comment by SeanMirrsen** [comment]
Windows will then look exactly the same as steel plate though, in ASCII. Not too much of a concern I suppose. (And really, why is steel plate bright cyan instead of dark? Would fit much better in my opinion.)

I'm unsure of the realism of making glass corners, but then realism doesn't factor into a lot of things in CDDA vehicle-making anyway. :P 

I'd say try it out and see how it looks.

**Comment by hitbutton** [comment]
There are a lot other vehicle parts which are facing-agnostic similar to windscreens. This is ok for things like seats/wheels which can trust that they should always be pointed at the front of the vehicle. The problem parts are things like doors, which should look very different depending on if they're on the side or back of the vehicle.

This would make it difficult to get a lot of mileage out of isometric windscreens with defined facing, since you're pretty much stuck with cube-blocks unless you know which direction every part should be facing.

I hope that makes sense, I could try to explicate some more with illustrations if I'm unclear.

**Comment by kevingranade** [comment]
Just an implementation note, we don't have to change the symbol in terminal mode to add facing for tiles mode.  We can just have n entries for a rotatable element, and set them all to " for curses.

**Comment by Night-Pryanik** [comment]
Closing as per lack of discussion.
