### ISSUE TITLE
[Suggestion] Add a spicy flag to food

### ISSUE THREAD

**Issue by Cyrano7** [CleverRaven/Cataclysm-DDA#14530]
Thinking about adding a spicy flag to food. Then having a new spicy intolerant trait or adding a penalty if you have the weak stomach trait or something like that. Id be against adding a spicy intolerant trait to the starting traits list at the moment as there are not a ton of spicy foods yet. We might get a few more now that we are cinnamon though. It would be cool to throw a spicy intolerant trait into some of the mutation trees as most animals can't eat spicy food. Just wanted to see what people think before I run off and do this though.

**Comment by hitbutton** [comment]
AFAIK all the current comestible restrictions use the "material" field of the food, which means you can easily tell whether or not a food will trigger your restriction by examining it.

If "spicy" was just added as a flag then you would have no easy indication of what foods were or were not spicy. So I'd suggest implementing it as an additional "spices" material, rather than a flag.

**Comment by Cyrano7** [comment]
@hitbutton thanks that's a good idea.

**Comment by BevapDin** [comment]
> If "spicy" was just added as a flag then you would have no easy indication of what foods were or were not spicy.

Why not? You can always add a line to the item info window.

**Comment by Cyrano7** [comment]
I think all the spicy items already have the word spicy in the description.

**Comment by hitbutton** [comment]
BevapDin: Emphasis on the "just" in the part you quoted. If the flag also caused an additional line in the  item info window that would work :)

Cyrano7: That method wouldn't be guaranteed to be consistent. Later additions could include spicy foods where the description doesn't contain that word, or foods where the word is used but the flag is not added.

**Comment by chaosvolt** [comment]
Soooon, we can have habanero? o3o

Not really sure how best this should be implemented though. A lot of the spicier existing items simply keep the spiciness implied by lower quench values.

**Comment by Cyrano7** [comment]
Oh wow I just found something kind of cool. So in item.cpp there is a way to print specialized messages for different types of food. Like if you have bionic stomach It will tell you what you can eat even if your food is rotten. Its the same function that tells you if a food is perishable. So what I can do is make a spicy flag and write a if statement something like if is_food && has_flag(spicy) && (u.has_trait(spicy_intolerance) || u.has_trait(weak_stomach)) then print "eating this might upset your stomach". @chaosvolt @hitbutton @BevapDin How this? Im still not sure if we should have a spicy_intolerance trait or just do it for weak stomach and nauseous though.

**Comment by Rivet-the-Zombie** [comment]
If you're going so far as to add something of this scope, then I see no reason to not go with a new trait. Besides, having a bad stomach shouldn't prevent you from enjoying spicy food.

**Comment by chaosvolt** [comment]
Hmm. Might be interesting then.

Needs moar Mexican food anyway, that'd make such a trait have more impact. X3

**Comment by Coolthulhu** [comment]
Spice as a material? Sounds like extending a hack just because we already have it. This is bad design.
We should move stuff like eggs and milk from "materials" to some new field, "allergens".
This field could be situated right below materials or nutrition.

Material is something that has damage resistance, density, mass and will soon probably also have a "material item", like a rag or a piece of scrap copper. Unless we intend to have a scrambled egg armor that is repaired by food sculpture kit using powdered egg as material, treating allergens as materials is a very non-elegant solution.

**Comment by chaosvolt** [comment]
Hmm. That might be the better option, yeah.

Though I'd love meat armor, o3o

**Comment by Cyrano7** [comment]
@chaosvolt well this was kinda a effect of adding cinnamon. Top open cinnamon request seems to be for spicy cinnamon candy. Something simple like chewy candy but craft-able too. (sugar, water, cinnamon) small morale boost. But before adding a bunch of new spicy stuff I want to finish this idea first.

@chaosvolt  I'm definitely against adding spices has a material. I'm not sure if you saw this "So in item.cpp there is a way to print specialized messages for different types of food. Like if you have bionic stomach It will tell you what you can eat even if your food is rotten. Its the same function that tells you if a food is perishable. So what I can do is make a spicy flag and write a if statement something like if is_food && has_flag(spicy) && (u.has_trait(spicy_intolerance) || u.has_trait(weak_stomach)) then print "eating this might upset your stomach"."

**Comment by Cyrano7** [comment]
I think I might add a new trait but hold off on adding it to the start trait list because there i'snt enough spicy food yet. But I aim to change that to hehe. I'll either keep it inactive or throw it in some of the mutagen branches for now.

**Comment by hitbutton** [comment]
Yes, that warning is present for all food intolerance. The player should still be able to tell if a certain type of food will trigger their intolerance before trying to eat it (for example, when choosing to craft or loot it).

@Coolthulu fair enough. I thought the existing usage of materials for comestible makeup was the convention to follow, rather than being a misuse of the material system.

**Comment by chaosvolt** [comment]
I saw that, yeah. I was agreeing that yeah, adding a spicy flag or something other than using a material would be better,

**Comment by mugling** [comment]
Questionable if we should add more intolerance traits.
Discussion continues in #14543
