### ISSUE TITLE
[Question] Spawns and Console/Graphical

### ISSUE THREAD

**Issue by SirMrGnome** [CleverRaven/Cataclysm-DDA#14535]
About a month back on reddit someone asked about mixing Wander Spawns with Static. [Post in question https://goo.gl/WUloj9.] @CIB replied that turning wander on with static will merge zombies into hordes but they won't actually spawn anymore zombies. This was a month ago and the experimental version changes quite often so I was wondering what if this is still true. And if not, how it now works.

As for my second question, on the sidebar of the official site there is two Windows options underneath experimental, Console and Graphical. What is the difference between them?

**Comment by SeanMirrsen** [comment]
>This was a month ago and the experimental version changes quite often so I was wondering what if this is still true. And if not, how it now works.

Not sure if this is true, because as far as I'm aware the world settings are saved at generation time. You could probably go into the save folder and look through the world settings file, change the `WANDER_SPAWNS` option to true, and see what happens.

>As for my second question, on the sidebar of the official site there is two Windows options underneath experimental, Console and Graphical. What is the difference between them?

The console version uses pure Curses - that is, it's a lot like a DOS window, that uses purely system text to display what goes on. Very retro. :P 
The graphical version is SDL, and allows you to set different fonts for different areas of the game (terrain view, text, and overmap), as well as use graphical tile sets made by the game's various talented users.

So the difference is one of appearance and speed, mostly. And compatibility.

**Comment by ryvn** [comment]
I just made two worlds, one with both Static Spawns and Wander Spawns, and one with only Wander Spawns. I also have an old save with only Static Spawns on.

With both enabled, I see basically the same zed distribution as my old world with only Static Spawns on, with the difference being that I can see on the map that they have formed (relatively small) hordes that slowly move about the city. I've been playing this one for a while and noticed that even when I make a lot of noise, I rarely manage to attract more than a handful zombies - I find myself hunting down hordes looking for things to kill. Once in a while a lone zed or small group will wander past my hideout, which did not really happen without Wander Spawns on.

With only Wander Spawns on, hordes cover most of the starting city and a quick investigation indicates that they contain screen-filling numbers of zombies. Static Spawns appears to not only place its initial zombies, but also prevents Wander Spawns from creating any.

**Comment by sparr** [comment]
This sort of post would get a lot more feedback and discussion on the forums: http://smf.cataclysmdda.com/index.php
