### ISSUE TITLE
Scrolling combat text in isometric mode

### ISSUE THREAD

**Issue by hitbutton** [CleverRaven/Cataclysm-DDA#14532]
SCT is written east to west.

In isometric mode, this means the text always slants upwards, and the draw order is broken by further tiles being drawn after nearer ones. Here is a screenshot to illustrate:
![image](https://cloud.githubusercontent.com/assets/16194079/11919228/9657970c-a744-11e5-943d-08a973894031.png)

You can see points where the text is being overdrawn by the ground rhombus of the further tile. I've colored one of them in magenta to make it easier to see.

I think the text would be easier to read in isometric if it was written north to south, so the text slants downwards. This would also mean the drawing order would be correct, rather than having to be reversed.

**Comment by SeanMirrsen** [comment]
Wouldn't it make more sense to have the overlay text be a, well, overlay? Like, an actual separate layer, drawn over the terrain map in main game font (not the terrain font). Console version would not notice the change because all fonts are the same. For everyone else it'd mean more compact and better readable text in these popups (if the terrain is square font and main text isn't).

**Comment by hitbutton** [comment]
That could also work, and would likely be more readable. I'd be concerned that text appearing in the viewport that doesn't match up with the tile layout could look quite jarring though.

I also kinda like the pseudo 3d effect on the combat messages.

**Comment by kevingranade** [comment]
Terminals don't support overlays, if you want to do that in sdl builds,
you'll have to add independent support for SCT there.
