### ISSUE TITLE
Add aggregate armor information to character info screen

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#14549]
Inspired by IRC:

```
2233 <Zubo> Can I see somehow how much exactly armor I have?
2233 <sparr> no, mostly because that's a very complicated question to answer
2234 <Zubo> something like "Torso - N armor, Head - N armor"
2234 <sparr> how do you think N would be calculated?
2235 <sparr> you have multiple layers of clothing on your torso
2235 <kevingranade> coverage really messes with it
2235 <sparr> each layer has different protection vs bash, cut, stab, acid, fire, cold, ...
2235 <sparr> each layer also has a coverage %
2235 <Zubo> layer1*coverage1 + layer2*coverage2 + ...?
2236 <sparr> that will give you six different numbers, one for each type of protection
2236 <sparr> how do you reduce those numbers to one?
2236 <kevingranade> yea, it'd be dozens of entries
2236 <sparr> also, it's L1*C1 + L2*C2*(1-C1) + L3*C3*(1-C1)*(1-C2) ...
2237 <sparr> but that part's easy :)
2237 <sparr> I actually wanted to add a display of how much damage your equipment has taken, averaged across layers like that
2237 <Zubo> or just know, for example, how many bashing defence I have
2237 <sparr> just bashing?
2238 <sparr> ok, so, you could calculate the layer-weighted bashing protection for each body part
2238 <kevingranade> and most ways of summarizing it would be misleading, because it rolls for coverage with each piece of armor
2239 <sparr> THEN you could use the probability of each part getting hit, and weighted-average all those protections together. that would give you the "average overall protection from bashing" that you have
2239 <kevingranade> although it could give a min-max spread
2239 <sparr> and... having written all that out, I think those ~6 numbers might actually be useful to put on the UI somewhere...
2239 <kevingranade> min would just be the sum of the 100% coverage items
2239 <kevingranade> max would be the simple sum of all the armor layers
2240 <sparr> min-avg-max?
2240 <sparr> avg is the most important in the long run
2240 <kevingranade> I'm not sure it is, but yea it'd be important at least
2240 <sparr> min or max could be mostly-irrelevant if you're wearing 10% or 90% coverage stuff
2241 <kevingranade> true
2241 <sparr> I gave up on this previously because I couldn
2241 <sparr> 't make it fit on the main sidebar like I wanted to
2241 <sparr> but I wonder if it might fit in the @ screen
2242 <kevingranade> it should probably try to get crammed into the armor layering screen
2242 <sparr> hmm, that's doable. the encumbrance section there has a lot more width than the same section on the @ screen
2242 <sparr> we've got 6 columns and num_body_parts rows of free space there, I think
```

**Comment by chaosvolt** [comment]
Hmm. Will be interesting to see.

**Comment by Zireael07** [comment]
Bump. Would be extremely useful.

**Comment by chaosvolt** [comment]
Agreed. Though actually trying to sum up the net effects of all the armor you're wearing might be awkward to display. The highest protection value, plus the coverage of whatever's providing that value, might be the most practical method (so you see both the best hit that part can take, plus whether your odds of taking that hit are at all decent).

**Comment by sparr** [comment]
It's a bit more complex than that. If your top layer doesn't catch a hit then the layer underneath might. I'm thinking I want to display the total % chance of a hit on that body part getting through to you, and also the health of that stack of items weighted towards the outer layer in the same way.

**Comment by chaosvolt** [comment]
True. Though it's hand to think up good math to display overall how the different degrees of protection and coverage will actually work out.

The most comprehensive would be a straightforward list of everything, but the character screen can't really hold all that.

**Comment by Coolthulhu** [comment]
"Expected protection" would be a bit too probabilistic, but could work.
Still, we're trying to describe a distribution with just one number, it has to be probabilistic.

The most informative way would be to display a graph, but then we'd have to draw a graph.
Ugly ASCII graph would be enough for small armor values, though.

Alternative option would be to just print out the distribution like:
* 3% chance to absorb 0 damage
* 80% chance to absorb 10 damage
* 11% chance to absorb 16 damage
* 6% chance to absorb 20 damage

**Comment by chaosvolt** [comment]
Hmm.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
