### ISSUE TITLE
Add flags to furniture to rotate to face impassable terrain or other furniture

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#14551]
This idea came from IRC in a discussion about isometric tiles, but applies to normal tiles as well. I propose two new flags for furniture, the names for which can be quibbled about. I'll call them ALIGN_TERRAIN and ALIGN_FURNITURE.

ALIGN_TERRAIN will cause a furniture sprite to rotate so that it's facing adjacent impassable terrain. If there's more than one, it will choose the facing closest to the most of them. This will be used for making lockers and refrigerators and chairs face away from walls.

ALIGN_FURNITURE will do the same thing, but the alignment target will be any other furniture that does NOT have the flag. This will be used for making chairs face desks, etc.

**Comment by hitbutton** [comment]
The behaviour for ALIGN_TERRAIN would probably be better if it chose a passable terrain to align to. Your description seems like it would act strangely in the case where furniture was blocked N+S or E+W.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.

**Comment by I-am-Erk** [comment]
Reopening as this has come up in the current tileset push.
