### ISSUE TITLE
[Suggestion] New Trait: Terrible Cook

### ISSUE THREAD

**Issue by railmonkey** [CleverRaven/Cataclysm-DDA#14584]
Random thought I had that I'm putting down before I forget. As the name implies, it would attach a morale penalty to any prepared food recipe (not necessarily drinks, though that would be hilarious). Think of it as a roughly opposing trait to Gourmand. I'm not entirely sure how it would be coded in, though. An if-then statement for each affected recipe? Probably a pain in the butt if so, but I'd be willing to do it.

**Comment by Coolthulhu** [comment]
I'd rather see "fussy eater" as opposing to gourmand.
Long-lasting penalties for eating anything that doesn't taste good, smaller for eating food that isn't hot/cold when it should, inability to forcefeed self.

Being a terrible cook isn't really a trait, just lack of skill. Unless you have no sense of taste/smell, in which case you couldn't tell it tastes bad anyway.

Currently recipes don't have flags. If you wanted to add something to all items produced in a specific way, you'd have to mark all the items that can have "bad tasting" flag with some other flag, then give them this flag on finished craft.

**Comment by railmonkey** [comment]
Hm, fair enough, at least in regard to it being an opposing trait. That sounds like a much less gimmicky idea, anyway. So, which file are morale modifiers found in?

**Comment by Coolthulhu** [comment]
> So, which file are morale modifiers found in? 

player.cpp
There is a section for gourmand, intolerances etc.

**Comment by railmonkey** [comment]
Ah... I have no idea what I'm looking at. :\ Could it be an extension of { _( "Disliked %i" ) }, ?

**Comment by Coolthulhu** [comment]
Find all instances where "GOURMAND" is checked for. "Anti-gourmand" should be checked in the same places.

**Comment by scorpion451** [comment]
I do think there could be something in the "terrible cook" idea- maybe tweak it to be dyspraxia (similar to dyslexia, but for things like complex sequences of steps.) Its generally not a crippling condition, but it causes things like remembering that you need to put the charcoal in the filter...after you've bolted the filter closed. In practice it could increase the chances to flub the recipe on food, and increase the time it takes to complete crafting.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
