### ISSUE TITLE
"Lost tool used for long repair" when attempting to use vehicle welding rig to enhance items (4096)

### ISSUE THREAD

**Issue by Vsevolod-Shustov** [CleverRaven/Cataclysm-DDA#14608]
Didn't have that bug on 4068. Probably related to 4093 changes.

**Comment by joneskun** [comment]
@Coolthulhu I'm liking it a lot but probably needs a little tweaking. Playing around (since I don't wanna spoil myself with the math): Dex 12, tailor 6, tailors's kit, focus >75, mood>=0, no status effects and the character could not fit in compression shorts. Approx ratio of damage/repair/fit in over approx 500 charge was 5:3:0

**Comment by DanmakuDan** [comment]
Using a welding rig creates a temporary welder item that borrows charges from the vehicle battery. The changes to the repair code expect that the welder is actually in your inventory before continuing, causing the debug message to appear.

**Comment by Coolthulhu** [comment]
Crap, that won't be easy to fix...

As for balancing: that's doable. I might have gotten some of the math wrong, because it worked good in the testing.

**Comment by Sternenfisch** [comment]
I think thats related to changes done to the repair/fix interaction, as on the most current build I'm asked whether to repair long as possible, repair but not reinforce etc. something that didnt come up before when the welding rig was working, and my guess is that is not properly implemented for vehicle welding rig hence the problem.
