### ISSUE TITLE
[Discussion] Furniture and vehicles, why different and can we merge?

### ISSUE THREAD

**Issue by SeanMirrsen** [CleverRaven/Cataclysm-DDA#14651]
Tried to be as laconic and descriptive in the title as I could. :)

Basically, that's the entirety of the question. After all this time, is there a reason to still keep furniture (in the real-world definition of "furniture") and vehicles apart from each other, and what would the butcher's bill be for everything we'd have to break in order to convert to a "dynamic map object" sort of class that encompasses them both?

From a gameplay standpoint, it would seem to me that merging the two "classes" of movable map-item together would only result in positives all around. Multitile tables and beds you can grab and move, the ability to install any furniture at all into a mobile base, just a general consistency between what is what and what can do what. Code-wise, no more duplication of the functions of one in the other (storing items, receiving/transmitting power, having auxiliary functions, beds, implied tools, liquid containers, etc), again consistency, in stuff like dragging, collisions, interactions, etc.

On the flipside, massive overhaul of the entire existing mapgen to switch to this new "dynamic map object" class, defining multitile furniture like beds and tables and sofas the same way as vehicles, the need for a new, more flexible system for examining and modifying the DMOs without being thrust into the current vehicle-interaction screen, handling rotation cases for furniture, lots of various recipes and item definitions that need updating, draw code that doesn't depend on the 'vp_' prefix... probably a lot more that I didn't get.

In my opinion, the potential for improving and expanding gameplay would be worth the work required to do the changes. But before the first lines of code are typed in, there needs to be one hell of a complete plan of action, and there needs to be agreement that it's actually a worthwhile direction to pursue. So... putting this here to get some feedback on the idea, and get a sense of how massive an undertaking would this actually be, from people actually familiar with the code involved.

**Comment by Coolthulhu** [comment]
Furniture has one great advantage over vehicles: it takes literally one `int` value to save it to memory and one short string to save it to the save file.

Converting furniture to vehicles would require adding tons of per-instance fields to furniture that is at the moment only described by per-type values.

Additionally, there would be a processing cost involved.
Furniture can be checked for by a simple `furn_at`, which brings up a complete structure of flags and stats.
For vehicles, you have to scan the entire part array to find what is located where. Even if vehicles had a part location cache (which could get expensive to store in case of lots of furniture), this would add some overhead and complexity.

Consider fire calculations. I improved their performance massively and they're still quite heavy.
Now add part location retrieval for every furniture burned, splitting big objects into smaller ones, even just the constant creation and destruction of new objects.

Vehicle cache is quite efficient at what it does also because it is relatively sparse. If it suddenly had to keep 100+ objects in a reality bubble slice (z-levels have separate vehicle caches, because they don't need to interact much), it could easily get overwhelmed in the current implementation.

Now, all of those problems are solvable with clever caching. But clever caching is a lot of work, a lot of testing and a lot of bugs.

**Comment by kevingranade** [comment]
What coolthulu said, but about 10x as emphatic.
Vehicles are incredibly expensive to maintain, the only reason they don't
slow the game to a crawl is that there aren't that many of them on the map
at a time.
Also the vehicle code is already very complex and hard to change/fix,
layering in special cases for handling furniture would make it worse.

You implicitly rejected the solution to this I've presented every time this
has come up, which is implementing complex, multi-tile furniture as a
special vehicle which cannot be modified using the vehicle crafting
interface.  This literally requires a single vehicle part flag and a few
dozen lines of code to enforce it,  and otherwise seems to represent the
best of both worlds. It keeps the complex stuff complex, and the simple
stuff simple.

**Comment by SeanMirrsen** [comment]
>It keeps the complex stuff complex, and the simple stuff simple.

And yet it would still use two entirely different class constructs that share no properties in code and act nothing alike except when forced to. I would be fine with a "bridge", the current single-flag furniture handler being used to invoke a temporary object referencing the underlying base class (or rather, a part thereof, constructed from the whole set of data but leaving the unused parts out), but in order to expand gameplay rather than merely reshuffle things behind the scenes, furniture and vehicles would need to be fundamentally the same thing, using the same logic in the same way when required.

But, to put a highly optimistic slant on the discussion so far - you would not be **against** an implementation of a merged "map object" class, in the basic principle? As in, if one were to come up with a way to make it work, you wouldn't shoot it down for the sheer gall of existing, correct? :P 

I fully understand the concerns for performance (I'm playing on a tablet, you bet I understand the performance concerns :P), indeed I posted this in part to get a better idea of the extent of those concerns, and of course if the result is unacceptably slow it won't make the cut, but I'd prefer not to dismiss the idea out of hand.

**Comment by kevingranade** [comment]
I would absolutely "shoot it down" unless you demonstrate that unification
makes the code simpler, and I'm very skeptical that simplification would be
the result of what you are suggesting.

**Comment by SeanMirrsen** [comment]
Depends on your definition of 'simpler', and whether or not you consider that it'd be *adding* functionality as a result. It would likely not be simpler than either furniture or vehicle code taken separately, but it could be simpler than them combined, and could result in simplifications elsewhere (i.e. anything revolving around functions provided by both furniture and vehicles).

In any case, I'll take a stab at it and see what results. I hope I'll be able to ask for help or code insights, at least. :)

**Comment by Coolthulhu** [comment]
> It would likely not be simpler than either furniture or vehicle code taken separately, but it could be simpler than them combined

Furniture code is quite simple, though.
In most cases it is treated as a layer of terrain on top of existing terrain. In cases where it isn't, treating it as a vehicle would most likely be a problem anyway.

**Comment by scorpion451** [comment]
> ...implementing complex, multi-tile furniture as a special vehicle which cannot be modified using the vehicle crafting interface. This literally requires a single vehicle part flag and a few dozen lines of code to enforce it, and otherwise seems to represent the best of both worlds. It keeps the complex stuff complex, and the simple stuff simple.

I rather like this idea. I wonder if that could be used to expand the power system as well- say, one could jumper-cable a player-made generator to a stock refrigerator or stove if each was a single-part quasi-vehicle able accept power from an outside source.

**Comment by kevingranade** [comment]
Extending the power transmission system is precisely why I came up with it
in the first place.

**Comment by kevingranade** [comment]
The answer to this is a solid "no" unless someone can demonstrate that it actually makes the code simpler, which is the only reason to do it in the first place.
