### ISSUE TITLE
Extra light quarterpanels heavier than quarterpanels.

### ISSUE THREAD

**Issue by Shadefang** [CleverRaven/Cataclysm-DDA#14663]
quarterpanel/board: 2.2 lbs 225/240 durability.
Extra light quarterpanel: 2.8 lbs 100 durability.

**Comment by SeanMirrsen** [comment]
That's... actually a problem with how vehicle parts work right now.
The parts don't have weight defined, just the items that they are made of. Extra-light quarterpanel is made from a metal pipe. Quarterpanel is made of a metal sheet. Metal sheet is lighter than the pipe. The solution to this would be to either make the x-light quarterpanel out of something else, or base the weight of the part on what it can be broken into, and have the x-light quarterpanel return some scrap instead of a pipe.

**Comment by Coolthulhu** [comment]
Maybe the pipe is too heavy or the sheet metal too light.
Sheet metal can be made into an entire small metal tank or a brazier.

**Comment by SeanMirrsen** [comment]
That depends on the sheet and the pipe, really. Not enough granularity in the item system to say. A 1kg sheet of steel (which I am assuming this to be) at 1mm thickness (decent enough for most purposes) comes out to a panel about 36 by 36 centimeters, which is not too bad, but woefully inadequate for the sort of things these get used for. Even at half-millimeter you only get a 50x50cm panel. Either various recipes need to start using more sheets, or we could definitely bump a single sheet's weight a bit.

Similar logic applies to the pipes, because they seem to be usable as anything from gun barrels to lightweight constructions, although the 1.4-something kg that the pipe currently weighs is more realistic for a decent length of pipe. (from what it's used for I'd say it needs 3 feet of length and about half an inch diameter, and going by the calculations above it'll give you about 2-3mm thickness which is fine)

(fake-edit: this one site tells me that a steel half-inch pipe (21mm outer diameter) with a wall thickness of 2.2mm will weigh about 1kg per meter. So it seems that we have a case of both the pipe being too heavy, and the sheet metal being too light.)

**Comment by Leland** [comment]
Discussion's been stalled here for a few years. Closing.
