### ISSUE TITLE
Vehicle turret related crashes

### ISSUE THREAD

**Issue by vulkans22** [CleverRaven/Cataclysm-DDA#14661]
There's an intermittent crash to desktop occurring when automated turrets attack hostiles, tested on official 0.C-4111 Windows/Tiles. I can't quite peg down the root cause.

I've included a nighttime save, there's a one tile vehicle containing a live laser turret, powered lights and lots of zombies around. Skip enough turns and the game should crash eventually.

[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/74462/save.zip)

**Comment by Coolthulhu** [comment]
OK, replicated the crash.
Seems to be related to the "high accuracy crash" which was reported on forums.
It seems that a ranged attack executed at very high accuracy may cause a "Floating point exception".

I'm recompiling the game in debug setting because I can't pinpoint what causes the crash just from the code alone.
