### ISSUE TITLE
[Suggestion] More makeshift polearms\spears

### ISSUE THREAD

**Issue by AppleConnoiseur** [CleverRaven/Cataclysm-DDA#14678]
Would it be possible for survivors to make Bills, Billhooks and Halberd out of everyday junk and spikes?

Grim Dawn had some interesting interpretations on how weapons made out of junk coud look like. Using a sawblade in a axe for instance. What looks like a short sword out of a huge razor. (makeshift machete)

So for making scrap bills we could use the spike component which is bent and one which is straight. Could be useful for poking a enemy to death. Maybe work as a crappy woodcutting tool too for young vegetation as well. Can be made in a short 1 handed version with no reach attack and a polearm variant.

Two spikes + Duct tape\String + Wood = Makeshift billhook
Two spikes + Duct tape\String + Long wood\Pipe = Makeshift long billhook (Same reach as knife spear)
Disarm and Parry as techniques

A scrap halberd could be made out of a knife spear with a sort of blade (lawnmower or sawblade) attached to it to allow slashing attacks.

Spike + Blade + Duct tape\String + Long wood\Pipe = Makeshift halberd
Trip and Parry as techniques

To go on a length it would be possible to make a makeshift pollax as well. Take a halberd and add a backside to it with a blunt object like a rock or a piece of scrapmetal. Would probably make for a unwieldy weapon compared to a properly crafted one with forging and fabrication techniques.

Will probably give it a bash myself making the items myself when i come home from this new years celebration :P.

**Comment by kevingranade** [comment]
Possible yes, but frankly they should be terrible imitations of the real
thing, mostly by being heavy and therefore slow.

**Comment by SeanMirrsen** [comment]
I wonder if knife spears could be made as an outcome of implementing "melee weapon mods". Take a knife, "mod" its handle to a broomhandle, instant spear. It'll even be able to have different damage values based on what weapon you use. 
Likewise you could add an extra melee weapon to an existing one as an "expansion", resulting in a single weapon that has reduced to-hit, but has the highest damage of both weapons for each damage type (i.e. attach a spike to an axe, get piercing damage of the spike and slashing damage of the axe).

**Comment by kevingranade** [comment]
Weapons don't work that way, the damage they can cause is a complex
combination of dynamic leverage as they are swung, weight distribution, and
the interaction of the striking surface(s) with the target, and that
doesn't even get into the complexities of maneuvering past a targets
defenses without opening your own guard.
I'm strongly against "moddable melee weapons", because I don't believe you
can come up with a simple system for determining the resulting parameters
of said weapons that makes sense enough to be worthwhile, and a system
complex enough to do so would be more trouble to maintain than simply
enumerating the weapons you can make.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
