### ISSUE TITLE
Painkiller effect from cold prevents interrupts from fire

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#14694]
Probably also affects other fields, like acid.
The lack of interrupts due to lack of pain should probably only affect "passive" sources, such as ongoing effects, radiation and traits.

**Comment by Malkeus** [comment]
Numb is numb though. If you can't feel pain, your brain doesn't assign priority to the input. Take [CIP](https://en.wikipedia.org/wiki/Congenital_insensitivity_to_pain) for instance, sufferers are insensitive to pain and often injure themselves without realizing it. They could burn themselves quite easily by picking up a hot pan and they don't have the instinctual response to a burn of snatching their hand back, because that requires pain input.

**Comment by Coolthulhu** [comment]
It's not about grabbing a hot object and not noticing, more about having a fire suddenly start burning the floor around your feet or smoke choking you out. Or acid splashing at you from the darkness.
Even if not the pain, you'd notice the smell.

**Comment by Malkeus** [comment]
I imagine the lungs wouldn't be numbed by the cold, not til you were too far gone to care, anyway. Acid and water probably feel pretty similar if theres no pain from the acid, and rain doesn't cause an interrupt does it?
Coming at this from a different angle..shouldn't the heat of the fire counter the numbing effects of the cold over the course of a few turns? And THEN the pain sets in?

**Comment by Coolthulhu** [comment]
I don't think the entire legs could ever get cold enough to stop all pain.
Also, currently painkiller effect is global. Meaning that freezing limbs cause immunity to headaches.

**Comment by scorpion451** [comment]
> I don't think the entire legs could ever get cold enough to stop all pain.
Actually, they can, very easily. That's why its so easy for people to get frostbite without realizing it. You get cold for a while and your limbs hurt... and then they stop hurting and you start to feel warm again, because your body has cut off the circulation to your limbs to preserve core heat and the nerves go to sleep just like when you sit on your foot too long. The fire thing, for instance, is actually a common problem with frostbite victims. The person finally gets to a place where they can build a fire or turn on a heater to get warm, puts their feet right next to the heat where the deepest nerves can feel a little pleasant warmth through the outer tissue, and doesn't notice that they're roasting their feet until they thaw out enough to realize they've now got second degree burns *and* frostbite.

 If you've ever had localized anesthetic, its a fascinating similar sensation: your head knows that having someone cut open your toe should really, really, hurt, but all you feel is a slight tingling. When it wears off the area that got operated on hurts like hell, but until it does you could beat on that toe with a hammer and not feel much beyond a little pressure.

> The lack of interrupts due to lack of pain should probably only affect "passive" sources, such as ongoing effects, radiation and traits.

It'd actually be the opposite of this- your core would still be affected by things passive like headaches, radiation pains, chemical imbalances, withdraw, inhaling smoke, etc until you were deep in the danger zone, but things like acid burns, fire, cuts, getting hit, etc that only affect the outer skin and extremities... "Oh, would you look at that. My foot's covered in blisters. That'll probably hurt when I can feel it again."

**Comment by Coolthulhu** [comment]
> because your body has cut off the circulation to your limbs

If the entire leg had no circulation, you wouldn't be able to walk.
Frostbite 
> It'd actually be the opposite of this- your core (the head and torso in cata terms) would still be affected by things passive like headaches, radiation pains, chemical imbalances, withdraw, inhaling smoke, etc until you were deep in the danger zone, but things like acid burns, fire, cuts, getting hit, etc that only affect the outer skin and extremities...

In this case it would be realism against gameplay - one very important reason long actions are a thing is that they can be canceled.
Waiting with "autowait" shouldn't be more dangerous than waiting by skipping turns manually, getting zapped by a shocker should never be totally skipped (even when player is in hazmat), having a glob of acid splash by one's feet should result in an interrupt as if a spitter approached the player etc.

The opposite should not happen. A harmless headache shouldn't trigger a window saying "you got hurt, stop crafting?" because the cases where player would want to say "yes" are very rare.
Prompts are there to inform the player about preventable things. Radiation pains are one, but body degradation due to "Disintegration" mutation is not.

The game should not fight the player by removing menus, skipping important messages or otherwise preventing the player from noticing something that is displayed on the screen.

**Comment by kevingranade** [comment]
This is definitely an unintended behavior, you should be able to detect
danger and react to it regardless of feeling pain.
This might be something we would want to do in a limited way, such as not
reporting damage from crawling through a window with broken glass if the
wounded limb is numb.

**Comment by Coolthulhu** [comment]
I can't reproduce it in the recent versions - the fire causes interrupts even when it doesn't cause pain.
