### ISSUE TITLE
Allow Sewing Kits and Soldering Irons to be usable when near player?

### ISSUE THREAD

**Issue by theglock** [CleverRaven/Cataclysm-DDA#14698]
**If this request has been asked a million times and/or it is exceedingly difficult to accomplish coding-wise, please tell me and I will delete this suggestion.**

I don't know if this is possible, but having the Soldering Iron and Sewing Kit function when nearby would be a good idea, in my opinion.
Working similarly to the Acetylene Torch, if you press the Use Item key or bring up the Execute Action menu, the ability to use both as if they're in your inventory would be much quicker when faced with multiple tasks.

**Comment by Coolthulhu** [comment]
It is doable, but it isn't simple.
This will require a good system for using any item out of inventory, not just those two.

**Comment by mugling** [comment]
> bring up the Execute Action menu

What's the long term plan for this menu, its grown to become perhaps somewhat unwieldy and whilst changes such as the above aren't inherently a bad idea they won't help slim it down any further.

**Comment by kevingranade** [comment]
The action menu should have all the actions the player can take on them, partially as a way to discover said actions, since hotkeys aren't a very friendly way to do so.

Implementation wise, what you want to do is have all the commands arranged on a tree with a relatively low branching factor (5 - 10 or so?) and carefully chosen nodes so that it's intuitive no navigate to the command you want.  I can't remember if the menu shows hotkey mappings next to commands on the menus, but it should.

**Comment by mugling** [comment]
@codemeimes recent PR does most of this?

**Comment by kevingranade** [comment]
Confirmed done.
