### ISSUE TITLE
[Suggestion] (More) Enemies that are 'actually' dangerous.

### ISSUE THREAD

**Issue by harald921** [CleverRaven/Cataclysm-DDA#14728]
When I have played for half a day I often find myself pretty much invincible against most enemies. Hulks are a piece of cake, hordes of zombies are no problem. Only real problem I face is the corrosive zombie.
I often find myself wishing there were more _really_ dangerous enemies. I mean enemies that makes you go "OH SHIT!" and run towards your vehicle to get the hell out of there. Addition of some new enemy that makes you shiver in your sleep? I wish this could be solved somehow. It (for me) kind of defeats the point of playing when you can walk up to one of the 'strongest' enemies in the game and slap it across the face a few times before it lay down and dies. It would be nice to have enemies that makes you want to use your .50 cals and that you REALLY don't want to aproach or even be remotely close to.

Thoughts? Ideas on what could be done?

* Shocker Hulk
* HP buff for Hulks
* HP and Damage buff for Jabberwocks
* Some buffed up variant of the feral predator
* Big buff for the giant worms

**Comment by Coolthulhu** [comment]
HP buff for hulks would be OK, but it wouldn't solve the biggest problem that hulks have:
The ability to stun and knockback them like small zeds, which means that even a mid-game survivor can Power Hit them into a vehicle wreck and kill them without using any weapons this way.

They should gain stun, knockback and knockdown immunity.
Same for Jabberwocks.

Jabberwocks could get a much lower cooldown on their special attack.

Additionally, huge critters could have a scaling on terrain penalty, to prevent rubble and car wreck abuse.

Feral predator variants should wait for the current predator to get nerfed a tiny bit: it needs to become escapable, so that getting spotted by one early on isn't a guaranteed death for low level survivors.
A buffed predator variant could have the ability to pounce for free, as in #14684 and then immediately follow with an impale.

Giant worms aren't really comparable to any of the high level zeds. They're closer to bears.

Also, all high level enemies could gain giant buffs to armor. Monster armor is heavily underutilized right now, leading to quick weapons being much better than heavy ones.
The hulk has armor comparable to what a first day survivor can craft and wear without encumbering self above 9 on torso or legs.

**Comment by chaosvolt** [comment]
So a stun resistance, maybe via a monster flag? Might be a useful feature.

Beyond that...what else? I'm sorely tempted to add my "giant cellar spider" idea I had once. Imagine a basement full of size-small nopes that trade the "bad poison" for "hard to shoot" instead.

**Comment by Coolthulhu** [comment]
> Imagine a basement full of size-small nopes that trade the "bad poison" for "hard to shoot" instead.

Spiders are meaningless post early game due to their incredibly low ability to pierce high-coverage armor.

If you wanted to make spiders scary, they'd need to gain some serious attack.
For example, impale. A swarm of impaler spiders would be badass.

**Comment by sparr** [comment]
As someone who has played for perhaps 200 hours and never gotten to the point that a horde or brute was anything but terrifying... Maybe whatever leads to the character capabilities you're achieving should be nerfed?

**Comment by harald921** [comment]
What about a really slow but armored hulk? Scarred hulk? Of course with a better name. Something that makes you want to throw a really big bomb at it. Or shoot at it. To me, weapons seem to be really lame atm and not really useful apart from the air guns..

**Comment by harald921** [comment]
@sparr Get a sleveless trenchcoat, get an awl pike from any mansion pretty much, get basic tools - perhaps even raid an ants nest for some eggs, and you're good for a LONG time. With some melee grinding, you can go 1v4 against hulks, using rubble/bushes, etc. And 1vInfinity against normal zombies, with corrosive ones and technicians being the only troublesome ones. Chop chop chop, they won't even get close to you.

**Comment by harald921** [comment]
@Coolthulhu Imagine.. Scarabs! https://www.youtube.com/watch?v=lI2raWlzZxU

No but seriously, some kind of small nopes that makes you run to your flamethrower rather than your broadsword would be awesome!

**Comment by chaosvolt** [comment]
What, no giant brown recluse spiders? <3

But yeah, that was just one of my random ideas for adding variety to a specific area, namely spider basements.

More monster ideas for challenge should ideally include both general things for making hordes as a whole a greater threat, but also more niche monsters for specific areas that a late-game character will seek out, to avoid screwing over early-game characters that aren't actively seeking out a challenge.

**Comment by evilexecutive** [comment]
I had an idea of expanding the list of Fungal Zombies to include Brutes and Hulks. Aside from that, there's a great suggestion in the IRC to create a new tile called a Foundry, and staff it with Incendiary Zombies. These zombies would be fire immune, and have various fire based attacks.

**Comment by chaosvolt** [comment]
Could be interesting. That does afford another way to expand zombies in general. In addition to the idea of more dangerous zombies, you could have zombies with a broader range of defensive capabilities, or other things that would allow for less ability to hau through a whole horde using a single tactic.

Expanding how monster armor works would compliment that, of course.

**Comment by evilexecutive** [comment]
I could probably also make a sort of 'endgame' level monster that's essentially a bit of everything. If you want something with pure, balls-out DANGER, you could have a "Abomination", that is a heavily armoured, cyborg zombie hulk. Give it an arbitrary amount of health, the Jabberwock attack, shock attack, and some other abilities that make it deadlier to players.

But it would still suffer the same problem as hulks. At that point we're just making bigger and bigger monsters that all have the same weakness, without fixing the underlying problem. 

I would still like to see more variety of zombies, and a better fleshing out of the evolution trees. Personally I would like to see an Arcane Tree of zombies too, whereby zombies can rarely evolve into necromancers, who become masters, who become Liches(Which have magic based attacks, and a very high regeneration ability).

**Comment by chaosvolt** [comment]
Right. Plus that's one of the things Arcana mod does, is the idea of "boss" monsters in limited areas.

Also? Adding mutant or zombie variants of wildlife that don't yet have any would be good for variety with innawoods characters?

Beavers? Batshit insane banzai-chargers (seriously, there's as bad as moose) but harmless. But giant beavers? X3

**Comment by Chezzo** [comment]
Yeah @sparr, I think you are right, reach attacks need to stop being god mode.

**Comment by evilexecutive** [comment]
Okay, have a description. I don't mean like an actual boss, so much as the "hulk equivalent" to masters and necromancers. 

Zombie Lich:
This creature is now little more than a burned skeleton with thin veins of purple blob running through where tendons should be. It's eyes glow brightly, and a faint whispering of unknowable tongues escapes its empty throat. The lich's mere presence sets you at unease.

**Comment by chaosvolt** [comment]
So...scarred hulks, giant beavers, giant cellar spiders, zombie liches, pyro zombies...

Should we add a zombie hulkamaniac while we're at it? o3o

**Comment by evilexecutive** [comment]
Don't forget more Fungal Zombies. Fungal Hulks and Brutes is a ~!Fun!~ idea as well.

**Comment by chaosvolt** [comment]
Ooh, maybe. Depends on how many types it can be boiled down to. Then again, more variety to fungal life itself could work too. Or maybe fungalized versions of nether creatures, at least the ones that aren't immune like mi-gos.

**Comment by Malkeus** [comment]
Mainline Bio-Weapons!

**Comment by Mecares** [comment]
I like the Idea of Zombie Lich or even Archlich as name for a stronger Necromancer just give him mass-ressurection on a long cooldown and we have a new priority target.

**Comment by chaosvolt** [comment]
Or the simple route would be to give zombie liches both resurrection and upgrading, but that'd be the lazy route. o3o

**Comment by kevingranade** [comment]
To steal from fallout, one of their apex enemies is the deathclaw. Lots of
hp, armor, plus speed and enough armor penetration and damage to cause
damage vs almost any armor.

**Comment by chaosvolt** [comment]
So, mutant chameleon if I recall my lore? o3o

**Comment by kevingranade** [comment]
Less the deathclaw itself and more something that fits that role, in DDA the zombear, hulk, and jabberwock could all easily fill that role in different ways, and a zombull would be an interesting addition as well (have to figure out how a charge attack is going to work in practice).

I also very much agree with Coolthulu that the larger enemies should not be susceptible to stun/knockback/knockdown, though I think that should probably just be having the chance of success scale with relative size/strength (or scale more) rather than an immunity flag.

Giant worms/Grabboids should get a total overhaul. Grabboids in particular should get a reach attack, huge HP, and crazy armor.

All these huge enemies should be basically immune to regular pistol fire and smaller melee weapons.

**Comment by chaosvolt** [comment]
Zomcow? That sounds hilarious.

And hmm. Might be interesting to have tough enemies able to do that.

Also, if worms had a charge-like attack to represent an ability to attack while surfacing, like erupting underneath the player, that might work.

**Comment by harald921** [comment]
@kevingranade I agree with your last statement (and the other ones) - Hulks, and especially jabberwocks, should really make you want to grab the strongest weapon you have and try and _destroy_ it.

**Comment by hitbutton** [comment]
A problem with tuning enemies to challenge late game characters is the effect on the early to mid-game. Right now hulks can appear from day one, and just getting spotted by one can be a near-unavoidable death sentence due to the difficulty of escaping.

If you're adding more challenging enemies, they should probably be prevented from turning up until later in the game - or at least be avoidable.

Increased difficulty for late-game characters could also come from flattening power curves somewhat (reducing the scaling of high skills / stats), which would have less impact on the early to mid game.

**Comment by Coolthulhu** [comment]
> A problem with tuning enemies to challenge late game characters is the effect on the early to mid-game.

That's why I'm advocating making them immune to stun, knockback and knockdown.
A properly built mid-game character can easily kill a hulk by cheesing it, which shouldn't be possible. An "improperly" built mid-game character won't suffer from hulks being made harder to cheese.

As for higher armor - it could be toned down by lowering their HP. That way they would only get more resistant to light weapons, not all weapons.

Jabberwocks don't need brakes on balancing. They are very rare, roar at critters and so don't usually appear unexpected around a corner and have low stats. Those could get crazy buffs just fine.

**Comment by harald921** [comment]
@Coolthulhu Fully agree with this as well. Especially your point on jabberwocks. The "horror" feeling you get when you take the quest from an NPC is quickly taken away when you literally brawl the thing to death after leading it onto a bush.

**Comment by chaosvolt** [comment]
Right. Though like I said, if we want to add more dangerous monsters, those should be in specialized locations so it's more likely that a player won't encounter them early or by accident. Whereas general defensive upgrades like stun resistance are quite sensible for monsters the players might encounter just going about their normal business.

**Comment by i2amroy** [comment]
Note on the stun aspect, but do we scale stunability with size? Because it's kinda silly to see a normal person (or even one with a bigger weapon) stunning hulk. Maybe in that aspect rather than giving them immunity we might just want to greatly increase the stun scaling with size penalty; a robo-muscled-power-armored-sledge-wielding, should hypothetically need to be able to stun or knock over a hulk as I see it, but it should just be out of the reach of most normal survivors.

**Comment by chaosvolt** [comment]
Basing it off of size might be sensible, yeah. If we need further control of monsters that we might want to give arbitrary immunity to stuns, could further have a flag for it. Or do we already?

**Comment by Coolthulhu** [comment]
I guess it's fine as long as it prevents non-bashing melee weapons.
If someone is dedicated enough to stunning to wield a sledgehammer (sledgehammers suck), it's OK. But it shouldn't be a lucky effect on top of a Niten-powered wakizashi crit.

**Comment by chaosvolt** [comment]
That might entail further altering the stun odds based on whether or not a weapon's cut/stab damage is higher than its bash, or possibly the ratio thereof..

**Comment by Coolthulhu** [comment]
Or just total bashing damage having to be above some (possibly semi-random) threshold. An axe stun is fine, katana stun isn't.

**Comment by chaosvolt** [comment]
That might be the saner idea, yeah. This also would allow heavy-hitting cutting weapons to still stun, possibly even against monsters with high cutting resistance.

**Comment by kevingranade** [comment]
> dangerous monsters relegated to specialized locations 

The goal has always been and continues to be to give the player the ability to detect and avoid dangerous monsters.  I'm very against restricting all dangerous monsters to specific late-game areas, though areas that thematically have tougher enemies for some reason is fine.

One thing I've considered is extending peeking to trigger automatically when in safe mode, effectively if you're walking (in other words disabled by running and driving) you peek into the square you'd be entering before doing so, and if safe mode triggers it prevents taking that step (with a notification so that you can then check it out manually).  This would suffer from the usual complaint of inundating people with warnings about monsters they don't care about, but it might improve the situation on balance since it would turn a sensible technique that experienced players used into a pervasive part of the game.

RE: bashing special effects, something like:
```weapon.bash * player.strength * player.skill vs monster.size * monster.strength```
of course with appropriate constants sprinkled in, and some flags enhancing either side would be fine.
The problem right now is all it requires is a successful hit, there are no checks against anything. (the pertinent code seems to be in player::perform_technique() in melee.cpp)

**Comment by chaosvolt** [comment]
> The goal has always been and continues to be to give the player the ability to detect and avoid dangerous monsters. I'm very against restricting all dangerous monsters to specific late-game areas, though areas that thematically have tougher enemies for some reason is fine.

Right. I didn't mean restrict all dangerous monsters to specific areas, just that new additions might be best reserved for logical niche uses.

**Comment by harald921** [comment]
Slightly slightly off topic - how about a buff for the giant ants? I mean, I fear normal ants IRL more than the giant ones ingame. When I see an ant I don't run away, I go "oh boy, eggs and CBM's!" and rush to the entrance. And that is with brand new chars, as long as I got a basic melee weapon. Perhaps just making the workers attack you when you're inside of it would be enough? It would make sense. Right now they just ignore you! O.o

Oh and how about fungal ants? I mean, those creatures theoretically exists irl, but not in Cataclysm. Imagine an ants nest infested with fungal, with corrupted ant queens spewing out more foul ants. Oh boy, that would be !FUN!

**Comment by chaosvolt** [comment]
Odd, I could've sworn there were fungal ants. o.O

**Comment by ValidAQ** [comment]
There are. A single variation, basic "fungal ant" monster.
They are weaker than normal ants, though, not a threat.

**Comment by chaosvolt** [comment]
Fungal soldier ants might add variety then.

Also regarding ants...drones. Something that can fly might be useful for adding to diversity for ant swarms. Less useful in the anthill itself though.

**Comment by harald921** [comment]
Oh wow, I am stupid. Yeah but, my statement about fungal queens + soldier ants still stand! >.<

**Comment by chaosvolt** [comment]
I'm not sure about fungal ant queens. At least, not any spawning.

Rather than have fungal ant queens potentially spawn, one COULD include them solely for the purpose of fungifying ant queens. While such a situation would be rare, it'd be very Fun to see.

**Comment by harald921** [comment]
No no, not spawning. Just being infected. Perhaps too unlikely to happen for it to be implemented but.. Yeah, anyway!

**Comment by chaosvolt** [comment]
That;s what I figured, yeah. It would be hilarious when it does occur though.

**Comment by SunshineDistillery** [comment]
It doesn't matter how powerful you buff up melee monsters. A player can always run away and come back to run it over with their car or find some way to kite it through it through terrain.

What the game needs is more NPCs with guns. Or even if they aren't full on NPCs, but are just human-monsters like CHUDs. 

That adds serious challenge and makes fighting melee a situational/tactical choice rather than a no-brainer. Enemies with guns should be the second tier of danger for enemies. Right now turrets and robots sort of fill that role, but turrets are stationary and robots are easily destroyed by EMP grenades.  Random NPCs are a threat now, but many people don't play with them because they're buggy or weird or spawn in places they shouldn't.

**Comment by chaosvolt** [comment]
> What the game needs is more NPCs with guns. Or even if they aren't full on NPCs, but are just human-monsters like CHUDs. 

This is related to an idea I suggested on the forums. Add more variety to the static NPCs that show up.

One thing that would faciltate this is if we had an "NPC group" function to allow for random selection of a set variety of NPCs. So a house could have, say, a 1% chance of spawning a static NPC. The NPC group used could allow for random quests, random NC classes, even the risk of it having a bandit instead of a friendly survivor, all while in static mode and avoiding the sheer, stupid clusterfuck that is dynamic mode.

**Comment by SunshineDistillery** [comment]
I might be able to that a little bit right now. If there is a null value for NPCs, I could place an NPC in a mapgen file with a 1 out of 5, or 1 out 10 chance of appearing.  Or I could make an occupied/fortified house with a really low weight. No random quests though.

**Comment by chaosvolt** [comment]
The easiest first step would be adding static NPCs where there's no real need for random settings. Like in cabins, add a chance of an NPC of NC class hunter, default faction, and maybe the jabberwock quest.

**Comment by harald921** [comment]
Probably off topic - but I'd really wish NPC's didn't show up on the map. Takes away a lot of the surprise. Only times I am surprised now is when I am walking into my deep underground locked down base to find out some bandit is creeping in a corner and try and rob me, wielding a .22 pipe rifle or something.

**Comment by chaosvolt** [comment]
Only dynamic NPCs get reliably shown on the map, if I recall. Static ones only sho once they're in your reality bubble, and by then it may already be too late.

**Comment by harald921** [comment]
"drop your weapon! *waves knife at me*"
"oh no, please don't hurt me *drops SMG-gatlin gun*... oh wait"

No but - to go back to the subject. How about adding some ranged abilities to the Z's? I mean, the corrosive one proves to be effective (too effective IMO, but that's for the other issue I created) but how about letting hulks throw things, or adding some zombie that shoots out some kind of needles? (Hedgehog needles, sorry - not a native English speaker)

**Comment by chaosvolt** [comment]
What next? Zombies with guns? ;w;

**Comment by Coolthulhu** [comment]
Soldiers evolving basic gun usage could be cool.
Their weapons would be damaged making them rather weak and inaccurate, but it would still make them dangerous at close range. Would require some ability to check out what they're holding, though.

**Comment by chaosvolt** [comment]
Maybe. so basically Doom: Dark Days Ahead.

**Comment by evilexecutive** [comment]
Heh, I still remember the old days when dynamic NPC's could just teleport
randomly all over the world when you were sleeping. I would be sitting nice
and cozy inside my Dorf Fortress, with full power armour and spooning a
zweihander.. When suddenly I wake up to..

"DROP YOUR ZWEIHANDER MOTHERFUCKER!" - Random dumbass who teleported
through an array of tunnels going through rings of blade traps and
murdertrenches. Dumbass is wielding a .22 pipe rifle.

Actually, come to think of it I don't even want to see NPC's get any
smarter. I still get my jolly kicks from watching them kill themselves in
stupid ways.

**Comment by chaosvolt** [comment]
Bleh, nowadays they just spawn inside your base to begin with,

**Comment by RadaRadaRada** [comment]
Zombie cops could have some martial arts, like disarms, joint locks, blocks and throws; defensive stuff like that. And soldiers could use some aggressive techniques instead. Cool thing would be if qualities like these could be inheritable between mutating.

**Comment by harald921** [comment]
Can confirm that they spawn inside your base. Often at the same tile. Had a cave where they always got stuck inside a small crack in the wall and wouldn't react unless I actually went there to check if I had gotten a new one.

**Comment by SunshineDistillery** [comment]
Instead of zombies with guns, why not add something like Fallout's supermutants? Intelligent enough for tool-use but still dumb and monstrous.  Instead of NPC dialog, they could just use text snippets like mi-gos do. 

I was thinking for weapons, a human-monster could use a 'built-in' weapon like robots do, but on death drop a random gun of that caliber. That way you could fine tune the dummy weapon to be as weak or as powerful as you want without worrying about them getting hold of BAR or a flamethrower.

**Comment by Coolthulhu** [comment]
> Instead of zombies with guns, why not add something like Fallout's supermutants?

Because we already have zombies with guns on them and because there already are many things hostile to zombies that use guns but nothing allied with them that does it.

**Comment by hitbutton** [comment]
Flavor-wise, using guns seems a bit wrong for stumbling zombies. Although I guess grenadiers are already down that road.

> adding some zombie that shoots out some kind of needles?

This sounds a better option flavor-wise for adding zombies with ranged cutting attacks (e.g guns).

**Comment by Malkeus** [comment]
I believe the blob is a hive mind, correct? How tapped in to that consciousness is the average zombie soldier? Is it telepathic or does it require physical contact to communicate? Do the blob bits infecting a zombie soldier have access to his/her memories, or only the use of the muscles?

What I'm getting at is, if the blob can access the memories of its host, soldiers should be well capable of firing their guns or use self defense abilities the military teaches. If the blob can share that knowledge, there's no mental reason for ANY zombie to be unable to fire a gun or use martial arts. The only restriction would be physical capabilities of the host body.

**Comment by hitbutton** [comment]
I'm sure you could find some blob justification for it, but its still out of keeping with traditional depictions of zombies. If they can remember how to fire a gun and use martial arts then why can't most zombies even walk in a straight line, or get through a window without bashing the wall next to it?

**Comment by Malkeus** [comment]
They aren't typical zombies though. They are corpses being puppeted by an alien organism.

**Comment by Malkeus** [comment]
I'd like to limit the blob to communication through physical contact, as that fits the current gameplay best. Then we can look at a basic zombie as being a new crew in a new ship, and as the blob units gains experience operating the machinery(corpse), they would evolve (like they do now) greater capabilities and coordination.

**Comment by Coolthulhu** [comment]
> If they can remember how to fire a gun and use martial arts then why can't most zombies even walk in a straight line, or get through a window without bashing the wall next to it?

Soldier zombies do walk in straight lines.
Scientists and grenadiers can use electronics. Hipfiring a rifle is easier than that - an ape could do it without training.

Martial art thing is actually a bionic, not a natural skill.

> its still out of keeping with traditional depictions of zombies

So are zombies that spit acid.

**Comment by hitbutton** [comment]
Low intelligence is a defining attribute of zombies, where "Doesn't spit acid" is not. Vomit zombies of various types are a relatively common trope.

Is there any reason to be specifically set on gun usage, rather than a more mutationy explanation for ranged attacks?

**Comment by Malkeus** [comment]
What about an evolved version of the soldier which has gained the dexterity to shoot it's gun, either because the blob has gotten access to the corpses memories of training or development of some sort of awareness like the 'zombie' masters have. This would leave the soldier as the typical heavily armored nightmare it can be right now, and provide ever increasing challenge as time goes on. They don't even need to be accurate, as the gunfire would attract more zombies and they would be deadly dangerous even if they didn't hit you.

**Comment by Malkeus** [comment]
[08:56] <hit_button> I think if zombies did have the ability to shoot guns, they should at least shoot them full-auto in entirely random directions
[08:57] <hit_button> for comedy reasons
[08:57] <austintrigue> give a zombie a flamethrower!
[08:57] <austintrigue> just call it asshole zombie
[08:57] <Malkeus> nah, that's perfect hitbutton
[08:58] <Malkeus> indiscriminate bullet spraying because all it can do is pull the trigger
[08:58] <Malkeus> it doesn't have enough control to actually aim

**Comment by harald921** [comment]
Zombies with guns.. Eeh, big no from me. It just doesn't feel right. Next thing you know the zombies are driving cars and going to their jobs daily. :)

**Comment by RadaRadaRada** [comment]
Well, if everyone here is expressing their opinion on gun totting zombies, i will do so too: I don't really mind zombies using guns. It doesn't really break my suspension of belief of what "zombie" could do. It would be cool to meet them at roadblocks and military bases, spraying gunfire blindly in general direction of player as they approach.

**Comment by chaosvolt** [comment]
Hmm. I'd probably be in favor of limiting gun-toting zombies to joke encounters, ideally referencing Doom. XP

**Comment by LlubNek** [comment]
> Next thing you know the zombies are driving cars and going to their jobs daily. :)

Cubicle Zombie -- Not much has changed for this guy since the apocalypse, save that he smells a little worse.

**Comment by kevingranade** [comment]
Just FYI, this is an absolutely perfect example of a discussion that should be on the forums, there is no way we're leaving it open until we act (either implement or formally reject) on all the ideas put forth, and once it's closed it'll be buried and most of the ideas never seen again.

Alternately, if you think your idea you presented here is a good one, you might want to add some detail and at least give it a dedicated issue.

**Comment by LlubNek** [comment]
If you want more ranged zombies, I'd go for fusion blaster zombies, or firestarter zombies (CBMs, not guns).

**Comment by chaosvolt** [comment]
This would likely need archival on the forums, yes.

**Comment by Malkeus** [comment]
I started a post on the Drawing Board, it links back here and includes a piss poor listing of the ideas presented here.

**Comment by chaosvolt** [comment]
Ah, nice.

**Comment by joneskun** [comment]
Been missing those VERY early (I'm talking day 1-2) screen-filling wander spawns that have new survivors crapping their pants and hiding under blankets.

**Comment by kevingranade** [comment]
Closing in favor of the forum thread.
