### ISSUE TITLE
Potential issue with AOE melee techniques?

### ISSUE THREAD

**Issue by SeanMirrsen** [CleverRaven/Cataclysm-DDA#14723]
After seeing shudokai on the IRC try and fail to get the lajatang's Spin Attack technique to activate, I delved into the code (I can't compile it on my own, weird compiler issues) to see what could be wrong. I stumbled on this bit in `melee.cpp`:

        // if aoe, check if there are valid targets
        if (tec.aoe.length() > 0 && !valid_aoe_technique(t, tec)) {
            continue;
        }

For some reason the check is *against* `valid_aoe_technique`. Now, `valid_aoe_technique` is properly labeled, it returns `true` if the technique is valid. More importantly - 

        bool player::valid_aoe_technique( Creature &t, const ma_technique &technique,
                                  std::vector<int> &mon_targets, std::vector<int> &npc_targets )
        {
            if (technique.aoe.length() == 0) {
                return false;
            }

It returns `false` when `aoe.length()` returns zero. And since the original check will check for `aoe.length()` returning greater than zero, and `length()` only returns non-negative values, this results in, basically, this hilarious setup:

        if (tec.aoe.length() > 0 && !tec.aoe.length() > 0) {
                    continue;
        }

Methinks there be a typo. :P 
Now, I'm obviously not an expert, and I can't even compile the code to check, but I don't recall ever seeing an "aoe" type attack at work. Ever. Impale, wide attack, spin attack, they just never happened for me. So this being an error does seem somewhat likely.

**Comment by Coolthulhu** [comment]
Such is the fate of underbalanced features. No one notices when they break...

If someone decides to unbreak this, it may be a good idea to also buff them in the same PR. Even if just by making them cost no extra moves compared to regular attacks.

**Comment by ejseto** [comment]
Your logic is wrong. Just because aoe.length() == 0 returns false does not mean that aoe.length() != 0 returns true. Assume aoe.length() = 1. Then that conditional in valid_aoe_technique() does not return anything. The rest of the function determines whether it is indeed a valid aoe technique, i.e. it must both *be* an aoe technique (aoe.length() > 0) and must have valid targets. 

Furthermore, the continue statement *prevents* the technique from being considered. Notice the other conditions that lead to continuing, like being a dummy technique. If your logic were correct, it would *never* continue, meaning *all* aoe techniques would be valid, and you would see them all the time.

**Comment by SeanMirrsen** [comment]
Hmm. That does make sense. Okay, then.

If I could compile the code I could've tested for that. :\

I guess I'll keep experimenting and looking through code.
