### ISSUE TITLE
Give hacksaws "charges" to represent blades wearing out.

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#14788]
Hacksaws are currently indestructible, when in fact they become dulled quite rapidly when used for certain things.  This could be represented by giving the tool "ammunition" of the type "hacksaw blade".  Handling it nicely would involve overriding the reload code to only swap blades as they wear out instead of adding their charges together, but surprise, that's how batteries should work anyway, so that would kill two birds with one stone.
Possible further extensions could be to add different blades with different quality levels, but other than different durabilities that's probably uncalled for since I don't think the time spent is a major factor.

**Comment by nanovad** [comment]
Couldn't this apply to most anything? Circular saws, axes, etc?

**Comment by kevingranade** [comment]
Circular saws yes, axes not so much.
Hacksaw are just the most egregious example I'm aware of.

**Comment by Rivet-the-Zombie** [comment]
Hacksaw blades are meant to be disposable, like circular saw blades. Stuff like axes are meant to be sharpened when they get dull, so this wouldn't really affect them.

**Comment by Coolthulhu** [comment]
That would change balancing of early crafting quite a lot, as there are no improvised hacksaws. It even could lead to the situation where it's cheaper to bash down vehicles to get frames than to dismantle them properly.

Then there are toolboxes, which include hacksaw capabilities, but already have ammo.
And toolsets, which are bionics and thus can't have ammo.

**Comment by Rivet-the-Zombie** [comment]
Those are very good points, @Coolthulhu.

**Comment by Malkeus** [comment]
I don't see anything wrong with under-equipped players having to find alternatives to tools. 

Toolboxes are a problem. Totally in agreement there.

Bionics are made with advanced materials that don't wear out. It's a monomolecular hacksaw.

**Comment by Coolthulhu** [comment]
> I don't see anything wrong with under-equipped players having to find alternatives to tools.

Bashing down frames is rather tedious and weird, though. There is a safe way to do it - by using collision "shaking" damage to damage only the frames. This could get exploity.
Plus, it doesn't train mechanics and "uncrafting" vehicles is one of the most important sources of early mechanics.

I'd say we need some makeshift mechanic of ripping vehicle parts first. Something that would damage them on removal or have a random chance of destroying them or something like that.

**Comment by Malkeus** [comment]
I started learning about cars by swapping out alternators, starters and spark plugs; I didn't rip cars into pieces. I will say that when I did start ripping cars into pieces I learned a lot more about how they were put together than I did doing simple part swaps and brake jobs, so your makeshift mechanics idea has a lot of merit. Without experience using tools for simple jobs, I wouldn't have been very successful removing transmissions, motors and suspension parts without damage.
I think we could separate cars into simple and complex jobs.
Simple:
Batteries, alternators, mufflers, seats, seatbelts, doors, smaller cargo units, windshields, lights, light armor(fragile), tanks, frames < 6 (ie: gocart sized)

Complex:
Large frame assemblies, engine swaps, axle assemblies(especially steering), generators, solar cells(wiring), turrets, crafting units, refrigeration units, heavy armor(sturdy)

I'm sure I missed a few, but you get the idea. This would mesh well with Coolthulhu's idea of 'ripping' parts with a chance of damaging complicated things.

**Comment by kevingranade** [comment]
Malkeus beat me to it.
All I'll add is perhaps we should allow some disassembly with crowbar or
similar (not the frames obviously, but some less well secured parts), and
possibly make hacksaw craft able with the right tools, no idea if that's
feasible.

**Comment by Rivet-the-Zombie** [comment]
Very good information, @Malkeus!

As a further note: most everything in the 'simple' list should be handled with screwdrivers and wrenches, and not require a welder to install, or a metal saw to remove - batteries and a few other components already do this to a degree.

**Comment by Coolthulhu** [comment]
The "complex" stuff could also require actual welder and not allow duct tape.
Though installing new frames should probably always cost something.

**Comment by chaosvolt** [comment]
Hmm. An interesting concept. It would stand out a bit to have hacksaws need replacement blades, when knives and similar tools need no sharpening or anything beyond the typical generic structural repairs.

We could go for full consistency and make x-acto knives use charges too, but that would only be a pointless flavor detail unless fine, razor-like blades become important for crafting (higher cutting quality for example).

And having said all that, there's also the issue of multitools and other sources or low sawing quality. While the fact they're not as good overall as a hacksaw allows it to remain logical in implementation, it still would draw attention to the difference.

**Comment by Malkeus** [comment]
@kevingranade Peripherals could possibly be removed with crowbars, but there should be a very large chance of damage. On the majority of bolt-on parts, the portion that the bolt run's through is integral to the assembly. At the very least after damaging a part you would need a welder to have any chance of securing it to a new motor. And that's discounting the dissimilar metals problem.

@Rivet-the-Zombie Nearly every part on a car can be removed or installed with a wrench(various sizes), a screwdriver(various types) and a crowbar(crowbar is needed after removing nuts/bolts). Some parts need winches. Almost no parts aside from the frame need a torch or sawzall for cutting, unless you are trying to save time. A welder would only be needed to build custom frame assemblies for parts made by different manufacturers. For the parts we currently work with, custom frames would work just fine. I couldn't see hooking a transmission from a car to a truck engine working in any scenario, without some magic technical abilities coming into play.

@Coolthulhu Duct tape is awesome. Not as awesome as we've currently implemented it (it's basically jb weld in tape form), but still pretty awesome. Needs work. I agree with the point on frames, but I'd suggest making light frames constructible with duct tape, but limited in cargo part capacity.

@chaosvolt I think low quality tools like the multitool should wear out and need replacement. If individual parts of the multitool could wear out it would be ideal, but an overall durability would be acceptable. The current dynamic is find-one-tool-find-a-tool-forever, which isn't very conducive to sustained exploration.

**Comment by Rivet-the-Zombie** [comment]
@Malkeus, you're preaching to the choir when it comes to talking to me (ASME weldor and ASE wrenchtwister) about cars and metalworking. What we have to keep in mind is that we don't want the vehicle system to become too confusing to folks who aren't particularly familiar with such things in real life.

A simple division between 'frame and body pieces' and 'important fiddly bits' vis-à-vis requiring welding versus hand tools alone seems like a close enough simplification of things to me, how about you?

**Comment by Malkeus** [comment]
@Rivet-the-Zombie  I'm good with that distinction. We'll assume that a few years in the future someone came up with universal peripherals that were so much better than the competition that everyone adopted them. Lets call them RivMech. ;) All future car builders need to do is build the appropriate shaped frame to hold a piece of RivMech machinery, and all is well.

**Comment by Core0verload** [comment]
Hacksaws are already hard to find if you are unlucky with hardware stores and public works, and having them wear out would make them too rare to use. I would just switch to using toolboxes, toolbelts, toolset CBM or anything that provides metal sawing and has no charges.

On the other side, using screwdriver, crowbar and wrench for car assembly/disassembly is a good idea. From my experience, anything electronics-related could be removed with a Phillips screwdriver and a flat screwdriver (for prying).

**Comment by Malkeus** [comment]
Maybe hacksaws are too rare atm? I know of about 20 places I could find a multitude of hacksaws if I wanted one. Probably close to 50 if I REALLY wanted one. And a half dozen of those are on my street. And that's just within my city. Imo, every garage should have at least one, all department stores should stock them(they aren't a survival item, why would they run out?) and all hardware stores would have several and refills besides. 

You are exactly right on the electronics side of things. I've changed stereos with a butterknife and some electrical tape. The electrical tape was optional/for safety.

**Comment by Coolthulhu** [comment]
A lot of stuff is intentionally less common than IRL.
Though I'm not sure if common chainsaws would have a significant effect on game balance - their most important role is dismantling vehicles, which currently requires 2 mechanics (even for stuff like seatbelts) anyway.

Depending on how fast they run out, this may change hacksaws from tools to resources.
How fast should they run out?
If it was to run out as slowly as acetylene torches, the whole idea wouldn't change much - current acetylene torches have a very low "charge multiplier" on all crafts and can easily last for seasons.
If it is to run out quickly, it might be a good idea to explicitly use hacksaw blades as resources rather than having the player manually replace the blades all the time. This would also prevent using toolboxes and toolsets to get free sawing.

**Comment by aeoo** [comment]
I agree with everyone, but I am agreeing more, if that's possible, with @Coolthulhu.  What I mean is, I think we should be more concerned with keeping the game fun than with realism.

That said, if the game models equipment wear, why just the hacksaw?  It makes absolutely no sense to single hacksaw out.  It would need to be a game-wide mechanic that affects everything.

So for example, a wooden sawing needle.  It has charges too.  And I seriously doubt wooden sawing needles last forever.  These types of needles need to be re-crafted, I think, if we go with the proposal of equipment wear and tear.  Or take for example makeshift fishing hooks.  Can these things really be used forever?  I doubt it.  Or certain types of animal snares.  Etc.

So this would be a game-wide change with a *massive* game-wide rebalance.  Many items would need two kinds of charges then too.  Lots of rare items would need to be tweaked to be more common.  And so on.

This is possibly fun, because it will increase the incentive for continual exploration, but it will possibly be annoying because the incentive seems to be a tedious one.  Keeping my tools sharp isn't much of a life or game goal if you ask me.  I'd rather the game revolve around uncovering the mystery of the blob infestation and aliens, and perhaps establishing a safe and sustainable enclave to preserve some chunk of humanity, or something like that.

So I think the proposal is overall an increase in fun and realism, but it requires a *major* game overhaul across the board, and a complete rebalance of everything.  And it's possible to increase the fun of the game in other, perhaps less laborious ways too.

Just some thoughts.

**Comment by Malkeus** [comment]
Aeoo has a point. I may use a hacksaw blade for every foot of frame I cut(Ok, I only had to do this a couple of times when the power was out, but it's a real number), but that doesn't mean I want to do the same in the game I play. Searching for resources has a place in the game, but it's possible to go to far. I personally would like to see hacksaws remain at or slightly above their current rarity, but the extra hacksaws you find should help rather than be completely useless. Making them wear out at acetylene torch values would be fine by me, so long as they do wear out. We can revisit the exact amount of wear per job later on. 
@Aeoo needles should wear out too, but if we went anywhere near real world wear values we'd be replacing a needle for every piece of clothing, which would be tedious.

Massive game wide overhauls shouldn't be ignored simply because they are massive game-wide overhauls. If it's tedium you need, give me direction and I shall deliver.

**Comment by Rivet-the-Zombie** [comment]
These are all good ideas, but I think that if all that a bit of added realism adds is tedium, then perhaps that particular aspect needs more thought before implementation.

**Comment by Zireael07** [comment]
Let's try the simple/complex vehicle part split before trying to figure out at what rate hacksaws should 'use up charges' (=get dull)

**Comment by Malkeus** [comment]
The current mechanic is: Find a hacksaw and 2 welders, build a giant deathmobile. And you only need 2 welders because you need one to install the vehicle welding rig into your car. A jack is a bonus item that you only need if you want to add more axles. 
The simple/complex split is necessity, but tool charges will be a necessity as well if we want building a vehicle to have a sense of accomplishment instead of being a given.

**Comment by aeoo** [comment]
@Malkeus "Massive game wide overhauls shouldn't be ignored simply because they are massive game-wide overhauls."

I agree.  I hope nobody gets me wrong.  At the end of the day, if the dev team decides this is the way to go, I personally would enjoy the end result.  Which is why I said I agreed with everyone to begin with.  CDDA would, imo, be a better game with equipment wear and tear being a serious and balanced (somewhere between realism and fun) game mechanic.  If people think it's worth putting every other idea on hold to implement this, OK.

I still remember @Coolthulhu talking how after the 3D overhaul is done, the next big thing he wanted to contemplate was the NPC overhauls.  I was kinda looking forward to those myself.  Wear and tear is fun too, but if ends up competing with an NPC overhaul those sounds you hear are me sighing, lol.  Of course I also realize the dev team is big enough that everyone can work on different stuff all at once.

**Comment by aeoo** [comment]
Also @Malkeus , I loved all your ideas re: "The simple/complex split" up above.  I think a lot (or some?) of your ideas can be implemented *without* an introduction of an entirely new game-wide mechanic with the associated rebalance of a lot of stuff.  So, there is some low hanging fruit too I think.

I still think it would be weird if wear and tear affected only hacksaws or hacksaws and a few other items.  It would be strange I think.  I think it's best to either go whole hog on the wear and tear idea or to leave it alone, personally.

**Comment by aeoo** [comment]
Don't all items have an "item health" measure already?  It's represented as "||" when at full health (depending on game options).  Don't hacksaws have those item health parameters?  Is it too crude to just apply damage to the hacksaw that way?  Maybe items don't need two charge parameters.

So for example, improvised lockpicks already wear out with use.  And this is modeled through damage to the item and not through charges.

So maybe just apply this already-existent mechanic more consistently?

**Comment by Coolthulhu** [comment]
Hacksaws are different from needles and makeshift hooks: you can't quickly craft a replacement from readily available materials.
Wear and tear should be limited to the stuff that would actually get their availability restricted by that.

> The current mechanic is: Find a hacksaw and 2 welders, build a giant deathmobile.

Do welders wear out IRL?
Maybe welding is simply way too cheap in terms of energy. Currently you can connect two frames of any size using energy contained in a handful of AA batteries. If welders instead consumed energy from a car battery contained in inventory or something like that, it could easily be increased by a factor of 10 or so.

> Don't hacksaws have those item health parameters? Is it too crude to just apply damage to the hacksaw that way?

Crafting system wouldn't support that well and it would have very low granularity (a single use would have to randomly damage the hacksaw by 20% or not damage it at all).

**Comment by aeoo** [comment]
So I believe we have "||" then "|\" then "|." and so on when it comes to item health.  Is this simply not granular enough?  Is that the issue?  Charges (a numeric value) would be more granular.

**Comment by aeoo** [comment]
@Coolthulhu "Crafting system wouldn't support that well and it would have very low granularity (a single use would have to randomly damage the hacksaw by 20% or not damage it at all)."

I see.  Maybe item health is what needs overhaul then.  Maybe it should be shifted to a percentage value.  But item health is distinct from charges and is displayed on the left side of the item name.

**Comment by aeoo** [comment]
BTW, even an item health ranging from 0-10000 could be represented to the player exactly as now.  I just need to know when to replace the hacksaw.  I don't care about the minutia of its true condition.  So the game can track all item health in a very fine grained manner under the hood, but still represent it to the player in a simple-to-digest format as now, and it wouldn't be a fundamentally new game mechanic, since item health is an extant mechanic.  Just a thought.

**Comment by Coolthulhu** [comment]
> Maybe item health is what needs overhaul then.

I don't see a good reason to change item health system for crafting purposes. Hacksaws would only get damaged by crafting, so charges are fine here.
Combining item health and charges would make sense in the case of tools that wear out that could also be used as weapons (or armor), but currently vast majority of tools either doesn't wear out or can't be used as viable weapons.

**Comment by aeoo** [comment]
@Coolthulhu This situation is already happening with the fire drills.  And fire drills are easily made just as the wooden needles.  I agree with your above post, but it seems weird that sometimes item health and charges are used to represent item's condition.  But that weirdness is happening with the fire drills already, so it's nothing new I suppose.

To me charges best represent transient qualities.  Like for example, fire extinguisher has pressurized contents and those contents are the charges.  The fire extinguisher mechanism can be in good health and be missing its contents.  Or a battery, esp. if it's rechargeable.  The battery is undamaged but its ability to do useful work is measured in charges.

When it comes to things like hacksaws, the health and the ability to do useful work seem to be one and the same.  Ditto fire drills.  Ditto wooden needles.  You say wooden needles are easy to make fluff, but so are fire drills, imo.  The most basic fire drill is just two sticks, basically.  It doesn't, strictly speaking, need cordage.

**Comment by aeoo** [comment]
Maybe with hacksaws you can conceive of the condition of its blade's teeth as charges and the item health is the condition of the rest of the blade.  Or maybe the hacksaw frame's condition is health and the blades are charges.  In this case, I should sometimes find packs of hacksaw blades.  Not one.  But like 50 or 100 hacksaw blades together in a pack.  Then I can switch these blades into out and of the hacksaw frame.  Then the game would have two items: the hacksaw frame, and the hacksaw packs with lots of blades.  And maybe once in a while you'll find a loose hacksaw blade somewhere, why not.

**Comment by aeoo** [comment]
It's going to be weird to take a disposable hacksaw (blade or frame or both?), add it to a firearm repair kit and end up with a permanent 1 fine sawing quality that only needs batteries.  I believe @chaosvolt mentioned this above already.  So if we really want to be realistic, then certain things will need more than one separate charge value to keep track of the various consumables.  You'll have items like '|| firearm repair kit (100) (300)', where 100 is your hacksaw blade consumable, and 300 is battery consumable, and it's not 100% obvious which value signifies which consumable.  Maybe this could be explained in an item description or a convention would have to be defined that explains how to read those values in parens.  Right now it's easy because we only ever have one possible consumable per item.  Ditto toolbox and survivor utility belt and possibly other items.

**Comment by aeoo** [comment]
Maybe all the kits are just pseud-items that aren't needed?  After all, a kit is simply a way to pack some items together, efficiently.  Isn't that kind of a generic skill that a survival would have and always use?  If I put 5 tools in a box, why would I get magical volume savings?  On the other hand, if I learned to pack things better, that makes sense, however that skill should be separate, imo from toolboxes.  It's a general item packing skill that should apply to any and all items.

**Comment by nanovad** [comment]
The entirety of this mechanic needs to stay mostly the same (I'm against this) or have a large overhaul. 
A possible change, instead of having two "charges" in parenthesis, would be to display item health by percent instead of the current ||->|\->|. etc mechanic. I agree with the whole "tools should wear" idea though. The largest problem here is balance, as others have mentioned. I'm still using a hacksaw I found on day 8 (its ~day 30 now and I've removed dozens of vehicle parts.) However, I don't want to carry 30 blades around as well as a hacksaw, just so I can disassemble a vehicle. Instead of having charges, what if the blades were dealt with as ammo? You could have a hacksaw contain only 1 blade at a time and need to be reloaded (this might require a partial disassembly field for vehicle parts though), but would that classify it as a firearm?

All in I'm not sure this can be done effectively with current game mechanics. I think there needs to be a new system to track tool wear.

**Comment by SeanMirrsen** [comment]
> If I put 5 tools in a box, why would I get magical volume savings?

Because.. you put the tools in a box. You now only have the volume of the box to contend with.

I'd like to perhaps point out that, under, say, the container-based inventory system, displaying the various charges of a tool with multiple charges would be simple, if not quite as compact.

    b ╥ toolbox
    g ╟ screwdriver set
    f ╟ hammer
    R ╟ wrench
    y ╟ duct tape (180)
    j ╙ hacksaw blade (40)

**Comment by chaosvolt** [comment]
> These are all good ideas, but I think that if all that a bit of added realism adds is tedium, then perhaps that particular aspect needs more thought before implementation.

This is pretty much the big reason to be wary of this idea in general.

**Comment by Malkeus** [comment]
The only truly indispensable part of a hacksaw is the blade. The rest of it
is just a convenience. I've made many 'makeshift hacksaws' using a blade
and some duct tape. I like the idea of loading blades into a hacksaw like a
gun, with 'ammo' being expended as its used. The hacksaw blade alone could
have a lower rating than the hacksaw in its proper handle to represent the
leverage bonus you get from the handle. Blades should wear out at about the
same rate as acetylene, but I think acetylene should be used up about 30%
faster. Ideally the hacksaw and torch use would vary depending upon the
material being cut/melted. Sheet metal is pretty easy to cut, steel frames
take a bit more effort and composite armor would probably be brutal to cut.

**Comment by Coolthulhu** [comment]
> Blades should wear out at about the same rate as acetylene

That would mostly negate the point of them wearing out, though.
Acetylene torch can be used 250 times before it runs out. That's enough to dismantle a tank.

**Comment by chaosvolt** [comment]
That would sharply reduce the annoyance factor it'll cause though. As with acetylene torches, it would cause the player's motivation to seek out new places to scavenge to be more long-term. :V

**Comment by Coolthulhu** [comment]
But it would negate the while point of limiting the use.
And it wouldn't motivate the player, because a single blade would last enough to construct a moderate size deathmobile.
For wearing blades to matter at all, there needs to be a choice between using the blade or not using it. Giving it 250 uses would make it only really matter when grinding for pneumatic rifles.
With acetylene torches, one fully charged item is enough for everything less than of months of repairing the entire vehicle every time it is scratched.

And if annoyance factor was more important than actual gameplay impact, there would be a better solution than 250 use blades: infinite use blades.

**Comment by Malkeus** [comment]
That's why i followed up by saying the torch should run out faster. Having
a concrete number of uses instead of just my impression from gameplay makes
me even more certain they need toned down. 30% was a guesstimate, after
seeing your comment i think 50% reduction in uses would be better. And
hacksaw blades should have a similar number of uses. They could remain
relatively rare like the torch but still have useful life spans.

Imagine breaking down after a run in with a horde, breaking your last
hacksaw blade while fixing the damage and having to go on a madmax style
quest to retrieve tools (and gasoline) from a nearby town. Substitute any
tool for hacksaw in that sentence. Tools should be something you can break
and need to replace before advancing. Right now y you can use a tool
forever, there is no need to grab more than 1 of each, they become trash
after you have that first 1. All we need to horde is batteries to keep them
going.

An interesting mechanic could be random damage to a tool add its used, but
I think that would require a more granular item health system. Such a
system would make sewing less panic inducing as well...

**Comment by Coolthulhu** [comment]
>  Imagine breaking down after a run in with a horde, breaking your last hacksaw blade while fixing the damage and having to go on a madmax style quest to retrieve tools (and gasoline) from a nearby town.

That's why I'm saying it needs significantly less uses than current acetylene torch.
With those, a single drop will almost certainly last you long enough to get a second drop. And once you have a vehicle, there is no choice between picking and not picking tools - all tools will fit inside just fine.

If hacksaws are to become a resource rather than an infinite tool, they should most often be found in a used up, sorry state, not bundles of 50 fresh blades that would last a year even if used all day every day.

**Comment by Malkeus** [comment]
Are you purposely ignoring the parts of my responses where i say the torch
needs to be toned down and the hacksaw would match its toned down uses? If
you think the hacksaw would be better at 50 uses per blade, i could get
behind that as well.

**Comment by chaosvolt** [comment]
Hmm. Then we'd still need to select a usage rate that's enough to be meaningful, but *again* is not such that it serves no purpose except to annoy players.

**Comment by Malkeus** [comment]
Current uses on a torch is 250, it could be half of that and easily still
be useful for days before you needed to get another. 100 uses might be
better, that's enough to maintain a car for awhile or build a quarter of a
death mobile. The hacksaw could match those numbers or perhaps be 3/4 that,
depending on the rarity of blades.

I think several days of tool use per blade/tank would be sufficient without
being annoying, without tripping over the line into pointlessness.

**Comment by kevingranade** [comment]
I'd expect to have to change
blades on a hacksaw multiple times while disassembling a single car. I'd
also expect to use most of a hacksaw blade cutting through the bars on a
window. The things do not last long when heavily used.

**Comment by Malkeus** [comment]
Then we get back into the reality/tedium vs enjoying the game issue. I guess it comes down to how much of a pita it is going to be to swap blades. If we need to change them out every half dozen car part removals, dropping out of the car building screen and reloading the tool will just add tedious repetition. If it's handled transparently via a pool of blades in the inventory, I think that would be ok.

**Comment by chaosvolt** [comment]
Exactly.

And here's another issue. What about crafting of hacksaw blades? It seems sensible to allow them, aside from possible issue of getting the right hardness, but it would trivialize the need to procure replacements.

**Comment by Coolthulhu** [comment]
Crafting them would combine the worst parts of having to replace them and lack of limitations on usage.
Instead, it would be better to either void the mechanic at some point by adding a rare infinite saw (possibly vehicle mounted) or not allow any crafting and make saws a truly limited resource.

That is, unless the blade replacement mechanic was truly automatic and not as manual as current reloading. Then we could have makeshift blades with a very limited number of charges. Producing those could double the time of crafting anything without real tools.

**Comment by Malkeus** [comment]
I don't think manufacturing blades should be a thing. The information I can find indicates that they are made of special alloys and undergo hours of heat treatment. And coolthulhu makes valid points. If makeshift blades were a thing, they wouldn't be made of the proper material and wouldn't last long.

**Comment by chaosvolt** [comment]
> That is, unless the blade replacement mechanic was truly automatic and not as manual as current reloading. Then we could have makeshift blades with a very limited number of charges. Producing those could double the time of crafting anything without real tools.

This seems sensible, and might be good if we assume that the right sort of hardening can't easily be replicated using survivor smithing, this allows them to be craftable while still be less ideal alternative.

**Comment by kevingranade** [comment]
On Jan 11, 2016 11:24 AM, "Malkeus" <notifications@github.com> wrote:
> I guess it comes down to how much of a pita it is going to be to swap
blades. If we need to change them out every half dozen car part removals,
dropping out of the car building screen and reloading the tool will just
add tedious repetition. If it's handled transparently via a pool of blades
in the inventory, I think that would be ok.

I suggested auto reload during long actions for batteries, the same applies
here.

**Comment by vache** [comment]
I think it should be possible to manufacture your own blades at some point, but that goes back to a lot of advanced manufacturing that people have been wanting.  It's all a part of the power curve, initial tools should be makeshift and garbage that wear out quickly, then the player should be able to scavenge real purpose-made tools of higher quality that wear out over a longer time, then the player should find the ability to essentially produce things at near infinite quantity (provided resources) and almost industrial quality.  The idea is that the player always has a certain set of needs, and the game should provide ways to satisfy them at certain levels of efficiency, and as the player has more and more wants dealt with efficiently, it opens up more time to deal with other things.  

An NPC run machine shop makes sense for providing that upper tier satisfaction of needs, and it could end up being a system where you provide fuel and raw materials, you make an order to an NPC, and then they provide you with a time that you can come pick your order up.

**Comment by Malkeus** [comment]
I think this issue should be represented in the forums like the last
derail...so, how about those hacksaw blades?

**Comment by kevingranade** [comment]
Focusing on the replaceable blades, the two tricky parts are the
replacement infrastructure (which is being worked on for batteries) and
deciding how long a hacksaw blade will last for various tasks.  A major
secondary issue is replacing or augmenting hacksaw use with other tools
(wrench or socket set is the primary candidate).

**Comment by Malkeus** [comment]
The length of time a blade lasts is heavily dependent on the hardness of
the material you are cutting.  High grade bolts will eat your blade in
short order, frames tend to be easier to cut than the bolts holding them
together. Body work might as well be paper. Assigning a hardness value to
materials might be a good starting point. I'll look at it when I get home
and share my thoughts.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
