### ISSUE TITLE
Reloading using batteries

### ISSUE THREAD

**Issue by mugling** [CleverRaven/Cataclysm-DDA#14797]
As rasied by @kevingranade in #14788

> Handling it nicely would involve overriding the reload code to only swap blades as they wear out instead of adding their charges together, but surprise, that's how batteries should work anyway

I've wanted to add this behavior for batteries for some time and now the reloading refactors are done we are in a position to consider how this might be done in a way that adds an interesting mechanic without becoming tedious.

We could implement batteries as a kind of magazine for charges. IRL we have AA, C, D cells although it might be best to abstract these away as `small battery pack`, `medium battery pack` and let most (all?) tools use these interchangeably. Differing pack styles could have different capacity, energy density (weight:charge ratio) and efficiency. There are lot of other interesting possibilities - some could be craftable, explode in fire etc.

There needs to be some mechanic (other than tedium) to discourage a player continuously unloading and reloading the same battery through a series of tools and this would seem to be at least one major stumbling block. Possibly players could assign a tool a given battery which remains within the inventory (and is shuffled automatically between tools on their behalf). This would also solve the infamous gains weight when reloaded bug and storage tazer exploit.

If we can work out a specification I'll look in to this now I'm starting on the magazines implementation.

**Comment by Coolthulhu** [comment]
> There needs to be some mechanic (other than tedium) to discourage a player continuously unloading and reloading the same battery through a series of tools and this would seem to be at least one major stumbling block.

For tools that aren't weapons, there isn't much of a reason to keep them charged.
Keeping a battery pool (possibly limited by types) would probably work.
Instead of consuming 30 charges of soldering iron, we'd consume 30 charges of batteries and require a soldering iron.

Cases like UPS or atomic tools would be a bit more complicated, because they would require changing the battery type to UPS charges or plutonium, but that doesn't sound like a huge problem.
It would mostly require special handling of crafting with tools that currently are charged.

**Comment by hitbutton** [comment]
I'm not really sure if it would fall into the "tedium" or "interesting mechanic" bracket, but I kind of like the idea of having to hunt around for the AAA batteries that I need for tool X.

Possibly I could find them by disassembling a 9V battery? http://www.instructables.com/id/how-to-open-a-9v-battery/?ALLSTEPS

**Comment by SeanMirrsen** [comment]
Making batteries work a little like cash cards could be interesting. But... well, there is an issue I'm thinking of, I just can't seem to put it into coherent sentences.

Basically, there are two types of batteries, regular and rechargeable. If most batteries are regular, you have the player being forced to use partially spent reloads for things like flashlights, with no option to reload to full by default, until he finds matching rechargeable batteries, for which he will then need a device like a universal charger, to transfer leftover juice from regular batteries into the new ones.

**Comment by aeoo** [comment]
One thing that is imo good about the old way of doing things is that I can tell at a glance the state of readiness of the device, because it is right next to the device in parens.  With the proposed solution, all else being the same, I'll have to keep in mind how many batteries are laying around at the bottom of my inventory list.  This could be solved through some clever UI tweaks.  Ideally I want it to be easy to tell how much charge I still have available for device use.  I'm not particular about how exactly the batteries are implemented, like whether we have to stick them into the devices or whether the devices just use them from inventory.  My main concern is ease of use.

Also re: tazer, presently it doesn't print its charge level into the combat log, but at least when I 'a'pply it I can see right away what its charge level is and I'll know how close I am to running out, so this is OK right now.  Once devices no longer have charge levels printed next to them, unless I'm mistaken 'a'pply command will no longer reveal where I stand with regard to available charge levels if the interface is left as is.

So if the devs decide to allow devices to drain batteries straight from the inventory, fine, no problem, but maybe there should be an easy way to see how much charge I have left instead of hitting 'i' and then visually scanning half way down my inventory for a number.  As long as the implementation is easy to use, whatever floats everyone else's boats is fine with me as far as charges go.

**Comment by kevingranade** [comment]
On Jan 11, 2016 4:29 AM, "mugling" <notifications@github.com> wrote:
>
> There needs to be some mechanic (other than tedium) to discourage a
player  continuously unloading and reloading the same battery through a
series of tools and this would seem to be at least one major stumbling
block Possibly players could assign a tool a given battery which remains
within the inventory (and is shuffled automatically between tools on their
behalf)

Does there? This is a perfectly valid thing to do, but in general I don't
think batteries are in short enough supply that it will be a major problem.
How about long actions reloading the tools used with batteries as needed?
At that point we have a clear signal from the player that they want the
thing to happen and we're already abstracting away the individual actions
they're taking.
This would also have a tendency to smooth over the "last bit of charge"
problem, since long actions could burn through a number of barely charged
batteries.

**Comment by John-Candlebury** [comment]
I don't like the inventory managing  implications for having to keep my batteries and tools separated.

I think Kevin's solution of auto-reloading tools would work better.

**Comment by Night-Pryanik** [comment]
Closing as per lack of discussion.
