### ISSUE TITLE
No sound is played when reloading

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#14835]
Chezzo soundpack, Win 10, tiles, 0.C-4191.

**Comment by Chezzo** [comment]
I noticed doors opening and closing don't make sounds anymore either.

**Comment by Night-Pryanik** [comment]
Hmm, at least basic wooden and metal doors are opening and closing with sound on 4191.

**Comment by mugling** [comment]
@Night-Pryanik is this still a problem?

**Comment by Night-Pryanik** [comment]
@mugling yep, there's still no sound of reloading in 0.C-4533.

**Comment by budg3** [comment]
This is caused by missing `reload_noise_volume` for almost all ranged weapons. I've made a PR (#23903) that adds it, but another option would be to change this part in [activty_handlers.cpp](https://github.com/CleverRaven/Cataclysm-DDA/blob/b8744fb50a887954d5791569cc9d07917e29882b/src/activity_handlers.cpp#L1307-L1309). 

Reload sounds are also currently limited to `"type": "GUN"` so reloading magazines or gunmods that add grenade launchers, flamethrowers or shotguns etc won't play any sounds.

**Comment by Leland** [comment]
Closed in #23903
