### ISSUE TITLE
[Suggestion/CR] Additional Usages for Pumpkin

### ISSUE THREAD

**Issue by Nymall** [CleverRaven/Cataclysm-DDA#14869]
I'm plotting out a PR for adding more usefulness to Pumpkin. This PR will add the following changes:

## 2 Recipes 

Pumpkin Loaf
* 1 unit flour
* 1 unit sugar
* 2 eggs or 10 units powdered egg
* 2 units water
* 1 unit smashed pumpkin
* Time: 18000
* Difficulty: 3

Similar stats to regular bread, except enjoyability brought up to 5 from 1 and reduced nutrition down to 135.

Based on: http://www.culinaryenvy.com/spiced-pumpkin-chocolate-chip-loaf/

Candied Pumpkin
* 1 unit sugar
* 2 units water
* 1 pumpkin
* Time: 24000
* Difficulty:2

-2 Quench, -1 Healthy, 12 Nutrition, 3 Enjoyability, 2 Charges(servings), Junk Food Candy. Based off Cookies.

Based on: http://www.wikihow.com/Make-Candied-Pumpkin

## As well as changes to these recipes 

Pumpkin as an additional ingredient to "fruit_pancakes" OR as a separate form of pancake.

Pumpkin as an additional ingredient to "cookies" as a fruit.

Pumpkin as an additional ingredient to "pie" as fruit.

Anything I'm blatantly missing? Any other preserves/foodstuffs that should qualify for this PR? Suggestions for balance? I'm considering looking into some savory applications(I have a friend who uses pumpkin in his chilli)... is that something that should be included?

**Comment by Coolthulhu** [comment]
> 2 eggs or 2 units powdered egg

Powdered egg isn't 1-to-1 for some reason, but 5 powdered per 1 regular.

> Similar stats to regular bread, except enjoyability brought up to 5 from 1.

Sanity check on math:
* 1 flour is worth roughly 40 nutrition because flatbread is 3 flour for 120 nutrition
* 2 eggs is 70 nutrition because scrambled eggs
* Pumpkin is 24
* Sugar is hard to count

`40+70+24=135` - comparable to bread's `8*20=160`
Seems to add up.
> Difficulty: 1

Should bump the difficulty. 1 is flatbread difficulty - literally just dumping wet flour glob on a pan and heating that stuff up.
Figuring out what you want from food is a large part of the difficulty - that's why cookies are diff 4.
We don't have a good mechanic for "difficulty 3 without recipe, 1 with", so recipes should be somewhere in between.

> -2 Quench, -1 Healthy, 5 Nutrition, 7 Enjoyability

Should bump the nutrition and drop enjoyability. 7 enjoyability is "proper" cookies, candied pumpkin is kinda "improvised cookies".
Proper cookies are difficulty 4, take flour, sugar and fruit (4 ingredients, not counting water), while those take only 2 (pumpkin and sugar).
How many charges per craft?
Nutrition shouldn't drop below the base one - 24 per pumpkin unit.

Also, 1 difficulty is too low here, 2 would be just fine.

**Comment by Coolthulhu** [comment]
Also, pumpkin could be added to regular, bland veggy recipes:
* Dehydrated veggy (unless we want it to be a fruit?)
* Veggy soup (carrots are usable in a veggy soup, pumpkin soup tastes kinda like carrot soup)
* Other soups (pretty much anywhere where carrots fit)
* Vegetarian rice+beans
* Veggy pie

etc. Basically, most of the places where carrots can be used. Preferably not all not to make them too similar, though. Maybe a different multiplier, for example making pumpkin worse for crafting "carroty" recipe (some nutrition being wasted), but better for crafting "pumpkiny" ones?
Being usable in "familiar" recipes is a major part of food item being usable.

**Comment by Nymall** [comment]
Soups I know pumpkin is very popular and easily usable, as well as an addition to curry dishes.(actually looking at it, someone beat me to the punch - it's already part of soup_veggy and delux beans and rice!)

Damn, actually, save the two recipies I just proposed, it looks like a lot of this has already been done. That's what I get for playing a outdated exparimental, I guess... Sorry about the confusion!
