### ISSUE TITLE
Separate point pools for Traits, Skills, and Attributes

### ISSUE THREAD

**Issue by YeAdventurer** [CleverRaven/Cataclysm-DDA#14895]
As you know, characters in CDDA have a single pool of points which they spend on traits, skills, and attributes.

Coming from a background of tabletop gaming, I can tell you that these sorts of systems present the most significant balance issues by far. GURPS is the only system that comes close to doing it in a manner that isn't easily exploited - it has countless hours of math poured into it, and yet, even THAT has some significant issues that the GM has to watch out for.

Cataclysm: Dark Days Ahead is no different. While no system can be truly balanced, its good to have a system where obvious flaws can be readily addressed. But when you pit everything against everything in terms of character budget, it gets exponentially more difficult as the game gets larger. And CDDA is already a very large game.

The way it currently works incentivizes players to ignore investing in skills altogether - they can be earned in gameplay. Attributes and Traits cannot. This alone inherently stymies character versatility.

What I'm proposing doesn't fix character balance on its own, but is a necessary step that needs to be taken. Skills, Attributes, and Traits need to all have their own separate point pools, plain and simple. In doing so, they become much easier to adjust on a case-by-case basis.

**Comment by YeAdventurer** [comment]
And I want to address something really quickly here, too, since it's been brought up on the forum. It's been argued that doing this causes a decrease in diversity, because what if you want to spend a bunch of points in traits and skills but nothing in stats? Or attributes and skills but nothing in traits?

This is true, you wouldn't be able to do that as readily in the segregated pool framework I'm proposing. But in all actuality, you would actually have MORE character diversity than before. As mentioned prior, the game incentivizes an emphasis on attributes, because skills can always be gained in-game, much better for the long run. This is already the most popular mentality.

Now, skills can be chosen without impacting anything else, leading to a significant decrease of skill-less geniuses running about the wasteland and much more well-rounded characters that are trying new things. Plus, it would help curb that insatiable need to prioritize finding the library as soon as possible.

**Comment by Rivet-the-Zombie** [comment]
>This is true, you wouldn't be able to do that as readily in the system I'm proposing. But in all actuality, you would actually have MORE character diversity than before.

So taking away the player's choice to spend their points on anything they want in order to force them to spend points on pre-specified categories of stuff? I fail to see how that's adding any diversity.

**Comment by sparr** [comment]
> So taking away the player's choice to spend their points on anything they want in order to force them to spend points on pre-specified categories of stuff? I fail to see how that's adding any diversity.

It reduces *possible* diversity, but will increase *typical* diversity. Right now, it is uncommon and foolhardy to take skills at the start. If skills had their own point pool, that would change.

**Comment by YeAdventurer** [comment]
I couldn't have put it better myself sparr.

**Comment by YeAdventurer** [comment]
I'd also like to point out that implementing a system like this would open the doors to the pools having their own rules if you wanted to, so you could do things like balance skill costs against one another.

As far as wanting to play unskilled geniuses or skilled weaklings, professions can help fill that role - and I don't think that would be a detriment. I think it would help make the more mundane professions more interesting.

**Comment by Coolthulhu** [comment]
I support this idea.
Optimal choices lead to cookie cutter characters.
The choice should not be "to go easy mode or hard mode" - world settings should handle that part.

Plus, this would balance scenarios against each other. "Very bad day" can, with just a bit of luck, become "very happy survivor". Lab starts are much better in the long term than any non-challenge scenario. Instead of risk vs. reward, there is long term vs. short term, with the short term option being obviously worse.
Having scenarios/professions give skills (and skillpoints), items and CBMs rather than "points for anything and by anything I mean stats" would really help with that wild balancing.

And more than just fixing the unbalanced professions:
Having professions not cost the precious stat points would mean that people could finally start with all those subpar professions like Bionic Firefighter, Handy Man, SWAT or Survivalist, and not feel like voluntarily challenging self.

**Comment by pingpong2011** [comment]
The "problem" with Cataclysm (and most other roguelikes) is they're knowledge based games. To rebalance character creation, you'd have to make each thing actually useful. Currently, some stats like perception are totally useless to dump extra points in, but strength and dexterity would make you easily kill everything. Skills are egregious, in that there's a few skills you can level up normally, but the rest you have to grind out if you want to get anywhere. Increasing construction from 1-3 for example requires just repeatedly chopping trees, for the only reason of increasing your level. If you don't have an axe, the only way is to search something like 50 bushes to get to level 2 survival. Similarly, I don't know anyone who doesn't repeatedly do certain crafts like needles to level up fabrication, otherwise it can take literally more than a season of in-game time when you're not abusing the system. Higher levels are completely dependent on repeatedly dissembling/assembling certain items if you don't have the books.

**Comment by YeAdventurer** [comment]
@pingpong2011 Kinda getting a bit off-topic. As sparr eloquently put it, 'It reduces possible diversity, but will increase typical diversity. Right now, it is uncommon and foolhardy to take skills at the start. If skills had their own point pool, that would change.'

There is an immediate benefit to balance, and would make future balancing easier, but I think the variety aspect is even more important.

There's still going to be optimal builds, of course, but no doubt a lot more than them. Segregating the skill pools opens a whole slew of options that don't feel like you're purposely handicapping yourself.

**Comment by pingpong2011** [comment]
It'd easily reduce variety. You'd see pretty much every beginner probably dying to something from like low dodge skill, so they'd all put extra points in dodge and melee-related stuff. Then they'd survive that, only to die from say, not having enough food/warmth/tools, so they'd put points into tailoring or survival. The people who know what skills are useful late-game would dump their skills into that and just hope they don't get railed in the beginning. If electronics, driving, even construction, had noticeable early-game benefits (construction has maybe bed and furnace), then they would be worth investing in. Currently there's a lot of time spent "early-game" which doesn't have a strong dependence on later-game skills. I could see changing spawn locations having greater diversity, but in a lot of ways the game, despite having tons of items and crafting and stuff, is still going to be played the same way regardless of how you start.

**Comment by sparr** [comment]
> some stats like perception are totally useless to dump extra points in

Perception is not quite as much of a dump stat as it used to be. http://dev.narc.ro/cataclysm/doxygen/Effects_Stat_Perception.html

**Comment by YeAdventurer** [comment]
@pingpong2011 I flat out said that optimal choices wouldn't go away. But there is such a thing as a step in the right direction.

**Comment by pingpong2011** [comment]
@YeAdventurer That's ALL dump stat stuff. When most of the dangerous enemies in the game are bullet-firing-gas-spraying-100-damage-per-move beasts, having an advantage in melee and foraging is not useful. The sight of objects nearby is negated by... moving closer, and why would you even be disarming traps 95% of the time anyway?

**Comment by sparr** [comment]
ALL? Explain to me how these are "dump stat stuff" please:

lower ranged accuracy penalties similarly to Dex
increased throwing accuracy
increased critical hit chance
increased martial arts hit and dodge bonuses
increased ground item interaction range
increased ability to determine NPC stats

**Comment by YeAdventurer** [comment]
So there's no point in making a system better if you can't make it perfect?

I'm not talking about remaking the entire game here, this is about segregating the point pools because it's a better alternative than the current system. So let's stay on topic, eh?

**Comment by pingpong2011** [comment]
Sparr: Unless you're using a ridiculous sniper rifle, ALL enemies (that I've ever seen) get close enough to easily do crazy damage with guns, to the point where a NORMAL character can 100% headshot kill at decent range with shotgun mods. Throwing is really, really silly if you have a gun or decent melee, crit chance makes sense, but seriously, martial arts, ground interaction range, and NPCs? (which are still default off!)

Ye, it might make sense to have some default characters (say woods, melee, gun owner), but after playing, someone should be able to slice and dice until they find a good fit for them. To force everyone to play the same style to cater to one set of players is nonsensical.

**Comment by sparr** [comment]
This does the opposite of that. This will force people into *more* styles than the current system does.

**Comment by pingpong2011** [comment]
What styles can there be? Overall the game is very consistent, that you get the best melee, you get the best gun available, and you use them. There's no "style" to it other than slow vs fast, and doing things "slow" still means having to get books, having to read those books to make progress, repeatedly do the same crafts, and sometimes having to travel a bunch of map tiles because your city has no jack and there are no working cars. For someone who doesn't wants to "just play" I can see the reasoning behind them starting with melee skills, but otherwise, it just telling me that I have to play the game in an even more strict way. The game can't be both a time-intensive game which requires actually knowing how some of the game mechanics work and dealing with certain BS, AND an easy-to-pickup fun game.

**Comment by sparr** [comment]
Right now there is little to no reason, other than role playing or under-priced professions, to take starting skills. No "good" build includes starting skills.

This change would result in all starting builds including some skills. Are you predicting that everyone would choose the same skills? We should fix that. Ditto on you saying Perception is a dump stat. That's another problem in need of a solution, not a reason to argue against other things.

**Comment by pingpong2011** [comment]
The argument here is not balancing other skills (which would require making many things less useful and variable), but forcing people to choose worse things.

**Comment by Zireael07** [comment]
@pingpong2011: The argument is that people IRL usually have some skills.

**Comment by Coolthulhu** [comment]
> The argument here is not balancing other skills (which would require making many things less useful and variable), but forcing people to choose worse things.

This is a necessary part of balancing. The only other option is to make everything else creep up in power, which quickly makes a mess out of everything.
Having stats above 14 cost more points also "forces people to choose worse things".

Ideally, there should be no "better things" and multiple playstyles should be viable. This is the opposite of what "dump everything into stats" causes:
* Starting out as a crafter doesn't make sense - even if you crafted a katana at start, you'd have lower stats and would suck by the time hulks appear
* Putting points in melee doesn't make sense - just get dex, it will help you with hulks more
* Cooking? First aid? Electronics? Just raid a library, put those points in stats

So cataclysm is full of clueless superhumans who start their lives by crafting socks and distaffs and catching up with all the education they missed by reading books.
This is unrealistic, bad for balance and makes vast majority of professions not exist beyond professions.json file.

Honestly, the only good point I see against the split is "It isn't done yet and would require someone to write it".

**Comment by SeanMirrsen** [comment]
There is no good reason to force people to take skills at the start or force them to lose character points if they don't. "Typical" variety is a meaningless statistic. If particular ways to spend points are "better" than others, that's a call for a rebalance, not for gutting the system and trying something else.

My proposed solution - a *start* of a solution, to see what changes - would have been to increase granularity on the points system, and scale the values of all things proportionally to how useful they are at chargen. Say, bump the available points tenfold. Then bump stat increase costs tenfold (since those you can't readily increase in-game), bump trait costs five-fold (you still have the positive/negative pool to limit you, and traits are semi-trainable via mutations and CBMs), and keep skills as they are now since they are the most useless at chargen. That's as a start.

From there, tune the values as necessary. Perception and intelligence less useful than strength and dexterity? Lower their increase/decrease costs to 8 per instead of 10. Dodging overpowered as a starting skill? Bump its starting point cost to 2. Etc, etc.

An unbalanced character creation system is not a problem you solve by changing the character creation system. It's a problem you solve by *balancing the character creation system*.

**Comment by Zireael07** [comment]
@SeanMirrsen, the thing is, as it stands the system is very difficult to balance. Moreover whenever something is changed (a mutation that was bad across the board gets some positive effects, or a skill gets more uses, or stat effects are different) you need to rebalance everything again.

Just for this last reason we should aim at modularity. CDDA is developing at such a rapid pace that either someone needs to rebalance stat creation over and over, or it gets neglected and imbalanced rather quickly.

And survivors having *zero* skills when the apocalypse hits is bad both for realism and for playability, as @Coolthulhu already pointed out.

**Comment by Coolthulhu** [comment]
> If particular ways to spend points are "better" than others, that's a call for a rebalance, not for gutting the system and trying something else.

So, for example, giving them separate point pools.

There is no way to balance permanent stats against temporary items.
This could work in a linear game with clearly set goals, but in an open-ended game, this only results in choice being good start vs. good future. Unless you plan to die early on or "retire", the choice is obvious.

> My proposed solution - a start of a solution, to see what changes - would have been to increase granularity on the points system

How is separate point pools "gutting the system" and wildly increasing numbers across the board not?
> An unbalanced character creation system is not a problem you solve by changing the character creation system. It's a problem you solve by balancing the character creation system.

Balancing necessarily implies changing.
Multiplying costs and points by 10 is a way less elegant way of achieving the goals. And also one that doesn't address the problem of long term vs short term or realism of superhuman "mental babies" who know zero real life skills.

**Comment by SeanMirrsen** [comment]
Then how about having zero real life skills being more punishing? How about fewer or no "pick-me-up" zero-skill recipes for crafting? Limited gains from repeated doing of the same thing? A *knowledge system that actually unlocks recipes and abilities that a current player would take for granted in a starting character, based on taking particular skills*?

**Comment by Coolthulhu** [comment]
> How about fewer or no "pick-me-up" zero-skill recipes for crafting? Limited gains from repeated doing of the same thing?

Booklocked skills certainly aren't a solution to short term vs. long term and library raiding being better than putting points in skills.
Limited skill gains would actually worsen the library raiding being better than putting points in skills problem - early skill levels require much less repetition than the ones later on.

> A knowledge system that actually unlocks recipes and abilities that a current player would take for granted in a starting character, based on taking particular skills?

This sounds way bigger, more complicated and harder to balance than separating pools for stats and skills. You suggest gutting+overhauling an entire system to avoid a simple tweak.
And it also sounds like it wouldn't do much to long term vs. short term split problem.

**Comment by illi-kun** [comment]
I'm for having two point pools: one for stats and second one for the rest (skills, traits, etc.). Further splitting is excessive from my point of view.

**Comment by YeAdventurer** [comment]
@illi-kun You have the same problem being discussed with your suggestion. Skills would be neglected in favor of traits, because you can earn skills during play and you can't with traits.

**Comment by SeanMirrsen** [comment]
Though without stats to soak up the difference from negative traits, there would either be less negative trait bias, or it would go into skills because however useless in the long term, short term they are quite helpful. Plus you can gain traits long-term, at least certain ones, with mutations and CBMs.

**Comment by YeAdventurer** [comment]
There are a lot of extremely helpful short-term perks too, and that there are 'certain' ones that you MIGHT get through mutation isn't really a good justification either.

I really don't see the sense in this approach, at the end of the day you're still balancing permanent character features vs. something earned through play. If you had your heart set on doing two pools, you would do stats + traits and then skills.

**Comment by YeAdventurer** [comment]
I'd also like to bring back up, since I feel it's been overlooked, that profession options that offer little to no skill points could be put in the mix for those that want the option of playing an unskilled survivor. So at the end of the day, you still wouldn't be forced into taking skills if you really don't want to.

**Comment by Coolthulhu** [comment]
Also note that professions are more than just skill sets:
Skills can safely compete for points with items as both are earned during play.
CBMs and martial arts could also classify. In case of some rare CBMs (monomolecular blade) this may be a bit of a problem, but it could be balanced by giving them only to otherwise bad professions.

**Comment by hitbutton** [comment]
At the risk of derailing conversation, I think this is worth adding, from IRC discussion of the idea:

> kevingranade: what I actually want to do *is* let the player pick whatever they want, the game just evaluates their selection and gives them feedback on how challenging the character will be to play.

Players can already use an arbitrary number of starting points. I think a lot of people would consider that "cheating" since the option is contained in an area of the UI that's separate from normal character creation. Perhaps the seeking of any kind of balance/tradeoffs in character creation is unnecessary, and "spending" points should just be replaced with an indication of game challenge for the character you have created.

**Comment by YeAdventurer** [comment]
I do like the idea of a freeform system, but I know from experience there are people who become paralyzed at the prospect of deciding their own budget.

Also, if this freeform system is going to evaluate and give feedback, it makes sense for that feedback to be at least somewhat accurate, which ties back into the balance issue, does it not?

I think there's room for both a Budgeted system and a Freeform system.

**Comment by Coolthulhu** [comment]
Game balance depends on there being a default difficulty.

Freeform system switch would be very simple to implement, though. Just a single option that changes the strict "you can't start, you went over stat/trait/skill budget" into "you went over budget, you can start but the game will be easy".

**Comment by YeAdventurer** [comment]
@Coolthulhu Mechanically I agree, but as far as the message conveyed to the player, it would seem like the game is telling them that their character would be badwrongfun.

**Comment by i2amroy** [comment]
Personally I'm all for the total hiding of the numbers completely, or at least de-emphasize them (though they would still exist behind the scenes of course) and just replacing them with a general difficulty outline that is listed (and probably recorded in your memorial log) without any specific limits on the number of points that you can have in a category.

That lets players that want to roleplay (which is a significant part of the player base) to build characters as they want without breaking out the debug menu, while the fact that the exact numbers are no longer present also would remove some of the drive where you *have* to use every last point, and descriptive difficulty names could add some more incentive to try out slightly harder starts (does anybody here actually enjoy knowing that they are playing a game on "obnoxiously easy" difficulty? :P).

I know that at least I certainly would find it easier to be moderate in choosing traits if there wasn't a X/12 or similar that I actually saw as a "max", and the needling to avoid the stupidly easy listed difficulties would stop me from just picking all of the positive traits in the book (while allowing me to play that way if I really wanted to).

**Comment by YeAdventurer** [comment]
This is definitely veering off topic. A freeform system is going to need numbers behind the scenes, so if you already have that, you might as well have a budgeted system as well. They will appeal to different moods and different players, no need to choose one over the other.

**Comment by SeanMirrsen** [comment]
A freeform system will not need to have separate budgets though. If the eventual move is in that direction, working on splitting the point totals now would be a wasted effort.

That's besides the whole "what is the actual goal here" thing. Is splitting the point pools supposed to make the game play better? Because it probably won't. How many points will actually be allocated to the skills? Two? Three? That's, what, a point in mechanics (hardest to start up and most useful), a point in tailoring (reduces startup costs for making armor), and maybe a point in dodging (because can never go wrong)? Taking anything else is either not immediately important, or can be taken along with a useful profession. And you can't shave points off elsewhere to take more skills if you want to, then.

**Comment by sparr** [comment]
As a player who isn't great at the game, split pools will make the game play better for me. Right now, when I create a character I want to take skills because it reduces the tedium of the early game, but I know that if I do then I am permanently handicapping my character, which will be annoying if it turns out to be a long game.

**Comment by YeAdventurer** [comment]
@SeanMirrsen Again, there is no reason a budgeted system and a freeform system can't coexist. They will appeal to different people and different moods. I know plenty of people who hate freeform systems on principle.

**Comment by SeanMirrsen** [comment]
@YeAdventurer But wouldn't the system still be, basically, freeform? Nothing would change but the imposed limits, none of which are even hard-set. You can still start without spending all points.

I mean. If the plan is to split the current default total, then what you'll have is merely a different kind of willful handicapping that @sparr speaks of, just on a different level. You'll have the same total, and you'll choose to have it split between different character stats and abilities... which you can very well do already, without a system in place to limit you to just **one** way of limiting yourself.

**Comment by YeAdventurer** [comment]
I honestly can't wrap my head around how splitting the point pools up per category is somehow making the system Freeform. If anything it's moving away from that in doing so.

**Comment by sparr** [comment]
@SeanMirrsen no one said we would simply split the current default total. I would expect there to be more points overall, with a lower cap in any given area. Right now if you give a player 50 points they will put almost all of them in stats, which means we just can't give people 50 points.

**Comment by SeanMirrsen** [comment]
It's not *making* it freeform, it's just not changing it in that regard. It's an artificial imposed limit on what you can do with the points you are given, but it does not impede the freeform nature of the character generation at all. It also serves no purpose as an option - because without it as an option you have the *option* of limiting yourself in any way you please *already*.

But sure, why stop there? We can make it even better. JSONize the selection mechanism and make it a mod! So that, like professions and start scenarios, people can come up with their own personal ways to limit the character generation!
That's not a joke, by the way. If you're going to add a meaningless limitation system to the game, at least make it properly moddable and expandable.

**Comment by Coolthulhu** [comment]
> That's, what, a point in mechanics (hardest to start up and most useful), a point in tailoring (reduces startup costs for making armor), and maybe a point in dodging (because can never go wrong)? Taking anything else is either not immediately important, or can be taken along with a useful profession.

First aid, computers (hard to level), melee (to deal with dogs while armored), cooking and fabrication (for recipe unlocks), unarmed combat (to hit back).
In my voluntary challenge builds, I usually include cooking, fabrication and first aid (1 point in each) just for the recipes.

> And you can't shave points off elsewhere to take more skills if you want to, under that system.

Moving points from stats and traits to skill could be added. Just not back, because that causes all the problems described in this issue.

> That's besides the whole "what is the actual goal here" thing. Is splitting the point pools supposed to make the game play better? Because it probably won't.

* Make survivors not start out as geniuses who somehow missed all the education
* Reduce early game tedium such as grinding tailoring to 3 to make armor, without just giving everything for free
* Make character building meaningful rather than just "do I want a strong character or a gimped one" by removing the objectively best option of making cookie cutter stat heroes with no skills
* Make picking negative traits, "weak" professions (ones that give points) and challenge scenarios not result in significantly easier endgame, have them be more like specializations than early game grind for late game benefits
* Make balancing average players vs. good players much easier by not requiring tricks and grinding knowledge

All of those are pretty much guaranteed to happen just from the point split alone.
And all of those sound pretty much like "it will play better" to me.

**Comment by YeAdventurer** [comment]
This issue isn't about the freeform system. This is about the budgeted system. Unless the assumption that the budgeted system that the game currently uses is going to be scrapped entirely, then I don't understand the purpose of this discussion. If freeform is introduced, it should be an addition, not a replacement.

I've actually already suggested making the character generation system moddable and have been told that there's no way in hell it's going to happen.

**Comment by Coolthulhu** [comment]
> It's not making it freeform, it's just not changing it in that regard. It's an artificial imposed limit on what you can do with the points you are given, but it does not impede the freeform nature of the character generation at all. It also serves no purpose as an option - because without it as an option you have the option of limiting yourself in any way you please already.

Game has to be balanced around some difficulty. This difficulty can't be freeform, there has to be an "average survivor" who takes on the challenges.
And this "average survivor" should be as close to actual average survivor as possible.
Not having a point to balance around would result in players having to probe randomly until they find the actual difficulty of the game.

Even now, the mass of options can be overwhelming to new players - add having to figure out difficulty to that, inability to compare against other players and problems with balancing on the dev side and you get what a default freeform would be like.

**Comment by hitbutton** [comment]
I like the sound of a freeform which informs you of difficulty level, and also like the suggestions in this PR. But the two cannot coexist. If a freeform mode spits out a single difficulty level, then the categories must be weighted against each other.

> Game has to be balanced around some difficulty. This difficulty can't be freeform.

So balance for "normal" difficulty in freeform. That is exactly the status quo.

**Comment by SeanMirrsen** [comment]
>Make survivors not start out as geniuses who somehow missed all the education

Perfectly valid as far as I'm concerned. Can be amnesia induced by psychological trauma because, well, *zombie apocalypse*.

>Reduce early game tedium such as grinding tailoring to 3 to make armor, without just giving everything for free

"Early game tedium" should not be a complaint from people who willfully start with zero skills. Want long-term gains, endure short-term inconvenience. Tradeoffs everywhere.

>Make character building meaningful rather than just "do I want a strong character or a gimped one" by removing the objectively best option of making cookie cutter stat heroes with no skills

No such thing as objectively best. Cata is not an MMO, not a competitive game of any description. New players will play better with skills instead of stats. Experienced players... well, see point above this one.

>Make picking negative traits, "weak" professions (ones that give points) and challenge scenarios not result in significantly easier endgame, have them be more like specializations than early game grind for late game benefits

That's rather outside of the scope, as I was told. It has nothing to do with the character generation.
And on top of that, it will turn picking negative professions into the sort of willful handicapping that @sparr mentions as a thing he'd like to avoid.

>Not having a point to balance around would result in players having to probe randomly until they find the actual difficulty of the game.

But won't the split-point system do the same thing still? It's still freeform. Quite literally, all it will do, is ensure that all players, bad, good, and average, will pick some manner of skills, and won't overload on negative traits.

Here are a few things I think will be bad about the character creation process itself, in this new system.
(I will, for the moment, assume that there are separate pools for Attributes, Profession and Traits together, and Skills.)
- Attributes: arguably the only positive outcome, this will just ensure that people stay within bounds of reason when shuffling stat points around. New players will still just as easily handicap themselves here by perhaps playing "smart" characters instead of strong and fast ones.
- Professions and Traits: the new system will make it nigh impossible to start with a character without negative traits, because the only way to do so - barring even more points tossed into the mix - will be to take bad professions. You will literally be unable to start as a decent character without tradeoffs. Something expensive like Martial Artist (or whatever the actual name is) will be unjustifiable to most players. Pretty much the worst impact of the change.
- Skills: again, will require more points added to the total - making it even more of an "easy mode" - to make selection of skills even remotely meaningful. And, again, most players pick at least some skills anyway - new players because they think they'll be useful, experienced players to alleviate the early-game grind.

Unless I'm understanding something entirely wrong here, I just can't see how the proposed system - especially when it'll be an option - will lead to "better" gameplay. Easier, yes, with all the added points. Might call for a rebalance of some experience gain ratios down the line if it's popular enough. But I've yet to be convinced it will actually be "better".

>Game has to be balanced around some difficulty. This difficulty can't be freeform, there has to be an "average survivor" who takes on the challenges.

Problem is, there isn't one, at least in-universe. Characters range from sickly schoolchildren to cyberbetic nuclear abominations. And the "average survivor" is our zero-point Joe Schmoe. Man who can drive anything under the sun (if badly), cook a few meals from ready ingredients, take apart and assemble flat-panel furniture, make simple tools out of scrap and rocks, and wrap stuff in duct tape. "Zero skills" are not actually, you know, zero. They are a baseline, and the average zero-point starting character is far from totally inept.

And the difficulty of choosing the "right" setup from a multitude of available choices, is kind of what I made the "reroll character" feature for.

**Comment by sparr** [comment]
Someone could have implemented two or three different systems for us to test in the time we've spent discussing this. I'm unsubscribing from this issue. I look forward to a PR for any of the ideas mentioned above.

**Comment by Coolthulhu** [comment]
> "Early game tedium" should not be a complaint from people who willfully start with zero skills. Want long-term gains, endure short-term inconvenience. Tradeoffs everywhere.

That's bad design. Tedium should not be used as a balancing method, it never leads to anything good.
Tedium is always a problem. Can be a smaller problem than other problems, but it is inherently bad by itself.
And in this case tedium is bigger than the "problems" that would replace it.
> That's rather outside of the scope, as I was told. It has nothing to do with the character generation.

Starting profession has everything to do with character generation.
> And on top of that, it will turn picking negative professions into the sort of willful handicapping that @sparr mentions as a thing he'd like to avoid.

It won't. A weak starting profession would be simply exchanging items for skills. A totally valid trade that doesn't impair balancing, unlike exchanging starting items for permanent stats.

> Quite literally, all it will do, is ensure that all players, bad, good, and average, will pick some manner of skills, and won't overload on negative traits.

It will ensure that all players will have a similar upper stat cap. Which will make balancing easier, starting skills more useful, choices more meaningful and voluntary gimping not necessary to keep the difficulty level sane.
Well, it won't remove all voluntary gimping - not picking "forgetful" is voluntary gimping when playing without skill rust - but at least it will make such exploits more objective (forgetful without skill rust is obviously not "proper", while lactose intolerance being free points isn't obvious).

> New players will still just as easily handicap themselves here by perhaps playing "smart" characters instead of strong and fast ones.

Not as easily. They will have less bad choices to make.
Plus, the stats will all be in sane ranges, meaning that balancing stats against each other will become easier.

> Professions and Traits: the new system will make it nigh impossible to start with a character without negative traits, because the only way to do so - barring even more points tossed into the mix - will be to take bad professions.

Or just not take good traits.
Honestly, current traits are far too lenient for this to be a valid point.

> You will literally be unable to start as a decent character without tradeoffs.

This was always the case. Except now you will have to make less tradeoffs, not more. Negative traits for more stats, for example. Removing that will certainly help with stat balancing.

> Something expensive like Martial Artist (or whatever the actual name is) will be unjustifiable to most players.

It isn't justifiable now. It is a bad trait.
And in case you missed my post above: it should cost skill points. Making it compete with skills rather than traits would make it better than it is now by making it competitive rather than subpar.

> Skills: again, will require more points added to the total - making it even more of an "easy mode" - to make selection of skills even remotely meaningful.

Easier start, harder mid- and lategame.
DDA does have a problem with pacing - early game can be tough, but then it all gets easy until hulks start appearing.
Moving difficulty later into game is a good thing.

> And, again, most players pick at least some skills anyway - new players because they think they'll be useful, experienced players to alleviate the early-game grind.

Experienced players generally do not pick the grindable skills, but the ones that can't be easily leveled. But this is partly because experienced players pick gimped starts for the game not to get too easy later on.

> Unless I'm understanding something entirely wrong here, I just can't see how the proposed system - especially when it'll be an option - will lead to "better" gameplay.

As a default option and a center point around which balancing would happen, it would offer a good set of choices for players who want a game that is relatively challenging, relatively low on grind and relatively low on exploits.
Compared to the current system at least, where chargen exploits and willingness to tolerate tedium determine uncomfortably much of the difficulty of the game.

> And the "average survivor" is our zero-point Joe Schmoe.

That may be an average "in-universe" survivor, but this means nothing for balancing.
As a result, there are such quirks in the system as:
* Healthy, adult man not being able to hit a dog that is biting his legs
* "Trained" critters not dodging any hits
* "Trained" critters not being able to land a hit, unless more than one attacks the player at the same time
* Block technique being useless
* Generally critters being either unhittable early on or always hittable with no dodge chances
* Melee weapons clearly fitting into "good", "bad", "mediocre" etc. categories rather than being specialized. Granted, I managed to get rid of a large part of this problem, but it is still there.
* WILD differences in martial arts balancing. I mean, holy fuck, their balancing is in a sorry state, with amazing choices and utter crap next to each other, pretending to be comparable.

Sure, many of those problems were caused by something other than lack of a good balancing point (most likely just not wanting to bother with balance), but if a clear, objective balancing point (or at least a range) existed, it would be much easier to get rid of them before they start causing problems.
I'm mostly thinking about Niten here because it is such a good example of how stats can get out of hand.

> They are a baseline, and the average zero-point starting character is far from totally inept.

Except this baseline:
* Varies wildly depending on how much cheese the player wants to squeeze in
* Levels up almost immediately after starting the game, becoming useless for balancing
* Is not actually a baseline but a minimum. No character can be less competent (in terms of skills) than 0 skills

> And the difficulty of choosing the "right" setup from a multitude of available choices, is kind of what I made the "reroll character" feature for.

You'd still benefit from the game being more balanced even if you only played random characters.
And assumptions about player's starting skills/stats/traits do help with balancing.

**Comment by kevingranade** [comment]
It's a given that if we have separate pools they should be configurable
seperately.

If we add one more pool that is shared among the different attributes, we
can have both modes, as well as an in-between one where points for
attributes is partially rivalrous.

There is a seperate question of what the default should be, but IMO that
can wait until there's an implementation.

**Comment by YeAdventurer** [comment]
I'm not sure I see the point in a universal pool on top of everything else, seems like needless complexity. We'll already be able to have professions give different amounts to each category.

**Comment by kevingranade** [comment]
Professions don't set point totals, they adjust them. The baseline is set by an option.
The point is to allow people to continue to use a unified stat pool if they so desire.

**Comment by YeAdventurer** [comment]
Professions can be used to adjust the individual point totals is what I meant.

**Comment by aeoo** [comment]
I agree with everything @Coolthulhu said and I think the suggestion in this issue has merit.

Currently I use the "stats through skills" mod to play and I love starting with some skill points.  Before that I would routinely use the "Real Bad Day" scenario and other scenarios that awarded a ton of points and spend all those points in stats.  I'd also take 12 points in negative traits and only 9 in positive traits and then plow another 3 points into stats.  In a really weird way that ended up creating an absurdly strong character right away simply because of insane stats.  It's basically min-maxing to the Nth degree.  No, I don't think that's good design at all and the proposed solution I think will move us to a better design.

In general I hate the early game tedium.  Grinding every essential skill to 3 is annoying.  I spend every game grinding fabrication and survival and even *these days* when I constantly use the "stats through skills" mod, I still *never* ever take fabrication and survival because these two are super easy to grind.  But are the annoying to grind?  Yes.  And I would absolutely feel like I would be making a bad choice were I to invest into fabrication and survival early on, but that should not be so ideally.

I feel that the present system certainly forces some kind of strange and awkward choices on me.  I avoid investing into skills I can grind easily.  I feel obligated to grind because if I don't it means I'm a sucker by wasting points.  Then I feel like I have to plow everything into either stats or skills if I am using "stats from skills" mod.  All this is really strange.  I think the proposal here would go a long way to reducing tedium and making the character creation more fun.

**Comment by SeanMirrsen** [comment]
>In general I hate the early game tedium. Grinding every essential skill to 3 is annoying. I spend every game grinding fabrication and survival and even these days when I constantly use the "stats through skills" mod, I still never ever take fabrication and survival because these two are super easy to grind. But are those two annoying to grind? Yes. And I would absolutely feel like I would be making a bad choice were I to invest into fabrication and survival early on.

Would that really change with the proposed system? You say yourself, that you allocate points to skills *anyway*, and still suffer through the grind because some skills are not worth their points. The problem you want to solve lies elsewhere, methinks. Character generation is but a tiny part of it.

**Comment by Chezzo** [comment]
I take all sorts of skills in character creation. 

They give you the recipes you would get if you read every single book up to your skill level. 

I can leave the shelter with Night Vision goggles.

**Comment by macrosblackd** [comment]
I think it would be a poor idea to replace the current system out-right, for many of the same reasons mentioned already. I would not be averse to having an option, somewhere, to choose a different system. This would also allow players to try both and compare them (A/B Testing). With feedback from players, perhaps the new system could eventually become the default, but for now I would recommend, at the least, leaving in the existing system as default.

**Comment by kevingranade** [comment]
Pedantry, it's not an a/b test if the user picks which group they're in. :)
And yes, that's what I was suggesting with making the individual and
collective pools configurable.
