### ISSUE TITLE
The flaw with Flaws

### ISSUE THREAD

**Issue by YeAdventurer** [CleverRaven/Cataclysm-DDA#14896]
Right now, the rather low amount of points you get by default places a great emphasis on getting as many flaws as you can. This leads to people choosing flaws which can have little to no impact on the chosen scenario.

I know some feel this is more of a reward for making smart choices. But to take a look at the bigger picture, this sort of 'system mastery' has been around for a long time, particularly in tabletop games. It makes an already difficult game even more frustrating to learn for new players.

I don't think it's a worthy trade-off, and roleplaying game companies tend to agree - you don't see a lot of 'flaw' character options in their modern day products. They're extremely difficult to get right. The games that do include them usually come with a big 'Check With Your GM' label.

In CDDA's case, I don't think they should be gotten rid entirely, but they need to be scaled back so they don't have the importance they currently do. Starting characters could be made a little bit more powerful by default to compensate for this.

(Tangentially related to this issue here: https://github.com/CleverRaven/Cataclysm-DDA/issues/14895 - I believe by implementing segregated point pools, flaws are much less of a hassle to properly address.)

**Comment by karols146** [comment]
Cataclysm is a rougelike - one of best (That just my personal opinion), and one thing with mark that is a difficult level like in all other rougelikes. That games just need to be hard to be good.

**Comment by YeAdventurer** [comment]
What?

**Comment by karols146** [comment]
Ok Need more sleep today.... Just paste it by mistake.

**Comment by ejseto** [comment]
I don't see why it's a problem to have "overpowered" flaws or character builds. Some things are going to be objectively better than others. That doesn't mean they shouldn't exist. If some players want to be a munchkin, so be it. Others gain pleasure from surviving as the most weak, underpowered character they can. You can also straight up adjust the number of character points you start with, or edit the plain text save files, or use the wish menu, or even modify the source code to your liking. It's nobody's place to say how much or how little a player is "cheating" since this isn't a competition. There's no score, and no real endgame. If you personally think the flaws are overpowered, I suggest *not using them*.

**Comment by YeAdventurer** [comment]
I'm not sure you actually read anything I wrote.

**Comment by sparr** [comment]
In general, flaws are not very well balanced. Some of them are so very easy to never trigger. And you're right, the imbalance gets worse in certain scenarios.

There is occasionally discussion about various ways to rebalance character creation. There's a big one right now in another issue about how to allocate points.

If you want to make a proposal to fix flaw pricing, please do.

**Comment by ejseto** [comment]
I'm not sure you read anything *I* wrote. What's wrong with having variable difficulty based on the player's knowledge or the player's choice? You want to homogenize everything?

**Comment by ejseto** [comment]
>flaws are not very well balanced

So? Why does everything need to be balanced? Particularly in character creation, where one can choose the difficulty?

**Comment by sparr** [comment]
@ejseto difficulty should be varied by changing the available points. the whole idea of the point system is that 16 points should be the same amount of difficulty no matter how you spend them. Different, but equivalent.

**Comment by YeAdventurer** [comment]
I read what you wrote @ejseto, but my issue was never about the overpowered aspect of flaws, that's why I questioned if you actually read my post. It's about the additional layer of obscure things you need to learn before you even start playing the game. It's not good design.

**Comment by ejseto** [comment]
>layer of obscure things

This is a staple of roguelike games. Inb4 "DDA isn't a roguelike." You can call it whatever you like, but people are attracted to it for various reasons, some of which may include its roguelike qualities. If you really want to know how things work, you can read the wiki or the source code. Or you know, muddle through and actually *discover* things, which can be a lot more fun than being a spoiled munchkin.

>the whole idea of the point system is that 16 points should be the same amount of difficulty no matter how you spend them

People are going to trade (in either direction, depending on skill and preference) early-game power for late-game potential anytime you let them. If you force people to have separate point pools, who's to say they won't just go into the options and set starting skill points to 0 and add whatever they subtracted to the starting stat point pool?

**Comment by YeAdventurer** [comment]
Obscurity is not the goal of a roguelike, it's a circumstance of all the advanced elements that are put into them. You want your game to be as intuitive as possible without taking away complextty, unless you're just a jerk or something I guess.

**Comment by ejseto** [comment]
Who says it's crippling? Is the game too hard? Is that the consensus? The title of this issue is "The flaw with flaws." Maybe it should be "This game is too hard! Give me more points by default so I don't feel like a cheater for increasing it!"

**Comment by YeAdventurer** [comment]
Please stop acting like a child.

**Comment by ejseto** [comment]
Oh, ad hominem, nice. I'm sorry if you take offense to what I say, but you might try actually addressing it instead of insulting me. Here, I'll be more diplomatic: You raised an issue with flaws. It seems you really think the issue is with the game's difficulty. Is that not correct?

**Comment by YeAdventurer** [comment]
It is not correct, I've said as much.

**Comment by ejseto** [comment]
>so it's not crippling if you don't load up on them properly

You think it's crippling if you don't take flaws. How does that not imply the game is too difficult?

**Comment by YeAdventurer** [comment]
The problem is not with the game's difficulty. This issue is taking as many flaws as possible is currently a staple of effective character building and new players aren't going to know that.

**Comment by YeAdventurer** [comment]
Let me put it another way.

It's bad game design for something so important to not have any emphasis. So there are two good options here to fix that, emphasize the importance of flaws, or make them less important.
I think the latter is the better option.

**Comment by Headjack** [comment]
Let's all just take it slow, yeah?

I think that a degree of system mastery is inevitable, but also that flaws are sometimes too cost effective.

A degree of minmaxing is basically unavoidable in any system with character customization, that's not a reason to overcompensate and nerf flaws too severely, because, as was mentioned, some people intentionally play weak chars or roleplay some...role. A good median is probably making the flaws more impactful or weighty in game, rather than diversifying people primarily by what they are able to do instead of things they would rather not be doing.

**Comment by YeAdventurer** [comment]
That's also a good idea.

**Comment by Coolthulhu** [comment]
> What's wrong with having variable difficulty based on the player's knowledge or the player's choice?

The part where you need to know the game to have fun and the part where you knowing the game enough ruins the fun and forces you to invent new ways to gimp self.

> You can also straight up adjust the number of character points you start with, or edit the plain text save files, or use the wish menu, or even modify the source code to your liking.

You can even daydream about doing something else.

Video games are about acting within limitations, making correct choices from a limited set of them and the choices being non-obvious or obvious but hard to execute.
One could argue that DDA isn't really a game because it has no winning condition, but it has a losing condition and preventing that could "count" as a win.

> If you personally think the flaws are overpowered, I suggest not using them.

If people want balanced traits and you don't care about balance, why argue against balancing the traits?

> If you force people to have separate point pools, who's to say they won't just go into the options and set starting skill points to 0 and add whatever they subtracted to the starting stat point pool?

If I read something like this on a forum that isn't all "serious business", I'd accuse you of trolling.
It's like you aren't arguing for something, but against the idea of balancing altogether.

**Comment by ejseto** [comment]
>against the idea of balancing altogether

I am to some degree, because I don't believe everything can be balanced. Yeah, some things like "lactose intolerance" are basically free points, and a point of strength will almost always be better than a cool glass of milk, unless your character is stuck in a desert with nothing but milk, but the solution is to make this more of a disadvantage by adding more dairy based foods, by implementing additional bonuses to nutrition/health, or by decreasing the points you get from it (giving it a fractional point value).

**Comment by YeAdventurer** [comment]
#by decreasing the points you get from it (giving it a fractional point value).
So in other words, something akin to what I suggested in the very post of this issue that I'm still not sure if you read.

**Comment by Coolthulhu** [comment]
> a point of strength will almost always be better than a cool glass of milk

That's why the split is a good idea. Because later in game you have enough food to fill a truck, but strength is still valuable (even if just to haul this crap).
> but the solution is to make this more of a disadvantage by adding more dairy based foods

This is not "the" solution, just "a" solution. For one, it solves only the part where lactose intolerance is a free point, not where it becomes a free point later in game.
"Effective importance" of lactose intolerance drops to zero by late game, meaning it can't be balanced for early and late game at the same time.

**Comment by ejseto** [comment]
>something akin to what I suggested

That'd be the last resort. I don't even really think it solves the problem. The problem is the disadvantage of never drinking milk isn't a disadvantage at all.

>"Effective importance" of lactose intolerance drops to zero by late game

I don't see why it can't or shouldn't be important all game. Oh, you don't like milk? Enjoy your osteoporosis! Oh, you don't like vegetables? Enjoy your colon cancer! Oh, you don't like apples? Too bad there aren't any doctors anymore!

**Comment by YeAdventurer** [comment]
Easy fix vs Very complicated system overhaul that few people are going to even appreciate

**Comment by ejseto** [comment]
I think a lot of people would appreciate a more complex nutrition and health system.

**Comment by YeAdventurer** [comment]
Say you wanted to do that. Wouldn't it still make sense to make short-term adjustments at least until such a system was finished?

**Comment by ejseto** [comment]
I guess. Personally I think the whole "mastery of the system" thing has more value than balancing something in character creation.

**Comment by ejseto** [comment]
I've been thinking, and the real problem with flaws is that there's no opportunity cost for taking many of them. Is there a reason flaws are limited by total cost rather than number? If you only had, say, 3 slots, you might think hard about wasting one on a one-pointer. If an absolute limit is too harsh, there could be a penalty based on the number of flaws, similar to the increasing marginal cost of skills.

No matter what, lactose intolerance is basically a free point. You could decrease the value to a fraction, but it would still be a free, say, 1/2 point, because milk/dairy has no particular nutritional value besides the calories. But if it locked you out of something worth more, that would no longer be free.

**Comment by Coolthulhu** [comment]
> If you only had, say, 3 slots, you might think hard about wasting one on a one-pointer.

This one sounds good.
Could make all the really shitty traits like schizo or illiterate actually worth getting.
And it doesn't conflict with separate pool idea, which is a plus.

**Comment by YeAdventurer** [comment]
The slot system is a good idea, I agree.

**Comment by Rivet-the-Zombie** [comment]
>If you only had, say, 3 slots, you might think hard about wasting one on a one-pointer.

This is an interesting idea, but the number of slots should be configurable as well.

**Comment by YeAdventurer** [comment]
Agreed

**Comment by kevingranade** [comment]
My mainproblem with limiting number of traits is making things harder for
rp oriented players.
A secondary problem is a lack of rationale, it's extremely arbitrary.

**Comment by YeAdventurer** [comment]
My thinking was the proposed Freeform option could fill the niche for rp-oriented players, and this change would just affect the people who would rather have the video gamey point system.

**Comment by Coolthulhu** [comment]
Diminished returns then?
Skills and stats already have that.
Say, -0.5 point per negative trait after the third, rounding down at the end.
Then after the fifth, -1 point per negative trait, so that adding that lactose intolerance would do nothing (because at this point the player is either rp-ing a sad wreck or munchkining).

And then we could get rid of the 12 trait point limit thing.

**Comment by YeAdventurer** [comment]
Personally, I would much rather see Freeform implemented and have Budgeted have some more hard n' fast rules (that can be customized in Debug).
