### ISSUE TITLE
Implement Freeform system

### ISSUE THREAD

**Issue by YeAdventurer** [CleverRaven/Cataclysm-DDA#14914]
My suggested implementation is this:

When you select Custom Character, it will prompt you

Point Budgeted
Freeform

If you choose Point Budgeted, it'll go to the current character creation system.
If you choose Freeform, it'll go to something similar, but it will be different in the following ways:

1. You can spend as many points as you want.
2. Point values will be completely hidden.
3. There will be no limits put on traits.
4. In the place of where your point budget would normally be, it will give tell you a rough estimate on how difficult that character will be to play in the scenario you've chosen.

~~4. In the place of where your point budget would normally be, it will give you a probability readout based on the points you spent and the scenario you chose, with the maximum being 'Excellent' (spending lots of points), and minimum being 'Remote'. Some possible suggestions for in-betweens: 'Good' 'Average' 'Unlikely' 'Slight' etc.~~

~~The reason I suggest 'Probability' instead of 'Difficulty' is because players will look at something like 'Difficulty: Easy' or whatever and feel like their character is badwrongfun. Plus if their character isn't particularly optimized it wouldn't make sense to say the character is easy, either. Probability is more vague and positive-sounding.~~

**Comment by hitbutton** [comment]
> players will look at something like 'Difficulty: Easy' or whatever and feel like their character is badwrongfun

Is this not the intention? Informing the player of difficulty is intended to prompt them toward challenging themselves.

Also I think "Probability" is really too vague and meaningless. What probability is this meant to represent?

If you want to abstract difficulty away from "Easy" vs "Hard" then I'd suggest a "Life Expectancy" measured in time. Although it obviously wouldn't be particularly accurate, the presentation would give achievement focused players obvious benchmarks to test themselves against.

"Can I get this character to survive past his life expectancy? How much longer?"
"Oh man, I keep making characters with a life expectancy of years and they die in under an hour :( "

**Comment by YeAdventurer** [comment]
>Is this not the intention? Informing the player of difficulty is intended to prompt them toward challenging themselves.

It's so players do what they want to do instead of feeling pressured by the game calling them a sissy.

>Also I think "Probability" is really too vague and meaningless. What probability is this meant to represent?

That... is a good point. I was thinking 'probability of survival' but considering the game has no win condition, I guess that's not really accurate.

**Comment by kevingranade** [comment]
We specifically do want to challenge players, if they just "do what they
want", it's a pure sandbox and no longer a game at all. They can do so, but
I see no reason to make a distinct character creation mode to cater to that.

**Comment by YeAdventurer** [comment]
But it was your idea

**Comment by kevingranade** [comment]
Not the total lack of feedback, feedback informing the player of how
survivable the character is was an integral part of the concept.

**Comment by YeAdventurer** [comment]
Okay. Revised the first post then.

**Comment by ejseto** [comment]
>Freeform

Is this really even necessary? Is it any different than just setting the point pools to however high you want? Also, if you're just setting the points to what you want, you get automatic feedback on how difficult your character will be.

>If you want to abstract difficulty away from "Easy" vs "Hard" then I'd suggest a "Life Expectancy" measured in time. 

Aren't those the same thing? They are both subjective and arbitrary, so might as well go with what people would expect, the easy-hard scale.

>It's so players do what they want to do instead of feeling pressured by the game calling them a sissy.

Why does it matter? If you're going to "cheat," own up to it. It's not like anyone is judging you, it's a single-player game. If a game's "judgement" can prevent you from exercising your own will, I don't know what to tell you.

**Comment by YeAdventurer** [comment]
@ejseto The latter 2 points are dropped, no need to argue it.

**Comment by hitbutton** [comment]
> Is this really even necessary?

The reasoning behind it is evident in your reply. You talk about playing easier characters as "cheating". However I'd imagine you don't consider it "cheating" to play a character with the default 8 starting points, instead of lowering it to 6 or 4.

It's to present a framework in which it's implicit that the player is setting the difficulty level for themselves, without feeling bound to a specific default. I think that's better suited to the sandbox nature of CDDA, and it would remove a lot of the impetus behind trying to game the points system. 

That said, I'm sure you'd still get people taking Ugly and Truth Teller in order to bump their difficulty up to hard.

**Comment by kevingranade** [comment]
A little feedback on your suggestion, instead of saying:
> When you select Custom Character, it will prompt you

> Point Budgeted
> Freeform

It would be much better to say something like "I'm suggesting this as an option in addition to the existing system".
As it is it gives the impression that you are trying to dictate how the entire character generation system is going to work instead of making a suggestion about a particular feature.

Another problem is a suggestion this vague doesn't really belong on the issue tracker, otherwise I would have opened an issue for it long ago, since as you note it is my idea.
You may notice we have over a *thousand* issues open right now, which is entirely too many already.  If you want to start a discussion about a potential feature, please open a thread on the forums, the issue tracker is intended for more concrete ideas (which we're not perfect at, a lot of the very vague issues open now are likely to be removed to cut down on clutter)

**Comment by YeAdventurer** [comment]
>As it is it gives the impression that you are trying to dictate how the entire character generation system is going to work instead of making a suggestion about a particular feature.

The very thing I said is 'My suggested'

> the issue tracker is intended for more concrete ideas

It seems like a pretty concrete idea to me??

**Comment by YeAdventurer** [comment]
Oh, and do notice I forgot to mention that it was your idea in the opening post, it slipped my mind. Sorry about that.

**Comment by Zireael07** [comment]
@YeAdventurer: A 'concrete' idea is something that can be picked up and coded immediately, without having to discuss how it should work and what is the reasoning behind it.

**Comment by ejseto** [comment]
>The reasoning behind it is evident in your reply. You talk about playing easier characters as "cheating". 

No, it really isn't. I put "cheating" in quotation marks precisely to mock the idea that you can even cheat in a game like this. It's single-player and no score is kept. There is absolutely no way to compete with others because there is no objective metric to compare. *The game* considers it cheating, which is why the option is in the debug tab. But in the end, what does it matter? The only person you're cheating is yourself, out of the intended difficulty of the game. Whether you actually lose anything is up to you.

Maybe we should change the death screen to say you won the game. That tombstone is pretty depressing. Wouldn't want people to feel bad about dying any more than we would want them to feel bad about cheating right?

**Comment by chaosvolt** [comment]
I'm not even sure what to make of all this lunacy. ಠ_ಠ

**Comment by Rivet-the-Zombie** [comment]
>However I'd imagine you don't consider it "cheating" to play a character with the default 8 starting points, instead of lowering it to 6 or 4.

Six *is* the default for character points, not eight.

**Comment by hitbutton** [comment]
Haha whoops, that is true. But not really relevant to my point :)

**Comment by chaosvolt** [comment]
I suppose the manly way to play is to set starting points to zero, then maximum points to the cap of 1000.

"I am MinMaximus, and I have all the disadvantages. ALL OF THEM."
