### ISSUE TITLE
Unintentional krav maga nerf

### ISSUE THREAD

**Issue by tivec** [CleverRaven/Cataclysm-DDA#14933]
We had a talk on the IRC today regarding the recent pull request #14741. It appears it has unintentionally nerfed krav maga by quite a lot.

<Biocava> Krav Maga relies on crits to stun creatures, as well as damage and speed to take them down pretty quick. In the versions I went, which had about a 9 day difference... Damage went from 30-40 at fairly proficient, to 5-20, and stun extremely rarely.

Looking at src/melee.cpp line 532 in this pull request, the crit chance was changed from:
```
weapon_crit_chance = 0.5 + unarmed_skill * 0.5;
```
to
```
weapon_crit_chance = 0.5 + 0.05 * unarmed_skill;
```

Intentional or unintentional nerf? :)

**Comment by Mecares** [comment]
Well the above reads out to crit chance being 50% plus 50% for each skill point and the one below to 50% plus 5% per skill point looks like the second one is the more reasonable to me.

**Comment by Coolthulhu** [comment]
Crit nerf was totally intended. That `0.5` there meant that unarmed skill 1 was enough to guarantee a "crit point" from weapon accuracy. That's pretty close to halfway to guaranteeing a crit.
Crits shouldn't be guaranteed, the whole point of them is that they are exceptional, not that the regular attacks are glancing blows.

Krav Maga nerf wasn't the intent, but it isn't really wrong. It has rapid attack and a passive scaling cut buff usable with all weapons.
If someone wants to buff martial arts, it would be nice, but Krav Maga shouldn't be the first one (nor the second, third, fourth or the fifth...) to receive buffs.
And when buffing Krav Maga, the buff shouldn't be about raw damage output - it's good at it already. Instead it should only get utility, like downing or AoE, maybe a critstun when used with weapons.

**Comment by aeoo** [comment]
@Coolthulhu In the past Krav Maga was not just about raw damage, but feints and stuns.  That's what's missing.  Also it's weird that Krav gives edged bonus because from what I understand the weapons used by Krav are mostly knives, which in CDDA generally do piercing or stabbing damage, but not cutting.  I don't believe Krav Maga teaches people how to use swords or is intended for use with swords (cutting damage).  Maybe a Krav Maga student can correct me.

So I think the bonus should be *probably* switch to whatever is commonly used in knives to reflect how Krav Maga operates in the real world, and it probably needs to have more feints and stuns as before.

As it is, people are going to be dissuaded from picking Krav now. because I think you can agree there is a *massive* nerf in both style and substance to this style.  If you don't want anyone to pick Krav it's best to just remove it entirely from the game.  It's not a good idea to have a skill that no one will want to use.

**Comment by Mecares** [comment]
Ah the old if it is not overpowered anymore it is useless argument.

**Comment by aeoo** [comment]
http://www.kravmaga.com/applied-self-defense-weapons-and-krav-maga/

For reference on weapons.  So of the conventional weapons, a big item there is knives.  They also train to use firearms as blunt weapons and improvised weapons.  Knives don't mesh well with the cutting damage, if I understand correctly.

**Comment by aeoo** [comment]
@Mecares 

It's never been overpowered imo.  Besides, even if you want it to have less damage output, it should still have flavor of some sort.  The style should be fun to use and it should be distinctive.  Krav in the past wasn't simply about bashing your opponent with straight bashing damage.

**Comment by aeoo** [comment]
@Coolthulhu main intent in that PR was to increase bashing weapon damage.  It's not the stated intent anywhere in the PR to nerf Krav Maga by a factor of more than 2 and to completely change how the style works by essentially no longer generating feints and stuns at all.

If Krav was OP before, there would have been a specific discussion about it.  There was no such discussion that I am aware of.  Please correct me if I am wrong.

**Comment by Coolthulhu** [comment]
> In the past Krav Maga was not just about raw damage, but feints and stuns.

It still has feints, it's just that feint is a very weak technique. It was very weak in 0.A. It got a tiny bit better since then (nerfs to accuracy scaling), but it still isn't good.
Non-crit stuns aren't OK, so giving it those will have to wait until we nerf stuns.

>  Also it's weird that Krav gives edged bonus because from what I understand the weapons used by Krav are mostly knives, which in CDDA generally do piercing or stabbing damage, but not cutting.

Martial arts currently don't separate those - cutting and piercing are affected by the same modifier.

> As it is, people are going to be dissuaded from picking Krav now, because I think you can agree there is a massive nerf in both style and substance to this style.

It still has rapid attack and a guaranteed sizeable boost to cutting damage.
> If you don't want anyone to pick Krav it's best to just remove it entirely from the game. It's not a good idea to have a skill that no one will want to use.

I don't want it to remove Krav, just bring it more in line with other styles.
It is still better than the most, easily top 3 of unarmed arts.
> completely change how the style works by essentially no longer generating feints and stuns at all

Stuns are still there and feints aren't affected at all.
It's just that stun rate is lowered from nearly guaranteed to high.

**Comment by aeoo** [comment]
@Coolthulhu 

>cutting and piercing are affected by the same modifier

 interesting!  This wasn't obvious to me in the past.

>It still has rapid attack and a guaranteed sizeable boost to cutting damage.

Krav from what I understand (which is based on reading about it on the web, admittedly) is primarily an unarmed style, where weapons mostly provide occasional options and aren't a primary reliance.

So you're saying in its primary mode, unarmed, you only get rapid attack and that's it?  That's a little on the boring side when it comes to flavor, although I suppose it's somewhat true to life.  Krav is also about counterattacks, and specifically countering weapons while yourself being unarmed.

Also isn't rapid attack a half strength attack?  Is it the same thing that's also on weapons like quarterstaff and cudgel?  Maybe the point of a rapid attack is something other than damage, I don't know, but in my experience it's a weak technique.  Doing half as much damage twice as quickly is something I don't understand.  Maybe I don't understand the formula.  Maybe it's 70% damage twice as fast? Or 50% damage 3 times as fast.  Which would be a weak technique against armored opponents where you'd want a stronger attack even if it's slower, because you want to overcome damage absorption.

>It is still better than the most, easily top 3 of unarmed arts.

There were many nearly useless styles in the past, so that much is also true, mainly the Chinese ones.

>It's just that stun rate is lowered from nearly guaranteed to high.

I'll need to play test it myself later.  So far I'm going off what someone was saying on IRC (from whom the second paragraph in the issue is quoted).  It's possible that in play testing there is a bigger difference than what the line 532 in src/melee.cpp might suggest.

**Comment by Coolthulhu** [comment]
> So you're saying in its primary mode, unarmed, you only get rapid attack and that's it? That's a little on the boring side when it comes to flavor, although I suppose it's somewhat true to life. Krav is also about counterattacks, and specifically countering weapons while yourself being unarmed.

Rapid is the most powerful one.
It has feint, precise, disarm, grab and grab break.
It has no counterattack at the moment.

> Maybe it's 70% damage twice as fast?

This one is the closest. 66% damage twice as fast, for a total of 132% damage per turn.
It is also means your non-critical hits will consume less move points, so you can retry for a critical sooner.
Downside is that you will consume stamina faster.

> Which would be a weak technique against armored opponents where you'd want a stronger attack even if it's slower, because you want to overcome damage absorption.

Currently it is applied post-armor. That is, 30 damage rapid against 10 armor isn't `30 * 2/3 - 10 = 10`, but `(30 - 10) * 2/3 = 13.3`.

> It's possible that in play testing there is a bigger difference than what the line 532 in src/melee.cpp might suggest.

You can view your crit chances by looking at an unarmed weapon like brass knuckles. Unarmed attacks have the same chance of critting as attacks with brass knuckles.
There are 2 crit chances shown: the lower one is when you're attacking something slow (hulk), higher one against something you're barely hitting (manhack).

Even at mediocre stats, the higher one (the one that applies against vast majority of zeds) doesn't drop below 20%.
You can drop below 20% by getting very low perception and dexterity.

**Comment by aeoo** [comment]
@Coolthulhu That's very informative, thank you.  I didn't know about rapid attacks being applied post-armor.

So am I correct to understand that the feint technique is not tied to the critical hit rate?  What about the other techniques, like disarm or grab?  Do they all trigger on a critical or do they have independently calculated frequencies?

**Comment by Coolthulhu** [comment]
Disarm applies against NPCs, grab causes downing (loss of turn). Only precise strike is a crit technique.
Grab triggers on normal hits.
Feint triggers on misses.

**Comment by aeoo** [comment]
I still haven't play tested it yet.  I'm just trying to wrap my head around the math here.  So assuming rapid attack triggers every single time, that's only a roughly 32% buff over a normal attack pattern.  That's nothing major, right?  But if let's say we're only getting a 32% buff 20% of the time, that's only a 6% buff on damage, which is basically nothing -- this is negligible assuming I understand it correctly.  

If by having low dex and perception one can dip even lower than 20%, this can make the whole rapid attack trivialized.  This would certainly be the case for most of my recent characters which start with all 8's in stats and gradually earn their stat points through skills because I'm using the "stats through skills" mod which lets me start games with some skills without feeling bad about the stats (so it cuts the early game grind quite a bit but it also makes the early game much harder due to low stats).

I think an unarmed style that focuses on damage as opposed to strange tricks should *easily double or triple* the unarmed damage.  If the specials that don't involve direct damage are nothing special, and the style is mostly about damage, then a 6% boost or 10% boost in damage is imo not attractive.  Grab is a pretty powerful technique, but it's the last one you get in the krav technique line, probably at a pretty high skill level.  So until then, assuming I understand the math correctly, you roughly get something in the neighborhood of a 10% boost compared to having no style at all.

Also every style competes against brawling which is a free style.  We should keep this in mind.  Brawling has some decent techniques in and of itself.  The difference between brawling and krav might be even smaller than krav and nothing.

**Comment by aeoo** [comment]
Assuming I understand the math correctly, the way krav maga is now, I will get the most benefit if I use a katana with it (cutting boost), getting a straight 20% damage increase on a katana.  If this is correct, it is bizarre, because IRL krav maga doesn't teach people how to use katanas at all.  So it's an unarmed style which in the real world doesn't teach sword use which benefits from swords in-game more than it benefits from bare hands, which in the real world would be krav maga's primary use.

If I don't get the math, I apologize.  But assuming I understand everything at least half way correctly, krav maga's present implementation seems kind of off kilter to me, not just for being underpowered in general, but for strangely applying its biggest benefit to exotic swords of all things.

**Comment by aeoo** [comment]
Also for reference: a "Quick" trait grants a straight 10% speed bonus, and this trait is not a result of any kind of dedicated training, but is merely a result of a happy genetic accident from what I understand.  So 10% is a very low bar for a 3 point trait, especially if we want unarmed to compete with weapons for damage like in most other roguelikes.  In PosChengBand and DCSS unarmed attacks are game-winning attack styles, to name two examples.

If we explicitly *don't* want unarmed to compete with swords and sledgehammers for damage, *fine*, but then we should think about the *role* of unarmed damage styles. If unarmed cannot be relied upon to "win" the game, it means they're situational use attacks.  In what situations should unarmed be used?  Why would anyone want to spend 3 points upgrading their brawling style, which is a style everyone gets for free if they train unarmed skill to 2?  These questions I think would be good to answer to get a sense of perspective.

**Comment by Coolthulhu** [comment]
> But if let's say we're only getting a 32% buff 20% of the time, that's only a 6% buff on damage, which is basically nothing -- this is negligible assuming I understand it correctly. 

No, rapid attack activates only on non-critical hits.
32% damage buff is quite good. Being able to act more often (to reposition, change tactics etc.) is also good on its own.

> I think an unarmed style that focuses on damage as opposed to strange tricks should easily double or triple the unarmed damage.

That would make martial arts kinda magic or regular punches useless.
Unarmed combat shouldn't have that kind of damage output, especially not early on.
Martial arts shouldn't be like Niten, where reading a book suddenly triples your damage output (well, now less than triples - after a big nerf).

Keep in mind that unarmed combat means you're always "armed", have fast attacks, good accuracy and lots of support techniques that can be switched to in no time (say, brawling for knockback).

>  In PosChengBand and DCSS unarmed attacks are game-winning attack styles, to name two examples.

Didn't get a good unarmed fighter in PosCheng, but DDA has stronger unarmed than DCSS without transmutations. With transmutations, we have to compare against mutations (+ maybe hydraulic muscles), where once again DDA gives more benefit to unarmed fighters than DCSS does.

> Also for reference: a "Quick" trait grants a straight 10% speed bonus, and this trait is not a result of any kind of dedicated training, but is merely a result of a happy genetic accident from what I understand. So 10% is a very low bar for a 3 point trait,

Yeah, style traits are rather weak. This is the same problem as with skills: you get something that you can acquire in game. But this is an inherent problem of styles competing with traits for points.

Plus, Quick is a really good trait that could use a nerf (4 point cost).

> If unarmed cannot be relied upon to "win" the game, it means they're situational use attacks. In what situations should unarmed be used?

* Knockback against a hulk clogged in wreckage, preventing it form ever taking a hit
* Using mutated body parts, getting "flurries" comparable to armed attacks in total damage
* As bashing attacks, they're good against armored enemies (on crit)
* No need to carry a heavy weapon, giving extra inventory space
* Quick attacks against weak enemies without having to equip a different weapon
* Counterstrikes to get good defense when surrounded or otherwise impaired
* Non-metallic weapon, meaning you won't suddenly be disarmed by a technician zed
* NPCs trust you more if you aren't wielding a weapon while they form their opinion of you or when they're mugging you

Unarmed is still better than improvised weapons and sledgehammers, it only loses against swords, strongest of axes and firearms.

**Comment by aeoo** [comment]
>That would make martial arts kinda magic or regular punches useless.

Don't forget that regular punches can always be supplemented by brawling.  Is brawling useless right now?

My take is, with unarmed styles you should be able to use unarmed as your primary damage style from start to finish of the game, so it shouldn't be losing to the strongest of axes, blades, etc.  Firearms are a different story.  I don't think melee should necessarily compete with firearms in a game like CDDA because technologically generated damage (firearms, car bashing, car turrets, bombs, remote control cars) should be essential imo, for anyone.  Hi-tech fighting methods generally consume resources (ammo, gasoline, batteries), and so one needs a "what am I going to use when I don't use a firearm or car or a bomb" option.  I imagine this is where a katana, or zwei or something of that nature finds its niche.  This is where an unarmed attack should compete just fine too, imo.

So someone with training in an unarmed skill using the default brawling style can use unarmed as a fall back option when for example disarmed, or if one's melee weapon broke and it's not easy to just run away and/or get a new one, or maybe your melee weapon is too slow to hit something fast moving and unarmed does that trick in this case.

If a player wants to use unarmed as a primary start to finish non-technical means of damage, they should be choosing a martial arts style at chargen and they should also be getting rewarded massively for doing so.

Right now the difference between krav and brawling is too subtle, imo.  I like that there is brawling, btw.  I just think unarmed needs to do damage comparable to the best weapons in the game.  Unarmed can still be a bit weaker, but not massively weaker.  Instead unarmed with any damage oriented martial art style should be within 20% of the best weapon damage or so.  So you still get something for carrying that volume 12 thingy.  Plus lots of weapons can be sheathed in a scabbard, right?  You might not pay any volume cost for carrying a weapon, but only an encumbrance cost (body eq strap slot I believe).

>DDA has stronger unarmed than DCSS without transmutations.

But in DCSS transmutations are neither random nor dangerous to your character's health.  Further, have you tried unarmed with Chei in DCSS?  Unarmed attacks do ludicrous and certainly game-winning heaps of damage under the right circumstances in DCSS, without any chance danger from a bad mutation or a bad bionic.

In general I think mutations are so dangerous that they should be considered effectively outside the main game.  No reasonable and conservative player will opt for mutations in my opinion.  Mutations are what people opt for when they're tired of their character and just want to see what happens, because why not?  And they're ready to basically lose their character at that point.

So unarmed + mutations shouldn't be considered, imo.

Hydraulic muscles bionic *is* kind of powerful, I grant you that.  I imagine a good way to fix this situation is make hydraulic muscles only usable for dragging cargo and for lifting things but not for fighting.  Make it ridiculously strong but slow in terms of game lore (for example, it gives +20 strength but also -20 dex and all your movements take 200 energy instead of 100), so that it's not usable for melee but is only usable for industrial type environment manipulations.  Like you could maybe lift a car with it and walk with a car suspended over your head, but not throw jabs and taekwondo kicks with it.  I don't like the idea of unarmed styles being balanced entirely around a hydraulic muscles bionic.  That seems absurd to me, because then hydraulic muscles become mandatory for unarmed practitioners.  I don't like this idea myself (especially once bionics get slots like they should, forget it).  I'd rather hydraulics become something with a narrow and situational use rather than a 20 point all around strength boost if this can allow unarmed styles to move forward to where I believe they should be.

>Yeah, style traits are rather weak. 

I think they should be unapologetically strong and *should be a no-brainer for anyone who wants to focus on unarmed as a primary source of non-technical damage*.  If you want to rely on archery instead for your non-tech damage, then you wouldn't pick a martial arts style.  You also wouldn't pick a martial arts style if you wanted to rely on weapons primarily (although we do have styles that work with weapons, but those generally serve as extra sauce instead of a necessity and maybe that should change too?).

One exception here is silat and eskrima which allow otherwise forgettable weapons to become formidable.  Silat even improves unarmed fighting which is great for people who like to have more options sooner.  So I think silat and eskrima are fine (or maybe one of them or both also need a tiny buff to make them comparable to diamond katana and above damage).  I think it's OK to allow one crazy powerful style to be one crazy powerful style, so niten is fine as a kind of "wow, look what I found" thingy that you can still look forward to later in the game.

>Plus, Quick is a really good trait that could use a nerf (4 point cost).

I really don't believe this at all.  I think quick is fine at 3 points and isn't a major boost.  What makes quick good is that it stacks with whatever else you have going and quick can only be had safely at chargen, so it's fine.  FYI, I generally do not pick quick.  I think there are lots of better traits than quick, personally.

>Knockback against a hulk clogged in wreckage, preventing it form ever taking a hit

Not all martial arts styles feature knockbacks.

>Using mutated body parts, getting "flurries" comparable to armed attacks in total damage

Unarmed shouldn't be balanced against mutations because mutations are not in the main game so to speak for reasons I outlined above.  They're "I'm bored and I don't care if I ruin this character" end game toys and nothing in the game should be balanced around mutations.  If mutations can be made safe and reliable, I take everything I said here back.

>Quick attacks against weak enemies without having to equip a different weapon

That's what brawling is for, imo.  This is when you get disarmed and for whatever reason you want to attack now instead of wielding a second weapon or picking one up off the floor and re-wielding it.  This kind of occasional fallback is precisely the role for brawling, imo.

>Counterstrikes to get good defense when surrounded or otherwise impaired

This applies to *some* styles.

>Non-metallic weapon

Unarmed still shocks you though, IIRC.  Unless something changed one still needs a real non-metallic weapon to fight shocking zeds as opposed to bare or gloved fists.

>NPCs trust you more if you aren't wielding a weapon while they form their opinion of you or when they're mugging you

Good point, and this might become very important later when the recommended setting will be "dynamic NPC spawns = true"  I believe currently the recommended setting is still "static NPCs" only, which means you get one starter NPC, and only very rare encounters besides that.

>Unarmed is still better than improvised weapons and sledgehammers

Are you sure about that?  A simple quarterstaff is non-metallic and gives 20 damage boost when it's juiced up by a resinous cord (which is an early game item).  19 without the resinous cord buff.

So with the equivalent skill levels, comparing unarmed skill level 2 to bashing weapon skill level 2 (and comparing 6 to 6 and so on, with the same melee skill score), you're telling me krav maga will do the same or better damage compared to a quarterstaff?  A quarterstaff comes with a free rapid attack too, and a block.  It uses 12 volume which is a bit of a problem in the early game, but it insulates your attacks from electrical damage and *it doesn't require 3 points at chargen or a special book find*.

I think we should also keep in mind that dojos are notoriously unreliable in how they spawn books and in how they themselves get spawned in cities.  I've been very lucky with the dojos and very unlucky.  So if someone wants to rely on an unarmed attack it should still make a lot of sense to spend 3 points at chargen and there should be a massive reward for doing so.

Another thing to consider is this: how well does drunken boxing trait work?  It's a 1 pt trait that I also never pick.  I have no idea what its specific in-game effect is.  I think it's supposed to increase bashing damage.  I tried it a few times and didn't notice anything that made me go "oh boy I really need to use this trait more."  Which is to say, I didn't notice anything at all.

I think in terms of game philosophy all the damage-oriented unarmed styles over and above brawling should be first class choices for non-technological fighting (technological fighting is anything like firearms, car turrets, bombs, remote control vehicles and anything else that goes beep beep or whirrrr when it operates).  Brawling should be the choice of people who want to use unarmed as an occasional situational fallback while mostly resorting to say blades.

**Comment by kevingranade** [comment]
> My take is, with unarmed styles you should be able to use unarmed as your
primary damage style from start to finish of the game, so it shouldn't be
losing to the strongest of axes, blades, etc.

Both of these statements are deeply flawed.
There is no reason a particular game mechanic should be sufficient for all
situations, and I would actually prefer the opposite, having various
options with deep enough tradeoffs that being a generalist and choosing an
action to suit the situation is the optimal approach.
Using an unarmed martial arts style has various tradeoffs vs using a melee
weapon, but it's absurd to try and make them comparable in damage output,
weapons are just better at that.

**Comment by aeoo** [comment]
@kevingranade 

So do you believe that all the martial arts styles have compelling value that justifies 3 points at chargen?

How about at least lowering the value of all the martial arts styles from 3 to 2 points at chargen, assuming nothing else changes?

I'm all about tradeoffs, but they need to make sense first.  Right now it makes little sense to spend 3 points at chargen to get a style that's barely better than brawling, and then you'll be using a weapon and a rifle and a car anyway.  How is this creative?

Your decision drives people toward a uniform style of character.  You're telling people martial arts styles are supposed to be uniformly worse than weapons.  Weapons are uniformly worse than rifles.  And so on.  What this does is it pushes all the characters toward the same choices.

Plus, if a martial arts style is short 20% in damage output compared to the best weapons, that's plenty, don't you think?  Or how about 33%?  That's really good, right?  So the weapons still have a significant edge but the unarmed styles are actually genuine useful and are worth 3 points at chargen.  Then some people will choose to focus on martial art styles and some won't.  This will move us away from cookie cutter characters by inviting people to make choices instead of telling them X is unequivocally better than Y, and Y is unequivocally better than Z and so on.

So there is definitely a middle ground that satisfies both what you're talking about and what I am talking about, @kevingranade.  It can still be true that the weapons are more damaging, but they don't need to be so absurdly better that they become the only choice and a necessity.

@kevingranade what role do you see martial arts styles play?  What are they for?  What kinds of characters get them at chargen?

**Comment by aeoo** [comment]
Also @kevingranade, if you're leaning toward realism for realism's sake, why does krav maga enhances katana damage?  How does that make any sense?  Krav maga should only enhance small blades like knives and similar, and not full on swords, if we care about realism.

Secondly, I've now done some play testing, finally.  I find the results to be, *not terrible*, but still pretty absurd.  Let me elaborate.

I've created a character with stats 9,9,8,8, melee 2, bashing 2, unarmed 2 for the purpose of testing.  This is with a default evacuee scenario.  No positive or negative traits.

I then dropped a Krav Maga manual using the debug menu, a quarterstaff, a katana, some first aid kits, some tramadol, and proceeded to test various things.  I was spawning tough zombies and zombie soldiers at this phase.

The first thing I noticed is that brawling, is in no obvious way inferior to krav maga with the above settings.

Second thing, quarterstaff seems to beat krav maga, as I expected it to.

Third thing I noticed is that krav maga enhances katana damage.

Then I raised melee to 5, bashing weapons to 10 and unarmed to 10, spawned brass knuckles and continued testing against moose, zombie soldier and cyclopean.  I wanted to see what would happen at high end.  I was healing and de-paining completely before each spawn.

OK, so here I noticed that brawling is either as good as krav maga or maybe even superior??

Second thing I noticed is that at this skill level quarterstaff is no longer obviously superior anymore, but it still held its own just fine and wasn't significantly worse.  What was making a big difference at this level is the high level specials of the unarmed styles.  This is why quarterstaff was having a bit of trouble keeping up here.

But what I also noticed is that when I wielded brass knuckles, there was a massive damage boost from krav maga.  It appears now unarmed styles can be used in conjunction with unarmed weapons.  When I use brass knuckles with krav maga, there seems to be something like 50% to 100% (double in some cases, basically) increase in damage and all the specials still work.

Both brawling and krav maga now work with brass knuckles, and imo brawling has an edge over krav maga in that it has a counter attack such that often things can't even hit my character.  Krav maga doesn't seem to improve anything over and above brawling.

And a katana with a skill of cutting = 10 still completely dominated brawling and krav maga in terms of damage.

**Comment by aeoo** [comment]
I've done some more play testing at high end with 2 in dodge, 5 in melee and 10s in bashing, piercing, unarmed, cutting, with a character souped up with bionics but stats only 9, 9, 14, 8.

I had myself learn every unarmed style using the debug menu.  I noticed that there are some pretty strong inconsistencies between styles that seem like they need a bit of tuning, but I don't want to get into that here.

I noticed that hydraulic muscles do provide a huge boost to pretty much everything and they only create noise level 19 and no other downsides.  They drain 17 PU per turn, which is either a lot or a little depending on how much power you can store.  Personally I'm not a huge fan of balancing all the stuff with the expectation that eventually you'll want to be using hydraulic muscles for combat.  I'd rather hydraulic muscles fill a more utilitarian role.  I imagine someone with hydraulic muscles should have the strength and the agility of a construction crane, and I figure this kind of bionic is used on the construction sites by bionic construction workers and not in combat.

I also noticed that bionic claws performed really weirdly too.  Somehow they performed as well or better without any unarmed styles, which is strange.  So bionic claws by themselves were as good as krav maga + bionic claws.

There might be some strange interactions between certain weapons and unarmed styles now that the styles allow the use of certain unarmed weapons.

Bionic combatives seemed kind of useless and unimpressive and it's a rare style (can't start with it either).

There is overwhelming amount of information to consider.  There are so many styles and they do so many things and now there are so many more style + weapon combinations too, it's not at all easy to test everything and balance it.  I've spent a few hours play testing and I feel like I barely scratched the surface as far as the various combinations of styles and weapons go.

So my current opinion is that unarmed styles need some love.  Krav maga and brawling are far from the worst styles imo.  I must agree with @Coolthulhu on this specific point.

I still think there is no shame in buffing the damage on even the best unarmed styles and some styles need massive amounts of love to get to par, imo.  Unarmed damage doesn't have to be equal to a diamond nodachi or a diamond katana, but there is no problem if it's equal to a katana without any style at equivalent skill levels.  I also find it strange how *relatively* good brawling is.  With brawling as it is, there is really little incentive to get any other styles.  I wouldn't solve this by nerfing brawling.  I'd solve this by buffing everything other than brawling, in some cases by a lot.  Brawling is one good reason to train unarmed, but specialists who dedicate more to their unarmed training should be rewarded more, imo.

I would be OK with all the unarmed weapons receiving appropriate nerfs too, because now they can be used together with the unarmed styles.  An unarmed weapon plus an unarmed style should probably not result in a massive explosion of damage, but only in a decent little increase, but the base damage for unarmed should be much higher.  That's how I'd balance it. :)

**Comment by Coolthulhu** [comment]
> Don't forget that regular punches can always be supplemented by brawling. Is brawling useless right now?

Brawling is bad at damage, it's pure utility.

>  Unarmed attacks do ludicrous and certainly game-winning heaps of damage under the right circumstances in DCSS, without any chance danger from a bad mutation or a bad bionic.

DDA unarmed depends mostly on strength. Getting a lot of it will help with damage output noticeably too.

> Right now the difference between krav and brawling is too subtle, imo. I like that there is brawling, btw. I just think unarmed plus a dedicated martial art style needs to do damage comparable to the best weapons in the game.

I disagree. Unarmed is faster, gets more crits (= more effects), gives extra effects etc.
I'd rather have it be more about utility than pure damage. Like what Kevin said.

> But in DCSS transmutations are neither random nor dangerous to your character's health.

Mutant starts allow getting safe muts.

> That seems absurd to me, because then hydraulic muscles become mandatory for unarmed practitioners.

Yeah, that's not really optimal. But that's mostly a problem with infinite bionic power, which was always a problem.

> I think they should be unapologetically strong and should be a no-brainer for anyone who wants to focus on unarmed as a primary source of non-hi-technological damage.

Problem with balancing them is that you eventually gain styles outside those traits. Styles like Krav Maga and even stronger ones like Muay Thai.
They should drop in points, not gain in power to be worth 3 points.

> Not all martial arts styles feature knockbacks.

But with high unarmed you can just use brawling at any time to do that. Without high unarmed you simply can't.

> If mutations can be made safe and reliable, I take everything I said here back.

Try lab or experiment scenario and play with fangs+toe talon+high strength (14 or so).

> This applies to some styles.

Styles can't be fully separated. When you get Unarmed, you get better in all of them at once. And brawling is available to everyone.

> Are you sure about that? A simple quarterstaff is non-metallic and gives 20 damage boost when it's juiced up by a resinous cord (which is an early game item). 19 without the resinous cord buff.

Unarmed is faster, gets the same damage boost from stats and more from skills. And it's available at all times, no huge bulky item to carry.

> So with the equivalent skill levels, comparing unarmed skill level 2 to bashing weapon skill level 2 (and comparing 6 to 6 and so on, with the same melee skill score), you're telling me krav maga will do the same or better damage compared to a quarterstaff?

At 2 no, but at 10 it should outdamage it.

> So if someone wants to rely on an unarmed attack it should still make a lot of sense to spend 3 points at chargen and there should be a massive reward for doing so.

I'd rather nerf or remove the trait. Most styles are currently trap options.

> how well does drunken boxing trait work?

Boosts your damage and accuracy when you're drunk. No cap, can get ridiculous, but is quite weak in vast majority of cases.

> Plus, if a martial arts style is short 20% in damage output compared to the best weapons, that's plenty, don't you think? Or how about 33%?

It's more complicated than just pure damage output.

**Comment by aeoo** [comment]
Another funny thing: drunken master + brass knuckles + no style is seemingly better than brass knuckles + krav maga with the setup described in the above message (even when drunk).  Am I right to think that the 1 point chargen trait "drunken master" only gives its bonus when one isn't using a style?  At least it doesn't seem to work with the krav maga.

So a 1 point trait plus alcohol appears to outperform a 3 point trait at least in terms of damage, at least in my brief testing.

What would be nice too, is if drunken master gave a better player feedback in the @ screen.  Right now it just says "Drunk" when you're drunk, even if you have the "drunken master" trait.  I figure it would be better if when you hovered over "Drunk" in the "@" screen it said something like +20 bash damage, or something.

**Comment by aeoo** [comment]
@Coolthulhu 

>It's more complicated than just pure damage output.

I'm well aware.

Special effects do not make up for the current damage shortfall when considered w/o the unarmed weapons.  It's often better to deal maximum damage than to deal less damage plus a special effect.  Why so?  Because if you can kill something in 2 or 1 attacks, you should prefer than over monkeying around with the same thing for 10 rounds applying all kinds of effects to it.  As you extend the length of combat you also extend risk to your character.

So I think unarmed falling behind by 20% in top damage compared to top weapons is a good idea *precisely because* I am taking into account special effects.  Without those effects I'd want 100% parity.  I'm not a fan of realism in this regard.  I like the standard roguelike trope of unarmed being a first class damage option, no apologies, no shame.

So even if I make the most charitable assumption about special effects, unless those effects are truly staggering and they apply with something like 90% regularity, OK, maybe this can account for damage being off by 50%.  It still makes no sense to extend the life of the enemy just so you can monkey around with it some.  The best and smartest choice is always going to be instant death.  Instant death is the ultimate technique.  Not stun.  Not pushback.  Etc.

Plus some effects are way too subtle to be useful or fun.  For example +4 attack speed if you're not hit?  That's not a fun, noticeable special effects.  It's subtle and very ineffective.  What would be better?  Even if you wanted to keep this trope, I would fix it as follows: +50 speed, but let it stack only 3 times instead of infinitely.  Then you get a very visible effect right away.  It's more obvious, and thus more fun.  You need to be a scientist with a spreadsheet taking copious notes to notice +4 speed during regular gameplay.

There are probably more cases like this.  Special effects should be eye popping and strong to account for a massive shortfall in damage.  And in my view, regardless of how good those special effects are, you still want damage to be good anyway.

So "but special effects" is not by itself a sufficient argument to keep the damage very low.

That said, I think unarmed weapons contribute way too much damage to the unarmed skill.  I also think some effects in some styles are too subtle or otherwise represent unfavorable tradeoffs.  I think currently there are plenty of styles no sane player will want to use, even if you get them from books in-game.  Never mind chargen.

Also I think balancing unarmed entirely around what can happen in a lab start is not a good idea.  This might be the same thing as the unarmed weapons issue: too big of a damage buff.  I'd solve it the same as with the weapons: reduce damage bonuses from weapons or claws, but buff the base unarmed damage very significantly (in some styles much more than in others).

**Comment by aeoo** [comment]
As for hydraulic muscles I think a fun motto for them would be "the strength of a construction crane with the agility of the same."  I'm in favor of making hydraulic muscles give +50 strength instead of +20, but give -50 dexterity and require even as much as 800 energy per turn instead of 100.  So basically it's what you'd use to lift cars, push on walls of buildings, dragging an 18 wheeler out of a river, but not for combat.  So it would have a very similar utility to a construction crane.  It would let you change tires without a jack (it probably already does this, I'm guessing).  Things like that.  But in combat a hydraulic muscle I think should generate a nearly guaranteed miss and plus take up a ton of time, giving enemies a ton of turns on you in the meanwhile.

**Comment by kevingranade** [comment]
You are choosing to ignore a critical point I've made, there is no good rationale for artificially buffing unarmed combat to make it a match for melee combat with weapons.  Because of this very nearly everything you are saying is irrelevant, because it is predicated on the assumption that they should be competitive.
If you want to enhance the niche of unarmed combat do some research or thinking and come up with some areas where unarmed combat excels compared to weapon combat, and make suggestions along those lines, but unsubstantiated assertions that unarmed combat "should" be competitive to weapons aren't going to go anywhere.

As for this issue, it was answered yesterday, and the ensuing discussion belongs on the forums, not here.
> Crit nerf was totally intended.
> Krav Maga nerf wasn't the intent, but it isn't really wrong.
