### ISSUE TITLE
"edit-mode" for monstergroups entries:  "addition" and "override"

### ISSUE THREAD

**Issue by Malkeus** [CleverRaven/Cataclysm-DDA#14947]
This would work in a similar fashion to the modify/override flags for monster entries. A modder could use the addition mode to tack a new monster onto an existing named monstergroup, instead of recreating the entire group with the new monster tacked on. The current method leads to conflicts when 2 mods alter a particular monstergroup, requiring an additional override mod combining both mods new entries AND duplicating the core data [example](http://smf.cataclysmdda.com/index.php?topic=11871.0). Without an override, one mods entries will be lost, and it's monsters won't spawn as intended. 

The override mode would behave like the current method and replace the entire named group.

Example from dinomod (dinosaur.json):
    "type":"monstergroup",
    "name" : "GROUP_SWAMP",
    "default" : "mon_null",
    "monsters" : [
      { "monster" : "mon_lemming", "freq" : 50, "cost_multiplier" : 0, "pack_size" : [2,7], "conditions" : ["DAY", "SPRING", "SUMMER", "AUTUMN"] },

---snipped 292 lines of monster entries copy/pasted from core data---

```
  { "monster" : "mon_spinosaurus", "freq" : 1, "cost_multiplier" : 50 },
  { "monster" : "mon_tyrannosaurus", "freq" : 1, "cost_multiplier" : 40 },
  { "monster" : "mon_allosaurus", "freq" : 2, "cost_multiplier" : 30 }
]
```

would become:

```
"type":"monstergroup",
"name" : "GROUP_SWAMP",
"edit-mode" : "addition",  
"monsters" : [
  { "monster" : "mon_spinosaurus", "freq" : 1, "cost_multiplier" : 50 },
  { "monster" : "mon_tyrannosaurus", "freq" : 1, "cost_multiplier" : 40 },
  { "monster" : "mon_allosaurus", "freq" : 2, "cost_multiplier" : 30 }
]
```

**Comment by Noctifer-de-Mortem** [comment]
This would be very similar to how item groups group where you just add a wished item to a specific item group and it adds it without rewriting the whole item group.

**Comment by chaosvolt** [comment]
Yesss. This is one of the big things that might cause hindrances regarding mod compatibility. Though at present, if I recall Dino mod is the only official mod that edits monster groups.

**Comment by Malkeus** [comment]
Arcana overrides several groups as well.

**Comment by chaosvolt** [comment]
Hmm? I could've sworn I added new monster groups, not overrode existing ones,

**Comment by Malkeus** [comment]
Different groups than dinomod though, so there's no conflict.

**Comment by Malkeus** [comment]
Isn't group nether in there? If not, my mistake.

**Comment by chaosvolt** [comment]
Let's see...GROUP_NETHER_LAVA (flying nether monsters, used in the eerie glowing pit), GROUP_IMPACT (mixture of nether and cultist monsters), GROUP_IMPACT_FLYING (flying nether monsters minus the SUNDEATH hunting horror, plus vortices), and GROUP_GROVEBASEMENT (triffid plus nether monsters, minus anything that could eat loot or easily leave the moruboru runnin' wild prematurely).

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
