### ISSUE TITLE
Automated minutia

### ISSUE THREAD

**Issue by Shoes01** [CleverRaven/Cataclysm-DDA#14971]
I think the survivor needs to spend more time getting ready for the day, but the player shouldn't have to "ready up" everything.

I've talked about hygiene, and I've also talked about folding/packing things properly. Both of these things, while necessary IRL, would be a chore for the player. Very few people would actually enjoy folding the clothes they pick up to properly place it in their backpack... however, a well organized survivor would make optimal use of his or her containers.

My idea is this: press a button, such as "P"repare, and your survivor then takes the time to do all these minute things. Pack things away properly, use a razor/other basic hygiene, sew all your items back to reinforced, perhaps even eat and drink to a satisfied level. Once magazines are implemented, have the survivor top those off, etc etc. Heck, maybe even you could add your own tasks (cook 4 x deluxe eggs) to your "P"repare list. The list and complexity of tasks would dictate the time it takes to complete them. 

The result: spend time to gain morale/focus, in an immersive way. Allows developers to introduce 'boring' mechanics (hygiene), which are important IRL, without impacting the game much.

And yes, I understand how strange it is to suggest a mechanic be added where the player doesn't actually interact with it...

**Comment by illi-kun** [comment]
It's sound like complex but useless "enhancement", and request consists of various sub-requests which were discussed previously (hygiene, macros). Sorry.

**Comment by Coolthulhu** [comment]
It wouldn't be all that useful, but it would be a lot of work.

Topping off magazines would be doable, but most people keep them full anyway. A separate "reload all" (possibly only just some flagged items) would be necessary here, because most uses of "reload all guns" command wouldn't include shaving or ironing clothing.

Vitamins would need their own solution. And proper solution to vitamins would be separate from the prepare button anyway - they take no time to use.

Repairing all items could be a thing, but it could easily last more than the rest of the preparation.

Craft lists could be a thing, but they wouldn't be too useful for preparation. Plus, they would offer a rather boring diet - it would cause situations like "Bread would be better, but I already have eggs on my prepare list, let's just go with that".

Out of those, only "repair all" sounds like actually useful.
But it wouldn't be something you do on wakeup. It would be something you spend most of your day on.

**Comment by kevingranade** [comment]
How is this better than the current status quo of "most of these things are assumed to happen "off-camera""?
For repeated tasks that are already present in the game, I feel like targeted commands might be a more reasonable thing to do, such as the mentioned "repair all", and "organize inventory", and "reload all guns/magazines".

**Comment by Shoes01** [comment]
I agree with all the points here. I was curious as to what sort of discussion this would generate, and it seems a "do X" macro, that may or may not be player modified, is the fruit of it. 

I will go ahead and close this issue :)
