### ISSUE TITLE
Magazine/gun reliability

### ISSUE THREAD

**Issue by mugling** [CleverRaven/Cataclysm-DDA#14993]
Split off from #14949

> Also loving that magazines can affect reliability

What are the mechanics for poor reliability? Jams? Wasted ammo? Suggestions...

**Comment by Coolthulhu** [comment]
Jammed gun could require unjamming that would take the same time as reloading the magazine.
I don't see how a magazine failure could waste ammo.
Dislodged magazine dropping on the ground could be a thing. Possibly spilling the ammo in case of some really primitive (crafted) magazines.

**Comment by mugling** [comment]
> I don't see how a magazine failure could waste ammo.

You have to eject the unused round which ends up on the floor?

**Comment by mugling** [comment]
How about the following initial implementation:

1. For each trigger pull roll a random number from 1-10
2. Add the current magazine and gun damage to this
3. Subtract this from the magazine reliability only

For negative results consider the following list sequentially with a 50% to apply a penalty at each level stopping after the first penalty, the end of the list or penalty exceeds the bad roll.

- - 1 `EJECT_FAIL` - requires cycling of the action (wastes turn equivalent to misfire)
- - 2 `BAD_FEED` - adds `JAMMED` flag to gun which can only be cleared by magazine ejection
- - 3 `LOST_MAG` - magazine fell out
- - 4 `SPILL_MAG` - as above but spills ammo
- - 8 `BREAKS` - magazine or gun is destroyed

In practice this means that undamaged ruger 223 mag (`reliability 9`) has a 5% chance to suffer a problem which will always be `EJECT_FAIL`.

For a survivor 223 mag (`reliability 5`) the possibilities for each trigger pull are:
- `SUCCESS` 60%
- `EJECT_FAIL` 25%
- `BAD_FEED` 10%
- `LOST_MAG` 4%
- `SPILL_MAG` 1%
- `BREAKS` 0%

We shouldn't force a player to immediately eject the magazine giving the player the option to reach for a sidearm. Certain magazines or guns could prohibit certain failure modes (eg. caseless ammo can't have `EJECT_FAIL`)?

This should be open to both balancing (adjust reliability, probability roll and penalty thresholds) and future extension (more failure modes).

**Comment by Coolthulhu** [comment]
> Add the current magazine and gun damage to this
> Subtract this from the magazine reliability only

Reliable guns shouldn't increase damage that when damage is below some threshold.

I'd rather see the rolls use much higher numbers than 10. 10 would make the difference too strong - reliable magazines would almost never jam, improvised ones would jam commonly, only damaged ones would cause further damage.
This would make the improvised firearms even more useless than they are now.

Should be more like:
* Reliable magazines don't affect ejection failure too much (that's more of a gun thing), generally don't detach unless the gun is unreliable, never spill, don't get damaged by use.
* Unreliable magazines cause failure to feed (faster to clear than re-attaching the magazine, but slower than shooting - say, just regular reload or unload time), jams that require reattaching the magazine and sometimes lost mag and spill.
* Damaged gun could increase the chances of all of those when its damaged above its reliability. Unreliable guns could naturally increase the chance.

Some failure chances could depend on recoil - it would make sense for a bad mag to be more likely to detach when firing a gun that kicks hard.

> 8 BREAKS - magazine or gun is destroyed

This sounds too punishing. Could instead cause damage to gun and/or mag or cause a semi-permanent jam that would require firearm tools and few minutes of work to remove, essentially making the weapon useless for that one encounter.
Unlike with many other items, gun damage is meaningful because they can only be repaired with rare and relatively costly tools.

**Comment by mugling** [comment]
> Reliable guns shouldn't increase damage that when damage is below some threshold

Damaged guns increase the chance for a reliability problem

> reliable magazines would almost never jam, improvised ones would jam commonly, only damaged ones would cause further damage.

The first two statements sound desireable but the later one needs correcting

> Some failure chances could depend on recoil

Yes, that's a good idea indeed. Repeatedly burst firing a weapon should increase the chance of most of the failure modes.

> `BREAKS` ... could instead cause damage to gun and/or mag ... unlike with many other items, gun damage is meaningful because they can only be repaired with rare and relatively costly tools.

Fair enough

> cause a semi-permanent jam that would require firearm tools and few minutes of work to remove

A long action sounds good but possibly without the firearm tools though?

**Comment by Coolthulhu** [comment]
> Damaged guns increase the chance for a reliability problem

I mean, damaged guns shouldn't increase the reliability problems in the same way.
A damaged high-tech polymer wonder should lose a lot of its reliability, a damaged Mosin Nagant should function comparably to undamaged one.
Gun reliability shouldn't affect magazine-only failures, though.

> The first two statements sound desireable but the later one needs correcting

In this case "almost never" means "unless damaged beforehand". Since gun maintenance isn't currently a thing, the only way to damage a gun is to either have it misfire or be used to attack/block.
So reliable magazines would last forever rather than just being reliable.
Like in your example where the only option of failure is the loss of a turn, which in case of pistols is negligible.

> A long action sounds good but possibly without the firearm tools though?

Maybe with damage chance due to lack of tools?

**Comment by mugling** [comment]
> Gun reliability shouldn't affect magazine-only failures, though.

Might be simplest for now to keep them separate for the reasons you describe

> > A long action sounds good but possibly without the firearm tools though?

> Maybe with damage chance due to lack of tools?

With a warning to the player before proceeding without them?

> So reliable magazines would last forever rather than just being reliable.

I was thinking about a 1% of damage per round fired to simulate wear with magazines repairable with similar tools to other items?

**Comment by mugling** [comment]
How to show magazine damage to the player?

**Comment by Coolthulhu** [comment]
> With a warning to the player before proceeding without them?

Could even have the chance shown directly:
"You are trying to unjam your %s without proper firearm tools. %d% chance to damage it. Proceed?"
But some tools should be required anyway. At least pliers or a screwdriver.

> I was thinking about a 1% of damage per round fired to simulate wear with magazines repairable with similar tools to other items?

Could be it.
But repairs should means something, not just soldering iron + scrap. If it was just about soldering, there may as well be no damage to magazines.
Maybe with improvised ones being solderable, but advanced ones requiring proper tools.

Also, magazines could stop getting damaged after some point. Misuse could probably wear them down, but it would be unlikely to make them disintegrate.

> EDIT: possibly specified via a durability property?

Maybe some formula of reliability? `one_in( 10*reliability )`, for example.

> How to show magazine damage to the player?

Could be a bit of a problem.
Maybe the player weapon display should get another line to display ammo type and magazine damage.

**Comment by mugling** [comment]
> "You are trying to unjam your %s without proper firearm tools. %d% chance to damage it. Proceed?"
> But some tools should be required anyway. At least pliers or a screwdriver.

Ok, this is the mechanic for jams I'm going to go with - infrequent but costly.

> Also, magazines could stop getting damaged after some point. Misuse could probably wear them down, but it would be unlikely to make them disintegrate.

Makes sense and also means the 'repairs' can be harsher (require gunsmithing tools)

> Maybe the player weapon display should get another line to display ammo type and magazine damage.

Makes the most sense and should probably be extended to show gunmod details as well

**Comment by Night-Pryanik** [comment]
>I was thinking about a 1% of damage per round fired to simulate wear with magazines

So 30 rounds fired from standard 30-round magazine mean magazine is worn for one-third? I think 1% is a way too much, maybe 0.05%?

>Also, magazines could stop getting damaged after some point.

After some point of damage they could become fully unusable and require repair to become functional.

**Comment by Rivet-the-Zombie** [comment]
>You have to eject the unused round which ends up on the floor?

Unless the round has already been struck (and was a dud) you could just pick it back up and reuse it.

This is even simpler if the gun has a brass trap, as the unspent cartridge would just end up inside its bag.

**Comment by stk2008** [comment]
If reliablity is added please please tell me NPC`s weapons will also be
effected by this?

**Comment by kevingranade** [comment]
Just some generalities, I'll try to make a more detailed reply later.
1. Jams are quite rare in reality, the reputation of the "notoriously
unreliable" m16 was based on a jam rate well under 1%, and that was with
sand and dirt poured into the action before the tests. IIRC it was
something like .03%.
2. Jams could easily have several levels of severity, one kind can be
cleared by working the action of the gun, but *very* occasionally it might
require tools to clear.
3. I feel like it makes more sense to add magazine and gun unreliability
together and make one check, because feed errors from a bad magazine are
going to be nearly impossible to separate from feed errors from the action,
and it makes the math easier.

**Comment by stk2008** [comment]
I may be wrong but the m16a1 was made to remove the unreliablity of the m16.

The m16a1 was more reliable because i think it had some different metal in
the barrel or some thinG along them lines.

I may be wrong here but i heard some thing about this on discovery channel.

The m16 im sure was very unreliable in viatnam some thing to do with the
weather and dirt/water actually im sure it was some thing to do with water.

**Comment by Rivet-the-Zombie** [comment]
You're not wrong; it was a retrofitting kit that replaced the receiver with a chromed version.

**Comment by stk2008** [comment]
Ah i knew it was some thing along them lines :)

**Comment by kevingranade** [comment]
Yes, but my point is even the "notoriously unreliable" original m16 was
still only misfiring on 3/10,000 rounds or so (that number might be off,
but it was way under 1%).

**Comment by mugling** [comment]
Yes 1% jam rate for an undamaged factory magazine is too high.

I was proposing each round had a ~1% chance to damage the magazine to simulate wear and that damaged or improvised magazines were as a consequence less reliable. Effectively this means that magazines don't last for ever.

Such damage would need a lower bound as the magazine would never be destroyed.

The main stumbling block is how to show to show display magazine damage to the user?

**Comment by kevingranade** [comment]
I'm not sure that should happen at all,  how quickly do magazines wear out
irl?  Unless they wear out* within a year or so it's too short a time
period for us to worry about.  1% chance per round is going to lead to
magazines wearing out in under 1,000 rounds, which is definitely wrong.
AFAIK 10,000 rounds is a break in period for this kind of hardware, and at
those wear rates it's not something we even want to track.

*wear out here is "start to degrade in performance".

**Comment by Malkeus** [comment]
Damage should still be taken into account, in the case where a magazine is dug out of the wreckage of a burnt building, it should have some issues without taking the time to repair it. Ditto for random damage at lootspawn.

**Comment by Rivet-the-Zombie** [comment]
>I was proposing each round had a ~1% chance to damage the magazine to simulate wear and that damaged or improvised magazines were as a consequence less reliable. Effectively this means that magazines don't last for ever.

There's not a magazine out there that wears out this fast in real life. If cared for and not abused, they can last for pretty much forever - I've fired removable-magazine type firearms that are nearly a century old, and their ancient magazines worked just as well as if they were fresh from the factory.

>The main stumbling block is how to show to show display magazine damage to the user?

The same way every other item displays its state of damage?

**Comment by kevingranade** [comment]
This is a valid suggestion, but it's an old suggestion no one seems to be interested in implementing since the rate of occurrence would be so low.
