### ISSUE TITLE
Different stat blocks for weapons based on attack range

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#15034]
I've been thinking about giving reach weapons alternate stat blocks to represent different attack types.  The most obvious use is allowing reach weapons like the halberd to stab at range 3, chop at range 2, and haft-bash at range 1. That's not necessarily correct, but gets the idea across.

**Comment by chaosvolt** [comment]
Hmm. 3 is still quite a lot though, and loosing chopping at melee range is a lot weirder than, for example, losing a spear's stab damage at melee range.

**Comment by Coolthulhu** [comment]
I though about multiple attacks for weapons, but more in context of multiple melee attacks.
Things like ice pick/warhammer stabbing or piercing, bayoneted weapons not bashing when stabbing, knives stabbing or cutting.
Though once we got one kind of multiple attacks, others would be simple.

While we're at statblock revisions, it would be cool to get rid of stabbing-is-cutting thing and give it a separate field.

Reach attack could also become a technique rather than a flag. This would allow making it cost more or less moves, deal more or less damage (for weak ranged jabs with a quarterstaff, for example) or disabling just the bashing component of damage.

I don't think halberd should get reach 3, though. It would be a really solid weapon at reach 2.

**Comment by kevingranade** [comment]
> That's not necessarily correct, but it gets the idea across.

**Comment by chaosvolt** [comment]
True. Still pondering the best way to handle multple attacks. Reach? Technique? Some new mechanic? Not sure.

**Comment by Shadefang** [comment]
First thing that came to my mind was to handle it (from a UI standpoint) about like you do burst fire/weapon mods. Hit a hotkey to toggle the attack type you're using. This along with allowing multiple attack styles to be defined in json (say, through an alt_attack field) would seem to give the most freedom.

**Comment by Coolthulhu** [comment]
I'd prefer it to be automatic, at least by default.
The character could estimate which attack would be the best against a given enemy without having to manually set the attack mode.

**Comment by Shadefang** [comment]
The issue i see with the automatic choice is that what is best is subjective and situational. Sure a sweeping bash with a spear will probably be more effective against a skeleton than a quick jab, but I don't want the game deciding that's the case for me when i'm fighting several things.
I could somewhat see an automatic mode by default, but it seems  that it'd be an additional option you have to cycle through that doesn't give a large amount of benefit, and increases the unpredictability of your own character's action. I'd personally prefer the default to be whatever's the norm for that weapon (stabbing for a spear, chopping close in for a halberd, etc.) and have the alternate attacks be something you have to actively use when the situation calls for it. and if that means you have to manually switch to using the haft of your spear to kill skeletons, that's not really a bad thing.

**Comment by Malkeus** [comment]
Perhaps a fusion of both ideas would work best. Allow for mode switching
similar to burst fire, to allow for tactical choices, but make one of those
modes 'auto' to allow the game to choose for you.

**Comment by Shadefang** [comment]
Possibly allow a weighting field on the item to determine how common the attacks are. Both to avoid having to write something to determine attack effectiveness, and to allow creators to make attacks that should be uncommon, or _always_ be a conscious choice

**Comment by Coolthulhu** [comment]
> to avoid having to write something to determine attack effectiveness

We will need that one for NPCs anyway. Letting player use it too would be a convenience.

**Comment by Shadefang** [comment]
Good point, I wasn't thinking of that. 
I would personally ask, if it's reasonably simple to do so, that there be an option somewhere to turn off defaulting to autoselect. Possibly having it be a toggle separate from the normal cycle. For those of us who would have cycling off auto be the first thing we do whenever we wield a new weapon.

**Comment by kevingranade** [comment]
Note: ignore all of the above about selecting variant attacks, that is a completely different feature, though it could share some infrastructure.
THIS feature is about handling of reach weapons which are naturally balanced by poor attack ability when a target is too close.  There would be no selection of attack mode, just different attack types based on distance from attacker to target.

The halberd remains a good example regardless of

**Comment by brannamm** [comment]
@kevingranade I am interested in putting this feature in but have some worries because it seems like the logical 1-range-haft-bash attack for a reach weapons will be far weaker than their main attacks, resulting in a nerf for melee. Do you have any guidance on implementing this without nerfing reach weapons? Maybe something like adding knockback on the under optimal range attacks?

**Comment by kevingranade** [comment]
It's supposed to be a nerf, you need to manuver tactically to use a reach weapon properly.

**Comment by I-am-Erk** [comment]
Is this still how we want to model this? I would suggest that with how melee changes are coming along, it would probably be better to have attack modes linked to weapon range for reach weapons, and that would couple nicely with other suggested changes (eg tracking how you use a weapon to slash or stab using the framework for martial arts specials)
