### ISSUE TITLE
Uncanny Dodge does nothing outside of monster specials

### ISSUE THREAD

**Issue by macrosblackd** [CleverRaven/Cataclysm-DDA#15078]
So after a little testing and looking around in the code, I can't find anywhere that uncanny dodge affects either dodge chance or simply an outright dodge.

I'm making this issue to create some discussion on how this cbm should function in regards to ranged attacks & melee attacks.

**Comment by Coolthulhu** [comment]
From what I can tell, it is supposed to let you dodge only the powerful attacks, without wasting power for regular ones.
I don't like this bionic from dev perspective. It requires special casing and is rare enough not to matter except for overpowered postgame characters.

**Comment by macrosblackd** [comment]
Some thoughts on how we might be able to overhaul the cbm to hopefully make it a bit more balanced.

- Provide an bonus, either flat or multiplier, to dodge stat
- Any attack which would kill the user is dodged - this would have a cool down associated with it.
- Special attacks are dodged - same cooldown as above.

**Comment by vache** [comment]
I don't like it from a balance perspective because it basically neutralizes a ton of special attacks.  It's not even a "change a 1/10 chance to dodge to a 1/4 chance to dodge" its a 1/1 chance to dodge.  Too overpowered IMO.  I like the cooldown on special dodging suggested above, but it seems like this is only likely to come into play when you're surrounded.  Most of the time it is going to be a free dodge.

**Comment by kevingranade** [comment]
Having the CBM decide whether or not to trigger based on (potentially
invisible) properties of the attack is unreasonable.
Triggering based on "would kill the player" is way OP.
The original intent may have been to only dodge projectiles, which is
fairly reasonable.  If it's going to trigger on melee as well it should
trigger on all melee.
I'd much prefer a huge bonus to dodge rather than automatic dodge, this
would let us put some things back to being undodgeable by adjusting their
properties rather than by special casing.  E.g. lasers and shrapnel should
probably be impossible to dodge.

**Comment by Coolthulhu** [comment]
> E.g. lasers and shrapnel should probably be impossible to dodge.

I assume it works before the actual attack and thus should work on lasers. Otherwise the speed to dodge bullets would be Time Stop tier magic and not just dodge. And if it's time stop, it could work on shrapnel instead (except for dense clouds of it, no Touhou-ing that stuff up).

I don't really see how could Uncanny Dodge be explained in the lore, though. How does it predict stuff? How does it control the dodging? Why would it work only on a limited selection of attacks, but on an unlimited selection of mutated survivors with different encumbrances?
Why does it work for blind, bound, sleeping, legless, grappled and overencumbered (all at once, if required) survivors an arbitrarily large number of times per turn? Why does it do so without waking them up?

It's weirder than Time Stop if you think about it. Time stop is magic, but it has logic behind it, Uncanny Dodge is both magic and weird.

**Comment by macrosblackd** [comment]
My thoughts on the how behind the uncanny dodge are basically a piece of technology that takes in everything going on, makes a decision in a few milliseconds ( < 20 ms) and sends out the instructions for dodging to your body.

**Comment by ejseto** [comment]
>it is supposed to let you dodge only the powerful attacks, without wasting power for regular ones.

It was supposed to dodge everything. Wasting power on weak attacks was just a cost of doing business. Maybe someone changed it or it got lost in some refactor along the way.

>Provide an bonus, either flat or multiplier, to dodge stat

That might be reasonable now, though it feels a bit boring/ordinary. Back then, all monster special attacks were just blocks in a giant if-else, and I don't think they took any player statistics into consideration. I think they were all just 100% hit, being balanced around probability of use.

>Most of the time it is going to be a free dodge.

It *does* cost energy per dodge. Maybe it's too low, or maybe the real problem is you can keep adding power CBMs until you have millions of bionic power, assuming you live/play that long.

**Comment by kevingranade** [comment]
On Jan 29, 2016 3:59 PM, "Coolthulhu" <notifications@github.com> wrote:
>>
>> E.g. lasers and shrapnel should probably be impossible to dodge.
>
> I assume it works before the actual attack and thus should work on
lasers. Otherwise the speed to dodge bullets would be Time Stop tier magic
and not just dodge. And if it's time stop, it could work on shrapnel
instead (except for dense clouds of it, no Touhou-ing that stuff up).

Assuming shrapnel came in clouds is why I thought they shouldn't be dodged.
Good point about the lasers, practically speaking the speed difference is
irrelevant at some point. That does imply not seeing the shooter should
prevent dodging.
> I don't really see how could Uncanny Dodge be explained in the lore,
though. How does it predict stuff? How does it control the dodging? Why
would it work only on a limited selection of attacks, but on an unlimited
selection of mutated survivors with different encumbrances?

The limited selection of attacks is IMO a bug.
The encumbrance thing is one of the reasons to model it as really good
dodging instead of an automatic miss.
> Why does it work for blind, bound, sleeping, legless, grappled and
overencumbered (all at once, if required) survivors an arbitrarily large
number of times per turn? Why does it do so without waking them up?

Those are simply bugs.

**Comment by macrosblackd** [comment]
So there seems to be some consensus around changing it to provide a bonus to dodge. Any thoughts on to how to apply that bonus? Flat rate? Multiplier? Are we also looking to get rid of the 100% dodge chance on special attacks? If so, should we make the cbm passive, or maybe just lower the activation cost, with a minor hit every time you dodge while its on?

**Comment by kevingranade** [comment]
I'm thinking a flat bonus large enough to make bullet dodging feasible, but
I haven't done any math on what that would look like.  IIRC the dodging
code could do bullets, but it's impractically high.
Special dodging should work the same, but outside of gunfire it will
probably be automatic in practice.
It should remain expensive to use, too expensive to leave on continuously.

**Comment by Coolthulhu** [comment]
Could set remaining blocks and dodges to 0 and require a dodge to activate, thus limiting it to 1/turn. That would prevent it from dancing through a burst, while still keeping it useful against thinner bursts.
