### ISSUE TITLE
Guns are far too accurate

### ISSUE THREAD

**Issue by mugling** [CleverRaven/Cataclysm-DDA#15125]
Even with no skill and high recoil I have little difficulty hitting a target at the maximum range for the pipe rifle. Has anyone else noticed a recent and significant increase in accuracy?

**Comment by macrosblackd** [comment]
not really - the guns i've used at 0-3 skill have horrible or mediocre accuracy. M4A1 with decent hit chance at < 6 tiles away, pistols at < 3.

**Comment by John-Candlebury** [comment]
I don't think so, I still waste a lot of precious ammo when sniping things that more than 20 tiles away even with decent skill and gear (scoped barrett and 4 rifle skill).

I general nerf would only result in players using snipers like this:

![alt text](http://i.imgur.com/qVvgHTh.png "")

(In all honesty I'm pretty sure most players already do that)

**Comment by Rivet-the-Zombie** [comment]
I'm okay with the current level of accuracy.

----

@John-Candlebury, I really like your illustration!

**Comment by chaosvolt** [comment]
Yeah, I'm calling bullshit on that too. Accuracy seems acceptable to me.

The real issue is that RANGE is obscenely short. The actual scale of a map tile is vague, but a square meter is a good estimate. So note that all your delightfully accurate shots are in fairly close range. You're likely not scoring good hits and headshots, but at least getting hits within a reasonable distance.

I still think it would be perfectly acceptable to buff the ranges of firearms, but without buffing their accuracy. You're already going to have trouble scoring hits with most rifles beyond 20-25 tiles, so just because you CAN reach out and touch someone doesn't mean you WILL. X3

**Comment by macrosblackd** [comment]
yea, range on guns is ridiculous - most rifles are zeroed in at 100 yards, and are usually still good until 200-300 yards.

**Comment by Malkeus** [comment]
I seem to recall Kevin weighing in on the range issue before. I can't
recall what he said n I'm on my cellphone so searching for it would be...
frustrating. I rather like the idea of range limited only be some kind of
simulation of bullet drop. The current range could become a limit beyond
which accuracy went out the window and you are much much more likely to
miss. Then I could unload with my uzi at max sight range of a massive horde
and expect to get a few hits by chance. Lasers would be a problem...
Instead of bullet drop, maybe attenuation would be their limiting factor.

**Comment by chaosvolt** [comment]
I could've sworn last time I saw a contributor weigh in on giving guns realistic range, they derped and argued that getting sniped by NPCs would be frustrating, forgetting the range does not equal accuracy. :V

Can't recall who made that argument though.

**Comment by Malkeus** [comment]
^

**Comment by mugling** [comment]
Hmmn, I was getting 100% accuracy at any range which smelt like a bug but I can't seem to replicate this now.

**Comment by chaosvolt** [comment]
Hmm. Might have been RNGesus that time, a more accurate weapon, or better dex/per and skills that time. :V
