### ISSUE TITLE
Explosive projectiles not triggering properly.

### ISSUE THREAD

**Issue by Rivet-the-Zombie** [CleverRaven/Cataclysm-DDA#15187]
Explosives like 40mm grenades and 20x66mm rounds seem to have lost the ability to target the ground or enemies properly.

If aimed at less than maximum range, the projectile will attempt to travel its full range regardless, triggering its effect when it does so or reaches a solid obstruction.

If fired at a living target, it will pass through its victim - doing base projectile damage to them in the process - then continue on until it strikes a barrier or reaches its maximum range, not triggering its effect until it does so.

**Comment by chaosvolt** [comment]
Hmm. This seems like two separate issues here.

First, if it hits something it should go off, and ideally for any ranged weapon pentrating a target should affect penetration further.

Second, if a grenade launcher round misses the target...does it sail on anyway? I would assume that we've reached an issue where the DESIRED outcome should be up to the player. The player might desire to have the shot keep going, or they might aim low so that even if they  miss it hits the ground and explode amongst their targets.

**Comment by kevingranade** [comment]
Yea, explosives should target locations, not enemies.
I think what's happening with passing through monsters is direct hits cause
massive damage, and each hit just applies a penalty until the damage is
cancelled out, which basically never happens.
Possibly add an "indirect fire" flag that bypasses the "bullets keep going"
code?

**Comment by chaosvolt** [comment]
Maybe. Though an "indirect fire" idea sounds delicious if it turns into allowing firing over obstacles. Glorious mortars? X3

**Comment by Rivet-the-Zombie** [comment]
Yeah, a flag that excludes a projectile from the pass-through function would work nicely.

**Comment by Coolthulhu** [comment]
Also affects spitters
