### ISSUE TITLE
Ambush scenario bug

### ISSUE THREAD

**Issue by player0981234** [CleverRaven/Cataclysm-DDA#15210]
When you start a new game with the ambush scenario,a debug message  DEBUG:Could not find starting overmap terrain cabin  appears and then you start at the edge of a forest with a few zombies around you.

**Comment by IFailAtGaming** [comment]
That means that the map doesn't have any cabin tiles

**Comment by illi-kun** [comment]
Yeah, it happens for rare locations (and it should be fixed somehow, I'm sure it was discussed previously but I'm not sure if dedicated issue about that already exists).

**Comment by player0981234** [comment]
Fixed in the latest experimental.

**Comment by kevingranade** [comment]
This is going to be an intermittently occurring bug, I'm pretty sure no one
has addressed it.

**Comment by nanovad** [comment]
I've experienced this on maps without labs (choosing lab start).
It's hard to say what behavior should be, though. Move to a new overmap, generate (and repeat until the desired building appears)?

**Comment by narc0tiq** [comment]
Given that it's perfectly possible for a structure to be defined yet never
appear in natural worldgen at all (by accident, due to deprecation, or
otherwise), I can only suggest the "right" thing to do would be to raise an
error and return the player to the character generation phase -- they may
choose to save the current character as a template and make a new world, or
they may decide they'd be willing to try a different profession.

Bonus points for remembering (perhaps as a property of the world) that the
world does not support that particular profession and showing an early
warning the next time it's chosen (yet still with an option for the player
to override it and try anyway).

Further bonus points for a "try harder" option, where at the player's
discretion we may visit all generated overmaps (and perhaps even start
generating overmaps) in search of the elusive structure. This should show
some kind of progress indication (think of Dwarf Fortress's worldgen status
displays) and should be interruptible.
