### ISSUE TITLE
Volume 0 items

### ISSUE THREAD

**Issue by mugling** [CleverRaven/Cataclysm-DDA#15235]
We currently have the `charges`/`stack_size` system because the units for `volume` are too big to accurately represent small items (for example a single 9mm round). The long-term goal is to increase the granularity of `volume` but this is a long way off.

I'd like to start limiting the number of `volume 0` items. These can be divided into two categories - those that should be eg. `cash_card` and those that are exploitable eg. 49 rounds of `9mm` (which has a `stack_size` of 50).

I've started some refactoring of the charges code (#15153, #15157) and I'm considering the, no doubt controversial, change to stacking of charges so that `volume` includes incomplete stacks.

There may be some items for which this behavior is not appropriate. Some of these could become `volume 0` (for now) or we could consider a `STACKS_FULL` flag to temporarily handle them?

Are there any good examples of the above items and what are comments overall?

**Comment by DeadLeaves** [comment]
I don't know if it's a good way to do it code-wise as I have little knowledge of how the code regarding this looks. However I was thinking, maybe just let items use decimals in the volume? That would make so that no current items would need rework (storage and most items would need no changes). And it would allow that stack of 49x9mm to take up 0.99 or 0.9 volume. Whatever we decide a good decimal truncation would be.

Just an idea.

**Comment by mugling** [comment]
@DeadLeaves unfortunately that's not possible (C++ has no builtin type for decimals)

**Comment by DeadLeaves** [comment]
Huh? Aren't float and double built in? The more you know I guess.

**Comment by Man-animal** [comment]
Making volume more granular is a good idea, but there's no pressing balance issue around players shaving a point of volume off by micromanaging stack sizes.  Does anyone actually even do that?

**Comment by i2amroy** [comment]
>The long-term goal is to increase the granularity of volume but this is a long way off.

This is actually a whole lot easier than it seems; the only real time consuming part is finding actual volumes for every single previously zero volume item. Beyond that all you really have to do is go through the entire codebase for every place volume is referenced and provide an appropriate scaling factor to maintain the numbers as the same as they are. It's a huge amount of busywork, but nothing really complex to do, just rather time consuming.

**Comment by mugling** [comment]
> Huh? Aren't float and double built in

Those are binary floating points not decimals and you get some very exciting errors from trying to use them as a substitute.

> Making volume more granular is a good idea

Long term goal

> micromanaging

Generally indicative of poor design

> but there's no pressing balance issue

No, but as we start to move away from `volume 0` items we are likely to identify any other issues that need addressing.

**Comment by mugling** [comment]
> This is actually a whole lot easier than it seems; the only real time consuming part is finding actual volumes for every single previously zero volume item

Literally `volume * 1000 / stack_size` in the JSON is a good chunk of the work **providing** the `stack_size` and `volume` parameters are sane. The goal in forcing the issue with `stack_size` is that once items start consuming volume we're likely to get meaningful issues/PR's concerning appropriate item volumes.

> Beyond that all you really have to do is go through the entire codebase for every place volume is referenced

More painful

**Comment by Coolthulhu** [comment]
I don't like the `1000 * granularity` idea. It sounds like we're trading one kind of micromanagement for another.
I'd rather just round the volume up instead of down, with the exception of inherently 0 volume items (pocket knife).

We don't have a penalty for over-cluttered inventory, meaning that the optimal gameplay involves (and would still involve) keeping tons of nearly-useless items "just in case". Rounding it all up would be painful at first, but it would cut the micromanagement greatly.
Could be compensated for later by buffing some weaker items' storage.

**Comment by kevingranade** [comment]
I don't follow how increasing the granularity of item volumes leads to more
micromanagement compared to having a lot of volume 0 items. Refining stack
size handling leads to the same outcome, just with greatly higher code
complexity.
Most items are still going to be listed at 0 volume, it's just that
aggregations of items will add together instead of rounding down. This also
allows for cleaner handling of very small items.

**Comment by Coolthulhu** [comment]
> I don't follow how increasing the granularity of item volumes leads to more micromanagement compared to having a lot of volume 0 items.

Cluttered inventory isn't really micromanagement. It is tedious to shift through it, but it doesn't require managing at all.
By having a lot of items with very low volume to manage, we'd trade some of the inventory clutter for some of the management.

> Most items are still going to be listed at 0 volume, it's just that aggregations of items will add together instead of rounding down.

That sounds rather confusing. It would be better to just list the decimals.

**Comment by mugling** [comment]
> just with greatly higher code complexity.

I'd agree two competing systems (regular and count-by-charges) is far from ideal.

> That sounds rather confusing. It would be better to just list the decimals.

There's no reason we can't use different internal and presentation forms. Weight works this way (stored internally as integer grams but output in kg or lb).

> I don't follow how increasing the granularity of item volumes leads to more micromanagement compared to having a lot of volume 0 items.

To some extent we're confounding two issues - how we store and calculate volume internally and what items should be low or no volume. #15237 considers only the former.

**Comment by kevingranade** [comment]
I don't consider adding minuscule volume to some items to increase
micromanagement, all its going to do is discourage obvious idiocies like
storing thousands of rounds of ammo or pills in a single pocket just
because they fall under some threshold.
For the most part it's just going to mirror similar limitations imposed by
weight.
