### ISSUE TITLE
json_format_check.sh breaks on Ubuntu builds

### ISSUE THREAD

**Issue by macrosblackd** [CleverRaven/Cataclysm-DDA#15231]
```
bash: tools/json_format_check.sh: /bin/bash^M: bad interpreter: No such file or directory
```
We have several other options for writing these tools including lua & python - could we perhaps move this over to one of those? We also already have a lua tool to verify json file integrity, why not put the default value whitelist check in there?

**Comment by narc0tiq** [comment]
Your Git client appears to be configured such that it is creating text files in DOS format (line separator = `\r\n`) instead of Unix format (line separator = `\n`). This is configured by the [`core.autocrlf` setting](https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#coreautocrlf-7kTgIgFwI4), for which a value of `true` will result in exactly this behaviour.

IIRC, Windows Git tends to recommend that as a default, presumably to retain your ability to work on files from a Git repo using Notepad (that being the only editor I'm aware of that still doesn't understand Unix line endings). A much preferred value (and the default on non-Windows platforms) is `input`, which will convert DOS to Unix when checking in and do nothing when checking out (effectively leaving Unix format files in place).

---

As to using a different language... sure, why not; I don't particularly like depending on bash.

I'll note that I don't believe Python is a requirement for our build process (there are Python tools, but they're not involved in the `make` process AFAIK), therefore Lua would be the safer choice.

Do also note that it is currently possible to build a version of Cataclysm without Lua (by leaving out LUA=1 from your `make` invocation or environment), so it should be possible to avoid running the script in that case (but equally you could choose to make it a Python script that is ignored if no Python is available).
