### ISSUE TITLE
Spawn restricted "safe" zones/areas. 

### ISSUE THREAD

**Issue by valuial** [CleverRaven/Cataclysm-DDA#15253]
Discussing spawn mechanics in IRC kosan, Levitator, Sir_Kernicus and me thought of a way to prevent unrealistic spawns inside "rooms" a player secured earlier in the game. The idea was spawned by frustration of death by sudden spawn in believed to be secured areas.

We considered the game keeping track of rooms the player explored, but discarded it in favor of the following mechanic:

For a safe area the player needs to actively secure it:
- The area needs to be walled in.
- All doors and windows need to be secured (locked, boarded up, maybe with a jury-rigged alarm or similar. More ideas how to secure against entry very much welcome.)
- If there are any stairs inside the area, they need to be either secured (blocked, boarded up, etc.) or the other z-level needs to also be a secured area.

Whenever the player secures a door/window/stair, the game checks if an area with the above points met exists. If it does, the area is marked as secure, and no new spawns are allowed inside.

Active spawns should be able to breech the secured perimeter - smash windows or doors, trigger an alarm when opening doors -, which would enable spawns again. (To prevent sudden spawns while defending the perimeter, have a - hidden - timer that lets the player re-secure the area before actual spawns are permitted).

**Comment by kevingranade** [comment]
Sounds good, map fun might be able to set them too.

**Comment by mugling** [comment]
I like this idea a lot

**Comment by kevingranade** [comment]
That's map gen, curse you autocorrect.

**Comment by Zireael07** [comment]
That's a great idea. Those boarded up survivor houses might get used for something now :)

**Comment by Leland** [comment]
Looks like discussion has stalled on this suggestion. Closing. If there's still interest, let me know and I can reopen.

**Comment by codemime** [comment]
I'm reopening this because the suggestion is too good to be buried under the pile of others and forgotten. I hope I'll have some spare time to start implementing it.

**Comment by Leland** [comment]
There's a rudimentary implementation of a base through bulletin boards that got added way back in #120 and was never really expanded on. It's really just used to designate an area to send a friendly NPC back to. Would be a pretty good launching off point – ex. when a player <kbd>e</kbd>xamines a bulletin board, a check would run to see if the containing area has been secured according to the list OP posted. Perhaps the result of that check would be displayed to the player? `4/9 windows have been secured.`

Further down the line, the suggestion of having this be present at mapgen is a cool idea too – there could be one present for safe spawn points (i.e there'd be one in the evac shelter start, but not in the burning house), that's fully functional and ready to be used. Would give the player a starting base, and also introduce the player to the concept of "safe zones."

Then, there could be bulletin boards present in certain locations but the surrounding area would need to be re-secured. These would be areas that survivors had previously been in, but had been overrun or otherwise abandoned.

**Comment by Night-Pryanik** [comment]
Closing as per lack of discussion. Added OnHold tag.
