### ISSUE TITLE
Is mapgen broken

### ISSUE THREAD

**Issue by mugling** [CleverRaven/Cataclysm-DDA#15318]
For the following (simplified) mapgen:
```
"place_items": [
  { "item": "guns_rifle_common", "chance":  50, "x": 20, "y": 12 },
  { "item": "guns_rifle_common", "chance": 100, "x": 20, "y": 11 },                
  { "item": "guns_rifle_common", "chance":  75, "x": 20, "y": 10 },
  { "item": "guns_rifle_common", "chance":  75, "x": 20, "y":  9 }
]
````

With the itemgroup:
```
{
  "id" : "guns_rifle_common",
  "type" : "item_group",
  "items": [
    [ "garand", 50 ],
    [ "ar15", 25 ]
  ]
}
```

Which of the following behaviors are bugs and which are my lack of understanding?

* More than four rifles spawn in total
* More than one rifle spawns on any given tile

**Comment by illi-kun** [comment]
See doc/ITEM_SPAWN.md for reference, and pay attention to diffetence between distribution and collection (sorry for such general comment, I can be incorrect is details).

**Comment by mugling** [comment]
`guns_rifle_common` is a distribution

**Comment by BevapDin** [comment]
It's ... complicated. Take a look at `map::place_items` (mapgen.cpp). There should be exactly one item at (20,11) and one or more at the other places.

**Comment by mugling** [comment]
@BevapDin I did read through that function and couldn't explain the results I was getting (multiple items on each tile)

**Comment by vache** [comment]
The function keeps rolling as long as ```rng(0, 99) < chance``` succeeds, which means it could potentially go on forever.  100 is a special case that means "spawn one and stop".

**Comment by mugling** [comment]
@vache is that by design? What is the purpose of `repeat` then?

How do I get a % chance of an item per tile?

**Comment by vache** [comment]
It's by design so far as that's the way it's pretty much always worked and everyone has managed to get spawns where they want (for the most part) in spite of it.  

There's a json mapgen field to apply a single item with a chance (I think a 1/chance).  Some mapgens stack many single items with different chances on the same tile (I think the abandoned farm does this).

Item spawning is a bit arcane and could really use some fine tuning in terms of controlling spawn chance.  If it were up to me, I would change it so we could specify a % chance, a min, and a max, and it would roll the chance and if it succeeds would place min items, then continue rolling and placing additional items until it fails or places max items.  Another change to that might be to split chance up into 2 percents, one to determine whether to spawn items there, and another to determine whether to spawn additional items, to support something like a 100% chance to spawn between 1 and 3 items.

**Comment by mugling** [comment]
> Item spawning is a bit arcane

Very much so!

> I would change it so we could specify a % chance, a min, and a max, and it would roll the chance and if it succeeds would place min items, then continue rolling and placing additional items until it fails or places max items

What would the consensus be if I were to implement this, probably using the existing `chance` and `repeat` fields?

**Comment by vache** [comment]
Repeat has a different function right now.  Basically, when a json mapgen method specifies a wide area, it will rng a single point within that area to perform whatever task on, and that field causes it to select "repeat" number of points.

**Comment by mugling** [comment]
` { "item": "guns_rifle_common", "chance":  100, "x": [19,2], "y": [11,12], "repeat": [1,4] }`

would place between 1 and 4 items? (or 2 and 5?)

**Comment by vache** [comment]
It would place between 1 and 4 items, but it would roll a new location each time.

**Comment by mugling** [comment]
With each location being within the rectangle [19,11]->[20,12]?

**Comment by vache** [comment]
Correct

**Comment by mugling** [comment]
@vache thanks, that's most helpful

**Comment by kevingranade** [comment]
I'd be in favor of this being reimplemented, but please migrate to new
fields, otherwise you'll either have to rebalance all item groups in one
pr, or they will be massively imbalanced and confusing while the transition
is happening.

**Comment by mugling** [comment]
so how to do a % chance of a single item or is that not currently possible? Would `chance 100` and `repeat [0,1]` give a 50% chance?
