### ISSUE TITLE
Creatures can't see vehicles driven by invisible people.

### ISSUE THREAD

**Issue by withp** [CleverRaven/Cataclysm-DDA#15342]
Creatures don't appear to see vehicles themselves, but rather only the driver, and react accordingly (along with reacting to the noise). That'd be fine except that invisible drivers are then apparently driving invisible cars. This leads to zombies and robot hostiles cheerfully allowing the vehicle to pass and leads to fleeing animals not noticing you and getting run over by the vehicle when they otherwise wouldn't (in broad daylight).

Unless of course, invisibility is supposed to apply to the vehicle the invisible rider gets into...

**Comment by CIB** [comment]
So would zombies then attack empty, but running cars like sometimes spawn randomly?

**Comment by Malkeus** [comment]
Zombies are attracted to the sound of running cars, they move towards them
and attempt to move THROUGH them. The sound of them smashing into the car
attracts more zombies. I don't know how many times I've either come across
a horde of zombies surrounding a pile of scrap metal and a damaged car.

I often smash a car myself to attract zombies at night for the above reason.

To address the OP, no, zombies aren't attracted to moving cars driven by
invisible or concealed people, but they are attracted to the sound of the
cars motor. I don't see a problem really, the blob isn't doesn't want to
convert non-organics. It just wants our bodies. And silence.

**Comment by Coolthulhu** [comment]
Animals should be afraid, though.
And more important than animals would be the tankbots: tankbots should hate vehicles and nuke them with the main gun.

**Comment by BevapDin** [comment]
The behavior of the monsters is not caused by the invisibility of the driver. Monsters simply don't know that a moving vehicle can be dangerous. There is no check for this in the code and therefor a moving vehicle looks like terrain to them. They react to the driver (if they can see it).

If they flee from the driver, it will look as if they flee from the vehicle. If they don't flee from the driver, it looks as if they don't flee from the vehicle. Try this with a remote controlled vehicle. Monster will not react to it either.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
