### ISSUE TITLE
[Suggestion] Choosing side for one-handed weapons & future separation

### ISSUE THREAD

**Issue by zj44** [CleverRaven/Cataclysm-DDA#15363]
Now that we can change sides for some items, should weapon handedness be considered?

This came to mind for me when I had a swag bag in my left hand/arm while wielding a sling. I can understand loading the sling to take time for being a two-handed activity, but not affecting its accuracy! You just spin it around with one hand. This could extend to melee weapons as well since arm/hand encumbrance affects melee. I'm not advocating making players choose handedness, just the ability to use one-handed weapons on a less encumbered part.

Further down the line, arm/leg/hand armor might be separated into individual pieces as well -- nothing as specific as a 'left leather glove', but just a 'leather glove' item that could be worn on either hand.

I understand that this is not a simple change that'll come overnight but I was hoping to post this in the possibility that it might be something that could be discussed and considered.

**Comment by Coolthulhu** [comment]
Explicitly selecting sides should not be required. It would be better to always use the best side instead.

**Comment by zj44** [comment]
That's another good solution to it -- that's one of three options that I think most people would prefer to have.

**Comment by kevingranade** [comment]
I can't think of a good reason to label players with a handedness, or to
choose a particular side to equip weapons. There's already some support for
seperating items by side, but very few things use it because it needlessly
complicates the UI.
As for the other issue you snuk in, it's totally reasonable for encumbrance
on your off hand to interfere with actions performed with your primary
hand, that 3ncumbrance can throw you off balance etc and interfere.

**Comment by Rivet-the-Zombie** [comment]
>Further down the line, arm/leg/hand armor might be separated into individual pieces as well -- nothing as specific as a 'left leather glove', but just a 'leather glove' item that could be worn on either hand.

Gloves don't generally work like that.
