### ISSUE TITLE
Can we have more firearm spawns that already contain a magazine?

### ISSUE THREAD

**Issue by Rivet-the-Zombie** [CleverRaven/Cataclysm-DDA#15443]
I'm really, really loving the new magazine system, but the fact that guns pretty much never come with a magazine sucks, and it has made a lot of them useless. Previously, before magazines were a thing, if you found a gun you could make use of it until your ammo ran dry, but now they're mostly good as bludgeons. We've traded readily functioning weapons for a really neat new function that we rarely get to actually see in action because magazines can be so incredibly hard to come by.

Not everyone stores their gun with a magazine in the well, but I've never known anyone who owns a firearm but doesn't own a single magazine to use in it. Also, guns we find on dead zombies should pretty much always have one in them, since they were apparently being carried and used right up until the person got zombified.

**Comment by mutt3x** [comment]
I support this.
Found a RM scout rifle in the bassement... no magazine. :-1: 
All the guns i had are now without a magazine...  :-1:  :-1:
I like gathering/scavenging stuff but this is a quite detrimental for guns and might i say illogical.
Dont get me wrong i dont want all guns to have magazines but around 90% of time they should.
The problem here is **why** is it missing. What happened that the mag is missing? Scavenger took it (why would he leave the gun)? Is the gun itself broken? 
These are delicate things.

>Also, guns we find on dead zombies should pretty much always have one in them

Only for Force zombies like soldier or cop since its securely strapped on them. The ammo on them can vary mostly from empty to some ammo. They probably used some when they where not zombies and soldiers might have and extra magazine.

Non-force zombies, here and there. I see zombies being clumsy and dont care on what materialistic stuff they have, their pure goal is to seek you and eat your brains. They might as well accidentally droped the whole gun at some point... unless they have somesort of a backpack...
NPCs might have various loot, asuming they take what they find like the player. Traders as well.

I would like to point out that rare guns should always have a magazine depending on the location they are found and thats mostly the bassement, lab or millitary base. Where is the mag gonna go huh?
Common weapons not so much, like the crash site or dead soldiers random spawn...

**Comment by Nymall** [comment]
A fix would be enabling single round chambering for some weapons. For automatic weapons it wouldn't really make sense, but you can still single chamber many rifles without having the required magazine.

**Comment by Rivet-the-Zombie** [comment]
>Only for Force zombies like soldier or cop since its securely strapped on them.

I'm not talking about having a spare magazine alongside the gun when you find it, but rather the gun already having a magazine inserted.

Making it so more guns spawn with a magazine already inside would also make it awesome to discover duplicates of guns you already have, since you'd be able to use the extra magazine in your original gun.

**Comment by mugling** [comment]
@Rivet-the-Zombie

Agreed, I'll look into increasing the spawn frequency at the weekend. #15341 adds a new mapgen format supporting percentage chances to spawn magazines/ammo. Do you have a list of circumstances in mind for when a gun should contain a magazine/ammo?

**Comment by Rivet-the-Zombie** [comment]
They should probably have magazines in 95% of cases that's not a regulated armory type of setting, and the ones that you find on dead stuff should probably have a chance of containing a random amount of ammo when spawned.

**Comment by SeanMirrsen** [comment]
>What happened that the mag is missing? Scavenger took it (why would he leave the gun)?

Having frequently played survivor types who manage to get themselves into a "lots of guns" situation... yes, a scavenger took it. Because he needed the extra magazine, but not so much the gun.

Generally speaking, magazines are much more important to any one person than whole guns, specifically guns he/she already has on their person. So it would make sense that the more common guns could be commonly found sans magazine.

**Comment by kevingranade** [comment]
There have been a number of changes that were aimed at addressing this, @Rivet-the-Zombie, would you consider this closed?  (Not necessarily perfect, just to the point where it's not broken)

**Comment by Rivet-the-Zombie** [comment]
Yeah, I think we've overcome this.
