### ISSUE TITLE
Morale penalty reduction for constant immoral actions

### ISSUE THREAD

**Issue by Murumuru** [CleverRaven/Cataclysm-DDA#15488]
In Cataclysm people are struggling to survive and killing other people is more or less common or doing immoral actions of one or another kind.
Therefore, what about guilt reduction for such actions?
I suggest something like mechanics of current zombie child penalty apply to NPC killing (Innocent Killed penalty), as far as I understand, killing NPC gives penalty directly, unless you have Psychopath trait.
Same for the actions like creating zlave (I am not sure how moral penalty is calculated, but I am also not sure that "how many times player made zlaves" counts)..
I apologize if some of these are implemented already: I checked issues and found nothing, could not check commits - github does not allow search for commit text and some testing I made did not show that it is implemented.

**Comment by Coolthulhu** [comment]
Zlave penalty scales with survival and making zlaves grinds survival.

As for penalty decay: killing innocents wears people down fast. It should never become something you do without consequences. I can see it dropping from "I MURDERED him!" after first kill to "I had to do it, I'm starving/infected" after the fifth, but that would be 50% reduction, not to something negligible like -30 morale (like from being wet or eating raw meat).

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
