### ISSUE TITLE
New Monsters: Rust Eaters and Junk Gluttons (Requires: Group Spawns)

### ISSUE THREAD

**Issue by GlyphGryph** [CleverRaven/Cataclysm-DDA#1550]
http://smf.cataclysmdda.com/index.php?topic=67.0

The Metal Eater is a small batlike creature. Always appear in groups of 3-8. Often appear around wrecked vehicles and in junkyards. They can fly, although not well, and their bite and claws can do a decent amount of damage. Does not aggress against the pllayer unless the player seems weak and injured or accompanied by a Junk Glutton. Will flee from loud noises, like gunshots. Tends to harry and pursue, keeping distance and moving quickly as they stagger through the air. Hard to shoot because of erratic movement behaviour. More likely to flee the fewer there are, and will keep fleeing until off-map. Not slowed by hindering terrain.

The Junk Glutton is larger, weighing over 300 pounds. Essentially the Hulk version of a metal eater, though they are slightly slower than the player. Can destroy light blocking objects like a brute should, but not full walls like a hulk. Can move quickly over hindering terrain like counters and vehicles and windows without being slowed. Will only aggro a player if they get too close an attract it's attention, or make a loud noise that startles it. Always accompanied by a pack of 3-8 metal eaters. If the Junk Glutton is killed, the metal eaters will flee.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
