### ISSUE TITLE
Sweep fire for full automatic guns

### ISSUE THREAD

**Issue by player0981234** [CleverRaven/Cataclysm-DDA#15521]
Add a sweep fire mode for automatic guns

**Comment by Malkeus** [comment]
What's a 'sweep fire'? How would that behave in game?

**Comment by NickGrease** [comment]
I can only imagine [Rambo](https://youtu.be/3pEjfuRygS4?t=16s)

**Comment by Rivet-the-Zombie** [comment]
I think the idea is that you'd be able to point your weapon at one side of a group of enemies and then hold the trigger down as you turn to the other side of the group, spraying the whole line with projectiles as you do so.

**Comment by mugling** [comment]
Burst fire does already have a similar behavior as described above but it does need some improvements a presently it's very ineffective proportional to the amount of ammo used

**Comment by Malkeus** [comment]
Is that a euphemism for suddenly spinning around and shooting your NPC ally in the face because your burst had 10 shots and the zombie brute you were firing upon died after 3? Gotta put those bullets into flesh!

**Comment by kevingranade** [comment]
The way I was envisioning the ui was to set mode to "spray" or similar,
when firing it would prompt for two targets instead of one. While firing,
it would move the aim point from the first point to the second in steady
increments.
Now that rounds keep going beyond their targets, this is all that is
required.

Frankly though, unless you have a TON of ammo this is a terrible idea,
since most of your hits are going to be glancing or regular hits, the
damage per round is going to be extremely low compared to aiming even
briefly.

OTOH it might be worthwhile with some special weapons, such as a
flamethrower.

**Comment by mugling** [comment]
That would actually be fairly feasible now the refactoring of gun firing is complete

**Comment by ituluwituluwzev** [comment]
Closing - the suggested sweep fire mode is not different enough from existing burst fire mode.
