### ISSUE TITLE
[Idea]Butchery item groups

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#15650]
I tried to implement the idea in title. I ran into a problem: item groups are relatively independent of everything else (except their own recursion lists) and the butchery drops require dependency on outside rolls.

Implementing this in item groups would have a bunch of advantages:
- JSONized everything
- No hardcoding when adding new components
- Ability to define alternate butchery drops, drop sets, recursive groups etc.
- Later could be extended to things like deconstruction (loss of components from low skill) without much extra code

The problem is that item groups are currently implemented in a way that makes it hard to get informations about them. They're "one-way". To implement the above, I'd have to either make them "understand" enough about butchery rolls to scale the drops or expose them and have the butchery drop system be responsible for scaling the drops.

My idea was to pass a drop modifier structure with result of butchery roll and have the item group scale the drops based on the roll result and min/max specified in the item group (as a new parameter, similar to how damage and charges are specified).

The butchery drop groups would need the following to be definable:
- Optimum roll value, below which some drops are lost
- Either minimum roll value to get any drops or the amount of drops lost per missing point of the roll
- (optionally) Ability to define more than one roll per drop. For example, to allow survival, first aid and electronics all to contribute towards CBM recovery

Are item groups even the right place to implement this, though?

**Comment by Zireael07** [comment]
Maybe you could have "disassemble groups" - since butchery for items equals (D)isassemble, which would specify the drop/roll stuff and then point to groups?
Something like
disassemble_group: [
  drops: [ 30-blah, 60-bla, 70-foo]
  item_group: [zombie_cop]
]
(just random example and forgive me for not remembering how the value-key pair is done in JSON - I am much more familiar with lua

**Comment by BevapDin** [comment]
You could invoke the item groups multiple times. One time for bad butchering and several times for good butchering. On each invocation, an item of each category (meat, hide, bones, ...) *may* be created (with a certain probability < 100%).

**Comment by Coolthulhu** [comment]
> On each invocation, an item of each category (meat, hide, bones, ...) may be created (with a certain probability < 100%).

But would it be possible to have that probability be dependent on the roll?

**Comment by BevapDin** [comment]
> But would it be possible to have that probability be dependent on the roll?

No. Why would you need that. Make an item group that spawns a single meat item with a probability of 50%. Roll for butchering success (higher roll means more items, right?) Invoke the item group as often as the roll says. If roll is 1, you'll get 1 meat with a p=50%. If roll is 2, you get one meat with p=50%, two meat with p=25% and no meat with p=25%.

Granted, this is not exactly the same as you propose, as it scales differently. It may not fit your requirements at all, but it's an easy to implement idea, only needs a loop (-;

**Comment by kevingranade** [comment]
If you're looking at extensively overhauling butchery and jsonizing it, how about switching to a system where you have a manifest of harvestable parts, and each part entry has a difficulty to harvest properly, and an entry for what happens on failure e.g. some of the meat entries might render "mangled meat" on failure, but some, near the digestive system, would render "tainted meat".  For the repetitive "this animal has a chance of dropping 15 units of meat in 5 lots", the top-level entity could just have a count property too.
```
{ "difficulty" : 15, "success_product : { "type" : "meat", "count" : 5  }, "failure_product" : { "type" : "mangled_meat", "count" : 5 }, "count" : 10 }
```
Then butchery would just run over this list evaluating the difficulty of each entry.

For the first draft the majority of the failure items could be "none", and be backfilled later.

PROS:
  Simple to understand the json.
  Simple code.
  0-sum, it's easy to discuss whether it's the correct amount of meat for a particular type of animal.
  Fine control over the yield from any particular creature.
  Isolates animals from each other, perhaps some have e.g. a hard-to-retrieve hide.
  Doesn't reuse item groups.
CONS:
  No recursive definitions, though I'm sure you could work that in if needed.
  Requires rebalancing since it's a total overhaul
  Doesn't reuse item groups.

**Comment by Shadefang** [comment]
Just a thought, but how difficult/useful would it be to allow the items defined in kevingranade's idea be either an item or an item group? This seems like it would have most of the advantages that Coolthulu is looking for, without requiring as much reworking.

**Comment by kevingranade** [comment]
If you drop the alternate item concept and get creative with interpreting "drop rate" from an item group, you could shoehorn it in, but you shouldn't do that because it means now item groups mean different things depending on which one it is.

**Comment by illi-kun** [comment]
PR #19209 is seems to be a result of this discussion so I guess @Coolthulhu gathered all requred info from this issue.
