### ISSUE TITLE
Melee Combat Overhaul

### ISSUE THREAD

**Issue by GlyphGryph** [CleverRaven/Cataclysm-DDA#1565]
This is essentially what we decided on in chat (me, kevin, and several others weighed in)

Combat will be the result of three disparate factors - Goal, Style, and Patterns.

Goals: (Parens indicate less important) Actions players take
Attack - Move into enemy. Attempt to deal as much damage as possible. Will automatically try to aim for weak points.
Push - Push command. Choose direction or no direction. Handles knocking down and moving enemy characters. Tactical manipulation of enemies.
Cripple - Cripple command. Handles dealing attacks with a primary purpose of weakening the enemy rather than damaging them.
Jump/Dive - Not normally attack, but will impact enemies or objects that get in the way, and influenced by styles like the other actions. Some styles turn this into a full a attack.
Defend - Happens automatically if no other action is taken.
(Grapple)

Style: Switched through style selection menu
Styles can be switched between at will, and influence what the above behaviours actually do. The player will attempt to execute the selected goal with the most effective technique from their currently selected style (or the generic fallback if their style does not cover this goal). For example a "push" to behind the player while using karate might result in a karate throw.

Patterns: Results of player actions that can be manipulated
Actions can influence the actions that follow. Defending (taking no action for a turn) gives a large defense bonus on that turn, but also a small one to the following turn, so alternating attacks and defending results in a defensive style of fighting - at the cost of allowing the enemy more chances to attack and taking more time to take them down. Enemies can critically fumble attacks or otherwise leave openings against defending players, allowing for an opportunistic attack pattern.

Certain actions with certain styles may provide lasting bonuses or penalties, bonuses that synergize well with other actions from other styles (or the same style) or which minimally influence some specific action. The player can discover effective "combos" in this way.
##

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
