### ISSUE TITLE
Implement Negative Trait slots (replacing the trait point limit)

### ISSUE THREAD

**Issue by YeAdventurer** [CleverRaven/Cataclysm-DDA#15676]
Currently the limit on Negative Traits is a point limit. A better method would be having slots. Suddenly the negative traits that were considered to be 'free points' before, like Lactose Intolerance, is an important decision because minor negative traits fill spots that could be filled by major flaws that give you more points. The amount of slots would be configurable in debug, and would default to 2 or 3.

Let players take as many Positive Traits as they want.

**Comment by player0981234** [comment]
multipool points(scenario+profession,traits and stats each has individual points)is added now so it is probably not needed

**Comment by YeAdventurer** [comment]
Multipool has no bearing on the value of this.

**Comment by player0981234** [comment]
traits points are individually calcuated, and most positive traits are not so useful, so it might be enough

**Comment by ejseto** [comment]
*Some* positive traits *are* useful, while not *all* negative traits are truly detrimental. That is the crux of the matter. You take negative traits that don't matter and get good positive traits in return. Maybe you only get 1/4 of a good trait that way, but you take enough such traits and you'll get something good for free. Something needs to be done to make lactose intolerance an actual disability.

**Comment by John-Candlebury** [comment]
Afaik the biggest problem with balancing the negative traits are all those awards one  point minor hindrances.

I think it would be a better solution if only the first two 1 point traits gave you points, so you could still take all of them if you wanted to roleplay stuff.

**Comment by YeAdventurer** [comment]
Negative trait slots are by far the simplest solution.

**Comment by kevingranade** [comment]
I like the idea of only awarding negative points for the first/worst n
negative traits, letting people take more for roleplay.

**Comment by YeAdventurer** [comment]
I like that suggestion kevingranade.

**Comment by player0981234** [comment]
maybe add this as a toggleable option cuz I don't like this idea so much

**Comment by YeAdventurer** [comment]
Could just add an option as to how many slots will give points.

**Comment by mutt3x** [comment]
>Let players take as many Positive Traits as they want.

YES YES next thing infinite ammo pfff. NO
 ...unless you are playing a perfected god-like human lumberjack overlord simply because you refuse to be a lowlife sub-human. Top at everything jumping running stealing dancing, nothing can match IT. To destroy IT, It must be taken deep into Mordor and cast back into the fiery chasm from whence it came... in other cases it does not fit in any aspect of gameplay.

It further makes no sence since you can already configure to have silly amount of trait points. Put 100 and god power is given to you.

I have an idea of a randomized negative traits system but nobody would find that exciting except me + its not adequate for the roleplayers since they dont get what they want...

the roleplayers maaan.

**Comment by YeAdventurer** [comment]
mutt3x, I think you're misunderstanding. It would simply be removing the point limit on taking positive traits, not literally letting you take every positive trait.

**Comment by mutt3x** [comment]
>removing the point limit on taking positive traits

so what part did i get wrong again?
i really dont see any gain of this.

**Comment by YeAdventurer** [comment]
You were comparing it to infinite ammo. But you would still be limited by the amount of points you have, so that comparison doesn't really stick. It just doesn't seem like you understand. The point of having negative trait slots is to increase the value of major flaws and devalue minor flaws.

**Comment by mutt3x** [comment]
I was being satiric about removing limitations. u no fun.
the traits itself are the problem. your mission is pure but you will still have the same problem meaning you would have little or no change. i just dont see this working on its purpose. it makes it easy really.

but hey maybe you prove me wrong.

**Comment by YeAdventurer** [comment]
In the current system, the 1 point minor flaws are a problem. When you go to a slot system, they become less valuable because they are taking up the same amount of space as a major flaw, and you are getting less overall points to spend on your character by taking these paltry downsides.

It is a far simpler, easier, and fairly unique solution than rebuilding the entire flaw list from the ground up.

**Comment by mutt3x** [comment]
yes thats what i understood this whole time.
ahh well we will see.

**Comment by Rasip** [comment]
Seeing as how several of the flaws are either largely neutral or even beneficial rebuilding them from the ground up might not be that bad of an idea. 
I'm looking at you ugly, light weight, addictive personality, trigger happy, truth teller, and thin skin. With heavy sleeper and weak stomach being the beneficial ones.
That's 9 points right there. The system does need work, but slots might not really be an improvement.

**Comment by YeAdventurer** [comment]
Some of those are NPC-related, I personally think those flaws should only available if NPCs are.

**Comment by Rasip** [comment]
Even with NPCs truth teller just means you are going to fail if you try to lie. Are there any opportunities to lie other than telling them you killed the mom/jabberwock? 9 times out of 10 NPCs either open fire as soon as you refuse to let them rob you or offer you a mission and are long gone before you have any chance of getting back. So, ugly doesn't do much either.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
