### ISSUE TITLE
tutorial and defense mode guns not containing magazines

### ISSUE THREAD

**Issue by player0981234** [CleverRaven/Cataclysm-DDA#15697]
basically ruining these for me

**Comment by player0981234** [comment]
why nobody sees my bug report again

**Comment by Night-Pryanik** [comment]
@player0981234 - @mugling added a label to your issue. 
What else actions do you expect? That everyone drop their current work and attend to this problem? Or that everyone comment this like "Oh yeah, that's a real bug indeed"?

**Comment by mugling** [comment]
@player0981234 you were given the correct answer in #15531.

This is a volunteer project with finite resources. Your bug was read, tagged, and will be dealt with when all higher priority bugs (of which there are many) are resolved. You are welcome to contribute a solution or any further comments that might help someone else produce one.

Repeatedly bumping your issues (similar to previous) may result in users blocking you and then indeed we won't see your issues. Note for exactly that reason there isn't a need to reply to this unless you have more comments that expand upon the bug itself.

**Comment by player0981234** [comment]
I dont need reply but it really feels bad to see everyone else's bug fixed and mine not
