### ISSUE TITLE
Purifying water from one vehicle and filling another vehicle does not deplete the dirty water supply.

### ISSUE THREAD

**Issue by horse-f** [CleverRaven/Cataclysm-DDA#15709]
Here is the set up: Two vehicles, one with a dirty water tank, funnel, and a water faucet; the other with a kitchen unit, battery, and on another frame a clean water tank. When i use the kitchen unit to purify water and refill the kitchen vehicle, the dirty water supply in the water vehicle does not deplete. This is on version 0.C-4517.

**Comment by jcd000** [comment]
i can verify this. boiling water is not draining the dirty water tank.. (made sure no other water source nearby).

**Comment by jcd000** [comment]
so, i looked a bit into it and after a bit of searching (i'm pretty rusty) i am lead to believe the problem is here (inventory.cpp, line 550 onwards):

`        if(faupart >= 0 ) {
            item clean_water("water_clean", 0);
            clean_water.charges = veh->fuel_left("water_clean");
            add_item(clean_water);

            item water("water", 0);
            water.charges = veh->fuel_left("water");
            // TODO: Poison
            add_item(water);
        }`

That's because i see that the code checks for fuel_left, and if there is fuel, it adds needed water to the inventory, without erasing it from the fuel tank...
This seems to me like a pretty big ommision and it should certainly have been noticed before, so i think i forgot something... But that's all i can see right now...

**Comment by BevapDin** [comment]
It's probably `map::use_charges`. It does not check for the faucet vehicle part, only for the kitchen part. They used to be one part, but have been split recently. I guess that function has not been updated.

**Comment by jcd000** [comment]
indeed it does exactly that.. since kitchens have the tag 'faucet' though, fix seems straightforward..

**Comment by mugling** [comment]
Lots of recent changes to related code. Is this reproducible in `master`?
