### ISSUE TITLE
Character templates do not seem to save the "Points" choice.

### ISSUE THREAD

**Issue by aeoo** [CleverRaven/Cataclysm-DDA#15748]
So I created a 'Freeform' character (It's a third choice in the new "Points" tab during chargen) and saved it as a template by hitting '!' on the last tab.  Then once I loaded the template in a new game, my character's mode was set to "Multiple Pools" and it was showing 0+0+0=0 which doesn't make any sense anyway, because I've spent a ton of points in 'Freeform.'

**Comment by ejseto** [comment]
Why does it matter how many points were spent when it was created in freeform (which, incidentally, doesn't tell you how many points you spent either) in the first place?

**Comment by aeoo** [comment]
My only point is that if I select "Freeform" and save a template, when I load it for a new game, that character should start with "Freeform" selected as well, as per the template.  It's probably just a cosmetic issue in the UI, but it's a bug nonetheless.

**Comment by BevapDin** [comment]
> It's probably just a cosmetic issue in the UI, but it's a bug nonetheless.

It's probably not because points (or even the type of starting point system) is not stored in the template at all. That's why you need to have (or should have) zero points left when saving a template.

**Comment by aeoo** [comment]
@BevapDin makes sense.  But I was right about this issue being cosmetic then, looks like.  The template mostly loads fine, it's just that I get an expected visual result of my prior "Points" selection being lost.  IMO, there should at least be a warning at the time of saving the template that this is something that's going to happen, and not to be surprised by it.

**Comment by ejseto** [comment]
There *is* a warning. If you try to save a template with points remaining, it'll tell you those points will be lost and ask if you want to proceed. Templates are finished initial character builds. There is no need to save point values because they are finished. Character creation isn't long enough that you should need to be able to save progress part of the way through.

**Comment by aeoo** [comment]
>If you try to save a template with points remaining, it'll tell you those points will be lost and ask if you want to proceed. 

I don't think I communicated myself well.  What I meant to say is that there should be a warning that once you save a proper template, your "Points" mode selection will not also be saved, and not to be surprised by that.

>There is no need to save point values because they are finished.

It looks confusing.  I create a template for a "Freeform" character.  Then I load it, and it has "Multiple Pools" selected instead of "Freeform."  That's confusing.  When I load a template I expect everything in the same state as when I saved the template, minus the character name.

**Comment by NickGrease** [comment]
I think the issue here, if you can call it an issue, is that you're not actually saving a 'template' as the name might suggest, but an actual player character 'object'. I'm going out on a limb here, but I would assume programming best practices means; not including in an object that which the object doesn't need to know. In this case, (looking at it from the games point of view), once a character is created, it doesn't need to know how many points are left or what type of pool was used.

Looking at the code it would be trivial to add the missing info, but it would pollute the character object, leaving the second best option; which is to write an *actual* template system, which is not hard, but it is substantially more code than just adding the word "Freeform" somewhere and reading it back later.

All that said, your points/concerns are valid - a template should be a template.

**Comment by aeoo** [comment]
@NickGrease I agree with all your points.  After hearing the explanations I don't have any personal concerns about the game not working.  I realize everything will work fine.  So it's an issue of how the game communicates to the player.  I don't think a lot players know the difference between a template and a player character object.

So the easiest way to handle it, imo, is to simply inform the player that the visual result in "Points" tab is harmless and doesn't affect the main game.

Personally I am not invested in this issue after hearing the explanations (and even when I opened it I didn't think it was a huge deal, but I *did* think it was an easy fix too).  So I personally won't care if someone just closes it as "wontfix."

**Comment by Coolthulhu** [comment]
It's not really wontfix, just low priority.
