### ISSUE TITLE
Item variants

### ISSUE THREAD

**Issue by mugling** [CleverRaven/Cataclysm-DDA#15781]
Continuing from #15765 I'm working on a system for item variants to reduce duplication in the JSON. I'd prefer duplicates to be discrete itypes in their own right (and therefore compatible with `item_groups` etc) and be applicable to all types `GUN`, `AMMO`, `GENERIC` etc. The simplest method I can think of has the following JSON syntax:

```
{
  "id": "223",
  "type": "AMMO",
  "name": ".223 Remington",
  ...

   "variants": [
    [ "reloaded_223", [ "RECYCLED" ] ]
  ]
}
```

Where `reloaded_223` is the `id` for the variant and `RECYCLED` is a flag that is attached to a clone of the the base `223` itype.

Flags then have the responsibility of adjusting the properties, eg the name becomes ".223 Remington (reloaded)" and the stats are shifted appropriately?

**Comment by BevapDin** [comment]
I see two problems with the proposed format (the idea itself is fine):

- It's very restrictive, one can create derived items with additional flags and that's it.

- It must be used inside the base item definition, mods can not use it on an item from the core data.

First point can be solved by allowing a complete item definition instead of just flags. Data that is not specified in the new definition is copied from the parent. You may need some special syntax to allow adding (instead of overriding) sets and for removing from them.

Second point can be solved by a separate definition, for example this:
```JSON
{
    "type": "...", "id": "foo", ...
},
{
    "type": "...", "id": "makeshift_foo", "copy-from": "foo", ...
}
```
Mods could use that to simply add hand loaded bullets. Or to add a bulkier, but otherwise identical makeshift item.

**Comment by mugling** [comment]
> Second point can be solved by a separate definition

This could work. I have prototype that implements an (explicit) copy constructor for `itype`
