### ISSUE TITLE
Small critters in groups ripping through vehicle integrity

### ISSUE THREAD

**Issue by pisskop** [CleverRaven/Cataclysm-DDA#15805]
Small animals in packs, like fungal sprouts, several grouped spore, or customed floating heads;

will destroy vehicles at an alarming rate, despite claims that they are 'wispy', made of a soft material, or otherwise not a real threat to the player/vehicle.

**Comment by Coolthulhu** [comment]
This is because of our vehicle HP/armor thing.

Currently vehicle parts can't have armor, but the do have "threshold" which is based on current hp. Physical damage below threshold is ignored, but is not reduced otherwise.

Maybe we should switch to hp+armor model and then greatly nerf HPs. This would prevent hulks having problems with car wrecks and the like.

**Comment by Mshock777** [comment]
What kind of armor we are talking about: Damage Resistance or Damage Threshold?

**Comment by Leland** [comment]
Looks like discussion has stalled on this topic. Closing. If there's still interest, let me know and I can reopen.
