### ISSUE TITLE
Multilevel houses (and shops/parks)

### ISSUE THREAD

**Issue by Mshock777** [CleverRaven/Cataclysm-DDA#15914]
I wanted to add custom basement for one of the houses but realized that it can only be done using `overmap_specials`, and they are designed for unique structures (that are mostly outside towns).
It would be nice to have a tool to create multilevel houses/shops and add them to `regional_map_settings` (or just straight up assign `om_terrain` to them).

Also I looked and didn't find any documentation on `overmap_specials`.

p.s. Maybe this way we can also add `house_base` to json houses and resolve #10612.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.

**Comment by Leland** [comment]
I've closed #10612 in favor of this, but definitely check out the discussion over there as well.

**Comment by Leland** [comment]
I've closed #13639 in favor of this, but @vache's issue description from it is relevant enough to just copy in it's entirety here:

>Right now, houses with basements are implemented by spawning house_base, which causes any basement spawn underneath.  Also right now, z level transitions are applied by searching for stairs at the lower level and spawning the player there.  When +Z levels get implemented, these stairs need to line up, which means that pre-defined mapgens need some way to associate with their counterparts on different z levels, and randomly generated mapgens need to access the layout on different levels to know where to place stairs.
>
> JSON Changes:
> - Add ID field to mapgen, along with an up_mapgen and down_mapgen if necessary, to associate > with what to spawn on the +1 and -1 z levels.
>
> Mapgen.cpp Changes:
> - Track the ID of a mapgen spawned in a given location
> - Use the mapgen ID of adjacent locations along with oter info to decide how to generate a given area
> - If the mapgen ID indicates it is randomly generated, access the up/down levels to determine stair locations.  This may be doable with the transition from "reality bubble" to "reality > column".
>
> Overmap.cpp Changes:
> - This is probably where the mapgen ID needs to be tracked.
>
> Generation order is important for a system like this to work though.  Starting at z=0 and then moving up/down as necessary would work for the majority of mapgen, but in a situation where you have a randomly generated house with a json defined basement, the basement would need to be generated first and the house would need to generate last to line the stairs up.  It could be enforced that if the z=0 mapgen is randomly generated, then so are the rest, but I've only been considering house generation, not the implications it could have on labs or mines.
