### ISSUE TITLE
'Multiple pools' Points choice is difficult to understand

### ISSUE THREAD

**Issue by Shoes01** [CleverRaven/Cataclysm-DDA#15918]
First issue: the points aren't in the same order as the tabs. Stats-Traits-Skills in the equation, but Traits-Stats-Skills in the tabs.

Suggested solution: Reorganize the tabs. Given the pyramid-esque nature of how stat points trickle down, the tabs should be in a Stats>Traits>Skills order.

Second issue: I've had to read that description a few times, and I still don't think I understand it. How do I choose which pool the points come from? At first I was under the impression that, as long as the total was 0, I was in the clear. That's wrong. Now I assume the points have to be positive... but if that's the case, then I "can't" put stat points into traits unless I leave myself positive stat points and negative trait points. The UI is unclear with what I can and can't do, and I can't suggest a fix because I don't exactly know how the system works at the moment.

Suggested solution: Add a sentence after the equation describing how many points you have left. In the regular 2+2+2 scenario, the Stats tab would say "You have 2 points left to spend.", the Traits tab would read "You have 4 points left to spend." and the Skills tab would read "You have 6 points left to spend". The sentence (and equation) could also turn red when you have an illegal assignment of points.

Looking at the "console size" for the UI, there's not a lot of space left! A secondary solution, which isn't as good as the first, would be to highlight the points in the equation that are able to be used on each tab. The stats tab would only have the first number highlighted, but the Traits tab would have the first and second numbers highlighted.

Another suggestion would be to rename the points. Having "Stat points" be usable in more than just "Stats" is inherently misleading. Perhaps have "Global points", "Character points", "Ability points", or things of the sort.

**Comment by Labtop-215** [comment]
It's supposed to be Stats-Traits-Skills&Professions.

You only get 2 points to put into stats.  You can't transfer them towards skills, but if you take worse stats then average, you can transfer the stat points into traits.  You get 2 bonus points for traits, which can only be transferred down to skills, and you get a pool for skills which can't be transfered anywhere else.  The total at the end tells you weather you have any spare points or not, or if you have gone over your overall allotted point limit.

It is strange that they moved stat points further down in the character creation menu though.

Also, bonus points from challenges go towards skills only.

**Comment by Shoes01** [comment]
How does the transfer happen? There did not seem to be an indication on the UI.

**Comment by Labtop-215** [comment]
2 (stats) -> 2 (traits) -> 2 (skills and professions)
Having your character set up like this:
(0) + (2) + (-2) = 0 is a vaild character under multipool.
as is this
(2) + (-2) + (0) = 0
But
(-2) + (2) + (0) = 0 is not valid because stats costs cannot be substituted.

Basically the system is designed based on this discussion here:
https://github.com/CleverRaven/Cataclysm-DDA/issues/14895

**Comment by SeanMirrsen** [comment]
Why can't stat point be put towards skills, though?

**Comment by Shoes01** [comment]
@SeanMirrsen I imagine the #14895 would talk about that. Has to do with balance.

@Labtop-215 I think I understand now. Thought of as a pyramid, Stat points are at the top, Trait points at the middle and Skill points at the bottom. Points can be used in a downwards fashion. The description pretty much reads "You can put stat points where you like", which for some reason I thought it meant I could have negative stat points. 

Given the difficult to follow description (I can't be the only one!), I would recommend having a sentence next to the equation. For example, in the standard 2+2+2 scenario, in the Stats tab you would have a sentence reading "You have 2 points to spend". In the Traits tab, it would read "You have 4 points to spend", because you can put stat points there. Skills tab would read "You have 6 points to spend". I think this would have helped me a lot! I will add this suggestion to the OP.

**Comment by SeanMirrsen** [comment]
>@SeanMirrsen I imagine the #14895 would talk about that. Has to do with balance.

That poster goes on and on about how skills are so rarely chosen because stats and traits are so much more valuable late-game, yet now, somehow even if you *want* to take extra skill points by dumping stats, you can't? I sense a miscommunication of intent somewhere. The whole thing would be much simpler as down-linked pool, you get points to spend at each step, plus however many points you did not spend in all previous steps. Simple and straightforward.

Just to clarify that there is no misunderstanding - I mean a situation when you have, i.e. 2 points to spend on stats, 2 on traits, and 2 on skills - and you reduce your stats to get 2 extra points, take 2 points worth of negative traits, and put the whole 10 points into skills.

**Comment by Shoes01** [comment]
Funny enough, that is how I understood it! If it's not like that, that's odd. I suppose my UI solution is still a good one, despite describing a slightly different system ;p

**Comment by Shoes01** [comment]
I will close this as my PR went through and fixes the issues I had.
