### ISSUE TITLE
Ak-47 removed

### ISSUE THREAD

**Issue by player0981234** [CleverRaven/Cataclysm-DDA#15941]
i looked in the debug menu and couldn't find the Ak-47
version 12391 gaca2bd9

**Comment by mugling** [comment]
Was renamed to `AKM` a while back

**Comment by player0981234** [comment]
its ok but i prefer the original and world famous ak47

**Comment by mugling** [comment]
I was never quite sure what the advantage of the original name change was as it just leads to confusion such as this

**Comment by player0981234** [comment]
keep that akm and make a new ak-47

**Comment by illi-kun** [comment]
It was changed in #14078 intentionally. Current "issue report" doesn't contain anything new comparing to discussion in the mentioned PR.

@player0981234 I think some mods from the forum may contain AK-47, so you need to look in this direction.

**Comment by Mshock777** [comment]
Maybe we should swap Icecoon's weapon pack for Artyom's Gun Emporium?

**Comment by kevingranade** [comment]
There's no swapping, if we have one and not the other, it's because someone PRed one and not the other.
Anyway, "I prefer the original name" isn't a valid reason to call it the wrong thing in the game, so we aren't changing it in the main game.

If you want to rename it locally though, you can open data/json/items/gun/762.json and change the name and/or description to whatever you like, you could also make a tiny mod to make this one change.

**Comment by Rivet-the-Zombie** [comment]
>keep that akm and make a new ak-47 i like the original ak more than any other gun

An AKM *is* an AK-47 in the same way that a M16A2 is a M16; it's a slightly improved version, but it's still the same firearm.

**Comment by kevingranade** [comment]
Also, the original point is that an actual AK-47 would be so rare that it
wouldn't be reasonable to spawn them at random, so a common second item
definition would also be pointless.
