### ISSUE TITLE
Move shenanigans into an easter egg mod

### ISSUE THREAD

**Issue by lucianposton** [CleverRaven/Cataclysm-DDA#15991]
Based on the conversation from https://github.com/CleverRaven/Cataclysm-DDA/issues/15981, move the out-of-character shenanigans into an easter egg mod (or, for example, a no-shenanigans mod so they are included by default). This includes the pop culture, etc references that don't match the Cataclysm setting.

<details>
<summary>Examples of the ones I've seen so far are (possible spoilers):</summary>
- jacqueshammer
- granade
- Shia LaBeouf
</details>

There are others, I expect, but I don't want to search them out for sake of spoiling the surprise for me.

**Comment by Mshock777** [comment]
Isn't Shia LaBeouf already in some mod that removes it?

**Comment by Karbine** [comment]
He's excluded by the No Joke Monsters mod. That mod itself could potentially be reworked into a "No Jokes" mod that includes the above in addition to what it already blacklists.

**Comment by Coolthulhu** [comment]
* Vibrator
* Cat ears (the item, not the mutation)
* Cat tail
* Golden and diamond "grill"
* Fursuits
* Arguably everything clown-related

**Comment by nanovad** [comment]
@Karbine I think a separate mod for disabling items would be appropriate. A lot of people would probably want to play with silly items off, but things like Mi-Gos on.

**Comment by Coolthulhu** [comment]
Mi-Gos aren't a joke. Joke monsters are Shia, Thriller, zombie dancers and smoky bears.

**Comment by kevingranade** [comment]
None of the items coolthulu list belong in such a mod, they are all real
things, unlike the granade or a jaqueshammer.
The monsters OTOH are.

The criteria for inclusion should be both "doesn't exist irl" *and* "added
as a joke", in other words real things added because it's funny are fine,
it's just things whose very existence is a joke that would go in this mod.

The other issue is default behavior, personally I think it's reasonable to
default this content to off and have people opt in by enabling it.

Finally the name, I propose "crazy cataclysm".

**Comment by Headjack** [comment]
Those things should just be hyper-rare, is what, excepting vibrators which exist and are indistinct in description from back massagers.

**Comment by lucianposton** [comment]
Fixed by #16180
