### ISSUE TITLE
Healing is unrealistic, weak until stacked, scales too much

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#16017]
Disassembling a pillow grants cotton balls. Cotton balls heal hp. You can scramble half-dead to a bedroom, cut up pillows, stuff your wounds with (not disinfected) cotton balls and regain all the hp you just lost to fire/acid/getting impaled/poison/smoke.

With bandages, you need to spend hard alcohol/disinfectant/saline solution, which can't be easily crafted early on, but cotton balls are just pulled out of common pillows.

While nerfing cotton balls would help and is a good idea on its own (they are currently as powerful as disinfected bandages), they would need to be nerfed to rag level for it to really matter. Now that healing is an iuse_agent, healing can be balanced freely and quickly.

In addition, healing could apply "recently healed" effect to the body part that got healed. This effect would reduce hp healing to the body part until waited out (could wear off faster during sleep and if mutated to heal fast). The reduction would have to account for scaling due to skill, but not be pure percentage because it should:
- Not make healing too order-dependent - using cotton balls shouldn't make it impossible to "correct" it with a first aid kit if cotton balls aren't enough
- Make cotton balls totally useless for hp healing after n-th application within the same hour to the same part. There should be a relatively hard limit of healing with low quality items
- Hit extra HP gains due to high skill more than base healing to reward using better items over stacked cotton balls

This one would be relatively easy, provided the formula for healing reduction was good.

Alternatively, changing the entire HP healing mechanic into a HP regeneration boost effect:
- Applying a healing item grants "this body part is regenerating" effect
- Intensity affects healing rate
- No stacking. New effect overrides the old one.
- Trying to heal a body part that is only weakly wounded caps the duration to prevent stupid things like bandaging a healthy part in anticipation of damage

This would require a rebalance of all healing items, though.

Both solutions should benefit regenerating mutants, who are currently rather weak - fast healing will heal (to full hp) even tough and unhealthy characters. They should not benefit nanobots bionic, because it is way too good (full hp in 0 time with very renewable resources) and by "benefit" I also mean "make it shine by nerfing other options while not giving this one a hard limit".

**Comment by Labtop-215** [comment]
How about have cotton balls not heal hit points, and instead just be useful for stopping bleeding?  Also, for other healing items, things like bandages and first aid kits are really only supposed to be used in an emergency, after you have sustained major injuries.

I know that this has the potential to slow the game down a bit, but maybe common items that restore lost hit points on ones body shouldn't bring them above 33%?  But perhaps they should help give back lost hit points if you sleep or rest instead since you have covered you wounds to help prevent parasites and bacteria from getting in.

I mean, really.  How much sense does it make to bandage oneself up and then head right back into combat as though nothing had happened previously?  Unless you are using like high tech items like the medical ampoule or the nanobots.

**Comment by Zireael07** [comment]
Cotton balls shouldn't heal hp (or a really minor amount, like, 1 point).

**Comment by lucianposton** [comment]
If you pulled cotton from a pillow (not disinfected) and dressed a wound with it, all that would happen is the cotton would become stuck in the wound when the exudate dried. If anything, making infection more likely.

**Comment by Night-Pryanik** [comment]
I like the idea to change all healing into regenerating boost. 
Consider all healing items doing their direct job (bandages - stop bleeding, disinfectant - prevent spreading of infection) and not "repairing the damage done to body part". Make the healing done only by one's body.

**Comment by illi-kun** [comment]
Just for the record, this topic is similar to this one: #4960.

**Comment by illi-kun** [comment]
... and another one topic with the similar content: #7029.

**Comment by Soyweiser** [comment]
So, was the result of this that cotton balls don't work as healing anymore? http://prntscr.com/bnl5n7

**Comment by Coolthulhu** [comment]
> Bit tedious again

As opposed to trivial. With cotton ball healing, HP damage meant very little and involved pillow scavenging tedium.

> This removes all the early game healing (apart from

"All except"
Also, disinfectant and hydrogen peroxide.
Bandages aren't that rare.

I'm open to suggestions on how to handle it without reworking the system.
Dropping bandages down to autolearn at lvl 0 would be one option. They do take duct tape and concentrated alcohol, which makes them a bit too rare for mass healing, though this also implies they're not cheap enough to trivialize HP system like cotton balls did.

Something cheap like improvised bandages from boiled rags would be rather tedious.

Slow passive regeneration when awake would make sense, though it would need to be slow enough not to (again) make the HP system meaningless.

**Comment by Soyweiser** [comment]
Yeah, but but the cotton balls healed a lot iirc at least 4 hp on the head, and a guaranteed 1 on the body etc. Perhaps just dropping it to a chance of healing a hp, instead of just doing guaranteed healing. (Which is however how I assumed at first they always worked in fact. They had a stronger effect on healing than medical tape. And the same power as bandages). Even now medical tape (stops bleeding 0.5) is worse than cotton (stops bleeding 0.9).

Disinfectant and hydrogen peroxide also aren't that common as items.

And yeah, improvised bandages would also be pretty tedious. I think that is now neoscavenger does it. And well, needing to replace your bandages every few hours is not really that much fun.

**Comment by Coolthulhu** [comment]
> Perhaps just dropping it to a chance of healing a hp, instead of just doing guaranteed healing.

That sounds really tedious. Having to go through a mass of cotton balls to heal, but still being able to do it (meaning tedious optimal gameplay).

**Comment by mugling** [comment]
> meaning tedious optimal gameplay

We should avoid rewarding grinding at all costs.

**Comment by Soyweiser** [comment]
Well, seems better to me than, finding you have no healing, having to wait till you get tired. Finding new food, drink. Sleeping. Healing a bit, and going back into the game.

The using the same thing over and over again is tedious. But that grinding part is sadly part of the game. Same with attacking a Z over and over until it drops. (iirc that is why various other roguelikes implement the 'repeat this action x times' function. Like we can batch craft.

**Comment by Coolthulhu** [comment]
> The using the same thing over and over again is tedious. But that grinding part is sadly part of the game.

For this specific case, it doesn't need to be. Trivializing the HP system by grinding pillows would be a bad idea even if using the cotton balls wasn't tedious.
I see no reason to bring that back.

If we are to replace cotton ball bullshit with something, it need to make more sense. For example, consume some resources, a ton of time (character time, not player time) or cause penalties for a while (a day or so, stacking if reapplied).

**Comment by Soyweiser** [comment]
Yeah, but right now it just removes an option totally. And im assuming the 0.D release is near. (as there is an milestone now. I don't think it would be smart to release a new official version with less healing in the game.

I'm also not totally sure about the need for harder healing. I have had enough trouble even finding enough cotton balls in the early game. (with first aid skill, low armor, low dodge etc). And in the late game healing that is slow (takes 300 turns) will not save you. At least in most cases I was in real danger, I didn't have the time to use 3 turns to heal. (in those cases I would either remove the threat at that moment. Or the threat stunlocks/painlocks me and I die).

Without healing items it just becomes a 'I have to wait/scavenge in scrubs for food/till healed up and I can continue' part of the game for me. But then again, I think most systems you are thinking off will be those kinds of systems. I think that would not be much fun, even if it is realistic.

**Comment by Coolthulhu** [comment]
> I don't think it would be smart to release a new official version with less healing in the game.

How so? Why should stable version have lower standards than experimentals regarding healing?

> I'm also not totally sure about the need for harder healing.

We could buff other items to compensate. Bandages are rather weak at low levels, they could use a buff.

> I have had enough trouble even finding enough cotton balls in the early game.

I played at 3.0 zombie spawns and 1.0 item spawns and had plenty.

> And in the late game healing that is slow (takes 300 turns) will not save you.

HP damage doesn't mean much in the middle of combat - it's the pain that kills you by draining all the stats to 0. I'm actually considering nerfing pain scaling because it makes HP so meaningless.
The problem with healing is that once the combat ends, you go back to full HP in minutes and are left only with pain.

> Without healing items it just becomes a 'I have to wait/scavenge in scrubs for food/till healed up and I can continue' part of the game for me.

As opposed to "regen to full health in no time using tedious to gather but cheap resources".

I'm open to suggestions.

**Comment by Soyweiser** [comment]
>    I don't think it would be smart to release a new official version with less healing in the game.

> How so? Why should stable version have lower standards than experimentals regarding healing?

I would say having less healing in the game is lower quality. I'm going to assume you mean, shitty healing mechanic is lower quality. (My concern is more with people giving up on cdda due to it becoming to hard to play).

> We could buff other items to compensate. Bandages are rather weak at low levels, they could use a buff.

That would be a good solution. The whole first aid skill tree feels underwhelming anyway. But you do need it to raise the % of cbm install success. (mostly I raise it by just finding all the various skillbooks and using that).

> Pain
Yeah, I agree on the pain scaling btw, it makes HP mostly meaningless. (in most cases you are at max pain before you start to die (or something punches through your armor in one turn)).

> I played at 3.0 zombie spawns and 1.0 item spawns and had plenty.
I play at 2.5 zombie spawns and 0.8 item spawns and don't have enough. (until I come to the midgame (which I cannot clearly define, but I would say, having most basic tools, a defensive base, stuff to boil water, create food and some food supplies ready), but by then you have enough of most stuff).
I guess it also depends a lot on playstyle and starting location.

> As opposed to "regen to full health in no time using tedious to gather but cheap resources".
I don't find disassembling pillows / picking up bags of cotton that tedious myself. Bit the same as repairing clothing with rags/thread. Not being able to do it would be more annoying to me. But that is me apparently.

> I'm open to suggestions.
I don't have a good replacement yet. I did find out that cotton + alcohol is apparantly a good way to clean up wounds a bit irl. So making an improvised bandage craftable that uses alcohol and cotton could be a good solution. Perhaps giving it a -1 health penalty due to contaminants in most alcohols.
Right now normal bandages: http://cdda-trunk.estilofusion.com/bandages/craft require 'clean' alcohol. You could make the improvised bandages take 'dirty' alcohol. Like vodka, moonshine etc (*). We could use the strong mixed alcohol for that.

This also gives a possible progression for first aid, more usage for alcohol. And something else you can put on survivors/npcs/LMOE shelters etc.
Skill level 0: cotton + strong alcohol -> improvised bandages.
Skill level 1: Normal bandages.
Skill level 3: First aid kits.

Right now it is not possible to easily craft splints as well as these are first aid level 1. Creating a level 0 craftable at least makes it possible to heal your broken legs/arms without finding a first aid book.

And bit offtopic. But is bleeding broken? I can only recall bleeding after starting the heli crash start. Not from monster attacks.

*: It was something alcohol was used for irl when a country (can't recall which one, probably Argentina, and cannot find the story which told it sorry) collapsed. Being able to build a still, and create your own alcohol was a good way to make money. (as I mentioned on the forums iirc).

**Comment by Coolthulhu** [comment]
> You could make the improvised bandages take 'dirty' alcohol. Like vodka, moonshine etc (*). We could use the strong mixed alcohol for that.

This was the case for a while but apparently it isn't how it works IRL (higher alcohol proof is required for disinfection) so it was removed. Not sure about gameplay implications, though it made liquor store raids much less useful.
I'm not opposed to that, though other devs may disagree here since they care about realism more than I do.

> But is bleeding broken? I can only recall bleeding after starting the heli crash start. Not from monster attacks.

It requires special attacks (impale) and cutting damage. Cutting damage generally gets blocked by armors since there are very few monsters with lots of cutting damage and low bashing damage.

**Comment by kevingranade** [comment]
Short term, I'm very in favor of making all healing items act over time as suggested in #7029.  This is a nearly trivial change that moves the system a significant distance toward where it should be.

The general outline of where I think it should be eventually (not for 0.D) is:
- Get hurt:
  - Take some pain penalties
    - Immediate accumulating penalty that makes combat more diffficult.
  - Maybe some ongoing damage, like bleeding
    - Short-term risk of death.
  - Chance of infection on a relatively long timescale.
    - Long term risk of debilitation if wounds aren't treated properly.
  - Makes you more vulnerable to future injuries.
    - Mechanism for repeated minor damage to become life-threatening.
- In combat mitigation, such as a high-powered painkiller.
  - Removes pain in short term to enable escape or elimination of threats.
- Once out of combat, use some resources to treat the wound (bandages, suturing, splinting):
  - Reduces pain penalties.
  - Removes ongoing damage.
  - Reduces or removes chance of infection.
    - Simple bandaging would reduce chance, full cleaning and bandaging would remove it.
  - Does NOT reduce vulnerability to injury.
- Over time, the wound either heals or becomes infected.
  - Healing either eliminates or downgrades a wound.
  - Infection increases wound severity.
    - More pain, more vulnerability.
    - Slows healing.
    - Carries a risk of systemic infection.

**Comment by jzambo** [comment]
I have POC for some of those points on top of existing master. Which of thouse could be proposed in PR? I will make votable comment for each.

**Comment by jzambo** [comment]
Penalty: Focus drops linearly with added perceivable pain.

**Comment by jzambo** [comment]
Penalty: Negative morale based on percieved pain (player is "too sad" to craft bandages unless he takes enough painkillers plus maybe sits comfortably somewhere while listening to music)

**Comment by jzambo** [comment]
* Maybe some ongoing damage, like bleeding:
  * Untreated bleeding stays for much longer, less often lose HP to compensate
  * Bleeding has multiple intensity levels depending on damage
  * Piercing and cutting damage is more dangerous because of intense bleeding

**Comment by jzambo** [comment]
* Reduces or removes chance of infection:
    * Applying first aid adds an effect that reduces bleeding and infection chance but stat penalties remain

**Comment by jzambo** [comment]
Natural healing is done per body part and it takes longer to heal badly damaged body part. Player no longer can simply sleep off after taking 80% damage.

**Comment by Coolthulhu** [comment]
* Focus already drops with pain
* Pain penalty to morale would just prevent crafting, leading to situations where player is too sad to boil water because he got beat up a bit
* Bleeding could work, but it would take a fair bit of work to design it to work
* Penalizing healing speed on high damage would bring back that heavy armor playstyle I managed to push back a bit. If anything, I'd rather see healing speed scale positively with missing hp, for more risk vs. reward (stay and heal fully or go fight bruised) instead of enforcing being fully healed all the time.

**Comment by nexusmrsep** [comment]
Is this still valid after #23757?

**Comment by kevingranade** [comment]
No, #23757 implements one of the alternatives.
