### ISSUE TITLE
bring back acid rain

### ISSUE THREAD

**Issue by player0981234** [CleverRaven/Cataclysm-DDA#16011]
in the balance section of the 0.b changelog :`Removed acid rain until it can be made into a local event.`now weathers are local we can bring them back the area of efect should be small and it will damage everything including plants monsters stuctures and vehicles add this as a toggleable option some people dont want to see their deathmoblie destroyed because of an acid rain

**Comment by Labtop-215** [comment]
I doubt it would happen now, because of the reason that acid was nerfed.  Basically, if acid destroys items, it has to severely damage the player as well, instead of just seriously hurting them.

Acid destroying items, and acid rain was awesome while it was in though.  I remember having some epic showdowns while trying to get back to my shelter just in time before my everything was melted off.

Lastly, according to the lore anyway, we would need way more dead tree's in the forest instead of living ones.  Since there was supposedly one major acid rain that killed off most people.

**Comment by joneskun** [comment]
Uhm.... yeah. A good, even great, roguelike mechanic IMO. Probably not a good fit with the farmville vibe here. Also, I thought the lore was a late 80s BttF thing. Suitcase cellphones, luggable PCs, mechanical ignition systems on vehicles and so on. Except for the secret research facilities of course.

**Comment by Labtop-215** [comment]
Here is the official cannon:
http://smf.cataclysmdda.com/index.php?topic=4160.04

Also, the game really isn't supposed to be like farmville.  You can create liquid fertilizer, and have crops ready to harvest within a day or two if you are desperate for fully grown crops, which may or may not be broken.

Look, if you really don't like the mechanic, give an actual reason why and then articulated it well.  You'll find that is actually more effective than "Uhm...  yea.  Riiight."

**Comment by Headjack** [comment]
Bring back lightning, burn everything down again. I still don't feel safe unless I'm underground...

If returned, I agree with causing pain and minor damage, and damage to loose items, but assuming it can happen anywhere (rather than just certain zones) it's probably weird to have it damage things too badly, or else why isn't it like that already, right? Lab's on the right track there, I think.

**Comment by Labtop-215** [comment]
> it's probably weird to have it damage things too badly, or else why isn't it like that already, right?

Because secretly, every character you play in the game is a Solipsist, and they are all justified.

This is especially true if you accidentally cause a forest fire.  If you leave fast enough while it is burning, and come back later when there is a thunder or lightning storm, the fire will still be there, in roughly the same state it was previously, except now instead of spreading, the fire is being put out by torrential rain.

Normally, if you cause a forest fire, most if not all of the forest will have been burnt down and destroyed.

**Comment by Coolthulhu** [comment]
Acid rain is not ready to be brought back:
* Critters can't handle it
* NPCs can't handle it
* Reality bubble would restrict it, making areas near player age much faster than all others

There is a lot of work that must be done before acid rain is enabled back in the mainline game and it doesn't look like anyone started working on any of that.
