### ISSUE TITLE
Codeine, heroin, tramadol don't treat cough

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#16037]
Contrary to codeine's own description.

**Comment by mugling** [comment]
Tramadol shouldn't. Heroin definitely should.

**Comment by Night-Pryanik** [comment]
Tramadol should. There are lots of info that it, as opiod, can suppress cough reflex.

**Comment by mugling** [comment]
Compared to diamorphine and codeine the effect is minimal at any reasonable dose

**Comment by Night-Pryanik** [comment]
Well, ok, forget about tramadol.

**Comment by kevingranade** [comment]
Crap, missed this one. Here's the thing, the drugs we have in game are
parodies of the real things, and we shouldn't be applying real world
effects to them  (especially buffs, they're already super OP) unless we
also commit to making them realistic depictions in all ways, which is
problematic because they are rendered almost useless then.

Example, do opiates also cause nausea? That's at least as significant an
effect as cough suppression, why are we cherry picking effects?
