### ISSUE TITLE
Killing NPCs that are guaranteed to become hostile gives -100 Killed Innocent penalty unless they are already red

### ISSUE THREAD

**Issue by EditorRUS** [CleverRaven/Cataclysm-DDA#16041]
Have some faction being hostile to you and find an NPC from that faction and kill them before they become hostile.
This is really annoying considering most NPCs have ranged weapons and turning them to red is asking for trouble. On the other hand it's strange they are not hostile already.
http://i.imgur.com/wZmysys.png

**Comment by Labtop-215** [comment]
Yea, in the past an NPC was robbing me, so I pretended to comply, then I picked up my shotgun and then shot them.  Then I got a penalty for it.  = (  This was quite a while ago though, so it may have changed already.

**Comment by kevingranade** [comment]
It shouldn't be that hard to put them in a state that means "overtly hostile but not attacking yet".

**Comment by Labtop-215** [comment]
Not to extend this further, but since I've been playing with NPC's, I've also found that if they turn to flee, they are basically stuck in a perpetual state of running away, and they don't defend themselves, even if they have a gun that they could kill you with in one hit, and you are beating them with a rock.  They are still considered hostile, and you get no penalty for killing them.

**Comment by Coolthulhu** [comment]
> overtly hostile but not attacking yet
