### ISSUE TITLE
[Spoiler] Canon Check:  High Energy Dimensional Transpositions and Gravitational Field Interactions

### ISSUE THREAD

**Issue by acidia** [CleverRaven/Cataclysm-DDA#1606]
High Energy Dimensional Transpositions and Gravitational Field Interactions

The discovery of high energy dimensional transposition has revolutionized modern scientific thought unlike any discovery since the development of atomic theory.  We have unintentionally encountered flora and fauna from worlds completely unbeknownst to mankind and in doing so we have unleashed the greatest ecological catastrophe the planet has seen since the extinction of the dinosaurs millions of years ago.  It is only by understanding how these 'portals' work that we will be able to salvage what remains of our former biosphere and learn how to adapt to the inevitable bi-dimensional ecosystem. 

The intricacies of controlled directional transposition were among the first explored in numerous experiments.  Extremely precise equipment was required to even produce a modest degree of success, limiting the number of researchers that could be dedicated to the task.  It was during these experiments that the dangers of 'teleportation sickness' were first addressed.  The density of matter that the subject teleported into determined the chance of acquiring such 'sickness.'  The discovery that transposition into and out of a vacuum was nearly without risk, baring ecological contamination, paved the way for funding into studying aerospace applications.  Finally, it was from these aerospace programs that it was proven that dimensional transposition gates interact with gravitational fields and are not completely external to known physical laws.

Due to fears of a compromised intelligence network it is not possible to directly release the results of our study into gravitational field interactions.  For what can be said, the reason that non-directional short and long range transposition follow gravitational equipotentials is due to the planet's gravitational field after all.  Although the purpose of our study was rather humdrum, we have made a second rather remarkable discovery that nearly rivals that of the original portals.  Under certain energy 'resonances' it is possible to transpose an object to a location far beyond the normal range given power requirements.  These resonances are gravitational well dependent and may explain why we briefly travel through the 'sub-prime dimension' when moving between two points.  It is our hypothesis that the 'sub-prime dimension' is simply the widest and lowest energy resonance field gate.  Through the dedication of Melchior's processing banks we have discovered two additional energy 'resonances.'  One is inside a planet that is similar to our own with a silica-oxygen rich crust.  It is impossible to determine where this planet might be due to extreme pressures crushing any probes sent to it.  Our only information comes from the avalanche of material that 'kickback' from the portal.  The second location is the proposed focus of all available research assets.

We have found a portal that appears to lead to a stable intergalactic Lagrange point formed by two spiral galaxies.  The point is far enough away that our simulations of what the known universe would appear as in the future and past, dependent on the speed of light and reference frame, are unable to locate it.  Isolated beyond belief, it is predicted that the chance of an external catastrophic event would be less that one-one millionth of any similar event on earth.  For the cost of several thousand kilo-watts we can now move bulk matter between the surface of the earth and a specific point isolated in the depths of intergalactic space.  This point may appear useless since it offers no form of natural resource but it will allow us, with investment, to create a 'space station' that will be beyond the reach of any weapon or enemy excepts what may travel through the transposition gate.  

Our formal request to the coalition  of nations is that all spare resources be invested in planning and building the 'space station' that will guarantee the survival of mankind even if the planet is entirely lost.  Our scientific ambassador will formally present you with the new proposal at the emergency council meeting.

[Sorry, I have no idea why these things won't format correctly...]
[Note:  These are for the scientist mission tree... or anyone else who happens to break into the Melchior network in the data lab room]
##

**Comment by qbradq** [comment]
Can we get the Enhancement label applied please?

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
