### ISSUE TITLE
Add limb modifying bionics (prosthetics limbs, weaponized arm, etc)

### ISSUE THREAD

**Issue by jason0320** [CleverRaven/Cataclysm-DDA#16105]
So it's possible to loose arms and/or legs, an option to regain missing limb(s) by installing artificial limbs or attach weapon like chainsaw or mini gun will be helpful to gameplay.

Btw how can I build using on win7? I followed the makefile guide and only got some timespec structure redefined error.

**Comment by Labtop-215** [comment]
As far as I can tell, you only lose an arm when you install the Fusion Blaster CBM.  If your arms or legs hit 0 hp, they need to either be fixed by wearing a splint and waiting some time, or seeking out a Mr. Stemcell terminal and using it.

**Comment by kevingranade** [comment]
While that's true, the main reason we don't have limb loss is we don't have
a way to recover from it. These could initially use the same code as the
fusion blaster, but later expand into being replacement limbs, then we
could add limb loss mechanics.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
