### ISSUE TITLE
Vitamins and defficiencies

### ISSUE THREAD

**Issue by mugling** [CleverRaven/Cataclysm-DDA#16118]
Presently it's too easy to exist on a single food source indefinitely (oatmeal or cooked meat being common examples). In reality such a diet results in nutritional deficiency diseases such as scurvy.

I'd like to propose a series of deficiency status effects triggered by prolonged lack of one or more vitamins/minerals. Some foods would have various deficiencies forcing at least a minimal attempt at a balanced diet. Vitamin pills can then have their typical use becoming both rarer and more valuable.

I'd like to keep such a system simple so that it's both easy to implement and more importantly easy for players to understand. For example eating a diet entirely composed of eggs should eventually lead to hypovitaminosis C (scurvy):
```
"id": powder_egg"
"type": "COMESTIBLE"
"deficient: [ "vitC" ]
```

IRL the body is capable of storing many vitamins (dependent upon their lipid-solubility) for some considerable time and excluding deficient foods vitamins are usually present in massive excess in most foods. Accordingly we can model this simply and intuitively as a requirement to consume a non-deficient food (or vitamin tablet) within a given number of turns.

| vitamin   | state                 | effects                                                                             |
|------------|---------------------|-----------------------------------------------------------------------|
| `vitA`      | night blidness   | markedly reduced vision in low light                                |
| `vitC`      | scurvy              | painful sores with chance to become infected                 |
| `vitD`      | osteomalacia    | risk of fracture from bashing damage                             |
| `calcium`| hypocalcaemia | convulsions (similar to current tetatnus implementation) |

Most foods should **not** have a deficiency (and certainly never foods cooked from multiple ingredients). Deficiencies occur after 7 days of entirely deficient food (IRL scurvy takes just under 4 weeks) with the counter for each vitamin reset upon eating a non-deficient foodstuff. This makes deficiencies easy to avoid whilst still requiring you to more carefully plan your dry food stores (or hoard vitamin tablets).

Questions, comments or suggestions before I start on an implementation?

**Comment by kevingranade** [comment]
Hooray! Just out of curiosity, is this based on one of my rants on the
subject, or reached independently?
Hardcoding the duration would be fine for a first cut, but I feel like each
deficiency disease is going to end up with a definition that includes a few
things like name, nutrient, effect, etc, so that will be a.nice place to
put a duration stat before the effect is experienced.

**Comment by mugling** [comment]
Independently but i'd be happy to collaborate on the list of vitamins and diseases?

**Comment by Coolthulhu** [comment]
> Deficiencies occur after 7 days of entirely deficient food (IRL scurvy takes just under 4 weeks) with the counter for each vitamin reset upon eating a non-deficient foodstuff.

Sounds incredibly easy and inconsequential, to the point where eating even the blandest diet would be unlikely to ever trigger it. For example, a single stack of wild herbs (0 stack volume, 20 stack size) would last 20 weeks.

I'd change it to be more like hunger:
* Each deficiency gets a counter
* When consuming a food item with given vitamin, counter is decreased by an amount based on item's nutrition and healthy value. For example, `(nutrition + 10) * max(healthy + 1, 0)`. Unhealthy food would not add anything
* When the counter increases past some value, deficiency effects happen. Possibly with multiple thresholds or linear scaling
* Counter ticks slower when the deficiency is stronger, to make recovery easier

This would fix exploits like:
* Eating a unit of flour to fix deficiencies for a week
* Eating a single berry to last half a season
* Consuming an unupdated not-really-comestible (salt, cig) to remove deficiencies

Also, mirroring the `deficiency` field, there could be a `vitamin` field which would increase the deficiency reducing power of a selected vitamin by some amount - set or relative.

The vitamin pills should lose their `healthy` effect. Later on health could be calculated based on deficiencies, with very low deficiencies boosting it.

**Comment by codemime** [comment]
What about ill effects of overdose? Hypervitaminosis is sometimes more dangerous, than lack of vitamins.

**Comment by mugling** [comment]
@Coolthulhu how then to stop abuse of vitamin pills?

**Comment by codemime** [comment]
@mugling No multivitamins, vitamin A and vitamin C as different items, no other vitamins in pills?

**Comment by Coolthulhu** [comment]
Possible solutions:
* Split them up into subtypes, with multivitamin being just one of them. This wouldn't stop it, but would increase "effective rarity" without having to make vitamins rarer than katanas
* Allow them to get the deficiency counter into negatives, then have that cause hypervitaminosis. Shouldn't make regular food cause it, though - food should be capped
* Combined with the above - have deficiencies rise at different rates to make pure pill popping cause both deficiencies and hypervitaminosis at the same time
* Make them decrease health rather than increasing it, to make healthy food a better choice

**Comment by mugling** [comment]
@codemime only one type of vitamins so yes multivitamins (although not necessarily containing all possible vitamins)

**Comment by Labtop-215** [comment]
Shouldn't eating raw flour gum up the works so to speak and make you constipated?  I know we don't model bodily fluids, and I don't suggest we start, but I think eating raw flour should result in some pain, with a message occasionally telling you that your stomach hurts a lot, or something along those lines.

Other than that, I found that eating the same food over and over again with no consequence does make the game boring.  I've gone out of my way to make sure that my characters eat at least something of a balanced diet as possible, simply for role playing reasons, and I think adding diet management, and consequences for mismanagement would add a nice challenge to the game.

One thing that concerns me about this possible change though is that it will make eating items that are split into portions more dangerous because their vitamin increasing or deficiency effects will trigger multiple times (like biscuits, or soup), while items that give their whole benefit at once will only trigger once, like ant eggs will only penalize you once, Mycus fruit (if you are dependent on it) will only trigger once per feeding, and grilled cheese sandwiches (don't judge me for my eccentric tastes!) will only trigger once.  This could lead to weirdness where ant eggs don't penalize you much if you eat them regularly, while somebody following the Marloss tree who needs Mycus fruit could end up either over or under vitamin'd.

**Comment by Coolthulhu** [comment]
> One thing that concerns me about this possible change though is that it will make eating items that are split into portions more dangerous because their vitamin increasing or deficiency effects will trigger multiple times (like biscuits, or soup)

That's why scaling with nutrition is important. It could be overridden in the JSON, but by default the vitamin value should scale with nutrition and health of the food item.

**Comment by lucianposton** [comment]
> @Coolthulhu how then to stop abuse of vitamin pills (beyond rarity)?

How about expirations on vitamins? Multivitamins expire after a year or so, and nobody's manufacturing new vitamins in cdda. If we have a mechanic along those lines, difficulty would ramp up over time since no fresh vitamins would exist after the first yearish.

**Comment by player0981234** [comment]
This also needs balance for mutant survivors who can only eat meat
