### ISSUE TITLE
[Suggestion] Add Skill Rust Speed option

### ISSUE THREAD

**Issue by Murumuru** [CleverRaven/Cataclysm-DDA#16113]
As title says, add option similar to "Skill training speed", but for the skill degradation rate. 
I think, it would allow to better customize the game for players as well as not too difficult to implement.

**Comment by Labtop-215** [comment]
I wont use it, but it would add another dimension to how difficult the game can be for those that want it.

If it's ramped up, it could force some specialization for those who want that kind of challenge anyway.  I know the obvious answer to that is "Savant" but that only covers one skill when specialization could easily cover 2 or three.

Like melee, dodge, and a weapon type skill like bashing, cutting, peircing, or hand to hand.

Cooking, marksmanship, and shotgun skill (flamethrower specialist)

Cooking, Speaking, and Driving (Drug dealer specialist)

And the like.  Some flexibility would be nice, and with this in place, Savant as a character trait would have more weight as well, instead of less.

**Comment by kevingranade** [comment]
There are already too many options for adjusting skill rust, and a general
consensus that what we have doesn't really work. I don't think piling fixes
and tweaks on a broken system is worthwhile.

**Comment by Rivet-the-Zombie** [comment]
The character's INT stat and traits already affect the rate of skill rust.

**Comment by Murumuru** [comment]
@kevingranade, it is not intended to be a fix, just a customization option, which, I think, will be handy to have.

@Rivet-the-Zombie, they depend on a character, but this should affect skill rust in general.

**Comment by mugling** [comment]
Skill rust is broken and almost nobody uses it. We should either scrap it or replace it with a better mechanic as opposed to adding more configuration options
