### ISSUE TITLE
Corpse weight and volume need reworking

### ISSUE THREAD

**Issue by Sir-Kernicus** [CleverRaven/Cataclysm-DDA#16158]
Weight of a : 
Coyote- 15-46 lbs
Beaver- 24-71 lbs
Fox- 4.9-31 lbs
Deer "White tail" 150 lbs male 100 Female Avg. this one is variable from 200 lb doe to a 100 lb buck
In game:
coyote (both eastern and north eastern) 179 lbs
beaver 90 lbs
Fox 90 lbs
Deer 264 lbs
(Bear 264 lbs small but accurate)

I had found that the weights didn't seem to match up.  My first question is does this even warrant change, and secondly could there be a reason they got heavier.

**Comment by DanmakuDan** [comment]
Corpse weight and volume are hardcoded by creature size in game, they aren't defined per creature (yet).

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
