### ISSUE TITLE
Show texture creation progress bar on game load (SDL)

### ISSUE THREAD

**Issue by remyroy** [CleverRaven/Cataclysm-DDA#16268]
On some system, the main part of loading the SDL game is creating the tile textures. For instance, on my MacBook Pro Mid 2010 (Intel Core 2 Duo, 2.4 Ghz), it takes more than 92% of the loading time (about 40 seconds in some cases).

It would be nice to show a progress bar for that part of loading the game. It would give a better idea to the user about the remaining time before he can play and it would be a better user experience overall.

You can see a profiling trace I just did on my MacBook. It shows how much time is spent in which function with a sampling interval of 1 ms.

[Time Profiler - Run2.csv.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/225448/Time.Profiler.-.Run2.csv.zip)

**Comment by DanmakuDan** [comment]
Just wondering, is this using the default hardware acceleration option for Cataclysm? What happens if it's set to software rendering? It looks more like glTexSubImage2D isn't performing like it should, possibly due to that system's openGL implementation. 40 seconds is crazy.

In comparison on Windows, loading many small files has more impact on performance than other systems.

**Comment by remyroy** [comment]
It is much faster on software rendering. It takes about 3.6 seconds on my Macbook for loading tiles.

[Time Profiler - cataclysm-tiles_Run1.csv.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/226102/Time.Profiler.-.cataclysm-tiles_Run1.csv.zip)

**Comment by remyroy** [comment]
The long delay for loading textures seems to have been a driver issue. I've updated to OS X 10.11 from 10.9 and the delay seems shorter. It's down to ~4-6 seconds and more like 40-50% of the loading time under debug and profiling. Various factors can slow it down further like other applications already using the GPU.

It would still be interesting to have progress bar showing loading progress nonetheless.

Here is another trace run with hardware acceleration on OS X 10.11.

[Time Profiler - cataclysm-tiles_Run1-10.11.csv.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/226655/Time.Profiler.-.cataclysm-tiles_Run1-10.11.csv.zip)

**Comment by kevingranade** [comment]
The main question I have is whether the api exposes that progress. If it's
a simple matter of registering a callback, great, but if it means
overhauling how we initialize sdl just to get the progress out, it doesn't
seem worth it

**Comment by DanmakuDan** [comment]
For a tileset like ChestHole, the for loop loading the tileset is initializing around 8000? different textures after accounting for alternate lighting. In this specific case with the MacBook, SDL hardware accelerated rendering automatically picked openGL as the main renderer. The openGL driver appeared to have its own issues that were contributing to excessive memory allocation times. 

For a simple way of showing loading progress, the popup code can be used to print what stage loading is at currently (json, tileset, loading save, etc.)

**Comment by Rivet-the-Zombie** [comment]
As far as progress bars go, folks are generally happy with pretty much anything that shows that the game is still doing stuff and not just hung in place, be it a moving bar, a changing list of files, an estimated time remaining, or a completion percentage.

**Comment by lucianposton** [comment]
..or a much simpler, animated spinner / moonwalking zombie

**Comment by Rivet-the-Zombie** [comment]
That would work too. Basically something on the screen that moves or otherwise changes over time to show that the program is still alive, and not frozen in place or something.

**Comment by Zireael07** [comment]
Not to mention the fact that Windows treats "no changes to screen" as "we're frozen" :P

**Comment by Nullsrc** [comment]
Agree with @Rivet-the-Zombie on some kind of movement. Feels better to know that something is happening and that the window isn't frozen. What about drawing some kind of generic "loading" thing to the screen for a large number of intensive parts of the game, not just loading tiles?

**Comment by lucianposton** [comment]
Would be okay with a super moonwalking zombie animation loop:
![supermoonwalk](https://cloud.githubusercontent.com/assets/646121/14682892/b10d256a-06dc-11e6-8898-e966d77c1bb7.gif)

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
