### ISSUE TITLE
Engine repairs

### ISSUE THREAD

**Issue by mugling** [CleverRaven/Cataclysm-DDA#16271]
Currently strategy for engine selection is limited to finding the biggest displacement gasoline engine. I want to tackle this via differing fuel efficiencies (#15775) and also reliabilities with this PR considering the latter

There are two paths we could take, either more vehicle parts (`radiator`) or internal state for an engine (`old_belt`, `old_oil`) with a requirement to replace these parts or suffer effects (`SEIZED`, `SLOW_START`). It would be good if you had to scavenge for new glow plugs for your diesel engine before the winter came around and rendered your engine unusable.

Such an implementation needs to be clean (eg. not a repetition of the gunmod code).

Comments and suggestions?

**Comment by Rivet-the-Zombie** [comment]
>more vehicle parts (radiator)

I like this approach better than the alternative. We already track the alternator as a separate component, so it really wouldn't be anything new, just an expansion upon that concept.

**Comment by mugling** [comment]
It gets a little tricky for things like belts though - these should remain attached to the engine when removed?

I also want to look into vehicles require oil (and older or abused engines burning/leaking oil)

**Comment by Coolthulhu** [comment]
I'm against more parts that don't have downsides ("having to install them" doesn't count). For example, bigger radiator requiring the center slot, preventing having it share a tile with something useful.

Slow start sounds like a good downside for anything that could be required for a big engine to work properly.

It would be good if the requirements grew with engine size. Small engines (V4 or smaller) should not require much extra scavenging, with 1 cylinder ones working out of the box. V12 can require significantly altering the vehicle to make it fit. Electric engines shouldn't need extra parts, maybe except the enhanced ones.

Also, it shouldn't be too annoying. Having to manually replace oil sounds annoying. If multiple components start requiring maintenance, it could be worth implementing it, but with a "maintain vehicle" function that allows selecting maintenance options, supplies good defaults (including a sane, useful "maintain everything" option) and, once again, affects "good" engines more than it affects the simple, tiny crap (v4 and less) that everyone removes from the vehicles in current version of the game.

**Comment by kevingranade** [comment]
I prefer the "worn belt" condition rather than adding a new belt item with
its own state. If literally the only think we're tracking is that it's
wearing out and needs replacement, it doesn't seem worth modelling as a
separate part.
Radiators for example might have something to differentiate them, like
capacity, air cooled vs water based, other exotic mechanisms. That would
make them worth modelling as a separate part.

**Comment by kd8qdz** [comment]
Reading what was talked about in #16272, I think the case can be made for having radiators, especially as these are damage liabilities for vehicles.   There can be a significant down side to hiding your radiator behind armor.    And I agree that "Worn Belt" and "Dirty oil" etc should be conditions rather than items.

As for more parts, I think its odd that we don't have transmissions as parts.  This could tie in well with the attempt to differentiate the engines.  The downside is that I'm not sure how to meaningfully implement them with out doing massive damage to the current engine system.

**Comment by kevingranade** [comment]
Transmissions would be nice, the question is what level of detail to use.
In the extreme, you can have a power curve that relates rpm to horsepower,
and a similar curve for fuel consumption, the transmission would have a set
of gear ratios and an efficiency curve.
In practice the engine and transmission definitions might be ok to just
have rpm ranges, ratios, provided torque, and an efficiency number.

I'd like the internal APIs to support the higher level of detail, though
it's not as complicated as it sounds (it's just a matter of the vehicle
passing instantaneous drive shaft rpm and maybe some object that captures
torque requirements into the transmission, the transmission adjusts them
based on its current gear ratio and passes them to the engine which uses
some fuel and returns how much torque it was able to apply, the
transmission then adjusts that number itself and passes it to the vehicle,
which applies it to the wheels.)
