### ISSUE TITLE
scenarios.json "professions" flag could use an exclusion version

### ISSUE THREAD

**Issue by Mattamue** [CleverRaven/Cataclysm-DDA#16289]
Hey team, see data\json\scenarios\scenarios.json. Specifically the infected and burning building scenarios. The inclusive list of professions allowed in these cases is prohibitively long in order to exclude a few professions, I assume, that could negate the starting situation.

It is a little confusing as a player seeing "limited" on the character creation for these two scenarios, but still having a large list of professions to chose from.

Because of the inclusive nature of the list any new professions that aren't added into the profession list is automatically excluded. An easy oversight. The infected list, for example, appears to be a snapshot of new professions rather than just their intended excluded emergency-type professions.

Excluded (by not being included) today: basketball_player, bio_sniper, broken_cyborg, churl, detective, drone_op, fisher, jr_survivalist, mall_cop, medic, national_guard, paperboy, parkour_practitioner, patient, preacher, reenactor, reenactor2, riot_police, sniper_police, swat, swat_heavy

There are only 2 impacted scenarios today so it is a minor enhancement request. I imagine the only way to remove the player confusion for the exclusion version would be to have a new command on the scenario screen to expand to a list of excluded professions for space concerns. Otherwise they'll still roll to a long list of available professions on the professions tab. So, this may be a lot of work for a little payoff!

**Comment by railmonkey** [comment]
Going to second this suggestion. I've fiddled about with workarounds, myself, though only for Infected. So far, the easiest solution I've found is to just go in and delete the professions line for the Infected scenario outright. Given how comparatively simple it is to acquire first aid kits and/or antibiotics in a reasonable span of time (or die trying), I don't bother playing any professions that start with them. I don't bother playing any cross-scenario specific classes, either. If I wanted to do that, I'd just switch to the proper requisite scenario.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
