### ISSUE TITLE
Non-repairable vehicle parts

### ISSUE THREAD

**Issue by mugling** [CleverRaven/Cataclysm-DDA#16291]
Many vehicle parts have a finite lifespan and can be patched but never made new.

Good examples would include radiators and batteries. The former can have leaks patched but can never be returned to their as-new factory state. Batteries are similar in that you can topup electrolyte but ultimately the plates fall apart.

This is a separate issue as to whether you can reasonably recycle and craft those items (batteries yes, radiators no).

What would be the gameplay implications of making some parts non-repairable? One of the obvious outcomes is that you could have real breakdowns (with a need to carry a realistic set of spares) as opposed to merely having to spend a few IRL minutes repairing all the vehicle tiles.

**Comment by AdonaiJr** [comment]
I like this idea, mugling. Like you said, the player would have to carry a spare or to watch carefully the wearing of the part, looking for a new part every now and then. Also, it could be made somewhat repairable, like each time you repair, it looses some of it's "max life", until finally would be better to change it. This way the player can "in an emergency" repair the thing and keep going, but to planning to change it because it's less and less reliable to keep the thing.

(sorry for the weird english)

**Comment by Coolthulhu** [comment]
Needs a good mechanic for wearing the parts down.

Wearing with use:
* If too fast, things would wear off faster and more commonly than fuel
* If too slow, you could easily subsist on parts scrapped from semi-wrecked cars on roads
* On paper, it looks like the "golden middle" is actually at the same time both too fast and too slow, due to how scarce fuel in vehicles is compared to how common the vehicles are

Wearing with damage:
* Parts that matter are already too easy to install in safe spots
* Parts that are installed on the outside are just steel sheets/frames

Wearing with time (hard thresholds):
* If too slow, wouldn't be noticeable
* If too fast, it would be all Flintstones mode after a year or so

Wearing with time (half-life decay):
* As above, but stretched more naturally in time
* Doesn't actually have the Flintstones Threshold, meaning you could subsist on some weird combo of sci-fi tech, real tech and primitive tech (steam engine cars?)


Also, it would require reworking some minor mechanics:
* Part repairing would require a major rewrite
* Fuel leaking (including batteries) has ugly hard threshold at ~50% hp - it doesn't leak at all before that, it leaks very fast after that. Should probably leak when `current_content% > 50% + hp% / 2` or something like that.
* After above is done, fuel deposition should prefer undamaged batteries, to avoid having to "re-enumerate" (uninstall and reinstall to push to the back of the vector) the batteries. Or instead a realistic model where each battery gets a percentage of incoming power could be written.
* Vehicle part HP tracking would need to get more precise. Currently it is a very lossy division/multiplication that actually allows you to repair parts by reinstalling them, with no extra action (meaning no resource cost for batteries).

**Comment by mugling** [comment]
> Doesn't actually have the Flintstones Threshold, meaning you could subsist on some weird combo of sci-fi tech, real tech and primitive tech (steam engine cars?)

This seems like a strangely appealing outcome for the late game

**Comment by narc0tiq** [comment]
I want to suggest that wear should track separately from damage, with some
overhauling possible to wind back the clock (at the cost of losing some of
the total capacity for wear).

The more worn something is, it should have an increasing chance to take
actual damage, which can be repaired as normal without affecting the wear
in either direction. At the extreme, it'll be practically impossible to run
with the part as it'll take damage before you've gone more than a few
tiles.

**Comment by John-Candlebury** [comment]
>The more worn something is, it should have an increasing chance to take
actual damage, which can be repaired as normal without affecting the wear
in either direction. At the extreme, it'll be practically impossible to run
with the part as it'll take damage before you've gone more than a fewThe more worn something is, it should have an increasing chance to take
actual damage, which can be repaired as normal without affecting the wear
in either direction. At the extreme, it'll be practically impossible to run
with the part as it'll take damage before you've gone more than a few tiles

This seems really good

**Comment by Night-Pryanik** [comment]
Closing as per lack of discussion.
