### ISSUE TITLE
Ideas for Lamps, Floodlights

### ISSUE THREAD

**Issue by darth-servo** [CleverRaven/Cataclysm-DDA#1632]
I'm sure someone has suggested these things before, but I didn't see anything on here.

Makeshift Reading Lamp:
Just a large bundle of activated Light Strips duct-taped together.  Provides constant light and will burn out (as Light Strips already do), but provides light equivalent to the console in the Evac shelter -- illuminates 1 square in every direction.  Deployed like a brazier/rollmat/trap.

Battery-powered Lantern:
Same effect as above (illumination in 1 square around it), but uses batteries and can be turned off and on.  More efficient than a flashlight but only gives light when it is deployed (immobile).

Floodlight:
A UPS connected to 3-4 flashlights attached to the end of a pipe as a makeshift stand.  Provides directional illumination like the current makeshift vehicle-based floodlight in the same sort of arc as vehicle headlights.  Deployed like a brazier/rollmat/trap with either a popup dialogue asking which direction it should point, or the direction being based on which way it was deployed, so that players can set them up in corners of a room.  More efficient at using batteries than a regular flashlight (so it lasts longer per charge), the advantage being offset by it being immobile and not providing 360-degree illumination.

Crank-powered Flashlight:
Instead of disposable batteries, uses a hand-crank/dynamo to charge the internal battery.  Real-life versions of this sort of flashlight provide 45+ minutes of light from 1 minute of cranking, but this could be balanced to fit the setting.  Perhaps has a chance to break each time it's cranked up to recharge.
##

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
