### ISSUE TITLE
Clay items are too expensive to be useful

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#16333]
The requirement of a kiln loaded with charcoal makes it unfeasible that anyone will construct even a single clay item. Sealed stomachs are far cheaper and easier to craft.

My ideas:
- Split the tools used into kiln and (separately) fire. Remove the ability of the kiln to hold charges. Not too realistic, but neither is requiring pure charcoal for clay stuff
- Make kiln constructible at sane levels (2 construction) and drop its stone requirement to 10-20. 4 construction is unfeasible without books and clay stuff is simply not worth it - only clay crucible doesn't have a cheaper alternative that fulfills all its functions
- Remove the leather component or allow using cured (not tanned) hides for that. Leather is expensive in the wilderness, its two biggest sources are zombie clothing and car seats
- ~~Remove the string component or allow using withered plants for that. Strings are expensive in the wilderness~~ (resolved by #21783).
- Nerf stone pot so that clay pot has an use

**Comment by DanmakuDan** [comment]
> Nerf stone pot so that clay pot has an use

Add a cooking efficiency quality that lengthens cooking times unless you have better equipment? How efficient is a pot made from 3 rocks and some string?

**Comment by Coolthulhu** [comment]
> Add a cooking efficiency quality that lengthens cooking times unless you have better equipment?

That's much bigger than all the clay stuff combined.

I was thinking about just removing its COOK 3, CHEM 1 and BOIL 2 and giving it only COOK 2 and BOIL 1.

**Comment by DanmakuDan** [comment]
It sounds fair, just noting that downgrading to BOIL 1 alone mostly removes access to some tanning recipes, most chemicals and some minor(?) foods. Most of those overlap with having COOK 3.

**Comment by Coolthulhu** [comment]
Then it could keep that BOIL 2, but it shouldn't have COOK 3. Recipes that require COOK 3 and should be allowed with wilderness tier equipment should drop to COOK 2.

Would be easier if we had a description of what should each level do. For example, COOK 1 being just holding above heat, COOK 2 allowing simmering in water, COOK 3 allowing fully submerging in boiling water.

**Comment by kevingranade** [comment]
Shouldn't the stone pot just be hella heavy?

**Comment by Coolthulhu** [comment]
If it was made from a single stone then maybe. But it is made from 3 rocks. Not sure how is it supposed to work.

**Comment by kevingranade** [comment]
I thought you were grinding the stones against each other or something.

**Comment by Mshock777** [comment]
It would be nice to decease rock pot volume to 8 to be in line with other pots, or nerf even further, but keep weight the same.(maybe remove it from survivor mess kit recipe?)

**Comment by Coolthulhu** [comment]
Honestly, I don't really see how would a stone pot work, except if it was carved from a boulder. Could be cool to have it be a construction project taking a small boulder and turning it into very unwieldy, heavy and voluminous pot.

**Comment by Mshock777** [comment]
It would be more logical to have rock bowl instead of pot (like clay bowl, but without `CONTAIN`)

**Comment by Coolthulhu** [comment]
The whole deal with the clay pot is that it is the only cooking utensil available to "primitive" survivors. It can't become a bowl.

**Comment by kevingranade** [comment]
For our purposes a pot is simply, "something that contains liquids and is
permeable to heat".
It would be better to have a "large rock" required for powl/pot crafting,
because "fist sized" as per the rock item is certainly too small.
Also grinding a stone pot without power tools is going to take a very long
time (days).

**Comment by Mshock777** [comment]
I think medium boulder is large enough for volume 10 rock pot.

**Comment by Mshock777** [comment]
It's a bit off topic, but

> What do you think about decreasing the rate at which pot spawns? Apart from volume, it's significant upgrade, but right now they both spawn at the same rate.

**Comment by AppleConnoiseur** [comment]
Letting us make simple cords from plastic bags, hide, leather, reeds and tall grass could be useful. Time consuming but possible to do it by hand just like in primitive times :D.

Some examples i made when i was curious after having been binge playing 7 Days to Die with its plant fibers being used for everything.

Cardboard loom with simple 4 cord braid pattern. Fairly strong for being made out of essentially trash. For my skill and technique i think it took at least 2 hours to make. Should be strong enough to keep a stone axe together though.
https://dl.dropboxusercontent.com/u/547140/7d2d/2016-04-19%2021.18.31.jpg

Plastic bag single cord made within 15-25 minutes. Not very strong but it should be able to at least keep a satchel shut and attached to your waist.
https://dl.dropboxusercontent.com/u/547140/7d2d/2016-04-19%2021.54.51.jpg

**Comment by Hague** [comment]
On the subject of clay pottery. The most primitive clay-firing would be done with a [pit kiln](https://en.wikipedia.org/wiki/Pit_fired_pottery).

**Comment by Zireael07** [comment]
I agree that a stone pot from a single rock is a bit silly. Changing that to use a boulder and increasing the weight are good ideas.

**Comment by keyspace** [comment]
> Nerf stone pot so that clay pot has an use

Done in #19804

**Comment by kevingranade** [comment]
Some of the suggestions here are reasonable, but I have to point out that the rationale doesn't hold up.  We don't change things because "clay pots aren't worth making".  It might be a symptom of other issues, which is the case here, but you need to find the underlying issues and use them as the basis for change.  Put another way, the fact that an arbitrary item isn't worth making in the cataclysm scenario is not in of itself a reason to change anything, maybe it's just worthless.

The suggestions touch on some of the actual issues:
Kilns are unreasonably difficult to make (fabrication:4 seems excessive, charcoal kiln is 3 and you seem to be building more or less the same thing).
Gathering the number of stones required for a kiln is too tedious: I don't buy the reduced stone requirement, 40 is already a ridiculously low number for crafting a large kiln, it would easily be more like 500 fist-sized stones (roughly 10x10 stones to a side, and 6 sides), it seems more problematic that we don't have any larger stones, or good bulk sources of stones.  If you were seriously building stone structures like kilns IRL, it would be far more productive to find a quarry or riverbed ravine or similar place with a large number of exposed stones than to wander around fields looking for them, then it would just be a matter of transporting them back o your construction site (or building in-situ, which is also more interesting from a gameplay POV).
Kilns are unreasonably difficult/expensive to use (only accepting charcoal, and potentially lots of it, and not batching firings (normally you'd NEVER fire just one item, which cuts the fuel-per-item a great deal))
We are missing key crafting materials used in wilderness survival, such as cordage and rawhide bindings.

**Comment by DaviBones** [comment]
Clay items are still very awkward, fabrication 4 is required for any sort of kiln, which makes the fact that clay recipes are unlocked at fabrication 2 a bit misleading. Even if the kiln requirement was reduced to fabrication 2, charcoal is unavailable until fabrication 3.

This is a real shame, because in an actual "innawoods" survival situation, a clay pot would be far and away the quickest and easiest solution for boiling water and other liquid-cooking usage, assuming good availability of clay. Why is that, you might ask, since building an actual kiln would be such a huge project? The answer is because of [pit kilns](http://ballclaystudio.com/how-to-pit-fire-pottery-without-a-kiln/), the oldest known method of firing clay items. They do not require charcoal, just a reasonably sized hole, and a decent amount of combustible material.

I think that pit kilns would solve this issue quite nicely, and help a lot with innawoods realism as well. My idea for implementing them is as follows:
1.) Modify current clay recipes to not require a kiln but result only in an "unfired clay XX", an intermediate product unsuitable for use as a tool.
2.) To restore standard kiln functionality, either:
    a) Add recipes requiring "unfired clay XX" and a brick kiln, resulting in "clay XX"
    b) Modify kiln functionality to work somewhat like the constructed charcoal kiln: player must drop items to be fired onto the kiln, then (e)xamine the kiln with a source of fire and enough charcoal in inventory to fire it. This has the added benefit of enabling batch firings like @kevingranade mentioned.
3.) Add "Pit Kiln" to the construction menu. Requires fabrication 2, a "Shallow Pit," and a decent amount of combustibles (perhaps 6 two-by-fours or 12 heavy sticks or 40 splintered wood) to build, takes 30 minutes. Used similarly as in (2b) above, drop unfired items on it, and (e)xamine with a source of fire in inventory. After 24h, the fired items are dropped on the ground, and the pit kiln is deconstructed completely, so a new shallow pit and pit kiln must be constructed to fire more items, which could incentivize the creation of an actual clay kiln. If that isn't enough incentive, batch sizes could be limited to 1 or 2 items, though this is pretty unrealistic.

I am not the most adept C++ coder and am unfamiliar with CDDA's source, so doing this myself would be a pretty decent sized project -- but I am still happy to make this PR myself if the idea is approved.

**Comment by thethunderhawk** [comment]
It might be worth pointing out that IRL primitive boiling is usually accomplished by putting hot rocks into whatever water container you have on hand, an unglazed clay pot for example. I’m not aware of any culture where stone pots were a common piece of primitive cookware.

**Comment by kevingranade** [comment]
Supplanted by #27091
