### ISSUE TITLE
Number of turns to reload guns don't change when changing amount of ammo to be reloaded

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#16373]
![222](https://cloud.githubusercontent.com/assets/11132525/14767821/af1ec88c-0a40-11e6-8b0d-ae0d001f76ed.PNG)
Seems like to happen only with revolvers.

Win 10, tiles, 0.C-4750.

**Comment by mugling** [comment]
Can't find an obvious cause for this. What version and platform?

**Comment by Night-Pryanik** [comment]
@mugling 
> Win 10, tiles, 0.C-4750.

**Comment by BevapDin** [comment]
`player::item_reload_cost` ignores the amount of ammo to reload with when the item is gun (and not a magazine). This means `reload_option::moves` effectively ignores the `qty()` value when the item is a gun. No idea what the behavior should be.

Btw. I confirm this on Linux (32bit), with S&W 619, reloading with .38 FMJ from ground.

**Comment by kevingranade** [comment]
I assume this was a "don't disturb existingfunctionality" Kind of decision.

**Comment by mugling** [comment]
I think it was because originally `RELOAD_ONE` guns have `reload` specified per round whereas those with integral magazines specified per full-load. The correct solution is to transition the JSON to per-round.

The recent changes have effectively deprecated `RELOAD_ONE` to a UI hint that the reload dialog should initially offer one round
