### ISSUE TITLE
Old Guard Quest - Bandit Camp couldn't spawn

### ISSUE THREAD

**Issue by Lazasar** [CleverRaven/Cataclysm-DDA#16390]
Got a message after getting quest that the camp couldn't be found, or something like that, and then a hostile NPC spawned in the refugee center, which I killed, thus completing quest.

**Comment by nanovad** [comment]
Isn't this related to the bug that would throw errors if it couldn't find a lab/cabin in which to spawn the player? How was that bug fixed? (I can't find the issue # right now.)

**Comment by Soyweiser** [comment]
http://smf.cataclysmdda.com/index.php?topic=12899.msg278391#msg278391 somebody else also had the same problem. I don't think this person had the hostile npc show up.

**Comment by Noctifer-de-Mortem** [comment]
I believe #18244 fixes this as well no?

**Comment by random313** [comment]
No. Still got this bug on 5583 build.

**Comment by Coolthulhu** [comment]
Two possible solutions:
* We disable missions that don't have good locations. Doable.
* We overhaul the mapgen to prevent this situation from happening. Unlikely to happen in this millennium.

**Comment by eliotcougar** [comment]
If I understand it correctly, all we need is an overmap location bandit_cabin to spawn in the world... There's a bandit_cabin.json in mapgen... The mission worked almost fine when I placed it manually nearby before asking for a quest... (Bandits were friendly)
Also, in the second mission, the rat from Hell's Raiders does not become hostile after you talk to him... Something is wrong with faction relations here...
In the fourth mission bandit_camp_1 does not spawn, so that the guy you are supposed to kill spawns in the refugee center instead (and is again friendly)

**Comment by Coolthulhu** [comment]
@codemime did quite a bit of work on overmap gen and so probably has the most knowledge about current state of overmap gen.
How feasible would it be to actually guarantee existence of bandit camp in nearby future?

**Comment by codemime** [comment]
@Coolthulhu This can be done extremely easily by softening the distance requirements. All our cabins have certain difficulties with spawning. The condition "at least 20 tiles from any city in a forest" isn't easy to meet using completely randomized deployment. Though 10-15 tiles would almost guarantee reliable spawning under normal circumstances, it's still impossible in case of big and closely-grouped cities.

I remember you were suggesting Voronoi diagrams. I like that suggestion very much, but it takes some time to implement properly. At the same time, @vache's [suggestion](https://github.com/CleverRaven/Cataclysm-DDA/pull/19144#issuecomment-259292247) would be easy to do and would suffice for now.

**Comment by BorkBorkGoesTheCode** [comment]
This just happened again in 0.C-22759
