### ISSUE TITLE
Vitamin deficiency affects need some rebalancing

### ISSUE THREAD

**Issue by Lazasar** [CleverRaven/Cataclysm-DDA#16393]
Eating bread for 3 days in a  row shouldn't hit me with Scurvy and Night Blindness, That should take week (well, really months)

**Comment by mugling** [comment]
Existing on a single food source is what the code is trying to prevent. Minimum time to develop scurvy is 4 days if consuming absolutely no vitamin C. An apple a day is sufficient to prevent it entirely (and indeed many foodstuffs contain sufficient for 3-5 days).

**Comment by mugling** [comment]
We could possibly do with adding a *recovering from deficiency* state?

**Comment by Rod-Serling** [comment]
Does vitamin deficiency scale with season length?

I can see going 4 days of a 14-day season (26 "Real days") causing scurvy , but 4 days for a 91-day season (4 "Real days") isn't nearly as realistic.

From a gameplay perspective,  I've found the vitamin system to be a bit harsh so far. I'm not asking to survive on a single food source forever, but so far I've not been able to avoid some vitamin deficiencies, especially near the start when my cooking options are limited, and I don't have multivitamins yet.

**Comment by Coolthulhu** [comment]
> We could possibly do with adding a recovering from deficiency state?

I'd rather see it as effect intensity that starts out low (mostly just informs the player), builds up with time based on deficiency (so low deficiency for long time will still build up to serious intensity), then quickly but not instantly drops in intensity once deficiency clears (possibly benefiting from excess vitamins).

That way scurvy after 3 days would be more of a warning than an emergency.

**Comment by mugling** [comment]
The penalties are currently turned off whilst we address balance. We need to consider both availability of the vitamins and the size of the player storage pools for each.

> but so far I've not been able to avoid some vitamin deficiencies, especially near the start

This part can be considered a balance issue. Which vitamins in which circumstances. You should have little problem inside a city but I could see other starts being more problematic and this needs considering.

> Does vitamin deficiency scale with season length?
> but 4 days for a 91-day season (4 "Real days") isn't nearly as realistic

I don't want to get into this trap of trying to balance the implementation at different season scaling. As to realism there's going to need to be some liberty. IRL some hypovitaminoses/hypervitaminoses can have permanent or fatal consequences and I don't think that would add much to gameplay.

> I'm not asking to survive on a single food source forever

This is indeed the implementation goal, not to simulate the minutiae and perfectly mimic reality (which would be excessively tedious).

> I'd rather see it as effect intensity that starts out low ... builds up with time

The current implementation could be easily extended to support that by adding an intensity parameter to each deficiency effect.

I want to get some more feedback as to which vitamins players are finding difficult to obtain and then adjust the foodstuffs before making alterations to the effect levels

**Comment by Coolthulhu** [comment]
> IRL some hypovitaminoses/hypervitaminoses can have permanent or fatal consequences and I don't think that would add much to gameplay.

Ideally, vitamins should affect downtime the most, because they're the most likely to happen when digesting all those books rather than when scavenging. Plus, heavy combat debuffs could prevent recovering from deficiencies, by locking out all zones with good food.

Good penalties: Lowered focus, speed, book learning (could be separate from focus), intelligence, vitamin gains (except for the vitamin causing it), calorie gain, bodytemp variations (always in the direction of penalty), health drops (slow but uncapped), extra time wasted on sleep, vomiting, increased metabolism, static pain that doesn't spike, making CBM installation and removal harder

Could be OK, could be bad: periodic damage (makes combat risky), regeneration problems (also risky combat), problems with sleep (regeneration), night vision problems (doesn't affect crafters/readers), vulnerability to illness (illness is more of a combat debuff), perception debuff

Bad: big debuffs to combat, vulnerability to infection (only happens in combat), pain spikes (interrupt actions), waking up when tired enough to instantly sleep again (purely annoying), vulnerability to damage or combat-related effects, hallucinations

Evil: selectively purifying good (and only good) mutations

**Comment by secretfire42** [comment]
No offense, but the basic /eating and drinking/ systems don't work very well, I'm kinda amazed that we have a vitamen system - it should probably be a toggle. I mean, there's a big difference between a 92 lb women and a 200 lb man in terms of what they eat (and a lot of range in between!) ... and the food system itself has felt like its...all over the map, at times. I never know from one RL month to the next if its going to be absurdly easy or absurdly harsh. Sometimes, you can live for a week off of a single can of vegetable soup, other builds you can drink gallons and gallons of water (or soup) a day and still be thirsty. Its erratic at best. And thats in part due to its realism. It would take years to get a vitamen system going, and even then, most foods (even bread!) are fortified with vitamins specifically to prevent the problems you discuss. It takes astounding lack of nutrition before you see any of these side effects, and even in the worst post-apoc scenerio, they are extremely unlikely to come up within the timeframe of the game. (A month or a year later, this isn't going to be an issue for most survivors. 5 years? Perhaps.)

**Comment by BevapDin** [comment]
While we're at this, the "Expanded Digestive System" and "Recycler Unit" (maybe more?) affect the amount of required food. They should also scale the amount of extracted / required vitamins.

Currently the character needs to eat less with those bionics, but that also means they can not consume enough of the required vitamins or have to eat the normal amount of food just for the contained vitamins (and thereby making the bionic useless).

**Comment by Coolthulhu** [comment]
> Currently the character needs to eat less with those bionics, but that also means they can not consume enough of the required vitamins or have to eat the normal amount of food just for the contained vitamins (and thereby making the bionic useless).

I disagree, the bionics would still be useful for high-calorie actions and would allow eating low calorie food to fulfill all the needs.

**Comment by Alicecomma** [comment]
Been playing 0.C-4742 on 90 day seasons for about a (real life) week now, spawned near a city and after about an in-game week I managed to get Vitamin A deficiency due to eating nothing but cooked meat (fresh) (hot) which I must say seems realistic. It's very easy to combat this deficiency by eating a few apples/pears/whatever once in a while.

I haven't had any deficiencies in Vitamin B12/C but at the end of the third week I got "Brittle bones" from Calcium deficiency. I haven't eaten anything containing calcium during that period and now I'm eating uncooked bird eggs because they have higher calcium, yet the "Brittle bones" effect is seemingly impossible to fight - I ate nothing but calcium containing foods (hard cheese, raw eggs, cooked eggs) and can't seem to get the effect to go away for longer than 1-2 days after which I instantly get it back.

I have not used multivitamins because hypervitaminosis (vitaminosis in-game) sounds like a bitch, and I don't think they contain Calcium. Imo there should be some more sources of Calcium (since currently it seems literally every vegetable contains Vitamin A/C and every meat contains Vitamin B12/Iron). I am not sure if I'm missing a Vitamin D dependency on Calcium intake (as in real life), since Vitamin D synthesis might be disrupted by the large amount of rain during the 90 days of spring.

Also Calcium seems to be in foods in amounts of 3-5 compared to most vitamins and minerals' 10-20.

**Comment by mugling** [comment]
> and after about an in-game week I managed to get Vitamin A deficiency due to eating nothing but cooked meat (fresh) (hot) which I must say seems realistic.

> I haven't had any deficiencies in Vitamin B12/C

Feedback including numbers from actual gameplay is very useful. I think `VitA`, `VitB` and `VitC` are reasonably balanced alogn with `iron`.

> and I don't think they contain Calcium

They do. Your comment suggests a deficiency in the interface so we might look at improving the `description` for multivitmains

> Also Calcium seems to be in foods in amounts of 3-5 compared to most vitamins and minerals' 10-20.

> Imo there should be some more sources of Calcium

The outstanding issue is calcium balance

**Comment by cainiaowu** [comment]
Could animal bone be a good source of Calcium? Cooking them with vinegar or something.

**Comment by Rivet-the-Zombie** [comment]
Or some sort of gross homebrew nutritional supplement involving bone meal.

**Comment by KorGgenT** [comment]
this would be fixed by #27781
