### ISSUE TITLE
batch-crafting canned soups yields only one result

### ISSUE THREAD

**Issue by Voker57** [CleverRaven/Cataclysm-DDA#16408]
example: craft 10x woods soup (recipe with tin can), receive only one tin can of woods soup (4)

**Comment by karols146** [comment]
What build ? What system ?

**Comment by Coolthulhu** [comment]
It's quite unlikely that this would act differently on different systems.

The problem is caused by batch code not being updated to work with the canning system.

The code works like this:
* Single result version of `create_result` creates the recipe's result, then puts it inside a container (if any)
* Batch craft version of `create_result` creates result using the single result variant
* Batch craft then continues by checking if the result of the recipe (not of `create_result`) is `count_by_charges` and if it is, it multiplies the charges of the result of `create_result`, otherwise it multiplies the entire result

In the case of a soup can:
* Soup can is created
* The recipe result is soup (not a can), so it is `count_by_charges`
* The final result is a can with soup in it
* Can's charges are multiplied by batch size, but can has 0 charges

**Comment by WizardOfOoo** [comment]
I can confirm this.

Win x64
Build 4766
0.C-13472-gf81d426 (tiles)
