### ISSUE TITLE
Fungal zombies don't retain original drops.

### ISSUE THREAD

**Issue by DanmakuDan** [CleverRaven/Cataclysm-DDA#16405]
This was reported as a bug by a Guest5855 in IRC.

> I was tracking a zombie soldier for a little way, since I couldn't deal with it. It wanders up to a Fungaloid and became a fungal zombie (alright). But when I go to loot it afterwards (after a bear attacked it), it dropped normal items not soldier items.

The main reason for this behavior is that the fungal zombie is a different monster altogether, but the idea is worth some discussion. Should any monster types be modified to retain their original drop properties when they convert?

**Comment by remyroy** [comment]
There is a related discussion on http://smf.cataclysmdda.com/index.php?topic=12464.0

**Comment by pisskop** [comment]
A new fungal zombei could be created for each dropset/profession

**Comment by kevingranade** [comment]
As per the forum discussion, I'd prefer to have the zombie inventory spawn
with the zombie and persist indefinitely, that way you'd naturally get
different inventory sets across mutations.

**Comment by Coolthulhu** [comment]
Some minor problems with inventory pre-spawning:
* Performance of spawning big hordes
* Performance of moving hordes of spawned and "hordified" zombies on the overmap
* Save size
* Zombies don't process their inventories
* Some zombies are too huge for some clothing (hulks drop rags)

Nothing major, just something to note.

Fun fact: you can create an XCom style "suicide bomber" by stuffing your zlave with active bombs. They won't detonate (or even tick) while the zlave is alive. This is quite useless as the zlave won't attack or be attacked by other zeds, though.

**Comment by kevingranade** [comment]
On Apr 28, 2016 3:17 PM, "Coolthulhu" <notifications@github.com> wrote:
>
> Some minor problems with inventory pre
> -spawning:
>
> Performance of spawning big hordes

Real issue.
> Performance of moving hordes of spawned
> and "hordified" zombies on the overmap

Shouldn't be a problem, the objects shouldn't be getting copied around
anyway.

> Save size

Possibly a real problem, could store them as an itype label until
interacted with, now that I think of it that might be worthwhile in general.

> Zombies don't process their inventories
> Some zombies are too huge for some
> clothing (hulks drop rags)

Could have effects applied when zombies transform, leading to "ripped
pants" or similar.

> Fun fact: you can create an XCom style
> "suicide bomber"

Awesome! In theory you could shoot the zlave when there are a lot of
zombies nearby, or trigger a radio bomb in its inventory. I suspect that's
broken :/

**Comment by pisskop** [comment]
a great use is as a sentry.

a bandit/jabby comes by and see a chained up slave.

kills slave.  slave drops bomb

**Comment by i2amroy** [comment]
>Zombies don't process their inventories

This is also a real problem, because fixing it first depends on fixing problem B:
```B) Item processing requires calling iuse.cpp functions, which currently pass around a player pointer```
and that in turn requires solving problem C:
```C) Switching the player pointer to a creature pointer means creating generic versions of a lot of functions/data used that is currently only in existence on the player class```
Last time I was looking at the possibility of doing this the sheer amount of data that would have to be dragged upwards and generalized was the biggest problem I encountered by far, long before you could even *start* to worry about things like efficiency. The alternative to generalization, magically creating an NPC, magically transporting all of the monster's inventory to their inventory, processing it all, and then transporting it back, was incredibly hacky and also wouldn't catch many cases such as items that grant effects/etc. to the person carrying them.

If we want working monster inventories, start by generalizing player class data upwards into the Character and creature classes. :P

**Comment by Coolthulhu** [comment]
> B) Item processing requires calling iuse.cpp functions, which currently pass around a player pointer

We could substitute a fake NPC for that. Or, like with items on map, just pass `g->u` and handle weirdness separately, noting somewhere that the player pointer shouldn't be accessed in iuse functions designed for monsters.

That would be a temporary solution, but would work for most cases.

> The alternative to generalization, magically creating an NPC, magically transporting all of the monster's inventory to their inventory, processing it all, and then transporting it back, was incredibly hacky and also wouldn't catch many cases such as items that grant effects/etc. to the person carrying them.

Monsters don't get most effects from the effects themselves. It would be fine if they just processed their inventory in the same way items lying on the ground are processed.

The fake NPC for processing wouldn't even need to have anything in the inventory, it would only be used as the iuse argument.

**Comment by i2amroy** [comment]
>The fake NPC for processing wouldn't even need to have anything in the inventory, it would only be used as the iuse argument.

This may not work because a fair number of functions (such as ```has_item()```) go player->inventory->item rather than just checking from the item directly, so if the NPC doesn't actually have the item in their inventory then said things will fail to trigger properly.

That said it does look like you guys have done at least some cleanup of the more problematic areas with things like iuse_actors and whatnot in the last handful of months since I last looked at those particular bits of code, so who knows, maybe it'll be manageable enough to actually be feasible to do now. :P

**Comment by Coolthulhu** [comment]
> This may not work because a fair number of functions (such as has_item()) go player->inventory->item rather than just checking from the item directly

Those are quite specific cases. Electric cuffs (which would need to be hardcoded anyway), mp3, acid bomb and jumper cables.

The only real problem I see here would be items that create other items - those would actually not work without copying.

**Comment by I-am-Erk** [comment]
Now that monsters have inventories we may be able to fix this. I don't believe it is fixed yet, but perhaps we can cache the monster inventory and transfer it to the new entity

**Comment by NetSysFire** [comment]
Unfortunately not fixed yet.

**Comment by LyleSY** [comment]
Fixing this in JSON would be trivial. Any problem with that as a stopgap for 0.G?
