### ISSUE TITLE
Discrepancy between npc and player range. Circular distances

### ISSUE THREAD

**Issue by Greiger** [CleverRaven/Cataclysm-DDA#16400]
Version 0.C-13427-gde66270 or O.C 4750.

Not sure which part of this is the bug, With circular distances on players cannot make reach attacks directly diagonal to them.  I've been assuming that was intentional, so this part has been present for many versions if this is the issue.

But I've recently gotten an NPC capable of making reach attacks with a spear and found that they are perfectly capable of making reach attacks directly diagonal, unlike me.  
This does not seem like a huge issue, But it may be problematic when fighting hostile npcs with such weapons, and seems worth reporting.

**Comment by Coolthulhu** [comment]
> With circular distances on players cannot make reach attacks directly diagonal to them.

There was an issue documenting this and I think it was agreed back then that circular distance shouldn't block diagonal reach.

While reach attacks don't really need more buffs (it's not that hard to reposition self around it), having to do it is quite "Nethackish" and wouldn't fit well in DDA. Plus, NPCs actually do need that diagonal reach, since they aren't smart enough to reposition.

Not sure what would be the best fix. We can hack around this by using square distance for reach attacks, but this would break apart if we ever allowed arbitrary range reach attacks. We could allow float ranges, which would be a bit ugly, but only a bit.

**Comment by Greiger** [comment]
I'm no coder, I pretty much just contribute issues and the odd JSON rework, but is it possible to just get ranged attacks (or just reach attacks) to round differently?  

Without looking at the code it seems like the problem lies in the range of a fully diagonal reach attack coming out to two and a fraction of a tile while the reach attack itself only works on something equal or less than two.

I do agree about reach attacks being OP though :)

**Comment by kevingranade** [comment]
The immediate issue is that the limits on player reach attacks are enforced
in the aiming ui. NPCs are using different code which is behaving
differently.
The inability to attack the squares in the corners of the box surrounding
the player is intentional.

**Comment by Leland** [comment]
Note from #19258:

>By pressing F key, you can only attack diagonally adjacent enemy(near you), but pressing Tab you can also attack enemy 1 diagonal tile away, which otherwise is not possible if you press F key.

**Comment by Mooses2k** [comment]
Sounds iike this is functioning as intended?

**Comment by Melodeiro** [comment]
> Sounds iike this is functioning as intended and can be closed?

There is one annoying problem with that: when the enemy is 2 blocks away diagonally, and you press F, i guess, its still trying to aim the enemy, but since maximum reach distance in that case should be 1 block, it aims at the empty tile. Problems starts, when you are dealing with a lot of enemies, and character is trying to aim the enemy, which is out of range, instead of one, who he is able to reach.

Here is a screenshot, where i just pressed F, and nothing more:
![image](https://user-images.githubusercontent.com/2702567/63177474-a33b4d00-c050-11e9-967d-43be97b6a280.png)
Character is able to hit monster with red arrow, but is trying to aim at the one with black, and fails.

Well, TAB hotkey solves that problem, detecting the spear range properly, and is anyway doing job much better at "spamming" attack, the only problem, i didn't noticed that hotkey first. And you actually can't attack enemies 2 tiles away using TAB hotkey, at least with naginata, so at least this one is fixed. But F is not working properly.

**Comment by kevingranade** [comment]
Picking up on what Coolthulu said, it's possible we can choose a specific
reach value that will consistently do the right thing at these close ranges
and also at longer ranges, something like adding 0.5 to the reach distance
should do it.
The inconsistency problem is more annoying, we need to track down all the
places that determine reach range and have them all the same underlying
range determining code.
