### ISSUE TITLE
Increase natural nightvision both for zeds and player

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#16415]
Night vision trait is pretty much mandatory, but once you have it, all darkness becomes a great tactical advantage. Nights are very dangerous without NV, but with NV are much easier than days.

Without NV, the player is effectively blind in the darkness, which makes exploration tedious. While it makes sense that the bottom of the mine, dark lab or a weed basement is totally dark, lack of map memory makes it more annoying than it should be. And above ground nights shouldn't be as dark as that most of the time.
I'd bump the base NV to 2 tiles range. Or possibly do something experimental and allow seeing terrain for 2 tiles, but not items or critters (to avoid buffing spears even that small bit).

IMO the NV trait should only give the player the same level of NV that basic (non-night-specialized) zombies have. That is, if you see a zombie with NV, it sees you too.
After all, zombies are supposed to be spooky and nights being safe during zombie apocalypse is counterintuitive and not "fun". Worse: it allows a non-mutated Joe Average+1 (Joe Average who ate a lot of carrots in his childhood) to take down a hulk with just a 9mm pistol and a pouch of ammo for it, without risking getting smashed.

Though I'm not sure whether it is a better idea to buff zed NV or nerf the NV trait to zed NV range.

**Comment by codemime** [comment]
> Or possibly do something experimental and allow seeing terrain for 2 tiles, but not items or critters (to avoid buffing spears even that small bit).

That's counterintuitive: zombies and items appearing from nowhere.

**Comment by RogueYun** [comment]
Again I felt like including my two cents worth... Please forgive me, I tend to feel like chiming in even though I'm sure I'm not qualified to chime in.

I agree about the base NV needing to be increased ever so slightly.  Perhaps the reach/thowing attacks take a severe accuracy loss in darkness without the appropriate equipment/lighting? Maybe the PC only sees forms of things and not what they are specifically until they are right next to it? It would give the player one more reason to use a flashlight.

I'm sure I'll incite some criticism for this, but I think we need to up the cost of the Night Vision trait as well. I believe I would still shell out trait points for it even if it cost 6 or 8 points. It is definitely one of the most important traits (if not the most important) why not make it cost as much as it's value?

Good luck with finding a good balance for this!

**Comment by Rod-Serling** [comment]
I disagree with the zombie changes.

The reason Night Vision is manditory is not only because it's stupid hard to find your way without it, but because players need some kind of advantage at some point over the zombies. If we can't avoid them at night, and we can't avoid them at day, then new characters are going to get smashed faster than before.

I would suggest removing "Night Vision" trait completely. Keep Improved Night Vision as the first "Night Vision mutation". Buff the player's default night sight, and keep it at least slightly higher than base zombie night sight.

Otherwise, when you're night raiding, you're going to take one wrong step, and suddenly there's a shriker zombie yelling bringing in more zombies from all sides.

**Comment by Coolthulhu** [comment]
> If we can't avoid them at night

Huge running speed that zombies can't match is enough to avoid all early zombies.

> keep it at least slightly higher than base zombie night sight.

No need for that. Base zombies are really weak, so there is no need to also keep them blind.

> Otherwise, when you're night raiding, you're going to take one wrong step, and suddenly there's a shriker zombie yelling bringing in more zombies from all sides.

You can always do the right thing and run. The only zombie type you can't outrun is the predator, which already has good night vision.

**Comment by Rod-Serling** [comment]
You're assuming a pain-free, full, slaked character. When the chips are down a bit, you still need a way to recover. 

A little bit of hunger, thirst, or pain and suddenly the base zombies are just as fast as you. You can run, sure, but you're going to wear yourself out quick and still be no better off than before.

I think the night time difficulty is balanced well right now. It's generally very dark and night raids for early characters aren't all that safe. Nights are supposed to be easier than days, the NPC's even say so in their missions. I don't think there's a balance issue here that needs to be addressed.

**Comment by Coolthulhu** [comment]
> You're assuming a pain-free, full, slaked character.

You shouldn't be night raiding when dying from pain, you should be holed up underground until you can sort that out. Unless you're starving and parched, you can outrun most zombies.

> It's generally very dark and night raids for early characters aren't all that safe.

Only due to overpowered zombies occasionally popping up. Spitters and hulks wouldn't get a significant buff here, only the weak crap.

> Nights are supposed to be easier than days

They would still be and significantly so, just a bit less significantly. You'd still avoid shockers, hordes, being chased for more than few steps. You could still distract an entire incoming horde by having some of them bang a bus. Hordes would still split up due to some of them getting mad at walls/trees/trashcans/cars.

For night raids to be harder than days, it would take strong zeds to have better NV than player.

**Comment by cainiaowu** [comment]
>Without NV, the player is effectively blind in the darkness, which makes exploration tedious.

So could we have the option like the one in #11808?

**Comment by Hague** [comment]
Night vision isn't even necessary. Blinkering a flashlight on and off is just as good as night vision. Sure, it uses batteries but if you immediately deactivate your flashlight the zombies don't move on you. You can still fire into the darkness and hit a target, just remember where the enemy was at and fire at the tile. Works wonders with a quiet weapons. Even if they do notice you, you can use this to good effect by drawing enemies to a location and doubling back (works great with less scent or by doubling back through doors or buildings. Though night vision could stand to be improved on bright-moon-clear-weather nights. I might have good night vision personally but seeing during a clear night with a half-moon isn't as difficult as it is in Cataclysm.

**Comment by kevingranade** [comment]
Sounds reasonable, zombies should have a little edge in the dark, but there
is room to make  default vision at night a little nicer without encroaching
that territory. Equal vision at night with the basic trait is a nice
balance point.
Are you planning on adjusting the other tiers of night vision too?

The player has a massive advantage in vision range over zombies during the
day, this is when the player is intended to have an advantage.  The night
vision/night raiding advantage was not intended and I have no problem
removing it.

**Comment by Coolthulhu** [comment]
> Are you planning on adjusting the other tiers of night vision too?

Didn't think about it, but it could help. High night vision is good enough to drive at moderate speed, which doesn't sound sane to me.

> Blinkering a flashlight on and off is just as good as night vision.

That sounds like a problem. It's obviously an exploit and I'm not sure how to best fix that.

**Comment by Greiger** [comment]
Perhaps adding an additional light level of 'pitch black' or something to that effect?  

I recently experienced a blackout at night and inside it's so dark you literally can't see your hand in front of your face, no matter how long you wait for your eyes to adjust.  But once you get outside or near a window you can see fairly well.  It's still dark, too dark to read by, but I could see across the yard and make out my cat sitting on the back fence.
So by that meaning you'd be able to see half a dozen or so tiles when outside when there's even a sliver of moon out without any special night vision.  But during a new moon, or if you are inside at night vision is reduced to the current very dark levels.

Also pardon if I'm wrong but don't zombies already dynamically adjust their vision based on light level?  I can get a lot closer to a zombie during dusk or dawn than I can during the day, but not as close as I can at midnight.

**Comment by kevingranade** [comment]
>> Blinkering a flashlight on and off is just as
>> good as night vision.
>
> That sounds like a problem. It's obviously an
> exploit and I'm not sure how to best fix that.

The source of this is that you can turn on the flashlight (refreshes your
vision, allows you to look around, etc), then turn it off before your turn
ends, therefore no monster gets a chance to see you.

Simple fix: when you activate a light source, you get an effect
"illuminated" that lasts until your next turn, monsters can see players or
NPCs with this effect regardless of current light level. Alternately the
player counts as still holding the active light source.
Unfortunately this WILL lead to erroneous bug reports about the exploit no
longer working.

Larger fix: increase turn granularity such that any action taken will end
your turn (eliminates all instances of this issue).

**Comment by Coolthulhu** [comment]
> Larger fix: increase turn granularity such that any action taken will end your turn (eliminates all instances of this issue).

It doesn't need turn granularity, we could have item transforms take full turn even at current granularity. Transforming an item should probably end the turn by default.

The problem with that would be finding all the cases where an item loses illumination, since not all cases use the transform actor.

> Simple fix: when you activate a light source, you get an effect "illuminated" that lasts until your next turn

Though about it, but it has one small problem: the effect would have to last a whole turn and stay on the player who moves. This would result in player being visible even after moving. That doesn't sound like that much of a problem, though - certainly less than flashing a flashlight for free vision.

> Unfortunately this WILL lead to erroneous bug reports about the exploit no longer working.

The status could leave some light around the player and be explicitly mentioned in character sheet. Say, atomic lamp tier radius.

**Comment by kevingranade** [comment]
On Apr 28, 2016 3:02 PM, "Coolthulhu" <notifications@github.com> wrote:
>>
>> Larger fix: increase turn granularity such that
>> any action taken will end your turn
>> (eliminates all instances of this issue).
>
> It doesn't need turn granularity, we could have
> item transforms take full turn even at current
> granularity. Transforming an item should
> probably end the turn by default.

If the granularity was increased, sure, but expending 6 seconds to flick on
a flashlight seems extreme.

>> Simple fix: when you activate a light source,
>> you get an effect "illuminated" that lasts
>> until your next turn
>
> Though about it, but it has one small problem:
> the effect would have to last a whole turn and
> stay on the player who moves. This would
> result in player being visible even after
> moving.  That doesn't sound like that much
> of a problem, though - certainly less than
> flashing a flashlight for free vision.

I have no problem with that outcome.

>> Unfortunately this WILL lead to erroneous
>> bug reports about the exploit no longer
>> working.
>
> The status could leave some light around the
> player and be explicitly mentioned in
> character sheet. Say, atomic lamp tier radius.

That's why I suggested it providing a light effect, though I like your idea
of it being a dimmer light than the original source.

**Comment by pisskop** [comment]
my two cents is to make the moon/statlight and weather conditions affect visibility more.  Without human light pollution it should be much easier to do

**Comment by AdonaiJr** [comment]
I'm aware that there's this night-raids strategy you guys talk about. Just to make my point, I'm a "daylight" player. I often find myself "bored" at some shelter, making a fire somewhere, cooking or reading a little while it's very dark. I don't use at all the night vision perk, maybe it explains why I gave up nor gave much of a chance to moving around while it's dark. Though I like when it's clear at night and I can move around.

**Comment by Hague** [comment]
On the subject of lights and such. Zombies at night time do not respond to moving vehicle lights. They cast spotlight which can't illuminate the player from behind. A flashlight by all rights should be able to do the same thing. The light cast by a real flashlight wouldn't illuminate the holder and anything directly viewing it would suffer glare or flare effects. The exploit currently is just a cheap way to emulate the way a flashlight would really work. Though, I do like the idea of specific zombie types being interested in any light source they can see. Too bad it would probably lead to zombies inadvertently smashing important consoles or something.

Perhaps a simulated 'f'ire function for a wielded flashlight that allows the user to target a specific cell within x-tiles. That would set a spotlight angle for illumination on tiles similar to the headlight on a vehicle. It will hold that angle until it's changed or the flashlight is put away or turned off.

**Comment by pisskop** [comment]
Im more of the opinion that the zeds _should_ respond to the moving lights of a car.

**Comment by kevingranade** [comment]
Agreed, their disinterest in headlights is the bug, having flashlight
welders be invisible to zombies is completely unworkable.

**Comment by Hague** [comment]
Okay, you're standing in an open field. It is pitch black night of a new moon with cloudy weather. For a split second a light blinks on and off. Which direction did that light come from? If you were facing the other direction, you were unlikely to ever spot the exact location of that light. Unfortunately, all zombies within range would spot it, identify it as a valid target for murder in the blink of an eye and remember the exact location and move to it with 100% assurance in what they saw. Flare is a real thing and it would affect a creature with already terrible vision even worse. If anything, strobing lights, high-powered spotlights, and other flare effects should be disturbing to zombies, a creature wracked with half-destroyed, half-integrated sensory structures. I don't think clicking a flashlight on and off merits the level of response from zeds that carrying a fully-uncovered lantern or torch does.

I mean by this regard, zombies should follow and attack a laser designator you paint on a wall despite it not looking, moving or smelling like valid prey and be easily lead away from you or into a trap. The whole zombie apocalypse could have been avoided by corralling all the zombies with cat toys since they have to move towards any moving lightsource they see.

**Comment by Coolthulhu** [comment]
> I don't think clicking a flashlight on and off merits the level of response from zeds that carrying a fully-uncovered lantern or torch does.

Reminds me of that bad joke that goes kinda like:
> How much is a drop of gas?
> A drop? Free
> A tank of drops of gas, please

Same deal here. So there are two options left:
* Blinking a flashlight doesn't allow neither the player nor the zombies to see
* Blinking a flashlight allows both the player and the zombies to see

We can handwave this as zombies using the same sense that immediately allows them to tell the living humans apart from fresh zombies. That will certainly be a better solution than allowing flashlight rave to bypass all zombie senses while allowing the player to see everything just fine.

**Comment by kevingranade** [comment]
On May 1, 2016 12:27 AM, "Hague" <notifications@github.com> wrote:
>
> Okay, you're standing in an open field. It is
> pitch black night of a new moon with cloudy
> weather. For a split second a light blinks on
> and off. Which direction did that light come
> from?

Same scenario, but you're holding the light, list every feature within 20
feet.  If the light was on long enough for you to navigate, it was on long
enough for you to be seen. You still have a huge advantage because you're
in control of when the light turns on and off.

We could go the other way and not allow the player to see things revealed
by activating a light source, but the outcome would be the same and the ui
would be more annoying.

**Comment by pisskop** [comment]
I do wish that zombies could see flashlights.

Actually.  Id like to add a usetime for flashlights

**Comment by Hague** [comment]
Well that same level of unrealistic awareness applies to everything a player can see, even with the lights on, a 6 second frame of time and I can pick out ever object within visual range, it's level of damage and so on. The only way to really make any of that fair is to create a system of perception checks or visual thresholds based on factors: proximity to cover, size of the units/objects, color (bright colors), motion, and so on. Imagine you're standing some distance away, and there's a small animal on the opposite side of a bush, instead of immediately spotting the animal, you would get a motion icon similar to noise icons and/or message indication (You see something move to the <direction>) Only until you get within a certain range threshold can you truly identify the target. Same with objects "You see some thing(s) on the <terrain>" Objects that are high in volume are easier to spot at a distance, having a higher profile. Some objects should be visible on the surface over buildings. Creatures that would realistically tower over buildings. Profile would apply to players too, running makes you more visually obvious increasing the range at which zombies can spot you and the player forcing a shambling gait. Flicking a flashlight on and off at night would give you a high profile temporarily but wouldn't necessarily attract all the zombies within direct visual range, only the ones who were close enough to pass the profile threshold and gain interest in the flash of light they saw. Could lead to other light sources that generate less profile (infrared or UV filter lenses, specialized emitters and so on) 

Also, a much simpler nerf would be a player getting a movement penalty and a stumbling chance for running on flat or rough terrain. Stumbling is loud and can be painful.

**Comment by kevingranade** [comment]
I'd like to add some amount of perception checks like you outline, but I
disagree that it is required for fairness.
It will be totally fair for monsters to be able to see the player when the
player can see the monster.

**Comment by Skidborg** [comment]
Having night vision range scale with perception would add some incentive to put points into it. It's still a dumpy stat.  And it would give another strategic decision to make at character creation.  You want to evade zombies at night? Then you'll be weaker in other ways if you screw up and let them see you at all.

The only issue I see with zombies attacking flashlight flicking is that then they should be attacking /any/ light source at night, human held or not.  A person holding a flashlight is mostly invisible behind the light's glare.  Of course, that would expand the distraction and traps game, so I'm not against it, it just needs to be made consistent.  How do zombies deal with car headlights? Fires? Dangling shiny things in the sun?

**Comment by codemime** [comment]
> The only issue I see with zombies attacking flashlight flicking is that then they should be attacking /any/ light source at night, human held or not.
How do zombies deal with car headlights? Fires? Dangling shiny things in the sun?

Zombies should react not to the light sources themselves, but to significant changing of their intensity. It's not that hard to model.

**Comment by Coolthulhu** [comment]
> The only issue I see with zombies attacking flashlight flicking is that then they should be attacking /any/ light source at night, human held or not.

No, they can be optimized to detect living beings. Specialized neural structures act a lot faster than ones that need to recognize everything.
Zombies are blind to light sources, light intensity, traps, fire, obstacles, other zombies, vehicles - pretty much everything that isn't prey. This means they only really need to look for specific features. Such optimization already happens in nature (for example, star-nosed mole which detects its prey barely above the theoretical minimum time for neurons to achieve, though using something closer to echolocation than sight) so we can just explain it as zombies being killing machines instead of making them hate cars even more than they do now.

**Comment by Treah** [comment]
I find that even with the NV trait on my char, zombies seam to have the same visual range with a char with improved NV.... This becomes very problematic for instance with Bruts in enclosed spaces. ( such as with the Prison escape scenario ) Playing that without improved NV is pretty much impossible since there are at least 3 or 6 brutes there and they 1. faster then the player and 2. can see seemingly farther then the player even with improved NV. Some people have commented on this in IRC saying its sound or smell but this just seams not the case since Z can find you around corners even when sitting completely still.

**Comment by Coolthulhu** [comment]
Prison scenario isn't supposed to be balanced in any way.

**Comment by Treah** [comment]
I was only using that as an example. I do find they seam to have a higher then normal chance of locating me. Maybe its just improved AI

**Comment by Coolthulhu** [comment]
Scentmap had a major bug that resulted in zeds stumbling a lot instead of beelining for the player. It was fixed.

**Comment by pisskop** [comment]
I didnt think it was a bad thing that they sometimes 'didnt notice you'.  It added flavor to the idea that they were dead/mindless/unholy.  They were shells, imperfect shells of former humans worn like a suit.

**Comment by Skidborg** [comment]
> No, they can be optimized to detect living beings. Specialized neural structures act a lot faster than ones that need to recognize everything.

Except that flashlights aren't a feature of living beings.  They're an artificial tools, and as likely to be attached to a car or a robot as a person.  Magic detection of a human-held light is above the level of a creature that'll spend an hour attacking a car because they heard it creak.

**Comment by Coolthulhu** [comment]
Flashlights don't make the holder disappear.

**Comment by Zireael07** [comment]
Who's saying the flashlights make you disappear? O.o

**Comment by pisskop** [comment]
I would, again, like to point out that the zombies dont need to even see a player.  They see a stimulus, and they go to the shiney and beat it up.

Like a crow.  A dead, rotting, vicious crow.

**Comment by Coolthulhu** [comment]
> Who's saying the flashlights make you disappear?

Implied by @Skidborg who argued that zombies can't be optimized to detect living beings (or that this optimization doesn't work for flashlight-holding beings) because they aren't optimized to recognize flashlights.

**Comment by Skidborg** [comment]
In real life Flashlights do not illuminate the holder.  When contrasted with the beam blinding everyone downrange, it's usually more difficult to discern the flashlight holder than if there was no flashlight at all. 

It would attract attention and probably running zombies.  Not denying that.  I just expect some reaction to other lights with unclear sources as well.  

I could expect hunters and other specialized zombies to be able to tell the difference with other senses, but the baseline zombie is just a walking corpse.  Superhuman abilities should appear /after/ evolution.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
