### ISSUE TITLE
Quick rag crafting time

### ISSUE THREAD

**Issue by rriegs** [CleverRaven/Cataclysm-DDA#16420]
Edit: Long rag disassembly time is intentional and intuitive; it should be hard (if not impossible) to pick rags apart into useful threads.  I've changed this issue to instead ask whether being able to craft a rag from thread in just 6 minutes is reasonable; see below.

Original text:

Disassembling a rag into thread takes 60 minutes (comparable to disassembling an electronic device), even though knitting one takes just 6 minutes.  Disassembly time should probably be 6 minutes as well.

This affects very-early-game balance because cut up curtains or clothing may be the only readily available source of thread to a minimally skilled character.  Having to wait an hour to reload one's needle can put one in a dangerous situation with regard to hunger, thirst, or the encroaching horde.

**Comment by Rivet-the-Zombie** [comment]
You're picking a piece of cloth into individual threads with your fingers. It's meant to take a long time compared to unravelling a piece of string.

**Comment by rriegs** [comment]
I can understand that explanation, but then how is it possible to reassemble the same cloth in just 1/10th the time?  Perhaps knitting a rag should take longer?

**Comment by kevingranade** [comment]
Please supply a source indicating how long it takes to pick apart or
unravel rags and then make thread out if it.
From a relatively brief search, it looks like rags are not normally picked
apart by hand anyway, though there are various industrial devices that do
so.
I'm not at all sure knitting thread into rag is a reasonable thing to do,
so comparing it to that isn't particularly helpful.
Your argument about balance boils down to, "it's hard to do clothing repair
very early in the game", which is working as intended.

**Comment by illi-kun** [comment]
I'm not sure that threads obtained via rag disasembling is useful / acceptable for further use, so a possible way to solve this issue is simply removing the discussed receipt.

**Comment by rriegs** [comment]
I agree that clothing repair should be hard in the very early game (unless you're a Tailor :smiley:).  I also realize I've neglected another important (and much quicker) source of thread in the early game: curtain draw strings.

Eliminating the disassembly is not unreasonable.  Threads and their equivalents would still be readily available from strings, hunting, cattails, and spun cotton.  Plus, it would remove a potential {not thread} -> garment -> rags -> threads pathway.

**Comment by rriegs** [comment]
On a related note, slow rag disassembly means that 'B'utcher -> 'd'isassemble All is bad news if you're standing on a pile of zombie loot.

**Comment by pisskop** [comment]
While the option to disassemble rags amoungst other loot is annoying, longstring are readily available and take 30 minutes to break down into 300 thread.  theres zero reason for rags to be convenient.

**Comment by Rivet-the-Zombie** [comment]
Exactly; they're meant to be a source of thread when there's no better option available, not a convenience.

**Comment by rriegs** [comment]
You've all convinced me.  I'll change the title of this issue to reflect the suspiciously quick ability to knit rags from thread.

**Comment by rriegs** [comment]
For comparison, the only other recipes that can be crafted from thread alone are string, long string, knit scarf, and long knit scarf.  The scarves take 40 and 60 minutes to craft and can be cut into up to 3 and 5 rags, respectively.  That suggests a thread-to-rag production time of about 12 minutes, which is not far from the existing 6.

Accordingly, I suppose there is no need for change.  I was just surprised to see rag disassembly take so much longer than crafting, but then #16421 would help with that.

**Comment by pisskop** [comment]
A _lot_ of clothing doesnt make sense timewise.

You can sew a whole duster together from a bunch of rags in 30 minutes.  Maybe thats why it breaks so quickly though.

I think that any attempt to tackle an minor, incredibly common thing like rags, should also include a complete reworking of sewing and possibly crafting in general

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
