### ISSUE TITLE
high-recoil firing can make you hit yourself

### ISSUE THREAD

**Issue by Voker57** [CleverRaven/Cataclysm-DDA#16513]
reproduce: get m60, fire full-auto without waiting for recoil, watch your character shred themselves.

**Comment by kevingranade** [comment]
The problem is that the code handling misses picks a random spot near the
target as the aim point, it should instead pick a random angle relative to
the player, this would guarantee not targeting the player and also make
misses scale properly with distance, and if a 3D angle is chosen, also
handle fiuring onto the air and at the ground for really poor shots.
A more extreme change would be to model where the gun is aimed at all
times, then recoil could have useful biases like pushing the player's aim
into the air instead of just unsettling it.
The more trivial change of adding some bounds checking to the miss code so
it doesn't target the player would also be ok.

**Comment by Coolthulhu** [comment]
> it should instead pick a random angle relative to the player

This would also fix the issue with player shooting backwards or NPCs being more likely to friendly-fire when near player.

**Comment by Rivet-the-Zombie** [comment]
I can see the character ending up with a seriously sore shoulder after firing without proper stance, but how in the heck are they going to completely turn a three and a half foot long, twenty-two pound rifle around to shoot themselves in the process?

**Comment by Hague** [comment]
Well, you can shoot yourself with a weapon if you fire at the ground. The game doesn't simulate ricochets (I have a friend who was hit in the back of the leg when a shot fired forward ricocheted backwards, deflected off another surface behind them and hit him in the calf. Barely hurt him, however, most of the energy was gone) but if it did you could potentially hit yourself with bullets if you dropped the barrel to a certain angle while still pulling the trigger. But with a weapon as large as an LMG I don't think that's possible.
