### ISSUE TITLE
Ammo Storage for primitive ranged Weapons.

### ISSUE THREAD

**Issue by Shudokai** [CleverRaven/Cataclysm-DDA#16537]
Early-Game ranged weapons put the user at unnecessary risk when fired because they fire and reload in a single motion, a good example for this is the sling and slingshot, while they are decent to hunt small game and based on damage values strong enough to fend off the weaker undead their reload mechanics make them incredibly risky to use. The slingshot for example should be a really easy to use early game weapon and with sone efford can turn into a deadly early to midgame ranged weapon but with 15 tiles range it is really hard to fire more than one shot before the enemy is gnawing your face off.

My suggestion would be ammo pouches for stuff like pebbles and other small non-gunpowder ammo types like darts and in addition to this entirely missing item maybe a new mod for bows and crossbows, namely an arrow holder that acts like a quiver attached to the weapon.

The pouches should not be any harder to make than simple pouches to the survivor and arrow holder attachements shouldn't be any harder to make than bow sights, arrow rests or bow stabilizers.

http://blog.thecrossbowstore.com/wp-content/uploads/2013/04/Stryker380.jpg

**Comment by Hague** [comment]
There are already quivers in the game for arrows and this seems unnecessary. You would still need to place the stone in the thong of the sling or slingshot even if you had a pouch in your hand with the stones. This would make sense if the game models extra time from reloading from your inventory over a ready container (like a quiver) but if it doesn't there doesn't seem to be any point to this. A magazine for pebbles doesn't make much sense since you're still doing the hand-loading yourself.

**Comment by Shudokai** [comment]
With the addition of magazines, bandoliers etc. to the experimental it does make a difference in reload time, reloading a bow from your inventory takes more time than reloading it from a quiver and swapping a magazine from an ammo pouch takes less time than swapping it from your inventory.

Thats why I even thought of ammo pouches for miscelaneous weapons.

And I am talking about quivers to be attached to the Bow or Crossbow so you don't have the heavy encumbrance on your torso when you're using a bow alongside a backpack or belt. Those attached quivers should come with a disadvantage like increased dispersion and weight and less capacity but with the same quick reload as a regular quiver.

I am pretty sure since the magazine stuff is in the experimental the slingshot and sling take ages to fire, that never happened before, those weapons fired at a reasonable speed but now a single shot is enough for a regular zombie to move 4-6 tiles if not more.

**Comment by AppleConnoiseur** [comment]
At the same time making these reload-and-shoot weapons less aggravating to use if you got multiplie ammo types in the inventory. I.e pebbles, marbles and bearings.
Just use the same type you fire until you press the reload key instead of having to pick Every. Damn. Time.

Would really love more bandoliers and maybe even CLIPS for shotgun shells and the like which you can put in pouches for easier reloading. Speedloaders for revolvers would be convenient for revolvers as well.
Guess you could in theory make clips for every weapon. All they are is metal strips that are bended in specific ways in order to keep cartridges _clipped_ onto them.

**Comment by Leland** [comment]
Old suggestion and no recent discussion here. Closing. Feel free to let me know if you want it reopened.
