### ISSUE TITLE
Vitamin deficiencies time out and reapply constantly

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#16549]
Expected:
Vitamin deficiency message is printed once, when the deficiency is gained, and only repeated if it is cured and regained

What happens:
Vitamin deficiency effect times out, prints "you cured your deficiency" message, then is immediately reapplied with "you are now deficient" message

**Comment by Rivet-the-Zombie** [comment]
Perhaps it's getting wonky as it attempts to change level of severity?

**Comment by i2amroy** [comment]
>Perhaps it's getting wonky as it attempts to change level of severity?
The effects themselves don't have levels of severity, and the other math looks right from my end, though I'm still fiddling with a few things. That said an easier way to address the problem would just be to change it so that rather than trying to synchronize duration+1 with vitamin_mod checks it simply sets the vitamin deficiency effects to a duration of 1 with permanency. Then simply have each check either add (if it's not already there) the effect or delete it as needed without worrying about timers running out.

**Comment by Asmageddon** [comment]
There is the exact same problem with metabolic imbalance right now.
