### ISSUE TITLE
Stats reporter

### ISSUE THREAD

**Issue by mugling** [CleverRaven/Cataclysm-DDA#16578]
It would be very helpful to know how popular certain items and play styles were. For example as part of balancing #16577 it would be helpful to know what foodstuffs were commonly eaten and which deficiencies resulted.

One option would be to allow uploading of expanded memorial files (possibly to Amazon S3 or an equivalent). This obviously should be opt-in and inactive by default but I would be surprised if many players objected to doing so.

Comments both as to the idea itself and potential implementations?

**Comment by 321nick** [comment]
this idea sounds brilliant, id totally love too see it implimented

**Comment by mutt3x** [comment]
Overall i think its fine as long it is an option...

Hmmm yes yes. If you remove the debug menu, add somekind of checksum to the log. Implement certain type of scoring for days/time survived, zombies killed, quests and maybe even food eaten... maybe even disable saving.
>CDDA tournament edition

its a dream
!!! someday

**Comment by BorkBorkGoesTheCode** [comment]
I oppose this. It resembles spyware.

**Comment by cainiaowu** [comment]
> I oppose this. It resembles spyware.

How does collecting IN-GAME information resemble spyware?
And you could turn it off(which is by default), so it is clearly not spyware.

I fully support this implementation.

**Comment by 321nick** [comment]
`I oppose this. It resembles spyware`
how ? i mean, i dont think just some statistics that the devs (which is everyone who is willing too make pull requests)  can see and be able too easily know what is OP, what is under-powered, what is bugged, etc can be considered spyware, and its not like this is knowledge that is personal or anything.


also, i think it should be on by default so people who dont know its there accidentally have it off for most of the time they play, leading too it being left un-used.

**Comment by nanovad** [comment]
I don't think it should be an in-game option. Perhaps a place where you could upload saves to instead, so that more conscious intervention is needed. It would unnerve me (personally) if the game I were playing suddenly had capability to upload my save files to somewhere random for stats.

**Comment by Labtop-215** [comment]
Ehh...  As long as you are upfront about what this option gathers, and you make sure that it is off and is not activated by accident, then gathering the information is fine.

I say this because I have had experience with Samsung Smart TV's that send information they find on the network, over the internet unencrypted, sometimes without giving people the option to opt out.

As long as you don't pull something like that, people probably wont mind.

**Comment by mugling** [comment]
> I oppose this. It resembles spyware

Not by any reasonable definition of that word

> also, i think it should be on by default

Many (most?) users are receiving automatic updates via @remyroy's application so this wouldn't be fair. Users should therefore be asked to explicitly opt-in or opt-out.

> Perhaps a place where you could upload saves instead, so that more conscious intervention is needed

Both impractical and likely expensive to store and process all of that data. Also collects far more information than is reasonably required

> It would unnerve me (personally) if the game I were playing suddenly had capability to upload my save files to somewhere random for stats.

It wouldn't concern me about the data being sent but I'd be very interested why all of a sudden the binary wanted to open a socket in the first place.

> As long as you are upfront about what this option gather

We need to first define what is useful to know.

I'd like to propose that the world creation option 'Submit game statistic on save' with three options (Yes, No and Prompt). The default would be prompt. Players therefore become aware of the option immediately and have the option to enable the functionality on a case-by-case basis when starting new games.

For games with stat submission enables condensed statistics would be submitted (probably via S3) upon either game loading/saving (probably the former).

**Comment by Labtop-215** [comment]
> We need to first define what is useful to know.
It would be useful to know what information the program gathers, and how the information is transmitted.

So for instance, if the program gathers names of survivors and weather or not the name is randomly generated, then it would be nice to know, so that I don't put my real name in as the name of the character I'm playing as.

Does it gather information about the type and version of the operating system it is played on?  That would be useful in determining weather I would want to opt in or not.

Is the connection to the stats server encrypted, or open (I'm not sure if S3 is encrypted or not, I'll do some reading on it now though)?

Essentially, I and I think anybody else who would want to know what a stat gathering program does would want to know what I can do, and what I can't do, in order to maintain my privacy if I chose to enable this option.

**Comment by mugling** [comment]
> So for instance, if the program gathers names of survivors and weather or not the name is randomly generated, then it would be nice to know, so that I don't put my real name in as the name of the character I'm playing as.

A good point. It's fair to publish a list of what would be collected. There's no useful value to be gained from the player data.

> Does it gather information about the type and version of the operating system it is played on?

That, along with (game) version information would be exceptionally useful

> is the connection to the stats server encrypted, or open

Anonymous usage data should be accessible to all so I don't see a need to provide encryption?

**Comment by Labtop-215** [comment]
> That, along with (game) version information would be exceptionally useful

> Anonymous usage data should be accessible to all so I don't see a need to provide encryption?

That could be an issue for some people.  Once the data reaches it's destination it's harmless, but packet sniffing software is freely available online, and has many legitimate uses.  And also some not so legitimate uses.  However, people could, if they wanted to crack into your system, use information about that users operating system to engineer a break in attempt.

That's why many people want that information sent encrypted over the internet.  The information doesn't have to remain encrypted once it reaches it's destination, but before then, that represents a security risk.  If I were you, I would strongly consider getting the program to send that information through HTTPS or SSL for that reason.

You don't have to though.  As long as you tell people what information is being gathered, and that it is being sent open and clear over the internet, people can then make an informed decision for themselves if they want to do that or not.

**Comment by mugling** [comment]
For our purposes SSL wouldn't add any additional costs so I've no objection to such a requirement if it was a factor for anyone.

**Comment by kevingranade** [comment]
There is an alternative that meets the original goal of in-game usage
information (actions taken, survival times, items used, enemies
encountered), which is to record such metrics locally, but host a game
instance on a server people can log into to play.  It's a totally different
set of tradeoffs, just thought I'd throw it out there.

I'd want any such metrics to be annonymized as well as we can manage, even
something like login times could potentially get someone in trouble, so I'd
prefer to make it as difficult as possible to tie a record to a user or
remote ip.

It being opt-in is a given.

**Comment by mugling** [comment]
@kevingranade are you thinking similar to DCSS webtiles?

**Comment by mugling** [comment]
Ok, lets talk semantics:

* ZeroMQ with curve22519. Minimal dependencies (libsodium). Cross-platform.

* Client generates 128-bit random UUID for each world

* Optionally send the player name (to allow high scores etc). Default is not to send (anonymous).

* Events are queued and submitted to remote server

* Remote server exposes results (exclude UUID) via a web interface which includes a minimal scoreboard

For each event:

* Game turn
* Skill levels
* Player stats (hp, hunger, effects etc)
* Worn items/wielded weapon

Collected events:

* Monster kills
* Food/drink consumption
* Achievements/memorial entries

**Comment by macrosblackd** [comment]
If it isn't too late, and options might be to use one of the many free metrics solutions that offer a REST api for handling the server side.

The main one I've seen mentioned a lot is http://www.gameanalytics.com/

**Comment by mugling** [comment]
HTTP is excessive considering the client is never interested in the servers reply
