### ISSUE TITLE
Add Recipes for Tents

### ISSUE THREAD

**Issue by Hague** [CleverRaven/Cataclysm-DDA#16605]
Noticed a book called "Pitching a Tent" that didn't contain recipes for a tent. Turns out you cannot craft tents or large tents at all. Perhaps these should be added. A recipe to turn a damaged tent into a working tent would be nice as well.

**Comment by Headjack** [comment]
I thought there were hide-and-stick "shelters" that were like this, at least a while back, along with repairing.

**Comment by Labtop-215** [comment]
There are, but Hauge wants a crafting recipe for the actual tent item.

The issue I have with this is that it would mean there is very little difference between the shelter kit and the tent then, essentially just a color scheme and a material composition difference between the tent and shelter kit.

I'm not actually opposed to this idea, but I think having items in the game that are better than what can be crafted, and being unable to craft those items is what makes them stand out as luxuries, instead of just stuff.

Maybe it would be nice to be able to track the damage to a tent via it's items health bar though, and allow for the item to be repaired via soldering items and fabrication skill.

**Comment by Rivet-the-Zombie** [comment]
Not crafting factory-made tents, but this part would be great:

>A recipe to turn a damaged tent into a working tent would be nice as well.

**Comment by Hague** [comment]
What is a manufactured tent? People have made and used tents for centuries before they had nylon and other synthetic fibers. Here's a sample recipe:

X number of sheets
X number of units of wax, paraffin, or spray starch or other water repellent. 
2 long ropes
8 heavy sticks or 4 pipes
4 wooden stakes or 4 spikes

Tools would be a sewing kit (40 charges) and a cutting tool.
Requires Survival 5 and Tailoring 6 (spitballing here)

Alternate recipe is as above but replace sheets with tarpaulin and remove the waterproofing requirement.

It should be noted that in real-life even with a high quality synthetic fabric for a tent you still need to consistently treat the exterior with a waterproofing aerosol, though spray starch for your laundry works just fine.

**Comment by Leland** [comment]
Closing - old suggestion and no movement in a year. Feel free to reopen or create a new issue if there's still interest.
