### ISSUE TITLE
Cell phones don't require batteries

### ISSUE THREAD

**Issue by busterbogheart** [CleverRaven/Cataclysm-DDA#16634]
Given that they tell time and can be alarm clocks i feel like im cheating to use it.

**Comment by Rivet-the-Zombie** [comment]
Watches don't require batteries either, and they do both of those things.

**Comment by busterbogheart** [comment]
Yes add that to the bug too.  IRL they are powered by something that runs out.

**Comment by 321nick** [comment]
dont they run out after a very long time IRL, and in this slightly-futuristic setting it cant be too hard too assume the battery are slightly too moderately better, thus allowing long times for watches and etc too last, especially longer than most chars live?

**Comment by illi-kun** [comment]
See #676 for similar discussion about watches & batteries.

**Comment by busterbogheart** [comment]
I'll agree that watches last a long time (longer than an avg cata lifespan at least) but the topic was phones.

**Comment by Shudokai** [comment]
The phones in cata are just glorified pocket watches, they have the drawback of taking up space and weight already. And if you disassemble Phones, Watches and the like you actually get a few batteries, so they actually run off of something.

**Comment by Xpyder** [comment]
regardless of the realism, if disassembling gives batteries then assembling them should require batteries too.

I'll look into PR this

**Comment by keyspace** [comment]
I've tried an implementation in a branch, [all work in one commit so far](https://github.com/keyspace/Cataclysm-DDA/commit/d42336805773e66d6259feea1da5f0c1401e9bcf). It kind-of-works, but is hackish in a few places. `"turns_per_charge": 30000` doesn't work - the intent was for the phone to stay on for slightly longer than a day, but it drains ~ 80% of battery in 6 hours.

Could open a provisional [WIP] PR if desired.

**Comment by raymoo** [comment]
In real life, mechanical wrist watches are often "self-winding" by using the movement of the wearers wrist. They can last as long as the watch is in good condition and is worn regularly.

**Comment by Xpyder** [comment]
> In real life, mechanical wrist watches are often "self-winding" by using the movement of the wearers wrist. They can last as long as the watch is in good condition and is worn regularly.

I assume the subtext here is that with enough tech advancements you could get a cell phone to power from the mechanical motion of your body.

The closest you would probably get would be  a military grade battery charger that straps to your ankle for troops that spend a long time deep in territory where they can't be resupplied

Self winding watches are only achieved because of the extraordinarily small amount of power it takes to move the tiny parts (if they're made precisely enough) and because at your wrist the motion of your steps are greatly exaggerated and because you're staying with the same type of power (mechanical to mechanical) you can get a high efficiency with minimal parts (quarter flywheel, ratchet, spring, timing mechanism)

**Comment by illi-kun** [comment]
Pretty minor thing, I'm in mood to close this.
