### ISSUE TITLE
Boozeberry and Strawberry Surprise are unbalanced. 

### ISSUE THREAD

**Issue by Cyrano7** [CleverRaven/Cataclysm-DDA#16659]
The recipes are similar but the outcomes are very different. One has fun 8 and the other -12, or for nutrition 8 and the other 30. Quench is 15 per unit(6x) but 2 units of vodka is -20 and 2 blueberries is 4. The description says they are gross and I don't see a reason you would naturally want to make this for survival besides persevering some element of the fruit? The recipes as it stands currently even can only be made near a fire and not a hotplate or stove. Should they just be removed? In game you are pretty much better off using the ingredients separately or in another recipe. I've never really heard of people making something like this IRL.
Edit: its actually 4 vodka per batch so that's -40 quench.

**Comment by Coolthulhu** [comment]
While I'm generally in favor of removing things that are badly designed, I'd keep those two because they're "fun".

I assume the boozeberry's negative fun is just a way of balancing it. It probably isn't anywhere near that gross. It is done IRL to preserve fruit and to get flavored drinks.

The numbers are way off:
* 6 units of boozeberry are 180 nutrition
* 4 vodka + 2 blueberries are `4 * 2 + 2 * 18 = 44` nutrition
* 4 vodka and 2 berries result in all 6 units of the booze
* Boozeberry is almost as nutrition-dense as ant eggs, but with positive quench

Then there's the production method vs. description. Description says they ferment. Vodka and fruit mash will not ferment - except maybe into vinegar.
If the description is correct, then the recipes have to be removed.

**Comment by Cyrano7** [comment]
For these two items they don't seem to well thought out or executed to be worth keeping in my opinion. I can understand having a generic whole fruit preserved in alcohol item and recipe and then having a few fruit specific specialty items similar like whisky cherries though. I'm might take a crack at it after https://github.com/CleverRaven/Cataclysm-DDA/pull/16568 is resolved.

**Comment by Cyrano7** [comment]
Discussion continued in https://github.com/CleverRaven/Cataclysm-DDA/issues/17293
