### ISSUE TITLE
'g'rabbing and dragging items

### ISSUE THREAD

**Issue by Chezzo** [CleverRaven/Cataclysm-DDA#16652]
I think you should be able to drop backpacks and suitcases and such, either multidrop with other items or just dropping them straight into the bags, and then you could hit 'g' and grab them and drag them around.

And then, to avoid minutia, when you pick them up they act just like they do now, so no having to mess around with bags in your inventory.

**Comment by Coolthulhu** [comment]
Unreal World has something like this. You can mark some items for dragging, then when moving all those items are pulled into tile you just left.

The problem with it is that there is no surefire, persistent way of telling which items are selected. Item selection already causes some problems with long actions such as pickup and dropping if anything happens to the item set.

**Comment by 321nick** [comment]
i wouldnt mind just being able too drag singular items, it would make hauling v8s and such easier.

**Comment by Hague** [comment]
I usually just use the advanced inventory to move big parts between spaces directly. It's not fast, but it's not terribly slow either. Any other way is far more cumbersome.

**Comment by Hisel** [comment]
Hi, I just started looking around at the code and I'm interested in trying to help, could someone point me towards the files that have the relevant furniture dragging code? All I can find seems to be the vehicle dragging one.

**Comment by Coolthulhu** [comment]
Everything is in game.cpp.

The problem is, furniture and vehicles can be unambiguously identified (there can be only one of each on the tile), while items can only be identified by index on the list. Meaning that if for some reason some of the items being pulled are removed from the list, different items will be pulled next time.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
