### ISSUE TITLE
Underbarrel Laser Sights and Rail Laser Sights have no effect on Weapon Stats beside adding weight.

### ISSUE THREAD

**Issue by Shudokai** [CleverRaven/Cataclysm-DDA#16669]
The laser sight mods are dead weight right now as they literally only add weight to the gun they are attached to. This is probably caused by the fact that sights SET the aim speed and sight dispersion instead of modifying it, so they would probably conflict with other sight mods.

To prove this I've taken two identical guns and added the mods to one of them and took a screenshot of both guns in direct comparison.

http://imgur.com/pfO2rb6

I also did some playtesting with the time it takes to steady both guns after walking the same steps back and forth, aiming at the same stationary target, it only reinforced my suspicion of the mods not working.

After some brainstorming I thought they would be Infra-red laser sights as they are used by special forces, so I equiped and activated IR Goggles but that was a disappointment aswell.

**Comment by Griffinhart** [comment]
I *believe* this is working as intended; lasers and glass are only useful on weapons with worse aim speed/sight dispersion than what they would set them to.

**Comment by Coolthulhu** [comment]
They do have effects - their aim speed is better than regular sights so
they get used when your recoil is high enough.

2016-05-17 7:03 GMT+02:00 Griffinhart <notifications@github.com>:

**Comment by Griffinhart** [comment]
Oh right, I totally forgot that aim speed is a thing.

(Honestly, I feel like a lot of the issues regarding gun mods would be clarified if there were better documentation of what all the different stats do. Or has there been a documentation update that I totally missed on these past months?)

(The other issue I think is that it's not clear in each individual case when a number is better or worse. Like, lower turns to use = better, lower sight dispersion = better, but you want bigger damage numbers and such. Granted, the item comparison screen can clue you in, but it still doesn't actually explain *why* a number is better if it's lower, and IIRC has led to issues being filed because a user thinks the comparison is wrong.)

**Comment by mugling** [comment]
Obsolete following aiming rework

**Comment by BorkBorkGoesTheCode** [comment]
This is still a problem. Laser sights of both varieties have no visible effect on aim speed or sight dispersion, even though they have json lines for both.
