### ISSUE TITLE
Expand Advanced Inventory to accomodate later ground interactions and wielded items

### ISSUE THREAD

**Issue by Hague** [CleverRaven/Cataclysm-DDA#16685]
Wielded items are not directly accessible through the advanced inventory without wielding another object. Seems like they should be added to the 'w'orn tab under a "wielded" heading.

The advanced inventory hasn't been modified for the ability to Unload and eat from nearby ground tiles. The action menu (default 'e') could be expanded to work on nearby tiles (currently only works when the inventory or worn tab is highlighted) so players can consume, unload or reload nearby objects without picking them up directly sparing some tedium from interactions of that sort in that menu. (Currently, you must take an item into your inventory to interact with it, as the ground tile action menu defaults to simple inspection with no ability to interact) Wearing objects through the menu is already supported by transferring to the worn tab so it shouldn't be considered too much of a stretch to wield objects through it as well.

The 'a'ctivation function should logically be enabled via Advanced Inventory but there's probably caveats regarding ground interactions with some activations that makes that unmanageable right now.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.

**Comment by Consoleable** [comment]
I'm having the same issue
