### ISSUE TITLE
Order NPCs to grab only food, only water, only medical supplies.

### ISSUE THREAD

**Issue by Shudokai** [CleverRaven/Cataclysm-DDA#16689]
As of now the command that allows NPCs to grab items is pretty much useless and will only slow the game down to a crawl in some situations, they will grab items with a high value instead of usefull items and when they actually grab equipment for once they will not even use it.

I suggest to split that command into 3 or 4 different commands.

Grab food - They will actively try to grab food to feed themselves with.
Grab drink or grab water - They wil actively try to grab any drinks or maybe only water so they don't get drunk all the time.
Grab Drugs - They will go for painkillers, bandages, first aid kits and other medical supplies.
Find better Equipment - They will look for anything that will be better in terms of armor and capacity for each individual layer of their body, so they will try to have the best equipment in each slot at any time. (Each bodypart and each layer: Skin, Normal, Outer, Waist, Strapped)

In terms of immersion some NPCs might actively go for booze or drugs if they are addicted no matter how you adjust their settings, some might always grab money because they are greedy or something like that.

It is just a general thought to make NPC companions more fun and less annoying, because right now they are more of a pain to deal with than anything else.

**Comment by Coolthulhu** [comment]
I'll most likely make it use a whitelist, like autopickup.

**Comment by Shudokai** [comment]
A whitelist like what? So they will only ever pick items they need for survival instead of everything thats not bolted down?

My biggest issue is feeding multiple allies right now, it is way to button intense and sometime they don't even take my food because they don't trust me enough.

I think giving them new equipment is okay-ish but the feeding is absolutely annoying to the point where I always tell them to shut up and starve in silence.

**Comment by pisskop** [comment]
I would love a whitelist.

Whitelist is an explicitly specified list of items you allow NPCs to grab.

**Comment by Coolthulhu** [comment]
The whitelist would most likely reuse autopickup one. I'm not sure how good autopickup whitelist is, though. It might be too bad for this purpose.

**Comment by kevingranade** [comment]
Might supplement the existing whitelist with ability to mass-add commonly
looted items like food, medicine, ammo, etc.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
