### ISSUE TITLE
Construction Ideas

### ISSUE THREAD

**Issue by darth-servo** [CleverRaven/Cataclysm-DDA#1669]
Allow Rope & Pulley systems to raise/lower a drawbridge:
Basically, the same effect as placing a plank over a pit now, except allowing the rope & pulley to activate it.  

Perhaps allow wider and longer bridges to be built so that bridges can span 2+ tiles and be used by vehicles.  Could be interesting if bridges had a weight limit and could break if a heavy vehicle rolled over them.

Metal walls, doors, gates:
Made of Steel Plating.  Instead of a Rope & Pulley, the gates might require a Mechanical Winch (as found in Garages) built from steel and chain.

Root Cellar:
Especially considering the region, Root Cellars should be a thing. http://www.almanac.com/root-cellar-build
3 stages: Shallow Pit, Deep Pit, Finished Root Cellar.   Perhaps require Hay for insulation (yay, a use for Hay!)
##

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
