### ISSUE TITLE
Make seing minefield sign appear in safe mod message

### ISSUE THREAD

**Issue by baraba3** [CleverRaven/Cataclysm-DDA#16693]
if such change is possible as minefiled sign is object not creature...
Currently one of my most often mean of death is being killed by boredom while i traverse large spaces on foot and dont dedicate enough   attention to spot those signs in fileld and blow myself up as conswquence.As minefields are currently marked so survivor can easily spot them in day i would argue that having some short of warning message when survivor spot minefiled sign while you are walking around can make you not step in them oblivously becuse you are not looking hard enough and want to get from point A to point B in shortest amount of time.
this would off course not help you much in night except if you come in visula contact with minefild sign again.

**Comment by AppleConnoiseur** [comment]
Minefields is the main reason i only drive around during daytime :P. Maybe could have a 1 point trait for  the overcautious people.

**Comment by Coolthulhu** [comment]
Maybe mines shouldn't be hidden?

After all, if the mines are marked and supposed to kill critters that have no regard for survival, there is no good reason to bury them underground.

**Comment by baraba3** [comment]
thats maybe better alternative Coolthu.

Obviosly currently signs are there to stop people for venturing in mine fields.Dying becuse you didnt payed attention after waching for signs after walking around all day is i think not intended.

**Comment by mutt3x** [comment]
>there is no good reason to bury them underground.

The sole functionallity of a mine is compromised if above ground, 
I come from a place where there a a lot of mine leftovers.
Most mines are box or circle shaped. That part goes underground while the trigger goes above. The trigger is Mostly very sensitive and very small (anti personel ones). Some mines are designed so that they can only be inside ground (stick like ones)
If you just place it on the ground you would have very little chance to trigger it unless you have a special funny walk (Monty Python).

Even if you just drop a mine on a field grass would eventually cover it, if in a forest leaves would cover it making it more or less hidden.

>After all, if the mines are marked and supposed to kill critters that have no regard for survival

Highly bad way of land mine use, putting poison on ground would have better success rate really. Aslo animals dont tend to snoop around flags and markings. Wild animals mostly avoid most human stuff, unless there is food around.
The field itself is just a very small box with four signs, who tought that that is effective. Making a whole field with a landmine wide line would be much more wiser. 

The really bad thing about mines is that you can spot them ingame. Very ridiculous and thats not how you would find a mine IRL. You need special tools to disarm it. You need special tools to find it unless you have special eyesight that can see... omg stop. Yeah i summoned the IRL theme since if you apply it to most of other things...

If i remmember signs where added layter because users where not seeing mines. (Bohoo) Thats how they should work. Even signs IRL are distanced from each other, people very often like to steal them as well (very nice skull art lol), that is punishable by law in here btw.

mines are dangerous, you are the one that needs to be cautious not the game.

>It would be in my mind more realistic that bunkers and outpost and some important installations have mines in vicinity.

+1

**Comment by baraba3** [comment]
i am fine with dying to minefield  becuse of my lask of perceptuon/trapping/equipment but not minefield that is marked so player can avoid it.

A said have problems with marked minefields and having to devote attention to check signs of them.if there would mines only in certain areas even without any signs i would be fine dying to them thinking well shit i blew myself up trying to enter that military installation-its my fault not going prepared.But currenly it goes like this-i am   traveling on field in middle of  nowhere to next city and holding forward keyy becuse i dont see any danger and boom i am dead....3 squares from my dead body is sign that says "danger minefield".

**Comment by Coolthulhu** [comment]
> If i remmember signs where added layter because users where not seeing mines. (Bohoo) Thats how they should work.

Random deaths you can't feasibly prevent in a game with permadeath are somewhere in the Top 3 of bad game design ideas.

There are very few ideas worse than undetectable minefields just happening randomly, without warning.

> putting poison on ground would have better success rate really

Poison has to be absorbed somehow. Plus, it would most likely not do anything important anyway. Mines at least can be used as an environmental hazard.

> The really bad thing about mines is that you can spot them ingame.

There is no reason to hide a mine that is supposed to kill something that doesn't "see" mines. In fact, it's better to leave it visible, so that it doesn't explode under things it isn't supposed to kill.


Honestly the whole idea of minefields existing in DDA is pretty bad. They are pretty bad at their job as minefields, as they are too small to permanently kill what they're supposed to kill (zombies rise back). They can occasionally be used by kiting monsters into mines, but they also force a tedious kind of caution on the players.

**Comment by sanyaskillpro** [comment]
It would be nice if some special map features would give a warning in log even without safe mod. I wonder how many air drops and anomalies i missed at the edge of LoS when traveling.

**Comment by Shoes01** [comment]
What if the signs triggered the safemode check?

**Comment by Labtop-215** [comment]
> There are very few ideas worse than undetectable minefields just happening randomly, without warning.

Then maybe they shouldn't be just littered around a field.  With or without signs.  If those mines are there for enemy combatants as the game lore would suggest, the signs would be a dead giveaway that that particular location is dangerous.  It might make sense for landmines to have signs beside them after a conflict is over and done with, to warn people about landmines that your military hasn't gotten around to disarming yet, but not during times of conflict.

Not to mention that it tends to make road travel oddly difficult through forests without good reason.  How do you bury a landmine in the middle of a concrete road without making it sort of obvious there are land mines there in the first place?  It just leads to problems with road travel that probably shouldn't be there.  Dead vehicles, lava vents, zombie hordes, and the like make sense, but "buried mines" don't, and they are annoying to deal with on open roads and bridges.  Bridges especially because you have no place to bury them!  What are they doing?  Are then under the bridge?  Then how can you spot them?  Are they under the water?  Then how do they damage your vehicle?

As the locations we have access to are expanding, we are gaining more locations for landmines to be placed.  Honestly, we should probably change were they are so they are more of a feature in other locations, like Military themed areas (Bases, Bunkers, Outposts, Fema Camps) and areas of special interest (government run areas like Laboratories, Refugee Shelters, Hazardous Waste Sarcophagi, and the like) with the idea being that friendlies who know where the mines are planted would inform people who have to work or go to those locations where the land mines would be, and people who are not supposed to be there where they are supposed to step.  Maybe warnings like "Setting off into the grass may be hazardous for ones health without a metal detector." or something.

**Comment by Xpyder** [comment]
@Coolthulhu 
While interesting, I think you nailed the biggest issue with minefields: They spawn in places where they are too small to be useful.

Maybe they should be changed only show up in their current iteration in chokepoints in large military bases, and possibly be added as hazards at some hardened military checkpoints.  Possibly with unburied versions at bridge entrances with barriers in front of them meant to stop people who try to barrel through the barriers (as though they were deployed when still trying to contain the infection)

**Comment by Xpyder** [comment]
In their current iteration they remind me of back when there used to be shogun and crossbow traps spawning in groups randomly out in fields.

**Comment by pisskop** [comment]
Minefields should be clustered, to make actual fields of mines.

Seeing the sign and having that break safemode - Im not sure how doable it is, but its one of the better uses of safemode.


Id prefer that the minefields were actually harder to avoid, not easier . . .

**Comment by nornagon** [comment]
Maybe minefields could be a lot rarer and a lot bigger? Having to walk around a minefield is a nuisance, but not really an impediment at all. Running out of a house to escape some Zs and escaping into the forest, then suddenly from somewhere behind you: BOOOM, and you realise you're dead in the middle of mine central. Would perhaps also need some tools for cautious movement, a la `s`earch in Nethack to try harder than normal to find traps in adjacent squares, so you don't just roll to find out if it's RIP every turn and instead have a meaningful choice between moving quickly with the chance of setting off a mine, and moving slowly and methodically but with less (no?) chance of explosions.

I'm not sure how much that would improve matters, though. It seems fine to remove minefields altogether.

**Comment by Leland** [comment]
Closing due to age and lack of discussion.
