### ISSUE TITLE
Cooked meat nutrition has been nerfed with the recent changes

### ISSUE THREAD

**Issue by remyroy** [CleverRaven/Cataclysm-DDA#16708]
It used to be 50. Now it is 28.

Was that on purpose or was it overlooked? I cannot find any explanation for this change in the logs.

**Comment by Rivet-the-Zombie** [comment]
>Was that on purpose or was it overlooked?

I have no idea, but it makes no sense.

**Comment by karols146** [comment]
Can be related #16536

**Comment by Coolthulhu** [comment]
I think it was a result of switching nutrition to calories and not double-checking that the values are balanced. Possibly by using real life stats instead, which aren't balanced.

**Comment by DangerNoodle** [comment]
I assumed it was due to the  nutrition system. Smoked meat and jerky were neglected by this nerf, making cooked meat even more inferior.

If the expectation is that survivors should eat offal to make up for the nutrition loss (avoiding rabbit starvation), then the Simplified Nutrition mod should add changes to restore the old nutrition, and possibly blacklist offal.

Offal is mostly pointless with Simplifed Nutrition anyway, no player is going to put up with an item that costs morale, has low nutrition, and can not be preserved.
