### ISSUE TITLE
Negative Trait: Glial Tissue Rejection Syndrome

### ISSUE THREAD

**Issue by Hague** [CleverRaven/Cataclysm-DDA#16719]
The new Deus Ex game is coming out in September and I think these series of games always bring a huge inspiration to near-future sci-fi creative conventions. Playing through "Human Revolution" led to mentions of something called "glial tissue cell rejection." Basically, some people are mostly incompatible with cybernetics, having them promoting a form of painful cancer-like overgrowth in the myelin sheath and other non-neuronal nervous tissue. Could this be modeled as a Trait in-game? The characters in this instance can have implants, potentially, but they need treatments of anti-rejection drugs ( called "Neuropazine" in Deus Ex) regularly to prevent the tumors. If they don't have the drugs, they gain incrementally worse penalties from the painful scarring and nervous tissue damage

It should take into account the number of total occupied cybernetics slots. Characters with more implants face faster-accumulating rejection penalties. Potential penalties: Growing pain modifiers, tremors, flat stat and speed penalties, random blackouts, blindness, or deafness and as the disease progresses, shock rolls for death. The tissue damage ought to be permanent barring the use of stem cell treatment.

**Comment by sanyaskillpro** [comment]
Such a trait would be very hard to balance. Bionics are way too powerful, they would continue to be so even with limited slots. This trait would either be -75% hp trait-tier, meaning never take it or reroll if random character. Or, if penalties are rather mild, free points for early game-tier. Also consider these flaws:
1. Depends on a certain consumable. Even harder to balance, because everyone plays with different spawn rate.
2. You can already "reject" bionics, by installing faulty ones. The penalties are also very similiar.
3. How would a person without any bionics even know he has this syndrome? I'm referring to a character creation.

**Comment by player0981234** [comment]
what about professions with starting bionics do they start with a couple of those drugs

**Comment by baraba3** [comment]
How would a person without any bionics even know he has this syndrome? I'm referring to a character creation?

maybe doctors diagnosed condition pre-cataclism.

idea doesnt sound bad.it is quite limitation to play without bionics or play with constraints of they  are properly thought out.Does neuropazine in your thoguht can be  self produced or only scavenged from hospitals?

**Comment by player0981234** [comment]
> Does neuropazine in your thoguht can be self produced or only scavenged from hospitals?
Again, this is hard to balance. Self producing that would make the trait a non-issue, while limiting that to hospitals would make the trait too damaging

**Comment by baraba3** [comment]
yes, i would agree with you considering self production.in those cases ti would only postpone use of  cbms.

but i would argue that in cases its found in hospital you can make a interesting case.For example you need more of medication for more cbms you have which would force you to either stay out of cbms completely or have only handfull of most important ones for which you will have to look for medicine to maintaim and having considerable penalties for not having medication.I think this limitation would make for intersting gameplay and  player decisions.Aslo there is option for removing bionics now as far as i recall whcih would give you choice if you have bad luck to lift penalties for cost of cbms you already have.

**Comment by Coolthulhu** [comment]
> How would a person without any bionics even know he has this syndrome? I'm referring to a character creation?

We already have Robust Genetics, which would be even harder to test for than rejection. "But we already have worse offenders" isn't a good reason when adding new things, but it is a reason nonetheless.

Though obviously we'd need a good reason to add badly justified things. And this sounds just too hard to balance, except as a challenge trait or even challenge scenario. Challenge scenario that gives you mutant powers and good skills in exchange for the ability to ever use bionics could be cool.

**Comment by Hague** [comment]
The knowledge of the condition could be pretty simple: "You almost got a good job with the government until you took a physical and found out you have a latent genetic tendency for implant rejection. You need a regular supply of anti-rejection drugs or any CBMs will cause you permanent system damage." (Taking the trait would give you a anti-rejection drug syringe to start, like the inhaler for asthmatics)

Also, you could take this with Robust Genetics, they aren't mutually exclusive. CBMs are invasive technology that, according to the timeline, were developed a year before 4th dimensional transposition was discovered, which means they don't necessarily rely on the gene-warping properties of extra-dimensional materials and radiation. The CBMs are just looked at as a foreign contaminant, and since many (almost all, if they can be controlled via 'though') CBMs use neural interaction, they result in scarring, like emphysema on your nerves.

I don't necessarily see it needing to be balanced so much. The idea is that you're probably not gonna have a steady supply of anti-rejection drugs if you have the syndrome and no one is crafting any more. I mean, you could add a means, but I don't think it's necessary. You can't make inhalers (AFAIK) so you shouldn't be able to manufacture ARDs. Anti-rejection drugs would probably be found in pharmacies, hospitals, and bathrooms in mansions, and gov't-run facilities. As an alternative use for the drugs, they could be used to provide a temporary boost to the chance to successfully install CBMs.

As for stem cell treatments, there's no reason to say you can't mimick that functionality of them through other means: A cutting-edge military medkit that has super-science portable stem cell treatment in it. The idea of a player homebrewing their own stem cells in a home cryogenics facility powered by a homemade solar array and dozens of car batteries sounds just like something that would happen in Cataclysm.

**Comment by macrosblackd** [comment]
I think this could be fun to play with - either as @Coolthulhu mentioned, a challenge trait similar to glass jaw, or just as a normal trait. If it were me playing with this trait, I would probably stockpile the ARDs until I had a decent supply before attempting to mess with cybernetics, if I even bothered to mess with cybernetics at all.

**Comment by kevingranade** [comment]
Two thoughts:
Instead of having it adjust the chance of rejection having it give
penalties while CBMs are installed would allow you to have a manageable
penalty but have the anti-rejection drugs remove that penalty temporarily.
Instead of a trait what if it was a mutation which would provide a
mechanism for mutation use to conflict with CBM use, it could even have
multiple stages.

**Comment by Isaacssv552** [comment]
I really like the idea of a trait that makes CBMs more difficult to install and escalates the penalties of failure. Basically an Anti-MD trait.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
