### ISSUE TITLE
Cabellas/hunting store/Npc idea

### ISSUE THREAD

**Issue by Nickboom1** [CleverRaven/Cataclysm-DDA#1674]
As we talked about in the IRC we thought about making a hunting mega store similiar to Cabella's in which would be very good gear. However we also decused how it would commonly be filled with a group of NPC's that reactive hostively to you if you try to force your way through. You would be able to do missions for the NPCs and they would give you gear and guns and maybe even lets you enter the building. Of course the flip side to this is you could try and fight them all. Rarely the Store would be filled with zombies instead of survivors I was thinking this would be more of a 10% chance sort of thing. (Cabellas for those of you dont know is a hunting type store that is usually very large and sells camping gear, survival gear, and lots of hunting weapons.
##

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
