### ISSUE TITLE
Wastebread shouldn't be Junk Food

### ISSUE THREAD

**Issue by Hague** [CleverRaven/Cataclysm-DDA#16749]
Wastebread currently is considered junkfood and has a health loss associated with it. However, Wastebread's list of potential ingredients contains no explicitly unhealthy foods or Junk Foods such as: sugar, salt, cooking oil, lard, or chocolate. It might taste terrible, but it shouldn't be explicitly unhealthy.

**Comment by Coolthulhu** [comment]
We don't have a strict definition of what counts as "junk food". IRL most junk foods are made from subpar components (mechanically separated meat etc.) or are highly processed (extracted with solvents like low quality vegetable oil).

Wastebread is made mostly of bone, which, in this context, does qualify as subpar.
IRL wastebread would most likely include some wood shavings instead of only bone.

**Comment by Hague** [comment]
But bone isn't junk food itself. It doesn't lower health, it just has low enjoyability. Also, bone broth, made of simply bones and water, isn't unhealthy. There's absolutely zero mechanical reasons why wastebread should be Junk Food. We count all foods containing dairy as dairy. Since there's no junk food components to wastebread it shouldn't be junk food. Or should we just ignore consistency in this instance just because? By the context you've given, orange juice the player acquired from a store should be junk food as all manufacturer's add cellulose (wood pulp) to maintain the orange flavor of concentrated orange juice. Also, paper is totally edible in-game, it's not unhealthy (health: 0) but highly disgusting (enjoyment -50) and not considered junk food.

You're wrong by every metric standardized in the game. Though, you've brought up a good point: You should be able to use paper in the wastebread recipe. Still shouldn't be unhealthy though. Gross, unfulfilling, but not unhealthy.

**Comment by Coolthulhu** [comment]
> Also, paper is totally edible in-game, it's not unhealthy (health: 0) but highly disgusting (enjoyment -20) and not considered junk food.

That's more of a bug than anything intended. Paper has no material.

> You're wrong by every metric standardized in the game.

You're quick to claim victory. Too quick to actually check what you're talking about.
For example, condiments (ketchup, mayo) contain no junk food, but are junk food. Cookies allow more healthy ingredients than junk food. Onion rings. French fries and potato chips. Sugar beet syrup. Nachos.

That would make you the wrong one here.

> We count all foods containing dairy as dairy.

But junk food isn't a real allergen.
> There's absolutely zero mechanical reasons why wastebread should be Junk Food.

So you want it to be Bone material instead?
Because it sure isn't pure wheat.

**Comment by Hague** [comment]
Ketchup is full of salt. Salty foods are unhealthy. Mayonnaise is full of oil. Oily foods are unhealthy. Ergo, directly consumed condiments of that variety should be junk food (especially mayo) Since there's no salt, oil, fat, or sugar in Wastebread it doesn't sit at the top of the food pyramid, it can't be unhealthy, at least. It's arguable whether or not having junk food components make a food into a Junk Food. There's probably a threshold: sugary sodas are nothing but sugar and water but a smear of mayo on a burger isn't gonna kill you. That said, I can't see a standard for a making something a junk food when it has no junk food components at all.

And yes, add bone as a material, it should be in there, along with wheat as those are the two constituent ingredients but since none of the ingredients match the current design paradigm around what constitutes unhealthy (it's not overly fatty, salty, sugary, or tainted) it shouldn't be unhealthy.

There's nothing unhealthy about bones anyway: High in iron (marrow) and calcium. Animal gelatin is basically bone meal. Aspic isn't unhealthy and it contains bones as a constituent ingredient to make the gelatin.

**Comment by Coolthulhu** [comment]
> Ketchup is full of salt. Salty foods are unhealthy.

So you want meat jerky to be junk food? Broth has more salt than ketchup.

> Mayonnaise is full of oil. Oily foods are unhealthy.

Biscuits, johnnycake, some fried foods (ones that use oil as a component, not a tool).

> That said, I can't see a standard for a making something a junk food when it has no junk food components at all.

That's because junk food is an arbitrary designation for things with low quality of nutrition, not a strict switch based on content. So far the only standards junk food follows is that chocolate component makes it junk food, soda component makes it junk food and junk that exists in uncooked and cooked variants (cooked and uncooked hot dogs) is junk in both.

"Junkiness" can be added, removed, passed from components.

> none of the ingredients match the current design paradigm around what constitutes unhealthy (it's not overly fatty, salty, sugary, or tainted) it shouldn't be unhealthy

This design paradigm isn't current, but yours. There are too many counterexamples for it to really be a design paradigm.
It could be made an official one if you found most of the counterexamples and proposed (or better - PR'd) a fix, but it isn't one at the moment.

Also, junk food and unhealthy are two different things. Junk food is closer to "low in useful microelements" while unhealthy to "contains mild toxins".

> Animal gelatin is basically bone meal.

No, it's just one component of it. Bones themselves accumulate heavy metals, contain much more calcium and phosphorus than broth made from them (in fact bone broth contains less calcium than vegetable broths) and aren't processed all that well by human digestive system.
Bone meal is considered dangerous even as a pet food supplement.

They do make a good calcium (and phosphorus) supplement, but to say they aren't unhealthy when consumed in bulk would be just plain wrong. Like carnivore liver - it can be a great supplement (in low amounts), but human metabolism is closer to that of a cow than that of a bear and it simply can't deal with high concentrations of certain substances. A meal of bear liver can cause a deadly hypervitaminosis.

If we were going by pure realism, bone broth would lose the bone component (aspic doesn't have it either) and wastebread would gain so much calcium that it would become a limiting factor in its consumption, but also some negative health value (because heavy metal accumulation).

**Comment by Hague** [comment]
The original basis for my argument was the stats currently listed for the ingredients, not an in-depth realistic analysis. However, all of what you said makes sense and it seems to me to unify the recipe would simply involve making bone meal an unhealthy food. That would make wastebread's qualities match that of its ingredients better.

**Comment by mugling** [comment]
Closed due to lack of consensus on issue of minor importance. Much greater problems exist with the comestibles system which we should tackle wherever we can first reach broad agreement
