### ISSUE TITLE
Cannot save in Defense Mode

### ISSUE THREAD

**Issue by DearVarun** [CleverRaven/Cataclysm-DDA#16864]
When playing defense mode the game prompts "cannot save in defense mode" and does not allow you to save.

**Comment by Rivet-the-Zombie** [comment]
What's the problem then?

**Comment by codemime** [comment]
@DearVarun It's not a bug, it's a feature.

**Comment by Autastic** [comment]
i've mentioned this issue before, but it looks like they have no intention of fixing this (among many, MANY other issues with defense mode) because, from what i gathered, the person who was developing defense mode stopped working on it. it's completely unfair that you're not allowed to play defense mode on laptops or are forced to restart every time you encounter a gamebreaking bug, but we have to deal with it until someone in charge decides to change something.

**Comment by DearVarun** [comment]
@Rivet-the-Zombie  I can't seem to be able to save even when no enemies are present in the wave 

@codemime It seems slightly nonsensical to prevent people from saving even when there are enemies present because you can do it in survival.

**Comment by DearVarun** [comment]
Anyone know where the code for defense mode is.

**Comment by Shoes01** [comment]
I searched "defense_game", and there were hits in defense.cpp, gamemode.cpp and gamemode.h. I then searched "special_game", which led to game.h/cpp, gamemode.h/cpp, worldfactory.h/cpp, main_menu.cpp and enums.h. 

And so your adventure begins! Good luck!
