### ISSUE TITLE
Skeletons have organs

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#16893]
Skeletons drop raw offal (the edible kind) when butchered.

**Comment by mugling** [comment]
Confirmed, and there are other examples also

**Comment by pisskop** [comment]
Maybe bones should imply no meat

**Comment by Rivet-the-Zombie** [comment]
This would be easily fixed by something similar to the STOMACH flag, so monsters who aren't opted-in via the flag won't produce offal.

**Comment by 3721assistant** [comment]
Triffids also drop organs, and the organs have material of meat, not sure if it is right since they are plant

**Comment by kevingranade** [comment]
That is also a bug.

**Comment by i2amroy** [comment]
Might be important to note that our skeletons aren't just skeletons, but are more something that looks kinda like this (but with black ooze instead of red, IIRC)
http://img01.deviantart.net/2fd5/i/2012/043/6/1/cancer_by_lordnetsua-d4phl2v.jpg

So the fact that they drop edible offal is almost certainly a bug, but the fact that they necessarily still have internal organs is not necessarily one.

**Comment by pisskop** [comment]
tainted soup stock aye
