### ISSUE TITLE
Trader NPC sells guns without magazines

### ISSUE THREAD

**Issue by 3721assistant** [CleverRaven/Cataclysm-DDA#16908]
How to reproduce:
1. keep a friendly trader npc alive for about 3 days
2. buy a random gun from npc after restock
3. the gun have no magazine so ya can't fire with it

**Comment by Shudokai** [comment]
So what? How is that unreasonable? Random NPC goes around and loots corpses or houses, what are the odds he finds a gun missing a magazine and decides to sell that instead of using it himself?

Think about it that way. You will also find guns without magazines in basements and stores and even labs many many times.

**Comment by John-Candlebury** [comment]
It makes the merchant rather useless for game purposes. At the very least they should stock magazines regularly, and sell magazine-less guns at a discount

**Comment by Leland** [comment]
Old suggestion and no recent discussion here. Closing.
