### ISSUE TITLE
Replace nondeterministic placement methods with deterministic ones.

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#17039]
There are a number of places in the code that try to place something like so:

```
int attempts = magic;
do {
    int x = rng( maxx, minx );
    int y = rng( maxy, miny );
    attempts--;
    if( m->can_place_furn( x, y ) ) {
        m->furn_set( x, y, t_stairs_down );
        break;
    }
} while( attempts > 0 );
```

Instead, a permutation generator can enumerate all the available coordinates, but in a random order and iterate over them until a valid location is found:

```
for( const tripoint &target : permuted_points_in_square( max_point, min_point ) ) {
    if( m->can_place_furn( target ) ) {
        m->place_furn( target, t_stairs_down );
    }
}
```

Generating the permuted lists might be a little slower, but I strongly suspect that overhead is dwarfed by the redundant checks the random checking does.

**Comment by codemime** [comment]
I'd use quite similar, but slightly different [approach](https://github.com/CleverRaven/Cataclysm-DDA/pull/15249#discussion_r52281072):

1. Build a vector of all suitable places using `m->can_place_furn( target )` as a predicate
2. Shuffle the vector
3. Pick `N` first (or last) elements (in case we need more than one item of anything).

**Comment by kevingranade** [comment]
Reasons to build a permutation of coordinates up front:
Isolates enumeration code from the testing and placement code.
Permutations are potentially cacheable, this can be hidden from callers and implemented as needed.
Testing until success allows early exit, enumerating all legal locations requires testing all legal locations, which is the most expensive part of the operation.

**Comment by codemime** [comment]
> Isolates enumeration code from the testing and placement code.

Looks like an acceptable isolation:

```c++
valid_points_in_square( max_point, min_point, [ this ]( const tripoint &target ) {
    return m->can_place_furn( target );
} );
```

> Permutations are potentially cacheable, this can be hidden from callers and implemented as needed.

It requires rerolling the cache every time you need it again (otherwise it's not actually permuted and can't be trusted). Legal locations could be cached too (especially when requirements are similar), but unfortunately this can't be hidden from a caller since lambdas can't be compared.

> Testing until success allows early exit, enumerating all legal locations requires testing all legal locations, which is the most expensive part of the operation.

Agreed. Although enumerating all legal location has its advantages too:

- You can estimate the possibility before actually placing anything (i.e. if you need to place either a large structure of `NxM` adjacent things, or exactly `N `things)
- If there are some optional requirements, they can be taken into account during shuffling/filtering
- Enumerating can be even faster if there are very few legal locations.

**Comment by Coolthulhu** [comment]
> It requires rerolling the cache every time you need it again (otherwise it's not actually permuted and can't be trusted).

For mapgen, it would be enough to cache a few permutations and then pick a random one, start from random index, iterate from there and wrap back at the end.

**Comment by codemime** [comment]
@Coolthulhu Good idea, but is mapgen performance really an issue?

**Comment by Coolthulhu** [comment]
It can be, but mostly due to bugs.
