### ISSUE TITLE
Dirt Mound Decay

### ISSUE THREAD

**Issue by pisskop** [CleverRaven/Cataclysm-DDA#17040]
A decay rate in-bubble, _for_ unplanted dirt mounds.

Considering the lack of urgency in plant harvest (and in some cases bonus for lax farming practice) this is not going to affect actively planted mounds, but for things such as diggers and vehiclular skidmarks it would remove this intrusive and largely aesthetic eyesore.

**Comment by pisskop** [comment]
Since there are no objections, Ill move on to trying to make this happen.

**Comment by Coolthulhu** [comment]
In-bubble sounds bad.

I'd rather see it as out of bubble only - that is, on load, like plant maturing is.

**Comment by pisskop** [comment]
> 
    const int plantEpoch = seed.get_plant_epoch();

    if ( calendar::turn >= seed.bday + plantEpoch ) {
        if (calendar::turn < seed.bday + plantEpoch * 2 ) {
                i_rem(p, 1);
                furn_set(p, furn_str_id( "f_plant_seedling" ) );
        } else if (calendar::turn < seed.bday + plantEpoch * 3 ) {
                i_rem(p, 1);
                furn_set(p, furn_str_id( "f_plant_mature" ) );
        } else {
                furn_set(p, furn_str_id( "f_plant_harvest" ) );
        }
    }
    if( g->m.ter_set(p, t_dirtmound) && one_in(5) ) {
        g->m.ter_set(p, t_dirt);
>}


Like this?

**Comment by Coolthulhu** [comment]
The chance needs to depend on time that passed. `grow_plant` doesn't have this time, so it would be better to put the mound decay code elsewhere, preferably in its own function that would get `time_since_last_actualize` passed from `map::actualize`.

Don't use `i_at( p ).empty()` when there is `items` above that already is `i_at( p )`.

**Comment by pisskop** [comment]
So basically I can copy the funnel code?


It makes a variable, then the funnel calls upon it in order to fill.
What does the exclaimation point actually mean?  Its not 'not'

**Comment by Coolthulhu** [comment]
> So basically I can copy the funnel code?

Well, kinda
The only thing you need from funnel code is the part where it gets the time difference.

> What does the exclaimation point actually mean? Its not 'not'

Vast majority of time it is "not".

Important thing to note before pushing any PR: testing own changes isn't an option, it is mandatory. If you didn't set up the compiler yet, there are some guides on forums (or you can just ask for a fresh, working one, in case some things changed).
Last time a contributor repeatedly tried to push first and test never ended up really badly.

**Comment by pisskop** [comment]
right,  I want, almost need this to happen so.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
