### ISSUE TITLE
Plutonium rebalancing

### ISSUE THREAD

**Issue by mugling** [CleverRaven/Cataclysm-DDA#17086]
As set out in #16959 our current implementation of `plutonium` isn't especially interesting and is a frequent source of bugs. Effectively our current implementation is as 1:500 batteries. I'm considering the following revised implementation:
- `plutonium` is contained in `plutonium cells` which are non-craftable and relatively rare
- cells cannot be reloaded nor their contents transferred between cells
- considerably better energy density than `battery`
- once activated a cell begins to discharge at a consistent rate independent of any tool usage
- items with variable power (especially `minireactor`) may use multiple cells in parallel
- cells continue to leak radiation when damaged

The intended balance point is as an energy-dense replacement for batteries offset by their limited shelf-life once activated. Would allow for some very powerful vehicle mounted weapons balanced by the requirement to activate a large number of plutonium cells which may then otherwise go to waste.

**Comment by Coolthulhu** [comment]
> once activated a cell begins to discharge at a consistent rate independent of any tool usage

I don't like this point. The rest looks good.

We could even get rid of the atomic battery mod and just make plutonium cells a special kind of a battery, to make them more useful.

**Comment by Solusphere** [comment]
Not a dev, but I just wanted to give my two cents. I personally get severe too-good-to-use syndrome with anything that consumes plutonium cells. They're simply too rare and too useful in crafting to be used for any purpose that doesn't strictly require them. Fusion cannons and microreactors are nice, but not nice enough to warrant using over conventional equivalents when they're consuming components you could use to make power storage CBMs. I think the only exception is the enormously rare Rivtech low-profile power armour, which is relatively efficient at using them and good enough to justify it. Making plutonium cells highly inefficient as well as vanishingly rare would not help to expand their role as a power source rather than just a crafting component, IMO.

**Comment by Soadreqm** [comment]
I'd like to see nuclear power to be handled at least somewhat realistically, although considering the context, I'm not sure how reasonable this is. :P

One approach I can think of would be to turn plutonium cells into self-recharging batteries. Picture a miniature RTG connected to a conventional battery, good for zero maintenance low power output for the next hundred years or so. That'd make them amazingly good for general use. Of course, this would make absolutely no sense considering the existing applications. The car minireactor, the nuclear UPS and the Rivtech Warframe all assume plutonium cells to have a very high output voltage and an active life measured in minutes, basically the exact opposite of an RTG.

**Comment by kevingranade** [comment]
The use case you're talking about is covered by the "atomic" items of
various kinds.
Plutonium cells are being used in some kind of super-science application
that somehow extracts something between "reactor" and "passive decay"
levels of power.
Which reminds me, I always wanted to have all the super science stuff
labelled as such so it can easily be turned off.

I'd like Plutonium cells to be differentiated by being required by exotic
gear that can't be replaced by conventional means, examples include Power
armor, big energy weapons, big robots, and the ever popular plot device.
E.g. a mission requires using a platinum cell to restart a facility that
can afterwards provide some kind of irreplaceable services.

**Comment by jcd000** [comment]
Well, afaik today the reactor fuel cycle is like this: 
Put cell in, use for ~4 years.
Wet store the spend cells for ~10 years in order to have them cool down a bit as they are still producing significant amounts of power (~1-2 orders of magnitude less than before) 
Afterwards, transport the spent cell and store it for 100's of years since it will still be hot enough to cause problems.


Keeping these in mind, as well as the fact that plutonium cells in game are pretty small i'd propose to have them:
1) Provide lots of power for a considerable amount of time (one month?), when comparing with batteries, just as @mugling  suggests, and be good for top-tier electronics and quests as per the @kevingranade comment. Having them drain after being activated, regardless of use, will be unpopular but i think i like it as a mechanic. Makes them even more valuable.

2) After they are spent, cells don't dissapear, but become 'spent plutonium cells'. These are supposed to produce much less power, but they should be able to do it for a long time (1-2 years?). So these can still be used for purposes other than super high-tech electronics.

This could be achieved if we allow using such cells in low power applications like the atomic devices.
On that front, i'd like to see an 'atomic charger' : a charger that works for 1-2 years regardless of use, but charges very slowly and uses spent plut cells to do it.
Another idea could be some kind of atomic heater, using spent plutonium cells for space heating.

3) After all that period we can abstract the player throwing them away by having them finally dissapear.

**Comment by Coolthulhu** [comment]
> Having them drain after being activated, regardless of use, will be unpopular but i think i like it as a mechanic. Makes them even more valuable.

But way more tedious to use, barring some rework of battery system to drop charges from tools and just have them drain the batteries directly (ie. changing crafting from "50 charges of welder" to "welder and 50 charges of battery").

Without a rework, the proper way of using atomic batteries would be to use only one of them at a time, but swap it between all tools until it runs out. Otherwise you'd waste all the "active" cells.

**Comment by jcd000** [comment]
> Without a rework, the proper way of using atomic batteries would be to use only one of them at a time, but swap it between all tools until it runs out. Otherwise you'd waste all the "active" cells.

To avoid this i'd suggest making active plutonium cells unloadable and balance it out by making them last long enough (couple of months?)

**Comment by Soadreqm** [comment]
>After they are spent, cells don't dissapear, but become 'spent plutonium cells'. These are supposed to produce much less power, but they should be able to do it for a long time (1-2 years?). So these can still be used for purposes other than super high-tech electronics.

Interesting idea. That might actually mitigate the too-cool-to-use factor. A dead plutonium cell could still be good for atomic-nightlight type applications. Or recharging conventional batteries, if you have time to wait and the right equipment. The activate-once-drain-constantly thingy doesn't sound that good, for reasons outlined by Coolthulhu, but you could make it togglable, or just activated-on-demand by whatever device you're powering.

>Another idea could be some kind of atomic heater, using spent plutonium cells for space heating.

I like this too. An atomic heater is the kind of nuclear engineering that any survivor worth his duct tape should be able to do. Hell, the real problem should be making the nuclear stuff NOT heat.

**Comment by Zireael07** [comment]
The one time I found some plutonium, I definitely had a case of 'too cool to use'.
Just throwing it out there.

**Comment by Kadian** [comment]
I agree with Zireael, they are so rare you never want to use them, especially since they are currently just glorified Batteries.

How about the Introduction of something like a radioisotope thermoelectric generator? an RTG could use plutonium cells to give the player basically an unlimited (although low) amount of power. I could easily see them being used on Vehicles, powering smaller bikes, Quadbikes and therelike without the need for solar panels, gasoline or diesel.
Although, you might want to introduce radiators at that point as well, considering how much heat an RTG would produce. Actually, how about a new kind of Fuel: "Heat" ? You could use "Heat" to use Steam engines for example, or some flying vehicles, if it ever comes to that. And if the "Heat" fills up too much...well, overheating an RTG would probably cause a nice explosion?

**Comment by TempestMaiden** [comment]
Meanwhile, I'd say plutonium's uncommon at worst; I wouldn't want to try to run RM13 armor 24/7, but I'm able to run a vehicle using a minireactor as sole powersource and still keep a supply of plutonium for special occasions.

And that's without getting lucky in lab ends or trying to disarm teleport traps. Do those still give 20 plutonium each?

The trick is, the vast majority of plutonium the player gets usually ends up spent raising bionic power rather than anything else. If bionic power gets capped, players will find themselves with spare plutonium a lot more often.

**Comment by Solusphere** [comment]
That doesn't match my experience. I don't think I've ever had a game in which I've found over sixty or so plutonium cells in total in modern builds, and I've had several games that have lasted well over three years. The only relatively reliable place to find them that I have found are the storage rooms with the crates and chain link fences in labs, which occasionally have them in sets of five. They used to be a lot easier to acquire back when you could unload portable teleporters to get 20 of them. I haven't tried disarming teleporter traps to get them. If they do indeed contain 20 plutonium cells each, that would represent a huge majority of the total available cell yield.

**Comment by kevingranade** [comment]
The decay after activation thing is right out, it's a totally arbitrary and
annoying mechanism.
When thinking low power, please keep in mind it's REALLY low power, think a
light or heater, not an electric vehicle of any size.

My concern with the lowering power output is communicating how it works to
the player. Generally if it stops powering whatever it's being used for,
players are going to assume it's spent, and expect it can be disassembled
or used for crafting at best. Also is the output going to drop over time or
suddenly drop to a lower level? If the latter, what's the rationale for it
working that way? If we're not trying to model how it would actually work
(gradual decay), I'd prefer to just keep it simple.

To avoid confusion, I'd rather keep the "low power but indefinite lifetime"
and "miraculous power level but short lifespan" items separate like they
are now.

**Comment by jcd000** [comment]
I will try to quickly explain my logic behind the rationale, but bear in mind that i am not a nuclear engineer so its possible i misunderstand something.

1) Extracting energy from fission is a controlled proccess that provides the nominal required energy and no more. Meanwhile its max possible power gradually declines, but as long as this is more than the nominal, there is no problem. When the fissible material cannot provide that much energy, it is considered spent.

2) It would be inefficient to create a facility in order to do second-stage power extraction via fission, as the costs to build it would not be covered by the worth of the (much lower than before) power output.

3) On the other hand, the spent cells provide considerable amounts of power due to their inherent instability. This will be 1-2 orders of magnitude less than the power we were extracting before, but still sufficient for low power uses. The duration of this will be very large indeed. For reference, Pu-241 has a half-life of 14.4 years, meaning that it would take that much for its power output to halve, and this will happen regardless of use (as it will produce that much heat regardless of what we do with it - hence the non-switching-off rationale)

3) So, if we can find a sufficiently low cost & low output application for the spent cell, we are in business. Well, since the cell already produces heat, spece heating is a given.
But with heat, we can also produce electricity, even with small amounts of heat. For example via a [TEG](https://en.wikipedia.org/wiki/Thermoelectric_generator) or an [ORC](https://en.wikipedia.org/wiki/Organic_Rankine_cycle) generator.

Keeping in mind that there is a large difference in size between our plutonium cells and the huge ones used in reactors, the power output of one cata spent cell should be very low. (not enough to justify an ORC i'd wager, but TEG's could work)

As Kevin said, vehicles are right out, and the same applies for things like welders or a forge. But low power electricity devices, such as lights or slow battery chargers, maybe also slow cookers and the such, should be possible.

**Comment by Soadreqm** [comment]
>When thinking low power, please keep in mind it's REALLY low power, think a light or heater, not an electric vehicle of any size.
Speaking of this, the atomic coffeemaker probably shouldn't work as well as it does. Heating water takes a relatively large amount of energy.

**Comment by pingpong2011** [comment]
@jcd000 One of the biggest problems with actual nuclear material is the chain of breakdown elements, and their barns. I can't find the specific reference, but one (if not the first) nuclear experiments literally had a fault where they'd stop within the day, only to restart randomly in the middle of the night to shear panic by the scientist watching over it. The problem was the generation of Xenon-135 absorbs neutrons like crazy, and will shut down fission. Shutting down the fission prevents it's own production, and as it has a half-life of less than 10 hours, it will decay rapidly, re-enabling the fission reaction. Uncontrolled, the fission process will within a day cycle between full power and no output, with a greater poisoning rate at high power drains.

Nuclear power is in no way reasonable to do "realistically" in-game, unless you count the atomic lamp. Even a heater is way too much power for a portable nuclear source. Unless you count the source itself in some shielding.

Some rebalancing could be done with fuel cells, I'd propose. In the future, presumably we have the technology for it, and fuel cells would only take water and energy to fill. (vehicle+solar generator maybe to fill a special unit?) Today. the most efficient (cost, volume, etc) source of hydrogen for fuel cells is reforming natural gas, so even gasoline could in principle be used for it. I wouldn't mind if a fuel-cell was some hard-to-get thing like plutonium, because it would give a trade-off between using plutonium for high-end gear and CBMs i.e. "disposable" and balance it with a "renewable"/utility fuel.

**Comment by natsirt721** [comment]
This sounds like a proposal for a nuclear battery using a nuclear isomer of Hafnium (178m2Hf).  The battery would produce no ionizing radiation and had a specific power orders of magnitude higher than chemical reactions but also orders of magnitude lower than full-bore nuclear reactions.  The issue is that unlike uranium there isn't a good way to get all the energy out at once (some studies in the 90s suggested bathing it in x-rays helps but the results were inconclusive). It wouldn't be a far leap so say that someone discovers how to rev up the power output in the next few decades.  But I digress...

As for fuel cells, I think that they really are not useful.  A fuel cell is basically a battery that consumes diatomic hydrogen and oxygen and also produces water.  This implies that the player has access to diatomic oxygen, for which the best way to acquire would be electrolysis or scavenging oxygen tanks. However, a fuel cell is essentially just a scalable battery - add more H2 and O2 tanks and get more energy storage, but not more power.  The fuel cell unit can only produce electricity at a fixed rate, but more fuel means more energy in the long run.  Usefulness would be determined by the amount of electricity each unit of hydrogen and oxygen can produce and the power output of the RFC versus the capacity of storage batteries.

I think in general a vehicle electrolysis unit (or standalone item) for creating hydrogen would be great, as electrolysis is very easy to set up with minimal electronics and chemistry know-how.  Energy costs would be substantial, but being able to generate hydrogen (and oxygen, if you didn't want to vent it) would be a huge boon.

As for plutionium cells, an RTG would be a much more plausible use.  The Mars Curiosity rover's 50kg RTG produced 125W at mission start and is expected to still generate 100W after 14 years with only 4kg of 238-Pu [[source](https://en.wikipedia.org/wiki/Multi-Mission_Radioisotope_Thermoelectric_Generator#Design_and_specifications)].  While this is a pathetic amount of power (car alternators are ~1kW) it would operate effectively indefinitely and would not be restricted to daytime charging.  As for heat, the 2kW it produces can easily be shed by convection (keep in mind that insolation at 45°N is around 400W/m2, so 5x more energy than sunlight delivers), or at the very most an integrated closed-cycle water-cooling system.  The issue is that their specific power is so bad that they really can't be used as a sole power source for anything other than space probes or other very low-power applications, and they don't scale very well - too much fuel and you can reach criticality.

Using plut cells for high-power applications is really what this is about though, so here goes.  It seems to me like having them as an ammunition in their current state makes any attempt to rebalance them difficult.  I propose that cells could be non-stacking items with charges that when activated would 1) slowly decay over time like a lightstrip and 2) decay rapidly when in use.  An active idle cell would last for many hundreds of days, but running power armor 24/7 would drain them at a more rapid rate.  They would probably be most practically used by a nuclear power supply (nuclear UPS) rather than as a direct ammunition to make updating the charge counter easier, and things that currently take them directly as ammo would be reworked to require a nuclear power supply.  It is assumed that a regular UPS wouldn't be able to provide enough power for these items to work at all OR they would drain batteries at an obscene rate - hence the reason they require plutonium in the first place.  Leaking radiation when damaged is a nice feature, as they are going to have to be heavily shielded in order to not irradiate their environment, but should be fairly resistive to damage. For use in reactors, they could be craftable into fuel rods or simply added as a fuel - probably the latter as nuclear engineering may be beyond the scope of most players' comprehension.  

I think steam power is a great idea but this post is getting long, so I'll leave it at that.

**Comment by vache** [comment]
This is an old issue, but I agree with this:

> I'd like Plutonium cells to be differentiated by being required by exotic
gear that can't be replaced by conventional means, examples include Power
armor, big energy weapons, big robots, and the ever popular plot device.
E.g. a mission requires using a platinum cell to restart a facility that
can afterwards provide some kind of irreplaceable services.

I know everybody hates sci fi handwavium but I feel like that's really the best use in the context of game mechanics.

**Comment by Coolthulhu** [comment]
RM-13 does that. Overall it's not a bad idea, but that particular implementation makes it tedious to use (activate in combat, deactivate afterwards).

Still, allowing plutonium to be "downgraded" to a large amount of batteries shouldn't hurt.

**Comment by kevingranade** [comment]
Plutoium cells as battery replacements is not desireable, if you want to turn plutonium power to battery power, you should be able to do it through a reactor, but using them directly as batteries erodes their distinctiveness.
