### ISSUE TITLE
Redrawing the game when the player has no movement points causes undue strain on games

### ISSUE THREAD

**Issue by pisskop** [CleverRaven/Cataclysm-DDA#17094]
Redrawing the game ever time you perform a slow action is slowing the game down considerably, and apparently its effects are even more felt on laptops like mine.  And others, Im not the only one who sees it.

This option becomes almost unbearable when traversing large cities, multi-Zlevel buildings or structures with zlevels on, when large amounts of fighting is occuring, and when large number of monster exist in bubble.

  It should be an option in the option menu, and not a forced feature of the game.  I think it should be removed until it can be properly added.

@i2amroy

**Comment by pisskop** [comment]
What is involved in making an option?

I did some looking and I know theres an option entry:

> 

    mOptionsSort["general"]++;

    OPTIONS["NOTURN_REDRAW"] = cOpt("general", _("Zero turn redrawing"),
                                    _("If true, the game will redraw the game periodically in between player movements to create a more fluid enviornment. Defaults to true."),
                                    true
                                   );


And then theres calling the variable set by the options:

> 
    if (OPTIONS["NOTURN_REDRAW"] && safe_mode = SAFE_MODE_OFF) {
    if (u.moves < 0) {
        draw();
    }

But then I run into more question?
  Do I have to enum it?

say that off is noturnredraw_off and on is nturndraw_on?

Or will true false work on it own?

**Comment by i2amroy** [comment]
>It should be an option in the option menu, and not a forced feature of the game.

If we're going to make it an option then do it as an int and use a calendar::once_every( value). That lets people whose computers can't handle it turn the value down to match what they can without immediately disabling it completely.

>I think it should be removed until it can be properly added.

What it is right now is as "proper" as you're gonna get. :P There's literally no other way that I can think of to allow players to see what is going on while you are stunlocked other than making some sort of special "stunned" status that introduces all sorts of other issues (and won't let you see what happens when you say, climb over that window or something similar either).

**Comment by pisskop** [comment]
I dont mind formatting it or working at it since its my goal to ultimately understand howdo code, but Im not going to pretend I understand howdo int.

**Comment by Coolthulhu** [comment]
We have that option now.
Is there a way to check if the last redraw was in time?
If not, then we won't get anything better than the "don't force redraw" option.

**Comment by Coolthulhu** [comment]
Do we want something more here?
Forced redrawing is now optional.
