### ISSUE TITLE
Unable to change world type to desert

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#17107]
There was a fix that enabled changing the world type to `desert_test`. It no longer works.

To change the world type to `desert_test` you need to:
- Load a game (any world)
- Save the game (or otherwise go back to menu)
- Create a new world

Just starting the game and trying to create a new world will not work. The `desert_test` will not be on the list of world types.
Loading the game and trying to change the world's setting to `desert_test` will not work, despite the option listing `desert_test` in the description on top of the menu.
The option will be enabled after going back to main menu from a game. After that, the option to change the world type in load games will also be "unlocked".

**Comment by BevapDin** [comment]
Regional settings are loaded from JSON, mods can add new regional settings. The options menu can not display those options before the world data (including the mods) has been loaded as it doesn't know them yet.

The display of regional settings from the main menu is actually wrong: it could contain regional settings that are defined by a mod (loaded when playing the previous game) and that are only available in a world with that mod. New worlds, or just any other existing world may not have that setting.

One fix: load the world data when creating a new world. First tab allows to select mods, switching to the second tab (world options) would load the world data, including the available regional settings, which could than be displayed. However, loading the world data takes time. This loading time seems bad.

Other fix: just move the regional into a single instance, managed via mods. Instead of selecting a setting in the menu, one can do the same by selecting a proper mod.
