### ISSUE TITLE
Food weights are wrong (inconsistent with each other)

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#17114]
Specifically I noticed mushroom and chicken soup have twice the weight of meat soup which is provably incorrect.

I don't know how many other items are off, nor do I know what the values actually should be.

**Comment by Kadian** [comment]
The main Issue is probably that most soups can be made with different ingredients, giving a variety of possible weights. I do have to admit though, the Mushroom soup seems very, very heavy for it's ingredients. In fact, i did calculate it:
1 Mushroom Soup equals 4x288g = 1152g
Ingredients:
1 Broth + 4 Mushrooms. That is 250g + 4x159 = 886g

That's a 30% increase in weight, even though making a soup would most likely lessen the weight by a small amount, due to the loss of water as Steam. It get's even worse if you use dried shrooms, which would end up in 4x15 = 60g, giving the finished product a max weight of 310, which would make the finished mushroom soup 3,7 times as heavy as it's ingredients.

I can't calculate anything for the chicken soup, sadly, considering we don't have a recipe - or raw chicken, for that matter.

**Comment by Xpyder** [comment]
did some quick look ups and it seems to vary wildly.  lean fish has about half the calories of steak by mass, but fatty/oily fish has about the same.

Also the comparisons I found were on mass, but I don't know about the relative density's of steak vs fish, i.e. I don't know if they have similar weights per volume, so that may affect stuff too.

I think I may just leave this one to someone better qualified.

**Comment by Leland** [comment]
Closing - minimal discussion going on here, and we're approaching this being a year old. Feel free to comment here if you still want it open, or make a new issue.
