### ISSUE TITLE
gun mods make weapons huge

### ISSUE THREAD

**Issue by moosestrangler** [CleverRaven/Cataclysm-DDA#17151]
The gun mod system does not take account of the fact that many mods are replacements, not additions. This causes increases in volume and weight where they do not make sense. A 20lbs, 20 volume rifle is a problem for a character whose motivation to use it is low str.

Proposal:
Make firearms modular as a list of parts with a minimal group required to function. Part interchangeability between weapons, maintaining individual components, and similar concerns would add depth to the game and encourage using common or military issue weapons for reasons other than the availability of ammunition. A realistic implementation would probably be more complex than the vehicle system.

Proposal 2:
Replacement furniture does not change volume or weight unless that is its purpose.

**Comment by mugling** [comment]
I wrote `integral_volume` for this reason. We should perhaps consider also `integral_weight`

**Comment by Coolthulhu** [comment]
> The gun mod system does not take account of the fact that many mods are replacements, not additions.

Because mechanically they ARE additions rather than replacements. They improve stats.
If they are to be replacement, they should provide nerfs to stats in almost all cases (excepting small ones like improved iron sights).
For example
* If the mod lowers dispersion, it should lower damage and range or increase weight noticeably. Not recoil (or not just recoil) since sniper rifles should have that "mod" by default
* If the mod lowers recoil, it should increase bulk or dispersion or lower damage
* If the mod lowers bulk, it should lower combat viability or at the very least make it harder to deploy (such as the collapsible stock mod)

Until then, it's better to keep the mods with added bulk, to make them harder to holster, to make strength matter a tiny bit when using them etc.

**Comment by moosestrangler** [comment]
> Until then

Already implemented. Short barrels reduce muzzle velocity, extended barrels increase volume and recoil, bulky underbarrel additions increase dispersion. The numbers need fixing for most of them but the possibility is there. 20lbs carbines with two stocks are unjustifiable even with the current mod implementation.

**Comment by Coolthulhu** [comment]
> Already implemented.

Not for stocks and grips, which are mostly just buffs.

**Comment by moosestrangler** [comment]
Some of the stocks and grips have nonsense stats. A stock shouldn't improve dispersion. They need fixing.

**Comment by kevingranade** [comment]
Nothing actionable in here
