### ISSUE TITLE
Generic guns broken again

### ISSUE THREAD

**Issue by mugling** [CleverRaven/Cataclysm-DDA#17157]
The JSON load errors can be fixed and the definitions brought in-sync, possibly via the syntax discussed in #14250:
```
{
    "id": "glock_19",
    "copy-from": "glock_19",
    "type": "GUN",
    "name": "semiautomatic pistol",
    "description": "A typical sidearm for the police, military, and licensed civilians."
},
```

The question is though is anyone actually using this mod as nobody ever complains upon breakage and I suspect the work going into maintaining it greatly exceeds the maintenance costs.

**Comment by pingpong2011** [comment]
I don't use the mod just because I don't normally use mods, but I might use it if I was sure I could just look at a gun and it says "name" "ammo". The whole point of generic guns would be to limit the, uh, obsession with explicit fancy gun, and even if it changed the names, if I couldn't tell at a glance what the class and ammo is, there's not really a point. "pistol 19mm" would make sense, but "semiautomatic pistol" is useless because it barely tells me anything more than the original name.

**Comment by Coolthulhu** [comment]
Would make sense to make poll on forums. There are people who don't have github accounts, but post on forums.

**Comment by mugling** [comment]
I don't have an account. Perhaps someone can post there?

**Comment by Coolthulhu** [comment]
http://smf.cataclysmdda.com/index.php?topic=12776.0

**Comment by mugling** [comment]
@Coolthulhu Thanks.

@kevingranade Is two weeks sufficient to collect the broad range of opinion?

**Comment by BorkBorkGoesTheCode** [comment]
@mugling it is easy to create an account on the forums, all you need is a new password and an email account.

**Comment by nikheizen** [comment]
I use Generic guns with the disabled magazines, even though they are totally broken at present. I would very much like if it could be fixed and may submit a fix myself if I start looking through the code.
If anyone does decide to start maintaining it, I would appreciate ammo counts being lessened. Since all ammo is compatible, you end up getting too much too easily.

**Comment by mugling** [comment]
It's mostly working again now thanks to the effort of @nikheizen
