### ISSUE TITLE
Game Segfault on Launch 

### ISSUE THREAD

**Issue by Treah** [CleverRaven/Cataclysm-DDA#17177]
Linux Curses version below. Segfaults when trying to load the game. Will try and walk down git and see where i can find a working version and narrow down which commit broke. 

commit 311bffda14f44f42fa2e9eee28df60231b679b62
Merge: 841d7cc 9238298

**Comment by Treah** [comment]
To be clear this is when running the executable before you even get the menu.

**Comment by Coolthulhu** [comment]
OK, got it:

Seems that `string_id<Skill>::NULL_ID` is not initialized at the time it is used in `place_monster_iuse` constructor.
The PR that caused the crash is #17058 since it creates the `place_monster_iuse`, which accesses the `NULL_ID`. Though the actual source of the bug may be lower, in `string_id` template.

**Comment by mugling** [comment]
Fixed in #17179
