### ISSUE TITLE
Stat Damage should be fatal

### ISSUE THREAD

**Issue by evilexecutive** [CleverRaven/Cataclysm-DDA#17187]
This has really bothered me recently, but as it turns out cataclysm doesn't have any severe consequences at all for your stats being damaged to 0. You can have an Intelligence or Strength of 0, and you still won't die despite being completely brain-dead. This is a staple of roguelikes and RPGs where you can die from Stat Loss, such as D&D claiming that any stat being reduced to 0 causes you to die, either from Brain Death(If it's a mental stat), or Heart Attack/respiratory failure(If it's a physical stat). 

I'm basically saying that there should be a check that kills the player if any of their stats is reduced to 0, maybe even display a special death message whenever it happens. "You feel your last thoughts drift away into nothingness as your brain dies", or "You seize up and stop breathing."

This could also open up new consequences, such as monsters that deal temporary stat damage, which can accumulate with other sources of stat damage. But right now the biggest contributor to getting stats to 0 is Frostbite, which deals dexterity damage, and Pain, which deals a ton of intelligence damage. Obviously if you get too much frostbite, your body shuts down and you stop breathing. This in and of itself could facilitate freezing to death.

**Comment by evilexecutive** [comment]
Oh, here's a few examples of texts for each stat-loss related death

Strength: "You feel a terrible pain in your chest, then you collapse."
Dexterity: "You seize up and stop breathing"
Intelligence: "You feel your last thoughts drift away into nothingness as your brain dies"
Charisma: "*character* Lost the will to live. For a brief moment, you looked down upon a body that is no longer yours."

**Comment by Solusphere** [comment]
I don't like it, to be honest. It feels like it would only exist to conform with other roguelikes. Cataclysm, in many ways, is more of a simulator than a roguelike. Having a character die because they ran out of charisma makes no sense at all. While you could argue that enough pain to drop your strength to zero should kill you, it should be the pain that kills you, not the strength drop.

**Comment by Rivet-the-Zombie** [comment]
I'm opposed to killing the player in this scenario, but I could dig something less severe in its place.

It's a LOT easier to have a stat drop to zero in DDA than it is in any of those other games.

Also,

>Charisma

Are you sure we're both playing the same game?

**Comment by Solusphere** [comment]
Haha, I'm so used to having charisma as a stat in my game that I totally didn't catch that XD

But yeah running out of perception should make you blind, or at worst unconscious, not dead.

**Comment by Darkyhard** [comment]
I think that having 0 in any stat shouldn't cause instant death, but it should cause something that results in nearly 100% chance of death if in dangerous situation (if this happens, the character will almost certainly die anyway, but this would add some "fun" to the process), but is usually not deadly otherwise. Here are some examples of what could happen.

If character has strength or dexterity of 0, they are completely unable to do anything until these stats are above 0.

If character has intelligence of 0, the player loses control of their character, the character drops what they are wielding and starts wandering around like a monster, trying to attack (or run away from?) moving things (monsters and NPCs), smashing objects that get in the way and being attracted/frightened by sound. This stops when intelligence gets back above 0.

If character has perception of 0, they simply go blind. Sight returns when perception is above 0.

**Comment by illi-kun** [comment]
> If character has perception of 0, they simply go blind.

Why only this? Character should list all senses, so it should go blind, deaf, and also do not provide feedback messages about colliding into something.

**Comment by Darkyhard** [comment]
> Why only this? Character should lost all senses, so it should go blind, deaf, and also do not provide feedback messages about colliding into something.

Heard sound volume doesn't currently depend of perception value. Not sure if this is intended or not, but if it is, this means that perception doesn't affect hearing.

And about lack of colliding messages: how is the player supposed to "tell" character to attack a specific tile instead of trying to walk into it (during combat, for example) if this happens?

**Comment by Coolthulhu** [comment]
This doesn't make sense.

Someone with bad coordination (4 dexterity) getting shakes (-4 dexterity) shouldn't drop on the ground in an epileptic fit, just waddle around having problems with small objects like cell phones.

> If character has perception of 0, they simply go blind. Sight returns when perception is above 0.

No real effects at perception 1, then sudden loss of eyesight at 0?

> If character has intelligence of 0, the player loses control of their character

Now that's just fantasy. I could understand catatonia (even though it wouldn't make much sense either), but turning into a mental zombie because you are in pain/on adrenaline?

> It's a LOT easier to have a stat drop to zero in DDA than it is in any of those other games.

This

Also:
* Pain causes a lot of intelligence loss, 4 int character is likely to end up at 0 int when in any kind of severe pain
* Perception and eye encumbrance use roughly the same units. Welding goggles are comparable to losing 4 perception
* Depressants cause major stat loss
* Freezing/scorching temperature cause a major stat loss
* Adrenaline causes a large intelligence loss

When looking at "realism", the whole idea of stat death/stat paralysis is pretty much instantly out, having no IRL equivalent at "stat" scales comparable to those in the game. 4 intelligence doesn't mean "has half the brain power of 8 intelligence person".

I'd be still in favor of it if it served a gameplay purpose, but I don't see any.
* Dump stats are much less useful than they once were, now that dexterity is mostly defensive and perception affects crit rate. Meaning there is no need to punish hard for taking 4 perception
* Pain already hits hard enough as it is. In fact, I'd rather nerf the pain penalty, since typical character death from non-hulk combat goes like "walk in the park -> get hit a few times -> lie on the ground crying while getting murdered by weak stuff"

Now, adding more penalties for LOWERED stats - that would make sense. Lower vision for <10 perception, less cutting/piercing damage for low strength, intelligence allowing autolearn of crafts above current level etc.

**Comment by kevingranade** [comment]
I mostly agree with Coolthulu's take on it, it's way too easy to get to 0
in a statement for such severe penalties.

Just to throw it out there though, what about much larger penalties (e.g.
down to -10 or so) causing the catatonia, paralysis, or blindness effects
mentioned above? This would basically resale stats of 0 to mean "barely
functional" or similar, and you don't get to real inability to even act
unless it gets much lower.

**Comment by Rivet-the-Zombie** [comment]
When your strength hits zero you pretty much collapse under the weight of your own hair, so we've already got that much.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
