### ISSUE TITLE
Welder, makeshift welder and bionic toolset charges for recipes are inconsistent.

### ISSUE THREAD

**Issue by Cyrano7** [CleverRaven/Cataclysm-DDA#17206]
Sometimes the ratio is 1 to 1. Sometimes it's 1 for the welder and 1.5 for the others. And there are some other variations. I like the 1 to 1.5 ratio. The welder should be the most efficient one. Anyone else have a opinion?

**Comment by Coolthulhu** [comment]
It should be 1 to 1.5 in all cases. It would be the best if we could enforce it from the code side by automatically generating extra entries.

**Comment by Cyrano7** [comment]
@Coolthulhu whats the rule for the soldering iron? 1 to 1 with the toolset? Also there are a few recipes that have the welder and soldering iron like the wetsuit one which seems strange.

**Comment by Coolthulhu** [comment]
> whats the rule for the soldering iron? 1 to 1 with the toolset?

Yes.
Meaning that it should get (at least) 1.5 the cost of welder when both are allowed.

**Comment by mugling** [comment]
> It would be the best if we could enforce it from the code side

Every time I look at this I struggle to find an easy to implement elegant solution

**Comment by Coolthulhu** [comment]
It could work like this:
* The `"sub"` ("works as x tool for purposes of crafting") field would become an array - one value for the tool, other for cost multiplier
* A tool with no `sub` would get `sub` to self with `1.0` multiplier
* Somewhere a map of `sub`s to arrays of tools with given `sub` would be kept
* On recipe finalization, each tool would be replaced with a list of its subs

Alternatively, the multiplier could be a divisor, so that higher is better.

Later on, the `sub` could stop being required to be a valid item id and could instead become some sort of abstract id. For example, a quality id.
Then the value could be displayed on the item's info as "This item provides 30 heat per 100 charges".
At this point we could stop unrolling the recipes into "hotplate 3, oil cooker 40" and just leave them as "heat 30" and let player do the math.

**Comment by pingpong2011** [comment]
@Coolthulhu that'd be a pretty neat way of doing it. You could also go the other way around, that once it's implemented, you state the heat, and if the tool was available, how much charge it consumes. next to the heat requirement. Or probably easier, in a sub-menu, like when it asks what you want to craft with (this doesn't state quantity either, un-wielding weapons states turns, so code exists somewhere for this sort of thing).

**Comment by mugling** [comment]
> Later on, the sub could stop being required to be a valid item id and could instead become some sort of abstract id. For example, a quality id.

An implementation of `quality_id` allowing consumption of charges is a good design and we could consider implementing this extension as opposed to writing another near-equivalent system via `sub`

**Comment by kevingranade** [comment]
On Jun 17, 2016 2:44 PM, "mugling" <notifications@github.com> wrote:
>>
>> Later on, the sub could stop being required
>> to be a valid item id and could instead
>> become some sort of abstract id. For
>> example, a quality id.
>
> An implementation of quality_id allowing
> consumption of charges is a good design and
> we could consider implementing this
> extension as opposed to writing another
> near-equivalent system via sub

In other words, do the same thing, but declare and store the crafting
multiplier as a parameter of a tool's quality field. That does sound like
an improvement.

**Comment by mugling** [comment]
@kevingranade yes

**Comment by mugling** [comment]
This was solved via recipe `using` syntax. Updating all recipes to use it is a more widespread issue
