### ISSUE TITLE
Joint Torsion Ratchet provides power every other step

### ISSUE THREAD

**Issue by pingpong2011** [CleverRaven/Cataclysm-DDA#17220]
0.C-15013-gdffc5a5

117 Base Move Cost, Current speed 100

**Comment by Coolthulhu** [comment]
Working as intended then.

**Comment by pingpong2011** [comment]
I would disagree because it means a UPS flashlight and a UPS mp3 player can be left on indefinitely with a net gain in power.

**Comment by Coolthulhu** [comment]
It's certainly not a bug

If you want a balance discussion, edit the first post and describe the issue, possibly proposing a solution.
At the moment it looks like a bug report and there are no bugs here.

**Comment by TempestMaiden** [comment]
There's a bunch of bionics that use up proportionately more limb space than torso space, and a larger number that use them up at more-or-less the same rate.

The +Str and Dex CBMs, Hydraulic Muscles, armor plating...

Interestingly, most of the useful ones that prefer limb slots are passives; I don't think the bionic slots system is going to make the fusion blaster arm any better a pick, and the railgun cbm is of very questionable value.

There should probably be more, but the power from the torsion ratchet already isn't free. It uses up over a third of your arm slots instead of using less than a third of your torso slots, and compared to anything but the solar panels, it gives shitty power generation.

Solar panels should probably be buffed, instead.

**Comment by illi-kun** [comment]
@TempestMaiden it's better to post this in #16920 instead of this closed issue.
