### ISSUE TITLE
Scissor jack found in common vehicles can't lift those vehicles

### ISSUE THREAD

**Issue by romkuma** [CleverRaven/Cataclysm-DDA#17231]
The "jack_small" item is found in the cargo storage of common vehicles including the SUV, but doesn't have the lifting capacity to change the tyres on the SUV or pickup (and probably other common vehicles).

Probably could be fixed by upgrading it to JACK level 3 (1500 kg), or alternatively by introducing a new item (do real SUVs have a heavier duty jack than smaller vehicles?).

**Comment by TheWebfrog** [comment]
I agree this is the case

Maybe just changing the spawns might help

**Comment by Solusphere** [comment]
I feel like jacks should be buffed across the board. Currently the stats seem to assume a low end of the current existing product range for the types of jacks available. Given that vehicles in cataclysm tend to be a little heavier than their real life equivalents in my experience, I think it would be reasonable to just use the upper IRL curve for max load.

Current ingame scissor jack max load: 1000kg.

IRL 1500kg scissor jack: https://www.amazon.co.uk/Premium-Scissor-Jack-Loading-Capacity/dp/B001QV4Y0O

Current ingame bottle jack max load: 3000kg

IRL 4000kg bottle jack: http://www.supercheapauto.com.au/online-store/products/Kincrome-Hydraulic-Bottle-Jack-4000kg.aspx?pid=322393#Recommendations

I did a little research regarding the telescopic cantilever, but neither I nor google can seem to figure out what the hell it's actually supposed to be. Is it a cherrypicker-style telescopic boom, or a delivery-truck-style cantilever lift, or what?

**Comment by DaliTimelord** [comment]
Before I try my hand at this issue I wanted to point out some things:

- Irl Scissor jacks lift about 3 tons (~6 Jacking, where 1 Jacking = 500 Kilograms). https://www.alibaba.com/product-detail/3-ton-scissor-jack-small-scissor_60311818255.html
- Irl Bottle jacks, on the other hand, **are absolutely broken**. Some can lift 10 tons (18 Jacking), others can lift 20 tons (36 Jacking), _some can even lift 100 tons (~182 Jacking!!!)._ These weigh slightly more than a scissor jack. http://www.jettools.com/us/en/p/jhj-100-100-ton-hydraulic-bottle-jack/453399K
- Irl Floor jacks, in comparison to other jacks, are terrible. They can only lift as much as a scissor jack, but weigh 4x as much. The benefit of having wheels is not currently advantageous.
- If there would be a tier list of jacks, they would mostly consist of bottle jacks, as well as having no suitable 'medium' bottle jack. Having a 100 ton jack work would obsolete cantilevers.

So: Should scissor Jacks should be buffed to 3 tons, bottle jacks to be buffed to 10 tons, and floor jacks will not be added due to impracticality? Maybe this can be revisited when jacks become disassemblable.

**Comment by mugling** [comment]
> Irl Scissor jacks lift about 3 tons (~6 Jacking, where 1 Jacking = 500 Kilograms).

Misleading as not one item on the first page of amazon results is 3000kg. The average is about 1400kg

> Some can lift 10 tons (18 Jacking), others can lift 20 tons (36 Jacking)

Again misleading. Similar amazon search shows an average of 5000kg.

Note those are also on flat incompressible surfaces. Performance on grass would be **much** worse.

**Comment by mugling** [comment]
> some can even lift 100 tons

...and are also thoroughly useless for changing a wheel. Once you get anywhere near that sort of weight the two sane options are lifting or digging a hole under the wheel.

**Comment by DaliTimelord** [comment]
> Misleading as not one item on the first page of amazon results is 3000kg. The average is about 1400kg
> ...
> Some can lift 10 tons (18 Jacking), others can lift 20 tons (36 Jacking)
> Again misleading. Similar amazon search shows an average of 5000kg.
> 
> Note those are also on flat incompressible surfaces. Performance on grass would be much worse.
> ...and are also thoroughly useless for changing a wheel. Once you get anywhere near that sort of
> weight the two sane options are lifting or digging a hole under the wheel.

Thank you for the clarification!! Although, that still means that jacks need to be buffed to the averages? I don't know if there's a way for the game to tell if you're conducting the jacking on a solid surface or grass (maybe relying on traction).

**Comment by mugling** [comment]
> Although, that still means that jacks need to be buffed to the averages?

It might be reasonable to consider an increase in both `volume`, `weight` and `JACKING` for the bottle jack.

> I don't know if there's a way for the game to tell if you're conducting the jacking on a solid surface or grass (maybe relying on traction). That would be a nice feature though.

It's fairly easy to implement. Lets float that as an idea and see if anyone can come up with any flaws in it though. I might also implement digging a hole to change wheels.

**Comment by Coolthulhu** [comment]
I hear mostly complaints about jacks so far. It would be a good idea to have a mod disabling them (and making them use welders).

While they are pretty realistic in that they are required, they don't achieve their purpose (limiting early deathmobiles) because they are common enough not to matter when building a deathmobile, but rare enough to matter when setting up the first vehicle. Should be the opposite - early vehicles have enough problems as is and setting up a working but banged up and shitty car shouldn't require welding it.

IRL a great deal of cars (most of them?) carry a jack and a spare wheel.

It could be a good idea to abstract out the early jacks and just keep the ones for 3+ tons vehicles. Then make the 3+ tons ones rarer, limited to garages and places that spawn trucks.
This could ease in the transition to jacks, because they are still among the worst received features so far. They're on every "laundry list of bad things added to DDA recently" I keep seeing one the forums and outside them.

**Comment by mugling** [comment]
> It would be a good idea to have a mod disabling them
> "laundry list of bad things added to DDA recently" I keep seeing one the forum

I'm not keen on the mod for everything approach and am wary of 1-post forum accounts for which there is a high risk of sock puppetry (a risk in all forums). The reply from @Soyweiser was accurate in that we care most about those that contribute either code or useful suggestions. Repetition of an argument provides neither and doesn't increase it's importance.

> While they are pretty realistic in that they are required, they don't achieve their purpose

I'd agree they currently don't meet their design goal but I don't think it would be too difficult to achieve that.

> IRL a great deal of cars (most of them?) carry a jack and a spare wheel.

Yes, but we can assume the spare has already been looted.

Presuming their are four classes of vehicle
* Bicycles
* Light vehicles (motorbike, car)
* Heavy vehicles (truck, military)
* Deathmobiles

The question is how to ensure reasonable progression.

* Firstly bicycle wheels are exceptionally rare. We could perhaps change mapgen so that bicycle's aren't smashed up so much.

* Secondly we could implement digging under wheels on soft ground. That would help for motorbikes as you could drag them to appropriate ground. Cars could always spawn with a scissor jack.

* The bottle jack could increase to 5-tonne but become rarer and possibly require a flat sturdy surface to operate on. IRL most large vehicles have four tyres per axle so that the vehicle can still be driven to a suitable surface after one tyre is lost. An implementation of towing vehicles would be helpful but I'm not sure how practical this would be in the current code base

* Deathmobiles don't require balancing. A fix for the currently broken hard-cap on the boom crane should suffice.

**Comment by Coolthulhu** [comment]
> I'm not keen on the mod for everything approach.

Me neither, but a mod is better than waiting for the whole deal to be fixed, especially without good ideas.
And sometimes it's either mod to disable or disable for everyone, like with filthiness.

> Repetition of an argument provides neither and doesn't increase it's importance.

Except when it's from a lot of different people, many of whom played the game for a long time.

Plus, they do have a good point - that jack is just another component required for crafting. The binary "you can craft" vs "you can't craft". This makes the whole deal similar to forge setup requirement.

**Comment by mugling** [comment]
> Except when it's from a lot of different people, many of whom played the game for a long time.

A number of those posts are from throwaway accounts. Yesterday someone registered an account, repeated the familiar argument about filthy clothing then proposed a fork excluding it. In their second post they then outlined an exceptionally complex mechanic for damaged clothing including both degree's of filthiness and repair of individual bullet holes. It's hard to determine what will satisfy that user?

Longstanding posters however should expect some weighting to any suggestions. I probably should read the forums more and I do always appreciate it when you cross-post relevant discussion here.

> Me neither, but a mod is better than waiting for the whole deal to be fixed, especially without good ideas.

I gave some options in my above post and no doubt you'll have further. I'd like to concentrate on fixing problems with a design rather than providing further configuration switches.

**Comment by kevingranade** [comment]
> It could be a good idea to abstract out the
> early jacks and just keep the ones for 3+ tons
> vehicles. Then make the 3+ tons ones rarer,
> limited to garages and places that spawn
> trucks.

How is this different from having a crappy scissor jack spawn in a high
proportion of vehicles and making bottle jacks rarer? I'm assuming you can
automatically use a jack stashed in the vehicle you're working on, which
very much seems like something that should be allowed.

**Comment by Cyrano7** [comment]
Soooo I guess this is fixed now?
