### ISSUE TITLE
Filthiness affects everyone, but isn't well designed enough for mainline

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#17254]
Filthiness is a relatively intrusive mechanic without much actual impact.
When it was tied to a trait, it was a voluntary thing. Now everyone has to deal with it.

It isn't difficulty to deal with it because:
* The penalty doesn't stay with you once you remove the filthy clothing
* When you really need to use the filthy items, the filthiness doesn't really matter
* Even with the trait, you eventually can use all items, you only need some soap and water source, which are only hard to find early on
* Zombie items almost universally require repairs before use, meaning only some rare drops (flame-resistant underwear) really require cleaning
* It isn't passed around when crafting

At the same time it can't be said not to be intrusive:
* The morale penalty will stay with you during crafting, unless you manually remove (and then put back on) the filthy clothing
* You can't wait it out, like it is the case with wetness penalty
* Removal requires semi-rare components (soap) and access to water. Ironically the best water access in a city will be the sewer - you'll be cleaning filthy clothing with sewer water
* It is bugged at times due to unstable morale system which doesn't recalculate stats often enough

The biggest problem is that it doesn't properly split two exclusive sections of the game: action and downtime
During downtime, protection doesn't matter much. You don't start crafting in the middle of Hulktown. Warmth also matters surprisingly little - you can just wrap yourself in a blanket. Morale does matter, though.
During action, morale doesn't matter much. Focus will drop really fast during combat and even 50 points of morale won't make a big difference here. What does matter is protection, storage and (to lesser extent) warmth.

End result is that advantages during combat and scavenging are balanced with tedium during crafting and resting. Balancing with tedium is pretty much the closest thing to "objectively bad" there is.

At the very least there should be a mod disabling morale penalty for filthiness. Though honestly I don't see a good justification for filthiness penalty in its current state to be enabled by default. It would be better off disabled for those who don't explicitly pick a mod that enables it or the "squeamish" trait.

**Comment by mugling** [comment]
> It would be better off disabled for those who don't explicitly pick a mod that enables it or the "squeamish" trait.

Penalty should only apply if you are `squeamish`

**Comment by Vidiveni** [comment]
Though I agree with Coolthulhu's points, I will probably pick `squeamish` every time solely because it reduces tedium for me when looting large amounts of zombie corpses. The brown gives a nice color filter when searching for interesting loot using `V`.

**Comment by Night-Pryanik** [comment]
It'll be ok for me if the system will be reverted back to the mod, like at the very beginning.

**Comment by Rivet-the-Zombie** [comment]
I like the basic idea behind it, it just needs some bug fixes.

**Comment by bumpkindda** [comment]
If it's getting axed I'd rather see it in a mod than a trait. I don't think it's particularly 'squeamish' to dislike wearing rotten zombie-guts clothing.

**Comment by Fallingferret** [comment]
I'd rather the penalties just mostly effect squeamish trait characters. The world has gone to shit, the last thing I'm worried about would be dirty clothes.

The idea is neat, but needs a little polishing.

**Comment by codemime** [comment]
> The world has gone to shit, the last thing I'm worried about would be dirty clothes.

You can get -50 for simply being wet. I expect that rotten flesh is worse than clean rain water.

**Comment by Fallingferret** [comment]
Technically the rain water isn't clean either. :^) you're right though, I didn't assume the flesh may still be stuck to the fabrics.

We could really go into it with this system if we wanted to though. - (Bloody) (Slimy) (Dirty) (Smelly) Rather then just "Clean" to "Disgusting"

**Comment by Breligar** [comment]
If this is going to stick around, the ability to clean items needs to be a little more accessible while removing some of the oddities, like the aforementioned washing your socks in raw sewage. I'd suggest being able to wash clothing in the various water-filled toilets strewn about. That would require you to make a special trip into potentially dangerous areas if you want to clean something without it being too crazy.

Beyond that, the concept of zombies having rot and muck all over their clothes makes sense to me, and not enjoying wearing those clothes also makes sense to me. I'm fine with a simple way of handling it, like this. Anything more complex and it'll turn into irritation rather than fun. If people want in-depth hygiene then that could be fun, but it should likely be a mod, not baked into the main game.

**Comment by Night-Pryanik** [comment]
Then using sewage water for crafting food and drinks is normal, but using it to wash clothes is bad. Ok, very consistent.

**Comment by flitvious** [comment]
Cleaning is not very realistic currently, because it requires soap and (huge amounts of) water. It would be more realistic to have an ability to use smaller amounts of water and common cleaning agents (bleach, ammonia) instead. This would also add usefulness to those items for starting characters.

Also, do water requirements depend on the item volume? Cleaning a filthy hairpin shouldn't take a bucket of water.

**Comment by Night-Pryanik** [comment]
> common cleaning agents (bleach, ammonia) instead.

IIRC it isn't possible now to use several different kinds of "ammo" for a tool.

> Also, do water requirements depend on the item volume? Cleaning a filthy hairpin shouldn't take a bucket of water.

No, but this is a good idea.

**Comment by bumpkindda** [comment]
Wouldn't it be possible to make the washboard a non-loadable tool that doesn't consume charges like ammo, but checks for soap (or bleach or lye etc.) the same way it checks for water?

**Comment by Night-Pryanik** [comment]
Yes, it is possible.

**Comment by Coolthulhu** [comment]
I just had an idea on how to make filthiness matter where it should:
Filthy armor could increase the chance of infections on the parts they armor.
This would make them matter on combat armor, which is where it actually should matter, and not on "craft wear" where it shouldn't have any effects.

**Comment by flitvious** [comment]
> Filthy armor could increase the chance of infections on the parts they armor.

Then introduce zombies that make player items filthy.

**Comment by RadaRadaRada** [comment]
Boomers, maybe?

**Comment by Vidiveni** [comment]
> Wouldn't it be possible to make the washboard a non-loadable tool that doesn't consume charges like ammo, but checks for soap (or bleach or lye etc.) the same way it checks for water?

Would like this so you don't have to pick it up and reload sometimes. This prevents a small tedium similar to when cooking alot with a hotplate.

**Comment by kevingranade** [comment]
> It isn't passed around when crafting

Is the only valid complaint on the list, and even that is just a bugfix away.  Everything else is either an underlying bug that needs to be fixed anyway, or working as intended.  Most are even contradictory in that they're problems with both being able to and not being able to use the affected items.

> you'll be cleaning filthy clothing with sewer water

This in particular needs to be reversed anyway, you shouldn't be able to get potable crafting water from the sewer.

> do water requirements depend on the item volume? Cleaning a filthy hairpin shouldn't take a bucket of water.

That's a good adjustment, also said hairpin *could* be immune to filthiness, but that might be more involved than it's worth.

> Filthy armor could increase the chance of infections on the parts they armor.

I'm totally onboard with this, in fact it fits nicely into the way I want to overhaul health and wounds.

**Comment by Coolthulhu** [comment]
> Most are even contradictory in that they're problems with both being able to and not being able to use the affected items.

I explained it below that.

The penalty doesn't matter during combat.
The penalty does matter for crafting.
Removing armor is trivial and safe, but tedious.

The penalty only causes tedium, not difficulty.

**Comment by bumpkindda** [comment]
Fiddling with your armor to game out a small morale malus while grinding sounds to me like player-made tedium that'll only affect the minmaxers who actually do it. I do like the idea of making it matter in combat via infection chances, though.

**Comment by Coolthulhu** [comment]
Making min-maxing tedious implies making optimal gameplay tedious. Literally just "if you want to play well, enjoy wasting time".
DDA is unfortunately quite full of tedium, but most of it is meaningful. Manually taking off armor to sleep or craft is not meaningful.

**Comment by bumpkindda** [comment]
Min-maxers are going to do tedious things no matter what. I once found an oblivion guide that detailed how to grind all your skills up in a safe area by running around, jumping thousands of times, and sneak-walking into a wall with people on the other side for hours. He also said the game was kinda boring.

If there are players who are gonna wear filthy zombie clothes and then manually take them on and off to avoid a small morale debuff while they assemble and disassemble a flashlight 40 times, that kind of tedium is pretty much of their own making.

**Comment by Coolthulhu** [comment]
> Min-maxers are going to do tedious things no matter what.

Games will always break. Doesn't mean bugs shouldn't be fixed.
People will always randomly die to bad luck. Doesn't mean we should put 1 move instakill abilities in the game.
Game will always have some tedium. Doesn't mean we shouldn't try to remove any and just put nested menus everywhere.

"Balance" of filthy clothing is like that of nested menus: it penalizes the player with extra clicks, not the character with anything.

> while they assemble and disassemble a flashlight 40 times

Recrafting same stuff over and over is also a problem. Except one that doesn't have a trivial fix and thus it isn't (as much of a) bad design to keep it around.

**Comment by bumpkindda** [comment]
I'm not arguing against improving it. I think making it matter in combat with higher infection rates or even a risk of nausea spells is a great idea. I think making it a lasting debuff like 'wet' that trickles away after you remove the clothes is a great idea. Removing ways to get use out of filthy clothes but exploit your way around the penalties can only be a good thing.

I'm just arguing against cutting the feature out of mainline because some players will figure out how to exploit their way around it and then get upset that they have to fiddle around making extra clicks to exploit their way around it.

**Comment by Coolthulhu** [comment]
> I'm just arguing against cutting the feature out of mainline because some players will figure out how to exploit their way around it and then get upset that they have to fiddle around making extra clicks to exploit their way around it.

That's a part of what design is about: not rewarding exploits.
Not making the game about dropping skewers under things and lighting those up.
Not making the game about flashlight meditation/crafting clean water until 10 cooking like it was in old versions.

Giving the player a choice between having fun or being good is also a really, really bad way of achieving anything. It should be avoided whenever possible.

> cutting the feature out of mainline

It doesn't mean removing it entirely from the game. Just not burdening everyone involved with a feature that wasn't well thought out or at least isn't finished.
There are way better things that aren't mainline - for example Generic Guns mod.

Also, mainlining a feature is possible and was done before. Moving bad crap to a mod happened like once. We still have fursuits in the core game. And vibrators, flaming weapons (which no one uses because "lmao what is design"), cat ears and golden rapper "grills".

**Comment by BorkBorkGoesTheCode** [comment]
> We still have fursuits in the core game. And vibrators, flaming weapons (which no one uses because "lmao what is design"), cat ears and golden rapper "grills".

I have no objection to any of these. Out of all the miscellaneous items in the game why do you dislike these? Surely the 5+ versions of underpants are more worthy of excision.

**Comment by kevingranade** [comment]
If you're concerned about it, make it matter for the use cases you care about too.  The infection vector is a reasonable thing to do, as is a lingering penalty, and neither would be particularly difficult to implement.

**Comment by Coolthulhu** [comment]
> If you're concerned about it, make it matter for the use cases you care about too.

The problem is mostly the opposite one:
It shouldn't matter when it can be trivially defeated.

Ideas for the action side:
* Infection being more likely - on hit, not over time
* Smell attracting zombies
* Stat debuff based on "filthiness threshold"
* Random move wasting actions - like itching or retching, but without the annoyance to the player
* Sticky grime making grab attacks more likely
* Increased encumbrance due to discomfort

But then, that's certainly not enough to make it not bad. It has to be fixed too, so that it doesn't end up a gold plated, polished, turd.
That morale penalty is a problem for the reasons outlined in details above: pure tedium, no difficulty.

**Comment by BorkBorkGoesTheCode** [comment]
Why not add filthiness to characters instead?

**Comment by bumpkindda** [comment]
Why wouldn't a lingering debuff solve the morale penalty problem?

**Comment by Coolthulhu** [comment]
> Why wouldn't a lingering debuff solve the morale penalty problem?

Because then you still have that part where you have to manually remove everything before sleep or crafting for longer than debuff's length.
And then some genius will figure out that it should be cleanable.
So we'll get a totally fun mechanic of having to undress and take a shower. Completely non-automatized, with picking up the drops and rearranging them being all manual.

> Why not add filthiness to characters instead?

Because we're talking about filthy clothing's morale penalty, not adding another mechanic without thinking it out first.

**Comment by Vidiveni** [comment]
> Min-maxers are going to do tedious things no matter what. I once found an oblivion guide that detailed how to grind all your skills up in a safe area by running around, jumping thousands of times, and sneak-walking into a wall with people on the other side for hours. He also said the game was kinda boring.


I see no reason to make minmaxers suffer, as if their feelings don't matter. Even non-minmaxers may feel bad from knowing they are penalised for not taking gear off when it's time to craft something. I lost all will to play when the character was bugged with a mere -6 morale penalty. Unmodded Oblivion has a terrible skill system. 

> Infection being more likely - on hit, not over time
> Smell attracting zombies

I particularly like the first . Not sure if the smell one would make sense though, as being covered in zombie/blob filth might make more sense to be camouflaging the human smell.

**Comment by Coolthulhu** [comment]
> as being covered in zombie/blob filth might make more sense to be camouflaging the human smell. 

Could use the same excuse as L4D boomers: that it (L4D boomer bile or DDA goo) reacts with human sweat to avoid "marking" allies or terrain, yet still make hosed humans smell.

**Comment by bumpkindda** [comment]
> Because then you still have that part where you have to manually remove everything before sleep or crafting for longer than debuff's length.
And then some genius will figure out that it should be cleanable.
So we'll get a totally fun mechanic of having to undress and take a shower. Completely non-automatized, with picking up the drops and rearranging them being all manual.

... or you could just avoid wearing filthy rotten zombie-smeared clothing unless it's an absolute necessity, like any normal person would in that situation.

**Comment by Coolthulhu** [comment]
I wish I could just passively-aggressively post a link to "how to design a game" webpage, specifically "crap that may look good on paper but is actually shit" section.
After getting multiple replies to why is tedium bad, you decide to ignore all of that and fall back to
> but realism therefore it is allowed to be tedious

Next station: bodily functions. Those are realistic! Diarrhea is a significant risk of dehydration!

**Comment by bumpkindda** [comment]
Tedium is bad. I agree. That's why I don't wear filthy clothing unless I feel it's absolutely necessary, and I accept the morale penalty when I do. This taking-off-clothes-to-craft routine is a thing that will only ever be tedious for people who are deliberately using an exploit to game themselves a marginal increase in grinding speed, because nobody else is going to do it. The problem isn't 'tedium', the problem is that there's an exploit ; an extremely minor exploit compared to throw-sock-and-light-it zombiekilling or moving giant stacks at superspeed in advanced inventory by using enter instead of move-all, or the fact that a single rainwater collection funnel outstrips consumption by a good 20x since acid rain was removed, or walking right up to anti-mat turrets by pushing a frame with a board attached. Exploits exist. It'd be great if they all get removed eventually. I don't see how the amount of tedium that goes into accessing an exploit factors into anything. If it's tedious, just stop doing it.

I've been playing cataclysm with the filth system ; the filth system is fine. Not just on paper, it's fine in practice. It obviously still needs some bugfixing and tweaking, but it's a good system. It's a great addition to the game, it devalues early game zombie clothing drops (which are everywhere) and adds value to scavenging houses and stores for clothing.

**Comment by Vidiveni** [comment]
> that will only ever be tedious for people who are deliberately using an exploit to game themselves a marginal increase in grinding speed, because nobody else is going to do it. 

Those people matter too. And this would not be considered an exploit by most people. I like the early game changes too introduced by this nerf to zombie clothes, but we can make it less intrusive for gameplay's sake.

**Comment by Coolthulhu** [comment]
> I don't see how the amount of tedium that goes into accessing an exploit factors into anything. If it's tedious, just stop doing it.

Let's apply this logic consistently:
> If reloading magazines is tedious, stop using ranged weapons
> If collecting food is tedious, starve
> If turning on lights on a vehicle is tedious, don't drive in the night

Then:
> it devalues early game zombie clothing drops

It already needs repairing, often from the brink of breakage. It is already barely useful, because you can just craft 90% of the useful stuff, like hoodie+underwear combo.

It fixes a problem that isn't there by introducing a problem that "you can just stop doing".

> The problem isn't 'tedium', the problem is that there's an exploit

There is no exploit, there is just tedium. Removing clothing to avoid a badly designed penalty is not an exploit - it was literally designed (badly) this way. It was designed to penalize continuous wearing of filthy items. It fails at it because it applies the wrong kind of penalty, but it isn't exploitable - just badly designed.

**Comment by BorkBorkGoesTheCode** [comment]
Clothing is also tedious, so it should be removed in favor of an abstract buff. Adding weapon mods is also tedious, let's remove them too.

**Comment by Zireael07** [comment]
@Coolthulhu, how would you fix the tedium part from the design standpoint then?

**Comment by Coolthulhu** [comment]
> how would you fix the tedium part from the design standpoint then?

Get rid of the morale penalty. Apply only penalties that matter in combat and scavenging, not in crafting.

Butchering rotting corpses doesn't cause morale penalties, carrying a backpack full of rotten meat doesn't cause morale penalties, eating rotten meat doesn't cause morale penalties (until you barf), not washing for 4 years doesn't cause morale penalties, sleeping on top of a rotting zombie corpse doesn't cause morale penalties, pain, hunger, thirst, getting attacked by a living corpse, being barfed on, eating same food over and over, having parasites, having all limbs broken in the middle of an apocalypse - not one of those causes morale penalties.
Filthy clothing doesn't need to cause morale penalties. It should if it was doable in a way that makes sense, but I don't see any here.

Just apply those penalties that actually matter for armor, not ones that matter for sleeping and crafting. Don't force any more tedium into optimal gameplay.

**Comment by flitvious** [comment]
Good stuff that "filthy for everyone" adds:
-  Early game incentive to scavenge for clean clothing. Problem is, morale doesn't matter much in the first two days (wet, cold and in pain all over anyway). Probably filthy clothes should get other effects that make them inferior to clean clothing. So there will be a choice between a clean backpack and a filthy military rucksack for early characters.
- Mid game gate to immediately using zombie loot. All those juicy drops from zombie soldiers? Have to wash everything before wearing it 24/7. Or go scavenge for military gear. This is ok in my opinion, not so easy to get good clothing. I'm actually for a mod that bans the washboard altogether.

**Comment by Izicata** [comment]
Another issue with the filthiness morale penalty is that it's a disconnect between what the player feels and what the character feels. If you're picking something up off a zombie and wearing it immediately, it's because it's better than what you've currently got or otherwise very useful, and as a player you feel good about that. If I find a pair of roller-blades off a zombie, I feel good about that because roller-blades are powerful. But if I put them on, my character feels bad because they're dirty. My character is feeling the exact opposite of what I am, and that hurts player immersion. If filthy clothing was obviously mechanically inferior to clean clothing, then this would be less of an issue.

**Comment by Labtop-215** [comment]
I think we should have implemented a mechanic for the player being filthy first, before their clothing, and that mechanic should affect, and be affected by their filthy clothing, as well as particularly gory combat, being boomered on, doing lots of butchery work, and generally walking threw dirty areas like swamps and slime pits.

Cleanliness should be a mechanics that influences moral and health, and should be expanded upon so that it's still something you can ignore or deal with in the short term, but should probably be a mid term goal for survival, along with a sustainable or large food reserve, a safe place to stay (or suitable mobile replacement), and training supplies.

Being able to wash ourselves and perhaps take a bath or a shower, while it would take tons of at least "not sewage" water, should be something that you should do every couple of days when you get the chance, since you can get sick otherwise.

**Comment by Izicata** [comment]
A fleshed-out mechanic for the player being filthy also offers more interactions with traits and mutations; a "Bloodthirsty" trait/mutation could offer a morale bonus for being covered in gore instead of a malus, a "Slob" trait/mutation could remove the morale malus for not bathing, etc.

**Comment by nikheizen** [comment]
Player filthiness somehow manages to sound even worse than clothing filthiness, which I don't like at all.
> If I find a pair of roller-blades off a zombie, I feel good about that because roller-blades are powerful. But if I put them on, my character feels bad because they're dirty. My character is feeling the exact opposite of what I am, and that hurts player immersion.
This is a very good point. I could not possibly imagine someone living in a post-apocalyptic wasteland filled with lethal monsters and murderous other people being upset because their life-saving MBR Vest that they lucked into somehow was covered in goop. You're wearing 2 layers under it any damned way. The only exception would be someone who was incredibly, how do I say this, "squeamish;" the situation is handled realistically with that trait alone.

**Comment by Soyweiser** [comment]
Why is this game mechanic implemented as a penalty? Why not make players get a morale bonus for wearing clean clothes (say +20). (And to prevent people from abusing the system, reduce morale system baseline a little bit down. (without people noticing) (say -15, so the baseline for cleaning your stuff is a bonus)) That way, it feels like a bonus when you clean your clothes. The game effect is minimal.

You could even perhaps add a "very clean" tag to clothing that goes away after a while. I'm saying, if you implement large scale penalties like this, add a benefit as well. (Remember people being mad about solar panels potentially being nerfed? People were fine when there was a potential upgrade path for solar panels. (even when the end result was still a nerf). Currently this system is only a nerf. And a bad one at that. It only makes the game tedious.

Not only is it annoying as fuck. It makes the early game even longer and more annoying. (Now you also need soap (**) and the washboard ingredients (which are pretty low atm thankfully, only fab:1). The mechanic would be fine as a penalty if it is a choice. And if a 'clean clothes' tag is implemented, the washboard still has a usage for people without the negative trait.

Please stop making stuff realistic for realism reasons only. Remember there should be some fun in the game. Just making stuff tedious is not fun. (Yeah, I'm beating a dead horse, I already mentioned this on the forums).

Another issue, CDDA is complex. Very complex. Esp if you are a new player, the filthyness mechanic is not explained at all. And as soap is pretty rare, it is not likely a new player will ever discover on it's own how to fix this big morale penalty. Now granted, most long term players will find the forums and the wiki etc. But this will still cause problems. (Lower player retention). It already confuses people.

*: I'm having a lot of trouble early game recently. I'm not a noob by any stretch, but recently I just keep dying over and over. I think some playingtesting is a bit in order. (I am playing on 2.5 normal Z amounts, but less npcs and less zombie evolution). But for some reason, it is very hard.

**: So if I understand the code, each clothing item you wash takes one soap right? That is a lot of soap you use for cleaning. Is this wanted? using up so much of the rare soap for cleaning? I suggest upping the usage of a soap bar a bit (for cleaning only) Say a bar of soap has 25 (was 10) usages. So you can at least clean most of your equipment with one. (Just multiply the other soap usages (dynamite crafting) as well).

tl;dr version:
My suggestion: Add 'clean' tag to clothing that creates positive morale. Make tag go away over time/boomered/etc. Move negative morale penalty to negative trait.

**Comment by Izicata** [comment]
>Why is this game mechanic implemented as a penalty? Why not make players get a morale bonus for wearing clean clothes (say +20).

I was just about to suggest something like that. Cataclysm does have some other personal hygiene related morale effects; shaving and cutting your hair gives you small, relatively long-lasting morale boosts, and there's no morale malus for not cutting your hair or growing a 4-year beard. Having a small, relatively long-lasting morale boost for wearing clean clothes would be both more in line with the pre-existing cleanliness morale effects, and far less tedium-inducing than the current implementation.

As for the specific number, I'd say 5 or so would be plenty for a long-term morale boost that players are going to start the game with. Maybe 10, if you want to be really generous.

**Comment by jokaro** [comment]
> My suggestion: Add 'clean' tag to clothing that creates positive morale. Make tag go away over time/boomered/etc. Move negative morale penalty to negative trait.

This is a good suggestion.

**Comment by pisskop** [comment]
My 2c as a habitually naked survivor in winter doing midnight city starts:

  -the penalty is a smidge too high
  -its consistent, and amount of wearing them will reduce the penalty.  why not reduce it as you wear this?  kill count is a mediocre but easy threshold
  -filthy is a state of being and not caused by external forces.  myclean jacket isnt getting filthy as i use a hammer to crack skulls
  -penalty goes away as soon as the filthy clothing does.
  -player cant get filthy either
  -past early game its less threatening


I dont think we should dump it though.  a blacklist mod sounds bettef

**Comment by Night-Pryanik** [comment]
If #17591 will be merged, then we basically get back to the time prior to introduction of entire filthiness system. 
The player will wear filthy clothing with absolutely no complaints about all the filth, and if he manages to avoid melee contact with enemy, he will be fine, just as he isn't wearing filthy clothing at all.

**Comment by flitvious** [comment]
>  if he manages to avoid melee contact with enemy, he will be fine, just as he isn't wearing filthy clothing at all.

When out of melee combat, clothing doesn't matter much. It doesn't give any bonuses to crafting, nutrition, resting, morale. If not for hungry zombies, a blanket and two makeshift slings would suffice for an early survivor. With this PR, the penalty goes where it matters (from the game mechanics perspective, at least).

Now that I think about it, there are two major dangers to a survivor: physical harm (damage, infections) and lack of nutrition (hunger, thirst, vitamins). Morale is not in the list. It just hinders crafting and is easily fixed. All the things that affect morale, consequently, seem not as important as food and protection. Imagine if there was another major source of danger tied to morale and things affecting it. Losing sanity and going mad. It works just like health: not instant, but creeping up. This danger semi-permanently damages your character for doing psychopathic things long enough (eating ants, wearing filthy clothes, butchering zombie kids). In the context of this danger, morale drop from filthy clothing would become important.

**Comment by Labtop-215** [comment]
By eating ants, do you mean eating giant ants?  Why is that on the list of things that could make you go insane?  I'd just see them as animals after the initial shock of seeing giant insects.  If you have a fear of insects or something that makes sense, but it doesn't otherwise.  If anything, eating dead people and rotten food should be far more damaging to ones psyche, since cannibalism can induce Kuru, and rotten food is disgusting if you aren't a saprovore (and it's probably still a little gross even if you are since you weren't a saprovore originally).

**Comment by Izicata** [comment]
Pretty sure he means eating ant eggs, which give like -20 morale or something because they're really disgusting.

**Comment by Labtop-215** [comment]
Ahh, I see.  Meh...  I think there should be a distinction between stuff you have to do to survive and stuff you do to make your life easier, but isn't necessary and is really messed up.

Doing what you need to do to survive shouldn't put you at risk of going insane.  Eating stuff that is rotten or gross, wearing gross clothing, dropping (but not smashing or butchering) zombie children, and seeing disturbing things like dead bodies, otherworldly horror's and the like should hurt your psyche, but on their own, or even together, shouldn't **break** you.

But other things like smashing/butchering zombies or people (I think of them as one in the same mostly), seeing zombies rise to their feet after they where downed, eating people, using human or tainted bones/fat to craft things, seeing or hearing violent explosions that you didn't trigger deliberately, murdering friendly or neutral NPC's (when murder isn't so janky), and the like probably should have the potential to push you over the edge.

**Comment by kevingranade** [comment]
It sounds like the real issue is that the morale system was broken at some
point.  It used to be the case that you needed to manage morale, or risk
not advancing any skills.  The comments on this issue seem to indicate that
this is no longer perceived to be the case, and that the only drawback of
low morale is interference with crafting.

**Comment by Coolthulhu** [comment]
The biggest problems are
> Tedium: the morale penalty will stay with you during crafting, unless you manually remove (and then put back on) the filthy clothing
> Harmless when the tedium is actually accepted: during combat morale doesn't mean much, so inventory management is enough to get rid of all the important consequences of filthiness

Those aren't anywhere near solved.

**Comment by pisskop** [comment]
> It used to be the case that you needed to manage morale

I have to manage it early game, but I take traits that specifically make it important, such as slow learner and alcoholism.  The penalties for low morale are fairly nonexistant, just less xp and a red 8( in the hud.

Filthy clothes and wetness penalties and things of this nature are instantly removed.  I dont know about anyone else, but even after a shower and warm dry clothes Im still somewhat sour about getting soaked to the bone.

**Comment by Vidiveni** [comment]
> It used to be the case that you needed to manage morale

I feel focus changes too slowly to be worth paying attention to. Might be nicer to have the focus correlate  faster with current morale level. This would make temporary boosts and penalties to morale matter more, such as from eating something good or killing a child.

**Comment by Labtop-215** [comment]
I don't understand the wetness penalty for the most part.  Being soaked by the rain is only an issue because it makes you colder, but otherwise it isn't a problem.  Unless it's acid rain or something...

I know the wetness penalty comes from other places too, like sewage water and lake water, but those are different from rain, they're essentially sludge or mud respectively.

**Comment by i2amroy** [comment]
>Being soaked by the rain is only an issue because it makes you colder, but otherwise it isn't a problem.

Have you ever been running around outside doing things while you've been soaked before? As a person who recently did a *lot* of hiking in the rain, I can assure you that once wetness actually succeeds in penetrating down to your lowest layer things can get pretty miserable pretty quickly. :P

Which is not necessarily to say that it's perfectly balanced either though, a lot of which is just the fact that right now the morale system is a really crude one (honestly I've always seen it as *crude* rather than outright *broken*). It's just never really been given that true realism/gameplay overhaul that most other game systems have been over the years, and the system that we are using today is virtually identical to the system that we were using back when morale was first added, just with a small handful of touch-ups and extensions.

Really the two key points that need to be addressed if we really wanted to improve it are (in my opinion):
1) Doesn't really mean too much in the big picture right now. With the exception of extremely high/low morale or when you are actively trying to learn something it really doesn't do much; either branching out/diversifying a few of it's effects or fixing the skill learning system could address that.
2) Really needs to differentiate between short-term and long-term morale, possibly with different effects. Getting a new tool, for example, might have some fairly large effects on my long-term morale, because every time I use it for quite a while I'll remember how much more awesome it is to have it than not. On the other hand eating a chocolate bar is mainly a short term boost. I feel awesome for the next five minutes or so, and I gain a tiny boost in my overall long term morale (which can add up if I can consume it on a regular basis), but it's mainly a short term boost.

This digresses from the original point of the filthiness issue though, where I support Rivet/Kevin on the matter, I like the idea, just needs some balancing/etc to get working well.

**Comment by DangerNoodle** [comment]
Is there no practical use for filth? DF does a thing like that, for infected injuries. It's just stupid if it only affects morale.

**Comment by ross-t** [comment]
>Another issue with the filthiness morale penalty is that it's a disconnect between what the player feels and what the character feels.

I think this is a really good point. If people want to keep filthiness in something like its current form, what about at least referring to filthy clothing as "gory" or "gore-spattered"? To me, "filthy" clothing is something stained or something that hasn't been washed for too long, which isn't nearly enough to make me upset about having to wear it in an apocalyptic scenario. I'd totally understand my character being upset about wearing `|\ leather jacket` if it were infused with zombie flesh, guts, and various vile rot-juices, though.

I'm also a fan of various other ways to reduce filth tedium, including but not limited to:

- removing the morale penalty for filthy clothing (perhaps not for characters with the squeamish trait)
- reducing or removing the morale penalty for filthy clothing that's not worn close to the body if you're wearing something underneath it (though it might be difficult for players to realize that this mechanic exists)
- replacing the morale penalty with an increased chance of infection if a damaging attack is made to a body part covered by a filthy item, accompanied with a message like `Bits of viscera from your || straw hat (gory) contaminate the wound!` if it procs so that the player can discover that mechanic
- allowing the player to wash filthy clothing with just soap if it's raining
- making it so items worn by zombies have a chance of being filthy instead of always being filthy
- making it so some items can be crafted with much lower morale than the current cutoff—a character who's wearing some filthy pants and who's been recently rained on might not be up to crafting a fancy gun, but could reasonably be expected to continue making bandages/funnels/arrows for their bow until they were _really_ feeling down
