### ISSUE TITLE
Z's appearing very close to player with "Wander spawns" on

### ISSUE THREAD

**Issue by romkuma** [CleverRaven/Cataclysm-DDA#17251]
Sorry, not sure how to replicate this one, but here is the situation:
- Was near a hospital (just outside one of the walls), no Z's in sight but a number of wandering spawns (Z's on map).
- Took a few steps away from the hospital
- suddenly there were ~4 regular Zs and a boomer near the hospital wall.
- Took a few more steps (diagonally towards the hospital, trying to get around the corner to escape Z's)
- Another boomer and ~2 regular Zs appeared within 4-5 spaces of the PC

I assume they are only supposed to appear at the limit of sight, but the proximity to the hospital wall confused something?

**Comment by Vidiveni** [comment]
Probably unrelated, but there has been some weird disappearances and reappearances the last few weeks that made me wonder if I was imagining things or not. Especially NPCs tend to suddenly disappear in plain sight, even from the map, to either be gone forever or suddenly reappear later at the same spot. 

Probably seen it happen to other things as well including zombies, but memory is fuzzy and got no solid evidence. This was without any active speed penalties, which could otherwise explain zeds suddenly appearing.

**Comment by keyspace** [comment]
I've been playing with wandering spawns for about a month, and never seen this happen.

A savegame would be nice. Otherwise suggest **Confirmation Needed** tag or closing. :/

-----

Took a cursory glance through `map::spawn_monsters(bool ignore_sight)`. The three places it's called with `true` during game are:

* ` editmap::mapgen_preview()` - debug editing
* `game::place_player_overmap()` - debug teleport
* `game::vertical_shift()` - scaling stairs

None seem relevant.

-----

An unlikely explanation - player could be on the edge of overmap, and walking off onto another one and back.

**Comment by Leland** [comment]
No confirmation, closing. If OP or anyone else experiences this again, feel free to ping me here to reopen or just make a new issue.
