### ISSUE TITLE
Water purification tabs not working

### ISSUE THREAD

**Issue by MrWoot** [CleverRaven/Cataclysm-DDA#17308]
Running version 5104; for past several days water purification tablets haven't been working.  To test, fill up a bottle with water, and with multiple tabs in inventory, attempt to Activate the tabs from inventory.  "You don't have enough charges in your purifier to purify all the water" is the resulting error message.  Attached is a savegame illustrating this.

[Spiritwood 2016-06-20.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/328933/Spiritwood.2016-06-20.zip)

**Comment by bumpkindda** [comment]
Can confirm.

**Comment by mugling** [comment]
Likely regression from #17013.

The problem is the usage actions can apply to both `COMESTIBLE` and `TOOL` but the former doesn't use the `ammo_*` accessors which the purify action now requires.

We don't want to go back to directly manipulating `charges` as that would break tool magazines and tool mods. Neither do we want `COMESTIBLE` pretending to be ammo. Finally we don't want to restrict use functions to one or the other (resulting in duplicate code).

Probably we need an `item::deplete_unit` function or similar?

**Comment by Coolthulhu** [comment]
> Neither do we want COMESTIBLE pretending to be ammo.

For purposes of ammo remaining and similar checks, it wouldn't be a bad idea. Comestibles are effectively tools that are their own ammo.

**Comment by mugling** [comment]
They should support the entire range of `ammo_*` functions or none at all. The advantage of a function working on a superset is we can avoid such a requirement.

Also I'm not sure if coupling `TOOL` and `COMESTIBLE` together might be a bad design as they may become more divergent over time?

**Comment by Coolthulhu** [comment]
> Also I'm not sure if coupling TOOL and COMESTIBLE together might be a bad design as they may become more divergent over time?

Water tablets are an edge case. They're similar to meds and tools.
Forcing them to become tools could be easier than keeping them as meds, because they're one of the very few variable use cost meds.

Still, having the ability to consume multiple food/med charges per turn might be convenient. For example, swallowing a whole handful of aspirin/chips/caffeine pills.
