### ISSUE TITLE
Separate build directory and executable for release and debug builds

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#17339]
Currently it isn't possible to cleanly build debug over release and vice versa. Changing release to debug and back requires a `make clean` in between. Or moving the `obj`/`objwin` directory manually plus stashing the executable.

This makes it more tedious than it needs to be. It is probably relatively easy to fix for those who know how into makefile.

**Comment by kevingranade** [comment]
yea, based on RELEASE flag not being set we could switch obj to obj-debug (I'd rather keep release in obj to avoid perturbing jenkins builds) and cataclysm to cataclysm-debug, and cataclysm-tiles to cataclysm-tiles-debug, then they could all coexist in the dame main directory.

While we're at it, do we want a obj-tiles directory.... hrm

Do we want to build the obj dir and executable names by concatenating the flags that have been set?  At some point that actually becomes a problem because the number of directories and executables starts getting out of control...

New idea, just update ODIR (and friends) and TARGET (and friends) to be overridable, so you can do..

make TILES=1 BUILD_SUFFIX="debug-"
(builds in debug-obj, produces exe names debug-cataclysm-tiles)

make TILES=1
(still builds in obj and produces exe named cataclysm-tiles)

make BUILD_SUFFIX="tacoparty-"
(You get the idea)

**Comment by Coolthulhu** [comment]
> Do we want to build the obj dir and executable names by concatenating the flags that have been set?

How about having it default to some long flag-based name, but allow overriding? That is, if `BUILD_SUFFIX` is unset, it gets all the necessary details to avoid collisions.

**Comment by kevingranade** [comment]
The huge-number-of-directories problem is going to be mostly invisible to people, and have a bizarre failure mode of filling up people's hard drives (a single obj directory is at least 0.5GB, a single exe is at least 0.25GB, if we factor in every flag that could be dozens of directories and executables).
I could see adding that as its own flag, but I'm not happy about making that the default behavior.  People probably don't even realize how big the .o files and executables are, much less anticipate that there could be dozens of them by default.

**Comment by kevingranade** [comment]
Flubbed the autoclose label, addressed by #17394
