### ISSUE TITLE
Conversion kits cannot be used on shotguns

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [CleverRaven/Cataclysm-DDA#17359]
The descriptive text for the .223 caliber conversion kit and the .308 caliber conversion kit says they can be used to convert a shotgun into a 223 or 308 rifle, but they lack a shotgun entry in their mod_targets field.

**Comment by mugling** [comment]
The question is should they be allowed at all. My understanding is those weapons lack rifling which would be a major obstacle to this. Perhaps an opinion form @Rivet-the-Zombie?

**Comment by Kadian** [comment]
Conversion Kits often contain a Barrel for the new Ammo. This is especially necessary when the calibers have different sizes, like the .223 (aka 5.56x45mm NATO) and the .308 (aka 7.62x51mm NATO) ; A Barrel for a .223 wouldn't be able to properly use a .308 bullet and vice versa.
That also means that rifling isn't an issue because you would need to put a different barrel on it anyways.

**Comment by Rivet-the-Zombie** [comment]
Most shotguns do indeed lack rifling, but some are made specifically for firing slugs, and those are rifled.

Either way, a shotgun barrel (rifled or not) isn't going to work for a rifle caliber - but that's where this part comes into play:

>Conversion Kits often contain a Barrel for the new Ammo.

So yeah, it could work.
