### ISSUE TITLE
Inventory columns are confusing

### ISSUE THREAD

**Issue by mugling** [CleverRaven/Cataclysm-DDA#17427]
Something we'll all probably get used to over time but `RIGHT` arrow should certainly not be equivalent to `ENTER`. The latter is counterintuitive and frequently results in selection of the wrong item.

Additionally the spacing between columns is too narrow with most of the text compressed to the left of the display

**Comment by codemime** [comment]
Could you expand on that? From my POV the right arrow behaves just as usual (I mean nothing's changed). The spacing could be adjusted fairly easy. BTW I tried to arrange columns evenly on the screen, but it looked rather weird on high resolutions.

**Comment by Vidiveni** [comment]
When I first pressed `right` arrow I expected to move selection to the equipped items to the right. Instead the item in the right column I intended to select got a red selection that made me think "oh...okay I guess it's selected now". I pressed enter but it did not open the expected menu. Took me months to realise you have to press` left` arrow instead of `right` arrow. And I still don't know what the red selection does.

**Comment by mugling** [comment]
> From my POV the right arrow behaves just as usual (I mean nothing's changed)

Before those changes it was exceptionally rare (almost never) to press `RIGHT`. Now it's fairly common. The problem is instead of moving to the right column (which is intuitive) it instead activates your grenade which leads to YASD.

It's a significant regression and a blemish on what is otherwise a good design.

**Comment by mugling** [comment]
@codemime how difficult would it be to fix the `RIGHT` action issue - it continues to be reported outside of GH?

**Comment by codemime** [comment]
It's fairly easy and I can do that, but I need a robust usage scenario. What's the expected behavior?
I had tried [this](https://github.com/CleverRaven/Cataclysm-DDA/pull/17765/commits/30ac79f93200823fcf953835068b09bf60084b66), but the change was [criticized](https://github.com/CleverRaven/Cataclysm-DDA/pull/17765#issuecomment-235049235):

>  Coolthulhu commented on 25 Jul

> Seemingly tiny change, but actually quite major:
> In wield menu, "Right" changes tab instead of selecting the current item. This is a discrepancy with drop > menu, where "right" selects.

**Comment by mugling** [comment]
`RIGHT` selecting an item (activating a grenade, eating something nasty) is definitely more surprising than switching column considering `LEFT` behaves as anticipated.

Everything else should be balanced around `LEFT` and `RIGHT` being commutative

**Comment by codemime** [comment]
Which key do we choose for selecting then (keeping in mind that pick-up menu uses arrows)?

**Comment by mugling** [comment]
Space?

**Comment by codemime** [comment]
> Space?

Dubious. It's neither very convenient nor consistent. I wonder what does @Coolthulhu think on this matter?

**Comment by mugling** [comment]
Yes, wait for an answer before implementing anything

**Comment by codemime** [comment]
Pinging @Coolthulhu. What do you think about the keys for the inventory menu?

**Comment by mugling** [comment]
Fixed by 0dc49566 factored out of #18514

**Comment by Coolthulhu** [comment]
Sorry, I missed the ping.

We should be going for consistency. Whether right works as left/enter/whatever should depend on how is it working in other menus.
It should all be changed in one PR. Weird behavior is better than inconsistent behavior.

I didn't look at the current UI, but if right now behaves sometimes like enter and sometimes like left, that's a regression and not a bugfix.

**Comment by mugling** [comment]
The only exception now is multidrop where `RIGHT` selects as opposed to changes column.

We can't really have `RIGHT` selecting an item in the other inventory prompts as this results in accidentally activating grenades instead of changing column and all other manner of YASD.

We could do with `SPACE` for selection/action and `ENTER` for confirmation/close throughout the UI?

**Comment by Zireael07** [comment]
> We could do with SPACE for selection/action and ENTER for confirmation/close throughout the UI?

+1.

> We can't really have RIGHT selecting an item in the other inventory prompts
Quoted for truth.

Whatever is the ultimate solution doesn't matter as long as multidrop behaves like the rest of UI.

**Comment by mugling** [comment]
I agree consistency is essential but effectively ending a players game because they pressed `LEFT` then `RIGHT` to try to change back to the original column is too high a price.

**Comment by Zireael07** [comment]
Nowhere did I say that RIGHT selecting an item is a good idea. (fixed bad quote)

**Comment by Coolthulhu** [comment]
Ending one character's life is nothing compared to having to figure out each menu separately.
YASD because of weird-but-consistent behavior is kinda bad, inconsistent menus where same buttons do different functions is horrible.

You can learn to work with weird menus. Weird isn't that much of a bad design.

**Comment by mugling** [comment]
Whilst that's true in the general case `LEFT` should always be commutative to `RIGHT`. It's such a strong association it's almost impossible to train yourself out of expecting that.
