### ISSUE TITLE
Zombie grab attack status makes no sense.

### ISSUE THREAD

**Issue by Soyweiser** [CleverRaven/Cataclysm-DDA#17439]
The zombie grab attack is pretty annoying. Say this happens: "ZZ@" First zombie grabs you. Second Z moves up. You kill first Z. Grabbed status remains active. The status is freely moved unto the second zombie. Once by one zombie, if there is a large trailing amount of Z's just outside of combat, you can never ever get away again, due to this strange transfer of grab attacks.

Not only does this annoying effect happen. The grab status remains on your character screen even if there is no zombie next to you http://prntscr.com/bna8wc. (I think it is only removed after you take an action (so im assuming it only gets checked for validity after you take an action. Should be moved to before you take an action then)).

This makes combat against zombies early game a lot more annoying (and deadly) than it should be.

(I have also noticed that the grab status can be dropped strangely when you don't expect it. Currently it just behaves very wonky. I have no idea when the speed penalty (and other possible penalties of being grabbed) are dropped).

**Comment by Coolthulhu** [comment]
The grab status is a giant hack. To implement it properly, we'd need persistent creature IDs. And persistent creature IDs aren't easy.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.

**Comment by Soyweiser** [comment]
Still in the current game this bug.

Was grabbed by a zombie, killed zombie. Grab status didn't go away until I moved. (There was also a zombie dog next to me).

**Comment by kevingranade** [comment]
Taking a look at this, I'm adding an effect to the grabbing monster so that if the monster is moved or killed the grab is released.

**Comment by Zireael07** [comment]
@kevingranade: I believe the "remove grab on kill or move" thing has already been done, might have been mugling or Coolthulhu who did it?

**Comment by kevingranade** [comment]
It does not remove on death, I've been testing it.  Also I've been all through that code.  AFAIK the existing grab removal code just removes grabs when the player takes a turn and there are no eligible grabbers nearby, exactly as outlined by Soyweiser.  Its also still subject to the effect where monsters can "hand off" their grab after death.

On the plus side, I have this working when monsters die, now I just need to clean up my code, add it to move code as well, and do some more testing.

**Comment by Night-Pryanik** [comment]
@kevingranade any update on your progress?
