### ISSUE TITLE
Suggestion: Medicine Bag 

### ISSUE THREAD

**Issue by natsirt721** [CleverRaven/Cataclysm-DDA#17474]
Carrying around multiple medicines is a pain in the behind when even 1 pill takes up a full volume point.  The medicine bag will have a finite volume but be able to carry a fixed amount of meds (50?) of any variety.  Being able to have a large variety of medicines on hand for a small inventory investment (1-4) is a nice feature IMHO. Maybe have a number of pouches to ensure medicines dont mix.

**Comment by illi-kun** [comment]
I guess it's better to postpone that till general Nested Containers system will be implemented.

**Comment by illi-kun** [comment]
I'm thinking about closing this. Any other points of view, anyone?

**Comment by natsirt721** [comment]
Go for it.  Im sure it will get raised again when nested containers exist.

**Comment by mugling** [comment]
Close is reasonable. We need to control the number of issues so that it actually represents a reasonable queue of intended tasks.

**Comment by kevingranade** [comment]
The other large change that would obsolete this concept is rescaling volume
tracking, meaning each pill would be the minimum 1ml.

**Comment by Coolthulhu** [comment]
> meaning each pill would be the minimum 1ml

That would actually be really bad for both gameplay and realism. A backpack full of all sorts of crap is not a good place to store single pills.

**Comment by kevingranade** [comment]
>> A backpack full of all sorts of crap is not a
>> good place to store single pills.

Agreed, but the answer is to make that unfavorable for the same reasons it
is irl, like a "rummage" move penalty, or even risk of loss or breakage of
tiny objects in inappropriate containers, not a nonsensical rule that all
objects are a minimum of 250ml or so in volume.

**Comment by Coolthulhu** [comment]
> risk of loss or breakage of tiny objects in inappropriate containers

That would be far more annoying than arbitrary limitations. Unless it was relatively deterministic, like "when stored improperly, 1 pill is lost for each used pill" or something (arbitrary and unrealistic) like that.

We don't allow using steel bullets in handloaded cartridges because even though it works, it is not the proper use of the gun and damages it. We don't allow holding extra objects in teeth, elbows and armpits, even though it could be useful, because IRL it isn't much of a thing.
Sometimes just straight forbidding a thing does a much better job at making it realistic than allowing it and having it result in non-realistic usage.
> "rummage" move penalty

Depending on how high would that penalty be, it would either make it impossible to activate painkillers in a dangerous situation without having them stacked or it would do nothing to solve that stupid "store a handful of loose pills at the bottom of a backpack" thing.

In the end the effect would make less sense than what we have now. Unless per-container storage and retrieval costs were implemented, but that's a whole new can of worms.

> nonsensical rule that all objects are a minimum of 250ml or so in volume

Despite its seeming lack of realism (250 ml is arbitrary), it does a far better job at "enforcing realism" than any of the suggestions I've heard:
* It does not allow exploity behavior that wouldn't happen in real life, like storing few loose pills in a backpack/pocket
* It isn't tedious, unlike explicit, non-automatic container management or - far worse - random penalties for improper storage
* It doesn't depend on complex features that may or may not ever be implemented
* It limits the "feasible size" of optimally managed inventory, limiting tedium. Inventory tetris may seem like it isn't a big deal, but it does add up.
