### ISSUE TITLE
Build failures for Windows on Jenkins

### ISSUE THREAD

**Issue by DLaboratory** [CleverRaven/Cataclysm-DDA#17496]
Since build 5178.

```
In file included from src/player.h:5:0,
                 from src/player.cpp:1:
src/copyable_unique_ptr.h:11:9: error: unused parameter 'rhs' [-Werror=unused-parameter]
         copyable_unique_ptr( copyable_unique_ptr &&rhs ) = default;
         ^
In file included from src/player.cpp:1:0:
src/player.h: In constructor 'player::player(player&&)':
src/player.h:139:7: note: synthesized method 'copyable_unique_ptr<T>::copyable_unique_ptr(copyable_unique_ptr<T>&&) [with T = craft_command]' first required here 
 class player : public Character, public JsonSerializer, public JsonDeserializer
       ^
src/player.cpp: At global scope:
src/player.cpp:294:29: note: synthesized method 'player::player(player&&)' first required here 
 player::player(player &&) = default;
                             ^
```

**Comment by mugling** [comment]
Likely fallout from #17434

**Comment by kevingranade** [comment]
What exactly is the point of a "copyable_unique_ptr"?  AFAICT it provides functionality explicitly rejected by the C++ standards committee by the removal of auto_ptr because it was a very error prone way of managing memory.
If you need a unique_ptr in a class that needs to by copyable, you need to resolve that in your copy constructor (yes that means you can't have an implicit copy constructor any more).

**Comment by BevapDin** [comment]
> (yes that means you can't have an implicit copy constructor any more)

And that's where the trouble starts. Who wants to write a copy constructor of `player`? And who wants to keep it up to date? I remember at least one bug that was caused by not copying a member in the (formerly explicit) copy constructor.

Maybe `copyable_unique_ptr` is unfortunately named. It is supposed to be a Pimpl wrapper that provides value semantic (copy the referred object, not just the pointer). It's basically used to avoiding including the header for the wrapped type.

**Comment by kevingranade** [comment]
Does anyone have an environment that can reproduce this?  I built on linux
with gcc and windiws with mingw, no dice. I hate stabs in the dark, but
here they are:
The move constructor isn't templated, is that normal?
Try making the move constructor explicit.

**Comment by DLaboratory** [comment]
Now Windows curses passes the build but tiles is still failing.

**Comment by DLaboratory** [comment]
Sad, `ERR_CONNECTION_RESET` to [ci.narc.ro](ci.narc.ro).
