### ISSUE TITLE
Tool subtype system interface deficiency

### ISSUE THREAD

**Issue by mugling** [CleverRaven/Cataclysm-DDA#17517]
Lamp oil cooker is a subtype of hotplate. If you have both in your inventory it's impossible to select which one is used for crafting. Worse in one is on the floor and one in the inventory you get offered `hotplate` and `hotplate (nearby)`

**Comment by mugling** [comment]
Worse it prefers the inferior forms depleting `wooden needle` before `tailors kit`

**Comment by Labtop-215** [comment]
Is there an actual difference between a wooden needle and a tailors kit in terms of success when tailoring?

**Comment by Coolthulhu** [comment]
Nope. Tools can't currently grant any difference in crafting success rate, speed or output quality.

**Comment by Labtop-215** [comment]
Yea, as long as there is no success rate or quality difference between items, then it's better to use the inferior version first, since it otherwise leads to frustration and micromanagement.  Most people want to save the best or least renewable item for last, and instead use the cheaper item for crafting.

The player should still be given an option between using a lamp oil cooker or a hotplate when crafting items that need hotplate charges, in case you end up in a situation where lamp oil is less available than batteries.

**Comment by mugling** [comment]
I'm not sure if the order isn't likely be pseudorandom - eg. walk one tile left and now something else is preferred

**Comment by mugling** [comment]
#17536 changed in scope slightly to setup a possible fix but this issue remains otherwise open

**Comment by mugling** [comment]
Fixed in `master` by the subtype unwrapping PR (#19052)
