### ISSUE TITLE
Pickup time shouldn't scale with volume

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#17511]
Picking up a plank shouldn't take more time than picking up a needle. Especially considering that larger items can be set to lean on a wall or otherwise be more easily accessible.
Picking up an empty metal tank shouldn't take few minutes.

Weight (above certain threshold) makes much more sense here.

**Comment by mugling** [comment]
Yes the balance is out somewhat

**Comment by Labtop-215** [comment]
It would be nice if it where better explained why it takes 480 moves (24+ seconds) to wield my makeshift machete from my inventory, instead of just being stun-locked mid combat while I go fetch it from my inventory, but other than that I'm not bothered.

Maybe make it a little more obvious that storing weapons in scabbards will actually save time rather than just looking like an impractical alternative to having inventory would be a good idea.

Most wearable items just seem to be impractical alternatives to having extra inventory, so I figured I would point this out.

**Comment by mugling** [comment]
> Maybe make it a little more obvious that storing weapons in scabbards will actually save time rather than just looking like an impractical alternative to having inventory would be a good idea.

It's very obvious from the wield menu. It gives you the raw number of moves of the various options

> Most wearable items just seem to be impractical alternatives to having extra inventory,

They don't take up space and are (typically) quicker to access

> Maybe pickup time should scale more with inventory volume state (how full is your inventory), and torso, arm, and hand encumbrance instead.

The latter is already true and the former I'd very much like to implement.

> Taking a long time to wield something would make sense if you had to take off your backpack, and shuffle though it to find what you need, but very little to no sense if you just had to take that same weapon out of your leg pouches, for instance.

Already implemented. Reloading from ammo pouches also displays moves. It should (and is) quick to pull out a holstered gun, backup knife or spare magazine whereas fetching that 2x4 out of your backpack is going to take much longer. What you carry about your person is now much more of a tactical consideration.

The underlying mechanic is solid but the actual issue is very massive items are heavily penalised. I'm probably going to wait until we have either of dragging large items and/or proper containers for reimplementation. A stop gap is further capping `MAX_ITEM_HANDLING_COST` and I may do some testing of that later.

**Comment by Labtop-215** [comment]
Except by backpack, you mean inventory right?

I get the same problem with removing things from my drop leg pouches as I do from my backpack, since it comes out of inventory.

**Comment by mugling** [comment]
> Except by backpack, you mean inventory right?

Sorry, yes I mean inventory

**Comment by Labtop-215** [comment]
I suppose the issue I'm bringing up might be solvable if or when we get separate inventory containers.

**Comment by Coolthulhu** [comment]
> The underlying mechanic is solid but the actual issue is very massive items are heavily penalised.

And tiny items not penalized enough. And medium items penalized too much. Basically, everything that isn't "just small" (1-3 volume) is off.

Tiny items can be assumed to be stashed in the pants' pockets. Here it should cost 30-50 to retrieve. More than current 1.
Small items should cost the same as tiny items. Pulling out a cell phone or a kitchen knife isn't harder than finding a pocket knife within the pocket.
Medium items most likely stick out of the bag/backpack, meaning they'd be easy to retrieve.
Huge items can take a while (if they're in the inventory, they're probably crammed there), but they shouldn't take that time when picked off the ground.

That's for realism.

For gameplay:
* Small items already have good attack times (knives, pistols), good properties (dust masks), good storage wearables (holster, especially the overpowered quick draw one). No need to have them also take 0 time to retrieve
* Medium items are the best melee weapons around and best early ranged weapons (shotguns). I guess the retrieval time can be a bit high here
* Huge items aren't weapons. They should be deep into max manipulation time cap, especially considering retrieval isn't a long action and thus paralyzes the player
* The grabbed/handcuffs penalty should be way flatter - it doesn't affect knives and magazines much, only large melee weapons (like planks taken from the ground to bash a shocker)
