### ISSUE TITLE
Split Underbarrel into Underbarrel and Bayonet mod locations

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [CleverRaven/Cataclysm-DDA#17568]

**Comment by mugling** [comment]
Questionable. Could result in a lot of corner cases as not all possible combinations would be plausible. Additionally I quite like the fact that its bayonet **or** auxiliary gunmod. Allowing both upsets balance markedly. Status quo has no such corner cases nor balance concerns.

**Comment by Rivet-the-Zombie** [comment]
Those are all very good points, @mugling!

**Comment by BorkBorkGoesTheCode** [comment]
Several guns cam mount a Bayonet irl. Adding a Bayonet mount would also fix the rifled musket integral bayonet hack.

**Comment by mugling** [comment]
> Several guns cam mount a Bayonet and grenade launcher irl

But certainly not all...

> Adding a Bayonet mount would also fix the rifled musket integral bayonet hack.

...but also introduce wider problems that are probably more difficult to fix

**Comment by Izicata** [comment]
I'm against this because it removes the opportunity cost for using a bayonet. Having to choose between increased melee capability, a powerful secondary weapon, or decreased dispersion and recoil is an interesting problem that doesn't always have an optimal solution. Choosing between increased melee capability or slightly lower dispersion is a much easier choice and much more easily optimized problem; bayonet on close/medium range guns, no bayonet on long-range guns.

Being able to use an underbarrel grip as well as a bayonet would be especially troubling, considering the underbarrel grip lowers dispersion by far more than the bayonet increases it.

**Comment by Breligar** [comment]
This seems like one of those "Realism vs. Gameplay" concepts, and I have to side with gameplay on this one.

As a simple player, I prefer having to make a choice with weaponry/gear; for example, do I want lots of carrying capacity on my general-purpose gear, or would I rather be less encumbered for safer combat? Once you start to encounter items that seem to "do it all", it becomes an issue of feeling like you have to use it or you're hurting yourself, which leads towards less fun instead of more. You don't feel rewarded for making a smart choice because there's only one smart choice to make.
