### ISSUE TITLE
brass catcher doesn't work with Kel-Tec KSG's second magazine

### ISSUE THREAD

**Issue by jarmush** [CleverRaven/Cataclysm-DDA#17588]
it catches brasses only if regular magazine used, but it doesn't if switched to integrated second magazine

**Comment by jarmush** [comment]
Yep, i know, it's underbarrel shotgun in fact, but Kel-Tec KSG description says that it's a second magazine.

**Comment by mugling** [comment]
Marked long term as the correct fix is allowing multiple magazines. We could hack around this via a flag but I'm not sure given the minor nature if this is warranted?

**Comment by Breligar** [comment]
Could possibly just make the ammo capacity 14+1 for now? That's basically what the two tubes accomplish, and would still promote the weapon as being a good choice in-game since it would hold a good amount of ammo at once for a shotgun.

**Comment by mugling** [comment]
You couldn't load differing ammo types though.

The +1 idea has been floated before and rejected as unnecessarily increasing the complexity of the implementation.

**Comment by chaosvolt** [comment]
I made it use a gun mod for the second magazine specifically to allow for loading one ammo type in one tube, and another in the second tube. It was very hacky, but I'm proud of the fact it ONLY uncovered a shitload of stupid bugs specific to integrated subweapons, instead of turning the game into a black hole or something. :V

Seriously, that fucking thing had caused me almost as many problems as back when I first added pine lean-tos to More Survival Tools, back in the 0.B days before i was even a contributor.

**Comment by l29ah** [comment]
How to switch it to the second magazine? o_O

**Comment by chaosvolt** [comment]
F, same as with toggling to bayonets or other fire modes. -_-

And holy shit, this bug is still around? That thing has been a pain in the ass code-wise ever since I added it.

**Comment by l29ah** [comment]
Yes, it still doesn't catch shells.

**Comment by wapcaplet** [comment]
Tested in 0.E-6177-g 9f4a1b841d with the Kel-Tec KSG. Attached brass catcher, reloaded and fired 7 shots, then unloaded the brass catcher and got all 7 shells back:

![image](https://user-images.githubusercontent.com/238395/94313342-ca469c80-ff3b-11ea-8fa8-8b45466226f1.png)

Likely was fixed by recent PR #42455 . Closing issue.
