### ISSUE TITLE
Toolbox doesn't have all its components' qualities

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#17599]
At the very least it lacks the WRENCH 2.

**Comment by nikheizen** [comment]
Speaking of toolboxes, it's a little strange that a survivor who lasted long enough to get 4 fabrications, 3 mechanics, and all the requisite components would somehow manage to destroy a wrench while assembling a toolbox. Perhaps since it no longer includes basic repair kits, the difficulty should be adjusted?

**Comment by nikheizen** [comment]
Just tested on latest master and this issue seems to be incorrect.Toolbox has 2/1 bolt turning as well as all its other component abilities.

**Comment by mugling** [comment]
`data/json/tools.json:6999` specifies `WRENCH 2` for `toolbox`

**Comment by Coolthulhu** [comment]
I must have checked the toolset then.
