### ISSUE TITLE
Driving, turning with high skill results in 'free turns'

### ISSUE THREAD

**Issue by pisskop** [CleverRaven/Cataclysm-DDA#17601]
http://www.bay12forums.com/smf/index.php?topic=149157.msg7080881#msg7080881

**Comment by Coolthulhu** [comment]
What "free turns"? Does it allow gaining moves or what?

**Comment by Izicata** [comment]
>
It seems to be related to what Greiger said - with higher amounts of driving skill, turning has an increasing chance to happen instantly, and take no time. I don't know whether there's a limit on it, but at 10 driving skill you seem to get either 2 or 3 'turns of the wheel' before time starts up again.

>I get it now, I guess, but the whole thing still seems odd and unintuitive to me. I mean, I've driven - the old system of continually making small adjustments to the wheel to stay level (and this being less of a thing the more skilled you are) tallies up with all my real life experience of driving. 

Someone doesn't like how high driving skill makes turning faster and wants the old system back. I wasn't paying attention to the project when it happened, but I assume it was removed for being incredibly annoying?

**Comment by Coolthulhu** [comment]
I see three options:
* Splitting turning from turn order completely. That is, being able to set a direction, then having the character try to steer towards it automatically, similar to cruise control. This would allow all sorts of weird twists and turns to be added without it becoming annoying.
* Making it so that without cruise control, turning the vehicle ends the turn. Like in old system, but without random turns. This would mean that no cruise control mode would be objectively inferior to cruise control, though.
* Some sort of a time hack making steered vehicles act out of their turn, having continuous time, unlike all other vehicles in the game.

**Comment by TheWebfrog** [comment]
I'd choose the first option out of all of them

**Comment by Izicata** [comment]
Yeah, the first option is the only viable one. Driving even already sort of works like this, if you turn on the vehicle facing indicator.

**Comment by nanovad** [comment]
I could see having the "character" try to turn towards a certain direction being quite difficult when attempting to navigate a crowded street with a car or larger.

**Comment by TheWebfrog** [comment]
True, but I think reflects real life

**Comment by kevingranade** [comment]
The cruise control thing sounds good in theory, but what does the ui look
like? Do you move an indicator to an arbitrary spot on the screen, or pick
a cardinal-or-sub-cardinal direction with a keypress?  The first sounds
cumbersome to set, the second sounds lacking in expressiveness.  I'm hoping
we can come up with something in between.
