### ISSUE TITLE
Bionic choices from profession and traits.

### ISSUE THREAD

**Issue by DeadLeaves** [CleverRaven/Cataclysm-DDA#17641]
I've been playing a few martial characters and though it was really cool how you choose between styles at character creation. That got me thinking, it would be really cool with professions and traits that allow you to choose between a list of bionics from taking certain professions or traits. 

I have spent a few hours looking into implementing this myself. And while I've gained a little insight in how one would implement such a system. I found it above my level of competence and  familiarity of the code to implement such a feature myself. 

Seeing as the system would probably end up quite similar to the martial art system I looked around and here is what I found. It might be helpful to anyone who might take on such an endeavor.

_At line 607 of newcharacter.cpp_ the code for finding martial arts and the prompt to have the user select the ones they want are found. It can probably be copied and repurposed along with the _choose_ma_style_ function found at line 188 in the same file.

in the json styles are defined in the mutation.json as follows.

``` json
    {
        "type" : "mutation",
        "id" : "MARTIAL_ARTS",
        "name" : "Martial Arts Training",
        "points" : 2,
        "description" : "You have received some martial arts training at a local dojo.  You start with your choice of Karate, Judo, Aikido, Tai Chi, or Taekwondo.",
        "starting_trait" : true,
        "initial_ma_styles" : [ "style_karate", "style_judo", "style_aikido", "style_tai_chi", "style_taekwondo" ],
        "valid" : false
    }
```

So an implementation of a traits with bionics could be like the following: 

``` json
    {
        "type" : "mutation",
        "id" : "BIONIC_FAN",
        "name" : "Bionic Fanatic",
        "points" : 5,
        "description" : "Since you were a kid, you've looked up to super heroes and once your budget allowed it after working many long hours you decided to turn yourself into one.  You can choose between Fingertip Razors, Bionic Claws, Monomolecular Blade or Fusion Blaster Arm",
        "starting_trait" : true,
        "initial_bionic_choices" : [ "bio_razors", "bio_claws", "bio_blade", "bio_blaster"],
        "valid" : false
    }
```

Of course that is just an example and by no means balanced.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
