### ISSUE TITLE
AIM not allowing us to pour fluids onto floor :(

### ISSUE THREAD

**Issue by stk2008** [CleverRaven/Cataclysm-DDA#17652]
Win 10 x64 bit
CDDA build 5233 x64 bit

Ok sooooo basically I have a load of rotten juice in plastic bottles and I want to empty them all out so I can cut the bottles up for plastic chunks.

So I press /
select tile with all the bottles on and then hit c

In the other AIM window I select an empty tile

go back to window with contects of bottles and hit enter but its says I cant pick up lquids problem is I am not trying to pick them up I am trying to pour it out.

I know I can do "U" select bottle and direction I want to pour but when ya have like 40 of em its a bugger.

Thanks in advance you awesome lot :)

**Comment by ProfoundDarkness** [comment]
... I don't think you are allowed to manipulate liquids directly like that anyway, related to how you can't pick up liquids on the ground iirc.  How it normally works is you hit C on the container you want to move liquids TO and then select the container(s) on the other pane that you want liquids FROM.  I haven't seen direct manipulation of liquids yet (in Advanced Inventory Manager).  I don't know if the lack of direct liquid manipulation was considered a bug but I don't think it was.  Also using (C) on a stack of containers only opens one of the containers in that stack, not all of them.  I'm still new-ish to the game so maybe I've missed something cool for multiple containers?

While I would love a quick(er) way to empty LOTS of smaller containers like that I do value the protection of direct liquid manipulation.  What I've been doing is having the containers I want empty in inventory (no other food in inventory) and from AIM hitting (e)xamine, (U)nload, (g)round (k)-direction, repeat.  I don't know why I go with k at the end but any direction key will do (in a clear area).  The next container I want emptied should always hang out under the selection cursor in AIM assuming I selected the first one and there are more to be emptied.  Oh I tend to use AIM in category mode, that might matter.

Maybe in this context what would be handy is an additional butcher menu option for emptying containers or just allowing filled containers to be butchered (cut up)?  <shrug>  I say 'just' having not even glanced at that area of code yet so that may be a horrid idea.  Something I might do were I in a similar situation is to create an autohk/autoit script to spam that key combination to the game but it's short enough that I can usually just hit it a bunch OK.  I haven't actually had need to empty so many containers yet though.

**Comment by Oskar636** [comment]
This isn't a bug, but a suggestion for improvment.

**Comment by Leland** [comment]
This thread hasn't seen a real update in 9 months. Closing for now. If anyone is still interested, I can reopen... or feel free to just make a new issue!
