### ISSUE TITLE
Can't clean goo'd towel

### ISSUE THREAD

**Issue by codrus** [CleverRaven/Cataclysm-DDA#17678]
I got slimed by a zombie and used my towel to clean it off, which soiled it. But when I use my washboard (w/ 7 charges) to try and clean it at a swimming pool, it says I am missing an object. I don't think it sees the soiled towel (even not wearing it.)

**Comment by illi-kun** [comment]
I guess it should be cleaned by just water (I didn't check it but I think cleaning of used towel is not the same as cleaning of dirty clothing).

**Comment by Zireael07** [comment]
Gooey towel is handled completely differently to "filthy' clothing.

**Comment by sethsimon** [comment]
To clarify, one of the towel recipes in the crafting menu requires a soiled towel and water.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
