### ISSUE TITLE
Brass catcher deletes casings

### ISSUE THREAD

**Issue by Vidiveni** [CleverRaven/Cataclysm-DDA#17670]
Tested with H&K UCP and H&K MP5. When a brass catcher is modded to a gun, the casings will disappear completely instead of landing in your inventory. 

Build 5233.

**Comment by mugling** [comment]
Try unloading the gun at which point it should return them to you.

**Comment by Rivet-the-Zombie** [comment]
So it's broken but not completely broken?

**Comment by mugling** [comment]
That was actually intentional - the catcher stores them in a bag which is emptied at the same time the gun is reloaded/unloaded.

This is presumably how it works IRL (although I'm happy to be corrected). It's also a sane behavior that turrets could later share if we allow them to use gunmods (the brass catcher is the most frequently requested) in combination with other changes to their reloading.

**Comment by Vidiveni** [comment]
>Try unloading the gun at which point it should return them to you.

It works perfectly, thank you. If it's intended then all is fine. I agree; having brass catchers work on vehicle turrets would be a sweet addition.

**Comment by mugling** [comment]
Note that you should also be able to unload an otherwise empty gun if it contains casings. This is important for `RELOAD_ONE` to work correctly.

**Comment by Vidiveni** [comment]
Haven't tested the magazine-less or one-bullet guns yet, but when using guns with magazines it appears you don't get your casings back when reloading individual bullets, without switching mags. You only get them when the magazine is unloaded or reloaded. Not a big problem though.
