### ISSUE TITLE
Tinkering with bionics should cost time

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#17698]
A lot of time! As now both installing and uninstalling them is completely time-free.

**Comment by Coolthulhu** [comment]
I see it like this:
* Long activity
* Not too much time spent on it, because we don't have anything like "take painkillers during long activity if your pain goes above 30", meaning we have to rely on effects acquired before starting surgery
* The activity would progressively cause more and more pain, making intelligence drop, thus making painkillers necessary to properly install CBMs
* If there are friendly NPCs with good skills nearby, the chance to install would be the best of the entire group (of NPCs and the player). Or even higher than that, since player should take penalties for operating on self.

**Comment by nanovad** [comment]
I'm pretty sure you wouldn't operate on yourself without painkillers, unless it was an emergency and there were no painkillers on hand - so I'd say take a bunch of painkillers before you start (maybe a Y/N prompt to take them?)

I don't know how suitability is determined for CBM installs, but it probably wouldn't be hard to check nearby friendly NPC skills in a certain radius. The NPCs could also gain trust from this - I know I'd trust someone more if they asked me to operate on them. Perhaps another prompt "Ask a nearby NPC for help or do it yourself?"

**Comment by kevingranade** [comment]
> Not too much time spent on it, because we
> don't have anything like "take painkillers
> during long activity if your pain goes above
> 30", meaning we have to rely on effects
> acquired before starting surgery

This is backwards, we can easily work around the pain management thing, but
bizarre compromises like, "pain-causing activities can't last longer than 5
minutes" are going to be difficult to root out of the system when and if
the underlying issue is addressed

> The activity would progressively cause more
> and more pain, making intelligence drop, thus
> making painkillers necessary to properly
> install CBMs

Just make a sufficient supply of painkillers mandatory. It's totally
reasonable to say an invasive self-surgery with no pain management is
impossible and just disallow it.

**Comment by pisskop** [comment]
my preference for the matter is to make advanced or impossible to self-install bionics require a doctor stem cell

**Comment by Night-Pryanik** [comment]
Installing and uninstalling bionics through the autodoc consumes time, through the NPC surgeon doesn't.
