### ISSUE TITLE
Bugged broken cyborg corpse on dissector

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#17728]
I checked it in item editor and it has huge negative damage.

**Comment by Soyweiser** [comment]
Yeah, the cyborgs keep walking into the dissectors. (they do spawn next to them). While it is fun, and does kinda fit what I wanted to portray when I added the cyborgs. (basically humans who went mad due to excessive cyborgization, only their head is human. While the robotic body kept reviving them). They are now pretty rare 1 in 10 dissector rooms has one. And they keep being ... dead.

Them walking into the dissector would kinda fit the idea I had. They trying to kill themselves. But it not working due to cybernetics. But it was a byproduct of the design, not the original intent.

I'm wondering what to do with them. Perhaps move the cyborgs to somewhere else.
