### ISSUE TITLE
Survivor's map reveals very large area

### ISSUE THREAD

**Issue by HeadWar** [CleverRaven/Cataclysm-DDA#17748]
360x360 seems excessive for something that's supposed to be a hand drawn map. It's also pretty boring to have that much revealed.

**Comment by Labtop-215** [comment]
It's also strange because it's like Schrödinger's map in that you don't know whats around you until you use it.

You know how computer terminals reveal a sort of quadrant around you and that's it?  Could maps be tied to the quadrant they are found in and only reveal stuff in that area?  So even if you take the map with you, you can't use it to reveal area's that the map shouldn't have been able too?

**Comment by Leland** [comment]
Old suggestion and no recent discussion here. Closing. Feel free to let me know if you want it reopened.
