### ISSUE TITLE
Dodging gains experience very slowly

### ISSUE THREAD

**Issue by HeadWar** [CleverRaven/Cataclysm-DDA#17749]
Maybe it's intentional, but so far I have killed 100 monsters, and gained Dodge experience just once.

Playing as failed cyborg, which might have something to do with it, but I made a quick test with another character, without any experience gain.

**Comment by Zireael07** [comment]
It's not killing monsters which gives you dodge experience, it's actually being hit by them. If you're killing them before they can hit you and/or wear armor all over your body, well, no dodge exp for you.

**Comment by HeadWar** [comment]
I mentioned the 100 just as an indication of how much  I have been fighting.

Why does wearing armor prevent Dodge gain? (Failed cyborgs start with alloy implants all over...)

**Comment by Labtop-215** [comment]
I would think that wearing armor that is too encumbering would potentially stop your character from attempting to dodge entirely.  What does your torso and leg encumbrance look like?

Besides this, dodging only goes up if you are attacked, and I think only if you are attacked in melee.

**Comment by Zilenan91** [comment]
There's also books on Dancing that are relatively easy to find that raise your dodging skill. I think the upper level dodging book can get it to 3, it's called the Book of Dances.

**Comment by Labtop-215** [comment]
I disagree.  You don't have to strip down completely to gain dodging skill.  I have 12 torso encumbrance and 10 leg encumbrance, and I still gain skill from dodging.  You just have to successfully dodge.  My nomad gear gives me 11 bash and 11 cut protection, and it helps protect me from lots of hits when I do fail to dodge.

Having 6 in dodging from a book would break the game I think since having 6 dodging is like and endgame stat.  Even 4 or 5 dodging would be too much overall from a book.  There are just some skills that really need to be practiced, like actually practiced to understand and make use of.  There is only so much you can be taught about combat before you have to physically attempt to use it yourself.

Just treat dodging as a measure of overall combat competency instead of attempting to grind it like everything else.

**Comment by Taberone** [comment]
Having more than 6 dodging doesn't seem that much of a game breaker. IIRC, torso encumbrance reduces the dodge skill by a huge amount, so if you have something like 10 dodge and slap on some body armor and a military rucksack it subtracts 4-6 or something from your dodge.

Even with 10 dodge or higher and the Uncanny Dodge CBM, you'll still get ripped to shreds by bullets from NPCs or Turrets. At least on the IOS version that happens.

**Comment by HeadWar** [comment]
I guess the problem is that you need to dodge successfully to gain experience, which means that it's hard to get started, unless you find a book.

**Comment by Labtop-215** [comment]
> IIRC, torso encumbrance reduces the dodge skill by a huge amount, so if you have something like 10 dodge and a lot of encumbrance it subtracts 4-6 or something from your dodge.

The solution then is to not wear encumbering gear.  That is the point of the encumbrance system.  It's essentially to make it so that if you wear a ton of armor, you wont be able to dodge and that you will have other penalties to offset the protection you are getting.  Alternatively, you can wear so much armor that getting hit wont matter as well.

> On a side note, even with 10 dodge or higher and the Uncanny Dodge CBM, you'll still get ripped to shreds by bullets from NPCs or Turrets. At least on the IOS version that happens.

There seems to be lots of things in the game that are either bugged, or their function is not clear conveyed to anyway.  I remember seeing on here that Uncanny Dodge is only specifically for special attacks and may not even have any effect on ranged attacks at all.  I know this is annoying because Uncanny Dodge specifically tells you it can dodge bullets, but this probably isn't true.

https://github.com/CleverRaven/Cataclysm-DDA/issues/15078
