### ISSUE TITLE
Mixed alcohol makes little sense

### ISSUE THREAD

**Issue by Cynthius** [CleverRaven/Cataclysm-DDA#17802]
Currently, the recipes for strong and weak mixed alcohol only require one unit of an alcoholic beverage, so mixing a drink is essentially just "stirring your can of beer" for 20 seconds. A more realistic recipe would require two different types of alcoholic beverage as input, but there are two problems with that.
1. There is no way to ensure that both inputs are a different drink, so it's possible to simply mix two cans of beer (which could possibly be explained as them being different beers).
2. It's only possible to make a proper recipe that mixes two of the same drink. If you were to make a recipe that required an alcoholic drink as each input, the recipe could be crafted using the same single unit of beverage for both inputs.

Additionally, while strong mixed alcohol does have a use as an ingredient for ethanol and denatured alcohol, the only use for weak mixed alcohol is to drink, but weak mixed alcohol gives less fun, nutrition, and quench than any of its possible ingredients. The dirtiest fix for this would be to simply remove weak mixed alcohol, but a better solution might be to make sure that one ingredient can't be used in two inputs, adjust the recipes to actually mix two drinks, and rebalance the stats of the mixed alcohol.

**Comment by Coolthulhu** [comment]
Weak mixed alcohol could be removed. It was added just to mirror the strong one.

There isn't much sense in preventing mixing the alcohol with itself. It must be possible to mix the mixed strong alcohol with any other strong alcohol, otherwise the entire purpose of it would be rendered null, as you would always need 2 different alcohols just to add them to your mixed storage. You would just have another crafting stage: craft the initial batch of mixed alcohol from 2 different alcohols, then craft the rest from mixed + non-mixed.

**Comment by pisskop** [comment]
Mixed alcohol has come in occasional use.


Early game, for instance, when you have limited physical storage or bottle space.  As a habitual alcoholic, its useful to be able to mix the boozes to create empty bottles.

**Comment by Labtop-215** [comment]
Shot in the dark here.  Could this be handled by the unload menu?  You simply have to make sure that the alcohol has the same stack to volume size, complete the stack, move as much alcohol as possible over to the container being unloaded into, and then convert the container of alcohol into "strong mixed alcohol" or "mixed alcohol" or whatever.

So for example, glass bottle of 15 vodka -> glass bottle of 17 rum.

17 MOD 7 = 2 and 3 remainder.
3 + 4 = 7
Subtract 4 Vodka and add it to the rum to get 21 rum.
Change 21 rum into 21 strong mixed alcohol.

There is room for 0 more stacks.  So don't move any more vodka.
The result should be glass bottle of 11 vodka and glass bottle of 21 mixed alcohol.

It would ensure that 2 different alcohol's are used to create mixed alcohol, and it would prevent the cluttering of the drinks menu with redundant alcohol recipes.

Maybe you can add a hint for this too the first time your character drinks alcohol.  I dunno, if this implemented it would have to be told to the player somehow, or else it would seem unfair to players who don't know you can do that since you can't do this with anything else in the game.

I'm not really bothered by the idea of mixed alcohol being just alcohol you've stirred or anything because I understand that as a limitation of the crafting engine, but this would possibly open up the door to more combination methods, so long as this is documented as a possibility to the player.

**Comment by Xpyder** [comment]
"Mixed Alcohol" actually serves a meta purpose, it's not supposed to equate to a real live equivalent.  

It's meant as a way to store alcohols together, for example if you're just going to use them to make Denatured Alcohol or Molotov's rather than drinking them.  It lets you use some of each if you have partial doses but enough alcohol if you combine it.
