### ISSUE TITLE
Lighting a fire on a spreadable tile needs a confirmation dialog

### ISSUE THREAD

**Issue by ZombiesAreUs** [CleverRaven/Cataclysm-DDA#17821]
After accidentally setting a house on fire trying to activate a flashlight, I thought that lighting fires could use a confirmation dialog. To make it a bit less tedious braziers, ovens, wood stoves and pits should be exempt.

**Comment by Zireael07** [comment]
Neat idea!

**Comment by Labtop-215** [comment]
Do pits and deep pits contain fires now?

**Comment by pisskop** [comment]
im against.

all these confirmation checks slow down the game.

broken windows are a large part of early game, for instance, and its tedium because you should be aware of that minor danger.

same with lighting a bush on fire. :/

most ooc fires are spread by items, not terrain

**Comment by Coolthulhu** [comment]
> all these confirmation checks slow down the game.

I agree, for many of those there should be a different kind of warning.
For fires on spreadable tiles, I'd rather implement the ability to stomp out small fires.

> broken windows are a large part of early game, for instance, and its tedium because you should be aware of that minor danger.

I disagree, it's hard to tell broken window with glass and without glass in console mode when it's dark or when it's covered in blood.

**Comment by Zireael07** [comment]
I play tiles build in ASCII mode and I can't differentiate between the window with glass and w/o.

Also, I haven't seen a fire spread by items but I have seen two flamethrower-wielding NPC induced fires burning down terrain (with no items in-between)

**Comment by pisskop** [comment]
do you why i smash windows twice?  its not because im afraid of 2 ho damage or a 2% chance if cutting clothing, its because itd tedious, a hassle, to press 'yes', i really do want to go through the window and escape the 15 zombie conga line behind me.

its tedium, its inconcenience, the risk of windows is minimal the reward semantic.

even rubble.  id argue that losing your balance is only common when already under attack.


Fire spreads when you light wooden terrain and you dont have a brazier or oven or stove over that tile.  :|

fire is still a primary early game weapon.  early game is the most interesting part of cdda, and its being watered down by extraneous keystrokes.


perhaps an option to turn on a 'safe mode' wouod be better than having to confirm these.  or walking onto thin gas with a filter mask on.  the chance of choking on non-max intensity gas with a filter mask on is so low I cant recall the last time its happened, but i still have to waste keystrokes confirming the action.  it rips you out of the action.

**Comment by Coolthulhu** [comment]
> its tedium, its inconcenience, the risk of windows is minimal the reward semantic.

At the moment being cut on a window can cause a disease, which hits pretty hard if you have no means to cure it.

But I agree, the keypresses (and the disease) are too much. Maybe if there was a faster way to confirm dialogs?

**Comment by pisskop** [comment]
walking/sprinting comes to mind.

sprinters ignore safety warnings

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
