### ISSUE TITLE
Incomplete quests remembered to all characters as one

### ISSUE THREAD

**Issue by CataclysmWanderer** [CleverRaven/Cataclysm-DDA#1788]
In Stable SDL 0.6, Character A gets a quest of NPC Samantha and dies before completing it.

Character B talks with NPC Samantha and is asked if it completed the quest... which the Character B has no way to know anything about. :p

**Comment by qbradq** [comment]
#11384 changes NPC behavior such that this can be closed. Missions are now tracked on a per-character basis as of current master (NOT 0.C stable).

Testing method:

- Create character A
- Create character B
- Create NPC with mission
- Accept mission with character A
- Talk to NPC with character B, NPC will offer the mission to character B as well instead of asking about progress

Please close
