### ISSUE TITLE
Lit charcoal kiln satisfies 'fire' requirement.

### ISSUE THREAD

**Issue by Soyweiser** [CleverRaven/Cataclysm-DDA#17907]
As mentioned here https://www.reddit.com/r/cataclysmdda/comments/4w0gmw/construct_fireplace_or_kiln_why_does_fire

A lit charcoal kiln can work as a source of fire for cooking and other recipes requiring fire.

Imho, this makes construction even less useful (see : #17826) , as you can simply build the kiln, and not even bother with a fireplace. And it doesn't really make sense, as charcoal kilns don't use open flames a lot.

This is not intended as a full bug report, but more a source of discussion, do we want to change this? Or is this fine?

**Comment by Rivet-the-Zombie** [comment]
Yeah this really shouldn't be possible.

>And it doesn't really make sense, as charcoal kilns don't use open flames a lot.

As in 'at all'. Having an open flame would result in a kiln full of ashes, not charcoal.

**Comment by Soyweiser** [comment]
Yeah, I looked at the vid in the reddit tread, and there was some open flames in that one. So that is why I was confused, as I recalled charcoal being no open flame, and just smoldering.

**Comment by Xnfinity** [comment]
He basically using the charcoal kiln as you would a fireplace, kinda makes sense as it still a /fire container/ so fire doesn't spread, though it doesn't stop smoke so there no real problems?

**Comment by petermorck** [comment]
Yeah I'm the OP in that thread.
Just to be clear: I'm using the constructed kiln (so construction isn't less useful in this case) and I'm not using the "Fire the kiln? (Y/N)" option and enabling the charcoal creation process, so it's not a dual-purpose operation so to speak.
I'm just dumping burnable material in it and setting it on fire with a lighter as if it was a fireplace. I can't cook while making charcoal. But, depending on whether it's actually possible to leave a kiln "open" to allow a proper fire in real charcoal kilns, this may still need to be prevented somehow for game balancing purposes.

Removing the fire container flag from it seems like kind of a illogical solution, but would prevent it from being used as a fireplace. Otherwise I guess you have to prevent people from setting things on fire in the same tile, which seems even worse. Maybe there are other ways to solve it. I don't know the game code well, just noticed the flags while searching.

**Comment by Xpyder** [comment]
My understanding of making charcoal is there are 2 ways.  Both would provide heat and light and could probably be used as a fire source.

Direct as seen here and here
 https://www.youtube.com/watch?v=GzLvqCTvOQY
 https://www.youtube.com/watch?v=3orn5uy0DbQ

And indirect which is basically cooking the wood in an airtight container (with a tiny hole to allow the pressure to equalize so it doesn't explode) as seen here and here.  The first one is more about charcloth but is good at explaining the theory behind how it works.  The latter is an actual charcoal kiln+retort
https://www.youtube.com/watch?v=LUtNzzGM2XU
https://www.youtube.com/watch?v=ceJap39Qwro

**Comment by Xpyder** [comment]
Maybe activating the charcoal kiln should turn it into a "trap" tile like deploying a brazier, with the assumption being that you're lighting a fire under it and burning it appropriately?

**Comment by Leland** [comment]
Combining #21054 here. Along with not providing flame, shouldn't provide (much, but more likely any) light either.

**Comment by AlecWhite** [comment]
@Leland could please add the exploit label too?

**Comment by I-am-Erk** [comment]
Tested in game, does not happen anymore. Closing until contradicted.
