### ISSUE TITLE
New enemy group, self-replicating robots.

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#1790]
Belteshazzar mentioned automated fabricators on the forums, and of course my first thought was fabricators gone HORRIBLY WRONG.

My proposal is a new monster type, replicating_robot (not really distinct from copbots, turrets, etc  as far as function, more of a faction).

These robots would as a group want to consume resources, build more robots, and spread.  The overall tone is up in the air, are they combat robots, or just a replication experiment gone bad?  Are they directed by an intelligent AI, or perhaps a survivor, or do they merely represent another mindless force that wants to expand and consume?  Finally, are they a localized threat that sweeps the area around their factory, or will they spread across the whole map if left unchecked?
##

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
