### ISSUE TITLE
Survival marker and permanent marker consume no charges on use

### ISSUE THREAD

**Issue by mightyagrippa** [CleverRaven/Cataclysm-DDA#17926]
To replicate, wish for any marker and any item then use marker on item to make a note or label.

Very minor issue, but it does make any of those items past the first worthless.

**Comment by tswood** [comment]
Confirmed issue still present current master. 

Charges are used if either marker is used to write on the ground.
Charges are not used when writing / remove a label / note on an item.

Removing a label / note probably shouldn't use a charge, but writing makes sense.

Another consideration is if its worth making charges spent based on number of characters written instead of one per use.

**Comment by Night-Pryanik** [comment]
Tested on latest experimental as of 07 April 2019. Can't confirm, both permanent and survival markers' charges are spent when writing notes or labels.
