### ISSUE TITLE
Debug version fails to build

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#17945]
```
Ubuntu clang version 3.6.0-2ubuntu1~trusty1 (tags/RELEASE_360/final) (based on LLVM 3.6.0)
```

```
src/ranged.cpp:1429:24: error: chosen constructor is explicit in copy-initialization
                return {};
```

**Comment by Soyweiser** [comment]
Hmm, im suddenly getting this error:
||=== Build: Release in Cataclysm (compiler: GNU GCC Compiler) ===|
s\Cataclysm-DDA\src\main.cpp||In function 'int main(int, char**)':|
s\Cataclysm-DDA\src\main.cpp|410|error: 'srand' is not a member of 'std'|
s\Cataclysm-DDA\src\main.cpp|410|note: suggested alternative:|
\CodeBlocks\MinGW\include\stdlib.h|353|note:   'srand'|
||=== Build failed: 1 error(s), 0 warning(s) (6 minute(s), 12 second(s)) ===|

**Comment by mugling** [comment]
Is this still a problem?

**Comment by ProfoundDarkness** [comment]
I was getting the first error mentioned.  Now I'm not.  Instead I'm getting:
In file included from src/armor_layers.cpp:8:
src/npc.h:912:82: error: chosen constructor is explicit in copy-initialization
        standard_npc( const std::string &name = "", const std::vector<itype_id> &clothing = {}

Though might be due to running a bit of a dated version...
Ubuntu clang version 3.4-1ubuntu3 (tags/RELEASE_34/final) (based on LLVM 3.4)

cleared ccache, Flags: CLANG=1 LUA=1 CCACHE=1
Those flags with TILES=1 SOUND=1 also fail (same error though in that case before I cleared ccache).

As before, I can compile without CLANG flag.

**Comment by Soyweiser** [comment]
I still get the second error, and it has also appeared in dump.cpp. Build compiles normally if I just remove the namespace reference in front of the function call. `std::to_string( i )` -> `to_string( i )` but im a bit confused why the errors suddenly show up. And that the errors are showing up in more places.
