### ISSUE TITLE
Game runs too slowly

### ISSUE THREAD

**Issue by player0981234** [CleverRaven/Cataclysm-DDA#18019]
It takes me half a minute to start up or quit the game. In cities I only get one move per two seconds at 100 speed. It's fine in combat ( I think a lot before every move ) but too slow for everything else.

**Comment by Coolthulhu** [comment]
Need OS, hardware stats, build and world settings.

**Comment by Zireael07** [comment]
Do you have 3D mode on? Software rendering on? Those are the most common culprits when it comes to slowness.

**Comment by DaliTimelord** [comment]
Build version wouldn't hurt too.

**Comment by player0981234** [comment]
@Coolthulhu 
OS: windows 7 sp1
CPU: Intel(R) Core(TM) i3-2310m
RAM: 4GB
graphic card: Geforce GT 520M
build 5382
World settings are all on their deault values
@Zireael07 
I don't have any of these on

**Comment by DLaboratory** [comment]
1. Where did you download the game, from [http://dev.narc.ro/cataclysm/jenkins-latest/](http://dev.narc.ro/cataclysm/jenkins-latest/)? 
2. Are you using SSD or traditional HDD?

This is pretty weird, I have friends playing the game very smoothly with Core i3-380M, a processor weaker than yours, so the culprit is very likely your OS or your hardware. Try to close all other applications before you launch the game. And open the task manager, see if `cataclysm.exe` is the only process consuming all CPU power.

**Comment by mugling** [comment]
No obvious path to resolution

**Comment by Coolthulhu** [comment]
I'll reopen because I wanted to make a similar issue and this one already exists.
Also, now that I'm currently on Windows, I may be able to locate the source of problems.

I'm experiencing a giant slowdown on Windows 7. It wasn't this bad before. Game load times are horrible, like ones in debug builds, except I built release (for some reason CodeBlocks projects sets both `-Os` and `-O2`).

Some extra details:
* It's not HD, at least not just HD. It worked fine on same HD near 0.C stable
* It doesn't happen on Linux, where load times and draw times are all good
* It could be related to the compiler, would be cool if someone could compare Visual Studio builds (with #18176 merged, since it will most likely not compile otherwise) with GCC ones. On Windows of course - GCC vs. Clang on Linux and BSD will most likely not be all that different.
* Draw times on Windows are horrible, but they were always bad. Large viewport significantly decreases performance there, to the point where tiles builds can run faster than console ones just because they force smaller viewports (tiles are big)
* Load times somehow got worse despite `data` not growing too much. Maybe we could reconsider the old proposal to have an optimized giant json file generated after build? Unix systems could have much better file access, especially considering they have good file systems while Windows is all about the rusty NTFS

**Comment by mugling** [comment]
> Maybe we could reconsider the old proposal to have an optimized giant json file generated after build?

Try concatenating it and seeing if this helps. If it does I'll extend the linter to pack the data in an optimal ordering.

**Comment by Coolthulhu** [comment]
I managed to concatenate it. We have some minor order dependencies in the code, but I don't think they affected much. Managed to hack around the ones that throw errors.
It's not just file reading for sure. The times did get a bit shorter (didn't measure exact times, but I can tell that they did improve), but not significantly so. May be worth doing since we'd only sacrifice order dependence (which should be done with finalization, not filenames), but it won't fix the whole issue.

I'll probably need to get a profiler on this to properly time it then.

**Comment by schmithub** [comment]
I don't know about with Windows, but playing in Linux and setting software rendering to false, things like navigating the crafting menu are rather laggy in response.  If you enable software rendering (set to true), then navigating them becomes very responsive like desired.  However a big downside to software rendering enabled is many tiles show up (regardless of tileset used) with seams (ugly lines between tiles in some places).  However with software rendering, the game seems to run very smooth overall pretty much everywhere.  This is rather puzzling as you would think it would be the opposite (hardware rendering would be more responsive than software rendering).

**Comment by mugling** [comment]
Specific code performance issues are being tracked elsewhere

**Comment by Davidkuku** [comment]
Hi...
Am David.
Am using an Intel core i3-380m 
And my fifa 14 lags all the time 
I've tried updating all my drivers 
But it still changes nothing 
I have a 4gb ram..
3.80 usable. 

The release date of my driver is 26/11/2012
Driver version 8.15.10.2900 

Windows 10 64bit
