### ISSUE TITLE
Medieval Stuff mod armors are not up to date on balance

### ISSUE THREAD

**Issue by Barhandar** [CleverRaven/Cataclysm-DDA#18024]
Armor values overhaul on Feb28 did not change them at all. It produces things like bronze greaves having 20 encumbrance while iron greaves have **6**, with similar levels of protection. Or nasal helmet, which is better than hard hat _and_ protects the eyes as well.

**Comment by chaosvolt** [comment]
Hard hat is make of plastic. It will protect you from some stuff being dropped, but if a utility worker drops a wrench, you are straight-up fucked.

Nasal helmet was meant to be balanced against other ancient metal helmets both vanilla and in the mod, due to being uncommon and requiring some investment to make.

**Comment by Barhandar** [comment]
The helmet will bend and is more likely to transmit damage. Both will glance cut strikes, [but hard hat, especially with padding, will likely absorb more blunt damage](https://youtu.be/-4pUyUA14oc).  
If the wrench drops in the same way on the helmet you'll be fucked _and_ deafened!

Basically hard hat should have amazing bash protection but small cut and absent pierce protection, while helmet should have good cut and pierce protection but bad bash.

**Comment by Leland** [comment]
Fixed by #18246
