### ISSUE TITLE
Hypervitaminosis Spam

### ISSUE THREAD

**Issue by DaliTimelord** [CleverRaven/Cataclysm-DDA#18026]
If my metabolism becomes unstable, then stable, then repeat ad nauseum, isn't it technically still unstable?
<img width="957" alt="hyperspaminosis" src="https://cloud.githubusercontent.com/assets/20878878/17647513/803856d6-61c1-11e6-84c0-9f34e4424140.png">

**Comment by mugling** [comment]
How to reproduce?

**Comment by Coolthulhu** [comment]
Confirming it does happen.

`player::update_vitamins` removes deficiency and excess per every non-deficient or non-excessive vitamin.
That is, if you've got too much iron and optimal vitamin A, iron will apply hypervitaminosis, then A will remove it, because it interprets it as vit A hypervitaminosis.

Splitting hypervitaminoses to have 1 per vitamin (and confirming in code there are no duplicates) would fix it.
