### ISSUE TITLE
Have NPCs want to learn?

### ISSUE THREAD

**Issue by DaliTimelord** [CleverRaven/Cataclysm-DDA#18039]
Right now you can teach your NPCs about anything you can manage out of a book, but I was wondering if there could be NPCs that desire knowledge?
- NPCs could have quests where they want to learn about X until they reach level Y, but either they don't have a book for this level, they're illiterate, or they are farsighted and can't read without prescription glasses. The NPC could also have the book, but just want you to read it to them since they are illiterate or need glasses.
- NPCs, while you're not exploring, fighting, interacting with them or having them assist you with a task, they could sit down and read a nice book, for fun or for skills, or practice melee or ranged weapons, maybe on a fighting dummy?

What's needed is that a dummy would have to be a new furniture item, would not be able to teach beyond a level [has similar horrors in comparison to allowing gyms to give you stats], a special prompt where the player can say that "everything's chill, go play while I do stuff", and then the ability for NPC to know when everything is not okay "Crap! I triggered a trap!" "A zombie's coming towards me!" and be able to react or revert.

Any thoughts on this? This could just be for NPCs wanting to read books by themselves.

Edit: #18066 could also fulfill NPC learning quest requirements, although in a rather rudimentary way.

**Comment by mugling** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug

It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request

If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue

Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
