### ISSUE TITLE
Tents and fences render incorrectly in isometric mode 

### ISSUE THREAD

**Issue by Chezzo** [CleverRaven/Cataclysm-DDA#18134]
From Kedryn in the [Forums](http://smf.cataclysmdda.com/index.php?topic=13196.0). 

Kedryn found that tents and fences render incorrectly in isometric mode, "because f_canvas_wall and f_canvas_door, not being actual walls and doors, don't line up or rotate properly. The doors won't 'attach' to the walls and the walls won't make corners if a door is next to it instead of a wall."

![tents](http://i.imgur.com/ACm77SM.jpg)

**Comment by Karlieb** [comment]
Would this help or work only with terrain tiles? Would 'fix' the water, anyhow.

https://github.com/CleverRaven/Cataclysm-DDA/pull/14874

**Comment by hitbutton** [comment]
The fences are a tileset issue. t_fence_v and t_fence_h are functionally identical to t_fence since #14874, so those terrains just need the connections set up in the same way in the tileset config.

The tent issue is a bit thornier, rooted in the fact that tents are implemented as furniture instead of terrain. Connection groups to allow furniture to connect to furniture of a different type aren't implemented in the code right now.

**Comment by int-ua** [comment]
Closing as this tileset no longer exists, at least in this repository.
