### ISSUE TITLE
Make martial arts manuals follow color conventions as other books

### ISSUE THREAD

**Issue by mightyagrippa** [CleverRaven/Cataclysm-DDA#18146]
They're already red for unbrowsed and gray for used up. But they're also gray if you've browsed but not learned them. Please make them blue for browsed but not memorized.

The issue is partially due to a hilarious hack at https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/iuse.cpp#L2833. The martial art attached to a book is not defined by a json attribute; every MA book is named in the format "manual_foo" and the code takes the text after the seventh character of the item name and concatenates it to "style_" to get "style_foo".

**Comment by Leland** [comment]
Closing due to stalled discussion. If there's still interest, ping me here to reopen or just make a new issue.

PS, for reference, [here's the correct line](https://github.com/CleverRaven/Cataclysm-DDA/blob/c99dc5af0068f680253aefc68ca036558ddbd727/src/iuse.cpp#L2740-L2742) referenced in OP's description. Make sure to press <kbd>Y</kbd> when you're linking to a line in code, which will append a specific commit to the link. Otherwise, as commits are added, the line will be completely different down the line.
