### ISSUE TITLE
Static NPC aggression is not working

### ISSUE THREAD

**Issue by pisskop** [CleverRaven/Cataclysm-DDA#18154]
In any building or map area, regardless of whether or not Ive modded them in.

Im using a pretty character, but they arent even turning their usual 'red' color to indicate hostility upon LoS

**Comment by Taberone** [comment]
Are those the guys that turn red a few turns after spotting you?

**Comment by Zilenan91** [comment]
Actually I've had a similar issue, but it was because the NPCs couldn't see me. Military Outposts where Bandit NPCs spawn in are usually dark on the interior, so if you have Night Vision you'll see farther than NPCs in the dark, and thus they won't be hostile. The problem with this is that if you kill them before they become hostile to you, you lose 100 morale, and if you go closer to them to make them hostile they pump you full of 5.56 until you die.

**Comment by pisskop** [comment]
fixed by
