### ISSUE TITLE
Arcana mod: Silver athame broken, numerous items generating error message, other mistakes.

### ISSUE THREAD

**Issue by chaosvolt** [CleverRaven/Cataclysm-DDA#18177]
Well, as I kinda suspected, when I finally poke my head onto here and take a look at how the game has been since I've been gone, and find problems. So far just things in Aracana mod, two screwups by others and three lingering screwups I made ages ago.

The first is that silver athame no longer works as intended. No idea how long ago this change was made, but apparently the knife use_action is now linked to either a butchering or cutting quality. So the active athame tries (and likely fails) to cauterize a wound, thus doing the exact opposite of what it normally does. :V

For blood_athame_active, changing this:
```
    "use_action" : {
        "type" : "consume_drug",
        "activation_message" : "Upon drawing the blade across your palm, wounds open elsewhere on your body!",
        "effects" : [ { "id" : "bleed", "bp" : "TORSO", "duration" : 100 } ]
    },
"qualities": [["CUT", 1], ["BUTCHER", 3]]
```
to this:
```
    "use_action" : {
        "type" : "consume_drug",
        "activation_message" : "Upon drawing the blade across your palm, wounds open elsewhere on your body!",
        "effects" : [ { "id" : "bleed", "bp" : "TORSO", "duration" : 100 } ]
    }
```
will resolve that issue.

The second is that the hammer of the hunter fucks up when attempting to use its flash effect. This appears to be caused by it not having a charges_per_use given to it, so it transforms into a glowing hammer of the hunter without consuming the dull essence, and thus fucks up and spits out an error message.

Veinreaver is also subject to the same mistake. It already has a charges_per_use, but it seems like countdown might not work well for this item. Instead, if this:
```
    "turns_per_charge": 1,
    "flags" : ["DURABLE_MELEE", "CHOP", "LIGHT_8", "NO_SALVAGE"],
    "revert_to": "bloodaxe",
    "category": "weapons",
    "qualities": [["CUT", 1], ["HAMMER", 2], ["HAMMER_FINE", 1], ["BUTCHER", 16]],
    "use_action": {
        "type": "explosion",
        "sound_volume": 1,
        "sound_msg": "Drip.",
        "no_deactivate_msg": "You can't dispel the effect.  Might want to try throwing it instead.",
        "fields_radius": 3,
        "fields_type": "fd_blood",
        "fields_min_density": 3,
        "fields_max_density": 3,
        "explosion": {
            "power": 12
}
```
became this:
```
    "turns_per_charge": 1,
    "ammo": "essence_blood_type",
    "flags" : ["DURABLE_MELEE", "CHOP", "LIGHT_8", "NO_SALVAGE", "NO_UNLOAD", "NO_RELOAD"],
    "revert_to": "bloodaxe",
    "category": "weapons",
    "use_action": {
        "type": "explosion",
        "sound_volume": 1,
        "sound_msg": "Drip.",
        "no_deactivate_msg": "You can't dispel the effect.  Might want to try throwing it instead.",
        "fields_radius": 3,
        "fields_type": "fd_blood",
        "fields_min_density": 3,
        "fields_max_density": 3,
        "explosion": {
            "power": 12
        }
      }
```
That should ensure it works as intended.

The cursed blade also fucks up for the same reason. Assign it blood essence as an ammo typo, give it NO_UNLOAD and NO_RELOAD, boom.

Now for another fun mistake. I intended the delay between activating the hammer to be briefer than it is. Setting the inactive hammer's use_action to a target charges of 0, and setting the active version's initial charges to 0, seems to eliminate this excess delay.

The other two issues are typos I made that no one has caught in all this time. In the snippets, the first note_chalice section should be:
```
        "text": "\"Those fools actually believe a bunch of blood mages caused all this?  Tore down the barrier between worlds?  I don't know what caused it, but the others only exacerbated the problem.\""
```
The "it" would be the missing word.

Minor: wyrmskin material (makes the wyrmskin armor acid-resistant) was meant to be hidden by naming it leather. But it had to have leather added as a material to allow repair. Changing wyrmskin's visible name to, well, wyrmskin will resolve "leather" appearing twice on the material list.

And finally, the active incorruptible sword (sun_sword_on) has a lingering mistake in its description. It is still described as "some kind of arming sword" instead of "some kind of broadsword" like the inactive version. This was back when I made the recipe require an already-made sword instead of making one from scratch.

I no longer play this game, nor do I frequent the forum like I used to. But I still feel a fondness for the mods that I developed. I feel as though some recent contributors do not have that care and concern for their work, even work they're still an active part of, compared to other contributors past and present. Though even I made fuckups, both in terms of the actual work and in interactions with others.

**Comment by cainiaowu** [comment]
My guess is that nobody actually play this mod, so such kind of broken thing dont get spotted.

And IMHO mod contents should maintained by the modder not by the devs.

**Comment by chaosvolt** [comment]
Gee. I feel so fucking loved. :V

I used to maintain this mod. Feel free to tell @kevingranade that opinion of yours, but even if he let me contribute again, I don't think I could put my heart into it like I used it.

**Comment by mugling** [comment]
Actions resulting from qualities shouldn't obliterate any specified via `use_action`?

**Comment by Taberone** [comment]
I've always been playing with the Arcana mod. I've never gotten far enough to do any magic or anything, but I have gotten far enough to run into the buildings from the Arcana mod(And get horribly murdered by whatever lies inside those buildings most of the time when I foolishly try to explore).

**Comment by chaosvolt** [comment]
> Actions resulting from qualities shouldn't obliterate any specified via use_action?

Shouldn't, but did. See forum thread where I was made aware of this: http://smf.cataclysmdda.com/index.php?topic=13209.0

Rather obviously, the fact that I explained what to remove means that yes, I tested it and quickly realized it defaults to the first option on the knife menus. This is because the active silver athame is, well, and ACTIVE item and tries to engage its use_action on running out of charge. But as with any active item, it defaults to the first AVAILABLE action if multiple are provided.

I made sure that the active athame lacked the knife action for exactly that reason, until it went and got that action hard-coded into a quality. I didn't think leaving the qualities in the active version would hurt anything. -_-

**Comment by aeoo** [comment]
If I reported every bug I come across I'd have no time to actually play.  The game has so many bugs that I just accepted it as a normal fact.  I opened one issue recently, mostly on a lark.  If I were actually serious I'd open a bunch of issues for AIM and dragged vehicles, but I'm not up for it.

BTW, I love the concept of the arcana mod, but I find all the arcana starting locations to be impossibly difficult and leaving those places safely is not something I've been able to do either.  So I always play with arcana enabled, hoping that I'll run into one of the books and can begin learning and using the arcana skill.  The problem is, I never find these books anywhere.  I do find "essence" sometimes on shady zeds, necros, etc., but I have no clue how to begin using the arcana skill from scratch.  So that's where I'm at.  I love the idea, but the starting scenario is stupid-hard (so I avoid it), whereas naturally learning arcana from 0 using one of the other starts seems to be next to impossible.  But it isn't for lack of trying!  Nor is it because I don't play the arcana mod.  I always have it turned on.

What might help is some kind of newbie guide for the arcana mod.  How to start grinding arcana from 0?  Where to find the books?  It seems the only way to know this is to read the source code.

**Comment by chaosvolt** [comment]
Mansions are, last I checked, the foremost example of where to find arcana books. You can also sometimes find offering chalices and even the symbol of judgement, which is your best bet for increasing arcana skill without the books, since it uses regular essence. Libraries also rarely have Apprentice's Notes and History of Alchemy, and churches are supposed to (also rarely) have The Cleansing Flame.

As for the scenario, it's currently fucked over by issue https://github.com/CleverRaven/Cataclysm-DDA/issues/18184 . But the default starting location, the curious structure, is generally the easiest. All the nasty enemies are underground, and the first basement level has decent potential loot relative to the difficulty. The peculiar shrine is perhaps second easiest, though the outside is still potentially hectic. Both of them have the hardest end bosses though, because fire. :V

I did consider basements at one point, but they aren't JOSNized. Or at least, weren't back when I was a contributor. No idea now.

**Comment by chaosvolt** [comment]
Eventually poked my head back onto the wiki for once, to at least make a guide to the scenario itself: http://www.wiki.cataclysmdda.com/index.php?title=Guide:_Seeker_of_the_Arcane

**Comment by aeoo** [comment]
>As for the scenario, it's currently fucked over by issue #18184 . But the default starting location, the curious structure, is generally the easiest.

And yet I get destroyed if I try to explore it.  It's possible I just don't know how to play.  I'm just saying how I experience it.  The only way I can explore the first starting location in the dedicated arcana scenario is to pick "Freeform" and give myself tons of points all over the place, then I can smash everything.  I don't mind doing some of that up to a point, but beyond a certain point it starts to feel too cheap.  I like to play with freeform, but I still limit which skills and how many points I allow myself to take.  I mostly take all the skills that are easy to grind but boring, like survival 5, fabrication 5, etc.  I don't want to grind those so I just start with them.  I skip the boring part of the game and go straight toward the fun part. :)  I take between 2 and 4 points in dodging, melee and unarmed (don't like grinding those against wimpy critters, feels like a waste of my time), but that's generally not enough to survive for me.  (Maybe a better player can do it, but not me.)  Things in the arcana church basement are very agile and brutal and they tend to skin my characters alive if I just go down.  On the other hand, it's not fun to grind outside the church.  Plus, if I try to simply abandon the location and come back to it later, either a moose or a bear or a jabberwok invariably gets me, so I haven't been able to reach civilization by trying to run away from the arcana start location.  I'll give your guide a read and maybe try again.  I really want to get bloodmage going, but not if I just die 20 times in a row.  If I die that often, I'd rather play an easier start. :)

Another note, the staff that shoots fire is very powerful but I can never hit anything with it.  The fire seems to miss whatever I aim at and hits 5 tiles behind where I was aiming.  I don't know if that's normal or not, but it makes it virtually unusable.  Maybe I need a very high marksmanship skill?  No idea.  Plus the fire it creates is just... well... fire!  Fire isn't all that powerful unless I can trap monsters in it.  So it's a hassle, basically.  It's easier to just smash things with it than to shoot fire.  And athame seems like a precious item, so I am always leery of fighting with it, because what if I damage it?  Where will I find a second athame?  It's not like athames are laying around.  I always play with the arcana mod, but never see any athames anywhere unless I start with one.  So they seem too precious to use for fighting.

Just some comments.  Chaos, I am a huge fan of all your mods!  To me CDDA is a much better game because of your mods.  So thank you.  I wouldn't even think of playing without "more survival tools."

**Comment by chaosvolt** [comment]
It's fine. I did post in the guide the advice that it's generally a solid idea to stick to the first part of the curious structure or island temple, but even clearing the first part of it can be difficult without saving a point or two for skills. Which the player base is mostly conditioned to never do because you can always raise your skills, but you can't unspend character creation points. XP

And...fuck me. Is that bug where you can't aim explosive shots at the ground STILL an issue? That was a problem way back before Kevin gave me the boot, so it seems some fuckups never get fixed.

In any case, thank you. I'll admit that yeah, overall it can be an awkward challenge at times, and I suspect that making it cost points might've been a bad decision. I'm betting high odds that some other dev suggested I make Seeker of the Arcane cost 2 points though. :V

**Comment by aeoo** [comment]
>And...fuck me. Is that bug where you can't aim explosive shots at the ground STILL an issue?

Actually I did try to aim it at the ground and it worked better then.  So it's probably not an issue?  But it's not intuitive to aim at the ground imo.  It's not a biggie once I know I should always aim it once square in front, but that's not the default aiming behavior and it's not explained that while everything else should be aimed at the target, the staff alone should be aimed one square to the side of the target.

> That was a problem way back before Kevin gave me the boot

Please tell me this didn't happen.  I really didn't like Kevin to begin with, but hearing this...  I'll just stop here.

>I suspect that making it cost points might've been a bad decision

I agree.  But luckily "Freeform" is an "official" choice now, so it's not a huge problem provided you don't mind taking a hit to your pride for choosing "freeform." :)

**Comment by chaosvolt** [comment]
> Please tell me this didn't happen. I really didn't like Kevin to begin with, but hearing this... I'll just stop here.

Pretty much. It's a long story that involves both Kevin and I being rude to each other, and I readily admit my part in that. This has been a thing since february.

**Comment by aeoo** [comment]
>Pretty much. It's a long story that involves both Kevin and I being rude to each other, and I readily admit my part in that. This has been a thing since february.

I'm sad to hear this.  CDDA is going to be a much shittier game without you.

**Comment by chaosvolt** [comment]
I've been gone since february. ._.

**Comment by aeoo** [comment]
>I've been gone since february. ._.

I assumed you just left on your own...  I had no clue *why* you were gone. :/

**Comment by chaosvolt** [comment]
Occasionally someone over on Utterly Made pokes their head into the CDDA forums to, aong other things, remind people that I didn't simply leave, in response to people asking why I'm not around to fix things when somebody inevitably breaks one of my old mods. For now it's just a matter of waiting for the multiple people who've offered to PR a fix over the past couple days to actually submit said PR.

I love the fact that literally the only discussion here that's been on-topic and relevant to getting this fixed has been @mugling expressing disbelief that their PR could've broken an old, obscure misuse of use_action and active items.

**Comment by mugling** [comment]
Please avoid cross-posting, quotation is from #17058 but discussion preferably to continue in this issue

> If you give an active item multiple choices of use_action, it will automatically select the highest option on the menu, and thus break if you were trying to make it do something else

It's not necessarily the first JSON entry that is chosen. Actions are stored in a `std::map` for which the sort order is implementation dependent so having multiple `use_action` could result in the action invoked for active items varying with different platforms.

**Comment by chaosvolt** [comment]
Hmm, odd. I only knew that the cauterize item on the menu is the highest entry of the knife action menu. Either way, I didn't expect that retaining cutting quality on an active item would ever lead to adverse effects. You only get a single turn before the effect triggers anyway, so I don't know why I retained that quality. Players likely wouldn't get any chance to notice it, logically.
