### ISSUE TITLE
Large Electric Motors are noticeably worse recently

### ISSUE THREAD

**Issue by Zilenan91** [CleverRaven/Cataclysm-DDA#18324]
They use up a monstrous amount of power now. I have four car batteries on my SWAT truck, almost the entire top filled with upgraded solar panels, and I can only drive a few map tiles before running out of power.

An example of this is when I camped overnight on some dirt areas and when morning came I tried to drive away and I kept getting messages that my car was too heavy and my power would just dissapear after a few seconds of me trying to move. I tried replacing my large electric motor thinking it was a weird bug, dropped about 2k pounds of weight to see if that was the problem, and even added another electric motor but this just caused the power to drop to 0 instantly instead of after a few seconds like it did before, still giving me messages that it was Too Heavy for my large electric motor(s). The problem persisted, and I was only able to leave this area when I installed a V6 gasoline engine and drove away, receiving only about one Too Heavy message until I got onto a road. Even after getting out of the area the one remaining large electric motor I left in my car still had absurd power usage just for driving a few map tiles.

Large Electric Motors were perfectly fine before filthiness was removed, as a sort of landmark. Something changed that caused them to just be awful engines. I even tested them with an RV I spawned in the debug menu, as well as a few extra car batteries and upgraded solar panels and they still had ridiculous power requirements.

**Comment by Coolthulhu** [comment]
Could be offroading penalty.
Does your car have tiny wheels?

**Comment by Zilenan91** [comment]
24' wheels, SWAT truck defaults. I did think it was offroading penalty, but even outside of that one incident large electric motors still have ridiculous power requirements.

**Comment by Griffinhart** [comment]
For reference, if I'm understanding the `vehicle_parts.json` correctly, these are motor power consumptions (newgative epower) and panel/reactor power production (positive):

Part|epower
------|-------
small electric motor|-5,000
electric motor|-20,000
enhanced electric motor|-200,000
large electric motor|-120,000
solar panel|50
reinforced solar panel|45
upgraded solar panel|100
reinforced upgraded solar panel|90
quantum solar panel|300
minireactor|149,000

And for further reference, battery capacities from `items/vehicle/battery.json`:

Part|capacity
----|------
small storage battery|500
medium storage battery|7,000
storage battery|40,000

Which is to say - if I'm understanding these numbers right - a single `large electric motor` requires the power of 3x`storage battery` to power for... however long.

I think electric motor power consumption needs to be scaled back by an order of magnitude (or maybe two).

**Comment by Zilenan91** [comment]
120,000 power consumption is literally insane, it should be 80,000 at the very most, and maybe not even that for even the enchanced motor.

**Comment by Griffinhart** [comment]
Yeah, the `electric motor` and `enhanced electric motor` consume literally three orders of magnitude of power more than even the best solar panel can provide. It *might* be possible to fit 10 solar panels onto a single vehicle, but more than that is kind of unrealistic, and even then the consumption would outstrip the production by two orders of magnitude.

Maybe solar arrays are better, and it's expected that any serious electric-powered vehicle is going to have an array (or an array of arrays)? I haven't checked their values.

It might be intended that consumption *should* outstrip production by a lot, but then the small size of storage batteries (standard vehicle battery is 40k, large engines eat 120k per whatever unit of time) means that you can't reasonably build a decent charge unless your vehicle is literally packed full of batteries (and IIRC standard electric cars only have 2 batteries?).

Note that these are just numbers without context. I have no idea how much power is *actually* consumed by a given engine per turn or whatever, I haven't actually looked at any of the relevant vehicle code.

**Comment by Zilenan91** [comment]
Downtimes are fine. You had to do that before occasionally. After driving what I'd estimate to be a mile or three you'd be at a bit below 50% charge and would usually sit for a while, read a bit, maybe craft something. The point is that the distance you could drive was reasonable. Currently you can drive like 6 map tiles and you're at empty.

**Comment by Griffinhart** [comment]
As an aside, the way the vehicle part jsons are organized makes looking things up... kind of a pain in the ass.

data/json/vehicle_parts.json
data/json/items/vehicle_parts.json
data/json/items/vehicle/*.json
data/json/vehicleparts/*.json

The data seems spread out all over the place, and some jsons aren't fully inclusive of stuff (e.g. data/json/vehicleparts/engine.json does not include any of the electric motors, the batteries in data/json/vehicleparts/battery.json don't have their capacities or descriptions, etc.).

**Comment by mugling** [comment]
`items != vehicle_parts` so they are separated by JSON type. Consider items such as `funnel` and `sheet_metal`. We are currently in the progress of migrating from the the legacy files to the hierarchical structure.

**Comment by Coolthulhu** [comment]
> 120,000 power consumption is literally insane

Is heavily misunderstanding how it works.

It's the ratio that matters, not absolute value. `epower / power` specifically.

As for low range per battery, it's mostly because currently batteries are small. We don't have a big battery, meaning that any actual electric vehicle needs to have a stack of them to work right.
This could be changed by:
* Bringing back technomagic battery storage which make vehicle energy free - that would be a bandaid fix
* Rescaling engine and alternator epower values. Could be just by some constant. This could also help with making vehicle energy not free (currently gasoline is like 100+ times more energy dense than batteries)
* Adding a big battery part, with giant storage and giant weight. Adding it to electric vehicles that store power (everything except atomic and pure solar ones, which have other sources)

**Comment by Griffinhart** [comment]
@mugling Sure, but what I'm saying is that there is both a `vehicle_parts.json` in the `items` directory, *and* there are vehicle part JSON files inside of the `vehicle` subdirectory inside of the `items` directory. If this is all because it's a WIP migration, then sure, whatever. It's just annoying to have to look at like, four different places for one piece of data. (Thank goodness for grep.)

@Coolthulhu 
>Rescaling engine and alternator epower values

This does not address power problems with pure electric vehicles.

>Adding a big battery part

That would seem like the most sensible solution, though I don't know what real-world all-electric vehicles use in terms of power storage.

**Comment by mugling** [comment]
> and there are vehicle part JSON files inside of the vehicle subdirectory inside of the items directory

As in `vehicle_part`? Where?

**Comment by Griffinhart** [comment]
as in `data/json/items/vehicle/battery.json`, for example.

**Comment by mugling** [comment]
That's not a `vehicle_part` but an `item`. Find the definitions for `funnel` and it will become clearer to you

**Comment by Griffinhart** [comment]
Sure, but that's where the actual battery storage capacities are listed.

Basically, I had to search four different files:

`data/json/vehicle_parts.json`
`data/json/vehicleparts/battery.json`
`data/json/items/vehicle_parts.json`
`data/json/items/vehicle/battery.json`

It didn't occur to me to look at `items/vehicle/battery.json` first because it wasn't intuitive that a storage battery for use on a vehicle would be located in `items`. (It also didn't occur to me that the different stats for a battery would be split across multiple files.)

**Comment by mugling** [comment]
These are legacy:
```
data/json/vehicle_parts.json
data/json/items/vehicle_parts.json
```

This split is intentional:
```
data/json/vehicleparts/battery.json
data/json/items/vehicle/battery.json
```

Again see the `funnel` item for why there has to be a split.

**Comment by Cat09** [comment]
[](http://www.techspot.com/news/66323-new-electric-bus-proterra-can-travel-up-350.html)
"This new electric bus from Proterra can travel up to 350 miles on a single charge"
also, the latest tesla vehicle breaks 300 miles/charge. If we assume that battery technology gives +10-20% storage capacity by Year:cataDDA , then that's 330-360 miles/charge on production vehicles (w/o solars)
so player made vehicles should probably be balanced for todays miles/charge, barring super-tech.
as an aside, what does the current EPower reperesent?  it's a little unintuitive: it looks like a large motor uses 3 storage batteries per second / tick

**Comment by Coolthulhu** [comment]
Using real life data can work, but we'll need to get stats like vehicle weight and battery weight.
And then, miles/kilometers/etc. don't really make sense in the DDA world, we'll need to compare energy densities instead. That is, "gas_car on full gas tank can drive for x distance, elec_car on full battery can drive for y distance"

> as an aside, what does the current EPower reperesent? it's a little unintuitive: it looks like a large motor uses 3 storage batteries per second / tick

There's a hidden multiplier (hardcoded). Every unit of power is worth 373 epower.
To get epower of engine to battery, you have to divide it by 373. That's at full use. Below full use, there's a linear decrease.
So, if the engine thrusts at 50% power every turn, it will drain `epower / 373 / 2` units from batteries every turn. That is assuming no strain (going over safe speed) - strain will drain all power in seconds while damaging the engine.
```
120000 / 373 / 7000 = ~0.046
```

So a large electric engine will take 21 full thrusts to drain a storage engine.
That's very low and needs adjustments, but not as alarming as it looks from raw numbers.
For comparison, a medium engine has 1/4 the power, but 1/6 the epower, giving it 150% the efficiency.

Where possible, I'd prefer to adjust the engines rather than batteries.

**Comment by Zilenan91** [comment]
yeah the batteries aren't a problem. They already store tons of powers, it's just that large electric engines absolutely delete power right now.

**Comment by Coolthulhu** [comment]
Need a good test.
I tried just spawning an electric car and driving it around. It drained power pretty fast, but it was nowhere near

> Currently you can drive like 6 map tiles and you're at empty so something has changed.

I'm thinking about making it so that a freshly spawned solar car running on one engine only could drive indefinitely at some low speed, as long as it stays in full sun. Something like 20-30 mph.

**Comment by DangerNoodle** [comment]
I just had an electric scoot complaining about it being too heavy. Electric motor was in the green, so it should not be making this complaint.

**Comment by Zireael07** [comment]
@DangerNoodle: this is about power, not weight.

**Comment by DangerNoodle** [comment]
I noticed that @Zireael07, I was simply reporting the message the game uses. All other electric vehicles are heavier, but they also have more powerful engines.

I managed to go nowhere in my testing. At first I kept tweaking small electric motors, before I realized that those vehicles use normal electrics. I fully suspect now that a genuine small motor likely can not even power even a bare-minimum setup.

Meanwhile, even doubling the power of standard motors was not enough, nor was combing that increase with more efficiency (via not increasing `epower`).

I have yet to hit the minimum power to make an electric scooter or bicycle function.

**Comment by DangerNoodle** [comment]
I have quickly determined that buffing the power of small/medium motors is not the ideal solution, as even 250 is insufficient. Reducing the power consumption seems to be more effective and avoids giving scooters triple-digit max safe speed.

I will experiment with the `epower` needed to prevent electric bicycles and scooters draining in a few turns, then see what it takes to make small engines viable for oddball minimalist builds (electric shopping cart?) to work.

**Comment by DangerNoodle** [comment]
I stand corrected. I mistakenly set the `epower` of medium motors to positive, that was what make it suddenly work. Set it to a 1:1 ratio of power to consumption and it went right back to bottoming out the battery.

In contrast, something I did suddenly make electric bicycles start working for a decent length of time, despite their use of small motors making the total power and efficency vastly inferior to standard motors.

**Comment by mugling** [comment]
Electrical balance is known concern and is being tracked in multiple other issues
