### ISSUE TITLE
Attacking small things is unreasonably difficult

### ISSUE THREAD

**Issue by Lady-Luck** [CleverRaven/Cataclysm-DDA#18336]
With no encumbrance whatsoever, a sewer rat can take me from full health to dead if I try to spar with it enough. I will never hit the damn thing and it will slowly wear me down and kill me. I mean, it's easy enough to avoid, get it locked in a room, but come on. This is just silly. Back when I played CDDA a year ago this wasn't an issue, I imagine some new melee algorithm was put into place that makes small things way too difficult to hit.

In the IRC people recommended me I start a fire under it or something. Isn't resorting to that kind of silly?

**Comment by Zireael07** [comment]
What are your skills?

**Comment by Lady-Luck** [comment]
This is with 0 melee. But I mean, come on. It's a sewer rat.

**Comment by mugling** [comment]
Have you ever tried chasing a rat IRL?

**Comment by Lady-Luck** [comment]
>Have you ever tried chasing a rat IRL?

This rat is chasing me!

**Comment by mugling** [comment]
Rats add an element of danger to basements for new players.

**Comment by Lady-Luck** [comment]
>Rats add an element of danger to basements for new players.

I mean, am I crazy in thinking it's silly for an unskilled character to not be able to hit a sewer rat at all without resorting to gimmicks?

**Comment by Lady-Luck** [comment]
It is far easier to hit a sewer rat with a thrown object or a firearm than it is swinging something at it.

That's as if it was easier to kill a fly with a BB gun than a flyswatter

**Comment by Zireael07** [comment]
If you have 0 melee skill, don't try to hit the rat, just get the heck out of there and go back once you have 6-7 melee. Or try throwing stuff at it. Rats are d*mn nimble IRL too, or so I heard.

**Comment by Lady-Luck** [comment]
Again, it's really silly that ranged would be more accurate than melee in this situation. It should be much harder to hit a small target with ranged than with melee, not easier.

**Comment by Zireael07** [comment]
... I think we're talking circles here. This belongs in the forum, not in GitHub issues if we're gonna have a long discussion.

**Comment by Lady-Luck** [comment]
I'm honestly surprised this is intended behavior.

**Comment by Rizoel95** [comment]
If we're not going to make rats and all that easier to bash, then, yeah; at least make it so it's not **easier** to hit them with throwing weapons with 0 throwing skill, or with a gun with 0 gun skills. Otherwise it doesn't make sense. Not that this game is realistic or anything but still.

At least make is so all other types of attacks are as difficult to land on small creatures as trying to melee them.

**Comment by Coolthulhu** [comment]
It's less about small things and more about dodge formula being bonkers.

**Comment by aeoo** [comment]
>I mean, am I crazy in thinking it's silly for an unskilled character to not be able to hit a sewer rat at all without resorting to gimmicks?

You're not crazy.  This game is designed by a group of people and in that group there are one or two totally crazy people.  I won't name any names, but I bet they'll know who they are just by reading this.  For example, one of them said that if the day is cloudy enough, you cannot read any books in real life.  Obviously he's not from planet Earth.  And yet he's one of the people who designs this game.  So is it crazy?  Yes, it is.  Is it going to be fixed?  There is a 50/50 chance.  The devs fix some nonsense and leave other nonsense left standing.  It is from what I can tell 100% luck-based and isn't based on any kind of rigorous and formalized game design philosophy.  It depends more on if the dev had a good night's sleep or not, whether they had their coffee yet or not, etc.  Maybe they'll listen.  Maybe they won't.  So it makes sense to note the issue as you have done, but now that your issue is in the pipe, don't think they'll jump to it right away simply because what you're saying is common sense, lol. :)

BTW, your issue was indirectly already addressed when there was a discussion about the dodge formula being "threshholdy" (I think that's a direct quote).  I believe @Coolthulhu started the discussion and he's one of the core devs from what I know.  He's certainly one with the most passion for the game (and all around good sense) and if he's not a core dev, he damn well should be.

So is there a dev who *probably* agrees with you?  Yes.  Will this be fixed?  Who knows.

**Comment by aeoo** [comment]
@Lady-Luck 

Oh, one more thing.  I want to make a *suggestion* for you that I believe will improve your experience instantly, so that you don't have to wait for this to be fixed properly.

Unfortunately to follow my suggestion you'll have to set aside some degree of your pride.

During character creation choose "Freeform."  Then select your scenario and starting background.  Then leave all your starting stats at 8 (even though apparently you no longer have to do that with the STS, I still recommend it), then pick 12 points of negative traits and 12 points of positive traits, but avoid those negative traits which have been disabled.  Last I checked there will be 2 of them, and I'll get to that in a second.

Then when it comes to skills, gives yourself 3 points in dodge, melee and unarmed, and maybe 2-3 points in marksmanship/archery/throwing or not.  Then give yourself between 3 and 5 points in the following: construction, fabrication, cooking, electronics, first-aid, survival, tailoring.

Rationale:

1. 2-3 points in basic combat is so that you have a decent experience.  It won't enable you to tank a hulk, no, and it won't make you invincible or anything, but it will give you a basic level of competence in combat so that you don't start out worthless and you can proceed toward the fun part of the game, bypassing tedium of grinding and/or book reading.

2. 4-5 points construction, cooking, tailoring, etc. is because all those skills are easy to grind but annoying as hell.  Fabrication and survival are particular easy to grind and you can go from 0 to 3 on the first day!  But why should this 1st day be spent grinding?  What a waste of my time (and I believe yours too, which is why I am typing this).  Plus there isn't anything interesting going on when your skill level 1 or 0.  It doesn't add any flavor to the game.  There is no gameplay benefit of starting with cooking 0.  It doesn't make anything more fun, and presumably you play games to have fun?  I hope.  There are no interesting decisions to be had with cooking at 0 except: grind the hell out of it, because you need a lot of things that show up with cooking 3-4 or so.  Ditto most other skills.  The only option to grinding is to find a book, but thanks to "realism" reading a book takes takes literally about 1 minute of real time.  So you read a book and sit there twiddling your thumbs, staring at the screen, waiting for the game to simulate time progression.  It's beyond idiotic.  It's one thing to make game time pass, even 1 week of game time, but to force me, the player, to stare at an inactive screen waiting for the game to process something is nonsense.  There is absolutely no reason for it to be that slow.  But I digress.  Suffice it to say: the books are not much better than grinding at low levels, and reading the books is annoying as hell because you start reading it and stare into the screen for a loooooong while, just waiting.  There is no technical reason for it (no, it's not necessary to simulate every rat blow by blow while I am reading a book.  instead calculate encounter chance based on what's around me, and roll the dice once for that chance.  This is instant!).  One standout is electronics.  I am not sure if it's easy to grind electronics or not, but I take elec 4 because I want to start with the formulas for atomic gadgets, plus, electronics is #1 most important skill for installing bionics.  Again, you don't want to postpone your bionics longer than necessary, so it's good to start with 4-5 points in electronics, first aid and mechanics.  Mechanics is easy to grind from 2-3 onward, but from 0 to 2 it's nigh impossible.  Another reason to short-circuit crap game design with a smart chargen decision.

But you can't play yet!

Before you do anything, go into options and **turn off skill rust**.  It's under the debug menu.  Skill rust contributes nothing to the experience.  It's a poorly designed and 100% unrealistic feature, but I am willing to bet my thumbs that whoever put it in *thinks* it's realistic.  But it isn't.  Some of the most vocal pro-realism people are not familiar with reality at all, it's crazy, but true.  Often times "realism" means "hard/annoying for no reason."  It has actually next to nothing to do with realism most of the time but this is how they sell you those annoyances.  Calling unnecessarily and unrealistically hard game aspects "realistic" is just PR, nothing more.  It plays off people's misguided and uninformed feelings that the world is a brutal and unforgiving place.

Also to make my advice above work, you must remember 2 things when *creating the world*:

Make sure to select "More Survival Tools" mod, because it solves a lot of the early pain paints in the game.

Make sure to select "Stats Through Skills" mod.  It's essential.  These two mods are mandatory, if you ask me.  Everything else is take it or leave it.

I highly recommend turning off **fungal monsters** too.  They add nothing to the game, but only make you hunt for more drugs for no good reason.  It's stupid.

Also the option "mutate by radiation" (might not be the exact name) should be set to off.  I'd turn off all mutations if I could, since they add nothing to the game.  But the only thing I know how to turn off is mutation from radiation.  Apparently some monsters can still mutate your character and there is nothing you can do unless you have end-game gear with strong environmental protections, which is absurd in so many ways.  If you get mutated in the early, don't feel bad to use the wizard mode to simply turn them off.

Also season length 14 is too short.  I recommend season length 30.

So, if you follow all this advice, you'll end up with a fun game almost no matter what.  All the worst aspects of the game will be bypassed by starting in this way and you'll proceed straight toward the fun part.  Mind you, this doesn't make you invincible!!  You'll still die.  But when you die using my recommended start, you'll probably think it was your fault and not game's fault and you can begin carefully plundering the cities right away instead of grinding in the forests before approaching the city.

Also, starting this way gives you a character, roughly, with str:9-10, dex:10-11, int:10-11, per:9, which is a surprisingly modest lay out of stats, which in some cases only differs from the default scenario by as few as 1 point!  Because with the default start you can have 10, 10, 10, 8, and in many cases starting as I recommend gives you 10, 10, 10, 9, or 10, 10, 11, 9.  So just because you splurge on the starting skills because of the STS' design you don't in fact get an insane amount of starting stats.  So in many ways this is actually a more modest way to start than say the old Really Bad Day start!

Summary: CDDA is a mix of brilliance and insanity.  It has many awesome decisions and some truly bad ones, but you can mitigate the worst aspects of the game if you know how to use all its starting options well.

**Comment by Lady-Luck** [comment]
Oh, I already play freeform, because I felt like it was better than trying to finagle points out of the drawback system by taking a bunch of minor stuff that doesn't really matter.

I honestly feel like the current trait system is very flawed and should be scrapped in favor of something that offers double-edged sword traits, rather than getting to cherrypick. For instance, an Agile trait, which makes you faster but also more fragile.

**Comment by aeoo** [comment]
>Oh, I already play freeform, because I felt like it was better than trying to finagle points out of the drawback system by taking a bunch of minor stuff that doesn't really matter

By the way, I start as I describe, but I still miss some rats and other small critters regularly.  So don't think because you start with 3 in melee you'll hit every rat!  I often have to hold the attack button for like 1 minute to get it to connect, but at least once 3 becomes 4 you'll be hitting rats almost every time or so... so the problem is much less severe that way.

>I honestly feel like the current trait system is very flawed and should be scrapped in favor of something that offers double-edged sword traits, rather than getting to cherrypick.

I don't agree.  There is no need to force people to endure negative traits.  This isn't masochism.  It's a game!  Remind yourself: it's a game.  It's not punishment for having been bad in a previous life, lol.  There is no reason to force people to play with even 1 negative trait.  It should always be a choice.

**Comment by mugling** [comment]
> It's less about small things and more about dodge formula being bonkers.

What is the status of your recent PR on this?

**Comment by Coolthulhu** [comment]
Didn't PR it yet, will try soon.

**Comment by Lady-Luck** [comment]
>Didn't PR it yet, will try soon.

Please do!

**Comment by DangerNoodle** [comment]
I suspect that if an animal is actively attacking you, it should logically be easier to hit, unless it is given the hit and run flag. At least, for animals and other creatures that are relying on small size and speed to avoid being hit.

**Comment by Griffinhart** [comment]
So, where DND has Cats vs. Commoners, CDDA has Rats vs. Survivors, huh?

**Comment by Lady-Luck** [comment]
@Coolthulhu Any progress? Any time I run into a rat and have to kill it by throwing things at it I think of you. :p

**Comment by Coolthulhu** [comment]
Here's a draft: #18351

I would be a bad rat, rats aren't poisonous. You should think of me when looking at an angry wasp decimating a horde due to unbalanced hit chances.

**Comment by pisskop** [comment]
Slings work well for even the most unskilled.

**Comment by DangerNoodle** [comment]
> 

Here's a draft: #18351

> I would be a bad rat, rats aren't poisonous. You should think of me when looking at an angry wasp decimating a horde due to unbalanced hit chances.

Weren't normal vermin wasps unkillable hostiles when they were first added?

**Comment by Treah** [comment]
This becomes more apparent if you are super unlucky and come across a skeletal dog... They are crazy fast and damn near unhittable unless you have good skill in melee. I had a decent char with good gun skills die to one without landing a single blow (yes im aware guns dont do much for skeletal beings). I guess the flipside to that is they can't bash through windows. If your in the open tho your pretty screwed.

**Comment by Zilenan91** [comment]
skeletons aren't that dodgy, their niche is bullet dodging due to the bullets going through their bones. If you have 1 or 2 melee skill you can hit them pretty reliably right now even with not-so-great weapons.

**Comment by DangerNoodle** [comment]
I recall the problem generally is not skeletons, but skeletal dogs. Not sure if they have much in the way of dodging skill, but they do have their small size.

**Comment by Zilenan91** [comment]
that's just dogs in general. They're very difficult early on due to their dodginess but once you have melee skills that aren't zero you do fine against them. Most dogs are flat out worse than basic zombies past that point.

**Comment by DangerNoodle** [comment]
Makes sense. It might be more the small size dogs have in common plus their resistance of bullets, making them vulnerable only if you have a minimum of melee skill or a shotgun.

**Comment by latogato** [comment]
I glad it get a fix, it was a problem for a long time. I always threw my objects at small targets because of their impossible-to-hit dodge levels. Which is really unrealistic (and very irritating) because no healthy human ever lost a fight and get killed by a rat IRL. :)

**Comment by Coolthulhu** [comment]
The dodge formula got a big rework, closing.

**Comment by latogato** [comment]
Thank you! Time to visit that pesky cellar spiders again...

**Comment by pisskop** [comment]
its still more tha. possible to miss high Dodge cellar spiders with low skill.  id pack a small pistol for them

**Comment by DangerNoodle** [comment]
I recently cleared a cellar spider basement while playing as a samurai, from the Medieval and Historic Content mod. At that point I still had the same melee skills the profession starts with (1 cutting and 2 melee).

Multiple hits were sustained, and it took repeated attempts to score hits on them. However, part of it may have been due to the 25 torso encumbrance of an o-yoroi plus backpack. However, due to the armor almost no damage was taken, aside from being repeatedly envenomed.
