### ISSUE TITLE
"NULL weather" bug  (exp 5501)

### ISSUE THREAD

**Issue by busterbogheart** [CleverRaven/Cataclysm-DDA#18406]
Started a new world with a new character and the first frame showed an error shown in the screenshot.  Options for world were 7 o clock start, in autumn, 60 day seasons, and eternal seasons false.

Let me know if you need more info.  :cake: 

![2016-09-18 12_25_54-cataclysm_ dark days ahead - 0 c-18352-g6766898](https://cloud.githubusercontent.com/assets/19196781/18617369/cee6457c-7d9b-11e6-8233-76db0b2b1609.jpg)

**Comment by busterbogheart** [comment]
I waited for dawn but dawn never came.  :sun_with_face: :disappointed:   Never could see more than one square away even though the sundial UI area showed sunshine eventually.  What is this, the end of the world?

**Comment by Coolthulhu** [comment]
The fix is already merged, but the build system is broken - #18388

When the build system is fixed, the new game build with the fix should be available.
Until then you can do this:
* Bind debug menu in keybind options
* Open debug menu in game
* Select weather options ('h' bind, I think)
* "Stop weather forcing"

This has to be done every game load for the bugged versions.

**Comment by busterbogheart** [comment]
Ok gotcha.  Should i continue to bug newer experimental builds?
