### ISSUE TITLE
Survivors with the "Thick Tail" mutation are unable to put on the Winter Survival Suit

### ISSUE THREAD

**Issue by Zilenan91** [CleverRaven/Cataclysm-DDA#18416]
Lizard-mutation survivors can already wear the medium survivor suit so it seems a bit strange that they can't make the jump to fur clothing.

**Comment by mightyagrippa** [comment]
This is due to the materials of the winter survivor suit, fur and kevlar. Tail mutations restrict you to leg armor that has at least one material with "soft" : true. At the moment the only soft materials are cotton, leather, wool, and nomex. This goes for a lot of other mutations; no winter survivor hood with antennae, etc. 

It might be a good change to make fur soft.
