### ISSUE TITLE
Construction and z levels.

### ISSUE THREAD

**Issue by mdtrooper** [CleverRaven/Cataclysm-DDA#18444]
I have been thinking and testing some code (at the moment only json sorry) about the contruction and z levels.

It is a very difficult thing, because there are a lot of code to change.

But I have wrote this part of json for contruction a Upstairs, yes I know it is few code and json:

```
{
        "type" : "construction",
         "description" : "Build Upstair and floor in the next level",
         "category" : "CONSTRUCT",
         "difficulty" : 4,
         "time" : 180,
         "qualities": [ [
                { "id": "SMOOTH", "level": 1 }
         ] ],
         "components" : [
                [ [ "concrete", 4] ],
                [ [ "2x4", 12] ],
                [ [ "water", 4], [ "water_clean", 4] ]
         ],
         "pre_terrain" : [
                [ { "id": "t_floor", "level_terrain": 0 } ],
                [ { "id": "t_open_air", "level_terrain": 1 } ]
         ],
         "post_terrain" : [
                [ { "id": "t_stairs_up", "level_terrain": 0 } ],
                [ { "id": "t_floor", "level_terrain": 1 } ]
         ]
    }
```

I think that one a solution is change pre_terrain and post_terrain for a array of hashes, and each hash it is the id of terrain and the level (values can be -1, -2, 0, 1 or others). And the level 0 is the actual level of character.

What do you think?

**Comment by Coolthulhu** [comment]
Not a bad idea, but I'd rather see it done like in Dwarf Fortress - that walls seen from above look like floors.

**Comment by mdtrooper** [comment]
@Coolthulhu Yes, it sounds good, for example the player runs on top of the edge (I don't know it is correct in english) of wall like parkour. Or to create a monorail. Because somebody have said trains in CDDA ;) .

But, now the z system is such as "layered system". Do you think that it is good spend hours in coding with actual system?

**Comment by Coolthulhu** [comment]
Writing a partial solution wouldn't help here, it would only allow json-coded layered terrain placement.
It would be easier to extend the roof implementation to add roof terrain above newly placed tiles.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
