### ISSUE TITLE
Mod for forcing "modern" recipes to be book-learned only

### ISSUE THREAD

**Issue by DangerNoodle** [CleverRaven/Cataclysm-DDA#18457]
This is an idea for a mod that, at present, might be unfeasible to implement, but with the right additions it would be possible.

The main component would be recipe edits changing various recipes to booklearn-only, based on assumptions involving how modern is too modern. Specific tool demands like welding, firearm repair kits, soldering irons, etc would be obvious hints for excluding some recipes, but other cases might be borderline. Where books are not already specified, they would have to be added.

If recipe mods can use the modify ability, it would sharply reduce mod maintenance and reduce the file size. If not, it would rapidly become a nightmare to keep current.

The second requirement would be a world setting enabled by the mod, as some mods enable. This setting would disable the feature that allows characters to start with book-only recipes depending on their skills. This would ensure that the effect is not cancelled out.

Ideally this would be intended for a deliberate challenge, or as a roleplaying feature used while playing a churl (vanilla), prehistoric hunter (MST), the Medieval Mod professions, or the Classic Roguelike Classes.

I do not not how easy it would be to implement the second prerequisite, hence why I am suggesting the idea rather than attempting it myself. Additionally, it would be desirable to see if others can devise effective ways to satisfy that prerequisite without source changes.

**Comment by aeoo** [comment]
The flip side of this would be to allow natural learning of all the survival recipes.

Personally I don't think "modern" implies "so tricky you need a book for it."  For example, a soldering iron is a simple modern tool that anyone with high school physics should be able to figure out after getting a few of them wrong.  A battery, again, a modern tool, and yet its design is so simple that the kids are forced to make potato batteries in school in order to teach them the concept.

On the other hand, just becomes something is survivalist it doesn't mean it's obvious, at least to modern people.  So it makes sense to be able to learn some modern recipes without a book and yet to still need a book for some survivalist recipes.

The devil will be in the details.  It would taking going through each recipe individually and deciding if it's easy to figure out or not.  "If it's modern, it belongs in a book" is what's known as a heuristic.  Heuristics are lazy ways of thinking (or if you want to be charitable, they're mental shortcuts) that replace genuine consideration with a simple one size fits all rule.  We need heuristics to program computers, cause computers only respond to simple rules (duh), but heuristics hurt humans when humans use them.

**Comment by DangerNoodle** [comment]
Filtering based on modernity might be an awkward method, yes. Granted, things like putting plates in an MBR vest, or tying rags to a flashlight, would presumably acceptable. The items are modern, but what you are doing with them would be plausible for a non-modern character to be able to figure out.

**Comment by aeoo** [comment]
>Granted, things like putting plates in an MBR vest, or tying rags to a flashlight, would presumably acceptable.

I agree.

Cloth is kind of high tech the way we do it too.  I mean, who in the world spins their own yarn.  We have machines that spin such thin and consistent thread that I imagine you just can't spin it like that by hand.

But a potato/vegetable peeler is also a modern invention.  And yet all it is, is a curved metal stick with a slit in the middle, which is a brutally simple design.

I think 90% of complexity in the modern stuff is because of the materials science.  A crappy battery is easy.  The hard part is figuring out some arcane materials that make it very efficient and safe to use.  To be honest, we're still working on the "safe to use" part even now!  Isn't that funny?  Similarly a pipe is relatively easy (especially a short one), but making a pipe ultra-straight to a high degree of tolerance and making it have an even/smooth heat expansion profile, that might be hard.

Similarly measuring length to +/- 1 centimeter or roughly half an inch, that's easy.  But measuring it up to a micron is hard.  So even an easy concept can be hard to make.  But, a lot of this problem I think isn't something that's solvable with a book anyway.  I mean, do you think I can make a device that measures +/- 1 micron tolerance if only I had a book right now?  I don't think it's that simple.

I think you have a decent idea, but I would rename your mod to:

>Mod for forcing "~~modern~~difficult" recipes to be book-learned only 

And unfortunately once go that route, there might not be an easy way to filter recipes.  It would take a lot of effort to go through every recipe, and there are so many of them, and decide if it's hard or not.  Once that's done, you may have to do it again later, to keep your mod up to date.

Unless you can get everyone to agree to use a "needs-book" flag in a consistent way... but then why would that be a mod?  If you could get everyone to agree to this policy, then wouldn't that already be mainline?  The reason you're contemplating a mod is, presumably, not everyone can agree on what's hard enough to require a book.  Once that happens, imagine how much maintenance your mod would need.  It would be far from a fire-and-forget kind of mod, imo.

**Comment by DangerNoodle** [comment]
True. The details of what should and should not be in the game quickly make this idea impractical to implement, whether as a mod or mainline. I suspect that others surely have developed similar mod ideas for private use, but those would not have the main stumbling block that an official mod would have. These players would have presumably had their own concrete idea of what recipes are and are not plausible to preclude from autolearning.

The other reason I brought the suggestion up is due to the "autolearn book recipes based on skill" feature being another stumbling block for this idea. This idea may well only be possible to implement as a homebrew mod due to differing ideas on what needs to be shifted to book learning, but only an official mod would be able to obtain the desired source changes that would facilitate it.

**Comment by aeoo** [comment]
One way, possibly, to side-step some of the issues, is to make a very modest claim with your mod, so as to set a very low expectation.  Imagine if you waited for 0.D to materialize and then you claimed in your mod that it's *only* expected to work with 0.D, period.  I don't know if that's possible.  But the idea is, you're only promising that you reviewed all the recipes at the time 0.D was released and you make no promises for anything that comes after 0.D.  Maybe that's one way to limit the scope.

Otherwise you might want to consider essentially being married to your mod so to speak, and just keeping it up to date as a hobby. :)  It might be worth it if you think the mod dev process is fun and/or you believe the gameplay value is very high.

**Comment by illi-kun** [comment]
Why we're talking about this as a mod? Complex recipes should be in books, easy recipes should be autolearnt, and this statement is applicable to mainline. Am I miss something?

**Comment by DangerNoodle** [comment]
I am not sure how well I could upkeep such a mod, especially as I might end up focused on another mod that will become subject to this issue of time.

**Comment by DangerNoodle** [comment]
Closing for now, as in practice this mod idea would not be feasible to implement as an official mod. Everyone would have different ideas on where to set the reasoning behind recipe changes, as well as differing desires for what gameplay and roleplay purpose it serves.
