### ISSUE TITLE
Gas tanks shouldn't explode without a source of open flame

### ISSUE THREAD

**Issue by jedibob5** [CleverRaven/Cataclysm-DDA#18464]
It's actually more difficult to get a gas tank to explode than one would think - the Mythbusters tried it once several years ago, and repeated gunfire couldn't even get it to light. They were able to get a small fire to ignite after shooting it with tracer rounds (which have a small pyrotechnic charge that burns mid-flight to allow the shooter to see the trajectory), but even then it wasn't a Hollywood-style explosion.

There's certainly no way a zombie attack should be able to do it, unless all the zombies' hands are perpetually on fire and I didn't realize it.

**Comment by Beanzy** [comment]
However unrealistic, changing this would have gameplay impacts (not necessarily for the better).

For example, if gas tanks explode, a mob of zombies attacking a car can be a significant challenge for the player. If the player does nothing, the car may explode and attract more zombies or burn valuable loot.

In other words, besides realism for realism's sake, what gameplay effects does this change have? How would eliminating vehicle explosions make Cataclysm a better game?

**Comment by Coolthulhu** [comment]
> How would eliminating vehicle explosions make Cataclysm a better game?

By removing a part of that scummy reality bubble manipulation where you try to have the least number of cars around to avoid them getting destroyed.

**Comment by jedibob5** [comment]
Well, it killed my second-most successful character ever when I had made the reasonable assumption that CDDA's aim for realistic physics where possible extended to zombies punching gas tanks.

Besides, the devs have made a point that realistic gameplay is important to CDDA - if realism is important enough to track individual vitamin intake levels, why shouldn't gas tanks behave realistically when struck?

**Comment by Beanzy** [comment]
Vitamin levels have a gameplay aspect though, it makes players search for a wider variety of food, instead of just stocking up on meat.

Having gas tanks explode provides an impetus to engage the zombies attacking the vehicle, it presents a dilemma to the player. Removing it removes the challenge of making that decision.

Really, most gas tanks in C:DDA are located on the outermost part of the vehicle, just moving them more towards the center of most vehicles would also reduce explosions.

**Comment by Rizoel95** [comment]
Perhaps we should make it so only certain things makes gas tanks explode. Maybe only shooting it should make them explode, or just incendiary rounds.

Still unrealistic, but hey.

**Comment by Rivet-the-Zombie** [comment]
>Really, most gas tanks in C:DDA are located on the outermost part of the vehicle, just moving them more towards the center of most vehicles would also reduce explosions.

It would also make a lot of sense realism-wise; gas tanks are typically located underneath the vehicle, closer to the center line of the vehicle, not inside one of the quarter panels.

**Comment by latogato** [comment]
Gas tank explosion makes the game more fun. Rarely a problem in the game, but makes fun moments when zombies blows themself up, also an explosion alerts you. If you in a car, just be a little careful or move your gas tank inward. 

I had some accidents with gas tank in the game, but it really just made the game more challenging. Maybe the explosion damage could be less to make it less deadly to the unlucky survivors.

**Comment by Beanzy** [comment]
If the game modeled the spread of liquids across the ground and the vaporization of gasoline I don't think this change would be remiss.

Because while IRL gas tanks don't really explode, a pool of evaporating gasoline _from a ruptured gas tank_ presents a great risk of starting a huge conflagration from an errant spark or flame.

My issue is that we're just trading one form of unrealism for another, more subtle, unrealistic mechanic that also takes away from gameplay.

**Comment by jedibob5** [comment]
> Removing it removes the challenge of making that decision.

So realism only matters when it makes the game harder? You can justify a lot of objectively terrible design choices with that approach. Why not make all zombie attacks explosive, regardless of what they're hitting? It's not realistic, but it presents more challenge to the player, right?

Look, I understand that the difficulty of Cataclysm is a huge part of its appeal - It's still a challenge to me that I have yet to consistently conquer, and that's part of why I love it. However, it feels cheap as hell to get killed by assuming that a system in the game (particularly one that isn't influenced by the futuristic/supernatural aspects of CDDA's setting) will behave realistically.

**Comment by flitvious** [comment]
Some time ago diesel fuel was made into a less explosive alternative to gasoline. 

As for spontaneous explosions, I like to imagine poor zombies wrecking a car, gasoline pouring from the damaged tank, soaking everything, including zeds. Then some spark from the car electronics starting the fireworks. Just like in the movies. 

If spontaneous boom-booms will be removed, there must be a way to explode a car. Throwing matches at the leaking gasoline or something.

**Comment by Zilenan91** [comment]
Car exploding would be a nice thing to have but them just randomly exploding and instakilling players should not happen. I had something like that happen to me where the gas tank I placed on the inside of my car was damaged due to me hitting a wall and it exploded and burned away most of my stored items and nearly killed me. There luckily weren't many zombies around and if there were that would've been an insanely shitty way to lose a late-game character.

**Comment by Beanzy** [comment]
I think a good model would be:

1) Zombies bash up car, and eventually rupture the gas tank. Pouring gas everywhere.

2) One of the zeds eventually causes a spark that ignites the gas on the ground, causing a decent sized fire.

3) This fire eventually brings the remaining contents of the gas tank to a boil.

4) ka-boom

If this entire process averaged out to being like 10-15 mins, it would add some good tension and allow the player to get the hell out of dodge.

So instead of gas tanks spontaneously exploding, gas on the ground nearby should ideally have a chance of igniting if zeds are tearing up a car right above it.

This would be both more realistic, and less random death inducing than what C:DDA currently has.

**Comment by DangerNoodle** [comment]
I can see one possible idea for a dynamic occurring. A nearly-empty tank would plausibly have a better fuel-air ratio and thus be more likely to reach that point of exploding. But a tank with more fuel available overall would have more fuel going up in the event that it gets to the point of a violent reaction.

**Comment by schmithub** [comment]
There's nothing realistic about cars blowing up so easily.  Some of you people watch too many movies.

**Comment by latogato** [comment]
Yes, in movies cars blows up easily. Also there are zombies. I see no problem with any of it.

**Comment by Treah** [comment]
I

>  think a good model would be:
> 
>  1) Zombies bash up car, and eventually rupture the gas tank. Pouring gas everywhere.
> 
>  2) One of the zeds eventually causes a spark that ignites the gas on the ground, causing a decent sized fire.
> 
>  3) This fire eventually brings the remaining contents of the gas tank to a boil.
> 
>  4) ka-boom
> 
>  If this entire process averaged out to being like 10-15 mins, it would add some good tension and allow         the player to get the hell out of dodge.
> 
> So instead of gas tanks spontaneously exploding, gas on the ground nearby should ideally have a chance of igniting if zeds are tearing up a car right above it.
> 
> This would be both more realistic, and less random death inducing than what C:DDA currently has.
> 
> 

It already takes a few turns for the zombies to get to the tank and cause an explosion. There is nothing AFAIK in the game that is considered "gaseous" so none of the fuel right now evaporates into a gaseous state. I recently was looking around the json files trying to see if there was another state other than liquid when trying to put together a new mod.

**Comment by Beanzy** [comment]
> There is nothing AFAIK in the game that is considered "gaseous"

I wonder if the way smoke works could be leveraged to do this? Maybe make uncontained gasoline emit an invisible, flammable  "smoke" to emulate gas vapors.

**Comment by kevingranade** [comment]
I agree the current behavior is shorthand for, "tank pierced, gas leaking, fumes igniting", and doing that stuff explicitly would be an improvement.

The simplest thing IMO would be for fuel puddles to produce "fuel vapor" fields above them, and perhaps add a system where gasoline can spread across hard surfaces.
These vapor fields wouldn't cause fires directly, but if above somethiblng else that's very flammable coukd cause e.g. a spark to trigger a small fire.

**Comment by Leland** [comment]
No movement in nearing a full year – closing. If there's still an interest in discussion/development, please ping me to reopen!
