### ISSUE TITLE
Basic Wolf just crushed a building?

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#18528]
Fresh start

I smashed a window with a rock for the string, a wolf pack was outside.  One chased me through the window and crushed the starting shelter, it's now entirely full of rubble.

![cdda wolf shelter collapse](https://cloud.githubusercontent.com/assets/12039454/18817366/4d96898c-8313-11e6-9986-3bbe5c2554ab.png)

**Comment by pisskop** [comment]
???

that sounds unreasonable.  wolves dont bash at all.  in any mod or the base game.  though structures have always been finicky about their supports.

something damaged the wall (or, more likely, the window), and it turned into rubble.  you shoot it?  smash it?

**Comment by Xpyder** [comment]
I smashed both windows twice as always, to clear them.  I usually board them back up later with the benches if I live that long.

How does the starting shelter determine it's supporting blocks?

**Comment by pisskop** [comment]
You may be misunderstanding me a little.

Every time a structure is destroyed, a new one may spawn, items may spawn, and/or support checks are made.

    When you smash a window, you are making an (incredibly low) strength check to destroy that window.  It will loose its items and turn into a window with glass shards.
    When you smash that, it becomes an empty window, and looses another glass shard.
    When you smash that, you risk the window being destroyed and loosing its rock/nail/2x4 making.  This is where the support is kaput.

It doesnt matter if a hulk smashed the window or a butterfly.  If the window is hit 1 time it degrades into a glass shard window.

Multiple hits, say from an automatic gun, can degrade it multiple times, but a single hit can only do so 1 step at a time.

thus, you broke down the window to its base, weakest state.  which is fine, its common practice.  no issue there.

 but, with the nerfing of windows to prevent cheese (some time ago now), the windows are pretty weak and will crumple under a small hordes assaults.  or ever a guy with a rifle smashing at it.  So, any bullet or attack made against it could have broken the window frame.

the support and gravity and ceiling mechanics of the game.... leave a lot to be desired at the moment.  Like picture dwarf fortress, and then cry because its nowhere near as good as even old 2d df support and gravity mechs.

the loss of that single support tile was enough to collapse the vast majority of the ceiling.  if gas tanks Hollywood up when a zombie smashes them, the ceiling hollywoods down when a zombie smashes a window.

**Comment by 2birdie** [comment]
http://img1.wikia.nocookie.net/__cb20130207024637/metalgear/images/1/13/Character_02bladewolf.png

Maybe it was an infected wolf? I'm not sure if they are capable of bashing.

**Comment by Oskar636** [comment]
This is intended behaviour, at least with the current code, like @pisskop said. Whether it is a bug or not I don't know.
