### ISSUE TITLE
Suggestion: Allow glasses and cups to hold liquid.

### ISSUE THREAD

**Issue by 2birdie** [CleverRaven/Cataclysm-DDA#18569]
Glasses, ceramic bowls and cups cannot hold liquid. Hot tea can never know the embrace of a proper cup. Glasses, begging for a frosty one will never receive their desired frosty one.

**Comment by Reclusive-reptile** [comment]
For shame!

**Comment by Xpyder** [comment]
This is something that comes up once in a while.

The short version is that you can only store liquids in containers that are resealable and waterproof.  The reason for this is the game can't tell if you're transporting the liquid or not.  Since there's a direct consume action now (Unload > consume) the only thing being able to put a liquid in a container gets you is long term storage and portability.

You're welcome to carry around a teacup that you inscribe a phrase on, to RP a momento or something, and there's a case to be made to adding Boiling 1 to glass cups, or being able to make lids.  But beyond that there's not much of a case for trying to store liquids in cups long term, unless the engine gets modified to allow spilling and movement/balance penalties for moving with an opened container of liquid, which would be fiddly, and cpu costly without much real gain.

**Comment by Rivet-the-Zombie** [comment]
>The short version is that you can only store liquids in containers that are resealable and waterproof.

This is no longer the case, as you can store liquids in stuff like opened cans which can only be carried around in the 'hands' slot once they've been filled.

**Comment by Xpyder** [comment]
huh, never messed with that.  If so then yes that same functionality should be added to similar items.

Do you feel like posting an actual item list?  You could probably dig into the items.json to find them, or use the wish (debug) menu to peruse them.

**Comment by MisterFox** [comment]
I had a look around and I think I have a partial list of some items that should be able to hold water but currently can't:

* Plastic cup (cup_plastic) -- The 'opened' version of this (cup_plastic_unsealed) can actually hold water, but there's no way (as far as I can tell) to actually open this.
* Ceramic cup (ceramic_cup)
* Glass bowl (glass_bowl)
* Pewter bowl (bowl_pewter) -- May be from More Survival Tools mod
* Glass (glass)
