### ISSUE TITLE
Not all lake edges smooth into shallow water

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#18583]
Part of the river spawned isolated with only one half of the tiles
It's about even with the lower bend, just to the right of the forest.

![image](https://cloud.githubusercontent.com/assets/12039454/18975549/bcc23bd6-865f-11e6-99b3-c2900c27ed8f.png)

**Comment by Mecares** [comment]
Looks like a oxbow lake a natural result of meandering rivers.

**Comment by Xpyder** [comment]
If it was intentional then it would have shallow tiles all around it, it wouldn't go from deep to land.

Also I thought lake tiles had their own notation, or is that only ponds?

**Comment by vache** [comment]
If I recall correctly, it is actually an overmap special that makes these.  They're supposed to be something like ponds, but the generation doesn't usually place enough tiles, and the river smoothing algorithm doesn't know how to handle them so they often end up looking disjointed and awkward.

**Comment by Xpyder** [comment]
could be.  It looks almost like it and the forest were placed, then overwritten by something else, but the river's on the other side so either way there's a bug somewhere.

**Comment by vache** [comment]
It's not supposed to be connected to the main river:
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/overmap_specials.json#L14

It's supposed to generate as a blob of "river" to simulate a lake, but the blob shape is too sparse and it doesn't generate as "connected" as it should be for the smoothing to take effect.

**Comment by Leland** [comment]
Alright so just to recap – this issue is about lakes, which use river tiles and spawn without a connecting river.

The game's river "smoothing" applies to deep water and introduces shallow water on the edges. You'd expect it on lakes as well, but, like @vache said, the lakes' river tiles are too small and too far apart to get smoothing applied.

IMO, I think the issue is really two-fold:

1. The edges aren't shallow, like mentioned, and
2. The tiles for rivers and lakes are _exactly the same_.

I don't think very many people, including myself, knew that these were supposed to be lakes. They just look like mapgen screwed up the placement of rivers.

**Comment by kevingranade** [comment]
Also still water and flowing water can be expected to have different
properties (freshness, swim difficulty, population of animals)

**Comment by Leland** [comment]
#21833 encountered this issue (as well as some oddness in the shape of the lake)

<img src="https://user-images.githubusercontent.com/11132525/30247194-fde55004-9616-11e7-8972-b0b628361c3c.PNG" height="200px"> <img src="https://user-images.githubusercontent.com/11132525/30247196-00729412-9617-11e7-8f7c-ec552ac4a557.PNG" height="200px">

**Comment by ralreegorganon** [comment]
As of #30442 these lakes that were created by dropping a few river tiles on the map no longer exist and have been superseded by dedicated lake mapgen.
