### ISSUE TITLE
Rivtech magazines are poorly differentiated from each other

### ISSUE THREAD

**Issue by John-Candlebury** [CleverRaven/Cataclysm-DDA#18612]
Since the name of the magazines are model numbers, it can be difficult to differentiate between the magazines, especially if you are carrying different kinds of rivtech guns. 

Its nothing memorization cant fix, but it'll probably be better if you could tell the difference at a glance.

**Comment by Rivet-the-Zombie** [comment]
I've not been able to come up with a much better nomenclature for them, since they're shared between different guns of varying types. The names do differentiate them by what they do, if you decode them:

RMGB100 - **R**ivtech **M**agazine **G**eneral (8x40mm) **B**ox capacity **100**
RMGD250 - **R**ivtech **M**agazine **G**eneral (8x40mm) **D**rum capacity **250**
RMGP25 - **R**ivtech **M**agazine **G**eneral (8x40mm) **P**istol capacity **25**
RMSA10 - **R**ivtech **M**agazine **S**hotgun (20x66mm) **A**uxiliary capacity **10**
RMFB50 - **R**ivtech **M**agazine **F**lechette 5x50mm) **B**ox capacity **50**

That being said, I'd be happy to hear suggestions for better names.

**Comment by John-Candlebury** [comment]
I think that adding a suffix to the description them could go a long way to fixing the issue, even if it is a bit redundant. For example:

RMGB100 could become: RMGB100 magazine
RMGD250  could become: RMGD250 drum magazine
RMGP25 - could become: RMGP25 pistol magazine
RMFB50 - could become: RMFB50 5x50mm magazine.
And so on.

Simmilar to how the names of the extant rivtech firearms.

**Comment by Rivet-the-Zombie** [comment]
Sounds good to me.
