### ISSUE TITLE
short ropes cannot be disassembled.

### ISSUE THREAD

**Issue by Shudokai** [CleverRaven/Cataclysm-DDA#18632]
For a while now short ropes give the message "The item might be gone, at least it is not at the expected position anymore" when you try to disassemble them.

Quite the annoying bug when you use seatbelts as a source of thread.

**Comment by mugling** [comment]
By any chance are you dropping the item during disassembly. Try wielding it

**Comment by Shudokai** [comment]
I always disassemble stuff thats lieing on the floor.

**Comment by joeshipley** [comment]
Same in my game. Whether it's in inventory or it's on the floor, short ropes can't be disassembled.

**Comment by DangerNoodle** [comment]
Confirming, I have tried it dropped, in inventory, and wielded. None work.

**Comment by rsofaer** [comment]
I looked at this in the debugger for a minute:
When you try to disassemble a short rope, it tries to get the recipe from recipe_dictionary::get_uncraft with the key "rope_6_from_string", which returns what looks like a null-filled recipe.  To contrast, recipe_dictionary::get_uncraft("rope_6") gives the recipe.
This problem seems to be specific to reversible recipes that have the id_suffix attribute.  Another one that I found is "armor_lightplate", which tries to get the recipe for "armor_lightplate_assembly".  I guess not that many people are out there disassembling suits of plate armor.
