### ISSUE TITLE
Snare Kits Recipes cannot be learned.

### ISSUE THREAD

**Issue by Shudokai** [CleverRaven/Cataclysm-DDA#18638]
The light snare kit and the heavy snare kit recipes cannot be learned. The wiki says both recipes are aquired once the skill requirements are met, estilofusion says they are not auto-learn but there is no books to teach you the recipes and disassembly doesn't teach you how to make them aswell.

Are they supposed to be uncraftable?

**Comment by DangerNoodle** [comment]
If I recall, the wiki is outdated and likely reflects an older version.

They were dummied out for reasons I am unaware of, then re-implemented in More Survival Tools once Chaosvolt determined there were no peculiar consequences in doing so.

**Comment by BorkBorkGoesTheCode** [comment]
Can confirm, They are missing "autolearn": true and a list of books that contain the recipe.

**Comment by Xpyder** [comment]
They are disabled because they're broken.

Originally they were intended to be used to help catch game, but no way to lure with them was ever implemented.

There has occasionally been some discussion about changing them to work like fish traps for woodland creatures, or to rework trapping completely.  In the meantime someone should add a comment to the item in the JSON to make it clear that they're intentionally disabled and why.

**Comment by DangerNoodle** [comment]
I thought they were mod-shifted though. Or was that reversed?

**Comment by Xpyder** [comment]
I don't know what you mean by mod-shifted.  They still live in the default jsons below

data/json/traps.json 
data/json/items/tools.json

**Comment by illi-kun** [comment]
>  someone should add a comment to the item in the JSON to make it clear that they're intentionally disabled and why.

No, either they should be removed or fixed.

**Comment by DangerNoodle** [comment]
> I don't know what you mean by mod-shifted.

I mean the recipes to craft them were implemented in More Survival Tools.

**Comment by mugling** [comment]
> No, either they should be removed or fixed.

How long has it been broken for? If its months and theres nobody about to fix it then it's hard not to justify removal

**Comment by Xpyder** [comment]
Years I believe.

**Comment by DangerNoodle** [comment]
From what I know, the issue is not functionality but balancing. But all traps are subject to the same problem, animals will not be lured into them. As far as I am aware of, they do at least work when triggered.

Why are snares the only trap subject to this discussion? We have bubble wrap traps, trip wires, and other even less useful traps that should be subject to the same questioning of whether the player would ever use them.

**Comment by Xpyder** [comment]
@illi-kun 
Your comment is an oversimplification.  you can't just "fix" them.  To have them work as intended AI for woodland creatures would need to be heavily modified to create game trails, and common feeding, watering, sleeping, and territorial behaviours, along with a tracking system.

some have proposed an interim fix using a bait and lure system, but there are separate issues with that and again that comes down to AI modifications, not some trivial fix, which is why it's persisted in this state for so long.

If we remove them entirely, they we should look at completely removing the trapping stat as it's essentially useless.  The only other thing it gives access to bear traps, disarming mines can easily be rolled into mechanics or some other skill.

**Comment by illi-kun** [comment]
@Xpyder yes, that was intentional simplification. We should not store disabled stuff in core just in case it will be used later. If this trap used in mod it should be moved to mod, if it's disabled it should be removed. Item can be restored if some implements

> territorial behaviours, along with a tracking system.

It's the same logic we're applying to dead code: remove it, not comment it out.

**Comment by DangerNoodle** [comment]
I assume it was not moved fully to the mod due to the risk of breaking save compatibility, but that should be less of a factor depending on how long ago the snare items were dummied out from mainline.

**Comment by Xpyder** [comment]
Fair enough, I'm definitely for cleaning up the code

**Comment by DangerNoodle** [comment]
If the item is removed in full, just remember to remove the recipes in the mod it is still used in.

**Comment by DangerNoodle** [comment]
I belatedly realized something. We now have the ability for monsters to have pathfinding. If this ability can be added to wildlife without causing undue slowdown, that would make their movements more predictable and make trapping more practical overall.

**Comment by BorkBorkGoesTheCode** [comment]
>I belatedly realized something. We now have the ability for monsters to have pathfinding. If this ability can be added to wildlife without causing undue slowdown, that would make their movements more predictable and make trapping more practical overall.

I don't see why a few woodland creatures would cause any more performance problems than a horde of zombies, so this would be good.

**Comment by DangerNoodle** [comment]
Problem is that, if I recall, pathfinding has yet to be expanded in use. The only zombies Coolthulhu mentioned giving the token to would be the masters, necromancers, and I think scientists.

**Comment by Coolthulhu** [comment]
The pathfinding is currently rather primitive: it doesn't handle fleeing, stumbling around and allies.

Animals don't have goals, they just mill about and only use pathfinding to find a path to charge things that anger them.

**Comment by DangerNoodle** [comment]
That was something I was uncertain about, yes. Apologies for that.
