### ISSUE TITLE
Use high skills instead of tools

### ISSUE THREAD

**Issue by Waladil** [CleverRaven/Cataclysm-DDA#18643]
A thought based on Coolthulhu's points in discussion about #18538 -- perhaps include high skill levels as alternatives to certain tools, implying that highly skilled practitioners have learned how to quickly improvise tools or work without them.

So, for example, removing a car door would take mechanics 2, and bolt turning 2+ OR mechanics 6. At mechanics 2-5 you need the wrench, but a skilled mechanic could work without it.

**Comment by Rivet-the-Zombie** [comment]
>So, for example, removing a car door would take mechanics 2, and bolt turning 2+ OR mechanics 6. At mechanics 2-5 you need the wrench, but a skilled mechanic could work without it.

Advice from a real life mechanic: you're still going to need the wrench.

**Comment by Waladil** [comment]
Hehe, I'll take your word on it, then. At best, my RL mechanics skill is 2.

**Comment by mugling** [comment]
I'm working on a crafting implementation that support skills or time. How we use that is very much up fro debate

**Comment by HeadWar** [comment]
Could that implementation also support the possibility that better tools than required could reduce time?

**Comment by Coolthulhu** [comment]
A generic enough implementation could support even tools saving other ingredients.
Though the UI may be a big problem.

**Comment by mugling** [comment]
A sane JSON syntax is whats holding that back

**Comment by Coolthulhu** [comment]
JSON syntax is easier than displaying it to the user.
AND/OR tree with depth 2 would be easy to do on the JSON side, but displaying it could easily lead to weirdness.

We'd have to do away with tools/components/qualities being separate groups and just toss them all into one group, with flags determining whether charges or whole items are used.
This isn't a problem on the JSON side, but would lead to lower readability on the UI.

**Comment by mugling** [comment]
Can you outline an example syntax?

**Comment by Coolthulhu** [comment]
```
"ingredients": [
  [ [ "fire", -1 ], [ "hotplate", 20, "tool" ] ],
  [ { "skill": "cooking", "level": 3 }, [ "fire", -1 ], [ "hotplate", 10, "tool" ] ],
  [
    { "AND": [ { "OR": [ [ "two_by_four", 2 ], [ "stick", 2 ] ], { "skill": "fabrication", "level": 2 ] } ] },
    { "AND": [ [ "scrap", 10 ], [ "welder", 20, "tool" ], { "skill": "mechanics", "level": 2 ] } ] },
    { "using": "plastic_working", "amount": 10 }
  ]
  [ [ "plastic_chunk", 10 ] ]
]
```

This is a bit convoluted example. Would be simplified by using "using"s, especially for things like woodworking (we want wood, saw, wood skill) or metalworking (scrap, welder, mechanics). Though it could also spaghettify it.

Basically,
* The first node is AND (because we want all ingredients by default)
* Each node on level 0 defaults to OR, because it's clearer, but can be explicitly made into an AND
* Each node after that must be explicitly specified as AND or OR
* Components, tools, qualities are all on the same level, just marked in some way. Would also help with pseudo-components, such as time and having an acid blood mutation. In fact, we could even make it so that time is internally only expressed as such pseudo-component rather than having a separate class field for it (json field would probably stay, for readability)

**Comment by DaliTimelord** [comment]
A mechanic is limited by his tools, not his imagination. A tool exists to perform a specific act with as much efficiency and concentration as possible. You will not be able to improvise the torque of a wrench or a screwdriver, the precision, temperature, and consistency (of heat) of a welder or torch, or the strength of a jack lifting cars. If you're able to craft or improvise an equally efficient, precise, and consistent tool (which requires late-game tools like an anvil or crucible), at that point, why not just have the tool to begin with?

Are these tools to be easily craftable, but break after use? Doesn't this bypass the difficulty curve of getting tools to begin with? There is also the bootstrap problem of 'you need tools, to train high mechanics, to make (improvise) tools, to utilize high mechanics'? 

A better idea is to permit other non-tools to act as a substitute, or to simply expand the library of 'tools', some of which would act at a cost:

- **The non-tool is consumed:** You use acid to cut metal, but the acid is used in the process.
- **Some components of the item being disassembled are destroyed:** You use a fire to burn wooden objects to obtain the scrap or nails, but lose the wood in the process.
- **The process damages you:** You can use acid blood to cut metal, but cutting yourself does damage as well as blood loss. Not common, but reasonable. This is not unlike welding without protection.

**Comment by aeoo** [comment]
>So, for example, removing a car door would take mechanics 2, and bolt turning 2+ OR mechanics 6. At mechanics 2-5 you need the wrench, but a skilled mechanic could work without it.

I'm trying to think how this might be done without a wrench.  I'm assuming there are some bolts that need to be unscrewed.  They could conceivably be drilled out instead -- then you need a drill instead of a wrench, and doing it this way you lose the bolts.  Maaaybe in some cases, if you sprayed the bolt with some grease, and banged on it a bit with a rock or something, it would loosen up enough to unscrew with just your fingers or pliers?  Now I'm really getting into some hypotheticals here, maybe if you heated the bolt with a blow torch and rapidly cooled it with ice water, it would snap, but something other than the bolt might also snap.  That isn't exactly a clean way to remove the door.

I think your idea is not wrong, but to replace the wrench you often need other tools (so not tool-free), and/or, you need to be some sort of a mechanics maestro, so it would be mechanics 8 rather than 6, I think.  Someone with mechanics 6 is a highly trained mechanic but not necessarily someone who knows how to think outside the box, or how to think from first-principles, which is something people do at the very top of their skill level.

**Comment by Xpyder** [comment]
I wonder if we could implement "workaround" tools like a mattock or crowbar for extracting things, with disadvantages like damage to the parts, possibility for injury, and special parts disallowing them?

For example, most batteries could theoretically be freed by crowbaring them out, destroying the securing bar and at risk of damaging the battery connectors

**Comment by DaliTimelord** [comment]
[I've made a forum post on this issue](http://smf.cataclysmdda.com/index.php?topic=13408.0), since it's likely that this will be argued in the future, not just now. The recipes (disassembly, crafting, vehicle, etc), properties, and tools in those recipes should be referenced by a list of exceptions that would be handled by a small system called 'Substitution', rather than have those exceptions directly added to the recipe. This would keep recipes static while exceptions, being as heinous as they are, would be dynamic. When separated, downsides like additional time needed or breaking of parts can be handled by Substitution, rather than skipped when normally added to a recipe.

**Comment by Leland** [comment]
Closing due to stalled discussion. Ping me here to reopen if there's still interest.
