### ISSUE TITLE
fixing Night Vision 1

### ISSUE THREAD

**Issue by pisskop** [CleverRaven/Cataclysm-DDA#18640]
The night vision you can take with any start is incredibly strong, and easily worth double its point cost.

suggested fixes, especially in lue of how it avoids the need for a nighttime lightsource early game, are to nerf it to 3 - 4 tiles, to increase its cost, both, or to buff early game by allowing the moon to not be new on spring day 01.

**Comment by ZenZen2** [comment]
i agree, i never take it because it feels to strong.

**Comment by Rivet-the-Zombie** [comment]
Ever since the lighting system was last improved, night vision doesn't have a hard rule that states 'you can see X tiles in the dark' any more; nowadays it actually improves your ability to see in low-light conditions, which varies depending on how dark it is/whether you're outdoors or not/moon phase. It may be that it could use a bit of a tweak, but limiting its visual range to an arbitrary number of tiles regardless of current light level is not the way to do it.

**Comment by Coolthulhu** [comment]
> limiting its visual range to an arbitrary number of tiles regardless of current light level is not the way to do it

NV effect in total darkness is a good thing to balance around. It's not an arbitrary cap, but is a cap nonetheless.

**Comment by illi-kun** [comment]
NV was modified in #19010. I guess we need to update this issue taking into account that rebalance.
