### ISSUE TITLE
Roads overwriting building segments

### ISSUE THREAD

**Issue by John-Candlebury** [CleverRaven/Cataclysm-DDA#18726]
It seems that in some cases the roads that are supposed to connect building and towns may overwrite parts of the building.

Readily evident with the apple orchard, football field, and large power substation; but can also happen with the apartment building

**Comment by codemime** [comment]
I didn't see the consequences of the bug yet, but I guess I found what may cause it. The bug is in `overmap::place_special()` and it seems to be quite old. The function assumes that the road should come out of the "top" of the map specials, and if it's not the case, it places the road without any rotation and regardless of the `"allow_road"` flag.
