### ISSUE TITLE
Crafting menu recipes aren't sorted

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#18777]
They seem randomly scrambled.

**Comment by mugling** [comment]
Do you know since when?

**Comment by mugling** [comment]
What isn't sorted correctly. I get them in descending order of difficulty?

**Comment by mutability** [comment]
Hickory nut ambrosia is difficulty 3
Tainted tornado is difficulty 5
Bark tea is difficulty 3.

![bad-crafting-sort](https://cloud.githubusercontent.com/assets/3055062/19410372/8b7d4dec-92e2-11e6-92d7-dbb4fa98ee9a.png)

Oxidizer (5), diazepam (6), potassium iodide (5)

![bad-crafting-sort-2](https://cloud.githubusercontent.com/assets/3055062/19410389/0c338884-92e3-11e6-8f75-f3bd6bd33b9c.png)

**Comment by mutability** [comment]
This may be because of sorting on the raw difficulty but displaying get_custom_difficulty()

**Comment by Oskar636** [comment]
This is fixed now, I suspect it was fixed by #19086, the difficulty of the items didn't match their real value when shown, but it was getting filtered correctly would be my guess. Oxidizer power is 8, diazepam is 6 and the only thing that isn't in the same place is the iodine tablets, which also have 6 difficulty, but that's probably sorted by some other factor.
