### ISSUE TITLE
Item migration bug?

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [CleverRaven/Cataclysm-DDA#18819]
After editing the id of the Rico 454 and saving Fictional Weapons on windows, the following message appears:

DEBUG          : ERROR: data/mods//FictonalWeapons/fic_weapons.json: line 1.1: 
expected object or array

FUNCTION boolgame::opening_screen()
FILE src/main_menu.cpp
LINE 813

This is repeatable with most recent experimentals.

**Comment by illi-kun** [comment]
That's something similar to #18721.

**Comment by BorkBorkGoesTheCode** [comment]
Incredibly, it only happens when the DeadLeaves is changed.

**Comment by BorkBorkGoesTheCode** [comment]
This happened due to using item migration

**Comment by BorkBorkGoesTheCode** [comment]
Replicate: migrate an item in a mod using item migration.

**Comment by mugling** [comment]
> Replicate: migrate an item in a mod using item migration.

Don't do that all all

**Comment by BorkBorkGoesTheCode** [comment]
>Don't do that all all



It doesn't matter if the migration.json file is present in the mod or core.

**Comment by mugling** [comment]
> It doesn't matter if the migration.json file is present in the mod or core.

Mods performing migrations isn't going to work due to potential interactions between mods. There are too many moving parts:

* JSON `MIGRATION`
* C++ migrations in `savegame_json.cpp`
* Legacy savegame support via `data/legacy`
* Mods with indeterminate loading order
* Blacklisting via `ITEM_BLACKLIST`

Use of the json `MIGRATION` type is only intended for core and only then when otherwise entirely unavoidable.

The correct (and only) approach with a mod if you **need* to break compatibility is start a new version. Doing so because you want to update an item `id` isn't sufficient.

**Comment by BorkBorkGoesTheCode** [comment]
The test mod is corrupted.
