### ISSUE TITLE
Sleepy trait seems to have no effect.

### ISSUE THREAD

**Issue by WJohn** [CleverRaven/Cataclysm-DDA#18837]
If you have the sleepy trait and go to bed at 11 PM while tired, you will still get up by roughly 5 AM fully rested. This is effectively a free trait to pick with no actual downsides because it's not like you're losing hours where you could be doing something when it's dark out, early game or otherwise.

**Comment by Coolthulhu** [comment]
It makes you tire a bit faster and then also sleep faster.
It could lose that latter part, I guess. No one needs to sleep 12 hours, so those frequent sleeps are probably just extra regen.

**Comment by victicdin** [comment]
As the living reincarnation of a log I can attest to the morale benefits that chasing a good dream can net you. It also makes you tire faster despite sleeping longer because your chemistry isn't hunky dory with all that, which in turn triggers a downturn near the middle of your wake cycle. In fact I'd say it actually lowers your stamina a lot of the time in real life.
Heavy Sleeper makes you sleep deeper, Sleepy makes you sleep more frequently. If Sleepy were to change at all I'd think it would net a small stamina debuff if anything. Otherwise it still makes sense as is. Making the PC sleep longer _and_ more frequently would risk interfering with comestible intake severely imo. Not sure if desirable?

**Comment by BorkBorkGoesTheCode** [comment]
>It makes you tire a bit faster and then also sleep faster.

You could include that feature in the Langorous mutation.

**Comment by Coolthulhu** [comment]
Languorous is one of those traits that come in pairs (good/bad).
As far as I recall, it is supposed to be more generic than just lack of energy, also including effects like having lungs ruined by smoking or heart problems.

**Comment by Leland** [comment]
No active discussion for over 6 months. Closing – feel free to reopen if there's still interest, or just create a new issue.
