### ISSUE TITLE
'Blocking' technique vs. an enemy seems to take 0 turns

### ISSUE THREAD

**Issue by MisterFox** [CleverRaven/Cataclysm-DDA#18899]
It seems that the 'block' technique (W_BLOCK1, possibly 2 and 3) may be bugged but I'm not certain -- this is what I experienced:
1. Found a book that taught the 'Medieval Swordsmanship' melee combat style.
2. Made a 2-by-sword to test it out.
3. Attacked a zombie. Every hit was 'You block the zombie for X damage!' but no turns were being taken unless I missed.
4. I was able to kill a zombie in a crowd of other zombies before any of them could move by repeatedly blocking the first zombie over a dozen attacks.

I assume this is a bug, but is it working as intended?

**Comment by Oskar636** [comment]
I don't understand what martial art was used, since the 2-by-sword can't be used with any martial art. But the Eskrima martial art used with a 2-by-four can lead to this. Essentially the blocking works fine ( it takes turns ) but there is a bugged atack which says " You block X for X damage!", and this atack takes 0 turns.

**Comment by Coolthulhu** [comment]
Block technique is marked as dummy, meaning it shouldn't be automatically used.
But it looks like the `"dummy"` field is not read anywhere, meaning it stays unset. This is probably a very old bug, that only became noticeable when blocks started taking 0 time.
