### ISSUE TITLE
Vehicle repair charge counting doesn't get multiple UPS sources right

### ISSUE THREAD

**Issue by mutability** [CleverRaven/Cataclysm-DDA#18912]
Given:
- a welder with a UPS conversion mod and 189 charges, in inventory;
- a UPS with 113 charges, in inventory;
- a UPS bionic, activated, with 646 power available

I can't do a repair on a vehicle that needs 300 welder charges.

The bionic UPS on its own, or the standalone UPS plus welder charges, should be able to cover 300.

**Comment by jaked122** [comment]
Could you tell me if it works properly if you have two UPS units that add up to 300?

**Comment by mutability** [comment]
It seems to be entirely dependent on the welder charges. Now I have 2 fully charged UPSs (2x1000) and a welder with 192 charges and I can't do a 300-charge repair.

Maybe this is user error, I thought UPS-converted tools would draw on available UPS power as well as their own charges but maybe that is not true? (It's an annoying timesink if so as you have to hang around and wait for the UPS to recharge the tool)

**Comment by mutability** [comment]
player::consume_charges() is aware of USE_UPS-enabled tools being able to draw on available UPS power (though it is a little buggy, it should drain available tool charge and take the remainder from UPS if insufficient tool charge is available). But that logic doesn't seem to have made it to the crafting stuff at all.

**Comment by jaked122** [comment]
@mutability at player.cpp:10848 seems to be the line that needs looking at.

I'm going to try and fix it.

**Comment by Coolthulhu** [comment]
0.D? This?
If this is 0.D, then we aren't getting the stable out this year. And possibly even not the next one.

**Comment by kevingranade** [comment]
My addition of this to the 0.D list is based on severity not difficulty.  If you have an outline of why it's infeasable in the short term please add it to the issue.

**Comment by Coolthulhu** [comment]
It's infeasible because the game doesn't support any of:
* Direct UPS consumption during crafting
* Consumption of UPS charges outside inventory
* Mixed consumption of tool charges+UPS charges
* Splitting UPS charges across different tools (needs to be handled somehow or at least debugmsg if a requirement with multiple UPS consumers is defined)

At this point it's more of a feature request than bug report. Crafting using charges from UPS directly was never a thing.

**Comment by mutability** [comment]
This is repair, not crafting.

**Comment by Coolthulhu** [comment]
Repair counts and consumes charges in the same way as crafting. The only difference is the UI and the result.

**Comment by mutability** [comment]
Ok.

IIRC (given the time elapsed since this report was created, my memory is hazy) the bug here, aside from possible enhancements, is that the "do you have enough charges" test gets it wrong and prevents you from trying to do a repair that would actually succeed (i.e. would find somewhere to drain the charges from)

**Comment by jaked122** [comment]
@mutability, its been a while, but that's the first issue, I recall there being two ways that the tool's functions were invoked, and it worked with one, but not the other.

I think that might have changed when the ammo-clip overhaul was done, as my fixes no longer worked properly. Though, that might not be remembering correctly.

The InventoryVisitor or whatever it is went way over my head, which is where I think the issue is.

**Comment by Coolthulhu** [comment]
It never worked, it's a feature request rather than a bug report.
Vehicle repairs always (3+ years) used the crafting code, nowadays more explicitly.
Crafting code never understood UPS sources properly - it only cares about tool charges, which aren't encapsulated but rather accessed directly. UPS allows recharging tool charges, but it doesn't allow the crafting system to use UPS charges.

**Comment by kevingranade** [comment]
Plan of attack:
In player::use_charges(),
  tally available UPS charges and their sources.
  search for a tool with the appropriate tool quality and a UPS mod.
    If found, consume the charges from the UPSs

Only question is, do we prefer consuming UPS charges or tool charges?

**Comment by Coolthulhu** [comment]
> Only question is, do we prefer consuming UPS charges or tool charges?

If we're going player-centric, then tool charges.
We want tools sitting in a recharger to consume vehicle charge, not player charge.
Later on, we could have those tools drain vehicle charge directly (instead of own charge) and just get rid of the internal battery in UPS-modded tools. But that would require having location data with items.

> In player::use_charges()

I'd expect the biggest problem to be `has_charges` instead.
Consider the edge case:
* Spawn a hotplate, UPS-mod it
* Spawn a soldering iron, UPS-mod it
* Spawn an UPS, load less than 20 charges into it
* Open crafting menu, look at kinetic bullet puller
* Do we have enough hotplate charges? Do we have enough soldering iron charges?

The simplest option would be to ensure that there are no recipes that use two different electric tools. There aren't many core recipes that do this.

**Comment by kevingranade** [comment]
It should be fine as long as has_charges() and use_charges use the same algorithm.
For each tool set, consume tool charges first and only consume UPS charges if the tool charges are insufficient.
