### ISSUE TITLE
Otherworldly horror sighting morale penalty

### ISSUE THREAD

**Issue by Voskhod-1** [CleverRaven/Cataclysm-DDA#18957]
Inspired by #18950

Something I feel isn't implemented very well in the game yet is how psychologically damaging even viewing some of the transcendent terrors in the Cataclysm can be. Mi-gos, shoggoths, jabberwocks, deformed snail-like humans, and eldritch abominations from the outer spheres all make their appearance in the game. All of these apparently elicit no response from them player character other than a raised eyebrow.

There is already a tag in the game for paralyzing fear, but I figure that would be too much to add to the many monstrous creatures in the game. Instead, I suggest a new flag - a "horror" flag that induces a very significant morale penalty (100 or 200) for a short amount of time when a creature bearing this flag comes within 10 or less tiles of the player character. (This penalty would of course stack)

This only makes sense, no? The average human response to seeing such creatures would probably be at minimum "Oh God oh God WHAT IS THAT? LOVECRAFT WAS RIGHT ABOUT EVERYTHING, HOW DID HE KNOW!?". Not only would it severely reduce focus, but it would also make these creatures indirectly more dangerous by invoking the negative stat modifiers from extremely low morale. Of course, this low morale modifier would have to expire relatively quickly, to signify the creature either being dead/gone but the player still being residually disturbed by the experience.

There could also probably be 2 or 3 tiers of this flag, so that a mi-go induces a morale penalty of 50 or 100, whereas a jabberwock or shoggoth might induce 200.

**Comment by Solusphere** [comment]
I can see this being very annoying to deal with.

"Goddammit, not another Mi-go. Now I have to kill it and wait another two hours in one spot to regain focus before moving on again."

You could possibly just have them trigger shaking hands, which already exists in the game.

**Comment by Voskhod-1** [comment]
A common theme of Lovecraft's works, of which I'm a huge fan of, is of the fragility of the human mind upon its blissful ignorance being torn away by witnessing aeons-old cosmic abominations from other planes of existence. I feel like - thematically at least - it would fit within the game without being too annoying. 
I'd mostly like to point out how this isn't anything outstanding from human-behavior, the average response to such horrors would be fear and wishing to avoid them at all costs (which most players do with Mi-go's to begin with)
That and its not much different from other monster-affected morale malluses like killing zombie children.

**Comment by BorkBorkGoesTheCode** [comment]
How about a 25 morale version called "other" and a 100+ morale penalty after surviving a mauling? THe player could become desensitized after enough of both.

**Comment by Solusphere** [comment]
I agree it would be very thematic, I just don't like the idea of having your skill gain unavoidably suppressed for long periods. The morale malus might go away quickly, but with a -200 penalty, I imagine your focus will tank like crazy, and take a while to recover even after the malus is gone.

That said, I don't have enough experience with short-lived, extremely severe morale penalties to know exactly what the effects would be, so its possible i'm overestimating the consequences.

**Comment by Voskhod-1** [comment]
I don't think you can become desensitized to Shoggoths. Not without going insane, at least.

**Comment by Solusphere** [comment]
Possibly not shoggoths, but you should at least get used to killing Mi-go after you've killed 10 or so. They're scary and otherworldly, but ultimately only a minor threat to an experienced survivor, and I'd consider them to be less instrinsically terrifying than, say, a zombie master.

I'm not sure how possible it is, but what would be cool is if you could get the visual distortion effect (from hallucinations and the visual disruptor bionic) in just the tiles adjacent to the stronger otherworldy creatures, so you can see reality visualy warping from their presence. Zombie masters pretty much explicitly have this effect when you look at them. I don't think it works for tilesets unfortunately, but it would be a very nice touch for those who use ascii.

**Comment by DangerNoodle** [comment]
I am unsure if a morale penalty is a good idea. In addition to it adding tedium, it would be another morale effect in a sea of morale effects. Causing tremors, visual distortions, or hallucinations all sound more interesting that a morale penalty.

That said, it would also be reasonable for characters to not be all that shaken by confronting the anomalous. Unless the horror effect is psychic or otherwise itself an anomaly (fear paralysis is explicitly a psychic attack), it would only make sense if the creature in question is blatantly violating known laws of physics with its mere presence.

A shoggoth is likely a formidable thing, and its common depiction with a shifting, oozing appearance might realistically be nauseating if its changes were chaotic enough, but a rational mind could still file it away as a blob monster, assuming the creature is consistent with artistic depictions of it. Likewise, a mi-go is generally interpreted as an arthropod of some sort, and that grounds its appearance in reality.

**Comment by Voskhod-1** [comment]
Causing secondary effects like shaking hands / other status effects rather than morale seems to be the popular alternative then. Perhaps along with shaking hands we could add another status effect of "Fear" and a stronger version "Horror" which add varying degrees of INT/PER penalties?

**Comment by Voskhod-1** [comment]
>A shoggoth is likely a formidable thing, and its common depiction with a shifting, oozing appearance might realistically be nauseating if its changes were chaotic enough, but a rational mind could still file it away as a blob monster, assuming the creature is consistent with artistic depictions of it.

Yes, but seeing a mere canvas picture of a Shoggoth and seeing the actual real thing in front of you, moving about, is probably enough to cause even the bravest person to recoil in horror. Beyond that - I'd like to mention that there's absolutely nothing rational about fear, at least usually. It's an instinctive, gut response to an unknown danger that can only rarely be controlled - and likewise rarely be invoked by conscious thought.

**Comment by Coolthulhu** [comment]
I don't like the idea of monster-inflicted morale penalty.

The penalty for killing NPCs is already disliked enough. The one for killing children is lower, but also annoying.

Lovecraft's "undulating horror I dare not describe" kind of a thing doesn't work in a video game where "if it bleeds, we can kill it" is a common theme.

Realistically, the player character and all NPCs would have permanent PTSD, problems sleeping, at least 3 phobias each and would lose stomach contents really often. But that wouldn't add much to the game.

A short term penalty could be a specific attack, but I'd rather test it in very limited environment before making it a global theme for all "horrors".

**Comment by DangerNoodle** [comment]
> Yes, but seeing a still, digital picture of a Shoggoth and seeing the actual real moving thing in front of you - roiling bubbles of infinitely plastic, blasphemous un-flesh; eyes teeth and mouths forming and unforming in nauseating protoplasmic chaos - are two entirely different things. Such would probably enough to cause even the bravest person to recoil in abject horror. Beyond that, I'd like to mention that there's absolutely nothing rational about fear, at least usually. It's an instinctive, gut response to an unknown danger that can only rarely be controlled - and likewise rarely be invoked by conscious thought.

True. I am mainly thinking that the fear response and nausea such a creature would provoke is more likely to be a mundane response. Less "what even is that abomination, I cannot even process this" and more "that thing is huge, how do I kill it, oh god it's likely going to eat me" I mean.

Along with possibly "stop shifting so much, just trying to keep an eye on it is giving me motion sickness" in the case of shoggoths.

**Comment by Soadreqm** [comment]
>A common theme of Lovecraft's works, of which I'm a huge fan of, is of the fragility of the human mind upon its blissful ignorance being torn away by witnessing aeons-old cosmic abominations from other planes of existence bearing down on them.

No, that wasn't really what Lovecraftian sanity loss was about, at least in the works Lovecraft wrote himself. People did go mad, but it wasn't because they saw something weird and gross. It was because they realized they had been wrong about how the world worked.

Lovecraft's protagonists lived in a state of blissful ignorance about a lot of things. They believed in Newton's laws of motion, the applicability of Euclid's geometry to the real world, and the absolute, unassailable supremacy of the human race. The third one there is the one they see violated the most. It's not the sight of great Cthulhu that drives men insane, it's the realization that _humans are not that big a deal._ There's a giant monster in the ocean, it's been there for longer that your kind have known language, and there isn't a damn thing you can do about it. One day, it'll rise up, and the world will end. Ancient religions were right, and enlightenment was wrong.

In the setting of Cataclysm, of course, this is less a sudden, horrible realization and more an established fact that's already given away by the very premise. Humanity has lost its spot at the top of the food chain so unquestionably that there isn't much point in even mentioning it. Civilization has crumbled, and you're fighting for survival against an enemy you have no chance to truly defeat. A shoggoth isn't anything _new._

**Comment by DangerNoodle** [comment]
True. That suggests that the mere existence of the cataclysm, the presence of extradimensional beings in general (not merely Lovecraft-style ones), and the dead rising and hungering for the living are all things likely to have provoked those thoughts first. Terror after the fact is more likely to be primal and mundane in nature, or possibly generated by explicit anomalies.

**Comment by Rivet-the-Zombie** [comment]
>People did go mad, but it wasn't because they saw something weird and gross. It was because they realized they had been wrong about how the world worked.

Their sanity was also about as resilient as spun glass, and had a tendency to evaporate the moment they saw anything even remotely weird.

>In the setting of Cataclysm, of course, this is less a sudden, horrible realization and more an established fact that's already given away by the very premise.

I'd say all the Gustaf Johansens of the world are probably dead by this point, with the survivors numbering among those folks who didn't turn into gibbering idiots upon seeing arrival of the eschaton.

**Comment by DangerNoodle** [comment]
Granted, I do not know if it meant to be something impossible to depict in writing, or if Lovecraft had rather low expectations of other people and their mental fortitude.

**Comment by Leland** [comment]
Stalled discussion for about 6 months – closing. If anyone wants this reopened for purposes of continued discussion/development, ping me here. Or feel free to create a new issue, which will give you greater visibility in the issue queue.
