### ISSUE TITLE
Variable transparency causes shadowcasting to perform very badly (i.e. O(2^n)) in worst case.

### ISSUE THREAD

**Issue by KyleSiefring** [CleverRaven/Cataclysm-DDA#19007]
The transparency calculations added to the shadowcasting code make it possible to encounter exponential complexity in worst cases. Simply alternating between two different levels of transparency should cause shadowcasting to become uncomputable.

I have prepared a unit test in the branch below that demonstrates this case by randomizing each value with some degree of transparency.

https://github.com/KyleSiefring/Cataclysm-DDA/tree/random_transparency_performance

On linux: To run, compile and run `./tests/cata_test shadowcasting_random_transparency_performance` from the base cataclysm directory.

Example output:

```
castLight() executed with a view distance of 9 in 606 microseconds.
castLight() executed with a view distance of 10 in 1154 microseconds.
castLight() executed with a view distance of 11 in 2037 microseconds.
castLight() executed with a view distance of 12 in 4118 microseconds.
castLight() executed with a view distance of 13 in 7902 microseconds.
castLight() executed with a view distance of 14 in 15449 microseconds.
castLight() executed with a view distance of 15 in 29637 microseconds.
castLight() executed with a view distance of 16 in 63421 microseconds.
castLight() executed with a view distance of 17 in 115850 microseconds.
castLight() executed with a view distance of 18 in 231070 microseconds.
castLight() executed with a view distance of 19 in 457259 microseconds.
```

If this is currently causing performance problems, I suspect that it would be most noticeable near a large fire. Since many transparency effects aren't very transparent, it may very well not be causing any serious problems right now.

At the very least, information about this worst case scenario should be included somewhere in the shadowcasting code.

**Comment by Coolthulhu** [comment]
The problem seems to be inherent in the shadowcasting algorithm.
It is one of the reasons why smoke near fires was almost totally removed.

Shadowcasting recurses on any transparency change (except to fully opaque).

Comments could be added, but shadowcasting is essentially the "restricted area" where all changes are supervised closely due to hard algorithms behind all of it. Anyone who edits those parts will need to understand the algorithm first and this includes realizing that it recurses on transparency change.

**Comment by jaked122** [comment]
@Coolthulhu is this really an acceptable algorithm for this problem? 

Shouldn't raycasting handle this fairly easily?

**Comment by kevingranade** [comment]
(Sorry to necro, I don't seem to be getting a lot of my emails in the mail
client I typically use so I saw this for the first time just now)

First, this test is a pathological torture test for shadowcasting, the game
CANNOT actually produce this scenario.  This line:
square = LIGHT_TRANSPARENCY_OPEN_AIR * rng();
Is what breaks it, because LIGHT_TRANSPARENCY_OPEN_AIR is equal to
0.038376418216
(an empirically determined number that causes visibility to drop to 0 by
the time shadowcasting reaches the map edge).  As a result, this test sets
all squares to practically indistinguishable variations of "almost totally
transparent", which simply breaks the shadowcasting algorithm.
I strongly suspect that if the above line were changed to:
square = LIGHT_TRANSPARENCY_CLEAR * rng();
The results would be very different, since many of the transparency values
would be extreme enough to cull a significant number of tiles.  An even
more fair test would be to select from one of about 6 transparency values
the game actually uses, which would result in some contiguous spans the
algorithm could work on, but more importantly a lot of culling of the
squares above some distance since visibility would degrade enough to cause
it to halt.
An even more fair test would weight the distribution of transparencies such
that squares are mostly transparent, with some opaque squares, and small
clusters of semi-transparent squares.

> is this really an acceptable algorithm for this problem?

Shadowcasting has very good (near linear in the number of tiles being
shadowcast across) performance as long as there are large contiguous areas
with the same transparency.  As this test points out, it has a bad
degenerate case when there are few or no contiguous areas with the same
transparency level.  To avoid this scenario, the game only uses a very
small number of transparency values and combines them in such a way that
they will quickly become opaque if you stack a number of fields.
Shadowcasting has beter-than-linear performance when it can cull large
areas of the map, which happens frequently in scenarios that would
otherwise be problematic, like smoke clouds and forests.  To put this a
different way, shadowcasting is linear with respect to the number of
visible squares, and less-than-perfect transparency generally corrects
itself due to tile culling that low visibility causes.

It would be nice to extend this further with some performance tests that
run shadowcasting against some typical map scenarios produced by dda
mapgen, such as inside and outside of houses, near or in forests,
underground (That one I'm not worried about, but test the expected good
tests too), and some pathological but real cases such as near a cloud of
semitransparent tiles.

> Shouldn't raycasting handle this fairly easily?

You need to be more specific, shadowcasting IS raycasting, there are a
number of different, specific raycasting algorithms, most of them do a LOT
more work than shadowcasting in some extremely common scenarios, so they
would need to be carefully compared for accuracy, performance, etc.

>

**Comment by kevingranade** [comment]
Unless there's a demonstrable issue with an in-game use case, this is a non-issue.
