### ISSUE TITLE
Holsters can function from inventory

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#19043]
Wielding a gun from a holster stored deep in the backpack is just as fast as wielding one from a worn holster.

Same for sheathing.

**Comment by mugling** [comment]
Presumably it should be possible, just much slower?

**Comment by Coolthulhu** [comment]
Should probably take as much time as regular inventory grab.

Also, the draw time for holsters is incredibly low (4 moves at skill 3), though that's a totally separate issue.

**Comment by John-Candlebury** [comment]
I dont know if this is related but: 

Holsters and scabbards cant  be utilized when wielded in your hands, which might cause your death when you accidentally "w"ield them instead of activating them.

 Could activating them while in your hands simply drop the holster to the ground and leave you wielding the weapon?
