### ISSUE TITLE
Rifle caliber ammo needs a damage nerf

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#19042]
Now that accuracy at range is pretty good, rifle caliber ammo no longer needs 50+ damage to hurt.

The damage listed is just base. It can get increased to as much as 335% of the base due to a good hit roll.

Because of that, a torso shot is likely to be an instant kill and a hulk can be taken down with a single burst.

This prevents sensible balancing of monsters, adding hostile NPCs (because they can be instant death), adding monsters with guns without making them giant threat and balancing melee against guns and making hp increase mutations actually matter.

And before someone invokes "but realism" - we don't have instant death from being stabbed through the eye with a broadsword, shot in the eye with a .22, getting impaled by falling on a wooden spear or getting face smashed with a sledgehammer. For good reasons.
Rifle caliber ammo would be perfectly fine with no capability to 1-shot anyone from 30 tiles.

**Comment by BorkBorkGoesTheCode** [comment]
The section talking about damage being based on muzzle energy (joules) needs to be removed from GAME_BALANCE if this is done.

**Comment by mugling** [comment]
I'd agree with both. Those values in `GAME_BALANCE` were useful for achieving a semblance of balance but ruining gameplay for their arbitrary preservation isn't helpful especially considering we don't apply the same logic elsewhere.

We need to improve the distinction between ammo types - for example `223` should be good in low range and in bursts whereas `300`, `762R` etc should be higher damage at longer range. This would also add some more distinction to the guns.

It would be best if we discussed proposed balance as opposed to randomly fiddle with stats and when we reach a decision it should be backed by acceptance tests.

**Comment by Solusphere** [comment]
Maybe leave the .50 cal damage where it is? It has enough drawbacks currently to be rarely worth using, and it's damage really should be well over twice that of a .223 round.

**Comment by BorkBorkGoesTheCode** [comment]
It should literally be the best cartridge from a damage standpoint. It could be okay from an accuracy standpoint when fired from the M2.

**Comment by BorkBorkGoesTheCode** [comment]
Why not create a ratio system for setting damage?

**Comment by mugling** [comment]
> Why not create a ratio system for setting damage?

That could work and would prevent painful mass-rebalancing, @Coolthulhu?

**Comment by BorkBorkGoesTheCode** [comment]
It could be a slider in the world defaults menu like monster spawns. In order to allow modding it should allow full overrides.

**Comment by Coolthulhu** [comment]
Sounds like a lot of work that would just form dependencies between all bullets.
I'd rather just see it as a standard, not mechanic.
We don't want it to turn into another material thickness thing.

We should come up with an arbitrary measure of worth for guns and ammo, something like what damage per moves is for melee.

**Comment by kevingranade** [comment]
> Because of that, a torso shot is likely to be an
> instant kill and a hulk can be taken down with
> a single burst.

Two things, hulks should probably just have ludicrous hp. Yes that might
make them invulnerable to pistol fire and melee, that's fine. Alternately
crits are likely out of control so that would be worth toning down as well.
Also, if assault rifles are hitting anything several times in a burst with
good hits, somethings wrong.

> This prevents sensible balancing of monsters,

How so?

> adding hostile NPCs (because they can be
> instant death),

This isn't fixable, if you're ambushed by a homicidal and skilled  npc with
a rifle, you *should* die. This is literally what rifles are for.  Npcs
shouldn't be randomly offing other survivors, this is the real problem.

> adding monsters with guns
> without making them giant threat

This doesn't make any sense, of course they should be a giant threat,
that's the point of arming them.

> and balancing melee against guns

If balancing means, "making them remotely similar in effectiveness", you're
missing the point, melee shouldn't deal remotely as much damage as a good
gun.  Melee should have its own niche around ease of
acquisition/maintenance and lack of noise.

> and making hp increase mutations actually
> matter.

Again, it's not remotely reasonable for a mutation (or a whole series of
them) to make a player tough enough to tank rifle rounds.

Kevin

**Comment by mugling** [comment]
One possible solution is to actually implement meaningful armor piercing - pistol and lighter rifle rounds have equivalent damage but the latter has better range and armor piercing?

One of the reasons the zombie soldier is a scary early game monster is because it can tank the non-AP pistol rounds.

> Also, if assault rifles are hitting anything several times in a burst with good hits

At point-blank/adjacent range: yes, at any significant distance: no. Anything else is a bug (but I don't think this is the case).

**Comment by Coolthulhu** [comment]
> Two things, hulks should probably just have ludicrous hp. Yes that might make them invulnerable to pistol fire and melee, that's fine.

That's pretty much the opposite of fine. That's very limiting and sacrificing fun and balance for "realism" of critters that have no real life equivalent.

> How so?

Any monster can be shot down with a gun that has good burst capability. Nothing else can compare.
Giving monsters giant hp/armor to compensate would be a big middle finger to most people who want to enjoy the variety the game has to offer instead of going for the bland but effective.

> This isn't fixable, if you're ambushed by a homicidal and skilled npc with a rifle, you *should* die.

It makes for horribly uninteresting game, though.

> Npcs shouldn't be randomly offing other survivors, this is the real problem.

The player is very often a rich, armed, dangerous mutant. That's at least 3 "realistic" reasons to shoot before asking questions or even being seen.

And that's even before we consider any future expansions to factions.

> This doesn't make any sense, of course they should be a giant threat, that's the point of arming them.

Turrets that warn you that you will die in a moment if you don't go back aren't "realistic", so they "should not" warn about that.
Bots that insta-kill you without warning is just asking to get well deserved criticism (possibly also well deserved insults) from the playerbase, even though they "should" be bursting down people in the middle of the night, with no warning, compensation or explanation.

> Melee should have its own niche around ease of acquisition/maintenance and lack of noise.

Noise isn't a problem. Zombies don't path, don't coordinate their attacks and take a while to reach the player, even if they don't stop to punch a car that happened to stand in their way (which happens very, very often).
Horde code is in pretty awful shape and even if it wasn't, without pathing the zombies just spawn a block away and get occupied with houses and cars.

So it boils down to acquisition.
But if pistols and SMGs can't fill the role of rifles (because of low damage) and melee (because they still require ammo), that's 2 skills with no good uses and a giant set of items that exist only "like that".

> Again, it's not remotely reasonable for a mutation (or a whole series of them) to make a player tough enough to tank rifle rounds.

Not any less reasonable than taking a steel spear between the eyes, which can happen.
Same for zombies taking said steel spear between the eyes.

**Comment by kevingranade** [comment]
>> Two things, hulks should probably just have
>> ludicrous hp. Yes that might make them
>> invulnerable to pistol fire and melee, that's
>> fine.
>
> That's pretty much the opposite of fine. That's
> very limiting and sacrificing fun and balance
> for "realism" of critters that have no real life
> equivalent.

Being able to use any method of attack on any opponent, no matter how
impractical, does nothing to enhance "fun" or "balance". Instead it simply
makes everything needlessly similar.
Where does it end? Shouldn't we support a specialist in killing things with
folded paper? How about using tiny knives? Thrown pebbles? Why not? Simply
because those methods don't deal appreciable damage. Pistols deliver a
fraction of the stopping power of a rifle, that is a fact, and we should
work within the framework of that reality instead of making arbitrary
adjustments in the name of "supporting every way of playing the game".

As for critters having no real life equivalent, that doesn't make much
sense, if for example we say that a hulk is as tough as say an elephant or
a bull, we have a very concrete basis for how much damage one can take
before being killed.  In neither case would it be reasonable to take one on
with a pistol or submachine gun.

>> How so?
>
> Any monster can be shot down with a gun
> that has good burst capability. Nothing else
> can compare.

Cars, explosives and traps are all pretty compelling as far as
effectiveness.
It's quite likely that the way we handle burst fire is simply broken,
hitting a single target with a significant number of rounds at range is
unreasonable. Likewise defending yourself with a rifle against a horde of
enemies at close range shouldn't be feasible.  It's a lot more interesting
to accentuate these weaknesses instead of simply making rifles and pistols
more similar.

> Giving monsters giant hp/armor to
> compensate would be a big middle finger to
> most people who want to enjoy the variety
> the game has to offer instead of going for the
> bland but effective.

You could say the same about literally any challenge that requires
resources of any kind to address. If you want to build a character that
punches things and has no other skills, I have no sympathy for you getting
killed by a bear.

The point of this game is a (pseudo-)person attempting to meet the
challenges posed by a post-apocalyptic wasteland, not building a
nonsensical overpowered wish fulfillment character.  If you want to do
that, you can adjust the data to make that happen.

>> This isn't fixable, if you're ambushed by a
>> homicidal and skilled npc with a rifle, you
>> should die.

> It makes for horribly uninteresting game,
> though.

Again, this vvvvv
>> Npcs shouldn't be randomly offing other
>> survivors, this is the real problem.
>
> The player is very often a rich, armed,
> dangerous mutant. That's at least 3 "realistic"
> reasons to shoot before asking questions or
> even being seen.

So in order to support your concept of NPC social dynamics, you want to
adjust physical reality, doesn't that seem a little backwards to you?
It doesn't matter how much you nerf rifles, if you assume npcs will be
ambushing the player, the player is going to die. If one rifle won't do it,
assume a group of npcs, because attacking in a group is just as justified
as unprovoked agression.
> And that's even before we consider any future expansions to factions.
>>
>> This doesn't make any sense, of course they should be a giant threat,
that's the point of arming them.
>
> Turrets that warn you that you will die in a
> moment if you don't go back aren't "realistic",
> so they "should not" warn about that.

The original concept is that the bots are programmed to interdict an area,
in which case it makes perfect sense to try and warn civilians away before
attacking.  Frankly we've taken this too far by having all robots on warn
mode, but that's not pertinent to this discussion.

>> Melee should have its own niche around
>> ease of acquisition/maintenance and lack of
>> noise.
>
> Noise isn't a problem. Zombies don't path,
> don't coordinate their attacks and take a
> while to reach the player, even if they don't
> stop to punch a car that happened to stand in
> their way (which happens very, very often).
> Horde code is in pretty awful shape and even
> if it wasn't, without pathing the zombies just
> spawn a block away and get occupied with
> houses and cars.

Should, yes it doesn't work the way it should right now, but that's no
reason to make nonsensical changes in unrelated areas to compensate for it.

> So it boils down to acquisition.
> But if pistols and SMGs can't fill the role of
> rifles (because of low damage) and melee
> (because they still require ammo), that's 2
> skills with no good uses and a giant set of
> items that exist only "like that".

Pistols and SMGs fill the niche if being fast to access, simple, small,
cheap, and maneuverable.  These attributes should be accentuated.  For
example if you round a corner in a lab and see an enemy at close range, a
rifle should be nearly useless, this is when you want a pistol, smg, or
shotgun.  The shortcoming of the system is that a rifle *is* capable in
this scenario.  Likewise, if you find yourself adjacent to an opponent, no
gun should be particularly useful, this is where melee weapons should shine.

**Comment by Coolthulhu** [comment]
> Being able to use any method of attack on any opponent, no matter how impractical, does nothing to enhance "fun" or "balance". Instead it simply makes everything needlessly similar.

Needlessly similar?
Being able to stunlock a hulk, wear it down with pistol shots from darkness, pierce it with a spear, burst it down with rifle fire, lead it into mines, lead it into strong animals or bots or fungify it makes it similar to regular zombies just because you technically can do those to them?

Hulks are very different to other zombies because you actually want to attack them in a way more complicated than bumping them while standing in a favorable spot.

> Pistols deliver a fraction of the stopping power of a rifle, that is a fact, and we should work within the framework of that reality instead of making arbitrary adjustments in the name of "supporting every way of playing the game".

Facts don't make good games. We don't have things like bodily functions, 300 yard ranges for pistols, willpower restrictions on work done per day, deadly diseases being randomly caught be healthy people, choking on food and a lot of other facts.
Real life is horribly designed and would make for a very shitty game.

> Likewise defending yourself with a rifle against a horde of enemies at close range shouldn't be feasible. It's a lot more interesting to accentuate these weaknesses instead of simply making rifles and pistols more similar.

Nerfing rifle damage and balancing everything around that would do much more to make pistols useful than artificial limitations on rifles in close range.
Faster aiming and shots on pistols are useful, but they don't fill a niche without being able to stand against strong enemies.

Pistols are expensive to use (like most firearms), have loudness comparable to rifles (40 noise is enough to count as "global") except for hearing damage, take a lot of skill to use (including reloads) fast enough to compare with melee and so on.
The only exception is laser pistol, which shoots nearly for free and doesn't require reloading, has no recoil and minuscule dispersion, thus being completely broken.

> You could say the same about literally any challenge that requires resources of any kind to address.

No, only the badly designed ones.
The well designed challenges offer choices other than name of the rifle to shoot things with.
This is one of the primary principles of video game design: meaningful choices.

At the moment there are multiple ways to kill hulks. Most of them require spending limited resources such as drugs, ammo, hitpoints in a given day, zombie pheromones.
And that's good, because it is how it should be: it is interesting, allows thinking and not just going with the obvious, it makes the player engaged and not frustrated.

The problem here is that some choices are too clearly better than the rest.
Rifle bursts are comparably cheap, yet safe and fast. Cheesing them with infinite use traps and cheap/free ranged attacks (or just careful kiting) is tedious and slow but totally safe and cheap.
Note that buffing hulk HP would favor the latter option more than the former.

> So in order to support your concept of NPC social dynamics, you want to adjust physical reality, doesn't that seem a little backwards to you?

In order to add interesting mechanics to the game, some things have to be sacrificed.
And if the choice is between hostile NPCs making sense and firearms matching some arbitrary measure of "damage", the choice is obvious to me.
It's not like you're defending matching real life here. Just a small subset of it. While also pushing back other parts of it, like simulated people acting in sensible and interesting ways.

> It doesn't matter how much you nerf rifles, if you assume npcs will be ambushing the player, the player is going to die.

We're long way from any ambushing. At the moment we're barely at the point where sniping is possible. But said sniping is already presenting problems that have to be addressed if we are to move forward.

At the moment an NPC could say "hey stranger, wait up", get into range, shoot once and end the game. The only thing that prevents this from happening is artificial limitation on them never shooting without warning or "being red" - a limitation that doesn't make sense from "realism" perspective anyway.

> Should, yes it doesn't work the way it should right now, but that's no reason to make nonsensical changes in unrelated areas to compensate for it.

Some distant future promising fixes for problems that exist since forever is no reason to handwave proper design as "nonsensical" and instead going with no more sensible and no less arbitrary measures of "realism".

And those promises look far less convincing after you said that you don't want zombies pathfinding. Hordes spawning offscreen then just milling about/smashing cars won't do much to balance gun noise.
Unless you changed your mind about zombies pathfinding. Then there would be a potential path from "now" to "gun noise actually mattering, drawing hordes to player's location and not just 3 blocks from it".

> Pistols and SMGs fill the niche if being fast to access, simple, small, cheap, and maneuverable.

Those don't translate well into mechanics. Volume is no big deal (just drag a cart), simplicity loses its value very fast, low price is what melee is infinitely better at, maneuverability is only really important in an emergency ambush/gunslinging/etc. situations where you can't just step back into safety (and those are rare).

It basically boils down to two choices: free to use and silent melee, and hard-hitting and safe ranged. Rifles win in the second category, pistols and SMGs don't compete in the first.

Pistols can be occasionally used as a backup weapon for wearing down tough threats (predators, corrosives, hulks), but this requires being in melee range and just using "gun kata" for fast damage burst. And you just said that ranged weapons should lose to melee at that range.

> For example if you round a corner in a lab and see an enemy at close range, a rifle should be nearly useless, this is when you want a pistol, smg, or shotgun.

We're incredibly far from this situation actually working mechanically.

For one, it would require dropping giant amounts of realism regarding ranges and weapon handling to force a situation where a rifle can't be effectively fired at close range, despite having enough time to aim it roughly in the direction of a (relatively big) target. Shotguns would need to be spared this treatment, despite not differing that much in shape and handling from rifles and carbines.
There was once a penalty for gun volume, but it ended up being so badly thought out that it prevented rifles from being accurate at any range, except in hands of a very skilled shooter.

Then, we'd have to address ability to trivially run away instead of having to actually engage the target right now, in bad position.

Finally, we'd have to actually make the player want to use an expensive, loud weapon against a threat that can be dispatched by bashing it with a plank a couple of times. And if we did it by buffing its HP, then we'd also automatically fail the part where SMGs and pistols are supposed to be viable choices. And it would most likely STILL not result in ranged being a good choice, just more kiting.

And all of that is in a very rare situation: when the player is in a lab, has a choice of firearms, and is in any semblance of danger. Players in labs are, in vast majority of cases, either lab starts (no guns) or advanced characters who can dispatch 90% of threats by punching them repeatedly.

**Comment by mugling** [comment]
Lots of words here so I'll try and be concise and stick to things for which I could write a solution:

* Bursts should now be reasonably balanced and are dependent upon `range`, ammo `recoil` and weapon `weight`. Automatic pistols are only useful for adjacent tiles (too light). An SMG with similar ammo is passable at near distances (heavier). A rifle on full auto is only useful at point-blank range. A heavier machine gun using the same ammo is slightly better or actually usable when mounted on a limited selection of terrain. Anything else is a bug. This could really do with acceptance tests.

* @kevingranade is correct about pistols. I wasn't able to fix that problem in the my recent reworking. Smaller weapons aim faster which works well for everything apart from adjacent range where you are guaranteed a hit so aiming becomes irrelevant. It is currently more effective to carry a huge rifle round a corner than a pistol.

* One solution to the above is for taking melee hits to seriously throw of your aim (proportional to weapon `volume`) sufficient that large weapons are non-viable. This doesn't stop the player getting off the first shot but does reduce the rifle to a giant club in melee.

* We could also have an initiative system whereby whoever changed tile last acts before whoever was standing still. Walking around a corner with a rifle now becomes very dangerous as you'll get attacked first and lose the ability to fire a rifle. A pistol is now more suitable - you could either shoot or holster it quickly and go for a fast weapon.

* @Coolthulhu is correct about `hp` - an increase alone just encourages exploits. Hulks could gain better armor and if we improved the armor piercing code and damage handling they could for example become near-immune to non-AP bullets, bashing and only affected by cutting and stabbing.

**Comment by Coolthulhu** [comment]
> A rifle on full auto is only useful at point-blank range.

Unless you attach a bipod and kite into a favorable position.

> One solution to the above is for taking melee hits to seriously throw of your aim (proportional to weapon volume) sufficient that large weapons are non-viable.

It is already the case if you dodge a melee hit. Does next to nothing to stop rifle superiority.

> We could also have an initiative system whereby whoever changed tile last acts before whoever was standing still. Walking around a corner with a rifle now becomes very dangerous as you'll get attacked first and lose the ability to fire a rifle.

You don't walk around corners that much and even when you do, you won't get attacked by anything without ranged attacks. We don't have many enemies with those because they are too dangerous to have around because they deal too much damage.

And even if we had those, you could still just walk back and use your superior rifle.

> Hulks could gain better armor and if we improved the armor piercing code and damage handling they could for example become near-immune to non-AP bullets, bashing and only affected by cutting and stabbing.

That would lead to tons of tedious exploits using fire, critical hits, spammed weak explosives and the like.
While also robbing pistols and SMGs of one of their few roles.

How about this: on good ranged hit, don't multiply damage but armor piercing (plus add some flat AP, for ammo without it).

**Comment by mugling** [comment]
> > A rifle on full auto is only useful at point-blank range.

> Unless you attach a bipod and kite into a favorable position.

This is a reasonable tactic considering those favorable positions are very limited.

> It is already the case if you dodge a melee hit. Does next to nothing to stop rifle superiority.

The effect is weak though and independent of weapon size. See also #14994

> You don't walk around corners that much...
> ...you could still just walk back and use your superior rifle.

Monster AI and placement needs improving to the point where you might open a door in a building and find a grabber zombie?

> How about this: on good ranged hit, don't multiply damage but armor piercing (plus add some flat AP, for ammo without it).

Not sure about that. Bullets deal `pierce` damage so armor should effectively be resistance to that and `AP` should mitigate that?

**Comment by Coolthulhu** [comment]
> favorable positions are very limited

Not at all - in a city you can just smash open a window and "straddle" the frame (you're sitting on the window tile, so it's essentially straddling). Or get on a nearby car - which you want to do anyway, to avoid spitter acid.

> The effect is weak though and independent of weapon size.

```
recoil += std::max( weapon.volume() / 250_ml - get_skill_level( skill_dodge ), 0 ) * rng( 0, 100 );
```

For an average shotgun or rifle, it translates to average of 400 points of recoil. Enough to undo a whole round of aiming. And it stacks indefinitely.

> Monster AI and placement needs improving to the point where you might open a door in a building and find a grabber zombie?

I'd love clever zombie AI, but unless Kevin has changed his mind about zombies being dumber than insects, it isn't happening. Outside a mod, that is.

**Comment by mugling** [comment]
Putting AI to one side (neither developer consensus nor proposed implementation) we could certainly improve monster placement. This has been discussed before - why do monsters spawn in locked buildings.

Even better if we had an internal increasing difficulty counter that selected spawns dependent upon what would be a challenge for the player?

**Comment by Coolthulhu** [comment]
No, that's certainly an AI issue. If zombies can't silently wait for the right time in a good spot, no placement tricks will lead to ambushes.

**Comment by subhazard** [comment]
Please consult the design doc before making any balance changes.

In reality, bullets dont have 'damage' numbers.   a .22 is just as lethal as a .50 BMG, provided you hit the right spot.

In reality, guns pretty much have the same lethality with some outliers (.22, and .50  for opposite reason), so if the intent is to be realistic, guns SHOULD feel kind of samey, because they are.

If the intent is to make interesting and varied gameplay, then throw out all notions of realism and focus on 'rarity/damage/cost to produce'

-IF YOU TRY TO GO HALF AND HALF YOU MAKE A CONFUSING MESS-

**Comment by mugling** [comment]
> Please consult the design doc before making any balance changes.

This issue is about how the recent aiming changes have caused an inadvertent increase in damage output (second line of @Coolthulu's first post) and secondarily how we might better balance the different types of weapon. You may wish to do some background reading of the last months PR's.

**Comment by mutability** [comment]
This is probably relevant:

![1991eebc-9874-11e6-9e80-f189c788d67c](https://cloud.githubusercontent.com/assets/3055062/19951322/30bbe554-a155-11e6-8e44-06e7d7d22216.png)

**Comment by mugling** [comment]
Yes, that's very helpful. How are you producing that?

**Comment by mutability** [comment]
It's one of the outputs from here: https://gist.github.com/mutability/625b8edb72aceb6abfa161e0acc1c681

**Comment by mutability** [comment]
You could build something equivalent using `Creature::projectile_attack_chance` now, might be a useful addition to the stats dumper to be able to dump a damage curve for a given gun+ammo

**Comment by mugling** [comment]
Yes that would be a very useful addition. It would also demonstrate @Coolthulhu's issue well that at distance there is choice but at adjacent range you're best with the biggest rifle you can find

**Comment by Firestorm01X2** [comment]
Just opinion. What if hordes will be enabled by default? Possible with reduced strenght. Thi way player will think twice brfore usingq loud gun.

**Comment by Oskar636** [comment]
@Firestorm01X2 Hordes would need to be rebalanced first, let's see how #19222 does, and then I think they also need some changes to how many " hardcore " and evolved zombies spawn.

**Comment by mutability** [comment]
Current master: you're always better off using the rifle:

![output](https://cloud.githubusercontent.com/assets/3055062/20248602/85d13bb0-a9df-11e6-9c05-3ed860cc69c6.png)

**Comment by mutability** [comment]
I wonder if tweaking the base (unaimed) dispersion penalty based on gun type/size/handling would help here (i.e. so that a rifle snapshot has a much larger dispersion penalty than a pistol snapshot)

**Comment by mugling** [comment]
It could help but the problem is you need huge dispersion to stop an attack against an adjacent tile from succeeding

**Comment by Coolthulhu** [comment]
I'd rather see monsters use their dodge against guns at close range.
For example, having moving critters add their dodge roll to dispersion - the closer they are, the higher the percentage.
This would represent things actually moving while you're trying to aim at them, which is not represented in the game at all, meaning that the accuracy decreases linearly with range.

**Comment by mugling** [comment]
Both could help here - most importantly we need to plan first to ensure there aren't any obvious exploits

**Comment by jesseking** [comment]
A few comments:
- Generally agree that gun damage should be more credibly 'game-ified'. Trying to make a pistol or rifle do 'realistic' damage while ignoring the fact that having a spear jammed through your chest is almost invariably lethal doesn't make any sense. Most guns don't do more damage than melee weapons - they just do it further away and often faster. In this particular regard CDDA is squarely in the 'game' category, rather than the 'reality sim' category, which is good, because it has far too much combat for it to treat it particularly realistically.

- From a gameplay standpoint, creating a strong distinction between long weapons which have very low dispersion (good effective range), and pistols/smg's with poorer dispersion (shorter effective range) would require placing some kind of very dramatic penalty on firing at targets in melee range for the former, to the point of making it a desperation mechanic - for starters, all aim could be completely lost the moment you are attacked in melee, and probably apply a dramatic 'recoil' value as well. Maybe also make aiming take a bit longer for the long weapons. If none of that gets the point across in terms of distinguishing the weapons, then perhaps simply apply a huge hit penalty at point-blank for 2h ranged weapons.

- If you want to model 'reality' as closely as possible for 'to hit' issues, then gun tracking becomes a major factor as range decreases - quickly becoming much more important than dispersion - but you don't handle tracking as a variable, so range reduction only benefits the shooter in your model. 

EG: When a target is 50 meters away, if it is running fast laterally you need to only very gently adjust your aim to follow them and keep them squarely in frame, although it is still trickier to hit them while moving thus. However, if someone is jumping around 2 meters away, they can literally step 1 meter to the side and force you to swing your gun over 45 degrees or more in an instant. Needless to say, long rifles and bows are terrible at this kind of rapid tracking without completely losing all accuracy due to their awkward mass and grips, and this is part of why some combat rifles and shotguns are sawed short to make fast tracking easier, trading long range dispersion accuracy for better short range tracking. Then there is entanglement - which is the part where anyone in HTH combat will first move take control of your rifle barrel, which you are conveniently holding stock still pointed in their general direction - and hold it up in the air while kicking you repeatedly in the head, were you foolish enough to try to keep the gun in hand once someone reaches melee. Leverage ensures that even a much weaker opponent can easily prevent you from bringing a long rifle to bear in such a situation.

Pistols of course are better for this sort of thing, though they are still a poor match for someone swinging a broadsword at your head in melee or attempting to grapple you and bite your face off, shoving your arms around crazily while you try to shoot. Hopefully you'll manage to put one or two into his gut or face before he bites yours off.

Getting to melee is of course the real problem with guns. Most people won't make it - but we have zombie hordes to throw at you, so chances are decent that some will.

So if you want to be realistic, by all means go ahead - but don't leave out several important factors. Me? As a game designer I'd just apply a massive hit and defense penalty for using 2h ranged weapons in melee and go grab a beer, job well done. ;)

**Comment by kevingranade** [comment]
On Dec 1, 2016 2:39 PM, "jesseking" <notifications@github.com> wrote:

A few comments:

   -

   Generally agree that gun damage should be more credibly 'game-ified'.
   Trying to make a pistol or rifle do 'realistic' damage while ignoring the
   fact that having a spear jammed through your chest is almost invariably
   lethal doesn't make any sense.

Spear through chest is quite lethal, but "spear through chest" is not a
regular hit, it's a critical hit with large stat boosts.  another
consideration you're glossing over is that something that inflicts a lethal
wound on a human will not necessarily inflict a lethal wound on a large
creature such as as moose or a bear, and this would obviously apply to
various large zombies as well.


   -

   Most guns don't do more damage than melee weapons - they just do it
   further away and often faster.

They absolutely do, a 9mm pistol or larger will inflict a highly lethal
wound with a hit anywhere in the chest due to shock, all manner of
bludgeoning weapons will merely wound or break some ribs, and cutting or
stabbing weapons need to hit something vital to be immediately lethal. This
is without getting into rifles, which cause absolutely massive damage.


   -

   In this particular regard CDDA is squarely in the 'game' category,
   rather than the 'reality sim' category, which is good, because it has far
   too much combat for it to treat it particularly realistically.

From. the point of view of 'number of decisions the player makes',
absolutely, we can't afford to micromanage combat, but that has nothing to
do with how accurately we portray various weapons.


   -

   From a gameplay standpoint, creating a strong distinction between long
   weapons which have very low dispersion (good effective range), and
   pistols/smg's with poorer dispersion (shorter effective range) would
   require placing some kind of very dramatic penalty on firing at targets in
   melee range for the former, to the point of making it a desperation
   mechanic - for starters, all aim could be completely lost the moment you
   are attacked in melee, and probably apply a dramatic 'recoil' value as
   well. Maybe also make aiming take a bit longer for the long weapons. If
   none of that gets the point across in terms of distinguishing the weapons,
   then perhaps simply apply a huge hit penalty at point-blank for 2h ranged
   weapons.
   -

   If you want to model 'reality' as closely as possible for 'to hit'
   issues, then gun tracking becomes a major factor as range decreases -
   quickly becoming much more important than dispersion - but you don't handle
   tracking as a variable, so range reduction only benefits the shooter in
   your model.

Exactly, I'm planning on modelling all of that eventually.

**Comment by kevingranade** [comment]
The propoal as stated is moving in the wrong direction, rifles and pistols should not have remotely similar damage output.
