### ISSUE TITLE
Activities that are of ACT_NULL type are still "true"

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#19045]
* Spawn vehicle
* Dismantle it completely
* `activity_handlers::vehicle_finish` will call `veh_interact::complete_vehicle()`, which invokes `g->u.activity.set_to_null()`
* `act->type` is now `activity_id( NULL_ID )`
* `!act` is still `false`
* Game crashes

Pinging @sethsimon who reworked activities.

**Comment by codemime** [comment]
This looks like #19003, but describes the issue far more comprehensively.

**Comment by sethsimon** [comment]
It looks like it was a typo on my part:
`void activity_handlers::vehicle_finish( player_activity *act, player *pl )`
`{`
`.... /** snip (why are spaces ignored?) */`
`....// complete_vehicle set activity type to NULL if the vehicle`
`....// was completely dismantled, otherwise the vehicle still exist and`
`....// is to be examined again.`
`....if( !act ) { // should be *act`
`........return;`
`....}`

`is_null` seems to be working correctly.
