### ISSUE TITLE
ASCII gaming in SDL build is terribly slow

### ISSUE THREAD

**Issue by BrettDong** [CleverRaven/Cataclysm-DDA#19071]
I've had this feeling long time ago, when driving a car in ASCII interface, you can feel the little pause between redraws, but it's quite smooth with tiles interface. Now I checked out DanmakuDan's #19066 branch, and got a shocking benchmark result:

| Interface | FPS(debug) | FPS(release) |
|---|---|---|
| ASCII | 15.971 | 20.008 |
| tiles | 29.338 | 126.673 |

OS: macOS 10.12.1
CPU: Intel Core i5-5250U 2.6GHz
GPU: Integrated Intel HD Graphics 6000

**Edit**: I mistakenly submitted the data of FPS(debug) in tiles.

**Comment by BrettDong** [comment]
![2016-11-01 5 40 24](https://cloud.githubusercontent.com/assets/21075502/19885883/0f715b62-a05c-11e6-9461-dfec0036f307.png)

Is this _normal_? I'm shocked that `draw()` could take up 75% of the time.

**Comment by Coolthulhu** [comment]
Interesting that it's fill rect function that eats up 22% of total time.
Maybe it's not accelerated?

**Comment by DanmakuDan** [comment]
The debug log should mention if the program defaulted to software rendering if it's not already set.

**Comment by DanmakuDan** [comment]
It might be possible to save some rendering time by having all the glyphs on one texture, instead of an individual texture per glyph. Also, if SDL_RenderFillRect is slow in drawing the glyph backgrounds, maybe we could experiment with using a white texture that uses SDL_SetTextureColorMod to alter its background color before each background render.

**Comment by mutability** [comment]
I messed around with putting all the glyphs on one texture; it was maybe fractionally faster but within the measurement noise.

**Comment by mutability** [comment]
The SDL behaviour seems to vary a lot from system to system. e.g. on my system (Ubuntu 16.04, discrete nvidia gpu with offload through the inbuilt intel gpu) SDL_RenderCopy is really, really slow - 10us per call minimum. That adds up rapidly.

Possibly using something like SDL_gpu (https://github.com/grimfang4/sdl-gpu) would help.

**Comment by mutability** [comment]
After some hacking on this, the main major slowdown AFAICS is due to lots of binding/unbinding of textures.

I switched everything over to SDL_gpu and it was just as slow initially. Using SDL_gpu, doing lots of blits from the same texture is fast as they are batched, but interleaving them slows it right down as it has to rebind the texture.

This collection of changes makes wrefresh go much faster:

 * SDL_gpu
 * putting all the glyphs on a single texture
 * splitting curses_drawwindow up into two passes: first, do all the backgrounds; second, do all the foregrounds

Starting from a version that does not have the windowed-inventory-UI fix, that reduced the time taken to redraw the inventory window from ~150ms to ~15ms.

The two passes are necessary because SDL_gpu (and, I suspect, vanilla SDL) disables texturing to fill the rectangle, so if you interleave filling with blitting you are constantly toggling the texturing mode and having to rebind the texture.

There are lots of things that could be done here, e.g. creating pseudo-glyphs for the background colors so you can do it all in one pass.

Terrain map drawing probably suffers from the same, but I have not looked at that in much detail (it was half-broken with my SDL_gpu changes anyway)

Some of this might be useful as a starting point for a less invasive set of changes on top of vanilla SDL. It might be worth trying all-glyphs-on-one-texture plus pseudo-glyphs-for-backgrounds as a starting point.

**Comment by mutability** [comment]
I dumped a snapshot of my SDL_gpu stuff here: https://github.com/mutability/Cataclysm-DDA/tree/sdlgpu_hackery

(it's nowhere near suitable for a PR yet and has changes that shouldn't go in e.g. the CachedTTFFont string -> uint32 thing, but maybe it is a starting point)

**Comment by BrettDong** [comment]
Hi, I tried to compile your branch, but I met the following link error:

Undefined symbols for architecture x86_64:
  "Atlas::null_locator", referenced from:
      Atlas::add_tile(SDL_Surface*, SDL_Rect const*, void
(*)(SDL_Color&)) in sdltiles.o
      CachedTTFFont::create_glyph(unsigned int, unsigned char) in sdltiles.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see
invocation)
make: *** [cataclysm-tiles] Error 1

**Comment by BrettDong** [comment]
Link error solved. But the screen is constantly flickering insanely:
![2016-11-19 5 55 55](https://cloud.githubusercontent.com/assets/21075502/20454641/b863489c-ae81-11e6-8605-d87f520ff98a.png)
![2016-11-19 5 56 47](https://cloud.githubusercontent.com/assets/21075502/20454640/b85c9902-ae81-11e6-8e61-d3649373f491.png)

Anyway I tried to do a draw benchmark, and the result is 67fps, three times more than the original score.

**Comment by BrettDong** [comment]
I saw this in console output:

BrettdeMacBook-Air:Cataclysm-DDA brett$ ./cataclysm-tiles
GPU_CreateTargetFromWindow: BACKEND ERROR - Failed to create GL context.
GPU_InitRendererByID: BACKEND ERROR - Renderer OpenGL 4 failed to
initialize properly

Is this the reason I was seeing corrupted image?

Hardware: MacBook Air, CPU/Intel Core i5-5250U, GPU/Intel HD Graphcis 6000
OS: macOS Sierra 10.12.1

My integrated graphics card supports OpenGL 4.1, but why it is saying
"Renderer OpenGL 4 failed to initialize properly"?

**Comment by mutability** [comment]
The "failed to initialize" is OK - I just have lots of debugging turned on, it will try each renderer in turn. On my system both the OpenGL 3 and 4 renderers fail for some reason. Haven't dug into why since OpenGL 2 is more than enough.

I don't know what's causing the flickering, I've only really tested on one system and it was fine. I did notice that if I switch from the discrete nvidia to the built-in intel graphics here, I lose the menu borders, so there's something a bit nonportable going on.

FWIW: SDL, ASCII, no minimap, 200x60 character window, identical save/view:

master, nvidia: 5.42fps
sdlgpu, nvidia: 52.8fps
master, intel: 4.66fps
sdlgpu, intel: 37.5fps

**Comment by mutability** [comment]
It might be worth trying with localization off (or at least with the regular English locale) as I'm pretty sure I broke some of the wide-character support while meddling with CachedTTFFont

**Comment by mutability** [comment]
@BrettDong: Can you try https://github.com/mutability/Cataclysm-DDA/tree/sdlgpu_basic

This is the minimal set of changes to swap over to SDL_gpu. It will not go any faster than regular SDL (in fact it's probably slower) but I would like to see if it works without flickering on your system.

**Comment by BrettDong** [comment]
OK. Trying to build on my macOS system.

Patch:
```patch
From 9863954796809ef444a7f5fa1922eb7eeaea0d70 Mon Sep 17 00:00:00 2001
From: Brett Dong <brett.browning.dong@gmail.com>
Date: Sun, 20 Nov 2016 18:23:59 +0800
Subject: [PATCH] Revise Makefile to build on macOS

---
 Makefile | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/Makefile b/Makefile
index 23ac3ff..e1d2079 100644
--- a/Makefile
+++ b/Makefile
@@ -460,7 +460,7 @@ ifdef TILES
       CXXFLAGS += $(shell sdl2-config --cflags) \
                  -I$(shell dirname $(shell sdl2-config --cflags | sed 's/-I\(.[^ ]*\) .*/\1/'))
       LDFLAGS += -framework Cocoa $(shell sdl2-config --libs) -lSDL2_ttf
-      LDFLAGS += -lSDL2_image
+      LDFLAGS += -lSDL2_image -lSDL2_gpu -framework OpenGL
     endif
   else # not osx
     CXXFLAGS += $(shell $(SDL2_CONFIG) --cflags)
-- 
2.10.2
```

**Comment by BrettDong** [comment]
@mutability Still very unstable:

![2016-11-20 6 32 20 5](https://cloud.githubusercontent.com/assets/21075502/20462149/d40fddb6-af4f-11e6-92ab-f87f27e8b56b.png)

Unplayable at all. Everything on the screen, even the dialogue closed which should disappear, all leaves on the screen. And all the things twisted into a total mess.

**Comment by BrettDong** [comment]
The screen flickers really fast, even ten times per second. Very chaotic.

**Comment by mutability** [comment]
I think this must be a double buffering problem, the code assumes that the
contents of the previous frame are still in the framebuffer after flipping
but that may not be true with some double buffering setups. Let me get you
a new version in an hour or so

**Comment by DanmakuDan** [comment]
```draw_window``` in ```sdltiles.cpp``` uses its own buffering to decide which characters need redrawing. Disabling the two continues where ```cell``` is being checked would make it always do a full redraw.

**Comment by mutability** [comment]
Yeah, there's lots of scope for doing things better there. For now I just want to make sure that we can get SDL_gpu working properly on various systems before doing a more invasive redesign based on it.

@BrettDong I pushed https://github.com/mutability/Cataclysm-DDA/commit/4486e6d153ae9195ce3c963ca44f0e51ffd69350 to sdlgpu_basic, can you try that and see if it fixes the flicker? (It introduces a separate render buffer, much like the original SDL code, which is a bit wasteful since we're double buffering anyway but that can be fixed later)

**Comment by BrettDong** [comment]
The interface is now stable. No flicker anymore. Display are perfectly
correct. But it is even terribly slower. The benchmark is 3.2fps in
release build.



在 2016/11/20 下午10:13, Oliver Jowett 写道:

**Comment by mutability** [comment]
Ok, great! The slowness is expected, I get similar results, but if the display is correct that's the important thing. Let me get back to you with a new branch in a while.

**Comment by mutability** [comment]
Can you try https://github.com/mutability/Cataclysm-DDA/tree/sdlgpu_fonts
This puts all the font glyphs on a single texture so sdl-gpu can batch-blit them.
I also tweaked how the curses layer finds dirty characters to repaint.
It does not change tiles mode, so that will still be slow, but "ASCII SDL" should be much faster.
It also doesn't touch the minimap code, having the minimap on will halve my framerate here, so please test with minimap off for now.

My benchmark setup (220x60 char window, no minimap) goes from 5.5fps (master) to 32fps with these changes.

**Comment by BrettDong** [comment]
Got a compile error (`-Werror`, a warning in fact) with clang:
```
src/cata_tiles.cpp:128:11: error: moving a temporary object prevents copy elision [-Werror,-Wpessimizing-move]
    tex = std::move( make_texture( 256, 256 ) );
          ^
src/cata_tiles.cpp:128:11: note: remove std::move call here
    tex = std::move( make_texture( 256, 256 ) );
          ^~~~~~~~~~~                         ~
1 error generated.
make: *** [obj/tiles/cata_tiles.o] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by BrettDong** [comment]
Brilliant performance boost! The benchmark result is 74.8 FPS now with minimap on, and 121.2 FPS with minimap disabled.

But to compile on macOS, the following patch is needed:
```patch
diff --git a/Makefile b/Makefile
index 23ac3ff..e1d2079 100644
--- a/Makefile
+++ b/Makefile
@@ -460,7 +460,7 @@ ifdef TILES
       CXXFLAGS += $(shell sdl2-config --cflags) \
                  -I$(shell dirname $(shell sdl2-config --cflags | sed 's/-I\(.[^ ]*\) .*/\1/'))
       LDFLAGS += -framework Cocoa $(shell sdl2-config --libs) -lSDL2_ttf
-      LDFLAGS += -lSDL2_image
+      LDFLAGS += -lSDL2_image -lSDL2_gpu -framework OpenGL
     endif
   else # not osx
     CXXFLAGS += $(shell $(SDL2_CONFIG) --cflags)
diff --git a/src/cata_tiles.cpp b/src/cata_tiles.cpp
index e5251db..d65de37 100644
--- a/src/cata_tiles.cpp
+++ b/src/cata_tiles.cpp
@@ -125,7 +125,7 @@ GPU_Image_Ptr Atlas::make_texture( int w, int h )
 
 bool Atlas::create()
 {
-    tex = std::move( make_texture( 256, 256 ) );
+    tex = make_texture( 256, 256 );
     if ( !tex ) {
         return false;
     }
```

**Comment by mutability** [comment]
I think it's probably at the point where I can turn this into a proper PR then. Thanks for testing!

**Comment by BrettDong** [comment]
The final problem remaining is localize support. Thank you very much for
the amazing performance boom!


在 2016/11/22 下午10:22, Oliver Jowett 写道:

**Comment by mutability** [comment]
The sdlgpu_fonts branch should be OK with localization, can you check?

**Comment by mutability** [comment]
I have exhausted my efforts to get #19412 merged, so we are back to square one here and someone else will need to provide a fix.
