### ISSUE TITLE
Allow to edit github wiki for everyone

### ISSUE THREAD

**Issue by illi-kun** [CleverRaven/Cataclysm-DDA#19090]
Migration of our ```\doc``` folder to wiki pages (started in #18859) allows to update documentation easier (for persons who have write permission) but removes such possibility completely for everyone else.

What about the idea to allow to modify wiki by everyone? Without this, the devs are only persons who can contribute to wiki, and this is unpleasant restriction, IMO.

Ping @kevingranade since it's pretty important change and it seems only Kevin has an access to magic switch of access permissions to wiki.

**Comment by mugling** [comment]
I wonder how GH prevents abuse/spam in that circumstance?

One of the major uses of the wiki should be documenting significant parts of the API so that does restrict somewhat whom outside the development team requires access. Also technically only the developers can update the repo docs anyway (via a merge).

As you highlighted in #19089 there is also the issue that a lot of our documentation is fairly useless and in other cases it is so hopelessly outdated to be actively misleading.

A well structured wiki is likely to attract new contributors but the question is how we get to that stage.

**Comment by Nhatorama** [comment]
A few months ago I did try to get my computer setup for making contributions and I failed miserably. I think I tried both on my Windows and Debian computers (Debian for sure).

I read/used resources from:
https://wiki.libsdl.org/Installation
http://www.wiki.cataclysmdda.com/index.php?title=Developers
http://www.wiki.cataclysmdda.com/index.php?title=Mod_manager
https://github.com/kahrl/gettext-msvc
https://github.com/CleverRaven/Cataclysm-DDA/issues
http://smf.cataclysmdda.com/index.php?topic=1063.0
http://smf.cataclysmdda.com/index.php?topic=1165.0
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/COMPILING.md
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/ISSUES.md
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/CONTRIBUTING.md

**Comment by illi-kun** [comment]
@mugling 
> Also technically only the developers can update the repo docs anyway (via a merge) so this isn't necessarily such a huge difference here.

Yes but in case of storing md files in the main repo, anyone can propose changed via PRs but it's not the case for wiki, I guess.

@Nhatorama sorry to hear that. It seems that further work on 'getting started'-like page is required.
BTW, I wonder why a lot of people try to start compiling the game with all possible features (TILES, LOCALIZATION, LUA, SOUND). It's much easier to start from building of minimalistic version using only C::B IDE (on Windows at least).

**Comment by illi-kun** [comment]
No support to this idea, so closing this.
