### ISSUE TITLE
Killing enemies on terrain where their corpse should be moved, makes the corpse dissapear.

### ISSUE THREAD

**Issue by Oskar636** [CleverRaven/Cataclysm-DDA#19155]
As in the title, when you kill an enemy on a young tree, or an opened window or terrain like that, makes the corpse dissapear instead of moving it onto a tile where items can be stored.

Build 5835

In build 5814 it seems to work properly, don't know about 5833 and 5834

**Comment by Nhatorama** [comment]
:D I was about to make a new issue about it. I killed a hulk while it was inside a window and like you've said it left no corpse or items. Hopefully it won't reappear out of nowhere.

**Comment by Rivet-the-Zombie** [comment]
Smashing windows is bugged as well; the sheets/stick/string/glass isn't dropping.

**Comment by codemime** [comment]
I suspect it has something to do with #18997.

**Comment by Oskar636** [comment]
@Rivet-the-Zombie I suspect it is so, because the items drop onto the window, where normally they would be moved onto a floor, but since this bug exists they dissapear.

**Comment by latogato** [comment]
I found two bugs, maybe they are related to this.
1)  I can't drop my RM11B scout rifle to the empty floor (or any other tile) with the AIM because the "destination area is full". If i drop it with the normal inventory menu then it's gone. I can drop other items without problem.
2) There is a basement in the game where is a dead body with an M60 or a M249, next to a line of sandbags. In the 5835. version, i found this type of basement but there was no machine gun.

**Comment by BorkBorkGoesTheCode** [comment]
I opened an issue at the same time as you. The AUG and SKS are also affected. The shotgun mods appear unaffected.

**Comment by latogato** [comment]
After my post I just saw the fix already on the pull request list, so i deleted my post because i saw it unnecessary.

**Comment by BorkBorkGoesTheCode** [comment]
Oh. Good to know.
