### ISSUE TITLE
Chickenbots special attack appears broken

### ISSUE THREAD

**Issue by pisskop** [CleverRaven/Cataclysm-DDA#19156]
Or at least I cant find the part where it shoots at things and its not shooting at things ingame.

**Comment by keyspace** [comment]
Guess this is about `mon_chickenbot`, "chicken walker", and its `CHICKENBOT` special attack.

**Comment by kevingranade** [comment]
the grenade launcher only fires if it is at range 38, but it now only detects the player at a range of 16 or so.  At some point monster range was rescaled, but the specials weren't rescaled along with it.  A similar situation seems to occur with the rifle.

**Comment by kevingranade** [comment]
The vision thing is due to averaging day and night vision when light level is less than full sunlight, I'm giving the chicken walker some night vision to compensate, which is also  reasonable thing for an attack robot to have.
There were also some bugs in the code to limit the amount of overkill the chickenbot used, one particular clause caused it to only ever select the grenade launcher to attack dangerous enemies, and a check to prevent firing the grenade launcher when too far away to have a chance of hitting was overly restrictive, with the result of never actually firing.
The only reason it even did the fallback to the tazer is it was checked first.
