### ISSUE TITLE
Mounted Machine Guns Should Not Require Cutting Tools

### ISSUE THREAD

**Issue by rtizzy** [CleverRaven/Cataclysm-DDA#19206]
Most machine gun mounts will utilize a quick release pin system of some sort. 

Please review the following. 

https://www.armyproperty.com/Resources/PS-Mag/2004-08/Vehicular%20Machine-Gun%20Mounting%20Systems.pdf

Search for M197 in the following document. 

http://www.liberatedmanuals.com/TM-9-1005-224-10.pdf

**Comment by pisskop** [comment]
Does that cover how to superglue a targeting sytem and a mount onto a vheicle not designed to carry one beforehand?

**Comment by mugling** [comment]
Thumbs down not because the idea is inherently unreasonable but because we make decisions based upon what is fun to play not random links to a document that happens to support a particular point of view.

Long-term I want to move to a system of weapon mounts to which arbitrary guns can be attached and removed without the need for tools

**Comment by Oskar636** [comment]
@mugling Sounds really fun. And I'm also against the idea in this issue.

**Comment by elricsfate** [comment]
@Oskar636 @mugling 

>Thumbs down not because the idea is inherently unreasonable but because we make decisions based upon what is fun to play not random links to a document that happens to support a particular point of view.

Requiring cutting tools for something that should not otherwise require it does not particularly seem fun, nor does it appear to add much to the game play. 

The only thing this really accomplishes is preventing low level starting characters from utilizing said objects until obtaining a cutting tool (Which more than anything, is an annoyance). 

>Long-term I want to move to a system of weapon mounts to which arbitrary guns can be attached and removed without the need for tools
 
What I suggested and what you mention are not mutually exclusive. 

Point being, please demonstrate how this would make the game any less fun than it already is. If anything this is an issue of balance but I'd argue it's a negligible one. 

@pisskop 

You don't superglue a targeting system to a vehicle when utilizing something like a machine gun. The M240, M249, and Browning M2 .50 cal all utilize integrated iron sights or scopes, all of which are mounted on the weapon itself 

The major exception to this rule is in multi gun systems used primarily for Anti-Anticraft roles (For example there as an AA system utilizing 4 M2 Browning) but even these are integrated on the mount itself.

To my knowledge, most of the vehicles with weapons are military so they would utilize a quick detach system. 

You could handle this with different mounting systems or by differentiating in between a "military mount" and a "makeshift mount" for example as @mugling mentioned.

**Comment by pisskop** [comment]
Maybe we should create a mount item to allow for quick attachment of guns on military vehicles?  Kind of like a swappable storage battery and the storage battery case?

**Comment by elricsfate** [comment]
@pisskop

I believe that would be a great way of handling it.
