### ISSUE TITLE
Add Mac OSX download links on main website

### ISSUE THREAD

**Issue by remyroy** [CleverRaven/Cataclysm-DDA#19227]
In the sidebar, in the *Experimental Builds* section, someone should add the links to the Mac OSX downloads directories:

* Console: http://dev.narc.ro/cataclysm/jenkins-latest/OSX/Curses/
* Graphical: http://dev.narc.ro/cataclysm/jenkins-latest/OSX/Tiles/

The main website is http://en.cataclysmdda.com/ .

@GlyphGryph Can you do this? If not, who has access to do this?

**Comment by kevin-at-corista** [comment]
I can do it, hopefully in the next few days (send me a reminder over the weekend), but there should be several people on the project who have access to the servers. I don't know who exactly they would be any more since I'm mostly just providing and paying for the hosting right now and don't really have anything to do with project management - I suppose everyone with access could have moved on without sharing it! I wouldn't know.

So I can change it, but if no one else has access anymore I think that's probably an even bigger priority.

**Comment by GlyphGryph** [comment]
I can do it, hopefully in the next few days (send me a reminder over the weekend), but there should be several people on the project who have access to the servers. I don't know who exactly they would be any more since I'm mostly just providing and paying for the hosting right now and don't really have anything to do with project management - I suppose everyone with access could have moved on without sharing it! I wouldn't know.

So I can change it, but if no one else has access anymore I think that's probably an even bigger priority.

**Comment by remyroy** [comment]
@GlyphGryph Don't forget this please. If you know list the people who has access to modifying the website, let me know and I'll ping them next time instead.

**Comment by BorkBorkGoesTheCode** [comment]
@GlyphGryph The source code download on the main page points to 0.6.

**Comment by remyroy** [comment]
Another friendly reminder for @GlyphGryph

**Comment by GlyphGryph** [comment]
I have done this and a lot of other work I found mentioned in various tickets and by people in the past, so it's really just updating the architecture now

**Comment by GlyphGryph** [comment]
And also you guys should probably try to find someone I can give these credentials too

**Comment by remyroy** [comment]
Piging @illi-kun @mugling @Rivet-the-Zombie @Coolthulhu @sethsimon @BrettDong @codemime :

Who should have access to modifying [cataclysm.com](http://en.cataclysmdda.com/ )? Who would want to take that job? Would it be a good idea to redo the website using something like a simple CMS to make it easier to modify?

**Comment by mugling** [comment]
> And also you guys should probably try to find someone I can give these credentials too

@GlyphGryph you can PM me a set via the forum (username `mugling`). I'd be quite interested in working on some git API hooks that automatically updated the website.

**Comment by GlyphGryph** [comment]
I fixed everything. Baby decided to sleep long, thankfully, and some of the fixes were easier than I expected. So this is done!

**Comment by remyroy** [comment]
Thanks @GlyphGryph .

**Comment by GlyphGryph** [comment]
Mugling, everything on the website that I can imagine would be relevant to the git api hooks already points to the narc server, which is hooked in. What exactly would you be looking for?

**Comment by GlyphGryph** [comment]
Oh wait, actually the primary stable version links aren't. I was gonna do that this time around, but we don't seem to have a single endpoint for latest stables.

**Comment by GlyphGryph** [comment]
www.cataclysmdda.com should now work as well - I think that's all the fixes that were in my queue

**Comment by GlyphGryph** [comment]
Anything else you want me to do while I've got this all working and am in here?

**Comment by mugling** [comment]
> What exactly would you be looking for?

Connect the stats dumper to the wiki

**Comment by GlyphGryph** [comment]
Isn't someone else doing the wiki? I am pretty sure thats one of the things I don't host anymore.

**Comment by remyroy** [comment]
I'm hosting the wiki.

**Comment by mugling** [comment]
@remyroy I see. How would you feel about such a collaboration?

**Comment by remyroy** [comment]
I'm not sure what would be needed but the mediawiki should already have APIs to dump whatever you want. Let me know if you need some permission and I'll add it.
