### ISSUE TITLE
Debug message about mandated special spawns serves no purpose

### ISSUE THREAD

**Issue by pisskop** [CleverRaven/Cataclysm-DDA#19290]
While it complains about too many mandatory spawns, it still manages to spawn several optional spawns and Ive never noticed it to fail to spawn at least 1 mandated spawn.

Its a thrown error that doesnt particularly help.  Nor does it particularly seem to be an issue.

**Comment by pisskop** [comment]
Indeed, its hard to tell what its actually counting, and  if there is/was never an issue in the coregame why was it included in such an abrasive manner?

**Comment by Coolthulhu** [comment]
It counts the sum of mandatory counts of all specials.

Defining extra mandatory effectively specials pushes out some "mandatory" specials into optional ones. This means that the abrasive warning is well deserved: "mandatory" loses its meaning if it can't actually be enforced.

For example, if you want to make sure every overmap contains an evac center, but then request no less than 10k ponds, the evac center will no longer be guaranteed.

The message could possibly be displayed in some different way, but it does deserve to be a big red warning for the designer (not necessarily for players).

**Comment by DangerNoodle** [comment]
I have observed this while testing Mining Mod today. Can we confirm that minimum demanded specials are actually being enforced if under the threshold? I increased the minimum due to signs that minimums were not enforced, frequently seeing overmaps with no sign of veins generated unless the minimum was solidly high.

If I can confirm that a reasonable number is reliably generated when the minimum is reduced from 100 each (which was overkill), then I can safely reduce each to around 5 or so. It would be prudent for @mugling to mention this problem in https://github.com/CleverRaven/Cataclysm-DDA/issues/19376.

**Comment by mugling** [comment]
> It would be prudent for @mugling to mention this problem in #19376.

What is the change though?

**Comment by DangerNoodle** [comment]
I am uncertain. Was there a pull request recently affecting overmap specials?

**Comment by DangerNoodle** [comment]
It seems it is either https://github.com/CleverRaven/Cataclysm-DDA/pull/19223 or one of the prior pull request in that series.

In this case, it would seem that the issue (too many minimums) is pre-existing, but this issue makes it visible to mod authors. They should be made aware of this maximum of minimums (odd as that phrase sounds) so they may test what will stay within acceptable limits.

**Comment by DangerNoodle** [comment]
Any possible way to correct this?

**Comment by pisskop** [comment]
Yea.  Mod authors can overwrite the defaults Like I do.

**Comment by DangerNoodle** [comment]
How so?

**Comment by pisskop** [comment]
https://github.com/pisskop/PKs_Rebalancing/blob/master/pk_overmap_freqloc.json#L1296

Take all of these.  But this line is about the outpost; that bunker with 8 turrets and 4 spotlights that only usually spawn rarely off of roads.  I make them spawn much more.

Essentially I redefine the locations after the coregame loads.

**Comment by DangerNoodle** [comment]
I see. Peculiar. Not sure if that is the ideal solution. I assume it can at least be made more efficient and futureproof by use of `copy-from` so that only the `occurances` section needs to be overriden (see https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/mods/No_Fungi/overmap_specials.json).

**Comment by kevingranade** [comment]
This was invalid to start with, and most of the mandatory misuse seems to have been corrected by now.
