### ISSUE TITLE
Buildbot issue

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [CleverRaven/Cataclysm-DDA#19314]
@narc0tiq intermittently for the last few weeks, the buildbot has been timing out and taking a long time to build PRs.

**Comment by Coolthulhu** [comment]
At the moment it also refuses to build anything due to Makefile not matching the reference one.

**Comment by narc0tiq** [comment]
It's mostly because the mainline builds weren't running at all. Primarily because, despite my asking it to do so, Jenkins didn't restart after installing plugin updates. I've got that part taken care of now, and the PRs should get redone once [build 5885](http://ci.narc.ro/job/Cataclysm-Matrix/5885/) finishes.

Please reopen if it doesn't seem to be fixed within the next couple of hours.
