### ISSUE TITLE
Removable Storage Batteries Require 2 Skill

### ISSUE THREAD

**Issue by pisskop** [CleverRaven/Cataclysm-DDA#19407]
Removable storage batteries shouldnt take any skill to replace and even attempting to mod it to zero difficulty has no effect.

The generic electric car has 2 examples of swappable storage batteries that dont swap

**Comment by keyspace** [comment]
The issue arises 

Relevant commit (from `git blame`): efdb7a2e - moved batteries to separate JSON file.

`data/json/vehicle_parts.json` (where the batteries were defined) had duplication.
`data/json/vehicleparts/battery.json` (definitions here now) uses `copy-from`+`extend`, but doesn't add an overriding `"difficulty": 0` for `storage_battery_removable`.

Pretty sure this is unintentional.

**Comment by keyspace** [comment]
Just checked: adding `"difficulty": 0` to `storage_battery_removable` changes installation difficulty, but not removal difficulty. :/

**Comment by saneman226** [comment]
What I am thinking is that there could be a small chance based on your intelligence (and if you have 0 mechanics) that you could be zapped by the removable storage batteries, and when mechanics 1 is achieved, it would return to normal. Perhaps this would make you think twice about removing highly charged batteries. Also there should not be any skill gained by removing or adding removable storage batteries since it is such an easy task.
