### ISSUE TITLE
Remove duct tape requirement for screwdriver

### ISSUE THREAD

**Issue by Charlesilv4** [CleverRaven/Cataclysm-DDA#19428]
I dont see much logical sense in using duct tape for the screwdriver, we can use strings or rags as a substitute.

**Comment by mugling** [comment]
Without duct tape it's craftable within the first hour which does upset balance somehwat. Same reason hacksaw is a relatively rare drop

**Comment by Blank99** [comment]
it could be made into a 'makeshift' screwdriver, then bump the quality of regular and set ones by 1. Much like you can make a makeshift hammer that's worse than the drop one, or make a wood adze, while an actual wood saw is better.

Independently of that, the duct tape requirement could be replaced by something else that makes more sense from a realism perspective while still retaining the balance. Glue & wood, maybe, or a better tool to get the head right.

**Comment by Charlesilv4** [comment]
IMO the only thing it upsets is the RNG.

**Comment by mugling** [comment]
So how does this actually improve the gameplay?

**Comment by Charlesilv4** [comment]
Unless you like being dependent on the random chances of finding duct tape or a screwdriver, is much better to make one. Also finding a screwdriver or making one is almost equal in pros/cons.
If you are on a city you have a high chance of finding one, but if you like to play with small cities or isolated you have no options but to rely on RNG to be able to progress.
How not being able to make a screwdriver improve the gameplay ?

**Comment by mugling** [comment]
> How not being able to make a screwdriver improve the gameplay ?

Because it's defcto removal of the screwdriver

**Comment by Blank99** [comment]
removal of requirement: it opens some recipes early, like deconstruction, tho nothing particularly powerful since those tend to be gated by either materials, metal sawing, or welding. It makes it a little easier for lab challenge starts to beat it through electrohack if the RNG is being cruel. It allows screwdrivers for wilderness games.

replacement of requirement: the recipe makes more sense, so it's prettier. All for a 1 line change. It may also allow screwdrivers for wilderness games.

Addition of a 'makeshift' quality: it makes sense so it's prettier, and it allows for opening some choice recipes to make the early game more interesting. Regular screwdriver remains attractive.

I do not know how the code handles when you're crafting something and your tools are superior to what you need. IF the code rewards you for this with, say, faster crafting, then the 'makeshift' version allows access to things, while the regular one remains attractive because it gets your crafting speed up,

**Comment by mugling** [comment]
Variable crafting times aren't supported and more makeshift items is just bloat. You can already craft far too much from the materials in the starting shelter. The changes your proposing adjust balance enormously so there isn't much chance of that change being made unless you can demonstrate necessity

**Comment by Blank99** [comment]
That's a little unfair, but perhaps I wasn't explaining myself well enough. The proposals are OR, not AND. Any of the three would solve "this recipe doesn't make sense", how much work it takes and how much impact it has varies depending on the option.

Yes, the 'removal' path lets you make more things at the start. Yes, this alters balance. This change isn't necesarily all that large. The biggest is furniture deconstruction and perhaps one early electronic out of the console, neither of which helps you feed or water your character.

Yes, the 'makeshift' path involves more bloat, but it is not without precedent in other tools (hammer, saw, crowbar), and having a benefit for beating the tool requirement isn't necesary for it, just something that'd be 'nice'. This benefit doesn't have to be of crafting time either, it could be of crafting change.

However, the 'replacement' part has zero balance impact and little to no implementation difficulty. It's a "this doesn't make sense, let's change it with something that does make sense without touching balance beyond minor RNG-proofing, with as little work as possible".

For example, most places that drop screwdrivers also drop hammers. Changing requiring duct tape to make a handle into requiring a good hammer to make the head right makes sense and doesn't change balance.

Alternatively, metal sawing could get you the screwdriver head, it's a much rarer tool so it would have an even lower chance of impacting balance, but it still makes more sense than duct tape.

**Comment by Coolthulhu** [comment]
> For example, most places that drop screwdrivers also drop hammers.

But most early uses for hammer require only a makeshift one, which is much cheaper.

**Comment by Blank99** [comment]
> But most early uses for hammer require only a makeshift one, which is much cheaper.
What I mean is requiring the good hammer, either through hammering 3 or through fine hammering, representing the precision to get the screwdriver head the right shape/size.

**Comment by flitvious** [comment]
Screwdriver is a scavenger's loot, like hacksaw. It should stay so.

Screwdrivers already became more easily accessible with the addition of extra tool items. In 0.C I've crafted screwdrivers, now I never do that, because they are so common.

You can obtain a screwdriver by getting a loot or zombie drop:
* screwdriver or screwdriver set (often)
* toolbox (rare)
* swiss army knife or multi-tool (very rare)

And also you can get duct tape from scavenged stuff:
* Find duct tape (often). Pretty much anywhere in the city, including cars.
* Find and unload duct tape from a basic repair kit (somewhat rare).
* Craft duct tape (never). Needs a book and fab 3, but all components are common (superglue, rags, thread, plastic chunks). Also RNG must really hate you.

**Comment by Charlesilv4** [comment]
There is so much people that play on different settings, not everbody start on a big city.

**Comment by Charlesilv4** [comment]
Sorry clicked on the wrong button.
But like i said having access to the screwdriver early on doesnt change the game balance overral. For the best recipes you still need the screwdriver set.

> You can already craft far too much from the materials in the starting shelter. 

Thats not realy a good point.


> Screwdriver is a scavenger's loot, like hacksaw. It should stay so.

Hacksaw is far more usefull than the screwdriver, wich doesnt affect the game that much unless it is a screwdriver set.

**Comment by mugling** [comment]
OP continuing discussion in http://smf.cataclysmdda.com/index.php?topic=13755.0

**Comment by DangerNoodle** [comment]
This seems rather peculiar. I was unaware that a pull request involving this was already attempted.

If this is still deemed undesirable at present, I can remove my proposed idea from https://github.com/CleverRaven/Cataclysm-DDA/pull/19519 if desired.
