### ISSUE TITLE
Allow forcing inventory menus to be fullscreen

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#19427]
Is there anything the new, scaled, menus offer that the old, fullscreen, ones didn't?

They're pretty disliked on the forums, they make the menu less consistent between uses (ie. pick up more items and you have to look in a different spot) and are less consistent with rest of the UI design than the old ones, where only trivial menus (`uimenu`) and very old menus (NPC dialogue) are centered and small.

**Comment by mugling** [comment]
There was an earlier performance bug that was resolved with them? We could consider a minimum width?

**Comment by codemime** [comment]
I don't mind if we introduce an option to force them be fullscreen.

> They're pretty disliked on the forums,

There are people who like the new menus more. They're just not that noisy.

> Is there anything the new, scaled, menus offer that the old, fullscreen, ones didn't?

The old menus were squashed to the left most of the time (or to the upper-left corner in case of small number of items). Staring at the corner was rather annoying.

**Comment by DangerNoodle** [comment]
Thus far, I do not strongly care about the new menu either way, but I can see instances where the old method might be easier to parse, for the reasons @Coolthulhu stated. Allowing either option might be the best solution.

**Comment by mugling** [comment]
> They're pretty disliked on the forums

I see at present four dissenting posts, one is a brand new account and one is complaining about performance. Notwithstanding that four isn't by any stretch a quorum.

> There are people who like the new menus more. They're just not that noisy.

This is very true. Player feedback is important but the feedback cycle shouldn't just be based upon whoever shouts the loudest because this often selects for a minority opinion.

**Comment by codemime** [comment]
> are less consistent with rest of the UI design than the old ones, 

Correct me if I'm wrong, but I don't recall any other borderless fullscreen menu.

> where only trivial menus (uimenu) and very old menus (NPC dialogue) are centered and small.

I suppose big menus are so for a reason: they always have enough useful information to show. Small, but fullscreen inventories only show vast blackness.

**Comment by Treah** [comment]
The problem occurs when you have a small menu but you have a large list of items.. You are then scrolling though a bunch of things that you wouldn't have to. Size of the interface seams to be directly driven by the width and not the length of the list. Also there are some menus that are full screen and then some that render small that shouldn't. This causes a bit of frustration esp on smaller screens or when playing in a terminal multiplexer like screen. It should not be assumed that all players are playing full screen.

**Comment by codemime** [comment]
> The problem occurs when you have a small menu but you have a large list of items.. You are then scrolling though a bunch of things that you wouldn't have to.

Large lists of items lead to big menus. They're not always fullscreen, but they always occupy all the height available. Which means you don't need to scroll any more that you would in the fullscreen mode. If it's not what you see, it's probably a bug. Please post a screenshot of the entire screen.

> Also there are some menus that are full screen and then some that render small that shouldn't. 

Can you show us some screenshots for a substantive discussion?

**Comment by mugling** [comment]
We should be certain there are both no bugs or possible improvements before adding configuration options. We do the latter too often and it typically results in two incomplete implementations that are both broken

**Comment by kevingranade** [comment]
We're still missing a list of desired features that are supplied by each imementation, this would really help direct discussion and suggest win/win changes we can make.

**Comment by sniperm13** [comment]
Hi everyone. I actually signed up just to put in my 2 cents here. Been playing cdda for a year.

First off, im in favor of the new inventory screen. Its cleaner and less intrusive than the fullscreen inv menu. While bumpy at first, its more stable now (by exp 6023 at least).

Like the others tho, i do get a performance hit when im interacting with my stash. The bigger the stash, the longer it lags. What I've figured out is that moving away from the stash to interact with my inventory solves this (like eating something from my inventory or turning on a light) since it doesn't have to populate the items in the stash into my inventory. Now, I use the advance inventory menu to move things around between stash and inventory even with the old inventory back when. So, I mainly use the inventory screen when I need to interact with an item. Even with the old fullscreen inventory, direct interaction with an item in the stash is clunky at best since you have to essentially "tab" to each stash and more often than not is less intuitive than putting the item into your inventory then interacting with it.

Now i know, this may not be how others play... but I have a suggestion. Would it be possible to make a switch in the options menu that allows the inventory screen to NOT to populate with the items around you? I think this would practically eliminate the lag caused by the stash during inventory interactions.

**Comment by Barhandar** [comment]
Agreed, an option to force the inventory to be fullscreen would be great, as well as option to skip area search (perhaps a different button to open inventory + in-world item list?). I am very annoyed by the microscopic new inventory menu, and if it still _scales_ based on amount of items in it I will outright hate it for reasons stated by Coolthulhu.

**Comment by Barhandar** [comment]
Issue still present, UX still bad due to needing to regularly change where you're looking for the same items or effectively have Hoarder trait without Hoarder trait.
