### ISSUE TITLE
Engine toggling disabled

### ISSUE THREAD

**Issue by Regularitee** [CleverRaven/Cataclysm-DDA#19436]
Upon starting up a vehicle, it will sometimes not give you the option to control individual engines at all. The game also fails to remember the last used engine configuration. (It properly did in the previous week's version of experimental)

Also, and I'm not sure if this second part is a bug or intentional, but there no longer seems to be the ability to run more than one engine at once (even if they're identical). The only time you can run multiple engines at once is when the above bug happens. I didn't create a separate issue for it since I didn't know if it was intentional or not. 

![engines](https://cloud.githubusercontent.com/assets/8593513/20595594/b42e8696-b1f7-11e6-8759-8a182ff16336.png)

**Comment by codemime** [comment]
The second part is #19346.

**Comment by Blank99** [comment]
I don't know if it's the same bug, two bugs, or a different one:
When the above happens to me, the vehicle plain refuses to start at all, all engines are set to activate, but nothing does. The only way around it seems to be to go around uninstalling and installing an engine.

Happened on a vehicle in which I installed pedals to charge up the battery in order to get it to start,

**Comment by mugling** [comment]
Can reproduce
