### ISSUE TITLE
Enhanced Hearing bionic multiplies your own sound output

### ISSUE THREAD

**Issue by Regularitee** [CleverRaven/Cataclysm-DDA#19443]
For reference, in my case I'm using a character with "light step" which normally reduces step sound to 3. When Enhanced Hearing is toggled on, this increases to 12. Obviously, this is suggesting sound from footsteps is quadrupled in this particular case.

I'm not sure if this bug is just a misleading display by the "Sound" display in the UI, or if the game is genuinely multiplying your actual noise for the purposes of enemy detection.

**Comment by illi-kun** [comment]
Why it's wrong? You hear your steps better (as louder sound).

**Comment by Regularitee** [comment]
The "sound" indicator is supposed to be a measure of how much noise you make, and not the ambient sound level, isn't it? Otherwise it would pick up other NPCs' actions when displaying a number.

**Comment by saneman226** [comment]
If you are using that hearing bionic, then you will most definitely hear your footsteps be louder. The number is of the noise level you make from what you hear. So since you make 3 noise and you have enhanced hearing, you hear 12.

**Comment by NickGrease** [comment]
> If you are using that hearing bionic, then you will most definitely hear your footsteps be louder.

I've always been under the impression that the Sound indicator in the UI is the Sound you make, not the sound you hear. The yellow footsteps (in Tiles) represent sounds you hear, and with bionics you should be able to see/hear the footsteps from farther away. It makes no sense for the UI to display the relative sound you *hear*, as it has no in-game purpose, but displaying the sound value you *make* does serve a purpose, as it allows you to figure out if a creature is likely to hear you, and give chase.

**Comment by saneman226** [comment]
If the indicator is of the sound you make and it shows 3 with the bionic, then it would be a measure of how much sound was made by the character for that tile relative to all the zombies in the area. The same can be said for a zombie making the noise, the zombies indicator would be 5 for example, but the players hears 20 w/ bionic. I suppose the indicator should be for the sound you make then. But I can also he several uses for a hearing indicator rather than the yellow steps.

**Comment by Karlieb** [comment]
I was having problems with zombies not hearing noise I made when I was deaf as well. It seems like the video camera issues where if I could see them through the camera they could see me.

**Comment by tswood** [comment]
The sound display is currently affected by any player sound modifiers, bionic or otherwise, and only takes into consideration sounds that are coming from the same tile as the player or immediately surrounding tile.

It seems like the major confusion is around the original intent of the sound display on the UI.  If it is to be the player's sound as perceived by the player, then it's fine as is. However, if it's supposed to be a raw sound generated by the player to give indication of how generally loud they are being regardless of how their character perceives it, then it could probably be changed. I think it's fair to still have it be nothing when truly deaf.

**Comment by Toybasher** [comment]
Can someone test it by making a test NPC that reacts to sound from the player? 

Do we know if the display actually effects the volume of the sound? I.E. if you're deaf, do zombies not hear your footsteps?

Behavior is fine if it's perceived sound by the player, though. I noticed when using an MP3 player I couldn't hear my own footsteps when walking. (Realistic, yes, but the question is, is the actual sound volume effected, too? Do zombies also care if you're deaf, similar to #13491?)

**Comment by kevingranade** [comment]
Based on what has been posted this is working as intended, the display is the *subjective* volume of the loudest noise you made during the previous action, so if you have enhanced hearing it's apparently louder.

Feel free to test with a zombie or NPC and track the distance at which they detect you via sound, and if that isn't working as expected reopen this issue or a new one.
