### ISSUE TITLE
modded tools can't be used in recipes

### ISSUE THREAD

**Issue by BrainDamage** [CleverRaven/Cataclysm-DDA#19457]
modded tools can't be used in recipes when the recipe calls for the tool name explicitly instead of checking charges 
steps to reproduce:
cheat yourself fabbrication 3 and handguns 3
wish for the handloader's helper, ups, 3 sets of batteries, hand press and die set, ups conversion mod
read the handloader's helper
check crafting menu for handloaded ammo which requires hand press as tool ( eg reloaded 9x18mm P+) and both tool and charged tool requirements are satisfied
attach the ups mod to the hand press, reload the ups with the batteries, and wait for the hand press to be charged
check the crafting menu for the same item
now the tool requirement won't be satisfied, but the tool charged requirements will be

i suspect it's due to the fact that ups modding changes the name and the tool checking checks for exact name

**Comment by mugling** [comment]
Know cause, fix is relatively simple

**Comment by Night-Pryanik** [comment]
Can't confirm. Tested on latest experimental as of 06 April 2019.

Since hand press & die set is no longer has charges, it isn't moddable anymore, so I UPS-modded a hotplate (which is required for the recipe) and charged it in a recharger.
![изображение](https://user-images.githubusercontent.com/11132525/55670255-3ab6b500-5893-11e9-9e99-644df176010b.png)

Then I checked the recipe, and the tool requirement is satisfied by my modded hotplate.
![изображение](https://user-images.githubusercontent.com/11132525/55670283-95501100-5893-11e9-9691-f8a615ee9db6.png)
