### ISSUE TITLE
Add Cache to the inventory_selector so it only repopulates the menu when there is reason to 

### ISSUE THREAD

**Issue by jasonmbrown** [CleverRaven/Cataclysm-DDA#19452]
I was hoping someone would be able to add a cache to the Inventory_selector from inventory_ui.cpp. I have noticed alot of lag when trying to consume items directly around the player if you have piles of junk food.

My thoughts were there should be a check on the players action, and if its the same action to use the cache instead of having to repopulate the entire menu.

Similar thoughts on the crafting menu.

I attempted to add this in myself, But got super lost. It doesn't really become an issue until super late game when the hoarding player has piles and piles of stuff. However When Im trying to quickly Consume food on the ground by mashing "E" and "Enter" theres a good 1-2 second delay between each consumption of food. 

Same Idea with food crafting, there is about a 10-15 second delay (Per Menu "<",">" Once you start collecting enough items to craft anything you want)

**Comment by codemime** [comment]
Adding a cache to each menu isn't a particularly good idea: that would barely mitigate the issue, but would increase complexity, duplication, and add unnecessary state (a reach source of bugs). The real cause of possible slowdown is that piles of similar items aren't stacked on the map (one item -> one object, 1000 items -> 1000 objects) and they have to be "restacked" whenever they get shown. Storing them initially stacked would be a much better idea IMO.

**Comment by mutability** [comment]
This is one of those suggestions where it pretty much needs a proposed implementation (or a skeleton of one) to be any use - the devil is in the details.

**Comment by Coolthulhu** [comment]
My implementation (the one with id cache) would speed up the calculations by order(s) of magnitude (sometimes plural) to the point where cache shouldn't be needed.

The problem here isn't caching the individual recipes (even though multiple tricks could be used to speed it up) but the fact that for every single recipe, the cached inventory is linearly traversed until enough ingredients are found or the inventory is fully processed.

**Comment by codemime** [comment]
@mutability Which one?
@Coolthulhu Your PR is good for the crafting menu, but the plain inventory requires traversing all adjacent items.

**Comment by mutability** [comment]
@codemime I meant the OP's suggestion

**Comment by Coolthulhu** [comment]
While persistent caches (more than one turn) are very risky business, we could have a particularly weak kind of cache here by marking it as dirty on any item manipulation that potentially invalidates pointers (spawn item on map, inventory or vehicle - basically anything that could trigger active items).
This would be enough to avoid rebuilding the whole inventory every time an item is eaten from the stack, but not if the last item from the stack is consumed.

Though to keep the caches light, they shouldn't encompass the whole map/vehicle, but only the nearest 9 tiles.

With those assumptions, a cache of this kind could be just plain item pointers or item locations. If stored as list, they could be spliced in constant time. Otherwise copying pointers/`item_location`s is still much faster than reconstructing them from actual data. Or we could take a mandatory cache route and just treat the cache as naturally "fractured", with the code expecting a vector of sub-caches (per-tile).

**Comment by AMurkin** [comment]
Maybe for recipes in crafting window, first simple change to reduce lag, could be shifting first tabs with all recipes in category at the end of tab lists?

**Comment by kevingranade** [comment]
This suggestion doesn't get us any closer to a solution, we need an implementation.
