### ISSUE TITLE
Salt water in vehicle tanks can't be cooked with

### ISSUE THREAD

**Issue by anonner** [CleverRaven/Cataclysm-DDA#19453]
Unlike regular water, salt water cannot be stored in vehicle tanks and used in cooking recipes.

**Comment by mugling** [comment]
Can regular water be used from tanks? That is interesting

**Comment by Coolthulhu** [comment]
Clean water can be accessed with faucets. Non-clean water and other liquids can't be accessed without siphoning.

**Comment by mugling** [comment]
Faucets add nothing to gameplay. Any objections to allowing crafting using vehicle liquids and drinking from tanks via the interaction screen?

**Comment by Greiger** [comment]
I wouldn't be completely opposed, but wouldn't it be odd that you can get liquids from tanks with crafting but need a rubber hose to drain it otherwise?
Maybe if some tanks just worked if they had faucets built in and others like Gas or diesel style vehicle tanks did not?

**Comment by saneman226** [comment]
All tanks that you want to use in crafting should have an easy-to-access faucet, otherwise you would be required to have the rubber hose to get to that liquid. So I do object to getting rid of faucets. :D

**Comment by Coolthulhu** [comment]
> Faucets add nothing to gameplay.

They add the ability to drink from a tank that is distant without approaching it.
Combining position and function - like in current funnels - is a bad thing so far, as evidenced by water purification annoyance. "Role" is better than position.

> Any objections to allowing crafting using vehicle liquids and drinking from tanks via the interaction screen?

Then we should either drop the requirement of a hose for siphoning or disable this new option when hose is not available. Otherwise it would be inconsistent.

**Comment by mugling** [comment]
We could/should drop rubber hose. Given how available they are I don't think they add anything?

**Comment by anonner** [comment]
I do appreciate the realism that the faucet/hose add.

Perhaps a compromise of ease/realism would be attaching a hose to each tank in order to make the contents available for crafting? With that, the faucet could be left as is. You'd essentially be requiring some ghetto plumbing in your vehicle in order to craft with tank contents.

**Comment by mugling** [comment]
@illi-kun can you expand on why?

**Comment by saneman226** [comment]
The faucet adds the ability to react with the tank easily and effectively without the use of additional tools for getting the liquid. The rubber hose is useful for transferring liquids from and to tanks that don't have faucets. For example, the gasoline tank in cars don't have a faucet and can only be refilled from a hole on top of the tank, nothing on the bottom to pass the liquid through.

**Comment by illi-kun** [comment]
@mugling 
- Using hose for siphoning fuel adds some desired difficulty for beginning of vehicles use (without it, it's much easier to gather fuel from one vehicle and apply it to another)
- Requirement of hose enforces new players to find a source of it (exploration is good, right?)
- Breaking fridges for getting hose may attract zombies (and beating them can be a challenge for beginers)
- It's reasistic because you're not possible to siphon fuel from attached vehicle tank (it's pretty minor argument actually);

**Comment by mugling** [comment]
@illi-kun ok, can we reduce the spawn frequency of hoses somehow though as at present it's just an arcane piece of knowledge a new player must acquire (smash fridges) with no real challenge

**Comment by Zireael07** [comment]
@mugling: Do we have other ways to acquire hoses other than fridges? Because well, if we reduce spawn frequency without other ways, then the player is forced to rely on smashing fridges trick...

**Comment by mugling** [comment]
@Zireael07 not that I am aware of. Suggestions?

**Comment by Coolthulhu** [comment]
> Using hose for siphoning fuel adds some desired difficulty for beginning of vehicles use (without it, it's much easier to gather fuel from one vehicle and apply it to another)

Not really, it's just 2 cups worth of trivially obtainable tool. Every single house has a fridge and every fridge has a hose.

> Breaking fridges for getting hose may attract zombies (and beating them can be a challenge for beginers)

It would need to have 50+ noise to matter. At 27 noise, it goes barely past 1 overmap tile radius.

> EDIT: Ideally a less common furniture than fridge

Washer and broken wending machines have them.
But fridges are currently considered the primary source of hoses. We don't have a sensible tutorial, so common items shouldn't be hidden.

**Comment by mugling** [comment]
If we drop the `hose` requirement for crafting via tanks I can close the issue with salt water PR's today? Although inconsistent it's probably more consistent than allowing water but not other liquids?

**Comment by Zireael07** [comment]
@mugling: I think I remember seeing a suggestion that smashing/disassembling vehicles should spawn hoses (otherwise how does the fuel get from the tank to engine? :P).

Also, hardware stores, maybe?

**Comment by Coolthulhu** [comment]
As for the tanks themselves, would it be possible to conditionally allow using vehicle liquids if there is a hose in the crafting inventory?

**Comment by mugling** [comment]
> As for the tanks themselves, would it be possible to conditionally allow using vehicle liquids if there is a hose in the crafting inventory?

Yes, I did initially try this - it's doable but very ugly. I'm not sure adding more complexity to an already problematic subsystem is a good idea. I'm also not certain from a UX perspective that it's actually intuitive as opposed to just being an arcane fact the player is forced to remember.

**Comment by Coolthulhu** [comment]
It's far less arcane than, say, the requirement for a boom crane to be adjacent to the player to work.

Is there a cleaner way? Having to install a separate faucet for every type of liquid is not a good idea. Water faucets being limited to water made sense when water tanks were just water tanks, it doesn't make sense for generic tanks.
The best option I see would be allowing the faucet to dispense any liquid from any tank, then have the presence of a faucet in crafting range include all liquids in the tanks.

**Comment by mugling** [comment]
> It's far less arcane than, say, the requirement for a boom crane to be adjacent to the player to work.

?? relevance?

> The best option I see would be allowing the faucet to dispense any liquid from any tank, then have the presence of a faucet in crafting range include all liquids in the tanks.

This is trivial to implement either after, or most probably with #19497

**Comment by Coolthulhu** [comment]
> ?? relevance?

Crafting inventory building weirdness (same category) that you approved (wrote) despite it being much uglier and less necessary than what we're talking about right now.
If boom crane adjacency special case is OK, then hose special case must also be OK.

Badly communicated is less bad than hard to use. At the moment to use tank's contents, you need to drain the tank into a container first. This is actually less intuitive than allowing using all contents, because clean water is an exception to this unwritten rule.

**Comment by mugling** [comment]
#19497 is an unsolicited PR that fixes a significant flaw (duplication of `water_clean`) and could potentially be used to close this issue. The discussion here seeks the opinion of yourself and @illi-kun about what we should do with `hose`.

Closing bugs and seeking consensus with the other developers isn't grounds for a snark.

**Comment by illi-kun** [comment]
I'm pretty happy with the current role of hose and I don't think we need do something with it now. I agree that Coolthulhu's proposition with hose in inventory is quite ugly but I have nothing better in my mind.

**Comment by saneman226** [comment]
The way the hose should be thought of should be that it is simply a tool used to gather liquids from cars or pumps. The faucet is for a more established player. If the problem here is that he host spawns too regularly, you can simply lower the chance of drop by saying that breaking the fridge could "damage" the hose and render it unusable. The rubber hose is also a source of plastic chunks for an early game character. Other than the problem of having a low number of uses and a high rate of spawn, I see no problem with the realism provided to us by having the rubber host present within the game.

**Comment by Tharn** [comment]
You can also get water from a vehicle through its chemistry lab. I don't think hoses or faucets should be removed. In fact I find the rubber hose thing rather elegant. It's realistic and it adds a sense of accomplishment plus an early risk/reward decision when you're trying to acquire one.

Tanks built into vehicles don't magically dispense their goodies. They're meant to be tapped through hoses, faucets or appliances that tie into the tanks. If water can be accessed from vehicle tanks without any tools or extras, that ability should actually be removed.
