### ISSUE TITLE
Discussion: Armour thickness

### ISSUE THREAD

**Issue by Regularitee** [CleverRaven/Cataclysm-DDA#19537]
So, what it says in the title: why not add varying thickness to vehicle-mounted armour plates? Such a system adds depth without significant complexity (particularly if it's kept to simple scale of light, medium, and heavy). It would also make the design process more involved and realistic, since  you could add heavier armour to the most front and save weight by reducing armour in the rear. And you can finally add a bit more armour to the sides of a vehicle without it becoming wider than the street.

Not to mention it would also much better fit the post-apocalyptic setting in that you could apply applique or makeshift armor, rather than only using military-grade plating when you want something heavier. And it better matches the gameplay balance of personal armour (which also lets you add multiple layers of clothing and armour, at the cost of decreased stamina and agility).

Thoughts, anyone?

**Comment by mutability** [comment]
Can't you already put another layer of armor on your vehicle by.. putting another layer of armor on your vehicle? (i.e. another ring of frames)

**Comment by Regularitee** [comment]
The current system can lacks flexibility. If I use a 0, 1 tile, or 2 tile thick hull, they have me 0% armour, 100% armour, and 200% armour. There's no real gradients for choice; It's like if personal armour only let you choose between cloth, and full metal plate armour.

It isn't strictly needed, but by the same reasoning we don't really need 8+ different types of tires, or 6+ types of vehicle batteries. It's just something nice to have and add to the degree of customisation.

**Comment by mutability** [comment]
I don't think this is worth it without nontrivial changes to the code. With the current setup you'd need to triple the number of armor parts (and invent corresponding base items) and the only thing that could really vary would be mass and durability, neither of which affect the effectiveness of the armor (effectiveness is based on material density)

**Comment by Regularitee** [comment]
Actually, the code modification would be pretty easy. You can just re-name the current armour plates to medium armour plates. Then create light and heavy variants, and their recipes (all of which can be done by copying the current code, and tweaking the stats). No major code changes required.

**Comment by mugling** [comment]
That just item bloat

**Comment by mutability** [comment]
>
> Actually, the code modification would be pretty easy. You can just re-name
> the current armour plates to medium armour plates. Then create light and
> heavy variants, and their recipes (all of which can be done by copying the
> current code, and tweaking the stats). No major code changes required.
>
That is exactly what I meant about it being a bad idea without nontrivial
code changes. You've tripled the number of armor parts and underlying items
for no good reason, and the only difference between them is they might have
different durability.

To do it properly would need (for example):

 * a better interface to let the user select armor variants, not just a
bunch of new parts in the (already way too big) list of vehicle parts;
 * support for having something other than a 1:1 mapping between vehicle
parts and items used to construct them, so that (e.g.) you can say "heavy
steel armor needs 4 steel plates" rather than having to have a separate
item for each variant that only exists to support the vehicle part;
 * changes to the collision code so that the different armor thicknesses
actually _mean_ something, not just "you can run over 20 zombies before the
armor breaks, rather than 10"

Which is all possible, but not trivial.

The best way to demonstrate that "the code modification would be pretty
easy" is to do the modifications and push them for review.

**Comment by BorkBorkGoesTheCode** [comment]
> * a better interface to let the user select armor variants, not just a
bunch of new parts in the (already way too big) list of vehicle parts;

Nested menu for armor variants?

**Comment by Regularitee** [comment]
Ah, I didn't realise that the game only allowed one item per vehicle part during construction. But in all fairness, the item bloat by having to go [components -> whole item -> installed vehicle part] instead of [components -> installed vehicle part] is an issue with every single part in the game, not just theoretical armour subsets. 

Admittedly, trying to rebuild the vehicle construction system is beyond me right now, so what do you think of simply limiting variable thickness to alloys? Specifically, steel, military composite, and superalloy. Creating thickness variants for just the alloys: steel, military composite, and superalloy. That's six new vehicle parts, plus six new corresponding items to make said parts. I should be able to make that, assuming that isn't too much item bloat to be acceptable.

As to armour effectiveness being based on density, how do you mean? Does the game engine automatically create damage resistance (which I think you mean by armour resistance?) as a direct function of the armour's weight? Or does it draw up fixed numbers from a materials table.

I'm just spitballing ideas here, so if I assume wrong or am suggesting anything unreasonable, please let me know.

**Comment by mutability** [comment]
The primary reference for this is, for better or worse, the existing source
code.

**Comment by 321nick** [comment]
i like this idea a lot! maybe it could be a simple addition where you can put an armor plate on normally, but then you can add onto that tile another extra armor plate vehicle part, like how you can put a seatbelt on a seat once you place down the seat. so 1 armor plate with no additional armor plates is like, not too much armor, but you add more plates, add more weight, add more armor. simple, and it shouldnt cause item bloat because the option of adding additional plates would only be available if a plate is already present.

**Comment by mugling** [comment]
The only two ways of implementing this is adding more items or reworking the code. The former is item bloat (just adding more of the same with slightly different stats). The latter requires actual code changes which isn't likely given the current focus is on fixing bugs and getting a release out.

Asides in almost all cases an extra ring of frames is more useful. If anyone wants to try and define a good implementation of variable armor it could get looked at after `0.D`.

**Comment by 321nick** [comment]
well, item bloat isnt _that_ bad is it? its just more items.

**Comment by mugling** [comment]
```
1mm steel plate
2mm steel plate
3mm steel plate
4mm steel plate
...
56mm steel plate

etc.
```

Adds precisely nothing to make the game more fun but does:
* Bloat all the menus (enjoy paging through all those meaningless choices)
* Slows down item lookup (already a problem)
* Makes maintenance work more difficult (we are approaching half a million lines of JSON).

'It's just a few more items' it's usually a good metric for an idea that is poorly conceived and will be abandoned shortly after being added.

**Comment by 321nick** [comment]
what you provided an example of is not what i had in mind, i was thinking, you have a couple new items at most, like, a thin plate, you get a couple of them from cutting a plate of some other material, like you could get thin steel plates, or thin wooden plates, etc, and you could say, start at your standard armor plate that you usually use to cover vehicles in, then you could add up too 1 or 2 thin plates. the only new items would be the thin versions of all the standard plates. you would use it too add an aditional layer, hell, you dont even need the new plates, just add a extra armor plating car part, that costs the plate, so an additional steel layer would just cost a steel plate, although i havent played in a while so pardon me if im using wrong terminology for it, but there are steel or metal plates , right? just have extra steel plate be a car part that costs 1 steel plate, and can only be added on parts where steel armor already is. thus, it is simple. and it makes sense, because if we have this for all the material varietys, like with the miltiary alloy ( i think thats what its called, its green on the vehicle construction GUI) then armored military vehicles could have extra armor in the front, like in real life, instead of the same armor everywhere.

**Comment by mugling** [comment]
> i was thinking, you have a couple new items

See again:

> 'It's just a few more items' it's usually a good metric for an idea that is poorly conceived and will be abandoned shortly after being added.

This isn't a new mechanic your proposing here - it's just more item bloat.

The vehicle part installation UI is already pretty bad and vehicle armor is badly balanced. Adding more almost-identical items isn't going to help either

**Comment by 321nick** [comment]
did you read the second half? it details how you don't even need new items- just allow a new car part, which i assume is not what you mean when you say items, that takes the _original_ item used for making the armor plate car part, that adds an additional armor plate of equivalent size and, i assume, durability or health, to the original plate, or too the tile itself. it would alloy for extra armoring, without a new ring of frames just for armor, which can make a vehicle too big for certain purposes, like, fitting it in a garage or something.

**Comment by mugling** [comment]
> did you read the second half?

Yes, but please condense and/or punctuate your comments.

> just allow a new car part,

This is also bloat (especially of the already bad vehicle UI). Also requires code support to stop you adding endless layers and/or enforce some kind of ordering. That also adds complexity for no significant improvement in gameplay.

**Comment by saneman226** [comment]
I do not like the idea of adding any new items into the game. I do however think that adding something like "Military Plating w/ rebar" or "Reinforced Spiked Plating" that do add the depth that you desire and keep bloating to a minimum.

**Comment by 321nick** [comment]
> Also requires code support to stop you adding endless layers and/or enforce some kind of ordering

i thought that was simple to do. but maybe you are right.

**Comment by warriorsofcats** [comment]
Why not you add the modifiers to the armor plate. For Example, you put on the standard armor plate on a car, then you want to make it thin or thick or whatever. The game would just add a modifier ([Thick] or [Thin]) to the standard armor plate and then the game would knows to change it durability and health according to the modifier.
Do you guys have something like this in code. If not is it simple or hard to add it?

**Comment by saneman226** [comment]
It would be difficult to add in the way you are saying @warriorsofcats . The thick modifier could simply be 2 plating items. However, this would be a problem the way the vehicle layering is setup, the "layers" allow only 1 item to be on that layer. There would need to be another layer dedicated to secondary armor like you are saying. 
Now the thin modifier that you are talking about would need to be something like 1/2 of a full plate. Without adding any new items, this is impossible to do.  
The devs are trying to keep unique items down to a minimum while they fix other major bugs. Like mugling said, he wants to keep item bloat at a minumum. This discussion is going to be dead to the devs until everything gets more stable. :D

**Comment by warriorsofcats** [comment]
I'm pretty sure you misunderstood my idea but I'm willing to wait until this game is more stable before any idea gonna get toss around.
