### ISSUE TITLE
Firelighting difficulty and weather

### ISSUE THREAD

**Issue by sick-trigger** [CleverRaven/Cataclysm-DDA#19554]
Starting a fire when it's raining should have some difficulty attached to it

my brain is jumping to this huge, awful system with a thousand variables based on: 
- what you're using to light the fire
- what materials you're trying to light
- what your morale is etc.

_You can ignite a rag in this thunder storm with your fire drill but we're going to take control away while you stand still for 8 hours!_

but ultimately it should just be a check of **' it's raining -> player is outside -> 'not right now' '**
the magnifying glass pretty much already does something like this

ploease discuss

**Comment by DangerNoodle** [comment]
I suspect that any such system runs the risk of causing player tedium and annoyance for no meaningful contribution to gameplay balance. The magnifying glass only has this check partly because you outright cannot use it without sunlight, and partly to balance their being the only overtly limitless source of firestarting.

In contrast, separating situations where a friction fire is outright impossible versus merely difficult would be more complex, and of questionable gain.

**Comment by Leland** [comment]
The fact that weather extinguishes fires serves the purpose well enough already, to me.
