### ISSUE TITLE
New action menu incorrectly shows action for Atomic Lamp

### ISSUE THREAD

**Issue by saneman226** [CleverRaven/Cataclysm-DDA#19573]
![capture2](https://cloud.githubusercontent.com/assets/12336871/20785516/81cf1f2c-b76e-11e6-9daa-46089a9a1cd9.PNG)
This shows correctly that the atomic lamp would be "turned on" (show light) if I uncover it.
![capture](https://cloud.githubusercontent.com/assets/12336871/20785522/86485032-b76e-11e6-9054-5fd1bd8ee6da.PNG)
This should show "Turn off" (cover it) as the option of it"

Instead of using "Turn on"/"Turn off" for this, could we simply make it "Cover"/"Uncover" as the item would suggest?

Also with the Caffeine pill, it shows that you "Drink" it rather than consume it like the aspirin, multivitamin or the tramadol.
![capture](https://cloud.githubusercontent.com/assets/12336871/20785744/c62d6b1e-b76f-11e6-952a-e44de90e386b.PNG)

**Comment by saneman226** [comment]
Also with the Caffeine pill, it shows that you "Drink" it rather than consume it like the aspirin, multivitamin or the tramadol.
![capture](https://cloud.githubusercontent.com/assets/12336871/20785625/2cfad3fa-b76f-11e6-8f6c-85ca52d7a44f.PNG)

The flares should also be something like "Light" rather than "Turn on" because it can't be turned off when activated.

**Comment by codemime** [comment]
There are far more items that show "Turn on" for no reason.
Yet it's not something introduced with the new action menu (in contrast, the problem was slightly mitigated there: see 9a479a8ef75a6a9c884ac55be27fe9250283f0fd). The fix is relatively easy: each item with `"use_action"` being `"transform"` should have an appropriate`"menu_text"`:

```json
"use_action": {
    "type": "transform",
    "menu_text": "Cover",
```

Otherwise it would show the default "Turn on".
