### ISSUE TITLE
Reinforced items, damage error?

### ISSUE THREAD

**Issue by Regularitee** [CleverRaven/Cataclysm-DDA#19575]
I'm not sure if this is normal as far as the game goes, or is genuinely a bug, so someone clarify if possible. 

Updated from version... I think #5975 or #5976 (according to http://ci.narc.ro/view/Cataclysm-DDA/job/Cataclysm-Matrix/changes ) to the most recent version. Caused a bunch of items to vanish.

All the items in question were items that had been reinforced via tailoring kit or welder, and had the line 

"damage" : -1.000000e+000," 

in the save file.

**Comment by mugling** [comment]
Can you please upload that save to github

**Comment by mugling** [comment]
I think we have a serialization bug for floats

**Comment by Regularitee** [comment]
I ended up manually editing the save files to remove the damage modifier, to restore my inventory. (The items were still listed under my character's inventory according to the text I edited, but were invisible in-game due to the damage thing). I probably should have copied the save for debugging before editing the save and continuing to play, sorry.

**Comment by mugling** [comment]
Presumably reproducible by someone else? Tentatively may depend on locale settings?

**Comment by Coolthulhu** [comment]
> "damage" : -1.000000e+000,"

The comma was inside the quote? That would be really bad.

**Comment by mugling** [comment]
It looks like a bad copy-pasta though as there's no leading quote? The save really is essential here. Hopefully someone can reproduce - please include what locale you are using (where are you in the world and what language are you using)

**Comment by mugling** [comment]
We're currently serializing via `std::scientific` whereas I think we actually want `std::fixed`. The float deserialization code is nasty - I don't know why we aren't just using stringstreams?

**Comment by keyspace** [comment]
Can't reproduce with `LANG=en_US.UTF-8` (dot separator) or `LANG=fr_FR.UTF-8` (comma separator). Testing on Arch Linux, NCurses version.

* world created on 9bf4dbb (matches release 5976) with default settings
* started new random character
* wished for tailor's kit, rags, leather patches
* wished for tailoring skill
* reinforced: first worn item
* padded with leather: second worn item
* then opened with ea28c5b (current latest master)

The items are still displayed in inventory (with either locale).

Reinforced items do have `"damage" : -1.000000e+00,` - but it appears after reinforcing, as expected, and doesn't change after loading in the newer version (with either locale).

Here are the .sav files (these are from separate games/worlds), but they're useless, since they don't reproduce the issue.

[en.sav.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/625509/en.sav.txt)
[fr.sav.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/625508/fr.sav.txt)

**Comment by Regularitee** [comment]
My particular game build was the windows tileset. 

It's also worth noting that I had the left the game running overnight prior to upgrading my game version, so it's possible that running very long before saving the game contributed to the errors, which only popped up when the game was re-loaded after the update.
