### ISSUE TITLE
JSON linter missing contexts

### ISSUE THREAD

**Issue by Cyrano7** [CleverRaven/Cataclysm-DDA#19586]
Getting errors when using the web linting tool. 'Unmatched context'

**Comment by DangerNoodle** [comment]
Several contexts are not yet supported. A larger problem is when the commit tester lacks said context, as it can cause otherwise viable commits to generate as failed due to context issues.

**Comment by ZhilkinSerg** [comment]
Is web linting tool based on rules presented in  \Cataclysm-DDA\tools\format folder?

**Comment by Leland** [comment]
This issue is talking about [this JSON linter](https://github.com/CleverRaven/Cataclysm-DDA/tree/master/tools/format), right? I was trying to use it a while back on some new JSON and ran into the same context issue. I tried to figure out the [syntax](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/tools/format/format.conf) for adding new contexts but didn't make a whole lot of headway.

Would be great to get all those contexts added, I may give it a try again at some point.

**Comment by narc0tiq** [comment]
This feels like an impossible issue, in that there is no way to complete it (too broad). For a linter issue like this to be actionable, it must specify some JSON which should be accepted but which the linter rejects. At minimum, it should specify the unmatched context, but it's always better to just provide the snippet of JSON the linter complained about.

In the general case, if the linter is wrong (as in: doesn't understand something), the linter should be updated; for an example, AlecWhite#1 contains the necessary updates to make the `monstergroup` context function with the JSON in #21153. This is similar to how #20060 incorporated John-Candlebury#2 for a similar problem.

If you're not sure how to update the linter, ask for help! At worst, we may recommend extracting the problematic JSON objects to somewhere the linter won't see it.

**Comment by kevingranade** [comment]
There's a higher level issue here.  I'm unclear what the benefits of the linter are, and if those benefits are worth the constant breakage we're seeing.  For one thing there's already a consistency check in the game, and keeping an internal and external check in sync is asking for this kind of problem.

**Comment by DangerNoodle** [comment]
> I'm unclear what the benefits of the linter are

Do you mean the online linter, or linting rules in general? Because having an easily accessible way for contributors to lintfix their changes is absolutely a good development practice, as not all users can be counted on to set up the required tools on their own. The fewer tools contributors have to procure on their own to ensure good code, the more efficient their contributions are.

Ensuring the online linter is able to handle everything the lint rules demand is simply basic maintenance of a useful tool, just as ensuring the code does not create failures to compile is important.

**Comment by narc0tiq** [comment]
To the best of my knowledge, the linter serves the same purposes as `astyle` does -- maintaining consistent indentation and JSON property order allows for diffs that are easier to read and compare, and JSON blocks that are readable and of similar shape within a specific type.

I'm not at all sold on the mechanism -- I'd rather the game enforced the indentation and field order rules, precisely so we can avoid having to maintain two sets of the same kind of data -- but I'm pretty happy with the idea of having it.

I don't have data as to how much breakage is involved; searching around the issues for things like "json linter" gets relatively few hits, but I'm fairly sure I'm missing things, too. I'd expect it to be relatively rare, with the actual common things already being within the validation rules.

**Comment by kevingranade** [comment]
> Do you mean the online linter, or linting rules in general?

I mean the specific set of linting rules that exist, there's been little to no evaluation of whether they're on balance helpful or harmful.  Again I point out that having two (three!) sources of truth for what correct json is is asking for continual breakage.  This might be mitigated by trimming down exactly what is enforced by the linter.

> To the best of my knowledge, the linter serves the same purposes as astyle does -- maintaining consistent indentation and JSON property order allows for diffs that are easier to read and compare, and JSON blocks that are readable and of similar shape within a specific type.

Consistent indentation, great, no problem there, but enforcing consistent ordering actually makes diffs more difficult to read because it tends to confuse the diff tools.  AFAIK the main things we'd like to enforce are indentation and bracket use.  The linter has no business worrying about the content of the json, that's an anti-feature and the source of the synchronization issue reported here.

**Comment by DangerNoodle** [comment]
> I mean the specific set of linting rules that exist, there's been little to no evaluation of whether they're on balance helpful or harmful. Again I point out that having two (three!) sources of truth for what correct json is is asking for continual breakage. This might be mitigated by trimming down exactly what is enforced by the linter.

Understood. Indeed, I recall when I first started to contribute, the linting rules were a source of frustration and confusion. I also recall witnessing an argument between @chaosvolt and @mugling, where the former asserted that the commit failures caused by lint rules might drive away newcomers, which could be detrimental to the project.

Do note that my initial problems, and the argument mentioned, occurred not only before the online linting tool was available, but also before the commit failure readout adequately explained what lint rule was being broken.

**Comment by narc0tiq** [comment]
> The linter has no business worrying about the content of the json

I'm down with that; the game should be the *only* authoritative validator for content.

Ideally, I'd like to get rid of `format.pl` altogether, to trim the list of "things I can't check in PRs because of arbitrary code execution". That said, I'd rather not replace it with checks on `src/*.{h,cpp}`, so we can't run the game itself nor instantiate the objects (although I *am* getting the odd idea that I could still do the compile and just skip/insta-fail JSON checks in that kind of case, so maybe it's an option after all).

**Comment by ZhilkinSerg** [comment]
Linting can help find issues like this one - #21567

**Comment by ZhilkinSerg** [comment]
I've added a bunch of context rules in #21847.

**Comment by ZhilkinSerg** [comment]
Can be probably closed due to new cpp linter?

**Comment by kevingranade** [comment]
Correct, I'll try and close all the related issues now.
