### ISSUE TITLE
Shock weapons and electricity damage require major rebalancing

### ISSUE THREAD

**Issue by DeltaEpsilon7787** [CleverRaven/Cataclysm-DDA#19613]
Currently electricity damage is a generic type of damage unlike bashing or cutting or piercing damage. It doesn't even stun [I couldn't find any lines in code that would say so], it simply adds a temporary effect_zapped that does nothing at all.
That renders tasers, shock tonfas (which are simply glorified tasers) literally useless and shocker zombies much less dangerous than they should be. Tasers not stunning is most likely a bug.

However, I do remember tasers being so OP that they could make killing a shoggoth a trivial task by tazing them enough so as to stop regeneration.
Right now all that tasers do is simply inflicting 2-25 damage which kinda contradicts the purpose of a taser -- to stun a living being, not to inflict a shock. That's even worse considering they consume 100 charge per stun which is _extremely_ much. There is no other weapon in game that consumes so much energy per use. To put that in perspective, even a simple fusion blaster rifle which works on pure electricity consumes 40 charge per shot and that thing can set buildings and zombies on fire, the resulting explosion is powerful enough to break windows around and even inflict some damage to you. And it takes only 40 charge. But a simple taser spends 100 charge and only slightly shocks the target. Even worse, it's only enough for 5 zaps. No real life taser is that pathetic.

My own suggestions are provided here: http://pastebin.com/9XXUDzAq

Needs more discussion

**Comment by Regularitee** [comment]
I was actually thinking about making a similar thread concerning the other energy weapon -- lasers. I have four laser rifle turrets on my APC, and I now have literally nothing to fear of even the largest possible hordes I've seen. Even hulks go down before they can touch my vehicle.

And the kicker? The lasers mowing down a horde drains less power than leaving the floodlights on all night. I find it a bit silly you can run weapons-grade lasers on a handful of solar panels. Not to mention that on top of that, they also indirectly increase your vehicle speed and cargo space by freeing up room that might otherwise be used for ammo racks and ammunition, plus the long hours required to manufacture the ammo.

**Comment by Coolthulhu** [comment]
> it simply adds a temporary effect_zapped that does nothing at all

Except lowering speed to 25.

Could get better duration, because right now it can be waited out too easily.

We're not bringing back move drain without good justification. It stacks way too well, meaning that the same number of "raw" move drain can be useless, but stacked even once becomes YASD.
For example, 2 tazerbots.

I'm thinking lower damage but more zap duration.

**Comment by mugling** [comment]
Recent changes allow different weapons to actually have different damage types

**Comment by Coolthulhu** [comment]
Only bashing and cutting are read, though.

**Comment by mugling** [comment]
That's easily fixed. We would need some kind of mechanism of depleting ammo on hit but that wouldn't be hard either

**Comment by EditorRUS** [comment]
>Except lowering speed to 25.

I can't find **any** references of this effect in code.
![Uploading df7qqe.jpg.png…]()

**Comment by Coolthulhu** [comment]
effects.json

**Comment by EditorRUS** [comment]
Huh. Even then max_duration is only 2 which is almost useless when you spend 100 moves to use a taser. What is the point of std::max( adjusted_damage, 2 ) if it can't be higher than 2 anyway?
This still makes tasers inflict much more electric damage than stunning.

**Comment by EditorRUS** [comment]
> We're not bringing back move drain without good justification. It stacks way too well, meaning that the same number of "raw" move drain can be useless, but stacked even once becomes YASD.

"Move stun" is still a powerful feature to have. According to my suggestion as to how electricity damage should work, the more damaged some creature is, the higher the effect of electricity will be. "Move stun" has an incredibly high threshold, so high in fact that it can only be reached for enemies that are VERY damaged or very small enemies.

**Comment by CoroNaut** [comment]
When I came across a hulk, I grabbed 3 tasers and shocked him but he still came after me immediately after 15 zaps. :D

**Comment by Night-Pryanik** [comment]
Closing as per lack of discussion.
