### ISSUE TITLE
Shopping cart battery dies?

### ISSUE THREAD

**Issue by hmstanley** [CleverRaven/Cataclysm-DDA#19686]
I'm getting this weird message while reading in my bat cave.  I have two shopping carts with me, but none of them have batteries?  I'm not sure if this is connected to the change mug is making to the battery code, but wanted to put this here, since it's weird.  It doesn't affect any functionality, or break anything it appears.
![capture](https://cloud.githubusercontent.com/assets/1002600/21023869/380ee40c-bd37-11e6-9278-f1364f8c4480.JPG)

**Comment by codemime** [comment]
`vehicle::idle()` assumes that any vehicle has a power supply.

**Comment by CoroNaut** [comment]
I can confirm this still happens in build 6047

**Comment by DaliTimelord** [comment]
Can confirm in build 6074, is happening with several nearby battery-less vechicles.
![batterylessdeath](https://cloud.githubusercontent.com/assets/20878878/21448217/0ca11010-c8ae-11e6-96c2-febc5f7d280c.png)

**Comment by Chase-san** [comment]
I once fixed this long long ago. It occurred because epower_to_power at the time could in rare causes return a value despite there being no input. So I fixed it with a check against that.

My fix may have been reverted or the code restructured causing this to occur again. See #5757 and my original fix for it #6216.

**Comment by ZhilkinSerg** [comment]
Does not reproduce on current master.
