### ISSUE TITLE
Buckets unable to capture water using a funnel

### ISSUE THREAD

**Issue by Regularitee** [CleverRaven/Cataclysm-DDA#19715]
Sat it through at least three separate rainfalls and/or storms, no water. Switched to other containers and had no problem getting at least some water after a single rainfall/storm event.

I haven't tested every funnel type, however.

**Comment by keyspace** [comment]
This is true for all containers that are watertight but are not sealable.

The container chosen for filling must pass `item::is_watertight_container()` (in `item.cpp`, via `item::is_funnel_container(...)`), which currently checks for both `watertight` and `seals`.

Trivially modifying `i:i_w_c()` to check for `watertight` only may result in regressions, since the function is used in many more places. There is no mention of `funnel` in directory `tests`.

**Comment by sniperm13** [comment]
Tried this before and thought that it'd make sense as a funnel IS kinda hard to set up on a bucket. Didn't think much else on it and moved on. What would make sense is if they could "set" the bucket similar to the brazier and allow it to collect water on its own.

**Comment by keyspace** [comment]
@sniperm13 that proposal would make a nice separate issue IMO.

**Comment by keyspace** [comment]
PR relevant to OP:  #2618 - Requiring the item to be sealable is intentional.

**Comment by sniperm13** [comment]
@keyspace It would, but isn't the bucket item too uncommon a drop to warrant an issue? i mean, with a hacksaw, you can nab 60 litre tanks from most cars and use that with a funnel instead... :/ btw, 3 yr old PR. wow. :)

**Comment by BorkBorkGoesTheCode** [comment]
>PR relevant to OP: #2618 - Requiring the item to be sealable is intentional.

Those seem to be technical issues instead of balance issues.

It is realistic to have a bucket collect water if left out in the rain.

**Comment by sniperm13** [comment]
Ok done. Dunno how to link. -_-

**Comment by sniperm13** [comment]
or edit. sorry guys, im new to this. its #19750.

**Comment by keyspace** [comment]
IMO you closed the issue too early.

The description of `funnel` says "a funnel used to collect rainwater". I've imagined it [like this](http://www.aquabarrel.com/media/images/rainsaucer/abpRainSaucer_single_dblbung_275x310.png), although the volume doesn't reflect that. A `makeshift_funnel`, made from a gallon jug, obviously covers a much smaller surface area.

Anyway, the issue here is legacy mechanics. My previous mention of `item::is_watertight_container()` was meant to higlight that. Perhaps a separate `item::is_sealable_container()` is warranted?

-----

With `watertight` and `seals`, there could be four possible combinations:

* non-watertight, doesn't seal: generic container, mostly used for loot drops - e.g. `bag_plastic`;
* non-watertight, seals: as above - e.g. `bag_canvas`;
* watertight, doesn't seal: can be used to store liquids, and carry them when wielded - e.g. `bucket`, `can_drink_unsealed`;
* watertight, seals: can be used to carry liquids in inventory - e.g. `waterskin`, `bottle_glass`, `clay_hydria`.

(The complication of `rigid` items not taken into account.)

**Comment by Regularitee** [comment]
I closed it because there's a parallel thread in #19750, and thought it was pointless to have two with the exact same topic.
