### ISSUE TITLE
game freezing for moment first action after item is removed from autopickup 

### ISSUE THREAD

**Issue by baraba3** [CleverRaven/Cataclysm-DDA#19716]
been experiencing this few last version never happend before -first step after removing item from autopickup  game freze for moment-(just tested it several times with splintered wood it constantly repeat).need more confirmation if this is maybe my pc or game.

ps-autopickup is meant as from item meny not specific autopickup meny

**Comment by Regularitee** [comment]
Another possibly directly-related bug:

After loading a save, the first time you come within adjacency of any pickup-able item on the ground, there is a very similar "lag spike" where the game stops responding for a period. 

I think they're related because both increase in severity the longer the game is (which I'm assuming -- correctly or not -- has to do with how many items are on the item auto-pickup list)

**Comment by codemime** [comment]
This may be related to #19240.

**Comment by CoroNaut** [comment]
I have NPC's turned off and get the same lag spikes, perhaps it is just a raw bug with auto pickup all together?

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.D-9346. This issue is almost 3 years old, I guess we can safely close it.

**Comment by ThomasLinkin** [comment]
This is an 3 years-old post,anyone mind checking out?

**Comment by Night-Pryanik** [comment]
Ok, closing until re-confirmed.
