### ISSUE TITLE
Nomad Gear doesn't protect from rain

### ISSUE THREAD

**Issue by bouchacha** [CleverRaven/Cataclysm-DDA#19732]
I'm not sure if this is actually a bug or not but I walked just a few blocks in the rain and quickly gained a -53 morale penalty from being wet despite wearing a nomad suit and a nomad cowl.

Win 10
0.C-20222-g21cd417 (tiles)

**Comment by Regularitee** [comment]
To add onto this, the same issue appears with the Scavenger Gear (the heavier variant of the Nomad Gear). All my other stuff is waterproof, and the moment I strip off my gear, I go from -40 wetness morale penalty to +10 wetness morale bonus.

**Comment by bdgackle** [comment]
It looks like we have two different tags -- WATERPROOF and RAINPROOF.

In armor.json there are:
1) 31 items that are both WATERPROOF and RAINPROOF
2) 3 items that are RAINPROOF but not WATERPROOF
3) 51 items that are WATERPROOF but not RAINPROOF

Both Nomad Gear and Scavenger gear fall into the third category -- they are waterproof, but they aren't rainproof.

It would be easy enough to add these tags, but this must be by design.  What is the intended difference in the use of those tags?  Should we combine them?  Should one always imply the other?

**Comment by Coolthulhu** [comment]
WATERPROOF items prevent applying water if all parts hit by a water "splash" are also WATERPROOF.
RAINPROOF prevents 98% of applications of rain, regardless of body part (ie. if your socks are RAINPROOF, you are rainproof).

So nomad gear being WATERPROOF means that if you have a complete set, you should resist rain too. But if you have WATERPROOF suit but uncover your head, you are completely unprotected from rain (which hits the head too).

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.C-6421, Windows XP SP3 x86, curses. 
Wearing just nomad suit and nomad cowl in thunder rain don't get you wet.

**Comment by bouchacha** [comment]
This is still an issue on 0.C-255586 Build 7029, Windows 10 64bit, tiles. I have nomad cowl, nomad suit, boots, and leather gloves but I still get a nasty -40 penalty after just a few minutes in the rain. I still don't completely understand the difference between RAINPROOF and WATERPROOF.
