### ISSUE TITLE
Automatic Turrets don't shoot at things from inside vehicle without LOS

### ISSUE THREAD

**Issue by ussdefiant60** [CleverRaven/Cataclysm-DDA#19730]
http://imgur.com/a/p3b2R

Essentially, i have a turret set to target and fire at things automatically, and it is only shooting at things in the non-black squares. Given that AFAIK, turrets are supposed to be on top of vehicles instead of inside them, i suspect this is a bug.

i blame the fact that turret.ccp has auto turrets being fired by a fake NPC from the turrets location in automatic_fire_turret, and AFAICT the target is only selected from things said fake NPC can see from the turrets location with a 12 Perception. Unfortunately, vehicle frames are quite able to block this NPCs' vision.

Is there perhaps some X-Ray Vision trait we could give to the fake NPC to hack around the issue?

**Comment by kevingranade** [comment]
Actually, we might be able to just treat the turret as if it is on the next z-level up for targeting purposes.
This wouldn't be all good for turret owners though, because turrets would lose the ability to shoot at things adjacent to the vehicle (unless the turret is adjacent to the edge of the vehicle).
If we do that though, we'd also need a "turrets eye view" builders could use to plan where to put their turrets.

**Comment by kevingranade** [comment]
Actually, we might be able to just treat the turret as if it is on the next z-level up for targeting purposes.
This wouldn't be all good for turret owners though, because turrets would lose the ability to shoot at things adjacent to the vehicle (unless the turret is adjacent to the edge of the vehicle).
If we do that though, we'd also need a "turrets eye view" builders could use to plan where to put their turrets.

**Comment by Firestorm01X2** [comment]
In fact I won't be able to force turret autofire on freshly spawned APC. 
If problem still exitst it should be blocking issue for 0.D. Or Autofire feature should be disabled for 0.D

**Comment by Night-Pryanik** [comment]
Should be closed after #27005?

**Comment by Firestorm01X2** [comment]
I think it should.
