### ISSUE TITLE
Laser weaponry is totally overpowered

### ISSUE THREAD

**Issue by hmstanley** [CleverRaven/Cataclysm-DDA#19757]
I'm sorry.. it's like pressing the easy button.  

I can just sit back and shoot to the cows come home with large 40000 storage batteries on my vehicle and UPS's up the wazoo on my person.. I suggest we discuss/think about 1) making them drop only for the hardest and most complex dungeons, or 2) reduce their abilities or 3) up the amount of power per shot? something.. but now, I mean, why would I ever use a gun powder based weapon again?

I am gonna turn them off in my next game play, they are just too easy to use and make my gameplay kinda boring after a while.. 

believe me,  at first, when I got one, it was like "holy cow batman, this is awesome!!" and not in a "power armor" kinda way. 

At least with power armor there are several serious drawbacks, power draw, high encumbrance, lack of inventory size, etc, which really makes using it something to think about, and work around.  Core Laser weapons/ Cata++ Laser weapons/pistols, etc, are way way too easy to use and make the game a virtal shooting gallery..

**Comment by Regularitee** [comment]
The power thing is the aspect that most pressingly needs attention, in my opinion. Currently solar power alone is usually enough to sustain vehicle laser turrets indefinitely, which is both silly and overpowered. Laser weapons should be a burst weapon that can be sustained for short periods, rather than infinitely. The only question is how to properly balance this energy drain in such a way it still keeps handheld lasers viable.

Upping rarity of drops won't do much except make it more grindy, seeing as they're already pretty rare. And nerfing damage might be the same, given their already low damage compared to bullets (an A7 laser does ~20 damage, while high calibre bullets do ~60).

**Comment by hmstanley** [comment]
I was also bunching in Cata++ mod into this discussion, which adds several different new types of Laser rifles and pistols/LMG's.  These are just easy kill button... 

I mean, range 30, damage 40+, and they destroy everything.. I mean it's awesome, but it gets too easy.

**Comment by CoroNaut** [comment]
This is one of those topics where only a few people have largely varying opinions on the subject. Perhaps the details on this one would be best left for the developers to figure out. I personally believe that laser weapons aren't overpowered, their stats are weak compared to some of the conventional weapons, which is good

**Comment by sniperm13** [comment]
Not too sure about overpowered... Powerful, sure. But I have run out of Power using the rifle when faced with uber large mobs before. Though, I have to admit, I didn't mess with the turret which I CAN imagine being a bit on the upper scale.

But considering the fact that you have to delve into a lab (which is pretty nerve wracking especially ice labs), get to the bottom and survive the sentry bots guarding the thing, I felt pretty rewarded getting it.  It's not as strong or have the range of a Barrett rifle sure, but decent power with decent consumption made me feel like the trip to the lab was worth it.

If you have to REALLY nerf, please don't do the base guns at least. It'd make the trip to labs a little less exciting...

**Comment by Coolthulhu** [comment]
Laser guns have almost everything:
* Cheapest ammo out of all guns
* Good damage
* Incredibly low recoil
* Accuracy
* Good range
* No need to reload ever

They could afford to lose three of those and still be great.

I'd nerf the damage and range.
That way they'd still be useful (for removing trash mobs at safe range), but not insta-win.

**Comment by lucasmr** [comment]
Cooldown between shots would be cool imo. You could still use them to run and gun, would be a new niche.

**Comment by sniperm13** [comment]
If you nerf the main guns even a little, that'd make the laser rifle weaker or equal to the pneumatic bolt driver with steel bolts...

so much for lab runs to get those guns then. :/

and please don't even think about nerfing the bolt driver. Xd

**Comment by hmstanley** [comment]
maybe the key is to add some differentiation to the weapon?  that's why I thought of cooldown/limiter.  Some way of mimicking reload, and also address power on vehicles.  I think you can leave everything else alone, damage and range, since one is 20, and the other is 19 (range) i believe.  

as an aside, I'm more worried about the Cata++ mod ones, but I can always play a game without the mod, but I digress.

Some changes to vehicle inclusion would be useful. On par with doubling the power drain for firing along with a cooldown (maybe after double the amount of shots vs. using it as a personal weapon) on vehicles, or reducing range on vehicles? something.. but right now, it's easy button.

Right now, the A7 = 19 Range, 20 damage
On vehicle maybe the amount of power should be 100 per shot with a 5 second cooldown after 20 shots
On person, the amount of power per shot should be 50, with a 5 second cooldown after 10 shots.

Hows that?

**Comment by Coolthulhu** [comment]
> If you nerf the main guns even a little, that'd make the laser rifle weaker or equal to the pneumatic bolt driver with steel bolts...

Not at all. It still has the ability to fire full accuracy bursts without stopping to reload ever.

So basically, like pneumatic bolt driver with infinite ammo, burst fire and accuracy that doesn't decrease during said burst.

**Comment by Aivean** [comment]
A7 laser rifle has slightly better DPS in auto mode comparing to diamond katana with Niten Ichi-Ryu.  And it drains UPS/bionic power pretty fast (125 energy per burst, if I'm not mistaken), so it's not usable for killing hordes (necropolis). Also it has pretty low armor penetration and hence not suitable for killing armored zombies.

Most of the other laser weapons that I'm aware of either require rare ammo (fusion cells) or have to be mounted (do they come from the blaze mod?). Sure, you can create foldable wheelcart with the battery and mounted laser cannon, but eventually it becomes too much hassle to drag it around when literally everything can be obliterated with diamond katana/nodachi.

I personally prefer to have equally good options for the end game, not equally bad ones. 
Like, power armor should be slightly better than top regular gear, but drain batteries. 

Same with laser weapons. Draining batteries is already a disadvantage, that reduces mobility (for handheld weapons). But I think that's a good thing that we have sustainable range weapons for the endgame. 

You can make laser rifles only craftable using rare recipes from rare components on high skill levels, but PLEASE don't make them useless. There should be laser-rifle analogue of diamond katana for the endgame.

**Comment by Aivean** [comment]
I think @hmstanley is right. The reasonable way to nerf laser weapons is to add cooldown. It's consistent with reality — you have to charge condensators before emitting laser beam and it also balances their usage on vehicles — even having a huge power pool you are still limited by a charging rate of condensators inside your laser gun.

**Comment by kevingranade** [comment]
On Dec 13, 2016 4:36 PM, "Coolthulhu" <notifications@github.com> wrote:

Laser guns have almost everything:

   - Cheapest ammo out of all guns
   - Good damage
   - Incredibly low recoil
   - Accuracy
   - Good range
   - No need to reload ever

They could afford to lose three of those and still be great.

I'd nerf the damage and range.
That way they'd still be useful (for removing trash mobs at safe range),
but not insta-win.

I agree, though I'd also suggest nerfing them by increasing power draw, irl
one of their greatest drawbacks is the energy requirements, let's keep that
around.

Another way of saying this is that their niche is supposed to be very
reliable but expensive damage over time. The low recoil and lack of
reloading allows them to be fired continuously, but they *should* drain
your power reserves if used for protracted periods.
If we want to make this continuous fire effect even more extreme, we could
have damage output of lasers ramp up over time, so they'd hardly do any
damage at first, but ramp up to their steady damage output with continued
firing.   This would be modelled as an effect on the monster with a
relatively short cooldown that makes the monster more vulnerable to damage
from lasers.
This would further limit their niche since they would be less good for
dealing with really weak targets that would take a single round from a
firearm to drop.

Suggestions for balance points:
Laser pistol should easily kill a zombie before it closes.
Laser pistol should fail to kill a group of ? zombies before they close.
Laser pistol should probably fail to kill a charging brute
Laser rifle should kill a charging brute but fail to kill a charging  hulk.

**Comment by sniperm13** [comment]
@Coolthulhu  You just pointed out the laser rifle vs bolt driver comparison as it stands.

But if you nerf the damage for example, vs the driver, itd be on equal standing. less than 20 with autofire vs 40 for the bolt driver. If you nerf the range, thatd still hurt the laser rifle usage.

My first lab success was 10 lvls deep and rewarded me with the laser rifle. The trip was easily vindicated. And while the laser rifle was pretty good, energy consumption was still an issue which forces me to melee or pull out the bolt driver for uber mobs after it's drained.

I still think the personal rifle was well balanced with regard to risk vs reward. Also, lets not forget that RNGesus is rarely THAT giving as subsequent games took me more lab trips to find the laser gear.

The mounted version on the other hand, I can't comment on as I got killed by my first automated turret (YASD XD), I never mess with them since.

It's still ya'll game, just putting my 2 cents in.

**Comment by kevingranade** [comment]
With respect to cooldown, the end result is exactly the same as simply
dropping damage,  but the niche for laser weapons is continuous damage, not
burst.

**Comment by kevingranade** [comment]
All the back and forth about this weapon vs that weapon is why I want
functional tests, they give a much more understandable and objective
measure of balance.

**Comment by Aivean** [comment]
@kevingranade Let's understand the problem first. I thought OP was talking about mounted weapons being overpowered, not handheld ones.

In the blaze mod there is mounted laser cannon that eats 400+ energy per shot and has 150+ damage. It also can be crafted from very common Fusion Blaster CBM. Yes, this thing is arguably op, but it can hardly be used as handheld weapon.

Regarding A7 rifle (are we talking about it?), it has relatively low damage and it's unsuitable for killing certain monsters. Also it's pretty rare. Maybe it's my luck, but after clearing 10+ labs I managed to find only one of these.

I'd say if you want to nerf it, make it even harder to acquire, but don't touch the stats.

**Comment by Coolthulhu** [comment]
> I'd say if you want to nerf it, make it even harder to acquire, but don't touch the stats.

I'd do the opposite: make it more common and weaker.

Having incredibly rare instant-win items is horrible design.

**Comment by Aivean** [comment]
@Coolthulhu I agree that if it's possible to get it if you first day/month/year it's a bad design. But having the possibility to find/craft insta-win items when you already "won" is a good thing. It basically makes endgame less boring.

**Comment by kevingranade** [comment]
> @kevingranade <https://github.com/kevingranade> Let's understand the
problem first. I
> thought OP was talking about mounted weapons being
> overpowered, not handheld ones.

He mentions pistols at least,  I took it to mean,  "all laser weapons".  If
it turns out to be just lasers added by mods we should just close the issue
because it's working as expected, we don't require mods to be balanced so
in general they aren't.

If the issue concerns core game turrets it doesn't really change my
approach,  we need some functional acceptance tests that demonstrate how
good they are, agree on how effective they should be based on those tests,
and change them to pass the tests.
I also think if they are too powerful,  the approach to take is to reduce
power per shot,  reduce range,  and increase power consumption.

@Coolthulhu <https://github.com/Coolthulhu> I agree that if it's possible
to get it if you first day/month/year it's a bad design. But having the
possibility to find/craft insta-win items when you already "won" is a good
thing.

Insta-win items are bad no matter how hard they are to obtain.  Breaking
the game is breaking the game no matter how it happens.

**Comment by Aivean** [comment]
@kevingranade what is insta-win?  Is using `Krav-maga` with `Power Armor` and `Hydraulic Muscles CBM` insta-win?  Is using `Diamond katana/nodachi` with `Niten Ichi-Ryu` insta-win?

I think it's part of the game design that there are things that are hard to find but which alter/break game mechanics significally.  Otherwise what's the point to progress?  You can build a home near ant nest and survive indefinitely.

**Comment by sniperm13** [comment]
@Aivean Otherwise what's the point to progress? You can build a home near ant nest and survive indefinitely.

I agree. Once you get your crafting skills up to snuff, the world gets "manageable" is probably the word. By that time, with what looting you've done to get there, it gets boring, so challenges are sought to keep things interesting. But more importantly, you want some form of satisfaction other than "I can beat temples and labs now." when you do them.

I actually HATE "achievements" in video games now because I think it's the source of laziness in some of them being creative with respects to breaking them (achievements) but that's beside the point.

The laser rifle filled that niche nicely for me. I'd go to labs now just to see if I can get the laser set there knowing whatever hardships, injury and lousy RNG mutations my character gets might be vindicated. The key word here tho, is chance. There is no assurance that this weapon will be there when you get to the last level. But fail or not, it keeps things interesting.  Take that away, and that's one less interesting plot of land to visit after you get all the unique books from there as there is little else in the end of labs that you can't get anywhere else...

**Comment by kevingranade** [comment]
On Dec 13, 2016 7:07 PM, "Ivan Zaitsev" <notifications@github.com> wrote:

@kevingranade <https://github.com/kevingranade> what is insta-win? Is using
Krav-maga with Power Armor and Hydraulic Muscles CBM insta-win?

Almost certainly, those shouldn't even work together.

Is using Diamond katana/nodachi with Niten Ichi-Ryu insta-win?

Most likely.

For the last time, these comparisons are pointless, the only meaningfull
way to talk about weapon balance is to outline how effective they are
against enemies, comparing weapons to each other just leads to talking in
circles since the existing weapons are not balanced either.

**Comment by BorkBorkGoesTheCode** [comment]
>On Dec 13, 2016 4:36 PM, "Coolthulhu" <notifications@github.com> wrote:

Laser guns have almost everything:

   - Cheapest ammo out of all guns
   - Good damage
   - Incredibly low recoil
   - Accuracy
   - Good range
   - No need to reload ever

They could afford to lose three of those and still be great.

I'd nerf the damage and range.
That way they'd still be useful (for removing trash mobs at safe range),
but not insta-win.

I agree, though I'd also suggest nerfing them by increasing power draw, irl
one of their greatest drawbacks is the energy requirements, let's keep that
around.

Another way of saying this is that their niche is supposed to be very
reliable but expensive damage over time. The low recoil and lack of
reloading allows them to be fired continuously, but they *should* drain
your power reserves if used for protracted periods.
If we want to make this continuous fire effect even more extreme, we could
have damage output of lasers ramp up over time, so they'd hardly do any
damage at first, but ramp up to their steady damage output with continued
firing.   This would be modelled as an effect on the monster with a
relatively short cooldown that makes the monster more vulnerable to damage
from lasers.
This would further limit their niche since they would be less good for
dealing with really weak targets that would take a single round from a
firearm to drop.


I'd support damage, reload, and power nerfs.

The pneumatic bolt driver shouldn't be so low-recoil; is there a way to increase the recoil without affecting crossbows?

**Comment by sniperm13** [comment]
And there goes my bolt driver. :/

**Comment by BorkBorkGoesTheCode** [comment]
@sniperm13 Serious question: How would you balance the pneumatic bolt driver?

**Comment by sniperm13** [comment]
@BorkBorkGoesTheCode I'd keep it as is. I wouldn't even call it an OP weapon but that's probably subjective. The ammo is heavy, there's the reload and even with high rifles and marksmanship, it's not reliable at near max ranges. Not to mention that you also need 8 mechanics and suitable marksmanship to unlock it. I prefer guns, but the bolt driver is a good fallback weapon in late game.

**Comment by Noctifer-de-Mortem** [comment]
My two cents, lower damage, keep them accurate, make them energy hungry, add cool down and make bursts have recoil.

**Comment by hmstanley** [comment]
@ Noctifer-de-Morton - It was your mod that precipitated my OP. 

Frankly, the A7 and pistol are fine as is on person. With the cool down/ramp up tweak.  I'm more inclined to make these items have drawbacks similar to the "using power armor". Not the insta-win. 

1) cool down or ramp up (makes logical sense)
2) higher power draw for vehicle mounts

Leave the rest alone and Cata++ and other mods should follow suit with their items.

**Comment by kevingranade** [comment]
Confirmed this is a mod balance issue, please discuss it directly with the mod author.

**Comment by Noctifer-de-Mortem** [comment]
@hmstanley Issue was addressed here. https://github.com/Noctifer-de-Mortem/nocs_cata_mod/pull/7
Feel free to post other issue or bugs you have with my mod in this repo as well.

**Comment by waldoswify93** [comment]
Fhfhffhdhffhfhf
