### ISSUE TITLE
Diesel Engines have low max speed

### ISSUE THREAD

**Issue by pisskop** [CleverRaven/Cataclysm-DDA#19761]
70 kmh is very low for any vehicle that isnt peddle powered

**Comment by Tharn** [comment]
Depends on what kind of vehicle it is, and how much it weighs. For a military APC or a construction vehicle it isn't low at all.

**Comment by Aivean** [comment]
Max speed is not the problem. The problem is that vehicles' speed is completely detached from everything else.  70km/h doesn't really mean that one can travel 70km in one hour.  

Also currently 70km/h ≈ 43.5 mph ≈ 4 tiles per turn, which is only TWICE as fast as running player.

We already discussed that here:
* https://github.com/CleverRaven/Cataclysm-DDA/issues/19754
* https://github.com/CleverRaven/Cataclysm-DDA/pull/19275#issuecomment-265305309

**Comment by pisskop** [comment]
Why does it not excede third gear?

Is it a problem specifically with how gears are managed, or power is calculated?  The problem is perhaps not related to any fuel efficency or how speed is arbitrarily measured, but that the engine itself is flawed

**Comment by 1skandar** [comment]
Actually, unless things have changed, top speed on most things are absurdly low. Ignoring kph/mph label as that is arbitrary, you're going to struggle to get a Diesel engine much past 2 or 3 tiles/turn and much past 3 or 4 tiles/turn for other types of engines. Now, I'm not advocating a return to the old days of stupid fast vehicles, just that top speed for most things needs a slight bump upward by a tile or two per turn.

**Comment by BorkBorkGoesTheCode** [comment]
The game really needs a uniform scale.

**Comment by Tharn** [comment]
One indication for scale are multi-tile objects like vehicles. They impose an upper limit, i.e. you can't make a tile much bigger than 1m² without breaking vehicle size in the process.

**Comment by 1skandar** [comment]
Ok, let's not get into this argument again. I'm perfectly happy with tiles being an arbitrary size, as trying to do otherwise breaks all the things and reduces modularity, both being Very Bad Things.

What I'm less happy about is trying to get a Diesel engine to go much faster than my character can run. That scale, at least, is a hard constant. Most, if not all, vehicles should be capable of 3 to 4 tiles per turn, max, unless severely overweight. After the rebalance things got shift d a bit low, I think, and deserve a slight shift upwards.

**Comment by Aivean** [comment]
To make vehicle dimensions realistic tile should be 0.5x0.5m. This way the width of narrow cars (4 tiles wide) is 2 meters.  Wider cars (like RVs and humvees) are 5 tiles wide — 2.5 meters.

Houses occupy one map tile: 24 x 24 tiles or 12x12 meters,  which is consistent with reality. Larger houses can occupy two map tiles.

One issue is player's speed. In order to have the same 1 tile/turn, turn should be 1/4seconds (this makes walking speed 2 m/s). However it may require revision of the combat system, as one melee swing per quarter of the second may be too fast.

Another issue is the firearms range. Currently it's unrealistically low, but I think the only way to solve that is through lore. Fluent tile size doesn't really address this problem, as you can easily relay shooting range to other objects, like houses. Pistol range currently is too short to reach the opposite wall in a large room. This is required by game balance, but it can't be solved/explained by "magic" tile size.

And the biggest issue, of course, is the amount of effort required to revise current system. There are thousand of places where "turns" are mentioned in the code.

**Comment by 1skandar** [comment]
Ok, again THIS IS NOT THE RIGHT PLACE FOR THIS DISCUSSION, thanks. If you want to discuss this either open your own issue or comment on one of the existing ones about it, please stop cluttering up mine with things irrelevant to my issue.

**Comment by pisskop** [comment]
i would like to reiterate that the large personell trucks are topping out in 3rd gear at 67 kmh

**Comment by 1skandar** [comment]
It gets worse if you consider that is 30 mph or so under the old system. They are still tweaking this section of code and balancing things. They want to keep vehicles much slower than they were, which I agree with. That said, I think they've maybe taken things too far. Regardless of what you call that speed we are talking 3 times a player's walking speed. I'd like a dev to weigh in here and see if this is intended or still needing balancing. If it was me, I'd say bumping it up a tad is warranted.

**Comment by BorkBorkGoesTheCode** [comment]
It looks like the cargo truck is based on cargo trucks like the https://en.wikipedia.org/wiki/M939_Truck 

The truck engine installed in the military cargo truck has 120 horsepower.

**Comment by JacobKessler** [comment]
That wiki article also makes it look like the mass dynamics scaling is too harsh - even if the quoted speed (60mph) is unloaded, that's a 240hp engine moving a 10 metric ton vehicle at 60mph, when people putting the largest engines they can find (the v12 is ~300hp, the large electric is ~400) are having trouble getting 6-7 metric ton vehicles above 40 mph.

**Comment by keyspace** [comment]
Revert of #19275 (Vehicle propulsion overhaul) might have made this obsolete.
