### ISSUE TITLE
Vehicle part repair costs should be proportional to their health levels.

### ISSUE THREAD

**Issue by Asmageddon** [CleverRaven/Cataclysm-DDA#19866]
Without a vehicle welder, keeping repairs up is very cumbersome unless you wait for the parts to be more damaged, which exposes them to the risk of breakage. It doesn't make a whole lot of sense, either.

**Comment by Regularitee** [comment]
Energy costs should scale roughly linearly, but time costs should not, in my opinion. Since there's a minimum time expended with inspecting a part, getting your tools out, putting on your protective work gear, and putting everything away when you're done. It's like cooking a meal at home: no matter how small the meal, there's always a minimum prep and cleanup time due to having to wash dishes and cooking tools afterwards.

**Comment by CoroNaut** [comment]
I can't agree with the time costs being the same for each part given different damage levels. If you have a frame that is only slightly damaged with a crack or something simple, then fixing it should take much less time than a really damaged frame that has multiple larger cracks. The same problem comes up when repairing a simple wall or door compared to repairing an engine. The engine would most likely require more time since it has a lot more parts and is much more complicated in comparison.
Example:
![capture](https://cloud.githubusercontent.com/assets/24307650/21589248/f17ba062-d0bd-11e6-9f7d-556912cb99d8.PNG)
![capture2](https://cloud.githubusercontent.com/assets/24307650/21589253/f98754e0-d0bd-11e6-8294-5da53165213b.PNG)
18 minutes for full engine repair, 22.5 minutes for trunk door repair. The trunk door even requires less mechanics skill to repair. The damaged engine should take much longer to repair than the damaged trunk door. The trunk door is essentially just a steel frame.

**Comment by mutability** [comment]
Part repair requirements _already are_ proportional to part damage AFAIK.

https://github.com/CleverRaven/Cataclysm-DDA/blob/ec3d3f8faa0152325b636def2df9a0be55e6393d/src/veh_interact.cpp#L2382

**Comment by Asmageddon** [comment]
Yeah, I realized that since, I guess it was just my luck that for a longer while all the damaged parts I was repairing had the same damage level. That said, I feel like there still needs to be some rebalancing done, oftentimes it's better to just replace a part than repair it, or to uninstall, repair manually, reinstall. Then again, now that batteries are common, it's not as big of an issue as it used to be.

**Comment by kevingranade** [comment]
On Jan 3, 2017 6:53 AM, "Asmageddon" <notifications@github.com> wrote:

oftentimes it's better to just replace a part than repair it, or to
uninstall, repair manually, reinstall.

The first option isn't necessarily a bad thing, the second shouldn't happen.

**Comment by Asmageddon** [comment]
It does, though, since the repair costs for installed parts are really high, especially for parts that can use the soldering iron.

**Comment by Night-Pryanik** [comment]
Closing as per lack of discussion.

**Comment by Asmageddon** [comment]
@Night-Pryanik @kevingranade What if you gave tools a size limit, so that soldering iron cannot be used to repair car parts, or made manual repair costs scale up with size?

But then again, there's still a lot of vehicle crafting changes and fixes that need to happen. (or I assume there are, since it was a running issue that no one got around to for years)

**Comment by kevingranade** [comment]
I'm not sure its directly related to this issue, but soldering and welding should generally be two different things, you cant repair car parts with a soldering iron, and you cant solder electronics with a welder.
