### ISSUE TITLE
Ask NPC to "Stick close!"

### ISSUE THREAD

**Issue by RogueYun** [CleverRaven/Cataclysm-DDA#19874]
It would also be nice to tell the NPC to "Stick close!" so that the NPC will try to stay within 1-2 tiles away from the PC. This would make for easier pushing/swapping positions and enable the PC to more easily close some doors.

**Comment by jzambo** [comment]
There are potential many topics involved.

Going through and closing doors could be implemented through recognition of player being inside the building while NPC is not.

Another relevant topic is having NPC close enough so that you can see each other during night. I have implemented POC for this without additional "distance" parameter so that I could keep them from dying in the dark easier.

**Comment by Coolthulhu** [comment]
I'd rather see it as a setting, to allow exact number of tiles of distance.
