### ISSUE TITLE
Scenarios need adjustments.

### ISSUE THREAD

**Issue by Asmageddon** [CleverRaven/Cataclysm-DDA#19871]
- Sheltered: Probably isn't worth +3, because tailoring makes surviving the winter weather relatively easy, and shelters usually aren't as remote as they could be.

- Missed: Possibly should give a token +1, since you're missing out on the shelter, and potentially starting among zombies. That said, it's variable.

- The Next Summer: Gives access to strong classes, and actually boosts the total points by +6 should you opt for Survivor? It should be changed by -3 at least, it's literally a non-winter, no-zombies variant of Ambush.

- Wilderness: Should be +1, since while it gives some bonus class choices, wilderness start is tough, and the choices are, after all, more limited.

- Bottom of a Mine: Miner should probably start with a shovel. Would be nice to have additional class choices(manager?)

**Comment by Aivean** [comment]
* Tweaker:  gives only +2 points, while amphetamine withdrawal (30) makes crafting (including cooking) nearly impossible for the first nine days or so

**Comment by ZhilkinSerg** [comment]
Manager going to the bottom of the mineshaft will probably have the very same set of equipment as usual miner.

**Comment by Asmageddon** [comment]
Classes definitely need some adjustments too, but that's often more subjective and a topic for a separate issue besides.

**Comment by DangerNoodle** [comment]
> Bottom of a Mine: Miner should probably start with a shovel. Would be nice to have additional class choices(manager?)

Do miners start with a gas mask, or with filter masks? It might be more of a viable challenge if they started with filter masks instead.

**Comment by RogueYun** [comment]
I'm about to suggest something drastic... but maybe we should remove scenarios entirely and let people make their own scenarios on the fly? We allow them to pick their traits, and their stats already, why not allow players to choose their starting equipment by giving them an allotment of money to spend (or convert from skill points). Give them points for taking negative effects like amphetamine withdrawal and infection. Remove points for starting in easy locations like a farm or LMOE shelter. Give points for starting in harder locations like the mall. Instead of trying to funnel players into a few tantalizing scenarios, maybe we should let them be as creative as they want and make their own starting story? A cannibal in the graveyard? A football player? A cheer leader?  We don't have to pre-write these scenarios if we just let the player choose for themselves...

**Comment by Aivean** [comment]
@RogueYun  I think your idea is great. However I'd split it into several items:

1. Implement fixed set of "starting traits", such as:
   * starting item
   * starting condition (disease, withdrawal)
   * starting bionic
   * starting location
   * ...

    Each of these traits can cost positive or negative amount of points, as regular traits do.
2. Reimplement current scenarios and professions as "templates" for these traits. This implies calculating "cost" of the scenario and profession "on fly" based on the cost of individual starting traits.
3. [Optional]  add possibility to pick individual "starting traits".

This way instead of balancing large "scenarios" we have to balance smaller "traits" which should be easier (divide and conquer principle). Also it potentially allows to make character creation more customizable (if 3 is implemented).

**Comment by kevingranade** [comment]
This way instead of balancing large "scenarios" we have to balance smaller
"traits" which should be easier (divide and conquer principle).

It is not the case at all, it is much more difficult if not impossible to
assign points to items and other traits and remotely expect the result to
be balanced.  The result is a specific 'best' load out for each playstyle,
either making people who know about the optimal load out overpowered or
making people who do not underpowered.  It is MUCH easier to assign a
relative survivability rating to a particular set of traits and items.  If
that's too hard, what we need is less configurability, not more.

**Comment by RogueYun** [comment]
I'm certainly not as involved in this project as you are, but I still don't get it. This game is all about configurability. If people want a different start it is super easy for someone like us to make a custom scenario and put it into the files, but wouldn't the goal be to allow the player to do that for themselves instead? Cut out the middleman so to speak? I mean, sure we give 20-30 cars for players to drive and use, but 90% of the players build their own mobile killer fortresses. Isn't this the same principle? I don't think it would be as fun for the player if we compelled them to play with our mobile fortresses, no matter how many custom ones we made. Our job is to provide them the parts to build their own. Shouldn't the same principle apply for starting characters?

**Comment by kevingranade** [comment]
I'd be totally fine with having a character creation mode where you can
assemble a character with unlimited traits, items, whatever, but this sort
of thing is impossible to balance so nothing would be assigned points, it
would just be lists of options you could select.

**Comment by DangerNoodle** [comment]
I can see it being possible to assign points, but finding a sensible balance would be difficult, and a lot of it would depend on context. For example, a gun with obscure ammunition would be of little use unless ammunition or the means to handload were additionally purchased.

Not to mention, such a structure would be a massive undertaking to code to begin with.

**Comment by Asmageddon** [comment]
Tbh I dig it, but don't replace the current scenarios, make it an additional option that unlocks new tabs for start(location+options), items, bionics, mutations, with enabling bionics/mutations at all costing extra points.

**Comment by Asmageddon** [comment]
Instead of freeform item choice, you'd probably offer complete sets of items, e.g. gun with ammo, electronic components with an electronic books, etc. Still, lack of points would probably make more sense.

**Comment by WizardOfOoo** [comment]
Just debug what you want, that's what I do when i want to try something different.

**Comment by Night-Pryanik** [comment]
Closing because of no discussion in more than a year.
