### ISSUE TITLE
Recipes persist between characters

### ISSUE THREAD

**Issue by TheSadFox** [CleverRaven/Cataclysm-DDA#19885]
Now this one is bizzare. I've edited my character preset, moving one skill point from dodge to tailoring, saved the preset under same name, then proceeded to play with that character. Fast forward, character died, i've created new world, edited the preset again, moving the skill point from tailoring back to dodge. Saved the preset, again, under the same name, and proceeded to play the game. Now, upon opening the crafting menu, my new character with zero skill points in tailoring had access to all level 1 and 2 tailoring recipes. Every single character created using this preset starts with recipes unlocked. Characters created without using that preset are unaffected.

Build: Experimental 6085

**Comment by kolsurma** [comment]
The bug exists because the templates load all of a characters stats, including what recipes are learned. When changing skill levels in the new character screen the learned_recipes are not dynamically refreshed, leading to the bug in question.

The easiest possible fix would be to have a new character's learned recipes erased and recreated when loading from a template.

Interesting side note: if you save a template and then immediately return to the main menu, you can't load the template. You either have to exit the game or load a world then return to the menu.

**Comment by Night-Pryanik** [comment]
Should be closed after #20288.
