### ISSUE TITLE
All vehicles on bridge spawn with 0.0 everything

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#19972]
I found 4 cars on a 5-length bridge and they all had 0 energy, 0 diesel, and 0 gas. If I'm not mistaken, empty tanks shouldn't show any gas or diesel in the tank, but they spawned with 0.0 liters.

**Comment by Regularitee** [comment]
I, too, have found MOST vehicles all have 0.0 fuel and energy when they spawn on bridges. By most I mean 90% or so of vehicles. It's been that way for some time now, but I didn't submit an issue report since I wasn't totally certain it was caused by the base game rather than a mod like PK's rebalancing.

**Comment by Leland** [comment]
Still present.
