### ISSUE TITLE
Could we have an electronics mod similar to atomic lamp?

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#19989]
Could we have a mod for electronics that when attached would automatically power the device similar to the atomic lamp? Perhaps it could take something like 5 plutonium cells to create the mod. It could just make the device fully powered all the time, or it could be a mod which gives a single charge every turn similar to how the ups distributes energy. I don't know which would be more balanced, but it may still be a good idea to include this into the game.

**Comment by Coolthulhu** [comment]
This would pretty much obsolete advanced UPS and atomic battery mod.

**Comment by CoroNaut** [comment]
If we are talking about usability of the UPS vs. advanced UPS, the regular UPS takes batteries which are so common that you could fill 20 UPS's before you could use a plutonium cell on an advanced UPS. They are best off used to make an atomic lamp if you haven't found one already, or best used for the power storage CBM. The atomic battery mod is also useless before you even get the ability to craft it. You gain the UPS so early compared to it that you would have everything you need to power powered by that ups already. Also, if you happened to get the unified power system CBM, then you would completely drop the idea of using the advanced UPS or atomic battery mod entirely. To be honest, I believe those two items are completely inbalanced solely because you gain better items before you get them. Also, you only gain 500 charge per plutonium cell which is equivalent to grabbing 500 batteries from nearby houses, or especially the electronics store. As of right now, the advanced UPS and atomic battery mod are useless compared to regular UPS and its CBM.

**Comment by kevingranade** [comment]
In short, no.  Atomic power is already pushed well past what is reasonable,
it doesn't need any more extensions, particularly not that make it more
generic.

**Comment by Regularitee** [comment]
If you want a largely infinite, renewable energy source, you can always get the UPS bionic and UPS conversion mods for your electronics.

Most electronic devices drain power slowly or infrequently enough that your natural energy gain from Joint Torsion Ratchets or Solar Panel bionics can cover their usage, particularly if you have a very large bionic power reserve. Furthermore, you can convert all fuel types (alcohol, combustibles, batteries, sunlight, plutonium, even food) into bionic power -- and by extension, UPS power.

**Comment by CoroNaut** [comment]
Regularitee confirmed my point that advanced UPS and atomic battery mod have been useless since the UPS CBM is just way better in all aspects. I am also confused as to why you say that atomic power is already too powerful. The plutonium cells are equivalent to 500 batteries each, this makes them way under-powered just because of how common regular batteries are. Is it really intended for plutonium cells to carry so little charge?

**Comment by CoroNaut** [comment]
Just for emphasis on the problem, I want to bring up #17086. natsirt brings up a very good point that I brought up here, especially about an RTG type device, his example comes from the Mars Curiosity rover.

**Comment by Aivean** [comment]
I agree with @CoroNaut that plutonium cells currently behave inconsistently:

1. in Microreactor CBM, they provide [5000 energy over time](http://cddawiki.chezzo.com/cdda_wiki/index.php?title=Internal_Microreactor)
2. in Advanced UPS or atomic battery mod, they give you 500 energy instantly
3. when refueling vehicle's Minireactor they provide 500 "reactor charges" which translates to way beyond the 5000 battery charges
4. In atomic lamps they provide infinite (thousands of years) light

In my opinion correct (semi-realistic) behavior is:
* non-constant discharge rate over time as in №1
* same as  №1, but with constant discharge rate

Now about the discharge time. I'm not sure which [plutonium isotope](https://en.wikipedia.org/wiki/Plutonium#Decay_heat_and_fission_properties) plutonium cells contain, but all isotopes have half-life at least several years. [Half-life](https://en.wikipedia.org/wiki/Half-life) roughly represents the time required for half of radioactive atoms to decay. This means that if half-life for "Plutonium cell™" is one year, then after one year it will be half as efficient. After another year it will have 1/4 of the initial efficiency and so on.

I'm not sure what is the right way to balance cells. Probably it's something along the lines of making them an infinite power source with limited low discharge rate (like, half of the flashlight consumption rate). 
Alternatively (or additionally) plutonium cells can be made craftable (for example from radioactive ores found in craters).

**Comment by kevingranade** [comment]
On Jan 9, 2017 9:33 AM, "Regularitee" <notifications@github.com> wrote:

If you want a largely infinite, renewable energy source, you can always get
the UPS bionic and UPS conversion mods for your electronics.

Do that then, this isn't a reason to extend atomic power.

**Comment by kevingranade** [comment]
On Jan 9, 2017 2:07 PM, "CoroNaut" <notifications@github.com> wrote:

Just for emphasis on the problem, I want to bring up #17086
<https://github.com/CleverRaven/Cataclysm-DDA/issues/17086>. natsirt brings
up a very good point that I brought up here, especially about an RTG type
device, his example comes from the Mars Curiosity rover.

Did you happen to read the part where he said it's a 50kg device that only
produces enough power to run a light bulb?  Do you want a 500kg microwave?
Because this is how we get 500kg microwaves.
These things are incredibly low power devices thay have incredibly few
niches where they can be used.

The in-game niches for atomic power:
Plutonium cells provide power for exotic scifi gadgets.
Atomic whatevers are perpetually powered joke toys.

**Comment by CoroNaut** [comment]
I couldn't explain it as thoroughly as you can Aivean, I've been with cataclysm for an insanely long time but only looked through ~5% of the code, done a little modding, ect. Everything I know is based off of in-game stats and whatnot. I figured that if 1 plutonium cell could power a coffee maker, that these cells could be used to power more items. Especially so since 2 cells could power just a lamp. 

Talking about the RTG, the game allows the power of two cells to power a lamp, so they give approximately 10 watts maybe (My living room takes 4 23W bulbs, and even 1 of them is brighter than the atomic lamp). So given this, I concluded that it would be fair to have a couple of these cells able to power the flashlight.

**Comment by Aivean** [comment]
@kevingranade 

> Did you happen to read the part where he said it's a 50kg device that only
produces enough power to run a light bulb?  Do you want a 500kg microwave?

Incidentally on the same Mars rover digital cameras have [2MP resolution](https://www.dpreview.com/articles/0353350380/curiosity-interview-with-malin-space-science-systems-mike-ravine). If you apply the same logic, modern [250MP cameras](https://www.cnet.com/news/canons-250-megapixel-sensor-powers-eagle-eyed-camera/) should not be possible.

In reality, the theoretical power output of the 1kg of plutonium-238 is:

      1000 * 15 * 32000 μW = 480W

![image](https://cloud.githubusercontent.com/assets/2865203/21826536/c05f8d88-d73c-11e6-997e-c1580328dc73.png)
(from [this article](https://arxiv.org/pdf/1511.07427.pdf))

So, even in reality it's possible* to power a lamp from under 1 kg of plutonium.
<sub>* however, we can't have 100% efficiency and we still need heavy shielding</sub>

But let me remind you two things about Cataclysm:

* It has futuristic setting with bunch of physically impossible things (laser rifles, zombies, mutations,...)
* [Game balance is more important than realism](https://github.com/CleverRaven/Cataclysm-DDA/pull/19275#issuecomment-265334115)

Here we're trying to fix the **game balance issue**. Currently advanced UPS and atomic battery mods are completely obsolete. Moreover, they behave inconsistently compared to the other items that use plutonium cells. 

Now I understand that there might be reasons why this can't or shouldn't be fixed, just don't pretend that the issue doesn't exist and please don't bring realism as an excuse.

**Comment by Coolthulhu** [comment]
Well technically Kevin can override anyone here. I'll stand by my opinion about "balance > realism", but it doesn't mean it won't be ignored.

Realism of plutonium cells is barely above that of zombies. At this point it runs not on fission, but on rule of fun.
Like atomic coffee maker, which not only has infinite power, but also techno-magically extracts extra power from coffee grounds.

**Comment by Aivean** [comment]
@Coolthulhu 

There are three main types of nuclear-powered energy sources:

* Fusion reactors
     > fusion is the process where two light nuclei combine together releasing vast amounts of energy
* Fission reactors
     > Fission is the splitting of a heavy, unstable nucleus into two lighter nuclei
* Atomic batteries
     > Atomic batteries, nuclear batteries or radioisotope generators are devices that use energy from radioactive decay to generate electricity. Similar to nuclear reactors, they generate electricity from atomic energy, but differ in that they do not use chain reactions and instead use continual radioactive emissions to generate electricity. 


First two types are "reactors", which means that they contain active nuclear reaction which produces immensive amount of energy most of which is heat. Although the mass of the radioactive core [doesn't need to very large](https://www.reddit.com/r/askscience/comments/1e8hs3/whats_the_smallest_nuclear_reactor_we_can_build/), the shielding and the mechanisms that convert heat into electricity makes these types of reactors somewhat bulky. However:

> The 5MW reactor on NR-1 (world's smallest nuclear submarine) was trashcan sized, but that includes the size of the primary shield, and is not just the size of the core.

>  ...Submarine reactors aren't much bigger, but they have the whole ocean available for heat rejection. A reactor on, say, an airplane, would have different heat rejection limits.


Now about the [atomic batteries](https://en.wikipedia.org/wiki/Atomic_battery). From wikipedia:
> The terms atomic battery, nuclear battery, tritium battery and radioisotope generator are used to describe a device which uses energy from the decay of a radioactive isotope to generate electricity. Like nuclear reactors they generate electricity from atomic energy, but differ in that they do not use a chain reaction. Compared to other batteries they are very costly, but have extremely long life and high energy density, and so they are mainly used as power sources for equipment that must operate unattended for long periods of time, such as spacecraft, pacemakers, underwater systems and automated scientific stations in remote parts of the world.

There are multiple ways to extract energy of radioactive decay. They are mostly based on utilizing emitted alpha and beta particles.

So, back to the Cataclysm. From what I see, atomic lamps and coffeemakers use some kind of atomic battery, that's why they last so long. On the other hand mini- and micro- **reactors** use either fusion or fission, that's why they produce more energy over the short time. 

So, naturally I'd expect **atomic battery** mod  and advanced UPS to have more or less constant power output over large period of time, as apparently they are some variant of radioisotope generator. 

In my previous post I gave the theoretical limits for power output of plutonium, so you can't say that it's non-realistic. Certainly Curiosity is not powered by fun.

**Comment by Coolthulhu** [comment]
> There are multiple ways to extract energy of radioactive decay.

That fission part in my post was a mental shortcut. Decay can involve fission, though.

> In my previous post I gave the theoretical limits for power output of plutonium, so you can't say that it's non-realistic. Certainly Curiosity is not powered by fun.

Add shielding, the idea of everyone having access to weapon-grade plutonium, risk of radiation poisoning etc. It quickly adds up to the same level of "possible" as UPS (lossless, wireless transfer of electricity on whole person).

I'm not saying it should be dropped or anything - I like the idea of plutonium cells and would rather see them expanded on than dropped. Just that it is rather pointless to argue about the realism of something like that.

**Comment by Aivean** [comment]
Ok, let's not argue about realism then. 

Obviously at our current technology level atomic batteries are less practical than regular ones. And it's pointless to argue about fictional universe. I find it plausible that in universe where force-fields exist it's possible to convert all radioactive emissions into energy (so there is no need for extra shielding). 

Anyway, as we share the opinion that Cataclysm is better with atomically powered devices let's discuss how this issue can be addressed:
> Currently advanced UPS and atomic battery mods are completely obsolete. Moreover, they behave inconsistently compared to the other items that use plutonium cells.

**Comment by Aivean** [comment]
Ok, here is a design proposal.

**Core concept:**
"Atomic battery anything" no longer requires refueling. Instead it works like a UPS mod plugged into low-output charging station (charge rate is less than 1 / turn). This means that the new niche for atomic batteries is creating autonomous appliances. And the trade off is that power output is not great, so it's not suitable for power-hungry devices.

* Atomic battery mod. Works similar to UPS mod: provides some rechargeable power pool and constant but low charge rate. Like 1 energy per 16 turns (or less). This should be sufficient to power smaller appliances indefinitely (like flashlight or mp3 player), but if you use it to power something more power-hungry (like hotplate or jackhammer) you eventually will have to wait for it to charge.
* Advanced UPS. Works similar to the regular UPS that is constantly connected to low-output charging station. Charge rate is something around 1 energy per 4 turns. If you use it to power Power armor (which drains 4 energy per turn) it will last slightly longer than one in-game hour (`-t * 4 + t / 4 + 2500 = 0`). To fully recharge it you'll have to wait 16.6 hours. You'll need to carry 16 advanced UPSs to power Power Armor indefinitely. The niche: alternative for bionic power that is more autonomous.
* Atomic battery CBM (new). Provides unconditional constant charge rate of 1 energy per 4 turns. Occupies 10-20 torso slots. With this CBM alone 12 hours of rest will give you 1800 energy points or 3 hours of active Power Armor usage (if you have interface installed). Niche: addition/alternative for cable charger/solar panels that is more autonomous but less powerful.

**Comment by Tharn** [comment]
Batteries are already very abundant; certainly by the time you get UPS or vehicle solars going. This is just pushing batteries to become even more worthless. IMO plutonium cells should be reserved for a certain range of items that fit their high-tech / nuclear theme, and provide power over a long period of time for those items.

I'm in favour of the concept. Just not as a battery mod. Sticking a minireactor with lead shielding onto an electric hair trimmer wouldn't make for a very even shave. I guess the same goes for the mod that lets you use vehicle batteries - which is why it's so bad. It (rightly) tacks on the weight of the battery.

**Comment by Aivean** [comment]
@Tharn  please [read my comment above](https://github.com/CleverRaven/Cataclysm-DDA/issues/19989#issuecomment-271728677). Atomic batteries are NOT reactors. 

Certain isotopes do no require heavy shielding. As we discussed above, atomic batteries exist in real world, they are just not practical for most applications, mainly because of their price and low output. For example, they are used [in pacemakers](https://en.wikipedia.org/wiki/Betacel). 

As per batteries, at certain point they become useless anyway because of bionic power, UPS and recharging station. The point of this suggestion is to make atomic battery mod and advanced UPS useful by changing them into an alternative to regular UPS/bionic power.

**Comment by kevingranade** [comment]
> The in-game niches for atomic power:
Plutonium cells provide power for exotic scifi gadgets.
Atomic whatevers are perpetually powered joke toys.

**Comment by Aivean** [comment]
@kevingranade are you going to ignore the issue with atomic battery mod and advanced UPS being obsolete?

**Comment by kevingranade** [comment]
On Jan 12, 2017 5:50 PM, "Ivan Zaitsev" <notifications@github.com> wrote:

@kevingranade <https://github.com/kevingranade> are you going to ignore the
issue with atomic battery mod and advanced UPS being obsolete?

I'm really not certain that's an issue, as you said earlier:
> And I think that batteries becoming useless at certain point is natural
way of progression.

This is, by design, not a "well formed" game.  Not every item fits onto a
neat power curve, it's totally fine for some to be obsoleted by other
things or even outright useless.

Additionally, this issue is, "Could we have an electronics mod similar to
atomic lamp?",  not "atomic battery mod and advanced UPS (are) obsolete".
The answer to the former is, "no", and has been for 4 days, so there's no
reason to keep the issue open.

**Comment by CoroNaut** [comment]
Wow that is completely cold hearted. The initial suggestion turned into a technical debate over the uses of atomic items and its usages. There should be no reason to turn down a suggestion just because you don't want it yourself. If you yourself also believe that the atomic items are useless, then what is the problem with adding other things that other people would want? Also, the age of a suggestion should never be reason to terminate it. My evidence being all the other item, interface and game play suggestions still in the list.

**Comment by kevingranade** [comment]
On Jan 13, 2017 8:11 PM, "CoroNaut" <notifications@github.com> wrote:

Wow that is completely cold hearted. The initial suggestion turned into a
technical debate over the uses of atomic items and its usages.

That's not what GitHub issues are for, if you want to have an open-ended
debate, do it on the forums.

There should be no reason to turn down a suggestion just because you don't
want it yourself.

If someone wants to add tentacle monsters I should let them? No, turning
down suggestions that don't fit in the game is one of my responsibilities.
I did forget to mention that someone can feel free to add an "atompunk" or
whatever mod that adds more extensive uses of plutonium if they like.

Also, the age of a suggestion should never be reason to terminate it.

The only reason I brought up age was to point out that this issue had an
unequivocal answer 4 days ago, I guess I should have closed it then.

**Comment by CoroNaut** [comment]
Don't forget about this thread: #17086 This problem has been around for a while.

**Comment by Aivean** [comment]
Relevant: [small poll on reddit](https://www.reddit.com/r/cataclysmdda/comments/5nnp6w/has_anyone_used_atomic_battery_mod_or_advanced_ups/).

Results: no one reported to use atomic battery mod or advanced UPS. 

Advanced UPS is different from other useless items because it's not only json, there is dedicated code to support it.

**Comment by CoroNaut** [comment]
I love how I referenced the issue #17086 and it was immediately closed, it seems like there is no crap given about plutonium and its power at all. Perhaps a fresh issue about plutonium rebalancing is in order.

**Comment by kevingranade** [comment]
> I love how I referenced the issue #17086 and it was immediately closed,

Almost as if it prompted someone to review the issue and they came to some decision about it, we'll never know since it was closed without comment, oh wait it wasn't.

> it seems like there is no crap given about plutonium and its power at all. Perhaps a fresh issue about plutonium rebalancing is in order.

If you characterize these issues as "rebalancing", you have no idea what that means.  These issues propose completely changing the role of plutonium in the game.  It is that role change that has been rejected, not any rebalancing of the plutonium related items.

**Comment by Coolthulhu** [comment]
The issues of advanced UPS and atomic battery mod being useless are completely valid, though.

Do we want to buff them or axe them?

**Comment by kevingranade** [comment]
On Jan 20, 2017 10:54 AM, "Coolthulhu" <notifications@github.com> wrote:

The issues of advanced UPS and atomic battery mod being useless are
completely valid, though.

Do we want to buff them or axe them?

Leaning toward axing.

**Comment by Aivean** [comment]
@kevingranade is there a way to change your opinion on the matter?

**Comment by CoroNaut** [comment]
I'm actually glad we came to some decision about it, the plutonium stuff was balanced and realistic for some people while others thought it was unbalanced and out of proportion. This is exactly the reason why I sought for a rebalancing of the idea. Yes you can drop these items completely from the game, it may leave a gap but it can work. If these items are left in, they can be rebalanced so they have some use for either early **or** late game adventurers. 

Reasoning is tough ehh?
