### ISSUE TITLE
Check for no-VARSIZE but FIT items (upon savegame load?)

### ISSUE THREAD

**Issue by keyspace** [CleverRaven/Cataclysm-DDA#19996]
Brought up as part of #19988 (see for some discussion):

> Any items that were fitted before this change will stay that way, further lowering their encumbrance.

The change referenced is switching some items in JSON from having `VARSIZE` to not having it. That is, from being "fittable" and possibly having the `FIT` tag (flag?) to being "one size fits all", bu still retaining `FIT` tag if a previous save is used.

Have taken a cursory look, - `grep -R VARSIZE src` - and there seems to be no check for this. Such item would result in reduced encumbrance (compared to JSON definition). Haven't checked `grep -R FIT src` yet.

**Comment by kevingranade** [comment]
Added a check when FIT is applied so it doesn't give the encumbrance buff, Someone can clean up the non-matching fit flags on game load if they like, but I don't see the point.

**Comment by keyspace** [comment]
For reference, 7034c4040ba56532e6d450c9ed5ab7a966ab9ef3

Guess OK to close.

**Comment by keyspace** [comment]
Forgot what I saw while reviewing other uses of the flags - reopening.

The "subtle bugs" mentioned by @Coolthulhu in #19988 are, for example: items that still have `FIT` will have diplayed name and description modified. E.g. seeing in the inventory:

* pair of hand wraps (fits)
* pair of hand wraps

Very minor display issue, and goes away upon character death, but still confusing.

The underlying issue is, again as @Coolthulhu mentioned, "flags that need other flags to work".

**Comment by kevingranade** [comment]
Which is more confusing, the clothing that you specificically remember
modifying no longer saying it is modified, or that clothing continuing to
say it's modified, and (due to adjusting the underlying stats), acting
exactly as if it was in fact still modified?  The only time the latter
looks like a bug is if you compare a "fitted" item to an "unfitted" item of
the same type and realize that they have the same stats, but IMO that is
going to happen less often than people noticing that their clothes seem to
have lost some state, so it has lower impact.

**Comment by keyspace** [comment]
Chm, correct.

I imagined the save-loading code to have a `debugmsg` alerting the player that some properties are being removed from their items, a-la:

```
Item X that could be previosly fitted is now "one size fits all". This message is safe to ignore.
```

Would this be reasonable or annoying?

**Comment by kevingranade** [comment]
Annoying, never use debugmsg for things that aren't broken.
