### ISSUE TITLE
Changes to CDDA are difficult for the average player to follow

### ISSUE THREAD

**Issue by eScribMac** [CleverRaven/Cataclysm-DDA#19998]
Beyond [this](http://smf.cataclysmdda.com/index.php?topic=5877.0) thread, I'm not aware of any summary of recent changes and additions to the game. This makes it hard for the average player to follow the development or keep track of new features. I'd be willing to write a weekly changelog post on the forums, but I wanted to check here first to make sure there's nothing ongoing that I'm unaware of.

**Comment by kevingranade** [comment]
There isn't anything else right now, I'm sute it will be gretly appreciated.

**Comment by Asmageddon** [comment]
What if you had your builder bot include a list of changed based off commits? Additionally, add a "Summary:" tag for it to look for in said commits to use instead of commit messages. I think it would be a reasonable thing to do, and not much more than an adjustment for contributors to make.

**Comment by Zireael07** [comment]
@Asmageddon: @remyroy's launcher already does something like that.

**Comment by Coolthulhu** [comment]
A tolerably readable changelog could be created by getting all the contents of the posts in the changes thread and removing boilerplate and offtopic.

That could probably be done with a bot, by someone who has access to forum database or whatever it uses to store data.

**Comment by Asmageddon** [comment]
What I had in mind was the bot keeping track of changes, and putting a .txt file into the game distribution, and an option to view it. Also, I didn't know there was a launcher c.c

**Comment by charlesharris** [comment]
Consider letting git do the heavy lifting here.  The alias below is tweaked a bit from the one here https://coderwall.com/p/ch-wew/git-alias-to-generate-the-changelog

You could generate a changelog with an alias like this:
```
changelog = "!f() { r=${1:-`git describe --all --abbrev=0`..HEAD}; echo Changelog for $r; git log --no-merges --format='* %s' $r; }; f"
```

Here's an example of the output for some recent changes:
`git changelog HEAD~5..HEAD`
> Changelog for HEAD~5..HEAD
> * Changed the description of 6.54x42mm [Icecoon's Arsenal]
> * lint blazemod (and chill the buildbot)
> * Attempted to fix build error (#20105)
> * Trivial json cleanups.
> * Rebalance of cooking qualities for leavening bread

It gets a little messy with large merge commits like 9806ac246f80781382d8d6dc40bf690e4dba3ef8, and you might need to clean up or remove or edit some of the commit messages to prevent things that are confusing, uninformative, etc., but it'd be fairly quick to start out with and it can always be iterated upon if it's not really an acceptible solution.

**Comment by kevingranade** [comment]
On Jan 25, 2017 9:40 PM, "Charles Harris" <notifications@github.com> wrote:

Consider letting git do the heavy lifting here. The alias below is tweaked
a bit from the one here https://coderwall.com/p/ch-
wew/git-alias-to-generate-the-changelog


Here's an example of the output for some recent changes:
git changelog HEAD~5..HEAD

Changelog for HEAD~5..HEAD

   - Changed the description of 6.54x42mm [Icecoon's Arsenal]
   - lint blazemod (and chill the buildbot)
   - Attempted to fix build error (#20105
   <https://github.com/CleverRaven/Cataclysm-DDA/pull/20105>)
   - Trivial json cleanups.
   - Rebalance of cooking qualities for leavening bread

This is a perfect example, none of these commit messages would make it into
a final changelog, the ratio is something like 1:100.  Summarizing each
pull request would be a lot closer, if you have a way to do that it would b
a start, but I already start from raw commits and summarize them.
Part of the problem is that the commit messages might be a reasonable start
at a change log if users are also developers, but in our case they aren't.

**Comment by charlesharris** [comment]
All of that is totally fair.  Like I said, just a suggestion for a starting point to iterate from.

I wonder if it would be feasible to have devs mark/tag their commits that are "changelog worthy".  I know it's possible, but I'm talking about it being culturally feasible here. Combined with my original suggestion you could then maybe filter for those particular commits.  Or, alternatively, mark the "only relevant to developers" commits and exclude them.

I know summarizing things like this is not a simple, straightforward problem, so please don't take my original post as flippant or anything :)

**Comment by Asmageddon** [comment]
If you can configure a bot here on github to help with it, I still think that mandating inclusion of `changelog: ...` in PRs could help.

**Comment by kevingranade** [comment]
I'm not opposed to a summary field in commits per se, but its also one more
thing contributors need to do, and requires automatic enforcement.  Make
enforcement manual and its just going to end up not happening, meaning
someone (me) is going to end up reading 10s of thousands of commit messages
to make the changelog anyway.

Probably we could have the build bot check that such a field exists for
each PR and fail the pr build if its not present, someone feel free to look
into that.
