### ISSUE TITLE
Proposal for batch-crafting failure modes based off time scaling.

### ISSUE THREAD

**Issue by Asmageddon** [CleverRaven/Cataclysm-DDA#20009]
E.g. to resolve the common "why does everything fail at once" complaint.

The concept is simple: Look at how much time to craft one unit is reduced compared to crafting just one, and use it as a basis to decide how many of the products will be rolled for success individually.

The overall formula would be something such as: ` floor((time_to_make_all - time_to_make_one) / time_to_make_one)`, for example:

If it takes 10m to craft 1 itemA, and 33m to craft 5 copies, 2 would be rolled for success individually, and depending on how many succeeded, the message would say "You fail all but N", or "You succeed all but N".

In case of products for which the crafting time per unit stays constant, all would be rolled individually, in case of products like diesel where time is independent of batch size, all would be rolled at once.

Thoughts?

**Comment by CoroNaut** [comment]
Why not just have batch mode calculate them all individually to begin with and have a skill bonus to making that item when the game calculates the next item to craft. You would have the recipe in mind after the first one and would be able to do the second recipe at least a little easier. This would be a simple progression system for batch crafting and would give a small benefit to anyone who uses the feature.

**Comment by Aivean** [comment]
@CoroNaut some of the recipes require progressively less time when crafted in batch. So it's not as simple as rewriting batch craft as one-by-one craft in loop.

And then again, what's the point to have batch craft in the first place if it's just a looped one-by-one craft? You can craft once and press `-` N times as opposed to pressing `b` and `↓` N times.

**Comment by CoroNaut** [comment]
Yes, I do know that, but you wouldn't need to rewrite anything. It would be as simple as trying to batch 10 items, but stopping at the 5th, the time would calculate to this point, give you your 5 items, and cancel the batch craft.  

Also, the batch crafting is there specifically so you don't have to repeatedly press the - key. If we allow batch crafting to give items while it is in the process, it would be both convenient and eliminate the issue.

**Comment by Coolthulhu** [comment]
Longcraft and batch craft are two separate things.

Longcraft is "craft then craft again".

Batch craft can't be stopped halfway because it is only processed at the very end of the craft. Changing that would require rolling for failure at start.

**Comment by CoroNaut** [comment]
Crafting the same thing 5 times without batch craft should be close if not equal to batch crafting those 5 items. Why wouldn't you be able to stop half way? Shouldn't the player have the ability to stop crafting in the middle of their batch? If the player is interrupted from making bandages by a zombie for instance, the craft may be paused, but its very possible that progress can be lost (and lose all work no matter how much time it took). If you already spent much more than the time required to craft 1 bandage, why don't you get it in this circumstance?

I don't see what you mean by "require rolling for failure at start". It would be best to roll for each item individually, and perhaps use what I said before about adding a tiny skill bonus for each consecutive item. The time would just be calculated as it would be normally. It would allow a player to batch craft 20 and stop at 5 to have the same outcome as just batch crafting 5.

If you ever thought "Oh crap, I wanted to use that resource for something else" and you couldn't end the batch of 20 or whatever, you would be sad.

**Comment by Greiger** [comment]
Maybe I'm imagining batch crafting wrong but I always imagined it not as just making a bunch of individual items one at a time but making them....in a batch.  You can scramble eggs two at a time.   Or you can scramble a half dozen at once and save a whole lot of time.  

In that case if you screw up and ruin it yer not gunna come out with one or two that are still good.  No the entire batch is going to be ruined.  Maybe if you were batch crafting something that did not save time by crafting a bunch at once, then yea you could realistically have a few that worked and some that didn't.   But if you batch craft a 6 batch of soup you are not going to end up with 4 good soups.  You will have 6, or 0.

**Comment by Aivean** [comment]
I think there is some conceptual difference between batch craft and repeated craft. The fact that the time to craft batch can be less than the time to craft the same number of items one by one can indicate that when crafting batch you "reuse" part of the work.

Let me explain by example. I could find two recipes that take less time when crafted in batch: clean water and broth. In real life boiling 2 liters of water at once will take less time than boiling four times 1/4 liter of water (the boiling itself will take the same time, but auxiliary actions, like lighting fire, pouring water, etc, will take additional time). 

This also means that when trying to boil the whole volume of water at once if something goes wrong you'll lose the whole batch (well, not always, but often). For example, if you forget to light a fire, you won't get partially boiled water. However, if you tipped over a kettle after boiling finished, you might have something left.

This gets more complicated for crafting distinct items. But still, it's possible to explain. For example, before crafting two bandanas you might try to prepare the piece of fabric for both of them. If you screw up the process you won't be able to get a single bandana.

**Comment by Greiger** [comment]
Just want to add an extra little note:   I'm not opposed to the idea in general.  Being able to screw up only a few in many things sounds great.  Even some things that share some minor steps to save a little time.

But when something shares a MAJOR step, such as the actual cooking of most batches of food, there should definitely be something in place to prevent you from getting partial results where it would sensibly not be possible.

**Comment by Aivean** [comment]
Also I can think of one case when current batch behavior is much more beneficial than alternatives. Btw, this may be a reason to revise it.

Suppose you have ingredients only for ten items. And it happens that you need to craft exactly ten. Let's say you know the success probability for one item. Let's say it's 0.9  (or 90%). What is the chance that all ten items will be crafted successfully? It's 0.9<sup>10</sup> ≈ 0.35, or 35%. Now if you craft the batch of ten, you'll have the same chance of success as when crafting one item, 90%. 

See the difference? In this case it's far more wise to craft items in batch. 

P.S. I intentionally didn't mention chance to fail without losing ingredients, because it's irrelevant. It's already included in "success" chance.

**Comment by Asmageddon** [comment]
Alternative to my proposal system, likely more sensible but also considerably more involved, would be to introduce a flag for individual success rolls.

**Comment by CoroNaut** [comment]
This is where my idea of adding a small skill bonus to each consecutive item comes into play. Batch crafting 10 items at 90% chance would lead to 35% that they are all fine when calculated all at the end. As you are crafting however, you have the recipe fresh in your brain and can repeat the same process with less time and with more quality. Hence my idea would make more sense in this scenario.

There is the problem that we have many different types of batch crafting available such as boiling water, making shirts, making CBMs and others. In the case of boiling water, you would obviously have that all in one pot and boil it together. With the shirts, you would need to cut the fabric for them together or individually and then assemble them individually. With the CBMs, you have one whole item that you need to craft individually. Crafting CBMs would easily fit with any idea because they are individual items. Shirts would require some work to get right considering you can make them individually or cut up all the supplies together. Finally, boiling the water would have to stay as it is because it is just common sense to boil it all together. 

Overall, I will be opting for the idea that accurately represents what common sense would tell you to do to craft the objects.

**Comment by HotSake** [comment]
If you want to change the failure mode, could it simply depend on whether there is a time discount for batch crafting? If there is no discount, then assume the items are crafted individually and allow partial success. If there is a discount, then assume some crucial step is done together and use total failure as it is now.

Because the batch crafting bonus is defined per item, this would avoid having to add another flag or change the JSON at all. There are two batch modes, and which mode an item uses is implied by whether it's definition gives a batch bonus.

**Comment by Asmageddon** [comment]
Yeah, but most items do have a discount, it just tends to be small.

**Comment by Night-Pryanik** [comment]
Closing as per lack of discussion.

**Comment by Asmageddon** [comment]
Another issue that I feel shouldn't be closed.
