### ISSUE TITLE
Character should use blankets/clothes to keep warm while waiting (And maybe reading?)

### ISSUE THREAD

**Issue by ReservoirHeadcrab** [CleverRaven/Cataclysm-DDA#20058]

**Comment by sethsimon** [comment]
Great idea. Some related (but closed due to inactivity) issues: #14364, #12455, #1197. Currently activities have a `rooted` flag, which makes recoil decrease and plant mutants gain nutrition from soil. It would make sense for that flag to also determine whether you can wrap yourself in clothing for warmth.

I think that when this is implemented, there should be time, dexterity, etc. penalties for unwrapping the blankets if any clothing is being used, whether sleeping or just resting. Otherwise you could attack, dodge attacks, etc just as easily as if you were standing and active (that always ruins the immersion for me when I get attacked in my sleep).

**Comment by Leland** [comment]
Closing - no movement here for some time. Some good ideas presented; if anyone wants to work on this or discuss further just ping me and I'll reopen.
