### ISSUE TITLE
Fermenting bug

### ISSUE THREAD

**Issue by AMurkin** [CleverRaven/Cataclysm-DDA#20077]
Fermenting curdling milk gave message on examine of vat:
```
//iexamine.cpp#L2033
debugmsg( "fvat_full was empty!" );
```
actual windows tiles

**Comment by AMurkin** [comment]
Can't reproduce in newest version.

**Comment by Coolthulhu** [comment]
I didn't test it, but vat-related code wasn't changed, so it shouldn't be any more fixed than back then.

Try to test it by advancing time a lot using debug menu. Few years. Then move away from the vat to remove it from reality bubble and come back.

I suspect the bug is caused by fermenting milk rotting away - fermenting vat doesn't seem to prevent that from happening and it doesn't actually "turn things fermented" until player interacts with it.

**Comment by AMurkin** [comment]
I've tested it by moving away for a short time and for 8 hours required to complete the fermentation.
Both times got gebug message and empty vat.
![vat-debug](https://cloud.githubusercontent.com/assets/1931904/23330016/6b2cf674-fb55-11e6-8b68-233fa04a07b9.png)
