### ISSUE TITLE
Cannot make doors in wilderness setting without nails

### ISSUE THREAD

**Issue by DangerNoodle** [CleverRaven/Cataclysm-DDA#20086]
Recently I realized that, playing in a wilderness scenario, there is no way to build a door that does not require nails, unlike with log walls that can be built in the forest with tools and materials available there.

I noticed that there were options to make a door curtain and a makeshift door, and the former allowed alternatives such as spikes or pointy sticks instead of nails. But this was made a moot point by requiring a door frame. Maybe door frames should also permit use of those alternatives? Either that, or door curtains should not require door frames as a prerequisite.

**Comment by pisskop** [comment]
wooden pegs should be feasible, and a sliding door or liftable door a thing

**Comment by DangerNoodle** [comment]
Possibly. What would be the best method of implementing this, at least for door curtains (which presently seems useless)?

**Comment by Leland** [comment]
There was some worthwhile, relevant discussion over at #8109. I personally think creating a wilderness-craftable alternative to nails is a great idea.

**Comment by DangerNoodle** [comment]
I see. Quite an old discussion that went no where in terms of implementation, unfortunately. There is no a recipe for hand drills, but they require metalworking capability.

One solution might be to add a recipe for a makeshift hand drill operating as is shown in the issue discussion. How should this be handled though? Given hand drills are evidently meant to be balanced by tedium, adding more time to use a makeshift version might be realistic but a terrible balancing mechanism.

A possibly better idea would be to exclude makeshift hand drills from any recipe that requires drilling through metal or other non-wood objects.

Finally, there are two ways to implement this in construction. One would be to simply add redundant recipes that allow for different tools and time taken. This would be overall simplest, but may be seen as undesirable unless the drill-and-peg method was applied sparingly, such as mainly only with walls and door frames.

A second method would require either hard coding to add alternatives (impractical and unlikely to ever be implemented), or some way to combine tool and component requirements so that either a hammer plus nails or a drill plus pegs (not possible as far as I know).

**Comment by Headjack** [comment]
> I see. Quite an old discussion that went no where in terms of implementation

Well, we did get the tree shelter actually.

It ought to take ages. those drills are really inefficient, and it doesn't need to be balanced against nails if the alternative is not building anything at all. It's a workaround, not a competitive alternative.

Your method two is only viable if the alternatives can be made to take a different length of time, which I don't know if is possible. Method one is the best bet, since ever-longer menus is usually the go-to solution for additional crafting options. 

It'll also need to add a simple pegs or trunnels item that takes a bit of construction and survival, and the drill with some string, wood, and a sharp stone. A binding agent is needed to attach the bit, so that's going to mean pitch from pine tar, and so a few pine boughs too.

**Comment by WizardOfOoo** [comment]
I'm in the door curtains should not require door frames as a prerequisite camp.

Might just be able to change a few lines in construction.json
Change line 193 to read "        "pre_special" : "check_empty","

And figure out how to change it so that if you smash a door curtain down it doesn't leave a door frame behind.  And make the durability really low.

**Comment by DangerNoodle** [comment]
I could have sworn that door curtains did not require a door frame to begin with. I can change that perhaps.

**Comment by WizardOfOoo** [comment]
I think I see where it could happen in the code.

While I'm there I'm looking at smashing.  Smashing it is currently "str_min": 3, "str_max": 6, maybe lower it to "str_min": 1, "str_max": 4?  It's a blanket and four nails.  I don't think that would stop much anything

**Comment by WizardOfOoo** [comment]
From construction.json

```
{
        "type" : "construction",
        "description" : "Build Door Curtain",
        "category" : "CONSTRUCT",
        "difficulty" : 1,
        "time" : 30,
        "qualities": [ [
            { "id": "HAMMER", "level": 2 }
        ] ],
        "components" : [
            [ [ "nail", 4 ], [ "pointy_stick", 2 ], [ "spike", 2 ] ],
            [ [ "sheet", 2 ] ],
            [ [ "stick", 1 ] ],
            [ [ "string_36", 1 ] ]
        ],
        "pre_terrain" : "t_door_frame",
        "post_terrain" : "t_door_curtain_c"
    }
```

**Comment by DangerNoodle** [comment]
Reducing the minimum and maximum for smashing would be a good addition. I assume replacing `"pre_terrain" : "t_door_frame",` with `"pre_special" : "check_empty",` would be the normal method of changing how it is built, or at least copying the prerequisite door frames use.

Likewise, I will need to change the bash `ter_set` to match the result of smashing a door frame.
