### ISSUE TITLE
First Aid Kits not consumed when healing NPCs

### ISSUE THREAD

**Issue by MystiaLorelei** [CleverRaven/Cataclysm-DDA#20090]
Using first aid kits to heal your own wounds consumes uses as expected now after the fix, but using a kit on an NPC follower does not. I'm not sure offhand exactly what else you're allowed to directly use on NPCs, so did not test other any other drugs or consumables. So this might extend to all other medical items.

To reproduce: Get an NPC follower, go get them beat up by something hostile and try to heal them with a first aid kit from the examine menu.

Running Windows, 0.C-20814-gac528f64f8 (tiles) \ Build 6165

**Comment by DaliTimelord** [comment]
Verified.

**Comment by didemaGibson** [comment]
Same with bandages, peroxide, and disinfectant.

**Comment by kolsurma** [comment]
Got it, but I've got a question.

Do we want to check the item type before calling a function or do we check in the function?
E.g. in this case consume_charges has a check if item is of a usable type, but the method was performing a check before calling consume_charges and was silently failing.

**Comment by Coolthulhu** [comment]
It worked fine earlier, must have been broken by one of the changes that introduced more proper med/food split.

> Do we want to check the item type before calling a function or do we check in the function?

I think the check within function is more common.

I'm not sure if there aren't any edge cases. Item use code is a bit convoluted like that - you never know where is the check supposed to go. It needs a cleanup.
As long as the check is done consistently in the same way, it should be fine.

**Comment by kolsurma** [comment]
I believe it started occurring when people started adding NPCs back into their worlds.

Rags may be an edge case anyway, since they're not technically a medicine, but at the same time are. They have no inherent charge, but transform into a different type when used. 

I just traced the way items are converted (rag -> bloody rag), that could possibly be moved to either a better named function, or incorporated into player::consume_charges.

code in question:  heal_actor::finish_using

```
    if( !used_up_item.empty() ) {
        // If the item is a tool, `make` it the new form
        // Otherwise it probably was consumed, so create a new one
        if( it.is_tool() ) {
            it.convert( used_up_item );
        } else {
            item used_up( used_up_item, it.bday );
            healer.i_add_or_drop( used_up );
    }
```
The code just seems so redundant in places.
