### ISSUE TITLE
The Milk Dialemma

### ISSUE THREAD

**Issue by TheWebfrog** [CleverRaven/Cataclysm-DDA#20113]
![](http://i.imgur.com/pa40STS.jpg)

Ahh milk, one of natures fabled delights, milked straight from the cow this fresh and tasty treat is considered a staple in many communities.

But what happens when your milk goes bad, an event which happens so regularly that it almost needs specialised packaging and storage to be viable.

In Cataclysm these facts are not ignored, with milk still being a common house drop, and often appear in other loot tables.

**BUT WHAT HAPPENS WHEN THE MILK GOES BAD**

The way that Cataclysms perishable foods work is when the food goes past it's predetermined best by date it automatically tags the food as (Rotten). After even a couple hours in the Cataclysm you will see milk spoiled everywhere, as far as the eye can see.

**BUT WHAT IF THE MILK WAS NOT ROTTEN**

As of the current build milk and other foods tagged as (Rotten) can be exploited out of that tag. Here are the ways I have found to do so.

* Moved rotten food into a vehicle tank, and move out of a vehicle tank. This works with any perishable liquid

* Change it's state via crafting. A more obscure way to do so, it still does no at all supply an explanation. Milk and presumably eggs can both be turned from "Powdered Milk" back into "Milk" meaning that even (Rotten) tagged milk can return to its non-rotten state.

**PROBLEMS WITH THE CURRENT SYSTEM**

* Milk and other perishable liquids can be turned from (Rotten) to not rotten using the new "Every liquid allowed in the vehicle tank" system.

* Crafting does for whatever reason **NOT** exclude (Rotten) tagged foods from crafting recipes, allowing for exploitation.

* Abundant amounts of milk in some locations, as to the point of absurdity ( Tea shop and possibly Coffee shop ), as realistically these locations would have powdered alternatives for more long-term storage.

* Possibly a reworking of Milk perish rates, as even 8 hours seems a bit harsh for a milk to go straight from the cow to fully inedible.

Thanks for consideration and reading all the way to the end!

**Comment by Coolthulhu** [comment]
> Crafting does for whatever reason NOT exclude (Rotten) tagged foods from crafting recipes, allowing for exploitation.

This is an old problem that might be soon fixed due to reworks in crafting system.

**Comment by ZhilkinSerg** [comment]
I'd like to have a milk tank in my car... If I had a car.

**Comment by Barhandar** [comment]
Not to mention that normally milk _sours_ instead of outright rotting, and remains perfectly edible for a long time after that, and is even intentionally fermented for sour cream, kefir, airan, etc.

The exception to souring is ultrapasteurized milk, which simply lacks enough of proper bacteria to go sour, and goes inedibly rotten and bitter instead. However, such milk also takes months to spoil _unrefrigerated_ as long as it's still sealed.

**Comment by Asmageddon** [comment]
@Coolthulhu What reworks are we talking of? I'm interested in that.

**Comment by kevingranade** [comment]
On Jan 29, 2017 1:13 PM, "Barhandar" <notifications@github.com> wrote:

Not to mention that normally milk *sours* instead of outright rotting, and
remains perfectly edible for a long time after that, and is even
intentionally fermented for sour cream, kefir, airan, etc.

Soured milk is not the same as fermented milk.  The difference is the kind
of organism that is growing in it, some produce toxins that don't affect
people in small doses, others do.  The safest default is to treat soured
milk as dangerous and inedible.  If you can find some stats on varieties of
soured milk, we could look at making things more specific.  Regardless,
soured milk isn't an acceptable substitute for fresh milk in recipes.

I believe the crafting rework would prevent rotten ingredients from being
used in crafting.

**Comment by didemaGibson** [comment]
There could be two different types of "wild" milk: the pasteurized stuff you'd find in grocery stores, coffee shops, etc. and unpasteurized raw milk that turns into clabber when it sours and make that only available on farms.

I wish there was more you could do with rotten milk except pour it out and use the gallon jug. Stink bomb maybe? Apply (ugh) to mask human scent?
