### ISSUE TITLE
[Suggestion] Add a no-specials grace period of configurable length to the start of the game

### ISSUE THREAD

**Issue by Barhandar** [CleverRaven/Cataclysm-DDA#20167]
Currently, meeting any of the acid zombies before you have a gun or acid protection is death. Having a grace period during which _no_ specials can be encountered, not even "base" varieties, regardless of spawn types, would let the players find guns and/or acid protection without getting lol-killed. And having it configurable, from no grace at all to some arbitrary time, allows those who want the loldeaths to continue with them.

**Comment by CoroNaut** [comment]
I presume this will break some scenarios similar to Challenge-Abandoned where you start within a hospital against the very difficult spitter zombies.

Also, you are supposed to be starting out 5 days after the bombs drop and that there is over 99% zombification. [Timeline](http://cddawiki.chezzo.com/cdda_wiki/index.php?title=Timeline). If you start off seeing 0 zombies in a large town, or even less than what challenging monster rate you have set, it may break immersion. Mostly because you would see a barren town for no reason.

The game wants the player to be able to be able to be killed at any moment. Under this pressure, it forces the player and the survivor to make the best decisions to keep themselves alive. If the survivor can just roam freely for a while, it may break this balance.

**Comment by Barhandar** [comment]
Not zero zombies. No _special_ zombies, aka no "lol you're too slow from the cold to run away from the sure-death-melee acid zombies that are not affected by the cold at all" zeds, or brutes.
>Also, you are supposed to be starting out 5 days after the bombs drop

In which case you would be equipped or dead already, and a significantly larger portion of the game than zombies stops making sense (to start: half the professions + weather = you would be dead to exposure already, starting locations with no warming-up-things like braziers + weather = dead to exposure, even without weather half the professions' equipment is nonsensical for having 5 days to prepare), unlike than with "8 hours after the Apocalypse".

**Comment by Coolthulhu** [comment]
There once was an offset time in zombie evolution setting. Not sure why and when it went away.

I'd say it would be a better way to solve it than strict grace period. We could have all zombies start bland, then immediately start evolving.

Alternatively, setting the starting season to autumn, as someone (PK?) suggested, to avoid having to deal with the cold.

**Comment by Barhandar** [comment]
>I'd say it would be a better way to solve it than strict grace period. We could have all zombies start bland, then immediately start evolving.

They more or less already do that, the problem is that they evolve from basic specials, as opposed to differentiating from plain, nothing-special zeds. So even with evolution slowed down to the point of being absent you'll still see basic boomers, basic acids, basic hunters, basic swimmers, etc.

**Comment by ReservoirHeadcrab** [comment]
Sounds like a good easy mode start for new players to get familiar, it may be easy to implement with the new zombie mutation system?

You do come off as rather whiny though. You don't need acid protection or guns to deal with acid zombies. If you have problems with temperature because of your starting profession (Ex. Hobo) just make clothes out of curtains.

**Comment by keyspace** [comment]
> I'd say it would be a better way to solve it than strict grace period. We could have all zombies start bland, then immediately start evolving.

This is the proper solution IMO. Currently, there are monsters in `GROUP_ZOMBIE` (`data/json/monstergroups.json`) that might be considered "evolved".

Addressing this one group is insufficient, though, since there are other location-based ones.

Not sure if possible, but that file could also use `copy-from`, `extend`, etc..

Related:

* Monster upgrading might not be entirely balanced #12313
* Hordes contain excessive numbers of shocker brutes #14692
