### ISSUE TITLE
Advanced inventory 'm'ove autofills dialogue

### ISSUE THREAD

**Issue by sick-trigger** [CleverRaven/Cataclysm-DDA#20234]
Using 'm' for moving part of a stack in the advanced inventory now automatically fills the dialogue box with the full size of the stack, when it used to start empty. Means you now have to backspace every time you use it. If you wanted to move the whole stack you can just use upper-case 'M' instead.

possibly related: when searching in the wish-for-item menu the cursor now always starts at the beginning, even if the box already has something in it from a previous search, when it used to start at the end of any text. Means you now have to move the cursor back to the right or END when spawning different types of items.

both present in build 6217, but not 6208 (latest previous successful build). Possibly from #20033?

**Comment by keyspace** [comment]
Confirming both issues, haven't bisected.

Arch Linux, curses, self-built, lastest git master (`0.C-21086-g3aea92e4fd`).

**Comment by keyspace** [comment]
Doing a bisect, confirm PR #20033 as culprit. Bisect is skip-stuck (doesn't compile without modification) on commits in the PR: here's [the log](https://gist.github.com/keyspace/416ed8d6a65d9222a22a7f6ff43cfef3).

Noticed another issue: when moving part of stack with `m`, pressing `ESC` still moves the whole stack, even in a smaller number was entered. Expected behaviour is to cancel moving.

**Comment by keyspace** [comment]
"Amount auto-filled" can possibly be corrected [on this line](https://github.com/CleverRaven/Cataclysm-DDA/pull/20033/files#diff-570f284881dfa11d0f06697a7e5fe6dcR2154).

"`ESC` moving instead of cancelling" - [a few lines above](https://github.com/CleverRaven/Cataclysm-DDA/pull/20033/files#diff-570f284881dfa11d0f06697a7e5fe6dcR1654), but requires reviewing function's logic.

**Comment by kevingranade** [comment]
Both issues still present after a number of fixes.

**Comment by kolsurma** [comment]
Haven't touched this particular issue.

**Comment by keyspace** [comment]
@kolsurma it used to start empty, which seems desirable to me.

When `m` is pressed to move a custom-sized stack, pre-inserting a 0 in would mean that it'd have to be erased anyway.

**Comment by kolsurma** [comment]
The reason I asked was because the offending code passes the amount by reference into 
`void string_input_popup::edit( long &value )` and `long` can't be empty so...

The easy thing to do there would be to remove `text( to_string( value ) );` or change which function it calls. At the moment, `advanced_inventory::query_charges` is the only thing that calls this function. I'll try the former first.
