### ISSUE TITLE
Changes to Monster Definitions

### ISSUE THREAD

**Issue by GlyphGryph** [CleverRaven/Cataclysm-DDA#2024]
In preparation for the combat changes I'll be working on over the next two months, I'll need to make the following change to monster definitions. 

This is a work in progress, and may not be the final form for this feature!

Note that as a players skill and knowledge of the particular monster rises, they will become more likely to avoid armor and hit weak points:

regeneration: 3.4, //The amount the monster heals every one hundred tics. Can contain fractions
cut_resist: 10, //The monster's resistance to cutting damage, as a percent.
bash_resist: 25, //The monster's resistance to bashing damage and sudden forces
pierce_resist: 5, //The monster's resistance to holes being made in their body
armor: [
  [ 25, "chitin skin", 2, 1], //Name, armor coverage percent, flat damage prevented by hard layers, flat damage prevent by soft layers. Hard armor absorbs cutting damage better. Soft armor absorbs bash damage better. A monster may have multiple armor values.
  [ 60, "chitin shell", 10, 2] // Armor that would bring the value above 100% is ignored, as armor is applied on a first come first served basis. Weak points work from the same percentage, so putting armor percents too high will force out weak points.
]
weak_points: [ //A monster needs weak points to be susceptible to criticals
  [ 5, "eyes", 100, 0, 0, 15, "BLIND", "BLIND"], // Likelihood of part being hit, part name, bonus damage, hard armor, soft armor, total health before being destroyed, and conditions partially inflicted if part is damaged, followed by conditions inflicted if part is destroyed.
  [ 5, "brain", 300, 0, 0, 30, "STUPID", "LETHAL"]
]
##

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
