### ISSUE TITLE
Escape from lab challenge/prison break with z-levels

### ISSUE THREAD

**Issue by Chezzo** [CleverRaven/Cataclysm-DDA#20279]
Currently, enabling z-levels lets you just hop right over the walls in lab challenges/prison break, using the go upstairs key, on a downstairs (t_stairs_down) in a corner. 

I think evac centers have roofs, prisons and labs should too.

**Comment by 1skandar** [comment]
Evac shelters have roofs, this trick works anyway. I'd have to do some checking, but with z-levels enabled you can do this in any corner.

**Comment by DangerNoodle** [comment]
I was going to say, I expected that the it was a matter of evac shelters having `t_floor` in place of `t_rock_floor`, but prisons have wooden floors as well.

However, tested in an older build due to having not updated recently.

![possible regression](https://cloud.githubusercontent.com/assets/22048567/22991888/6f95b270-f383-11e6-92c0-dd39ef822acb.png)

I need to try additional corners, it might simply be a solid wall directly above this corner.

**Comment by DangerNoodle** [comment]
Debugging confirms that sidewalks were above, not walls.

**Comment by Chezzo** [comment]
Thanks for the fix DangerNoodle.

I thought it was weird because the top lab floor WAS t_floor, but it turns out the exploit, in both prisons 
and labs, is from on the stairs.

**Comment by DangerNoodle** [comment]
I assume this means downstairs require a roof as well? Thank you for pointing that out, I can add that to the pull request as well.

**Comment by DangerNoodle** [comment]
Also realized that open doorways could be exploited if generated in a corner, and possbily constructed doors as well. Will add these as well.
