### ISSUE TITLE
Acid should not be able to "break" your legs

### ISSUE THREAD

**Issue by chaos-dev** [CleverRaven/Cataclysm-DDA#20293]
This is a simple mechanics issue. When your limbs get to zero health, they become "broken" limbs.  This makes sense for your typical combat, but it doesn't make sense for some situations.

One example is acid.  If you stand in a pile of acid from a dead acidic zombie, your limbs will slowly deteriorate to where they have 0 hp and are "broken".  But tell me, how will splints help my legs recover from chemical burns?  Why do I need to use splints to get them back up to some positive health?

**Comment by pisskop** [comment]
It does.  Or at least can.

The issue isnt with acid 'breaking' your legs.  Its never actually called a 'broken limb'.  Simply its implied by the use of a splint.

But, a splint could be used for keeping a limb immobile even if it isnt broken.  And protected from physical harm as you inevitably continue dangerous tasks in a dirty world.

Similarly, stem cell injections make perhaps even more sense for acidicly destroyed limbs than broken bones.


But, the concept behind acid isnt that it breaks your limbs, its that they become dis-functional to the point of uselessness by the acid.  Think showing bones and massive pain.


This sounds more like it should be about an oversimplified medical system than acid killing your mobility ... which I encourage.  Acid in game is perhaps slightly too common due to zombies, and perhaps overly powerful an effect (still), but reducing your mobility is preferable to being physically harmful to your hp.  This puts corrosives and spitters into a distinctly 'support' role and also nerfs the usefulness of things like survivor wetsuits (which are basically acid-immune backpacks, as ludicrous as that is) by consequence.

**Comment by chaos-dev** [comment]
> This sounds more like it should be about an oversimplified medical system than acid killing your mobility ... which I encourage.

I agree.  The acid should be able to give you sever chemical burns on your legs, but splints shouldn't be the **_only_** way to repair them (or even a valid way to heal them). I'm ignoring stem cell injections, of course, since low-level players rarely have access to them.

**Comment by kolsurma** [comment]
Seems to me that instead of 0hp 'breaking' something it should apply a flag depending on the type of damage it received. Bash/cut/pierce would apply the 'break' flag, acid/fire would apply a 'burnt?' flag, and so on.

**Comment by kevingranade** [comment]
There's no implementable proposal here, if someone has a proposal for how acid *should* act, feel free to open an issue outlining that, but "shouldn't work like other damage" isn't something we can take action on.
