### ISSUE TITLE
Idea for new vehicle part (Astral Shift Module)

### ISSUE THREAD

**Issue by NaturesWitness** [CleverRaven/Cataclysm-DDA#2029]
When looking at kevingranade's pull request for a folding bike, it gave me an idea for a cool item; The Astral Shift Module.  When installed on a vehicle, you can "shift" it to the nether dimension while standing next to it, and recall it later at a different location when you need it. Would have to be balanced (Very hard to install, shifting takes a large amount of energy, and has a chance to spawn void creatures on recall) but it could be a really cool "superscience" thing to have ingame.  Would make a cool "end stage" reward for bottom of a Lab, maybe with logs and things saying it was something they built during their research of the nether dimension that caused the cataclysm.  Anyone know if I this is doable, interesting, game-breaking, idiotic, or whatever?
##

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
