### ISSUE TITLE
Weapon Types for the melee combat rewrite

### ISSUE THREAD

**Issue by GlyphGryph** [CleverRaven/Cataclysm-DDA#2030]
The following types of weapon will exist, defined by the damage it deals.

Cutting : Cutting weapons deal damage by applying sliding force along a narrow ridge. They are effectively stopped by hard armor, but less so by soft armor. Cutting damage is the most effective type of damage for crippling enemies without requiring targeting weak points (reducing effectiveness by cutting muscles, tubes, or cables, causing bleeding in the process). Armored enemies tend to be particularly resistant to cutting weapons, while triffids and animals tend to be particularly susceptible. Crippling attempts tend to cause heavy bleeding in the target and render them unable to move or attack as effectively.

Cutting injuries are usually serious but "clean" and enemies with high regeneration rates, such as zombies, will recover from them fairly quickly.

Force : Force weapons deal damage by imparting large amounts of force across a fairly wide area. Force is best absorbed by soft armor, although hard armor will still dampen the force applied. Triffids are particularly resistant to force weapons, while Zombies tend to be particularly susceptible. Crippling attempts tend to slow or stun the target, leaving them open for further strikes.

Force injuries tend to do lots of pure damage, distorting shapes in ways though could not be describes as "clean" (think of the difficult in repairing an item which was cut in two versus one which was shattered) which takes significantly more effort for regenerating enemies to heal from.

Piercing - Piercing weapons deal damage by focusing their force into a narrow point of force directed directly into the enemy. They are not as accurate as cutting weapons or as damaging as shock weapons. They are less directly effective at at dealing overall damage than other weapons, but the same focused damage makes them superior at punching through armor and exploiting weak points. Fungaloids, bereft of critical locations to hit, tend to be very resistant against piercing weapons, while robots and insects tend to be weak to them, focused as they are on effective armor protecting vital weak points.

Piercing damage is usually the easiest for enemies to recover from, except for piercing attacks which cause objects to be lodged in, which are the hardest.

Although these are the three primary types of damaged, there are others:
Energy (lasers, fire, electricity) - Very effective against fungaloids.
Chemical (nerve gas, acid rain, smoke, poison) - Effective at bypassing armor and attacking prime health directly, different types effective different targets and materials. Has specific counters. Especially good against fungaloids and triffids and animals.

Some guidelines on the kinds of damage various weapons would do:
Swords - A good balance between the different damage types, but best at cutting. Stabbing attacks lose their bashing advantage for a bonus to piercing.
Axes - A good balance between the different damage types, but best at piercing - the power behind their swings allows effective punching through enemy armor.
Knife - Primarily cutting and piercing damage.
Warhammer - Exclusively bashing and piercing damage, leaning more towards piercing.
Quarterstaff - Exclusively bashing damage.
Spear - Primarily piercing with some cutting damage as well.
##

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
