### ISSUE TITLE
Consider additional time when interacting with things

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#20312]
It takes 6 seconds to throw grenade with bare hands, and it takes the same 6 seconds to throw it with my character holding large and heavy jerrycan full of water, for example.

There is related issue that we can activate, throw etc things right from the inventory with no need to take things in hands prior to interacting with them. I see two possible ways to cope with this matter (on throwing example).

- Simply add additional time needed to carry out process like "unwield if there's foo wielded -> take bar in hands -> throw bar -> take previously wielded foo in hands".
- Or make player automatically and explicitly execute aforementioned process prior to throwing.

**Comment by kevingranade** [comment]
The latter is the better option, it keeps things more consistent if e.g.
the action is interrupted or peevented, and keeps the cost from getting out
of date if the related actions are changed.

**Comment by Coolthulhu** [comment]
> There is related issue that we can activate, throw etc things right from the inventory with no need to take things in hands prior to interacting with them.

Do we? #20325

**Comment by DangerNoodle** [comment]
I do not think we need to add further time management. Expanding time management to other actions is prone to causing consequences that are not needed while attempting cleanup and preparation for

Take the extention of this idea to activating items for example, and see issues https://github.com/CleverRaven/Cataclysm-DDA/issues/19899 and https://github.com/CleverRaven/Cataclysm-DDA/issues/20325

**Comment by kevingranade** [comment]
On Feb 19, 2017 12:08 AM, "Coolthulhu" <notifications@github.com> wrote:

There is related issue that we can activate, throw etc things right from
the inventory with no need to take things in hands prior to interacting
with them.

Do we? #20325 <https://github.com/CleverRaven/Cataclysm-DDA/issues/20325>

That's a different issue, I'm pretty sure what Anton means is that the
expected sequence for e.g. throwing a grenade is:
Make hands free (e.g. holster a wielded gun)
Retrieve grenade from inventory (grenade is now in hand)
Activate grenade (still in hand)
Throw grenade
Re-ready your main weapon if you like.

What actually happens is:
(Non-action) leave hands occupied.
Activate grenade while it remains in inventory.
Throw grenade directly from inventory.

Addressing this corresponds to Anton's second option, implementing all the
sub-actions required to track this kind of thing.
Ideally the system would be streamlined enough that optimal play would
require different behavior (e.g. keeping your hands free in order to make
using various tools fast) rather than additional actions (manually
holstering and unholstering sidearm all the time).

**Comment by HotSake** [comment]
Let's not forget that just because it takes two hands to effectively use a rifle, does not mean it takes two hands to hold one. It is entirely possible possible to simply take your throwing hand off the gun, retrieve a grenade from your pocket, and pull the pin with a finger of your occupied hand (or your teeth if you're Rambo).

You can have your fingers curled around something, e.g. a foregrip, and still extend a single finger to snag the ring. Paying the time cost of completely unwielding and rewielding a gun is excessive. Also, you'd add an extra step of player input by asking whether they want to sheathe, wear, stow, or drop the weapon each time, or annoy people by automatically choosing the option they didn't want.

From a gameplay perspective, I get that this would help define a niche for underbarrel launchers as a faster explosive delivery option in a pinch, so I'm OK with emptying the hands to throw something as long as you can address the issue of choosing *how* to unwield. Perhaps use whatever option would be fastest to return to the wielded state, if you don't want to require a dialog.

Finally, you're going to have to seriously shorten the time penalty for folding stocks if you do this, unless you want them to be a cruel joke.

**Comment by kevingranade** [comment]
Totally agree, if anything we'd tend to be generous with what is allowable
to accomplish one handed.  There would be rules for what can be done one
handed vs requiring two, and we'd only stash wielded items if it is
required for the current action.  And yes, stashed items would go in the
location it would be fastest to retrieve them from.

Also yes, folding stocks are ludicrous.

**Comment by Night-Pryanik** [comment]
> It is entirely possible possible to simply take your throwing hand off the gun, retrieve a grenade from your pocket, and pull the pin with a finger of your occupied hand (or your teeth if you're Rambo).

> You can have your fingers curled around something, e.g. a foregrip, and still extend a single finger to snag the ring. Paying the time cost of completely unwielding and rewielding a gun is excessive.

Grenade throwing was just an example. There are other actions (well, almost everything that we are able to interact with from the inventory) as well. Also, there are things that character have to wield with two hands, no option to wield it one hand, only to drop or store in inventory, which IMO should pay time cost.

**Comment by DangerNoodle** [comment]
Last I checked, activating items from inventory is already bugged to the point of being horribly slow, and worse displays inconsistent behavior where a wielded object takes longer to activate from the use item menu than it does using the "activate wielded object" command.

See issue: https://github.com/CleverRaven/Cataclysm-DDA/issues/19899

**Comment by kevingranade** [comment]
Throwing at least requires wielding first.
