### ISSUE TITLE
Nonhuman allies cant ride vehicles

### ISSUE THREAD

**Issue by Steelfang** [CleverRaven/Cataclysm-DDA#20314]
Dogs or robots that get into a vehicle are run over when the vehicle is operated by the player. This makes the retrieve dog quest much harder and having canine or robot comrades much less flexible in terms of long distance travel

**Comment by CoroNaut** [comment]
This is a bug? I thought it was never implemented in the first place for this behavior to happen. Its been like this forever.

**Comment by kolsurma** [comment]
It's definitely a limitation of the game. If you leash a zombie/dog/robot to a 'seat' they should act the same as a NPC sitting in one.

**Comment by Coolthulhu** [comment]
The problem is that monsters don't have IDs, so they can't be tracked without complex and vulnerable hacks like tracking creatures by index in creature vector (which changes as the vehicle crushes creatures).

But it looks like we have agreement on how IDs should look like, so it may be fixable in the future. Though probably not before 0.D.

**Comment by BevapDin** [comment]
Duplicate of #11381.
