### ISSUE TITLE
Deleting the Pks_Rebalancing Mod folder from this repository

### ISSUE THREAD

**Issue by pisskop** [CleverRaven/Cataclysm-DDA#20326]
I would very much like to, to allow my own repository to be the primary and only source.

The version here still causes confusion for new players to the mod, and its been on the obsolescence list for a while now.

The mod is still being actively developed and is still enjoying growing popularity, and I would be willing to provide a backup of the old version included with this repository, although it should be unplayable due to the majority of commits and linting method improvements.

**Comment by Coolthulhu** [comment]
The question, as in #20129, is whether we do it just before the stable release or just after.
I'd support doing it just before stable and keeping a "compatibility version" somewhere, but that may be a problem for those who somehow ended up with old version of the mod and want to update to 0.D.

Leaving it in to 0.D will instead cause problems to players who want to install the new versions of the mod, because they will have to delete the old version manually.

The safest way would probably be to add some sort of ID migration system, to internally re-id the old pkmod as "pkmod_compatibility". This would allow obsoleting the old version without problems for migrating players and avoid problems for the new ones.
Still, it may be worth it to just say that the old version is too obsolete to support and just add a debugmsg on load saying "this mod has been obsoleted, see [link to new version] instead".

**Comment by WizardOfOoo** [comment]
Just take it off the world creation menu, leave the files as is.  People that want that stuff will know what files to change.  That way we have 100% compatibility with the old mod and nobody will start a new game with the old one.

**Comment by CoroNaut** [comment]
Are you sure you should leave a mod that is unintended for use by the majority of players in the files but not accessible within the game? I know I usually delete those extra mods to save a little space.

**Comment by Coolthulhu** [comment]
Space use is minimal here.
What is a problem is leaving the mod with the same ID.

@pisskop Is it important that the compatibility mod has same/different ID from your current version?

**Comment by WizardOfOoo** [comment]
Just change the ID of the mod that's no in our repository.

**Comment by Coolthulhu** [comment]
It's not "just". Mods are referred to by ID, meaning we need to hack around that. I'd avoid doing that if it isn't important.

**Comment by ZhilkinSerg** [comment]
Can we use several IDs in the same mod? One main ID and list of obsolete IDs.

**Comment by Coolthulhu** [comment]
No.

**Comment by pisskop** [comment]
They do share the same id.  Originally it was to force people to delete the obsoleted version.


Compatibility mod?

**Comment by Coolthulhu** [comment]
How so? It shouldn't demand mods to compile.
Lint warning due to missing files? If it's lint, change `json_whitelist`.
