### ISSUE TITLE
Filthy items disassemble into non-filthy components

### ISSUE THREAD

**Issue by ZhilkinSerg** [CleverRaven/Cataclysm-DDA#20342]
Filthy items yield non-filthy materials:

* disassembling `rag (filthy)` yields non-filthy `thread`;
* disassembling `steeltoed boots (filthy)` yields non-filthy `leather`;

Items yield materials which weren't used during item fabrication:

* disassembling `sling` produced from `long string` or `small string` yields `leather` and `thread`.

**Comment by Coolthulhu** [comment]
The second problem is known and old, but the first one is new.
In general one issue should be reported per issue where possible (unless they have same fix), so I'll edit the title for this one.

**Comment by ZhilkinSerg** [comment]
I believe issues has same root cause.

**Comment by Coolthulhu** [comment]
There could be a fix solving filthy items by aiming for the root cause, but it would be relatively complex.

Some items have components and those will deconstruct into filthy rags just fine.
Others do not have components and need to be special cased here.

From what I can tell, you want to generate components for all the items. This would work and be relatively resistant to changes, but it would bloat saves as every craftable item was now made of many components. And currently the identical components do not stack, meaning it would be really costly.

So instead it would be better to treat this as a special case.

**Comment by keyspace** [comment]
> Items yield materials which weren't used during item fabrication

Possibly covered by #18153.

**Comment by DangerNoodle** [comment]
> disassembling sling produced from long string or small string yields leather and thread.

Strange. I searched pull requests for a possible cause of the latter issue, and after enough searching found a pull request (https://github.com/CleverRaven/Cataclysm-DDA/pull/14811) that claimed to have fixed that specific example a long time ago. I was unaware there was an exploit of that nature originally.

**Comment by Night-Pryanik** [comment]
>  disassembling rag (filthy) yields non-filthy thread;
    disassembling steeltoed boots (filthy) yields non-filthy leather;

That's happening because at the moment filthy materials are obtained only from cutting up items, not disassembling. Submitted a PR #20346 to address this.

**Comment by Night-Pryanik** [comment]
Should be closed after #20346.

**Comment by keyspace** [comment]
@Night-Pryanik nex time, please do include

> Closes #<[]()issue-number[]()>

in the PR description.

**Comment by Night-Pryanik** [comment]
Yes, I always do this, but I forgot about this one.

**Comment by Night-Pryanik** [comment]
Repeat: should be closed after #20346.
