### ISSUE TITLE
Disconnected cities and locations

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#20386]
Cities may be generated without connections to the rest of the world.
That is, some cities may be generated in such a way that it isn't possible to get to overmap edge without crossing non-road tiles.

**Comment by codemime** [comment]
That's fairly possible, but I haven't seen it actually happening due to abundance of fields and forests. They "allow" roads, and a "raw" overmap consists mostly of them. The issue can be resolved by choosing a starting point for a new city and laying "virtual" roads before generating the actual city and the actual roads.
#20350 is a closely related issue.

**Comment by Leland** [comment]
#20417 noted that this can happen with anthills and with subway tunnels as well

**Comment by Leland** [comment]
There have been a couple issues regarding location disconnections. I imagine they're all related. 

- #19973 saw this happen with a lab
- #20350 saw this happen with a motel

**Comment by tinukedaya** [comment]
Not sure if this would belong here or if it's a different issue, but I came across this weird Public works road connection.

![image](https://user-images.githubusercontent.com/19891532/43716422-65dba21e-9984-11e8-806d-11689fd0f970.png)

**Comment by Night-Pryanik** [comment]
Anyone seen this since 2017?

**Comment by Night-Pryanik** [comment]
I'm closing this for now. If this is still an issue, ping me.
