### ISSUE TITLE
Enable mods to add buildings to variant lists.

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#20399]
Mentioned by @DangerNoodle in #20373 
>  If I knew a way for mods to change house placement in default region settings so that it can pick normal one-floor houses or the variants added in the mod, that would eliminate the need for separate overmap specials entirely.

I thought this was something we supported, it frankly sounds pretty easy as long as it still fits in the footprint of a regular house.

**Comment by DangerNoodle** [comment]
As I mentioned in the discussion, part of the likely problem is that the footprint of the mod houses are different, due to having multiple floors. Adding support for that might be more complex than simply allowing house placement to cite more than just the house mapgen ID.

Being able to add basic, single-story houses would not even require editing default region settings. They can simply be given the mapgen ID for normal houses and a specific weight, and they will be placed automatically.

However, I thought that the Animatronics and Dinosaur mods were obsoleted because mods adding to the shop list was considered unreliable in some way? Or it might have been because at least one of them modifies monster groups, my apologies if I am incorrect.

**Comment by Coolthulhu** [comment]
Do we really need this done before 0.D? It doesn't sound like something easy to squeeze in before the freeze.

**Comment by DangerNoodle** [comment]
As stated, implementing this would be more complicated than first assumption would indicate, and would be of limited utility at present.

**Comment by kevingranade** [comment]
I don't think the footprint thing is that significant, basement layer is
reserved, and nothing spawns in the air, so there's nothing to conflict.
I don't actually anticipate it being that hard, just some list surgery.

**Comment by DangerNoodle** [comment]
Again, problem is not only adding the ability to define other mapgen entries in the house list (instead of just house), but additionally ensuring that list can cite structures that consist of more than one mapgen 

That would be doable so long as the space above the building is unoccupied, but this would amount to allowing the house list to cite entire overmap specials, not individual mapgen entries. Or at least some way for a mapgen entry to contain instructions to force additional mapgen entries to be places above it, as I have seen that it seems mapgen entries can do this on a horizontal level (like with farms).

I am merely uncertain whether the complexity of what this requires is being adequately understood here. It is not as simple as simply allowing the existing framework for shop and park spawning to also apply to houses.

**Comment by Coolthulhu** [comment]
> I don't think the footprint thing is that significant, basement layer is reserved, and nothing spawns in the air, so there's nothing to conflict.

Actually, basement layer requires overmap generation.
Same here: the overmap needs to handle those cases, we can't just plug in the mutant buildings at individual mapgen time.

If we tried to handle it at mapgen, we'd get:
* Mapgen overriding existing terrain in 2D if player approaches the tall buildings from above
* (Alternative to the above) Mapgen not triggering for some levels, resulting in buildings with "slices" removed
* Buildings changing their overmap type when mapgen'd, despite being seen as the old type before
* Lab map info becoming obsolete as player explores the area and notices buildings are taller than on the map

What we need is overmapgen that can understand that a given 1 tile building can stretch upwards and can replace the flat 1 tile building with a tower. The height of this tower would need to be checked first: it can't just generate a height 2 tower if all buildings in current mod set are height 1 and 3.

**Comment by Coolthulhu** [comment]
1x1 footprint buildings are supported. What else needs to be done here?

**Comment by Leland** [comment]
Closing per above and lack of discussion. Of course, do reopen or ping me if there's more to do here.
