### ISSUE TITLE
Per-tile draw time is too high, draw time scales horribly

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#20404]
Drawing is slow. It isn't the Unicode as I expected in #20190, but rather slow drawing per tile.

While not redrawing things that don't change could help, the vision radius is huge and we have to draw something everywhere.

So here's a relatively implementable algorithm that could help:
* Background (map, items, effects - anything drawn sequentially by default) gets drawn onto a cache. This cache is kept between draw calls and where possible, dirtied only partially (no "drop all cache", just "drop cache in rectangle"). If a draw would be a cache hit, it is skipped.
* The cache above is treated as a texture (and probably is one). It is drawn as the background for everything else.
* Rather than drawing things that we see, we draw entire background (except things not cached) and then hide things we do not see. That is, we blit the background and then obscure the tiles that are unseen. Obscuring is faster than drawing because we can draw rectangles (overhead is often larger than the blit times).
* To avoid dirtying the whole cache during bubble shift, the caches could be tiled (say, submap sized) rather than having just one

There are three semi-common edge cases here:
* Walking around in the darkness near a light source would redraw ~30 tiles per turn. But at the moment we routinely redraw >1000 tiles per turn, so 30 would be negligible
* Lightning changes. Day/night cycle, lightning and (worst offender) flickering lights. Two first would be tolerable. Flickering lights could be just dropped for the sake of not overdesigning everything around an incredibly unimportant gimmick.
* Walking around a corner and seeing a lot of stuff at once. This one is not fixable here. It would still be better than what we have now, but there would be a noticeable hiccup on giant screen combined with weak computer

Using OpenGL would make this totally redundant, though.
Nowadays everyone has one of:
* Hardware OpenGL support (99% of computers)
* Curses support (if someone, for any reason, plays on server hardware)
* Screen too small for the true performance drop to show, now that empty spaces are no longer drawn (UI is mostly empty space)

**Comment by Zireael07** [comment]
> flickering lights

We do have flickering lights in CDDA? I never noticed...

> Walking around a corner and seeing a lot of stuff at once. This one is not fixable here. It would still be better than what we have now, but there would be a noticeable hiccup on giant screen combined with weak computer

Been playing on fairly weak rig off an USB stick, biggest slowdown was saving and not drawing.  Any improvement is better than what we have now.

**Comment by AMurkin** [comment]
Lighting should be calculated separately and in the texture of 1 pixel = 1 tile (or higher optional). Then be applied to rendered texture.

**Comment by Coolthulhu** [comment]
> Lighting should be calculated separately and in the texture of 1 pixel = 1 tile (or higher optional). Then be applied to rendered texture.

You mean as a filter, an overlay or alpha-blended?
A filter sounds too expensive.
A dithered "fog" could be doable. Though it would be an incredibly retro-looking effect.
Alpha blending is pretty slow without hardware acceleration. I'm not sure if the performance we have now is with or without alpha blending.

**Comment by kevingranade** [comment]
Need to recapture some context, this is specifically on Windows console
builds, right?

Overall this looks like it would help, but I have to wonder if it would be
simpler to just replace cursesport.cpp with pdcurses.
Curses already does heavy caching and buffering, instead of adding it
(invasively) to the draw logic, moving to pdcurses would just bring the
windows terminal build to parity with the rest of the build targets.
Alternately, look into the buffering and caching the curses library and SDL
are doing and replicate in cursesport.

On Feb 27, 2017 11:27 AM, "Coolthulhu" <notifications@github.com> wrote:

Drawing is slow. It isn't the Unicode as I expected in #20190
<https://github.com/CleverRaven/Cataclysm-DDA/issues/20190>, but rather
slow drawing per tile.

While not redrawing things that don't change could help, the vision radius
is huge and we have to draw something everywhere.

So here's a relatively implementable algorithm that could help:

   - Background (map, items, effects - anything drawn sequentially by
   default) gets drawn onto a cache. This cache is kept between draw calls and
   where possible, dirtied only partially (no "drop all cache", just "drop
   cache in rectangle"). If a draw would be a cache hit, it is skipped.
   - The cache above is treated as a texture (and probably is one). It is
   drawn as the background for everything else.
   - Rather than drawing things that we see, we draw entire background
   (except things not cached) and then hide things we do not see. That is, we
   blit the background and then obscure the tiles that are unseen. Obscuring
   is faster than drawing because we can draw rectangles (overhead is often
   larger than the blit times).

This part might be better with a masking operation instead of two passes,
would require experimentation to find out.


   - To avoid dirtying the whole cache during bubble shift, the caches
   could be tiled (say, submap sized) rather than having just one

This makes things a lot more manegable.



There are three semi-common edge cases here:

   - Walking around in the darkness near a light source would redraw ~30
   tiles per turn. But at the moment we routinely redraw >1000 tiles per turn,
   so 30 would be negligible

Do you mean because it changes the symbol drawn when it's brightly vs
normally vs dimly lit? If so I agree that it's probably going to be fine if
we just let that trigger cache misses and re-enter the affected squares.


   - Lightning changes. Day/night cycle, lightning and (worst offender)
   flickering lights. Two first would be tolerable. Flickering lights could be
   just dropped for the sake of not overdesigning everything around an
   incredibly unimportant gimmick.

I'm not in favor of dropping features because of issues on a secondary
platform.


   - Walking around a corner and seeing a lot of stuff at once. This one is
   not fixable here. It would still be better than what we have now, but there
   would be a noticeable hiccup on giant screen combined with weak computer

I don't follow why this is is a problem, your proposal was to render
everything on the map and then cover it if it's not visible, revealing map
shouldn't cause any additional calculation or drawing.



Using OpenGL would make this totally redundant, though.
Nowadays everyone has one of:

   - Hardware OpenGL support (99% of computers)

We do recommend the SDL build for Windows users, I suspect SDL is more
performant than terminal on Windows simply due to buffering in SDL.

**Comment by Coolthulhu** [comment]
> Need to recapture some context, this is specifically on Windows console builds, right?

No, SDL builds on Windows are also affected, just less so due to caching of glyphs.
Windows console builds are slower because they do uncached truetype drawing per every glyph, but all SDL builds (including *nix) are affected (more or less) by the cost of repeated, small, unaccelerated texture draws.

> Overall this looks like it would help, but I have to wonder if it would be simpler to just replace cursesport.cpp with pdcurses.

For windows console, it could be really good. I'm getting ~5 times more FPS (120 instead of 25) on a cygwin build than tiles-with-tiles-off.

> Do you mean because it changes the symbol drawn when it's brightly vs normally vs dimly lit?

Yes. It happens quite a lot when moving around in dimly lit areas. Not a huge performance concern (it's the static drawing that is), just a case to consider.

> I'm not in favor of dropping features because of issues on a secondary platform.

Flickering lights aren't much of a feature - more of a gimmick. They only really happen in the "wild", on relatively fresh police cars and ambulances.
And the performance issues affect everything except *nix curses.

>  I don't follow why this is is a problem, your proposal was to render everything on the map and then cover it if it's not visible, revealing map shouldn't cause any additional calculation or drawing.

The biggest cost of rendering is often the cost of repeated draw calls. By rendering one huge texture and then multiple mid-sized textures to hide parts of the large texture, the cost could easily drop to a fraction.
Even if just because the actual drawing itself would most of the time be "dumb" rather than context-aware (ie. would not need to actually know the map and mix calculations with drawing).

That is, in basic systems. If the drawing was done by a batching, hardware-accelerated system, texture draw cost would not be noticeable.

**Comment by Coolthulhu** [comment]
To clarify because it may not be obvious:
* Windows console has worst performance out of all options
* SDL on any system is affected by slowdown
* *nix console is fastest out of all the options

Also, when I'm talking about adding a lot of caching, I'm mostly thinking about SDL builds, as they are the de-facto standard on systems where proper curses console is not available.

**Comment by kevingranade** [comment]
On Mar 1, 2017 10:17 AM, "Coolthulhu" <notifications@github.com> wrote:

Need to recapture some context, this is specifically on Windows console
builds, right?

No, SDL builds on Windows are also affected, just less so due to caching of
glyphs.
Windows console builds are slower because they do uncached truetype drawing
per every glyph, but all SDL builds (including *nix) are affected (more or
less) by the cost of repeated, small, unaccelerated texture draws.

Thanks for the clarifation, that changes things a lot.  It might be the
case that curses is the only library that does the caching and batching I
was thinking of.

Overall this looks like it would help, but I have to wonder if it would be
simpler to just replace cursesport.cpp with pdcurses.

For windows console, it could be really good. I'm getting ~5 times more FPS
(120 instead of 25) on a cygwin build than tiles-with-tiles-off.

It might still be worth doing, but it wouldn't resolve the entire problem.

I don't follow why this is is a problem, your proposal was to render
everything on the map and then cover it if it's not visible, revealing map
shouldn't cause any additional calculation or drawing.

I think the context was lost here, the above comment was with respect to
your comment that, "sudden reveals would be expensive", I think with your
proposal, there would be negligible difference between showing most of the
map and showing all of the map, because the only difference will be drawing
some large rectangles after drawing the terrain textures.

That does highlight an issue with this approach, which is that it draws the
entire map full of terrain on every tick with no culling.  I *think* this
would be net very positive compared to how it works now due to lower cost
of drawing per tile of terrain, but it's something to look out for.

Actually nevermind, we could still do culling with a visibility bitmap. We
just need to determine if the player can see a particular tile once a draw
operation, if they can't there's no need to draw it, and we might avoid
updating it as well.

**Comment by Zireael07** [comment]
@kevingranade your comments don't have quotes so I can't tell what you're quoting and what you're replying to...

**Comment by kevingranade** [comment]
Unfortunately GitHub broke their email parser a while back. I don't know if
there's anything I can do to fix it.

**Comment by kevingranade** [comment]
This is less an issue and more a discussion, and now that it's been stalled for most of a year, it's not providing any value.
