### ISSUE TITLE
Attack sequencing seems odd with fencing perk

### ISSUE THREAD

**Issue by jonathanblu** [CleverRaven/Cataclysm-DDA#20403]
Build - 6269
Platform - Windows 64 bit

Pretty easy to reproduce,
Spawn in a world with Melee weapon training - fencing
Wish yourself a baldric and a rapier
Wear the baldric and put the rapier in it
Equip any item in your hands
Spawn a zombie nearby
Now activate your baldric to remove your rapier and put away whatever is in your hands
The attacks start the instance you activate this action when it seems they shouldnt start until whatever is in your hands is put away and the rapier is equipped.

![ccda](https://cloud.githubusercontent.com/assets/25240810/23374609/d9a73558-fcd9-11e6-8979-8707e080d585.png)

**Comment by DangerNoodle** [comment]
I would assume that this applies to all defensive techniques. This is mainly visible with fencing because it is the only instance I know of where the defense and counter attack occur in the same technique, and the only one that resolves fully without player input.

If I recall, Boxing has a cross counter technique, that requires the player to actually initiate an attack while under the effects of the "They're wide open!" buff effect. The same applies to displace and counter in Medieval Swordsmanship in the mod containing it, and likely other styles in the game (Viper Kung Fu?).
