### ISSUE TITLE
Throwing is too good

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#20414]
Throwing got all the buffs that aiming got, but without any requirements to aim.
It also uses the old XP formula, back then when guns were incredibly inaccurate even when aimed. That old formula scales with accuracy. Result is that you can gain throwing 7 before your melee reaches 3 or so.

The only thing preventing throwing from being the ultimate hulk killer is the UI issues of having to re-select the item over and over.
Which is pretty much the worst possible situation when it comes to balancing - balancing with tedium (unintentional, but still).

**Comment by DangerNoodle** [comment]
If I recall, there is also the problem that weapons designed to use throwing do not gain any benefits from the skill. Eventually throwing a sling pebble or atlatl javelin by hand outpaces using the weapon, when realistically these weapons improve upon the ability of the user to accelerate the projectile.

However, making slings objectively better than throwing by hand would not solve the issue of throwing being able to reach considerable range and damage at extreme levels of skill and strength. The latter at least should be fine, it would be reasonable for throwing to be highly damaging if the player character is a mutant or cyborg with superhuman strength.

**Comment by kevingranade** [comment]
The main thing were missing is a rationale for just how good throwing
should be, otherwise this sort of thing just becomes "I think foo should be
better than bar, so here's a PR making it so".

**Comment by DangerNoodle** [comment]
Understandable. Part of it is that ideally it should not make firearms inferior, at least when throwing anything easy to obtain. Likewise, range would need to scale with strength more than with skill, but getting a good handle on range requires that the rather nebulous tiles be set to roughly correlate with likely averages for human ability to throw things. Then determining what strength and skill level would generate results comparable to world records for various throwing sports (javelin, discus, etc).

This would give a good model for what the maximum should be for players at the normal maximum, with higher values requiring literally superhuman strength.

**Comment by kevingranade** [comment]
On Feb 28, 2017 5:22 PM, "DangerNoodle" <notifications@github.com> wrote:

Understandable. Part of it is that ideally it should not make firearms
inferior, at least when throwing anything easy to obtain.

Actually that's a good sanity check, the best thrown item probably
shouldn't beat the worst firearm in either range or accuracy. I wouldn't be
surprised if we fail that check.

Likewise, range would need to scale with strength more than with skill, but
getting a good handle on range requires that the rather nebulous tiles be
set to roughly correlate with likely averages for human ability to throw
things.

If we can get a good set of numbers for thrown ranges and accuracy, we can
at least plot a function and then scale that function to our constraints.

Then determining what strength and skill level would generate results
comparable to world records for various throwing sports (javelin, discus,
etc).

This would give a good model for what the maximum should be for players at
the normal maximum, with higher values requiring literally superhuman
strength.

The problem I ran into before was a total lack of information about the low
end of the scale, and lack of data about misc thrown items.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/CleverRaven/Cataclysm-DDA/issues/20414#issuecomment-283215313>,
or mute the thread

**Comment by glenmack** [comment]
In terms of data for "bad throws" -

Mythbusters did a myth on throws like a girl where they tested speed and accuracy at 32 feet with a baseball. (9.6m). They used people with no sport background and had them throw at a target 1ft square. If they hit it they scored 5 points. a 3ft square around that scored 4, and 5 ft square 3.

I'm trying to get hold of the actual numbers but in the episode they stated the average accuracy for men was 2.66 and women score a 3.2.

Men on average threw 15% faster though.

Is that of any help?

**Comment by 1skandar** [comment]
Add in the fact that throwing levels absurdly quickly. I'd have to check it, but I remember from my last mansion start walking out with throwing 4 or so just from chucking pool balls at zombies for a few hours. Add in the fact that ammo isn't consumed, throwing is either perfectly silent or nearly so, and you can throw without equipping the item it is easy to just sit out of sight of a zombie and unload like 10 pool balls at their head with no reaction, then lure the now damaged zombie in for a quick kill, scoop up the pool balls and repeat.

**Comment by DangerNoodle** [comment]
I realized now that sling pebbles and atlatl javelins are also potentially better off thrown by hand due to not having a high chance of being preserved on impact. This would apply to all throw ammunition, but weapons that use the throwing skill are the major examples, because this factors into not just balancing throwing against wielded ranged weapons, but also against ranged weapons that use the throwing skill, which throwing by hand can outclass.

**Comment by Coolthulhu** [comment]
> Add in the fact that throwing levels absurdly quickly.

It's because leveling speed scales with range and accuracy, while accuracy no longer is as bad as it was.
When you score a headshot, you get up to 21 "ticks" per unit of distance. 5 tiles means 100 ticks. A missed attack grants 10 ticks, so you can always tediously grind to infinity too.
With guns, you only get 10 ticks per shot that hits, regardless of range.

**Comment by 1skandar** [comment]
Yeah, that second should likely be changed, then, and probably explains why I've used a shotgun the whole game with my last character and gained two levels only. Lord. The first should *certainly* be changed. It id *risky* to use a gun because of noise, while throwing things is nearly risk free. Add in the fact you can easily throw two or three rocks in the time it would take you to line up one shot and things get out of balance quick.

**Comment by Mecares** [comment]
How about using the soon to be implemented wielding times to make throwing stuff you do not actually wield take more time instead of basically being instant?

**Comment by DangerNoodle** [comment]
> How about using the soon to be implemented new wielding times to make throwing stuff that you do not actually wield take more time? Then the damage and accuracy still can be relatively high because the rate of fire will be significantly less than other ranged weapon options.

Do we seriously need time management to creep into every single action the player makes?

**Comment by kevingranade** [comment]
On Mar 3, 2017 8:55 AM, "DangerNoodle" <notifications@github.com> wrote:

How about using the soon to be implemented new wielding times to make
throwing stuff that you do not actually wield take more time? Then the
damage and accuracy still can be relatively high because the rate of fire
will be significantly less than other ranged weapon options.

Do we seriously need time management to creep into every single action the
player makes?

Yes, it's the fundamental attribute shared by all actions, and in this case
it is a natural balance point between guns and thrown weapons.  Guns
generally have fast acting internal magazines, your best option for a
thrown weapon is a holster.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/CleverRaven/Cataclysm-DDA/issues/20414#issuecomment-284008226>,
or mute the thread

**Comment by Xpyder** [comment]
As long as we're talking about range, slings have similar ranges to bows.  Surprising but true
The big issues are accuracy (timing based), movement (startles your target), penetration, and typically inferior ammo (most arrows have more time spent on them, the best sling ammo are ovoid rocks as from a river bed not the broken pieces you get off the ground)

Sling farthest shot: 437.10m Larry Bray 1981

**Comment by DangerNoodle** [comment]
> the best sling ammo are ovoid rocks as from a river bed not the broken pieces you get off the ground)

Steel bearings of an adequate size, or cast lead sling bullets, are more effective due to better uniformity and density. The latter is well-established historically.

**Comment by Xpyder** [comment]
There's probably some truth to that, I'd guess that the perfect ammo would be something with dimples like a golf ball.

**Comment by BorkBorkGoesTheCode** [comment]
>Sling farthest shot: 437.10m Larry Bray 1981

Did it retain energy at that distance?

**Comment by Xpyder** [comment]
Probably as much as an arrow would at max range which is more than one might assume.

Accurate shots are obviously shorter.  I think the farthest accurate bow show was 235m or so and slings are harder to aim because you have a timing component that bows circumvent.  Bows should definitely be more accurate, and I think the sling ranges are fine for the most part, people were just talking a lot about ranges so I wanted to make sure they didn't get accidentally over-nerfed.

**Comment by Xpyder** [comment]
I should also add that slings shouldn't have long bow range, that would be more equivalent to a staff sling which I don't think currently exists in game.  Their range should either match survival bows or be somewhere between them and short bows.

**Comment by ynemo** [comment]
Looks like throwing should levels 3-5 times slower.

**Comment by kevingranade** [comment]
This was improved by #20551, but not fixed, a simple test of spawn a totally average character (all 8 stats, no skills) with a pile of rocks can hold off a sizeable horde of zombies, and rapidly gain throwing skill levels in the process.

**Comment by kevingranade** [comment]
How this has proceeded so far is a perfect example of why I was insisting:
> The main thing were missing is a rationale for just how good throwing should be

We made the effort of making extensive changes to throwing, with no impact at all on this issue since there was no goal to measure the changes against.

Also, while I was digging into this issue I ran across the absurd series of PRs (dispersion overhaul) that were merged behind my back while I was out that I had called out as completely unacceptable.  I will be reversing the key parts of those PRs, restoring the "sum of errors" system that existed previously.

**Comment by Barhandar** [comment]
Throwing should be less potent than bows and (especially) crossbows at low skill and stat levels, and far more potent than either at high skill and stat levels, becoming equivalent of primitive firearms if not better.  
With bows and crossbows, damage/range is limited by bowstring strength, bow draw strength, and your own strength, accuracy/dispersion is limited by weapon and dexterity. With throwing and slings, damage/range is limited by lever length, your own strength (ability to swing arm/sling fast enough to utilize the leverage in full) and sling durability, and accuracy/dispersion is limited by dexterity alone.

Thus, my suggestion is that training throwing should be on a curve, relatively quick at first (someone who has never thrown is going to miss like crazy, but quickly learn to hit) but slow later. Throwing damage should scale with both strength (can throw harder) and skill (can throw more effectively), the latter up to a point. Range should scale with strength for freehand throwing, and with both strength and skill for assisted throwing (also, slings should be able to be used for throwing arbitrary items, that is, 't'hrowing items with sling wielded should use assisted-throwing formulae, provided they're not too large/too light). Accuracy should scale with dexterity and skill, capped by dexterity.

Also, RL slings have _higher_ effective range than primitive bows, except for composite bow, so they definitely should have max range equivalent to longbow's, and scale with skill.

**Comment by i2amroy** [comment]
>Also, RL slings have higher effective range than primitive bows, except for composite bow, so they definitely should have max range equivalent to longbow's, and scale with skill.

This is definitely true, but I think it's important that anything starts out very weak and then scales hard with skill to make up for it. After all there's a reason why historical armies mainly abandoned the sling in favor of the bow; it's because it's *way* easier to learn how to hit something at range reliably with a bow than it is with a sling. (Also a few other things, like it's easier to have archers stand in close proximity, but that doesn't really matter too much from our perspective).

**Comment by Xpyder** [comment]
> After all there's a reason why historical armies mainly abandoned the sling in favor of the bow

The bow does a lot more piercing damage and is much better against armor.  In general I would suggest slings have similar range and light to moderate damage, with bows doing more damage in general, and possibly better at penetrating armor.

**Comment by Barhandar** [comment]
>After all there's a reason why historical armies mainly abandoned the sling in favor of the bow; it's because it's way easier to learn how to hit something at range reliably with a bow than it is with a sling. 

"If you want to have a good archer, start with his grandfather". The learning speed is negligible and almost same, the other advantages of the bow, like the ones you and Xpyder listed, are far more important.

Also, slings with ammo should be better _melee_ weapons than bows, instead of vice versa like now. It's essentially a higher-leverage rock in a sock, if not released into throw. But they should be unusable for throwing at very close range (1-2 tiles) due to the higher space required.

**Comment by Xpyder** [comment]
and probably a longer fire time as well

**Comment by LyleSY** [comment]
For the purposes of 0.D, is the current improved throwing system good enough to be retired from the 0.D project? In my testing, I think it is. I'm excited about the ideas being discussed here, but I think we're talking about richer improvements beyond 0.D.

**Comment by kevingranade** [comment]
No, I consider this:
> a simple test of spawn a totally average character (all 8 stats, no skills) with a pile of rocks can hold off a sizeable horde of zombies, and rapidly gain throwing skill levels in the process.

To be utterly broken.  No skills, no plan, just a big enough pile of rocks and you can hold off a massive horde of zombies.

**Comment by Xpyder** [comment]
I think the best solution right now would be to give thrown rocks and slings need a longer throw time, slower skill progression, lower base accuracy, and probably have skill ranks improve accuracy more and damage less.  Possibly with a damage adjustment.

**Comment by roobie** [comment]
As a relevant aside; lead bullets can be pretty devastating:

> The Greeks and Romans used lead sling projectiles made in molds. “Writers tell of the terrible wounds that slings would inflict, especially [lead] bullets. The Romans developed a special pair of tongs designed for getting bullets out of people. [written here](https://www.wayoflife.org/reports/the_power_of_the_ancient_sling.html)

Another good thing to know is that wooden bows do not work when wet.

However, during the time in history when slingers were common, combatants were generally lightly armoured, which is why it was effective. One reason for the shift from slings to bows is that the bow has a much greater potential for armour penetration. Do note that the arrows used makes a big difference. Arrows made for war (and thus made to be able to penetrate armour) was very thick, weighed more than a bullet ever could, and therefore they could carry a lot more momentum.

**Comment by jeremyshannon** [comment]
There are records of massed slingers standing on docks and sinking incoming enemy ships with lead bullets. Penetration isn't that big a problem for an egg-sized ball of lead. The main reason slings were discarded in favor of arrows in war has little to do with accuracy (bows aren't terribly accurate either past the range where you have to use indirect fire) or penetration, it was the fact that you can't pack them together tightly.
 When your main way of preventing cavalry from creaming your ranged guys is to surround them with a bunch of other guys holding pikes, the closer you can pack the former together, the better. Slings need a broad space around each man to swing without tangling and injury, so you can't put as many guys in a pike square. What's more, whether bows or slings, your main way of hitting an enemy group at any appreciable range is just to put as many bullets/arrows in the air as possible and hope a good percentage will hit, so packing more guys in massively increases effectiveness, on top of defensibility.

I don't know how throwing should be fixed, but while it's clearly gotta be nerfed to some extent, I gotta say that if I can't be Judas Priest's The Sentinel, I will be sad.
"Across his chest, in scabbards rest, the rows of throwing knives
 whose razor points, in challenge tests, have finished many lives!"

**Comment by Aidolii** [comment]
Coolthulhu opened this issue on Feb 28, 2017

**Comment by Endovior** [comment]
I'm also in favour of a throwing nerf; useful as it is, it feels somehow wrong that a pile of rocks or sticks is the best non-firearm weapon around, but I often find myself using throwing as my primary combat style over archery and such, simply because it works so well for so little investment. Of the suggestions made so far, I feel like the most impactful would be the application of two systems that other ranged combat styles already have, but throwing doesn't; reloading time and ammo mulch.

'Reloading' a thrown item is basically just wielding it, fishing it out from wherever you have it stashed. A backpack full of rocks is not particularly accessible to your throwing arm, and it shouldn't be treated as such. This alone would substantially reduce the desirability of throwing as opposed to archery, as it's a penalty that archers have and throwers don't. Ideally, this process shouldn't involve any more UI complication than the existing throwing system... but it would go a long way to make throwing less deadly, since it'd make it hard to spam out quite so many attacks so quickly.

As for ammo mulch, it's a penalty that all the other ranged combat styles have that throwing doesn't have. I understand why it hasn't been implemented yet (it'd be somewhat problematic to figure out just how likely any given item is to break when thrown), but that absence does make it such that thrown has the least ammo concerns of any ranged combat style. That being said, a starting point might be to give all items a thrown mulch chance based on the material they're made of, and then to make specific items which are 'designed' to be thrown weapons less likely to mulch than that.

**Comment by Epictyphlosion** [comment]
Although I don't use throwing that much (unless I'm in a really desperate situation), I think just nerfing it would be the best course of action, either by making it harder to level up, or making it so that butter knives or other weak items can't do much damage at lower levels. Besides, this hasn't been fixed in over a year, and we have another bug that hasn't been fixed in over two years...

**Comment by kevingranade** [comment]
Nerf it how much? Reduce damage from throwing weapons by one? Increase move
cost of throwing by one? Will that fix the issue?

"Just nerf it" doesnt address the problem.

**Comment by Epictyphlosion** [comment]
@kevingranade Either increasing the amount of throws needed to level up, meaning you would need to throw more stuff to level up from level 0, or reducing the damage dealt. It's up to you

**Comment by Endovior** [comment]
Reducing the damage-per-tick (by adding draw time for thrown items) would probably be better than reducing the damage outright. I don't see that there's anything broken with throwing that couldn't be fixed by treating throwing with the same rules that everything else follows... but since it currently doesn't follow those rules, thrown weapons deal a lot of damage per tick, and without much in the way of ammo concerns.

The fact that weapons that use the throwing skill (slings, atlatl) are less good as weapons than throwing the ammo barehanded feels like a symptom of this; the weapons are limited by the mechanics of the ranged weapon system, while throwing isn't.
