### ISSUE TITLE
suggestion to ad in organs wen butchering. animals, zombies or some other creatures

### ISSUE THREAD

**Issue by Eddyskingdom** [CleverRaven/Cataclysm-DDA#20415]
ading in organs to the game will be much more realistic and fun and it will also provide more food to the player. wen hunting. like ad in: lungs, heart, brain, liver, kidneys, and make dat brains and lungs will give you bad moral boost wen eaten also ad in dat you can get a parasite wen it's not cookt

**Comment by kevingranade** [comment]
On Feb 28, 2017 7:44 AM, "Eddyskingdom" <notifications@github.com> wrote:

ading in organs to the game will be much more realistic and fun and it will
also provide more food to the player. wen hunting. like ad in: lungs,
heart, brain, liver, kidneys, and make dat brains and lungs will give you
bad moral boost wen eaten also ad in dat you can get a parasite wen it's
not cookt

Currently we call everything meat and apply a toned down version of the
disadvantages you mention to all raw meat.  I'm not seeing a benefit to
calling out specific organs that is greater than the overhead of adding
them.

In particular, this wouldn't add more food since when organs are added wed
probably reduce the yield of meat to compensate.

**Comment by ZhilkinSerg** [comment]
It is very likely that it possbile to mod out such behavior, but it won't add to much to the game.

**Comment by Coolthulhu** [comment]
We have organ meat already - it's called offal. It's just that it isn't divided into 10 categories with minimal differences.

**Comment by kevingranade** [comment]
I totally forgot about offal, excellent point.
Lacking a more concrete set of differences, closing.
If you want to brainstorm about ways this would improve the game, please consider posting on the forums: smf.cataclysmdda.com
