### ISSUE TITLE
Proper strict json warning system

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#20410]
The current `load` function is `load( JsonObject &jo, const std::string &src )`.
Then the `src` is string-compared to "core" or "dda" (some places have the former, all should have the latter) to check if we want strict assignment.

This is pretty bad for mods which could want to define their own strict checking.

Instead, the second argument should be a mod structure containing, at the very least, `bool strict`. But could also contain useful debug data, so that debug messages due to failed load could change from
```
Unknown id in recipe make_xyz: that_thing_added_in_mod
```
To
```
Unknown id in recipe make_xyz: that_thing_added_in_mod
make_xyz was added by mod make_extra_stuff
```

**Comment by kevingranade** [comment]
I'm a little concerned about the existing checks, I've seen a lot of noise about these checks failing because of pretty arbitrary sounding reasons, as well as failing because there seems to be a requirement to add a linting definition to each new type of json entity, seems like a lot of overhead for marginal benefit, e.g. sorting keys and json entries, which json is agnostic to.

**Comment by Coolthulhu** [comment]
I had this idea for a while:
What if json checking was always in `--check-mods`, but otherwise either disabled or just kept on jenkins side?

**Comment by kevingranade** [comment]
If it happens in Jenkins, it should get triggered on at least a release build as well, otherwise you're making it harder to comply with the thing, requiring contributors to know that they have to run cataclysm --check-mods in order to find out what the problem with their json is before pushing.  At the minimum, we need a build target (maybe release, maybe something new) that at least tries to do all the same checks Jenkins does.  (Excluding compiling every target and on multiple compilers of course)

Side issue, maybe we want a build target specifically for json contributors that runs the consistency checks?  IDK, maybe that *is* cataclysm --check-mods, but I don't see a reason not to do it on make Release=1 or the Code::Blocks release target (if C::B is even up to doing that, I don't know much about it).

**Comment by Coolthulhu** [comment]
A bit ugly, but workable way to have it work for Windows would be to make a .bat file that would execute `cataclysm --check-mods` (or the tiles variant of the file), then would wait for prompt. This could be dumped into a tools directory.

**Comment by kevingranade** [comment]
Re: the initial suggestion, it's a random implementation detail, if you want it in, just add it, but it doesn't rate a slot on the issues list.
