### ISSUE TITLE
Hide vitamins by default for 0.D

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#20513]
Currently the vitamin system does nothing mechanically.
Not a thing. Zero.
It only prints warnings which mislead the players who aren't yet aware that the game is lying to them.

False warnings like that are objectively wrong. They aren't just a flavor thing - they explicitly warn of effects that never come.
While implementing penalties would be a way to fix false warnings, I'd rather not experiment with it so close before 0.D.

After 0.D we can try doing something with the system. I recall @pisskop doing some experiment with vitamins in his mod, so his experience could be helpful with making vitamins matter in core.
But that's for post-0.D experimentals. Now the question is: do we want to disable it by making the no-vitamins mod default or hardcode the disable for 0.D and then remove the hardcode afterwards?

**Comment by kevingranade** [comment]
Does no-vitamins suppress the messages, vitamin spawns, or both?

Suppressing vitamin spawns seems excessive, but suppressing the messages
sounds reasonable.  I'd favor making the mod default until they do
something.

**Comment by Coolthulhu** [comment]
It doesn't actually blacklist vitamins, only makes items and characters not have vitamin fields. It turns vitamins into bland candy.
Disabling the mod is totally safe, though it has to be done by safe editing.

**Comment by DangerNoodle** [comment]
Vitamin effects still have not been implemented? Why was this feature allowed to be added and additionally made mandatory if it was non-functional to begin with?

It might be desirable to additionally revert the implementation of offal and the corresponding nerf to meat products if this is done, because otherwise offal only exists to waste around half the potential nutrition of game due to the greater difficulty of preserving it. It additionally fails in its secondary role of preventing players from getting complacent via sharply reducing the utility of jerky.

In my own gameplay experience, it is still trivial to hoard jerky and subsist entirely on it if I am playing a wilderness character, even with the severe reduction in nutrition for all meat products. I usually wind up leaving raw offal on the ground to rot and do not suffer for it in the slightest.

**Comment by kevingranade** [comment]
> It might be desirable to additionally revert the implementation of offal and the corresponding nerf to meat products if this is done

> In my own gameplay experience, it is still trivial to hoard jerky and subsist entirely on it if I am playing a wilderness character, even with the severe reduction in nutrition for all meat products.

So in other words, no it is not desireable to revert the addition of offal. If your direct experience is that it doesn't need to happen, why did you suggest it?

**Comment by DangerNoodle** [comment]
I mean that the addition of offal has had little to no effect on how easy it is to subsist on jerky. My point being that the reduction in nutrition of meat did little to actually make it difficult to subsist on meat.

Instead, it only serves to cause player annoyance by requiring the player to enter more keypresses and use more of a resource that is still trivial to build up. I am saying that reducing the nutrition of meat items only added more tedium and keypresses, and does not actually do anything to encourage the player to vary their diet and rely on other food sources.
