### ISSUE TITLE
smf.cataclysmdda.com is down.

### ISSUE THREAD

**Issue by Chezzo** [CleverRaven/Cataclysm-DDA#20547]
The forums are down. Should I make and host a new one?

**Comment by BorkBorkGoesTheCode** [comment]
Who's hosting them now? Can they be notified?

**Comment by Chezzo** [comment]
I'm not sure, maybe Glyphgryph?

**Comment by BorkBorkGoesTheCode** [comment]
>The forums are down. Should I make and host a new one?

If you have the time and resources and the ability to counter hacking attempts, it might be good.

@kevingranade @Rivet-the-Zombie @narc0tiq @GlyphGryph

**Comment by BorkBorkGoesTheCode** [comment]
It's still down.

**Comment by narc0tiq** [comment]
I'm sorry, I have nothing to do with the cataclysm website or its forums.
Probably still GlyphGryph's, if we can get hold of him.

**Comment by BorkBorkGoesTheCode** [comment]
Sorry to bother you.

**Comment by kevingranade** [comment]
On Mar 14, 2017 8:18 AM, "Chezzo" <notifications@github.com> wrote:
> The forums are down. Should I make and host a new one?

If you have the resources handy, please, if not I'll do it, but it might be
a day or two for me since I have the plague (ronovirus?).

**Comment by kevin-at-corista** [comment]
Hey guys, I mentioned a couple weeks ago my Dreamhost hosting was probably going down since they raised it to $70 and I've not got a lot of spare cash this year and suggested folks start migrating over anything that wasn't moved yet, I guess it might have been. Actually kind of figured everything was already moved away to be honest so I didn't worry about it too much.

**Comment by GlyphGryph** [comment]
Hey guys, I mentioned a couple weeks ago my Dreamhost hosting was probably going down since they raised it to $70 and I've not got a lot of spare cash this year and suggested folks start migrating over anything that wasn't moved yet, I guess it might have been. Actually kind of figured everything was already moved away to be honest so I didn't worry about it too much. If you guys want a copy of the last db dump or something let me know and I'll see what I can do about grabbing one

**Comment by Bubbadoo** [comment]
You know what **IS** still up? Utterly Mad.
_Ignore me, I am being a cheeky bastard._

**Comment by kevingranade** [comment]
Yea this is my fault, I heard dreamhost and thought it was en.cataclysmdda.com going down and not the forums. 

Last db dump would be amazing.

**Comment by BorkBorkGoesTheCode** [comment]
Who won Last Survivor Posting?

**Comment by Rivet-the-Zombie** [comment]
>Who won Last Sausage Posting?

**Comment by Bubbadoo** [comment]
> Who won Last Survivor Posting?
It was Noctifer I believe.

**Comment by elricsfate** [comment]
@kevingranade @Rivet-the-Zombie @GlyphGryph I currently have the bandwidth (Been travelling the world for the past 6 months with no job. It's been awesome.) to handle this as well as a hosting account that is pre-paid for the next 2-3 years. 

If someone can provide me with the DNS stuff (Why are we still using en instead of just cataclysmdda.com???)  and the files I can have everything online sometime tomorrow.

**Comment by kevingranade** [comment]
I actually can't work on any of this at the moment because my Internet is down until Saturday  (how's that for timing? >_< ), but I've been trying to do some research on my phone.  Regardless, we're a bit stalled until GG can get back to us with that db dump.  I'll see if I can hunt down some DNS credentials, I think he handed them to me sometime... like a year ago...

Found an interesting option.  Since the last time I checked, Discourse grew an open source plan https://blog.discourse.org/2016/03/free-discourse-forum-hosting-for-community-friendly-github-projects/ that we might qualify for.  I'm looking at hosting because to be honest I'm a terrible sydadmin.  Don't take this as a "no" to any other offers of hosting, I'm just dropping this in as an option in case we want to switch to new forum software.  Frankly smf is feeling it's age, it's pretty old school and lacks effective community moderation tools.  This of course would not get us a website up, but I feel like it's a lot easier to wrangle hosting for a small website than a forum, and the forum is also much more critical.

**Comment by BorkBorkGoesTheCode** [comment]
Looks like they require 2,000+ stars. That is negotiable though, according to codinghorror.

**Comment by kevingranade** [comment]
I feel like the 500+ contributors will carry more weight than the "only"
1000+ stars, but hey, we'll see :)

**Comment by kevingranade** [comment]
> I feel like it's a lot easier to wrangle hosting for a small website than a forum.

For example: https://pages.github.com/
We can configure static page content (html or Jekyll markdown) in the /docs directory of the master branch, and bam, website.

**Comment by GlyphGryph** [comment]
Sorry on the delay getting the database access. I'm actually not sure if I *can* get them now. Working my way through customer support (also busy with other stuff and that will be over one way or another after the caucus tomorrow)

**Comment by kevingranade** [comment]
This isn't on you, if you can get us a DB dump you saved my bacon, if not, it's me that dropped the ball.

**Comment by kevin-at-corista** [comment]
I just bit the bullet and paid the bill - but I'm going to discontinue at the next opportunity, so still worth transferring over.

Also, it looks like the *main* page might be down now? Not sure what's up with that

**Comment by kevin-at-corista** [comment]
Unfortunately, I still can't seem to log in - I've got access through the web portal, but not to the data.

It might take some time - or I might have already waited too long. They told me I had at least a week, so I hope not. o_o

**Comment by kevin-at-corista** [comment]
Okay it says everything *should* be back within three hours, so I guess I'll send out an update at noon.

Then, hopefully, we'll have most of a year to figure out how to get the rest of this stuff to a more secure location :)

**Comment by kevin-at-corista** [comment]
Forums are back up!

**Comment by Chezzo** [comment]
Hooray!

**Comment by DangerNoodle** [comment]
Is it possible it may fail to load for some people, even hours after it was allegedly back up?

**Comment by DangerNoodle** [comment]
Even after fully clearing browser history, cookies, cache, etc it still fails to load for me.

Any possible cause?

**Comment by kevin-at-corista** [comment]
No idea - it's working for me across multiple machines.

**Comment by Coolthulhu** [comment]
Could be hardware problems on the way to the host. At one point, I couldn't connect from my real IP, only from proxies. No bans or anything, just no connection.
If it works through proxy, it's probably routing and it should pass in a day or two.

**Comment by DangerNoodle** [comment]
That is most likely the issue for me. My apologies for that.

**Comment by kevingranade** [comment]
Could be dns cache poisoning if the dns for the site didn't resolve for
some period of time.
You can try 'dig smf.cataclysmdda.com' on linux, idk what the windows tools
for this are.
