### ISSUE TITLE
Should Knit Scarf be made from wool yarn?

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#20698]
Knit Scarf should be made from yarn, material changed to wool, and the description updated.
Same for Long Knit Scarf, and their loose versions.

Why?
 - Brings it in line with Knit Hat
 - You knit with Yarn not with Thread (or sinew... eww.)
 - These items are from before yarn was added into the game so thread was the closest approximation

I feel that the qty should be lowered to reflect the larger component, but unless someone can provide guidelines (or a counter point) I'm going to leave that out of any PRs I make regarding this.

regarding a counterpoint:
> Coolthulu mentioned "Wool hat and wool scarf already exist."

I'll take his word on this (haven't actually tested them in game) I suspect taking them apart yields felt, and felt scarves are very different from knit scarves.  As an example imagine sleeping under just a knit blanket vs under a felt blanket.
More importantly, until yarn in the game can have different material types, or exists as it's own material type (since I think that determines the butchering loot) Knit items need to match the material types of their components.

**Comment by Xpyder** [comment]
This is intended to open a discussion, since a member expressed disagreement.  Or if no one responds by the time I feel like PRing I'll just submit it as a change

**Comment by Coolthulhu** [comment]
The wool scarves are knit wool scarves.

I was wrong about knit hats - in those, the cotton version is actually named cotton hat.

You can rename the knit scarves to cotton scarves if the name is misleading.
And possibly add felt scarves, but I don't think that's needed - yarn scarves aren't used all that often so felt ones would be just pure bloat.

**Comment by Xpyder** [comment]
The issue is that you knit with yarn not thread.  Also a normal survivor wearing a Knit Sinew Scarf seems....

**Comment by Xpyder** [comment]
maybe that just need to be merged into a single item?

**Comment by Coolthulhu** [comment]
> Maybe they just need to be merged into a single item?

No, cotton scarves do exist and should keep existing.

**Comment by Xpyder** [comment]
Ok, I think you've lost me somewhere along this path.

Do you disagree that Knit scarves should be made of Yarn?

**Comment by Coolthulhu** [comment]
> Do you agree that Knit scarves should be made of Yarn?

Wool scarves are knit scarves made of yarn. The knit scarves that aren't wool scarves should not be made of yarn, because they are a different item. If knit scarves were made of yarn, they would be identical to wool scarves in every way except name.

> I meant should knit scarves and wool scarves be merged?

No, because knit scarves are scarves made of cotton thread, while wool scarves are scarves made of yarn.

**Comment by Xpyder** [comment]
Can you provide any example of any knit scarf irl that isn't made of yarn?  I've searched and I can't find any, all that comes up is ones made of "Wool Yarn Thread"

**Comment by Xpyder** [comment]
> knit scarves are scarves made of cotton thread

I think you mean Cotton Yarn not thread.  Yarn and Thread are very different.  It would be like saying motor oil and Vaseline are the same because they're both lubricators made from petroleum.

**Comment by Xpyder** [comment]
I will acknowledge that you can knit with cotton (albeit with cotton yarn) and that the issue really traces back to yarn only being able to be of wool material type as currently implemented.

The issue is with the knit scarf being made of thread (of any type) rather than made of yarn (of any type) which is incorrect.

**Comment by Xpyder** [comment]
I'm not saying we should add it for scarves.  I'm saying the scarves should use Yarn not what they're using currently because knitting a scarf out of sinew or thread makes no sense at all.

Your issue seems to be with the material type change if I'm understanding you?

**Comment by Coolthulhu** [comment]
> The crux of the issue for me is that you're knitting with sinew and thread which isn't actually done.

Removing sinew from components is fine. It doesn't fit there at all and allows converting flesh into cotton.
Same for plant fiber and yarn, neither of which is cotton.

Thread should stay because we don't have cotton yarn and all yarn in the game is made of wool.
Just assume that it's a simplification here: the "thread" represents all cotton materials you can sew with.
The alternatives would be:
* Removing cotton scarf. But cotton scarves are pretty useful. The only reason to remove them would be to buff wool (this could be a good reason, though)
* Making cotton scarf uncraftable, because thread is not yarn. This would limit their availability pretty hard.
* Adding cotton (or acrylic or whatever) yarn. But again - overkill.

The "knit scarf" is just a cotton scarf. If the name is wrong, change the name. But don't turn it into a cotton scarf made of existing yarn (which is made of wool) or a wool scarf (which already exists and is named wool scarf).

**Comment by Xpyder** [comment]
I would argue that Knit scarves exist for the same reason Knit hats do, It's a warm starting item that can be easily disassembled into and rebuilt into other items (including string) depending on what you need (knitting isn't particularly hard either in game or irl).

Since yarn can be turned into string, if string (not thread) was hard to come by then this would be a more compelling reason to keep as it is.  As it stands I would be fine with it being split into Cotton Scarf from thread(uncraftable without a loom, which I don't think we currently have) and a Knit Scarf from yarn

If you wanted to PR a conversion of this to Cotton Scarf, and update the recipe and reversibility I'd be fine with that provided it's less disruptive to lore and balance than just changing it to use yarn would be.
