### ISSUE TITLE
"Other" crafting subcategory breaks to newline on small resolutions

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [CleverRaven/Cataclysm-DDA#20706]
Tested Windows curses 0.C 21860

The OTHER crafting subcategory is bumped offscreen when using low resolution settings. :(

**Comment by Leland** [comment]
@BorkBorkGoesTheCode screenshot?

**Comment by AMurkin** [comment]
May i?
![image](https://cloud.githubusercontent.com/assets/1931904/25612198/6c87aef4-2f32-11e7-89f4-ba44e39c67d6.png)

**Comment by kevingranade** [comment]
Perfect, thanks.  It's tempting to try and squish it, but that will break if translations provide longer labels, so really the only options are scrolling or wraping.

Scrolling is fine as long as we don't think we need all the category labels visible at once, and will impact the surrounding layout less.

Otherwise, we'll just have to bite the bullet and wrap it.

**Comment by Leland** [comment]
Also see #21262

**Comment by wapcaplet** [comment]
Still reproducible on 0.E-9603-g42468f6cab - in fact it's worse, since the green "No hidden recipe" text overlaps several of the main tabs:

![image](https://user-images.githubusercontent.com/238395/107867756-adebc380-6e3a-11eb-86a4-0cc54583ac20.png)

**Comment by ZeroInternalReflection** [comment]
I didn't see this issue before working on #56822, but this should be resolved now.  I ended up implementing a scrolling system since the primary category tabs were running into the same issue and wrapping category tabs seemed like it would be a real mess.
