### ISSUE TITLE
Weather changed through debug mode resets to pre-changed state after save and load

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#20703]
Don't know if it's bug or feature, but it's rather unconvenient.

**Comment by Coolthulhu** [comment]
That debug weather is generally not too well supported. I hacked it in because testing without was even more painful, but adding more hacks to it is rather hard. There is no good place to store the values for it.
For example, debug mode weather is ignored in retroactive weather calculations.

It might be relatively useful to have it stored in overmap weather settings, as a "debug biome" kind of a thing.

**Comment by kevingranade** [comment]
It's neither a bug nor a feature, debug weather is hacked in just well enough to test things, we don't care if it stays consistent over time.
