### ISSUE TITLE
MinGW compilation problems.

### ISSUE THREAD

**Issue by somot** [CleverRaven/Cataclysm-DDA#20739]
When I try to compile the CataclysmWin.cbp file with MinGW, the following error appears: c:\mingw\include\time.h:115:8: error: previous definition of 'struct timespec'

Any help is very much welcome.

**Comment by Qrox** [comment]
I also had this problem. It happens because the code does not check for `__struct_timespec_defined` which is the MinGW macro to mark the definition of `struct timespec` in `time.h`. The fix is to change the line
`#if !defined(_TIMESPEC_DEFINED) && !defined(_INC_TIME)`
to
`#if !defined(_TIMESPEC_DEFINED) && !defined(_INC_TIME) && ! __struct_timespec_defined`
in `posix_time.h`.

After fixing this problem, you might encounter two more problems, all code-related.

1. The compiler might complain about not being able to find the definition of `_putenv` in `translations.cpp`. The current code indeed tries to fix this problem by undefining `__STRICT_ANSI__` before including `stdlib.h`. I don't know if it worked before, but it's not working in my case since it seems that `stdlib.h` is already included by one of the previously included headers (`translations.h` or `string`. I haven't checked which). Moving `#undef __STRICT_ANSI__` to the start of `translation.cpp` fixed that.

2. The linker might complain about muliple definitions of `vsnprintf` in `libmingwex.a` and `stdio.h` when linking the unit test binary. This can be worked around by adding `#define __USE_MINGW_ANSI_STDIO 0` before any includes in `tests\catch\catch.hpp`. This disables the definition of `vsnprintf` (and a bunch of other functions) in `stdio.h`. (If you compiled the unit test sources before, you may want to do a clean build, since the makefile does not seem to check whether `catch.hpp` has changed).
