### ISSUE TITLE
Make microwaves, fridge, washer, dryer, oven, shower, toilet functional.

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [CleverRaven/Cataclysm-DDA#20806]
I'd like to be able to eventually use all the aforementioned items to somehow add to the realism. Food spoils slower in fridges (yes, minifridges are a thing, I know, I'm talking normal fridges). Washer to wash the dirty clothes, dryer to make wet clothes (after an extended period of time in rain) dry and warm (for bonus morale), shower if you're cold for morale and to clean yourself (dirty, a new negative effect maybe?), toilet to relieve yourself after eating or if you have diarrhea, oven/microwave to prepare / heat up food.

And so much more. There's so much furniture left unused that can be made to add to realism...

**Comment by cdag** [comment]
I think the reason why furniture doesn't work in game is because... well it's the end of the world. You think the power grid would be up for anything that isn't emergency related? Terminals are understandable in some places. Hospitals for example usually have generator rooms to keep life support on if the power goes out. With that being said, I think the toilet idea is a bit much. I don't think a need to use the bathroom adds much to the depth of gameplay. A few of your ideas however could possibly add to gameplay. Showers for example could give a morale boost or play a part in preventing wounds from getting infected, like getting tetanus from broken windows or walking on metal debris. If you take a look they have IRL camping shower kits. Most of these things might be better off being made into a mod.

**Comment by mutt3x** [comment]
There is no electricity so they are not working (if i remmember the explanation) but i do think the utilities could have some specific uses

Microwave: could make some food faster
Fridge: could have more storage room but its only stationary (non-vehicle)
Washers could wash more robes at once. (agian non-vehicle)
Showers... morable boost maybe. (non-vehicle)
You only need a source of power.

I say non-vehicle because these utilities could be house-only and might be a good reason for the players to consider making stationary bases. ATM mobile bases (vehicles) are simply better in every way possible. This could somewhat equalize the usability of stationary bases.

The toilet thing is bloat and cringy.  -1
You can add washing, you can add vitamins but please for the love of god DONT ADD BLADDER CONTROL. Think beyond your realism fetish, think about other players that just want to play a roguelike.

**Comment by Zireael07** [comment]
Most of the stuff has been already suggested on the forums.

**Comment by DangerNoodle** [comment]
Usage of this feature would likely be limited to portable electronics, if they can be used off of vehicle power. Methods of DC to AC conversion do exist, so this is realistic. In actual implementation, only electronics that exist in item form can easily be used for this, by allowing them as items for vehicle part construction. Any system that combines vehicle power with more static features such as furniture will involve more work.

Needing to use toilets however is a terrible idea. We absolutely do not require more realism focus when that aim has caused to bulk of controversy among the playerbase. Any such addition would need extensive testing for balance, proper application of realism (meaning no situations were lack of realism is exclusively to the detriment of players), and overall sanity well before it becomes merged, something that current development has not done for the majority of new features.

**Comment by Unrepentant-Atheist** [comment]
That's fine being utilities being usable from vehicle or portable powers. All fine and dandy, just being usable is a wish of mine. 

I get the reasoning behind it being non-functional after a world wide cataclysm, doesn't mean I should be able to jurry-rig it to run again somehow.

**Comment by cdag** [comment]
If you read DangerNoodle's post it best sums it up. Household electronics run off of AC current. Vehicles use DC power but something exists called a "Power Inverter" that takes DC current and allows you to use AC devices from your vehicles power. Most of these are rated at certain wattages and things can happen (blown fuses, melted power inverter, fire) if you exceed the wattage. Something like this would be awesome to have implemented so we could make giant mobile bases with all sorts of luxurious amenities, but sadly right now only one type of electricity exists in the game. There is no implementation right now of AC/DC power.

**Comment by WizardOfOoo** [comment]
The jury rig is to put in on a vehicle and run it off vehicle batteries.
Nothing says that a vehicle has to have wheels.

**Comment by kevingranade** [comment]
Several of the things mentioned in the OP can certainly happen, but we can't afford to keep vague wishlist issues open.
