### ISSUE TITLE
Old commit #18881 appears to break Krav Maga's weapon use

### ISSUE THREAD

**Issue by aeoo** [CleverRaven/Cataclysm-DDA#20948]
#18881 "added" tonfas to Krav Maga weapons, however, this appears to have had the effect of disallowing any weapons *other than* tonfas.  That means Krav Maga's "cutting" bonus is no longer utilized and Krav Maga's old knife use is no longer operational as well.  Even though it says "cutting bonus" in the description of its Krav Maga Edged trait, it's actually a stabbing bonus that used to work with knives if I remember correctly.  There is a "melee_allowed" flag on the "cutting" (really: stabbing) bonus.

Can we please either revert #18881, or otherwise, add all the small stabbing weapons as well as tonfas?

**Comment by kevingranade** [comment]
AFAICT the cutting bonus should still work since "Krav Maga Edged" has melee_allowed:true, but KM will not show as enabled if the player is wielding a knife.
Also AFAICT, reverting that PR will not change any of this behavior, just disable some of the bonuses for Tonfa.

Feel free to PR an addition of misc small knives to the Krav Maga weapon list.

**Comment by aeoo** [comment]
I see.  I got confused by the status changing to "Normal", but I think you're right because in the '@' character screen the bonus does still show.  I was assuming "Normal" meant "no style."  I think it's a bit confusing in terms of UI, but it works as designed under the hood, so I'm closing this issue.
