### ISSUE TITLE
Better Status indicators

### ISSUE THREAD

**Issue by Lazasar** [CleverRaven/Cataclysm-DDA#20969]
In the midst of fighting off a horde of zombies it can be hard to tell all sorts of things that should be affecting decision making:

1. Am i standing in acid?
2. Am I grabbed? And which zombie has grabbed me?
3. Am I standing in a poison cloud

etc.

Some kind of area in the UI maybe at the top of the screen...

**Comment by Night-Pryanik** [comment]
Grabbed effect can already be seen in `@`menu.

Good idea, of course, but unfortunately, sidebar is already clustered, very little free space (if any) for any additional info.

**Comment by ChuckJKelly** [comment]
> Grabbed effect can already be seen in @menu.

You can also use x to see if the tile your currently standing on has acid on it, but neither of those things is very convenient to do during combat.

**Comment by DangerNoodle** [comment]
Fields not showing are a console-mode-only issue. Since they can be seen in the sprite background in tiles mode, it might be desirable to make use of background color to depict whether the player is currently standing in a field, in console mode.

**Comment by notafed** [comment]
It would still be nice to know these things in tilesets version. Especially grabbing, since it's very important to combat and you have to constantly flip back and forth between the fight and your character sheet, for something that should otherwise be very obvious to the character (and the player) without having to examine himself.
