### ISSUE TITLE
Extra-light quarterpanel heavier than quarterpanel

### ISSUE THREAD

**Issue by Qrox** [CleverRaven/Cataclysm-DDA#20994]
In the vehicle part installation menu, quarterpanel is 1.0kg with 240 durability, extra-light quarterpanel is 1.2kg with 100 durability, heavier than quarterpanel.

**Comment by Leatherlappen** [comment]
The densities here really don't match up. Both steel sheets and pipes (Which are the parts that make up boards/quarterpanels and xl-quarterpanels) each have a volume of 1dm³, but a mass of 1kg and 1.25kg respectively. In reality steel has a density of ~7.8kg/dm³.

**Comment by Qrox** [comment]
For pipes that weight is reasonable since pipe is a hollow object. So we can increase the weight of steel sheets to something like 7.8 to fix this.

**Comment by Leatherlappen** [comment]
Looking in metals.json it should probably 7.6kg/dm³ since that's the density used there - which is also a reasonable density for steel (it varies depending on the alloy) - just for consistency.
That said, increasing the mass of metal sheets would also increase the mass of all vehicles, possibly dramatically, so the power of engines might have to be increased as well.
Does mass affect other things? Like combat viability for example?
It's a bit too late at night for me to look into this right now, will experiment a bit tomorrow, probably.

**Comment by DangerNoodle** [comment]
Would extra light quaterpanels be made out of pipes though? They could possibly lightened if they were set to use plastic or some other component, assuming that pipes are not lightened.

**Comment by Leatherlappen** [comment]
Making them out of plastic chunks makes a whole lot more sense. The name could also be change to "plastic quarterpanels", since "extra light" is kind of a boring name. And since getting your hands on plastic is already really easy I don't think any balance is disturbed.

**Comment by Leland** [comment]
So each type of "board" (cloth board, heavy duty board, etc) has one specific large item that they use as the base for their weight. E.g. the generic quarterpanel uses `sheet_metal`, and the clothboard uses `sheet`. Is there a generic sheet-like piece of plastic item in the game that we can use here?

**Comment by DangerNoodle** [comment]
Currently we only have plastic chunks.

**Comment by Leatherlappen** [comment]
My suggestion is this:
Sheet plastic is added, volume of 1L (same as sheet metal) and mass of 0.5kg, slightly worse durability/mass than regular boards. (Less efficient but more specialized.)
Plastic chunks swapped for sheet plastic in a few items, eg. microwaves and TVs.
Volume of plastic chunks reduced by like a fifth, to 0.2L. This also make other objects contain more reasonable amounts of plastic. (Gameboys are currently 400% plastic, by volume at least.)
Name of extra light quarterpanel changed to plastic quarterpanel, and plastic board is added.

**Comment by Qrox** [comment]
What about extra light frames? Currently they are made of aluminum.

**Comment by DangerNoodle** [comment]
Frames are acceptable, it makes more sense for the frame to be metal than for the body to be. Many modern cars use a non-metal body with a steel frame.

**Comment by DracoGriffin** [comment]
Since extra-light frames rely on aluminum ingots, could just simply change the single "pipe" (which is already weird, how is one pipe becoming a quarterpanel?) to a single "material_aluminum_ingot" (google shows them to be quite large). If not that, then an aluminum sheet of a sorts (not sure what tools would be required if allowed to be craftable?) -- smashing it would produce a 1-3 ingots (half of what it takes to make an extra light frame).

I think working with aluminum makes more sense rather than coming up with plastic frames -- especially to commit to keeping uniformity between extra light frames and quarterpanels (why are extra light frames made from aluminum ingots but quarterpanels are made from plastic?).

Changing pipe to material_aluminum_ingot has these changes for the quarterpanels:

|   | Durability | Weight |
|---|:-:|:-:|
| Quarterpanel  | 192  | 2.2 lbs |
| Extra light quarterpanel (pipe) | 100  | 2.8 lbs |
| Extra light quarterpanel (aluminum ingot) | 100  | 1.5 lbs  |

**Comment by cake-pie** [comment]
Resolved by #25210 making steel sheet (and hence quarterpanel) 6kg

**Comment by nexusmrsep** [comment]
Resolved as mentioned above.
