### ISSUE TITLE
batteries crafting balance

### ISSUE THREAD

**Issue by tsulh** [CleverRaven/Cataclysm-DDA#21009]
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/recipes/recipe_electronics.json#L469

I suggest to replace  "qualities" : [ {"id":"SCREW","level":1} ] with soldering iron or welder charges, and add wire and copper wire, and copper scrap to the recipe (to make cathode).

Also, I'd increase the crafring time from 5min to at least 10min, since the crafter should make the battery shell to be exactly the size of the regular battery (to fit it into devices like mp3 player), which takes time.

**Comment by Solusphere** [comment]
Requiring batteries to make batteries seems counterproductive, and not necessarily realistic, except in the instance of making them out of scrap metal rather than cans or canisters.

As for the form factor, batteries in CDDA are very abstract to begin with, and the recipes to make them are have that vagueness in mind. I don't think you should be adjusting the recipe to fit a specific form factor until the batteries themselves are made more specific as well.

**Comment by l29ah** [comment]
Real world "dumb" batteries don't use copper.

**Comment by Treah** [comment]
@Solusphere  Nowhere in his description does it say that the recipe requires batteries to make batteries :)

**Comment by Shadefang** [comment]
Adding the requirement for a soldering iron or welder essentially adds the requirement for batteries to make batteries. Almost every way of getting around that that I am aware of is high enough tier that you wouldn't really be making batteries anyway at that point.

**Comment by Night-Pryanik** [comment]
Closing as per lack of discussion.
