### ISSUE TITLE
Canned Meat and Canned Fish unable to be heated

### ISSUE THREAD

**Issue by Zilenan91** [CleverRaven/Cataclysm-DDA#21037]
Unlike stuff like cooked meat, you can't heat canned meat or canned fish with anything.

**Comment by ituluwituluwzev** [comment]
They don't have EATEN_HOT flag, as they does not become more enjoyable when heated.

**Comment by Zilenan91** [comment]
Well yeah but most meat has this

**Comment by kevingranade** [comment]
I gagged a little thinking about eating hot canned meat, that does NOT
sound appetizing.

They intentionally don't have EATEN_HOT.

**Comment by Night-Pryanik** [comment]
Well, don't know about New England canned meat, but we here in Russia (just an example) do heat up canned meat, and make the awesomest dishes from cooked canned meat.

**Comment by Zilenan91** [comment]
I mean Canned Meat in the game can't be THAT bad, it has more enjoyability than cooked meat does as a baseline. The only positive morale cooked meat provides is when it's heated.

**Comment by Balketh** [comment]
Well, most canned fish I've ever seen is sold to eat cold, but most canned meat, which can and often is recommended to eat cold, can and is also recommended to eat hot, or as part of recipes. I know SPAM is a differing thing in a sense, but any kind of canned red meat or chicken would benefit in some way from being warm, even if it's just because it's a hot meal, not that it tasted good.
