### ISSUE TITLE
JSONifying Garages and Adjusting drop rates after spawn fix

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#21049]
I just ran through 7 garages and found 0 welders, makeshift welders, or acetylene torches.  There used to be an aceteline or welder ever 2 garages, along with a bunch of other stuff, but 4 of these garages had nothing and the rest only had 1 item on the counters.

I'm also pretty sure that something was changed recently to affect monster spawns (there was a bug causing overpopulation), so it's definitely possible this drop rate is the new intended norm or an outlier, but I wanted to check it wasn't an unintended side effect of that other fix.

**Comment by Solusphere** [comment]
I'm pretty sure it's because the garage was relying on a flawed implementation of the item spawn mechanics, which has since been fixed. Unfortunately the garage and several other map tiles have not been updated accordingly, causing them to spawn little or no loot.

I tried to take a look at the garage myself, but it looks like it hasn't been jsonized?

**Comment by Toothspit** [comment]
> I tried to take a look at the garage myself, but it looks like it hasn't been jsonized?

Correct, there are bunch of dinosaurs living in mapgen_functions. [Here you go](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/mapgen_functions.cpp#L3409). I couldn't find much discussion on jsonifying these, but it's probably a separate issue from item spawn woes.

On-topic, has anyone done any measurement of item spawn before and after that recent merge? There've been consistent mumblings in IRC, this isn't an outlier.

**Comment by ZenZen2** [comment]
@Xpyder can you tell me your item spawnrate setting ?

**Comment by 1skandar** [comment]
To chime in here, I'm experiencing the same thing and my spawn rate is set to the default.

**Comment by Lazasar** [comment]
Ditto

**Comment by 1skandar** [comment]
Ok, if I'm reading the code rightly, and lord knows I may not be,  it seems json-ized buildings have a different spawn function verson non-json-ized. And the bug in the spawn rate was on the non-jsonized side.

And my experience seems to bear this out. Houses, grocery stores, and such are unchanged, but offices, mansions, garages are the ones impacted. 

Basically, I guess, that means that priority needs to be placed on jsonifying the remaining structures, yeah?

**Comment by Night-Pryanik** [comment]
> Basically, I guess, that means that priority needs to be placed on jsonifying the remaining structures, yeah?

Yes, that's the goal.

**Comment by 1skandar** [comment]
Kinda nice that, *if* I'm correct this will be an issue that will be solved as a side-effect of work already underway. I'd say, as a test, JSON-ifying garages would prove things. 

Well, I understand the JSON format, at least, and the structure in code looks simple enough. And I've got nothing to do for a few hours. I'll see if I can JSON-ify the garage and test it a bit.

**Comment by Night-Pryanik** [comment]
@1skandar, you can look at #20308, #20307, #20304, #20276 on how to jsoni-fy hardcoded map locations.

**Comment by 1skandar** [comment]
Might need a bit of help. I can create the JSON easy enough and get it to generate, but pulling the hardcoded bits may be trouble. 

Actually, I've got the garage JSON itself nearly done. I just need to add it to overmap_terrain to see if it works.

**Comment by 1skandar** [comment]
https://dl.dropboxusercontent.com/u/46780505/garage.json

I think I got the JSON working? If someone will give that a quick look over to see if I did anything egregious.. If not, I'll try to figure out how to submit a pull request.

Each counter has a 1 in 5 chance of generating loot, so about 4 ish items per garage on default. Should be about right, I think?

**Comment by pisskop** [comment]
> I think I got the JSON working? If someone will give that a quick look over to see if I did anything egregious.. If not, I'll try to figure out how to submit a pull request.


Looks okay from a quick glance.  this is good.  Ill submit one for you if you;d like.

**Comment by 1skandar** [comment]
If you wouldn't mind. It'll need the "om_terrain" value changed to  "s_garage", I added the t so it wouldn't conflict, but for a replace it should match. I think?

And then the garage should be pulled from [here](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/mapgen_functions.cpp#L3409). 

Since the ID matches there should be no need to modify anything else. 

And I'm going to sit down and figure out this whole git thing as soon as I have time. I'm not a good enough at C++ to submit actual code, but JSON is easy and the code changes appear minimal, for single tile map terrains at least. I can spend a couple hours every few days digging the rest of the buildings out of source and into JSON. Give back a bit.

**Comment by Leland** [comment]
@1skandar promise, it's not too crazy. It's a very novel concept if you've never worked with a version control system before, and can take some time to get your head wrapped around it, but really all that git is is is a series of changes over time, represented on a graph.

Check out GitHub's tutorial series for a good intro: https://try.github.io/
