### ISSUE TITLE
Travis CI commit tester generating failures, both are unhelpful for reporting build errors

### ISSUE THREAD

**Issue by DangerNoodle** [CleverRaven/Cataclysm-DDA#21050]
As stated, the presumably recently introduced Travis CI build bot is causing all checks to fail, cause unknown.

Id addition, neither current tester provides easy access to the actual error message. Travis appears to only provide compile logs up-front on some commits, while others it does not unless a specific link is clicked. Meanwhile I am unable to find build messages in the Gorgon build bot details screen.

**Comment by kevingranade** [comment]
It's a real and valid build failure, so that part is working as intended.

You have to drill down into the build matrix, but the error is fairly clear in travis https://travis-ci.org/CleverRaven/Cataclysm-DDA/jobs/233498180 (more clang warnings about template instantiation)
And likewise in gorgon, though it isn't subject to the recent breakage since it only happens with clang 4.0

**Comment by DangerNoodle** [comment]
Understood. My main concern is that the older Jently bot exclusively displayed the compile logs, with any errors at the bottom, so it was quicker to find the problem than with these systems.

**Comment by kevingranade** [comment]
I'm not sure what you expect, we don't maintain the build UIs.  If you have an alternative that works the way you like feel free to suggest it and we can evaluate features, but otherwise we'll just get what travis and jenkins provide.

**Comment by DangerNoodle** [comment]
Very well then, my apologies for that.
