### ISSUE TITLE
Bone arm guards use wrong layer

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#21055]
Currently use "normal" layer, but all other arm guards are "strapped"

**Comment by Xpyder** [comment]
Looks like Leather Arm Guards also exibit this inconsistency, but all the other are indeed strapped

**Comment by Leland** [comment]
Confirmed. Looks like these lines are missing the `BELTED` flag:

https://github.com/CleverRaven/Cataclysm-DDA/blob/137cb1c57d9418ed0d8d5ddd90479269f2ee9e3e/data/json/items/armor.json#L207
https://github.com/CleverRaven/Cataclysm-DDA/blob/137cb1c57d9418ed0d8d5ddd90479269f2ee9e3e/data/json/items/armor.json#L272

**Comment by DangerNoodle** [comment]
There are also steel arm guards with use outer, because I added the option to wear the cuirass separate, or craft a set of light plate using the components instead of forging it as one set.

At some point I would like to add a steel/leather Japanese armor of the tosei-gusoku style, allowing the use of the cuirass for a different recipe.

**Comment by Xpyder** [comment]
Initially I was going to suggest they be changed to Outer to fit better with the vambracers and elbow pads, but then I realized they'd conflict with trenchcoats and dusters which I think is how they ended up in "strapped"
