### ISSUE TITLE
Ability to transfer liquids between tanks.

### ISSUE THREAD

**Issue by Lazasar** [CleverRaven/Cataclysm-DDA#21098]
For example, it would be nice to be able to purify a tank, and then move that water to an empty tank so that the funnel can refill the tank ... or just for prettiness, to have all the gas tanks lined up, and the water tanks lined up, etc

**Comment by Leland** [comment]
So I'm closing this in favor of #18815 because it addresses your exact use-case: purifying water. What's awesome is that PR #21095 will address this.

However, if you want a broader discussion about a general ability to transfer liquids between tanks, outside the context of water purification, let me know and we can reopen.
