### ISSUE TITLE
Vehicle curtains inconsistent

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#21110]
Windows and doors only take a sheet to make a vehicle curtain
Aisle Curtains take a special crafted item.

The equipment needed to install a curtain into a window or door should be essentially identical to that needed to put one in an Aisle.  I could see the Aisle curtain needing to be attached to an aisle (or aisle with lights) tile so you can't just put them in an empty frame (if we feel doing so is important for balance reasons)  or for windows and doors to be changed to require the Vehicle curtain item rather than just a sheet.

But it's very strange to have these two essentially identical objects have such different requirements (one requires hammering 2, metal sawing 1, bolt turning 1, cutting 1, sewing 1, fabrication 2, mechanics 1, and 4 wires; while the other just takes smashing a window in any house)

**Comment by jtgibson01** [comment]
Hmm... this could go either way.  Technically, depending on the furnishings already present in a pre-built car, you already have various things to dangle sheets off of near a car door or window -- (in real life) when I was running a vehicle in my job at night, on my lunch breaks I'd routinely just dangle my work jacket across the grab handle and seat to block out one of the prevailing lights when I stopped in an otherwise pitch dark parking lot, so I could turn the e-book screen brightness *way* down.

But actually installing the furnishings necessary to support a curtain from the ceiling or between two adjacent walls requires at least *something* else on top of that.  That's what I presume the fabrication part of it entails: manufacturing and installing a curtain rod with rings, as well as all of the grommeting to set up the curtain properly.

Thus, the door/window curtain versus the aisle distinction makes a perverse sort of sense.  It's relatively simple to string up a block over any door (and windows only slightly more difficult).  It's much harder to install one in an aisle.

However, aforementioned realism arguments aside, I wholly support this.  I'd be in favour of a compromise approach between the two, however, rather than the "strictly up to spec" aisle curtain that's already there.

I figure the ideal would be: wires and a sheet, no special skill required.  Anyone could string up a sheet pretty much anywhere with a set of wires and a sheet, whether by tying the wires off to any convenient fixture and dangling the sheet over, folding the top lip of the sheet over a wire with another wire "sewn" through it and poked into the headliner, etc.  Debatably: mechanics 1, to make it less about the player's foresight and more about whether the *character* is smart enough to do it.  The wire requirement would unfortunately make it less easy to block out windows in the early game, but the consistency would be worth it in the end.

**Comment by Xpyder** [comment]
> wires and a sheet, no special skill required
I think this would be a good compromise

**Comment by rm-code** [comment]
I'm working on a PR for this atm. At the very least I think we could get rid of the special item. I think that just using wires and a sheet would be a bit too simple considering that sheets are a pretty heavy material in CDDA and a curtain on windows and doors doesn't need to be openable.

The current recipe goes for something like [this](https://i5.walmartimages.com/asr/4e7b1c11-9925-4acd-85bc-a7c7c9e386a8_1.08486df4b5122d9d327b4f7fddbd6498.jpeg?odnHeight=450&odnWidth=450&odnBg=FFFFFF) as far as I understand. I think something like [this](http://thefrugalhomemaker.com/wp-content/uploads/2014/06/DSC_0024.jpg) would make more sense.

**Comment by Xpyder** [comment]
> " a curtain on windows and doors doesn't need to be openable."
I disagree on this, the biggest thing I tend to use them for is to make a windshield I can black out from the sun when I need to sleep during the day

**Comment by Theundyingcode** [comment]
I second @Xpyder... Actually I don't understand the use of vehicle curtains except blacking out the windshield so turrets don't shoot you. (and sleeping)

**Comment by rm-code** [comment]
Like @Xpyder and @Theundyingcode I think window and door curtains should be openable, but that's not really the point of the ticket. The real issue is the discrepancy in the crafting process between aisle curtains and "normal" vehicle curtains.

@Theundyingcode They can be used to separate the driver's cockpit and the rest of a van / RV for example([example](http://www.curtain-tracks.com/media//wysiwyg/wordpress/v/a/Van-3.jpg)). In CDDA it probably doesn't make much sense, but IRL somebody could drive while another person sleeps in the back (hopefully with their seatbelts on :P). Also it's just another way to design your car.
