### ISSUE TITLE
Moving items to inventory via advanced management yields "Too heavy"

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#21200]
[Build 6504] As the title says, anything I try to move from somewhere around my character into my characters inventory yields the message: "This is too heavy!." When I clearly have both the weight and volume requirements met.
![capture3](https://user-images.githubusercontent.com/24307650/26891365-c2bf626e-4b82-11e7-8814-f4c9681ca53b.PNG)

**Comment by Leland** [comment]
@CoroNaut this is a duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/21167, an issue which should have been fixed by https://github.com/CleverRaven/Cataclysm-DDA/pull/21172. That update was only merged into the game 12 hours ago.

Can you double check your CDDA version? And if it's outdated, try running the most recently updated version.

**Comment by CoroNaut** [comment]
Yep sorry my fault, CDDA launcher confused me in the versions.
