### ISSUE TITLE
Agricultural vehicle parts not craftable

### ISSUE THREAD

**Issue by WraithCadmus** [CleverRaven/Cataclysm-DDA#21393]
### Expected Behavior
There are recipes in the game for 
- Reaper
- Seed Drill
- Plow
- Scoop(?)

So there should be a method by which they can be learned.

### Actual behavior
They aren't autolearned, and they appear in no books. Rendering them uncraftable.

### Steps to reproduce the behavior
1. Create a character
2. Debug yourself 10 in every skill
3. Debug yourself every book

The three (four) recipes are still uncraftable.

### Proposed Solution
A book should be made, *Your Friend on the Farm*. A manual produced by a tractor manufacturer covering their products with an irritating corporate mascot. It should have the three(four?) recipes above plus one or two from *Under The Hood* (vehicle controls?) as exploded diagrams, but doesn't provide enough skill to understand making them from scratch.

I'm not sure on skill requirements, fixing tractor parts needs Mech 5 so that would be the logical maximum but that does seems quite high. You should learn the recipe at Mech 6 if that's the case perhaps? Also I don't know how to pitch the minimum, could it be said the book assumes you have basic car-fixing skills, so bump the minimum to 2? That's a lot of overlap with Mechanical Mastery, but with far fewer recipes.

Locations should be Farms (most common), Bookshops (obviously), Garages (rare).

### Other Info
Issue #19929 by @Asmageddon made a mention of this, but that issue was closed due to being unfocussed.

**Comment by WraithCadmus** [comment]
I was just having a think about the Scoop, it's usable on other vehicles (like the street sweepers) so maybe put that in *Mechanical Mastery* instead?

**Comment by Tharn** [comment]
Can these recipes be learned by disassembling the parts?

I'm thinking agricultural machinery is a fairly specialized thing and there doesn't need to be a book-learnable recipe in the game for every piece of esoteric equipment. But I'm not opposed to the idea.

**Comment by WraithCadmus** [comment]
Hadn't thought about disassembly, is that the `"reversible": true` bit in the recipe that means that's possible?

**Comment by WraithCadmus** [comment]
To follow up on disassembling I don't quite understand the code well enough to understand what you can learn from disassembling, but I did debug myself skill 10 and 10 reapers and nothing happened after disassembling all of them. So that's either a no or just too high a price given how rare these parts are.

**Comment by kevingranade** [comment]
Reaper, seed drill, and scoop are not intended to be player craftable. 
IIRC there's a mod that makes them  craftable.

**Comment by DangerNoodle** [comment]
> Reaper, seed drill, and scoop are not intended to be player craftable.
> IIRC there's a mod that makes them craftable.

Incorrect. These unusable recipes are in the game itself. See https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/recipes/recipe_others.json#L6891

If they were not intended to be craftable, then whoever decided to add unobtainable recipes for them rather than remove the recipes made a mistake, and is ultimately responsible for this issue occurring.

**Comment by kevingranade** [comment]
The mere presence of a recipe means nothing, dead code or data is technical debit, not a bug.

**Comment by DangerNoodle** [comment]
My reasoning was that someone intentionally made the recipe unusable rather than removing it entirely.

**Comment by ArikVhedrovix** [comment]
Why were they meant to be uncraftable? Is it too overpowered? Not in the intended spirit of the game? I don't mind either way as I have yet to farm anything. Hunter gatherer life suits me ok. A lot of people seem to like starting settlements and I could see farming being helpful for supporting a large group of NPCs(assuming needing to eat was enabled).

**Comment by kevingranade** [comment]
Between trhose two, 'spirit of the game'.  Combines and robotic devices for
pickinf up itemscare masdively complex machines thst its not reasonable for
an arbitrary survivor to build from scratch.

**Comment by Asmageddon** [comment]
I'd argue that the more basic ones at least aren't much more complex than futuretech batteries or some of the CBMs, both of which said arbitrary survivor can build.

**Comment by AlecWhite** [comment]
It makes the player require a vehicle specially built for it, with enough fuel for the vehicle to work and enough space for the vehicle to move.

Having able to craft it is more a convenience/quality of life thing for the player(the real life person, not the character) than "spirit of the game" or balance.

As it simply saves up a lot of mind-numbing key-presses for the player, increasing fun and reducing gratuitous tedium that doesn't really add anything to the game.
It really doesn't save as much time of in-game character time, as it does for the player IRL time and general mental health.

And the "it helps the player plant and harvest massive quantities of food", isn't really much of an argument since you can do the same without it, and with barely much in-game time spent on it, but without the aforementioned mind-numbing key-pressing. 
Unless of course the whole point of not being able to craft these parts, is to artificially and arbitrary punish players that opt to plant food.

**Comment by Coolthulhu** [comment]
It's not as much intentionally punishing the player as just the farming system being bare and unfinished.
The agricultural parts are bandaids on the bad farming-related UI. UI isn't intentionally bad, it's just bad because it lacks QoL enhancements such as "jobs" for the character to automatically perform.

That said, I'm pretty sure the uncraftability of some of those is just an omission.
For example, the plow - it shouldn't be arcane tech.

**Comment by Asmageddon** [comment]
For what it's worth, farming without a vehicle takes bloody ages, while being crazy fast with one - plow being the most important part here, since the others are largely QoL stuff. IMO, both tool-less and vehicular farming need some adjustments. The first is too slow, the latter too fast.

**Comment by kevingranade** [comment]
Plow is an oversight, yes, feel free to add a recipe for that somewhere.
That having been said, I'm cleaning up some issues, and "please make a place for a crafting recipe for a specific item" doen't rate an open issue, please PR.

**Comment by DangerNoodle** [comment]
> That having been said, I'm cleaning up some issues, and "please make a place for a crafting recipe for a specific item" doen't rate an open issue, please PR.

Again, note that the recipes exist but are set to be unusable. These either should be assigned to books, or removed. If no one does either I can do so, depending on which you would prefer.

**Comment by AlecWhite** [comment]
>If no one does either I can do so, depending on which you would prefer.

Unless the whole point of not having those recipes is to punish farming, please do so.
