### ISSUE TITLE
No offence but the way bionics need painkillers to install is silly.

### ISSUE THREAD

**Issue by youlickassholesformoney** [CleverRaven/Cataclysm-DDA#21424]
It feels like someone got a wild hair up their ass and wanted to make bionics more "difficult" now all you need to do is pray you find oxy or tram in some random bathroom so you can install it after smoking your meth, the already somewhat hard to find CBMs that appear in general electronic stores for normal every day people without a prescription to high powered pain killers are absurd because seemingly anyone can buy them, this is a paradox that feels like it was added because the process 'needs' to be 'difficult' even though you already need to have high medical and electronic skills to install any CBM worth a toot or else you risk getting a semi-permanent disability or losing any other bionics you've gone out of your way to collect.
I don't see it making much sense, I'm not trying to offend anyone who thought it was a good idea but.

As someone who does have a prescription for high powered pain medicine let me tell you that's not how it works, it doesn't make you immune to pain it just dulls your senses and makes you feel better, if you were already in pain now its manageable but new pain and especially getting cut open is going to be horrifying and painful, what makes sense is that CBM installers would come with auto-injecting anesthetic since they're already expensive disposable equipment.
Anesthetic and painkillers are very, very different and there's a reason you get one and not the other before surgery

**Comment by BaronVonClop** [comment]
Agreed entirely. Given that CBMs are supposed to be self installing kits, I've always just assumed that they came with local anesthetic in a high enough dose to make the installation _manageable_ pain wise.

It's also super silly that you take an oral painkiller to do a surgery. That isn't how medicine works, and no doctor is going to load you up with oxycodone instead of anesthetic. I get that it's the post apocalypse and the whole idea is "work with what you've got", but that's still really strange.

A suggestion on reddit had a great idea. If a full fledged kit is found, uninstalled, it comes with the necessary anesthetic and/or painkillers for installation. If a CBM is ripped out of a corpse, it does not, and would _then_ require additional medicine.

As it stands now, it makes whether or not I can ever install CBMs totally based on RNG. It's difficult enough to find the right ones, but now I also _have_ to keep searching and hope that one day I come across the exact right pill in order to install it? That really sucks, IMO.

**Comment by kevingranade** [comment]
Working as intended, this is not a forum, try smf.cataclysmdda.,com
