### ISSUE TITLE
CBMs needs painkillers regardless of being new or used

### ISSUE THREAD

**Issue by AlecWhite** [CleverRaven/Cataclysm-DDA#21423]
CBM are supposed to be a kit of the bionic and all the tools needed to install it. 
A brand new CBM looted from a locked cage in a lab should not need anaesthetic or any kind of tool to install it.
A salvaged or butchered *bionic* out of a corpse, should need anaesthetic and tools to install

Thanks to https://github.com/CleverRaven/Cataclysm-DDA/pull/20892 any CBM regardless if it was hard earned through lab raiding and hacking a locked box or just killing and butchering a random technician, needs lots of painkillers.
So far installing CBM already made almost obligatory to use any kind of intelligence enhancing drug to reduce the fail chances. Which is what the majority of players did, as it has become the current metagame of installing CBMs. As the consequence of a bad installation range from a faulty bionic, mutation or death.

This seems to be a rather lazy and incomplete implementation of distinguishing between low-difficulty RNG based butchered **bionics** or hard-difficulty looted **CBM**s proper. 

I understand the need between killing a zombie technician with a rock in a sock, butcher it with a pocket knife and getting a CBM; and having to get a lab card, deal with security turrets, manhacks and security bots, hack a CBM display case to get a CBM.

Plus painkillers being as vague as they are at telling the player how much is enough, and that there's a fine line between enough painkillers and "your breath stops completely", having specialized anaesthetic would be needed for the current state of CBMs.

If we are going to differentiate between **CBM**s and butchered **bionic**, we need a properly designed and implemented system. Instead of further penalizing all kinds of CBMs regardless of how they were acquired.

**Comment by BaronVonClop** [comment]
Adding on, the drugs required don't even make sense. You'll never find a doctor that tells you to take six codeine pills instead of anesthetic before surgery; that'd be absolutely absurd. And even if we do go down that route, why isn't morphine an option? I can shoot myself up with _heroin_ and install a CBM high as a kite with no issues, but morphine is where we draw the line? If heroin is allowed, why can't I get really drunk instead? Slugging liquor while going through painful surgery is a common action movie trope.

Furthermore, things like cauterizing an open wound with a hot knife is doable with no pain medication, so why isn't it an option to install a CBM with no painkillers but a huge pain and morale penalty at the end?

Lastly, as mentioned, I have always been under the impression that a found CBM is a complete self-surgery kit, and I can't fathom a reason why it wouldn't come with the appropriate anesthetic. Obviously a CBM that was ripped out of a corpse would require special treatment, but I see absolutely no reason why a store-bought kit wouldn't come with the required medicine.

I definitely dislike the fact that CBMs are now reliant on unavoidable RNG. In the past, there was only the "chance of failure" mechanic which I could overcome by skilling up or taking stimulants, and that made perfect sense. Now, no matter how much skill my character has, I not only need to _find_ the rare CBM, but also happen to hopefully one day stumble across the correct type and amount of medicine.

As highlighted by [this reddit post](https://www.reddit.com/r/cataclysmdda/comments/6ndpp9/some_balancing_is_definitely_needed_with_the_new/), this mechanic functions poorly because it _kills_ characters from overdose when they are forced to take a certain amount of the drug.

**Comment by kevingranade** [comment]
Working as intended, this is not a forum, try smf.cataclysmdda.com

**Comment by Happydacat** [comment]
Just because it's working as intended doesn't mean that it's working well.

**Comment by AlecWhite** [comment]
This is a game balance problem. As this increases the needs of hard to find painkillers and specially hard to dose, as an over-dose causes death.

I don't think it is working as intended as that unreasonably **unbalance** all the CBMs regardless of how they were acquired.

Now that we have test it, I'm not the only one that think it is **unbalanced**, and gave plenty of arguments of _why_ it is unbalance, and on _how_ it can be fixed. 
Including more or less what would be the expected behaviour and what is the current behaviour.

And I would like to ask please to hear the reasons and rationale behind having this in its current state, and of why any of my arguments and reasons would be wrong.

**Comment by BaronVonClop** [comment]
I'm not sure how "kills the player due to being forced to take a lethal dose of painkiller" is working as intended. Can you explain why that behavior is intended?

It is far more logical to just hit the player with a huge pain penalty at the end of the surgery, and allow them to dose themselves how they please, whether that be through rest, alcohol, drugs, or yes, painkillers.

**Comment by RedPine91** [comment]
This issue HAS been discussed on the forum, in great detail.  Kevin is equally dismissive there as well.  I don't like being hostile, but being nice and rational clearly didn't work so the only option left is complaining.

**Comment by mdb45424** [comment]
yeah works as intended my bum. Just took 20 codine and still not numb enough to install a cmd. tried morphine and alchol, and finally as a last attempt I tired some asprin thinking I might be off a tiny bit. This update stops you from have cmb you didnt start with.

**Comment by mdb45424** [comment]
ok figured it out it takes a LONG time for the stuff to take effect. way longer than the last in game they seem.   Seems it took  30 min game time for the codine to take effect.

**Comment by Toybasher** [comment]
I agree. Have not played the game since the update yet but I do remember how CMBs worked.

While I understand self-surgery would be very, VERY painful, it shouldn't outright cancel the installation. Maybe give a chance of failure, or cause a fuckton of pain. 

The painkillers need better feedback for when you're numb enough. I'm a former ems student, and I know drugs take time to actually take effect, but it's a literal guessing game of "take pill, wait, attempt installation. Nope. Did I not wait long enough? Did I wait too long? Did I not take enough pills?" etc. 

I'd prefer what other commenters said. New in the box CMBs should come with all you need, but used, preowned ones should require tools.

**Comment by DangerNoodle** [comment]
I must again add my concern here as well. I do not think feedback here was considered in a rational manner.

**Comment by AlecWhite** [comment]
@DangerNoodle 
http://smf.cataclysmdda.com/index.php?topic=14776.0
http://smf.cataclysmdda.com/index.php?topic=14746.0

**Comment by DangerNoodle** [comment]
Seeing this, I do not feel as though Kevin is on the same page as the rest of those posting. In the second thread.

> That's not what the change is about, it's about fleshing out CBM from realism and resource consumption points of view, it was massively over-abstract in both areas.

Kevin neglected the higher priority point this was a response to. This change was incomplete, and it should not have been merged until it was complete. My concerns the feature itself will be resolved almost entirely by the pull requests @Night-Pryanik has been working on as of late.

My concerns about how Kevin has handled this are what I prioritize when I present my objection. The feature-incompleteness has had entirely predictable consequences, and it reflects poorly on both the community and on Kevin.

**Comment by DangerNoodle** [comment]
That said, apologies if my knowledge of how discussion has gone on the forums is a bit lacking. I have been only a lurker there, and have no major incentive to get involved compared to contributing to the project directly.

**Comment by AlecWhite** [comment]
@DangerNoodle There's a subreddit about it too https://www.reddit.com/r/cataclysmdda/comments/6ndpp9/some_balancing_is_definitely_needed_with_the_new/

But is too full of trolls that are just there for the drama, so I don't use it.

**Comment by Akhier** [comment]
I've been looking around and just found this. I will not be giving my opinion on this topic though as I have something more important to go over. @kevingranade , "Issue" does not mean broken, it means people have a problem with it. If issues were only something broken then you should just close issues like #21431 about brick walls not dropping bricks, after all the walls are dropping stones just as intended.

Also, yes this is not the forum. This is an issue thread about something people take issue to in which they can seriously put forth what changes should be made and maybe eventually submit a fix. IE what this issue was doing.

If you just force people to shut up it doesn't make it go away. It just makes people resent you. Want to know a secret? If you didn't close this issue people would have just talked about it. Eventually maybe someone would submit a pull request but you don't have to accept that pr and just give your reason for it not being what you want. Even better, eventually with enough hashing it out they might have come up with a solution you hadn't thought of that solves it better! So yeah, you just made people question your leadership of this project for only negative results. You didn't even properly justify your closing of the issue as your one line reason for closing this issue doesn't hold water.

**Comment by kevingranade** [comment]
My comment did not lay out a rationale, because the issue was a extremely vague, inaccurate, rambling, and rude.  Nearly every assertion in it is incorrect, it insults the developers for no apparent reason by characterizing the change as "lazy", willfully misconstrues the purpose of the change, and makes extremely unhelpful suggestions about resolving the issue.

Some issues are low value, and I'm not going to spend any time on them.

Subsequent discussions elsewhere outlined valid issues, and we have a number of changes in progress to address them.

**Comment by DangerNoodle** [comment]
It is still less than ideal handling. But unfortunately, merging the change in the first place, without the improvements that are now in-progress, was less than ideal to begin with, so following that all reactions would be less than optimal than what could have been done.

For that, I will admit it is understandable that reacting to them in the way others others wish of you is not the ideal action.

But I would hope you understand that reacting to them in that way was not the best choice either. Only one of several choices remaining, after the most efficient courses of action had already been neglected to the point of being too late to do the pull request in the way least likely to disrupt the community.

**Comment by AlecWhite** [comment]
>My comment did not lay out a rationale, because the issue was a extremely vague, inaccurate, rambling, and rude. Nearly every assertion in it is incorrect, it insults the developers for no apparent reason by characterizing the change as "lazy", willfully misconstrues the purpose of the change, and makes extremely unhelpful suggestions about resolving the issue.

I'm sorry if you took "lazy" as an insult, because it wasn't meant as an insult but as a description, and I'm sorry you took it with such an overreaction.

> willfully misconstrues the purpose of the change, 
Now you are implying things I didn't wanted to do. I may have misunderstood the purpose of the change, but there wasn't a lot of information behind the motivation of doing it. Nor here https://github.com/CleverRaven/Cataclysm-DDA/pull/20892 nor here https://github.com/CleverRaven/Cataclysm-DDA/issues/17698

But saying "extremely vague, inaccurate, rambling, and rude" and claiming that I "willfully misconstrues the purpose of the change" is going too far regarding what my intentions were and are. You are painting me like some kind of troll. Which ironically is a rude thing to imply.

>and makes extremely unhelpful suggestions about resolving the issue.
I suggested:
>A salvaged or butchered bionic out of a corpse, should need anaesthetic and tools to install

Which made reference to https://github.com/CleverRaven/Cataclysm-DDA/pull/20892#issuecomment-296871236
>It's abstracted, we don't have local vs general anesthetic, and adding something that acts like local anesthetic is well outside the scope of this PR.

Hence suggesting anesthetic as it seems yourself considered it in the past.

And:
>we need a properly designed and implemented system. Instead of further penalizing all kinds of CBMs regardless of how they were acquired. 

Is very direct and simple to understand as https://github.com/CleverRaven/Cataclysm-DDA/pull/20892 directly increases the difficulty of CBMs.

I really don't see how they are "extremely unhelpful". Please explain it to me.

**Comment by Akhier** [comment]
See? That is the kind of stuff you should put forward when closing the issue. I don't mind you closing the issue but rather your flippant way of doing so. This repository has you as the owner so you have the final say. If people don't like it they can go and make their own version. However it is a community project. You can do whatever you want irrespective of others opinions but you would quickly lose people that way. I enjoy the game and don't want the development to stall out because you can't take people thinking the latest change to the game was lazy. Is it rude to call the people who help develop here lazy? Yes, just about as rude as you are when you flippantly close the issue without a good reason besides you think everything is fine (which since you admit discussion elsewhere has brought up valid issues was completely untrue).

You know the biggest irony? You say some issues are low value and you don't want to spend time on them and yet by closing this issue so flippantly instead of going quietly into the night it has become an issue for you.

**Comment by kevingranade** [comment]
> You know the biggest irony? You say some issues are low value and you don't want to spend time on them and yet by closing this issue so flippantly instead of going quietly into the night it has become an issue for you.

You are quite likely correct that my response made it worse, but the main actors here seem to have been riled up and looking for an argument before I said a thing, so I very much doubt it would have been a non-issue no matter what I did.  Nevertheless, point taken, I should be mindful to avoid posting if I'm rushed.

@DangerNoodle, @AlecWhite get a clue, I'm willing to discuss this with roughly anyone but the two of you, but both of you have seriously burned some bridges here.

**Comment by AlecWhite** [comment]
You know what? Forget it.

Nothing of what I said was said with malice or intent to hurt as it has been insinuated, implied and stated. I tried to be as constructive and explain myself as best as I could. I apologize if anyone got offended or if I looked pushy by repeating my self or giving too many explanations. I could even have PR local anaesthetics if I ever had a clear answer. 
I just wanted to help and contribute.
So gonna play in @Coolthulhu 's patched version or savescum as it was suggested in various places.

And I'm going to drop this topic as it seems that everything I say, may and will be used against me and that it's clear that Kevin is taking all this way too personal, as if all this was a conspiracy against his person. 

You win Kevin. Do whatever you want with painkillers and CBMs, I'm going to work on other stuff.

**Comment by DangerNoodle** [comment]
> @DangerNoodle, @AlecWhite get a clue, I'm willing to discuss this with roughly anyone but the two of you, but both of you have seriously burned some bridges here.

My apologies. I have attempted to be polite in my presenting these concerns. None of this has ever been intended as an insult. My first and foremost concern has been the project.

Like I have already stated, my concerns regarding the feature itself are already being addressed.

**Comment by elricsfate** [comment]
@kevingranade 

Can this be reopened and properly addressed?

**Comment by kevingranade** [comment]
There have been a number of changes to CBM installation since this, so if you want to bring the subject up again, please do so in a new issue.

AFAICT literally nothing about the original issue is valid any longer, the one valid point about aesthetics not providing feedback has been addressed.
