### ISSUE TITLE
Can't place funnel on keg (exp 0.C-6488)

### ISSUE THREAD

**Issue by busterbogheart** [CleverRaven/Cataclysm-DDA#21435]
### Expected Behavior
Funnel should be applied to keg just like other containers

### Actual behavior
"You can't place a funnel there."

### Steps to reproduce the behavior
Build keg, apply funnel to space

**Comment by busterbogheart** [comment]
Also can't deconstruct?

**Comment by Coolthulhu** [comment]
You mean constructed keg or item keg?

**Comment by busterbogheart** [comment]
Constructed keg from build menu, sorry.  Crafted keg works as expected with funnel.

**Comment by rluddy** [comment]
There's a lot of special handling for constructed kegs (and standing tanks, which are basically the same thing with a bigger capacity). I've been struggling with their funky UI and weird little bugs like this myself recently, but due to ingredients and skill requirements constructed kegs are a handy early-game base container.

Since the time they first went in, fabrication/construction has been merged and fluid handling in general has gotten much better. I'm not sure what they still add to the game any more versus adding a couple of new (very heavy) autolearned container recipes with the same ingredients, crafting time, and volume.

Someone more familiar with the current state of the game could make a better call about it, but it seems like a clean solution.

**Comment by Treah** [comment]
I would almost say this is working as intended. The construction of these implies that its part of a building which to my knowledge you cannot construct a funnel like you can on a car. The free standing funnel you make is literally putting a funnel on the top of the keg. Its a bit hard to explain in IRL terms but from a game mechanics view it makes sense. Your trying to place a trap into a solid constructed object so its invalid.

**Comment by logistictangent** [comment]
Sorry in advance for the drift but it has been nagging at me while i was
tracking this thread.

If I am completely mistaken please let me know.

Have you ever looked at the top of a beer keg*? Last few I have seen all
have a air/fluid tight seal in the neck. I suppose that if you had enough
motivation you could remove it but at a guess it would be easier to cut the
neck off the keg. Given that I made several assumptions about the kegs in
game the foremost of which is that, it is like any other keg I have
interacted with under that name, I would assume that in game it would be
"impossible" to refill a keg using a traditional funnel. If anyone would
like I can talk to a professional brewer I know and find out all about them
IRL. (Any specific information you need please ask for otherwise I would
just ask about the funnel thing / normal filling process.)

**places thread firmly back on track**

*The kegs I am referencing are American "standard" full kegs made to hold
beer, or I suppose that they could hold other fluids but the ones I have
interacted with hold beer.

P.s. sorry if I present a bit offensively, I was injured at work today and
painkillers don't like my system (I get a bit loopy, among other things).

On Jul 31, 2017 6:29 PM, "Treah Blade" <notifications@github.com> wrote:

I would almost say this is working as intended. The construction of these
implies that its part of a building which to my knowledge you cannot
construct a funnel like you can on a car. The free standing funnel you make
is literally putting a funnel on the top of the keg. Its a bit hard to
explain in IRL terms but from a game mechanics view it makes sense. Your
trying to place a trap into a solid constructed object so its invalid.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/CleverRaven/Cataclysm-DDA/issues/21435#issuecomment-319214693>,
or mute the thread

**Comment by Night-Pryanik** [comment]
That's not a bug, but a limitation of current keg-like furniture.
