### ISSUE TITLE
Long-term activity infrastructure.

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#2151]
When some ongoing activity is happening, for example a stick of dynamite with a burning fuse, or a switched-on flashlight draining its batteries, the code currently scans over all "active" items on the current map and updates them every turn.  This has a problem in that when you move far enough away from the item (or potentially terrain/furniture/trap/whatever), it is removed from the active list and is no longer updated.  This leads to weirdness like fires that burn forever and flashlights that shine forever, as long as the player isn't nearby.

To handle this more cleanly, I propose the following system.
On-map items are fine as they are, though there is some optimization that could be done there.
When a submap containing an active entity is unloaded (due to the player leaving the vicinity) the entity gets a timestamp indicating the last time it was updated.
When a submap containing an active entity is loaded (due to the player entering the vicinity), this timestamp is consulted, and the results of the passed time are applied to the entity immediately.  So batteries discharge, food decays, plants grow, etc.  For items influenced by the weather, (temperature, humidity, light levels, etc), the log of weather events would need to be consulted to determine rates of change over the time period.
This may or may not work for things that spread, such as fire or smoke.  The last I spoke to macrosblacd, he was looking into a specific system for handling the spread of fire off-screen.
##

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
