### ISSUE TITLE
Items made of bone, chitin, paper and wood are marked as non-repairable in the examine menu, though they actually can be repaired

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#21573]
![123](https://user-images.githubusercontent.com/11132525/29036136-dea1e23c-7ba6-11e7-9352-0fda965caac9.PNG)
Bokken as an example.

**Comment by ampnaman** [comment]
To note, bone and wood items are still repairable with resinous cord despite the tag. Ranged weapons made with these materials (bows/crossbows) can't be accurized however, even with a firearm/gunsmith repair kit.

**Comment by DangerNoodle** [comment]
Ranged behavior seems to be due to a flag that enables repair of them without gunsmith repair kits, with inability to reinforce/accurize as an unusual tradeoff.

The reason these materials are not shown as repairable is because the function that lists valid tools does not take into account items that use the hardcoded `MISC_REPAIR` use action.
