### ISSUE TITLE
Allow sorting in recipe menu

### ISSUE THREAD

**Issue by angoddu** [CleverRaven/Cataclysm-DDA#21644]
I'm honestly not sure how difficult this would be but would it be possible to allow for sorting in the recipe dialog? instead of sorting by difficulty could we have options to sort by name and maybe other things. It becomes rather difficult to find the recipe that I am looking for in the menu without searching by name.

**Comment by Leland** [comment]
> instead of sorting by difficulty could we have options to sort by name

Agreed and in fact, I'd propose that alphabetical be the default.

**Comment by BevapDin** [comment]
I like the current sorting. It lets you find the important (and newly available) recipes that you want to do to improve your skills.

If you want to find a specific recipe, why go through the list at all? There is a search function exactly for that purpose.

**Comment by angoddu** [comment]
While the search is useful for finding specific recipes, it makes it hard to find items when just scanning the list. And I'm not suggesting to remove the difficulty sorting, I'm just saying to allow for alphabetic sorting as well.

**Comment by Leland** [comment]
> I like the current sorting. It lets you find the important (and newly available) recipes that you want to do to improve your skills.

@BevapDin an approach I think you'd agree with is to make things as low friction as possible for new users, and then provide means of customization for power users such as yourself. E.g. pressing <kbd>S</kbd> to switch to difficulty sort.

Alphabetical is generally the way to go for menus for new users as that's the convention employed by menus across OSs and is thus immediately intuited. Sorting by difficulty only becomes relevant when one wants to start grinding to increase their skill level.

> If you want to find a specific recipe, why go through the list at all? There is a search function exactly for that purpose.

This is a UI issue rather an UX one, but the search key isn't actually marked on the window. 

Additionally, I didn't even know that the lists were sorted by difficulty at all until this issue. It's not marked anywhere. Turns out that's not even the full story – the recipes are sorted first by difficulty, then by reverse order of subcategory (e.g first Other, then Vehicle, etc), and then finally alphabetically within each subcategory.

**Comment by angoddu** [comment]
At first I thought the menu was simply unsorted until I statred trying to grind skills. That's why I figured we should allow the user to sort how they want

**Comment by Night-Pryanik** [comment]
Closing as per lack of discussion.
