### ISSUE TITLE
Cannot have a reinforced door with peephole

### ISSUE THREAD

**Issue by angoddu** [CleverRaven/Cataclysm-DDA#21641]
### Expected Behavior
Able to install a peephole on a reinforced door

### Actual behavior
If you reinforce a door with a peephole then you lose the peephole.
If you try to add a peephole to a reinforced door then it says "you cannot build there"

### Steps to reproduce the behavior
Go to any unlocked wooden door
Install peephole in door
Reinforce door

OR

Go to any unlocked wooden door
Reinforce door
Install peephole

**Comment by Night-Pryanik** [comment]
To successfully resolve this issue we must get rid of defining numerous variations of doors (ordinary, boarded, with peephole, locked etc) as a separate types of terrain and make terrains accept construction elements and features as a flags. So that we don't need to add another terrain type for another combination (reinforced wooden door with a peephole), but consistently add flag to some base terrain type.
In our example, one base terrain type - wooden door - can become reinforced wooden door or wooden door with a peephole simply by adding flags like either REINFORCED or PEEPHOLE (in any order!). Then we just add second flag and get the resulting terrain.
We need to define these flags somewhere in code prior to that, or course, and define on what type of terrain they can be used.
