### ISSUE TITLE
Possible issues with "ILLITERATE" trait

### ISSUE THREAD

**Issue by ZhilkinSerg** [CleverRaven/Cataclysm-DDA#21655]
I believe that characters with `ILLITERATE` trait should not be able to tell time using various watches and should not be able to use maps.

Also book names are known for the character who is unable to read.

**Comment by Coolthulhu** [comment]
The whole illiterate trait doesn't really make much sense when you think about it.
Most common form of illiteracy isn't not being able to read letters at all, but rather having reading comprehension so low that one can't really absorb information that isn't explained by someone.

The in-game illiteracy functions as if the whole text was written in Cyrillic or Katakana but still using English words, or as if the character had brain damage preventing them from associating glyphs to meaning.
A genuinely illiterate character would be incapable of comprehending the information even with someone to read the text out loud.
https://en.wikipedia.org/wiki/Functional_illiteracy

The in-game trait works less as if the character was illiterate, but more as if they were a foreigner who barely understands English, but can still be explained things to if the speaker has the time to enumerate synonyms for a given word, rephrase a phrasal verb, explain cultural implications and so on.

**Comment by ituluwituluwzev** [comment]
I think the in-game illiteracy is not a pathological condition, but is lack of education, and it should be.

**Comment by ZhilkinSerg** [comment]
I always thought `ILLITERATE` character is the one who grew up in the jungle with the wolves and didn't attend kindergarden/school.

**Comment by Maykeye** [comment]
I don't care about books...

> I believe that characters with ILLITERATE trait should not be able to tell time using various watches and should not be able to use maps.

but I'm very strongly against this

1) You don't need to be able to read to tell that "a snowman" `8:00` corresponds to the time when the sun goes up or goes down. You don't need to be able to read to tell that "a pillar and a swan" (`12:00`) corresponds to the time when sun is completely up or down completely. You don't need to be able to read to notice the pattern of 0-1->2->3...9 that goes again and again.  

All you need to do is not to be blind.

2) Some watches don't even have [digits](https://cdn.shopify.com/s/files/1/0377/2037/products/WhiteTanLeather.Front_1024x1024.jpg?v=1501528324) at all.

Same with maps. Maps are drawn, not written, often using very descriptive symbols as "fork and knife" or "red cross". 

> I always thought ILLITERATE character is the one who grew up in the jungle with the wolves and didn't attend kindergarden/school to learn reading.

It's available in every scenario, including school.  If character grew up in the jungle, then he also shouldn't be able to know how to use or make 99% of items(including how to boil water) or how to talk.

**Comment by kevingranade** [comment]
First, its working as intended that illiterate characters can tell time and
read maps.  There is some potential for limiting what they get from maps,
but I don't recall a sensible adjustment that has been proposed, so that's
stalled at best.

Second, this kind of reasoning, "I think an illiterate character was raised
by wolves, therefore they also dont know how to do x" is erroneus.  The
illiterate trait indicates the character can't read, nothing else.

**Comment by Theundyingcode** [comment]
> There is some potential for limiting what they get from maps,
but I don't recall a sensible adjustment that has been proposed, so that's
stalled at best.

The first thing that came to mind when I read this was they should know where the roads and buildings are but not what type of building they are since they can't read the legend.  This would entail creating a generic building over-map symbol that replace the unexplored #'s instead of reveling the buildings (i.e. make # lighter gray)

The more code intensive but realistic way of doing it would be to have them know "these are all building type A, these are B etc." and mark their map as such.  Then, when they come across say a bank, they can go "oh, building Type G is a bank" and change all of the G's on their map to be banks.

Other thoughts:

- Restaurant guides usually have a picture of the store front and food but not necessarily a map. even then, its only of the surrounding couple blocks.  Make these unusable or only reveal stuff in nearby/ visited towns.

- Town names have been recently added but illiterate characters should only know the name of the starting town (they where their pre-cata) and, at most a couple others near by; unless they can get an NPC to tell them.

- Since it's just they can't read, shouldn't they be able to learn form children's books and NPCs? It should still take a really long time though.  Maybe like 400 hours of study give you INT 1 when it comes to book reading and another 200 for every point after that up until player's max base INT.  Times could then be halved with an NPC helping you.  Good memory could give a bonus as well.

- Do/should they know how much is on a cash-card? (I never played literate outside of challenge and murder only characters) they should still be able to use a vending machine though since it's just pictures. (actually why can anyone see how much money is on a cash card?)

- Anything meant to provide basic emergency instructions (First Aid, CPR, in flight safety card etc.) are almost always specifically designed to be understandable by anyone who sees them.   To a lesser extent, this is also true for "some assembly required" products.  Tailoring and artsy crafty things are also usually very picture/diagram heavy. There should be at least some materials that a illiterate "read" to learn (some) skill levels and recipes.

**Comment by l29ah** [comment]
How do i alpha mutagen while being illiterate?

**Comment by kevingranade** [comment]
Stalled and most likely invalid.

**Comment by l29ah** [comment]
Do i get it right that mechanics skill is off limits for the illiterate? Any vehicle modification requires mechanics 1 at least (except messing with batteries, but it doesn't count for the purpose of skill improvement), and there's no recipe that requires mechanics 0.
