### ISSUE TITLE
Freeze with RAM-Overflow

### ISSUE THREAD

**Issue by Wroooom** [CleverRaven/Cataclysm-DDA#21706]
### Actual behavior
Savegame freezes after walking a bit
### Steps to reproduce the behavior
Load save, walk a few steps, CDDA freezes.
In the Task-Manager you can see CDDA slowly eating more and more RAM (the longest time  I waited before killing it, it  ate about 4 Gig)
SaveGame:
[Hotevilla.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/1248949/Hotevilla.zip)
DebugLog:
[debug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/1249029/debug.zip)

**Comment by Wroooom** [comment]
I don´t know why, but it changed behaviour:
When walking there is an endless (keeping spacebar pressed) add_zombie error, when I ignore it, I get the behaviour described above.

When crafting a blindfold, it freezes at once like describes above.

**Comment by DanmakuDan** [comment]
There are a large amount of monsters underground at your location, and an irradiated wanderer is giving itself infinite move points from spamming its special lunge attack.

Technically, it is an issue since it is unable to spend its extra move points for some reason. The move points tick down 1 at a time due to failure to move/act (its ability to stumble randomly causes the decrement of 1 point versus 100), and the lunge gives a 200 point bonus. The lunge special cooldown timer is decremented for every attempt the game makes at moving/bashing/pushing with the monster, so the special will be off cooldown during the failed move attempts. It looks like the special attack cooldown timer needs to be restricted by a different method to prevent infinite moves in this specific case.

**Comment by Wroooom** [comment]
Thank you.
As I don't know anything about getting the info you talk about, there´s only one thing I think, I can contribute:
When exploring those sewers underground there seemed to be irradiated wanderers only, dozens of them (I believe, I killed about 30 or more on my short journey down there).

**Comment by Leland** [comment]
@Wroooom can you download the latest experimental version and test your savefile on it?

This may have been fixed by #21734

**Comment by kevingranade** [comment]
Fix landed, please re-open if you run across this again.
