### ISSUE TITLE
Opening safe at low skills power level mechanics.

### ISSUE THREAD

**Issue by tinukedaya** [CleverRaven/Cataclysm-DDA#21814]
Game version:
0.C-6743
Mods active:
tested with just default pre-selected

### Expected behavior
new character with 0 skills in everything, should not be able to open safe.

### Actual behavior
i started new game. Saw a veterinary clinic close to my position, nicely isolated just with one additional house. went there, found stethoscope, saw a safe, tried to crack it. 4 hours later ingame time, my character has 2,5 level in mechanics and items from opened safe.

### Steps to reproduce the behavior
wish for stethoscope, map edit an safe, try to open it.

**Comment by Night-Pryanik** [comment]
The same for lockpicking locked doors. I'd suggest removing mechanics practice through these actions.

**Comment by Theundyingcode** [comment]
As someone who has a lock pick set (yes it is legal there is even a hobbyist group called toool) It is defiantly something you get better at with practice.

I agree that being able to power level skills through key-less/combo-less entries can be a bit game braking and that safes are things that should not be openable at the beginning of the game.  However, there should be some recognition of practice.

My suggestion- hidden lock breaking skill.  Mechanics and dexterity would still influence success chance by providing bonuses/penalties to it and all the exp from picking and cracking would go to raising that instead.  This also would pave the way to creating different quality locks.  Honestly all of this is pretty unrealistic right now.  I can open a filing cabinet or MY back door without any difficulty but there is no way in heck i'll be able to open the locks in a prison or bank (i'm sure others could) and building a car isn't going to change that.

**Comment by Night-Pryanik** [comment]
We can add some minimum mechanics level requirement - say, level 2 - for player to practice mechanics by picking locks. I'm pretty sure that a total noob in lockpicking, having no knowledge of how locks are constructed and operated (mechanics levels 0-1) couldn't open the lock, ever, no matter how hard he tried, and therefore couldn't gain anything from trying to pick the lock.

**Comment by kevingranade** [comment]
For a short-term fix the threshold in mechanics seems reasonable.

Longer term I'm not seeing a problem with a specific lockpicking skill. It really is very little like any other activity, so cross-training between mechanics and lockpicking is quite a stretch. They do overlap in the areas of general tool use and understanding mechanisms, which is why they're related now, but yes, it's a stretch.

The problem with a totally isolated lockpicking skill is the skill curve.
* First, how do you start at lvl0? Us there an action you can attempt to train it, or does it require finding a skill book?
* Then, how do you progress through the levels? No single action should level you by more than a few levels, so there need to be ~10 actions at different difficulties to allow you to level.
* Finally, what actions are covered?  Picking sure, but how about:
** forcing doors with a crowbar?
** forcing windows?
** safecracking?
** torching a safe?
** drilling a safe?
** blasting a safe?
** hotwiring a car?

These are thematically related, but practicing one has very little to do with practicing with the others.

**Comment by LordZanos** [comment]
> Longer term I'm not seeing a problem with a specific lockpicking skill.

It's extremely niche, and construction was removed in the past for doing very little. Mechanics and lockpicking might not have a massive amount of overlap but I think that they're close enough and that lockpicking doesn't deserve an entire skill category on it's own. 

Unless there's a massive expansion to breaking and entering in the future I don't really see a need for an entire skill for it.

**Comment by John-Candlebury** [comment]
I'all be fine with lock picking using mechanics, but not training it past level 1

**Comment by Night-Pryanik** [comment]
> I'all be fine with lock picking using mechanics, but not training it past level 1

You mean allow lockpicking to train mechanics from level 0?

**Comment by John-Candlebury** [comment]
Yess allow it to train from 0 to 1.

You cant do any real mechanics at level 1 so I dont think it would really be a problem

**Comment by Theundyingcode** [comment]
I second the threshold idea short term.

I'm going to reply about the skill a little out of order:

> Then, how do you progress through the levels? No single action should level you by more than a few levels, so there need to be ~10 actions at different difficulties to allow you to level.

This is why I suggested a hidden stat instead of an actual skill.  Like a marital artist who only practices straight jabs, lock-picking is lock picking it doesn't really have the same transfer-ability as other skills do.  A car mechanic stripping a tank or a vet. acting as a doc. isn't unreasonable as they're using their same skill, the straight puncher may have the fist of god but that dose not mean he can kick or block.

The biggest problem with implementing it as a skill  is the quality of locks and type of picking tools makes a massive difference.  I have opened a high security tumbler lock once after fidgeting with it for a few hours while watching TV but if you asked me if I could pick it my answer would be no.  On the other hand if you gave me a pick gun (which are controlled) It might take a few minutes but I would be able to get it open.  

The only thing you can do is get faster and better at it.  For safes and the more rare and complex high-security locks the dissembling and reassembling them can help a lot (If you gave a bank's lock mechanism to a professional thief they would have it in pieces in under a minute). Other wise it's just practice.  A hidden stat could simply make picking/ cracking take less time with higher success rates the more you do it.

> First, how do you start at lvl0? Us there an action you can attempt to train it, 

IRL "knife entry" (open door by ignoring lock and moving the spring loaded latch) is really-really easy. I would use my ID card to open classroom doors in middle school since they auto locked and people are.... Push button locks are even easier, you just jam something in the bolt and they open.  As spring loaded and push button are the cheapest locks they are used on most internal doors (office, bathroom ect.) and unknowledgeable home owner's doors and, could both be level zero.  

> or does it require finding a skill book?

As for actually picking locks, you kneed like a note-card rather than a book.  The back of a lock's packaging in the store would probably be enough assuming you had access to a TV pre-cataclysm:

Almost all the locks an average person comes across in their day to day are some form of tumbler.  The have a bolt (The part that turns) and something preventing the bolt from turning without a key (usually pins on doors and padlocks and wafers on cabinets).  The reason why you can pick a lock is because there are imperfections in manufacturing and the pins don't perfectly line up.  So, if you apply a torque to the bolt the force will rest against one pin.  If you push that pin (pick it) into the correct spot, the bolt will move over so it's pushing against the next pin and the now set pin can't move back because the bolt is now in the way.  So, set the next pin and then the next and keep going until it's unlocked. 

> Finally, what actions are covered? Picking sure, but how about:

- forcing doors with a crowbar? -your just using a lever to apply enough force the door breaks
- forcing windows? - Same as with doors
- safecracking? - Yes. Picking is all about feeling the lock move.  A maintained safe's mechanism's movement will be to smooth for you too feel it click into place so you listen instead.  With some practice one could probably pick a lock with a stethoscope and open a cheap old safe by feel. 
- torching a safe? - No. This is just using a blowtorch to cut it open. Use whatever cutting metal bars dose.
- drilling a safe? - Yes. the reason why people drill safes is so they can stick a camera into the locking mechanism. because the mechanism has been soundproofed. (speaker+duct tape)
- blasting a safe? - NO!!!! maybe high level cooking or launchers but not lock picking
- hotwiring a car? - No. This is bypassing the key and applying power straight to the ignition. This should stay as mechanics.

**Comment by Coolthulhu** [comment]
> This is why I suggested a hidden stat instead of an actual skill.

Making something a hidden stat/skill creates problems, most of which are worse than the individually worse than the problem at hand.
Hidden elements in the game are notoriously imbalanced to the point where they usually max out or never reach any sensible values. For example, for a long time critical hit rate was reaching 100% by 3 melee skill. The exception is when someone competent crunches math (makes charts) for it instead of just saying "oh it kinda works at lvl 5".
So creating some hidden skill for it is out of question - if it's a skill, it must be one the player can see.

Those are fine:
* Adding a chargen trait that represents practice in picking locks. Give this trait for free to burglar style professions. Don't allow others to pick it because it's such a minuscule detail that it's basically RP.
* Merging it with trapping to form a "security" skill
* Basing it on stats (dexterity obviously, but also perception)
* Basing it on tools (this one is currently barely used, with lockpicks hammered from scrap with no skill being comparable to actual tools)
* Basing it on light quality (currently ignored)
* Turning it into a long action and increasing the time spent per attempt

Those are not fine:
* Hidden "locks picked" variable that does what skills do except worse and more awkwardly
* Including encumbrance as anything but time penalty. Forcing the player to manually remove the gloves to increase picking chances is bad UI design. Time penalty is fine, as long as it is comparable to cost of removing and putting on gloves or lower.
* Making lockpicking so hard that it doesn't matter but still keeping it in the game

**Comment by AncientSion** [comment]
time based seems to be the best base for it, where as time decreases with higher skill level (if a skill) or time decrease with increased perception and dex base skills.
At any rate, time need should be harshly increased if no light source is active.

I find it rather immersion breaking to be able to lookpick almost any GUN STORE even at low mechanics level (say, 2).

**Comment by Theundyingcode** [comment]
> I find it rather immersion breaking to be able to lookpick almost any GUN STORE even at low mechanics level (say, 2).

Gun stores in the USA are not exactly epitomes of great security but I agree with the sentiment. I think if you REALLY want to spend all day trying you should be able to get in but more realistic alternatives should be incentivized (car+brick=open door)

> At any rate, time need should be harshly increased if no light source is active.

Lockpicking is completely tactile.  As long as you can find the lock and your tool(s), blindfolds or spotlights make no difference IRL.

> Merging it with trapping to form a "security" skill

I like this idea.  I'd want a different name though since a bunch of the trapping now is more hunting  than oriented...

How about something like:
Stats (dex primaily) reduce time needed for attempt while the skill level increases the success chance. have it scale like:
you need lv.1 to pick a lock representing gaining the knowledge to understand what they were actually doing in those movies...
Low Security locks (houses/offices) 20% at lv.1 and cap at lv. 4-5 with 90%
Medium Security (Electronic/Gun Stores) 1% at lv.1 (bad lock?) and cap at lv.7 with 80%
High Security (Labs, Military, Prison) 0.01% at lv.1 (get lucky) and 75% at lv.10
And have using good tools (not makeshift) give like 2% success and 10% speed bonuses
Maybe speed bonus for skill levels above cap?

> Adding a chargen trait that represents practice in picking locks. Give this trait for free to burglar style professions. 

Have them start with skill lv.1 and a trait that gives them say a 5% bonus to both speed and success chance.  Then convict will have a 5% success chance on the front door of the prison in that scenario which would translate to expecting it to take 15-30 min in game time to open the HIGH SECURITY prison door.

**Comment by Night-Pryanik** [comment]
While I like the idea of adding some new meaning to heavily underpowered skill like trapping, I think mechanics fits better here.
What is the mechanics, in a nutshell? Let's say it is knowledge of how various mechanisms are operated. Locks are mechanisms, so lockpicking is essentially applied mechanics.

**Comment by tinukedaya** [comment]
The treshold sounds reasonable for quickfix. 

As for longterm I had an idea which might be a little too complex to implement though.
As I agree that mechanics is quite suitable for lockpicking, it's also quite specialized part of it, with diferent skill or stats influencing it... So what about introducing a secondary skills set, that is based on curent ones? It's almost like the idea of having hidden lockpick skill. But it could be exposed and explained. 

Lockpicking: 40% mechanics, 30% dexterity, 15% trapping, 15%, perception. 
and then when performing lockpicking it will practice the skills at the above rate.

**Comment by kevingranade** [comment]
> construction was removed in the past for doing very little.

It was removed (#20368 for discussion) because it was a giant umbrella skill, whose actions were better handled by other skills.  Fewer skills aren't automatically better. In this case it would be a very specialized skill, but there's nothing wrong with that, skills don't need to have the same degree of usefulness.

> This is why I suggested a hidden stat instead of an actual skill.

That doesn't adress any of the issues around what is or isn't included, and how progression works, if it's influenced by experience, the only way we have of representing that is as a skill.

> The only thing you can do is get faster and better at it. 

I don't think this is acurate, especially if we have more differentiation between lock qualities.  There are kinds of locks that only a handful of people in the world know how to pick, and a fairly wide range of differentiation between various kinds of locks as far as how pickable they are and how much they slow people down.  It would definitely be reasonable IMO to have a large number of lock types that are only pickable if you have the requisite skill level, and perhaps also the requisite set of tools.

> IRL "knife entry" (open door by ignoring lock and moving the spring loaded latch) is really-really easy. 
> Push button locks are even easier,

Both good points.  Wether we split out lockpicking seperately or leave it with mechanics, we can add these actions to provide a lvl 0 action as an on ramp to the skill.

* Adding a chargen trait that represents practice in picking locks.
Not ok, basic lockpicking is an easly learnable skill.
* Merging it with trapping to form a "security" skill
Also not ok, traps+lockpicking is enven more tenuous than mechanics+lockpicking.
* Basing it on light quality (currently ignored)
This is intentional, most lockpicking is performed by either touch or sound, so impaired sight doesn't matter.

**Comment by vache** [comment]
I like the idea of having more "soft" skills, that aren't necessarily part of the skill system, and act more like traits or perks.  So if you found a set of lockpicks, you could play with them for a while, and it would use mechanics skill to make a roll every time, once you roll high enough or make a certain number of rolls, you gain a "lockpicking" perk that grants a fairly wide boost to your lockpicking ability.  Alternately, you could find a lockpicking book that gives the perk automatically.  I think something like that would be a good balance between adding an extra skill and having hidden properties.

**Comment by Night-Pryanik** [comment]
Should be closed after #22278, or left for history for all the discussion?

**Comment by Night-Pryanik** [comment]
No reply, closing.
