### ISSUE TITLE
On `overmap_special` and `overmap_terrain`

### ISSUE THREAD

**Issue by ZhilkinSerg** [CleverRaven/Cataclysm-DDA#21815]
As far as I understand, `overmap_special` consists of one or more `overmap_terrain`s which are put to overmap altogether.

Is `overmap_special` tracked somehow after overmap was generated or is it just split to its `overmap_terrain`s?

Is `overmap_special` used for easier mapgen to put several overmap terrains together or are there any other uses?

**Comment by Coolthulhu** [comment]
Terrain refers to a single tile on the overmap. It can be a special, it can be just a bland tile. Everything seen on overmap must have a terrain associated with it.

Special is a single structure used only for the purposes of aggregating a set of terrains. It is not saved in any way, only used at overmap gen.
It could be useful to save special data to the overmap, so that mapgen (not overmapgen) can understand connections and neighborhood, but it is not done.

**Comment by ZhilkinSerg** [comment]
Thanks! So for now there is no difference: either we put several `overmap_terrain` tiles nearby each other sequentially or put them altogether with single `overmap special` - the result is the same.

**Comment by kevingranade** [comment]
Yes, overmap specials effectively cease to exist after overmap generation completes.
