### ISSUE TITLE
House generation bug, kitchen door behind Oven regulary

### ISSUE THREAD

**Issue by AncientSion** [CleverRaven/Cataclysm-DDA#21915]
Game version: experimental, about 2 weeks old

### Expected behavior
Kitchen are connected to 2 or 3 romms usually. As far as i can tell, for a large amount of houses generated, a door is placed in the wall right behind the kitchen cell.

https://i.imgur.com/A9RMza6.png
https://i.imgur.com/mP4UmW8.png
https://i.imgur.com/4weFcsl.png

These are in the fact the first 3 houses i went into, its no cherry picking. As far as i can tell, it has been an issue for a longer time for sure.

### Actual behavior
Place doors not adjacent or next to kitchen units.

### Steps to reproduce the behavior
Load game, run into some houses. Should be common to find the problem i mentioned above.

**Comment by ituluwituluwzev** [comment]
The furnitures presumably barricade the door.

**Comment by AncientSion** [comment]
That seems unlikely, the furniture that is presumly barricading the door is the Oven or Refrigator. It wasnt moved manually. I find it very likely it is a which doesnt account for the Placement of 3/4 tile kitchen unit.

**Comment by CoroNaut** [comment]
This is a very long-standing bug, its tough to fix, just thinking of how to restrict the mapgen math for the house makes my head hurt.

**Comment by ZhilkinSerg** [comment]
> This is a very long-standing bug, its tough to fix, just thinking of how to restrict the mapgen math for the house makes my head hurt.

Put doors and windows first, furniture second.
Do not put furniture near indoor doors.

**Comment by Coolthulhu** [comment]
Procedurally generated houses are an ancient function in need of a rewrite.
Having someone actually study basics of architecture/"house design" (complete wiki-tier basics, I'm not talking about majoring in it) and chalk up a basic guideline would be useful.

One seemingly minor but very important detail: basement stairs. Care must be taken that they align with the stairs in the basement.

**Comment by John-Candlebury** [comment]
>Procedurally generated houses are an ancient function in need of a rewrite.
Having someone actually study basics of architecture/"house design" (complete wiki-tier basics, I'm not talking about majoring in it) and chalk up a basic guideline would be useful.

Architecture student here,  this would be a basic guideline for more accurate house design. Its a bit long, but I think most of this should be obvious once you think about it.

**Connections between rooms.**
The most important thing is to keep the kitchen, dinning and living room together as adjacent rooms (there's no need to place walls between them).

Ideally the rooms are connected like this:  entrance>living room>dining room >kitchen. So you dont cross the living room when walking from the kitchen to the dining room. You can also make the entrance lead to the dining room, but remember not to put the living room between dining and kitchen.

The exit to  the garden is near the  living room or dining room.

Now  for the rest of the rooms.  Connected to the living room, entrance hall or in some cases dinning room; is a another hall that leads to bathrooms and bedrooms. An example of such hall can be found in House 4, another way to make it is in House 15. You can also have these rooms connected directly to the living room. 

**Main Entrance**
The main entrance should lead an entrance hall or to the living room. An entrance hall can be seen on House 10, its the 3x3 group of tiles directly after the entrance. 

**Windows**
Try to have every room that is not storage have at least a window. Also try to make it so that the room seems realistically lit up when the climate is sunny, use your own house/apartment/whatever as comparison. 

**Service door and Garage**

Its not necessary, but many houses have a service door in addition to the main door. It usually connects  to the kitchen, a laudry room or a hall near the kitchen/laundry room.

If your house has a garage, the service door is often in it.

**Basement**
The stairs to the basement  often go under the stairs to the second floor. Which is to say in a small closed off room somewhere close to the living room/dinning room or entrance hall. You can also place them close to the kitchen/laundry room.


**Other tips**
-If your house has a study room, its often connected to the entrance hall or living room. The same is true for any  other rooms you imagine would look nice and would like to show to guests.
-If your house has a laundry room, if often goes behind the kitchen. Or near the master bedroom bathroom.
-Try to have at least one bathroom relatively close to the living room or entrance hall, you know for guests.
>Try not to have furniture in the way, make it so that the player can easily move through the house, without needing to vault over the sofa.

--
At a glance house 4, 7, 10, 13, 15 are decently realistic and cover this requirements. If you want to look up houses and floor plans for inspiration, the site Archdaily has a bunch of them made by renowned architects. Just select a house and you can find the floor plans in the Valery at the bottom. Link here:

http://www.archdaily.com/search/projects/categories/houses?ad_name=flyout&ad_medium=categories

In fact, the site has floor plans for about any civilian structure in existence.
