### ISSUE TITLE
Special brownie is lacking information everywhere other than [E]at screen

### ISSUE THREAD

**Issue by lonelychaser** [CleverRaven/Cataclysm-DDA#21954]
Game version: 0.C-23389-gd993d6c

Operating system: WIndows 10

Tiles or curses: Tiles

### Expected behavior
Special brownie should display its food/drug information when player looks at it in every occasion.
### Actual behavior
Special brownie only shows its food information when player tries to [E]at it.
### Steps to reproduce the behavior
- craft/wish a special brownie
- open inventory to check it, examine it on the ground or find it in wishing screen and it doesn't show information of special brownie as a food.

**Comment by TeMPOraL** [comment]
Same happens for e.g. caffeinated chewing gum. It seems it's because it's of `comestible_type` `MED`, not e.g. `"FOOD"`. See `item::is_food()`:

```c++
bool item::is_food() const
{
    return is_comestible() && ( type->comestible->comesttype == "FOOD" ||
                                type->comestible->comesttype == "DRINK" );
}
```

The question is if this should even be fixed, and if so, whether the fix should apply only to this case, or in general. If the decision is to fix it, then for just the brownie, it might be worth it to simply change it's `comestible_type` to `"FOOD"`. I don't feel showing nutrition/quench for drugs in general is a good idea.

**Comment by kevingranade** [comment]
Agreed, I think when it was created you could only apply the "special" effects with a MED item, but I think it doesn't matter any longer which one it is, so the simplest fix is to make both gum and brownies a FOOD.

Evidence:
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/items/comestibles.json#L127
energy drink triggers a use_action for the caffeine effect.
