### ISSUE TITLE
Cant safely aim at empty terrain

### ISSUE THREAD

**Issue by John-Candlebury** [CleverRaven/Cataclysm-DDA#21967]
Because you need to steady your aim to shoot accurately, and you cant steady your aim while aiming at nothing, all shots made with intent of hitting a piece of furniture or terrain are basically random unaimed shots.

Noticed this after almost killing myself with a fusion gun while trying to blow up some reinforced glass.

**Comment by CoroNaut** [comment]
I very much want this to be changed as well. 

I would also like to see some way of targeting the same tile over and over without moving the cursor there every time, similar to how it auto-targets enemies over and over. This would help when I'm training by shooting at something other than an enemy.

**Comment by DanielPBak** [comment]
I'm thinking that this just requires an interface similar to the normal aiming interface. Does anyone have suggestions as to how I would implement this?

**Comment by kevingranade** [comment]
There's a member of player that tracks the current aim target, it currently must be a pointer to a creature.
When aim actions are taken, it first checks that you're still aiming at the last target aimed at, if not, it resets your recoil to RECOIL_MAX to represent changing your target, then applies the aim action.  It's a bit complicated because you continue aiming at the same monster even if it moves.

This feature requires a change to the related code to set your aim point as coordinates instead of a creature.
It also requires a decision about what to do if a monster wanders into the square you're targeting.  Does shooting with high aim into a square with a monster count as a aimed shot at the mobster?  I don't think it should, but completely resetting your aim also seems like an extreme approach.

**Comment by DanielPBak** [comment]
Yes, I edited it after a few hours (before you replied though, I think). A lot of this stuff was still super useful.

re: the monster thing, I think it makes most sense to just shoot the terrain where the creature is standing. One can imagine situations where you'd really actually want to aim at furniture or something the creature is standing on. It seems odd to me that a player would desire that the target be switched to the creature, since they wanted to shoot the terrain.

On the other hand, one can imagine aiming at a doorway, waiting for a zombie to walk through it at which point you immediately shoot it. This would require a "pre aim" feature which feels like a separate thing.

**Comment by TeMPOraL** [comment]
> When aim actions are taken, it first checks that you're still aiming at the last target aimed at, if not, it resets your recoil to RECOIL_MAX to represent changing your target, then applies the aim action.

> It also requires a decision about what to do if a monster wanders into the square you're targeting. Does shooting with high aim into a square with a monster count as a aimed shot at the monster? I don't think it should, but completely resetting your aim also seems like an extreme approach.

Maybe the aim shouldn't be always reset to `RECOIL_MAX` on target change? Maybe a more tiered approach would be suitable - e.g. if the new target is in the same tile (e.g. switching from the floor to a monster), reset to 33% towards `RECOIL_MAX`; if the target is in a neighbouring square, reset to 66% of it; anywhere else it goes to 100%. We could then not count the shot aimed at floor as a shot aimed at a monster - the reasoning being, if I aimed at the ground next to monster's feet then I really want to shoot the ground; if I want to shoot the monster, I pay the slight (33%) penalty of adjusting my aim.

**Comment by Amariithynar** [comment]
This really needs to be changed; there's no reason that I'd stop aiming and just stand down when a Smoker Zombie is barrelling towards me at full tilt, but a wisp of smoke obscured him for a split second and as such I can't pass turn/time until he shows up again, without wasting ammunition. Same goes for if I know there's (more of) a horde coming around a corner, but I've already killed all the currently visible zombies.
