### ISSUE TITLE
Dispersion cap is hidden from the player

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#22002]
`player::get_weapon_dispersion` has this line:
```
int weapon_dispersion = std::max( obj.gun_dispersion() / 3, 45 );
```

This means that any weapon with dispersion below 135 still shoots at 135 dispersion. This is not a bad thing on its own, the problem is that the cap is applied in `player::get_weapon_dispersion` and not `item::gun_dispersion`.

**Comment by aeoo** [comment]
Is sniping effectively impossible with the new changes?  From my limited testing every gun behaves like a handgun now.  It no longer makes any difference in terms of effective range, because roughly every gun in the game has an effective range of about 5 or so (with 3 marksmanship).

**Comment by aeoo** [comment]
Another thing I am curious about is whether or not this recent aiming change has indirectly made all the gun skills much more difficult to raise.  Since hitting things is much harder (as far as I can tell) and since marksmanship requires hits from a very long range to advance, it's next to impossible to train it now.

So not only is hitting things much harder now, but even the skill that would help you hit things is also harder to develop now?  It's potentially soft-capped at around 3-4 unless you find a rifle scope?   I might be wrong but that's how it seems for now.

**Comment by Coolthulhu** [comment]
> Is sniping effectively impossible with the new changes?

You can still snipe, but just like before that change, you need to be very "high level" to pull it off. It increased the threshold of when real sniping starts, though.

An optimized (for ranged) but not "one trick" character can expect to have sum of dex+per of 22. Before the change, this would result in no penalty and also possibility of offsetting weak sights. After the change, you can't drop the stat penalty below 20 average dispersion with those stats.

> If the max effective range for every gun is fixed at roughly 5, the hanguns become the best possible guns in the game.

Not really. Most ranged weapons are necessarily support - the only pistol which can be the main weapon is the laser pistol. Rifles are better support than pistols. Pistol burst won't take down a hulk.
Wield time doesn't matter, volume doesn't matter, what matters is how can it complement melee. Rifles can be trained more easily and are much stronger at burst damage, hence they still rule.

>  Since hitting things is much harder (as far as I can tell) and since marksmanship requires hits from a very long range to advance, it's next to impossible to train it now.

The message is misleading now. It was changed not to require hitting target at range, just hitting any target. The best way to grind marksmanship now is spamming sling/bow at adjacent fungaloids.

**Comment by aeoo** [comment]
That's very informative, thank you.

>The message is misleading now. It was changed not to require hitting target at range, just hitting any target. The best way to grind marksmanship now is spamming sling/bow at adjacent fungaloids.

This might be so, but it appears there needs to be a *lot* of spam because each individual increase is tiny when at short range?  This would explain the reason why you suggest slings, because their ammo is nearly infinite and free, compared to bullets.  So I have to use a sling to grind marksmanship now instead of wasting bullets for tiny marksmanship gains.  Once my marksmanship hits around 6 or so I should use rifles once in a while.

As for bursts, the kings of bursting are still imo, submachine guns.  Rifles used to be better at placing a single exceptionally powerful round at a very very long range.  If I want to burst at short range, I love smgs for that.  They're lighter and easier to aim too, and MP5 line of smgs are almost rifle-like in accuracy (which doesn't say as much these days, lol), and they fit into a survivor harness instead of like rifles which pretty badly increase encumbrance when worn (and the back holster is kind of encumbering and it conflicts with backpacks which occupy the same layer).

So what I think has happened is that with this change the rifles were nerfed in favor of shorter range weapons and now using actual bullets to advance skill is counter-indicated?  So there is a strong push toward something like a pneumatic rifle and a crossbow.  Which might be intentional, and that's fine.  But the balance now is quite different in many ways.

**Comment by aeoo** [comment]
I think quite a bit differentiation in terms of accuracy was lost, basically.  There is still differentiation between hanguns, smgs and rilfes in terms of ammo types and magazine size and other properties, so there are still interesting and meaningful differences between the many gun types, but accuracy and range distinctions at least at lower levels of marksmanship are kind of lost in the noise now.

I can understand this up to a point.  Like if we assume all the shots taken from a rifle are from a standing position, fine, maybe rifles aren't all that much more accurate than handguns.

Would it make sense to consider implementing a prone position that takes a lot of in-game time, makes one unable to quickly run away once prone, but drastically increases accuracy specifically with rifles and to a lesser extent with smgs and shotguns and has next to no accuracy effect on handguns?

I think ideally even a rifle with iron sights should still put a handgun to shame in terms of range and accuracy when shooting prone.

**Comment by kevingranade** [comment]
Agreed this is a bug, and the suggested solution of moving the adjustment into item::gun_dispersion should resolve it,

This discussion of balance issues is picking up a bit of steam, please post your thoughts here http://smf.cataclysmdda.com/index.php?topic=15001.0 , because this issue is going to be closed soon and this conversation is going to be effectively lost.

Re: marksmanship training:
Ideally (not how it's implemented now), marksmanship practice would typically be a lot more intentional.  I.e. you set up a target, and spend x rounds and y time target shooting, gaining a high amount of marksmanship xp while doing so.  Meanwhile shooting at live targets doesn't give that much xp because it's really difficult to learn in a nuanced way in that environment, but it would serve to stave off skill rust, so no mandatory practice sessions just to maintain your skill level.

Shorter term, ranged practice could probably use a boost of some kind.
