### ISSUE TITLE
AMMO stack_size not working as expected

### ISSUE THREAD

**Issue by angoddu** [CleverRaven/Cataclysm-DDA#22028]
Branch off master

### Expected behavior
When ammo stack size is set to 100 and volume is set to 1 then 100 of that ammo would fill 250ml (0.25L) of space

### Actual behavior
Ammo with stack size 100 and volume 1 take up only 200ml (0.20L)

### Steps to reproduce the behavior
Plant fiber has a stack size of 200 so if you spawn in 200 plant fiber (in the wish for count put 20 because it spawns in batches of 10) you will see that the volume is only 0.20L. In JSON_INFO:

>"volume" : 1,                     // Volume, measured in 1/4 liters

> "stack_size" : 50,    // (Optional) How many rounds are in the above-defined volume. If omitted, is the same as 'count'

Am I doing something wrong or is stack_size calculating wrong?

**Comment by angoddu** [comment]
Can anyone help me here?

**Comment by cainiaowu** [comment]
This seems to be a rounding problem, the minimum volume is 1ml so anything below just get ignored.

**Comment by angoddu** [comment]
Right but that's what stack size is supposed to handle. "How many fit in this volume". I find that the stack size is completely ignored sometimes

**Comment by jbytheway** [comment]
I think a solution here is to store volumes as a rational number rather than an integer.  Given that volumes are nearly always passed around as a units::volume object, that probably wouldn't be too hard to implement.  It does increase the risk of integer overflow, however, especially if people start defining items with unusual volumes.

**Comment by cake-pie** [comment]
There is an alternative, if handling all volumes as floating point numbers is not desired.

Instead of doing this in item factory, which ultimately leads to `charges × truncate(vol_per_charge)`
https://github.com/CleverRaven/Cataclysm-DDA/blob/c5d4ca6aac03d46d249cf06f897a4f3ae45e995a/src/item_factory.cpp#L182-L186

Only perform the division + rounding when a volume value is requested, so
`truncate( charges × default_stack_vol / stack_size )`
