### ISSUE TITLE
How to help with Astyle

### ISSUE THREAD

**Issue by angoddu** [CleverRaven/Cataclysm-DDA#22093]
I would like to do more to help this game develop as I really love playing it. While I'm learning the ins and outs of how the code functions, I figured I could start by helping with the Astyle stuff so here are my questions. 

What needs to get done? 
How many files should I re-style in a single PR? 
Is it just the JSON files that need re-styling or does the C++ code also need re-styling?

I wish I could help with the translation stuff but I don't know another (spoken :P) language. I would love to be able to work on the little fixes so people like @codemime and @Night-Pryanik can focus on the bigger picture things. I know C++ fairly well so I can make fixes to the source code as well as fixes to the JSON files.

**Comment by kevingranade** [comment]
I'd hold off on json styling for the moment, I'm just about to swap out the tool we use to do that with #21612, and it will work slightly differently after that lands.

For c++ styling, we use the astyle tool, and have put some wrappers around it in Makefile.
I have a brief outline of a batch settling workflow in doc/CODE_STYLE.md, feel free to ask for clarification on that since I don't know of anyone doing it except myself.

Generally though, you want to restyle a manageable chunk of code, read the diff to check for obvious errors, build the game (with RELEASE=1) and run it to again check for fairly obvious errors, remove any fully-styled files from the astyle blacklist file, then make a pull request with your changes.

**Comment by angoddu** [comment]
If I'm reading this right then I could just install the sublime style, open the cpp files, auto format them, test, then remove them from the black list. Is that all that would need to be done or am I missing something

**Comment by ZhilkinSerg** [comment]
You also need compile and run game after you astyled them.

**Comment by angoddu** [comment]
Right. That's what I would do when I test the changes
