### ISSUE TITLE
Artifacts do not have a category

### ISSUE THREAD

**Issue by lonelychaser** [CleverRaven/Cataclysm-DDA#22104]
Game version: 0.C-23389-gd993d6c

Operating system: Windows 10

Tiles or curses: Tiles

Mods active:
  "dda",
  "filthy_morale",
  "no_npc_food",
  "novitamins",
  "StatsThroughSkills",
  "blazemod",
  "Tanks",
  "boats",
  "realguns",
  "ew_pack"

### Actual behavior
![extra item entry in v](https://user-images.githubusercontent.com/31850167/31314065-e7d0d1ee-ac28-11e7-8c32-da6f83f15ba1.png)
An invisible entry appears on the player tile without any reason and the description of the previous item carries onto the invisible entry. There is nothing below the ground player is on.
### Steps to reproduce the behavior
- Load [the save](https://drive.google.com/file/d/0B9NNp9wUrjFgNHhIeFgxaXBBWEU/view?usp=sharing)
- Press [V] to list all items around the player and move up to find the invisible entry

Unfortunately, I haven't been able to replicate this bug so I can't provide more useful information. Maybe this is related to the vehicle parts on the vehicle?

**Comment by OzoneH3** [comment]
This is a problem with artifacts not having a proper category assigned to them, so V is skipping printing the category because it's "empty" but not empty().

![](https://user-images.githubusercontent.com/3514404/31336835-f48b0046-acf8-11e7-84f1-a3a2b6aa8c96.png)

When picked up it becomes clearer to whats happening.
