### ISSUE TITLE
Missing explosives data

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#22120]
There is missing data on these explosives:
- [ ] `mininuke` - no data at all. `mininuke_act` has data on power;
- [ ] `c-4` - no data at all. `c4armed` has data on power and shrapnel, no data on countdown;
- [ ] `pipebomb` - no data at all;
- [ ] `fertilizer_bomb` - no data on countdown;
- [ ] `tool_rdx_charge` - no data on countdown;
- [ ] `tool_rdx_sand_bomb` - no data on countdown;
- [ ] `dynamite` - no data on countdown;
- [ ] `tool_anfo_charge` - no data on countdown;
- [ ] `empbomb` - no data on countdown;
- [ ] `tool_black_powder_bomb` - no data on countdown;
- [ ] `tool_black_powder_charge` - no data on countdown;
- [ ] `tool_rocket_candy` - no data on countdown;
- [ ] `matchbomb` - no data on countdown.

**Comment by angoddu** [comment]
How could you figure out the values ingame so you could add the data in

**Comment by Night-Pryanik** [comment]
@angoddu Not sure what you meant here.

**Comment by Coolthulhu** [comment]
Some of those tools (3 first) use hardcoded algorithms for countdown.
Mininuke and C-4 use it to set countdown. The best way to solve this would be to expand the transform actor to allow setting countdown, then make them use the actor.
Pipebomb uses some weird hardcoded algorithm for everything. I don't think it is a good idea to keep it this way just so that it can fizzle sometimes. It probably should be turned into a more normal bomb, using a regular actor, with stats pulled out of the air.

For the rest, the problem is solvable with json: they need to be changed in the following way:
* In the inactive item, use "countdown" instead of "target_charges"
* In active item, "use_action" to "countdown_action"
* In active item, "turns_per_charge" to "countdown_interval"
* In active item, "countdown_destroy": true 

For examples, see tools.json (search for "countdown" to find bombs) and grenades.json.
