### ISSUE TITLE
Trouble Compiling on VS 2015

### ISSUE THREAD

**Issue by nrfowler** [CleverRaven/Cataclysm-DDA#22156]
Operating system: Windows 7
Pulled in the master branch from CleverRaven, followed the steps on the Compile page for Visual Studio. I get the following error:

Error	MSB3073	The command "prebuild.cmd
:VCEnd" exited with code 9009.	Cataclysm	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	123	

If I just delete that PreBuild target from Microsoft.CPPCommon.targets, the errors do not come up and the compiler runs. But then I get many similar errors which all point to json.h and have the same error code, here is an example:

Error	C2535	'unknown-type JsonIn::read(T &)': member function already defined or declared	Cataclysm	c:\users\nathan\desktop\cataclysm-dda\src\json.h	302

**Comment by Night-Pryanik** [comment]
Is this still an issue?

**Comment by Leland** [comment]
Closing due to lack of response

**Comment by henck** [comment]
This is still an issue. I tried compiling the code today in Visual Studio 2015 and I got 200+ errors over the overloaded `JsonIn::read(T &)` member function (already defined or declared). Apparently it won't accept the overloads.

I did get `prebuild.cmd` to work, so that has nothing to do with the issue. Is this a Visual Studio configuration problem?
