### ISSUE TITLE
Windows/OSX builds broken on ci.narc.ro (6852)

### ISSUE THREAD

**Issue by DanmakuDan** [CleverRaven/Cataclysm-DDA#22157]
Starting with build 6852 (new JSON formatter) on Windows and OSX builds, using xargs to check the json_whitelist formatting is causing the formatter to try to format its own CGI app.

Windows 64bit tiles version:
```
09:33:33 xargs -a json_whitelist -L 1 tools/format/json_formatter.cgi
09:33:33 tools/format/json_formatter.cgi: 1: tools/format/json_formatter.cgi: MZ����@���: not found
09:33:33 tools/format/json_formatter.cgi: 1: tools/format/json_formatter.cgi: Syntax error: word unexpected (expecting ")")
```

**Comment by narc0tiq** [comment]
What I get from that output is that it's trying to execute. As a Windows (or OSX) binary, it naturally can't run on the Linux host.

The way I mitigated that for `chkjson` was to have the `make json-check` step part of the build script:
```sh
if [[ "${Platform}" == "Linux" || "${Platform}" == "Linux_x64" ]]; then
    make json-check
fi
```

Since the new formatting check is just part of general `make`, it tries to run in all cases, including in a cross-compile. Someone should probably fix that.
