### ISSUE TITLE
"Linter currently unavailable" error in web linting tool

### ISSUE THREAD

**Issue by ZhilkinSerg** [CleverRaven/Cataclysm-DDA#22179]
Cataclysm web linting tool located on http://dev.narc.ro/cataclysm/format.html gives following error: "Linter currently unavailable".

**Comment by ituluwituluwzev** [comment]
This is very useful. Why is it an issue?

**Comment by kevingranade** [comment]
Dumb mistake on my part, I renamed the executable during some testing
because I was using a webserver that insisted the filename should be .cgi

**Comment by ZhilkinSerg** [comment]
How can we fix this? Do we need to move compiled `json_formatter.cgi` to web-server or what?

Also pinging @narc0tiq :)

**Comment by narc0tiq** [comment]
There's some problems:
- the formatter deployment wasn't building the `json_formatter.cgi`, I've fixed that.
- `format.html` is referencing `/format/json_formatter.cgi`, but on the server it lives on `/tools/format/json_formatter.cgi`, in the same place `format.pl` lived. I'm not changing the server path, so that'll need updating.
- `json_formatter.cgi` doesn't get copied over as executable, but this may have been fixed now that I `chmod`ded the target.

Really, nobody thought to ping me sooner?

**Comment by ZhilkinSerg** [comment]
Online linter worked yesterday after you have fixed it, but now it is not working again (probably after new automatic build which replace path in `format.html` to invalid value). I've changed server path in #22551. Will it be enough?

> Really, nobody thought to ping me sooner?

I probably should've done it in a first place :)

**Comment by kevingranade** [comment]
Working now, sorry for breaking it and then forgetting to follow up.
