### ISSUE TITLE
Gun magazine differentiation.

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#22206]
As brought up in #18497, magazine support is a good point of differentiation for various kinds of guns.  These are proposals that were brought up to accomplish that.

- [ ] 223 rifles that don't accept STANAG magazines
- [ ] There are some STANAG rifles that we could still block drums and such on simply due to ergonomics
- [ ] Standard Styer Aug uses dedicated 30 and 42 polymer magazines.
- [ ] The G36 could have it's own magazine
- [ ] We could add the C-Mag 100-round drum.

**Comment by Phenomphear** [comment]
It seems as of recently the C-Mag 100-round drum has received enough improvements to be much more reliable and was tested by the army in 2008.

[http://www.betaco.com/documents/Dept_of_Army_memo_08-11-28.pdf]

It is compatible with these firearms that are in the game:

SMG's
-----
Heckler & Koch MP5
UZI 9mm

Pistols
------
Any Glock 9mm 

Rifles
------
AR-15
Beretta ARX-160
Both SCAR's
G36
416A5
M4A1
Ruger Mini-14
SIG 552
Steyr AUG
FN FAL
H&K G3
M14 EBR-RI

A C-Mag loaded with 5.56×45mm NATO ammunition weighs about 2.1 kg (4.63 lb) and loaded with 7.62×51mm NATO ammunition weighs 4.77 kg (10.5 lb).

The volume of the pouch that carries one (approx.)
.223 2L 
(1.8L in actuality, but I don't think the dimensions given for the pouch included the space in the cover that flips down over the magazine)

9mm 5L (it's huge because of how long the magazine that leads to the drums has to be)
7.62 5L

The volume of the actual drum is kinda tricky since the company doesn't give it I used rectangular tank volume.

9mm 1.3L (This is somewhat inaccurate because of dead space above each drum that follows the length of the magazine, so in reality, it probably takes up about 5L)
.223 2L
7.62 4.7L

I'd like to create this item, but, I need some feedback first and help on how to implement an item.

**Comment by Mooses2k** [comment]
Not sure if this is the right location or separate issue.

There exists a caliber called 300BLK (.300 Blackout) that uses necked-up .223 brass. It's gaining popularity. One of the benefits of the round is that it can be loaded in STANAG mags. This brings up the issue in the game. I don't think there's a system by whereby a mag can accept two different calibers, and not operate with guns that don't have that caliber but accept that mag. Example, load a STANAG with 300BLK - it shouldn't work in a standard M4.

**Comment by bandti45** [comment]
I believe it would take some c++ (which I don't know anything about using) but you could make it that when the magazine is trying to be reloaded it can check to see if the ammo in the mag is useable in the gun, and if not then cancel the reload process. this would allow the magazines to have multiple ammo types loaded without breaking guns.
