### ISSUE TITLE
[Ranged balance - STEP 3] Ranged balance doesn't satisfy ranged balance design

### ISSUE THREAD

**Issue by Firestorm01X2** [CleverRaven/Cataclysm-DDA#22213]
Current ranged balance doesn't satisfy balance design outlined in:
https://github.com/CleverRaven/Cataclysm-DDA/issues/21244#issuecomment-310013403

It must satisfy tests and design.

It is continuation of:
https://github.com/CleverRaven/Cataclysm-DDA/issues/22211

Recommended actions:
I recommend to going for Test Driven Development approach for ranged balance. So - tests first.
https://en.wikipedia.org/wiki/Test-driven_development

1) Take care of that issue first: https://github.com/CleverRaven/Cataclysm-DDA/issues/22211
2) Achieve ranged balance that fits test in multiple tries. Tests will be indicating  that balance normalizing step by step.

Do not recommended actions:
1) Trying to achive balance in single try with big PR for months or years.
2) Force test to fit themself while fixing that issue. If it would be done again - then we will return to same issue again. And again.

**Comment by Firestorm01X2** [comment]
Current range balance satsfy tests that missed design.

**Comment by kevingranade** [comment]
It is unclear what the difference in expected outcome between "Step 2" and "Step 3" is.  It looks like they have the same outcome, which is "better ranged balance tests".

Your proposal of adding failing tests to the master branch is not workable, this is not a valid way to proceed.  Tests that fail are not valid tests, they are only allowed to exist on feature branches, not the master branch.  Likewise written but un-executed tests are only allowable to exist temporally.  It is not workable to write a large batch of tests that fail, then incrementally make them pass, this is not a sane workflow because it is extremely fragile and prone to being abandoned.

This:
> Force test to fit themself while fixing that issue. If it would be done again - then we will return to same issue again. And again.

Is exactly how TDD indicates that you proceed.  At each step you have passing tests that make meaningful assertions about the behaviour of your system, and you introduce new tests and code that causes them to pass simultaneously to the master branch in order to refine the behaviour of your system.

**Comment by Firestorm01X2** [comment]
>Your proposal of adding failing tests to the master branch is not workable, this is not a valid way to proceed. Tests that fail are not valid tests, they are only allowed to exist on feature branches, not the master branch. Likewise written but un-executed tests are only allowable to exist temporally. It is not workable to write a large batch of tests that fail, then incrementally make them pass, this is not a sane workflow because it is extremely fragile and prone to being abandoned.

Well. I think thoght on that again. You are right. But it may be tried anyway. But yes- bad idea.
So I am closing that. But test issue will stay.
