### ISSUE TITLE
Cataclysm-DDA Discord Weekly Discussions Week 1: NPCs

### ISSUE THREAD

**Issue by mount2010** [CleverRaven/Cataclysm-DDA#22223]
Hey guys, this is a compilation of the suggestions bought up during Week 1 of the Weekly Discussions channel on the CDDA Discord server.

* AIs with background stories and variable approaches to the player and the world 
* AIs being able to adapt to the player's actions; i.e. catching a ride on a slow moving vehicle (KantoJolto#1276, Mount2010#9649)
* NPCs to be able to define a hometown, or home location, and have a attachment rating. This will lead to them not wanting to leave it, for example (Mount2010#9649)
-- Can result in hermits
* NPCs to be able to do construction (KantoJolto#1276, Lear85#0671)
* Player occupation can affect what static NPC spawns. E.g: Bride profession getting a Groom NPC (Mount2010#9649)
* NPCs to be able to go on supply runs, and raid. NPCs to be able to steal in order to build up their own terrority e.g. steal doors from neighbouring houses; (KantoJolto#1276, Lear85#0671)
* NPCs to be able to define locations as sources for specific locations; world context for specific locations - e.g. "food and drink" connected with restaurant. (KantoJolto#1276)
--  Can be implemented via the same system as "notes" atm
* Do social awkward things e.g. strip naked in public with a "crazy" variable - give insane quests?(KantoJolto#1276, Lear85#0671)
* NPCs to consider current skillset v.s. the base stats of a weapon they have less skill in (KantoJolto#1276)
-- Scored based on variables such as personality and encumbrance (Lear85#0671)
* Factions: Being able to sell NPCs to bandits, for example (KantoJolto#1276)
* "Should I explore" check - automation for NPCs - check if Player is doing something socially awkward -- makes socially awkward things e.g. Vibrators less effective
```
"Basic structure of "should I explore" check.

Is house fully enclosed, or are doors/windows/walls broken?
  If so, do I have the skills to fix that?
  If yes, +5 to explore.
How am I on food?
  Great? Great.
  Running low? +3 to explore.
  Entirely out? Am I hungry?
    No, +5 to explore.
    Yes, +x to explore, depends on how hungry I am.
Is a player currently using a vibrator in line of sight? +X to explore, depending on personality tags. //"Um... Should I leave? I should leave. Have fun, I guess...? Jesus christ."

I'm crazy, so my threshold to explore is higher.

Is incentive higher than threshold? Yes? Draft a shopping list and start roaming!"
``` 
(Lear85#0671)

* Mutations to affect NPCs' genetics. (ZelteHonor#0686)

**Comment by Coolthulhu** [comment]
> NPCs to be able to define locations as sources for specific locations; world context for specific locations - e.g. "food and drink" connected with restaurant.

This is already in, just that the NPCs are too bare bones to properly show it.

> NPCs to consider current skillset v.s. the base stats of a weapon they have less skill in

This is already in and working pretty well.

> Mutations to affect NPCs' genetics.

Not sure what is that supposed to mean, so I'll pick the best possible option: NPC traits.
I planned to add those, but the problem is, someone needs to go through traits to find those which won't bug the NPCs. For example, NPC with wool allergy should, like the player, get replacement items instead of the wool ones.
Then the NPC-friendly traits need to be marked somehow.

**Comment by kevingranade** [comment]
> AIs with background stories and variable approaches to the player and the world

Agree With Coolthulu here. This differentiation already exists, but is not particularly visible or meaningful, it pretty much just sets starting skills and gear.
For this to be an actionable issue, it needs to be a lot more developed, like enumerating the conversation tree that wold reveal a NPCs history, and presenting a framework for how aspects of NPC history contribute to decision-making.

> AIs being able to adapt to the player's actions; i.e. catching a ride on a slow moving vehicle (KantoJolto#1276, Mount2010#9649)

I think I understand the first part, the second part is very clear, but I have no idea how they are related to each other.
Seems like jumping on a vehicle is doable up to a speed approaching top running speed, which is just shy of 30MPh for olympic sprinters, I can't really see alowing this to exceed 20MPh for a survivor considering:
non-ideal running surface, not an olympic athlete, generally not wearing minimal running clothes
So yea, having a NPC hop onto a vehicle they can catch up with that is moving at no more than 20MPh sounds like a reasonable feature ask.

> NPCs to be able to define a hometown, or home location, and have a attachment rating. This will lead to them not wanting to leave it, for example (Mount2010#9649)
    -- Can result in hermits
> NPCs to be able to go on supply runs, and raid. NPCs to be able to steal in order to build up their own terrority e.g. steal doors from neighbouring houses; (KantoJolto#1276, Lear85#0671)
> NPCs to be able to define locations as sources for specific locations; world context for specific locations - e.g. "food and drink" connected with restaurant. (KantoJolto#1276)
    -- Can be implemented via the same system as "notes" atm
> "Should I explore" check - automation for NPCs - check if Player is doing something socially awkward -- makes socially awkward things e.g. Vibrators less effective

I don't think there's a sufficient infrastructure in place for NPCs taking action when not near the player for these to be feasible feature asks right now, this is the kind of thing that needs to go into a "NPC acting on their own" design document to try and guide development of such a framework.

> NPCs to be able to do construction (KantoJolto#1276, Lear85#0671)

Seems reasonable and achievable, this would be an extension to the construction menu that results in assigning the construction task to a NPC rather than to the player.  There's an extra wrinkle in that the NPC can end up outside the reality bubble for part of the constructon task, but I don't think that'll be to problematic.
Also I don't think NPC's can even do long actions as such, that might actually require a lot of overhaul of that system to make it work, but it's worthwhile.

> Player occupation can affect what static NPC spawns. E.g: Bride profession getting a Groom NPC (Mount2010#9649)

Rather than tying it to occupation, how about attaching it to a scenario?  Just seems like a better fit.  Regardless, seems like a reasonable feature, there's also a super-powered scenario where player spawns with a whole group of friendly NPCs.

> Do social awkward things e.g. strip naked in public with a "crazy" variable - give insane quests?(KantoJolto#1276, Lear85#0671)

This lands in the "I'm not going to tell you not do add it" (depending on the details of some of the craziness), but I'm also not going to open an issue suggestion someone do it.

> NPCs to consider current skillset v.s. the base stats of a weapon they have less skill in (KantoJolto#1276)
    -- Scored based on variables such as personality and encumbrance (Lear85#0671)

Can you give an example?  Is this intended to make NPCs seek out and use more varied weapons, prevent them from all getting stuck with the same weapon preferences, or something else?

> Factions: Being able to sell NPCs to bandits, for example (KantoJolto#1276)

No.

> Mutations to affect NPCs' genetics. (ZelteHonor#0686)

If by genetics you mean, "traits passed down to descendents", we have no intention of having multi-generational play, so no.

**Comment by Night-Pryanik** [comment]
Lots of proposals, this list should be split into separate issues.

**Comment by BorkBorkGoesTheCode** [comment]
@Night-Pryanik You have an avatar now

**Comment by Night-Pryanik** [comment]
Yes, I know it, as I've added it myself.

**Comment by BorkBorkGoesTheCode** [comment]
What has led you to become a little hunched devil man?

**Comment by Night-Pryanik** [comment]
I became a little hunched devil man a long time ago, I guess more than 15 years ago. Friend of mine pictured me from the back like that when I was doing something on my PC (don't remember exactly what it was, but it was obviously devilish, heh). And while searching some info in my archives some days ago, I found this long-forgotten pic, and decided to use it as avatar.
