### ISSUE TITLE
Prying already pryed and then closed windows mechanics grinding exploit

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#22230]
Game version: 0.C-6872

Operating system: Windows XP SP3 x86

Tiles or curses: tiles

Mods active:default only

### Expected behavior
Closing pryed window should turn it into not-pryable version to prevent re-prying it.

### Actual behavior
Closing pryed window turn it into pryable version and one can re-pry it and grind mechanics this way.

### Steps to reproduce the behavior
Pry domestic window, enter house, close this window in question from the inside, exit house through door or other window, pry this window again.

**Comment by TeMPOraL** [comment]
Doesn't sound like a bug to me. Careful prying of a window should leave it generally undamaged (aside from possible damage to a lock, if it was applied). Therefore closing it shut and going around to pry it again is a reasonable thing to do, even if you'd want to train your window-prying skill in Real Life for some reason.

Also, prying windows AFAIK risk breaking them completely, which puts a natural limit on the effortless grinding you can do with this method. Not to mention, can you train any-skill beyond 1 with prying? (If so, I'd consider nerfing this.)

**Comment by Coolthulhu** [comment]
The skill gains for opening things are very low. It should probably be taken out - it's rather weird that you can train welding/gear systems/internal combustion/hydraulics by repeatedly closing and opening a door/crate/window. It's also weird that welding/gear systems/internal combustion/hydraulics knowledge improves your ability to operate a crowbar.
It makes sense for lockpicks because those obviously involve mechanical parts, but crowbars aren't even tangentially related.

**Comment by kevingranade** [comment]
See #21814 for further discussion re: b&e and mechanics.

**Comment by Coolthulhu** [comment]
Pretty sure it's fixed now, unless there was some other non-crowbar-related way of doing this.
