### ISSUE TITLE
Character creation issue with CerealMod

### ISSUE THREAD

**Issue by Radar11** [CleverRaven/Cataclysm-DDA#22248]
Game version: 0.C-24669-g31eba0c

Operating system: Windows 10 x64

Tiles or curses: Tiles

Mods active: (Core Content Packs) Dark Days Ahead, (No Category) The Wonder Of Cereal!

### Expected behavior
Expected to create a new character, The Last Firefighter Scenario to test out the CerealMod for KantoJolto.

### Actual behavior
Error occurred during initialization of character creation, unsure of the source. Contacted the mod creator, and they're sure it's not an issue created by their mod. I have attempted to create a world and character with only (Core Content Packs) Dark Days Ahead installed and was successful. Image of error screen included: https://imgur.com/a/S4cgA 

### Steps to reproduce the behavior
In order to reproduce error, download mod here: http://www.mediafire.com/file/cuv4rk3ofg3nb5p/CerealMod.zip 
Create new world with both mods enabled, create new character, error appears. 

Any help or tips to fix this error from occurring, will be greatly appreciated.
This is my first time posting a bug report on GitHub, so I apologize if this isn't formatted correctly. If you require any additional information, feel free to let me know.

**Comment by Coolthulhu** [comment]
Error is almost certainly on their side, though the error message being very uninformative could be considered a bug on its own.

Each item group has one of two types:
* Distribution - only one item is selected from the group
* Collection - all items from the group are rolled

The author tried to extend an existing group, that currently is one of the groups, using the other group type. This is not allowed because doing so would be rather complex.

I'll try to make the message more informative so that authors of mods can be informed what they need to fix.

**Comment by KantoJolto** [comment]
I've released newer versions since then, just on very inconsistent release channels. 
The newer version I am currently deploying does not feature any such bugs that you are experiencing. I even tested the firefighter scenario just now and experienced no problems. A download link will be sent to you directly on reddit, Radar.

**Comment by Night-Pryanik** [comment]
Closing now. If anyone still encounter this issue, feel free to ping me.
