### ISSUE TITLE
Disassembling sling made from 3 long strings yields leather and thread

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#22305]
Game version: master

**Comment by Coolthulhu** [comment]
Confirmed.

Seems that the game has no means of telling which recipe produced a given result and it doesn't respect the `components` field if it differs from the ones specified in recipe.
`player::complete_disassemble` specifically searches for components from the recipe. If it fails, it defaults to ones in the recipe rather than ones in the item.

**Comment by ZhilkinSerg** [comment]
I've mentioned the issue in #20342.

**Comment by Leland** [comment]
Merged with #18153 to more broadly address this
