### ISSUE TITLE
Custom item selection menu performance scales very badly with item count

### ISSUE THREAD

**Issue by Coolthulhu** [CleverRaven/Cataclysm-DDA#22319]
A shopping cart full of bottles and bags with food causes the item selection menu to take up to 1 second to open on my side. My computer is a toaster, but if a single cart full of bottles can clog it, a trunk or cargo carrier will lag even high end computers.

EDIT: Wrong lead, `item_location` is only linear when it's loading a save.
Maybe `inventory_column::expand_to_fit`?
Can anyone run a profiler? I couldn't set it up right on my setup (and each attempt takes over an hour due to toaster hardware).

**Comment by taiyu-len** [comment]
it does have a bit of slowdown,
heres something quickly put together.

build game with `make LOCALIZE=0 LUA=1 CLANG=1 cataclysm` using -g1, instead of -g however
recompile `game_inventory.o, inventory_ui.o, ui.o` with -pg flag, link with -pg flag
start new game, filled shopping cart with a bunch of random food from debug menu. save. quit
start game under `uftrace record -F game_menus::inv::consume cataclysm`
load game, press E next to cart to open up menu. press escape while its loading, then quit

heres the results. it has quite a bit of slowdown so the timings might not be the most reliable.
https://gist.github.com/taiyu-len/51e9655dd6f3932c40d8b83d6b1fd108

a few things to note,
sort_compare takes the longest to do, pgettext, rate_freshness, then allocations.
there are 1million allocations, just opening the `E`at menu and closing it. which is probably a bit more then it should be.

expand_to_fit is relatively small compared to those.

**Comment by Coolthulhu** [comment]
Interesting: my local MSYS2 build is an order of magnitude faster at opening the menu than ones from Jenkins.
Could be related to localization.

**Comment by Coolthulhu** [comment]
The code for item selection menu is rather convoluted. I'm not sure how to best make it cache the values used for sorting and display.
Pinging @codemime

**Comment by Xelat84** [comment]
> I'm not sure how to best make it cache the values used for sorting and display.

Just thoughts.

May be keep items sorted in a pile/container/inventory, and resort only in some cases when you interacting with item list:
- game just loaded (initial sorting)
- some items added/renamed
- may be some other triggers

Also cache item text width within item itself, but only on runtime of course. And invalidating that cache when renaming, changed state or charges count.

**Comment by cainiaowu** [comment]
not sure if related, but I am also getting lag in Android port when trying to repair something via % menu in my shelter.
There are lots of items (thousands different stacks) insight.
If I just step outside of the shelter then the lag is gone even though those items are still in the bubble.

**Comment by Coolthulhu** [comment]
> May be keep items sorted in a pile/container/inventory

They need to be re-sorted every time the menu is opened. They can't be pre-sorted, because different menus opened in different locations at different times may have different sorting orders.

**Comment by Xelat84** [comment]
> They need to be re-sorted every time the menu is opened. They can't be pre-sorted, because different menus opened in different locations at different times may have different sorting orders.

But anyway any caching logic should have some triggers for invalidation.
How about keeping in memory a single collection (A), containing sorted collections of items (B), each related to specific set of affecting parameters (tile, interface window). And there will be cached only item lists that has more than X items in it, so it will not cache item lists, that have few items. And whole collection (A) limited to N records, so when added N+1 record, most outdated is removed. Also when item got removed from tile/container, we can just remove that item from sorted list.

Usually lag issue is related at most to player bases, and only sometimes to some POI containers (food store for example).

I also will think about some generic solution later.

**Comment by Coolthulhu** [comment]
Presorted options are out, that would require keeping sort order caches per-item-stack, per-sort-type, which is just plain unmaintanable.

I'm going for `mutable` hacks for now. The problem is serious and a small hack that can be easily reverted is better than overhuge solution that may take weeks to engineer.

**Comment by Leland** [comment]
#23636 saw this with cash cards

**Comment by kevingranade** [comment]
Fixed by #25346
