### ISSUE TITLE
There should be a recipe for clean water using water purifier

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#22315]
As it is 3x more energy efficient, but now requires lots of manual effort to use, especially for batch processing.

**Comment by ZhilkinSerg** [comment]
Unmodified water purifier can purify up to 100 pieces of water in single container. Using recipes will allow up to 20 pieces of batch crafting.

Also batch processing without limits is already possible with vehicle water purifier - `FOODCO kitchen buddy` is your buddy!

**Comment by Tsunder** [comment]
using crafting would allow specifying how much water to purify, rather than the whole container or nothing. this is most notable with containers that have over 100 units of storage (>20L of storage) (or over 200 w/ extra battery mod, or more with others. but these are workarounds for the fundamental problem)
