### ISSUE TITLE
toaster pastries are too entertaining

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#22354]
Game version: master
Cooked toaster pastries are 30 enjoyability each (+5 for being hot), those stack to 90. It's even more than some serious drugs. I'm not sure if it's intended, as all the other food is a lot less fun.

**Comment by Coolthulhu** [comment]
Here are 50 most fun foods:

<details>
<summary>Big table</summary>

Food | Fun
--- | ---
crack | 50
heroin | 50
toaster pastry | 30
s'mores | 30
marloss berry | 30
marloss seed | 30
marloss gelatin | 30
mycus fruit | 30
cake | 30
methacola | 30
low-grade methamphetamine | 30
toast-em | 25
cocaine | 25
pink tablet | 25
morphine | 25
Irish coffee | 20
Long Island iced tea | 20
screwdriver cocktail | 20
wild apple | 20
rum & cola | 20
nachos with meat and cheese | 20
niÃ±o nachos with cheese | 20
pudding | 20
cake | 20
cake | 20
fancy hobo | 20
kalimotxo | 20
bee's knees | 20
whiskey sour | 20
spiked eggnog | 20
Xanax | 20
tequila | 18
imperial stout | 18
cooked corn dog | 18
toast-em | 18
glazed tenderloins | 18
oxycodone | 18
single malt whiskey | 17
pinot noir | 16
dandelion wine | 16
nachos with cheese | 16
nachos with meat | 16
niÃ±o nachos | 16
riesling | 15
chardonnay | 15
cabernet sauvignon | 15
whiskey | 15
vodka | 15
gin | 15
rum | 15

</details>

Glazed cake, toaster pastries and s'mores are meth. Toastems are cocaine. Pudding and cake is better than best wines.

**Comment by Theundyingcode** [comment]
tost 'ems come up as 75 in my eat menu... I always have gourmand though.

**Comment by Headjack** [comment]
Sweets being better than drugs is obviously wonky, but nice foods as a whole are almost pointless in my experience. The short duration of the morale boost isn't worth the very common drop in filling-ness compared to basic foods like cooked meat and bread. They should have a much lower, but extremely long lasting buff to happiness, maybe 24 hours or so, to encourage a pleasant menu daily and occasional indulgence on sweets.

**Comment by FulcrumA** [comment]
Probably it shouldn't be the food values that'd be balanced but the cumulative morale benefits from eating them, especially when combined with the point @Headjack makes.

**Comment by Dragometh** [comment]
> ...but nice foods as a whole are almost pointless in my experience.
hey, I just KNOW you have a favorite food that when you eat you stay at least happy for an hour or so

> The short duration of the morale boost isn't worth the very common drop in filling-ness compared to basic foods like cooked meat and bread. They should have a much lower, but extremely long lasting buff to happiness, maybe 24 hours or so, to encourage a pleasant menu daily and occasional indulgence on sweets. 

I think the boost should still be short-lived, but nerfed in terms of morale boost and the accumulation of such. You don't stay happy for an entire day after eating a bar or two of chocolate, no. No one does, I think.
Either way, I think there should be some drawbacks too, like some hunger pangs when constantly eating sugary foods. Or maybe just getting nauseous of eating too much sugar in a short time.
The drawbacks on eating poorly is already reflected on health, and IMO there should be some morale debuffs on bad health because of the IRL consequences (stomach aches and such), but that is another issue.

**Comment by Headjack** [comment]
Rather, I think that the fact you have a pleasant diet overall should be what you're happy about, instead of enjoying the one meal a bit for the time being. Cake once between wastebread meals is a lot different than steak and soup every day for a week.

It almost feels like this is still geared for the old focus system where you banked the enjoyment forever to develop into skill points.

**Comment by l29ah** [comment]
Does the "focus" thing even influence anything these days?

**Comment by Night-Pryanik** [comment]
Focus directly affects the speed at which skills are trained. More focus - faster skill training.

**Comment by l29ah** [comment]
Does it include skill gains from reading?

**Comment by Night-Pryanik** [comment]
Yes, of course. Skill training from all sources benefit from high focus.

**Comment by Headjack** [comment]
Like, what I do is just eat my nasty food before bed. That way I don't care by the time I wake up. That doesn't sound like what should happen either. 

You should have a running tally of how we you've been eating that determines the value of a constant buff/debuff. Regularly eating tasty food reinforces their buff in height and duration, and conversely eating nasty food lowers it for some period and strength, on top of the immediate unpleasantness of eating it.

Think of it like a line graph. So, if you eat good enough stuff like meat sandwiches, TV meals, raw fruit, you get a small enjoyment hit at once, then they pay into your running tally to get you a constant, like, +5 morale. That's like what you get from Stylish. If you suddenly eat a cow pie or mutant fetus, you suffer the short term unenjoyment dip it regularly gives you, and it negatively influences your tally by some amount for some duration. So, the next 15  hours you are at -20 instead of +5, then it tapers off to -10, and vanishes as you get on with your life. Improving your diet to lasagna, pizza, high-end soup, with occasional treats like pie and candy improve your constant buff to +20 for however long you can maintain that, because you have constantly reinforced the duration and strength of those high-end values that it will last even if you have sandwiches every so often, that would just cause you to have a mere +17 for a bit, but suddenly eating a fetus still ruins your day and bottoms it out with extreme negative strength and a middling duration.
