### ISSUE TITLE
Windows tiles build is being aborted.

### ISSUE THREAD

**Issue by Chezzo** [CleverRaven/Cataclysm-DDA#22359]
Paging Mr. @Narc0tiq.

The windows tiles build is being aborted, possibly because it is taking too long to compile? 

The only windows tiles link on the website goes to that, instead of the 64 version.

**Comment by narc0tiq** [comment]
It got aborted once, yes, because it took more than 60 minutes to finish. However, it's also been broken for a couple of weeks (see also <https://github.com/CleverRaven/Cataclysm-DDA/issues/22233#issuecomment-340635469>), which is a little more relevant.

I honestly can't keep checking why things fail when literally every build fails. So unless someone fixes the build, I'm going to have to turn off the 32-bit Windows builds (at least the Tiles builds) -- then I can know that when I get a failure warning, it's a legit failure.

**Comment by narc0tiq** [comment]
The build after the one reported didn't time out, so I'm closing this. It did fail, but it was because it ran out of disk space -- a problem whose resolution is being tracked in #22386.
