### ISSUE TITLE
Add (in)sanity traits from long-term morale changes

### ISSUE THREAD

**Issue by notafed** [CleverRaven/Cataclysm-DDA#22372]
To improve the effect of the morale system, perhaps an invisible "mental health" or "sanity" stat should calculate long-term morale changes, and may give the player character "mood traits" according to how well they manage or adapt to the stress of the apocalypse.

Instead of simply decreasing "focus" in the short term, the following traits can be gained as a long term punishment or reward, getting progressively worse or better as the player adapts:

The Good:
- accomplished sleeper
- addiction resistant
- optimist
- indefatigable

The Bad:
- insomniac
- mood swings
- bad temper
- languorous
- addictive personality
- nightmares?

The Ugly:
- chemical imbalance
- psychopathic
- and eventually, schizophrenic

The intention is to make the morale system more significant outside of simple XP gain, while also giving it more flavor or personality as a hardened survivor adapts to their chaotic world.

Imagine after the months or years of butchering countless zombie children and the burning of mass graves, the insomnia, nightmares, drug abuse, and eventual depression or schizophrenic hallucinations the survivor may have to battle with. This detail should give the game a better taste of emergent narrative from player performance alone... and fighting the hallucinations can be entertaining. :P

**Comment by Treah** [comment]
Psychopath is a positive trait tho..

**Comment by Barhandar** [comment]
>Psychopath is a positive trait tho..

And schizophrenia is _impossible_ to get without genetic predisposition (or mutation, as can be the case in CDDA). Someone without it will get other mental issues from equally traumatic experiences (depression, anxiety, PTSD, etc). Conversely, it cannot be cured, though the sufferer can become better at managing the symptoms or suppressing them via medication.

What this will likely be, is a _complete nightmare_ to balance and to make it not ruin player experience by sheer accident, or give too much benefit. And I think it needs a separate set of traits as well instead of co-opting existing ones.

**Comment by kevingranade** [comment]
I'm quite interested in splitting morale into a long term effect (still called morale) and a short term effect (probably called mood).
Both would be visible, I don't see a reason to hide them.
Some of the traits you call out would work for good or bad morale, some (that @barhandar called out) would not.

**Comment by Night-Pryanik** [comment]
Closing as per lack of discussion.
