### ISSUE TITLE
CI Build server is out of disk space

### ISSUE THREAD

**Issue by BrettDong** [CleverRaven/Cataclysm-DDA#22386]
Cc @narc0tiq 

Recent builds are failing because there's no available disk space left on the server.
```
17:11:56 Receiving objects:   0% (1/293084)   
Receiving objects:   1% (2931/293084)   
Receiving objects:   2% (5862/293084)   
Receiving objects:   3% (8793/293084)   
Receiving objects:   4% (11724/293084)   
Receiving objects:   5% (14655/293084)   
Receiving objects:   6% (17586/293084)   
Receiving objects:   7% (20516/293084)   
Receiving objects:   8% (23447/293084)   
Receiving objects:   9% (26378/293084)   
fatal: write error: No space left on device
17:11:56 fatal: index-pack failed
17:11:56 
17:11:56 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1924)
17:11:56 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1643)
17:11:56 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$300(CliGitAPIImpl.java:71)
17:11:56 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:352)
17:11:56 	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:815)
17:11:56 	... 11 more
17:11:56 ERROR: Error fetching remote repo 'origin'
17:11:56 Retrying after 10 seconds
17:11:56  > /usr/bin/git rev-parse --is-inside-work-tree # timeout=10
17:11:56 Fetching changes from the remote Git repository
17:11:56  > /usr/bin/git config remote.origin.url git://github.com/CleverRaven/Cataclysm-DDA.git # timeout=10
17:11:56 Pruning obsolete local branches
17:11:56 Fetching upstream changes from git://github.com/CleverRaven/Cataclysm-DDA.git
17:11:56  > /usr/bin/git --version # timeout=10
17:11:56  > /usr/bin/git fetch --tags --progress git://github.com/CleverRaven/Cataclysm-DDA.git +refs/heads/master:refs/remotes/origin/master --prune
17:12:06 ERROR: Error fetching remote repo 'origin'
```

another log:
```
17:12:02 Makefile:710: recipe for target 'objwin/tiles/editmap.o' failed
17:12:02 make: *** [objwin/tiles/editmap.o] Error 1
17:12:02 make: *** Waiting for unfinished jobs....
17:12:06 src/item_factory.cpp:2473:1: fatal error: error writing to /tmp/ccLVLOJf.s: No space left on device
17:12:06  }
17:12:06  ^
17:12:06 compilation terminated.
17:12:06 Makefile:710: recipe for target 'objwin/tiles/item_factory.o' failed
17:12:06 make: *** [objwin/tiles/item_factory.o] Error 1
17:12:07 Build step 'Conditional step (single)' marked build as failure
17:12:07 SSH: Current build result is [FAILURE], not going to run.
17:12:07 Recording fingerprints
17:12:08 IRC notifier plugin: Sending notification to: #CDDA-dev
17:12:09 Finished: FAILURE
```

**Comment by narc0tiq** [comment]
Thank you for the @ mention.

Yes, I was investigating that before I saw this -- somehow, a single build managed to eat 20G of disk space! The reason for it seems to have been that the `.git` folder for the inner jobs (windows-curses, linux_x64-tiles, etc.) kept increasing in size with each subsequent one -- the first was about 1 GB, the second was almost 2 GB, and so on -- which rapidly exhausted available disk space.

Since I know that Git can, when cloning, reuse objects from a copy of the same repo on the same disk, I just had to check if I had it set up that way (remembering that, in a previous incarnation, I did). Turned out the reference repo wasn't set. I still can't explain why each subsequent build's `.git` kept getting bigger and bigger (and due to the size, I couldn't just keep them around), but I'm guessing it's something idiotic Jenkins tried to do, perhaps to speed things up.

So what I just changed was to set the top-level `.git` to be the reference, so that all objects in the sub-builds' repos should be hard-linked to objects in that top-level folder instead of redownloaded. This so far seems to have worked, with the working directories of the two inner jobs currently running occupying less than a third of the disk space the top-level `.git` does. I will, of course, keep monitoring [build 6917](http://ci.narc.ro/job/Cataclysm-Matrix/6917/) until I find out if it's fixed or not.

**Comment by narc0tiq** [comment]
It did succeed, mostly -- at least, it didn't run out of disk. One of the sub-builds didn't finish (timed out), but ccache helped it on the second attempt (in build 6918).

On that note, I'm also restricting the builds such that:
- Linux_x64 + Curses *must* succeed for the build to continue, and
- Only one sub-build will be done at a time (hopefully speeding things up by using less resources)

**Comment by kevingranade** [comment]
Both sound like good ideas, we drive enough rebuilds of PRs that it'll usually be somewhat parallel anyway.
Thanks as always for your support.

**Comment by narc0tiq** [comment]
The machine really doesn't have the resources to build two Cataclysms at the same time and still remain responsive (goes into I/O death), and the PR builds can't build at the same time anyway (because of the need to check files against the reference repo). I'm just aiming for reliable and reasonably fast -- and it still takes 26 minutes to "rebuild" all eight variants with a fully primed ccache (no changes between builds).

I'm actually considering dropping win32, but I think folks still use it a fair bit.

**Comment by BrettDong** [comment]
Something a little tangent:

I found that building Cataclysm with GCC can consume a lot of RAM. When I
was building it on my 1GB RAM VPS yesterday, it ran out of memory: 'memory
exhausted'. I manually added a temporary swap file and observed that the
peak memory usage of cc1plus reached 1.7GB when compiling mapgen.cpp. So
when you are running some parallel builds simultaneously, RAM resource must
be taken into account.

**Comment by narc0tiq** [comment]
Yeah, the new build machine is a 4 GB VPS, which would technically be enough for at least a `make -j2` -- but it was trying to do two of them at a time, which mostly worked, but slowed things down greatly (it didn't dip into the swap space much, but there's a lot of I/O involved in the compiles, too -- and that did impact even the other machines on the same host).

**Comment by narc0tiq** [comment]
Also, I think we've got the disk space problem resolved, a `du -sh` says:
```
951M    cataclysm-reference-repo/.git
3.6G    cataclysm-reference-repo/platform-builds
```

That's been pretty stable the last couple of builds (plus the build time's likely improved, partially due to a bigger `ccache` max size), so I'm going to call this one done. Please do continue to @ mention me on build issues in future, too-- it really does help.
