### ISSUE TITLE
Strnlen Compilation problem [COMPILE,CLANG]

### ISSUE THREAD

**Issue by MagicToster** [CleverRaven/Cataclysm-DDA#22443]
Game version:"0.C-25055-gb94c476f73-dirty"

Operating system:FreeBSD 11.0-RELEASE-p12

It's compilation problem with filesystem.cpp and #include <string.h> ( I think ), I use FreeBSD clang version 3.8.0. I don't know what exactly is wrong but when try to gmake, I got

src/filesystem.cpp:215:28: error: use of undeclared identifier 'strnlen'
    auto const len_fname = strnlen(entry.d_name, sizeof_array(entry.d_name));
                           ^
I check if  <string.h> even work on my Os, and it work. Anyone know what is wrong ?

**Comment by kevingranade** [comment]
Historically, the freebsd developers have had a bug up their collective asses about strnlen.
http://freebsd-hackers.freebsd.narkive.com/qORUKIgr/where-is-strnlen
I can't find the current state of things, but it's possible that freebsd does not include it by default and requires an extra flag or something.

I also note that it is not officially a part of the c++ standard, so that exclusion is technically correct.

Solutions:
* Add a BSD-specific build flag here: https://github.com/CleverRaven/Cataclysm-DDA/blob/b4780c2f60957c5eb9fe2c7be06cd8a7b06ba16f/src/filesystem.cpp#L35 to define it locally on bsd.
* This is the only place it is used in our codebase, so perhaps we should just:
  * refactor the code to make it unecessary.
  * if it's really necessary here, just inline the definition in the one place it is used.
