### ISSUE TITLE
Should vehicle boards be classified as roofs?

### ISSUE THREAD

**Issue by angoddu** [CleverRaven/Cataclysm-DDA#22590]
I am working on a patch that will make it so that vehicle parts will provide locations for other vehicle parts. So, for instance, for solar panels they must be installed on a vehicle's roof. It would make sense that there must be a roof for the solar panel to be installed on. Most pre-generated vehicles don't have roofs over the edge boards. 

Should the boards be classified as roofs for the purposes of installing parts? I mean full boards and not half boards.

**Comment by RedPine91** [comment]
Yes, since they function as walls (full boards) for purposes of LOS and hp.  It would be silly to add a roof on top of a wall, since the number of parts installable on a single tile is already pretty long.  Adding a roof on top of a wall would also effectively increase the hp of that tile by quite a bit, which would make balancing vehicle sturdiness harder.

**Comment by Night-Pryanik** [comment]
Closing as per lack of discussion.
