### ISSUE TITLE
No Cure mod

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#22618]
Feature suggestion:
When infected bites were added, they were carefully balanced based on their inclusion being mandatory and not unduly disrupting the game.  However some people might prefer a more challenging and thematic impact for zomie bites if they opt into it, i.e. the No Cure zombie infection as featured in many zombie movies.  A zombie bite won't be an instant death, but it will be certain, leaving the player to either quit or live out the remainder of their game with no hope of recovery.

Implementation should be fairly simple, add a set of effects parallell to the deep/infected bite effects, sharing most of the same code, with the only difference being that the new effects are not added to the effects of items that cure regular zombie bites.  This would include all treatments chemical and physical, as well as the periodic chance of natural recovery.

**Comment by Headjack** [comment]
That system is my least favorite part of Project Zomboid, though it makes sense with that game's style; hopelessly hiding as long as possible("this is the story of how you died"). I feel that Cata is a more bombastic and larger than life, given the wild zombie types and bizarre aliens, artifacts, and laser guns.

 When I play Zomboid, that system leads to a very sedentary playstyle that mostly focuses on avoidance and fortification. I've played games of Cata like that too, and I think Cata's many systems give a better experience for it than Zomboid, it's still missing out on a great deal of the features and content. Playing a more normal way under such a system would certainly see you infected within a few days, cutting yet shorter a game already meant to be played with permadeath. It's not unthinkable, but it would definitely curtail such a player's options given the sheer deadliness of being anywhere near zombies if they wanted to stay alive, and make things even quicker if they are just sprinting around wildly. Plus, it seems to raise questions regarding the lore, and what would be happening to NPC companions if they were bitten.

Now, I know I diverge with common sentiment regarding lore surrounding the source of zeds and the nature of infection; my understanding of it from the past is that the player and all NPCs are the small portion of humanity that are naturally immune to the zombifying capacity of the extradimensional goo organism, and everything is already exposed as can be(as seen in the lab logs about it getting into the water). This explains why NPC and found-in-game corpses never become zeds, and you never find your own zombie if you locate your former character from a graveyard file. If, as some say, exposure to the goo will only zombify people after death, then it seems unlikely that all of society would have collapsed worldwide rather than understanding to destroy their dead.

That said, a negative trait for something like "no immunity" would be somewhat interesting. Much like you describe, with an additional potential hazard from blobs and unboiled water. I'd probably give that a try, especially if you managed to replicate the higher chance of infection given an existing wound when fighting particularly goo-y enemies, like blobs or the husk zed. It'd also be rather fun if you became a survivor zombie or similar upon death if another character finds them. The only thing I'd have to ask is whether a normal bite along existing lines would always be zombie-infecting or if it would merely be a chance. I think Zomboid plays on that, turning it into a fear about whether a particular bite is superficial, merely a mundane infection, or the real thing, especially with their hypochondriac trait.

**Comment by DChieh1** [comment]
I dislike the idea of No Cure bites as well. It might be interesting to make it a much more dangerous infection that will require far more requirements to cure, but having an instant Game Over feels pretty cheap and ends up heavily biasing for certain playstyles such as eternal rangedness. If it, for example, required an amputation which could only later be countered with Mr. Stemcell or bionic limbs, that'll be responsive and interactive as opposed to an instant Q.

**Comment by anonymous6936** [comment]
Sent from Yahoo Mail on Android 
 
  On Sat, Dec 16, 2017 at 12:28 AM, DChieh1<notifications@github.com> wrote:   
I dislike the idea of No Cure bites as well. It might be interesting to make it a much more dangerous infection that will require far more requirements to cure, but having an instant Game Over feels pretty cheap and ends up heavily biasing for certain playstyles such as eternal rangedness. If it, for example, required an amputation which could only later be countered with Mr. Stemcell or bionic limbs, that'll be responsive and interactive as opposed to an instant Q.

**Comment by anonymous6936** [comment]
Sent from Yahoo Mail on Android 
 
  On Sat, Dec 16, 2017 at 2:53 AM, Anonymous Me<anonymous6936@yahoo.com> wrote:   

Sent from Yahoo Mail on Android 
 
  On Sat, Dec 16, 2017 at 12:28 AM, DChieh1<notifications@github.com> wrote:   
I dislike the idea of No Cure bites as well. It might be interesting to make it a much more dangerous infection that will require far more requirements to cure, but having an instant Game Over feels pretty cheap and ends up heavily biasing for certain playstyles such as eternal rangedness. If it, for example, required an amputation which could only later be countered with Mr. Stemcell or bionic limbs, that'll be responsive and interactive as opposed to an instant Q.

**Comment by kevingranade** [comment]
I guess it's not clear that this would be a mod and therefore opt-in?  I would definitely not push for this being the default.

**Comment by ZenZen2** [comment]
I love that suggestion. I would also like a different mod that cause infection on like every 2nd or 3rd bite. And no, i wouldnt combine them together in one game :)

**Comment by ZhilkinSerg** [comment]
I've just made a PR with lua-modification for that - #22631.

**Comment by sniperm13** [comment]
I wouldnt mind this mod and itll up the ante when against zombies in the game. I do have a few questions/concerns.

firstly, based on the description as i understand it, zombie bites are instantly "fatal". in zomboid, as was compared to, it isnt the case. bites arent fatal, infection is. so my question is, are you planning on making bites instantly "fatal" or is it a chance thing as in the infection has to set in? (i prefer the latter)

my only other concern is this mechanic cant apply to all of the creatures, or will it?

**Comment by ShadowDragon8685** [comment]
I don't really see the point of modeling the zombie virus, but I guess there's no harm in including it provided that it's an optional add that is not selected by default (the way Filthy Clothing is.)

It would definitely be enragingly frustrating if it were made standard, especially without saves and reloads.

**Comment by aeoo** [comment]
I personally wouldn't play with it, but since it's a mod, why would I be against it?  If someone thinks is a fun way to play, why would I try to block it?

I don't understand why would the issue even arise except maybe if the mod list is growing too large and now we're running out of space for the mod list and therefore have to decide which mods belong on the list.  As long as the list is manageable and it's a mod, as far as I am concerned, even if it's just 5 other people who like it, it should be added right away.

I'm trying to think why would I *not* want this mod and my only other thought is that maybe this mod is somehow extremely maintenance-intensive and that effort is better spent elsewhere, but it doesn't seem like it.  Based on my superficial understanding I guess the mod is pretty light-weight?

**Comment by kettleswordfang** [comment]
what about an infected zombie bite just never healing? so makes your new max for that `||||\ instead of `|||||`?

**Comment by TinkerWorX** [comment]
@kettleswordfang I kinda like that idea too. Couple it with some sort of special action you have to do. "Cut away the zombified flesh", which requires a certain amount of painkillers just like CBMs, and results in a deep wound you need to tend to afterwards too. The amount you have to cut away depends on how long you've gone untreated. If we model it on a body part, it could be something like this:

An arm has max 80 hp normally. Along with the arm hp, there's an arm infection counter which is normally 0. On an infectious bite, the infection counter is increased by 2-6 and you're now dying of infection. Each hour you go untreated, the infection counter is increased by 1-4.

Using the "Cut away ..." action, you reduce your arm infection counter **and** max HP by 2-6. Once the infection counter is reduced to 0, you're safe again, but have potentially reduced your max hp by bunch.

Death would happen if any vital body part (head, torso) is 100% infected. If an infection in an arm or leg goes above 25%, there's a chance it'll spread to the torso every turn.

All this would obviously need to be checked for balance and some skill synergy would be nice like high first aid means the amount you cut away is less random and closer to how much you actually have to cut away to get healthy. The painkiller requirement is also a nice stress factor since you need to hit the pain killer threshold to do it, but the longer you wait the more you need to cut away.

**Comment by sniperm13** [comment]
Kinda reminds me of dying light. speaking of, that could be a good model too. bite=insta-infection so youll need antibiotics to stay alive. XD and since theyre kinda rare outside of labs and hospitals, youll be forced to raid those dangerous places to stay alive.

2 pills per day should do it. id play that actually. :)

**Comment by CoroNaut** [comment]
Its basically an iron-man mode, if you get biten, you die, you restart. If this is exactly what is meant for this mod, then it should just be implemented as an option for the base game instead of being a mod.

**Comment by Ystyr** [comment]
I think a hard cure mod would be better than that. It would be nice if the cure would be possible, but difficult to get.

**Comment by Isaacssv552** [comment]
I would prefer a Hard Cure mod, but as long the behavior remains toggleable I have no objections.

**Comment by ThomasLinkin** [comment]
is this idea still on ? i think this one is really good for those "Challenge Accepted" out there. but what if you have to ampute your limbs instead of just dying ? if this idea works, and my idea is through, i suppose the game will have the limb amputing as well
