### ISSUE TITLE
Filthy Go bag leads to filthy electronics, and filthy components

### ISSUE THREAD

**Issue by Stephen2** [CleverRaven/Cataclysm-DDA#22622]
Game version: 0.C-25438-g7acb622

Operating system: Win 10x64

Tiles or curses: Tiles

Mods active:
* Standard ones
* StatsThroughSkills

### Expected behavior
Maybe only the clothes in the go bag should be filthy?

### Actual behavior
Disassembling the filthy go bag leads to filthy parts, even at the component level... Seems wrong?

### Steps to reproduce the behavior
* Get filthy go bag
* Disassemble
* Get filthy flashlight
* Disassemble
* Get lightstrip (unpowered) (filthy)
* Can't use it to craft lightstrip (unpowered) :(

**Comment by Night-Pryanik** [comment]
I think that go-bag should be either changed from crafting and disassembling to its own function, or even entirely removed from the game.

**Comment by aeoo** [comment]
>Disassembling the filthy go bag leads to filthy parts, even at the component level... Seems wrong?

I get where you're coming from and to some extent I agree, but what you're witnessing was intentionally designed that way in order to avoid players carving up filthy gear for clean components (like cutting or disassembling a filthy pair of cargo pants into clean rags).  The idea of filthy mod is to make clean anything much more rare.  There is still plenty of clean gear anyway, but clean components and gear is no longer literally walking up to your player character.

I personally can see it working both ways.  It depends on why the gear is unclean.  For example, if the zombies secret mucus and the go bag is just rugged cloth, the mucus will seep into it and eventually cover all the contents.  It will also seep into the electronic gear inside the go bag and cover all the microchips and such.  That's if the uncleanliness is a result of mucus secretions, which seems reasonable to me.  But if it's not mucus, maybe the contents of the go bag should be clean?  I think that would be fine as well.

**Comment by Solusphere** [comment]
I've run into this problem. What makes it more annoying is that washing an entire go bag before dissassembly requires something like 48 detergent to accomplish, aka nearly two and a half whole boxes. This seems a little ridiculous to me.

**Comment by Night-Pryanik** [comment]
> I've run into this problem. What makes it more annoying is that washing an entire go bag before dissassembly requires something like 48 detergent to accomplish, aka nearly two and a half whole boxes. This seems a little ridiculous to me.

Required amount of soap/detergent is calculated based on filthy item's volume. Go bag has outstanding 35,75 liters of volume (survivor duffel bag has only 7,5 liters, for comparison), so a significant amount of cleansing agent is required.

**Comment by ShadowDragon8685** [comment]
I think that the contents of the Go Bag, save the resultant Duffel Bag and the Backpack (which are the external items,) should probably come out clean. I can see why they aren't, but it's a little silly since they're actually the contents of a container which should protect them from getting zombie filth on them.

I think this is probably an artifact of the way Go Bags are disassembled into components. This would also hold for, say, finding an MRE on a zombie soldier - why would the contents of a sealed pouch get zombie filth all over them, unless the pouch itself was ruptured?

Perhaps Go Bags and MREs should be moved to [A]ctivated items? And if they're found Filthy, only the exterior container should be filthy.

**Comment by Night-Pryanik** [comment]
> Perhaps Go Bags and MREs should be moved to [A]ctivated items? And if they're found Filthy, only the exterior container should be filthy.

This. 

Though it's hard to find filthy MRE since filthiness only applies either to armor/clothing or components from a disassembled filthy item, and MRE neither armor nor a component of some other item.

**Comment by ShadowDragon8685** [comment]
> Though it's hard to find filthy MRE since filthiness only applies either to armor/clothing or components from a disassembled filthy item, and MRE neither armor nor a component of some other item.

Okay, it doesn't really apply to MREs, that was more relating to MREs being a thing you should activate to get at the contents of, rather than disassemble.

**Comment by CoroNaut** [comment]
Instead of having a bag which uses crafting to look through, how about it be removed and a new bag item that can contain any list of things but reduce encumbrance by a little bit, perhaps make the weight of items in bag be multiplied by 80% or so. It really seems pointless to have a bag that must be crafted with specific items.

**Comment by ShadowDragon8685** [comment]
Why would the weight of the items in the bag be reduced by 20%? Magic? That's not likely to happen.

Now, reducing volume by, say, vacuum packing a bunch of loose items together and sealing them up? That's quite theoretically possible.

However, the reason for "Go Bags" and MREs to exist is because those are things people make; a bag full of the stuff you might need if you have to grab your stuff and go in a hurry - hence, "Go Bag." MREs are sealed pouches.

Using the crafting interface to uncraft them to get their parts out was perhaps not ideal, but you *do not craft them in the game.* It's strictly a matter of item disassembly being used - possibly inappropriately - to allow the player to unpack prepackaged goods.

**Comment by Mooses2k** [comment]
I think there's no problem here. Filthy means filthy. For instance, this zombie was lying in the street during the acid rain and it got EVERYWHERE.
