### ISSUE TITLE
Chainsaw is inferior to wood axe

### ISSUE THREAD

**Issue by DChieh1** [CleverRaven/Cataclysm-DDA#22659]
Game version: o.C-25440-g217f504

Operating system: Windows 10

Tiles or curses: Tiles

Mods active: PK

### Expected behavior
Activated chainsaw uses gasoline and is significantly more rarer than wood axe. It should have tree cutting 3, or 4 to compensate for its rarity and/or difficulty in construction.

### Actual behavior
Woods axe is tree-cutting level 3, and as a hand tool is superior to powered tools. 

### Steps to reproduce the behavior
Standard behavior in game.

**Comment by Alkheemist** [comment]
I don't think the cutting level change would help since the tree felling construction checks for a tool with at least that level and then takes a set amount of time. I don't know if there is a system for dynamically scaling the speed of construction with the quality of the tool

**Comment by ShadowDragon8685** [comment]
I do agree, though, a chainsaw should be far superior to a hand tool; and a vehicular version should be both available, and far, _far_ superior to either.

**Comment by kevingranade** [comment]
While the chainsaw *should* be faster at felling and processing trees, your argument is invalid:
> It should have tree cutting 3, or 4 to compensate for its rarity and/or difficulty in construction.

Rarity or difficulty in construction don't imply anything.

**Comment by DChieh1** [comment]
It encourages more exploration/risk if rarer items are more rewarding, and if items that have limited fuel such as gasoline are more effective than infinite-use items.  At any rate, having a good set of powered tools should give some sort of a sense of accomplishment, much like having a good set of metal tools in the game.

**Comment by sphdj** [comment]
I think the wood-cutting attribute is related to crafting and construction capabilities, where level does not correspond to time consumed during an activity, but instead is a label showing how effective, or how precisely a tool can be used to craft. I would agree that eventually a system would need to be implemented to add an efficiency stat that would determine the amount of time it takes to complete a task, but I wouldn't be sure if that would be the most efficient solution in terms of coding as we don't want to make the game files have to process more information than they need to. Plus adding efficiency would likely require a crafting overhaul of some kind.

**Comment by DChieh1** [comment]
I don't think there's any need to introduce a different system for efficiency; butchering speed is already related to butcher quality to my understanding. If it needs to be component of a recipe, just create a "fine woodworking" quality instead, much as there is a fine hammering quality.

**Comment by Alkheemist** [comment]
The butcher mechanic and the construction mechanic are different parts of code entirely and in any case, as far as I know butchering quality affects what you can get from butchering, not it's speed.

A good example of how an efficiency mechanic would work would be resawing a log into planks with a hand saw and with a chainsaw. The chain saw should obviously be faster, but the only way to currently implement that is to have two different crafting (or construction) recipes that explicitly call out each tool and have different durations. However, this means that if Urist McModder adds a chainsaw bayonet and wants it to be possible to resaw wood with it, they would have to find and edit those recipes.

The alternative method would be that some tasks require a certain level of tool quality that specifies what is possible with the tool and also look at a tool's "efficiency" to scale the time of the operation. I think a PR was already made something along those lines but the issue is that this is not a trivial change. It would definitely require a crafting overhaul.

**Comment by Night-Pryanik** [comment]
#21628 is meant to deal with the issue.

**Comment by ShadowDragon8685** [comment]
> However, this means that if Urist McModder adds a chainsaw bayonet and wants it to be possible to resaw wood with it, they would have to find and edit those recipes.

This is not actually the case, @Alkheemist 
If you make the recipe for wood-sawing-by-chain-tool call for a tool with, say, Chainsawing X quality, then _any_ tool with the Chainsawing quality ≥ X will be able to use that recipe, whether it's an activated chainsaw, an activated chainaxe, a chain-bayonet, or a chainsaw-lajatang.
Of course, you will have the problem that if the player has, say, a fireaxe upon their person or within reach, they'll still see both recipes active in the menu at once, which is probably unideal, since if you have an activated chainsaw, you probably don't want to run the battery/tank dry by idling the tool whilst cutting wood with an axe.

_Ideally_, the time taken to perform laborious, repetitive tasks which can be sped up by more vigorous activity and more efficient machinery would, in fact, achieve faster speeds based upon the equipment the player had to work with and the skill of the character. Logging by hand would take a hella long time; logging with a wood axe should probably be a little faster than logging with a fire axe, whilst logging with a chainsaw should be faster than both; logging with a vehicular mounted, articulated chainsaw boom should be _hella_ fast: https://www.youtube.com/watch?v=luygMuoFnXs
