### ISSUE TITLE
Should be able to unfold items even if too heavy to pick up

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#22771]
Game version: 0.C-2557

Operating system: windows 7

Tiles or curses: Tiles

Mods active:

Dark Days ahead
filthy clothing
disable npc needs
simplified nutrition
makeshift items
more survival tools
alternative map key
folding parts pack
vehicle additions pack
tanks and other verhicles

### Expected behavior
Activating folded object on ground should unfold it, even if I can't pick it up

### Actual behavior
Says "Too big to pick up"

### Steps to reproduce the behavior
make a bunch of folded frames
craft a foldable vehicle, keep adding frames until it's far enough over your weight capacity that you can't pick it up when folded
fold it
try to unfold it

**Comment by Leland** [comment]
Reworded title slightly to make this a suggestion since it's changing current game functionality

**Comment by kevingranade** [comment]
Folding vehicles are intended to be only tiny person-portable vehicles like a folding bicycle, in which case this issue does not appear.  The weight check failure is working as intended to enforce this limit.

We could make the folding action fail to prevent you from getting into a bad state.

**Comment by Xpyder** [comment]
> Folding vehicles are intended to be only tiny person-portable vehicles 

That's fine, if it's conveyed to the player, but this has never been made clear in any game sense.  Also if this was the intended functionality it should be preventing you from FOLDING it, not from unfolding it.

And there's no way to disassemble a folded vehicle, nor any indication on the vehicle construction screen this is going to happen, making it very easy to permanently loose parts to a mechanic that's never indicated to the player until you end up in an unrecoverable state.

**Comment by Xpyder** [comment]
Also, until hitching is implemented, large folded vehicles is currently the only way to transport a motorbike and van together without spending lots of in game hours rebuilding the motorcycle in every single town you visit which gets tedious

**Comment by Dansiman** [comment]
I always thought it was weird when, at the beginning of the game, I couldn't unfold the emergency blanket because my pockets were full. From a realism standpoint, I could certainly manage, even while wearing several bulky strapped-on containers and holding (wielding) something in my right hand, to unfold a blanket with my left hand (or even my foot). So, weight limits notwithstanding, it should definitely be possible to unfold things that exceed your _encumbrance_ limit without picking them up.

As for the issue with folding vehicles, I'll echo Xpyder's comment that the functionality should prevent folding, and not prevent unfolding, so as to allow those who unfortunately found themselves in this unrecoverable state to rectify the situation, while preserving the intended functionality by preventing them from folding it again afterwards.
