### ISSUE TITLE
Allow the usage of bleach to clean water

### ISSUE THREAD

**Issue by Ska-Riot** [CleverRaven/Cataclysm-DDA#22941]
Title
It's minor, but IRL you can use bleach to purify water, but the option to do so is not in this game.

**Comment by ZhilkinSerg** [comment]
> It's minor, but IRL you can use bleach to purify water, but the option to do so is not in this game.

If bleach contains perfumes or other substances, treated water won't be really `clean`.

**Comment by Ska-Riot** [comment]
Alright, then add in scented bleach too.

**Comment by Beetlecat** [comment]
"Clean" for the purposes of not being parasitic/contaminated. Lavender or Mountain Spring-smelling water seems pretty minor for the capful of bleach added to a giant tank of water. :)

**Comment by kimesik** [comment]
I have a additional suggestion. Most houses will contain scented bleaches and there's will be really low chance to regular bleach appear. Player can unscent bleach by himself, using fire or something otherwise hot enough for cooking, two bottles (one with bleach, other empty) and some time and cooking 1. Scented bleach can't be used to disinfect water, but unscented bleach can be used to create "disgusting water". It is clean as clean water, but adds morale debuff and it much less quenching than clean water.

**Comment by ZhilkinSerg** [comment]
> much less quenching than clean water.

Why? It is exactly the same liquid just with clorine odour?

**Comment by kevingranade** [comment]
https://www.epa.gov/ground-water-and-drinking-water/emergency-disinfection-drinking-water
Also one from the ancient past
https://github.com/CleverRaven/Cataclysm-DDA/issues/72

**Comment by smolbird** [comment]
Do we really need to distinguish between scented and unscented bleach? It already doesn't get in the way of chemical recipes involving it.

**Comment by MattD94** [comment]
Ok I did some thinking:



If you were going to add  a recipe for it, the numbers would be pretty big.
Considering 1 portion of bleach = 0.125L and 1 portion of water is 0.25L:

Assuming that the bleach found in the game has the same concentration as 6% Bleach (e.g. regular bleach such as Clorox Regular Bleach), both the US EPA and Clorox websites say to use 2 drops per quart or 8 drops per gallon, which is 2 to 2.12 drops per liter.

Rounding down to 2 drops per liter and using 1 drop = 0.05mL, then 1 portion of bleach is is 2500 drops
At 2500 drops per portion, each portion of bleach could clean 1250L of water
1250L is 5000 portions of water. You would need 21 of the 60L metal tanks or 7 of the largest container in the game to store all that water.

Since the recommended bleach to water ratio varies slightly depending on how much water you are purifying, its fair to say those calculations are off - especially so with the use of a "drop" as a base unit.

Looking it up online, I've found two different sites stating that 1 gallon of bleach can be used to purify 3800 gallons of water or more, which is approx. 14384.56L
Even if we assume those estimates are too high and round way down to 13250L (approx. 1:3500 bleach to water ratio) that gives us 441.6667L of clean water per portion of bleach

Using this extra conservative estimate that still gives us more than 1700 portions of clean water for every portion of bleach, which is still not very reasonable.

To make it workable you can either add a recipe for diluted bleach which would then be used to purify reasonable amounts of water OR you can change the portion size of bleach to something smaller and adjust existing crafting recipes accordingly.

If you add a diluted bleach recipe and use that for treating water, we need to figure out how much to dilute.
Let's assume we want to use the bleach to purify large amounts of water at a time - since there are already numerous options for small quantities anyway.
Using a target of 100L (common enough, can be stored in wooden barrel, 100L steel drum, 30 gallon barrel, or two 60L metal tanks) and assuming the super conservative ratio of 1 portion of regular bleach for 1700 portions of water:
If we use a diluted bleach recipe of 1 portions of bleach (0.125L) mixed with  9 portions of water (4.75L)
we now have a 4.875L diluted bleach solution.
This entire diluted solution can treat 1700 portions of water, so to get to 100L we need to divide it into 170 portions. Now each portion can treat 100L of water.

Its still a lot of water per portion of bleach, and no matter how you adjust it by tweaking the definition of portion volumes or diluted solutions, the fact remains that you can purify a large amount of water with a very small amount of bleach.

Since bleach is easily found in the game, and it only takes a tiny amount of a single instance of it to purify lots of water, I think it will always throw off the balance of the game.

But that doesn't mean you can't add bleach based water purification without breaking the game balance.

You could simply add a recipe using (what would be lethal) amounts of bleach to purify more manageable amounts of water for the sake of game balance - although I personally don't like this since the main reason to add the recipe in the first place is to be more "realistic." Considering that there are multiple other ways to purify water in the game, I don't think it's usefulness outweighs the oversimplification.

Alternatively, a potentially balanced and realistic solution could be to add a recipe for "inefficiently" crafting water-purification tablets using bleach. I don't know what other ingredients go into water purification tablets aside from iodine or chlorine or the process to make them - or even if making them using bleach is feasible - but someone who knows might be able to come up with a realistic-enough recipe.

Another way to implement it could be to make a bleach-fueled water purification device.
This device would basically be a "smart" storage tank that stores and purifies water using bleach.

Essentially, you put water in the tank and the tank "dispenses" the necessary amount of  bleach to purify the water from a built in bleach reserve.

Sodium hypochlorite breaks down at varying rates according to temperature, concentration, pH, the presence of salt (which is a product of the breakdown), and presence of heavy metals.
Generally bleach has a shelf life of about a year when stored at room temperature and Clorox says to only use bleach purchased in the last 4 months when using it to purify drinking water.

Since bleach in game is certainly not kept at room temperature, and any bleach crafted by the player would still contain large amounts of salt compared to commercial bleach, you can assume in-game bleach has a very limited window where it is strong enough to reliably disinfect water.

This way we can justify that the bleach fueled water purification device needs periodic restocking of fresh bleach, regardless of how much water you purify.

It could be implemented as vehicle part or furniture that has a bleach reserve component that needs to be reloaded after a period of time, and a water tank that gets loaded with water which is then turned to clean water after about 30min in game and can be dispensed whenever.

------------------------------------------------------------------------------------------------------------------
Of course none of this takes into account the fact that using bleach to purify water only disinfects it and doesn't remove toxic chemicals/metals/large particles like boiling and filtering do.

Additionally, treating water with bleach takes longer than boiling or filtering and relying on bleach treated drinking water for more than a few weeks can cause serious health issues.

Regarding the health issues: you could make a "bleachy water" recipe that is something like 1 portion of bleach with 10 portions of water but will make the character sick as if they drank bleach unless they have the poison resistant trait.

**Comment by kevingranade** [comment]
The breakdown process is IMO sufficient, I'm fine with bleach providing a reliable way to mass-disenfect water that only works in the first year of the cataclysm.  
Bleach can simply 'rot' after a year or so and turn into salt water (I don't think we have the transform code in place, but it's not hard).

Considering the ratios involved, I'd propose the bleach acts without being consumed in all but the largest quantities (up to 250l or so), and batches that large just round up, no real need to be precise here, it's effectively limitless if you find just a few bottles of bleach.
However, we can treat this water differently from "proper" clean water, dropping the fun value to account for the bad taste.

If that's not sufficient, we could add water tainted with toxins and more stringent requirements to clean it.

**Comment by Xpyder** [comment]
Another approach is to just make bleach turn water from dirty to poisoned (if we have a mild poisoned version of water)  So you'll get some side effects but it's better than dying of thirst

**Comment by Ska-Riot** [comment]
Only if you're impatient enough to not wait for 30 minutes and/or poured in
too much bleach. It's relatively safe as long as it's not drunk in large
amounts.

**Comment by Ska-Riot** [comment]
And if you have to provide a negative to bleached water, just give it a
small cut to sanity because of the bad taste from the bleach.

**Comment by Xpyder** [comment]
@Ska-Riot As mentioned above scented, color safe, or bleaches with added cleaners are all considered toxic by the EPA (with good reason) and are likely to cause poisoning of some kind.
https://www.epa.gov/ground-water-and-drinking-water/emergency-disinfection-drinking-water

In addition if all bleach was good for cleaning water it would throw off the balance in the game.  But making it cause mild to moderate poisoning allows you to choose to mitigate risk, guaranteed bad effects to avoid the possibility of something worse you can't deal with yet (since if you were far enough to deal with parasites you could probably boil or filter water without issue), without making it the best solution across all times in the game.

**Comment by Night-Pryanik** [comment]
No discussion in over half a year, closing.
