### ISSUE TITLE
Manage NPC's weapons

### ISSUE THREAD

**Issue by SaltGin** [CleverRaven/Cataclysm-DDA#23022]
In current version, NPCs always tend to use the weapon that has the highest dmg in their inventory, whether if they have appropriate skills to use them.
While it is complex for NPCs to judge the weapon they use by judging both the weapon's dmg and their skills, I think players should have the ability to decide which weapon they use in their inventory, not to remove all other weapons that have higher dmg from NPC's inventory instead.

For instance, players can have a new submenu to decide the weapons that NPC use  in the combat command menu:
Weapons rules...
   1. use the weapon I select...
       - select weapons that NPC have;
          disable the original NPC weapon select rule;
   2. use any weapon you want.
        - use the original NPC weapon usage rule;

**Comment by kevingranade** [comment]
Replacing poor so by making the player micromanage NPCs is not ok.

It should be pretty trivial to have NPCs base weapon selection on chance to hit times weapon damage times attack rate so it's at least the best option for damage over time.

**Comment by xcscsf** [comment]
@kevingranade 
I see... But there are still some other problem appeared. When monster closes to NPC that uses ranged weapon, they tend to keep shooting until the gun/crossbow is empty, then the NPC will bash the monster even if they have better melee weapon in their inventory.

There should be a judgement when monsters get close to the NPC, if they have no confidence or enough ammo in magazine to hit them, they should draw their melee weapon and bash/cut the monsters. If NPCs were supported to draw their weapon from the shealth/scabbard, it should be much more effective than reload or bash the monsters with ranged weapon which has slow attack rate.

**Comment by xcscsf** [comment]
Sometimes players should have decision to do some special stratagies, like command NPC use the knife spear to support the player from behind, or use submachine guns to clean the room, and players might want to avoid the noise... I think this kind of micromanagement is essential for NPC's further application...

**Comment by kevingranade** [comment]
There are other problems, and they need to be fixed, but forcing the player to do it is not ok.

**Comment by xcscsf** [comment]
Yeah..I agree.

**Comment by MattD94** [comment]
I think adding the ability to micromanage NPC gear would still be a worthwhile addition eventually.
 
Specific situations or tactics may require different gear - e.g. you would probably want your followers to use a crappy shotgun they have no experience with instead of their high powered anti material rifle when they are badly poisoned & surrounded by giant basement spiders since they will be able to hit easier with a faster aim time even though their rifle actually has a better, yet slower, accuracy and damage.

I think if this option is implemented, the player needs to have the right relationship (i.e. NPC trusts or likes the player or is very intimidated and afraid of the player) or else the NPC wont listen and will choose their own gear.

**Comment by Night-Pryanik** [comment]
No discussion in almost a year, closing.
