### ISSUE TITLE
Tough zombie has both both into and into_group defined

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#23034]
Game version:0.C-7145

Operating system: Windows XP SP3 x86

Tiles or curses:tiles

Mods active: pk rebalance, cata++

### Expected behavior
No errors at game start.
### Actual behavior
![15194031129600](https://user-images.githubusercontent.com/11132525/36610321-effbf1f8-18e0-11e8-95ee-48f0283ade99.png)
### Steps to reproduce the behavior
Start game.

I suppose this is caused by  #22969.

**Comment by tyrael93** [comment]
It's a PK problem.
I fixed that by digging into the pk zombie.json and deleting the tough zombie basic template. Turns out it was redundant.
Tough zombies still spawn, don't give any error messages when dying/hitting/being hit and upgrade as normal.
either tell pisskop or DIY.

**Comment by boydkr** [comment]
Mentioning @pisskop to see if he has any input

**Comment by tyrael93** [comment]
Pisskop himself said that he's not that interested into updating the main mod anymore. 

Also, I've been told this now also happens with monster_mon_ant and monster_mon_ant_larvae now.
Again, it can be fixed by deleting the offending strings. One wonders if it will apply to all monsters sooner or later. It is a bug I don't understand and just indiscriminately cutting down lines isn't really the best way around it.

What is happening to monster spawns?

**Comment by illi-kun** [comment]
So, I guess this issue should migrates to [PKs Rebalancing repo](https://github.com/pisskop/PKs_Rebalancing/issues)?

**Comment by tyrael93** [comment]
a'ght
