### ISSUE TITLE
add ebooks

### ISSUE THREAD

**Issue by ymber** [CleverRaven/Cataclysm-DDA#23154]
Ebooks and digital documents would give the tablet a useful purpose and reduce inventory juggling from a stack of 20+ books. They could be found on terminals in libraries, SD cards, USB sticks, any other appropriate source. Taking what thefnorder was talking about on the discord, it should be partly doable with the digital recipes system.

**Comment by ZhilkinSerg** [comment]
It would be possible to implement this pretty easy with Lua if `BOOK` items contained in other items, provided recipes.

**Comment by SaltatorMortis** [comment]
if this is impemented there should be too a digitize a book option.
i mean book scanner with differing speed and successrates
from manual photographing over V shaped rack with 2 cameras to fullautomatic bookscanner

**Comment by Epictyphlosion** [comment]
I'm also assuming that e-books can only be read on tablets, smartphones, or terminals, correct?

Although, finding e-books would be hard if you could only find them terminals, since just about every terminal in the game is broken by default unless it serves a purpose (Like as a door unlocker in a bank). Something like an e-book that are located SD card or e-book flash drive would work, though

**Comment by MattD94** [comment]
Considering it would be pretty rare to get an e-book without an internet connection, I think this would be just a little unrealistic since there is no internet available. A homemade book digitizer might be workable with sufficient computer and electronics stats, and e-ink tablets could spawn with some non-skill books or they can be saved onto sd cards or whatever. 

But other than making your character's post apocalyptic library more compact and battery dependent, which is neat, I think it might be more hassle than it's worth - especially considering that you toss a lot of books once you read them, unless you have significant skill rust on.

Also isn't Lua going to be dropped eventually?

On the other hand, it may open up some interesting opportunities for bionic upgrades - maybe with the right implant a character can save and read e-books directly in their bionic-enhanced memory/implant.
Perhaps some sort of visual scanning eye implant can be used to scan books directly while reading them so that recipes can be permanently saved (but not necessarily memorized).

**Comment by Night-Pryanik** [comment]
Closing per lack of discussion for a long time and to clean up the issues list.
