### ISSUE TITLE
Prevent monsters from smashing random furniture in Necropolis.

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#23151]
Game version:
ALL

### Expected behavior
Necropolis terrain is relatively undisturbed when player first explores.
### Actual behavior
Monsters smash the various gate winches immediately upon the player arriving.
### Steps to reproduce the behavior
Visit Necropolis.

Brought up in and replaces #23056

**Comment by kevingranade** [comment]
I wonder if this has something to do with monsters inapropriately detecting the player when they are on an upper level.

**Comment by Night-Pryanik** [comment]
Tested the Necropolis on latest experimental as of 04 of April 2021, and it seems that monster movement code was tweaked since time of this issue. I run through the location from ground to lowest underground levels, and monsters didn't break any furniture, even when they were chasing me. I'll close this for now, but if this is still an issue, ping me.
