### ISSUE TITLE
Conditionally hiding or disabling options from settings

### ISSUE THREAD

**Issue by Leland** [CleverRaven/Cataclysm-DDA#23183]
It would be a nice UX improvement to either hide or disable options from the settings menu when other, dependent options are disabled. Here's an example:

`Auto pickup light items` is a setting that only does something if `Auto pickup enabled` is set to true. My proposal, therefore, is to remove or disable `Auto pickup light items` if `Auto pickup enabled` is set to false.

This makes things much more intuitive to the user ("I set Auto pickup light items to true... why isn't it working?") and additionally simplifies the documentation we'd need to provide for each option. No more having to mention, "If setting X is also set to true, then this setting will do Y."

**Comment by CoroNaut** [comment]
Perhaps allow the user to still select the option, and when they try to change the value, have the description box change to tell the user what prerequisites this particular option needs. I am against removing the option though because then a new user may never know that option existed. I like this idea.

**Comment by kevingranade** [comment]
Coloring the text grey and preventing the option from being adjusted should
get the idea across.
