### ISSUE TITLE
alt+f4 closes cataclysm-tiles when another window has focus

### ISSUE THREAD

**Issue by ymber** [CleverRaven/Cataclysm-DDA#23228]
Game version:
0.C-26469-ge9970dde19

Operating system:
Arch Linux 4.15.8-1-ARCH x86_64
xfwm4

Tiles or curses:
Tiles

Mods active:
N/A

### Expected behavior
Cataclysm closes when alt+f4 is pressed while it has focus.

### Actual behavior
Cataclysm closes when alt+f4 is pressed while the window above it has focus.

### Steps to reproduce the behavior
Give cataclysm focus.
Give a different window focus.
Press alt+f4.
Focused window and cataclysm close.

**Comment by illi-kun** [comment]
Can't reproduce this on Windows 10 system, so maybe it's linux specific issue.

**Comment by RustyPotato** [comment]
Confirmed on Linux. Ubuntu 16.04.

**Comment by BevapDin** [comment]
Most likely caused by code in "sdltiles.cpp" line 1280. It checks the current key status and if ALT and F$ are down, it quits the game. This as introduced by 99be2add0d14647b6e6df4c4d7a13be007679e6a, apparently because "old sdl version doesn't support that directly". Note that this was done with SDL 1, we ow use SDL 2, so this code can probably be removed.
