### ISSUE TITLE
Lack of stowboard cornerpieces and heavy duty variant considerably limits their appeal.

### ISSUE THREAD

**Issue by Asmageddon** [CleverRaven/Cataclysm-DDA#23318]
I feel kinda bad opening this issue.. I've actually implemented this myself in the past in a mod + modification of retrodays tileset, but have lost the files since.

While the lack of cornerpieces has no effect on gameplay itself, it makes vehicles ugly if you want to make all your walls stowboards.

On the other hand, the lack of heavy duty variant(less durable than normal heavy duty walls, less capacious than normal stowboards) means that you sadly need to forgo that extra storage space completely, if you want your vehicle as durable as possible.

I know this is a very minor issue, but.

**Comment by MattD94** [comment]
Well if you think about it conceptually, it seems justifiable.
Stowboards are compartments built into the frame/quarterpanel/siding, so the lack of a heavy duty variant makes sense - you  basically have a hollow space where there is normally some other metal. Perhaps there could be a heavy duty variant added that does add some extra durability, but I think it should be noticeably less durable than other heavy duty variants and capacity should be penalized.

As for corner stowboards, I kind of like that there is no corner piece. I think a corner stowboard is a little awkward of a concept - what vehicle in real-life has a storage compartment that opens in the corner? More realistically, if there was a corner storage piece, it would be accessed from openings on side panels on either corner.

Typically I personally don't use stowboards on my vehicles because anything less than a heavy duty frame with lots of armor gets wrecked pretty fast since I play with hordes on and an increased spawn rate. When I do use stowboards, it's in a smaller lightweight vehicle that never gets too close to anything dangerous.

Although a reinforced stowboard part might be a good addition - maybe something with 80-90% of the stowboard capacity and 200-300% of its durability.
