### ISSUE TITLE
Bad strings (typos, missing plurals, incorrect grammar, etc.)

### ISSUE THREAD

**Issue by Wuzzy2** [CleverRaven/Cataclysm-DDA#23393]
Game version:
N/A, strings checked on Transifex on 6th April 2018. Some of the strings below might be fixed already.

Operating system:
N/A

Tiles or curses:
N/A

Mods active:
N/A

### Summary
While translating this game to German, I found a couple of bad strings. Most of the time, the plural is broken.
Please fix the source strings.

Bad plural (remove the final “s” in your source code search):

* [x] spare partss
* [x] steel drum (100L)s
* [x] steel drum (200L)s
* [x] metal tank (60L)s
* [x] metal tank (2L)s
* [x] chime loudspeakerss
* [x] turret chassiss
* [x] pipe SMG: .22s
* [x] pipe SMG: .38s
* [x] pipe SMG: .40s
* [x] pipe SMG: .45s
* [x] pipe SMG: 9x19mms
* [x] bionic goggless
* [x] autonomous surgical razorss
* [x] USP 9mms
* [x] Uzi 9mms

Need differentiation by context (for foreign grammar):

* [ ] Grotesque
    * lang/json/mutation_from_json.py:, src/artifact.cpp
* [ ] Unknown
    * lang/json/material_from_json.py:, src/artifact.cpp:, src/npc.cpp

Other bad strings:

* [ ] Adds a bunch of rare weapons loosely based fiction.
    * Grammar?
* [x] chili_pepper
   * Literally this is the string. Found in `lang/json/COMESTIBLE_from_json.py`
* [x] This is a hand held fire extinguisher containing a liter of highly compressed C02 gas. It would be useful for putting out adjacent fires.
    * It's “CO2”, not “C02”
* [x] This is an active nail_bomb, likely to explode any second now. Better throw it!
    * “nail_bomb”
* [x] に坂索トし荷測のンおク妙免イロコヤ梅棋厚れ表幌
    * NO COMMENT!
* [ ] Is has head.
    * Grammar?
* [ ] %1$s falls tries to climb the %2$s but slips.
    * Grammar?

Please keep this issue open until further notice. I'm likely to add more strings as I progress in my translation.

**Comment by KongMD-Steam** [comment]
Also, this menu doesn't use the plural for 'batteries':
![batteries_plural_bug](https://user-images.githubusercontent.com/36478131/38455279-d2baf092-3a43-11e8-8018-36b8cee001da.jpg)

**Comment by Wuzzy2** [comment]
There are still 5 unticked checkboxes left. Please reopen (unless they are already done).

**Comment by illi-kun** [comment]
@Wuzzy2 to avoid that missunderstanding, please, next time avoid issue with collections of bug. The major rule: one issue - one report.

**Comment by Wuzzy2** [comment]
Okay, the PR looks fine.

@illi-kun: What do you mean? Do you really want me to report one issue per faulty string? ;-)

Those bad strings I've found are all from Transifex, it was way faster to just combine them all in one single issue. Also, all problems are of the exact same type (“bad string”), so I don't understand what you want. :-(

**Comment by illi-kun** [comment]
Ideally, yes.

**Comment by Wuzzy2** [comment]
Well, by that logic I should have created 25 issues. o_O And you're telling me this is more convenient to you? *blankeyedstare*

Anyway, I might have split the 3 categories to 3 issues at least, but I really thought all those problems were closely related to each other. I thought it is possible to just fix everything in one commit. :-/

> Request like "Please keep this issue open until further notice." also doesn't make sense. This is not how issue tracker works.

Yeah, sorry, that was a bit rude.

**Comment by ZhilkinSerg** [comment]
> Well, by that logic I should have created 25 issues. o_O And you're telling me this is more convenient to you? *blankeyedstare*

Actually it is. That is how a process works: Someone opens issue -> someone makes PR which closes single issue (or several issues at once).

**Comment by illi-kun** [comment]
@Wuzzy2 
> Yeah, sorry, that was a bit rude.

No need to sorry, this discussion is not about emotions.

Serg already described the process above but I will expand this, to show why collections of issues are evil.

Process of working with issue is something like this:
1) Check if the issue is valid. If it's invalid, close it, elsewise keep it open until it's fixed.
2) Check if the issue is fixed. If it is, close it, elsewise wait. ([this step can be done automatically using keywords](https://help.github.com/articles/closing-issues-using-keywords/)).

Let's see what difficulties we meet in working with collections on a example:

Four issues was reported at once.

First and second issues are invalid ("it works as intended", "won't fix", etc.). We can't just close the report because other items in the list are valid. So we need to request to manually edit the message (and lose the record of the initial report), or modify it using moderation rights (seems like a censorship, isn't?), or keep it in the report as is and let some contributors waste time on unnecessary fix them.

Two contributors want to ask some details about third and fourth items, so they asked them simultaneously. Topic starter answered to both, and two discussions interweaves, making tracking of each of them harder.

Third issue was fixed quite fast and the reporter notes that and put a tick in the list (this tick can't be set automatically, only manually, and only by the topic starter or by maintainer).

Fourth issue was fixed two months later by someone who found the issue independently. Xe tried to find the report about that in the repo but the broad name of the issue doesn't allow to do that.
Other reviews see the incomplete issue but can't recreate the described issue and this confuses them.

All of these issues and many more are avoidable if you split the list of issues. Yes, it takes more time to properly present them, but it saves much more time for everyone in future to maintain the issue reports.
