### ISSUE TITLE
Martial art styles are using Bashing Weapons instead of Unarmed Combat

### ISSUE THREAD

**Issue by papersplease** [CleverRaven/Cataclysm-DDA#23454]
Game version: latest

Operating system: Windows 7

Tiles or curses: tiles

Mods active: N/A

### Expected behavior
When using martial arts without a weapon, the unarmed combat skill should be used.

### Actual behavior
The bashing weapons skill is used instead, the damage output is very low.

### Steps to reproduce the behavior
Create a Blackbelt character, choose Muay-Thai as a preffered style (should work with any style, it's just the one I typically use), try to punch some zombies. Watch yourself dealing ridiculously low damage and training Bashing Weapons instead of Unarmed Combat. Upon selecting "No style" everything works as intended.

Looks like the bug was introduced in one of these commits https://github.com/CleverRaven/Cataclysm-DDA/commit/651fce62a30fe1588d34100a76408a044bd71c6b https://github.com/CleverRaven/Cataclysm-DDA/commit/4c1e7f35c4151d82caa4224f39f4de8995466b56 https://github.com/CleverRaven/Cataclysm-DDA/commit/063f797bf7b0c0074e872777012f3b798fe8b6cb https://github.com/CleverRaven/Cataclysm-DDA/commit/cc3b7172682e9e0342177365f7a8df237f1b3851

**Comment by illi-kun** [comment]
Added 'confirmed' tag because I saw some complains from users in some forum.
@BevapDin could you take a look on this?

**Comment by MisterFox** [comment]
Unable to duplicate this bug on **NEW** characters. Tested builds 7297 to 7310.

I did not have any existing characters to test with (they died) but I did experience this bug in 7295 which led to me testing in the first place.

**My control variables:**

_All stats 8
Unarmed combat increased to 3
Brawling style
Attacking a zombie_

On all builds, unarmed damage and experience gain was as expected. I have a feeling that this issue is with characters that existed prior to the introduction of the changes in an unknown build (I suspect 7301 with #23412 or 7304 with #23462 though I cannot confirm for certain).

@papersplease -- please create a new character on your current build and see if the issue persists. If so, that confirms my theory that it could be because of changes somewhere not being applied retroactively.

**Comment by papersplease** [comment]
@MisterFox Well I was specificially talking about newly created characters, although I'm getting this with old characters too. Styles are broken for me in every build starting with 7299 and up. Verified it once again just now with all default settings on 7310, still the same.

My build was: Infected, Blackbelt, 10-8-10-10, dodging to 12, Muay Thai; the traits were: Animal Discord, Far and Near-Sighted, Heavy Sleeper, Poor Hearing, Lactose Intolerance, Squeamish, Thin-Skinned, Truth Teller, Addiction Resistant, Packmule, Robust Genetics. However, I was able to repro this on entirely different builds. Muay Thai, Taekwondo and Zui Quan all seemed to be broken by this.

**Comment by ZhilkinSerg** [comment]
I guess it is related to `UNARMED_WEAPON` flag which is not set in `item()` by default, so `bashing` skill is being trained and other things work not as intended.

https://github.com/CleverRaven/Cataclysm-DDA/blob/085b6e2d1d358716dbb23ce64424b008bebb4361/src/melee.cpp#L275

We could add `UNARMED_WEAPON` flag to null item by default or use more proper fix.

**Comment by MisterFox** [comment]
After testing with all the martial arts styles it seems that this issue is only happening to **Muay Thai** and **Taekwondo** as of build 7312.

**Comment by kevingranade** [comment]
Please don't add properties to the null item. An "unarmed_attack" pseudo item would be ok, special casing skill and attack code when the null item is encountered is ok, but treating the null item as a real item is not

**Comment by ZhilkinSerg** [comment]
> Please don't add properties to the null item. An "unarmed_attack" pseudo item would be ok, special casing skill and attack code when the null item is encountered is ok, but treating the null item as a real item is not

`null` item is kind of `fists`, but what I don't get is why do we need this `null` item in `data\json`. It has some flags and other properties defined there.

Could be related - #23466.

**Comment by ZelteHonor** [comment]
Unlike what is said above, I can confirm it's happening to more than just Muay Thai and Taekwondo. I am trying to play with the Dragon Kung Fu martial art and I am dealing with the same bug.

**Comment by papersplease** [comment]
It's definitely not properly fixed. After creating a Blackbelt character with Missed scenario and everything else at default, Muay Thai still does 2-5 damage per attack.

**Comment by ZelteHonor** [comment]
I can say that in the case of Dragon Kung Fu, it is fixed. Martial art is trained properly and the damage gets higher when it level up, meaning it use the proper skill. Since it still affect Muay Thai and Taekwondo, maybe it's related to the fact that those martial art can be use while still holding something in your hand?

**Comment by papersplease** [comment]
@ZelteHonor In my experience it only affects particular attacks, not styles. For example, only power kicks from Brawling deal lowered damage, while all special attacks from Muay Thai, Karate, Taekwondo, Judo and probably some others seem to be affected.

**Comment by ZelteHonor** [comment]
It's true that I haven't reach special attack yet with my character. I'm still at level 3.
