### ISSUE TITLE
Flyers, snippets, newspapers, maps, etc. are not “good reading material”

### ISSUE THREAD

**Issue by Wuzzy2** [CleverRaven/Cataclysm-DDA#23450]
Game version: 0.C

### Expected result
If you `R`ead a map, flyer, snippet, newspaper, prospectus, etc., you read it.

### Actual result
It's not allowed. Game tells you it's “not good reading material”.
Oddly, you must look into item menu to see the written text of snippets and you have to `a`ctivate maps.

This is wrong, it's perfectly reasonable to expect for `R`ead to work here.

### Suggestions

When you `R`ead an item, do:

 * Map: Same as `a`ctivate
 * Flyer, newspaper, snippet, etc.: Show the text written on the paper in a simple overlay window

**Comment by rtizzy** [comment]
This issue is making it far more difficult to add more immersive lore aspects to the game with longer form notes/books/journals. 

I feel it could be incredibly useful to add this feature to the game.

**Initial Implementation:**

1. A user should be able to examine/read/apply a book/snippet/note.
2. A user should not be able to read the contents from a distance. 
3. This screen can be an overlay similar to the console functionality or a "full screen" to bring the full attention of the reader to the note. The latter may be more appropriate for immersion reasons. 
4. This interface should be either scrollable or paged. 


**Feature worth adding in the future:**

1. Ideally, this interface should allow for the ability to utilize bolded, italicized, underlined, or strike-through text. 
2. These files could be added to project in a simple language such as markdown or HTML.

**Comment by rtizzy** [comment]
@kevingranade It may make sense to close this issue and reference the following 

https://github.com/CleverRaven/Cataclysm-DDA/issues/28853

**Comment by Wuzzy2** [comment]
There is overlap, but #28853 is not identical or covers everything this issue already covers. Please read everything very carefully before closing or merging issues. Thank you.
