### ISSUE TITLE
“Remaining points: X” may get overwritten in player creation

### ISSUE THREAD

**Issue by Wuzzy2** [CleverRaven/Cataclysm-DDA#23486]
Game version: ae5bdc0

Operating system: GNU/Linux

Tiles or curses: curses

Mods active: Default

### Summary
In the menu for creating a new character, the “Remaining points: X” text might be overwritten by overlay texts like “Increasing Str costs 2 points.” if the translation of “Remaining points” is a bit longer than English

### How to reproduce
* Use German or other slightly verbose language
* Start new custom character
* Use multi-pool mode (“Mehrere Punktevorräte”)
* Click through the tabs
* Provoke a message at the top

In some instances, the “Verbleibende Punkte” / “Remaining points” are overwritten and partally unreadable:

* Always in the TRAITS tab
* In the STATS tab, if you assign lots of points
* Always in the SKILLS tab

**Comment by gastamper** [comment]
Confirmed this, it looks pretty wonky when it happens.  One option would be to move the descriptions that normally pop up to the right of the "Remaining points" out about ~10 characters; there's certainly plenty of screen space available for this.

**Comment by Wuzzy2** [comment]
Note that at least for German, I could possibly shorten the translation a bit, but not much.

Here's a screenshot in TRAITS tab:

https://i.imgur.com/D1vkLgy.png

**Comment by gastamper** [comment]
A better solution than the one I originally proposed might be to move the point cost down to the explanatory window, that way we have the full line available for the translation and point totals.  As a bonus, this puts all of the 'pertinent information' for the trait in question into one place (point cost + description) instead of making the user look in two places.  Terrible MSPaint concept:
![proposal](https://user-images.githubusercontent.com/20960555/38780661-35b2f1b2-40a8-11e8-86a6-f0156f32fed4.png)
Thoughts?
