### ISSUE TITLE
Automatic line breaks in mod descriptions don't work

### ISSUE THREAD

**Issue by Wuzzy2** [CleverRaven/Cataclysm-DDA#23483]
Game version: ae5bdc0

Operating system: GNU/Linux

Tiles or curses: curses

Mods active: N/A

### Summary
Automatic line break in mod descriptions don't always work. Sometimes the text overflows and can't be read fully.

For some reason, for some mods, automatic line breaks DO work. :-/

### How to reproduce
Create a new world, in the mod selection, just scroll down the list of mods and read the description.

You may or may not use a translation like German.

**Comment by illi-kun** [comment]
Please give a screeshot.

**Comment by Wuzzy2** [comment]
Why, can't you reproduce this? :(

**Comment by Wuzzy2** [comment]
https://i.imgur.com/mX5Mv7E.png

**Comment by illi-kun** [comment]
Yes, sometimes even detailed explanations don't help to find the issue but screenshot makes it clear and obvious.

**Comment by illi-kun** [comment]
How it happens that empty line between shortcut hints and 'author' line dissapear on your screen?
I'm talking about this line:
![q](https://user-images.githubusercontent.com/5421954/38772722-4a211730-4046-11e8-8281-b19ea5cea031.PNG)


Full screen on my system:

![wrap](https://user-images.githubusercontent.com/5421954/38772675-32ea6c2a-4045-11e8-83ab-5be6c43ea178.PNG)

Note that I've removed a 'maintainer' line to check the issue you described.

That's why we ask you and other reporters to provide a screenshot for better understanding of the issue.

**Comment by Wuzzy2** [comment]
The empty line is back again:
https://i.imgur.com/Dols8YZ.png

Now checked in 99883575c331d567c179ff6efb7bf5463aa52175.

Probably this was a temporary problem in an older version which has been fixed since.

The problem with the description being cut off remains.
If this empty line is removed, it would give a bit more breathing room for descriptions, however.
