### ISSUE TITLE
De-Aggro'd Monsters Ignore Other Hostiles

### ISSUE THREAD

**Issue by YakumoChen** [CleverRaven/Cataclysm-DDA#23601]
Game version: 7331

Operating system: win7

Tiles or curses: tile

Mods active: More Survival Tools, Generic Guns, Enhanced Bionics, No Fungal, More Buildings, Enhanced Classes & Scenarios

### Expected behavior:

A Moose or a Bear that has been de-aggro'd (via shouting) will still attack other monsters that attack it, and/or re-aggro.

### Actual behavior:

De-aggro'd monsters (that go back to Tracking) do not react to any other monsters that attack it, continuing to wander randomly, being mostly content to ignore anything else that gets angry with it, especially obvious with hit and run type monsters.

### Steps to reproduce the behavior:

Piss off a Moose and [C] Shout it off, lure another monster like a dog or zombie and watch it do nothing while they attack.

**Comment by ZhilkinSerg** [comment]
I've edited markup to separate headers from the paragraphs.

**Comment by YakumoChen** [comment]
![image](https://user-images.githubusercontent.com/10399117/43981139-2d6727a0-9ce0-11e8-8ffa-a4220f01e512.png)

**Comment by Night-Pryanik** [comment]
@YakumoChen I suppose the bear was first hostile to you and then became tracking?

**Comment by kevingranade** [comment]
A little context from the backend.
Monsters only have a single aggro score and a single fear score, they're
either angry at everything or nothing, theres no way to differentiate
between being angry at one target vs another, or one faction vs another.

The fix for this AFAICT is to start tracking general aggro,
faction-specific aggro, and individual aggro, then we could differentiate
between "angry at everything", "angry at one target", "angry at everything
but scared of the player", etc

**Comment by YakumoChen** [comment]
At the very least you could have another attack trigger aggro on everyone again, there's no sense shouting at a bear and then it being content to sit there and let you kill it.

**Comment by YakumoChen** [comment]
@kevingranade At the very least you could have another attack trigger aggro on everyone again, there's no sense shouting at a bear and then it being content to sit there and let you kill it.
