### ISSUE TITLE
`%`Item Action menu should include nearby tools like `&`Crafting does

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#23621]
Game version: master

### Expected behavior

i press `%` and able to `w`repair metal/plastic/kevlar with my nearby welder

### Actual behavior

it's greyed out

`a` maybe works but requires one to pick the tool up and put it in one's pocket while it may be too bulky to fit (like a welder with a car battery attached); crafting menu doesn't require it

**Comment by JornVernee** [comment]
I looked into this today. At first it appeared to be a 3-line solution in item_action.cpp in `item_action_generator::map_actions_to_items`, just add the map items to the items checked as well:
```
inventory map_inv;
map_inv.form_from_map( p.pos(), PICKUP_RANGE );
map_inv.dump( items );
```

But the problem is that these items are `item *`, and an item doesn't know it's own location. But a location is needed to actually use the item, so currently it just assumes the players position, and when you try to use items from the map (i.e. somewhere else) the game crashes.

A possible solution is to create a class that represent a reference to an item that actually exists somewhere in the world, with location and condition metadata attached. Maybe something like that exists already?

A minimal example would be:
```
struct item_ref {
    item &item;
    const tripoint &location;
}
```

I looked into implementing that a bit and it seems doable. The first roadblock I hit is that pointers have the built-in sentinel value `nullptr` which is used here and there, so will probably have to implement some kind of `optional` type, or think of case by case solutions.

I will look into that more at a later time.

**Comment by JornVernee** [comment]
Ok, using `item_location` as a "reference to item at location" type (thanks for the tip) I have a version that works for items on the ground and on a vehicle.

> `a` maybe works but requires one to pick the tool up and put it in one's pocket

There is no easy way to change that imho, since some of the use functions (e.g. for soldering iron) assume that the item is in the player inventory.

This also applies to pseudo items (like a nearby fire), which is a problem. It doesn't seem like you can generically 'use' an item (with `u.invoke_item`) unless it's in your inventory (i.e. has an inventory index).

**Comment by kevingranade** [comment]
Side note in case anyone looks into doing this, a solution that makes items triggerable at a distance, it should only happen if the triggered action is a long one similar to crafting.
Immediate actions triggered remotely would open up exploits.
