### ISSUE TITLE
Collecting water (from shallow water, for instance) doesn't take any time

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#23656]
Game version: master

### Steps to reproduce the behavior
Get a dozen of bottles and a clock, fill the bottles, observe the clock showing the same time.

**Comment by Night-Pryanik** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/26f02fbbcea0825d2612bf40349e1de582583aa0/src/game.cpp#L9391-L9408

It seems that the first check (`if( item_index != INT_MIN && create_activity() )`) when filling containers is true, so the game doesn't check for the `pour_into`, where time is consumed, because of `else if`. Changing it to 

```
if( item_index != INT_MIN && create_activity() ) {
    serialize_liquid_target( u.activity, item_index );
}
if( u.pour_into( *cont, liquid ) ) {
```

begins to consume time (and even displaying info about "Your `container` can't hold any more `liquid`"), but I have doubts if this is the right fix because filling vehicle tanks, for example, have the similar code:

```
if( create_activity() ) {
    serialize_liquid_target( u.activity, *veh );
} else if( u.pour_into( *veh, liquid ) ) {
    u.mod_moves( -1000 );
```

and it's working as it should.

**Comment by Night-Pryanik** [comment]
Cannot confirm on latest experimental as of September 27, 2019. Filling containers correctly advances time. The only issue here is too little time required to fill containers (mere 20 seconds to fill a 10-liter plastic jerrycan).
