### ISSUE TITLE
Recharging station consumes vehicle power even when it doesn't charge anything

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#23685]
And amazingly fast: three solar panels at daylight can't provide the required power.

Game version: master

**Comment by FulcrumA** [comment]
To be honest, I always considered some power taken by the charge station to be intentional, the way many devices take some when in standby mode but I can agree, it's absolutely too high and serves no real function isntead of being bothersome, forcing player to turn the station on and off every time they want to charge something. 
Single average solar panel should be able to easily meet the demand of a charge station not charging anything and even still provide a slight trickle to batteries for future use.

Also, @l29ah - since I notice you usually write down the version as "master" despite the fact that stable version is quasi-discontinued and experimental changes often even several times a day, it'd be good if you'd use actual version number. In general, I am unsure why you don't use the template provided when you make a new ticket, providing the data requested - I suspect it's there since it'd help people. Not really complaining, just thought I'd direct your attention to that.
