### ISSUE TITLE
Zui quan attacks cost no movement

### ISSUE THREAD

**Issue by MisterRIckson** [CleverRaven/Cataclysm-DDA#23696]
Game version:
7380
Operating system:
Windows 7
Tiles or curses:
Tiles
Mods active:
none
### Expected behavior
attacks should cost movement points
### Actual behavior
normal attacks with the Zui Quan style cost zero movement. Critical attacks show normal attack cost
### Steps to reproduce the behavior
character must have the zui quan martial art and enough unarmed combat to meet the requirements for the zui quan counter technique. The normal attack seems to use the counter technique, which now costs zero movement points.
edit: on further experimentation it seems like counter techniques are potentially used for all applicable martial arts styles when attacking, which have recently been changed to consume 0 movement points.

**Comment by l29ah** [comment]
I observe this too.

**Comment by papersplease** [comment]
Yeah, that's why Zui Quan seems massively overpowered when paired with high dodging and melee skill. A fresh blackbelt character with 12 dodging can just walk around a city barely noticing whole hordes crashing into him/her. You don't even need to attack, just mind your own business and they will die in droves every turn. (acid and electricity is a problem but not a big one)

I can also confirm this happening with other styles with counter attacks on high melee skill levels.

**Comment by ZhilkinSerg** [comment]
Should be probably resolved as part of https://github.com/CleverRaven/Cataclysm-DDA/issues/32422

**Comment by Hymore246** [comment]
Has anyone experienced this bug recently?

**Comment by ymber** [comment]
Cannot reproduce in current master. Couldn't say when it got fixed but it's not an issue anymore.
