### ISSUE TITLE
NPCs not spawning

### ISSUE THREAD

**Issue by TimeIsEndless** [CleverRaven/Cataclysm-DDA#23717]
Game version:0.C-27773-ga61f9b2 (tiles)

Operating system: Windows 10

Tiles or curses: Tiles

Mods active: Dark Days Ahead, Filthy Clothing, Statsthroughskills, Simplified Nutrition, No Fungal Monsters, Deadleaves' Fictional Guns, Icecoon's Arsenal, Makeshift Items Mod, Medieval and Historic Content, Mutant Npcs. Npc Traits, Alternative Map Key, Beta National Guard Camp, More Buildings, More Locations, Tall Buildings, Urban Development, Boats, Folding Vehicle Parts, Vehicle Additions Pack, Tanks and Other Vehicles, Necromancy.

Random NPCs and Static Npcs enabled. (Static NPC spawned and worked as intended.)

Screenshot:
https://i.imgur.com/pVlgmyS.png

### Expected behavior
NPCs spawning during gameplay at semi regular intervals while traveling and staying somewhere.

### Actual behavior

No NPCs spawning whatsoever after 3 ingame years with 24 day season length except for the Static Npc at the start.

### Steps to reproduce the behavior

Generating a world with these mods active and playing the game.

**Comment by FulcrumA** [comment]
What starting scenario did you choose? You can test if it's a matter of your settings or a bug if you'll choose survivor or other such character as there's a guaranteed NPC spawning at the shelter with you.

**Comment by TimeIsEndless** [comment]
As i said in my Issue the starting Static NPC is not affected. Only NPCs that should normally spawn during gameplay and spawning an NPC with the debug console works aswell.

**Comment by smolbird** [comment]
What about NPCs in the evac center and other static NPCs besides the starter NPC? Is it only dynamic NPCs?

**Comment by TimeIsEndless** [comment]
Haven't tried to find the evac center but since the other static NPC spawned i guess it is just dynamic NPCs

**Comment by smolbird** [comment]
Starter NPC and other static NPCs are different things though.

**Comment by FulcrumA** [comment]
Yeah, I pretty much am sure that it's not a bug, just confusion. Starter NPC at the shelters etc are static, dynamic NPCs are random folks who will approach you around the world if they'll spot you. Their default spawn rate however is quite low and it's not a stretch to be unable to find them if you do not travel very much and through the areas where they will be both able to spawn and not quick to die due to local zombies, monsters and whatnot.

**Comment by thethunderhawk** [comment]
Yeah at default setting I’ve found 1 dynamic NPC in a year of play. It definitely seems that they used to be more common.

**Comment by FulcrumA** [comment]
It's possible, but I still wonder how many times an NPC possibly did spawn, but was quickly killed.

**Comment by TimeIsEndless** [comment]
after some testing and two ingame years i found an NPC after buffing the spawnrate to three times the original rate

**Comment by thethunderhawk** [comment]
Hmm, should we be seeing NPCs more often than that? Is this level of rarity at default the intended behavior? NPCs often just run away as soon as they see anyone, it seems like if that’s intended we should be seeing more of them, if only to allow the player to interact with a random NPC more than once every few ingame years. Maybe the default spawn rate should be more like 1.00 instead of 0.10.
@FulcrimA are you finding a lot of dead NPCs in your games? I feel like I havent seen a single one.

**Comment by FulcrumA** [comment]
I think the most of the issue is that they spawn unreliably - soemtimes you have quite a few, sometimes none at all, independant on your own actions. I can somewhat understand low spawn rate, as NPCs can be buggy or even disruptive, especially when they're hostile. They're also some general balancing issues, like NPC who may just run through one's base, take whatever they can and still somehow maintain great enough speed to run away, swim through a lake and so on.

@thethunderhawk In the most recent game I've stumbled upon only one non-static NPC and made him join my party while still alive but in the past it did happen that I only noticed a few turns worth of really concentrated combat before stumbling upon a few straggler zombies surrounding an NPC corpse on a scene of carnage
