### ISSUE TITLE
Battery charge: balance (discussion)

### ISSUE THREAD

**Issue by Altreus** [CleverRaven/Cataclysm-DDA#23737]
Game version: 0.C

Battery discharge is very haphazard and not very realistic. There's enough trying to kill me in this game that I feel like battery usage could be buffed a bit. I would expect batteries in C:DDA to be *more* efficient than IRL, when in good repair.

For example:

If you leave the overhead light on in your electric car in-game it will run out in a matter of days. A modern electric car stores enough energy in its batteries to power the internal LED light for 3 *years*.

IRL I have a cheap LED torch that I can leave on for at least 24 hours before it starts to dim; in-game, a torch will use 1 battery per step, essentially. I am constantly turning a torch on, looking around, then turning it off and moving, because if I leave it on while moving, it will run out. IRL I can read an entire novel with this torch but in-game I would be reloading it to do that.

Batteries are unrealistically weak in C:DDA and might be a good candidate for rebalancing.

**Comment by FulcrumA** [comment]
You may be onto something. There was already a ticket in regards to, for example, how much a "standby mode" (activated, but recharging no items) UPS recharging stations use up energy (#23736) but in general I can agree that nearly all handheld items use up energy too easily/quickly and so does majority of vehicle equipment.

However, changing it across the boards would probably require also change in availability of batteries. Bateries should drain much slowly but devices loaded with them upon spawn should also have lower charge. Possibly also in loot there should be less than merely stacks of (100) when it comes to batteries to encourage one's own production.

At the same time I'd advocate keeping the maximum charge as it is. I always found it weird how neither average nor pro camera could handle making even a couple of dozens of pictures without recharging.

**Comment by FulcrumA** [comment]
To comment, @Theundyingcode 
>Player made batteries should be significantly worse than their factory counterparts.
Agreed. At the same time there should be different tiers of batteries a player can make. The difference between factory and hand-made stuff not always is a matter of quality. The former however almost always wins in terms of mass production.

>Fully charged batteries (full stacks) should only be found in stores, garages, closets and other storage locations. Battery charged items should be found with random amounts of charge in them.
As I've made a similar point, I can only agree.

>Officially designate the energy in a charge of battery as some RL unit say 100mah. This will allow for power usage to be properly balanced.
I am ambivalent toward that. Batteries are already balanced more from the standpoint of gameplay than any real units of power they provide. I don't mind it staying that way and maybe even prefer it.

>Make batteries act like magazines holding charges rather than a stack of small items that magically get eaten when you turn your flashlight on. Define the batteries' performance by size, weight, max charge and rechargeability.
Making them "power" magazines and making most electrical devices able to use many types of them, while making maximum charge fully dependant on the batteries themselves would work fine. It'd be important to redo all electrical devices so that they'd be able to use many varied batteries of similar size and probably modifications allowing a device to use batteries of different kind/greater variety of them should be added as simple electronics recipes.

**Comment by RadHazard** [comment]
At the low end, portable electronics are definitely too power hungry.  However, in my opinion, high-end power consumption is too low.  There's essentially two tiers of power use: Things that can be run efficiently off of batteries and things that require a base to run.  Once you have a few solar panels, electricity becomes basically free for everything but a few items (minifridges come to mind).

It would be nice to have a wider spread of electric usages to allow for a greater progression curve.  Items could be separated based on what sort of power source they generally require (batteries, standard wall sockets, 240V dedicated lines, Sci-fi power sources) and rebalanced to make it infeasible to run higher-tier items off of lower-tier generators.  (note: infeasible meaning it should be possible but it should take far too long to be regularly usable).  We already have items in each of those tiers, but the difference in power usage between, say, a hotplate and a plasma rifle is so small that there's really never any reason to upgrade past solar power.

In addition to rebalancing power usage, there should probably be another tier in between battery power and power from a base.  Perhaps a handheld portable generator item that could work as a pseudo-UPS, generating enough power to run "medium-tier" items in your inventory at the cost of gasoline and noise.  There could also be a craftable variant made from one of the tiny engines and an alternator.  These should be easier to find or make than building a proper base, but would only provide enough power to consistently run things like hotplates, water purifiers, coffee makers, and other household appliances (which would all have to be rebalanced so that they aren't really feasible to run off of AA batteries anymore).  There could even be an "inverter" item that could be easily installed into cars to power items at this tier.

The intended progression of this rebalance would be batteries -> handheld generator/car with inverter -> generator/solar bank powered base -> minireactor-powered base.

**Comment by FulcrumA** [comment]
To expand upon the idea, @RadHazard 

I wouldn't want to be strictly tiered system, to be honest. I'd rather have batteries and vehicle-power generators of many types (not only solar) and tiers as well as varied rarity, with types merely exceling on average in regards to certain qualities (batteries being more portable than all but most advanced power generators of any other kind, solars being on average the most "free" and cheap energy etc). 

By making each: batteries, solars and fueled-generators appear in various, worse and better models (be those differences of power, size or quality because this crappy homemade plutonium reactor leaks and may explode if a fly lands on it too hard) we'd let the player pursue their own prefered option dependant on circumstances and resources. 

A gasoline-guzzling generator may be much easier to find/make than an average solar panel, maybe even provide more power, but there should be also solar panel of size and level that will be comparable while not requiring any fuel to generate energy as long as it gets some light. And maybe in some laboratory there are tiny superadvanced powercells that provide handheld devices with infinite energy but explode if it's too warm. Or maybe similarly superadvanced battery that you can hook up to a vehicle or just plug somewhere in a base - which regenerates charge out of nowhere, but can hold only a bit of power at a time, making it unsuitable for anything requiring constant supply of electricity. Maybe some of those things could be converted into something else (I am bothered how I cannot simply rip a battery out of a scooter and weld it onto a welder while at the same time making it compatible with solar-powered UPS recharging station).

If we are to really go this far into revamping whole power system, I'd like it to be flexible around that we get stories like "yeah, I've built a shed where I keep a dirty improvised reactor with a core I took from some heavy droid. I have to keep the thing in a fridge and cannot approach it without a hazmat suit, but it glows nice at night, even through walls". But that's more like new ideas rather going out of the scope of this ticket so I'll stop here.

**Comment by Night-Pryanik** [comment]
No discussion in almost a year, closing.
