### ISSUE TITLE
Suggestion: Add "Works" field to vehicle examine display

### ISSUE THREAD

**Issue by Theundyingcode** [CleverRaven/Cataclysm-DDA#23753]
Examining a vehicle gives you a whole bunch of information which is great for building your deathmobile.  The rest of the time however, the only thing I care about is whether or not the thing will move.  There have been way too many times that I have gotten in a vehicle to escape the chasing horde only to find I overlooked something examining it. (especially since the addition of mending)

Can we add a simple indicator as whether or not the thing is usable in its current state?  (has enough wheels, controls, enough battery to start up, some fuel, working engine. etc)

**Comment by Night-Pryanik** [comment]
I think we could slightly rework the existing "Status" field to show the info you want.

**Comment by FulcrumA** [comment]
With exception of the controls - doesn't it? Fuel, battery power and whether the vehicle has enough wheels is shown immediately. If engine wouldn't work for any other reason (something requires to be mended) it's a bit more tricky since engine damage where everything else is fine doesn't really permanently mess the engine up, simply makes it considerably harder to start.

**Comment by Theundyingcode** [comment]
I am not disputing the fact that all the information is there, I am suggesting we condense it into a simple yes it works or no it doesn't.  Having to check multiple different things makes it easy to overlook something.  For instance, @FulcrumA you missed needing battery charge in order for the engine to start.

**Comment by FulcrumA** [comment]
>For instance, @FulcrumA you missed needing battery charge in order for the engine to start.

Good point but isn't it obvious that any engine needs some power to start? You can usually easily gather that by simply checking if battery has any charge at relevant position of the screen - from my experience, if it's not under 1% - it'll work.

I am simply unsure if we need further condensation. If there's not enough wheels it's obvious it won't work. Same with no fuel or charge. If it's just yes/no I'd argue it'll be only additional clutter because most people will want to know how exactly much the power/fuel there is so all those new stats would have to be in addition to what's already there and then there's again no point since people seeing that there's some fuel/power will also know it's enough of fuel/power to start the vehicle (as long as a working engine is there - and engines are also listed immediately on the screen), even if not possibly to use it for long (a thing which new indicators wouldn't help with).

**Comment by Night-Pryanik** [comment]
No discussion for over half a year, closing.
