### ISSUE TITLE
error: use of undeclared identifier 'g' on compile

### ISSUE THREAD

**Issue by StripedMonkey** [CleverRaven/Cataclysm-DDA#23766]
Probably missing something important but basically I'm getting a strange compile error, obviously this shouldn't be an issue but it is and I'm assuming there's something that I'm missing. I'm no good with understanding makefiles and such though, so I'd love some help.

Game version:
Latest git
Operating system:
Ubuntu 18 (linux)
Tiles or curses:
tiles
Mods active:
N/A
### Expected behavior
Compiles without error
### Actual behavior
https://hastebin.com/xocihijuni.swift
### Steps to reproduce the behavior
1. Download repo on fresh ubuntu install
2. Install dependencies
3. run `make TILES=1 SOUND=1`

**Comment by vschule** [comment]
This is temporarily fixed by https://github.com/CleverRaven/Cataclysm-DDA/pull/23760

The only change is to include game.h again in 'src/sdltiles.cpp'

That include was removed in this commit https://github.com/CleverRaven/Cataclysm-DDA/commit/f030180c4b63be91562359f11cd0ed452e47d7b3 for some reason.

**Comment by ZhilkinSerg** [comment]
Should be fixed by #23760.
