### ISSUE TITLE
Windows with curtains in an orchard hut have all four sides set to outside

### ISSUE THREAD

**Issue by papersplease** [CleverRaven/Cataclysm-DDA#23868]
Game version: 0.C-27987-g5a5585c

Operating system: Windows 7

Tiles or curses: tiles

Mods active: none

### Expected behavior
Windows with curtains can be opened and closed from inside the orchard hut, and cannot be manipulated from outside.

### Actual behavior
Windows cannot be opened or closed from either side, even from the side adjacent to the wall if you break it.

### Steps to reproduce the behavior
Find/spawn an orchard, get inside the hut, try to open and close windows. Try to break the wall to check all 4 sides.

I suspect is has something to do with log walls.

**Comment by DracoGriffin** [comment]
I believe the issue is it's referencing the incorrect concrete terrain -- t_concrete is used outdoors `        "flags": ["TRANSPARENT", "FLAT", "ROAD"],`, whereas t_thconc_floor is used indoors `            "TRANSPARENT", "SUPPORTS_ROOF", "COLLAPSES", "INDOORS", "FLAT"`.

So the issue is the windows are surrounded by outdoor tiles, hence you can't interact with them in any direction (whether inside the hut or outside).

I'll correct this by swapping the concrete terrains so the windows can be interactive.
