### ISSUE TITLE
Limits on wearing headgear ain't working right

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#23924]
Game version: latest experimental

Operating system: Windows XP SP3 x86

Tiles or curses: curses

Mods active: default only

### Expected behavior
Can't wear headgear over army helmet or headgear over headgear.

### Actual behavior
![default](https://user-images.githubusercontent.com/11132525/40858070-c8251626-65e5-11e8-8e6a-a817933aab5b.png)

### Steps to reproduce the behavior

Spawn headgears, spawn army helmet, try to wear them all.

**Comment by ymber** [comment]
Headgear has OVERSIZE for some reason. Should probably get rid of that.

**Comment by Max17U** [comment]
The problem is not within the item itself but rather with the OVERSIZE flag. The real question is: what is it supposed to be the standard? Should someone be able to put 1 Oversized helmet onto a "normal" helmet? Should someone be able to put 2 or more Oversized helmet over a "normal" helmet?
Or wasn't supposed to happen? In game you can't put an oversized pair of boots over a "normal" pair of shoes/boots, so why is this happening with helmets?
Another question is why the "headgear" is "oversized" ? It shouldn't be imo. And still in my opinion, maybe you shouldn't be able to put an oversized helmet onto a normal helmet.
I think i could fix this problem so let me know how it should work

**Comment by NetSysFire** [comment]
You can wear both, but you get 45 encumbrance from this and the sort armor thing says it is due to wearing type normal clothing.

@Venera3 is doing the limb rework and you should be able to define where exactly a piece of clothing is worn, e.g a chestplate and a backpack do not conflict because the backpack item is hanging specifically from the back of the character, while the chestplate is occupying the front.

**Comment by Venera3** [comment]
I have seen the discussion about this stuff few times, and it always goes "yeah that's weird" "well how is it supposed to work?" "Err, dunno" (I'm abbreviating a bit, obviously) - it's one of those bits that kind of need somebody to rework them along an internally consistent idea in my opinion.

**Comment by NetSysFire** [comment]
I am removing good first issue since this does seem too confusing and complex for a new contributor.

**Comment by Night-Pryanik** [comment]
Tested on 0.F-10122 and can't confirm this anymore. Seems that #55566 resolved this issue.
