### ISSUE TITLE
Edibles listing inconsistencies

### ISSUE THREAD

**Issue by FulcrumA** [CleverRaven/Cataclysm-DDA#23933]
Game version: Currently 0.C-28092

Operating system: Windows 7

Tiles or curses: Tiles

Mods active: More Survival Tools, No Explosive Zombies, No Fungal Monsters, StatsThroughSkill, Vehicle Additions Pack, Tanks and Other Vehicles, Bionics Systems Mod, Boats, Icecoon's Arsenal, Filthy Clothing, Makeshift Items Mod, More Buildings, No Flaming Weapons, Disable Mutagens, Disable NPC Needs, No Antique Firearms, No Fictional Guns, NPC Traits

### Expected behavior
Items of the same type maintain the same system in how they're listed.

### Actual behavior
Items are listed in various, inconsistent ways, for example:
![inconsistency2](https://user-images.githubusercontent.com/38487938/40884825-3138393c-671b-11e8-87c6-6d6a4c78eace.png)
In one row cooked meats are described as 5 portions of a single type of item, but in the row immediately below, as 3 units of single portions of cooked meat. The meat in question almost surely comes from the same creature and was cooked at circa the same time, using the same recipe.

### Steps to reproduce the behavior
Cook meat or craft other similar items regularly.

**Comment by Leland** [comment]
@FulcrumA can you split this into two issues, please? The books issue is relatively simple to fix, see:

https://github.com/CleverRaven/Cataclysm-DDA/blob/66ccbdb265cf9017649dd6822d2c64ee09c29308/data/json/items/book/pistol.json#L22-L23

**Comment by DracoGriffin** [comment]
The food issue is based on the age assigned to the item/stack when it was generated after crafting. Because they have different spoil timers, they are on different lines rather than clumped together.

The book issue is more on styling and how the devs want to approach it. "copies of" basically denote identical copies of a singular book -- we can assume Ye Scots Beuk o Cuikery is a single edition book that doesn't have different issues or editions, hence why you would have "copies of". `2 Self-Esteem for Dummies` should likely be "copies of" because they are probably the same version/edition and so on.

The times when "copies of" shouldn't be used if for the generalized morale books, since I believe they are meant to be like newspaper pages (snippet_categories). So "Y copies of TIME magazine" shouldn't be, since you should be seeing an array of issues and volumes -- the reason you don't is because I think no one has really sought to handmake a bunch of different versions with snippet flag (someone did add more morale books #23192) and to reduce json bloat (given how many issues there are of TIME, how many do we really need?). And lastly, I have no idea why some books will occupy two lines -- like your Under the Hood -- there is only one Under the Hood as `manual_mechanics`, I'm assuming because it doesn't have a name_plural listed.

**Comment by FulcrumA** [comment]
@DracoGriffin 
>The food issue is based on the age assigned to the item/stack when it was generated after crafting. Because they have different spoil timers, they are on different lines rather than clumped together.

True, but the issue still lies in how represented those stacks are. First is "cooked meat - five portions", the second is "three units of cooked meat one portion each", instead of being, say "5 cooked meat (1)" and "3 cooked meat (1)" or even better "cooked meat (5)" and "cooked meat (3)" as apparently they do stack in some way so spoilage shouldn't be an issue here.

>The times when "copies of" shouldn't be used if for the generalized morale books, since I believe they are meant to be like newspaper pages (snippet_categories).

Funnily enough, I remember reporting newspaper stacking issue as well as newspapers were stacking in up to three stacks (ceased generating new stacks no matter how many new newspaper pages I've added) randomly despite differences in articles and (presumably, as they were all picked up from the ground undisturbed till then) same condition.

As for generalized morale items, they're also somewhat inconsistent. Many novels and magazines describe general theme, while many others describe plot of a particular story. Only a few times I've seen different novels of the same type with different descriptions regarding the content.

@Leland 
Gladly. Is there a way I could move around the comments as well though - as they refer to different aspects of the issue and may help in the new ticket?

**Comment by Leland** [comment]
@FulcrumA I typically just quote the relevant parts in the new ticket's description

**Comment by FulcrumA** [comment]
@Leland 
Guess it'll have to do. Alright, changing this ticket to concentrate on food stacking issue, splitting book stacking to another issue.

**Comment by DracoGriffin** [comment]
>True, but the issue still lies in how represented those stacks are. First is "cooked meat - five portions", the second is "three units of cooked meat one portion each", instead of being, say "5 cooked meat (1)" and "3 cooked meat (1)" or even better "cooked meat (5)" and "cooked meat (3)" as apparently they do stack in some way so spoilage shouldn't be an issue here.

You're right, I overlooked those details. I'd hazard to guess the 5 is from a batch and the other was from some weird single crafting potentially.

However, I was not able to reproduce this in any form (dropping some meat, heating up a partial stack, batch crafting, cooking single items).

That isn't to say it doesn't exist, I'll have to make a note of it in my own playtesting/playthroughs because there have been times where I have butchered a zombie corpse and got 5 tainted meats (1) and other times where I've butchered a zombie corpse and got tainted meats (3). And hopefully then I can reproduce it more diligently. For any dev/coders, I'd suggest doing that method of reproduction as that's most likely the culprit.

**Comment by FulcrumA** [comment]
Since I just noticed the batch mention (quite some time after the comment, eh?) I have to point out that I seldom ever use batch-crafting and it's almost impossible that either stack of meat was cooked in such a way (while less efficient, I do use "repeat last crafting" key habitually, though).
