### ISSUE TITLE
2x4 Arm Guard is the only arm guard with Block technique.

### ISSUE THREAD

**Issue by RedPine91** [CleverRaven/Cataclysm-DDA#23931]
Game version: Current experimental (7435)

### Expected behavior

Arm guards that are harder to make should have better stats than arm guards that can be made with a skill of 1.

### Actual behavior

2x4 arm guards are the only arm guards with "Block: Medium Blocking Ability" as granted them by the "WBlock_1" technique in data/json/items/armor.json

All other arm guards have the "Block_While_Worn" flag, but since they are missing the blocking technique, the flag is currently (if I understand how techniques work correctly) useless.  

### Solution

Either remove blocking from ALL arm guards (including the "Block_While_Worn" flag), or give the medium blocking technique to all arm guards.  This is a very simple fix, but I haven't learned how to do pull requests just yet.

**Comment by BorkBorkGoesTheCode** [comment]
@RedPine91 GitHub assumes all numbers preceded by a # sign are supposed to link to an issue or PR of the same number.

**Comment by FulcrumA** [comment]
>Either remove blocking from ALL arm guards (including the "Block_While_Worn" flag), or give the medium blocking technique to all arm guards.

I'd personally recommend the latter. I find it weird that most arm guards protect from damage only if the enemy specifically targets the protected limb, rather than allowing the character wearing the item to protect vital areas with their arms as it is often done IRL.

**Comment by pisskop** [comment]
Did arm guards stop blocking attacks in combat or is this just a case of examining item details sheets?  
Perhaps guards need to be laid out in the ui.

> Arm guards that are harder to make should have better stats than arm guards that can be made with a skill of 1.

why is this true?

**Comment by RedPine91** [comment]
@pisskop 

It should be self evident that the higher the craft difficulty of an item, and the greater the rarity of the ingredients, the better the item should be overall... so why should only the easiest to craft out of all the arm guards be the only one with the blocking technique?

Here is a comparison:

|Armor|Skill|Bash|Cov|Enc|Special|
|---|---|---|---|---|---|
|Papper Arm Guard|0|3|80%|10|No conduct
|2x4 Arm Guard|1|9|75%|25|No conduct, Medium Blocking
|Leather Arm Guard|3|8|90%|16|No conduct, Sturdy
|Bone Arm Guard|4|8|95%|22|No conduct, Sturdy
|Metal Arm Guard|4|12|80%|15|None
|Chitin Arm Guard|5|9|90%|10|No conduct, Sturdy
|Acid Chitin Arm guard|6|12|90%|15|No conduct, Sturdy, Env Prot 2

Note that ALL arm guards have the "Can block while worn" flag, but ONLY the 2x4 has any blocking technique.  Can an armor block with the flag, but no technique? Can an armor block with the technique, but no flag?  Is blocking with the flag just as effective as blocking with the technique?

I have no idea, but something might not be working as intended - and if it IS working as intended, the UI or code should be clarified to make this easier to understand.

**Comment by DracoGriffin** [comment]
This is just a bit of confusion: items that have any techniques listed are what the player may randomly utilize (just like with weapons) in combat when wielded. Essentially, the `Techniques: Block: Medium blocking ability` means when you wield the 2-by-arm guards as a weapon, you sometimes will block with them. It does not mean the level of block they have when worn. This makes sense because two-by-fours also grant `Techniques: Block: Medium blocking ability` when wielded as a weapon and all other arm armor/arm guards don't have this technique because they don't really block very well when wielded as a weapon.

Is this superfluous? Yes, a bit. How often is a survivor really going to wield the 2-by-arm guards as a weapon?

You can see this with all types of random items, like pot helmet (gives Blocking) which incidentally, doesn't block when worn. Only when wielded.

This is easily verifiable by creating a test character with no martial style, normal stats, and mutate Debug Invincibility. Generate a simple zombie next to you. Wish in a pot helmet and wear it. You won't block attacks. Wield instead and suddenly you start blocking attacks. Same thing with arm guards.

Wish yourself leather arm guards and wear them. You will block attacks with your arm because of the BLOCK_WHILE_WORN flag. Remove them and wield them instead. You won't block attacks anymore (because leather arm guards do not have the Blocking technique).

Wish yourself 2-by-arm guards and wear them. You will block attacks with your arm because of the BLOCK_WHILE_WORN flag. Remove them and wield them instead. You will also block attacks (because 2-by-arm guards have the Blocking technique).

As of now, there is no quality difference of blocking for the BLOCK_WHILE_WORN flag: they all block similar amounts of damage. However, certain material items will last longer than others and thus, withstand more blocked attacks before being destroyed.

**Comment by kevingranade** [comment]
More general comment, please dont open issues where the expected/actual results are game stats, lots of these issues turn out to be misunderstandings of how the stats work.

If there is an imbalance, please outline an in-game scenario where that imbalance arises.
