### ISSUE TITLE
Block ability for non-wielded arm guards

### ISSUE THREAD

**Issue by FulcrumA** [CleverRaven/Cataclysm-DDA#23945]
Game version: 0.C experimental in general

Referencing #23931 as it was closed due to misunderstanding about stats, while still being an inspiration for this ticket. 

### Expected behavior
Nearly all more sturdy and rigid arm guards should have blocking ability that can kick in even when they're not wielded, to represent a chance where the wearer attempts to block/deflect incoming strike with their arms as it is normally done IRL

### Actual behavior
Most arm guards have no blocking ability, block ability in general only kicks in when an item is wielded as a weapon, otherwise providing damage mitigation only if the character is struckt in the body part thus armored.

The feature, as a side bonus, would also allow easy addition of shields.

### Steps to reproduce the behavior
Use arm guards

**Comment by Blank99** [comment]
As explained during the ticket in question, arm guards already give blocking ability while worn.

If you look at the list of properties where it says things like "performs well while wet" and the like, you'll see that they all inform you that you can block attacks with them when you wear them.

The only arm guard that gives the ability to block while wielded is the wood one, because it's basically a club and it's easy to block with it.

**Comment by FulcrumA** [comment]
Understood, my bad - conclusion of the aforementioned ticket combined with the fact I didn't see my arm guards block in quite a long time unless it was the arms themselves that were hit by the enemy made me react too quickly.
