### ISSUE TITLE
Wire basket installation inconsistency

### ISSUE THREAD

**Issue by FulcrumA** [CleverRaven/Cataclysm-DDA#23949]
Game version: Currently 0.C-28092

Operating system: Windows 7

Tiles or curses: Tiles

Mods active: More Survival Tools, No Explosive Zombies, No Fungal Monsters, StatsThroughSkill, Vehicle Additions Pack, Tanks and Other Vehicles, Bionics Systems Mod, Boats, Icecoon's Arsenal, Filthy Clothing, Makeshift Items Mod, More Buildings, No Flaming Weapons, Disable Mutagens, Disable NPC Needs, No Antique Firearms, No Fictional Guns, NPC Traits

### Expected behavior
Recipes for wire baskets for installation in a vehicle should either all call for pre-assembled baskets craftable through crafting menu or for wires and soldering iron/welder to assemble them on-site (preferably the former).

### Actual behavior
One wire basket recipe calls for 1 wire, the other has to be preassembled with 6 wires beforehand to be installed.

### Steps to reproduce the behavior
Attempt to install wire baskets in a vehicle

**Comment by DracoGriffin** [comment]
I don't think you can assign more than one item for vehicle construction currently (or at least the last time I looked), so making it require 6 wires will require coding change.

Otherwise, just changing the 1 wire requirement to something similar for a recipe, 2-4 wires to produce some sort of cheap wire basket.
