### ISSUE TITLE
Book listing inconsistency

### ISSUE THREAD

**Issue by FulcrumA** [CleverRaven/Cataclysm-DDA#23946]
Game version: Currently 0.C-28092

Operating system: Windows 7

Tiles or curses: Tiles

Mods active: More Survival Tools, No Explosive Zombies, No Fungal Monsters, StatsThroughSkill, Vehicle Additions Pack, Tanks and Other Vehicles, Bionics Systems Mod, Boats, Icecoon's Arsenal, Filthy Clothing, Makeshift Items Mod, More Buildings, No Flaming Weapons, Disable Mutagens, Disable NPC Needs, No Antique Firearms, No Fictional Guns, NPC Traits

Issue related to #23933 - split to a new ticket per request by @Leland 

### Expected behavior
Items of the same type maintain the same system in how they're listed.

### Actual behavior
![book inconsistencies](https://user-images.githubusercontent.com/38487938/40884844-895ab982-671b-11e8-8005-7b18b2f87d65.png)
Several different piles of books (underlined in a way inconsistent with the previous image). Ye Scouts Beuk of Cuikery is listed as a position with 2 copies, while under it, other piles of books like Self-Esteem for Dummies or Big Books of First Aid are merely listed as [number of][title].

### Steps to reproduce the behavior
Acquire various books

### Relevant notes from the previous ticket

@DracoGriffin 
>The book issue is more on styling and how the devs want to approach it. "copies of" basically denote identical copies of a singular book -- we can assume Ye Scots Beuk o Cuikery is a single edition book that doesn't have different issues or editions, hence why you would have "copies of". 2 Self-Esteem for Dummies should likely be "copies of" because they are probably the same version/edition and so on.

>The times when "copies of" shouldn't be used if for the generalized morale books, since I believe they are meant to be like newspaper pages (snippet_categories). So "Y copies of TIME magazine" shouldn't be, since you should be seeing an array of issues and volumes -- the reason you don't is because I think no one has really sought to handmake a bunch of different versions with snippet flag (someone did add more morale books #23192) and to reduce json bloat (given how many issues there are of TIME, how many do we really need?). And lastly, I have no idea why some books will occupy two lines -- like your Under the Hood -- there is only one Under the Hood as manual_mechanics, I'm assuming because it doesn't have a name_plural listed.

Funnily enough, I remember reporting newspaper stacking issue as well as newspapers were stacking in up to three stacks (ceased generating new stacks no matter how many new newspaper pages I've added) randomly despite differences in articles and (presumably, as they were all picked up from the ground undisturbed till then) same condition.

As for generalized morale items, they're also somewhat inconsistent. Many novels and magazines describe general theme, while many others describe plot of a particular story. Only a few times I've seen different novels of the same type with different descriptions regarding the content.

**Comment by DracoGriffin** [comment]
The fixes for this issue is relatively simple however it's more of a dev style choice, so any future additions can maintain semblance of conformity and uniformity.

Basically:
When is "copies of" meant to be used?
When is name_plural meant to be used?

However, the Under the Hood issue may not be so simple:
Under the Hood issue may be related to not having name_plural (as the fallback for missing name_plural is just to add an 's' at end of item), but in my testing, what I actually found was whether you read the book or not. (Tested with books that do have name_plural specified)

Debug yourself 5 or more of any single skill book(makes this easier to visualize). Make sure to have enough volume storage (debug carrying capacity or not, this is also to make it easier). Skim book. Read book once. You should now have two stacks in your inventory of the debugged book: 1 that you just read, and the other 4 in another stack. Read another book but from the stack of 4. Now the previous single book is a stack of 2, while the stack of 4 becomes 3, and so on. There doesn't seem to be any issues of differences in % gain (for instance, reading a "new" book doesn't reset skill gain and continues as normal _as expected_).

Example:
Debug wish 5 `The Big Book of First Aid`
Skim `5 The Big Book of First Aid`
Read `5 The Big Book of First Aid` once
You now have `The Big Book of First Aid` and `4 The Big Book of First Aid` in your inventory.
Read `4 The Big Book of First Aid` once
You now have `2 The Big Book of First Aid` and `3 The Big Book of First Aid` in your inventory. And so on.

So essentially, it looks like there is not only the "Skimmed" check (changing from red color to post-red color [purple, yellow, blue, gray depending on status of player]), but an additional (unintended ? ) check if that same book has actually been read (so why are the books being assigned additional namevalues or whatever in order to differentiate, which it shouldn't be?).

**Comment by Leland** [comment]
I'll handle this
