### ISSUE TITLE
"Too big to pick up" does not take wielding into account

### ISSUE THREAD

**Issue by Altreus** [CleverRaven/Cataclysm-DDA#23957]
Game version: 0.C

Mods active: Default

### Expected behavior

If character has low inventory space (e.g. is naked), can `a`ctivate nearby large item (e.g. camp fire drill) as long as their hands are empty.

### Actual behavior

Item is "too big to pick up"

### Steps to reproduce the behavior

* Craft something usable, e.g. camp fire drill
* Drop inventory space. I tested with 0.75L
* Attempt to light a fire by pressing `a`
* Camp fire drill is listed in the menu but is "Too big to pick up!" and cannot be activated
* Wear enough clothing to store the item
* Camp fire drill can be activated

**Comment by Theundyingcode** [comment]
personally, I never liked the whole activating means putting it in your inventory thing.  Why do I need a backpack to read a book? why can't I just set it on the table, open it and read the thing?

**Comment by kevingranade** [comment]
Yea, just pick it up and put it on a table without touching it, it's simple.

**Comment by Brambor** [comment]
@Theundyingcode Sometimes CDDA is too realistic for me, as I have the same issue with reading books 😄.

**Comment by Theundyingcode** [comment]
> Yea, just pick it up and put it on a table without touching it, it's simple.

I have the ability to take the comic book from a dead kid at the bottom of a pitfall  and stuff it in my bag while holding a giant drum, two bindles and, pulling a shopping cart.  Yet for some reason I can't use my feet to turn over a book on the ground so I can read the back and figure out what it's about.

**Comment by Altreus** [comment]
I dunno, if it's literally too big to pick up (or too heavy) you shouldn't be able to activate it. Anything that doesn't need to be picked up to activate is already activated by `e`xamining the tile.

If you want to read a book that's on a table, that could be an `e` menu feature, a bit like when you `e` a vehicle and it lets you pick between "Examine vehicle" and "Get items on the ground".

But you kind of have to pick up a fire drill to use it - but that should be literally the only consideration: I (IRL) can't use a fire drill if I'm wielding a knife spear, and I can't unwield the knife spear if I don't have room in my inventory. There's already a "What do you want to do with knife spear?" menu, so it makes sense that if you want to activate the fire drill, it would pull up this menu, from which you drop the knife spear.

I think it makes sense that if you want to activate something that can be picked up, you *have* to wield it to do so. And certain items could be activated in situ, like a book, from the `e` menu.

**Comment by RadHazard** [comment]
It makes sense from a realism standpoint that you must be able to hold an item in your hands in order to activate it, but from an "avoiding tedium" standpoint I don't think we should force the player to manually wield the item every time.  We can assume that during the process of using the item the character puts down their weapon, picks up the item, uses the item, then puts it back down and picks their weapon back up.

Adding an extra move cost for the extra motions (maybe with text notifications to indicate that they're happening) makes sense, but manually forcing the player to go through all those keypresses every time just adds tedium.

**Comment by kevingranade** [comment]
I'm ok with automatically stashing the currently wielded item to free up the hands and then wielding it again afterwards.

**Comment by Altreus** [comment]
I agree that the player shouldn't have to actually perform those actions, but it made sense to me that if those were the things the game did for you, that would be a more sensible method of using something nearby.

I note that if you even try to use something nearby, as long as it gets to the point where you actually attempt to perform the action, the item remains in your inventory. This would therefore have to introduce a "put back" step that currently doesn't exist; alternatively, the item remains wielded and you have a "Where the hell did my weapon go?" moment some minutes later because you didn't realise you'd wielded the used item and not put it back.

**Comment by Brambor** [comment]
Yeah, I just wanted to point out that it should be considered what happens when a player tries to read book, is done and then reads another one.
Or maybe you already said that when a player reads book it means that they drop their wielded item, they pick up the book, they read the book, they finish reading the book, **they put it in pocket or put it back (?)**, they pick up their previously wielded item.
