### ISSUE TITLE
Sugary candy as energy source when starving

### ISSUE THREAD

**Issue by thethunderhawk** [CleverRaven/Cataclysm-DDA#23953]
First off I just wanna say this is my first issue submission, and I apologize for any formatting errors or etiquette issues you might find here.

I suggest that a mechanic be developed that would allow sugary candy to temporarily reduce hunger penalties upon consumption. It would not affect actual hunger level, it would only reduce existing penalties for being Famished or Starving.

I recently found my grandfather’s US army field manual from his time in Vietnam. It suggests candy as a survival supply in case of being lost behind enemy lines. The idea is, should you go a couple days without a meal and then have to exert yourself, your body can convert pure sugars into fuel extremely quickly, giving you a temporary burst of energy. In game terms we would model that as a “sugar rush” effect that would reduce stat loss to high hunger levels, possibly followed by a “sugar crash” perhaps an hour later that would temporarily increase those same penalties (or, the crash could cause fixed penalties, thus penalizing well fed characters for binging on candy).

This would give candy an interesting and fun effect, and give an early player a reason to craft and gather stockpiles of candy for emergencies beyond the simple morale boost, which can already be achieved quite a few different ways. 

I appreciate your feedback!

**Comment by FulcrumA** [comment]
My feedback is simple - if it's indeed a thing of effect considerable enough to be included in manuals, I am not against it. It's certain that it'd be nice if a role of sweets would be expanded beyond morale boosters.

**Comment by Maddremor** [comment]
Well, since candy is calorie dense they should be a valuable consumable given that providing calories is kind of the primary point of food. If you want to ease the feeling of an empty stomach after your caloric needs are filled you could eat mushrooms, leaves, drink a lot of water or something like that.

**Comment by FulcrumA** [comment]
To be honest, it may be good to consider upping somewhat how filling candies are. Not only they're a limited resource that can be only scavenged and with exception of few items, not crafted - we do have vitamins and other such nutrients as well as general healthiness stat junkfood affects negatively to balance it out and require for one to consume other things as well.

**Comment by Maddremor** [comment]
I think we could look at how many calories candy typically contains IRL and use that. This assumes that the `nutrition` stat represents calories, although if not I don't know what it means.

**Comment by FulcrumA** [comment]
I believe nutrition is largely arbitrary currently. Nutrition based on caloric content would require rebalancing of all foodstuff but is intended for faraway past. I worked with @mrkybe a tiny bit on it already, but - at least on my end - it was going slowly. Feel free to help out by providing charts of caloric content and possibly other nutrients per 100g of equivalents of ingame edibles, that'd help out a ton because it's not hard, but time-consuming and mind-numbing.

**Comment by Maddremor** [comment]
@FulcrumA I had a look at `itype.h`, and saw that 1 nutr ~= 8.7kcal. As a bonus, you can use `calories:` instead of `nutrition:` when defining a food item, which makes makes the process of balancing a bit easier. I will try to make some kind of table as time and mental fortitude allows.

**Comment by FulcrumA** [comment]
@Zireael07
Pretty interesting. I'll take an in-depth look in a few days. Did you use the same conversion Maddremor uses (1 nutr ~= 8.7kcal)? Because some of the values I see there are very high per portion of the product. Kybe was already tagged so hopefully he'll take a look at it himself if he'll be around.

@Maddremor 
>I will try to make some kind of table as time and mental fortitude allows.
I've made some table on majority of liquids, with comments. The list may require adjustments, updating and conversion if you want it to be exactly 8.7kcal per 1 nutrition. Also, the more mind-boggling thing is checking nutritional value of each (vitamins, iron, calcium) which I didn't do yet. Still, it may be of some help.

`- Drinks, nutrition value (no thirst quenching/alcohol values). 250ml portions. Remember to portion booze - current values also per 250ml. Mostly based on fatsecret, nutracheck and other similar weird websites. Values counted caloric value/10, rounded. 
- Food that's here as liquid and provided in grams, translated to 1g = 1ml even though there likely would be a difference since said food has both liquid and solid bits. 
- Also, using various sites (many of them community-content-based) may lead to some variation in values for similar items so we may want to adjust some for gameplay reasons (seriously, surviving on guzzling cooking oil should not be possible).
- Lastly, there are HUGE differences between different types of milk (especially condensed and regular). Recipes that use them interchangeably probably will need to be changed.
- No info on mash/wort and other alcohols halfway-done

apple cider			13
atomic coffee		0		assumed it's like regular coffee
bee balm tea		0
beer				10
belgian ale			15
blood				11
brandy				57
broth				16		assumed vegetable broth as per 'vegetabble matter' tag
bone broth			9
human broth			9		used bone broth
cheap wine			21		used cheap cooking wine (relatively low-caloric) value
chai tea			0
chocolate drink		20
coffee				0
coffee syrup		83		no idea why so high, probably because it's some ready-made crap
dark cola			9
methacola			9		copied previous value
energy cola			9		copied previous value
condensed milk		107		assuming sweetened, condensed kind (junkfood tag) - just fat or powdered milk should be called as such 
cooking oil			221		used vegetable oil stats
cranberry juice		14		assuming sweetened
cream soda			17
crispy cranberry	11		averaged value of juice and lime soda this thing is made out of
curry with meat		46		assuming it's beef curry, probably not taking 'solid' bits into account
curry				23		assuming it's vegetable curry
dandelion tea		0
dandelion wine		21		using cheap wine stats cause no data
bee's knees			17		don't know the drink, used values of recipeofhealth.com which may or may not be this thing
boozeberry			17		used blueberry wine stats
fancy hobo			26		since it can be made out of all kinds of sodas mixed with strong booze, no exact data. Value of strong wine.
kalimotxo			16
rum and cola		18
screwdriver			21
sewer brew			26		no data, caloric content of sewage varied depending on what's in it. Using fancy hobo/strong wine stats
strawberry vodka	57		based on sweet strawberry vodka
wild apple			26		no data, strong wine value
whiskey sour		39
eggnog				36
spiked eggnog		41
energy drink		11		huuuuge difference between energy drinks of different brands
atomic energy drink 11		copied previous value
European pilsner	12
fruit wine			17
gin					65
homebrew beer		10		big variety here, using beer stats
herbal tea			0
soylent green drink	46		used curry with meat values
soylent green shake	46		copied previous value
fortified soylent g	46		copied previous value
hickory nut ambrosia36		no data, using eggnog value
honey ball			76		ant honey? using normal honey value
forest honey		76		copied previous value
honeygold brew		76		different mixes of honey - using normal honey value
hot chocolate		20		'Hot Chocolate Cocoa (Made with Whole Milk)' value
imperial stout		18		something between regular stout (down below) and wine		
India pale ale		14
Irish coffee		21
fruit jam			62
blueberry jam		62		shouldn't it be just another fruit jam?
strawberry jam		62		as above
fruit juice			12		you may want to increase it a few points since in-game fruit juice is likely sweetened vending machine stuff
ketchup				24
kompot				15
lemonade			10
lemon-lime soda		9
Long Island iced tea23
maple sap			28		if meant to be maple syrup - 65
mayonnaise			97
spiced mead			25
mexican hot choco	29
milk				15		whole milk value
coffee milk			73		somewhat suspicious till I realized it's practically condensed milk lite
curdled milk		13		less than whole milk? weird, data from recipeland for sour milk
milk tea			7		couldn't find decent unsweetened one, average of values between tea and milk (type of milk should matter)
strong mixed alcohol60		average of strong alcohols
weak mixed alcohol	10		base beer value
molasses			100
moonshine			56
mustard				16
mutagens			0		it's like horrible abomination-making tea, right?
orange juice		11		maybe it should be just 12, like generic fruit juice?
orange soda			12		dunno, guess it's not as sugary as I thought it'd be. Given how soda adds to obesity supposedly - dunno.
American pale ale	10
peanut butter		147		liquid? This thing either should be solid like fat or fat should be treated as liquid
pine needle tea		0		
pine wine			21		cheap/dandelion wine stats used
protein drink		25		huge variation here between brands
protein shake		25		similar as above
fortified protein sh25		similar as above
purifier			-20		value pulled from my ass, but it's stem cell thing, should require nutrients to work and multiple cells
grape drink			16
root beer			10
rum					57
single malt whiskey	57		Glenfiddich Single Malt Scotch Whiskey 12 Year, I suspect
chicken noodle soup	13		probably no account for actual solid bits of meat and whatnot, needs adjustment
cullen skink		27		VERY rough estimate, half-winged
chicken & dumplings	37
fish soup			12		based on "Sopa De Pescado"
sap soup			13		let's make the poor fellow a chicken and call it a day (no data)
meat soup			8		Again, probably no solid bits being accounted for? I don't know what other reason for such caloric content.
mushroom soup		13		same site that has the above. Mushrooms more caloric than beef? Apparently!
tomato soup			10		as above
vegetable soup		10		as above
woods soup			11		average between mushroom and meat soups, vide variety of ingredients
soy sauce			13
spezi				10		something between cola and orange soda since it's a mix of those
sports drink		5
stout				15		based on Sierra Nevada stout
sweet water			10		absolutely pulled from my butt, it really depends how sweetened. Made it at soda-level of 'sweet'.
tainted tornado		56		declaring it a zombie moonshine now and giving it similar value
tea					0
bark tea			0
tequila				57
triple sec			68
v8					5		oh how super-filling drink has fallen when faced with reality
vinegar				4		where did the calories go when the booze turned into this? What the hell.
vodka				57
water				0
clean water			0
mineral water		0
whiskey				62
cabernet sauvignon	21
chardonnay			20
pinot noir			20
riesling			20`

**Comment by Shoes01** [comment]
While I am not at all in the loop of the calories/nutrition discussion, the website [Wolfram Alpha](www.wolframalpha.com) might help too. I can search "100g of marshmallow" and it returns calories, fat, sodium, protein for a specific brand of marshmallow. Searching "100g of meat" gives me a ton of info, as well as a dropdown list to specify exactly what kind. Sources are provided at the bottom, too.

**Comment by DegenerateGroundState** [comment]
Candy also has the (short term) advantage for the malnourished in that it contains very little to no protein, which means it is non-thirst provoking. Protein metabolism requires a certain amount of water, so it is mostly excluded from things like lifeboat rations.

**Comment by Maddremor** [comment]
I've made a [spreadsheet](https://drive.google.com/file/d/1CX6Y932SnqYmwAcPv5FgOVcE2KttsCuA/view?usp=sharing) where i added all relevant items from `consumables.json` and added kcal values for the low hanging fruit. Mostly used Wolfram Alpha as a source (thanks @Shoes01 ). Some things do look kind of strange, but thats because weight per serving is off. I used in-game weight per serving and IRL kcal/100g.

**Comment by FulcrumA** [comment]
@Maddremor 
Awesome. If we'd also include different nutrients (vitamins, iron, calcium etc values) we may have all the data now to do full nutrition revamp.

**Comment by Stone94** [comment]
MyFitnessPal has a one of the largest food databases on the net, and also a custom recipe calculater that will take alot of the guess work out of micros and macros.

**Comment by Night-Pryanik** [comment]
No discussion in over half a year, closing.
