### ISSUE TITLE
oceans

### ISSUE THREAD

**Issue by africalinguist** [CleverRaven/Cataclysm-DDA#23987]
It would be cool and make the game more realistic if there were oceans. These oceans should be very, very large, possibly 1000s of tiles. There should also be cities on the oceans, with docks and shipwrecks.

**Comment by uqrs** [comment]
> Probably not worth it, since "ocean" isnt going to have a lot of good gameplay elements, but might be moddable for realism or challenge.

While "Realism" is probably not really a solid argument for implementing something like _Oceans_ into the game, I do believe it's handier to tackle this issue by laying out the possible _Pros_ and _Cons_, and make an evaluation based on these: I think it's handier to think in _solutions_ and _possible ways to make this work_ before writing something off so quickly.

I believe having oceans for "realism"'s sake might not be the best possible approach, though I will admit that having _large bodies of water_ would - under the right circumstances - be more than able to enrich and support fun gameplay.

Perhaps _1000s of tiles_ might be a bit overboard- realistically, you want to be working with _large_ to _very large_ bodies of water (perhaps modifiable by a world variable, not dissimilar to _city spacing_, with _0_ disabling oceans outright).

I urge the following guideline to be effected, should anyone try to implement this:
**These 'Oceans' must be crossable with a reasonably small amount of time and effort**- 'Oceans' must be big enough to not let a player "swim" to the other side, nor must it allow some random player to cross it using a wooden rowboat or rubber boat. **That said**, an ocean should be easily made crossable by a player with a reasonable boat, at around the same point in time where the player would otherwise acquire a car (needless to say- introducing oceans into the game _would_ require a more advanced boat-building system, similar or built-in to the current vehicle system). Ignoring this rule outright would probably end up '_crimping_' map generation, and halting players dead  in their tracks, causing them to curse "Oh for the love of god- another uncrossable damn ocean".

On the upside, should something like this be implemented, we can expect a multitude of cool, explorable return concepts:
- Coastal cities, perhaps with harbors, a beach scene, and stuff like a beach boulevard (put some more work on our Urban Development friends ;) )
- Beaches. Long stretches of beach, dunes, other cool map generation.
- Small to Multi-tile shipwrecks. I'm talking anything from someone's hobbyist speedboat to a massive _freighter_.
- Islands, coupled with optional island-based survival scenarios.
- Diving, with corals and fish and other cool stuff.
- If we want to insert **plot-related content**, then perhaps a underwater laboratory a la Deus Ex could be a nice concept.
- Rivers that empty out into oceans, coupled with the required boat system, could be a cool alternative way to get around other than roads/cars.

**I should note** that this would undoubtedly be a big undertaking: making Oceans a viable part of gameplay that's fun and exciting (as opposed to a hindering nuisance) will require a lot of work, both in actual map generation, would require the team to generate an explosion of additional content and buildings that would populate this _Ocean setting_, and the aforementioned _Boat_ system would have to be implemented into the base game as well to accommodate ocean/seafaring gameplay. I don't know if that's at the top of the list of priorities right now- as fixing the current world/city generation (see: Urban Development) seems like a pursuit that might be more beneficial for now.

**Comment by FulcrumA** [comment]
I am not really sure there'd be a point. Game would just generate huge swats of useless terrain with no real interesting features - because that's what ocean would be in current rendition. And to forcefully make it a huge project to spiff it up while it's unlikely that the game's target audience was ever wannabe sailors would be kinda disruptive.

**Comment by FulcrumA** [comment]
@JayThirtySeven 
In theory yes, in practice, as actual game content - no. Which is the issue I talk about - to add huge bodies of water that aren't just waste of space on the world map, you need to add whole slew of features to them so they aren't useless. If oceans aren't as varied and interesting as ground overmap, a few people may enjoy embarking onto them in a boat as the endgame goal before quitting, but most people will simply avoid them, be bothered that there's even more to traverse before finding anything fun, it's harder to find anything fun.

Oceans etc may work, but only as a part of huge revamp that would add things to them. And even that may be hard because let's be honest - sailing can be fun, but oceans themselves ARE kinda boring, at least on the surface without adding things to happen there "by force" or going even more ambitious and adding diving, underwater features, places of interest, associated mechanics etc - which makes it suddenly nearly a new game in its own right.

**Comment by uqrs** [comment]
>Oceans etc may work, but only as a part of huge revamp that would add things to them. And even that may be hard because let's be honest - sailing can be fun, but oceans themselves ARE kinda boring, at least on the surface without adding things to happen there "by force" or going even more ambitious and adding diving, underwater features, places of interest, associated mechanics etc - which makes it suddenly nearly a new game in its own right.

The huge revamp would need to be part of this project- I agree completely on that a lot of features would need to be added to make this viable. I do think that some kind of system for large bodies of water in the game would add countless of possibilities for extra content that wouldn't need to be added "by force". The oceans wouldn't need to be boring- I could see plenty of ways by making them more interesting with actual engaging map generation, such as coastal cities, boulevards, beaches, archipelagos connected by bridges, shipwrecks, underwater laboratories, massive harbors, etc.

"Ocean" might be a misnomer here, as I suggest that we add "very large bodies of water" instead of anything resembling a _massive real-life ocean_ that will take ages to cross.

I stand by it that this could very well work in practice- what you fear is not the concept of oceans itself, but rather any kind of failed or half-assed implementation.

A "new game in its own right" I would hardly call it. Diving seems like a secondary additional thing that could be added if needed- honestly just a big amount of interesting terrain generation and a boat system that's relatively easy and non-painful to get into would be enough to make this worthwile.

**Comment by smolbird** [comment]
It might further be augmented if some more fantastic elements are added into the body of water itself. The occasional island is a logical choice, including unexpected volcanic developments. Could have such cataclysmic things as a mutated coral reef that's overgrown and breached the surface, island cities of stone packed with anomalies (if we had good spacial anomalies to play up the Ry'leh angle that'd be perfect), literal ghost ships, an obligatory Bioshock reference...

More mundane structures could include volcanic islands, desert islands, small communities built on artificial island structures, patches of marine debris (though making it so dense that it counts as valid terrain would be a misconception), etc.

And of course lost ships of various kinds. Military vessels of varying size, with useful supplies and possibly hostile robots. Drifting or stranded cruise ships, quite likely infested with undead. And of course pirate ships of the more modern sort, whose inhabitants might not be zombie. Though a proper old-school pirate ship with angry cutlass-swinging NPCs would be a perfect addition to Crazy Catalcysm.

**Comment by BorkBorkGoesTheCode** [comment]
Adding oceans would allow the player to interact with the Old Guard flotilla directly.

**Comment by jtgibson01** [comment]
There's already some water-related content in the game files, such as shipwrecks and such -- and BorkBork mentioned the Old Guard which is also highly relevant.  (Presuming that their flotilla is actually a thing and not just a rumour to get people to fishmonger for free!)

I do think the ocean should just be an endless swath of ocean that starts at a certain X distance, with entire overmaps devoted to ocean terrain.  This would force the player to remain coastal as simply sailing out into the ocean would be meaningless (and avoid any confusion over "what happens when the player crosses the Atlantic").  The gameplay would come from being able to use the ocean to sail up and down the coast, and to run into occasional islands or special maps in sight of the coast.  Adding traversable oceans that generate fractally like the forests would be more detrimental to gameplay than beneficial, IMO, because it would make the game resemble Finland more than New England and would simply complicate overland foot and vehicle travel unnecessarily -- it's not an ocean game, and zombies and survivors are both inherently land-based.  Something like the Great Lakes or massive hydroelectric lakes would certainly be interesting, but should be relatively rare (i.e., appear once every few full-sized overmaps at an absolute maximum, preferably much less).  To me the eventual late game seems to be heavily intended to focus on faction content... since there's only one faction associated with the ocean, unless we're just looking for the Old Guard to be a Fallout 2 Enclave expy there needs to be a focus on faction wars on land.

There's another advantage to the ocean as a single broad entity that occurs at a predictable distance: it exists as its own constrained mid-game ecosystem that the player can optionally interact with or not.  The player can continue to interact with the heartland, or head out to the coast to interact with the coast, or jump between the two as the mood strikes.  There's also a fair bit of low-hanging fruit for incremental additions of coast-related content without needing to worry so much about what's out in the middle.  Shore-hugging whale pods (no more whalers, after all) -- loads of meat, loads of hide.  Rotting explosive beached whales.  Infested whales filled with strange parasites.  Sharks.  Murderer whales and zombiehead sharks.  Oil deposits.  Fractional distillation towers and refineries.  Resorts.  Fishing docks.  Shipyards.  Naval yards.  Container ports.  Old Guard coastal outposts.

Also, to deter turtling and long-term stay over the water, water of all sorts should be either A) intentionally boring or B) infested with aquatic monsters or zombies that catch up to the player slowly.

**Comment by nexusmrsep** [comment]
New England has a costline to the east, where Atlantic Ocean sprawls. From RP reasons it is reasonable. And i agree with @jtgibson01 that its full of possibilities. And you can always go West.

**Comment by ZhilkinSerg** [comment]
https://www.reddit.com/r/cataclysmdda/comments/8vcant/canoeing_down_the_bayou/

**Comment by kevingranade** [comment]
Interesting discussion, but it gets us no closer to the feature than just mentioning the desire for it.  Closing as inactive.
