### ISSUE TITLE
Adjust weapon breakage to specify what parts the weapon breaks into.

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#24018]
As brought up in recent [fragile spear PRs](https://github.com/CleverRaven/Cataclysm-DDA/pull/24005#issuecomment-397706156), since fragile melee weapons are generally fragile in a specific way, it makes sense to specify what the breakage products are.

Examples:
* Knife Spear -> Spike + Heavy Stick + fraction of bindings.
* Forked Spear -> Same
* Glass Shiv -> Nothing specified, actually breaks.
* [Macuahuitl](https://en.wikipedia.org/wiki/Macuahuitl)! -> Stick or 2x4 + sharp rocks.

Additionally, one component (the haft generally) can be specified to stay wielded by the player.

**Comment by Vasyan2006** [comment]
Glass shiv was a single use weapon before because of material: glass. Maybe we should destroy a component with weakest durability based on material (bindings for knife spear and stone hammers) and return other components damaged. And/or specify weakest component if required, using a bow as a melee weapon will destroy the stick instead of the rope. Some weapons (like Macuahuitl) should be disassemble into all components instead of destroying (add flag for that).
