### ISSUE TITLE
Inconsistency in skills upgrade cost at chargen

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#24056]
Game version: 0.C-7473

Operating system: Windows XP SP3 x86

Tiles or curses: curses

Mods active: default only

### Expected behavior
Upgrading skills cost at chargen should be the same no matter if there is some bonus for skill from profession or not.

### Actual behavior
![default](https://user-images.githubusercontent.com/11132525/41649137-7ca6e88a-7483-11e8-8331-2e29c4b30767.png)

![default](https://user-images.githubusercontent.com/11132525/41649166-8e1dc750-7483-11e8-94cb-a0db97a17aeb.png)

Profession "Traceur". On the first pic we see that upgrading cutting weapons (and any other skill except for dodge) from 5 to 6 costs 3 points. On the second pic we see that upgrading dodge from the same 5 (1 + 4) to 6 costs only 1 point.

### Steps to reproduce the behavior
Take profession "Traceur" at chargen, move to the `SKILLS` tab, set cutting weapons and dodge skills to 5, look at the "Upgrading X costs Y points" text for both.

**Comment by AlienZimogor** [comment]
At least, need a initial fix for a cracked skill progression:
How it works now(prof with 4 bonus and free 4 pts)
Pts 1 1 2
Skl 6 7 8
Bns 4

How it HAVE TO works
Pts 1 1 2
Skl 3 4 6
Bns 1 1 2

Idea is simple: separate way of calculating prof bonus. And further, if these rules do not change at all situation with 99999dodge/fabrication/melee/unarmed/tailor and etc, would need a next, more violent fix.

**Comment by 1skandar** [comment]
Think this is working as intended. You are already heavily incentivized to choose stats over skills *anyway* (stats can only be raised after char gen in a very limited fashion, so investing in skills is, generally, a dumb thing to do) so having something that gives a slight advantage take the other way doesn’t seem out of line.

**Comment by DracoGriffin** [comment]
>Think this is working as intended. You are already heavily incentivized to choose stats over skills anyway (stats can only be raised after char gen in a very limited fashion, so investing in skills is, generally, a dumb thing to do) so having something that gives a slight advantage take the other way doesn’t seem out of line.

No, the point threshold is ignoring the profession skill bonus and acting as though the +4 to Dodge is actually just 0. (If you already knew this, then at least I'm just establishing this more clearly for others reading)

![professionfreepoints](https://user-images.githubusercontent.com/32253888/41698944-752b58ba-74de-11e8-8b4c-ba207f308c4c.png)

And whether professions are meant to cost the total amount of points that it takes or some sort of shortcut or otherwise, I'm not sure. The total cost of Traceur is 3 points, the Parkour Expert trait is worth 2 points, and getting Dodge to +4 requires 4 points (1 pt for 0->2, another 1 pt for 2->3, and then 2 pts for 3->4) for a custom character total of 6 points for what Traceur takes with half the points.

Now I know this isn't the only profession to do this but it's a good case example. The only thing is I don't think there's any sort of game balance design doc for professions and if there is, I don't recall reading it / seeing it.

National Guard costs 4 points, only gives +1 Marksmanship / First Aid (which incidentally, would technically cost a custom character a total of "1" point, since every one point spent on skills gives the initial increase from 0->2).

Then you have Special Operator which gets a ton of skills, nice submachine gun but only costs one more point than National Guard (which doesn't give any weapons but does give a go-bag).

Then you have all the various Bionic professions which are much more difficult to analyze, especially now with the AutoDoc changes (although you can still do manual installation, it may not be forever). Some of them are also 5 points, but some of those CBMs can be incredibly rare -- and to have it right at game start, rather than hunting and all that's required to install CBMs (generally relegated to mid-game).

So back to Traceur -- 3 points, gives a few extra stuff in dodge. Is it a huge deal? No. Could it be an oversight? Potentially. However, it seems like an extremely minor hill to die on when you have much more cost-effective professions (seriously, all the Bionic professions are 5 points, and give massive amount of really good CBMs, and Cyborgs are 6 points, same deal. And at this point, shoot, why not go for 8 and get the Bionic Sniper/Assassin but wait, then there's Blackbelt which basically gives a martial art for free and has high unarmed melee skills which is kinda underwhelming when compared to the other 8 point professions).

The better solution would be to establish a guideline / design doc for professions (with this issue in mind), fix the profession skill bug, then fine-tune the existing professions.

**Comment by 1skandar** [comment]
I get what the OP is saying, yeah. Im just saying this could very well be working as it is intended to work, that the bonus is ignored and only skill points invested from the pool counts towards the cost, not any points given by the profession. Please note that you *also* get the standard +2 to the skill for the first point spent, which is *decidedly* working as intended. (otherwise professions that give only a +1 bonus to a skill would be worthless). 

As for the point cost of the various professions, yeah the balance is likely wonky as all hell. The problem is you have to value not only starting skills, but starting CBMs and starting equipment. However, that is a completely separate issue.

**Comment by Zaabass** [comment]
There are actually three ballance issues here:
First, Traceur prof is too good, it should be either 2 dodge prof or -5 point prof.
Second, dodge is too good. I honestly don't know how to fix it, but it's a fact. With dodge 10 your character is virtually invulnerable to meele attacks, and currently 4 base dodge just makes getting it too chap.
And last, profession skills are too good. And no, more linear progression won't ruin 1 skill profs. You will simply get it to 3 points for 1 SP and to 4 points for 2 and go on as usual. You can look at it as a continuation of character creation ballance changes that came with the pools system.
Those are all issues that need to be fixed.

**Comment by papersplease** [comment]
Traceur is fine IMO, he should clearly be better at dodging than a dancer and worse than a martial artist, and dodge 4 isn't a lot really, if the inconsistency described isn't being exploited. Regarding high level dodging being a bit too OP, I'd say it's fine as it is, but it should probably be counterbalanced by something to not allow you dodge indefinitely. I mean, it doesn't even consume stamina, and IRL dodging is quite exhaustive. (just giving an idea here, or maybe make it less effective based on exhaustion, particularly to make Zui Quan + high dodging look less ridiculous, etc)

Anyway, this is a bit off-topic here I guess. OP is right and this is inconsistent behaviour at the very least. Taking you from some skill value to another one should take the same points for two non-posthuman characters with similar stats, that just... makes sense?

**Comment by railmonkey** [comment]
I've wondered every now and then about this very inconsistency. I agree with establishing profession guidelines and addressing the behavior mentioned in the OP. I think, however, that the fix should be aimed at the professions themselves rather than reworking the skill point investment. If you think about it a bit, each profession represents up to several years of time spent acquiring the skills beforehand. It makes sense that they come as freebies rolled into the cost of the profession. Anything that you drop points in beyond that accounts for either talent or dedicated study/practice. As for Traceur in particular, the point cost was hashed over already both on the forum and in the original pull request. I'm open to having it bumped up as part of standardizing everything, but here is the original PR for reference: #14376.

**Comment by papersplease** [comment]
@railmonkey 
> If you think about it a bit, each profession represents up to several years of time spent acquiring the skills beforehand.
Actually you could be on point here, but for a bit different reason. The profession could represent a _natural inclination_ towards some skill set (chemist, military, mechanic etc), which also makes sense indeed, and additionaly makes characters more specialized, which is good for balance/replayability and stimulates the player to try different builds. In the light of this, the current system makes sense.

>I think, however, that the fix should be aimed at the professions themselves rather than reworking the skill point investment.
The problem with this is that it's not easy with current system, because the granularity is poorly thought out. The CDDA design outline gives a clear 0-10 range for skills, where 10 is a skill avaliable at a maximum human capability. And the current system is rather easily exploitable in this regard; for example you can easily get 14 (!!!) dodging for a Blackbelt character in certain scenarios, because the Black belt has 8 as a starting value. According to the design outline and actual in-game performance, 14 dodging is way beyond the human capability and should only be available for augmented characters (mutants/bionics). The character with that kind of skill is 99.9% immune to any melee attacks even when encumbered, he/she can easily fight in an ANBC suit for example. But at the same time, 8 dodging is perfectly reasonable for someone "competitive at national level" as the legend says. I think there's no easy solution for that; either the current multi-pool system is insufficiently sophisticated, or the whole chargen mechanics is wrong.

**Comment by papersplease** [comment]
To add to this: extremely high skills are intended to be countered by skill rust. In theory...

**Comment by l29ah** [comment]
blackbelt + infected + uberslow healing + str + dodging/melee/unarmed = totally OP character

**Comment by anoobindisguise** [comment]
This can be closed now because of the new chargen system.
