### ISSUE TITLE
Problematic recoil logarithm

### ISSUE THREAD

**Issue by Heaper327** [CleverRaven/Cataclysm-DDA#24066]
Game version: 0.C-28368 (lastest)

Operating system: Mac osx 10.13.5

Tiles or curses: Tiles

Mods active: None

int qty = gun.gun_recoil( *this, bipod );
        delay  += qty * absorb;
        // Temporarily scale by 5x as we adjust MAX_RECOIL.
        recoil += **5.0** * ( qty * ( 1.0 - absorb ) );

This part of the source code handles how the recoil resulted from firing a shot is added to the total recoil, but for some reason, the recoil from firing a shot is multiplied by 5 before added to the Total recoil. I don't see what adjusting MAX_RECOIL has to do with recoil from single shot. This has resulted in extremely inaccurate burst-fire and automatic fire.

**Comment by kevingranade** [comment]
This was rescaled based on the effective range of recoil being rescaled, i.e. the max recoil value was multiplied by 5, and the accumulation of recoil was scaled by the same amount to make it reach max recoil in the same number of shots.  
Unless you have some criteria for how fast is "too fast", this issue is invalid.  We can reopen it if such criteria are posted.
