### ISSUE TITLE
improve throwing menu

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#24144]
Afaict, the fundamental tradeoff in throwing is going to be how hard you throw vs how accurate the throw is, but I haven't thought of a good ui for exposing this, until now.

The proposal is to adjust the throwing menu to be similar to the firearm menu, but instead of separating by 'aim level', it breaks down by throwing intensity, ranging from, "hard enough to reach target" to, "as hard as you can throw it".

Throwing intensity mostly trades off accuracy for damage, but harder throws will also spend more moves.

**Comment by DracoGriffin** [comment]
Should stamina play a role? Given athletes [generally have their own limits](https://en.wikipedia.org/wiki/Pitch_count), as stamina decreases, range and power decrease, with pain inflicting at 0 stamina, similar to running with expired stamina. Maybe even have arm throw preference so if the survivor switches arms, throwing is also hampered -- unless have some ambidextrous-like trait.

**Comment by Blank99** [comment]
Speaking of menu, and sorry for this being a bit of a tangent:
Throwing would benefit from having it's actions streamlined so it either auto-chooses throwing weapons if one is being wielded, you have a way to mark what your default thrown weapon will be, or it autochooses the last thrown weapon.

Because going t -> (inventory letter) -> enter gets tiring annoying fast, even after changing inventory letters so the thrown items are readily accessible.

The current system also lends itself to impromptu strip-teases where your character attempts to distract zombies with clothes when you keep mindlessly repeating the throwing key sequence and miss that your throwing sticks ran out.

---

As for the question, it sounds good to me.

**Comment by kevingranade** [comment]
Another setting for the menu would be "throw at monster" vs "throw into area". I *think* this would be one of the hotkeys, it doesn't seem like it would overlap with any of the other settings, and it would imply, "actively avoid hitting a target" as a priority.
