### ISSUE TITLE
Bird feed

### ISSUE THREAD

**Issue by DemAvalon** [CleverRaven/Cataclysm-DDA#24216]
Now that we have the means to raise chickens (and other birds) we could get an item (like we have cattle fodder) to make chickens (also ducks and cockatrice?) friendly, so my NPC friends stop bashing them into oblivion because chickens dared to cross their path, I'm not saying that they should follow the player (even though speaking from experience, raising chickens from chicks all the way to adulthood makes them very friendly, walking close to you and even letting you get close and pick them up) but at least make it so companions won't treat them as enemies.

Also, if this is implemented, we should be able to put them in pet carriers for safe transport (that way if the player wants to move some place else they don't have to start their chicken coop from zero)

**Comment by mlangsdorf** [comment]
So adding a CHICKENFEED flag is pretty easy, and I'm doing that now.

I'll figure out the pet carrier.

My question is what are chickens fed so I can put together a recipe for chickenfeed? I figure I can start with the cattlefodder recipe, cut the weight, cost, and ingredients by a factor of 5. I think chicken don't eat vegetables, so I'm going to replace the wild veggies with seeds, but if there's a more sensible choice I'll do that instead.

**Comment by mlangsdorf** [comment]
Pet carriers work automatically if the creature is friendly and small enough to fit in the carrier; no code changes needed.

**Comment by nexusmrsep** [comment]
Use all possible grain (wheat, buckwheat, corn, etc.), and seeds, as this is what they primarely eat. Chickens actualy eat grass, dandelion leaves, etc., but I think we should assume that grass is avalaible all-around, but grain and seeds is "preferable" by the birds, so they will be more tamed then when offering something they already have. And thats what we want to achieve, yes?

**Comment by mlangsdorf** [comment]
Please review and comment.

**Comment by DemAvalon** [comment]
Actually, chickens will eat pretty much anything, cabbages, fruit, lettuce, insects, mice, small snakes, their own eggs, each other (I'm not sure about that last one, never saw it happen, but I would not put cannibalism past them)

Don't kid yourselves, if a chicken ever got the chance it would eat you and everyone you care about:https://imgur.com/s05awRy

**Comment by kevingranade** [comment]
Theres a rationale that dogs and cats are domesticated, and just need an act of kindness to get them to trust you.  I'm sceptical that that applies at all to birds.

**Comment by DracoGriffin** [comment]
>Theres a rationale that dogs and cats are domesticated, and just need an act of kindness to get them to trust you. I'm sceptical that that applies at all to birds.

How about a similar flag that instead of friendly, they are just forced neutral to player to avoid fleeing (or at least, doesn't lose morale when close to player after being "fed") -- common enough with raising chickens, but feral ones would still run. They might not be fully trusting and trainable, but they'd be friendly enough to *generally* not bite the hand that feeds them. Or at least, that's how my friends' chickens act around people and kids.

[Article on befriending crows and lots of tidbits](http://thewildlife.wbur.org/2015/03/12/the-secrets-of-gift-giving-crows/).

>“If you want to form a bond with a crow, be consistent in rewarding them,” advises John Marzluff, professor of wildlife science at the University of Washington. He specialises in birds, particularly crows and ravens…
But crow gifts are not guaranteed. “I can’t say they always will (give presents),” Marzluff admits, having never received any gifts personally, “but I have seen an awful lot of things crows have brought people.”
I asked Kevin McGowan if it is OK to encourage people to feed crows and interact with them as this little girl in Seattle did (and as I once did myself).
With a few cautions provided, he said he’s in favor of positive interactions between crows and people.

And considering the downsides of befriending the animals is mainly because of modern living and humans in a landscape... devoid of such stuff, becomes irrelevant (don't befriend crows because we don't want them to end up being killed as nuisances for people that don't like them or want their attention).

**Comment by mlangsdorf** [comment]
At this point, my preference is to make ducklings and chicks tameable, and then make monster upgrades inherit friendly from the previous monster. So you can't tame a chicken, but you can tame a chick and have it grown into a chicken that is friendly.

Adjusting monster AI so there's a tolerant state where the monster will never go hostile against you is way more work than I intend to put into this PR.

**Comment by DracoGriffin** [comment]
>Adjusting monster AI so there's a tolerant state where the monster will never go hostile against you is way more work than I intend to put into this PR.

No worries, that's why it's addressed in this Issue, rather than a suggestion in your PR. It's just something to think about in the future if this topic is addressed again or further. Plus, kevin didn't offer an answer, so it doesn't mean much anyway.

**Comment by GroeneAppel** [comment]
Chickens (and most birds) are omnivores, and will eat and consume just about whatever edible they will find on the forrest/jungle/barn floor. Whether this is worms, seeds, bread, pieces of meat  or berries. They will happily consume this. This also applies to the modern bred chickens, who really won't shy away from eating any of the above. 
A few random (non scientific) sources when searched for also support the above. 
Eg:
https://www.backyardchickencoops.com.au/what-do-chickens-eat-in-the-wild

>Still grain is most common: THIS.

A quick note here: Most (including chickens) birds that are fed only seeds will have their lifespawns drasticly shortened. It's critical to feed your birds a varied diet of berries, veggies, seeds etc. 

>Theres a rationale that dogs and cats are domesticated, and just need an act of kindness to get them to trust you. I'm sceptical that that applies at all to birds.

It's right to be sceptical here, as taming birds does not work like taming a dog does. Birds are best tamed/trained when very young, as older birds typically need much more effort to tame. The main rule to understand with birds is that they consider any kind of attention, the good kind. To receive a response from their owner for them is a good thing, regardless of the kind of response. 
Yelling at your birds after they bite you therefore is a great way to encourage them to bite again in the future. Hitting/hurting birds in any way is also a great way to destroy any trust you've built with them. 
Training a bird involves rewarding positive behavior and _ignoring_ bad behavior. Which is rather hard when the bird in question has just bitten you. 

To give an example, the first thing an owner will want to train their young bird is to "step-up" which is a simple act where the bird simply steps up to the owners fingers/hand. This is done by repeatedly putting their fingers next to the bird and having them step up your finger on their own accord (with the help of a little food at a distance to lure them). Once the bird steps up, they are rewarded with food and then the process is repeated many times. Once the bird performs the act without any encouraging you know you've taught your pet how to step up. 

Note: Most of the information above is based on many topics i've read around and my own experience. Since i'm rather fond of birds and i've owned budgies for a large part of my life.

Now as to my ideas:
Bird feed could either be tackled by simply letting the player leave non processed food around, or if we wish to be more specific could be handled by having the player craft bird feed from individual (broken up) pieces of food. This could be a crumbled up bread, berries, pieces of meat chopped up etc. This could then perhaps even be loaded to a feeder if we want to further increase control (and reduce clutter!). This could also encourage chickens and other birds to stay near the feeder as they are aware of the existing food supply. 

Not related to this PR but worthy of attention: (chain) Fences currently don't really hold anything in them. This really should be the case if we wish to further develop systems like keeping chickens.
