### ISSUE TITLE
Making survivor mess kit from stone pot incorrectly increases food cooking

### ISSUE THREAD

**Issue by svick** [CleverRaven/Cataclysm-DDA#24227]
Game version: b33cfe4

### Expected behavior

Crafting survivor mess kit does not increase the food cooking quality beyond what its components have.

### Actual behavior

When you put a stone pot near an oil cooker and call it "survivor mess kit", it apparently magically increases how good the stone pot is, even if you don't use the oil cooker.

Specifically, stone pot has food cooking of 2, while survivor mess kit, which can be crafted out of it, has food cooking of 3.

It seems to me a reasonable solution would be to remove the stone pot option from the recipe for survivor mess kit.

**Comment by TechyBen** [comment]
Would the stone pot not have different weight considerations too? So I can understand that part not meeting requirements in quite a few areas.

**Comment by FulcrumA** [comment]
I believe that in general, final product doesn't track qualities of it's components for determining final qualities. It's not just with mess kit and pots, it's basically every item in the game. 
It would be nice if components would determine quality of the final product - from various combinations of ingredients making a fluid sandwich item with different nutritional content to being able to create slightly modified/customized/improved equipment using rare/varied quality components - but we're nto there.

**Comment by DracoGriffin** [comment]
>I believe that in general, final product doesn't track qualities of it's components for determining final qualities. It's not just with mess kit and pots, it's basically every item in the game.
It would be nice if components would determine quality of the final product - from various combinations of ingredients making a fluid sandwich item with different nutritional content to being able to create slightly modified/customized/improved equipment using rare/varied quality components - but we're nto there.

Well, two-fold: no one has offered to do it really and secondly, it's one of those things that apparently development does not want Dwarf Fortress-esque crafting (where you make X template item, but can use different materials for different qualities, say, making a spear out of copper instead of steel results in a poorer quality spear). But I am not 100% on the second part, it may be my misunderstanding.

**Comment by DracoGriffin** [comment]
[Here's the PR](https://github.com/CleverRaven/Cataclysm-DDA/pull/10469) where it was added.

@Rivet-the-Zombie, since you added it, do you want to explain the reasoning (I didn't see one in the PR) or how would you like to handle it?

Otherwise, the one I see it, the survivor has somehow finagled these together that utilizes the pot to a much more beneficial effect -- however, it is true, if you have the items apart singularly, shouldn't that act similarly? Or perhaps it's missing some duct tape or cordage to show it's been connected in some makeshift way?

**Comment by RadHazard** [comment]
>apparently development does not want Dwarf Fortress-esque crafting (where you make X template item, but can use different materials for different qualities, say, making a spear out of copper instead of steel results in a poorer quality spear)

Is this true?  I was actually hoping to work on something to that effect if I ever got the time.  There are a lot of redundant recipes that could be collapsed into one if we could make the resulting item depend on the materials used to craft it.

**Comment by FulcrumA** [comment]
>apparently development does not want Dwarf Fortress-esque crafting (where you make X template item, but can use different materials for different qualities

>Is this true? I was actually hoping to work on something to that effect if I ever got the time.

First time I hear about it myself. Someone from the 'core' team should drop an input on this.

**Comment by Amariithynar** [comment]
Same happens with Toolbox and using a stone knife, hah.

**Comment by FulcrumA** [comment]
Calm down, Draco. I've put part of your context merely to maintain context for RadHazard's comment which I regarded. You're not accused of anything, you do not need to defend yourself. 
Also, yeah, guess we can just ping @kevingranade so he can give an opinion on the whole thing.

**Comment by kevingranade** [comment]
I'm not enthusiastic about calculating item *stats* based on construction materials because it leads to either:
1. Requiring contributors to know a lot about the system to get the item stats they need. (AFAIK this is what df does)
2. Overriding the calculated stats, meaning the desired consistency of this kind of system is not realized.

Adding *flags* to items based on crafting components used seems reasonable, but it needs a sensible json representation and ui, and I dont know what that should look like.
