### ISSUE TITLE
Cooked Acorn Meals have no spoilage and give too much nutrition

### ISSUE THREAD

**Issue by StripedMonkey** [CleverRaven/Cataclysm-DDA#24255]
Cooked acorn meals are currently overpowered with their 42 Nutrition and 0 spoilage. I suggest, instead of adding a spoilage we simply lower the nutrition to 9 like we have with fried seeds as this is pretty close to the same thing although I have no clue how much nutritionally they vary. It seems semi reasonable as I've gotten 50+ "meals" in the fall.

**Comment by Amariithynar** [comment]
Acorns are incredibly high in nutrition, though, so this wouldn't really be accurate. However, acorns that haven't been soaked to remove the bitter tannins (leeching) are just that, bitter (though some varieties are less bitter than others, even those varieties are still quite bitter, but edible), so it should have a major negative Enjoyability penalty. Another problem is the ease of preparation; you don't roast acorns in-shell just like you dont roast chestnuts or hazelnuts or any hard-shell nut in-shell without at least scoring the shell to allow air to escape; it basically is a miniature pressure cooker. https://www.youtube.com/watch?v=slqA-H6jums . Currently you just have to cook them at a fire to obtain ground, cooked acorn meal, instead of having to first shell them like with hickory nuts, then use a mortar and pestle, a quern, or a food processor to grind them up into meal, which should be "unleached acorn meal", that then needs to be either "fermented" in a vat into "leached acorn meal", which should give you some tannin as byproduct; tannins are used to tan hides (where the word "tan" comes from), or just washed with water for a long time (and a very small batch multiplier, since you really just need more water for a larger volume, not more soak time). It should also be given the same spoilage rating as flour and cornmeal, be usable in the same recipes once prepared, as well as be able to be cooked as is for immediate edibility into the currently existing "cooked acorn meal"; it should also be able to be boiled with water to make "acorn coffee", though it shouldn't have the same tiredness-reducing effect. Supporting source: http://www.askaprepper.com/use-acorns-survival-food/

If I knew how, I'd try to write the changes myself.

**Comment by StripedMonkey** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/items/comestibles.json
Line 6062.
I can agree with the enjoyability modifier but like I said, they're extremely common so I'm unsure the best way to mitigate that.

**Comment by StripedMonkey** [comment]
Nutritionally do you have any sources as to what they actually are?

**Comment by Amariithynar** [comment]
http://tacticalintelligence.net/blog/how-to-make-acorn-flour.htm which is another source for how even white oak acorns need to be leached references http://nutritiondata.self.com/facts/nut-and-seed-products/3083/1 for nutritional data.

>    "type": "COMESTIBLE",
    "id": "acorns_cooked",
    "name": "cooked acorn meal",
    "name_plural": "cooked acorn meal",
    "weight": 212,
    "color": "brown",
    "comestible_type": "FOOD",
    "symbol": "%",
    "healthy": 1,
    "nutrition": 42,
    "description": "A serving of acorns that have been hulled, chopped, and boiled in water before being thoroughly toasted until dry.  Filling and nutritious.",
    "price": 90,
    "material": "veggy",
"volume": 1

What about it? Or are you saying "this is how it's recorded, so you can write up a replacement for it"? Because the recipe really doesn't match the reality of it. It takes a lot more than 24 minutes and just a cutting 1 implement and food cooking 2 implement to shell, dice, pulverize (without food processor), boil, and then toast acorns, to process them into meal. Basically: The nutritional value being very high is pretty accurate, but it is actually a lot more labour-intensive to actually produce anything that we consider palatable from them. If you want to just roughly shell, halve, and boil them, then eat the soft, boiled nuts, that's a different story; even then, though, it takes 6 minutes alone to shell hickory nuts, and then an additional 24 to roast them, as the nearest comparative for acorns. That seems like a much more accurate timeframe, too. As for grinding them up, from experience, it doesn't take TOO long, since they're actually pretty soft nuts; for each serving of meal, maybe another 20-30 minutes by mortar and pestle (they're just too small to do large batch processing, but are great for herbs or mixing together ingredients to make a crushed blend, paste, or extract), maybe 10-15 by quern, and just 30 seconds-2 minutes by food processor. So in total, to actually do a handful of toasted acorn meal, it should be 6 minutes to shell, between 30 seconds to 30 minutes to grind down, 5 minutes to boil, 30 minutes to soak/leach, 24 minutes to dry out and toast. It should take about an hour to an hour and a half to make a single batch of cooked acorn meal. Consider that grinding flour from any of the ingredients takes a total of 11 minutes through to 1 hour 7 minutes, and we see that it makes perfect sense for acorn meal to take at least as long if not even longer than crops that were specifically domesticated to produce flour. Cornmeal is the same. Plus, as I mentioned, the water that the acorns soaked in becomes saturated with tannins, and can be used to tan hides.

I understand the desire to have a quick meal available to survivalists in the wild with little resources to begin with, but acorns really do require some substantial processing to render really edible, and if you're downing them just to survive, you aren't going to take those precautions, and that's going to taste terrible and, if consumed in large enough quantities, might even mildly poison you, as larger doses of tannic acid does NOT play well with the liver/kidneys/bladder. https://toxnet.nlm.nih.gov/cgi-bin/sis/search / http://jpet.aspetjournals.org/content/77/1/63/a?dbs+hsdb:@term+@DOCNO+831

**Comment by 0be1isk** [comment]
the amount of time it takes to prepare even a single meal is more than enough of a counter to how nutritious it is. it will take you maybe around 3-4 acorn meals to to go from very hungry to full. just cooking in batches of 5 takes 2 hours. Now if you're a fresh spawn, 2 hours is a HUGE amount of wasted time, for only something being able to fill up once. Let's not forget how absurdly heavy they are and how much volume they take up. Unless you're purposefully farming acorn meals, where you purposefully over encumber yourself with multiple duffel bags for increased volume and spend a good 75% of the day scavenging for acorns, they are hardly a a viable means of obtaining a sustainable source of nutrition. If anything farming buckwheat is OP, you can get 500-1000+ each 12 days if you're traditionally farming.

**Comment by GroeneAppel** [comment]
A quick note on the current situation. While they are incredibly nutricious, they take a very long time to prepare. So long in fact, that the player might want to reconsider and find other food sources. Which rather offsets the amount of nutrition they provide. Not to mention you need two of them to make some flour. 

I see @0be1isk mentioned this too. I have tons of unprepared acorns on my current more survival oriented character. I however treat these as emergency food which I rather not waste any time unless I absolutely have to due to a broken limb or something. They just take too much time to prepare from a gameplay perspective to be that great. Im far better off shooting some random animal and cooking it's meat. 

I believe from a gameplay perspective that acorns are in a perfectly fine and balanced position.

**Comment by Amariithynar** [comment]
>If anything farming buckwheat is OP, you can get 500-1000+ (50 nutrition each) each 12 days if you're traditionally farming. You're able to sustain yourself for a year from one harvest.

But... that's accurate? There's a reason that wheat was a staple crop. You can subsist on it as a staple ingredient of your diet, supplimented by other bits and bobs to round out your nutritional profile. It also takes a lot of work to harvest enough, convert to seed, and replant, until you reach critical mass for producing more than you consume in a 12 day (standard season length) period. It also doesn't take much to process, and can be eaten boiled, though it tastes bland as crap (reflected by having no enjoyability rating at all).

>the amount of time it takes to prepare even a single meal is more than enough of a counter to how nutritious it is. it will take you maybe around 3-4 acorn meals to to go from very hungry to full. just cooking in batches of 5 takes 2 hours.

Sausage takes 3 chunks of meat, 3 fat products, some form of seasoning, and REQUIRES a charcoal smoker with 10 charcoal, to make 6 in 1 hour. So you have to actually get enough meat and non-tainted fat to make them in the first place, AND make enough charcoal to make them. That's a LOT of effort, but then, you make sausages because they're long-lasting, not because you want something to eat right that moment. Smoked meat, 3 chunks and 15 charges in a charcoal smoker over an hour to make 3 pieces worth 36 nutrition each. Meat soup requires broth (minimum 20 minutes and requires one of a range of vegetables and some seasonings to make 1; more can be made) or bone broth, which takes a whole hour to make 1, then needs either a veggie, egg, or noodle, and 2 chunks of meat, cooked for 20 minutes, to get 4 portions of 40 nutrition food. If you need immediate food, harvesting dandelions is far more efficient than acorns, taking just two of them, a fire, and 6 minutes beside some water to make cooked dandelion greens, which give 20 nutrition. Or baked dahlia root, 12 minutes and a fire for 28 nutrition (better than a baked potato!). 

And that's not even touching on how inaccurate the recipe is, just comparing it to other foods that take more ingredients and preparation to give you a less efficient product; the recipe, as it stands, IS inaccurate, though, and as mentioned, should give a serving of tanning fluid (used for tanning) when steeped. While nutritionally dense, they take a LOT of labour to prepare for human edibility. Thus why I also suggested a separate recipe where you just crack and roast the nuts directly, at a massive Enjoyability penalty, and potentially some minor sickness if you eat too many; probably best implimented as a disease the same way that Teleglow is applied, or that drugs are applied.

**Comment by StripedMonkey** [comment]
>Unless you're purposefully farming acorn meals, where you purposefully over encumber yourself with multiple duffel bags for increased volume and spend a good 75% of the day scavenging for acorns, they are hardly a a viable means of obtaining a sustainable source of nutrition.

Acorns are absurdly common when scavenging during the fall, every third bush you search seems to give you 2-3 acorns, you can get a full load of them in no time.

**Comment by nexusmrsep** [comment]
What spoilage time would be acceptable? If there are no sources on that, what other comparable in game food could it be compared to, for this purpose?

**Comment by Amariithynar** [comment]
@nexusmrsep acorn meal is high in fats and starches, just like any other flour, and the process of preparing meal does treat it properly. Sure, if stored improperly the oils will oxidize and taste 'off', but same happens with flour, and it's still perfectly edible for months. Still think the recipe needs to be changed, though, as outlined and sourced above.

**Comment by nexusmrsep** [comment]
I am for adding a quern or food processor for grinding, extra water for tannin removal, but all other processes are included in time used to make them.

**Comment by GroeneAppel** [comment]
Frankly I think this discussion has a much bigger underlying issue. Namely how the process of 'crafting' for cooking works. The player cannot perform any other task while cooking, even when a certain task does not really need the players attention. 

Take for example the smoking meat, a great way of preserving it. 
Following these two references [1](https://www.smoking-meat.com/smoking-times-and-temperatures-chart) [2](http://www.smokymtbarbecue.com/bbq-tools/bbq-smoking-times-temperatures-chart.php) smoking meat can take from 1 hours to 20 (!) hours time. 
We cannot expect the player to be actively watching his meat get smoked during this time. Nor does it make sense that this act should be repeated for each piece of meat that is smoked. More sensibly, the player should be able to smoke hunderds of pieces of meat if he so desires. The biggest prep time here would simply be the time it takes to put the meat pieces on a stick. 

Now let's look at preparing acorns. As it is, the description of preparing acorns hints at a very intensive preperation. It would make sense to believe that the player can't really do anything else while preparing them. On the other hand, when the player boils water, smokes meat or performs other cooking acts which don't need much attention, it makes little sense to force the character to just stand there watching his products cook. 

I feel that if we truly want to start properly balancing cooking and preperation times, we should start looking at how much effort is actually involved. Things like smoking for preservation should only require the player to ready the meat and to later pick it back up as whatever proces has done it's job. Finely chopping up nuts and roasting them should force the player to the task at hand. This way things like sausages mentioned by @Amariithynar would make much more sense. As it is a product which can be produced in very large quanities once everything has been properly set-up.

**Comment by 0be1isk** [comment]
> But that's accurate? There's a reason that wheat was a staple crop. You can subsist on it as a staple ingredient of your diet, supplimented by other bits and bobs to round out your nutritional profile. It also takes a lot of work to harvest enough, convert to seed, and replant, until you reach critical mass for producing more than you consume in a 12 day (standard season length) period.

I've always been under the impression that 28 days is the standard condensed season time frame in video games. Ex. Stardew valley., and while one game example isn't by any means a compelling point it makes far more sense then 12 days. Condensing a season into a month for video game purposes is far more logical. 

> Sausage takes 3 chunks of meat, 3 fat products, some form of seasoning, and REQUIRES a charcoal smoker with 10 charcoal, to make 6 in 1 hour. So you have to actually get enough meat and non-tainted fat to make them in the first place, AND make enough charcoal to make them. That's a LOT of effort, but then, you make sausages because they're long-lasting, not because you want something to eat right that moment. Smoked meat, 3 chunks and 15 charges in a charcoal smoker over an hour to make 3 pieces worth 36 nutrition each. Meat soup requires broth (minimum 20 minutes and requires one of a range of vegetables and some seasonings to make 1; more can be made) or bone broth, which takes a whole hour to make 1, then needs either a veggie, egg, or noodle, and 2 chunks of meat, cooked for 20 minutes, to get 4 portions of 40 nutrition food. If you need immediate food, harvesting dandelions is far more efficient than acorns, taking just two of them, a fire, and 6 minutes beside some water to make cooked dandelion greens, which give 20 nutrition. Or baked dahlia root, 12 minutes and a fire for 28 nutrition (better than a baked potato!).

While I understand what you mean, this is breaking very  close to making recipes into mundane ultra realistic simulations. Many of the chemical recipes are REEEAALLLY pushing it for game simplicity. Lye powder generally can't really be made from charcoal and water, but rather wood ash and water, even then we don't have to go through the process of putting it in vats with a filters at the bottom. We don't have to determine what wood ash we need (different trees produce different forms of lye). We don't need to choose between "hard" or "soft" water (determines the quality of soap is used for making soap). We also don't get a by-product of lye water since that's the whole point of the water, to leech out the potassium from the wood. kevingranade has stated multiple times that there needs to be a balance between realism and game simplification. This just seems like a way to bring more mundane chores to dda then there already is. its already a chore to gather the acorns, and its already a chore to waste 2 hours on a batch of 5 where you eat 2-3 of them by default since you spent 2 hours not eating so effectively meaning you spent 2 hours making a batch of 2-3. which is a terrible time:sustainability of nutrition ratio.

**Comment by nexusmrsep** [comment]
> More sensibly, the player should be able to smoke hunderds of pieces of meat if he so desires. The biggest prep time here would simply be the time it takes to put the meat pieces on a stick.

Technically possible by mimicking how fermenting vat or charcoal kiln works and creating a smoking rack that processes it's contents from non-smoked to smoked versions.

> We put things into abstractions for game purposes. In all honesty, this just seems like a way to bring more mundane chores to dda then there already is.

I agree - but - there is a way to have both: converting smoking rack as said above for batch smoking, and leaving the existing recipes for smoked food for those who want to have just one or few smoked items.

**Comment by Amariithynar** [comment]
>I've always been under the impression that 28 days is the standard condensed season time frame in video games. Ex. Stardew valley., and while one game example isn't by any means a compelling point it makes far more sense than 12 days. Condensing a season into a month instead of a fraction of a month for video game purposes seems far more logical.

The default season length on CDDA is 14 days. Buckwheat takes about 10-11 weeks (70-77 days out of 91) to harvest. As each season is a compression of 3 months, 12 days is a good approximation for how long it takes buckwheat to mature and be ready to be harvested. Furthermore, extending the season timeframe also extends the growth period of crops accordingly, so it should always match up.

>Lye powder generally can't really be made from charcoal and water, but rather wood ash and water, even then we don't have to go through the process of putting it in vats with a filters at the bottom.

Actually, yes it can. black soap, or early lye soap, is just made from powdered charcoal, water, and fats mixed together and boiled down. The carbon of the charcoal doesn't inhibit the potassium carbonate in the slightest in this manner. However, the real issue there and what you're trying to touch on is with *purity*, since refined lye powder, that is just potassium carbonate, is of far greater purity than powdered-charcoal-as-lye powder. Furthermore, we do in fact leach water through ashes to form lye, as you later noted with your edit. That's a different process (and has its own issues and has for years, according to multiple issues opened on the topic).

> It's already a chore....

Yes, and preparing acorns as food IS a chore. They aren't an easy source of nutrition, but they can be a good source of nutrition if you put the effort in to make it one. Survival off of foraged food ISN'T EASY. Hell, you don't see me complaining that we need a *pasta extruder* to make pasta, when so many noodles are easily formed by rolling the dough out thin enough and then cutting it into strips and cooking it right then and there, or drying it out and storing it for later, amongst other quirks.

>Technically possible by mimicking how fermenting vat or charcoal kiln works and creating a smoking rack that processes it's contents from non-smoked to smoked versions.

A good start, especially since it doesn't really matter how much meat you're smoking, you still need to smoke it for the same amount of time to saturate it properly. glad we agree on more than one thing! ;P Really, we shouldn't be able to smoke meat in a few minutes by hand, at all; that's basically just barbequing it.

**Comment by 0be1isk** [comment]
> The default season length on CDDA is 14 days. Buckwheat takes about 10-11 weeks (70-77 days out of 91) to harvest. As each season is a compression of 3 months, 12 days is a good approximation for how long it takes buckwheat to mature and be ready to be harvested. Furthermore, extending the season timeframe also extends the growth period of crops accordingly, so it should always match up.

fair enough

> Actually, yes it can. black soap, or early lye soap, is just made from powdered charcoal, water, and fats mixed together and boiled down. The carbon of the charcoal doesn't inhibit the potassium carbonate in the slightest in this manner.

I can't seem to find a single source that uses charcoal as it's base compound. Every google search brings up wood ash.  (at least  in the most common use of lye production) Even searching for "black soap" and "early lye soap" fails to bring up any mention of charcoal being used. Can you provide some sources?

> Yes, and preparing acorns as food IS a chore. They aren't an easy source of nutrition, but they can be a good source of nutrition if you put the effort in to make it one. Survival off of foraged food ISN'T EASY.

You're missing the whole point here. If it's already a chore, due to how long it takes to make a remotely sustainable batch where you could eat 40-60% of it because you didn't eating the whole time preparing the single batch in the first place coupled with the huge weight and volume required, why do you want to make it MORE of a chore? This all goes back to game design. There's a reason games don't make you do every little thing that you would do in the real world. Nobody would play them since every thing becomes a grind fest. Games can make it difficult to survive sure, but difficulty shouldn't come from tedious-ness. I stand by what I said earlier "In all honesty, this just seems like a way to bring more mundane chores to dda then there already is."

> Technically possible by mimicking how fermenting vat or charcoal kiln works and creating a smoking rack that processes it's contents from non-smoked to smoked versions.

> A good start

I agree

**Comment by nexusmrsep** [comment]
Ok, I'm queuing smoking rack (expansion) on my TODO list. @Amariithynar can you make a separate issue for that, so that we split this discussion to correct titled threads? And also give me some approximations on how long should the smoking process take? We don't have any huge items to smoke like whole pigs, so my first thought (wild guess) would be 3-6 hours? Just put in on the new thread please.

**Comment by 0be1isk** [comment]
@nexusmrsep would it be possible to smoke dead corpses? ie. cattle, pigs, turkey, rattlesnake, coyote, dogs? this could preserve the rotting status of the corpse. Just an idea

**Comment by GroeneAppel** [comment]
@nexusmrsep I've put two references down in my earlier post which contain various smoking times. I suggest you use the times listed there. I'll list them again below:

[Source1](https://www.smoking-meat.com/smoking-times-and-temperatures-chart)
[Source2](http://www.smokymtbarbecue.com/bbq-tools/bbq-smoking-times-temperatures-chart.php)

**Comment by Amariithynar** [comment]
@0be1isk whole corpses would never be smoked; at the very minimum you'd see them be dressed down, organs removed, given a wash and a rub with the cure of their choice, before slow-roasting.

>I can't seem to find a single source that uses charcoal as it's base compound. Every google search brings up wood ash.

Hmm. I made it at a camp one year when I was much younger, as part of the arts & crafts programme, and I know that charcoal still contains the same potassium carbonate that the eventual ash residue left over after it's completely burnt does. Unfortunately, seems that over the past year or two we've seen an explosion of it in the beauty market thanks to the craze over activated charcoal IN EVERYTHING. But anyways, all soap is is the result of the action of an alkali on fats, the process of which is known as saponification. It doesn't NEED to be lye to create soap; I know that ammonia soaps used to exist decades ago. Other than that, I'm coming up dry as well.

>You're missing the whole point here. If it's already a chore...

No, I'm not. It's *not* already a chore. It's currently as easy as pressing "&", "/", "acorn", "b", and selecting batch size. Voila! It's as "hard" to do as any other basic crafting recipe. To make 20 only takes 8 hours, and even if you just leave it at that and don't make anything beyond that, 20 batches of 42 nutrition will fill you up from famished and you'll still have a couple left over- but you won't even be famished in that time period; in a 24 hour period you only need 288 hunger to feed yourself, and in 8 hours of cooking you gain 840 potential nutrition, enough for nearly 3 days of food. It's still a net gain in your food. It also overly simplifies the work that goes into it, and also removes a very useful product that boiling acorns should produce- a solution of tannic acid in water, perfect for tanning with, or to utilize as a stypic and astringent in the production of medical supplies.

Furthermore, if you make a quern, and you convert one acorn meal to 10 flour in 45 minutes. Another 33 minutes later and 9 of that flour with 6 water becomes 18 flatbread, worth 20 nutrition a piece. Lets plot this out in full, here, as it stands currently: 24 minutes to cooked meal. 5 minutes to make a quern. 45 to grind to flour, 33 to cook to flatbread. 1 hour 47 minutes after you began, you've made almost 1/5th the nutrition of a full 20 stack of acorn meal. If you do this 5 times instead, 2 hours for the meal, 1 hour 26 minutes for the flour, 48 & 1/2 minutes for the bread. 30 portions of 20 nutrition. 4 hours 14 & 1/2 minutes to make 600 nutrition.

Also, CDDA DOES make you do all the little things when it comes to preparation, usually. To make Vodka, for example you need to first combine all the ingredients together to make a mash, then ferment the mash to make a wash, then distill the wash to get the final product, so that's a moot argument to begin with.
