### ISSUE TITLE
Sickle and Scythe should be able to harvest plants (without necessarily auto picking them up)

### ISSUE THREAD

**Issue by 0be1isk** [CleverRaven/Cataclysm-DDA#24271]
Once you start farming, tools become your best friend. The hoe is capable of rapidly creating dirt mounds so we don't have to constantly go into the construction menu, and scroll to "till soil" to create huge pieces of farm plot. Fast forward to when 100+ crops have fully matured. Since a sickle and a scythe are in the game, and their descriptions hint at their farming abilities (strongly suggested to be reaping) you would think you could use the action menu to reap the 3x3 square around you (similar to how the shovel removes rubble), but you can't. Instead you have to hand picking each crop (unless using a tractor with a reaper). So a suggestion would be to give the sickle and scythe the same capabilities as the reaper, but minus the auto pickup feature.
![baf5993092ef1d4af48f7cb60827b7c9](https://user-images.githubusercontent.com/40281029/42606817-8bbf9864-854d-11e8-9ff9-5918ef068f35.jpg)

**Comment by Amariithynar** [comment]
Dunno about the sickle (maybe just make harvest action faster, if it's not fast already?) but scythe should clear a 1x3 wide, in the direction you designate it to (a)ctivate in. As for the sickle, given what its description of is, I'd think that it could harvest a 1x2 long, and prune branches off of trees.

**Comment by kevingranade** [comment]
Considering how scythes are used, I'm thinking what you really want to do is activate the scythe, and then if you step adjacent to "long grass" or similar terrain, it automatically triggers an action to cut the grass, leaving it on the ground.
Then you come back with a grass fork (?) and roll up the mown grass into a bale with a similar process, then you stash the bale in your barn for feeding to horses or cows.

Sickle AFAIK is more like "grab a sheaf of your crop, chop it with the sickle, then stash the sheaf in a basket or similar",

Longer term, I'd like to have an activity like "harvest all of X crop in this area", which checks that you have the right tools, and automates the entire process.

**Comment by Amariithynar** [comment]
>I'm thinking what you really want to do is activate the scythe, and then if you step adjacent to "long grass" or similar terrain, it automatically triggers an action to cut the grass, leaving it on the ground.

Grass, harvestable crops, the whole shebang. Gotta go pick it up manually, though. Witha warning that there's immature crops there, if it would hit them.

>Sickle AFAIK is more like "grab a sheaf of your crop, chop it with the sickle, then stash the sheaf in a basket or similar"

That's the case for the short-handled sickle that I know, where you would basically harvest the tile you activate it on (maybe same one you're standing on like the hoe, so you can rapid-press it while moving to harvest), but the description of the tool in-game seems to me to be leaning more towards the longer-handled variety. If that's not the case, then yes, that would be perfect use for it!

>I'd like to have an activity like "harvest all of X crop in this area"...
I think that sort of thing is best left to vehicles, otherwise it completely invalidates the Reaper.

**Comment by 0be1isk** [comment]
> Considering how scythes are used, I'm thinking what you really want to do is activate the scythe, and then if you step adjacent to "long grass" or similar terrain, it automatically triggers an action to cut the grass, leaving it on the ground.

Any form of automation is a good start, it beats having to hand pick 100+ crops.

> Then you come back with a grass fork (?) and roll up the mown grass into a bale with a similar process, then you stash the bale in your barn for feeding to horses or cows.

very interesting, what about putting in a baling machine?
![abbriata-mini-round-hay-baler-with-net-wrapped-bale](https://user-images.githubusercontent.com/40281029/42659540-8d41053e-85f6-11e8-8a50-48a6691b8645.jpg)
once the player has a given amount of straw (or other grain-type crop) and has the bale machine nearby, you could craft a bale and place it in barns

> Sickle AFAIK is more like "grab a sheaf of your crop, chop it with the sickle, then stash the sheaf in a basket or similar"

so what exactly should the sickle be used for?

> Longer term, I'd like to have an activity like "harvest all of X crop in this area", which checks that you have the right tools, and automates the entire process.

This would be a very well received addition. Farming can be quite tedious. Like in IRL, automation should ease this burden

**Comment by 0be1isk** [comment]
> Grass, harvestable crops, the whole shebang. Gotta go pick it up manually, though.

Yes, the whole idea is to still pick it up manually, like one would do IRL, but automate part of the process (pretty much to get rid of the tedious "harvest this crop" pop up for every crop)

> I think that sort of thing is best left to vehicles, otherwise it completely invalidates the Reaper.

Not necessary. The reaper has storage space and auto picks up the crops. Combined with how fast it can cut down and store crops, hand style reaping is slower, as well as needing the space to carry and store the crops somewhere else. Automation at this level shouldn't have a huge impact on the viability of the Reaper

**Comment by Amariithynar** [comment]
@0be1isk when you stand on a tile and hit "/" with one panel being I and the other being A, hitting "," will grab all in a 3x3 centered on the survivor anyways. No reason at all to auto-harvest anything you scythe. And, as I also said, if the sickle is the short-handled kind and not the long-handled variant (which the description leads me to believe it is moreso), then I'm all for it, specifically, harvesting and autolooting a tile at the same time.

**Comment by 0be1isk** [comment]
> when you stand on a tile and hit "/" with one panel being I and the other being A, hitting "," will grab all in a 3x3 centered on the survivor anyways. No reason at all to auto-harvest anything you scythe. 

The advanced inventory management is for moving stacks of items between tiles (or put into your inventory), it does not allow for (a)ction menu performances. There may be a misunderstanding here. By auto harvest, I do not mean in the way the reaper works (where it harvests AND autoloots) . I mean it in the way that @kevingranade suggested. Where you activate it and anything within X tiles is auto harvested (ie. not autoloot, but to prevent the constant "harvest this plant" window from coming up), similar to activating the shovel near rubble and it "auto removes" the rubble tile and all you have left is it's dropped contents (which you are free to pick up manually).

>   then I'm all for it, specifically, harvesting and autolooting a tile at the same time.

autolooting was the main thing that I suggested against with traditional reaping. I suggest that autolooting should not be a thing when using the scythe or sickle as that will continue to give the reaper a viable advantage over manual reaping

**Comment by Amariithynar** [comment]
I may have misunderstood what @kevingranade meant when he said "harvest X tiles in the area", as I thought that was already in support of altering the scythe and sickle to be useful for harvesting, since he was referring before that to using a grass fork to gather up the cut plant matter into bales. I'd be against a "designate zone as farming, then when crops are ready move into zone and (a)ctivate tool to harvest all crops" or something similar. A thresher and a baler are all that are really needed for automating that process properly, and as I mentioned, you can just advanced item menu loot up the place after coming through swinging with a scythe by hand, until you can thresh it by vehicle.

I specifically noted the sickle as being viable for auto-picking-up stuff after you use it to harvest, because of the method by which you use a short hafted sickle; grab up a sheaf of the plants, and then chop them low to the ground, as you mentioned. You already have them in your hand, at that point, so why would you just drop it on the ground? That makes no sense. Scythe, on the other hand, involves holding the two side-mounted handles to the main haft and swinging it in a wide sweeping motion in front of you.

**Comment by sfsworms** [comment]
There is an interesting balance decision  between player time and character time here. Player value their time a lot more than their characters: it takes more player time to fix and find a combine harvester than to equip a scythe, so if we have an automated zone, it would take more player time (but a lot less character time) to use a scythe over using a vehicle.

There might be a parallel with how batch crafting clean water kind of make water purifier obsolete: they might save time for the character, but not for the player. 

Hopefully the introduction of bases and the need to obtain massive amount of food would help make vehicles viable.

**Comment by Amariithynar** [comment]
Batch-crafting made *battery operated* water purifier obsolete, but not *vehicle mounted* water purifier. FOODCO Buddy is still amazing, and does it in a fraction of the time for as large a tank as you can install.

**Comment by kevingranade** [comment]
> I think that sort of thing is best left to vehicles, otherwise it completely invalidates the Reaper.

A vehicle-mounted reaper should still have a LARGE advantage in time spent to harvest in-game.  A field it takes an in-game day to harvest with a scythe should only take an hour or so with a reaper.

Even if it did obsolete the reaper (it might still, because if you only need to spend a day or two per season reaping, it might not be worth it to maintain a reaper vehicle), that not a good reason to avoid automating a tedious player task.  If we can eliminate hundreds of keypresses, we should, full stop.

**Comment by Amariithynar** [comment]
Then farming just becomes even more free food, which locusts were introduced specifically to combat. I'm not saying that it shouldn't be made easier like how farming has been made easier in reality, I'm saying that player input and effort needs to be there- they have to have scavenged or built a reaper, for example. Just like how there's no method to automate collecting the 50+ corpses of a horde to one location to smash/butcher/burn them just to stop tainted nymphs from spawning, so shouldn't there be automation that invalidates the work you need to put in to feel like the effort you put in was rewarded, rather than just given free loot. This is why I'm for making the tools work like how they should IRL as best as possible, but against just automating an entire harvest in a zone. Eliminating keypresses is not always a positive. Sometimes it just makes things more shallow.

**Comment by kevingranade** [comment]
Bailing machine is fine.
> so what exactly should the sickle be used for?

Afaik it's used for harvesting grains, and then you take another pass with a scythe to get the stalks.

> Then farming just becomes even more free food

It's not free, you're trading time for food, but theres never a reason to arbitrarally force player time to be spent, spending character time is sufficient.
> Just like how there's no method to automate collecting the 50+ corpses of a horde to one location

Great example of why using one part of the game to justify another part doesn't work, we plan on allowing this to be automated as well.

> Sometimes it just makes things more shallow.

As I mentioned above, I'm perfectly fine with making farming less interactive, because it's a *chore*.  Exploring is interesting/risky/fun, combat is interesting/risky/fun,  farming is just repetitive, and it hardly matters what order you do things in, so there's no reason to make it interactive.

**Comment by Night-Pryanik** [comment]
No discussion in over half a year, closing.
