### ISSUE TITLE
“Press any key to continue” is not correct

### ISSUE THREAD

**Issue by Wuzzy2** [CleverRaven/Cataclysm-DDA#24325]
Game version: 2443ef3b29ecbdcea0dd35c494330306d1af116e

Operating system: GNU/Linux

Tiles or curses: Both

Mods active: N/A

### Expected behavior
Ahh, yes. The infamous Any key …

In screens with the message “Press any key to continue”, if you press literally any key on your keyboard, you continue.

### Actual behavior
Most keys do work.
But there are some special keys which do not “count”: Shift, Ctrl, Alt, Alt Gr, Num Lock, Caps Lock, special media keys found on some keyboards (e.g. volume up/down), etc.

### Steps to reproduce the behavior
* Open help
* Select entry with multiple pages
* Press Shift (which is literally any key) and see what happens

### Suggested solution
Change message to “Press Space to continue”
(or say “Press Enter to continue” or whatever you feel appropriate).

**Comment by glamcube17** [comment]
Isn't this the usual behavior of "press any key to continue"? I don't recall Shift/etc counting, though I could be wrong.

**Comment by ZhilkinSerg** [comment]
`Shift` is a modifier key, so all messages like `Press any key` should be read like `Press any key, except modifier key`.

**Comment by CoroNaut** [comment]
Well TECHNICALLY... :smile:

**Comment by Wuzzy2** [comment]
Just say “Press space to continue”, then the issue is fixed.

**Comment by glamcube17** [comment]
>Just say “Press space to continue”, then the issue is fixed.

Then it would be even less accurate and far more confusing.

**Comment by Wuzzy2** [comment]
How is this confusing? Just press the space bar, it will always work.

If even this is too confusing to you, then I can't help anymore.

**Comment by glamcube17** [comment]
You're only considering confusion due to not continuing when the user expected to continue. Saying "press space to continue" but actually continuing when any (non-modifier) key is pressed would create a great deal of confusion due to continuing when the user expected to not continue.

The current behavior is the standard behavior and is unlikely to cause confusion. From https://en.wikipedia.org/wiki/Any_key: "The prompt is not strictly accurate in that, **for the vast majority of computer systems, modifier keys or lock keys would not cause processing to resume**".
