### ISSUE TITLE
First Aid Kits do not heal over time.

### ISSUE THREAD

**Issue by LadyCatnip** [CleverRaven/Cataclysm-DDA#24320]
Game version: 0.C-29071-g81f89da

Operating system: Windows 7 64bit

Tiles or curses: Tiles

Mods active:

### Expected behavior: 
Using a first aid kit will heal you slowly over time, rather than instantly.

### Actual behavior: 
Using a first aid kit will only remove the bite and bleeding debuffs, and will not heal you over time.

### Steps to reproduce the behavior: 
Get damaged, (Debug the limb health down, Jump off a building, burn yourself), use a first aid kit on the damaged limb, and wait, and your health will not go up at all.

**Comment by ZhilkinSerg** [comment]
Did you receive `bandaged` ot any other effect on a healed limb?

**Comment by LadyCatnip** [comment]
I received the bandaged effect as well as the disinfectant effect, up to the 16 max.

**Comment by LadyCatnip** [comment]
Should I take screenshots and post them here or will you be able to test this on your own?

**Comment by Night-Pryanik** [comment]
> Should I take screenshots and post them here

This.

**Comment by LadyCatnip** [comment]
https://gyazo.com/459dea9324cbbe684542abbd89f0f2dd
Before I apply first aid kit to myself, I gave the test subject the self aware mutation so it'd be easier to figure out Hitpoints.

https://gyazo.com/bdb51200011858dc3f7e872d4cc7ce40
After I apply first aid kit, it seems to properly apply the bandage and disinfected 'buff'

https://gyazo.com/13e7bcc1d18298cf2d0c4180f130dad2
After I wait six hours, my health has remained at the same level, and the bandage and disinfected buff lost 1 'stack'.

**Comment by LadyCatnip** [comment]
Is that good?

**Comment by Night-Pryanik** [comment]
Yes, though you can also use built-in GitHub image posting feature.

**Comment by Lasiace** [comment]
Going through the commit, I wonder if the issue is on line 2661 of character.cpp? This specifically:

`bandaged_rate += e_bandaged.get_amount( "HEAL_RATE", 0 ) / HOURS( 24 );`

both `e_bandaged.get_amount( "HEAL_RATE", 0 )` and `HOURS( 24 )` are integers, so wouldn't this result in integer division? If the numbers are less than 1 then I suspect it might round off to 0.

unfortunately I don't have the tools to compile the game so I can't check for myself, but it seems like a possible cause.
