### ISSUE TITLE
faction camp errors

### ISSUE THREAD

**Issue by mlangsdorf** [CleverRaven/Cataclysm-DDA#24332]
Game version:
cataclysmdda 0.C-7575, commit 3ce526f4d9

Operating system:
Windows 7

Tiles or curses:
Tiles

Mods active:
  "dda",
  "DinoMod",
  "Experimental-Z-Level",
  "More_Survival_Tools",
  "StatsThroughSkills",
  "blazemod",
  "Tanks",
  "Urban_Development",
  "boats",
  "deoxymod",
  "filthy_morale",
  "makeshift",
  "more_buildings",
  "more_locations",
  "mutant_npcs",
  "no_flaming_weapons",
  "no_olg_guns",
  "no_religious_Texts",
  "npc_traits",
  "realguns"

### Expected behavior
I acquire the goods (large tent in my inventory in one instance; 8 two by fours, a hammer, 20 pine boughs, and an entrenching tool on the tent floor in the other) necessary to perform a faction camp upgrade mission. I select the mission and an NPC companion, and the NPC companion goes and does useful stuff.

### Actual behavior
An error has occurred!
DEBUG: Aborting craft: couldn't find cached components
FUNCTION: std::__cx11::list<item> craft_commd::consume_components()
LINE: 147

### Steps to reproduce the behavior
Debug spawn an NPC, make him the camp manager, debug spawn a large tent, attempt to upgrade the camp.

**Comment by acidia** [comment]
So, you've never been able to complete any of the NPC missions?  I'm assuming this bug kicks the first time you select to upgrade the camp and it immediately crashes.

I just did a test run with all your mods excepts:
"blazemod",
"deoxymod"

I had no problems in my test run using the mods I could find in Windows 8, build 0.C-7575, tiles
Were you using a previous save that got ported to the new build?

If all else fails, my primary suspect is that one of your NPCs had a mutation that grants tool/charge ability???  These intangible tools/items can't be found to be consumed if they are on an NPC, the methods I've been testing should ignore intangible player items but it may not ignore NPC items since those are fairly new.

**Comment by DracoGriffin** [comment]
>I just did a test run with all your mods excepts "blazemod" and "deoxymod" because I couldn't find them.

"blazemod" is Vehicle Additions Pack
"deoxymod" is Folding Parts pack

**Comment by mlangsdorf** [comment]
My PC has an internal toolset, I don't think the NPCs do.

I was using a previous save that get updated in the new build, though.

**Comment by acidia** [comment]
Hmmm, very strange.  Just tried in the latest build with the internal tool-set on the PC and didn't have an issue.

Actually, what are you doing right before you do the missions?  It could be caused by a task that doesn't call g->u.invalidate_crafting_inventory(); after modifying it... I'd imagine it would be wasting CPU time if I rebuilt it every time I start a crafting method then called it when I was done.  Since I can't replicate it I can't really offer much more insight.

**Comment by mlangsdorf** [comment]
Okay, I'm closing the issue until I get a definite reproducer. Thanks for looking into it.

**Comment by acidia** [comment]
Do you think #24343 could be similar to your issue?  Doesn't look like aborting from vehicles is handled cleanly, you didn't mention one but just checking.

**Comment by RadHazard** [comment]
I've also run into this issue.  It happens every time when I try to build or upgrade a camp in my existing save.

I haven't narrowed down the cause yet.  I can confirm that I DON'T see it when using a backup of my save (made just before the upgrade) or a new save, so there's got to be some kind of in-game task causing it.

**Comment by RadHazard** [comment]
After further testing, it looks like crafting anything immediately before trying to upgrade the camp causes problems.  Once it's broken, it seems that it's stuck that way.

**Comment by mlangsdorf** [comment]
Oh, #$@#! I have a large tent in a go-bag style item, so of course I unpack it when I need it for the camp. And then I immediately go to upgrade the camp and get the error.

Okay, re-opening the issue now that there's a definite reproducer.

**Comment by 0be1isk** [comment]
![screenshot 26](https://user-images.githubusercontent.com/40281029/42849644-0c5b6202-89f2-11e8-8e0b-6891c7858741.png)

**Comment by mlangsdorf** [comment]
I got it do to it correctly once.
And then I went and cooked some food and things broke again. Darnit.
I'm pretty sure it's the crafting cache issue against a recent crafting. 

Why isn't can_make_with_inventory renewing the crafting cache? That's half of what it's for.

**Comment by mlangsdorf** [comment]
I haven't had a problem since updated to 7581 that includes these fixes.
