### ISSUE TITLE
Logged out in vehicle, came back in and vehicle is gone.

### ISSUE THREAD

**Issue by codrus** [CleverRaven/Cataclysm-DDA#24385]
Game version: 0.C-7470

Operating system: Win10

Tiles or curses: Curses

Mods active: NA

### Expected behavior

Logged out in my vehicle which was parked inside a subway building. When I logged back in the vehicle is gone w/ all the stuff it held, and I'm standing in the subway building. When I move I get a cannot find vehicle error. See 2 following screenshots for full info:

https://s33.postimg.cc/74obmz2i7/DDABug.jpg
https://s33.postimg.cc/nfofjdugf/DDABug2.jpg

**Comment by kevingranade** [comment]
Its unclear what you mean by "logged out", if you used the save command
it's a bug, if you exited the program otherwise it's not something we plan
to adress.

Use save to exit.

**Comment by UncleBenis** [comment]
Thats fine and all but theres quicksave and autosave features in the game that interfere with world save regardless of intention of their user. Ive had the game crash on me twice in the last few days and Id rather not lose an hour of progress because I pressed F5 instead of doing the whole save and quit to menu then reload thing every time.

**Comment by codrus** [comment]
Kevingranade: I saved out.

**Comment by DracoGriffin** [comment]
`Save & Quit` option from Esc menu most likely.

**Comment by Night-Pryanik** [comment]
No confirmation in over half a year, closing.
