### ISSUE TITLE
[RFC] Drawbridges for crossing multiple pits

### ISSUE THREAD

**Issue by mlangsdorf** [CleverRaven/Cataclysm-DDA#24397]
I want to add a drawbridge, a construction similar to a palisade gate, but that would instead over multiple rows and columns of pits (including spiked or glass pits). Basically, I'd like to have a 2x7 row of pits with an easy way to get my vehicle across it.

I would need to add the following terrain:
* t_gates_control_drawbridge: like the existing t_palisade_pulley, but has examine_action controls_drawbridge instead of controls_gate
* t_drawbridge_up: like the existing t_palisade_gate
* t_drawbdrige_down: like the existing t_palisade_gate_o
* t_pit(_glass, _spike)_bridged: like the existing t_pit_covered

controls_drawbridge would be a combination of the existing open_gate and pit_covered functions, converting the existing pit terrain to pit_bridged.
unfortunately, there's no way to store a flag or quality for terrain, so there's no way to indicate that the drawbridge is N rows wide. short of creating t_drawbridge_up1 through t_drawbridge_up6 (or so) terrains and having controls_drawbridge know how many rows of spits to cover based on the number, which is inelegant at best.

**Comment by acidia** [comment]
If you're looking for easy but not-so-great suggestions, you can always implement it the way I was using computers to unlock doors in the labs.  It would just convert all t_door_locked to t_door_closed_unlocked, or whatever, that fell within range x of the control device.  You'd build your draw bridge on all the pit tiles and call them all up or all down.  Works well for RPing but I doubt the players would like it since the bridge doesn't go "up" in a tile, it just disappears and re-appears.

**Comment by mlangsdorf** [comment]
The trick is how to determine the number of tiles that a raised drawbridge supports, because there's no way to save state about a terrain tile. Furniture tiles can have inventories that are saved, but some of the furniture interactions are limited.

**Comment by Amariithynar** [comment]
That's why I suggested having it work like the Folding Vehicles mod; as far as I understand it, it remembers the vehicle blueprint in the folded vehicle's information, and upon unfolding it, recreates the vehicle. Or is that an impossibility?

**Comment by mlangsdorf** [comment]
Closing this because I don't have time to work on it.
