### ISSUE TITLE
duplication of items.

### ISSUE THREAD

**Issue by Alce00** [CleverRaven/Cataclysm-DDA#24399]
Charcter with broken arms tries to wield item lying on ground. He does that, but item doesn't dissapear from ground.

**Comment by Alce00** [comment]
Actually wield command works as intended. Trying to pick-up item without having inventory space and chosing wield option produces this bug.

**Comment by Amariithynar** [comment]
This was addressed in a recent commit, as another commit to fix certain watertight containers not filling with water under a funnel accidentally broke this somehow, I believe; I originally reported this issue on the Discord, and it was quickly fixed, and as of the commit listed in the launcher for it, it does in fact resolve proper for me in every build since. Have you updated to the latest experimental?

**Comment by Alce00** [comment]
Oh, my bad. I should have updated game before posting this. It just I haven't seen neither commit nor open issue with that so I decided to post it. My mistake.
