### ISSUE TITLE
Garlic bulbs will consume the whole stack when activated, but will always give 6 cloves, regardless how many bulbs were in the stack

### ISSUE THREAD

**Issue by Lasiace** [CleverRaven/Cataclysm-DDA#24393]
Game version: 0.C-29319-gb289975

Operating system: Windows 7

Tiles or curses: Tiles

Mods active:

### Expected behavior
A stack of 1 garlic bulb gives 6 garlic cloves when split, and 2 bulbs give 12 cloves

### Actual behavior
A stack of 1 garlic bulb gives 6 garlic cloves when split, but 2 bulbs also give 6 cloves, including 3, 4, etc.

### Steps to reproduce the behavior

1. Get any stack of garlic bulbs
2. Split the stack
3. You'll get only 6 cloves, no matter how many bulbs were in the stack

Added screenshots of the bug:

![1](https://user-images.githubusercontent.com/24522330/43013102-6520557a-8c7a-11e8-85e2-9933c61ec8bf.PNG)
![2](https://user-images.githubusercontent.com/24522330/43013104-65a5a356-8c7a-11e8-8eb8-0314ba72f004.PNG)
![3](https://user-images.githubusercontent.com/24522330/43013105-65db1c3e-8c7a-11e8-8940-0d1d46407928.PNG)
![4](https://user-images.githubusercontent.com/24522330/43013107-664f69cc-8c7a-11e8-8755-98d18137a65b.PNG)

**Comment by nexusmrsep** [comment]
I hate half-measures, but the problem is in `iuse_actor::transform` that operates on existing items and transfers charges from source items to target items (in fact it does not transfer anything, instead operate on exisitng item changing it properties) . I brefly made it possible to properly use one charge of bulb and produce 6 charges of cloves, but it broke flashlights, etc. (they go on->off and off->on and their charges don't and should not change in that process). In other words: I failed to make a more sophisticated fix for the problem, but i fixed it by applying a less ideal method (disassembling garlic bulbs).

**Comment by FulcrumA** [comment]
@nexusmrsep 
Wouldn't it be better to get back to crafting recipes? This way it's much easier to turn multiple bulbs into cloves through the use of repeat key while disassembling doesn't seem to work so well and reliably.
