### ISSUE TITLE
"TURRET" flag prevents blazemod amorphous core from being installed

### ISSUE THREAD

**Issue by amystewart256** [CleverRaven/Cataclysm-DDA#24401]
Game version: 0.C-29353-ga27701f (tiles)

Operating system: Windows 10

Tiles or curses: Tiles

Mods active: Blazemod

### Expected behavior

When you have an Amorphous Heart, the option to install an Amorphous Core is available

### Actual behavior

There is no option to install an Amorphous Core when you have an Amorphous Heart

### Steps to reproduce the behavior

Get Amorphous Heart, attempt to install on otherwise empty vehicle frame

NOTE: This issue is fixed by changing the Amorphous Core's location to engine_block and removing the "TURRET" flag. 

![image](https://user-images.githubusercontent.com/7119741/43032161-7c248ada-8c7e-11e8-816f-18a5b27a11ef.png)

![image](https://user-images.githubusercontent.com/7119741/43032164-aecf0546-8c7e-11e8-96a0-686a44221c75.png)

**Comment by DracoGriffin** [comment]
Since you have the fix, you should submit a PR for the fix. You don't have to, but it'd be appreciated!

**Comment by amystewart256** [comment]
Hey! I was just messing around with some tags, but I haven't dug too deeply into the codebase to know what the intent of all of them are (what's the point of the mass being boardable/beddable/sittable when it's in the engine slot instead of the center? Is the "BELTABLE" tag related to its turret status?) Stuff like that.

**Comment by DracoGriffin** [comment]
Uhh, since it's a mod, that was kinda the discretion of the author, so hard to say why.

[Beltable ](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/JSON_FLAGS.md#flags-3)means you can install a seatbeat if there is a applicable seat in the same tile.

These two JSON ([JSON_INFO](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/JSON_INFO.md) & [JSON_FLAGS](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/JSON_FLAGS.md)) docs will help explain stuff without having to code delve.

**Comment by amystewart256** [comment]
Herp. I was tired last night and didn't realize that the location has nothing to do with it. It's just the turret flag. I'll make my first (woo!) PR later today.

**Comment by mlangsdorf** [comment]
@amystewart256 : Any progress on that PR? I'm trying to clean up blazemod as part of my effort to make vehicles more player friendly, and it'd great if this got cleaned up.

**Comment by mlangsdorf** [comment]
Fixed in #24624
