### ISSUE TITLE
A player character with a null inventory capacity will lose charges when trying to reload an item that it is not being wielded.

### ISSUE THREAD

**Issue by Break-Off** [CleverRaven/Cataclysm-DDA#24413]
### Game version:
0.C-29381-g4479903 (tiles)

### Operating system:
Windows 10 x64

### Tiles or curses:
Tiles

### Mods active:
`[
  "dda",
  "StatsThroughSkills",
  "blazemod",
  "Tanks",
  "Urban_Development",
  "alt_map_key",
  "boats",
  "ccpark",
  "deoxymod",
  "ew_pack",
  "filthy_morale",
  "more_buildings",
  "more_classes_scenarios",
  "mutant_npcs",
  "no_npc_food",
  "no_olg_guns",
  "no_pipe_guns",
  "no_rivtech_guns",
  "novitamins",
  "npc_traits",
  "oa_additional_buildings_mod"
]`

### Expected behavior
When hitting 'r' to reload a nearby item (e.g. wooden needle with thread), a PC with 0.00L volume capacity in their inventory should wield the item (since they can't pick it up) and reload it with nearby charges.

### Actual behavior
The PC doesn't wield the item and the message log shows:

> Some items tumble to the ground.
You reload the _item_.

Indeed, the item with intention of being reloaded ends up in the PC's feet. However, it hasn't been reloaded and the charges are lost.

### Steps to reproduce the behavior
1. Debug an item with charges (e.g. wooden needle)
2. Debug charges for said item (e.g. thread)
3. Drop all clothing that gives you storage capacity (until inventory shows 0.00L)
4. Instead of wielding the object to be reloaded, drop it nearby the player and hit 'r'eload.
5. The item will not be reloaded, fall to the ground and the charges will be lost.

**Comment by wapcaplet** [comment]
Cannot reproduce in 0.E-9737-g511ddcb179. Since nested containers, it is not possible to carry items (not wielded) without any wearing anything with storage capacity, but the basic steps still apply:

1. Get naked
2. Get a wooden needle and thread, on the ground nearby
3. `U`nload the thread from the needle - both items land on the ground
4. `r`eload the needle with the nearby thread - reloaded needle and thread become wielded

The same behavior occurs with a flashlight and light battery, or a handgun and magazine.
