### ISSUE TITLE
Some combat styles aren't on all applicable weapons.

### ISSUE THREAD

**Issue by Amariithynar** [CleverRaven/Cataclysm-DDA#24412]
Inspired by #24407 I was looking over weapons and noting what styles they used, and compared them to what weapons they actually use, as well as things that would make sense.

I've noticed a couple weapons that cannot be used for Silat, for example the copper spear and forked spear; copper knife; bokken (which are basically just sword-shaped bludgeons; wouldn't be used in the same way as in Niten Ichi-ryu, of course); wakazashi aren't that dissimilar to the mid-length blades used in Silat like machete, same with cavalry sabers and cutlasses (which are little more than more formal machete); and axes, from fire axe down to hatchets (https://www.youtube.com/watch?v=Ir2tnu3ZZog). Eskrima (Arnis Kali) should be able to use all the same weapons as Silat, as they are functionally quite similar in their "use what is at hand, especially bludgeoning/generally light bladed weapons" concepts, though Eskrima definitely does support more improvised weapons, which the list of known Eskrima weapons as listed on the wiki does show. Here's Arnis spear, for example: https://www.youtube.com/watch?v=Rvq9ANCLekc and spear & walking staff: https://www.youtube.com/watch?v=1HQdPyUMpXY

Broadswords can be used with Fencing, yet Arming Swords, their lighter, slimmer brethren that usually have a better taper to the point, cannot. Jian are long, thin Chinese swords that definitely can be used for fencing, similar to rapiers, epees, and sabres. Similarly, the bokken is a sword-shaped stick; the cudgel can be used for fencing, so should bokken.

Krav Maga should be usable with pistols (not shooting with it, but if you have to melee with a pistol equipped; treat it as an auto "force unarmed" perhaps, without losing the style bonus?), combat-ready knives (similar to Silat/Eskrima), and other short bludgeons than tonfa, like the batons and the cudgel. http://www.your-krav-maga-expert.com/krav-maga-weapons.html

All weapons I noted came from a completely clean world with no mods; there's most likely a plethora of mod weapons that are maintained not by the original creator that need to add styles to them appropriately, as well.

**Comment by Blank99** [comment]
Keep in mind that the style weapons is a bit more complex than what the list contains.
To whit: for the sake of techniques and buffs, anything can be used with any of the style weapons, anything with "unarmed allowed" can be used with unarmed weapons, and anything with "melee allowed"  can be used with any melee weapon.

So Krav, for example, does not allow _techniques_ with non-style weapons, but it gives the stab damage buff, so the style 'works' with any stabbing weapons, from knives, to spears, to bayonets.

Similarly, all Silat and Eskrima buffs work with **any** weapon, tho only the style weapons get the _techniques_.

**Comment by Mooses2k** [comment]
Two thoughts on this.

One, an arming sword should not be usable with the fencing style as it's not a complex hilt weapon. The style for arming sword (and arming sword + buckler) is very different than the styles for rapier or sabre or broadsword.

Secondly, I think it's a balance and flavor thing to make certain weapons JUST for Niten, even though, yes, they'd make sense in other styles as well. I have an escrima teacher who insists his style is usable with any weapon at all, since it's more about how to hit, how to interpose or intercept with your weapon while hitting at the same time, how to move, overwhelming and unexpected aggression, etc, with only distantly secondary mention paid to 'techniques' and 'forms'. YMMV, though. Point is, game balance kind of insists that that art doesn't work with everything udner the sun, including using your cellphone as a palm stick.
