### ISSUE TITLE
Antibiotics Revamp: Antibiotics should be split into three catagories, to more accurately represent availability, function, and strength.

### ISSUE THREAD

**Issue by Amariithynar** [CleverRaven/Cataclysm-DDA#24416]
As I stated in #24379 I'm splitting off the wider discussion regarding antibiotics that stemmed from how antibiotics are far too inaccessible now with first aid kits having their antibiotic capability removed.

Antibiotics as we know them consist of three broad catagories of antibiotic; Glycopeptide, Macrolide, and Quinolone.

Beta-lactam antibiotics work by breaking down cell walls (which human cells don't have; we only have cell membranes), the rupture of which spills their contents out and has the cell effectively 'die'; all beta-lactams are technically also glycopeptide antibiotics, but other glycopeptide antibiotics like vancomycin target different types of bonds and do not centre around a beta-lactam ring in their chemistry. Penicillin and its derivatives are beta-lactam antibiotics. Macrolide antibiotics like Erythromycin target the ribosomes inside the infecting bacterium, damaging or destroying the proteins needed for the cell to survive. Quinolones like ciprofloxacin break the DNA within the bacteria that allows it to properly function, including to replicate. Reference: http://learn.genetics.utah.edu/content/microbiome/antibiotics/

Now, this said, bacteria do evolve methods of fighting back against antibiotics; Beta-lactams: https://www.ncbi.nlm.nih.gov/pubmed/8314292 Macrolides: https://www.ncbi.nlm.nih.gov/pubmed/11810493 and Quinolones: https://www.ncbi.nlm.nih.gov/pubmed/15942878

As such, all things considered, I'd like to propose that these three broad catagories of antibiotic are introduced instead effectively as "tier 1", "Tier 2", and "Tier 3" antibiotics, with differing negative effects per dose taken (fluoroquinones should severely affect health, -10 per tablet or more, for example); infections should also match the type of antibiotic, separate from the severity; while fluoroquinolones should be the single strongest antibiotic (highest base antibiotic strength value), matching the right antibiotic to the infection (should require a good First Aid to do, similar to how Cooking shows the current lifespan of food) would give a bonus to the check to clear the infection; if this is too complicated, of course, scrap it.

It should take multiple "positive" results to clear up an infection, just as it takes between 3-14 days before an infection is completely cleared up. Infections should also be able to be resistant to any number of the three, regardless of tier, including being resistant to ALL three, and resistance chance slowly drops off as time passes in game, so that by the third year the chance of being infected with a resistant strain is far smaller than in the first year. Resistance should just give a flat chance for an antibiotic to not work.

You CAN overpower resistant strains by downing more of the antibiotic, but that also causes other complications; this could be done through the application of debuffs or even negative traits in the case of permanent damage from fluoroquinolones, or just abstracted out to increased health penalties to do so; wrecking your health is still preferable to dying, after all, and it would allow for simple abstraction.

Lastly, by splitting "antibiotics" into three, you can diversify rarity, much like how painkillers are split up. Aspirin is very common but doesn't really do much, while codeine is significantly rarer and much stronger. Thus, fluoroquinolones would be found in the current rare circumstances, (the original PR noted that antibiotics are only found in drug_rare and drug_soldier) as they are typically controlled substances; macrolidic antibiotics would be a bit more common, as they aren't controlled substances, but do suffer a dip in general strength; and gylcopeptide antibiotics, which are massively more common, would also be a relatively common drop (not as common as aspirin is, just was using that as a separation of painkillers into rarity and strength tiers) and even found in corner stores and similar, but with relatively low strength, as well.

**Comment by StripedMonkey** [comment]
I mean, I'm not against the idea personally but I think this is going overboard in terms of depth

**Comment by Amariithynar** [comment]
Even if the vast majority of it is discarded and we simply implimented the tripartite group of antibiotics as "weak antibiotic", "antibiotic", and "strong antibiotic", with only strong antibiotic having a 100% chance of clearing an infection, it'd still be far superior to how it is currently. Antibiotic accessibility is simply too small right now.

**Comment by FulcrumA** [comment]
I like the idea but yeah, it may be developing a really indepth system to solve a simple issue. If it's inaccessibility of antibiotics that's the problem, I'd start by increasing the accessibility.
I don't think we need to multi-tier antibiotics themselves, we can simply include certain items that have antibiotic properties (like your #24414 which you could make have non-100% effectiveness, like how it is with disinfectant-soaked rags).

**Comment by RadHazard** [comment]
One thought I had for antibiotics is that it might make sense for antibiotics to slow or reverse the progress of an infection rather than insta-curing it.

How I imagine this might work:
Infections would get progressively stronger, with more and more serious effects as time goes on.  The stronger an infection is, the less likely your immune system would be able to fight it off (possibly with a modifier based on the health stat).  Taking an antibiotic reduces the strength of an infection by X%, where X depends on how strong the antibiotic is.  There would probably have to be some kind of diminishing return or negative effect here or something to ensure players don't just swallow the entire bottle at once.

That means you could completely kill an infection by taking an entire bottle of antibiotics over the course of your infection, or you could ration your antibiotics and hope that your immune system can finish it off.  This fixes the "one bottle of antibiotics and you're set for life" issue, which would make it safer to make them more common without breaking the balance.

**Comment by FulcrumA** [comment]
@RadHazard 
>One thought I had for antibiotics is that it might make sense for antibiotics to slow or reverse the progress of an infection rather than insta-curing it.
That's a pretty interesting idea. Half of it is already done - infection does progress and gets more disruptive over time, ending with death. I wouldn't want antibiotic to take just some percentage of infection, because it would just mean 'use enough antibiotic to instacure' (and adding superficial barriers for that wouldn't be good either). Simply have the antibiotic make infection progress in the opposite direction would suffice. While I am still ambivalent toward the idea, if we really need to include strengh of antibiotics, that should be more about how fast the 'reverse-infection' will progress, rather than how much percent of infection it reverses.

>That means you could completely kill an infection by taking an entire bottle of antibiotics over the course of your infection, or you could ration your antibiotics and hope that your immune system can finish it off.
The first part of this I actually find pretty bad, and an issue in itself I've underlined. One shouldn't just be able to gulp down a bottle. That's a good way to mess oneself up. Maybe there should be a slight boost to how antibiotic works after another dose, but anything more than that should be detrimental to health. Otherwise, not only it won't work how antibiotics are used, the whole tiered system makes no sense anyway. Why to look for various antibiotics when you can just put in plenty of one particular type?

**Comment by RadHazard** [comment]
I was thinking less along the lines of "gulping down the bottle all at once" and more "taking a full regime of antibiotics over the course of the infection".  So you could keep popping pills every X hours (maybe 12 or 24 hours) until the infection dies off for maximum effectiveness, or you could space out your pills even further and risk it getting worse again in between the doses.

Probably the easiest method of ensuring players don't overuse them would be to have each antibiotic cause a long-lasting effect that reverses the effect of the infection.  Taking pills before the effect wears off would just reset the duration without giving any other benefits.  Higher quality antibiotics could be differentiated by having them reverse the infection somewhat faster, meaning you'd need less pills and less time to cure one.

**Comment by Mooses2k** [comment]
Honestly, aren't antibiotics good enough now?

Close #22557 & #20742 as well?

Okay, if not, what? Infections still too deadly? Add a 'strong antibiotic' and make antibiotics more common? Make taking a course of regular or greater antibioitics something like 90% likely to cure infection (eventually)?

**Comment by kevingranade** [comment]
The key point brought up here has been adressed (multiple types of antibiotics with varying availability and effectiveness).  

The issue doesn't provide a meaningful roadmap for implementing the much more involved system it outlines, we might as well start from scratch as use this as a starting point.
