### ISSUE TITLE
Rotting food/corpse indoor should produce miasma 

### ISSUE THREAD

**Issue by cainiaowu** [CleverRaven/Cataclysm-DDA#24457]
### Expected behavior
Rotting food/corpse indoor should produce miasma, which may
1. Drop your morale, which could be negated by proper air filtering/environment protection.
2. Produce Purple smoke like scent (which doesnt hide item/creature) to provide a visual feedback to player.
3. Hide your scent like smoke, so you might use it to loose scent tracker.

### Actual behavior
No such feature.

### Steps to reproduce the behavior
N/A

**Comment by Lasiace** [comment]
We Dwarf Fortress now.

Well, I'm not against the idea, but from a gameplay standpoint it kinda overlaps with carrion doesn't it? (As a penalty for keeping rotten food around) Or I guess maybe not, since it would take place during the rotting phase rather than after.

The scent seems like it would *attract* potential zombies, though? Since the scent of rotten flesh might indicate a dead body for them to get, and they don't particularly care about the bad smell.

**Comment by kevingranade** [comment]
Need a rationale for why this needs to exist, I don't see one.

If were talking just a rotting smell, zombies would tend to produce it too,
so it'd be everywhere, and also it wouldn't make sense for it to mask
zombie scent abilities.

I'd also expect the survivor to go nose blind to this kind of thing almost
immediately since they're exposed to it so much.

**Comment by cainiaowu** [comment]
One would only nose blind if you stay in a place for a long time. The player will constant changing  indoor/outdoor or even go into forests where does have all those dead corpses.

One would also expect the survivor would get used to filthy clothes, but they are still giving you morale penalty.

**Comment by DracoGriffin** [comment]
Counteridea: survivors could be able to use dead zombie corpses around their safehouses in order to overcome their own scents --- basically stealth by smell.

**Comment by kevingranade** [comment]
Scent isn't visible at a distance, so the purple miasma thing is out unless it's only displayed adjacent to the player, at which point it's fairly useless.

After a little searching I'm not seeing any indication that rotting odors are going to throw off an animal tracking with scent.  The concentration is never going to reach that of smoke from a fire or similar, so I don't see a good rationale for using it to mask your scent.  If you can find some sources that indicate otherwise feel free to provide them.

With it just being morale, I'm not seeing a compelling reason to add it, scent diffusion is actually really expensive to calculate and really complicated, so updating it for this minor effect seems counterproductive.

**Comment by cainiaowu** [comment]
OK, closing since nobody seems to be interested.
