### ISSUE TITLE
Slow healing items like first aid kits show zero health gain when choosing limb

### ISSUE THREAD

**Issue by Xhuis** [CleverRaven/Cataclysm-DDA#24481]
Game version: Latest as of posting; unsure

Operating system: Windows 10

Tiles or curses: Tiles

Mods active: None that affect healing items

### Expected behavior
The interface shows the amount of health that will be gained over time.

### Actual behavior
The interface shows zero health gain.
![](https://i.imgur.com/6oIsEN2.png)

### Steps to reproduce the behavior
Get hurt and use a healing item.

**Comment by Vasyan2006** [comment]
This UI window was not changed and will show instantaneous healing from items (as it was before).
It is not possible to precisely calculate net healing from effects, because it will depend on taking damage, sleeping, mutations and other factors. You can see healing power of the item (intensity of applyed effects) in the item description.

**Comment by kevingranade** [comment]
We either need to display something useful in this menu or trim it down to just listing the body parts.
