### ISSUE TITLE
Feedback / Next Steps on Lab Expansion 

### ISSUE THREAD

**Issue by BrianLefler** [CleverRaven/Cataclysm-DDA#24508]
Hi, here is a potential roadmap for the lab work I'd like to implement over the next few months; not in any particular order.  I'm creating this thread as a central spot to get both early feedback as I work through these, as well as a place to get feedback after PRs are closed if they turn out to have issues in practice.

Most important, if some of these are controversial or would be unworkable, I'd love to know ahead of time so I can avoid/modify the idea.

<b>Refinement:</b>
- [x] Initial round of lab json. (feedback helpful on risk/reward and whether stylistically similar)
- [x] Placement of central lab. (feedback helpful on difficulty/size/discoverability)

<b>Lab Difficulty / Rebalancing</b>
- [x] Breakable doors - glass doors, frosted glass doors, or wooden doors when appropriate.
- [ ] Turn lab doors into automatic sliding doors so that monsters can chase.
- [ ] Make mutagenic serum rare: Generally limit availability to locked/defended areas, have recipes require a mutagenic concentrator tool found in a new lab finale.
- [ ] Less monster infighting - add a bot_ir faction that's friendly with zombies (representing infrared-targeting only), apply it to mon_skitterbots and a new mon_turret_ir.  Make half of lab turrets mon_turret_ir turrets instead.
- [x] Expand zombie tables to include shockers, shocker brutes, technicians.
- [ ] Add popup turrets: Spottable like traps, come out to shoot when nearby, difficult (but possible) to damage when concealed. 
- [ ] Add evolved zombie scientist variants.

<b>More Lab Content</b>
- [x] More floor-plans: Full-size mess hall, apartments, chemistry labs.
- [x] More randomized rooms.
- [ ] VR training terminals (functions like a stationary book, but faster).
- [ ] Finale that grants a friendly secubot.
- [ ] Finale that grants a VR terminal which can bring a random skill from 0 to 10.
- [ ] Finale with a 3D Printer (allows player to select any item in a given category: firearms, melee, clothing; then shuts down)
- [ ] Finale with a breeder reactor that gives plutonium once per day.
- [ ] Locked areas & a finale containing mutagenic serums.
- [x] Locked area with a library.
- [ ] Locked area with director's office & mansion-style loot.
- [ ] Locked area requiring military_ids to enter, resembling the bunker building.
- [x] Section-wide effects: Small chance any section will have running acid sprinklers, smoke-filled sections, flooding w/ shallow water, or radiation (including flashing red lights).

<b>Central Lab Content</b>
- [x] Mission for finding the lab subway tunnels (given by?) which also gives lore context.
- [ ] Make grand finale inaccessible without going down a separate mission chain to get a badge (hazardous waste facility chain?)
- [ ] Make grand finale inaccessible without an additional mission to get a badge from deep in a mall.
- [ ] Metal walls / terrain flag that prevents pickaxe/jackhammer tricks from entering via other routes.
- [ ] Central lab grand finale w/ loot and more lore?
- [ ] Add an optional 'Endgame' choice in grand finale for speed-run / challenge purposes.

**Comment by DracoGriffin** [comment]
>Lab Difficulty / Rebalancing
Turn lab doors into automatic sliding doors so that monsters can chase.

Yes. Although shouldn't be common.
>Make mutagenic serum rare: Generally limit availability to locked/defended areas, have recipes require a mutagenic concentrator tool found in a new lab finale.

Not sure about this one, are you suggesting unrefined mutagens that have to be used by the new tool/furniture in order to make mutagen? This one seems like it might be bigger than stated, need a bit more explanation.
>Less monster infighting - add a bot_ir faction that's friendly with zombies (representing infrared-targeting only), apply it to mon_skitterbots and a new mon_turret_ir. Make half of lab turrets mon_turret_ir turrets instead.

This sounds good as well in limited areas, especially with a few mi-go lines ("Oh god, why aren't the turrets shooting them!?", "Who thought IR-only defenses was a good idea?!", "*beep* W-wha... *beep* N-no, no don't *sounds of gunfire*" ) or blood-scrawled notes on ground or something.
>Expand zombie tables to include shockers, shocker brutes, technicians.

Yes. Technicians especially in the areas with the pipes and machinery.
>Add popup turrets: Spottable like traps, come out to shoot when nearby, difficult (but possible) to damage when concealed.

I don't think detection works very far yet and kinda difficult for the player to overcome. Could be an interesting mechanic with the range thing --- certain distance they have high protection, get closer and they can now damage but exposed and much more vulnerable. Trap detection would probably need to be looked over.
>    Add evolved zombie scientist variants.

I believe zombie scientists is something kevin has stated before about removing or moving away from, so variants could be interesting but should be ... "grounded" more in blob evolution, I suppose is the way to put it? I dunno, maybe like zombie scientists 

>More Lab Content
More floor-plans: Full-size mess hall, apartments, chemistry labs.

More is better, if you enjoy it, all the power to you friend. I've made two locations and took me forever. I hate making maps.
>    More randomized rooms.

As long as they don't look like some of the current randomized houses (that have bathrooms bigger than kitchens or bedrooms).
>    VR training terminals (functions like a stationary book, but faster).

This would be awesome as well, I know there's been talk of doing e-books and such (I think mainly on Discord, not sure if anyone referenced or worked on it for GitHub).
>    Finale that grants a friendly secubot.

Who wouldn't love a [friendly secubot](https://www.reddit.com/r/cataclysmdda/comments/8jtkcv/my_robot_exploded/dz360vj/?context=10000)?
>    Finale that grants a VR terminal which can bring a random skill from 0 to 10.

I don't know if a finale can be that challenging to offer such a steep reward. While cool and fun for gameplay, if we're going to talk "balance", no idea how this would work. However, if it's some sort of training lab for Prime mutants to make supersoldiers or superscientists or something (How funny would it be if you got 0 to 10 in Bartering or Speech, oof), then more plausible.
>    Finale with a 3D Printer (allows player to select any item in a given category: firearms, melee, clothing; then shuts down)

This could be actually cool, to potentially duplicate or make a second item of a super rare item you have (looking at you can sealer before that PR made you craftable or faraday shark suit or [insert item players have been looking for but could never find due to RNG]). Could also include other versions that can be used to input with base ingredients (Wood/metal/plastic) and templates you might find on usb drives or on the E-Ink PC tablet.
>    Finale with a breeder reactor that gives plutonium once per day.

Interesting, but kind of lackluster with the Microreactor CBMs, disassembling Power Storage CBMs or visiting the National Guard Camp (if enabled, player can walk out with a ton of plutonium if they are careful and don't die horribly).
>    Locked areas & a finale containing mutagenic serums.

All for it, especially with more lore tidbits of notes and such. Maybe even horrible half-mutants bodies or still alive (similar to Broken Cyborgs).
>    Locked area with a library.

Don't tempt me, that sounds lovely.
>    Locked area with director's office & mansion-style loot.

Sounds cool, maybe the "suit of armor" turns out to be a hostile robot.
>    Locked area requiring military_ids to enter, resembling the bunker building.

Can still bypass with electrohack and equivalent CBM, right? Although there is always bombs and pick axes too.
>    Section-wide effects: Small chance any section will have running acid sprinklers, smoke-filled sections, flooding w/ shallow water, or radiation (including flashing red lights).

YES! Also with the flooding, maybe some areas that will shock player (exposed power line or equivalent, maybe a malfunctioning robot) -- may need some type of visualization so players can be aware (like the description is different "This area looks flooded." compared to "This area looks flooded and you can hear faint crackling of an exposed power cable" or maybe an exposed access panel terrain tile near the water).

>Central Lab Content
    Mission for finding the lab subway tunnels (given by?) which also gives lore context.

Yes. Scientist trying to recover information, soldiers trying to reclaim lab, looters trying to get access, merchants trying to make a safer trade route underground rather than exposed above to zombie hordes / nether monsters / bandits.
>    Make grand finale inaccessible without going down a separate mission chain to get a badge (hazardous waste facility chain?)

Or similar to Temple places (need rare item to unlock entrance). And maybe not EVERY finale needs one. Not sure about the proportions, but maybe at least 25%/33%? Also, what about explosives? Won't that allow access?
>    Make grand finale inaccessible without an additional mission to get a badge from deep in a mall.

Maybe not always a mall, but other large overworld locations. Maybe also interact with existing Refugee Center to earn trust of a faction? Become a Marshall in order to convince NPC you're a "good guy" or something.
>    Metal walls / terrain flag that prevents pickaxe/jackhammer tricks from entering via other routes.

Ahh, yes this answers some questions above. However, how about explosives? Especially with #24171.
>    Central lab grand finale w/ loot and more lore?

Of course!
>    Add an optional 'Endgame' choice in grand finale for speed-run / challenge purposes.

Yes, seems interesting. There is the Ascension mod, but also there are missile silos in-game as well. Maybe you pull a Half-Life and go to nether world(s) (but then it ends there, a nice juicy cliffhanger --- "And [survivor name] was never heard from again..." or maybe you contact the Old Guard flotilla in Atlantic Ocean with information that prompts reinforcements to take back areas.

**Comment by BrianLefler** [comment]
>> Turn lab doors into automatic sliding doors so that monsters can chase.
>
> Yes. Although shouldn't be common.

Could convert all of the metal doors into either automatic metal doors or manual wooden doors?  Hope is to get rid of the situation where very room can be closed without consequence if you don't like the contents (vs a town, where you might need to run away and circle back).


>> Make mutagenic serum rare: Generally limit availability to locked/defended areas, have recipes require a mutagenic concentrator tool found in a new lab finale.
>
> Not sure about this one, are you suggesting unrefined mutagens that have to be used by the new tool/furniture in order to make mutagen? This one seems like it might be bigger than stated, need a bit more explanation.

Would leave non-serum mutagens alone.  Injectable serums, which are supposed to be rarer, would go from 'same item group as mutagens, but less common' to being special loot in locked locations/finales.  Right now serums have a recipe which consumes 2 mutagens--that would stay the same, but it would require a mutagen concentrator instead of a chem set.  So out of reach until you find a mutagen finale (exactly like diamond weapons are out of reach until you find a CVD machine).  I was imagining a portable tool, but I guess it could be a machine instead.

>> Locked area requiring military_ids to enter, resembling the bunker building.
>
> Can still bypass with electrohack and equivalent CBM, right? Although there is always bombs and pick axes too.

Yes, sounds good.


>>Finale that grants a VR terminal which can bring a random skill from 0 to 10.
>
> I don't know if a finale can be that challenging to offer such a steep reward. While cool and fun for gameplay, if we're going to talk "balance", no idea how this would work. However, if it's some sort of training lab for Prime mutants to make supersoldiers or superscientists or something (How funny would it be if you got 0 to 10 in Bartering or Speech, oof), then more plausible.

Ok, good advice.  I was thinking VR terminals wouldn't be instant, this would be much like finding three skill books at the same time (0->3, 3->6, 6->9).  You'd still have to camp there for hours to take advantage of it.


> "And [survivor name] was never heard from again..."

Yeah, that is perfect.  Open-ended is good so that it does not become the definitive 'right ending'.

**Comment by DracoGriffin** [comment]
>Could convert all of the metal doors into either automatic metal doors or manual wooden doors? Hope is to get rid of the situation where very room can be closed without consequence if you don't like the contents (vs a town, where you might need to run away and circle back).

Probably most of them would qualify for automation, my opinion for manual doors would be some maintenance areas (in case of power failures, probably need areas that are accessible without ID cards or something) and some storage areas. Barracks probably manual as well (at least after the entrance). Certain offices maybe as well.

>Would leave non-serum mutagens alone. Injectable serums, which are supposed to be rarer, would go from 'same item group as mutagens, but less common' to being special loot in locked locations/finales. Right now serums have a recipe which consumes 2 mutagens--that would stay the same, but it would require a mutagen concentrator instead of a chem set. So out of reach until you find a mutagen finale (exactly like diamond weapons are out of reach until you find a CVD machine). I was imagining a portable tool, but I guess it could be a machine instead.

Ok, that makes sense that advanced mutagen (serums) could require specialized equipment and also have notes/lab books to make portable/vehicle versions (basically some of the scientists were trying to leak the information or something), but aren't guaranteed at every lab or mutagen finale (kinda like how the current lab notebooks spawn). Probably need to update lab note books regarding the special equipment needed.

>Ok, good advice. I was thinking VR terminals wouldn't be instant, this would be much like finding three skill books at the same time (0->3, 3->6, 6->9). You'd still have to camp there for hours to take advantage of it.

Or perhaps link it to Intelligence, so higher Int survivors get more benefit. Maybe one series would be enough (0->3 or 3->6 or 6->9), but I could see players min-maxing it to save it so they can skip skills to later, which suppose could be feasible... yeah. This one I'll just avoid commenting further on and someone else could give some feedback or ideas.

**Comment by kevingranade** [comment]
Overall, love everything you're doing, I dont think theres anything I object to.

> Turn lab doors into automatic sliding doors so that monsters can chase.

Lots of options here, at the end of the day I think we want the player to be able to close off some but not most of the rooms.  Even if it's around 50/50, it will end up in a situation where just a handful of monsters can make most of the lab dangerous.  There are a number of ways to accomplish this, self-opening doors, broken doors, fragile doors (glass seems more thematic than wood in general).


> Make mutagenic serum rare: Generally limit availability to locked/defended areas, have recipes require a mutagenic concentrator tool found in a new lab finale.

Haven't looked into the balance, but I'm generally in favor.

> Less monster infighting - add a bot_ir faction that's friendly with zombies (representing infrared-targeting only), apply it to mon_skitterbots and a new mon_turret_ir. Make half of lab turrets mon_turret_ir turrets instead.

Mildly in favor, though I share JCs concern about labs being one of the coolest areas for triggering infighting.

> Expand zombie tables to include shockers, shocker brutes, technicians.

In general I expect zombies to be an incidental danger in labs, I'd prefer the main dangers to be lab specific, some of which you've outlined and sounds great.

> Add popup turrets: Spottable like traps, come out to shoot when nearby, difficult (but possible) to damage when concealed.

Nice.
> Add evolved zombie scientist variants.

Not super hype about this one, scientists are a kind of goofy exception to how zombies are supposed to work.  That being said they might just be a clever palette swap away from making sense.

> VR training terminals (functions like a stationary book, but faster).

Neat, yea no issue with that as long as they arent too ubiquitous.
> Finale that grants a friendly secubot.

That works, needs upkeep to keep it from being a win button.
> Finale that grants a VR terminal which can bring a random skill from 0 to 10.

Same as the other one, just needs appropriate rarity.
> Finale with a 3D Printer (allows player to select any item in a given category: firearms, melee, clothing; then shuts down)

Less enthusiastic about this. 3D printing doesn't work like that, and having examples of it working it this way is going to encourage people to demand it even more.  If you can come up with a different source for the one-off item appearance, I have no objection.
> Finale with a breeder reactor that gives plutonium once per day.

No problem there, though it seems like it would also accumulate a stockpile in between.
> Locked areas & a finale containing mutagenic serums.
> Locked area with a library.
> Locked area with director's office & mansion-style loot.

Cool.
> Locked area requiring military_ids to enter, resembling the bunker building.

I like the idea of sub-areas within the lab that require extra resources to enter.  Also nice would be multiple clearance levels.
> Section-wide effects: Small chance any section will have running acid sprinklers, smoke-filled sections, flooding w/ shallow water, or radiation (including flashing red lights).

All of these would be amazing.
> Mission for finding the lab subway tunnels (given by?) which also gives lore context.

Works in both directions, entering and exiting the lab.
> Make grand finale inaccessible without going down a separate mission chain to get a badge (hazardous waste facility chain?)

Totally on board with this.
> Make grand finale inaccessible without an additional mission to get a badge from deep in a mall.

Not sure why a mall, a hospital, government office, military compound or police station would work though.
> Metal walls / terrain flag that prevents pickaxe/jackhammer tricks from entering via other routes.

At least in some cases, it should still be possible with enough resources (I'm thinking drills and explosives).
> Central lab grand finale w/ loot and more lore?

Yea special mega labs as a secondary location would be great.
>  Add an optional 'Endgame' choice in grand finale for speed-run / challenge purposes.

Not sure what you mean by this.

Something I'm not seeing is making lab layouts more internally consistent, like having security zones vs living zones vs research zones, and having different security levels for each.  It's understandable if it's not something you're interested in, but I think it'd improve consistency a lot.

Other finale ideas:
Lock up some of the uber bionics like time dialation.
Teleporter network.
Large scale map reveal, possibly real time with population mumbers.

**Comment by BrianLefler** [comment]
Thanks.  Will deprioritize anything controversial until I can give the idea more thought.  I'll also give some thought to macro-scale lab layouts, which I had not before.  But it would mean a change in build_city algorithm, which I had kept at arms length.  So long as labs remain big blobs, then it's hard to have badge chokepoints.  It would be easy to have a 'residential floor', 'research floor' etc, but no guarantee of all floor types, so that's weird too.

The other issue with zoning might be whether there's enough content for each zone.  Vs when anything can go anywhere, there is at least a lot of content which is selectable from.

>> Add an optional 'Endgame' choice in grand finale for speed-run / challenge purposes.
>
> Not sure what you mean by this.

Like a stable portal you could go through and the game ends--possibly leaving up in the air what happens.  So if people wanted an end-point for a run through, they could designate this as it.

>> Make grand finale inaccessible without an additional mission to get a badge from deep in a mall.
>
> Not sure why a mall, a hospital, government office, military compound or police station would work though.

Thought would be you need a high security id, and the exec with it was in the mall at the time of the cataclysm.  Chosen only because malls are the densest zombie-rich place I can think of and I'm not aware of any reason to go to malls otherwise.

**Comment by curstwist** [comment]
First, thanks for all the work on the labs.  I'm really enjoying your first release.

> Section-wide effects: Small chance any section will have running acid sprinklers, smoke-filled sections, flooding w/ shallow water, or radiation (including flashing red lights).

I think the atmospheric elements like smoke filled corridors, flooding, etc will give a lot of tension and ambiance to labs.  Great idea.  I'd like to suggest adding sewage flooding since labs can be connected to sewers.  Maybe around areas with sewer access?

Questions about this part:
> Make mutagenic serum rare: Generally limit availability to locked/defended areas, have recipes require a mutagenic concentrator tool found in a new lab finale.

As with the autodoc, expect players to want to be able to dismantle and take the instrument with them.  If that won't happen (reasonable), it may need additional locations.  It's not quite as important as for autodocs since you aren't locking out lower level mutagens but I'm sure it'll be a community complaint.  Will serums have other gated areas outside labs too?  Maybe the Hazardous Waste Sarcophagus since you are considering using that as well and high end doctor's offices (like the new autodoc clinic).

...Or maybe I just misread that and 'tool' refers to something you take with you instead of furniture like the centrifuge.  

>  Add popup turrets: Spottable like traps, come out to shoot when nearby, difficult (but possible) to damage when concealed

Pop-up turrets worry me some, perhaps some warning beeps can precede it's arrival to give lower level characters a chance of escape?  Not a fan of surprise insta-death encounters.

> Finale that grants a VR terminal which can bring a random skill from 0 to 10.

Will illiterate survivors be able to access this?  

>  Make grand finale inaccessible without an additional mission to get a badge from deep in a mall.

I can see this society's scientists and military thinking this is a reasonable place for an extra secret lab or even a recruiting office.  Maybe also consider the under used missile silos or military outposts (the ones with bio-operators and turrets outside)

**Comment by Solusphere** [comment]
As someone who loves lab starts, how exactly are you supposed to deal with the popup turrets? That seems like the kind of thing that would be near impossible to avoid without very high trap skill, and that's something you generally don't have access to when just starting out.

**Comment by Human-Shield** [comment]
Love the work to make labs closer to campaign areas like a vault. I think like a vault the spawns should be made unique, so a 'Lab' faction that is friendly with each other (so lab robots don't shoot former lab workers but will shoot outside zombies). This also lets you distract robots and turrets by opening containment prison areas that are filled with normal zombies or other creatures. Zombies with two factions listed should be friendly with both, right? 

Auto doors would be great if the player could actively work to seal them.

Serums being moved to something that the player has to be proactive to get would be a good idea. I would like a higher tier of bionics that are only in lab finales as well. 

Another idea for finale or lab section content : Mutated or bionic filled NPC companion in cryo sleep that can join your party. Or an insane one that has broken out and claimed a section of the lab.

**Comment by DracoGriffin** [comment]
Some additional input from C:DDA Discord:

From @Soyweiser : 
>Have it have a limited supply of power, but don't tell the players that (aka, watch the rage as suddenly the computer goes dark)

I'd suggest there would be some type of power meter or at least a warning of how long before the device powers down. Potentially have a use for the breeder reactor finale (bring plutonium cells from there to this device to power it).

From Inglonias (not sure if have GitHub account):
>You can have a rare station in the library that downloads random audio books to your e-Ink PC
Or an SD card, or a USB drive

A digital copy of a book that is without recipes and can potentially allow illiterate characters to learn. Or even allow the VR stations to scan books on some type of limited basis. Or use this rare station mentioned that can be copied onto SD card / USB drive that you can then take to a VR station (to allow some interaction between these features between labs). So if you find a VR station, you'll probably want to keep searching more labs to find a "Library Station" that can teach you books faster or something.

Either way, just discussing this subject to show interest in it. Looking forward to all the great work.

**Comment by MT-Arnoldussen** [comment]
>Less monster infighting - add a bot_ir faction that's friendly with zombies (representing infrared-targeting only)

Zombies currently do show up using IR-vision, so that would need to be changed too.

**Comment by Lorith** [comment]
Going to leave a few of my ideas as someone that spends way too much time in labs: Lab starts are nasty even before the certain death aspects of some of the entry areas comes into play, due to lack of resources and the like.  The current rebuild of labs seems to help quite a bit with that, but the entry/exit should be looked into.

I would recommend airlock style entry with turrets on the inside, preferably at least two with different firing angles.  Exposed turrets should probably have a way to notice them before just dying, such as a turn where you can peek around, and/or bodies present in the area the turrets can hit.  Additionally, a T shape can be made with turrets on one side pointing down towards the entry/exit hall.

Another idea would be making multiple levels of ID cards and higher security sections inside the lab, and other secured areas that require IDs to open up, with spawns of lower level IDs inside the lab that work for the lower security areas and the exit.

When I have some time I'll go ahead and do a bit of a mock up of some stuff I think would work well - I still can't figure out how the mapgen works atm, unfortunately.

**Comment by RadHazard** [comment]
The mutagen rebalance should definitely be broken out into it's own discussion.  I think it makes sense for it to happen, but the rarity of mutagens and recipes needs to be spread out more than it needs to be made overall more rare.

At the moment, mutagens are basically inaccessible until you find a (very rare) recipe book, and then it suddenly becomes easy to mass-produce mutagens by the gallon.  There's no point in scouting labs for mutagen vials since the chances of finding even one vial of a tree you want is less than the chances of finding the recipe book for it.

Making the recipes for mutagen harder or more rare partially fixes that, but shifts the balance to the point that you'd need to scout potentially dozens of labs to find a useful quantity of mutagen.  That would push mutagens so far into the late game that they're basically pointless unless you want to roleplay as a furry.

The best solution for that IMO would be to make the actual vials of mutagen significantly more common in labs compared to the recipes (even if they're locked behind doors or something).  Maybe add dedicated "mutagen storage vaults" guarded by turrets or mutated NPCs, similar to the CBM storage rooms we currently have.

These rooms wouldn't have recipes, but they'd have a larger quantity of mutagen vials compared to the current mutagen rooms.  Ideally, most successful lab dives should give enough mutagen to at least experiment with transhumanism in much the same way almost every lab contains a decent quantity of CBMs (even if they're not *good* CBMs).

**Comment by BrianLefler** [comment]
100% agree with the balance criticisms about mutagen drops.

Would this be in line with what you're thinking, @RadHazard ?
- keep basic mutagen drops as they are.
- make flavored mutagen drops often come in repeat doses, so players can find a stash which gives them some shot of getting onto that mutation tree.
- have locked areas with a higher density of mutagens, including serums.
- move as much else into finale rewards
  - mutagen recipes restricted to being a finale reward (other than the basic recipe).
  - a big vat of basic mutagen as a finale reward.
  - make the ability to manufacture serums into a finale reward.
  - make a finale reward that allows duplicating flavored mutagen in inventory (a limited number of times).

That could basically mean a player could have a good time exploring normal lab loot, but finales would either 1) unlock better mutagen cooking, 2) provide alternatives to mutagen cooking.

**Comment by RadHazard** [comment]
@BrianLefler those suggestions sound pretty close to what I was thinking.  I'm not too concerned about the specific details, just as long as hunting existing mutagen flasks becomes a viable option to mutate before you get the ability to manufacture your own.

I especially like the suggestion that flavored mutation comes in sets.  A single flask is almost not worth using but if you happened to find, say, 3 of them, it may become more tempting to roll the dice.

**Comment by secretfire42** [comment]
Some of this stuff sounds really awesome. One lore suggestion/alternative I'll note. If your going to 'make the labs make more sense' and redo them, and make out specific areas - there are two points I always thought were wierd. 1: In 'real life' you don't loose your security badge when you enter a facility, you know? It might ONLY WORK AT THAT ONE FACILITY, or not allow access to the whole thing - but you won't suddenly loose it. Perhaps when your redoing things, make it so that having a science ID doesn't permanently open the lab in question, but also - that it doesn't steal the ID forever. 

Likewise, one solution to 'more common turrets' with the lab-ID start would be, as mentioned above, multiple security levels. Or, alternatively/in conjunction with that, have ID badges have a randomly assigned (hidden to the player without checking on a military base computer or somesuch) security level, with access to specific parts of the facility, and as long as you don't leave those 'allowed parts' turrets won't attack you, but if you do, the turrets become hostile and the ID card is deactivated. (which would suck, but your going for a difficulty increase.)

The other thing is, if you guys are going to have a highly secured area with mutagen/etc; - all of the ideas above are great. One thing to consider however, might be some secure machine that rapidly pumps in mutagen into you of a specific subtype; which you can't control. There should be some sort of way to get a decent 'number' of mutations of a random sort the player can't control. I mean, its interesting from a gameplay point of view (will I end up as a freaking cow if I go in there?) - but also, lorewise, you have endless rooms in these places where apparently they were testing mutants, again and again, and then injecting them with purifier. There is a distinct lack of half-mutated insane people, OR whatever automated process they were using to do this. 

Also, if I was stolen and experimented on in a lab, and repeatedly partly mutated into a rat, octopus, plant, etc - I'd probably honestly start to go a bit mad. I think Kevin is right about not wanting too many zombies in labs; they should feel special. But perhaps some mostly-human but completely-insane part-mutants might not be so bad, especially ones locked in areas you might want to get to, and thus safe from the turrets....

**Comment by Nightquaker** [comment]
Hey!
Sorry for "necroing" this, but the issue is open still, so I decided to pop into the discussion.
Have the labs in house basements ever been implemented? I find the idea a bit strange. I mean, people having labs in their house basements isn't completely unrealistic, but it is very, very rare I'd imagine.

**Comment by cainiaowu** [comment]
Well, the "lab" ingame are all government funded large scale high security type secret evil site which doing human experiment stuff. Not your DIY basement type.

**Comment by Nightquaker** [comment]
Also, now I realized how stupid the "inhabitants not knowing of labs in their basements" sounds. But regardless, in one of the previous issues it was mentioned that houses will indeed have labs in their basements. But I haven't played enough of the newest experimental to find any houses like that. Hence why I'm asking about it here.

**Comment by BrianLefler** [comment]
Yes, they are implemented but rare.  I had imagined any houses over a basement labs represented a cover identities, ala the Arklay Mansion in Resident Evil 1.

It would be awkward to imagine massive foot traffic in and out of a house, so it might be nice to do some kind of different treatment like having them always be a very small 3x3 lab or ensuring access to the lab monorail.

They are smaller on average just because they skip the first level of the lab which is generally larger, but it could definitely have a better treatment if something unique was done for it.  The implementation I have was just something I could do quickly, I'm not opposed to improving it or having someone improve it.

**Comment by Nightquaker** [comment]
I think those labs could be actually something of a backup, really. In case the central lab and other bigger labs get nuked (hypothetically). Therefore, not really requiring any personnel in them and being sealed! Heavily sealed, of course, and very well hidden. And of course, very small.
I think something like that could be realistic.
And the houses themselves would be pretty much for masking of said labs. Say, they were bought out (forcefully) from their previous owners and are now owned by the government.
How about that?

**Comment by Nightquaker** [comment]
Furthermore, the "lore" in my previous post probably wouldn't require any alterations of the current labs at all, really. Aside from making them smaller, but even that is not necessary.
Though, maybe a mention of said lore in the game somewhere would be nice. Maybe in a note from a private investigator somewhere, or something like that.

**Comment by kevingranade** [comment]
> And the houses themselves would be pretty much for masking of said labs. Say, they were bought out (forcefully) from their previous owners and are now owned by the government.

This is more or less how I see it, the house is either empty, or has a guard with appropriate security clearance stationed there to maintain the cover.

**Comment by Nightquaker** [comment]
Hmm. I think a guard in the middle of the neighborhood would actually blow the cover.
I reckon, it's better to just have the government agent(s) living in the house, blending in.

**Comment by Nightquaker** [comment]
You know, never mind. The entire neighborhood is zombies, ha!

**Comment by Night-Pryanik** [comment]
@BrianLefler are you still working on this?

**Comment by BrianLefler** [comment]
No, I will close this issue.  I can reopen or create a new issue if I pick back up the work to create a grand finale for the central lab.  But even without it, the central lab is a valuable find (by accident or by completing the mission chain) since it contains multiple standard lab finales.

**Comment by BrianLefler** [comment]
I am glad folks like @I-am-Erk are adding more things to the labs, though!  I don't want (or have) a monopoly on lab changes.

**Comment by I-am-Erk** [comment]
For what it's worth, I don't have too many plans to delve underground with labs except to possibly add some new nested maps... So if you do decide to get back into what you were doing at any point, it's not likely to conflict.
