### ISSUE TITLE
Average precipitation is unrealistic.

### ISSUE THREAD

**Issue by Vasyan2006** [CleverRaven/Cataclysm-DDA#24505]
Game version: 7587

Operating system: Windows 10 x64

Tiles or curses: Cursed

Mods active: none

### Expected behavior
Every summer month should have near the same or above average precipitation compare to other seasons according to https://en.wikipedia.org/wiki/Climate_of_New_England

### Actual behavior
Twice as less precipitation during summer compare to spring.

### Steps to reproduce the behavior
Use `get_weather_conditions()` function and calculate number of hours with `WEATHER_DRIZZLE`, `WEATHER_RAINY`, `WEATHER_THUNDER` and `WEATHER_LIGHTNING` during summer and spring seasons.

It may be not a thing, but I am working on new Plants'n'Weed watering system for #24291, so game balance will be quite unrealistic.

UPD: Average precipitation during summer season is 300 mm (from the wiki link above).
Ingame precipitation during summer (91 day per season) is 2700 mm.

**Comment by nexusmrsep** [comment]
**Side note:** I haven't read the weather daemon's code line by line (but saw it's beauty), but it might be possible to completely change the climate via an option or a mod (set of mods), so that if you wanted, you might play in a desert climate, or a monsoon climate, all of which could be coded in a json sets. Furthermore, consider that with a mod that would swap New England's wildlife with desired climate's wildlife (moose to elephant, cougar to lions), and swap the trees to for ex. palms, banana trees, etc. change the ratios for terrain generation (desert = scarce trees, jungle = max trees.) and 'New England' would no longer be a constans as goes for the place of action.

Just a dream now.... but I'd love to see that some day - just imagine the style of play changes due to different survival aspects (lack of water in the desert, hot humid jungles, etc.).

**Comment by Inglonias** [comment]
i blame global warming.

**Comment by nexusmrsep** [comment]
> i blame global warming.

In one of my PR's (might be wip/pending yet) I've moved `SPRING_TEMPERATURE` (spring) to `game_constants.h`, so yes... bump that up, and you'll get your global warming alright. But without pairing it with humidity/precipitation/cloud effects you won't get the full measure of it.

**Comment by Vasyan2006** [comment]
You can change "base_temperature" and "base_humidity" in "regional_map_settings.json", but in any case this !"§$%&/ Maxwell's demon will do unnatural things with climate.
