### ISSUE TITLE
Wolves, dogs, coyotes and other animals should have a fear trigger.

### ISSUE THREAD

**Issue by RafeHaab** [CleverRaven/Cataclysm-DDA#24521]
Game version: any

Operating system: windows 10

Tiles or curses: any

Mods active: any

### Expected behavior

Bears and mooses have a fear trigger (noise), but dogs, wolves and coyotes do not. I think one should be implemented because at of now, your ownly choice is to fight them off.

### Actual behavior

Said enemies don't have a fear trigger.

### Steps to reproduce the behavior

I'll simply link to this reddit comment where another user and I were talking about the topic.

https://www.reddit.com/r/cataclysmdda/comments/92php8/currently_4_days_into_a_no_starting/e37lf44/

**Comment by DracoGriffin** [comment]
Yes, that's me, now you should suggest what that fear trigger should be.

**Comment by RafeHaab** [comment]
Wolves are shy by nature. They won't attack anything that they see as dangerous. Noise would be a good fear trigger, but it's already done in the game and runs the risk to become boring for players if every predator can be scared away by yelling.

What I propose is to keep "friend attacked" as an anger trigger, but change "friend killed" to a fear trigger for these species. It's realistic, as seeing a pack memeber die means this "prey" (the player) is too dangerous to be a prey, and mimicks actual wolf/dog behaviour. It also makes the "hit and run" ingame tactic they use better, as you can tell they are afraid of getting hurt. Fleeing when one of them is killed would make it possible to survive their attacks and make the game more fun and realistic.

If the order of the triggers in the code matters, it should be like this: friend killed (fear), stalk, player close, player weak, friend attacked (anger)

**Comment by nexusmrsep** [comment]
Fire, lit torches. Although not even sure it can be implemented.

**Comment by ipcyborg** [comment]
Fire and Animal Behavior:
https://talltimbers.org/wp-content/uploads/2018/09/161-Komarek1969_op.pdf

According to this doc:
>It may surprise many that animals do not have an innate fear ot
fire. 

Looks like we don't need to add "FIRE" to fear_triggers for mammals. 
And probably remove "FIRE" from "gigantic naked mole-rat" (mon_nakedmolerat_giant). 

This confirms adding the "SOUND" trigger to fear_triggers:
https://www.businessinsider.com/what-to-do-if-you-are-attacked-by-a-pack-of-wolves-2015-12

Still not sure about FRIEND_DIED, probably just leave this for now.

So, if I'm correct, this issue is all about adding "SOUND" trigger to fear_triggers for dogs, wolves and coyotes.
I could use this as the "Good First Issue" :)
Or is it require more research?
