### ISSUE TITLE
This unwinnable death trap of a lab labout.

### ISSUE THREAD

**Issue by Sorgklaan** [CleverRaven/Cataclysm-DDA#24545]
<img width="114" alt="cataclysm-tiles_2018-07-30_01-43-08" src="https://user-images.githubusercontent.com/36496033/43379644-70b05228-939b-11e8-83e5-62531f96239b.png">

Walked up the stairs and died immediately to two turrets. Nothing I could have even done.

**Comment by Lorith** [comment]
Did a quick fix after spotting this on discord. [Replaces data\json\mapgen\basement\basement_lab_stairs.json](https://cdn.discordapp.com/attachments/252368751016542218/473375960037589002/basement_lab_stairs.json)
Changed it from certain death to being safe from the inside, using [an airlock](https://cdn.discordapp.com/attachments/464930574818082816/473377698262155264/unknown.png) design, since we already have a design that has an exposed turret.

**Comment by ZhilkinSerg** [comment]
> Did a quick

Consider making a PR.

**Comment by Lorith** [comment]
Unfortunately, I can't seem to get git to work lately.

**Comment by 0be1isk** [comment]
If it's cool with Lorith, I'll do it

**Comment by 0be1isk** [comment]
ignore that commit, still trying to figure out how git fully works

**Comment by DracoGriffin** [comment]
[If this helps at all](https://github.com/CleverRaven/Cataclysm-DDA/issues/24511#issuecomment-408632655), @0be1isk.

**Comment by 0be1isk** [comment]
@DracoGriffin 
yea I accidentally updated master

**Comment by 0be1isk** [comment]
@DracoGriffin 
Thanks, think I got it working
