### ISSUE TITLE
Disinfectant soaked rags/cotton balls recipes don't produce enough of final product

### ISSUE THREAD

**Issue by stekolla** [CleverRaven/Cataclysm-DDA#24649]
Game version: 0.C-30025-g02305e8

Operating system: Windows

Tiles or curses: Tiles

Mods active:

### Expected behavior
Disinfectant soaked rags and cotton balls allow your disinfectant supply to stretch further.

### Actual behavior
Recipes for disinfectant soaked rags and cotton balls only produce 1 soaked rag/cotton ball for each disinfectant used.

### Steps to reproduce the behavior
Create disinfectant soaked rags or cotton balls.

Previously, the recipes called for (and resulted in) 4 rags/2 cotton balls to 1 disinfectant, but were changed to 1 rag/1 cotton ball to 1 disinfectant by commit https://github.com/CleverRaven/Cataclysm-DDA/commit/945c9b068e1419146b33ca0bfc746f5ba7eeb4dd

**Comment by Vasyan2006** [comment]
Disinfectant has more charges for the same volume now, so you spend near the same volume of disinfectant per rag/ball as it was before.

**Comment by stekolla** [comment]
Hi Vasyan, that makes sense, but doesn't address the game balance aspects.  A single disinfectant soaked rag is less effective than a single use of liquid disinfectant (the soaked cotton balls are equally effective), so there is no reason why a player should ever craft them -- you're simply giving up 1 rag/cotton ball for no benefit. It's in contrast with the description for disinfectant soaked rags, which contains: "Not as effective as pouring it on the wound, but useful to optimize the bottle contents."

**Comment by Vasyan2006** [comment]
Wrong item description must be fixed. Balance of healing power between items with same properties (e.g. disinfecting) is rather simple - all high quality pre-cataclysm items have the same power. Because liquid disinfectant and antiseptic powder were created for different first aid actions and cannot be combared directly.

**Comment by stekolla** [comment]
Hi Vasyan, I'm not sure I understand what you're saying.  Are you saying that item's description should simply be updated?  If so, that doesn't address my concern that the disinfectant soaked rag and disinfectant soaked cotton balls are now pointless because making them simply leads to a similar amount of charges, but of an inferior potency.  Since you can just use 1 charge of liquid disinfectant directly, why would you instead use that 1 charge to create and use a 1 charge disinfectant soaked rag that is inferior?  That was the previous benefit of the disinfectant soaked rags/cotton balls -- it would allow you to use 1 charge of liquid disinfectant to make multiple charges of a lower potency disinfectant.

**Comment by Vasyan2006** [comment]
>disinfectant soaked rag and disinfectant soaked cotton balls are now pointless

Exactly, like antiseptic powder, hydrogen peroxide, hemostatic powder and many other healing items. It is somewhere planned to rework healing system, remove HP and treat each wound separately, in this case every item will have its role.

Actual disinfecting the wound (as a part of wound dressing) with liquid desinfectant requires some sort of cotton ball to apply disinfectant properly. So disinfectant soaked cotton balls must have better healing power and make much less damage to the wound (due to higher precision of applying) compare to using disinfectant directly from the bottle.

But personally I dont want to participate in the minor rebalancing of a single item until new healing system will be introduced, because all item properties will be changed anyway.

**Comment by nexusmrsep** [comment]
Shouldn't this be closed as a result of #24710 ?

**Comment by pjf** [comment]
+1 here for re-opening this issue. Making disinfectant soaked items doesn't seem to provide any benefit, and in some cases makes things worse, so it was certainly confusing for this new player as to how they fitted into the game.

If possible, I would suggest removing these items from the crafting menu until the new healing system comes in.
