### ISSUE TITLE
Missing Status Effect on Character Screen after taking Antibiotics/Atreyupan

### ISSUE THREAD

**Issue by DracoGriffin** [CleverRaven/Cataclysm-DDA#24651]
### Expected behavior
A status effect similar to bandage/disinfectant, that states something like "Started [antibiotics/Atreyupan]" with the descriptor of the new infection system (no longer instant, process over number of hours, etc). "You started an antibiotic regimen to fight off infection, but it could take up to 12 hours before you recover, or you may need to take another dose."

### Actual behavior
No message if given to NPC, but there is a message in the message log when taken by the survivor. Otherwise, there is no way to track under the effects of antibiotics to avoid "overdosing"/repeatedly using antibiotics since infection is no longer on/off.

This [comment](https://www.reddit.com/r/cataclysmdda/comments/94noxk/antibiotics_overhaul_and_atreyupan_how_have_they/e3ob7tm/) on C:DDA subreddit prompted my testing.

**Comment by Xhuis** [comment]
Should be a pretty easy fix. I deliberately didn't include a status effect since medicines such as Xanax and Adderall don't have them; it's why I included the unique message if you take one without already having a dose in your system. Simple fix - just add a name and description in `effects.json` - but it's that way by design, though I have no problem with such a design being changed.

**Comment by Night-Pryanik** [comment]
Xanax and Adderall could have effect descriptions too, as well as antibiotics. There is no secret of what each of this drugs do, and their effects not having descriptions feels like more of forgetfulness rather of design decision.

**Comment by Xhuis** [comment]
Realistically, would you be aware of the exact effects and lengths of a drug dose? I certainly don't; I just feel the effects of the medicine and they slowly fade out when the dose wears off. I think it's reasonable that they not be visible by default. Perhaps it'd be possible for a trait like Self-Aware to allow you see the exact times.

**Comment by DracoGriffin** [comment]
>Xanax and Adderall could have effect descriptions too, as well as antibiotics. There is no secret of what each of this drugs do, and their effects not having descriptions feels like more of forgetfulness rather of design decision.

They already attribute `Depressants` and `Stimulants`, respectively. Is there something more they should be conveying or uniquely?

Taking antibiotics/Atreyupan reveals nothing on status effect unless it cures an infection, which gives the "Recovering from Infection" status effect (which is valid, and useful to inform that player of the penalties from recovery) and that can happen hours after taking the medication (due to how the system works now). Secondly, a player can take antibiotics/Atreyupan without an infection and no status effect will ever appear.

**Comment by nexusmrsep** [comment]
@Xhuis you can read the dose time in effect on the packaging or a leaflet that comes with the medicine. And unless the medicine actualy changes your behaviour, or any other thing that you can feel, you don't percieve its effects. As for gameplay its a question of design - are effects strictly reserved for percievable things or can they be applied as a reminder of some actions that player did and know of them from memory only: "I don't feel it, but I remember that a I took antibiotic pill in the morning, so I should not take another untill next morning". Thats also quality of life thing. Say you take a pill, save & quit, then return to the game after a week. You will forget of that fact and it might end badly for the character if you don't have a way to check that. I am for this change. And Im not promoting in any way to show any other status that should be hidden by design.

**Comment by Night-Pryanik** [comment]
> I am for this change.

Me too.

**Comment by kevingranade** [comment]
If it's a reminder, it should be approximate, since players dont
necessarally have access to accurate timekeeping.
The message could be something like, "Took %medicine recently.", and the
duration should be nominal duration +/- 20% or so.
