### ISSUE TITLE
Consoles unlock/remove doors/windows in adjacent map tiles

### ISSUE THREAD

**Issue by maniak1349** [CleverRaven/Cataclysm-DDA#24701]
Windows, tiles, 0.C-29661-g765578f.
Mods: dda, no_npc_food, novitamins

After unlocking mi-go in the room to the north half of the storage doors turned into open doors:
![cata_misalign1](https://user-images.githubusercontent.com/2755776/43827633-d7aa6c8e-9ae9-11e8-8d28-a88f0814313e.PNG)

After unlocking cyborgs in autodoc room closed doors in lab to the north went missing:
![cata_misalign2](https://user-images.githubusercontent.com/2755776/43827644-dcd08388-9ae9-11e8-91de-3de308d30f2f.PNG)

Something. Likely another autodoc unlock:
![cata_misalign3](https://user-images.githubusercontent.com/2755776/43827648-e0580e90-9ae9-11e8-8af8-12878446f805.PNG)

After unlocking CBMs in lab's final room reinforced glass windows in lab to the north went missing:
![cata_misalign4](https://user-images.githubusercontent.com/2755776/43827650-e299a75e-9ae9-11e8-8ba5-fb487eaf101f.PNG)

**Comment by Lorith** [comment]
The computers don't have set locations they unlock, they simply process everything in a certain radius around them, making it difficult to control how they act.  The fix for this would be to feed them specific locations to edit, though that may cause more issues due to having to restructure how they function.
