### ISSUE TITLE
Mod Inclusion Project: blazemod and Tanks

### ISSUE THREAD

**Issue by mlangsdorf** [CleverRaven/Cataclysm-DDA#24730]
Proposal for mainlining blazemod and Tanks:

- [ ] I. Finish the clean-up of blazemod
- [x] A. Enable mod defined fuel types (see #24600)
- [x] 1. shift blobfeed and liquid blob feed to the new definitions.
- [x] 2. Re-enable vortex parts.
- [ ] B. Resolve the remaining issues with automatic turrets.
- [x] 1. Get rid of BATTERY_MOUNT hack
- [ ] 2. Change blazemod turret chassis to stabilized turrets, and make firing from on the move from an unstabilized turret much less accurate.
- [ ] 3. Add multiple turret mount sizes, so artillery pieces and LMGs can't be mounted on the same mount, and larger mounts take up more space in the vehicle.
- [ ] 4. Add C++ support as necessary.
- [ ] 5. Possibly clear out the vehicle turret menus
- [ ] C. Add proper C++ for treads and tread sprockets.
- [ ] 1. Create new tread vehicleparts to not break existing designs.
- [ ] D. Minor fixes to bring blazemod up to date with 2018-2019 CDDA concepts (lifting to install/remove parts, mounted weapons need firearms kits to repair, etc).
- [ ] E. Rebalance blazemod weapons so that improvised weapons are not better than pre-Catacylsm weapons.
- [ ] II. Clean-up Tanks
- [ ] A. Minor fixes to bring Tanks up to date with 2018-2019 CDDA concepts (lifting to install/remove parts, mounted weapons need firearms kits to repair, etc).
- [ ] B. Add some support vehicles to Tanks (armored bulldozer, trank crane, demolition tank with light howitzer)

To be determined:
- [ ] III. Merge mundane parts of blazemod and Tanks into mainline
- [ ] A. Bandit bulldozers, heavy tractors, and some support vehicles and their supporting vehicleparts, items, and recipes go into mainline
- [ ] 1. Merged vehicle designs use new parts, not old ones.
- [ ] A. blazemod non-blob, non-diamond, non-vortex parts go into mainline.
- [ ] IV. Remaining bits stay in the mods
       1. Tanks is reduced to actual tanks (main battle tank, light tank, atomic minitank, and the artillery pieces) and IFVs.
       2. Blazemod is blob parts and diamond/vortex parts.

I intend to work on this as I have time, but I welcome other views about how to approach it and/or contributors to the effort.

**Comment by DracoGriffin** [comment]
Appreciate your work so far on blazemod, thanks for showing the initiative.

**Comment by 321nick** [comment]
i think its really nice, but idk if blob parts, solar arrays, diamond, and vortex parts should go into crazy cataclysm. i thought crazy cataclysm was for the un-immersive, or just plain silly stuff, like easter eggs and such, not the sorta-plausibly-believable-ish stuff.

**Comment by FulcrumA** [comment]
Good idea. As I've said before, blazemod - at least in the form it is nwo - is one of those mods that mesh very well with the base game, introducing content - some of which is now taken for granted by big part of the playerbase - but not significantly altering the balance (at least not till later parts of the game) or clashing with the gameplay and atmosphere of the base.

I support moving of blob, diamond and vortex parts somewhere. Doesn't necessarily fit well with crazy cataclysm though - those features are not paticularly wacky and crazy, merely a bit over the top advanced - but rather make it a small mod on its own. Solar panels should stay. Their stats may need rebalancing as certainly more than just several basic panels should be necessary to keep a decent vehicle or a base powered - but the basic idea is solid in my opinion.

**Comment by Night-Pryanik** [comment]
Blob, diamond and vortex parts don't need to be moved somewhere. After we move all the things we need from the mod to vanilla, the aforementioned parts will stay in the mod. Perhaps it could be renamed, but that's minor.

I'm heavily against adding tanks to the vanilla (at least in its current state treads = wheels), as I find it very unlikely that an average Survivor Joe could sit and drive tanks, even if he has huge driving practice (on conventional vehicles). Treads mechanics should be very different from wheels mechanics, and this must be considered prior to allowing driving tanks. Not to tell firing from a tank gun in all its complexity. Maybe require some sort of tank-operating education.

**Comment by mlangsdorf** [comment]
I mentioned I want to fix treads in step IC. My plan for treads is approximately:
1. define new flags, CONTINUOUS_TRACK and TRACK_SPROCKET
2. define a new vehiclepart "road_wheel" (or something) with TRACK_SPROCKET. Adjacent groups of road_wheels are one axle for installation difficulty. Roadwheels themselves are moderately heavy, narrow wheels.
3. define 1 or more new vehicleparts "continuous_tread" with CONTINUOUS_TRACK. CONTINUOUS_TRACK parts have to be installed on TRACK_SPROCKET parts, and fall off if the vehicle moves while there are CONTINUOUS_TRACK parts on some but not all of a TRACK_SPROCKET group. CONTINUOUS_TRACK parts are going to be wide, long, heavy, have huge surface area, etc. Hopefully they'll also be able to turn in place without moving (not all caterpillar track vehicles can do that, but everyone seems to expect it, so fine).
4. Define some vehicles with road_wheels and continuous_tread parts - construction bulldozers, heavy farm tractors, snowmobiles, etc are obvious civilian applications of treads. 

Getting all that working is prerequisite for merging blazemod and Tanks.

I don't insist that IFVs and MBTs go into mainline, and even if they do, I would create a disable mod that was part of the default mod list.

**Comment by Night-Pryanik** [comment]
> I would create a disable mod that was part of the default mod list.

This is a bad practice. We already have one default mod that disables something (`Simplified Nutrition`), and that's exactly one more than there should be in our default mod list.

**Comment by FulcrumA** [comment]
@Night-Pryanik 
>I'm heavily against adding tanks to the vanilla (at least in its current state treads = wheels), as I find it very unlikely that an average Survivor Joe could sit and drive tanks, even if he has huge driving practice (on conventional vehicles).

I'd be kinda sad to have the tanks and other such military hardware disabled, though I certainly understand rationale of average character not being familiarized with it. At the same, having a family who served in military and dealt with tanks (more in commanding role than as actual personnel, but he did have training and did rode some) I know that tanks are only somewhat more complicated in basic functionality than the average car. They may be less comfortable, the controls may be somewhat differently shaped (like something looking more like bicycle handles than a steering wheel, for example and a steering itself achieved often by a set of two levers/sticks setting treads independently to various speeds) and located in slightly different places but many regular car's basic control element has some equivalent - often similar - in tank's controls. Some may be slightly misleading in location - depending on the model it may turn out, for example, that both the turning and the acceleration is done only by using some sticks on the side or by pulling/pushing aforementioned levers, while all the pedals are for breaking (or the other way around!) - but it can be figured out.

The real problem comes in limited field of vision and crapload of additional, controls, gauges and indicators for various systems normal car doesn't have (you don't have any hatch you swivel into place and then secure with some other lever - though I guess neither you have in game to avoid necessity of implementationg of z-level boarding). But I reckon a proficient driver with some intelligence and a disregard for environment as they figure things out (which is a common theme in the CDDA world) could figure out at least roughly how to move the thing, with relatively low chance of something breaking the vehicle in the process (after all, for all their faults, tanks are made to last). Also, a lot of the problems with the field of vision are kinda alleviated by a set of cameras.

>Treads mechanics should be very different from wheels mechanics, and this must be considered prior to allowing driving tanks.
Sure it can be different, stuff like turning in spot is not possible with majority of cars. But such kind of things do not also mean that basic vehicle functionality - moving forward and turning - is somehow much more difficult in tanks. You usually just pull/push relevant lever/stick. Ignition may be a button rather than ust a key-turn. Things like turning may be achieved differently mechanically (threads operating with different speeds to make the vehicle turn rather than turning the wheels) but from the standpoint of the person driving it, it's still just "press/pull/push/turn this". Messing things up won't easily lead to some horrible consequences either - unlike how it'd be, for example, with a plane or even an average car - if you lose control of a tank and are nowhere the tank could get buried or fall of, you're more likely to be a danger to your environment than to the vehicle.

There are differences, but they certainly aren't harder to figure out than things average survivor does, especially when it comes to autolearned recipes which can be figured out by knowing principles behind them (though IRL they'd also require high intelligence and inventiveness in applying those principles while figuting out potential pitfalls and issues) or actually learning to drive a car - a person with 0 skill in driving would have MUCH harder time figuring out how to move a regular car than an average driver to control a tank - and wouldn't find it much easier than learning how to drive a tank from the scratch.

I wouldn't mind balancing things, like forcing the player to read a certain manual or otherwise possess a certain driving skill level to be able to drive a tank. I wouldn't mind tanks being less responsive, turn slower at higher speeds and other such balancing gimmicks (even if they wouldn't be necessary realistic) to simulate lack of skill. But taking them out on the basis of their difference toward commonly used hardware is going a bit too far.

**Comment by kevingranade** [comment]
I'm extremely sceptical that a tank is so difficult to drive that a survivor wouldn't be able to figure it out simply given time.  Will they be an expert at it and use it to its fullest potential? Certainly not.  Maybe they even need some amount of time to even figure out the controls and get it moving, but barring them from the game because they're hard to drive seems a bit extreme.

Issues I *am* concerned about re: tanks
Spawn frequency should be extremely small compared to ordinary vehicles.
Fuel expenditure should be high.
Space in a fighting vehicle should be cramped in comparison to most large vehicles (somewhat less so for APVs).
Armored vehicles should probably be adjusted to prevent casual modification, they're an amazing find, but you cant exactly do extensive frame mods without some extrordinarally heavy tools, and even if you can mod it, the result is going to experience degraded performance since the  armor will have been compromised.
Likewise you cant exactly swap parts from an ordinary car into a tank.

One issue I'm not sure of, what kind of features do these vehicles have to prevent theft?  If one is locked up, is it at all feasible to get in?  If so, can you start it, or is that secured somehow?  I smell a questline.

**Comment by FulcrumA** [comment]
@Night-Pryanik 
In that I fully agree.

On unrelated note, since we are talking about adjusting blazemod which is popular for its expansion of solar power, maybe it'd be a good opportunity to rebalance that? Currently solars are simply too attractive and efficient - not only the basic ones give far too much power (even improved ones should merely provide as much as regular ones do now), they're too easy to repair (should probably require actual solar cells).

As per idea thrown around on discord, it'd be good if fewer devices use batteries and it'd be harder to go clean energy efficiently without some scavenging and jury-rigging involved but instead use of fuel based generators (basically, engine, alternator and some fluff cable part that would power regular devices in its vicinity) would be more commonspread.

**Comment by cainiaowu** [comment]
Those overpowered solar panel fit quite nicely in the Bright Night settings though, at least keep unnerfed one in there.

**Comment by mlangsdorf** [comment]
My understanding is that the primary theft deterrent device of a AFV is that is surrounded by hundreds of people with guns and a license to shoot trespassers. Many of them don't have keys, because the military doesn't want to keep track of keys, and you can just start the engine if you can get inside the vehicle.

**Comment by mlangsdorf** [comment]
So in the process of tracing through vehicle power consumption, I've come to the realization that the in-game stats for electric motors give them 700% to 300% efficiency. Nerfing electric vehicles is as easy as giving them realistic efficiencies in the 90-95% range and increasing their epower draw by x3 to x7.

Solar panels are still going to be viable for stationary craft rigs, but I don't think that's unreasonable.

**Comment by lcy03406** [comment]
blob and tank both require a new game concept: vehicle parts compatibility.

+ The main cannon for a tank cannot be installed on a pickup. Maybe implemented as two kinds of turret mounts.
+ Normal control system cannot work in a tank. And a tank control has a very high skill check.
+ Any blob part cannot live in a metal vehicle.
+ Only blob weapons can connect to a blob vehicle.

These restrictions make sense in game. And the primary benefit is that balancing between different gene of vehicles will be easier. You only need to balance vehicle to vehicle, not part to part.

**Comment by lcy03406** [comment]
@mlangsdorf simply increasing their epower draw won't nerf electric vehicles much. I always prefer solar panel plant and exchangeable batteries over massive diesel farms. Once built up, solar panels need no maintaince. Take 8 times the effort to initiate the solar plant won't change my mind.

**Comment by Zetsukaze** [comment]
>I'm heavily against adding tanks to the vanilla (at least in its current state treads = wheels), as I find it very unlikely that an average Survivor Joe could sit and drive tanks, even if he has huge driving practice (on conventional vehicles). Treads mechanics should be very different from wheels mechanics, and this must be considered prior to allowing driving tanks.

Vehicles on treads are actually easier to drive than conventional vehicles. (Trained to drive M113 and Terrex). Tread turning has no need for counter-steering, you only drive with two sticks. Pull one to brake that respective side of the tracks, pull both to stop, let go of both to go straight. (M113)

Wheeled vehicles (Terrex) however are more complicated, where there is no automatic counter-steering, so you have to manually turn the steering wheel back in order to straighten out from a turn. If you go around the bend too fast, you can make the turn, but not straighten out in time. For the tracked vehicle, there isn't such an issue, just pull a stick, and let go once the turn is completed.

> firing from a tank gun in all its complexity. Maybe require some sort of tank-operating education.

The complicated bits about modern armour vehicles are the systems, from the camera displays to the weapons systems. There is a whole process you have to go through before you can unlock the weapon systems for fire, including loading the weapon automatically. That being said, conventional vehicles in CDDA can have mounted weapons and camera displays too, so unless there needs to be training for using all of such systems, both military and conventional vehicles are equal in this regard.

>My understanding is that the primary theft deterrent device of a AFV is that it is surrounded by hundreds of people with guns and a license to shoot trespassers. Many of them don't have keys, because the military doesn't want to keep track of keys, and you can just start the engine if you can get inside the vehicle.

There are keys, same as conventional vehicles. They start up the electrical systems of the vehicle. There are also locks on the hatches to disallow entry into the vehicle when parked, which are separate keys. So for every vehicle there is a loop of keys to accompany it, one for each hatch, and the main vehicle key for the electrical systems. The older one (M113) has keys for the hatches but no keys for the electrical system, so you can start the engine after turning it on.

**Comment by TechCatOther** [comment]
Solar panels need add some cost of maintained. For exapmle, new property is polluted. After every day add some pollution on panels and drop their power generation. When snow, wind or rain add more pollution. Also need to repair other solar panel. More damaged panels give less resources to repair.

**Comment by Night-Pryanik** [comment]
> After every day add some pollution on panels and drop their power generation.

A lot of players will consider everyday cleaning as a chore or a tedium and will be very against it.

**Comment by kevingranade** [comment]
Another way to put this is that if it is at all reasonable to assume that this routine maintenance happens automatically, that's what we should do.

**Comment by kevingranade** [comment]
Blazemod per se is totslly defunct, the approach listed here for adding treaded heavy vehicles is good, but the context really isn't, "absorb blazemod" anymore, and the issue is super stale.
