### ISSUE TITLE
Mod Inclusion Project: Arcana

### ISSUE THREAD

**Issue by DracoGriffin** [CleverRaven/Cataclysm-DDA#24733]
(Animatronics has been skipped based heavily on @Night-Pryanik's [comment](https://github.com/CleverRaven/Cataclysm-DDA/issues/24699#issuecomment-411429722) and some discussion on Discord)

Use the following issue as a space to discuss the inclusion of:

Mod Ident: Arcana
Name: Arcana and Magic Items

Your comment should include:

### Suggestions for induction
(what parts of the mod should be included, can be as simple as just an item, a location or the complete inclusion)

### Incompatibilities
(what parts of the mod should not be included, either some objects / items or entire mod is conflicting with DDA theme [ for whatever reason ])

**Comment by FulcrumA** [comment]
I kind of discussed that with you and others before. Even my comment in the Mod Inclusion Project's ticket would probably be a bit of an indicator.

I believe it's not a bad mod, but it's far too heroic fantasy for my taste. I certainly hope its creator will keep working on it as it brought quite fun to some people but I don't think making it vanilla, even with limitations would be good. Certainly many things could be improved, and it's remarkable how much the author was able to do despite being forced to include workarounds due to inability to actually change the basic game's code but even without those limitations, the direction the mod is taking and its approach to many themes, while fun, clash with base game's atmosphere in many ways.

Thus, to sum up yet again - good as a mod, not as an addition to the base game.

**Comment by ymber** [comment]
I also think arcana isn't appropriate for mainline. It's a major thematic leap from anything currently in the game and I don't think introducing something like that would be an improvement.

**Comment by DracoGriffin** [comment]
I'd like to really stress this part of the opening message and project goal:
>(what parts of the mod should be included, can be as **simple as just an item**, a **location** or the complete inclusion)

I'd suggest reviewing how @mlangsdorf broke down #24730. He has already made a goal to work at induction, whereas the issues I'll be opening are predominantly discussing aspects of mods that can be included (from a feasible tool or new item, to a location that could potentially be brought in and revamped to suit an end-game location or variant to something else, new professions or scenarios that might be appropriate).

So wholesale reviews of a mod aren't entirely productive (unless it's basically "the whole mod should be included") but I appreciate the time to give some thought on the practicality as a whole for Arcana mod.

**Comment by cainiaowu** [comment]
Well IIRC the original author @chaosvolt was banned from this repo and he cant comment on this thread at all (And stays salty at the Bay12 forum).

**Comment by Maddremor** [comment]
Also note that @chaosvolt is still developing Arcana on a separate [repo](https://github.com/chaosvolt/cdda-arcana-mod). That one has features that the legacy mainline one lacks.

**Comment by Night-Pryanik** [comment]
Arcana is being developed in its own repo, so there is no reason for keeping the heavily outdated version in our mods list.
I don't think there is some item or monster or whatever in the mod that could be mainlined.

**Comment by DracoGriffin** [comment]
@cainiaowu I appreciate the information, but I don't feel it's relevant to dredge up the past.

>Would it be fine if I get the mod author’s opinion on the matter?

I had originally intended to seek out author approval, but some consideration, discussion and reviewing authors of mods, it could be quite difficult in being able to successfully reach out to each other. Especially when everything is essentially open source, so it becomes somewhat of a moot point.

So yes, if people know a way to contact the author, then it's potentially much easier to inform them of the discussion to including the mod (parts or all).

---

On review of Arcana mod, I can't find anything particularly that would fit thematically, other than the possibility of cultist activities (less actual magic, and way more just kooky and crazy worshipping of nether creatures or whatever), but that's somewhat already established by the [prisoner's quest](https://github.com/CleverRaven/Cataclysm-DDA/blob/2114e2291b2abab9aef2b0fd03e184094defff87/data/json/npcs/missiondef.json#L461) ([Church of Starry Wisdom](https://github.com/CleverRaven/Cataclysm-DDA/search?q=starry+wisdom&unscoped_q=starry+wisdom)) and some of the established lore, so nothing unique.

Another day for more feedback before moving onto the next mod.

**Comment by FulcrumA** [comment]
Yeah, the more 'dark & culty' occultism and magic is fine on its own but like you've mentioned, that's kinda already covered and there's no point in redundancy, at least at this point where there's no real occult features to back it up (and given that Arcana's take on those - at least as little as I've seen of it - doesn't really mesh that well).

**Comment by Noctifer-de-Mortem** [comment]
Words from the mod author: 

My own thoughts on it:
`Sadly there are some technical issues with doing so. There was a time when I was maintaining the mod separately while an out-of-date version remained in the repo, fixing bugs and adding new content. For one the launcher (already something that can be finicky about third-party mods in my experience) did not like there being two versions of the mod.

The other issue is that I fully intend to keep fleshing things out and improving the mod as I am able to, in general trying to make things less clunky and occasionally adding new content if it seems like it'd add to the mod. I won't have that option if it's brought over into the base game again,  and if I kept updating it in my own repo I would have to rely on other people to keep the versions in sync.

Part of what led to arcana being marked as obsolete was due to bugs cropping up and no one being available to fix them. As by then I started maintaining my own repo, and due to arguments between Mugling and I (plus argument occurring in related issues, remember this was during the "too many issues, we're recruiting more devs to help" period) it was decided that just obsoleting the mod would be better. Didn't fix all the problems though (old saves that didn't use my version would have load errors, the launcher would replace the third-party version with the obsolete one, etc), so eventually the old version was deleted outright.`

**Comment by Human-Shield** [comment]
I think their should be a new skill of "Super Science" "Weird Science" or "Quantum Physics" that covers portals, artifacts, cult stuff, and Nether things. In which spells are just uses of Nether physics and artifacts. So advanced books from labs, ancient rare mansion books, or stone tablets at the bottom of mines to read. 

So no magic shops, potions, or magic swords but limited spells and crafting options around artifacts and other weird objects.

**Comment by FulcrumA** [comment]
I am not really fond of that. I don't mind actual cults, studies on nether etc but I remember talking about it with Kevin - having a bit of cience stuff, basic analysis of various materials, even perhaps pseudo-quests where you have to acquire certain body parts, corpses etc of various nether creatures and study them for understanding of certain matter may be (far-away) goal but actual "super science" usually requires either a team of professionals due to sheer work involved or lifelong commitment to sitting in the laboratory to acquire a lot of the necessary knowledge and results.

Also, as stated above, I don't mind some occultism, but it has to be subtle and, well, occult, esoteric - something alien and not easy to study to any sufficient degree nor even recognize as such. Changing a few descriptions, names of skills and items around won't cut it for me at all.

Again, I don't think Arcana is a bad mod. It does well-enough, given it's limitations, to provide interesting content. It's taking it into a fresh, new direction, presents interesting ideas and while I don't know author personally - I also talked with him recently on discord and I know he does have many of such ideas in general. The problem is, I don't see that particular direction meshing well with CDDA, without solid rewrite and butchering of nearly anything that could be included to the benefit of the game - and at such point, it could as well be coded properly from scratch.

**Comment by DracoGriffin** [comment]
>I think their should be a new skill of "Super Science" "Weird Science" or "Quantum Physics" that covers portals, artifacts, cult stuff, and Nether things. In which spells are just uses of Nether physics and artifacts. So advanced books from labs, ancient rare mansion books, or stone tablets at the bottom of mines to read.

As @FulcrumA touches on, this is actually a possibility for potential NPCs if you were to find or recruit them, that there could be an extensive quest line (potentially taking place over several years, research isn't as quick as movies make them out to be) into researching some of this, however it seems quite obtuse of a topic that hasn't been nearly fleshed out more than just a simple idea. If you were interested in working something up along those lines, please feel free to open a separate Issue with some storylines with timeframes and maybe some sample text and what potential rewards could be.

---

Thanks everyone for your input. This will now be closed for discussion to move onto the next mod.
