### ISSUE TITLE
Mod Inclusion Project: Bionics Systems

### ISSUE THREAD

**Issue by DracoGriffin** [CleverRaven/Cataclysm-DDA#24780]
Use the following issue as a space to discuss the inclusion of:

Mod Ident: bio_mod
Name: Bionics Systems Mod

Your comment should include:

### Suggestions for induction
(what parts of the mod should be included, can be as simple as just an item, a location or the complete inclusion)

### Incompatibilities
(what parts of the mod should not be included, either some objects / items or entire mod is conflicting with DDA theme [ for whatever reason ])

---

edit:

Based upon feedback, Bionics Systems mod seems like a good fit. Therefore,

- [ ] - Add advanced form of Directional EMP CBM with the EMP Projectors
- [ ] - Add Autonomous Surgical Razors CBM as butchery equivalent to Integrated Toolset (potentially exclusive to Bionic Surgeon professions or other profession, could also be lab book-gated [like most serums])
- [ ] - Add Ionic Overload Generator CBM to Crazy Cataclysm OR to core but needs extreme balance/tuning
- [ ] - Add Bionic Surgeon profession with some tuning

All the aforementioned are based on suggestions in thread and not necessarily written in stone, but for any contributors that would like to induct the mod in, these are the suggestions to keep in mind at least.

**Comment by Night-Pryanik** [comment]
Bionics, CBMs and profession added in this mod seem to fit nicely in the Cata theme. But I don't know how well balanced they are. If they are not imbalanced, the entire mod could be added to the vanilla.

**Comment by Nymall** [comment]
All the CBMs are great - As for professions, there is only one, and that's the Bionic Surgeon(Who starts with implanted surgical razors). As for balance, the cost could easily be rejiggered - presently, the Ion Cannon is about on par with where explosives are presently at(Truth be told though, has been a while since I last used one).

**Comment by Noctifer-de-Mortem** [comment]
As I commented in #21583 , the PR to add said mod, if there is interest in mainlining it then that's neat. I would say some re-balancing would be warranted but on that department I am of not much help. The mod itself was meant as a way to add Bionics to test them out but that seems to be what Bright Nights is being used for anyways.

Here are my thoughts on it's contents for mainline.

It seems the EMP Projectors are the most requested thing to be added to mainline and I agree; I added them since the Vanilla EMP Bionic is a bit useless. However, I am not sure it should be mainlined as is, as a replacement of the Vanilla EMP bionic or what other options might be available.

Autonomous Surgical Razors are meant to always have something to harvest from corpses, bionics included. Since this bionic would be better at it than any other item you would only need the skills set to do a proper butcher job. That being said, it being the best item to butcher in, I would not be surprised if it's installation is revisited as a core bionic.

The Ionic Overload Generator is the most exaggerated bionic here. It's a very gimmicky weapon with the closest thing to compare being the blast cannon. However, I decided to go for it using chest slots for the reason of the future implementation of the bionics slot system. This would make it so you would sacrifice precious slots in your chest for a powerful weapon. 

The Bionic Surgeon Profession seems fine as is in my opinion. Maybe nerfing the items it carries might be warranted but the cost for what you are getting seems fair to me. What you are getting won't help you to survive early game as it's more of an investment into a medically themed char.

**Comment by Nymall** [comment]
For balancing, the only thing I can suggest is to increase the power cost of the Ionic Overload generator. I've tinkered a bit with it since last night, and it only costs 500 energy per shot, which has a massive destructive power(seems to be about 15 tile radius). It's next to impossible to control where it hits, but at 500 you could get 4+ hits off fairly easy with 8 good Shocker Hulk butchers. I suggest increasing the cost per use up to 750, so that even with the new bionics change it's harder to become "destroyer of worlds".

Also, as a note, it lights stuff on fire. My test city is ablaze. :p

**Comment by DracoGriffin** [comment]
I have to agree with some of Noctifer's points but I'd re-evaluate the EMP Projector as an advanced version of Directional EMP, perhaps even requiring that CBM in order to craft it from a lab journal.

The razors could be an unique CBM to the Bionic Surgeon Profession that additionally has the new AutoDoc trait from Augmentation Associate, [Autodoc Specialist](https://github.com/CleverRaven/Cataclysm-DDA/blob/fe7d11d596be92821995d5cadb412dc0123b5737/data/json/mutations.json#L5188) and increase the cost to 8.

I believe the Ionic Generator CBM would be better suited for Crazy Cataclysm, as the other similar CBM is the Fusion Blaster which removes an arm, whereas there is no downside for Ionic Generator (until a ton that CBM slots becomes a thing or some other system overhauling). Plus, a giant laser beam cannon from your chest invokes anime and screams silliness, to me.

With all that said, they would definitely need to be fine-tuned for induction, but they seem to be a great starting point.

---

Another day for more feedback before moving onto the next mod.

**Comment by FulcrumA** [comment]
I agree with @Night-Pryanik - thematically, the mod fits very well. However the blades are surprisingly powerful melee weapon and with unarmed martial arts quite ridiculous. I do believe they could be added after some rebalance and they indeed should be like an inbuilt butchering knife. In general, I'd make them far less beneficial in combat (just a tiny bit of additional cut damage) and more useful as an actual utility item (butchering item or even in general inbuilt cutting/fine cutting tool, possibly a scalpel equivalent in future medical procedures on NPCs if such will happen).

I am fine with leaving vanilla EMP and keeping generator CBM out of it, for the same reasons @DracoGriffin mentions. A bit of animeish Rule of Cool doesn't bother me, but this one is going a bit too far.

**Comment by Noctifer-de-Mortem** [comment]
I could go ahead and work on a PR to move this mod's content to mainline; I just need a few things clarified so I can do so:

-For making the EMP projector an upgrade of the Directional EMP would I just need to set the `"upgraded_bionic"` to point to the Directional EMP in the bionic.json definitions?

It says in the description of OP to add Surgical Razors like the integrated tool set. Does that mean change it from an item you wield to use like the bionic claws and instead make it an "invisible" bionic item like the toolset?

-I will go ahead and swallow up the Ion Overload Generator to the mod Cataclysm++ where I can use it for some plans if that is ok.

-For the professions, change cost to 8 and add the Autodoc specialist? This professions is meant to be a normal general surgeon and not a bionic one so am not sure the trait is warranted.

-The Surgical Razors and EMP projector should be lab drops and projector maybe a military drop as well.

-Also, can someone give me some pointers on removing folders and it's contents on the web version of github?

**Comment by cainiaowu** [comment]
You should not remove the mod folder, it will break saves.

Mark them obsolete instead.

**Comment by cainiaowu** [comment]
I dont think you can remove file via web interface, I had to clone the whole repo(1.5GB size) to remove PK and arcane mod from mainline.
