### ISSUE TITLE
Power armor overhaul suggestion.

### ISSUE THREAD

**Issue by The-Scout** [CleverRaven/Cataclysm-DDA#24790]
The way i see it power armor right now is pretty uninteresting. Power armor should be changed to a more modular system akin to vehicles. Stuff like storage slots, plating, servos, ect. These components should be found in the bottom of labs that have the current power armor room.  You should be able to install curtain bionics should be able to be implanted in the power armor. I also suggest power armor should be more rare, only to be found in labs and bunkers no longer can you find them in a random spider basement.

**Comment by kevingranade** [comment]
A model I really like based on FO4 power armor.

Power armor core - this is the part the player actually climbs inside.  Its uncraftable, unmodifiable, and unrepairable.  It includes structural elements, motors, a HUD if any and controls. Includes helmet, but the helmet armor is modular, just like the rest of the parts.  You can walk around in just this and a power plant, but it'd be a bad idea because it's not heavily armored. It has attachment points for other PA components, like armor plating, weapons, carrying frame, power plant, etc.  Certain qualities must be included in the frame, like environmental protection, climate control, targeting systems, carrying capacity (weight).  Up in the air is what the player can wear while in power armor.  I'm leaning toward brutal simplification of "nothing", that means one simple rule prevents having to handle stacking power armor with regular armor, requires the player to drop inventory before entering power armor, and makes exploits where the player enters and exits the power armor during combat more difficult.

A power plant is the one core part of the armor other than the frame needed to operate it.  The power plant can have different capacities, which determines how long you can operate the power armor without recharging (or refueling depending on the type) and different power output, which determines what features can be used.  Low power output means certain features may be unusable. In an extreme situation like a small survivor-crafted generator, the power plant may only allow the armor to walk but not fight, even when unloaded. High power output means many or all features are usable simultaneously, possibly including energy weapons or other exotic features similar to CBMs.  For full use of features, i.e. fast movement and melee combat while full armor plating is equipped, pre-catacltsm power systems should be required.

Armor plates with various weight/toughness can be attached to the frame.  Certain levels of these can be crafted by the player as it just requires following a template and attaching to mount points. Pre-cataclysm armor plates may have better armor to weight ratios, or special features like reactive plating cells. Helmet armor requires special consideration, it either needs viewports, limiting coverage, or externally mounted cameras, which would be a point of failure. Pre-cataclysm helmet armor could include armored cameras with a similar level of toughness to the rest of the armor.  Heavy armor will drive up motor load, increasing power requirements for movement, possibly preventing certain kinds of movement if the power plant or the frame arent up to it.

Weapons, either melee or ranged can be attached to armor mount points, which are not limited to arm mount points.  The survivor should be able to rig most melee weapons to an arm, and attach most ordinary firearms, but the accuracy may be limited, and any onboarding firing systens would be unusable.  Advanced PA-specific weapons would have integrations with onboard targeting systems and/or autonomous firing modes.  Some non-main-weapon mounts would still be usable as a secondary weapon, e.g. a launcher firing a frag grenade straight up 10' before detonation.  Non-adapted weapons should not generally be usable.  Power armor with human-sized hands is going to have extremely poor armor, and digits large enough to have substantial armor are going to be unable to operate human-sized weaponry.

Specialized mount points, such as cameras for view modes, reinforced mount points for jump jets, extra ammo, etc can be added.

**Comment by Human-Shield** [comment]
It would be great to see power armor get some love. I would say expand its availability for low grade versions. 

Japan is working on exoskeletons for seniors and the military already has powered leg devices that allow troops to carry more weight and fast detach them if they need to sprint. 

The most basic version could be found in senior homes or hospitals and wouldn't have a helmet; it might run off a small swappable battery and just allow walking with more cargo but prevent sprinting (dodge penalty?). Then a smart survivor could start welding stuff to it and working on increasing servo power.

**Comment by kevingranade** [comment]
> Japan is working on exoskeletons for seniors and the military already has powered leg devices that allow troops to carry more weight and fast detach them if they need to sprint.

I dont have anything against a weight-carrying device like this, but it is not the same thing, and it can't become the same thing, because this:
> Then a smart survivor could start welding stuff to it and working on increasing servo power.

Is explicitly out of scope for the game.

**Comment by Night-Pryanik** [comment]
No discussion in over half a year, closing.
