### ISSUE TITLE
Allow electronics management from top-level vehicle menu

### ISSUE THREAD

**Issue by FulcrumA** [CleverRaven/Cataclysm-DDA#24802]
Game version: 0.C-30348

Operating system: Win7

Tiles or curses: Tiles

Mods active: More Survival Tools, Stats Through Skill, Vehicle Additions Pack, Tanks and Other Vehicles, Boats, Icecoon's Arsenal, Filthy Clothing, Makeshift Items Mod, More Buildings, No Flaming Weapons, Disable NPC Needs, No Antique Firearms, No Fictional Guns, NPC Traits, Extended Realistic Guns.

A small quality of life issue. Currently any management of electronic devices in a vehicle requires one to first enter relevant menu and then turn on/off required device. Previous versions, where all electronic devices and their state were immediately available upon interaction with the vehicle worked just fine without requiring one to enter any submenus. Now, if one often turns on/off devices, there's plenty of additional keystrokes for hardly any benefit as even pretty huge, loaded with electronics vehicles should be relatively easily contained in said menu given how much space an average screen offers.

Ticket mostly in reference to stationary installation one doesn't drive around as an actual vehicle (base workstations and similar) where one cannot activate electronics without either choosing "control vehicle" or "control multiple electronics first".

**Comment by mlangsdorf** [comment]
So if you examine a vehicle at a tile with electronics controls, you get the examination menu:
![examinecontrols](https://user-images.githubusercontent.com/8007405/44005184-dcb7c3f4-9e34-11e8-8cea-9b1c03080d67.png)
If you control the vehicle in an adjacent tile (^ followed by an arrow key) you go straight to the electronics control menu
![controlvehicle](https://user-images.githubusercontent.com/8007405/44005195-f99c7820-9e34-11e8-81da-9ace41c149b1.png)

I am reluctant to make all the electronics control options available straight from the examine menu at this time, because that code path is already kind of a mess and I don't want to add more mess.
