### ISSUE TITLE
Mod Inclusion Project: Boats

### ISSUE THREAD

**Issue by DracoGriffin** [CleverRaven/Cataclysm-DDA#24864]
Use the following issue as a space to discuss the inclusion of:

Mod Ident: boats
Name: Boats

Your comment should include:

### Suggestions for induction
(what parts of the mod should be included, can be as simple as just an item, a location or the complete inclusion)

### Incompatibilities
(what parts of the mod should not be included, either some objects / items or entire mod is conflicting with DDA theme [ for whatever reason ])

**Comment by Rod995** [comment]
All the boats.
~~mod works fine right now~~
~~Once it's mainlined, we could add more support for it, like amphibious vehicles.~~

**Comment by FulcrumA** [comment]
Inclusion of boats would be do, but it should be done in a less hacky way than adding special type of wheels to the boat. Possibly should also include ways to add amphibious vehicles without the need to modify them every time since I bet you people will ask for that.

**Comment by Lorith** [comment]
That is something that would require a redo of the vehicle code, which is currently ongoing already.  I would recommend including everything from the mod for now and fix the inability to do amphibious vehicles later.

**Comment by Lorith** [comment]
Good point, I had not thought of that, so it kinda depends on how the vehicle recoding is being done.

**Comment by mlangsdorf** [comment]
Serious use of boats requires:
1. Proper support of flotation, starting with not using hacked wheels to determine flotation, and including support for leaks and taking on water.
2. A rework of the collision rules, so that boats can push creatures in deep water out of the way, instead of hammering themselves to destruction just by moving.
3. Reworking bridges, such that every bridge isn't a roadblock to exploring by boat. The simple and lame version would be adding drawbridges. My preferred version would be support for vehicle z-level transitions.
4. Preferably an improved physics model for boats, that better calculates boat speed.

The current boat mod is adequate for rowboats used to explore sewers or cross rivers; it starts to fail when confronted with motor boats used to move along a river. Resolving Items 1 and 2 are the minimum preconditions before we should attempt to mainline boats.

**Comment by cake-pie** [comment]
What I would hope to see eventually in a serious implementation: at least simplified [hydrostatics](https://en.wikipedia.org/wiki/Naval_architecture#Hydrostatics), so the vessel may be considered listing at some angle depending on distribution of mass vs bouyancy.  This would affect performance -- leading to infeasible to operate beyond some threshold.

**Comment by DracoGriffin** [comment]
Honestly, @cake-pie and @mlangsdorf pretty much summed up my review and I don't believe Boats mod is adequate in any regard to be included (even in the future, at that point, there will be most likely entirely different specifications for water-related vehicles), especially considering the massive vehicle code overhauls that would be necessary to make it sufficient.

Additionally, I believe this issue at least can serve as an initial jump-off point with the ideas/points the aforementioned have both made in supporting water-based vehicles.

---

I think this is enough feedback to warrant closure and moving onto the next mod.

**Comment by mlangsdorf** [comment]
This issue is closed but starting progress on a better model for boats, see #27225

**Comment by mlangsdorf** [comment]
When #30519 is complete, I will look into mainlining Boats.
