### ISSUE TITLE
New butchery requirement is onerous.

### ISSUE THREAD

**Issue by jim-huynh** [CleverRaven/Cataclysm-DDA#24874]
Version: 0.c-30616-g5d18af2

You have to stand on top of your butcher's rack in order to do a full butcher.  To remain consistent with other crafting equipment, it should allow the same range leeway.

Also, it seems outlandish to me that you cannot get the skin, bones, and viscera from an animal without modern equipment like a butcher's rack and a table.  Our nomadic tribal ancestors would not have had any clothing if this were the case.

Maybe a full butcher would take longer without the equipment, but barring it all together sounds unreasonable.

**Comment by AbsalomAchitophel526** [comment]
You're forgetting you also need a full butcher for feathers and fat.  You can technically get a few bones (I've never gotten more than 1 with survival 5 from a deer) bones from large creatures with field dressing it first.

In any case, this change makes total woodland survival nearly impossible - you cannot make a table without nails and 2x4's, which you can only loot or make with advanced metallurgy equipment.  This is REQUIRED for feathers, fat, skin etc.

Even then, dragging every single coyote wolf deer etc corpse just to get fat and skins all the way back to your shack greatly ratchets up sheer tedium.  The increased meat yields (And when debug tested, the increased yields apply only to meat - not to any other animal byproducts) are meaningless to a lone survivor.

I get that there is a (metal) foldable version, but if you are going to scrum towns for rare loot, why not just stay there

**Comment by jim-huynh** [comment]
I am somewhat fine with the tedium of dragging a corpse back to base, but there really should be a travois-like container craftable without metals, for the woodland survivor.

The travois would be draggable, with enough container space for a deer sized corpse.  Maybe buildable like the other container furniture.


Maybe full butcher without the equipment would take more time and with more skill.

**Comment by svick** [comment]
> In any case, this change makes total woodland survival nearly impossible

See https://github.com/CleverRaven/Cataclysm-DDA/issues/24878.

**Comment by FulcrumA** [comment]
I have to agree. Full butchering should merely benefit from racks and other specialized equipment which could help provide better yield and decrease time spent butchering considerably - but they should be optional.

**Comment by puyebu** [comment]
I have checked the new requirements. 
It seems very tedious now to do the butchering for componenents. I like the change overall but rack requirement seems rather annoying.
It should be possible to gather skin/feathers/et cetera without any butchering racks even at reduced odds and consuming more time than with the equipment.
For example, Open Skinning technique does not require any stands and while Case Skinning technique benefits from racks, any tree or something to hang the carcass can be used rather than some specialized stand.
At worst, trees, big rocks, fences and other similar structures combined with a rope or a hook should be allowed to be used as improvised racks.

**Comment by nexusmrsep** [comment]
Obsolete after changes listed in #24878. If something from here still needs to be addressed you can do it at that PR too to avoid duplicates.
