### ISSUE TITLE
items getting frozen within 5 minutes in a building when only im chilly

### ISSUE THREAD

**Issue by stk2008** [CleverRaven/Cataclysm-DDA#24914]
**Describe the bug**  
bottle of water is getting frozen within 5 mins of me boiling it to HOT

**Expected behavior**  
based on ambient temp it should take longer than this

**Screenshots**  
https://cdn.discordapp.com/attachments/252368987210514433/480120663252664322/unknown.png

https://cdn.discordapp.com/attachments/252368987210514433/480120837723258910/unknown.png

https://cdn.discordapp.com/attachments/252368987210514433/480121077130067989/unknown.png

sorry I know this PR is killing you mate.

**Comment by stk2008** [comment]
yeah definatly needs to take player temp into consideration.

I know its not 100% accurate to do that but I wasent wearing much so wasent getting much from my clothing so for me to be chilly and the bottle of water to get cold within 5 minutes is very odd.

Might test with me being naked actually compare my body temp then to the bottle of water.

I know this is not an accurate way to do it but im sure ya get my train of thought here.

If I am naked and only chilly there is NO WAY water can be much much colder and freeze within 5 minutes.

Any way thanks for your hard work mate I am sure you will get there in the end :)

**Comment by nexusmrsep** [comment]
Thanks for posting this issue. I also think that time of temperature changes is too fast, and I have few suspicions where it originates from. I will work on this problem soon.

**Comment by stk2008** [comment]
Thank you and dont get put off with this mate we do appriciate every thing your doing we have faith in ya although we are having a rather good giggle at your expense :P

**Comment by Chezzo** [comment]
People on IRC are reporting that frozen things can be heated with the % menu until hot, but stay frozen. Also they unfreeze into your inventory, so you are unable to consume them. Haven't tested personally, however.

**Comment by stk2008** [comment]
Damn just had a thought there is thermometers in the game I shall do some testing later and get exact ambient temp and get some real numbers going.

**Comment by stk2008** [comment]
ok i have on me frozen water note the time and temp etc

https://i.imgur.com/scfo2QW.jpg

boiled water

https://i.imgur.com/wQr9fyB.jpg

skipped time 10 mins and its now frozen again

https://i.imgur.com/9dXN4PD.jpg

and temp is -4

https://i.imgur.com/V2WyzJT.jpg

maye have froze before that but could only skip time 5 mins at a time and did not do it at 5mins so had to skip again.

Ok -4 is bloody cold but would water freeze that fast at -4? after just been boiled?.

**Comment by FantasticFwoosh** [comment]
Different things have different properties, if boiling & freezing temperatures minimum could be enforced, then besides from the worst onset of weather water freezing may yet be more uncommon.

* Some tools such as meat temperature probes & said thermometer's being inserted into food to get a reading of their exact relevant temperature would be useful in that regard to see how much time you have left before they freeze.

Additionally addressed in #25061 that the more water you gather in a container such as a 3L glass bottle or a jerrycan the longer it will take to thaw out similar to food if you decide to dethaw the lot (maybe for crafting purposes needing unfrozen water) rather than craft clean water.
