### ISSUE TITLE
Traning First aid 1 without books is tedious.

### ISSUE THREAD

**Issue by Treah** [CleverRaven/Cataclysm-DDA#24912]
The only real way to train this skill without books is to make bandages ( which dont train the skill ) and apply them one by one. Each application is 1% so it takes 100 bandages and 100 applications of said bandages to a hurt part before you scan skill up to 1. 1 is needed to heal broken limbs since they wont mend without a splint. 

This could be remedied by having making bandages skill use first aid instead of tailoring.

**Comment by alanbrady** [comment]
Seems reasonable to me.

**Comment by CoroNaut** [comment]
What about both :rofl:

**Comment by Night-Pryanik** [comment]
> This could be remedied by having making bandages skill use first aid instead of tailoring.

Proper (not makeshift) bandages already use first aid skill for crafting. Crafting makeshift bandages from rags training first aid skill make no sense. Also I can't imagine how soaking makeshift bandages in bleach or boil them in water should train first aid either.

Maybe we should just raise the amount of percentile increased on each application from 1% to 10%, so it would require just 10 applications of bandages to achieve the first level of first aid.

**Comment by Treah** [comment]
Proper bandages require skill of 1 so its the same problem. I like your suggestion tho to just increase the amount gained I can pr that.

**Comment by FeepingCreature** [comment]
@kevingranade Instead of trying pull requests blindly... should this bug be closed, or are there alternatives to get splints in wilderness starts that you'd consider?

**Comment by kevingranade** [comment]
No, no and maybe
It's not the bare concept of supporting a limb with a splint, it also includes setting the bone.  Is that first aid 0? Definitely not.

It's kind of silly that you think someone that's completely clueless about first aid would just "figure it out".  If anything the unrealistic thing is that bone setting and splinting is *only* first aid 1, and that you *can* learn it by making a bunch of bandages.

If you have an alternate way to train first aid from 0 to 1, I'm all ears, but making it even easier is counterproductive.

**Comment by FeepingCreature** [comment]
Yes, hence the failure chance.

But I'd been thinking about this some more and the problem here is really that there's no way for any of this to make sense under a model of "health from 100 to 0, then break." (As far as I can tell, I got the broken bones by spending too much time in the cold...) A broken bone is not a state of health 0, it's an affliction that prevents the use of your limbs. I think what should realistically happen is: the condition of broken bones should eventually transition to "badly healed bones", returning use of body parts but giving a random permanent max health malus that needs high medical knowledge to fix. You should be able to use splints to set bones at a low level, and have an (initially very low) chance of preventing this effect, a higher chance of reducing it, and a high chance of, instead of being applied, actually damaging you.

Does that make more sense?
