### ISSUE TITLE
Better presentation of information about fireplaces.

### ISSUE THREAD

**Issue by Androwski3000** [CleverRaven/Cataclysm-DDA#24977]
**Is your feature request related to a problem? Please describe.**  
Sometimes the fire gets out before the cooking is finished. Then the process stops, because lack of light. How does one know how long a 2-by-4, heavy stick, wood splinter, etc. burns?

Also in the description of the wood stove it´s says the wood stove is more efficient than an open fire. -The stone fire place is semy open, right?
So how much more efficient is the wood stove?

In the stone fireplace it says the fire is relaxing.
How much relaxation or /Joy /does the stone firepace give? 

How much is the efficiency difference there between the different woodfed fireplaces? Bracier, digged pit, wood stove, stone fireplace, etc.

There are some things which are not clear in the game.

**Describe the solution you'd like**  
All wood fed fireplaces could use a counter for how much units of "cooking" they have left in them. Like the survivor mess kit or gasoline cooker. Or would that be bad for the game?
As gasoline has very defined properties as a product, a counter on the cooker makes sense very much for the game.
Wood could be different piece by piece but I think it is not needed for the gameplay to give every piece of wood an RNG based fuel value.

So the cooking places could get different efficiency falues for using the energy value of the fuel which was put in.

Efficiency:
Wood stove > stone fireplace > fire pit > bracier ....
There are others like the charcoal cooker but I havent used everything in the game yet.

So butchering tools have a value for how good they are for that task, like butchering 22. Saws and other tools have their value in numbers also. How thinkable is it to introduce such a property for the fire places? Like "Fuel efficiency: 0,5"

**Comment by nexusmrsep** [comment]
They use a counter and to my belief it can be easily converted to usable information for the player. I support this idea. However I see one implementation risk - a fire in a fireplace is the same as wild fire on a building on fire, where you don't want to know the information about how much fuel it has.

**Comment by Androwski3000** [comment]
Ok. So there is a need for two different fires or another solution maybe. 

One "another" solution for the fire in a dugout hole could be no counter at all, as this fireplace is....so basic.

Is the counter you talk about already visible? I have to check that via X and then hover over.

**Comment by nexusmrsep** [comment]
Hidden but exists. Leave the rest for some eager contributor.

**Comment by Androwski3000** [comment]
Ok, cool. That´s the answer I wanted. :=D

**Comment by HeadWar** [comment]
Could be done with an 'e'xamine on the various fireplaces? So that they give an estimate of how much time the fire has left in it. That eliminates the problem with being able to tell how long a "wild" fire will last. Maybe increase the precision of the estimate with higher survival skill?

Skill 0: That's a big fire! / Looks like it'll burn for a bit longer. /That's definitely about to go out.
Skill 2: The fire will burn for several more hours. / The fire will go out in less than an hour. / The fire is going out within a few minutes.
Skill 5: The fire will burn for another 3 hours, 30 minutes, give or take.

(Also, if you construct a "firewood source" or whatever it is called, next to (near?) your fireplace, you will automatically pull firewood from that square and put on the fire, if the fire is about to go out while you are crafting or reading. Very handy. Doesn't take any resources or time, it's just a way to mark the square.)

**Comment by Treah** [comment]
@HeadWar  I actually really like this idea and is the most accurate to IRL skill with using a fire. A person who knows alot about survival and outdoor living is going to be able estimate how long a fire will last more then a person living in the city.
