### ISSUE TITLE
Triffid queens can remove stairs to their nest.

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#24995]
**Describe the bug**  
Triffid queens have the ability to change nature at their will, but also allows them to remove the entrance to the underground system they produce.

**To Reproduce**  
1. Find a triffid grove
2. Allow triffid queen to pass over top their nest.

**Expected behavior**  
I could imagine there are bushes over top the entrance, but when the triffid queen passes overhead, the underground entrance should not be covered with trees and inaccessible.

**Versions and configuration(please complete the following information):**
 - OS: Windows 7
 - Game Version 0.C-30421-gf615e24
 - Graphics version tiles
 - Mods loaded none

**Comment by tyrael93** [comment]
Due to old whalescode, since stairs and trees are both terrain, cutting the tree will leave an empty dirt square where your  stairs used to be, blocking the entrance to ( or escape in some cases) to a lower or upper level.
I personally use a personal mod/patch that among other things removes a queen's "treewake"because of how broken it is.
