### ISSUE TITLE
Items freezing so fast the game is almost unplayable.

### ISSUE THREAD

**Issue by WizardOfOoo** [CleverRaven/Cataclysm-DDA#25014]
I know that they are a WIP, but right now the game is almost unplayable after build 7700.

Could the freezing changes be rolled back and made a little less game breaking before they are put back into the code?

**Comment by MT-Arnoldussen** [comment]
while i agree the change wasn't tested adequately, "unplayable" is a bit melodramatic. even before the bugfixes that have already been merged it was an inconvenience at most.

**Comment by Xhuis** [comment]
I disagree @MT-Arnoldussen. Food would freeze quickly, and defrosting it was bugged. Thus, you physically had no way to eat a lot of foods during winter.

@WizardOfOoo Defrosting has been fixed, I believe, so try updating your game and it should give you less trouble.

**Comment by jniscior** [comment]
I see no reason to roll the changes back. Most critical issues have already been resolved by merged PR's. I've also been playtesting #24971 and although freezing of some items is still a tad too quick in my opinion - it makes the game entirely playable and enjoyable.

**Comment by nexusmrsep** [comment]
And after that there is PR #24956 in which hot air from fires and heat radiation can help to thaw food or keep it unfrozen.

**Comment by FantasticFwoosh** [comment]
Remove the incidental seasonal weather during spring such as the _hardcoded game-start flurries_ at the start of the player experience of the catacylsm if you could, because consistently low starting temperatures freeze objects, then a lack of improving weather keeps them there in that state dethawing naturally too slowly to return to normal or are mushy & spoilt as a unnessecary starting challenge.

Many such objects defreeze in the inventory anecdotally when temperatures actually rise for a window of time, it is warmer underground generally as rule also besides the hot air PR which seeks to raise the local temperature.

* This is besides the fact that many fire sources don't actually burn long enough to cook objects vs using the time left from the fire to re-heat them instead entirely dependent on the fuel you put in the engine being too inefficient despite working fine on a general fire. Ovens are particularly guilty for burning out too fast to use when you're dependent on guessing the correct fuel type.

**Comment by nexusmrsep** [comment]
#24977 has to be adressed to counter this inconvenience.
