### ISSUE TITLE
Cannibal recipes auto-learned

### ISSUE THREAD

**Issue by chaisawlajatang** [CleverRaven/Cataclysm-DDA#25038]
**Describe the bug**  
Even if you're not a cannibal, you always have the following recipes from the game start:
- nino nachos & nino nachos with cheese
- soylent green shake & soylent green drink
- boiled human stomach & boiled large human stomach
- rehydrated human flesh
- slob sandwich
- cooked creep

If you start with extra Cooking skills, all recipes with human flesh with that skill level needed are unlocked.

**To Reproduce**  
1. Start a new game with or without Cooking skill.
2. Go to FOOD category.
3. Look at cannibal recipes.

**Expected behavior**  
Non-cannibal shouldn't be able to cook human flesh. Not only these recipes clutter the recipes tab, but it's illogical. I assume in extreme circumstances one can eat a human meat - by roasting it aka cooked creep, but NOT turning it into sausages, pizzas, nachos etc. 
Maybe Sapiovore mutation should unlock those recipes.

**Versions and configuration:**
 - OS: Win 7
 - Game Version: latest master
 - Graphics version: Tiles
 - Mods loaded: No mods

**Comment by Rivet-the-Zombie** [comment]
>Non-cannibal shouldn't be able to cook human flesh.

I feel like even non-cannibals should have a basic recipe or three - maybe cooked, salted, smoked, and dehydrated versions - for human flesh for use in times of dire need. Just because you don't really want to have to eat a piece of a person in order to survive, that doesn't mean you shouldn't be able to do basic forms of preparation to it when you're forced to.

**Comment by LadyCatnip** [comment]
I see why the recipes are being learned automatically, they don't have **"autolearn": false,** unlike all the other Human Flesh recipes.

**Comment by LadyCatnip** [comment]
I tried to edit the human flesh recipes  to include autolearn false, yet even with that tag for all the recipes, when I start a character with cooking 10 I know those recipes. Does anyone know what's causing this?

**Comment by FulcrumA** [comment]
>Non-cannibal shouldn't be able to cook human flesh. Not only these recipes clutter the recipes tab, but it's illogical.
I absolutely disagree. The fact that I didn't initially start as a cannibal doesn't mean I have no knowledge of how to use human flesh to cook all kinds of regular meals. And that's what many cannibal dishes are - regular food, just with human flesh, ones I bet I could prepare IRL despite not being a cannibal myself. Ideally, recipes would call for types of ingredients and give results on the basis of what ingredients were used but we're not there.

Even if I don't use human meat in my cooking, somehow making the knowledge unavailable bothers me. I'd understand if there'd be some special qualities of the meat and very sophisticated, gourmet recipes that simply do not work with any substitute - in such case, yes, the recipe should only be learnable from a source of sorts. But if I know how to make a sandwich with some meat, I should know how to make the same with a human meat. 

The clutter isn't big, especially if you filter regularly, the recipe may be used in emergency or for some RP and the change in general is some arbitrary decision that is illogical - the only silver lining is that if someone will try to get it through, I don't think it will be hard for me to revert it, if only as a personal modification for myself. Though frankly, "No cannibal recipes" should be its own mod, as it is with questionable weapons and some types of enemies.

**Comment by chaisawlajatang** [comment]
> I feel like even non-cannibals should have a basic recipe or three - maybe cooked, salted, smoked, and dehydrated versions - for human flesh for use in times of dire need

Yes, that's right. 

> The fact that I didn't initially start as a cannibal doesn't mean I have no knowledge of how to use human flesh to cook all kinds of regular meals

Yes, from technical point of view cooking human flesh could be the same as cooking, say, beef, but the thing is **why** would you do that. Non-cannibals receive severe moral penalties for butchering human corpses and eating human flesh, so the only possible situation they would eat human flesh (aside from roleplay reasons) is an absolute abscence of any other food for a long time. I don't see any reason to auto-learn all those recipes unless you have cannibal or psychopath traits.

**Comment by sfsworms** [comment]
Ok, but why remove them? If someone wants to rp with them, why stop them?

**Comment by chaisawlajatang** [comment]
> Ok, but why remove them? If someone wants to rp with them, why stop them?
If someone wants to rp a non-cannibal eating human flesh for some reason, they would still have basic recipes (i.e. cooked creep). And there's always "To serve man" cookbook.

**Comment by FulcrumA** [comment]
>Yes, from technical point of view cooking human flesh could be the same as cooking, say, beef, but the thing is why would you do that.

Because I decide to. For various reasons, RP included. Because even if I don't cook human meat ever, I find it absolutely logical to still have that possibility if I know how to cook other types of meat.

>Non-cannibals receive severe moral penalties for butchering human corpses and eating human flesh, so the only possible situation they would eat human flesh (aside from roleplay reasons) is an absolute abscence of any other food for a long time.

Which proves we have the feature already balanced and cannibalism coming with consequences - there's no need to disable recipes on top of that, forcing people to disregard certain options when they should be available when it doesn't not disrupt the gameplay or balance in any way.

>I don't see any reason to auto-learn all those recipes unless you have cannibal or psychopath traits.

I see few more, ones already mentioned - because logically and believably a person should be able to. I strongly advocate leaving decision if they should be willing to the player rather than force thing supon them when it's not necessary. 

>If someone wants to rp a non-cannibal eating human flesh for some reason, they would still have basic recipes (i.e. cooked creep). And there's always "To serve man" cookbook.

Going by that logic, we should absolutely turn off all cooking autolearn recipes beside a few most basic ones. There's always cooking books out there they can seek to be able to make the simplest of dishes. After all, what if someone doesn't want to indulge some other type of food or they play with a trait that makes certain groups of food unavailable - shouldn't we advocate for having those recipes disabled as well for the fairness of it?

Generally, I can fully understand someone not wanting to indulge in the cannibalism feature, be it on moral, RP or merely practical (malus for non-cannibals) grounds. But it's arbitrary change that will be of miniscule benefit to the portion of playerbase minding the recipes, while quite disruptive and inconsiderate toward everyone else.

**Comment by Kelenius** [comment]
It might be a good idea to add in-game toggles to the crafting menu - e.g. hiding cannibal recipes, food that you have an allergy to, clothes you have an allergy to, clothes you can't wear due to mutations... That way the recipes are still available but can be easily hidden to not clutter the menus.

**Comment by chaisawlajatang** [comment]
> Because even if I don't cook human meat ever, I find it absolutely logical to still have that possibility if I know how to cook other types of meat.
> there's no need to disable recipes on top of that, forcing people to disregard certain options when they should be available when it doesn't not disrupt the gameplay or balance in any way.
> I see few more, ones already mentioned - because logically and believably a person should be able to
> Going by that logic, we should absolutely turn off all cooking autolearn recipes beside a few most basic ones

We already have dozens of recipes very probably never ever used by anyone, cluttering the crafting menu. But cannibal recipes are very specific niche stuff for 1-2 traits and 1 mutation perk only. 

> After all, what if someone doesn't want to indulge some other type of food or they play with a trait that makes certain groups of food unavailable - shouldn't we advocate for having those recipes disabled as well for the fairness of it
> Why certain group should be treated with more leniency than the other - because it's more commonspread

Again - we have a very specific trait, benefiting from a single type of food ingredient, everyone else gains severe debuffs. Yeah, this trait is balanced, I agree, and good portion of the balance goes with the starting cookbook. 

> I can see it as an opt-in mod rather than obligatory change, though.

**In fact, that would be totally ok**. But it looks tricky to implement. Before opening this issue, I tried the same thing as LadyCatnip did. Looks like the problem is deeper, and all recipes are auto-learned at the start regardless of "autolearn":false flag.

> It might be a good idea to add in-game toggles to the crafting menu - e.g. hiding cannibal recipes, food that you have an allergy to, clothes you have an allergy to, clothes you can't wear due to mutations... That way the recipes are still available but can be easily hidden to not clutter the menus.

And that would be a godsend. I think of tab "Undesired" or like, where all unwanted recipes go. Allergic food could be automatically transferred there, also player could mark some unwanted stuff to move there etc.  They're still craftable, but not in the main tab.

**Comment by CoroNaut** [comment]
human meat is nearly the same as animal meat, I don't quite see why we don't have regular meat versions of all the above recipes :wink:

**Comment by Treah** [comment]
@CoroNaut Its not cooked creep without the creep, then its just cooked meat :P

**Comment by kevingranade** [comment]
> I think of tab "Undesired" or like, where all unwanted recipes go. Allergic food could be automatically transferred there, also player could mark some unwanted stuff to move there etc. They're still craftable, but not in the main tab.

I like this idea a lot, it nicely models the, "I know *how*, but *why*?"
