### ISSUE TITLE
Mod Inclusion Project: Folding Parts Pack

### ISSUE THREAD

**Issue by DracoGriffin** [CleverRaven/Cataclysm-DDA#25068]
Use the following issue as a space to discuss the inclusion of:

Mod Ident: deoxymod
Name: Folding Parts pack

Your comment should include:

### Suggestions for induction
(what parts of the mod should be included, can be as simple as just an item, a location or the complete inclusion)

### Incompatibilities
(what parts of the mod should not be included, either some objects / items or entire mod is conflicting with DDA theme [ for whatever reason ])

**Comment by cake-pie** [comment]
Relevant: #19991

---

We can review individual parts for inclusion based on some consensus volume/weight limits.
(will mostly involve applying `FOLDABLE` to existing DDA parts, thus obsoleting the mod version)

I think it would be reasonable it to be possible in vanilla DDA to allow folding of:
- the smallest engines (small 1-cylinder) and tanks (2L)
- small electronic / dash-mounted items ( clock, atomic nightlight, *maybe* alarm, backup beeper, stereo )
   - necessary to allow them to be mounted on foldable vehicles
- electronics control is already foldable in DDA since #24594 and can be obsoleted in mod
- and add a smaller version of the basic solar panel in DDA for foldable / portable applications

Making large items like quarterpanels and solar panels foldable is a probably stretch for vanilla DDA, so the mod should continue to exist for people who want such features.

**Comment by Night-Pryanik** [comment]
Maybe I don't fully understand the meaning of word `folding`, but how it would be possible to fold an engine? I mean, it's rigid!

**Comment by cake-pie** [comment]
Ah, right. This is a bit of a quirk/workaround as I understand it.

For a vehicle to be foldable, all of its vehicle parts must have `FOLDABLE` flag.

So, to make a part such that "this part is allowed on a folding vehicle, but isn't a part that actually folds", we give the part with `FOLDABLE` but set the folded volume to be identical to its original volume.

See https://github.com/CleverRaven/Cataclysm-DDA/pull/17183#issuecomment-228588237 and surrounding context.

**Comment by kevingranade** [comment]
I agree with @cake-pie, the very smallest parts could get "FOLDABLE" applied, IIRC that got derailed in the past because people interested in expanding what is FOLDABLE wanted everything to be FOLDABLE, so when told they can't mark a car seat as foldable they made a mod instead.

**Comment by AbsalomAchitophel526** [comment]
I think the issue is not that people want foldable VW Beetles but rather that they want something like this:  ![atvrack](https://user-images.githubusercontent.com/33147994/44615540-03aefa00-a802-11e8-9f84-7cca62141d84.jpg)

And that currently, foldable simulates this by allowing you to stuff a much smaller vehicle into a larger one.  A compromise could be reached by allowing Drive-By-Wire controls to be foldable, or some smaller drone variant, to allow for surveillance vehicles carry-able as cargo.

**Comment by cake-pie** [comment]
> foldable simulates this by allowing 

Sure, but that's a stopgap measure, a workaround to make up for the lack of features to support towing and/or transporting other vehicles (e.g flatbed).

Design decisions about whether a part should be `FOLDABLE` in mainline DDA should be made solely based on whether it can realistically be included on a vehicle that can be collapsed into compact dimensions and carried around. The need to support a workaround should not be a consideration here.

The workaround will still be possible by using the mod, which will still exist -- status quo preserved.

**Comment by cake-pie** [comment]
## Exising parts altered by the mod

### Obsolete
* electronics control unit `controls_electronic` -- already foldable in vanilla


### Definite yes
Make these foldable in vanilla; no volume reduction

* vehicle tank (2L) `tank_little`
* small 1-cylinder engine `engine_1cyl_small`
  * smallest engine, 0.3L 2-stroke
* clock `vehicle_clock`
  * it's a wristwatch


### For consideration

* stereo system `stereo`
  * tie a boombox to your bike

* wheelbarrow wheel `wheel_barrow`
  * similar use case as folding shopping cart

* drive by wire controls `drive_by_wire_controls`
  * for remote-control / drone applications

Lighting -- likely OK
* atomic lamp `atomic_lamp`
* atomic nightlight `atomic_light`

Simple offensive capability
* `blade_horizontal`, `blade_vertical`
* `spike`, `spike_wood`

Portable water rig?
* water faucet `water_faucet`
* water purifier `water_purifier`


### Probably not
* security system `vehicle_alarm`
  * kind of moot if the vehicle can simply be folded and carried off

* camera control system `cam_control` and security camera `omnicam`
  * allows driver fully enclosed with no view of "outside" -- won't occur in a foldable vehicle

* back-up beeper `beeper`, chimes `chimes`
  * seems rather silly



### Nope
* aisle lights `aisle_lights`
* swappable storage battery case `storage_battery_mount`
* all 5 types of solar panel
  * instead, add a small solar panel to DDA
* minireactor `minireactor`

Ruled out by https://github.com/CleverRaven/Cataclysm-DDA/pull/19991#issuecomment-271467357 :
* small wheel `wheel_small`, `wheel_small_steerable`
* vehicle tank (10L) `tank_small`
* 1-cylinder engine `engine_1cyl` ( 0.6L )
* V-twin engine `engine_vtwin` ( 1.0L 4-stroke )



## Parts added by the mod
None of these should be foldable in vanilla

* folding extra light quarterpanel `fxlhalfboard_*`
* foldable door `fdoor`
* superalloy coating `sheet_superalloy`

**Comment by Human-Shield** [comment]
I thought that swappable storage battery case was just an empty frame box with wiring to it. Seems like it could it folded down to flat pack it.

**Comment by Kelenius** [comment]
>stereo system (3.5L)

It's not just a boombox, it's a stereo system that draws power from the vehicle. I think it's too clunky to be added to a foldable bike.

>wheelbarrow wheel (2.25L)

It's just a wheel. I'd say yes, without volume reduction.

>drive by wire controls (3.75L)

This is a pretty big thing. I don't know about this one. It would be really neat to have foldable devices that are remotely controllable.

>atomic lamp (1L), atomic nightlight (0.25L)

These are just lights, they don't even need power connection. Yes.

>Simple offensive capability

These all protrude from the vehicle, so I'd say yes.

>water faucet (0.75L)

It's just a small faucet, shouldn't cause issues, I'd say yes.

>water purifier (3L)

????? water purifier is foldable, really? I think it shouldn't be. I'd say no.

>security system (0.25L), back-up beeper (0.25L), chimes (4L)

It might seem pointless to attach these, but that's not the point. What matters is if's theoretically possible to attach them, and I think that both security system and the beeper should be, but not the chimes. Aside from the volume, `A stereo system with loudspeakers and a built-in set of simple melodies that it will play.` doesn't seem like something that can be folded.

>camera control system and security camera

Monitors on a foldable device don't make a lot of sense, and the camera is useless without them. So I'd say no.

>aisle lights

It's an attached flashlight... I don't see why not.

>swappable storage battery case

The frame itself is 2.25L, but the battery is whopping 10L, which implies that the frame has a lot of empty space in it... and it actually makes perfect sense to make it foldable - you'd just need to take out _the battery itself_ before folding it, and inserting it back after unfolding.

>solar panels

Solar panels, being flat, should be easily foldable, but it might be better to make a separate recipe for a foldable panel.

>minireactor (1.5L)

I was initially in agreement, but it's surprisingly small, so I'd say it should be foldable (without volume reduction, of course).

>small wheel (2.25L)

`A pretty small wheel.  Probably from one of those Segway things.  It is not very menacing.`

I think this is small enough to be attached to a foldable device, so I think this should be up for debate.

>vehicle tank (10L), 1-cylinder engine, V-twin engine

I can definitely imagine the tank being attached to a side or the back of the vehicle without getting in the way of folding, but if it's made like that, you'd also be able to stick it in every tile.

As for the engine, here you go: https://www.youtube.com/watch?v=gG8pzzElF18, definitely possible.

>folding extra light quarterpanel, foldable door

I'm having trouble imagining how this even works.

>superalloy coating (0.5L)

As far as I can tell, it does absolutely nothing. Should be probably just removed.

**Comment by cake-pie** [comment]
> water purifier (3L)

I was leaving it under consideration in case of some use case involving carrying it around, but come think of it you already get that by not installing it, in which case it is a battery-powered device. Moved to nope.
.

> water faucet (0.75L)

Pretty useless with limited capacity of tanks that can be installed on a foldable veh.
.

> aisle lights
It's an attached flashlight... I don't see why not.

> `"name": "aisle lights",`
> `"location": "on_ceiling",`

What aisle? What ceiling?
.

> solar panels
Solar panels, being flat, should be easily foldable

These are large, flat, rigid, fragile panels, perhaps slightly under 1m x 1m dimensions. Doesn't seem like a good idea to incorporate them into a collapsible rig: expect them to be outside or protuding when vehicle is in folded form, hard to protect them when wrangling it around.

Hence my suggestion for smaller version of the basic solar panel, maybe a quarter of the size, which flavor-text-wise would be more practical to tuck away safely.
.

> swappable storage battery case
The frame itself is 2.25L, but the battery is whopping 10L, which implies that the frame has a lot of empty space in it... and it actually makes perfect sense to make it foldable - you'd just need to take out the battery itself before folding it, and inserting it back after unfolding.

We should not approach this as "is there a way to engineer part X so that it is collapsible?", but rather "should part X be permitted on folding vehicles?" with the understanding that "folding vehicles" are intended to have pretty limited capability -- not much more than a bicycle or small gas/electric moped.

Having storage battery case as foldable is pretty much attempting to circumvent the limited capability, under the guise of being a tradeoff, requiring battery to be removed and transported separately.
While that used to be practical with sufficient character strength, since #22980 you now need lifting tools to swap out the battery -- making it too far-fetched for use on a folding vehicle that's supposed to be conveniently portable.

**Comment by FulcrumA** [comment]
>water faucet (0.75L)
>Pretty useless with limited capacity of tanks that can be installed on a foldable veh.

Perhaps, with very small tanks it makes kinda less of a point but still, it hurts no one and if someone wants a faucet connected to their bike, why not?

>What aisle? What ceiling?

Aisle lights are kinda a hacky job. Yeah, mounted on the ceiling etc but it's basically just regular lamp. In fact, no matter if this mod passes, I'd like the aisle light to be changed into simply a 'light/lamp' since it is a flashlight connected to controls and I'd agree that after renaming and slightly changed it it also should go on a folding vehicle. Hell, I already use those as a lamp on my welding carts due to lack of better alternative.

>Having storage battery case as foldable is pretty much attempting to circumvent the limited capability, under the guise of being a tradeoff, requiring battery to be removed and transported separately.

I think that's a pretty good tradeoff - sure, it may circumvent one shortcoming of such vehicles but at a considerable price. I think it's only fair.

>We should not approach this as "is there a way to engineer part X so that it is collapsible?", but rather "should part X be permitted on folding vehicles?" with the understanding that "folding vehicles" are intended to have pretty limited capability -- not much more than a bicycle or small gas/electric moped.

While it'd be very cumbersome, you can strap a pretty big battery to such. It will just work worse, the weight will impact its mobility and it will still be limited by how much the engine would be able to move - exactly as it'd be in game. I'd rather avoid forcing folding vehicles to be unable to use certain parts just to enforce their limitations. Even in this case, making the storage battery itself not foldable and given its weight, it'd be only applicable in limited circumstances so I'd be all for making the storage case foldable as well.

**Comment by sfsworms** [comment]
I have to agree with @FulcrumA's position here. The basic question is one of design: do we base the decision of whether to make a part foldable or not on what we thing is useful, or on the fact that it should be possible to have it being foldable?

I favor the second option. If a part is useless on folding vehicles, people simply won't use them. Or maybe the player base will invent some nice, emergent use, or they'll be useful for niche applications. (What if you want to carry along a cart-mounted laser gun for clearing cities? It might make sense to unfold them, and use a crane on your deathmobile to swap the batteries.)

With this in mind, I thing the general rules to determine whether a part should be foldable or note should be based on two things: size, and whether it's too fragile to stand the folding process. (So, basically, windshield and solar panels should be out, as well as anything over a certain size (3 L?) with the exception of purpose-made folding parts (folding frame, etc etc).

**Comment by kevingranade** [comment]
Re storage battery, theres another question of whether the folding frame can handle the weight of the battery.

**Comment by Kelenius** [comment]
>In my view, foldable vehicles, e.g. folding bike, collapsible shopping trolley, are intended to fill the role of "last mile" in transport and loot hauling

I agree with this; the biggest reason to fold a vehicle is (probably) to put it on your deathmobile, and we'll hopefully soon have #25191 to do that with vehicles too big to be considered "foldable".

**Comment by cake-pie** [comment]
>  the biggest reason to fold a vehicle is (probably) to put it on your deathmobile, and we'll hopefully soon have #25191 to do that with vehicles too big to be considered "foldable".

Not exactly; #25191 is still limited to bike-scale: 1-tile wide and no longer than the width of the carrier vehicle. It will not support use cases that are more akin to towing, trailer, or flatbed.

**Comment by Kelenius** [comment]
>Not exactly; #25191 is still limited to bike-scale: 1-tile wide and no longer than the width of the carrier vehicle. It will not support use cases that are more akin to towing, trailer, or flatbed.

And these devices are obviously too big to be foldable.

**Comment by cake-pie** [comment]
My argument isn't that
> we shouldn't allow certain parts because it will bring it closer to what [some people] want, [and that] would be a bad thing inherently

What I'm trying to express (possibly quite poorly) is, from a game design standpoint, there ought to be different roles for mobile bases vs "normal" vehicles vs foldable vehicles, each with differing capbilities, and clear advantages and disadvantages when choosing between them.

My chief concern is: if we're not careful, foldable vehicles can become almost as capable as regular ones. If it gets to the point where foldable vehicles can supplant regular ones for many purposes, you have a dominant strategy, gameplay suffers.

So I'm particularly wary of parts that would extend range and endurance -- that being a key differentiator in the vehicles' roles. Storage battery case is the  obvious example. Water purifier is another -- increasing duration out in the field without having to return to base or stopping to build a fire.

Keep in mind that this mod was made, and parts added to it, because those parts were rejected as foldable in vanilla in the first place. By definition, many (most?) things in this mod exist to circumvent intentional limits imposed in vanilla DDA. Therefore, with the exception of a handful of uncontroversial parts, it's worth thinking twice about inclusion of most of them.

---

> we should leave it to players and their decisions, including the bad decisions - just making sure the realistic consequences apply, rather than enforce 'common sense'. 

I'm not completely convinced that it's adequate to let in-game mechanics govern the practicality of a folding vehicle design. No one is going to lug a large, heavy folded vehicle around, they'll just unpack it immediately after unloading from their deathmobile. The unpack action requires adequate inventory space to hold the folded vehicle, and sufficient strength to handle its weight. Volume can be easily gamed by wearing a lot of storage, which leaves weight as the only meaningful limitation.

Also worth noting, there's no currently no protection against a player folding a vehicle that they will not be able to unfold, which is punishing/unfair: https://github.com/CleverRaven/Cataclysm-DDA/issues/22771#issuecomment-359950862

Re: silly/uselesss parts, I was just pointing them out, and don't feel strongly about letting players use them on folding vehicles.

**Comment by FulcrumA** [comment]
>What I'm trying to express (possibly quite poorly) is, from a game design standpoint, there ought to be different roles for mobile bases vs "normal" vehicles vs foldable vehicles, each with differing capbilities, and clear advantages and disadvantages when choosing between them.

Here I mostly can agree with you - yes, foldable vehicles should primarily serve different roles than other types of them, I just have to underline that those different roles should come as a natural limitation of the vehicle, rather than arbitrary decision and ti shouldn't be rigid - just a tool of certain boundaries and limits, with players operating within them as they see fit. The advantages/disadvantages doesn't need to be something specifically enforced, just stemming from the nature of foldable vehicle.

>No one is going to lug a large, heavy folded vehicle around, they'll just unpack it immediately after unloading from their deathmobile.

Which I'd say is fine. If someone wants to devoid themselves of primary benefit of a foldable vehicle, paying the price of it being hardly well-transportable and requiring packing oneself with bags or rolling it down the road with advanced inventory before unpacking, it seems fair. Even relatively heavy and sizeable foldable vehicle will have to be pretty light and thus limited in various roles - because the weight and volume of those increases pretty easily and it won't take long before it will be hard to carry it in another vehicle's cargo storage yet alone in inventory, thus making it completely useless as an actual foldable.

The issue you mention is indeed an issue and probably should be solved with a warning and inability to fold things above certain size/mass (probably the one of aforementioned cargo storage should be the max possible).

**Comment by cake-pie** [comment]
First, quick note:

> it won't take long before it will be hard to carry it in another vehicle's cargo storage yet alone in inventory

Cargo space accepts 250L, trunk 162.5L; character's str-based weight limit for carrying is the more likely limiting factor most of the time.

-----


Okay, here's (hopefully) better organized reasoning and elaboration on why I don't think it is sufficient to rely on volume/weight of the folding vehicle as the only limitations.

The foldable vehicle mechanic, like any other game mechanic, should offer a meaningful gameplay choice. The player must make a tradeoff: to gain some advantages, you have to pay a cost in some other way.

The status quo in vanilla, without this mod, is as follows:

**Advantages:**
A vehicle spanning multiple tiles can be reduced to a 1-tile item
- depending on the parts, there is some volume reduction
- it can be carried (depending on volume/weight)
- it can be transported in another vehicle (depends on vol/wt, but usually not the limiting factor)

**Disadvantages:**
.
- Limited by ability to unfold the vehicle
  - cannot be larger than your available inventory space
  - cannot weigh more than you can carry

.
- Limited electrical system
  - limited epower storage
    - only car battery, small and medium storage battery allowed,
  - limited recharging
    - no solar panels, only motorbike alternator, or use jumper cables

.
- Limited propulsion choices:
  - muscle power
    - power capped by player strength
    - range/endurance capped by stamina
  - electrical
    - power limited: small electric motor only
    - range/endurance capped by limited batteries

.
- limited range of other parts that can be included, e.g.
  - seats: limited comfort: only saddle and foldable seat
  - cargo: limited capacity: only folding wood box, storage bag, wire bike basket, folding shopping cart basket
  - etc.


It's super obvious what your tradeoffs are if you're evaluating a folding vehicle vs a 12-, 16- or 20-tile sized car. In such a comparison, the size factor dominates.

What is more subtle, and you're perhaps forgetting to consider, is the choice between a folding vehicle vs a non-folding one in roughly the same size/weight class.

Why should I build a 4- or 5-tile bike/buggy/sidecar that isn't foldable? Right now, if you choose to go with foldable, you make clear sacrifices in terms of electrical and propulsion options. The cost you pay in limited power, range, utility is evident.

Consider the change that allows storage battery case. That's a massive boost in battery capacity from 7000 (medium storage battery) to 40000. You also gain the ability to hot-swap batteries rather than having to hook up a cable. The only cost incurred is a little inconvenience of having to remove the battery for transport and reinstall it before use -- and that itself aids in circumventing the weight/volume limits of folding vehicle mechanics.

As for allowing internal combustion engines: it's fine if we stick to the tiniest fuel tanks and engines, maintaining proportionality with the other propulsion methods currently allowed. Going from 2L fuel tank to 10L is a fivefold range increase, which I am wary about. Engines: should be more like "put-put" than "vroom".

What I do not wish to see is a situation where there is little meaningful choice. If it becomes a trivial decision -- "if I'm going to make a vehicle that size, I might as well make it foldable", that's a loss in richness of gameplay. 

So:

> > No one is going to lug a large, heavy folded vehicle around, they'll just unpack it immediately after unloading from their deathmobile.

> Which I'd say is fine. If someone wants to devoid themselves of primary benefit of a foldable vehicle, paying the price of it being hardly well-transportable and requiring [troublesome] before unpacking, it seems fair.

What about someone who has (or is considering) a vehicle of volume/weight that is at around the practical threshold for foldability? They may not really care about being able to carry it around at all. But if they can gain the ability to pack and load it onto another vehicle, for little or no cost or disadvantage, does that not become the dominant strategy?

**Comment by Kelenius** [comment]
>What is more subtle, and you're perhaps forgetting to consider, is the choice between a folding vehicle vs a non-folding one in roughly the same size/weight class.

>Why should I build a 4- or 5-tile bike/buggy/sidecar that isn't foldable? Right now, if you choose to go with foldable, you make clear sacrifices in terms of electrical and propulsion options. The cost you pay in limited power, range, utility is evident.

Even with this mod, if you make it foldable, you are still making sacrifices. If you're making a non-foldable buggy, you can easily fit a cargo space or three on it, each giving 250L of volume, then add liquid tanks in every tile for 60L each. There is no way a folding vehicle of any size is going to be even remotely close to that.

Furthermore, you _are_ expending more resources to make a folding vehicle. For example, regular frames are common, but you need to specifically make folding frames. They're also more flimsy IIRC.

The parts should be foldable if they can be feasibly folded, not because you decided that the game should be played your way.

**Comment by DracoGriffin** [comment]
Looks like this has been decent debate so I'll leave this issue open for further discussion and for anyone interested in tackling the induction.

**Comment by FulcrumA** [comment]
@cake-pie
>What is more subtle, and you're perhaps forgetting to consider, is the choice between a folding vehicle vs a non-folding one in roughly the same size/weight class.

Not at all. I simply think that's a non-issue. 

If a player wants to create a tiny vehicle that would work as well as foldable, using weaker frames etc to mimic the qualities of a foldable analog, then sure - I'll let them make such unfoldable foldable-like vehicle. I don't see why foldables should be arbitrarily made worse just because you can make non-foldable vehicles which would serve similar function or that only foldables should serve certain purpose not directly relatd to them being foldable.
They still will lack the actual foldability which is the point of making foldable vehicles in the first place while being able to handle customization with parts foldable vehicles won't have - all seems fine to me.

Anything other than a small vehicle will not be workable as a foldable without other downsides we discussed earlier, either.

>Why should I build a 4- or 5-tile bike/buggy/sidecar that isn't foldable? Right now, if you choose to go with foldable, you make clear sacrifices in terms of electrical and propulsion options. The cost you pay in limited power, range, utility is evident.

Which is fine, but it doesn't and even shouldn't stem from arbitrary decisions of enforcing certain roles on vehicles or players, but from limitations of parts that are compact enough to befit a foldable vehicle. If you can make a vehicle that isn't exploity but it works for whatever purpose you have for it, you should be able to do it no matter if it's foldable/unfoldable or if such analog can be made.

>Consider the change that allows storage battery case. That's a massive boost in battery capacity from 7000 (medium storage battery) to 40000. You also gain the ability to hot-swap batteries rather than having to hook up a cable. The only cost incurred is a little inconvenience of having to remove the battery for transport and reinstall it before use -- and that itself aids in circumventing the weight/volume limits of folding vehicle mechanics.

While at the same time defeating a lot of the purpose of the foldable vehicle in the first place as to conveniently travel with a set of such batteries to swap, you likely will need another vehicle, thus making storage batteries still an option a player may pursue, even if it's an option that's not the most reasonable as it defeats the points of a foldable vehicle when it requires another vehicle to be able to set it up to be mobile. It self-balances right there without stifling player's options.

>What I do not wish to see is a situation where there is little meaningful choice. If it becomes a trivial decision -- "if I'm going to make a vehicle that size, I might as well make it foldable", that's a loss in richness of gameplay.

As long as it's merely an opinion based on player's preferences, not ouright lack of balance, I am very well fine with people saying so. And given the things we mentioned, tradeoffs between those two types of vehicles, it will be exactly merely a preference - some players will be know and decide to build the vehicles as foldables if they'll be of particular size but well-knowing that the same vehicles won't be able to accept many parts and thus their utility will be limited to some particular roles and some will create non-foldable versions which may serve exactly the same purpose but, well, lose the whole foldability. To force all of the potential vehicles to some nice based on foldability is unfair.

Ability to create analogues between foldables and non-foldables isn't loss of richness of gameplay. As long as it's fair, I'd argue it adds to the richness, allowing alternative ways of knocking same issues/creating vehicles for particular purposes. It's arbitrary gating of "your foldable vehicles have to serve in this capacity by being made in this particular way and your non-foldables in that capacity" that's a loss of such richness in my opinion.

Again, the idea behind the ticket is to make certain vanilla things foldable to allow option for that, it's not to decree what those vehicles are allowed to do- a thing which you base your whole argument on - merely what parts believably fit either type of design. The mod is a mod because people wanted parts to fold that shouldn't be realistically foldable without losing the qualities that gave them their current form in the first place. I believe that adjusting that purely on the basis of realism and believability will be much more fair and balanced than trying to arbitrarily enforce certain roles and expectations on players regarding what they'll have to use, how and why. 

Otherwise, at best, it will lead to pretty fair but avoidable "this thing should be foldable and it makes sense, I'm including it/please include it" tickets/pull requests, at worst treated as a giant, insulting "play this particular aspect of otherwise sandbox game how I want you to on no other grounds than that I want you to do it this way" change that will be inferior to the mod and thus disregarded/pointless to implement in the first place.

**Comment by cake-pie** [comment]
> not because you decided that the game should be played your way.


This isn't about how the game "should be played". Neither you nor I nor anyone can dictate that to anyone, and this mod's existence is proof enough. If this discussion results in absolutely no changes to the game, folks who don't like the existing limitations can still use this mod and play the game however they like and enjoy. OTOH if parts are made foldable that I don't find realistic, I'll just play without using them on folding vehicles, or mod my own copy if it comes to that. But that's beside the point.


What this discussion is about, is what the "default" vanilla game balance should be for foldable vehicles. *That* is why we are having this debate.


This mod is definitely not suitable for wholesale merged into vanilla, so we are posed with the question of what items in the mod *can* be included, i.e. do not conflict with preexisting DDA theme and game balance.

I choose to approach this by giving heavy consideration to the status quo: What are currently allowed folding parts in vanilla, and what is the present state of gameplay balance as a result of those limitations. I'm not saying that the balance is immutable, it can certainly be tweaked; however, I don't think we should be making changes here that lead to a large swing in game balance, e.g. 5- to 6-fold increase in foldable vehicle operating range.

So when Kevin indicated that we could allow internal combustion for foldable vehicles, I also took heed that he has already ruled out parts like I2 engine (above, https://github.com/CleverRaven/Cataclysm-DDA/issues/25068#issuecomment-416454542) and others https://github.com/CleverRaven/Cataclysm-DDA/pull/19991#issuecomment-271467357 . Perhaps he can be persuaded to change his mind about some of them, but I take that as a good starting point for determining where the line should be drawn, for game design and balance purposes.

I may not have conveyed my thoughts clearly enough in the earlier part of this thread, but thanks to a robust debate I've been pushed to articulate better; I have arrived at two key criteria that I believe are reasonable based on the present state and balance of the folding vehicle mechanic -- to restate in brief:

1.
> If the result is significantly bulkier than a folded bike -- say, more than a large briefcase -- or involves further dis/assembly (e.g. storage battery) then [it is] against the spirit of being a conveniently portable thing.

2.
> The foldable vehicle mechanic [...] should offer a meaningful gameplay choice. [...]
> If it becomes a trivial decision -- "if I'm going to make a vehicle that size, I might as well make it foldable", [...] does that not become the dominant strategy?

This may seem excessively complex when there is the option of taking a simpler approach and just go with "is it small enough? is it foldable? Y/N".

But, that approach leaves us open to changes that will significantly shift the game balance from where it is currently at. It is a flawed criteria because our `volume` stat is an abstraction that doesn't properly capture the dimensions and structure of a part. It is not a reliable gatekeeper vs items that may have wonky stats.

I believe it is this lack of clarity that led to discussions that were

> derailed in the past because people interested in expanding what is FOLDABLE wanted everything to be FOLDABLE

Because when `FOLDABLE` is taken at face value, it is easy to come up with various lines of reasoning to justify making `myfavepart` foldable, by devising a certain structure or construction for the part or the way it is mounted on the vehicle. So, is the swappable battery case collapsible because it is hollow? Or is that not feasible because you need it to be rigid and robust to support the weight of an installed battery? etc ... We'd face having to go through such minutiae just to consider the foldability of every individual borderline or controversial part.

On the other extreme, we could allow almost anything and everything, as long as someone is able to contrive some means of "here's how I can make this work as part of a foldable vehicle" -- but once that kind of precedent has been set, it becomes difficult to rein things in if and when the need arises.

All this is why I don't consider the simple size criteria as being sufficient.

I realize I may be arguing for an unpopular position, but so be it -- it's not a popularity contest.

---


> If you're making a non-foldable buggy, you can easily fit a cargo space or three on it, each giving 250L of volume, then add liquid tanks in every tile for 60L each. There is no way a folding vehicle of any size [can do that]

The disadvantage of a foldable vehicle vs a non-foldable one of the same size/weight is that the non-foldable one can have many parts -- including large parts -- put on it, thus no longer being in that size/weight range... :confused: That's just sidestepping the parameters of the question, isn't it?


---


> it will lead to pretty fair but avoidable [...] tickets/pull requests, at worst treated as a giant, insulting [...]

It's only game, why heff to be mad? Use the mod, free yourself from the restrictions you don't agree with, play the game, be happy.

It doesn't even have to be a binary choice between vanilla vs the utterly unrealistic foldable parts -- if there is demand for a middle ground between the two, we can have a mod that caters to that, too. I don't see a problem with that -- this isn't a content mod, it's more like "Simplified Nutrition" or "Perfect Reliability" mods -- giving players more options if they don't want to deal with certain mechanics or limitations in the base game.


---


Re: needing foldable frames as opposed to easily obtained non-foldable frames:
You don't need that many, so it's a pretty small one-time upfront cost at build time when amortized vs the benefits you reap from the folding vehicle over its entire lifetime.

Re: foldable frames have less durability than regular ones:
This is a better type of tradeoff -- it involves an ongoing cost in return for the benefits of foldability. But in this case it just means you have to be more careful not to get into a fender bender. It is generally desirable behavior to avoid getting into accidents anyway, so that's not actually a significant inconvenience.


---

Side note: because robot controls is already foldable, I think that is sufficient precedent for drive-by-wire to be made foldable as well.

---

At this juncture, I've given my 2¢ and laid out my full reasoning. No offense meant, but I don't feel I have much left to add if this continues with the same few people talking. I'm moving on to other PR/issues, feel free to @ summon me if the need arises.

**Comment by Kelenius** [comment]
...let's just go through the list of the parts and see where we disagree specifically. This thread has spiralled waaaaaaaaaay out of control.

**Comment by meladath** [comment]
Just piping in here, a v-twin/I2 should totally be foldable imho... as its potentially a motorbike engine, anything larger than that though, absolutely not.

As a car enthusiast, the vehicles in this game are lacking, I want to stick a turbo on my 3l inline-6 petrol (supra anyone?) and gain speed, not just sticking a bigger engine in (also the power that engines give out seems very unrealistic in my opinion)
