### ISSUE TITLE
Error message on auto pickup failure 

### ISSUE THREAD

**Issue by logros13** [CleverRaven/Cataclysm-DDA#25087]
**Is your feature request related to a problem? Please describe.**  
It is very easy to miss auto pickup not picking up an item if you are not paying close attention.

**Describe the solution you'd like**  
A failed auto pickup resulting in a error message in the log ex "you failed to auto pickup kevlar vest due to insufficient storage volume."

**Comment by cake-pie** [comment]
Some thoughts:

- avoid spamming: player should not complain re: "stop bugging me, I already know that I don't have enough capacity for \<big item\>"
   - automatically suppress further messages (until some condition has been met)
- should not require manual intervention to re-enable
   - avoid "I forgot to turn it back on and now I missed getting \<item\> due to lack of notification"
- stay useful: player might want to continue looting i.e. "I know I can't pick up any more \<big item\> but I want to continue collecting \<small item\>; tell me when I run out of space for *that*"
   - suppression of further messages should be nuanced, not binary

I think this can be accomplished with using a threshold.
Pseudocode:
```
warn_thresh = INF;

if( autopickup failed for item_X ) {
   if( item_X.volume < warn_thresh ) {
      warn_thresh = item_X.volume;
      show_warning();
   }
   // else: suppress warnings about equal/larger items
}

if( storage capacity increases beyond warn_thresh )
   warn_thresh = INF;
```
