### ISSUE TITLE
Having an NPC install a CBM does not consume CBM or anaesthetic

### ISSUE THREAD

**Issue by saladasa** [CleverRaven/Cataclysm-DDA#25167]
**Describe the bug**  
When you use the NPC dialogue to install a CBM, the process does not consume the CBM and does not consume any anaesthetic kits.

**To Reproduce**  
1. Spawn in any CBM and an anaesthetic kit.
2. Spawn in an NPC capable of installing bionics.
3. Install the CBM through the NPC dialogue.
4. Observe the still-existing CBM and anaesthetic kit.

**Expected behavior**  
The CBM and anaesthetic kit should be consumed in the process.

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version:  0.C-30823-g1052542
 - Tile

**Comment by mlangsdorf** [comment]
I'm not going to say I broke this, because I'm fairly sure I didn't, but currently the CBMs are consumed in the autodoc iexamine.cpp function, not in install_bionics.

mission_companion.cpp talk_function::bionic_install() needs to be updated to remove the CBM installer item from the player's inventory.

I don't know if the anesthesia kit needs to be consumed, either: it's not an autodoc operation and the doctor may be providing the anesthesia.
