### ISSUE TITLE
Sealed stomach behaves unexpectedly

### ISSUE THREAD

**Issue by Brambor** [CleverRaven/Cataclysm-DDA#25182]
**Describe the bug**
**A)** When crafting a liquid, sealed stomach (non rigid container, reseable, watertight) is calculated as a viable option for storage. However, when it is in inventory that is full, it cannot contain produced liquid when crafting is successful, so it forces the PC to spill liquid on the ground, if the stomach had to be used as a container.

**B)** Additionally, again, PC inventory is full and there is empty sealed stomach in there. The stomach can be accessed via advanced menu and liquids can be poured into it. This results in exceeding inventory volume, so PC may have 3.00L/2.00L (150%) of their inventory used. The PC doesn't drop anything ~~and can walk around with it.~~ But they drop it the next turn. (thanks for patience while testing @alanbrady)

**C)** When trying to move liquids in advanced inventory, you can press move some (default key `m`) which will ask for "How many do you want to move? (have 1)". It always displays 1. When you write one it transfers all liquids possible, not only one.

**Steps to reproduce the behavior:**
**A)**
1. Make PC with filled inventory including empty sealed stomach. No nearby watertight containers (or better add their volume up to the assumptions following).
2. Craft clean water, it allows you to batch craft 6, that is 1.5L = volume sealed stomach can contain.
3. Watch as you cannot select sealed stomach as a destination for water.

**B)**
1. Make PC with filled inventory including empty sealed stomach.
2. Open advanced menu, hover over sealed stomach in inventory and "open" its content. The default key is `C`.
3. Try to fill it up from the other side of advanced inventory with any liquid, e.g. `plastic bottle of clean water (2)` not `water (2)`, sorry.
The last step will result in increasing volume in inventory and exceeding it.

**C)** Vis description.

**Expected behavior**
**A)** Probably allowing sealed stomach as a container (as it does now). Shoving it up in the selection menu, when selected, and when it will exceed volume inventory, then drop it on the ground. (or say dispose of wielded item and wield it or something)

**B)** Same as A, when inventory volume is exceeded, drop the item.

**C)** Allow player to choose any value, not just all of it.

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version #7775
 - Graphics version Tiles
 - Mods loaded dda, StatsThroughSkills

**Comment by alanbrady** [comment]
I'm not sure I'm fully understanding all the issues outlined here and it might be better to break these up into separate issues.  But here's what I've got:

A) This does seem like a bug and should probably get fixed.  I'm actually surprised this doesn't happen already.

B) When I try to do this, if I try to do this with advanced menu, the game tells me I can't pick up liquid.  I'm not sure I'm understanding your reproduction steps correctly.  If I do this via the reload menu, then overflow inventory appears to be dropped correctly.

C) I get same thing I get with B if I try to move liquids around with the advanced menu.

From what I see, 'A' is definitely a minor bug that should get fixed, 'B'/'C' shouldn't even be possible because you shouldn't be able to move liquid with the advanced menu and the real bug is that you can move liquids with the advanced menu.

That said, I couldn't reproduce B and C with the steps listed above.

I'm wondering if it's possible https://github.com/CleverRaven/Cataclysm-DDA/pull/24488 has anything to do with this and the reason I can't reproduce the other issues is because @Brambor has some sorting set that I don't in my test environment.

**Comment by alanbrady** [comment]
That got it thanks, I can reproduce those now.

I still think the real problem here is the advanced menu lets you move liquid around like this.  I can think of a handful of edge cases that would be really terrible to try to handle if we try to enable this behavior.  The advanced menu currently doesn't really have a lot of feedback to be able to properly handle something like this.

There's a reason you can't normally handle liquids raw like this.

Having now understood the issues at hand, A is a completely different problem from B/C and I would recommend closing this and filing two new separate issues so they can be addressed independently.  I would also combine B/C to just say advanced menu lets you move liquids and causes problems.

**Comment by Robik81** [comment]
Ability to move liquid is not IMO a problem. Problem is that AIM apparently does not handle work with expandable container well - it probably does not check it there is enough of inventory space for expanded container and just checks it the container itself could be expanded without any external constraint.

In other words, large sack inside of the small box problem.

**Comment by alanbrady** [comment]
@Robik81 might be right and that all that needs to happen is we need a check to see if we need to drop overflow and/or prevent filling the container if it would make us overburdened.

I just tried playing some more with this, and amazingly, the edge cases I thought would be a problem are actually already handled pretty nicely.

For part C where @Brambor wants to specify the amount of liquid poured would take a bit more work to do right but I suppose it's possible to do, but that falls under feature request I think.

> This results in exceeding inventory volume, so PC may have 3.00L/2.00L (150%) of their inventory used. The PC doesn't drop anything and can walk around with it.

This part confuses me because if I repro this, the player character immediately drops the overflow inventory following the next turn.

**Comment by Brambor** [comment]
@alanbrady I lied. I made this issue from memory, I thought I moved, sorry again. Never thought that I would be wasting so much of your time. Well, thanks.

I'm updating the issue

**Comment by Brambor** [comment]
I will split it as @alanbrady suggested.
