### ISSUE TITLE
Zombie technicians can steal built-in bionic weapons

### ISSUE THREAD

**Issue by Regularitee** [CleverRaven/Cataclysm-DDA#25190]
Had this issue with autonomous surgical razors, not sure if others are affected.

**Comment by Qrox** [comment]
We can fix this by having them tear out all the bionics in you and damage your body.

**Comment by Night-Pryanik** [comment]
> We can fix this by having them tear out all the bionics in you and damage your body.

This will make zombie technician probably the most dangerous opponent for bionics-heavy characters.

**Comment by AMurkin** [comment]
He should pass PC armor + roll with some chance to perform this attack. And give some sign for a player that next attack may cause such problems. Like necromancer before he rises dead zombie.

**Comment by Night-Pryanik** [comment]
I think for now it should be sufficient just to block the ability if wielded weapon is a fake weapon.

**Comment by mlangsdorf** [comment]
Easiest solution is to make all fake items out of superalloy, then the zombie technician won't even try to steal it.

**Comment by mlangsdorf** [comment]
Everything currently in mainline with NO_UNWIELD is also superalloy.
We can fix this in code, which is tricky, or in JSON, by making autonomous surgical razors by superalloy.

**Comment by mlangsdorf** [comment]
and yet it was the way the code worked for years without the bug appearing. Zombie technicians don't attempt to pull monomolecular blades out of your hands because they're superalloy. You can't test the NO_UNWIELD fix with mainline CBMs because mainline CBMs aren't valid targets of a technician magnetic pull.
Why not apply the bandaid immediately and then fix the issue long term?

**Comment by Kelenius** [comment]
Since #25369, razors aren't a wieldable weapon.
