### ISSUE TITLE
Autocrafting of intermediate components

### ISSUE THREAD

**Issue by G3Kappa** [CleverRaven/Cataclysm-DDA#25265]
**Is your feature request related to a problem? Please describe.**  
When crafting certain items, some intermediate components may be required. These may be not readily available, such as a spike when crafting a knife spear, even if the player has enough materials to make them. Thus, the knife spear will be grayed out, and the player will not know that they can craft it. The problem becomes more evident when dealing with electronics and more complex crafts.

**Describe the solution you'd like**  
Ideally, items that fall into this category should be displayed in a different color (say, yellow or blue) in order to indicate that _they may be crafted, but some intermediate assembly is required_. When selecting them, the game will automatically take care of crafting the intermediate components, possibly asking the player to choose between different options and materials. Since some components may require the same materials, a check should be performed to make sure that _all materials are available, including those required by the missing components_.

**Describe alternatives you've considered**  
Autocrafting itself may be scrapped entirely, but highlighting items that lack craftable intermediate components seems rather useful to me. I can't really think of an alternative on the spot, but it goes without saying that everything is up for debate.

**Additional context**  
Here's a simple mockup of my suggestion:

![image](https://user-images.githubusercontent.com/6323641/44882082-2afa4100-acb2-11e8-9a69-ebfa27bb6661.png)

Additionally, items shown in yellow should be sorted after items shown in white but before items shown in dark gray.

**Comment by kevingranade** [comment]
This is possible, but quite tricky and difficult to implement without causing a great deal of overhead when displaying the crafting menu.
Keep in mind the menu ends up having to evaluate this for every recipe it displays, and it has to do all of these calculations before it displays anything on the menu.

It would be reasonable to display this only for highlighted recipes since that keeps it from having to evaluate everything at once.

Ironically autocrafting intermediate parts is far easier than just displaying whether it's possible or not.

**Comment by Theundyingcode** [comment]
implementing the autocrafting and simply highlighting craftable sub components for the current recipe would still be a massive QOL improvement though
