### ISSUE TITLE
Overmap special placement fails when city distance is over the default value (4) 

### ISSUE THREAD

**Issue by TheEventHorizon** [CleverRaven/Cataclysm-DDA#25359]
**Describe the bug**  
If the world setting for city distance is greater than 4 overmaps specials fail to be placed. Such as the refugee center. The larger the city distance the fewer overmap specials are placed.

**To Reproduce**  
1. Make a world (with or without mods)
2. Set city distance to any number greater than 4
3. Start with the evacuee scenario 
4. Examine the computer terminal
5. Select option 3
6. Close computer terminal
7. Or move about the map causing new specials to fail to place

**Expected behavior**  
Placement of overmap specials to not be dependent on city distance. No errors regarding placement should occur without mods. 

**Screenshots**  
N/a

**Versions and configuration:**
 - OS: Windows 10
 - Game Version:  0.C-31493-gf5a6c87
 - Graphics version: Tiles
 - Mods loaded: "dda",  "filthy_morale",  "no_npc_food",  "novitamins"

**Additional context**  
N/a

**Comment by MT-Arnoldussen** [comment]
huh, i thought the refugee centre not spawning was a bug in general

i do play with higher city spacing a lot though

**Comment by ralreegorganon** [comment]
> **Expected behavior**
> Placement of overmap specials to not be dependent on city distance. 

Overmap specials specifically allow city distance to control when they spawn.

I just stepped through the repro steps here for city sizes 5 through 8 (the max), and it spawned a refugee center in every single case. However, it could be many many overmaps away from the spawn location.

In general, increasing the distance between cities decreases the number of cities per overmap, which means that the specials that need to be in or near cities are competing for fewer spaces, sometimes significantly fewer depending on the settings.

```
    // spacing dictates how much of the map is covered in cities
    //   city  |  cities  |   size N cities per overmap
    // spacing | % of map |  2  |  4  |  8  |  12 |  16
    //     0   |   ~99    |2025 | 506 | 126 |  56 |  31
    //     1   |    50    |1012 | 253 |  63 |  28 |  15
    //     2   |    25    | 506 | 126 |  31 |  14 |   7
    //     3   |    12    | 253 |  63 |  15 |   7 |   3
    //     4   |     6    | 126 |  31 |   7 |   3 |   1
    //     5   |     3    |  63 |  15 |   3 |   1 |   0
    //     6   |     1    |  31 |   7 |   1 |   0 |   0
    //     7   |     0    |  15 |   3 |   0 |   0 |   0
    //     8   |     0    |   7 |   1 |   0 |   0 |   0
```

Looking at the definition of the refugee center in specific, it looks to me like it has a fairly tight set of constraints which probably limits the likelyhood that it spawns on any given overmap, despite being a mandatory special.

```json
{
    "type" : "overmap_special",
    "id" : "evac_center",
    "overmaps" : [
        { "point":[0,0,0], "overmap": "evac_center_1_north"},
        { "point":[1,0,0], "overmap": "evac_center_2_north"},
        { "point":[2,0,0], "overmap": "evac_center_3_north"},
        { "point":[3,0,0], "overmap": "evac_center_4_north"},
        { "point":[4,0,0], "overmap": "evac_center_5_north"},
        { "point":[0,1,0], "overmap": "evac_center_6_north"},
        { "point":[1,1,0], "overmap": "evac_center_7_north"},
        { "point":[2,1,0], "overmap": "evac_center_8_north"},
        { "point":[3,1,0], "overmap": "evac_center_9_north"},
        { "point":[4,1,0], "overmap": "evac_center_10_north"},
        { "point":[0,2,0], "overmap": "evac_center_11_north"},
        { "point":[1,2,0], "overmap": "evac_center_12_north"},
        { "point":[2,2,0], "overmap": "evac_center_13_north"},
        { "point":[3,2,0], "overmap": "evac_center_14_north"},
        { "point":[4,2,0], "overmap": "evac_center_15_north"},
        { "point":[0,3,0], "overmap": "evac_center_16_north"},
        { "point":[1,3,0], "overmap": "evac_center_17_north"},
        { "point":[2,3,0], "overmap": "evac_center_18_north"},
        { "point":[3,3,0], "overmap": "evac_center_19_north"},
        { "point":[4,3,0], "overmap": "evac_center_20_north"},
        { "point":[0,4,0], "overmap": "evac_center_21_north"},
        { "point":[1,4,0], "overmap": "evac_center_22_north"},
        { "point":[2,4,0], "overmap": "evac_center_23_north"},
        { "point":[3,4,0], "overmap": "evac_center_24_north"},
        { "point":[4,4,0], "overmap": "evac_center_25_north"},
        { "point":[2,5,0], "overmap": "road_end_south"}
    ],
    "connections" : [
        { "point" : [2,5,0] }
    ],
    "locations" : [ "wilderness" ],
    "city_distance" : [3, 5],
    "city_sizes" : [1, 12],
    "occurrences" : [75, 100],
    "flags" : [ "UNIQUE" ]
}
```

Looking at that, it's
1. big, 26 overmaps (5x5 with a road), 
2. requires a road connection 
3. must spawn in forest or fields
4. must be between 3 and 5 distance from a city
5. the city must be between size 1 and 12

That's a fairly tall order, and one which the world settings can greatly influence the chances of. 

I'd probably suggest tackling this by reviewing that definition for the refugee center such that it's more likely to spawn in a broader range of world settings.

I think in general this issue is more one of needing to review and potentially adjust the special definitions--we already have the case where too many specials mark themselves as mandatory, which the game then dutifully respects and prioritizes placing these mandatory specials. I get the feeling the min/max city size and distances for many of the specials also reflect a bit of just copying values from existing specials without understanding the impact on the overall mapgen.

**Comment by mlangsdorf** [comment]
Ban all non-quest related mandatory specials and then relax the constraints on most of the rest. There's no reason why gas stations, labs, and sugar houses shouldn't spawn at city size 3, or botanical gardens shouldn't spawn at city size 4.

Redo city_sizes to be [ 0, 16 ] for things that should spawn for innawoods games like caves and bee hives, and [ 1, 16 ] for things that should only spawn in games with civilization. The primary constraints  should be handled by city_distance and locations, and should be biased toward having stuff spawning instead of not spawning.
