### ISSUE TITLE
Several wheels missing/unable to be crafted

### ISSUE THREAD

**Issue by hughesdylan** [CleverRaven/Cataclysm-DDA#25379]
**Is your feature request related to a problem? Please describe.**  
Currently building a plow requires a generic "wheel" item that the player cannot create. It appears that these can only be disassembled from other farming equipment. Many other types of wheels are unable to be created also including casters and Bike wheels

**Describe the solution you'd like**  
Add recipes for all wheels that are not too technologically advanced. Specifically:
"Wheel"
"wheel_armor" (perhaps not this one for balance reasons)
"roller_drum"
"metal_wheel"
"wheel_bicycle"
"wheel_motorbike"
etc.

**Describe alternatives you've considered**  
If these items are un-craftable for game balance reasons perhaps instead make it clear that players could not craft those items. For instance:
"wheel_caster",
 "description": "A set of small wheels, mounted on pivots, like the ones on a rolling office chair or grocery cart. **Made on a precision lathe and would be very hard to duplicate.",**

It is also possible that this part of the code is simply messy and I am misinterpreting neglect as design. If so, apologies. 

**Additional context**  
This FR was originally about the fact that I could not make a plow without disassembling other farm equipment because it uses a generic "wheel" item that I was unable to produce or find. That item does come from breaking down other farm equipment I believe but this is a very confusing mechanic.

**Comment by FulcrumA** [comment]
Armored wheels aren't that much more complex than regular ones. I'd rather balance them by requiring a recipe found in a rare book, rather than making them much skill or materials dependant, yet alone completely outside of the scope of what player can make - especially given they can make much more impressive stuff.
Sure, armored wheels seem pretty great but with collisions balances that are being worked on they should be much less necessary.
