### ISSUE TITLE
In game chat would be epic. 

### ISSUE THREAD

**Issue by Lazyactor** [CleverRaven/Cataclysm-DDA#25371]
I am a big fan of another rogue-like called TOME or Tales of Maj'Eyal. In that game the guy who made it refereed to as Dark God managed to put in a  global chat. Its great. new players ask questions. theres achievement's that get announced live. Deaths that get announced. What killed them. Character sheets people can check out.It really brings the community to life even while your in game. I think it would be awesome if this community could enjoy something like that. 

-Implement an in game Chat that can be toggled on or off. 
-implement death messages for said chat. (example) - John Doe was crushed into pulp by a brute zombie after 12 days of survival. 
-implement an achievement system for people. so and so has killed a shocker brute for the first time. So and so has maxed  survival for the first time. 
Implement a character sheet people can share listing equipment and builds. 

What do you guys think? I would be willing to place a bounty for this feature of around 200-300 bucks if the community backs the idea.

**Comment by ennob** [comment]
Isn't most of what you are suggesting solved by, say, running IRC on the side? 

I am not in favor of this for the simple reason that adding network code to the game opens up a world of issues with remote exploitation. These issues are of course manageable, but I would be much less willing to run experimental builds if the game was accepting network traffic.

**Comment by CoroNaut** [comment]
There is absolutely no reason to introduce just chat messages, if you are going to add something like this then it would be best to just go all out and make the game multiplayer online or at least multiplayer LAN. Then these types of messages could come up when someone in the world dies instead of just someone in some other world. Making the game completely multiplayer however would be a serious feat to pull off.

**Comment by alanbrady** [comment]
We already have local multiplayer.  It's super broken but people use it.  That's actually a case I could see getting some value out of this but a) it requires a solid bit of work b) we should be probably be working on making local multiplayer less broken before we start talking about adding something trivial like chat though.

**Comment by kevingranade** [comment]
I mostly agree with @ennob , jumping from a completely self-contained executable to one that talks to the internet is a really big change.  As such the feature would strictly be an opt-in, it would not communicate with the network in any way by default.

If we were to have some kind of in-game chat, it would only be in-game, as in it would be based around interactions with a radio or similar messaging system, not game-like, "so-and-so has died" messages.

I wouldn't be totally hostile to an achievement or character export feature, but it would be push only, I have no interest in having an in-game feature for retrieving and viewing other people's achievements and characters, that would be better handled by a standalone website.

A major limitation of the system is that survivors could of course never meet each other, effectively they would be communicating across parallel universes.

**Comment by FulcrumA** [comment]
I am against it. It was fun, for a bit, in Elona but quickly got bothersome. CDDA is a turn-based game, with dedicated discord channel for seeking help or chatting and it's not a problem to simply stop doing things that pass the time in-game to comment or ask a question while not requiring coding necessary to add a feature that'd be more of a gimmick than anything.

In-game radio messages would be pretty great. Together with improved and expanded NPCs/factions, it could add much more to immersion and interaction between human characters, with various factions and individuals talking, making alliances, reporting happenings in their areas.

Achievements, however I am against as well. CDDA presents you a world and things to do, putting in useless feel-good checklists that may even not fit some player goals seems kinda pointless. Rather than excouraging some sort of completionist attitude that doesn't even fit the game well (and then having to maintain, bugfix and improve it as features achievements would be connected to change) we simply should have more goals and developments to aspire to, a thing which naturally will likely happen over time as the game grows bigger.

Given the randomness of such online things, how some leaderboards, achievement sets or other such stuff adds nothing to the gameplay or immersion for me (and how useless they'd be with modded games since various achievements would have various difficulties depending on the mods used), only generates useless buzz if implemented I'd likely force the game to not connect to the net to avoid it or outright mod it out if possible without much effort.

**Comment by Lazyactor** [comment]
you guys make a solid point. thank you for your feedback. 

"In-game radio messages would be pretty great. Together with improved and expanded NPCs/factions, it could add much more to immersion and interaction between human characters, with various factions and individuals talking, making alliances, reporting happenings in their areas."

i like this radio idea though.

**Comment by kevingranade** [comment]
If someone wants to add this, they can, but it's an obscure enough feature request that I'm going to close to try and keep the size of the issue tracker down.
