### ISSUE TITLE
Military vehicle spawn rate

### ISSUE THREAD

**Issue by Regularitee** [CleverRaven/Cataclysm-DDA#25433]
To follow up on the previous discussion about balance in https://github.com/CleverRaven/Cataclysm-DDA/issues/24982 is the issue of vehicle spawn rates.

Currently, the ratio of tanks to light vehicles seems much too high. Even historical deployments against enemies with large numbers of tanks (e.g. Gulf War 1) have involved much lower proportions of tanks-to-IFVs than what we see in Cataclysm. So I created this issue to get some input on what should be done in this regards.

For reference, these are the current military vehicles in the game, and closest contemporary US analogues:

 Game Name | Army Analogue
------------ | -------------
Self-Propelled Howitzer | [M109 Paladin Howitzer](https://en.wikipedia.org/wiki/M109_howitzer)
Main Battle Tank | [M1 Abrams](https://en.wikipedia.org/wiki/M1_Abrams)
Light Tank | None. Closest is [M551 Sheridan Tank](https://en.wikipedia.org/wiki/M551_Sheridan)
Atomic Tank | None. Nuclear-electric light tank.
Mobile Gun System |  [M1128 Stryker Mobile Gun System](https://en.wikipedia.org/wiki/M1128_Mobile_Gun_System)
IFV | [M2 Bradley](https://en.wikipedia.org/wiki/M2_Bradley)
APC (MG) | [M113 APC](https://en.wikipedia.org/wiki/M113_armored_personnel_carrier)
APC (GL) | See above
Mech. Inf Carrier (MG) | APC for power armor troops
Mech. Inf Carrier (GL) | See above
Humvee (MG) | [Humvee](https://en.wikipedia.org/wiki/Humvee)
Humvee (GL) | See above
Military Truck | [M939](https://en.wikipedia.org/wiki/M939_series_5-ton_6x6_truck) or [FMTV](https://en.wikipedia.org/wiki/Family_of_Medium_Tactical_Vehicles)

And the current spawn schedules:

```        "type" : "vehicle_group",
        "id" : "city_wrecks",
        "vehicles" : [
            ["tank_light", 100],
            ["tank_medium", 60],
            ["sp_howitzer", 40],
            ["mobile_gun_system", 50],
            ["ifv", 30],
            ["tractor_bandit", 25],
            ["tank_atomic", 25]
        ]
    },{
        "type" : "vehicle_group",
        "id" : "city_vehicles",
        "vehicles" : [
            ["tank_light", 80],
            ["tank_medium", 60],
            ["sp_howitzer", 40],
            ["mobile_gun_system", 50],
            ["ifv", 30],
            ["tractor_bandit", 20],
            ["tank_atomic", 25]
        ]
    },{
        "type" : "vehicle_group",
        "id" : "highway",
        "vehicles" : [
            ["tank_light", 200],
            ["tank_medium", 100],
            ["sp_howitzer", 100],
            ["mobile_gun_system", 75],
            ["ifv", 75],
            ["tractor_bandit", 50],
            ["tank_atomic", 25]
        ]
    },{
        "type" : "vehicle_group",
        "id" : "military_vehicles",
        "vehicles" : [
            ["tank_light", 500],
            ["tank_medium", 250],
            ["tank_atomic", 100],
            ["sp_howitzer", 200],
            ["ifv", 200],
            ["mobile_gun_system", 200]
        ]
```

As a side note, some of the vehicles don't seem to spawn at all, so those probably need to be added to the schedule as well.

**Comment by mlangsdorf** [comment]
I'm going to go with the percentages I suggested last time:

Vehicle | Spawn %
-------- | -------
tank_light: | 1.5
tank_medium: | 1
sp_howitzer: | 0.5
mobile_gun_system: | 2
ifv: | 6
tank_atomic: | 1
military_cargo_truck: | 25
humvee: | 12.5
humvee_gl: | 12.5
apc: | 11
apc_gl: | 11
aapc-mg: | 8
aapc-gl: | 8

Half all military vehicles are humvees or trucks. 90% of the remainder are APCs and IFVs of some kind. Only 5% of all military vehicles are actual heavy tanks (okay 10% if you include the IFVs) and SP howitzers are really rare.

The balance between humvees and military trucks could be adjusted (20% and 15 + 15% or 20% and 25% with only 5% of military vehicles being humvees with grenade launchers) but I think that's the general ballpark.

Maybe a tank recovery vehicle (big engine and a boom crane) should be added to the military vehicles, spawning at about the same rate as sp_howitzer.

**Comment by Regularitee** [comment]
A few notes:

1) Military truck deployment would not scale with inventory available, since one could argue they are being deploying in "unsafe" or "hostile" territory. They would likely be instead replaced with APCs or IFVs. (I think? Depends on the timeline lore explains how/when the military mobilized).

2) The light tank shouldn't exist, from a realism perspective. Production stopped by the 1970s due to the proliferation of infantry anti-tank weapons, and was fully phased out of American service by the end of the century. Its presence here (in 2050?) doesn't make sense, at least from a real-world perspective. (One could argue that this is an alternative timeline where... for some reason, light tanks remained viable, however. But in our "real" timeline, it wouldn't be ) Compared to IFVs or Humvees with TOWs, they're slower, less fuel-efficient, only slightly better protected, and they have no trained crews for them. And they're probably all mothballed and would require weeks/months to bring back into service.

3) You have nearly as many power armor APCs as you do regular infantry APCs on that list. Given how rare power armor is, shouldn't that number be way lower?

4) The IFV-to-tank ratio seems way off. America's inventory of the Bradley is currently 6230, while the Abrams is about 8100 . Its past deployments have seen similar ratios (1730 Bradleys and 2024 Abrams[1] deployed in active units during the First Gulf War)

[1] GAO/NSIAD-92-94 Performance of Bradley and Abrams, numbers for Feb 26, 1991

Actually, the ratios as a whole seem to deviate from the existing inventory. For reference, here's the current US inventory:

Vehicle | Inventory
--------- | ---------
M1 Abrams variants | 8100
Bradley variants |  6230
M113 APC variants | 5000 active, 8000 mothballed
Humvee variants |  230000
M109 Self-Propelled Howitzer |  48 (with 180 scheduled to be bought)
M551 Sheridan Light Tank | 0 active. 1662 built

But again, these are the real-world numbers, so there's some flexibility in a sci-fi setting.

**Comment by mlangsdorf** [comment]
Tom Clancy's "Armored Cav" is the only book I have quick access to that includes a full TOE for a large military unit.
The 3rd ACR has 2 IFVs, 12 APCs, 6 Humvees, and 6 trucks in the HQ Troop. 41 tanks, 41 IFVs, 6 APCs, 8 SP artillery pieces, 6 Humvees, and 44 trucks in each of 3 cavalry squadrons. 9 Armored recovery vehicles, 11 APCs, 11 Humvees, and 102 Trucks in the supply squadron. 12 APCs, 12 tanks, and 7 trucks in the engineering company. 6 more Humvees in the Air defense section.  Clancy is a bit vague on the support vehicles so I may have undercounted the trucks and humvees.

So that's a 135 tanks, 125 IFVs, 31 APCs, 24 SP artillery pieces, 9 Armored Recovery vehicles, at least 41 Humvees, and at least 240 trucks.

Your numbers put the ratios of tanks to IFVs to Humvees at 4:3:130, and I would expect the military has nearly a 1:1 ratio of Humvees to military trucks. So while I may be overcounting the number of APCs and AAPCs by a lot, I'm also really over overcounting the number of armored vehicles at all.

You can't replace the trucks with IFVs. The trucks aren't combat vehicles (though they may have an M2 on them because the US Army puts an M2 on everything), they're supply vehicles to transport the 200,000 gallons of fuel and multiple tons of spare parts you need to keep an armored regiment moving.

**Comment by Regularitee** [comment]
>a full TOE for a large military unit.

Actually, this brings up a good point: we've been focusing on front line, war-time military units. In truth, given the domestic nature of this emergency, the majority of the forces would be the under-equipped national guard and militias rather than the full-time professional forces. So we probably would see a much higher number of humvees and trucks, and drastically less SP arty, and somewhat fewer armored vehicles. Especially with the majority of career soldiers being deployed overseas due to a lack of recruitment numbers in recent years (probably? I dunno, its 50 years in the future).

Vehicle | Spawn %
-- | --
tank_light: | 0
tank_medium: | 4
sp_howitzer: | 0.5
mobile_gun_system: | 2
ifv: | 3
tank_atomic: | 2.5
military_cargo_truck: | 38
humvee: | 19.5
humvee_gl: | 19.5
apc: | 5
apc_gl: | 5
aapc-mg: | 0.5
aapc-gl: | 0.5

Is something closer to what I'd expect a realistic deployment to look like. *However*, that's just my take on realism: We may want to fudge the numbers more for diversity's sake so the spawn tables are more interesting for players. Particularly increasing light tanks and APCs, and significantly fewer trucks (since there are plenty of non-combat trucks already in the civilian vehicle spawn tables)

**Comment by overbo** [comment]
perhaps the light tank should be rebranded as the survivor tank, the tank companion to the armored car.

**Comment by Regularitee** [comment]
What about just merging the light tank and atomic tank into one thing? Their overall layout is extremely similar, save the power source. It would also provide some justification for a nearly century-obsolete "light tank" design to be reintroduced (super fast nuclear cavalry tanks being introduced to replace Humvees or something).

**Comment by Regularitee** [comment]
Vehicle | Spawn %
-- | --
tank_atomic: | 2.5
tank_medium: | 5
sp_howitzer: | 0.5
mobile_gun_system: | 3
ifv: | 4
military_cargo_truck: | 38
humvee: | 25
humvee_gl: | 15
apc: | 9
apc_gl: | 4.5
aapc-mg: | 1
aapc-gl: | 0.5

Which, if I didn't mess up the numbers,  roughly translates to:

Vehicle | Spawn %
-- | --
Armored Fighting Vehicles | 15
Thinskin Fighting Vehicles | 40
APCs | 15
Non-Combat Vehicles | 30

Military trucks should be disproportionately small for the sake of player interest... a there is already a nearly limitless supply of non-combat civilian vehicles, so I don't feel like a realistically much higher rate of trucks would be interesting for players. Similarly, I boosted APC numbers considerably above their realistic values so to keep anti-infantry vehicles the most prominent spawn type without making most stuff a humvee.

**Comment by mlangsdorf** [comment]
I'd recommend dropping the AFV percentage to 10%, adding 5% of Combat Engineering Vehicles (old tanks with howitzers and bulldozer blades), wrecker trucks with boom cranes, and tracked recovery vehicles. Possibly drop the military trucks to 20%, the Humvees to 25%, and adding some more MRAPs and other think-skinned fighting vehicles.

**Comment by Regularitee** [comment]
Well, that sounds all well and good, but to my knowledge they don't exist in game yet (unless I'm using an out of date version of the mod?). So the focus should for now should be balancing the ratios of existing vehicles, particularly since the as-of-yet-undecided configuration and loadout of these future vehicles may change the ideal spawn ratios even if we set some now.

Once the vehicles have been designed and published, we can then consider a separate issue to revisit the spawn schedules and factor them in.

**Comment by terribleperson** [comment]
This is just a thought, and isn't strictly related to spawn rates but it seems to fit here since you did mention the idea that light tanks probably shouldn't exist.

The idea of a nuclear tank doesn't seem completely ridiculous; a government that no longer cares about the political issues with nuclear power or thought the gains were worth the political price might very well revisit the idea of nuclear powered vehicles. I can't tell whether it's actually doable because there hasn't really been any need for a reactor with the particular set of specifications a tank would need. Tiny reactors for satellites are far smaller than the engine in a Abrams, but don't put out anywhere near enough power, and are designed to go much longer (years) without refueling than necessary for a reactor powering a tank. Experimental aircraft reactors have been too large to fit in a tank, but later ones also put out more power then a tank needs. The only known nuclear-powered tank proposal was before MBTs, before modern reactor design, before modern armor, and before modern electronics. It provides almost no useful insights.

The idea that they'd put a tank-sized reactor in a light tank is weird. Besides the already mentioned issue that light tanks are obsolete, putting a reactor in a tank would be super expensive. With that sort of investment, I can't see them being installed in anything but the most heavily armored platform. Weight isn't really a concern, because unless the reactor is capable of much more output than existing engines there's very little reason to use it. It would probably still be an MBT, not some sort of modern heavy tank, but it'd be the most heavily armored MBT yet.

**Comment by Mooses2k** [comment]
This is on pause until the tanks etc mod is integrated?

**Comment by Nacarbac** [comment]
An armoured reactor and repair truck intended primarily to serve drones, power armour and energy weapons - and never actually be used in combat - might make sense. 

It'd also have a dual-purpose of being something you could send to communities for disaster relief, so one variant might replace some of the UPS stations and robot carriers with water purification systems and crates of Evac Shelter supplies, etc.
