### ISSUE TITLE
I can't seem to start my charcoal kiln correctly with my regular Fire Drill that has 27 charges

### ISSUE THREAD

**Issue by Christopher3264** [CleverRaven/Cataclysm-DDA#25503]
**Describe the bug**  
I examine my kiln with fire drill in hand and don't get the option to light the wood inside it on fire. I have a pic but I'm not sure if this is a bug or not. Is the (fire drill) (50 charges) not considered a fire starter for the charcoal kiln? I don't have any other fire starters

**To Reproduce**  
1. Make a player with a gun, magazine, and some ammo.
2. Try to aim at a wall.
3. There's no way to increase aim level.

**Expected behavior**  
Ideally also describe *why* you expect it to happen.

**Screenshots**  

**Versions and configuration(please complete the following information):**
 - OS: [e.g. iOS 8 or Windows 10 or Ubuntu 18.04]
 - Game Version [from the main menu, e.g. 0.C-29938-g90f5268437]
 - Graphics version [Tiles or Terminal]
 - Mods loaded [e.g.dda, boats, hacktheplanet, StatsThroughSkills]

**Additional context**  
E.g. A link to a savegame that allows the issue to be reproduced.

**Comment by Christopher3264** [comment]
![screenshot 9](https://user-images.githubusercontent.com/43102117/45260111-82dd2a00-b3cd-11e8-93b8-106829d4cb5b.png)

**Comment by MT-Arnoldussen** [comment]
i think you might have accidentally your issue

**Comment by Christopher3264** [comment]
@MT-Arnoldussen What do you mean? I'm pretty sure its a bug because only a few firelighting tools actually let you properly light the kiln with (e)xamine.

**Comment by MT-Arnoldussen** [comment]
Read your issue and you'll see what I mean.

**Comment by Christopher3264** [comment]
Could I post a 1 minute video? I think it'll explain it better

**Comment by Christopher3264** [comment]
@MT-Arnoldussen Is it not a bug? The fire drill not being able to properly light the inside of the charcoal kiln on fire?

**Comment by CoroNaut** [comment]
Read your issue again: you have description explaining a fire drill bug, then you have steps recreating a bug with aiming a gun at a wall, then the rest is just bug report default text. We don't know what to make of it.

**Comment by Christopher3264** [comment]
@I guess I Couldn't post a short video clip?

**Comment by Qrox** [comment]
@CoroNaut I believe the steps are also default text from the template. @Christopher3264 You should remove all irrelevant bits in the template before posting to avoid confusion.

**Comment by AbsalomAchitophel526** [comment]
In any case,  the issue wherein fire drills and other craft-able fire sources are unable to "fire" a charcoal kiln is a real one.  A fire 1 tile away would count as a source of flame, but unless that fire is in a rock oven or similar item, the innawoods survivor risks burning the kiln.

Essentially, a charcoal kiln cannot be fired from craft-able fire sources.

**Comment by DocMooncalf** [comment]
I feel like there is some confusion on this issue. 

I just tested and a  fire drill (id: fire_drill) with charges CAN light the charcoal kiln.
But the "Camp Fire drill" (id: fire_drill_large) cannot, because the examine function for the kiln checks for charges, which the camp fire drill doesnt have.

I'd suggest two solutions:
1. Change the "camp fire drill" to have charges as well, or
2. Change the "iexamine::kiln_empty" to check for the "fire starter" flag instead of !p.has_charges( "fire" , 1 ) 

PS: I find the fact that the the "fire drill" has charges but the "camp fire drill" has no charges inconsistent.

**Comment by EirenexTheDragon** [comment]
It is because it is not a tool that creates fire instantly, unlike a matchbook or lighter. you can however use a open fire to lit the kiln.

**Comment by DocMooncalf** [comment]
@EirenexTheDragon this is not from a mod. Its from the experimental version. 
fire Drill (id:fire_drill) and camp fire drill (id:fire_drill_large) behave differently because one has charges and the other one doesn't.  That is the way those functions are coded, they check for charges " if( !p.has_charges( "fire" , 1 ) ) "

that's why the fire drill works like a lighter but the "better" camp fire drill doesnt work in these circumstance. I don't think that should be expected behavior

**Comment by Treah** [comment]
@DocMooncalf 
You are correct and I think the whole flag was introduced a while back to fix the problem with the electric fire starters. The original behavior for both drills used to be that they did not work on the kiln. Honestly I think its ok for them to start the kiln but using them to start an oil lamp would a bit far fetched for IRL applications but game play it may be something we have to live with for simplicity sake.

**Comment by DocMooncalf** [comment]
I think, in the end fire drill and camp fire drill should work **consistently**, i.e. both should be able to light up the same items. 

My guess for the quickest fix would be to change the camp fire drill to have charges as well (maybe a bigger number like 500). I'm not sure if a change to the tools.json would be sufficient for this (don't know the source code for charging)

**Comment by AbsalomAchitophel526** [comment]
Camp Fire Drills take a LOT more volume than regular fire drills, thus they have infinite charges.
