### ISSUE TITLE
CBM Integrated Toolset usable for cooking but not reheating?

### ISSUE THREAD

**Issue by communistkiro** [CleverRaven/Cataclysm-DDA#25527]
The integrated tool set can be used for cooking, yet not for reheating, the latter requiring arguably less heat, although the heat capacities of ice is at least double that of water depending on the conditions of reheating. Anyways, if food is FROZEN cost for reheating could be doubled or something, or the cooking part of the CBM could be scrapped, but currently it isn't consistent.

**Comment by Regularitee** [comment]
This has been an outstanding issue with the toolset bionics: they can be used in actions you cannot select with the bionics alone.

For example, with the integrated toolset you can use bionic power to solder stuff. But you can't actually start any soldering actions without a soldering iron, because the item action menu has the "Start repair..." option greyed out. Same for heating food. You can use bionic power to heat up food, but since you cannot select it in the item action menu, you need another item (like a stove) to start the heating process.

**Comment by communistkiro** [comment]
I'm currently content by adding a toolbox with little weight, yet the heating is still impossible. Adding an invisible, if possible, (upgraded with soldier iron/welder/heating flame) toolbox in player's inv could be an easy-ish solution, but I don't know how the CBMs are written to draw power/charges from the power storage.

**Comment by Regularitee** [comment]
Found the original issue for this problem: https://github.com/CleverRaven/Cataclysm-DDA/issues/19489

**Comment by nexusmrsep** [comment]
@Regularitee I didn't have time to address other problems in #19489, but some workarounds are possible in my opinion, if I managed to bypass this problem. I may return to it later, so remind me on Discord.

**Comment by DarianLStephens** [comment]
Is this an issue again? I'm not seeing the option in build 9140:
![image](https://user-images.githubusercontent.com/15375876/59409851-9e60df80-8dfa-11e9-91ce-db39338767ee.png)
I have several frozen items, including chunks of meat and fat.
