### ISSUE TITLE
Shooting in full automode doesn't stop after target is dead

### ISSUE THREAD

**Issue by Yuof** [CleverRaven/Cataclysm-DDA#25559]
Game version: 0.C-31975-g57f7aee (tiles) Build:7903

### Expected behavior
Pre #23098 bursts from automatic weapons would stop if they run out of targets.
### Actual behavior
You always shoot the full burst size even after the target is dead.
### Steps to reproduce the behavior
1.Get character with some stats + good SMG.
2.Shoot a zombie.
3.Even if you kill the zombie with the first bullet,you will continue wasting ammo.

As I understand the purpose of #23098 was to remove retargeting after the first target but it also removed the stop after all targets are gone.

**Comment by MT-Arnoldussen** [comment]
What else would you expect? It's not like you would know, mid-burst, whether your target is dead or live.

**Comment by Break-Off** [comment]
It think OP misunderstood burst fire as "PC firing 3 times, semi-auto", when it's an actual burst of 3 or more shots done by the weapon.

**Comment by Yuof** [comment]
It makes sense for short bursts(3) but for the longer ones (10+) the old code where you had a skillbased chance to stop made sense.
Also the PR never states the intention to remove this feature so I assume its unintended.

**Comment by MT-Arnoldussen** [comment]
Yeah, I imagine a true full-auto mode would work something like the current aim system, where you would press `.` to keep shooting for a turn.

**Comment by kevingranade** [comment]
This change was totally intentional, the firing rate for automatic weapons is far too high to react to an enemy collapsing and stop shooting.  Instead you pre-determine how long you intend to fire, and fire that much.

In the pr I said:
> Follow-up might adjust how long bursts are, but I don't want to get into that here.

To expand on this, we can change the duration of bursts and/or add additional burst modes in order to make things act sensically.

It's also feasible to adjust duration of short bursts based on player skill level, representing better mechanical ability to pull the trigger in a short and controlled fashion.
