### ISSUE TITLE
Food tags/materials hidden by packaging

### ISSUE THREAD

**Issue by Regularitee** [CleverRaven/Cataclysm-DDA#25605]
To explain what I mean, let's take potato chips. Look at the Material section. 

![food](https://user-images.githubusercontent.com/8593513/45562753-82e38c80-b808-11e8-8a99-86e24bb4c3c7.png)

While in the bag, the material is listed as plastic. When taken out, it shows the proper food material/categories. In other words, when in a package, the packaging's material is shown instead of the food's material. Not only does this layout hide relevant information about the food, but it's also formatted in such a way as to be confusing (the packaging material is mixed in with the food nutrition information, with no spacing or line divider).

**Comment by MrHrulgin** [comment]
This also frustrates me from the perspective of item sorting. Having clean water be in a number of different places in the list of consumable items because it's in different containers is not particularly useful. I get that for most other containers like magazines and batteries the container is more important than the contents, but when you find a "small plastic bottle of po..." in a kitchen somewhere because the item list truncated the long name it's clear there's an issue.
