### ISSUE TITLE
Dragon martial art style functions after death

### ISSUE THREAD

**Issue by mding9** [CleverRaven/Cataclysm-DDA#25629]
**Describe the bug**  
A person using dragon style will continue to use Dragon Vortex after being mortally wounded. This probably also works with other styles that have some sort of countering ability.

**To Reproduce**  
1. Choose shaolin adept trait.
2. Run at a horde of zombies and kill yourself.
3. It will look like the zombies are suddenly dying around you after you are downed (high skills and stats make this more noticeable).

**Expected behavior**  
You should not be able to dodge, block, or counterattack with a crushed skull or spine.

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version 0.C-32110-g9b133d9
 - Graphics version Tiles
 - Happens without any mods.

**Comment by Theundyingcode** [comment]
Cut off a wolfs head and it still has the power to bite?

IMHO while that is probably not intended behavior, it can explained away as "with their final breath..." or simply due to the fact that a beings momentum won't suddenly disappear when they die.  Even if this wasn't the case, so long as the `game over` code properly executed, anything that happens after a players death doesn't really matter.  If this occurs with NPCs then I think it would be worth looking into if they were not already so...
