### ISSUE TITLE
Clean water can be frozen after crafting

### ISSUE THREAD

**Issue by Kelenius** [CleverRaven/Cataclysm-DDA#25621]
**Describe the bug**  
Making clean water out of frozen water keeps it frozen.

**To Reproduce**  
1. Obtain frozen water.
2. Make clean water.
3. Observe that it is frozen.

**Expected behavior**  
It shouldn't be frozen. I've just boiled it. It should be hot, like crafted food.

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version [from the main menu, e.g. 0.C-32108-g5b8c27c]
 - Tiles
 - None related to freezing

![image](https://user-images.githubusercontent.com/6681708/45584569-d3c5b480-b8de-11e8-96d8-7d6dcd7555c7.png)

**Comment by alanbrady** [comment]
:(

**Comment by alanbrady** [comment]
So this just occurred to me but the recipe for clean water doesn't actually produce "HOT" water, which I'm pretty sure it should.  Will fix both.

**Comment by alanbrady** [comment]
So fixing this the way I want requires adding a flag to the recipe.  Items that have the EATEN_HOT flag are automatically heated, but are there any other items that aren't necessarily EATEN_HOT but their recipe requires heating them up?  I pretty much just have clean water, but I think there's others.

If it's truly only clean water it probably doesn't need a flag but that's not my suspicion.

**Comment by cake-pie** [comment]
Recipes involving `BOIL` quality or `water_boiling_heat` tool could be taken as indication that product is `HOT`

**Comment by alanbrady** [comment]
> Recipes involving BOIL quality or water_boiling_heat tool could be taken as indication that product is HOT

That's exactly what I was thinking.  There's kind of weird intersection currently between EATEN_HOT though.  Currently we automatically mark EATEN_HOT items as hot after making them.  I'm not convinced this actually correct because EATEN_HOT really just says whether or not you get a morale bonus from eating it while hot.  Meanwhile you could have a recipe that doesn't necessarily prepare the item hot, and as a secondary step, you could heat it up as well for morale bonus.
