### ISSUE TITLE
Lifting/cranes have restrictions, but do not inform players of these in any way

### ISSUE THREAD

**Issue by Regularitee** [CleverRaven/Cataclysm-DDA#25639]
The current restrictions on cranes are:
1) It must be on a vehicle other than that being worked on
2) It must be within two tiles of the player/vehicle being worked on

It's objectively horrible design that these two restrictions are in place, **and** that no where in the game does it tell the player this information. The lack of feedback means players will fail again and again, becoming confused and frustrated, since they have no feedback on why it fails to work. 

These restrictions should to be told to the player in an in-game manner, or otherwise removed completely.

EDIT: I was incorrect, it is in-game by examining the crane vehicle part. Though it is still missing from vehicle part items, and from providing any error message when examining the vehicle being worked on with the crane.

**Comment by maniak1349** [comment]
![cata_boom](https://user-images.githubusercontent.com/2755776/45590894-511b1480-b933-11e8-9076-343ea6331c7e.png)
It probably should be mentioned on parts before they are installed too though.

**Comment by Regularitee** [comment]
My mistake, it was present. 

Though it does seem to be poorly placed; it requires you be viewing the vehicle screen of the vehicle with the crane... which is mutually exclusive with seeing the vehicle you are working on (since cranes don't work for the vehicles they are installed on). 

Having it on the item description would be ideal, though having it listed under the additional requirements would be much better if possible. i.e.,

``"Additional requirements: 
strength 20 OR tool with lifting within 4 tiles``

**Comment by kevingranade** [comment]
Chill out, if you cant be civil, we dont want your bug reports.

**Comment by mrkybe** [comment]
@Regularitee Cranes should work for the vehicles that they are installed on.  I made the the changes and specifically to fix that issue.  The crane needs a clear path to the installation site.  Looks like the merge didn't go through correctly, since the text that is there is not what I had in the PR.  Will fix.

**Comment by Regularitee** [comment]
@kevingranade I didn't realize the word "horrible" was an uncivil word. It was my understanding that the word horrible was not particularly uncivil if used to describe something abstract ("horrible weather, a horrible part of town, a horrible crash"). Doubly so because my criticism here was constructive, providing my reasoning and recommendations.

Though if even that is too harsh for use, it might be more prudent to setup a word filter to ban the term completely.

**Comment by mrkybe** [comment]
@Regularitee is the intended description clear?

**Comment by derpkerk** [comment]
> Chill out, if you cant be civil, we dont want your bug reports.
implying that you are 100% civil all the time

guys if you were in his situation you would react with the same words. It is up to the receiver to take the mood into account when he after a bug encounter that prevents him from playing his weak character can't go on and is frustrated.

you receive frustration here. That is what motivates for a bug report, so that others don't have to have that feeling.

you chose to do this so not even "counter-abuse" is justified. it's just emotions involved for some. ANd you'd do good not to overreact with intimidation

**Comment by Regularitee** [comment]
@mrkybe Yeah. I'd also add a blurb to the item itself (when it's not attached to a vehicle), since people should know restrictions on the item's use *before* they install it (otherwise, they'll install it in a place where they can't really make use of it)
