### ISSUE TITLE
allows_remote_use flag doesn't work with placing monsters.

### ISSUE THREAD

**Issue by SunshineDistillery** [CleverRaven/Cataclysm-DDA#25645]
**Is your feature request related to a problem? Please describe.**  
The new flag ALLOWS_REMOTE_USE added in  #24732 does not work with the place_monster use action. It places a monster but does not remove the item from the ground. 

**Describe the solution you'd like**  
Have it properly delete/replace the item even when it's outside the player inventory. 

**Describe alternatives you've considered**  
**Additional context**  
Turrets and manhacks can be picked up or stored in inventory, but other robots(items) can be too heavy to pick up and activate.  If this new flag worked, it would solve that problem. Similar to the issue with folding vehicles in #22771.

**Comment by Robik81** [comment]
Just a note in case someone plans to use ALLOWS_REMOTE_USE for other items. Feel free to add the flag, but you have to test it in game if it is working. 

Flag ALLOWS_REMOTE_USE in itself does not guarantee function for every item. The use action must be written in a way that support it - not to be reliant on position of the item in the player inventory.

As such, this feature request should be considered as a request to make place_monster use action compatible with ALLOWS_REMOTE_USE flag, rather than a request to fix the ALLOWS_REMOTE_USE flag.
