### ISSUE TITLE
Too many mutations causes issues with actives

### ISSUE THREAD

**Issue by arc166** [CleverRaven/Cataclysm-DDA#25653]
**Is your feature request related to a problem? Please describe.**  
If you have too many mutations, the game runs out of keys to assign, so you can't select them to assign keys

**Describe the solution you'd like**  
The game either needs more keys to assign or a way to select them beyond pressing they keys the game assigns, as if it never assigned a key, you can't select the mutation to reassign that key

**Describe alternatives you've considered**  
As above.

**Additional context**  
N/A

**Comment by JantDarvus** [comment]
I'm having this exact issue. Due to getting some of my actives after first gaining a lot of passives, no way to actually use them. Bionics interface deals with this same issue by simply letting you manually browse through your bionics with arrow keys rather than only being able to use the hotkeys, could something similar be implemented perhaps since it would hopefully mean just reusing code rather than making something new?

**Comment by JantDarvus** [comment]
As a minor addendum, i'll note that both the Plant and Spider mutation trees are somewhat prone to this due to having actives towards the end of their selection, although you can certainly get the same from other paths simply by getting a wide variety of passives before some of your actives.
