### ISSUE TITLE
The Player should be able to carry more in their hands

### ISSUE THREAD

**Issue by TheWebRoamer** [CleverRaven/Cataclysm-DDA#25668]
**Is your feature request related to a problem? Please describe.** 
I find it strange that the player cannot hold more than one thing at a time. This becomes very frustrating for players starting a Naked and Afraid scenario and I'm sure there are other situations. Realistically, the player should be able to carry more than one item, whether it's a handful or an armful.

In the Naked and Afraid scenario, it just doesn't make sense that my character has to pick up one pine bough at a time rather than an armful. In other less extreme situations like the Evacuee, this feature could come in handy if the player has enough dexterity/aim/strength to wield multiple weapons at once. Such as dual melee weapons, dual pistols, or even dual shotguns (assuming the player is skilled enough to effectively wield two at once.) . If this is implemented the player should take a hit to aim/effectiveness in exchange for a boost in the speed of their attacks.

**Describe the solution you'd like**  
The player should be able to carry, wield and, use more than one item at a time.

**Describe alternatives you've considered**  
Implement something that would take into account the players ability to hold multiple items in their hands. I think some obvious things to start with would be the players Dexterity and Strength stats. If the player tries to go over what their stats allow, they either have a chance to drop the things the are wielding (potentially making noise?)  or won't be able to wield them at all.

If the player can't effectively use dual weapons, their combat ability will be severely hampered. If the player has more than one item in each hand, they won't be able to fight at all. If they get hit or attempt to fight, they will be forced to drop what they have in their hands.

**Additional context**  
Below is the skyrim comic that inspired me lol. See how the Khajiit is slamming down all those helmets onto the counter? I'm thinking something like that just... something more possible lol.
![comic](https://user-images.githubusercontent.com/43351987/45645035-4bd1dd00-ba8d-11e8-95a4-b2a2d2e3f791.png)

**Comment by Endovior** [comment]
I get your point, since it's possible to carry four two-litre bottles of soda, if you aren't doing anything else with your hands. On the other hand, that's less 'wielding an item for use in combat against the hordes of living dead' and more 'awkwardly carrying a load of junk'.

Something like the pic you posted would sort of demand more carrying ability than bare hands can supply; a bag of some kind is pretty much required. For a Naked and Afraid start, you're probably best off searching for a canvas sack; they're a common enough find when foraging, and one which can be instantly turned into a swag bag with no skill, and that's 15 litres of storage at the cost of _all the encumbrance_ on your off-hand.

In terms of a possible change to game mechanics, it might be possible to carry items instead of wielding them, giving you a fair boost to your carrying capacity... at the cost of high encumbrance, being unable to attack, and likely to drop the whole mess if you do get attacked. Even so, this is something that would mostly be useful in the very early game, before the player has any decent storage items.

Going further, and talking about dual-wielding of weapons... well, dual-wielding of guns is _wildly unrealistic_, and is unlikely to be implemented here. It's less unrealistic in terms of melee weapons, but even there, it's more a matter of 'specific martial arts allow use of specific paired weapons' instead of 'with appropriate training, you can fight effectively with any two random items'. I'd argue that in the cases where dual-wielding does make sense, it would be better to implement it as being able to use recipes found only in relevant martial arts stylebooks to craft two melee weapons of appropriate types into a paired version, which occupies both of your hands and has appropriate stats for that particular dual-wielding style.

**Comment by TheWebRoamer** [comment]
>I get your point, since it's possible to carry four two-litre bottles of soda, if you aren't doing anything else with your hands. On the other hand, that's less 'wielding an item for use in combat against the hordes of living dead' and more 'awkwardly carrying a load of junk'.

Yes, that's the idea. It's not just for fighting off enemies. It's also for utility. One such scenario that a survivor might run into is... "You've just finished clearing out a town. You parked your vehicle outside of town and now you're looting. You've filled your inventory to the brim and thus cannot carry anymore. But you've just found a whole bunch of books you've been looking for." Rather than having to carry one book back to your vehicle and come back for the others, why can't my survivor just take a stack of them? In my head, It's meant more as a quality of life change that just so happens can be doubled as a extra option for fighting.

> Something like the pic you posted would sort of demand more carrying ability than bare hands can supply; 

Yeah, it was just meant as a little visualization. As stated, I don't think something like that is reasonable.

>In terms of a possible change to game mechanics, it might be possible to carry items instead of wielding them, giving you a fair boost to your carrying capacity... at the cost of high encumbrance, being unable to attack, and likely to drop the whole mess if you do get attacked. Even so, this is something that would mostly be useful in the very early game, before the player has any decent storage items.

This is pretty much a restatement of my point. Especially:
>...at the cost of high encumbrance, being unable to attack, and likely to drop the whole mess if you do get attacked.

As for the dual wielding of weapons I didn't really make to much of a case out of it seeing as it wasn't the point of this issue. But what I had in mind regarding firearms is "sacrificing stability for rapid fire", as it would be harder to aim because, you know, you have two guns in your hands.
As for melee weapons, I wasn't really thinking about martial arts, I was thinking more along the lines of wielding two tonfas and just beating down monsters at the cost of losing stamina faster. I thought it was kind of a funny picture. But with certain weapons, it could be viable. 

>it would be better to implement it as being able to use recipes found only in relevant martial arts stylebooks to craft two melee weapons of appropriate types into a paired version, which occupies both of your hands and has appropriate stats for that particular dual-wielding style.

This is a good idea. Nice one. :)

**Comment by Lamandus** [comment]
I can't code, but my idea would got like this: you get volume bonus if you don't wield anything. The amount is debatable, how about 3-4 liter. But when you start wielding something, you loose the extra volume, dropping the stuff on the ground.

**Comment by Tatterdemalian** [comment]
I'd just let players wield a whole stack of items, with a maximum quantity of individual items equal to their DEX and maximum total mass equal to their STR in kilograms.

**Comment by AdriaanRenting** [comment]
I think it would need some kind of stackable mechanic and probably a few other things as well.

I'm not sure how much realism it would add for the extra cost of the code that needs to be developed and maintained.

I'm imagining someone trying to smash and climb into a window with some 2L bottles in their arms. It would be a struggle at best.

I understand the point but in the end it's a game, and as such I am interested in game balance arguments as well, not just realism arguments.

**Comment by AdriaanRenting** [comment]
I was wondering if this could be solved by giving the player some carrying capacity depending on their STR and DEX. That would not model the resulting encumbrance though.

**Comment by Tatterdemalian** [comment]
Actually it's as simple as enabling the same "select how many items in the stack you want to drop" in the wield menu, and the system I proposed would deal with yet-uncoded situations where a player might ever try to wield too many or too heavy items, by simply making them fumble and drop the excess at their own feet. The only problem I see so far is that it doesn't make much sense for a character to only be able to carry a single type of item at a time, but giving a character a new STR and DEX based carrying pouch doesn't make a lot of sense, either. If you're carrying stuff in your arms instead of in duffel bags, you're not going to be able to wield any weapon, except the pile of junk you're hauling. If you want an actual permanent body pouch, there are bionics and mutations already for just that purpose.

**Comment by TheWebRoamer** [comment]
@Tatterdemalian I have extremely basic knowledge of coding but going off what @AdriaanRenting was saying, I feel as though if the player had some sort of unseen storage container that would act as the player's arms, it would work pretty well. I feel like this would be a solution to your proposed problem of only being able to carry one type of item at a time. 

And if the player is utilizing their "arms container" they are unable to wield weapons. And if they attempt to, they could be prompted that if they wield their weapon they will drop what's in their arms. So if a player ends up having to fight, they have to drop everything in their arms. Which by the way, the speed at which a player is able to drop items should be increased because you know, it's in their hands and not a bag or something. However, if the player is hit while carrying items in their arms, make it so there is a high chance of the player dropping whats in their arms.

If the arms were made into a back up container that is only revealed to the player when their inventory is full, couldn't this arm theory be a simple if statement? Like "If inventory is full, prompt player to carry item with their hands/arms. If no, drop item. If yes, stop wielding current weapon/item and prompt player as to what they want to do with it.".

**Comment by Kelenius** [comment]
Having a storage container representing arms doesn't make a lot of sense. Holding two two-liter bottles is trivial, so logically the container should be at least 4L - a volume that would also allow you to carry 400 lighters. No, it should be based more on item count than their volume. Although I am not sure how exactly.

And if this is added, you shouldn't be simply unable to wield items. It should be a total inability to attack. Survivors with good stats and skills don't need weapons for most enemies.

**Comment by TheWebRoamer** [comment]
Good point. To combat this, maybe blanket restrictions on the amount could be set. Let's go off of your example.

A survivor is carrying 5 two-liter bottles around in their arms for total amount of 10L. Let's just pretend that 10L is the maximum amount you can carry. As you said, in theory, this means that the survivor is able is able to hold 1000 lighters which is just... no. So maybe, a blanket restriction can be set for items based on their volume? So if an item's volume is less .25L then a restriction would be put in place, limiting the survivor to only be able to carry a reasonable amount of that item, like  10 15 or 20, etc. The exact amount could be decided later. 

> And if this is added, you shouldn't be simply unable to wield items. It should be a total inability to attack. 

I thought this would probably go without needing to be said. If you were to attack with a bunch of items in your hands, you'd drop them at best.

**Comment by Tatterdemalian** [comment]
> @Tatterdemalian I have extremely basic knowledge of coding but going off what @AdriaanRenting was saying, I feel as though if the player had some sort of unseen storage container that would act as the player's arms, it would work pretty well. I feel like this would be a solution to your proposed problem of only being able to carry one type of item at a time.
> 
> And if the player is utilizing their "arms container" they are unable to wield weapons. And if they attempt to, they could be prompted that if they wield their weapon they will drop what's in their arms. So if a player ends up having to fight, they have to drop everything in their arms. Which by the way, the speed at which a player is able to drop items should be increased because you know, it's in their hands and not a bag or something. However, if the player is hit while carrying items in their arms, make it so there is a high chance of the player dropping whats in their arms.
> 
> If the arms were made into a back up container that is only revealed to the player when their inventory is full, couldn't this arm theory be a simple if statement? Like
> 
> > If inventory is full, prompt player to carry item with their hands/arms. If no, drop item. If yes, stop wielding current weapon/item and prompt player as to what they want to do with it.
> 
> Also, @AdriaanRenting encumbrance wouldn't even be a factor in my suggestion above. Seeing as it would be extremely impractical, if not impossible to do anything with your arms in that state.

This would be the best idea, in my opinion. I don't like the idea of having the "arm inventory" as a hidden back up, though, as players should be able to use it if they want to, instead of bags. Extending the wield menu, so players would have to unwield any weapon they're carrying (and be aware that they're doing so), is still the superior option, again in my own opinion. There should simply be appropriate balancing penalties for doing this, in addition to only being able to use your arm inventory to attack/throw. 

- Volume would only be an issue for extremely large items, because you're essentially carrying them loose in your arms instead of in a container with hard limits on how much it can hold. Say, all players can hold 10L for each arm they have in their arm inventory, plus 1L (to the total, not per arm) for each point of DEX. Total arm inventory volume in dL (volume in L x10) should be added to both arm and hand encumbrances, though, with all related effects.
- Quantity of items should be SHARPLY limited, to 1 item per arm, plus 1 item per point of DEX, again because you're carrying them loose in your arms (this is why bags were invented in the first place). Attempting to pick up more than this, or DEX being reduced to the point where you can't hold all your items, results in the old Infocom inventory message: "You fumble while carrying your ${NAME} and it falls to the ground." Hope the players are alert enough not to miss it!
- Mass of items in the arm inventory should be less than maximum burden, equal to their maximum "bench press" mass rather than maximum "full body lift" mass (10kg + 25kg per point of STR is a decent approximation of human limits). Mass of arm inventory items should be added to the total carried mass for "overburdening," of course, but attempting to carry too much mass in your arm inventory, or having STR reduced to the point you can't carry the weight, again results in a fumble and auto-drop.

Essentially, arm inventory should NOT be a superior alternative to the standard pockets/bags, and should not be forced on players "in secret." It's there if the players want to cripple themselves for a challenge, like nudism.

**Comment by Tatterdemalian** [comment]
> I thought this would probably go without needing to be said. If you were to attack with a bunch of items in your hands, you'd drop them at best.

Depends on how you go about doing it. Shift your inventory so you hold all but one item in one arm while swinging/throwing one item in the other is how I would do it, though there should be increased chance of a fumble when this is done, not to mention the exponentially scaling accuracy penalties I mentioned. Optionally, just shove the whole pile in the enemy's as you body check, or throw them all at once to make a crapton of distracting noises.

**Comment by TheWebRoamer** [comment]
> Quantity of items should be SHARPLY limited, to 1 item per arm, plus 1 item per point of DEX, again because you're carrying them loose in your arms (this is why bags were invented in the first place). Attempting to pick up more than this, or DEX being reduced to the point where you can't hold all your items, results in the old Infocom inventory message: "You fumble while carrying your ${NAME} and it falls to the ground." Hope the players are alert enough not to miss it!

While I agree that there should be limits... again, perhaps the limits should be based on the size of the item. At least to some extent. Because assuming that a player has the default amount of DEX (8), that would mean that the player would be limited to carrying 10 lighters. In real life, as part of an experiment, I was able to carry 8 lighters comfortably in one hand. (dont ask me why i have so many lighters lmao).
I suppose at this point, it becomes argument of game realism vs game balance. How important to the game is it to make the amount of one item a player can hold realistic? Is it worth the extra code? Maybe it would be best to go with your suggestion. I'm not entirely sure, I'm just here to insight discussion. 

> Depends on how you go about doing it. Shift your inventory so you hold all but one item in one arm while swinging/throwing one item in the other is how I would do it

For some reason, that thought didn't even cross my mind. Of course you should be able to designate one arm to carrying items. This could also be a stepping stone to dual wielding, if its ever implemented.

**Comment by Tatterdemalian** [comment]
How about this: instead of always unwielding the item you're wielding when you try to wield another in the wield menu, you have more options:

- Store ${WIELDED_ITEM} in inventory and wield ${NEW_ITEM}
- Drop ${WIELDED_ITEM} and wield ${NEW_ITEM}
- Continue wielding ${WIELDED_ITEM} but carry ${NEW_ITEM} in your arms as well
- Wield ${NEW_ITEM} but carry ${WIELDED_ITEM} in your arms as well
- Cancel

This gives you a primary item you swing, but also the ability to carry more in the new "arm inventory," if you really want to. Again, though, bags and bindles were invented for a reason, and if the player isn't aware enough to notice those reasons appearing in the message logs, it's really going to suck to be them.

Arm inventory appears as its own heading in the inventory menu once the player starts loading his/her arms with extra stuff, and items in it can be wielded, dropped, and thrown like normal, just with penalties to AP based on arm encumbrance. An extra collection of warning messages could be implemented, if you want to be nice and warn players if they're doing something that will result in objects dropping as soon as they exit the inventory window.

**Comment by TheWebRoamer** [comment]
I personally find it extremely hard to not notice new messages in the logs. Especially if they're colored red. And as you said, new warning prompts could be implemented to further warn the player. As it is currently, this covers everything in my head. I can't think of any further problems.

**Comment by Tatterdemalian** [comment]
> While I agree that there should be limits... again, perhaps the limits should be based on the size of the item. At least to some extent. Because assuming that a player has the default amount of DEX (8), that would mean that the player would be limited to carrying 10 lighters. In real life, as part of an experiment, I was able to carry 8 lighters comfortably in one hand. (dont ask me why i have so many lighters lmao).

Have you tried carrying all those lighters while running at top speed, climbing through a window frame, etc? Do any fall out if you move your hand too fast or squeeze them a little too tightly?

> I suppose at this point, it becomes argument of game realism vs game balance. How important to the game is it to make the amount of one item a player can hold realistic? Is it worth the extra code? Maybe it would be best to go with your suggestion. I'm not entirely sure, I'm just here to insight discussion.

Well, there wouldn't be much point to it if it was just a simple "extra inventory space." Like I said, you can just make a mod that gives all players an automatic container, or cheat it on to your characters if you really want to scale the weight/volume limits to the individual's STR/DEX. The system I'm proposing may seem gimped, but the paradigm shift from limited mass/volume to practically unlimited mass/volume but limited quantity could be used (or abused) by a clever player in all kinds of interesting ways. Game-breaking ways? Well, that remains to be seen, and can be fixed afterward or removed outright if abused too egregiously.

**Comment by TheWebRoamer** [comment]
> Have you tried carrying all those lighters while running at top speed, climbing through a window frame, etc? Do any fall out if you move your hand too fast or squeeze them a little too tightly?

I tried quite a bit. I squeezed, whipped my arm around, etc. The only thing that had an effect on my ability to hold those lighters was punching my bed. It ended up loosening my grip on them and 2 of them slipped out of my hand. I imagine it would be worse if I punched something hard but I didn't want to hurt my hand lol.  Other than that though, carrying those lighters was pretty fine.

And no, I think your system is probably the better one, I'm just pointing out that you should probably be able to carry a slightly larger amount of smaller items.

**Comment by Tatterdemalian** [comment]
> I tried quite a bit. I squeezed, whipped my arm around, etc. The only thing that had an effect on my ability to hold those lighters was punching my bed. It ended up loosening my grip on them and 2 of them slipped out of my hand. I imagine it would be worse if I punched something hard but I didn't want to hurt my hand lol. Other than that though, carrying those lighters was pretty fine.

Maybe you have more dexterity than you give yourself credit for? You are right, of course, carrying a really tiny volume, small enough to fit in one hand, would allow you to carry a lot more individual items. Hard to think of a convenient way to do that in code, though, without also sucking away computation time for a whole lot of extra math that wouldn't apply 90% of the time because the player is trying to haul an armload of sticks, instead of a fistfull of sand. Maybe have a hand inventory as well as arm inventory, but the more extra spaces added, the less likely this idea will ever actually be allowed into the master branch.

**Comment by Tatterdemalian** [comment]
Well, it turns out the code already has the ability to wield a full stack of items, but with no penalties or other weaknesses to compensate. This is part of the reason why throwing sticks (from the Extra Survival mod) are OP, you can wield as many of them as you can stack and rapid-fire chuck them at zombies with 100% accuracy, no need to wield them one at a time like rocks.

So, if I do add core code that handles multiwielding by assigning an automatic accuracy penalty, makes you drop items if you try to wield too many, etc. it will add a sudden nerf to throwing sticks, and any other items in any other mods that can be wielded as a stack.

**Comment by TheWebRoamer** [comment]
Is that not a good thing? To nerf OP weapons?

**Comment by Tatterdemalian** [comment]
Depends on what other people are working on, and whether the modded weapons are meant to be OP. I'm continuing with my changes anyway, and will submit them and see what the core team thinks.

**Comment by kevingranade** [comment]
Nothing has come of this, and I'm not at all sure there's a reasonable implementation of this that doesn't cause more problems than it solves.
