### ISSUE TITLE
Disassembling a First Aid Kit nets inconsistent mass and volume than the sum of their parts

### ISSUE THREAD

**Issue by KurzedMetal** [CleverRaven/Cataclysm-DDA#25691]
**Describe the bug**  
Here you have a First Aid Kit and the parts from a second disassembled First Aid Kit.
![20180918_211956](https://user-images.githubusercontent.com/1426680/45723709-0c88b680-bb89-11e8-9ae1-6e014d8a7c68.png)

If you sum up every part, you get a total of 1.63 kg mass and 1.09 L volume, yet the closed First Aid Kit has mass of 1kg and a volume of 1.5 L.

**Expected behavior**  
I was expecting the closed First Aid Kit to have the same or slightly higher Volume, and the same or slighter higher Mass, depending on how good was the packaging.

But I definitely wasn't expecting the closed First Aid Kit to have less mass than the sum of its parts.

**To Reproduce**  
1. Spawn two First Aid Kit
2. Disassemble one of them.
3. Compare mass and volume

**Versions and configuration(please complete the following information):**
 - Game Version 0.C-32214-g0c28494
 - Graphics version Tiles

**Additional context**  
I'm guessing this discrepancy could've been introduced by the recent First Aids re-balance changes.

**Comment by Szara-ManOfHonor** [comment]
I'd expect the kit weight to be slightly more than the sum, and the kit volume maybe  a bit less, due to efficient packaging. Or a bit more or the same in which case there's not much reason to do keep them in kit form. So a bit less just to make it worth it in some way.

**Comment by Theundyingcode** [comment]
I would suggest 1.65kg and 1,1 L or 1.2 L for the packed kit

**Comment by Regularitee** [comment]
From a gameplay perspective, a packed medical kit must be a smaller volume than the sum of its parts, otherwise there is no purpose to the first aid kit itself and players will instantly disassemble them on obtaining one. Especially since, unlike food packaging, they don't serve the role of reducing item stack count as their primary purpose.

**Comment by CoroNaut** [comment]
> From a gameplay perspective, a packed medical kit must be a smaller volume than the sum of its parts, otherwise there is no purpose to the first aid kit itself and players will instantly disassemble them on obtaining one.

Will we ever get backpacks that allow you to condense items similar to the medic kit? -> is my reaction to this statement. If something can be compressed in a kit like this, why not have the ability to compress other things?

**Comment by Regularitee** [comment]
> Will we ever get backpacks that allow you to condense items similar to the medic kit? -> is my reaction to this statement. If something can be compressed in a kit like this, why not have the ability to compress other things?

From a gameplay perspective, backpacks are used for different purposes: they increase total storage volume, not volume efficiency. And further they are re-usable, and can be used to store anything, whereas first-aid kits are not. And furthermore backpacks play a role in setting encumbrance, when taken into comparison with other types of wearable storage.

A first aid kit, on the other hand, can _currently_ serve no other purpose than to reduce volume. (Or, to a far lesser extent, as a weapon and/or a method to carry multiple healing items in your hands slot). 

While I share your enthusiasm for discrete inventories for wearable containers, that's a far larger and complex issue that should be discussed in its own thread.

**Comment by AbsalomAchitophel526** [comment]
There IS no purpose to a first aid kit itself, as most of it's contents are junk.  The booklet will raise your skill enough to make a splint... but doesn't have enough medical tape for one.  Amusingly, using the gauze and bandages it contains will raise the player's skill from 0 to 1 as well.  It doesn't have enough medical tape for ANY recipe... except for bandages, which the Kit already contains.  The player can also just use duct tape in that recipe instead.  Conversely, it has enough gauze for three splints!  Saline Solution is of similar niche use - it can be used in place of salt in some recipes, and can clear your vision in case of a boomer attack, but it's questionable to carry the first one, let alone more.

The First Aid kit is, for the majority of situations, curiously wrapped disinfectant.  The exception will be players who hoard every item they get despite never using them.

**Comment by Theundyingcode** [comment]
I disagree early game, first aid kits are incredibly useful source of materials during the early game before one can readily craft duct tape and stockpile salt water.

**Comment by AbsalomAchitophel526** [comment]
It doesn't have enough medical tape for any useful recipe, and the amount of saline solution in one will cure one hide, but not tan it.

**Comment by FulcrumA** [comment]
I also disagree here. First aid kits make pretty convenient set of tools for the most common non-severe injuries as well as come with very simple, basic booklet to give one that first level of first aid which, sure, isn't that hard to get other ways nowadays but may still be useful. I find the item quite valuable even when non-vital.

> The booklet will raise your skill enough to make a splint... but doesn't have enough medical tape for one.

The splint you learn as part of the autolearning due to getting high enough level of skill, assuming you also have the other skill necessary for splints (survival, I believe). The recipe isn't taught by the book itself and thus we can safely assume that splints were not meant to be part of the kit nor should the kit itself strive to provide resources to make some.

>It doesn't have enough medical tape for ANY recipe... except for bandages, which the Kit already contains. The player can also just use duct tape in that recipe instead. Conversely, it has enough gauze for three splints!

The tape isn't included with thought of any particular recipe non-basic recipe in mind and it shouldn't be, from both the standpoint of balance and fluff consideration, because I doubt people stocking those were thinking "did we include enough of medical tape in our first aid kits to allow people to make improvised welding goggles?".

>Saline Solution is of similar niche use - it can be used in place of salt in some recipes, and can clear your vision in case of a boomer attack, but it's questionable to carry the first one, let alone more.

Again, you think of it as if first aid kits would be made with how applicable they are in in-game situations considering in-game mechanics. No, they're made with resources that normally can be found in first aid kits to treat believable, "regular civilized life" injuries. No "boomer attack" or "so you can craft some stuff" but "for cleaning that knee scrape your kid may get in the playground".

Lastly, this ticket is not to address viability of first aid kits, but merely the mass/volume dissonance of packed and unpacked kits of this type.

**Comment by Kelenius** [comment]
Toolboxes are smaller than their components combined.
