### ISSUE TITLE
Zweihander should require two hands to wield

### ISSUE THREAD

**Issue by AbsalomAchitophel526** [CleverRaven/Cataclysm-DDA#25743]
**Describe the bug**  
The zweihander does not require two hands to use.

**To Reproduce**  
1.) Obtain Zweihander
2.) Wear anything that requires a hand, e.g bindle or briefcase.
3.) Wield Zweihander without any trouble

**Expected behavior**  
"Zweihander" means 'two hander.'  The in-game description calls it a two handed sword.  It should require two hands.

**Comment by Regularitee** [comment]
Ideally, there would be some sort of strength check for one-hand versus two-hand usage for certain weapons. Though I don't know how hard that would be to make.

**Comment by Regularitee** [comment]
Your viewpoint seems a bit too narrow, too focused on conventional human precedent. Players can achieve unbelievably high attributes through bionics, mutations, and stats-through-skills. So while it may not be realistic for a person to wield a weapon this way, it is feasible in-game with the strength levels achievable.

While you or I may not be able to swing a mop like in your example, I'm pretty sure a 25 strength monstrosity could. Especially if grip strength is correspondingly powerful, which could counter-act the effect of having a farther center-of-gravity on a weapon.

Though I guess this is kind of going off-topic, since multi-handed weapons should be its own issue, not a sub-topic in a bugfix thread.

**Comment by Leland** [comment]
Renamed for future visibility (my condolences – original title is definitely awesome)

**Comment by DemAvalon** [comment]
Shouldn't this get closed?

**Comment by Night-Pryanik** [comment]
Why? The issue is valid and isn't resolved yet AFAIK.

**Comment by aierce** [comment]
This should be closed. The linked proposed fix is rejected because people there decided it's a feature not a bug.

**Comment by kevingranade** [comment]
The sources cited in that PR absolutely support that meaningful use of a two-handed weapon requires use of two hands.
