### ISSUE TITLE
Various foods need their rotting time revisited

### ISSUE THREAD

**Issue by Regularitee** [CleverRaven/Cataclysm-DDA#25740]
... especially in consideration of the fact that 90 day seasons are the norm, not 14 day seasons. Some examples I've found include:
- Hamburger helper: 10 hours
- Hobo Helper: 10 hours
- Eggnog: 8 hours
- Nachos with meat and cheese: 20 hours
- Nino Nachos with cheese: 20 hours

There are many, many other foods which only have a 1 day expiry period which may need to be revisited and a new minimum rotting duration set. Very few modern foods become inedible if left on the counter for a full day.

**Comment by Lorith** [comment]
Also, nothing lasts over three seasons.  Pasta and rice sitting in my garage are good for significantly more than three seasons.

**Comment by nexusmrsep** [comment]
Already done here #23986. Assumption that food shelf life is based on 15 days seasons is simply false.

@Lorith  you misinterpreted game mechanics. Shelf life is measured in room temperature. Put your food in a basement or root cellar and you'll get it's life span equal to your garage pasta. Since that might get confusing, @MT-Arnoldussen  is working on a PR that would give some more info on food expected expire rate.

**Comment by kevingranade** [comment]
The existing spoil times are not based on 14 day seasons.
None if your examples seem off to me.
We arent reopening the discussion from the previous issue, the goal is basing spoil times on highly suboptimal conditions present in the cataclysm, not based on anecdotes about spoil times of contemporary foods in contemporary storage conditions

**Comment by Regularitee** [comment]
@kevingranade 
I'd disagree. Raw meat rots in 24 hours. Cooked meat rots in 24 hours. Cheese many times more. Why does combining (hamburger helper) them accelerate rotting rate? Especially when in comparison to raw meat.
