### ISSUE TITLE
Getting temporarily stuck in counterattack when using certain martial arts.

### ISSUE THREAD

**Issue by Sorgklaan** [CleverRaven/Cataclysm-DDA#25859]
https://cdn.discordapp.com/attachments/252368751016542218/494683604690141194/2018-09-26_21-32-54.mp4

This is something that has been in the game for a while. I'm not sure if it's as much of a bug as it is just... An oversight?

You can get stuck in a counterattack wherein you will continue to be attacked and counterattack until either all enemies are dead, or you die. This is especially a problem if you have lower speed.

Just grab dragon kung fu, lower your speed with debug near a group of enemies, and watch.

Counterattack is powerful, but the current behavior makes playing with a martial art that uses counterattack incredibly risky, and any risky encounter is all or nothing because of it.

**Comment by Siyalatas** [comment]
I thought this issue was 'fixed' once the move cost of counter attacks was reduced to zero. Of course, this introduced another issue, since counter attack techniques seem to go off even on regular hits, causing certain martial arts, notably Zui Quan, to have strings of several hits for no move cost at all.

It seems your problem is tied not to counter attacks specifically, but to misses due to your encumbrance, since missed counter attacks still cost move points, and a lot of them if you're heavily encumbered. I suspect this will not be worth trying to fix on its own, but should rather be addressed at such time when melee gets a full blown overhaul.

**Comment by kevingranade** [comment]
The plan for fixing counters is to remove the automatic aspect of them,
instead providing a bonus to a subsequent attack against the attacker, then
they wont automatically drain your move points.

**Comment by ZhilkinSerg** [comment]
Should be probably addressed during #32422
