### ISSUE TITLE
Amount of Mandatory Overmap Specials is too low

### ISSUE THREAD

**Issue by dissociativity** [CleverRaven/Cataclysm-DDA#25895]
**Describe the bug**  
So we've had quite a few new locations including overmap specials merged into the base game and/or it's accompanying mods lately, I propose that we increase the limit by about 10, although 5 would likely suffice.

That or allow mods to specify it.

**To Reproduce**  
Start new world with all location mods except urban development enabled
Use PK rebalance too, which doesn't add many extra specials
Usually result in having too many specials, sometimes not.

**Expected behavior**  
This would only previously happen if we were to use urban development.

**Screenshots**  
I think everyone that's played the game has experienced this at least once

**Versions and configuration(please complete the following information):**
 - OS: Windows 8.1 and 10 x64
 - Game Version latest commit as of this post, my self-compiled compiled builds don't seem to like giving me a coherent version
 - Graphics version: Tiles
 - Mods loaded: All vanilla location mods except Urban Development, my patched PK rebalancing version
**Additional context**
Not sure any more is necessary.

**Comment by Theundyingcode** [comment]
>  Longer term mods shouldn't be able to mark specials as mandatory at all.

Rather than preventing mods from marking things manditory wouldn't it be better to make mandatory status a function of starting scenarios?  The only true reason I can see to require a special is if you are supposed  to be starting there.  If scenarios mark what is mandatory, you can avoid the issues with too many mandatories while ensuring that the necessary starting locations get placed.

**Comment by kevingranade** [comment]
That's what I mean.  Clearly we can't trust mod authors to do it manually,
so it needs to happen automatically if a starting scenario or mission
requires it.
