### ISSUE TITLE
Taming Hallucination uses up the item

### ISSUE THREAD

**Issue by EirenexTheDragon** [CleverRaven/Cataclysm-DDA#25907]
**Describe the bug**  
You can tame Monsters that appear in hallucination, despite being nonexistant. they still dissappear, eating with the food you used to tame them. 

**To Reproduce**  
1. Debug in a Dog (any, just be sure to add the hallucination on it when spawning.)
2. Debug in some Dogfood
3. activate the dogfood on the Dog .

**Expected behavior**  
The Dogfood should not be used up at all. maybe give a funny reaction when trying to tame a fake animal.

**Screenshots**  
![grafik](https://user-images.githubusercontent.com/41762755/46258346-5ba7e300-c4c9-11e8-97ed-c24aa65811ae.png)

**Versions and configuration(please complete the following information):**
 - OS: Windows 7
 - Game Version Most Current
 - Mods loaded: Standard

**Additional context**  
This might also be the issue with cats and other animals that can be tamed with their respective taming food.

**Comment by cake-pie** [comment]
Can confirm, tested with cow and cat:
![tamehalluc](https://user-images.githubusercontent.com/28502722/46311602-55af2080-c5f5-11e8-9570-cdb7f7d08413.png)

Though I can also see this as a feature rather than a bug. Who knows what you actually did with the food when trying to interact with a hallucinated animal? Whatever happened, that food is gone now.

If this is changed so that the food is not consumed by the taming, my concern is it would become a test for hallucinations. Unless you also hallucinate that the food gets consumed, and it reappears in your inventory when the animal disappears?

**Comment by Theundyingcode** [comment]
I second the idea of the food should be lost or else be exploitable but, at the same time I definitely agree that hallucinations eating food is ridiculous. 

Maybe change the  message for taming hallucinations to be something like "The __tamable__ makes a mess eating the __food__.  Nevertheless, it seems to be really happy and rubs its head up against you."
