### ISSUE TITLE
CTD when trying to use bike rack.

### ISSUE THREAD

**Issue by tinukedaya** [CleverRaven/Cataclysm-DDA#25906]
**Describe the bug**  
When trying to rack vehicle with more than 11 parts the game stops working.

**To Reproduce**  
1. Check attached save, strip random parts from the bike on the right side of the vehicle to only contain 11 parts.
2. Rack the bike, observe that it's working
3. unrack and install one random part back.
4. Rack the bike, observe your desktop.

**Additional context**  
Must be somehow connected to the main vehicle, because if I spawn the default SUV with bike rack the same bike connects as intended. 

[Lake Andes.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2431544/Lake.Andes.zip)

**Comment by alanbrady** [comment]
In my testing I wasn't able to repro after #26039, but it was kind of finicky to repro without the fix.  There was also a user on discord who reported crash when racking bike which was fixed after #26039, so I have a fairly high degree of confidence it is fixed now, but do please reopen this if it's not fixed. (note #26043 will actually close it since I missed this bug when doing #26039, but I've now tested it and it seems to be fixed).
