### ISSUE TITLE
Feature Request: "Attack Only Zombies" Follower Mode

### ISSUE THREAD

**Issue by GearheadLydia** [CleverRaven/Cataclysm-DDA#25917]
In Cataclysm, one of the more exploitable situations is the existence of monster factions, where monsters can attack each other based on what type they are. It can be a pretty useful strategy, for instance, to lure zombies into attacking a moose or cougar.

However, your followers may ruin this by shooting the cougar / moose / other interloper, which means that the zombies just got that much more threatening.

Would it be possible to create an "only attack zombies" combat option for followers? Alternatively, could there be a blacklist/whitelist function for what your followers will attack?

**Comment by mlangsdorf** [comment]
NPCs choose their target in npcmove.cpp:choose_target(), and skip monsters with att == MATT_FRIEND or MATT_FPASSIVE. An additional check to skip whitelisted or blacklisted monsters by faction would be straightforward codewise (I think), but might have performance concerns.

NPCs get the dialogue options to set their combat commands in npctalk.cpp:dynamic_line() and npctalk.cpp:gen_reponses().   A structure similar to np.rules.pickup_whitelist would need to be added to handle manipulating the target whitelist/blacklist.

**Comment by kevingranade** [comment]
Toggling aggression vs factions would be simple, togglingvagression vs
individual monsters would be slightly harder.

**Comment by paulenka-aleh** [comment]
Well, my survivors did quite the opposite from time to time, in early game, e.g. running from a fast pack of wolfs or coguar to locations with some zombies (normally aren't that fast). Same way as a bear could be used to kill a a few dozens of zombies you wouln't want to deal with otherwise a pack of proper ones (e.g. spitters) can be used to deal some damage to the bear to kill it easier.

The only way I see to allow it are shout commands to NPCs like "Focus your fire on that monster" and "Don't fight this monster".
