### ISSUE TITLE
"duplicate bionic id"- moving from 7982 to 7998

### ISSUE THREAD

**Issue by evankimori** [CleverRaven/Cataclysm-DDA#25935]
**Describe the bug**  
On loading save:
 DEBUG    : duplicate bionic id
 
 FUNCTION : void load_bionic(JsonObject&)
 FILE     : src/bionics.cpp
 LINE     : 1451

**To Reproduce**  
Saved in last used client version 7982 and loaded 7998 and error appeared.

**Additional context**  
CURRENT MODS:
  "dda",
  "craftgp",
  "safeautodoc",
  "brightnights",
  "StatsThroughSkills",
  "manualbionicinstall",
  "more_classes_scenarios",
  "bio_mod",
  "realguns",
  "makeshift",
  "More_Survival_Tools",
  "alt_map_key",
  "crazy_cataclysm",
  "mutant_npcs",
  "boats",
  "deoxymod",
  "necromancy"

Game also freezes on attempting to Sleep after using [I]gnore on error message with excessive slowdown on crafting with CTD when whitescreened.

Savegame attached.

[Crazy Test.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2435544/Crazy.Test.zip)

**Comment by eturner** [comment]
Should there even be reports for bugs that occur after updating the game with an old save?

**Comment by kevingranade** [comment]
Yes, we intend for updates to work.

**Comment by Siyalatas** [comment]
#25369 

There's your problem. You probably just want to delete `bio_mod` from the world's modlist and you should be fine.

If I understand the code right, mods marked as obsolete aren't loaded, and bio_mod has been marked obsolete in the given PR. You probably copied the mod from an old version though, and that's why you got this problem. There really isn't much we can do to prevent an error if you don't update all the way through, so if I am correct in the assumption, this one is a non-issue.

**Comment by evankimori** [comment]
> #25369
> 
> There's your problem. You probably just want to delete `bio_mod` from the world's modlist and you should be fine.
> 
> If I understand the code right, mods marked as obsolete aren't loaded, and bio_mod has been marked obsolete in the given PR. You probably copied the mod from an old version though, and that's why you got this problem. There really isn't much we can do to prevent an error if you don't update all the way through, so if I am correct in the assumption, this one is a non-issue.

Thanks for the quick reply. The system for this particular save, I cant use the Loader to install new releases due to proxy blocks on Internet access but I'll keep adding in any bugs I find with this different system setup - seeing that all I can do to install new releases is to Overwrite on extract. Would this data be of any use going forward or should I just move Save and Config folders across with new PR?

**Comment by narc0tiq** [comment]
> mods marked as obsolete aren't loaded

Actually, it looks like the way to get the obsolete mod removed from worlds is to add the mod to `data/mods/replacements.json`: <https://github.com/CleverRaven/Cataclysm-DDA/blob/a44e1cdc0720079e3a1c29875c34f857b83c20aa/src/mod_manager.cpp#L423-L427>

Setting `obsolete:true` will remove it from the available mods list when creating a new world: <https://github.com/CleverRaven/Cataclysm-DDA/blob/a44e1cdc0720079e3a1c29875c34f857b83c20aa/src/mod_manager.cpp#L455-L460>
...but the `obsolete` member of the mod info is not otherwise checked, that I could tell on a quick search.

**Comment by Soyweiser** [comment]
#26388 fixes the missing bio_chest_gun bionic definition.
