### ISSUE TITLE
Should a copper pot burn/melt?

### ISSUE THREAD

**Issue by keisetsu** [CleverRaven/Cataclysm-DDA#26042]
**Describe the bug**  
When a copper pot is on an oven and a fire is started in the oven, the copper pot burns and is consumed.

**To Reproduce**  
1. Have a copper pot on an oven
2. Drop/move wood into the oven
3. Light the oven with matches or a lighter
4. The pot starts burning, then is consumed.

**Expected behavior**  
The pot should not be consumed, like the aluminum(?) pot.

**Screenshots**  
#### Just after the fire is lit
![screenshot_20181003_202218](https://user-images.githubusercontent.com/5448338/46448126-f400ca80-c74a-11e8-9bc5-4065b41e46c3.png)
#### A few minutes later
![screenshot_20181003_202720](https://user-images.githubusercontent.com/5448338/46448127-f400ca80-c74a-11e8-826c-27a4c372fc44.png)
#### Then the pot is gone (no screenshot)

**Versions and configuration(please complete the following information):**
 - OS: Manjaro Linux
 - Game Version: Sorry, haven't figured out how to get the version from the game. The main screen just says 0.C, but this is a version compiled from source yesterday (2018/10/02)
 - Graphics version: Tiles
 - Mods loaded: DDA, filthy clothes, dinosaurs, z-levels
**Additional context**  
None

**Comment by NotFuji** [comment]
Woodburning fires can exceed the melting point of copper, while stove-tops copper pots are meant to be used on aren't nearly as hot.

Keep in mind putting your pot directly on the fire tile is assuming you're putting it right on top of the fire, not above it on a pot hanger or something.

Shouldn't burn though, that's not right.

**Comment by keisetsu** [comment]
I don't totally understand the thinking behind fires in ovens (perhaps they are built at the bottom of the oven and pots/kettles sit on a rack or something?), but in the past copper pots were not destroyed.

**Comment by kevingranade** [comment]
While in theory copper can be melted by a wood fire, to have a reasonable chance of it actually happening you need charcoal and enhanced airflow and a crucible, because otherwise the flame is unlikely to be hot enough, and the pot is too good at shedding heat.

I also don't think that's what's happening here anyway,this definitely sounds like a bug.

**Comment by keisetsu** [comment]
I should mention this also happened in a version compiled a couple of weeks ago. Sorry I don't have the version information.

**Comment by cake-pie** [comment]
Not limited to oven, here's one burning in a brazier:
![burn-copper-pot](https://user-images.githubusercontent.com/28502722/46449400-69f24980-c7be-11e8-9527-c94bbde6f9c1.png)

I've tested a254c49aa6dba674dc8b0e37cff8fd6d7b12f9fe and the issue is present, which rules out regression caused by the recent change adding insulation to ovens.

**Comment by FulcrumA** [comment]
Has to be also pointed out that even on a stovetop, a pot - and not only a copper one - left for long enough over a continuous source of heat may be damaged/ruined (thus explaining the burned tag).

**Comment by ituluwituluwzev** [comment]
Whether copper melting is desired effect or not, this works in unintended way.

I also think that copper should be damaged by fire, but the process should be much slower than wood.
