### ISSUE TITLE
Mapgen error: tried to generate map for omtype (PR 8029)

### ISSUE THREAD

**Issue by evankimori** [CleverRaven/Cataclysm-DDA#26143]
**Describe the bug**  
 DEBUG    : Error: tried to generate map for omtype , "nothing" (id_mapgen )
 
 FUNCTION : void map::draw_map(oter_id, oter_id, oter_id, oter_id, oter_id, oter_id, oter_id, oter_id, oter_id, oter_id, oter_id, const time_point&, float, int, const regional_settings*)
 FILE     : src/mapgen.cpp
 LINE     : 6519

**To Reproduce**  
Savegame attached for reproduction. Overmap shows "%nothing" generated as a point. On attempting to approach: the above error is produced when reaching close to the site. Screenshot below shows the result. No building is generated aside from the wooden floor and an over-shadow. Tiles count as floor but no roof.

**Expected behavior**  

**Screenshots**  
![weird](https://user-images.githubusercontent.com/43046067/46681282-e919c000-cbb8-11e8-83ca-8d48cea620f8.png)

**Versions and configuration(please complete the following information):**
Game PR 8029 version.

MODLIST: 
  "dda",
  "craftgp",
  "safeautodoc",
  "brightnights",
  "makeshift",
  "More_Survival_Tools",
  "modular_turrets",
  "Salvaged_Robots",
  "crazy_cataclysm",
  "alt_map_key",
  "Mining_Mod",
  "boats",
  "deoxymod",
  "necromancy",
  "no_rivtech_guns",
  "no_olg_guns",
  "no_flaming_weapons",
  "no_medieval_items",
  "more_classes_scenarios",
  "manualbionicinstall",
  "sleepdeprivation",
  "StatsThroughSkills"

**Additional context**  
[Crazy Test 2.0.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2461125/Crazy.Test.2.0.zip)

**Comment by ralreegorganon** [comment]
I think this is basically a non-issue / working as intended.

What is happening here is that an overmap was generated which included a particular overmap_terrain type, and then subsequent to that but prior to entering the vicinity of that overmap terrain location, that overmap_terrain definition was removed.

When the game attempts to load the overmap, it will provide an error message of the form `Loaded bad ter! ter **name_of_overmap_terrain**`, which is its indication that this has occurred. It will then treat that entry as the **nothing** overmap_terrain. 

Later, when the player gets close enough to the location to cause mapgen to occur, the game will attempt to do mapgen for the **nothing** entry, which triggers the error listed in this bug report: `DEBUG : Error: tried to generate map for omtype , "nothing" (id_mapgen )`.

This is all functioning as expected, and the actual issue here is the removal of an overmap terrain which was included in the overmap at generation--the most common source of that being removing or updating mods for an existing save game: even seemingly innocuous changes like a mod renaming one of its existing overmap terrain ids to fix a typo will cause errors for existing save games that have references to it.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
