### ISSUE TITLE
Excessive yield of nails from cabin rubble

### ISSUE THREAD

**Issue by boydkr** [CleverRaven/Cataclysm-DDA#26162]
**Describe the bug**  
A collapse porch and corner of a cabin in the woods yielded almost 9000 nails.

**To Reproduce**  
1. Find cabin innawoods
2. Look for rubble
3. clear rubble

**Expected behavior**  
I would expect there to be maybe a few hundred nails, in the rubble

**Screenshots**  
![excessive_nails](https://user-images.githubusercontent.com/5815066/46754658-99a2c500-cc88-11e8-9bdf-b82bd1c5d1f2.PNG)

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.C-33196-g90d0a9b
 - Graphics version: Tiles
 - Mods loaded: Makeshift items, more survival tools, extended buildings

**Comment by kevingranade** [comment]
An exaustive 5 minute search yielded this source
https://www.manasquanfasteners.com/decking_and_fastener_blog_5 which says
350 nails per 100 square ft of deck, putting one tile of porch at a square
meter puts the approximate number of nails at 35 per tile of porch.  That's
an extreme low estimate for house rubble though, since it will usually have
a lot of nails in walls, ceiling and roof as well.

**Comment by Xion350** [comment]
That assumes that most of the nails are usable.  Which I highly doubt they would be after being used in construction and torn apart.

**Comment by Rivet-the-Zombie** [comment]
I'd expect the heat of the fire to ruin some of the nails' temper, rendering a great many of them too soft to effectively reuse for their intended purpose.

**Comment by FulcrumA** [comment]
I am really ambivalent toward the whole thing. In many cases it'd require a really strong fire to render a nail completely unsuitable rather than just somewhat less dependable while still useful. If we also count loss of nails from walls and ceiling as how @kevingranade mentions, the number of usable ones that can be retrieved doesn't strike me as so weird. IRL the biggest issue likely wouldn't be number of nails that could be retrieved from a fire, but having to look through the rubble to retrieve them.

I guess to not have to track quality of every nail, one could code it in a way that "raging fire" on a tile would have a chance to damage nails as well if maintained long enough (ensuring fire temperature above resistance of iron material?) but it probably shouldn't go beyond that.

**Comment by boydkr** [comment]
I think the issue is that the nails are somehow being added by count instead of by charges:

https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/map.cpp#L2409

**Comment by kevingranade** [comment]
yea the retrieval rate is a bit of a side-track, it looks like it's dropping hundreds of nails per tile instead of dozens.
