### ISSUE TITLE
Fire extinguishers are useless - improvement suggestion

### ISSUE THREAD

**Issue by FulcrumA** [CleverRaven/Cataclysm-DDA#26200]
**Is your feature request related to a problem? Please describe.**  
Currently fire extinguishers are absolutely unsuitable to contain anything beyond the smallest of fires. They work by snuffing fire on the tile they're used on, but in case of any fire just big enough to spread there's no guarantee the location won't start burning again a turn later.

Fire extinguishers in general are much weaker and much more useless than they should be.

**Describe the solution you'd like**  
I believe a good and relatively simple way to improve the situation would be to mimic behavior of even simple extinguishers IRL. 

First, an extinguisher should be of somewhat area of - and short range effect, not very unlike a flamethrower. Each hit by the extinguisher spray could decrease fire by two levels (so 'fire' and 'small fire' would be extinguished immediately, but 'raging fire' would require a couple of applications). Secondly, I'd propose for the extinguishing chemical to stay on every tile affected for a number of turns (like a regular puddle, perhaps?) to prevent reignition.

**Additional context**  
If we assume that each area spray would take 1 ammo, extinguishers should probably by adjusted so small ones have about 3 units of ammo and big ones about 10. Possibly making extinguishers work and behave like guns (requiring one to be wielded and fired rather than used) would add to consistency.

**Comment by cake-pie** [comment]
Proposed solution: Model extinguisher spray as a field of extinguishant, which spreads slightly, thus suppressing fire in an area rather than a single tile.

**Comment by nexusmrsep** [comment]
Idea for how it can be achieved: Fire is emitted field of different types each with a 3 possible levels. CO2 or whatever fire retardant is used in fire extinguisher could be possibly also emitted as a field (short lived white cloud with the ability to spread a bit) that directly contradicts fire fields and either removes their levels, downgrades them and eventually completely removes them. It would use it's own 'power', so one level of extinguisher cloud could extinguish 1 level of fire. Interactions between fields can be coded in `fields.cpp` and it would possibly be a place for some other side-effects or uses of that. In RL extinguishers cannot put out bigger fires, but that can be balanced by extinguishers capacity. and how it relates to emitted cloud.

**Comment by Regilith** [comment]
I'm playing around with an idea about making non-spoiling freezedried foods using dry ice as a craftable alternative to irradiated foods, and a way to easily make dry ice IRL is by shooting a CO2 fire extinguisher into a burlap bag.

I ran into the problem of justifying it's inclusion, as realistically, the processed food would need to be in a bag to stay non-spoiling, and there are many easier ways to preserve food such as canning and vacuum sealing. The end product would be lighter, but it's comparatively much more expensive.

I also couldn't find a good way to form a crafting recipe, as realistically it would take 6 hours of sublimating in a cooler. Timed recipes like tanning is handled could work, but I would need to abstract the freezedried foods into "freezedried fruit", "freezedried vegetables" etc to keep from bloating the crafting menu.

I think it would be handled much better once we are able to store solids in containers and use them for crafting, and the possible use of (freezedried), (irradiated), (smoked), (dehydrated) flags to foods, modifying their properties, so that we wouldn't need a whole new list of foods for each possible preservation method.

**Comment by Regilith** [comment]
@nexusmrsep 

>Freeze-dried food are compared to dried food of the same type as far as shelf life is concerned.

No, not really. Dehydration removes about 90-95 percent of the moisture content while freeze drying removes about 98-99 percent, which matters a lot in terms of shelf life. When sealed, freeze-dried lasts essentially indefinitely, which cannot be said for foods dehydrated via heat. Freeze-drying also has numerous other benefits over regular drying/dehydrating. https://www.thereadystore.com/food-storage/8376/dehydrated-vs-freeze-dried-food/

>Freeze-dried food would need a special equipment

That's the preferred method, but you can certainly freeze-dry foods DIY style with a cooler and dry ice https://besurvival.com/guides/how-to-freeze-dry-food-with-and-without-a-machine 
https://authorizedboots.com/2015/10/how-to-freeze-dry-food-at-home/ 
https://www.wikihow.life/Freeze-Dry

> Vacuum-sealing is in fact a form of in-game freeze drying.

The end products of vacuum sealing don't reflect this, either in their spoilage times upon unsealing, their weights, their quench values, or their descriptions, so I believe you are wrong on this. 
"Fruit slices soaked in a sugar syrup, to preserve freshness and appearance." 
"Vegetable chunks pickled in a salt bath. Goes well with burgers, if only you can find one." 
http://cdda-trunk.chezzo.com/apple_vac
