### ISSUE TITLE
 Mod Inclusion Project: Filthy Clothing

### ISSUE THREAD

**Issue by DracoGriffin** [CleverRaven/Cataclysm-DDA#26228]
Use the following issue as a space to discuss the inclusion of:

Mod Ident: Filthy_Morale
Name: Filthy Clothing

Your comment should include:

### Suggestions for induction
(what parts of the mod should be included, can be as simple as just an item, a location or the complete inclusion)

### Incompatibilities
(what parts of the mod should not be included, either some objects / items or entire mod is conflicting with DDA theme [ for whatever reason ])

---

edit:

Based on feedback, complete induction is warranted.

- [ ] - Add filthy clothes as default behavior.

**Comment by Rivet-the-Zombie** [comment]
I'm all for including this in the base game.

**Comment by Reclusive-reptile** [comment]
Laundering clothing is a lot less tedious than it used to be. There really isn't a reason why this should not be default behavior now.

**Comment by tyrael93** [comment]
Don't even think about it.

**Comment by tyrael93** [comment]
>Official repository jester here.

Don't be so hard on yourself kevin, we know you're a valuable member of the project. You're much more than that.

Anyway when we're done with the preschool banter: this is gonna get merged no matter what, so at least have the decency to add a mutation that's the opposite of squeamish that lets you wear filthy clothing. I know you guys like your tedium well done but try to think for the rest of us too.

**Comment by nexusmrsep** [comment]
> the objection to it is that that leaves some items too-rare.

From my personal experience if I found a dirty item that I cared about I simply tried to wash it. That, depending on RNG circumstances, sometimes was a fun mini-quest of its own. Never had I any feeling of it being impeding of getting any items because of their dirtiness, with one exception - en-mass resource harvesting for crafting, but with newly added batch cleaning, washing machines etc. even that is not a huge problem anymore.

> at least have the decency to add a mutation that's the opposite of squeamish that lets you wear filthy clothing

And /  Or hobo trait for the hobo scenario, nice idea!
And perhaps a reverse only-clean-clothes mod after merging for those few casual players.

**Comment by FulcrumA** [comment]
I am absolutely for filthy clothing mod and considered it kinda a basic thing, wondering why it's not yet integral part of the game especially since there seems to be even recipes using the filthy tag. It's relatively easy now to clean filthy items too so assuming one isn't compulsively gathering whole tons of filthy items and expecting them to be cleaned just like that - it shouldn't be too much of an issue (and let's be honest, allowing making huge amounts of item clean easily would kinda make the whole tag pointless).

I don't think that adjustments of traits is much necessary either. Filthy clothes provide a bit of additional risk of infection upon being injured and some morale penalty which can easily be countered. The former shouldn't be counteracted by any particular trait sans ones revolving around resistance to infections, while the latter, as just mentioned - isn't much of an issue.

In spirit of letting the players who really hate the thing to have their own way and mod game to their liking, being able to put on clothes moments ago worn by blood and filth-covered, reanimated corpse without any issue - sure, some mod disabling the filthy tag could be handy.

**Comment by Inglonias** [comment]
PR #26322 is related to this. It moves the filthy item logic into JSON, allowing someone who wants to mod filthy clothes out if this gets merged into the base game to do so with JSON edits only (provided further tweaks are made so that the ONLY thing that determines if clothes drop filthy is the presence of the new flag)

**Comment by Soyweiser** [comment]
Btw, my PR is only intended to have a specific flag for monsters to drop filthy clothings, it is intended to be in addition to the zombie/fungus monsters dropping filthy clothing. Ideally (my pr isn't intended to be perfect) you would have both tags on species that makes an entire species filthy, and on the monster level flags that force filthy/non filthy. (Will add a 'force non filth' flag to the pr).

**Comment by DracoGriffin** [comment]
@Soyweiser if you'd like to do a follow-up PR that essentially merges Filthy Clothing and then detail the NOT_FILTHY flag, that'd be great. Based on the feedback, I think this one should be inducted.

If not, I can leave this open for another brave soul.

**Comment by Soyweiser** [comment]
I changed the PR I made so it only has the FILTHY tag, removed the species requirement, and went over all the monsters and added the FILTHY tag to the fungal/zombie types.

**Comment by DracoGriffin** [comment]
So I'm going to leave this one open as I'm not entirely sure #26322 has the influence on this issue as I initially believed.

**Comment by Night-Pryanik** [comment]
Will just removing morale penalty and a chance to get an infection suffice for a No-Filthy mod? Or it is required to remove `(filthy)` tag and brown color as well?

**Comment by DracoGriffin** [comment]
> Will just **removing morale penalty** and a **chance to get an infection** suffice for a No-Filthy mod? Or **it is required to remove `(filthy)` tag and brown color** as well?

I think inversing the current mechanism of the mod would be the ideal.

That is, No Filthy mod would yield no filthy clothes, would not affect morale and lastly, would not affect infections when hit.

Basically, I bolded the part of your statement that best fits.

**Comment by Night-Pryanik** [comment]
Just wanted to mention that removing only morale penalty and chance to get infected is super easy and require any code editing, just json. Removing filthy tag and brown color will require some additional code editing.

**Comment by ifreund** [comment]
Should be quite simple code editing, nothing more than adding or expanding a conditional in 2 places.  I may do this when I get around to it.

**Comment by Night-Pryanik** [comment]
I don't say it's hard or anything, just an observation. 

I planned to do it myself, but ok, feel free to implement it.
