### ISSUE TITLE
play music in real world when listening to music in game

### ISSUE THREAD

**Issue by Heaper327** [CleverRaven/Cataclysm-DDA#26255]
(sorry about any bad grammar)

**Is your feature request related to a problem? Please describe.**  

No

**Describe the solution you'd like**  

Plays music - probably music clips from sound pack - when listening to music in game

**Comment by FulcrumA** [comment]
I am unsure what do you mean - do you request a feature for a soundpack to play some music when in-game item, like mp3 player is activated? If so I am very reluctant about this. In-game mp3 player can be left turned on for a long time but ILR I'd be bothered having to listen to some piece of music whenever my character is. When I want to listen to some music IRL, I'd prefer to turn some track I'd prefer on my own, without having to listen to random in-game tunes playing at the same time.

I guess it could be an option, but not only it's very unlikely that the fluff message would synergize with the track (as the former is random and changes semi-randomly as well) I'd need an option fo disabling such a feature altogether if it'd be ever introduced (for example, by making it fall under music rather than sound effect slider) as I am often already listening to things of my choice when playing the game.

**Comment by Leland** [comment]
> for example, by making it fall under music rather than sound effect slider

Yes, I think that would be expected.

I'd envision fading out the standard game music and playing a song specific to what's being played on the MP3 player.

**Comment by Drakasin** [comment]
*Royalty free ukulele starts playing on repeat*

**Comment by nexusmrsep** [comment]
Sounds are important part of game, so I support this idea. Time passes quickly in game so it would be awkward to add a sound for each "play" displayed, but maybe adding infrastructure for a few optional royalty free sounds for each instrument wouldn't be a bad idea overall?

**Comment by Drakasin** [comment]
Then maybe instead of entire songs just a note or chord of the specific instrument that occurs in the logs, like "You hear a sweet bass guitar" and you'd hear a short, royalty-free note or chord of a bass guitar.
