### ISSUE TITLE
Wilderness start almost impossible now..

### ISSUE THREAD

**Issue by Treah** [CleverRaven/Cataclysm-DDA#26266]
1. You are unable to thaw food even when its next to a fire. If your not going to implement heat near a fire then make it an action to fix this that does not require a tool. There is no reason a tool is needed at all... This makes no sense from a game play or realism standpoint.

2. Can no longer cut long grass unless you have a very special tool, the Sickle? What and WHY change this? Again makes little to no sense from a game play or IRL standpoint. You can cut grass with pretty much anything sharp or just your hands. This prevents placing down brazier or clearing an area to make it somewhat safe for a fire.. 

3. Salt gets into the frozen state.. Pretty sure its frozen normally on earth. 

4. Sleeping no longer cancels and makes no sense. You can literally "TRY" to sleep till you die... This make 0 sense why it was changed. You should still have the pause after a failure or make it a toggle. Also it only ever checks the first attempt cause my char went into the dead tired state while still trying to sleep....

**Comment by kevingranade** [comment]
One problem per issue please.

**Comment by Theundyingcode** [comment]
> You are unable to thaw food even when its next to a fire.
Food dose defrost when left within ~2 tiles of a fire.  It might take a while but I lost a lot of my food because I didn't realize this was a thing.

> Can no longer cut long grass unless you have a very special tool, 
Reasonable but, cutting grass with a knife also needs to be a lot less efficient.

> Salt gets into the frozen state..
Just... wow.

> Sleeping no longer cancels and makes no sense.
You can cancel trying to sleep with '.' at least in 30 min blocks and, trying to sleep makes a lot more sense now than it used to.

Sorry kevin, I had already started typing this when you closed the issue, so I went and finished it.
