### ISSUE TITLE
visuals of "pre-game" dead bodies (underwear everywhere!)

### ISSUE THREAD

**Issue by SomeDeadGuy** [CleverRaven/Cataclysm-DDA#26261]
Game version: Tiles Latest

### Expected behavior
Dead bodies found in the wild, like drug cartel wars aftermath, should look like copses laying on the ground. "Dead Body" item should be on top of the pile of loot it got.
### Actual behavior
Now they look like bunch on underwear laying on the floor, because "dead body" item always at the bottom of the loot pile on each body, and underwear is always on top.
### Steps to reproduce the behavior
Just find some dead bodies what was placed in the game before it started, like gang war aftermath, and you will see underwear instead of corpses.

**Comment by Drakasin** [comment]
So many panties...

**Comment by curstwist** [comment]
The panties make it far more challenging to find bodies, nor sure if it's intended.  They used to stack differently.

**Comment by dsmky117** [comment]
Would it make sense to generally draw the item with the greatest volume?

**Comment by kevingranade** [comment]
I vaguely remember it doing exactly that, that should be fine.

**Comment by jbytheway** [comment]
> Would it make sense to generally draw the item with the greatest volume?

I'm trying to decide how this would affect piles of stuff in your base.  On the one hand perhaps it's nice to see the item you last put on the pile (as currently happens) because that might be an item you're likely to want again soon.  On the other hand drawing the highest-volume item would make the pictured item more consistent, so you'd get used to the appearance of each tile and maybe it would be easier to recognise which one is e.g. the pile of weapons.

**Comment by Trokinos** [comment]
I think the corpse visual (and so the item list order) should always be what takes priority when you discover those dead soldiers/scientist/gangs around because considering the whole game takes place in zombie infested area the character immediate concern should be triggered by seeing any corpse, even not moving just in case it moves later.

So before seeing the panties, the credit card , it should always be the corpse first.

**Comment by OzoneH3** [comment]
```get_uppermost_item()``` is used to get the item to display
which is just the last item from the submap ```std::list```.

```
const item &get_uppermost_item() const {
    return sm->itm[x][y].back();
}
```

**Comment by kevingranade** [comment]
We might just stash corpses at one end of the list so they show up on top.

**Comment by SomeDeadGuy** [comment]
remembered this issue and made two comparison shots
how it is now
![corpses now](https://user-images.githubusercontent.com/37592026/54934060-ecb6be80-4f2e-11e9-9463-6bfbbc7238b6.png)
how i want it to be
![corpses after fix](https://user-images.githubusercontent.com/37592026/54934079-f50ef980-4f2e-11e9-96f9-8ba67d4525dd.png)

**Comment by SomeDeadGuy** [comment]
Plastic bags of drugs still spawn on top of the bodies and cover them. Just like on my screenshot there.
