### ISSUE TITLE
Segfault in item::is_null when exploding myself in my car

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#26316]
I've accidentally lit a black gunpowder bomb when i was chilling in my RV and had no time to get out to throw it away.
0.C-33397-g0c4464c32b-dirty
```
#0  item::is_null (this=0x10) at src/item.cpp:411
#1  0x0000564d19a65c2f in item::volume (this=0x10, integral=<optimized out>) at src/item.cpp:2989
#2  0x0000564d19a65d4c in item::volume (this=0x564d217080a0, integral=<optimized out>) at src/item.cpp:3014
#3  0x0000564d19a69477 in item::tname[abi:cxx11](unsigned int, bool) const (this=0x564d217080a0, quantity=quantity@entry=1, with_prefix=with_prefix@entry=true) at src/item.cpp:2601
#4  0x0000564d19a06364 in inventory::remove_item (this=this@entry=0x564d1ba14c80, it=<optimized out>, it@entry=0x564d217080a0) at src/inventory.cpp:533
#5  0x0000564d1a1c62b3 in player::process_active_items (this=0x564d1ba14ad0) at src/player.cpp:6793
#6  0x0000564d198fb9ad in game::do_turn (this=0x564d1b9b9a90) at src/game.cpp:1652
#7  0x0000564d1951ae3c in main (argc=<optimized out>, argv=<optimized out>) at src/main.cpp:649
```

**Comment by l29ah** [comment]
I use this ebuild to install cdda: https://github.com/leycec/raiagent/blob/master/games-roguelike/cataclysm-dda/cataclysm-dda-9999-r7.ebuild
Apparently it changes something that the build system then detects.

**Comment by kevingranade** [comment]
I think I found it.
The scenario is.
Player has an active bomb in inventory.
Bomb goes off.
Blast destroys some clothing that was providing storage.
This triggers item dropping.
The bomb is dropped.
Cleanup code after the explosion tries to remove the item but fails because it's been destroyed.
Ironically everything about this is fine except for the debug message that gets printed because the code can't find the item to remove it.
