### ISSUE TITLE
Weather prediction/forecast?

### ISSUE THREAD

**Issue by ianestrachan** [CleverRaven/Cataclysm-DDA#2633]
Weather changes very rapidly in Cataclysm sometimes. While there's no weather forecast on the news in a zombie apocalypse, I'd like to see characters with decent levels in Survival be able to forecast the weather while they are outside, something like "You look up at the sky; it looks like it will rain later today". (It may also have to be during daylight hours)

If I recall rightly, there is a weather pattern planned out slightly in advance, so this shouldn't be too difficult. What would be a reasonable Survival level to do this? Or maybe you can always use the command, but at lower levels you can't make a prediction or might predict wrongly (predict rain when it won't, predict clear skies when it's going to rain).

Maybe there can be equipment to help with this, like a barometer and/or thermometer?

It'd be good to know if you can leave the raincoat and umbrella behind, or if you should set up a funnel or two to collect water while you're gone (with #2618). You're probably not going to be able to tell the difference between rain and acid rain, though.
##

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
