### ISSUE TITLE
Extend character info page to show all limbs

### ISSUE THREAD

**Issue by rubenpd** [CleverRaven/Cataclysm-DDA#26338]
**Is your feature request related to a problem? Please describe.**  
I'm always frustrated when i wear some single leg equipment and have to scroll down the list to see my feet's warmth
**Describe the solution you'd like**  
Being able to see all limbs when wearing different gear for arms and legs

**Describe alternatives you've considered**  
noone so far
**Additional context**  
https://cdn.discordapp.com/attachments/494455674378518529/503577450391928842/unknown.png

**Comment by xrandomuserx** [comment]
Agree, this always happen when I am hot. Maybe sort by temperature?

**Comment by Theundyingcode** [comment]
> Maybe sort by temperature?

ABSOLUTELY NOT!!!  Not being in a consistent order would drive me crazy.  Plus it brings up the issue of why you aren't sorting by encumbrance or putting the freezing thing first.  

Just make the box bigger.  On second thought I like having the limbs combined when the values are the same since it reduces clutter.  Make the box scale to the list size if the screen is big enough.  Probably want to handle #25091 to address concerns regarding small window sizes.

**Comment by rubenpd** [comment]
Yeah just make the box bigger, no sorting unless is an optional feature:)
