### ISSUE TITLE
Unable to resume crafting interrupted by the lack of light

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#26389]
It is just started anew. Quite sad when you don't have enough daytime for those 9h weapons.
0.C-33403-ga10e5d7bb8
It used to work some months ago!

**Comment by Leland** [comment]
Per #23944, can you try the following:

> crafting interrupted by darkness can be resumed if you'll get the light going again, have access to the necessary tools/materials and, say, press the key to repeat crafting of the last recipe

**Comment by l29ah** [comment]
This never works these days. If i'm sitting in the middle of my vehicle, sun goes down, and the only thing i do is turning on the dashboard, when i press `-` it is started from the beginning.

**Comment by eturner** [comment]
I noticed this too. You used to be able to stop to eat and drink briefly before pressing - to resume, but I haven't seen "you resume crafting" in a while.

**Comment by Leland** [comment]
See #23642 and prior issue #23642.

Additionally note #25400 which plays around similar concepts

**Comment by rubenpd** [comment]
yeah 9h craft recipes are really frustrating with the "resume craft" feature not working

**Comment by DarkRainX** [comment]
After spending over 3 (in-game) weeks doing nothing but cooking and preserving meat I can confirm that crafts interrupted by anything — be it the sunset, or the random skeletal juggernaut coming out from the nearby forest — can't be resumed.

I also found the reason: #25675 added the following lines to craft_command::execute() in craft_command.cpp
https://github.com/CleverRaven/Cataclysm-DDA/blob/7ac91babf9a1c22771eef42556ac59638d8c14db/src/craft_command.cpp#L85-L86

Right before the call to **player::assign_activity()**. Since both **activity.values** and **activity.coords** were modified, the **player_activity::can_resume_with()** check will always fail.

**Comment by l29ah** [comment]
I guess a simple workaround would be to check if any of the components of the recipe can ever spoil during the crafting process before applying the logic.

**Comment by l29ah** [comment]
I don't see how to go from `item_comp` to `item` to ask for `goes_bad()` though without triggering consumption.

**Comment by jbytheway** [comment]
I have an idea; looking into this now.
