### ISSUE TITLE
Open containers should act as very weak funnels

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#26391]
So they would fill after some time during rains. Maybe they would need to be "prepared" for this (turned the right side up), but irl you can find those filling themselves "naturally" ;)

**Comment by dissociativity** [comment]
This should at the very least apply to pots, buckets and frying pans

**Comment by FulcrumA** [comment]
I'd say other wide-opening containers should benefit from it as well. Ice cream tubs, unfilled plastic flower pots, jars etc. Either way, I do think it's a good idea - not only it makes sense on its own, it does make nice post-apoc mental image whne rather than a set of funnels, some survivor just lines a bunch of various pots in the field to catch rainwater.

**Comment by Night-Pryanik** [comment]
The whole idea requires adding a feature of water drying - both in open containers and in the fields able to soak. Otherwise it should surprise players when they find some open container filled with rainwater despite there wasn't any rains for a long time.
