### ISSUE TITLE
Tank installation fails to pick the proper tank and aborts

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#26430]
**To Reproduce**  
1. Have an empty tank nearby and also carry a filled one.
2. Install a tank to a vehicle.
3. After all the hard work when the game asks which tank to install select the one you carry.
4. `Could not find base part in requirements for vehicle tank (60L).`

**Expected behavior**  
The empty tank gets installed, no dumb questions asked.

**Comment by Night-Pryanik** [comment]
Cannot reproduce on latest experimental as of September 29, 2019. Tested on:
- having one tank (filled) in inventory and an empty one nearby on the ground;
- having one tank (empty) in inventory and a filled one nearby on the ground;
- having both (empty and filled) tanks in inventory;
- having both (empty and filled) tanks on the ground.
In all cases game automatically takes an empty tank, not asking me at all about which tank to install.

@l29ah have you ever encountered this bug on latest experimentals since while?

**Comment by l29ah** [comment]
No, but i haven't actually tried to trigger it; i was checking it for fun back then.

**Comment by Night-Pryanik** [comment]
Could you please test this situation once again to check if this is still an issue?

**Comment by Night-Pryanik** [comment]
Closing as unconfirmed.
