### ISSUE TITLE
Grappling hooks don't seem to work as intended.

### ISSUE THREAD

**Issue by preacherpix** [CleverRaven/Cataclysm-DDA#26446]
**Describe the bug**  
When dealing with a hole that goes between z-levels, i.e. a hole caused by an explosion, I walked down into the hole with the grappling hook and still took fall damage, despite what the description of the item implies.. Once inside the hole, I cannot climb out or activate the grappling hook in any way, which also seems like a... pretty fundamental thing for a grappling hook to do.

**To Reproduce**  
1. Get yourself a grappling hook and an open space that drops you to another z-level, such as a roof or a hole blasted in a ceiling.
2. Fall down into the hole and take fall damage.
3. Try to climb back up the hole with the grappling hook.

**Expected behavior**  
The description of the item states pretty well, verbatim, "Useful for keeping yourself safe from falls." All I can gleam from that is that, with the grappling hook in my possession, I should be able to maneuver down a z-level without taking fall damage. It states it has a 30 foot long length of rope attached, so I see no reason I shouldn't be able to plant this down and use it to climb back up or go down.

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.C-33739-gab6328e
 - Graphics version: Tiles
 - Mods loaded: None. Thought this may be because of my extensive mod list, but I just tried it on a totally vanilla world. Still the same thing.

**Comment by NickGrease** [comment]
If memory serves (and that's a risky proposition)  I'm pretty sure you need to be wielding the hook *prior* to the fall. While your expected behavior should be... expected, the introduction of the hook, again if memory serves, was to combat falling in swamp holes. The 'lore', I believe, wasn't so much about falling in a giant hole where you could swing your hook around and throw it up to solid ground, but falling into a confined hole (1 tile) or more like swampy marsh quicksand - neither conducive 'swing your way out' but it did make (more) sense that having it wielded gave you the opportunity to latch onto something solid on the way down and pull your way out.

**Comment by preacherpix** [comment]
Wielding it changes nothing, just tested by blowing my starter shelter to smithereens and cleaning out the rubble. Having it in my hands still causes me to take damage whether or not I walk into the open space or examine it and jump down that way.

**Comment by Night-Pryanik** [comment]
Grappling hooks for now are useful in only a handful of situations, in fact, only three situations - descending down a ladder which have a sheer drop halfway down, and when falling in a sinkhole; also as a substitute for a rope when butchering corpses. All other cases, including the ones you mentioned, ain't affected at all. So that's not a bug per se, but instead a not yet implemented functional.
