### ISSUE TITLE
Damage-min : 0 not working, for item spawns

### ISSUE THREAD

**Issue by Soyweiser** [CleverRaven/Cataclysm-DDA#26473]
**Describe the bug**  
If you use damage-min 0, you would expect an item to spawn with a chance of not having damage, this isn't true. An item set to Damage-min 0, Damage-max 1, always creates an item with 1 damage. (Same for "damage": [0, 1]).

**To Reproduce**  
Create a droplist with something like:
{ "item": "briefcase", "damage": [0, 1] }
Test it, and you will get around 100 briefcases with 1 damage. ( |\ )

Otoh, if you use [-1, 1] you create either a ++ briefcase, or a |\ briefcase, but no || briefcases as expected.

**Expected behavior**  
You would expect undamaged items to also show up, but there are none.

**Versions and configuration(please complete the following information):**
Compiled the game myself using the most recent codebase.

**Comment by Theundyingcode** [comment]
Without looking at the code, I highly suspect this is due to an if statement somewhere saying 0 = false.

**Comment by Qrox** [comment]
My guess is that, since item damage value was converted to integer from float some time ago, and scaled by a factor of 1000, it's hard for the value to be exactly 0 in randomization. Currently any item with positive damage value is shown as damaged (`|\` or worse), so this is more likely a display issue than a spawn bug.

**Comment by BevapDin** [comment]
> If you use damage-min 0, you would expect an item to spawn with a chance of not having damage, this isn't true. 

It does work, it just happens *very* rarely. Testing via the item group debug menu gives a few (< 10) undamaged items and many (~1950) damaged items.

The values from JSON are multiplied with `itype::damage_scale` (which is 1000) and later used in an `rng( min, max )`statement. The item will only be undamaged when this returns 0, which has a chance of about 1 / 1000.
1
All the spawned items have damage values in the range 0 to 1000, but only the value 0 will show as undamaged, the other values (1-1000) will show as single damage level.

I have no idea how to deal with that.

**Comment by LeahLuong** [comment]
@ymber Matthew, if some1 else picks this up, is there any wisdom you'd like to pass on??

If the issue has become irrelevant due to another fix, this thread should be closed.

**Comment by ymber** [comment]
Nothing has changed to fix this bug that I know of but I've not been keeping track of cata development for a few years now. I remember looking at this back when I was working on item distributions and unless it's all changed since then the code in the engine that handles this stuff is pretty simple. Give it a shot if you want.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
