### ISSUE TITLE
"Workstation" from Refugee Center Quest Can Override All Other Computer Functions

### ISSUE THREAD

**Issue by GearheadLydia** [CleverRaven/Cataclysm-DDA#26481]
**Describe the bug**  
When you get the second quest from the Refugee Center doctor, she will point you to a lab. Upon downloading the data, all of the computers in that lab that had not yet been interacted with will be converted into "Workstation" computers, regardless of their original intended function - making it impossible, for instance, to open metal doors by hacking. Completing the quest does not reset any already affected computers, but does seem to stop this from happening to new computers.

**To Reproduce**  
- Complete the refugee center quest for analyzing zombie blood and bringing it back. Turn in this quest and accept the next one.
- Go into a lab.
- Download the data from a computer designated as a workstation, but do not turn it in.
- Attempt to mess with any other computer that had not previously been touched. Look especially for those controlling doors.

**Expected behavior** 
Only the first computer the player tries to access with this quest active should be clobbered with the workstation functions, probably at runtime rather than overriding everything in the map (which may or may not be what it already does).

EDIT: I have realized that the way this quest seems to work is by spawning computers in the laboratory. In any case, that should be sufficient; replacing existing computers is superfluous.

**Versions and configuration(please complete the following information):**
 - OS: Windows 7
 - Game Version: 0.C-32651-gba0cd1a
 - Graphics version: Tiles
 - Mods loaded: Filthy Clothing, Simplified Nutrition, Craftable Gun Pack, Safe Autodoc, Bright Nights, Makeshift Items Mod, Mutant NPCs, NPC traits, More Locations, Tall Buildings, Boats, Folding Parts pack, Vehicle Additions Pack, Tanks and Other Vehicles, Classes and Scenarios Mod, No Acid Zombies, Fuji's More Buildings, Beta Natiional Guard Camp, Hair aka Rainbow, More Location hairs.

**Comment by Qrox** [comment]
I suspect the cause of this is that currently each submap only contains one `computer` member, which is shared by all the consoles on the submap. Some lab submaps happen to contain both consoles and broken consoles (such as near some locked doors). The current code generates mission consoles first by converting broken consoles into consoles, and if a broken console near another active console is selected, both consoles will be converted to workstations because now the submap `computer` member will be changed to function as a workstation. This gives the impression that many consoles are altered, while in fact at most 4 conversions are done. @GearHeadLydia Could you please check your save and see how many consoles are converted and in which locations?
