### ISSUE TITLE
Vehicle menu confused by multiple bike racks

### ISSUE THREAD

**Issue by strife26** [CleverRaven/Cataclysm-DDA#26528]
**Describe the bug**  
Examining any bike rack on a vehicle seems to interact with only the first bike rack, not the examined part. 
 
**To Reproduce**  
1. Spawn car and two different one tile vehicles
2. Install two bike racks on vehicle 
3. Load one cart on vehicle
4. Attempt to load second cart - first car is instead unloaded 

**Expected behavior**  
Examining a bike rack interacts with that bike rack and multiple vehicles can be loaded, or game clearly notes that this is not possible. Aside, racking a cart on a cart on a car currently works

**Versions and configuration(please complete the following information):**
 - OS: Win 10 
 - Game Version: gc7832c6 
 - Graphics version: Tiles
 - Mods loaded: Boats, Folding Parts, Vehicle Additions, Tanks

**Comment by JacobKessler** [comment]
This seems inconsistent, but there are definitely problems with it. I was able to run around with a pair of two-tile vehicles racked to the back of a light tank without a problem, racking and unracking them independently and without issue. I switched to a different vehicle that I wanted to rack on the sides, and now I can sometimes unrack those same two-tile vehicles, sometimes not, and sometimes only partially (only one of the two parts will detach).

My suspicion is something in the code that tracks what should unrack when a particular rack is interacted with.

**Comment by Lorith** [comment]
Can confirm issue exists, but getting different behavior than JacobKessler is - I put two bike racks similar to 4 and 5 above, but only 5 worked, regardless of which one was placed first or last, it was impossible to make 4 work even if nothing was near 5.

**Comment by swofle** [comment]
After encountering this problem myself and some digging around, I found that the cause is `vehicle::find_lines_of_parts()` returning the wrong racks when the vehicle has multiple racks along the same axis.

In this code section:
>https://github.com/CleverRaven/Cataclysm-DDA/blob/f03c26b4a2029b83d3b28750fb7ba199217db796/src/vehicle.cpp#L2270-L2281

The check for `found_part` is done before the check for "break in run". This means that when we detected the break, we would also include the current `x_parts[ i ]` in our search, even though the current part is disconnected from `first_part`. The fix here would be to move line 2271 to 2280. The same issue applies for `y_parts`. @mlangsdorf Please take a look.

**Comment by mlangsdorf** [comment]
Any reason you can't summit a fix yourself?  I'll take a look but it may be a day or two.
