### ISSUE TITLE
Awl pike inferior has same damage as regular one. Description for regular one is wrong. 

### ISSUE THREAD

**Issue by SirPendrak** [CleverRaven/Cataclysm-DDA#26547]
**Describe the bug**  
Recent changes to awl pike not only reduced its to hit ratio from +2 to -2, but also lowered its damage. 
Description still says its accuracy and damage are unparalleled. 
**To Reproduce**  
1. Spawn 3 different variants of awl pike.
2. Notice their stats are different than before
Regular 15b/45c -> 8b/25c
Inferior 12b/25c -> 8b/25c 
Fake 10b/15c -> 6b/15c (not revelant)
**Expected behavior**  
Awl pike inferior will have its damage different than true version. So far every inferior weapon in game was different so this one breaks a trend and common sense. There should be more differences than material, durable melee flag and ability to wear only best one with spear strap (might be bug as well). 

Also, right now its accuracy and damage are paralleled.

**Versions and configuration:**
 - Game Version 8123
**Additional context**  
Weaker wariants cannot be worn with spear strap.

**Comment by JeraldOfLibya** [comment]
I gotta agree with this one.  Please edit the item descriptions as well when you modify the numbers.

![pointy-bois](https://user-images.githubusercontent.com/44783693/48026790-feffae00-e181-11e8-994b-38ebbe8705b1.png)
As a side note. if we assume that the boar spear here = steel spear in-game, just from looking at the darn thing, most of us here can probably agree that the awl pike should have:

- Higher pierce damage due to being an extra pointy-boi.
- Slightly lower to-hit by virtue of increased weight.. but not (-2) levels of low.

As for gameplay.. here are the stats as of 8123:

Steel spear
- Fabrication 4 + auto-learn
- 29 pierce
- ~140 moves per atk
- +2 to hit

Awl pike
- Fabrication 7 + book
- 28 pierce
- ~160 moves per atk
- -2 to hit

It just wouldn't make sense that it'd be a downgrade in every way.

**Comment by kevingranade** [comment]
Addressed by https://github.com/CleverRaven/Cataclysm-DDA/commit/40e325c78722de1a4559c1e4d765c164b7bd386d

As for balance, please open a new issue for it if you think it's a problem.
The "awl pike" in game is clearly the "pike" from the above diagram, as it has additional reach compared to the other polearms.

See #26459 for discussion, but the crux of it is that due to the additional length of the weapon, it's extremely unwieldy, and as such presents greater difficulties in hitting your target.

As for the fabrication requirement, it's literally a spear head on an extra-long pole, so yes the Fabrication 7 seems uncalled for.

**Comment by JeraldOfLibya** [comment]
Hmm.. guess that makes sense.

I kinda forgot that the awl pike in-game has reach 3. Darn naming technicality.
