### ISSUE TITLE
The Planter Tractor's planter turns off due to low temperature. x15

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#26576]
**Describe the bug**  
I've got the Retrieve Prospectus mission and started receiving these messages for no apparent reason, even though the farm is really far away.

0.C-34135-g129cc5ea2a-dirty

**Comment by ribchinski** [comment]
I am seeing it too. I visited the ranch once and opened the Garage to see the tractor. Started receiving the message afterwards. I decided to leave the Garage, because the message was becoming incredibly annoying...

Now, almost a kilometre away, I still get these messages! This is definitely a bug. It really makes the log harder to look at...

**Comment by ribchinski** [comment]
Here are some screenshots
<img width="360" alt="screenshot 2018-11-09 at 17 04 47" src="https://user-images.githubusercontent.com/20406114/48290642-99d9e000-e441-11e8-9d07-1eabe543d07a.png">
<img width="654" alt="screenshot 2018-11-09 at 17 05 49" src="https://user-images.githubusercontent.com/20406114/48290682-b8d87200-e441-11e8-8b89-c0e3cfd6d0a9.png">

**Comment by l29ah** [comment]
May be related to https://github.com/CleverRaven/Cataclysm-DDA/issues/26617
