### ISSUE TITLE
Cutting up items doesn't destroy them

### ISSUE THREAD

**Issue by Feuerhai** [CleverRaven/Cataclysm-DDA#26673]
**Describe the bug**  
When you cut up an item which is in an adjacent square you get the materials but the original item doesn't get destroyed

**To Reproduce**  
1. Create a Survivor
2. Drop any of your clothing next to you
3. Cut up the dropped item with your pocket knife without moving

**Expected behavior**  
The item which get's cut up disappears.

**Versions and configuration(please complete the following information):**
 - OS: Windows 7
 - Game Version 0.C-34487-gd84de37
 - Graphics version: Tiles
 - Mods loaded: Dark Days Ahead, Disable NPC Needs, Filthy Clothing, Simplified Nutrition

**Comment by Lorith** [comment]
Confirmed on 8152 (0.C-34440-geca4878) - activate knife, cut up item, item on different square, item does not get destroyed.  Works fine for anything on your square.

**Comment by kevingranade** [comment]
@Night-Pryanik had the right idea, the code at https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/iuse_actor.cpp#L1163-L1360 needs to be adjusted to find and destroy the right item.

The code has the info it needs here: https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/iuse_actor.cpp#L1175 but then it discards the location and passes just the item reference into https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/iuse_actor.cpp#L1266-L1360

It looks like salvage_actor::cut_up() needs to accept the item_loc variable instead of an item reference, then at https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/iuse_actor.cpp#L1334 use that reference to remove the right item from the map.

**Comment by scanevaro** [comment]
Can confirm this happening with Shift+5 Menu and picking Cut Up Item option.
