### ISSUE TITLE
Strength is too necessary and impactful, and renders all other stats obsolete

### ISSUE THREAD

**Issue by Muffindrake** [CleverRaven/Cataclysm-DDA#26699]
Melee combat is a staple of this game - there is no way to avoid close conflict. Ranged weapons are either rather terrible early on, or require ammunition which a fresh survivor doesn't have in near-unlimited supply. In contrast melee weapons, even a simple pipe, let you bludgeon most non-brute zombies with impunity. They don't use ammo and many are trivially replaceable.

Unless you're role-playing a 4 STR super-nerd hunting fossils, you are _always_ making your character weaker by putting points into any other stats. STR gives the greatest and most reliable power-up to the ability of your character to not die. Here's a list of some aspects of your character that an increased STR augments:

- base horsepower
- melee damage
- carry capacity and lifting ability
- escaping traps and grabs
- pulping/smashing power
- throwing range, damage and weight limit
- weight limit of dragging anything
- gun recoil handling
- success chance of prying attempts

Dexterity improves:

- dodging
- aiming/throwing speed and aiming/throwing accuracy
- various random rolls involving gas pumps, safes, dangerous terrain and other things
- escaping grabs - if DEX is greater than STR
- chance of setting off traps
- melee attack speed
- critical hits
- mutation part melee attack chance

INT:

- caps survival skill from reading bushes (this is a nonsensical limitation)
- hacking of any type (vehicle security, computers, card readers, robots, ...)
- crafting success
- reading comprehension
- disassembly

PER:

- forage success chance
- aiming penalty
- disarming traps
- clothing mod chance
- overmap sight range

(http://dev.narc.ro/cataclysm/doxygen/pages.html)

This makes STR distinctly more useful as a stat to dump points (or hell, all points) into. The weight limits alone make a low-STR (particularly with mutations that reduce carry weight) character extremely undesirable and a pain to play. Such a character will also have huge problems living whenever anything closes into melee range, unless all points were dumped into DEX as well as Dodging.

I've excessively play-tested [X STR, 4 DEX/INT/PER] characters for an extremely long time. None of the bonuses besides some of the DEX bonuses are worth it in any respect if your goal is not dying. INT and PER in particular are **THE** worst choices you could make. This renders CDDA a game that has 1.5 distinct stats.

**Comment by Trokinos** [comment]
Combat being a very important element (considering how super infested cities can be), maybe INT and PER should get some combat-related bonus too in order to make them more interesting as a choice instead of going full STR when it comes to dealing with the enemy threat.

By example, unless i'm reading wrong it seems only STR provide a damage bonus (melee and throwing), it does not seem there's a stat that provide ranged melee damage bonus .

While DEX provide interesting combat bonus (accuracy and speed), maybe a ranged damage bonus could be affected to either INT or PER , explained by your character being intelligent enough to aim for weaker spot , or being able to percieve the best opening for a damaging shot.

I don't feel this is a problem that would be fixed by "nerfing" STR (as characters with best STR still die ;D ), but by improving the neglected stats to make them more attractive for people not creating STR - based characters.

**Comment by Inglonias** [comment]
The way I see it, we have two broad options. Either make combat less necessary for survival (for instance, make sneaking around easier in general, thus making strength less neccesary), or make other stats increase your combat effectiveness in new ways (for instance, make DEX increase your base speed, or running speed).

The examples above are just that: Examples. A way to think about what I'm saying here. That said, decreasing the ability for zombies to detect you would be kind of neat in my opinion.

**Comment by Trokinos** [comment]
A sneaking option would be interesting as out of walking at night there's no such a thing in cdda.

**Comment by plazma-rush** [comment]
Just spitballing some ideas:
INT could decrease crafting times by some percentage. All recipes would have a default maximum percent decrease, and individual recipes could specify a different one (say, recipes that can't be sped up at all or recipes that can be sped up by a lot more than usual)
"You find a faster way to craft this item."

DEX could also decrease crafting times, and would work similarly to how it would for INT. This would stack with INT as they're two different ways of crafting things faster.

PER could increase aim speed in conjunction with DEX. Aim speed would take into account both.

PER could display information about zombie hordes on the overmap. Increased PER means increased information, such as an estimate of horde size at above average levels and the composition of the horde at higher levels. Higher PER means more accurate numbers.

**Comment by kevingranade** [comment]
Just an FYI, if this issue turns into a brainstorming session, it will be closed and most likely ignored.  If you want something to actually happen your suggestion needs to address part of the problem and have enough detail to be implementable.

**Comment by chaisawlajatang** [comment]
I tend to disagree. I almost always pick 7-8 strength and still have a great game.

> Melee combat is a staple of this game - there is no way to avoid close conflict

Most of my recent games I played as an (almost) pure archer and avoided close combat, I dunno, 9.9 from 10 times? 
You have to fight in melee only very early on. One can easily achieve bow or pistol or gun or something (and due to the recent buff they're great). And even if you don't, you'll make more than decent damage with some basic weapons (NOT the spear).

**Comment by TempestMaiden** [comment]
> I tend to disagree. I almost always pick 7-8 strength and still have a great game.

I frequently run characters with 6 strength. You need a decent bit of gear and practice before trying to melee brutes to death, but starting out with a cudgel is still plenty versus lesser zombies. The more important bit is not encumbering your torso.

**Comment by derpkerk** [comment]
I like this idea but I'm not very far in the game so.. Im getting familiar with vehicles so having the necessary strength is very needed.

I only play melee characters and as I understand it the way to play that is along the lines of 12,8,13,5. I always take the same stats so I do enough dmg to easily smash a counter or two. I often tried max int Zi-Quan or Dragon. I'd like to use trapper too one day.

I like that we have drones now and the military vehicles for it. 

I read from others they do the low strength thing regularly so I'll give it another shot.

I want to do a max int run I think I'll start that now and see where it goes if it goes at all.
A trapper maybe. But the nailboard trap is so massive and heavy that carrying it around is never worth it to me.

When I read this I imagine having more strong options.

**Comment by Asmageddon** [comment]
As a preface, forgive me for how... "stream of thoughts" this comment is, but I tend to suck at making decisions unless one speaks to me as *the* right approach, and just wanted to share my thoughts on the matter.

-----

I feel like this is something that could/should have been reflected by the game having a different sets of stats, in accordance to what kinds of uses they might have. In particular, INT, other than crafting times, I'm having trouble thinking of enough uses for so as to bring it up to par other than gating content in a somewhat inorganic way(int reqs), and STR frankly could, if not should, have been split into STR/END to avoid becoming such a crucial stat relative to others. INT could have been either merged into PER, or split between PER and a willpower stat, since that sounds more relevant to an apocalyptic survival scenario.

AGI could probably be expanded with some movespeed bonuses, but I feel like they'd have to either be underwhelming, or really damn good, as you hit or miss breakpoints of being able to outrun enemy types. It'd be more appropriate, if footing and conditions affected movespeed more. Benefits to parkour/looting speeds and noise overall could be good. Perhaps some reductions to encumbrance penalties, but that doesn't sound right.

PER, I think that accuracy bonuses would be good, as a way of scaling ranged damage on a nice curve, where you go from misses to grazing hits, to hits, to critical hits, increasing your ranged damage output on a somewhat similar curve to how melee works. Affecting sight radius I feel could be a bit meh, especially if we were to want to hit enemy aggro range breakpoints. But perhaps with the truly dangerous turrets having an additional warning, it'd be fine?

INT... now that's the really tough nut. Faster crafting and learning are one obvious way, gating stuff behind it are another, but the former is just a convenience thing and not any true improvement, while the latter cuts content, rather than gameplay options, off. Even affecting learning/xp rates would be dodgy, since you usually want to grind books anyway(something that I profoundly think needs to be addressed if the midgame of CDDA is to ever be really fun). Perhaps giving it a side of willpower, with bonuses to morale, pain resistance, addiction resistance? But I'm not sure how I feel about putting a bunch of smaller bonuses on a stat rather than giving it some indisputably "primary" benefits. Same would go for giving it a side of charisma and thus NPC interaction.

-----

One more thought, for melee combat, I think that something like in Punch Club could be done - where both AGI and STR increase melee damage output, but in different ways, and it's "linearized" - e.g. increasing AGI lets you attack faster and more accurate, but if you also level STR, you increase the stamina costs significantly, and since AGI is a smaller part of your build now, its bonuses are milder. This way, going full AGI would be roughly as viable melee-wise as going full STR, and just slightly less powerful than going for both - either way, not doing multiplicative scaling is important imo. You could probably do something similar for PER and AGI and ranged combat, as well as STR and AGI for thrown weaponry. 

Still, I just can't think of a way to bring true equity, not without splitting STR into STR and END. Making benefits from high stats taper off as you go higher, and not work multiplicatively could be something of a stopgap measure, as it'd make it more desirable to have at least somewhat well-rounded stats, rather than go into one or two and hit breakpoints(if any) on the rest. Anyway, I'll comment more if anything more comes to mind, sorry again for how longwinded I got here.

-----

This is quite offtopic, but I think the stat system I'd like for my games would be STR, END; AGI, DEX, PER, WIL. For physical fitness, physical ability, mental fitness groups, in pairs of "offensive" and "defensive" stat, with many things scaling off two stats, in a nonmultiplicative manner. Just wanted to share, forgive me c.c

**Comment by kevingranade** [comment]
Roughly a month in, and this hasn't presented any real solutions, closing.

**Comment by Asmageddon** [comment]
@kevingranade I'm not gonna be doing anything, at least not anytime soon, but would changes like my idea to merge, split, or add stats be off limits? Because I just don't see the issue being "solved" without splitting STR into STR and END, just reducing the gap at best.

**Comment by kevingranade** [comment]
Adjusting the stat list is a very expensive and disruptive thing to do,  so you'd need a really compelling solution for it to be worthwhile.  In particular jumping straight to that without attempting the multitude of smaller-scale proposals is a non-starter.
