### ISSUE TITLE
Unbalanced Screwdriver set Reciepe

### ISSUE THREAD

**Issue by Lamandus** [CleverRaven/Cataclysm-DDA#26801]
Regarding #26697
Since it just got PRed without anyone being for the change, we now can craft a whole screwdriverset with near to no regarts of balance or sense... 

> {
"type": "recipe",
"result": "screwdriver_set",
"id_suffix": "forged",
"category": "CC_OTHER",
"subcategory": "CSC_OTHER_TOOLS",
"skill_used": "fabrication",
"skills_required": [ "tailor", 2 ],
"difficulty": 6,
"time": 180000,
"autolearn": true,
"using": [ [ "forging_standard", 10 ], [ "sewing_standard", 60 ] ],
"qualities": [ { "id": "ANVIL", "level": 3 }, { "id": "HAMMER_FINE", "level": 1 }, { "id": "CHISEL", "level": 3 } ],
"tools": [ [ [ "tongs", -1 ] ], [ [ "swage", -1 ] ], [ [ "crucible", -1 ], [ "crucible_clay", -1 ] ] ],
"components": [ [ [ "plastic_chunk", 6 ], [ "duct_tape", 180 ] ], [ [ "steel_chunk", 12 ], [ "scrap", 36 ] ], [ [ "leather", 8 ] ] ]
},

is actually a good idea from FulcrumA taken from the PR "discussion", making it realistically harder to forge such a set from scratch.
But why would anyone listen, right?

**Comment by Lamandus** [comment]
> The material cost seems a bit excessive, that's 0.42kg of plastic/~0.8kg of duct tape, 3kg of steel, and 0.8kg of leather to make a 0.34kg screwdriver set.

but that is the normal "waste of material", comparing to other reciepes.
Take the scythe as an example. The object is 3,01 kg. The components are "6 lump of steel" (6 kg) and 4 heavy sticks (6,8 kg), so you need 12,8 kg of resources to make a 3 kg object.

in my opinion the set is too light anyway, it is just double the weight and volume, does it just contain of 2 screwdrivers?

**Comment by l29ah** [comment]
![](https://images-na.ssl-images-amazon.com/images/I/91NTJwP6-RL._SL1500_.jpg)
// maybe we should require the safety glasses when using a screwdriver set? ;)

**Comment by Lamandus** [comment]
ah, I see, but I also can see, that these things are very "precicely" done. I mean, when we can craft those things, why can't we craft normal black powder then? Where is the line?

**Comment by niglow** [comment]
Some players were calling the recipe for a forged screwdriver "useless" before, I don't mind that - guess, they just didn't play the "real wilderness" or "super low item spawn rate" scenarios where you might not have duct tape at all and wouldn't be able to craft it. The justification of being able to forge a Phillips head screwdriver stays the same as in the #22469 - it should be possible with enough skill & effort, and someone that have made a smithing set is obviously fit for this task, the time is mainly spent on shaping the head.
The issue of being able to acquire the "brand new just as manufactured screwdriver" by combining some duct tape with a random steel chunk hasn't been adressed in the #22469 since that implied enormous re-balancing - lots of recipes and car parts manipulations use screwdrivers.

The #22469 didn't have a recipe for a "screwdriver set" for a number of reasons. First of all, "screwdriver" description explicitly mentions "Phillips head". Thus the crafting time & skill requirement, because shaping the Phillips head with the used tools (chisel, anvil, hammer) wouldn't be a no-brainer. And that was just a "regular head" not a minuscule one (which size would we use to tinker firearms?):
![default](https://user-images.githubusercontent.com/5590079/48917710-4d5abf80-ee99-11e8-8eed-29452ca4769c.png)

The "screwdriver set" description states "several sizes and blade types". Flat heads are obviously easy, hex heads are achievable too, but the star-shaped and some other exotic or extremely small heads... 
![default](https://user-images.githubusercontent.com/5590079/48917793-b5a9a100-ee99-11e8-8c55-754f753c124a.png)

I'm not a smith, but it looks to me that the amount of precision needed to craft smaller screwdriver heads isn't achieveable even with the whole smithing set that's available in the game. If this justification is wrong, I'd really like to see a real life example of someone manually making small screwdriver heads within the given tools limitations.

As for possible solutions... I don't have an easy one. To me it looks completely reasonable that a screwdriver set shouldn't be available for crafting. All other solutions that I have in mind will lead to having more different screwdrivers (sizes times head types) and that doesn't look good from the UX standpoint. That's a huge effort for little gain, though I personally wouldn't mind having this layer of difficulty, to a degree, of course, it's not "Screwdrivers hunt: DDA" -  the addition of all kinds of screwdrivers sizes & heads would be an obvious overkill. Guess, we have a limited list of wheels sizes & one wrench that fits all nuts for a similar reason.

Another thing to consider - items spawn rate (ISR). Even with ISR=0.20 screwdriver sets are not too rare - if you loot enough places & kill enough zombies you'll get at least one (sometimes as a part of a gunsmiths/firearms kit) within a couple of weeks. But if one sets ISR to extremely low values then it's absolutely normal to actually struggle to find such items. If a player wants an easier life - settings are adjustable.

What I see a viable alternative: to turn current "duct tape" recipe result into a "makeshift screwdriver" (it could also use filament instead of duct tape) with "screw driving quality" of 2. Forged screwdriver would have quality of 3. Manufactured screwdriver can have the quality of 3 or more to reflect it's quality. Some tools like scissors & some knives could have screwdriving quality of 1, or even a negative one (similar to butchering tools) to reflect that they are not comfortable to use, with some time penalty and maybe with a chance to damage/break them. And, the "best part" - all recipes that use screwdrivers would have to be revised for balancing - some recipes would require a certain level of "screw driving quality" thus being completely unavailable without a proper tool. Other not too complex recipes could allow using substitutes but with some time penalty (similar to crafting in the dark or while being in a bad mood), maybe with a morale penalty too. IMO screwdriver sets shouldn't be craftable unless we have a really good justification for that and so far I'm unable to find one.

**Comment by kevingranade** [comment]
I was sceptical at first, but the existing recipe seems to pan out fine.
Working backwards from your results, you want 10 or so screwdrivers with a variety of heads.
For each screwdriver you want a shaft with a worked head, and a handle.
The shaft is a small spike that has had it's head shaped with a swage, chisel and file.
Swage and chisel are in the recipe, maybe add something for the metal filing, worst case a hacksaw would do it.
To make a spike you draw out a tiny piece of metal, thats a standard forging operation, and steel_tiny provides more than enough metal for 10 spikes.
```"components": [ [ [ "steel_chunk", 1 ], [ "scrap", 5 ] ] ]```
Maybe double that if they're large screwdrivers?
forging_standard is already a lot higher than normal so it's fine.
The handle is even easier, just cut the plastic chunks into 10 rough cylinders, heat your finished screwdriver shaft, and press fit it into the handle and then let it cool.
The recipe is missing cutting tools for this, throw in a hacksaw and a knife for shaping the plastic and you're set.

End of the day, consider adding a hacksaw, a cutting tool, and maybe double steel_tiny.

**Comment by tinukedaya** [comment]
Just as sidenote... I always considered the need for duct tape and/or other materials for the handle an overkill for makeshift screwdriver... When I would make me one (and I did a few times) I would just do something like this...
![image](https://user-images.githubusercontent.com/19891532/48963576-811b0f80-ef95-11e8-9048-8f8857f49005.png)

Doing it with a file/hacksaw is actually quite ok for normal size screwdriver. All those tiny fine screwdrivers are another issue, but I guess doable. 

What I would like to see though is a chance for the makeshift screwdriver being damaged when used. Because of the not really precise manufacturing the edges of the head gets "chewn" away often. 

That will give the players an intention to still search for proper screwdriver, while providing them an option to craft things that need it.
