### ISSUE TITLE
Modify Melee Damage to search for worn weapons.

### ISSUE THREAD

**Issue by Rod995** [CleverRaven/Cataclysm-DDA#26860]
**Is your feature request related to a problem? Please describe.**  
Sister Feature to #26836.
I'd like to be able to wear armored gloves and other worn melee things without having to wield my weapon to actually do damage with them. Currently, wearing my gloves instead of wielding them won't increase damage.

**Describe the solution you'd like**  
Maybe register the gloves as a damage maker, or an option to mark them as the currently used melee item.

**Describe alternatives you've considered**  
Working around it by strapping a gun to the glove. 
The perfect solution!

**Additional context**  
I think this might cause problems if I want to use a bayonet on my gun instead of my iron glove....

**Comment by HotSake** [comment]
So some worn items would have a special tag like "ADDS_MELEE_DAMAGE" that would get added to the damage of any unarmed attacks (actual unarmed attacks only, not weapons that use Unarmed skill like the Cestus)? Because I think it would be necessary to separate unarmed bonus damage from the damage the item does if wielded as a melee weapon.

**Comment by Rod995** [comment]
There should be an option for you to force the character to use only unarmed, right?
That could work, maybe....

**Comment by Rod995** [comment]
Jesus, I forget a lot of things.
