### ISSUE TITLE
Alternative components for constructing Butchering Racks

### ISSUE THREAD

**Issue by nullinsky** [CleverRaven/Cataclysm-DDA#26869]
**Is your feature request related to a problem? Please describe.**  
Currently Butchering Racks require 6 long sticks as it's first component with no alternatives, this is counter-intuitive because:

1. Long sticks can only be harvested from trees (particularly young ones).
2. If trees are present, the player only needs to rope to full butcher corpses anyway.

So in areas with a scarcity of trees (such as urban or underground settings where one wants to build a rack), it's impossible to construct unless you prepared the sticks in advance.

**Describe the solution you'd like**  
Alternative components would make construction less of a hassle, any similar pole-like material (heavy stick, 2x4, pipes or even rebars) would do.

**Additional context**  
Started in a lab, as a curious scientist, I wanted to see the innards of the rare and interesting creatures in containment... then found out I couldn't build a rack because it would require me to go to the surface, say hi to the turret, and take a long detour to a forest to gather the components needed.

**Comment by Xion350** [comment]
There are metal butchering racks but they require an anvil and a recipe book.

**Comment by HotSake** [comment]
I'd be in favor of adding pipes and 2x4s as options equivalent to the long sticks, but disassembly gets weird because the game doesn't store the exact materials used. Honestly that's such a corner case, I wouldn't mind if disassembling a butchering rack gave nothing back. How often do you even do that? A real innawoods survivor is probably just using a tarp and a tree, while a highly mobile survivor is finding enough mats that it won't hurt them, or can make a folding metal one.

**Comment by I-am-Erk** [comment]
a disassembled rack could give splintered wood, for a 'best of both worlds' thing.
