### ISSUE TITLE
Eat last food key.

### ISSUE THREAD

**Issue by WDevil3221** [CleverRaven/Cataclysm-DDA#26879]
**Is your feature request related to a problem? Please describe.**  
Well, you ate something, and still hungry and you have to scroll down through this again just to find that one loaf of bread you have laying on the ground? 
![image](https://user-images.githubusercontent.com/2744737/49195183-f9803700-f3c0-11e8-925e-c133d1fcb656.png)
Isn't that frustrating? Sure, you can just press / to filter out the food you need, but that's almost as bad as scrolling through the list.

**Describe the solution you'd like**  
Why not add a simple 'Eat last eaten/consumed food' key? Which is obviously as similar as 'Craft last item' key!

**Describe alternatives you've considered**  
Honestly I have no other alternatives, other ideas are welcomed though!

**Additional context**  
Thank you again for reading and making the Favorites/Recent tab a thing, using it a lot! c:

**Comment by GoLoT** [comment]
Throwing mode ideas: when eating from a stack of items a prompt could be used to ask if you want to eat a single portion of that stack or as many until satiated. I'm not sure how this or the "last eaten hotkey" would behave when having multiple stacks of the same food though.

**Comment by AMurkin** [comment]
Or keep Consume item window open until Esc pressed.

**Comment by WDevil3221** [comment]
The auto-eating one/marking food one is...so-so. I do like the 'Eat until full' though and the keeping your selection on the consume menu!

**Comment by Pupsi-Mupsi** [comment]
> Or keep Consume item window open until Esc pressed.

Keeping the window open should work just fine - Good thinking!

**Comment by tinukedaya** [comment]
Or move the last eaten item to the top of the list.

**Comment by FulcrumA** [comment]
I simply divide stacks of food for stuff I plan to eat soon and the rest. Basic supply management works fine enough for me.

**Comment by Phenomphear** [comment]
I would honestly much prefer an alternative option: A coded selectable option that is designed to feed your character food and water when needed with the best available food. Obv. it would need to be made so that bleach, vinegar, and other horrible things are not stuffed down your throat. I understand the realism in the game and that some people like selecting their food. I do not, however, find joy in navigating menus to feed my character or any number of more than 1 keypress. This game is already very jam-packed with features and crazy things. Playing the menu mini-game to feed my character just sinks my joy every time.

Since eating and drinking is a large and important part of this game, I really think it could use more attention in the QOL area of improvements. I'm not saying the system is bad, don't get me wrong, I'm sure there was a ton of work to get it to where it is now. I just would really really like a much simpler and easier, less frustrating way to eat.

As always, thank you all for such hard work on a free game!

**Comment by WDevil3221** [comment]
Yeah. But at least there's labels!

**Comment by Meuka** [comment]
> Or keep Consume item window open until Esc pressed.

I really want this to be a thing.

**Comment by mekaerwin** [comment]
Leaving the menu open would be highly desired. I'm always trying to eat the thing that is spoiling first and it's always midway down the list.

**Comment by WDevil3221** [comment]
Shouldn't be too hard to do...but I suck at coding.

**Comment by Pupsi-Mupsi** [comment]
Maybe the way the bionic window works could be transferred to the consumption.cpp.

**Comment by Pupsi-Mupsi** [comment]
@kevingranade - @mlangsdorf  - @jbytheway - @ZhilkinSerg - @OzoneH3 ...

I apologize if I broke any etiquette by shouting out.

Is this an easy thing or does it take a lot of effort?
Could someone point us in the right direction?

**Comment by Pupsi-Mupsi** [comment]
Thanks for taking a look at this!
There's always more to things than meets the eye.
This is way out of my league but i'm really grateful for you perspective.
Maybe someone will pick up a thought or two.
**Happy Holiday!**

**Comment by peperov** [comment]
I tried to make an attempt at keeping the last eaten item's pointer memorized and reselecting it when re-opening the (E)at menu. Short story: My approach failed. I don't think it is possible without introducing a major specialization in the comestible_inventory_preset and possibly also the inventory_pick_selector.
To me it seems like a bad idea trying to go that route.
