### ISSUE TITLE
Map memory cannot be toggled

### ISSUE THREAD

**Issue by woutershep** [CleverRaven/Cataclysm-DDA#26956]
**Describe the bug**  
Map memory refuses to actually go away with the { key.

~~Also there is really bad lag every couple of moves, maybe that its own issue though.~~  (@Leland: see #26958)

**To Reproduce**  
1. Press { to turn the display off.
2. It doesn't turn fully off, only a chunk?
3. Walk around.
4. Get intermittent freezes.

**Expected behavior**  
That it turns off and just goes black like it used to be. Also no lag.

**Screenshots**  
![2018-12-05-220803_1920x1080_scrot](https://user-images.githubusercontent.com/11578180/49544128-522c6400-f8da-11e8-8059-fd7807f491b1.png)
![2018-12-05-220807_1920x1080_scrot](https://user-images.githubusercontent.com/11578180/49544135-58badb80-f8da-11e8-93a8-f35b655021d0.png)

**Versions and configuration(please complete the following information):**
 - OS: Linux
 - Game Version: ab7b4079dd56a413a587889fba74436920f39d87
 - Graphics version: ncursesw
 - Mods loaded: only first party mods, no third party.

**Additional context**  
Potentially related to #26875 but to me the lag occurs everywhere not just in new areas also he made no mention about the { key not working.

**Comment by AMurkin** [comment]
Watch for config/debug.log when game lags. Maybe it's writing messages there.

**Comment by Leland** [comment]
See #26958 regarding the slowness. We'll use this issue to track an inability to turn off the map memory

**Comment by RosaEscura** [comment]
I made a duplicate issue (accidentally) about the problems with map memory not turning off as it should (see #27028) with some additional info. Also it seems that people are having a hard time replicating this problem which probably impacts this issue getting solved. Feel free to ping me for any extra information or contact me on Discord. My issue also includes a save for testing this problem.

**Comment by RosaEscura** [comment]
An update: I tried to fix this problem by uninstalling and then reinstalling CDDA. I started a new game and since I installed the tiles version the game starts with tiles on by default. I thought I'd give check if the problem with the map memory is there and it wasn't. Then I turned tiles off as I always play in ascii and that's when the map memory display wouldn't turn off anymore. So this problem seems to only exist in the ascii view, which makes sense as the person who opened this issue is also using ascii.
