### ISSUE TITLE
Make the mycus more of a threat

### ISSUE THREAD

**Issue by hyper2snyper** [CleverRaven/Cataclysm-DDA#26979]
In my current late game i needed fungal seeds, so i got an ANBC suit and walked right up to about 12 squares away from the fungal and then shot it, then i shot the hedges and walked through there territory and went to my RV, boom home free. 
Now i thought that was to easy and then while thinking about it came up with a few ways for the mycus to be harder.
1: When a neutral fungal creature (fungaloids, fungal tower, sporelings) takes damage by the player it immediately turns all the all the fungal creatures in the area hostile to the player, thus making it much harder to kill the Fungal tower.

2: The later in the game you come across a fungal bloom or tower, the more land they have already acquired. So lets say I'm i starter character, then the fungal towers start with only there over-map tile infected, however if a come across a Fungal tower a year later, they have started with an extra radius of 5 tiles around their fungal tower.
3: have them grow a "fortress" make the tower grow walls and whatnot over time, thus making it more necessary to take them out earlier. (it also give me an excuse to use a 155mm Howitzer)

**Comment by LostGoldfish** [comment]
I don't mind them being harder to deal with but I hope they change the spreading to be a little slower as well.

**Comment by Nameless-Survivor** [comment]
This thread on the forums has been discussing this topic, as well as how to rebalance the spread rate of the mycus.

https://discourse.cataclysmdda.org/t/thoughts-on-fungus/17647?u=nameless_survivor

**Comment by Nameless-Survivor** [comment]
The one thing I really dislike about how the fungus spawns currently is that they seem to pop up all over the damn place, not just within a few tiles of a tower or other infestation. I've found huge clusters of them out in the middle of nowhere, with no tower in sight. Exterminating them is possible, but its extremely tedious because of how fast they can spread and how far spores can drift. While the fungus should DEFINITELY be a pernicious & resilient foe, right now its more like an extremely annoying weed that spreads like a wildfire. 
I would make them spread starting from a central location, with growth rate increasing with infested area. You could have it spread asymmetrically by spores or something as well, but they would need to drift from the initial infestation.

**Comment by I-am-Erk** [comment]
I've been busy with dialogue at the moment, but I have sketched out some ideas for slowing fungal spread and giving them some "attacks".

Mycus as a 'character' is not really a smash-you-in-the-face kind of enemy. Fungal zombies are a bit of an exception, not sure why, but the mycus is more interested in converting us than destroying us. Their method of attack should be much more about capturing you and making you into a mushroom than about smacking you in the face with tendrils. I'd like them to be more threatening to the player and less threatening to the framerate and world map, but I think their threat should still be due to tricks and treachery, not damage and hp.
