### ISSUE TITLE
CBM Balancing: Rejection, Infection, Malfunction

### ISSUE THREAD

**Issue by Nameless-Survivor** [CleverRaven/Cataclysm-DDA#26982]
Bionics are somewhat overpowered, especially once players start acquiring vast amounts of bionic power. 

To make things slightly more realistic and address the issue of the overwhelming advantages of being heavily cybernetic, I have several proposals which might help, and could be used individually or together:

1. The addition of a requirement for taking anti-rejection drugs on a regular basis.  Care must be taken to keep bionics practical however, so anti-rejection treatments would probably need to be taken either weekly, monthly, or seasonally. The treatment would be an injection, found in hospitals, pharmacies, ambulances, doctors offices, and labs, and its rarity would be scaled with how often it must be taken.

2. A stacking increase in risk of infection from being hurt if the player has _**certain**_ CBM's that have portions that _protrude through the skin_ such as bionic claws, internal storage, or the cable charger. The Leukocyte Breeder CBM would help mitigate this in addition to its current function, but would not be able to overcome it entirely if a large number of skin-protruding CBM's are installed. Alternatively, instead of an increased chance of infection from damage, add a small chance of getting an infection every turn or day, increasing with # of skin protruding CBM's.

3. If a limb is broken there is a risk of a bionic installed in that limb being damaged and either needing maintenance via an autodoc and a bionic repair kit (found in labs, hospitals, or electronics stores), or outright replacement.

4. Extensive mutation that changes the human form greatly (ie, anything other than Elf-A or Alpha mutation trees), may result in one or more bionics in the mutated areas being rejected, requiring immediate removal at an autodoc if the mutation is not purified or a painful death will result.

EDIT:

5. EMP vulnerability. Being near a any kind of electromagnetic pulse, like from a mininuke detonation, will make most bionics lock up while they reboot. This would have varying consequences, but for example, if you have muscle augmentation, you might be paralyzed while the bionics are rebooting. Alternately, EMP may cause damage to you from the induced current electrocuting you or joule heating causing internal burns. A third possibility would be EMP damaging the CBMs themselves, necessitating their repair or replacement.

6. An option in either worldgen or the options menu somewhere to toggle the above features on/off, in case a player does not wish to use them. All existing worlds/characters would start with these features off. All new worlds would start with them on by default.

**Comment by I-am-Erk** [comment]
1. As I said in the thread, I'm strongly against the idea of anti-rejection meds for CBMs. Name a single implanted device in real life that requires anti-rejection medications and I'll consider revising my stance. Why on earth would you design an implantable device that has the possibility of rejection, when it's pretty straightforward to just *not* do that?

2. Stacking risk of infection is a good idea.

3. Potential of damaging bionics is a good idea. I'd also suggest that bionics that protrude through the skin might be at risk of being damaged in combat like any other external gear.

4. Fully agree that mutation can and should expel bionics. I'd suggest that your mode is a little harsh, since we don't get to choose our mutations. Given the gravity of the changes that are taking place with mutations, I'd be fine with a massive increase in pain, damage to the limb, and the CBM taking damage and getting "ejected". Certain mutations should prevent certain bionics from ever being installed.

**Comment by FrozenSnowFox** [comment]
1. I think any sort of rejection system is just terrible due to the sheer work required to get CBMs and install them in the first place.  Not to mention it would probably just become very tedious and annoying to constantly drug yourself up.

2. If it makes sense an increased risk of infection works I suppose.

3. This sounds reasonable and seems like it could work quite well overall.  It might be good to have it even happen without breaking a limb although you'd need to test if that's too big an issue.

4. Again not a fan of rejection, although depending on the bionic and the mutation I could see this actually making sense to some degree.

On the topic of bionic balance I'd thought about the topic myself quite a bit.  I thought of two ways you could maybe add some sort of balance to it.

The first is to make bionics work similar to clothes.  You can only put 1 on each lay of each body part before getting penalties or perhaps just flat out only allow 1 on each layer.  Layers would probably be something like bone, tissue and skin.

Another thought I had was using a slot style system like the original Deus Ex.  There are many slots for many parts of the body but they are limited.  All in all it would work similar to the layer system but probably be more limited.

**Comment by mlangsdorf** [comment]
There's already been a push for a slot system, but it's huge and invasive and complicated.  The guy pushing the idea isn't active right now and no one else has picked it up.  It's certainly post 0.D material.

**Comment by Nameless-Survivor** [comment]
Everyone who has posted so far makes excellent points. I've been personally swayed in favor of no rejection. Unfortunately, its not up to me what gets done, so who knows what will happen. Kevin seemed to like the idea of anti-reject drugs in the thread.

As for the bionic slot system, personally I HATE that idea quite a lot. I like the idea of being able to make your survivor become more machine than man, just as you can twist your genes with mutagen to become less human and more of something else. In addition, bionic slots would thoroughly break a lot of people's characters, including mine, who has almost every single CBM installed, 20k+ bionic power, and somewhere around 150 bionic power I & II CBMs just lying around.

**Comment by FrozenSnowFox** [comment]
> There's already been a push for a slot system, but it's huge and invasive and complicated. The guy pushing the idea isn't active right now and no one else has picked it up. It's certainly post 0.D material.

I did see traces of that in places especially on the wiki.  Although assigning values to bionics on how much room they take up seemed like a fairly complicated approach for players and development.  I think something like pure slots or layering would be a simpler approach.

Anyway as you said its old and nobody has worked on it.  I don't see anyone taking on bionics changes at the moment when there's more interesting stuff to work on.  I figured I'd just throw in my thoughts on the subject.  Point 2 and 3 Nameless-Survivor brought would be better to work on although I think even those could potentially require quite the undertaking.

> As for the bionic slot system, personally I HATE that idea quite a lot. I like the idea of being able to make your survivor become more machine than man, just as you can twist your genes with mutagen to become less human and more of something else. In addition, bionic slots would thoroughly break a lot of people's characters, including mine, who has almost every single CBM installed, 20k+ bionic power, and somewhere around 150 bionic power I & II CBMs just lying around.

I too hate the idea of limiting bionics but I also think it has merit.  I think allowing you to use everything is a quite weird and overpowered.  There's limitations on weight, volume and clothing.  Even mutations are limited in that you can't do more than 1 threshold plus there's a huge chance of negative traits being added.  I would be in favour of a fairly loose bionics system that allows you to install large amounts of bionics but has some limitations or drawbacks.

**Comment by I-am-Erk** [comment]
I posted before that I think the slot system should come with its own form of encumbrance. You can exceed your slot allowance, but doing so comes with penalties. Eg:

-reduced sense of taste
-bionic ennui (permanent negative to morale)
-slight loss to hp in the limb
-risk of the installed bionic getting damaged in combat because it's exposed
-chance of emitting noise from the exposed part
-chance of random pain

Et cetera, with the "over slot limit" effect of each CBM probably being specifically coded to the CBM.

**Comment by SirPendrak** [comment]
I belive that when bionic slots hit release, there will (or should) be official mod allowing disabling the limit for people wo are used to being OP. The proposed ballance so far lets you become really powefull anyway, you just have to think what is necassery, and what is not. For example, in current state, proposed slot limits let you instal:
- integrated toolset
- flamethrower
- aiming system 
- torsion rachet
- all Stats +2 enchantments 
- torso and head plating
- memory baks
- power armor mk2 interface
- repair nanobots 
- food recycler 
This is just example of bionics mix that fills almost every body slot to 100%, but with good gear and skills it is more than enough to make you godlike. Oh, and dont let me start talking about bionic power... 
IMHO, current limitless status makes Bionics change CDDA from survival game into Sims for kids simulator

**Comment by JoeTheHobo1** [comment]
So, other than once more cementing mutations as the go-to endgame due to bionics getting more drawbacks with nothing in return, what's the actual point of this?

**Comment by I-am-Erk** [comment]
"making bionics more realistic and giving them appropriate drawbacks" is an entirely unrelated issue from "make mutation balanced". Particularly since you can have both, they're not exclusive.

**Comment by Ker-Nes** [comment]
1. As others have mentioned, it's just tedious and annoying, not to mention probably not very realistic.

3. Only if repair is not a herculean task. And, more importantly, if the chance of a CBM just breaking completely from full repair being close to nil, if not zero outright, specially now that CBMs are not craftable.

4. Not unreasonable, but I'd like to see the ability to adjust them to the new form, or at least install it anew for the form. For most mutations there's nothing really stopping having CBMs, just that the ones already installed would present a problem.

5. Doesn't EMP already remove a character's entirely bionic power? Besides, the "passsive" CBMs probably aren't electronic enough to be vulnerable to EMP.

6. Yes. So very much yes.
