### ISSUE TITLE
Negative damage for firearms

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#27006]
Game version: 0.C-8263

Operating system: Windows 10 x64

Tiles or curses: tiles

Mods active: default only

### Expected behavior
![default](https://user-images.githubusercontent.com/11132525/49688146-11755a80-fb27-11e8-88bc-eba31bcf7a96.png)

Firing ammo with negative damage should heal monsters instead of damaging them?

I guess we should either cap the negative values even for damaged firearms to 0 or change the formula so the negative values should never appear - either way it should eliminate confusion for players.

**Comment by Lorith** [comment]
This causes [other issues as well](https://github.com/CleverRaven/Cataclysm-DDA/issues/26415), even at zero, though apparently it is 'not a bug' since it only shows up while modding

**Comment by Lorith** [comment]
Ah, right, I was wrong, this can occur in basegame via weapon damage, as shown above.  Take your gun and smash it into a wall repeatedly until it is damaged, or run it over with a car a few times, and you will get a large negative damage on the gun.

**Comment by JoeTheHobo1** [comment]
Imagine actually being Kevin looking at this now, after being a smug dick when it was first reported.

**Comment by tyrael93** [comment]
Easy now, bucko

**Comment by tyrael93** [comment]
>Pointing out how the person in charge of the game is smug for no deserved reason, and then it immediately came back to spit in his face?

Yes friend
is not smart move, is just angery move
if you wish project to be good, you work around these thing and then you do the thing 
but you don't insult reader 
we know reader
he like that
he ain't gon change
if you wish to fix you must bend 
now bend

**Comment by JoeTheHobo1** [comment]
So, let me get this straight here. Everyone knows that Kevin is an asshole, doesn't listen to feedback, and that any attempt to change that will just make him get angry and dig in worse. And for some reason, everyone just keeps going along with this, rather than just ignoring him entirely like he deserves, and going off to make a fork of the project. And that you actually support this, because... I honestly don't know a reason that you'd support it, so please, I'm curious. Why should the community not just give him the boot?

**Comment by tyrael93** [comment]
Alright we're done here

**Comment by JoeTheHobo1** [comment]
That's what you just said, though.

**Comment by Night-Pryanik** [comment]
@JoeTheHobo1 Please stop talking some about something that's not related to the issue itself.

**Comment by JoeTheHobo1** [comment]
Given that it directly relates to the issue being ignored by the person in charge of the project, and subsequently coming up again, it is indeed related to the issue itself.

**Comment by Zireael07** [comment]
I am not seeing any posts from Kevin, so your comments about Kevin being smug are completely unwarranted.

**Comment by JoeTheHobo1** [comment]
> 
> 
> I am not seeing any posts from Kevin, so your comments about Kevin being smug are completely unwarranted.

See the second post, then, for the link to the original issue.

**Comment by Zireael07** [comment]
@JoeTheHobo1: That other issue is admittedly related (caused by negative damage), but "modding causes weird stuff to happen" is a completely valid reply. Here we have clear steps how to reproduce the negative damage without any modding at all, so hopefully someone actually skilled in c++ comes along with a fix.

**Comment by I-am-Erk** [comment]
Until now it was only a bug shown through modding. Bugs that show up by modding things out of range aren't bugs, if we focused our efforts into making code so robust it couldn't even be modded to break, we'd never solve actual bugs.

Someone has now shown that the same problem comes up in niche areas of regular play. Now it is a bug.

This isn't rocket science.
