### ISSUE TITLE
Damaged guns should not do less damage but have a higher malfunction rate

### ISSUE THREAD

**Issue by Admiral-Wily** [CleverRaven/Cataclysm-DDA#27017]
As the title states damaged guns should not do less damage but have a higher malfunction/misfire rate and reduced accuracy (perhaps the damage has bent the barrel slightly) . As a bullet fired from a damaged gun does not magically reduce the velocity of it, it is still just as dangerous as if shot from a gun just out of the box. Also with heavily damaged guns you could add a chance to have a round explode in the chamber ruining the gun and harming the player. These are issues IRL if you fail to take care of your firearm
![example](https://user-images.githubusercontent.com/45573913/49692326-98c1ce80-fb25-11e8-9f27-ac6117593d4a.jpg)
^chamber explosion

Admittedly I know nothing of coding so I have no idea how difficult something like this would be to implement... But what do you guys think?
.

**Comment by HotSake** [comment]
Makes sense. There is already code for malfunctions, so it may just be as simple as removing the condition modifier from damage.

**Comment by Night-Pryanik** [comment]
Related to #27006.

**Comment by kevingranade** [comment]
Seems reasonable, also presents a good way to introduce various malfunctions without them being ubiquitous.

**Comment by nullinsky** [comment]
Gun misfire, chamber explosions, ammo jams, melted barrels... think of all the fun stuff that could happen due to not properly maintaining your guns. XD

**Comment by Ker-Nes** [comment]
Maybe a bit of damage reduction close to the bottom conditions, to represent possible losses in pressure if there are any very minor leaks in the barrel or receiver? Sure, it's also quite likely to blow in your face if there are, but if it doesn't _blow_, it should probably do less damage as well.

Also, bows, crossbows, slingshots (but not slings) and pneumatic weapons should still have lower damage, since their damage is also dependent on the elasticity of the materials, and part of damage there is probably losing tension. 

Energy weapons and rail/coilguns probably could do either way depending on the interpretation used for them.

Slings, well, I honestly have no idea. Might honestly merit no change until outright breaking down, maybe just a slight increase in the chance of a "misfire" to represent the pebble getting out of the pouch when it wasn't supposed to. But really, it's so incredibly simple that other than that I really don't see physical damage to it causing any trouble.

**Comment by darktoes** [comment]
To my knowledge, minor damage (I'm assuming cracks maybe chips in the limbs or a frayed string) on a bow/crossbow/slingshot aren't actually going to reduce your effective damage noticeably.
The main concern for things like that is that they'll fail entirely, and one limb is going to snap off at full draw and come up towards the wielder.

I'm not sure how I'd feel about damaged bows having a chance of breaking during firing, but that's probably the realistic way to handle it.
