### ISSUE TITLE
Certain lab finales Have no Science ID 

### ISSUE THREAD

**Issue by Admiral-Wily** [CleverRaven/Cataclysm-DDA#27043]
Not sure if it's intended or not but the finales with a Raptor, Alpha, Medical, Targeted purifier serum, and  the one with a Tank of mutagen all have no Science ID spawns and more often then not that leads to a failed escape the lab starting challenge (at least in my experience). So if it's not intended it would be cool to have a Science ID spawn in those finales.

**Comment by Inglonias** [comment]
You're right that this happens, but I don't know if this is a problem per se. There are many other ways out of a lab. Here are a few:

- Electrohacks can get through the card reader on the front door (buildable with computers 1). If you're clever with EMP grenades, you can hit the turret without hitting the card reader.
- With the materials inside a lab, you can construct an electric jackhammer with a bit of work. This requires electronics 5, but the sheer number of starting points the scenario gives you (and/or the libraries present in the lab) means that this shouldn't be too big an obstacle to overcome.
- Labs can sometimes have subway connections not just with other labs, but the main line. Similarly, they can sometimes hook into the sewer system.
- You'd be surprised how often I go deaf when I spawn into a lab because the anthill spawned THROUGH it. Get out through there if you can survive. (I just commit suicide if an anthill spawns through a lab, honestly)
- Use a mininuke on the top floor of the lab, if you find one in the lab. Admittedly, nuking the facility you are still inside is a bad idea, but...
- If you're lucky, you can find a teleporter (not a teleporter pad, though I guess you can disassemble those with trapping). These make escape trivial.

**Comment by BrianLefler** [comment]
This is just an oversight—I agree that science ids should be added to the json lab finales.  Should be a quick fix.
