### ISSUE TITLE
Zombies and NPCs weaken with lower health

### ISSUE THREAD

**Issue by Epictyphlosion** [CleverRaven/Cataclysm-DDA#27053]
**Is your feature request related to a problem? Please describe.**  
I'm not sure if this is already implemented and I just haven't noticed it, but I thought it would be good to suggest it either way. 

When you shoot or stab zombies or NPCs, they seem to still move at the same speed and deal the same amount of damage even when they are severely injured, or nearly dead. In the real world, this doesn't happen, but it does happen to the player. When you get backed into a corner with zombies and aren't prepared well enough, they will slowly damage your limbs further and further, causing you to move slower and deal weaker blows until you either manage to get away from them, or die. When you damage zombies or NPCs, they don't become weaker or slower like you do when you are injured.

**Describe the solution you'd like**  
Add some code that will cause zombies and NPCs to weaken as their health gets lower, so they move slower and deal less damage with less health. I'm not saying that each zombie and NPC should have health values for each limb they have, like the player does, but just something simple that linearly reduces the speed and damage of zombies and NPCs as they lose health.

**Describe alternatives you've considered**  
I can't really think of any alternative for this at the moment

**Additional context**  
If an NPC becomes hostile and begins to attack you, you wouldn't have to kill them, but just injure them until they either stop fighting, or until you can safely run away from them. If you're unlucky, and encounter a zombie hulk or zombie brute near the start of the game, you can deal some damage to slow them down, and get away to safety.

**Comment by Zireael07** [comment]
Zombies don't feel pain, which is the main slowdown effect in the game. For NPCs, your idea would basically double-stack pain penalties.

**Comment by Epictyphlosion** [comment]
> Zombies don't feel pain, which is the main slowdown effect in the game. For NPCs, your idea would basically double-stack pain penalties.

Even though they don't feel any pain, their bodies can still get damaged. Surely they'd move slower after getting shot at or stabbed a few times, even if they don't feel it.

**Comment by GoLoT** [comment]
Since zombies don't feel pain I think their penalties should be tied to limb health instead. Broken legs should slow their movement and broken arms should slow their attacks or prevent grabbing. AFAIK the limb system isn't implemented in zombies and isn't working in NPCs but I think it would be the way to go.

**Comment by I-am-Erk** [comment]
I don't think zombies need anything to make them less of a threat. They're kept simple for a reason

**Comment by nexusmrsep** [comment]
True, but the idea itself makes sense. Zombies may be more resilient since they can't feel pain, but the damage cannot be ignored. Broken bones, destroyed sensory organs, severed arms etc. can't be waved off. I'd even believe that transition from normal so.bie to crawling zombie might occurre if damage is high (50 Cal +).

That said it'd be hard to implement at a low granularity level as zombies technically don't have limbs. Some simplification could be done however to my belief.
