### ISSUE TITLE
Improve feedback why actions are not available on vehicle screen

### ISSUE THREAD

**Issue by SeelenJaegerTee** [CleverRaven/Cataclysm-DDA#27104]
**Is your feature request related to a problem? Please describe.**  
If you want to install or repair components in a vehicle the game could do a better job telling the player why options are not available.
Some examples:
1) I wanted to install a funnel on a tile with a solar panel. I select the tile press [ i ], I see no funnel, I am confused i press [ / ] and type funnel, still no funnel. I google the issue and find out that a tile can only have one part for some layers.
2) a) I have a damaged medium storage battery that looses power over night. Game does not tell me I lose power because battery is damaged, I had to find out by reading some google result on reddit.
b) I want to fix the battery, I select the tile and press [ r ] but I can only select the damaged frame and windshield. I don't understand why. If i remove the battery I can use my welding rig to fix it up, so why can't i just repair it while in the car?

**Describe the solution you'd like**  
1) In the installation screen funnel should appear in a different colour and game should tell me. "installation of funnel impossible because slot is occupied by: solar panel" (similar to when you try to install the funnel on a tile without a tank you can select the funnel but get a message that tells you "funnels need to be installed over tanks")
Basically at first in white there should be the items I can currently install, then in red there should be the items I have the components available but can't install on this tile because another item occupies the slot required. At least when searching for the item it should appear in the results list and tell the player why it can not be installed.
2) a) In the middle panel of the vehicle screen. Faulty battery should be displayed not in yellow but in red, giving a visual cue that something is wrong with it. On the right pane under description there should be a warning telling me "Warning: damaged batteries may loose charge over time."
(It could be argued that low skill characters would not know this but at least if the character has a high electronics skill they should know that damaged batteries loose charge.)
b) Even if I can not repair the battery when installed in the vehicle it would be great if the game could tell me why. I should be able to select the battery and then the game should tell me why I can't repair it on this screen. Am I missing materials? Is it impossible to repair installed batteries in principle? Is it a bug? Right now I have no clue. If there was just a message saying "you need to uninstall this component to repair it" this would be great for the player to understand what is expected of him.

**Describe alternatives you've considered**  
None.

**Additional context**  
I believe this would be especially helpful for new players.
Priority: low as it is just a convenience thing.
![mockup](https://user-images.githubusercontent.com/39884350/50016610-f5ac0180-ffc9-11e8-9117-5b4719982975.png)

**Comment by TechCatOther** [comment]
I think red color is for broken(critical) info. For warnings yellow not so bad.

**Comment by paulenka-aleh** [comment]
> In the installation screen funnel should appear in a different colour and game should tell me. "installation of funnel impossible because slot is occupied by: solar panel" (similar to when you try to install the funnel on a tile without a tank you can select the funnel but get a message that tells you "funnels need to be installed over tanks")
Basically at first in white there should be the items I can currently install, then in red there should be the items I have the components available but can't install on this tile because another item occupies the slot required. At least when searching for the item it should appear in the results list and tell the player why it can not be installed.

It was bothering me for a while. Actually if I enable blazemod and start installing batteries I see lots if blob parts which my survivor couldn't have idea about. I'd rather change installation process completely:
1) You select install options
2) You're presented with possible parts you can install into this vehicle (not tile-specifc). Parts for which you don't have items or don't have items highllighted in gray showing these items in red like now
3) You pick the part
4) You're to select spot on the vehicle with some spots displayed as gray and giving a message why you can't install it here.

At step 2) Items you can't install due to lack of good spot can be marked with alternative color and a message by can be selectable to check why can't you install it in particular place. Later some parts you should have no idea about until you get skill/receipe could be hidden.
