### ISSUE TITLE
Change default graphics from ChestHole to DeadPeople

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#27111]
**Is your feature request related to a problem? Please describe.**  
ChestHole is updated less frequently than DeadPeople and contains a number of missing tiles.

**Describe the solution you'd like**  
DeadPeople is a popular tileset that is frequently updated. It would be a good choice for default.

**Describe alternatives you've considered**  
Not changing the default, and getting someone to update ChestHole.

**Additional context**  
At some point soon it might be worthwhile to go through our included graphics sets and remove some of the less well maintained ones from the mainline.

**Comment by FulcrumA** [comment]
I recall ChestHole's work fondly, especially since it was the first largely complete tileset and a labour of love of a player wanting to add graphics for some friends who had hard time with CDDA otherwise. I do have to agree though, it's kind of behind now, while DeadPeople is both relatively up-to-date and quite approachable for average player compared to many alternatives.

I'd certainly be fine with making it a default.

**Comment by I-am-Erk** [comment]
Totally. I don't mean it as a negative to chesthole, and if I ever get tired of writing I might pick up the ol' tablet and update chesthole. However for the moment, I think the more complete set should be the default.
