### ISSUE TITLE
Split "disinfectant" into actual disinfectant chemicals

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#27189]
**Is your feature request related to a problem? Please describe.**  
With more chemistry features being added, and with many common disinfectants being chemically useful, it is high time to split the vague "disinfectant" into actual common disinfectants.

**Describe the solution you'd like**  
Existing "disinfectant" could easily be split into the following common substances:
- Iodine is an older disinfectant but still pretty common in homes and pharmacies. It's a good disinfectant
- Isopropanol (rubbing alcohol) is a very common household disinfectant and sometimes used in medicine. Although it dries the skin out, it's a very good disinfectant.
- Hydrogen peroxide isn't a great disinfectant, but it creates a satisfying fizz and is commonly available. It still does clean and disinfect, and it is a chemical that players could have a lot of fun with. 
- Chlorhexidine is a common medical disinfectant and frequently used in surgery.

**Describe alternatives you've considered**  
Existing disinfectant could just be converted to one of the common disinfectant types. I would go with iodine or peroxide, since there are several kinds of alcohol in game already and isopropanol is less interesting.

**Comment by tenmillimaster** [comment]
How about some other shoddy disinfectants? Hand sanitizer, salt water, soap, Lysol, various spirits(i.e. trying to use whiskey on your wounds),  mouthwash?

**Comment by Asmageddon** [comment]
I'm against this proposal, on the other hand could get behind @tenmillimaster's one.

**Comment by I-am-Erk** [comment]
Why are you against stating what disinfectant is so that it can be used for things?

**Comment by Asmageddon** [comment]
What is the benefit of replacing self-descriptive "disinfectant" with a substance name, much less several substances? It's not like the game needs a more complete chemistry system that requires identifying every substance.

**Comment by I-am-Erk** [comment]
Why does the game not need a more complete chemistry system? There's one in the middle of being made, and that's in response to the wide ranging requests for more ability to make things using chemistry.

**Comment by paulenka-aleh** [comment]
I'm nowhere near a doctor but a question what antispectic to use is bothering me since my adult life started and I got to choose myself which one to buy. Most widely available in our country are chlorhexidine, hydrogen peroxide, alchohols, iodine and brilliant green. Iodine and brilliant green were commonly used when I was a child and my parents keep them. After a surgery I know doctors used alchohols and chlorhexidine on my wound. And at home I keep chlorhexidine and 3% hydrogen peroxide. After reading a few articles in my native language I made conclusions: for serious dirty wound hydrogen peroxide will do but it shouldn't be ever used on healing wounds or unless really necessary since it slows down healing and kills your cells as good as bacteria. Chlorhexidine for for non-dirty wounds which you'd like to disenfect for whatever reason. But just water and soap will do in most cases, e.g. scratches, small cuts or anything alike.

After spending a couple of hours reading articles in English to link here as a source I'm no longer sure I made proper choices, especially wrt hydrogen peroxide.

So if there's a doctor around who could link an article with a proper explanation it would be great.

I'm a huge fan ofimplementing different types or disinfectants / antispeptics in game with proper properties corresponding to real-life ones at some degree.

**Comment by I-am-Erk** [comment]
The actual question of what type of disinfectant to use is complex.

Alcohol based disinfectants are widely used and one of the most effective, killing most bacteria except those with certain cell wall coatings. Alcohol based disinfectants with detergents are even more effective and can get pretty much anything, but the choice of detergent does matter. For example, C difficile spores basically require bleach or sodium hypochlorite. Luckily they're not generally responsible for skin and soft tissue infections. We don't usually use straight alcohol solutions for surgery.

Chlorhexidine works similarly to alcohol, by disrupting the cell membrane, but works faster (alcohol has to dry first) and is safer on mucous membranes and things. It's the preferred surgical prep for most things and a very good wound disinfectant. It still doesn't work against some specific organisms and viruses.

Hydrogen peroxide really isn't bad as a disinfectant, for shallow skin damage. However for deep wounds it's kinda terrible, you're basically dumping bleach on it. Since we don't use it in medicine for this reason, I'm not as familiar with its specific properties.

Iodine is another really effective and fairly safe disinfectant. For deep wounds we usually use it combined with alcohol since they're complementary. It can be used safely in the mouth and eyes and things so it's a common mucus membrane disinfectant.

What you usually see for surgery prep is a mixture of solutions. Iodine solutions for mucus membrane surgery, and for everything else chlorhexidine, alcohol-iodine, or chlorhexidine-alcohol. 

This article talks a bit about skin prep for surgery. Since we're talking about deep wounds and not skin cuts here, this is probably more to the point than most of what you'll see. https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2809986/
