### ISSUE TITLE
Corpses in RetroASCII throw up errors and have no graphic since #27099.

### ISSUE THREAD

**Issue by l-Ashery-l** [CleverRaven/Cataclysm-DDA#27199]
Updated my game after a couple weeks of not playing and any time a corpse comes up on screen I'll get an error akin to "Missing item definition: corpse_mon_zombie_child" after I kill a zombie child. The corpse itself lacks a graphic and is just a blank rectangle. I tried one of the other Retro tilesets and it had no issues.

I'm guessing the issue is pretty straight forward, but I'm not familiar enough with the inner workings of the game to fix it myself.

This was using build 8314 and I haven't seen any recent changes that would suggest the issue's been fixed.

**Comment by kevingranade** [comment]
Confirmed, trying to wrap my head around how this tileset even works since it doesn't seem to specify much of anything.

**Comment by kevingranade** [comment]
Of course, it just uses the fallback character rendering based on the sym field of entities.
It looks like the item draw code was extended to encode corpse monster type at some point, presumably to allow them to have a custom corpse tile, but since the fallback item drawing code tries to create an item to find the fallback symbol to use, it fails because the id supplied "corpse_<monster_id>" is no longer a valid item id.
