### ISSUE TITLE
missions error:  "called calc_chance with invalid talk_trial value: 0"

### ISSUE THREAD

**Issue by nsklaus** [CleverRaven/Cataclysm-DDA#27281]
**Describe the bug**  
missions fails. see attached screenshot and debug log

**To Reproduce**  
1. reach refugee center, talk to folks to get missions

**Expected behavior**  
missions should be given or refused, in any cases:  not crash

**Screenshots**  
![mission_fails](https://user-images.githubusercontent.com/6810861/50386108-11598b00-06e1-11e9-8b33-924e4e4b9ed5.png)
![mission_fails2](https://user-images.githubusercontent.com/6810861/50386628-00ae1280-06eb-11e9-8b06-0d8b0cd395ee.png)

**Versions and configuration(please complete the following information):**
 - OS: kubuntu 18.10
 - Game Version: 0.C-35451-ge0588e5098-dirty
 - Graphics version Tiles
 - Mods loaded: default

**Additional context**  
debug log 1:
[missions_errors.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/2706164/missions_errors.txt)
debug log 2:
[missions_errors2.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/2706244/missions_errors2.txt)
copy of save:
[save.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/2706173/save.tar.gz)

update:
---------
tried to git pull to latest (0.C-35471-gf3ae3e048b), compiled, started a complete new game, new world, no mods.
the bandit cabin mission succeeded this time (located not far from refugee center).
but, the error from the 2nd screen is still there, and i still got lots of 
"called calc_chance with invalid talk_trial value: 0" in the log (see debug log 2)

**Comment by ralreegorganon** [comment]
Can you attach a copy of the save?

**Comment by nsklaus** [comment]
> Can you attach a copy of the save?

done, i've updated the issue with the link.

**Comment by ralreegorganon** [comment]
Ok, #27282 will mitigate this specific problem in the future, but the underlying issue of the flow for assigning a mission and what happens when it doesn't have its mandatory location is a different, bigger, and more difficult problem.

The problem you ran into here is that mission had a very small search radius (50 OMT) and a restrictive placement requirement for the location (at least 20 OMT away from the nearest city), so depending on where the refugee center spawned in relation to cities, it may have been impossible for the game to find or spawn the bandit camp for the mission.

Once that gets merged, you should be able to keep going--I was able to successfully start the mission in your save. You'll probably need to use the debug menu to 1) terminate the mission you're on and 2) re-add the mission to the offering from the NPC, but then you can proceed.

**Comment by nsklaus** [comment]
it's not only about the missions 'bandit cabin, given by the old guard.
if you look at the log, you see the save error happened more than one.
for example when i've reached the refugee center, this mission crashed too.

**Comment by nsklaus** [comment]
no, when i picked up the mission at evec center, everything seemed fine, it's upon arrival at refugee center that i got a crash message. unfortunately i didn't take the screenshot at that time.

i also edited the issue to add a new screenshot for another mission fail. this one's about delivering food, cornmeal. upon delivery i get the error message.

**Comment by ralreegorganon** [comment]
Great, that helps.

**Comment by mlangsdorf** [comment]
Did #27480 fix the bandit camp issue the way #27499 fixed the dialogue issue?  If so, please close.

**Comment by kevingranade** [comment]
AFAICT all issues reported are either fixed or not reproduceable, so I'm closing.
