### ISSUE TITLE
Nanofabricator finale has no science ID card

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#27357]
**Describe the bug**  
Nanofabricator finales for labs do not have a science ID card.
**To Reproduce**  
1. Spawn in the bottoms of labs until you hit a nanofabricator finale. Note that there is no ID card.

**Expected behavior**  
As of #27070, all other science finales have ID cards.
**Screenshots**  

**Versions and configuration(please complete the following information):**
 - OS: Win 10 (64 bit)
 - Game Version: 0.C-35900-g0779cd4
 - Graphics version: Tiles
 - Mods loaded: N/A
**Additional context**  
N/A

**Comment by kevingranade** [comment]
There is no rule that finales have id cards.
As pointed out [here](https://github.com/CleverRaven/Cataclysm-DDA/issues/27043#issuecomment-445804904) there are a number of other options for escaping in case of a lab finale start.

If it's desired for the lab finale start in particular, it would be better to spawn a card based on the scenario instead of messing with mapgen.

**Comment by Inglonias** [comment]
It's funny that you bring that comment up. I made it.

I was under the impression that there was a rule, but if you say this isn't a concern, I will believe you.
