### ISSUE TITLE
sidebar needs an overhaul

### ISSUE THREAD

**Issue by nsklaus** [CleverRaven/Cataclysm-DDA#27367]
**Issue:**  
Sidebar take too much space. 
The overall feeling is messy it needs more order.
The sidebar code also need cleaning.

**Proposal**  
The idea is to get independent panels, that can get toggled on and off by the user. 
those panels could be stacked to simulate the old sidebar. 
and in the end the user could choose which panels he want to display. 
for example the user could do: 
- 0 panel on screen (just opening them on a need basis then immediately close them)
- 1 panel only (keeping most of the time only one panel open)
- 2, 3, 4.. panels on screen. 
- simulate the old sidebar by stacking a few panels of his choice and keep them most of the time.
- those panels could of course be toggled on and off at will while playing.
- choose the spacing between panels

Panels "a la carte" ..
Please consider the following mockups. 
( the term dimension is 120x37, font is 20x20 that makes a resolution of 1440x900 )
![preview2](https://user-images.githubusercontent.com/6810861/50542669-63a81980-0bc3-11e9-8a91-95d6ea02f541.png)
![preview11](https://user-images.githubusercontent.com/6810861/50547235-89bad180-0c36-11e9-8b12-2189599477b8.png)
![preview8](https://user-images.githubusercontent.com/6810861/50546965-4f026a80-0c31-11e9-9f5a-91808c5ec826.png)

the following mockups represent a minimal dimension (80x25) terminal. 
( my font size is 20x20 so that make resolution of 1600x500 )
most users will not use such minimal setting of 80x25 terminal dimension. 
it is shown to preview what this idea would look like for those playing on lower dimensions terms.
it allow to maximize game area, by showing only 
what we need when we need and not 'everything' all the time.
![preview3](https://user-images.githubusercontent.com/6810861/50547137-7149b780-0c34-11e9-9744-3c87097b851d.png)
![preview9](https://user-images.githubusercontent.com/6810861/50547138-71e24e00-0c34-11e9-9607-0471541640c3.png)
![preview10](https://user-images.githubusercontent.com/6810861/50547139-71e24e00-0c34-11e9-83eb-bb1fbfb6db25.png)

**Coding**
Iam already trying to do it. This is a follow up from my [pull request](https://github.com/CleverRaven/Cataclysm-DDA/pull/27352) on cleaning the existing sidebar. While doing it, i came up with the idea and did the mockup. The problem is i'm not a very skilled cpp dev just yet. So it will take me time. If someone want to help or takeover the idea then great, do it. 
Otherwise i'll continue to do it myself slowly at my pace. I just wanted to put the idea out and eventually get a bit of help and feedback.
For the beginning i'm planning on making 5 or 6 panel available. 
The user will choose when and what to display, as shown in the mockup.
The good new is that most code already exists for all this.

planned panels:
- character
- environment
- messages
- compass
- minimap
- look_around / mouse_view

Since everything will be segmented, each panel could have its own function.
It mean everything will get cleaner. And we can also load them all from a central point, 
if conditions are met (if user toggle them on).
```
load_panels() 
{
    if (toggle_compass)
        draw_compass(); 
    if (toggle_minimap)
        draw_minimap(); 
    if (toggle_messages)
        draw_messages();
    if (toggle_environment)
        draw_environment();
    if (toggle_character)
        draw_character();
}
```

**Comment by nexusmrsep** [comment]
Looks interesting.

**Comment by OrenAudeles** [comment]
Do you have a mockup for how this would look in a terminal with minimum dimensions (80x25)?

**Comment by nsklaus** [comment]
> I like the way it looks, but I'm a bit concerned that it seems to be displaying less information than the existing sidebar. E.g. there is no minimap or monster compass, and the message area is much smaller.
> 
> When you say floating, do you mean just a visual effect, or that the panels would be movable? I could see some interesting options like only placing panels in the corners, or drawing a message panel across the top or bottom of the screen. However that could complicate the code a great deal compared to panels that draw in a fixed location.

sir, you've just read my mind..
here's a couple more mockup i made to reply @OrenAudeles about the 80x25 dimmensions.
(my font is 20 square, so that's 1600x500).
when i said "floating", i mean it like just the visual effect. and yes i was thinking about corners too.
about the missing info it's just because i haven't made a complete mockup but of course there could be a compas panel too, and since we could choose "a la carte" what panel we want to display on screen, there could be even more panel created. maybe even having modders come up with ideas for new panel to add ?

![preview3](https://user-images.githubusercontent.com/6810861/50543120-4298f600-0bce-11e9-8938-6aa04cf67fdb.png)
![preview4](https://user-images.githubusercontent.com/6810861/50543121-4298f600-0bce-11e9-82a9-0ab8b09bd19d.png)

**Comment by CoroNaut** [comment]
Please allow this to be an option if it gets introduced, I much prefer the preexisting sidebar. Also, changing the terminal size in the options to be larger would shrink the sidebar.

**Comment by nsklaus** [comment]
No, it will be forced onto you and your name will be pinned on it.
Joke aside, it will be possible to lay out the panels to mimic the actual sidebar, that's the beauty of it.

**Comment by Solusphere** [comment]
"These panels can be stacked to simulate the old sidebar".

How? The existing sidebar is "cluttered" by virtue of displaying a huge amount of information in a very small space. Your mockup is considerably less space efficient, which it gets around by selectively displaying less information at a given moment. I'm not sure how your system could emulate the old style without either displaying less information or taking up more screenspace. 

As it stands, I considerably prefer the existing setup to the mockups you've shown, as it displays a great deal more information in a smaller space, and requires no management. I think your system would definitely be more approachable to new players though. Some players have played for years without fully understanding what some of the features on the existing sidebar represent.

**Comment by kevingranade** [comment]
Whether we move completely to a new layout or keep the old one around depends on how space efficient we can make the new layout and how much duplicated code will be required to keep both versions.

> Some players have played for years without fully understanding what some of the features on the existing sidebar represent.

This is a very strong argument against keeping the existing sidebar, if it's so dense you can't understand it, it's too dense.

**Comment by nsklaus** [comment]
just to end 2018 on a good note, i've been able to some progress. happy new year everyone. 
![screenshot_20181231_221157](https://user-images.githubusercontent.com/6810861/50568342-9cc1c480-0d50-11e9-91b0-8abde1d854ae.png)

**Comment by Solusphere** [comment]
Happy new year!

I absolutely agree that the sidebar could use an overhaul to make it easier to learn what the various components do. That's why I brought it up. I appreciate @nsklaus taking the time and effort to design something new, I just have concerns with it's current methodology.

@nsklaus, the specific example you've provided is a questionable one. While in combat, seeing your stats can definitely be helpful, as it's the primary way you're alerted to the very frequent stat penalties of pain, poison etc. It would also be very helpful to display the minimap, as it contributes greatly to your situational awareness. If we do go with a configurable "combat hud" and "exploration hud" that you can swap between, both of those would likely end up being wanted in the combat hud by players. I also notice that none of your mockups feature the movecost indicator (though that might simply be because they're mockups).

I feel like you underestimate how often certain elements of the old sidebar are actually needed. You don't need to see everything at once, no. But most of the current info is there for a reason, and it's much worse to have needed information that isn't displayed than to have unneeded information that is displayed. I'd get some more in-depth feedback from the playerbase at large before selecting what information needs to go in which pane.

**Comment by NotFuji** [comment]
@kevingranade If a veteran player can't figure out what the sidebar widgets do, that's their fault.  There's veteran players who can't survive a week too, but I don't think the bottom of the bucket should be dictating global features.  It's cluttered, sure, but that's a layout problem.

@nsklaus Nearly **Everything** on the current sidebar is important in nearly all situations.  That's not an exaggeration.  You can't properly choose what is and isn't a priority when situations change in a constant, unexpected, and sometimes hidden way.

===

**Lets do a rundown!**

Overmap Minimap: Gives a vague picture of the immediate surroundings so you don't have to constantly press M trying to find something.

Health: Self explanatory, even out of combat enough can affect this to have it always visible.

Power: See Health.

Pain: There are things that can hurt you outside of combat, it's important to know when that happens.  It's even more important in combat.

Hunger: Affects performance both in and out of combat.  Fluctuates often enough that it needs to be readily visible when it changes.

Mood: Possibly not actually very important.

Stats: Red stats gives a reasonable indication that you're afflicted with a negative status effect.  Again, this isn't only useful in combat, plenty of environmental hazards can affect this as well so it needs to be constantly monitored.

Focus: How to know if what you're doing is actually affecting your skill growth without constantly having to flip through menus.  Not super important, but it's nice to have.

Speed: Important in combat (and out for readiness purposes).  No one wants to guess how fast their character is actually moving.  Knowing if you're running or walking is important for not accidentally draining your...

Stamina: No one wants to accidentally run out of stamina at the wrong time, if you shove it in the players face, it's their fault if they do it.

Warmth: No one wants to accidentally freeze to death because they didn't have the right menu open.

Weather: See above

Overmap Name: Admittedly redundant with the overmap minimap.

Time: Maybe not too important, but checking a separate menu for timekeeping would be unnecessarily annoying.

Lighting: Can things see me right now?  Can I see right now?

Sound: Is what I'm doing (even just walking) going to attract unwanted attention?

Weapon: No one wants to accidentally break their weapon because they didn't check their inventory after every kill.  Or wonder why their...

Martial art: Isn't working for various reasons.  Or if they actually have the right martial art currently equipped.  Or if it's only partially working.

Monster Compass: Because no one wants to spend their time scrolling around trying to find a deer to hunt, or figure out what dangerous zombie types are nearby.  Acts as an early warning radar for hostiles when in relative safety.

Pixel Minimap: Not critically important, but shows exactly where those things you spotted with the compass are without having to scroll around.  You can already disable this.

Message Box: Probably the most important thing.  Explains exactly what you're doing at the given moment, and what things are changing.  Suddenly slow?  You can see that you're traveling over rough terrain.  Zombie won't die?  You can see that your attacks aren't doing enough damage.  That thing you crafted isn't in your inventory now?  Oh wait, you failed and all your scrap metal vanished from existence.

===

The panels are pretty, but they seem like a lot of wasted space for little benefit.  You seem to be already doing it, but a simple reformatting of the current sidebar seems like it would fair better.  

If you want it really small maybe allow tiles support for some of the UI elements: a single icon for weather, a single icon for lighting, pie charts to replace all the vertical bars, paper doll HP display, etc.

**Comment by nsklaus** [comment]
moar mockups .. food for thoughts.

mode exploration:
![preview14](https://user-images.githubusercontent.com/6810861/50577064-93ebf400-0e1f-11e9-8d39-881aac5f508a.png)

mode exploration (same, but also looking around)
![preview15](https://user-images.githubusercontent.com/6810861/50577065-93ebf400-0e1f-11e9-869c-8e3b75681033.png)

mode combat:
![preview16](https://user-images.githubusercontent.com/6810861/50577066-93ebf400-0e1f-11e9-9dbd-d9a717d254e7.png)

**Comment by Zireael07** [comment]
Love that combat mode shot, modifiers and compass are awesome!

**Comment by nsklaus** [comment]
> Love that combat mode shot, modifiers and compass are awesome!

@Zireael07
thanks :) 
it's always nice to hear positive feedback. i'm getting [there](https://i.imgur.com/vfQNwJG.png)

**Comment by GoLoT** [comment]
Sorry if it has been answered already but I didn't see any mention of it. How would you handle centering the screen in such system? I mean, right now the world is offset by the UI sidebar but if you make it float I'm guessing it won't really take that space and anything you draw on top will only occlude the view on one side, possibly blocking all view on that side at low resolutions. I guess a quick fix would be to make the view center be offset by the panels when at least one is open but I'm just wondering if you have something else in mind.

On a different note, making separate panels for different UI elements gives freedom to make a horizontal message box. Maybe making it a 2 column message box (possibly 3) so it shows different kinds of messages in each. One could be used for combat related messages and one for general information. This would be tricky though because all messages would have to be tagged some way.

Having a horizontal message box would free a lot of space in the sidebar for useful information.

**Comment by Anrock** [comment]
Regarding compass, i've been thinking about if it could be integrated directly into world view. Like list of enemies on NW would be put in top left corner, enemies on SE in bottom right corner and so on. Given that perimeter of  world view is way bigger than sidebar compass it's even possible to make directions more granular by having an arrow to each enemy (groping together if they're close enough to avoid clutter). Something like that:
```
+-----------------------------------------------------------------------------+
|   ^Z                         ^C                      | sidebar              |
|                                                      |                      |
|                                                      |                      |
|                                                      |                      |
|                                                      |                      |
|                                                      |                      |
|                                                      |                      |
|                                                      |                      |
|                                                      |                      |
|                                                      |                      |
|                                                      |                      |
|<                          @                          |                      |
|Z                                                     |                      |
|Z                                                     |                      |
|z                                                     |                      |
|                                                      |                      |
|                                                      |                      |
|                                                      |                      |
|                                                      |                      |
|                                                      |                      |
|                                                      |                      |
|                                                      |                      |
|                                        Vzzd          |                      |
+-----------------------------------------------------------------------------+
```

**Comment by rumly111** [comment]
For me the main problem is the limited vertical space. I don't mind if the sidebar is 1/3 of horizontal space. But with 1366x768 laptop screen and font size 20 I don't get that much lines for messages. So drawing fancy borders for those windows takes away lines that could be used for message logs.
