### ISSUE TITLE
Decluttering the crafting menu.

### ISSUE THREAD

**Issue by MalevolentAura** [CleverRaven/Cataclysm-DDA#27440]
During my playthroughs of C:DDA, I've noticed a problem about the creation of certain items, specifically, what tools are required to make said items. For the creation of dynamite, for example. The way that it lists every single cooking tool within Cataclysm in a giant block of `this OR that` I feel hurts readability, and I feel like it could be condensed into a neater form.

**The current state of the crafting menu**
![2019-01-04_16-58-43](https://user-images.githubusercontent.com/23717536/50718600-2c63bd80-1046-11e9-84f8-8d4e22e8ec68.png)
The more items that 'cook' that are added to the game, the more the crafting menu will be cluttered up. Mods that add items that are able to cook will append their entries to the text block of `OR this (25 charges) OR that (25 charges) OR etc (25 charges)` and will only make the issue of readability possibly worse over time. 

**A possible solution**
A solution that could possibly declutter the crafting screen and add to readability would be to check if each item uses the same number of charges, and if so, place it in a list of items that use the same number of charges. So instead of having a giant block of

`this (25 charges) OR that (25 charges) OR something else (25 charges) OR miscellaneous (15 charges) OR etc (15 charges)`

it could be reformatted into something like this:

`25 charges - (this, that, something else)`
`15 charges - (miscellaneous, etc)`

With the tool available to the player being highlighted a green color, and those not being colored red, of course.

I feel like this could greatly reduce the amount of screen space used by just listing out all the different tools that use a certain amount of charges, along with making the crafting screen more readable, even with many mods that add tools that use a certain amount of charges for a crafting recipe.

**Comment by GoLoT** [comment]
I like the idea but I think that instead of making a comma separated list of tools it could be a header for the number of charges and then an indented list of tools.

So instead of:
```
25 charges - (this, that, something else)
15 charges - (miscellaneous, etc)
```

it would read:
```
25 charges of:
    this
    that
    something else
OR 15 charges of:
    miscellaneous
    etc
```

It would take more space but it would make it a lot more readable and prevent having item names split between two lines or starting at the end of one line.

**Comment by KucharczykL** [comment]
Would it be useful to create a key to toggle displaying only items that are available? In the screenshot above if I have charcoal cooker with 25 charges it would only display that one item in green and upon pressing the key it would revert to the original display with full list that includes unavailable items.

My other comment seems less pertinent to this specific issue but also contributes to cluttering up the crafting menu and that is if I'm not mistaken there is no option to display only craftable items (= items that I have resources to make right now).

I think both of these could be added as additional display modes (bound to 'm' currently). The current mode would have to be shown somewhere, though, since there would be more than two.
