### ISSUE TITLE
Project outline documentation.

### ISSUE THREAD

**Issue by nexusmrsep** [CleverRaven/Cataclysm-DDA#27452]
This [project documentation ](https://docs.google.com/document/d/1LhNpXGXmkPOxp_cp0-c9G7xqnihwApq-eZSa99exfcU/edit?pli=1) seriously needs an attentive update and a shiny place in the GitHub docs.

Although GitHub CDDA projects show some open doors and avenues to aim for, in my opinion there is a place for more elaborate material on the topic, maybe also with pointing out some closed doors and dead ends for the development process and overall creation of content. A place where major ideas discussed in other places, but not yet developed, might be outlined in manner of whats acceptable and whats not. Great ideas for future implementations fished out of forums. **A road-map of sorts.**

Would you consider it @kevingranade?

**Comment by DracoGriffin** [comment]
Additionally, more design documents for reference would be incredibly useful.

Further, the [wiki section of GitHub](https://github.com/CleverRaven/Cataclysm-DDA/wiki) desperately needs updating and I totally forgot back when #24928 was open, to put in a mention or line for PR authors to [add to the "easy" jobs](https://github.com/CleverRaven/Cataclysm-DDA/wiki/Want-to-help-with-development%3F-List-of-easy-jobs) (at the minimum to offer "easy" jobs to flesh out the PR's content for newcomers/contributors instead of being lost to the archives of merged PRs).

Examples would be fragile_melee still needing to be applied to other items, fleshing out more life cycle / food web (for instance, horses don't currently breed), a mention for using looks_like, sleep_aid for items useful for sleeping (although this might be completed, I haven't delved through the entire item list to verify), usable NPC bionics (although Mark did a great job covering 99% of this) and so on.

That way when an author introduces some new flag or content or code with a sample item/profession/code, there would be some type of tracking for new contributors to be able to get their feet wet to help complete the new feature or change.

**Comment by ZhilkinSerg** [comment]
# Cataclysm:Dark Days Ahead Design Outline

## What is Cataclysm: Dark Days Ahead?

We consider DDA a freeform, post-apocalypse, low-intensity, reality-based, roguelike, with a focus on survival-sim elements and a heavy emphasis on scavenging.

To unpack that: "**freeform**" means that there's no set goal. There's no way to undo the Cataclysm and no way to permanently block it. You might be able to carve out a niche or a safe area, but evolution is gonna happen. You can accomplish a lot of things--build a house, drive around, develop areas, etc, but the only hard and fast rule is "if you get killed, you're gonna have to deal with that."

**Post-apocalypse:** Civilization, as known pre-Cataclysm, is Done. You might be able to get a microstate together (that's what factions are), but vital infrastructure is gone in several places. National power grids are down, water treatment is stagnant, reliable long-distance communication is dead. Whatever petroleum-processing still existed has stopped now; gasoline is limited to whatever's in the pumps. Pre-Cataclysm government is limited to pockets of police/military (essentially indistinguishable from factions, though they can probably provide authentication to any surviving pre-Cataclysm computer networks, etc) and whatever automated systems are still up. There are a few.

**Low-intensity** means that the game is not constantly high-pressure, and not every move must be precisely calculated. It's OK to relax and enjoy it; there will be aspects that you need not mess with, and that's OK. Someone else will like those, and maybe even dislike the aspects that you enjoy. But there's enough to go around. We neither need nor want competition for the "best" DDA player, and don't even know how we'd define that. _The Rule of Fun is prime: if it isn't fun, you shouldn't be doing it._ That said, super-intense stuff may happen (and it may happen when you don't want it to!) but the overall experience should come at you at whatever pace you choose to pursue. It should be just as possible to lead a slow and careful life in harmony with nature outside the cities as it is to make crazy laser-slinging assaults on superscience labs.

**Reality-based:** At its core, DDA is based in the real world. One that has been changed in extreme ways, but still very much the real world as we know it. The things in the game that exist in the real world should act like their real-world counterparts; things that are extrapolated from real-world things should hold true to the real-world principles involved, and things that do not exist in the real world are free to act in whatever internally consistent way they want. This includes things like population density, item stats, item spawn frequencies. It's a simulation, so there are of course limits to the verisimilitude, and in fact it's generally not a very good simulation at all, but the \*goal\* is to depict reality.

**Roguelike** in that it uses random world-gen and item spawns, eschews fancy graphics for a detailed interface and display, and emphasizes thought over reflexes. We don't place strong value on item-identification; our official take on _Permadeath_ is death is permanent. Implementation-wise, though, we're not interested in putting any effort into enforcing permadeath, including stashing the player save in a graveyard folder instead of deleting it.

**A focus on survival-sim elements** means that a large part of the game's focus is on the basic necessities of day-to-day survival after the downfall of society. There's a definite _Robinson Crusoe_ element to the game, from making your own clothes and weapons from animal skins and sticks, to constructing your own cabin in the woods, to more modern variants on this theme; turning urban detritus into specialized tools designed to make life after the apocalypse safer and more comfortable. A lot of the player's time and efforts are spent ensuring a constant supply of food and clean water are maintained, and problems like illness, infections, food poisoning, frostbite, and exposure to the elements provide a constant threat to their continued survival. In most roguelikes one's needs are abstracted down to occasionally consuming an iron ration while venturing ever deeper into the dungeon in search of treasure. In C:DDA your current 'quest' is often as simple as 'I must keep fed, hydrated, and warm' and the risk of dying from hypothermia while you are sleeping is often as great a risk as any monster.

**Scavenging:** We're sympathetic to people who want a totally self-sufficient survival game, but (as outlined below in Noncraftables) it's simply unreasonable to make certain items on your own, and some other items are simply \*much\* more easily scavenged than created. In general crafting is focused on repurposing found items rather than making things \*totally\* from scratch. A specific example is tailoring, which could use some adjustment. Found clothing (IF it's just what you need) should be superior to player-created clothing in general. Where crafted clothing shines is in filling a niche that simply doesn't exist in the civilised world, or in making clothing that's exactly what you need that you haven't found.

## Canon-checking:

* [http://smf.cataclysmdda.com/index.php?topic=4160.0](http://smf.cataclysmdda.com/index.php?topic=4160.0) This is the canon clearinghouse; requests to change things are stickied in the same board. **If you have questions, here's the place to start.**.

* [http://www.wiki.cataclysmdda.com/index.php?title=Main\_Page](http://www.wiki.cataclysmdda.com/index.php?title=Main_Page) **The wiki mainpage is merely descriptive, and not canon.** You do not start with a backpack (by default), and though you can certainly play DDA as a grim deathmarch, that's your style, not the _only_ style. ;-)

* [https://www.youtube.com/watch?v=iC8dlT7SFa0&noredirect=1](https://www.youtube.com/watch?v=iC8dlT7SFa0&noredirect=1) **The Kickstarter video is based on canon at the time, but is primarily descriptive.** Subject to revision.

* [http://smf.cataclysmdda.com/index.php?topic=644.msg7086#msg7086](http://smf.cataclysmdda.com/index.php?topic=644.msg7086#msg7086) (Forum post introducing powered armor)

* [http://smf.cataclysmdda.com/index.php?topic=1719.msg20298#msg20298](http://smf.cataclysmdda.com/index.php?topic=1719.msg20298#msg20298) (Power Armor MK II forum post) **Creator's notes regarding things they created (provided the relevant PRs were/are accepted) are canon until & unless determined otherwise.** These Power Armor posts are examples of in-universe forum advertising, as well as creator notes: fine job of lore-work.

* [http://www.kickstarter.com/projects/568375735/cataclysm-dark-days-ahead-dedicated-developer](http://www.kickstarter.com/projects/568375735/cataclysm-dark-days-ahead-dedicated-developer) **The Kickstarter, like its video, is based on canon at the time it was made, It's accurate unless superseded elsewhere.**

## Atmosphere:

There have been disagreements from time to time over DDA's atmosphere, and even us devs don't always have a completely shared understanding of what the DDA-world looked like prior to the Cataclysm, nor exactly what it will change to be. But here's what we're working towards, and what we'd like you to aim for:

**Overarching**: The DDA world takes itself fairly seriously. Stuff that exists for comic effect (Such as Actual Cannibal Shia LeBoeuf) should be encountered rarely at most, and should be "missable" without causing hardship to the player. (ACSL **doesn't** have a super-duper knife only available from him, for instance.)

 The world will change, significantly, over time. In the years following the Cataclysm, the Fungus will work to colonize as much of the planet's surface as it can (and we aim to allow you to help with that!), the Blob will further reanimate corpses and develop them into bigger, scarier, and more effective troops (aiming to make the planet more hospitable for itself), Triffids will do their best to develop their gardens, and so on.

 Keep your gear real, or reasonably close to real. For example: Vibroblades might be an experimental development from the electric carving knife, but would not be commonplace. Plasma swords are not feasible, especially as the plasma gun in-game is first-gen. Likewise, caseless firearms exist IRL but have not been a widespread commercial success. Rivtech firearms had been making inroads before the Cataclysm, though. We are ~30 years from now (204X). **When in doubt, talk it out.** We're happy to work with people on their ideas, and even if we reject the idea outright, best to do so before you put in the time and effort.

 **Glossary** :

"Prime" and "subprime" are dimensional references. Earth's dimension is the "prime" one (likely thanks to human-centric naming conventions ;-) ) and most of the major players arose from teleportation experiments which opened portals to the "subprime" dimension. In general, it's easier (takes less energy) to travel from sub-prime to prime. As a result, subprime life will find it easier to get to "here" than humans will find it to go "there" (or to send them back there). However, they may not enjoy the experience.

"Critter" is the official term for stuff that moves around in the DDA world. "Denizen" is a critter from the subprime dimension; because conditions in the subprime planes are significantly different from those here on Earth, most denizens cannot last very long on Earth. Those that we see are either particularly adaptable, or hang out close to the portals so they can get some help from home. (Probably for similar reasons humans hang out near/in the points where oxygen is available in gas form, rather than dissolved and blended with hydrogen. It's easy for us to get into the "liquid" plane, but not to thrive there!)

We generally use US English, with preference for New England regionalisms if possible (since DDA is set in New England).

**Pre-Cataclysm** the United States was somewhat more corporate-dominated and right-wing than it is today. The most immediately-obvious result of this is that the citizenry is encouraged to arm itself against the threat of Communist invasion from China and/or North Korea. (This is why houses have a significant amount of fallout shelters and weapon-storages.) In practice, this encourages the widespread distribution of hunting and personal-defense weaponry; burst-capable and full-automatic weapons remain in military (and increasingly militarized police) control.

Peak Oil has had little widespread effect on the US transportation scheme: heavy-duty steel frame cars are the norm on US roads, as are semi-trucks hauling goods about. Underground light-rail, ride-sharing, and alternative-power vehicles have been steadily increasing, but marketing efforts have been lackluster and people regard them as lower-class. Regional subway systems are being worked out in the Northeast US as a way to maintain transport in questionable weather (and as a Civil Defense measure).

With power generation largely transferred to nuclear plants and the populace increasingly comfortable with it (and the regulatory oversight considerably less strict), Atomic! consumer goods have become commercially viable. Likewise, the initial drive for bionic augmentation (for the Troops) has resulted in higher-end consumer electronics being integrated into one's body, though bionic gear remains largely unaffordable for the working classes.

In efforts to cut government spending, however, the police departments have largely been converted to droid-based operations. Police officers in these times are either mechanical, machine operators/maintainers, or there to handle things the bots can't. Similar increases in automated processes have displaced workers throughout the US. As such, unemployment is a constant threat (if not reality), and enterprising folks with access to the resources have started going into various criminal enterprises. Marijuana micro-grow operations are commonplace, drug gangs are on the rise, and localized tech-head and hacker groups are getting back into the swing of things.

In short, the pre-Cataclysm United States is in another Gilded Age. There's plenty of Nifty and Shiny Stuff for the USA! USA! USA!, but not much thought to how it's used, whether it'll still be there for the grandkids, or whether the country's actually doing the right thing.

 **The C:DDA World** is largely a matter-of-fact dystopia. Humankind wasn't paying attention, broke the world, and is now buying it. The larger culture didn't value human life, though individual humans certainly valued theirs, and there's a far greater tolerance for violence there than (hopefully!) is or will be present IRL. Things that fit this theme will probably work--for instance, there's one proposal to have smaller land mines intended for hunting game floating around. Though such gear is Ludicrous IRL (mines are likely to cause painful, slow deaths and destroy edible meat, so dishonorable and a liability), in DDA's world they might be acceptable to get rid of those pesky varmints.

 **Specific locations** may aim for particular sorts of feeling. Factories, offices, and such will probably show very little distinction in the architectural design, but workspaces may show signs of the worker who was there (items, etc). Mines and other such sites will largely be void of particular concern for the workers--just get it done. Labs are due for a mapgen rework, but didn't pay much attention to isolation and safety protocols--get the information out and exploitable faster! Combat sports may well be popular, and schools/exhibition venues will likely be popular. (Consider the existing dojos, upcoming gym, and so on.)

**Supernatural influences** definitely exist in DDA, but they all tend to flow from the same sources. The primary rules remain that a) it has to be fun; b) it needs to have a Cata twist. No just plopping your favorite $THING into the game unaltered.

_Lovecraftian Horrors_ are basically everything that came out of the portals; they're from the next dimension "in". Several such creatures have actually arrived, and chances are that more will show up. They aren't guaranteed to be exactly like the stories, but then that's how Cata Operates.

_Zombies_ are a subset of the _Blob_ (AKA _XE037_), that stuff in the slime pits, lab fridge-rooms, etc... It moves in on living organisms--including the player--and takes over once they die. We tend to favor a blend between the "shambling horde" and "high-speed killer" models: most zeds are somewhat slower than the average player character, but those the Blob has had the time and resources to upgrade become increasingly more dangerous. The Blob is a major subprime player, and interacts with the prime world through inhabiting, modifying , and controlling host bodies, at least until conditions alter to favor its natural forms. (That'll take a while, both in-game and to code; the Slime Pits are the best it's done, and they are NOT where it wants to be.)

_Artifacts_ are likewise in the Lovecraftian frame. If someone codes "_Magic_", it should follow the same general principle. Powerful in the right situation, but tough to clearly understand How It Works, and typically requiring a significant toll from the user.

_Mutations_ are, for the most part, highly-specific alterations courtesy of specially treated Blob infusion. The Swimmer Zombies are a good example of this sort of principle in effect. Human science has gotten a bit of a handle on harnessing these effects, though research was abruptly redirected and as abruptly halted by the Cataclysm. (For the most part. Information was flying even after New England fell, as seen with Raptor, but chances are most facilities are dead now.)

 _Marloss Mutations_ are planned. The Fungus can do more than just make you emit spores: it's a major Nether player too, and much better at terrain-modification. Not as versatile with the animal-mod, though. Very much a factional thing.

_Martial Arts_ may get Cinematic at the high ends; in particular, the Kung Fu forms will eventually be quest-rewards, and at that point they might permit supernatural effects. Chi and all that. At this point, we're keeping them tame, because there's no way to slow or restrict the progression.

_Unearthed Horrors_ tend to originate from manga: the Spiral Cavern and Amigara Fault, in particular. More love for Subterranean Terrors is a good thing, as we're likely to develop the underground further and it would help to have more variety. (Even converting the existing worms and Graboids to function underground would be a good start.)

_Psionics_, at this point, are pretty much confined to Lovecraftian, Unearthed, and Artifact effects. Some mutations might theoretically help against them, but at this point developing that sort of power in a human (that remains functional in human society) seems... unlikely at best. (Maybe the cult might know something, though. After all, those flesh-angel beings seem awfully terrifying…)

**Development and mods:**

A "mod" for the purposes of DDA is a chunk of content that \*ships with the main game\* and can be turned on and off. There's a certain amount of support for third-party drop-in content, but the official policy is that if you want your content to keep working, it needs to be included in the main distribution.

How a mod is implemented is subject to change over time, currently a mod is a chunk of content stored in a separate folder/file to allow easy activation/deactivation. In the future a mod will most likely be defined by a set of white/black lists that tell the game which content to include and which content to ignore.

A separate but related issue is game defaults. The content as outlined in this document establishes the default setting for DDA, the game will be configured to use content matching this definition "out of the box", but everything is subject to configuration by the end-user, to the limits of what the implementation will handle. The guiding principle for inclusion with respect to content that exists in reality is whether it is common enough to feasibly encounter in the given scenario. Unreal content needs to match the tone of the game in the context where it appears.

Content is categorized in one way or another to make this configuration process user-friendly. The canonical example is "classic zombie mode", which is an alternate and also supported game mode that only includes unnatural elements from "classic zombie movies" such as Night of the Living Dead. Content will also be categorized for easy inclusion/exclusion primarily based on genre-bending elements that break immersion for some, such as super-science, infeasible weapons, or anachronisms.

This configurability places limits on the amount of savegame compatibility we support. We currently support loading savegames generated by versions `0.8` and `0.9` of the game, with saves produced by intermediate development versions supported on a best-effort basis. We only provide savegame compatibility if you use the same content configuration of the game as the version that produced the savefile. If you change the game configuration and it makes the game incapable of loading your save properly, it is \*not\* a bug.

Long-running mental trauma, sanity meters, etc are mod territory: they can certainly be fun and add value to the game, but not everyone wants them, whether for distaste, triggering, or simply not interested.

**Game progress**: it's primarily the character/player's development, in skills, gear, and traits. Player knowledge is a factor as well. At this point, quite a few folks on the forum have the player-skill aspect Down, so they tend to jump into what currently passes for late-game. We plan on adding more and nastier challenges as time goes on.

It's probably best to think of things in GlyphGryph's four stages, which he laid out in the IRC transcript below.

The _Survival_ stage can be rather short if you avail yourself of decent gear; you'd need fire, cutting implement, storage, and utensils, then to work out sources of food and water. Absent scrounging or other such boosts from pre-Cataclysm civilization, this stage can still be hazardous.

_Growth_ happens once you've got the basics down. At this point, you're actively targeting long-term development, whether through seeking libraries, training skills, or simply reconnoitering the area. Nevertheless, you're working with what's available. One's goals focus on improving one's capabilities.

_Influence_ might be termed actively targeting goals. Where before you might see a Semi out of fuel and think "I'll grab that sometime,"now you'd know the nearest source of gas and where you might take the Semi for processing. "Sometime" is now.

_Transcendence_ involves actively modifying parts of the world… bearing in mind that the player character is xemself a part of the world. Building a mobile base, engaging in planned-mutation or bionic programs, and so on are current examples of Transcendence. We aim to have these take significantly longer-term roles as we continue adding to Cata.

````
[17:28] \<@GlyphGryph\> I think the game has, or should have, 4 stages. Survival. Growth. Influence. Transcendance. You go from struggling to survive the apocalypse to becoming someone capable of dealing with it on its own terms. From there you move from someone responding to the events that are happening to them, from someone at the mercy of the world, to someone who influences how the new world takes shape. And finally, in one way or another, you truly leave your pre-cataclysm life behind and become something that is truly part of the world you helped shape. Change is inevitable - when the player starts he may think eventually he can create a pocket of sanity in whcich he can reverse the Cataclysm, but the character eventually has to accept that and decide to change the world and themselves with it instead of fighting for a dead reality.

[17:33] \<@GlyphGryph\> To me at least the Cataclysm is what the player is in, but its not an end - its a transitionary stage

[17:34] \<@GlyphGryph\> And yeah I think NPCs and factions will be needed to really get there

[17:34] \<@GlyphGryph\> There are ways to hit every step without them though

[17:36] \<@GlyphGryph\> Eventually, and I know this will be incredibly contentious, but I think its true, eventually I dont even think there should be any more zombies

[17:36] \<@GlyphGryph\> To me the zombies are the 'living' embodiment of the transitionary period

[17:37] \<@GlyphGryph\> stuck between life and death, between human and alien

[17:38] \<@GlyphGryph\> I know there are a lot of people who want it to be a zombie game first and foremost

[17:39] \<@GlyphGryph\> Well right now they are basically a transitionary step for the netherum invasion, since it is using them to establish a foothold in our world until it figured out a way to adapt

[17:39] \<@GlyphGryph\> Theres several places they could go

[17:39] \<@GlyphGryph\> See my threa about them serving as eggs for specially adapted new netherum critters
````

We're against "having zombies die off" or replacing them throughout DDA with non-zombies. In line with our plans for progressive difficulty, they can certainly become tougher, develop special abilities, etc, and SOME of them could be co-opted by the fungus or processed into unrecognizability by the Blob, etc, but both thematically and as a practical consideration we believe players would feel betrayed by significant removal of zombie content, considering that the game is billed foremost as a zombie apocalypse: there will NOT be any wholesale removal or replacement. Bigger, nastier, 'evolved' zombies are good, removal of zombies is bad. They need not be everywhere (though the planned Roaming Hordes will take things to the wilderness, more so than the zombear has already) but they're not leaving outright.

_Old proposals (some that succeeded, some did not, some just haven't happened):_

* [http://smf.cataclysmdda.com/index.php?topic=4667.msg71814#msg71814](http://smf.cataclysmdda.com/index.php?topic=4667.msg71814#msg71814) Infection levels & nether-threshold (the Nether Cliff; will likely happen at some point)

* [http://smf.cataclysmdda.com/index.php?topic=4077.msg59005#msg59005](http://smf.cataclysmdda.com/index.php?topic=4077.msg59005#msg59005) Advanced zed-thread (GG referenced this one at 17:39; this is primarily a hasn't-happened, though significant zed-reduction is a nonstarter)

* [http://smf.cataclysmdda.com/index.php?topic=2113.msg26507#msg26507](http://smf.cataclysmdda.com/index.php?topic=2113.msg26507#msg26507) Nether-Critter Briefing (these either already exist, or are plpanned for future development)

* [http://smf.cataclysmdda.com/index.php?topic=1266.msg14532#msg14532](http://smf.cataclysmdda.com/index.php?topic=1266.msg14532#msg14532) The Labs, notes therefrom

* [http://smf.cataclysmdda.com/index.php?topic=1226.msg14047#msg14047](http://smf.cataclysmdda.com/index.php?topic=1226.msg14047#msg14047) Sludge Crawler (which is now in-game, more or less as worked out here)

* [http://smf.cataclysmdda.com/index.php?topic=1131.msg12554#msg12554](http://smf.cataclysmdda.com/index.php?topic=1131.msg12554#msg12554) Actem Labs (one of many corporate players in the DDA world)

* [http://smf.cataclysmdda.com/index.php?topic=502.msg5329#msg5329](http://smf.cataclysmdda.com/index.php?topic=502.msg5329#msg5329) Design thoughts (the notes on player-preferences are relevant to GlyphGryph's at 17:28)

_Materials_:

These are our working thoughts, and are subject to solid discussion/research:

 _Iron_ for large tools, display weapons, etc: metal that's not intended for combat or harsh-condition applications. (The Crowbar might be iron. Halligan, not.)

 _Steel_ is high-quality steel, though we're fudging the differentials between weapon-grade, stainless, etc. It should be much less susceptible to rust, but not rustproof.

 _(Alloy)_ would be the player-craftable upgrade from Steel and less-than-Superalloy hypothesized in the Noncraftables section. Rustproof and perhaps marginally lighter than Steel.

 _Superalloy_ is probably high-tech titanium/memory plastic blend or somesuch, made in Labs, in orbit, or otherwise generally rare and expensive. You might be able to produce Steel, almost certainly Iron, but you are not crafting Superalloy.

**Mutation categories, etc:**

No category should be totally undesirable. It may not match what you want (for this character's RP, your playstyle, etc) but no category should be completely "useless, purify it now". That's content that isn't getting used and is bloating the game.

Basic perspective on categories (all include post-Threshold):

_Lizard:_ Light tank. Will ideally accommodate Lizard Style's wall-buffs and possibly chameleon mutations once there's some reason for 'em. (Bear in mind that chameleon only does you any good if you don't cover it with clothing.) Currently takes Large for the gator/Komodo angle.

_Bird:_ Fast ranger type. We're planning to add Down as an upgrade to Feathers--should help in Winter. Point regarding their Food needs (birds IRL eat a LOT as compared to their body weight) is well taken but something on the order of Humming wings might help that. Will rebalance the current Eagle Eyes trait as "Scout", "Lookout", or somesuch and probably make an eye trait for Bird. Currently considered mid-priority as they lack significant post-Threshold traits.

_Beasts/Cattle:_ Tanks of various weight. Ursine and Cattle are intended as the heavies, with Lupine and Feline both potent but limited. Very Sleepy should enforce a different playstyle, and we'd appreciate hearing from Feline folks on that.

(_Feline & Lupine_ ought to be able to socialize & obtain packs, though the mechanics may need a Break From Reality. Generi-beasts, probably not as much and Ursine not at all--bears aren't noted as social animals.)

_Plant/Rat:_ These should be the survivalist categories: plants would thrive topside, deriving sustenance from light and soil BUT would be increasingly unable to eat directly (thus, a slower and more deliberate style); Rats would have difficulty being out and about in the daylight but become increasingly able to handle anything. Eat questionable food, shrug off diseases, sleep without useful bedding, etc.

(Both would be able to obtain followers.)

_Fish/Cephalopod:_ These very badly need better Z-level support and mapgen work to have underwater terrain. They're intended to flow toward sharks, Deep Ones, and other Lovecraftian outcomes--no worries--but there's no point in living Under The River if you can't actually live there.

_Troglobite:_ (That's how it's spelled in DDA) These folks are shaping up as Cata's take on the fort-builders. With some more love for construction and underground terrain--upcoming megaproject, you might say--we could make underground life something worth taking, as opposed to the ooops-you-mutated-badly category it is now.

_Spider/Insect:_ Spider's currently hamstrung: migrating effects to one unified file has left its venom and webbing pretty much useless. (This would be an excellent place for some programming backup; get in touch with KA101 and coordinate!) Insect might go for Bee/Bloodsucker lines; becoming a Queen is theoretically possible but I'm not sure whether it's worth the fallout.

_Slime:_ This'll likely be a quick & dirty Crawling Chaos line. Dex bonuses at the expense of ST (your arms become increasingly flexible... but your lack of rigid structures limits your leverage, etc). Might get eyestalks, eventually improving PE and minimizing blindness, but that'll be an initially-negative chain. Passing through bars and under doors would be worth considering, as would be engulf-attacks and splitting off smaller versions (as with the Blobs) when you take enough damage.

_Medical:_ End-stage Medical is someone totally out of it from pharmacological prototyping, and also bloody tough to bring down (super healing, pain-proof, etc). In short: the world's toughest chemotherapy patient!

_Alpha:_ This is the only one who could still function in human (read: non-mutant) society post-Threshold. No mutations here would give more than 1 ugliness/noticeability, and I'm planning on adding some mental-fortitude to go with the statboosts. Post-thresh gives Impressive stats and might also give better looks, but that's low priority.

_Elf-A:_ These folks will become increasingly slime-warped forest-humans. You won't be able to live among non-mutant humans, but when you appear you'll have dramatic effects (good & bad) and ought to be able to survive fairly well, provided you didn't get some of the nastier downsides. Once Research gets into the game, sufficiently science-minded chars might try refining the design.

_Chimera:_ Yeah, these folks typically don't live long. So if you breach the threshold, we're inclined to make you a force (and, incidentally, a bit more survivable). Once we've got the critter-rework settled, they'll be able to eat (for hunger/health) in the middle of combat, literally chewing and swallowing when their Bite attacks kick in, and if that doesn't pique your interest

_Raptor:_ Carnivorous and predatory tendencies are certainly present. These are a boosted combo of Bird and Lizard, and will ideally get a lethal two-hit combo around the Capstone level (claw knocks target down, jaws tear it open). Combat and staying power should stick around, though the Very Heat Dependent should make winters tough.

_Marloss/Mycus:_ I've pushed this back a few times based on the scale of the work it needs to be done properly: two more Fungal Bloom types with new berries and monsters along with the new mutations. No promises on when it'll happen, but we seriously want to make it happen.

_Nether:_ Low-to-non priority ATM. If someone wants to work on this, it'd help to compare notes with KA101 so everyone's on the same page, but this is something likely to happen.

**Gear-check:**

Remember, C:DDA is taking place in post-apocalypse New England. For some reason (FPS games are the likely culprit) a lot of contributors seem to think the game needs a bunch of Warsaw Pact weapons, and to take it to a new level of annoying, they're generally obsessed with WP guns that were produced in quantities numbering in the dozens. While it would be fine for an additional-content-mod, there's no good reason to find super uncommon WP guns lying around rural New England in the base game. Of course stuff like _common_ Kalashnikov variants, SKS, PPSh, and the like, which are common in the USA IRL, are okay. Same rule goes for super uncommon guns of any nationality; the AA-12 is a prime example which has been requested numerous times (those danged video games!) even though there's only been ~20 of them ever made. Stuff that is that uncommon really doesn't need to go in the game. There are a good number of guns that can get pushed out to various "rare gun" mods, available for those who don't mind the unreality of the situation. (Some already have been.) There's other content in the same boat, but let's be honest, guns are the worst offender here. And if for some reason you absolutely must have a Super Unique… change the name, file off the serial numbers, and have the decency to give it a good backstory. If we can't tell it's That Super Unique, then it's got a better chance of making it in!

**Noncraftables**: Some stuff just can't be accomplished with the resources available post-Cataclysm. You would have to build the tools to build the tools, and that's likely to take generations. Here's a list of stuff that **won't work and why**.

**Solar cells** in-game are high-efficiency models, which require industrial chemicals and processes. You can't duplicate those with the resources available. Homemade cells are certainly possible IRL and if someone wants to code them they'd be acceptable... but would need to be significantly less efficient than the current solar in order to pass.

**Burnt out bionics** (as in, a core component for bionic-crafting, as currently implemented) involve a lot of microelectronics and biotechnological Stuff. Forges and soldering irons aren't up to the work required to make that sort of gear.

**Power Armor** requires machine tools, to put it nicely. You might be able to make an addition or upgrade the helmet, but building a suit from scrap ain't gonna happen.

**(full-size) Storage Batteries** use high-end technology (lithium-ion or Newer!) to store a Lot of power in a fairly light & compact unit. Lead-acid batteries are much more feasible.

**Kevlar, Nomex, superalloy, and similar ultramodern materials** require fancy chemical processes and high-tech machinery that no longer exists in a functional state. Perhaps late-game science-types might be able to create small batches of functionally-similar yet inferior materials using the best chemistry and manufacturing equipment the game has to offer, but things like this should really stay as loot to be scavenged, and not made. Carbon fiber and fiberglass are examples of borderline materials; as we understand it, carbon fiber is quite possible, if extremely difficult, to work with using artisan methods. It has its own built-in downsides though. Likewise fiberglass is something that an individual can reasonably craft with, though creating the chemicals used for either is probably beyond the abilities of an individual. So though you might find and work carbon fiber or fiberglass "stock", you won't be able to produce more.

**Engine blocks and minireactors** likewise require precision machining and industrial processes. You might be able to craft an electric motor, but that's in the same vein as the solar cells: likely bulkier for the power output, at minimum. Be glad that C:DDA cars don't need transmissions or brakes! ... Yet.

**Semi- and full-automatic firearms** for the same reasons that engine blocks are out of the question: precision machining is not available. Gunsmithing a revolver might be feasible (the Revolver Shotgun) and there are several air-based weapons. You might be able to kludge together a firearm made out of mods (conversion kits and the like) but in practice a good black-powder piece would probably be more effective.

**Comment by ZhilkinSerg** [comment]
And [here is gist](https://gist.github.com/ZhilkinSerg/11bad962a9bb2eaa37eb82600ce6c57f) for those interested to make a PR.

**Comment by KucharczykL** [comment]
Unless I'm doing something wrong, links pointing to http://smf.cataclysmdda.com are not working.

**Comment by ZhilkinSerg** [comment]
Ofc, they aren't - that are outdated links to forum on old host which should changed.

**Comment by mlangsdorf** [comment]
I also site searched for the dead smf links and put up my best guesses for their current locations.

**Comment by kevingranade** [comment]
I've been working on a new design document for a while now, but it's not up to rough draft state yet, so I haven't published anything.

**Comment by mlangsdorf** [comment]
Added the old "Frequently Made Suggestions" posting to the wiki.

**Comment by kevingranade** [comment]
As i said, its not at rough draft yet, its barely a skeleton at the moment.
This thread is really helpful though.

**Comment by kevingranade** [comment]
https://discourse.cataclysmdda.org/t/draft-of-the-cataclysm-lore-writeup/10345

**Comment by kevingranade** [comment]
Ok, here it is, officially published at long last, the "good enough, damnit" edition.
https://cataclysmdda.org/design-doc/

**Comment by nexusmrsep** [comment]
So, no central road map, no TODO list of ideas fished out of forums qualified for future implementation. Just old docs and and forums where good ideas are mixed with bad ideas and wishful thinking and are often lost in time. I know you ain't got time for that, but in a long time I'm seriously disappointed by that nothing will be done on that field. The issue section on GitHub is no better, with many feature requests not judged by their validity, and not bunched together to unclutter this section.

**Comment by kevingranade** [comment]
There is a roadmap, https://github.com/CleverRaven/Cataclysm-DDA/projects/23

If there is an issue not on the roadmap that you think belongs, feel free to bring it up.

If you want to go fishing on the forums for ideas and turn them into issues, feel free, you don't need me for that and we have enough to work in the tracker now for years. We've been getting somewhat organized using the projects feature, but it's an incremental process.

> Just old docs and and forums where good ideas are mixed with bad ideas and wishful thinking and are often lost in time.

Did you read the new design doc? Yes it's not comprehensive, but this stuff takes serious investments in time.
