### ISSUE TITLE
Acidic Ant Larva turns in to Acid Soldier Ant upon spawning

### ISSUE THREAD

**Issue by SomeDeadGuy** [CleverRaven/Cataclysm-DDA#27464]
If i spawn any number of Acidic Ant Larva they all emidietly turn in to acidic Ant Soldier. And i tried finding them in Ant Hills but it is always adult acid ants and no acid larvas.
Normal giant ant larvas are present in ant hills and do not turn in to ants as soon as i spawn them with debug menu.

**Comment by Night-Pryanik** [comment]
Debug menu isn't officially supported and thus can cause all sorts of weird stuff, I'm inclined to close the issue, sorry.

**Comment by SomeDeadGuy** [comment]
Wow, slow down there, buddy. I said what they dont spawn in nature too. There are no acid larvas in anthills, however there are ton of adult acid ants.

**Comment by DracoGriffin** [comment]
Yeah, looks like this got fudged in the life cycle updates (You can see in the original #23238 acid ants and normal ants had the same half life upgrades). I'm guessing on this as I can't find the exact change, since ants were removed from monsters.json and ported to insect_spider.json

Acid ants just need to be updated to normal ant values and this will be fixed.

     "id": "mon_ant",
     "upgrades": { "age_grow": 14, "into": "mon_ant_soldier" }, // this was changed in the lifecycle updates

     "id": "mon_ant_acid",
     "upgrades": { "into": "mon_ant_acid_soldier", "half_life": 0 }, // this wasn't updated
