### ISSUE TITLE
Disassembling basket of plastic yields too much material.

### ISSUE THREAD

**Issue by BBlankie** [CleverRaven/Cataclysm-DDA#27478]
![image](https://user-images.githubusercontent.com/44106380/50761630-d9884100-12a5-11e9-97aa-43c43e095000.png)

**Comment by DSeyka** [comment]
Item description states as much: "A plastic basket meant for storing and hauling clothing."
![image](https://user-images.githubusercontent.com/34726992/50765085-dbdaa300-1285-11e9-9551-531d46ab89d0.png)

**Comment by mlangsdorf** [comment]
Laundry basket masses 680 grams and a plastic chunk masses 70 grams.  Salvage yield should be calculated from mass, not volume, and should be 9 in this case.

**Comment by DSeyka** [comment]
Fair enough.
I thought the material itself was the issue, not amount of produce from disassembling.

**Comment by davidpwbrown** [comment]
Is this to suggest that salvaging materials is not calculating correctly from mass, in ALL cases, or just in this case?

**Comment by mount2010** [comment]
No, this is Working As Intended. A laundry basket (suitable for large mutated anatomy) is 100 units of volume (25l). Disassembling means you're cutting volumatric chunks out of the laundry basket. In this case, you're cutting 0.25ml chunks from the basket (iuse_actor.cpp: minimum_volume_to_cut). Adjusted for skill loss 99 is almost perfect.

Because you're mostly cutting the *area*, however, again we run into a problem. A laundry basket isn't a solid block of plastic to cut chunks out of! My proposal is to specify JSON "disassemble" manually, to make better sense that you're cutting up a basket (with empty space in it) rather than a block of plastic.
... which makes me think, it should really yield sheets of plastic instead.
In this case we're talking 11(meters?) of plastic per side.
