### ISSUE TITLE
Obtaining 196 portions of vinegar from 14 portions of fruit juice

### ISSUE THREAD

**Issue by Degvik** [CleverRaven/Cataclysm-DDA#27473]
**Describe the bug**  
There are two options to get unfermented vinegar:

1) 14 fruit juice (plus 7 water) -> 14 unfermented vinegar 
2) 1 fruit juice (plus 3 water) -> 21 portions of fruit wine must -> ferment to 21 portions of fruit wine -> 14 unfermented vinegar

so, with the first option you spend 14 fruit juice and 7 water to obtain 14 unfermented vinegar
with the second option you spend 14 fruit juice and 42 water to obtain 196 unfermented vinegar

**To Reproduce**  
1. Get 14 fruit juice and supply of water. Perform crafting steps as described above.
2. Do the same with the second crafting option

**Expected behavior**  
I expect to have the same or similar amount of vinegar from both crafting options, if they both use the same amount of fruit juice, instead of the second option giving 14 times more. 

As it is, with the addition of 35 water you get an extra 182 unfermented vinegar, which is clearly wrong.

**Screenshots**
Here the screenshots show where the numbers go off:
https://i.imgur.com/MSTurF4.png (21 'fruit wine must' creates 21 fruit wine, but only needs 1 fruit juice)
https://i.imgur.com/AwGB9t6.png (unfermented vinegar needs 21 fruit wine or 14 fruit juice)

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version 0.C-36130-g4098edb
 - Graphics version Tiles
 - Mods loaded: I checked the recipes in the game with no mods active! The bug is still there.

((The game I first noticed this had the following mods: Dark Days Ahead, Disable NPC Needs, Filthy Clothing, Simplified Nutrition, Nonperishable Overhaul, Makeshift Items Mod, More Survival Tools, Boats, Folidng Parts pack, Vehicle Additions Pack, No Fungal Monsters))

**Additional context**  
E.g. A link to a savegame that allows the issue to be reproduced.

**Comment by mlangsdorf** [comment]
1 unit of fruit wine is 41 grams.
1 unit of vinegar is 127 grams.
1 unit of fruit juice is 263 grams.
1 unit of water is 250 grams.

vinegar is made from ethanol, and fruit wine is probably 10-15% alcohol - call it 5 grams per unit of fruit wine.  Most vinegar is 5-10% acid, so the fruit wine recipe probably should make 1 unit of vinegar per 2 units of fruit wine.

1 unit of fruit juice producing 21 units of fruit wine might be a bit sketchy, but I don't know how the numbers work on wine production.  It doesn't seem crazy.

Since the two processes are supposed to be the same chemical process, just starting at different points, vinegar production from fruit juice should be increased to 10 units of vinegar per unit of fruit juice.

**Comment by KorGgenT** [comment]
note that in #27289 vinegar's portion size will change
