### ISSUE TITLE
[RFC] New human factions

### ISSUE THREAD

**Issue by mlangsdorf** [CleverRaven/Cataclysm-DDA#27479]
## More human factions needed
Currently, the game has 6 NPC factions, but there's really only 3: Your Followers, the Wasteland Scavengers, the Old Guard/Free Merchants/Tacoma Commune, and the Hell's Raiders.  The Hell's Raiders are always hostile (currently) and Your Followers are basically an extension of the player.  So it's really just the Free Merchants as a mostly friendly group, the Wasteland Scavengers as an unorganized group, and the Hell's Raiders as an enemy

There should be more non-hostile human factions who are not necessarily friendly with each other.  That would add scope for more missions, including diplomacy or war between factions.

This topic is intended to brainstorm some new factions and possibly start work on them.

## Obvious factions
I'm either borrowing other people's ideas or using some very obvious concepts.  This list should be expanded.

#### Survivalists
Description: "Some people knew the End was coming and prepared.  Now they intend to keep what is theirs."
Size: Small (half the size of the Free Merchants?)
Attitudes: Extremely hostile to the Old Guard (who they see as having caused the Cataclysm) and the Robofac (who they just don't trust).  Generally suspicious of the Free Merchants for being Old Guard allies.  Generally not hostile to other factions, and trying to be decent people in a tough situation, but they're not about to provide charity for people too foolish to prepare.
Bases: A farm.  Seeking to expand to other farms, missile silos, or military bunkers.
Trade: Barters copious ammo supplies for diesel, alcohol, etc.  Doesn't have currency but will use promissory notes for specific things to round out a barter deal.
Missions: Go find that one thing they forget to prepare, get them luxury goods that they want but thought they could do without, weaken the Old Guard, deal with hostiles.

#### Robofac
Description: "The scientists of a working lab."
Notes: The lab is barely functioning, but the Melchior AI has taken control of the remaining staff and is now running the place.
Size: Small (half the size of the Free Merchants?)
Attitudes: Hostile to the Old Guard (Melchior doesn't want to be controlled).
Bases: A small, partially working lab.
Trade: Uses precious metal coins for currency.  Sells ultra-tech wonder products.   Buys food, basic goods, plutonium cells, information.
Missions: Acquire science specimens, provide replacement science equipment, set up radio repeaters near other labs, hook other Melchior networks into this lab's network, acquire gold and silver for its currency.

#### Zombie Cult
Description: "Madmen who think they can make friends with the zombies."
Size: Small
Attitudes: Mildly hostile to everyone, but also desperate.  Making friends with zombies is hard, and they need help surviving until they make contact with the zombie brain.
Bases: Desolate buildings.
Trade: Barter random scavenged good for food, clean water, etc.
Missions: Sabotage other factions, learn more about the zombies, attempt diplomatic relations with the Nether things.

#### Marloss Evangelists
Description: "Mutants have eaten of the Marloss berry and now preach the only way humanity can survive."
Size: Medium
Attitudes: They would like to have good relations with all factions, but people keep setting them on fire.
Bases: Fungal areas.
Trade: Barter random goods for random goods.  They will round out trade with promises of future marloss berries.
Missions: Spread the fungus, convert other factions, destroy nether creatures and triffids, intercept people trying to destroy the fungus.

#### Fence Men
Description: "Former convicts who have taken over the prison and now seek to trade to improve their goods."
Notes: Mildly unsavory, but more "mean people in a bad situation" than "outright evil."  Well, maybe evil depending on how you consider slavery, but they're not going to shoot you for breathing.
Size: About the same as the Free Merchants
Attitudes: Hostile to the Old Guard, but otherwise neutral or friendly.  Trades with the Hell's Raiders.  Sometimes donates to the God's Chosen.
Bases: Most of a prison - parts of it are still blocked off with zombies inside.
Trade: Uses bullets for currency.  Sells wrecked robot bits, raw material from the prison, or slaves for food, water, medical supplies, etc.
Missions: Acquire farming supplies.  Conduct diplomacy with other factions.  Sabotage Old Guard.  Handle trade with the Neo Natives because the Fence Men don't want to end up in anyone's cooking pot.

**Comment by SeelenJaegerTee** [comment]
**Deserters:**
Soldiers who defected when shit hit the fan.
- Relations: They wish the Old Guard would let them alone, but the Old Guard wants them on trial since they are deserters.
- Size: one squad
- Attitude: Either marauders that will trade with anyone they consider a threat and rob people they consider an easy pick. Or they could be decent folks who just wanted to survive (or got disconnected from their unit) and are now helping other survivors - would make it especially awkward when the Old Guard wants the player to execute the deserters but they are actually the knights in shining armour who protect the weak.
- Base: campsite or cabin
- Trade: need ammunition will give combat training
- Missions: Diplomatic relations with old guard/other factions

**Gods Chosen**
A religious end of the world sect - but this time a good one.
- Attitude: harmless pacifists, will never attack living humans
- Size: A hand full of families.
- Base: A cathedral.
- Trade: offer small crafts, clothing, wood, food, will provide low level medicine for free
- Missions: protect us from X, retrieve religious artifact, retrieve bible

**The great library** (obviously this is one of the great wonder's of the post-apocalyptic)
Some surviving scientist(s) and librarian(s) have set themselves the task of preserving humanities knowledge.
- Base: fortified library
- Attitude: friendly
- Size: should be a rather small faction
- Trade: are looking for food, books and electronic components will offer training and stuff they can build from said components
- Missions: retrieve books, retrieve artifact for study, scavange technological equipment

**Comment by Epictyphlosion** [comment]
**The Strongarms**
A group of somewhat crazy gun-nuts 

- Attitude: Anyone who has harmed the faction or a faction member is considered an enemy, and faction members are required to shoot enemies on sight. Enemies of the faction are given the option to clear their name, but only if they pay a hefty fee. Outsiders are allowed to visit their bases and purchase goods, but they cannot stay there, and they are constantly watched by faction members to ensure they are abiding by their rules. People that have friendly relations with a Strongarm member are trusted, and allowed to stay at their bases. They are very territorial over their faction's belongings, and charge higher than normal prices for goods.
- Base locations: Shooting ranges, fortified homes, gun stores (rarely)
- Size: Medium-small
- Trade: Lots of guns, ammunition, armor, and gun mods, as well as some food, water, medicine, bandages, and sometimes things like tools and materials. They can trade with cash or items. Most items, especially firearms and ammunition, cost higher than normal if your reputation isn't high enough with the faction.
- Missions: Killing enemies of the faction, Rescuing captured faction members, Looting gun stores or armories (sometimes from rival factions), Repairing X's firearm(s), Finding X a new firearm

**Comment by SeelenJaegerTee** [comment]
**AMSL** (Adolescent mutated shinobi lizards)
Four Lizard mutants living in the sewers together with their rat-mutant master.
- attitude: friendly towards photojournalist profession
- base: under a sewer cover
- faction size: 5
- Trade: Fast Food items for martial arts training
_________

And now to the serious version:
**Brotherhood of the Tentacle**
A band of mutants that have made bad experiences with non-muties after the end of the world.
- attitude: unfriendly or even hostile to everybody not visibly mutated, friendly to everyone with visible mutations
- base: a cave
- faction size: probably small
- Trade: want mutagen AND/OR purifier serum 
- Missions: would be awesome if there were two mutually exclusive paths a revenge path where the player sabotages other factions for them and a diplomatic path where the player negotiates friendly relations between the other "good/neutral" human factions

**Comment by kevingranade** [comment]
You might be using it as a catchall, but instead of zombie cult it should be mycus cult, since mycus actively wants to recruit.  I think the utterly deranged and fruitless zombie cult would work too, but it seems like a more minor faction.

**Comment by mlangsdorf** [comment]
There are probably multiple tiny zombie cults, made up of people who have lost their minds, that pop up and die within a few months.  While the Marloss Evangelists are slowly growing in strength.

Faction (Abbreviation)  | Size | Membership
-- | -- | --
Fort Evac (FE)  | Micro | 3-5 people depending on how you count
Bravo Deserters (BD) | Micro | 5-7
Zombie Cult Cell (ZCC) | Micro | 2-5
Brotherhood of the Tentacle (BOTT) | Tiny | 12-15
Neo Natives (NN) | Tiny | 14-18
The Great Library (TGL) | Tiny | 15-20
God's Chosen (GC) | Small | 4-5 families of 2-6 people.
Zombie Cult (ZC) | Small | 4-6 Cells
Robofac (RF) | Small | 25-35 people + Melchior
Farm Survivalists (FC) | Small | 4-5 families of 3-6 people
Strongarm Survivalists (SA) | Small | 4-5 families of 3-6 people
Free Merchants + Tacoma Commune (FrM, TC/RR) | Medium | 60-80 people (supposedly)
Fence Men (FeM) | Medium | 50-70 ex-convicts
Marloss Evangelists (ME) | Medium | 50-60 mutants
Old Guard (OG) | Large | Hundreds off-screen, and 2-20 on screen
Hell's Raiders (HR) | Large | Hundreds

**Comment by Epictyphlosion** [comment]
> Strongarm Survivalists (SA)	Small	4-5 families of 3-6 people
That's a much better name compared to what I wrote, lol

**Comment by I-am-Erk** [comment]
The Campus

Medium sized faction formed by a group of people who were evacuated to a college campus, managed to survive there, and have formed a community.

Makeup: lots of young adults and university professors as well as members of the nearby community. About 60-80 people.

Disposition: begins slightly idealistic and anti-old-guard. At some point they are taken advantage of by the free merchants and become a bit more jaded. They aren't foolish though; they have strong defenses and are probably one of the more powerful factions in the region.

Qualities: the campus is quite large and well fortified. They have a few raiding groups that have gathered supplies and secured the nearby area. They begin white welcoming to newcomers, but become more xenophobic (like everyone) over time. After a period of time they become quite reluctant to trade.

General notes: the people of the Campus were somewhat less hard hit by the cataclysm, owing largely to their younger age meaning fewer zombies intially, and them having more capable combatants. This doesn't mean they don't fear zombies, but they're less risk averse than most other factions. On the other hand, the campus provides most amenities they need to survive, with fabrication and science facilities as well as comfortable living dorms and underground tunnels allowing movement between buildings without going outside. It's pretty ideal. While the average campus-dweller isn't keen on going to the outskirts of town to find food, they don't have too much trouble putting together raiding parties large enough to actually make some headway.

Grey areas: early on  the campus becomes quite unwilling to work with other factions. The old guard got us into this, the free merchants only care about themselves, and the Raiders are the Raiders. This will translate into hostility and distrust to the player as well, unless the player starts the game as a member as well. Because they feel like they have this well in hand (and they kinda do), it should be very difficult to earn their respect.

**Comment by peperov** [comment]
The Hell's Raiders shoot on sight, but one possibility to get in contact with them could be via two-way radio. Let's say the player picks up some conversation oder maybe a call for help. Upon investigating he finds a group of raiders trapped and out of ammunition, giving the player an opportunity to pick a side. As far as I know there are already some missions in the refugee center that involve killing Hell's Raiders, so there could be a possible plot turn in which the player instead allies the HR and betrays the refugee people.
A great narrative would be to have the HRs save the player from captivity of some sort (save him but enslave him) and have the player work himself up the psycho-hierarchy from being slave of a member to finally being assistant of a leader.
I'm not entirely sure if this can at all be done within the game, but it's some food for thought. Maybe we can come up with a more simple solution.

**Comment by Quintovir** [comment]
**The Radiant Ones**
Description: A group of mutated people who are both radiogenic and radioactive.
Size: ?
Attitudes: The Radiants are happy to interact with anything that will openly accept their radioactivity, but anyone who strongly shields themselves from radioactivity or are immune to it are not welcome. Anyone who actively tries to denuclearize the Radiant agenda are to be killed on sight.
Bases: Radioactive places (random places and nuclear craters) or places with radioactive materials (nuclear silos and spent nuclear storage warehouses).
Trade: They always have an ongoing nuclear PPE (hazmat suit, anbc suit, etc) and Prussian blue/Potassium iodide buyback program (burned/destroyed immediatly). They sell plutonium and anything that runs on plutonium. They buy all the food and drink you have for sale, since their constant nausea causes them to vomit regularly.
Missions: Their mission is to make the world a radioactive place by launching nukes and sending their members to irradiate other places/people. Launch nukes or detonate nuclear bombs on designated targets. Escort Radiants on their missionary work.

**Survivalists**
"promissory notes" cash cards?
"Trade:" I would add tools, weapons, guns, and standard drugs as merchendise. Preppers tend to have a lot of backups.

**Zombie Cult**
"Trade:" they might want to buy armor and drugs (disinfectant, antibiotics, bandages, etc) to make their interactions with zombies safer and longer.

**Fence Men**
"Trade: Sells... slaves for food" once you buy these slaves will they turn into standard NPC followers?

**Comment by Sniperman1109** [comment]
Knights OF The  Cataclysm.
•Description: The Knights of the cataclysm are made up of a buch of medieval  fanatics who not only studied the way if the knight and the fighting style of them but also always took a liking to the  architectural types buildings that were im the medieval ages as well. They got their armors by either owning them prior to the cataclysm or they found armor on scouting runs in mansions, pawn shops, musems, and they also have a few among them who can craft armor aswell that being they have they right resources.
• Attitude: they are weary of outsiders and their tecnology but will still welcome those that have a level head and wont start trouble in the towns.
•Faction Size and makeup: the faction size is small due to the fact that most didnt care about the medieval era and dont wish to live as our ancesters once did, but alas they are growing from taking on those who do not mind converting their lifestyle/beliefs over to the Knights OF The Cataclsyms beliefs. Mostly the population of the faction is made up of mosly men ages between 18 and 60, and a decent amount of women ranging from 18 and 60.
•What they wish to Acomplish: The Knights of The Cataclysm want nothing more then to carve out their own piece in the world of CDDA and wish to possibly recreate society in a medieval form minus some of the more barbaric ways like in the oldin days.
•Towns/Bases: They vary from small villages with a few peasents and few lightly armored milita to semi sorta big settelmets with a stone wall surrounding the paremitor of the town with gates at every entrace along with guards stading next to them letting people in or out “if this is possible”.
•Trade: even tho they dont like tecnology they srent fools either and know that this is still a modern world and they will need things like guns, kevlar armor for the utmost protection agaisnt bullets, and things that can help preserve food, and food itself.
•Missons:  “A Lord of sorts should give these or a village leader/ elder” Rescuing  enslaved peasents or captured knights who fell in battle. Get the black smith some materials and he could make something for you as payment. Helling a farmer get some seeds so he can grow more food for the village. Taking out some bandits that have been coming into town robbing the town or trade caravans. Taking a villager/merchant to another town guarding then ensuring their safety etc.
I hope you guys like my faction idea! Ive actaully in my playthrough have been trying to make my faction medieval and dress eveyone in medieval  attire. I really hope this finds its way into the game! Let me know what you guys think!

**Comment by thethunderhawk** [comment]
I think it’s important not to over saturate the world with survivors. I know it’s ancient, but that old design doc painted a world near-impossible to survive in. I believe a core concept was the idea that “The Walking Dead”-style survivor communities aren’t feasible, and for humans to survive the new world they must change fundamentally into something more than human. I have trouble with the idea of simple communities surviving past the first couple seasons.

**Comment by kevingranade** [comment]
> I believe a core concept was the idea that “The Walking Dead”-style survivor communities aren’t feasible, and for humans to survive the new world they must change fundamentally into something more than human.

This is definitely not intended.  Ordinary humans can survive and even thrive as long as they know what they're doing and don't draw too much attention from strong factions.

**Comment by thethunderhawk** [comment]
@kevingranade understood, thanks for clearing that up for me

**Comment by I-am-Erk** [comment]
It's still pretty bleak, but it's not a mandatory transhuman thing. There's certainly not going to be any big reset button on the world.

**Comment by kevingranade** [comment]
AFAIK we moved everything we wanted from this to the [design document](https://cataclysmdda.org/design-doc/]
If we missed something feel free to ping this issue about it.
