### ISSUE TITLE
Zone menu CTD, plus Error: Tried to access zone on unloaded vehicle

### ISSUE THREAD

**Issue by Solusphere** [CleverRaven/Cataclysm-DDA#27487]
I recently performed a major reconstruction of my vehicle, which had previously included a full zone configuration. Upon completing my renovations, I tried to remove all existing zones in order to reassign them. Initially, simply accessing the zoning menu caused a CTD, which was repeatable three times (while I was gathering info for creating an issue here) before the fourth attempt seemed to work without any problems, despite using the same save in all attempts. On the successful attempt, I managed to remove all the zones except one, which produces the titular error message upon attempted removal, and as far as I can tell can't be removed. Note that the displayed position seems to be consistent, and moves with the vehicle.
![image](https://user-images.githubusercontent.com/19789267/50815081-d6995900-1356-11e9-9813-a7963344219d.png)
![image](https://user-images.githubusercontent.com/19789267/50815093-def19400-1356-11e9-9584-e64bdb417dc4.png)

On a hunch, I tried quitting the game, loading the save again, and trying again. Once again, it crashed, as it seems to do on the majority of attempts to access the zone menu while the vehicle is in the reality bubble. Crash log here: 
![image](https://user-images.githubusercontent.com/19789267/50815242-6212ea00-1357-11e9-9005-076ff69e68fa.png)

I'm using build 8390, though the reconstruction of the vehicle took place on build 8382. I'm attaching the affected save. I'm keeping these both as one issue as it seems likely they have the same root cause.

[Gearhart.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2735510/Gearhart.zip)

To reproduce the crash, just hit Y upon loading the save.

**Comment by MetroidHunter** [comment]
Im not sure when I'll get around to it this week but, I plan to look at this sometime this week

**Comment by MetroidHunter** [comment]
Somehow, your vehicle has a loot_zone at -2,7 but it no longer has a cargo part there. There is logic already to remove loot_zones on parts when they are being removed but it would appear that did not fire off. You are left with your vehicle assuming there is a loot_zone at -2,7 and when it goes to get the absolute position of that loot_zone by finding the actual cargo part, it turns up a negative index which crashes the game by passing -1 to the parts array.

Im going to add a check to make sure the part exists. If it doesnt, debugmsg and remove it. Its better to alert and have to replace the zone than have the entire game crash and past that, theres not really a lot of options to fix this since there are a million ways you could have placed zones and rebuilt the vehicle

Ill also look at what happens with removing the zone

**Comment by kevingranade** [comment]
Fixed by #28142
