### ISSUE TITLE
Lab Monster idea: Spectre

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#27504]
I had a good idea today, but I have no time to build this. 

**Is your feature request related to a problem? Please describe.**  

Labs are currently the be all end all loot source, yet suffer from being quite easy to explore once you have made it out of the early game. With few actually dangerous enemies, labs provide all the mutagens and gear you need to make it most of the way to the end game.

Mid to late game characters have a few things that make the game more easy, but one big contributor is powerful armour that renders many enemies trivial. Most enemies that can best your armour are invalidated by a control laptop.

**Describe the solution you'd like**  
Many things could change, but I thought of one that would specifically return some of the horror elements to the Lab, while also fixing some of its difficulty without making it too boring or frustrating.

The Specter: a lab specific monster
Description: a shimmering, barely visible illusion, like a mirage. Up close you can see an emaciated, panicked looking human in a lab coat reaching towards you.
Stats: the Specter is invisible until adjacent to you, like a shade zombie at night. It uses similar code to a mi-go to randomly make sounds, like soft sobbing, wailing, and scratching noises. It is essentially invulnerable to physical attacks and can't attack physically either. Some artifacts that do non physical attacks might damage it. It moves just a bit slower than a survivor's walking speed, can see through walls like the clairvoyance artifact, and has a keen sense of smell.

It should be able to either walk through walls at reduced speed, open doors, or teleport short distances to move through obstacles. It would be lame if it could be circumvented by a closed door.

Its main attack is a special: it reaches out plaintively to you, its limbs passing through your armour and burning your flesh, doing something like 1-5 damage ignoring armour completely.

Natural outdoor light kills it, so that it can't leave the lab.

Spawning: this should be a rare creature that only spawns in labs. Ideally there should only be one per floor of a lab, and most labs should get one.

**Describe alternatives you've considered**  
Countless

**Additional context**  

This would provide a hard counter to just holing up in a lab and relaxing, and create a race against time scenario. The enemy is pretty weak at first and can be walked away from, but if you try to jackhammer through a wall or something, it will find you and stop you. Because its attack ignores armour, it's a pretty equal threat at most stages of the game.

If someone makes this, I'll see about adding some interesting lore and stuff about it eventually.

**Comment by Night-Pryanik** [comment]
Do you have a strategy in your head to kill this monster? Because if it's mostly invulnerable, and the only way to not to be killed by it is to run from it, it will be simply uninteresting (imo, of course).

**Comment by logros13** [comment]
Have to agree with Night-Pryanik here, the rest sounds good but having it be unkillable sounds tedious and frustrating more than anything else. 

Maybe have it susceptible to electric damage if you don't want it damageable by ordinary attacks? that could give currently mostly useless weapons like tasers an interesting niche?

**Comment by AMurkin** [comment]
Who you gonna call? Ghostbusters!

I agree, there should be some ways to deal with them.

**Comment by I-am-Erk** [comment]
Well, you could lure it outside into the sunlight. Failing that, I'd like to add quest based solutions, like a lab machine that does it. I don't mind it being killable, but I don't think it should be killable by just walking into it with a very good unarmed skill.

**Comment by SirPendrak** [comment]
I quite like the idea, but there are some things we need to remember. 
First, lab start scenario. Theese characters need to be able to sleep in a lab until they break free. 
Second, reality bubble mechanic. In a really big lab one could lure it to the far edge of lab, and then sprint out from it, essentially trapping it there, as long as you dont get close again. Also, should it be able to cross Z-levels if this option is enabled? 
Electricity being one of the few things that damage them sounds neat, but wouldnt it be just: From now, allways carry a taser when entering a lab. All problems solved. 

Maybe it shouldnt be a monster per se, but rather a mechanic of location? 
At first, when you stay too long in one place in lab, you get chills running down your spine, and your morale drops. Then you get a little cold, and some pain. After that, true Spectre spawns, sloowly consuming you. Darkness speeds up the process, while radiant light slows it down. Mowing from one place to another reverts the process, but runing in circles or very erarly backtracking shouldnt work. Also, it should only attack if you are allone. Sleeping next to a cell with shoggoth, zombie brute etc. might scare the spectre away, as might bringing a lot of companions or friendly doggo. And killing spectre should give you a break for a few hours, but then it will despawn.

**Comment by I-am-Erk** [comment]
> I quite like the idea, but there are some things we need to remember.
> First, lab start scenario. Theese characters need to be able to sleep in a lab until they break free.

That's a bit of a concern, but lab challenge is also supposed to be a challenge. Currently, I'd say the only really challenging bit is getting past the turret at the main entrance.

> Second, reality bubble mechanic. In a really big lab one could lure it to the far edge of lab, and then sprint out from it, essentially trapping it there, as long as you dont get close again. Giving it horde mechanic could solve this. Also, should it be able to cross Z-levels if this option is enabled?

If I were designing it, I think I'd make it unable to cross z-levels, but having one monster in the entire lab and making it able to go freely up and down z-levels would also be fun.

> Electricity being one of the few things that damage them sounds neat, but wouldnt it be just: From now, allways carry a taser when entering a lab. All problems solved.

That's why I'd want the damage vulnerability to cycle. If you kill it with a taser, it respawns several hours later, and now it's vulnerable to fire damage. Or maybe you got unlucky and now it's only vulnerable to radiation.

> Maybe it shouldnt be a monster per se, but rather a mechanic of location?
> At first, when you stay too long in one place in lab, you get chills running down your spine and hear strange noises, and your morale drops. Then you get a little cold, and some pain. After that, true Spectre spawns, sloowly consuming you. Darkness speeds up the process, while radiant light slows it down. Mowing from one place to another reverts the process, but runing in circles or very early backtracking shouldnt work. Also, it should only attack if you are allone. Sleeping next to a cell with shoggoth, zombie brute etc. might scare the spectre away, as might bringing a lot of companions or friendly doggo. And killing spectre should give you a break for a few hours, but then it will respawn.

That would be pretty cool, I like most of that stuff. I think it should still be something that appears when it gets within range, because it would lead to some nice jumpscares. However, handling it more like an effect that accumulates in darkness would also be really interesting. I really like the idea of darkness and light having an effect. Perhaps, if left as a monster, rather than taking damage from daylight, it should simply not be able to enter light areas? That would solve your lab challenge issue, you just need to find a safe illuminated place to sleep.

Running in circles to avoid it shouldn't be too big of an issue. The problem isn't supposed to be so much "oh no the specter caught up to me, how am I going to get away", it should be "oh no, the specter caught up to me, now I have to leave this room and go somewhere else." It should be slow enough that as long as you don't linger for too long in an area, it's fairly safe to move around and explore, but as soon as you start gathering every item and flask and hauling them back to the entrance, or jackhammering through plate glass to access the goodies you weren't able to hack into, you're in trouble.

**Comment by kevingranade** [comment]
> First, lab start scenario. Theese characters need to be able to sleep in a lab until they break free.

If theres a choice between adding an interesting mechanic and *removing* lab starts, the interesting mechanic wins.

I like the idea of there being an underlying effect instead of a distinct monster implementation  wise.

**Comment by SeelenJaegerTee** [comment]
> > First, lab start scenario. Theese characters need to be able to sleep in a lab until they break free.
> 
> If theres a choice between adding an interesting mechanic and _removing_ lab starts, the interesting mechanic wins.
> 
> I like the idea of there being an underlying effect instead of a distinct monster implementation wise.

One could also disable the spectre for lab challenge starts.

I think it would be awesome if the spectre couldn't be killed but if there was some condition to get rid of it. Some kind of semi-random conditions that the player needs to achieve to banish the spectre, that can be inferred from its behaviour.
Then there could also be the option that some spectres want to find rest others not. That way some spectres just try to bully the player into achieving the goal while others try to inhibit the player.

"Friendly" spectre
- approaches PC from a direction that a fleeing PC gets closer to the goal
- only attacks PC until he has dangerously low HP (doesn't want to kill the player after all), is still problematic for the player when other mobs can finish PC off easily).
- will risk killing the PC when he tries to leave to the surface floor
- threatens PC when he is close to items and only attacks PC when he picks up items not required for banishing

Hostile spectre
- approaches PC from any direction but tries to bully him away when the PC gets too close to the goal
- will deliver killing blows to the player, but will for a long time "play" with his prey (to confuse the player so it's harder for player to guess whether it's a hostile spectre)
- will attempt killing the PC when he tries to leave to the surface floor
- threatens PC when he is close to items and will attack PC sometimes when they pick up non-quest required items but always when picking up quest related items

For lab starts just spawn a firendly spectre. That way the player still has a realistic chance to finish the lab challenge.

Goals to banish spectre could be:
- find dead body of spectre and bring a certain item to it (picture of loved ones, lost item)
- find dead body of spectre and pulp it/burn it/...
- shut down some sort of machine that binds the spectre to this world
- activate a machine that can banish the spectre
- attack spectre with a specific weapon like tazer, ignited torch, ...

**Comment by AskaHope** [comment]
Spelunky reference detected!

**Comment by I-am-Erk** [comment]
I should note that my vision of a specter isn't a ghost with a body, it's a xedra scientist stuck between dimensions.

**Comment by Amneiger** [comment]
A stuck scientist?  If you got them unstuck and back in our dimension, could you recruit them, or get some useful item or information from them?  It'd be a pretty good reason for a NPC to be grateful enough to do what you say.

Seconding the idea of the spectre being tied to some dimensional machine.  Maybe they can't go a certain distance from the machine?

**Comment by I-am-Erk** [comment]
Eventually it should be possible to rescue them, but with a very high mortality rate.

**Comment by Amneiger** [comment]
Had a few thoughts on this at work today, and came up with an idea.  It might need coding that doesn't currently exist.  In any case:

The spectre would be tied to whatever dimensional machine had sent them into this state, and would not attempt to go up or down floors.  Instead, it will approach the player and stay very close to them, occasionally creating messages about the spectre waving their arms.  Interacting the spectre (through the "e" command) will allow you to look at what they're doing.  A high intelligence check should reveal that they're using Morse code and are trying to say the words "freedom" and "danger," followed by pantomiming using a rifle.  If you're in the room with the dimensional machine, they should frequently 
point at it.  A computer check on the machine will get the player access to the dimensional tunneling system, which has something like this to say: 

MASS DIMENSIONAL FATIGUE DETECTED 

FAILSAFE ACTIVATED

RETURN PROTOCOL SUSPENDED

ALERT: XEDRA PERSONNEL WITHIN DIMENSIONAL SUBSPACE - COMPLETION OF RETURN PROTOCOL REQUIRED FOR RETRIEVAL OF SCIENCE TEAM.

WARNING: UNKNOWN ENTITY DETECTED WITHIN DIMENSIONAL SUBSPACE.  UNKNOWN ENTITY MATCHES PROFILE OF KNOWN HOSTILE SUB-PRIME ORGANISMS.  ORGANISM IN RANGE OF RETURN PROTOCOL.  DANGER LEVEL: HIGH.  

Here's what happening: the scientist was exploring another dimension and was attempting to come back when the Cataclysm happened.  The system that was supposed to bring them back was halted, trapping them between dimensions.  Completing the return protocol will bring them back here, giving them freedom.  The danger they were trying to warn you about is the unknown entity, which is a Nether monster which followed them into the dimensional tunnel and will be brought back with them if you use the return protocol.  They're miming a gun to tell you to be prepared for combat.

At this point, the player would be presented with two options:

The first is **Emergency Eject**, which will send both the scientist and the monster to the other dimension.  This gets rid of the spectre, but has no other rewards.  

The second is **Complete Return Protocol**, which brings both the scientist and the monster to the lab.  The monster should be something stronger than a mi-go - maybe a wraith or a hunting horror or a Thing.  The scientist will have a low-tier pistol and their lab coat, and they'll spawn closer to the monster than you, which should cause the monster to focus on them first.  Unless you're well prepared and have excellent skills and gear, the monster will kill the scientist.  (There's no time limit on this choice.  A player can leave and come back whenever they feel like they're capable of fighting the monster.) 

If you manage to save the scientist, the scientist will be grateful and reward you.  You can recruit them, or ask them for skill training (they have very high science skills but minimal combat training) or high-tech gear.  I don't want them to hand out lab reward items like quantum solar panels or energy weapons, but at the same time they should have something more useful than the chemistry set lab techs already start with.  Another option might be unlocking all computers and doors on the floor. 

Another option for characters who are technically inclined - a combined very high computer/electronics skill and intelligence will unlock an option to bring back only the scientist (the character figures out a way to cut off the return protocol after the scientist is back but before the monster can emerge).

**Comment by FulcrumA** [comment]
@Amneiger 
I really like some of the ideas, but some things I'd prefer to be adjusted.

First, I worry whether it'd be worth adding the location-dependant behavior of the scientist (pointing to the machines etc). Since I don't recall seeing something like this so far it'd probably require quite some new code written for it. I do like it quite much and can see how the same code could be repurposed in the future for other NPCs responding differently depending on what room or building they're in.

NPC I'd randomize. Some, rarely, could use morse code or pantomime but I'd like also to see simply panicking, screaming, haunted victims whose sanity is clearly affected. Or even lifelessly looking, staring, dejected and still silhouettes. I'd similarly randomize results of calling the NPC back - beside lab/security/technician/janitorial staff skills and gear (since why not randomize the type of NPC who'd work at the lab as well - that doesn't seem too hard to do and would help maintain freshness of it) of various quality, there shouldn't be ensured monster that'd come with the NPC. In fact, I'd prefer it to be 50% chance at most, with the creature being also potentially something weaker. However, at the same time, I wouldn't mind it if said NPC wouldn't be assuredly friendly - many could be scared, confused, suspicious and/or neutral, some could be grateful for saving them but some could also turn paranoid or be driven mad by the experience and lash out at the player, possibly with a last-ditch chance of calming down dependant on player's speech skill and intimidation roll in case of most extreme cases (possibly initial NPC behavior as a wraith could give some inidicator here as well).

Similarly I'd randomize the device the NPC is tethered to somewhat. Some could be operational and require hacking offering the choices you've listed, but some could be somewhat damaged, be it by mysterious physical attack or by clear signs of power surge - some burned cables and whatnot. Depending on those, hacking, electronics or mechanics could be used to have the machine operational and options allowed.

The point of it all would be to randomize whole scenario from start to finish, rather than making it linear "wraith mime appears, shows you through the process, player prepares to battle the monster and save returned scientist, gets reward and/or NPC" every time a player would stumble upon such event. It would also make the cause a bit more vague rather than "every goddamn single time I stumble upon such NPC, they're stuck in alternate dimension with some nether pal". In general, I would make spawning of such creatures an unexpected event caused by return procedure and for the NPC to leave simply more simple explanation of "whatever happened during the cataclysm stressed out fabric of reality and shitload of devices in the laboraties went haywire" - that way the randomization works better than a particular exact reason for particular, single situation - it isn't given and just repeated and the event/quest can be more easily expanded later as well as well as be more believable when stumbled upon repeatedly.

**Comment by Amneiger** [comment]
@FulcrumA 
I like everything you're saying about randomization.  I'd like to set it up so that every time the game creates a spectre, it also makes sure to create at least one random significant problem with trying to bring the spectre back, such as your suggestions about the NPC being hostile or the monster I'd suggested earlier.  Maybe the room with the device is full of turrets, or there's an environmental hazard, or the NPC is heavily wounded and needs an immediate difficult first aid check to save their life.  There should definitely be clues as to what the important problem is, using the spectre behavior you'd suggested (and possibly a few other things).  This will give players a fair chance to prepare. 

I'd suggested a dangerous monster because I recall from reading the lore pages on the wiki that in the initial days of the cataclysm, there were lots of dangerous monsters that eventually died when the major interdimensional portals closed.  I also remember that occasionally when traveling I'd find a portal with a few nether creatures such as flaming eyes nearby.  This all points towards the possibility of a creature 
that wouldn't normally be in our reality coming through. 

The randomization would be some work to implement.  We could put together a bunch of different 
spectre situations by hand and add them to the lab generation code, or set up something up where the game pulls randomly from a list of possible spectre types and problems.  

Spectres should be a very rare event.  I'm thinking that there shouldn't be more than one spectre per lab, maybe no more than one spectre every two to three labs.  We should probably make sure that the reward matches the difficulty of saving the spectre.  I-am-Erk said that he was thinking in most cases rescue attempts would end in the NPC dying in the process, which makes sense; over-populating the cataclysm doesn't feel right to me.
