### ISSUE TITLE
Road Rollers are too large

### ISSUE THREAD

**Issue by mlangsdorf** [CleverRaven/Cataclysm-DDA#27520]
Road rollers currently have a diameter of 60" and a width of 60".  That makes them the ultimate off-road wheel with a staggering 3600 wheel area.  The treads of an M1 Abrams main battle tank are only 50" wide IRL, and a tank's tread should have much more wheel area than a road roller.

Road roller width should be be reduced to 30" and the diameter to 48", which is still 50% wider and 50% larger in diameter than an armored wheel.

**Comment by SeelenJaegerTee** [comment]
The Problem for the rollers would also be that they have zero profile.
No profile combined with being rigid means that a normal tire that deforms onto the ground should have a higher contact area.
Perhaps add something like a 'BAD_OFFROAD' flag?.

**Comment by boydkr** [comment]
A road roller should also weigh a couple tons and have a moment of inertia much higher than any other wheels.

The problem statement here is too prescriptive of the solution, I think, if the road roller works too well as an all-purpose wheel.

**Comment by DavidEdwards** [comment]
Perhaps you could use tyre surface area?

Knowing the wheel radius and width you can determine the flat surface area of the rim. Then you can have the surface area of the tyre. Working with those two numbers you could determine a single metric.

Traction = TyreSurface - RimSurface

If the Traction value is too low, the roller will just rotate in place. Whereas a wheel would have a larger TyreSurface value compared to RimSurface (due to grooves, etc), giving it more traction.

Sure, it isn't the only contributing factor, but it should be enough to simulate on-road / off-road?

You could even have higher quality tyres to find.

**Comment by mlangsdorf** [comment]
Fixed in #27723
