### ISSUE TITLE
Change grenadiers "on-death" effect to "on-low-hp"-effect

### ISSUE THREAD

**Issue by SeelenJaegerTee** [CleverRaven/Cataclysm-DDA#27555]
**Is your feature request related to a problem? Please describe.**  
![screenshot from 2019-01-11 18-58-17](https://user-images.githubusercontent.com/39884350/51051214-706d3a00-15d3-11e9-93bc-634d72ca31db.png)
This annoys me.
I don't mind the fact that zombie grenadiers exist. I also don't mind their explosion per se. It's just the fact that there is literally no way to prevent their on death effect.
Realistically severing the brain stem (or cutting/blowing the head right off) ensures that all communication between brain and body is shut down.

**Describe the solution you'd like**  
On death effects that realistically would require actions by the creature in question should instead be actions they perform upon reaching a certain HP threshold. If you deal enough damage to move them from above the threshold to dead in one single attack it should prevent them from performing those actions.

**Describe alternatives you've considered**  
Implement functionality to target specific body parts. On-death effects are only reliably prevented by head shot-kills. Torso kills have a percentage change that increases with damage of killing attack (higher stopping power).

**Comment by SirPendrak** [comment]
If this gets implemented, the"on-low-hp" effect only should happen if creature gets its turn after loosing required HP. For example, if you shoot .45 SMG at point blank with 10 round burst, and first 3 bullets damage grenadier enough to reach treshold, he should not activate this skill, because next 7 rounds will finish him, and he does not have time to open his pockets.

**Comment by Barhandar** [comment]
> Realistically severing the brain stem (or cutting/blowing the head right off) ensures that all communication between brain and body is shut down.

Unless in the past year CDDA drastically changed the lore, zombies _do not care_ about said communication. They're dead and being puppeteered by the Blob, hence their ability to revive. "Death" is simply critical shock/damage that requires pause to recover from; which is why actual-death required (likely requires) smashing or destroying the corpse (damaging it beyond Blob's ability to use the tissues).


However, beyond invalidating your point of targetted shots, this does not affect the issue - zombies that are taken out in single, or close to single, attack shouldn't get to trigger special abilities that rely on explicit actions, be it exploding, vomiting, or somesuch.

**Comment by thethunderhawk** [comment]
>...which is why actual-death required smashing or destroying the body.

We already have that represented in game in the form of “gibbing”. If you blow a zed to bits it can’t revive. If nothing else that definitely ought to prevent on-death effects.

**Comment by anothersimulacrum** [comment]
This effect no longer exists, I think this can be closed.
