### ISSUE TITLE
Make unaided safecracking an activity

### ISSUE THREAD

**Issue by Kodiologist** [CleverRaven/Cataclysm-DDA#27667]
If you don't have a stethoscope, the game allows you to guess the combination for opening a safe, which has a suitably small chance of success. Now, what if you don't have a stethoscope but you do have plenty of time, so you want to just guess till you get it right? (Or, more sanely, you want to start at all zeroes and work your way up?) There doesn't seem to be a way to repeatedly guess blindly without pressing some keys for every guess, which is pretty tedious. Why not make it an activity that just takes some time until it succeeds, like safecracking with a stethoscope? I guess it would take 30^3 * (6 seconds) / 2 = 22.5 hours on average. I could take a crack at this (pun intended) if it sounds desirable.

**Comment by Quintovir** [comment]
Makes sense.
Maybe require a piece of paper that turns into "safe cracking notes X, X (coordinates of safe location)", so that in case you stop or are interrupted your progress is "saved" and can resume your task later.

**Comment by Kodiologist** [comment]
Notionally, no notes are necessary if the survivor is starting from all zeroes and going up. When he returns to the task, he can just keep going from whatever number he left it at.

**Comment by GoLoT** [comment]
If I'm not mistaken a safe that requires a stethoscope to be cracked has a dial, not just one of those suitcase locks with 3 independent rolling things. It can use a 3 or 4 number combination. If it's 3 numbers its 100^3 different combinations (101 I guess, since its 0-100 both included), taking at least 10 seconds to test each combination because of having to reset it and turning the dial a few times per attempt.

That's... 1030301 combinations and 10303010 seconds to test all of them, so 17171 minutes or 286 hours to go through all combinations. On average that's 143h for a single safe, and 100 times that if it's a 4 number combination. And that's if you keep checking combinations every 10 seconds, which is tedious and would probably drive you crazy after minutes or hours.

Considering any person would slow down after a few attemps and probably make a few mistakes here and there, I'm not sure how viable it would be.

**Comment by Kodiologist** [comment]
I can't speak to whether Cataclysm safes are supposed to have suitcase-style or single-dial locks, but [the code](https://github.com/CleverRaven/Cataclysm-DDA/blob/d2d65ae2bc7ee7b96b0583ef7c45395546388f59/src/iexamine.cpp#L1032) implies there are only 27,000 possibilities.

**Comment by GoLoT** [comment]
Since that's the only reference to the number of combinations it might just be a number that whoever wrote the code put there. From what I can find standard safes use dials with 101 numbers. They possibly used that as a way to make it pretty much impossible without it being an automatic failure.

**Comment by Kodiologist** [comment]
It would certainly be reasonable to decide that Cataclysm safes actually require 4 spins on a 100-number dial, decrease that chance to 1 in 100 million, and say that there won't be an activity to brute-force the safe because an activity that takes 124 game years to complete on average isn't useful.

**Comment by kevingranade** [comment]
Cheap safes have a significant amount of slop, roughly speaking if you use a number adjacent to the correct number it will work.  I believe this is why the code uses 30^3 instead of 100^3.

This is still not a particularly reasonable way to try and crack a safe, so I'm not excited about adding it as a non-joke mechanism.  If you want to make it better, take a look at how safes actually work and come up with a mechanism for brute-forcing them, but don't take a jokey stab in the dark and turn it into something that looks like it's a reasonable thing to do.

**Comment by Kodiologist** [comment]
Perhaps I misunderstand you, but this isn't a joke. The method I'm proposing requires no knowledge of the mechanics of safes, just guessing the first possible combination, then the second possible combination, and so on; that's what I mean by "brute force". If there only a few combinations, it's a feasible method. Otherwise, it isn't, unless you supplement brute force with tricks that actually do use some mechanical feature of the safe, like the tricks Richard Feynman described. And I guess I wouldn't recommend adding that, since the game already represents more intelligent safecracking with the stethoscope method.

**Comment by kevingranade** [comment]
What I'm saying is the ``one_in( 27000 )`` mechanism is a joke, don't use that as a basis for something serious.

**Comment by DeltaEpsilon7787** [comment]
Considering that you don't need to preserve the safe or most of the time they don't even have anything valuable in the first place for an early game survivor, I think this idea has no real use out of a joke way to do things.

If you really want to expand safe-cracking, actual ways of doing so should be considered, like drilling in, detonating a shaped charge or simply cutting into it with an acetylene torch.
