### ISSUE TITLE
sidebar medium cosmetic changes proposal

### ISSUE THREAD

**Issue by nsklaus** [CleverRaven/Cataclysm-DDA#27666]
I have proposed a more radical set of changes for the sidebar in pull request [#27439](https://github.com/CleverRaven/Cataclysm-DDA/pull/27439) to transform it into user select-able panels instead.
while waiting to see if that idea will get supported or not, i am proposing a new set of changes that are more intermediate level: keeping the sidebar as it is with all its content, but organized differently.

a first pass would look like this:
![preview4](https://user-images.githubusercontent.com/6810861/51259272-1346ff00-19ac-11e9-8d17-378a9daadc0a.png)

it could stays like this if this is everyone's preference.

or i could continue making a second pass, 
modifying things a bit more to have a toggle between minimap and compass. here showing minimap:
![preview6](https://user-images.githubusercontent.com/6810861/51259337-383b7200-19ac-11e9-8150-b8f7aed7f5de.png)

here showing compass:
![preview7](https://user-images.githubusercontent.com/6810861/51269517-fa961380-19c2-11e9-87bd-8c6bb90a5158.png)

this whole proposal is linked with PR [#27665](https://github.com/CleverRaven/Cataclysm-DDA/pull/27665) which is a first step in that direction.

**Comment by DeltaEpsilon7787** [comment]
Strongly against this design: unless you are a beginner, you don't really need those labels. They use a lot of space and generally just as much of a clutter as the current version: they provide generally redundant information.

On that matter, a more symbolic representation of various statuses would be useful: you're already doing this for mood, sun/moon and health, but you can extend this to the rest: four colored boxes for hunger, thirst, sleep and pain, maybe a bar for temperature and lighting. The rest of the info displayed in actual numbers would actually benefit from labels somewhat, but icons are still potentially preferable.

However, there is one case I can think of where this design would make a lot of sense -- Self-Aware trait. Because Self-Aware displays a lot of actual values, labels/icons would be perfectly acceptable for it.

**Comment by nsklaus** [comment]
@DeltaEpsilon7787 
You say this design brings  a of clutter, but if you look between actual sidebar being used now and this design, the one that looks with less clutter is this here.
Beside, information without context doesn't make much sense. Could you tell of me of a rpg game for example that would show you character sheet, displaying all the character data without labels ?
How would you know what is what ? let's say you open character sheet and see:
10
08
09
10
How do we know which one is str, dex, int and per ? Without labels it is confusing. We need those.

What could be done about this is: option to enable / disable labels eventually. If that is a desired feature.
Using icons instead like you propose is a good idea.. But i don't think this project would accept that because it is mostly text based. Maybe it could be done if someone design a special font for this game that would be used for displaying what would look like icons but would be in fact custom chars from that font. That is another possibility.

**Comment by Asmageddon** [comment]
I think a much better alternative would be mouse-over tooltips for the existing sidebar. Could double as a game learning tool.

**Comment by nsklaus** [comment]
> I think a much better alternative would be mouse-over tooltips for the existing sidebar. Could double as a game learning tool.

Again, it's another idea. It depends how it is done. In the end, if it's good, then why not.. 
But consider it is "thinking out of the box". Look at the majority of games, when you open inventory or character stats screen, you don't have that kind of things.
For example, i like when i think of character info in games to use diablo 1 and 2 and fallout 1 and 2 as reference, but still, any other rpg or game with character management in it would do.

**Comment by DeltaEpsilon7787** [comment]
>Beside, information without context doesn't make much sense. Could you tell of me of a rpg game for example that would show you character sheet, displaying all the character data without labels ?

I never said you don't need context, I merely pointed out that, in a nutshell, you don't need all this verbosity at all.
Also you get used to it really quickly so there isn't even a need for labels for those stats -- just nail it down STR-DEX-INT-PER. Even then, it's not an issue because STR-DEX-INT-PER are known precisely so they must be displayed with a label and a precise value.

Icons mostly apply for SDL build only, but even in curses build you can pretty much get away with a few more bars: after all, hunger, thirst, fatigue, even pain are all bounded values that you know only roughly.

It will also give a very nice feel for those stats rather than pretty cryptic descriptions like "Distracting Pain" or "Very Hungry". Incidentally I hate those labels for pain because the sequence is pretty annoying to remember and I can guess how bad the pain is just based on the color -- the redder, the worse.

Also no, from what I gathered CataDDA does NOT appear to support Unicode characters for things and it'd stick like a sore thumb if you used them in that specific place. 

I should probably actually make a mock-up of what I propose.

**Comment by DeltaEpsilon7787** [comment]
A very specific example to consider is a recent removal and eventual return of the item bars.

There is a very good reason why a lot of players hated this or, at the very least, were confused about them. It kinda applies here as well.

Sure, it kinda takes away the fluff and makes it slightly harder to come up with a story for a character, but it's sure as hell more useful gameplay wise.

**Comment by nsklaus** [comment]
@DeltaEpsilon7787 
When you discuss with someone, when the person reply to you, do you prefer he use words and sentences or just give you a colored piece of paper to you as a whole representation of what he's trying to say to you ? .. This just humor from my part don't think too badly of it. I am just trying to say a little bit of verbosity is needed, at least in the beginning. When you are used to something, only then, it could be shortened. As in: ..ah yes i know it's the usual "xyz" meaning as always.. 
So in my opinion, an option to remove some verbosity would be good, but not as the default presentation.

**Comment by DeltaEpsilon7787** [comment]
Well, your original suggestion is specifically changing the default. If you're going through with it, there should be a legacy version then and a compact one as well.

**Comment by nsklaus** [comment]
> A very specific example to consider is the recent removal and eventual return of the item bars.
> 
> There is a very good reason why a lot of players hated this or, at the very least, were confused about them. It kinda applies here as well.
> 
> Sure, it kinda takes away the fluff and makes it slightly harder to come up with a story for a character, but it's sure as hell more useful gameplay wise.
> 
> Using colors, highlighting, gauges and bars just works better as a representation for a lot of things than vague descriptions that don't really tell you how far away you're from reaching the bottom.

recent item bar removal was not an intended feature, it was a bug introduced by me by error.
it have been added back of course.

**Comment by nsklaus** [comment]
> Well, your original suggestion is specifically changing the default. If you're going through with it, there should be a legacy version then and a compact one as well.

no need for multiple versions. a simple option setting would suffice. 
like for item bars, it is optional, and that's good.

**Comment by DeltaEpsilon7787** [comment]
>sentences or just give you a colored piece of paper to you as a whole representation of what he's trying to say to you 

That doesn't even apply here. I don't say to use colors and gauges everywhere, but for continuous bounded vague values -- that is, most stats that are now represented with vague descriptions rather than something that gives you a sense of scale. 

The most infamous example of such a thing would be hunger, which takes a decent amount of time to actually put you in danger or kill, but your characters starts complaining that he's **very hungry** not even 2% in before the actual death. With a scale, there'd be no such bullshit, it would show very clearly how much "fuel" you've got left.

**Comment by nsklaus** [comment]
> > sentences or just give you a colored piece of paper to you as a whole representation of what he's trying to say to you
> 
> That doesn't even apply here. I don't say to use colors and gauges everywhere, but for continuous bounded vague values -- that is, most stats that are now represented with vague descriptions rather than something that gives you a sense of scale.
> 
> The most infamous example of such a thing would be hunger, which takes a decent amount of time to actually put you in danger or kill, but your characters starts complaining that he's **very hungry** not even 2% in before the actual death. With a scale, there'd be no such bullshit, it would show very clearly how much "fuel" you've got left.

have you seen the other proposal i made for sidebar modification? it's a lot more compact, and less in the way of the player. you can even toggle the whole sidebar off. [here](https://github.com/CleverRaven/Cataclysm-DDA/pull/27439)
there's videos to see it in action.

**Comment by DeltaEpsilon7787** [comment]
I've checked it out and somebody told you the same thing: labels are not necessary at all.

Also, to be completely honest: date and location are not really necessary to know at all times. Even sound is not really needed most of the time.

**Comment by DeltaEpsilon7787** [comment]
Well, you do need to be aware that those stats are hidden and should only be described vaguely, not precise numerical values.
In fact, if you have numerical values, as would be cool to have with Self-Aware, then you don't need anything else -- you already know the precise value of this stat. No need for a scale or anything.

**Comment by nsklaus** [comment]
> I've checked it out and somebody told you the same thing: labels are not necessary at all.
> 
> Also, to be completely honest: date and location are not really necessary to know at all times. Even sound is not really needed most of the time.

what can i say,  make a PR to remove those ?
me i like information. the only thing is how to display it properly. and for that i think there is no way to please everyone. so the solution is: options to toggle on / off. 
so everyone can choose to their liking.

**Comment by nsklaus** [comment]
> Well, you do need to be aware that those stats are hidden and should only be described vaguely, not precise numerical values, and bars are fairly good for that.
> In fact, if you have numerical values, as would be cool to have with Self-Aware, then you don't need anything else -- you already know the precise value of this stat. No need for a scale or anything.

for the records, i think an "all bars" design would be good to have.
i would like something like this:
(here for that example, bar are on a base of 10)
```
hunger: IIIIIII... (green)
thirst: IIII......     (red)
sleep: IIIIII....    (yellow)
```

**Comment by curstwist** [comment]
Hey, a few comments on the design in the first screenshot.  

I do agree the labels are overkill and not needed except when you have multiple bars/numbers that look alike but express different information (health bars & stats come to mind).  

However, if those are kept, they need better wording.  Specifically: SLEEP, FOOD, DRINK, HEAT should be more precise.  Fatigue, Hunger/Hunger level?, and not sure about the other two.  Big problem is finding words that make sense and fit the limited amount of space.  For heat  I'd say temperature but that should be used for actual world temperature (actually you aren't showing external temperature in your mock-up, where will that fit when shown?).  Internal/Body Temp would probably be too long...  

On MOON: you have broken it out from the day/night cycle bar.  Not sure that is necessary as the day/night cycle one isn't labeled in your example.  Previously moon phase was shown during the evening of the cycle bar instead of always being shown (if I'm remembering correctly)

That segment also takes a much larger chunk of the sidebar vertically at the cost of the message log.  Move through some grassy fields and you'll lose any important information very quickly. Could it fit into 3 columns?

Not shown, but noticed in my current game.  Stats always using 2 digit (08, 07, etc) can be difficult to read especially when it is 06 & 09 due to the default font.  Can future examples have below 10 stats in some fields and also include how they look when boosted/depreciated by short term buffs, like stimulants?  Are they still color coded red and green?

Hope this input is useful for your future changes.
