### ISSUE TITLE
Exotic crossbows show inconsistent classification for gun mods

### ISSUE THREAD

**Issue by KITbutler** [CleverRaven/Cataclysm-DDA#27724]
**Describe the bug**  
The bullet- and repeating crossbows do not accept a pistol stock despite the mod explicitly noting it can be used on crossbows. The bullet crossbow does however accept a "cheek pad" mod despite it only being applicable to rifles, while the repeating crossbow does not. There is no explicit mention of any special interaction in the JSON definitions. From this I conclude the bullet crossbow must erroneously be considered a rifle behind the scenes, presumably due to its usage skill. Mechanically however it very much still is a crossbow and the crafting recipe is learned from archery books.

**To Reproduce**  
1. Acquire a bullet crossbow
2. Acquire a gunmod which works on one out of crossbows and rifles, but not both
3. Attempt to attach the gunmod to the bullet crossbow
4. Note rifle mods are accepted while crossbow-specific mods are rejected.

**Expected behavior**  
Mods noted as being usable on "crossbows" should attach to any weapon named as such or using the same mechanical principle, regardless of ammo type. Firearm-specific mods like waterproofing should not apply to purely mechanical weapons like crossbows.

**Versions and configuration(please complete the following information):**
 - Game Version 0.C-8443

**Additional context**  
Other non-gunpowder projectile weapons probably need a closer inspection as well. For example firearm waterproofing can be applied to the pneumatic weapons and they do not have an innate "waterproof" tag, yet moisture should not impede their operation all that much compared to soaked gunpowder. Bowstrings historically **were** severely hampered by moisture but the waterproofing gunmod description states it to contain "A set of seals and gaskets" which would be completely useless on a crossbow.

And while technically a separate issue it might be worth mentioning the bullet crossbow also lacks the "dampening" gunmod slot present on all other crossbows.

**Comment by darktoes** [comment]
I'll take a look at this once I get into my archery redux, but there's a solid chance that parts of this won't be fixable without changes to hardcode. Gun types appear to be skill based, so since there's no crossbow skill, almost all count as rifles. That said, I can just look into what slots can be removed to prevent weird behaviour.

Thanks for bringing this up.

**Comment by SirPendrak** [comment]
In some cases current system makes sense. You cannot install rifle scope on crossbow pistol, but you can use pistol scope on it. Description of both rifle scope and pistol scope mention crossbows. It seems that if a mod can be used on any type of crossbow, it will mention it in the description. 
Possiblle solutions: 
1. Remove crossbows gun group entierly, and call all crossbows that are used like a rifle - rifles. 
Repeating crossbow - SMG
Pistol crossbow - pistol group. 
But then there is a problem of bow dampenning kit, wchich can be used on crossbows, but not on rifles/SMG's/pistols. Maybe then description od bow dampening kit should be changed from "bows and crossbows" to "dampening slot", if that is even possible. 

2. Create new groups called "rifle crossbows", "SMG crossbows" and "pistol crossbows". 
In this case for example, pistol scope will be viable on "pistols and pistol crossbows", and bow dampening kit will be fitting to "bows, rifle crossbows, SMG crossbows and pistol crossbows". 

3. Leave thing as they are and believe in players common sense.

**Comment by KITbutler** [comment]
How are crossbows even defined in the code? I would have guessed there'd be a (poorly-named) flag or it'd be tied to the crossbows.json file but the repeating crossbow satisfies both of those.

**Comment by darktoes** [comment]
Crossbows aren't anything special code-wise. They're just a rifle/SMG/pistol that fires bolt type ammunition and has a special tag that makes strength affect the reload time. The crossbow weapon type should probably be removed from mention entirely since it doesn't actually exist or do anything. I think it's just a remnant from when crossbows used the archery skill.

I can shift some descriptions around and maybe change some mod slots to make it more obvious, but there's always going to be a degree of common sense required since you can attach things like a brass collector to a crossbow despite it doing nothing.

**Comment by KITbutler** [comment]
> Crossbows aren't anything special code-wise. They're just a rifle/SMG/pistol that fires bolt type ammunition and has a special tag that makes strength affect the reload time. The crossbow weapon type should probably be removed from mention entirely since it doesn't seem to actually exist or do anything. I think it's just a remnant from when crossbows used the archery skill.
> 
> I can shift some descriptions around and maybe change some mod slots to make it more obvious, but there's always going to be a degree of common sense required since you can attach things like a brass collector to a crossbow despite it doing nothing.

That is not future-proof however. Mods doing nothing is fine and all, the brass catcher can be applied to caseless rounds as well, but there's also the risk of a mod working when it really shouldn't. Waterproofing would need to replace the bowstring if that even works at all, and something like a bump stock would be ineffective on the repeating crossbow because its body absorbs much of the perceived recoil. 
Similar issues could arise with other non-firearm projectile weapons so in addition to homogenising crossbows there needs to be a more general solution both for managing mod effects and for communicating this to the player, without hardcoding everything and manually writing explanations every time. (e.g. a railgun might produce a muzzle flash and sonic boom for a suppressor to reduce but no significant gas pressure within the barrel for a muzzle brake to redirect)

Plus there's the semantics of calling something a "rifle" when it doesn't even have a barrel, let alone rifling within said barrel.

**Comment by darktoes** [comment]
If someone else wants to look into expanding how gunmods work that's fine and I'd approve wholeheartedly, but as it stands that would be outside the scope of this issue. For the moment, adjusting the available modslots on crossbows should be sufficient, and I fully intend to eventually.

Unless I'm mistaken, the waterproofing mod is a mechanism mod, which means crossbows just need that slot removed if they have them in the first place (I know I gave crossbows a mechanism slot for tuned mechanisms in my original archery mod, but I don't remember if I ported that to mainline). There's an argument to be made for improving the mechanism of a crossbow, but not with gun parts.

I'm inclined to consider the waterproofing mod similar to the brass catcher. It would serve no real purpose, as most crossbows would probably work fine underwater, at least for a little while. Until we can model water damage and different materials being affected differently, or there's actually some reason to spend extended periods of time in the water and try to fight things, I don't consider it a large concern. If that happens, synthetic coverings and/or strings might be a useful addition, and I'll keep that in mind.

Crossbows might not have barrels or rifling, but they're still aimed and fired very similarly to a rifle, at least compared to a pistol. By that logic, an A7 laser rifle isn't a rifle either. In-game that definition is skill-based, and nothing else as far as I know.

One thing to keep in mind is that the engine fully supports randomly adding new mod slots. You could revamp the entire system so that certain mods only worked on certain parts of certain guns through JSON alone. Making sure you can't put a suppressor on a railgun is a matter of keeping the right slots off of railguns, and a bump stock certainly could be attached to a crossbow. However, most only hold one round, so it usually isn't going to be an issue. Preventing burst fire on repeating crossbows may be more difficult, but should be easily doable if someone ever actually adds a bump stock.

**Comment by KITbutler** [comment]
> I know I gave crossbows a mechanism slot for tuned mechanisms in my original archery mod, but I don't remember if I ported that to mainline

I can't pin it on you but crossbows have *[four](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/items/crossbows.json)* mechanism slots! Not that there are four mechanism mods (or accessories for that matter) to even fit on there in the first place.

> I'm inclined to consider the waterproofing mod similar to the brass catcher. It would serve no real purpose, as most crossbows would probably work fine underwater, at least for a little while.

After some digging it gets even sillier than that: archery (and throwing) weapons are [automatically assigned full waterproofing](https://github.com/CleverRaven/Cataclysm-DDA/blob/60240b836cdebf53a26658c7e59b043e9dfc0925/src/item_factory.cpp#L283) but as far as I can tell crossbows *aren't* ever since they were moved to rifle skill. In addition [this](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/item.cpp#L4849) piece of code seems to implement a crossbow "tag" but is also broken, again because it checks for archery skill first.

On the realism side there's the famous [Battle of Crécy](https://en.wikipedia.org/wiki/Battle_of_Cr%C3%A9cy#Longbow_versus_crossbow) but at a quick glance I can't find any properly referenced sources on the impact of water on historical bows. And yes the specific case of underwater performance is a minor issue, crossbow code being a dummied-out mess possibly not as minor.

> Crossbows might not have barrels or rifling, but they're still aimed and fired very similarly to a rifle, at least compared to a pistol. By that logic, an A7 laser rifle isn't a rifle either. In-game that definition is skill-based, and nothing else as far as I know.

I have no real-life experience shooting any of those but there *are* a few key differences: loaded historical crossbows can't be aimed (or otherwise held) downwards without the shooter deliberately holding the bolt in place, they cannot have a traditional front sight and those you hold downwards for reloading cannot use bayonets or other protrusions while short underbarrel tubes or laser pointers should not interfere. The A7 is a fantasy weapon so we can't discuss any details. My original issue still stands though: mod slots, their names and the currently available mods are not consistent when crossbows are considered.

> One thing to keep in mind is that the engine fully supports randomly adding new mod slots. You could revamp the entire system so that certain mods only worked on certain parts of certain guns through JSON alone.

That certainly sounds like an acceptable solution. I would still prefer to see the "crossbow" type fixed to deal with edge cases where individual mods out of an otherwise consistent class do not make sense. I can clean up the JSON within the specific context of a "typical" gunmod per type.

**Comment by darktoes** [comment]
Crossbows.json's history says the mechanism slots were added by the first person who added crossbows, so it wasn't actually me. Woohoo.

Those bits of code are very odd. I wonder if I might be able to repurpose them for something useful? I'll look into it at some point, but I suspect I might just remove them since I can't think of anything special that needs to be done with crossbows that doesn't cause more problems, or can be done more easily other ways. Personally I'm of the mind that attaching things as JSON tags makes things easier for content creators, so any changes will probably be based on that rather than checking ammo and skill types. Especially since crossbows are spread across 3 different skills.

The Battle of Crecy is interesting, it's come up a lot in my reading. Depending on who you talk to, the stretched crossbow strings weren't the main cause of the crossbows' failure though. That said, I'm fairly certain water has some effect on bowstrings (crossbow strings included) but I also suspect actually implementing that would make people hate my guts, so I've been tactfully avoiding discussing it.

Some crossbows actually included a small spring plate to hold the bolt in place, but who knows how common/useful that actually was. Basic crossbows could probably stand to have a few mod slots removed for realism. I'll think some more on it. Overall, there is some weirdness on crossbow mod slots, which i fully intend to fix in future.

The issue with the "crossbow" type is that it would have to tie all crossbows to a particular skill, probably rifles (or require more elaborate code shenanigans and weird names to confuse players). Which makes no sense with pistol/repeating crossbows, and then people have to wonder which skill crossbows DO use since they're not named after a skill. In all, I think leaving them attached to their appropriate usage skill is fine, and removing all mention of the crossbow gun type would be for the best, causing the least confusion.

> I can clean up the JSON within the specific context of a "typical" gunmod per type.
Not sure what you mean by this?

**Comment by KITbutler** [comment]
> Personally I'm of the mind that attaching things as JSON tags makes things easier for content creators

Yes, as long as we can query JSON tags on gunmods this sounds great. In fact even if this does not exist implementing it would provide a future-proof framework for other kinds of mods as well.

> Not sure what you mean by this?

I am not familiar enough with the code to properly fix all the weirdness let alone implement a proper distinction between abstract weapon classification (what that "crossbow" tag code is intended to do) and usage skill for operating them in combat. A quick JSON-only cleanup of mod slots and maybe adding the "WATERPROOF_GUN" flag until the hardcoded bow hack is fixed sounds like something I *could* do however.

**Comment by darktoes** [comment]
Ah. You needn't worry yourself with that unless you really want to. I'll be revamping crossbows pretty entirely in the near future so it would be trivial for me to fix it at that point. Feel free if you just want to do it for practice though.
