### ISSUE TITLE
Error on launch. : invalid magazine lw12mag

### ISSUE THREAD

**Issue by Necrosian** [CleverRaven/Cataclysm-DDA#27730]
**Describe the bug**  
Build : 8451

Error upon loading a world.

**To Reproduce**  
1. Launch Cataclysm 
2. Create/Load a character.
**Screenshots**  
![bug1](https://user-images.githubusercontent.com/26538192/51441555-89fd3880-1cdb-11e9-8194-c6b0fe1b85ba.PNG)

**Versions and configuration(please complete the following information):**
 - OS: [Windows 7 x64]
 - Game Version :Build 8451 version: 0.C-36894-gdbbeb42
 - Graphics version: Tiles
 - Mods loaded : dda, Disable NPC Needs, Filthy Clothing, Simplified Nutrition, Remix Indicators, Vehicle Addition Pack, Tanks and Other Vehicles, Folding Parts, Urban Development, More Locations, Fuji's More Buildings,Mutant NPC, More Survival Tools, Medieval and Historic Content,No Fungal monsters, Oa' aAdditional Buldings mod

**Additional context**  
E.g. A link to a savegame that allows the issue to be reproduced.

**Comment by Solusphere** [comment]
I'm getting this same issue. Brand new world, brand new character. No mods affecting weapons.

**Comment by tenmillimaster** [comment]
It's because the game sees the magazine as being incompatible, comparing '45' to the magazines type of '460'. The magazine is still capable of loading .45 and is correct for the mod. A deeper look at how multi Cal magazines should be implemented is needed, in the interim I recommend just silencing the error message on this issue, lest anything get truly broken.
