### ISSUE TITLE
Meat, more like black gunpowder: flesh burns way too quickly | A bug with temperature of comestibles?

### ISSUE THREAD

**Issue by DeltaEpsilon7787** [CleverRaven/Cataclysm-DDA#27741]
**Describe the bug**  
Try to butcher a corpse of, say, a moose. You'll get hundreds of liters of meaty goodness.
Set it on fire. I don't think 600+ liters of meat and various other flesh should burn away in less than a minute of in-game time.

**Expected behavior**  
Meat doesn't really burn so well it can be used to proper Davy Crockett right at the location of whoever designed this. 

**Versions and configuration(please complete the following information):**
  - Game Version: 8447

**Additional context**  
An interesting thing to note is that sinews and all that burn away on the next turn pretty much guaranteed, no matter the amount.

HOWEVER, a frozen chunk of meat is first defrosted if applicable, then they start disappearing one by one every turn or so and suddenly all of it is destroyed.
So if you had, say, 500 chunks, you'd see something like this: 500 -> 500 -> 500 -> 499 -> 499 -> 498 -> 497 -> 496 -> 0

**Comment by KITbutler** [comment]
Based on an older explanation I read this is because of the way fire is coded: IIRC it consumes all available fuel (not just meat) at once and burns for the same duration as if it had only a single fuel item. Every additional fuel item is supposed to increase the "intensity" of the flame though, as if you were burning everything in its own independent fire next to each other rather than a dense pile.

This actually seems appropriate even for fresh meat assuming you already have a fire capable of setting it alight in the first place but makes less sense with fire pits and stoves past a certain filling threshold.

**Comment by jeremyshannon** [comment]
It's definitely on the ridiculous end of things, though I'm not sure making it 100% realistic would be good for gameplay. It's already a huge chore to dispose of zombie corpses to prevent carrion spawns after clearing an area. I don't know that "hang around on the street for 36 hours* while the giant corpse pile burns" would help matters. (* duration pulled directly from butt)
 Some middle ground between realism and concessions to gameplay is probably warranted, IMO. Maybe once fires will burn outside the reality bubble a realistic duration would be good, but right now I don't want to have to stand there twiddling my thumbs.

**Comment by Barhandar** [comment]
What about making burning flesh (optionally, in a deep pit) be unable to spawn carrion?

**Comment by Fris0uman** [comment]
>dispose of zombie corpses

This seems like a separate issue that could be solved by adding large scale ways to deal with corpses : mass graves, incinerator, corpse grinders etc ...
