### ISSUE TITLE
Make grenades more realistic

### ISSUE THREAD

**Issue by hyper2snyper** [CleverRaven/Cataclysm-DDA#27820]
So, the hand grenade has a safety pin on the side of it, this means that as long as you hold the safety pin the grenade will not go off. So that the grenade will not go off while being held. In Cata this is not the case. i suggest that when you are wielding the grenade, it will not detonate, only by throwing it will the timer be activated. While you are wielding the grenade you should be able to (a)ctivate it, thus pulling the pin. and then be able to activate it again putting the pin back in.

**Comment by DeltaEpsilon7787** [comment]
That implies that you actually wield a grenade, which is rarely a thing unless you're about to throw it.

Otherwise you'll be able to have tons of preprimed grenades in your backpack and while this is hilarious, this ain't X-Com where this makes sense.

**Comment by dissociativity** [comment]
my only issue is that keypresses can get confusing, I can say have an item that I usually 'a'ctivate at 'k', I drop it at some point and pick up a grenade, pull the pin and kill myself totally by accident, I think there should be a grenade safe mode, same for other activated explosives. Just an option for an (are you sure? Y/N)

**Comment by Barhandar** [comment]
Aren't you already forced to wield the thing you're 't'hrowing, as part of the stupid-throwing-nerfs thing people alleged to?

Also, you 'A'ctivate wielded things, so this is perfectly possible. Just make grenades auto-activate if picked and wielded for throwing. Then player issues turn from "forgot to pull the pin" to "decided to not throw, but forgot to put the pin back in".

**Comment by kevingranade** [comment]
This is how I want it to work eventually, but it doesnt work with the
current implementation, because the countdown is extremely long and
sometimes the player will want to wait out part of the countdown.

IRL the timer is just a few seconds, but in the game it's very long because
the player sometimes needs to throw it and then take cover.

At a minimum, there needs to be a capability to throw a grenade and
reliably drop to the ground before it detonates to shield yourself from
fragments.  Ideally the player could also take cover in depressions and
behind large items (like corpses). This is a can of worms I don't want to
open right now.

**Comment by kevingranade** [comment]
More clearly stated in #24561
