### ISSUE TITLE
Refugee center reinforcements prevent completing the first Merchant mission

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#27887]
**Describe the bug**  
https://github.com/CleverRaven/Cataclysm-DDA/pull/27437 have made it impossible to reach the zombie room without wall-breaking equipment, as now it is sealed off from the outside. The mission should not require breaking walls as it is the least difficult available from the Merchant.

**Comment by Leviathan21** [comment]
you can grab things if they are in way

**Comment by l29ah** [comment]
I cannot grab neither closed metal doors nor reinforced windows.

**Comment by Hirmuolio** [comment]
The mission to clear the dead off from the back room in the refugee center?

The doors to the back room are blocked with two lockers and some benches. You can pull/push them around if you have enough str. Or you can smash/disassemble them.

![asd](https://i.imgur.com/OVefW7t.png)
![asd](https://i.imgur.com/mUbTMHY.png)

**Comment by l29ah** [comment]
And then you have closed metal doors that are impossible to pry or lockpick.

**Comment by Hirmuolio** [comment]
The unopenable metal doors don't lead to any place relevant to the mission.

Only the store rooms in the middle section of the center are sealed completely.

![asd](https://i.imgur.com/I5SGD5e.png)

**Comment by l29ah** [comment]
Oh, i see. Your screenshot however contradicts your words: the second pair of doors leading to the zombie room are metal and unopenable.

**Comment by l29ah** [comment]
Meanwhile it's easier for the Str7 char to reach the metal doors since only one item of furniture must be deconstructed there versus two on the other side.

**Comment by Nymall** [comment]
It's always been intended that the player goes around the center section(This introduces you to the merchant in the lower left corner of the above screenshot). I don't think this is an issue, much less a 0.D blocker.

**Comment by kevingranade** [comment]
I also verified that this route is workable.  Pried the doors with a makeshift crowbar and str 7.

**Comment by FirebrandCoding** [comment]
While this issue has been closed for a while, as a new player who's just encountered the problem, I think it's worth reconsidering, at least in terms of approach.

Reinforcing the refugee center sounds like a great idea, and something the faction would do to their home area. From the in-game perspective, having a door to the room full of zombies blocked and reinforced makes sense. But then, one has to ask: just the one closer to the hall, and not the door that leads directly to kitchen (which, as far as people inside the game are concerned, may lead to pathogen contamination) and to the other bedsite (where so many people reside)?

And from the game design perspective: it's been cited by @Nymall as "always intended" for players to take the longer route because "[t]his introduces you to the [broker]". The broker is part of the refugee camp's ecosystem and provides the player/character with additional agenda by giving them goals ("_You guys need jerky and fruit wine? Excellent! That's something I can help you with. BRB, scavenging_"). But then, to show him to the player, you introduce railroading to a sandbox game?

It's not as if the broker is part of any sort of tutorial: he doesn't guide the player through the important aspects of survival, nor does he give you character tools they need to increase their odds in the unforgiving world outside (not ostensibly, anyway). The player doesn't have to meet them, nor is meeting the broker required for much else outside of the camp. So why cause players grief over something they might not even be interested in?

The way I see it, players who want to explore the area and gather quests will inevitably stumble upon the NPC, who sits in their own secluded area alone, so they must be important – so the players will check them out.

Is it possible to walk around? Sure. Is it meaningfully-challenging, or important to the plot, or of any benefit to the player? I'd argue it isn't. It's a little detail that leaves some people frustrated (count me and @l29ah as two), and it doesn't promote a cause or reward the player or the character in the end, so the net result is an unpleasant interaction with what looks like oversight in layout design, no matter how you explain it on GitHub.

Reminds me of what Jackie Chan once said. [He was talking about making films](https://youtu.be/Z1PCtIaM_GQ?t=496), but I reckon it applies to every craft that results in a lasting product:

> Whatever you do, do the best you can, 'cause the film will live forever. "No, because it was raining, and I didn't have time..." I say: "Would you go to every theater to tell the audience? No! The audience in the theater [will go] '_good movie_', '_bad movie_' – that's all!"

And it's not like you guys haven't done a _splendid_ job making the game into what it is today. It's amazing. It's a marvel of a roguelike, and gives the player opportunities someone like me wouldn't even dream of. It's grounded, and it's rough, and it's rewarding if the player puts their nose to the grind.

But this little thing? It's the kind of a small problem that leaves a bad impression in an otherwise very good game. When the thing is good, but there's something small that won't go away, it sticks, 'cause the expectation is how high at this point. You gotta work that kink out.
