### ISSUE TITLE
CTD when dragging a shopping cart towards my warehouse (basketball court).

### ISSUE THREAD

**Issue by Quintovir** [CleverRaven/Cataclysm-DDA#27889]
**Describe the bug**  
CTD when dragging a shopping cart towards my warehouse (basketball court).

**To Reproduce**  
1. Grab the shopping cart.
2. Move northwest towards the basketball court.

**Expected behavior**  
No crash

**Versions and configuration(please complete the following information):**
 - OS: Manjaro Linux 64-bit
 - Game Version 0.C-37030-g44abf4a64e-dirty
 - Graphics version Tiles
 - Mods: "dda",
  "filthy_morale",
  "no_npc_food",
  "novitamins",
  "StatsThroughSkills",
  "more_classes_scenarios",
  "realguns",
  "makeshift",
  "Medieval_Stuff",
  "More_Survival_Tools",
  "mutant_npcs",
  "npc_traits",
  "more_locations",
  "national_guard_camp",
  "more_buildings",
  "Experimental-Z-Level",
  "FujiStruct",
  "oa_additional_buildings_mod",
  "boats",
  "deoxymod",
  "blazemod",
  "Tanks",
  "no_rivtech_guns",
  "modular_turrets",
  "Salvaged_Robots"

**Additional context**  
Save game: [Sea Bright.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2798471/Sea.Bright.zip)

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/2798469/crash.log)

**Comment by GoLoT** [comment]
This should be fixed by #27883 (launcher version: 8475), unable to reproduce in that version.

I'm guessing it's the same issue as #27871 only with a vehicle that has been cached and moved while out of view. Did it only happen when the cart went out of your line of sight? Moving diagonally through a doorway is a good way to test it.

Try moving from here:
![image](https://user-images.githubusercontent.com/1606943/51783632-e4175700-213c-11e9-9f53-4b32b59cf0fe.png)
To here:
![image](https://user-images.githubusercontent.com/1606943/51783637-f98c8100-213c-11e9-9ce0-824282b42a57.png)

**Comment by Quintovir** [comment]
> This should be fixed by #27883 (launcher version: 8475), unable to reproduce in that version.

Updated the game and it's not CTD anymore.

> I'm guessing it's the same issue as #27871 only with a vehicle that has been cached and moved while out of view. Did it only happen when the cart went out of your line of sight? Moving diagonally through a doorway is a good way to test it.

Actually it CTD only when I was a few tiles away from entering the basketball court and the cart would have no chance of leaving afterimages.

> Try moving from here (make sure the cart is in the same position):
> ![image](https://user-images.githubusercontent.com/1606943/51783632-e4175700-213c-11e9-9f53-4b32b59cf0fe.png)
> To here:
> ![image](https://user-images.githubusercontent.com/1606943/51783637-f98c8100-213c-11e9-9ce0-824282b42a57.png)

Did this and nothing happened.

Thanks for the fix.
