### ISSUE TITLE
Spiked Tail mutation should't be in the Insect category

### ISSUE THREAD

**Issue by Amoebka** [CleverRaven/Cataclysm-DDA#27916]
**Is your feature request related to a problem? Please describe.**  
The description of the Spiked Tail mutation (currently in the Insect mutation tree) states it's "...a long tail that ends in a vicious stinger, like that of a scorpion..." Scorpions aren't insects, they are arachnids.

**Describe the solution you'd like**  
Spiked Tail mutation should be moved from Insect to Arachnid. Insects should probably get some other offensive mutation to compensate.

**Describe alternatives you've considered**  
Alternatively, Spiked Tail should be renamed and re-described as something more insect-fitting. Also worth noting that only female insects have stingers (not the case for scorpions, who are not insects).

**Comment by KITbutler** [comment]
The mutation line is called "spider" not "arachnid" and its other mutations reflect that: web spinning, extra limbs for climbing but no pincers, venomous folding fangs, urticating hair.

Since the attack seems to be entirely physical at the moment I'm in favour of reimagining it as an ovipositor similar to those seen in [parasitic wasps](https://en.wikipedia.org/wiki/Megarhyssa_macrurus), though not functional as such. The sex disparity is easy enough to handwave and would also apply to antlers and other pronounced horns.

Or if sci-fi is fair game say it's a hybrid limb similar to what's shown in [Splice](https://upload.wikimedia.org/wikipedia/en/2/22/Splice-poster.jpg).
