### ISSUE TITLE
Furniture under vehicles

### ISSUE THREAD

**Issue by BBlankie** [CleverRaven/Cataclysm-DDA#27967]
I can't move my vehicle nor remove the metal butchering rack and leather tarp under said vehicle.

**Comment by ThinkInvis** [comment]
I might be wrong about this, but I'm pretty sure that the game doesn't support furniture being in the same tile as a vehicle at all. It's not supposed to happen in the first place -- vehicles smash into furniture while trying to move into the same tile. If furniture ended up under a vehicle somehow, well, that's what the bug is.

**Comment by kevingranade** [comment]
Fixed by #27976
