### ISSUE TITLE
'Player tried to fire a null weapon' infinite loop upon loading a saved game

### ISSUE THREAD

**Issue by Givemeurcookies** [CleverRaven/Cataclysm-DDA#27989]
**Describe the bug**  
Game throws an exception (stated below in the debug log) after loading a save, I have autosave enabled and I was unable to load.

A workaround for this was loading it up with monster whitelist enabled and cancel the firing action (aka. monsters are nearby, stop aiming?), this worked and the loop error didn't occur. The weapon is still available afterwards and I'm able to fire the weapon like normal after the tick.

**To Reproduce**  
I believe you might be able to reproduce the issue by firing a weapon, quicksave during the action and quit. Though I haven't tested this myself, I can provide the save file where the issue occurs upon loading the game. 

**Expected behavior**  
Either continue the last action/finish the tick or revert the firing action and let the player choose whatever they want when loading up the last save. 

**Versions and configuration(please complete the following information):**
 - OS:  Windows 10
 - Game Version: This issue is at least from CDDA-0.C -8393 to the current version 0.C-8487 (0.C-37192-gf53995c). Experimental build, pre-complied.
 - Graphics version Tiles, I have tested the same in console and did not experience the same problem.
 - Mods loaded: DDA, modular turrets, salvaged robots, disable npc needs, filthy clothing, simplified nutrition, alternative map key, boats, mutant npcs.

**Additional context**  
Output from the debug log:
23:24:19.363 : Starting log.
23:24:19.370 INFO : Cataclysm DDA version 0.C-36262-g4a1ab34
23:24:19.412 INFO : Language is set to: 'en'
23:24:20.489 INFO : SDL version used during compile is 2.0.5
23:24:20.499 INFO : SDL version used during linking and in runtime is 2.0.5
23:24:21.930 WARNING : opendir [./mods/] failed with "No such file or directory".
23:24:48.568 WARNING : opendir [./save/Black Gecko/mods] failed with "No such file or directory".
23:24:59.291 INFO : Loaded tileset: MSX++DEAD_PEOPLE
23:25:04.660 ERROR : (error message will follow backtrace)
	(@0x5506fc[cataclysm-tiles.exe+0x1506fc]), 
	(@0x550a5e[cataclysm-tiles.exe+0x150a5e]), 
	(@0x5512b3[cataclysm-tiles.exe+0x1512b3]), 
	(IMG_LoadWEBP_RW+0x110bf3@0xd8e563[cataclysm-tiles.exe+0x98e563]), 
	(@0x97a3bf[cataclysm-tiles.exe+0x57a3bf]), 
	(@0x600416[cataclysm-tiles.exe+0x200416]), 
	(IMG_LoadWEBP_RW+0x300d41@0xf7e6b1[cataclysm-tiles.exe+0xb7e6b1]), 
	(@0x42648e[cataclysm-tiles.exe+0x2648e]), 
	(@0x9b24cc[cataclysm-tiles.exe+0x5b24cc]), 
	(@0x5e24f2[cataclysm-tiles.exe+0x1e24f2]), 
	(@0x5f7c7b[cataclysm-tiles.exe+0x1f7c7b]), 
	(IMG_LoadWEBP_RW+0x47013c@0x10edaac[cataclysm-tiles.exe+0xcedaac]), 
	(@0x4013e2[cataclysm-tiles.exe+0x13e2]), 
	(BaseThreadInitThunk+0x24@0x74ee8484[KERNEL32.DLL+0x18484]), 
	(RtlAreBitsSet+0x88@0x77b83ab8[ntdll.dll+0x63ab8]), 
	(RtlAreBitsSet+0x58@0x77b83a88[ntdll.dll+0x63a88]), 
Backtrace emission took 0 seconds.
src/player.cpp:12162 [const targeting_data& player::get_targeting_data()] Tried to get targeting data before setting it
23:25:07.507 ERROR : src/game.cpp:9066 [bool game::plfire()] Player tried to fire a null weapon.
23:25:08.188 ERROR : src/game.cpp:9066 [bool game::plfire()] Player tried to fire a null weapon.
23:25:10.051 ERROR : src/game.cpp:9066 [bool game::plfire()] Player tried to fire a null weapon.
23:25:10.441 ERROR : src/game.cpp:9066 [bool game::plfire()] Player tried to fire a null weapon.
23:25:10.689 ERROR : src/game.cpp:9066 [bool game::plfire()] Player tried to fire a null weapon.
23:25:10.988 ERROR : src/game.cpp:9066 [bool game::plfire()] Player tried to fire a null weapon.
23:25:11.174 ERROR : src/game.cpp:9066 [bool game::plfire()] Player tried to fire a null weapon.
23:25:11.426 ERROR : src/game.cpp:9066 [bool game::plfire()] Player tried to fire a null weapon.
23:25:11.629 ERROR : src/game.cpp:9066 [bool game::plfire()] Player tried to fire a null weapon.
23:25:11.914 ERROR : src/game.cpp:9066 [bool game::plfire()] Player tried to fire a null weapon.
23:25:12.077 ERROR : src/game.cpp:9066 [bool game::plfire()] Player tried to fire a null weapon.
23:25:12.253 ERROR : src/game.cpp:9066 [bool game::plfire()] Player tried to fire a null weapon.
23:25:12.856 ERROR : src/game.cpp:9066 [bool game::plfire()] Player tried to fire a null weapon.
23:25:30.305 : Log shutdown.

**Comment by ZhilkinSerg** [comment]
Yes, savegame would help a lot.

**Comment by Givemeurcookies** [comment]
Here's the save file, world is: Black Gecko, char: Jake Alexander
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2818917/save.zip)

**Comment by ThinkInvis** [comment]
Can reproduce with a new save generated by "Play Now!" (generates a world with default mods). Win10, Tiles, 0.C-37192-gf53995c (exp. build 8487).
 1. Set autosave options to: autosave enabled, every 10 turns, every 0 minutes (no real-time cooldown).
 2. Spawn or otherwise have a loaded firearm wielded, something capable of performing the Fire action. Tested with a spawned-in USP 9mm and compatible ammo.
 3. Find a valid target to shoot at, such as a zombear -- could not reproduce by firing at the ground.
 4. Use the "wait 1 turn" action until an autosave occurs, then wait 9 more turns.
 5. Fire at the target. If the autosave notification doesn't appear, keep firing or repeat from step 3 depending on context. The autosave notification must appear immediately after the fire key is pressed ("aim and fire" keys work, "aim and wait" key was not tested).
 6. Immediately close the game without saving, e.g. by using the system close button on the C:DDA window.
 7. Restart the game and open the save file used to perform this.
 8. Infinite loop as described.

The infinite loop could possibly be patched by adding a `u.cancel_activity();` at line 9135 in game.cpp (directly after `debugmsg( "Player tried to fire a null weapon." );`). There's a check just under this to `cancel_activity` if the player lost their weapon, but there's an early `return` caused by the null weapon case so the former never happens. I'm not sure what's actually causing the loop in the first place, though, and that's probably what needs to be fixed.

**Comment by Asmageddon** [comment]
Amazing job reproducing, @ThinkInvis, I can't believe @Givemeurcookies actually somehow hit something so bloody unlikely with typical autosave intervals.

**Comment by KorGgenT** [comment]
so adding u.cancel_activity() gets you out of the infinite loop

however, i have a strong hunch that the thing that's causing this is that the targeting data is not getting saved at all, making you lose your target, even though the game saves that you're aiming

**Comment by Asmageddon** [comment]
@KorGgenT Sounds possibly related to my debug test game crashing if I fire at the nearby debug monster - if I move the cursor, everything works, but if I just press `f` twice, it crashes.

[Rocklake.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2833061/Rocklake.zip)

It happens on the second character on the save.

**Comment by kevingranade** [comment]
Severity reduced enough to remove from 0.D blockers, but needs a more complte fix as it still spits out error messages.

**Comment by olanti-p** [comment]
Found an easier way to reproduce:
1. Set autosave to: enabled, every 10 turns, every 0 minutes
2. Wield a loaded gun
3. Press 'f' and aim at something/someone/empty tile
4. Skip time by pressing '.' until autosave occurs
5. Crash the game / exit via Alt+F4
6. Load the save
