### ISSUE TITLE
Ruminant mutation does not function (can't eat underbrush) 

### ISSUE THREAD

**Issue by carteale** [CleverRaven/Cataclysm-DDA#28034]
**Describe the bug**  
The description of mutations says "you can eat underbrush, stand over you target and press E to eat" 
but there is no option to eat the underbrush 

**To Reproduce**  
1) give your dude the Ruminant mutation in debug 
2) stand over or adjacent to an underbrush tile and press E to consume 
3) see that nothing happens 

**Expected behavior**  
I tested on top and adjacent to underbrush tiles, I tested empty and 'full' underbrush tiles and I tested it in good lighting so I could "see" the underbrush. not sure why it isn't working. 

**Screenshots**

**Comment by ThinkInvis** [comment]
Actually, it doesn't work _entirely_ properly when activated. In code, all the checks match up if you're standing over (full) underbrush... but there's some unintuitive behavior if you're too full to eat. You get the message "You're too full to eat the underbrush.", but it doesn't stop the Eat action there. It instead goes on to check whether you have anything else to eat. Seems like the bug is that it doesn't behave consistently with normal eating; i.e., you can eat normal food items while full and get the "You can't finish it all!" message, but you can't do this with the Ruminant/Grazer traits.

**Comment by nexusmrsep** [comment]
What would you see as a desired effect then? Displaying other items seems quite fine to me as long as you get the message about not eating the underbrush/grass as a result of being full. This is I believe to allow eating something else like medicine if you so wish to. Would you like it to bail out at this stage, and do not display the menu at all?

**Comment by ThinkInvis** [comment]
At the very least it should be changed to more closely match behavior for eating other things -- if you're full and attempt to use the Ruminant/Grazer trait on something, it should display the "eat anyways?" prompt displayed for normal food items in the same case. Eating underbrush could also be displayed as an option in the consume menu, like how bionic fuel sources (batteries, internal furnace) are already, but that could negatively affect player workflow (requires an extra keypress).

**Comment by kevingranade** [comment]
Fixed by #28040
