### ISSUE TITLE
Unable to place items under a vehicle cargo space using AIM anymore

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#28091]
**To Reproduce**  
1. `/` in your car's (non-full) trunk
2. `v` to select sidewalk
3. 'tab' and 'enter' to move stuff

**Expected behavior**  
Stuff goes down to the sidewalk instead of a trunk

**Versions and configuration(please complete the following information):**
 - Game Version 0.C-37136-g6567661e93-dirty

poke @ifreund

**Comment by ifreund** [comment]
Alright, what's happening here is that the Advanced inventory now uses `ACT_DROP` when moving items out of the inventory instead of its own logic. The logic for where to put the item is checked in the same was as using `d` or `D` to drop items. 

Notice that this bug is only reproducible when moving an item from the inventory or worn items.  

I guess I'll have to add another value to the activity to let it know that it needs to drop to the ground vs vehicle cargo.  Should get to it soonish.

**Comment by ZhilkinSerg** [comment]
Should be fixed with #28130.
