### ISSUE TITLE
Night Vision consumes far too much power

### ISSUE THREAD

**Issue by Photoloss** [CleverRaven/Cataclysm-DDA#28131]
**Describe the bug**  
The CBM consumes 1 battery every 10 turns, the "light amp" goggles 1 every 7. At [1kJ/battery](https://github.com/CleverRaven/Cataclysm-DDA/pull/27882#issuecomment-457779063) that equates to 16.7W and 23.8W respectively.

**To Reproduce**  
Math and research. See [CBM](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/bionics.json#L637) and [light amp goggles](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/items/tool_armor.json#L1034).

**Expected behavior**  
[This](https://improb.com/best-night-vision-goggles/) article advertises battery lifetimes of 40-60h on a single CR123A lithium battery, which according to [this](https://www.batteryspace.com/CR123A-Batteries.aspx) retailer provides about 4Wh of energy. The top entry on [this](http://www.alphaopticsinc.com/nv_goggles.html) page claims a lifetime of 70h in "passive" mode on two [AAA](https://en.wikipedia.org/wiki/AAA_battery) batteries which might provide as little as 2.6Wh for a lower bound of 0.04W

In-game these devices allow us to see in what probably *should* be complete darkness however so passive light amp might not be enough. The "[Ghost Hunter](http://www.alphaopticsinc.com/nv_goggles.html)" also provides "a powerful infrared illuminator providing a bright, clear image in low-ambient light conditions or total darkness" which shortens the battery life to 20h. Using the high-end AAA's for 3.6Wh yields an upper bound of 0.18W

Now since illumination is not limited to realistic cones (except for vehicles) you might assume this to be a "feature" and increase the power consumption accordingly. The Ghost Hunter claims a 30° FoV so scaling that to full 360° coverage yields 2.2W, still **ten times less** than the in-game version.

**Additional context**  

Alternative high-end milspec (prototype?): [ENVG-III](https://taskandpurpose.com/armys-new-thermal-sights-nvgs) with 7h on four AA's (4Wh each) has 2.3W real draw, or 21W upscaled from its 40° FoV. This one has an outline-drawing image processor however and claims to also work well in inclement weather plus it has a daytime setting none of which we have in-game.

Please point out any calculation errors and feel free to cite more reliable sources if you know any.

**Comment by darktoes** [comment]
Sounds reasonable to me, and that would make equipment night vision actually somewhat useful, especially if you tone down that awful green overlay.

Sass aside, can I recommend that you use your real-world values for the worn nightvision goggles, then make the implanted bionic nightvision somewhat more efficient, on the grounds that it feeds directly into your brain rather than needing various interfaces and such.

I'm not sure if it was fixed or not, but I remember looking at the power usage of flashlights and finding those a bit high as well, so maybe you could take a look at those as well.

**Comment by Photoloss** [comment]
The CBM still needs to "translate" from photomultiplier signals to either visible light or optical nerve signals and the "full darkness" IR flashlight won't be cheaper either. Unless you can dig up some specs on how much power the HUD actually draws by itself there shouldn't be more than a token discount (and let's face it, bionics in their current state don't need stat benefits anyway as they already relieve you of encumbrance, gear slots, durability/repair and inventory fiddling)

I am *very* hesitant to look at flashlights because most I've seen IRL are *vastly* underpowered compared to pretty much any game. If someone can code realistic light cones and character turning or we get official confirmation that in-game flashlights are 360° floodlights I might reconsider.

Feel free to point out other appliances though, I'm struggling to find proper infrared/thermal imaging goggles and most other CBMs are pure sci-fi at this point.

**Comment by darktoes** [comment]
Unless I'm mistaken, NV goggles have to project "what they see" onto a screen of some sort, no? In that case, having it implanted saves some energy on the screen alone. On top of that, I'd assume experimental NV systems would just be flatly more efficient than civilian models, and there's the possibility of the implants sapping some energy from the nervous system, to the point you could probably find justification to remove the power cost entirely, similar to the nightvision mutations. For that matter, you could argue that implanted NV would just modify the eyes to work more like some animals that can see better in the dark, perhaps with a small infrared light to illuminate true darkness (I.E "passive" mode increases night vision 20-50%, "active" mode doubles or triples it.)
That said, you are correct on bionics already being flatly superior. However, the NV implant is currently fairly worthless due to how common the nightvision mutation is, and how cheap normal lighting is, in my opinion at least.

I'd imagine flashlights ingame work largely on the principle that the character _could_ shine it on anything in the illuminated radius, so it's assumed they just work on the same principle as the 360° vision, or that they can look around enough in a 6 second turn to see everything around them. Either way, I think it would be quite reasonable to just use standard flashlight values.

Finding real-world equivalents for a lot of items ingame is exceptionally difficult. It's often more than enough to just make an educated guess in my experience.

**Comment by Photoloss** [comment]
> Unless I'm mistaken, NV goggles have to project "what they see" onto a screen of some sort, no? In that case, having it implanted saves some energy on the screen alone.

First of all the bionic might be "projecting" right into your eyeball rather than on a screen at roughly the same power. Like I said if you can find specs for displays (and whatever neural stimulation technology we actually have IRL...) please post it.

> On top of that, I'd assume experimental NV systems would just be flatly more efficient than civilian models

Definitely not, read the article. The one I posted is *not* a simple "green screen goggles" gadget however, it seems to have multiple display channels or colour options, the already-mentioned target outline drawing (which requires an image recognition algorithm i.e. a small computer) and at the cost of halving its battery life it can be linked to a high-tech weapon scope to let you "see" through that instead. Generally speaking "experimental" or "prototype" technology will have little regard for power consumption unless that is the entire point of the innovation, although this one seems to be close to market-ready.

> there's the possibility of the implants sapping some energy from the nervous system, to the point you could probably find justification to remove the power cost entirely

Our *entire brain* uses [about 20W](https://hypertextbook.com/facts/2001/JacquelineLing.shtml) and I know no energy-harvesting technology which could draw from neurons without completely shutting down their signal transmission. An electric eel mutant self-powering as a kind of improvised Metabolic Interchange is a different topic.

> Finding real-world equivalents for a lot of items ingame is exceptionally difficult. I don't think anyone would blame you for just making an educated guess.

I trust the previous coders to have done that already unless published facts say otherwise.

**Comment by darktoes** [comment]
If you're not able to find the specs then I'm not going to waste effort looking. My point was more along the lines that cutting out a "middleman" is probably going to improve energy efficiency somewhat. It seems odd to me that an implanted night vision system would project into the eye rather than just go straight to the nerve.

The implanted NV doesn't have any of those features, it only provides basic night vision. It makes sense to me that a high-end military-grade piece of hardware would have closer tolerances and better components than civilian grade equipment, especially something the PC can put together by hand. That said, a number of other similar bionics (targeting system, telescopic eyes, the +2 perception one) have no power requirements, so there is a precedent. You might also consider that the bionic cloaking system uses significantly less energy than the worn cloaking system.

Perhaps that was a bit of a long shot, but there are a number of bionics that use no power to achieve things more substantial than providing night vision. It seems there must be some degree of power provided by the body to power these things.

A bit of quick math suggests the flashlight is ~7W and the heavy duty flashlight is ~21W. Assuming the use of LEDs, that would make for some exceptionally bright, although probably not ridiculous, flashlights. According to the wikipedia page on flashlights.
