### ISSUE TITLE
Wait a turn while in observation mode.

### ISSUE THREAD

**Issue by Bulletfang** [CleverRaven/Cataclysm-DDA#28178]
**Is your feature request related to a problem? Please describe.**  
Not a problem exactly. Just a quality of life improvement.
When observing things from afar; When you press x and look at things outside your normal range of vision, you can only observe them for the turn you've pressed x. If you want to see what it does, you have to leave observation mode, wait for as long as you feel like is neccesary, then hit x and go back into observation mode again, search for the thing that interests you and so on. Alternatively, pressing V and filing through the list of monsters and animals yields the very exact same problem of not being able to observe anything over a course of time comfortably with the press of one button.

**Describe the solution you'd like**  
When hitting x and entering freelook mode, the player navigates his center of attention with the numpad, but the key 5, the same key used to wait a turn or so outside of looking around, does nothing. Adding the same function of waiting a turn in observation mode with that key would not only add the ability to look at things over a course of time easily, but would also feel natural to anyone familiar with the controls of CDDA.

**Describe alternatives you've considered**  
None that come to mind.

**Additional context**  
Watching things in the distance opens up the possibility of enemies creeping up on you, which is a realistic thing to happen when your attention is far away.

**Comment by AMurkin** [comment]
Alternative is shifting center of the view with H, J, K, and L.

**Comment by Bulletfang** [comment]
True, I didn't even know of that functionality. The controls in CDDA are already rocket science, and just having numpad 5 work when looking around seems a lot more ergonomical and a whole lot easier to learn for new players.

**Comment by CoroNaut** [comment]
I would rather just have functionality that the op suggests rather than shift my camera with 30 key presses, and then shift it back.

**Comment by ennob** [comment]
@CoroNaut, it comes out to the same number of key-presses. Regardless or how you move your view it is one press per square, then either esc or colon to get back, depending on whether you look or move your view.

You can of course still prefer OP's suggestion but the key-press argument doesn't really work.

I prefer the way it is working now for the following reason: when you press x to look around, nothing you do can get you in trouble. It is safe even in a tight situation. I prefer that, rather than being able to accidentally pass time while looking around, which might get you killed in a tight spot. Especially given that the functionality OP wants is already in the game.
