### ISSUE TITLE
Brainstorming: lab and hospital furnishings

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#28187]
**Is your feature request related to a problem? Please describe.**  
I'm in the middle of making a real-life lab building, and I'll probably expand from here to hospital revamps as well soon. There just isn't enough furniture and decor for these kinds of locations, and I plan to add it.

However, I'd like to make it as general purpose as I can, so that it can be used in more than just these locations. I'm posting my thoughts here so that folks can weigh in particularly on how the same stuff might be used in other sites.

**Describe the solution you'd like**  
I figure the following furniture should be added for sure. I'll probably do the tile art for most of these myself because I'm excited about it.
- [x] workbench: a cabinet derivative with a durable low reactivity countertop and fittings for power, gas, and water.
- [x] fume hood: a laboratory fume hood with a fan venting to a central air filter
- [x] shaker/incubator
- [x] autoclave
- [x] sample freezer: a large metal freezer that goes to -80C. 
- [x] eyewash and emergency shower station: just for flavour but fun to add.
- [x] utility shelf: I'm debating if we need this or if the current "rack" furniture serves this job. Personally I think it's weird we don't have one... Just an open piece of furniture made of plastic, with the state capacity of a locker
- [x] iv pole
- [ ] utility cart: a plain metal shelf on casters, ubiquitous in hospitals, labs, clinics, and really everywhere.
- [x] lab analytical equipment: I have eventual plans for these so they're unlikely to change except to add to the list, but for fellow nerds who want to make sure their favourite tools are added, I plan to add GC, HPLC, MS, and NMR, as well as an electron microscope.
- [x] medical imaging gear: stationary x-ray, CT scanner, and MRI for sure.
- [x] dialysis machines
- [x] ventilators for ICUs. Technically this is a vehicle, but draggable furniture might work.
- [x]  curtains to hang from the ceiling would be great in both labs and hospitals.
- [ ] paper shredder
surgical suite decor: 
- [x] anaesthetic machine 
- [ ] lighting arms using multitile decor to make arms hang from the ceiling.
vehicles/similar: 
- a toolbox option to add to casters could be used for mechanics toolboxes, as well as crash carts, anaesthesia carts, medication dispensing cabinets, chemical carts, and more... Ideally it should be lockable. I'd also like a portable ultrasound machine and maybe a portable x-ray.

Anyone else want to share the specific interesting equipment they've seen or worked with that they think should be included?

(For completeness, I'll also be adding a few items that don't need new parts: exam/hospital beds on wheels, rolling stools, and a few things like that.)

**Describe alternatives you've considered**  
I've been working on trying to use existing furniture, and it's not terrible but it's not right either. It gets increasingly obvious that the furniture just isn't up to it yet

While writing this I was thinking of some other things we really should have, like boiler rooms and furnaces and hot water tanks. I might throw some of that in too. On that note, here is some more furniture I don't necessarily need for labs and hospitals but we probably should add and start integrating into old maps.
- [x] central air filter
- [x] furnace
- [x] hot water tank
- [ ] boiler
- [ ] radiant heater
- [x] server stack
- [x] air conditioner/refrigeration unit (both for homes and for walk-in fridges and freezers)
- [x] satellite dish
- [ ] grandfather clock
- [x] glass front cabinet
- [x] stationary air compressor (gas stations eg) plus a vehicle or item version for construction sites, lots of good stuff to dismantle from that
- [x] water purifier
- [x] street light
- [x] traffic light
- [ ] telephone pole (I can't believe we don't have those last three already)
- [x] standing lamp
- [x] dishwasher
- [ ] awning: a terrain type and vehicle component made of cloth, offering shade and shelter. Possibly activate to retract?

**Additional context**  
I want to avoid anything clearly science fiction, we have plenty of that already. Ideally I'd like to make everything I'm adding have a use eventually beyond just decoration, even if that is just as a source for valuable salvage.

**Comment by Photoloss** [comment]
- workbench: best to start with a generic version which can serve as a (posh) kitchen counter or machine shop bench as well. No reason to make it lab-specific until spilt chemicals or sterility actually matter.
- fume hood: if we have any kind of multi-component-tile functionality this could be assembled from the above counter, a glass safety screen and a regular hood as found in kitchens above stoves. The safety screen can be reused in glove boxes, CNC machining etc.
- freezers don't need a lab-specific version unless there are some fancy plans for e.g. dry ice. Regular freezers distinguished from refrigerators as well as full-size vehicle versions would be appreciated though.
- eyewash/emergency shower/decontamination can be built from regular showers, we just need a room layout to fit them in
- a shelf sub-tile would be nice in general, dito for roof racks on vehicles. Not sure the code supports multi-level storage arrangements though
- a multitude of ceiling light fixtures are another obvious sub-tile. Not sure we need a full operating theater though, I'd expect that to be integrated into the autodoc to a large extent.
- large industrial ventilation fans on vehicles will be nice for smoke/fume control once wind effects are fully implemented
- I presume with "curtains" you mean the long curved rails often depicted around hospital beds, otherwise we already have a "canvas door" found in changing rooms as well as tents.
- shaker, incubator and autoclave seem too specific to really bother until we need functional versions

I do wonder which of these could potentially serve any gameplay function though. Especially since even the existing furniture like ovens and fridges don't work *yet* but should in principle be easy for a mid-game survivor to fix with a bit of luck (easiest case literally just drag over a backup diesel generator from a garage). Once anything of the sort is added it will be very confusing and rather annoying to sift through all these fancy devices which *should* be powerable the same way but simply aren't implemented as such. 

One thing I really miss on that list in terms of gameplay, even if the furniture is nonfunctional and we have to salvage and craft it for vehicle conversion, is specialty lamps. Heat/IR, UV and "sun" lamps for plant growing in pot basements.

And while you want to avoid sci-fi stuff lab decor still is the context in which I would expect the highest frequency of atomic lights, coffeemakers and similar gadgets especially since they clearly had some pretty lucrative deals with RivTech.

**Comment by I-am-Erk** [comment]
All of these should be added in their expected final form, not by using temporary stuff with the knowledge we'd want to change them later... It's much harder to update map files later than just to make a furniture file using looks_like and copy-from to limit additional work, and update that definition file later on. Going through maps is a hugely time consuming and mind-numbing procedure.

I'd like to be able to make multi-layer furniture, but it's well beyond my skills. What I can do is make a range hood that copies a lot of details from the fume hood, mainly for the purposes of salvaging a motor and some sheet metal.

Specialty lamps are a good addition... Grow lamps certainly could show up in hydroponics labs, for example. Industrial fans are another thing I've been considering, either separate or as part of the air unit.

**Comment by SunshineDistillery** [comment]
The humble filing cabinet. 

I recommend making as many things furniture as you can instead of terrains. It avoids trouble with assigning bash terrains or setting indoor flags.  

Lamps would be great, but if you add light-producing furniture/terrain it should be as a json flag.  Right now only utility lights produce light and they are hardcoded to do so. 

I don't know about multitile furniture, but I believe you can can set deconstruct and bash furniture.  So you bash a glass cabinet and get a cabinet and shards, etc.  You  can also open/close furniture like doors, and have two versions of one piece, if that's helpful.

**Comment by chaisawlajatang** [comment]
It may not a 'furniture', but I guess something like this would nicely fit into a lab (maybe with something dangerous - mutagen, plutonium, slime container, marloss berry or even an artifact - behind the glass). 
It can be a separate furniture (multitile?) or a construction with a line of reinforced glass with a closed chamber behind it.

![25438-7874513](https://user-images.githubusercontent.com/40278862/52837993-1e539300-3102-11e9-99b7-07ebcf37798c.jpg)

**Comment by I-am-Erk** [comment]
Biohoods are super cool and I'm probably adding them. I'm not sure they're sufficiently different from fume hoods to merit their own item, or if they can just be copy-from so that they are functionally identical but with a different name. I've been assuming the latter... They even look similar enough to use the same icon.

**Comment by Photoloss** [comment]
Not just "bio". While probably quite obscure IRL such glove boxes are also used to handle [tritium](https://www.euro-fusion.org/fileadmin/_processed_/5/4/csm_Pic2_TLK_glovebox_Antunes_563a72c87b.jpg) and other dangerous gases in physics. Thus the fusion research and the nanofab lab could have quite a few.

**Comment by Wolfechu** [comment]
Something basic from working in hospitals years ago: Trash cans. Lots of trash cans, bins, wheelie bins. Color coded bins for every purpose. Regular trash, confidential data hardcopy trash (see also shredders above). Clinical waste trashcans. Sharps bins. Hazardous material bins. Recycling bins. 'Parts' bins for various bits of anatomy going to the incinerator. Laundry hampers. The list goes on.

**Comment by Maleclypse** [comment]
f_shredder exists already.

**Comment by actual-nh** [comment]
> utility cart: a plain metal shelf on casters, ubiquitous in hospitals, labs, clinics, and really everywhere.

Most definitely, including school buildings for science classes.
