### ISSUE TITLE
Bullet damage modifiers in the item display are half-invisible

### ISSUE THREAD

**Issue by ghost** [CleverRaven/Cataclysm-DDA#28252]
**Describe the bug**  
A L39B-45 (damage modifier 0 at full health) spawned with damage |. and loaded with .45 ACP FMJ (damage 27) will show Damage: 0+27=15.

**To Reproduce**  
Look at a loaded damaged L39B-45's item display and notice an invisible damage penalty.

**Expected behavior**  
Damage: 0+27=27 or Damage: 27-12=15

**Screenshots**  
![damage_penalty](https://user-images.githubusercontent.com/47664500/52974102-3e3ebd00-3375-11e9-8d33-4e41550c7bf9.png)

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version 0.C-37523-g4c3c368

**Comment by iordanivanov** [comment]
I took a look at this, and it seems that it's caused when the gun doesn't have a `ranged_damage` key in its JSON entry. (I think the default value for `ranged_damage` is 0, since when I tried setting it explicitly I got a debug message about the key not changing anything, but I could be wrong)

From what I was able to understand, when the total gun damage is being calculated, the item's damage (multiplied by two) is subtracted from each damage unit that the gun's total damage possesses.

What I assume is happening is that when there is no `ranged_damage` key, the item damage penalty is being subtracted from the ammo's damage unit, but when the UI queries the gun's item info, it's getting the ammo's original damage, making it look like there is no damage penalty.

This doesn't seem to apply to guns that have the `ranged_damage` key, where the item damage penalty is **not** subtracted from the ammo's damage unit. I haven't found out why this happens, though.

I've only recently started looking at CDDA's code, so I may be mistaken.

**Comment by wapcaplet** [comment]
Still reproducible in 0.E-9702-gdc4167363d. When a gun is damaged, its total "Ranged damage" indicator does not show the correct total.

Mint-condition `M45A1` has `0+27 = 27` damage:
![image](https://user-images.githubusercontent.com/238395/108147254-c7d01500-708b-11eb-83aa-1b2a3fe97f74.png)

Damaged `|. M45A1` shows `0+27 = 23`:

![image](https://user-images.githubusercontent.com/238395/108147334-e2a28980-708b-11eb-86b6-4c2dba7fa3a8.png)

The same occurs with an `M4A1`, undamaged `-2+42 = 40`:
![image](https://user-images.githubusercontent.com/238395/108147404-049c0c00-708c-11eb-91fa-b78444818673.png)

versus severely damaged `\. M4A1`, totaling `-2+42 = 34`:

![image](https://user-images.githubusercontent.com/238395/108147460-209fad80-708c-11eb-978c-6fbac2451e1b.png)
