### ISSUE TITLE
Transhumanism rework proposal, part 2: Mutation trees

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#28277]
**Is your feature request related to a problem? Please describe.**  
Bionics and mutations represent an overall category of transhumanism, which should start in the mid-game and progress into the late-game, allowing the player to slowly develop into a superhuman or a monster. Currently the transhumanism progression suffers from a number of problems. Key among these in my opinion:
1. It tends to be all-or-nothing, especially with bionics. There is little decision making to the installation of CBMs, aside from initially having to ration autodoc access and anaesthetic. As access to CBMs becomes less of the gateway (through things like building your own clinic), the gating system needs to ask for player *choice*, which is more meaningful and fun than lucky finds anyway.
2. Mutations offer a fun gambling subgame, but one where the risk-rewards are very poorly balanced currently. The gambling aspect of mutations needs to be preserved, but there needs to be a higher element of player control, again for the purpose of proper decision making. As well, there should be more of a realistic feel, as opposed to the current insta-mutation.
3. Mutations and bionics currently are fully complementary, allowing you to get the best of both worlds with little to no tradeoff.
4. As Kevin points out, "There is no meaningful tradeoff between acquiring mutations and CBMs vs refraining from doing so. If you can acquire them, it's a given that you should do so, because it's only plusses. Some of the mutations have drawbacks, some are significant, but it's (IMO correctly perceived) as something to manage by trying to get the right mutations, not avoiding them entirely."

**Describe the solution you'd like**  
This issue will address primarily mutations, I have addressed my suggestion for bionics in https://github.com/CleverRaven/Cataclysm-DDA/issues/28273, although I think the two problems need to be considered at once.

Mutations already currently follow loose trees of dependency: mutation x needs mutation x-1 to develop. However, these trees are still only very slightly relevant to the player, as there is limited ability to choose which tree you go down. I propose a couple major system changes that would make mutation trees far more relevant, slow down mutation speed, and offer the player a blackjack style gambling game wherein during mutation you always face the decision: Do I go further down this path, hoping for another good deal? Or do I fold and quit while I'm ahead? I hope this preserves the gambling fun of mutations, while adding player choice instead of the current game of craps.

Here is the process of mutation as I see it:

1. **Mutagen Ingestion**

When the player drinks or injects mutagen in the new system (or when exposed to other mutagen sources), they gain what is basically a drug effect called something like "phenopotency". This effect fades slowly as the body processes the mutagen. Each new mutation gained causes a sharp drop in phenopotency, with the exact amount based on the tier of the mutation (explained below).

You advance to a new tier mutation gradually over time, with the sudden step down at the next tier designed to generally end when you get the next tier mutation... but sometimes you'll run out of phenopotency too early and not make it. See section 4, maintaining/canceling the pathway.

2. **Selection of mutation pathway**

Once the player starts mutating, the game selects a Mutation Pathway. This is the series of mutations the player will get, and the full course is selected from the start.  However, whenever the player consumes a large amount of anything that increases their phenopotency, the game decides if they should stay on the same Pathway or not. The further along the pathway you are, the more likely you are to switch to a different one when you take more mutagen. So, if you have only got to the first step of your pathway and then you drink more mutagen, you have a very high chance of staying on the same path (because who wants to stick around with 'itchy scalp' as a mutation? seriously). By the time you get to the high tier mutations, which have a very high chance of being extremely dangerous, it's very unlikely you'll stay on the same path (because disintegration sucks). The chance of staying on a Pathway should be higher if that Pathway is linked to a threshold you have crossed.

Once you leave a Path, it should be possible to reawaken it, but this is probably something that should be done intentionally, not by randomly taking mutagen. A reawakened Pathway would actually still reroll the upcoming results, the game doesn't need to store what the next result on the Pathway was before.

3. **Traveling down mutation pathway**

Each stage along a Pathway is called a mutation tier. At each tier there should be a minimum of two options for what you can get for mutations. For example:

Start - You ingest some mutagen. It chooses this pathway.
Tier 1 - **itchy scalp**.
Tier 2 - "head bumps" or "thickened hairs" (and probably many other options). Game chooses **Head Bumps**.
Tier 3 - Antennae or Horns - game chooses **Horns**
Tier 4 - Curled Horns, Pointed Horns, Antlers - game chooses **Pointed Horns**
Tier 5 - Making this up at this point, let's go with Demon horns - a variant on pointed horns that starts to add some serious problems due to their bulk, but are also dangerous and frightening and quite powerful.
Tier 6 - Deciduous Demon Horns - large unstable horns that shed every day, causing pain and increased hunger because of the energy to maintain them. When at full growth they are bulky and encumbering.  This is an unstable mutation - looks like you went too far.

The timeframe would be like this:
Tier 1 - appears almost immediately upon ingesting the mutagen, within a few turns to a few minutes.
Tier 2 - appears within minutes to hours
Tier 3 - appears within hours to a day
Tier 4 - appears within days
Tier 5 - appears within a week or so
Tier 6 - another week or so.

Speed could be increased by having a very large reserve of phenopotency, ie. by injecting tons of mutagen all at once. This is good for impatient people but not without risks at all!

4. **Maintaining/canceling the pathway**

The pathway can be maintained in a few ways. 
- First, just by drinking/injecting a lot of mutagen at the start. This makes sure you'll go far down whatever path you get, but gives you little to no control over it, because you don't yet have any mutations. Also it speeds up the pathway, which gives you less time to process and decide if you like the mutations you're getting.
- Second, by drinking/injecting mutagen early on when your pathway starts to manifest. The chance of losing the pathway is low at first, so you get time to decide if you want to keep accepting cards or not.
- Third, by drinking/injecting mutagen later on down the pathway. The chances of staying on the same pathway get low once you hit tier 3, but can be boosted a bit if you take a mutagen that is associated with the pathway in question - so if you're growing horns, then Cattle mutagen would have a better chance of keeping you on the same path. (Note: A mutagen is considered associated if your most recent mutation is part of that mutation tree. So, when you have head bumps, insect mutagen would help get you down the path, even though the game knows that the next mutation is going to be Horns.)

I picture the chance of staying on Pathway being something like this:
Tier 1 - 100% with matched mutagen, 95% with unmatched
Tier 2 - 95%  with matched mutagen, 80% with unmatched
Tier 3 - 80% with matched mutagen, 50% with unmatched
Tier 4 - 60% with matched mutagen, 20% with unmatched
Tier 5 - 40% with matched mutagen, 5% with unmatched
So you can always choose to try for an unstable tier 6 mutation by specifically ingesting the right match of mutagen.

On the flip side, a path can be halted by taking purifier. While you are mutating, purifier drops your phenopotency to zero immediately, but leaves you on the Pathway. A second dose of purifier kicks you off the Pathway, with a small chance of clearing out your most recent mutation. If you take purifier serum, it is almost guaranteed to kill your last mutation and a high chance of getting the one before that (hitting the mutation before that is an important element of the cost-benefit. Obviously if you're taking serum, that means you've gone "over" on your blackjack hand... but the penalty to going "over" is that now you have a significant chance of losing whatever mutation you had previously, which presumably was something you liked. Shoulda called it earlier!)

When you're not on a Pathway, purifier functions more like purifier already does. However, it doesn't ever target mutations that are prerequisites to other mutations you have - it always targets the last mutation in a given pathway that you have achieved. It has a saddle-curve of preferences: Purifier goes for tier 1 and 6 mutations preferentially, 2 and 5 next, and finally 3 or 4, because tier 3 and 4 represent the most generally stable forms. This is random though, it's just a weighted preference.

5. **Downsides**

This is an area that still needs some work, primarily as regards issue 4 in the introduction - there needs to be a meaningful trade off for mutations, and it shouldn't just be "I rolled the dice and got crappy stuff, dang." 

One possibility is to include minor 'side effect' mutations that are selected as part of each Pathway, at random, appearing around tier 2, and worsening with each tier progression - integrated into the mutation (not every single pathway would always get a side effect, and not every side effect has to be purely negative). So, you might get Horns, with the randomly associated downside 'weeping' ("the site of this mutation constantly seeps fluid, which is very annoying and a bit gross"), making them Weeping Horns, and later Weeping Pointed Horns, causing a small morale penalty that gets worse as you go down the tier list. Individually these should be minor, but the more mutations you accrue, the more they add up.

Many other possible balances have been suggested (@psyxypher), probably better for the proponents of them to list in comments than to have me rephrase them poorly. I think psyxypher's was better than mine but I don't know it off memory. I'll CP the interesting ones here for consideration.

**Side note**: Unstable mutations. I'd like to see many tier 6 mutations offering huge benefits at huge costs. A common theme here might be mutations that make you unstable, but that can be maintained with special "Suppressor" mutagen, a very weak form of purifier. You might, for example, get a mutation where your STR just continues to slowly increase, along with increasing pain, metabolism, and encumbrance and decreasing speed when it exceeds a +6 bonus. You can suppress it back to safe levels, but the effect will only last a few days before it rises up high again. If you run out of Suppressor, your life is at risk; eventually your speed will drop to zero and your muscles will crush you. You could purify this mutation away, of course, but it's also the highest strength bonus possible in game, so you could live with the complexity and risk in exchange for the power.

****Summary/Final goal:****
Mutation becomes a game of blackjack, with the cards you'll get known to the game in advance but not you. The amount of mutagen you ingest determines how many cards you'll get dealt and how fast they come. Purifier lets you stay the dealer and start a new hand, and gives you a chance to change your mind at the last minute. You get some control over what's coming next by using mutagen types matched to the last card you were dealt - or by avoiding those types.

The key element to this is going to be reorganizing existing mutations into their Pathway trees, and figuring out where the downsides to getting the stable tier 3-4 mutations comes in. Unstable tier 6 mutations and suppressors, if they're as popular with others as they are with me, would be a later-stage thing.

**Comment by KorGgenT** [comment]
just putting this here because it touches a lot of mutations. will read later #28049

**Comment by I-am-Erk** [comment]
Stomach contents also includes some of the code framework that I think we'd use to process mutagen via phenopotency, I think.

**Comment by KorGgenT** [comment]
i was thinking maybe using the vitamin system, or something like it?

**Comment by I-am-Erk** [comment]
I like that mainly because then we can call it 'vitamin M'.

**Comment by Photoloss** [comment]
> there needs to be a meaningful trade off for mutations, and it shouldn't just be "I rolled the dice and got crappy stuff, dang.

I don't see why you dismiss the "crappy stuff" so flippantly. Right now you can avoid the genuinely bad stuff via purifier-scumming but many of the "negative" mutation effects would already be sufficient tradeoffs if they are semi-fixed "steps" on a Pathway as opposed to an entire path of increasingly bad ones (which you'd just abort immediately). Especially if that includes the paths to threshold mutations i.e. **all** post-thresh Feline mutants pick up Carnivore and all post-thresh slimes get High Thirst and a choice of Very Fast Metabolism or Genetically Unstable.

It's not there "is" no tradeoff, just that the one which was *intended* (bad mutations) does not actually work as such in full endgame practice.

**Comment by I-am-Erk** [comment]
I didn't intend that to read as flippant dismissal of all bad mutations; rather, of the current system where you roll the dice, you get what you get, and you don't get upset (because you probably save scummed, let's be honest here). Bad mutations are a necessary part of the game, although I believe the plan psyxypher laid out was to integrate them into good mutations rather than have them as separate 'bad roll of the dice' results... basically achieving the same end you're describing.

**Comment by AirPhforce** [comment]
Note; I made an account here for this discussion. 

I really like your suggestion for mutations. Specifically the slow upgrading of various features. I've always thought there were far too many, I guess I'd say 'replacement' mutations, things that could just get swapped out for others with no benefit or loss really.

I really like your suggestion then, to enhance existing mutation lines with 'ideal' end states as well as the ability to go way too far. However I would like to recommend that those 'too far' states be, at the end of the day, the 'ultimate' version of that 'line' but that peak mutation costs a shitload. For example, using your horns example, the "Deciduous Demon Horns" would provide the strongest attack in the 'horns' line, but have downsides as you suggested. Ideally, each 'threshold' would have the opportunity to get something like this.

Insect, for example, could get a bee abdomen, which later grows a singer, and if you keep going, it gets way oversized, and while it's now stronger and has the venomous property, slows you down quite a bit. Arachnid could get a set of 6 legs that give it perfect footing and silent steps, but prevent any kind of leg or footwear at all that isn't cloth. The 'huge' line could be extended even more, giving even more strength and HP bonus's for even more loss of character function. The theme of course being that if you go super overboard you become an actual monster that can't even remotely pass for human, which I think makes sense thematically. Chimera could then get the 'ultimate' version of claws, horns, size, etc, and just be the ultimate superbeast that has to eat a cow every few hours or it starves.

Of course, this sort of thing would be absurdly strong with all the 'oversized' actual armor you could wear, so I'd add a special tag so that things past a specific point could only wear very specific non-armor gear that has it's own tag.

Though I am not super keen on the idea that mutations outright kill you though as in your last example. I'd rather they make life difficult that it results in your death, such as by making you walk at 1/4 speed max, but shouldn't ever just outright just kill you because you didn't purify it in time. I'm also not exactly sold on things like 'weeping' effects to existing muts, unless positive ones exists as well (horns could be 'big,' bonus bashing damage, 'sharp,' bonus cutting damage, etc). While it would be cool, it does seem like needless complexity. Then again, adding a list of possible mutation affixes and manually tagging each mutation to include 'viable' affixes wouldn't be too hard to implement, I don't think.

**Comment by KorGgenT** [comment]
Interesting thought for mutation "prefixes." as far as gaining the mutagen is concerned, are you planning to still stick to the mutation category trees, such as cattle, ursine, etc? if so, i have a couple ideas on how that could be implemented, but my initial thought of the vitamin system would definitely need to be revised. However, we may be able to use vitamins as an example for keeping track of the mutagen levels in the player's system, depending on how you plan to keep track of that.

do you have any comment on receiving mutations through special events in game, like artifacts or missions? modders would probably rather like the ability to add specific mutations that way.

**Comment by AirPhforce** [comment]
Making mutations work sort of like vitamins would be solid, but I think there would need to be a separate 'vitamin' for each mutation line. I do think the system should stay with cattle/ursine/plant etc. I do think it might be the simplest way to implement, as the game could just check percentages when it comes time to mutate, though I say this knowing I won't be the one coding it. :-/

The more I think about the affix system, however, the more I like the concept. Affixes could have a value assigned, positive and negative, and we could add some kind of 'bolstering' item you could create that would specifically and singularly raise those numbers. Just something so you don't roll leaky eyes and have to be stuck with them until you purify out and mutate back in. Would also provide end-game mutation characters with goals, such as max out all existing mutation affixes. 

I also like the idea of being able to make affixes and tag mutations, if this is just json adding new mutes and mute affixes would be piss easy and a good modder resource.

**Comment by Fris0uman** [comment]
So a model of how phenopotency could work

You inject yourself with mutagen You get Q amount of XE027  (blob agent, I don't remember the exact name) in you

Then on one side the blob works on building a new mutation. With
Wm : amount of work required to build mutation m
S: speed of work per blob unit
Each tick the work progesses of Q*S until it reahes Wm and you get that new mutation

On the other end your body eleminates the blob at a rates of E.
Each tick Q is reduced by E unit

Purifier reduce Q either directly or by increasing E and works at deconstructing the mutation. (Or it s all instantaneous but it's less cool)

The point of this is : It looks a bit like a real mecanism, 
We can modify E according to health, specific anti blob drug, specific anti blob cbms and traits
We can modify S between mutagen and serum and according to the quality of each. We could  have makeshift serum or serum Mk.I and top notch serum Mk.V for exemple
Q can be managed by the player, could be visible with use of specific tool/CBMs/Furniture or through traits such as self aware or some sort of blob attunement mutation.

Wm can vary with each mutation and get higher with the tiet of the mutation the path.
And eventually we could keep track of the amount of work already done on one mutation so that it can be resumed later.

Maybe it's too detailed but I like it ^^ . I might try to make a figure to explain it better when I get access to a computer with internet.

**Comment by AirPhforce** [comment]
Why not have the health stat give a flat boost to whatever it is you just injected? For example, if you have a very high health stat, and use a mutagen, you would end up with a lot more Q. Likewise, if you are of good health, and use a purifier, you would end up with more E then an unhealthy person.

That way these things are less effective if you're of poor health, but if you're of good health you're more likely to get what it is you want (sort of?) out of the injection. 

I feel this makes sense thematically as well because if you've been subsisting on pixie sticks for three in game months and are unhealthy as hell, stuff just isn't going to work that well on you. Likewise if you're a pemmican and pine tea subsisting Chad and go for horns mutatoins, your body would be more, thematically, able to support faster growth.

**Comment by AirPhforce** [comment]
Why not have the health stat give a flat boost to whatever it is you just injected? For example, if you have a very high health stat, and use a mutagen, you would end up with a lot more Q. Likewise, if you are of good health, and use a purifier, you would end up with more E then an unhealthy person.

That way these things are less effective if you're of poor health, but if you're of good health you're more likely to get what it is you want (sort of?) out of the injection. 

I feel this makes sense thematically as well because if you've been subsisting on pixie sticks for three in game months and are unhealthy as hell, stuff just isn't going to work that well on you. Likewise if you're a pemmican and pine tea subsisting Chad and go for horns mutations, your body would be more, thematically, able to support faster growth.

**Comment by Fris0uman** [comment]
Well at the same time the mutagen is a foreign body that is very much going against you, so it would make sense for your body to reject it. And the ability fo your body to do that is dependant on your health.

This way if you've been living on pixie sticks for three months you won't be able to fight back and you might go much further down the path that you want because the blob stays in your system.
And if you're super healthy you'll progress one tier down the path and that's it (the numbers need to be calibrated towards that).
This way unealthy means you have no idea what's going to happen and you'll probably go too far, and healthy means the mutagen will work just as advertised and you'll be able to stop in time.

Then if you want to make it more complexe we can say that the blob needs matter to build something new and then it take from your `Hunger` or more credibly your `Starvation` pool to build the new mutation, this way being healthy (or at least well fed ) is a boost toward mutating. Well more like a requirement because otherwise you'll starve even more. And that would make thermodynamical sense because otherwise the blob is creative stuff out of nothing.

**Comment by AirPhforce** [comment]
That works too. 

Ultimately I would like to see a 'thing' the player could to to encourage more mutations and influence the system a bit, such as high health meaning more, or a full stomach resulting in more, and either of those causing purifiers to work better.

As for your body being healthy and rejecting mutagen more then a weak body, sure that does make sense. But it is essentially science fiction, there is no real life analog to a serum you can inject to give you retractable claws. However, if the mutagen works better on healthy people, it would strongly incentivize getting and staying at max health for the process, which is something I think benefits game-play while also incorporating 'health' into the calculation. If a 'weaker' body mutates more it may result in people deliberately tanking health just so they can mutate more 'efficiently' as it may result in less mutagen needed overall. This can be explained by just stating somewhere that a healthy body gives the mutagen more ability to change what it needs to change, and I think we can simulate the body 'rejecting' mutagen as we currently do, by causing it to have a big health negative effect. 

It is why I support a 'good health = more ideal changes' concept for mutating and purifying.

**Comment by Fris0uman** [comment]
>Science-fiction

Well yes but I would prefer if it was science fiction that makes as much sense as it can.

>strongly incentivize getting and staying at max health for the process

Well max health is already incouraged because that's what help you heal, it would still be encouraged because it would help you stay in control of your mutation. I don't think that people are currently considering `Genetic Chaos` and `Unstable Genetic`  as very good mutations.
Also we could introduce drugs that influence the parameters of the mutations which is an oportunity for more content.
Also also I think that's it's pretty ok if players are actually willingly tanking their health to mutate faster. It's a trade off between health and mutation, which is what you suggest with mutagen degrading your health but here you're doing it willingly because you put it your gameplay strategy and I think it's better.

**Comment by AirPhforce** [comment]
Sure, I agree with you then!

**Comment by tinukedaya** [comment]
I really like this idea. Would probably even make me start playing around with mutations. Right now I usually avoid them as much as I can while keeping an purifier around for the random mutations. 

What I also like further down the topic are the affixes to the mutations. An analogy that immediately comes to my mind is Diablo (and I'm talking the original one right now) and it's item generator.  

You have a basic item (mutation) with some stats. 
You have a list of possible prefixes that can be added to the basic item. ("weeping", "fragile", "sturdy", "hollow") which add some additional (negative and/or positive) property of the mutation.
And then you have a suffix that might add yet another stats. Again possibly both positive and/or negative. ("with bone hooks", "with venom gland")

With every tier transition (maybe only 2 and higher?) you have a chance of getting the prefix and/or suffix. Once you have them every tier transition has a chance (50/50) of loosing or keeping it.

This way a lot of randomness can still be added to the mutations even if you can better keep the general direction under control.

Just a few possible end results following on the horns: 
Demonic Horns (just a "normal" set of Demonic Horns...)
Sturdy Demonic Horns (additional bash damage / higher encumbrance due to it's higher density/weight)
Sturdy Demonic Horns with bone hooks ( as above plus chance of being stuck in your victim for some time while adding a lot of cutting damage)
Hollow Demonic Horns (less damage / less encumbrance due to less weights. Kinda opposite to "Sturdy")
Pointy Demonic Horns (Extra sharp for some piercing damage) 

And if someone is up for the complexity challenge, the prefixes/suffixes might have their own dependency or even progression tiers.

(btw: is prefix/suffix actually correct term in this case? Isn't it more like adjective/something but well you know what I mean.)

**Comment by AirPhforce** [comment]
It is like diablo.

As you said, it would be a modular system. With affixes (both suffix and prefix as defined in the entry for that thing) supported. I would imagine a 'mutationaffix.json' reading something like this;

        "type" : "mutation_affix", //name of the new type
        "id" : "HOOKED", //internal name
        "name" : "Hooked", //name used in game
        "opposite" : "None" //used for when one affix cancels another out, so 'Brittle' could change to 'sturdy' without getting both.
        "affix" : "Pre", //pre if it goes before the mutation, "post" if it goes after, ie 'Hooked Horns' or 'Horns Hooked'
        "points" : 1, //lower or negative numbers are bad changes, such as bleeding, frail, etc, higher numbers are positive changes
        "affix_message" : "Your "id" : "HORNS_CURLED"" possess menacing hooks." //added to description when examining that mutation on a new line below the normal description.
        "gain_message" : "Your "id" : "HORNS_CURLED"" grow menacing hooks."
        ##actual code work goes here where the affix adds damage or lowers damage or changes metabolism or stats or minus head health for brittle horns or whatever it is this affix does, 

So we write a bunch of these, then go through and add them to applicable mutations in a new entry for 'valid' affixes for that mutation. For maximum fun, we should not limit how many affixes one item could have, so if you go hog wild you could end up with like "Imposing hooked spiked bleeding sturdy demonic antlers."

I would also be of the opinion that we add an item that specifically augments mutations, functioning either on random chance or like the proposed overhaul above; take too much and end up with horns so big you nearly starve to death as you sleep.

**Comment by NancokPS2** [comment]
I'd say that to keep the gambling idea there, the downsides should never be guaranteed
If you always get a downside as you go down a path, then it's not longer gambling, it's just a straight sidegrade
With that said i don't know if mutations are necessarily about gambling, if you go down a path fully you are pretty much guaranteed to get all the pros and cons within that category, the only gambling is in the order in which you get said downsides
If you go willingly down a mutation path, you are by definition ready for whatever downside you may get unless the goal is to just use debug mode to remove the unlucky mutation later

**Comment by I-am-Erk** [comment]
I think this issue can be reasonably closed at this stage, as the current mutation system is pretty similar to what I envisioned.
