### ISSUE TITLE
Some mutation attacks use incorrect damage types

### ISSUE THREAD

**Issue by Photoloss** [CleverRaven/Cataclysm-DDA#28303]
**Describe the bug**  
- HORNS_POINTED explicitly mentions a piercing attack and "stab" in the log message but inflicts bash damage
- TAIL_THICK is described as "long, thick, lizardlike" and "whap"s but deals stab damage
- TAIL_CLUB also deals stab damage, this one should be obvious

**To Reproduce**  
[Source code](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/mutations.json)

**Expected behavior**  
- HORNS_POINTED should deal stab damage as advertised. 
- TAIL_THICK should deal bashing damage
- TAIL_CLUB should deal bashing damage as advertised. 

**Additional context**  
If multi-type damage akin to weapons is desired a lot more mutation attacks need changes. 

A "Spiked Club" mutation akin to mace vs. morningstar could be added if more dinosaur hybrids are desired.

**Comment by Tatterdemalian** [comment]
- HORNS_POINTED: In addition to doing bash damage, it does an unusual amount of damage, comparable to a steel spear. In addition to converting the damage to "stab," I would also recommend bringing it more into line with the damage one would expect of a non-metallic horn, essentially making it a fire-hardened wooden spear without the to-hit bonus and reach attack. Should probably also lower the chance to occur below that of HORNS_CURLED, since the area that causes damage is smaller and likely harder to properly deploy, especially in melee.
- TAIL_THICK: I favor keeping this as is, since bullwhips also do stab damage. Whips don't bash to inflict damage; rather, the damage comes from the supersonic speed the end of the whip moves at (the sound of a whip cracking is essentially a small sonic boom), which is why they can cut flesh.
- TAIL_CLUB: Definitely needs fixing.

**Comment by Photoloss** [comment]
Copy-paste from my reply to your PR: It says "whap" [right here](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/mutations.json#L2806) in the log message text. And a *thick* tail definitely counts as a blunt object. My first guess would be that the bullwhip deals pierce damage because reach attacks are [hardcoded to scale off that skill](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/melee.cpp#L520).

Mutation damage is not currently comparable to weapons *at all.* As I already stated *many more* mutations would need to be considered in this regard so that should be done in a separate PR for the sake of consistency. Horns and spears aren't comparable directly anyway because a spear thrust's force is limited by the mass of the spear or the strength of your arms (either you "let it fly" or your arms are actively pushing on it during the impact) while horns depend on the strength of your neck and your willingness to risk a concussion. I'll also note mutations are created by active Blob inside the person so they may very well provide supernatural material properties in addition to the more obvious unrealistic aspects like Hollywood acid blood.

**Comment by Tatterdemalian** [comment]
Fine, I was just stating my case. Changes made to damage types, no other changes made.

**Comment by kevingranade** [comment]
Fixed by #28307

**Comment by Photoloss** [comment]
> Fine, I was just stating my case. Changes made to damage types, no other changes made.

Sorry, guess I was a little harsh. I don't mean for you to quit entirely, just that aligning mutation attacks with weapon mechanics and rebalancing them should be done in a separate issue and probably warrants a broader discussion. The mutation mechanic itself is being discussed in #28277 and I'm sure they'll welcome more people doing the legwork once the core mechanics are done if not sooner.
