### ISSUE TITLE
Tiles no longer scaling when pixel resolution less than screen resolution

### ISSUE THREAD

**Issue by kd8qdz** [CleverRaven/Cataclysm-DDA#28383]
When using windowed Borderless or windowed mode, setting the number of tiles no longer scales when set to a number that would result in a resolution less than system screen resolution.

**To Reproduce**  
Adjust settings to match as above. 

**Expected behavior**  
Tiles should scale to become larger on the screen because on small but high resolution monitors, the fonts become to small to read.

**Versions and configuration(please complete the following information):**
 - OS:Win 10
 - Game Version: 0.C-37529-g91a0c5f (tiles)
 - Graphics version: Tiles
 - Mods loaded: N/A

**Comment by ifreund** [comment]
The new scaling factor option is intended to address this, though it may be buggy on windows right now.  Have you tried setting scaling factor to 2x?

**Comment by kd8qdz** [comment]
well, that did fix it.   I guess i didn't see the option because the font was sooo small.

**Comment by ifreund** [comment]
Perfect, may I ask how it's working for you? Have any graphical/window size issues?  I don't have a windows machine to test the new stuff unfortunately

**Comment by Alapaga** [comment]
Windows 10 user here, I play windowed mode most of the time, and i have a few issues similar to this.

I wanted a bigger font size than what was standard, and I started fiddling with the parameters while on windowed mode.

If i get scaling factor to x2 or x4 from x1 and then restart the game, the game doesn't register the scaling factor change, it resets to x1 and the console width/height defaults to 160 and 41 respectively, which coresponds to a resolution of a window that fills in a 1280x720 desktop but leaves the taskbar visible.

If I don't touch the scaling factor and start tweaking the console width/height one of two things will happen :
- if the resolution ingame is higher than the screen resolution let's say my screen res is 1920x1080 and i set the numbers to get 2304x1296 resolution ingame, after restarting the game the numbers reset to match a 1280x720
- if the resolution ingame is set to 768x432 the game window becomes smaller but then the text is harder to read as a result

If I select windowed borderless, the resolution doesn't ever change because of me imputing numbers and always reset to match a 1280x720 after restarting the game.

I hope this helps, let me know if there's more testing to be done on this.

**Comment by ifreund** [comment]
Thanks, that's very helpful.  Would you happen to have 2 displays in your setup or something like that or just the one 1920x1080 display? If so which one is selected in the options menu as the default? 

>If i get scaling factor to x2 or x4 from x1 and then restart the game, the game doesn't register the scaling factor change, it resets to x1 and the console width/height defaults to 160 and 41 respectively, which coresponds to a resolution of a window that fills in a 1280x720 desktop but leaves the taskbar visible.

To explain a bit about what's happening, on a restart the game should check to see if it has enough screen space to display at 2x or 4x.  It seems that this check isn't working properly on windows.  The way it does this is to open and close a maximized test window the read the size of that window. 

> if the resolution ingame is higher than the screen resolution let's say my screen res is 1920x1080 and i set the numbers to get 2304x1296 resolution ingame, after restarting the game the numbers reset to match a 1280x720

The fallback windowed size is determined by the check for maximum windowed size that seems to be misbehaving.

> if the resolution ingame is set to 768x432 the game window becomes smaller but then the text is harder to read as a result

Is the text actually getting scaled down here? If so that should definitely *not* be happening...

>If I select windowed borderless, the resolution doesn't ever change because of me imputing numbers and always reset to match a 1280x720 after restarting the game.

Ok, SDL definitely thinks that your display is 1280x720 for some reason.  Any idea why that would be?

Thanks so much for the help with this, hopefully we can get the kinks worked out soon

**Comment by Alapaga** [comment]
> Thanks, that's very helpful. Would you happen to have 2 displays in your setup or something like that or just the one 1920x1080 display? If so which one is selected in the options menu as the default?

I do have two displays, and the one selected in the game is the 1920x1080 one (the main display) 
the second one has a 1280x720 resolution which the game seems to fall back to. At some point in the prior testing I was using the second monitor as the one the game runs on, but i switched back to the main one as it didn't seem to scale the fonts up putting it on the second monitor with a lower res (even taking into account the monitor is slightly bigger physically than the main display is). so the 1280x720 figure is not a worrying thing for me, as it does correspond to one of the screen resolutions after all. and besides that, the games seems to be the exact same size regardless. It might be due to the fact that i am using a 150% zoom in on the main screen on the windows 10 desktop display options, it makes the icons on both screens be of the same size, and so the game seems to think that the display is 1280x720 on windowed mode even tho the screen resolution is 1920x1080 for all other intents and purposes.


> To explain a bit about what's happening, on a restart the game should check to see if it has enough screen space to display at 2x or 4x and if not set it to 1x scaling factor and the maximum windowed size possible. It seems that this check isn't working properly on windows. The way it does this is to open and close a maximized test window the read the size of that window.

I went on and i disabled the 150% zoom levels and then activating the x2 scaling factor for the 1920x1080 display screen on windowed mode did work as intended, but there are some flickering artefacts on top and bottom of the game screen 

Resizing the game console to 786x432 and then going x4 showed a very deceiving game screen (at least to me) but terminal width is capped at max screen resolution as intended 1920x1008 in windowed mode and the scaling factor is reset to x1 again in the options. 

I was deceived because the main reason i would wanna go with a small res and add a scaling factor was to up the font size, but it just seems to multiply the numbers on the terminal width/height. and if it thinks that the screen can't handle the size of the resulting windows, it just caps at the max res and that's it


[Video of the flickering.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2906067/Video.of.the.flickering.zip)

> Is the text actually getting scaled down here? If so that should definitely _not_ be happening...

it is going as intended, the text size is the same relative to the window, but since the window's smaller, i almost can't read anything anymore on a high res screen.

That's all the feedback I have, let me know if you need me to do some testing again. I am more available on the game's discord as finding this thread was a little difficult to me, I'm a dabbling user of github at most. 

Alapaga out
