### ISSUE TITLE
Investigate mainlining iOS code

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#28404]
The developer of the iOS port has published his source on github: https://github.com/CliffsDover/Cataclysm-DDA/releases

We should investigate mainlining these changes.

**Comment by Epictyphlosion** [comment]
Oh man, I remember one of the first times I played C:DDA was on the iOS version. I even bought the sound pack addon! The version was WAY out of date last time I checked, and it's great to see the person who ported it making it open source!

**Comment by ZhilkinSerg** [comment]
There are a lot to fix:

![image](https://user-images.githubusercontent.com/16213433/53496976-376e2380-3ab4-11e9-8250-098c1f54fc21.png)

![image](https://user-images.githubusercontent.com/16213433/53497007-481e9980-3ab4-11e9-9e33-d3d2a43c5778.png)

**Comment by ZhilkinSerg** [comment]
It seems files from the latest IOS archive are from October, 2015 (probably 2fe649e7b6004bc954fa3a16c61b0498f2da267b).

**Comment by ZhilkinSerg** [comment]
### Files added/modified in IOS version:

0. Folder with various IOS stuff (project files, headers, libraries, etc):

- `IOS`.

1. Several helper scripts:

- `build.sh`;
- `gfx/convert.py`;
- `tools/DumpSoundUsage.py`;
- `tools/ogg2wav.py`.

2. Updated translations:

- `lang/po/zh_CN.po`.

3. Updated soundset:

- `data/sound/soundset.json`;
- `data/sound/*.(ogg|wav).

4. Updated tileset:

- `gfx/ChestHole32Tileset/fallback.png`;
- `gfx/ChestHole32Tileset/tiles.png`.

5. Changes to source files:

- `gfx/ChestHole32Tileset/fallback.png`;
- `gfx/ChestHole32Tileset/tiles.png`.

6. Changed Cataclysm-DDA source files:

- `src/game.cpp`;
- `src/main.cpp`;
- `src/main_menu.cpp`;
- `src/options.cpp`;
- `src/sdltiles.cpp`;
- `src/sound.cpp`;
- `src/vehicle.cpp`.

**Comment by ZhilkinSerg** [comment]
Split changes to different commits and created a branch here - https://github.com/ZhilkinSerg/Cataclysm-DDA/tree/cdda-ios.

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/how-to-fix-game-for-ios-14/25319/2

**Comment by apollovy** [comment]
New iOS app is here and available for installation in the app stores! Read the press release [here](https://www.notion.so/cdda/1-0-f55b20dd45cc48b39ee86e4fb42f2014).

**Comment by ZhilkinSerg** [comment]
> New iOS app is here and available for installation in the app stores! Read the press release [here](https://www.notion.so/cdda/1-0-f55b20dd45cc48b39ee86e4fb42f2014).

You better make an announcement on Reddit/forums.

**Comment by apollovy** [comment]
Already done it: https://www.reddit.com/r/cataclysmdda/comments/kuiot0/new_ios_app_is_here_and_available_for/, thanks for suggestion.

**Comment by Widdershin** [comment]
@apollovy I posted a new version of the announcement thread, as that one had been removed fairly early on.

The new post got some traction, and I think there are some folks in there who would love to hear from you: https://www.reddit.com/r/cataclysmdda/comments/kvkyct/new_ios_port_now_released_based_on_0e3/

Thanks for your work by the way, it's high quality! Looking forward to seeing how it progresses, and helping out if possible. Is the code mainlined/planned to be mainlined?

**Comment by apollovy** [comment]
If under "mainlining" you mean "support / maintain" then yes. I have plans to implement some features, including more user-friendly screen controls. Btw app store reviews and improvement suggestions count as helping. I'd love to hear from the users!
If you mean "updating to the experimental version: then I'm planning to have another app with experimental under the hood. That's because of the stability and save games, of course. I tried to simply replace 0.E-2 onto master and load my saves and encountered some difficulties just after the load was complete. So I believe it's better to have 2 versions in app store, same policy as for the main game itself :)

**Comment by Widdershin** [comment]
@apollovy thanks for the context. I was more wondering if you’re planning to contribute the code for your iOS port back to this repository? I’d be personally interested in reading it and helping to maintain if needed.

**Comment by apollovy** [comment]
Well, not now. I wanna play with that stuff myself for some time, and then I believe I'll open the source. And since it's a clear wrapper, meaning no lines of original code were modified to make things work, I'm unsure whether it's a great idea to mix repos. But we'll see.
For now I can say that the repo is already in the github, but it's private. And one of my main goals when approaching this project was to make is fully and easily supportable and upgradeable, so I wanna assure you that I know what am I doing: I have 10 years of experience developing business applications in python, so I sort of know approaches, best practices, tools and friends and am interested in playing with that stuff in iOS/ObjC/Swift domain, because it's new and exciting for me.

**Comment by kevingranade** [comment]
If you aren't going to open your changes you aren't welcome here. You're taking the output of over a thousand people's freely shared work and using technicalities to maintain sole control of it on iOS.

**Comment by apollovy** [comment]
Okay, folks. After a couple of months of active development I am now ready for opening the sources and, if desired, to integrate with this repo. Kinda become a part of a family :)
What am I to do? Just open the repo? Or maybe something else?

**Comment by anothersimulacrum** [comment]
Opening the repo is a good start, then you can look into how the android port was mainlined (https://github.com/CleverRaven/Cataclysm-DDA/pull/24674).

**Comment by apollovy** [comment]
Okay, here I go: https://github.com/apollovy/Cataclysm-DDA-iOS
I've chosen MIT for initial license, you can suggest I change it if it's necessary.

**Comment by kevingranade** [comment]
Well that's pretty much a wash, we don't really need a project or tracking issue, we need someone interested in championing an official iOS build, until that person appears there's no reason having an issue sitting here.

**Comment by Epictyphlosion** [comment]
Darn, I remember first playing CDDA on my old iPhone way back when. Shame that build hasn't been picked up in all that time. Oh well.
