### ISSUE TITLE
error: npc dying in passenger seat

### ISSUE THREAD

**Issue by FONZACUS** [CleverRaven/Cataclysm-DDA#28411]
**Describe the bug**  
slight error when an npc (friend and foe) die on a passenger seat.

**To Reproduce**  
1. easiest way should be having an npc friend
2. spawn a bike
3. and a hostile turret behind

**Expected behavior**  
business as usual i guess?

**Screenshots**  
none

**Versions and configuration(please complete the following information):**
 - OS: win10 x64
 - Game Version: 8549
 - Graphics version: tiles
 - Mods loaded: default

**Additional context**  
both parts of the error copied.
```
DEBUG    : map::unboard_vehicle: passenger not found

FUNCTION : void map::unboard_vehicle(const tripoint&)
FILE     : src/map.cpp
LINE     : 908

DEBUG    : Empty passenger part 12 pcoord=61,70,0 u=61,70,0?

FUNCTION : vehicle* map::displace_vehicle(tripoint&, const tripoint&)
FILE     : src/map.cpp
LINE     : 992
```

**Comment by kevingranade** [comment]
Looks like there's a conflict here where the vehicle code is failing to remove the dead NPC because it's sanity checking that the NPC in question isn't dead.  Since the NPC IS dead, it's cancelling out of the operation before removing the flag on the vehicle part indicating that there's a NPC there.

**Comment by FONZACUS** [comment]
thanks, did a round on 8563, dead passengers and moving to different tiles is fixed for me.
