### ISSUE TITLE
"again" in the enter menu

### ISSUE THREAD

**Issue by Headjack** [CleverRaven/Cataclysm-DDA#28450]
The 'Enter' menu is nice and all, but could perhaps the first selected option be "again", so that it re-performs whatever you did last with the enter menu? For example, I want to till earth, but I need to go in and find that each time. I'd rather hit enter twice and get straight there.

**Comment by zsebastian** [comment]
For tilling earth you can use zones. For disassembling multiple items you can drop them on the floor and enter the butchering menu. For most operations that you would do multiple times there is a better way of doing it than something like an 'again' command.

**Comment by Headjack** [comment]
Why not both? There's surely several applications it would help. The enter menu itself is entirely redundant, in fact, and everything there can be done some other way.

**Comment by kevingranade** [comment]
Because it makes the code more complicated, and if there are suboptimal options for performing actions, people can easily get stuck taking those suboptimal options instead of finding better ones.

In particular, the enter menu is more a way to *find* actions than the best way to trigger routine actions.
