### ISSUE TITLE
Adjust city spawning options in worldgen to allow more control

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#28538]
**Is your feature request related to a problem? Please describe.**  
City generation is currently very difficult to control. The max size is only 16, and the code for choosing city size looks like this:
```int size = rng( op_city_size - 1, op_city_size + 1 );
        if( one_in( 3 ) ) {      // 33% tiny
            size = 1;
        } else if( one_in( 2 ) ) { // 33% small
            size = size * 2 / 3;
        } else if( one_in( 2 ) ) { // 17% large
            size = size * 3 / 2;
        } else {                 // 17% huge
            size = size * 2;
        }
```
This is very coarse code that doesn't allow much variation at all.

**Describe the solution you'd like**  
Really, we should be able to set "average city size" and "maximum city size", and instead of four coarse categories of city size, the game should then make cities choose their size along a normal distribution from those two data points.

There is already a rand_normal function in rng.cpp, so this shouldn't be too tough.

It would also be nice if the upper limit in size was much higher.

**Describe alternatives you've considered**  
Even just a better designed equation than the current one would be nice, if we didn't go with a normal distribution.

**Comment by OrenAudeles** [comment]
A simple triangular distribution is pretty nice looking and is easy to calculate.

Given: `A = min city size - 1`, `B = max city size + 1`, `C = most common city size`
The +/- 1 to A and B are so that min and max size cities can actually be picked.
Percentage of cities of size X in range (A, B) is given by the following equations:
if A <= X <= C: `P(X) = 2 * (x - a) / ( (b - a) * (c - a) )`
if C <= X <= B: `P(X) = 2 * (b - x) / ( (b - a) * (b - c) )`

A normal (or other) distribution can also be used. A triangular distribution is just simple to work with as an example.

We can then use a `weighted_float_list` for city size picking using a random value in range [0, 1] by inserting into it the chance of occurrence for each city size.

**Comment by I-am-Erk** [comment]
Triangle would also work, I don't know if there'd be any difference in how it would look in game.

Heck if we want to get technical here we should look at size distribution of cities in new england

**Comment by OrenAudeles** [comment]
If we use the population values from [Wikipedia - List of cities by population in New England](https://en.wikipedia.org/wiki/List_of_cities_by_population_in_New_England) we end up with 150 data points to be formed into a weighted list.

Not sure how that translates into city sizes, but it looks to be a reasonable research direction.
