### ISSUE TITLE
Refillable lighter can compress gasoline 50-fold

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#28589]
**To Reproduce**  
1. Get 100 refillable lighters
2. (optional) Fill them 50mL gasoline each
3. Note their volume

**Expected behavior**  
Refillable lighter consuming more volume than its fuel.

**Versions and configuration(please complete the following information):**
0.C-37610-g8ea7031265-dirty

**Comment by junkyjb** [comment]
Not sure where you are getting 50-fold? Looks like 5 fold to me.

A plastic jerry can is 10 litres and holds 10,000 units of gasoline.
So 1 unit of gasoline is 1 ml.

The refillable lighter's volume is 0.01 litres, which is 10 ml.
So if it holds 50 charges, (50 ml), then it's holding 5 times more gasoline than it should be able to.

Sure this is a little silly, but how should it be fixed?

5cm x 5cm x 0.5cm is 12.5 ml, or 0.0125 Litres. 
Rounded down to 0.01 Litres, is a decent size for a refillable lighter.

Reducing it to 10 uses per refill feels to me like unnessecary busy work for the player.

The problem is that a realworld lighter uses much less than 1 ml of fuel each time it is used.
I can't find numbers for refillable lighters, but Bic claim on their website that their disposable lighters can light up to 3000 flames.

So either it's changed so that it uses less than one charge of gasoline per use, which I assume would be difficult to display to the player, or the volume of one charge of gasoline is reduced which would probably cause headaches for re-balancing vehicles, flamethrowers, molotovs etc.?

Is there really any negative impact to leaving it the way it is? It's not as though players will be hoarding refillable lighters to store their gasoline in less space - they would need to find 200 lighters in order to replace one plastic jerry can.

**Comment by l29ah** [comment]
The refillable lighter's volume is 0.001 litres, which is 1 ml.

**Comment by junkyjb** [comment]
![refillable lighter](https://user-images.githubusercontent.com/48153531/54224929-75c30400-44f2-11e9-8e57-08c77959b9a8.png)

No, it's 0.01 litres, which is 10 ml. 

Why aren't you running 0.D?

**Comment by l29ah** [comment]
No, it's 0.001 litres, which is 1ml, and the display is invalid since it just rounds up anything that is smaller than 10ml.
Because i don't believe in releases of CDDA.

**Comment by junkyjb** [comment]
> the display is invalid since it just rounds up anything that is smaller than 10ml.

Ahh, my bad, now it makes sense why you said to get 100 of them - to note their total volume, not individual volume - sorry!

> Because i don't believe in releases of CDDA

I was asking because I thought maybe it had been fixed since you last updated, but I can confirm that they do have 0.001 volume in 0.D-400-g73b0882 too.

My apologies again.
