### ISSUE TITLE
Deconstructing a threadmill results in a closed metal door

### ISSUE THREAD

**Issue by pescepalla** [CleverRaven/Cataclysm-DDA#28596]
**To Reproduce**  
1. Deconstruct a threadmill

**Expected behavior**  
The tile should become free of obstructions

**Versions and configuration(please complete the following information):**
 - OS: Archlinux
 - Game Version: git master
 - Graphics version: tiles
 - Mods loaded: default

**Comment by Pr0man** [comment]
Just tried to replicate it using the newest master without any mods to no avail. spawned in an ergometer and a treadmill into my shelter and deconstructed them - it neither spawned a metal door or any other structure below it. I also couldn't find any entries regarding this in their furniture declaration that would lead to such a behaviour.

If you encounter this behaviour inside the training rooms of labs, this is most likely due to the way the room itself is designed and it may be a flaw in the design file of said room, as I do remember encountering it inside a lab specifically.

**Comment by pescepalla** [comment]
Can confirm it happens consistently inside labs.

**Comment by int-ua** [comment]
Confirming. Inside lab gyms they leave metal doors behind.

**Comment by Throwaway-name** [comment]
Found it

https://github.com/CleverRaven/Cataclysm-DDA/blob/4ab7b15ad465c232b44dc73011cfd947e91d6d15/data/json/mapgen/lab/lab_common.json#L33

https://github.com/CleverRaven/Cataclysm-DDA/blob/4ab7b15ad465c232b44dc73011cfd947e91d6d15/data/json/mapgen/lab/lab_rooms.json#L975

Could somebody move the palette to mapgen_palettes?

**Comment by Night-Pryanik** [comment]
Closed by #28612.
