### ISSUE TITLE
Range values below 0 in ammo json out of range

### ISSUE THREAD

**Issue by dissociativity** [CleverRaven/Cataclysm-DDA#28607]
**Describe the bug**  
Range values below 0 in ammo jsons causes an out of range error.
Ammo therefore cannot reduce range of weapons, I believe this limitation is a bug, or at least should be considered one.

**To Reproduce**  
1. Try to use darktoes' archery redux:  https://github.com/CleverRaven/Cataclysm-DDA/pull/28069
2. Get out of range error from range of arrows being below zero
3: get booted back to main menu

**Expected behavior**  
Arrows in this PR lower the range of the bows used without error
Alternatively we have a proportional range value instead of a static number of added tiles:
IE: 0.5 to half the range, 1.5 to add 50% range.

**Screenshots**  
![image](https://user-images.githubusercontent.com/40927483/54079143-ba9c3e80-432a-11e9-97c9-d9fd6f1980db.png)

**Versions and configuration(please complete the following information):**
 - OS: Windows 8.1
 - Game Version: Latest as of 10/03/2019 (DD/MM/YYYY) at 11:51AM GMT 11+ Sydney/Melbourne time
 - Graphics version: Tiles
 - Mods loaded: default

**Comment by kevingranade** [comment]
There are two problems with this.
1. You can just set bow range to the minimum and only add with ammo.
2. Range is an extremely arbitrary and artificial number, and is only still around because NPCs aren't smart enough to figure out weapon effective range on their own. New features should not be trying to do new things with range.

**Comment by darktoes** [comment]
> Range is an extremely arbitrary and artificial number, and is only still around because NPCs aren't smart enough to figure out weapon effective range on their own. New features should not be trying to do new things with range.

I suspected as much and that's a pretty fair call. I just wasn't sure if we wanted to support it properly until it was pulled out.

Setting bow range to minimum and adding with ammo would work extremely weirdly, since we'll have a pretty broad range of bow strengths. That said, range through dispersion/accuracy should work out just fine.
