### ISSUE TITLE
Fur trim for hot mutants

### ISSUE THREAD

**Issue by Headjack** [CleverRaven/Cataclysm-DDA#28618]
**Is your feature request related to a problem? Please describe.**  
Fur-bearing mutants become excessively hot in the summer. Realistic, but a sapient being would like to address such problems.

**Describe the solution you'd like**  
We have hair trimmers/ shave kits in the game already. Could those have a way to debuff the warmth gain from fur?

**Comment by kevingranade** [comment]
Can you be more specific about the scenario? Which mutations, what is your gear worn, what is the ambient temperature, and what level of overheating is reached?

**Comment by DracoGriffin** [comment]
### Notes:
Rat mutant with Furry mutation, no other traits that influence
Debug time to summer was used, force updated by teleporting long-range out of reality bubble and back
Torso slot is a bit overrated due to double stacking military rucksacks (10 warmth each for 20 total can be subtracted from Torso heat for slightly more accurate)
### Spring day 36 (of 91 day seasons, default, inside):
![AlreadyOverheatEarlySpring91dayseasons_inside](https://user-images.githubusercontent.com/32253888/54090267-f1c51c80-4337-11e9-812f-13abae1d3103.png)
### Spring day 36 (of 91 day seasons, default, outside)
![AlreadyOverheatEarlySpring91dayseasons_outside](https://user-images.githubusercontent.com/32253888/54090268-f1c51c80-4337-11e9-9bf4-14f1035dcdee.png)
### Spring day 36 (of 91 day seasons, default, inside, standing next to burning two by four in oven after waiting 30 minutes and door/window open to help "vent" radiant heat)
![AlreadyOverheatEarlySpring91dayseasons_inside_nexttoburningtwobyfour](https://user-images.githubusercontent.com/32253888/54090479-3d78c580-433a-11e9-96b7-85922036f9c9.png)
### Summer day 36 (of 91 day seasons, default, inside):
![OverheatingEarlySummer91dayseasons_inside](https://user-images.githubusercontent.com/32253888/54090264-eeca2c00-4337-11e9-849b-e27d91e7a021.png)
### Summer day 36 (of 91 day seasons, default, outside)
![OverheatingEarlySummer91dayseasons_outside](https://user-images.githubusercontent.com/32253888/54090265-eeca2c00-4337-11e9-9210-f960c12e34a4.png)
### Summer day 36 (of 91 day seasons, default, inside, standing next to burning two by four in oven after waiting 30 minutes and door/window open to help "vent" radiant heat)
![OverheatingEarlySummer91dayseasons_inside_nexttoburningtwobyfour](https://user-images.githubusercontent.com/32253888/54090480-3fdb1f80-433a-11e9-93c6-5497dfeea748.png)

### Suggestions
Allow player to shave off "furry" hair with loss of protection and cold tolerance (Becoming "Furry (Shaved) - you shaved off all that extra hair! Slimming and cool for those hot months" or something).

Time spent should be respective of size (considering #28593) - as it normally takes about 1-2 hours to completely shave a "shaggy" canine ([some of the other reasons why pet grooming can take so long](https://i.redd.it/ayy9nc7ktkk21.jpg)) and humans are larger, it might take longer but considering you're much more cooperative than an animal is, it should probably be roughly the same amount of time or less. ([Source](https://www.quora.com/How-long-does-it-take-to-shave-a-dog))

If we go with sheep shearing, the world record is apparently [37.9 seconds with the correct tools](http://www.sheep101.info/shearing.html) although [those usually have teams](http://www.shearingworld.com/worldchamps/Worldchamps.htm). The average time per sheep is about two minutes with professional equipment (aka not using rusty scissors).

Lastly, length of time should be several weeks unless enhanced by blob stuff, as it takes a completely shaven area of a dog to regrow ([independent of seasonality, source](https://www.ncbi.nlm.nih.gov/pubmed/14989702)) average of 14.525 weeks or roughly 100 days.

If we go with sheep, then:
> It takes up to six weeks for the fleece to regrow sufficiently to provide effective insulation. 

and

>Sheep grow wool continuously. If they are not sheared at least once a year, they become very stressed and uncomfortable, especially when it is hot and humid. Eventually, the wool will become matted, stained, and difficult to remove. It is inhumane to not shear sheep that require it.

So a side-effect of NOT trimming could be added in which morale decreases, move cost increases or whatnot.

**Comment by Headjack** [comment]
Er, yeah, what he said.

I think URSINE_FUR, LUPINE_FUR, and FUR are the most notable ones, since they provide high warmth  and describe longer, insulatory fur that could conceivably be trimmed. During daytimes, I'm seeing over 34 warmth even with no warmth-adding gear on while indoors, more when it's sunny, and frequent pain in the extremities because of it. This, with around a -20% speed debuff for Hot.

**Comment by kevingranade** [comment]
Ok, so as expected, you're trying to run with a standard load out of gear in addition to having the fur mutation.  Thus is substantially working as intended.  The fix is ditching some of your gear or not mutating.

I don't like the shaving thing, it requires micromanagement, it requires new infrastructure for tracking mutation state, and it's not something that's going to accomplish much IRL.  Fur-bearing creatures don't sweat, so their ability to shed heat through their skin is impaired even if the fur is gone. What fur-bearing creatures do to get rid of heat is pant, which I don't believe is adressed anywhere in the mutation system.

**Comment by Headjack** [comment]
That's true, I was looking into it some more and it seems like fur coats have a sort of winter/summer cycle that addresses this by...not being so hot sometimes. Panting is also appropriate as a replacement for sweating it seems.

In my case I had on cargo shorts and nothing else and had overheating, but not above 50 like Dracogriffin.
