### ISSUE TITLE
Extremely annoying (I)gnore, and how it could be fixed

### ISSUE THREAD

**Issue by gmiz** [CleverRaven/Cataclysm-DDA#28672]
**Is your feature request related to a problem? Please describe.**  
While (for example) moving 100 two-by-fours from one space to another using the advanced inventory, if there's any kind of loud noise, player is stuck having to hold the I key to ignore the sounds. I'm pretty sure everyone is already familiar with and have encountered the problem at least one time in the game.

**Describe the solution you'd like**  
IMHO, we should have something like "ignore sounds entirely" option, or we should use the safe mode to say that we don't want safety while moving these items. There is a problem though, and that's: What happens if a zombie comes and kills me while i'm moving the stuff and have the safe mode off?
Well, I think safe mode works as a "sight safe mode" currently, so adding sound to that would be weird and hard. Maybe it's better to add an additional safe mode called "sound safe mode" which controls safety for sound only. Also if you decide to add scent detection to the player some time in the future (Like, for example, "you can smell rotten meat here!"), you could add another safe mode for scents called "scent safe mode" which would control the scent detection only. With more safe modes, every player has more in-game control in my opinion.

**Additional context**  
For me, this is a must-do "fix". I've seen people getting really mad about having to press 'I' to ignore all the messages, and i've experienced it myself too. I think it's super annoying, and with more safe modes and more control, this could be fixed nicely.

Thank you for your time!

**Comment by ZhilkinSerg** [comment]
> IMHO, we should have something like "ignore sounds" option

You already have a couple of options for that: like ear plugs or noise cancelling head gear.

**Comment by Gmiz** [comment]
> You already have a couple of options for that: like ear plugs or noise cancelling head gear.
@ZhilkinSerg Yeah, I know there are options, but I spawned in an evac shelter with tons of triffids around it and I couldn't do the easiest of tasks without being interrupted.

**Comment by RickySandbox** [comment]
> I know there are options, but I spawned in an evac shelter with tons of triffids around it and I couldn't do the easiest of tasks without being interrupted. You want me to wish for an item :-)

I know exactly how you feel, especially when I played The Last Firefighter and zeds kept beating on the walls when I tried doing the slightest things. Seriously, it felt like they could hear me cutting rags into thread! :laughing: 

Continuing where @ZhilkinSerg left off, you can craft _noise canceling headgear_ with thread, string and a few rags at level 1 tailoring, and you can reach level 1 by crafting a few makeshift bandages from rags. (You'll probably need the bandages later.) Once you're wearing the headgear you're deaf and will only be interrupted when something enters your line of sight or attacks you.

(Someday you might need that headgear _and a blindfold_ to keep from being interrupted by an annoying hulk behind glass, because every room around you contains things that you're not equipped to handle, yet!)

**Comment by Gmiz** [comment]
> Continuing where @ZhilkinSerg left off, you can craft _noise canceling headgear_ with thread, string and a few rags at level 1 tailoring, and you can reach level 1 by crafting a few makeshift bandages from rags. (You'll probably need the bandages later.) Once you're wearing the headgear you're deaf and will only be interrupted when something enters your line of sight or attacks you.

Alright @RickySandbox , that seems like a great quick solution, but I'm just talking about the game concept here. What will happen if totally new players get caught in this kinda situation?
What I'm trying to say is: I know there are ways to stop it, but why would you prefer stopping a badly designed feature manually by using in-game hacks over re-designing and fixing it? :smile:

BTW, thank you both for your precious time! :+1:

**Comment by I-am-Erk** [comment]
I do kind of agree with gmiz here. You shouldn't need to wear earplugs when crafting to signal to the game that you don't want to be interrupted by every background noise.

**Comment by CoroNaut** [comment]
Could simply be a true/false option in settings under gameplay and default it to true for new players.

**Comment by Gmiz** [comment]
> Could simply be a true/false option in settings under gameplay and default it to true for new players.

I feel like having an in-game real-time version of that true-false would be more useful and realistic since humans can listen to something or they can just ignore the sounds around them and they can change that all the time. It simply makes the game more natural, and we already have the "sight safe mode", so why not expand the possibilities and add more realism :slightly_smiling_face: 

Once again, thank you for your time everyone!

**Comment by Mooses2k** [comment]
Having an option to have, in the warning dialogue itself, the option to forever ignore this sound or spotted monster (separate matter to ignore its approach or attacking you). Using existing safemode menu, just have it autopopulate from that dialogue itself rather than requiring remembering and adding every type of zombie and squirrel from there that you're not concerned with. Maybe also an 'ignore this for an hour or for a day?" Maybe an 'ignore white tier zombies and wildlife"? These are barely formed first thoughts for discussion.

#23828 related

**Comment by I-am-Erk** [comment]
Having the option to put certain monsters into the safemode ignore list right from interruption seems like it would be an easy add and quite nice

**Comment by Mooses2k** [comment]
I'd like this resolved and I'll put a bounty behind it.

Could we have some discussion on what sort of solution is best?
PR #28961 - should involve safemode, fix the chapter-reset bug
Issue #23828 - should include automarking certain creature types and manually marking specific creaturees ignored
PR #30866 - some non-working code maybe useful or an example

Thoughts?

**Comment by Destragon** [comment]
I'm surprised this still hasn't been fixed, looking at how annoyed people get by it. I think someone should just take #28961 and make it depend on safe mode. Deactivated safe mode should make you ignore all interruptions while performing any action, although I'm not sure if it really should ignore the damage ones.

**Comment by I-am-Erk** [comment]
As always, someone has to get annoyed enough to start coding a fix
