### ISSUE TITLE
Some food too provides too many calories per portion

### ISSUE THREAD

**Issue by drayath** [CleverRaven/Cataclysm-DDA#28783]
**Describe the bug**  
Portion sizes for high energy foods are too large making them difficult/impossible to fully eat.
E.g. Fruit Waffles are 4200 calories.

**Expected behavior**  
Portion sizes of foods should be reasonable.
In my opinion should cap at the value need to get from just hungry to just sated, which leaves a bit of leaway for bionics/mutation that affect nutrition. 
Alternatives: Ability to hold/eat partial potions of food (e.g. eat until sated and keep the rest for later) or managing food by charges/weight (e.g. removes portions from recipes and replace will producing XXX calories/grams of food which can be eaten/uses as such)

**Comment by DSeyka** [comment]
Fruit waffles are 426 calories, both in data/json/items/comestibles/wheat.json and in-game:
![image](https://user-images.githubusercontent.com/34726992/54499443-f9ca2100-4922-11e9-9c54-5d6cd384ebbd.png)

**Comment by drayath** [comment]
After recent changes food calories are based on the ingredients, not what is specified in the recipe.
Just double-checked Fruit waffle = 3969 calories with: condensed milk, tallow, bird egg, maple syrup, tallow, sugar, water.
4200 was achieved with different ingredients.

**Comment by DSeyka** [comment]
Yes, I figured out a bit later that you were talking about crafted ones. Can confirm.

**Comment by drayath** [comment]
Ah, didn't realize non-crafted items still used values from recipes. That is probably a separate issue as non-crafted items should at least match in calories/nutritional as the crafted version (with worst/typical ingredients at least)

**Comment by drayath** [comment]
A random though, but if food crafting code already handles portion count in recipes (e.g. divides total ingredient calories between recipe portions) could it just automatically bump up the portion count until calories per potion < ?1000?  and everything else would just work (as calories/nutrition would be appropriately divided between portions)

**Comment by MisterWytt** [comment]
Perhaps there's a way to make it so you can eat some of it, and the rest later? Like leftovers you can save up instead of eating the whole thing and throwing away the rest you can't eat.

**Comment by DSeyka** [comment]
4200 cals for a fruit waffle is what I'd categorize as not intended.  
24-hour norm is 2000 calories on average, both in-game (assuming no traits) and IRL.

**Comment by Mecares** [comment]
Could you provide a list of affected items?

**Comment by junkyjb** [comment]
This looks to be the same as issue: https://github.com/CleverRaven/Cataclysm-DDA/issues/28634
[28634](https://github.com/CleverRaven/Cataclysm-DDA/issues/28634)
It was suggested there that the problem is that the high calorie tallow/lard is being used as an ingredient rather than a tool.
(Comparing Chocolate Waffles and Chocolate Pancakes.)

**Comment by KorGgenT** [comment]
right, so lard, tallow, and fat are very calorie dense. if you eat them, that's a lot of calories. if you use them to cook a pancake, you're basically eating them. HOWEVER; the way the code works now is that if you use them as a tool it doesn't not include them as an ingredient whatsoever, which isn't accurate at all because if you cook with lard you're going to end up eating lard.

honestly what i think should be done is to alter tallow and lard to have much smaller portions, and use those portions for cooking (as an ingredient instead of a tool). say, a tablespoon of it. that way the numbers aren't so out of whack anymore, and you can still use a bit of it to cook with.

**Comment by Mecares** [comment]
Used fat as a byproduct that is gross and unhealthy but still edible and can be filtered into cooking oil could also solve the problem.

**Comment by aoae23** [comment]
Yeah, no one is shoving two blocks of tallow in a single pie.
