### ISSUE TITLE
A few issues with new panel layout

### ISSUE THREAD

**Issue by OzoneH3** [CleverRaven/Cataclysm-DDA#28813]
* Defaults to "Label" style should be classic

* Player centering completely messed up (Not taking panel size into account)
![Auswahl_025](https://user-images.githubusercontent.com/3514404/54590405-506d5300-4a28-11e9-9e59-af50d70597fa.png)
![Auswahl_027](https://user-images.githubusercontent.com/3514404/54590572-b22dbd00-4a28-11e9-9d2d-08435f94ad5c.png)

* No pixel minimap displayed even if active (Crashes after toggling it onand off with N #28812)
![Auswahl_023](https://user-images.githubusercontent.com/3514404/54590417-58c58e00-4a28-11e9-85a9-eaa80a22158f.png)

* List items: Monsters tab messed up/missing lines. (Items got fixed it seems)
![Auswahl_026](https://user-images.githubusercontent.com/3514404/54590464-78f54d00-4a28-11e9-9643-b2e2ba5a916e.png)

* Panel Admin lable artefacts in curses mode after moving some around.
![Auswahl_029](https://user-images.githubusercontent.com/3514404/54591669-ffab2980-4a2a-11e9-886e-75cf215adf95.png)

* Panel manager hardly usable on minimum resolution
![Auswahl_022](https://user-images.githubusercontent.com/3514404/54590427-60853280-4a28-11e9-93d5-ccb096c4fe01.png)

**Comment by Tharn** [comment]
More of a feature, but the message log in 'compact' and 'labels' mode is also tiny. Would be nice to give it a bit more room or be able to set number of lines.

**Comment by NEONZARIN** [comment]
![image](https://user-images.githubusercontent.com/16442992/54615182-b4b30580-4a6e-11e9-9023-0c4ce9e80665.png)
Where are these settings? I want to enable classic panel.

**Comment by OzoneH3** [comment]
> Where are these settings? I want to enable classic panel.

It's accessible with the } key.
Should probably get its own ESC menu entry and remove the keybinding.
They are scarce enough and nobody is changing the sidebar style every 2 minutes.

**Comment by NEONZARIN** [comment]
> They are scarce enough and nobody is changing the sidebar style every 2 minutes.

![image](https://user-images.githubusercontent.com/16442992/54617336-1de84800-4a72-11e9-839e-18783649c58f.png)
Thanks for the info, it looks so much better. Is it possible to somehow lower the panel down? As in this screenshot.

**Comment by KorGgenT** [comment]
thank you for your concerns. 
no, it won't default to classic, that's a decision from kevin. it saves what you choose when you close the game anyway, so it shouldn't be an issue beyond when you first load.

not really sure what to do about minimum resolution panel manager, unfortunately. do you have any suggestions for that?
my priority is as follows:
fix crash bug (will fix pixel minimap being shown while i fix the crash)
fix centering oddity
fix monster tab
fix ghosting during panel admin

**Comment by n3tr4k** [comment]
I don't see any minimap even after number of reloads, and in SIDEBAR OPTIONS it's ON. After I tried to activate minimap I've got Segfault (I'm gonna to open a separate issue on that)

**Comment by Tharn** [comment]
There already is one. OP linked it.

**Comment by KorGgenT** [comment]
> I don't see any minimap even after number of reloads, and in SIDEBAR OPTIONS it's ON. After I tried to activate minimap I've got Segfault (I'm gonna to open a separate issue on that)

no, don't open another issue. it's been resolved in the past couple minutes. set your pixel minimap height to 22, that should be square for you.

**Comment by n3tr4k** [comment]
> > I don't see any minimap even after number of reloads, and in SIDEBAR OPTIONS it's ON. After I tried to activate minimap I've got Segfault (I'm gonna to open a separate issue on that)
> 
> no, don't open another issue. it's been resolved in the past couple minutes. set your pixel minimap height to 22, that should be square for you.

eh, too late

**Comment by Redbox12236** [comment]
Just a suggestion, maybe there should be an option to choose where the "pick-up items" sidebar should be

**Comment by KorGgenT** [comment]
once i figure out the ghosting issue, i'll consider that.

**Comment by Fris0uman** [comment]
If you look at the first screenshot you can see that `Per` is displayed as `Int` in classic mod.

**Comment by jeremyshannon** [comment]
If this issue is supposed to cover "everything" then I guess I  should add that in curses mode, the new panel interface has a sort of z-fighting problem when scrolling through items in the "V" menu, where it draws the ground tiles over the panel, then redraws the panel over the tiles with every selection change. It makes scrolling through the list a flickering pain.

**Comment by kevingranade** [comment]
It's not, please open a new issue.

**Comment by tinukedaya** [comment]
I'd like to see three things on the new panel:

1. Adjustable length of the log part. If it would automatically stretch for all available screen space it would be even better (i have empty space below the sidebar with my resolution, would like it to be filled with the messages).
2. add a little indent to the left side just one pixel would be enough to look much better.
3. open the manager from the esc menu

![image](https://user-images.githubusercontent.com/19891532/54743625-eccc5c80-4bc4-11e9-9adc-8106c52f5de2.png)

**Comment by Gmiz** [comment]
> not really sure what to do about minimum resolution panel manager, unfortunately. do you have any suggestions for that?

@KorGgenT Yeah, actually. Maybe you could have the whole sidebar printed out in like a menu, so you have a "final sidebar result viewing mode" or something like that. So when you're in that viewing mode, you can only see the sidebar, so you know what you changed and what's still the same. What I mean is like a popup similar to the inventory popup that would only let you see how the sidebar looks.

**Comment by tinukedaya** [comment]
Also in classic mode creatures only show as letter on the compass. The legend below with creature name is missing. 

When repairing items using the tailor's kit, some messsages (e.g.: You don't have enought rags ... ) only show when you close the repair menu, leaving you confused as why the repair did not happen.

**Comment by Fris0uman** [comment]
>It's not

![image](https://user-images.githubusercontent.com/41293484/54753461-64a88000-4be1-11e9-9ae6-397972eface2.png)

In this screenshot of the screenshot Int is displayed twice with different value and I think it's because the second Int is in fact Per.

> please open a new issue.

I can do that but I thought this issue was meant to list the problems with the new panel layout, and that it would better to not open many different issue on top of it.

**Comment by junkyjb** [comment]
Can we have an option to restore Mouse View as a panel in the sidebar please?
(It could default to off, if you want to minimise clutter for the default experience)
I'm aware we can still view it by pressing ; or x for the pop-up look around panel, but this results in a lot of unnecessary key strokes, both opening it and then closing it again with ESC, each time - where it used to be seamless.

> the message log in 'compact' and 'labels' mode is also tiny. Would be nice to give it a bit more room or be able to set number of lines.

Yeah, it's been reduced to 10 lines in 'classic' mode too. I used to have 20-25 lines with mini-map on, and more when I turned the mini-map off.
Now when the mini-map is off the space is just left un-used.
If we could have an option for number of lines in the main Options-Interface menu that would be great, similar to the mini-map size in pixels under Options-Graphics, or a Y/N toggle for it to auto-fill remaining unused lines even better.

> > Just a suggestion, maybe there should be an option to choose where the "pick-up items" sidebar should be

> once i figure out the ghosting issue, i'll consider that.

Yes please. It could default to off, (shown in the new left position and not as a panel the right sidebar), to save space for users with lower resolutions.
But it would be great to have the option to enable it as a panel on the right for those with sufficient room.
I assume the point of a customisable interface is to provide more options for players to customise their preferred view, rather than forcing a new view upon them.

**Comment by KurzedMetal** [comment]
The km/h display has a bug too on Classic mode, sometimes it overlaps the numbers:

With high target speed (green part) it works kinda fine (no space before ">")
![20190321_182428_cataclysm-tiles](https://user-images.githubusercontent.com/1426680/54786130-ce875080-4c06-11e9-9f60-342cef73316d.png)

But if I get to negative target speed a bit I get something like:

![20190321_181339_cataclysm-tiles](https://user-images.githubusercontent.com/1426680/54786205-07bfc080-4c07-11e9-8170-dbef1482c995.png)

Classic/Label don't show overlapping in my tests but sometimes it doesn't show an space before ">" either. Like:

![20190321_181615_cataclysm-tiles](https://user-images.githubusercontent.com/1426680/54786358-65eca380-4c07-11e9-9647-c8a8137c36bb.png)

**Also, I'm just noticing that Classic have the blue part on the left while Compact/Label has it on the right, it would be nice having consistency here between all 3.**
