### ISSUE TITLE
Knowing Cash-Card PIN and Cellphone Codes

### ISSUE THREAD

**Issue by xrandomuserx** [CleverRaven/Cataclysm-DDA#28973]
How am I able to know the PIN codes for cash cards, and use all the phones I find. 

Cash cards would require computers 10 and electronics perhaps, and resetting phones would require computers and electronic skills. Seriously can one even bypass a cashcard pin? 

Perhaps you can modify individual ATMS (Hacked ATM), but maybe easier to "issue a new cash card" at your nearest bank. On the otherhand, contactless cash cards could be used at vending machines, but not at ATM. Monsters carry cash, cashcard, contactless cash card ect

Traders like cash, gold, silver....

Maybe Zombie Technicians carry their hardware wallet with BTZ .... maybe can find a server farm somewhere, use my HackPro and Laptop and install some mining software.
https://www.ispot.tv/ad/weAP/new-england-mint-coins-bitcoin

Resetting phones is simple, but sometimes requires a laptop computer, could be difficult without an internet connection, but easy enough with high computer/electronic skills

 Ex. I'm always frustrated when I have tens of thousands of dollars from picking up cashcards

A clear and concise description of what you want to happen;
 - Use cash cards for arrows
 - Use cash cards for plastic chunks
 - Light cash cards on fire

 - See above for alternative solutions

**Additional context**  
Add any other context (such as mock-ups, proof of concepts or screenshots) about the feature request here.
https://www.ispot.tv/ad/weAP/new-england-mint-coins-bitcoin

**Comment by Photoloss** [comment]
C:DDA takes place in a dystopian near-future with evidence of omnipresent surveillance and heavy militarisation even before the prelude to the Cataclysm itself began. It is possible these "cash cards" contain no *Personal* Identification Number because criminals/dissenters could *technically* use this to hide the contents from low-ranking government officials. The same logic can be applied to smartphones but with those there'd be a substantial number of legacy devices, if not in the streets then in landfills.

Since cash cards mostly see use at vending machines it's also possible they're set up to allow PIN-less transactions in this context, though I personally have never encountered a gas station where you can get away with that IRL.

**Comment by kevingranade** [comment]
They aren't credit cards, they aren't debit cards, they're cash cards, they physically represent cash.

They're working as intended in that they allow you to accumulate and sometimes use huge amounts of not-that-valuable "old money".

Similarly the phones are presumably operating in some mode where you can make limited use of them (light, time, very little else) without being authorized.

**Comment by xrandomuserx** [comment]
Thanks for clarification on CDDA lore. Have not been here long, and what you say makes sense.
