### ISSUE TITLE
Translation bug when using search option when crafting

### ISSUE THREAD

**Issue by SirPendrak** [CleverRaven/Cataclysm-DDA#28970]
**Describe the bug**  
The part that describes how to use some advanced search options is broken, at least for polish version, while it works in english. See screenshots.

**Screenshots**  
![Crafting pl](https://user-images.githubusercontent.com/43266802/54886624-592bb200-4e8a-11e9-9afd-e00241c0985d.jpg)
![Crafting en](https://user-images.githubusercontent.com/43266802/54886628-5d57cf80-4e8a-11e9-9987-7ec80509218b.jpg)

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version 0.D-572-gc62f18a (tiles)
 - Build 8621
 - Mods loaded:

Dark Days Ahead
Disable NPC Needs
Filthy Clothing
Mutant NPCs
Beta National Guard Camp
Sleep Deprivation
Z-levels enabled

**Additional context**  
I think it was broken for at least a few months now, probably arround 1 or 2 months before D. came out.

**Comment by nexusmrsep** [comment]
I've re-translated the affected parts in Polish translation. I think this might work. Please check this out after next translation update PR.

**Comment by BrettDong** [comment]
This error was because of incorrect place-holder positions in Polish translation. I believe it has been fixed and this could be closed. @Night-Pryanik 
Screenshot taken from binary built on latest master branch
![po](https://user-images.githubusercontent.com/21075502/57682111-a1ce4300-7663-11e9-8c18-89e25b93323f.png)
(oops, here comes another bug, strings on the top didn't change after I switched language to Polish.)

**Comment by Night-Pryanik** [comment]
I'll close this one, untranslated tabs name after switching languages is a separate bug.
