### ISSUE TITLE
Heating or insulation vehicle container.

### ISSUE THREAD

**Issue by vivi00790** [CleverRaven/Cataclysm-DDA#28981]
**Is your feature request related to a problem? Please describe.**  
Liquid in gas tank and food in container rapidly getting frozen during winter. I have one vehicle heater installed but it seems not affecting things in container. Even if it did, which means I must spend more space for additional heaters, is not acceptable because I want a compact car with as much as storage space I could have.

**Describe the solution you'd like**  
1. Something thermostatic and insulate with some storage penalty. Yes, it sounds like a mini fridge, but what in my mind is that it should have at least 120L storage, keep things in it at around 10-15 degrees Celsius and can be installed like a trunk. It should drain some power from battery.
**Edit:** and it won't block my way :(
2. Gas tank with heating device, keeps liquid in it from freezing and drain power from battery.

**Describe alternatives you've considered**  
1. A mini-fridge that won't block my way like floor trunk will do.
2. Maybe let FOODCO can heat up and purify water at the same time?

**Comment by Crunchepillar** [comment]
Is it possible to apply the insulation tag to a vehicle part like how a thermos has insulation 10? If so you could add a 60L tank that is wrapped in uh Nomex(? Nomex is insulating right ?) that would keep liquids thermally stable without the need for a heating element. This would be further increased by always keeping the container topped off since more liquid needs more energy to freeze.

Poking through the JSON it should be possible to add insulation to a copy of the 60L tank as a container but I'm not sure if that will carry over to the vehicle part once it is installed. If it works that could be a fairly simple solution what do you think?

**Comment by Hirmuolio** [comment]
The fridge vehicle part already has insulation on it so I would assume it would work as intended on any vehicle part.

**Comment by Crunchepillar** [comment]
It, indeed, does work as intended. I whipped up an insulated 60L tank mod and then tested it against a regular 60L tank. Both tanks had 0.5L of clean water in them and then I waited overnight to see if the insulation made a difference.

![image](https://user-images.githubusercontent.com/4098225/54947739-080ed300-4f09-11e9-9528-738f7ba87c79.png)

Even with as little as half a liter of liquid in it a tank with insulation:4 (same as the Mini-Freezer) can keep it from freezing overnight when the temp dropped as low as -8°c.
I'd say this is a very viable option and easily doable with the tools we currently have.

**Comment by vivi00790** [comment]
@Crunchepillar  Thanks for the simple and beautiful solution. Can't wait to try it out. I hope it also apply on regular containers like trunk.
Tough this option is pretty good, I hope it could be more realistic like reduced storage (thick insulation layer) or more weight.
Maybe I should make my own mod. Could you kindly provide the modding tool you mentioned?

**Comment by Crunchepillar** [comment]
I didn't actually use any specific tools to make that mod, I just edited the JSONs with notepad. If you don't wanna make your own mod, here's the example I used in the screenshot above but edited to be a little more balanced, since I wanted to use it in my own worlds. The recipes are auto-learned at tailoring 2 and fabrication 2 and use 12 nomex patches to make a nomex sheet and then wrap that around a steel jerrycan with some duct tape or strings to make a 20L insulated tank with insulation rating 2 (since I thought having the same insulation as the freezer from just wrapping a tank with nomex was a bit powerful)

[CatFDA.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3006651/CatFDA.zip)

If you don't like the recipes or other values just edit them as you see fit, the mod structure is really simple 😆

**Comment by vivi00790** [comment]
Actually I do want to make my own mod, but I have little knowledge about modding CDDA.
Are there any document or tutorial?

**Comment by adamkad1** [comment]
just take a look at existing mods and try to reproduce them. making json mods is awfully easy

**Comment by PaulBlay** [comment]
Not asking for a re-open, but I would note that heat tapes for pipes https://www.amazon.com/Easy-Heat-AHB-019-Weather-Heating/dp/B00002N6MB and under-tank heat pads https://www.amazon.co.uk/Upgrade-Version-Facon-Automatic-Thermostat/dp/B077VLB1KK are things that people going winter camping or leaving RV outside in winter for some time can use.
