### ISSUE TITLE
Digging pits creates too much soil

### ISSUE THREAD

**Issue by Crunchepillar** [CleverRaven/Cataclysm-DDA#29066]
**Describe the bug**  
Digging a pit creates almost 2,000L worth of soil and additionally small amounts of rock, clay, sand, etc
-edit-
Turns out some of the soil was sorted into my parts pile so actually I had a total of 2,230L of soil with negligible amounts of the other materials. 😨 

**To Reproduce**  
1. Dig Pit
2. Notice there is so much volume of created material that it can't even fit inside two game tiles (over 2,000L total material)

**Expected behavior**  
I don't know how deep a pit is but there is absolutely no way that digging down a bit in one tile creates more material than can be stored in two tiles.

**Screenshots**  
![image](https://user-images.githubusercontent.com/4098225/55125067-89679080-50d6-11e9-96b5-e7514b96a119.png)
This is just the soil and pebbles, I've got clay, sand and rocks on a third tile nearby

**Versions and configuration(please complete the following information):**
 - OS: Win10
 - Game Version: 0.D-1063-g7d75fdf (tiles)
 - Graphics version: Tiles
 - Mods loaded: 
  "dda",
  "no_npc_food",
  "filthy_morale",
  "makeshift",
  "More_Survival_Tools",
  "alt_map_key",
  "Urban_Development",
  "DP_XOTTO_INDICATORS",
  "more_classes_scenarios",
  "cars_to_wrecks"

**Additional context**  
🍇

**Comment by ralreegorganon** [comment]
Digging producing excavated material is something I just added. The quantities are a bit hand-wavey but I’ve documented my assumptions [here](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/iuse.cpp#L2495). Please give that a read and double-check my math and suggest what element should be changed.

For clarification, I’m pretty sure you’ve dug a deep pit after digging a shallow pit, right?

**Comment by Crunchepillar** [comment]
If the pit doesn't penetrate down to the next Z level then regardless of your assumptions it can't possibly produce more material than needed to fill a single tile with soil. If the pit is less in size than 1x1x1 tile then how can more material be excavated than can fit in 2 full tiles?

Naturally, I'm assuming the 1000L limit on each tile is representative of how much volume can fit in the game world's 1x1x1 space, but doesn't that logic check out?

**Comment by ralreegorganon** [comment]
> If the pit doesn't penetrate down to the next Z level then regardless of your assumptions it can't possibly produce more material than needed to fill a single tile with soil. If the pit is less in size than 1x1x1 tile then how can more material be excavated than can fit in 2 full tiles?

The horizontal and vertical coordinate systems are not the same. Part of the difficulty of this discussion is, as I noted in the comment, the size of tiles are not rigidly defined anywhere. That being said, 1m x 1m has been a not-uncommon assumption for the horizontal distances, but a z-level being 1m makes no sense. I believe the vehicle code assumes a z-level is 4m, for example.

> Naturally, I'm assuming the 1000L limit on each tile is representative of how much volume can fit in the game world's 1x1x1 space, but doesn't that logic check out?

Not quite. The maximum volume of a terrain/furniture is defined on a per-terrain/furniture basis and can be greater or less than 1000L. Most just don't define it, and thus have a default value of 1000L.

> Also I'd like to point out that I have read through your massive comment and I respect the heck out of how much thought you put into it but I think we gotta scale back the soil volume.

Can you elaborate on what the specific problem is though? For example, is it that you find it inconvenient that the items exist? That you have so much and nothing to do with it yet? Just the principle of the thing? Something else?

My primary goal here was to provide access to some resources (clay, sand, rocks, pebbles) that I thought should be trivially available in small amounts provide the right tools were on hand--the soil just comes along for the ride, and doesn't necessarily have a use yet but that doesn't mean that it won't get used to fill in pits, in constructions, in planting, or any other relevant use as those features are expanded/updated.

> For reference: I just dug out 7 full tiles with a jackhammer and the game gave me 22L worth of limestone and rocks, how does getting 100 times that volume in soil when just digging out a pit make sense?

I think the actual issue is that you've demolished 7 tiles and ONLY gotten 22L of materials. If we just go by your estimate that a tile is 1m x 1m x 1m, then you've demolished 7 m^3 or 7000 liters of solid rock and only gotten enough material to fill one of these buckets plus a little extra:

![image](https://user-images.githubusercontent.com/11464/55128299-ed368d00-50c7-11e9-9a22-bb4f2b96bd83.png)

The ability to adjust those sorts of numbers to be something more representative is part of the goal of the change that introduced the byproducts for digging.

**Comment by Crunchepillar** [comment]
When I say "1x1x1" I'm just saying one tile or one unit or whatever. If we end up increasing the amount of mats dropped from digging out other sources to match your assumptions then that's okay. What bothered me enough to make this issue was that it was so wildly inconsistent with how much stuff you get from doing anything else.

As you have pointed out it is established that mining produces very little and recipes involving limestone, et al are basically tuned around that. I consider myself a bit of a hoarder and I've never once filled an empty tile to its maximum 1000L capacity and its very jarring to be given almost 2300L of soil which as far as I can tell is a junk item right now. Additionally, I only dug this pit in the first place to build and reinforce a junk metal barricade, a fixture that spans and protects the entire tile but only requires a pit and resources that take up less than 100L. How did I make use of that huge volume of pit space with so few materials going into construction? I don't know anything about the realism of digging a pit or how deep the pits are in game (and clearly you science-d this thing up something fierce) but I *do* know that none of my experiences with digging waste material from this update have matched my expectations in terms of pre-established game mechanics. I really think looking at the mining we see that realism was eschewed in favor of just having more manageable amounts of stuff. If we want excavations to include waste material handling and disposal as game mechanic then lets go for it, lets go deep on that and include chaff rock and tailings when mining in a future where handling large volumes of waste isn't a chore, but right now soil has no use, takes up tons of space and is very inconsistent with the volume of materials moved in other operations.

My final opinion is, if you're set on dumping literal tons of soil on me then you had better include something to do with it soon. I'd suggest flower beds to spice up greenhouses, a plant food and soil mix as an easier to make but lighter fertilizer, mud bricks reinforced with straw or withered plants and baked at a kiln for cheaper construction. 😸

**Comment by kevingranade** [comment]
As pointed out, the deep pit is assumed to have a volume of 1x1x2m, which means 2,000 L of stuff coming out of it is if anything under-representative (that stuff expands a LOT when it's broken up).

I'm totally fine with some follow up issues or PRs making suggestions for other parts of the game where the materials produced should be different, but presently this is more correct than other parts of the game, not less.

> My final opinion is, if you're set on dumping literal tons of soil on me then you had better include something to do with it soon.

You know, this was pretty much fine until you said this.  You might not realize it, but "you had better" is incredibly rude, stop it.

**Comment by Crunchepillar** [comment]
I think you read some tone into my words that was not meant to be there. The phrase was meant to highlight how out of place it feels to have so much of a resource with nothing to do with it not as "You gotta do what I say". I feel like the inclusion of the cat smiling emoji should have helped with conveying the tone of that section of my response.

I'm sorry if @ralreegorganon read it that way, too, because I certainly didn't mean it that way.

**Comment by Shibimon** [comment]
Aside from other numerous uses the "soil" could and should have, i think it could be used to "fill pit" as right now you can fill a pit with tin air and dig it again for even more useless soil.
"This mixture of sand, silt and clay is ideal for growing plants" leads to think you could somehow transform it or pull apart into sand, silt and/or clay, and some use for plants too.
