### ISSUE TITLE
NPC's First Aid use

### ISSUE THREAD

**Issue by scanevaro** [CleverRaven/Cataclysm-DDA#29311]
**Bug/Issue**
+ The thresholds for bandaging is about less than 15 HP remaining on limbs for NPCs. 
+ NPC bandaging doesn't work well with the new delayed bandage system. 
+ And though they have code to bandage the player, they don't have a way to detect that the player is in need of bandaging.

**To Reproduce**  
1. NPC get's limb with less than 15 HP.
2. Give Bandage to NPC.
3. See if it's being used.

**Expected behavior**  
+ Make the threshold number for bandaging settable on a conversation/dialog. 
+ Be able to set when the NPC should stop to bandage/first aid himself and player.
   - Detect when player is in need of First Aid.

**Comment by kevingranade** [comment]
Micromanaging NPCs is never the answer, especially having the player poke around in AI settings.
It should be sufficient to just adjust the threshold to something more reasonable if the bandages work properly once applied.

Bandaging the player is a different and more complex issue, should the npc forcibly halt the player to bandage them, does the player have to actively wait for the action to be done? Etc.

**Comment by adamdeno** [comment]
Yes , Here is what i got.

this is one of the NPCs hurt.
![8x1](https://user-images.githubusercontent.com/41305926/55666786-e3452480-5853-11e9-8250-60b15cf03b8a.PNG)

i have a bandage so i tried making him "Hold" it
![8x2](https://user-images.githubusercontent.com/41305926/55666800-f8ba4e80-5853-11e9-89fd-cc77d3cfe111.PNG)

Yet nothing happens its in his backpack and he isnt using it.
![8x3](https://user-images.githubusercontent.com/41305926/55666811-1f788500-5854-11e9-8a10-ae302b383855.PNG)

i tried making him "Use" it but he thinks its a melee so he refuses and says his weapon is better.

**Comment by mlangsdorf** [comment]
There's a whole mess of bugs here:
1.  Thresholds for healing are 15 HP or less on the limbs, 25 or less on the torso, and 35 or less on the head.  Those should be changed to percentage rather than absolute values.
2.  NPCs have an AI action for healing the player, but no way of assessing the player's wounds.
3.  NPCs don't know about the new bandaging system and will repeatedly bandage the same badly wounded limb.
4.  NPCs don't know how to use disinfectant.
5.  NPCs don't know how to use the player activity to perform bandaging.

Proposed solutions (not in order, just things we need to do)
1. Move to a percentage based threshold that takes into account the NPC's first aid skill, altruism, and bravery - altruistic NPCs heal others earlier and themselves later, brave NPCs require more damage before healing anyone, skilled NPCs wait longer to maximize benefits of their skills.
2.  Teach NPCs to recognize bandaged limbs and not re-apply bandages.
3.  Teach NPCs to use disinfectant.
4.  Teach NPCs to use the bandaging player activity, now that NPC use of player activity is supported.
5.  As part of that, rewrite the bandaging player activity to be NPC friendly and including pathing support.
6.  Add conversation options to control NPC bandaging - "we've got lots of bandages, use them freely" versus "we're running low, make them count."
7.  Allow NPCs to heal each other.

**Comment by l29ah** [comment]
The conversation option would be nice. My NPC got `Left Leg |\...` and `first aid 5`, but doesn't want to bandage himself, and this is really messed up.
