### ISSUE TITLE
New satiety mechanic needs fixing

### ISSUE THREAD

**Issue by Tharn** [CleverRaven/Cataclysm-DDA#29430]
**Describe the bug**  
A character with no hunger or thirst status, i.e. neutral.
I give him a couple of deluxe beans & rice - nothing happens.
I give him clean water like 6 or 7 times - suddenly he is sated.
I hit the wait button. The 'sated' status keeps flicking on and off every other turn.
I give him some more solid food - the 'sated' status disappears.

Is this just working on a delay, or what's going on?

**Versions and configuration(please complete the following information):**
 - OS: Win 8.1 x64
 - Game Version: 8746
 - Graphics version: Tiles

**Comment by Hatfish** [comment]
I had a similar issue, I tried to drink from a puddle and ended up drinking about 50 units of water without any change in my actual thirst (judging by the movement debuff in the stats page), but a very confused status window that couldn't tell whether I had ate a lot or drank a lot.

**Comment by Tharn** [comment]
Even if it worked without issue, separating satiety from kcal only makes this mechanic more opaque. A solution in search of a problem. But that's just my opinion.

**Comment by TheMurderUnicorn** [comment]
I don't hate the concept, but I'm running into similar issues.  My character no longer prompts me for overeating (because they don't even know they're full) and the sated/hydrated flags keep blinking in and out of existence.  My character goes from 'very hungry' to no status (as though I'm not hungry) and then suddenly becomes very hungry a few minutes later.  

Also, though I get the concept, my character shouldn't be able to drink water 11+ times without my status changing or at least telling me that I'm drinking too much.

**Comment by pjf** [comment]
Linking in #28049 as the relevant pull-request here.

My main feedback from having played with the new mechanics is that drinking/quenching feels like it should have an instant effect. I ended up drinking 1.5 litres of water because my thirsty flag wouldn't clear, only to feel turgid a few turns later.

**Comment by SkuliAdams** [comment]
I have seen a similar blinking effect with fullness. After I ate some food while neutral, my character became full. But full would be removed, then return, then be gone again as I waited.

**Comment by KorGgenT** [comment]
current plan is make water more immediate, but leave hunger alone for a while longer.

**Comment by Xpyder** [comment]
With this new hunger mechanic, we should have some way to check our weight to make sure we're not too skinny or fat

**Comment by KorGgenT** [comment]
fatness isn't implemented yet. you'll see a speed negative in the @ menu for starvation for now.

**Comment by Xpyder** [comment]
ok, can you still die of starvation?

**Comment by pjf** [comment]
Reporting in that 'consuming' bandages¹ makes my hunger go away. I know my character's first aid skill is low, so they might just be *really* confused as to how to treat a stomach wound.

—

¹ Or at least boiled, makeshift bandages

**Comment by Tatterdemalian** [comment]
Not sure when/why this was changed, but this is quickly turning into another "vitamin deficiency" imbroglio that can't be solved with the Simplified Nutrition patch. Maybe a new "Simplified Satiety" patch is in order?

**Comment by l29ah** [comment]
I'm starting to like this change, since now i can stockpile a lot more food and water in my body :]
