### ISSUE TITLE
Cordless Drill (UPS) does not consume charges when installing Tree Spile (PR 8752)

### ISSUE THREAD

**Issue by evankimori** [CleverRaven/Cataclysm-DDA#29447]
**Describe the bug**  
UPS modded Cordless Drill does not consume (battery/electrical) charges when installing Tree Spile onto trees.

**To Reproduce**  
UPS mod a Cordless Drill, fully charge the item and install a Tree Spile. No charges are consumed from storage.

**Versions and configuration(please complete the following information):**
Currently does not consume charges on PR 8752.

**Comment by Fris0uman** [comment]
So cordless drill never uses charges when used in construction, because it already has the drilling quality when turned off It's mentioned in this issue  : [#26534](https://github.com/CleverRaven/Cataclysm-DDA/issues/26534)

I tried to fix it, but the drill also has screwing quality and if you make a tool with scewing quality active it will spam you with a prompt to rmove tool mod every turn.
 [Failde attempt at a fix](https://github.com/CleverRaven/Cataclysm-DDA/pull/27375)

**Comment by int-ua** [comment]
Closing in favor of #39246
