### ISSUE TITLE
Ash is immensely dense

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#29632]
**Describe the bug**  
100000kg/m³, five times denser than plutonium or as dense as the Sun core // https://en.wikipedia.org/wiki/Density#Densities

**Expected behavior**  
700kg/m³

**Versions and configuration(please complete the following information):**
0.D-1798-gf078e2d44a-dirty

**Comment by AlexanderUldall** [comment]
I took the information from **chemicals_and_resources.json** for both **chem_sulphur** and **ash** in order to compare the to items densities.

``` 
"type": "AMMO",  
"id": "chem_sulphur",
"volume": 1,
"weight": 5,
"count": 100
"//": "NOTE: Weights are given for ONE UNIT.  The actual weight of a spawned pile of sulfur is
 now 5*100 = 500g.  For reference, 1 C:DDA unit of volume is around a quarter of a liter
 (calculated from the weight of water).",
``` 

Which gives a density of 0.5kg / 0.00025 m^3= **2000 kg/m^3** which matches wikipedias density of 2g/cm^3.

``` 
"type": "AMMO",
"id": "ash",
"volume": 0.1,
"weight": 1,
"count": 100
``` 

Which gives a density of  0.1kg / 0.000025m^3  = **4000 kg/m^3** which is around **5.7** times higher than the proposed **700kg/m^3**.

This would mean the weight should be something more like **0.175**. 

Is **700 kg / m^3** what we are aiming for?

**Comment by l29ah** [comment]
Now wood ash is absolutely weightless.
