### ISSUE TITLE
Lamp oil isn't craftable from "rotten" fat.

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#29770]
**Describe the bug**  
Lamp oil isn't craftable from "rotten" fat.

**To Reproduce**  
Have rotten fat or rotten tainted fat.
Be unable to make rotten tallow or rotten tainted tallow.
Be thus unable to make lamp oil

**Expected behavior**  
"Rotten" (actually just rancid, as fat doesn't actually rot) chunks of fat should be able to be converted to tallow for use in non-food applications, as lamp oil is a real-life solution for using up rancid oils.

**Comment by pjf** [comment]
I'm not quite so sure how I feel about this from a balance standpoint. Fat going bad means that the player has to make a choice as to when to harvest and render it in a timely fashion versus doing other things with their time. This is especially the case with tainted fat, which goes bad extremely quickly, and thus is more a desperation fuel.

Having lamp oil craftable from rotten fat would greatly increase the amount of oil available in the game, without adding any interesting gameplay mechanics or choices. I'm not sure that's unbalanced as it currently is, especially since it's possible to render fat into tallow and lard which have significantly longer shelf-lives.

**Comment by MrHrulgin** [comment]
From a simulationist perspective: fat doesn't rot, and would continue to be good for oil IRL.
From a gameplay perspective: this is the main route to making diesel, as other sources of fat are *very* limited. Given the new and incoming limitations on repairing/maintaining batteries and solar panels, diesel will become a more important source of late-game transportation.
From an enjoyment perspective: At the moment, if you kill 10 zombies and immediately spend the day full butchering them all, the fat will be "rotten" and unusable before you're done. Is it really more enjoyable to lure one zombie at a time to butcher in order to harvest and render their fat before finding another single zombie to repeat the process?

**Comment by echomirage1** [comment]
Recycled household cooking oil is one of the main ingredients of biodiesel. In the more advanced selective waste disposal systems the rancid cooking oil is dumped separately. Fat going rancid without refrigeration in a day or two is fine, but you should be able to make fuel out of it.

**Comment by kevingranade** [comment]
The project stance on realism vs balance is that there are plenty of places to inject balance without negatively impacting realism.
In other words, if rancid fat is usable to craft lamp/fuel oil IRL, then it should be usable to do so in game, if this causes a problem, we can find elsewhere to apply balance.

E.g. theres nothing that says fat reserves survive zombification intact and in a usable state. If zombie fat is a problem it can simply be eliminated.

**Comment by pjf** [comment]
@kevingranade : Thank you so much for the clarification!

@MrHrulgin : Your wish is granted! (Pending successful review and merge.)

Pull request allowing rendering of lamp oil from (rotten) and tainted fat: #29808.
