### ISSUE TITLE
Unloading gun you're wielding when you have nowhere to store its ammo leads to an error

### ISSUE THREAD

**Issue by drayath** [CleverRaven/Cataclysm-DDA#29839]
**Describe the bug**  
Unloading gun gave error then put a None item into player inventory.
With None item in inventory: Advanced inventory: Player Inventory->Vehicle Inventory: 'Move All' action crashed game.

**To Reproduce**  
Complete the 3rd? mission for the old guard rep in the refugee center
Get rewarded with Marshall badge and gun (plus other stuff)
My gun contained a single round of ammo (don't know if this is random)
Unload the gun.

**Versions and configuration(please complete the following information):

Version: 0.D-2038-g49c568e705 (Windows 10-64 Tiles - Custom build with VS2015 but with no code changes)
Mods: [ "dda", "aftershock", "filthy_morale", "no_npc_food", "growable-pots", "makeshift", "Medieval_Stuff", "More_Survival_Tools", "modular_turrets", "Salvaged_Robots", "mutant_npcs", "more_locations", "FujiStruct", "Urban_Development", "deoxymod", "blazemod", "Tanks", "no_flaming_weapons" ]

This is the only error in the debug log, not sure if it is related: ERROR : ..\src\player.cpp:8434 [item_reload_cost] cannot determine reload cost as none is neither ammo or magazine

**Expected Behavior**
Unloading should not give none item.
Should None be in inventory (as some sort of emergency placeholder) Interacting it should not cause crash

**Comment by Night-Pryanik** [comment]
Confirmed on latest experimental as of April 10, 2021.
This happens when you have nowhere to store the ammo and try to unload the gun you're wielding.

1. Get naked.
2. Get Ruger Redhawk with 6 ammo and wield it.
3. Try to reload the gun.
4. Game asks "Stop wielding Ruger Redhawk?"
5. If you select the only available option "Drop item", the error `Tried removing item from object which did not contain it` pops up. This also leads to 6 .44 Magnum ammo created from the air as Redhawk remains fully loaded.
