### ISSUE TITLE
Separate buttons for crouching and running 

### ISSUE THREAD

**Issue by Yunatan** [CleverRaven/Cataclysm-DDA#29894]
**Is your feature request related to a problem? Please describe.**  
It is a bit frustrating to have to scroll through all the moving options using single button.

**Describe the solution you'd like**  
Activating different moving options should work more like a toggle. 
If there is danger, I want to start running. When it's okay, I don't want to run anymore. I don't want to start crouching when I stop running, I want to go back to my previous mode. 

**Describe alternatives you've considered**  
Implement a popup to choose a desired moving option, similar to martial styles.

**Additional context**  
Given that in the future there could be more moving options, I think we need to make this user-friendly now.

**Comment by esotericist** [comment]
There's probably going to continue to be a primary "cycle movement mode key" no matter how we approach this, and simply adding a bunch of discrete toggles has a lot of problems if we eventually have, say, five or six movement modes. 

Keybinding options are at a premium at this point in the game's development, especially for defaults, but even custom bindings for players only have so much wiggle room (since they're still going to need to have access to all the game's critical functions).

Addressing this properly will take some consideration.

**Comment by Yunatan** [comment]
If we are going to consider different options, I'll just put borrowing DF mechanics on the table:

![image](https://user-images.githubusercontent.com/6611291/56678637-db96d400-66cb-11e9-9b5a-d62a748b2ab4.png)

**Comment by SomeDeadGuy** [comment]
Yes, 100% yes!
This crouching mechanic ruined many of my escape attempts. I just keep forgetting what i am crouching, and not walking all the time. When i need the crouch, i will use crouch, i do not need it most of the time i play the game.
Run/walk cycle on one button, croucing/standing on the other. Like in any other good game in existence.

**Comment by kevingranade** [comment]
I'm fine with the suggestion by @eso to add default-unbound keys to have more limited toggles, but I have no interest in spending more default keys on it, especially as we intend to add even more movement modes in the future.
