### ISSUE TITLE
Revise and Balance Workbench stats

### ISSUE THREAD

**Issue by ifreund** [CleverRaven/Cataclysm-DDA#29925]
**Describe the bug**  
Workbenches currently have very hand-wavy stats, which are in general way higher than they probably should be.  This includes the fake workbench items holding stats for crafting in the hands and crafting on the ground.

**Expected behavior**  
The stats for a workbench are:
- `multiplier`: this is a simple multiplier on crafting speed
- `mass`: this is the maximum allow mass before crafting speed starts to fall off
- `volume`:this is the maximum allow volume before crafting speed starts to fall off

What I want to see:
- Lowered `mass` and `volume` for `f_fake_bench_hands`
- Maybe lower `multiplier` and raise `mass`/`volume` for `f_fake_bench_ground`
- Find some kind of pseudo math way to calculate a more realistic `mass` and `volume` for all workbenches
- Examine the multipliers to make sure they make sense ( I think they are fairly reasonable already )

Current stats for (fake) furniture:

type | multiplier | mass | volume
--- | --- | --- | ---
`f_fake_bench_hands` | 1.0 | 30kg | 30L
`f_fake_bench_ground` | 0.75 | 50kg | 100L
`f_desk` | 1.0 | 100kg | 100L
`f_table` | 1.0 | 100kg | 100L
`f_counter` | 1.0 | 100kg | 100L
`f_lab_bench` | 1.1 | 150kg | 150L
`f_workbench` | 1.2 | 250kg | 250L

Current stats for vehicles:

type | multiplier | mass | volume
--- | --- | --- | ---
`veh_table` | 1.0 | 80kg | 80L
`veh_table_wood` | 1.0 | 80kg | 80L
`workbench` | 1.2 | 150kg | 150L

Important note about vehicles:
The maximum volume of tables is 3.75L and 5.0L for workbenches.  I didn't realize this when making these initial values and as such they definitely need revision.  I do think that the volume limits should be quite low for vehicles from a realism perspective, as doing serious work inside a cramped vehicle shouldn't really be possible. 

EDIT:

Proposed Changes:

Furniture benches:

type | multiplier | mass | volume
--- | --- | --- | ---
`f_fake_bench_hands` | 1.0 | 30kg -> 5kg | 30L -> 10L
`f_fake_bench_ground` | 0.75 -> 0.70 | 50kg -> ∞ | 100L -> ∞
`f_desk` | 1.0 -> 1.1 | 100kg | 100L -> 75L
`f_table` | 1.0 -> 1.1 | 100kg | 100L -> 75L
`f_counter` | 1.0 -> 1.1 | 100kg | 100L -> 75L
`f_lab_bench` | 1.1 -> 1.15 | 150kg | 150L -> 100L
`f_workbench` | 1.2 | 250kg | 250L -> 125L

Vehicle benches:

type | multiplier | mass | volume
--- | --- | --- | ---
`veh_table` | 1.0 -> 1.1 | 80kg -> 100kg | 80L -> 20L
`veh_table_wood` | 1.0 -> 1.1 | 80kg -> 100kg | 80L -> 20L
`workbench` | 1.2 | 150kg -> 200kg | 150L -> 30L

The vehicle parts would also be updated to hold more than the specified volumes for workbench stats.

Note that these are still very hand-wavy numbers, and I'm not too happy about that, but I think these proposed changes would bring workbench stats much more in line with reality.

**Comment by esotericist** [comment]
I'm of the opinion that tables/desks should have *some* small multiplier benefit, because right now people are reaching the conclusion that until they can make the higher tier workbenches, there's no point in not just doing work out of your hands, since they have the same multiplier. 

The mass and volume limits in theory affect that a bit, but I'm not sure how much that actually matters (especially if someone has a Lifting device nearby so that the task is weightless while wielded).

**Comment by eliotcougar** [comment]
The problem I had when crafting minifridge and minifreezer was that the virtual "crafting in progress" item (that has volume and weight as the sum of weights and volumes of all components was very high... It was above 150L if I recall correctly, mostly due to lots of steel plates, and huge condenser and heater components... In the end, "crafting in progress" is much heavier and bigger, then the resulting minifridge or minifreezer...

**Comment by Yunatan** [comment]
> I do think that the volume limits should be quite low for vehicles from a realism perspective, as doing serious work inside a cramped vehicle should really be possible.

How about doing some serious work inside a luxury deathmobile? 
Seriously though, you probably shouldn't punish some particular play styles. Maybe add a good vehicle workbench that is harder to craft than a good regular workbench?

**Comment by Yunatan** [comment]
> The problem I had when crafting minifridge and minifreezer was that the volume of the virtual "crafting in progress" item (that has volume and weight as the sum of weights and volumes of all components) was very high... It was above 150L if I recall correctly, mostly due to lots of steel plates, and huge condenser and heater components... In the end, "crafting in progress" is much heavier and bigger, then the resulting minifridge or minifreezer...

I can imagine disassembled fridge taking up a lot more space that assembled one, but it definitely shouldn't be heavier.

**Comment by Tharn** [comment]
Even kitchen units in regular RVs have plenty of volume of free space on top of counters. Otherwise they would be unusable. We're talking hundreds of litres worth. You don't put these in sports cars. You put them in RVs, repurposed fire engines, trucks and deathmobiles.

The argument that vehicles always have to be cramped is flawed. Please give vehicle workbenches the intended volume. And fix the low values for tables etc. while you're at it. A 4 litres maximum for a RV table unit is almost nothing. This is the number that should be fixed, not the other way around.

https://www.rv-insight.com/images/rv-kitchen-600.jpg

**Comment by ifreund** [comment]
Ok, here are my proposed changes:

Furniture benches:

type | multiplier | mass | volume
--- | --- | --- | ---
`f_fake_bench_hands` | 1.0 | 30kg -> 5kg | 30L -> 10L
`f_fake_bench_ground` | 0.75 -> 0.70 | 50kg -> ∞ | 100L -> ∞
`f_desk` | 1.0 -> 1.1 | 100kg | 100L -> 75L
`f_table` | 1.0 -> 1.1 | 100kg | 100L -> 75L
`f_counter` | 1.0 -> 1.1 | 100kg | 100L -> 75L
`f_lab_bench` | 1.1 -> 1.15 | 150kg | 150L -> 100L
`f_workbench` | 1.2 | 250kg | 250L -> 125L

Vehicle benches:

type | multiplier | mass | volume
--- | --- | --- | ---
`veh_table` | 1.0 -> 1.1 | 80kg -> 100kg | 80L -> 20L
`veh_table_wood` | 1.0 -> 1.1 | 80kg -> 100kg | 80L -> 20L
`workbench` | 1.2 | 150kg -> 200kg | 150L -> 30L

The vehicle parts would also be updated to hold the specified volumes.

Note that these are still very hand-wavy numbers, and I'm not too happy about that, but I think these proposed changes would bring workbench stats much more in line with reality.

**Comment by l29ah** [comment]
It would be nice if the crafting interface would suggest the optimal place for the given task since at some point ground outperforms everything else.

**Comment by l29ah** [comment]
With a 5L workbench i cannot continue crafting anything big on it and have to use my hands instead :<

**Comment by MrHrulgin** [comment]
I disagree with the reduction of vehicle bench volume. With the changes you've proposed, taking a workbench that you had as a construction will suddenly lose 95L of workable volume if attached to a single frame.

**Comment by Scischm** [comment]
> Purpose of change
 Provide a way to work on **_very large/heavy_** in progress crafts.
 Provide a convenient place to store **_long term crafts_** and return to them later.
 Provide a small crafting bonus for a good crafting environment.

```
add_msg_if_player( m_bad, _( "The %s is too large and/or heavy to work on.  You may want to"
                                     " use a workbench or a smaller batch size" ), craft.tname() );
```

That face when I can't craft a single 200L drum on the largest available workbench with the proposed changes, let alone a batch.

The above code implies that crafting on a bench is better than with your hands for large crafts.

With 2 mechanics skill, a welder & goggles, and a steel frame you can make a forklift to work with crafts in your hands for up to 3000kg and ∞ volume, all in the same space that the workbench would go. It doesn't really matter at that point if you get a 20% craft speed bonus if the things you are trying to craft (large and long term items) are better handled with a lifting tool in your hands than on the ground or with the best available workbench because they don't fit on it.

Can only fit two cargo carriers, or livestock carriers, two heavy duty frames, one 100L barrel, can't fit 200L barrel, can't fit a reinforced caterpillar track on it (this ones a mod but still). 

Granted these are some of the few niche cases where it can happen and most crafts get along with the restrictions ok, but I'm thinking in the future for things like building car engines. Workbenches would be especially helpful if they are decided to take days to craft just one.

I mean hell, one of these  

![image](https://user-images.githubusercontent.com/49844315/57176904-07345f80-6e2c-11e9-8e81-ee00971d53eb.png)
 
can take up to roughly 317kg in stress tests. If a folding plastic table can hold that much, I would expect a full size metal workbench to be able to take more.

I think that a workbench would work well to provide a bonus in a small range around it for crafting since you have access to tools, organization, putting pieces of the craft on the table etc. Realistically you'd be moving around grabbing different things while crafting instead of just staring at a bundle of stuff.

It could also potentially recognize multiple workbench tiles placed next to one another and combine the volume if you are worried about the bench having too much storage in one tile.

If I'm misunderstanding how the benches work that is my bad. I'm under the impression that you only gain the bonus if you are currently crafting an item sitting on the table. 

I guess personally when I heard about workbenches I got excited at the idea of "throw all your crafts on it for a place to hold them and work on it when you feel like it, possibly even getting a small speed bonus for taking the time to make and setup one".

I had a biased image in my head of industrial workbenches 
![image](https://user-images.githubusercontent.com/49844315/57177055-13b9b780-6e2e-11e9-9728-8495d4a41db4.png)

There's nothing wrong with limiting the benches size, but I guess there also isn't anything wrong with erring on the side of lenience with it. Crafting already requires you to have the materials, skills, time, tools, and food/water/sleep to complete and makes up a rather large part of the game for most players. If you've got more than enough materials to justify a big work area might as well let them save some time.

Just something to think about. 

The crafting overhaul is going well so far and I appreciate the changes. First time I saw "in progress" crafts coming off an older build I about pissed myself with excitement.

**Comment by eliotcougar** [comment]
Here's an idea:
When checking if the items fit in the workbench, first check the NUMBER of items of the type "craft in progress", let 1 or 2 biggest crafts in progress fit, ignoring the size... Then for the rest of the "crafts in progress" and items of other types, do the regular volume checks to decide if they fit...

This way you will always be able to craft an item of any size, at least one at a time. I imagine that when you work on a big craft, you don't really have to be able to fit ALL the components on your working surface SIMULTANEOUSLY, you put them there when they are needed, so this whole volume limit issue is not an issue...
