### ISSUE TITLE
Allow recipes/deconstruction to specify magazines with a certain number of charges.

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#29947]
**Is your feature request related to a problem? Please describe.**  
With the battery overhaul, the inability for us to specify that recipes require a full battery as a component goes from "minor quirk" to "mild annoyance"

**Describe the solution you'd like**  
Allow recipes that require magazines to specify how many charges that magazine needs, and allow disassembly recipes to contain magazines that are not empty. In short, teach the recipe system how to work with magazines.

**Describe alternatives you've considered**  
As an example, the Go Bag could disassemble into free floating battery charges in addition to the battery magazine, but this is an odd, hacky solution implemented on a case-by-case basis.

**Additional context**  
This fix is non-trivial and would require C++ code, so I didn't tackle it in the battery overhaul.

**Comment by ifreund** [comment]
I think that adding a `FULL_BATTERY` recipe flag rather than allowing specification of magazine charges in the component list would fix this issue, and is far easier to implement.  If that sounds good to you I could do that tonight, it would only take a minute.

Could also do `FULL_MAGAZINE` to be a little more generic, don't really see a reason to limit such a flag to only batteries but please correct me if I'm wrong.

Making the flag work for disassembly as well might be a little trickier, but still easier than implementing arbitrary charge values.  I haven't looked into that yet though.

**Comment by Inglonias** [comment]
Honestly, even full/empty would be an improvement over what we've got now. If you know how to pull that off, I won't stop you.

I can't think of a reason you'd want a full magazine besides a battery, but the more generic, the better.
