### ISSUE TITLE
Reduce turn length to 1 second

### ISSUE THREAD

**Issue by ymber** [CleverRaven/Cataclysm-DDA#30018]
**Problem**
The status quo of 6 second turns effectively gives us days shorter than they should be and makes simple actions take a disproportionately long time compared to long actions. Some situations like spending an hour walking across a small town and 6 second melee attacks are quite jarring.

**Solution**  
The length of a turn should be reduced to 1 second. This would reduce a tick to 10ms, providing good granularity for very short actions.

A lot of the implementation should fall into place if tick/turn conversions are encapsulated. Any json adjustments required across a large number of objects could be automated.

**Additional context**  
This would go well with the 91 day seasons change to set characters actions in a realistic timeframe.

**Comment by Hirmuolio** [comment]
While we are at it we could test even shorter turns than 1 second.

For example driving at high speeds is currently too hard due to very long turn. At 100 km/h you move 162 m in single turn (not sure how many tiles this is). it is completely impossible to do any kind of steering when each action moves you 162 meters.  
1 second turns would move you 27 meters per turn. Still quite long distance.

**Comment by kevingranade** [comment]
To expand on this a little, most actions that occur within a turn will still occur within a turn, and actions with durations of many turns (usually specified as a time duration instead of moves) will take more turns to process.

Making all turns take less than a second would be problematic, because then the number of turns in combat would be too high.  We can look into something else like adjusting turn progression while driving or something that directly addresses driveability.

**Comment by Hirmuolio** [comment]
>Making all turns take less than a second would be problematic, because then the number of turns in combat would be too high. 

I don't see how that would happen. If player kills zombie in 5 attacks the player would see 5 "turns". It wouldn't matter if these 5 actions took 5 or 63 "turns" under the hood.

**Comment by Zireael07** [comment]
The turns in combat are the same as turns everywhere else. If there are six seconds to a turn, there's 10 turns in a minute. If a turn is one second, there are 60 turns in a minute, so combat lasts six times as long (or it's unnaturally quick, felling a Z in five seconds?)

**Comment by Hirmuolio** [comment]
Actions don't need to take one turn. Even now you can have actions that take multiple turns (costs more than 100 moves or the player has penalty and gets less moves per turn).

With one second turns you could just set the action to take six turns to keep the balance same.

**Comment by Zireael07** [comment]
Combat actions taking more than one turn is honestly contrived.

**Comment by Hirmuolio** [comment]
Combat actions taking less than a turn is IMO worse.

I think the rigid concept of turns is not really necessary. Just having moves for tracking when it is your turn and time would be enough.

For example DoomRL https://drl.chaosforge.org/wiki/Time#Fractional_Time

**Comment by kevingranade** [comment]
It's not necessary, but there's a huge difference between, "adjust mapping of action durations" and "throw out entire tactical time tracking system and start over".

In short, if you want to explore that, please do so in another issue.
