### ISSUE TITLE
After rebinding '<' and '>', certain functions stay on those keys

### ISSUE THREAD

**Issue by echomirage1** [CleverRaven/Cataclysm-DDA#30015]
**Describe the bug**  
Rebinding '<' and '>' makes the "descend/ascend stairs" and "change targets" functions use the new binding, but some functions stay on the default keys.

– Changing z-levels on the (m) map
– Flipping through pages of descriptions in the vehicle menu
– Changing tabs in the mod menu at the world generation section

Might be others.

**Expected behavior**  
Ideally these functions would change with rebinding.

Latest version.

**Comment by esotericist** [comment]
So an important thing to understand here is that keybindings are often associated with specific game states, and not necessarily global.

When you're in the rebinding screen, you want to put attention up at the top here:
![image](https://user-images.githubusercontent.com/1569754/56862985-85dd5880-6965-11e9-9e1e-c733587d1c2a.png)

Whatever keybinding you're about to change will be either green (that binding only exists for this screen) or grey (that binding is valid everywhere). When you go to add a keybinding, you can either add it locally or globally.

Additionally, some things might use the same key by default but aren't associated with the same *concept*, so even changing globally will not necessary impact a different concept, especially if it's a concept that only exists in certain game states/screens.

Now for some of your specific examples:
ascend/descend stairs does have conceptual parity with 'up/down' on the overmap, and that's a thing we can look into (especially since both are grey/global bindings).

Scrolling through the part descriptions in the vehicle menu, however, is not conceptually connected to that, so I think expecting it to also change is not necessarily intuitive, and would cause more problems for players who don't expect it than help those who do.

**Comment by echomirage1** [comment]
@esotericist That's fair enough, I understand the concept. My only real problem was the z-level changing on the map, which I could rebind with global rebinding.

I will close this now, thanks for the help.
