### ISSUE TITLE
Batteries migrated from old saves sometimes do not stack.

### ISSUE THREAD

**Issue by drhead** [CleverRaven/Cataclysm-DDA#30029]
**Describe the bug**  
Some batteries from my savegame before the battery overhaul will not stack.  This is likely due to them having different parameters in the save game.  Correct batteries (particularly freshly crafted ones) have a `bday` parameter in the save file.  Badly migrated ones have a `charges` parameter.  They can also be distinguished by how bad batteries gain 120 cents in displayed value per charge in them.

**To Reproduce**  
1. Migrate and old save from before battery overhaul to after the overhaul, probably with some battery tools in your inventory.
2. Unload batteries from the tools and try to stack them with freshly spawned or crafted batteries.

**Expected behavior**  
I would expect the migration code to create batteries that are identical to fresh ones and that stack.

**Versions and configuration:**
 - OS:  Windows 10
 - Game Version: 0.D-2341-g1c62c69
 - Graphics version: Tiles
 - Mods loaded: dda, aftershock, vehicle additions

**Additional Context**
From my investigation, I am pretty sure this is using the same code used to migrate guns to the magazine system, `item::magazine_convert()` at savegame_json.cpp:158 (as the PR for the battery overhaul had no code changes outside of unit tests), and that the batteries have different parameters than magazines (for instance, batteries shouldn't gain value with charge).  The solution would likely to be to create a special case for batteries in the migration code, as well as something to correct existing bugged batteries.

Additionally, the bulk of my battery stash came from unloading tools that were dropped by zombies before updating, and those batteries behave properly, so whatever happens to tools on the ground while migrating seems to work fine.

**Comment by Inglonias** [comment]
I'm not sure I follow what's happening. You're not supposed to be able to unload batteries from their battery cells anymore (unless you've used the migration mod), and my testing showed that tools with batteries already loaded would sprout their default magazines and continue as normal.

**Comment by Teeklin1** [comment]
Was asked from discord to post here the situation I'm seeing.  I have a new world created after the new battery overhaul system was already in place (2 days ago).  In this world I'm seeing batteries that are failing to stack due to differing values (3 of the medium battery cells are stacking with value of $100, but one is not with value of $700).  This is the case for other battery types as well (twenty five of my light battery cells stack with $35 value, but two of them are in a different stack with $155 value).

Weirdly, the ultra-light battery cells I have a stack of 8 and a separate stack of 2 both with the same $15 value but a 3rd stack with a single battery is $75 value.

The dollar value is the only difference I can see in the items that would keep them from being identical and stacking, but the ultra-light batteries having the same value and not stacking is also very weird.
[Zombieland.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3144894/Zombieland.zip)
