### ISSUE TITLE
Game lags with a large number of NPCs in the reality bubble

### ISSUE THREAD

**Issue by chaoticidealism** [CleverRaven/Cataclysm-DDA#30045]
**Describe the bug**  
In the latest experimental build, NPCs make the game lag severely. When I deleted all the items from their inventories via the debug menu, the lag improved but didn't go away. I have also noticed that large numbers of zombies tend to cause more lag than they used to, but it's not nearly as bad as NPCs.

**To Reproduce**  
1. Go to a refugee center. Walk around. Experience lag.

**Expected behavior**  
NPCs shouldn't cause extreme lag.

**Versions and configuration(please complete the following information):**
 - OS: Windows 7
 - Game Version: 0.D-2346-g1acd83c
 - Graphics version: Tiles
 - Mods loaded: DDA, Disable NPC Needs, generic guns, makeshift items, more survival tools, mining, mutant NPCs, mythical martial arts, no flaming weapons, classes and scenarios mod manual bionic installation, safe autodoc, statsthroughskills IV

**Comment by Scischm** [comment]
This is what currently kills the experience of npcs for me. I really enjoy the features being added to npcs, especially faction camps, but the slowdown makes it more beneficial to drive my care out of the reality bubble to sleep, craft etc instead of making use of the facilities that I spent lots of resources on making.

**Comment by Insineer** [comment]
NPC performance is being optimized in #45497

**Comment by Aivean** [comment]
Should be closed by #45497. Please reopen with savefile attached if still reproducible.
