### ISSUE TITLE
New Batteries don't show up in the eat menu with the battery system cbm on.

### ISSUE THREAD

**Issue by Naranar** [CleverRaven/Cataclysm-DDA#30074]
**Describe the bug**  
Unlike the batteries of old the new ones don't show up in the eat menu when using the battery system cbm.

**Expected behavior**  
Batteries should pop up when the battery system cbm is turned on to be eaten for bionic power.

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 8846
 - Graphics version: Tiles

**Comment by Naranar** [comment]
@esotericist

**Comment by Inglonias** [comment]
Try activating the battery system CBM rather than using the eat menu.

If that doesn't work, I'll take a look at this.

Esotericist has been very nice in fixing bugs, but if this is still a problem, it is ultimately my fault.

**Comment by esotericist** [comment]
My initial investigation shows that the fact you can actually consume batteries from the main inventory is actually the result of a bug in logic meant to prevent a character from using e.g. car batteries to recharge their bionic power.

Hilariously, this means that for some unspecified span of time people have been able to use car batteries for Battery System and it looks like nobody realized.

I don't know if there's a sensible way to make the Consume Item menu populate for battery cells and not car batteries (or anything else that holds charge in it), or if that's even desirable. This is one of those bugs that requires answering design questions first, and that's why I stalled in my attempt to fix it.

@Inglonias if you want to take point on this, feel free to ask me for anything if you need data you can't find that you think I might have

**Comment by Inglonias** [comment]
If it was up to me, I would just let people eat the car batteries at this point. If they've been able to already, it doesn't seem that bad to leave it and make it official.

**Comment by xxEntity** [comment]
Instead of "eating" batteries, what if we remove battery system and instead enhance and rename jumper cable cbm to clamp onto the new battery types to draw power off without consuming the freshly drained battery.

**Comment by kevingranade** [comment]
Ideally you'd stash the battery somewhere and it would drain at some rate instead of instantly dropping the charge into your system.

Not a requirement for right now though.

**Comment by Inglonias** [comment]
Alright. I think the short term fix should be to let people eat magazines from the Consume menu and we'll accept the fact that they can drink an entire storage battery instantly for now. Not ideal, but it will keep the battery system CBM from being in its current state.

Longer term, someone will need to redo how the battery system CBM works.

**Comment by drachs** [comment]
It's unfortunate that this CBM is literally intended to have the user consume the batteries.  That seems very weird.  My expectation as a user when I installed it is I would be able to plug a battery in and load/unload myself like any other battery operated device.

**Comment by Inglonias** [comment]
Just a quick update: I've started looking into this, but my time and knowledge of this part of the code is limited right now. But it is next on my to-do list for the game.

**Comment by akhvledi** [comment]
Dunno, if this warrants a new issue, but I've encountered this problem in build 10839. I used the launcher to revert to 10838, and was able to consume batteries as normal.

**Comment by anothersimulacrum** [comment]
Probably #42095, could you make a new issue?
