### ISSUE TITLE
Swimmer zombies cash card occurrence nerf is needed

### ISSUE THREAD

**Issue by eliotcougar** [CleverRaven/Cataclysm-DDA#30179]
**Is your feature request related to a problem? Please describe.**  
Every single swimmer zombie carries a cash card on them... Combined with the fact that swimmer zombies usually come in big groups, and are not especially tough, after defeating them you end up having an easy 2000-4000 dollars in your pocket, that'll basically serve you until the inevitable end of the game in most situations... The risk/reward associated with swimmer zombies is way off...

**Describe the solution you'd like**  
Reduce the chance of swimmer zombies having cash cards on them to the level of regular zombies.

**Comment by Inglonias** [comment]
This is actually a very easy fix to apply. Simply change [this line of code](https://github.com/CleverRaven/Cataclysm-DDA/blob/f2c0b8f217990dffb9d8d0c87dd128f4d171a7d7/data/json/monster_drops.json#L194) from `{ "item": "cash_card", "charges-min": 0, "charges-max": 50000 }` to `{ "item": "cash_card", "charges-min": 0, "charges-max": 50000, "prob": X }` where X is a number between 1 and 99. Doing that changes swimmer zombies to have an X% chance to have a cash card on them instead of 100%.
