### ISSUE TITLE
All guns should have some armor pen

### ISSUE THREAD

**Issue by Zombiemanpig** [CleverRaven/Cataclysm-DDA#30211]
**Describe the bug**  
Pistols have less armor pen than crossbows with wooden bolts.

**To Reproduce**  
Get some random ranged weapons, from crossbows to bows to handguns to rifles to shotguns.

**Expected behavior**  
If you guys want I can link you a video of handguns clearly shooting through a car with enough power to wound a person on the other side (same video also shows shotguns but as expected only slugs went fully through), lets see a crossbolt be able to do that. The recent changes to ranged weapons completely destroyed balance and realism.

ALL GUNS should have some armor pen built in, all GUN AMMO should also have some armor pen built in. I assume armor pen goes though 1 for 1 in defense so 1 would be a nice baseline in all guns with higher power guns having higher. All ammo should have 1 aswell with armor pen ammo having more. 

**Screenshots**  
![image](https://user-images.githubusercontent.com/47362783/57140817-af8fe880-6d86-11e9-9054-ab8dba719afa.png)
![image](https://user-images.githubusercontent.com/47362783/57140836-b880ba00-6d86-11e9-8fea-a046b2b6be2e.png)
![image](https://user-images.githubusercontent.com/47362783/57140846-c0405e80-6d86-11e9-9f33-22591dddce02.png)

**Versions and configuration(please complete the following information):**
Almost most recent version (8897)
Windows 10.
No item mods.

**Additional context**  

Handguns: going through the car no problems
https://www.youtube.com/watch?v=6qXwdBOZzpY

280lb crossbow: Can't even get through the door
https://www.youtube.com/watch?v=GIyuHrsfKhY

**Comment by kevingranade** [comment]
That's not how armor pen works.  Armor pen represents an attack's ability to penetrate armor *that does not contribute to damage*.  Bullets can pierce through things, but they lose energy when they do so, reducing damage delivered.

"Add armor pen to all rounds" isn't happening, closing.

**Comment by Zireael07** [comment]
Is this detailed anywhere? MODDING.md or CONTRIBUTING.md? Otherwise, the confusion is understandable...

**Comment by Zombiemanpig** [comment]
> That's not how armor pen works. Armor pen represents an attack's ability to penetrate armor _that does not contribute to damage_. Bullets can pierce through things, but they lose energy when they do so, reducing damage delivered.
> 
> "Add armor pen to all rounds" isn't happening, closing.

I still don't understand how wooden bolts have higher armor pen than lead bullets; Wood v lead which one penetrates armor better. 

Can you please explain how wood is better that penetrating armor that does not contribute to damage than lead is?

Ever since last week or so pistols are now useless against anything with a bit of armor, zombie soldiers take 3 damage a hit (Good hit!) from something that is supposed to be doing 26.

Can you please explain the math of how the 26 damage turns into 3?

**Comment by esotericist** [comment]
a sharpened projectile is going to be better at piercing through a resisting surface better than an unsharpened lump of metal is.

the crossbow bolt here gets gets (a very tiny amount of!) armor penetration for that reason. but the bullet in this example has a bit more total damage, so it will, in fact, be better at dealing with most armored targets than the crossbow bolt will, simply by virtue of having more total damage to offer.

The difference that allows standard bullets to penetrate better than crossbow bolts in real life is total kinetic energy. bullets have higher kinetic energy (represented in-game as base damage), and thus can overpower more armor. that armor penetration of 1 means comparatively little with the lower kinetic energy (again represented as lower base damage).

armor itself is a direct subtraction for matching damage types. if you have an attack that does 26 damage, and a target that has 25 armor (such as what a zombie soldier has for cut damage), then your on-paper expected damage is 1. 
armor penetration subtract from the armor rating before it's applied.
this means your crossbow bolt against the same target would reduce the armor to 24...
... but then it's doing 21 damage subtracted by 24, resulting in an on-paper expected damage of 0 (because you can't deal negative damage). 

actual damage can vary a bit due to the small random element, resulting in higher or lower damage than otherwise. sometimes it's small (such as 1 becoming 3), sometimes it's substantial (crits can do much more damage due to having a much higher base value being compared to the armor rating).

**Comment by mlangsdorf** [comment]
Thank you!  That was the explanation I didn't want to write this morning.

Also, there is a plan to balance all ranged weapon damage against each other in a consistent fashion.  darktoes is leading the effort and he likes bows and crossbows, so they are getting attention first.  Everything else will catch up at some point.

**Comment by Zombiemanpig** [comment]
> a sharpened projectile is going to be better at piercing through a resisting surface better than an unsharpened lump of metal is.
> 
> the crossbow bolt here gets gets (a very tiny amount of!) armor penetration for that reason. but the bullet in this example has a bit more total damage, so it will, in fact, be better at dealing with most armored targets than the crossbow bolt will, simply by virtue of having more total damage to offer.
> 
> The difference that allows standard bullets to penetrate better than crossbow bolts in real life is total kinetic energy. bullets have higher kinetic energy (represented in-game as base damage), and thus can overpower more armor. that armor penetration of 1 means comparatively little with the lower kinetic energy (again represented as lower base damage).
> 
> armor itself is a direct subtraction for matching damage types. if you have an attack that does 26 damage, and a target that has 25 armor (such as what a zombie soldier has for cut damage), then your on-paper expected damage is 1.
> armor penetration subtract from the armor rating before it's applied.
> this means your crossbow bolt against the same target would reduce the armor to 24...
> ... but then it's doing 21 damage subtracted by 24, resulting in an on-paper expected damage of 0 (because you can't deal negative damage).
> 
> actual damage can vary a bit due to the small random element, resulting in higher or lower damage than otherwise. sometimes it's small (such as 1 becoming 3), sometimes it's substantial (crits can do much more damage due to having a much higher base value being compared to the armor rating).

25 armor... wow ok.

Do they also get the protection from their worn items?

**Comment by esotericist** [comment]
No. Monsters do not wear equipment. The stuff you get from a zombie actually doesn't exist until the zombie dies, at which point loot spawns. 

The threat level of military zombies is intentionally high for early game characters, by the way, to provide a threat that should be evaded until you can get an excellent weapon. Also, their bash armor is much lower, so they're actually easier to kill in melee than you might expect.

**Comment by darktoes** [comment]
It's worth noting that, based on preliminary calculations, a 9mm JHP round should probably still have ~2 AP. While a decent crossbow with decent bolts should have 3 or 4 (though that's for a basic, low-end crossbow).
That said, I completely agree with the explanation that arrows cut through armor more effectively than most bullets, especially hollow points. A standard broadhead crossbow bolt with the KE of a 9mm would enjoy around 6 AP. Though if a soldier zombie has 25 armor, pretty much all of those AP values are borderline worthless. Damage is still far more useful, and even with current numbers the 9mm comes out on top.
