### ISSUE TITLE
Issues with current state of batteries.

### ISSUE THREAD

**Issue by SirPendrak** [CleverRaven/Cataclysm-DDA#30213]
1. Ultra light battery is 8x times smaller than light battery, despite being only 2x weaker. This not only does not make sense, but also is strange when we look at the recipes. You can make 250ml of acid using only 200ml of ultra light battery cells. Using other batteries it takes 800ml of batteries to get 250 ml of acid. (some scrap metal could be added as byproduct) 

Solution -> make ultra light battery 0,04l instead of 0,01

2. Tools and weapons are getting bigger when being reloaded with battery-magazine. This is mostly notable on weapons like L-stick.
Volume of tools does not increase when instaling battery mod. 

I believe best solution would be making all batteries stored internally, and making battery mods allways increasing items volume by size of new battery type (even when you install mod for smaller batteries on tool using bigger ones by default)

3. Raw "battery" energy has mass and volume. While it made some sense in old system, right now battery cells are heavier when full, and lighter when empty. This applies even to vehicle mounted storrage batteries. 

Solution -> make battery charges weight and volume 0

4. Extreme differences between personal and vehicle batteries/accumulators. 
Medium battery cell (500 power)   0,38L 0,25kg empty
Bike battery (500 power)                1,25L 4kg empty
Small storage battery (500 power) 0,50L 2,5kg empty
I know there were some plans to increase size of vehicle batteries, and consumption of electric engines, this is just a remindeer.

Solution -> make theese proportional, or almost proportional. 

5. UPS moded devices dont seem to work. At least i was not able to use them in any form, be it handheld UPS, UPS CBM, or vehicle CBM station. 

6. In JSON batterry cells have some kind of "rechargeable" flag. Their descrieption does not mention anything about recharging. Make it more clear that you can recharge your batteries in car UPS recharge stations. Is it even real to recharge acidic batteries? Maybe add small, handheld, less efficient accumulators that can be recharged and remove this flag from standard batteries.

7. Energy consumption is off for almost everything. This long topic, but some obvious ones are too low costs to boil, weld and forge almost everything, and too big cost to activate lights, some bionics (like claws or M.blade), etc...

**Comment by esotericist** [comment]
The ups conversion mod needs to be re engineered to work going forward. It is completely non functional right now (and that's a task I have pending)

**Comment by mlangsdorf** [comment]
Making batteries 0 volume will break the vehicles code for complicated but stupid reasons.  It's something we can fix, but it's not as simple as making a change.  Making them 0 mass is fine and probably should be done.

There is currently no plan to change the size of vehicle batteries or the consumption of electric engines.  Those concerns were adequately addressed in #26209 and its follow-ups.

We know that energy costs for heating things are much too low, but no one is volunteering to fix it right now.

**Comment by anothersimulacrum** [comment]
Batteries can't be volume 0 because that breaks electric vehicles. I believe the issue was that batteries are the 'fuel' in storage batteries, and the vehicle fuel consumption depends on volume.

**Comment by Inglonias** [comment]
I'll address all the points, because there are some very good points here.

> Ultra light battery is 8x times smaller than light battery, despite being only 2x weaker. This not only does not make sense, but also is strange when we look at the recipes. You can make 250ml of acid using only 200ml of ultra light battery cells. Using other batteries it takes 800ml of batteries to get 250 ml of acid. (some scrap metal could be added as byproduct)

**Solution:** Numbers were based on educated guesses for battery size and weight. If you have better numbers, feel free to propose them.

> Tools and weapons are getting bigger when being reloaded with battery-magazine. This is mostly notable on weapons like L-stick.

**Solution:** Give battery powered tools a sensible `magazine_well` entry in their JSON and this problem disappears completely.

> Raw "battery" energy has mass and volume. While it made some sense in old system, right now battery cells are heavier when full, and lighter when empty. This applies even to vehicle mounted storrage batteries.

As mlangsdorf said, I actually tried this at some point and managed to break electric vehicles for the purposes of vehicle tests. Until that gets resolved, there's really not much I can do about this. I can change the weight to zero, but not volume.

> Extreme differences between personal and vehicle batteries/accumulators.
Medium battery cell (500 power) 0,38L 0,25kg empty
Bike battery (500 power) 1,25L 4kg empty
Small storage battery (500 power) 0,50L 2,5kg empty
I know there were some plans to increase size of vehicle batteries, and consumption of electric engines, this is just a remindeer.

This is a design issue, not a technical problem. As an open-source project, if you have an idea to fix this, you're free to propose it. This can likely be fixed with nothing but JSON entries.

> UPS moded devices dont seem to work. At least i was not able to use them in any form, be it handheld UPS, UPS CBM, or vehicle CBM station.

Yeah. Turns out that the way UPS modded tools works is fundamentally incompatible with the new system. The UPS modded tools REQUIRE the old battery system to function. Specifically, they rely on the fact that tools have a `max_charges` entry. Unfortunately, putting this entry in with the magazine entry causes weird things to happen. Eso is working on a fix, but from what I understand, this is not a trivial problem. In the meantime, remove UPS mods from tools with a screwdriver.

> In JSON batterry cells have some kind of "rechargeable" flag. Their descrieption does not mention anything about recharging. Make it more clear that you can recharge your batteries in car UPS recharge stations. Is it even real to recharge acidic batteries? Maybe add small, handheld, less efficient accumulators that can be recharged and remove this flag from standard batteries.

This is a design complaint, not necessarily a flaw. It's one I'm open to discussing as well. Having non-rechargeable batteries is entirely possible.

> Energy consumption is off for almost everything. This long topic, but some obvious ones are too low costs to boil, weld and forge almost everything, and too big cost to activate lights, some bionics (like claws or M.blade), etc...

This was known even when I put in the first PR for the new system. I made the decision that overhauling how batteries worked was enough change for one PR and that a balance overhaul would take things overboard. Handheld tools are balanced around having a max of 100 batteries in them, and we've established that a C cell alkaline IRL would be around 40 charges. Electric vehicles are balanced to this, but handheld tools are not.

**Comment by Zireael07** [comment]
I think having all batteries rechargeable is fine, just the description should make it clear they are Li-ion, not acidic.

Handheld tools rebalance was asked for in several places, I noticed. Out of curiosity, would it require C++ or is it merely a JSON change?

**Comment by anothersimulacrum** [comment]
Just JSON - you would need to go through the 'requirements' and some of the recipes, and charge the charges needed for each tool.

**Comment by I-am-Erk** [comment]
As an aside, do you think you might make your issues with less agressive titles than "Everything wrong with ..."? It doesn't exactly foster a friendly conversation environment.

**Comment by SirPendrak** [comment]
> do you think you might make your issues with less agressive titles than 

Sorry if it sounded rude, i am not native english speaker, no bad intentions, i actually like new changes here, just wanted to report bugs. 

> Numbers were based on educated guesses for battery size and weight. If you have better numbers, feel free to propose them. 

I just think that battery capacity should be almost always proportional to its size, unless one type is made in different technology. If we wanted to go with very small "ultra light batteries", being many times smaller than AA size, then theese should have many times smaller capacity. But because in game a tool cannot consume less than one charge at once, for example talking doll saying one phrase, i think its better to have 40 ml and 50 charges u.l.b. than 10ml and 13 charges u.l.b. 

> Give battery powered tools a sensible magazine_well entry in their JSON and this problem disappears completely.

yea, thats probably better solving method than one i proposed, and should solve mod-volume issue as well? 

> Making batteries 0 volume will break the vehicles code for complicated but stupid reasons. It's something we can fix, but it's not as simple as making a change. Making them 0 mass is fine and probably should be done.

Just the mass change will probably be enough, since pure battery charges are not going to be obtainable outside of debug mode. We could change it that 100 battery charges are not bigger than 100 charges light battery cell, but that probably does not matter. 

Giving rechargeable batteries propper description is obvious, but i think it would be nice to have two types of batteries, one rechargeable, and one not, the second type being much more common, probably more efficient per volume, and being possible to craft acid. This way rechargeable batteries would be very valuable and nice a find.  

UPS, energy consumption and car batteries , if they are well known issues, then it probably wasnt really constructive mentioning them there.

**Comment by HKMist** [comment]
Just some thought on the battery magazine's weight. 
If my understanding on the code is collect, a magazine's weight is calculate at item.cpp 3311>3317, and already have code to separate calculation base on ammotype. So is it possible to code it to alway return only the battery magazine's weight without the weight of it content if the ammotype is battery?

**Comment by Highmongrel** [comment]
So, I'm not entirely sure why, but after playing around with battery weight I found something a bit odd. Removing the weight entry entirely seems to make it so that batteries no longer increase in volume with charge.

Comparison using medium battery cells
![0 Weight Battery Comparison](https://user-images.githubusercontent.com/47551519/57384213-015cb800-7165-11e9-8225-13252f8de39c.png)
When placed in a tool
![0 Weight Battery in Tools](https://user-images.githubusercontent.com/47551519/57384222-0883c600-7165-11e9-83d7-cb521f5b302b.png)

Not sure if it breaks anything with vehicles, as I haven't been able to do a thorough test with them, and tools still get bigger until magazine_well is added, but it seems to be worth noting.

Will have to do some more testing before trying to push it though.

**Comment by Inglonias** [comment]
The change to add magazine wells is very close to done and is next on my todo list.
