### ISSUE TITLE
Can't cut up any pet armor

### ISSUE THREAD

**Issue by Yunatan** [CleverRaven/Cataclysm-DDA#30339]
**Describe the bug**  
Can't cut up e.g. leather dog harness. 

**To Reproduce**  
1. Craft leather dog harness.
2. Drop it on the ground and stand over it.
3. Press ``B``utcher to cut up items.
4. Observe absence of the leather dog harness among the options 

**Expected behavior**  
I expect to be able to cut up pet armor that is made from the same materials as human armor that I can cut up. I also expect to salvage no more materials than I used to craft it. 

**Additional context**  
It has ``[ "NO_SALVAGE" ]`` flag, but just removing it is not enough, as it results in inadequate salvaged materials (rags in addition to leather and the quantity is wrong too).

**Comment by DracoGriffin** [comment]
Related to #29134, specifically:
>NO_SALVAGE applied to leather harness (gave back way too much rags and leather patches for some reason) and rainsuit (yielded neoprene sheets).

Looks like I forgot about making specific disassembly recipes. Making recipes that yield 50-60% of input items back would probably suffice, and rainsuit would need to avoid giving back neoprene sheets (they aren't used in the crafting recipe).

The reason they have unusual material combinations because the armor is inherited by material type, rather than being able to specify bash/cut values. More details can be found in #29134 and #28646.
