### ISSUE TITLE
Finding comfort amidst the apocalypse

### ISSUE THREAD

**Issue by Yunatan** [CleverRaven/Cataclysm-DDA#30354]
I want to use this thread to provoke a discussion and gather some opinions. 

**Premise**  
There was inclinations to implement things that regularly give a small morale bonus, like a [hairbrush](https://github.com/CleverRaven/Cataclysm-DDA/pull/30013). It is natural, players want to roleplay having nice things and get a little mechanical reflection of that.

**Problems**  
1) Hygine-related stuff is a rabbit hole nobody wants to explore for now; 
2) It is something that has to be constantly activated in a grindy fashion to harvest that morale boost. 

**Examples of what we currently have**
You can play an acoustic guitar by the campfire, make coffee and tea (different kinds actually), enjoy a hot meal, make your base pretty (no mechanical bonuses for this right now), pick Fancy or Spiritual trait and enjoy their benefits, read a piece of a classical literature, play with your dog, chit-chat with another survivor, etc. 

**Describe alternatives you've considered**  
I was thinking what other tools can be introduced to satisfy "I like to have nice things" playstyle. Of the top of my head I can suggest implementing an "admiring" mechanic like in dwarf fortress, which would give you a little moral boost each time you pass by a statue or a painting.

**Comment by kevingranade** [comment]
Previously this kind of thing was a problem for balance because it was difficult to draw a line between making these effects overpowered if you pursued them all and keeping them balanced, but effectively making a lot of these activities mandatory for optimal play.
Now that we have overhauled morale to stack in a root-of-squares way, this effect is still present, but greatly diminished.  As long as we don't introduce effects with extremely high morale bonuses, they won't impact the game balance a great deal, though they will continue to contribute to player morale and mood, and large numbers of them can really add up, especially if we make some of the bonuses particularly long-lasting.

So with balance out of the way, the remaining issue is UI. Wake up every morning and step through a (large?) number of grooming or "fun" activities isn't particularly "fun".
The "ambiance" class of bonuses is fine, maybe you collect nice stuff and station it around your living space, maybe you have nice furniture instead of crappy furniture, nice food instead of boring food.  That all mostly works out because once you establish your source of morale boost, it's a durable bonus.
The problem arises with bonuses that require repeated input from the player to perform, shaving, haircuts, bathing, reading for fun all fall into this, along with potential side issues related to ambient bonus sources like cleaning furniture and dishes.

The main thing I've come up with to address this issue is to add a menu for managing leisure activities if you don't want to micromanage them.  You would accumulate/unlock various activities as you acquire the prerequisites for them, and then you can batch select various activities to perform, and the game can time-skip through all of them at once so you can get down to some zombie smashing.

This could handle leisure activities, studying and maintenance activities.  Ideally the overal amount of micromanagement would drop, while the number of modeled activities would increase.

**Comment by Yunatan** [comment]
Thanks, I got your point on input-requiring activities, but can you please elaborate on your view on  "ambient" morale bonuses? For instance, do you think it would be "balanced" to live in a literal art gallery or a museum and constantly have +20 morale for nice surroundings while you are at your base?

**Comment by kevingranade** [comment]
If the bonus from being near an art piece is relatively small and/or short-lived, it works out fine, because the way we calculate morale now has severe diminishing returns for large numbers of small bonuses.  So unlike df where there's a huge emphasis on quantity of morale sources, we would have a much higher emphasis on consistently generating large bonuses instead.

**Comment by JonahDes** [comment]
One other issue with routine chores is that the appreciation of a bath is much more diminished when you're already clean, as compared to "the first time in months" when you come out of the forest. So you'd also have to include some kind of waiting timer or adjust the actual morale bonus dependent on various factors like how filthy you are, or something.

That could be exploited, someone could roll in mud - the solution to that is probably a somewhat long lasting debuff to morale like "I was filthy".

An interesting idea might be to shape morale bonuses in such a way that it encourages people to engage in activities that they usually wouldn't:

Consider the use of a 'stir-crazy' debuff from spending way too much time (days) crafting inside the same house or interior. That gets resolved by taking a walk somewhere, that might lead to people going on more town raids than just crafting.
