### ISSUE TITLE
Half of existing gear became "too big" after merging PR 28123

### ISSUE THREAD

**Issue by dom4op** [CleverRaven/Cataclysm-DDA#30410]
**Describe the bug**  
Stuff like holsters, sheathes, canteens now have "too big" added to their names. Even those which I make from scratch and supposedly for myself are "too big". There is no encumbrance penalty, it's just mildly irritating to see stuff like "pair of binoculars (too big)".

Link to PR in question: https://github.com/CleverRaven/Cataclysm-DDA/pull/28123

**To Reproduce**  
Craft a holster/sheath/canteen. It's too big.

**Expected behavior**  
Would be great if there wasn't "too big" mark on gear that actually fits.

**Screenshots**  
https://i.imgur.com/J9bZni2.jpg

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 8940
 - Graphics version: Tiles
 - Mods loaded: none

**Comment by XhameX** [comment]
I have the same problem as of #28123 PR and it's really annoying.
Most of the "Too big" tags seems to be connected with the Tag
"`This clothing is large enough to accommodate abnormally large mutated anatomy`."
"`This piece of clothing is oversized and does not fit you`."

**To Reproduce**
Do what @dom4op wrote.
Add a shoulder strap mod to a gun.
Craft a Cloak.
Craft a Pouch.
Craft a Bandolier /Rifle/Shotgun/Pistol.
Craft a Patchwork quilt.
Craft a Survivor rucksack
Find a pair of binoculars.
Improving the fit on items still have the "too big" tag.
For example the stealth cloak.

And much more.

**Expected behavior**
What my survivor craft should not have this tag since he/she is not crafting the item for another NPC.
When it says my survivor improved the fit i expect it to fit obviously.

**Screenshots**
![cataclysm-tiles_Oqwdk86Ih7](https://user-images.githubusercontent.com/2852063/57572400-09914d80-741a-11e9-9f4b-5edfdd1b39de.png)

**Versions and configuration(please complete the following information):**

- OS: Windows 10
- Game Version: 0.D-2810 tiles, Build 8941
- Mods: Too many but i edit them for myself and making sure they throw no errors on start.

This is my first time writing here and if should make a new issue post about this and delete this one let me know.

**Comment by chaisawlajatang** [comment]
I have this problem too, it happens with a lot of clothes and gear.

**Comment by Leosky** [comment]
It seem to happen to every items considered big enough to accommodate to large mutations.

**Comment by Leosky** [comment]
I checked doc and json and code i think it come from recent code addition in https://github.com/CleverRaven/Cataclysm-DDA/commit/70a8c03925de287e183a61bd58368b15f2135411

Regarding code it may be change on how oversize works and json may not have been adapted.

**Comment by MetroidHunter** [comment]
My apologies. I will look into this very soon

**Comment by Leosky** [comment]
> My apologies. I will look into this very soon. This comes from a change in the aforementioned PR around how we handle OVERSIZED gear and what FITS means. I will be sure to add a unit test of some kind to check for these cases

Well, i though a bout it an i was wondering if it was intended. Cause when you see a blanket being 'too big' and the overzised definition it was quite logical. May be it could be kept like that and add a 'larger' tag for the old oversized ?

**Comment by esotericist** [comment]
Looking over the discussion history of the pull request in question ( #28123 ) it seems like the core problem here is a disconnect over the intent of the "oversized" flag.

The game had the assumption that "oversized" meant "can be worn by normal sized players or large players", and it appears that @MetroidHunter was attempting to change that definition.

It was pretty clear from kevin's [comments here](https://github.com/CleverRaven/Cataclysm-DDA/pull/28123#issuecomment-485226264) that he did not receive the understanding that the definition was being changed intentionally (and honestly I couldn't pull that understanding out of the PR description myself, I only realized it after the fact while looking through the discussion).

So when kevin asked for the additional encumbrance penalty to be moved, metroidhunter complied, but did not walk back any of the other UI changes that went along with metroidhunter's revised definition of the term.

**Comment by MetroidHunter** [comment]
> So when kevin asked for the additional encumbrance penalty to be removed, metroidhunter complied, but did not walk back any of the other UI changes that went along with metroidhunter's revised definition of the term.

This is 100% correct

**Comment by alexander-gabriel** [comment]
I still experience this in the latest experimental. Did we have a regression concerning the PR?
