### ISSUE TITLE
Filling a held container from a container on the ground returns "no defined temperature" error

### ISSUE THREAD

**Issue by railmonkey** [CleverRaven/Cataclysm-DDA#30449]
**Describe the bug**  
As of build 8949, attempting to reload a container that is in the inventory, in this specific case a worn hydration pack, from a water bottle on the ground will return the "no defined temperature" error. This also occurs when unloading such a bottle and trying to pour it into the pack.

**To Reproduce**  
1. Debug in a hydration pack and wear it.
2. Attempt to fill the pack specifically from a bottle upon the ground. Alternatively, attempt to unload a bottle on the ground into the hydration pack. Wishing a bottle into your inventory and filling from it will not return this error.

**Expected behavior**  
Liquid in containers on the ground properly reflects ambient environmental temperature.

**Screenshots**  

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.D-2860-g56c8b8c
 - Graphics version: Tiles
 - Mods loaded: Filthy Clothing, Extended Realistic Guns, Makeshift Items Mod, More Survival Tools, Mythological Replicas, Mutant NPCs, Boats, Vehicle Additions Pack, Tanks and Other Vehicles, StatsThroughSkills, DinoMod, Garden Pots

**Additional context**  
E.g. A link to a savegame that allows the issue to be reproduced.

**Comment by Hirmuolio** [comment]
If you look at the bottle on ground with debug mode enabled does it show its "spec ener" as -10?

If you wait one turn does the problem stay?

Does this happen with items spawned with debug menu or with normal items? Items spawned with debug menu don't have temperature when they spawn. The temperature is set for them on the first turn after spawning.

**Comment by ipcyborg** [comment]
Can't reproduce this specific temperature-related issue in 0.D-8234-gfd911084b2
Found a crash, possibly related to this issue: #34507.

**Comment by Night-Pryanik** [comment]
Cannot reproduce this on 0.D-8431 either. If this is still an issue, ping me.

**Comment by ben-wallis** [comment]
@Night-Pryanik just had this happen on 0.E when filling a steel jerrycan from a water pump outside a cabin, I got the error `src/item.cpp:8090 [void item::fill_with(item&, int)] Poured item has no defined temperature` and after ignoring the error, the jerry can was then filled with frozen water. If it's any help I've attached the stack trace and a zip of the save file from a couple of minutes after the error (the water in the jerry can by the fire is no longer frozen since I cooked a clean water from it after the error).

No mods except Generic Guns and Disable NPC Needs enabled.

[Cliff Village.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4471674/Cliff.Village.zip)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4471676/debug.log)
