### ISSUE TITLE
Refugee Center bay clearance mission not spawning target zombie.

### ISSUE THREAD

**Issue by KevlarNet** [CleverRaven/Cataclysm-DDA#30638]
# Describe the bug
The first mission given by the 'Trader' NPC at the Refugee Center to clear out their barricaded bay does not spawn the targeted zombie.

# Steps To Reproduce

1. Start new world with default settings. Turn on NPCs. Wandering Spawns.
2. Locate and Teleport to nearest Refugee Center.
3. Speak to an accept the NPC's question. proceed to the locked bay.
4. Fail to find the appropriate zombie.

# Expected behavior

4. Find and Kill the zombie.
5. Profit.

# Screenshots

# Versions and configuration
- OS: Windows [64-bit]
- Game Version: 0.D-3178-g258b2e8
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

**Comment by alexanderbk1** [comment]
I believe this happened to me too, the dialogue suggests thats theres a zombie master or necromancer among the zombies that spawn in the center, I did not pay attention to that at the moment because the quest was still cleared after killing all the zombies in the area but there was no master or necromancer among them. 

Oh and there was also a guard NPC who I could not help from kamikazing herself against the small horde of zombies despite my best (and somehow reckless) efforts to save her (I even save scummed once to see if I can have her survive, but dont tell anyone)

**Comment by chriseich21** [comment]
It should spawn a shocker zombie named Sean. Can confirm I've had it not generate in Android build 8971, believe shortly after refugee center update I noticed it happening more. It tracked location but no entity to kill. However, my build 8990 it did generate and I have not reset worlds yet, only been updating my apk. I will attempt again and update (play a lot of Refugee start and Bionic Sniper, need to open more issues since they've been getting broken lately).

**Comment by AMurkin** [comment]
Several times he was spawned outside the Refugee Center building for me.

**Comment by Hatfish** [comment]
Can confirm that this is still happening, the shocker zombie hasn't spawned in the last ~3 games I've played and the first quest cannot be completed.

**Comment by mlangsdorf** [comment]
The mission setup isn't complicated:
```
    "start": {
      "assign_mission_target": { "om_terrain": "evac_center_9", "reveal_radius": 1 },
      "update_mapgen": {
        "om_terrain": "evac_center_9",
        "om_special": "evac_center",
        "place_monster": [ { "monster": "mon_zombie_electric", "name": "Sean McLaughlin", "x": 10, "y": 10, "target": true } ]
      }
    },
```
in my test game, the mission target indicator was at the right place, but at zlevel -4.  zombies can't spawn in solid rock, so no shocker zombie.

I'll work with i-am-erk and ralreegorganon to figure this one out.

**Comment by ralreegorganon** [comment]
@mlangsdorf 

I think the problem here (or at least part of it) is that the code for finding locations will do partial matches--it ultimately ends up calling `overmap::is_ot_type` which will allow a partial match if the names match from the start up until a `_` separator, and while `evac_center_9` is the intended target, it's also going to match `evac_center_9_z-4`. 

The code that finds the location starts from the bottom z-level and works its way up, and so it's matching `evac_center_9_z-4` before it can match `evac_center_9`, which is why you ended up having a target indicator at z -4.

We already have a flag (`allow_subtypes`) in the parameters for the finds here which allow specifying whether a "subtype" match is allowed, which is a substring match anywhere. We probably need to revisit how we're doing matches so that it's possible to allow specifying an explicit match (that also handles when the overmap terrain is rotatable and thus has the _north/south/east/west suffixes).
