### ISSUE TITLE
Error while starting up game

### ISSUE THREAD

**Issue by YukariMindGap** [CleverRaven/Cataclysm-DDA#30798]
# Describe the bug

I got an error about something wrong in the JSONs and it didn't proceed into the game

# Steps To Reproduce
1. Try starting the game.

# Expected behavior

the game proceeds successfully

# Screenshots
![image](https://user-images.githubusercontent.com/39007766/58305522-9aa4f300-7e22-11e9-8726-1c3f2d0b55a0.png)

# Versions and configuration

 - OS: Windows 7
 - Game Version: 0.D-3387-ged96404
 - Graphics version: Tiles
 - Mods loaded: dda

**Comment by tinukedaya** [comment]
Same here... Happens when processing "Mapgen Weights"



-----------------------------------------
09:16:46.608 : Starting log.
09:16:46.608 INFO : Cataclysm DDA version 0.D-3387-ged96404
09:16:46.628 INFO : Number of render drivers on your system: 4
09:16:46.628 INFO : Render driver: 0/direct3d
09:16:46.628 INFO : Render driver: 1/direct3d11
09:16:46.628 INFO : Render driver: 2/opengl
09:16:46.628 INFO : Render driver: 3/software
09:16:46.634 INFO : Language is set to: 'en'
09:16:47.762 INFO : SDL version used during compile is 2.0.5
09:16:47.762 INFO : SDL version used during linking and in runtime is 2.0.5
09:16:47.827 INFO : Active renderer: 0/direct3d
09:16:48.149 INFO : USE_COLOR_MODULATED_TEXTURES is set to 1
09:16:48.150 INFO : generate_alt_rect_texture() = FAIL. alt_rect_tex_enabled = 1
09:16:48.404 WARNING : opendir [./mods/] failed with "No such file or directory".
09:16:58.594 ERROR MAP_GEN : (error message will follow backtrace)
	(@0x58630e[cataclysm-tiles.exe+0x18630e]), 
	(@0x58693a[cataclysm-tiles.exe+0x18693a]), 
	(@0xb11c65[cataclysm-tiles.exe+0x711c65]), 
	(IMG_LoadWEBP_RW+0x1bedfc@0x113a4dc[cataclysm-tiles.exe+0xd3a4dc]), 
	(@0x6fed01[cataclysm-tiles.exe+0x2fed01]), 
	(@0x7016c2[cataclysm-tiles.exe+0x3016c2]), 
	(@0x701cdb[cataclysm-tiles.exe+0x301cdb]), 
	(@0x669ac4[cataclysm-tiles.exe+0x269ac4]), 
	(@0x66bd86[cataclysm-tiles.exe+0x26bd86]), 
	(@0x6938a5[cataclysm-tiles.exe+0x2938a5]), 
	(@0x86424c[cataclysm-tiles.exe+0x46424c]), 
	(@0x867b55[cataclysm-tiles.exe+0x467b55]), 
	(IMG_LoadWEBP_RW+0x526e1f@0x14a24ff[cataclysm-tiles.exe+0x10a24ff]), 
	(@0x4013ed[cataclysm-tiles.exe+0x13ed]), 
	(@0x4014fb[cataclysm-tiles.exe+0x14fb]), 
	(BaseThreadInitThunk+0xd@0x76fd571d[kernel32.dll+0x1571d]), 
	(RtlUserThreadStart+0x1d@0x7723385d[ntdll.dll+0x5385d]), 
Backtrace emission took 0 seconds.
sym is defined as number instead of string for overmap_terrain: robot_dispatch_first (robot dispatch center)
09:16:58.594 ERROR MAP_GEN : sym is defined as number instead of string for overmap_terrain: robot_dispatch_second (robot dispatch center)
09:16:59.506 WARNING : opendir [./save/Arlington Heights/mods] failed with "No such file or directory".
09:17:00.208 ERROR : src/main_menu.cpp:977 [bool main_menu::load_character_tab()] Error: line 42:13: member not found: item


          { "item": "broken_skitterbot", "chance": 3 }
        ],
        "l":
            ^
             { "group": "ammo_pocket_batteries_full", "amount": [ 0, 2 ] }
      },
      "items": {

**Comment by WhitePaperWraper** [comment]
I had this exact error too but disabling "more buildings" mod seems to be helping.

**Comment by Platyclysm** [comment]
I'm having the same error, not sure which 'more buildings' mod you're referring to, the only one I had with that name specifically was Fuji's More Buildings and disabling that did nothing.

**Comment by ZhilkinSerg** [comment]
Update to latest game version. The issue was fixed already.

**Comment by tinukedaya** [comment]
Hmmm... was under the impression i have the last build as it happened on 9032 which is the last on http://dev.narc.ro/cataclysm/jenkins-latest/

**Comment by ZhilkinSerg** [comment]
9032 was last available build for Windows, but it doesn't mean that it was last available for other systems. Builds are failing sometimes. You can check latest build number [here](https://github.com/CleverRaven/Cataclysm-DDA/releases).

**Comment by RusOne83** [comment]
-----------------------------------------
23:00:32.801 : Starting log.
23:00:32.801 INFO : Cataclysm DDA version 0.D-4014-gdd554e5
23:00:39.441 INFO : SDL version used during compile is 2.0.8
23:00:39.441 INFO : SDL version used during linking and in runtime is 2.0.8
23:00:39.509 INFO : USE_COLOR_MODULATED_TEXTURES is set to 0


-----------------------------------------
09:37:07.862 : Starting log.
09:37:07.862 INFO : Cataclysm DDA version 0.D-4014-gdd554e5
09:37:14.802 INFO : SDL version used during compile is 2.0.8
09:37:14.803 INFO : SDL version used during linking and in runtime is 2.0.8
09:37:14.907 INFO : USE_COLOR_MODULATED_TEXTURES is set to 1
09:37:14.908 INFO : generate_alt_rect_texture() = FAIL. alt_rect_tex_enabled = 1
09:37:15.913 WARNING : opendir [/storage/emulated/0/Android/data/com.cleverraven.cataclysmdda/files/mods/] failed with "No such file or directory".
09:37:36.254 ERROR : /var/lib/jenkins/workspace/Cataclysm-Android/android/app/jni/src/assign.h:46 [void report_strict_violation(JsonObject &, const std::string &, const std::string &)] line 12:21: assignment does not update value


    "type": "overmap_land_use_code",
    "id": "cropland",
    "land_use_code":
                    ^
                     1,
    "name": "Cropland",
    "detailed_definition": "Generally tilled land used to grow row crops.  Boundaries follow the shape of the fields and include associated buildings (e.g., barns).  This category also includes turf farms that gro
09:37:49.274 WARNING : Deprecated foreground color suffix was used: (lt) in (ltred).  Please update mod that uses that.
09:37:49.292 WARNING : Deprecated foreground color suffix was used: (lt) in (ltgray).  Please update mod that uses that.
09:37:49.487 WARNING : Deprecated foreground color suffix was used: (lt) in (ltgray).  Please update mod that uses that.
09:37:49.487 WARNING : Deprecated foreground color suffix was used: (lt) in (ltgray).  Please update mod that uses that.
09:37:49.490 WARNING : Deprecated foreground color suffix was used: (lt) in (ltgray).  Please update mod that uses that.
09:37:49.498 WARNING : Deprecated foreground color suffix was used: (lt) in (ltgray).  Please update mod that uses that.
09:37:49.651 ERROR : couldn't parse color: c_light_grey
09:37:51.016 ERROR MAP_GEN : sym is defined as number instead of string for overmap_terrain: robot_dispatch_first (robot dispatch center)
09:37:51.016 ERROR MAP_GEN : sym is defined as number instead of string for overmap_terrain: robot_dispatch_second (robot dispatch center)
09:37:54.761 WARNING : opendir [/storage/emulated/0/Android/data/com.cleverraven.cataclysmdda/files/save/Metal Gear :Raiden Sinn/mods] failed with "No such file or directory".
09:38:05.407 ERROR : /var/lib/jenkins/workspace/Cataclysm-Android/android/app/jni/src/computer.cpp:1889 [computer_action computer_action_from_string(const std::string &)] Invalid computer action bonesetting

-----------------------------------------
11:14:06.259 : Starting log.
11:14:06.259 INFO : Cataclysm DDA version 0.D-4014-gdd554e5
11:14:13.178 INFO : SDL version used during compile is 2.0.8
11:14:13.178 INFO : SDL version used during linking and in runtime is 2.0.8
11:14:13.272 INFO : USE_COLOR_MODULATED_TEXTURES is set to 1
11:14:13.272 INFO : generate_alt_rect_texture() = FAIL. alt_rect_tex_enabled = 1


-----------------------------------------
11:15:49.001 : Starting log.
11:15:49.021 INFO : Cataclysm DDA version 0.D-4014-gdd554e5
11:15:56.497 INFO : SDL version used during compile is 2.0.8
11:15:56.508 INFO : SDL version used during linking and in runtime is 2.0.8
11:15:56.608 INFO : USE_COLOR_MODULATED_TEXTURES is set to 1
11:15:56.610 INFO : generate_alt_rect_texture() = FAIL. alt_rect_tex_enabled = 1

Can anyone point me in the direction of a fix for this when using msx++deadpeople?

**Comment by RusOne83** [comment]
I play Android version on a tablet

**Comment by ZhilkinSerg** [comment]
[I]gnore error. There is a good chance game loading would successfully continue after ignore.

If you were using PlayStore stable version, try opt-in to Beta to receive experimental updates and see if issue is resolved there. If it is not - wait for next Beta version (they come out roughly once per month).

P.S.: You are reporting an error in a closed unrelated issue. In the future if you want feedback - you better open new issue.

**Comment by RusOne83** [comment]
I've been ignoring the error . And everything works fine with different tile sets . But MSXdeadpeople causes a fail alt tex enable=1 error. I want to use the deadpeople file but I'm having problems.

**Comment by RusOne83** [comment]
Sorry for doing this in the wrong place

**Comment by ZhilkinSerg** [comment]
> 
> 
> I've been ignoring the error . And everything works fine with different tile sets . But MSXdeadpeople causes a fail alt tex enable=1 error. I want to use the deadpeople file but I'm having problems.

You didn't tell what was the issue in the first place. App crashed or what?

**Comment by RusOne83** [comment]
Oh , the game crashes if I try to load MSXDeadpeople tile set. Game works with other tile sets. But I was trying to use the MSXDeadpeople

**Comment by Night-Pryanik** [comment]
Usually this means that your device doesn't have enough memory to run this tileset, as it is very memory-hungry.

**Comment by RusOne83** [comment]
> Usually this means that your device doesn't have enough memory to run this tileset, as it is very memory-hungry.

Is there a way to move to SDcard? My internal memory is low but I've got plenty memory on sd

**Comment by Night-Pryanik** [comment]
> Is there a way to move to SDcard? My internal memory is low but I've got plenty memory on sd

It's device-dependent. My device forbids moving apps to SD too, for example.

**Comment by Zireael07** [comment]
Nope, even if there were, it won't help. The memory @Night-Pryanik mentioned is RAM - the game doesn't have enough RAM to unpack the tileset for actual use.

**Comment by RusOne83** [comment]
> Nope, even if there were, it won't help. The memory @Night-Pryanik mentioned is RAM - the game doesn't have enough RAM to unpack the tileset for actual use.

Dang ,thanks anyway.
