### ISSUE TITLE
Misclassification of various foods as vegetables

### ISSUE THREAD

**Issue by Regularitee** [CleverRaven/Cataclysm-DDA#30821]
Concerning the "Hates Vegetables" trait, it seems popcorn qualifies as a vegetable ("material: vegetable matter"). This also applies to various forms of nuts: cashews, almonds, peanuts, and pistachios ("material: nut").

Maybe they should be reclassified as junk food, or something like that?

**Comment by KorGgenT** [comment]
nut is a material.

**Comment by EirenexTheDragon** [comment]
salted popcorn is junkfood, but normal popcorn without is considered healthy, so it doesnt makes sense to make it junk food.

**Comment by Regularitee** [comment]
Wouldn't it be junkfood by virtue of its lack of substance? i.e., provides insignificant nutrition or even calories. It's only "healthy" in the sense it temporary stops you from eating other junkfood, at least in my opinion. 

And maybe nuts don't deserve to be junk food, but they certainly don't qualify as a conventional vegetable; in fact, many junkfoods make large use of nuts (chocolate bars, cookies, etc).

**Comment by kevingranade** [comment]
Popcorn is corn, corn is a vegetable.
Nuts are also vegetable matter.

This is working as intended.

**Comment by SourSlime** [comment]
I agree about the corn, but I don’t think nuts should be classed as a vegetable in this case. 

Hates Vegetables Description:
"You, like many children, hated eating your vegetables; however, you didn't outgrow it. It's possible for you to eat them, but you will suffer morale penalties due to nausea." 

The type of vegetable being referred to is probably leafy greens, like spinach, broccoli, asparagus and brussel sprouts, not nuts. Nut allergy is also a thing IRL which we don’t have in the game, and a seperate issue to hating vegetables. I used to dislike leafy greens, but never nuts.

Also, I don’t think hating vegetables causes people to be nauseous. It should be a straight morale penalty, because nausea indicates a digestion issue rather than a dislike.
