### ISSUE TITLE
First Aid Kits for the ranch Foreman should be craftable

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#31149]
**Is your feature request related to a problem? Please describe.**  
The Foreman asks to bring him 6 first aid kits. The quest was created when the first aid kit was a distinct item directly used to heal things and used to be craftable with the proper components. Now the kit is just a compound item that disassembles into various medical supplies plus the booklet.

**Describe the solution you'd like**  
I doubt the Foreman needs 6 noob first aid booklets for his clinic. Let him ask for raw medical supplies instead of complete pre-Cataclysm kits that are quite rare of a drop ATM, and he asks for the supplies themselves anyway in the first place.

**Comment by faefux** [comment]
Lots of the things he asks for are fairly rare, I don't think randomly making the Tacoma Commune missions easier is a great idea, personally.  i'd assume they want a bunch of medkits because they will be guaranteed to have a bunch of itemized and sterile medical supplies.  One can assume that in the post-catacylsim, pre-cata medical supplies are somewhat sought after.

**Comment by dom4op** [comment]
The foreman actually states that he aknowledges the rarity of medkits. I do not remember the exact phrasing, but I got the feeling that the foreman doesn't even know exactly what can be found in those medkits. He's not a doctor, after all. They should suffice for the planned clinic, and that's the whole point.

**Comment by kevingranade** [comment]
The ask is for pre-cataclysm first aid kits, not cobbled together improvised stuff. This is working as intended.
