### ISSUE TITLE
predecessor terrain bug

### ISSUE THREAD

**Issue by SunshineDistillery** [CleverRaven/Cataclysm-DDA#31144]
# Describe the bug
Predecessor_terrain does not work with most om_terrains.  It will work with the hard-coded terrain types, like forest, slimepit, etc,, but not with most .json om_terrains.  

# Steps To Reproduce
Change dock's predecessor to "dirtroad" or something
Get error messages.

# Expected behavior
It works with any om_terrain. 

# Additional context
This might just be an unimplemeted feature rather than a bug, but the doc does not make that clear.

**Comment by ralreegorganon** [comment]
I’ll give it a look.

**Comment by ralreegorganon** [comment]
@SunshineDistillery so I thought this bug report was a little odd because in the docks I **do** use it with a json based terrain (`lake_surface`), but since you didn't include the actual error messages I had to see for myself. 

The error message is `invalid overmap terrain id "dirtroad"`, and that's accurate. 

Here's what the actual issue is: if you're specifying a rotatable terrain as the predecessor, you need to specify the rotation you want to use. So, `dirtroad` does not work, but `dirtroad_north` does. 

This is the same thing you experience when designing overmap specials and using rotatable terrains--you end up needing to specify a rotation for any rotatable terrains that are referenced, and then they are all rotated together if the placement is rotated.

Thanks for the bug report, but I think this is working as intended.

**Comment by SunshineDistillery** [comment]
Cool. I'll continue to experiment with it.
