### ISSUE TITLE
Tile "Brightness" does not match Lighting level

### ISSUE THREAD

**Issue by GitGodScrub** [CleverRaven/Cataclysm-DDA#31151]
# Describe the bug
The light that is visually shown on the tile do not match the actual light-level.

# Steps To Reproduce
I noticed this when i loaded the game, i am not sure if it was always this way.
This bug might need additional verification.

# Expected behavior
NA.

# Screenshots
![lqQTCuK](https://user-images.githubusercontent.com/18603041/58949455-ca41ec80-878c-11e9-93a4-1eeddaa22838.jpg)
This tile works as intended.

![RlI2UKG](https://user-images.githubusercontent.com/18603041/58949456-cada8300-878c-11e9-8b11-42eadb134bfd.jpg)
This tile should be fully lit.

![vk3WH71](https://user-images.githubusercontent.com/18603041/58949461-cdd57380-878c-11e9-8c45-de0accc79526.jpg)
Cloudy-brightness seems about right.
This tile is 1 tile futher away than the "bright" tile.

![V1wX8Z5](https://user-images.githubusercontent.com/18603041/58949459-cc0bb000-878c-11e9-9d37-e68a11b7d5f3.jpg)
The zombie should be fully "lit up"

![BXm6aw4](https://user-images.githubusercontent.com/18603041/58949450-c746fc00-878c-11e9-83ae-69b4dd8cfe73.jpg)
My char. is quite bright. Tho this is not the main issue.

![image](https://user-images.githubusercontent.com/18603041/58950205-7fc16f80-878e-11e9-8d60-5ee393a83edc.png)
As i get closer, it corrects itself, somewhat.
This really makes me in doubt if the feature was intentional?

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-3958-g7f230b5 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bootleg Walkers [Bootleg_Walkers],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Mining Mod [Mining_Mod],
    Beta National Guard Camp [national_guard_camp],
    Dorf Life [Dorf_Life],
    Arcana and Magic Items [Arcana],
    Magiclysm [magiclysm],
    Necromancy [necromancy],
    Manual Bionic Installation [manualbionicinstall],
    Prevent Zombie Revivication [no_reviving_zombies]
]

# Additional context
Its almost as if the "cloudy" tiles are 2 tiles futher out than it should be?
[cdda.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3256704/cdda.zip)
(Savegame + configs)

**Comment by neitsa** [comment]
Yes, there's clearly a visual discrepancy between the lighted locations and the visual feedback the game gives.

> This tile works as intended.

Yep :)

> This tile should be fully lit.

Yes, I think it falls under the light generated by the turret itself. The games "sees" it lighted but the visual feedback is wrong.

> Cloudy-brightness seems about right.

Yes, `bright > cloudy > shady > dark`.

> The zombie should be fully "lit up"

Yes.

> My char. is quite bright. Tho this is not the main issue.

Yup strange... There are various reports of characters generating their own lighten tile...

> This really makes me in doubt if the feature was intentional?

I don't think so.

I'm also concerned by the fact that it seems the turret FoV is extending into dark areas:

![Melaine Gorman _2019-06-07_15-45-51_+0100](https://user-images.githubusercontent.com/4538670/59116675-61a16e00-894c-11e9-99e8-c5a989a567cc.png)

**Comment by KurzedMetal** [comment]
Just because there's light somewhere, it doesn't mean you are close enough to see details there.

IIRC, this is what the code does:
your char has "vision threshold" value, if light is below certain level, you'll either not see it or see it as low light (tile shown as grey scale.
But when the code checks the light level of the tile, it applies a reduction due to distance (coming from "seen_cache", as a percentage), in this case, bright is lowered due to distance to a point that your vision threshold can't see details correctly and that's why you see the description as "Bright" but the tile as grey scale.

Distance in light calculations is also the reason why light sources get bigger radious the closer you get to them (easy to see by approaching a turret at night).

Not sure if this is intended by design or just some quirk to it, but I'm pretty sure this could've been around for a while but no one bothers to check light levels of those tiles (or report it).

**Comment by int-ua** [comment]
I always thought this was intended. The shown brightness is not the actual objective value but how it is visible to the player character.
