### ISSUE TITLE
Idea for new vehicle part (Ram Bars), and concept (Torque)

### ISSUE THREAD

**Issue by NaturesWitness** [CleverRaven/Cataclysm-DDA#3121]
With the addition of collision damage affecting multiple parts of a vehicle (which makes a lot of sense), it would be cool to have vehicle parts that are MEANT to smash into things.  Maybe add a new flag "ram_plate" that can be added to parts like ram bars, bulldozer blades, etc.  When a part with this flag hits something, the damage is isolated to that specific part, kinda like CASE from the old MechWarrior games.  It could also have a value attached the way LIGHT_x does.   Something like a reinforced bumper (like you see on police cars) would be fine for small thing like pushing wrecks out of the way at slow speed but won't do much when ramming a mountain at 60 mph, but a bulldozer blade (which would weigh a ton) would plow through pretty much anything with little trouble.  Could also have crumple zones (high absorb factor, but low durability so break easily).

This also reminds me of one other oddity I noticed; torque (or lack thereof).  While I was testing a new armored car PR, I noticed it was completely possible for my massive, armor-plated behemoth to be stopped dead by a simple bush.  If I was going at a high enough speed I could just flatten it. but if I was moving slow I just stopped dead.  No amount of leaning on the gas pedal would allow me to run over that little bush from a standing start.  I started having flashbacks of Starcraft (C'mon you stupid siege tank, just run over the damn zerglings!  I don't CARE if there's five of them, you're 50 times their size! Don't sit there like a moron and get your ass kicked, squash them!  ARRGH!)  Sorry about that, point is velocity shouldn't be the sole factor in collisions, things like raw power (both from the engine and from how much surface contact we have to apply it with (vis a vie how big the tires are) should be considered too.  This could also be a great incentive for adding more wheels, and maybe even tracks (how cool would it be to have a huge tracked dozer and just cruize through town at 5 mph, crushing every house in the way).
##

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
