### ISSUE TITLE
Crafting with broken arm does not produce crafted item

### ISSUE THREAD

**Issue by DavisBroda** [CleverRaven/Cataclysm-DDA#31323]
# Describe the bug

Attempting to craft some items with broken arm does not produce item.

# Steps To Reproduce

1. Break character's arm
2. ensure character not wielding any item, and no table is nearby
3. attempt to craft tiny motor 
4. tiny motor not wielded, or placed in surrounding tiles, despote crafting being successful

# Expected behavior
 
item should be crafted, then dropped onto player's current tile, 
OR
crafting should fail immediately, with a message informing the player that crafting this required two hands

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-4155-g2afc018 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context
Error occurs both when arm is unsplinted, and when arm splinted. no effect on behaviour

Error does not occur when table nearby. tiny motor ends up placed on the table.

If an item is already wielded, a menu to select what to do appears. If "dispose of your wielded \<item\> and start working" is selected, this bug occurs. If "put it down and start working" is selected, the completed item is placed on the ground, as expected. 

Suspect - but cannot confirm - that this is related to attempting to wield an item that needs to be held in two hands. A few items I tested that can be picked up with one hand (2-by-sword for instance, or rioter mask) craft without this bug, and are wielded at the end of the crafting.

**Comment by RustyBrute** [comment]
Hmm that can be related what just happened to me. I have a splintered broken arm, I were wielding nothing, and I crafted a makeshift welder. Could not find anywhere, so I crafted two more.
While the log said I crafted them, the welders were nowhere to find.
Then I crafted an antena with no issues...
 
-Game version 0.D-5687-g8058314
-Mods: Medieval and historic classes...
           Alternative map key

**Comment by Ramza13** [comment]
I just tried to reproduce this bug and its current behavior is slightly different than described.  If you have a broken arm and attempt to craft a tiny motor, it creates an in progress tiny motor (0%) which is dropped and which you cannot wield or finish due to the broken arm.

This doesn't seem like a good use case, but there are a number of different solutions.  We could  prohibit the player from crafting a two handed object with a broken arm or allow them to resume in progress items on the floor or even start on a slightly bigger definition of what you can and can't do with a broken limb which seems sorely needed eventually. 

Anyone have thoughts on the best way forward?
