### ISSUE TITLE
Audio books.

### ISSUE THREAD

**Issue by DemAvalon** [CleverRaven/Cataclysm-DDA#31353]
**Is your feature request related to a problem? Please describe.**  
Audiobooks are a thing in real life that would enable someone who is visually impaired or illiterate to learn recipes or train skills.

**Describe the solution you'd like**  
audio books could be found in sd cards and downloaded into an e-ink tablet and listened to much like one would do with music (maybe they train a skill much slower than reading a book but passively?)

**Describe alternatives you've considered**  
them not existing or needing a specific device for them, a book reader/audiobook tablet or something like this.

**Comment by Inglonias** [comment]
It's been previously stated that the [illiterate trait is meant to be an all-or-nothing choice](https://github.com/CleverRaven/Cataclysm-DDA/issues/27312#issuecomment-450053736).

That said, having the ability to slowly gain XP in a skill passively is fine.

**Comment by DemAvalon** [comment]
> as long as it doesn't allow an illiterate person to gain recipes without the help of an NPC.

Seems weird to me but if its a balance reason then I guess there is nothing that can be said about it...

The audiobook idea would still be good in the sense it would allow a player to slowly train skills while doing other stuff, like working on a vehicle, farming, traveling, etc...

**Comment by Inglonias** [comment]
If they were implemented like you describe, the issue I brought up is actually moot. As far as I know, computers of any kind (including e-ink tablets) can't be used if you're illiterate.

I like the idea and already see a trade-off. Your focus drops when you're learning from a book, so this would keep your focus down, maybe even be a passive morale drain, while you do other things and learn all about the secrets of the universe all the while. Since presumably you're listening with some sort of headphones, like you do with the mp3 player already, you'd be hard of hearing and/or deaf while this happens, so it's not a universal boost.

**Comment by Stone94** [comment]
I dunno, I disagree with computers and tablets being off limits when your illiterate, considering I watch my illiterate 5 year old use both every day, he uses it just by pictures alone,  he has no trouble finding the games he likes, and he always has new ones downloaded. Assuming we are talking about illiterate meaning they can't read.

**Comment by I-am-Erk** [comment]
I'm fine with entertainment books as audiobooks.

It's pretty unlikely to find a useable technical manual as an audiobook.

**Comment by DemAvalon** [comment]
Even cookbooks and "how to talk to people in public" books?

**Comment by l29ah** [comment]
https://www.youtube.com/watch?v=SI35jKT3Usc
