### ISSUE TITLE
Tool and grenade processing with 1 second turns

### ISSUE THREAD

**Issue by ifreund** [CleverRaven/Cataclysm-DDA#31382]
#### Describe the bug

Tools that make use of `"turns_per_charge"` haven't been updated to account for 1 second turns.  This means that in most cases they consume charge six times too fast.

#### Expected behavior

Unfortunately the fix is not as simple as multiplying them all by 6, as there are be some tools that used to have a value of 1 `"turns_per_charges"` and should continue to do so.

#### Additional context

Grenades suffer from the same problem, though it's even less clear if their lifetimes should be extended to match the old behavior.  Most likely they are fine as they are now.

**Comment by Rivet-the-Zombie** [comment]
A grenade really shouldn't take thirty seconds to explode after its pin is pulled, so I think they're fine now. The other stuff totally needs to be fixed though.

**Comment by ymber** [comment]
Most of the powered tools and similar should be fine since #30656. Grenades are fine now. Most of the items left have arbitrary turns_per_charge values like the rebreathers. While we're updating them we should do the research for realistic values for the real items and make up some plausible numbers for fictional ones.

**Comment by Night-Pryanik** [comment]
We need an exhaustive list of tools not working right (if any at all) for this issue to be valid.

**Comment by anothersimulacrum** [comment]
Seeing as none has been provided, I think this is probably resolved (or very well hidden).
