### ISSUE TITLE
RM13 Combat Armor reload oddities

### ISSUE THREAD

**Issue by daydreamer0000** [CleverRaven/Cataclysm-DDA#31400]
# Describe the bug

Reloading the RM13 Combat Armor with 10 plutonium fuel cells Increases its weight to 800+ pounds, Unloading drops 5000 plutonium fuel cells, duplicating the cells but making the armor unusable.

# Steps To Reproduce

1. Give self RM13 Combat Armor and 10 plutonium fuel cells
2. Wear armor
3. reload armor with cells, notice you are now 800+ pounds overweight
4. Unload armor, notice 5000 cells on the ground.

# Expected behavior

Reloading the empty armor increases its weight by the weight of 10 cells. Unloading gives 10 cells back if it was never activated.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-4254-g4259f65 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Hydroponics [hydroponics],
    Boats [boats],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Disable Religious Texts [no_religious_Texts],
    No Survivor Armor [no_survivor_armor],
    No Fungal Monsters [No_Fungi],
    Safe Autodoc [safeautodoc],
    StatsThroughSkills [StatsThroughSkills]
]

**Comment by hexob** [comment]
i have this issue too

**Comment by joe9000** [comment]
me too. showed up somewhere after 9140

**Comment by joe9000** [comment]
this appears to have been introduced in #30874. calls to ammo_type() were replaced with ammo_current() but the right side was left as "plutonium" which is the ammo_type but the id is "plut_cell" so the blocks that manage the PLUTONIUM_CHARGES constant in game_constants.h are getting skipped. i think fix would be to have ammo_current() return the ammo_type instead of id, but my cpp skeelz ain't up to that at present.
