### ISSUE TITLE
Add map reveal to matchbooks.

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#315]
Allow reading a matchbook to reveal a local business, a bar, gas station, or motel.
##

**Comment by sparr** [comment]
would reading the same matchbook always reveal the same location? how would we keep track of that?

**Comment by kevingranade** [comment]
Single use is intended, ideally mapgen would insert the spawn location of
the item into the item itself so it can use it as the basis for an offset
to the location being mapped, possibly with some additional entropy in case
several are spawned at the same location.

**Comment by WizardOfOoo** [comment]
Survivors maps show all the things on a list in the viewable map area right?
What about making it like work like that on a smaller scale? When read It shows the location of one building within the view range, chosen from a list of bars, restaurants, hotels, gas stations, and what ever else is appropriate.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
