### ISSUE TITLE
[I18n] What is ’kinbot‘？

### ISSUE THREAD

**Issue by kwl01skz** [CleverRaven/Cataclysm-DDA#31503]
src/monattack.cpp:

`a soft robotic voice say, "Greetings kinbot. Please take good care of this patient."
`
I can't translate it because I can't understand it.

**Comment by DemAvalon** [comment]
Seems like its something like Kin (a member of the same species/family) Bot (robot) so another way of saying "Greetings fellow robot", at least that is what I think.

**Comment by ZhilkinSerg** [comment]
https://www.thesaurus.com/browse/kin

**Comment by Fris0uman** [comment]
It was an attempt at suggesting family ties without using brother/sister because they suggest gender and robot have no gender. If you're translating to a language without neutral word like in english I suggest to default to female (so replace kin with sister basically) because it seems that nurses are mostly female in people's mind.

**Comment by kwl01skz** [comment]
> It was an attempt at suggesting family ties without using brother/sister because they suggest gender and robot have no gender. If you're translating to a language without neutral word like in english I suggest to default to female (so replace kin with sister basically) because it seems that nurses are mostly female in people's mind.

OK，谢谢
