### ISSUE TITLE
Reading times are under 1 minute per chapter

### ISSUE THREAD

**Issue by Proman9000** [CleverRaven/Cataclysm-DDA#31502]
# Describe the bug

No chapter of any book is over 1 minute reading time.

# Steps To Reproduce

1 Load Save
2 Press R
3 Admire superhuman reading comprehension

# Expected behavior
Longer read times

# Screenshots

![grafik](https://user-images.githubusercontent.com/49998438/59558019-661ef400-8fe8-11e9-8597-e64d3108c0c3.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-4484-gbcc75f4 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

[Aplin.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3293737/Aplin.zip)

**Comment by Amoebka** [comment]
Can confirm this happens. Also worth noting is that during character creation, if your INT is below 10, read times are shown correctly (i.e. around 600%, which really should be 100%, please fix), but when INT goes to 10 or higher, read times are displayed as exactly 10%.

**Comment by Amoebka** [comment]
Ok, basically what happens is INT affects reading WAY more than it should. Default reading speed (8 INT) is 600%, and a change of 1 INT in any direction changes this value by 300% (doesn't quadruple, but "adds" percentage modifier). So with 7 INT you read at 900%, with 6 INT at 1200%, etc. With 10 INT you go to "0%" and with more you go negative, which the game defaults to 10% reading speed, which, since the actual base is now 600% instead of 100%, means 60 times faster than average.
