### ISSUE TITLE
Crafting that uses water constantly produces "Consume the missing components" dialog if done near a water pump

### ISSUE THREAD

**Issue by aleksandrtikh** [CleverRaven/Cataclysm-DDA#31619]
# Describe the bug

When trying to craft something that uses water (e.g. clean water) near a water pump, "Consume the missing components and continue crafting?" dialog pops up with water as the missing component. If Y option selected, the dialog pops up again instantly, with crafting progressing slightly (one turn?). When moving away from the pump, the dialog pops up once, consumes required amount of water, and then crafting proceeds as usual.

# Steps To Reproduce

1. Find a water pump (encountered the bug in the LMOE Shelter location, don't know if location-specific)
2. Try to craft something that uses water as ingredient (e.g. clean water) while staying near the pump.

# Expected behavior

Crafting proceeding normally, without dialog, as it does everywhere else.

# Versions and configuration

- OS: Linux
    - OS Version: Fedora 30
- Game Version: 0.D-4578-gf477339 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by jpfalk1** [comment]
Problem also occurs when the water source is a nearby container of water (i.e. Plastic Jerrycan under a funnel).
Version: 0.D-4796-g8fd4c4a

**Comment by pjf** [comment]
Encountered this today in a LMOE shelter.

Attaching a save in case it helps with debugging. To reproduce bug, go to the craft menu ('&'), select 'tainted tallow', and observe the endless dialogs.

Tested on bd083c93cce35991427d28e74f4507dccd68bbfc.

- [save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3438835/save.zip)

**Comment by pjf** [comment]
Done some testing, and it appears that `player::consume_items` returns an empty list when this bug shows up. Since the return from this method is added to the items being used in the craft, we see the endless string of messages prompting for more inputs.

I'm not yet sure of the circumstances that trigger this. I have a water pump in one LMOE shelter that seems unaffected, and one in another shelter that results in the bug appearing.

**Comment by pjf** [comment]
I *think* I know what's going on. The bug is seen in the LMOE shelter that has a pump that's in an adjacent (but accessible) room:

![wall1](https://user-images.githubusercontent.com/12072/62002477-40891c80-b148-11e9-97b5-44240047c7ad.png)

What I think is happening is the code that checks if a craft is possible sees the pump, and flags water as being available. However for whatever reason when we go to consume the water the wall gets in the way, resulting in it not being consumed.

Removing the wall makes crafting work as expected:

![wall2](https://user-images.githubusercontent.com/12072/62002511-f8b6c500-b148-11e9-9280-6adcd2b3de1e.png)

This is why we're only seeing this bug occasionally, rather than for every craft involving map resources.

**Comment by ifreund** [comment]
I believe this issue (and probably other similar ones with in progress crafts) is rooted in the fact that `map::use_charges()` uses an outdated method of determining which points are to be included.  The fix should be as simple as updating use_charges to use `map::reachable_flood_steps()`
