### ISSUE TITLE
Throwing spears and Survival

### ISSUE THREAD

**Issue by faefux** [CleverRaven/Cataclysm-DDA#31641]
**Is your feature request related to a problem? Please describe.**  
I always wonder why throwing spears as prim:Survival; sec:fabrication. I understand fabrication is used for a lot, but until this is fixed i feel like we should be as realistic and consistent as pssoble.

**Describe the solution you'd like**  
I'd change it to either a primary:fabrication on it's own or Survival of a secondary.

**Describe alternatives you've considered**  
Get feedback and see if anyone recommends better alternative or insists on no changes.

**Comment by glenmack** [comment]
Throwing sticks are the only thrown weapon I can find in the game with a primary crafting of survival and secondary of fabrication. They're both skill 1, so it would be a semantic change at best, and ideally the primary should be throwing, then fabrication. As these extremely low skill requirements indicate the very most basic understanding of the concept, You should probably need to understand at the very least how throwing works first. Will wait for some feedback then open a PR. Otherwise recommend closing.
