### ISSUE TITLE
Winded, quickly dying of dehydration for no apparent reason

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#31657]
# Steps To Reproduce

1. Load the game.
2. Check the anomalous event log and stats.
3. Wait for an hour.
4. You die of dehydration on day 1 with ~50 worth of quench points drank.

# Screenshots

![](https://pstbin.ru/f/38325/)

# Versions and configuration

 - Game Version: 0.D-4695-g888f3e381b-dirty
 - Mods loaded: alt map key

# Additional context

[2019.06.04.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3310709/2019.06.04.zip)

**Comment by Metalsoul212** [comment]
This happened to me last night as well. My character had a heavy cocaine addiction I was trying to break. When to sleep and died of dehydration. Naturally I save scummed because I felt it was unusual. I drank like 3 bottles of water thinking for sure I'd at least make it though the night and of course I died from dehydration in the middle of my sleep again. Said fuck it and turned off the game for the night. Please fix!

**Comment by TechyBen** [comment]
Depressants 11? Can you check your hidden health stats?

**Comment by l29ah** [comment]
I'm drinking alcohol since it's the only liquid thing available at day 1.

**Comment by l29ah** [comment]
@Metalsoul212 check https://github.com/CleverRaven/Cataclysm-DDA/issues/23574

**Comment by l29ah** [comment]
Oh shit, now i load the game, and i'm spawned in the air away from the apartment tower i used to be in.

**Comment by l29ah** [comment]
Okay, teleported myself away, but i'm still dying quickly.
