### ISSUE TITLE
Pain recovery does not match the new HP recovery speed

### ISSUE THREAD

**Issue by Regularitee** [CleverRaven/Cataclysm-DDA#31856]
Now that healing takes ~21 nights instead of 1, the gap between pain and HP regen rates has become sorely obvious. You can be on the cusp of death for days, and take weeks to fully heal -- while you feel fit as a fiddle after a night's sleep, and can run and jump like someone in peak physical condition.

**Comment by eilaattwood** [comment]
Complete pain rework needed here. Wounds are not very painful when not disturbed. 'peaceful'(like reading, crafting, walking with normal speed and without overweight, e.t.c.) activities shouldn't cause more than minor pain. But activities that require physical strength (fighting, running, building, carrying under overweight, e.t.c.) should have penalties: decent pain increase, or even a chance to make the wound worse.

**Comment by 7illian** [comment]
Walking around for several **days** with moderate+ pain sounds like a terrible idea, utterly divorced from gameplay. What do you think would be possible to do with severely lowered stats caused by pain? 

This recent change has already *significantly* increased player down time. Adding penalties upon penalties is poorly conceived. 

Try *playing* with high pain for a few days, to mimic your proposal. Test it. You can cause pain in the debug menu. Not with a high level character with stockpiled food either, but with a new one.
