### ISSUE TITLE
Running out of stamina causes pain levels to increase by a lot

### ISSUE THREAD

**Issue by TheGamingFox1911** [CleverRaven/Cataclysm-DDA#31889]
# Describe the bug

Whenever a player runs out of stamina for any reason they end up getting a lot of pain and their needs increase.

# Steps To Reproduce

1. create a character and spawn into the world.
2. start running until you are out of breath.

# Expected behavior
Normally when you run out of breath during running or pulping zombies you sometimes feel some pain and then you go back to normal.

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-5015-g3fb8798 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Bens GF recipes [Tolerate_This],
    Craftable Gun Pack [craftgp],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Garden Pots [growable-pots],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    DinoMod [DinoMod],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    Mythical Martial Arts [MMA],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Mapgen Demo [mapgen_demo],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Necromancy [necromancy],
    sees-player icon, +attitude [sees_player],
    No Fungal Monsters [No_Fungi],
    Battery Migration for Existing Games [Battery_Overhaul_Legacy_Mode],
    SpeedyDex [speedydex],
    Safe Autodoc [safeautodoc],
    Manual Bionic Installation [manualbionicinstall],
    Disable NPC Needs [no_npc_food],
    Classic Roguelike Classes [RL_Classes],
    Classes and Scenarios Mod [more_classes_scenarios],
    Bionic Slots [cbm_slots]

**Comment by esotericist** [comment]
The "winded" condition causes you to take pain whenever you do anything that would be a net loss of stamina. It currently persists about 10 seconds, unless you keep doing things to keep being winded.

Basically, if you run out of stamina, you need to stop and recover.

**Comment by TheGamingFox1911** [comment]
The problem for me is that it ends up making my character unable to do a single thing. My stats go to all 0, I get severe pain, and my character gets exhausted/parched

**Comment by Rivet-the-Zombie** [comment]
I had a character end up with 1-2 in all stats and in dark red pain from stamina loss after fighting three giant bees. She was so exhausted afterwards that she had to sleep for four days straight in order to recover to the 'tired' state.

**Comment by EvgenijM86** [comment]
One more thing I noticed is that riding a bicycle drains your stamina very fast, even if you ride at very slow speed.

**Comment by lgordon85** [comment]
> I just now had a character end up with 1-2 in all stats and in dark red pain from stamina loss after fighting three giant bees. She was so exhausted afterwards that she had to sleep for four days straight in order to recover to the 'tired' state, and it took about four gallons of water to recover from the instant dehydration it brought on.
> 
> Something feels odd about the particulars of this.

Heh, yeah I'm not sure if it is physically possible to get that winded in such a short period of time.

Judging from a personal frame of reference in personal athletic pursuits, there is no level of short term winded that you won't be mostly recovered from within an hour.

I think there's a bit of confusion in the current implementation between the incapacity caused by short term windedness and long term fatigue built over time.

**Comment by micage** [comment]
Same for me.

> Basically, if you run out of stamina, you need to stop and recover.

Right. In other words stop playing. Not a joke.

You loose stamina way too fast. Pulping one zombie dropped my stamina under 50%. Pulping two or more gets me in a world of severe pain with heavy stat losses. Being attacked by more than 2 or 3 zombos in such a situation is the end of the run. Alt F4.
I thought, ok, I don't pulp anymore, but this is not a possible workaround. This rapid stamina loss let's your character have to wait for breath coming back most of the time.

It's game breaking.

**Comment by JayThirtySeven** [comment]
I'm having the same problem, but once winded I basically can't recover no matter what I do. Standing still for a full minute doesn't fix it. I just stay winded and my pain just builds and builds. No mouth encumbrance or anything; just can't breathe for some reason. If I'm lucky enough that I'm not in combat I'll randomly recover after a long time (10+ minutes) waiting. If I'm in combat it's completely hopeless and for now I'm using the debug menu to bypass the bug.

**Comment by TheMurderUnicorn** [comment]
Pulping is the only thing I've really taken issue with.  3-ish pulped corpses = my characters stats being so low I'm basically incapacitated.  This is especially troubling because a pile of corpses on the same tile does not prompt you on how many to pulp, so you will pulp the entire stack -- thus causing pain, tiredness, and terrible stats.

Although I like the stamina 'nerfs', I'd like to see actions that take significant stamina, like pulping, take longer in-game time, and consume reduced stamina.  This could be treated as the character pulping the corpse, but taking small breaks in-between to regain stamina instead of pushing themselves to the breaking point.  I think this logic could also extend to things like cutting trees.  Obviously this wouldn't apply to bicycling, as it's a player controlled action that proceeds turn by turn.

**Comment by Kilvoctu** [comment]
I understand stamina recently underwent a rework, but I feel like some of the particulars of it warrant further investigation. The pursuit of realism is what drew me to CDDA to begin with, and while I've no issue with the concept of stamina and being winded in the game, its current implementation doesn't feel realistic to me. It feels difficult for the sake of being difficult, under the facade of realism, and makes the player character feel more like a robot than human with their strict actions-over-time limitations.

The idea that my fresh firefighter character, fire axe in hand, can't fight more than a few zombies without being winded, can't pulp more than a couple corpses without being winded, or can't break down more than one door without being winded seems unreal. How did this individual even perform their job before the Cataclysm?
Unless I'm mistaken, max stamina is a fixed amount outside of changing it through a couple traits or mutations. I feel like there should be some way to scale this maximum dynamically, through one's stats or ideally, in-game actions. A character who spends their days relaxing in their stocked up wilderness hideout shouldn't have the same amount of stamina as the urban scavenger risking their life each day. This may also give a function to the seemingly useless exercise equipment.
Stamina usage of some actions could take another look at, and more of the traits should have an effect on stamina. For example, characters with Parkour or Martial Arts training should naturally have more stamina. Sleepy or Insomnic may have less.

**Comment by nexusmrsep** [comment]
From what I've heard here, the problem might be not the loss of stamina itself, but the winded effect itself. As I see it it might give far too much pain that it really needs to. This should be investigated further.

As for pulping I'll add a Fail-Safe mechanic like the one I did for butchering. This will encourage taking a short rest, but will not trigger winded effect during the activity itself. The penalty will be that the activity will be longer as you auto-pause to rest in-action.

As for melee mechanics it might need more fine tuning, so every observation is valuable. I've cross tested it with 0.D on a default character vs breathers monsters using fire axe and fists to get roughly the same amount of drain for same amount of hits delivered. But I it's not 1:1 port in calculation so it's open for further polishing.

**Comment by glenmack** [comment]
Butchering, smashing, dissecting, ALL corpse related stuff _under no pressure_ should take 0 stamina. EVER. This change is nonsense.

What you have made is a system where the survivor is a relentless insane maniac that has no impulse control. You want to make smashing corpses take more time when already low on stamina, or makes you tire quicker, fine. Dissecting a corpse is not going to leave you winded. 2-3 smacks to a brain will not leave you winded. You take a breath between smashes.

You want to switch to RUN mode and have it drain stamina like this, at a reward of it being done 4x faster, fine. We need a way to turn off the relentless stamina drain when trying to execute the main game-play loop. Otherwise the majority of the players are going to switch off revivification, and just have a bunch of extra key presses.

Humans by nature have self-control. Any survivor is not going to perform a considered action at a rate which will wind them.

No fail safe, no winding at all. Not for butchery, dissection, or dismemberment.

UNLESS YOU SPECIFICALLY WANT TO DO IT FASTER. Then i'm fine with it.

The game-play loop already has a significant "out of game" time penalty for taking damage in the form of the new "realistic" healing in that you're forced to find somewhere safe and hole up for days-weeks. Further slowed by sleeping now taking minutes rather than seconds.

Stop punishing players (not characters) for the sake of "realism". While simultaneously making the game _feel_ less realistic.

**Comment by agaume** [comment]
I can't understand the new stamina mechanic.
Had a character reach 1200 pain level and exhaustion from a 3 minutes bike ride at 8 in the morning on day 1.
The main problem is clearly the pain you get from being winded !

**Comment by Contemplator11** [comment]
Got the same issue. Ran out of stamina from running, and standing for several minutes caused me severe pain (with pain resistance trait) and dehydrated.
That really ruined my day. My previous run ended prematurely due to 2 mi-go spawned right out of evac shelter exit. This run was ended by the bug.

> I'm having the same problem, but once winded I basically can't recover no matter what I do. Standing still for a full minute doesn't fix it. I just stay winded and my pain just builds and builds. No mouth encumbrance or anything; just can't breathe for some reason. If I'm lucky enough that I'm not in combat I'll randomly recover after a long time (10+ minutes) waiting. If I'm in combat it's completely hopeless and for now I'm using the debug menu to bypass the bug.

**Comment by Kibawan** [comment]
Same Issue. Is a Bug, not a Mechanic XD

**Comment by TechyBen** [comment]
Just to say, similar bug here.
Win 7, latest build, tiles (existing saves).
"Winded" effect happened with no interruption/waring on pulping. Pain and stats meant the character was basically "dead" for about 30 mins to an hour until the pain dropped a couple of levels and they could move again (stats were still low single digits.

Moving excessive loads/weights also caused "winded" effect. IMO there are few people who will push against a wall/drag a car until they physically die on the floor. Their muscles/desire/breath gives out before, but not their ability to breath (muscles to one part of the body get tired, but the others could be fine?).

We already simulate this with interruptions "you are tired, continue?" or *self regulation* to some extent (Your stomach is full you cannot eat anymore). Similar limits to exhaustion/fatigue actions would fit. Not removing the limits, but walling them off, so only cardiovascular activity pushes the character past this (possibly with pain interruption choice for the players benefit), where as low or slow exertion is prevented until stamina increases.

A nice example was given above, if possible. Cycling/activities with the "walk" system enabled, would limit cycling/activities at a power sustainable. Cycling/activities at the "run" system would exhaust the character. Similar for other tasks. Wall them off at times, let the player overexert at others? But I guess that's a lot more coding than the original PR?

**Comment by nexusmrsep** [comment]
Severity of winded mechanic is unintended and will be toned down / fixed soon.

**Comment by eilaattwood** [comment]
I agree with @glenmack, losing stamina during butchering is very weird. You are just sitting near the corpse, calmly making cuts, not dancing and jumping with a corpse on your shoulders until death by exhaustion.

And about smashing... I think, It should check player movement mode, or something like that. When player is not in a hurry, it should take more time, but keeping stamina high. Otherwise it should be as fast as possible, sacrificing stamina, but not until character become winded. Becoming winded while running is ok, because this process is controlled by player turn by turn. But long actions that are performed automatically without full control from the player also should manage stamina automatically.

**Comment by lgordon85** [comment]
@nexusmrsep
I think the reason some are reacting is that it doesn’t feel right in relation to reality.

I sat down and read it bit to refresh my existing knowledge on stamina from being a mediocre athlete in a past life 😆

Basically in order to improve the stamina abstraction in a manner similar to real life, it might be useful to avoid a tack on effect and instead track three parameters:

Oxygen deficit: The burn rate of oxygen intake. This is basically the intensity of the activity and is  the oxygen usage rate of a particular activity versus the ability of the the lungs to bring in oxygen and the heart to deliver it.

Low impact activities have no oxygen deficit, high impact activities incur an oxygen debt.

Oxygen debt: This is the debt built up by running an oxygen deficit. Muscles at work build up lactic acid and need oxygen delivered in order to oxidize this to glucose and remove it from the muscles. This is why we pant after activity in order to keep bringing in oxygen and pay back the debt. 
Fitness affects the ability to burn at a high level and remove lactic acid quickly. Obviously because of high oxygen intake.

Lastly Fatigue:
Fatigue is what causes long term muscle tiredness and is not caused by lactic acid like windedness, but is instead caused by microtears in muscle fibers that break down the muscles themselves. Under regular exercise, the body builds these fibers back stronger than they were before, which is part of what causes improved fitness and strength.


Long story short. IMO a good abstract would be a system that tracks burn rate vs use to create oxygen deficit.

This deficit accumulates oxygen debt (lactic acid build up in the muscles) and would require a recovery period (running an oxygen surplus) to fix it. Different debt levels would accumulate higher levels of disability and pain, but this is a pretty gradual threshold that only reaches extreme pain and disability at a very high level. A high level debt also increases muscle damage (fatigue)
The extreme debt level would be decreased pretty quickly to lower levels upon stopping exercise.

Low impact activities don’t run at oxygen deficit and should essentially never accumulate debt. You can walk for essentially forever and will only accumulate fatigue. The average person could easily ride a bike at a low level for 30-40 miles without serious debt. This is where the current system is causing some clash with the way real life feels.

**Comment by lgordon85** [comment]
Note: The “stamina bar” is already basically an abstraction of oxygen debt budget.

I think you had the right idea by expanding the pool, it probably just needs tweaks to burn rate and a more gradual list of effects as things are depleted, with the most extreme effects clearing quickly.

What might be needed is separate fatigue tracking, maybe in a way similar to the way rads are tracked in fallout.

Fatigue would make a permanent reduction to the stamina (debt) bar and would build up over time with activity. High levels of debt would create this faster. Fatigue would only be removed by sleep, and high levels of fatigue might take days to recover from.

**Comment by Table99King** [comment]
Winded should only make you tire quicker, pain is **unnecessary**

**Comment by nexusmrsep** [comment]
Ok, so let's sum up the actions that are being taken to address some of the cases:
* #31911 is dealing with the bloated out of proportion winded effect, courtesy of @deadcutlass2 
* #31921 adds fail safes to pulping (butchering already had it) and stamina reserve at 1/3 max stamina, belove the limit character will wait in-action to regain some of stamina then pick up the job started
Read the PRs for more info.

Among some salt there are valuable ideas in this thread, that I may revisit, but I'll be away for a while, so this has to suffice for a start on my part.

**Comment by lgordon85** [comment]
@nexusmrsep
Those look like good stopgaps. I look forward to potential expansion of the stamina concept in the future. Good on you to tackle it!

**Comment by nexusmrsep** [comment]
I was able to squeeze a little tweak for the bicycles here: #31923

**Comment by Zmedaris** [comment]
When I'm winded in real life, it's a little harder to breathe and I might feel a bit of cramping.

So maybe a small pain boop, with a cap of course. Getting smashed into a building by a hulk (didn't even break the wall) causes about 40 pain, and I don't think any amount of personal physical exertion could attain that kind of ouch time.

And then maybe a penalty to stamina regen, so it's harder to recover if you push yourself to that point. Plus we already have move point penalty at lower stamina levels.
