### ISSUE TITLE
Invalid Recipe and Missing Item Definition from save older than build 9219

### ISSUE THREAD

**Issue by suka97** [CleverRaven/Cataclysm-DDA#31898]
# Describe the bug

Loading this save triggers the following errors:

-  DEBUG    : Missing item definition: makeshift_shovel
 FUNCTION : const itype* Item_factory::find_template(const itype_id&) const
 FILE     : src/item_factory.cpp
 LINE     : 1194
- DEBUG    : invalid recipe id "tanned_hide_scraped"
 FUNCTION : const T& string_id<T>::obj() const [with T = recipe]
 FILE     : src/recipe_dictionary.cpp
 LINE     : 59
- DEBUG    : invalid recipe id "leather_scraped"
 FUNCTION : const T& string_id<T>::obj() const [with T = recipe]
 FILE     : src/recipe_dictionary.cpp
 LINE     : 59
-  DEBUG    : invalid recipe id "makeshift_shovel"
 FUNCTION : const T& string_id<T>::obj() const [with T = recipe]
 FILE     : src/recipe_dictionary.cpp
 LINE     : 59

(The game loads after them though)

# Steps To Reproduce

1. Load the attached save

[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3332433/save.zip)

# Screenshots

![Untitled](https://user-images.githubusercontent.com/49660888/60225402-14cefa00-985d-11e9-8880-60e7db6ed17d.png)

# Versions and configuration

- OS: Windows 10
    - OS Version: 10.0 1803
- Game Version: 0.D-5015-g3fb8798 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    StatsThroughSkills [StatsThroughSkills]
]

**Comment by ProfoundDarkness** [comment]
Pretty sure this is due to PR #31563 

You can read through the PR for details but basically some stuff got migrated from More Survival Tools to mainline and then within that PR, before merge, a few things got deleted from mainline.

The end result of the PR being that those items and recipes were removed without being obsoleted.

The recipe errors should go away when you save after having got those errors and probably aren't a big deal.

As for the items, if anyone has the items coming up as errors... I don't know.  Undefined items won't just go away like the recipes will.  I myself ended up hand editing my save to remove them.  I find it easier to find items in my character's inventory rather than looking through game world data.
