### ISSUE TITLE
Various weathers create constant light at night

### ISSUE THREAD

**Issue by Zmedaris** [CleverRaven/Cataclysm-DDA#31905]
Most weather events cause varying levels of light, ranging from cloudy to almost day-time bright, during night time. All weathers except clear and cloudy (and the non-included acids) seem to do this.

# Steps To Reproduce
1. Start any character and use the debug menu to set time to night hours.
2. Use debug menu to change weather to something like lightning storm or snow storm.
3. Now you can leave your flashlights at home.

# Expected behavior
Differences in weather shouldn't be creating magically bright overworlds in the dead of night.

# Screenshots
![Screenshot (1782)](https://user-images.githubusercontent.com/12032854/60246693-148e2900-9874-11e9-819a-6cc66050b866.png)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-5005-gc88b7db [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    Mythical Martial Arts [MMA],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Disable NPC Needs [no_npc_food],
    SpeedyDex [speedydex],
    StatsThroughSkills [StatsThroughSkills],
    No Rail Stations [No_Rail_Stations]

**Comment by Lazasar** [comment]
THANK YOU! I have been trying to isolate what was causing this... was making me crazy. Yes, I get this too

**Comment by TechyBen** [comment]
I wonder if this has to do with the optimisation and caching. Hopefully seems like an easy fix? :)
Nice spot.

**Comment by ProfoundDarkness** [comment]
WOW! I only had a few minutes to play earlier and this confused me greatly.

**Comment by Kibawan** [comment]
that happen to me to, any workaround until the fix?

**Comment by chphilli** [comment]
I think there's another side effect of this... sometimes when this is happening I also completely lose vision _inside_ -- I can't even tell where my character is!

I'm standing on the NW corner of the bed here... 
![image](https://user-images.githubusercontent.com/504167/60387761-018a7d00-9a5d-11e9-82ca-8e4f61a330fd.png)

Let me turn on my headlamp to show where I am... 
![image](https://user-images.githubusercontent.com/504167/60387756-f20b3400-9a5c-11e9-856c-3f07bb883465.png)

I'm not blinded... I even have Night Vision!
![image](https://user-images.githubusercontent.com/504167/60387758-fb949c00-9a5c-11e9-8111-058c6a8664a1.png)

And no gear that would be impeding my vision.
![image](https://user-images.githubusercontent.com/504167/60387765-0818f480-9a5d-11e9-8e86-a2f9c4fa3b5c.png)

This is brutal -- I can't go outside because it's bright, and there are acid ants everywhere, and with my broken leg (I hate acid ants) I can't outmaneuver them. I can't do anything _inside_ because I can't even tell where I am unless I use a light source (and I'm very limited on supplies right now).

**Comment by jagoly** [comment]
bisection shows that this issue was introduced by 259d1738e93d2e60225fdd18a89515634a4e139b
