### ISSUE TITLE
Give monsters carried and worn inventories

### ISSUE THREAD

**Issue by ymber** [CleverRaven/Cataclysm-DDA#31957]
**Is your feature request related to a problem? Please describe.**  
Currently zombie drops have some problems and monster armor is abstracted. See #31878.

**Describe the solution you'd like**  
Monsters should have inventories the same as players and NPCs. This will mean adding inventories to the monster class, updating spawn code to give them items,  and updating any code that uses the abstracted armor numbers in damage calculations to use the same system we have for players and NPCs.

**Additional context**  
We may be able to build on Mark's animal armor work here. Worth checking before reinventing the wheel.

This would allow us to stop abstracting armor for zombies as they would have real worn item armor. A lot of zombie types could be obsoleted - zombie soldiers, police, security etc are essentially just tough zombies with plate carriers.

**Comment by Rivet-the-Zombie** [comment]
>A lot of zombie types could be obsoleted - zombie soldiers, police, security etc are essentially just tough zombies with plate carriers.

I'd still leave their names intact. Having them all called by the same name would make it harder to guess their particulars at a glance.

**Comment by FulcrumA** [comment]
Not to mention unique graphics they have. Their item group could probably be set up so "if this zombie uses clothing and loot from the 'police' group of items, call it 'zombie cop', use relevant graphics tile". 

It'd be a huge loss to lose all those nice images and rewriting graphics so all zombies would use layered items like player does seems like a huge undertaking all on its own (and a thing that'd restrict how most zombies would look like so they can all be fit as 'paperdolls' for clothing).

**Comment by Hirmuolio** [comment]
Probably a spawned zombie wouldn't need a real inventory and could keep on using the current system.

But once it dies the corpse would get items generated "inside" the corpse instead on the ground. And when it revives these items are kept on it.

Setting the zombie type from its inventory after reviving would be tricky. At what point does a zobie police turn into normal zombie? How many "police" items would it need to have in its inventory. 
To make things easier player should not be able to dress new items on the corpse.

The zombie drop tables would also need some fixing to make sure they have more type specific clothes so that the revived zombie would be the right type.

Looted zombies would also revive as naked zombies if the plyer loots enough of the items.

**Comment by ProfoundDarkness** [comment]
\<shrug\> Why not just have something like a new action on examining the corpse which 'strips' said corpse and spawns the loot then?  No need to do all kinds of funky tracking and stuff, a simple flag/bool is all you'd need and not a lot of new code (naive assessment).  If you want the zeds to transform on being looted you could do that as part of the action.  This method seems the simplest, by which I mean it seems like something I could do.

I specified a bit more of a detailed example of zombie loot on death and zombie loot tracking in the issue referenced at the top of this issue.  Only thing missing from there was the zombie transform mechanic.  In hind sight the idea seems like an unnecessary middle ground between a loot player action and zeds having inventory/gear which functions.  Especially when there are NPCs who have inventories.

In the end I'd rather see the zombies with real items.  I suspect memory usage would climb pretty fast not to mention pretty significant increase to processing time to spawn the new monsters with gear relative to how long it takes to spawn now (consider z-levels with high spawn rate).  I expect actual turn processing would remain largely the same though.  I'd be curious to know why the idea of zeds with functional stuff (worn items, not guns) got shot down before, if it did.

**Comment by kevingranade** [comment]
Tracking full-blown items would be a bit of a problem, but what we could do is just generate a list of items without instantiating them and use that, and the only get turned into actual items on demand.
Additionally the only things that *need* this treatment before the zombie is killed are worn items, items in pockets or backpacks would not even need to be generated until the zombie is downed because there's no way to interact with them.

**Comment by Night-Pryanik** [comment]
No discussion in more than two years, closing.
