### ISSUE TITLE
Negative water drag on super-heavy death fortress

### ISSUE THREAD

**Issue by Edgar-cy-Lee** [CleverRaven/Cataclysm-DDA#31984]
# Describe the bug
So I own about 37 ton death fortress. I added boat hull to every fields and edited existing vehicle parts that I would consider "Float"(fluid tanks and trunks, which are sealed and would float) and make it barely sea-worthy. And at some point, I got negative water drags.
![image](https://user-images.githubusercontent.com/8914956/60392192-ec990280-9acb-11e9-80f8-d8f47f1f3a10.png)

Driving this vehicle on water will make the vehicle accelerate. Forever. Until you hit something.
Deceleration is disabled during this part.

1. Make incredibly heavy vehicle. (mine is 6x10)
2. Make this vehicle to "Swim" level.

# Expected behavior
Negative water drag value is outside of Newtonian physics this game is simulating.

**Comment by Lorith** [comment]
This is because the calculation compares number of tiles for vehicle vs number of objects with floats flag, and if you have more than numtiles floating objects, the math goes below zero.  Currently your vehicle is simply too heavy and you have to reduce the weight or expand it further to fit more boat boards.  There are plans to eventually have fully-sealed vehicles, but that is a fair ways off.

**Comment by kevingranade** [comment]
Do I understand you correctly that you edited the game data and then the game stopped working correctly?

**Comment by Edgar-cy-Lee** [comment]
> This is because the calculation compares number of tiles for vehicle vs number of objects with floats flag, and if you have more than numtiles floating objects, the math goes below zero. Currently your vehicle is simply too heavy and you have to reduce the weight or expand it further to fit more boat boards. There are plans to eventually have fully-sealed vehicles, but that is a fair ways off.

Makes sense. Thank you.
