### ISSUE TITLE
Being grabbed doesn't affect player's dodge at all

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#32064]
In contrary with ingame description - "You have been grabbed by an attack. You are being held in place and **cannot dodge**, and blocking is very difficult." - game itself doesn't check for player being grabbed whatsoever. Being grabbed slightly reduce your actual dodge value due to `grabbed` effect reducing your speed, but it should reduce dodge value down to zero... right? Or it shouldn't?

Should we add a check for being grabbed and zero the dodge value in this case, or should we change the description instead and remove mention of "cannot dodge"?

**Comment by zacklucky7** [comment]
If you're being held in place by a zombie, you shouldn't be able to dodge, or if you can (like pulling your head away from a bite), it should be with a heavy penalty.

At the moment, melee is relatively risky with a group of zombies because one could grab you while the others close in, but if you're fighting a lone zombie, grabbing is not something to worry about. Getting grabbed by a monster trying to eat your face should change the player's priority to 'get away so I don't get eaten', not 'keep swinging'. I'd even suggest a penalty to melee skills to represent the zombie pinning your arms in place, or maybe being too close to reliably swing at them.

**Comment by l29ah** [comment]
It makes sense to do a check, but right now i think it's too easy to get grabbed: you can hardly dodge/batter off a grab even with quite high melee skills, and martial arts aren't helping at all.

**Comment by TychaiosIlithios** [comment]
A side idea - add this check to martial techniques - for both having grabbed and being grabbed. and so have player and monster techniques with on_grabbed/non_grabbed and on_grabbing/non_grabbing. Thus a zombie on_grabbing would have access to nastier biting and non_grabbing could have a skills with rushing or claw swinging flavors. Same with player on_grabbed having CQC krav-maga or aikido stuff and non_grabbed do some leg swinging if available per martial art.

Although there would be a slight mess in definitions. Because
on_grabbed - have to decide does it just mean grabbed by anyone or by the thing you are trying to target. for simplicity better anyone. (even though while grabbed by one enemy it's quite feasible to kick another)
on_grabbing - when someone else is already grabbing the target it might be just as easy to attack the target as if you yourself are grabbing it. Guess the logical easy solution would be on_grabbing be only personal between the two, but on_grabbed being a stackable debuff to dodge from multiple sources so that several grabs could lead to problems. Could compare it to crowd in project zomboid - if a few Zs throw a lucky grab, usually and suddenly it's all over.

**Comment by Amoebka** [comment]
Being unable to dodge while grabbed makes sense, but grabs are currently already incredibly deadly, and zombies grab very often. Low strength characters are already more or less non-viable because they can't break grabs, taking their dodge away will make it ten times worse. I would say add the check, but also consider making grabs less frequent/easier to break.

**Comment by RDru** [comment]
Waiting/pausing ('.' or '5' by default) could make a player try to push back the zombie that grabbed him. Could be harder than just moving away.

**Comment by Zmedaris** [comment]
Seems like the dodge shouldn't be reduced to zero, but maybe penalized a fair bit?

If you're being grabbed by ONE zombie, let's say its got hold of your arm (probably one of the more common 'grabby' zones), it makes sense you can still dodge... just not as well. If you're a very skilled 'mover', with lots of experience dodging blows and other bad things, you're probably still able to consciously keep other parts of your body out of reach despite having your arm locked in place. Like you can pivot the rest of your body to try and stay out of reach of other grabby baddies, bob your head to avoid swipes, lift or jerk your legs, etc etc.

I don't think it would make sense to reduce dodge to zero just because one zombie is grabbing you, although a penalty is obviously in order. Multiple zombies reduce dodge further, and if enough zeds are grabbing you it can fully negate your dodge to zero. Wouldn't take much. One might actually be all that's needed, but the really slippery folks might need two or three holding them in place to completely immobilize them.

**Comment by lgordon85** [comment]
Not to be overly ignorant or state the obvious, but are grabs an RNG thing, or merely an attack used by zombies and thus potentially avoided in the first place by dodge?

Also, i'd take into account martial arts specifically centered around grabs and getting out of holds.

But as mentioned above, I don't think one zombie could reduce your dodge to zero, seems like it should replicate that classic movie effect of being grabbed by multiple zombies and immobilized unless you can break out.

Perhaps one thing to look at is the ability for dodge itself to roll you out of a grab, after all brute strength is not the only way to get out of a hold. With proper leverage and agility, even a much weaker opponent can remove a grab.
