### ISSUE TITLE
Herb and Spice Overhaul

### ISSUE THREAD

**Issue by roaringjohn** [CleverRaven/Cataclysm-DDA#32084]
**Is your feature request related to a problem? Please describe.**  
Seeing the severe lack of spices and herbs, literally dozens of real herbs and spices missing from the game, was annoying my sense of **_realism_**. Not to mention the broad item "Wild Herbs", which should definitely not even cover all of those herbs/spices that are missing.

**Describe the solution you'd like**  
Add those dozens of spices, gradually if need be. Starting with spices that could be used to craft already-existing items, such as Italian seasoning (adding a recipe requiring **basil, oregano, rosemary**, and thyme) and Chili powder (adding cumin to the recipe).

These additions could go hand-in-hand with the addition of more recipes, more condiments, and so on.

Possibly even adding a flavor system or something, which I heard of was probably in progress in some way as I was thinking of what to do about the severe lack of herbs and spices.

**Describe alternatives you've considered**  
Just adding the few spices/herbs for the already-existing items, or not at all, and thus leaving Cataclysm with a lack of flavor.

**Comment by kevingranade** [comment]
To embark on an overhaul, you need to have a better idea of how it's going to work than, "add all the spices".
The main drawback is if you add an obscure spice to an otherwise easy recipe and make the recipe difficult to make for an arbitrary reason.
The only available alternative is making slightly different recipes for seasoned and unseasoned variants that differ only in fun, which is a lot of extra json for little impact.

**Comment by Maddremor** [comment]
In my experience, seasoning of foods is rarely strict, often allowing replacing or combining spices for dishes. If we consider seasoning a given meal with 0-3 spices, the number of recipies would grow exponentially.
An alternative would be to place all (or most) spices under a requirement and have recepies use that, but that would give little room for interacting with spice variety in any meaningful way.

**Comment by roaringjohn** [comment]
Same as with the Meat Overhaul feature request, the addition of more spices is not something I'd like to see right this instant. More herbs and spices, as well as the differentiation of meats, can be put off until whenever it makes sense. Whether that's a week, a month, or multiple stable builds from now.

Both of these are intended to allow for many more recipes. If there's an "obscure spice" out of the most common spices found in at least the East Coast, then I wouldn't mind it not being added. If it's not so common that it makes "an otherwise easy recipe" difficult, then it should not be added.

**Comment by TychaiosIlithios** [comment]
As a side note, plants are pretty easily moddable - just make chilli peppers with another name and a different spice for result and enjoy. IMHO best major modpack would involve things similar to seasonings so that spice variety is mostly gated through seasoning recipes and individual product recipes remain more or less simple.

**Comment by lPeckishl** [comment]
>  The main drawback is if you add an obscure spice to an otherwise easy recipe and make the recipe difficult to make for an arbitrary reason.

What if you make spice as an activated item? So you make any food, use the spice on it and it gets a "flavored" tag or something that increases the fun. Maybe change ketchup and mayo to the same mechanic.
This would also have a problem where you could add spice to already spiced food and candies, maybe have spicy food already come with this flavored tag and forbid spicing any food that has volume and weight under a certain limit (candy)

**Comment by Rogal-Dorn** [comment]
> > The main drawback is if you add an obscure spice to an otherwise easy recipe and make the recipe difficult to make for an arbitrary reason.
> 
> What if you make spice as an activated item? So you make any food, use the spice on it and it gets a "flavored" tag or something that increases the fun. Maybe change ketchup and mayo to the same mechanic.
> This would also have a problem where you could add spice to already spiced food and candies, maybe have spicy food already come with this flavored tag and forbid spicing any food that has volume and weight under a certain limit (candy)

That seems like the most logical thing to do, but I don't think that any modifications to food besides rotting and temperature states currently exist, so this would have to be a C++ change.

**Comment by YakumoChen** [comment]
After reading up chili powder and getting reminded that chili powder doesn't actually need to contain other spices, I feel like you should focus on making a recipe for curry powder instead (which lacks one)

**Comment by FulcrumA** [comment]
Since we already have tracking of ingredients that went into full meal, wouldn't it be best to simply have optional ingredients as well? It wouldn't be too hard to add/modify json entries if it'd be just in a form of a new "optional components" line and would allow both addition of various spices without making dishes impossible as benefit some of the current recipes which should work. 
In fact, it'd help decreasing bloat as now "deluxe" versions of various dishes would be just their base form + optional ingredients.

**Comment by CoroNaut** [comment]
If you want to create recipes with such detailed ingredients, it may just be best to remove all recipes for food and make a way to make any kind of meal with any ingredients. Adding these spices to the current recipes will be like a blocker seeing as you cant make a meal unless you got this spice. Basically if you want to introduce such diversity, you gotta sacrifice some uniformity. 

Another option is to simply have "optional" ingredients. I would be 100% for this if that could be implemented, otherwise, no vote.

**Comment by Edgar-cy-Lee** [comment]
I agree with cornnaut... but then again, I have fond memories of cooking a meal with a rock, a hint of chrome and a woodbark.

**Comment by roaringjohn** [comment]
I like both ideas of optional ingredients and possibly make spices activated items. tbh. Having both makes sense. Both ways of doing it should apply the same flags, do the same things, and so on, however. The former means one less step, and the latter is useful if the spice is obtained later on.

**Comment by Contemplator11** [comment]
I would also love to see a perspective change to food-cooking process. As it is implemented now, each recipe has it's own skill requirement. IMHO, it would be more logical to implement skill requirement for cooking techniques, i.e. roasting on a stick or boiling is a 0 skill, baking is 3, dehydrating is 2, smoking is 2, canning is 4, deep-frying is 4, fermenting is 3, pureeing is 1, caramelizing is 3, salt-preservation is 3, seasoning is 2 and so on. Cooking food and choosing a technique can be done via activating a tool (pot, frying pan, canning pot, food processor, dehydrator), and choosing a component.
To my mind, only particular dishes should be crafted as "recipes", such as haggis, foie gras, certain alcoholic cocktails, various pasta. You know, those dishes that are served in restaurants and have their recipes standartized.
For more generic dishes, I would love to see a more generic approach, such as when you choose a cooking technique, choose components and get the result. Such as "fried meat" or "fermented wild vegetables", "caramelized apple", "salt-preserved meat", "canned pickles", "seasoned fried liver".
All the techniques would have modifiers to calories, vitamins, health, spoilage time and fun.

As a result, food recipe list will be less bloated, as it is now, since it will only contain "staple" dishes.
However, it will require an overhaul with techniques, modifiers and so on.
