### ISSUE TITLE
Treads game balancing issues

### ISSUE THREAD

**Issue by Regularitee** [CleverRaven/Cataclysm-DDA#32139]
After playing around with tank design today, I've noticed some outstanding issues with them that probably need addressing:

* Treads effectively have infinite carry weight; they appear to ignore off-road (ground pressure) calculations. You can take a stock main battle tank, and remove all but the minimum two tiles of tread (one for each side), and it retains perfect (100%) offroad capability. In which case, why should any player vehicle ever have more than two treads?

* Treads appear to be insanely durable. The treads used on **farm equipment** (rubber treads; 2000 HP, taking 50% damage) appear approximately as durable as the front hull on a main battle tank (boards are 1000 hp, taking 100% damage, and MBTs have 3-5 layers of these on their front). And we're just comparing them to farmer treads here, not even looking at military-grade treads

So to conclude: treads can effectively carry virtually infinite vehicle weight, and even the weakest treads are more durable than the strongest stock vehicle hulls.

**Comment by esotericist** [comment]
Seeing as how treads currently exist only in mod content, and effort has not yet been made to make them part of the main game (with all of the vehicle internals engineering that implies), I'm not sure what exactly you're getting at here.

If someone wants to step forward to maintain mod content, great. If someone has a specific feature they want to pursue that would make such maintenance more feasible, then that'd be helpful. Otherwise, it's not really a balance concern for the game itself (since it doesn't actually have any treads).

Also it'd really be nice if you'd pay more attention to the templates when posting issues. They're there for a reason.
