### ISSUE TITLE
Make shockers take damage from converting tissues to electricity

### ISSUE THREAD

**Issue by ymber** [CleverRaven/Cataclysm-DDA#32131]
**Is your feature request related to a problem? Please describe.**  
Currently shockers are capable of generating an enormous amount of energy from no apparent source.

**Describe the solution you'd like**  
The lore for where shockers get their energy from is that they all have blob modified metabolic interchanges. This implies that their body tissues are being aggressively consumed to provide energy for their lightning effect. In cata terms this means they should be taking damage to generate this energy.

**Comment by aoae23** [comment]
I think this is a case where gameplay trumps realism. It wouldn't be fun if the best strategy for shockers is to wait them out and let them kill themselves.

**Comment by Lorith** [comment]
I always took shockers to have muscles similar to those in electric eels, and store the charge in their cbms similar to a capacitor, then discharge it all at once.  This covers the source and the cooldown both, with the blob mutating them to have that kind of muscle tissue in the first place.

**Comment by FulcrumA** [comment]
Given how common shockers now are and that they are the only non-bogstandard zombie still allowed to spawn from the very beginning, having a downside to their lightning-casting does seem like a fun thing. Now that there's advanced/evolved shocker coming in, I wouldn't mind nerfing the basic ones this way.

**Comment by TheMurderUnicorn** [comment]
This logic would also extend to the smoker zombie, which presumably consumes itself to produce smoke.  Don't even get me started on the gasoline zombies . . .

I think it would be a mistake to make them constantly degrading.  

Also, they're not the only non-standard zombie.  There *are* brutes and slavering biters at least that can spawn early, based on location.  This is another reason I think it would be a mistake to nerf them -- it's good to have a 'high end'.  Yes, the nerf to evolution was much needed, but if there's nothing for the player to be even halfway afraid of early on, then zombies stop being the main antagonist of the game.

**Comment by davidpwbrown** [comment]
how about for a period of time after they discharge, their speed is reduced?
This implies the storing of energy through movement.

**Comment by SirPendrak** [comment]
So they should die from casting their "spells" and then revive 6 hours later at full hp?

**Comment by KorGgenT** [comment]
so actually, i have a fun note, regardless of this is desirable or not, this will be possible in the near future with a combination of #31983 and #32108

**Comment by TychaiosIlithios** [comment]
Despite my theory below arguing for negative, I think the more stuff is selectable and tweakable via a json setting file - the better.

Believe there's a conflict of choice here on realism vs fun vs balance side. 'Cuz if we go towards realism then such guys as zombie flamers and grenadiers should mostly be extinct for natural reasons, followed closely by zombie scientists suicided by their own drones and zombie technicians that did not catch what they tried to grab.

Side theoretical note - since zombies are likely a result of an experiment-castrated slime strain infecting a host and said strain being taken from a very hitech symbiotic nanobots (what the slime is) - who can guarantee that said nanobots bugged into lightning mutation strain would not  create special organs for accumulating charge?

Alzo the longer development goes and such things as magiclysm appear, the more it seems to be that new energies came to actively be. Maybe some organisms came through and convert known energy to new waveforms to become usable by others, or maybe it's just portals leaking from other dimensions, but it's almost certain that further on it will be even harder to pretend physics only and closer to zangband style pondering on the differences between energies of nether, chaos and lorgus.

**Comment by I-am-Erk** [comment]
Zombies all get essentially infinite energy from an unspecified source, in any form of zombie fiction. Shockers are not special in this regard. In our lore it's because they're all basically gloves worn on top of appendages of a multidimensional organism; they could be drawing energy and matter from their connection.
