### ISSUE TITLE
Armor as weapons?

### ISSUE THREAD

**Issue by NaturesWitness** [CleverRaven/Cataclysm-DDA#3221]
Is it possible to implement a system where unarmed damage can be affected by what you're wearing on your hands and feet?  Like wearing boxing gloves increasing punch damage, and steel-toed boots boosting kick damage.  Ideally, these bonuses would be affected by what combat style you're using as well;  what I'm trying to say is, I REALLY REALLY REALLY want to be able to learn Traubel style, get a Tux, some armored boots, a set of shackles, and go kick zombie ass in STYLE!

PS - If this is confusing anyone, It's a reference to the game "Tales of Symphonia", which had a really cool character named Regal Bryant, who always wore manacles and fought solely with his feet.  His "weapons" were actually armored greaves, since he fought with his feet.  He was (IMO) by far the most fun character to play as in the game, and had a cool story to boot.

Similarly, is it possible to have worn armor provide usable weapons too?  Like armguards with a built in pistol or retractable blade?  Maybe while your wearing them they put a virtual "arm blade" weapon in your inventory you can select?  If anyone here has ever played the roguelike "Gearhead", that's pretty much what I'm thinking of.
##

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
