### ISSUE TITLE
Jousting simulation

### ISSUE THREAD

**Issue by Contemplator11** [CleverRaven/Cataclysm-DDA#32293]
My character has just demolished a group of zombies using an incredibly simple but effective tactics: riding on a motorcycle at 12 km/h past the group, and giving zeds two-three good old pipe spear reach attacks. I noticed that the damage is the same, and my character had no risk of damaging his hand from the impact or flying out of motorbike saddle. That gave me an idea of jousting.

**Describe the solution you'd like**  
Reach attacks made from a vehicle (or a horse) should pose some risk & reward for a player character, adding some damage but checking for strength, dexterity and/or driving skill not to fly out of the saddle or damage your hand.
Reach attacks has always been somewhat cheesy, but stamina somehow fixes it, disabling a player from kiting endlessly. Using a motorcycle for hit-and-run does not use up player's stamina.

**Describe alternatives you've considered**  
Well, vehicles are already very powerful, and giving zombies carmageddon is much less of a hassle than jousting them with a spear from motorcycle, so, this issue can be just ignored.

**Additional context**  
For players who want to roleplay a knight, some rewards for jousting would be nice.

**Comment by EirenexTheDragon** [comment]
Perhaps even just give a huge increase on damage when jousting with decent speed, but with the chance of breaking said spear on impact would be something.

**Comment by YakumoChen** [comment]
the new mountable horses really kick things up a notch with jousting. The only problem is you can't craft an actual lance to joust with.

**Comment by TychaiosIlithios** [comment]
If jousting were a separate flag like weapon couching ability in mount and blade then creating lances would be no problem. 

But if the exact negative consequences from crap reach attack were possibly falling from a mount, trauma or losing a weapon, then it would be justified to implement flags making certain seats/weapons more resistant or even immune to such mishaps. Which sorta kinda leads to a not so minimal job.

What I agree with is cheesiness of reach attacks weapons should jam much more often and all Zs adjacent to point being reached should have a chance to smash a moving object thinking its a limb resulting in weapon damage and chances to drop weapon to the ground. ofc it's proportional to player melee skill, but reach attack as an option is cheesy for newer characters mostly and thus should in theory have it's own problems on newbie stages.

**Comment by kevingranade** [comment]
Some things to consider:
If using something that's not particularly braced like a lance is you would run a significant risk of dropping your weapon to the shock of impact. Also most of these weapons are still going to require moving adjacent to the target, risking a grab or stepping in front of the mount.
When using an actual lance at speed it's virtually impossible to maintain use of the lance after impact. The design of the lance is going to lead to it impaling the target and therefore either breaking, unseating the attacker, or pulling loose from the attacker's grasp.

**Comment by Lorith** [comment]
For once I agree with kevin here - IRL lances were typically single-use weapons that got stuck or shattered on striking, and there would be stockpiles for repeated charges, or you would charge, shatter the lance, then switch to other weapon types.  Curved blades would work well with speed adding damage, but those are prone to issues with you being grabbed, weapon getting stuck, or enemy moving in front of your charge instead of staying to the side like you want.

You may be able to avoid it shattering by making a metal lance, but that would be insanely heavy, hard to use, and still get horrendously stuck, meaning it would still be single-use unless you stopped to remove it from the target.  On the extreme end of the strength spectrum you might be able to impale small creatures with a metal lance and shake them off, but that is talking mutants with maxed out strength and probably the hydraulic muscles too, as that is a hell of a lot of weight for one arm to manage with the center of mass far away from your body to make it worse.
