### ISSUE TITLE
mimic ASCII in tile mode

### ISSUE THREAD

**Issue by Abalieno** [CleverRaven/Cataclysm-DDA#3231]
I'm trying to port ASCII as a tileset so that one can use a good square ASCII for the map, and a truetype font for text, but there are a few hard limits of the tilemode that prevent obtaining a satisfying result.

For example for what I understand, when there's more than one object in one spot, in ASCII mode you see the character corresponding to the first item, and then the background lit blue so that you know it's a pile of object you're staring at.

This isn't possible in tile mode, because you can only draw the tile, and not manipulate colors like in ASCII.

So I thought, would it be possible to do a small modification to the code so that, when there's more than one object, you draw the first object as in ASCII, then use the transparent mask, and under it you print some special tile called something like "more stuff", so that whenever you see an object drawn on top of that special type then you'd know it's again a pile of objects instead of just one?

That would allow to retain ASCII feature in tile mode and let me properly model a decent ASCII tileset.
##

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
