### ISSUE TITLE
Rechargers don't Recharge

### ISSUE THREAD

**Issue by MiguelANunes** [CleverRaven/Cataclysm-DDA#32319]
# Describe the bug

Vehicle recharging stations should recharge batteries and UPS devices, as the description implies, however when said items are placed inside an active recharging station nothing happens.

# Steps To Reproduce

1. Get a functioning recharging station and some batteries
2. Install the recharging station on a vehicle that has power and turn it on
3. Put the batteries inside the recharging station and wait a bit
4. The batteries will not recharge

# Expected behavior

The batteries to be charged when inside the recharging station.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-5457-g40e3a64 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Bens GF recipes [Tolerate_This],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Garden Pots [growable-pots],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Hydroponics [hydroponics],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Classes and Scenarios Mod [more_classes_scenarios],
    Sleep Deprivation [sleepdeprivation],
    SpeedyDex [speedydex],
    StatsThroughSkills [StatsThroughSkills],
    sees-player icon, -attitude [sees_player_less_attitude]
]

# Additional context

In my case the frame where the recharging station was installed didn't have any power source, however it was connected via jumper cables to one that did.

**Comment by gavin1337** [comment]
do you have a dashboard installed onto the vehicle that contains the recharging station? said station needs to be turned on manually via a dashboard or electronics controls in order to be turned on and function.

**Comment by MiguelANunes** [comment]
Yes it does, and it is flicked on.

**Comment by gavin1337** [comment]
could you please upload your save file?

**Comment by MiguelANunes** [comment]
[Here you go](https://github.com/CleverRaven/Cataclysm-DDA/files/3384184/Kings.Canyon.zip)

**Comment by gavin1337** [comment]
I was able to get it charging, 
I believe the issue is that you have too many batteries charging off of your solar grid, I don't know if it's an intentional design choice but it appears as though that your cables will only run charge to other devices once the batteries in your solar panel vehicle are fully charged. Your lights were able to be turned on because...I don't know why. 
You also need some type of battery in your charging station because, I'm guessing that it's programmed to feed only from batteries installed from the charging station and not from jumper connected objects.

![image](https://user-images.githubusercontent.com/15938735/61090506-8d5cbb80-a404-11e9-9879-f3f25bf8767e.png)

![image](https://user-images.githubusercontent.com/15938735/61090513-951c6000-a404-11e9-9f55-532a71ac8be4.png)

before and after for the items in your charging station after I fixed it by installing/uninstalling some extra batteries in your two objects

![image](https://user-images.githubusercontent.com/15938735/61090552-b3825b80-a404-11e9-9583-ec18a563ef6c.png)

your solar panel (above) and your charging station (below)

![image](https://user-images.githubusercontent.com/15938735/61090558-bf6e1d80-a404-11e9-8f7f-9f3324d34f7f.png)


you either need to wait for all of those batteries to charge in your main station, uninstall your batteries and install them on a different rig in parallel to your charging station, or you could just install a solar panel and a small storage battery and take your charging station outside to charge them from its own personal supply.

**Comment by MiguelANunes** [comment]
Well that's interesting.
If this is an intentional design choice it sure is quite odd, however it does seem like an oversight from whoever programmed the charging stations. Anyhow, thank you very much for your help, it is very much appreciated.
