### ISSUE TITLE
Previous mission objective direction isn't shown after completing another mission.

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#32362]
# Describe the bug

I have acquired the mission to reach the refugee center. It made a red "arrow" appear on both map and minimap that denotes the direction to the objective.

After that i've acquired and completed a couple of hub01 missions. After i finished the last one, there's no longer the "arrow" that directs me to the refugee center objective, making reaching it cumbersome. Selecting the mission again in `M` window with `Enter` does nothing. This state is preserved over saving/loading the game.

[2019.07.09.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3388992/2019.07.09.zip)

070b9e9606f6063dd1df00d071b272d8f57ce3c9

**Comment by mlangsdorf** [comment]
I loaded the save game and opened the map, thereby reproducing the issue:
![NoMarker](https://user-images.githubusercontent.com/8007405/65333588-68b05d00-db86-11e9-9903-8eb882f03d61.png)

Then I scrolled the map so that information for my current location wasn't obscuring the map marker pointing to the refugee center to the NE:
![NoMarkerOhWait](https://user-images.githubusercontent.com/8007405/65333666-867dc200-db86-11e9-9e35-42b8472c7397.png)

I'll see if I can offset the current location information box by 1 line and 1 character so it will almost never obscure the marker.

**Comment by l29ah** [comment]
Probably a better (but a little ugly) solution will be to draw the marker over the information box.

**Comment by mlangsdorf** [comment]
I have to say, the offset corner box looks fine to me.
