### ISSUE TITLE
QOL Improvements for Boating re: Weight Limit

### ISSUE THREAD

**Issue by joe9000** [CleverRaven/Cataclysm-DDA#32367]
**Is your feature request related to a problem? Please describe.**  
Adding any weight beyond the maximum float weight instantly sinks the boat, which produces uninteresting outcomes like hauling a fish you caught into the boat's storage and having the boat immediately sink.

**Describe the solution you'd like**  
1. Add a "Are you sure you want to store this? It will make you immediately sink. [y/n]" warning message when you attempt to store something in the vehicle that would exceed the vehicle's maximum floatable weight

2. Replace or supplement the "swims" and "leaks" text in the wheels/boat section of the examine vehicle screen with plus/negative amount of weight left to add/remove to make the boat sink/float. E.g. if you're 5lbs from sinking it would say "swims (5 lbs)" in blue or if you're one hundred pounds from floating it would say "leaks (-100 lbs)" in red. Combined with the weight readout when installing a new part you'll be able to see whether it would exceed max float weight. 

**Describe alternatives you've considered**  
1. Flooding. Once the float weight is exceeded, the boat begins to take on water. As more weight/water comes in, the rate of flooding increases until the boat reaches a maximum water level and founders/sinks/vanishes. This would give the player time to lighten ship, run aground, or go down with their ship. Flooding would gradually decrease on shore.

2. Bilge pumps. When activated they consume power, but effectively increase the maximum floating weight up to a throughput threshold. Water and weight over that threshold overwhelms the bilge pumps and you begin to flood as in 1, but at a slower rate while the bilge pumps are still pumping.

3. Submersibles. Drive on the "bottom" of deep water as long as you've got a means of propulsion that isn't disabled by being submerged. So electric engines or a snorkel part added to the engine a la muffler. Could do an actual stays-dry sub or one that floods and the player needs a respirator to avoid drowning. Periscope part would let you see from the perspective of shallow water/sea level.

**Comment by TychaiosIlithios** [comment]
Problem is that whole naval (and naval vehicle) side is asking for a huge rewrite - it's sorta kinda hard to draw a line where desired minor patches turn into full scale update. Depending on the type of update that the dev chooses possible surface buoyancy will be subject to becoming a part of a more or less complex system. 

Imho it's optimal to keep surface flotation part binary until someone kamikazes into a big rewrite, 'cuz whole set of maritime calculations for basically a can floating or a can taking water is more boring than worth the coding time, so for the sake of argument the counter proposal is to imagine that all possible flotation is based on sealed air cans and bags and all complex vehicle parts have flags that make them work or cease to work or even break when submerged. Instead of ever implementing sealing mechanics, add locations with breathing pipes where a person can inhale (possibly drivers seat and few slots outside) - and voila with a couple of gadgets like airbags and vertical steering the whole thing can work submerged. 

Alzo with such view of submerged mechanics it becomes possible to have long term works underwater, which make it feasible to recover drowned wrecks, thus no more need to desintegrate whatever drowns, once again without a lot of complex stuff like calculating replaced cubic meters. 

This way there's no need to instantly implement exact psi/meter stuff, just mention it, add cans of compressed air used 1 unit per turn of breathing compressor and 300 units per airbag when car tries to go up a level - and here ya go, as long as the binary max lift minus weight switch is positive or whoops titanic becomes das boot if airbag got bitten by a swimmer and parameter went negative.

**Comment by joe9000** [comment]
i agree, leave the floating/sinking binary around a particular total weight. quality of life would be better if you had a warning before you were about to switch from floating to sinking though, since as far as i can tell there's no way to know what your max weight is except adding weight until it changes to leaks
