### ISSUE TITLE
Suggestion: Cooking recipes with Cannabis to make edibles

### ISSUE THREAD

**Issue by Ravor9933** [CleverRaven/Cataclysm-DDA#32393]
**Is your feature request related to a problem? Please describe.**  
I think it would be cool to add cannabutter that can be used as a replacement for regular butter that would produce cannabis versions of the recipe

**Describe the solution you'd like**  
You would need to make cannabutter using butter (or maybe lard/fat/oil), a pot, water, and, of course, a good amount of marijuana and you cook it at a hotplate or its alternatives. Cooking skill of 2 probably 

When you consume the cannabis infused food you will get a hidden status effect that lasts about half an hour to simulate the onset time of edibles (these aren't doing anything for me, why don't i take TWO). When the effect hits, it is more potent and much longer lasting than regular joints, maybe even works decently well as pain relief. However, if you take too much, then your movement and intelligence drop significantly, to simulate the "couch lock"

**Comment by CafeineCawfee** [comment]
Might try my hand at this.

**Comment by TychaiosIlithios** [comment]
Actually before learning to smoke this thing many countries like Russia were home to vast amounts of low quality herb, mostly used for rope making and fabrics, side part - oil production. Such oil is officially listed in a large number of 1940- books as a flavor to add to bread for fish baiting. 
On people this oil was mainly used for cold/stiff muscle massage and food cooking. No side effects or overdoses ever mentioned. But that is once again due to the fact that northern plant never fully matured into high 'sweetness' nor was subject to selection for drug quality. 

Based on this, not sure that all cannabis based products should be drug related, some of them might actually be quite healthy and useful, heavily dependant on how it's grown and cooked.
