### ISSUE TITLE
bikes or anything that uses muscle power drain stamina way to much

### ISSUE THREAD

**Issue by sammy202020** [CleverRaven/Cataclysm-DDA#32398]
its not such much a bug. its more that currently bikes are worthless since you cant even go 4 mphs on them without your stamina draining. 

# Steps To Reproduce

1. find a bike
2. ride the bike at 4 mphs or higher
3. watch the stamina bar drain. 

 - OS: Windows 10
 - Game Version: 0.D-5622-g3d4a952 (tiles)
 - Graphics version: Tiles
 

a solution could be is reduce the drain of muscle powered stuff to a point you can maintain atleast a slow speed on bicycle.  this has been an issue since the change to stamina.

**Comment by TychaiosIlithios** [comment]
hmm not yet balanced to 1sec turns?

**Comment by sammy202020** [comment]
> hmm not yet balanced to 1sec turns?

im guessing not since i cant even go 4 mph. but i think this is more of an issue caused by the change to stamina recovery rate

**Comment by l29ah** [comment]
It's still an issue. An untrained person can keep 25kph on a road bike on an asphalt indefinitely (well, at least an hour) IRL, but it's not the case right now on a Bicycle even with 10str: the player runs out of stamina after two minutes of such a ride.

**Comment by kevingranade** [comment]
We do not have precise representation of bicycle performance as a goal, if
there is *a* cruising speed that is stamina-positive, that is sufficient.
The Mph figures are pretty much just made up anyway since time/distance etc
isn't precise.

**Comment by M1nks** [comment]
I can see that this issue has been closed but as the previous poster said, this really hasn't been fixed.  I've actually been looking around for a Mod which removed Stamina entirely.  I don't want to do it but I was just forced to reinstall Cata due to a bug and after a few very frustrating hours of play on my rowboat and my bike, having to stop every few minutes or so to rest for about 8 minutes, my sense of !FUN! has reached it's limit.  This is a game breaker for me.  I have to cheat to be able to play, I can't bear it otherwise.
