### ISSUE TITLE
Magic progression is very RNG dependant

### ISSUE THREAD

**Issue by Lazasar** [CleverRaven/Cataclysm-DDA#32402]
I know its early days yet with the mod, but right now there is no way to reliably develop a magician, at least early-mid game

I have been to 3 bookstores 2 libraries and 3 schools, and al I have to show for my trouble is a scroll of Flesh Pouch a Dummies Guide to Necromantic Summonings (or something like that).

It makes sense that high tier spell books should be found in Labs (or similiar) just like mutation recipes, but there should be some reliable way to find the low tier spell books and/or spell scrolls to benefit from the low-level spells earlier in the game.

**Comment by KorGgenT** [comment]
i'm working on some dungeons to add in spellbooks. labs will not be where endgame magiclysm content is; and the regular books stores aren't great places for magic books. you ought to look for the magical locations: magic basements, used bookstore, magic shop, magic cabin. 

i'm going to close this issue because it's just asking for vague content, and i'm writing it as fast as i can.

**Comment by Lazasar** [comment]
Sorry to re-open, but in terms of your answer - Magic shops seem to spawn really rarely. Never seen a Magic Cabin, user bookstore or magic basement.
