### ISSUE TITLE
Horse sounds lag the game upon dismounting

### ISSUE THREAD

**Issue by chaoticidealism** [CleverRaven/Cataclysm-DDA#32463]
# Describe the bug
When you ride a horse for a long time and then dismount, the game lags massively to the point of freezing, depending on how long you have been riding. After riding a couple of map screens worth of distance, I dismounted, the game froze for a couple of minutes; then I got a message that said "You hear footsteps. x1559952" and the game resumed.

# Steps To Reproduce

1. Tame horse.
2. Ride horse for a long distance.
3. Dismount.

# Expected behavior
Game shouldn't lag severely.

# Screenshots
![Screenshot_2](https://user-images.githubusercontent.com/7295004/61419316-baf5a900-a8cb-11e9-8c4d-ef2a35c50450.jpg)

# Versions and configuration

- OS: Windows 7
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-5703-g850f19c [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Generic Guns [generic_guns],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Mutant NPCs [mutant_npcs],
    Mythical Martial Arts [MMA],
    No Flaming Weapons [no_flaming_weapons],
    Classes and Scenarios Mod [more_classes_scenarios],
    Manual Bionic Installation [manualbionicinstall],
    Safe Autodoc [safeautodoc],
    StatsThroughSkills [StatsThroughSkills],
    Mythological Replicas [nw_pack],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots]
]

# Additional context

**Comment by jeremyshannon** [comment]
Just encountered this in current experimental, toying around with horseback riding.  Whenever I'd dismount he would zip all over the place in an instant, as if he had stored up all the moves that he didn't make when I was riding him.
 I made a circle around a large city (which was fun, dodging zombies left and right) and at the end, off to one edge of the city, with no zombies in sight, I dismounted to see how many "you hear hoofsteps" events I'd get. Well, I guess he could see a zombie or something, because he ran. And I mean HE RAN, like to the edge of the reality bubble in a single tick. It was as if he had vanished from the ken of man. I couldn't find him.
 Obviously horses have Time Dilation CBMs.
