### ISSUE TITLE
NPCs become hostile immediately.

### ISSUE THREAD

**Issue by BBlankie** [CleverRaven/Cataclysm-DDA#32475]
It seems that every random npcs (and 2 scavenger bunker merchants) that i encountered becomes hostile whenever they saw me.

I tested this on a different character. Even with Glorious mutation, lots of speaking and intelligence, And on the second test, having no mutations. They call me a "Maniac" and always react with attacking me or fleeing.

**Comment by EirenexTheDragon** [comment]
If you use the same world ,it wouldnt suprise me that they still stay hostile. reset and try again without any mutations.

**Comment by BBlankie** [comment]
I'm not holding anything.

Eirenex, I meant every new npc that i encountered, becomes hostile instantly the moment they see me without me having a chance to talk with them.

**Comment by ShinWinddreamer** [comment]
I have the same problem in my current save. Every NPC i encounter are hostile to me. Saying something like :"fuckit, a maniac!" or "Is this Reno? Because I need to watch you die!". 
The most macabre thing: My own faciton NPC's, people i rescued from cannibalism, consider me their bestest friend with trust and best status etc came back from a task from my faction quarters and started to fire their composite crossbows at me whenever they see me. I can still send them out to upgrade the faction headquarters but it's kinda pointless with me being unable to approach NPC's. 
I can only assume it's bugged as I tried various things to get around that problem. Deinstalling my CBM's, giving me mutations/traits that make me pretty or otherwise able to better socialize and still the same issue, even with freshly spawned, resetted NPC's. PLease PLEASE help me because recruiting peeps and building a fortress in the ending world is my current characters mission and i find it very compelling with each char to do.
