### ISSUE TITLE
Better OSX installation experience

### ISSUE THREAD

**Issue by dbackeus** [CleverRaven/Cataclysm-DDA#3249]
Heard about this project for the first time yesterday. Downloaded 0.8 SDL for OSX and tried to run it but had quite a few stumbling blocks on the way.

First of all `libintl.8.dylib` was not found. Running `locate` I stumbled upon that very file inside my Adobe Flash CS6 application and managed to symlink it to the expected location. If I had not found it in Flash I would have had no idea how to proceed.

Next up were cryptic messages about not finding SDL packages (main, image and ttf) which I first tried to install through `brew` which didn't help. Then googled the packages and did manual downloads finding out in the readme where to copy the files.

In the end I got it running but I'm still not seeing any tiles graphics so not sure what's up with that.

Had I not been an experienced mac user with development experience I would probably have never got it running.

I would love to help out with this experience. At least adding some helpful error messages to the launcher script if anything is missing. Best case scenario would be to automatically download and install the missing files or bundle them with the download.

Who can I talk to about helping out with this? I didn't find the OSX specific files inside the repo...
##

**Comment by qbradq** [comment]
Since there still isn't a downloadable MacOS SDL bundle can we apply the label "Enhancement"?

**Comment by narc0tiq** [comment]
@qbradq Sounds good to me. Thank you :+1:

**Comment by dbackeus** [comment]
There is a homebrew formula for compiling Cataclysm these days.

Stable release is easy to install, however compiling form HEAD fails as it's unable to locate `SDL.h`.

Anyone have any clue regarding this?
https://github.com/Homebrew/homebrew-games/issues/496

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
