### ISSUE TITLE
New "foldable" vehicle - Wheelie bike

### ISSUE THREAD

**Issue by NaturesWitness** [CleverRaven/Cataclysm-DDA#3251]
Been thinking about this for a while, would it be possible to build a 1-square mini motorcycle?  We could have a similar system to the folding bike, where you can turn it into an item to store it.  The only snag is, we'd need code to store how much gas is in the tank, which I don't think the folding bike code has.  Is this doable?  Or is it too silly for Cata?

EDIT - Actually, could we just set it so when it gets folded, the gas in the tank is converted to charges on the folded bike item?  That way, you could refill it even while it's folded for storage.

PS - If anyone doesn't know what this is http://kirby.wikia.com/wiki/Wheelie_Bike
##

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
