### ISSUE TITLE
Trying to buy stuff from a NPC results in negative volume and his refusal

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#32531]
# Steps To Reproduce

1. Load the saved game.
2. Try buying `gallon jug of bleach` for a `lighter` from the nearby NPC.
3. `Denisha 'Moonstruck' Abbott, Survivor can't carry all that.`

# Versions and configuration

0.D-5749-ga24f3b03bf-dirty

# Additional context

[2019.07.17-2.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3414672/2019.07.17-2.zip)

**Comment by DanteTorn** [comment]
I just had this issue, and there is a way to fix it if it's on one of your NPC followers:

1. Unequip all your NPC's clothing that has carry volume, forcing them to drop all their stuff as well.
2. Re-equip the pieces you just took off.

The issue seems to be that you can hand an NPC more stuff than they can carry, but for some reason trying to trade that stuff back off of them doesn't calculate that the trade is bringing them under their max carry weight.
