### ISSUE TITLE
Lab cloning vats do not preserve contents

### ISSUE THREAD

**Issue by 81Denton** [CleverRaven/Cataclysm-DDA#32568]
# Describe the bug

The cloning vats found in labs do not preserve their contents. Due to that, the mutated body parts inside will rot away before most players enter laboratories. The only exemption to this are cold labs.

# Expected behavior

Post-cataclysm labs still provide power to the vast majority of their systems, like containment, autodocs, centrifuges, nano labs and so on.
IMO it would make sense that cloning vats preserved their contents, as they'd still be powered like the rest of all systems.

# Versions and configuration

 - OS: Win 10 x64
 - Game Version: 0.D-5805-g50eb478
 - Graphics version: Tiles
 - Mods loaded: dda, disable NPC needs, no fungal monsters

**Comment by FuelType-Memes** [comment]
I agree. But maybe while power is still provided, there might be problems with providing fresh nutrient sludge, filtration or oxygenation

**Comment by 81Denton** [comment]
That's true, I can also imagine that cloning vats aren't system you can leave unmonitored for weeks or months.

**Comment by kevingranade** [comment]
I can see it providing extended preservation but not indefinite. If nothing
else the environment is probably sterile and you will not have rot until
bacteria can work their way in around seals.

**Comment by EddiTheBambi** [comment]
> I agree. But maybe while power is still provided, there might be problems with providing fresh nutrient sludge, filtration or oxygenation

I think it's a plausible assumption that the (still powered vats) are kept quite cold, close to freezing, thus extending the life of the samples considerably, this also prevents addition of additional systems and AFAIK only requires a change in the vat furniture to reduce the temperature on the tile.

**Comment by kevingranade** [comment]
> Post-cataclysm labs still provide power to the vast majority of their systems, like containment, autodocs, centrifuges, nano labs and so on.

This is not intended to be a thing that continues, all non-emergency systems should be shutting down.

**Comment by EddiTheBambi** [comment]
> This is not intended to be a thing that continues, all non-emergency systems should be shutting down.

Could it not be assumed that labs have an automated nuclear reactor supporting systems in case of a national (or international) crisis in order to keep science moving forward? Maybe we could have labs gradually turn radioactive as waste builds up and automated systems start to fail or deteriorate without the regular pre-cataclysm maintenace.

I don't think cutting out power is viable from a gameplay perspective considering the commitment required from the player to produce enough power to get the machines online again. While jury-rigging solar panels and pulling wires from the surface to power various machinery is a neat idea, maybe there could be other tradeoffs to dealing with labs? Especially considering the planned introduction of mechs and the suggested lab-based recharging method for the late-late game when all non-emergency systems would be out.

**Comment by kevingranade** [comment]
> Could it not be assumed that labs have an automated nuclear reactor

No

> I don't think cutting out power is viable from a gameplay perspective considering the commitment required from the player to produce enough power to get the machines online again.

Why? You want them to just stumble into a perfectly preserved treasure trove of equipment and power? Either the player invests in getting things running, or they only scavenge what they can take with them.

> Especially considering the planned introduction of mechs and the suggested lab-based recharging method for the late-late game when all non-emergency systems would be out.

That's exactly the kind of thing the player should invest effort to achieve rather than just having it fall into their laps.

**Comment by EddiTheBambi** [comment]
> That's exactly the kind of thing the player should invest effort to achieve rather than just having it fall into their laps.

On second thought I agree with that. Would the above issue be best achieved with a "preserves" modifier to the cloning vat furniture then or perhaps creating a deployable "cloning vat" container that takes mutated flesh items?
