### ISSUE TITLE
UI shows tools that don't exist when continuing crafting food item

### ISSUE THREAD

**Issue by dissociativity** [CleverRaven/Cataclysm-DDA#32601]
# Describe the bug
UI shows tools that don't exist when continuing crafting food item as pictured, pressing enter appears to pass a turn, progress is made on the item

Save here: [https://drive.google.com/file/d/13URucCjxpju2njthHwUsBiyiR9i20Ujv/view?usp=sharing](url)
# Steps To Reproduce

1: load my save
2: light fire
3: 'a'ctivate the roasted acorns in progress in player hands
4: have screen pictured appear
![image](https://user-images.githubusercontent.com/40927483/61840378-4d9dd580-aed4-11e9-885d-35d2ab268965.png)

# Expected behavior
Item crafting as per normal

# Screenshots

**If applicable**, add screenshots to help explain your problem.

above

# Versions and configuration

9368, latest build as of 25/07/2019 12:05PM GMT 10+ windows tiles x64
 - Mods loaded: [both mods that add more survival tools, medieval items, all location mods, graphical indicators]

**Comment by glenmack** [comment]
I've also seen this "options" screen, I think specifically in cases specifically where a fire runs out? It was a while back so calling on old memories.

**Comment by dissociativity** [comment]
Yeah, that would make sense as it's raining

**Comment by ProfoundDarkness** [comment]
I'm playing with this one a bit.  BTW I also get the incorrect menu item on loading this save.

**Comment by AlexMooney** [comment]
I got this to happen on cdda-jenkins-b9853 (Nov 2nd).  I was cooking with fire but had integrated toolset available, and the fire ran out.  When I resume the crafting, I get a list of everything.

![image](https://user-images.githubusercontent.com/8269566/68074405-e3f55900-fd57-11e9-823d-0bb8323b147f.png)

Integrated toolset is at the bottom of the list, showing charges correctly.

**Comment by AlexMooney** [comment]
This is the same bug as https://github.com/CleverRaven/Cataclysm-DDA/issues/33746 and https://github.com/CleverRaven/Cataclysm-DDA/issues/32050.  I believe the key to reproducing the issue is to lose your initial cooking source but to have another valid one available.

**Comment by davidpwbrown** [comment]
Can no longer reproduce on latest master, either with the provided save, or with the other situations that alexmooney suggests was perhaps the original cause.

**Comment by davidpwbrown** [comment]
Just happened to me on a new world I started, happened when fire went out during crafting of cooked fish, then restarting the craft after restarting the fire, didnt need to move anywhere or do anything else.

And yes, there was a charcoal smoker nearby aswell.

**Comment by jbytheway** [comment]
I think I've figured out roughly what's causing this.  roasted acorns only require 5 charges, and only 5% of the charges are consumed each step of the craft, so if your craft is interrupted sufficiently close to the end then it might only need zero charges to complete.

When the code calculates the things on the map with availability, it scales down the value according to progress, here (via the call to `charges_required_modifier`):
https://github.com/CleverRaven/Cataclysm-DDA/blob/57b7dbe7c789ded9720f96fbe05251dff30f8b0a/src/crafting.cpp#L1632

But later, when it's assembling the UI, it doesn't, so the UI shows the requirement for the full craft, even though you won't actually be using any charges this time:
https://github.com/CleverRaven/Cataclysm-DDA/blob/57b7dbe7c789ded9720f96fbe05251dff30f8b0a/src/crafting.cpp#L1677

Note that in both the screenshots above, the total number of required charges is small (in particular, less than 20), which is consistent with this hypothesis.

So, the key to reproducing this issue is to have a craft which uses very few charges, and interrupt it very near the end.

If this is true, the fix is to skip those tools for which no more charges are needed when choosing tools for a resumed craft.

**Comment by jbytheway** [comment]
I have indeed managed to reproduce the issue in this way, so I'm now confident that's the source of it.  Specifically:
* Light a fire.
* Craft a single roasted acorn.
* Interrupt the craft at some point after 80% progress.
* Put out the fire.
* Activate the craft to resume it.
* Observe choices of all items.

On reflection, I've also thought of a simpler fix: always search for at least one charge, even if the recipe doesn't really need it.  This will be a very small, low-risk change.  The only down side is that it will require the player to have charges that don't actually get used, which may annoy people in some cases.  However, we actually already do that in some situations, due to the way craft charge uses get rounded, so it's not really making the problem much worse.  I hope to be able to draft a PR with that simple fix tomorrow.
