### ISSUE TITLE
Season stuck on default 15 days.

### ISSUE THREAD

**Issue by TechyBen** [CleverRaven/Cataclysm-DDA#32610]
Seems season length stuck on 15 days. I have thus had lots of strange results... (anything time based on season length was confusing me, till I noticed). Is set to 91 days on would options. Though I cannot remember if it was changed after world spawn/creation. I think I had it from creation/generation as 91 days.

Latest build, Windows 7, Tiles. Mods are the usual stuff, More survival tools, Stats through skills, NPC needs off, etc.

**Comment by DeeUnderscore** [comment]
I noticed some weirdness, wherein I can load the game repeatedly and it will assume seasons are 15 days long, but if I go into the settings menu to check on the season length, save, and load it again without exiting the game, it will load with the correct season length. It's almost like the season length is cached somewhere and the cache is not populated correctly until I look at the settings screen. 

This is with 0.D-5942-g666b2ec9ec

**Comment by TechyBen** [comment]
Yeah. I did swap back for one moment. But then the save settled in at the new date/lengths.

**Comment by DeeUnderscore** [comment]
Looks like the cached values are populated on options load, which means they take the value from the global config, instead of from per-save worldoptions.json. They're also populated when exiting the options config screen, regardless of whether or not you've changed anything, so that's why you can change the effective season length by just looking at the options screen.

I'll see if populating the caches at world load solves the issue, since at that point the active world is set and the per-save world options are overlaid on global options. I'll open a PR if it does.

If you want a quick workaround in the meantime, make sure that the default world options are set to your desired season length.
