### ISSUE TITLE
Friendly NPC won't wield another weapon after the current one was "traded" away from it

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#32613]
# Steps To Reproduce

1. Load the game.
2. Give the NPC a hatchet instead of his makeshift crowbar.
3. He wields nothing.
4. Try giving him a replacement weapon via `g: I want you to use this item.`.
5. He says his weapon is superior.
6. Spawn a fat zombie near him.
7. Observe him dealing no damage to the zombie.

# Expected behavior

NPC picking the best weapon from his inventory if he holds nothing and sucks at unarmed fighting.

[2019.07.22-buggy.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3432396/2019.07.22-buggy.zip)

0.D-5829-g4a400484d3-dirty

**Comment by TychaiosIlithios** [comment]
I recently had similar stuff - npc had compound bow, traded away, tried to make him use a spear - said it sucked in comparison to mega points from the bow. Cured by reentering the game.

But in regard to your referenced unarmed - good point to mention yet again, should npc master unarmed it becomes extremely hard to convince him to train any other sort of weapon, like a proper pike for proper formation reach attacks.

**Comment by kevingranade** [comment]
This looks like a caching error from my npc perf work.

**Comment by ipcyborg** [comment]
Tested in 0.D-6301-g3597e0f.

>2. Give the NPC a hatchet instead of his makeshift crowbar.
>3. He wields nothing.

Give hatchet using `Hold on to this item` and then remove makeshift crowbar using `Trade`. NPC wields nothing.

>6. Spawn a fat zombie near him.

It really depends on the distance from NPC to a zombie. 
If it is close enough (=1),  NPC goes unarmed, because `wield_better_weapon` is not called at all.
But if the distance is more than 1, NPC correctly selects a hatchet.

Another test:

>4. Try giving him a replacement weapon via g: I want you to use this item..

Works fine if you try to give a shotgun to an NPC at this step: changes makeshift crowbar to shotgun.

So the issue here seems to be avoiding of using `wield_better_weapon` when the monster is too close. 
Also we have to consider the time required to wield a weapon: may be in some specific cases it would be better to remain unarmed?

**Comment by l29ah** [comment]
> Give hatchet using Hold on to this item and then remove makeshift crowbar using Trade. NPC wields nothing.
No, i meant trading makeshift crowbar for hatchet.

**Comment by kevingranade** [comment]
NPCs only periodically re-evaluate what weapon they are wielding, the
process if them obtaining or losing items should probably either force a
new evaluation or at least reset the cache that they're using.

**Comment by zt1415926** [comment]
> Tested in 0.D-6301-g3597e0f.
> 
> > 1. Give the NPC a hatchet instead of his makeshift crowbar.
> > 2. He wields nothing.
> 
> Give hatchet using `Hold on to this item` and then remove makeshift crowbar using `Trade`. NPC wields nothing.
> 
> > 1. Spawn a fat zombie near him.
> 
> It really depends on the distance from NPC to a zombie.
> If it is close enough (=1), NPC goes unarmed, because `wield_better_weapon` is not called at all.
> But if the distance is more than 1, NPC correctly selects a hatchet.
> 
> Another test:
> 
> > 1. Try giving him a replacement weapon via g: I want you to use this item..
> 
> Works fine if you try to give a shotgun to an NPC at this step: changes makeshift crowbar to shotgun.
> 
> So the issue here seems to be avoiding of using `wield_better_weapon` when the monster is too close.
> Also we have to consider the time required to wield a weapon: may be in some specific cases it would be better to remain unarmed?

Before you spawn the zombie far from the NPC, it is very possible that you have reentered the game, so the NPC re-evaluate what it is wielding and choose the hatchet. So, it has nothing to do with the distance I guess. It is certainly fine if you try to give the NPC a shotgun to replace the makeshift crowbar, because the shotgun is evaluated as a better weapon. But what if you try to replace the shotgun with a makeshift crowbar? The NPC will refuse to wield it. And it will refuse to do so even after the shotgun is traded away unless you reenter the game.
