### ISSUE TITLE
Cash Card "Realism"

### ISSUE THREAD

**Issue by glenmack** [CleverRaven/Cataclysm-DDA#32635]
**Is your feature request related to a problem? Please describe.**  
Cash cards are a pain to manage in terms of getting money onto one card, making sure you don't melt that card down and are weirdly abstracted with no protection or associated ID. Finding cash cards and a vending machine in a lab escape mostly sorts food, and takes most of the urgency out of the scenario.

**Describe the solution you'd like**  
- Add cash deposit option to ATM machines; old world cash gains value.
- From @TechyBen Contactless use up to $30 ask for pin thereafter. Spawn cards (no pin) or cards and smartphones found together could be used with a "pingit" app to allow money transfer between cards. (Real thing in the UK) or wallets with 4 digit codes scratched inside, scraps of paper for forgetful people. **Swapped from my suggestion about hacking**
- Make some APV's (all purpose vouchers) that can be freely redeemed at ATM for cash or credit. ($10 - $50 increments); simulates gift cards and allows player to at least gain some cash.
- Make "personal cash card" a separate item, either bought from ATM, or recoded to you by e-ink tablet; withdrawn money always goes here and this item is not used in recipes, this separates it from blank cash cards that can be melted down.

**Comment by ZhilkinSerg** [comment]
Сurrent implementation has little to do with realism, but your suggestions, while adding to gameplay, aren't improving realism either.

**Comment by glenmack** [comment]
> Сurrent implementation has little to do with realism, but your suggestions, while adding to gameplay, aren't improving realism either.

Noted, I'd still say this abstraction is closer to reality than the current system.

**Comment by TechyBen** [comment]
Limits could be put on the cards. For example, IRL "contactless" payments are limited to $30 in the UK for example. Not sure what it is in US. So buying from a vending machine would still be possible without a pin/signature, but would be limited to 3 - 5 purchases, and ask for a pin after.

Hacking pins is not a thing IRL (or extremely rare), AFAIK. You find it written down in a wallet/purse. So we could spawn "card no pin" which can make a few small purchases, or "card with scrap of paper with pin" which would allow unlimited purchases, for example.

Phones could also have payment apps, but IRL most of these are also massively secured, and pin/authentication attacks are opportunistic in nature.

**Comment by Fris0uman** [comment]
Cash card are not supposed to be credit/debit card, that's why there's no pin on it. They are basically digital purse. But they could still do with a bit more depth.

**Comment by kevingranade** [comment]
Cash means cash, it works like cash.  I'm not sure how to make this any more clear.
There is not some network connecting banks and ATMs together, that is *gone*, so that is the only form of digital money that would continue to work.

As such:
``Add cash deposit option to ATM machines; old world cash gains value.``
This would only work at that particular ATM. The ATM itself would have an updated bank balance, nothing else would.
``Contactless use up to $30 ask for pin thereafter.``
This is an implementation detail of contactless payment security, there is no reason for us to model this unless we want to add a minigame for locking cards behind a guessing task or minigame. (I don't want to do that).
``smartphones found together could be used with a "pingit" app to allow money transfer between cards. (Real thing in the UK)``
That kind of thing works because the cards themselves do not store money, DDA cards DO, so this would not work.
``Make some APV's (all purpose vouchers) that can be freely redeemed at ATM for cash or credit. ($10 - $50 increments); simulates gift cards and allows player to at least gain some cash.``
Seems like kind of a hassle for no reason? Just add more cash cards. I might be missing someong about the proposal.
``Make "personal cash card" a separate item, either bought from ATM, or recoded to you by e-ink tablet; withdrawn money always goes here and this item is not used in recipes, this separates it from blank cash cards that can be melted down.``
There's already a workaround for this, which is to favourite your cards.  If this doesn't work we can look into fixing it. I'm against re-introducing any kind of item that gets special treatment like this.

Counter-proposal, replace cash cards with physical money, transmogrify all existing cash cards into cash + valueless plastic cards, and only spawn either valueless plastic cards or physical cash moving forward.  ATMs and vending machines would then ONLY transact with paper money.

**Comment by TechyBen** [comment]
So basically (for game mechanical purposes of making the cash card easy to use instead of the player micromanaging individual pennies/cents) the CDDA "cash card" is a type of escrow(?) deposit card similar to a cryptographic coin (bitcoin) that by itself has value, and is not in an individual's account. :+1: 
(As an example, AFAIK, if you had a bitcoin on a usb stick and no password, anyone could spend it if they had the usb stick)

**Comment by glenmack** [comment]
>Cash means cash, it works like cash. I'm not sure how to make this any more clear.
There is not some network connecting banks and ATMs together, that is gone, so that is the only form of digital money that would continue to work.

Translation;
We decided to abstract cash into this system; but we kept ATMs to give the illusion that it works like cash. In fact the ATM's are another abstraction that only serve to function as a point for the survivor to move money between the arbitrary system of cards. We're sure no one in the fictional society would be supremely pissed at a system where you had to drive into the city centre, find a bank, grocery store or gas station and use these machines to move $5 between your card and your spouses because there is no account or network system system, and no way to transfer money between the cards in a sensible manner.

So no, it works nothing like cash. As individual cards and amounts can't be divided in smaller sums, or amalgamated easily, like notes and coins.

Making your card a favorite works only to stop it being used recipes, it doesn't stop all the cards with cash being stacked on top of it, and amalgamating the amount. Making it impossible to tell how much floating money you have in the non favorite cash cards.

**Comment by kasanryukin** [comment]
I think you're trying to re-invent the wheel by claiming a square is better.  As Kevin outlined, the world ended; there is no functioning infrastructure for electronic banking still in existance. The suggestion of gutting cards and going full on cash and coins makes more sense.  The implemention of faction currency makes even greater sense since dollars are only worth the paper they're printed on essentially.

**Comment by Petethegoat** [comment]
Faction currencies sound great.

Old money should be pretty worthless, unless you can power up a vending machine or something similar.

**Comment by Contemplator11** [comment]
But flavorwise, from the card description, cash cards are actually "cash", aren't they? Like credsticks from Shadowrun. From game world perspective, it may be logical to add "encrypted" tag to cash cards, like SD-cards and add the same encryption process using tablet PC. Such a thing will add more use to computers skill.

**Comment by glenmack** [comment]
> I think you're trying to re-invent the wheel by claiming a square is better. As Kevin outlined, the world ended; there is no functioning infrastructure for electronic banking still in existance. The suggestion of gutting cards and going full on cash and coins makes more sense. The implemention of faction currency makes even greater sense since dollars are only worth the paper they're printed on essentially.

No, what Kevin said was that cash cards WERE cash and that in this world there was therefore no infrastructure for electronic banking/accounts because in the fictional world it wasn't needed. So therefore there wouldn't be any of the infrastructure that my suggestions rely on.

**Comment by Zireael07** [comment]
If cash cards are supposed to represent physical cash, ATMs need to be scrapped and descriptions updated to reflect the fact, otherwise we're gonna get this discussion again at some point in the future, since the cards are plastic.

Transmogrifying cash cards to physical banknotes via a save update is also an option.

**Comment by CoroNaut** [comment]
Perhaps we could have something like a clothing item (advanced wrist watch) or something similar that would be used by the richer folk in the days before cataclysm, you could just move your wrist over a terminal to buy groceries or other stuff. It would then be personalized and be a separate item from cash cards.
