### ISSUE TITLE
Frequently repeated text x9999 in Message log Slows down gameplay.

### ISSUE THREAD

**Issue by NEONZARIN** [CleverRaven/Cataclysm-DDA#32749]
# Describe the bug

Frequently repeated text x9999 in Message log Slows down gameplay.

# Steps To Reproduce

Start crafting an item or start sleep or when driving transport. etc.

Sources of slowing the game in Message log:
**Mi-go** _-if you live in the laboratory with him, earplugs will not help. The text in the Message log will not appear, but the game will still slow down. If you kill him, the game will work MUCH faster.
_ , **radio**, messages about the movement of fish, **music**. 
And other similar sources of noise that are constantly popping the text in Message logs x99999999

# Screenshots
![image](https://user-images.githubusercontent.com/16442992/62105631-93c7b000-b2ab-11e9-944f-d7338ce63795.png)

![image](https://user-images.githubusercontent.com/16442992/62105714-d5585b00-b2ab-11e9-997e-c8fd6b911687.png)

![image](https://user-images.githubusercontent.com/16442992/62105976-a7274b00-b2ac-11e9-9f2d-c35668058d53.png)

# Versions and configuration

 - OS: Windows 7 64bit
 - Game Version: 0.D-6005-g110f6f9
 - Graphics version: Tiles
 - Mods loaded: -

**Comment by pjf** [comment]
I see your catfish and raise you a [horse](https://github.com/CleverRaven/Cataclysm-DDA/issues/32746).

**Comment by free-coffee** [comment]
#30543 addressed similar issues before.

**Comment by kevingranade** [comment]
#30543 addressed the message log spam, and I believe this issue's statement about the mi-go messages still causing problems is erroneous.  Mi-go in a lab do trigger slowdown, but it's because they are using a more advanced and expensive form of pathfinding rather than because of their message spam.

In profiling I can't see any impact from message functions, and a great deal of impact from pathfinding.  As this issue doesn't contain any meaningful information about pathfinding, I consider it resolved.
