### ISSUE TITLE
Plastic Jerrypack requiring "hammering 3"?

### ISSUE THREAD

**Issue by TechyBen** [CleverRaven/Cataclysm-DDA#32772]
Latest build.

Not sure if this should be bug or feature request. But could the "jerrypack" crafting requirements be adjusted? I don't mind it having a difficulty/parts/tools or skills limit to it, but "hammering 3" sounds strange for a plastic item crafting recipe.
Perhaps fine cutting, or similar instead. Or if it's fine to have easy access to carrying water (IMO it should be super easy to make, but very fragile, and possibly high encumbrance too!), simple cutting tools, and the current recipe.

[Edit]
The only reason I can think of is for hammering out the straps to nice thing/strong compressed patches? But string/rope would not need this.

**Comment by kevingranade** [comment]
Looks like originally the idea was to drive nails into it to anchor the straps.
If you want to fix it, please come up with a rational recipe instead of just removing hammering.  It looks like it ended up using superglue, which does NOT work.

It could be a cordage or rope mesh around it, meaning it consumes a lot more and requires some knot tying skill.
