### ISSUE TITLE
Recipe: Makeshift Pet Carrier

### ISSUE THREAD

**Issue by chaoticidealism** [CleverRaven/Cataclysm-DDA#32792]
**Is your feature request related to a problem? Please describe.**  
Whenever I try to keep chickens, I'm constantly frustrated by my inability to move the chickens unless I physically push them around, tie a rope to them, or find a (rare) pet carrier. And the pet carrier is really the only solution if I want to put them in my vehicle, at which point I have to make multiple trips to move my flock of five chickens because I can only find one carrier.

**Describe the solution you'd like**  
Why can't I put my chickens in a cardboard box? Okay, maybe it'd need to be a cardboard box with holes cut in it, and maybe reinforced with a second cardboard box; but if I want to carry my chickens around and I have a box, I should be able to put the chicken in the box and move the chicken.

Add a new crafting recipe. Have it require a cutting tool and either eight small cardboard boxes, two medium-sized ones, or one large. Name it "Makeshift pet carrier". Let us carry our chickens wheresoever we desire, even if we cannot find an animal shelter or pound to raid.

**Describe alternatives you've considered**  
All the alternatives I've considered would take more coding. The ability to carry around a small mob in your hands, although realistic, is a little bit much to ask for just to allow for chicken transport.

**Comment by curstwist** [comment]
i like this idea.  also, can you use livestock carriers too, or are the too big for chickens? They are craftable at least.

**Comment by chaoticidealism** [comment]
They're vehicle parts, though, and huge. They're the only good way to transport a cow (if you can't ride the cow for some reason), but they only fit one animal apiece and it's a bit overkill to build a whole vehicle just to move your chickens. Nah, a makeshift animal carrier would really be the best solution.

**Comment by kasanryukin** [comment]
https://cdda-trunk.chezzo.com/pet_carrier

Works on a chicken in latest experimental?

**Comment by LaVeyanFiend** [comment]
Sounds like someone wants #32426 re-opened(the original author of that deleted their account), it had a petpack idea in there.

**Comment by kasanryukin** [comment]
A craftable carrier isn't really feasible made from cardboard.  I could forsee making a wire cage that is portable and functions identical to a pet carrier using wire and welder, but it would be very bulky, and you wouldn't be able to carry more than 2 realistically.  You aren't going to shove more chickens into 1 cage with out also rewriting some of the code governing containers.

I'll add a craftable wire cage and see where it goes in review, but don't get your hopes up on a multi-chicken carrying conveyance.

**Comment by kevingranade** [comment]
Cardboard is workable for a relatively small animal like a chicken or a cat there are cardboard cat carriers IRL.

**Comment by kasanryukin** [comment]
> 
> 
> there are cardboard cat carriers IRL.

Which are disposable and only meant for very short term use.  A scare cat can shred the inside of one to uselessness in a matter of minutes. 

While I don't debate the usefulness or ease of making a cardboard animal carrier (since it's just a cardboard box with some holes in the side for air/handles); I debate the need to add a third type of pet carrier when a craftable alternative already exists.  Rarely will you see cardboard pet carriers in use for anything other than very small pets such as rodents, lizards or snakes.  Chickens purchased as chicks out here where I live (and where they're common market goods throughout spring and summer) are transported in the self same tiny boxes; while full grown chickens are carried in wire coops or small wire cages; which is utilitarian in purpose. They're easier to clean, a chicken won't tear it up due to their talons (which are sharper than most people realize), and it's less stressful on the chicken since they can see their environment.

**Comment by TychaiosIlithios** [comment]
Objection here. It works only if you specify animals by names. If you go to size definitions, then not all small animals can be carried in cardboard. For example rabbits and hares - these abominations will rip any such container should they feel bored or vice versa agitated in many cases, some digging critters like rats and toy terriers will also wreak the containment. 

Wrote this because cataclysm is about libraries with proper definitions of classes, so mentioned container class-wise should have some flag like 'chewable' or later this forum might get a person complaining that it holds his zombie rat pet while it shouldn't.

**Comment by chaoticidealism** [comment]
It doesn't really have to be made out of cardboard; it just has to be craftable, that's all.

If the cardboard carrier really does seem too flimsy for bigger animals or ones with bigger teeth, then have it be made out of wood or plastic. Just make it craftable out of common materials--it's really ridiculous that we have to raid five vet stores or pounds just to be able to put our flock of chickens in the back of our trucks.

**Comment by 81Denton** [comment]
Ingame pet carriers have 1kg weight and are made of steel plus plastic, so I assume that they're based on these types:
https://images-na.ssl-images-amazon.com/images/I/81eLpE6l3NL._SX425_.jpg

This looks like something that can be done with wire + plastic chunks and tools that provide hammering, metal sawing and heat plus a plastic mold. IRL the door is kept shut by small springs, but ingame springs are heavy-duty and wouldn't fit.

There are also animal carriers made of wood:
https://ebth-com-production.imgix.net/2014/12/20/22/06/44/466/_DS22426.jpg

I'd make those from 2x4s, nails and hinges. Tools would require sawing and hammering - I don't think screwing is neccessary since the hinges could be held in place with nails. I also don't think that a lock would be neccessary, as the door could be kept shut without a lock and Cataclysm doesn't have proper locking mechanics.

The wooden model would obviously be slighly bulkier and heavier, but easier to craft early on.
