### ISSUE TITLE
Tame horses will climb through windows to reach you

### ISSUE THREAD

**Issue by pjf** [CleverRaven/Cataclysm-DDA#32795]
# Describe the bug

I was very surprised when cooking to have a horse climb in through the window so it could [make noise](https://github.com/CleverRaven/Cataclysm-DDA/issues/32746) while I crafted.

# Steps To Reproduce

1. Make friends with a horse.
1. Lock it outside, but accidentally leave a window open.
1. The horse is now inside.

# Expected behavior

Only small and agile horses climb through windows.

# Versions and configuration

- OS: Ubuntu 16.04 LTS
- Game Version: f95875f3eea4403333379d8a6d6e848c9d2ab837 with #32754, #32782 and MSX tiles applied.
- Graphics Version: Tiles
- Mods loaded:
```
    Dark Days Ahead [dda],
    Filthy Clothing [filthy_morale],
    Alternative Map Key [alt_map_key],
    [DP_MOD] Indicators: REMIX [DP_REMIX_INDICATORS],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Sleep Deprivation [sleepdeprivation],
    Bionic Slots [cbm_slots],
    sees-player icon, -attitude [sees_player_less_attitude]
```

**Comment by SquareMan** [comment]
I'm trying to figure out how to fix this as my first contribution. I've been searching around the code and json trying to find where I might be able to fix it but I'm really not sure where I should be looking. Is this an issue that can be solved with JSON or do I need to make some changes in the actual source code?

**Comment by anothersimulacrum** [comment]
This looks like it's an issue that would need to be solved with C++, not JSON.

**Comment by korvyr** [comment]
This could be solved several ways, so before I try to tackle it, I want to get some input from a more experienced CDDA contributor. This are listed somewhat from easiest to hardest. I say somewhat because I'm just running through the process in my head; they could end up being much worse.

**COA1** Restrict pets from using windows.
**COA2** Restrict mountable pets from using windows.
**COA3** Restrict _large_ critters from using windows.
**COA4** Restrict _large pets_ from using windows.
**COA5** Restrict _large_ critters from using _small_ entries.

Debatably the final COA is the best as it is the fundamental _bug_ at play here, but it would also require a fair bit of work. Happy to tackle it if others agree that it's the course that should be taken here.

**Comment by anothersimulacrum** [comment]
*COA5* would be my choice, though it doesn't need to be very expansive - just do something like adding a flag such as `SMALL_ENTRANCE` to windows, and prevent creatures over a certain volume from using it.
Then it can be expanded to more terrain/furniture.

Of course, that's just how I would implement it.

**Comment by korvyr** [comment]
Agreed. On it.
