### ISSUE TITLE
Apartment towers (and other multi story buildings) are too safe: Make them inhabitable by arthropods

### ISSUE THREAD

**Issue by Svankensen** [CleverRaven/Cataclysm-DDA#32801]
I finally managed to survive a "Tweaker" Reall Bad Day scenario by getting into an appartment building and staying there for 8 days. There are usually 5ish zombies per floor, and once you clear a floor, no more zombies will come, making them exceedingly safe places to set up in. Since making zombies move up and check buildings would be too smart for them and beyond their motivations, I suggest that other enemies that can move vertically (in theory at least) exploit this lack of zombies to make their nests. A simple fix would be to give each floor a 30% chance to be a wasp, bee or spider nest. This will create more variety in the enemies you face, and would justify some of them ocasionally spawning in levels above z1 to pester the survivor.

**Comment by curstwist** [comment]
rat swarms too!

**Comment by JonathanLochridge** [comment]
So, I was looking into issues about appartments since I had a semi-related idea. But, this issue caught my eye.

But, I think that a 30% wasp chance is way too much though.
I am still interested in adding some varient floors that have wasp, bee or spider nest though.
I am not completely sure how difficult that would be to do. I have done a bit of map work before though.

For all I know there might already be some infested apartment floor variants. 

I know there was bee infested office tower among the Urban development stuff people are trying to mainline though?
