### ISSUE TITLE
Hunger has no effect on morale

### ISSUE THREAD

**Issue by pjf** [CleverRaven/Cataclysm-DDA#32817]
# Describe the bug

No matter what one's hunger status, it seems to have no impact on morale.

# Steps To Reproduce

1. Don't eat for a couple of days.
1. Hit 'v' to view morale.
1. Observe no mention of hunger, even though one is very hungry to famished at this point.

# Expected behavior

I don't know about other folks, but I know I'm *absolutely miserable* if I haven't eaten for a while. Certainly much more unhappy than if I got caught in the rain, or ate a piece of fried liver.

While I can understand 'peckish' not having a morale impact, I feel the other levels should. This would make regular meals and planning food for longer trips more important.

# Versions and configuration

 - OS: Ubuntu 16.04 LTS
 - Game Version: 4add125df5bb28147745dc1a6a29f225e5b15624
 - Graphics version: Tiles
 - Mods loaded:
```
    Dark Days Ahead [dda],
    Filthy Clothing [filthy_morale],
    Alternative Map Key [alt_map_key],
    [DP_MOD] Indicators: REMIX [DP_REMIX_INDICATORS],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Sleep Deprivation [sleepdeprivation],
    Bionic Slots [cbm_slots],
    sees-player icon, -attitude [sees_player_less_attitude]
```

**Comment by ZhilkinSerg** [comment]
That's is not a bug though.

**Comment by kevingranade** [comment]
I'm on board with adding it, but it needs a bit more detail to be
implementable.

**Comment by pjf** [comment]
Oh gosh, for some reason I always thought we had this before the stomach
contents rework. I'll bounce some ideas around to see if any of them seem
worthy.

I imagine one of the most straightforward implementations would be to have
hunger act in a similar way to wetness; it's a malus to morale that grows
the hungrier you get, and disappears entirely when you've sated that hunger.

One gotcha is it's currently possible to sate one's hunger by drinking
water, but I recall that is absorbed quickly, so maybe it's not that big a
deal. I've also found that hunger sometimes disappear without any reason I
can determine, but then again my hunger comes and goes iRL as well.

Possible advanced mechanics could be stimulants and appetite suppressants
which remove or lower one's hunger for a while, and diseases and possibly
even CBMs with the same effect. There's also the potential for some foods
to be more or less filling than their caloric value would have you expect.
(Soft drinks are packed with calories, but I've rarely found they've made
me feel sated.)

>

**Comment by perryprog** [comment]
It would also be nice to have a morale boost when transitioning from very hungry to something like full, as that feels good in real life.

I know from experience that stimulants will only remove your appetite, you will still get fairly hangry if you forget to eat; the issue is just remembering to eat. If we want to be a bit creative, why not bring down the morale with "you feel agitated/grumpy" if the player's appetite is suppressed and if they haven't eaten in a while? Nothing as severe as what normal hunger would be, but enough that it encourages the player to be proactive about caring for their needs. Obviously the above is much less important than what @pjf said—it's just something I thought of while reading this.

p.s. @pjf, your username is my initials! :)
