### ISSUE TITLE
Activating canned dogfood results in eating it

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#32911]
Instead of feeding the nearby dog.

0.D-6156-gcb9471dd46-dirty

**Comment by jeremyshannon** [comment]
It looks like "canned dog food" is a separate kind of dog food, rather than just regular dog food in a container. The recipe generates uncanned "canned dog food" too. The fix would be either to add "canned dog food" to the item activation code, or more properly to replace it with the correct item in a can.
 I have some time, I'm looking into it.

**Comment by jeremyshannon** [comment]
Urgh, I got it working, but I accidentally committed it to master instead of my petfood-fix branch. Now I gotta figure out how to untangle this and get the commit moved onto the branch.

**Comment by l29ah** [comment]
git checkout petfood-fix
git cherry-pick master
git checkout master
git reset --hard HEAD^

**Comment by jeremyshannon** [comment]
Yeah, I figured it out, thanks.
