### ISSUE TITLE
Multiple faction camp bulletin boards

### ISSUE THREAD

**Issue by RarkGrames** [CleverRaven/Cataclysm-DDA#33009]
**Is your feature request related to a problem? Please describe.**  
The main faction camp bulletin board is out of range of some facilities in the faction camp. For example if you have a blacksmith shop in the northeast corner, you can't make use of the loaded charcoal forges or the tools stored there to give out tasks (even if you have direct vision of them). If you build a second bulletin board next to the shop or inside of it, upon examining it you get the "this bulletin board is not in a faction camp" message.

**Describe the solution you'd like**  
Building bulletin boards on the survey om tiles also count as faction camp bulletin boards.

**Describe alternatives you've considered**  
Adding the option to access the bulletin board panel through the faction screen (#).

**Comment by TychaiosIlithios** [comment]
Agreeing here. But believe optimal would be some itemless feature like radio management.
Likely some time in perfect future all of the camp items and facilities will be withing checks from main board but at the moment character needs to manually arrive at facilities or cargo locations to initiate crafting, and since the pleasure of making a special vehicle to access bboard through the gate with its cargo rear is highly dubious, it would be just dandy if I could just radio request needed operations from within the 3x3 camp area.
