### ISSUE TITLE
add military hunter-killer teams and giant alligators

### ISSUE THREAD

**Issue by Jaodacidade** [CleverRaven/Cataclysm-DDA#33067]
My feature suggest its: theres a chance of a military crew of 6-10 guys come to the city and kill zombies and if they find you they offer you supplies and a safe shelter with energy, food and etc. If you attack them, they will shoot you to death or taser you and arrest you.

The new enemie is: A giant alligator just like the one that appears on resident evil 2 but it could appears on the sewers and the city or the swamp too.
![jaca](https://user-images.githubusercontent.com/53924535/62751136-0ae20e80-ba39-11e9-8a48-804cb43c1a03.jpg)
![soldado](https://user-images.githubusercontent.com/53924535/62751143-0ddcff00-ba39-11e9-8899-2c421fca14ab.jpg)

**Comment by Xenomorph-III** [comment]
We already have sewer gators in-game, and they spawn rarely in basements.

I think they can be expanded to sewers and swamps, too.

**Comment by Kanexan** [comment]
Who would the military crew come from? Everybody's dead, the Old Guard doesn't have the resources or manpower to clear cities and rescue every lucky fellow who survived the Cataclysm, and none of the other factions would be interested—let alone capable!—of doing such a thing. 
Plus, resources are running thin after the end; just handing them over to somebody you just discovered is simply unwise, certainly if you're planning on doing it for every survivor you come across.
And is this a specific city they would spawn in? _Any_ city? The text is somewhat unclear.

**Comment by TychaiosIlithios** [comment]
As far as I understood previous topic, current governmental elite has fled to a flotilla of ships and oil rigs, from where they try to project their interests. Vastly and majorly through mercenary activity, i.e. hiring you.

Looking at such behavior, it seems logical that should such people for whatever reason send a military team to wherever, that team will likely be very focused on its goal and the only reason they wouldn't kill any encountered survivor would be possible interrogation. Because mission is important and threats must be mitigated. 

With that in mind such a team would be the last thing I'd love to meet, especially because it is likely in the focus of attention of whoever sent it, and unlike just a gang with guns they might be actually supported by sattelite feedback, drones and that very chopper that brought them here. Because there are heavy mutant situations and military wouldn't be military if they sent no anti-hulk guns to possible anti-hulk situation.

So it seems to me that any human activity in game should be 'intelligent', i.e. tied to scenarios of whatever stuff like quests, faction events etc. Too bad firefall game is a goner - it was a unique example how most mobs on the map spawned not just wondering around but as a part of some group guarding some chest or other minidungeon event - would be just right for any human activity here.

**Comment by mlangsdorf** [comment]
There's already a team of 6-10 soldiers who will kill zombies for you.  Of course, they're trapped in the Necropolis and are likely to get killed well before you get to them, much less before they kill all the zombies for you.
