### ISSUE TITLE
Using sheet of glass doesn't consume it

### ISSUE THREAD

**Issue by RarkGrames** [CleverRaven/Cataclysm-DDA#33124]
# Describe the bug

Upon using a sheet of glass to place the shards as a trap, the sheet remains in inventory/hand, producing the trap on the ground. Disarming the trap you get back one shard of glass.

# Steps To Reproduce

1. Activate the sheet of glass.
2. Place the trap.
3. Disarm it.

# Expected behavior

Placing the trap consumes the sheet of glass, and disarming it gives a whole sheet worth of shards.

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-6273-g40119a3 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by pierredavidbelanger** [comment]
I faced the same problem. And I can confirm this bug.

This happens only with the `tr_glass` trap, when using the `glass_sheet` because `glass_sheet` is of type `GENERIC` and [does not meet the conditions](https://github.com/CleverRaven/Cataclysm-DDA/blob/2bda93b4da79ad986df48ed8a5427dc3d77b6432/src/player.cpp#L8983) to either `consume_charges` or `i_rem`.

I have a PR coming for this.
