### ISSUE TITLE
Bare hands is not a valid eskrima weapon, should be

### ISSUE THREAD

**Issue by bleaky** [CleverRaven/Cataclysm-DDA#33264]
### Expected behavior

given that eskrima is explicitly designed to be used bare-handed-- the style integrates hand to hand strikes, joint locks, and barehanded (or armed) disarms. the bare-handed aspect of the art is integral to the style, and is baked into both the cultural tradition and material history of the art, and we can do better than providing a half-baked, fake eskrima for the game. aside from that, having the usefulness of taking a 3 point trait be completely nullified if your weapon is lost, dropped, broken etc.

the puño strike is a perfect example, being usable with fist, knife, and stick all, and being included in the game as an ability. 

a couple quick references:
https://youtu.be/8Gvz4ZF_oss?t=336
https://stickfightingsport.com/filipino-stick-fighting-basics/ (this website also includes a really nice list of viable improvised weapons that are compatible with the art)

### Actual behavior

simply put: does not recognize bare-handed as a valid eskrima weapon

### Alternatives considered

- simply removing eskrima and allowing silat to occupy a similar space

- changing eskrima to stickfighting, singlestick, kobudo, kendo, or some other martial art that focuses entirely on medium-length handheld weaponry and is easily compatible with bladed weapons as well

- renaming eskrima to a fictional style (or genericizing it to e.g. improvised weapon style, stickfighting, or the like) to more easily incorporate the work already done without having to do too much massaging

### semi-related footnote

i may make a separate issue for this, not really sure if i should: wing chun also doesn't respect knives and quarterstaves and similar as weapons. this again revises the tradition and history of the art as well as again, the potential usefulness of taking a 3 point trait. feel free to leave a comment regarding this particular issue and share your thoughts.

https://en.wikipedia.org/wiki/History_of_Wing_Chun

**Comment by ampersand55** [comment]
Pinging @Hymore246.

**Comment by Hymore246** [comment]
I'm working on a rebalance of all the martial arts in the game. See #32422 for more information. I got done with Eskrima recently so I can answer a few things.

> we can do better than providing a half-baked, fake eskrima for the game

Please elaborate, because just adding the ability to use the attacks unarmed doesn't really do much for the style. Thanks to the removal of "magic unarmed damage" in #31858, it's always better to use a weapon (or unarmed weapon) when using martial arts for more damage.

> having the usefulness of taking a 3 point trait be completely nullified if your weapon is lost, dropped, broken etc.

That's how the weapon martial arts work. You need weapons for the style you want to use. If this was about Niten Ichi Ryu, then you would have a point due to how hard it is to find the right weapon for it. Eskrima on the other hand can use a lot of commonly found items as weapons. Heck, it can use a 2x4 as a weapon and you can easily get one in the first few minutes of a new game. Eskrima is the style that has the easiest time finding the right weapons to use.

> New weapons

Mostly, they just don't exist in the game right now. If they did, they would be usable with the style for sure. I'm not adding new weapons as part of my rebalance because it takes a while to make sure the new weapons are in line with the existing weapons in the game. If someone wants to add them in, go for it.

All that said, it wouldn't be hard to change Eskrima to work with unarmed attacks. I just don't know what else it would offer to the style.

**Comment by LaVeyanFiend** [comment]
> 'm not adding new weapons as part of my rebalance because it takes a while to make sure the new weapons are in line with the existing weapons in the game. If someone wants to add them in, go for it.

I'll eventually add MA functionality to the Magiclysm school weapons, but that'll be after Silat/MS/FdB get their reworks in.

**Comment by kevingranade** [comment]
Hostile tone is not welcome.
```we can do better than providing a half-baked, fake eskrima for the game```
