### ISSUE TITLE
Warn player of rotten ingredients when crafting food items

### ISSUE THREAD

**Issue by Heaper327** [CleverRaven/Cataclysm-DDA#33385]
**Is your feature request related to a problem? Please describe.**  
When crafting food items, there is no remainder that the components you are using are already rotten/almost rotten, and if you don't memorize how spoiled all your ingredients are, you will often end up making a pot of hot, rotten soup. This becomes more annoying when you have a large food storage as it becomes harder to remember all their spoilage.

**Describe the solution you'd like**  
when attempting to craft food items with rotten ingredients or almost rotten ingredients, warn the player via a pop up like "the meat you are using is rotten, are you sure you want to craft food with it? (Y/N)"

**Describe alternatives you've considered**  
Highlight the name of rotten ingredients in the "&" crafting interface

**Comment by jbytheway** [comment]
With #36610 now merged, this is partly resolved.  Crafting will now warn about rotten food.

However, there remains the issue of starting a craft with nearly-rotten food and having it go rotten before you're done.

Fixing that is tricky because of rot rate being a function of the environment.  How accurately do we need/want to predict the weather, etc.?  Conversely, if we are willing to approximate, how badly can we overestimate the problem (i.e. be over-cautious about including nearly-rotten food) before that in itself becomes problematic.

There's a related issue which is that players have little control currently over which components are chosen.  Sometimes you might want to choose the least rotten components, other times the most rotten.

Overall it's a UX issue which I'm not sure how to deal with.

So, the issue should probably remain open (although you might want to update the title), but in the short term I'm wondering whether this is now sufficiently fixed to no longer be a 0.E blocker.

**Comment by esotericist** [comment]
Having looked over the PR again, I agree with @jbytheway 

This isn't "solved", but it's mitigated as well as I think is reasonable in the lead-up to 0.E since any thing more complete will get increasingly disruptive (and there's a lot of highly uncertain design concerns).

Consequently, I'm pulling this off the blocker list, and reflagging it a long-term issue so it doesn't get lost.

**Comment by anoobindisguise** [comment]
This can be closed now right? This was fixed forever ago.

**Comment by jbytheway** [comment]
It's still partly fixed, as discussed in the last couple of comments.  But if the community has stopped complaining about it, maybe we don't need to worry about a fix to the remaining aspects (especially since we don't know how to).

**Comment by Maleclypse** [comment]
Closing this as further progress on it's remaining point seems to be at a dead end.
