### ISSUE TITLE
Albino skin irritation should specify which parts of the body is affected.

### ISSUE THREAD

**Issue by SlackingSleeper** [CleverRaven/Cataclysm-DDA#33389]
**Is your feature request related to a problem? Please describe.**  
The current message is: "The sunlight is really irritating your skin."
Figuring out which part of the body that you've forgotten to cover up is rather unwieldy. It requires you to go through all of your clothing to find the uncovered part.

**Describe the solution you'd like**  
The message should be changed to "The sunlight is really irritating the skin on your X" where X is the body part.

**Describe alternatives you've considered**  
Instead several messages showing up at the same time an alternative message could be shown and the exact body parts affected shown in the '@' tab. "The sunlight is really irritating the skin on large parts of your body."

**Comment by ipcyborg** [comment]
Current implementation does not check body parts specifically (except the eyes).  Or at least I cant find any confirmation of it.
So it does not matter if you have 100 % coverage on every body part or not. The only checks are:
- character has ALBINO trait OR has datura effect applied
- character is in direct sunlight
- character does not wear something like RAIN_PROTECT (like umbrella)

Similar checks for SUNBURN (no check for body parts coverage).

Suggestion: 
It could be changed to check body parts coverage. To simplify things we could assume that even simple cloth could cover the skin (so ignore the material, just use coverage).
Also chance could depend on coverage (proportional to non-covered area), and not just `one_turn_in( 1_minutes )`.

It could still be funny, like `The sunlight is really irritating your left foot.`.
May be just some body parts?

**Comment by SlackingSleeper** [comment]
Could it reuse parts of the wetness/rain code?
I'm new to the project so I don't know where stuff is, where is the code for the current implementation?

**Comment by ipcyborg** [comment]
Well, there is `player::drench`. It is used to drench body parts separately. 
It is strange that it only accounts the `WATERPROOF` flag, but not coverage. May be it is intended, I don't know.
I don't think this code could be reused for ALBINO, since coverage (and probably material) is more important here than `WATERPROOF`. It still may be linked somehow, like drenched body part could be more/less susceptible to sunlight.

To keep it simple, I could implement my suggestion (above). Only check for coverage, not material.
Check all body parts and calculate ALBINO effect chance based on the percent of non-covered body area.
Probably use sun brightness to make effect stronger (clear is normal, sunny is high, all other - low). 

`one_turn_in( 1_minutes )` seems to be from before the `turn=1 sec` change. It should be something like 1/10 chance.

BTW, checked the vehicle/weather code to find if the solar panel efficiency is based on sun brightness. It is not, right?
