### ISSUE TITLE
find_or_create_om_terrain in mission_util does not find overmap_special even if it was placed in same function

### ISSUE THREAD

**Issue by sztosz** [CleverRaven/Cataclysm-DDA#33403]
# Describe the bug

`find_or_create_om_terrain` in `mission_util.cpp` https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/mission_util.cpp#L171 does not find `overmap_special` on line https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/mission_util.cpp#L205 even if it was placed by `overmap_buffer.place_special` on line 199 https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/mission_util.cpp#L199 

# Steps To Reproduce

Steps to reproduce the behaviour:
1. Load attached save.
2. Talk to intercom and choose to accept new mission.
3. Observe debug message `Unable to find and assign mission target`, and application hangs indefinietly. 

# Expected behaviour

No debug message and overmap_special being found, allowing to continue game.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-6737-g9f59a93762 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Beta National Guard Camp [national_guard_camp],
    No Rail Stations [No_Rail_Stations],
    [DP_MOD] Indicators: REMIX [DP_REMIX_INDICATORS],
    Simplified Nutrition [novitamins],
    No Fungal Monsters [No_Fungi],
    No Bees [No_Bees],
    No Ants [No_Anthills]
]

# Additional context

I tried to debug it in Visual Studio, but my C++ skills and familiarity with the game are not good enough to be able to make pull request fixing it.

`overmap_buffer.place_special` in this particular case uses `center = {x=129 y=48 z=-1 }` and `radius = 180` as parameter and It's position of the player (with z= -1, because player position has  z = 0), and it returns `true`, because it placed special somewhere on the overmap. 

Then `overmap_buffer.find_closest` try to find closes special to set it as mission goal, but it does not. It takes `origin_pos = {x=129 y=48 z=-1 }` as first argument, and `find_params = { ... search_range=180 ...}` as second parameter. 

`search_range` is the same as `radius` for when we place special, that makes sense, we couldn't place it farther than that, so no use in searching farther than that.

But with `search_range` being equal that `radius` we passed to `place_special` we can't find that special. If in that particular case I change in debugger `search_range` from 180 to 271 (or more, but not less) then it finds overmap special at `w_loc = {x=-138 y=151 z=-1 }`

I haven't been able to pinpoint what may be the problem. But 271 is exactly 180 * 1.5 + 1, not that it helps anyone :/

**Comment by sztosz** [comment]
[AAA.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3522249/AAA.zip)

Save I forgot to add to originall report.

**Comment by ralreegorganon** [comment]
The issue here is that when the radius is used in placing the special, it just uses that to determine which overmaps are valid for placement (see [here](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/overmapbuffer.cpp#L1476)) but then tries for placements on the entirety of the candidate overmaps. 

As a result, the search radius may just reach the edge of the overmap, but the placed special may be on the other end of the overmap and won't be found.

I think there is a pretty straightforward way to mitigate this problem:

The sectors that are used in the `place_specials_pass` can be filtered for each candidate overmap down to just those that are within the defined radius. 

This will have the upside of generally making it so that the range searched and the range in which things are placed will match up. 

Some additional changes will have to be made to account for the fact that it's generally working with an anchor point for placement and thus rotations and the size of the special may put parts of it outside the search radius, but the search radius could be extended after placement to account for that. 

The downside of doing this is that it's likely to reduce the chances of a successful placement for any given attempt since it will reduce the available space checked, but at least it will be respecting the radius provided.
