### ISSUE TITLE
Auto-notes overwrite player notes

### ISSUE THREAD

**Issue by AGrinningCat** [CleverRaven/Cataclysm-DDA#33416]
# Describe the bug

Auto-notes overrides custom notes

# Steps To Reproduce

Turn on Auto-notes
Allow auto-note to place a note (house basement)
Edit auto-note to include additional information (Such as labeling house basement as a spider basement)

# Expected behavior
Auto-notes shouldn't override player placed notes.

**Comment by ZhilkinSerg** [comment]
I am not following your steps. Did you place note on an unexplored tile?

**Comment by BaumgeistOne** [comment]
Steps to reproduce this (Build 9519 on Windows 7):
1. Enter a new basement with "auto-notes (basement)" enabled, and exit it.
2. Change "AUTO: goes down" to something else.
3. Enter and exit the basement again. Observe that the note was changed again, the player-made note discarded.

This has been happening for a while, I turned of auto-notes for basements because of it.

**Comment by JacobKessler** [comment]
I'm observing this behavior as well, built locally at commit 367f3a8960 (https://github.com/CleverRaven/Cataclysm-DDA/commit/367f3a8960). It looks like there is a check at game.cpp:10555 that should prevent this, but as observed it doesn't. I haven't checked the behavior of map extras, but it looks like that is in a completely different function

**Comment by JacobKessler** [comment]
A small update: It looks like placing a note on both levels (so, for a basement, both the basement tile at z-1 and the house at z0) prevents the auto-note from overwriting the surface one. That makes me suspect that the check to avoid overwriting player notes isn't correctly checking z-levels before it overwrites.

**Comment by ZhilkinSerg** [comment]
That's fine update.
