### ISSUE TITLE
Dehydrated fruit/meat have weird superfluous recipes

### ISSUE THREAD

**Issue by Techbane** [CleverRaven/Cataclysm-DDA#33437]
I'm unsure of whether this has resulted from me reading a recipe book somewhere, but (as of 9508) dehydrated fruit and meat have two recipes each: one that just requires a smoker/dehydrator and the food in question, and one that requires the above _plus_ a small charge from a cooking implement (which can include the smoker), and seems to yield the exact same result with a higher cost and more time spent.

**Comment by Rivet-the-Zombie** [comment]
>one that requires the above plus a small charge from a cooking implement (which can include the smoker), and seems to yield the exact same result with a higher cost and more time spent.

Those are for when the ingredient(s) in question are frozen - the extra charges/time are there for thawing it out during the process.

**Comment by ProfoundDarkness** [comment]
This is normal to my knowledge.

When the frozen item state was added to the game (I think) it was deemed inappropriate to allow using frozen ingredients in recipes not intended to be served frozen.  Rather than force players to thaw out every component it was also built in that recipes which finish hot (ie use something like a hotplate) COULD use frozen inputs... since the process of cooking would heat them up enough to... cook.

Pretty sure the base recipe for dehydration doesn't use heat so much as like a vacuum which means the result isn't hot which means frozen ingredients aren't allowed.

The recipe for dehydration that ALSO requires something like a hotplate (and if you look close also takes longer) results in hot dehydrated meat/fruit and because of that allows for frozen inputs.

**Comment by Techbane** [comment]
Alright, I noticed it extends to all dehydrated foods, and I guess I get the functionality of it -- but I have to say it really doesn't communicate its purpose or the difference in input/output the way it is now.

**Comment by Inglonias** [comment]
Requesting that this issue be reopened.
