### ISSUE TITLE
Vehicles shouldn't protect as much as they do now

### ISSUE THREAD

**Issue by roaringjohn** [CleverRaven/Cataclysm-DDA#33739]
**Is your feature request related to a problem? Please describe.**  
Vehicles have been protecting players and non-players time and again for too long, with the exception of engine compartments.

**Describe the solution you'd like**  
Somehow make it so that tiles not including the engine parts don't provide much protection/cover to bullets.

**Additional context**  
[Video that shows most bullets, with the exception of .22 LR, buckshot and another type of shotgun shot, aren't stopped by anything but the engine compartment.](https://www.youtube.com/watch?v=6qXwdBOZzpY)

**Comment by zeziba** [comment]
Greetings,

I like this idea but then again it would be true for 90% of the materials of this game. I worked with munitions for a while and I can tell you that there is little that will stop a bullet traveling at full velocity including walls and other such things.

What these things provide on the other hand is concealment and not cover. This is also why the armed forces tell their troops to take cover and also go over the difference between cover and concealment.

With cover or concealment the thing that protects you from getting hit is not the item itself but the fact you are out of the persons line of sight and the deflection that occurs when the round hits that medium. Check out (huge number) videos of 9mm being deflected off windshields of cars because of the deflection angle as an example.

From a gameplay standpoint it would be cool to simulate all this as random chance or some other method with each more complex method being more complex and requiring more cpu time. 

I do not know the difficulties that CDDA would have implementing this but would be cool nonetheless.

**Comment by Orinyau** [comment]
The difference between concealment and cover is a sucking chest wound.

**Comment by dkargin** [comment]
Technically, it is not only a 'vehicle problem'. It is more like 'projectile damage distribution and penetration problem'. Right now any projectile can hit only one block/object with exception of some tiles (i.e windows).

Good penetration model could calculate how much kinetic energy is absorbed by each tile (body) traveled and continue traveling until this energy is spent. But this model needs LOT of data. You should specify some values about how much any material interacts/absorbs/stops different projectile types. You should specify these values for ALL game objects you can hit: steel plating, hulk riding a pony, five bunnies in a row, ...

It is not impossible. It just takes more effort, and causes another spiral of balancing for every part in the game.
