### ISSUE TITLE
Mechanics skill NPC assistance

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#33896]
**Is your feature request related to a problem? Please describe.**  
I have 0 mechanics while my NPC ally has 10, but i still can't change that punctured tire on my bike!

**Describe the solution you'd like**  
The mechanics skill check would be extended to my whole party.

**Describe alternatives you've considered**  
Being able to order NPCs to work on certain vehicular tasks, but i guess it's much harder to implement.

**Comment by mlangsdorf** [comment]
So NPCs can already install CBMs for you.
I started work on gettings NPC to take over other tasks in iexamine and failed because a lot of (Whales original) tasks have extremely stupid formulas for calculating odds of success that do not allow you to say if an Int 9, Computers 5 NPC is better for electrohacking than an Int 13, Computers 4 avatar.

Sometime after 0.E I will go back through and make this happen.
