### ISSUE TITLE
Playing without NPCs still makes owned faction items

### ISSUE THREAD

**Issue by reed501** [CleverRaven/Cataclysm-DDA#33897]
# Describe the bug

When NPCs are disabled the refugee center is full of things owned by another faction. Now it's not all bad- you can set the steal notice to ignore always but still I'm not sure this stuff should be owned anyway.

# Expected behavior

If NPCs are disabled every item in the game should be not owned by anyone as you are literally the only one left.

# Versions and configuration

 - OS: ChromeOS 76
 - Game Version: 0.D-7343-g8333e52d
 - Graphics version: Tiles
 - Mods loaded: None

**Comment by KorGgenT** [comment]
NPCs being completely disabled is not really an intended way to play. As such, if NPCs are disabled, the refugee center or all of the stuff in it should not even appear, as it is a huge stockpile of goos for free.

**Comment by reed501** [comment]
I don't think the refugee center was built after the Cataclysm though, wouldn't it just be a location made for what happened? Maybe have it be mostly barren in that case, as if it was looted very early into the apocalypse.

**Comment by Zireael07** [comment]
Can't find the other issue, but Kevin said "refugee center is meant to be interacted with in the presence of NPCs"

**Comment by kevingranade** [comment]
That's #33635

The only thing that makes sense to address this is to make the refugee center not spawn if static NPCs are disabled.
Optionally you could also make a variant refugee center spawn that has zombies instead of NPCs.

But really enforcing consistency when non-standard options are enabled is not at all high on my list of priorities.
