### ISSUE TITLE
There's a the sewer rat in the way!

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#33900]
# Describe the bug

It's impossible to go up/down the ladder if there's a monster decided to mob there on the target level, however small.

# Expected behavior

It should be possible to push even a human-sized body out of the way.

# Versions and configuration

0.D-7411-g92a1956a0f-dirty

# Additional context

[2019.09.08.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3588020/2019.09.08.zip)

**Comment by SomeDeadGuy** [comment]
Yeah, game lacks of this ability.
In most zombie games you can push zombie (and other zombie behind him, like dominos) on the ground and run past them. You will probably get bitten but you at least can escape this way. Also some rugby player can run through corridor takling every zombie on his way with his shoulders. Smol rat instead of hitting him with the weapon can be just kicked like football to the other side of the room.
Also rat probably will latch on to you or climb in to your not tight clothes. Zombie can latch on to your back and be dragged behind you while you try to shake him of yourself.
Something like this would add so much more to the gameplay, and each enemy type will be way more unique.
Ofcourse it will need whole new system for combat, so I have little hope on this actually happening.

**Comment by BaumgeistOne** [comment]
A first step would be the addition of the ability to push (or switch positions with) small creatures like rats. I remember being in the rat cave with a melee character - not being able to run directly at that rat king because there were rats in the way was quite irritating.

**Comment by l29ah** [comment]
Still an issue on today's master.

**Comment by codemime** [comment]
As the bot says, "issues that are closed are still considered".

**Comment by busterbogheart** [comment]
Still an issue, experienced in--  Build number : #10478  Build version: 0.E-3

**Comment by olanti-p** [comment]
Should've been fixed by #40303. Does 0.E-3 have it?

**Comment by Maleclypse** [comment]
You can push past a monster in your way on the target level now. So I'm closing this.
