### ISSUE TITLE
Loot sorting zone for "items already there".

### ISSUE THREAD

**Issue by zachary-kaelan** [CleverRaven/Cataclysm-DDA#34009]
**Is your feature request related to a problem? Please describe.**  
My sorting system is too complicated for the filters to cut it. Plus, working with filters can be a pain sometimes.

**Describe the solution you'd like**  
Add a Loot: Preset zone, or an option to the Loot: Custom zone, that uses the items currently present as the filter.

Also add an option to these zones to "update" the list, and add any new items, without removing existing ones (as you might've used them all up in crafting). If the player wants to completely reset the filter, they can re-create the zone.

**Describe alternatives you've considered**  
Making filters more robust in the future is another option, but that's a whole 'nother beast.

It would make Loot: Custom zones a lot easier to work with if there was a `T`est command like with the Autopickup manager.

**Comment by int-ua** [comment]
Use-case: sort guns and ammo by caliber.

**Comment by zeggz** [comment]
+1
That's a feature that would be really usefull because some of the item categories are too wide sometime. For example if i want all tailoring related stuff in one place but not the other item of the same category, i'd have to give the custom zone a very long list of item to be sorted here wich is very annoying and time consuming. With the solution proposed, once i've put all the type of things i want to be stored in one place, it would be just a matter of selecting the zone to have it done. Can't wait to see that!
