### ISSUE TITLE
"Ambush" scenario is unbalanced

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#34007]
# Describe the bug

Even if you survive the initial 10 minutes being surrounded by a horde of highly evolved zombies, you won't live for long because all the settlements are overrun by top-tier Zs, and it's nothing to forage in winter. This is much, much harder than the Evacuee scenario, yet it comes with the same 0 points price tag.

0.D-7603-g1b96ad13c5-dirty

**Comment by snipercup** [comment]
The simple solution is to add some points to this scenario, i can do that. I'm wondering though what causes the zombies to start top-tier? as you say you won't live long so isn't this scenario broken at this point? I don't know what causes the top-tier z's. The surrounded starts takes critters from the GROUP_ZOMBIE group, most of which are low-tier and the winter start just starts in winter so that does not explain it. Anyone know what causes the top-tier z's?

**Comment by l29ah** [comment]
Top-tier Z's are caused by the fact it's 9 months after the cataclysm start.

**Comment by snipercup** [comment]
That means any scenario with a winter start will have top-tier z's. My suggestion is to change the season to spring, since the focus of this scenario is the ambush, not increase difficulty because of winter. I guess removing the start winter flag will do. I'm not sure if it would justify adding 1 point or leave it at 0.

**Comment by Night-Pryanik** [comment]
List of professions available for Ambush scenario contains professions suited specifically for winter (`winter_survivor`, `winter_scavenger`, `winter_army`). So changing starting season would require changing the professions list.
I think the best solution would be to simply increase the scenario cost, taking all factors (winter, advanced professions, surrounded start) into account. Also we could rename the scenario to something like "Winter ambush" to reflect all important things this scenario has to offer.
