### ISSUE TITLE
Faction error on load with new experimental

### ISSUE THREAD

**Issue by reed501** [CleverRaven/Cataclysm-DDA#34084]
# Describe the bug

When loading my save on the new experimental, I get an error as soon as loading in about factions and my savegame. This happens on every load. What I see is at the bottom of attached debug.log, not sure why it's so long. I can hit space and there's no crash. Also, now my deathmobile and everything in it is owned by the free merchants.

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Debian; Description: Debian GNU/Linux 9.11 (stretch); Release: 9.11; Codename: stretch; 
- Game Version: 0.D-7691-g2e55fbb [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda]
]

# Additional context

I play with NPCs off.
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3625087/debug.log)

**Comment by jtriddle** [comment]
Same bug. After digging a bit, here what seems to be the problem:
The "factions" field in master.gsav turned into an object while it used to be an array (faction_manager::deserialize expects an array there).
faction_manager::serialize just does "jsout.write( factions )".
And factions field in faction_manager was changed from vector to map in one of latest PRs.

Reverting the game to earlier build and manually editing master.gsav to change "factions" back into an array fixed the error.
Actually fixing the bug is more involved and is better left to the author of the PR that introduced the change.

**Comment by ZhilkinSerg** [comment]
Possibly caused by #33970.

**Comment by davidpwbrown** [comment]
mea culpa. im on it.

**Comment by Torbenbeta** [comment]
After applying the newest version, my follower changed factions from my_followers to Hub 01 (which is also hostile). I am listed as archenemy for hub 01 (no quests have been done for them).
