### ISSUE TITLE
dog turd have extreme throwing range

### ISSUE THREAD

**Issue by Leviathan21** [CleverRaven/Cataclysm-DDA#34118]
# Describe the bug
dog shit have range of 30 to throw

# Steps To Reproduce
1. poop
2. throw
3. repeat
# Expected behavior
dog shit have throw range of 10

# Versions and configuration
 - OS: шindows
 - Game Version: 0.D-7582-gc2913a1 (tайлы)

**Comment by RickyVanz** [comment]
a small but funny issue, i can confirm this by my recent gameplay session, where i jokingly throw turd at zombies and it hit the zombies even though the range is 15+ from my character.

**Comment by kevingranade** [comment]
I took a quick rummage through the code, range is set in character::throw_range()
What's happening here is throw range is based on a strange system where an item can be thrown further based on how close it is to this ideal weight, and the item weight is relatively close to the ideal value, which is the range 135 - 150 grams.  The actual weight is 250 grams, which puts the total range at strength * 10 / 3.  For an even remotely reasonable strength of 10, that leads to a throw range of 33, though it is then capped at str * 3 + throw_skill, which as it turns out is a similarly high number, actually 33 of throw skill is 3 and strength is 10.
It turns out because of this skill/strength cap, that this ballpark of 30 - 40 or so on distance is going to dominate the whole weight vs strength thing in the rest of the method.

This whole scaling really needs to be changed, I found a nice paper with some decent derivations for baseline throwing force https://pdfs.semanticscholar.org/f6f9/83f9652ed0589d1ba92c1706c6782511f8a2.pdf and deriving range from initial throwing force and the remainder of item properties is fairly trivial.

https://github.com/CleverRaven/Cataclysm-DDA/blob/fe55636ed2c7392ef72a44fe06d027c8d43328ff/src/character.cpp#L3037-L3080

**Comment by y2s82** [comment]
the paper seems to take into account the mass (muscle mass, perhaps?) of the hand and forearm that is throwing the object, as well as the object's mass.  So what would be a good way to interpret strength 10 to the muscle mass, given the character uniformly trained strength on all body parts instead of the select muscles?
