### ISSUE TITLE
featreq new traits for resisting temperature

### ISSUE THREAD

**Issue by FONZACUS** [CleverRaven/Cataclysm-DDA#34178]
**Is your feature request related to a problem? Please describe.**  
well, guess you cant teach an old dog new tricks -.-, tried making 2 +/- traits for both heat/cold temperatures but failed. hopefully someone can pick it up later on. the 2 + traits only tried to raise acceptable 'comfortable' temperatures, while the 2 - ones lowered them.

**Describe the solution you'd like**  
these traits help curve the dangers from nature. i added bonuses for the pain and morale curving done, but couldnt seem to figure out how to raise/lower the 'comfy' zone and yeah, gave up. these could be later expanded by mutations. some of them have heat dependency, but i havent played around with mutations yet. bionics also have temperature curving but havent tried them too.

**Describe alternatives you've considered**  
struggle against the forces of nature for the time being.

**Additional context**  
IRL, people do prefer different climates i personally love the cold and hate the heat. it would probably be more realistic to have the 2 + traits contradict each other, but that could be down the road.

EDIT
also forgot to mention temperature shouldnt be able to break bones and stuff...

**Comment by EirenexTheDragon** [comment]
IT sounds like something that could work great with mutations that can use such values to have a different temperature tolerance with Cold or Warm enviroments

**Comment by kevingranade** [comment]
This sort of thing needs a rationale for why certain people would have more or less vulnerability to extreme temperatures.
If you're claiming it's a natural variation among people I need a source for that because I'm not aware of any such thing and if it's a mutation I would still like to know what the mechanism is whereby certain mutants would prefer higher or lower temperatures other than the amount of insulation provided by skin fur etcetera.
