### ISSUE TITLE
"using" field doesn't work as intended for construction recipe

### ISSUE THREAD

**Issue by Fris0uman** [CleverRaven/Cataclysm-DDA#34191]
# Describe the bug

None of the construction recipe  using `"using"` are loaded properly.
See Workbench or Dumpster: they can be build with no tool at all.

# Steps To Reproduce

1. Start Game
2. Press `*`
3. Look at workbench
4. Need no tool
5. Check recipe in json
6. Recipe is correct

# Expected behavior

This should work ` "using": [ [ "welding_standard", 15 ] ],`
But the code can actually only handle ` "using": "welding_standard",`

# Additional context

`requirement` is only a `requirement_id` in `construction.h` instead of         `std::vector<std::pair<requirement_id, int>>` in `recipe.h`

**Comment by lazho** [comment]
> requirement is only a requirement_id in construction.h instead of std::vector<std::pair<requirement_id, int>> in recipe.h

It could be changed to `std::map<requirement_id, int>` just like how `required_skills` is `std::map<skill_id, int>` and reuse similar logic for checking requirement. The logic to check requirements is in the function `can_make_with_inventory` in `requirements.cpp`

**Comment by lazho** [comment]
On further investigation, when a construction recipe has `using`, all other requirements specified through `tools`, `components`, and `qualities` are ignored as well. This makes the few recipes that has `using` in it basically free (other than requiring skill)

In `construction.cpp`, the logic replaces the entire requirement data with the `using` one rather than add it to the existing requirements.

**Comment by lazho** [comment]
PR is currently blocked by the fact that `requirements/toolsets.json` loads after `construction.json`, even though the construction recipes depend on requirements in that file. Any ideas?
