### ISSUE TITLE
Frozen items thaw really really fast when taken from minifreezer

### ISSUE THREAD

**Issue by PaulBlay** [CleverRaven/Cataclysm-DDA#34316]
Take a frozen item from a minifreezer and it is not even cold by the time it is in your inventory.

# Steps To Reproduce

* Stick a pile of objects in the minifreezer (e.g. Meat Pie)
* Wait till frozen, then wait some more just to be sure.
* Take one or two from the freezer
* Look in your inventory and find that it is no longer frozen

I would expect that it would take at least 20 to 30 minutes for a frozen meat pie to defrost completely at room temperature, maybe more.

![defrost](https://user-images.githubusercontent.com/54060142/65829435-760fca80-e29d-11e9-828e-8c0fcb16c4c9.png)

Windows-x64 Tiles Experimental 9661

**Comment by PaulBlay** [comment]
Update: It appears that the freezer sometimes also does not completely freeze items put in it in a timely way. For example, I put a stack of hot maple pies in there and they never got below (cold). Now they are instantly (rotten) when you take them out.

Maybe it has to do with putting hot items in the freezer? Probably not a good idea. (Real life or otherwise).

**Comment by DanteTorn** [comment]
I've had this issue myself a LOT actually. Often, items I put into my vehicle freezers (the big ones from blazemod) end up taking *days* to freeze while items I leave on the floor next to a vehicle cooler can actually be faster, or also not freeze properly.

I had a stack of literally almost 800 grapes and the entirety of it rotted to nothing because of this issue. :/

**Comment by Funguss** [comment]
Furthermore, I'm having things rot immediately... Reminds me of an old bug from years ago.

**Comment by Hirmuolio** [comment]
Probably same as  #36401
