### ISSUE TITLE
Recovery from Infection is a tedious chore.

### ISSUE THREAD

**Issue by Bulletfang** [CleverRaven/Cataclysm-DDA#34362]
**Is your feature request related to a problem? Please describe.**  
A clear and concise description of what the problem is. Ex. I'm always frustrated when [My character recovers from an infection, and the frequent blackouts prevent me from doing anything at all, even sleeping and waiting. I have to spam sleep or wait, which is a massive, fun-strangling chore, as the blackouts happen about 30 times per hour, and I have to do it several in-game days on top of it, which can last up to an hour irl. This is extremely frustrating.]

**Describe the solution you'd like**  
An option that becomes available in addition, or as a replacement, to the sleeping or waiting option, let's call it: Bed-rest. It's exactly like sleeping or waiting, but prevents the symptoms of the infection from interrupting it.

**Describe alternatives you've considered**
Have waiting not get interrupted by blackouts.

**Comment by jtriddle** [comment]
It would be nice if at least sleeping (or trying to fall asleep) wasn't interrupted by passing out. It's really werid.

**Comment by jtriddle** [comment]
There is also a small bug involved. Back when the game switched from 6s to 1s turns a lot of things had to be rescaled. Infection effect was rescaled (its int_dur_factor), but infection recovery wasn't. As a result in most cases it will start at max intensity.

**Comment by GroeneAppel** [comment]
I'd like to add to this that it is somewhat odd that a player on antibiotics with an infected wound earlier on is absolutely fine. However once the infection is cured and the recovery status is triggered, the player starts blacking out. 

I would expect no blackouts whatsoever in that situation and otherwise i'd expect the occurance of blackouts to drasticly decrease as the recovery progresses.
