### ISSUE TITLE
Jumper Cables do not connect to UPS in Aftershock mod. 

### ISSUE THREAD

**Issue by x7GoSu** [CleverRaven/Cataclysm-DDA#34464]
# Describe the bug

UPS and Advanced UPS in the aftershock mod does not have the "IS_UPS" flag, preventing
the use of cable chargers as they seem to overwrite the base versions.

# Steps To Reproduce

1. Have player with a cable and ups.
2.  Activate cable to pick connection, choose ups.

# Expected behavior

To connect cable to ups because it gives the option to connect.

Apologize if this isn't the right place to submit this I could not find an active place for the AFS mod to submit the bug. Also I would fix this but the process seems  to be extremely intimidating sorry. =(

**Comment by Nerezza** [comment]
I've investigated this after encountering the issue myself. It's entirely a JSON problem, the flags for UPSes in AFS haven't been updated despite the changes they've received in the past 6 months.

Aside from not being able to connect them to a jumper cable, you also can't unload the new batteries from the standard UPS because it still retains the "NO_UNLOAD" flag. Someone just needs to go into afs_tools.json and re-do the flags for UPS_off and adv_UPS_off, so only 2 lines changed really.
