### ISSUE TITLE
NPCs unable to open tent flaps

### ISSUE THREAD

**Issue by Binary-2** [CleverRaven/Cataclysm-DDA#34646]
# Describe the bug

When NPCs are in faction camp tents, they are unable to open tent flaps.

# Steps To Reproduce

1. Create a faction camp tent
2. Put an NPC in the tent and close the flap
3a.Walk out and close the flap on the NPC, even if they are told they can open doors, they will not open the flap and be stuck.
3b. Tell the NPC to do something for the camp, they'll be stuck in the tent and be unable to complete the task.

# Expected behavior

The NPC should open the flap

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.D-8405-gb915f8b (tiles)
 - Mods loaded: dda, Disable NPC Needs

**Comment by KnightosMaster** [comment]
It seems like NPCs don't handle furniture with DOOR tags well, since with other furniture doors they just "phase" through without opening it, but since canvas flaps have a move_cost_mod of -1 they ignore it and pathfinding fails. A quick fix is increasing this to 0, which is reasonable, but NPCs should also properly open and close furniture doors too.
