### ISSUE TITLE
Down Mattress Errors

### ISSUE THREAD

**Issue by ANickelN** [CleverRaven/Cataclysm-DDA#34662]
# Describe the bug
When scrolling over the entry for down mattress in the crafting menu, it is written as "down_mattress" and gives this error when selected.

 DEBUG    : invalid furniture id "f_feather_mattress"

 FUNCTION : const T& generic_factory<T>::obj(const string_id<T>&) const [with T = furn_t]
 FILE     : src/generic_factory.h
 LINE     : 356

# Steps To Reproduce

Scroll over the down mattress entry.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-8418-g126c27b [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    [DP_MOD] Hide DEBUG [DP_No_Debug_Tile],
    No Fungal Monsters [No_Fungi],
    Disable NPC Needs [no_npc_food]
]

**Comment by snipercup** [comment]
The item called down_mattress has a "use_action": { "type": "deploy_furn", "furn_type": "f_feather_mattress" } except the furniture f_feather_mattress does not exist. It was added by #33923. To fix this, I think the use action should use 'f_down_mattress' instead of 'f_feather_mattress'.

Good beginners issue.
