### ISSUE TITLE
Quarter Panels are not Transparent Walls

### ISSUE THREAD

**Issue by EkarusRyndren** [CleverRaven/Cataclysm-DDA#34707]
# Describe the bug

As the game seems to have implied from the vanila designs as well as others quarter panels seem to serve the purpose of being the "hood" (or trunk) of a car. Something that holds parts such as the engine or tunk-stuff but able to be seen over.

In practice, you could climb over them in reality. In game, this cannot be accomplished at the moment and as such they're being used as transparent walls by most players.

# Expected behavior

Ideally, quarter panels wouldn't block weather, completely block projectiles, and be able to be climbed over slowly by creatures.

# Additional context

One of the primary reasons for using quarter panels over windshields of any kind is weight and the other is durability compared to a quarter panel. It may be prudent to include some kind of makeshift screen or grate that won't block smaller projectiles every time or weather at all that doesn't include any glass.

**Comment by Little-119** [comment]
Making them able to be climbed on would let monsters enter a vehicle when they shouldn't be able to, but that could probably be fixed by not allowing creatures to move to a tile on a vehicle with a roof from a quarterpanel.

**Comment by EkarusRyndren** [comment]
@Little-119 Except that quarter panels aren't walls, they're meant to be half-walls basically. Monsters being able to get in through them is kind of the point.

**Comment by Little-119** [comment]
On reconsidering this, I think the problem may be that the game doesn't distinguish between a solid quarterpanel that connects to the roof and a quarterpanel with a big hole in it where a windshield would go, and it doesn't factor in the height of roofs. Making the game distinguish between those would probably be necessary in order to fix this without letting creatures phase through vehicles that are meant to represent sealed vehicles.

**Comment by EkarusRyndren** [comment]
@Little-119 I understand that in the car design there are a handful of quarter panels that are used as transparent walls but frankly they need to be redesigned and probably make use of a mirror mechanic or something considering that in most modern cars you've got blind-spots where the frame blocks your view. The entire point of this bug report is the realism-breaking transparent walls that are currently being used simply to exploit one system or another in custom construction.

**Comment by Karthas077** [comment]
> On reconsidering this, I think the problem may be that the game doesn't distinguish between a solid quarterpanel that connects to the roof and a quarterpanel with a big hole in it where a windshield would go, and it doesn't factor in the height of roofs. Making the game distinguish between those would probably be necessary in order to fix this without letting creatures phase through vehicles that are meant to represent sealed vehicles.

A naive solution is to just assume that every instance of a quarter panel adjacent to a roof has a gap unless explicitly filled with a windshield. Any instance of a quarter panel leading directly to a roof rather than a windshield would be more accurately represented in-game with a board or something else that explicitly disables traversal.
