### ISSUE TITLE
Infinite Vehicle Energy Generation

### ISSUE THREAD

**Issue by TKTKO** [CleverRaven/Cataclysm-DDA#34703]
Description of issue: 
Unlimited energy generation using Foot Pedals and a vehicle battery.

Construct a 2x1 Wooden Frame stationary vehicle to generate power (Wooden Seat, Dashboard, Foot Pedals, and Motorbike Alternator on first frame. Electric Motor and Motorbike Battery on second frame), setting speed to maximum and then using "Let go of controls" option, the vehicle continues to charge.

Expected behavior:
Battery should not charge without player using pedals.

Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-8450-g8db2a17 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Armor Up! PA Utilities [ArmUpPAUtil],
    Armor Up! Survivor Expansion [ArmUpSurvEx],
    Bens GF recipes [Tolerate_This],
    Craft Ammo Mags & Belt Links [SD_Magcrafting],
    Craftable Gun Pack [craftgp],
    Garden Pots [growable-pots],
    Icecoon's Arsenal [ew_pack],
    More Survival Tools [More_Survival_Tools],
    Boats [boats],
    MST Extra [MST_Extra],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    Extended Realistic Guns [realguns],
    Craft Ammo Mags - ERG [SD_Magcrafting_Realguns_Extension],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    EZ-Mode Medical [fast_healing],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    More Locations [more_locations],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Roadheader and other mining vehicles [Heavy miners],
    Tanks and Other Vehicles [Tanks],
    Classes and Scenarios Mod [more_classes_scenarios],
    Classic Roguelike Classes [RL_Classes],
    Manual Bionic Installation [manualbionicinstall],
    Nonperishable Overhaul [Nonperishable_Overhaul],
    Safe Autodoc [safeautodoc],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Karthas077** [comment]
I might have tracked down the source of this problem. I'll see about checking this when I get done with work unless someone else gets to it before me.

Current theory:
1 - Alternators attempt to produce power if ANY engine is on.
2 - Electric engines do not consume power when "idle", so the idling electric engine is causing the alternator to try to generate power.
3 - The actual check for if the alternator is working, just checks to see if the engine it is attached to is enabled, not that it's actually on/consuming fuel.

**Comment by Zourin2** [comment]
There might be a 'perpetual motion machine' issue with the electric motor on the second block powering the alternator on the first.

**Comment by AlexMooney** [comment]
I had an electric scooter with pedals charging up as a rode it.  I don't think I could make a 400 lb vehicle cruise at 21 mph and charge a battery on muscle power without stamina drain, so it's probably related to this electric motor shenanigans.

**Comment by Karthas077** [comment]
> If it's being 'throttled up' as a co-engine to the pedals, it wouldn't be idle

The current code determines if an engine is idle based on if the vehicle is moving, so for the specific example given in this post, the electric engine is in fact idle and therefore not draining electricity but still generating torque for the alternator.

After stepping through the engine/alternator calculations with the debugger, the process goes something like this: 
1 - Letting go of a vehicle stops the muscle engine, but does not turn off ALL engines, causing the vehicle to start idling.
3 - An idling vehicle calculates energy drained by electronics, energy produced by alternators, horsepower produced by engines, horsepower drained by alternators, and fuel drained by engines.
4 - An idling electric engine produces horsepower but does not drain fuel. (#27166)
5 - The alternator consumes the free horsepower to generate electricity.

The problem is twofold:
1 - Idling electric engines should not be producing horsepower if they're not draining fuel.
2 - Alternators only care if the engine they are attached to is toggled enabled, not if it is currently running.


I can't state with certainty that this is also responsible for the behavior @AlexMooney is experiencing, but it would probably be best to investigate it after this part has been fixed.

**Comment by mlangsdorf** [comment]
Alternator load is the sum of alternator power for all alternators that return true from `is_alternator_on()` divided by the sum of engine power for all engines that return `is_engine_on()`.  That's probably wrong and we should sum the power of only the engines that can mount alternators.

Alternator power production is the sum of power production for all alternators that return true from `is_alternator_on()`.

`is_alternator_on()` only returns true if there is an available, enabled engine at the same mount as the alternator, so I don't see how an enabled electric motor at mount (0, 0) makes the alternator at mount (1,0) on the combustion engine count for `is_alternator_on()`.

**Comment by Karthas077** [comment]
The foot pedals don't get disabled when the player releases the controls, they just lose fuel. I fixed that by just having the alternator also check if the engine has fuel left instead of just being enabled at all.
