### ISSUE TITLE
Labs Collapsing

### ISSUE THREAD

**Issue by Phrux** [CleverRaven/Cataclysm-DDA#34752]
# Describe the bug

As soon as you start a lab run you can hear SMASH noises from far away as large parts of the lab collapse into rubble. Sometimes if you spend a long time in a specific spot- like when dismantling a turret- that area will collapse. Only noticed that at the entrance to the labs, though.

# Steps To Reproduce

1. Go to any moderately sized room in lab
2. Set strength to 500
3. Smash wall
4. Huge area collapses

# Expected behavior

Labs not randomly collapsing

# Screenshots

https://cdn.discordapp.com/attachments/459526544260333599/633363272153694219/rubble_lab.png

UPDATE: https://cdn.discordapp.com/attachments/598523535169945607/633436057232343041/HMM.png Perhaps a problem with the concrete floor?
# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-8520-gcb7938e [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Mythological Replicas [nw_pack],
    Alternative Map Key [alt_map_key],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    Mythical Martial Arts [MMA],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    No Flaming Weapons [no_flaming_weapons],
    Disable Religious Texts [no_religious_Texts],
    Classes and Scenarios Mod [more_classes_scenarios],
    Safe Autodoc [safeautodoc],
    Simplified Nutrition [novitamins],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    C.R.I.T Expansion Mod [crt_expansion],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Icecoon's Arsenal [ew_pack],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    No Rail Stations [No_Rail_Stations],
    No Fungal Monsters [No_Fungi]
]

# Additional context

**Comment by KorGgenT** [comment]
#34694 possibly related?

**Comment by Night-Pryanik** [comment]
Are you sure it's not a giant naked molerat burrowing nearby?

**Comment by DatMeg** [comment]
> 
> 
> Are you sure it's not a giant naked molerat burrowing nearby?

It's not a Mole Rat. However, I have seen these collapses in the same area as Shimmering Portals, extending multiple z-levels perhaps it's related to their generation?

[https://i.imgur.com/8p99pw3.png](url)

**Comment by mlangsdorf** [comment]
I was just walking through a lab when suddenly everything within the reality bubble got turned to rubble, including my deathmobile one z-level up.

**Comment by mlangsdorf** [comment]
Here's what I think is happening:
1.  someone smashes the floor of lab at z-level -1 or lower hard enough to turn it to rubble.
2. z-level -1 lab floors have "SUPPORTS_ROOF", rubble does not, so all adjacent points on the same level check for collapse_at()
3. any of those points that calls for collapse_at(), then checks collapse_at() again for 26 points adjacent on the same level or the level above or the level below.  So this recursively calls collapse_at repeatedly, and some points may get multiple checks against collapse_at() -- I saw up to 14 checks in one case.
4. incidentally, collapse_at() calls destroy(), which bashes any vehicle at those points 25 times for 999 points of damage, so say goodbye to your deathmobile.

Here's my vague plan for a solution:
1. there needs to be a distinction between SUPPORTS_ROOF and HAS_ROOF.  Interior floor sections should have HAS_ROOF, not SUPPORTS_ROOF.  In the short term, I think HAS_ROOF can be approximated by SUPPORTS_ROOF && INDOORS
2. there needs to be a couple of rubble variants, including one that is HAS_ROOF (or INDOORS and SUPPORTS_ROOF) and represents a wrecked interior floor with a roof overhead.  Similarly, there should be open_air variant that has HAS_ROOF and another one with just INDOORS if there isn't already.
3. Bashing a tile with HAS_ROOF just smashes that tile and doesn't cause a collapse.
4. if a collapse chain starts from a wall (ie, SUPPORTS_ROOF but not INDOORS) then adjacent tiles with HAS_ROOF convert to INDOORS rubble without SUPPORTS_ROOF and the tile above them converts to open_air and keeps the previous tile's HAS_ROOF status.  Collapsing tiles can keep the chain going.
5. If a wall (SUPPORTS_ROOF but not INDOORS) collapses, it attempts to collapse the tile above it and if that tile collapses, it checks for collapse for all adjacent tiles.
6. The basic concept is that collapses radiate from collapsing walls vertically and horizontally at the next z-level up as floors convert to open_air.  If a floor converts to rubble on the current z-level, that shouldn't cause any additional collapses.

**Comment by ralreegorganon** [comment]
I think [these changes](https://github.com/CleverRaven/Cataclysm-DDA/pull/34694/files#diff-ab005ad9757130721ffb66a09833090aR2936-R2944) need to be reverted and the issue tackled again with a little more rigor and testing.

The definition of what has a roof is a little more complicated, because the behavior differs depending on if z-levels are enabled or not. There is a [method for getting the roof](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/map.cpp#L3061) that will utilize the "roof" definition from the terrain's json, but usage of it ends up dancing around the z-level issue and doing things like just setting it to dirt.

We also [use this roof definition](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/map.cpp#L7418) to put a roof on a location if z-levels are enabled by walking the z-levels from the minimum to the maximum and if the terrain is open air, checking the roof definition of the floor below us and setting the terrain to that.

The changes I mentioned before made it so the collapse check calls points_in_radius with a z radius now also, and then iterates over those points and processes them, but it's probably worth making sure that the points are processed in an order that makes sense--it would be problematic if it jumps around z-levels or does it in a non-nonsensical order.

A couple comments on the solution plan:

re: 1 - I don't think we want to introduce a HAS_ROOF flag, but I absolutely agree that there should be a distinction between a tile that just has a roof, and a tile that actually supports a roof.

re: 2 - Some time ago, the rubble terrain (t_rubble) was eliminated in favor of placing `t_dirt` and `f_rubble` and some rocks when loading the save game, and just leaving the underlying terrain intact when calling `make_rubble` unless it's impassible, so there is no actual rubble terrain which we'd modify to do a wrecked interior floor with a roof overhead / open air variant. I don't think we want to re-introduce a special terrain for this.

re: 3 - I agree

re: 4, 5, 6 - I agree with the spirit / basic concept of this, and just based on past experiences with floor/roof destruction (namely #27015) I think it'll very much be a devil in the details sort of thing (see my comments [here](https://github.com/CleverRaven/Cataclysm-DDA/pull/27015#issuecomment-447102111) for example, including an aside about COLLAPSES and SUPPORTS_ROOF).

So, overall, the proposal makes sense to me but I'd rather see us tackle from a point of before [these changes](https://github.com/CleverRaven/Cataclysm-DDA/pull/34694/files#diff-ab005ad9757130721ffb66a09833090aR2936-R2944) were applied rather than after.

**Comment by mlangsdorf** [comment]
I didn't realize that rubble for furniture until after I wrote that; we don't want to return to `t_rubble`.  I think I can do everything I want with INDOORS and SUPPORTS_ROOF for now.

I'll check over those PRs, thanks.
