### ISSUE TITLE
Tac Vest's Encumbrance when full is too high

### ISSUE THREAD

**Issue by KurzedMetal** [CleverRaven/Cataclysm-DDA#34768]
# Describe the bug
Tac Vest Encumbrance seems prohibitively high.
![image](https://user-images.githubusercontent.com/1426680/66804428-cec7a000-eef8-11e9-9286-2c63a35f5747.png)

# Expected behavior
Not having twice as much encumbrance as a Backback for 1/5 of the capacity.

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-8494-gc95073d [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key],
    Mutant NPCs [mutant_npcs]
]

**Comment by mrkybe** [comment]
The description/mechanics are also unclear.  As the Tac Vest can store 4 mags, being full could either be interpreted as having all 4 mags stored or using the provided 3L of storage.  As a new player, I'd probably assume its talking about the number of mag storage spots used, but is it?  Or is it just talking about the 3L of storage.

**Comment by kevingranade** [comment]
The variable encumbrance is just based on volume stored, it doesn't look at slots at all.
Similarly, it's not "2x capacity for 5x encumbrance" because that also doesn't incorporate the slot capacity.

I'm not saying you're wrong overall, but the question isn't how it compares to a backpack, but whether it portrays the tactical best correctly.  I'm actually really sceptical of it having any significant storage capacity other than the holsters in the first place, if I skim through product listings for this kind of thing, it looks like other than holster storage, they only tend to have map storage, which is less than a quarter liter, not 3 litres.

**Comment by tenmillimaster** [comment]
I think earlier it was based on load bearing vests like ALICE and the like.

![LBV:](https://image.sportsmansguide.com/adimgs/l/6/674381_ts.jpg)

I was picturing it as one of these ![Vests](https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRHTOn0o6G2e-qvSkYL8R9ng4KP1slSyRmJYI7TbGNs4LvEH43a)

They're more common; I figured since it couldn't hold a gun, and like 6 mags, volume would be easier.


Do we have support for multiple item contents?
