### ISSUE TITLE
Silat should also be usable in unarmed combat

### ISSUE THREAD

**Issue by Lamandus** [CleverRaven/Cataclysm-DDA#34816]
Pencak Silat is actually mostly an unarmed style. Since it uses weapons only if necessary.

**Describe the solution you'd like**  
At least some moves or dodgebonus when unarmed.
.

**Additional context**  
Just examples:
https://www.youtube.com/watch?v=tmcjEpL42Fs
https://www.youtube.com/watch?v=TB-a91k65cw
https://www.youtube.com/watch?v=6uoOBur3ffs

As you can see, most of these moves are either disarming, immobilizing and when immobilized hard hitting.

If any more questions come up, I try to be of service.

**Comment by thethunderhawk** [comment]
>uses weapons only when necessary

Where are you getting that from? 

From the Wikipedia page for Silat: “Prior to the introduction of firearms, weapons training was actually considered to be of greater value than unarmed techniques and even today many masters consider a student's training incomplete if they have not learned the use of weapons.“

You still get +1 dodge and an OnDodge accuracy buff while unarmed.

**Comment by Lamandus** [comment]
> 
> 
> > uses weapons only when necessary
> 
> Where are you getting that from?


From the trainer who trained my wife in Java/Indonesia. Because as it says prior to the introduction of firearms. Nowadays it is more about unarmed combat than weaponised. And as it stated, nowadays without weapons it may be "incomplete" but that means that unarmed is much more important than armed and some trainers (wife's one for example) consider it fully trained without any use of weaponary.
It is not highly encouraged, it is more "based on older times". More modern Pencak Silat is mostly unarmed.

**Comment by Lamandus** [comment]
> 
> You still get +1 dodge and an OnDodge accuracy buff while unarmed.

that is not true anymore. Silat unarmed doesn't give you dodge anymore. See 
https://github.com/CleverRaven/Cataclysm-DDA/issues/34747

**Comment by thethunderhawk** [comment]
Good point, focusing on hand to hand weapons skill does make less sense in a world with guns. Might be hard to balance if you were to add more unarmed techniques though, since it’s currently filling the niche for a crit-focused melee style. I think any buff to it’s unarmed capability might need to be tempered by a nerf to its melee capability. Any ideas for how to handle that?

**Comment by Lamandus** [comment]
Not really. Maybe leave the higher crit chance but normal hits do less damage, since it is a very fast style to use.

**Comment by Hymore246** [comment]
The problem with this suggestion is it's effects on game balance. Unarmed and weapon styles are separated in balance due to weapons making styles MUCH stronger. Allowing a weapon martial art to be used unarmed means it must be balance against every other unarmed martial art. You have to ask yourself why you wouldn't want to use Silat instead of another unarmed style. The ability to just equip a strong weapon will make Silat out damage most unarmed styles while getting rid of the risk of becoming helpless if disarmed. Some styles are different enough to still stand out but others like Pankration would be completely overshadowed since Silat does roughly the same thing but with more damage. 

A similar problem would happen with Eskrima vs all "speed styles" like Centipede, Leopard, and Snake. Realism or not, this change would require multiple style rebalances to prevent Silat and Eskrima from becoming the "go-to" styles for players and making other styles worthless.

If you want an in-game reason, maybe the Silat in-game is a style of Silat that focuses exclusively on weapon combat. Silat and Pentjak Silat are both umbrella terms used to describe hundreds of martial art styles that are from Brunei, Indonesia, Malaysia, Singapore, and portions of the Philippines. It isn't unreasonable to believe that the CDDA version of Silat only uses weapons.

**Comment by Lamandus** [comment]
Well, then we need to question ourselves the goal of the game and balancing.

On the one hand people add and change stuff to cater to realism (for example the turret changes) with balance being the 2nd goal. Then we have you who rather change to cater balance over realism.

But let me ask: so what if Silat is stronger than other weapon styles? What if eskima is stronger than other fast styles.

If you see crafting, there is a lot of unbalance (axes for example) and it just reflect real life more than anything.

Yes, Silat is an umbrella term. But to pick the most impossible one of all (just weapons, not hand to hand) is not really immersive.

**Comment by Hymore246** [comment]
> Well, then we need to question ourselves the goal of the game and balancing.
> 
> On the one hand people add and change stuff to cater to realism (for example the turret changes) with balance being the 2nd goal. Then we have you who rather change to cater balance over realism.

Balance matters. I'm not opposed to realism, but it isn't an end all justification to make changes. You can't just make changes based on realism and not consider how it affects the rest of the game. Also, exceptions have to be made due to the limitations of how CDDA works. Sometimes you CAN'T add the realism in the exact same way as real life because CDDA isn't a perfect recreation of the world. This is why Judo doesn't have 67 different throws, why Krav Maga can't do everything, and why every single martial art in the world is not in CDDA. 

> But let me ask: so what if Silat is stronger than other weapon styles? What if eskima is stronger than other fast styles.

Then there is no reason to ever take those other styles. Compare the old versions of Dragon Kung Fu and Zui Quan to Aikido and Tai Chi. There was no contest that Dragon and Zui Quan were better defensive styles. Even after the rebalance of Aikido and Tai Chi, they would STILL be inferior to old Dragon and Zui Quan due to how powerful the styles were. It ends up becoming a question of why we even have Aikido or Tai Chi at all if they were so terrible. This is actually justification to remove Aikido and Tai Chi from the game and trivializing things like this is never a good idea.

> If you see crafting, there is a lot of unbalance (axes for example) and it just reflect real life more than anything.

First of all, you can't use the imbalances of one part of the game to justify it in another part. That just means that crafting ALSO needs to be fixed. 

Second, creating weapons requires the right recipes, skills, materials and non-trivial tools. It takes time and effort to get that Battle Axe. Almost all martial arts are available at the start of the game for 3 points. So they need to be balanced against each other. Even those that are not available at the start are still balanced as if they were because the rarity of a style is an external factor to the martial art's balance. It's completely possible that Bionic Combatives could be usable at char gen if a profession with the CQB CBM is added. If the style was balanced on rarity, it would need to be rebalanced to account for the char gen change.

> Yes, Silat is an umbrella term. But to pick the most impossible one of all (just weapons, not hand to hand) is not really immersive.

 The original creation of the martial arts system was done back in 0.B which is over 6 years ago. I do not know who the original authors were or there intent but Silat was added as a weapon style. Silat was balanced with this understanding in mind and as far as I know Silat (and Eskrima) were meant to just use weapons. 


In truth, I'm not opposed to unarmed Silat but it can't just be added without considering the impact. When I started the martial arts rebalance (#32422), the fact Silat and Eskrima could be used unarmed was unknown to me and I did not take that into consideration when I began changing the styles. While the time to make Silat usable while unarmed is trivial (3 minutes at most), making this change would completely throw off the balance of other styles and would take a large amount of time to brainstorm, change, test, and balance at least a half dozen styles to make sure Silat doesn't overperform. Silat (and Eskrima) would likely be nerfed as a result of these changes too.

Ideally, I rather let the rebalance finish and let the dust settle before someone makes a big change to a martial art style. I can only hope that change will make another Dragon Kung Fu.

**Comment by Lamandus** [comment]
> > Well, then we need to question ourselves the goal of the game and balancing.
> > On the one hand people add and change stuff to cater to realism (for example the turret changes) with balance being the 2nd goal. Then we have you who rather change to cater balance over realism.
> 
> Balance matters. I'm not opposed to realism, but it isn't an end all justification to make changes. You can't just make changes based on realism and not consider how it affects the rest of the game. Also, exceptions have to be made due to the limitations of how CDDA works. Sometimes you CAN'T add the realism in the exact same way as real life because CDDA isn't a perfect recreation of the world. This is why Judo doesn't have 67 different throws, why Krav Maga can't do everything, and why every single martial art in the world is not in CDDA.

But CDDA COULD have all styles, throws etc.. THe reason it is not in the game is just because noone took the time (which I am perfectly fine with). But the limitation of CDDA works is not appliaple in any shape or form in this case.

> > But let me ask: so what if Silat is stronger than other weapon styles? What if eskima is stronger than other fast styles.
> 
> Then there is no reason to ever take those other styles. Compare the old versions of Dragon Kung Fu and Zui Quan to Aikido and Tai Chi. There was no contest that Dragon and Zui Quan were better defensive styles. Even after the rebalance of Aikido and Tai Chi, they would STILL be inferior to old Dragon and Zui Quan due to how powerful the styles were. It ends up becoming a question of why we even have Aikido or Tai Chi at all if they were so terrible. This is actually justification to remove Aikido and Tai Chi from the game and trivializing things like this is never a good idea.

Some did take these styles, because even when inferior to others, these were the ones they found on doyos, or they liked the flavour of using it. Sure, you can go min max, you can freeform, even, where balance is just an excuse.

> > If you see crafting, there is a lot of unbalance (axes for example) and it just reflect real life more than anything.
> 
> First of all, you can't use the imbalances of one part of the game to justify it in another part. That just means that crafting ALSO needs to be fixed.

But why exactly? The world we are living in is not balanced. That is what made CDDA interesting. What will be the next step? Level caps? Some things have advances over other. We shouldn't kill immersion and gameplay for "balance".

> > Yes, Silat is an umbrella term. But to pick the most impossible one of all (just weapons, not hand to hand) is not really immersive.
> 
> The original creation of the martial arts system was done back in 0.B which is over 6 years ago. I do not know who the original authors were or there intent but Silat was added as a weapon style. Silat was balanced with this understanding in mind and as far as I know Silat (and Eskrima) were meant to just use weapons.

The reason can be seen in the old code. It was meant as weaponized AND unarmed style. Silat and Eskrima can use both. And from a realism standpoint, why can you dodge better when you have a stick in the hand instead of nothing is beyond me. I rather have some sort of grip on realism than just arbitrary changes and "balance". Rather change the name of the styles to be somewhat near the original, but not the original, same with antibiotics, because this doesn't look right.

**Comment by Hymore246** [comment]
I have feeling that this argument is just going to drag out if we keep going, so I'll just say this:
* I explained the reason not having 67 throws and other design choices for martial arts in my Muay Thai rebalance (https://github.com/CleverRaven/Cataclysm-DDA/pull/34070#issuecomment-532428575)
* Real life isn't balance but CDDA is game and should be. The game is meant to be fun and not a chore. It's impossible to completely recreate the real world in CDDA with 100% accuracy no matter how hard anyone tries.
* No one would use old Aikido if they found a manual in-game due to it's permanent -50% damage. Nothing old Aikido had was worth that penalty and old Aikido has been acknowledged by the community as the worst functional martial arts style.
* I don't know why all martial arts have the same cost. I assume it was for game balance. I saw no reason to change the cost with the rebalance.

I believe your approach to adding changes for the sake of realism with no concern to how it affects the rest of the game will hurt CDDA in the long run. I encourage you to understand why the game needs balance to be worth playing.

I've covered everything that needs to be said in my previous replies. I'll be going now. Thank you for your time.

**Comment by Lamandus** [comment]
I still keep that as the last word, as it is just a repeatition of what I said and still holds.
> And from a realism standpoint, why can you dodge better when you have a stick in the hand instead of nothing is beyond me.
Since you are not willing to do something about it, I think we should stop discussing, because that would lead to just talk against a wall.

**Comment by Zireael07** [comment]
Maybe worth revisiting in the future (the point about Silat burning through stamina fast is very valid), although I'm not sure if it's worth changing the implicit equal balancing and point cost of the martial arts.
