### ISSUE TITLE
Casing crafting - a half decent attempt

### ISSUE THREAD

**Issue by shotgunfrenzy** [CleverRaven/Cataclysm-DDA#34834]
**Is your feature request related to a problem? Please describe.**  
I've always thought it weird that with all the materials you can collect in game, all the tools to use them to create new things. You can use casings to make reloaded bullets, but good lord creating the casings themselves is impossible apparently? Also as a gameplay improvement, getting certain guns and having 1/8th of a clip of ammo to use, then borderline never using that weapon again, just for the sheer fact you'll almost never find the ammo, plus you won't have the casings to reload them and use again.

**Describe the solution you'd like**  

- A feature similar to how vanilla bullets can be deconstructed into their separate parts, with certain tools such as any of the current forge items and maybe something like metal tongs and the like, you can deconstruct x amount of ammo casings into either scrap brass or the brass item itself (similar to how scrap copper or copper tubing can be deconstructed into copper (100)).

- Then with this brass you can use a new recipe to craft bullet casings.
- depending on how this will be balanced, ideas include.
- Recipe Might be locked to the gun books and the hand loaders helper books.
- Fab skill requirements might be a level lower than what the completed shoot able reloaded bullet recipe is.
- Recipe requirements may include, x type of forge item, swage and die set, metal tongs, anvil, plastic mold or a new item, cast iron mold, and of course an already scavenged bullet casing of the type you are trying to create

**Describe alternatives you've considered**  
Brass resource returns for deconstructing certain bullet casings might give lower yields, such as low caliber pistol casings, if you deconstruct and melt down 200, you might only get 100 or 75 brass, where as more rare casings, such as .308 or .50 could give either a 1/1 yield ratio or 2/1

**Additional context**  
None thought of presently

**Comment by tenmillimaster** [comment]
What you are describing is possible.

But the components listed are incorrect.

You will want- drawings of casing dimensions, which are in handloading books.
Calipers.
A lathe.
Some high speed steel, or other form tools.

Also, the brass you will be machining will not be as strong as factory drawn brass. That may be in issue in medium to high pressure loads.


Another route that you can go down is drawing up ballon head  casings, thinner sheet metal early casings.  These are even weaker, so expect old west level pressures.


In reality, making casings is feasible and practical for a community, not a single person.


Part of the problem is guns don't drop exactly as many brass casings as are fired, which they should.

**Comment by kevingranade** [comment]
The proposal is invalid, as @tenmillimaster outlines, it is a much more involved process. But rest assured, as soon as we have the appropriate tooling, casings will happen.
