### ISSUE TITLE
NPC don't put back tools

### ISSUE THREAD

**Issue by FunkleBlaze** [CleverRaven/Cataclysm-DDA#34876]
# Describe the bug

After job is done NPCs don't put back tools

# Steps To Reproduce

1. Give NPC something to do which require tools (tree chopping).
2. Wait until it is done (or disable area to speed up it).

# Expected behavior

NPC put back tool in 'tool zone'.

# Versions and configuration

 - OS: Windows
 - Game Version: 0.D-8583-g08353e3 [64-bit]
 - Graphics version: Tiles
 - Mods loaded: 
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    Hydroponics [hydroponics],
    Vehicle Additions Pack [blazemod],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]

# Additional context

After job is done, NPCs just start to follow me.

**Comment by davidpwbrown** [comment]
Ah there may be a  misunderstanding here, they dont put the tool back in th etool zone, they put it back in an unsorted zone, if there is one.This is intentional, so that all your tools dont end up scattered across various other zones, you have a central repository where they are stashed when finished with.

**Comment by davidpwbrown** [comment]
Yeah jsut tested, and they pick up the wood axe fine, and put it back afterwards into a nearby unsorted loot zone.
