### ISSUE TITLE
Fire applied to Fungus for !!FUN!!

### ISSUE THREAD

**Issue by EkarusRyndren** [CleverRaven/Cataclysm-DDA#34883]
**Is your feature request related to a problem? Please describe.**  
A frequent and common solution to encountering the Mycus is to just burn it all away. I have an idea.

**Describe the solution you'd like**  
A handful of mushrooms in the real world release their spores when significant heat is applied to them. As such, I see no reason why a hive-mind of fungus wouldn't _borrow_ this feature. Spores would if this is applied probably need to be immune to fire.

**Describe alternatives you've considered**  
It may be prudent to lower their spawn-rate if this is added.

**Additional context**  
For whatever it's worth, making this change would make sprayable fungicide considerably more valuable and not something you do when you've got excess resources.

**Comment by zeggz** [comment]
Wow, you must be some kind of masochist! :-)
Fungus are already by far the most "world ending" creature in the game due to the speed they reproduce and expand. I've still haven't found a reliable way to eliminate them faster than they spread. Even fully loaded for the task (flamethrowers, fungicide, incendiary device...) they are just too fast. Util we can air drop fugicide on a large scale, i don't see how to fight them with succes.

More seriously, when they die they already realease spores even if they die from fire, and some spore fly away from the fire. It seem to already work as you describe minus the fire restistance, so.... not sure if adding a resistance to one of the only two things that can harm them in some mesure would be a good idea. I'm more in favour of nerfing them just a bit (their spreading rate), or adding better way to fight them (requiring time and effort in preparation or even better a full quest line) or at least way to contain them. But hey, that just my thought on the matter.

**Comment by MrOlaf** [comment]
Fungus will convert and deplete an area faster than player is able to clear it, clearly evidenced by the amount of people on reddit and even Vormithrax turning fungus off or just running away on the overmap to keep the fungus outside of their reality bubble. 

Fungicide grenades and makeshift fungicide sprays are hard enough to make to be used solely for fungal flowers and fungal towers due to resource constraints. Also there is no reward for engaging fungus other than limiting its impact on loot in neighboring tiles or going for the Mycus post-threshold rewards. Fungus issues are compounded by experimental z-levels and sleeping.

**Comment by Ulysses2** [comment]
Should dispersed spores really be able to resist heat that well, though?

**Comment by MrOlaf** [comment]
Spores are too tough as is. You can drive 10-ton truck with a ram into them at 60+ MPH and they survive. Pretty much only fire/heat are effective against them (fungicide grenades and spray are just too rare to use, you never find them out in the world and if you craft them - you need to leave the area where the fungus resides due to the amount of time needed to process sulfur into fungicide). At some lab starts where I'd stay in the lab for a week I had rooms packed full of fungaloids (literally every square) due to how fast they replicate (experimental zlevels)
