### ISSUE TITLE
Zoning QoL Suggestions

### ISSUE THREAD

**Issue by everythingisonfire** [CleverRaven/Cataclysm-DDA#34948]
I posted this on the forum, but I figured I might as well post here as well.

This is my vehicle zone setup: https://i.imgur.com/j4Yhak8.png

It is a chaotic mess. Here are some suggestions that I believe would help alleviate this mess:

* Zone list sorting. [Currently](https://i.imgur.com/oJRbcgS.png), it is based on distance and direction (I think?). It would be helpful to have other options as well, such as standard alphabetical/numerical sorting.

* Zone tabs. This would help identify zones for separate bases and vehicles. At the minimum, differentiate vehicle and land zones.

* Zone deletion confirmation. There is no Y/N confirmation and no message of what zones you remove. Accidently hit r while managing your zones? Good luck noticing it, and to what zone.

* Zone shaping and adding to existing zones. Say a player would like to have the unsorted zone [here](https://i.imgur.com/StYqhAJ.png). This could be one zone, formed that way or with spots added to it. Instead, the player will have to create 21 individual zones, which will convolute the management window.

**Comment by Karthas077** [comment]
> Zone list sorting
Non vehicle zones can be sorted.

> At the minimum, differentiate vehicle and land zones.
This is already done. Vehicle zones have an asterisk next to them. As for ordering, vehicle zones are always displayed before ground zones.

> Zone deletion confirmation.
If you accidentally delete a zone, all you need to do is exit the zone manager without saving and it will restore it.

> Zone shaping and adding to existing zones.
Ground based zones can already be resized. Vehicle zones cannot currently be resized or shaped due to system limitations without extensive overhauling of both zone and vehicle code. (I was the one that wrote the vehicle zone code in the first place, and it was a huge pain to get even this much working).

Additionally - Why do you have an unsorted zone on top of every sorted zone? That is almost entirely counter to their intended purpose. MAYBE on the food/drink zones because sometimes you get bottles/bags left behind...

**Comment by everythingisonfire** [comment]
> Non vehicle zones can be sorted.

Vehicle bases are quite popular, so it would be nice to have the option.

> If you accidentally delete a zone, all you need to do is exit the zone manager without saving and it will restore it.

A hassle if you're manipulating several zones and accidentally delete something, but fair enough.

> Additionally - Why do you have an unsorted zone on top of every sorted zone? That is almost entirely counter to their intended purpose. MAYBE on the food/drink zones because sometimes you get bottles/bags left behind...

I typically just drop stuff in my vehicle wherever and let zones to the work. I was under the impression that in order for items already in containers to be moved to the correct location, they had to have an unsorted zone over them.

**Comment by Karthas077** [comment]
> I was under the impression that in order for items already in containers to be moved to the correct location, they had to have an unsorted zone over them.

That is correct, and for a stationary base you can get away with it by just having a single unsorted zone that covers everything on the ground. However if you're using nothing but vehicle cargo zones, you have to make a choice between being able to drop things anywhere and having twice as many zones, and just designating a single drop off tile and being able to read your zone list.

I don't know how likely it is for multi-tile vehicle zones to be implemented any time soon. If I finish up some of my larger projects I might take another crack at it, but it could be a while. Of course if someone else decides they're willing to brave the convoluted mess that is the zones code it might get done sooner, but it doesn't look like many people are willing to make significant changes to it.
