### ISSUE TITLE
#9807 (and many earlier) install failure, tiles version

### ISSUE THREAD

**Issue by angryparakeet** [CleverRaven/Cataclysm-DDA#35054]
# Describe the bug

Encountered when downloading Windows tiles all versions #9807 to at least #9797. Not present in 0.D stable Win-Curses (related?). Unpacking from .zip seems to be interrupted (?), produces segfault when trying to boot. Makes parakeets very sad.

# Steps To Reproduce
1. Download 0.D-Windows-Tiles-9807.zip
2. Unpack into new folder
3. Take note of 'pung' noise of doom as unpacking is interrupted
4. Try to run cataclysm-tiles 

# Expected behavior
I expect it will produce a segfault?

# Screenshots

# Versions and configuration

Yeah I literally can't get that far, sorry

 - OS: Windows 7
 - Game Version:Cataclysm DDA version 0.D-8739-g3c1831f
 - Graphics version: [Tiles]
 - Mods loaded: n/a, fresh dl

# Additional context

From the /config folder (you can zip them both together):
        - CRASH LOG FILE: config/crash.log
VERSION: 0.D-8739-g3c1831f
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:
    @0x5441C2[cataclysm-tiles.exe+0x1441C2]
    @0x54443A[cataclysm-tiles.exe+0x14443A]
    SMPEG_error+0x3DAF3@0xC91985[cataclysm-tiles.exe+0x891985]
    @0x72DC9D3
    GetProfileStringW+0x12AA3@0x7695003F[kernel32.dll+0x5003F]
    RtlKnownExceptionFilter+0xB7@0x777E74DF[ntdll.dll+0x774DF]
    RtlInitializeExceptionChain+0x36@0x777A9EC5[ntdll.dll+0x39EC5]

        - 
-----------------------------------------
19:18:44.475 : Starting log.
19:18:44.485 INFO : Cataclysm DDA version 0.D-8739-g3c1831f
19:18:44.556 WARNING : opendir [./sound/] failed with "No such file or directory".
19:18:44.577 INFO : Number of render drivers on your system: 4
19:18:44.577 INFO : Render driver: 0/direct3d
19:18:44.577 INFO : Render driver: 1/direct3d11
19:18:44.577 INFO : Render driver: 2/opengl
19:18:44.577 INFO : Render driver: 3/software
19:18:51.377 INFO : SDL version used during compile is 2.0.5
19:18:51.377 INFO : SDL version used during linking and in runtime is 2.0.5

**Comment by angryparakeet** [comment]
I hope this is helpful. Literally  my first time using git for anything... sooo yeah.

**Comment by Orinyau** [comment]
I'm getting the same.

**Comment by new02DAY** [comment]
Do you have the same issue downloading with the launcher? Are you using 7zip or Windows Zip?

**Comment by ZhilkinSerg** [comment]
Most probably game crashes for you because essential files are missing in game folder.

I've just tried unpacking Windows versions [build 9807](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-jenkins-b9807) and it works fine for me. If you say you have tried multiple archives and all aren't working, then it is probably something on your side - incomplete download, incompatible unpacking software, antivirus software blocking some files during unpacking, etc.

First of all make sure that files are downloaded correctly (checksums are below):

![image](https://user-images.githubusercontent.com/16213433/67626362-13d1c780-f853-11e9-9c13-02000fb16aa3.png)

![image](https://user-images.githubusercontent.com/16213433/67626369-28ae5b00-f853-11e9-9661-8297c1ee9a99.png)

If hashes are okay - try using [7 zip](https://www.7-zip.org/) for unpacking.

**Comment by angryparakeet** [comment]
> 
> 
> Do you have the same issue downloading/extracting with the launcher? Are you using 7zip or Windows Zip?

Haven't tried that. I'm using Winrar, actually... I'll give it a shot with 7zip tomorrow, and the launcher. Will keep y'all posted.

**Comment by angryparakeet** [comment]
Hey all,
Problem turned out to be in the compatibility mode. It was set to Windows 7 like normal for stable but not experimental, apparently. On my end for sure, resolved now, thanks a bundle, mwah mwah.
