### ISSUE TITLE
Crashes examining loot with soda

### ISSUE THREAD

**Issue by irwiss** [CleverRaven/Cataclysm-DDA#35171]
# Describe the bug

Started lab run, examined locker with soda can - crashed with division by zero in consumption.cpp as the screenshot shows, reloading the save makes the looting screen show up with no crash.

A while later a second lab run - same thing, random lab locker - crashed.

3792bd75a9889171cfe388073c55d695036e9293 could be relevant as i've started getting these crashes after rebasing on top of current master

# Steps To Reproduce

Not sure this is directly reproducible as it's kinda random when it crashes, but;
1) Start lab run
2) Find locker with soda
3) It may crash
Extra:
4) Reload and examine same locker - it will NOT crash

# Expected behavior
No crash

# Screenshots

Cream soda crash
![image](https://user-images.githubusercontent.com/6560075/67893089-99f55300-fb5e-11e9-9c12-7ae2fd8eb4d6.png)

Orange soda crash
![image](https://user-images.githubusercontent.com/6560075/67899220-818b3580-fb6a-11e9-8a5b-40f4c067678b.png)

# Versions and configuration

 - OS: Win10
 - Game Version: git commit cad96914c1ca5fafe4f0ee89fa4a1d2dd52f3f4f
 - Graphics version: Tiles
 - Mods loaded: "dda", "aftershock", "crt_expansion", "Arcana", "alt_map_key", "MMA", "more_locations", "FujiStruct", "No_Rail_Stations", "deoxymod", "blazemod", "Heavy miners", "adv_gear", "nw_pack", "SD_Magcrafting", "cbm_slots", "no_npc_food", "novitamins", "No_Fungi", "_CustomTweaks"

# Additional context

I'm also attaching a save, but I don't think it'll help much - after reloading there is no crash on that specific locker, the locker is in the autodoc section to the left, the top-left room and has an orange soda can in it.

[Verona.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3791153/Verona.zip)

**Comment by Nerezza** [comment]
I referenced this in a probable duplicate issue. I've crashed about 5 times in the past 2 hours due to canned beverages, the error is always "Arithmetical error"
Crash log follows:
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3793066/crash.log)

**Comment by snipercup** [comment]
I'm getting a crash on Windows build 9842 when opening the consume menu next to a soda can but i'm not getting a crash if I use U to unload it and then consume it.

**Comment by ScarPan** [comment]
I got same crash on both 9845 and 9842 version. Tried avoiding examining stuff by interacting with g not e but no luck.

Arithmetical error crash still happened.

**Comment by Nerezza** [comment]
I think I might have figured out the cause. Because soda cans are seemingly the only cause for this crash (and not soda bottles, for example) I investigated can_drink and found that its volume is 250ml, which is the minimum volume for liquid containers (1 charge).

I suspect that the changes by https://github.com/CleverRaven/Cataclysm-DDA/pull/34980 don't take into account containers that can only contain 1 charge of a liquid, and it probably "fills" the soda can with an improper value as a result. I haven't been able to buckle down and review the math being done in that commit yet though, so hopefully someone who's reviewed it already can double check!

**Comment by irwiss** [comment]
I've added early return and currently run with no crashes for a while, it's probably sweeping the actual problem under the rug but it stops the crashes - not sure i know the code enough to pinpoint the correct solution, you can get 0 charges messages if you just randomly port around and search soda cans in houses or anywhere else

```diff --git a/src/consumption.cpp b/src/consumption.cpp
index 110b4bd4bf5eacde4e794544a6f528cbf53f507d..77dda2b7d87948095575a07ba182dd7ae5320e56 100644
--- a/src/consumption.cpp
+++ b/src/consumption.cpp
@@ -597,6 +597,12 @@ ret_val<edible_rating> player::will_eat( const item &food, bool interactive ) co
         add_consequence( _( "Your stomach won't be happy (not rotten enough)." ), ALLERGY_WEAK );
     }
 
+    if( food.charges == 0 ) {
+        add_msg_if_player( m_bad, "Bug: Food had 0 charges" );
+
+        return ret.make_failure();
+    }
+
     if( stomach.stomach_remaining() < food.volume() / food.charges && !food.has_infinite_charges() ) {
         if( edible ) {
             add_consequence( _( "You're full already and will be forcing yourself to eat." ), TOO_FULL );
```

**Comment by Nerezza** [comment]
I'm re-doing my volume test, I botched the first go and didn't actually change the volume for cans (oops!)
I also noticed that the code changes in https://github.com/CleverRaven/Cataclysm-DDA/pull/34980 makes it so that liquids not set to spawn with random charges will circumvent an already existing method of ensuring it'll never spawn with 0 charges. I think this problem existed before that PR, it just was never an issue until this PR stopped making sure drinks always spawned with 1 charge at the very least.

**Comment by ExeCUTEtioner** [comment]
Having the same problem, I've narrowed it down to the base game and even double checked to make sure its not affected by any of the other mods listed by OP. I think we are already past that point, but i just wanted to provide a bit more confirmation. However I would like to note that its not limited to just soda cans, I'm getting the same issue from food cans as well.
Can crash has been replicated by:
-Examining same tile as can
-Opening consume menu in range of can
-using (g) on same tile as can
-using (/) and selecting the tile with the can in either menu

I'm gonna assume that any kind of viewing of the can and its stats results in the same crash unless using (x).
Dragging does not result in a crash
reloading the save where the can has already been loaded into the cell *kinda* fixes it, at least until you discover another can in a different cell.

Maybe its the container type as well, and not its volume or contents? Not having these problems with 2L bottles and gallon jugs yet, though i'll get cracking on finding those to test.
Sorry if this is all useless data, lemme know if you need crashlogs. Pretty sure they are identical to the ones OP has.

**Comment by TheGoatGod** [comment]
i got the same error trying to read something. im trying to recreate

**Comment by Solusphere** [comment]
Probably related: https://media.discordapp.net/attachments/252368751016542218/639724335640215552/unknown.png

Happened at the moment I hit the w key to wield my weapon. I was carrying a frozen soda can in my inventory. My hands were empty at the time.

**Comment by Nerezza** [comment]
@irwiss I'm on bad internet 99% of the time and it would take me too long to set up to compile this game from source. Could you go to https://github.com/CleverRaven/Cataclysm-DDA/pull/34980 and try the suggestion I gave at the bottom?

It's not a fix for the problem, but I believe the problem is much deeper than that PR touched. At the very least, fluid containers should have a safeguard against spawning with 0 charges anyway.

**Comment by Trashkin** [comment]
I got the crash from a Tin Can of Curry so it can happen with food as well as drinks. However upon reloading the save I was about to loot the can.
