### ISSUE TITLE
Electric Chainsaws drain batteries after just one cut

### ISSUE THREAD

**Issue by Odieman1** [CleverRaven/Cataclysm-DDA#35203]
# Describe the bug
Electric Chainsaws can't realistically cut a single tree.  Using disposable batteries (the 1200 ones), you may be able to cut down two with 0 charge left.

# Steps To Reproduce

1. Acquire Electric Chainsaw and applicable batteries
2. Observe battery level before and after the tree has been cut

# Expected behavior

Looking online, Electric chainsaws can last as long as an hour on rechargeable batteries.  They can cut through a log pretty quick, in less than a minute.  Unless this is some sort of shrubbery chainsaw, then a standard electric chainsaw should act as a slightly more time consuming standard gas chainsaw with a decent amount of trees to be felled before requiring a recharge.

Keep in mind reading recent articles about electric vs gas chainsaws, as I was a bit disheartened to read an article from 2008 saying a single tree per single battery, but then found an article from 2019 that said electric chainsaws are on the same league as gas chainsaws now.  CDDA seems to take place in some alternate universe where electric and solar seems to be a bit more advanced compared to reality anyway.

# Screenshots

I shouldn't need to screenshot this, but if it's needed I can show it...

# Versions and configuration

Build #9842 0.D
Electric Chainsaws are in the base game, and no mods change them to my knowledge.

**Comment by kevingranade** [comment]
Some very brief research says that electric chainsaw battery packs can range from 400 to 800 Wh, have a runtime from 200 to 400 seconds, and weigh 3-5 lbs.
A VERY quick adjustment is to switch to the heavy battery pack for these instead of the medium, but that leaves us far short, so we could also considering either doubling the size (weight,volume,capacity) of the heavy battery pack or adding a new one with these stats.

Source: http://tcimag.tcia.org/publication/?i=539289&article_id=3228578

**Comment by Zourin2** [comment]
This was supposedly fixed in #33154 but appears to have broken again

**Comment by DaviBones** [comment]
> This was supposedly fixed in #33154 but appears to have broken.

No, that PR adjusted gas chainsaws, it didn't touch electric. Please keep the discussion here focused on electric chainsaws

> Gas and electric chainsaws and circular saws are consuming 100% charges for single actions, confirmed as per Build 9979

Yes, this is a very widespread bug caused by #35896 due to either inattention to `copy-from` or misunderstanding of the effects of `charges_per_use` , or both. It is causing chainsaws, rm13 armor, circular saws, and lots of other things to go through fuel 5x as fast as intended. I will have a fix PR'd in the next day or two. Please reserve further research and judgment until then.

**Comment by Night-Pryanik** [comment]
#35896 doesn't increase consumption rate of electric chainsaws to the point that they are able to cut down only one tree. To test it, just fully remove `charges_per_use` field from `elec_chainsaw_off` and see the consumption rate of the chainsaw. These chainsaws fully drained their battery after one cut even pre-#35896.

Code explicitly states that game reads **either** `charges_per_use` **or** `power_draw` fields.
https://github.com/CleverRaven/Cataclysm-DDA/blob/72dbda868da802919366b475105d40aa5191224e/src/item.cpp#L8854-L8863
So adding `charges_per_use` does not increased consumption rate five times, it overrided previous 2000000 mJ `power_draw`. It increased consumption rate twofold, but even without that consumption rate was too high and allowed cutting of only one tree.

**Comment by DaviBones** [comment]
Hmm, I actually don't think `charges_per_use` does override `power_draw` in this case. As long as `turns_per_charge` is at its default value of zero. In the above snippet, `charges_per_use` doesn't enter into things until `ammo_required()` is called.

Still, I added `"charges_per_use": 0` to this and other "on" tools with `power_draw`, because I don't think the inheritance of `charges_per_use` by the "on" variants was intentional, as it wasn't indicated or justified in #35896.

**Comment by Zourin2** [comment]
Circular Saw is attempting to draw 1430 charges for a single Log > 10 plank action, and it takes 20 minutes. By default it appears with a Medium battery (500 charge), but is attempting to consume more power than is in a High Capacity Heavy Battery (1250 charges).

Here's the fun thing. It ALSO takes 20 minutes to do the same job with a wood saw. While the item should probably be set to be Wood Sawing 4 rather than 2, changing this does not alter the power demand.

**Comment by DaviBones** [comment]
The power draw is not the problem, to be clear. 60V * 20A = 1200W =1,200,000mW which matches this entry perfectly:
https://github.com/CleverRaven/Cataclysm-DDA/blob/9b667e7b828512f7a8b429f6c3e3c5d4f155a0df/data/json/items/tools.json#L1295
The sawing speed and battery capacity could certainly use a reality check though. I believe battery charges are in kJ, though I could be wrong.

**Comment by kevingranade** [comment]
My relatively brief research indicated that either doubling the stats (volume, weight, charge) ofvtge heavy battery pack, or adding a new 'largest portable battery pack' as "industrial battery" with those stats would be reasonable.

Possibly even larger, I don't remember the precise details.

**Comment by Zourin2** [comment]
The weight of a 60v battery pack used for most of these tools are about 3lbs and are actually pretty small (fist-sized). Admittedly, I'm not sure of the output amps, just the amp-hours (9ah) which are very different. Just thought I'd mention it, since I happened to see some 2-packs at Home Depot.
