### ISSUE TITLE
Prove you're a survivor mission completed immediately

### ISSUE THREAD

**Issue by rfmnunes** [CleverRaven/Cataclysm-DDA#35257]
The mission "Prove you're a survivor" is completed immediately, if the NPC gives mission ten days after the cataclysm

1. Start a game ten days after the cataclysm.
2. Get the mission from NPC.
3. Talk to NPC to complete mission immediatly

The survive ten days should not use a hardcoded date, but ten days after the current moment

Probably useless, but I'm on Windows 10, 0.D-9059-gae829af (tiles)

**Comment by sdp0et** [comment]
I'd say it could be 10 days after that character's start date rather than when the mission is assigned.  For some missions it makes sense to be "from now" and for others it makes sense to be "in total". I got "kill 100 zombies" from an NPC when my kill count was already in the hundreds as a second mission from a follower that had been with me for quite a few of those kills and it seemed like the count started from assignment even though a real person would already have known I'd met that objective..

**Comment by Night-Pryanik** [comment]
> a real person would already have known I'd met that objective..

How's that? He didn't track your accomplishments, you know.

**Comment by sdp0et** [comment]
no, but he was standing next to me for a lot of it.

**Comment by Night-Pryanik** [comment]
Resolved by #58128.
