### ISSUE TITLE
@ changes characters and colors when using new mouse look

### ISSUE THREAD

**Issue by ymber** [CleverRaven/Cataclysm-DDA#35324]
# Describe the bug
When using the new mouse look to look around my @ changes to different characters and different foreground and background colors.

# Steps To Reproduce
1. Start a new game with tilesets turned off.
2. Look around using mouse look.
3. Observe @ changing colors and characters.

# Expected behavior
White @ remains a white @.

# Screenshots
![2019-11-03_1008_48](https://user-images.githubusercontent.com/34044886/68188432-062de780-ffa1-11e9-90ca-b2b60813948a.png)
The black # on a brown background above the cursor in this screenshot should be a white @.

# Versions and configuration
 - OS: Arch Linux x86_64
 - Game Version: Current master at 1e35a58b13751fc48b3dfb470eb1aeb10e071e02
 - Graphics version: Tiles
 - Mods loaded: [dda, no_npc_food]

**Comment by RoyBerube** [comment]
I've been looking into this and the bug happens on windows non-tile mode as well. Noticed that the character letter is not changed while the mouse is moving, but only after a short delay when the mouse stops moving.

Turning off animations in graphics options stops the bug from displaying. 

I suspect it has to do with get_player_input() in handle_action.cpp. There are a few places where a delay is used in the game logic, and this is the code that detects mouse movement.

**Comment by RoyBerube** [comment]
I've found that commenting out line 304 in current version of handle_action.cpp eliminates the bug. 

![image](https://user-images.githubusercontent.com/30374490/68519818-a1001d80-0250-11ea-897f-6d4a8172c3a1.png)

However, I'm hesitant to make a pull request on this just yet because this fix may affect something else.

**Comment by RoyBerube** [comment]
I've found out what is the cause. It seems to be intentional but am not sure why it would be desirable; in fact 0.D stable mouse view behaves the same way in ASCII mode. 

![image](https://user-images.githubusercontent.com/30374490/68538487-5f47a380-0332-11ea-98c5-c0be54272e20.png)

Game.cpp is the source file. Change of one boolean parameter disables the behavior.

I'll submit a pull request.
