### ISSUE TITLE
Turrets have insanely long effective range

### ISSUE THREAD

**Issue by RickyVanz** [CleverRaven/Cataclysm-DDA#35377]
# Describe the bug

i don't know if the turret is intended to have insanely long range of effective firing but i just encountered a military roadblock with turrets on it and i try to deal with it using my weapon and all of a sudden the turrets start firing accurately on my character, leaving me with critical wound to the torso.
while my weapons is still early-game weapon which has smaller range than the turrets did.

# Steps To Reproduce

find any turrets in-game (Missile Silo or Military Roadblock event) and deal with it.

# Expected behavior

in my previous experience dealing with turrets, i can deal with it after around 20 tiles near the turrets and shoot it with M4A1. 

# Screenshots

![wot](https://user-images.githubusercontent.com/45474242/68383424-384d6e00-0188-11ea-9d14-a3de207252e7.png)

# Versions and configuration

 - OS: Windows 7 64-bit
 - Game Version: 0-D.9196-g16728ff
 - Graphics version: Tiles
 - Mods loaded: [Dark Days Ahead [dda],
Disable NPC Needs [no_npc_food],
Aftershock [aftershock],
C.R.I.T Expansion Mod [crt_expansion],
Bens GF recipes [Tolerate_This],
Craftable Gun Pack [craftgp],
DeadLeaves' Fictional Guns [FIC_Weapons],
Garden Pots [growable-pots],
Icecoon's Arsenal [ew_pack],
Makeshift Items Mod [makeshift],
Medieval and Historic Classes and Shields [Medieval_Stuff],
More Survival Tools [More_Survival_Tools],
Mythological Replicas [nw_pack],
DinoMod [DinoMod],
PKs Rebalancing [PK_REBALANCE],
Secronom [secronom],
Alternative Map Key [alt_map_key],
Cataclysm++ [Cata++],
Crazy Cataclysm [crazy_cataclysm],
EZ-Mode Medical [fast_healing],
Hydroponics [hydroponics],
Mutant NPCs [mutant_npcs],
Beta National Guard Camp [national_guard_camp],
More Locations [more_locations],
Fuji's More Buildings [FujiStruct],
Mapgen Demo [mapgen_demo],
Urban Development [Urban_Development],
Folding Parts pack [deoxymod],
Vehicle Additions Pack [blazemod],
Roadheader and other mining vehicles [Heavy miners],
Tanks and Other Vehicles [Tanks],
Artyoms' Gun Emporium - Reloaded [Arts' Guns],
Manual Bionic Installation [manualbionicinstall],
No Filthy Clothing [no_filthy_clothing],
Prevent Zombie Revivication [no_reviving_zombies],
Safe Autodoc [safeautodoc],
Simplified Nutrition [novitamins],
Sleep Deprivation [sleepdeprivation],
SpeedyDex [speedydex],
Stats Through Kills [stats_through_kills],
Stats Through Skills [StatsThroughSkills]
]

# Additional context

if its an intended purpose of making the turrets deadlier, i would like to see turrets that evolving with time like zombies did.

**Comment by Destragon** [comment]
Turret ranges go up to 50 tiles right now, depending on their weapon. They've been getting their ranges increased not so long ago.

Turrets should be giving off more warnings. A warning sound would be hard to hear at that range, so maybe they should fire warning shots (not like they are short on ammo). Someone suggested in a PR that a non-damaging pain ray, probably microwave, turret should be added to act as deterrence and warning for the player. Maybe they should be illuminated in the dark again, because it doesn't really make sense for them to be hidden if they are just designed to be killing non-intelligent monsters.

**Comment by RickyVanz** [comment]
that's insane.. even weapons i found randomly on zombies and houses weren't able to kill turrets that has 50-tiles range. hell even 40-tiles is already enough to make turrets so deadly.

i agree, there should be warning shot or message on the log saying "there's a turret ahead, you may want to stay away from it" or something like that and tweak some early weapon to have enough range to deal with the turrets.

**Comment by Night-Pryanik** [comment]
> Maybe they should be illuminated in the dark again, because it doesn't really make sense for them to be hidden if they are just designed to be killing non-intelligent monsters.

That's not true. They were designed to kill living (intelligent) people who will try their best to locate and destroy turrets before turrets destroy them. That's why they ain't illuminated. It's not turrets' fault that most of Earth population are zombies.

**Comment by Night-Pryanik** [comment]
> i can deal with it after around 20 tiles near the turrets and shoot it with M4A1.

You can shoot your M4A1 from up to 36 tiles, while turret equipped with the same M4A1 can only fire from 20 tiles. Oh, that's absolutely fair, isn't it?

> tweak some early weapon to have enough range to deal with the turrets.

How do you see it happening? "Damn, our MP5 has only 14 tiles range, and we can't deal with .50 BMG turret with 60 tiles range! Let's buff our MP5 so it would shoot 60 tiles range too!" ?

**Comment by Night-Pryanik** [comment]
I'd label this issue as invalid, as turrets range are absolutely valid. Suggestion to add a warning or change turrets' armament to some pain-inducing mumbo-jumbo is a completely different issue.

**Comment by RickyVanz** [comment]
never heard of turrets responsible for turning people into zombies (unless they are loaded with canister of zombie gas) but that could be something that can exist in-game to add more variety to turrets.

now that part i missed, M4A1 can shoot up to 36 tiles, didn't realize that.. and yeah that's fair
forget about tweaking then, i hope there is some sort of warning message telling player that there is turret up ahead.

**Comment by Zireael07** [comment]
@Night-Pryanik: I think a suggestion to add a warning was made already in some different PR/issue, do you want an explicit issue for that?

**Comment by Night-Pryanik** [comment]
@Zireael07 yes, definitely. Discussing it in non-related or only slightly related issues is incorrect IMO.

**Comment by Nerezza** [comment]
I think the range is reasonable, but thinking about this further making the 5.56mm turrets rarer would probably be better for balance anyway...

Right now I can down a single 5.56 turret and get a couple belts of 5.56 NATO, I don't even have to consider using any guns other than AR-15 patterns and HK416s because I'm swimming in that military grade ammo.

The most common turret should probably be switched to 9mm imho. A shorter range, less insta-murder chance if you're wearing kevlar (it's still going to hurt a LOT and possibly kill you outright, though) and swimming in 9mm ammo isn't as game-breaking as swimming in military-grade 5.56 NATO. You'd also retain a reason for gathering your .223 casings to reload.

**Comment by anothersimulacrum** [comment]
There is no existing military hardware similar to turrets that use 9mm.
Because our turrets are based off of existing military hardware, they do not use 9mm.
The rest of your points were all addressed in the PR that introduced these turrets, I'd suggest you find that.

Unrelated, but this issue isn't accomplishing anything, if people have things that should be addressed, they should go in other issues and this issue should be closed.

**Comment by Nerezza** [comment]
There's also no existing military hardware similar to power armor, optical cloaks, and caseless ammunition guns (we tried that one, but the guns would need bulky cooling systems for the chambers to prevent heat from accumulating.) We're not exactly limiting ourselves to existing military hardware here.

**Comment by anothersimulacrum** [comment]
Our automated  defenses are based off of existing military hardware, and they should continue to be so.

**Comment by kevingranade** [comment]
User error, don't try to take on enemies with insufficient gear and planning.
