### ISSUE TITLE
Flaming Eye is not fun

### ISSUE THREAD

**Issue by MrOlaf** [CleverRaven/Cataclysm-DDA#35449]
**Is your feature request related to a problem? Please describe.**  
The Flaming Eye enemy uses the powerful STARE ability too often and is too powerful overall (huge speed, huge hp pool,spawns nether creatures and infects player and other enemy types with fungus). There's no protection from the STARE (aside from extremely rare artifacts or some bionics) and since nether creatures are their own faction, they should not indirectly spread fungus.

**Describe the solution you'd like** 
STARE should have teleglow removed, instead it would force a significant Morale Debuff alternating with blind (with a severely reduced duration). STARE is castable once every 60 seconds. Flaming Eye retains the huge health pool and night vision, but speed is severely reduced. Flaming Eye has a debuffer and detector role and becomes a semi-stationary deterrent for the player.

**Describe alternatives you've considered**  
STARE removed completely. Flaming Eyes act like Screeching Zombies for nether faction, alarming nearby Nether by pinpointing the player after which is starts to flee.

**Comment by jarmush** [comment]
Flaming Eye is fun!
Losing is FUN!

**Comment by MrOlaf** [comment]
Flaming Eye is OP in current form, provides no reward for defeating it and limits player choice in regards to build variety. Also, it indirectly contributes to outbreaks of fungus by using STARE on other creatures (AFAIK Nether and Fungus are not allies).

Side note - based on wiki teleglow is supposed to cause blind for 10-20 turns, while from my experience it's more like 15-30 in-game minutes - maybe a bug? teleglow attacks stacking?

**Comment by Night-Pryanik** [comment]
> provides no reward for defeating it

It shouldn't.

**Comment by Aphegis** [comment]
It should not provide rewards but the other points are valid. Why is the flaming eye so fast and tanky? It's a floating giant eye... Why does it spread fungus? 
I agree it should be kind of a long range debuffer, but the blind is lasting too long, and the flaming eye should have less hp and move speed aswell.
Maybe to compensate it should have a "advanced version" with the current hp and move speed (or even stronger), but rarer.

**Comment by Nerezza** [comment]
I treat the flaming eye like I treat fungal monsters (I disable those outright) by going into monsters.json and deleting its stare ability. That means it literally can't do anything anymore, but until it gets reworked that's what I'm doing.

So far the only aboveground lab I've tried assaulting had a flaming eye perfectly placed behind a bunch of reinforced glass so that it could stare at me at just about anywhere outside the building (but within the perimeter wall) if it had stare enabled, and it would've taken me a VERY long time to get access to the damned thing to kill it. If I hadn't disabled its stare I would've just had to avoid that lab entirely, similar to how fungal monsters are just avoided entirely right now.

**Comment by kevingranade** [comment]
Yes there are monsters that are so strong and with so little reward to defeating them that it would be completely reasonable for you to simply not engage them ever. That's completely intended and that's a decision you make as opposed to simply gunning down every monster you ever encounter.
