### ISSUE TITLE
mi-go slaver beam ignores pain modification traits

### ISSUE THREAD

**Issue by MrOlaf** [CleverRaven/Cataclysm-DDA#35464]
# Describe the bug

Mi-go slavers and scouts need tweaks: 
1A. Beam attack bypasses player protections, even with "Deadened" mutation the player is quickly brought to SEVERE PAIN. Pain debuff is outside of the regular pain scale and stacks for several hours with drugs/CBMs/armor/mutations barely affecting it.
1B. Mi-go slavers and mi-go scouts seem to have 50 tile night vision instead of 50 tile vision radius in the day

2. Mi-go encampment is too hot for player on NPCs to survive with current heat system (heat seems to stack and bypass all protections)

# Steps To Reproduce

Regarding 1A
1. Create character with DEADEND post-threshold mutation 
2. Spawn 2 mi-go slavers to apply their beam attack
3. Player is quickly brought to SEVERE PAIN with overlapping stacking debuff

Regarding 1B
1. Spawn mi-go slaver/scout 50 tiles from player at night
2. See results

# Expected behavior
Regarding 1A
Player with Deadened post-threshold mutation should be immune to the beam attack or the attack needs to be severely nerfed overall - just to provide short bursts of unmanageable pain, which could enable "capture" of player.
Regarding 1B
mi-go slaver and scout should have the same base stats, vision range as regular mi-go but mi-go slaver has non-damaging beam attack which debuffs the player and scout has a ranged damaging attack.
Regarding 2
Heat mechanic needs a fix so it doesn't stack/bypass protection.

# Versions and configuration
 - OS: Windows 10
 - Game Version: 0.D-9282-g4c43c0d (tiles) build 9882
 - Graphics version: Tiles
 - Mods loaded: dda, disable npc needs

**Comment by Night-Pryanik** [comment]
> Beam attack bypasses player protections, even with "Deadened" mutation
>Player with Deadened post-threshold mutation should be immune to the beam attack

Yes, this is definitely a bug and should be addressed. Also Sensory Dulling CBM.

> Mi-go slavers and mi-go scouts seem to have 50 tile night vision instead of 50 tile vision radius in the day

That's not true. They both have 50 day vision range and 20-25 night vision range.

>  Spawn mi-go slaver/scout 50 tiles from player at night
>  See results

Spawned mi-go scout at night at 50 tiles. It doesn't see me at 39+ tiles. (I debug-spawned clairvoyance artifact). Note the absence of "Aware of your presence!" warning.

![изображение](https://user-images.githubusercontent.com/11132525/68588183-4a8a1d80-04a2-11ea-96b1-2d0782eb38bb.png)

> mi-go slaver and scout should have the same base stats, vision range as regular mi-go

All mi-gos already have the same day vision range (50), and most of them have the same night vision range (20), with the only exception of myrmidon and scout which have slightly better NVR (25).

> Mi-go encampment is too hot for player on NPCs to survive with current heat system (heat seems to stack and bypass all protections)

While that MIGHT be a bug, I see nothing wrong in existence of locations that no player won't be able to survive in, no matter how hard he tries to. NPC cells could have a some sort of cooling mechanisms so they don't die from extreme heat, but otherwise harsh conditions in every other corner of this location seems to be intended.

**Comment by John-Candlebury** [comment]
Theres certainly some temperature bug at work. Im pretty sure @I-am-Erk  has mentioned that the Mi-go biome should work at something close to 56C but the place is often boiling hot instead.

![image](https://user-images.githubusercontent.com/5290912/68612977-59150c80-0483-11ea-98b9-9ce3cb81edad.png)

In fact if you wait in there the tempreatures can increase into the high 250s celsius.

**Comment by Rivet-the-Zombie** [comment]
>Beam attack bypasses player protections, even with "Deadened" mutation the player is quickly brought to SEVERE PAIN.

This shouldn't be happening at all; characters with that trait are supposed to be completely incapable of feeling pain.

**Comment by kevingranade** [comment]
This is working as intended except the pain effect and the temperature effect. The latter is documented elsewhere, leaving just the pain effects.

**Comment by MrOlaf** [comment]
Thanks for taking care of the bugs.

**Comment by KorGgenT** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/magic_spell_effect.cpp#L583

here's the line of code for the pain thing.
