### ISSUE TITLE
Ability to set default Liquid dispensed by faucet in vehicle (Default to clean water, if choice not available)

### ISSUE THREAD

**Issue by jasonmbrown** [CleverRaven/Cataclysm-DDA#35492]
**Is your feature request related to a problem? Please describe.**  
I like to store Large amounts of drink in my vehicle tanks, rather then haul around extra 60L tanks. I find it annoying having to siphon to drink non water. (especially when the vehicle hotkeys don't work correctly if you have more then 5 or so empty tanks the letters are already in use).

**Describe the solution you'd like**  
When interacting with a vehicle tile that contains a faucet I would like to have the ability to chose what type of Liquid is being dispensed (Must already be in the vehicle) When that runs out, it should default back to Clean Water.

**Describe alternatives you've considered**  
Maybe dispense whatever is in the tank that the faucet is attached to (However this would be inconvenient)

**Comment by Funguss** [comment]
I've thought this too... But it seems strange to have it all come out of a single faucet, I just can't picture ripping one from a sink and then getting it (cleanly) set up for multiple tanks. It would be something more like what they have in bars for soft drinks.

Rather than change the faucet why not have a separate part which acts as a kind of hub? I'd like to have an unlimited amount of taps available but at the same time I can't picture it. Ideally I'd like to see a faucet linked to a particular tank (or tanks) on another tile, and for multiple taps to exist in one tile in some form or another. As it stands the faucet just magically connects to your water tanks, whichever they may be, and this isn't exactly great.
