### ISSUE TITLE
Autodoc cosmetic surgery for mutants

### ISSUE THREAD

**Issue by MrOlaf** [CleverRaven/Cataclysm-DDA#35539]
**Is your feature request related to a problem? Please describe.**  
Mutations are random, some of those mutations could be corrected by the miracle of Autodoc cosmetic surgery (with invasive surgery risk involved). People are vane by nature and likely to undertake risky surgery to get rid of some mutations (especially when using a tileset) resulting in lots of fun.

**Describe the solution you'd like**  
Autodoc surgery option that enables you to:
1. Reconstruct face - on success: remove mouth mutations (like face tentacles and snouts), plop bulging eyes back into sockets, remove ear mutations - head, eye, mouth damage %25hp per part adjusted, reduced vision or hearing or dazed until fully healed; on fail - 50%hp damage par part,gain deformed instantly. Remove wings  (including wing stubs) - on success: Torso damage 50%hp, reduced speed by 25% until healed; on fail - additionally both arms broken (autodoc oopsie)
3. Remove tail - on success: leg damage 50%hp, reduced flat ground walking speed by 50% till healed; on fail - additionally both legs broken
4. File nails - on success: remove fingernails/claws mutations, including raptor feet but not hooves  - 75%hp damage to legs or arms, fail - legs or arms broken depending mutation removed
5. Reconstruct skin - all body parts 90%hp damage - remove fur/chitin/spikes, on fail - also bleeding to all body parts, paralyzing pain

Success chances should be a 50/50 coin-toss at 3computers+3medical and decrease to 75/25 at 8computers+8medical for balance.

**Describe the solution you'd like**
Room for exploits is removed by not allowing to remove leg/arm tentacles, hooves, horns as they are most valuable in regards to trait points.

**Comment by Amoebka** [comment]
From what I understand, mutations were never commercialized, unlike CBMs. They are a very very recent technology developed weeks before the Cataclysm and likely only considered applicable as super-soldier serums.
As for the point exploits, starting mutations can already be removed so it's not a big deal.

**Comment by Funguss** [comment]
I'm still hazy on what an autodoc actually is, and it seems there are a few different ideas as to what exactly it's supposed to be. My understanding is that it's used as a sort of surgical aid that can (riskily) perform operations by itself. I don't see why it couldn't do such things as, say, chop off tentacles if they're there, if it's being operated by a doctor. However, I don't think this should be a 'cure'; apparently mutations happen to your DNA, which is a bit ludicrous but whatever. Surgery can't fix that. If we're going to take this route then rather than curing a mutation the autodoc should treat the symptoms, especially the visibility of said mutation. Some things should be impossible, too. Really, each mutation would have to be looked at and given treatment routes. Things like 'lightly furred' should be treatable with the occasional shave, for example, or laser hair removal. Certain fangs could be given cosmetic surgery. 'Amorphous' is probably impossible to treat in any form.

**Comment by anothersimulacrum** [comment]
> apparently mutations happen to your DNA

Mutations do not happen to your DNA.

**Comment by Funguss** [comment]
Well, genetic downward spiral, and the other genetic traits, make it sound like they do. Purifier is apparently a stem cell treatment that purges genetic defects. I'm really not sure how else to interpret those if DNA isn't involved. What's your understanding?

**Comment by anothersimulacrum** [comment]
This is from the person who wrote most of the lore:
(They're explained before that mutations are phenotypic, not genetic)
> Genes encoded by dna are the blueprint your cells use to make the architecture of the cell
> Phenotype is the shape of the structure they encode, the actual final result
> Blob mutation is basically as though there's an architect there on site dictating alternate plans, skipping the blueprint entirely(edited)

**Comment by kevingranade** [comment]
No thanks, we don't handle any outcomes of surgery in enough detail to make this reasonable to represent, and you have a perfectly reasonable in-game mechanism for removing said mutations already.

**Comment by Funguss** [comment]
That's an interesting and surprisingly appropriate use of the word phenotype. I had to go refresh my memory! I see... Kind of... Though that does sound like genetics don't play a role in any way, so how do mutations about genetics make any sense? Could you share a link to where I can read up on this maybe? I didn't mean to subvert this issue.

**Comment by anothersimulacrum** [comment]
[Very recently added to the technology section of the design doc](https://cataclysmdda.org/technology.html).
Not a whole lot of info past that.

**Comment by Funguss** [comment]
Nice one, thanks!
