### ISSUE TITLE
Carnivore trait needs more points

### ISSUE THREAD

**Issue by MrOlaf** [CleverRaven/Cataclysm-DDA#35600]
**Is your feature request related to a problem? Please describe.**  
With introduction of mutated meat - Carnivore (-4) mutation/trait has more downsides due to toxins build up, which is a lot less of an issue for a late game character, but makes early game quite harder (since only the Experiment and Lab Start give option to start with Carnivore)

**Describe the solution you'd like**  
Carnivore mutation should have a cost of -6 points due to adverse effects on the hidden health stat and additional effects.

**Comment by DaviBones** [comment]
I would argue that it the 4 points it gave before was way overpriced. It should have been worth 2 points max, as huge quantities of meat were trivial to obtain.

Really, it's still not very difficult, all you need to do is find a cow or pack of dogs once you're out of the lab. Assuming you do find a source of mutant meat while you're still in the lab, 800 calories a day of mutant meat is safe, and that can sustain you for a very long time, weeks, I suspect.

6 points for what only amounts to a *potential* early game stat penalty due to hunger (that can be avoided completely with proper planning) is crazy talk imho.

**Comment by kevingranade** [comment]
Agreed, in real terms carnivore isn't a significant persistent challenge to the player.
