### ISSUE TITLE
Hell's Raiders encampment quest error + freeze/crash

### ISSUE THREAD

**Issue by SpellingSword** [CleverRaven/Cataclysm-DDA#35657]
Trying to start a mission for the old guard that would(I assume) have me clear a bandit camp. Get this error instead. Then the games freezes.

# Steps To Reproduce
Try to get the mission, get error. Reloading doesn't help. Restarting doesn't help. 

# Expected behavior
Get mission, no error.

# Errors
 DEBUG    : Unable to find and assign mission target bandit_camp_1.

 FUNCTION : cata::optional<tripoint> find_or_create_om_terrain(const tripoint&, const mission_target_params&)
 FILE     : src/mission_util.cpp
 LINE     : 227

After this error, another one pops up several times with different coordinates.

 DEBUG    : Tried to access invalid map position at grid (0,0,-2147483648)

 FUNCTION : size_t map::get_nonant(const tripoint&) const
 FILE     : src/map.cpp
 LINE     : 8216

...And then some more 

 DEBUG    : Submap already exists at (0, 1, -2147483648)

 FUNCTION : void map::generate(const tripoint&, const time_point&)
 FILE     : src/mapgen.cpp
 LINE     : 122

**After several repetitions of these errors, the game hangs.** 

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-9511-g32e0c35 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    No Fungal Monsters [No_Fungi]
]

# Additional context

Config and debug:
[config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3880701/config.zip)

Save zip:
[Enigma.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3880707/Enigma.zip)

Is there any hope for me to continue the quest line? I was rather enjoying this world...

**Comment by ralreegorganon** [comment]
You've fallen victim to [this bug](https://github.com/CleverRaven/Cataclysm-DDA/issues/33403#issuecomment-523212731). Basically, there IS a camp but it's outside the range, and so then it tries to place a new one for you to find, but that also ends up being placed outside of the search range due to the linked bug, and then it fails.

If you want to keep playing in the world and continue the quest line, you can use the debug menu to place the `bandit_camp` overmap special within 50 tiles of you (the nearby forest would be a good spot) and then try and start the mission.

**Comment by SpellingSword** [comment]
It worked! Thank you so much!
