### ISSUE TITLE
(WIP issue) Update effects of existing drugs and pharmaceuticals

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#35748]
Our drug system was based around a number of essentially made-up effects. Removing those has lessened the effectiveness of the existing drugs, but cleared up some design space to improve them.

This project-level issue will look at the drugs (prescription and otherwise) in-game and suggest uses and side effects for them. It will also suggest some new effects that can be further leveraged into new drugs, to be suggested in an upcoming issue.

### Side effects
A given drug should have a list of possible side effects. Ultimately the best way to handle this would be to give each side effect a likelihood, and the first time a character takes the drug, roll for the chance of getting each side effect in the list. That profile of side effects would then be memorized for that drug, and would occur every time the player had the drug. Some side effects could have tolerances (eg with antidepressants, indigestion should improve over time).

### List of effects
Note that some effects - such as the different stimulant sub-effects - should all be present on a given medication of that class, but we separate the effect types so that a given drug can have more of one effect and less of another.
* **Mental stimulant**: Increases focus, increase perception, decrease fear (if fear effects are implemented)
* **Physical stimulant**: Increase stamina recovery, mildly decrease pain, increase attack speed, decrease weapon accuracy, increase melee damage, increase calorie burning
* **Antidepressant**: works as a vitamin. As vitamin levels are increased, the severity of negative morale effects is reduced.
* **Depressant**: Slows speed, lowers intelligence and perception, lowers focus. Note: Depressant is used for the mental side of things, Sedative for the physical.
* **Sedative**: Increases fatigue, makes it easier to fall asleep, decreases speed and dex. Note: Depressant is used for the mental side of things, Sedative for the physical.
* **Analgesic**: reduces pain from physical injuries
* **Neuropathic analgesic**" Reduces pain from nerve damage and nonphysical injuries
* **Dissociative**: reduces the penalties from pain and hunger, reduces the magnitude of all morale effects
* **Antipsychotic**: decreases likelihood of hallucinations, affects some specific disorders which should be coded on a case-by-case basis.
* **Hallucinogenic**: increases likelihood of hallucinations
* **Anticonvulsant**/**Epileptic**: decreases/increases likelihood of seizures
* **Addictive**: Addiction needs a whole rework, but this means the drug can develop an addiction and then a withdrawal effect.
* **Tolerance**: This drug builds a tolerance if you use it for a long term, requiring higher and higher doses the longer you use it regularly.
* **Rebound**: Stopping this drug after long term uses, causes a rebound effect (generally the opposite of the drugs usual effects but not always). This is a type of withdrawal but this represents the physical effects rather than the mental ones of addiction withdrawal.
* **Diverting**: (I'm open to a better name, by 'diverting' I mean it diverts you from your concerns about the terrible situation you're in) Reduces the severity of negative morale effects.
* **Abusable**: This drug gives a positive morale effect.
* **Nauseating**/**Antiemetic**: More or less likely to vomit / feel nausea
* **Anticoagulant**/**Coagulant**: Increases or decreases duration of bleeding effects. At high levels may cause spontaneous bleeds (anticoagulant) or blood clots (coagulant).
* **Dry mouth**: reduces enjoyment of food and has a persistent small negative morale effect. Briefly reduced by drinking water.
* **Weight gain/loss**: Reduces or increases the daily caloric requirement to make weight loss or gain easier.
* **Headache**: Intermittently causes a small amount of pain and loss of focus
* **Libido depression**: Reduces morale gain from vibrators and *ahem* liaisons
* **Photophobia**: Reduces perception in bright light and causes mild pain
* **Irritability**: Increases severity of negative morale effects
* **Dysphoria**: Decreases magnitude of positive morale effects
* **Confusion**: Reduces intelligence, perception, and focus
* **Memory loss**: Reduces map memory buffer and focus
* **Dizziness/Vertigo**: These may need to be separated as symptoms if we gain the ability to model them separately but for now: reduce movement speed slightly, increase time to get up from knocked down, at high levels chance of randomly getting knocked down when walking (increases when running), decrease accuracy of attacks.
* **Discoordination**: Reduce dex and speed. When you press a directional button to move, there is a chance to move in one of the adjacent directions instead (including into hazards).
* **Blurry vision**: Reduce range of vision
* **Tinnitis**: Reduce range of hearing
* **Indigestion**: Represents both stomach ache and constipation. Causes pain after every meal, proportional to the volume of food consumed.
* **Antacid**: Reduces indigestion (for in-game purposes we can mush all laxatives and things in here too)
* **Nerve pain**: Causes general unrelenting pain that can't be treated by conventional analgesics (can be treated by neuropathic analgesics)
* **Aches**: Causes an unrelenting pain that responds to normal analgesics
* **Joint pain**: Causes pain when moving
* **Increased/decreased appetite**: For game purposes, work by decreasing or increasing the volume of the stomach so that hunger/satiety messages appear sooner or later.
* **Hot flashes**: Random mood penalty that is more likely to occur the higher the ambient temperature.
* **Heat/cold sensitivity**: Increases the severity of temperature effects
* **Itchy rash**: Experienced on a body part, causes morale penalty, worsened by amount of encumbrance on that body part.
* **Painful rash**: Experienced on a body part, causes pain, worsened by amount of encumbrance on that body part.
* **Insomnia**: Harder to fall asleep.
* **Cough**/**antitussive**: Causes the cough effect (no torso damage) or suppresses it
* **Breathlessness**: Reduces stamina pool.

### Tabular summary of recommendations

I have ranked the "potency" of each effect class from 1 to 5. Currently those numbers mean nothing, but I will work on getting some definitions.

1. Very slight effect, mostly flavour
2. Minimal effect but has some impact.
3. Average effect
4. Strong effect
5. Such a strong effect that it's easy to overdo it.

For name changes I suggest we move away from brand names of drugs, ideally settling on either using fictional names, generic terms, or maybe fictional name (generic term), eg thorazine (antipsychotic) or xanepam (sedative).

This is just a rough list. Really each drug should have its effects listed as maximum, and amount of drug where the effect is at 50% of its max effect, eg. `"nauseating": [ 4, 3 ]`. This can be plugged into a [Hill equation for dose response](https://en.wikipedia.org/wiki/Dose%E2%80%93response_relationship) to calculate how much of a given effect the drug should give at what concentration. The main trick here is to figure out what the "amount of drug" is going to be calculated in. I suggest the most intuitive way to do this for JSONers is to make "amount of drug" equal to the maximum amount in your system after taking that many doses of the drug, so for the above example for alcohol, if the player shotgunned three drinks they'd peak at nausea 2 when those drinks hit them. I'm open to suggestions for better or less math-y ways to do this.

In-game drug name | Drug class | Suggested effects | Other changes
------------ | ------------- | ------------ | -------------
Alcohol | Alcohol | Depressant 3, Anticonvulsant 2, Addictive 3, Tolerance 3, Rebound 4 , Diverting 3, Abusable 3, Dizziness 2, Nauseating 2, Discoordination 2 | May deserve a special "drunk" effect, but that would more be for messages to the player and less for mechanical changes, which should be modeled through drug effects as much as possible.
Adderall | Amphetamine | Mental stimulant 3, Physical stimulant 1, Addictive 1, Abusable 1, Insomnia 1, Indigestion 1, decreased appetite 1 | I suggest a name change to "Ritacentrin", or to simply "ADHD medicine".
low-grade methamphetamine | Amphetamine | Mental stimulant 2, Physical stimulant 2, Addictive 5, Tolerance 2, Abusable 4, Insomnia 2, Indigestion 2, decreased appetite 1, weight loss 1 | For this and other homemade drugs, a better system of quality level using chemistry tools to test purity would be wonderful.
Marijuana | Cannabinoid | Dissociative 2, Neuropathic analgesic 3, Hallucinogenic 1, Diverting 2, Abusable 3, Tolerance 1, increased appetite 1 | Might deserve a special cannabinoid effect as well since marijuana is pretty unusual in its mental effects.
Prozac | SSRI antidepressant | Antidepressant 3, Rebound 1, Neuropathic analgesic 2, libido depression 1, Dry mouth 1, indigestion 3 (decreases over time), Weight gain 1 | I suggest a name change to a fictionalized name, I suggest "Zolafine". Alternatively just change the name to "antidepressant".
Xanax | Benzodiazepene | Antidepressant 1, Addictive 4, Tolerance 3, Sedative 3, Anticonvulsant 4, Diverting 4, Abusable 2 | Needs a name change as well, I suggest "Xanepam" or simply "Sedative tablet'.
Lorazepam (new suggestion) | Benzodiazepene | Antidepressant 1, Addictive 3, Tolerance 3, Sedative 3, Anticonvulsant 4, Diverting 4, Abusable 2 | Does not currently exist in game, but this longer acting benzodiazepene is more common these days than xanax and should be in.
Thorazine | Antipsychotic | Antipsychotic 4, Sedative 3, Depressant 1, Weight gain 3, Dry mouth 2, Discoordination 1 | 
crack | cocaine stimulant | Mental stimulant 1, Physical stimulant 5, Addictive 5, Tolerance 2, Abusable 4, Insomnia 4, decreased appetite 3 | Faster onset and shorter duration than cocaine
cocaine | cocaine stimulant | Mental stimulant 2, Physical stimulant 4, Addictive 4, Tolerance 2, Abusable 4, Insomnia 4, decreased appetite 2 | Slower onset and longer duration than crack
Heroin | opioid analgesic | Analgesic 4, Depressant 3, Sedative 3, Addictive 5, Tolerance 4, Diverting 4,  Abusable 2, Indigestion 3, antitussive 1 | 
morphine | opioid analgesic | Analgesic 4, Depressant 3, Sedative 3, Addictive 4, Tolerance 3, Diverting 3,  Abusable 2, Indigestion 3, antitussive 1 | 
oxycodone | opioid analgesic | Analgesic 5, Depressant 4, Sedative 4, Addictive 4, Tolerance 3, Diverting 4,  Abusable 2, Indigestion 4, antitussive 1 | 
tramadol | opioid analgesic | Analgesic 2, Neuropathic analgesic 2, Depressant 2, Sedative 2, Addictive 3, Tolerance 4, Diverting 2,  Abusable 2, Indigestion 3, antitussive 1 | The only opioid in game that has neuropathic activity.
poppy cough syrup | opioid, antitussive | Analgesic 1, Depressant 3, Sedative 3, Addictive 3, Tolerance 3, Diverting 2, Indigestion 3, antitussive 3 |
poppy painkiller | opioid analgesic | Analgesic 2, Depressant 2, Sedative 2, Addictive 3, Tolerance 4, Diverting 2,  Abusable 1, Indigestion 5, antitussive 1 | Homemade painkillers tend to be very constipating due to the mix of opiate chemicals in them.
codeine | opioid analgesic | Analgesic 2, Depressant 2, Sedative 2, Addictive 3, Tolerance 4, Diverting 2,  Abusable 2, Indigestion 4, antitussive 1 |
destragon | Antibiotic | Strong antibiotic | Needs a full revamp of infection and sepsis. I suggest a name change as well, as "destragon" doesn't sound like an antibiotic at all. "Phenopenem" sounds like a last-resort antibiotic.
Atreyupan | Antibiotic | Weak antibiotic | Needs a full revamp of infection and sepsis.
antibiotics | Antibiotic | Regular antibiotic | Needs a full revamp of infection and sepsis.s

**Comment by Maddremor** [comment]
Opioids slow down digestion (possibly leading to indigestion). Although bodily excrection are not to be simulated, it could still have an effect on stomach/hunger and comfort.

**Comment by thethunderhawk** [comment]
I think the “low-grade” should be dropped from “low-grade methamphetamine”. To me the current name implies the meth is impure in some way, either cut with something else or cooked wrong. No reason to complicate things, meth should be meth.

**Comment by tenmillimaster** [comment]
Topical analgesics? It'd be neat to give cocaine a legitimate use.

**Comment by I-am-Erk** [comment]
Topicals should probably be handled separately, that would be its own list of effects. This assumes ingestion/injection

**Comment by aoae23** [comment]
I like this rework because it also paves the way for proper treatments of ODs. Though that is probably addressable in a separate issue.

In my opinion, we should stick with generic names if possible, and only use fictional drugs as a last resort, for the purpose of maintaining realism by making it easier to correct unrealistic drug effects.

I suggest that a more simplified approach where a "toxidrome" with a defined list of effects could be added, and then individual drugs could be assigned to said toxidromes. For example, two sedative-hypnotic agents should have a similar range of effects, only differing in intensity with exceptions for notable effects. To my novice coding knowledge this doesn't seem terribly difficult to JSONize too.

Also, do you think fentanyl would fit in the game using these effects? Also, is datura part of the scope of the issue?

**Comment by I-am-Erk** [comment]
@aoae23 ODs should in fact be baked in once we get a dose response curve, we do things like make respiratory depression a dose dependent side effect of opioids.

I am increasingly picturing these side effects working a lot like tool properties. Things like toxidromes could then be handled as just a plug-and-play group of side effects, where the "opioid" side effect list is constant and you just plug it into any opioid and give it a magnitude, but it actually applies a bunch of specific independently defined side effects. There could be others, like anticholinergics. Then one opioid being more constipating than another would be handled by giving the more constipating one a second, toxidrome-independent Indigestion side effect with different variables, stacking with the common one.

Datura is part of the scope of the issue, I've just picked a handful of drugs so far to experiment with settings. Adding new drugs like fentanyl would be a second issue, I want to make a whole project of this and part 2 is new drugs that should be added.

What I'm really keen on for this would be part 3: procedurally generating experimental drugs to be found in labs. I have some really weird ideas for that.

**Comment by Zireael07** [comment]
>  procedurally generating experimental drugs to be found in labs. I have some really weird ideas for that.

Oh be still my bleeding heart, that would be awesome <3 <3 <3

**Comment by Kodiologist** [comment]
> **Diverting**:… Reduces the severity of negative morale effects.

At least in terms of real-world psychology, that's pretty much the same as an antidepressent. Yes, alcohol is a CNS depressant, but it can also counteract actual depression to some extent.

> **Libido depression**: Reduces morale gain from… liaisons

I don't think sex is implemented, and I hope that doesn't change. Our inclusion of masturbation (with a vibrator) already represents far more realism than necessary, in my opinion.

**Comment by I-am-Erk** [comment]
> > **Diverting**:… Reduces the severity of negative morale effects.
> 
> At least in terms of real-world psychology, that's pretty much the same as an antidepressent. Yes, alcohol is a CNS depressant, but it can also counteract actual depression to some extent.

Antidepressant is already listed as an effect, and that's what it does. However the antidepressant effect takes weeks to build up, while diverting medications act quickly and temporarily.

**Comment by davidpwbrown** [comment]
> > **Diverting**:… Reduces the severity of negative morale effects.
> 
> At least in terms of real-world psychology, that's pretty much the same as an antidepressent. Yes, alcohol is a CNS depressant, but it can also counteract actual depression to some extent.
> 
> > **Libido depression**: Reduces morale gain from… liaisons
> 
> I don't think sex is implemented, and I hope that doesn't change. Our inclusion of masturbation (with a vibrator) already represents far more realism than necessary, in my opinion.

The set-in-absolute-stone word from Kevin on depictions of bodily functions and sex is mostly no.

As in, no depictions of it, no real descriptions of it.

Vibrator is the one legacy thing that kinda gets to stay.

Sexual liaisons with NPCs if ever implemented would have to be offscreen and alluded to in vague terms, its ever implemented in a way that is suitable.

I.E an NPC who offers "services of the night" or something equally euphemistic, and then screen fades to black and restarts in the morning with some kind of morale boost ( although using an NPC for this kinda thing for a morale boost feels very icky - thats the whole problem with the idea )

So although itd be tricky to implement in a way that isnt icky or bad taste, there is still a narrow space where such a thing might exist, and the effects of drugs or medication may interact with in positive or negative ways - therefore I can see why Erk is putting that option there just incase.

**Comment by DeimosDread** [comment]
I'm not sure dizziness/vertigo and discoordination need to be separated as they are now, or perhaps different terminology is necessary. Unless the plan for discoordination is less of just walking and a more complete loss of coordination for the upper and lower body, perhaps a crafting modifier instead of or in conjunction with the missteps for discoordination. Perhaps more severe dizziness (4+ on your scale for example) could cause missteps? Also, would/could the missteps happen while driving?

For tinnitus, if I could suggest flavor text of something along the lines of "You hear a faint/loud ringing (out of your left/right ear)." especially if you were just exposed to extreme sound, or haven't heard any sounds recently (this is anecdotal, but I tend not to notice it unless I'm in a quiet environment) as well as a small loss of focus when this occurs (which is probably outside the scope of this proposal). One last thing about tinnitus I believe it's one of its possible causes is ototoxic meds, like certain antibiotics, and large doses of ibuprofen (though I assume you knew this considering you included it in a list of possible side effects).

Maybe stick with generic names, and leave the fictionalized names for flavor text?

All that being said, this looks awesome!

**Comment by Silvenius** [comment]
To add to the above: opiates also reportedly kill sex drive, making the 'Vibrator' item not helpful to those characters;

dehydration/increased water need/dessicant should be added as an effect, definitely for Adderall and other uppers.

**Comment by souricelle** [comment]
Putting my money where my mouth is and posting some studies with timelines and probable effects. 

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6165228/

Here's Adderall. The study found that while it improved attention, mood, and focus, it actually mildly impaired memory, suggesting that the college kids using it to study are getting some benefit by being kept on task but might otherwise be suffering from reduced performance.

In pill form, the drug takes 30 minutes to start taking effect, peaks at 90 minutes, then starts dropping off at 210 minutes and eventually losing all effect by about 300 minutes. You can grind it into a powder (perhaps with a mortar and pestle) and snort it to experience peak effects within a minute or two. It then stands to reason that you would have peak effects at one minute, dropoff at 121 minutes, and sobriety again at 211 minutes. The drug's half-life is about 10 hours, and it takes 3 days for it to be completely eliminated from the body.

My suggestion would be that Adderall should improve mood and focus, with a small bonus to perception during its peak. Taking more than a single dose should probably only offer a greater mood boost and possibly an intelligence penalty as you creep closer to overdose.

People who use Adderall to stay awake do not feel tired, but they will still suffer the effects of sleep deprivation. These two are tracked separately so rather than inducing insomnia, it should simply reduce fatigue by ~50 points (fatigue seems to go up by 12/hour, Adderall lasts 5 hours). The logic here is that the drug will keep you up but fighting sleep with chemistry is always a losing battle.

Adderall is just amphetamines, so you could extrapolate from these numbers and timeline for proper meth, perhaps exaggerating the effects. There are many, many different kinds of amphetamines and potency varies wildly so there's not going to be any one set of numbers that work.

**Comment by souricelle** [comment]
Antidepressants should have little to no effect in the short term, as it generally takes a couple of weeks for a person's body to adjust to them (see: https://www.nami.org/About-Mental-Illness/Treatments/Mental-Health-Medications/Types-of-Medication/Fluoxetine-(Prozac) ). Furthermore they should not do anything for characters who don't have depression (see: https://www.webmd.com/depression/fears-and-facts-about-antidepressants). Antidepressants don't give you any kind of a high, they merely correct a dysfunction in people with certain kinds of mental illness. Rather than being a mood booster, they should work to prevent the negative mood from Bad Temper and Chemical Imbalance, as well as possibly offering a mild benefit to characters with Schizophrenia. There is probably an argument to be made for adding in an ADHD trait that impairs focus when not properly medicated and renaming Bad Temper to Depression.

Depression might also be a long-term condition that comes on if a character has a very poor mood for an extended length of time and brings on symptoms like chronic fatigue and an intelligence penalty. This would incentivize players to take better care of their characters and seek out sources of recreation, but is probably beyond the scope of this project.

**Comment by souricelle** [comment]
As for opioids, you seem to have the effects all worked out pretty well. If you need a timeline, https://www.oncolink.org/cancer-treatment/oncolink-rx/oxycodone-oral-immediate-release-pill-roxicodone-r-percolone-r has a typical oxycodone pill as coming on in 15 minutes with the full effects felt at 1 hour and dropoff starting at 3 hours, with the effects completely gone by 6. As with Addrall, Oxycodone pills can be ground into a powder and snorted for a faster effect ( https://erowid.org/pharms/oxycodone/oxycodone_dose.shtml ) but this reportedly stings like hell and can cause brief bouts of coughing and sniffles. I think insufflation should be an option whenever possible as many players/survivors are going to be taking drugs as needed to deal with emergency situations rather than long-term management of pain or other symptoms. Injected opioids like morphine would similarly work almost immediately.

Opioids/opiates of any kind can sometimes have itchiness as an unpleasant side effect, particularly during the comedown. There's no rash, you just get super itchy sometimes. Tinnitis is another one, and some long term users even experience partial hearing loss. ( https://emcrit.org/toxhound/sound-of-silence/ ). Permanent deafness is quite rare and should only hit chronic users but could be corrected with CBMs or other fantasy solutions.

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/lets-discuss-drugs/24246/2

**Comment by MichaelMacha** [comment]
I know I'm a little late to the party on this, and I'm a new contributor so apologies if any of this isn't important. However, I have a bachelor's in neuroscience (inclusive of a graduate course on psychopharmacology) and feel I can contribute. There are a few things that stand out to me after reading this over.

(Forgive me if this is a little long-winded, too.)

Drugs don't necessarily have the same intensity of effect on all people—it's more of a stochastic thing. That's why in drug development critical doses are initially determined by looking for the LD50 on animals, and later extrapolating (hopefully) that to match the effects on humans. That is, the concentration where 50% of the test subjects die—Lethal Dose 50%, LD50. Part of this is from tolerances developed by taking similar substances, part of it's genetic, etc.

So, it occurs to me that there would be some overflow of these effects across substances. As an example, carbamazepine, an anticonvulsant, also jacks up a patient's caffeine tolerance, just because they act on the same or related systems; caffeine has a lessened effect. It's probably going overboard to invoke all of the synergistics, antagonistics, and agonistics of all of these, but taking it into account could round out the in-game experience of taking an active substance. Maybe even if we just, initially, categorized them by effect rather than individual drug?

Forgive me if this is already being done.

The next thing to come to mind is, in the list above and from my own in-game experience, there are really two categories of substance. There's the specific molecular distillate, like, say, methamphetamine, and there's the plant containing such a substance, like marijuana or datura. I'm not sure why datura isn't in the list above, but what's interesting about it is that it actually contains a host of psychoactive compounds, including scopolamine (which is also a powerful non-narcotic painkiller with some really weird effects, and might make for a candidate for in-game inclusion as well), atropine (which can be used to slow heart rate down and has also shown use against some nerve agents), and hyopsciamine (more-or-less an antispasmodic). I really feel like they should be separated, and perhaps the ability to distill one substance out of another be implemented. Generally, plant-included compounds are weaker, whereas after distillation you can control the dosage, making them both more useful and potentially more dangerous.

The poppy-painkiller/poppy-sleep/poppy-cough-syrup thing could really be dropped if this is how we're doing it. Also, unless someone's going to tell me what "grade" means, or "high-grade" is going to be introduced—would that be better or worse?—we could abbreviate "low-grade methamphetamine" to just "methamphetamine", "meth", or even "crank".

I'm going to gloss over dosage for now.

The next thing is, not all effects come into play at the same time. As an example, take cocaine—I may have to look this up to be more precise, but it's more or less an hour long high, maybe a bit longer, followed by a half day of significant down. Not that I've done it myself, but it seems likely to me that this is perhaps part of what makes it addictive—users often attempt to use more of the drug to counter the down, rather than easing out of it. However, this isn't the whole story with it. Some effects only occur after the body has altered its metabolism in anticipation of it; this can go both ways as well. (Some seem to develop a tolerance, others actually become sensitized to the drug.) Prolonged usage can cause vasoconstriction around the colon, leading to ulcers and tears, but this isn't something a first-time user would ever have to contend with, because they haven't put themselves under the same repeated stress. While we're on the topic of cocaine, it also increases the risk of intracerebral hemorrhaging for much the same reason, increasing the risk of an aneurysm; but this is something that a first-time user would not yet have to worry about.

I feel like that could be introduced with some kind of history tracking in the game—has the player taken it before? How recently? What are the likely long-term stresses of it? Most of this could be done with a wiki look-up and a linear interpolation I think.

Lastly, the effects of a drug very much depend on its route of administration, more so than people tend to think. Going back to atropine, it's usually an intramuscular injection when administered clinically for the sake of, say, elevated heart rate or reducing saliva production during surgery; but if you take it orally, the effect is more likely to be antidiarrheal, simply because the compound has not been administered through the typical path. This effectively completely changes the nature of the drug, even though it's the exact same molecule. This can also be said for dosage, as some effects occur under lower thresholds than others; unfortunately I can't remember anything citation worthy on that at the moment.

So, chemistry and pharmacology is fun, but as much as we all like when things fit on nice even line-graphs pharmacology has never been that polite about it. It may be easier to just look up the specific compounds on a readily available website like Drugs.com or WebMD, and work from there. They really aren't "power ups", though; they've got their own lasting and exotic behaviors.

**Comment by I-am-Erk** [comment]
I had long mental debates over interaction systems and variable responses. The best I've come up with for the latter is not yet up above, I haven't updated the issue in a while, but put very shortly it's to have a list of side effects chosen randomly per character per drug and remembered by the system thereafter.

For drug interactions, I think we'd want a simplified tag representing where the drug is metabolized and what types of affects it has on other drugs with the same metabolic pathway. That stuff should also get added to this issue at some point but I have been much too busy elsewhere.

**Comment by actual-nh** [comment]
@DeimosDread: With regard to tinnitus, not ibuprofen, but salicylates (which include aspirin, pepto-bismol/etc (bismuth subsalicylate), and wintergreen flavoring - methyl salicylate). I have personal experience with this (I happen to be sensitive to much smaller doses than most... sigh), and they're used to induce tinnitus in lab animals.

Opiates: Most opiates will also cause problems with breathing, especially in someone with asthma. Exception: Tramadol, due to the additional receptors it stimulates.

**Comment by Night-Pryanik** [comment]
No discussion in almost a year, closing.
