### ISSUE TITLE
Put thermite to use

### ISSUE THREAD

**Issue by Mister-Cultist** [CleverRaven/Cataclysm-DDA#35761]
When I saw I could craft thermite in game I was pretty excited since it's real powerful stuff, I mean it's a powder that when lit on fire can burn through metal. The problem is that thermite is just a crafting component for the homemade incindiary rocket, last I tested it, you can't even light it on fire.

Since thermite is pretty easy to make it should be able to factor into a number of makeshift weapon recipes. Some of my ideas are a thermite grenade (see the new call of duty) a thermite breaching charge for blowing up metal doors (ie rainbow six siege) or maybe makeshift incindiary bullets and the like.

If no one's interested in making it I might get around to learning the code proper and doing it myself, been putting plans on trying my hand at programming the game.

**Comment by qutoh** [comment]
Thermite welding should also be a thing, perhaps taking longer to get it set up, doing significant damage to parts scaling down with greater part volume and skill, and being less useful for repairs. They use it to join railroad tracks, but there's no reason you shouldn't be able to use it for slapping together a functional (if a step away from collapse) metal framework with 'only' chemistry.

**Comment by Orinyau** [comment]
Thermite grenades are more like an easy to use thermite deployment package than a weapon. Unlike traditional grenades, they lack the fragmentation properties. The military uses them to destroy equipment. 

They would still be useful for zombies, creating a tile or two of temporary fire/molten metal that zeds could be lured into. Thermite traps would be cool, a flowerpot filled with thermite above a doorway with a magnesium lighter and a tripwire.

**Comment by kevingranade** [comment]
I'm quite certain there are various weapons one can assemble with thermite as a major component, but please do some research and base it on a tual weapons instead of, "ass seen in call of Duty".

There should definitely be some uses for thermite vis a vis demolitions, I understand you can form a tiny crucible onto a doorframe with clay to direct thermite onto lock assemblies and hinges for example.

**Comment by Mister-Cultist** [comment]
Right you are Granade, I used cod as an example that people would be used to but I am taking a look at real world implementations. The main draw about thermite is that it's easy enough to make and has plenty of use as a makeshift incindiary weapon in a situation like the cataclysm.

**Comment by Orinyau** [comment]
I haven't been able to find anything on thermite used as a weapon, besides nanoparticle thermite being used in fuel-air bombs. 

Sabotage and demolition is the niche filled by thermite. It is heavy, so splash is limited.

Copper oxide based thermite burns faster, my research shows that the reaction can be explosive, due to the fact that it is unstable, almost to the point of being considered "flash powder" depending on how it's mixed.
