### ISSUE TITLE
"Normal" cardboard boxes are absurdly rare

### ISSUE THREAD

**Issue by SpellingSword** [CleverRaven/Cataclysm-DDA#35795]
**Is your feature request related to a problem? Please describe.**  
Small and large cardboard boxes are seemingly everywhere, yet medium ones are nowhere to be found.

This makes Dino Dave's quest ludicrously hard to complete.

**Describe the solution you'd like**  
Replace some small/large box spawn points with medium ones.

**Describe alternatives you've considered**  
Make cardboard boxes craftable.

**Additional context**  
I don't think a lunatic hobo's fetch quest should be more difficult to complete than hub 01 recovery missions ¯\\\_(ツ)_/¯

**Comment by sah4001** [comment]
Supplies in item groups
- supplies_hardware has all boxes with a 2 probability
- office_mess has small and medium with 3, and large 2
In item_trades
- mischw has 2 for medium and large
item_groups
- 5 for medium in trash, others do not occur
- trash_forest has 2 for small and 1 for medium and large
locations
- recycle_paper has a 35 for medium box.

overall it looks like they should not be that rare, just all boxes are uncommon, but you get the others by consuming items, could make some chemical powders come in medium boxes to correct this, think a borax box. Otherwise look in a recycle center
