### ISSUE TITLE
[feature request] Shouldn't minilabs have some mutagen drops?

### ISSUE THREAD

**Issue by Amoebka** [CleverRaven/Cataclysm-DDA#35817]
**Is your feature request related to a problem? Please describe.**  
Minilabs mostly replace normal labs in default-generated worlds these days. While they arguably are a lot more interesting than old labs, they don't have mutagen supplies in them.
This is "bad" because it leads to a situation where the majority of mutagen player takes is cooked by them rather than looted. Which doesn't make a lot of sense from an immersion perspective.
From a gameplay perspective, old labs are actually a lot LESS dangerous than minilabs, so them having better end-game loot feels weird.

**Describe the solution you'd like**  
Add those "advanced PE07 sample" vaults to minilabs. Maybe switch them from consoles to card readers to be consistent with current minilab "finales".

**Describe alternatives you've considered**  
Do nothing about it?

**Additional context**  
The current mutagen implementation is bad because it has the same problem as old bionics. Since virtually all mutagen is player-crafted, and ingredients are trivially available, the player usually goes from "0 mutations" to "20 mutations and post-threshold" in one big leap. If mutagens had to be looted instead, it would provide a much smoother transition path (find 5 serums in a lab - consume them - find another 5 in the next lab - consume - etc).

**Comment by John-Candlebury** [comment]
Microlabs can rarely spawn a mutagen vault, same as how they can spawn the new alpha mutagen cloning room and the CBM clinic, and the vault has the same odds as those two.

Most likely, you've had bad luck with the spawns, or havent fully explored the labs.

**Comment by Amoebka** [comment]
The suggestion is to make mutagen vaults regular rooms, not just a possible finale (old labs have both serum vaults AND common mutagens on regular shelfs in some rooms). A single alpha serum is basically nothing (we are talking about going post-threshold, and not just in alpha), and having 3/4 (there's also some electronics-based non-CBM finale?) labs contain no mutagens doesn't really make it common enough to push looting over crafting.

**Comment by kevingranade** [comment]
> Since virtually all mutagen is player-crafted, and ingredients are trivially available, the player usually goes from "0 mutations" to "20 mutations and post-threshold" in one big leap.

If this is the case, no amount of lootable mutagen will make a difference.  Crafting *must* be meaningfully difficult for looting to be a real alternative.

As for your suggestion, how much do you think is necessary, and why?

**Comment by Amoebka** [comment]
The issue with crafting mutagen is that all ingredients and tools fall into two categories. The first is trivially obtainable ingredients - blob globs, tainted meat, bird eggs, chitin, etc. Demanding the player uses them for crafting is basically nothing but wasting their real time, because obtaining them poses no risk whatsoever and is pure tedium. The second is chemical supplies and tools which currently all spawn in the same exact places - labs. It doesn't matter if the recipe asks for ammonia and bleach or a list of 20 different chemicals - if they all spawn in the same location they will be obtained at the same time and might as well be a single ingredient.
So, basically, to craft mutagen the player currently needs to dive a lab (tools, recipe books, chemicals) and then grind some boring stuff like foraging bushes (bird, lizard, plant, etc) or killing easy prey (beast, feline, spider, etc). Since the only actually difficult part is diving a lab, the lab should just contain mutagens themselves instead of ingredients that need to be combined with honey and fish tails.
The only real way to make mutagen crafting "meaningfully difficult" is then to split the needed ingredients between multiple challenging locations. Which isn't really a sane solution, because labs logically SHOULD have everything you need from a story/realism perspective.

My proposal would be to actually just make mutagen uncraftable and dramatically raise its drop amounts in labs, but I can see this being a rather unpopular solution. Still, I don't think the current tedious grindfest is any better.
As for the amounts, I think looting 6-7 labs to get far into the tree you want seems reasonable. So, on average, 2 flavoured serums (or 3-4 mutagens) of each tree per lab. And I think for immersion reasons labs should specialize in certain flavours, so any given lab would only contain a few mutagen trees in it, but in fairly large quantities (so that finding 2 labs that specialize in the tree you want is enough to get you a mostly finished tree). The player is then also presented an interesting choice of going for the first mutation tree their first lab provides them or keep looking for the one they want.

**Comment by thethunderhawk** [comment]
You could make basic mutagen non-craftable, but keep everything else the same. That way both angles (premade serums/cooking your own targeted serums) are tied to exploring. You could tweak the spawns of pure mutagen/strum as needed for balance.

**Comment by Zupercharged** [comment]
This is just my impressions but what I found particularly odd, related to the original issue, is the fact that this is the only kind of lab I have found that has failed mutants, yet all I got were bionics. The original labs have a similar discrepancy as I was the only mutant in a lab full of mutagens, cloning vats and failed cyborgs and the autodocs to make them. The labs are great, the mini ones _look amazing,_ but they do come across a bit confused.

I recently cleared a mini lab as a unwilling mutant and spent a few hours afterwards collecting **_EVERY_** bit of loot to the elevator to take inventory, leaving nothing but the corpses (actually had to make two piles of clothes since it spilled over). Notable finds were the 203 clean water bottles, a few science SD cards, 201 credit cards totalling just shy of $45k, 3 UPS, a carp ton of drugs and books, and 7-8 bionics (including good ones like hydraulic muscles). Sounds nice but then you realise this was the best of it, and the bionics, books and drugs were the only really useful loot and they all were random drops from scientists!

Difficulty wise the minilabs are a massive improvement over the originals; the massive zombie population with manhacks and failed mutants mixed in was a thrill to deal with and this was only helped by removing the compartmentalised metal doors from the original labs that can even contain the zombie hulks, so you couldn't just cheese it by taking a breather on the other side. The loot definitely lets it down though, since all the chemical stuff and scientific apparatus is only useful to scientists who know how to use it. 

Normal labs just have a more practical selection for relatively less danger; bionics and mutagens sure, but also army gear and weapons from the barracks, books from the library and plenty of lab reports, friken _kevlar_ and stuff for actual crafting and not to mention the experimental stuff at the finales.

The mini lab was a fun experience, and I wouldn't go so far as to say it was unrewarding. But the valuable stuff, the 'meat' of the loot, really shouldn't be dependent on the zombie random drops. The mini lab has all this apparatus but everything of value you have to make yourself, meanwhile the big labs have all the loot in the world, ready to use, with only a few tedious turrets standing in the way.

**Comment by thethunderhawk** [comment]
I mean, I think most will agree that the mini labs are just straight-up more fun than old labs. I assume the long term plan is to work the new style into the old locations.

**Comment by John-Candlebury** [comment]
Thanks for your feedback @Zupercharged, its very valuable!

>This is just my impressions but what I found particularly odd, related to the original issue, is the fact that this is the only kind of lab I have found that has failed mutants, yet all I got were bionics. The original labs have a similar discrepancy as I was the only mutant in a lab full of mutagens, cloning vats and failed cyborgs and the autodocs to make them. The labs are great, the mini ones look amazing, but they do come across a bit confused.

The microlab that is playable right now is just the generic mapgen framework that will later be used to create more interesting themed variants. Its mostly just a senseless combination of all possible lab monsters and of the most basic lab loot, because the only part that is supposed to be final are the labyrinthine room layouts.

The current implementation will be replaced by themed variants later down the line, that will take care of the monster discrepancy, and that will  take care of the loot problem by adding more interesting and specialized loot.  However we need something akin to #33845 so that the variants can be created without loots of json file duplication.

**Comment by kevingranade** [comment]
No concrete suggestion for how much mutagen spawns are necessary, and nonsrgumentvfor how this would address the raised issues
