### ISSUE TITLE
Drugs should be not identified automatically on sight

### ISSUE THREAD

**Issue by Silvenius** [CleverRaven/Cataclysm-DDA#35881]
**Is your feature request related to a problem? Please describe.**  
In the real world, drugs are not easy to identify. Drugs in-game should be physically described and contain variance with the possibility of unexpected interactions.

**Describe the solution you'd like**  
Obscure drug names (cocaine, low-quality meth, etc) with physical descriptions of substances. Characters would roll vs PER, Cooking or Survival (for example) to automatically identify them, with possibilities for mistakes.
This would add a new item: drug-testing reagent kit (10) which would allow for detection of tested-for compounds. 
Fentanyl may cause adverse reactions to opiate-naive characters, for example.

**Describe alternatives you've considered**  

**Additional context**  
Add any other context (such as mock-ups, proof of concepts or screenshots) about the feature request here.

**Comment by anothersimulacrum** [comment]
This would be a huge regression in UX.
Besides, once players memorize the descriptions (or look them up), this is not effective.

**Comment by Szara-ManOfHonor** [comment]
Street drugs could be implemented like poisonous mushrooms are now to make them a bit more dangerous to deal with, which seems appropriate given how often accidental overdoses occur in real life due to people not realizing what they're dealing with.
Prescription and over the counter drugs and the like should be found in well labeled containers.  Sure in reality that wouldn't 100% always be the case but that seems not worth following up on.

**Comment by Aphegis** [comment]
If this is done, the drug should take on a generic name like "Unidentified drug", with no description that would allow the player to memorize which drug it is. However, I think at the moment this would only slow down gameplay and would be a good idea when the game had implemented the "chemistry" planned skill.

**Comment by TechyBen** [comment]
Yeah, not many people keep tablets in unlabeled packages. They either keep the original blister pack, or in a dispenser (with label). Though occasionally it may happen.

**Comment by Silvenius** [comment]
> This would be a huge regression in UX.
> Besides, once players memorize the descriptions (or look them up), this is not effective.
I have no comment regarding your first point.
I somewhat disagree with your second point. There are many forms of street drugs which have the capacity to look very similar to one another-- powdered cocaine and certain forms of speed, for example, and certain forms of speed and certain kinds of powdered heroin, for another. The potential for misidentification is present.

**Comment by CSHague** [comment]
Sounds a lot like potions in older ASCII titles. Have the description "<color>, <pill-type> pill(s)" and then randomize each drug for every new game world and then let drugs like aspirin have the same description every game. Naturally, drugs would be in labelled bottles so you just add a custom inscription for the plastic bottles you'd put them in: small plastic bottle labeled "Aspirin". It could also be a vehicle for randomly generated brand names for various drugs: a small cardboard box labelled "Sleepquil" It contains 16 green gelcaps.

You can find a PDR in the game, so that could aid the player in identifying most commercially-produced pharma.

**Comment by kevingranade** [comment]
By default we assume pharmaceuticals are packaged. Non-packaged drugs needing identification is a possibility, but it needs to be handled properly, i.e. visually similar substances being grouped together rather than anonymizing everything.
