### ISSUE TITLE
Purchased food from NPC merchants turns to rotten 1 turn after being bought

### ISSUE THREAD

**Issue by SpellingSword** [CleverRaven/Cataclysm-DDA#35906]
# Describe the bug

Buying food from NPCs seems to be broken. If you do not skip a turn after buying it, you can see it being fresh. 1 turn later it turns to rotten.

# Steps To Reproduce

1. Buy any food from a merchant
2. Wait a turn/move/do anything
3. Watch it rot before your very eyes

# Expected behavior

Player character isn't Tantalus

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-9846-g34ac4b8 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    No Fungal Monsters [No_Fungi]
]

**Comment by k4gi** [comment]
This happened to me just now. Starting NPC gave me a zucchini, no pockets so it fell to the floor, instantly rotten.

- Ubuntu 19.04
- 0.D-10040-ge8bfb5e29f 64-bit
- Tiles
- - Dark Days Ahead
- - Disable NPC Needs
- - Makeshift Items Mod
- - More Survival Tools

**Comment by davidpwbrown** [comment]
The problem here is that NPCs spawn with their inventory items ( and shop restocks ) given a birthday of time_point - 0  ( 0 being the date of cataclysm ) and now that the game starts by default on day 60, most foodstuffs spawn in the NPC inventory rotten.

This is not color-coded in the trade interface, so its not easy to spot, but its not the act of trading that makes it rotten, it was created in their inventory rotten.

I think a suitable fix would be to spawn it with a birthday of before_time_starts
