### ISSUE TITLE
Varying fouling levels and firearm state during character creation

### ISSUE THREAD

**Issue by CountAlex** [CleverRaven/Cataclysm-DDA#36004]
# Describe the bug
Professions with a firearm in equip allow different state/fouling for a gun with multiple choosing of a profession.

# Steps To Reproduce
1. Initiate character creation
2. Find one with a firearm
3. Scroll back and forth watching fouling level and state of a firearm (faulty/not faulty)

# Expected behavior
Predefined level of fouling/functionality of a firearm whether global or per profession.

# Screenshots
![1](https://user-images.githubusercontent.com/26584783/70557598-2ea69400-1b94-11ea-9206-03b40c42813e.png)
![2](https://user-images.githubusercontent.com/26584783/70557603-2fd7c100-1b94-11ea-9300-1c4e9a07c3eb.png)
![3](https://user-images.githubusercontent.com/26584783/70557607-31a18480-1b94-11ea-9044-3ba18796a083.png)

# Versions and configuration
OS: Win 7x64
Game Version: 0.D-10040-ge8bfb5e
Graphics version: Tiles
Mods loaded:Disable NPC needs

# Additional context
N/A

**Comment by kevingranade** [comment]
Pinning this to 0 fouling would be fine, as would making it configurable in the profession spawn list.

**Comment by anothersimulacrum** [comment]
Note that after #36341 this is harder to see, but fouling is still being varied when guns are spawned here.
It would be possible to fix this in JSON by specifying when guns are spawned that they have 0 fouling in the itemgroup, but that's a bit fragile - some solution capping it to 0 unless otherwise specified would be better, in my opinion.
