### ISSUE TITLE
Can crack a safe with a stethoscope while simultaneously listening to an mp3 player

### ISSUE THREAD

**Issue by PenceGL** [CleverRaven/Cataclysm-DDA#36013]
Game version: 0.D-10020-gd9d23c5 (tiles), build 9981
Operating system: Windows 10

Mods active: None

### Expected behavior
A prompt to turn off your mp3 player before trying to crack a safe with a stethoscope, or just a message saying something like: "There's too much noise for you to try to crack the safe!"

### Actual behavior
The entire time spent cracking the safe, music just plays and focus goes up like you aren't doing anything but listening to music.

### Steps to reproduce the behavior
Find stethoscope and mp3 player, turn on mp3 player, crack safe.

**Comment by ThomasLinkin** [comment]
That's weird,since quite a few exper patch ago i tried to do the same but the game didnt let me crack the safe whilst listening to the mp3 . seems like something went wrong in the past few updates

**Comment by wapcaplet** [comment]
I’ve started on a fix for this, but found a small snag: activating an MP3 player takes 0 time, and the “can’t hear” icon does not appear above your avatar until you wait 1 turn or do something else that causes time to pass.

So, in my current attempted fix, if you activate an MP3 player and immediately start safe cracking, it works because you are not “listening to headphones” when you begin, though it prints the music messages the whole time. But if you’ve had the MP3 player on for more than 1 turn when you begin, and the “can’t hear” icon is showing, you’ll be prevented from attempting to crack the safe.

Activating the MP3 player probably ought to take at least 1 second, but I’m not sure how many players may have come to depend on that action being “free”. I’m not sure how else to get around the above loophole, though.

**Comment by Night-Pryanik** [comment]
Just add a few seconds activation time in `mp3` iuse function, and it's good to go.

**Comment by wapcaplet** [comment]
Figuring out how to add that 1-second wait for mp3 player activation took longer than fixing the original bug! And now there's a loophole at the end (since it takes 2 seconds for the music to stop, for some reason I can't figure out), but that seems like something we can live with. PR submitted.
