### ISSUE TITLE
Clear or Sunny weather with a full moon is too bright to sleep

### ISSUE THREAD

**Issue by digitCruncher** [CleverRaven/Cataclysm-DDA#36036]
# Describe the bug

When there is a full moon, and the weather is clear or sunny, the lighting will be 'bright', allowing easy reading of books, unlimited crafting, and most notably being too bright to sleep.

# Steps To Reproduce

Unzip attached RAR file, and play the attached game. Note that 5 minutes ago it was impossible to sleep (in the double bed to the south of the building, next to the open window)
OR
Change the time and day to a day which has the moon indicator showing a full moon. Change the weather to either clear or sunny. Go outside.
In both cases, the lighting is bright.

# Expected behavior

The outside weather should be, at most, cloudy. This would allow slow crafting and the ability to read books. It would also mean sleeping outside would wake you up 'too bright to sleep' when you are not tired at all, but would also mean that sleeping inside would be 'very dark' and you would never wake up because the moon is too bright.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-10063-g278da94 [64-bit] [Build 9987]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Folding Parts pack [deoxymod],
    Mutant NPCs [mutant_npcs],
    No Flaming Weapons [no_flaming_weapons],
    No Survivor Armor [no_survivor_armor],
    NPC traits [npc_traits],
    Bens GF recipes [Tolerate_This],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    DinoMod [DinoMod],
    Bionic Slots [cbm_slots],
    No Rail Stations [No_Rail_Stations],
    Roadheader and other mining vehicles [Heavy miners]
]
[False Pass - Copy.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3952881/False.Pass.-.Copy.zip)

**Comment by wapcaplet** [comment]
I tried to reproduce this issue using your attached save game, but could not - the main issue is that the player in this save game has only 15 fatigue, which means they are practically wide awake:

![image](https://user-images.githubusercontent.com/238395/93009560-0cd1a780-f540-11ea-9f82-c6b7a90b749c.png)

Fatigue needs to be close to 200 before the character is "tired", and over 380 for "dead tired". This character won't be able to sleep easily until they are considerably more fatigued.

Using a new game, I had no trouble sleeping by the light of a full moon. With the debug menu:

- Spawn a luxury RV (for safety, and a bed near a window)
- Change `m`ap `t`ime to day 74 (full moon), hour 0 (midnight)
- Change `m`ap `w`eather to 2 (clear)
- Get into the bed in the back of the RV, and open the curtains - light will be "bright"

![image](https://user-images.githubusercontent.com/238395/93009654-d0eb1200-f540-11ea-861f-1e796a9e823e.png)

Trying to sleep right now will be fruitless, since there is no fatigue. There are no messages about it being too bright to sleep.

Now, set fatigue to 200 with the debug menu, by editing player needs. This is the first level of "tired", and should be plenty to allow falling asleep on the bed next to the window, and full moon. For me it worked on the first try.

Around 6:00 am, the sun will come up, and make it *really* too bright to sleep:

![image](https://user-images.githubusercontent.com/238395/93009688-317a4f00-f541-11ea-9e44-f29aa7eafee6.png)

Looks to me like this is working as intended. Can anyone confirm?
