### ISSUE TITLE
New map extras can overwrite overmap specials

### ISSUE THREAD

**Issue by Amoebka** [CleverRaven/Cataclysm-DDA#36273]
# Describe the bug

New fields map extras (long grass, ponds, trees, etc) can overwrite normal overmap terrain completely destroying it, but not removing it from the map. Most often happens with farm plots but can also be much more nasty. In the screenshots below a cave got overwritten by long grass.

# Steps To Reproduce

1. Make a world.
2. Teleport to overmap specials in fields until you see one overwritten by a new extra?

# Expected behavior

Extras that completely overwrite a tile shouldn't be extras and should just be an overmap terrain of their own? Terrain-overriding extras shouldn't destroy actual specials, at least.

# Screenshots

According to the map there should be a cave here...
![cdda — копия — копия](https://user-images.githubusercontent.com/44502845/71206805-0fb4aa00-22d8-11ea-8cae-1347720b97c3.png)

... however it is completely overwritten by a patch of long grass.
![cdda — копия](https://user-images.githubusercontent.com/44502845/71206799-09263280-22d8-11ea-83dc-9f60e7bef70d.png)

# Versions and configuration

 - OS: win10
 - Game Version: 0.D-10481-gd4ee75a
 - Graphics version: tiles
 - Mods loaded: none

# Additional context

While the issue with grass is obvious, it also kinda raises a question of why these things are implemented as map extras at all. We already have ponds in fields that are actually marked on the map as ponds because they are their own terrain, but now we also have new extra ponds that aren't? There are already desolate barns in fields that are shown on the map, but there are also new barns that aren't? A corpse of trees is basically a forest tile in a field, why isn't it shown as forest on the map?

**Comment by ralreegorganon** [comment]
Map extras are free to overwrite what's at the location--having a helicopter crash into a building, or a portal spawn and destroy the area are all intended. Additionally, there are mapgen mechanisms to make non-conflicting changes--e.g. the grass could use a ter_furn_transform to only transform a certain class of terrain into grass instead of overwriting the rocks. 

However, I think the primary issue here is that there are overmap terrains which are referencing the "field" map extra collection that probably shouldn't be.

For example, [the cave in question](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/overmap/overmap_terrain/overmap_terrain_hardcoded.json#L190):
```json
{
    "type": "overmap_terrain",
    "id": "cave",
    "name": "cave",
    "sym": "C",
    "color": "brown",
    "see_cost": 2,
    "extras": "field",
    "flags": [ "NO_ROTATE", "SOURCE_SAFETY" ]
  }
```
