### ISSUE TITLE
Remove unnecessary uses of "charges" in item definitions and recipes

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#36270]
**Is your feature request related to a problem? Please describe.**  
"Charges" are an antiquated concept in game. We should universalize our item management to use 'counts' for all items.

**Describe the solution you'd like**  
A good start through JSON would be to find items that use "charges", such as many food item powders and liquids, revise the volume and weight to be for a *single* charge, and remove any reference to charges. This will also require tracking down recipes and spawn groups that call that item and changing charges to counts.

Once the JSON end is done it would be comparatively easy to pare out the code.

**Comment by DaviBones** [comment]
This is a lot more complicated than you're making it out to be, and almost certainly a regression. The `charges` value of items is used to define the *default* number of charges that spawn (or are crafted). This means that for every item you changed, you would need to go through *every appearance* of that item in the entirety of the JSON, and:

1. If `charges` keyword is present, change it to `count` (as you already stated).
2. If `count` keyword is present, multiply it by the old `charges` value of the item.
3. If neither `charges` nor `count` is specified, add `"count": X` where X is the old `charges` value of the item.
4. (Note that in recipe definitions, it's called `result_mult`, not `count`.)

If you did not do this, you would get stuff like individual aspirin tablets spawning, rather than in groups of 10. This would mean *far* more verbose JSON entries in general, most noticeably in item groups. This is why I consider it a regression.

*However*, I *do* think that the `stack_size` property of items *is* actually antiquated and useless, and I think you may have been conflating the two (very easy to do, since `stack_size` defaults to whatever `charges` is, and `stack_size` is very rarely defined on its own). AFAICT, it was for volume granularity before... well, before we added granularity to the actual volume. The steps for removing that are as follows:

1. Go through all items with a `charges` entry, but *without* a `stack_size` entry, and divide the volume and price (**not** weight, that is already for a single charge) by the `charges` value.
2. Remove the `stack_size` entry from all item definitions. Divide volume and price by the old `stack_size` value.
3. This requires a bare minimum of C++ work; you must, at the very least, find where `stack_size` is set equal to `charges` if not specified, and have it default to 1 instead. Otherwise, they will be divided by the `charges` value twice: Once by yourself, in step 1, and once automatically by the `stack_size` code.
