### ISSUE TITLE
Throwing rocks crashes game

### ISSUE THREAD

**Issue by Xarafax** [CleverRaven/Cataclysm-DDA#36271]
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3985483/crash.log)
Game version: 
0.D-10481-gd4ee75a (tiles)
Build 10033

Operating system: 
Windows 7 Pro 64-bit

Tiles or curses: 
Tiles

Mods active:
Aftershock
Makeshift Items Mod
More Survival Tools
Modular Turrets
Salvaged Robots
Alternative Map Key
More Locations
Fuji's More Buildings
No Rail Stations
Folding Parts Pack
Vehicle Addition Pack
Tanks and Other Vehicles
Arcana and Magic Items
Manual Bionic Installation
Safe Autodoc
Simplified Nutrition
SpeedyDex
Stats Through Kills
Stats Through Skills

### Expected behavior
Throwing rocks doesn't crash game
### Actual behavior
Throwing rocks crashes game 

### Steps to reproduce the behavior
I wielded 10+ rocks, when I throw one rock and check my inventory, I see I only have one rock left being wielded. When I throw that last rock it looks like it's been thrown, but no rock lands on (or near) the target square. When I picked up the first rock I threw (The one that cost 10+ rocks to throw) it shows that it is only one rock. When I try to throw that bugged rock the game crashes with the following error message:

CRASH LOG FILE: config/crash.log 
VERSION: 0.D-10481-gd4ee75a
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:
   @0x555932[cataclysm-tiles.exe+0x155932]
   @0x555BAA[cataclysm-tiles.exe+0x155BAA]
   SMPEG_error+0x3DAF3@0xCA8825[[cataclysm-tiles.exe+0x8A8825]
   @0x727C9D3
   @0x1006b666
   RtlKnownExceptionFilter+0xB7@0x76F150E7[ntdll.dll+0x750E7]
   RtlKnownExceptionChain+0x36@0x76ED97D5[[ntdll.dll+0x397D5]

This error message is followed by a Microsoft Visual C++ Library Runtime termination message.

**Comment by Xarafax** [comment]
crash.log Entry:

CRASH LOG FILE: config/crash.log
VERSION: 0.D-10481-gd4ee75a
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
Crash.log Entry:
STACK TRACE:
    @0x555932[cataclysm-tiles.exe+0x155932]
    @0x555BAA[cataclysm-tiles.exe+0x155BAA]
    SMPEG_error+0x3DAF3@0xCA8825[cataclysm-tiles.exe+0x8A8825]
    @0x727C9D3
    @0x1006B666
    RtlKnownExceptionFilter+0xB7@0x76F150E7[ntdll.dll+0x750E7]
    RtlInitializeExceptionChain+0x36@0x76ED97D5[ntdll.dll+0x397D5]

**Comment by ChucklesTheBeard** [comment]
I think this is related to #36239 .
Reproduced the segfault in a new world, default settings, only dda.
[DebuggerVille.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3986591/DebuggerVille.zip)
1. Load save.
2. [t]hrow
3. [m]rock(1)
SIGSEGV

Presumably this has something to do with other rocks being present, because I can't reliably reproduce the bug in the default sheltered start.

[crash.log
](https://gist.github.com/ChucklesTheBeard/590f1eb760a5c84d9c0b1e8761d2b1ab)

INFO : Cataclysm DDA version 0.D-10538-g[1ccb6a8565](https://github.com/CleverRaven/Cataclysm-DDA/tree/1ccb6a856525171840e5b63b5f6b291cc74e6dbc)

**Comment by Xarafax** [comment]
Tested it again. It appears that throwing any stackable item causes the game to crash.
