### ISSUE TITLE
Keybindings "Reload Item" and "Reload Wielded Item" do the same thing

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#36297]
# Describe the bug
The keybindings "Reload item" and "Reload Wielded item" both go to the same menu with tailoring kit, the reload item menu.

# Steps To Reproduce
1. Make keybindings for both reload item and reload wielded item
2. Notice they both lead to same menu

# Expected behavior
Reload wielded item should try to immediately reload wielded item

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-10211-g0bd1ad2 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda]
]

**Comment by Ramza13** [comment]
So if reload wielded object fails to find any wielded object or weapon or magazine in your inventory it will then call reload item and pop up the menu to allow you to reload something else.  This seems intentional so you don't need to map both keys.

Heres the description of the reload wielded item(which under the hood is called reload weapons because that's really what it does first even if they aren't wielded)
https://github.com/CleverRaven/Cataclysm-DDA/blob/b1541cdf946105d4fe830e383ebec9ff7abba86d/src/game.cpp#L8482-L8488

**Comment by CoroNaut** [comment]
So is this feature only meant for weapons with magazines and ammuntion and not items like tailoring kit? I would much prefer to be able to reload the tailoring kit with the "reload wielded item" rather than having to use the "reload item" menu for it.
