### ISSUE TITLE
advanced inventory moves too much

### ISSUE THREAD

**Issue by captnblood** [CleverRaven/Cataclysm-DDA#36414]
# Describe the bug
advanced inventory moves objects that are not displayed on current panel.

# Steps To Reproduce
here is the case situation:   
you find nice clothes or armor you want to wear.    
you need to remove your current clothes and put the new ones.   

1. open advanced inventory, on left panel: select 'worn items' to display only clothes
2. on right panel select some tile on the floor where there is some other clothes for example
3. make all your clothes from inventory to move from left panel (inventory) to right panel (tile floor) by pressing "," key.
4. you will see _all_ your inventory gets moved, not just your worn clothes, but everything.

# Expected behavior
advanced inventory should only move what it currently shows.
if it shows 'worn item' panel there is no reason it also moves lighters and books and first aid kit etc ...

# Versions and configuration

 - OS: archlinux (some variant of it)
 - Game Version: 0.D-10667-g87ced37c15
 - Graphics version: Tiles
 - Mods loaded: dda

**Comment by Szara-ManOfHonor** [comment]
This isn't a bug. When you drop clothing and it reduces the volume of your inventory capacity below the volume of items in your inventory, excess inventory is also dropped so that you are not carrying more than you have the capacity to carry. The excess items are dropped in the same spot where you drop the clothing. This somewhat simulates dropping those items while they are contained within said clothing.

**Comment by captnblood** [comment]
alright then, case closed :)
thanks @Szara-ManOfHonor
