### ISSUE TITLE
Lab Prisoner Containment should have an autodoc in locked room.

### ISSUE THREAD

**Issue by glenmack** [CleverRaven/Cataclysm-DDA#36508]
Lab prisons are almost entirely useless. Hacking/drilling your way into the final room to find it empty or with easily available meds has made it a "wasted" end point for myself and notably vormithrax, as we both often ignore prisoner containment entirely.

The locked room at the back would have way more incentive should it contain an autodoc, but no cbms or meds. It makes sense as the contained specimens would likely be operated on. Maybe a doctor badge spawn too.

**Comment by Fris0uman** [comment]
There's already some cells near the autodoc, not everything needs to have a reward in it. It make sense for a prison to be pretty un interesting loot wise.

**Comment by glenmack** [comment]
> There's already some cells near the autodoc, not everything needs to have a reward in it. It make sense for a prison to be pretty un interesting loot wise.

Then there's no reason to have the prisoner containment at all, except to reduce the possible number of barracks and libraries, which DO have interesting loot. I'd be ok with removing the autodoc normal rooms and replacing the prisons entirely with autodoc prisons.

**Comment by Zupercharged** [comment]
The argument could be made that they are necessary because they're worthless. As someone who just had a lab start with 8 prisoner containment cells (roughly half the special cells overall) I wouldn't say what I got from the remaining barracks, storage cells and finale wasnt satisfying or rewarding, and for what its worth thats with reduced loot settings.

I dont find containment unrewarding because I know not to bother clearing them in the first place. On the other hand they prevent the overpopulation of labs with other special cells which might have to be rebalanced otherwise. And the question should probably be asked how rewarding sample and CBM storage even is when all most people do is take a jackhammer to it, just watch the timer tick down and get a nice pick of otherwise rare loot with none of the risk or security that hacking in has. 

I would argue that its prisoner containment that makes these storage cells so rewarding, because the odds were that much lower for it to generate in the first place. Victory against odds can be as rewarding as overcoming challenge, and since a shutter isnt all too challenging whats left?

**Comment by scorpion451** [comment]
I can go along with the idea of them being the "sad trombone" roll for the locked-room-generator compared to the others, but it would be nice if there were some motivation to explore them anyway: As it is I usually just ignore them entirely unless I'm desperate for some common medical item that may or may not be in there, or want to shut up the banging that's making it hard to sleep in a nearby room.

Maybe a better answer would be to mix up the contents of the cells more- some might have recruitable NPCs like quarantined survivors who really did just have a cold or mutated test subjects ala the player start, some might have been repurposed as a storage room for the lab (putting lots of low-grade loot behind some early-to-mid-game hurdles), that sort of thing.

**Comment by Zupercharged** [comment]
Being prisoner containment it is entirely plausible that it could have some sort of NPC locked away among the usual monstrosities, maybe a scientist locked themselves in the storage cabinet for safety only to realize they cannot escape? I personally dont care much for NPCs but for those that do it could help liven up the labs a bit more. Maybe it could tie in to a hub01 quest where you have to recover something, or someone?

**Comment by kevingranade** [comment]
We don't do arbitrarally buffed areas, some places should be great, some should be awful.
