### ISSUE TITLE
Auto-repaired vehicle frames with no cost

### ISSUE THREAD

**Issue by NeevAsteria** [CleverRaven/Cataclysm-DDA#36513]
# Describe the bug

When using damaged vehicle frames and using the 'Start Vehicle Construction', the frame is automatically repaired to full health without any cost or effort.

# Steps To Reproduce

1. Acquire a damaged vehicle frame
2. Open construction menu and select "Start Vehicle Construction"
3. Make sure to use the damaged vehicle frame
4. Examine vehicle to check the health of the frame

# Expected behavior

The vehicle frame should reflect the health of the frame when making a new vehicle, similar to when using a damaged frame to install on an existing vehicle.

# Screenshots

![Test](https://user-images.githubusercontent.com/58652206/71546238-ebd81f00-29cf-11ea-8cf6-409d836834d4.PNG)
![Test2](https://user-images.githubusercontent.com/58652206/71546240-eed30f80-29cf-11ea-918d-1a8c2cf06a07.PNG)
![test3](https://user-images.githubusercontent.com/58652206/71546242-f09cd300-29cf-11ea-94cf-0449185216bc.PNG)

# Versions and configuration

 - OS: Windows 8.1
 - Game Version: 0.D-10735-gd146e46
 - Graphics version: Tiles
 - Mods loaded: 
![modlist](https://user-images.githubusercontent.com/58652206/71546250-001c1c00-29d0-11ea-8135-4c2a9bf06429.PNG)

# Additional context

Deconstructing the magically repaired frame gives a full health frame.

**Comment by kevingranade** [comment]
It looks like the problem is that with a normal part installation the part used as the base is literally copied into place inside the vehicle part, but for some reason when creating a new vehicle, it instead only stores the "kind" of vehicle part, and it inserts an entirely new instance of that type into the vehicle part as it's being constructed.

This is happening in construct::done_vehicle() in construction.cpp
