### ISSUE TITLE
Book-recipe relations are defined backwards

### ISSUE THREAD

**Issue by ymber** [CleverRaven/Cataclysm-DDA#36563]
**Is your feature request related to a problem? Please describe.**
An excessive amount of changes to recipe definitions are required to add a new book.

**Describe the solution you'd like**  
A book should define a list of recipes it contains rather than recipes defining what books contain them.

**Comment by Ker-Nes** [comment]
On the other hand, the current method makes it much easier for a mod to insert a new item recipes into already existing books, and does so without having the mods break if the recipe book in vanilla ever gets updated.

That's not an insurmountable obstacle though, but the implementation of the fix should allow for mods directly _adding_, recipes to a book, not merely copying and replacing the whole entry for the book with a version with the new recipes, so that multiple mods can add to the same book, and that if the base book is changed, that doesn't cause problems either.

**Comment by I-am-Erk** [comment]
Outlined in more detail at #37475. My bad for duplicating.
