### ISSUE TITLE
Build 10112 seems to break overmap legend. Reverting to previous build fixes issue.

### ISSUE THREAD

**Issue by gunblast** [CleverRaven/Cataclysm-DDA#36685]
This is my first bug report so forgive me if I mess up the reporting format.

# Describe the bug

Overmap legend is blank. See here: 
https://i.imgur.com/9TV4kyP.png

I suspect it's a result of change #36662, as reverting to the previous build (10111) resolves the issue.

# Steps To Reproduce

1. Set terminal width to 256 & length to 72
2. Start new world with no mods and check overmap

# Expected behavior

Overmap legend should show the name of the selected location, keybind help, etc. 
This is how it should look (from build 10111): 
https://i.imgur.com/msxqTyE.png

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-10980-g059a00b [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda]
]

**Comment by anothersimulacrum** [comment]
This appears to occur when you have non-default font settings.

**Comment by Lamandus** [comment]
can confirm, using graphic_overhaul mapfont won't make it show up.

**Comment by snipercup** [comment]
I'm using the same version of the game but I don't have the issue.
![image](https://user-images.githubusercontent.com/50166150/71766266-66d49480-2efe-11ea-809b-7e8546e77a9f.png)

OS version windows 8.1

**Comment by chriseich21** [comment]
Same problem with build 10117 but it's only when I change overmap font width to 16 instead of 8. If I leave it at 8 it displays normally.

**Comment by keanuconcepcion** [comment]
Occurs when I changed overmap font width to 16 also. I tried to use graphical_overmap. 

The sidebar is still there with graphical_overmap on -- just gets disabled when I scale the width up.

**Comment by onigamii** [comment]
Can confirm using ` Graphical Overmap ` mod with font width set to 16 makes the legend / controls disappear, it's working fine with default options.

**Comment by WeaverThree** [comment]
(Build 11030, win10/win64, fresh download stock config aside from font h/w settings)

It actually seems to happen when "Font (width|height)" != "Overmap (width|height)". You can use nondefault sizes all you want as long as they're the same. Certainly 10x20 and 20x20 work.

![cataclysm-tiles — 2020·01·05 — 10·24·50](https://user-images.githubusercontent.com/1582240/71784266-76a7b380-2fa6-11ea-9c07-1a3b9b1219ee.png)

Other oddities: If I unmaximize and remaximize the window while the map is displayed, the standard sidebar appears in the blackspace (the one with health and log and stuff).

On some combinations of window size and font size (this is 10x18 main font and 16x16 overmap font), you can see the bottom edge of the sidebar being drawn under the map, as if it's starting drawing inward from the left of the map tiles rather than the left of the screen: 
![cataclysm-tiles — 2020·01·05 — 10·37·00](https://user-images.githubusercontent.com/1582240/71784349-88d62180-2fa7-11ea-8d3d-af091e1845fa.png)

**Comment by innun** [comment]
> build 1012. linux64 tiles(but use ascii).  
I have done several tests, and found that the inequality of the value of  `font width` and `overmap font width`  may results in this issue.  
*  'font width' < 'overmap font width':  the sidebar is drawn behind the map.
*  'font width' > 'overmap font width':  the sidebar is drawn on the right but compressed.
*  'font width'' = 'overmap font width': the sidebar is drawn normally.
> forgive my poor english.

**Comment by GGgatherer** [comment]
> Other oddities: If I unmaximize and remaximize the window while the map is displayed, the standard sidebar appears in the blackspace (the one with health and log and stuff).

You don't even need to do anything with the window. Open overmap, open mission list, [Escape] from mission list, and (right part of) the sidebar will be there.

**Comment by Garfink** [comment]
Build 10152 (bug has been around for awhile now.) Windows 10, x64.

I can confirm the above problem with the overhead-map menu/labels box missing (as described about).  Totally repeatable bug:  Just adjust the overhead-map font width and height to a square 16x16 or 20x20 (probably other square fonts as well.)  Seems to occur with square fonts, didn't test with larger non-square fonts like 16x32 or something else.

As noted about ANY font at 8x16 works fine.
