### ISSUE TITLE
Saner Inventory through Unified, Nestable Containers [$255]

### ISSUE THREAD

**Issue by jjs2** [CleverRaven/Cataclysm-DDA#3671]
Change backpacks, duffel bags, etc. such that they're
1. actual "containers" (i.e. each with its own internal invlet) [even if you can still "wear" them for a slight encumbrance reduction],
2. nestable inside any container with a larger volume. [Less important than (1)!]

This will fix the gross absurdities of the inventory-letter-based item limit, and will make e.g. duffel bags useful for melee characters.

(For example, Joe the Swordsman sees zeds approaching; he drops his duffel bags full of crafting gear and skill books, and proceeds to hack and slash unencumbered.  If Joe has to retreat, then retrieving his bags makes for an interesting tactical challenge [cf. the duffel bag Rick drops in downtown Atlanta in Season 1 of "The Walking Dead"].... especially if an NPC tries to grab the gear first!)

This will also be useful if you want to sort your gear by intended purpose, for quick mission-specific load-outs.

(Currently the closest thing to this goodness is the humble shopping cart, but those don't fit into trunks very well... ;)
##

**Comment by elricsfate** [comment]
- Player opens inventory 
- Player accesses a container 
- Player stores item in container
- Player drops container 
- Items remain in dropped container 

How does player know a dropped container has items in them? 

How are containers with items and without differentiated when dropped?

**Comment by Night-Pryanik** [comment]
Color differentiation.

**Comment by elricsfate** [comment]
@Night-Pryanik 

How would the Player (Not the player character) know that by looking at it with the "x" command or by looking at the V items men? 

Additionally what happens if multiple containers of the same type (say a leather backpack) are on the same tile? 

This would need to be managed as well.

**Comment by cainiaowu** [comment]
What about a DF trading screen style? 

When selecting containers you select them all, or you can select item in the containers individually.

**Comment by Shoes01** [comment]
I have been out of the loop regarding item storage discussion, but I think creating a Project for how containers should work would be practical. Gathering established ideas, putting them in a central place, and chunking them would allow small-time contributors to chip away at the project without losing their motivation and leaving it unfinished.

**Comment by bananaedmonkey** [comment]
Perhaps the player should not micro-manage everything that is in a bag. Instead the player could designate different bags for different purposes which would not require a complex UI.

In a way, every storage container could be treated like the zones that where added recently, not a perfect solution but I think it preforms better than nothing.

**Comment by TheRealGunShy** [comment]
> 
> 
> Perhaps the player should not micro-manage everything that is in a bag. Instead the player could designate different bags for different purposes which would not require a complex UI.
> 
> In a way, every storage container could be treated like the zones that where added recently, not a perfect solution but I think it preforms better than nothing.

I second this suggestion. Container flagging for quick sorting sounds rad. Your character already auto-deposits arrows into a corresponding quiver when you pick them up. Could that be extended to an overhauled inventory structure?

**Comment by kevingranade** [comment]
To be clear, especially since this issue has such a large bounty attached, a candidate feature to enable this *must* have the following features:
* Picking up or otherwise placing items in the inventory must automatically select a target container by default.
* The capacities of individual containers must be respected, i.e. if there is no single container with sufficient capacity for a new item, the inventory is considered full.
* The default placement algorithm must include a reasonable system for approaching efficient packing of items in containers.
* There must be a UI comparable to the current inventory menu that allows players to manage their inventory contents without interacting with individual containers.
* There must be a UI that allows examining and interacting with containers, i.e. to shift items between containers in the inventory.
* Items must move along with their container, so wielding or dropping a container must move the associated items along with it. The system must also handle container destruction.
* Examining containers on the ground must allow interacting with the contained items.

Some nice-to-haves:
* Commands can prompt the player to target a particular container, or "retroactively" correct which container the item is placed in.
* A single item may contain several sub-containers (i.e. several pockets).
* Containers or sub-containers may have different access times.

**Comment by Dansiman** [comment]
> * The default placement algorithm must include a reasonable system for approaching efficient packing of items in containers.

An extremely simple algorithm that is about as efficient as possible is this:
From all containers with enough room to hold the item picked up, choose the one with the least available space.
As far as code efficiency, I speculate that a fairly good approach might be to quicksort the list of containers by their remaining unused space, from least to greatest, then iterate through the list until you reach the first one with enough space to hold the item in question. (Whether it'd be more efficient to calculate each container's free space on the fly whenever an item is picked up up (more calculation), or for each container to have a persistent "free space" property that is updated every time something is added to or removed from that container (more memory usage), is a question I'll leave to those with more experience here.)

**Comment by BBlankie** [comment]
How about an option to switch into both container catagory and item type catagory, item type catagory is your average catagory that groups what kind of item and the container catagory is where items grouped by container that stores them.

Also a filter where picked up items automatically placed on targeted container, based on item kind or multiple list of names.

And volume should be replaced with total volume and volume from container.

**Comment by Dansiman** [comment]
Just had an idea for the interface to move items between containers:
1. Display the inventory as a tree view, with items displayed immediately below the container they're in, and indented.
2. Plus and minus keys can be used to expand/collapse a container.
3. Like the Sort Armor screen, press Enter to "grab" an item and move it up/down the list. If the container into which you would be moving the item doesn't have enough room for it, color the item red.

This could also be used to unload/reload items.

A quick mock-up:
```
                                           Volume          Storage
- B [ || backpack                            2.00       4.50/10.00
  - w / || copper spear                      1.50
  -   ) 3 plastic bottles                    1.50        1.50/1.50*
    -   ~ clean water (6)                    1.50
  -   ) 2 plastic bottles                    1.00        0.00/1.00*
  + b [ canvas bag                           0.25*       0.00/1.00
  -   ) tin can                              0.25        0.25/0.25*
    -   % mashed pumpkin (fresh) (cold) (1)  0.25
+ j [ |\ jeans                               2.00        0.25/0.50
- f [ || army jacket                         3.00        1.50/3.50
  - s , hobo stove (35)                      1.50        0.18/0.25*
    -   = tinder (35)                        0.18
```
Here, the asterisk indicates a container that can only hold certain types of things - liquids in the bottles, tinder in the stove, etc., or for the canvas bag, that its volume will increase when things are added to it.

**Comment by ThomasLinkin** [comment]
2 years and this one is still staying out of the Project tab. The inventory system must be really messed up

**Comment by KorGgenT** [comment]
there was a project for it on this repo at some point, but it didn't go anywhere. i've got a personal project for it, and plan to pick this up once 0.E is in sight or released

**Comment by FeepingCreature** [comment]
Alternate proposed implementation approach, moved here to deduplicate:

**Proposed solution: Volume Assignment**

Items gain a new internal field indicating the parent container that contains them. When the parent container is moved, all nested items are also moved with it, for free, without losing their parent. (Their encumbrance is accounted for by the parent container's encumbrance.) When picking up an item that has child items in the same inventory, the child items are likewise moved for free.

**Additional notes**  

I'm calling this "volume assignment" because items are assigned to the item which provides the volume that contains them.

It would be logically cleaner to represent contained items as a list of children in the surrounding container, as has been proposed here. However, this would require all code that handles inventories to be changed. Using a parent field allows for a gradual introduction.

The ability to assign items to containers would be handy, but is not necessary for the usecase of divesting yourself of encumbrance before combat.

There is no need to represent this in the inventory UI in the initial implementation, though it could be done by a gray right-aligned text in the inventory stating the container. Indentation is less useful in the player inventory, because the containing inventories will usually be [W]orn.

When picking up items, the default sort mode should show contained items indented under their parent container, similar to Dwarf Fortress.

**Proposed implementation tasks**

Each of those tasks could be handled in a separate PR.

* add a parent container reference to items
* assign items to a parent container on pickup, respecting that container's volume limitation
* when item is dropped, drop child items as well, keeping parent assignment
* when item is picked up, pick up child items as well
* when item is destroyed, spill contained items into the surrounding inventory or the ground
* show volume assignment in the player inventory
* show volume assignment in the pickup inventory
* add menu entries to [take out]/[put into] items.

Don't forget to assert that parent items are in the same inventory as the child item!

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/mr-roboto-a-diy-robot-idea/22446/12

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/new-things-ive-noticed/23541/15
