### ISSUE TITLE
Unloading guns does not warn of approaching enemies

### ISSUE THREAD

**Issue by Grubleafeater** [CleverRaven/Cataclysm-DDA#36726]
When unloading guns, you are not warned of dangerously close enemies. This is a issue, as some guns have incredibly long unloading times, such as the Pneumatic Assault Rifle.

**Comment by l29ah** [comment]
It feels like https://github.com/CleverRaven/Cataclysm-DDA/issues/32098 is occurring again: the check is there, but it's not triggered in the majority of cases.

**Comment by l29ah** [comment]
Still an issue today, moreover: `The %s is dangerously close!` event doesn't seem to appear even if you're just `|`waiting a while.

**Comment by l29ah** [comment]
Repro: 
[2020.03.02.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4282675/2020.03.02.zip)
Load, start dissecting the corpse, ignore spotted enemy, the next message will be about you getting attacked.

**Comment by jkraybill** [comment]
There are three separate cases with 2 probably unrelated underlying causes here.

1. Unloading ammo is not an interruptible activity with an activity handler. This is the reported issue. If you (U)nload a weapon that has a long unload time like the PAR, you can get attacked multiple times without ability to stop unloading. Unloading the PAR at an inopportune time can lead to death of a fully healthy character. The fix for this is to move the code that directly subtracts player moves in unloading ammo into an activity.
2. If you start dissection (or other interruptible activities), and (i)gnore a nearby enemy ("monsters spotted!" message), you may not get warned again until the enemy is attacking you. In reproducing this, I think this may actually be working as intended, but will defer to the experts.
3. "The %s is dangerously close! event doesn't seem to appear even if you're just | waiting a while." - as reported by @l29ah above - I could not reproduce this just by waiting, I got the message reliably. However, there were cases where if I (I)gnored the initial "monster spotted! Stop waiting?", I don't get the "dangerously close" message. Again, not sure if this is intentional. This is probably the same root cause as 2 above. It does seem reasonable that (I)gnoring "monsters spotted" should not skip the "dangerously nearby" message.

If 2 and 3 above are indeed bugs, I suggest opening a new issue for them, and keeping the scope of this issue to 1 above, since they're quite separate issues.

**Comment by jkraybill** [comment]
I opened #38664 to address cases 2 & 3 above. However I'm not sure that entirely captures @l29ah's report about waiting behaviour - if t he attack can occur while waiting, without ever (i)gnoring a threat, please add some repro notes for that to #38664.

I suggest this issue be scoped back to the unloading issue.
