### ISSUE TITLE
Rebalancing armors

### ISSUE THREAD

**Issue by Ker-Nes** [CleverRaven/Cataclysm-DDA#36759]
**Is your feature request related to a problem? Please describe.**  
With the new values established as top end _standard_ (as in, not power armor, not ultra advanced prototypes, not beyond cutting edge spec ops stuff) military armor by the ballistic vest, as mentioned in the now closed issue #36682 , the rest of the game's armors need to be re-balanced to be properly consistent with these values. 

**Describe the solution you'd like**  
I feel that the ideal solution would be to rebalance how damage and protection works from the ground up, but that might be beyond what's feasible at this point. Instead, I would like to see a project to discuss and handle the alteration of the protection values of all armor in the game, specially the pre-cataclysm models (that is, not the "survivor armor" types, although those probably should get a bit of a buff too, at least to perhaps II-IIIA) as well as their encumbrance and weight. 

In addition, given that the SPCS use removable plates, it is inherently modular to a degree, specifically in that it can use similar sized plates of other materials, which should be represented much like the currently present MBR armor does, allowing one to use other types of armor plates within its pouches. 

In addition, either its use of synthetic fabric too should be considered or other items should be changed to use it. It's only currently present in it, the webbing belt and the fencing vest, despite other items also should be logically (such as a number of backpacks, specially the top end ones) and by their own descriptions (such as at least some vehicle seats) also be composed of the material.

And finally, the project should probably look into rewriting the obviously outdated armor balance guidelines document: https://github.com/CleverRaven/Cataclysm-DDA/wiki/Armor-balance

**Comment by Brian-Otten** [comment]
I had not seen the previous discussion on the ballistic vest, but buffing other armors to match the performance of it should not be done, because it's values truly are too high, and changing other armors to match it would trivialize most content.
Ballistic armor, even if it's modeled after the current top end real life models, should not be at a level where your character can shrug off high caliber gunfire, because the sheer blunt force of the bullet will still hurt you. see : https://www.ncbi.nlm.nih.gov/pubmed/11307682.
Rather than completely overhaul all armour and then also overhaul all enemy damage to keep the game interesting the ballistic armor should be brought into line to be more similar to the mbr vests present in game with ceramic plates, since those are the "cataclysm brand" version of the same product.

**Comment by Ezsk** [comment]
Obviously, current systems are unable to handle bulletproof properties. (Does we need to explanation for this?) And there is nothing problem with the existing armors except ballistic vest I think.

The problem is being in only bulletproof.

So, I suggest that the ballistic vest should be removed until new logic to handle the bulletproof mechanism has been added. There is no reason to remain imbalanced thing until a new system is created.

**Comment by tenmillimaster** [comment]
> There is no reason to remain imbalanced thing until a new system is created.

If this logic were applied to the game, there wouldn't be a game left.

**Comment by LordZanos** [comment]
Yeah, I wouldn't call having you ribs fractured and thrown on the ground when you take a 7.62 round to the chest in a level IV ballistic vest '0 damage.'

**Comment by Brian-Otten** [comment]
You are looking at the mbr vest with hardened steel plates with 40 cut protection that could perhaps even be buffed a little bit or have it's encumbrance reduced(http://cdda-trunk.chezzo.com/modularvesthard). 

the discrepancy is with the new "ballistic vest" (http://cdda-trunk.chezzo.com/ballistic_vest). 

This has 50 bash and 90 cut soak, and can soak the 52 damage 38 pierce 8x40mm, the most advanced future tech assault rifle round. it can also soak the g80 railgun, and as far as i can see in a glance, every rifle round other than .50 cal.

**Comment by LordZanos** [comment]
I'm aware of what item I was looking at, I was arguing that vests other than the ballistic vest are more accurate than the ballistic vest is, and the ballistic vest is out of line.

Not sure how someone could think a vest that reduces damage from any round in the game that isn't a 50 cal round to 0 is reaaonable.

**Comment by GGgatherer** [comment]
> Not sure how someone could think a vest that reduces damage from any round in the game that isn't a 50 cal round to 0 is reasonable.

But it only gives 85% coverage, therefore it is realistic, therefore it is perfectly fine! /s

**Comment by Ezsk** [comment]
> e: it is actually insane compared to any other piece of gear, for example army helmet - which is, btw, the best "regular" piece of military headgear you can get - which gives a whopping 15 cut protection.

Maybe someone going to add ballistic military helmet that absorb full swing of sledgehammer.

**Comment by Amoebka** [comment]
> Considering a 7.62 round deals 58 damage with 6 AP, a character wearing a ballistic vest with hardened steel plates will take 24 damage from being shot in the chest

This is not how CDDA works at all. Damage is highly randomized, depends on shooter's skills, can be critical, etc. A bullet that "does 60 damage" will consistently hit through a piece of armor with 60 cut protection even assuming 100% coverage.

**Comment by Brian-Otten** [comment]
So i wasn't sure how the enemy gun damage/crit model works compared to the player so i just went and reproduced to make sure. testing method: edit ballistic vest in json to 100% coverage and all bodyparts to test it's soaking properties. wear it. spawn any enemies you'd like to test. in my case i surrounded my character with a bunch of point blank m240 crows (these use the .308 round). I let them fire a couple thousand rounds into me. My character never takes a single point of damage to his health, and the armor remains in perfect undamaged condition. This should be reproducable pretty easily.
![image](https://user-images.githubusercontent.com/47374323/71911263-b079e500-3173-11ea-9c12-b6011d3bd019.png)

**Comment by davidpwbrown** [comment]
> So i wasn't sure how the enemy gun damage/crit model works compared to the player so i just went and reproduced to make sure. testing method: edit ballistic vest in json to 100% coverage and all bodyparts to test it's soaking properties. wear it. spawn any enemies you'd like to test. in my case i surrounded my character with a bunch of point blank m240 crows (these use the .308 round). I let them fire a couple thousand rounds into me. My character never takes a single point of damage to his health, and the armor remains in perfect undamaged condition. This should be reproducable pretty easily.
> ![image](https://user-images.githubusercontent.com/47374323/71911263-b079e500-3173-11ea-9c12-b6011d3bd019.png)
> 
> ps: Also tried quickly versus some melee enemies, completely surrounding myself in a horde of various hulks and other nasties, none of them were able to damage my character or armor with their attacks either.

Well thats certainly more protective than it should be ...

**Comment by Ker-Nes** [comment]
Just quoting the relevant tests for what the ballistic vest is supposed to be that @tenmillimaster  [mentioned](https://github.com/CleverRaven/Cataclysm-DDA/pull/36799#issuecomment-571931689) in in the conversation for #36799 

> 
> 
> https://ciehub.info/ref/TM/10-8470-209-10_2013.pdf
> https://ciehub.info/ref/TM/10-8400-205-23P.pdf
> 
> Army Scalable Plate Carrier System is capable of carrying soft ballistic inserts and hard ceramic inserts, in front, back and side plate locations.
> 
> SAPI, ESAPI, and XSAPI are available.
> 
> This is a very similar arrangement to other body armor as I understand it- more info should be able to be discerned from the armorer maintenance manual above without digging for the other relevant TM's. I believe it is safe to conclude that differences between SPCS, interceptor, IOTV, etc don't really matter except for perhaps encumbrance, as the rigs were improved to hold the armor better throughout the years.
> 
> so we can just focus on the soft armor and the hard armor components.
> 
> Soft armor, probably something like level IIIA panels, that generally the best you'll see with kevlar.
> 
> XSAPI is the most advanced, but doesn't look to be as fielded as ESAPI and SAPI are. FBI appears to be using XSAPI. http://services.prod.iaff.org/ContentFile/Get/36292
> 
> This piece suggests they're really not being issued, the XSAPI plates. https://www.strategypage.com/dls/articles/Armor-Piercing-Myths-10-9-2011.asp
> 
> ESAPI seems to be most common, and is rated for 7.62x63mm AP M2.
> 
> Requirements for testing are here, page 8: https://apps.dtic.mil/dtic/tr/fulltext/u2/a499208.pdf
> 
> Therefore: an ESAPI plate can withstand 3 M2 AP 30-06 shots before failing. After my skimming, there appears to be some more information on what condition the plate would be in when it is failing.
> 
> **To recap:**
> 
>     * SPCS is just a carrier system for kevlar combined with (E/X)SAPI inserts for Front, Back, maybe sides. It can be scaled up to include additional possible lower level protection pieces: deltoid, groin and collar protectors, to name some.
> 
>     * ESAPI appears to be most commonly issued, and needs to be specced in game to withstand 3 shots of 30-06, M2 AP. Whatever damage reduction is available will need to evaluated based on the testing guidelines (Backface deformation on the clay).
> 
>     * The material `Ceramic` needs to have chip resistance lowers such that after 3 shots of AP 30-06, the `ballistic armor` is in whatever condition is indicated in the testing guidelines.
> 
>     * At a later date, it should be added in a different PR some sort of 'always recover/drop on destroy' option for the rig. The kevlar and ceramic might get busted, but the rig should still be repairable.
> 
> 
> This is how I believe progress should be made to address the ballistic armor's perceived issues.

**Comment by FuelType-Memes** [comment]
> > So i wasn't sure how the enemy gun damage/crit model works compared to the player so i just went and reproduced to make sure. testing method: edit ballistic vest in json to 100% coverage and all bodyparts to test it's soaking properties. wear it. spawn any enemies you'd like to test. in my case i surrounded my character with a bunch of point blank m240 crows (these use the .308 round). I let them fire a couple thousand rounds into me. My character never takes a single point of damage to his health, and the armor remains in perfect undamaged condition. This should be reproducable pretty easily.

> > ps: Also tried quickly versus some melee enemies, completely surrounding myself in a horde of various hulks and other nasties, none of them were able to damage my character or armor with their attacks either.
> 
> Well thats certainly more protective than it should be ...

Cut protection is fine, it needs to degrade faster and convert some part of cut damage into bash on hit. As for hulks and such it should give lower bash protection

**Comment by Ker-Nes** [comment]
With what I quoted in mind, if we could drop the "STURDY" flag for the vest, and put the armor resistance just about to remove most but not all damage from the closest equivalent to 7.62x63mm AP M2 and similar rounds currently in the game (damage doesn't mean necessarily penetration. I'd interpret small amounts of damage here as bruising, which could be further handled with other pieces of armors in inner layers to represent padding and the like). Even if it doesn't handle the exact number of shots (that's probably better going to take a reworking of how damage and armor works, as well as allowing component parts of clothing to get seriously damaged while the clothing is only lightly so).

Bashing resistance absolutely need to be reduced a _lot_ though, as even with attacks that aren't strong enough to crack the plates can be be able to transfer enough energy through it, even after the slight spreading of the energy over a larger surface area (and not that great surface area compared to proper rigid armor such as a plate cuirass), there's likely to be enough energy 



> Cut protection is mostly fine, it needs to degrade faster and convert some part of cut damage into bash on hit. As for hulks and such it should give lower bash protection

Until damage is reworked, I feel that the best we can do is to make so that it doesn't stop all damage: Enough to represent no penetration, but allowing just a bit to pass through to represent bruising.

**Comment by Brian-Otten** [comment]
Since we are keeping armor balance open as a subject i'm going to throw my suggestions on some armors out there.
I will be using the armor balance guideline since it is actually a really well thought out guideline (https://github.com/CleverRaven/Cataclysm-DDA/wiki/Armor-balance)

The MBR vests are honestly in a weird place, probably being underpowered. The variation in encumbrance feels like it's way too far apart (10-40 encumbrance. why is a vest with some steel plates 4x as encumbering as the platemail armor?).
 
They should probably receive a balance pass so they have top of the line simple values, while keeping encumbrance in the 10-25 range. They would still not be overpowered because 85% coverage and torso coverage only will always keep them from greatness.

Kevlar plates and ceramic plates should probably have the highest simple values, while the steel/ hard steel plates are a bit easier to get, have higher bash protection, and higher encumbrance.

I'm just going to toss some values out there as a suggestion:
MBR (empty): Keep as is. This is a kevlar vest, but "outer", for 2 more encumbrance and it has magazine slots. this seems fine.
MBR(kevlar plates): Up thickness so cut protection is 30 and bash is 20. keep the rest the same. New simple value = 1.35
MBR(ceramic plates): adjust thickness so bash is 15, cut is 40. ish. reduce encumbrance to 12. new simple value = 1.18
MBR(steel plates): reduce encumbrance to 20. increase thickness so soaks are 30 bash, 35 cut (ish) new simple value =0.88
MBR(hard plates): reduce encumbrance to 25. increase thickness so soaks are 35 bash, 50 cut (ish)
new simple value = 0.94

This leaves a slot open for where the ballistic vest is now, which is top tier special forces NJI4 rated body armor. It should basically be an upgraded version of the mbr(ceramic plates), and be found on zombie bio operators and in military bases. it should probably have around 55 cut protection, due to thickness of ceramic plates. it will stop .223, but .308 will still damage the armor and the player some.

**Comment by Brian-Otten** [comment]
If we are talking realism, NJI classifications allow 44 mm of backblast deformation. that's past bruising and into internal damage. IMO a good guideline is that the armors should have about 15-20 less cut protection than their highest rated bullet. that simulates the internal damage from concussive force and will allow the armor to get damaged when shot. That should hold us over until someone rewrites the games damage model.

**Comment by Ezsk** [comment]
Probably most people will agree the ballistic vests prevent rifle ammunition such as 30-06. I think we have a already good enough documentation for this discussion.

There are several other issues.
+ Material that won't be damaged by 1000 bullets.
+ Reduces the damage of unprotectable bullets like a 50cal.
+ Reduces melee combat damage too much.
+ Small value of encumbrance causes Inconsistent with other armors.
+ Consistency with existing MBR vests. Or integration.

> if we could drop the "STURDY" flag for the vest

I agree drop the "STUDY" flag for the one of quick fix. it will good enough for balancing the game except when the ballistic vest make tweaked to repairable as easily.

> why is a vest with some steel plates 4x as encumbering as the platemail armor?

I can imagine that it's simply heavy. The cuirass is half of weight than ballistic vest. See other armor for reference, the encumbrance and weight are almost proportional.

**Comment by Brian-Otten** [comment]
Since i was nerding out about the armors anyways, here's some of the others which i spotted that should almost certainly receive buffs so simple value is somewhere between 0.5 and 1:
Swat armor
ANBC suit
AEP suit

I couldn't really spot many others that were out of place, which is a testament to how good armor balance already is, so props to everyone that worked hard at those.

**Comment by Brian-Otten** [comment]
Opened a PR:https://github.com/CleverRaven/Cataclysm-DDA/pull/36853
Should buff some of the pre cataclysm armors to somewhat match both IRL performance and sit about where they should according to armor balance document guidelines.

**Comment by Brian-Otten** [comment]
Opened two more PR's for the riot armor and the dragon skin vest. 
I've run out of ideas for armor that is currently not where it should be balance wise. Anyone still able to spot any?

**Comment by Ezsk** [comment]
> Opened a PR:#36853
> Should buff some of the pre cataclysm armors to somewhat match both IRL performance and sit about where they should according to armor balance document guidelines.

PR that is kept to a minimum is worthy of evaluation. We needed to separating the problem. Thank you for your work.

**Comment by Brian-Otten** [comment]
When #36853 is merged or closed we could probably close this issue for now. I made a couple of PR's that balanced the edge cases of armor that needed some help, and am unable to find any that need balancing myself now.
If anyone knows of armor that still needs a pass you can make a PR or message me and i'll have a go. but i think we are close to done (until armor is more fully reworked.)

**Comment by esabaliauskas** [comment]
Hello, and sorry for my intrusion, may I offer a simpler alternative?

That would just be a bulletproof  tag, that makes bullets deal only their bash damage against the targeted item. So that would simulate higher caliber bashing damage done to the wearer. 

It could also apply a flat piercing damage reduction of value that would make all bullets up until a certain point a minor thread just like in this example

> it will stop .223, but .308 will still damage the armor and the player some.

I think that this is a good suggestion because it will not make a bulletproof vest that is also mele-zombie-proof.

And yes this would require to add a bit of bash damage for every bullet, what do you think about this compromise (proposal)?
