### ISSUE TITLE
Monster mutations

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#36850]
**Is your feature request related to a problem? Please describe.**  
Our lore describes an infinitely mutable power that transforms everything it touches, yet our monsters and zombies mutate in extremely predictable ways.

**Describe the solution you'd like**  
The current static evolution lines should be augmented by allowing monsters to get random Mutations. In order to evolve to a new type, a given creature would have to pick up the prerequisite mutations first, randomly. The evolution type would then mostly be to change its appearance.

Mutations could be used for major things - like giving zombies acid blood as a prereq to becoming acid zombies - or for minor things, like making one zombie slightly faster or weaker than the average.

In general I think monster mutations would be handled exactly like player mutations. We'd have to jsonize them as much as possible to allow a wide variance. We'd want the ability to add overlays for specific mutations, although for zombies at least the mutations should be kept small, with the evolution lines being the big sprite-changing things. Otherwise, zombie variants won't work.

This system would also be very useful for adding variability to other monster types: for example, mutant insects and lab experiments. For the latter I see it as critically important.

**Describe alternatives you've considered**  
We could have some variation in monster types expressed just by allowing attributes to fall within a range rather than being set. Instead of 80 HP, a zombie might have [70-90] HP. Instead of 100 speed, it might have [90-110]. This would accomplish the goal of making it less predictable if you're going to be able to outrun them, but it wouldn't allow a regular zombie to start getting a bit of acid blood before turning into an acid spitter, and it wouldn't make it more accessible to create a dozen variable lab mutants.

**Comment by Amoebka** [comment]
Random stats effectively blend zombie types together and remove any semblance of clarity for the player. Tough zombies are known to have more hp that plain ones, and feral runners run faster. But if stats are random, sometimes tough zombies aren't tough and feral runners aren't fast. This makes names and graphics irrelevant and makes it impossible for players to properly estimate risks. Sometimes you can have too much randomness, and this feels like one of those cases. Plus, number changes are boring.

Non-number mutations sound a lot more fun and interesting, but they too should be communicated properly. Zombies with acid blood should drip it, electrified zombies sparkle, etc.

**Comment by I-am-Erk** [comment]
A range of stats doesn't mean all zombies sample from the same range. If a mon_zombie has an HP range of [ 70,90 ] and a mon_zombie_tough has an HP range of [ 90-110 ], the tough zombies are still tougher. They just don't organize into discrete groups where you can accurately predict exactly how many hits it will take to bring that zombie down, or exactly how fast you need to be to outrun them.

I disagree that every change needs to be communicated visually. Zombies with acid blood should only leak acid blood if injured, for example, and there's no way to tell from looking at a zombie if it has evolved a weaker version of the screecher alarm. The main thing is that out-of-type mutations should be kept pretty mild, enough to make zombies not predictable but not enough to make them dramatically more difficult.

**Comment by Brian-Otten** [comment]
I'll agree with Amoebka here and say that being able to estimate enemy stats so you can play to their weakness lies at the very core of CDDA gameplay, so you'd have to be very careful with any randomness that is introduced. A fun middle ground might be having a couple zombies ingame with this property, along with stuff like lab mutants and maybe a nether creature or two. These would be both relatively strong and rare and function much like "elites" in other roguelikes. Some of their new mutations would be visible while others wouldn't. but since they don't come in large groups it makes you pause your gameplay for a second while you figure out how to approach the situation.

**Comment by CoroNaut** [comment]
I believe this is a fantastic idea. Introducing the random element should've been there from the beginning as I see it. Who says all tough zombies would be exactly the same? Some body-builder turning into a tough zombie and his friend that could lift a little more are different, so when they turn, they shouldn't just morph into general tough zombie. 
I don't think these mutations should classify enemies as unique in any way however, I would prefer all zombies to have these stat ranges applied. This will keep things interesting while teaching the player a more safe-approach driven game play style. I pretty much go to town on any zombie I see at about mid-game because everything is predictable as said.

**Comment by kuhnchris** [comment]
Maybe this would work as a seleactable mod - not sure how far the capabilities of the mods range right now - but you could leave the vanilla experience as-is and (incase we can only modify json files) add some property as mod that could affect those changes (e.a. base hp is 100, if you add mod 'randomize monster stats' it adds json parameter: hp_randomness: 10 and the modified base-code will only adapt the HP when this json parameter is available))

it's true that we'd lose some vanilla quality-of-life, but to be honest, life's bad. very bad. post-apocalytical bad. if you go up to someone on the street and punch him in the face you also do not know if he's actually buff, works out and going to woop your butt. same here. just because a zombie is a zombie you can't really tell what's happening on the inside. same with animals - some are friendly, some bite your hands off.

Adding this would really add a touch of "reality" to it - for the cost of throwing new and uncautionous players off for not clearly identifiying the Zeds. But that's why I suggest it as mod - new players can use it without the added realism, seasoned players will play differently anyways.

... just my .02 $

**Comment by Fris0uman** [comment]
> Maybe this would work as a seleactable mod 

Plz no.
When we add new stuff we should just make it work and not add another "reverse that" mod. Or we'll end up dragging hundreds of those mod behind us for no good reason.

This is a pretty great idea, could also go well with adding more regular animals and have them mutate through the course of a game.

**Comment by Night-Pryanik** [comment]
No discussion in more than a year, closing.
