### ISSUE TITLE
Blindness should probably debuff dodge and tohit.

### ISSUE THREAD

**Issue by Brian-Otten** [CleverRaven/Cataclysm-DDA#36909]
**Is your feature request related to a problem? Please describe.**  
Being blind does not decrease your tohit or dodge, you can still fight in melee at full effectiveness. tab will even still autotarget the enemies around you.

**Describe the solution you'd like**  
Being blind penalizes your dodge and tohit a meaningful amount (perhaps unless you have some alternative form of perception from mutations/cbm?)
**Describe alternatives you've considered**  
Blindness keeps only affecting vision while retaining combat functionality.
Keep combat ability but remove ability to use tab to autoattack enemies you cannot see.
Nerf combat ability and remove autoattack on unseen enemies.

**Additional context**  
Risks making the flaming eye blindness attack more deadly than it already is. Maybe have a look at that if this happens?

**Comment by 1n17** [comment]
IIRC there is currently no distinction between blindness (as caused by eg. blindfold, flashbang and flaming eye) and 'tearing eyes' (from eg. getting hit in eyes), other than 'boomered vision' mode. 
While the first should severely cripple, the latter is at most annoyance (as far as melee is concerned) warranting perhaps losing a dodge or two, and only if encircled at that (to model loss of peripheral vision and impaired depth perception).

**Comment by Brian-Otten** [comment]
Sounds good to me, would be good if we can distinguish between those.
