### ISSUE TITLE
Dragon skin should be replaced

### ISSUE THREAD

**Issue by Brian-Otten** [CleverRaven/Cataclysm-DDA#36901]
**Is your feature request related to a problem? Please describe.**  
Dragon skin armor is outdated armor that has been discontinued for 13 years now. It doesn't really fit in the game as is, and with all the controversy around it  is hard to balance properly.  
**Describe the solution you'd like**  
It should probably be removed and the item migrated into the mbr(ceramic plates), or the ballistic vest. (or a different suitable torso armor if you can think of one).
**Additional context**  
This item was most recently in discussed in #36861 where the suggestion was to go for this option.
I don't know how to do this myself correctly as of right now, if i learn and come back to do this i'll post first to say i'm working on it. If anyone else can can get it done feel free.

**Comment by CoroNaut** [comment]
There may not be any argument for keeping it around, but why not rebalance it and just leave it at that? It's not as though I'm for the armor or anything, but seems like this is just making more work for something simple. The game is not meant to be super realistic, so I'd believe stats can just be lowered to what you suggested, we see so many sci-fi elements in the game that it doesn't really warrant removing the armor for realism. Personally, I just say leave it in for flavor and just that little bit more variety.

**Comment by Ulysses2** [comment]
There has actually been a big push for super realism as of late, so all the unrealistic elements that aren't condoned by extradimensional magic have got to go.

**Comment by Brian-Otten** [comment]
My PR that was closed was to rebalance it to around its real world values, and it was decided that we probably shouldn't go that route because the real world stats are a bit questionable, it probably would go unused with its real stats, and its place in the game world is iffy at best. I might see if i can find a spot later for a civilian body armor between kevlar vest and the mbr with plates, but with how militarized cataclysm US was the mbr itself has already kind of snuck into that spot.

**Comment by CoroNaut** [comment]
Just want to make it clear that I'm not advocating for the vest. For a bit of clarification for what I was trying to say, the armor existed at some point, it would just be rare because its out of production, and was mainly a prototype as you've found. 

When I said the game was not meant to be super realistic, I refer to the widespread mutations, the apocalypse, extra-dimensional creatures, artifacts, and lore that suggests as such, all of which are main aspects of the game and are fiction. I personally haven't seen many comments for super realism, it's always been that cdda is set in futuristic New England. I can see the rationale for realism being that we are advancing technology very rapidly in the real world and therefore CBMs, underground labs, and numerous civilian-facing AI are all starting to seem closer to reality. This wasn't the case when the game was in its first stages.

If we are saying there is a big push for super realism, I believe the armor should be removed. The dragon skin was created far from New England (in california) and distribution was kept within US defense as a prototype and classified as too unreliable to mass produce. Therefore it couldn't really make its way to cdda's setting, and would probably be unique if found.

**Comment by anothersimulacrum** [comment]
Ah okay, that clears up my confusion about your comment. Game's not been set in future New England for a bit, may want to read up on the [design doc](https://cataclysmdda.org/design-doc/).

**Comment by Ezsk** [comment]
May be the dragon skin armor was handmade by military nerd! So it has unrealistic performance and need to be found in underground workshop only.

I love the joke in cataclysm like so.

**Comment by Ker-Nes** [comment]
> May be the dragon skin armor was handmade by military nerd! So it has unrealistic performance and need to be found in underground workshop only.
> 
> I love the joke in cataclysm like so.

That actually can make some sense. Let's say the more negative tests results about it are true, make it underpowered compared to other military-grade armor, and make it only possible to find in the equivalent of museums, collector's houses and the rare military surplus store as a collectible more than actual armor.

**Comment by CoroNaut** [comment]
I've read what it says in the design doc and I see under "World" 

> The primary setting of the game is present-day (2019 as of the time of writing) Earth. The current setting is New England in the United States, but that is not a core value, and there is interest in expanding the game to other regions.

Is there another portion of the document I'm missing? I wasn't able to find anything more, I must assume "other regions" just means general US? They mention about emulating other games too, which I like a lot. There will be much more potential to get the best of all the worlds.

As for technology, I see 
> Technology in Cataclysm should, except in specific situations, be at a modern real life level

> The military at large has access to technology that far exceeds civilian capacity

This is cool to see that it's changed. There has been much hand waving as to what the technology level has been for a long time here. Doc states civilians are modern real life tech, but military far exceeds that. The military wouldn't keep something as bad as dragon skin to begin with. :D

As for the armor, I like the idea of keeping it as a collectors item or in museums as Ker-Nes said. Since cdda is expanding its setting to get past New England, this idea is plausible.

**Comment by anothersimulacrum** [comment]
> Is there another portion of the document I'm missing?

Not that I know of.
