### ISSUE TITLE
New car part: tow hitch

### ISSUE THREAD

**Issue by illi-kun** [CleverRaven/Cataclysm-DDA#3699]
Using this feature, you will be able to create a few different trailers and choose one for your current task, or even create your own road trail. I think the special behavior of the tow hitch joint is also required: it should be pinned, and allows the rotation of the trailer (I really hope I described the main idea properly).

Upd:
Step 1: Basic process of towing;
Step 2: Realistic behavior of towed vehicles;
Step 3: Variety of towing mechanisms, destructions due to overloading;

related to #992.

**Comment by Shadefang** [comment]
Couldn't you have it not turn? have it moved over, and the rotation gradually applied as the towing vehicle goes forward?

**Comment by Cat09** [comment]
would vehicles being calculated inside their own co-ordinate planes, then translated to the main co-ords allow more fluid behaviour?

**Comment by DavidKeaton** [comment]
the problem still lies with proper translation and collision tostinh

**Comment by scorpion451** [comment]
`<necropost>`Thread, rise from your grave! `</necropost>`

With the recent work done toward defining the center of rotation on a vehicle by its actual physics, is there any chance we could see a revisit on this idea at some point in the near future? 

With regard to the wrecking ball thing, having worked in a salvage yard I'd call that a "feature" more than a "bug":

winch truck + guy with lead foot + 80's sedan = the week I got tasked with clearing glass and scrap metal off the roads in the lower section of the yard.

We lost a lot of good headlights, grills, radiators, and bumpers that day.

**Comment by Coolthulhu** [comment]
Different center of rotation isn't even close to "enough".
We'd need:
* The ability to push/pull vehicle at a particular point rather than just the center. Moving the center won't help here - the rotation part of the movement would be lost
* Splitting vehicle's facing from momentum (preferably turning both into proper vectors)
* If we want the rotations to look nicely, we'd need TWO momentum vectors (front and back)
* Some way of preventing collisions of the towed vehicle with the towing vehicle at semi-sharp turns
* Proper math for splitting the forces between vehicles. Math that takes angles and masses into account and doesn't break apart when one of the vehicles brakes hard.

**Comment by illi-kun** [comment]
This is well known features request which requires significant amount of changes. I think there is no need to keep this issue open.

**Comment by Leland** [comment]
FYI @illi-kun's old PR they referenced is here: https://github.com/CleverRaven/Cataclysm-DDA/pull/4403
