### ISSUE TITLE
Driving and focus

### ISSUE THREAD

**Issue by 1n17** [CleverRaven/Cataclysm-DDA#37070]
# Describe the bug
Driving a vehicle drains focus pool unreasonably quickly.
# Steps To Reproduce
hop into a car with 100 focus and start driving
put on some music for good measure
observe focus pool plummet within minutes

# Expected behavior
Neurotypical human should find activity like driving quite relaxing, especially considering how devoid of traffic the roads became after the caataclysm.

# Versions and configuration
any recent

# Additional context
I'm guessing its the driving skill practice calls.

**Comment by 8street** [comment]
You can turn off driving skill practice. This will not waste your focus and your driving will be relaxing.

**Comment by 1n17** [comment]
That's a nice workaround/crutch, but not a solution to the underlying issue.

**Comment by communistkiro** [comment]
The issue that driving is an almost useless skill in a game where you can get reasonably fast anywhere on foot, let alone bike. Why is it a skill too? Handling a tank at 200kmph on flat road is easy-ish, even at low skill, and to negate emergency brake not working and you going sideways (into something) one can just slow to down to negative -200 from +300 so few turns i'm scared of the survivors cranial solids becoming soup-like, acceleration-based effect a la DOWNED should be extended to stopping/crashing, i.e., rapid acceleration change. imo just.

**Comment by RobertoVGoulart** [comment]
Driving is currently a useless skill because of how little difference it currently makes.
Driving a tank shouldn't be easy, especially because it doesn't use wheels, it has much different controls and you have more stuff to control besides driving (turrets, cameras...).
The driving skill needs a rebalance, but i believe thats outside of the topic of how it currently drains your focus much faster than it should.

**Comment by kld87** [comment]
+1 (since this is getting marked as stale)
I'm relatively new to the game and was really confused why my focus was always so low until I figured out it was due to driving, which wasn't at all intuitive to me. I'm using the "workaround" mentioned above of disabling it during the skills menu now, but I think it warrants investigation/rebalancing.

**Comment by FeepingCreature** [comment]
Seconding. It's extremely silly. Do we have some sort of driving-related phobia? 30 minutes of driving should not leave one exhausted for hours.

**Comment by kevingranade** [comment]
Practice is triggered here: https://github.com/CleverRaven/Cataclysm-DDA/blob/687b6862891dfe079ed517a5a3dda666d1f2d242/src/player.cpp#L691-L707
This looks like especially with a large vehicle being driven fast it can fire multiple ticks of practice per turn (though it's throttled to activating one turn out of 8).  This could easily be throttled to a maximum of one point of practice at a time, and potentially scaled by the available focus level.

**Comment by kevingranade** [comment]
The main thing this needs is an acceptance test for what "good" focus drain while driving is.
A probably acceptable quick fix would be to just throttle it by an additional amount, say to one practice event a minute, then verify that on a reasonably morale-buffed character (call it +50) focus still drains at some rate, no net focus drain is too far.
