### ISSUE TITLE
Wildfires as a means to a less static environment and new hazard

### ISSUE THREAD

**Issue by Stuntaneous** [CleverRaven/Cataclysm-DDA#3707]
This comes inspired from the last day of bushfires over my way. How about some wildfires? They'd spruce up nature, especially for those who enjoy camping it up in the sticks, and possibly encroach on the urban environment from time to time which would affect our camping comfort zones (as is the primary motivation for adding migrating zombie hordes). They would also present an opportunity to engage in back-burning. 

A couple of photos from these recent bushfires (mostly skimmed from /r/australia + sydney) http://imgur.com/a/MT1IS

These capture the colour and atmosphere better http://imgur.com/a/z40Z3

Some characteristics for those not in the know include the smell of smoke in the air, a vibrant and surreal yellow or orange glow permeating clouds of smoke in the sky and the accompanying colour cast below, and spectacular sunsets of blood red and beyond. They tend to show up numerous, scattered, and uncontrollable on windy days of high temperatures (e.g. mid to late 30s celsius and above) when vegetation is dry. When severe, firefighters are often just waiting for a change in conditions to make the fires more manageable. 

If they were intended to be put into the game, I imagine there would be issues regarding the 'reality bubble', the regeneration of vegetation (also note: bushfires are known to be a natural and generally helpful part of the bush lifecycle), and interaction with current weather. Consideration of the introduction of wind may be very useful or necessary, too.

A fun fact to finish up. At the same time, it was hailing in Melbourne, the city of 'four seasons in one day'.

**Comment by mugling** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
