### ISSUE TITLE
Using wire instead of car springs in small-scale recipes

### ISSUE THREAD

**Issue by randomtyper** [CleverRaven/Cataclysm-DDA#37211]
**Is your feature request related to a problem? Please describe.**  
There is only one type of springs in game, Specifically - car spring, that is used in many recipes that IRL should use small springs. For example, nail rifle mag, that has volume of 250 ml and weight of 60 g, needs you to file down (without using a file) a 3 kg and 750 ml spring. Sounds absurd and stupid, isn't it?

**Describe the solution you'd like**  
Changing car springs in small-scale recipes to wire (quickest and easiest solution).

**Describe alternatives you've considered**  
Adding in a new item - small spring, that can be crafted using a wire as material and electric drill and rebar as tools (there may be better variants) - would be hard for me.
Continue to cram car springs into magazines and weapons.

**Additional context**  
I made this issue to figure out what variant of solving this problem is better and how I can improve the final solution without making a PR with a lot of edits (and redundant work), so feel free to comment.
https://www.instructables.com/id/Make-your-own-springs-in-seconds/ - making springs at home from wire using a drill and a steel rod.
About wire: how long is one length of it in-game? This may be needed for calculation.

**Comment by Kilvoctu** [comment]
I think it makes sense and realistic to prepare the small spring component first, than to put wire in one's end product and imagine it's small spring. It could be confusing for some recipes as to why wire is needed.
Also small spring could eventually be added as materials gained from disassembly, rather than wire.

**Comment by Ker-Nes** [comment]
Supporting the addition of a small spring item. While laborious, it shouldn't be hard, just requiring to go through all recipes that currently the car spring item and check if they should use a small spring instead, altering as needed. Maybe we make a collaborative fork to do that if it turns out that there are too many recipes? 

Rebar is probably unnecessary though. A small spring probably can be coiled even around the drill itself, depending how small we assume they are, and if we assume they are a bit bigger, a pipe, broom (for the handle) or the similar should be a good enough replacement, as it's not quite that much strength needed to bend the wire into a spring. Maybe copying the chainmail link recipe? 

Most annoying part is probably populating the loot lists, and to decide where they should appear.

**Comment by 1n17** [comment]
Springs require heat treatment to actually store energy and not deform, even assuming random wire has sufficient carbon content (mild steel doesn't).

**Comment by TechyBen** [comment]
They'd end up more slinky than spring. But yes, springs from washing machines (medium sized IRL) and VCRs (small sized IRL) are common. Though VCRs are now defunct. The guitars, heaters, etc could have small springs (though are these too wobbly/soft?) when disassembled.

Could add small springs as a possible drop to computers/terminals being dismantled. They are common in sprung doors/panels or CD players. Possibly ovens too, for the sprung door (should be smaller than the washing machine spring).

Currently, the springs from car seats would also be around medium sized. With only car suspension coil springs being the common source for large springs.

**Comment by 1n17** [comment]
Thing about springs is you never get the right size from disassembly. Making your own is the right solution when trying to improve realism in this regard, but thinking that random wire wound on a dowel makes a spring is arguably going in the opposite direction (at lest with car spring you can rationalize it was a close enough and you cut it to size, as long as you're willing to ignore size/weight)

IMO sensible option(s*) would be
- wherever there is need for high performance spring (eg. gun magazines), proper materials and heat treatment (forging) requirements should be included in the recipe requirement
- have spring be smaller, still quite abstract item - ie. spring (10-20) for every one spring now
 ###### *since both could be implemented for synergistic effect

**Comment by AH1684** [comment]
If you've an appropriate wire material (e.g. piano wire), all you need is the dowel rod (maybe a power input depending on the size, e.g. drill or lathe), pliers, and wire cutters can create small and medium springs. Heat treatment isn't necessary in all cases.
High strength wires could be looted from appropriate sources, providing another loot source for springs. Though adding a new material class may not be desirable.

**Comment by AH1684** [comment]
Alrighty, now with some free time amidst, I can work on this as a first contribution! One that has also bugged me when playing the game.
**Current Proposed solution:**
Creating a small spring would require the following:
Tools:
A tool with drilling 3 - a cordless drill
A heavy stick - to turn the spring wire on
Pliers - To form the wire.
Materials:
1x Wire
Output: 
10x Small Springs

**Possible Alternatives**
1. Introducing the "turning" tool quality. Though this may be out of the scope of this issue, moving forward with lathe-like tools is important for a crafting reform.
2. Requiring a machinists' handbook - Something I feel unnecessary in the current 0.E version, but also may be considered after crafting reforms.
3. Requiring wire cutting quality and tool - Small wire cutters to work with smaller projects. I felt requiring metal cutting or bolt cutters was egregious, but not requiring some sort of wire cutting feels off.

**Rejected Alternatives**
1. While it is true quality springs are made out of high strength steel alloys, springs have sufficient freedom to be designed around lower quality steels. In the case of the apocalypse, designing a working, though not ideal, spring is fine in the bulk of scenarios.
Thus I feel requiring forging/quenching equipment isn't necessary for springs.
A short design case study can be written up to showcase this point.

LMK whether this works or not as an implementation! Happy to take feedback!
