### ISSUE TITLE
Overrun scenario having trouble spawning

### ISSUE THREAD

**Issue by curstwist** [CleverRaven/Cataclysm-DDA#37288]
# Describe the bug

Military base scenario, overrun, is having trouble spawning on default settings map.
# Steps To Reproduce
1. create a debug world
2. try the scenario start, overrun.

# Expected behavior
it spawns easily.

# Screenshots

![image](https://user-images.githubusercontent.com/39442864/72848128-eccc3b80-3c71-11ea-8157-4e35a2e8e279.png)

# Versions and configuration
win10, vanilla world.

**Comment by RarkGrames** [comment]
I have now the same thing on generation. Most of the generated worlds can't spawn the location. I removed the `unique` flag, added `occurrence: [ 0, 1 ]`, and that made it work ten out of ten times. I never worked with the `unique` flag, so I have no idea what can be tweaked to make it spawn properly.

**Comment by curstwist** [comment]
Cool, glad you found a setting that works for fields.

**Comment by ralreegorganon** [comment]
> I removed the unique flag, added occurrence: [ 0, 1 ], and that made it work ten out of ten times. I never worked with the unique flag, so I have no idea what can be tweaked to make it spawn properly.

Basically because the unique flag makes the occurrence a % chance to spawn the given special as a mandatory special, the current configuration for the special was making it so that it had a 10% chance per overmap of being spawned. Once it's rolled a success there, it's still got to meet all of the other criteria in order to actually place (e.g. appropriate terrain, distance from city, etc).

When the game starts and tries to place you in a location, it'll generate overmaps out to a radius of 3 from your starting overmap when trying to find the location, and so for each overmap it'd be doing this roll (10% chance) and then trying to find a valid placement.

About the only thing you could tweak about the unique flag would be to increase the chances that it picks it to spawn at all.

**Comment by RarkGrames** [comment]
So basically this means that as long as it uses the unique flag, there will be failed generation cases. I guess this makes it a no-go for this location.

**Comment by RarkGrames** [comment]
Thanks for the clarification. Then it seems a more overarching solution is needed for cases like these (rare locations needing guaranteed spawns).
