### ISSUE TITLE
Game crashes after unloading bike raack

### ISSUE THREAD

**Issue by BrassRobo** [CleverRaven/Cataclysm-DDA#37304]
# Describe the bug

The game crashes when unloading a bike rack if you've modified the vehicle on the rack.

# Steps To Reproduce

1. Build a small vehicle with bike racks.
2. Build a second vehicle right next to it.
3. Load the second vehicle on to the first.
4. Add more frames to the loaded vehicle

# Expected behavior

The vehicle unloads successfully.

# Screenshots

![image](https://user-images.githubusercontent.com/8415614/72920310-05426180-3d17-11ea-8679-e6519b4e0961.png)

# Versions and configuration

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4099015/debug.log)

# Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4099020/crash.log)

[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4099021/save.zip)

**Comment by jeremyshannon** [comment]
I had this happen. My bike had wheel mounts automatically added (by the wheel update) which didn't have a "carry:" tag -- so they're part of the base vehicle instead of the mounted bike. There was also a seatbelt which somehow lacked the "carry" tag, it may have been damaged and replaced? Removing the affected parts allowed the bike to be unloaded without crashing the system.
 I imagine it's trying to remove the "carry" parts, and it ends up with free-floating parts hanging off the side of the vehicle in an impossible way.

**Comment by jeremyshannon** [comment]
Oh yeah, savegame surgery to add the "carry" flag to the affected parts solved the crashing issue, too. The "Death Machine" can now be racked and unracked with no trouble.

**Comment by jeremyshannon** [comment]
Fixed by #38767
