### ISSUE TITLE
Remove drugs from the "E"at menu.

### ISSUE THREAD

**Issue by RobertoVGoulart** [CleverRaven/Cataclysm-DDA#37323]
**Is your feature request related to a problem? Please describe.**  
The current Food/Drinks menu is already cluttered enough if you hoard most of what you find, we don't need drugs on the same menu when they can be used with the "a"pply menu.
Also, it's not fun to accidentally use crack when you're trying to drink some water.

**Describe the solution you'd like**  
Remove Drugs listing from the "E"at menu.

**Describe alternatives you've considered**  
Leave it as is.
Ask for a rework for the whole Eat UI.

**Additional context**

**Comment by curstwist** [comment]
I like them in E because you don't have to keep re-selecting the bandages to use them, it will automatically set itself on that line to reuse them.

There is a unbound alternative you can look into, I'm sorry I can't remember its name off hand, but it breaks out food, liquids & meds when you hit E, so you can choose which group to display.

see: https://github.com/CleverRaven/Cataclysm-DDA/pull/30286

**Comment by anothersimulacrum** [comment]
See #35350 for context on why this has been rejected in the past.

**Comment by RobertoVGoulart** [comment]
I didn't knew that there was an unbound alternative menu that basically solves the problem that sparked my suggestion and wasn't able to find that old discussion about the topic before opening this one.

Now i think this issue is irrelevant to keep open.
