### ISSUE TITLE
Game difficulty when using guns

### ISSUE THREAD

**Issue by Brian-Otten** [CleverRaven/Cataclysm-DDA#37496]
# Is your feature request related to a problem? Please describe.
Currently many of the game is still balanced/designed around the old stamina system, where most survivors would use melee for the entire game. With the new stamina system, and ammo being more available, guns are more used than ever before by our survivors (which is probably a good thing).

# Describe the solution you'd like
Endgame locations/gameplay should be balanced to be challenging/interesting for players with guns.

# Describe alternatives you've considered
Rework item drops to make ammo artificially scarce and not something you expect the player to have.

# Additional context
This is a very open ended issue intended to provoke some discussions/thought, but i think it's something that will probably need some thought when designing new areas and reworking old ones.
I would like to highlight the new 1 floor lab as a location that feels like a nice amount of challenge for a gun using survivor, with tense indoor combat with a large amount of varied enemies.

**Comment by GennFaol** [comment]
I doubt making ammo more scarce is gonna be a thing, considering there is talk of making MORE ammo spawn in gun stores since those don't spawn nearly enough.

**Comment by Brian-Otten** [comment]
I much prefer the world having realistic amounts of ammo myself, and for owning/using guns to be the expected route for the player to take in the mid/endgame.

**Comment by GennFaol** [comment]
Do you have any thoughts on how to make endgame locations more challenging, as compared to how they are now? I mean, a lot of the difficulty also depends on how you set both the spawn rate of enemies as well as the rate at which they evolve.

**Comment by Brian-Otten** [comment]
A couple different approaches to design difficulty using current ingame functions:

1: Amount of enemies is so large that carrying/reloading enough ammo becomes a serious concern (current towns)
2: Enemies that have enough armor to force an alternative approach. (kevlar hulks / skeletal juggernauts)
3: Zombies with threatening special attacks (acid spitter/ technician magnet pull/ predator leap)
4: Enemies with ranged attacks (currently almost solely robots/turrets with guns)
5: Enemies that cause environmental hazards (smokers/acid currently)

Locations that are intended to be challenging should probably have 2-3 of those. Zombie evolution tends to help some of the current areas reach those levels, but with how much of the gameplay often occurs in the first 1-3 months it doesn't quite do enough to keep the game challenging in many places.

**Comment by scorpion451** [comment]
Additional suggestions from a DM that likes to run high-powered kitchen sink campaigns in Pathfinder (aka, "Balance is that you really should not have chased the lone kobold down that dark hallway..."):

The "I'm scared, the DM is smiling" way to add challenge is to look at the strengths, weaknesses, and quirks of a thing, and turn all of those against the player with lots of variable hurdles.
* Thank you for helping: Zombie that picks up small debris and pelts the player with it. Little to no damage for most stuff, it's just annoying and has a tendency to damage the precious loot. You'll regret giving it arrows or bearings to chuck, though, and good luck aiming when it's pelting you with those casings you were planning to go back for.
* Make me not want to shoot it: Electromagnetic zombie that attracts metal stuff, gets armor based on how much crud its picked up. (non-ferrous metal is attracted because it's a fluctuating field) Shooting or bashing it damages the loot, and potentially gives it more metal. Let it get to that pile of casings from your minigun and it's going to be a nightmare to kill.  Maybe it pulls bullets and arrows off course, too, picturing pretty strong electromagnet here, but that'd probably be hard to code.
* Can't shoot what you can't see: stealth zombies aren't actually very stealthy, being aggressive and easy to spot at range. They'd be an actual threat if they actively sought out and avoided leaving dark areas, and didn't aggro until you were right next to them. Pairing them with some sort of trap-creating zombie could be interesting, too. Make the traps recoverable for some valued resource so there's incentive to approach and interact even when you know it's a trap.

**Comment by Ezsk** [comment]
I think we should evaluate the current difficulty and make a goal for balancing, "How to" is the next step.

**Comment by Brian-Otten** [comment]
@RarkGrames 
In the interest of making concrete suggestions, do you think we could add some of the "feral" variants to the military base? it is now mainly populated with soldier/kevlar zombies which are all slow, leaving the area a bit easy. I feel like 3-5% of zombies being runners would be thematically appropriate and make combat in the area more interesting.

**Comment by RarkGrames** [comment]
Yeah, there are two groups in the base monster groups that meant to represent mostly civilians. If they don't have feral runners, that is an oversight. I made the two civilian groups from a copy of a normal zombie group, that's why they might be missing.

**Comment by kevingranade** [comment]
Adding to your point ``1: Amount of enemies is so large that carrying/reloading enough ammo becomes a serious concern (current towns)``, having monsters react at longer distances to noise and particularly gunfire a la https://github.com/CleverRaven/Cataclysm-DDA/projects/3 is going to supply sustained engagements where the player runs the risk of running out of resources, including carryable amounts of ammunition.

**Comment by JacobKessler** [comment]
If there is a plan to have late-game be primarily guns but with some that are intended to encourage melee combat, it would be nice to implement being able to hold a weapon in each hand - not to attack with, but to be able to quickly switch between a one-handed melee weapon and a one-handed firearm, likely with some penalties (reloading the firearm is going to be... difficult, and I'd imagine that accuracy would suffer with the non-dominant hand). Bayonets might actually see some use as well, which would be good.
