### ISSUE TITLE
Canning water ratios are inconsistent among different sized cans

### ISSUE THREAD

**Issue by jkraybill** [CleverRaven/Cataclysm-DDA#37551]
# Describe the bug

In fixing #37504, I discovered numerous other inconsistencies in input ratios for hand canning.

Canned Fish is an example of what occurs in quite a few recipes.

Canned Fish (Can): 1 Fish:1 Water
Canned Fish (Glass Jar): 2 Fish:11 Water
Canned Fish (3L Glass Jar): 12 Fish:16 Water

I'm not giving an exhaustive list here, because I plan to fix this issue by doing a comprehensive pass through all the recipes in canned.json and making ratios consistent and also based on real-life canning recipes.

A related issue that could be looked at is that the large empty tin can doesn't have crafting recipes for many of the canned goods, it probably could be added.

# Steps To Reproduce

Get the crafting ingredients for canned fish in the three sizes (tin can, glass jar, 3L glass jar).

Note that the water ratios are all over the place.

# Expected behavior

The water ratios should be identical, or if they're not, should have some consistency behind them (I suppose it's possible that in real life, canning a larger quantity means you need more or less water than canning a small quantity).

I'm proposing that a model is used that is consistent for all canned goods and based on RL ratios.

**Comment by RarkGrames** [comment]
The water is a bit tricky on this one, because the more you fill the canning pot with jars, the less water you need to get the jars immersed in water, but then again if for example you would can 20 3L jars, using the 25L canning pot, you would use the same batch of water 7 times. The simplest solution for this would be to have every recipe use a couple of liters of water as a tool instead of an ingredient. That would account for all the different cases for different amount of jars.

**Comment by jkraybill** [comment]
There are different recipes for different jar sizes, so it could use, say (2 + cN) as the water requirement, where N is the total volume being canned and a is some constant. I think that c (the ratio of water to ingredient, in the can) would vary based on the thing being canned.

**Comment by RarkGrames** [comment]
Yeah, that seems solid, I didn't have any specific amount of water in mind. My comment was more about using the water as tool, rather than ingredient, the same way you use oil as a tool in certain cooking recipes.

**Comment by Maleclypse** [comment]
Also in the specific recipe you listed can sealer recipes only use water that actually goes inside the can.   In Canning Pot recipes, some recipes need water in the can and outside of the can for sealing and some recipes only need water outside the can.

**Comment by jkraybill** [comment]
Thanks for the tip -- I realise now what's going on with those! When I take a deeper look I will definitely keep in mind the differing ratios for different canning/cooking methods!

**Comment by jkraybill** [comment]
Also noticed that in juice recipes for canning, some of them need water, some of them don't. It's worth looking at this as part of this fix too.

**Comment by Amariithynar** [comment]
As per https://github.com/CleverRaven/Cataclysm-DDA/issues/37504#issuecomment-580206149 :

Canning recipes (not vacuum sealer recipes) that use sugar should also be able to accept syrups, honey, and fruit juice as the sugar component.

Related (but quite possibly outside the scope of this specific issue); since you use sugar in so many canning and other preservative recipes, the sugar recipe for converting sugar beet syrup or fruits to sugar is terrible, taking 20 lye and only 2 of various fruits or 4 sugar beet syrup (5 beets to 7 syrup) or a couple of other things with 20 lye powder to produce 10 sugar. 2 beets and 20 lye powder get you 71 sugar, and 6 pine bough/8 planks/16 splintered wood/8 heavy sticks using 2 units of acid water gets you 71 sugar as well.

Look into the vacuum sealer recipes as well (related since it's a sealed food container); they do the same thing. Meat, fish, fruit all were tested, all only put 1/8 pieces in. 

The "Canning Pot" should probably be renamed to "Pressure Canner", since you can use any old pot to do a basic water boiling canning procedure, but pressure canners let you can basically anything, regardless of preservative (vinegar/salt/sugar) content; since it allows you to can meat, it must thus be a pressure canner, not just a large water canning pot.

V8 is missing recipes and items for using cans and small jars, only allowing you to use 3L jars, or to make it uncontained. 

Batched recipes that use jars don't stack at all, even if all the ingredients used to make them stacked. This leaves a messy interface.

The fermenting sauerkraut jar recipe produces more than the jar can hold, containing 4/2 pieces. This is more an issue of the size of sauerkraut being too large than it should give less; you only use a little bit of sauerkraut when you do use it, nowhere near the same volume as the original cabbage you used, so it should be a 4/4 container for it, honestly. 

Canned fruit shouldn't require sugar to be added; the natural sugars present in the fruit are sufficient to preserve them. Though added sugar does help preserve texture and colour, by the description, it being a mushy sodden mess, that's not what we're doing here, and even if it were, the amount added is a fair amount too much; the most that is used is a 5:1 ratio of water:sugar to make a light simple syrup.

The amount of fruits consumed in canning (where used) is too low for the berries and small fruits, even after accounting for the error in volume to can ratio; you're basically concentrating your fruit down. Similarly, the larger fruits consume too many (Apricots, plums, pears, peaches, etc); a medium-sized can of peaches, for example, takes about 2.5 medium-sized peaches to fill it up, and a 1L jar would take 5; A 3L jar would thus take only about 15, not 36.

The various fruit juices lack cannable/jarrable recipes (both the generic "fruit juice" and the specific ones like orange, cranberry, apple, etc).

Aluminum drink cans should be re-sealable with a can sealer (you can take off the can top and then seal on a new one); I'd have suggested using them to make empty canisters at a 0 seconds conversion as an easy kludge, since canisters are allowed in the canning process already (and because they can both be used to make canister type bombs), but that causes a material crossup, changing them from aluminum to steel (this happens anyways when using aluminum cans to make canister-based bombs, but it shouldn't actively be accepted I don't think).

Many batching speeds are off, requiring you to spend hours as if you're preparing every container by hand and cooking them individually, instead of preparing a large batch of the product and pouring it into each vessel all at once, dealing with it as an actual batch. This is a general issue with recipes, though, not just canning, but since this is about canning... 

Related to the above point, canning should probably use the multicooker/charcoal smoker/charcoal kiln/washing machine/etc. code where you can set it and forget it until it's ready, after preparing it. You put the jars/cans in, seat the lid and lock it down, get it to temperature, and then come back when it's done. This will probably be better doable with the inventory code change where we will be able to actively store items inside of containers discretely.

For the jarred recipes that take 10+ water, if you subtract 10 water from the recipe as a component and make it a tool, make sure to take away the byproduct water generated as well. Honestly it should be producing clean water (it's getting boiled too, after all) instead of just water, but even just fixing the overly-high water requirements would be great.

**Comment by jkraybill** [comment]
@Amariithynar thanks for the detailed notes, that's super helpful. Are you working on this (or planning to)? I'm planning on doing some rework of "innawoods cooking" after this release is done, but don't want to step on any toes or do redundant work!

**Comment by Amariithynar** [comment]
Nope. Long story short, I will NEVER do any coding for Kevin. Ever. I could explain further, but not here. Still willing to provide feedback like the above for others to take or leave as they will, though; I've a wide array of knowledge in various fields I'm always willing to share.

**Comment by Amariithynar** [comment]
Glad that you found them helpful! I'd be more than happy to help out in that, or other regards as well.

As to your question: Nope. Long story short, I will NEVER do any coding for Kevin. Ever. I could explain further, but not here. Still willing to provide feedback like the above for others to take or leave as they will, though; I've a wide array of knowledge in various fields I'm always willing to share.

**Comment by Maleclypse** [comment]
@jkraybill was playing and noticed vacuum sealed chunks only half fill the plastic bags. Not sure if that makes sense for the recipe or not.

**Comment by jkraybill** [comment]
@Maleclypse thanks, that sounds similar to #37504. Is it affecting all vacuum sealing?

**Comment by Amariithynar** [comment]
> @Maleclypse thanks, that sounds similar to #37504. Is it affecting all vacuum sealing?

As I said in my long reply 22 days ago, "Meat, fish, fruit all were tested, all only put 1/8 pieces in." so as far as I know, yes, it does affect all vacuum sealing.

**Comment by RenechCDDA** [comment]
This should be resolved by #62180, which introduced canning standards. If you notice new issues with the canning recipes please open a new issue.
