### ISSUE TITLE
Portable "butchery racks" are not really a thing.

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#37678]
# Please describe.
While researching butchery racks for tileset art, I found - not really surprisingly in hindsight - that a folding deployable 'butchery rack' is not really a thing in real life. While there are portable ways to hang a carcass, they are not the sort of thing you could cart around with you and just unfold in the middle of a forest to butcher that moose you shot.

# Describe the solution you'd like
We already simulate most of butchery, from quick butchery to field dressing, quite well. We should complete this by simulating full butchery properly.

Realistically, I cannot find any evidence that people routinely hang and butcher corpses in the wild. It's something you're going to take back to a base camp or a garage and do over time. In terms of furniture, we should explore crane vehicle items working for full butchery. The current tree requirement is good. We may want to look into an indoor setup, wherein you could hang the carcass from the ceiling. This could be done, for example, with a "meat hook" or "gambrel" deployable item that can be placed anywhere that has a roof overhead. It would also be reasonable to create a "standing frame" furniture with three logs, a shovel, and a bit of rope on the ground (dig the logs down a bit, lay another overtop and secure).

# Describe alternatives you've considered
Going forward, I would love to see full butchery handled as a longer action, with a percentage completion like crafts use, but that's out of the scope of this issue. Likewise it would be cool if we could simulate draining and hanging the meat for a time.

# Additional context
This presents a small nerf to "innawoods" play styles, but quite small as they probably don't have butchery racks most of the time. In terms of convenience, adding cranes as a vehicle component that would work for butchery will solve some of the portability concerns people might develop, and the rest should be solved by the fact that you don't *have* to perform a full butchery if you just want to get your meat and go home.

## Tanning
It would be nice to explore tanning and tanning racks soon too...

**Comment by Maleclypse** [comment]
So if I start putting my butchery refuse rendering ideas into production should I reference this issue?

**Comment by I-am-Erk** [comment]
What are those ideas?

**Comment by Maleclypse** [comment]
So lamp oil precursors/non edible tallows could still be rendered from butchery refuse and feathers can be turned into powdered fertilizer/livestock feed using either powered furniture/powered vehicle parts or with larger pioneer technology structures.  For instance feathers to livestock feed uses modified autoclaves currently.  Not that we really need livestock feed yet, but if I was to start putting things in, it's better to consider these types of things for the future.  For the pioneer tech version I'd probably make it a faction camp expansion.

**Comment by I-am-Erk** [comment]
I think you'd want to first refactor 'butchery refuse' into more parts, as currently it's mostly blood-soaked dung, dirt, and connective tissue, I am not convinced it's got much in it to render. It could be split into some of its components I guess.

**Comment by Maleclypse** [comment]
Fair, all my research was based off large scale butchery operations across time not random hunter cutting up his kill.  Basically if you look at even Cannery Row level butchery operations they truly used everything that could be scraped off the floor in some fashion.  So this is probably faction camp expansion material.

**Comment by scorpion451** [comment]
> Basically if you look at even Cannery Row level butchery operations they truly used everything that could be scraped off the floor in some fashion.

Seconding this. The biggest things of value getting thrown out here in the current model are the blood and connective tissue. The former is used in a huge number of traditional recipes and has a ton of potential as component for both realistic chemistry and mad science, while the latter is the same stuff you're boiling bones to get when you make gelatin. 

Intestines require cleaning, but they're also incredibly useful. Sausage casings are just the beginning; intestine was the material of choice for zeppelin air bags because they're essentially made of natural polymers. If you put two pieces of cleaned intestine together and let them dry, they fuse together on a molecular level. Repeat until you've got a strong, seamless, air-tight bag of desired volume and thickness.

**Comment by I-am-Erk** [comment]
Getting a bit sidetracked here. I think we'd all be fine with a way of actually collecting blood from a carcass, but it's tangential to the core issue. I'd love to see other people propose further refinements to butchery and things, I'm thinking of putting together a "survival improvements"project with stuff like that and plant identification.

**Comment by Brian-Otten** [comment]
Isn't there already the installable meathook for inside your base for butchering? I suspect the main thing that needs to be done is removing the "butchering rack" and adding cranes as an alternative to the meat hook and the tree+rope.

**Comment by vlad1492** [comment]
Vehicle mounted would be good. I've seen mobile butchers IRL that bring a panel van to your site, do the processing / butchering right there in the driveway. Whole cows.  

Me, I like to drag my kills back inside the deathmobile where we can butcher in secret with the window curtains closed. Fewer interruptions that way.  Having an interior tile dedicated to hanging zombie of the week would suit me.

**Comment by TechyBen** [comment]
> Vehicle mounted would be good. I've seen mobile butchers IRL that bring a panel van to your site, do the processing / butchering right there in the driveway. Whole cows.
> 
> Me, I like to drag my kills back inside the deathmobile where we can butcher in secret with the window curtains closed. Fewer interruptions that way. Having an interior tile dedicated to hanging zombie of the week would suit me.

AFAIK it's going this way for most regulated countries when it's not a factory setup. Smaller farms just don't have the space/tech for a camera (record health/kill), racks/knives and trained staff. So if they cannot sent the cattle/animals out to slaughter, they get in a butcher to do it.

https://www.abattoirequipmentsupplies.com/mobile-slaughterhouses
(PS, google has a little on those... I should really get into modding/design in game and make one of those to spawn infrequently in dairy farms :P )

**Comment by Brian-Otten** [comment]
The full mobile abattoire is a bit more luxurious than the survivor would need, but would definitely be a fun semi-rare spawn near farms. Having the survivors use the ingame cranes already installable on vehicles should be fine.

**Comment by scorpion451** [comment]
There are delivery-truck and pickup-trailer sized setups for small on-demand operations. Kind of a rural thing in general, a local butcher shop might have one in places where you'd have enough demand from hunters wanting a professional to properly inspect and prepare large game, or many small operations that just cull a few from the herd every year, that sort of thing.

**Comment by CSHague** [comment]
We already have lifting quality. Why not just demand a level of lifting quality based on the mass and volume of the corpse? This means that ropes over trees should also count as having some level of Lifting Quality, as well.

**Comment by vlad1492** [comment]
My latest survivor has some plant mutations, including the 'vine arms' one that lets you use your arms like ropes.  But only for descending into deep dark places.  Perhaps vine arms could qualify as long rope for butchering?

**Comment by I-am-Erk** [comment]
I'm not sure how you'd hang a corpse and also butcher it with your long arms

**Comment by vlad1492** [comment]
Not arms, so much.  More like tentacles. 

Level 1: "You have developed several vines sprouting from your shoulder area. They're bulky and get in the way." 

Level 2: "You've developed the ability to control your vines; they make good lashes. You can even rappel down sheer drops using them, but disconnecting HURTS. "

I figure if I can use them competently in melee and to support my own not inconsiderable bulk on a descent, then they have the strength and dexterity needed to loop them over a branch and hold a carcass up to butcher.

**Comment by I-am-Erk** [comment]
I'm not convinced of that, you're potentially holding up a 1500kg moose for several hours here, and part of this PR is suggesting we start simulating other parts of butchery like draining blood for hours and potentially aging meat for days...

**Comment by vlad1492** [comment]
Fair point, but consider that there are already weight thresholds for tool needs. 
Should a 4-strength survivor who happens to have a rope be able to hoist a 700kg moose into a tree? 
Given knowledge and time to build tools, sure.

Perhaps it is time to break down butchery tasks a bit further - small medium large? 
Small - any strength, hand tools,good for carcass up to 40kg
Medium - Rope tree or suchlike, and 8+ strength - deer, wolves, ants etc up to 80kg
(Vine limbs count as rope)
Large - need mechanical hoist of some kind, bear, moose, jabberwock, etc.

**Comment by Amariithynar** [comment]
A "Mobile Butchery Rack" would just be a standing frame with hooks and points to hang corpses from, allowing you to strip a hide and break a carcass down to primals; taking a long stick or branch and tying it between two trees, or even just tossing ropes over a long strong branch (the current tree setup), provides much the same function that a meat hook does, too. It should continue to be, as it is now, just another replacement for a tree and rope or meathook on chain setup. Functionally it is no different, and it doesn't take much thought that a foldable frame that you can mount a carcass onto would be useful in a postapocalyptic scenario, while with the world as it is now, there is no need for such a thing.

The "mobile butchery" that is in use today that you speak about (where the butcher arrives with a trailer'd abattoir) is little more than a trailer purpose-built to hang carcasses in and cut them down to parts, rather than working out in the open. The actual functional part of it is still simply the mounting point which the butcher uses to prepare the carcass, and the butcher's block where a butcher cuts it down further from the primals cut off the carcass, into proper cuts of meat. 

I do agree that truly large animals like cow and moose should have to be field dressed and halved before the halves can be hung and butchered into primal cuts on a mobile butchery rack (make it act like a vehicle that has a volume/weight limit?), which can then be cut down into smaller pieces. A full meat hook and chain setup, or rope and tree setup, generally would be able to support anything. Pulleys and snatch blocks and all their various kinds of things make for very big force multipliers when attempting to lift something like a moose manually, as well. If you want to introduce pulleys and snatch blocks to give better lifting leverage, by all means.

Something that should be doable only when the carcass is fresh (and only doable as the first or second step done, if the first was to field dress it) is to bleed it out, which should dramatically increase its longevity before going bad, and give you the blood to use in cooking, as well,

The fact that primal cuts aren't made first, and then those can be broken down further, just like disassembling an item made up of other items that can be broken down further, has always been strange to me. You can't make a pot roast with a bunch of chunks of meat, after all (not that there is a pot roast recipe in game, but you get what I mean).

Here's a video of some guys cleaning a moose carcass, linked just to show the mounting system used; as you can see, a meat hook and chain system does the job fine, with a braced pipe going between the bones of the hind legs to ensure support. You could do this with a tree and several ropes even, but it'd be too big for a mobile rack as a whole carcass. If it was field dressed and halved, a half-carcass could be mounted easily enough and butchered down from there, however. https://www.youtube.com/watch?v=BV4agA7CJy0

Black bears can be held aloft with just a few lengths of thin rope and butchered easily enough so would fit on a folding rack, as seen here: https://www.youtube.com/watch?v=KYps42O-Zyc

ScottRea has several masterclass videos about the full carcass butchery process, that shows that you really only need the butcher's block to cut everything down on; here's his on butchering a pig, already dressed and bled. https://www.youtube.com/watch?v=eU_d_9opKg8 Even with a pig, it's easier to deal with halved, but isn't necessary to do to cut down; it just makes it easier.

One more thing that these videos should show is that the actual butchering process is quite fast if you just want to strip the meat off without any care for proper butchery cuts, as well.

**Comment by LyleSY** [comment]
I think this was fixed by all the butchery changes last year, for example #42372

**Comment by I-am-Erk** [comment]
I should take a look and see. It's been a while since I did much detailed butchery and not just dissection
