### ISSUE TITLE
Scaling explosive power by container used.

### ISSUE THREAD

**Issue by Brian-Otten** [CleverRaven/Cataclysm-DDA#37705]
# Is your feature request related to a problem? Please describe.
Currently explosives design has us use grams of tnt equivalent to determine explosive power, but we don't currently have a model for how the explosive power is diminished by using imperfect containers. This makes it very difficult to balance the explosives so they are all as strong as you expect.

# Describe the solution you'd like
I will be going over all the explosives soon, having already worked with a decent amount of them, and would like to be able to use a guideline for the explosive power modifier depending on the container used. 
I will suggest some numbers we could use here but am fully open to different ones:

Bad container (glass/plastic). 50% of explosive power
Improvised container (cans/ clay canister). 75% of explosive power
Suitable containers(metal container). 100% of explosive power.

# Describe alternatives you've considered
Waiting for someone to code a way for explosives to dynamically adjust their explosive power depending on casing material.

**Comment by Brian-Otten** [comment]
I have energy now so i am going to go over and make a PR to change the explosive power to tnt equivalence for now, i can adjust them with the values we decide on here very easily when we do settle on some.

**Comment by scorpion451** [comment]
Researching explosives is a good way to end up on watchlists but you might need to do that here if you want to get more precise.  The type of explosive makes a massive difference in what the ideal container material is: 

Glass would be superior to clay for a lot of middle-ground explosives, for instance, because it's strong but easily damaged by shock.  A low power, high velocity explosive could just be a flashbang in a tin can but extremely dangerous in a plastic or cardboard container it can easily burst. High power, low velocity explosives often hit a point of the container just influencing the shape of the debris field, if they matter at all, while high velocity, high power explosives don't care what's around them; they'll punch a steel plate into a concrete wall with open air in the other direction.

**Comment by Amariithynar** [comment]
Wouldn't black powder, gasoline, smokeless powders, etc. be low explosives, and then things like ANFO, RDX, dynamite, etc. be high explosives?

Wouldn't glassified clay (so, stoneware) be just as viable as glass for "middle-ground" explosives?
