### ISSUE TITLE
Some energy-related weapons should consume UPS charges while reloading, not while shooting.

### ISSUE THREAD

**Issue by eilaattwood** [CleverRaven/Cataclysm-DDA#37753]
# Is your feature request related to a problem? Please describe.
Weapons like gauss gun or rain gun (ferromagnetic rifle) actually has built-in capacitors capable of transfering  energy in extremely short time. Thing that most long-term energy storage solutions such as batteries could not provide. Those capacitors are consuming energy while the weapon is reloaded, and discharge when it shoots.

# Describe the solution you'd like
Add a json parameter for the weapons allowing to specify amount of consumed UPS charges on weapon reload.
Add possibility to modify that with weapon mod.

# Describe alternatives you've considered
We can definitely leave it abstracted to consuming charges on shoot.

# Additional context
None

**Comment by TechyBen** [comment]
A simple "capacitor" and "super capacitor" items/for recipes would also help with abstracting the gatekeeping of some of these items. Supercapacitors would (theoretically) be needed, and thus available, for the CDDA tech in game. For the ferromagnetic rifle, thus gatekeeping it (even if learned recipes early on etc). Though normal nail drivers/throwers/mag coilguns would probably use normal batteries/capacitors. Just the high powered rail or laser weps using the super caps.

Not sure what a survival could disassemble for super caps though. They could go in the Electric Sports Car instead of storage batteries (but that may be overkill for the number they'd give :P )!

**Comment by scorpion451** [comment]
I actually think the rifles would use regular capacitors- very high voltages, but limited storage capacity. Those you could find in any high-voltage appliance, like microwave ovens. 

Supercapacitors are really in the game already: that's pretty much what storage batteries are. We have them in the real world too, the only real reason they haven't totally replaced cell batteries is that with current tech, cell batteries can store more power in the same footprint. Storage batteries tech seems to be something like an [ultrabattery](https://en.wikipedia.org/wiki/UltraBattery)- storage density of a cell battery, rugged stability and high input/output speed of a supercapacitor.
