### ISSUE TITLE
Impossible to remove freshly installed foot pedals: Remove attached part first.

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#37860]
#  Steps To Reproduce

1. Load the game.
2. Try removing the foot pedals installed in the car.
3. `Remove attached part first.`

# Expected behavior

Being able to remove the pedals.

# Screenshots

![](https://pstbin.ru/f/95655/)
**If applicable**, add screenshots to help explain your problem.

# Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.D-12025-g40c494c222-dirty [64-bit]
- Graphics Version: Curses
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations]
]

# Additional context

[2020.02.09.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4177132/2020.02.09.zip)

**Comment by Hirmuolio** [comment]
This happens probably because pedals have "CONTROLS" flag.

But the security system part has "ON_CONTROLS" flag.

How to fix this?

* Create some new flags so that security system requires specifically normal vehicle controls and not other controls such as pedals.
* Change the check so that if there is another part with the required flag the part can be removed. Could lead to odd exploit where you can remove part X that is required by part Y if you first install different part Z and then remove part X.
* Make it so that you can't install multiple different "CONTROLS" parts on same tile.

Relates to #37453 (it doesn't fix it but it but touches this part of the code).

**Comment by Funguss** [comment]
Hm. Security controls on a push bike makes sense, though. Just not the same kind that are used on cars.

**Comment by l29ah** [comment]
Still broken in master.
