### ISSUE TITLE
Survivor armor rework

### ISSUE THREAD

**Issue by RarkGrames** [CleverRaven/Cataclysm-DDA#37961]
# Is your feature request related to a problem? Please describe.
The recent PR that removed survivor helmets suggests that survivor gear is about to be reworked. I wanted to open a discussion about how they could be reworked, rather than removing parts of them. (Currently they are unrealistic, I agree with that.) I would do the rework if there is a solid agreement about them.

# Describe the solution you'd like
Current survivor gear pros:
- Better protection
- Better encumbrance
- Better coverage
- They have the `sturdy `flag
- Lots of storage
- Added utility

To stay in line with reality, my idea would be:
- Better encumbrance
- Having the `sturdy `flag
- Lots of storage
- Added utility

With this the survivor suit would be for example same as a swat armor but with big pockets or pouches, and having tailor made with some encumbrance gain.
A survivor helmet would be the same as an army helmet, with the added utility of a built-in headlamp, or a full face helmet-gasmask combination.
A survivor mask would be the same as a gasmask, but with added utility to remove the mouth encumbrance with opening up the mouth section, etc.

**Comment by Fris0uman** [comment]
> as a swat armor but with big pockets or pouches, and having tailor made with some encumbrance gain.

So you add pockets on it and end up with something less encumbering than the original armor? Or you add pockets at no encumbrance cost?

**Comment by RarkGrames** [comment]
Adding encumbrance proportional to the storage space. Working out the features in a modular way, like for example 2 encumbrance per storage liters, or making them having the `"rigid": false,` attribute, similarly to backpacks.

**Comment by sayke** [comment]
I envision survivor armor as an extremely customized high-tech tactical suit, like Batman's or Black Panther's costumes: Visually understated and practical but still very much customized, and so just all-around better than off-the-shelf clothing/gear. It makes sense for it to have high coverage, as well as better encumbrance, sturdy, storage, and utility, while keeping protection on par with other armors.

**Comment by mlangsdorf** [comment]
I'd really like to see survivor armor as slightly inferior to the high quality manufactured armors, but optimized for a different set of threats.  Survivors expect to mostly fight against large numbers of basically normal humans with very little in the way of ranged threats, but with a very real chance of getting some kind of nasty gunk on you.  So survivor armor should provide full coverage and solid protection against punches and light blades, while not being very good against bullets or arrows.  Something akin to reinforced bunker gear without as much emphasis on fire protection, instead of crazy improved kevlar vests.

**Comment by SirPendrak** [comment]
Maybe split survivor armors into 2 tiers: 
1 - survivor sets of different kinds - same requrements to make as current survivor sets, much worse stats than current survivor sets
2 - apocalypse suits - same stats as current survivor gear, but much, much harder to make. Requires 10 in fabrication and sewing, probably full forging equipement and maybe "quality steel" (in case of heavy apocalypse set) from tools or weapons, and not just scrap from broken car doors. Maybe even bits and parts printed in nanofabricator. Or at the very least heavy apocalypse gasmask would require 2 pairs of ballistic googles, not safety glasses that you made earlier from plastic bottles...

**Comment by SirPendrak** [comment]
By quickly eyeballing every survivor item theese are quickfixes that come to my mind: 
Most of surv. gear isnt broken significantly, but: 
- all kevlar requires a soldering iron wchich is silly. I allways belived every surv. item except helmets was soft kevlar. Not sure about masks (or surv googles, but i dont know where they have that kevlar). 
- light survivor is a little on the OP side. Maybe it should have less storage than other sets. 
- medium survivor set is a bit on the weaker side (for a survivor set) It is over twice as encumbering while its protection is like 20% better and has a tiny bit less storage. Probably best outcome would be when medium set was your standard choice and other set were for specialised tasks, going super light or super tanky, going fireprooof, acidproof etc. Medium set should have 1 point better acid and 1 poin better fire protection than cotton light survivor set. Medium set should be a tiny bit more warm than light set. 
- heavy survivor set should have same acid and fire resistance as medium surivor set because of leather base. But its recipe is most broken on of them all. While oter sets are fine at 5-8 sewing, this one should be 10 sewing 10 fabrication, with full forging requirements. After all, heavy survivor set is baisically medium set with attached super-brigandine between kevalr and leather. Heavy set should be even more warm than medium set. 
- fireproof set is fine, only should have more warmth. 
- neoprene set is strange. Its boots encumbrance is nuts, and its encumbrance overall mean baisically noone could swimm with it. For some reason its only half as protective as other sets, but it has huge carrying space. IDK what to do with it. 
- All survivor gasmask should require ballistic googles to make, and/or fireman masks/gasmasks. 
Heavy gasmask should require double pairs of ballistic googles to make visor thicker. 
Same for surv. googles and divemasks. 
- Scavenger gear (baisically another forgoten cousin of surv. gear) shouldnt be 8 difficult in skills to make. Its simply another take on cotton light suit, 6 would probably be better.

**Comment by eilaattwood** [comment]
>     * Winter survivor set

I use it for raiding frozen labs.

**Comment by RarkGrames** [comment]
> 
> 
> I envision survivor armor as an extremely customized high-tech tactical suit, like Batman's or Black Panther's costumes: Visually understated and practical but still very much customized, and so just all-around better than off-the-shelf clothing/gear. It makes sense for it to have high coverage, as well as better encumbrance, sturdy, storage, and utility, while keeping protection on par with other armors.

I have a feeling that sooner or later they are gonna get axed if they are better than factory made armor. Survivor gear is one of the defining unique features of CDDA (at least for me), so I want it to stay, or even improve on it. With this issue I want to find that narrow little slit on the Venn-diagram of the realists and the apocalypticool people, so everyone can be happy (or at least not left completely salty).
@Rivet-the-Zombie Per my understanding you were the one adding the survivor armors originally, what is your take on this thing?

**Comment by RarkGrames** [comment]
> 
> 
> I'd really like to see survivor armor as slightly inferior to the high quality manufactured armors, but optimized for a different set of threats. Survivors expect to mostly fight against large numbers of basically normal humans with very little in the way of ranged threats, but with a very real chance of getting some kind of nasty gunk on you. So survivor armor should provide full coverage and solid protection against punches and light blades, while not being very good against bullets or arrows. Something akin to reinforced bunker gear without as much emphasis on fire protection, instead of crazy improved kevlar vests.

Would this mean a leather jumpsuit without kevlar? I'm asking from a game mechanics viewpoint, because the materials decide about most of the features.

What I had in mind is to make the whole thing more modular with @Rail-Runner 's addition of tailor-modifiable steel plating. Could be that for example the survivor suit is a simple, well-fitting leather jumpsuit with pockets that you can modify to make heavy survivor suit with kevlar and steel plates, or winter suit if you line it with fur. With this it is possible to get rid of a lot of items and recipes without losing out on options. A light suit would be the same, just made of cotton, if you need summerwear or you don't want encumbrance.

The 100% coverage is a subjective thing that I'm not sure how to interpret, because even if it is a full body suit, there are points of accessibility at the neck, ankles and wrists.

**Comment by RarkGrames** [comment]
@SirPendrak All these small changes can be fixed with a complete overview of all the armors. About the subject of a new, higher tier armor, the same applies as I mentioned earlier.

**Comment by SirPendrak** [comment]
> The 100% coverage is a subjective thing that I'm not sure how to interpret, because even if it is a full body suit, there are points of accessibility at the neck, ankles and wrists.

You can have gauntlets ovelap wrists with sleeve of the suit, same for boots overlaping at ankles ETC. You can do it with most standard clothing IRL.

**Comment by RarkGrames** [comment]
Yeah, that part of the question is clear, the meat of the discussion is more like why only the survivor gear has this, and not the rest of the in-game armors.

**Comment by wapcaplet** [comment]
The crafting times for survivor gear are laughably short in many cases too. I am not a tailor, but 1 hour for hand-stitched, Kevlar-reinforced gloves seems extremely doubtful. For a survivor hood, maybe 1 hour makes sense because there’s not much precise fitting needed, but the rest I suggest could use a significant increase. Gear this high-quality and well-fitting should take a proportionally long time to make, say more like 4-6 hours for the gloves and boots, maybe 8-10 for torso and leg pieces.

**Comment by RarkGrames** [comment]
> 
> 
> The crafting times for survivor gear are laughably short in many cases too.

**Comment by mlangsdorf** [comment]
My vision of survivor gear as light weight armor optimized to resist punches and biochem agents would probably be a soft kevlar and hard steel brigantine, with either a rubber or moisture wicking microfiber inner layer.  The rubber versions are warmer and have better environmental protection, the microfiber versions are more comfortable in summer.

Again, the model is the bunker_coat and bunker_pants, which already have decent storage and 100% coverage, in addition to being rain proof and sturdy.  Just less nomex and more steel plate.

**Comment by Rivet-the-Zombie** [comment]
@RarkGrames, the survivor gear is stuff that's supposed to be ultra-optimized specifically for the many unique needs of the apocalypse and custom fitted just for their creator, like @sayke said. Their crafting times really should be _much_ longer now that the crafting system can handle pausing tasks.

**Comment by esabaliauskas** [comment]
To add my two cents to the discussion, I don't see a problem that survivor gear is more suited for apocalypse than anything made pre-cata, just because there wasn't a need for such gear. All the civillisation needed was protection from bullets, fires and powerarmors (because they could).

But I agree that survivor gear needs readjustments as it is now

**Comment by Maddremor** [comment]
One route you could take is to have at least some survivor gear being explicitly modified pre-cataclysm gear, instead of just using them as ingredients. For example, survivor riot gear being a standard riot gear with some zombie specific alterations. Kind of like the current hard hat and hooded hard hat situation, but with less trivial modifications.
