### ISSUE TITLE
Specify avoid_sharp for appropriate monsters

### ISSUE THREAD

**Issue by jkraybill** [CleverRaven/Cataclysm-DDA#37978]
# Is your feature request related to a problem?
Currently, some monsters (e.g. pet dogs) don't avoid sharp objects when they should. #37964 allows sharp object avoidance to be specified in monster pathfinding settings.

# Describe the solution you'd like
Go through and specify trap avoidance after #37964 is merged. A reasonable first step would be to specify it true anywhere trap avoidance is true.

# Describe alternatives you've considered
Not doing anything, as #37964 alone doesn't change existing monster behavior around sharp objects.

# Additional context
Would love some input on any monsters that should avoid sharp things but not traps, or vice versa.

**Comment by Funguss** [comment]
Sharp things like broken glass? Or what? My understanding is that animals generally take getting injured to recognise a hazard, and glass is one that is hard to judge. This is why broken glass is a particular hazard for pets.

**Comment by jeremyshannon** [comment]
The problem with recognizing a hazard is that there's no way for monsters to learn things, so they will happily dance across a field of wreckage until they die. I found this out when I tried to have a pet dog to carry extra things for a no-vehicles Kwai Chang Caine run. Two dogs in, I switched to an NPC buddy.

Anything with basic animal intelligence should probably avoid obvious harm like that, just not traps like landmines and such.

**Comment by Funguss** [comment]
Yeah, I understand that, so I think it's reasonable to abstract those instances away. I'm just not sure about the glass issue. Is avoiding glass included in sharp objects?

**Comment by jkraybill** [comment]
It's anything with the SHARP flag, which are basically the things that mildly cut you when you walk into them after saying "Y" to the confirmation message. This includes barbed wire, metal wreckage, and broken glass.

This was a suggestion from my PR, and I don't have a strong opinion on it. I don't keep pets and haven't had enough experience with existing pet behaviors in game to form an opinion.

I get both perspectives but given the game behavior, if you have to choose one, it seems preferable that pets never plunge themselves into self-inflicted wounds than them doing it whenever their pathing takes them there?

**Comment by Funguss** [comment]
Yeah, I see... Having considered it a bit more I'm totally on the fence. Glass does pretty low damage, it would be an incentive for keeping your base clean, and it's realistic. On the flip side some folks may not even be aware that glass causes cut damage (due to never going barefoot) leading to mysterious dog deaths, glass shards may be buried in a big pile of loot such that it's not even noticed, clearing away glass in case your dog walks over it would get VERY tedious when roaming, and we're not even sure that dogs constantly exposed to broken glass wouldn't just get used to avoiding it anyway.

Actually, I just convinced myself that they shouldn't walk over glass. Also, I imagine that different breeds have different textured pads which are more or less resistant to tearing. It seems like a lot of effort to go to in order to accurately simulate a small outlier that would more often than not lead to frustration.

Yep, totally convinced now. No self-inflicted wounds for pets, please! :+1:

**Comment by scorpion451** [comment]
As someone who lives in an area with sticker burrs (not the little sissy ones that are like velcro, the living caltrop ones that can draw blood) I can assure you that dogs quickly learn to watch their step, even when running. Farm dogs also tend to have little problem with sharp rocks and whatnot; even my dachshund/chihuahua mix has pads like boot leather from running around on gravel and scrubbrush all the time.

**Comment by jeremyshannon** [comment]
This seems less like an enhancement to me, and more like a bugfix for "your animals will commit suicide because they're too dumb to avoid repeatedly impaling themselves."
