### ISSUE TITLE
The "common cold" is very unreasonable implemented

### ISSUE THREAD

**Issue by AncientSion** [CleverRaven/Cataclysm-DDA#38041]
Describe the ISSUE 

The common cold is unreasonable excessive in regards to how it punishes the player for a seemingly random effect. There is no way to "fight" the cold except staying inside and warm and drinking syrup to unbuff. 
And even that is speculation on my point and there is no tangible way to see if your condition is improving or not.

I think it is unjust to be able to mend broken limbs in a couple days of in game time, or heal severe health damage within 2 nights with bandages and some antiseptic while carrying the common cold for weeks on end with you. Since mending limbs and healing limbs is apparently in an "ok" state, i can only assume that compared the "common cold" is in a very unreasonable state.

As far as im concerned, within the scope of the game the common cold was implement OVER reality in regards to duration while every other health-based mechanic was implemented way UNDER reality in regards to duration.

# Expected behavior

As far as i am concerned, the common cold in reality lasts a week, maybe two. In terms of the game, this should be scaled to maybe 3 to 4 days with the option of using medicine or some stuff to cut it by maybe 25 to 33 %.

In addition, there should be more clear instructions on WHY you actually got the cold and how you can fight it. As it is, the whole mechanic is in my opinion a random, annoying mess that should (dare you, thats my opinion) have never been allowed to live this long in the game as it is in the first place.

I would rather see it disabled than continue in this wretched half-state.
Alternatively, cut the duration to a week, tops, for starters, maybe adjusted by a modifier based on player health. So that based on player health it lasts maybe 67 to 133 % time ?

**Comment by Funguss** [comment]
Well, from experience I can tell you that NOT resting up can make a cold linger for weeks. The longest I've had was in the area of two months, though it wasn't severe after the first week.

Are you playing release or experimental? Timescales have been upped substantially, so a year is (almost) 365 days. IIRC it's actually 364, but whatever. Personally, I'd like to see rest making a far  more substantial impact than health. Increased stamina drain, dependent on severity of the illness. Scaling ill effects. Relapses. I'd like it you had to make a tough choice between taking a week off, lying in bed and staying hydrated or risking a relapse or making things worse by cycling into town to get some food or do some hunting. I've not found a cold to be very punishing in game at all, just a minor nuisance. One of the key things is to make sure you don't drink regular cough syrup unless you want to spend the majority of the time asleep.

Regarding broken limbs: They should definitely be more punishing. Though I may have found a bug where NPC limbs don't ever heal, so I guess there's that...

**Comment by Lamandus** [comment]
In my opinion, I find the cold being implemented well. It is not an influenca, but still something which hampering your efforts quite well. Why you get the cold? Low health is one of the most reasonable reasons why you got it in the first place. So it makes sense.
And I have to agree to @Funguss here, instead of comparing it to broken limbs and saying, cold should be less punishing because of them, we actually should make broken limbs more punishing.

> As far as i am concerned, the common cold in reality lasts a week, maybe two. In terms of the game, this should be scaled to maybe 3 to 4 days with the option of using medicine or some stuff to cut it by maybe 25 to 33 %.
good night rest should cut the duration, if anything. There is no viable medicine on the market to "cure" the flu or a common cold (which is triggered by viriae same like the flu).

**Comment by Inglonias** [comment]
The biggest issue with the common cold in the game is that short of curing it with something like royal jelly, there is nothing you can do to shorten the duration of a cold once you have one. The duration is set when you catch the cold, and as far as I know, cannot be manipulated after that. We can avoid the need to shorten the cold by having treatment options available once you get it.

For instance the duration could be shortened by having a positive health stat while you have a cold,, and lengthened with a negative one. This would make something like drinking lots of tea shorten a cold. While it is a common belief that doing stuff like that shortens a cold, I'm not a doctor. I don't know if it actually shortens the cold or just makes you feel better if you have one.

**Comment by Funguss** [comment]
Well, it all comes down to your body's defences. Beyond keeping adequately hydrated and rested there really isn't much you can do beyond ride it out. All you can treat are the symptoms, and those are caused by the body fighting the infection. It's debatable whether that's really for the best.

I think the biggest thing about it is the lack of control. We're used to being able to deal with things in games, and when it comes to illness in C:DDA you lack control. Personally, I like this, even though it bugs me. All you can do is try and lead a healthy lifestyle, which, during the cataclysm, is easier said than done when you're living on whatever you can scavenge.

Though I must say the times when I've caught a cold on the first day (or even first couple of hours) have lead me to rage quit.

**Comment by Night-Pryanik** [comment]
> I don't know if it actually shortens the cold

It doesn't.
