### ISSUE TITLE
Removing this part would split the vehicle.

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#38061]
# Describe the bug

It's impossible to split the vehicle via the interaction menus, but it's perfectly doable by mauling the part in question with a sledgehammer.

# Expected behavior

Being able to split vehicles w/o vandalism.

# Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.D-12289-g26b2614aa9-dirty [64-bit]
- Graphics Version: Curses
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations]
]

**Comment by Funguss** [comment]
You can split vehicles by vandalism now?! With a previous bug I had some fun making a convoy of motorbikes for me and my NPCs. It was fun to build but they didn't really work.

**Comment by mlangsdorf** [comment]
Vehicle splits have been in the game since summer of 2018, as well as a limited subset of vehicle merges.

I can probably add a split option in the vehicle interaction menu (maybe), but I am not going to be the guy who writes the code to merge two arbitrary vehicles of unlimited size and facing.  Good luck to whoever decides to take that on.

**Comment by l29ah** [comment]
In fact i just wanted to cannibalize a car into frames when it turned out i just can't remove some middle ones just because of reasons (and removing wheels and stuff to be able to remove the corner frames would take extra time).

**Comment by Funguss** [comment]
Oh wow!! That vehicle splitting is amazing! Well done for that! It would be great to see it as an option in the interaction menu, would also be sweet if NPCs set to deconstruct vehicles would go ahead and split them if given the choice. For that, though, the job would probably need updating with the addition of the 'new' vehicle, otherwise I expect they'd ignore it until asked to deconstruct again. That would get annoying.
