### ISSUE TITLE
Message "The weight of the SUV damages the diesel"

### ISSUE THREAD

**Issue by bug-sniper** [CleverRaven/Cataclysm-DDA#38080]
# Describe the bug

After filling a car that already has gasoline with diesel, I get the weird message "The weight of the SUV damages the diesel"

# Steps To Reproduce

2. Drive car filled with gasoline and with an empty second gasoline tank (such as an SUV) near a diesel-containing vehicle.
2. Siphon diesel from the diesel vehicle into the SUV
3. Drive the SUV

# Expected behavior

Anything but a message saying that diesel is damaged by the weight of a vehicle.

# Screenshots

![Screenshot from 2020-02-16 18-30-14](https://user-images.githubusercontent.com/6971612/74619470-77c21980-50ea-11ea-808b-fcc6104e38d8.png)

# Versions and configuration

# Additional context

**Comment by anothersimulacrum** [comment]
The diesel is leaking from the tank and being damage under the wheels of the car.

**Comment by 1945pppp** [comment]
maybe a leak and then getting damaged under wheel

**Comment by Funguss** [comment]
Though I would like to mention that liquids being damaged by heavy vehicles is a bit odd regardless.

**Comment by jkraybill** [comment]
I agree that this probably is due to the vehicle actually damaging the fuel, but that message is pretty strange to a new player. That message also seems very sensitive.

I wonder if it could be modified such that you only get the "damaged" message when X is damaged if X is not a liquid, and/or the amount of damage is above a certain threshold, or if the damaged items are above a certain level of "significance".

**Comment by jkraybill** [comment]
I quickly coded up what seems like an improvement in #38082, any input much appreciated.
