### ISSUE TITLE
Electric motor in a vehicle has much less power when the vehicle is going backwards

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#38165]
# Describe the bug

# Steps To Reproduce

Install an electric motor on a heavy vehicle and find out it is not powerful enough to move backwards at all.

# Expected behavior

It should be the same, since electric motors don't care about the direction of the rotation.

# Screenshots

# Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.D-12404-g1d23fcce1e-dirty [64-bit]
- Graphics Version: Curses
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots]
]

# Additional context

**Comment by wapcaplet** [comment]
It took a few tries, but I was able to reproduce the problem with an electric car, after replacing the regular electric motor with a "small electric motor", and adding a bunch of heavy frames and armor until the vehicle weighed over 5300 lbs.

Now, I can accelerate forward (very slowly), but cannot move at all in reverse.

![image](https://user-images.githubusercontent.com/238395/74995776-12826700-540f-11ea-9d28-10d610aade22.png)

Glancing at the code, I see these lines in `src/vehicle_move.cpp` that appear to calculate the maximum reverse velocity as 1/4 of the forward velocity. And, because it's doing integer division, I guess if forward velocity is any less than 3, reverse will bottom out to 0.

https://github.com/CleverRaven/Cataclysm-DDA/blob/05940bfe3aa1c95c10dc2df49bb2b7a88f23b039/src/vehicle_move.cpp#L247-L248

Whether a vehicle uses a gearbox or not, I should think if forward movement is possible, then reverse movement should also be possible, even if it's slower. I will try a fix and submit a PR.

**Comment by kevingranade** [comment]
> Whether a vehicle uses a gearbox or not, I should think if forward movement is possible, then reverse movement should also be possible, even if it's slower.

That is not correct, if reverse has less torque than 1st gear, it can absolutely stall the vehicle.

I agree it should not be applied for electric motors.

**Comment by eilaattwood** [comment]
> if reverse has less torque than 1st gear, it can absolutely stall the vehicle.

In almost all real gearboxes 1st rear and reverse are made almost equal, as far as i know.

**Comment by wapcaplet** [comment]
> In almost all real gearboxes 1st gear and reverse are made almost equal, as far as i know.

This is kind of what I was assuming too, at least from a gameplay perspective. It looks like gearboxes are not modeled at all in the current vehicle system; electric-power, pedal-power, animal-power, and diesel-power all have their reverse acceleration nerfed by the same amount. This crudely simulates the fact that real-world gearboxes only have a single reverse gear, while typically having multiple forward gears.

I guess it would be harder to pedal a bicycle in reverse without a lot of practice, but I don't see any mechanical reason pedals should be slower or have less torque in reverse. I've never ridden a unicycle, but they would seem ideally symmetrical, the seat being directly over the pedals.

Horses, I would have to [do some more research](https://www.horsetalk.co.nz/2015/06/25/forward-thinking-perils-backwards-horse-training/) but it's probably safe to assume they won't win any races running backwards.

My thinking for now is to simply check whether the vehicle has any battery-powered engines active, and avoid the power-reduction if so. Full gearbox implementation I think will have to wait.

**Comment by l29ah** [comment]
As a side note, i wonder if modern car gasoline engines could actually rotate in reverse if the firmware understood such a mode of operation, or the valves are still operated mechanically by the engine shaft?
