### ISSUE TITLE
"Jungle Style" Taped gun magazines

### ISSUE THREAD

**Issue by Mister-Cultist** [CleverRaven/Cataclysm-DDA#38178]
Historically (ie ww2 and the Vietnam war) "jungle style" magazines were used by soldiers to increase reloading speed. Jungle mags are essentially just two magazines taped together so when one is depleted you can flip it over and reload it once without having to go into your pockets for the next mag, this increases your reload speed by a fair amount. Creating a taped or jungle style magazine would be easy enough for anyone who knew what they were doing (ie read a magazine about guns which might mention it), had two magazines of the same sort full for bullets and had some duct tape lying around. Modifications of this sort seem like the kind of thing desperate survivors would use and feel like they fit into the whole makeshit feel we have going on in the game. For historical and modern examples you can see the wikipedia article here: https://en.wikipedia.org/wiki/Jungle_style_(firearm_magazines)

**Comment by HaplessOperator** [comment]
This doesn't actually make reloading any faster unless you don't have any way to carry magazines in either a good, well-designed pouch on your workspace or in a holder on your belt or something.

If you're doing either of those two things, reloading with a "jungle style" taped magazine can actually slow you down, especially if you're not worried about magazine retention.

The only real benefit to taping magazines this way comes from using a weapon that has a non trigger finger operated paddle release, or in bullpup platforms that obviate a button-press drop-release in the first place, or if you're using the super old and busted 70s-era foldover box pouches.

tl;dr: jungle magazines can be done, but the benefit isn't what the OP thought it is; it's just an easy way to carry an additional magazine if you don't have a place to put it otherwise, or no other way to store them for quick access

Side note: it's also notorious for damaging magazines, as it has the vulnerable, easily damaged feed lips totally exposed on the magazine not currently inserted into the mag well, and provides for easy ingress of environmental contamination of the magazine.

**Comment by Mister-Cultist** [comment]
Point taken, main reason I want them in the game is that I don't usually wear things that have magazine pouches so being able to reload without having my character have to take the item out of their backpack would be faster.

**Comment by Amariithynar** [comment]
I'd argue that it is faster for someone who isn't trained in the use of the various tactical gear to use, but would also agree that it runs the risk of contamination or even possibly damage if you drop the weapon definitely if it gets hit and damaged. Perhaps give it a reduced durability, and make it more prone to jamming?
