### ISSUE TITLE
pneumatic assault rifle and pneumatic guns in general are too powerful

### ISSUE THREAD

**Issue by misterprimus** [CleverRaven/Cataclysm-DDA#38196]
# Describe the bug

Air weapons are too strong and unrealistic.

# Steps To Reproduce

1. Make a player with a pneumatic assault rifle & pebbles.
2. Try to aim at a zed.
3. Fire.
4. Zed takes more damage than it should.

# Expected behavior

Typical multipump rifles should be more or less useless against zeds. From strongest to weakest, air rifles typically go like this:

Multipump rifle < Break barrel single shot rifle < PCP rifle

PCP come in big bore variety, but they require a separate high pressure hand pump or electrical high pressure pump to pump up. The hand pump variety takes a long time to fill. These go as high as .50 cal and some custom made ones are apparently good enough for a bear.

The break barrel ones go as high as .30 cal but most are between .177 and .25. Useless as defensive weapons against humans, these are typically effective for hunting squirrels, but even a small pig requires a shot to the medulla for a kill.

Multipump/multishot guns are typically a bit of a joke. Plinking at target practice at best.

The way I see, zeds have no usable organs, so anything less than a big bore PCP is going to be downright useless except as a last resort kiting weapon comparable in effectiveness to a slingshot, though easier to use.

It looks like there's a multimag PR going on somewhere that supersedes the addition of other UPS-like second-ammo features (to simulate the air as a secondary required ammo for the pellets).

Also, "pebbles" would NOT be usable in an air gun. You'd need something like a .22 lead pellet.

So what I recommend:

1. Remove the pneumatic assault rifle, bolt driver, and shotgun.
2. Make one .30 cal rifle like the Hatsan HG130S. This would be the break barrel that just has a longer reload time. Would be about as good as a .22 rifle.
3. Modified version of the Seneca Dragon Claw, .50 cal - bigger tank space to allow for 10 shots instead of 3 per the real life specs. But the gun would be heavier. I suppose since they don't want alternate secondary-ammo solutions, this one would have something a bit simpler - haven't decided the best solution yet that doesn't invade too many files. Probably similar to the dirt accumulation system in gunpowder weapons that is fixed in the mend menu. This one would be about as good as a .223 rifle.

# Screenshots

# Versions and configuration

 - OS: Win7x64
 - Game Version: 0.D-12453-g05940bf
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: None

# Additional context

**Comment by Tamiore** [comment]
I'm really not sure we need to go as far as outright removing these recipes. 
More reasonable first step would be to just make pneumatic weapons NOT auto-learned recipes.
It doesn't really make much sense that normal crossbow requires a book to craft, while much much more advanced in pneumatic bolt driver is somehow auto-learned.

**Comment by eilaattwood** [comment]
> It doesn't really make much sense that normal crossbow requires a book to craft, while much much more advanced pneumatic bolt driver is somehow auto-learned.

That gun is positioned as survivor invention. It has very high requirements already. 8 in mechanics for a bolt driver, if I'm not mistaken. That's a lot. We can assume that survivor that is so good in mechanics, can invent such weapon. And because this weapon didn't exist before Cataclysm, there is no book that can teach that.

**Comment by Tamiore** [comment]
> That gun is positioned as survivor invention. It has very high requirements already. 8 in mechanics for a bolt driver, if I'm not mistaken. That's a lot. We can assume that survivor that is so good in mechanics, can invent such weapon. And because this weapon didn't exist before Cataclysm, there is no book that can teach that.
If a survivor can "invent" a multi-shot pneumatic contraption without a book, why can't the same survivor invent a basic crossbow?
Books don't even necessarily contain complete recipes. They may contain more general information that allows you to come up with a way to craft more advanced items.  
In case of pneumatic weapons, the book would contain general information on design of robust enough pneumatic systems. 
 Btw, under the current skill training system, lvl 8 in mechanics is easy to reach with very basic and easily obtainable equipment and materials. So it's not really acting as any kind of an actual barrier.

**Comment by misterprimus** [comment]
> 
> 
> > It doesn't really make much sense that normal crossbow requires a book to craft, while much much more advanced pneumatic bolt driver is somehow auto-learned.
> 
> That gun is positioned as survivor invention. It has very high requirements already. 8 in mechanics for a bolt driver, if I'm not mistaken. That's a lot. We can assume that survivor that is so good in mechanics, can invent such weapon. And because this weapon didn't exist before Cataclysm, there is no book that can teach that.

If whole businesses with industrial weapons factories couldn't invent a better pneumatic weapon for hundreds of years prior to the cataclysm, it's fair to say the survivor won't be able to build a significantly better one in a couple of months in his van using a DIY forge. That's like a survivor developing a gunpowder twice as good as the smokeless powder we use today using a couple of pots and pans.

**Comment by TechyBen** [comment]
> You're either going to be pumping for a few minutes or you're going to have to go to a REALLY big projectile like a bolt fired out of a really big crossbow.

That seems a more reasonable balance to this. Make the pebble version match realistic stats. Make a big version match the examples on youtube/rubber band crossbow channel (they make these things).

Just because something is not economically or militarily viable, does not mean it's not physically viable. A pneumatic bolt driver will do a lot of damage, but those are hooked up to external gas/pressure vessels/drivers. Even that kind of balance (a pressure vessel similar to the UPS needed for pressure weapons the same way a UPS is needed for energy weapons) would also work as a balance (gameplay mechanic) and realistic (fitting realism) option.

**Comment by misterprimus** [comment]
> > You're either going to be pumping for a few minutes or you're going to have to go to a REALLY big projectile like a bolt fired out of a really big crossbow.
> 
> That seems a more reasonable balance to this (IIRC the pneumatic bolt driver in game _does_ take minutes to pump for 1 single bolt of it's 8 total!). Make the pebble version match realistic stats. Make a big version match the examples on youtube/rubber band crossbow channel (they make these things).
> 
> Just because something is not economically or militarily viable, does not mean it's not physically viable. A pneumatic bolt driver will do a lot of damage, but those are hooked up to external gas/pressure vessels/drivers. Even that kind of balance (a pressure vessel similar to the UPS needed for pressure weapons the same way a UPS is needed for energy weapons) would also work as a balance (gameplay mechanic) and realistic (fitting realism) option.
> 
> The "balance" of current weapons might be due to limiting factors in the game code/abstraction previously, that now can be fully simulated (player "pumping" an internal gas can -> player carrying and refilling an external gas can and using power/vehicles/hand cranks/mechanical devices to repressurise).

Well that WAS how I had it working in my old attempt to have this system, with air cylinders and a compressed air generation system similar to how a UPS works now, but it was scrapped because of some multimag system that's being made. That's why I wanted this next PR to be less ambitious and simpler.

**Comment by Night-Pryanik** [comment]
> Zed takes more damage than it should.

This is way too vague. 

What zed in particular are firing at? Ordinary zombie, armored zombie, kevlar hulk?
What amount of damage do you expect, exactly, in game numbers?
What's your assumption based upon? Some research, tables, graphs? Videos, in the end?

**Comment by misterprimus** [comment]
> > Zed takes more damage than it should.
> 
> This is way too vague.
> 
> What zed in particular are firing at? Ordinary zombie, armored zombie, kevlar hulk?
> What amount of damage do you expect, exactly, in game numbers?
> What's your assumption based upon? Some research, tables, graphs? Videos, in the end?

The typical Zed, I generally kill it in one round of .223 from an M4A1. Sometimes I need 2, let's say 40% of the time. So let's look at the typical .223:
https://www.luckygunner.com/tula-223-ammo-for-sale-223rem55fmjtulablack-1000
55 grain at 3241 fps = 178,255 units of damage

Now let's look at an air rifle:
https://www.sportsmansguide.com/product/index/hatsan-big-bore-carnivore-135-quiet-energy-air-rifle-30-caliber?a=2059966
44.75 grain at 550 fps = 24,612.5 units of damage

Setting aside the idea that damage from heavier, faster rounds is likely geometrically greater than that of smaller & slower rounds, that would mean the typical zed should die from 7.2-14.4 rounds, or on average of about 10 rounds, but likely more given what I discussed above. For example, a .223 will likely go all the way through most zeds IRL (overpenetration) so it can easily damage the structural strength of zed skeletons, whereas much slower rounds will just get stuck in the bones without doing much damage.

**Comment by Amariithynar** [comment]
After going over all the numbers, I actually have to agree  on the change to a pre-charged tank to better reflect how we are pressurizing each shot in the magazine and even te damage reduction, if we're going solely by pre-Cataclysm regulation numbers instead of a post-Cataclysm survivalist's needs.

A single acting pneumatic cylinder with 100 bar (10^5 N/m^2) and full bore diameter of 100 mm (0.1 m) gets 785 N, following the formula F = p π d^2 / 4 ((10^5 N/m^2) π (0.1 m)^2 / 4). Increasing the pressure to a mere 500 bar gives us 3927 N of force. 1 N = 0.225 ft-lbf, and the linked ammo you provide (which is .223 and not 5.56, which is packed for greater force) is 1283 lbf  so the .223 round carries 5,702.2... N of force, or about 33% more N than 500 bar provides for a pneumatic arrangement with such a bore diameter (all calculations provided by https://www.engineeringtoolbox.com/pneumatic-cylinder-force-d_1273.html).

Why do I provide all the information above? To show that it's not that pre-Cataclysm tech CAN'T produce such, that it's not a matter of physics, but that it's a matter of laws and restrictions that prevent manufacturers from creating such. There is even historical precedent in the Girandoni air rifle, used by the Lewis & Clark expedition; the civilian variety was able to fire ~30 shots of .45 before needing its reservoir refilled, and doing so took 1,500 pumps with its low pressure hand pump. There is also the much more modern Talon SS (https://www.pyramydair.com/s/m/AirForce_Talon_SS_PCP_Air_Rifle_Spin_Loc_Tank/135) that is able to, with a mere 206 bar max listed pressure, shoot 65 to 75 shots on its medium power setting (general shooting rather than target shooting), in the just-sub-1000 fps range. There are other, heavier air rifles with greater ranges, but they also have commesurately less shots per before firing; the Escape (https://www.pyramydair.com/s/m/AirForce_Escape_Air_Rifle_Spin_Loc_Tank/3362) fires much higher velocities at each power setting, but many fewer rounds as well, which, according to the manual, means between 5~20 shots depending on power setting before needing a refill, which is far closer to the pneumatic rifle in game.  Why am I using PCP rifles? Because that's what the pneumatic weapons are in game, too. You pre-charge them (abstracted out as the extremely long 6000 moves reload time per individual round) before firing. According to the spec page, the Escape can fire a 21gr pellet up to 1,165 fps with 63.73 ft-lbf, which gives us a rather similar value of 24,465 units of damage as the 44.75 grain air rifle you note above with half the fps of the Escape; it can also shoot a 43.20gr pellet at 1,010 fps with 97.88 ft-lbf, giving a value of 43,632 units of damage; both these units have been calculated the same as you did the above, by multiplying the grains by the velocity, ignoring the energy values.

Granite, the most common type of stone you can find, weighs 2.75 grams per cubic centimeter, and the pebbles in game (as a handful, as per item description) are 50g, so likely about 20 pebbles that you have to sift through to find the exact right size for firing, meaning a single pebble is probably about 2.75g (42.44gr) rather than 5.5g (84.88gr), making the pebble round roughly equivalent to the 43.20gr .25 pellet. 43,632/178,255 = it should be doing about 24.48% of the damage that the .223 round does. According to the item browser, the .223 Remington currently does 44 damage, so a basic pebble should be doing about 10.77 damage at pre-Cataclysm regulation levels for pneumatic weapons.

That means the pneumatic rifle, if it were to be restricted by modern-day laws and regulations, currently does a bit more than 50% more damage than it should be doing (since they say not to exceed a mere 206 bar, or just slightly over 2 kPa, because increased pressure means increased velocity means increased damage). I think it would be a more than fair tradeoff to have refillable air tanks that we can pre-pressurize relatively easily rather than only pressurize on the spot for way too much time per round (it only takes ~10 pumps to get the Benjamin multi-pump (https://www.pyramydair.com/s/m/Benjamin_Variable_Pump_Air_Rifle_Black/4869) to be able to fire a .177 pellet at its maximum 1100 fps, and there are high pressure hand pumps out there that can easily provide ~50 bar per pump; 6000 moves for a single round is too much, even if it were a low pressure pump, as referenced with the Girandoni Air Rifle's setup of 1,500 pumps for ~30 shots) for less damage, with a high-pressure tank variant that gives us way more damage (back to current levels or even above) but requires finding pre-pressurized canisters, finding or making a better compressor than just a hand crank, or a LOT more time to pressurize such tanks by hand (since the only real difference between a low-, medium-, and high-pressure pump is the amount of pressure generated per stroke).

**Comment by misterprimus** [comment]
> 
> 
> After going over all the numbers, I actually have to agree on the change to a pre-charged tank to better reflect how we are pressurizing each shot in the magazine and even the damage reduction, if we're going solely by pre-Cataclysm regulation numbers instead of a post-Cataclysm survivalist's needs.
> 
> A single acting pneumatic cylinder with 100 bar (10^5 N/m^2) and full bore diameter of 100 mm (0.1 m) gets 785 N, following the formula F = p π d^2 / 4 ((10^5 N/m^2) π (0.1 m)^2 / 4). Increasing the pressure to a mere 500 bar gives us 3927 N of force. 1 N = 0.225 ft-lbf, and the linked ammo you provide (which is .223 and not 5.56, which is packed for greater force) is 1283 lbf so the .223 round carries 5,702.2... N of force, or about 33% more N than 500 bar provides for a pneumatic arrangement with such a bore diameter (all calculations provided by https://www.engineeringtoolbox.com/pneumatic-cylinder-force-d_1273.html).
> 
> Why do I provide all the information above? To show that it's not that pre-Cataclysm tech CAN'T produce such, that it's not a matter of physics, but that it's a matter of laws and restrictions that prevent manufacturers from creating such. There is even historical precedent in the Girandoni air rifle, used by the Lewis & Clark expedition; the civilian variety was able to fire about 30 shots of .45 before needing its reservoir refilled, and doing so took 1,500 pumps with its low pressure hand pump. There is also the much more modern Talon SS (https://www.pyramydair.com/s/m/AirForce_Talon_SS_PCP_Air_Rifle_Spin_Loc_Tank/135) that is able to, with a mere 206 bar max listed pressure, shoot 65 to 75 shots on its medium power setting (general shooting rather than target shooting), in the just-sub-1000 fps range. There are other, heavier air rifles with greater ranges, but they also have commesurately less shots per before firing; the Escape (https://www.pyramydair.com/s/m/AirForce_Escape_Air_Rifle_Spin_Loc_Tank/3362) fires much higher velocities at each power setting, but many fewer rounds as well, which, according to the manual, means between 5-20 shots depending on power setting before needing a refill, which is far closer to the pneumatic rifle in game. Why am I using PCP rifles? Because that's what the pneumatic weapons are in game, too. You pre-charge them (abstracted out as the extremely long 6000 moves reload time per individual round) before firing. According to the spec page, the Escape can fire a 21gr pellet up to 1,165 fps with 63.73 ft-lbf, which gives us a rather similar value of 24,465 units of damage as the 44.75 grain air rifle you note above with half the fps of the Escape; it can also shoot a 43.20gr pellet at 1,010 fps with 97.88 ft-lbf, giving a value of 43,632 units of damage; both these units have been calculated the same as you did the above, by multiplying the grains by the velocity, ignoring the energy values.
> 
> Granite, the most common type of stone you can find, weighs 2.75 grams per cubic centimeter, and the pebbles in game (as a handful, as per item description) are 50g, so likely about 20 pebbles that you have to sift through to find the exact right size for firing, meaning a single pebble is probably about 2.75g (42.44gr) rather than 5.5g (84.88gr), making the pebble round roughly equivalent to the 43.20gr .25 pellet. 43,632/178,255 = it should be doing about 24.48% of the damage that the .223 round does. According to the item browser, the .223 Remington currently does 44 damage, so a basic pebble should be doing about 10.77 damage at pre-Cataclysm regulation levels for pneumatic weapons.
> 
> That means the pneumatic rifle, if it were to be restricted by modern-day laws and regulations, currently does a bit more than 50% more damage than it should be doing (since they say not to exceed a mere 206 bar, or just slightly over 2 kPa, because increased pressure means increased velocity means increased damage). I think it would be a more than fair tradeoff to have refillable air tanks that we can pre-pressurize relatively easily rather than only pressurize on the spot for way too much time per round (it only takes about 10 pumps to get the Benjamin multi-pump (https://www.pyramydair.com/s/m/Benjamin_Variable_Pump_Air_Rifle_Black/4869) to be able to fire a .177 pellet at its maximum 1100 fps, and there are high pressure hand pumps out there that can easily provide over 50 bar per pump here's a fairly cheap 4500 PSI hand pump (https://www.youtube.com/watch?v=QC3_xHbRSq4) where the dude does 50 pumps to go from 100 to 150 psi; 6000 moves for a single round is too much, even if it were a low pressure pump, as referenced with the Girandoni Air Rifle's setup of 1,500 pumps with its ancient low pressure pump for ~30 shots) for less damage, with a high-pressure tank variant that gives us way more damage (back to current levels or even above) but requires finding pre-pressurized canisters, finding or making a better compressor than just a hand crank, or a LOT more time to pressurize such tanks by hand (since the only real difference between a low-, medium-, and high-pressure pump is the amount of pressure generated per stroke).

So, it looks like we'd need 2 air rifles to replace the current one. One a weak break-barrel type, and the second a PCP one that's about as strong as the rifle currently is?

**Comment by Amariithynar** [comment]
> So, it looks like we'd need 2 air rifles to replace the current one. One a weak break-barrel type, and the second a PCP one that's about as strong as the rifle currently is?

For the former, not really, unless you want to introduce it as findable loot out in the world, since it's based on pre-Cata restrictions, rather than built according to needs after the Cataclysm. If that's your goal, though, then yeah. Maybe with a conversion kit or process (like with the Multi-Cooker) that allows you to convert it to use a higher pressure pump and tank, too, so you don't have to discard it too quickly, if you don't want to? Should only take about ~300 moves to reload each shot, but if doing so could also cost stamina, that'd be perfect (using those hand pumps uses a fair amount of stamina, so you run out of breath pumping them after awhile).

Not sure how to work the PCP variant; two tanks, one "High Pressure Air Tank" and on "Low Pressure Air Tank", and crafting either takes x pebbles and time dependant on your pressurization capability (like the mortar/quern/food processor speed tree)?

**Comment by misterprimus** [comment]
> > So, it looks like we'd need 2 air rifles to replace the current one. One a weak break-barrel type, and the second a PCP one that's about as strong as the rifle currently is?
> 
> For the former, not really, unless you want to introduce it as findable loot out in the world, since it's based on pre-Cata restrictions, rather than built according to needs after the Cataclysm. If that's your goal, though, then yeah. Maybe with a conversion kit or process (like with the Multi-Cooker) that allows you to convert it to use a higher pressure pump and tank, too, so you don't have to discard it too quickly, if you don't want to? Should only take about ~300 moves to reload each shot, but if doing so could also cost stamina, that'd be perfect (using those hand pumps uses a fair amount of stamina, so you run out of breath pumping them after awhile).
> 
> Not sure how to work the PCP variant; two tanks, one "High Pressure Air Tank" and on "Low Pressure Air Tank", and crafting either takes x pebbles and time dependant on your pressurization capability (like the mortar/quern/food processor speed tree)?

Could you explain what you mean by "pre-Cata restrictions?" There most certainly are (and they are totally legal) air rifles that can take down a deer, but they are typically exclusively PCP. Break-barrel rifles are typically for smaller game. If you look online, break-barrel rifles generally go up to .25 cal with one or two going up to .30 cal. But when you look at PCPs, you get ones that go as high as .50. That, to me, indicates that "pre-Cata restrictions" have nothing to do with it and that it's a matter of a single stroke simply being insufficient to generate enough power to propel a projectile large enough and fast enough to do real damage to a big target.

Also, why are we still using "pebbles?" Loading a jagged rock into your air rifle is going to result in extremely poor performance due to not having a tight seal in the barrel (so air will escape instead of propelling the pebble) and will likely damage the barrel as most rocks have greater hardness than lead or teflon. Air rifles should use specially designed .177/.30/.50 lead pellets, not "pebbles."

**Comment by anothersimulacrum** [comment]
Why are we still using pebbles? Nobody fixed it yet.

**Comment by misterprimus** [comment]
> Why are we still using pebbles? Nobody fixed it yet.

I meant why is he using pebbles in his calculations. Shouldn't we be using .177 pellets or the like?

**Comment by Amariithynar** [comment]
> Could you explain what you mean by "pre-Cata restrictions?" There most certainly are (and they are totally legal) air rifles that can take down a deer, but they are typically exclusively PCP. Break-barrel rifles are typically for smaller game. If you look online, break-barrel rifles generally go up to .25 cal with one or two going up to .30 cal. But when you look at PCPs, you get ones that go as high as .50. That, to me, indicates that "pre-Cata restrictions" have nothing to do with it and that it's a matter of a single stroke simply being insufficient to generate enough power to propel a projectile large enough and fast enough to do real damage to a big target.
> 
> Also, why are we still using "pebbles?" Loading a jagged rock into your air rifle is going to result in extremely poor performance due to not having a tight seal in the barrel (so air will escape instead of propelling the pebble) and will likely damage the barrel as most rocks have greater hardness than lead or teflon. Air rifles should use specially designed .177/.30/.50 lead pellets, not "pebbles."

Yes, there are "Big Bore" rifles that are manufactured to higher potential specs, but that isn't what I'm referring to. There is no federal regulations (as air rifles do not qualify as firearms by the ATF's definitions) but there are many state- and county-level laws that restrict them, either in mandating certain velocities (both minimum and maximum) or what pellet sizes are legal, etc. with some states even treating them as being equivalent to firearms (New York does this, IIRC), while others like Maine state that you can only hunt raccoons with single shot .22LR, and turkey with shotgun or archery only, but other animals like moose aren't specified, and you can use whatever you want to hunt anything that doesn't have a type of gun or caliber specified. Until just a couple years ago, Illinois regulations stated that air rifles had to be under 700 fps or were classified as firearms, so that's what rifles were generally manufactured for sale to, there. All these rules and regulations influence the manufacturers to produce items within the limited specifications of what will be allowed to be sold. 

There's also things like what you just mentioned: Break-barrels being manufactured pretty much only in .177, .22, and .25, with a few in .30, when there's no reason they can't be manufactured in bigger calibers, or with higher velocity/energy output other than they aren't. Heck, there's the gas-operated Crosman Diamondback SBD that offers 1400 fps with .177.

Furthermore, compressors have pressure release valves and regulators specifically designed so you can't exceed regulated pressures, which the compressor is usually unable to exceed anyways because it was built to only compress to a certain pressure tolerance. Industrial-level compressors can get much higher, but they aren't generally for sale to individuals, and especially not for air rifle canister compression, but for industrial air tools. Many compressors are also deliberately limited to only 120~150 PSI because they're meant to be used to fill tires, or other similar low-pressure requirements; industrial level compressors exist that far surpass that, however, as can be seen here: https://catalog.sauerusa.com/item/gh-pressure-gas-compressors-air-cooled-compressors/-to-6000-psi-compressors-air-cooled-tornado-series/wp4325

So, that's what I mean by "Pre-Cata regulations/restrictions". Manufacturers following laws and ordinances to keep their products legal and easy to access and fit to the consumer's use, rather than straight up shooting (heh) for the most power they can get, which is what matters for our purposes post-Cataclysm. The amount of pressure behind each shot is what matters, after all.

As for "Why am I still using pebbles"? For one, because I was doing statistics for the current in-game pneumatic rifle. For two, guns in general, but air rifles specifically, don't need specifically forged pellets to fire. They can make things easier, and for rifled firearms (pistols, rifles, but generally not shotguns, and not air rifles) engage the rifling of the barrel instead of knocking against it (a serious concern) or do more damage (which is why the marble, clay pellet, and bearing exist within the "pebbles" ammo type that you can craft, and all are far superior to the basic pebble with their range and dispersion), but are not strictly necessary. Pebbles also aren't typically jagged, misshapen rocks, but the rounded, smoothed remnants of much larger rocks between 4 to 64 millimetres in diameter, and the item in-game is referred to as a handful, so you're picking out the most appropriate ones from the bunch for ammo and discarding the rest (as I noted above, regarding the weight value of granite per cubic centimetre and the weight of the "pebbles" item). If you want to introduce a .177, .22, and .25 pellet to the "pebbles" ammo catagory that is much better than the basic pebble (which would just be made out of like, 1 piece of lead to multiple pellets, as .223 is much larger and takes 3 lead), sure, but just as a sling can huck a stone with enough force to crack someone's skull, an air rifle can fire a pebble with pretty deadly force. 

Furthermore, simply upping the pressure you fire it with drastically increases the potential damage. because force is mass times acceleration, and, more specifically, you need more pressure pushing the projectile so that it can accelerate to higher speeds, as the ambient pressure pushing in will eventually equalize with the pressure pushing out and prevent further acceleration. That's why we use primers and gunpowder to accelerate bullets in firearms; explosives work incredibly well to build up massive amounts of pressure in the chamber and propel the bullet at very high velocities. If you increase the amount of pressure behind an air rifle shot, it does the same thing, though you still couldn't reach the high instantaneous pressures generated by gunpowder without basically a vehicle mounted industrial air compressor; it's the same principle behind a water jet cutter, at that point. Creating your own high-pressure compressor, or finding one in an industrial setting, would be about the only way you could reach the super-high pressures needed to rival such, but would seriously amp up damage potential.

**Comment by misterprimus** [comment]
> There's also things like what you just mentioned: Break-barrels being manufactured pretty much only in .177, .22, and .25, with a few in .30, when there's no reason they can't be manufactured in bigger calibers, or with higher velocity/energy output other than they aren't.

You haven't really answered my question. You speak of regulations limiting calibers, but PCPs are available in up to .50. You say:
_There's also things like what you just mentioned: Break-barrels being manufactured pretty much only in .177, .22, and .25, with a few in .30, when there's **no reason they can't be manufactured in bigger calibers**, or with higher velocity/energy output other than they aren't._
So you're saying air rifle manufacturers throughout the USA decided not to produce even a single model of commercial/mass-produced break-barrel air rifle in .45+ cal, when there's no physical or legal barriers for doing so, when there would obviously be a market for them as the only big bore air rifle to not need a bulky hand pump? That makes no sense. Clearly there does appear to be a barrier: a physical one and not a legal one, since as we have established, there is no legal barrier to producing such rifles in the PCP style, as they DO that.

Air rifle manufacturers also DO produce air rifles that are illegal in some states, like the Hatsan .30 in NJ (due to sound dampening device). They produce it as long as they can sell it in **enough** states, so I fail to see why they would decide not to make it in a higher caliber just because some state's hunting laws would prevent it from being used (when NJ's TOTAL ban of the .30 didn't prevent it).

I also can't envision your pebble ammunition. Could you show me a video of someone making pebbles out of a rock as easily as our survivor does it and then effectively, accurately, repeatedly, and forcefully firing it from any currently available commercial mass produced air rifle, PCP or otherwise?

**Comment by Amariithynar** [comment]
There is no physical barrier in using a larger slug; they'd just need to invest in better locking mechanisms rather than a single locking lug as most break actions have, as higher pressures can blow them open. Shotguns naturally operate at fairly low pressures, so it's not really a concern for them, which is why break-action shotguns are still quite popular even today, but it is more of an issue for a rifle (smoothbore or otherwise). It's not a physical restriction; you can build it to withstand the pressures easily enough, but they aren't, likely because it's too much effort for too small a niche. They could also fall under various state or county regulations, as I noted, which ARE legal restrictions beyond the federal level, which I also noted. Please read the entire post instead of skimming it for "gotcha"s, especially when they're already answered. I also never said that regulations/restrictions prevent them from making them entirely, but it does form the decisions made for production. OSHA compliance for strict safety reasons means that tanks are rated for much lower pressures than they can actually withstand (in fact the Talon and Escape I mentioned above note their tanks should be filled only to 206 bar, in the manual), even though many can withstand much higher pressures; this is shown by such as this RTI Priest tank test https://www.youtube.com/watch?v=5NRW5w9cZF4 where the tank is rated for only 300 bar (according to the spec sheet of the air rifle), yet when the pressure limiters (regulation valve, pressure release valve, etc) are removed or destroyed (as noted in the description of the video) of the compressor and tank are removed, it can be filled to 800 bar without rupturing just fine.

As for making pebbles from rocks? I agree those aren't reasonable ammunition for use in a pneumatic rifle. Naturally found pebbles are going to be rounded and weathered and good to use in a sling or as a generally smoothened projectile, but not those you get from breaking down rocks. I actually think that that should be changed entirely, so that breaking down rocks should give you "rough pebbles", which shouldn't be usable in pneumatic rifles (only slings or shotguns, due to the nature of shotcanisters), which you should have to put through a rock tumbler (small rotary ones are basically just a tiny motor, 2L metal tank, and a power source of some kind; they don't use much electricity at all, with the average cost for a US household being 13.19 cents per kilowatt hour (kWh) while a tumbler running all day would only be between 6-13 cents a day (https://rocktumbler.com/tips/rock-tumbler-cost/ only look at the Lortone and Thumler's, as the others are vibratory tumblers and don't round the stones as needed), but you need to run them for many weeks to get the final product) with some grit medium (sand would be a fairly good/standard starter grit, but gemstones would actually be the best grit medium to use, and would give the various earrings and necklaces and whatnot that you can find a use). That, or simply only allow bearings and the crafted pellets without making any changes to pebbles at all, if it's deemed as too much work to code all that (which I wouldn't blame anybody for doing). Naturally worn and weathered pebbles are basically just .45 ball shot, with a lot more natural deviation (dispersion, in game mechanic terms), though.

As for the argument for pellets specifically: Do note that smaller airgun pellets are designed specifically to not be able to travel as far as actual bullets, as part of safety regulations (since the legislation covering them is so much more lax than for actual firearms); that's why pellets are shaped the way they are, a shape referred to as "diabolo". They're good for short range accuracy, but their ballistic profile is such that it makes them not as accurate much further past, and they bleed velocity quickly, compared to a bullet in the same caliber (.22 pellet vs .22 bullet, or .25 pellet vs .25 bullet, etc). Interestingly enough, muzzle velocity and energy are pretty similar between a .25 pellet and the .25 ACP handgun round. Big bore projectiles typically aren't designed in the diabolo shape, but in conical forms more reminiscent of actual firearm bullets; they just are propelled at much lower velocities, because that's what the guns are manufactured to. 

As for showing you anyone firing pebbles? No, unfortunately. Air rifle pellets are so inexpensive to buy (you can literally buy 250 count boxes of .177 wadcutters for under $3 USD) that the time and effort of even just scouring through pre-graded bags of pebbles (like fish tank floor medium) for the right size pebbles to fire would take way more effort than just buying them would, plus would be as or more expensive. Just not worthwhile to do, unless you're in a survival scenario. I've simply been going off of their physical properties and how air rifles themselves work; they're basically pneumatic smoothbore rifles, which means they're very similar to shotguns and blunderbusses, which definitely can fire such loads as well.

**Comment by misterprimus** [comment]
> locking

**but they aren't, likely because it's too much effort for too small a niche**
You haven't provided any evidence for this claim or that a survivor would somehow have an easier time making this in the back of a van than they would in a weapons factory.

**OSHA compliance for strict safety reasons means that tanks are rated for much lower pressures**
But they ARE making PCP rifles that DO have high pressures, so this claim also makes no sense.

**which you should have to put through a rock tumbler (small rotary ones are basically just a tiny motor, 2L metal tank, and a power source of some kind**
So I assume you have a video of this procedure being done and then the pebbles being fired by an air rifle effectively? All I see is another revised "idea" with zero evidence to back it up.

**simply only allow bearings and the crafted pellets without making any changes to pebbles at all, if it's deemed as too much work to code all that**
What? Making the rifle use pellets instead of "pebbles" is merely a matter of changing the JSON around. There isn't even any CPP coding involved. Making the PCP air system work is the real work here.

**Do note that smaller airgun pellets are designed specifically to not be able to travel as far as actual bullets**
Doesn't seem very true.
https://www.airgundepot.com/airforce-texan-ss-demolition-ranch-combo.html#AGD-43179113
Grain 158 @ 850 fps

https://www.luckygunner.com/9mm-158-gr-fmj-sub-sonic-fiocchi-50-rounds
https://www.amazon.com/Air-Venturi-Grains-Hollowpoint-Count/dp/B006LLJ29M/
Grain 200 @ 930 fps

You can compare .45 caliber vs .45 caliber and get similar results. I just went by grain since that seems to be the actual weight of the bullet.

What laws are you talking about?

**that the time and effort of even just scouring through pre-graded bags of pebbles (like fish tank floor medium) for the right size pebbles to fire would take way more effort than just buying them would**
People can also easily by professionally made bullets, and yet there are YT videos of people reloading ammo with black gunpowder just to see how it would function. Sorry, not buying it. I think the real issue is you have no evidence to support your beliefs.

I hope I addressed all of your points to your satisfaction this time.

**Comment by EvgenijM86** [comment]
There is a good demonstration of what kind of firepower homemade pneumatic guns can have:

https://www.youtube.com/watch?v=1U7TRDFjnFM

I am pretty sure that should 1-shot most non-evolved zeds.

**Comment by NerosShadow** [comment]
Caselman air submachine gun
https://www.google.com/url?sa=t&source=web&rct=j&url=https://thehomegunsmith.com/CaselmanAPMG.shtml&ved=2ahUKEwiMzezmnK72AhVZoXIEHS9qAuMQFnoECBAQAQ&usg=AOvVaw11-q3eWqR99DZCzyOQ4dXl
