### ISSUE TITLE
Basement Walls Burn Down

### ISSUE THREAD

**Issue by DoonCune** [CleverRaven/Cataclysm-DDA#38252]
Basement walls and floors burn down despite the wiki saying they shouldn't and there being no flammable objects next to the fire.

Set a campfire next to a wall

Basement walls not to burn down

![Screenshot (2)](https://user-images.githubusercontent.com/61366740/75101649-912a0080-55d7-11ea-96a1-e87ebbcb8fd0.png)

 - OS: Windows 10
 - Game Version: 0.D
 - Graphics version: Tiles
 - Ingame language: English 
 - Mods loaded: dda, Filthy Clothing, Extended Realistic Guns, Icecoon's Arsenal. Makeshift Items Mod, Medieval and Historical Content, More Survival Tools, Modular Turrets, Salvaged Robots, More Locations, Fuji's More Buildings. Mapgen Demo, Oa's Additional Buildings Mods, Urban Development, Boats, Folding Parts Pack, Vehicle Additions Pack, Tanks and Other Vehicles, Classes and Scenarios Mod, Stats Through Skills

**Comment by Funguss** [comment]
This seems about right, really. The issue seems to be that the wiki is out of date. That being said, if the floors above don't catch fire then that's a problem, and really we should see the floors above collapsing. I'm not sure how the code for that is going, it's been a long while since I've been in a position like this.
