### ISSUE TITLE
🌶️ Making chilli powder violates conservation of mass 🌶️

### ISSUE THREAD

**Issue by pjf** [CleverRaven/Cataclysm-DDA#38296]
# Describe the bug

- Two chilli peppers weigh 110g, and take up 170ml of volume
- Refined into chilli powder, they weigh 500g, and use 250ml of volume
- Where does the additional 390g of mass come from?

# Steps To Reproduce

1. Find or grow 2×🌶️
1. Turn into chilli powder
1. Observe increased mass

# Expected behavior

Food processors should use *much* more energy if they're able to generate mass on this scale.

# Versions and configuration

585fbbe03d633d760f117c97f26e9b224dccbfc6, Linux

# Additional context

I would fix this myself, but it's not clear what the correct solution would be. Making chilli powder lighter and smaller wouldn't be consistent with other spices, as it inherits from the generic spice item.

Also if 100 units of chilli powder weighs 500g, then some of our cooking recipes are using truly ungodly amounts of chilli.

Maybe just lightening chilli powder is okay, because it's such potent stuff?

**Comment by Funguss** [comment]
Well, having a chilli create _less_ powder seems sensible. I must admit, I never really measure my spices... Is 5g a lot? If so we could probably tone down the quantity of spice in all recipes, therefore changing the spice item might work out at the best solution all round. I know the use rate of pepper has often felt off to me, alongside how rarely you find it. Salt usage also seems a bit OTT.

Also, most of these items don't currently have a nutritional value, which is also off. It would be nice to see some effects from capsaicin in cooking, for instance, and for this to translate into the chemistry changes.

**Comment by jkraybill** [comment]
4 ounces of fresh chillies yields 1oz powder IRL (https://www.chilipeppermadness.com/recipes/cayenne-powder/). I would be in favour of reducing the yield in the game, and decreasing the requirements in recipes that use chili powder.

This probably should be done in conjunction with a review of similar food powders in the game, there are probably similar issues elsewhere.

**Comment by Funguss** [comment]
Aha, that calls for a dehydrator, too. Well, that makes sense. It also exposes one of my pet peeves: most food is lacking in quench value. But that's a much, much bigger problem, and would require thirst being tied to stamina use and a more comprehensive emulation of exertion in general.

I totally agree regarding powders. In this case it could be that whoever wrote the recipe got the numbers backwards, or it's a simple oversight.

**Comment by wapcaplet** [comment]
I have made chili powder for real a few times, and 2 dried peppers won't yield more than a couple spoonfuls of chili powder. Plus, a real chili powder recipe should include a few other seasonings like garlic powder, cumin, and/or paprika (none of which exist in the game yet - though we do have garlic bulbs that I suppose could be dried and processed into garlic powder).

The chili powder weight and units (along with many other spices) are copied the base "spice" class in [data/json/items/classes/comestible.json](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/items/classes/comestible.json), which has 100 charges of 5g each. That's quite a lot of any spice -- 500g of chili powder is about 1 quart, basically one of those [20 oz jugs from Costco](https://www.costcobusinessdelivery.com/mccormick-dark-chili-powder%2C-20-oz.product.10193541.html).

And these 500g of spices fit into 250ml, so their density must be 2g/ml, twice as dense as water. That's some atomic chilly-P! Most real spices (having very little moisture) should have a density considerably less than 1g/ml. Chili powder [is about 0.54g/ml](https://www.aqua-calc.com/calculate/food-volume-to-weight/substance/spices-coma-and-blank-chili-blank-powder). Maybe there's an argument here for simply reducing the overall yield of the generic "spice" class, to somewhere around 100-200g (which is a much more typical weight for the items in my spice cabinet).

At any rate we could use a more realistic chili powder recipe, one requiring a lot more peppers, and at least some garlic.

**Comment by Funguss** [comment]
Just to add to this, one of the reasons (I assume) for having the recipe is for preservation. If we're going to have garlic in the recipe then having dried and smoked chili pepper would be good.

Also... Two singular chilies? That's a ludicrously low amount from one plant! My dad grew some once, tiny little plant but it produced loads of the hottest chilies I've ever eaten. I guess that's nothing new with farming in game right now, though

**Comment by captainego** [comment]
I went to the kitchen and measured the spices in the cabinet that seem to correspond with the types of spices that are in the game. The volume and mass values are from the containers themselves.  The density is calculated.  The "Charge volume" is my attempt to abstract out what a "charge" corresponds to for a given spice.  For spices like chopped dried onion or chili powder I used a US Tablespoon (15mL) as the "charge" since recipes tend to measure these spices in those volumes.  For spices like salt and cayenne pepper I used a US teaspoon (5 mL) as the "charge" since recipes tend to measure spices in those volumes.

Volume (mL) | Mass (g) | Density (g/mL) | Charge volume (mL) | Charge volume | Mass per charge (g) |  
-- | -- | -- | -- | -- | -- | --
1200 | 360 | 0.3 | 15 | 1 Tbsp | 4.5 | chopped dried onion
1200 | 540 | 0.45 | 15 | 1 Tbsp | 6.75 | whole peppercorns
1200 | 700 | 0.583333333 | 15 | 1 Tbsp | 8.75 | powdered garlic
553 | 54 | 0.097649186 | 15 | 1 Tbsp | 1.464737794 | dried oregano
553 | 200 | 0.361663653 | 15 | 1 Tbsp | 5.424954792 | chili powder
1200 | 453 | 0.3775 | 5 | 1 tsp | 1.8875 | cayenne pepper
1750 | 1560 | 0.891428571 | 5 | 1 tsp | 4.457142857 | kosher salt
88 | 39 | 0.443181818 | 5 | 1 tsp | 2.215909091 | dried thyme
88 | 74 | 0.840909091 | 5 | 1 tsp | 4.204545455 | mustard seed
88 | 53 | 0.602272727 | 5 | 1 tsp | 3.011363636 | ground white pepper

The average mass per charge from the table above is 4.26 g/charge.  The volume per charge is either 5 mL or 15 mL.  Based on these results I am proposing that "abstract spices" have a weight of 4g/charge and a volume of 10 mL/charge.  This feels like a reasonable abstraction for the purposes of the game.

Using the proposed values above I am proposing making 2 changes to resolve this issue.  The first change will be to modify the abstract spice entry in items/classes/comestible.json to have a weight of 4g (since the weight is per charge), and a volume of 1000 mL (since the volume is for 100 charges).

The second change will be to modify the recipe for chili powder (chilly_p) such that it takes 2 minutes and 11 seconds to create 1 charge of chili powder, and that the batch factor is 95% at 10 charges.  This results in the crafting time for 50 charges changing from 11 minutes 15 seconds to 11 minutes 20 seconds.  It also has the side effect of requiring 1 chili pepper to make 1 charge of chili powder, which resolves the conservation of mass issue described in this issue.

All spices now take up more volume, but I feel that the volume required is much more representative of the average volume required for spices.  Spice drops in the state which they appear in the world (100 units of spice in a plastic bag) still fit in their container.

**Comment by captainego** [comment]
@Maleclypse found a useful web resource https://www.aqua-calc.com/calculate/food-volume-to-weight.  Using aqua-calc as a resource I redid the table that I posted previously with a wider range of spices.  Here are the results:

Volume (mL) | Mass (g) | Density (g/mL) | Charge volume (mL) | Charge volume | Mass per charge (g) | Spice
-- | -- | -- | -- | -- | -- | --
1000 | 527.5 | 0.5275 | 5 | 1 tsp | 2.6375 | cinnamon web
1000 | 466.63 | 0.46663 | 5 | 1 tsp | 2.33315 | ground black pepper
1000 | 1217.3 | 1.2173 | 5 | 1 tsp | 6.0865 | table salt
1000 | 365.19 | 0.36519 | 5 | 1 tsp | 1.82595 | oregano
1000 | 541 | 0.541 | 15 | 1 Tbsp | 8.115 | chili powder
1000 | 358.43 | 0.35843 | 5 | 1 tsp | 1.79215 | cayenne pepper
1000 | 101.44 | 0.10144 | 15 | 1 Tbsp | 1.5216 | basil
1000 | 135.26 | 0.13526 | 15 | 1 Tbsp | 2.0289 | sage
1000 | 655.99 | 0.65599 | 15 | 1 Tbsp | 9.83985 | garlic
1000 | 290.8 | 0.2908 | 15 | 1 Tbsp | 4.362 | thyme
1000 | 1052.46 | 1.05246 | 5 | 1 tsp | 5.2623 | mustard

This analysis provides a slightly different outcome of 4.16 grams per charge (my original analysis had 4.26).
