### ISSUE TITLE
Magiclysm, rework XP system to make more sense and be more intuitive

### ISSUE THREAD

**Issue by AncientSion** [CleverRaven/Cataclysm-DDA#38304]
I talked about this on the cord and it was suggested to make an issue so it could be tagged for later.

Current system is:
Read a book or a scroll and learn a spell.

Casting a learned spell yields very, very little XP. So little in fact, that it would take a large amount of casts to level up a spell. So in practive, if you wanted to level up a spell, you have to study the book or scroll since leveling it up by casting would require hundreds (!) of successful attempts.

My suggestion would be to change this so that the vast majority of spell xp is gained by casting instead of being wholy dependant on studying.
As a simple, easy fix i would suggest to increase the XP gained by casting by a factor of ten. Yes, yes. And even that might actually be too little of increase to naturally level spells (keep note that spells range from up to level 20 to 30).

Another way would be keep the current spell XP gain values, but modify them by your spellcasting main skill, i.e. your gain would be modified by your general expertise.
For example, if you cast a spell and gain say 135 XP right now, as a fix this value would be modified by twice your spellcraft. So for example at Spellcraft 3, the XP gain would be 135*(3*2).

Im sort of hoping this change (aiming for the former one since its way easier and more initutiv) could make spontaniously ? (thinking this is a would be one liner in regards to code, might be wrong) :)

**Comment by KorGgenT** [comment]
> My suggestion would be to change this so that the vast majority of spell xp is gained by casting instead of being wholy dependant on studying.

This isn't going to happen. 

I'll consider making a "practice" action though. Spells are _supposed_ to take forever to get to max level. You aren't supposed to just crawl into a basement with some food and come out a god.

**Comment by AncientSion** [comment]
Ok, thats fine. So unlike mechanics, cooking and rifles you cant level in your cellar. Does that make sense ? A bigly YES.
But we arent talking about max level here. We are talking about the fact that leveling from 0 to 1 (**which is the equivalent of leveling from 0 to 0.3** on a normal skill) is (almost impossible) using the spellcast action.
We talked about it on the cord, just had to leave this last point here again.

**Comment by KorGgenT** [comment]
if you successfully cast a spell at level zero, it levels it up to 1.

**Comment by AncientSion** [comment]
Well, thats my bad, So my argument is only valid for anything but level 0-1. sorry.

**Comment by Funguss** [comment]
Well, I've never bothered to get a spell to max, but I must say that studying a spell levels up spellcrafting a hell of a lot faster than reading any skill book does. I do believe half an hour of study grants enough experience to get up to level one in spellcrafting more than five times over? I forget. I play with 0.1x skill gain and experience for spellcraft feels like traveling on a rocket after having a long, slow walk through the countryside.

Regarding spell levels, I'm pretty sure on a build a few days ago I got up to level five on light cue wounds within the span of a few days. That seems fast to me, but as I say, I'm used to a slog. Nothing else comes close to level five that easily, even getting to level one takes days if you rely on reading.

**Comment by AncientSion** [comment]
Is that with studying the scroll / book or actual spell casting ? Pretty sure its the former.

**Comment by Funguss** [comment]
Studying sorry, yes.

**Comment by KorGgenT** [comment]
i'd actually say @Funguss that should qualify as a feature request that spell xp scales with the skill learning multiplier.

**Comment by Funguss** [comment]
Oh, it doesn't? I was just making an observation really, I think if it was reduced by a factor of ten I'd likely never see a spell level up! Studying computers takes up all the reading time I can stand, and I wonder if I'll ever be getting to the control laptop I aim for.

Spellcrafting is what concerns me, really. Climbing the levels so fast feels really at odds with my other skills. Also, it seems that you could (theoretically, maybe not practicably) get to level ten with five spells learned, maybe less, and without reaching a substantial level on any of said spells. Not that I've tested this, mind you; I rarely get to midgame without finding a reason to start afresh.

**Comment by foulman** [comment]
This is why I went with an alternative method of leveling up spellcraft, it's a little too easy to advance it in a day or two of reading books or what have you when it should take significant effort and practice.

**Comment by foulman** [comment]
Also, you are unable to 'practice' some spells in the way that you can practice throwing weapons, many spells will only target a live enemy, such as magic missile, you can't even cast it at a target as you could with throwing or archery. Casting spells before you go to sleep at night isn't so bad, you can burn through a bunch of mana and have it all back in the morning.

**Comment by AncientSion** [comment]
Why would it be significantly harder to learn "Spellcraft" than learning "Dodge" or learning "Fabrication" or learning "Cooking" ? You can can go from building an antenna to building a remotely controlled drone in a matter of days in regards to the game and you dont complain there either.

Spellcraft by itself does literally nothing. Spells become "useful" when you level them, but lvl 10 spellcraft and level 1 frostspray wont give you anything worth using for the most part.

In my opinion, spellcraft as a mainline skill is alright. Whats bothering is the specific spell levels.

**Comment by foulman** [comment]
Because you're learning magic theory, and much like you can't pick up a Ph.D. in Physics in a week, you shouldn't be able to pick up how to manipulate the fabric of the universe and create things out of thin air in a week.
Spellcraft significantly affects your spell failure rates, IIRC, more so than even Int.
Assuming you don't want to blow spell casting left and right, or want to be able to use powerful (high difficulty) spells, you need a high spellcraft. If that frostspray spell fails 70% of the time, you might not live long enough to get it to level 2, which you should be able to do in a day or so just from casting it.

Pointing out that there is a significant issue with skill leveling in this game does not justify something else, skills being too easy to pick up are a known issue and there are plans to work on and eventually replace it. I addressed it for spellcraft because I could and it didn't break anything, it gives me tight control over how fast the player advances with their "spell" ability.

**Comment by Funguss** [comment]
@AncientSion to add to what Foulman said, the issue I mentioned is that spellcraft is significantly faster to train than anything else, not that it should be harder. As I also said, I play with 0.1x skill gain, which makes the speed of gain especially noticeable. It is impossible to do what you just described without some serious dedication, and even then I expect it to take something close to a month.

Looking back on my save, though, it seems I got the numbers mixed up. Spellcraft was nearly level three while bless had reached level four and light cure wounds was at level five. Half an hour study resulted in 3% spellcraft gain. Survival, also at level two, also went up by 3% over half an hour study of Through The Lens. This is all with the Fast Reader trait, mind you, so I'm not sure if that has an impact.

I think I expected there to be more of a difference due to the rapid growth from 0 to 1 spellcraft. Personally, I'd like to see learning a new school have a mechanism like martial arts, and for taking your first steps (without tutoring from an NPC) to be very difficult and time consuming.

**Comment by AncientSion** [comment]
> Pointing out that there is a significant issue with skill leveling in this game does not justify something else, skills being too easy to pick up are a known issue and there are plans to work on and eventually replace it. I addressed it for spellcraft because I could and it didn't break anything, it gives me tight control over how fast the player advances with their "spell" ability.

Its about coherence. By itself learning "spellcraft" is neither easier nor harder than learning electronics. Again i can go from building an antenna to building a UAV within 2 weeks in the game. Why would it be any different from kindling a fire with my finger than calling down a meteor strike. Both examples suggest the same, going from being a scrub to being a professional. 
I dont see anyway why you learning  magic should be significantly harder than learning chemics, learning physics or turning into a martial arts superhero.

Spellcraft  is NOT significantly faster to train than anything else. That is just plain out wrong. If you take skill gain modifiers into account its another issue, but that one would be bug and it out of scope of this discussion whatsoever.

And yes, Spellcraft impacts spell failure chance, but thats it. It does not effect the scaling of spells whatsoever. Only spell level (which is unique per spell, which is a significant disadvantage) affects the effects of a spell.
Compare that to Rifles, where one Skill (and Marksman) effects EVERY rifle.

**Comment by Funguss** [comment]
Meh, I don't think it's really worth getting this worked up about. But yes, getting to level one in spellcraft literally takes half an hour without modified skill gain, which does suggest that there's something odd going on with the experience gain in general. If you're going to say this is not the case then go and try it.

I don't know what you mean by drawing a parallel between weapon skills and spellcraft. They all seem to work on the same principle to me, save that weapon skills (apparently) add a small increase in damage.  As spells don't have accuracy (not ideal in my opinion) having a lower failure rate makes sense.

If I understand you correctly your concern is that skill gain from spells should be faster, and the only support for this is based on how fast it is to amass levels in skills currently. Using the current skill system as a reference point is a really bad move as (correct me if I'm wrong) it hasn't changed in any significant way since Whales abandoned Cataclysm. It needs work, and from what I understand there will come a point where getting to professional levels of skill within a few days or weeks will no longer be a thing. Please bear in mind that this game is under active development so any and all mechanics are subject to change.

That said, I see no reason why it shouldn't be harder to master an individual spell compared to learning how to install an engine on a car. What magic is and what laws govern it are all absolute fantasy and the domain of the author. Magic could be as easy a breathing or be the equivalent of lighting a match with your mind after spending fifty years in meditation. If this system of magic doesn't agree with you then that's all there is to it.

That's the last I'll say on those points. Please see the bottom of [this](https://github.com/CleverRaven/Cataclysm-DDA/wiki/Frequently-Made-Suggestions) document, specifically failed rationalizations. We could go around in circles on the point of "x therefore y" ad infinitum, which doesn't really help the situation.

Your initial suggestion is great, and I agree with it. Having a way to practice individual spells would be nice. The rest of your suggestions I'd need to think more about, but instead I've been thinking about all this other stuff. My gut reaction is that the issue doesn't lie with the balance of skill growth but that the maximum level makes it seem like a target. I doubt there's any real benefit to increasing the levels of most spells to maximum, even if it was significantly easier.

In fact, I think having three or five levels would do it, and the levels themselves could have thresholds barring their growth. Having x amount of spells for example, or having spent y amount of time on theory with z amount of experimentation. Once one or two thresholds have cleared you start to have a minuscule chance of leveling up on action and research minute (0.01% maybe?) and once all three are cleared that goes up (maybe 0.05% o 0.1%). Just throwing those figures out there, please don't analyze them.

**Comment by foulman** [comment]
> And yes, Spellcraft impacts spell failure chance, but thats it. It does not effect the scaling of spells whatsoever. Only spell level (which is unique per spell, which is a significant disadvantage) affects the effects of a spell.
> Compare that to Rifles, where one Skill (and Marksman) effects EVERY rifle.

That is true, it does not, and while I wanted spellcraft to do more, it does not, and likely never will. 
Given the choice, I would have it doing more, like affecting mana regen, or mana pool size, in fact I proposed a feature request recently to bring about things of that nature. Nobody even bothered to comment on it.
That is not to say that spellcraft **couldn't do more**, because I could whip up a staff that shoots fire and uses the spellcraft skill to aim, just like the rifle skill does, and that would take a minute or two, and I have considered doing so.

**Comment by foulman** [comment]
> 
> 
> Meh, I don't think it's really worth getting this worked up about. But yes, getting to level one in spellcraft literally takes half an hour without modified skill gain, which does suggest that there's something odd going on with the experience gain in general. If you're going to say this is not the case then go and try it.
> 
> I don't know what you mean by drawing a parallel between weapon skills and spellcraft. They all seem to work on the same principle to me, save that weapon skills (apparently) add a small increase in damage. As spells don't have accuracy (not ideal in my opinion) having a lower failure rate makes sense.
>
 
I agree with wanting the ability for spells to miss, I always did.

> If I understand you correctly your concern is that skill gain from spells should be faster, and the only support for this is based on how fast it is to amass levels in skills currently. Using the current skill system as a reference point is a really bad move as (correct me if I'm wrong) it hasn't changed in any significant way since Whales abandoned Cataclysm. It needs work, and from what I understand there will come a point where getting to professional levels of skill within a few days or weeks will no longer be a thing. Please bear in mind that this game is under active development so any and all mechanics are subject to change.
> 

Indeed, I would love for the whole spell xp/spellcraft gain system to be un-hardcoded and JSON-ized, because I have the same issue with it. It was intended for a very specific concept of how magic should work.

And yes, I don't want to see it just lump changed by some multiplier as suggested by AncientSion because the skill system is a known issue, planning to go along with it as is would be a mistake, as you'd have to change it again when the core system is revamped. Flexibility is always better.

> Your initial suggestion is great, and I agree with it. Having a way to practice individual spells would be nice. The rest of your suggestions I'd need to think more about, but instead I've been thinking about all this other stuff. My gut reaction is that the issue doesn't lie with the balance of skill growth but that the maximum level makes it seem like a target. I doubt there's any real benefit to increasing the levels of most spells to maximum, even if it was significantly easier.
>

I also support _practicing_ spells or magic in general, I always have, spell learning was a step towards exactly that kind of idea, that you could learn and develop your magic by using it, rather than just out of books or scrolls. This is not something that is used in Magiclysm though, despite being a feature. My current work uses crafting to accomplish a more controlled and gradual increase in spellcraft to _simulate_ practicing your abilities, it also allows me to reward the player for that practice in a direct way that increases their abilities commensurate with their knowledge/experience.

**Comment by kevingranade** [comment]
@foulman the entirety of https://github.com/CleverRaven/Cataclysm-DDA/issues/38304#issuecomment-590916408 is off-topic griping. Please stay on topic, and complaining about decisions people have made is never on topic.
