### ISSUE TITLE
Bipods need rework

### ISSUE THREAD

**Issue by SirPendrak** [CleverRaven/Cataclysm-DDA#38435]
# Is your feature request related to a problem? Please describe.

Currently bipods have theese flaws: 

1. They only reduce recoil while not helping in any way to make the first shot more accurate. Obvoiusly bipod is not affecting weapon's and ammo dispersion, but it reduces the human error by a LOT. Maybe it should reduce the gun operator's disspersion by half when bipod is used while leaving gun and ammo ballistic the same. Isnt that one fancy targetting system CBM doing something similar already? Welp, cant read the code, but maybe its code can be borrowed, and increased from 33% to 50% reduction, if it is working the way i think it is. If targeting system CBM reduces not only human error, but gun's disperion as well, then it needes to be changed. 

2. You can use bipods only near very speciffic terrain, furniture or vehicles. I believe author of #38299 wanted to add prone stance at some point. See #37866. So this should be resolved somewhere in the future. 

3. If you modd your weapon with bipod, then you have to allways loose some time when wielding it due to additional unfolding time. This makes bipod much less appealing because right now they are more likely to put you in danger that help you survive a fight. Ideally, a gun with bipod would get additional possible action when (a)ctivating said wielded gun. It would be "use bipod and go prone if needed". So if you are preparing to make that perfect sniper shot, you would have time to unfold it, and lay prone, and ammount of keypresses wouldnt be too overwhelming for ocassional precise shots. And when you dont need super precise shots, jus regular relativelly precise shots, then bipod would not be soo annoying, only increase weapons volume by tiny bit. 

# Describe the solution you'd like
Everything written above. One thing to mention is that bipods descrieption should inform the player about how it works. 

# Describe alternatives you've considered
Leave everything as it is now. So every player will dismount every bipod from every weapon they find.

**Comment by kholat** [comment]
I think theres an underlying problem here. 
There should perhaps eventually be some kind of "weapon is stabilized" flag. Right now the "mountable" flag kinda attempts to achieve that, but you can kinda stabilize your gun IRL when kneeling by putting your elbow on your knee already; or for instance put a hand on a doorframe and your gun on the hand etc. 

Until this is somehow simulated in the game i dont see the bipod being "useful" as in actually using it on a 24/7 gun, however if you carry an entrenching tool you can create mounds and just sit on them for clearing hordes, it really does help. This way you just create a few "fall back" points, as you go towards a town, then shoot your way back. Step on a mound, keep shooting till zombies are too close, run back to the other mound you made some tiles away within running distance, repeat.

Im only commenting because I know there were PRs before when people wanted bipods to work in adjacent tiles etc etc and it all flopped. I imagine all this will do is add more button presses and the end result will be you just use a forward grip or nothing. I think this really needs some big thinking time and supporting underlying mechanics like idk "you stabilize your weapon and assume a shooting stance" action when at/near appropriate terrain but itll take more then a few comments to think of something good IMO.

**Comment by ymber** [comment]
Related to #23169. Infrastructure for improving bipods was part of that implementation.
