### ISSUE TITLE
Improving "climbling downspouts"

### ISSUE THREAD

**Issue by AncientSion** [CleverRaven/Cataclysm-DDA#38472]
Climing on roofs is fine and fun and cool, but also very abuseable ATM.

I suggest the following:

When you climb up, you need to pass a check to see if u actually manage to get up the pipe and manage to get over the copper ledge.
Factors involved in check
- dex
- str
- arm/leg/torso enc

If you are obese or overweight, very harsh penalities should be applied to indicate the increased risk of breaking the thingies that hold the pipe and you crashing down, possibly destroying the pipe (or copper ledge) in question.

In addition, i suggest that each climb has a fixed stamina cost to be paid in advance. Something like 2 to 3 stamina bars are required to initiate a climb. Possible adjusted by PC weight.

Right now you can run from Zs and safely climb any pipe even if you technically are at 0 stamina. This is very abusable and breaks immersion.
You can do this even if you are overweight and have the flu.

p.s. i love when i find 2 or 3 level buildings and use my binos to see aaaall the things.

**Comment by Funguss** [comment]
Eh, it shouldn't be a flat amount of stamina, it should really depend on your overall weight and ability. The specifics are going to need a bit of research I think; I have no idea how feasible it is to actually climb using drainpipes, here it's all plastic.

In an ideal scenario, where you have good foot holds, it shouldn't really be any tougher than climbing a ladder. The burn comes when you're pulling yourself up with your hands or overstretching your legs as you're using muscles that aren't built for pushing your whole body vertically. 

Found this which might be useful to get an idea on climbing solid drainpipes: http://insectnation.org/nightclimbing/nightclimbersofcam/html/c132.html

**Comment by sharkfinsouperman** [comment]
> Eh, it shouldn't be a flat amount of stamina, it should really depend on your overall weight and ability.

I think the parkour trait may come into play here, too.

> In an ideal scenario, where you have good foot holds, it shouldn't really be any tougher than climbing a ladder.

I used to rock climb in my younger days and practiced intown by scaling buildings, and I agree with you. If you have the upper body strength, climbing to roofs is extremely simple, and a secure drainpipe is nearly as easy as a ladder.

Perhaps climbing drain pipes could have a chance of coming free and causing a fall, destroying them in the process? They aren't secured for climbing, they're secure to keep them in place.

**Comment by Funguss** [comment]
> parkour
I thought it went without saying. :laughing: 

> I used to rock climb in my younger days
Cool, me too! :grin: I wasn't enough of a rebel to try it around town, plus everywhere was red brick multistory terrace with no garden to speak of. It's nice to hear that my speculation was on point.

I've never been a fan of straight gambling. The way I'd calculate detachment is by keeping a damage level and having unskilled and heavy characters stand scaling chances of damaging it further with each attempt. Randomise the damage level when the pipe is spawned, stop it from being a Z magnet (I've never really understood the logic behind them trashing random furniture) and give a warning message when over the safety threshold for characters with related skills or traits (dodge, parkour, fabrication).

On top of this I'd give small and skinny characters buffs to success and damage chance, and maybe some specific bonus for certain mutations or mutation trees. Rats and mice are known for using them, after all.

**Comment by AdamLyon** [comment]
I've been thinking about this recently, and agree that the current downspout climbing implementation, at least on houses, feels wrong.

In the US, at least in my experience, the downspouts and rain gutters on any sub-50 year old (and often older) residential house are very thin metal (typically aluminum?) or plastic, are modular pieces which just shove into each other and can be easily pulled apart by hand, are only weakly secured to the wall with equally thin brackets, and in no way could hold an adult's weight. Like this: https://www.homedepot.com/p/Amerimax-Home-Products-2-in-x-3-in-x-120-in-White-Vinyl-Downspout-M0593/100095267 (The rain gutters themselves tend to be anchored a little better, but I wouldn't want to hang off of one either. :) )

Everything beyond a single family home tends to have the thicker round metal pipe versions that would be actually climbable and are securely bolted to the wall. My suggestions are:

1. Make downspouts on standalone houses have a (relatively high) chance at breaking when attempting to climb up them. As noted above, weight, stats, stamina, perks, etc could all play into it, or it could be a simple dice roll. This doesn't have to cause damage, but some noise makes sense. Once broken, they cannot be repaired. Climbing DOWN a downspout would nearly always break it. These type of drainpipes would be named differently, such as "unstable downspout", "vinyl downspout", "thin aluminum downspout" or something else to obviously separate them from the actual "metal pipe" variants (which wouldn't need a modifier for the name). ("Thin aluminum downspout" would make sense if it gave a couple scrap metal upon breaking. Or plastic chunks for a "vinyl downspout".) We don't need both a metal and a plastic version, just whichever one makes the most sense from a balance perspective to have extra scrap from.

2. As a balance to that, whenever there's a climbable fence touching a building, give an option to climb to the roof from there. We'd have to identify where the fence below you is when you're on said roof, but this much more realistic, IMO.

**Comment by Funguss** [comment]
I think the pipe you linked to is the kind I've actually witnessed, on two occasions and to my complete disbelief, someone successfully climb without any obvious damage to themselves or the pipe. I honestly think we need some expert opinion here from some urban climbing forum or something, as I doubt there's studies on how sturdy various pipes are for climbing.

On the note of fences, in most cases where they join a wall you can climb up already. You require five adjacent tiles with some flags I'm not certain on. Still, that would be a nice bonus on rare occasions.

**Comment by Mooses2k** [comment]
Bump. This, along with OP unicycles was something that's been feeling wrong in recent games of mine. I did a little research on this but didn't come up with much. This climbing is known as 'buildering' (like bouldering). I learned how to stop racoons from climbing up my downspouts though!

Seriously, how much research is needed? Just give it a chance to fail with a break and fall based on STR, DEX, torso/arm/hand enc, parkour perk. Yes, there are differences between home and larger building drainspouts, but something good enough is better than the current status quo.

**Comment by Night-Pryanik** [comment]
This is partially addressed by #39635. At least now you could slip down when climbing the downspout.

**Comment by Ofthefog** [comment]
I happen to be an urban climber who has experience in Texas and a touch of New Jersey, so I think I can add on here.

There are 2 main downspouts i've seen.

![Screenshot from 2020-05-09 21-07-21](https://user-images.githubusercontent.com/14334907/81482733-81ff3a00-9239-11ea-8594-0c5a13926adf.png)

Like this.

![Screenshot from 2020-05-09 21-09-27](https://user-images.githubusercontent.com/14334907/81482751-9e9b7200-9239-11ea-99c1-0bf460cf7ae6.png)

And like that.

The second type is much preferred. The way that one is climbed is by pulling away from the walls with your hands, and pushing towards the wall with your feet. The feet can hook into the cracks between the bricks are other protrusions to help, and these metal pipes are affixed quite well.

The first one is still possible to climb, often, but it requires another technique. You must put both of your hands and feet towards one another, such that the force is concentrated on the inside of the downspout. This is much harder because often your fingers cannot go all the way around the construct, but it redistributes the weight in such a way that it doesn't all focus on pulling out the flimsy bolts. 

I weigh around 60kg, so take this with a grain of salt, but you will be surprised about what structures can hold you, including being jumped down onto. Even some gutter systems are strong enough to hang from but this is far from the majority. Really only complexes like well funded schools have those strong and layered metal ones, otherwise they will absolutely break.

**Comment by Ofthefog** [comment]
This issue can be used as an opportunity now that I think about it.
My impression is that z levels and vertical movement is in its infancy, so a rework and some integration could be worth doing. 

Perhaps a greater movement skill that unites the "you try to keep your balance" vaulting from the parkour profession, climbing, and perhaps swimming? I'll develop that further in its own issue because I think it has potential.
