### ISSUE TITLE
Segmentation fault at a random spot

### ISSUE THREAD

**Issue by Hyperseeker** [CleverRaven/Cataclysm-DDA#38488]
# Describe the bug

SEGFAULT after running down the road. Nothing crazy was being done, no experimental mods were loaded.

# Steps To Reproduce

1. Load the attached save.
2. Go down the discovered road to the east, and follow it until the undiscovered area.
3. Proceed down the road.
4. (Optional) Get hit by a moose while auto-moving.
5. (Optional) Proceed to run the hell away from it down the same road.
6. SEGFAULT

# Expected behavior

I want to be able to finally run away from that moose. :(

# Versions and configuration

 - OS: Windows 10 Enterprise LTSC, version 1809, build 17763.292
 - Game Version: 0.D-12723-g120749f
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded:
```
[
  "dda",
  "cityside",
  "alt_map_key",
  "classic_zombies",
  "no_npc_food",
  "QuickStart",
  "StatsThroughSkills",
  "Nonperishable_Overhaul"
]
```

# Additional context

[crash+debug.log.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4271675/crash%2Bdebug.log.zip)

[bug report savegame March 1 2020.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4271678/bug.report.savegame.March.1.2020.zip)

This is empirical, but I get a sense that these appear due to RAM capacity issues. I'm playing on a laptop with 4GB of RAM total. If I don't free up RAM before the game – e.g. by closing Chromium – I get SEGFAULT sooner. Not always, but chances are good.

This has been an issue for a while and seemed to have waxed and waned throughout multiple playthroughs, with different game builds, loaded mods, and in-game actions.

**Comment by AMurkin** [comment]
> no experimental mods were loaded

\src\game.cpp:2791 [load_packs] unknown content cityside
\src\game.cpp:2791 [load_packs] unknown content QuickStart
\src\game.cpp:2791 [load_packs] unknown content Nonperishable_Overhaul

What about these?

**Comment by Funguss** [comment]
The real bug is that you lived.

**Comment by FirebrandCoding** [comment]
`Nonperishable_Overhaul` is [mod of the same name](https://github.com/chaosvolt/CDDA_Nonperishable_Overhaul) by chaosvolt. Only modifies a handful of items. Never caused an issue.

`QuickStart` is [Back in the Saddle](https://discourse.cataclysmdda.org/t/back-in-the-saddle-a-simple-quick-start-mod/20008) by Esther. Not mainlined, but only adds professions that I never used.

`cityside` is [More City Locations](https://github.com/nornagon/cdda-more-city-locations) by nornagon. I assumed it was a mainline mod 'cause all the rest of them got axed recently, but no: I had to download that one, probably through the launcher. Considering SEGFAULT happened when I was approaching a city... yes, this might be our culprit.

But then: a SEGFAULT?

**Comment by AncientSion** [comment]
I also get random segvaults always when driving overworld and im not running any mods.

**Comment by Qrox** [comment]
Your crash log says it's not able to get the base address of the game process, and because of this it doesn't contain a readable backtrace. This might mean when your game crashed it's in a worse state than most common segfaults. Anyway, without a readable backtrace it's hard to say what caused the crash.

**Comment by FirebrandCoding** [comment]
Anything I can do to improve readability of the issue?

**Comment by Qrox** [comment]
If you know how to use gdb you may run the game in gdb and try get a usable backtrace?

**Comment by ZhilkinSerg** [comment]
> 
> 
> If you know how to use gdb you may run the game in gdb and try get a usable backtrace?

gdb won't work for cross-compiled Windows binary probably.

**Comment by Fris0uman** [comment]
This is tangential to the issue but we can't use save that contain third party mods, nobody has time to go chase down mods just to be able to load the save. So it would help if you could reproduce the issue without those mods.

**Comment by FirebrandCoding** [comment]
> we can't use save that contain third party mod

What's stopping you?

**Comment by Night-Pryanik** [comment]
> What's stopping you?

The need to find and download the mod.

**Comment by FirebrandCoding** [comment]
This would've been somewhat more appropriate if I hadn't linked to every non-repo mod used in the save at the first request.

The solution to this particular problem is that you don't have to help. If you don't have the time to read through the thread and see that every single non-repo mod has already been linked to, I expect you also don't have the time to be meticulous with the testing, given that both actions take about the same amount of time.

It's not even that the suggestion is bad. *Of course* it's better to eliminate as many variables as possible. It's the indignant tone of the original comment on the matter suggesting the problem is too tedious to work with. Nevermind that in modular applications you want to make sure that the modules neither conflict nor elicit an error. Nevermind also that this is the exact setting the problem has occurred in: changing the variables *may* end up changing the outcome, but *maybe* the setting is what's causing the problem. One could never know until they test both.

For the record, even an empty world – nothing outside of the base game, not even the default NPC needs mod – causes segmentation faults after a bit of play. That would be the fifth world I tested this in.

*Please* don't suggest I'm not being diligent or I'm doing it wrong somehow. This error is not just a side bug I can forget about: this disables me from playing the game properly. I would eagerly provide all the assistance I can, given that it's within my means. I know testing can be a difficult and tedious process, but going so far as to suggest that testing is meaningless until the right bug is presented is beyond any inculpability.

**Comment by Funguss** [comment]
Please do take a step back and consider the discussion here. You're obviously upset, but Fris0uman's comment wasn't meant as an attack. Nobody suggested that testing is meaningless, all I see is people saying they won't. Nobody here owes anybody anything, so expecting someone to go out of their way to download unsupported mods to examine an issue which, given previously available information, may be due to said mods, is a bit much. Fris0uman may have been speaking loosely with "chasing down mods", but the point was that external mods may have caused this and the overhead involved with external mods will put most people off, even if the bug is obviously in the base game. There may be no reason for the mod to cause the issue, but that's not going to persuade most people to examine the mod to confirm this or download it on faith.

If you can reproduce this without mods then it would be more helpful to post a save without the mods and detail how to make this reproducible.

And  just to reiterate an important point: Everybody is spending their time on something. If they spend that time hunting down one inadequately reported bug, that's time they could have spent fixing well documented bugs. This is basic division of labor, and if you're posting issues it's in your best interest to make it as thorough and easy to identify as possible. In that spirit it would have been a great idea to update the issue description or comment as soon as you had more information.

**Comment by anothersimulacrum** [comment]
The game can load mods from `/save/worldname/mods`.
It's polite to put third party mods there when you are using them on a world.

**Comment by latogato** [comment]
I got seg fault once in the last week when i left the road to explore an unknown part of the map. My only comment is i don't think it is about the size of the memory, my pc has 16GB and still happened.

**Comment by dsmky117** [comment]
I was able to reproduce with no third party mods. In fact, creating a world with large cities and just debug teleporting into the middle of it seems to nearly always segfault on 10702. Maybe some item entering the reality bubble is the cause, but I'm not sure how to figure out what.

[Supercity.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4692180/Supercity.zip)

[crash + debug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4692183/crash.%2B.debug.zip)

### Steps to Reproduce
1. Load the attached save. Get an error message, maybe related:
![image](https://user-images.githubusercontent.com/19257672/83079446-ded85e00-a049-11ea-9aec-1bc71ac8062f.png)

2. Take 1 step south and get SIGSEGV.

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-2570-gb8bc6f1 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    No Rail Stations [No_Rail_Stations],
    No Fungal Monsters [No_Fungi],
    Stats Through Kills [stats_through_kills]
]

**Comment by anothersimulacrum** [comment]
@dsmky117, yours is #40899, which is a new, separate bug.

**Comment by int-ua** [comment]
Please comment if you are still able to reproduce it on fresh versions and we'll reopen this issue.
