### ISSUE TITLE
Backpack encumbrance exceeds 'encumbrance when full' with Packmule trait

### ISSUE THREAD

**Issue by AllanMAL** [CleverRaven/Cataclysm-DDA#38486]
Game version: 0.D-12725-ge035f12

Operating system: Windows 10

Tiles or curses: Tiles

Mods active: 
Dark Days ahead
Disable NPC Needs

### Expected behavior
Container encumbrance increases to, but not above, 'encumbrance when full' as stated in description.

### Actual behavior
Container encumbrance increases above 'encumbrance when full' as stated in description.

### Steps to reproduce the behavior
Wear backpack/rucksack/duffel and fill inventory to max volume.
![rucksack](https://user-images.githubusercontent.com/14248118/75658021-c41f6480-5c67-11ea-94c1-e614b3de7668.png)

Edit: Better?

**Comment by Funguss** [comment]
Ooh. The question here is what is packmule actually doing? Are objects poking out of their containers or are things packed into the containers in an especially economical way? If it's the former then this should be correct behaviour and needs UI support. If it's the latter then I reckon encumbrance should increase proportionally, not cap.

**Comment by SirPendrak** [comment]
Maybe after nested containeers change this can be touched. Possible solution would be: increase every wearable container storage volume (or lower encumbrance of currently existing backpacks), and then make it possible for normal people to use only 70% of storage while packmules can use 100% or 95%. Current trend to give every object their exact irl volume will change things a bit too, because most weapons for example like swords will have reduced volume by a factor of few times lower.

**Comment by kevingranade** [comment]
Obsoleted by #40820
