### ISSUE TITLE
Re-balance books to be more consistent 

### ISSUE THREAD

**Issue by Feniks-Gaming** [CleverRaven/Cataclysm-DDA#38567]
# Is your feature request related to a problem? Please describe.
Currently books are a bit all over the place some skills can be trained easily to higher levels like Tailoring while other skills don't benefit from this that much. While I understand that logic is that skills involve risk should require player to train harder than skills that don't there could be some improvements made. For example Swimming can be only trained to level 3 while it's the most tedious skill to train by going up and down a river for 20 min. 

We should aim for better balance. 

In addition we could provide better spread for books for the player. 

# Describe the solution you'd like

Skills that should be learn able to higher levels in my opinion should be:

Cooking
electrinics
fabrication,
survival
tailoring,
computers
driving
first aid
mechanics
swimming
trapping
bartering
speaking

I would consider for non combat skills 3 categories of books 

**Large Tomes:** - Long reading time unlocks most recipes in it's respectable levels

LargeA - Skills 1-3, 
LargeB - Skills 4-6,
LargeC - Skills 7-9

**Medium Tomes**

Increasing skills by 2 points - Has less recipes is slightly faster to read and  increases skill up to 2 levels

MediumA Skills 1-2
MediumB Skills 3-4
MediumC Skills 4-5
MediumD Skills 5-6
MediumE Skills 7-8
MediumF Skills 8-9

**Small Tomes**  Increases skills by 1 level has at best 2 -3 recipes. 

SmallA Required skill 0 max skill 1
SmallB - Required skill 1 max skill 2
etc. 

Finally 

**Magazines** - Books that don't increase any level their max level is the same as required level but can have couple of recipes in them. Those would be fast red unlock new crafting recopies. 

For combat skills we could only have small tomes up to level 3 requiring player to do the rest via fighting and taking risks. 

# Describe alternatives you've considered

I have considered bring in fighting skills in line with other books but decided against it we don't want players to just hunker in a house and emerge as zombie killing machines after 2 weeks of reading. 

I have also considered skipping magazines in favour of putting more recipes in small books but I think they could be more fun as little bonus to surprise player with new recipe that they can learn quickly while out looting and get rid of the book.  I also feel that magazines could encourage people to actually level through crafting. If you find a book that unlocks the recipe you want but you can't get there yet you are more likely to craft your way tho this level rather than spend weeks hunting for the book mechanic 301 book for example. This may have undesired effect of players exploring less in search for books but I doubt books were primary driving force for exploration for most anyway. 

# Additional context

I believe this is a task I could attempt with some guidance and I would be willing to have a go at it.

**Comment by Funguss** [comment]
A few points in no particular order.

It's faster to train by crafting already. Turn down your skill gain, makes it more obvious. Even with fast reader and the trait that increases skill gain from books they lose, even if your intelligence is 14 and you're reading the quickest ones you can.

Some of the skills you list are incomprehensible to skill through books to any substantial level, like swimming and driving. I'd say that it's impossible to get to any kind of skill IRL without actual practice, unless it's something that's purely theoretical.

I don't think there's a single crafting skill that can't be trained via books to level eight, most go to ten. I don't see why anyone would care to get driving, swimming, speaking or bartering that high, but they get to four, three, six and six, respectively. Those four already seems like a stretch of the imagination to me. After some level you can train from recipes a level or two below current, anyway, and the highest level recipes either cap out at the books level or go one or two higher, which is so much easier to get via crafting anyway.

Dedicated skill training via books is likely to get you killed due to the time it takes, as while you're hunkered down getting your fabrication up to make that sweet pneumatic rifle the brutes are growing into hulks. And worse. Honestly, anything that speeds up skill gain would be taking us in completely the wrong direction. Back when a season lasted fourteen days you could _kind of_ justify gaining levels that quick but now it's ludicrous.

I'm not sure if your suggestion is actually about having generic books, I can't imagine it is. In case it is, I'll just mention that that would remove a lot of depth and a bit of lore, while making the entire system feel trivial and impersonal. I think everyone gets a rush when they find Robots for Fun and Profit, even if their character will never use it.

Skills are overdue an overhaul, I don't think they've fundamentally changed since Whales was active. It's still a very abstract system. Personally, I think books have marginal use for NPCs and resource poor areas, and that's enough.

Sorry,I got carried away and I'm not even sure I understood your suggestion. :fearful: Also, I may have sounded short or something, I'm struggling to think straight right now, so sorry for that, too.

**Comment by ZhilkinSerg** [comment]
Skills like swimming and driving should have 80+%  activity-based learning - a couple of first skill levels can be learned from books, while anything else only learned by practicing.

Books should open new recipes and maybe new "techniques" (e.g. new swimming style), which still need to be practiced to be mastered.

**Comment by Funguss** [comment]
And have them speed up learning when used as a reference. Any unknown recipes should take longer and give significantly more experience, repetition give a lot less. Skill suggests... well... skill. Boiling water, cooking down fruit and pressing juice are each more difficult than the previous but I can do all those things many times then be able to make lasagna or whatever. Ensuring against that behaviour altogether would probably not work out too well, but encouraging diversity should help.

**Comment by AncientSion** [comment]
I think books should hardcap at 3, maybe 4. Ask yourself how much of electronics or woodworking can you really hard while studying ? 
Every master in realife has practive and real experience. Book grinding NOT A THING.

**Comment by Funguss** [comment]
Try playing with 0.1 skill gain. It really does put you off ever touching a book, even at low levels you get less than 1% per chapter. I shudder to think how reading the SICP will go.

Learning is best done with practice and reference materials, be they teachers or books.

**Comment by Funguss** [comment]
Hell yeah, that's the stuff! That's how it needs to be done! Rust looks a lot more reasonable there, but... I've never been a big fan of the notion. Getting rusty should impact the quality of your work after you've had a very significant amount of time without practice, and then it should only be basics. Once you've mastered a skill getting time away, learning different things and having other experiences can help you to come to a breakthrough. I'd say that learning a new skill is all about changing the way you think, and what we see as "getting rusty" is something along the lines of breaking a habit.

This book is excellent, and I drew some of my conclusions from it:
https://www.penguinrandomhouse.com/books/301358/the-secret-life-of-the-grown-up-brain-by-barbara-strauch/

It's well written and easy to understand, I mostly read it during break times at work. The stuff on alzheimers and dementia are really fascinating.
