### ISSUE TITLE
Loot-tables in general require a serious rework - here: House kitchens. Also World Loot Settings.

### ISSUE THREAD

**Issue by AncientSion** [CleverRaven/Cataclysm-DDA#38622]
In the current iteration of the game, every basic kitchen room very likely has a cupboard with a ton of forks and knifes and a cupboard with the very same loot

200 Duct Tape
7 Long Strings
2 Empty Batteries
Exactoknife and some other things

Now, i think there are following issues here, one is major, one is minor.

Minor:
Loot which some time ago was "hard" to come by, has been trivialized ALOT.
Formerely, Duct Tape was rare and very useful. Today you find TONs within the first 2 days of the game. This is bad.
Same goes for long strings. While it wasnt as important per se and neither hard to obtain, it also has been grossly trivialized to aquire huge amounts of thread.

Major:
Right now, every (every!) kitchen has this loot in the quantities above. That is boring. Even if kitchen loot isnt fleshed out, i really REALLY wish there was SOME randomization. Perhaps instead of 200 duct tape, gives is 1 full battery or something. Just SOME variance to go by until its fleshed out.
As a sidenote, im wondering why every household even has strings and duct tape and empty batteries. 
I know for a fact a person in my entire appartment would find a LOT of batteries (full), some Duct-Tape and not-even-one long or short string. Now im using this to proof anything. Just saying my house has no string. Whatsoever.

Major Major Major
I really, really, really have a strong dislike for the way world loot settings work at the moment.
When i play the game at 0.5 loot, what happens is that i find kitchens with an empty fringe and empty cupboards and kitchens with a stuffed full fringe and a fully stuffed set of strings and duct tape.
So im pretty sure for some reason the loot RNG applies on a per tile basis as opposed to a per-stack (or, per item) basis.
When im playing 0.5 loot, i want to find SOME loot everywhere, i dont want to jump from house to house hoping for that one lucky kitchen that has ALL the things (imagine 0.2 loot).

So sum it up:
- for now, please add a little bit of variance to kitchen loot. Even if its a big project in the making, just some variance (apart from RPG dies in every third kitchen) would help greatly.
- Please consider changing world settings to roll on spawn per item stack or better per item within the stack. Rolling per tile has some very unnerving sideeffects, obviously with tiles that have many loot possibilites (this is extreme for kitchens, but there are more tile objects that spawn a large amount of items and thus either spawn all or nothing).
- In general, with food being abudant and also many guys spawning with camera and gameboys, batteries are also abudant. I wish there was "rare" but "commonly" needed loot early game, like in the old (2 years?) days.

thanks for considering.

**Comment by GennFaol** [comment]
What someone would find in your apartment is anecdotal and not very useful. In my house you'd find a few hundred meters of duct tape of various types, as I buy it in bulk, and a few hundred meters of string. That info is not very useful, because your personal experience does not reflect all of reality.

I do agree there should be some variance in it, but simply saying what you have in your household is not a useful basis for figuring out what items should be there in which quantities.

As for finding some houses that are almost empty vs. finding some that have everything... that is perfectly realistic? Some people might have bailed and taken most of their things, or they didn't have much in to start with, whereas others were well-stocked and did not have the opportunity to take anything. That makes sense to me, and I disagree that every house should have an even spread of loot.

**Comment by Tamiore** [comment]
AncientSion has one good point:
Item spawn chance should works on per-item basics, not per-stack or per-tile. 
So if I have 10% base item spawn rate, I mostly find stacks with ~10% of items in them, not full stacks 10% of the time. 
Ideally, same should go for liquids and powders as well: 10% the normal gasoline at gus stations, etc.

**Comment by ZhilkinSerg** [comment]
Go and suggest changes to following item group:

https://github.com/CleverRaven/Cataclysm-DDA/blob/8c365a367ca06de6b6f429167b328597e42556ee/data/json/itemgroups/SUS/domestic.json#L92-L124

You can refer to following doc - https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/ITEM_SPAWN.md for details on item spawn.

**Comment by cupnooodle** [comment]
I agree with this issue. Finding an RPG die, x-actoknife, long string, duct tape (200), dead battery (0/200), fire extinguisher in every kitchen is immersion breaking. It wasn't like this in 0.D stable

**Comment by Amoebka** [comment]
Loot amounts are out of this world ridiculous because there are plans to introduce NPC looting later. Of course, nobody considers it a release blocker or even a priority, so it might take a year or more. Until then the game balance will remain pitifully broken.

0.E is honestly shaping up to be a "fake" release. It's scheduled right in the middle of several balance-breaking reworks, so even without bugs it will be a complete mess to play.

**Comment by ZhilkinSerg** [comment]
> 
> 
> I agree with this issue. Finding an RPG die, x-actoknife, long string, duct tape (200), dead battery (0/200), fire extinguisher in every kitchen is immersion breaking. It wasn't like this in 0.D stable

Immersion breaking was not finding these things in almost every kitchen. If you go to your own kitchen you will find most of these things.



> 
> 
> Loot amounts are out of this world ridiculous because there are plans to introduce NPC looting later. Of course, nobody considers it a release blocker or even a priority, so it might take a year or more. Until then the game balance will remain pitifully broken.
> 
> 0.E is honestly shaping up to be a "fake" release. It's scheduled right in the middle of several balance-breaking reworks, so even without bugs it will be a complete mess to play.

You are spreading misinformation without even caring to provide any factual links.

**Comment by davidpwbrown** [comment]
> Loot amounts are out of this world ridiculous because there are plans to introduce NPC looting later. Of course, nobody considers it a release blocker or even a priority, so it might take a year or more. Until then the game balance will remain pitifully broken.
> 
> 0.E is honestly shaping up to be a "fake" release. It's scheduled right in the middle of several balance-breaking reworks, so even without bugs it will be a complete mess to play.

Out of this world ridiculous is a statement that could quite adequately describe your post, when the "loot" you get from kitchens is duct tape and string and batteries and cutlery, not exactly end-game gear is it?

The basis of this game is that if it exists as a thing irl, it should be represented here. If this means raiding kitchens for strings is a viable strategy then thats fine! thats what people would *actually do* if they needed supplies in the event of a real-life Cataclysm.

If you consider that "pitifully broken" because  kitchens have got lots of slightly useful stuff, then maybe this isnt the game for you.


For the actual issue in question, the thing that is needed is *variability* of SUS item groups.

We will not remove strings or batteries from houses just because strings or batteries are something people always want early-game and it may upset some nebulous subject sense of "balance".

They will stay because it makes sense for houses to have strings and batteries, if this makes the game too easy, then that obviously is an indicator  that the game has other aspects that make too much use of strings and batteries to progress!

For future reference, keep your comments on an issue on-topic, making some weird statements about a release being "fake" and the game being "broken" and grinding your axe, is not welcome, helpful, or necessary.

**Comment by I-am-Erk** [comment]
I'm not sure what's up with the "There's always 'x'" claims.

Feel free to adjust the numbers, but there's only a one in ten chance of finding RPG dice. There's a 15% chance of getting 400 duct tape, 35% chance of getting no duct tape at all, and 50% chance of getting 200. There is an 80% chance of finding an xacto knife.

These could be tweaked (in particular, duct tape should use min and max charges to vary the amount you get), but nevertheless each kitchen selects a pretty random group from a long list of random common objects.

As for the argument that it breaks the game to be able to find string in places where you would expect to find string, well... Don't got much to say about that.

**Comment by Rail-Runner** [comment]
One more way to help with the issue (for those who think it's an issue) could be adding yet more mostly-useless clutter to appropriate places: stuff like TV remotes, mousetraps, globes, computer hardware, plastic/plush/etc. toys, ashtrays, dustpans, soap dishes, clothespins, hand fans, evenlopes, electric irons, hair dryers, vacuum cleaners (robotic and manual), leaf blowers. air ionizers, pencils, rakes, watering cans, vases and whatever else; it's just a short list of things I could think of and yet couldn't find in game as of now.

**Comment by I-am-Erk** [comment]
Adding more clutter wouldn't help tons with this issue in specific, aside from the sense of monotony (which I don't really agree with. You look in a silverware drawer, you're going to find a certain subsection of objects). However, I'd love more clutter items. It would be nice to have a distribution of subgroups in the junk drawer SUS that selected from something like up to 5 clutter flavour items per group, making each drawer a bit more distinct

**Comment by GennFaol** [comment]
I feel this really isn't an issue as such, I don't think you're finding unreasonable or unrealistic amounts of duct tape and string.

More clutter to add variation to the drawers would certainly be nice, though, even if it's things that have no or only limited use.
