### ISSUE TITLE
Slime Pits should be defeatable?

### ISSUE THREAD

**Issue by dwarfkoala** [CleverRaven/Cataclysm-DDA#3865]
As per: http://smf.cataclysmdda.com/index.php?topic=3792.msg56331#msg56331

Slime pits at the moment are kinda... useless. Flushing it out takes plenty of effort, and the bottom has nothing in particular that you'd consider taking it on for. Slimes can't be stopped from spawning and don't drop loot, so slime pits only serve as a hindrance to the player, and not a particularly good one either.

Maybe something at the bottom you can use to shut it off? Maybe the slime pits are so slimy because there's a portal or something at the bottom and you need to shut it off? Maybe it's possible to purify the pit (yeah, not sure how that would work) with some specialized items or some machines found at the bottom? Maybe it's possible to harvest the purest slime at the bottom for great mutagen justice?

Slimes are basically what caused this apocalypse. They should be more interesting.

EDIT: Thanks to NaturesWitness and #4017, blobs now drop some fashion of loot! YAAAY! Slime pits are still not defeatable, but Slimes now drop slime scraps, or pieces of blobs that have been smashed so utterly they do not appear sentient any longer. NaturesWitness also added recipes for mutagen, slime mutagen, superglue, and goo canisters.

Still leaving this issue up, for making slime pits defeatable, but changed to reflect that there is loot in them now!
##

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
