### ISSUE TITLE
Compound Greatbow weaker than regular Compound Bow

### ISSUE THREAD

**Issue by Amoebka** [CleverRaven/Cataclysm-DDA#38724]
# Describe the bug

Compound Bow requires 9 strength (medium weight) and has 50 base damage.
Compound Greatbow requires 15 strength and has 43 base damage.
Since both bows are compound, why is the bigger one so much less efficient?

# Steps To Reproduce

1. Look at bow stats.

# Expected behavior

Compound Greatbow does more damage than regular Compound Bow due to having similar efficiency but much higher draw weight?

# Versions and configuration

 - OS: win10
 - Game Version: #10412
 - Graphics version: tiles
 - Mods loaded: none

**Comment by Tamiore** [comment]
Check out compound crossbow vs heavy crossbow, while you are at it. 
Those two are even more hilarious.

**Comment by kevingranade** [comment]
They don't have similar efficiency, the basic compound bow is a modern hunting bow with modern materials and design, the compound greatbow is a basic cobbled together design with substandard materials.
The crossbows are in the same boat, this is working as intended.

**Comment by Tamiore** [comment]
@kevingranade 

So are there any bows/crossbows (in main branch) right now that are "not working as intended" yet?

Because it kind of perplexes me that an auto-learned bow (composite bow) with auto-learned arrows (wooden broadheads) has higher per-strike damage that high-tier polearms (glaive's, etc).
