### ISSUE TITLE
Dissecting corpses when running drains stamina

### ISSUE THREAD

**Issue by Scintile** [CleverRaven/Cataclysm-DDA#38877]
# Describe the bug
If you are in running mode your stamina will drain quickly when dissecting corpses (probably other tasks, not sure about that)

# Steps To Reproduce
1. Toggle running
2. Stand over a corpse while holding Fine cutting tool in your inventory (i used X-acto knife)
3. Start dissecting corpse
4. Observe your stamina draining, and message at the  top of the screen change constantly from Dissecting to Catching breath (dissecting thus takes way longer then it should)

# Expected behavior
You should expect the same results as if you are dissecting when not running - your stamina should slowly regenerate

# Versions and configuration
 - OS: Windows 7
 - Game Version: 10429 (but was observed in a lot of previous versions)
 - Graphics version: Undead_people (but was also observed with ChestHole)
 - Ingame language: English
 - Mods loaded: dda, cataclysm++, aftershock, bionic slots, CRIT expansion, Disable NPC needs, Magiclism

**Comment by Dacendeth** [comment]
Can confirm i've experienced this as well.

**Comment by jkraybill** [comment]
Yeah this is actually a bit worse than this. Stamina recovery is always affected by current move mode. Recovering using the "wait" menu with "wait until you catch your breath" took me 12:13 with a character while in running mode, but 3:04 while in crouching mode.

I'm looking at a fix that will remove the move modifier from the update_body() call that happens every turn, but I think it will require a counterbalancing increase to how stamina is burned when actually moving in order to not effectively dramatically increase running range.
