### ISSUE TITLE
Driving in reverse with the 1900HP gas turbine engine gives extreme fuel efficiency.

### ISSUE THREAD

**Issue by dhanyabeloit** [CleverRaven/Cataclysm-DDA#38923]
Game version: 0.D-12828-gf74fc97

Operating system: Debian Linux

Tiles or curses: Tiles

Mods active: Disable NPC Neesds, Aftershock, CRIT Expansion, Alternative Map Key, Fuji's Military Profession Pack, SpeedyDex

### Expected behavior

Since there is only 1 single gear to reverse and multiple gears to go forward, the faster you go, the more efficient going forward is compared to going backward at the same speed. 

### Actual behavior

Cruising forward at around 48kmph on my deathmobile, the guage said I was spending 0.2% per hour, with an air drag of 2.24 (1 week to empty). Moving backward at 85kmph however I got a steady cost (not affected by how fast I was accelerating) of 0.1% per hour (4 weeks to empty), with the same air drag, and rolling drag.

### Steps to reproduce the behavior

Get into a vehicle that used liquid fuel, drive backward as fast as possible, then forward. Check fuel consumption rates.

Also since I play with reverse driving, it literally feels like driving forward but with jk reversed.

**Comment by dhanyabeloit** [comment]
My guess is that fuel cost isn't updated while going in reverse like it is going forward, since people aren't expected to be doing it, so every increment of acceleration costs the same as any other.

If this is intended, I've been accumulating INSANE style points over the last few hours literally driving my vehicle backward across the map, slaying zeds for 15-25% of the normal cost (I have 2 of the same engine, but 1 was disabled for efficiency sake, however I get around 4x fuel efficiency going backward with both compared to forward with one, and 6x when comparing 1 to 1)

**Comment by mlangsdorf** [comment]
the logic in vehicle::thrust() is completely confusing.

okay, in vehicle::gain_moves() we calculate the vehicle's slowdown() due to drag and subtract it from velocity for vehicles moving forward and add it to velocity for vehicles moving in reverse.  So a vehicle moving in reverse at -85 kph slows down by 8 kph, making its velocity -77 kph, that makes sense.

then `vehicle::thrust( int thd )` is called, with thd 1 if cruise velocity (-85) is greater than velocity (-77) and -1 otherwise.

in `thrust()`, `thd` is -1 and `sgn` is -1, so `thrusting` is True.

`accel = acceleration( std::abs( velocity ) )` so 8 or so
`vel_inc = accel * thd` or -8
`effective_cruise` is `std::min( cruise, max )` or -85
`cruise_on` is true, `thd < 0`, so `vel_inc` is reset to `std::min( vel_inc, effective_cruise - velocity )` or -8.

 `load` is `1000 * std::min( 0, vel_inc ) / std::max( accel, 1 )` which is -8000.

`load` is less than 0, so the engine consumes no additional fuel beyond idling.

the load calculation in `vehicle::thrust()` is broke but I'll have to sit down some more and figure out the right answer.

**Comment by mlangsdorf** [comment]
Okay, short term fixes since this is not a 0.E blocker bug but I'm also not quite ready to redo vehicle braking:

```
    //pos or neg if accelerating or braking
    int vel_inc = ( thrusting ? accel : accel + 2000 ) * thd;
    if( thd == -1 && thrusting ) {
        //accelerate 60% if going backward
        vel_inc = .6 * vel_inc;
    }

    //find power ratio used of engines max
    int load;
    // Keep exact cruise control speed
    if( cruise_on ) {
        if( thd > 0 ) {
            vel_inc = std::min( vel_inc, std::min( cruise_velocity, max_vel ) - velocity );
        } else {
            vel_inc = std::max( vel_inc, std::min( cruise_velocity, max_vel ) - velocity );
        }
        if( thrusting ) {
            load = abs( vel_inc ) / accel;
        } else {
            // brakes provide 20 mph/s of slowdown and the rest is engine braking
            // TODO: braking depends on wheels, traction, driver skill
            load = max( 0, abs( vel_inc ) - 2000 ) / accel;
        }
```

That should result in this nice set of load values:

Cruise Velocity | Velocity | thd | sgn | thrusting | max_vel | accel | brk | vel_inc | ecruise | vel_inc2 | load
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
100 | 90 | 1 | 1 | TRUE | 120 | 20 | 40 | 20 | 100 | 10 | 0.50
100 | 110 | -1 | 1 | FALSE | 120 | 20 | 40 | -40 | 100 | -10 | 0.00
-25 | -30 | 1 | -1 | FALSE | 120 | 20 | 40 | 40 | -25 | 5 | 0.00
-25 | -20 | -1 | -1 | TRUE | 120 | 20 | 40 | -12 | -25 | -5 | 0.25
25 | -25 | 1 | 1 | TRUE | 120 | 20 | 40 | 20 | 25 | 20 | 1.00
-25 | 25 | -1 | 1 | FALSE | 120 | 20 | 40 | -40 | -25 | -40 | 1.00
-100 | -30 | -1 | -1 | TRUE | 120 | 20 | 40 | -12 | -100 | -12 | 0.60
-5 | -20 | 1 | -1 | FALSE | 120 | 20 | 40 | 40 | -5 | 15 | 0.00

And we can go ahead and get rid of `brk` since it is no longer used anywhere.

This needs playtesting and make effect the vehicle efficiency unit tests.
