### ISSUE TITLE
Batteries should lose charge over time

### ISSUE THREAD

**Issue by cupnooodle** [CleverRaven/Cataclysm-DDA#39095]
# Is your feature request related to a problem? Please describe.
Not related to an existing problem. 

# Describe the solution you'd like
Batteries should drain an arbitrary amount over arbitrary amount of time. Rate is dependent on the ambient temperature. Higher temp = higher rate of discharge and vice versa.

# Describe alternatives you've considered

# Additional context
https://batteryuniversity.com/learn/article/elevating_self_discharge

**Comment by Sirbab** [comment]
I frankly don't see this being a worthwhile feature.
Here's why:
-While it is true that modern primary and secondary cells lose charge over time, who is to say that the secondary cells are the same in principle as current ones?  A novel technology that isolates the terminals from losing charge/inhibiting chemical reactions could have been developed.
-Would this promote meaningful change in gameplay, or would it merely be realism?  I honestly don't see it other than looted batteries having low charge, which could be emulated with loot tables afaik.  Players with ample access to batteries past early game will likely just have them sitting on a UPS charging station.
- As far as i understand it, this would wreak havoc on recipes, constructions, activations that rely on a given charge.  Need 100 charges to craft the recipe?  Too bad, it decayed to 99 like 3 seconds ago.  This would either require a broad re-doing of charge requirements, or it would effectively nerf all batteries due to having 1 fewer uses than before.
-It would introduce a substantial amount of tedium to batteries that already are somewhat tedious to use.  I am leery of features that make it them more annoying to use than they are now.
