### ISSUE TITLE
can't turn off mp3 player when it runs out of batteries

### ISSUE THREAD

**Issue by rumly111** [CleverRaven/Cataclysm-DDA#39155]
I was listening to the mp3 player, and the batteries ran out. But in my inventory it was still yellow and "turned on", and there was an icon above my head indicating I'm deafened, and I couldn't hear opening doors etc. I tried dropping the mp3 player and picking it up, but it didn't fix it. I tried (a)pplying it to turn it off, but it said it needs batteries. The only way to fix it was to put in new batteries and then turn it off.

Game version: Tiles, recent git.

It would be nice if the mp3 player (and other similar devices) automatically turned off when the batteries run out.

**Comment by wapcaplet** [comment]
Are you sure your mp3 player wasn't still playing music?

I observed similar behavior, but it looks to me like a premature rounding issue - it shows "0" charge even while it still has a little power left, and music is still playing. After my mp3 player reached 0 on a standard light battery (100 capacity), I still had a good 5-10 minutes of music left before it finally turned off.

I noticed the same with a standard flashlight, but the time time left after reaching 0 was shorter since the flashlight draws more power.

Perhaps batteries should continue to show "1" charge, only indicating "0" when they are completely drained?

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Pop!_OS 19.10; Release: 19.10; Codename: eoan; 
- Game Version: 0.E-646-g00eebfe8f7 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by dsmky117** [comment]
On a new game on 10633, I cannot remove earbuds at all. After activating my mp3 player, deactivating/dropping leaves the player under the 'Wearing earphones' effect.

**Comment by Hirmuolio** [comment]
#53047 fixed this and this can be closed.

**Comment by silvadomi** [comment]
Has this been merged into the 0.I branch yet? I'm playing the 0.I release candidate (git commit ID 13efcb0ffbf3e208080aea281fc0833fc775a2f5) and have been seeing this issue. mp3-player must have run out while crafting a practice recipe, had no charge afterwards, but was still running and I couldn't turn it off.

Message log:
<img width="741" height="303" alt="Image" src="https://github.com/user-attachments/assets/7a42c29b-17c1-48a0-81cb-a6623e27734b" />

Inventory:
<img width="630" height="151" alt="Image" src="https://github.com/user-attachments/assets/75e60ac1-0468-4a3a-8dac-29e1da89799e" />
