### ISSUE TITLE
Compound Crossbow and Reflex Recurve Bow effectively Removed

### ISSUE THREAD

**Issue by Boredone** [CleverRaven/Cataclysm-DDA#39161]
The recent PR #39128 removed the crafting recipe for these items, which is somewhat understandable, but the Compound Crossbow and Reflex Recurve Bow do not seem to appear in any actual item groups.

So crafting was the only way to get them without modding, and said recipes have been removed.

Bit of a problem for Magiclysm since the Reflex Recurve was actually an ingredient for a mythical weapon recipe.

**Comment by Insanegame27** [comment]
You're wasting your breath, Kevin doesnt give half a damn about Archery and he'll close this one too without even saying anything, just like when I tried https://github.com/CleverRaven/Cataclysm-DDA/issues/39151 here

**Comment by anothersimulacrum** [comment]
It'd be a very easy PR to add them to itemgroups, please consider [making a PR](https://github.com/CleverRaven/Cataclysm-DDA/wiki/Guide-to-adding-new-content-to-CDDA-for-first-time-contributors) doing so.

**Comment by Insanegame27** [comment]
> It'd be a very easy PR to add them to itemgroups, please consider [making a PR](https://github.com/CleverRaven/Cataclysm-DDA/wiki/Guide-to-adding-new-content-to-CDDA-for-first-time-contributors) doing so.

Or we could open an issue to get archery progression unfucked ASAP... oh wait

**Comment by anothersimulacrum** [comment]
Please stop spamming this issue with your unrelated complaints about a similar topic.

**Comment by Insanegame27** [comment]
> Please stop spamming this issue with your unrelated complaints about a similar topic.

It's literally the same issue

**Comment by anothersimulacrum** [comment]
This issue is that these bows don't spawn anywhere.
Your issue is that you think you should be able to craft them.
Different issue, same topic.

**Comment by kevingranade** [comment]
The reflex recurve is an incoherent item and needs to go away anyway, so no loss there. We'd definitely accept a PR that adds compound crossbow spawns to sporting goods stores and occasionally to homes.

**Comment by I-am-Erk** [comment]
Spam ranting deleted.

**Comment by Night-Pryanik** [comment]
> The reflex recurve is an incoherent item

Why is that? Reflex recurve now is a valid RL thing.

**Comment by esotericist** [comment]
> > The reflex recurve is an incoherent item
> 
> Why is that? Reflex recurve now is a valid RL thing.

as i understand it, it's not so much "the existence of this is incoherent" as "it being a distinct thing, stat-wise, is not meaningful". reflex vs recurve vs reflex recurve does not seem to grant any mechanically significant properties.

**Comment by GGgatherer** [comment]
> 
> 
> > > The reflex recurve is an incoherent item
> > 
> > 
> > Why is that? Reflex recurve now is a valid RL thing.
> 
> as i understand it, it's not so much "the existence of this is incoherent" as "it being a distinct thing, stat-wise, is not meaningful". reflex vs recurve vs reflex recurve does not seem to grant any mechanically significant properties.

Meanwhile, we have absolute ****ton of practically useless forks, sporks, paper wrappers and whatnot added to kitchens nobody cares about, but this one bow? oh no, this one should be culled from existence because it doesn't add anything new to game mechanics.
...seriously?

**Comment by ZhilkinSerg** [comment]
> ...seriously?

Yes.

**Comment by I-am-Erk** [comment]
*is* reflex recurve an actual type of bow? I can't find much about them outside our game, and the definitions of reflex and recurve bows don't make sense together.

**Comment by Zireael07** [comment]
AFAIK reflex recurve is a purely game-ish thing (I saw it outside of CDDA, but also in a game).

**Comment by Night-Pryanik** [comment]
> I can't find much about them outside our game, and the definitions of reflex and recurve bows don't make sense together.

>AFAIK reflex recurve is a purely game-ish thing (I saw it outside of CDDA, but also in a game).

Did you ever bother to search? First link in google.
![изображение](https://user-images.githubusercontent.com/11132525/78270660-2f38b100-751c-11ea-8cce-b03ff2ac14da.png)

This was already discussed a while ago in #13478.

**Comment by I-am-Erk** [comment]
From that article:
> A reflex bow is a bow that has curved or curled arms which turn away from the archer throughout their length. When unstrung, the entire length of the bow curves forward from the belly (away from the archer), resembling a "C"; this differentiates a reflex bow from a recurve bow in which only the outer parts of the limbs turn away from the archer.

Nothing else in the article states what a "reflex recurve" bow is or would be, and the definitions cannot fit together. This is further evidenced that the *second google result* for "reflex recurve bow" is that tiny thread on this github from 2015, where you make an argument that, no offense, is nonsensical. If the arms of the bow curve away from the user when unstrung, the bow is reflex. If only the outer parts curve away from the user, it is recurve. If both the arms and the outer part of the arms curve away, *that is the definition of a reflex bow*.

Find me an example of a reflex recurve bow, besides one confusingly labeled image from wikipedia. I would like to purchase one from an online shop. Go ahead.

**Comment by kevingranade** [comment]
A big part of the issue here is that people are getting hung up on taxonomy versus function vs what-should-be-in-the-game.
This article outlines the major bow types https://www.2020archery.co.uk/blog/ask-the-experts-whats-the-difference-between-a-recurve-bow-and-a-traditional-bow/

Which despite the names used are not super meaningfully differentiated by geometry.
Traditional Bow
Modern Bow
Horse Bow

Traditional bows tend to be flat geometries, because those are far, far easier to make.
Modern bows tend to have some kind of recurve because it's more efficient, and it's much easier to add a recurve with modern laminate based assembly.
Horse bows are full reflex or reflex with stiff tips because that's necessary to maximize power in a small bow.

Now as for what bows should be in the game and how they should be described in the game, reflex vs deflex vs recurve is *irrelevant*.

Practically all modern non-compound bows are reflex and made of fiberglass.  We will call it a "Modern Recurve Bow" because that's what the industry calls it.
A survivor-craftable wood bow is either a straight flatbow or cylindrical bow, I'm not sure about the name, but it's probably not going to reference geometry.
A survivor-craftable horsebow will probably be horn and wood and sinew, and will be a reflex geometry, it will most likely be called a horn bow.
A pre-cataclysm compound bow is going to be called a compound hunting bow.
I'm not sure about the name for a survivor crafted compound bow, possibly just compound bow, but geometry doesn't come into it.
Super strong variants that are so strong they require being made from different materials would be called *whatever* Greatbows.

**Comment by Night-Pryanik** [comment]
> If the arms of the bow curve away from the user when unstrung, the bow is reflex. If only the outer parts curve away from the user, it is recurve. If both the arms and the outer part of the arms curve away, that is the definition of a reflex bow.

Arms curve away from from archer = reflex.
Tips curve away from archer = recurve.
And yet when both the tips and arms curve away from archer it's still only _reflex_ bow? I consider "reflex" and "recurve" as additive qualities, not mutually exclusive ones. 

Sure, that might be just a terminology issue, or maybe it's only me, but I'd rather call an item consisting of quality A _and_ quality B the "A-B thing".

>where you make an argument that, no offense, is nonsensical.

I personally NEVER called anyone's arguments "nonsensical" even if they were obviously wrong, because I understand how obnoxiously it could sound. So, well, offense taken.

**Comment by RobertoVGoulart** [comment]
From what I've googled, a reflex bow completely curves away from the user when unstrung, while on a recurve bow the tips of it curves away.

If this is right, a reflex bow is a type of recurve bow, since it's tips are curving away, but the name "reflex-recurve" doesn't mean much more than just "recurve".

**Comment by I-am-Erk** [comment]
The tips are part of the arms. A reflex bow is not one where the inner parts of the arms curve away but then it straightens out. Again: 

> When unstrung, the entire length of the bow curves forward from the belly (away from the archer), resembling a "C"

"Nonsensical" is just a descriptive word. It means the thing you said didn't make sense. I said "no offense" as an attempt to highlight that I wasn't trying to say it was nonsensical to be rude, but because the combination of the terms is nonsense, it's a pairing of terms that literally don't make sense in combination

**Comment by Arcangelus** [comment]
Hi. First time poster here, hoping you are all well. Now, to the relevant part.
I don't really care one way or the other, but as far as I understand the shape of a bow is determined while unstrung. So, assuming the archer is on the left, a reflex bow would look like a C, a deflex like a D, etc. With that in mind, I found a little chart with several possible combinations.
http://leatherwall.bowsite.com/tf/pics/00small68956330.JPG
The first is considered a reflex/recurve.

That image was taken from here: http://leatherwall.bowsite.com/tf/lw/thread2.cfm?forum=23&threadid=311066&messages=20&CATEGORY=3
There is also a reference to "Ben Pearson's 1959 classification", but I choose to ignore it as the image was lower quality and I'm not quite able to read it.

Now, whenever or not it has an advantage over other designs, I have no idea. I'm no archer.

**Comment by jeremyshannon** [comment]
I'm not sure that chart's showing a discrete "reflex/recurve bow" type separate from a regular reflex bow, so much as suggesting that we classify all reflex bows as a sub-type of recurve bow.

**Comment by Arcangelus** [comment]
You could say that, if we ignore semantics. At the end of the day, all these terms mean is whenever or not there is some kind of curve and where. For the main body we have reflex/deflex, for the extremes recurve/decurve. Combinations can be used to describe more complex shapes, but there's a limit to how useful that can be. No combination of those meaningfully describes a yumi, for instance.
Does reflex-recurve mean anything? Maybe, if the ends have a significantly different (more extreme) curvature than the rest. Does that make any practical difference? Hell if I know.

The only other real characteristic of a recurve bow is what happens when a string gets involved. If the string touches the shaft itself rather than just the ends, then its a recurve. Otherwise, it isn't.
So, a merely reflex bow should look something like this: (let's pretend there is a bigger C on the left)
https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/19th_century_knowledge_archery_reflex_bow.jpg/433px-19th_century_knowledge_archery_reflex_bow.jpg
https://armourandcastings.com/media/cache/sylius_shop_product_original/47/6f/3fee95b397d43efe2216b0ec9be2.jpeg

While a recurve looks something like this:
https://ae01.alicdn.com/kf/HTB1T8BeJXXXXXXwXFXXq6xXFXXXs/1-Uds-66-pulgadas-36lbs-caza-con-arco-recurvo-retirar-Flecha-de-arco-de-entrenamiento-para.jpg
https://i.pinimg.com/736x/66/29/95/6629959ad99e8d9945f1f59a9b614d3e.jpg

A probably better example of a purely reflex one may be the first and second in here, but I somehow doubt that the other designs were ever user in real life:
https://leyendasmirdalirs.files.wordpress.com/2014/06/evolucic3b3n-del-arco.jpg

Regardless, it doesn't seem like people refer to bows as reflex/recurve even when it would suit it. For instance, these ones refers to the bow as either recurve or reflex depending on where on the page you look but never both simultaneously.
https://traditionalbowshop.com/en/composite-reflex-horsebows/42-hungarian-magyar-bow.html
https://traditionalbowshop.com/en/composite-reflex-horsebows/45-krim-tatar-ij.html
https://www.outfit4events.com/eur/category/303-reflex-bows/
Some stores don't even acknowledge the existence of reflex bows. Not explicitly, at least. Granted, that may be me not looking at the right places but interesting to note nonetheless.

The only site I was able to find that explicitly called a bow reflex recurve is a sword store.
https://samuraiswords.store/reflex-bow/

**Comment by ampersand55** [comment]
I don't like the bow prefixes reflex or recurve. 

* They are technical terms most people haven't heard of which limit intuitive understanding. 
* They are not mutually exclusive with other bow types, like selfbow or composite bow. 
* Pretty much every bow from the 1500s onward is a recurve bow, (or a modern compound). 

I think it's better to class bows by how they are manufactured, representing how hard they are to craft and how effective the are in converting stored elastic energy to kinetic energy. 

Selfbow - made from a single piece of wood. 
Composite bow/laminated bow - made from strips of different natural materials glued together.
Modern bow - having a centre riser section with attached limbs of modern composites such as carbon fibre.
Compound bow - having an advanced levering system to get a mechanical advantage.

Another option is to use semantic naming, i.e. name the bows on what they do instead of their of how they look or how they are manufactured. This has the added benefit of being more intuitive for players.

Some other problems with bows: 

* You could string any type of bow to any draw weight, so different strength requirements doesn't really make sense.
* In reality you can't make a bow out of any plank or stick. You would need an elastic wood such as yew, ash or elm that has dried and been drained of water.

**Comment by Arcangelus** [comment]
Actually, I agree. Mostly. 

If you wanted names based on function, how would that work? Something like training, hunting, competition, war, mutant? Based on whose intentions? Most "old" bows were made for either hunting or war. Most modern bows are made for practice and/or competition. There are no "modern" war bows, yet some do archive similar performances K.E. wise.

Sure, you could go by gameplay use. But then, you have issues when it comes to fabrication. A war bow implies (generally) more damage potential than a hunt bow, yet you could make one in any style (selfbow, compound, composite), each with different implications. One way to solve that is to ignore that diversity. Simply putting "modern warbow" vs "survivor warbow" for the sole purpose of differentiating what is found from "made in house", assign the specifications from an arbitrary bow from that category and call it a day.

An alternative would be to combine how its manufactured with an epithet to factor in intended use. Say, a "practice selfbow", "hunting composite bow", etc. As to how to determine intended use, you could either:
- Based it on draw weight, so it gives an idea of how difficult it is to use.
- Base it on effective K.E., to give an idea of expected performance.
- Base it on the actual intent of the bow. This does lead to the "war longbow = competition compound bow" issue.

The epithet itself doesn't matter as long as it gives a sense of progression: "Practice, hunting, competition, war, mutant" work just as well as "crude, short, long, great, huge" for this as long as there is some consistency. Reference values for draw weight and K.E can be found [here](https://docs.google.com/spreadsheets/d/1wpuAk7F1fJ227yAgYbokwn7KxdEeOv-MGFvnnnW5s1Q/edit#gid=0) (that I assume is still in use).

- If based on draw weight, then harder to use bows are generally more powerful (compounds notwithstanding), while at equal difficulty of use the superior (more involved) manufacturing method leads to more damage.
- If based on K.E., then a simple glance at the epithet will give you a good idea of how effective it can be while none about how hard it is to use.
- If based on actual intent, you get a rough estimate inconsistent between "traditional" and "modern" bows.

A last point about bow skill requirements. If an [average looking person ](https://www.youtube.com/watch?v=BfduY0juAt4)can use a 100lb bow and shoot several times with good accuracy and no obvious sings of exertion, archery skill may be a tad more important than overall strength if for no other reason than the muscles used in archery may be useless to carry stuff. In an ideal world, it would be a function of both. But as no one is doing that anytime soon, and unmet requirements stop you from using the item entirely, the best you could do is to put a low(er) strength requirement alongside an archery one. That would force the player to use lower-tier bows to practice and "develop the muscles" and technique needed to use the stronger ones without injury while simultaneously acknowledging that a basic level of strength is required to do so. Training books only reach Lv3 so you could consider that pure technique, everything after that implying some muscle development.

**Comment by ampersand55** [comment]
> If you wanted names based on function, how would that work? Something like training, hunting, competition, war, mutant?

Yes, basically. But I like the materials approach better.

I also like the idea with naming them by draw weight. The draw weight could represent the elastic energy and strength requirements and the materials could represent the efficiency in converting elastic energy to kinetic energy. Then use a multiplier with the bows instead of the arrows.

* 50lb self bow (6 strength) does 50% arrow damage 
* 100lb self bow (9 strength) does 75 % arrow damage
* 150lb self bow (12 strength) does 100 % arrow damage
* 200lb self bow (15 strength) does 125 % arrow damage

* 50lb composite bow (6 strength) does 75% arrow damage
* 100lb composite bow (9 strength) does 100% arrow damage
* 150lb composite bow (12 strength) does 125% arrow damage
* 200lb composite bow (15 strength) does 150% arrow damage

etc.

**Comment by Arcangelus** [comment]
Friendly reminder that you don't need to be a [mutant](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/GAME_BALANCE.md) to use a 200+lb bow. [Only dedicated.](https://www.youtube.com/watch?v=MjY2QrU4sm4)

That aside, it doesn't sound like a bad idea. Numbers based on real data will probably look less tidy than that, but unless there is a good reason to use the multipliers with arrows I don't see why it wouldn't work.

**Comment by ampersand55** [comment]
Exactly. Strength and draw weight was just round numbers just to make my point clearer.

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/magiclysm-a-total-fantasy-overhaul/20612/393
