### ISSUE TITLE
Android: Trap Back Button Option Not Working in 0.E

### ISSUE THREAD

**Issue by tg122** [CleverRaven/Cataclysm-DDA#39224]
# Describe the bug
In Android 10 version 0.E full screen mode, the back button on my phone disappears even though I selected Trap Back Button = True.  Using a Pixel 3xl.

# Steps To Reproduce

When running version 0.E for the first time, select the Force Full Screen option and the Trap Back Button option.  As soon you click to move on to the title screen, the back button disappears.  Restarting the game does not fix the issue.

# Expected behavior

I expected the back button to remain present at all times as long as the Trap Back Button option is enabled.  Currently, I have to swipe right to left to bring the back button back into view, which results in an accidental swipe in game.

# Screenshots

# Versions and configuration

# Additional context

**Comment by ZhilkinSerg** [comment]
Sorry, but that is not what Trap Back Button option does :)

That option is only meant to change behavior of what happens when Back button is pressed, not whether on-screen controls are displayed. I have plans to implement some in-game on-screen control which would be used to toggle virtual keyboard, but until it is not implemented please do not use fullscreen mode.

**Comment by tg122** [comment]
Ohh my mistake!  Thanks for the response!

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/virtual-keyboard-not-showing-android/24792/4
