### ISSUE TITLE
Cordless Drill retains drilling and screw driving qualities even without charges.

### ISSUE THREAD

**Issue by 182crazyking** [CleverRaven/Cataclysm-DDA#39246]
# Describe the bug

The item Cordless Drill has Drilling 3 and Screw Driving 1 for the purposes of installing vehicle parts (and likely crafting, although I didn't test that) even when it doesn't have a battery or charges. Likely related to #29447, assuredly related to #26534.

# Steps To Reproduce

1. Generate character with maximum Mechanics.
2. Spawn frame, 2L metal tank, cordless drill (unloaded, no batteries in sight).
3. Install the metal tank using nothing but the powerless drill and your willpower.

# Expected behavior

Cordless Drill (off) might have screw driving 1, then turns into Cordless Drill (on) with screw driving 1 and drilling 3. Alternatively, audit crafting recipes that require drilling and make them consume charges (a la welder/hobo stove)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E [64-bit]
- Graphics Version: Tiles
- Game Language: System language [English]
- Mods loaded:
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Monsters [No_Fungi],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]

**Comment by OddSkollar** [comment]
Can confirm this bug. Possibly related, though I haven't tested it yet to confirm: an acetylene torch that's being dragged by the player (but not carried) doesn't seem to consume charges when cutting open things like lab doors.

Given that an attempt has already failed at fixing this by using cordless drill [on] as a tool with drilling 3 (and my own frustrations attempting to use charges of candle[lit] as a recipe component rather than a tool, which may be related), I suspect that your 2nd proposed approach may be more helpful, pending someone more knowledgable than myself diving into the cpp code.
