### ISSUE TITLE
Crash when opening followers list

### ISSUE THREAD

**Issue by GGgatherer** [CleverRaven/Cataclysm-DDA#39271]
# Describe the bug

Game crashes when you open basecamp/follower menu (#) and switch to followers tab.

# Steps To Reproduce

Load attached save, press #, press tab, see crash.

# Expected behavior

No crashes.

# Versions and configuration

- OS: Windows 7x64
- Game Version: 0.E-291-gac0d129 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Aftershock [aftershock],
    Alternative Map Key [alt_map_key],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Skills [StatsThroughSkills],
    Magiclysm [magiclysm]
]

# Additional context

Didn't happen yesterday. The only 2 differences are I updated to 10489 from 10481, and found new NPC with raptor mutation tree.

[crash-debug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4432911/crash-debug.zip)
[save](https://drive.google.com/open?id=1Ytppl711QEdcQ1TVcUZQR_gulfiLjDxM)

**Comment by Inglonias** [comment]
Same crash occurring here.

**Comment by wapcaplet** [comment]
I can reproduce this in a fresh game, but only after acquiring a follower.

**Comment by wapcaplet** [comment]
I ran a `git bisect` on this between a known good revision 8abe67dfce and known bad revision ac0d12947. Due to a series of commits that would not build, I did `git bisect skip` on several, and could only narrow it down to a series of commits that may have introduced the bug. Here's what git bisect reported at the end:

There are only 'skip'ped commits left to test.
The first bad commit could be any of:
97353c3da77c3b8a9685b3e7c41f2f8d77bcd825
05580e95534188f7e3d35bbeed17668643c04082
5b37e58b2071cb35505f5537258b4444e3b5ff49
166130fb6d7931377c759eab136bea40c867eca6
254227aa8abbcefb94baca9429e72179593c565e
0298cb2793f1ddaa8c8dd1afb432c707243e68be
c3dfa49df14ca62d553f56e95301ab542c51bdb1
015a1b2fbde843c7b75e065b3265871c00f1211e
