### ISSUE TITLE
Folding bicycle magically repairs itself

### ISSUE THREAD

**Issue by Dacendeth** [CleverRaven/Cataclysm-DDA#39399]
# Describe the bug
The folding bicycle item that the cyclist starts with magically repairs itself upon folding and redeploying, fixing any and all damage. 

# Steps To Reproduce
1. unfold the fold-able bicycle item
2. smash it with a sledge hammer, breaking even entire sections off
3. fold it and redeploy it and see it's in perfect condition again.

# Expected behavior
For my damaged bike to retain it's damage.

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-414-ge0bf561 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context
Another random note the folding bike itself isnt even made out of a foldable frame and you cant take apart or add anything to it. It appears to be something different than a normal player made fold-able vehicle.

**Comment by BevapDin** [comment]
The whole folding bicycle item should go away. It is either inconsistent or redundant:

It's inconsistent because it creates (when unfolded) a vehicle that could have been made via the vehicle interface (frames, saddle, wheels, etc.) However, making the item requires different tools / tool charges and different time than making the vehicle.

Fixing that inconsistency (which may get unfixed as soon as somebody changes the vehicle part installation settings), would make the item redundant. One can instead just make a vehicle and fold that. Why make an item, if it takes the same resources?

Therefor it should be removed.

Note that vehicles creates via the vehicle interface can be made with special properties (someone might want a bicycle with a horn, different cargo part, different wheels ...)

**Comment by ParaplegicRacehorse** [comment]
I agree that this should ideally be crafted via the vehicle interface. However, there being actually foldable bicycles in the world, I would like to retain it's folding aspect. And, yes, the magical repair thing is just wrong. Not that I've ever had a problem with zeds bashing my bike...
