### ISSUE TITLE
Artificial night generator CBM makes creatures invisible to the player

### ISSUE THREAD

**Issue by axujen** [CleverRaven/Cataclysm-DDA#39558]
# Describe the bug
Using the artificial night generator CBM makes creatures standing in lit tiles invisible to the player

# Steps To Reproduce
Use artificial night generator cbm
Spawn a creature in a lit tile
Notice the player cannot see the creature but the terrain is visible

# Expected behavior
Player should either be able to see the creature OR not be able to see anything.
right now the player can see the terrain but not the creatures

# Screenshots
<details><summary>Screenshots</summary>

[![2020-04-14-121630-1366x768-scrot.png](https://i.postimg.cc/MTXpsrSP/2020-04-14-121630-1366x768-scrot.png)](https://postimg.cc/JDV80xtZ)

[![2020-04-14-121805-1366x768-scrot.png](https://i.postimg.cc/FK58RTGf/2020-04-14-121805-1366x768-scrot.png)](https://postimg.cc/QFm0Yk2s)
</details>

# Versions and configuration
<details><summary>Version Info</summary>
- OS: Linux
    - OS Version: LSB Version: 1.4; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.E [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]
</details>

# Additional context
- Theres alot of wonkiness in the interaction of bright and dark tiles and i suspect this is one them and the easiest way to replicate.
- If the creature is far away enough from the player it can become visible again, this seems to depend on the player perception
- Have very high perception (ex 100) allows you to see the creature
- All forms of night vision mutations, cbm and goggles dont help with the exception of the debug night vision mutation

**Comment by GGgatherer** [comment]
Terrain is visible because of map memory, same as if you put on the blindfold or activate whatever that bionic is called, eye dampeners or something. I don't see what exactly could be considered a bug here.
Or do you mean you can, say, go around the corner you haven't seen before while ANG is active and see that, previously unseen, terrain while not seeing any creatures that are/could be there?

**Comment by axujen** [comment]
> Terrain is visible because of map memory, same as if you put on the blindfold or activate whatever that bionic is called, eye dampeners or something. I don't see what exactly could be considered a bug here.
> Or do you mean you can, say, go around the corner you haven't seen before while ANG is active and see that, previously unseen, terrain while not seeing any creatures that are/could be there?

Thats not how terrain memory works, terrain memory tiles show as Darkness and you cannot see items on the ground in terrain memory, you can with artificial night generator.
[2020-04-14-125657-1366x768-scrot.png](https://postimg.cc/Lg5FRJ67) <- Terrain memory tile when e(x)amined.

**Comment by Dacendeth** [comment]
Yeah this is a weird one, even at night with night vision every actor outside of the field of your generator is just invisible while it's toggled on. Another oddity of this CBM is enemies normal night vision doesnt even work while in the area, as you can stand directly next to a turret without it shooting you.

**Comment by Fris0uman** [comment]
I can reproduce the bug:

Night generator off:
![image](https://user-images.githubusercontent.com/41293484/79224254-10f77d00-7e5b-11ea-8f19-775074d9a20f.png)

Night generator on:
![image](https://user-images.githubusercontent.com/41293484/79224279-1a80e500-7e5b-11ea-8478-fa23bfe515ad.png)

**Comment by GGgatherer** [comment]
Um, is that particular thing (not seeing enemies while NAG is active) actually a bug? ANG is described to remove/disrupt all light in area near you. Since seeing something means receiving light reflected from/emitted by that something, it seems to me not seeing enemies is how it should work. And I remember it working just like that.
It's being able to see anything, be it terrain, monsters or items, that looks like a bug to me.
