### ISSUE TITLE
Eating/taking non-foods should not trigger Rigid Table Manners debuff

### ISSUE THREAD

**Issue by cupnooodle** [CleverRaven/Cataclysm-DDA#39580]
# Describe the bug
Drinking water bottles, taking medicine (and other non-food items) without a seat/table nearby triggers the _Ate like an animal_ debuff

# Steps To Reproduce
1. Create a character with Rigid Table Manners trait
2. Spawn in aspirin and eat it
3. Open up Morale menu to realize the negative morale hit

# Expected behavior
These are not food, per se, and shouldn't receive the debuff for consuming without a seat/table.

# Screenshots

# Versions and configuration
PS: Windows 10 64bit
Game Version: 0.E Stable
Graphics: Undeadpeople
Mods: None

# Additional context

**Comment by wapcaplet** [comment]
Confirmed, I can reproduce this issue by eating some aspirin with the rigid table manners trait. This penalty is applied starting with this part of `consumption.cpp`:

https://github.com/CleverRaven/Cataclysm-DDA/blob/14415de010a019c1cf9c4bed49589cb1b6da9083/src/consumption.cpp#L1105-L1107

Perhaps in order to prevent aspirin or other medicines from being penalized like other edibles, this condition should exclude `comestible_type: MED`.

**Comment by ZhilkinSerg** [comment]
Didn't we fix that (or something similar) in #38804 already?

**Comment by wapcaplet** [comment]
> Didn't we fix that (or something similar) in #38804 already?

Yes, the first fix was #38700 (preventing morale penalties for applying bandages without a table), but it went too far and removed morale buffs for other drugs too - so #38804 fixed that and restored morale buffs (without table effects) all the `NO_INGEST` fun drugs (cigars, meth, heroin, cocaine, bubble gum), along with a test case that covers all of them.

This issue here covers yet another class of "edible" items, the medicinal drugs such as aspirin (and possibly codeine, antifungals, and whatever other `MED` items do not also have the `NO_INGEST` flag.

It occurs to me that there is a third class of edibles, *drinks*, which would also give the morale penalty/buff for rigid table manners. Whether drinks ought to qualify for this trait, I don't know.

**Comment by jbytheway** [comment]
I think it would be best to add a new flag for comestibles which can be readily eaten without a table rather than try to infer a heuristic.
