### ISSUE TITLE
Fatal tempretures do not interrupt sleep.

### ISSUE THREAD

**Issue by Tamiore** [CleverRaven/Cataclysm-DDA#39593]
# Describe the bug

When a character goes to sleep in a (relatively) comfortable environment, and then the temperature drops down to the point where tissue damage occurs, this does **NOT** wake up the character.
Instead the character simply takes the damage, even if it breaks limbs and/or kills outright.

# Steps To Reproduce

1. Go to sleep with perceived temperature level above "very cold".
2. Allow the temperature to drop to the point where frostbite occurs while sleeping. (For example, because a nearby fire run out of fuel.)
3. Proceed to take damage without waking up once.

# Expected behavior

When perceived temperature drops low enough, character wakes shivering and can't sleep again without warming up first. 

# Versions and configuration

  - OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-732-gd0f0a96 [32-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Slots [cbm_slots]
]

# Additional context

An argument can be made that a character may fail to wake up if he was already **severely** hypothermic (actively taking damage from frostbite) and somehow managed to fall asleep.

Or if the character was exhausted to the point of passing out and/or **very** sick. Or immune to pain.

But an otherwise healthy character capable of feeling cold and pain should not be able to sleep into frostbite.

**Comment by mlangsdorf** [comment]
Do you have a cite for the idea that people will wake up as the temperature drops into extremes?  I really don't know here.

**Comment by Zireael07** [comment]
Temp dropping/raising into extremes will cause pain and/or discomfort, which does tend to wake people up.

**Comment by Tamiore** [comment]
>Do you have a cite for the idea that people will wake up as the temperature drops into extremes? I really don't know here.

Sure:
https://thehikingauthority.com/freeze-to-death-while-sleeping/

>So does sleeping increase your chances of freezing to death? Yes you can freeze to death while sleeping, but only if you’re already badly suffering from the cold. **Unless you’re already severely hypothermic you won’t freeze to death in your sleep.**

**Comment by kevingranade** [comment]
That's pretty definitive, thanks.

**Comment by Amoebka** [comment]
If what wakes people up is uncontrollable shivering, not pain, then pain reducing mutations won't matter here either.

**Comment by CodeBandit** [comment]
Created a pull request to fix this issue in #39827 basing it off of realistic standards and "There’s no sleeping through the early stages of hypothermia."

**Comment by Je55eah** [comment]
This was just happening to my character who was sleeping in a bed with gloves and blankets in a house that had a fire burning earlier on the 6th day (so it's spring or summer something). The frostbite impending warnings were there, but I couldn't wake my character and it all seems really stupid.  

Then I was woken up by a portal storm... and I don't know how to feel about that. I sent my character outside and battled weird shapes and purple blobs which didn't fight back. There was alien grass, which I avoided, but a zombie dog walked through it unharmed. Is this part of some kind of delusion? I hope the game explains everything at some point because between this run which has been all zombies, and a portal storm and an earlier run which had zombies, eyballs, eldriches, megos, alien dogs, tremor worms, spiders, and more on the first day it seems like the earth has been invaded by every b-movie. Is my character hallucinating all of it? The newspapers suggest there was a chemical attack. If the monsters are all in my characters imagination, then I hope he kills himself before more innocent people are killed. I was hoping this game would be more realistic. 

It's not though. Crafting a spear should take a few hours, top, but instead my character spend a day and a half carving and he still has something like five more hours of crafting needed to make a knife spear. Should it really take two days to attach a knife to a pole? Game mechanics such as tech trees, portal storms, and sleeping into frostbite all force the player to do boring things. grind the tech tree, confront the impotent storm creatures, wear a second layer of mittens before going to sleep.
