### ISSUE TITLE
multi drop menu does not like number hotkeys

### ISSUE THREAD

**Issue by shpookys** [CleverRaven/Cataclysm-DDA#39709]
# Describe the bug
the multi drop menu when dropping items works normally with letter keys and arrow keys but seems to not want to work with number keys numpad ones and regular ones

# Expected behavior
that when the number hotkeys when used would work when pressed
since there are apparently some by default that you can "use"

# Screenshots
![CDDA](https://user-images.githubusercontent.com/16250856/79678107-a2912280-81ac-11ea-803c-142b0814f2bb.png)

 
# Versions and configuration Version: 0.E-899-g5738946
 - OS: Windows 10
 - Game Version: [from the main menu, e.g. 0.C-29938-g90f5268437]
 - Ingame language: english

**Comment by shpookys** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/issues/27898 apparently someone also has/had this issue

**Comment by esotericist** [comment]
For the sake of clarity, this is not a bug or oversight; the multidrop menu is designed so that you can drop part of a stack by typing a number before hitting `->`

for instance if you have 20 planks, you can select it with arrow keys, type `10` using numbers, then press `->` right arrow, and you'll only drop 10 planks rather than the whole stack.

making this menu able to respond to numeric input for navigation without breaking that functionality is rather tricky.

**Comment by esotericist** [comment]
After spending some time reviewing this, I don't think this is a thing that can be done reasonably.

The usage of number input to specify quantity to drop is a crucial feature, and there's no coherent way to signal through normal game input whether you want to specify a specific number or do navigation using numeric input.

That said: if you're using a numpad on any kind of modern keyboard, you pretty much by definition have access to "numlock", which lets you toggle between numeric input and cursor navigation. This is probably the only coherent way to get what is requested here.
