### ISSUE TITLE
Auto-pulp/butcher should disable automatically when threats are near

### ISSUE THREAD

**Issue by gcaliber** [CleverRaven/Cataclysm-DDA#39726]
# Is your feature request related to a problem? Please describe.
Auto-pulp has to constantly be toggled on and off or repeatedly stopped when threats are nearby. I can't think of a situation where I actually want the current behavior. If I really need to pulp a corpse ASAP it would be easier to just do it manually.

# Describe the solution you'd like
All I want is for auto-pulp to disable automatically or with a single prompt when threats are nearby and re-enable automatically when they are gone. Essentially the opposite of what Ignore does right now, I want to Disable pulping until it is safe for it to be on again.

**Comment by jesus-ramos** [comment]
Works fine with Safe Mode on

**Comment by jesus-ramos** [comment]
Looks like when you ignore enemies it doesn't count them as being seen for purposes of disabling auto pulp/butcher. I threw this patch together really quick for changing the check so that it can disable the auto features if hostiles are nearby instead of non-ignored enemies.

https://github.com/jesus-ramos/Cataclysm-DDA/commit/54064216ec9ac02bfb1aec2c4d52c8e2065dc78f
