### ISSUE TITLE
0.E Stable Mapbuffer terrain data corrupt.

### ISSUE THREAD

**Issue by JuicyJuiceJubei** [CleverRaven/Cataclysm-DDA#39786]
(This is my first bug report so don't be on my case.)
 
# Describe the bug:
This bug doesn't show up when you are playing, only after you've save and quit the game. Trying to load back into the game on the character you last played on, you will be met with an error message that reads "Error Report: Debug: Mapbuffer terrain data is corrupt, expected string or array."
In game, this can drastically warp your map, making buildings on your map nothing but a dark silhouettes that are just shadows. Some roads end and trail off into forests, but on the minimap it will keep telling you you are on a road when there is none is sight.

**Comment by Qrox** [comment]
Please upload a save that reproduces this error message. Without a save it's hard to say what's actually causing the problem.

**Comment by int-ua** [comment]
@JuicyJuiceJubei template for reporting bugs is there for a reason. I bet files were corrupted not by the game itself since for now this is the only similar issue reported. Did you have sudeen reboots or power loss on the system you are playing? Or maybe you've run a script that edited all JSON files in a directory?
