### ISSUE TITLE
Discussion: backpacks coverage

### ISSUE THREAD

**Issue by matt32106** [CleverRaven/Cataclysm-DDA#39846]
TL;DR Backpacks coverage is too high?!  

Excuse me if this had been discussed already.
Most of the time, except if you are suicidal, the things you fight are in front of you and I don't see how a backpack can provide 50% torso cover, it being in your back. If the combat logic does not take the relative positions of fighters into account then these values are too high except when the char is surrounded which should be rare?! What do you think?

**Comment by FuelType-Memes** [comment]
In the current state of the game you cannot really tell where your character is currently pointed at. This is even without talking about situations where you're being attacked from multiple side

And I would say your back is ~50% of your torso. Maybe if you have a big belly or you're gifted (cursed?) in the chest area percentages might change, but this is a good approximation

**Comment by matt32106** [comment]
> your back is ~50% of your torso

yes and it is your *back*, and when you fight a limited number of opponents you try to never show them your back, so the protection of the backpack should be closer to 0%. And I would say it is 50% when you have 8 zombies around you because then half of them are behind you. 
So I'd like to suggest one of two mods:
- if we can easily know the number N of Z's adjacent to a char, the coverage can be moderated by N/8.
- else I would suggest modifying the json to lower the coverage of bags worn on the back (divide by 2?)

**Comment by Tamiore** [comment]
> yes and it is your back, and when you fight a limited number of opponents you try to never show them your back

Then how do you maintain perfect vision behind your back if you never turn?

**Comment by glenmack** [comment]
> In the current state of the game you cannot really tell where your character is currently pointed at. This is even without talking about situations where you're being attacked from multiple sides
> 
> And I would say your back is ~50% of your torso. Maybe if you have a big belly or you're gifted (cursed?) in the chest area percentages might change, but this is a good approximation

Are you 2 dimensional? Because I have sides as well as a front, and none of my backpacks cover my sides. even my hiking pack barely covers any of my sides.

35-40% For really large backpacks is more reasonable.

**Comment by CoroNaut** [comment]
You can think of the zombie cutting the strap across your shoulder as well which would at least make the backpack fall off of you. 

In situations where you are 1v1, yes you would keep your front to the enemy and have maybe 10% coverage to your backpack. 1v2 is you fighting a zombie head on, with one flanking you in any other position, 1v3 and more is even more so. it is unrealistic to make backpack coverage 0% or even 10% in the average case. Everyone's play style will determine the average number of zombies they fight per battle, but I would say 1v2 is close enough. Using this interpretation, I would say about 30-35% coverage for backpack makes sense if both are infront of you.

There is a clear idea for why we have 50% to begin with, and thats that a zombie can sneak up behind you in some scenarios, in which case, the zombie infront sees a 10% coverage, zombie in back sees 100% backpack coverage. This is an average of ~55% coverage. So the 50% makes sense.

This is really a game of chance as to what your next fight is gonna look like, and since it is nearly impossible to tell, a 50% coverage is just a nice average coverage for the vast majority of scenarios.

**Comment by meladath** [comment]
I also think that even the largest backpacks should be ~35% in realism terms, very few packs cover your sides.
Now that nested containers are the way forward, I think a backpack tweak is something worth looking into, just how they work in general/pocket sizes perhaps. 
It makes no sense for example that I cannot have my gun sticking out the top of my backpack because its too long for the pocket. Perhaps add extra penalty to speed for it?

**Comment by kevingranade** [comment]
We're assuming any pockets are closed, otherwise we'd be looking at things falling out of pockets as you move around, I don't think anyone wants that.
Also as you say, movement penalties for having things swinging around.

That's a lot of hassle to add something that you should pretty much never do.
