### ISSUE TITLE
Can fall when climbing down a stepladder

### ISSUE THREAD

**Issue by sick-trigger** [CleverRaven/Cataclysm-DDA#39892]
# Describe the bug
You can slip and fuck yourself up when climbing down onto a stepladder, despite it saying you should be able to climb back up easily.

# Steps To Reproduce
1. place stepladder next to building
2. climb up and down it over and over until you fall
3. break legs, rage quit

# Expected behavior
using a stepladder to climb down a roof should be 100% safe. When climbing down from a roof via an unsafe method the game should /very clearly/ indicate you might fall off for massive damage.

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.E-1182-g9f6568b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context
The changes to climbing down added in #39635 were incredibly rude and falling off a roof is infuriating when it happens.

A better solution is to put it back how it was, where you can either safely climb down somewhere or you cannot, without any RNG,  and with a clear message indicating that you're about to fall, and then just remove climbing up downspouts altogether, with maybe some exceptions for the parkour trait.

**Comment by Night-Pryanik** [comment]
> You can slip and fuck yourself up when climbing down onto a stepladder, despite it saying you should be able to climb back up easily.

And where's the contradiction? You really can climb back **up** easily, it doesn't say anything about climbing **down** easily or safely.

> using a stepladder to climb down a roof should be 100% safe.

When you're climbing down from any roof, you're **NOT** using stepladder, or downspouts, or any other furniture or terrain. It's simply not implemented at the moment. Every time you climb down from a roof, in fact you're climbing down, using only your hands, that's why you can really easily slip down and fall off.

> When climbing down from a roof via an unsafe method the game should /very clearly/ indicate you might fall off for massive damage.

Isn't that obvious? Climbing down from a roof is dangerous as hell.

>rage quit
>infuriating

Maybe you should calm down a little? Even if it's a bug and must be fixed, it's not a reason to go into berserk mode.

**Comment by sick-trigger** [comment]
when you try climbing down somewhere without something below to climb down you get a message warning you that it might hurt, which gives the impression you don't have to worry about damage when the message is only concerned with how difficult it'll be to get back up (which is how it used to behave)

using roofs to escape and abuse monster behaviour does need to be balanced somehow, but a random chance for your character to just be clumsy and receive lots of damage and pain is frustrating for the player. If you can safely climb up somewhere it stands to reason that you should be able to safely climb down the same route, assuming you are in the same state and the zombies haven't smashed your ladder

(and sorry is my word choice was too strong it's no worries :p)

**Comment by Tamiore** [comment]
It feels like there should be an option for very **slow**, but safe decent (as long as you are going just a single Z-level down). 

By "slow" I mean 30+ seconds. 
And by "safe" I mean "some pain and falling prone as the worst outcome".

**Comment by Night-Pryanik** [comment]
> but a random chance for your character

The chance is not totally random. It's based on character's dexterity. For a default 8 dexterity character the chance to slip down while climbing is 12.5%. Sure, it could be tweaked to be more/less frequent, but I think removing it altogether is a step back.

> If you can safely climb up somewhere it stands to reason that you should be able to safely climb down the same route, assuming you are in the same state and the zombies haven't smashed your ladder

As I said previously, currently you don't climb down the same route as you climbed up. Climbing down doesn't take any furniture/terrain you used for climbing up into account. Essentially you're asking for a serious rework of "climbing down" mechanics.

**Comment by sick-trigger** [comment]
it must consider furniture on the terrain at some point because you get a different message when examining a tile with a stepladder below, compared to the tile next to it, or the same tile with the stepladder removed. 'Should be able to climb back easily' vs. 'Jumping down might hurt', as well as what seems like an increased (what used to be guaranteed) chance to clamber down without issue

**Comment by wapcaplet** [comment]
There is a problem with inconsistent messaging here. I tested in 6c4120d528, a master branch as of today, but any recent version will probably work.

First, setup: Spawn in an evac shelter, spawn a stepladder, set up the ladder next to the outside wall, and climb onto the roof. All well and good - one assumes a sturdy ladder will allow safe passage up and down.

Now that we're on the roof, let's `x` or mouse-over the tiles next to the ledge. One of them is just open air with no support:

![image](https://user-images.githubusercontent.com/238395/80547815-64e38500-8976-11ea-9c99-c0ccd6a769e3.png)

Pressing `e` to examine that tile gives the ledge prompt - and if I say `c`limb down, I get a warning!

![image](https://user-images.githubusercontent.com/238395/80547897-93616000-8976-11ea-9e63-3e5ac56765ae.png)

On the other hand, the brown tile with my stepladder does show there is a stepladder on the ground below (though it also says "no support", curiously):

![image](https://user-images.githubusercontent.com/238395/80547822-68770c00-8976-11ea-8d33-6f573ac235ad.png)

Unlike before, using `e`xamine on this tile, then selecting `c`limb down, I get a *different* message than before, saying "You should be able to climb back up easily if you climb down there."

![image](https://user-images.githubusercontent.com/238395/80547975-d1f71a80-8976-11ea-926b-21de8750eb71.png)

It sure sounds safe. Guess I'll go for it. Look, I made it down safely! Must be OK. Six more trips up and down, no problem. Then, suddenly:

![image](https://user-images.githubusercontent.com/238395/80548108-4cc03580-8977-11ea-8e5a-2bdb74b003d5.png)

So I agree with @sick-trigger that the messaging is misleading/inconsistent here. It sure seems to suggest that climbing down onto the ladder is safe, and the high chance of it actually *being* safe only reinforces that belief.

Now, I also agree that climbing down probably shouldn't always be a guaranteed success, but if that's the case, the message needs to suggest that. Rather than "You should be able to climb back up easily if you climb down there", it should say "You are pretty sure you can climb down safely, but you would feel better if you had a rope" (assuming that would help), or even "It looks a lot harder to climb down than it did to climb up here."

**Comment by Night-Pryanik** [comment]
> It looks a lot harder to climb down than it did to climb up here

You can slip down with the same chances both when climbing up and when climbing down.

**Comment by wapcaplet** [comment]
> > It looks a lot harder to climb down than it did to climb up here
> 
> You can slip down with the same chances both when climbing up and when climbing down.

The chances of falling seem very different when going up and down - in fact I have never yet fallen when climbing **up** a stepladder. When I tested just now, I climbed up 30 times with 0 accidents. But coming back down, I fell down 5 times out of 30. It's possible I need to do more trials, but I would rather spend the time writing a test case to understand what the different chances are. I believe there is no chance of injury going up.

But either way, the message when `e`xamining the ladder from the rooftop should suggest that there is some risk to climbing down, since it *is* risky.

**Comment by Night-Pryanik** [comment]
> I need to do more trials, but I would rather spend the time writing a test case to understand what the different chances are.

There's no need for tests. Because you added a check for slipping _when climbing up_ for unstable terrain in #39705, you'll never slip down when climbing up by stepladder, as it doesn't have the `UNSTABLE` flag. We could add an `UNSTABLE` flag to the stepladder, so you could slip down when climbing up by the stepladder too.

**Comment by sick-trigger** [comment]
what is the problem with simply having stepladders be safe to use?

sometimes people do fall of ladders, but for every fall there are literally thousands of times a ladder was used safely. If you try and model this, all you're going to have is an occasional little 'fuck you' to a player.

**Comment by Night-Pryanik** [comment]
> what is the problem with simply having stepladders be safe to use?

Maybe that no one volunteered to rework the climbing down mechanics?

I'm tired of repeating that one don't use any terrain/furniture (stepladders, downspouts etc) when climbing down. In order to make "stepladders be safe to use" we need to completely rework the current climbing down mechanics.

Climbing up is already safe for stepladders.

**Comment by sick-trigger** [comment]
before #39635 they were safe to use, but climbing down a wall without one carried a risk. What, aside from downspout climbing which I'd be in favour of completely removing, was wrong with that behaviour? And why would returning to it require a rework?

**Comment by Night-Pryanik** [comment]
I repeat it once again. There is no such thing as _climbing down the downspouts_ or _climbing down the stepladders_. You simply _climb down_, using only your bare hands. And 100% safe climbing down in this conditions is unrealistic and unfun.

**Comment by sick-trigger** [comment]
Before the changes, _there was such a thing as climbing down a stepladder or downspout_. Examining a tile, with a stepladder deployed on the tile directly below, and choosing to 'c'limb down was 100% safe. Doing the exact same thing with the stepladder removed was not. On the stable build you can go up and down a stepladder over and over and never fall. Remove the stepladder, teleport back up and try the same thing and you fall pretty much every time. What is happening if not climbing down the stepladder? This was both more realistic and less frustrating than a 12.5% chance for an average human to lose their footing and severely injure themselves whenever they use a ladder to climb onto a single storey roof.
