### ISSUE TITLE
Stones and sharp stones have a higher throwing range than smaller pebbles

### ISSUE THREAD

**Issue by RafeHaab** [CleverRaven/Cataclysm-DDA#39948]
# You can throw bigger stones at +15 tiles with strength 8, but pebbles (made by crushing said stones) have a 5 tiles range when thrown by hand and with the same stats. This problem extends to sharp stones too.

# Steps To Reproduce

# Versions and configuration

 - Game Version: 1584
 - note #1: you can drag and drop files in this issue post!
- note #2: it is very important for us that you provide a save file in case of a crash. It really helps the developers
    to reproduce the bug and fix it. If possible, try to provide a save file that occurs in the right conditions, just
    before the crash happens. -->

**Comment by jeremyshannon** [comment]
I dunno, anecdotally it seems to me that as a stone gets smaller,  the distance I could huck it does tend to get longer, but there's a point where I start to lose range because the mass of the stone gets too small for me to impart a decent amount of force by hand.

 I guess some numbers would be good for determining whether this is a bug or not. Somebody's probably studied "how far can you chuck different sizes and types of rocks?" right?

**Comment by TartarusKelvin** [comment]
Doing some vague scratch paper calculations:

A rock has a mass of 657g while a pebble has a mass of 10g so you could expect someone that could throw a rock 15 tiles could through a pebble at atleast 985 tiles which seems rather extreme. This doesnt account for drag either so it would be even farther according to physics. Since I think the mass of pebbles is artificially low since its an ammo. If you go by volume instead you get around 150 tiles which seems more reasonable but still way to far.

I would suggest maybe adjust the throw distance for a stone to be 10 tiles with a strength of 8 and the adjust pebbles to maybe 25?

**Comment by jeremyshannon** [comment]
Problem is you can't impart force equally. The upper limit of throwing force is going to be determined by the top speed at which you can whip your empty hand through a throwing motion.
 Optimal rock size should be the heaviest thing you can get up around that top speed, as a heavy object going n miles per hour will have much more kinetic energy to resist drag than a light object also going n miles per hour. Heavier objects absorb more energy, but increasing resistance from the mass soon prevents you from reaching top speed.
 Assuming shape and density to be equal, a small palm-sized rock should fly much farther than a pebble the size of a marble. But I don't have any non-anecdotal data to back that up, just childhood memories of flinging rocks.

**Comment by JeanLucVanDamme** [comment]
Exactly, small pebbles are actually much harder to throw long distances compared to reasonable-size rocks. 

As an example, compare a baseball vs a small pebble. A person of average strength and throwing ability can throw a baseball 100 or more feet. It's about 100 feet from home base to 2nd base in a Little League field (baseball for elementary school children).
