### ISSUE TITLE
Cattle fodder & containers

### ISSUE THREAD

**Issue by ScampsAdams** [CleverRaven/Cataclysm-DDA#40137]
# Describe the bug

Errors when picking up cattle fodder, activating it.

# Steps To Reproduce

1. Load attached save, go to barn, pick up cattle fodder(frozen)
A few errors later cattle fodder fits into cargo pants.
"tried to put an item in a container that cannot contain it"

2. Walk up to a horse, try to activate cattle fodder.
Fodder disappears, horse is not tamed, error "Failed to obtain target item"
Works correctly if fodder is wielded.

# Expected behavior

No errors

# Versions and configuration
Build 10619, Tiles-64, Windows 7
Mods loaded: [  "dda",  "no_npc_food",  "Graphical_Overmap",  "No_Fungi",  "cbm_slots",  "stats_through_kills"]

# Additional context

[Dade Cities.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4574347/Dade.Cities.zip)

**Comment by ScampsAdams** [comment]
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4574373/debug.log)

**Comment by Resok** [comment]
I also got the same error when picking up aspirin, antifungal drugs, and a ton of other small drug-like items.

# Describe the bug

Error 'tried to put an item in a container that cannot contain it' when picking up drugs.

# Steps To Reproduce

1. Start new game
2. Wear some kind of storage 
3. Spawn antifungal drugs with debug menu
4. Pickup antifungal drugs

# Expected behavior

No error when picking up drugs and fitting them into general pockets.

# Screenshots

![image](https://user-images.githubusercontent.com/5217673/81041519-e9e10980-8e62-11ea-9afb-f6d1497266dd.png)

![image](https://user-images.githubusercontent.com/5217673/81041540-f5343500-8e62-11ea-8f19-644d768f72a3.png)

Error -

00:03:40.435 ERROR : src/item.cpp:8147 [int item::fill_with(const itype&, int)] tried to put an item in a container that cannot contain it

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-1778-g781ca2e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda]
]

# Additional context

Same error occurs when picking up Aspirin, antibiotics, syringe of adrenaline...

Also tried with jeans, hoodie, backpack, hiking backpack... all with the same result.

**Comment by ScampsAdams** [comment]
Build 10689, both fixed
