### ISSUE TITLE
(Nested Containers) Dropping items crash: MinGW runtime Assertion - Assertion Failed

### ISSUE THREAD

**Issue by DillonSimeone** [CleverRaven/Cataclysm-DDA#40154]
# Describe the bug

The game crashes when dropping lots of (edit: different) tiny items at once.

# Steps To Reproduce

1. Load my save up (Attached at the bottom, along with mods)
2. Spam `I` to ignore all of the scary red messages
3. `d`, `tab`, `right arrow`, `down arrow`, `right arrow`, `enter` (This selects all of the paperwrappers in my inventory and drop them)
4. Cry when the game breaks

# Expected behavior

All paperwrappers gets dropped.

# Screenshots

![image](https://user-images.githubusercontent.com/21962421/81013639-57177f00-8e10-11ea-8e82-79fe9574b7bb.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-1737-g11714a3 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    XEAS [XEAS],
    DinoMod [DinoMod],
    Crazy Cataclysm [crazy_cataclysm],
    My Sweet Cataclysm [my_sweet_cataclysm],
    More City Locations [cityside],
    No Rail Stations [No_Rail_Stations],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Arcana and Magic Items [Arcana],
    Graphical Overmap [Graphical_Overmap],
    Advanced Gear [adv_gear],
    Mining Mod [Mining_Mod]
]

# Additional context

Save: 
[Palmer Heights.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4577507/Palmer.Heights.zip)

Mods: 
[mods.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4577489/mods.zip)

Crash + debug log: 
[crash.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4577498/crash.zip)

**Comment by DillonSimeone** [comment]
@KorGgenT 

I just noticed, dropping that one paper wrapper of chocolate THEN the other paper wrappers gets it to go though just fine.

**Comment by DillonSimeone** [comment]
![image](https://user-images.githubusercontent.com/21962421/81137019-14d66680-8f12-11ea-9410-461d83ff218c.png)

Cut myself on this edge again.

**Comment by Resok** [comment]
Saw this same crash when dropping everything from my inventory that included a bottle of antiseptic.

**Comment by Resok** [comment]
# Describe the bug

Dropping 'all' from 'held' items that contains containers that are filled with liquids will result in a crash.

# Steps To Reproduce

1. Load attached save
2. Note bottle held in hands that contains antiseptic
3. Hit 'd' to drop items
4. Hit hotkey for select all (note that you cannot manually do this item by item) - default I believe is comma ','
5. Confirm drop

# Expected behavior

No crash. Items to drop.

# Screenshots

![image](https://user-images.githubusercontent.com/5217673/81138087-9c71a480-8f15-11ea-972b-6fe18f3787c1.png)

Drop -

![image](https://user-images.githubusercontent.com/5217673/81138071-9380d300-8f15-11ea-996f-9c33cd767dab.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-1808-g0da8625 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda]
]

# Additional context

[Save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4584786/Save.zip)

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4584787/crash.log)

**Comment by DillonSimeone** [comment]
And just cut myself on the edge again, ouchey. 

![image](https://user-images.githubusercontent.com/21962421/81230586-9e377880-8fa6-11ea-9986-b01129339671.png)

@Resok No liquids in this one. Just powder. Lots of powder.

**Comment by DillonSimeone** [comment]
It look like the game breaks if you try to drop the same type of item from many different pockets.

**Comment by DillonSimeone** [comment]
Update, guys, Korg just said that this bug is believed to have been fixed as a few days ago. I'm updating to current, and testing now.

**Comment by DillonSimeone** [comment]
It appears that this bug have been fixed! Haven't managed to triggered a crash so far.
