### ISSUE TITLE
Collect mods usage statistics

### ISSUE THREAD

**Issue by Aloxaf** [CleverRaven/Cataclysm-DDA#40340]
# Is your feature request related to a problem? Please describe.
If we have mods usage statistics, we could know which mod needs to be maintained and which can be removed.

# Describe the solution you'd like
Add an option to allow users to upload their mods usage.

# Describe alternatives you've considered
Keep it as it is: add mods and remove them at someday.

# Additional context
We can also collect more statistics, like tileset usage, system, and version.
Of course, this is optional and is turned off by default.

**Comment by anothersimulacrum** [comment]
While I think it'd be cool to see the data, I don't think has much bearing on which mods are kept and removed, that's more a matter of someone maintaining it and it [fitting within the mod guidelines](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/IN_REPO_MODS.md).

**Comment by kevingranade** [comment]
There are several aspects to this.  For security reasons, I am adamant that the game executable should not talk to the network. It would be fine to have the game executable write statistics to a file and then have a seperate executable push those statistics, but that also requires *someone* to write and maintain said statistics aggregator. This is a large and involved task, which needs a lot more care and interest than, "it would be nice if... ".

The other aspect is the core of the issue, which is driving mod maintenance based on usage statistics, which is a vanishingly unlikely proposition. Maintenance is based on developer interest, not feature utilization, so at best such a statistic would be informative rather than imperative.
