### ISSUE TITLE
Strength doesnt improve crossbow reload speed.

### ISSUE THREAD

**Issue by Dacendeth** [CleverRaven/Cataclysm-DDA#40704]
# Describe the bug
Crossbows are supposed to reload faster with a higher Strength stat, the crossbow description even states this and this is how it worked back in Danny version but somewhere along the lines this functionality stopped working.

# Steps To Reproduce
Reload a crossbow note how long it takes, make yourself stronger and reload again and note that it takes the same time.

# Expected behavior
High strength to cut down in reload times.

# Screenshots
![image](https://user-images.githubusercontent.com/26881007/82350561-84942900-99c9-11ea-8a75-63d264391e4a.png)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-2278-gf8f9f52 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context
If this isnt intended to be a feature anymore the description should be changed, but it seems like a reasonable feature to keep in.

**Comment by kevingranade** [comment]
Expected results: no misleading notes about high strength improving reload speed.

**Comment by Barhandar** [comment]
Crossbows are reloaded by pulling the string back into position, bending the arms and storing energy in them for later release. Realistically, higher strength should be resulting in faster reload.

Why are you making an exception for your "realism at all costs" design direction just for the crossbows?

**Comment by kevingranade** [comment]
The phase of crossbow reloading where you're pulling the string is a small fraction of reloading time, and higher strength isn't going to meaningfully shorten even that phase since peak draw weight is only encountered in a tiny fraction of the draw.

**Comment by EvgenijM86** [comment]
Higher strength person can reload crossbow more times in a row then a person with weak strength, until they reach their stamina limit. Assuming non-stop combat.

**Comment by ZhilkinSerg** [comment]
> Higher strength person can reload crossbow more times in a row then a person with weak strength, until they reach their stamina limit. Assuming non-stop combat.

It looks like it is more about stamina and less about strength.

**Comment by EvgenijM86** [comment]
Here is hypothetical example. If you have more muscle mass you will only need to use, say, 10% of muscle maximum pull to cock some crossbow. I.e. each muscle fiber is only used by 10% of what it can do, and thus it is pretty relaxed. And if you have a person with significantly lower strength he will need to use close to 100% of his maximum muscle pull. And if you ever have done exercises you will know that using maximum effort tires you out very quickly.

This example does not translate to melee weapons, because you can swing them harder with higher strength (and do more damage), but you cannot cock your crossbow harder.

**Comment by anothersimulacrum** [comment]
> Here is hypothetical example. If you have more muscle mass you will only need to use, say, 10% of muscle maximum pull to cock some crossbow. I.e. each muscle fiber is only used by 10% of what it can do, and thus it is pretty relaxed. And if you have a person with significantly lower strength he will need to use close to 100% of his maximum muscle pull. And if you ever have done exercises you will know that using maximum effort tires you out very quickly.

I still don't know what this has to do with reload times and not with stamina.

**Comment by EvgenijM86** [comment]
> I still don't know what this has to do with reload times and not with stamina.

The net effect is not that reloads are faster, but that there are more reloads before you tire out. This results in more shots fired over a period of time, because you don't need to rest as much. I think that muscle powered weapons should be affected by strength stat in some way. But I am not insisting on anything. Just an idea.
