### ISSUE TITLE
Died, pc died, reloaded the game - saw my dead body with all the items

### ISSUE THREAD

**Issue by Brytenwalda** [CleverRaven/Cataclysm-DDA#40710]
# Describe the bug

1. My character had an infection. He died, but when I was writing the obituary, my charger died. 
2. Reloaded the save.
3. I was standing on top my of own body, and all his items were on the floor.

# Expected behavior

It shouldn’t happen

# Versions and configuration

Latest experimental

**Comment by cirops** [comment]
I think this is another installment of related #12602, where you quit the game after the "Watch the last moments of your life?" prompt and before the game wraps up, which some supposedly do deliberately, and in your case, was an accident. It seems that in that issue and previous this is acknowledged as unwanted behavior, but solving it is kinda problematic because it runs the risk of killing legit savegames on accident. I'd just ignore it in your case.

**Comment by kevingranade** [comment]
Yea this is just an instance of, "don't force close the application".   There's no good way to adresses this.
