### ISSUE TITLE
Consume bug

### ISSUE THREAD

**Issue by buildfailedforallplatforms** [CleverRaven/Cataclysm-DDA#40731]
Cannot consume from cooking crafting menu

1. Batch make clean water
2. Consume crafted clean water
3. Nothing happens, even when only 1 is crafted. Can still place in containers/spill

Build: 10682

**Comment by DillonSimeone** [comment]
I can confirm that this is happening to me too.

![image](https://user-images.githubusercontent.com/21962421/82622400-9248da80-9b92-11ea-973c-7f8b07e7cbd3.png)

Press e, or hold down enter, nothing happens.

**Comment by Ramza13** [comment]
I've taken a look at this and understand what's happening.  Basically before when you could drink instantly having a bunch of water that didn't exist on the map or inventory anywhere was ok.  Now that it takes time to consume all of that you have to figure out where that water belongs in the meantime.  I will eventually get around to fixing this, though it might be by disabling consuming crafted liquids or preventing crafting liquids you can't store.

**Comment by jbytheway** [comment]
Can the craft result object be stored inside the activity object until the activity is complete?  I think something similar was done for bionic lockpick in #40824.  I guess that depends how `ACT_CONSUME` works.

**Comment by Ramza13** [comment]
The problem is multiple charges and interruptions.  Right now if you have crafted a single charge of water its a single line to get that to work and there are cases like grazing where a single item is stored in the actor and doesn't exist elsewhere.  

The problem is you craft 20 charges of water. Then drink one, now we have to wait until that's done to handle the rest.  Which could get shoved in the consume actor and then handled again at the end if it weren't for interruptions.  So you are drinking and a monster appears and you stop.  What happens to that water?  The consume actor is going away so the water needs to go somewhere.  I guess you could then force someone to dump it or put it in a container but that seems weird.  Like I could sit there drinking water for 10 minutes no problem but now that a monster appears it has to go in a bottle?  Where was it until now?

It's a bit more annoying in the UI to have to shove the water in a container but the alternative to my mind is somehow making all tools with boiling store liquids and then having the tool just hold the result. Which is the most realistic but I don't really want to do that as it sounds like a headache for relatively minor gains.
