### ISSUE TITLE
Mundane items spawn with plutonium fuel cells

### ISSUE THREAD

**Issue by mft-dev** [CleverRaven/Cataclysm-DDA#40800]
# Describe the bug

Mundane items in the world have plutonium fuel cells where they used to have no batteries or normal batteries.

This happens for items dropped by monster that have been killed as well as items found around in houses.

# Steps To Reproduce

1. Create a new game.
2. Kill stuff until one drops an item with charges, such as a cell phone
2. Alternatively: rummage around houses
3. Observe that the item has an obscene amount of max charges
4. Observe that the battery is a plutonium fuel cell

# Expected behavior

Mundane items should spawn with everyday batteries in them.

# Screenshots

![image](https://user-images.githubusercontent.com/566154/82758688-4db67c80-9de8-11ea-88ed-3e8359f92c81.png)

# Versions and configuration

- OS: Windows
    - OS Version: Windows 10.0 1903
- Game Version: 0.E-2427-g8677ed7 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Monsters [No_Fungi]
]

# Additional context

**Comment by KorGgenT** [comment]
interesting, must be because magazine_default() orders all the magazines alphabetically and then picks the first one.

**Comment by ussdefiant60** [comment]
My observations last week in my limited messing around with guns and battery powered stuff was that the first item defined in the JSON to be loadable in an item was treated as the default magazine unless the number of charges specified to be loaded in the item would not fit in the default magazine. 

This issue seems to be popping up in other items with their magazines defined with that in mind. Most notable i've seen so far is a M4A1 spawning with a 10 round magazine instead of a 30 round one.

**Comment by Ichthysdekilt** [comment]
Getting this 100% of the time in 10794.

**Comment by Inglonias** [comment]
It appears this issue is no longer present in 0.E-4787-g5cc59e1.
