### ISSUE TITLE
Advanced UPS no longer reloads and weighs 200 kg

### ISSUE THREAD

**Issue by ektoplazm** [CleverRaven/Cataclysm-DDA#40860]
# Describe the bug

Reloading advanced UPS consumes plutonium fuel cells without actually giving any charge to the item, also it weighs 200kg and takes 125L. 

# Steps To Reproduce

1. Spawn advanced UPS
2. Check its weight
3. Spawn plutonium fuel cells
4. Reload the advanced UPS
5. Watch the fuel cells disappear

# Expected behavior

Each fuel cell giving 500 charge to the UPS, advanced UPS weighed 0.82 kg and took 2L in build 10614 (before the nested containers update)

# Screenshots

![image](https://user-images.githubusercontent.com/60448096/82902801-b0cf1d00-9f68-11ea-9dfc-b97fa81a9da5.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-2476-g1b2af09 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Slots [cbm_slots],
    No Rail Stations [No_Rail_Stations]

# Additional context

**Comment by hexagonrecursion** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/issues/40863 has similar symptoms. There is a chance this two issues are related.

# I can confirm that
1. Reloading advanced UPS consumes plutonium fuel cells and prints "You reload the advanced UPS " to the log
2. After reloading the UPS still displays 0/2500 plutonium
3. An advanced UPS spawned via debug has abnormal volume and weight

# More observations
1. Title of a freshly spawned advanced UPS claims it has 0/2500 plutonium but the "contents of this item" section of the item description says "plutonium fuel cell (2500)"
2. The advanced UPS can be repeatedly reloaded with seemingly no effect
3. The advanced UPS fails to recharge a smartphone (UPS)
4. Trying to unload the UPS always says "your advanced UPS isn't charged"
5. Possibly a separate issue: on the item description it says "maximum <num> charges of plutonium" instead of "maximum 2500 charges of plutonium". Note: this is a different line from "capacity: 2500 rounds of plutonium" which displays correctly.

# A crafted (hammerspace) UPS behaves somewhat differently
1. Unlike a debug spawned UPS it has volume 2 liters and weight 1 lb
2. The UPS is initially empty and has no "contents of this item" section
3. After reloading it (even repetedly) the "contents of this item" section says "plutonium fuel cell" rather than "plutonium fuel cell (2500)"
4. Otherwise the behavior is identical

# Versions and configuration

- OS: Linux
    - OS Version: Fedora release 32 (Thirty Two)
- Game Version: 0.E-2532-gf4bb830 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by vvasyliev** [comment]
Cash cards also take up unrealistic amount of volume, might be related.
<img width="463" alt="Screenshot 2020-05-27 at 19 31 59" src="https://user-images.githubusercontent.com/12211770/83047534-2b736780-a051-11ea-926e-c427a1e0904c.png">

**Comment by dsmky117** [comment]
Cash cards have a fix incoming #40905. I think something similar needs to be done for the UPS: making the magazine rigid in [data/json/items/tool/electronics.json](https://github.com/CleverRaven/Cataclysm-DDA/blob/e3820539445f78c7fd5a1ab2904b9156908b6025/data/json/items/tool/electronics.json) resolves the volume issue, but it still weights too much.

**Comment by mft-dev** [comment]
It does look eerily similar in symptom to the cash card bug. Cash cards were all showing 0 balance in the inventory, but their charges had been correctly set. Migrating the special casing code for them over to use the pocket system was relatively painless.

With luck the same can be done for these other tools. I suspect it's more involved here, since a lot of code probably pulls charge from the UPS and will fail after a migration.
