### ISSUE TITLE
[MMA] Add 9 new martial arts and 2 new buff attributes

### ISSUE THREAD

**Issue by Hymore246** [CleverRaven/Cataclysm-DDA#40926]
_Purpose_
Back when I doing the the Martial Arts Rebalance, I mentioned that I didn't want to add any new styles to the game due to there already being a huge number of choices and how  difficult it is to keep balance between every martial art. When the Rebalance completed, I ended up becoming the primary maintainer for the MMA mod and I have now decided it is time to contribute some content to the mod.

Unlike styles in the base game, MMA martial arts do not need to be super realistic and can come from a large variety of sources, including supernatural origins. In addition, the styles do not need to be put under a microscope for the purposes of game balance. However, this doesn't mean that the styles should be overpower either. Most importantly, the mod is optional and players are not forced to use it if they don't want to.

_So what new martial arts are being added to the game?_
I decided to take a note from the Five Deadly Venoms and add a collection of martial arts from the 3rd edition Advanced Dungeons and Dragons supplement book, Tome of Battle: Book of the Nine Swords. Those styles are:

- **Desert Wind** - Fast style uses fire-based AOE manevuers.
- **Devoted Spirit** - Has alignment based abilities and can heal themselves with their attacks.
- **Diamond Mind** - Uses intelligence to outwit opponents offensively and defensively.
- **Iron Heart** - Pure skill style with feats that boarders on supernatural.
- **Setting Sun** - A supernatural version of aikido/judo that specializes in throws.
- **Shadow Hand** - A deceptive style that uses invisibility, teleportation, and debuffs.
- **Stone Dragon** - A tanking style that gains damage reduction when attacking and can bypass enemy damage reduction.
- **Tiger Claw** - Aggressive combat style that fights like a fast, vicious animal.
- **White Raven** - Teamwork style that guides allies to fight better.

However, after a lot testing I found that 3 of the styles couldn't be implemented in the game:

- **Devoted Spirit** - I couldn't find away to make the healing balanced. The effect lead to situations where you could just "farm health" from weaker enemies. There wasn't enough left in the style to make it interesting.
- **Shadow Hand** - Martial art enemy debuffs do not exist in CDDA. Further, 1 turn invisibility isn't that useful and controlled teleportation is completely removed from what a martial art should be.
- **White Raven** - NPC AI isn't smart enough to allow anything from this style to work. I would also argue that this is less of a martial art and more of form of leadership.

In order to make up for the loss, I will be adding 3 different styles adapted from other fictional works:

- **Hylian Swordsmanship** - Based off of Link's fighting style from the Legend of Zelda series.
- **Pokken** - A martial art made up of moves and special abilities from the Pokemon video game series.
- **Shii-Cho** - Better known as Form I or the Way of the Sarlacc, this is a form of lightsaber combat that specialized in fighting groups. I am NOT adding lightsabers to the game.

_What about the new attributes?_
Two new buff attributes will be added to CDDA. Both attributes will be added to the base game so any martial arts style can use them. These are being added as part of the MMA mod update because new content cannot contain "dead code". In other words, these attributes must be used by something to justify there inclusion in the game.

- **Blocking Effectiveness** - Reduces the damage from blocked attacks by a percent. This stacks with weapons that have blocking ability techniques (Block, Parry, Shield).
- **Critical Hit Chance** - Modifies the chance of scoring a critical hit.

Shii-Cho will use Blocking Ability and Tiger Claw with use Critical Hit Chance. Both attribute PRs will be merged right before their corresponding style's PR.

_List of MMA mod PRs_
- [x] **Desert Wind** (#40927)
- [x] **Diamond Mind** (#40966)
- [x] **Hylian Swordsmanship** (#41062)
- [x] **Iron Heart** (#41088)
- [x] **Pokken** (#41127)
- [x] **Setting Sun** (#41169)
- [x] **Add Block Effectiveness attribute** (#41188)
- [x] **Shii-Cho** (#41216)
- [x] **Stone Dragon** (#41246)
- [x] **Add Critical Hit Chance attribute** (#41293)
- [x] **Tiger Claw** (#41381)

**Comment by Zireael07** [comment]
Tome of Battle <3 I knew I recognized the names <3 <3

**Comment by Grekhaus** [comment]
As far as Devoted Strike goes, why not represent the healing abilities using pain reduction and stamina benefits? Something like...

Iron Guard's Glare (Melee 0): Static Buff, +2 Accuracy.
Iron Guard (Melee 0): OnGetHit Buff, -2 Accuracy, blocked damage reduced by 50% of Strength. Lasts 3 turns.
Foehammer (Melee 1): Melee Tech, +50% of Perception to armour penetration. Opponent must be downed. Crit OK.
Crusader's Strike (Melee 1): Melee Tech, +25% damage. Opponent must be stunned. Crit OK.
Revitalizing Strike  (Melee 2): OnCrit Buff, reduced stamina cost for attacks for 3 turns.
Divine Surge (Melee 3): OnKill Buff, codeine strength painkiller for 5 minutes.
Thicket of Blades (Melee 4): Melee Block Counter, -50% damage, stunned duration: 1.

Defensive/Endurance focused martial art for swords, cudgels maces and hammers. Gains defensive benefits when blocking or getting hit, gains offensive benefits when dodging or defending an ally. Because there are no critical style techniques without requirements, weapon techniques have a large impact: Brutal Strikes and Sweeps from maces and hammers enable Foehammer for armour penetration, while Precise Strikes from cudgels and Thicket of Blades both enable increased damage from Crusader's Strike. Critical hits and slain zombies mitigate stamina and pain based attrition respectively, making protracted fights against hordes less dangerous.

And for Shadow Hand, one D&D turn is the same as 6 CDDA turns. If you let the invisibility last more than one CDDA round and offer movement boosts in place of the teleportation, I think it could be made to work:

Assassin's Stance (Melee 0): Static Buff, quiet movement/attacks as per Ninjutsu, +4 Accuracy, +50% of Dexterity to Armour Penetration.
Visibility (Melee 0): OnGetHit Buff, -4 Accuracy, -50% of Dexterity to Armour Penetration for 3 turns.
Strength Draining Strike (Melee 1): Melee Crit Tech, +25% damage, stunned duration: 1.
Shadow Noose (Unarmed 1): Unarmed Cir Tech, +50% damage, stunned duration 1.
Feint (Melee 2): Melee Tech, Feint, 80% move cost.
One With Shadow (Melee 2): OnKill Buff, invisibility for 2 turns.
Shadow Blade Technique (Melee 3): Melee or Unarmed Tech, 50% move cost, requires One With Shadow.
Step of the Dancing Moth (Unarmed 4): Unarmed Technique, Grab Break.
Shadow Jaunt (Melee 5): OnPause Buff, 0.20 movement modifier for 1 turn. Requires Cloak of Deception.

Shadow Hand's big gimmick is that every time you kill something, you get either 2 turns of faster attacking or 5 turns worth of invisible escape, and that your offense tanks if you ever get hit. High volume of attacks and good accuracy, but few options for opponents with high armour or melee skill - you're expected to escape with Shadow Stride and use a non Martial Arts option instead. Comes with a grab break and some control in the form of stuns. Overall, a stealthy martial art focused more on momentum and escape than on the luring and kill setups of Ninjutsu.

**Comment by Hymore246** [comment]
Your suggestions are not bad, but I still have a lot of concerns with the styles.

I worry that Devoted Spirit having a a pain reducer and stamina cost reduction would allow players to go on a killing spree with no downside, especially since Devoted Spirit is a weapon style. It also has bit of overlap with Iron Heart and Stone Dragon which could be a problem. Devoted Spirit always seems like it has an issue with fighting endlessly which is not something player should be able to do in CDDA.

With Shadow Hand, I don't want it to be a better version of Ninjutsu. I'm fine with some overlap, but Shadow Hand and Ninjutsu need to be different enough from each other to make it a choice and finding that balance can be hard. Also, I am also not sure if invisibility "breaks" in CDDA the same way it does in AD&D. The OnKill buff might just let players attack endlessly without any fear of counterattack.

Lastly, implementing these special effects would take a lot of time, playtest, and balance. I do not have the time to do that.
