### ISSUE TITLE
Moving all contents between containers

### ISSUE THREAD

**Issue by CountAlex** [CleverRaven/Cataclysm-DDA#40933]
# Is your feature request related to a problem? Please describe.
It would be nice to have an option to pick container (like clothing) and move all itmes to another container.

# Describe the solution you'd like
For example, my char wears jeans with a dozen of cash cards in pockets. I want to replace jeans with w/e pants I have. At this point I have to drop those jeans, unload them and see how those items are elsewhere, not neccessarily at the container I want to place them to. There's no painless way to pull this trick of moving all content between two containers at will.

# Describe alternatives you've considered
Nothing really. Nested pockets is still WIP so I look forward to see those problems resolved.

# Additional context
Can be tied with #40169 probably but I don't think my idea duplicates it.

**Comment by KorGgenT** [comment]
how much different is this idea from the `i`nsert function when you select a container?

**Comment by CountAlex** [comment]
Unless I completely misunderstand how insertion works now, it would attempt to insert whole container with contents instead of contents only. Again, I have no option to move all content between two bags at will unless I use some intricate drop/pick-up combination.

**Comment by bigjane** [comment]
I don't believe the insert dialog allows you to see what container things are currently in?

**Comment by KorGgenT** [comment]
Say i want to move everything from these jeans to my backpack, because i don't want to leave them behind.

![image](https://user-images.githubusercontent.com/30208401/83293823-4c0b0100-a1ba-11ea-8bc7-e77c017c826c.png)

You'll note that i am already wearing a jacket, and i don't want to move the stuff from the jacket into the backpack.

Go to the insert menu:
![image](https://user-images.githubusercontent.com/30208401/83293879-60e79480-a1ba-11ea-8979-b927ec2092fb.png)

And you'll see a menu like this.
![image](https://user-images.githubusercontent.com/30208401/83293910-6e048380-a1ba-11ea-8a41-5dbf4e48ab93.png)

In order to switch to nested containers view, press `;`
![image](https://user-images.githubusercontent.com/30208401/83293931-79f04580-a1ba-11ea-94e3-e909dfffba86.png)

And then highlight items in the jeans as if it were the multidrop menu.
![image](https://user-images.githubusercontent.com/30208401/83293989-8d031580-a1ba-11ea-8cb4-a13c8b85445e.png)

**Comment by CountAlex** [comment]
Yeah, this works just fine, Korg! 
But I want to note I find this unintuitive - and I believe that relatively simple fix for this would be adding hint on using `;` for nested view toggle near `Filter` key hint.
