### ISSUE TITLE
Crossbow full-auto turret!

### ISSUE THREAD

**Issue by EvgenijM86** [CleverRaven/Cataclysm-DDA#41020]
# Is your feature request related to a problem? Please describe.
The problem of not having fully automatic crossbow turret, that does not lose any power compared to similar single-shot crossbow. It does loose accuracy.

# Describe the solution you'd like
Implementing this:
https://www.youtube.com/watch?v=a-0Cg2Ou9Gk

# Describe alternatives you've considered
There is no alternative.

# Additional context
Possibly mounted on a vehicle, with some machine learning chip that does automatic targeting and automatic shooting.

![image](https://user-images.githubusercontent.com/430076/83443931-18d6a500-a43a-11ea-8adc-c312a527a49e.png)

**Comment by anothersimulacrum** [comment]
Please follow the template.
This forum thread is relevant: [Adding more and new realistic primitive ranged weapons](https://discourse.cataclysmdda.org/t/adding-more-and-new-realistic-primitive-ranged-weapons/23818/2).

**Comment by EvgenijM86** [comment]
From mentioned forum thread:

> Full Auto Crossbow
> Not a fan, the inaccuracy pretty much defeats the purpose of the thing. Non-critical hits with a crossbow aren’t as damaging as non-criticsl hits with a rifle, meaning a full-auto crossbow is fairly worthless, especially as it means sacrificing power for firing rate.

This design uses an engine that fully draws average single-shot crossbow limb, meaning, that the amount of power per shot should be the same as a single-shot crossbow with that crossbow limb. The only thing that might reduce power per shot is slightly smaller size of arrows, but that can probably countered by adding more weight to those arrows. So as far as power is concerned we can get away without making any compromises.

The obvious downsides is that it is a turret, and not hand-held gun.

**Comment by EvgenijM86** [comment]
> 1. Can your character design these things from scratch? Are they going to spend years doing it after becoming a master crafts person? They don’t have that time, and they almost certainly don’t have the aptitude.

> 2. Can your character find design schematics for these? In a post-internet world, this seems unlikely. I don’t know if Joerg releases schematics, but even if he does, the likelihood if finding one seems immensely small.

No need to design them from scratch. Cataclysm world is set some time in the future, thus a lot of people have seen his inventions, and they should be at least reported in some archery magazines. Publishers would be stupid to skip such material and not make a profit from reporting on cool new inventions. And once you have seen something like the video above it would be much easier to replicate it than inventing it from scratch. And finding designs should also be a possibility. Here is an example of fan replicating his work and creating designs for 3d printer - https://legolini.com/

**Comment by EvgenijM86** [comment]
To clarify: I am not asking devs to add this to the game. I am just interested if this would be accepted if implemented. I don't want to work on this and find out at the very end that devs simply disliked the concept.

**Comment by KorGgenT** [comment]
> Cataclysm world is set some time in the future

It is set in present day, just to make sure you're aware

**Comment by EvgenijM86** [comment]
Thanks for info. The presence of bionics made me think that it was something like 20+ years in the future.

**Comment by kevingranade** [comment]
"with some machine learning chip that does automatic targeting and automatic shooting." is right out.
Machine learning isn't plug and play AI like this statement seems to indicate, it's just a technique for programming a system with feedback instead of by hand coding.

It's possible, if absurdly high effort (weeks to months of work), to build a blob tracking system and aiming etc and have a system that can place projectiles somewhere near the center of mass of a target, and this would be sufficient for a gun turret, for a crossbow turret not so much since *you need to deal critical hits for them to work*.

This applies to both the auto-turret and hand-operated concepts for this, a slow succession of bolts isn't great since it does not give you an opportunity to get those critical hits in.  You can certainly hit enemies, but your effective damage output is going to be abysmal.

"No need to design them from scratch." - You seem to be ignoring my feedback, I don't see any meaningful chance that you would ever come across media referencing this, much less come across designs for it.  Even if your character comes across a reference or happens to have seen something about it before the cataclysm, that doesn't do the bulk of the design effort for you, you still need to address a large number of potentially very difficult design problems n attempting to make something like this, all for an incredibly poor payoff since the thing isn't going to be dealing consistent critical hits.
