### ISSUE TITLE
Multi-tiled monsters?

### ISSUE THREAD

**Issue by martinrhan** [CleverRaven/Cataclysm-DDA#41087]
# Is your feature request related to a problem? Please describe.
I think some monsters are very large that they should be occupying more than one tile, like vehicles. It is not sensible that any monster whether how large it is can fit into a door as well as a human. This thing is especially unrealistic in dino mod.
Besides, driving vehicles to kill monsters seems so simple. Whatever thing can be smashed with a vehicle with a high speed. A large enough monster can act like a buiding or vehicle that won't be easily destroyed.
Further more, making multi-tiled monster available in game allows existance of super giant creature, imagine a hostile enormous being devastating the city, haha.

# Describe the solution you'd like
Maybe we can utilise codes about vehicle, make something similar.

# Describe alternatives you've considered
N/A

# Additional context
This thing sounds tricky, any one would like to do it? I don't want to spend time study another piece of not familiar code, but if no one doing it I will do it my self

**Comment by cirops** [comment]
Looking at the creature code, that would be a nightmare to implement and maintain. I think a "tile" is a more abstract thing than just say, 1.5mx0.5x..., being defined as "as big as it has to be". So to separate your remarks:
 > I think some monsters are very large that they should be occupying more than one tile, like vehicles.

I think they're not gonna do that at least because of technical limitations.
> It is not sensible that any monster whether how large it is can fit into a door as well as a human.

This could be modelled by, for example, a flag which says the monster is too huge to fit into a door, car door, window or something, and would try to force entry, possibily damaging or even destroying the structure in the process.
> Besides, driving vehicles to kill monsters seems so simple. Whatever thing can be smashed with a vehicle with a high speed. A large enough monster can act like a buiding or vehicle that won't be easily destroyed.

I think the dynamics of vehicle collision are a work in progress, and although I'm not sure what we'll end up with, it seems to me that taking the bulk of the collided object into account, as well as the bulk of your vehicle, makes sense and is currently partially being modelled, although this is a very hard system to model well.

As an aside, for RP purposes, the are actually multi-tile **graphics** for some huge creatures, so at least we have that.

**Comment by Hirmuolio** [comment]
The feature that allowss cars to tow other vehicles kind of turns vehicles into very limited creatures.

Probably the easiest way to get multi tile creatures would be to make vehicle creatures.

**Comment by martinrhan** [comment]
Thing cannot be attained in one step, maybe the first step is to make hostile auto vehicles.

**Comment by actual-nh** [comment]
Now in a project, so should not be stale.

**Comment by actual-nh** [comment]
@LyleSY: Sorry, didn't realize that would happen with the project categories...

**Comment by LyleSY** [comment]
No worries, good catch
