### ISSUE TITLE
Power Armor Hauling Frame does not work with any form of Power Armor.

### ISSUE THREAD

**Issue by PudgyElderGod** [CleverRaven/Cataclysm-DDA#41103]
# Describe the bug
The Power Armor Hauling Frame appears to not work with any form of Power Armor.

# Steps To Reproduce

1. Spawn in Power Armor Hauling Frame 
2. Spawn in all varieties of exoskeleton and power armor, which includes the RM13, all three Exoskeletons, and Salvaged Power Armor.
3. Equip Power Armor
4. Attempt to equip Power Armor Hauling Frame
5. Cry because it no longer works.

# Expected behavior
The Hauling Frame would be equipped on the Power Armor.

# Versions and configuration

- OS: MacOs
    - OS Version: Name: Mac OS X; Version: 10.15.4; Build: 19E2265; 
- Game Version: ede5ff205b [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    Alternative Map Key [alt_map_key],
    Mythical Martial Arts [MMA],
    More Locations [more_locations],
    Urban Development [Urban_Development],
    Fuji's More Buildings [FujiStruct],
    Beta National Guard Camp [national_guard_camp],
    Fuji's Military Profession Pack [fuji_mpp],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex]
]

**Comment by anothersimulacrum** [comment]
Helmets don't work either, it appears to be caused by #40866 - the problematic line is `src/character.cpp:3012` - `if( elem.get_covered_body_parts().make_intersection( it.get_covered_body_parts() ).any() &&`.

For a helmet:

`elem.get_covered_body_parts()` == `{
  parts = {<cata::transparent_less_than> = {<No data fields>}, <std::vector<string_id<body_part_type>, std::allocator<string_id<body_part_type> > >> = std::vector of length 9, capacity 16 = {{_id = "arm_l", _cid = -1}, {_id = "arm_r", _cid = -1}, {_id = "foot_l", _cid = -1}, {_id = "foot_r", _cid = -1}, {
        _id = "hand_l", _cid = -1}, {_id = "hand_r", _cid = -1}, {_id = "leg_l", _cid = -1}, {_id = "leg_r", _cid = -1}, {_id = "torso", 
        _cid = 0}}, <No data fields>}}
`

`it.get_covered_body_parts()` == `{
  parts = {<cata::transparent_less_than> = {<No data fields>}, <std::vector<string_id<body_part_type>, std::allocator<string_id<body_part_type> > >> = std::vector of length 3, capacity 4 = {{_id = "eyes", _cid = 2}, {_id = "head", _cid = 1}, {_id = "mouth", _cid = 3}}, <No data fields>}}`

The intersection is:
`{
  parts = {<cata::transparent_less_than> = {<No data fields>}, <std::vector<string_id<body_part_type>, std::allocator<string_id<body_part_type> > >> = std::vector of length 4, capacity 4 = {{_id = "arm_r", _cid = -1}, {_id = "foot_r", _cid = -1}, {_id = "hand_r", _cid = -1}, {_id = "leg_r", 
        _cid = -1}}, <No data fields>}}`

For a hauling frame:

`it.get_covered_body_parts()` ==  `{
  parts = {<cata::transparent_less_than> = {<No data fields>}, <std::vector<string_id<body_part_type>, std::allocator<string_id<body_part_type> > >> = std::vector of length 0, capacity 0, <No data fields>}}`

`elem.get_covered_body_parts()` == `{
  parts = {<cata::transparent_less_than> = {<No data fields>}, <std::vector<string_id<body_part_type>, std::allocator<string_id<body_part_type> > >> = std::vector of length 9, capacity 16 = {{_id = "arm_l", _cid = -1}, {_id = "arm_r", _cid = -1}, {_id = "foot_l", _cid = -1}, {_id = "foot_r", _cid = -1}, {
        _id = "hand_l", _cid = -1}, {_id = "hand_r", _cid = -1}, {_id = "leg_l", _cid = -1}, {_id = "leg_r", _cid = -1}, {_id = "torso", 
        _cid = 0}}, <No data fields>}}`

`elem.get_covered_body_parts().make_intersection( it.get_covered_body_parts() )` == `{
  parts = {<cata::transparent_less_than> = {<No data fields>}, <std::vector<string_id<body_part_type>, std::allocator<string_id<body_part_type> > >> = std::vector of length 4, capacity 4 = {{_id = "arm_r", _cid = -1}, {_id = "foot_r", _cid = -1}, {_id = "hand_r", _cid = -1}, {_id = "leg_r", 
        _cid = -1}}, <No data fields>}}`
