### ISSUE TITLE
Cudgel length of 3in is too short, needs simple realism adjustment

### ISSUE THREAD

**Issue by johnrdconnolly** [CleverRaven/Cataclysm-DDA#41175]
Game version: Experimental #10739

Operating system: Windows 10 64 bit

Tiles or curses: Tiles

Mods active: Skills through Kills, SpeedyDex

### Expected behavior

A cudgel should be at least 12 inches, and possibly be able to be attached to a belt loop. This is a link to the weapon that is more commonly known as a cudgel. Usually about 36in in length https://en.wikipedia.org/wiki/Singlestick

### Actual behavior

Cudgel in game is 3inches long, you can fit it in your pocket. Not at all accurate of the weapon.

### Steps to reproduce the behavior

Make or spawn in a cudgel and look at the length.

### Solution

Add a tag for length of 36 in, and possible the tag to allow on belt loop.

**Comment by wapcaplet** [comment]
All this needs is for the "longest_side" attribute of the "cudgel" to be defined in
[data/json/items/melee/bludgeons.json](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/items/melee/bludgeons.json). This would be an easy first issue for a new contributor.

This would also be a good opportunity to add "longest_side" to some or all of the other items in the same `bludgeons.json` file - for example the aluminum bat (4 in) and war flail (5 in). We've been using metric (usually cm or mm) for units, so for a roughly 36-inch cudgel, add `"longest_side": "91 cm"`.

For reference, see my recent PR adding length to swords and other blades #41044

**Comment by johnrdconnolly** [comment]
> All this needs is for the "longest_side" attribute of the "cudgel" to be defined in
> [data/json/items/melee/bludgeons.json](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/items/melee/bludgeons.json). This would be an easy first issue for a new contributor.
> 
> This would also be a good opportunity to add "longest_side" to some or all of the other items in the same `bludgeons.json` file - for example the aluminum bat (currently 4 in) and war flail (5 in). We've been using metric (usually cm or mm) for units, so for a roughly 36-inch cudgel, add `"longest_side": "91 cm"`.
> 
> For reference, see my recent PR adding length to swords and other blades #41044

This is exactly the response I was hoping for! I will attempt to make this change, possibly some others, and submit a new bludgeons.json!

**Comment by johnrdconnolly** [comment]
> All this needs is for the "longest_side" attribute of the "cudgel" to be defined in
> [data/json/items/melee/bludgeons.json](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/items/melee/bludgeons.json). This would be an easy first issue for a new contributor.
> 
> This would also be a good opportunity to add "longest_side" to some or all of the other items in the same `bludgeons.json` file - for example the aluminum bat (currently 4 in) and war flail (5 in). We've been using metric (usually cm or mm) for units, so for a roughly 36-inch cudgel, add `"longest_side": "91 cm"`.
> 
> For reference, see my recent PR adding length to swords and other blades #41044

Can you also tell me the tags for stuff like belt loops and holsters and such? I may as well update those tags on the bludgeons.json while I'm at it.

**Comment by wapcaplet** [comment]
> Can you also tell me the tags for stuff like belt loops and holsters and such? I may as well update those tags on the bludgeons.json while I'm at it.

What else do you have in mind to update? Tools might have a `BELT_CLIP` flag if they can attach to a compatible belt - that sort of thing is documented in JSON_FLAGS.md and JSON_INFO.md.

If you are referring to also giving length limits to holsters or other tool/weapon storage items, the pocket can may have a `"max_item_length"` telling the longest item that will fit.

**Comment by johnrdconnolly** [comment]
> > Can you also tell me the tags for stuff like belt loops and holsters and such? I may as well update those tags on the bludgeons.json while I'm at it.
> 
> What else do you have in mind to update? Tools might have a `BELT_CLIP` flag if they can attach to a compatible belt - that sort of thing is documented in JSON_FLAGS.md and JSON_INFO.md.
> 
> If you are referring to also giving length limits to holsters or other tool/weapon storage items, the pocket can may have a `"max_item_length"` telling the longest item that will fit.

#1. Ok, so you are saying that holstered are governed by item length, not a tag, correct? And that in theory anything under that length can be put in said holsters? Down to a holsters minimum size which I would assume there is..?

#2 I'm just thinking about other items that should have the belt_clip tag associated with them. I mean a cudgel is similarly shaped to a hammer and likewise should be able to be stored in a belt loop. As should other items with a slender handle and a large head.

#3 Along the belt_clip line, what governs the encumbrance of an item that is clipped to a belt? That might be a good way to maintain balance when adding belt_clip to new items.

**Comment by wapcaplet** [comment]
> #1. Ok, so you are saying that holstered are governed by item length, not a tag, correct? And that in theory anything under that length can be put in said holsters? Down to a holsters minimum size which I would assume there is..?

I don't know what you mean by "a tag", but as I said the "max_item_length" defines the longest item that will fit in any pocket (whether it is a "holster" or not, which has a separate meaning). And yes, there is a minimum as well, but it's not by length - it's "min_item_volume". You can read more about these in the [pocket_data section of JSON_INFO.md](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/JSON_INFO.md#containers).

> #2 I'm just thinking about other items that should have the belt_clip tag associated with them. I mean a cudgel is similarly shaped to a hammer and likewise should be able to be stored in a belt loop. As should other items with a slender handle and a large head.

Perhaps? I think of a cudgel as a simpler, straight weapon with no hooks or protrusions that you could use to attach it to a belt loop. I only mentioned the BELT_CLIP *flag* since you mentioned something about belt loops, and that's one of many possible flags related to belt storage. I definitely suggest learning and understanding these, and looking at existing tools that use them, before adding them to the bludgeons.

> #3 Along the belt_clip line, what governs the encumbrance of an item that is clipped to a belt? That might be a good way to maintain balance when adding belt_clip to new items.

Most items with storage/pockets have encumbrance that increases based on how filled up they are. See the "encumbrance" and "max_encumbrance" fields in the [armor section of JSON_INFO.md](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/JSON_INFO.md#armor).

All that said, if this is your first contribution, I strongly advise not biting off more than you can chew. There is nothing wrong with submitting a 1-line pull request to simply set the correct length of the cudgel - it would be an improvement to the game. As a rule, simpler contributions are easier to evaluate and more likely to be approved than complicated ones. You can always come back later and make further improvements to item flags or such.

Don't forget to check out the [guide for first time contributors](https://github.com/CleverRaven/Cataclysm-DDA/wiki/Guide-to-adding-new-content-to-CDDA-for-first-time-contributors) if you have not already.

Have fun!

**Comment by johnrdconnolly** [comment]
> All that said, if this is your first contribution, I strongly advise not biting off more than you can chew. There is nothing wrong with submitting a 1-line pull request to simply set the correct length of the cudgel - it would be an improvement to the game. As a rule, simpler contributions are easier to evaluate and more likely to be approved than complicated ones. You can always come back later and make further improvements to item flags or such.

I appreciate the feedback and detailed instructions and guidance/links.

I am have already researched and added lengths to all the items in the bludgeons.json and made a list/summary like yours from #41044 . That is all that will be in my first pull request. Now I just need to setup Git, fork clone sync and branch before I submit a PR. Gonna leave that for another night. Thanks again for the advice and such.

**Comment by johnrdconnolly** [comment]
Resolved by #41199
