### ISSUE TITLE
Molotovs not working and disappearing

### ISSUE THREAD

**Issue by FrameData** [CleverRaven/Cataclysm-DDA#41197]
# Describe the bug

-Molotovs disappear from inventory when being lit. The log displays the message "You've already lit the molotov cocktail (lit). Try throwing it instead." Even in non windy or underground conditions.

-Molotovs that are succesfully lit cannot then be equipped or stored in inventory.

_Molotovs produce no flames when thrown.

# Steps To Reproduce

1. Make a player with a lighter and some molotovs

2.Light molotovs till the message "You light the molotov cocktail" shows in the log instead of "You've already lit the molotov cocktail (lit). Try throwing it instead.".

3. Throw the molotov.

4. Repeat steps 1&2 then attempt to either store in inventory or wield the lit molotov.

# Expected behavior

Molotovs actually lighting in your hand or inventory.
Molotovs not disappearing from hands or inventory unless thrown.
Molotovs when lit and then thrown should produce some amount of fire. Same with incendiary grenades when launched (they also won't produce flames) 

- OS: Windows 7
- Game Version: 0.E-3006-g54fa33c [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by mioxyz** [comment]
Yes, I've encountered the same problem. I would try to fix it myself, but sadly I am currently unable to compile the game on my computer (and for some reason I can't get lldb to get along with my previous builds). I'm pretty sure the problem lies within the method `int iuse::molotov_lit( ... );` The game checks if the item has charges or not in the first case, and will display the "You've already lit the %s, try throwing it instead." message, if so. I think the return value needs to be 1 at this point, because the iuse functions return a bool (actually an int) of whether or not a charge of the item should be consumed, so if the function molotov_lit is called recursively every game step, then the charges are reduced until they reach zero after which the else case is reached (the else case being the explosion). Probably due to the new nested inventory system, molotovs have charges before they are lit (and possibly before charges were used as a count-down? Dunno). One could try to hack the save game state so that the thrown molotov has 0 charges and see if it produces an explosion to confirm my belief.

**Comment by FrameData** [comment]
With the most recent build 10771 it appears that molotovs now function. they still go out more than i would like but that's a balancing issue. As such i am closing this. Thankyou :)
