### ISSUE TITLE
Active Defense CBM doesn't provide any feedback on its work

### ISSUE THREAD

**Issue by GGgatherer** [CleverRaven/Cataclysm-DDA#41267]
# Describe the bug

Subj. It outright doesn't work. Had a bandit throw at me full clip of his SIG P226, and it didn't proc once.

# Steps To Reproduce

1. Make a player with AD CBM and some power.
2. Spawn bandit, turret or w/e can shoot.
3. Activate AD, count how many times it procs.

Alternatively, load [this save](https://github.com/CleverRaven/Cataclysm-DDA/files/4773742/Grand.Meadow.10751.zip), wait till the fire burns out, activate AD and see if it works (hint: it does not)

# Expected behavior

Its description clearly says the bullets have a chance to be deflected. Was it nerfed somewhere in late 0.D or 0.E so it now just reduced their damage by 5% instead? If so, maybe its description should be updated. If not, it should actually deflect them, like it says.

# Versions and configuration

    OS: Windows 7
    Game Version: 0.E-3128-gb880329 [64-bit]
    Graphics Version: Tiles
    Game Language: English [en]
    Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Skills [StatsThroughSkills]
    ]

**Comment by Night-Pryanik** [comment]
Tested right now on 0.F-6401.

Disposition:
MP5 turret is standing next to me. I activated the bionic.
![изображение](https://user-images.githubusercontent.com/11132525/155841046-d0d0d5e2-6ae8-4478-ad5a-824c82df7598.png)

I locally modified code related to this bionic and wrote this code snippet:

```
if( has_active_bionic( bio_ads ) ) {
    if( elem.type == damage_type::STAB || elem.type == damage_type::BULLET ) {
        int damage_reduction = rng( 1, 8 );
        elem.amount -= damage_reduction;
        popup( "incoming bullet damage reduced by %i units", damage_reduction );
    }
}
```

I let the turret fire at me, and here's the results:
![изображение](https://user-images.githubusercontent.com/11132525/155841167-8f55464a-6889-4f4a-be35-baef1e651de3.png)

Looking at the damage turret made to me:
![изображение](https://user-images.githubusercontent.com/11132525/155841241-12f7a07e-74f3-4685-9b60-439eb0f53b0e.png)

It's no wonder that one might think that bionic isn't working at: bionic reduced incoming damage by the overwhelming 4%! And no message in the log regarding work of the bionic doesn't help either. 

Concluding: bionic is working. The issue here is lack of feedback provided to player. And, probably, balance issue with way too small effect for such a presumably powerful bionic. Both of these problems should probably be discussed in their own separate issues.

Should I close this particular issue?

**Comment by Zireael07** [comment]
Instead of making a separate issue, I'd repurpose this one (maintainers can rename issues IIRC?) for lack of feedback
