### ISSUE TITLE
Ideas for Magiclysm

### ISSUE THREAD

**Issue by martinrhan** [CleverRaven/Cataclysm-DDA#41305]
# Is your feature request related to a problem? Please describe.
I am unsatisfyed with the current magiclysm as many common magical things are missing. I would like to disguss with other people to know whether my ideas are good or not.

# Describe the solution you'd like
I can figure out a lot of things that can be added into it, but it is going to be too much to tell all of them. One of the best thing to add in my opinion is such:
-Add property "records spell" to magic books, spell books, and scrolls. It includes several spells and level of spells. Add a flag "can cast recorded spell" for scrolls so they can be consumed to cast a spell. 
-Rework leveling up of spells and spellcraft skill. My idea is: 1,spells level cannot be more than 2*spellcraft level. 2, cannot get spells leveled up to more than learning source's level. 3, leveling up a spell adds exp to spellcraft skill.
-Enchantment mods, similar to gun mods, can be added to items.
-Recipe due to spell knowledge, for example, learning fireball makes player able to craft fireball scroll.

# Describe alternatives you've considered
N/A

# Additional context
I am going to work on this after disgussion.
And I gave up to work on this
https://github.com/CleverRaven/Cataclysm-DDA/issues/41087
as it is truely too difficult.

**Comment by Zireael07** [comment]
>  many common magical things are missing.

So far, you only mentioned recording spells and scrolls and a more complex way of limiting spells cast.

Artificial spell limits aren't a "common" thing, many rpg systems work fine w/o them.

**Comment by martinrhan** [comment]
> > many common magical things are missing.
> 
> So far, you only mentioned recording spells and scrolls and a more complex way of limiting spells cast.
> 
> Artificial spell limits aren't a "common" thing, many rpg systems work fine w/o them.

okey, its true that the logic of new spell learning mechanic is not common, but it is a cdda–style thing, it is similar to other skill's learning.

**Comment by solerante** [comment]
In my opinion:
I'm not a fan of your learning proposal. I don't think you should be limited to what is available from books, otherwise what does spell research look like? How did anyone get good enough at the spell to write the book in the first place? 
I do like the limit on how high you can take your learning of a spell based on a multiple of spellcraft.

I like the idea of recording spells with paper and writing utensil, don't think you should be able to make one time use scrolls. I never really liked that mechanic. I don't mind other single use mechanisms for spells though. Honestly, you should be able to write down any recipe from a nearby book into a notebook at the cost of time and writing utensil usage. Or be able to take a photograph of the book and keep the recipe and eventually have an sd card or notebook with recipes you can check from your phone. Including spells.

I like the idea of enchanting, but enchantments should apply to anything. Why limit it to weapons? I want feather weight on my hiking bag and silence on my jackhammer.

What about lingering AOE effects? Like cast dark, like the CBM? What about items that sustain those effects?
What about permanent effects? Transmutation? 

What about utility? Knowing a spell should allow the corresponding utility application, like fireball start a fire, freeze cone, freeze item, biomancer +5 butchering on top of best tool, technomancer -5% CBM install failure.

Or maybe it's a branch and you learn both spells and concepts. If you learn fireball, you also learn start fire at 0, because you learned the concept of magic fire. If you pass level 5 in fire concept, you learn the idea of a new spell (level 0) like cone of fire and must practice to learn it. Reading still improves spellcraft, but so does learning new spells and leveling current spells. High spellcraft lowers the level at which you learn next spell, increases how fast you level spells, and governs magical crafting.

I mostly want more utility stuff and less combat stuff because tech has a lot of survival tools but magic does not. Let me at least boil water magically, or freeze meat, or transfer items magically, or toggle my spells (like magelight), or summon an expensive portal, or weld using pyrotechnic magic, or craft wood items by guiding plant growth, or cast my vision into an animal to see their FOV, or freeze a river and walk over it, or charge a battery with electricity, or run a UPS device with mana via electricity, or condense water from atmosphere , or surgical facial reconstruction, or astral projection, or summon utility item from the ether, or summon previously marked item with spell, or clairvoyance (next few minutes or seconds of game revert after a bit), or polymorph (could be fun branch of biomancer), or magical fertilizer, or destabilize portal.

**Comment by martinrhan** [comment]
@solerante 
I am actually also having some ideas of "knowledge recording" for doing research, for example catch monster and do experiment on them or dessect them, but such thing reqiures a much detailed knowledge or skill system, for example zombie knowlegde enable you to make zombie minion. And it also reqiures main knowledge and content knowledge to be devided as in reality experts never memorise all the data and information of their subjects.

**Comment by solerante** [comment]
In retrospect, I feel I went too far with my response, sorry about that. 
I'm actually a big fan of that idea, especially since there is there photography aspect which captures monsters' images, if they have one. Can't you just capture information that is a description with key words that indicate key knowledge, much like the camera does, and save that to the character's memory? an sd card brain?

At the bottom of 
https://github.com/CleverRaven/Cataclysm-DDA/projects
there is a Practice makes Perfect pitch by kevin.granade. If Practice makes Perfect were implemented and knowledge of a creature, as captured by key observations in person or through literature, were insights with which you could level  creature skills that represented your knowledge of them and then make zombie minion is a recipe.

Is some thing like that aligned with what you mean?

**Comment by martinrhan** [comment]
@solerante what I mean by a much more detailed skill and knowledge system is a tree of skill and knowledge with a lot of subjects, for example, under melee I have sword skill, spear skill, knife skill, hammer skill, etc.,under driving I have bicycle skill, car skill, tank skill, helicopter skill, plane skill, etc., under spellcraft I have technomancer skill, biomancer skill, etc., similarly, under chemistry (or may be a new one added biology)

**Comment by solerante** [comment]
What is it, exactly, that having a good car driving skill imply? Can a better driver turn the wheel faster? Maybe it's related to driving fatigue? I'm not sure that the activities in CDDA, myriad though they are, necessarily benefit from total granularity. What exactly is it that you are trying to model? Which activities would change by having a skill for each aspect or item?

Let us take combat. There is currently a system where weapons have combat abilities locked by character skill. It's not very realistic, but is kind of interesting, could probably be a little more scalable. If there was a skill for knives, it could make sense, so that a knife master was sort of better of with a shoddy knife than a mace amateur with a morning star, but isn't that kind of modeled already? Is it really as thought a swordsman is clueless with a knife? The skills of bashing vs slicing vs piercing are modeled, implying some transference between weapons which cause each each kind of damage, more or less.

What if there were simply weapon expertise martial arts? Extensive use of a weapon unlocked a style which maximized something or other. I guess it'd be a shame to not be able to use the other styles, so  never mind. Perhaps a trait after a threshold of usage?

I think adding a skill basically means adding a new layer of gates to other rewards.

Frankly, I think you should flesh out on the mechanics of magical gun mods, since that could simply be a "magical slot" which accepts gun mod spells?
