### ISSUE TITLE
Add ability to transfer characters between worlds

### ISSUE THREAD

**Issue by dvolk** [CleverRaven/Cataclysm-DDA#4134]
It'd be nice if one could a character (and items they are carrying) to a brand new world, perhaps generated with the same settings and starting time set to current time.

**Comment by mugling** [comment]
There is a relatively recent forum post which includes a utility for such a task

**Comment by dvolk** [comment]
It's been possible to do this manually, but since it's not part of the game and this is a game feature request I don't see why you closed it.

**Comment by kevingranade** [comment]
Because this is a really niche feature and it's way easier to do this kind
of thing in a separate utility, which has already been done.

**Comment by mugling** [comment]
@dvolk there isn't a need for such code in `master` considering a [3rd party solution exists](http://smf.cataclysmdda.com/index.php?topic=12119) now exists.

Separately having >1000 open issues makes it harder to track which require attention and which are effectively permanently stalled.

**Comment by Orange01gaming** [comment]
This seems like a great way for us to add to portal storms and the "end game". If you stay long enough in the portal instead of merging with other yous, you could generate a new world to spawn in. Or have a final quest from the exodii/hub to allow you to do this. Perhaps exodii lets you create world as normal, but hub is a bit more predetermined, or exodii let you take a map tile with you.
