### ISSUE TITLE
Incorrect food sizes cause engorging with empty stomach

### ISSUE THREAD

**Issue by Cratelord** [CleverRaven/Cataclysm-DDA#41366]
# Describe the bug
When eating items (such as a PB&J sandwich) some items are deemed too large despite having an empty stomach. 

# Steps To Reproduce

1. Load a new character.
2. Eat an item that is .25L or bigger.
3. Become engorged with 2590mL in your stomach and throw it up. 

# Expected behavior
Food to work properly.

# Screenshots
![contents 1](https://user-images.githubusercontent.com/65396489/84839147-54609a00-b00a-11ea-9520-b93a40f41b6c.PNG)
![contents 2](https://user-images.githubusercontent.com/65396489/84839152-56c2f400-b00a-11ea-9c2a-43e8b67965b4.PNG)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-3223-g4919f51 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Graphical Overmap [Graphical_Overmap],
    Magiclysm [magiclysm],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    Caches [P_Caches],
    Mythical Martial Arts [MMA],
    Mining Mod [Mining_Mod],
    Crazy Cataclysm [crazy_cataclysm],
    Cataclysm++ [Cata++],
    No Freeze [no_freeze],
    Bootleg Walkers [Bootleg_Walkers],
    C.R.I.T Expansion Mod [crt_expansion],
    Blaze Industries [blazeindustries],
    Aftershock [aftershock],
    No Fungal Monsters [No_Fungi],
    Fuji's Military Profession Pack [fuji_mpp],
    Song of Shinigami [shinigamimod],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/pb-j-causes-you-to-go-from-very-hungry-to-engorged/23997/10

**Comment by I-am-Erk** [comment]
So some thoughts
1. We might want to put a cap on the multiplier to volume, or (better) make the equation more complex so the multiplier falls off the higher the calorie to weight ratio gets. Thinking on it.

2. More importantly though, this seems to specifically be a problem with sandwiches. Are there any other food items causing this issue?

**Comment by I-am-Erk** [comment]
Ok, reviewing other related issues there are some related concerns.

- some have had problems becoming too satisfied eating butter or raw fat, but from what I can see, the amount of pure fat you can eat without vomiting right now is actually more than you really could, so I don't know that these need much tweaking.
- cheeseburgers and sandwiches are overlying filling under the current formula. It seems that they might be a bit high on calories and volume and low on mass, but the formula probably needs adjustment so that it doesn't kick in as hard in this particular range. I'll poke around for other examples.

**Comment by I-am-Erk** [comment]
Okay, I've determined the problems and they're not my formula, which is good because I tested that thing up and down.

There are two issues here:
1. Main one - the formula isn't working properly for some reason. This sandwich should have a ratio of a bit more than X3, putting its effective volume at a bit under a litre. You should be able to eat two or three of these monstrous pbj naanwiches before getting sick, which I would say is probably a very accurate amount. Instead it's coming in at X10. I haven't yet figured out why.

2. A lot of sandwiches don't weigh enough. This one isn't far off (2 pieces flatbread = 180g, 2tbsp peanut butter = 60g, 2 tbsp jam = 30g so it should be more like 270g), but similar sandwiches are weighing 100g or so in testing which is tiny and gives them an insane calorie density like eating half a cup of straight peanut butter, as described above.

**Comment by Cratelord** [comment]
I didn't take screenshots of it, but for me this was also happening with deluxe cooked beans.

**Comment by anothersimulacrum** [comment]
Deluxe cooked beans don't exist. Do you mean deluxe cooked beans and rice?

**Comment by I-am-Erk** [comment]
I can't see a reason for this on deluxe beans n rice. The volume is fairly low, the calorie defaults are reasonable, and the portion sizes shouldn't have much impact from density. I'd appreciate a reproduction of that to make sure I'm not missing anything as we fix this.
