### ISSUE TITLE
Sidebar Wielded Weapon Text shows mods before weapon

### ISSUE THREAD

**Issue by Rokmonkey** [CleverRaven/Cataclysm-DDA#41382]
Game version: 0.E-3303-ge6b1dea

Operating system: Windows 10

Tiles or curses: Tiles

Mods active: Disable NPC Needs
Aftershock
Blaze Industries
C.R.I.T Expansion Mod
Magiclysm

### Expected behavior
Int he sidebar if I'm wielding a musket I expect to see **Wield: Flintlock Musket** no mater what mods I have attached

### Actual behavior
It instead shows **Wield: manual|| </colo** when there is a _shoulder strap_ and _makeshift bayonet_ attached.

### Steps to reproduce the behavior
![image](https://user-images.githubusercontent.com/10535336/84918264-5b30f080-b08e-11ea-938d-64e2e4909997.png)

**Comment by Rokmonkey** [comment]
I will note, a quick test.  Some of what is shown under Wield is correct, however once mods are attached it is drastically different.  With only the shoulder strap attached it shows _||flin_ even though normally is shows much more characters.  The addition of </colo as shown I don't know where it comes from.

**Comment by olanti-p** [comment]
"manual" comes from the fact that your musket can now be used in 2 modes:
`manual` - aim and shoot
`bayonet` - use the musket's bayonet (works like a spear)
So that part is intended.

The less characters thing and `</colo` popping up are likely caused by wrong truncation in `player::weapname`. I'll try my hand at fixing it
