### ISSUE TITLE
PR #41379 fix causes issues with siphoning iteration prompting

### ISSUE THREAD

**Issue by zeziba** [CleverRaven/Cataclysm-DDA#41395]
# Describe the bug

PR #41379 fix causes a underlying issue with how src/item.cpp::fill_with interacts with scr/veh_fill_with to become apparent. When filling up a vehicle if there are more than 2 tanks present when moving fuel through siphoning it will continue to prompt to select a tank to fill after every iteration.

# Steps To Reproduce

> Spawn two adjacent semi
> spawn a rubber hose
> siphon from one to the other

# Expected behavior

Once the siphoning process starts it should not re-prompt the user until the tank is filled or there is no longer anything to siphon or some other issue.

**Comment by EvgenijM86** [comment]
It's not a bug, it is a feature. I personally use to leave a little bit of fuel left in cars that I am interested in, so that I can later drive them away, while leaving 90+% of the fuel in my main vehicle. I see no reason why I should not be allowed to partially transfer fuel.

**Comment by zeziba** [comment]
I might have not been clear enough.

The issue is not the iteration but the re-prompting to select another tank mid way through the iteration. For example if you were to fill do the above to a single tanked vehicle you will not receive a prompt for each iteration but will perform each iteration with no further prompt but it will still stop the player from filling up if there is any type of safe mode threat. That is what you are talking about correct?

When the same is done to any multi tanked vehicle then it will re-prompt the player at each iteration step which is done from the `scr/item.cpp::fill_with` while loop that the `scr/vehicle_part.cpp` calls. 

Again to stress my point the iteration is not the bug it is the re-prompting to the user causing the player to have to hit enter `Volume/transfer rate` times for each instance of siphoning. Which in my test build on a 60L tank it transferred 0.7L per iteration causing over 80 additional key-presses.

**Comment by EvgenijM86** [comment]
In my example above the game have already warned about the zombies in your vision and you pressed ignore further warnings. The next warning you will receive is a "too close", when zombie is right next to you, which is what I want to avoid. And thus I want to have ability to siphon by small bits at a time and manually stop at any point.

Or here is a reverse example: let's say you drive on your car with 60L fuel tank that is almost full. Then you spot a car on the edge of the city that you want to switch to. You approach the car and the game give you a warning about zombies visible in your range. You press ignore. You examine the car and it misses car battery and fuel. You want to refuel it a little bit of fuel, so that the next time you go with the battery you can just drive it away to your base. You start siphon from you main vehicle. But someone posted an issue on github that says that you must siphon the whole 60L into it for some reason, or until zombie are right in your face when "too close" warning triggers (on winter start that is pretty much a death sentence).

**Comment by zeziba** [comment]
OK, so what you are talking about is actually another issue then as the above issue is only an edge case where specifically on multi-tank vehicles it fails to stop prompting the user to select a tank to fill with liquid.

Anything else other then this is not what this issue is referring to.

So if the safe mode fails to fire while doing the src/item.cpp::fill_with and in specific the insert command used in the while loop should be paused if there is indeed a supposed to be a pause.

The specific code would be 
```cpp
    while( pocket != nullptr && amount > num_contained ) {
        if( !pocket->insert_item( contained_item ).success() ) {
            break;
        }
        num_contained++;
        if( !pocket->can_contain( contained_item ).success() ) {
            pocket = best_pocket( contained_item );
        }
    }
```

This handles the insertion into a pocket/container for both the vehicle and any other thing that uses it.

The insertion is controled by the following,
```cpp
ret_val<item_pocket::contain_code> item_pocket::insert_item( const item &it )
{
    const bool contain_override = !is_standard_type();
    const ret_val<item_pocket::contain_code> ret = can_contain( it );
    if( contain_override || ret.success() ) {
        contents.push_back( it );
    }
    restack();
    return ret;
}
```

The vehicle code only calls on scr/item.cpp::fill_with to insert the fuel into the tank and is only passing it to that function. There is no control given to the src/vehicle_part::fill_with to determine if the pock can or cannot fill the tank as it stands nor if the sequence is stopped early from its completion.

That can be seen from the specific code used to fill the tank which is `liquid.charges -= base.fill_with( *liquid.type, qty );`
