### ISSUE TITLE
Derived ammo variants not showing their stats properly in the inventory

### ISSUE THREAD

**Issue by Brian-Otten** [CleverRaven/Cataclysm-DDA#41564]
Ammo that has its stats derived from the "base" ammo is showing its stats incorrectly, but has the proper values when used.

# Steps To Reproduce

1. Examine derived ammos in inventory (As an example i will use birdshot)

# Expected behavior

The game shows the proper relative values, notably the damage multiplier of 0.3
alternatively, don't show relative values at all and just show the absolute values, same as the base ammo it is derived from.

# Screenshots
![image](https://user-images.githubusercontent.com/47374323/85559693-3c040700-b62a-11ea-940a-df11cad4cab0.png)
![image](https://user-images.githubusercontent.com/47374323/85559721-445c4200-b62a-11ea-8706-eaa7fe69b34c.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-3486-ge60e4d8 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Rail Stations [No_Rail_Stations],
    No Fungal Monsters [No_Fungi],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex]
]

**Comment by AJsarge** [comment]
I've been trying to write out my diagnosing info for an hour, but I'm no programmer, so I have no idea how to write it.  So I'mma throw some sciencey mumbo jumbo at y'all to try and explain it.

_Problem:_ See above.
_Question:_ Is it the inventory bugging out, or is the damage calculation wrong, and the inventory right?
_Actions:_  Poke in the 9mm JSON as an example, figure out what's going on inside it, and mess about with stuff to see what changes in-game.
_Baseline:_ The issue isn't with base ammo types (such as buckshot, or 9mm JHP.  It's only when an ammo like birdshot or 9mm FMJ has "relative" or "proportional" values that the game messes up.  But, this is only when examining the ammo itself, or a loaded magazine.  Loaded weapons display appropriate values, and the reload screen (as shown above) shows appropriate values.
_Hypothesis 1:_ The inventory doesn't like relative/proportional value changes.  It instead shows a damage multiplier, which I think it's pulling from nowhere so we get the 1.00 value.
_Evidence:_ If I remove the "relative" and appropriate brackets, and make it an absolute overwrite of 9mm JHP's base damage (in this case, changing 9mm FMJ to be "amount", 24 instead of "relative"..."amount", -2) the inventory correctly displays FMJ to have 24 damage instead of a 1.0 multiplier.
_Hypothesis 2:_ There's some issue in the damage calculation for "relative" or "proportional" values.
_Evidence:_ In it's default coding, the reload and weapons info show a correct 24 damage for 9mm FMJ, appropriate with it's relative -2  compared to JHP.  But!, FMJ still shows a Pierce value of 0, even though the JSON has Armor_penetration at 4, and no matter if you examine the ammo/mag/weapon or within the reload window.  Changing penetration to "+4" throws an error, so I can only assume that a "4" in that line should appropriately add 4 to the pierce value.  Again, removing "relative" from FMJ changes the game to show the appropriate 4 pierce damage, just like the changes to damage.  Adding  "armor_penetration", 0  to 9mm JHP (or setting it to 10) doesn't change anything for FMJ.  As well, FMJ Black Powder is proportional to FMJ, and defining FMJ penetration non-relatively fails to change FMJ_BP's proportional penetration.
**Issues:**  I looked, and don't know where the code is for the inventory or damage calculations.  Someone will have to poke further to see if the game is only displaying the wrong values (probably due to relative/proportional calculations?) or if the actual  damage is being calculated wrong.

**Comment by anothersimulacrum** [comment]
The code is in item.cpp, look for iteminfo.

The damage loading code should be combining the relative and proportional into the same place that it is loaded normally, so I'm not sure why this occurs.

Experimentation has show that the armor penetration and damage values aren't just discarded, but still are used, however they don't display.

**Comment by dnikolajevich** [comment]
This is due to the imperfection of the "damage_instance class".
I noticed that the behavior of objects constructed through the default constructor differs from the behavior objects received through the static function "blank_damage_instance()".
Simple workaround:
In the "assign.h" file in the "assign()" template function for "damage_instance", remove everything in the "else" block and instead write two lines constructing damage_instance over an empty array.

`
inline bool assign( const JsonObject &jo, const std::string &name, damage_instance &val,
                    bool strict = false,
                    const damage_instance &lo = damage_instance( damage_type::NONE, 0.0f, 0.0f, 0.0f, 0.0f ),
                    const damage_instance &hi = damage_instance( damage_type::NONE, float_max, float_max, float_max,
                            float_max ) )
{
    // What we'll eventually be returning for the damage instance
    damage_instance out;

    std::string id_err = "no id found";
    // Grab the id for good error reporting
    if( jo.has_string( "id" ) ) {
        id_err = jo.get_string( "id" );
    }

    if( jo.has_array( name ) ) {
        out = load_damage_instance_inherit( jo.get_array( name ), val );
    } else if( jo.has_object( name ) ) {
        out = load_damage_instance_inherit( jo.get_object( name ), val );
    } else {
    	// walkaround of broken damage inheritance
    	JsonObject empty;
        out = load_damage_instance_inherit( empty, val );

        /* 
        // Legacy: remove after 0.F
        ... 
        */
    }
`
