### ISSUE TITLE
Decay and the passage of time.

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#4162]
Here's a simple system for implementing terrain decay over time.
Each terrain type gets assigned a half-life and one or more decay products.
Each time we load a submap, we have a last loaded timestamp, using this we can calculate the passage of time, and using that a weighted probability of the half-life occurring for each tile.  Decayed tiles will be modified in-place to be the new type. Ideally the comparison will yield when the decay happened, and we can re-roll with the new terrain half-life for additional decay.
This can apply to item decay as well.
Probably not good for crops, as we want that to be more deterministic.
Fire of course is still a problem.

Examples:
Terrain, half-life, product
Asphalt, 1 year, cracked asphalt
cracked asphalt, 1 month, weedy asphalt
Wall (exterior), 1 year, vine-covered wall
Wall (exterior), 1 year, crumbling wall
Wall (interior), 3 months, moldy wall
Meat, 6 hours, rotten meat
rotten meat, 2 days, pile of filth
pile of filth, 1 week, nothing
##

**Comment by qbradq** [comment]
Please apply label "Enhancement" so we can differentiate this from the defects easily. Great idea by the way :)

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
