### ISSUE TITLE
Tracking filepaths in Debug item spawn menu

### ISSUE THREAD

**Issue by BarBreaker** [CleverRaven/Cataclysm-DDA#41671]
# Is your feature request related to a problem? Please describe.

# Describe the solution you'd like

# Describe alternatives you've considered

# Additional context
Add any other context (such as mock-ups, proof of concepts or screenshots) about the feature request here.

**Comment by Qrox** [comment]
Well, this IS very concise. Not sure with the clear part though.

**Comment by ZhilkinSerg** [comment]
While you decide that your issue is of low effort and skipped filling issue template, possible tracking location (and hierarchy) of file origin for game objects loaded through JSON is actually tricky and requires significant input. It is something that we would love to have, but there is no need to keep debug function related issues in the backlog.

Debug menu already displays item ids which you can easily search for in data/mods folders. Showing file path there won't give you much - you would still need to locate and open all these files externally, so it is better to start directly from external search after you've got id of an item.
