### ISSUE TITLE
`Move all items` from inventory in AIM doesn't work

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#41706]
# Describe the bug

It presents you with `Really drop all your favorite items? (Case Sensitive)` but doesn't move anything regardless of your answer.

# Steps To Reproduce

1. Load the game.
2. `/`
3. `,` from your inventory

# Expected behavior

Every non-favorite item getting moved.

# Screenshots

# Versions and configuration
- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.E-3577-g8f973a75f6-dirty [64-bit]
- Graphics Version: Curses
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Blaze Industries [blazeindustries],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations]
]

# Additional context

[2020.06.30.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4853642/2020.06.30.zip)

**Comment by Menschheit** [comment]
That happens if you choose to move all items from your inventory. Because of nested container, you no longer has an "Inventory" anymore, all you have is what you wear and what you wield, everything else is "containts" of them.

P.S: There is another issue, if both the initial "source" and "targets" panes are "AIM_ALL", game will be terminated due to an assert() statement, should add additional sanity check after loading the saved stats to avoid that.
![123](https://user-images.githubusercontent.com/28317565/86284341-fffd1300-bbe2-11ea-90bb-66800b5d78fe.PNG)

**Comment by Qrox** [comment]
Seems to be fixed now.

**Comment by l29ah** [comment]
Indeed, thank you!
