### ISSUE TITLE
Rework flashlight and headlamp

### ISSUE THREAD

**Issue by Ununsept117** [CleverRaven/Cataclysm-DDA#41730]
# Is your feature request related to a problem? Please describe.

- Flashlight is described in the game as a "typical household flashlight with a plastic handle". Now show ma a typical household flashlight that weighs 400g and has volume of 0,5L. I've checked dozens of flashlights on [Amazon](https://www.amazon.com/s?k=flashlight&s=review-rank&qid=1593620363&ref=sr_st_review-rank) and I haven't found a single one that would fit these values.

- The same issue applies to headlamp. It has weight of 520g and volume of 0,5L. Headlamp can be crafted from a flashlight and long string/duct tape etc., so even if the flashlight really weighted 400g, that would mean a long string weighs 120g.

- Crafting headlamp takes 20 minutes. IRL headlamp made from a normal flashlight would look [like this](https://www.youtube.com/watch?v=lW9QB86M-UM), and I don't think it would take 20 minutes to make it.

- Disassembling headlamp takes 20 minutes. It yields flashlight and 2 rags/whatever you used to strap it on your head, so it would involve separating flashlight from the strap by cutting it, which should take seconds. 

- I guess survivor headlamp weight/volume might be okay because it's made to be more durable, brighter etc., although I'm not sure. But what I'm sure about is that you should be able to dissasemble it.
# Describe the solution you'd like

- Reduce weight and volume of flashlight and headlamp. By how much I'm not sure, but most flashlights weigh less than 300g and cheaper ones are less then 100g. Volume sohuld be somewhere between 0,1L and 0,25L.

- Reduce crafting time for headlamp. It should be as simple as crafting a headband and attaching a flashlight (see video above). Crafting blindfold which could serve this perpose takes 3 minutes, so I'm thinking about 5 minutes or so.

- Reduce dissasembling time for headlamp to 10 seconds or somewhere around that.

- Allow disassembly of survivor headlamp.

# Describe alternatives you've considered
Leaving it as it is.

# Additional context
none

**Comment by MatiasFito** [comment]
Wow @Ununsept117 amazing investigation, i will take on this change after reading all you've found now i can't leave flashlights as they are :smile: . Once i get the bulk of changes i will get back here and we can min/max the survivor lamp disassembly.

**Comment by MatiasFito** [comment]
@Ununsept117 hello again my dear friend :wave: , i've tweaked the values and played a little bit, it feels balanced and right, i will share the changes here:

- The headlamp now takes 5 minutes to make, i liked your suggestion of the time of a bandana (3m) plus a few minutes to arrange the light on the rags.
![Screenshot from 2020-07-03 13-22-27](https://user-images.githubusercontent.com/7430004/86486120-deaa3d00-bd30-11ea-9352-03b186d0c7f5.png)

- Also found the **Miner Hat** recipe, and it was already pretty aligned with your investigation, that recipe that took premade hard hats and strapped a light to them, would take 6m (which made sense, but not 20m for the makeshift light on a rag) to be consistent i toned it down to 3m so it's 2 minutes less than having to tie two rags first. I could make it 2 mins but at this point i don't think it makes much of a diff lol. I just did not want to leave it at **more** time than the other one.
![Screenshot from 2020-07-03 13-23-05](https://user-images.githubusercontent.com/7430004/86486347-6abc6480-bd31-11ea-811b-c05fb6a7a1b6.png)

- For weight and volume, also toned it down to 200gr and 200ml, it felt like the in between values, you can tell me if you feel some other values are more appropiate.
![Screenshot from 2020-07-03 13-22-50](https://user-images.githubusercontent.com/7430004/86486556-f46c3200-bd31-11ea-9440-6a11da7bf0a3.png)

- Finally i took a look at the survivor headlamp, this one takes 25m but i think it makes sense, because it takes metal scraps, light amps, and solder, screw driving, i mean it sounds it is somewhat complex, allegedly the sutvivor uses his/her knowledge to make the headband more sturdy and energy efficient, so i left it like that. But i did add the reversible flag.
![Screenshot from 2020-07-03 13-38-18](https://user-images.githubusercontent.com/7430004/86486743-8116f000-bd32-11ea-9abd-f922739e146a.png)

- What am i mising?, i do not know how to set the dissasembly time different than the craft time, out of the top of my head i can't remember an item that takes X time to craft and Y time to dissasemble, if you can think of any, i can look it up and try to guess how to config that on the headlamp. I will be back after work, cheers!

**Comment by Ununsept117** [comment]
Hi, good work! Here's my solution for disassembly time:
I just added this to data\json\recipes\recipe_deconstruction.json and it worked (and still yields components you used in crafting if they're different than rags):
{
    "result": "wearable_light",
    "type": "uncraft",
    "skill_used": "fabrication",
    "time": "30 s",
    "qualities": [ { "id": "CUT", "level": 1 } ],
    "components": [ [ [ "flashlight", 1 ] ], [ [ "rag", 2 ] ] ]
  }

You should also change the weight and volume of headlamp if you haven't already.
As for the survivor headlamp, the time is definitely right, I rather meant weight and volume. With your change the weight is increased by 420g and volume by 0,3L when compared to flashlight. 
As for the mining helmet I think the time crafting should be the same as headlamp, because it would involve making a headlamp and then attaching it to the helmet. I don't know how else it could be done so if you have other ideas please tell me. Also while we're talking about mining helmet, I noticed it can't be crafted with rags or leather patches, and it doesn't exactly make sense if you can craft headlamp with them, and you can make a mining helmet by strapping headlamp on it.

**Comment by MatiasFito** [comment]
Oh great, I'll do those tweakings, test it a bit and create the PR then, thanks again :wave:
