### ISSUE TITLE
Certain Items Being Cloned On Load

### ISSUE THREAD

**Issue by SageB** [CleverRaven/Cataclysm-DDA#41776]
# Describe the bug
When I load my save, the game displays an error (see screenshot), and several items (a wooden spear, a hacksaw, and a stone shovel) fall on the ground at my feet. These are all items that I _have_ had in my inventory at one point or another, but do not currently have in my inventory when saving the game. In the case of the hacksaw, the original doesn't even exist, as it has been crafted into a survivor utility belt.

# Steps To Reproduce
1. Load the attached save.
2. Move one square.

# Expected behavior
For items to not spontaneously appear on the ground at my feet when I load the game.

# Screenshots
The Error
![1](https://user-images.githubusercontent.com/30204365/86408498-b95bf700-bc7c-11ea-85ca-845b90936522.PNG)

The Items (multiple due to testing, it's 1 of each per load)
![2](https://user-images.githubusercontent.com/30204365/86408508-bc56e780-bc7c-11ea-8d81-9e9ebbb9b251.PNG)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-3669-g1c69950 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Monsters [No_Fungi]
]

# Additional context
[save_and_log.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4866632/save_and_log.zip)

**Comment by anothersimulacrum** [comment]
Same as #41648

**Comment by SageB** [comment]
Is it? They seem like completely unrelated issues...

**Comment by anothersimulacrum** [comment]
The game is freezing because items are being cloned on load, and now there are literally thousands of items in a pocket where they don't fit. The cause of that issue is what this one describes.

**Comment by Duck13Tales** [comment]
It is happening with me too. My water purification tablet got multiplied till it was so heavy that I couldn't lift it, then I threw it in the fire and got another (15) but it is multiplying again... I have a small cardboard box with (1000) toast-em and the box itself is over 100 Kg, and I have a bucket "with 2 items" that when I wield it it becomes "none" and the bucket itself weighs 1253003,05 Kg...

Every time I wield it I am thrown on the floor hahaha

**Comment by eilaattwood** [comment]
Yep, just thrown my leather backpack with 60000 crowbars in it into my fireplace.

**Comment by Menschheit** [comment]
There are several points may be related to duplication. 

1. In my first PR #41484 I forgot to delete some codes used for testing
![3](https://user-images.githubusercontent.com/28317565/86467466-b6710d00-bd35-11ea-9bbd-b379ae7cf030.PNG)

Even this is redundant, it should have been fine though,  but then there is something may break the if-statement.

![temp1](https://user-images.githubusercontent.com/28317565/86467573-e4565180-bd35-11ea-9726-e5406536dcb7.PNG)

while trying to call `item_pocket::insert_item` , if the pocket is not container, magazine or magazine_well (for example: MOD), it will be forced to be put into that pocket regardless of return value(true/false) . If the return value is false, that item will also be added to `uninserted_items`  and put into "MIGRATION".
And even in the original codes
![temp5](https://user-images.githubusercontent.com/28317565/86468144-14522480-bd37-11ea-8831-61d22c126ae2.PNG)
it may cause duplication for the same reason.

beside of this, in #41733 the pocket type was removed, I don't what will happen if a pocket dont have type in json defined.

The problem can only be reproduced by saving/loading several times, so it is a bit hard to track and test.

**Comment by Menschheit** [comment]
Sorry sometimes I only have a unclear image how things work before doing something. Is it correct now?

**Comment by hexagonrecursion** [comment]
I believe I have found a way to trigger this bug in a clean save file. Can someone please tell me whether this is the same bug or not?

# Variant 1 - duplicated items drop on the ground
1. Create a world with the following mod and start a new game
```
[
  {
    "type": "MOD_INFO",
    "ident": "BUG",
    "name": "BUG",
    "category": "items"
  },
  {
    "type": "GENERIC",
    "id": "this_changes_volume_between_versions",
    "category": "other",
    "name": {"str": "BUG"},
    "description": "BUG",
    "weight": "1 g",
    "price": 800,
    "material": [ "paper" ],
    "symbol": "*",
    "color": "light_gray",

    "volume": "4 L"
  }
]
```
2. Wear a purse (capacity: 5L)
3. Put 1 BUG in the purse
4. Save and quit
5. Change the volume of BUG from 4L to 6L
6. What should happen when you load the save? As far as the game is concerned there is now a 6L item in a 5L pocket. [I am told that when this happens items are supposed to end up in a limbo called "migration pocket" and get dropped on the ground one turn after the game loads](https://github.com/CleverRaven/Cataclysm-DDA/issues/42002#issuecomment-656549243). This does happen, but the current implementation is buggy (see below)
7. See the assertion "err: item too big" as intended
8. Wait one turn
9. See that the purse is empty and there is 1 BUG on the ground as intended
10. Save and quit
11. Load again
12. See the assertion again even though the BUG is supposed to no longer be in the purse at this point
13. Wait 1 turn
14. See 2 BUGs on the ground
15. Repeat steps 10 through 14 until you have the desired number of BUGs

# Variant 2 - duplicated items remain in the purse
Same as above except instead of step 2 you should wear a backpack (id: backpack) and put the purse in the backpack

Note that this seems different from what others have described - they say things like "60000 crowbars" but I see no way to find out the contents of my "purse with 11 items"

**Comment by misterprimus** [comment]
They merged a fix that fixed this, or something like this, for me. Can the poster try the save that had this problem and try to recreate it to see if it still happens on the latest experimental?

**Comment by hexagonrecursion** [comment]
I can no longer reproduce the variant 1 I described above. Variant 2 is still not fully fixed ("purse with none" stays and BUG is never dropped on the ground see #42273), but it no longer causes duplication.
```
- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 32 (Thirty Two); Release: 32; Codename: ThirtyTwo; 
- Game Version: 0.E-4254-gfea0266 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    BUG [BUG]
]
```
