### ISSUE TITLE
Boomer slime should make tires slip

### ISSUE THREAD

**Issue by souricelle** [CleverRaven/Cataclysm-DDA#41773]
Boomers are pretty trivial enemies. With some eye protection they're just a very weak zombie that you don't have to bash.

Driving over boomer bile at anything greater than like 30mph should trigger a driving/tire type/vehicle weight check otherwise you hydroplane over the goop and can't turn or decelerate until your tires have traction again.

**Comment by GGgatherer** [comment]
> until your tires have traction again

And maybe even 1-2 turns after that, depending on amount of tires and their diameter. Bigger tires - faster goop removal. More tires - less goop because there's a finite amount of it. Come to think of it, why only boomer bile? Why not any corpse, depending on the size and amount of wheels, and vehicle weight?

**Comment by souricelle** [comment]
That would probably get really annoying and make cars a lot less fun.

**Comment by Zireael07** [comment]
Why everything? Boomer bile is enough. Also, why close? The suggestion is very good.

**Comment by souricelle** [comment]
Accidentally closed, didn't mean to!
