### ISSUE TITLE
[Magiclysm] Puntastic spells

### ISSUE THREAD

**Issue by KorGgenT** [CleverRaven/Cataclysm-DDA#41990]
# Is your feature request related to a problem? Please describe.
Cause bear is the only pun spell in magiclysm right now. It could really use a couple more failed experiments: mostly puns caused by typos.

# Describe the solution you'd like
Create new spells that are a pun on some existing spell, or something that would be a spell (Cause Fear -> Cause Bear). I would like them to be in the same itemgroup as the smudged scroll, and of a similar power level. Ideally each class will get one, but it's better to be a little more organic when using creativity and puns.

# Describe alternatives you've considered
No Puns. A Travesty.

# Additional context
Over all i'd like at least half a dozen pun spells, but a PR with a single spell is perfectly acceptable.

**Comment by gc2020x3** [comment]
@kevingranade @KorGgenT
We are the Grey Committee. 

Cataclysm started as great Community Project. But recent events indicate that normal and healthy relationship between Community and Developers are lost and development going nowhere. Main reason of this is Kevin Grenade.

Kevin Grenade, current Project Leader deemed exclusively rights on everything in Cataclysm, violating project license and intellectual honesty. 

He does not respect community opinion and opinion of his own development team alike. Reasoning with him became pointless long time ago. A lot of people left project because of his attitude and decision making.

Worse of all that project development start going with questionable ways at best. Instead of proper and logical decision making changes start becoming more and more chaotic and subjective. Game becoming a mess.

So we are decided that time for compromises has passed. The Grey Committee was created to fight back.

Our Manifesto is simple:
1) Kevin Grenade must leave the project forever.
2) New Development Leader must re-establish normal relation between Development Team and Community.
3) All bans since beginning Kevin Grenade leadership must be revoked.

This goals are not negotiable and can be considered as our ultimatum.

To achieve our goals, we will engage Kevin Grenade and ones who blindly supports his behavior in various ways of informational and psychological warfare.

We are not going allow some false dictator to steal our project and reduce it to dust.

«In the struggle you will gain your rights»
Grey Committee.



To make our word loud we will repeat this message for ... a couple of times.

**Comment by ParaplegicRacehorse** [comment]
One wonders if Ken St. Andre would object to borrowing spells from Tunnels & Trolls. Many of them are puns.

Take That You Fiend! = D&D Magic Missile or other generic attack spell
Poor Baby = healing spell

etc.

**Comment by NickVolynkin** [comment]
Finger Firefighter — a miniature fire extinguisher, analogous in size and power to [finger firelighter](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/mods/Magiclysm/Spells/kelvinist.json#L28).

**Comment by NickVolynkin** [comment]
Paralytic Fart — the AoE version of [Paralytic Dart](https://github.com/CleverRaven/Cataclysm-DDA/blob/49a278ed96de6b6e07967307dd202e88616ea98d/data/mods/Magiclysm/Spells/biomancer.json#L177). Will hit the caster if they don't have enough environment protection.

**Comment by GGgatherer** [comment]
Horrid Tilting - makes all enemies in area to tilt horribly. Possible results: penalty to attack rolls, knockdown, stun or (low chance) death because of broken neck.

**Comment by NickVolynkin** [comment]
Sharkspray — the new [Shardspray](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/mods/Magiclysm/Spells/earthshaper.json#L76). Maybe it should only work underwater and/or sharks should be hostile to the summoner.

**Comment by NickVolynkin** [comment]
Summon Decayed Bouncer — summon a zombie hulk which will go to the nearest door and stand guard, keeping anyone from passing. Can't be managed otherwise, and won't follow the summoner. (Made from [Summon Decayed Pouncer](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/mods/Magiclysm/Spells/animist.json#L126)).

**Comment by NickVolynkin** [comment]
Repelling Art — make an inscription on a wall or a placed furniture which would repel zombies and lower the morale of living characters in some radius. Like any summoned item, disappears in a while. Source: [Repelling Arc](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/mods/Magiclysm/Spells/stormshaper.json#L316).

**Comment by Light-Wave** [comment]
Inflict Paint - Covers target in paint, extinguishes any fires on them and makes then unable to turn invisible like night stalkers does. Makes the target leave a trail of wet paint for the duration. Can also be used to paint walls, furniture, and items.
Cure Eight Wounds - Restores exactly 8 HP. Always.
Raise Bread - Allows for the baking of bread without yeast.
Joyful Raptor - Summons a dinosaur that is friendly to everyone and too joyful to fight back. Still aggros enemies. Like a somewhat stronger mirror image.
Symbol of Sheep - Magical trap that, when an enemy steps on, summons a single sheep nearby.
Altar Shelf - (Perhaps overpowered) Rerolls the random spawned items at target location
Zone of Science - Everything requiring applied science is crafted faster in this zone.
Detect Tragic - Reveal target NPC's backstory without having to talk to them
Scorching Rat - Summons a burning rat to fight your enemies. Explodes into fire when it dies.
Börkskin - People around you just assume you speak Swedish. NPC dialogue is translated to Swedish.
Commune With Texas - Lets you talk to people in Texas.
Control Frames - Allows you to alter targeted framerate of the game.
Chromatic brb - Target creature is removed, and a burst of a random energy type damages nearby creatures. After about a minute, the targeted creature is retuned.
