### ISSUE TITLE
Never-Ending Spurge Tea Antiasthmatic Effect [Bug?]

### ISSUE THREAD

**Issue by BrokenPaw-0-1** [CleverRaven/Cataclysm-DDA#42021]
# Describe BUG
Days, weeks, a very long time has passed since I drank "antiasthmatic drugs" (that being spurge flower tea) and the effect has not expired on the character sheet "shift + 2" screen.

So I invite you to make yourself some spurge flower tea and take some sips, and see how extremely long the effect last. Those are some potent herbs.

# Steps To Reproduce

1.) Make yourself some spurge flower tea in-game.
2.) Drink that tea and wait for the effects to expire (what's intended time-wise I'm not sure).
3.) Weeks or even months down the road you'll see you still have that status present.

# Expected behavior

The tea's effects to not be super-man strength and last for ever it seems.

# Screenshots

n/a

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-3894-g4929649 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Alternative Map Key [alt_map_key],
    Stats Through Skills [StatsThroughSkills]

# Additional context

See Included save game.
Thank you for your time and if you spot anything else that's anomalous please point it out.

[Halfway.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4905790/Halfway.zip)

**Comment by Ichthysdekilt** [comment]
Can confirm on 10836 with a new world, new survivor, no mods that the spurge tea's effect lasted for at least 4 days (didn't check longer than that).

I suspect this is also happening with vaccine's as I have another survivor who took one an ingame year ago and is still receiving the benefits - though with fewer people around to spread diseases maybe this is intentional?

**Comment by Ktmi** [comment]
Can confirm. Only really now realized that having the anti-asthmatic effect for a few in game weeks is probably a bug.

**Comment by AdelaBeard** [comment]
This issue still persists and I am commenting on this in the hopes that it will be addressed for 0.F

**Comment by neosulc** [comment]
This bug still persists in current experimental, How Can I help to confirm it?

**Comment by anothersimulacrum** [comment]
You just did, congrats!

**Comment by actual-nh** [comment]
This appears to be because, in iuse.cpp, the ANTIASTHMATIC effect is added as `p->add_effect( effect_took_antiasthmatic, 1_days, true );` - and, in the only place I can find an add_effect function with those parameters (talker_character.cpp; noted as override in talker_character.h), the final boolean parameter is for making it permanent.

**Comment by actual-nh** [comment]
> 2.) Drink that tea and wait for the effects to expire (what's intended time-wise I'm not sure).

The intended duration is 1 day, as far as I can tell.

**Comment by neosulc** [comment]
> The intended duration is 1 day, as far as I can tell.

Effect persisted for more than 2 seasons, definetly stuck.
