### ISSUE TITLE
Should be able to see if otherwise perishable food is currently sealed and unable to spoil in the 'E'at menu

### ISSUE THREAD

**Issue by VitreousEyes110** [CleverRaven/Cataclysm-DDA#42068]
When in the 'E'at menu food that is sealed inside cans/jars will display as spoiling as if it wasn't sealed. This is irritating as I can't distinguish between food currently sealed  inside cans/jars and food that isn't that needs to be eaten soon. This used to be solved before the container/pocket changes by greying out the text of the food item in the 'E'at menu. The change completely removed this information from the 'E'at menu, now requiring the player to look through the item pickup/advanced inventory to check which foods are sealed.

Example:
![curryExample](https://user-images.githubusercontent.com/45680256/87254549-68ed5200-c451-11ea-84c3-14cb1520e8ad.PNG)
Curry appears as if it's going to spoil in 5 days from the 'E'at menu
![curryExample2](https://user-images.githubusercontent.com/45680256/87254551-6be84280-c451-11ea-9468-f5d0228a2785.PNG)
However from the item pickup menu it clearly will not spoil and shows as sealed.

A solution would be some way to see that a food item is sealed/not sealed from within the 'E'at menu, either with greyed out text like it used to have or anything at all giving that information to the player from that menu.

**Comment by RoyBerube** [comment]
![image](https://user-images.githubusercontent.com/30374490/88822190-c9360080-d180-11ea-9466-ca52760176cc.png)

This is my solution so far: adding a 'sealed' note into the freshness column. I don't think overwriting the color coding is a good idea because the contents can go rotten in some sealed containers such as a condiment bottle.

Does this adequately address the issue?
