### ISSUE TITLE
Certain Melee Techniques Never Trigger

### ISSUE THREAD

**Issue by Bulletfang** [CleverRaven/Cataclysm-DDA#42104]
# Describe the bug
This is a 2 in 1 special bug report! (because I think they're related but I have no evidence)
1. The sweep attack technique that is innate to the quarterstaff, fire axe and their variants do not trigger, enemies never receive the downed status and no message is displayed that a sweep attack was used.  (I only tested these two but I strongly suspect the sweep attack doesn't trigger for any melee weapon)
2. Grab break from the martial art 'brawling' never triggers.

# Steps To Reproduce

Use the weapons or martial art with the necessary skill requirement and see that both their techniques are never applied.

# Expected behavior

Sweep attacks and grab break attacks are used when applicable.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-3974-g078a56c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key],
    Mutant NPCs [mutant_npcs],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Urban Development [Urban_Development],
    Bionic Slots [cbm_slots],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries]
]

**Comment by anothersimulacrum** [comment]
Paging @Hymore246 - no obligation, you just seem to like martial arts.

**Comment by Bulletfang** [comment]
The grab break for Krav Maga also doesn't trigger.

**Comment by harison86** [comment]
I can also confirm the Muay Thai grab break never triggers. I think it's safe to say all of the grab breaks are broken.

**Comment by Hymore246** [comment]
I've looked it over and found a few problems. The biggest being that the character requires a "grab_resist" > 0 to allow for a grab break but it always seems to be 0 and I can't find any code that increases or calculates it. It might be something specific for monsters instead of players but I am not sure. 

@anothersimulacrum  any idea if some backend changes to player information might have broken the check?

**Comment by Hymore246** [comment]
Ok talked it over on Discord here is what is happening.

1. The melee techniques not triggering is because they are not set to "melee_allow: true" meaning you can't trigger it with weapons. But weapons are the only place you can use the technique... Derp. This is an easy PR to fix.

2. The problem with the grab breaks was "grab_resist." Turns out this variable is NEVER used anywhere in the code aside from it being declared. In fact, prior to 0.E, it wasn't even declared (set to 0). In C++, if an undeclared variable is ever called, it pulls random garbage data as its value. In almost all cases, that will evaluate to TRUE because only 0 is FALSE. In other words, the only reason grab breaks worked previously was due to a coding error! 0.E fixed most variables being undeclared which "broke" grab breaks. After talking with the devs, I have decided to create a PR to completely remove grab_resist and all related functions as it is never used ANYWHERE in the game aside from the grab break check.
