### ISSUE TITLE
Can't hatch chicks from chicken eggs

### ISSUE THREAD

**Issue by Duck13Tales** [CleverRaven/Cataclysm-DDA#42183]
# Describe the bug

I left some chickens in a pen. They are laying eggs but the eggs are even getting rotten but aren't spawning chicks. Is it intended? Is there any way currently to breed chickens?

Though chicks grow into chickens it seems that there is no way to get chicks.

I found in the json what time chicks need to grow into chicken but nothing about egg_chicken hatching chicks.

# Steps To Reproduce

1 - put some chickens in a pen, with bird food if you wish.
2 - Watch them putting eggs but leave them alone for a few days.
3 - Watch the eggs getting rotten but no chicks at all.

# Expected behavior

Having chicken eggs hatch chicks after some time.

# Screenshots

Not applicable.

# Versions and configuration

I am using using the CDDA 0.E-b10839 with the mods:

DDA
Disable NPC needs
Stats through skills
Stats through kills
SpeedyDex

**Comment by Hirmuolio** [comment]
Tested and chicks still spawn from eggs. But this takes way too long. 

It happens when the egg has 2x of the required rot to be marked as rotten. Eggs become rotten after one week. 
It is a bit of a abuse of game system. The eggs "rot" into chick.

So after the egg has 2 weeks of rot in it a chick will spawn (how long this actually takes depends on enviroment temperature).

**Comment by Duck13Tales** [comment]
Wow, I would never have guessed. Thanks a lot!

Then do you know if this happens with all the eggs then?

I noticed that the birth and growth from monsters is measured in days. Wouldn't it be better to be measured in seasons?

**Comment by Hulkninja** [comment]
> The eggs "rot" into chick.

Thanks I hate it
