### ISSUE TITLE
Shoudl light amp googles or inferior versions of it be craftable?-suggestion

### ISSUE THREAD

**Issue by Azazoth** [CleverRaven/Cataclysm-DDA#42218]
# Is your feature request related to a problem? Please describe.
Currently only way to get night vision googles is to pray for rng  to give it  as they are pretty usefull but rare as heck.I found several do it yourself night vision googles videos just on youtube with some of them involving using smartphones or modifying cameras things whcih can be found laying aroudn in game and real world ...I am not expert nor i have night vision googles but it seems to me that crafting them from avaible electronics is doable...

# Describe the solution you'd like
If possible and in domain of reality night vision gogles or some inferior versions shoudl be craftable with certain  preresquities..

# Describe alternatives you've considered
If its not realistic it shouldnt be craftable

# Additional context
NIght vision googles woudl make electonics skil more usable.Its anecdotar but before obsoletion of night vision recipe i usually put point into electonics so i coudl craft them at early game.

**Comment by esavier** [comment]
Actually this is preatty sweet idea. Right now its really hard to use high electronics for anything (most of the stuff you find is good enough)
Problem is related to the stuff you would need to actually make military grade light amp goggles, however if simplified version based on CCD matrix (like from phones or camera) would exist (added to game), it would be doable.
I think its also a good idea to :
* make it so there are decent chances that military grade amp goggles are  found in military locations
* higher chances to high tier military zombies to have them on.

Also if we are at this, maybe a chance to have find broken military grade amp goggles and use electronic skill to fix those.

**Comment by kevingranade** [comment]
Need details, what are the properties of these devices cobbled together from cellphone cameras, what tools are used, etc?
I'm fairly certain they wouln't be a drop in replacement for any of the existing items.

**Comment by esavier** [comment]
dropin replacement - no definitively not, rather something in the middle between nothing and standard amp goggles

### IRL
In real world conditions you can do this kind of thing with literally any kind of light sensitive matrix (cellphone camera, cctv, nanny cam, or whatever else), some kind of circut board and a display matrix (i.e. lcd display of, for example, 144p resolution). To be blunt, there is a potential to amplify any signal from ccd matrix, given light can actually give a measurable signal in the first place, however quality of the image will fall drastically. To get best results you will have to let forget about any colors, also depending on ccd matrix, your frame rate may be lower since matrix will need more time to gather limited light. What pixels should be read as brighter and what should stay the same is dictated by software.
example of ccd amplifier for civilian use (hunting) (rather better ones) 
![obraz](https://user-images.githubusercontent.com/5251231/88241292-fb7bc580-cc89-11ea-9270-a3348774431c.png)

### Military NVD
Military nvd works in different way. There is no ccd matrix to gather light and no software to control brightness, instead there are high precision tubes, that given external source of energy, can amplify low spectrum of light. Those tubes can not be hand-crafted (maybe found in broken NVD's in our case?) and materials and tools to make those are not widely available. More reference to those here:
[NVD tech review PDF](https://www.inframet.com/Literature/Review_of_night_vision_technology.pdf)

### In Cata
Depending on implementation we can allow players to DIY basic ccd amp goggles:
- tools and materials required - screwdriver set, soldering iron, ccd matrix from some source (maybe phones could be useful here), circuit board or electronic scrap, LCD display, wires, some plastic
- some variations should be possible based on quality of the elements, i.e. quality of circuit board, or quality of ccd matrix ( there are ccd matrices already adapted to use low amount of light coming through lens, i.e. some security cameras or cctv)
- how would that work? i dont know right now. Since in cata there is only one military nvd (no breakdown between gen1 to gen4) there is no point speculating. I think that should be done via balancing. Maybe we would be able to actually add better and worse military amp goggles to accompany civilian ones, depending on how much work there is to do with those and if there would be distinct difference between those.

**Comment by kevingranade** [comment]
I can buy the CCD modification argument, as for drawbacks all we have to throw at it right now is encumbrance compared to a more refined NV system based on bulk, angle of view, and resolution and refresh rate issues.
Ideally that refresh rate thing would be prohibitive for some kinds of combat, but we can look into that later.

**Comment by Rivet-the-Zombie** [comment]
Player-made versions could also do stuff like eat battery charge at an accelerated rate, be more fragile, and have a shorter visual range.
