### ISSUE TITLE
Bring back the possibility to consume things directly from the tool used to cook it

### ISSUE THREAD

**Issue by matt32106** [CleverRaven/Cataclysm-DDA#42226]
# Is your feature request related to a problem? Please describe.
Naked character + a fire + a pool + a pot. Make clean water. You cannot drink it in the current experimental. This is not logical, why can I not drink the cleaned water from the pot?

# Describe the solution you'd like
Be able to consume directly from the cooking tool (this was possible before).

# Note 
I filed this first as bug #42201 but it was rejected as intentional, I don't understand what is the logic of this intentional.

**Comment by anothersimulacrum** [comment]
Consuming food takes time now, and is no longer instantaneous. Because of this, there must be somewhere to store the liquid while it is being consumed.

**Comment by BenlyAZ** [comment]
I believe if you wield the pot while cooking, you should be able to choose it as the destination container. If you can't (not in a position to check), then that would be a bug or oversight.

**Comment by matt32106** [comment]
> Because of this, there must be somewhere to store the liquid while it is being consumed. 
Ok but why not the container where it is?
> (Also, you can request issues be reopened)
I don't mind if you think it is not a bug. No problem for me to request a feature. What I would like is to get the old feature back because it was closer to what happens in reality where you can eat/drink while cooking without having to have another container.

**Comment by anothersimulacrum** [comment]
What happens in crafting is that you take all the items you need for the craft, and store them in the craft item. Then, when that craft item is produced, it places it's results where it was being worked on, or, for liquids, prompts you where to store them - there's no point at which the liquids are in a container during a craft.

Now, it would make sense to require liquid crafting to require containers while being crafted, which would resolve this issue, but that's not the current state of things.

**Comment by Ramza13** [comment]
So as the person who introduced this problem, it's set up this way at the moment because while its annoying, the fix required to fix it looked pretty difficult/bug prone.  

The logical answer is that the clean water would start in the tool you boiled it in. But in the current set up (and this happened earlier in nested containers when it was less stable) there is no guarantee that that tool can store liquids and at least for me personally there are a lot of unknowns around crafting.  You'd have to set up allowing you to use tools that are containers and add logic to check that they are empty/only contain the right stuff have enough space, change the tool detecting code, possibly have to change a bunch of json, and probably some more things I don't even know about.

It's solvable and I get your frustration and I went back and forth on how to handle this a lot but at least in my opinion the amount of changes/danger of creating bugs involved made this the right solution at least for now.  That said as nested containers continue to become stable it makes more sense to tackle this, though I have no plans at the moment to do so. 

It seems to me to be hard to say whether its a bug or feature request and you could argue either I guess.  Either way hopefully during stabilization for the next release this will get handled by me or someone else.

**Comment by matt32106** [comment]
Fair enough, I understand there maybe be intricacies to tweak the code so that the tool is not only a tool but also at the same time a container. I appreciate that it can be difficult to cope with in the current state of all the bug fixing around nested inv. But, just knowing that you and other devs know about it and think about fixing it someday is enough for me. Maybe make it a long term issue?! Thanks for listening.

**Comment by jbytheway** [comment]
It already is; it's one of the oldest open issues: #171.  Given that no one's figured out how to solve it in seven years, I wouldn't hold your breath :).
