### ISSUE TITLE
Use weapons without magazine by loading single round

### ISSUE THREAD

**Issue by Fabian-Schmidt** [CleverRaven/Cataclysm-DDA#42235]
# Describe the solution you'd like
Allow using a weapon without a magazine by directly loading a single round into the chamber.

There must a be time penalty to directly loading into the chamber. But at least I can use the gun when I don't find a magazine.

**Comment by buffog** [comment]
1) [Open bolt guns](https://www.youtube.com/watch?v=Ga4uoWmfEt4) can't be used in such way because of the way their mechanism works. 
2) Some handguns(for example, Browning Hi-Power) have “magazine disconnect safety”; its purpose is to prevent the gun firing if its magazine has been removed. 

Probably one of the more convenient implementations is a flag that allows reloading a gun with one bullet and firing it without magazine.

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/let-us-load-single-rounds-into-guns-without-magazines/27495/2
