### ISSUE TITLE
Cannot use hairpin as a lockpick if it's worn

### ISSUE THREAD

**Issue by GGgatherer** [CleverRaven/Cataclysm-DDA#42242]
# Describe the bug

Subj. It doesn't even say you cannot use the hairpin, it says instead "That cannot be picked".

# Steps To Reproduce

1. Make a player with a hairpin and wear it.
2. Make locked door (spawning military bunker, for example)
3. Try using the hairpin.

# Expected behavior

Either game should say you cannot use hairpin while wearing it, or, even better, just allow using it. 

# Versions and configuration

- OS: Windows 7
- Game Version: 0.E-4226-g1ea5556 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Night-Pryanik** [comment]
That's intended. If you want to use it, take it off first. You don't want to damage your precious hairpins, do you?

**Comment by GGgatherer** [comment]
> You don't want to damage your precious hairpins, do you?

What do you mean?

Anyway, all it does is just add another needless step(taking it off). Why does hairpin which lies in a bag work but a hairpin which is in your own hair doesn't? What's the cardinal difference here? It especially doesn't make sense to me because hairpin in hairs would actually be *easier and faster to reach*.

**Comment by Night-Pryanik** [comment]
>What do you mean?

Lockpicks (hairpins included) have a chance to be damaged and eventually break when you're using them to pick locks. Since hairpins have a very low lockpicking quality, they are especially prone to be damaged while using. So I ask you again: if you're _wearing_ hairpins, you don't want them to be damaged or more so be destroyed, do you?

**Comment by jbytheway** [comment]
From my perspective, a hairpin is exactly a lockpick that doesn't take inventory space.  If I'm wearing a hairpin then I absolutely want it to get used automatically as a lockpick.  You might be able to argue that a fancy hairpin would be bad to get damaged, but hairpins have no other useful effect than lockpicking.  Why else would you be wearing them if not to lockpick?

**Comment by Night-Pryanik** [comment]
>Why else would you be wearing them if not to lockpick?

Fancy hairpins give a bonus to morale if the character has the Stylish trait.
Otherwise, roleplay/character reasons. The same reasons players make their characters wear (otherwise useless) underwear.

The whole issue was raised in this comment (https://github.com/CleverRaven/Cataclysm-DDA/pull/35083#issuecomment-546694762). I found it valid, so I addressed it in that PR. If current behavior is inconvenient, it's rather easy to remove that check for worn items.
Seems like it worth discussing, so I'm reopening the issue.

**Comment by andrei8l** [comment]
I prefer the current behavior (for RP) and I think you can satisfy both sides if you move the `is_worn()` check down to the `for( item *it : picklocks )` loop (at `iexamine.cpp:1472`) and display a message that you're skipping worn lockpicks.

**Comment by Night-Pryanik** [comment]
No discussion in more than half a year, closing.
