### ISSUE TITLE
NPC carries Glock 22 loaded with .357 SIG, but Glock 22 can't use SIG

### ISSUE THREAD

**Issue by Madrawn** [CleverRaven/Cataclysm-DDA#42254]
# Describe the bug

I looted a guard in the rescue center. He carried a Glock 22 with an extended magazine which was loaded with .357 SIG. But if I try to shoot it tells me that the Glock 22 can't fire with incompatible ammunition loaded.

I also spawned a Glock 22 and extended mag via the debug menu. The mag spawned loaded with .357 SIG. Same story. When I spawned .40 S&W and loaded that it worked.

# Steps To Reproduce

1. Make a player with a Glock 22, magazine, and some .357 SIG.
2. Try to shoot.
3. It doesn't shoot.
4. Check out npc guards in refugee center. They spawn with Glock 22s loaded with .357 SIG.

# Expected behavior
If Glock 22 is supposed to be able to shoot .357 then it should do so. And if it isn't it shouldn't spawn with .357 loaded.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-4241-g36ba9f8 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by Hulkninja** [comment]
Having the same issue. Looted several Glock 22's, neither can shoot SIG .357, both can shoot 40.

The description says it should be able to use .357 SIG, so it's probably a bug that was recently introduced.

**Comment by Hulkninja** [comment]
Okay, so the issue seems to be that there are two different versions of the Glock 22, one for .357 SIG and another for .40 S&W.
Somewhere, somehow, these two versions seem to not have been properly "separated", for lack of a better term. Meaning that the .40 S&W says it takes .357 SIG ammo, despite ONLY accepting .40 S&W.

Now we're getting somewhere. The solution would probably be to make sure the gun says it uses .40 S&W ammo as default, and changing the kind of ammo that the .40 version spawns with.

Unfortunately, I'm about as good at coding as I am at quantum physics. Which is, terrible. So we'll still have to wait for someone to actually do it.

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/what-ammunition-does-the-glock-22-actually-use/25522/1
