### ISSUE TITLE
Expand artifact Procgen rules

### ISSUE THREAD

**Issue by KorGgenT** [CleverRaven/Cataclysm-DDA#42261]
# Is your feature request related to a problem? Please describe.
Currently the artifact procgen rules are rather light. I would like for them to be expanded to make artifacts more interesting, and perhaps make each of the different rules uniquely associated to what their ID entails.

# Describe the solution you'd like
More adjustable stats to make the artifacts more varied.
The randomly generated artifacts have a power level of 2000 and a maximum negative value of -1000. What this means, is that if there is a procgen stat that puts it below -1000 (it can go over) it won't gain any more negatives, and if it puts it above 2000 net (it can go over, too) it'll stop rolling for effects. So if there are any stats that cost 1750, it is quite possible to end up with an artifact with a power level of 3750.

# Additional context
Associated documentation:
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/ARTIFACTS.md
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/MAGIC.md#allowed-id-for-values

**Comment by gc2020x3** [comment]
@kevingranade @KorGgenT
We are the Grey Committee. 

Cataclysm started as great Community Project. But recent events indicate that normal and healthy relationship between Community and Developers are lost and development going nowhere. Main reason of this is Kevin Grenade.

Kevin Grenade, current Project Leader deemed exclusively rights on everything in Cataclysm, violating project license and intellectual honesty. 

He does not respect community opinion and opinion of his own development team alike. Reasoning with him became pointless long time ago. A lot of people left project because of his attitude and decision making.

Worse of all that project development start going with questionable ways at best. Instead of proper and logical decision making changes start becoming more and more chaotic and subjective. Game becoming a mess.

So we are decided that time for compromises has passed. The Grey Committee was created to fight back.

Our Manifesto is simple:
1) Kevin Grenade must leave the project forever.
2) New Development Leader must re-establish normal relation between Development Team and Community.
3) All bans since beginning Kevin Grenade leadership must be revoked.

This goals are not negotiable and can be considered as our ultimatum.

To achieve our goals, we will engage Kevin Grenade and ones who blindly supports his behavior in various ways of informational and psychological warfare.

We are not going allow some false dictator to steal our project and reduce it to dust.

«In the struggle you will gain your rights»
Grey Committee.



To make our word loud we will repeat this message for ... a couple of times.
