### ISSUE TITLE
Corpses generate foul-smelling air

### ISSUE THREAD

**Issue by Entity-y** [CleverRaven/Cataclysm-DDA#42329]
# Is your feature request related to a problem? Please describe.
Right now corpses are essentially junk items, easily ignored.
# Describe the solution you'd like
Once the corpse begins to rot, generate foul-smelling air that gradually consumes an enclosed space over time. This would force the player to properly dispose of or move corpses out of areas they may spend a lot of time in.

# Describe alternatives you've considered
Additionally when a corpse is in sight add an increasingly intense morale debuff calculated by the time the corpse has been in view and how far along the corpse has rotted and if the player is exposed to foul-smelling air.

# Additional context
Certain mutations and traits should affect the morale debuff, pacifists and weak stomachs get the worst of it while psychopaths and strong stomachs are able to manage, saprovores getting an increasingly positive buff instead.

**Comment by Fallout48** [comment]
It would be cool if decayed zombies, rot-weilers, their upgrades and similar enemies also had something similar. Getting bear hugged by a rotting mass of filth would ruin anyone's day.

**Comment by cainiaowu** [comment]
duplicated of #24457

**Comment by Xenomorph-III** [comment]
DF Misama, here we come.

**Comment by Bulletfang** [comment]
It was inevitable.

**Comment by ZaricaDemoni** [comment]
I do have to agree with kevingranade in the related post of #24457 you can become use to from exposure way too quickly.. even in real life we sometimes forget a smell exists from just a few days of exposure to it consistently. Ask anyone who has actively worked in a fish market during summer. its bad at first then is nothing after a few days to a week. Though, on what fallout said here, a decaying zombie or rot-weiler, a small addition to them giving off semi-toxic fumes when dealing with them in close quaters would make a dust mask much more useful in the game starting off since they are pretty common enemies.

**Comment by Entity-y** [comment]
If the corpses are outside it's one thing, there's airflow and the smell is quickly dispersed. In an inclosed space on the other hand, you're not getting desensitized to that smell no matter how long you've been exposed.

**Comment by ZaricaDemoni** [comment]
nose blindness is actually pretty common in enclosed spaces. we don't smell our own house funk like new people do upon entering. that, and adding in a major calculation of airflow just for a moral change is. silly to be honest.

**Comment by andrei8l** [comment]
> that, and adding in a major calculation of airflow just for a moral change is. silly to be honest.

It doesn't have to be an expensive smell calculation - it could be a field similar to `emit_migo_atmosphere` that represents flies or other tiny carrion-types

**Comment by Entity-y** [comment]
@ZaricaDemoni there's a huge difference between house funk and a decomposing body. The latter only getting more intense as time passes.

**Comment by ZaricaDemoni** [comment]
nose blindness is considered the bodies defense against over stimulation of the nervous system due to the same smell constantly barraging us constantly., this includes but not limited to, cooking food, rotting meat, pets, body odor, flowers, scented candles.

The study of smell aside, most people tend to avoid letting bodies or food rot due to it spawning carrion (when people butcher the undead, psychotic monsters) and plagued roaches are not fun.. mostly by mass piling them and dropping a match on it. this is also a very effective way of cleaning up the unwanted clothing clutter I find.

**Comment by Entity-y** [comment]
Sure you could avoid letting it get to the carrion stage, before then putrefaction is still setting in and the body isn't holding back on releasing all those nasty gasses. This could even be used to identify bodies in another room you may have forgotten about, preventing the carrion from ever occurring. 

There is a certain element about walking into an abandoned room and being hit in the face with the scent of death, seeing a pile of bodies left alone to time, then feeling upset about it that just fits into the theme of the game.

**Comment by I-am-Erk** [comment]
As an overall concept I think it's more useful to think of this not as nose-blindness because you have decaying zombie corpses in a pit behind your base and are used to it, but the effect of opening a house while scavenging to find that inside, a pair of pulped zombies have been sealed up in the summer heat liquefying over weeks. You'd be able to get used to that, yes, but the *initial* effect would be quite a potent morale and nausea effect. Probably we could get away with just simulating a one-time exposure to the smell that then causes an immediate effect and then leaves you immune until you return to the open air. We don't really need to simulate putting peppermint oil on your surgical mask.

**Comment by Entity-y** [comment]
> We don't really need to simulate putting peppermint oil on your surgical mask.

Now that you mention it, that wouldn't be a bad addition to complement the feature.

**Comment by I-am-Erk** [comment]
It never works as well as you think it's going to work. You just wind up smelling peppermint flavoured putrescence.

**Comment by meladath** [comment]
The ability to move corpses up and down Z levels would be essential before this could be implemented imo, otherwise the player could really be in some bad spots.

**Comment by anothersimulacrum** [comment]
You've been able to since #28365, and everyone has had that since #41707

**Comment by Fallout48** [comment]
I thought about this thread again since I started watching a TLOU2 playthrough.

What if fungal corpses occasionally spew out spores? Or they start producing a spore gas field if given enough time. 
It'd make the mycus a more imposing threat in an interesting way. And it would make people think twice about leading tough monsters into mycus mobs to mushroom-ify them if they aren't prepared to clean up afterwards. 
Sure you could weaken a Skeletal Jugg by making it into it's mycus version, but just because it stopped moving doesn't mean the spores aren't a danger anymore. You can pulp the corpses, but the fungus will continue to spread unless its burned.
![The-Last-of-Us™-Remastered_20150405224925-1080x608 1](https://user-images.githubusercontent.com/66659071/89724774-b8d22100-d9dd-11ea-9fa9-078240f97194.jpg)

Also kinda unrelated, but it'd be neat if we could sometimes come across houses and basements littered with black mold. More opportunities to wear environmental protection, is always fun.
