### ISSUE TITLE
Heating water with a pot using the action command

### ISSUE THREAD

**Issue by NotHereCDDA** [CleverRaven/Cataclysm-DDA#42328]
# Is your feature request related to a problem? Please describe.

Heating water with a pot using the action command of the pot doesn't clean the water. I would like it if it did.

# Describe alternatives you've considered
Make it clear that doing so won't make "clean water".

# Additional context
I put this up as a bug at first but since it's not a bug I wanted to suggest it as a feature.

**Comment by Cynthius** [comment]
"Heating" has always been rather unintuitive as a feature since many items (uncooked tv dinner, water) you might assume can be cooked with it since they require no ingredients, just the addition of sufficient heat. The thing is, "heating" in the context of the heating feature is _not_ a cooking process, it's for warming food. You're reheating a pizza or making hot water, not boiling or making anything hot enough to cook. The point is to thaw frozen items so they can be consumed, or heat foods that have a morale bonus when eaten "hot". I think the best solution would just be to rename the menu option to "warm food" or similar.

**Comment by NotHereCDDA** [comment]
Sounds good to me! :D
