### ISSUE TITLE
Vehicle Welding Rigs Cannot Be Crafted at Mechanics 4

### ISSUE THREAD

**Issue by Shinino** [CleverRaven/Cataclysm-DDA#42355]
# Describe the bug

Vehicle Welding Rigs require Mechanics 4 to be crafted.  However, the books the recipe comes in all require Mechanics 5+.  The recipe shows up as uncraftable at Mechanics 4.  

# Steps To Reproduce

1. Have a character with Mechanics 4
2. Have a book with Vehicle Welding Rig recipe (Mechanical Mastery, Electronic Circuit Theory, DIY Compendium, 
Welding and Metallurgy)
3. Enter crafting menu
4. Vehicle Welding Rig does not show in crafting menu, either under any category or when filtering specifically for it.
5. Examining any of the four books shows the recipe in brown, indicating uncraftable.

# Expected behavior

Vehicle Welding Rig should show in a book which raises Mechanics to 4, or be accessible in a book which is understandable at Mechanics 4.

# Screenshots

(Will add later)

# Versions and configuration
0.E-2
(Full report soon)

# Additional context

More of a suggested fix:  Either change the requirement from Mechanics 4 to 5 (as the lowest book with the recipe teaches to Mechanics 5), or either add to a book which teaches to Mechanics 4 (if one exists) or make it usable at Mechanics 4 in the four books listed above.

**Comment by I-am-Erk** [comment]
I'm not sure what the bug here is. Having it at a lower mechanics requirement affects your chance of succeeding at the recipe, for example. It doesn't mean you're able necessarily to follow along with what the book is saying overall.

It might be reasonable to drop the mechanics requirements of some of those books if it's hard to find books at a lower level, but the problem you're listing doesn't inherently seem to be an issue to me.

**Comment by Shinino** [comment]
> I'm not sure what the bug here is. Having it at a lower mechanics requirement affects your chance of succeeding at the recipe, for example. It doesn't mean you're able necessarily to follow along with what the book is saying overall.
> 
> It might be reasonable to drop the mechanics requirements of some of those books if it's hard to find books at a lower level, but the problem you're listing doesn't inherently seem to be an issue to me.

The issue is that you can't actually craft the recipe at the level the item browser (and thus the JSON) says you should be able to, because that recipe doesn't exist in a book that's usable at that level.  It's not 'hard to find books at a lower level', that recipe simply does not exist in any book below Mechanics 5.

**Comment by I-am-Erk** [comment]
Right, I understand what you're saying, I'm just saying I don't agree that is necessarily a bug. If it's hard to get  your mechanics up high enough or there's a paucity of books that cover lower mechanical levels, you could see about dropping one of those books down, but a mechanics 4 recipe not being commonly found in easier books isn't itself inherently a problem.

**Comment by Shinino** [comment]
> Right, I understand what you're saying, I'm just saying I don't agree that is necessarily a bug. If it's hard to get your mechanics up high enough or there's a paucity of books that cover lower mechanical levels, you could see about dropping one of those books down, but a mechanics 4 recipe not being commonly found in easier books isn't itself inherently a problem.

I don't fully agree here -- that's like saying that you won't find, for example, a basic cooking recipe until you get an esoteric text on 14th century cooking.  If you have the skill to craft something, and the recipe is in a book, it stands to reason that it'd be in a book you can use at that skill level.  Again -- I'm absolutely not opposed to Vehicle Welding Rigs going to Mechanics 5 (where the first book with the recipe exists).  I'm not saying that's the -right- answer, just that having the mismatch between Skill Level for the recipe and Skill Level for books where the recipe is found is not ideal.  They should match (across the board).

**Comment by I-am-Erk** [comment]
I think you're missing what I'm saying about what is and isn't a problem.

It's entirely reasonable to adjust the level of a mechanics book containing this recipe, if there aren't enough mechanics books at a lower level.

However, this recipe only being found in higher level mechanics books, but itself not being that high level, isn't itself a problem, it's done intentionally in many places. "They should match (across the board)" is false. Books can contain recipes that are lower level than the book they're in. Among other things, mechanically, that means that once you're at a high enough level to understand the directions, it's a task that has a low chance of failing. It can also be used to represent a book that gives obtuse directions. In the case of a vehicle welding rig and the books listed, for most of those books I'd say the issue is that they're pretty complex books that aren't necessarily written for ease of comprehension (with the exception of DIY compendium, which should not have this recipe at all). For example, a Welding and Metallurgy textbook might contain the things you need to know to build a welding rig, but not an actual design, and in order to get the information on how to actually make the rig from the book, you might need a firmer grasp on principles than the skill level needed to actually make the thing once you have it all figured out.

**Comment by ZaricaDemoni** [comment]
Just putting this here for ease of reference for people wondering.

The Vehicle Welding Rig requires both electric 4, and mechanics 4, with mechanics being the primary skill here.

All books with this blueprint are as follows with required level in mechanics to even use the recipe.

Mechanical Mastery (level 6)
Electronic Circuit Theory (level 8)
DIY Compendium (level 8)
Welding and Metallurgy (level 5) 

Note: I did always find it just a little strange that Electronic Circuit specifically, needed such a high level. given it does use 2 makeshift arc-welders in its fabrication which are learned at a level that is actually backwards, learned much earlier than can be crafted in this case. requiring 2 electronic to make, but can be learned from welding and metallurgy at level 1, which is also backwards for the vehicle welding rig. requiring 1 above base, where as the makeshift arc-welder is 1 below base.

all books with the makeshift arc welder recipe.

Under the Hood (level 3)
Mechanical Mastery (level 2)
Welding and Metallurgy (level 1) 

Final Note: What works works, just always found it odd there was a few things like this that existed and figured I would put this info out there for people wanting to discuss it.

**Comment by Alex-Folts** [comment]
There is mess with recipes, I played few times, get to the point where i had huge array of solar panels and other advanced stuff(i think even had reactor for vehicle) but i never even seen book with recipes for steam engines, I guess at least the most simple one should be available without book, so you can build it before it become completely useless.

**Comment by Shinino** [comment]
Looking at the books, I honestly feel the best way to resolve it is to change the recipe to require Mechanics 5 to match the Welding book -- since that kinda fits.  (And you're right, it does also require Electronics 4).

**Comment by ZaricaDemoni** [comment]
> 
> 
> There is mess with recipes, I played few times, get to the point where i had huge array of solar panels and other advanced stuff(i think even had reactor for vehicle) but i never even seen book with recipes for steam engines, I guess at least the most simple one should be available without book, so you can build it before it become completely useless.

the basic makeshift steam engine requires fabrication 6 to craft properly and can be found in the following books, note this only gives 112 kW  of power as well, so would be a downgrade to your solar panel arrays at that point.

**Comment by Amoebka** [comment]
Why is welding rig such a difficult recipe to begin with? You aren't actually crafting welders, you are merely converting welders you have to run from car battery.

**Comment by kevingranade** [comment]
Not a bug, as Srk outlined, there is no guaranteed correspondence between book skill level and contained recipe skill levels.

**Comment by I-am-Erk** [comment]
I think it should be expanded to say that a careful look into recipe book levels and recipe difficulties is still a fine idea. It's just that this issue in specific isn't a bug.
