### ISSUE TITLE
Picking up joint produces pickup message with incorrect item name - visual bug

### ISSUE THREAD

**Issue by MasterLiKhao** [CleverRaven/Cataclysm-DDA#42410]
Picking up a joint from the floor produces an incorrect pickup message - item chosen seems to depend on inventory, had the game call it a grenade before, and also cash cards with various denominations to it. Visual bug only - joint is added to player inventory correctly.

1. Make player, procure joint somehow. Maybe also have other item(s) in inventory.
2. Drop joint on floor.
3. Pick joint back up and check message log. It will not say "picked up joint(1)", instead using some other item as item name.

Expected behavior

Message log should state "picked up joint(1)" when joint is picked up.

Screenshots

![grafik](https://user-images.githubusercontent.com/68699341/88300982-65d14c00-cd04-11ea-9642-80bd565979d1.png)

Versions and configuration
- Newest experimental build #10863
    
- OS: Windows
    - OS Version: Windows 7
- Game Version: 0.E-4370-g8718a82 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Alternative Map Key [alt_map_key],
    Graphical Overmap [Graphical_Overmap],
    Mutation Changes [Mutation_Changes],
    Stats Through Kills [stats_through_kills]
]

**Comment by mqrause** [comment]
I can't reproduce this. Do you have a save where it happens?

**Comment by Bulletfang** [comment]
I managed to reproduce this bug reliably with soap and leather patches, @mqrause .
It happens only under specific circumstances, but it is very noticable when it happens.

Here it happened naturally to me, as I was searching for leather, then continue to pocket some soap, but the message says 20 leather patches instead of 20 soap bars:
![wrong pickup text 1](https://user-images.githubusercontent.com/45204409/89024905-2dde9000-d326-11ea-8ae1-e690d4419a98.png)

I tried to reproduce it with plastic, so I drop the 20 soap I picked up (I had 70 soap in total), drop the 3 plastic, then pick up the 3 plastic and then the 20 soap and it worked:
![wrong pickup text 2](https://user-images.githubusercontent.com/45204409/89025063-7a29d000-d326-11ea-8fbe-9289547ffa1a.png)

Here is a circumstance under which this bug doesn't trigger: I dropped all 70 of my soap and 5 of my leather, pick up the leather and then the 70 soap and the bug does not appear:
![wrong pickup text 3](https://user-images.githubusercontent.com/45204409/89025201-b3fad680-d326-11ea-9737-a3b5f63e7933.png)

It appears that if the game puts the charges of the soap in brackets behind the soap, it does not trigger the bug, like here I tested it on my debug world that only runs with the dda module, I spawned 20 soap and some leather patches, repeat the steps of picking up the leather first and the soap after and it didn't work (first red square), but when I dropped a single piece of soap it did trigger the bug (second red square):
![wrong pickup text 4](https://user-images.githubusercontent.com/45204409/89025477-3a171d00-d327-11ea-89c1-670f91d5d51c.png)

When you pick up a naturally stack of soap it says: **You pick up 20 soap bars.** (which triggers the bug)
But when you spawn 20 soap with the debug menu it says: **You pick up 20 soap bars (20).** (which does not trigger the bug)
