### ISSUE TITLE
Miscalculation in inventory/multidrop screen volume indicator

### ISSUE THREAD

**Issue by RocketPapaya413** [CleverRaven/Cataclysm-DDA#42465]
# Describe the bug

The volume indicator in the top-right of the inventory/multidrop screens only shows a "used" volume equivalent to the difference between the total volume of a container and the amount of empty space remaining in that container's pockets. This lead to a displayed inventory space of 17.88L/35.90L and being unable to pick anything else up (this type of confusion is a natural outcropping of the pockets system but this massive of a difference was a big clue that something else was going on). When I dropped a 1.32L glass bottle my used volume changed to 17.07L. Upon investigation the bottle has a .75L pocket and contained .25L liquid.

17.88-17.07=.81
1.32-(.75-.25)=.82

I'm assuming there's a rounding error in there somewhere. I tested it out with a few other containers I was holding and the numbers seem to check out.

The indicator in the get screen displays the same used volume as the other screens, but the change in volume when selecting items for pickup is correct.

# Steps To Reproduce

1. Create a random character.
2. Spawn a glass bottle.
3. Spawn a backpack to carry the bottle in.
4. Pick up the glass bottle.
5. Note that used inventory has increased by .57L.

# Expected behavior

At step 5 I would expect the used inventory to increase by 1.32L.

# Screenshots

![drop](https://user-images.githubusercontent.com/50273494/88481680-6a734b80-cf22-11ea-97e5-ce8f30713548.png)
![contents](https://user-images.githubusercontent.com/50273494/88481683-6d6e3c00-cf22-11ea-9e48-21290fb44c32.png)
![alc](https://user-images.githubusercontent.com/50273494/88482460-ee2f3700-cf26-11ea-8425-b991caaf8bad.png)
![3l](https://user-images.githubusercontent.com/50273494/88482535-84635d00-cf27-11ea-9cb2-3d970f95880b.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-4401-gea9b62d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm],
    Cars to Wrecks [cars_to_wrecks],
    Disable NPC Needs [no_npc_food],
    Stats Through Kills [stats_through_kills],
    No Rail Stations [No_Rail_Stations],
    DinoMod [DinoMod],
    Blaze Industries [blazeindustries]
]

# Additional context

**Comment by mqrause** [comment]
This is working as intended. Putting a rigid container in a pocket means the capacity of the rigid container is still usable. The real issue might be not being able to pick things up anymore. Do you have a save of that situation?

The get menu doesn't use the same calculations (for now), since it is very unclear what items you can or can not pick up either way with only total volume and weight displayed.

**Comment by RocketPapaya413** [comment]
> Putting a rigid container in a pocket means the capacity of the rigid container is still usable.

Only in the strictest, most narrow and unhelpful definition of "usable". By which I mean I can think of a few hypothetical situations where someone might use it but in reality we're talking about 20L of unusable space and a misleading interface.

Here is the save I drew the pictures from but I don't think it shows anything else. You can walk around and fail to pick up some small items while the game says you have room. I mean, some shrinkage is expected with the current implementation but thinking my inventory is taking up half as much space is kind of a joke.

It would be helpful and practical to the player to only show empty space in worn storage and occasionally have the pleasant surprise of nesting objects further into inventory and ending up with more space than expected. There would still be some wasted space in holsters and small pockets of course not at this level.

**Comment by RocketPapaya413** [comment]
Another option would be to make an exception for "single item" containers, like holsters and bottles holding liquids, and specify them as only ever being full or empty in terms of inventory volume display. The remaining 3.625 liters in a gallon jug containing 1 unit of bleach is not usable volume.

**Comment by mqrause** [comment]
Yeah, containers only able to hold liquids should probably be excluded. Maybe even all containers with restrictions.

**Comment by kenneth-ellis** [comment]
I came here to report the same issue and found this when searching first.  I agree even if this is "working as intended", it's incredibly confusing for the player.  The Inventory "Volume (L)" display that _used_ to tell a player how much _usable_ volume they had to pick up & store additional items.... is now worse than useless because it's misleading.  My inventory tells me I'm at 14.59 L out of 24.65 L, for example... but when I try to pick up 1 single piece of wire it tells me "not enough capacity to stash wire".

**Comment by anothersimulacrum** [comment]
To what extent is this still an issue after #43047?

**Comment by Squishums** [comment]
Same results.
![image](https://user-images.githubusercontent.com/2533896/99160781-b9ebac00-26b8-11eb-941f-5384b1e4940e.png)

But that's working as intended. Empty glass bottles aren't restricted to liquid, so their volume should be reported in the total.
![image](https://user-images.githubusercontent.com/2533896/99160961-089a4580-26bb-11eb-97fe-2501a5c32d47.png)

**Comment by mqrause** [comment]
> To what extent is this still an issue after #43047?

What I said in the PR:

> Not sure if this would count as a fix, since I don't think there's a way to really fix the issue with just some calculations. You will always have more volume available than you can actually fill.

was referring to the fact that if you have multiple containers with multiple pockets, you'll pretty much never be able to fill all of them completely. And the remaining capacity of all pockets will add up, even though there's hardly any items that could fit in any single pocket you have. The strength of that effect can vary wildly depending on the containers/pockets you have and the things you put in them.

I didn't try it out, yet, but #45377 should fix that mostly, since you see the individual item restrictions (though not for weight).

**Comment by anothersimulacrum** [comment]
Okay, then do you think this is done well enough to close, or is there more that should be done?

**Comment by mqrause** [comment]
Just realized your PR only adds those indicators for the pickup menu. That's definitely the most important place, but it might help to have it in inventory/multidrop, too, so you know your 5l of remaining volume are split up in chunks smaller than 0.3l or whatever.
