### ISSUE TITLE
Issues with Keybinds on QWERTZ Keyboard

### ISSUE THREAD

**Issue by Shudokai** [CleverRaven/Cataclysm-DDA#42519]
# Describe the bug

Many Keybinds were changed recently from the actual input to a combination of modifier and key, which makes them unusable on QWERTZ Keyboards and presumably other Layouts aswell.
Example: ? became shift-/, < and > became shift-, and shift-..

# Steps To Reproduce

Get a QWERTZ Layout Keyboard or the OS Language settings and try to use any of the Keybinds that don't match a QWERTY Layout.

# Expected behavior

The keybinds should be defined by Symbol Input not Keystrokes.

If the game asks for ? to do something it should be whatever combination of keys a keyboard layout needs to produce ? and not a very specific combination of keys.

? would be shift - ß on a QWERTZ Keyboard (impossible for QWERTY since they don't have ß)
? would be shift - / on a QWERTY Keyboard (impossible for QWERTZ since / already needs shift as a modifier)

# Versions and configuration

0.E-4551-geb83022

**Comment by Shudokai** [comment]
Reverted to an older version to find when the issue was introduced.

Build #10875 - July 28, 2020 at 5:51:54 PM +0200

Introduced the problem.

**Comment by Qrox** [comment]
> The keybinds should be defined by Symbol Input not Keystrokes.

That had the problem of letting the system manipulate your input via IMEs, dead keys, caps locks, num locks, etc, sometimes leading to confusion, and that's why it was changed from symbol input to key strokes.

> If the game asks for ? to do something it should be whatever combination of keys a keyboard layout needs to produce ?

In some settings you cannot produce `?` at all. For example, if you have a Chinese IME on and press shift+/ on a qwerty keyboard, you get `？` (the full width question mark) unless you switch the IME or its full-width mode off, which can be cubersome if you want to enter text later on and have to switch it back on.

I think one way to address your problem is to add keybindings specific to each layout in the keybindings file. Another quick way is probably to add a option to disable key stroke input.
