### ISSUE TITLE
Crafting ingredients inaccessible while on stairs.

### ISSUE THREAD

**Issue by elsxf** [CleverRaven/Cataclysm-DDA#42570]
# Describe the bug
items in adjacent tiles are not recognized by the crafting menu while standing on a down stair.
# Steps To Reproduce
drop items/tools to be used in a crafting recipe adjacent to a down stairs tile, and attempt to craft while standing on the down stairs tile.
# Expected behavior
The crafting menu should recognize the items on the adjacent tile and allow you to craft with them.
# Versions and configuration
- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 16.04.6 LTS; Release: 16.04; Codename: xenial; 
- Game Version: 0.E-1 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]
# Additional context
this bug does not prevent unloading/reloading items in adjacent tiles, or prevent the use of items/tools on the downstairs tile, and standing so the down stairs tile is between you and the items does not block the items.

**Comment by Valares** [comment]
This issue is still... well... an issue.

- OS: Windows 7 64-Bit
- Game Version: 0.E-8385-g9504d41 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

However, I can also add a few more information to this.

To specify a statement of the original report: If you stand on top of the stairs, the build menu ignores any items around the players character or on the stairs itself (but not in the characters inventory).
The build menu can access stuff that are on the stairs if the character doesn't stand on the stairs.

I've tested this in different settings and the character is affect by this bug when he stands on the down stairs of (not limited to):
Prison
Subway
Lab
Houses with wooden stairs
Radio tower
Player built wooden stairs

This bug also applies to standing on the top of:
The external **ladder** of a pawn shop
**Downward slope** of mi-go scout tower, crashed airliner and LMOE shelter

However, it does **_not_** affect a character standing on top of a uncovered manhole, as long as it generated a ladder underneath.
But it does affect the character if the ladder could not generate (attempting to go down results in "There is a sheer drop halfway down. Jump?"-prompt) - unless the manhole cover is put back into place or was never lifted.

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.F-6398, see testing in https://github.com/CleverRaven/Cataclysm-DDA/issues/48517#issuecomment-1051003365.
