### ISSUE TITLE
Wooden shovel craft

### ISSUE THREAD

**Issue by Darkenlord1** [CleverRaven/Cataclysm-DDA#42683]
# Describe the bug
Wooden shovel craft requires item, that provides wooden carving, which cannot be crafted with even 4 production or surviving skill

# Steps To Reproduce
Get 2 lvl production skill and try to create wooden shovel

# Expected behavior
Be able to craft that item, maybe on same skills level

# Versions and configuration
- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.E-4796-gda25633 [64-bit]
- Graphics Version: Tiles
- Game Language: Системный язык []
- Mods loaded: [
    Тёмные Дни Впереди [dda],
    Отключить потребности у NPC [no_npc_food],
    Графическая карта [Graphical_Overmap]
]

**Comment by Tamiore** [comment]
There is no "wooden carving" tool quality. 

"wood chiseling" is found on this tool: http://cdda-trunk.chezzo.com/stone_chisel/craft

**Comment by ShadowMiner** [comment]
Yes, sorry about wood carving.
Still a thing that is shovel can be crafted on production 2, but stone chisel is crafted on 4 lvl of survival. Same level or +1 will be better in my opinion.

**Comment by Tamiore** [comment]
Survival is pretty easy to train to lvl 4. (3) vs (4) in it makes little difference.

I mean, I can see your argument in general, but in practice I doubt someone else will make a PR for such trivial matter.

I'd say you've have better luck making *your own* PR to address whatever you think is the issue here.
