### ISSUE TITLE
Mosin (and potentially other non-detachable-mag weapons) bugged; speedloaders do not work

### ISSUE THREAD

**Issue by misterprimus** [CleverRaven/Cataclysm-DDA#42724]
# Describe the bug

Mosin spits out error on firing; can't be reloaded with clip.
Also it seems like I cannot use speedloaders. 
![image](https://user-images.githubusercontent.com/45959491/91937605-455fbe80-ecc0-11ea-930c-464e373870aa.png)

# Steps To Reproduce

1. Make a player with a Mosin, Mosin clip, and some compatible ammo (54mmR).
2. Try to aim at a wall.
3. Fire.

or

1. Make a player with a an L2037 Backup (unloaded) and a LW-5 speedloader (5/5 loaded with .223).
2. Reload the revolver.
3. Fail.

# Expected behavior

I expect no errors and for the clip to be usable as a speedloader, but what I get is an incompatible clip as if it's from a different gun and this error when I fire:
![image](https://user-images.githubusercontent.com/45959491/89373525-ed309f00-d6b6-11ea-8cf6-b6fc44b440ae.png)
Or it just doesn't recognize that I have it.
# Screenshots

Do not take a screenshot of the crashing window. Please provide the crash logs in the "Additional context" -->

# Versions and configuration

 - OS: Win7x64
 - Game Version: 0.E-4851-g7d816ea
 - Graphics version: Tiles
 - Ingame language: Eng
 - Mods loaded: Default NPCs need no food mod.

# Additional context

**Comment by Duck13Tales** [comment]
I noticed that the glock 22 spawn with incompatible ammo even when spawned through debug menu.

**Comment by Hulkninja** [comment]
This has been reported already, and as far as I know, the main contributors to the project are fully aware of the issue.

Guns are apparently the most complex feature in the game, which, considering the large number of types and model variants, the many different types of ammo and magazines, and especially how modifiable they are, seems pretty believable. 

This might be fixed somewhere along the line leading up to the release of 0.F, but don't take my word for it, I'm not in charge here. 

I've just been following this issue, and others similar to it, ever since my Glock decided it wanted ammo it can't fire, and my Mosin was found to be totally useless in the middle of a horde battle.

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/cant-reload-sks/24375/2

**Comment by wapcaplet** [comment]
Confirmed, still occurring in 0.E-5371-g2ea5e2e970

**Comment by misterprimus** [comment]
Also speedloaders seem to not be working anymore. Not sure if I'm just using them wrong? The stripper clip for the Mosin should act like a speedloader. Easy fix: just make it a speedloader, except speedloaders also do not work apparently.

**Comment by misterprimus** [comment]
Update: In most recent version, stripper clip seems to work correctly, but I get errors when firing. And after saving/loading, I get the pocket error and then the gun is totally broken/cannot be reloaded.

**Comment by wapcaplet** [comment]
Related to #42340
