### ISSUE TITLE
Fine tuning of skills for primitive crafting, re stone chopper

### ISSUE THREAD

**Issue by danielkwinsor** [CleverRaven/Cataclysm-DDA#42739]
# Is your feature request related to a problem? Please describe.
The stone chopper's difficulty level seems out of balance.  From my opinion, similar items at fabrication 3 are pretty hard in relation, while items at 1 are the same difficulty.  Once I've learned how to smash rocks into pebbles (fab 0) enough, can't I smash a sharp rock enough to make it sharp on 1 side and hand-held on another?

I'm leaving open the possibility of more fine tuning or more tools.

# Describe the solution you'd like
Decrease stone chopper's fabrication from 3 to 1

# Describe alternatives you've considered
Start characters with higher fabrication / survival, or with basic tools
Introduce even more new recipes
Add cutting 1 to flint aka sharp rock

# Additional context
I am very supportive of https://github.com/CleverRaven/Cataclysm-DDA/pull/41711  I love the idea.  I have a unique play style that most people won't have... start naked in the woods, no tools, no skills, and build from there before I freeze to death.  This was challenging but possible, until this refactor that placed the first cutting tool too far out of reach.  I am not against the changes in 41711, in fact I'd love to see this expanded more, but maybe with some additional skills and qualities relaxing.

Can it be checked whether all the new tools from 41711 are present in game?  I wasn't seeing recipes for the primitive drill and probably others.

**Comment by kevingranade** [comment]
Flaking a rock to a cutting edge isn't a matter of hitting it until it's sharp, it requires a specific kind of rock, specific tools, and specific techniques.
The difficulty of the recipe relative to the outcome is irrelevant, things are intended to be as difficult as they are IRL and as valuable as they are IRL.
Concerning your starting scenario what you need to do is start your character with higher levels of fabrication and now that it's in the game the knapping proficiency because my expected outcone for a Naked and Afraid scenario with a character that doesn't have decent survival skills is that they die. This is not a particularly survivable scenario.

**Comment by danielkwinsor** [comment]
I agree with leaving this closed, and I will also close the PR.  I don't agree with knapping being the only way to bootstrap one's self.  I will try to find a different solution.

The Naked and Afraid scenario was survivable in nearly 100% of my starts prior to this change (excluding the 80% of times I die due to being surrounded by zombies).  I like it, you might try it and form your own opinion.

I smashed a hand sized rock from the backyard between 2 other rocks and retrieved the 3 pieces.  I used the sharpest to "saw" 6 inches of rubber doormat in about 45 seconds.  A dinner knife --butter knife sharpness-- took 10 seconds to do the same length and also took a sawing motion with a serrated tip rather than a nice cut like scissors.
