### ISSUE TITLE
Maple syrup gathering

### ISSUE THREAD

**Issue by Darkenlord1** [CleverRaven/Cataclysm-DDA#42736]
# Describe the bug
Seems like maple syrup not gathering from trees, or maybe very-very slowly, 6 ingame days and there is 0 syrup in bottle.

# Steps To Reproduce
Get drill, get container for liquids, place tap.

# Expected behavior
Get maple syrup maybe after one-two days?

# Versions and configuration
- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.E-4856-ga05e3e8 [64-bit]
- Graphics Version: Tiles
- Game Language: Системный язык []
- Mods loaded: [
    Тёмные Дни Впереди [dda],
    Отключить потребности у NPC [no_npc_food],
    Графическая карта [Graphical_Overmap]
]

**Comment by Maleclypse** [comment]
Are you in the right season for it?

**Comment by Hulkninja** [comment]
>A hollow metal cylinder which is inserted in a tree crust in order to slowly harvest its sap. Can be used on a maple tree in between late winter and early spring to harvest maple sap.

If you're not doing it between the dates of the 11th of winter and the 7th of spring, that's your solution.
It only works during a certain time of the year. Just as in real life, if I'm not misinformed.

**Comment by Darkenlord1** [comment]
Where i can look current season in game?
And, if there is limitations like this, why don't add answer to this action?

**Comment by Hulkninja** [comment]
> Where i can look current season in game?
> And, if there is limitations like this, why don't add answer to this action? Like it can't be harvested right now.

By default, the season should be shown on the right side of your screen in-game. Not sure what exactly it's called officially, but it's the status overview panel. Where you can see the time, your health, status, etc. It will be shown alongside the current day of the season. So it might say something like "Spring 34". Most scenarios start during the spring, again, by default, so if chances are that if you've played for more than 7 in-game days, but less than 281 days, you might have missed your chance for the year.

I guess the reason that nobody added a response when trying to collect maple syrup at the wrong time is because people figured the description already kind of tells you when you can collect the sap, and that this should be enough. But that's just a guess.

**Comment by Darkenlord1** [comment]
![изображение](https://user-images.githubusercontent.com/20936024/89508092-185de000-d7d6-11ea-98ff-554af324451b.png)
![изображение](https://user-images.githubusercontent.com/20936024/89508127-24e23880-d7d6-11ea-9757-39ea384fdb43.png)
When I try to get syrup from tree, game says only this (Last lines in both of screenshots). There is nothing about spring.

**Comment by Hulkninja** [comment]
> ![изображение](https://user-images.githubusercontent.com/20936024/89508092-185de000-d7d6-11ea-98ff-554af324451b.png)
> ![изображение](https://user-images.githubusercontent.com/20936024/89508127-24e23880-d7d6-11ea-9757-39ea384fdb43.png)
> When I try to get syrup from tree, game says only this (Last blue colored lines in both of screenshots). There is nothing about spring.
> And if it is really can be harvested at ~30 days then yes, i cant get it in this year, 73 day.

It's not stated in the action/event log. It's stated in the description of the item. You know, the flavor text you tend to see when inspecting it in the inventory menu..?

Day 73 of what season? The seasons are absolutely vital for this to work. 
Day 73 of spring won't do. Day 73 of summer won't do. Day 73 of autumn won't do. 
The only one that should be allowing you to collect the sap is day 73 of winter, and judging by the lack of snow in your screenshots, I'm guessing you're not currently in day 73 of winter.
