### ISSUE TITLE
Procgen Artifact bug and potential bug

### ISSUE THREAD

**Issue by Maleclypse** [CleverRaven/Cataclysm-DDA#42813]
# Describe the bug

Working on #42791 I spawned in some procgen artifacts.  They all spawned as spoons with different max charges and charges loaded.  Once I picked them up they stacked and reset their charges to zero, so I'm not sure if they stacked to being the same artifact power wise.   I also noticed that I couldn't activate any of them via the activation menu.  I'll keep working through this and add more details.

# Steps To Reproduce

# Expected behavior

# Screenshots

# Versions and configuration

# Additional context

**Comment by KorGgenT** [comment]
the procgen artifacts nowadays are a newer build, so that should help a little bit in the interim. This _is_ a bug and i will not deny that; what i'm pretty sure is going on is they are "display" stacking. meaning you don't lose the charges, but everything will stack together and it'll just show the top of the stack in your inventory. this should be a relatively easy and straightforward fix to update item::stacks_with()
