### ISSUE TITLE
Bow crit rate issues

### ISSUE THREAD

**Issue by souricelle** [CleverRaven/Cataclysm-DDA#42842]
Recent changes to the archery system have revolved around lowering their average damage and greatly boosting their critical damage to simulate the ballistic properties of these weapons IE that lethality is relatively low unless they hit something vital. However due to the way criticals are calculated, self, short, and long bows are incapable of actually landing critical hits and will always deal subpar (~4-24) damage even with aluminum broadheads and an archer with 10 Archery and Marksmanship, while the same character holding a composite bow becomes astonishingly deadly.

We can look at deer hunting to draw some conclusions about how arrows might perform against an unarmored human sized target like a basic zombie:

1) Bow hunters operate by attempting to kill a deer with a single shot, usually to the heart. Wounding shots are highly undesirable and serious hunters try to avoid nonlethal hits at all cost.

2) A draw weight of 40lbs is considered suitable for deer hunting (https://www.bowhunting.com/bowhunt101/much-draw-weight-hunting) and is the legal minimum in many places. It is not unreasonable to assume that a lighter bow would do the job with less consistency and examples exist to support this (https://www.realtree.com/bowhunting/articles/what-to-know-about-low-poundage-bowhunting). The self bow is just under this at 30lbs and the longbow is well over at 60lbs

3) Estimates of wounding rates (a deer being hit and not killed instantly in a single shot) for bow hunters (http://www.seafwa.org/pdfs/articles/Pedersen-31-34.pdf) range from 18% to 50% (https://web.archive.org/web/20060910204949/http://www.sfws.auburn.edu/ditchkoff/PDF%20publications/1998%20-%20SEAFWA.pdf). We can assume a fairly broad range of skill levels for these archers and while their equipment, especially in the first example, skews toward more advanced bows, we have established that kill shots are possible with lighter bows.

With all that said, the fact that a 60 pound longbow is completely incapable of doing critical damage to a zombie irrespective of skill, conditions, or arrow type seems off. 

# Steps To Reproduce

1. Make a player with a longbow and some aluminum broadhead arrows. Set their marksmanship and archery to 10
2. Spawn a zombie.
3. Shoot the zombie. Typical "Good Hit!" shots will do between 6-24 damage. You will never crit.
4. Give yourself a composite bow
5. Spawn a zombie
6. Shoot the zombie. You will frequently crit for >100 damage

# Expected behavior

A 60 pound longbow is not the most impressive weapon but it should be perfectly capable of quickly killing a slow and unarmored man-sized enemy in the hands of a moderately skilled shooter. It was observed in Discord that throwing arrows is often more powerful than shooting them out of one of the lighter bows. On the other hand, a composite bow should not be consistently doing twice the damage of a SCAR-L loaded with 5.56 ammunition. 

The main thrust of this all is that all bows and crossbows should be able to crit, that all of their crit damage should be greatly reduced, and that all of their base damage should be increased. We don't need to be consistently one-shotting zombies with the longbow but at present it (and the basic crossbow) are very underpowered while some of the higher weight bows are very overpowered.

A long bow in the hands of a skilled archer should stand a decent to good chance of quickly eliminating a basic zombie. A composite bow in the same shooter's hands should do better. In neither case should "good hits" be doing 6-24 damage nor criticals doing 120+, especially as this makes both kinds of bows undesirable for hunting. A pulped deer is little better than a wounded and fleeing one.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-4852-gd519083f7b-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

Also tested on:

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-4457-g92af4ff [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    No Fungal Monsters [No_Fungi],
    Stats Through Skills [StatsThroughSkills]
]

# Additional contest

Another consideration here is armor. Multipliers from crits are only applied after armor reduces the base damage, so most arrows aren't really going to be able to damage enemies with any amount of armor. Arrows are much worse than guns at getting through armor but they probably shouldn't be totally worthless just because the dead guy used to be a cop. Raising the base damage for arrows would solve most of this problem. 

Lastly I should add that the longbow's description is possibly outdated. It describes itself as a medieval English longbow, which according to professor google is 80-150 pounds. It also says it can punch through mail armor, which obviously ours isn't doing.

**Comment by kevingranade** [comment]
> due to the way criticals are calculated, self, short, and long bows are incapable of actually landing critical hits and will always deal subpar (~4-24) damage even with aluminum broadheads and an archer with 10 Archery and Marksmanship, while the same character holding a composite bow becomes astonishingly deadly.

This is entirely intentional, it can either reach the vitals and cause absolutely massive damage, or it can't.

> It is not unreasonable to assume that a lighter bow would do the job with less consistency

It is unreasonable.

> examples exist to support this

Your article doesn't say what you seem to think it does. The article is pointing out that modern bows and arrows are far more efficient than older ones, but this is something the current archery balance takes into account as it uses projectile momentum instead of poundage.

> We can assume a fairly broad range of skill levels for these archers

Your study specifically indicates that skill level has a floor due to a hunting proficiency test.

> we have established that kill shots are possible with lighter bows.

You have not.

> It was observed in Discord that throwing arrows is often more powerful than shooting them out of one of the lighter bows.

The throwing system is in need of an extensive overhaul.

> On the other hand, a composite bow should not be consistently doing twice the damage of a SCAR-L loaded with 5.56 ammunition.

This is irrelevant.

> all bows and crossbows should be able to crit,

Against all targets? Definitely not.

> A pulped deer is little better than a wounded and fleeing one.

This is worth looking into. Probably pulping should only look at base damage.

> Multipliers from crits are only applied after armor reduces the base damage, so most arrows aren't really going to be able to damage enemies with any amount of armor.

This is 100% intentional, arrows are notoriously bad at penetrating armor.

> they probably shouldn't be totally worthless just because the dead guy used to be a cop.

If the armor is either epoxy filled or incorporates a trauma plate, it absolutely should. There is some amount if armor power creep since ordinary clothes provide non-negligiblevarmor, but this mostly applies to players and NPCs.

> the longbow's description is possibly outdated.

When I overhauled archery we were in string freeze, a lot of the bow and arrow descriptions should be updated.

**Comment by TheMasterGear** [comment]
As a medieval combat enthusiast, I can tell you that arrows, namely broadhead arrows would do a lot cutting damage compare to guns as it's almost like someone shooting a mini sword at you. The biggest disadvantage about bows and crossbows would be that they're projectiles are much easier to doge, and can be blocked with a shield, heck even parried by a weapon if you're really good. That's because arrow moves only about 150 feet per second, and its speed drops off very quickly after dozen or so yards. They're very slow compared to bullets, the main way they deal damage is because of their mass. I still, would say that broadhead arrow would be good to use against low armored zombies. Using a gun should be for armor targets, range, and more DPS.

**Comment by souricelle** [comment]
@kevingranade 

> You have not.

https://www.archerytalk.com/vb/showthread.php?t=1036227
https://www.thehighroad.org/index.php?threads/thirty-pound-bow-for-white-tail-deer.296004/

https://www.quora.com/Is-a-bow-with-a-draw-weight-of-30lbs-capable-of-killing-a-human

> Is a bow with a draw weight of 30lbs capable of killing a human?
> 
> Let’s assume the arrow is heavy and thus weighs 300 grains which is still a suitable arrow for that kind of bow. Let’s further assume the bow is not that fast and shoots that arrow at 110 fps.
> 
> So that arrow has an energy of merely ~ 10.6 joule.
> 
> Let’s suppose the tip of the arrow is just a sharpened nail. Let’s say it is as blunt as a sheet of paper is thick.
> 
> So around 19.5 grams at 0.01 mm² at a speed of let’s say 100 fps or 30 m/s would result in a pressure of 585 bar or 585 times the air pressure at sea level.
> 
> Let’s assume the arrow has a diameter of a quarter inch. This would still mean that the rest of the arrow is pushed in with 0.184 bar which are still around 2.6 psi.
> 
> It’s kind of obvious that that can do damage which can lead to the death of a human.

Here's a video of a guy one-shotting a 10 point buck with a self bow (a single piece of wood, not composite) and stone arrowheads https://www.youtube.com/watch?v=poRRyxDALe8

Here's another video of a guy using a self bow to bag a deer https://www.youtube.com/watch?v=AvsQYZ6nX-k

Here's a video of a guy using a 35lb self bow on a deer carcass and nearly penetrating through its entire body https://www.youtube.com/watch?v=Y8QaWfRJ5_c

So clearly it's possible to kill a deer (and one can infer, a human) with a single shot from a 35lb self bow. Anecdotal consensus is that it's a bad idea to go hunting with such a bow because they don't fly quite as straight and you need to be within 20 meters which is a tall order when deer hunting but pretty typical when zombie hunting. Our self bow is a little weaker but it should be fine for turkeys and other animals. A 60lb longbow is much more powerful than any of these.

**Comment by Grubleafeater** [comment]
@kevingranade 
> If the armor is either epoxy filled or incorporates a trauma plate, it absolutely should. There is some amount if armor power creep since ordinary clothes provide non-negligiblevarmor, but this mostly applies to players and NPCs.

I'm sorry, what.

Here's the thing, even IF they have that, that would only cover their body.

They have hands, legs, and a face. 



> This is 100% intentional, arrows are notoriously bad at penetrating armor, and if they do penetrate, their effectiveness is massively impaired.

This.....depends entirely on the kind of arrow.

Bodkin arrows, by the way, while designed for piercing armor, and capable of piercing through wrought iron armor(but not steel) are completely worthless for purpose, as they lose more damage than they add AP.



> This is entirely intentional, it can either reach the vitals and cause absolutely massive damage, or it can't.

Here's the thing.

Even if it doesn't reach the vitals, you've still got a arrow lodged in your body. Moving around with it lodged into your body is something that should be causing additional damage.

I don't care who you are, if you have 10 arrows lodged in your legs it is not even physically possible to _walk._

**Comment by GGgatherer** [comment]
> This is entirely intentional, it can either reach the vitals and cause absolutely massive damage, or it can't.

And bullets don't behave the same way because balance?

**Comment by anothersimulacrum** [comment]
No, because nobody has taken a good look at them.

**Comment by TheMasterGear** [comment]
>If the armor is either epoxy filled or incorporates a trauma plate, it absolutely should. There is some amount if armor power creep since ordinary clothes provide non-negligiblevarmor, but this mostly applies to players and NPCs.

You would be surprised what cloth can do. A good example would be to go outside with shorts and go through briers thorns vs wearing sweat pants.

> This.....depends entirely on the kind of arrow.
> 
> Bodkin arrows, by the way, while designed for piercing armor, and capable of piercing through wrought iron armor(but not steel) are completely worthless for purpose, as they lose more damage than they add AP.

https://www.youtube.com/watch?v=Uoz0eggQen8

While this example is flawed due to the chain main armor being crap and the target being locked in place which would make the armor do far worse. However, it still holds up well vs the bolts. The gambeson is no slouch and that's why it was used so much.

https://www.youtube.com/watch?v=eYsr81y0Aeo

Here a video shows that modern weapons vs. old styles can easily bypass chain mail. Still, a few of the older weapons got thought despite the mediocre arrow/ bolt heads.

https://www.youtube.com/watch?v=DBxdTkddHaE

This demonstrates why plate armor is so much better than chain mail. This why I said that plate is so much better.

https://www.youtube.com/watch?v=oksogPN6bAc

Here's a good talk about balancing game armor.

**Comment by TheMasterGear** [comment]
Here a few more armor tests,
https://www.youtube.com/watch?v=XMT6hjwY8NQ
https://www.youtube.com/watch?v=JqkiKjBQe7U

More discussions of arrows
https://www.youtube.com/watch?v=lQABDS0NmtM
https://www.youtube.com/watch?v=McnKrV0aDjo

Here a cool idea for an alternate crossbow
https://www.youtube.com/watch?v=nclNamJWokQ

An awsome gunmod for all bows that I'll be adding into my overhaul mod, the Instant Legolas!
https://www.youtube.com/watch?v=TcDP9jN_FFQ
https://www.youtube.com/watch?v=pOmR0EGUQbQ

Also, why does a 145-pound war bow require inhuman strength to use? The guy in the video I posted could draw a 200-pound bow and easily use a 150-pound bow.

**Comment by souricelle** [comment]
I think that might come down to a discussion of what the strength numbers mean. When I was a teenager and in better shape I tried shooting a basic compound bow and found it incredibly difficult to draw. Archery is very hard, so I don't see strength requirements as unfair. Is 12 strength herculean? 14?

**Comment by TheMasterGear** [comment]
> 
> 
> I think that might come down to a discussion of what the strength numbers mean. When I was a teenager and in better shape I tried shooting a basic compound bow and found it incredibly difficult to draw. Archery is very hard, so I don't see strength requirements as unfair. Is 12 strength herculean? 14?

The wooden great bow in the file says it's a 145 lbs draw and has a 17 strength requirement. The compound great bow has a 120 lb draw and requires 15 strength.

**Comment by souricelle** [comment]
I believe @kevingranade claimed on discord that the wooden great bow is a medieval longbow, which suggests that the strength requirement is too high as people didn't have cybernetics or mutations in the 14th century. The compound greatbow I think is not something that necessarily existed pre-cataclysm.

**Comment by TheJazziestCat** [comment]
> Not all bows and crossbows should be able to crit against all targets

What is the reasoning behind this? How are we determining what bow can crit against what target?

**Comment by TheMasterGear** [comment]
> What is the reasoning behind this? How are we determining what bow can crit against what target?
To my knowledge bows and crossbow and slings would be kinda like halfway between a melee weapons and gun, with higher mass and volume than bullets. This should mean if anything, they would be MORE likely to crit than melee weapons with higher penetration as arrow and bolt hit targets much faster with a smaller surface area. Bullets could very likely hit a non-vital area of a zombie or animal that would also deal far less surrounding damage around the tiny point of impact. However, most bullets should be able to penetrate through bone, and armor much better than arrows and other slow velocity weapons. However, from the videos I linked, broadheads should have no problem cutting through flesh and thick thin and can easily cause cataclysmic damage that should destroy muscles and organs stopping most zombies far easier than guns would. Bobkin arrows would also be useful for penetrating bone, wood, chain mail, kevlar, and hitting between weak points in any plated armor.

**Comment by TheJazziestCat** [comment]
That's good to know, but I'm asking what criteria the devs are currently using to decide whether or not bows "should" crit.

**Comment by TheMasterGear** [comment]
I don't know I'm not a dev, it seems like they don't like the idea of bows doing crit because of "poor armor piercing."
>This is 100% intentional, arrows are notoriously bad at penetrating armor, and if they do penetrate, their effectiveness is massively impaired.

**Comment by TheJazziestCat** [comment]
From what I've heard (and I could be wrong about this), critical multipliers are calculated _after_ armor. So even if bows crit consistently, they still wouldn't do any damage if they couldn't get through the armor.

**Comment by souricelle** [comment]
> What is the reasoning behind this? How are we determining what bow can crit against what target?

The reasoning appears to be whether the weapon can generate the force necessary to put an arrow through an enemy's brain, heart, aorta, lungs etc in a single shot. It's been repeatedly demonstrated that even a 35lb self bow can do this to a deer, so there's no reason it shouldn't be doing significant damage to humans/zombies. I still think the whole argument is flawed - damage is an abstraction, not every shot is a kill or nothing, etc.

**Comment by souricelle** [comment]
The legal minimum for deer in many states is 40lbs as previously stated. To be on the safe side, we can also look at hogs. Many hunters recommend 40-50 lbs for hunting hogs, which are generally more massive than a human. That would rule out the self bow but the long bow and possibly the short bow should still do the job:

https://hoghuntingforbeginners.com/what-is-the-minimum-draw-weight-for-hog-hunting/

As with deer, the objective in hog hunting is to quickly kill the animal with a single shot. That doesn't always happen, but a 40lb bow is considered a reliable tool to kill a 150lb pig in the hands of an experienced archer.

**Comment by mlangsdorf** [comment]
I spawned a hunter with ST 9, Archery 5, Marksmanship 5, a longbow, and a quiver of aluminium broadhead arrows.  I spawned a deer inside a wire fence pence, 6 tiles away, and starting shooting it with precise aim.  Second shot was a critical.  That seems to work as expected: longbows can kill a deer in a single shot.

I replaced the longbow with a shortbow and repeated the process against a dozen deer, loosing 40 arrows at them.  I never got a critical, though I was consistently getting good hits for 14-19 damage.  It always took 3-4 shots to kill the deer.  Even with bleeding, a single shot was never enough to kill the deer.

The shortbow has a 50 lb draw, and should be expected to be able to either kill a deer in a single shot, or wound it badly enough that blood loss will kill it within a minute or less.  We're not reaching that goal.

**Comment by souricelle** [comment]
Is there a particular reason vanilla zombies are more crit resistant than deer? I haven't been able to crit them with anything less than a composite bow in any of my tests. Deer are the same size as or bigger than humans IRL, I can't think of a reason it would be easier to hurt one.

**Comment by Zireael07** [comment]
Zombies don't feel pain and don't bleed, and IIRC the latter has been given as a reasoning, but I'm not sure it's spelled out anywhere.

**Comment by souricelle** [comment]
Zombies do indeed bleed. Pain is not implemented for them but it isn't a factor in calculating base damage and crit rate.

**Comment by kevingranade** [comment]
> The shortbow has a 50 lb draw, and should be expected to be able to either kill a deer in a single shot, or wound it badly enough that blood loss will kill it within a minute or less.

As noted in #37241 and earlier in this issue, we don't use poundage, we use arrow momentum, which is more directly related to penetration ability of arrows.  The bow regulations that make this imprecise statement about necessary poundage are assuming you're going to use a reasonably efficient bow to hunt with and therefore leave it to the hunter to do something appropriately optimal.  I'm using the regulations to reverse-engineer a standard for killing force, so we can't take that at face value, so I attempted to determine what the resulting momentum for a reasonably efficient bow and arrow combination would be and use that as my threshold.

Due to poor efficiency from those short bow limbs and more importantly a short draw, the shortbow does not produce the approximately .4 slug-ft-s of momentum necessary to meet the criteria for reliably taking down a deer.

You can trivially see that you can't use poundage as a criteria by imagining a 50 or even 100lb bow constructed from an extremely suboptimal material like steel or even untillered wood and using a short draw stroke.  The self bow and short bow are explicitly intended to be in this extremely poor efficiency category, which is why they are only suitable for small game.

I wanted to explicitly state the parameters leading to this outcome in the bow definition themselves, i.e. draw length, poundage, and efficiency, but I've been super short on time so haven't had time to do so.

**Comment by souricelle** [comment]
With all due respect, your calculations must be wrong. There's video of people taking deer in this very thread with 35 pound self bows, and many real-life hunters discussing using lighter self bows for deer hunting. These aren't complex recurve or composite bows, they're single pieces of wood (one is even bamboo!) held under tension by a string. They aren't even particularly big bows.

**Comment by mlangsdorf** [comment]
Okay, checking the design notes in `data/json/items/ranged/archery.json`, I do see that shortbow produces 0.35 slugs and the longbow produces 0.41 slugs, so things are working as expected.

I do think the binary nature of that breakpoint is a little unreasonable, given the vagueness of the original data.  Maybe we could enhance bleeding for hits that are accurate enough to potentially achieve a critical hit but fail to meet the HP/10 damage after armor threshold.  In that situation, if the attack does more than HP/20 damage after armor, up the bleeding by one category.  So you shoot a deer with a shortbow, damage it for roughly 1/3rd HP, and then it probably bleeds out over a minute or so.

**Comment by kevingranade** [comment]
There's a big data hole here, which is what should the behavior be on a non-crit.
Here is my sketch of what that looks like based on considering the properties of the wound channel.

Basically we enumerate the properties of each kind of hit.
1. Core hit with good force.
  This is a wound that intersects one or more major vascular organs with enough force to penetrate all the way through the body.
2. Perephial hit with good force.
  This is a through-wound that mostly inflicts damage via raw wound channel. The canonical "flesh wound".
3. Core hit with insufficient force.
  This hits in line with a major vascular organ, but does not penetrate enough.  How much is enough? Canonically for hunting you want a through-wound to maximize bleeding, so there might be multiple tiers of penetration, from through to penetrating organs to not reaching organs.  Currently this is all or nothing, the question is, what are the thresholds for these partial penetrations?
4. Finally a perephial hit with insufficient force.
  This not only fails to intersect a major vascular organ, but also lacks the force necessary to penetrate fully, further limiting bleeding.

**Comment by TheMasterGear** [comment]
> 
> 
> There's a big data hole here, which is what should the behavior be on a non-crit.
> Here is my sketch of what that looks like based on considering the properties of the wound channel.
> 
> Basically we enumerate the properties of each kind of hit.
> 
>     1. Core hit with good force.
>        This is a wound that intersects one or more major vascular organs with enough force to penetrate all the way through the body.
> 
>     2. Perephial hit with good force.
>        This is a through-wound that mostly inflicts damage via raw wound channel. The canonical "flesh wound".
> 
>     3. Core hit with insufficient force.
>        This hits in line with a major vascular organ, but does not penetrate enough.  How much is enough? Canonically for hunting you want a through-wound to maximize bleeding, so there might be multiple tiers of penetration, from through to penetrating organs to not reaching organs.  Currently this is all or nothing, the question is, what are the thresholds for these partial penetrations?
> 
>     4. Finally a perephial hit with insufficient force.
>        This not only fails to intersect a major vascular organ, but also lacks the force necessary to penetrate fully, further limiting bleeding.

Then what constitutes a crit then? Hitting someone's brain or spine?

**Comment by EvgenijM86** [comment]
The current system is bugged. You cannot land any crits at all with 10 rifle & 10 marksman skill if you raise zombie health with "Monster resilience" world setting. It is silly that melee weapons do the same average damage per turn while ranged average damage per turn is nerfed if you raise "Monster resilience".

**Comment by kevingranade** [comment]
Don't change zombie health then. We don't guarantee balance works if you use non-default settings.

**Comment by EvgenijM86** [comment]
If that was intended it should at least be mention in the setting description, that if you increase it you will not be able to make a crit against a creature with ranged weapons, but still be able to do the same crit with melee weapons.

**Comment by TheJazziestCat** [comment]
The monster resilience setting is neither the point nor the issue here. The issue is that the nature of critical hits right now is poorly defined and even more poorly implemented. The base damage/critical damage change paired with the new damage-threshold mechanic for ranged crits causes an unrealistic dropoff where some bows are simply incapable of scoring critical hits. A bow that just barely meets the threshold becomes ten times as effective as a bow that just barely falls short of it, even if the base damage only differs by a single point.

And even that's secondary to the fact that the data here is just plain wrong. As Souricelle mentioned earlier, there is plenty of evidence even in this thread that things like a 35-lb self bow are entirely capable of taking down a deer in a single shot. You can argue that a bow like that can't "reliably" do so, but whether or not that's true, the bows in the game right now can't do that _at all._

**Comment by EvgenijM86** [comment]
I think the main problem is that hitpoints are treated as some sort of armor. Hitpoints were never meant for reducing incoming damage - they are simply a measure of how much damage you can take. But for ranged weapons they act as some sort of helmet that hides any weaknesses in your body, if you have more than a certain amount of them.

**Comment by Bdole1454** [comment]
I'll give my two cents and say i think a lot of the problem here could be solved by either being more permissive with minimums necessary to crit, or differentiating crits into core-organs and headshots. It makes sense that a low weight self bow isn't going to be able to land reliable kill, or even high damage, shots against human size targets. I don't think it makes sense, or feels good, for these bows to *never* be able to land a meaningful hit. If you shot someone in the face with one of these it would do serious damage even if it didn't kill them outright.

I do think it makes sense that low weight and primitive bows should be much more inconsistent, and less effective overall, than modern, high-force bows, but extending the ability to land inconsistent crits would go a long way to addressing the perceived 'uselessness' imo. Thats just my two cents though
