### ISSUE TITLE
Translation extraction script creates incorrect entries

### ISSUE THREAD

**Issue by CountAlex** [CleverRaven/Cataclysm-DDA#42901]
# Describe the bug
I see two incorrect entries foк translation in Transofex master file, namely just `o` and `g` entries that shouldn't be there as they don't represent actual line to be translated.

# Steps To Reproduce
Check transifex `master` file and find lines 25665-25966
See `o` and `g` entries

# Expected behavior
Python script not extracting invalid entries for translation

# Versions and configuration
N/A

# Additional context
I was adviced to create this issue after some discission on Discord. 
@anothersimulacrum pointed that line
`"mag_glam": { "skill_level": 5 }, "cookbook_liverforkids":`
is what causing the problem.

**Comment by anothersimulacrum** [comment]
This is because of this bit of code in lang/extract_json_strings.py:
https://github.com/CleverRaven/Cataclysm-DDA/blob/478ced98fd31acbaef7dd6903d31572a562bbebd/lang/extract_json_strings.py#L585-L588

It's expecting it to always be an array, but after #42475 it doesn't always have to be one. In fact, this code to extract a translatable string here hasn't been working for years because that feature didn't exist, and the above PR brings it back.
So, this needs to be taught to ignore it when it's an array of objects instead of an array of arrays, and read it correctly when it's an array of objects.

Here's the full problematic entry:
`"book_learn": { "mag_glam": { "skill_level": 5 }, "cookbook_liverforkids": { "skill_level": 5, "recipe_name": "Buttery Duck Bites" } }`, the `recipe_name` is  what we want to translate.
