### ISSUE TITLE
Poison being directly lethal, completely non-interactive. 

### ISSUE THREAD

**Issue by Tamiore** [CleverRaven/Cataclysm-DDA#42904]
# Describe the bug

If a character gets enough poison stacks,  damage to the head just keeps being dealt until said charter dies from head "breaking".
And there are just sooo many things wrong with this.
Since there isn't really a way to treat poisoning, this is completely non-interactive. Literally nothing a player can reasonably do will prevent the character from dying. At this point, it would be better to just outright kill the character on the spot, instead of forcing player into hours (potentially) of "dead-end" game-play.
Direct damage also completely overshadows potentially interesting challenge of having to survive for a few days while severely weakened.

# Steps To Reproduce

Get enough poison stacks (by breathing gas from bloated zombie or something).
Wait and see.

# Expected behavior

Poison should progressively weaken the character, but shouldn't deal lethal damage to critical limbs (head and torso) **directly**. Within the current system, simply disabling damage (while keeping the pain) already leads (progressively, over several hours)  to -40% or more pain speed reduction, 0 focus, huge stat penalties, etc, etc. Maybe also add extra fatigue accumulation over time, large health penalty, etc. Maybe keep the damage initially, but prevent it from directly bringing the limb below 10 HP or so.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-4997-gaf19ae1 [32-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Slots [cbm_slots]
]

**Comment by Michael1993** [comment]
How long have your character stayed in a poisonous area to gain so much poison stacks?
It seems fairly straightforward (to me) that if you breathe a lot of poisonous gases in a relatively short amount of time, that could kill you.

**But** I do agree that poison could be made more fun/interactive. E.g.: different poison types, antidotes, etc.

**Comment by Tamiore** [comment]
> How long have your character stayed in a poisonous area to gain so much poison stacks?
No clear. 
My character was sleeping outside (under a free in the forest). Then he woke up already poisoned, with no poison source in sight. Presumably, bloated zombie wondered nearby and exploded. Somehow the sound didn't wake the character up. So however long it took for poison to dissipate under open sky.

**Comment by Michael1993** [comment]
> My character was sleeping outside (under a free in the forest). 

Maybe [a spider bit you](https://cddawiki.chezzo.com/cdda_wiki/index.php?title=Giant_black_widow)? 🤔 That's a stronger venom and entirely silent.

> For some types of poison, yes. 

My understanding is that there are currently food poisoning and general poisoning in the game. Perhaps there could be more poison/venom types (e.g.: spider venom, snake venom, etc.)? Then, they could have specific effects on the player (e.g.: one knocks you out, one pains you, one makes you delirious, etc.).

**Comment by Tamiore** [comment]
> Maybe a spider bit you? 🤔

Maybe. ¯\_(ツ)_/¯

> Then, they could have specific effects on the player (e.g.: one knocks you out, one pains you, one makes you delirious, etc.).

Aure, that would definitely be good to have. However, my point *right now* is that having poison that slowly but inevitably you with no reasonable way to treat it is really bad for gameplay, while not really being any more or less "realistic" than a poison than debilitates heavily without killing directly.

**Comment by BQurious** [comment]
iirc, royal jelly clears poisoning... and everything else. It's incredibly rare, though.
Isn't it kinda like this with early game infections and radiation? Although with a better chance of finding something to prevent an otherwise inevitable death.
If you had gone to sleep in an irradiated tile, wouldn't this be the same result?
Would a vet carry antidotes?

**Comment by Michael1993** [comment]
> Would a vet carry antidotes?

Hey, that's a really good question! I think it would make sense and I even remember recently finding a veterinary book in the game... It currently had no real uses but perhaps it could have antidote recipes?

**Comment by Tamiore** [comment]
>iirc, royal jelly clears poisoning... and everything else. It's incredibly rare, though.

It was patched to be just normal food quite some time ago.

>Isn't it kinda like this with early game infections and radiation? 

Not really, no.
Infections are rather interactive: you get a period to try and disinfect the bite, then you get another period to try and find antibiotics. 
Radiation almost never happens "randomly". I.e. you have to go into an irradiated area and stay there. While a poison source can happen rather randomly (go into a house and run into bloated zombie as you open a door from one room into the other). Or, indeed, a poison source can find YOU.

**Comment by Michael1993** [comment]
I had a short talk with a doctor and she said that:
 - Wasps, bees, spiders and snakes have a lot of different venoms?
 - You are supposed to treat bee/wasp stings with adrenaline...?
 - What about allergies and other animal-borne diseases/ailments?

**Comment by int-ua** [comment]
The experience that is described in the first post sounds like an implementation of rabies. Once you have symptoms you are dead in a week or so and it's even more terrifying when you read what the symptoms are. I don't agree with making poison less damaging as it is _poison_ after all. But maybe removing poison effect after some time has passed is indeed broken? Please test with looking at debug levels.

I've had one game where I slept the first night at an irradiated point and then barely made it out alive, spending all healing items I could find on head and torso just to keep them on last points. IIRC, all my limbs were in broken state and I had to use a car just to get around for a week or so in game. That was a really interesting challenge.

**Comment by Tamiore** [comment]
>The experience that is described in the first post sounds like an implementation of rabies. Once you have symptoms you are dead in a week or so and it's even more terrifying when you read what the symptoms are.

I don't see what purpose this kind of mechanic would serve in single player procedurally generated video-game. Practically no one is going to get terrified. Players with simply end up frustrated by the fact their character is killed in a completely arbitrary and non-interactive matter. An "interesting challenge" is only a challenge when you can influence the outcome.

>I don't agree with making poison less damaging as it is poison after all. 

Not all poisons directly destroy tissue. And, again, it's not a question of plausibility of existence of airborne poison that slowly, but inevitably kills the victim. It's a question of game-play desirability of such poison. What's the gameplay benefit of it being directly lethal over being debilitating and long-lasting, but still technically survivable?

**Comment by int-ua** [comment]
> Not all poisons directly destroy tissue.

Yes, I agree with you here, but IIRC there is no other way that is implemented right now to make poison lethal. I agree that damaging body part is not a realistic representation, but someone has to actually implement a better system. Can you do it? Just adding antidotes to the game sounds good to me too.

**Comment by souricelle** [comment]
The game definitely needs poison treatments. You can kind of fake it with bandages and antiseptic on the head or repair nanobots but neither of those make sense and the first one doesn't work very well.

**Comment by Tamiore** [comment]
>Yes, I agree with you here, but IIRC there is no other way that is implemented right now to make poison lethal. 

But why does it have to be "lethal" by itself? Even simply periodically rendering victim unconscious seems like way more fun of a game mechanic than being outright lethal.

>I agree that damaging body part is not a realistic representation, but someone has to actually implement a better system.

A good start would be to set HP threshold a limb can not go below directly due to poison. 10 HP or something.

**Comment by souricelle** [comment]
I had the idea to make acid more realistic which would require making it have a nonstandard poison effect for acidosis. Poisons could follow Erk's model (https://github.com/CleverRaven/Cataclysm-DDA/issues/35748) and have a list of pre-baked symptoms and severities (blindness, pain, breathing trouble, numbness, tissue damage, blood problems, individual cures etc) and become much more interesting. But that's a huge project and a basic antidote item would be a good stopgap.

**Comment by BQurious** [comment]
**Stone cold Info:**
Coincidentally, I just had an allied NPC go deep in a poison cloud for a few minutes (because the path she chose to try and find a way out was a dead end). I proceeded to watch her slowly get the life sucked out of her. (ultimately she was cured by me before death using royal jelly that I had on hand, in the stable release) The NPC in question took about 3 game hours from full HP to near dead.

There is already a paralyzing poison in the code (currently only used by few monsters), so this poison is not a neurotoxin, it is indeed intended to be the type that damages tissue.

some related stuff I dug up:
#40629 (May 2017, went stale with no apparent action/conclusion)
https://discourse.cataclysmdda.org/t/so-i-have-a-problem-badly-poisoned-isnt-going-away/22156/11 (Dec 2019)
https://discourse.cataclysmdda.org/t/poison-persists-for-too-long/20378 (June 2019)
Some more topics about poison on discord, but they are very old. Probably went stale too

Many effects do not have a max_duration; notably gases. Camping in tear gas or smoke for too long will lead to a sure death, even well after exiting the gas cloud(s)

**Opinions:**
I kind of agree with OP. I think when poison is _that_ severe it should either kill faster, or have more ways to heal out of it. This may be realistic, but that long for a sure death is bad for gameplay imo. Especially since the only cures, being cure-alls, (royal jelly, panacea, that stem-cell thing from hospitals iirc?) have now been removed.

The greatest stories come out of the most miserable circumstances, but there needs to be a possibility of survival, however small or with whatever great cost. Would stabbing yourself with several med serums to get immune/resistant work?
If you get severely poisoned and will most likely die, would lab dives be a plausible strategy? Or would that certainly be "died trying"?

**Things I can do about it:**
 - Adding an antidote as instant magic fix for poison would be easy (Oxygen was considered to be made into an antidote at some point, but since venomous bites also use this poison effect, that would not be appropriate)
 - More monsters could use the paralyzing poison instead if the tissue damaging one. Most (if not all?) insects and spiders IRL use paralyzing poisons, eventually leading to death in other ways. idk how the blob may change this though. (Paralysis may make them _more_ dangerous early game)
 - Said gas effects could have a max duration parameter added and/or have scaling intensity. (No slow, gradual, grueling death)

Those are json-only options, and I shouldn't take much time for those.

Things that would probably be better, but I can't do alone:
Slow acting antidote (like painkillers) or antidotes that work with the remaining duration

**Comment by Tamiore** [comment]
The main requirement for antidotes of any kind is that they should be obtainable (direct or via crafting) from/near the poison source itself, or from naturally-occurring components. 
Otherwise their existence is meaningless.

**Comment by jbytheway** [comment]
Autodocs could get a poison treatment function (maybe they do already?).

**Comment by Tamiore** [comment]
>Autodocs could get a poison treatment function (maybe they do already?).

Autodocs are specialized surgery machines. It makes rather little sense for them to be equipped (by default) with antidotes of any kind. 
Or, rather, toxicology treatments would be quite very low on the list of functions you would expect to find in an autodock. 
And it we make autodocks into general-purpose-heal-them-all machines (with all the expected functions up to and including toxicology), that would be a problem for game-balance in and off itself.

**Comment by BQurious** [comment]
> The main requirement for antidotes of any kind is that at least some of them should be obtainable (directly or via crafting) from/near the poison source itself, or from naturally-occurring components.
For some reason I thought I implied adding them to doc/hospital/vet item groups.. that's json too...

**Comment by Tamiore** [comment]
>For some reason I thought I implied adding them to doc/hospital/vet item groups.. that's json too...

If we assume that a player has access to such resource-rich locations and means to loot them (without being killed in the process), poison is already a non-issue since you can just find a gas mask of some sort instead.

**Comment by BQurious** [comment]
I think you got bitten by a forest spider, and not gassed by a bloater. And
would you wear a gas mask to sleep? It's poison, isn't it supposed to kill
the unprepared? The rush of the early game player frantically looking for
an antidote is the whole point, no?

**Comment by Tamiore** [comment]
>I think you got bitten by a forest spider, and not gassed by a bloater. 

Damage-dealing bite would have woken my character up.

>And would you wear a gas mask to sleep?

Absolute yes. Why would you ever NOT wear one to sleep if you have it?

> It's poison, isn't it supposed to kill the unprepared?

Like practically everything else in the game...

>The rush of the early game player frantically looking for an antidote is the whole point, no?

And for that to work antidote should be either be always potentially available nearby OR the poison shouldn't directly kill.
Otherwise the "search for antidote" will not be plausible unless you just happen to get poisoned next to a  doc/hospital/vet.

**Comment by kevingranade** [comment]
This is potentially a bug.
> Presumably, bloated zombie wondered nearby and exploded. Somehow the sound didn't wake the character up.

None of the rest is.

**Comment by Tamiore** [comment]
>None of the rest is.

I guess the real question here is: 
Is no-antidote (besides super-rare panacea and the like) slow-acting directly-lethal poison actually a desirable thing?

**Comment by kevingranade** [comment]
An antidote is not *necessary* for the poison effect to exist.
An antidote, if present, should not be constrained to appear near the source of the poison, it should simply exist where it makes sense to exist.
I wouldn't complain about stacking poison effects causing more damage per turns so that the window where you are suffering from the effect is reduced, especially as this better mirrors how poisons act IRL, a larger dose of poison has more severe effects, not just a longer duration.  However I would not call this a bug, poisons work like they work,  they can kill in seconds or hours, and they can be invariably fatal or have a chance of killing.

**Comment by Stretop** [comment]
Well, if we are talking IRL here
> An antidote is not necessary for the poison effect to exist.
While that is nominally true, there is only so much ways for a venom to break a living organism. Most popular are neural/muscular overstimulation (causing spasms), neural/muscular inhibition (causing cessation of breath) and necrosis induction (causing damage to tissues and renal failure as a result). And the last one is the rarest of the three among predators.

Even when you do not have a direct antidote for the venom itself - for each of those there are symptomatic treatments: antispasmodics for spasms, stimulants for inhibitive venoms, and debridement/anti-inflammatory drugs/antibiotics for necrotoxins. And all those can be found in pretty much any hospital.

> poisons work like they work, they can kill in seconds or hours, and they can be invariably fatal or have a chance of killing
Err, no, that's not how this works. There is no such thing as an "invariably fatal" venom. What kills you is not venom - it is systemic failure. If you are fast enough and know what to use - you can keep your body more or less working for as long as it is needed for your liver to detoxify the venom.

So if you are really aiming for that "realism" thingy - a more realistic model would be to have stacks of poison cause progressively worse conditions like nausea, vomiting, muscle weakness, body temperature drop (if you are still warm-blooded), losing consciousness... Or maybe the opposite: muscle spasms, pain, body temperature rise - depending on the venom is question. Or - for necrotoxins - damage to the bodypart thus poisoned, bleeding and high risk of infection. And then _those conditions_ (over certain threshold) should prove lethal (much like drug overdose).

This way between the usual "walk it off" and "you are so, so dead" there should still be a sweet zone, where you can beat the poison over time with deft usage of symptomatic treatments, but if you are unprepared - you still die. If an infected bite is like a sprint - a poisoned bite would be more like a marathon.
