### ISSUE TITLE
NPC followers are blind after waking up from sleep

### ISSUE THREAD

**Issue by Leebears** [CleverRaven/Cataclysm-DDA#43079]
# Describe the bug

After going to sleep and waking up naturally or through the dialogue option, NPC followers appear to be blind.  If you are not in an adjacent tile, their icon will indicate they don't see you, the "V" menu lists them as "unaware of your presence", and they will not move to engage visible enemies.  If you are fighting an enemy that is not adjacent to them, they will make comments about hearing things like "that sounds bad", etc.  They will no longer make comments about spotting distant enemies.  Looking at their character screens shows nothing out of the ordinary.

# Steps To Reproduce
1. Recruit an NPC follower
2. Wait for them to fall asleep
3. Wait for them to wake up or tell them to wake up via "C"hat command
4. They are now apparently blind.

# Expected behavior

Followers shouldn't be blinded by sleeping.

# Screenshots

# Versions and configuration
OS: Windows 10
Game Version: 0.E-4878-gf4440a4 
Ingame Language: English
Mods loaded: disable npc needs,  sees-player-icon-retrodays

# Additional context

I was able to do a workaround by crafting blindfolds, telling follower "I want you to use this item" and selecting the blindfold, then removing said blindfold through the "sort armor" menu for followers.  This seems to make them see again until the next time they go to sleep.

**Comment by eilaattwood** [comment]
Also they seem to stop searching for beds to sleep on.

**Comment by MrSamsa** [comment]
That was clever to use blindfolds like that, I just save&quit then reload and they work fine again.

**Comment by RadHazard** [comment]
As mentioned on #45470, I'm still seeing this issue in a recent version (specifically 0.E-8924-gc4efd9e7e7)

I'm not by any means certain, but I think what might be happening is that the NPC's vision range is actually getting out-of-sync with the NPC rather than them just going blind. The reason I suspect this might be the case is that I've occasionally witnessed my NPC do really weird things -- she'll start chasing a corpse three map tiles away to pulp it, or she'll run away try to engage off-screen enemies when posted on guard duty.  Saving and reloading makes her act as expected again, so the issue is likely either the same or related.
