### ISSUE TITLE
Art oriented wrong and door two different tile art on cars showing up randomly

### ISSUE THREAD

**Issue by UndeadMoose** [CleverRaven/Cataclysm-DDA#43115]
# Describe the bug

Playing Ultica I have noticed on certain angles the art for doors will be oriented wrong. As well randomly two different pieces of art for doors on cars will show up. This happens as well if I load a game and my car will suddenly have a hatch as art instead of the normal door art.

# Steps To Reproduce

1. Play the game using Ultica

# Expected behavior

Tile art parts on a vehicle should be oriented correctly at their respective angles and doors shouldn't have random tile art.

# Screenshots

![Screenshot (2845)](https://user-images.githubusercontent.com/56947231/90947013-6e38b600-e46d-11ea-862f-d891157776cb.png)

![Screenshot (2844)](https://user-images.githubusercontent.com/56947231/90947017-7133a680-e46d-11ea-9168-4d58c5210700.png)

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.E-5282-gc2e5682
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: None

# Additional context

I already filed a report in Ultica reports was told to report these issues here as well because this could be happening due to game bugs.

**Comment by wapcaplet** [comment]
Confirmed, still reproducible in 0.E-7041-gdbd1378fa. The right passenger door in many vehicles is often affected, in every orientation while driving:

![image](https://user-images.githubusercontent.com/238395/97082646-7f668600-15c8-11eb-8532-56dda5e89db5.png)

![image](https://user-images.githubusercontent.com/238395/97082652-8ab9b180-15c8-11eb-8a7e-4dcd8630f8f7.png)

The door part in the vehicle menu is indicated by a `T` instead of the angled symbol used for other doors:

![image](https://user-images.githubusercontent.com/238395/97082641-6d84e300-15c8-11eb-91a7-5ee52719b74d.png)

**Comment by Night-Pryanik** [comment]
Can't confirm on 0.F-10973.
