### ISSUE TITLE
Tool belt item draw clones the item.

### ISSUE THREAD

**Issue by Uesrnme** [CleverRaven/Cataclysm-DDA#43174]
# Describe the bug

Tool belt item draw clones item it contains to player inventory, original item remains in tool belt pocket.

# Steps To Reproduce
1.  Insert an item into tool belt.
2. Drop the tool belt.
3. Apply the tool belt from the ground, select "Draw tool or blade" option.
4. An item appears in player inventory, tool belt  still contains the item.

**Comment by wapcaplet** [comment]
Still reproducible in 0.E-5926-g a883429bdd

**Comment by kenneth-ellis** [comment]
I'm able to reproduce a similar issue with a bow sling:

1. Put a bow into a bow sling.
2. Drop the bow sling on the ground.
3. Wear the bow sling from the ground -- select the "draw from bow sling" option.
4. See that you have a bow in hand, but also a duplicate one in the bow sling.

Thanks to @wapcaplet for helping me find this issue to add to rather than opening a separate one, since they seem related.

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/weapon-containers-can-be-used-to-clone-weapons-and-rock-forge-doesnt-use-coal/24781/2

**Comment by RoyBerube** [comment]
Have been looking into this. It can be fixed by allowing the activation to happen in place without requiring the player to pickup the item. It also has the side effect of making the use of sheaths not in inventory less annoying. Only one prompt. I'm not confident that this is the best way to approach it; there may be unintended side effects.

On the original issue: the problem starts when the item being activated has to be wielded because of lack of inventory space. With enough inventory space there is no problem.

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/bug-exploit-carrying-long-objects-inside-inappropriate-containers-object-cloning/25253/2
