### ISSUE TITLE
Zombies hulks are patheticaly weak, despite breaking down doors, bashing people tens of feet, and other feats of strength

### ISSUE THREAD

**Issue by Relyksboa** [CleverRaven/Cataclysm-DDA#43266]
# Is your feature request related to a problem? Please describe.
Zombies hulks are described as “A human body now swollen to the size of six men, with arms as wide as a trash can.”, yet they only deal a measly 4d8 damage, which is quite weak as at best it does 32 damage, which isn't even half of a standard survivor's 80-ish health points.

# Describe the solution you'd like
put simply, they should do a lot more damage. their base and smash attacks should be heavily increased to perhaps even one shot you if they hit your head as a blow like that is essentially being hit by a bowling ball from a third story building.

# Describe alternatives you've considered
You could not increase the damage and maintain the wimpy hulk, or increase it to around a 50 to 60 maximum damage to while so while it still is deadly, it wouldn't one shot people with base health.

**Comment by EvgenijM86** [comment]
Having huge muscles does not necessarily mean that you are very fast. Your blow may have a lot of force behind it but not very fast, and thus you will just send you target flying instead of him absorbing all that force. But if there like a concrete wall behind him he will absorb most of that force. Or you have to attack in very special way, like by placing your fist high up and smashing down, so that ground acts like a wall in example above. But that kind of attack is probably easier to evade.

**Comment by Relyksboa** [comment]
@EvgenijM86 the zombie hulk's speed is 130, that implies that it is 30 percent faster than the player. the weight of the creature doesn't seem to impede it at all.

**Comment by Zireael07** [comment]
40% of a standard survivor's health is dangerous and very strong, though.

**Comment by Relyksboa** [comment]
@Zireael07 note, that is the damage at best. in practice it has an average of 18 damage.

**Comment by GGgatherer** [comment]
In a roguelike, you don't judge something by average damage, you judge it by the worst possible case, i.e. max damage.

**Comment by Tamiore** [comment]
@Relyksboa 
So, under what circumstances to you expect to be hit by hulk just **once**..?

If your character has already closed into MELEE range with a zombie hulk, clearly either:
- things are already "not going your way", and after the first hit you've get a ton of PAIN, that will slow your down and pretty much insure Mr. hulk will get all the chances it needs to finish what it started
or 
- you actually know what you are doing, in which case simply increasing huk's base damage will not change too much, if anything (because the first thing about "knowing what you are doing" is "don't go into melee with things you can't take a hit from)

More broadly, base melee damage practically never makes or breaks a fight with a "deep red" monster. The real deal are special attacks (flaming eyes, shockers, acid dudes, etc) and your (in)ability to kite/outrun the enemy (looking at your, Spearcat hunter) .

**Comment by SirPendrak** [comment]
I believie that "slam" attack it can perform every few turns has its damage depending on its damage dice but then multiplayed by some number so its stronger. But i do agree that it could be just a little bit more damaging with regular attacks. 
Like, 8 or 10 str survivor with unarmed lvled to max lvl and certain tehniques can deal more damage with his fists, despite being infant-size relative to hulk. And currently its too easy in endgame to armor up so hard that youre hulk immunue, where you can be a living tennis ball that crushes nerarby walls and shit. 
Since hulks dont spawn day 1 in normal places anymore, and you can kill them even with just 9mm pistol, they could use a buff so theyre harder to melee. Right now for example starting firefighter with his axe and basic stats and skills can sometimes win melee fight with hulk if using terrain right. 
Beating hulk in unarmed boxing duel should be next to impossible, only reserved for bionic mutants masters, or using heavy duty melee weapons.

**Comment by Amoebka** [comment]
As a reminder, not every player character has 80 max hp, not every player character has bash armor, and not every character can wear heavy survivor suit (or torso/head armor at all).

A single monster not being threatening enough to a minmaxed lategame character isn't exactly a problem. "Lucky" oneshots are certainly not a good game mechanic for a roguelike.
