### ISSUE TITLE
Bone Seer NPC is too strong for an easy quest

### ISSUE THREAD

**Issue by acepleiades** [CleverRaven/Cataclysm-DDA#43400]
# Is your feature request related to a problem? Please describe.
The Bone Seer NPC is very strong. She has skill level 9 in bashing weapons, 8 in cutting weapons, **10** in dodging and 4 in melee. and a top-tier bashing weapon with reach attacks (war flail). She also has great traits for combat. This NPC can dispatch a zombie hulk by herself without much issue (the flail's sweep attack tends to stunlock them). At the same time, the quest to recruit her is very easy: give her 8 bones. 8 bones are not very difficult to acquire, and the recruitment is also guaranteed, so if you find this NPC early in the game (this happened to me), you got a bodyguard that will carry you to the late game for very cheap!

# Describe the solution you'd like
A harder quest would be expected to recruit such a strong character. Bones are not very difficult to get, so in order to have the quest unchanged, the easiest solution would be reducing the Bone Seer's stats and giving her a weaker weapon.
My suggested stats:
Bashing weapons: 4
Cutting weapons: 2
Dodging: 2
Melee: 2

Equipment: Peasant flail instead of war flail. Her characteristic occult bone armor should probably stay, as it is characteristic.

Even this might be pretty strong for 8 bones, but that would be fine because seeing this NPC appears to be uncommon.

# Describe alternatives you've considered
A harder to implement alternative would be to change the quest, making it much fitting for recruiting such a strong NPC. I have never developed quests, so I can not describe exactly what should be done in this situation.

# Additional information
![bone seer](https://user-images.githubusercontent.com/69649956/91993882-4f0f1380-ed0c-11ea-85c1-9fa4bcd410a1.png)

**Comment by SirPiecemaker** [comment]
Hey - thanks for letting me know about this.

So, last week I actually made a large update for Brigitte which did adjust her stats a bit, not sure if you worked with those. Furthermore, her stats are a radius, meaning there is a range that gets randomly generated. You appear to have gotten good RNG, making her stats quite above the normal average.

I stand by the flail though. I really like the flail on her >:C

She is indeed uncommon, as she is a 20% spawn chance in a building that isn't all that common.

All that being said, that does give me an idea how to make her quest more interesting and less trivial, but I'll have to go and add some stuff, which means stopping procrastinating and getting around to it. Still, probably shouldn't be too hard. Thanks for your feedback!

**Comment by acepleiades** [comment]
I'm glad to hear you're working on it. If the player would make the war flail, the materials would be easy to get, but the tools, skill, and recipe required are very time-consuming. It's a top-tier melee weapon. How did Brigitte get such a weapon? She doesn't have the skills to make it herself.

As for the RNG, this was the first town I explored, and there were 2 of those buildings. I don't know if I got extremely lucky or what, but I don't think 10 in any skill should be in that radius. I hope the adjustments have addressed this.

Thank you.

**Comment by wapcaplet** [comment]
One of my past characters had some great adventures with Brigitte (back before 0.E when she still had survivor gear and more frequent spawns). Being overpowered made her both a blessing and a curse. She saved my character's life in more than a few fights, but I allowed her to lead me into situations I would never have attempted without her by my side, and the more often we won, the less careful I became, until I foolishly followed her into a mansion, got into a melee with a gasoline zombie, and then it was all over. Definitely one of my most fun and memorable runs to date!

While I agree she is still a little too overpowered, I think the more important problem is how easy it is to make her follow you. One quest for some animal bones seems too little to ask, for her to accept you as her acolyte and be willing to defend you with her life. If she had a few more challenging quests to prove your worth, and demonstrate your potential to hear the Song of the bones, then earning her as such a strong ally will feel more well-deserved, and believable.

Perhaps she could give a quest to craft a bone flute to help you hear the song, or a fashionable bone leather jacket like the one she wears (though I realize the game does not currently have crafting recipes for either of these items). Something requiring a bit more investment of time and effort, maybe even learning skills in order to craft something she wants.

She is a cool NPC and I would love to see the Bone Seer "fleshed out" more. I am looking forward to seeing what you come up with when you have the opportunity to work on this.

**Comment by jbytheway** [comment]
Continuing to brainstorm Brigitte quest ideas: I had thought it might make sense for her to ask for carving tools; some knife or knives that are moderately uncommon.  Of course, that 's just a fetch quest, which might seem shallow, but I thought I'd mention it.

**Comment by GGgatherer** [comment]
Maybe make it 2-part quest? First is the same, 8 bones. Then she asks you to bring her a whole heap of tainted bones, which should be harder to do if you aren't combat-oriented.

**Comment by SirPiecemaker** [comment]
Hey, so, a followup - the idea that I have to make the quest more inctricate is to give her 3 subsequent quests, one to gather regular bones, one to gather tainted bones and a third to go and craft several bone charms. Adding a recipe for those should be simple enough. And do bear in mind, in the experimental version a few weeks back, she was significantly expanded, stats and gear included.

Please bear in mind that this was the first NPC I made and basically my first excursion into JSON with absolutely no prior coding experience. A big part of why I made her strong was me being completely terrified that she would die before anyone got to talk to her, and that's on top of her being an uncommon spawn with a plot that few people might care about. I still have only a little clue as to what I am doing, so giving her multiple mission ain't so easy for me. Still, I will try and work on that when I finish working on the Artist.

**Comment by acepleiades** [comment]
Thanks for the follow-up! You have all my support. I'm looking forward to it.
