### ISSUE TITLE
Pocket system

### ISSUE THREAD

**Issue by CHJKDM51** [CleverRaven/Cataclysm-DDA#43440]
# Is your feature request related to a problem? Please describe.
The problem is there's no option to forbid usage of certain pockets -> witch increase encumbrance on certain armor pieces during looting -> witch forces player to manually unload every armor piece before every melee encounter.

# Describe the solution you'd like
Implement "pocket auto-pickup" filter into pocket usage system. So set filters would apply when game tries to find available pocket.
For example: if pocket on jeans is set to hold only bandage then nothing else could go to that pocked unless rules changed.

# Describe alternatives you've considered
Ability to forbid pockets usage on item.

# Additional context
Ability to have an empty whitelist would be perfect.

**Comment by Lovewyrm** [comment]
I played with those things and implemented a naive one key solution that set any selected pocket to -999 priority as well as whitelisting a category that does not have any items, but the game still filled those pockets when others became full.

Just as a quick FYI, since it suggests that the change won't possibly be utterly trivial.
