### ISSUE TITLE
Mild Summer Temperature Causing Warm / Heat Slowdown

### ISSUE THREAD

**Issue by PapaPetro** [CleverRaven/Cataclysm-DDA#43451]
Game version: 0.E-5641-g4e9b495 (Build 10977)

Operating system: Win 7-64

Tiles or curses: Tiles

Mods active: NA

### Expected behavior
Going around naked in typical summer weather (73-90°F), should not induce a heat slowdown debuff of -12% nor produce a chance for pain. In reality people down become 12% slower in the summer nor are they at risk for receiving pain.

Existing in 73~90°F should produce no debuff/pain if wearing typical summertime clothing (sneakers, shorts, t-shirt, baseball cap, etc.); humans operate just fine under these nominal conditions at the cost of increased perspiration (and thus thirst).

### Actual behavior
Going around naked in typical summer weather (72-90°F) not only triggers warm condition across the body, but also "heat slowdown" debuff for each body area cumulatively adding to -12% global speed along with a chance to receive pain due to having the Warm condition across all body parts.

![image](https://user-images.githubusercontent.com/29907309/92218728-8c3be880-ee67-11ea-9d9c-1f03fe24baea.png)

**Comment by Zireael07** [comment]
72 F is 23 Celsius. 90 F is 30 Celsius.
While I agree there should be no chance for pain, at least not for the 20-25 Celsius range, the slowdown debuff makes sense. Many people do move more sluggishly in the typical summer temps, probably due to increased perspiration you mentioned.

A chance of pain above 90 F, however, makes perfect sense - many people are not used to temps exceeding that, and do get headaches, muscle aches and similar.

**Comment by PapaPetro** [comment]
This is unrealistic though; perhaps at temps exceeding 100F where Heat Stroke kicks in.

![image](https://user-images.githubusercontent.com/29907309/92251915-895aeb00-ee9b-11ea-908f-0a4c561d1ee0.png)

I like the heat slowdown mechanic, but it should be reserved for more extreme conditions as intended (like for fires or the mi-go camp). 12% automatic slowdown while nude in 78F weather, while doing nothing exertive just doesn't make sense if the game is aiming for realistic survival mechanics.
There are many parts of the world where this temperature range is year-round; but that doesn't imply these people are constantly 12% slower, a -10 morale debuff and randomly are inflicted with pain.
https://twomonkeystravelgroup.com/amazing-countries-have-summer-all-year-round/

The human body itself is 98.6F and can thermoregulate quite well if hydrated to maintain healthy body temperature; hence we have joggers in the summertime who don't run slower or experience pain in normal summer conditions (unless there's a heatwave or they are running thru Death Valley). 
It would be more sensible the Warm condition just created the morale debuff (perhaps even lowed to -5 instead of -10) as a buffer letting the player know they are entering a non-optimal heat environment range.

**Comment by Zireael07** [comment]
'Heat stroke is the most serious form of heat injury' - meaning there are other, less severe forms.

Are you trying to tell me my IRL experience (granted, I live in temperate climate, not in the tropics) is unrealistic? I don't deny there are people who do jog in summertime, but many people are sluggish in heat, e.g. myself and my mother.
And not just us - there's a reason there are warnings put out - in my country, starting at 30 Celsius. The children, the elderly and those who are more vulnerable to heat injuries are advised to stay at home and hydrate.

That said, getting the debuff at 22 Celsius and while nude is excessive. Maybe it should kick in at 25ish and only provided you are wearing clothes...

**Comment by Fosheze** [comment]
I have to second what PapaPetro is saying here. While people maybe might move slightly slower in the summer heat, a 12% slowdown and pain while buck naked is beyond excessive. New England weather is fairly similar to the weather where I am and I can tell you that we have people roofing houses in 80-90F weather with 80% humidity, let alone just walking around. The argument that many people wouldn't be used to that kind of weather is also kind of invalid because we aren't talking about a world wide random sampling of people, we are talking about a cataclysm survivor in New England. The survivor is most likely going to be a New England resident who is used to that kind of weather mainly due to the fact that most of the people who would have been in the area at the time of the Cataclysm would have been residents of the area.

I agree that the warm trait should inflict a morale penalty but as long as the survivor is properly attired and properly hydrated, they shouldn't be facing more than maybe single digit slowdown or any pain what so ever in normal summer temperatures (82F for a high found at below link). Another thing to remember is that when pain is inflicted on the survivor that also inflicts a slow down due to that so as it is now you have stacking slowdowns just for existing during summer with no way to prevent it. 

https://en.wikipedia.org/wiki/Climate_of_Massachusetts#:~:text=Massachusetts%20sees%20a%20wide%20variety,%C2%B0C)%20in%20the%20wintertime.

**Comment by PapaPetro** [comment]
Mechanically that 12% speed debuff from cumulative body part head slowdown is a huge disadvantage for the player in the Summer time.
It means that base walking speed of 100 goes to 114 per move, so virtually all monsters will catch up to you at base walking speed.
I guess it adds artificial difficulty to the game, but it feels unrealistic and unfair to players.

At least in the Winter, you can layer up to avoid the chill debuff. Meanwhile, outside of the Internal Climate Control CBM, there is no way to cool yourself down out in the open (outside of being naked). So you have to eat this warm condition in the Summer with no realistic counter.

**Comment by Fosheze** [comment]
The Wiki on room temperature could be useful as well. It is for indoor temperatures but it does have some good ranges and WHO guidelines.
https://en.wikipedia.org/wiki/Room_temperature

I'm also not sure how all of the mechanics around humidity are implemented. I haven't looked into them too much but from what I can tell humidity doesn't factor into the survivors temperature at all where in reality it is one of the most important things governing how well the body dissipates heat. I know personally I'd take a Nevada 100F with 0% humidity over a Minnesota 80F with 90% humidity any day. 

Now that the BMR system is in place that should probably be integrated into the survivors temperature as well. The more calories the survivor is burning, the more heat their body should need to dissipate. 

But both of those are probably best left to their own issue. I mainly just wanted to leave that link.

**Comment by Zireael07** [comment]
"The recommendation regarding risk of exposure to high indoor temperatures is only "conditional". Minimal-risk high temperatures range from about 21–30 °C (70–86 °F) depending on the region, with maximum acceptable temperatures between 25–32 °C (77–90 °F)"

See, it confirms that people don't like temperatures above 30 Celsius.
And the first paragraph, about comfort temperature, it looks suspiciously like the devs looked at this, or some similar source, and decided to label anything above comfort as 'warm'...

**Comment by Fosheze** [comment]
> And the first paragraph, about comfort temperature, it looks suspiciously like the devs looked at this, or some similar source, and decided to label anything above comfort as 'warm'...

And I definitely agree that 30C should be uncomfortable but it it shouldn't be debilitating which 12% speed decrease in a game based largely around movement is. The way I see it the "warm" penalty should be more equivalent to the "wet" penalty; it should be bad for focus and possibly even make the player dehydrate faster but it shouldn't cripple their ability to move. Also remember those temperatures are guidelines for stagnant indoor air not outdoor temps and that was a 12% speed decrease while naked at only 25C. The survivor should be able to function reasonably well if a bit uncomfortable at those temperatures while still wearing light clothing.

 On the other hand I do agree that if the survivor is doing a lot of work at 30C they should be struggling but that's where integrating BMR into survivor temperature would come in. Chopping wood at 30C should slow you down; just walking down the road really should not.

**Comment by pshepjr** [comment]
As someone who lives in Massachusetts, I agree this is a bit wonky. The penalty makes more sense if you're in heavy armor/clothing - but if you are naked or light on clothing then there should be little to no penalty at these temperatures. Once you're above 90F degrees  consistently then it might make more sense.

**Comment by Aphegis** [comment]
I noticed this aswell, and i agree that 12% speed debuff is way too much. What happens is that it just makes summer more annoying, since you are basically with a 24/7 10% speed debuff.

**Comment by Aphegis** [comment]
I posting again just to show how relevant this problem, from a gameplay perspective, currently is: 

![Heat](https://user-images.githubusercontent.com/34956440/92941346-a311aa80-f426-11ea-9682-1fec355c5747.PNG)

I'm less than a week into summer and this speed debuff makes anything extremely inefficient, the thermometer only reads 26C (78.8F)! Reading is extremely slow even in this 12 int character. It's weird having to read books/craft itens in the basement during the day because of the heat.

In the basement it reads 6C (42.8F)
![Basement](https://user-images.githubusercontent.com/34956440/92942818-55963d00-f428-11ea-8e84-67cd27d8113d.PNG)

**Comment by Robik81** [comment]
Yeah, I just had similar issue. I am in late spring and heat propagating from wood stove while cooking (near open windows, no less) is crazy. I have to cook naked.

So I checked Issues and found this thread.

To add to the discussion, wearing light summer clothing should actually help a bit, as it prevents direct sunlight.

**Comment by JHQWER** [comment]
So we rather just not adress it at all and let it slip huh? Not only this is completely unrealistic but also unimaginable annoying for actual players who play the game. You know, i don't launch cataDDA to have my character sitting in basement doing nothing but reading books and munching on nuts because he is feeling _very hungry_ every 30 minutes but thats pretty much everything i am able to do in the game right now. Short term solution: make comfortable temperature range wider allowing at least some activities during summer. Long term solution: make heat more realistic with effects revolving around stamina pool and regeneration rather than overall slowing down. Running and fighting in combat gear should be problematic in heat, not lying on a couch with book.
