### ISSUE TITLE
Force unarmed make the wielded item unusable in crafting system.

### ISSUE THREAD

**Issue by Proluiz** [CleverRaven/Cataclysm-DDA#43977]
# Describe the bug
EDIT: Check the wapcaplet post for better detailing of the bug.
While fighting instance was supposed to effect just your finghinting it seens to affect the behavior of the crafting system too, so depending in the way that you do some inventory management the craft menu wont detect my scizor and the plank anymore.
While i have no idea why it happens i'll tell here the exactly steps that I do to make this happen.

# Steps To Reproduce
1. Set your fighting style to "Force unarmed".
2. Wield a pistol.
3. Pick up a scissors and put it on the backpack.
4. Pick up a plank and wield it imediately.
5. Try crafting the cudgel.
Note 1: Wont happen if brawling is the active fighting style.
Note 2: Sometimes it's able to detect the scissors.

# Expected behavior
Being able to craft the cudgel.

# Screenshots
![image](https://user-images.githubusercontent.com/6380147/92314561-abde2880-efaf-11ea-807d-c6fdab995d7b.png)
![image](https://user-images.githubusercontent.com/6380147/92314750-56efe180-efb2-11ea-800a-8683d480f2e1.png)

# Versions and configuration
- OS: Windows 7
- Game Version: 0.E-5621-g2de9f7e [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [Dark Days Ahead [dda], Disable NPC Needs [no_npc_food], Stats Through Skills [StatsThroughSkills]]

# Additional context
Wont happen on stable 0.E-2
This save is have the issue present, just check my inventory and look on crafting menu.
[Shady Side.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5178818/Shady.Side.zip)

**Comment by wapcaplet** [comment]
Confirmed in 0.E-5681-g2345fc2470

It can be reproduced by switching martial arts styles while the plank is wielded (no pistol is required):

- Get a plank and a cutting tool (scissors will do)
- `w`ield the plank
- Set `_` martial arts style to "No Style"
- Go to `&` craft and find the cudgel - you can craft it
- Set `_` martial arts style to "Force unarmed"
- Wait 1 turn or take 1 step (this is essential for the martial arts change to take effect)
- Go to `&` craft and find the cudgel - you can no longer craft it

The same results occur with a knife and a stout branch, and the same also occurs if I wield the tool (knife or scissors) instead of the materials (plank or stout branch). It is almost as if the "Force unarmed" martial arts style causes the wielded item to become invisible to the crafting system.

**Comment by Proluiz** [comment]
ok thanks for the clarification, i'll change the title accordingly.
