### ISSUE TITLE
Add `NO_MON_RESIL_SCALE` flag for monsters

### ISSUE THREAD

**Issue by Kenan2000** [CleverRaven/Cataclysm-DDA#44020]
# Is your feature request related to a problem? Please describe.
It would be of great help for mod makers if such flag existed because one can easily imagine what happens when the monster health has been properly calculated for certain balance but not taken into consideration the fact that players can up the `MONSTER_RESILIENCE` modifier and ruin the entire balance for themselves

# Describe the solution you'd like
Add a monster flag that will make the monster health entirely static and independent of `MONSTER_RESILIENCE` modifier, so it would be something like `NO_MON_RESIL_SCALE` (just an example)

# Describe alternatives you've considered
Nothing

# Additional context
Nothing

**Comment by DoctorVanGogh** [comment]
Bad (or rather *too short sighted*) idea.

Presumably users who fiddle around with their `MONSTER_RESILIENCE` modifier intentionally **want** a harder experience and will play and gear themselves accordingly.

So a regular zombie will take four .50 cal shots to kill.... along comes "Super special encounter specific" monster "Bob".... who falls over dead after having a rock thrown at them (because their resilience did not scale up and the player is appropriately "over" leveled/speced to deal with all the other dangers). 
Totally takes any fun or challenge out of those "special" monsters.

---

# Alternate suggestion:
Add a float `Resilience_Scale` factor to monster definitions. Range [`0`-`Float.POSITIVE_INFINITY`]. Default to `1.0` if not explicitly defined.
That way everything scales, but specially designed encounter monsters can have *different* (over- or under-scaled) resilience applied to them. 

Simply offers more options than just "Scaling = ON/OFF".

**Comment by Kenan2000** [comment]
> Bad (or rather _too short sighted_) idea.
> 
> Presumably users who fiddle around with their `MONSTER_RESILIENCE` modifier intentionally **want** a harder experience and will play and gear themselves accordingly.
> 
> So a regular zombie will take four .50 cal shots to kill.... along comes "Super special encounter specific" monster "Bob".... who falls over dead after having a rock thrown at them (because their resilience did not scale up and the player is appropriately "over" leveled/speced to deal with all the other dangers).
> Totally takes any fun or challenge out of those "special" monsters.
> 
> # Alternate suggestion:
> Add a float `Resilience_Scale` factor to monster definitions. Range [`0`-`Float.POSITIVE_INFINITY`]. Default to `1.0` if not explicitly defined.
> That way everything scales, but specially designed encounter monsters can have _different_ (over- or under-scaled) resilience applied to them.
> 
> Simply offers more options than just "Scaling = ON/OFF".

Yeah, that's a better suggestion, I admit that I have not thought too deeply of this when making this issue - just the first thing that came to my mind

**Comment by anothersimulacrum** [comment]
Yeah, I agree with DoctorVanGogh - resilience is an option that is explicitly the player stating 'I choose how the game is balanced with regards to health', and I'm not sure that should be subverted at all. This kind of option (a totally player specific one) being subverted by people making content does not seem like something that should happen.
