### ISSUE TITLE
Inks and Paints

### ISSUE THREAD

**Issue by Ali-Anomma** [CleverRaven/Cataclysm-DDA#44062]
# Is your feature request related to a problem? Please describe.
Permanent marker inks and spray can paints are useless: they are decorative tools; they don't change gameplay.
And it can't be crafted,
# Describe the solution you'd like
Removing inks and spray can paints,so it becomes pure decorative again.
# Additional context
(It is a bit about candle wax, they are handy tools and provide light to change gameplay; and they are consumable before 0.F,candle wax adds a bit of comsumability. But it must be crafted by fats (like in crafting candle) , and it becomes a good idea. )
[And a last note: crafted candles starts with zero charges of wax.]

**Comment by ZhilkinSerg** [comment]
What is exactly your concern?

**Comment by danielkwinsor** [comment]
If I interpret it correctly, let only the things that are crafted be regular items (survivor marker, paints), otherwise, these spray paint cans are only cosmetic items.

I might go the opposite direction... what about find a way to make them useful?

I have an idea which, if I'm not lazy, I can list later... use the charges of these to write Notes in a Map.  You don't get automap notes if you don't have a survival marker or permanent ink marker.

**Comment by meelock** [comment]
It would be interesting if you had to physically make your over-map using markers and the like. Though this would annoy a lot of players (what doesn't though).

**Comment by wapcaplet** [comment]
> Permanent marker inks and spray can paints are useless: they are decorative tools; they don't change gameplay.

What do you mean?

`a`ctivate to use:

![image](https://user-images.githubusercontent.com/238395/92547359-f2cb5880-f211-11ea-91f7-a89eac959715.png)

You can write on terrain or items:

![image](https://user-images.githubusercontent.com/238395/92547383-0080de00-f212-11ea-8975-e6053af6451c.png)

For items, it can be a label or a note:

![image](https://user-images.githubusercontent.com/238395/92547427-1a222580-f212-11ea-8d25-f733924e67b9.png)

The label is how it shows up in the inventory:

![image](https://user-images.githubusercontent.com/238395/92547412-0d053680-f212-11ea-8847-650c08016f20.png)

The note appears in the item description:

![image](https://user-images.githubusercontent.com/238395/92547463-2b6b3200-f212-11ea-90e7-1e5dc5f7222e.png)

Or you can write something on the terrain:

![image](https://user-images.githubusercontent.com/238395/92547634-8bfa6f00-f212-11ea-80ae-67a0cee54de4.png)

Now you can read the message, even from far away:

![image](https://user-images.githubusercontent.com/238395/92547755-d976dc00-f212-11ea-9bb7-bd3755b00447.png)

With a spray can, you can spray a message on a wall:

![image](https://user-images.githubusercontent.com/238395/92547517-42aa1f80-f212-11ea-8665-1d887e1b2a1c.png)

Then read the message later:

![image](https://user-images.githubusercontent.com/238395/92547540-5190d200-f212-11ea-8617-7a156ac54180.png)

> Describe the solution you'd like
> Removing inks and spray can paints,so it becomes pure decorative again.

@Ali-Anomma It sounds like you are asking for all of these features to be removed. Why?

**Comment by kevingranade** [comment]
My best guess is they're saying remove the ink and spray paint items, leaving note taking as a pure UI thing even when leaving a note on the map.

In short, no, items don't need a function in order to exist, and marking the map (which may have some tangible effect at some point, i.e. blazing a trail) should require material use.
