### ISSUE TITLE
Mansions weren't updated to use SUS groups

### ISSUE THREAD

**Issue by Amoebka** [CleverRaven/Cataclysm-DDA#44136]
# Describe the bug

Back when the great SUSening of urban houses happened, mansions were left out. As a result, their loot density is no longer consistent with the rest of the game (too low). While houses spawn with fridges full of food and wardrobes full of clothing, mansions have one bottle of beer per fridge and one or two jackets per drawer (most are downright empty).

# Steps To Reproduce

1. Spawn character, map reveal, long range teleport to a mansion, check loot in drawers.

# Expected behavior

Mansion bathrooms use SUS groups for house bathrooms.
Mansion fridges use SUS groups for house fridges (plus extra fancy foods rich people eat?).
Mansion wardrobes use SUS groups for house clothing (plus extra jewelry_front itemgroup spawns?).

# Versions and configuration

 - OS: win10
 - Game Version: 0.E-5859-g8e8260f
 - Graphics version: tiles
 - Mods loaded: dda

# Additional context

While I understand the hateboner some might feel for mansions, loot like common clothing and basic food shouldn't be uncommon there. A 3x3x3 mansion should have more common loot than a 1x1x2 urban house.

**Comment by curstwist** [comment]
When I was doing the house conversion (which is a palette swap/rows rewrite not just SUS spawns) I didn't do the mansion(s) because it really needs a complete overhaul, including getting json roofs which is complicated by its use of variant maps.

It definitely needs a good rehabilitation though and I'll see what can be done before 0.F.
Adding context here in case someone else gets to it before I do : )
