### ISSUE TITLE
Standardize rope proficiency

### ISSUE THREAD

**Issue by danielkwinsor** [CleverRaven/Cataclysm-DDA#44144]
# Describe the bug

All rope recipes have 3x time if proficiency isn't there, except for Long Rope from 5x short rope, which is 1.5  I suspect this is a copy paste error from fibers.

# Steps To Reproduce

View recipes

# Expected behavior

Long Rope from short rope should have the same multiplier as long cordage rope from short cordage rope, and all the other ropemaking recipes

**Comment by anothersimulacrum** [comment]
CC: @I-am-Erk

**Comment by danielkwinsor** [comment]
As an aside, it's always seemed weird to me that it takes the same amount of time to go from 6 withered -> short cordage as 36 withered -> long cordage.  We could use the same tactic here, with multiple recipes.

**Comment by I-am-Erk** [comment]
The long rope from short rope recipe appears to be just tying and stitching lengths of rope together, given the requirements. We could do with a proficiency-requiring recipe for splicing, taking less time and requiring nothing but short rope

**Comment by danielkwinsor** [comment]
If you look at the lengths, then short string -> long string is splicing, not twisting; same for cordage pieces and cordage ropes.
Going from long cordage piece to short cordage rope is clearly 3 strand twisting, so is long string to short rope.

There is a long rope recipe that takes either 5 short rope or 30 long strings.  1 of those is twisting, the other is only splicing.

**Comment by I-am-Erk** [comment]
I haven't gone to the granularity of distinguishing "just twisting" from splicing here, and that's not what I'm saying. The current short rope to long rope recipe doesn't appear to use twisting, splicing, or rope making in any major sense.

**Comment by lcy03406** [comment]
But, should splicing be an proficency? Nobody would say 'I am proficent in splicing'.

Common knowledge and simple actions should not be proficencies, or we would have too many proficencies such as stiching cloth, welding pipes, breaking lettuces....

Some stone age techniques (eg. knapping, drilling) can be proficencies, because (1) many people play CDDA as wildness survival and (2) an average (post)modern character should not have learned the ancient techniques.

Now in the game anyone can read books, drive a car, turn computer on and read notices on it. So any actions easier than writing, keyboard typing, driving should not need proficencies.

**Comment by I-am-Erk** [comment]
No, splicing would be covered in rope making, since you can't make rope without knowing how to splice. I'm saying, the action of tying together short ropes to form a longer rope doesn't require the rope making proficiency. We could have another recipe with fewer ingredients that did require the proficiency, if we wanted, but there isn't an error in the recipe as it currently stands.
