### ISSUE TITLE
UI Improvement - Scrolling / Paging

### ISSUE THREAD

**Issue by Nandorianen** [CleverRaven/Cataclysm-DDA#44152]
CDDA is played mostly from keyboard, so it's really important to have quick and intuitive ways of getting from point A to point B in any given list of items / monsters / options. One big part of intuitiveness is consistency.
@irwiss already did improvements for some menus, for example, in #44100, but there are many more.

Here is a brief and incomplete list of menus without Page Up / Down functionality at all:
* [x] character creation lists;
* [x] crafting menu (for the list itself);
* [x] construction screen;
* [x] Shift+V monster list;
* [ ] character screen (useful for long lists of traits, bionics, possibly skills);
* [ ] bionics screen;
* [ ] mutation screen;
* [ ] look around mode (no way to scroll through the list at all);
* [ ] basic (non-advanced) inventory screen;
* [ ] drop screen;
* [ ] disassemble menu;
* [ ] armor layering screen;
* [ ] wear item screen;
* [ ] take off screen;
* [ ] wield item screen;
* [ ] reloading screen;
* [ ] unloading screen;
* [ ] consume screen;
* [ ] reading screen;
* [ ] execute action screen;
* [ ] use item screen.

* [ ] For Shift+V: Page Up / Down works for item description, but not for the list of items itself. Since you move through this list with Up and Down arrows, what about making Left and Right go up/down a page respectively?
Left / Right arrows could also be used in several menus to quickly jump to the next pointer (for example, to the next category in Consume menu).

Also Page Up / Down behaves inconsistently in regards to looping around. For example, in advanced inventory pressing Page Up while in the first position will take you to the last position, but in most other lists it won't do anything.

It would also not hurt to have Home / End functionality for very long lists that do not naturally reset cursor position (debug spawn, debug mutation).

There are so many menus behaving in different ways that it seems like it would be a great pain to try to maintain them all at a more or less uniform level of development. Maybe some unification and templat'ification is in order? I have no knowledge of UI code to propose anything specific.

**Comment by esotericist** [comment]
this is something i've definitely been wanting to improve, but a lot of why this has taken so long to get standardized is because all of the various sections of the game have hand-written versions of the interfaces.

getting more unified internals is definitely a goal, and it's something a couple of us have been poking at since it's clearly needed. i at least have been moving kind of slow because my world has been kinda messy this year x_x 

props to @irwiss for getting some of it going despite us not having that framework yet, though. any progress on this front is appreciated

**Comment by Pupsi-Mupsi** [comment]
@Nandorianen

Would you mind removing "completed scrolling features" from the list?
You may also want to check whether you like the new "scrolls".

**Comment by Nandorianen** [comment]
@Pupsi-Mupsi 
Sorry, I stopped my run of CDDA a few weeks ago on account of it becoming more and more of a slugfest, so I haven't been keeping up with the development progress.

Tested the construction / crafting menu scrolls, and of course I like the fact that they are added. Thank you!
I would consider increasing the jump, though. Right now Page Up/Down jumps the cursor 4 lines, which only saves the player 3 button presses. Feels a bit small, especially considering that in other menus Page Up/Down would jump your cursor a whole... well, page. That would be an overkill, though. Maybe 10 or 12 lines?

Updated the OP as per your suggestion. Also noticed that I missed unloading screen the first time around (added it to the list), and that Page Up/Down stopped working altogether in "execute action" menu.

**Comment by Pupsi-Mupsi** [comment]
Thank you very much for your feedback.


`Tested the construction / crafting menu scrolls, and of course I like the fact that they are added. Thank you!
I would consider increasing the jump, though. Right now Page Up/Down jumps the cursor 4 lines, which only saves the player 3 button presses. Feels a bit small, especially considering that in other menus Page Up/Down would jump your cursor a whole... well, page. That would be an overkill, though. Maybe 10 or 12 lines?`

You are right. Changed in #45188.

`The Page Up/Down functionality of New Character traits and profession tabs feels right. One relatively minor thing, since we are talking about consistency: I would say that the expected behavior is for Page Down to only loop around if pressed while the cursor is at the very last position, and then only to the first position. It's not supposed to loop as freely as it does right now. Similar thing for Page Up.`

I agree. Already fixed that in #45181.

**Comment by Pupsi-Mupsi** [comment]
`For Shift+V: Page Up / Down works for item description, but not for the list of items itself. Since you move through this list with Up and Down arrows, what about making Left and Right go up/down a page respectively?
Left / Right arrows could also be used in several menus to quickly jump to the next pointer (for example, to the next category in Consume menu).`

--> Left and Right already in use. I'll use "<" and ">" for the description and PAGE-UP/DOWN for fast scroll.
--> Changed in #45189.

![grafik](https://user-images.githubusercontent.com/44737997/97790864-c22dec80-1bcc-11eb-9e89-972a05a1a15f.png)

**Comment by leemuar** [comment]
As a relatively new player I would like to add: the game is mostly played on keyboard because it has poor mouse support. When I started playing I was struggling by lack of mouse support in many UI elements.

This is not a critique of the project, I just want to point out "keyboard only because that how roguelikes were always made" should not be out dogma. Cogmind example shown how good mouse support make things much easier, accessible and enjoyable for players
