### ISSUE TITLE
Can't pickup guns

### ISSUE THREAD

**Issue by LlubNek** [CleverRaven/Cataclysm-DDA#44317]
# Describe the bug

Can't pick up guns off the ground even when they should easily fit in my inventory.  Wielding them still works though.

# Steps To Reproduce

1. Find a gun
2. Try to pick it up

# Expected behavior

Should be able to pick up guns.

# Screenshots
![image](https://user-images.githubusercontent.com/313762/93780723-80398000-fbf6-11ea-8f95-331d9356ca9e.png)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.E-6130-gb825e3a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Arcana and Magic Items [Arcana],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Medieval Mod Reborn [Medieval_Mod_Reborn],
    MST Extra [MST_Extra],
    DinoMod [DinoMod],
    Cataclysm++ [Cata++],
    Crazy Cataclysm [crazy_cataclysm],
    Mining Mod [Mining_Mod],
    More Survivor Stuff [more_survivor_stuff],
    Mythical Martial Arts [MMA],
    Dorf Life [Dorf_Life],
    Tankmod: Revived [Tankmod_Revived],
    [OBSOLETE] More Locations [OBSOLETE_more_locations],
    [OBSOLETE] Fuji's More Buildings [OBSOLETE_FujiStruct],
    [OBSOLETE] Urban Development [OBSOLETE_Urban_Development],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    [OBSOLETE] Graphical Overmap More Locations [OBSOLETE_Graphical_Overmap_More_Locations],
    [OBSOLETE] Graphical Overmap Fujistruct [OBSOLETE_Graphical_Overmap_Fujistruct],
    [OBSOLETE] Graphical Overmap Urban Development [OBSOLETE_Graphical_Overmap_Urban_Development],
    sees-player icon, retrodays [sees_player_retro],
    Fuji's Military Profession Pack [fuji_mpp],
    Manual Bionic Installation [manualbionicinstall],
    Portable Autodoc [portable_autodoc],
    Safe Autodoc [safe_autodoc],
    Safe Portable Autodoc [safe_portable_autodoc],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by LlubNek** [comment]
Here it is again with no mods:
![image](https://user-images.githubusercontent.com/313762/93783888-44081e80-fbfa-11ea-82b6-5027e901e28a.png)

Also happens with inactive tear gas hack:
![image](https://user-images.githubusercontent.com/313762/93783797-25a22300-fbfa-11ea-8974-cad04a544488.png)

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.E-6130-gb825e3a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by LlubNek** [comment]
The M17 in inventory came with the profession.

**Comment by LlubNek** [comment]
Also happens with 1-cylinder engine...
![image](https://user-images.githubusercontent.com/313762/93785200-cf35e400-fbfb-11ea-95a4-217c8a77f1bc.png)

**Comment by wapcaplet** [comment]
To pick up any item, you need to have a container with a pocket big enough (and lengthy enough) to contain it. My guess is you do not have any pockets with enough "Maximum item length" to hold these items.

For instance, the M4A1 is 758 mm long, which is too long to fit in most backpacks:

![image](https://user-images.githubusercontent.com/238395/93819674-42018800-fc19-11ea-8763-6f7edee58ce5.png)

![image](https://user-images.githubusercontent.com/238395/93819876-8c830480-fc19-11ea-9a43-16481df67c49.png)

The 0.4L 1-cylinder engine does not have much volume or length, but it is heavy (20 kg):

![image](https://user-images.githubusercontent.com/238395/93820079-dbc93500-fc19-11ea-8d78-4644c3684efc.png)

So even though it is small enough and short enough to fit in the pocket of cargo pants (for example), it is too heavy for them:

![image](https://user-images.githubusercontent.com/238395/93820210-0e732d80-fc1a-11ea-886b-6160eb9804e2.png)

I don't know what clothing/containers you are wearing, but my guess is the length or weight is why you can't pick them up.

That said, I agree that the message is wrong about why the item won't fit, saying only "You have no space ..." even if the reason is that you don't have enough length or weight capacity.
