### ISSUE TITLE
Suggestion: Gruel

### ISSUE THREAD

**Issue by JayThirtySeven** [CleverRaven/Cataclysm-DDA#4440]
A crafting recipe for gruel would be appropriate and could be useful for characters who try to survive by farming.

Basically: Water + Flour + Container + Heat = Gruel

It might have a zero or negative morale modifier but is much more pleasant than trying to eat raw flour. May also increase the nutrition value of the flour, since boiling whole grains would weaken some of the indigestible fiber.

This recipe could be very relevent if/when the player can grow wheat or maize and grind it into flour, as gruel would require very little time or skill to prepare.

Gruel could also be used as a broth for making soup if you're feeling generous.

Additional info at wikipedia: http://en.wikipedia.org/wiki/Gruel

**Comment by mugling** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
