### ISSUE TITLE
Whiskers are useless under a long scarf

### ISSUE THREAD

**Issue by Termineitor244** [CleverRaven/Cataclysm-DDA#44616]
# Describe the bug

Whiskers lose its dodge bonus under a scarf (even a loose scarf which allows for special mutated attacks (bites)).

# Steps To Reproduce

1. Make a character with whiskers.
2. Observe its dodge ability (with modifiers)
3. Spawn and wear a long scarf and loose it.
4. Observe again its dodge ability, it should have lost the bonus from the whiskers.

# Expected behavior

To be able to sense vibrations with my whiskers when my scarf doesn't hinders them (The scarfs are worn in the neck... And if I loose one so I can bite enemies without it hindering me, then my whiskers should not be hindered too).

# Screenshots

![whiskers 4](https://user-images.githubusercontent.com/53200489/95024111-b2130380-0646-11eb-8020-0b3e077c616e.png)
![whiskers 1](https://user-images.githubusercontent.com/53200489/95024112-b2ab9a00-0646-11eb-83b4-7c3b3631e24e.png)
![whiskers 2](https://user-images.githubusercontent.com/53200489/95024113-b2ab9a00-0646-11eb-8530-4d2e8b0b4e07.png)
![whiskers 3](https://user-images.githubusercontent.com/53200489/95024114-b3dcc700-0646-11eb-845c-f45ff3be6c6f.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-6459-ge49eaa0 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda], 
    Disable NPC Needs [no_npc_food],
    Whaleys Hair Mod (UDP Tweaks) [WHALEYHAIR_UDP],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

# Additional context

Inspired by #42620 in which its resolved a similar problem with the feet mutations and some clothing that should not hinder them.
This problem could also be present in other face mutations... Didn't check.

**Comment by wapcaplet** [comment]
Confirmed in 0.E-7041-gdb7d1378fa, with a basic starting character. Without whiskers, dodge is 2.4; with whiskers, it becomes 3.4. But a scarf (whether loosened or not) reduces it to 2.4 again. This code prevents whiskers from working if the body part is covered at all, not taking into account the "won't hinder special attacks" flag:

https://github.com/CleverRaven/Cataclysm-DDA/blob/089c59fe229593d189b71292c1021d8d014ad93d/src/avatar.cpp#L1276-L1279

This can be fixed by changing the `wearing_something_on` call with `natural_attack_restricted_on`, to allow a loosened scarf to be exempt. I have submitted a PR to fix this.
