### ISSUE TITLE
Gasoline should rot.

### ISSUE THREAD

**Issue by Profit0004** [CleverRaven/Cataclysm-DDA#44645]
In real life gasoline has a rather short shelf life, especially the ones blended with alcohol. 

In the US the average life is 3-5 months before it starts not working as well.  

Given the locations in the game I would believe they would use some fuel stabilizer but gasoline should still have a lifespan of about a year for full performance then significant degradation, and engine damage should start to set in till it no longer works. 

Diesel should be about twice that long, maybe longer as the engines tend to fare better with lower quality fuels.

**Comment by ZhilkinSerg** [comment]
See https://github.com/CleverRaven/Cataclysm-DDA/issues/37054#issuecomment-627660858

**Comment by Fosheze** [comment]
Blended gas does age fairly rapidly however most vehicles _can_  still run on it even after it has gone bad. It just isn't as good for engine health and doesn't run as well. At the same time if we are going to be adding fuel aging to the game different fuel mixes should be made available as well. Non-oxygenated gasoline is readily available from most gas stations and, while it technically only has a shelf life of about a year, I have personally never heard of it going bad when stored correctly. I have seen an 8 year old tank of the stuff that still tested good and worked just as good as new. In a subterranean gas station tank that stuff is basically never going to spoil. Odds are it is also going to be the most plentiful too. When the cataclysm strikes the premium gas is most likely going to be the last to go.

**Comment by Xpyder** [comment]
This has actually been suggested before though I can't find the issues related to it.  I think the core idea is good though timing and implementation may take a while and it make take some time for people to get used to the idea.

Also I don't know how well the game handles a tank of liquid that has different components at different levels of rot.

If it is implemented I think a lot of players may have trouble adjusting to this initially so I suggest setting the initial rot time to something longer like 2-3 years.  Once people are more accustomed to the idea and working around it (and maybe have ways to actively preserve it or replace it) then we can bring the rot timer back to a more realistic level

**Comment by Fosheze** [comment]
> Also I don't know how well the game handles a tank of liquid that has different components at different levels of rot.

This could be resolved by having a age timer for each "stack" of liquid and when different stacks of liquid are added together you would average the age timers together proportionally to the amount of liquid in each stack respectively and get a single rot timer for the new total stack. When splitting a tank you just copy the timer from the parent tank. After all adding good gas to a tank of bad gas will still make the bad gas work better because the bad gas is just more diluted. I would also say that you never want gas to turn "rotten" you would just want it to get older and thus you wouldn't want to check for the rotten state, you would just directly check the timer on that stack.
