### ISSUE TITLE
Tailor kits and clothing modification

### ISSUE THREAD

**Issue by SunshineDistillery** [CleverRaven/Cataclysm-DDA#44866]
# Is your feature request related to a problem? Please describe.

I've been using/modding tailor kits lately. They're cool but quite limited.
You can't alter the time it takes for a clothing mod or the amount of components or the visibility of available mods or additional tools needed and so on.

# Describe the solution you'd like

There should be new type of recipe that applies a flag to an existing item rather than creating something. That would use all the familiar mechanics of crafting and prevent the need to reinvent those features for clothing mods.

A general system for altering items--flags and changing number values--could then be used for other items too.

# Describe alternatives you've considered
Reinventing the wheel? Even if mods are kept as an item action, there should be a more generic system.

# Additional context
I sort of hate recipe bloat. But in this case, modification type recipes could cut things down. All those xl recipes could be condensed to two or three that add the oversize flag.

**Comment by Zireael07** [comment]
Clothing modification has been suggested already IIRC.

**Comment by Marrim** [comment]
With the new pockets system it would be slightly more viable to implement modifying storage space. Changing the volume of pockets and such.

**Comment by NickVolynkin** [comment]
@Marrim or sewing extra pockets onto something.

**Comment by SunshineDistillery** [comment]
Clothing modification is already in the game, and there's a whole project for expanding tailoring. My suggestion is just to ditch the wonky tailor's kit.

I did read a pr that said changing more things would be possible, like removing sleeves,adding pockets,etc.

**Comment by Giagantic** [comment]
> 
> 
> Clothing modification is already in the game, and there's a whole project for expanding tailoring. My suggestion is just to ditch the wonky tailor's kit.
> 
> I did read a pr that said changing more things would be possible, like removing sleeves,adding pockets,etc.

Primary reason it is wonky is because the overall UI and process is painfully annoying, forcing you to go through several unnecessary steps (Inventory -> Tailoring Kit -> Modification ->Pick Item -> Pick Modification -> Repeat ad nauseam in the case of failure to modify). A simple solution is make the menu for modification popup every time you finish or fail a modification. Such a thing already exists in the case of the repair meaning you can don't have to re-go through the process of (Inventory -> Tailoring Kit -> Repair Item -> Pick Item -> Pick Item -> etc...). The ideal scenario from my point is to introduce a wider array of tools for Tailoring and through that add more depth to modification with additions like Sewing Machines and other more mechanical tools with the hand-tools like needles taking significantly more time.
