### ISSUE TITLE
The mutation "Furred Plate" in the spider post-threshold line gives way too much dodge bonus.

### ISSUE THREAD

**Issue by MasterLiKhao** [CleverRaven/Cataclysm-DDA#45003]
# Describe the bug

After playing around with it and hoping it's intended, I am as of now pretty sure this is a bug. Furred Plate's description states that any limb left uncovered gives +1 dodge (with the head counting as a limb), with the torso giving +4 dodge. Even if the limbs granted by the mutation "Arachnid Arms" would count, as well (and I don't even know how many you'd have but I'm assuming 8 limbs in total, as spiders usually have) this would mean the maximum bonus you can get from these mutations is +13, which is already quite overpowered (And that is IF the Arachnid arms are supposed to contribute to the dodge bonus. Otherwise, the maximum would be +9). However, on my most recent character, I have 8 base dodge, and I apparently receive a whopping +22 dodge from these mutations. My current dodge is 30. Kinda fun to be able to take down an entire Megamall filled with zeds by simply holding down Tab, or going up against a Kevlar Hulk in Melee without ever getting hurt (stark naked and only using my fists, by the way. Using Crane Style Kung Fu or CRIT CQB), but clearly totally overpowered.

# Steps To Reproduce

1. Make a character. Maybe give them some natural dodge skill.
3. Use Debug to mutate in Spider threshold and Furred Plate mutation.
4. Make character strip naked.
5. Check dodge score. The value indicating the current dodge is too high given the description of Furred Plate's bonuses.

# Expected behavior

For the mutation to only give a maximum of +9 dodge (or +13 with Arachnid Arms, if intended), to make its effects match its description.

# Versions and configuration

- OS: Windows
    - OS Version: Windows 7
- Game Version: 0.E-6984-g8090909 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Cataclysm++ [Cata++],
    Mythical Martial Arts [MMA],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Cataclysm++ - UndeadPeople Tileset [Cata++UDP],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Mythical Martial Arts - UndeadPeople Tileset [MMAUDP],
    Whaleys Hair Mod (UDP Tweaks) [WHALEYHAIR_UDP],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

#Additional information

As I have mentioned in a reddit post to KevinGranade, my guess is that the calculation for the extra dodge from Furred Plate erroneously duplicates your natural dodge value. In my case (I also have antennae, which might count as an additional body part?) the calculation could work as follows: 4 Torso + 1 head + 1 Antennae + 8 limbs (Arachnid Arms) = 14; +8 (natural dodge) = 22. When natural dodge is then added AGAIN (which I assume is the bug here), I get to exactly 30 dodge, which is what I am currently seeing.

**Comment by junknowny** [comment]
A naked character with 8/8/8/8 stats and 0 dodge has 4 effective dodge. If we give the character Furred Plate via the debug menu effective dodge becomes 10.5, which makes sense since Furred Plate gives naked characters +9 effective dodge but also -1 dex (-0.5 effective dodge) and 10 encumbrance to torso (-1 effective dodge) and both legs (another -1 effective dodge) for a net value of +6.5 effective dodge.

Adding Arachnid Arms gives +2 dex, and thus +1 effective dodge, so does Very Dextrous for a grand total of +8.5 effective dodge over a vanilla naked character. Changing dodge from 0 to 8 results in +8 effective dodge as expected.

As you play with stats through kills & skills is it possible that your character simply has a massive dex stat?

**Comment by MasterLiKhao** [comment]
Sorry for not checking this in a while, I kinda forgot about it. My character indeed has 18 Dex; I thought this would have been calculated into the base dodge, but apparently it doesn't.

**Comment by junknowny** [comment]
18 dex is the main reason you have such a high dodge stat. That much dex gives 9 levels of dodge by itself, and even more with CRIT CQB (Crane Kung Fu also boosts your dodge _and_ uses your dex instead of str for damage calculations). Your base dodge skill of 8 and Furred Plate also increase your dodge by a large amount (8 and 7 respectively), but still less than the amount you get from raw dex + modifiers from martial arts.

**Comment by anothersimulacrum** [comment]
Seems to work correctly, and the description doesn't even say that anymore.
