### ISSUE TITLE
Hyper-metabolism does nothing

### ISSUE THREAD

**Issue by seerdecker** [CleverRaven/Cataclysm-DDA#45329]
Game version: b11142.

Got hyper-metabolism on. Eating never triggers the "You feel the %s filling you out." message unless I debug-edit the hunger level. Stomach bursts due to overeating if I do not use the debug menu.

**Comment by wapcaplet** [comment]
Confirmed in 0.E-7424-gcbcf5fd9, by acquiring the "Chaos" and "Hyper-Metabolism" traits, then getting hungry and eating lots of food. Never once was "You feel the ... filling you out" shown.

The section that checks for this trait appears to be unreachable, since `get_hunger()` returns positive values (or 0), while `capacity = stomach_capacity()` returns negative values (or 0). So `if( get_hunger() < capacity )` would always be false:

https://github.com/CleverRaven/Cataclysm-DDA/blob/4c8241733b07924a8a97e89148bb96c33d3ac677/src/consumption.cpp#L1377-L1379
