### ISSUE TITLE
Crafted tea evaporates into thin air when a friendly dog is around

### ISSUE THREAD

**Issue by wapcaplet** [CleverRaven/Cataclysm-DDA#45343]
# Describe the bug

When crafting pine needle tea, if there is a friendly dog nearby, the in-progress pine needle tea disappears before I can finish crafting. There are no messages about what happened to it, but the disappearance seems to coincide with the dog being on the table where I am crafting.

# Steps To Reproduce

1. Spawn a dog
2. Befriend the dog with dog food
3. Spawn pine bough, water, hotplate, and cooking pot
4. Attempt to craft pine needle tea - "You no longer have the in progress craft in your possession."

# Expected behavior

In-progress crafts should not vanish without a trace.

If the dog is somehow consuming the craft, there should be a message telling me this.

# Screenshots

![image](https://user-images.githubusercontent.com/238395/98746936-b9c77580-2373-11eb-9d80-31a2a5f117fd.png)

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.E-7424-gcbcf5fd9bd [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

# Additional context

This does not happen all the time, and I had difficulty reproducing it on demand. One trial, I attempted to craft pine needle tea about 15 times in a row, and failed every time ("You no longer have the in progress craft"). The next trial, I crafted pine needle tea 15-20 times, always successfully.

I have never seen it occur with anything other tha pine needle tea; I tried to reproduce the issue by crafting black tea, scrambled eggs, and cooked scraps of meat, but was always successful in completing the craft.

I have not seen it occur with a dog that I had not befriended using dog food.

**Comment by Xindage** [comment]
i've had issues in doing food with dog around too, seens like when he stand where you're crafting you lost the craft

**Comment by PatrikLundell** [comment]
Could it be an indexing error of the same type as the one affecting vehicles, i.e. the game expecting your in progress item to be at index X in the stack of stuff on the table, but if a dog (or cat, chicken,...) gets onto or off the table between the time you start crafting and the time the recipe needs to check progress the index refers to something other than the in-progress item? In particular if the critter was on the table at the start, but not there at the check, if the in progress item gets the last index, which would be dog + 1, but when the dog moves there is no item at position dog + 1, as it's now moved to the position the dog had.
(In the case of vehicles, removal of items by the PC or an NPC shifts the indices of the remaining items, causing other NPCs to remove items other than the ones they intended/started to remove).

Another possibility is that the in-progress item is placed in the dog's inventory, rather than on the table (that's what I'd expect if crafting while in a vehicle, and a dog is a mount for rat mutants).

**Comment by Ramza13** [comment]
Pretty sure this happens in the save for #43214 and was the ultimate cause of that issue as well.

**Comment by kevingranade** [comment]
The dog ate it.
Not figuratively, it literally thinks it's food and ate it.
I'm trying to track down *why* the dog thinks your in-progress pine tea is food, and also why the dog is even executing the code to eat things as it's not configured to.

**Comment by kevingranade** [comment]
Welp, it's pretty straightforward, dogs have the "eat_food" behavior, and "eat_food" is rather... generic.  It's literally anything that qualifies as food.  It needs to not be silent, and it needs to avoid grabbing food from IDK, immediately adjacent to the player.
