### ISSUE TITLE
[Request] Implement custom reloadable kits

### ISSUE THREAD

**Issue by Olaroll** [CleverRaven/Cataclysm-DDA#45356]
# Is your feature request related to a problem? Please describe.
I often find myself carrying a set amount of various meds, drugs, ammo and spare parts. Making sure I'm always topped off on these wastes a lot of time, especially once I start accumulating a lot of items.

# Describe the solution you'd like
I think a good solution to this would be allowing the player to create their own "kits" out of containers. These kits could then be [**r**]eloaded to very quickly replenish used supplies.

Here's what I think is the simplest and most intuitive implementation:
1. Use the **Insert** function to set up a container with all the items the kit should contain
2. Use a new "**Make Kit**" function to turn the container into a kit, configured to the items it currently contains
3. If an item from the kit is missing, it can now be refilled in one of two ways
   1. When a matching item is picked up, it gets placed in the kit
   2. When using [**r**]eload on the kit, it will be filled with matching items from the player's inventory and immediate surroundings
4. If necessary, the kit configuration can be edited by repeating steps 1 and 2

Useful extra behaviour:
* No other items are put in the kit without the player's explicit request
* Kits refill recursively, meaning bottles get topped off with liquids and magazines get reloaded with bullets
* Per-pocket kits, as opposed to turning the whole container into a kit.
* Examination info includes current/desired item counts (e.g. Bandage [1/6] )

# Describe alternatives you've considered
* No kits, only manual organizing :(
* A more advanced kit creation system with its own UI for extra features

# Additional context
Here are a couple of use cases off the top of my head:
* Med-kit
* Vehicle repair kit
* Clothing repair kit
* Easy to manage ammo pouches

**Comment by natsirt721** [comment]
You can do this with pocket whitelisting and blacklisting (I think). Blacklist everything, then whitelist the items you want and set the kit container priority higher. While something of a manual process to set up initially, it does solve the main issues you bring up:
- Items on the whitelist are place in there by default (by nature of having high priority)
- Item not on the whitelist (not in the kit) are ignored due to the blacklist
- Items counts are already displayed in the container's item screen
- Fluid containers can already be `r`eloaded to refill them from other containers nearby or in inventory
Let me counter-propose some enhancements to the pocket autopickup settings to facilitate this:
- Add an option that will "kitify" the pocket or item based on its current contents, by that I mean
  - Blacklist everything
  - Add everything that is currently in the pocket to the whitelist
  - "whitelist contents" sounds like a better name than "kitify"
- Add the ability to copy-paste white/blacklists between pockets in the same container
- Add the ability to set a soft maximum on the number of items
  - When the count is below the max, items will be added to the pocket according to the priority of the pocket as usual
  - When the count is >= the max, when inserting an item the pocket will have an effective priority of 0
  - This sounds messy and I'm not totally sold on it myself, but it would keep my med kit from filling up with hundreds of aspirin

**Comment by Olaroll** [comment]
Kits could very well be part of the pocket whitelist system. However, your proposed enhancements missed one key benefit of my original post, which is the kit reloading functionality.

Being able to reload a kit all in one go would be, in my opinion, a huge QOL improvement. I mean, it could easily **reduce dozens of keypresses to just two**, provided the kit has a key assigned to it. And this could happen many many times in a single session!

As an actual example, this is how you'd refill a medkit with only pickup:
1. Check what meds need refilling (otherwise you'll overfill into some other storage)
2. Open the right storage
3. Filter for the item you need and take it
4. Repeat step 3 for every different item you need, which could be around 10 for meds

And this is how easy it would be with kit reloading:
1. Press [**r**]eload and [**m**]edkit
