### ISSUE TITLE
Compound greatbow has balance issues

### ISSUE THREAD

**Issue by OtpalTS** [CleverRaven/Cataclysm-DDA#45366]
# Is your feature request related to a problem? Please describe.
Currently the Compound greatbow has a strength requirement of 15, stab damage of 11 and range of 22. Compare this to the Compound hunting bow set to high(CHB/high). It has a strength requirement of 11, stab damage of 12 and range of 18. 
This makes the greatbow suboptimal despite having 1.5 times the draw weight of CHB/high (120lb to 80lb).
I would expect the greatbow to have not only greater range(keeping it as now, adding more range to it is probably not the best idea since 22 is a lot) but greater damage as well
# Describe the solution you'd like
This could be solved by creating a new ammunition type for greatbows that has greater damage and/or armor penetration. This would probably be the best since I cannot imagine a selfbow and a greatbow using same the arrow length.

# Describe alternatives you've considered
Changing the stab damage from 11 to 14-15.

# Additional context
I could take a poke at this since it seems like a easy first issue, but I would appreciate any feedback since I've never shot a modern bow

**Comment by kevingranade** [comment]
This is working as intended, the attribute you missed is that the compound greatbow is craftable, this gives another option for reaching the upper tier of bow damage, but suboptimally it requires higher strength to achieve the same damage output because it's a simpler and less refined design.

The compound greatbow represents a very high draw weight bow cobbled together from scrap parts, the compound hunting bow represents a modern highly tuned carbon fiber hunting bow that is many, many times more efficient at turning muscle power into arrow momentum.

The range is pretty much incidental, that could be set tot he same as the compound hunting bow.
