### ISSUE TITLE
[balance] [discussion] Plastic mold should be in more books

### ISSUE THREAD

**Issue by Xpyder** [CleverRaven/Cataclysm-DDA#45514]
pivoted from #45293
Problem:
Plastic molds are VERY widespread in recipes, making them on par with Hammer or Screwdriver but for electronics projects
But they don't spawn in the world
And the recipe only appears in a single book (so far as I can tell)

Based on the discussion in the other thread, general consensus is that this shouldn't be autolearned but that it's availability is perhaps more rare than it should be.

Currently it seems like adding it to more books is the preferred solution

**Comment by Xpyder** [comment]
As for which books perhaps we can cross reference electronics books for recipes that use plastic molds. That would give us a starting list from which we can pick sensible choices

**Comment by Xpyder** [comment]
Also as Kevin mentioned

> This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:
> 
> https://discourse.cataclysmdda.org/t/should-plastic-mold-recipe-be-in-more-books/25310/5

**Comment by I-am-Erk** [comment]
In the future I'd suggest just editing your initial post and title rather than making a new, almost identical issue that requires people to go read the previous issue.

**Comment by Xpyder** [comment]
Alright.  I just followed my usual protocol for Stack Overflow where they prefer you to make a new question so you don't confuse incoming people trying to match old posts to the new issue.

**Comment by PaulBlay** [comment]
Points per the discussion (not directly relevant to the 'more books' point):
* plastic_mold (as originally introduced) was only intended for simple recipes.
* there is no silicone, which is what led to the 'mould made of plastic being used to mould plastic' problem.
* clay (which was not available when plastic_mold was originally introduced) could now be used instead of plastic chunks when moulding plastic.
* Realistically, you make a mould for the particular item you are trying to craft. This means that 'found' plastic_mold items don't make much sense and making a stack of plastic_mold items to use later also wouldn't work.

**Comment by Zireael07** [comment]
For the latest point, this is exactly why the original mold item was limited to very simple things (bottles, bags and more molds ie. two halves of a clamshell mold).

The proper fix is most likely changing mold item to either clay or a new material 'silicone', and cutting down on amount of items using it (even a clay or silicone version won't do it for complex electronics)
