### ISSUE TITLE
Allow weapons to have a unique killmessage

### ISSUE THREAD

**Issue by dwarfkoala** [CleverRaven/Cataclysm-DDA#4562]
So, I was killing things with a plasma rifle and found the lack of VAPORIZATIONS and DISINTEGRATIONS to be saddening. I propose a system within the game where you can define within the jsons unique messages for the system to display.
In order to avoid disintegrations and vaporizations becoming boring after awhile, I propose that the game only displays the special weapon messages during a critical hit kill, and with a definable chance of occuring.
"messages" {
"message to be displayed", "chance",
}

So for my plasma rifle, i'd define something like

"messages" : [
{"message": "You vaporize the [insert monster here] with your plasma rifle!", "chance": "10" }
{"message": "The [insert monster here] is disintegrated by your plasma rifle!", "chance": "10" }
]
So then upon landing a critical killhit, the game has a 10% chance of displaying either message. If one message is displayed, the game does not check for another one, to avoid problems with defining more than 100% for a message and to avoid spamming messages. I propose this because the flavor possibilities are immense.

"messages": [
{"message": "One two, one two, and through and through, the Vorpal Blade went snicker snack!", "chance": "10"
]

"messages": [
{"message": "You blow the [insert monster here] to pieces with your BOOMSTICK!", "chance": "20"
]

"messages": [
{"message": "With your battleaxe, you sacrifice the [insert monster here] to ARMOK!", "chance": "20"
]

Though of course the reference possibilities are immense, if references are not wanted, then it can merely be used to add generic flavor to weapons. As it stands, weapons are generally only defined by the stats they have. Adding unique killmessages would be a way to make weapons unique beyond the stats they have and their names.

**Comment by mugling** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
