### ISSUE TITLE
A lighting is decreasing the illumination (cell phone problem).

### ISSUE THREAD

**Issue by 0x9conc1** [CleverRaven/Cataclysm-DDA#45670]
Indoor ~visibility~ illumination is reduced when the phone light is on.

Steps To Reproduce: in a dark room, compare visibility and visibility with the phone turned on, or:
1. Upload the attached [save file](https://github.com/CleverRaven/Cataclysm-DDA/files/5608748/save.zip) and jump in.
2. Turn on the phone light.
# Versions and configuration
- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version (upd: Windows 7 64-bit)
- Game Version: 0.E-7804-g98d7868 [64-bit] (upd: buld 11184)
- Graphics Version: Tiles
- Game Language: Системный язык [ ] (upd: Russian)
- Mods loaded: [
    Тёмные Дни Впереди [dda]
    [speed for dexterity] 
    [characteristics for skills]
]
# Additionally
Works on buld 11192.
Lol, works on E.0-2, - really nobody noticed this?

(I assume that this is illumination because, for example, an electrified zombie would be visible in the distance, or the screen of a working terminal, etc. otherwise I do not understand what is the visibility function that makes it work like this; or maybe it's some kind of local visibility)

Maybe connected: https://github.com/CleverRaven/Cataclysm-DDA/issues/44693, https://github.com/CleverRaven/Cataclysm-DDA/issues/44845.
# Update
https://github.com/CleverRaven/Cataclysm-DDA/issues/45670#issuecomment-735277934 --> https://github.com/CleverRaven/Cataclysm-DDA/issues/45670#issuecomment-735289856 <--
To sum up: the cell phone has weak lighting. Visibility disappears, although it should not have (probably because the terminal's effect, which is discussed in the discussion, works, but there should not be this effect and if it should be, then after turning off the light, for a short time - while getting used to the changed lighting). Possible incorrect interaction with the character's perception.

No one noticed, including me, that there was light from the phone screen. however most of the arguments remain relevant to the topic, so
# Expected behavior
No terminal effect
# Decision
Make the terminal effect only for a short period of time after turning off the telephone light, removing its imitation while the light is on, which right now looks like the effect of the terminal when you are near it (right now it is like as if we were looking at the phone and then looking around, being blinded). or just remove the terminal effect reducing visibility

**Comment by wapcaplet** [comment]
I guess you are referring to this effect, where having a light decreases your overall sight radius. No light (left) versus cell phone light (right):
![image](https://user-images.githubusercontent.com/238395/100476247-4f684200-30a2-11eb-8968-5d23c75986d6.png)

I believe this is a normal and intended effect, simulating how a bright light in the darkness will reduce your night vision.

**Comment by AnonimusC** [comment]
@wapcaplet I don't quite understand why light should reduce night vision: the radius of visibility should not change at all, because this is responsible for the performance of the eyes, which is constant as long as the character is healthy, but the lighting should make objects in the radius of visibility lit and distinguishable from other darkness, in the same radius of visibility.

**Comment by ZhilkinSerg** [comment]
Your eyes adapt to bright light and you start to see worse in dim light and darkness.

**Comment by AnonimusC** [comment]
@ZhilkinSerg What bright light are you talking about? About cell phone light? We do not blind our eyes, or the light is not so bright as to be reflected from surfaces and dazzle in us, reducing visibility, like the effect of white snow; in addition, even to the bright light from snow in real life, we gradually adapt and look at it without squinting; besides, even if the light were very bright, I still would not understand what effect you are talking about. right yesterday, when I was writing this post, it was dark in my room, I drew up the curtains and it became almost impossible to see anything, only rare outlines of objects near and far, then I experimented with a flashlight from the phone, and, of course, the effect, oh which you say I have not found.

 Well, imagine that you are standing in complete darkness - nothing is visible at all. Behind, far from you, a light began to burn, shining through your back, and in front you saw the outlines of a person, and if you step back even one step, you will no longer see him. Ok, you stand still, turn on the flashlight - and it disappears?!? !!?!? Or a more obvious example with a wall, the wall in front of you would just evaporate ??? Obviously, if such an effect existed, most likely, they would give it a name, it would be known to many people, and moms and dads would teach their children: do not turn on the light in the evening - you will see less, or something like: when you will run in the evening with a flashlight, don't run too hard, otherwise you won't notice how the wall will appear in front of you, although if the flashlight were turned off, he would see the wall?!?!

**Comment by ZhilkinSerg** [comment]
> 
> 
> @ZhilkinSerg What bright light are you talking about? About cell phone light? We do not blind our eyes, or the light is not so bright as to be reflected from surfaces and dazzle in us, reducing visibility, like the effect of white snow; in addition, even to the bright light from snow in real life, we gradually adapt and look at it without squinting; besides, even if the light were very bright, I still would not understand what effect you are talking about. right yesterday, when I was writing this post, it was dark in my room, I drew up the curtains and it became almost impossible to see anything, only rare outlines of objects near and far, then I experimented with a flashlight from the phone, and, of course, the effect, oh which you say I have not found.
> 
> Well, imagine that you are standing in complete darkness - nothing is visible at all. Behind, far from you, a light began to burn, shining through your back, and in front you saw the outlines of a person, and if you step back even one step, you will no longer see him. Ok, you stand still, turn on the flashlight - and it disappears?!? !!?!? Or a more obvious example with a wall, the wall in front of you would just evaporate ??? Obviously, if such an effect existed, most likely, they would give it a name, it would be known to many people, and moms and dads would teach their children: do not turn on the light in the evening - you will see less, or something like: when you will run in the evening with a flashlight, don't run too hard, otherwise you won't notice how the wall will appear in front of you, although if the flashlight were turned off, he would see the wall?!?!

You need to learn what ocular adaptation is.

**Comment by AnonimusC** [comment]
Sorry, I experimented yesterday in a dark apartment and didn't find anything like that

**Comment by ZhilkinSerg** [comment]
Go visit an ophthalmologist, I dunno.

**Comment by AnonimusC** [comment]
@ZhilkinSerg Can you give an example of the manifestation of this effect, or, more precisely, I am asking what kind of experiment should be carried out in order to stop seeing objects when the light is turned on, which would have been visible before?

**Comment by emptytriangle** [comment]
the effect is supposed to simulate the effect of not being able to see into a dimly-lit room when you are standing in sunlight, despite the fact that you would be able to see the contents of the room if you were standing in darkness.

An example of when it's supposed to take effect is when you are in darkness and you blast headlights into a group of zombies, then exit the rear of the car and sneak up from the side. The zombies will not be able to see you because they are blinded by the headlights. Or if you are looting the zombies inside the cone of the headlights, you would not be able to see a zombie approaching from the side in the darkness due to your being in the flood of light.

It doesn't work perfectly in all situations. For example, when standing next to a lit computer console you cannot see into the darkness despite the fact that your character hasn't necessarily been looking directly at the display. IRL you don't get blinded just from standing near a computer, you'd have to have been reading the display. But it does work more often than it doesn't because in CDDA if you're near the display you were probably there for a reason (using it to read by or looking at it).

#44693 and #44845 seem to be unrelated to this issue

**Comment by Zireael07** [comment]
Yep, and to add, you can make your night vision worse just by looking at a phone screen or using a flashlight (I can see pretty well at night, so paradoxically, using a flashlight is often more of a hindrance than help).

Other than personal anecdotes, there's this: https://en.wikipedia.org/wiki/Flash_blindness
At night, the dark-adapted pupil is wide open so flash blindness has a greater effect and lasts longer.

I believe my eye at night is wide open because I see so well at night (you could say I have Night Vision or even Full Night Vision trait IRL) so I can tell you I get really dazzled/blinded from a flashlight or phone, even when not looking directly at it.

**Comment by AnonimusC** [comment]
@emptytriangle , @Zireael07 Guys, I'm very glad of your activity on this topic, thanks! but still: we're talking about a ridiculously short distance of 2-3 steps from the character! and this is awful! Most likely (since I myself did not pay attention to it), this effect can worsen your perception of objects, for example, in the distance: imagine that we see some very dimly lit object in the distance and look at it for a long time, we gradually adapt and we can see its shape and shape better, and then we turned on the flashlight and look around, our eyes look at the illuminated objects and, perhaps, in this example, the object in the distance will really become worse visible, because the eyes, having received a signal from light to adjust from night vision, will perceive the shape of an object in the distance worse. Here we can cite as an example, say, snipers, or shooters in general, who, before aiming their eyes, with which they aim, are kept closed or behind a blindfold. But, again, these are damn short distances. Stand in a dark room and look around, and then turn on the light. Even a weak light source is enough to illuminate (more or less) everything within a radius of 10 meters, or even 15 and 20 meters, in complete darkness! And here there is no question of loss of visibility at such a distance - as I already wrote, all objects that we saw with night vision became illuminated, and therefore better visible, because we switched to a more efficient algorithm for analyzing objects from better lighting, or rather, requiring a smaller pupil size to obtain information from the object. The situation given on

Right now, while writing this, I turned away from the bright monitor and I needed to adapt for 2-5 seconds to the dim room, and I began to see all objects, and then I turned on the light from the flashlight on my phone and began to see everything much better (and you seem to imagine every time that turning on the light is the same as glowing the monitor in your eyes, but after all, there is just a weak reflection of light from objects).

so the situation in this image is just awful
![image](https://user-images.githubusercontent.com/73962707/100516670-90418300-3196-11eb-93da-dc13070e9c0d.png)

**Comment by AnonimusC** [comment]
and btw, visibility in the game generally works lousy: we should not see what is behind (you might say we're turning around, but still), in the dark we should see further and in general, see the whole room, but with the only difference that it is not lit. I mean, for example, go to a warehouse at night and shine a light there, and you will see, if you can't imagine now, that you will see the outlines of objects at least within 10 meters, faint but distinguishable, and what the game now looks more like a fog of war, associated, as in other games, with technical limitations, but now it is already 2013, at the time of the game's creation. Then it would be possible without the fog of war.or is it due to an underdeveloped noise system, lack of stealth skills and all that is difficult and long to implement, I assume (there is no noise on walking on a wooden floor, on snow, on glass, if it is not glass specially laid out by us, etc.) ((sorry, I am not familiar with how the noise system is developed, I can be wrong))

**Comment by AnonimusC** [comment]
resume: all objects that we saw with night vision became illuminated, and therefore better visible, because they are illuminated 
(after deadaptation of the eyes for 2-10 seconds, I believe (the further in the dark the longer))

**Comment by AnonimusC** [comment]
or, if on the other hand, the game has a ridiculously small radius of illumination from a candle (although I didn't check with it) and from a cell or mobile phone.

**Comment by Zireael07** [comment]
@AnonimusC: >  all objects that we saw with night vision became illuminated, and therefore better visible, 

You assume our night vision range equals the flashlight/light source range. That is not necessarily the case, neither IRL nor in-game.

> we simply do not have the direction of view, face, in the game.
We don't, and it's not planned (too much complexity - many literal corner cases - and too unituitive for the average player - I haven't seen a top-down 2D game that communicates view direction well)

**Comment by AnonimusC** [comment]
@Zireael07 Yes, you're right, but I didn't conclude that. I'm talking about the case in the post.

I understand that you don't plan to. by the way, I saw this at project zomboid and at unreal world.

**Comment by AnonimusC** [comment]
Okay, guys, due to the abundance of text, in order to save you time, I will try to make a shorter summary, I hope, an ultimatum, because you have no reason to disagree with him.

# Describe the bug
0. When you turn on the light source, the object in the visibility radius disappears, although this should not have happened, because since we saw the object, light emanated from it, and when we turned on our light, the light that came from the object did not go anywhere and we can see it. Perhaps someone will say that we have lost the ability to night vision of a poorly lit object, but this is not so: even with the light on, we can concentrate on that object and see it, partially remaining in night mode, because the light does not blind our eyes like this strong enough to block off any light from it, as the light from a street lamp in the form of a halo would shine, blocking your view of the wires going to the pole, or the trees nearby. And the reflected light from the phone's flashlight is not strong enough to turn off the night mode completely. [Also, it's a little difficult to talk about a phenomenon that is rarely seen in everyday life - the light source spreads the light much further than in the game; more on this later]

Perhaps it would be better to start like this at all:
1. Due to the limitations imposed by the foundations laid at the beginning of the development of the game (apparently), the light spreads around the character, and not in the form of a cone or other shapes, and if we had imagined how much the light spreads from the irl phone, we would immediately understand that With the current lighting implementation, we would have to make the phone light within a 5-7 radius of the player, which would look completely absurd in an open area, because the illuminated area around the character would be gigantic due to this rounded shape of lighting.
2. Perhaps, in this regard, the game has very weak and unrealistic lighting from a phone flashlight and, possibly, a candle (and other faint glowing objects). Okay, just the shape of the lighting, but we are still talking about a very small radius. On this topic could be moved to the category of proposals and closed on this, if the light did not reduce visibility.
3. For some trait, the character has basic visibility in the dark, which is impossible without light reflected from objects, because night vision implies, in the case of a person, and not as a superpower, to receive more light from the same points in space due to pupil dilation - the size of the light penetration area. Of course, we can say that light enters a dark room from cracks and all that, but it is clear that these are excuses. When a character sees objects around him in a dark basement, and does not walk and touch each object by touch, this is absurd.
4. By linking 2 and 3, for some reason, this basic visibility decreases when you turn on a light source that is as weak as the flashlight from the phone in the game.

# Expected behavior

The light shouldn't spread like that. The light from the flashlight should be greater than the visibility from point 3 during the absolute absence of other light sources.

# Decision

Increase the illumination of such light sources at least to the basic visibility, which was discussed in paragraph 3. But it would be more logical to swap them.

# 
I would like the statement that an object within a 3-step radius, becoming invisible due to the inclusion of light, would be the only argument, and still do not understand why you disagreed with it and / or did not designate the topic as a bug.

**Comment by Zireael07** [comment]
CDDA tile has no defined size and never has had one, why are you saying that cellphone light range should be 5-7 tiles?

**Comment by AnonimusC** [comment]
@Zireael07 Sorry, I should have been more specific: comparing the lighting from my nokia phone of some kind, push-button, with the distance that the light extends between the open door of the room and the kitchen through the corridor, I estimated that its light is enough to illuminate about 3-4 sofas in the distance, so that they are clearly distinguishable with objects on them, 3-4 sofas each 2 meters. Somewhere 6-8 meters of reliable lighting. Then I looked at the sofas in the game and estimated that 1 tile = 1 meter, looking at the size of the sofa, because sofas are occupied by people along their length from the pillow to almost the edges.

**Comment by AnonimusC** [comment]
Perhaps everything is very simple, but for other reasons: the whole thing may be in the incorrect interaction of perception with weak light (or even with light) (hereinafter, the light everywhere in this message is from a cell phone) So, a character with perception 4 in the basement with the light seen within 1 (without light 0), in the room above - in a radius of 3, with light or without light, only the tile where we stand and within 1 become lighter, and the range has not increased (it should not be the inclusion of light should increase the radius of visibility)
with perception 14, a character in a basement with light saw within a radius of 1 (without light 4), outside the basement in a building with light saw within a radius of 3 (without light 5).
of course, this should not be the case. It must be that we see more with light than without light sources. Apparently, the game always simulates this effect, the effect of looking at the terminal, as if this light makes us unaccustomed to the darkness around us, but this is not so, because it is not a light shining directly into our eyes.

A character with perception 4 is only seen by the tile that is standing on, if no light at all, in the basement, and this is similar to how things should be. okay, perception increases visibility as such, this can be taken for granted, but the way it interacts with light is more like simply that the interaction of perception with light sources, at least such small ones, is not clear.

Indeed, the terminal simulates this effect, as if we are looking at the terminal and we get used to the darkness, which we will need to quickly get used to again. everything is OK here , as if we are looking at a terminal that blinds our eyes. I was also pleased that if you walk for a long time with the light in the basement with a good perception, when the light is turned off, visibility drops to a radius of 2, and then increases to 4 - I was pleased with the simulation of weaning from light and getting used to the dark, but I was not pleased that it should not be here, because there is no terminal effect

**Comment by ZhilkinSerg** [comment]
Just so you know - the light always shines into your eyes. That is basically how you see.

**Comment by AnonimusC** [comment]
@ZhilkinSerg Yes it is. You might assume that I know this, because I already wrote
- the lighting should make objects in the radius of visibility lit and distinguishable from other darkness
- imagine that you are standing in complete darkness - nothing is visible at all
-  if you step back even one step, you will no longer see him (you block the light from behind)
- etc

maybe you assumed it because of this:
- the eyes have fully adapted to the dark, turning on the light will only give a signal that it is not necessary to use large brain resources to obtain information with the help of the eyes - because the same objects that the eyes saw in the dark due to eye adaptation now made visible by light.

 but there were more arguments in the other favor, and there I should have written: from more light (not from light at all)

besides, what are you talking about?

**Comment by LeahLuong** [comment]
Not much of a suggestion & barely a discussion but I suppose it needed _**some**_ kind of tag after being inactive for over a year. Truly arduous getting to this point in the thread & I don't know whether to admire or pity you if you read everything above. Still, I think OP has a point (if only an extremely circuitous, long-winded 1): weak light sources like video screens or candles prob shouldn't impact night vision as much as they do.

Cell phones as flashlights in-game are worse than useless because they tend to highlight you while simultaneously decreasing your ability to see further. Fighting in darkness near lab consoles is needlessly hazardous; 1 instinctively wouldn't look @ the screen if perceived danger was near because of its effect on night vision.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
