### ISSUE TITLE
Missing New England foods

### ISSUE THREAD

**Issue by emptytriangle** [CleverRaven/Cataclysm-DDA#45716]
#45680 has me thinking about common New England foods that are missing from CDDA.

Here's a list I came up with off the top of my head, feel free to add to it:

- New York System weiners (and associated diners - should be somewhat rare)
- crab cakes (small stands / food trucks? Especially in amusement park-type locations)
- oyster crackers should be common in kitchens, especially near clam chowder
- Boston Baked Beans candy in gas stations and/or vending machines
- American Chop Suey dish crafted by player out of pasta, unprepared tomatoes (raw/canned/etc) and sundry spices and crunchy vegetables (celery, peppers, etc.)
- Hoodsie Cup ice cream in ice cream trucks and gas stations
- quahogs and stuffed quahogs ("stuffies")
- rhubarb plants and rhubarb pie recipe, also sweet rhubarb from dipping stalk directly in sugar before eating
- frozen lemonade
- Johnny cakes (pan-fried cornmeal biscuits)
- lobstah

**Comment by Xaleth** [comment]
Brooklyn pizza

**Comment by hjk321** [comment]
I don't think the foods should be brand name, but generic versions of these would add a lot of flavor to the setting. For example, the Boston Baked Beans candy would just be "baked-bean flavored candy" and Brooklyn Pizza would just be "brooklyn-style pizza."

If there aren't any objections, I'll go ahead and begin implementing these before the 0.F content freeze. If more regional foods get added here before I finish I'll add those too.

**Comment by emptytriangle** [comment]
maybe "Boston-style candy coated peanuts"

**Comment by hjk321** [comment]
Skipping american chop suey because it is too similar to hamburger helper, Hoodsie ice cream because the only differentiating factor from regular ice cream is the brand name, and rhubarb pie because rhubarb is already one of the ingredient choices for fruit pie. Lobster already exists, and quahog clams are already in the game in canned format. Everything else here has been added (including the stuffed clams) and I'm working on finishing up recipes, itemgroups, etc. Let me know if the reasoning behind any of my exclusions is faulty.

**Comment by emptytriangle** [comment]
Can we have an "ice cream sundae cup" that contains 3oz of ice cream? That should satisfy the actual novelty of the item and leave out the brand name.

It would be awesome to have quahogs you can dig up on a sandy beach to cook yourself but that sounds like it should be its own PR at a later time

**Comment by DalenTalas** [comment]
Latkes.
