### ISSUE TITLE
Corrupted save after updating. Overhauls the whole area

### ISSUE THREAD

**Issue by scraw-darkblade** [CleverRaven/Cataclysm-DDA#45734]
Corrupted save after updating. Overhauls the whole area

#After updating received couple of errors and when I loaded my game, It was a different area.
It is dark that time (like 4:00AM) and as you walk and discover the previous tiles it is replaced by new one's. Items that are supposed to be there is also removed.

Eg: Shrub that was supposed to be there (You can see it on unseen status, and when you walk to check it, it is gone. replaced by other tile. 

# Steps To Reproduce

1. Update the game from the recent one. 
2. Load the game.
3. Walk as you see terrain is changing while doing so.

# Expected behavior

It should work as it is no changes on tiles or any kind of change without manipulation by character, monster/NPC or natural occurences.

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-7938-g8736e6b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]
  

# Additional context

Limitations:
I am not able to check the whole world if it changed as well.
I am not able to load the previous save (forgot the build) but I provide both save.
[debug (New).log](https://github.com/CleverRaven/Cataclysm-DDA/files/5614806/debug.New.log)
[debug (old) .log](https://github.com/CleverRaven/Cataclysm-DDA/files/5614807/debug.old.log)
[Errors after update.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/5614808/Errors.after.update.txt)

**Comment by scraw-darkblade** [comment]
[save (new).zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5614873/save.new.zip)
[save (old).zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5614876/save.old.zip)

**Comment by ZhilkinSerg** [comment]
If you will try to load your savegame in a previous game version (that worked properly previously) and it won't work that would mean your files are corrupted and there is nothing wrong with new game version.

Corrupted savegames is an issue in your environment we cannot help you with besides suggesting to do backups regularly.

**Comment by jeremyshannon** [comment]
I found a bug that had similar effects to this on the last stable. There, it turned out that since my map was unreasonably large (over 1,000 overmap tiles from 0,0) that a change in formatting had removed commas from the map save format, causing it to not find the saved map contents and instead regenerate them.
 I'll try to take a look at your save soon and see if I can see what the problem is.

**Comment by ZhilkinSerg** [comment]
> 
> 
> I found a bug that had similar effects to this on the last stable. There, it turned out that since my map was unreasonably large (over 1,000 overmap tiles from 0,0) that a change in formatting had removed commas from the map save format, causing it to not find the saved map contents and instead regenerate them.
> I'll try to take a look at your save soon and see if I can see what the problem is.

Your issue is not a bug, it has nothing to do with current issue (and also has nothing to do with commas/formatting - nothing has been changed in that department recently). Thing is your overmaps were last opened and saved in older game version and contain overmap terrains that are no longer in game. Affected overmaps need to be migrated in `0.E` stable prior to loading them in `0.F` stable, because migration code for most old migrations was removed post-0.E (#41241).

**Comment by jeremyshannon** [comment]
Dude, I think you missed a couple of things. First, I was referencing a bug in the save code I discovered before 0.E was released, which was related to commas. (Whenever we get close to a stable release I try to dig up save migration bugs, because nobody wants those to slip in) That bug was verified and patched and has been closed for like a year. I mentioned it in passing because it resulted in the same kind of erroneous behavior from the game, so I figure there might be some similar problem happening.

 Second, the issue I currently have open IS a bug, or rather a defect in the design of the save migration code, which only performs a partial migration of saved map tiles, leaving unmigrated tiles around to error out in future versions. Thus I am getting obsolete migration errors in maps that were saved in experimentals AFTER 0.E stable. I guess maybe I could edit that bug's top post to make that all more clear?
 I understand dealing with people's dumb bug reports can make you grumpy and all, but slow your roll a bit.

**Comment by ZhilkinSerg** [comment]
> 
> 
> Dude, I think you missed a couple of things. First, I was referencing a bug in the save code I discovered before 0.E was released, which was related to commas. (Whenever we get close to a stable release I try to dig up save migration bugs, because nobody wants those to slip in) That bug was verified and patched and has been closed for like a year. I mentioned it in passing because it resulted in the same kind of erroneous behavior from the game, so I figure there might be some similar problem happening.
> 
> Second, the issue I currently have open IS a bug, or rather a defect in the design of the save migration code, which only performs a partial migration of saved map tiles, leaving unmigrated tiles around to error out in future versions. Thus I am getting obsolete migration errors in maps that were saved in experimentals AFTER 0.E stable. I guess maybe I could edit that bug's top post to make that all more clear?
> I understand dealing with people's dumb bug reports can make you grumpy and all, but slow your roll a bit.

What's your point?

**Comment by jeremyshannon** [comment]
What was yours?

**Comment by jeremyshannon** [comment]
All that nonsense aside, your "old save" zip appears to have suffered file corruption. Right away I discovered that #J0NoaWVmJyBTY3JhdyB0aGUgVG9ybWVudG9y.ano.json contains garbage. You might want to back up your files because you may have hard drive problems.
 It looks like this is not CDDA's fault.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
