### ISSUE TITLE
Asthma instakill bug

### ISSUE THREAD

**Issue by wether94** [CleverRaven/Cataclysm-DDA#45753]
# Describe the bug

Asthma instakill bug

# Steps To Reproduce
1. give yourself asthma mutation
2. give yourself an inhaler
3. overdose on epiph...something injector, two or three doses should do it
4. wait until you get an attack
5. die

# Expected behavior

if i use inhaler asthma sould be gone

# Screenshots

https://media.discordapp.net/attachments/598523535169945607/783280595139690496/unknown.png?width=1204&height=677

Do not take a screenshot of the crashing window. Please provide the crash logs in the "Additional context" -->

# Versions and configuration

0.E-7871-gdf17a62 build 11190

**Comment by XygenSS** [comment]
Reproduced on latest experimental

**Comment by LickornoRerovana** [comment]
The bug happens when you reach 73 Stims or above, and will stop once Stims reach 72.

**Comment by wether94** [comment]
got last moments before death screenshots:
![image](https://user-images.githubusercontent.com/75308718/100771302-53cc8c00-340f-11eb-8739-b50c1ccaf253.png)
![image](https://user-images.githubusercontent.com/75308718/100771340-62b33e80-340f-11eb-90bb-4f98e65dbbf7.png)

**Comment by Fosheze** [comment]
Maybe I'm misunderstanding the bug here but the inhaler is a stimulant, if you are already majorly overdosing on stimulants using it should kill you just like using any other stimulant in that state. 

The only undesirable part I can see here is that using the inhaler is an automatic action. Maybe an "are you sure" prompt should be shown for inhaler use when the character is already suffering from stimulant overdose. It would probably even be a good idea to have a prompt whenever using the inhaler would cause an overdose so that they can choose to not use the inhaler and not overdose.

**Comment by LickornoRerovana** [comment]
The problem is that once Stimulants reach 73 (or above), an asthmatic character will have an asthma attack every second. If they have an inhaler, they will use 1 charge of inhaler per second until they run out, where the character dies in 10 seconds. Stimulants increase chance for asthma attack per turn, so it seems the number 73 completely messes that up and makes that chance 100%.

**Comment by Fosheze** [comment]
> The problem is that once Stimulants reach 73 (or above), an asthmatic character will have an asthma attack every second. If they have an inhaler, they will use 1 charge of inhaler per second until they run out, where the character dies in 10 seconds. Stimulants increase chance for asthma attack per turn, so it seems the number 73 completely messes that up and makes that chance 100%.

Hmm. That is strange. I'm no doctor but a quick google search doesn't turn up anything for stimulants triggering asthma attacks. I found this site https://www.aafa.org/medicines.aspx which lists a variety of drugs that can trigger an attack however none of them are stimulants and I have seen a couple of sources say that caffeine helps with asthma (although many more reputable sources say it has no effect).

So it sounds like the stimulants causing asthma attacks should probably be revisited.

**Comment by actual-nh** [comment]
Anything increasing epinephrine levels should have positive effects on asthma, if anything. As another example, theophylline (closely related to caffeine) has been used as an asthma treatment. (On the other hand, it isn't safe for any asthmatic to take some blood pressure drugs like beta-blockers.)

In other words, stimulants should not be increasing the likelihood of asthma - but it **_is_** realistic to have asthma inhalers having stimulant side effects.

**Comment by Fris0uman** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/e7658fabe47669b945154ad809ff0a66957c5704/src/suffer.cpp#L611

`Stim` is currently the only trigger for asthma attack, we can remove it from the equation but then it becomes random so we would need something else to set the frequency of attacks.

**Comment by satheon49** [comment]
Shouldn't stamina level or stamina regeneration affect the chance of asthma attacks since they relate to breathing? Granted loosing stamina is a very frequent occurrence so its influence shouldn't be too high but it seems appropriate.

This would also give stimulants a positive effect on preventing asthma attacks since they keep the stamina level higher/increase stamina regeneration.

**Comment by actual-nh** [comment]
If the air is cold or dry (not uncommon in New England!), being very active in it (as in high activity level) is a definite asthma trigger for most (including some who don't have allergic asthma - pure exercise-induced asthma).
