### ISSUE TITLE
Sawing down the barrel of a Barrett anti-materiel rifle doesn't change its length

### ISSUE THREAD

**Issue by sdpillen** [CleverRaven/Cataclysm-DDA#45806]
A Barrett anti-materiel rifle, before sawing it, has a length of 57 inches.  Sawing the barrel using a hacksaw does not change this value.

# Steps To Reproduce
1. spawn a barrett
2. note the length of the barrett
3. spawn a tool that can saw barrels
4. saw the barrett
5. note the unchanged length

# Expected behavior

I'd expect it would saw down the barrel at least a few inches.   Apparently barretts are manufactured with 20 inch barrels, but the length in-game assumes a 29 inch barrel.  Perhaps custom sawing would shave off even more., but being able to shave off at least 9 inches would be nice.  That would make it 48 inches.

# Screenshots
Before:
![image](https://user-images.githubusercontent.com/13488324/101170502-db4c1200-363e-11eb-85e6-235718235a1a.png)

After:
![image](https://user-images.githubusercontent.com/13488324/101170406-b3f54500-363e-11eb-865b-6203631218f9.png)

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.E-8007-gf58e7a4
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: Aftershock, Magiclysm, Blaze industries, Mythical Martial arts, No NPC needs, Bionic Professions, Stats through skills, Graphcal Overmap, Graphical Overmap Cataclysm no trains, no shrooms, 
 -->

**Comment by Fosheze** [comment]
@sdpillen The "M107A1 CQ" has a barrel length of 20 inches however the rifle represented in-game is the standard M107A1 which does have a barrel length of 29 inches IRL See below.
https://barrett.net/pdf/products/M107A1/M107A1-Manual.pdf

As far as actually sawing it down goes it should be possible though. Listed Barrel length is 29 inches and from looking at the diagrams it looks like about 70% of that barrel length actually extends outside of the main rifle body to where it "could" be cut off so you "should" be able to reduce the length by as much as 20 inches. Firing the rifle in that state IRL would absolutely terrify me but it should technically maybe be somewhat possible and in game I could see it making an excellent door breaching tool. 

As a side note large rifles like this are able to be taken apart for transport IRL. The take down length of this particular rifle is 41.375" at it's longest. It would be interesting if we had the capability to actually tear these down for transport in game but I am aware that that is outside the scope of this issue.

**Comment by sdpillen** [comment]
@Fosheze  Oh yes, the way I worded the expected behavior was a little ambiguous.  I meant to say, "the barrels come in both 29 and 20 inch variants, and since in game the 29 inch variant is used, at bare minimum cutting it down to 20 inches should be possible".

I'll take your word on the stuff about cutting it down deeper than that, I have no serious knowledge of gun modification.

**Comment by emptytriangle** [comment]
I imagine if you actually sawed down the barrel of a Barrett you'd end up reducing the range by around 75% and would probably be launching lethal clouds of unburned propellant at ludicrous speed in addition to your bullet

**Comment by Fosheze** [comment]
> I imagine if you actually sawed down the barrel of a Barrett you'd end up reducing the range by around 75% and would probably be launching lethal clouds of unburned propellant at ludicrous speed in addition to your bullet

As I said, Absolutely terrifying. Main issues are that this would dramatically decrease bullet velocity, cause increased flash, cause increased report, likely cause the bullet to tumble through the air rather than flying properly (this could actually increase damage due to leaving a larger wound), absolutely butcher the range, and, most importantly for this particular rifle, increase recoil. Considering that the recoil dampening built into the barrel on this gun is designed with that longer heavier barrel in mind I doubt it would be doing much dampening at all. I'm not sure about the physics that go into recoil dampening but, per the manual I linked earlier, the dampening springs in the barrel are rated at 70 pounds so there is likely going to be a whole lot more kick without them working properly.

Of course I can't find any information about how this particular rifle performs when sawn down (probably because no one want's to ruin that expensive of a gun) but I do know that sawn down Mosin-Nagant rifles (chambered 7.62 for those who aren't familiar) were fairly common as close range weapons during the Russian civil war. They were called Obrez and some were cut so short that the total "rifle" length was under 1 foot. That makes it basically just a rifle chamber with a grip and a trigger. If you can saw something chambered in 7.62 down to essentially nothing and fire it like a pistol then sawing something chambered in .50 down to 9 inches and leaving the stock intact "shouldn't" maim you when you shoot it.

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/sawn-off-shotgun-length-was-not-reduced-after-sawing-barrels/25481/2
