### ISSUE TITLE
Friendly NPCs count as impassble obstacles when sorting loot with zones

### ISSUE THREAD

**Issue by ElfLeaderMike** [CleverRaven/Cataclysm-DDA#45859]
# Describe the bug
When using a larger Unsorted Loot zone to consolidate loot from a building, the sorting will suddenly stop and say "You can't reach the source tile". This will occur if your friendly NPC stands in the doorway and traps you in the room like a creep.

# Steps To Reproduce

Create a large unsorted loot zone covering a building with multiple 1 entrance rooms
Create a custom loot zone with no filter somewhere nearby
Put items in each room
Have a friendly NPC following you closely
Attempt to sort and watch as they follow you and eventually trap you in a room mid sort

# Expected behavior
When sorting, the player should autoswap positions with the NPCs to get past them and they should not be considered impassable objects.

# Screenshots
![image](https://user-images.githubusercontent.com/22645231/101273762-522ffa80-3766-11eb-87e4-ab7285ca5cec.png)
Footage of sorting starts here
https://www.twitch.tv/videos/826886370?t=0h54m31s

# Versions and configuration

- OS: Windows
- OS Version: Windows 7 Professional 64-bit
- Game Version: 0.E-7938-g8736e6b [64-bit]
- Graphics Version: Tiles
- Game Language: English
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

# Additional context

There also seemed to be points where my character gave up grabbing certain items but did not seem to stop sorting other items. Almost as if he gave up trying to get to some of them. So they're definitely a little janky.

**Comment by PatrikLundell** [comment]
A potential problem with auto position switching is that if you've asked the companion(s) to sort loot and then start to sort loot yourself switching positions might put the companion out of reach of the loot they're trying to sort, and if companions get auto swap as well you could get into situations where all that's happening is that the characters involved switch places with each other, rather than achieving anything.

Loot sorting is a bit odd, with seemingly random stops to the sorting process, where a new sorting order may well continue.
- Full zones result in such items not being sorted. That's not unreasonable.
- Zones are subject to the 60 tile reality bubble range. That means companions sorting concurrently with the player can result in some things getting outside of the bubble. Similarly, things that were in the bubble when the sort list was created might be outside of the bubble at the location the player is at at the time that item has been reached in the list. These are behaviors resulting from the reality bubble implementation. It wouldn't be trivial to work around those issues (for the PC sorting, it might be possible to order the PC to move back to the location where the sorting action was initiated to get items back in range if an item to be sorted is found not to be in range, but give up on that item if no valid target zone was found in range from the item).
