### ISSUE TITLE
Carrots and Onions should be plantable as-is

### ISSUE THREAD

**Issue by narkiel** [CleverRaven/Cataclysm-DDA#45890]
# Is your feature request related to a problem? Please describe.
Certain food items (carrots, onions, broccoli) do not have craftable seeds.  This makes sense from a realism perspective, as those food items do not have seeds in real life.  However, this makes such foods disproportionately and unrealistically difficult to farm. Carrots and onions in real life will grow on their own if replanted.  The subsequent plant produces multiple seeds which could then be planted.

# Describe the solution you'd like
Give carrots and onions the Plantable_seed flag.  Make harvesting produce both vegetables and seeds, if it does not already.

# Describe alternatives you've considered
Alternative solutions include making the seeds craftable , or creating something like Seed Potatoes.  This would address the game balance issues but would reduce realism, and are thus not recommended.

**Comment by anothersimulacrum** [comment]
They should have craftable seeds, instead of being plantable directly, so you can set them aside for planting explicitly and not consuming (like potatoes).

**Comment by ZhilkinSerg** [comment]
I am pretty sure carrots are grown from real seeds. You can possibly stick taproot into mud and it would possibly grow seeds the next year, but it does not sound too efficient.

**Comment by narkiel** [comment]
> 
> 
> I am pretty sure carrots are grown from real seeds. You can possibly stick taproot into mud and it would possibly grow seeds the next year, but it does not sound too efficient.

Inefficiency is fine.  It just doesn't make sense for the lategame to be devoid of carrots.

**Comment by emptytriangle** [comment]
You can just buy carrot and onion seeds at the hardware store in new england, home depot and lowes have them. Regardless of whether it's changed so you can plant raw carrots and onions, carrot and onion seeds should exist and should be in the hardware store spawn tables.

**Comment by ZhilkinSerg** [comment]
> 
> 
> You can just buy carrot and onion seeds at the hardware store in new england, home depot and lowes have them. Regardless of whether it's changed so you can plant raw carrots and onions, carrot and onion seeds should exist and should be in the hardware store spawn tables.

Carrot and onion seeds already exist and are spawned in stores.

**Comment by PatrikLundell** [comment]
It sounds reasonable to be able to plant roots to get seeds (and it shouldn't take longer than when planted from seeds to get to the harvest stage. The simplest would be to just have it take the same amount of time and ignore that the "seed" roots probably wouldn't be very tasty by that time, and so you'd just get a normal harvest, allowing the game to not make any distinction between the sources). However, you'd probably need quite a few roots to get a farm plot's worth, so you can't just plunk down a single carrot.

**Comment by DalenTalas** [comment]
Hobbyist gardener here. Carrots are indeed grown from seed, and can be left to flower for seed harvesting. Same with onions. So, both plants should drop seed when harvested.

Onions can actually be regrown from scraps. For the purposes of the game, it can be abstracted into being able to craft "seeds" from it. See [here](https://www.mrshappyhomemaker.com/15-foods-that-can-be-regrown-from-scraps/).

Garlic easily propagates from cloves. So, if that's not already implemented, cloves may count as garlic seeds.

Potatoes can be cut up and planted as well. This is where "seed potatoes" come from. They can propagate through seed, but the roots are usually harvested before the plants flower, so that the nutrients do not get wasted on them.

Carrots, on the other end, are not like onions or potatoes. They WILL regrow the PLANT part (the stem, the leaves, and the flowers eventually growing into seed) from the scrap of the root. However, the ROOT itself, the part that's actually eaten, will not regrow. See [here](https://www.gardeningchannel.com/carrots-regrown-from-tops/).

With the above in mind, I am of the opinion that changing the way carrots behave in game to match how they behave IRL will require:
1) Creating the "carrot scrap" item craftable item.
2) Implementing the new "scrap carrot" plant that only drops carrot seeds when harvested.

Which, IMVHO, does not make sense.

**Comment by narkiel** [comment]
> 
> 
> Hobbyist gardener here. Carrots are indeed grown from seed, and can be left to flower for seed harvesting. Same with onions. So, both plants should drop seed when harvested.
> 
> Onions can actually be regrown from scraps. For the purposes of the game, it can be abstracted into being able to craft "seeds" from them. See [here](https://www.mrshappyhomemaker.com/15-foods-that-can-be-regrown-from-scraps/).
> 
> Garlic easily propagates from cloves. So, if that's not already implemented, cloves may count as garlic seeds.
> 
> Potatoes can be cut up and planted as well. This is where "seed potatoes" come from. They can propagate through seed, but the roots are usually harvested before the plants flower, so that the nutrients do not get wasted on them.
> 
> Carrots, on the other end, are not like onions or potatoes. They WILL regrow the PLANT part (the stem, the leaves, and the flowers eventually growing into seed) from the scrap of the root. However, the ROOT itself, the part that's actually eaten, will not regrow. See [here](https://www.gardeningchannel.com/carrots-regrown-from-tops/).
> 
> With the above in mind, I am of the opinion that changing the way carrots behave in game to match how they behave IRL will require:
> 
>     1. Creating the "carrot scrap" item and corresponding recipe.
> 
>     2. Implementing the new "scrap carrot" plant that only drops carrot seeds when harvested.
> 
> 
> Which, IMVHO, does not make sense.

What would be the gameplay or realism benefit of creating a "scrap carrot" item instead of just letting you plant the whole carrot?  

Also, to clarify my initial proposal: I don't expect you to be able to harvest more actual Carrots besides the original from what you plant in this way; harvesting a carrot plant should produce only 1 carrot but also multiple seeds.  Such that, starting from carrot seeds, you can start a garden right away, but starting with just Carrots, you'll have to spend a season producing seeds.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
