### ISSUE TITLE
Don't switch advanced inventory panels when you re-select them

### ISSUE THREAD

**Issue by Raikiri** [CleverRaven/Cataclysm-DDA#45900]
# Is your feature request related to a problem? Please describe.
Assume I want to open adv. inventory with [4] on the left panel and [6] on the right panel. So I open the adv. inventory, left tab is highlighted, I press [4], then right, then [6], done. However, if when I opened the inventory, [4] was already on the left pane, when hit [4], it instead switches panes, and now my left pane is whatever used to be there on the right one instead of [4], and from this point it screws things up because I have to look intently which pane it actually selected vs what I was planning to select, filters get swapped as well, etc etc.

Another scenario: assume I wanted to open adv. inventory with "all" on the left. I open the inventory, hit "a", but turns out, "all" was already on my right pane, so I end up swapping panes. In general this does not sound terrible, but my right pane had a filter like "CBM, chain, oxy, auto" from previous time I was managing it, and now I have to notice that the filter has moved to the left pane, either purge it or swap panes again, lots of extra actions that should not have been there.

This behavior prevents muscle memory from working because when selecting panes, you need to actively pay attention to which panes there currently are and make sure to not accidentally try to switch to a pane that's already selected.

I understand that having the same left and right pane makes no sense and so instead of dealing with this problem when player tries to select them like that, they're switched instead. Boom, easy implementation, problem solved. However, this behavior requires visual feedback from actions where it should not be needed.

Another example of a similar menu is Total Commander, Norton Commander and other such file managers and all of them allow opening left and right panes to the same directory even though it does not make much sense from file management perspective.

# Describe the solution you'd like
Actually allow opening both panes targetted to the same tile. Just ignore item moving commands because moving item from tile to the same tile indeed makes no sense.

# Describe alternatives you've considered
I also tried using default layout to make sure that adv inventory is opened to some panes that I rarely use (like 5, 5[vehicle]), but problem still exists if I want to change panes later. I have also tried the option that resets adv inventory layout after every operation, but it has proved extremely annoying to move multiple items with that option on because AIM resets its state after every single item moved. This seems like an unrelated bug outside of the scope of this issue.

# Additional context
Depending on others' perception of this swapping feature, maybe we don't even make it an option, but just change the behaviour instead. Maybe some people use it, I don't know, but surely not me.

**Comment by Raikiri** [comment]
Wow, that was fast

**Comment by satheon49** [comment]
Well it is a pain point of mine too.

**Comment by Davi-DeGanne** [comment]
This is not a bug, it is intentional. See [this comment](https://github.com/CleverRaven/Cataclysm-DDA/pull/34502#issuecomment-539267948) by @esotericist and #645 where the feature was added, on the basis that it is consistent with ncurses apps as a whole.

More subjectively, eso is not alone, I also am very used to this feature and use it intentionally quite frequently. You mention lack of consistency for your muscle memory; I'd like to point out the menu option "Open default advanced inventory layout" which could solve this problem nicely. This way you could have your consistency, and even learn to utilize this feature to your advantage (for example, to open and quickly move everything from position 4 to position 6 would be: [/] -> [6] -> [6] -> [4])

I'm not active enough anymore to feel like I have authority to explicitly veto this, but I would personally be very annoyed by this change, and I really doubt I'm the only one. Perhaps a menu option to toggle it off would be a solution that appeases both sides, but IIRC @kevingranade has historically been averse to haphazardly adding menu options.

**Comment by andrei8l** [comment]
> and #645 where the feature was added, on the basis that it is consistent with ncurses apps as a whole.

I think you linked the wrong PR. Can you also give an example of a curses (or similar) app that auto-swaps windows? The ones I'm familiar with don't auto-swap anything (notably `mc` which is somewhat similar to the AIM). Is common curses behaviour even relevant to CDDA if our other UIs don't auto-swap windows?

**Comment by Davi-DeGanne** [comment]
Well, I didn't link the wrong PR, I just misunderstood that PR when I read it. Sorry, didn't intend to spread my confusion. I think my other point still stands though, but if my voice ends up being only dissenting one, then I can always be safely dismissed as a crazed lunatic clinging to the old ways :slightly_smiling_face:

**Comment by Raikiri** [comment]
@Davi-DeGanne 
If this behavior was consistent with ncurses apps, then in MC/NC if you tried to cd into a directory that's already selected into the current panel, it should have swapped panels. Obviously nobody does that as it would be unintuitive, however, this is exactly what happens in CDDA right now.

**Comment by emptytriangle** [comment]
I don't like the panel switching when you press its number, and I would like to turn it off. But I don't think this change should be forced on players who don't want it.

**Comment by satheon49** [comment]
I would be fine with adding it as an interface option but I really don't understand why it is necessary.

I have added 'x' as a keybind to AIM that allows swapping tabs no matter what is displayed.
What is easier?
Making the decision to swap tab, then looking at the square displayed in the inactive tab and then pressing that key
OR
Making the decision to swap tab and press 'x'.

I mean even if you use the functionality of swapping tabs this change makes that easier too.

**Comment by KorGgenT** [comment]
> This behavior prevents muscle memory from working because when selecting panes, you need to actively pay attention to which panes there currently are

So i actually completely disagree with your premise in the first place; it's muscle memory that AIM is in the state it was when you closed it. Additionally I heavily disagree that we should make it possible to select the same square in both panes *and* ignore anything done to those panes; this adds absolutely nothing to AIM use except adding some extra keypresses and confusing behavior.

**Comment by satheon49** [comment]
The state of AIM does not change between closing and opening. The only part of the PR that did this was the forced focus on the left tab and that was reverted.

I am not sure what you mean by "ignore anything done to those panes". You get a message if you try to move items between the same square in both tabs "Source area is the same as destination" which was already implemented btw.

Can you name a single use case of AIM where the new behavior requires more keypresses than the old one? I can't find a single one where the current PR does not have the same number of keypresses or even less (like switching back and forth between vehicle/ground)

And that it does not add anything to AIM is plainly wrong because it adds consistency to keypresses. Pressing '1' should always select the southwest square and not in one of 12 cases swap tabs. That would be like the ENTER key on your keyboard having the functionality of TAB once in a while depending on what action you last took a minute ago.

**Comment by esotericist** [comment]
issue where feature was requested: #6215
pull request added it: #6693

still not a bug. still behavior people use and would miss. you have, thus far, not presented a compelling argument for why we should lose functionality beyond "i think it's incorrect", and the fact multiple wanted it added, it got intentionally added, and multiple people want to keep it, you may need to consider the possibility that it is not objectively incorrect.

it's possible you could come up with a solution that leads kevin to accept some type of configuration option to disable it, but that's typically a hard sell.

**Comment by andrei8l** [comment]
@satheon49's PR doesn't remove the functionality - rather it moves it to an explicit action. You need the same number of key presses too.

**Comment by satheon49** [comment]
Nobody who wants to see this implemented said that this was a bug. Even the template used was "Feature Request" not "Bug".

Please take a look at the PR #45903 because I am not sure you know what the PR actually entails. No functionality is taken away. You can still switch panels it even has its own keybinding.

About the issue #6215 you linked. It seems the main pain point was that the game would not let you open the same location in both panels and instead do nothing. I agree that this is annoying. The author also wished that he could easily swap panels. 

#45903 would have fully addressed both issues of #6215 too:
- there is a keybind for swapping tabs
- you no longer get an error message when trying to select the location present in the other tab

**Comment by esotericist** [comment]
> Nobody who wants to see this implemented said that this was a bug. Even the template used was "Feature Request" not "Bug".
>

my "still not a bug" was remarking on how it was reported as a bug last time it came up, and that it still isn't a year and change later.
 
> Please take a look at the PR #45903 because I am not sure you know what the PR actually entails. No functionality is taken away. You can still switch panels it even has its own keybinding.

you are changing interface semantics such that a previous method of interaction no longer functions, one which has been present in the game actual years, and which people have grown very accustomed to.

"i can't press the same keys to get the same result" is in effect a loss of functionality, and you can't simply rebind keys to restore the old behavior the way you can with the common use cases (we've moved things around in the main game interface before, but generally try to keep things available so people can reclaim old patterns whenever it's still possible and won't substantively increase maintenance burden or result in mostly-dead code).

> About the issue #6215 you linked. It seems the main pain point was that the game would not let you open the same location in both panels and instead do nothing. I agree that this is annoying. The author also wished that he could easily swap panels.
> 
> #45903 would have fully addressed both issues of #6215 too:
> 
> * there is a keybind for swapping tabs
> * you no longer get an error message when trying to select the location present in the other tab

and if this solution had been offered back in 2015, odds are pretty good it would have been accepted and would have began life as the status quo, but we have the weight of lots of time of people playing this way.

completely absent all other considerations, is it possible that this design is better? yes, it is possible. if what you want had been here first i probably would have been a lot more disagreeable about someone trying to suggest what the game has now.

but unfortunately we do, in fact, have years of this having been in place. it's a mechanism that works aside one specific corner case (which i would like to see improved), and without something new driving the change to make it necessary beyond "i don't like it", the change is unlikely to take place. the consistency concern is certainly meaningful, but is not sufficiently compelling on its own to overcome the inertia of learned patterns.

if you had some new functionality you were pushing forward with which improved the game and *as a necessary element of its function* required this change, it would be a rather different conversation, but i haven't seen anything like that cited so far.

**Comment by Raikiri** [comment]
I read multiple comments in this thread and everytime I want to reply something, @satheon49 has already said exactly that. Again, the issue #6215 clearly says: 

> Hitting the key that the other side of the advanced inventory is set to.. at he moment gives you the warning "same square".

Without doubt, that would be really annoying because just swapping left/right panels without a dedicated would have been nightmarish if you can't select the same panel twice. However, swapping panels when you select the same panel twice in my opinion is not a good solution because this way behavior of your action on one panel depends on the state of the other panel: if you change to the same panel, then it swaps, otherwise, it changes. In fact, this is even more complicated: it swaps if EITHER current tab is already set to what you're trying to set it to, or the other tab is set to that. So just to swap a panel to something you need to check both its state and adjacent panel's state.

All these considerations don't come out of thin air. Double-paned editors is not cataclysm's invention, there are multiple editors that do that already : free commander, total commander, NC, MC, double commander, krusader, and NONE of them have this strange functionality of swapping panels if you cd into a directory that's already viewed.

**Comment by Davi-DeGanne** [comment]
Thank you @esotericist for saying what I was attempting to, in a far more eloquent way than I ever could have.

I have little to add, but allow me to reinforce the fact that *it has been this way for 6 years now*, making it the status quo; you are not just arguing with esotericist and me, you are trying to convince the entire collective of CDDA vets that the UX they are used to is bad and they should suck it up and agree with you. That is unlikely to be fruitful, since good UX is subjective, and dependent on what said user is already accustomed to. Rather, more argument will likely only polarize everyone further. If you want this change, I think your energy is better spent coming up with a compromise.

Example: implement the dedicated hotkey to swap panes, and try to convince Kevin to allow a menu option in the "interface" section along the lines of "Advanced Inventory: press existing slot to swap panes" that defaults to ON.

**Comment by satheon49** [comment]
I would say excellent timing since I just got done with such a compromise. A hotkey for AIM that allows you to toggle the auto swap behavior on or off (there is already precedent for similar toggle hotkeys for example "Toggle category selection mode"). Default for auto swap is ON which means no one will get the new functionality without toggling it first. There is no UI indicator (though outside of category sort there isn't one for category selection mode either).

Like most AIM settings those are stored per character and won't pollute any central options menu. Is that agreeable?

**Comment by Davi-DeGanne** [comment]
> A hotkey for AIM that allows you to toggle the auto swap behavior on or off (there is already precedent for similar toggle hotkeys for example "Toggle category selection mode"). Default for auto swap is ON which means no one will get the new functionality without toggling it first. There is no UI indicator (though outside of category sort there isn't one for category selection mode either).

That'd be cool with me, but I'm hardly the arbiter here. Perhaps @kevingranade could weigh in?

(Getting a bit philosophical here, but for what it's worth: Attempting to see it from a perfectly objective perspective, I think you all make a lot of good points and your new way might even be better. However, perfectly objective perspectives don't exist in the real world; in the real world, we all have past experiences which bias us, and make us more efficient/successful at doing things in imperfect ways. These imperfect perspectives should be considered in addition to unbiased perspectives.)

**Comment by satheon49** [comment]
Even with the initial PR, it was never my intention to take any functionality away. But honestly I am baffled that there is so much resistance to this. If anything I expected the PR to be welcomed by those using the swapping functionality too because they would have gotten a SINGLE key for it instead of having to use one out of 12 situational keys.

**Comment by Davi-DeGanne** [comment]
I have a medical condition and previous injuries that cause my right hand to develop repetitive strain symptoms extremely quickly (don't neglect your vitamin D, kids), so I play with custom keybindings that allow me to use nearly exclusively my left hand.

This means that for me, keyboard space is at an even more extreme premium, and I am already very, very accustomed to and fond of the current key-press patterns; I am used to it enough that I never really make mistakes, and can use AIM very quickly, use this functionality several times per play session, and having it be 1 dedicated key instead of 2 of 12 would make zero difference for me in terms of efficiency, and would require me to stretch my hand further than is ergonomically comfortable for me.

Does this help you understand that not everyone has exactly the same background and biases as you?

**Comment by Aivean** [comment]
>  However, if when I opened the inventory, [4] was already on the left pane, when hit [4], it instead switches panes

I'm playing CDDA on and off for 4+ years and I often step on this issue and it always annoys me.

I'm not sure that swapping the panels in general is bad and that having same panel on both sides is the right solution, but I firmly believe that if you press a "location button" (e.g. `[4]` or  `I`) on the active panel, you should expect that panel to show the requested location (even if it was already selected).

Perhaps we can settle on a compromise:  add a single option for the behavior when requested location is the same as already selected in the panel.  By default AIM would swap locations (current behavior).  Alternative would be to just such keypresses.

**Comment by Raikiri** [comment]
@Aivean 
> Alternative would be to just ignore such keypresses.

Ignoring such keypresses contradicts to this

> I firmly believe that if you press a "location button" (e.g. [4] or I) on the active panel, you should expect that panel to show the requested location

I think that showing 2 panels pointing to the same location makes perfect sense from UX standpoint as a temporary state when you have just selected one panel that happened to match the other panel, but you're about to swap the other panel to something else. The reason to make each action as predictable as possible and to have as little side-effects as possible, this is a common knowledge design consideration in any user-facing system.

**Comment by Raikiri** [comment]
By the way, another example where existing UX is pretty terrible.
Assume I want to make a filter on the left pane that would find a food dehydrator in all adjacent spaces. Naturally, I go shift+F, then write "dehydrator", enter. Then I hit "a"ll to apply this filter to contents of all adjacent spaces. However, if the other pane was targetted at "all" already, it switches panes instead and my "dehydrator" filter switches to the other pane as well effectively ignoring my changes. The only workarounds when that happens is to either switch the other panel to something else or to enter the filter again in the other panel, both of which are terrible workarounds around a feature.

**Comment by Aivean** [comment]
@Raikiri 

> Ignoring such keypresses contradicts to this
> > I firmly believe that if you press a "location button" (e.g. [4] or I) on the active panel, you should expect that panel to show the requested location

Seems that there is a misunderstanding. I was describing the following behavior: 
1. after "location" hotkey is pressed, active panel always displays the requested location
2. if it was already displaying the requested location, nothing changes (no swapping)
3. but, if requested location matches the other (inactive) panel, the panels are swapped. That means that active panel becomes the requested location (consistent with 1) but passive panel changes to the previous location of the active panel. 

I think this a good compromise that fixes the biggest issue with the current behavior, and does that in least invasive way (no big changes to the current behavior, no new hotkeys).


> From my standpoint, this feature is such a no-brainer, that I did not even expect to see any discussion about it.

I was hoping you would continue: "but seeing that there is a discussion and there are actual users who disagree with me, how could I adjust my suggestion in the way that solves my problem without breaking anything for the others?"

**Comment by satheon49** [comment]
There is a problem with that solution: Do you also swap filters and sorters? If the user triggers the swap intentionally the answer _may_ be yes. If the player just opens AIM and (re)selects the target squares without looking at it the answer would be no.

**Comment by esotericist** [comment]
@Aivean it's fairly routine for me to do something like `1 1 5`, when neither pane started with `1` loaded, in order to 'push' the NW location to the opposite pane, then switch to the ground underneath me for the current pane. i use this just as often as i 'call' the opposite pane's location to the active pane (swapping the current location to the other pane)

so you're still describing a loss of functionality for me, as far as manipulating pane state with minimal logical keys and keypresses.

@satheon49 belatedly, your suggested solution of a toggle stored within persistent AIM state would be fine for *my* purposes, but i don't know for sure how kevin will react to it.

the lack of UI indication is concerning, and i'm not sure how to address that (or if it's reasonable to do so at this time).

from a discoverability standpoint, this going into the global options is probably better design (easier to find the setting if you care, able to see the state of it directly), but... well, like i noted the first time i commented, we still have to convince kevin.

this is why i brought up novel functionality which would require a change by necessity to support it. if you're bringing something new to the game, breaking old conflicting semantics without keeping a configuration option around is easier to argue.

**Comment by satheon49** [comment]
>  it's fairly routine for me to do something like 1 1 5, when neither pane started with 1 loaded, in order to 'push' the NW location to the opposite pane, then switch to the ground underneath me for the current pane. i use this just as often as i 'call' the opposite pane's location to the active pane (swapping the current location to the other pane)

*This* might be the single most important piece of information I needed to understand how you can stand the current behavior. It basically works around the limitation of the current system (and making it predictable) by targeting the destination first -> switching it to the other panel -> selecting the source tile which all things considered results in a pretty good situation where you can start moving things immediately (except if you used filters/sorters which now are also on the target space).

I ( and probably others favoring the change) come from the other direction. We use AIM like two panel file editors select our desired folders in both tabs then start moving stuff (while keeping filters/sorters were we defined them).

At least using AIM this way is something you can actually train yourself to do though there is still the sorter/filter problem (which we might be able to solve by keeping a separate swap hotkey that swaps everything while NOT swapping filters/sorters during reselect). I have to think about this for a bit...

**Comment by satheon49** [comment]
Here is my current stance on this issue:
- I like the result of @esotericist key sequence (because it keeps the focus on the source panel) and will train myself to get used to it in case the PR is not accepted (and maybe even if it is). 
- making the most out of the current system is for power users while being detrimental to new users. It never occurred to me to try to set up the non-focused tab while staying in the source tab (played on and off since acid rain). If you don't use AIM like @esotericist describes you just get a really confusing UI that sometimes reacts to your input in a certain way and sometimes differently. While efficient which I support it is not intuitive (as can be measured by the amount of posts in this issue)
- there is a bug in the current implementation if you want to use those key sequence: You can not switch away from a vehicle when reselecting it. Target vehicle square->target vehicle square->target source square) should result in you being able to move stuff to the chosen vehicle. It doesn't. I will fix this after #45903 gets accepted or reject because I do not want to create merge conflicts between my own PRs
- there is also the matter of filter/sorter which should not swap when you use double tap especially because your focused tab will always be your source tab and as such keep its settings. Wanting to swap sorters/filters in addition to drop targets should really be a separate hotkey (if anyone needs it).

Anyway. I am no longer going to try to push this change on you because I understand how you (and I might) use AIM. However I can promise you that anyone not knowing/wanting to double tap target first will stumble over this issue again and again.

**Comment by andrei8l** [comment]
> @satheon49, @andrei8l
> From my standpoint, this feature is such a no-brainer, that I did not even expect to see any discussion about it. If the mergers actually decline both of your implementations, can you maybe try pushing your changes to Bright Nights? That fork seems to be more user-facing.

I think we can reach a compromise without running away to a different repo. Aivean's solution seems best to me. If the number of options is a problem, we can just replace `OPEN_DEFAULT_ADV_INV` because it's completely broken and I don't think anyone uses it (or they would have written a bug report).

**Comment by esotericist** [comment]
@satheon49 
> there is a bug in the current implementation if you want to use those key sequence: You can not switch away from a vehicle when reselecting it. Target vehicle square->target vehicle square->target source square) should result in you being able to move stuff to the chosen vehicle. It doesn't. I will fix this after #45903 gets accepted or reject because I do not want to create merge conflicts between my own PRs

this is actually the corner case i mentioned earlier. i'd like it fixed, but haven't been in a position to think about the possible ways we can fix it correctly. (fun fact: if it turns out fixing this is impossible without changing the current semantics, that would be an example of a valid reason to change the current semantics, but that would not be the first resort)

your notes about it being unintuitive to the unitiated are definitely on point; while i didn't have much trouble adapting to it (and immediately preferred it and its behaviors to normal inventory motion), i am fully conscious that my cognitive patterns are atypical when compared to the general populace.

making it more accessible is absolutely a thing of interest, but we always have to balance "more accessible" against the 'power users', as you put it. when there's a working high throughput option, removing it in favor of something less arcane has to be done with care. inertia is the biggest element here; forcing users to relearn a new behavior when they aren't getting any benefit from having to learn the new behavior is just as much a path to frustration as difficulty learning a behavior in the first place.

but like i've said, change can absolutely come if it must; if we can't keep an old mechanic, we do what we have to, and that's always a good time to do something more intuitive. 

the movement mode design shifts (while ahem, moving more slowly than we'd like) are a good example of this; adding crouch made the original toggle problematic, and with the plans to add more facets to movement, making the default a menu made more sense but we kept some additional bindings around for people who couldn't adapt right away.

i don't have a strong opinion on the filter issue.

@andrei8l 
if we have a functionally dead aim-specific option that doesn't do anything useful, repurposing it to support this semantic is possibly doable. kevin has previously exhibited slightly less reluctance to pivot an option from something useless to something useful than he has to adding an option.

is there an open issue or discussion somewhere documenting the breakage? being honest, i can't recall offhand what the option even does. i'd want to be *certain* we weren't actually disposing of a thing that matters.

**Comment by andrei8l** [comment]
> is there an open issue or discussion somewhere documenting the breakage? being honest, i can't recall offhand what the option even does. i'd want to be _certain_ we weren't actually disposing of a thing that matters.

As Raikiri mentioned above, that option makes the AIM switch back to the default state whenever you transfer an item, which completely breaks the workflow with the AIM. It would be **trivial** to fix this issue (to what I assume was the intended behaviour), but I'm taking the lack of bug reports as a strong indication that nobody is interested in this feature. It's also a global option that effectively only removes the need for one key press.

**Comment by satheon49** [comment]
I am not sure how this option has ever worked, but I stumbled over the problem @andrei8l mentioned too when I implemented the forced focus on the left tab. 

Basically AIM gets closed after every item move operation and is immediately reopend. AIM saves and restores its setting for every close/open and there was no way to differentiate between those and a user triggered close and reopen. So on every open that global setting got checked and would restore the default I/A layout. This means you have exactly one item move before AIM resets to its default state.

I [fixed](https://github.com/CleverRaven/Cataclysm-DDA/pull/45903/commits/1b61d2e50a543eed764bb2f446892fcc8b362416) that problem by letting AIM know whether it was reopened due to a item move operation or by the user. But I reverted it together with the forced focus because the latter was a bad idea and as @andrei8l said the bug is pretty obvious and no one complained about it.

I will change #45903 to use a global option but not remove the current one. Removing (or fixing) the other option is pretty simple at any point in time. However as I said I am also fine with the PR getting rejected.

**Comment by esotericist** [comment]
oh, now i know what's happening

it used to work before we made item motion in aim into a proper activity; it used to just eat the turns without closing.

i have no idea how many people actually use it, but it's possible that it being broken when the next stable hits could get more reports than we aren't getting now.

**Comment by satheon49** [comment]
Are containers in AIM even working at the moment? During my tests only bottles allowed me to press 'c' and then it was named invalid container and did not show the liquid. Worn backpacks don't seem to work and neither small cardboard boxes with sugar (in inventory or on the ground)

**Comment by Aivean** [comment]
> Are containers in AIM even working at the moment? 

I don't think so. 

There was an attempt to fix it ( #45056, stalled atm). Also there is #45243 from @andrei8l , which I hope gets merged in the new dev cycle and either adds support for containers or makes adding it less painful.

**Comment by Raikiri** [comment]
@Aivean I think having both panel point to the same source for managing containers is a great argument, but adding support for nested containers is way outside of scope of this issue. We can, however, use this plan as an argument to why this behavior will be needed in future anyway.

**Comment by Aivean** [comment]
> @Aivean I think having both panel point to the same source for managing containers is a great argument, but adding support for nested containers is way outside of scope of this issue. 

I agree.

> We can, however, use it as an argument to why this behavior will be needed in future anyway.

As Esotericist said, Kevin is strongly averse to the changes that don't have solid rationale to support them. And, unfortunately, UX is very opinionated, so it doesn't count as a solid argument.

At this point, I'm not sure that pushing any changes to AIM here and now is a good idea long term. The "compromise" that I suggested will still require adding and supporting extra setting and behavior.

However, if we wait for #45243, it would be possible to make major changes in UX to make it more aligned with the underlying functionality.

**Comment by esotericist** [comment]
alright at this point i think we're about as close to a consensus as we're likely to get.

there's ideas for things that would require the existing semantics to be changed or removed, at which point i will happily entertain that.

but for right now, trying to change this is disruptive without *universal* positive benefit. it'll be plus for some, a negative for others, probably a wash for everyone else. that kind of change will consistently lose to the status quo. 

i am currently leaning towards:

*  we close #45903 for now, since i think it's probably too late in the cycle to start tinkering with this extensively and i'm pretty sure kevin's not going to sign off on the option (and i'm pretty sure the 'hidden' toggle in aim is probably a bad way to go)
*  we keep this issue open, since it's still a pertinent request but we just aren't in a position to act on it definitively at the tail end of a stabilization cycle
*  once we're looking at refactoring aim so we can do cooler stuff with it, cooler stuff could require us to revisit it

@satheon49 @andrei8l since you two are both waiting on the state of this, does this sound fair?

**Comment by esotericist** [comment]
as a side note, we probably *should* fix the default-state aim config setting, independent of the above

**Comment by satheon49** [comment]
#46021 fixes it. For all other changes we should probably just wait for #45243.

**Comment by anothersimulacrum** [comment]
Does this remain a problem after #50531?

**Comment by satheon49** [comment]
The PR fixes a pane with a selected vehicle blocking swapping which was afaik the only instance were autoswapping was inconsistent. As such it arguably makes this issue worse because now there is another instance where AIM autoswaps.

As for this issue itself: I only see two possible resolutions to it: Either an option for player to disable autoswapping or closing it because the current version is working as intended. Even though I got used (and now prefer) autoswapping I would still be willing to add such an option if desired.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
