### ISSUE TITLE
Implement showers

### ISSUE THREAD

**Issue by Svankensen** [CleverRaven/Cataclysm-DDA#45942]
Whenever I come back from the wilderness IRL, a hot shower is right after a hot meal in my priority list. An average shower uses 59.8 liters. That's one full water tank. A shower in an RV with a water recirculator uses on average 1/4th of that. 

Make two different showers:
- Makeshift shower: heating element, faucet, water bottle, metal plating, towel. Uses the full 60 liters, a bar of soap, some power, and wets the towel. Big morale boost. Maybe even counts as low quality disinfection (IRL washing is much more used than antiseptics).
- Recirculating shower: Uses 15 liters and less power, the rest is the same. Requires far more skill to craft, uses the same components plus, a water pump, a circuit board and a small 10 lt tank.
Both count as towel hangers of course. 

No idea on apropiate morale boosts, but they should be largeish. It is a lot of water compared to all other uses, and a sizeable ammount of power I imagine. Also requires a dedicated slot.  I would do away with the requirement to get naked, if only because getting dressed again in a cluttered RV is a pain.

Alternatives:
Taking baths in rivers and ponds could give a similar, smaller morale boost. Need to be naked, so you are vulnerable, and also uses soap.

**Comment by jfcaron3** [comment]
Solar-heated showers for camping are a niche but real thing you can buy.  A plastic tarp with reflecting foil heats a bag of water, so it could be craftable in-game.

**Comment by Zaraka** [comment]
Right now there are plenty of non functional showers in every house. What about them?

**Comment by Mom-Bun** [comment]
No thanks in my opinion, this strays too close to simulating filth and hygiene, as a moral boost from a shower would open up moral debuffs from being outside, sweating, etc and none of us want that.

**Comment by Svankensen** [comment]
> Right now there are plenty of non functional showers in every house. What about them?

They are likely not electric showerheads, I'm not familiar with the region tho, they are the most common shower aparatus in some parts of the world. Heard people call the shoddy ones suicide showers, but if anything it goes to show. Whole countries just do whatever, connect two wires, use some insulating tape, and call it a day. And it is not a constant cause of death. But if I'm not mistaken the US mostly uses stationary electric heating tanks. I guess you could pilfer a showerhead proper from them instead of making one with a bottle. 

>  Solar-heated showers for camping are a niche but real thing you can buy. A plastic tarp with reflecting foil heats a bag of water, so it could be craftable in-game. 

I recall using some back in the early 90s. They were just black water bags that you left in the sun, not as elaborate as the ones you mention. Very far from your normal shower experience, but still good.

**Comment by Zireael07** [comment]
The black bag kind of a solar shower still exists, btw. We had one of those on the yacht, at least until the bag broke (or was it the plastic showerhead bit? I don't remember)

**Comment by Svankensen** [comment]
Found a teardown from one of the showerheads. Jesus they are simple. The shock protection is simply the neutral going into the water, and the resistive coil is inmersed into the the water without much consideration. The guy examining it says it is safe enough, but certainly not up to stringent standards. 

https://www.youtube.com/watch?v=jo99U3nVCnA

**Comment by jfcaron3** [comment]
I kind of agree with Mom-Bun about considering whether this would add fun to the game or add to the tedium.  We already have shaving kits, but no other non-medical personal hygiene/grooming stuff.

**Comment by Zireael07** [comment]
Yes, but having showers as basically the same, but differently flavored, is a good idea. Especially the static showers in buildings would give players a reason to actually use the buildings instead of being a nomad/living out of a car.

**Comment by Svankensen** [comment]
> I kind of agree with Mom-Bun about considering whether this would add fun to the game or add to the tedium. We already have shaving kits, but no other non-medical personal hygiene/grooming stuff.

Oh, so that's what they do! I'm a beardy dude, so I see shaving kits and don't imagine they will make me feel good. Ditto when playing as a female character. Maybe it should be renamed grooming kit instead of shaving kit, it would be more clear in it's intent.

> Yes, but having showers as basically the same, but differently flavored, is a good idea. Especially the static showers in buildings would give players a reason to actually use the buildings instead of being a nomad/living out of a car.

Only problem I see with that is that it implies there's still water and power. I do like the image of a survivor carrying a jerrycan and a heavy battery to the water heater in hopes of having a hot shower. But then, the morale bonus better be huge, to be worth going through all that trouble.

**Comment by Fosheze** [comment]
Having a morale bonus from showering is nice but what I'm seeing is a possibility to reduce the player's scent cloud. Maybe taking a shower could temporarily give the player something like the "weak scent" trait or alleviate the malus from "strong scent". I could also see it giving the player a bonus to their social abilities. After all people are going to be more likely to join you when you don't smell like the entire garbage dump and it looks like you can take care of yourself.

As far as the people concerned about the micro go, a shower should never be necessary and not taking a shower shouldn't negatively impact morale. It should be a nice luxury if you have the means like the shaving kit or electric trimmer. It's been a while since I've played it but I remember Project Zomboid having a good shower/bathing system. In that game you never "needed" to clean yourself but if you had the opportunity to do so it came with a few minor benefits. Mainly, if I remember correctly, it just reduced infection chance a bit.

**Comment by emptytriangle** [comment]
you should have to wash the recirculating shower frequently to prevent it from getting nasty

**Comment by Svankensen** [comment]
> you should have to wash the recirculating shower frequently to prevent it from getting nasty
> 
> mop?

Recirculating showers still dump the water at the end, and don't recirulate water with shampoo and whatnot (you press a foot pedal when you are gonna throw dirty water). They just recirculate the "idle" water.

**Comment by Fosheze** [comment]
> Found a teardown from one of the showerheads. Jesus they are simple. The shock protection is simply the neutral going into the water, and the resistive coil is inmersed into the the water without much consideration. The guy examining it says it is safe enough, but certainly not up to stringent standards.
> 
> https://www.youtube.com/watch?v=jo99U3nVCnA

This is incredibly off topic but people always think these things are way more dangerous than they actually are. An electric water heater is essentially the same thing just larger and remote; the heating elements aren't insulated in any way on either appliance because under normal circumstances they are always going to be the path of least resistance compared to the water. Most tap water is actually much less conductive than most people think. Also grounding into the plumbing isn't all that uncommon. When people did wiring upgrades in older homes a lot of times they used to just run the ground wires from the outlets to the plumbing as it was already there and it was a convenient continuous length of metal running into the ground. That worked and you can still find houses wired like that but doesn't fly anywhere that I know of anymore. All it takes is for someone to upgrade one section of that metal plumbing to pex and all of a sudden none of your outlets are grounded anymore. 

As a side note I have actually load tested high wattage UPS units with a length of nichrome wire in a bucket of water; it's sketchy and definitely not recommended but it's still fairly safe if you know what you're doing. Call it a survivor water heater.

**Comment by emptytriangle** [comment]
> 
> 
> > you should have to wash the recirculating shower frequently to prevent it from getting nasty
> > mop?
> 
> Recirculating showers still dump the water at the end, and don't recirulate water with shampoo and whatnot (you press a foot pedal when you are gonna throw dirty water). They just recirculate the "idle" water.

yeah but if the shower gets nasty and moldy you'll be wearing nast and mold. With a normal shower you can use it filthy for a really long time and just get like athlete's foot

**Comment by Svankensen** [comment]
> > > you should have to wash the recirculating shower frequently to prevent it from getting nasty
> > > mop?
> > 
> > 
> > Recirculating showers still dump the water at the end, and don't recirulate water with shampoo and whatnot (you press a foot pedal when you are gonna throw dirty water). They just recirculate the "idle" water.
> 
> yeah but if the shower gets nasty and moldy you'll be wearing nast and mold. With a normal shower you can use it filthy for a really long time and just get like athlete's foot

Same could be said about normal water tanks, kitchen units, etc. There's nothing particularly nasty about a shower that makes it warrant a different treatment.

**Comment by Night-Pryanik** [comment]
No discussion in a long time, closing.
