### ISSUE TITLE
You can activate not wielded grenade, it will stay activated and spam warnings indefinitely but won't go off

### ISSUE THREAD

**Issue by Mrzjadacz** [CleverRaven/Cataclysm-DDA#45970]
# Describe the bug

Wanted to kill my char (game crashed and duplicated it somehow) by activating multiple grenades.
I couldn't activate normal, nor incendiary grenades from inventory, but I was successful with insecticidal ones.
It turned active but was too shy to take the next step.

# Steps To Reproduce

Activate makeshift insecticidal grenade and wait. It'll be displayed as active, you won't be able to activate it again but it will never go off, unless thrown or wielded.

# Expected behavior

A grenade cannot be activated while not wielded.

# Screenshots

![image](https://user-images.githubusercontent.com/26396019/101829491-63488500-3b33-11eb-86e7-7fb0dea107f1.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-8109-g9953469 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    Mythical Martial Arts [MMA],
    C.R.I.T Expansion Mod [crt_expansion],
    No Fungal Monsters [No_Fungi],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Bionic Professions [package_bionic_professions],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Mythical Martial Arts - UndeadPeople Tileset [MMAUDP]
]

**Comment by Hirmuolio** [comment]
This seems to be sum of multiple layers.

What happens:

Player activates the grenade.
On next turn the countdown causes the pin to be pulled. This checks for wether the item needs to be worn.
The game says you can't pull the pin.
But the grenade is already active so it tries to pull its own pin every turn.

It all begins in item `grenade_canister` (canister grenade. Well it is not really an item.). 
This item has this: `"use_action": { "type": "countdown", "name": "Arm grenade", "message": "You pull the pin on the %s." },`.
What it does is defined in `int countdown_actor::use` at: https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/iuse_actor.cpp#L424
In short it sets a counter and makes the item active.
This item gets processed every turn. This calls `int iuse_transform::use` at https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/iuse_actor.cpp#L200
This reduces the countdown by one, I think. It is weird function that covers many unrelated possibilities.

Problems start in item `gasbomb` (tear gas grenade).
This item copies from `grenade_canister` so it has the same use_action.
So when you use it the item simply becomes active and starts a countdown.
But then things start to get a bit convoluted.
This item also has `"countdown_action": { "need_wielding": true, "menu_text": "Pull pin", "type": "transform", "target": "gasbomb_act" }`
I think this gets called in `int iuse_transform::use`. So when you pull the pin the pin actually gets pulled on the next turn!
But this is where the "is wielded" requirement is checked. So you can pull the pin and on the next turn the game checks if you could even do that.

Then we get to `insecticidalbomb` (insecticidal gas grenade). This item copies from `gasbomb` so it has all the same issues. It has its own `countdown_action` which owerwrites the one from previous item.

I think the root of this problem is that the function that handles player activating item is same as the function that handles item doing somethin. These two need to be separated.
