### ISSUE TITLE
Would it be possible to make plutonium slurry, and damaged and/or leaking minireactors, emit radiation?

### ISSUE THREAD

**Issue by MetalCr-e** [CleverRaven/Cataclysm-DDA#45984]
# Is your feature request related to a problem? Please describe.
This would be great for players who like to roll the dice with radiation-acquired mutations, and it would also provide an additional challenge and hazard for players to tackle.

# Describe the solution you'd like
Plutonium slurry, and leaking and/or damaged minireactors, should emit radiation.

# Describe alternatives you've considered

# Additional context
Add any other context (such as mock-ups, proof of concepts or screenshots) about the feature request here.

**Comment by andrei8l** [comment]
Items in inventory aren't radioactive due to a bug, technically. I had a fix for that (https://github.com/andrei8l/Cataclysm-DDA/commit/eafd2447727219eeb96369a9f6fca340e1bba190) but didn't PR it because I didn't think it would improve the game (see my reasoning [here](https://github.com/CleverRaven/Cataclysm-DDA/issues/42458#issuecomment-664433655)). AFAICT, items on the map were only radioactive for a couple of days a very long time ago and I'm not sure what kind of effort you'd need to bring that back (and make it realistic)

**Comment by NetSysFire** [comment]
These items do emit radiation when in inventory. This was fixed somewhat recently: #58449
