### ISSUE TITLE
Targeting indicator displaced off of the player

### ISSUE THREAD

**Issue by ToxiClay** [CleverRaven/Cataclysm-DDA#46035]
# Describe the bug

Pressing the Examine button (and presumably other such functions as invoke the same interface) doesn't start the reticle on top of the player anymore; it starts one tile to the left.

# Steps To Reproduce

1. Press x to invoke examine mode.
2. Notice that the indicator is not on top of the player.

# Expected behavior

I expected the indicator to start on top of the player, as it has before.

# Screenshots

# Versions and configuration

- OS: Windows 10 20H2
- Game Version: 0.E-8128-gc363e33 [64-bit]
- Graphics Version: Tiles
- Game Language: System language [English]
- Mods loaded:
-- Dark Days Ahead [dda],
-- C.R.I.T Expansion Mod [crt_expansion],
-- No Fungal Monsters [No_Fungi],
-- Disable NPC Needs [no_npc_food],
-- Alternative Map Key [alt_map_key],
-- SpeedyDex [speedydex],
-- Stats Through Kills [stats_through_kills],
-- Stats Through Skills [StatsThroughSkills]

**Comment by ToxiClay** [comment]
I wonder if it isn't instead that the player is off-center in the screen. I'm not sure how to determine which is the case.

**Comment by anothersimulacrum** [comment]
Is it fixed if you press `:`?

**Comment by ToxiClay** [comment]
I can't tell what that button did, but I don't think it mattered. The weird thing is, I reverted back to the last version I had (11232), to verify that the behavior didn't exist there; it didn't. But then I restored back to 11243....and the behavior is gone. I have no idea what changed with switching between versions.

**Comment by Qrox** [comment]
Sounds like you accidentally changed the view offset and restarting the game reset it. You can press `shift+H/J/K/L` to shift the view and `:` to reset it.

**Comment by satheon49** [comment]
I believe you accidently pressed "H" at one point. You can use "H", "J", "K", "L" to move the cursor without moving the character. This allows you to observe stuff happening a bit offscreen while passing time.

@anothersimulacrum suggested pressing ":" because it resets your view to your character. If you do not intend to use that feature you might want to unbind those keys.

**Comment by PaulBlay** [comment]
Hey, I think I may know what causes this error and can confirm. 

When you drive a vehicle around the vehicle and player is displaced so that you see more of the area 'ahead' of your vehicle. When you stop the vehicle, and exit it, the player should return to the center of the local view. This does not always happen. I haven't narrowed down exactly when / why it happens, although it is quite common in my game play. I do a lot of biking around then letting go of controls so I can fire my rifle with both hands. In extreme cases I have ended up with my character not being visible on screen at all (when I have returned to my bike and started moving again, it adds the old displacement to the new one).

I usually just save the game and reload which resets the position. Thanks to @anothersimulacrum &co. for pointing out the : key to re-center the character - very useful.

**Comment by int-ua** [comment]
Does that still happen when you are completely sure you didn't move the view with `shift + movement key`? Is there a way to indicate shifted view in game UI to improve UX?

**Comment by PaulBlay** [comment]
@int-ua I don't know about Toxic-Clay but I still sometimes get this. Only two or three times, though, and not nearly so far off centre. I think it depends (somehow) on my gameplay and possibly bike design (I had a fast two tile bike, now I have a little slower three tile one). I've changed both since my last post so it's not the same. I am 99% sure I didn't accidentally use shift.

You could possibly have a dot on the centre of the map when (deep breath) the player is not centred + view is not dynamically shifted (from having been in a vehicle in motion).

**Comment by int-ua** [comment]
It is 0.E or latest experimental?

**Comment by PaulBlay** [comment]
(Nearly) Latest Experimental.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
