### ISSUE TITLE
Taekwondo crashes the game

### ISSUE THREAD

**Issue by AI3xander** [CleverRaven/Cataclysm-DDA#46059]
# Describe the bug

Fighting hand to hand using Taekwondo results in a segmentation fault and hard crashes the game.

# Steps To Reproduce

1. Make a player with martial arts proficiency and choose Taekwondo.
2. Seek out a worthy sparring partner.
3. Upon connecting a strike against the opponent, unravel existence.
(After multiple tests it seems feints and misses don't trigger a crash.)

# Expected behavior

I expect the enemy to suffer under a flurry of kicks, some stunning, some downing, some pushing, with passage of time and the integrity of reality intact.

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-8201-gc49b2cc [64-bit]
- Graphics Version: Tiles
- Game Language: System language [English]
- Mods loaded:
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Graphical Overmap [Graphical_Overmap],
    Blaze Industries [blazeindustries],
    Bionic Professions [package_bionic_professions]

# Additional context

[Crash_Save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5693779/Crash_Save.zip)
[Crash&Debug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5693786/Crash.Debug.zip)

**Comment by satheon49** [comment]
It's reproducible. Until it is fixed you might want to wear gloves so reality can handle your power.

Technically it happens when you don't wear anything on your hands. Gloves would be used as an improvised weapon during unarmed attacks but without any handwear the check item->is_unarmed_weapon runs into a segfault because it can't check itself for null (because the roll methods use object references instead of pointers.
I am looking into fixing it.

**Comment by AI3xander** [comment]
That's wild, thanks for the workaround in the meantime!
