### ISSUE TITLE
"None" item in travois

### ISSUE THREAD

**Issue by ToxiClay** [CleverRaven/Cataclysm-DDA#46052]
# Describe the bug

"None" item is present in my travois. Attempting to move it yields this:

```
 DEBUG    : Item 'none' with zero volume

 FUNCTION : int item::charges_per_volume(const volume&) const
 FILE     : src/item.cpp
 LINE     : 875

```

Looking into the source code for the offending line doesn't offer much insight; perhaps you can do more with the save file.

# Steps To Reproduce

I am unsure how to repro this issue; I was having a good time looting and then ran into this.

# Expected behavior

I don't know what I should have expected, other than to not find "none."

# Screenshots

![NoneItem](https://user-images.githubusercontent.com/13796683/102132599-cd0dab00-3e21-11eb-977b-88022a05f1eb.png)

# Versions and configuration

- OS: Windows 10 20H2
- Game Version: 0.E-8128-gc363e33 [64-bit]
- Graphics Version: Tiles
- Game Language: System language [English]
- Mods loaded:
-- Dark Days Ahead [dda],
-- C.R.I.T Expansion Mod [crt_expansion],
-- No Fungal Monsters [No_Fungi],
-- Disable NPC Needs [no_npc_food],
-- Alternative Map Key [alt_map_key],
-- SpeedyDex [speedydex],
-- Stats Through Kills [stats_through_kills],
-- Stats Through Skills [StatsThroughSkills]

# Additional context

Find attached a copy of the quicksave for diagnostic purposes.

[Woodcock.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5691461/Woodcock.zip)

**Comment by acbcodetribulations** [comment]
Going from memory, an obvious culprit was a "move all" in advanced inventory attempting to move cartridges that were in gas masks or similar face coverings. I remember it due to having to remove the cartridges, favorite them so they are not dropped, and putting them back in to avoid the issue. When they fail to get moved it shows an error, and then the none are used in place of them.

As an aside, attempting to pick up none duplicates them depending on the method used. Moving them to another spot using advanced inventory worked without a problem, and so does running them over with a vehicle.

**Comment by Night-Pryanik** [comment]
Save game is no longer loadable.
