### ISSUE TITLE
.50 ammo belt linkage is way harder to find than .50 ammo itself

### ISSUE THREAD

**Issue by Raikiri** [CleverRaven/Cataclysm-DDA#46074]
# Describe the bug

.50 caliber ammo itself drops in ungodly amounts from practically everywhere: each bunker, military outpost, barracks has hundreds of it. However, in order to use it from a machinegun on a vehicle, one needs an ammo belt made with ammo linkages, and it's unreasonably harder to find those links than ammo itself. Basically I think only high-caliber turrets and some vehicles with these machineguns installed drop it (from what I found).

# Steps To Reproduce

1. Go into the game
2. Try to find .50 cal ammo linkages

# Expected behavior

I think links should be made trivial to find or craft. If for balancing purposes player is supposed to have only limited access to this ammunition, then ammo itself needs to be limited, not linkages.

# Screenshots

# Versions and configuration
Current experimental

# Additional context
I'd love to see way less high-grade military ammo in the game. Currently every turret drops way more ammo than I expect it to. And I don't mind at all having ~10 bullets loaded into my vehicle machinegun on average. However, I really wish it was limited by number of bullets and not by ammo linkages. I'd also really love to use my bullet pullers and crafting to actually reuse casings and stuff, because currently it's 100% unnecessary considering how much ammo drops from everywhere, but it might be a separate issue, this one is specifically about linkages.

**Comment by emptytriangle** [comment]
I actually like this from a gameplay perspective. But real CROWS turrets don't have any fancy machine in them to reuse linkages and automatically reload belts as far as I know. So just giving them enough linkage to go with their ammo would probably solve this

**Comment by Raikiri** [comment]
As I said, I like lack of linkages from gameplay perspective too. However, I think it makes way more sense to be limited by the amount of ammo, not linkages. In other words, I don't mind having as little ammo as we currently have linkages, but finding linkages should not be a problem.

**Comment by satheon49** [comment]
It is not that easy to solve and somewhat related to #45861.

The "starting_ammo" json attribute could use a rework now that magazines are available. Maybe replace it with "inventory" where you just define items available for the monster instead of just ammo. Then you would be able to just give it ammo belts/magazines which it could use for its integral weapons (I think monsters are aible to reload their weapons already, right?)

About the amount of ammo: If those turrets are meant to be area denial emplacements I think there ammo capacity is justified.

**Comment by Raikiri** [comment]
@satheon49 isn't it possible to at least add linkage into the disassembly recipe of the turret? because as was pointed earlier, in reality they do reuse linkages via an internal mechanism (?). 

> About the amount of ammo: If those turrets are meant to be area denial emplacements I think the ammo capacity is justified.
Sure, but this is another example where from gameplay perspective it makes no sense to follow simulationism: looting just a single turret literally solves all your ammo problems for the entirety of the game, making all the bullet pullers, primer recipes and the rest of ammo-crafting-related recipes irrelevant. Besides, 1000 rounds of .50 cal would weight ~350kg, and this is the ballpark amount of ammo we're talking about that drops from a bunch of turrets guarding a single helicopter landing pad. This, plus 5-7 linkages that actually enable using them.

Smaller caliber bullets are even more ridiculous because there's 1.5 thousand rounds dropping from each turret, and they don't even need linkages.

This combined with the fact that weapons like ferromagnetic rifles firing rebars for 3x less damage are removed from the game as being "too powerful" and "unrealistic" just really makes me wonder what kind of game the devs are trying to make out of cataclysm.

**Comment by satheon49** [comment]
Sure, adding linkage to the disassembly recipes is an option too.

I think the game will always gravitate toward one form of weaponry be it melee, throwing, archery or guns. At the moment this seems to be guns. I don't live in the US but polls I read show that more than 40% of households have guns so the amount of small arms found in game might even be underrepresented.

Military installations should start out with a large stockpile of military grade ammo though some (maybe a lot) of it should be missing after the cataclysm due to the military fighting back. Maybe turret starting ammo could be randomized to simulate that fighting.

**Comment by Fosheze** [comment]
> Military installations should start out with a large stockpile of military grade ammo though some (maybe a lot) of it should be missing after the cataclysm due to the military fighting back. Maybe turret starting ammo could be randomized to simulate that fighting.

This seems like the ideal solution for the ammo problem. Gameplay wise the turrets don't need 1000 rounds of .50 cal ammo to dissuade the player from entering the area. For that matter all you really need is the IFF warning because no one is going to stick around to see if it actually has ammo left. While it makes sense that the turrets would have been loaded with that much ammo initially they also should have used most if not all of it in the first few days after the cataclysm. If my understanding of the lore is correct then that is when most of the chaos took place. It would feel much more accurate for the player to show up to a military outpost and see the turrets with mounds of casings next to them and a field absolutely littered with bodies (possibly destroyed vehicles as well). I've personally never seen one of those turrets fire more than about 100 rounds of ammo unless I'm doing something really cheesy so everything more than that just makes them a very appealing loot piñata.

I also agree with @Raikiri in that it would make sense for there to be ammo linkages in the disassembly recipe. I could also see just adding boxes of bulk linkages as spawns wherever the ammo spawns.
