### ISSUE TITLE
NPCs cannot pass through gates

### ISSUE THREAD

**Issue by DalenTalas** [CleverRaven/Cataclysm-DDA#46124]
NPC seem to be stumped by non-door gates and do not move across them.  Gate is open, "do not open doors" behavior is disabled.

Swapping position works. Pushing the NPC results in the "NPC has no place to go" message.

Wild guessing this may have something to do with how the gate's state registers, or with the return of a function that checks pathing.

# Steps To Reproduce

1. Load attached save.
2. Move across the subway entrance gate to the south.
3. Watch the NPC stumble.

# Expected behavior

NPCs should be able to operate doors.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-8292-g00db780 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Graphical Overmap [Graphical_Overmap]
]

# Additional context

Save file: 
[Gladewater.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5718604/Gladewater.zip)

**Comment by PatrikLundell** [comment]
I believe this bug has been reported before. Mesh doors are similarly hard for companions to understand.

**Comment by DalenTalas** [comment]
Saw that as well. Can you link to where the issue was reported first?

**Comment by DalenTalas** [comment]
Saw that happen with mesh doors as well.

Can you link to where you saw the issue reported originally?

**Comment by PatrikLundell** [comment]
No. If I knew what to search for I would have done it and linked to it in the first post...

**Comment by Emotions211** [comment]
Can confirm on 11302 that NPC's cannot walk through, but may open and be forced through, "t-gate-metal-o" in terrain-fences-gates.json as well as "t_door_metal_bulkhead_o" in terrain-doors.json.

Messed around with the flags on the bulkheads just because and it's none of the flags there. Currently a NPC cannot enter a freshwater research station without them diving to the submerged entrance and you swamping places to pull them in through the doors. It also seems they cannot use the ladders in that location (Or even stairs, I just tested). Should probably open a separate issue for that...

In order to push them through a door/gate that's bugged, get them next to it by walking through it, SWAP positions with them. This will place them on the door, They can walk out on their own from here or you can push them through.

You can repeat the metal bulkheads by taking these steps

- Take a Freshwater Research Station location
- Spawn an NPC and make them a follower
- Attempt to enter the research station
