### ISSUE TITLE
Warehouse scenario failing to load in map generation

### ISSUE THREAD

**Issue by WilliamTheWombat** [CleverRaven/Cataclysm-DDA#46146]
Whenever I choose the "Overrun" scenario, and proceed with the world as a hazmat unit, my game gives me a pop-up with the following message: "Unable to generate a valid starting location Military Base Warehouse [sloc_military_base_warehouse] in a radius of 3 overmaps, please report this failure.", and I am using the following mods: Dark Days Ahead, Disable NPC Needs, Bionic Professions, Stats Through Skills. 
I had tested to see if this would happen with any other traits or scenarios, but it was just the map that was causing this to happen.

**Comment by wapcaplet** [comment]
Could not reproduce in 0.E-8292-g00db780b75. Starting new games in new worlds with the Overrun scenario, and Hazmat Unit profession, I got successful world generation 6 times in a row.

@WilliamTheWombat What is your game version number? Possibly you are on an older version that has since been fixed.

**Comment by Night-Pryanik** [comment]
I guess this is just another variation of #35376 with no reliable reproduction.
