### ISSUE TITLE
No "Hungry" status?

### ISSUE THREAD

**Issue by Raikiri** [CleverRaven/Cataclysm-DDA#46273]
# Describe the bug

Why the UI always transition from no hunger status to being "Very Hungry"? Why are there no inbetween states like "Peckish" or just "Hungry"?

# Steps To Reproduce

1. Fire up the game
2. Wait
3. Watch the character transition from no hunger status right to "Very hungry"

# Expected behavior

I expected to see more inbetween hunger states displayed.

# Screenshots

# Versions and configuration

# Additional context

Interesting thing to note is that I think I very rarely saw status "Hungry", but it only lasted for one turn or so.

**Comment by XygenSS** [comment]
If you are underweight (below normal) then you will feel `very hungry` the moment your stomach clears some room for more food.

And yes, the hunger meter is not calorie meter, it is stomach fullness meter.

**Comment by emptytriangle** [comment]
working as intended, you can't get hungry unless you are fat

this is realistic

**Comment by kevingranade** [comment]
No impact, no meaningful expected results means this issue isn't actionable, if you want to outline what different hunger states should be occurring and under what circumstances they would happen, we could talk, but "more" doesn't give us anything to go on.

Peckish in particular was removed because a relatively large number of people seemed incapable of seeing any feedback at all without treating it as a cue to eat, so we just don't display anything in between "no hunger"" and "you should consider eating something".

**Comment by Raikiri** [comment]
Sure, but why are there None->Tired->Very tired, and only None->Very Hungry? It should be called then None->Hungry and rename famished to Very Hungry maybe? Because from player's perspective when they see a "Very Hungry" status it just looks like there has to be a "Hungry" status that they missed and "missing" it every single time feels strange.
