### ISSUE TITLE
open_container flag prevents items from being valid targets for unloading liquid

### ISSUE THREAD

**Issue by ToxiClay** [CleverRaven/Cataclysm-DDA#46318]
# Describe the bug

The `open_container` flag in item JSON files prevents items from showing up in the menu for selecting the destination for fluids.

# Steps To Reproduce

1. Load a save in build 11292
2. Spawn a "plastic beverage bag," as would come out of an MRE.
3. Attempt to unload, say, a plastic canteen.
4. Note that the plastic beverage bag is not allowed.

# Expected behavior

I expect plastic beverage bags to be allowed to be filled with water.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 20H2 (build 19042.685)
- Game Version: 0.E-8388-gb85c4a9 [64-bit]
- Graphics Version: Tiles
- Game Language: System language [English]
- Mods loaded:
    - Dark Days Ahead [dda],
    - C.R.I.T Expansion Mod [crt_expansion],
    - No Fungal Monsters [No_Fungi],
    - Disable NPC Needs [no_npc_food],
    - Alternative Map Key [alt_map_key],
    - SpeedyDex [speedydex],
    - Stats Through Kills [stats_through_kills],
    - Stats Through Skills [StatsThroughSkills]

# Additional context

I discovered this problem during the course of normal play. Exhaustive analysis and comparison between the plastic beverage bag and a plastic bottle eventually revealed that the `open_container` flag in the item definitions file (`.\data\json\items\containers.json`) was the root cause. I verified this against another item (an aluminum can) possessing this flag. I don't know why this would be the case, but I suspect the problem ultimately arises from `item_pocket.cpp`, `item_contents.cpp`, or `game_inventory.cpp`.

A very naive fix for the issue would be to remove the `open_container` flag, but that has potentially undesired ramifications.

**Comment by PaulBlay** [comment]
I think the 'open container' means 'liquids will just pour out of this unless you hold it up'. IIRC, you see it with cans of condensed milk after they have been opened. You can't have them in your inventory and open with liquid in unless you are wielding them.

I think this is probably working as intended?

**Comment by ToxiClay** [comment]
OK, so actually I can verify that the beverage bag with the `open_container` flag _does_ let you fill it if it's wielded. However, this behavior is not communicated very well to the player; with this information in mind, I suggest the following:

If an `open_container` is in the inventory, and the player wants to fill it, make it appear available but cause the character to `w`ield the item after the fill is complete.

**Comment by PatrikLundell** [comment]
I've seen the same thing with a bucket in 0.E2 stable, i.e. I can't put anything into it (such as milk from a cow) unless it's wielded. It makes sense that you can't have these containers sloshing their contents out into the inventory, so technically I think it's working correctly. The problem here is to somehow make the players aware of which containers are open and which are not and that you'd have to wield them to fill them (at least the bucket can then be placed on the ground without the contents spilling out, which is what I'd expect).

**Comment by actual-nh** [comment]
Is the bucket fillable while on the ground?

**Comment by PatrikLundell** [comment]
Yes. Just tried to drop a bucket and milk a cow into it (0.E2 stable).

**Comment by emptytriangle** [comment]
plastic beverage bag can also be filled while on the ground which is probably not quite right

**Comment by PaulBlay** [comment]
> plastic beverage bag can also be filled while on the ground which is probably not quite right

It's specifically a beverage bag. It's probably designed so that, when there is liquid in it, the base is stable to stand it on. 

> can I put an open plastic container of lamp oil on a bookshelf? I can definitely do that IRL.

You wouldn't want to do the same thing with an open container of lamp oil in a vehicle trunk or other mobile storage area, though. When there is more in the way of 'base furniture that isn't actually on a vehicle frame' you could make stationary storage a separate case. 

I don't recommend open containers on bookshelves, though. Sounds like a recipe for accidents.

**Comment by ToxiClay** [comment]
> It's specifically a beverage bag. It's probably designed so that, when there is liquid in it, the base is stable to stand it on.

US MREs actually aren't designed that way. It's incredibly stupid, but they don't have the gusset they would need.

![image](https://lh3.googleusercontent.com/proxy/H_SlULY_hHsH3P8-vQQC0IJTUWlsHeHAI5VyUADUzEitCMeVhGpOvSVvKNeu9bf81N4XmtBBQx8x2T4xaZJDyyg4sax54_DskjPm1ZA05wPlGVxO)

**Comment by PaulBlay** [comment]
@ToxicClay Ah, well it's the military. I should have expected that.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
