### ISSUE TITLE
Nomex sheets required to craft survivor fire gear but there's no way to obtain them.

### ISSUE THREAD

**Issue by TaxyTails** [CleverRaven/Cataclysm-DDA#46519]
# Describe the bug
There is no way to get nomex sheets, however some recipes (like the "pair of survivor firegloves") require them.

# Expected behavior
There should be a way to either get or craft Nomex sheets.

# Versions and configuration

- OS: Arch Linux 5.8.14-arch1-1
- Game Version: 0.E-8682-gd859f82a41-dirty
- Graphics version: Terminal
- Ingame language: English
- Mods loaded: [ dda, no_npc_food, package_bionic_professions, blazeindustries, crt_expansion, magiclysm, my_sweet_cataclysm, speedydex, stats_through_kills, StatsThroughSkills ]

**Comment by PaulBlay** [comment]
Don't you get Nomex sheets by dismantling appropriate clothing? Like from firefighter zombies.

**Comment by TaxyTails** [comment]
Tried with a lot of them but got nothing. Most of them I can't disassemble

**Comment by TaxyTails** [comment]
Only thing I get is Nomex patches

**Comment by PaulBlay** [comment]
Ah, what about 'sheet_nomex_patchwork'? I have a feeling that you're supposed to be able to make that from nomex patches but there is no recipe for it.

**Comment by TaxyTails** [comment]
I'm not sure

**Comment by PaulBlay** [comment]
In the item browser it's listed as 'patchwork Nomex clothing parts' and seems to be intended as an alternative to Nomex sheets - but is shown as "can't be crafted" which can't be right. I think probably someone did half the work of introducing them.
http://cdda-trunk.chezzo.com/sheet_nomex_patchwork

**Comment by TaxyTails** [comment]
So how would you get patchwork Nomex clothing parts?

**Comment by TaxyTails** [comment]
Also, the survivor fireboots require Nomex sheets

**Comment by actual-nh** [comment]
> So how would you get patchwork Nomex clothing parts?

Should be by sewing together Nomex patches (using Nomex thread).

> Also, the survivor fireboots require Nomex sheets

Yes, the boots need updating to "tailoring_nomex_patchwork" instead of "tailoring_nomex".

**Comment by PaulBlay** [comment]
To answer your first question, there would presumably be a recipe to sew Nomex patches together. But nobody wrote it. It probably wouldn't be very hard to do that. The only problem would be if it used to be there but was removed for some reason (like somebody decided that sewing together Nomex patches with flammable thread would be a bad idea).

Second question, yeah the patchwork only can be used in three recipe instead of six or whatever. I think that's (again) just because it wasn't fully implemented. Adding it as an option to the fireboots (and other recipes) would be really easy.

Having said that, getting the changes into the game requires someone to go through the PR (Pull Request) process. In theory it isn't terribly difficult but it can be tricky to get your head around it. Unfortunately I am firmly in that part of humanity who doesn't get it.

**Comment by anothersimulacrum** [comment]
`sheet_nomex` should probably spawn in some tailoring related itemgroups, and sheet_nomex_patchwork should have a crafting recipe similar to `sheet_cotton_patchwork` or `sheet_neoprene_patchwork`. Nomex thread may also need to spawn somewhere or be available from disassembling nomex rags.

**Comment by actual-nh** [comment]
There indeed seems to be a lack of thread_nomex as well. (In terms of itemgroups, have fire stations been created? I would think the better-equipped ones would have some nomex thread and sheets.)
