### ISSUE TITLE
[Generic Guns] Ammo stacking bug

### ISSUE THREAD

**Issue by KyleFRS** [CleverRaven/Cataclysm-DDA#46577]
# Describe the bug

I have 2 stacks of rifle ammo, ball and they do not seem to stack together when I try to put them into a rifle mag. 

# Steps To Reproduce

I came across the ammo.

# Expected behavior

They should be able to be loaded into a mag together.

# Screenshots

![image](https://user-images.githubusercontent.com/77028330/103705960-ed76f280-4fe6-11eb-826e-3a900ee3cb62.png)

# Versions and configuration

0.E-2
Windows 10

Here is my save.
[Namahakara.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5772883/Namahakara.zip)

**Comment by esotericist** [comment]
so on investigation, it turns out the stack of 3 "rifle ammo, ball" is actually a stack of `762_51`. the item hadn't properly migrated yet, and when the player reloaded the save, it correctly migrates to `rifle ammo, AP`

there are three problems here:
a) it looks like items are still not fully migrating mid-run, which is unfortunate and i previously thought had been resolved
b) the contents of the `temp-ammo_redefine_hack.json` are either incorrect (`762_51` should be copy-from the AP ammo instead of the ball ammo) or should no longer be in use (inclear, depends on resolution of a above)
c) the debug mode item info is not showing the item id, which would have immediately made it clear why the two ammo items were not stacking
