### ISSUE TITLE
Add a place to see total armor values per body part

### ISSUE THREAD

**Issue by ToxiClay** [CleverRaven/Cataclysm-DDA#46587]
# Is your feature request related to a problem? Please describe.

As of build 11341, there is no place where a player might see their total armor values. Currently, the `+` menu can show you individual armor values per item of clothing, but that isn't as holistic as one might like.

# Describe the solution you'd like
There is enough room on the `+` screen to add this sort of display.

# Additional context
![image](https://user-images.githubusercontent.com/13796683/103740534-6402f880-4fc5-11eb-853e-c060730539e8.png)

**Comment by Asmitha90** [comment]
Ye this one should take priority :)

**Comment by anothersimulacrum** [comment]
This is a tricky UI thing - either every single piece of armor, with it's armor values and coverage must be enumerated, or we do some sort of thing to combine all the armor and coverage into a display that has some assumptions going in.

**Comment by kevingranade** [comment]
The best you're going to get is some kind of "typical" armor value, or a spread of values.
The problem is if it's too simplified, it could be actively misleading.
e.g. if you report the total and the... average coverage? That's most likely to be more misleading than informative.

e.g. you have three articles on your torso, each of which has 50% coverage and an armor value of 10.
12.5% 0
37.5% 10
37.5% 20
12.5% 30

Keep in mind that if you have values less *convinient* than 50/50 coverage and the same armor values, the combinations of values multiply very rapidly, for example if you have just three articles with different armor values, that could produce up to 8 different combinations.

**Comment by emptytriangle** [comment]
What if it's a range? Worst/best case scenario. So if I am wearing a chainmail armor and a hoodie it would be

0-18 95%

Showing the minimum armor rating, the maximum armor rating, and the coverage value of the lowest-coverage item in that slot? That wouldn't be perfect, it could confuse some players who put on a low-coverage piece of gear and then think their stats may have dropped.
