### ISSUE TITLE
Can't butcher with the "sharp rock"

### ISSUE THREAD

**Issue by OmeleteDuFroMago** [CleverRaven/Cataclysm-DDA#46622]
# Describe the bug
When you try to butcher a corpse with the -50 butchering rock it says it need at least 1 level of cutting.

# Steps To Reproduce
Just try to butcher something with the rock

**Comment by anothersimulacrum** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/issues/42739#issuecomment-670356779

A random sharp rock being able to cut is intentional behaviour, AFAICT.

**Comment by OmeleteDuFroMago** [comment]
> 
> 
> [#42739 (comment)](https://github.com/CleverRaven/Cataclysm-DDA/issues/42739#issuecomment-670356779)
> 
> A random sharp rock being able to cut is intentional behaviour, AFAICT.

I meant like, i forgot the especific name but, there's a rock with -50 butchering and the description says it can be used to butcher but when i try to butcher something it don't work and says i need at least a tool with 1 level of cutting or more

**Comment by emptytriangle** [comment]
That just means you also need something that can cut to cut through the thick tissue and tendons. A sharp rock won't be able to butcher by itself. But if you had a sharp rock and some scissors it would work. Scissors seems like an unusual thing to have out in the wilderness if you're using a sharp rock to butcher, but there are probably better examples. A bunch of weapons and gardening tools have cutting quality but no butchering quality.

If you ever do use a sharpened stone for butchering you'll probably only use it once, because you can make better tools for butchering from the bones you get from the butchery.

**Comment by anothersimulacrum** [comment]
> I meant like, i forgot the especific name but, there's a rock with -50 butchering and the description says it can be used to butcher but when i try to butcher something it don't work and says i need at least a tool with 1 level of cutting or more

Then I would say this can be resolved by modifying the description to reflect that.
