### ISSUE TITLE
(Aftershock) Forgotten Experiment - Quest Line - Incorrect monster

### ISSUE THREAD

**Issue by GyprockGypsy** [CleverRaven/Cataclysm-DDA#46665]
Was sent on the quest to get a heart, but after talking on a thread with some people, it appears that I am being sent after the wrong creature.

# Steps To Reproduce

Not sure exactly. It's a transfer character from 11340ish, but otherwise pretty vanilla. 

# Expected behavior

The quest should sent me after a Flesh Golem named Billy", but instead sends me after a Jabberwocky with a Flesh Golems description. Produces a putrid heart like a Jabber, rather then a Flesh Golem heart as required by the quest.

 - OS: Windows 10 Pro - Current
 - Game Version: 11352
 - Graphics version: Undead
 - Ingame language: English
 - Mods loaded: Aftershock, CRIT, Blaze, Crazy, Dinos, Magic

# Additional context

Haven't had time or gas to back, but the quest marker has reappeared, so I'll try returning this evening and see if the correct creature is present now.

**Comment by int-ua** [comment]
The title does not reflect the issue, please change it.

**Comment by Mrzjadacz** [comment]
Issue refers to content from #44709

**Comment by mark-ik** [comment]
Can confirm this happened to me. Instead of a flesh golem, I found a jabberwock named Billy at the quest coordinates. 

My mods.json:

  "dda",
  "aftershock",
  "Arcana",
  "magiclysm",
  "crt_expansion",
  "package_bionic_professions",
  "Cata++",
  "Graphical_Overmap",
  "Graphical_Overmap_Magiclysm",
  "AftershockUDP",
  "ArcanaUDP",
  "crt_expansionUDP",
  "Cata++UDP",
  "MagiclysmUDP",
  "stats_through_kills",
  "StatsThroughSkills",
  "cbm_slots",
  "speedydex",
  "fuji_mpp"

**Comment by actual-nh** [comment]
Exactly how do you mean "sent after a Jabberwock but with a Flesh Golem's description"? (I'm wondering if the Jabberwock ate the Flesh Golem...)

**Comment by LyleSY** [comment]
Maybe CRIT is replacing flesh golems?

**Comment by mark-ik** [comment]
Here's a screencap of the carcass. I field dressed the corpse and only got three putrid hearts, which Sadie the forgotten experiment NPC will not accept because they need a seeping heart.

![2021-01-21](https://user-images.githubusercontent.com/54276851/105417501-bff68f80-5c09-11eb-95a5-48746f615dc5.png)

Out of curiosity, do flesh golems exist aside from this quest? Where are they typically found?

**Comment by LyleSY** [comment]
Not sure, I used them because I thought they weren't used enough, but they're a vanilla creature

**Comment by actual-nh** [comment]
Flesh golem: `"upgrades": { "half_life": 15, "into": "mon_jabberwock" },`. From data/json/monsters/jabberwock.json.

**Comment by Mrzjadacz** [comment]
Hmm. Replace it with a new monster inheriting from flesh golem all but `upgrades`?
