### ISSUE TITLE
"Pair of attached ear plugs" item should have description updated

### ISSUE THREAD

**Issue by NyarlathotepZERO** [CleverRaven/Cataclysm-DDA#46698]
# Is your feature request related to a problem? Please describe.
"Pair of attached ear plugs" item should have search reference words in the description, in line with other noise cancelling items. 

# Describe the solution you'd like
To have the words "this gear prevents you from hearing any sounds" similar to the "noise cancelling headgear" item so it is searchable by useful words such as 'sound' or even 'noise' perhaps

# Describe alternatives you've considered
Just addition of any searchable word relating to their purpose of noise cancelling

# Additional context
none

**Comment by ThomasLinkin** [comment]
i think Kevin had proposed a tag system where you can put a tag onto an item and it will help in many different aspects, such as your, since giving noise cancelling headgear a "soundproof" tag or something like that will make it easier to create a patterned interaction with other items or world's object, or in your case, easy searching. but it requires a system rework, so i dont think it's possible ? anyway, good suggestion.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
