### ISSUE TITLE
Allow unattended time while recipe progresses

### ISSUE THREAD

**Issue by Xaleth** [CleverRaven/Cataclysm-DDA#46775]
# Is your feature request related to a problem? Please describe.
Related to #42556

When crafting a recipe, allow the player to unattend the recipe for a certain amount of time such as boiling water or baking bread for example. You would want to go around doing something while waiting for the bread to bake instead of unrealistically and awkwardly standing there waiting for time to pass. 

There can also be an option to stay in the recipe the entire time when the unattended time starts.

# Describe the solution you'd like

Add `"unattended_for"` in a JSON crafting recipe, for example:

```
{
  "type": "recipe",
  "result": "bread",
  "time": "30 m",  // Time spent with player intervention. When 30 minutes are over, it gets switched over to unattended time.
  "unattended_for": "1 h",  // This is where the player doesn't need to be at the bread while it's baking unless otherwise stated. 
  "//": "There can be a time where you can come back to it when the unattended time is finished and the player completing the rest of the craft, if the unattended time is finished but the player waits too long the recipe can go bad"
}
```

# Describe alternatives you've considered
Me doing it. I have attempted to try and figure out how to do this for a while now and realized this is far beyond my skillset as I have next to no clue what I'm doing in the code and that there are performance issues related to it along with other things.

# Additional context
I was informed to look in `craft_command::create_in_progress_craft` since the unattended crafting is basically just increasing progress without the player being there, and to mark it with a flag so that it's processed in `item::process_internal`. Other methods are welcome.

**Comment by PatrikLundell** [comment]
JSON doesn't support comments (as far as I understand the creator removed the functionality in a fit over it being "misused" for processing instructions).

If the functionality is introduced, you need at least 3 parameters:
- time: Should be the total time, in order not to mess up existing recipes.
- unattended_time: optional parameter for how much of that time you can spend doing other things.
- unattended_failure_time: optional parameter for how long you can wait to pick up the results before the crafting is failed.

Also note that you may get issues with resources when you've e.g. started boiling water on the stove: You shouldn't be able to have an unlimited number of jobs active at the same time using the same resources.

If this gets implemented, a number of "work around" recipes could be converted, such as ones where the crafting results in items that are effectively in progress ones (I think there are such recipes for fermenting, for instance).

It certainly would be great to stock a dehydrator and start it, without having to stare at it while it works, and then pick up the results at a convenient time, as there wouldn't be a failure time for that process: normal perishable food decay should start at the time the processing is done.

Reality is more complex than "spend time at the beginning and then wait until it's done", but this might be a reasonable compromise between realism and avoiding tedium (bread: make the dough, wait while it rises, shape the dough, wait while it rises, shove it into the oven, wait while it's baked, remove from oven. Each of the waiting steps have their own time limits, with the oven time one depending on whether the oven is timed to shut off/run out of fuel when done or not).

**Comment by Fosheze** [comment]
> Reality is more complex than "spend time at the beginning and then wait until it's done", but this might be a reasonable compromise between realism and avoiding tedium (bread: make the dough, wait while it rises, shape the dough, wait while it rises, shove it into the oven, wait while it's baked, remove from oven. Each of the waiting steps have their own time limits, with the oven time one depending on whether the oven is timed to shut off/run out of fuel when done or not).

If someone wanted to you could add the extra bit of realism and allow a person to have a list. For example you could have something like the following. (Sorry I still can't figure out how to make code look right when using insert code so you're getting normal text).

    "craft_order": [
       [ "attended_time", 5 m ],
       [ "unattended_time", 45 m, 1 h ],
       [ "attended_time", 2 m ],
       [ "unattended_time", 30 m ],
       [ "attended_time", 1 m ]
      ]

The crafting recipe would just go down the list. For unattended time you would have an optional second parameter which would be the point at which the craft sat long enough to be ruined. If there is nothing there then it can sit indefinitely at that stage. While this would be a lot more work, if the crafting code gets rewritten to add in unattended time it "shouldn't" be that much more code to make it iterate through a list.

**Comment by actual-nh** [comment]
> JSON doesn't support comments (as far as I understand the creator removed the functionality in a fit over it being "misused" for processing instructions).

[Roll eyes re removal of functionality...] "//#": "[comment]" seems to be how it's done in practice, with the # being needed because you can't duplicate keys.

**Comment by PatrikLundell** [comment]
Yes, the removal of comments from the text is worked around by burdening the executable with the storage of them as data.

Regarding Fosheze's list I'd guess it would be a list of lists, i.e. [[[attended time], [unattended_time], [optional_spoiler_time]], <additional entries>] (in some kind of pseudo JSON). From a code implementation point it's probably easy to handle multiple stages when one has been introduced, but the real question is if the game benefits from all these action snippets, so care would have to be taken when reworking recipes.

Also, I still suspect the hardest part is to lock "tools" up by the in progress item when it's in process (the dehydrator and stove still being there, but somehow marked to be in use, while the pot should probably be incorporated into the in progress item until the end and then returned, while "real" tools aren't locked up [if you're not actively sawing on this craft you can use it on something else, but the clamps are presumably occupied while the glue takes effect, etc.]).

**Comment by actual-nh** [comment]
> Also, I still suspect the hardest part is to lock "tools" up by the in progress item when it's in process (the dehydrator and stove still being there, but somehow marked to be in use
That's not even getting into (some) stoves having multiple burners...

**Comment by Fosheze** [comment]
> Yes, the removal of comments from the text is worked around by burdening the executable with the storage of them as data.
> 
> Regarding Fosheze's list I'd guess it would be a list of lists, i.e. [[[attended time], [unattended_time], [optional_spoiler_time]], ] (in some kind of pseudo JSON). From a code implementation point it's probably easy to handle multiple stages when one has been introduced, but the real question is if the game benefits from all these action snippets, so care would have to be taken when reworking recipes.
> 
> Also, I still suspect the hardest part is to lock "tools" up by the in progress item when it's in process (the dehydrator and stove still being there, but somehow marked to be in use, while the pot should probably be incorporated into the in progress item until the end and then returned, while "real" tools aren't locked up [if you're not actively sawing on this craft you can use it on something else, but the clamps are presumably occupied while the glue takes effect, etc.]).

Ok this is getting **drastically** more complicated but what about just locking tools in the in progress craft item and then just nesting full blown crafting recipes for each stage inside of the main recipe. Each sub-recipe could have it's own tool requirements and could be attended or unattended. When a sub recipe finished it would yield the tools it was using and an incomplete craft then if it had the materials it would automatically progress onto the next sub-recipe. The main recipe would just check it's sub recipes to find the tool/material requirements to display. Basically a recipe as the player sees it would actually be more of a collection of recipes all bundled together.

This would also make longer crafts more immersive. If you wanted to make a heavy survivor suit and you didn't have a welder yet for the armored portions, you could spend a day completing the first stage of stitching together the basic foundation of the suit and then go out that night to find a welder to finish it. Or after you could cut the wood pieces for your craft but you would need to find clamps to be able to finish it.

This could also allow the use of future furniture tools like drill presses and table saws. once you completed the work on the table saw you would take the incomplete item over to the drill press to complete the next step.

**Comment by PatrikLundell** [comment]
That would also make it drastically more complicated to display in a manner that can be understood by players. Before you start a recipe you'd need a list of everything needed, but while in the process you'd need a list of what's needed for the next step as well as the total list where things no longer needed are crossed out, so you don't take the thing needed for step 1 and 3 and use it for something else during step 2 without realizing it's going to be needed again soon. Also, while sort of realistic, is this level of detail any fun for anyone except the dedicated [insert craft type here] nerd?

**Comment by Fosheze** [comment]
> That would also make it drastically more complicated to display in a manner that can be understood by players. Before you start a recipe you'd need a list of everything needed, but while in the process you'd need a list of what's needed for the next step as well as the total list where things no longer needed are crossed out, so you don't take the thing needed for step 1 and 3 and use it for something else during step 2 without realizing it's going to be needed again soon. Also, while sort of realistic, is this level of detail any fun for anyone except the dedicated [insert craft type here] nerd?

It doesn't need to be complicated to display. You could keep the crafting menu menu exactly the same and only show total requirements because for the most part different tool requirements for different stages won't matter if you have all of the tools anyways. It is only applicable in niche situations or with niche crafts. If a person wanted to see the craft in more detail you could have a separate detailed view which just lists the stage, recipe time, tools required, and if it is attended time or unattended time. If a player tried to continue a craft while they were missing a tool you could just display a message "You are missing the (tool name) required to continue this craft". This would also give the player a reason to have multiples of various tools. Realistically how many carpenters only have one clamp or how many mechanics only have one wrench. With this you could work with limited tools but having a well kitted out workshop would be a boon and scavenging for additional tools would still be desired even once you have one of everything.

This would do two things which is allow unattended crafting which in turn allows for longer crafts (realistically a composite bow takes days to cure) and lay the ground work for future use of industrial machines with the proper proficiencies (CNC, end mill, foundry equipment, all of the new bio lab equipment). No, having to go through a detailed crafting route for every single little recipe wouldn't be fun; some abstraction is still required. As I said for the vast majority of simple recipes this shouldn't change anything. I imagine that most would only have one major attended stage. However for larger more complex crafts (wind turbine, mutagen, survivor suit, biodiesel) this would add a lot more meaning and impact to player choice. I can't speak for everyone but I personally hate how building a survivor suit is standard practice no matter what you do; it's just a normal mid-level gameplay step for basically every survivor. It kind of ruins immersion that you can build a suit of armor that completely surpasses military gear in a couple of days with a box of scraps. If that process was actually expanded into something that took thought, work, and and an actual decision, in my opinion, that would make the game more fun.

This could also open the door to significantly more complex and high end crafting. I have seen crafting ideas rightfully shot down by the devs before because crafting that item would require industrial machinery and inordinate amounts of work/knowledge. The proficiency system already deals with the knowledge requirement (once we can have NPCs use their proficiencies) but what if you could actually use that industrial machinery and realistically put in that inordinate amount of work as well? With staged crafting like this adding in immobile industrial machinery support would be as easy as dragging the in progress craft over to the machine when it is needed and treating the machine exactly like you would a welding rig or cook station. You wouldn't absolutely need every machine/tool to be in one place.

**Comment by PatrikLundell** [comment]
The problem I see with a "hidden" crafting level is that I'd expect bug report of the type "I started crafting X and the recipe claimed I had everything, but now it won't allow me to continue to step X because Y is missing" because during the week long process the player started crafting something else without even knowing it would block the first crafting.

Another potential issue is the current gotcha you can get with coldish storage: you pick out X to cook something, but then the game claims it's rotten, but you can move a tile to the side and craft directly from the coldish storage and get your foie gras.

I don't have a problem with large crafting projects, but if survivor gear (as an example) gets harder to acquire, difficulties ought to be adjusted accordingly.

**Comment by actual-nh** [comment]
Indicate "this recipe has # stages" and, beside each tool, note which stage(s) it's needed for (ideally with "1-3" instead of "1,2,3")? Also noted could be in which stage(s) a particular component would be used.

**Comment by actual-nh** [comment]
Oh. One other thing. See if at least some of the sub-recipes (stages) could be made reusable, and allow them to be repeated - helps figuring out exactly how much equipment is needed for batches.

I am inspired by working with "programmable" PCR machines, back before they were hooked up to computers or essentially were special-purpose computers. Each stage would be very simple (keep at X temperature for Y minutes) and to make a whole PCR program - involving thermal cycling - you'd link a bunch together, usually with a specified number of repetitions for each stage.
