### ISSUE TITLE
Rotten milk gets fresh by pouring in a container

### ISSUE THREAD

**Issue by sulyi** [CleverRaven/Cataclysm-DDA#46819]
## Describe the bug ##

When reloading an empty container with rotten milk (possibly other liquids also) it gets fresh.

## Steps To Reproduce ##

* Spawn milk from wish menu
* Change time forward (10 days does it)
* Select empty container from inventory
* Select reload
* Select rotten milk
* Check inventory

## Versions and configuration ##

 - OS: Linux 5.10.4-arch2-1
 - Game Version: 0.E-8938-g4b6a590632
 - Graphics version: Tiles

## Additional context ##

#20844 might be related

**Comment by PaulBlay** [comment]
I think this is related to the bug where liquids sometimes lose their component information when they are poured from one container into another.
https://github.com/CleverRaven/Cataclysm-DDA/issues/46470

If you see there, the broth that was poured into the 3L jar became 'fresh'.

I had a look at https://github.com/CleverRaven/Cataclysm-DDA/issues/20844 and, although it was closed, it seems to be a patch job. You can no longer pour rotten milk into your vehicle's tank, but that wasn't really the problem. It's stupid, sure, but if you want to fill your vehicle with stinking rotten milk you go you. The problem was that 'rotten' was turning into 'fresh'.

**Comment by Hirmuolio** [comment]
It is most likely something similar to  #42825

Somewhere along the way instead of moving the original item to new container a new item is created and the item attributes are not copied to the new item.

**Comment by PaulBlay** [comment]
@Maleclypse 
I can confirm that using 'r'eload as described in the steps above does produce fresh milk. 

I never really used reload on empty jars before, so that might explain why I couldn't get it to work before (I was using 'u'nload on the rotten milk).
