### ISSUE TITLE
Zoom level is too big in NeoDays

### ISSUE THREAD

**Issue by GGgatherer** [CleverRaven/Cataclysm-DDA#46815]
# Describe the bug

Somewhere in January 2021 zoom level in NeoDays became too big (as in, "the camera" is "too high". we've lost the closest zoom level and got one that's so far it's frankly impossible to see anything from)

# Steps To Reproduce

Best explain it with screenshots, I guess. All of them taken with closest zoom option available.

Here's build 11305. Last one in 2020. (probably were more with good zoom in 2021 but I can't check them all so decided to go with this one)
```
- OS: Windows 7x64
- Game Version: 0.E-8531-gea3e6a3 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]
```
UltiCa:
![cataclysm-tiles_2021_01_17_09_00_22_351](https://user-images.githubusercontent.com/56833396/104829126-5d1c9580-58a3-11eb-978c-ab589b50935c.png)

NeoDays:
![cataclysm-tiles_2021_01_17_09_00_10_151](https://user-images.githubusercontent.com/56833396/104829130-660d6700-58a3-11eb-8738-d8bdc0b9b2e5.png)
Not as close as UltiCa but as I mentioned in forum, UltiCa is quite more detailed so that's fine.

Now, build 11373. (current one I'm using but the zoom changed some time before that)
```
- OS: Windows 7x64
- Game Version: 0.E-8972-g8041d14-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]
```
UltiCa:
![cataclysm-tiles_2021_01_17_08_58_47_673](https://user-images.githubusercontent.com/56833396/104829171-b1c01080-58a3-11eb-97fa-0ec88247c2a2.png)
As you can see, nothing changed.

NeoDays:
![cataclysm-tiles_2021_01_17_08_59_08_687](https://user-images.githubusercontent.com/56833396/104829178-c43a4a00-58a3-11eb-9c44-7f70397eb9ed.png)
And here you can see that visible area went from 18.5 tiles wide to whopping 37 tiles wide. That's almost 2 times more. 

# Expected behavior

Zoom level behaving as before.

# Versions and configuration

```
- OS: Windows 7x64
- Game Version: 0.E-8972-g8041d14-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]
```

# Additional info:

[config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5825434/config.zip) - used my current config in the old build, too. Just copy-pasted the whole folder. So no, this is not a config issue.
[Testburg.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5825439/Testburg.zip) - save the screenshots are from. Doesn't really matter, the issue is with a tileset, not with the save. But if you want to check it, it's there.

**Comment by ZhilkinSerg** [comment]
Should be because of large sprites/overlays.

**Comment by GGgatherer** [comment]
I don't get it. Was this change intended? And if yes, why?

**Comment by wapcaplet** [comment]
Confirmed in 0.E-8914-g8c0034b74e. At the smallest zoom level, RetroDays sprites are verging on unintelligible:

![image](https://user-images.githubusercontent.com/238395/104846520-2f7e1f00-5898-11eb-8069-2aa6d93e95d8.png)

But NeoDays is only half that size - here is NeoDays at full zoom-out (each tile is only 4x4 pixels):

![image](https://user-images.githubusercontent.com/238395/104846556-5a687300-5898-11eb-80eb-c02bf343d8cd.png)

**Comment by ZhilkinSerg** [comment]
> 
> 
> I don't get it. Was this change intended? And if yes, why?

Which change?

**Comment by GGgatherer** [comment]
Are you kidding? It's explained in OP. Even with screenshots.

**Comment by ZhilkinSerg** [comment]
> 
> 
> Are you kidding? It's explained in OP. Even with screenshots.

Huh?

**Comment by actual-nh** [comment]
> Huh?

There are before-and-after the change screenshots in the original "posting".

**Comment by Zireael07** [comment]
@ZhilkinSerg: He's asking if the (perceived, shown on screenshots in OP) increased zoom level in some tilesets was intended.

**Comment by actual-nh** [comment]
> @ZhilkinSerg: He's asking if the (perceived, shown on screenshots in OP) increased zoom level in some tilesets was intended.

I think part of the problem is "increased zoom level", which I find rather unclear myself. The problem pointed out by the original issue is that the most-zoomed-in (as in largest magnification) level is too small to see details; there also appears to be the corresponding issue (no pun intended) that the widest field of view (as in least magnified) level is too small to use for anything. (This is my best guess - I don't use tiles.)

**Comment by wapcaplet** [comment]
The problem is clearer when comparing RetroDays with NeoDays, since they have the same tile resolution.

In the "before" version ea3e6a3837, RetroDays and NeoDays have the same apparent sizes at all zoom levels. Fully zoomed out, the reality bubble is about 600 pixels wide:

![image](https://user-images.githubusercontent.com/238395/104856640-16de2b00-58d1-11eb-96bc-7af6cb5d7fe0.png)

In the "after" version ac88c03ac0, NeoDays zoom levels are all significantly smaller than RetroDays. The reality bubble at widest zoom is only 240 pixels:

![image](https://user-images.githubusercontent.com/238395/104856598-d7174380-58d0-11eb-8861-abbb4619b27a.png)

while RetroDays remains around 600 pixels and looks the same as before.

**Comment by wapcaplet** [comment]
Using `git bisect` led me to #46492 when NeoDays was updated in early January.
