### ISSUE TITLE
Plastic Molds are extremely difficult to obtain

### ISSUE THREAD

**Issue by Cyprex** [CleverRaven/Cataclysm-DDA#46948]
# Describe the bug

Plastic molds do not spawn as far as I can tell. The book containing a recipe for plastic molds is exceedingly rare, I've generated 1 lab marked on the overmap, one not marked on the overmap and possibly more unmarked ones. Only 1 unmarked lab had 5 plastic molds books as far as I can tell from grepping the map files. Apart from a few houses at the outskirts pretty much the entire visible city area in the screenshot provided below has been generated(See the autonotes placed if you don't want to just take my word for it).
Among this 2 librarys, a crafts shop, a hardware store, 3 recycling centers and many other things. Note that some are grayed out due to me disabling some of the areas I looted.
Results of grepping: 
Map:  0'96  -1'162  -6
Map:  0'101  -1'168  -4
Map:  0'101  -1'170  -3
Map:  0'96  -1'159  -3
Map:  0'106  -1'168  -5
Turned out to be a lab after checking in debug mode.

From a Discord user having similiar issues:
Svankensen:  plastic molds are uber rare now
Svankensen: Best bet is a lighthouse for the book in my experience
Svankensen: It needs some rebalancing
Svankensen: Or most likely a rework

# Steps To Reproduce

(Note that revealing areas on the overmap is not enough to generate them, you need to actually get reasonably close, areas that enter your reality bubble presumably have to be generated, but the game could also generate terrain outside of the reality bubble, I don't know)
1.Generate a good amount of terrain
2.Run either of these 
`grep -ril "plastics_book" | cut -d'/' -f3- | xargs -L1 python3 /home/orbit/g/CDDA/repo/tools/map_coords.py | grep Map`
 `grep -ril "plastics_book"`
Note that you might need to change the python3 to python in the first variant. With the second version you'll manually have to throw map filenames into tools/map_coords.py to get Overmap coordinates
3.Check what is at the provided overmap coordinates.

# Expected behavior

Plastic molds possibly being found in garages, hardware stores, craft shops.
The book not being very difficult to find.

# Screenshots
![Screenshot_20210122_205820](https://user-images.githubusercontent.com/35031555/105539503-20163000-5cf5-11eb-962b-9aba3232feb9.png)

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Debian; Description: Debian GNU/Linux 10 (buster); Release: 10; Codename: buster; 
- Game Version: 0.E-8924-gc4efd9e-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

This is b11360

# Additional context

Plastic molds were made not autolearn in #44061 along with adding the book and adding it to 4 loot tables, exotic_books, book_survival, textbooks_school and a group for lab bookshelves.
I have not yet generated a school, though it is fairly rare in textbooks_school.
[Exprito.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5858389/Exprito.zip)

**Comment by PaulBlay** [comment]
I started a conversation on the whole plastic mold thing late last year.
https://discourse.cataclysmdda.org/t/should-plastic-mold-recipe-be-in-more-books/25310

Some good suggestions came up, IMO, but nothing actually got as far as a PR.

**Comment by casswedson** [comment]
See this comment https://github.com/CleverRaven/Cataclysm-DDA/issues/45293#issuecomment-730188106 in #45293 
The problem here seems to be that no one is interested in committing the fix, this is relatively easy to do, anyone can do it, see https://github.com/CleverRaven/Cataclysm-DDA/wiki/Guide-to-adding-new-content-to-CDDA-for-first-time-contributors learn to contribute to this project, get the changes *you (note that we have maintainers and curators) want to see in the game.

**Comment by PaulBlay** [comment]
@casswedson If you read the following comments, and this https://github.com/CleverRaven/Cataclysm-DDA/issues/45514 you'll see it's not quite that simple. Plastic molds, as currently defined, probably shouldn't exist. They should be replaced by clay molds and / or 'silicone molds' (although silicone does not exist yet either). They are also only suitable for simple crafting and probably not everything they are used for at the moment. There is also the point that molds really only make sense on a 'per item type' basis. A mold for a plastic mug is useless when making a plastic plate.

**Comment by FeepingCreature** [comment]
Reopen please, the "fixing" PR was reverted and the "proper" fix is languishing. This is an ongoing problem.

**Comment by Zireael07** [comment]
The problem is not that it's difficult to obtain, the problem is that it's overly used. #49422 is probably the way to go, so there's no need to have two issues for the same thing.

**Comment by FeepingCreature** [comment]
There's a difference between arguing solutions and noting problems. The *problem* from a game perspective is that the mold situation is in an unfinished state where many existing recipes cannot be realistically executed because a key piece of them is borderline unachievable. The problem from a *development* perspective is that Plastic Mold was the wrong solution to begin with. But as of current master, Plastic Mold is nonetheless a required component that is very hard to acquire.

A player doesn't care what's going on with the redesign PRs or proposals behind the scenes. The game demands plastic molds. You cannot get plastic molds. This is the ongoing issue with the _game_ (not the codebase), and IMO deserves to be noted as such.
