### ISSUE TITLE
NPC command "keep supply of X item", which would override "don't pickup" 

### ISSUE THREAD

**Issue by Salty-Panda** [CleverRaven/Cataclysm-DDA#46997]
# Describe the solution you'd like

NPC has an order "don't pick up and wear random crap from the street and don't drop your battle-axe in order to wield those exquisite filthy flip-flops"
NPC despite that can pick up bandages to limit of 20, fill up their hip flask of antiseptic, possibly "eat" battery to fill bionic.
Maybe could be used to "always carry one battle-axe" to partially help with NPC constantly dropping their weapons?

# Describe alternatives you've considered

Something like "remember your current inventory and always aim to this state"

**Comment by PatrikLundell** [comment]
Definitely useful if the NPCs could automatically refill their ammo, be it arrows or rocks by recovering ammo spent (and picking up zombie dropped bullets of the correct kind). In the case of "new" ammo (rather than recovering arrows spent) there's a need to respect a limit, as NPCs tend to be weak and thus have a limited carrying capacity.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
