### ISSUE TITLE
Spontaneous total loss of focus during crafting

### ISSUE THREAD

**Issue by xthorgoldx** [CleverRaven/Cataclysm-DDA#47006]
# Describe the bug

While crafting, Focus will spontaneously drop to near-0 every 30 minutes. The drop occurs instantaneously once the game ticks past 30 minutes, regardless of the players' starting focus, morale, or other conditions.

~~Some recipes trigger the focus drain, while others do not unable to identify a common cause at this time~~ Only recipes of high enough difficulty to train skills will trigger focus drain. 

The focus drop seems to be attached to each recipe individually - crafting for 25 minutes on Item A then crafting Item B for 25 minutes won't trigger the drop, but crafting Item A again and crossing 30 minutes will trigger the drop.

# Steps To Reproduce

1. Make a player with access to raw materials for crafting
2. Craft (almost) any recipe that requires more than 30 minutes. 
3. Monitor Focus

# Expected behavior

Focus should drain at a steady rate depending on morale, pain, and addictions.

# Screenshots

Starting crafting of Leather Chaps:
![image](https://user-images.githubusercontent.com/59494135/105646847-c3875200-5e67-11eb-94ff-3da39a353605.png)

After 30 minutes:
![image](https://user-images.githubusercontent.com/59494135/105646862-d8fc7c00-5e67-11eb-956f-bbfb9b43f959.png)

After another 30 minutes (not pictured: focus climbing back to ~25):
![image](https://user-images.githubusercontent.com/59494135/105646872-eb76b580-5e67-11eb-866f-ee3049dc562a.png)

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version (NOTE: Leaving report verbatim; running Windows 7)
- Game Version: 0.E-9115-g9f43baa-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Blaze Industries [blazeindustries],
    Bionic Professions [package_bionic_professions],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    Crazy Cataclysm [crazy_cataclysm],
    SpeedyDex [speedydex]
]

# Additional context

None

**Comment by actual-nh** [comment]
What happens with regard to learning of the skills in use? (I'm wondering if there's a relationship to #46952.)

**Comment by xthorgoldx** [comment]
Skill training has been notably slow, as one would expect from trying to train with 0-20 focus. Sitting down to craft a Baldric (Tailor skill 5/5) with 100 focus yielded 14% skill gain after 5 hours of crafting; 6% of that gain came from the first 30 minutes before the focus dropped to 0. The Leatherworking proficiency increased by 2%, and Garment Closures by 5% (not sure if proficiency training depends on focus). 

Come to think, I don't think I've leveled any crafting skills without skillbooks this build. It wasn't as immediately obvious since I spawned next to two libraries right off the bat.

**Comment by Shadefang** [comment]
I've noticed similar as well. I'm running 0.E-9181-g308bec1 and enough mods I'd want to do vanilla testing before further reporting. The test I did do was with +10 morale, crafting a sleeping bag at 5/4 tailoring. In ~10 minutes I dropped from 90 focus to 10, went from 66 to 71% tailoring, and the progress of the sleeping bag went from 27% to 41%. Finishing the rest of the craft took ~40 more minutes and brought me to 77% tailoring. This is with fast learner and high int, and it took me a three hour wait to regain the focus.

**Comment by xthorgoldx** [comment]
As an additional spot of testing, I boosted my morale up to 271 (fun fact: morale is apparently stored as a signed 16-bit integer - it was fun having -200000 morale for a bit) and triggered the focus loss - still got wiped out to 0.

It's possible this is also an issue caused by commit [448f603](https://github.com/CleverRaven/Cataclysm-DDA/commit/448f6032dff9172e099adab17a9cf94f6edd4f6a) from #46952; if there's a focus drain related to crafting that triggers on a certain tick, then it'd make sense that if said drain was 1000x stronger than intended it'd be why focus is completely drained.

**Comment by kevingranade** [comment]
I don't know where you're getting 30 minutes from, please outline your process for determining how it's exactly 30 minutes.

I spawned a character, set skills to 4, gave myself recipes, gave myself materials, and started crafting.
Crafted the leather chaps to mirror your testing.
I continuously interrupted crafting by hitting ., then once the interruption confirmation dialogue was up I repeatedly hit Enter and . to exit the dialogue and then re-enter it as quickly as possible.
Results were as expected, there is a large focus hit and skill gain even once every 5% progress in the craft, then between ticks focus grew rapidly back up to about 50 before the next tick.

Starting from tailoring lvl 4, I was able to craft continuously to reach 60% progress to tailoring lvl 5 in one day.  The fact that progress was consistent in this way is the important thing here, the exact state of character focus at any particular point in time is mostly irrelevant.

I disagree with your expected result:
"Focus should drain at a steady rate"
Proceeding by ticks or every turn is only of marginal importance, in fact when I've tested a single point practice tick per turn, overall practice rate is lowered because the character spends all of their time with a very low focus as opposed to intermittent practice where there is a chance to recover before the next tick.

I don't see any impact to the player here, yes focus periodically bottoms out, but then it recovers over time.

**Comment by Shadefang** [comment]
It would seem my issue is almost purely a display complaint. 

Doing the same test on my character, but with an XL holster and 6 tailoring: the first 5% crafting tick knocked my from 83 focus to 1 and it only regenerated up to 18 before the next tick. 
Doing similar tests on a fresh world and character (leather pants, wool poncho, and kilt) it seems you only have enough time between ticks to regenerate to a reasonable amount of focus if you're crafting something which takes an extremely long time to craft (such as leather pants when you lack the proper proficiencies). 

After my minor testing this doesn't seem to impact skill gain rates over time, but from a player information standpoint it's confusing. The information you're given about focus tells you that the level it's at directly affects skill gain rate. If you're crafting something that isn't taking an extremely long time between the 5% ticks (say, something that only takes 8 hours to craft as opposed to a day and a half) you'll likely spend the entire time you're crafting under 25 focus (displayed in red) which, according to how the game tells you focus works, means your experience gains should be tanking.

Given that my testing showed similar rate of skill gain over ingame time, it seems the rate of experience gain is fine and the issue is the game giving you incorrect information as to what impact your focus is having on your learning.

**Comment by xthorgoldx** [comment]
After going back through the recipes used for testing, you're right - it's not necessarily on 30 minutes, it is on 5%; by coincidence of proficiency detriments and weariness all the items I tested ticked through (quite consistently) at 30 minutes. 

However, regarding focus loss: "substantial" is an understatement. I raised morale to its limit and bumped focus up to 387 (in this case, while crafting - the focus loss from crafting training is still _total_. As noted by continued testing, it appears to even out in the long run in terms of overall skill gain... but it's certainly odd to see. Notably, the total focus loss only seems to occur for very long recipes.

* Peasant Flail (3/3 Fabrication 0/2 Bashing, 2 proficiencies missing) - total loss of focus per 5% tick over 3 hours (out of 9 hours total due to 3x time), gained 20% skill (5% Principles of Leatherworking Proficiency)
* Razorbar Katar (4/4 fab, 1 missing proficiency) - net loss of 6 focus per 5% tick on 1 hour recipe, gained 15% skill (2% Carving)
* Razorbar Katar x5 (as above) - total loss of focus per 5% tick on 5 hour recipe, 29% skill (4% carving)
* Razorbar Katar (as above) - as with above single test
* Quarterstaff (2/2 Fabrication, 1 proficiency missing) - net loss of 5 focus per 5% tick over 30 minute recipe
* Quarterstaff 10x (as above) - total loss of focus per 5% tick on 6 hour recipe

**Comment by PaulBlay** [comment]
> Results were as expected, there is a large focus hit and skill gain even once every 5% progress in the craft, then between ticks focus grew rapidly back up to about 50 before the next tick.

I think the problem is that that is only 'as expected' if you know how the code works. In other parts of the game focus is something that slowly changes while you are driving / whacking zombies / whatever. I don't think this is necessarily a BUG but I would suggest as a feature that it would be desirable for focus drop / skill increase to happen more frequently when 5% of a craft progress is a long time.

I once made a pair of winter survivor gloves that took me about two game weeks to complete. (Ouch).

**Comment by Shadefang** [comment]
> I don't think this is necessarily a BUG but I would suggest as a feature that it would be desirable for focus drop / skill increase to happen more frequently when 5% of a craft progress is a long time.

Pretty much my thoughts. Whether or not the tick frequency is changed the focus display should be showing your effective experience multiplier, as that's what it's intended to represent, as opposed to jumping around wildly and showing numbers that seem to end up being largely disconnected from what actually is happening. I say disconnected because for me the crafts that were cycling between 0 focus and 20 were giving me approximately the same hourly experience rate as the ones jumping between 0 and 60.

**Comment by Sahblade** [comment]
Focus and experience seem to be acting very differently from what I remember. No matter what I'm doing, fighting, crafting, driving, shooting arrows at a target, my focus constantly drops to 1 from any number and takes hours to gain back. Gaining experience is slowed to a standstill. I can kill hundreds of zombies and not gain 1 level in melee from 3, is that normal? Reading books still acts the same, and is 1000% more conducive to actually gaining levels. I don't think this is simply a display bug.

Let me know if focus and experience rates have been nerfed since a month ago, I honestly don't know if this is simply a change or not.

**Comment by RogerKrunswick** [comment]
This isn't strictly a UI bug.  It also affects proficiency learning.  As long as you are gaining skill crafting, focus will be 1 when the proficiency learning calculation is done.  This leads to proficiencies staying very close to 0% until the skill is at cap for that craft.  The relevant lines in are 1760 and 1763 in activity_actor.cpp

**Comment by ferociousdork** [comment]
It appears this is caused by the [square term introduced here](https://github.com/CleverRaven/Cataclysm-DDA/commit/448f6032dff9172e099adab17a9cf94f6edd4f6a#diff-4fb59232b9e70232ceadaef037d3091e34e4a773b8d2c7fba8f488c15bdd6955) (line 2365). Since `focus_drain` is generally just `amount`, the drain scales with the square of the amount (i.e. if an activity yields twice as many points, it drains 4 times as much focus). This is why longer activities are most affected.

An option could be to change it to exponential decay (`focus_pool *= std::exp(-FOCUS_DECAY * amount)`, for some constant FOCUS_DECAY). This has the desirable property that the decay by an amount `X`, followed by the decay by an amount `Y`, is the same as the decay by `X + Y`. Hence it would treat long and short activities equally.

**Comment by PaulBlay** [comment]
>  As long as you are gaining skill crafting, focus will be 1 when the proficiency learning calculation is done.

The proficiency learning takes the focus at the end of every period of activity, not the start, then? Perhaps it should take the average of the start and end point at least that way the first chunk would count towards proficiency gain.

**Comment by RoyBerube** [comment]
Here is a running printout of focus and current time from `Character::practice()` while crafting a shortbow on a character with 1 in all skills. Focus in this example started out at 92.

<img src=https://user-images.githubusercontent.com/30374490/115135308-dfb50e00-9fd4-11eb-969e-465d2d0f0a37.png width =500px>

Going by Kevin Granade's comments in #47186 leads me to believe that the problem of losing so much focus while crafting is that practice() is just called too frequently. We can't really touch practice() without affecting practice on anything not crafting.

**Comment by RoyBerube** [comment]
I've spent some time running some tests and trying a few changes. Not happy enough with the results to submit a PR however. From what I can tell there are 3 problems right now with crafting affecting training and focus.

1.  As ferociousdork mentioned above, the square is a problem here:
  https://github.com/CleverRaven/Cataclysm-DDA/blob/3cd92bed7f2acd4b49fe82da77119c3b5454b308/src/character.cpp#L2427
The problem is that any practice that saves up a big value applies the focus loss well in excess as compared to if it did the same amount in smaller time increments. IMO any formula used here that uses exponents will cause issues - there can be no curve to the equation or the result is distorted according to how large the value is. I know the intention is to slow down focus loss at small values, but the effect at large values is causing problems.
Perhaps the answer is to apply a linear equation at large values, and to apply the quadratic equation within a loop at lower values. Think of it as rough integration; calculus.
2. Small values are affected by this line:
 https://github.com/CleverRaven/Cataclysm-DDA/blob/3cd92bed7f2acd4b49fe82da77119c3b5454b308/src/character.cpp#L2421
The 1% value is always selected for small increments. When the method gets called every 5 seconds, this results in drastic loss of focus within a few minutes. 
3. Crafting training seems way too high right now. Going from 0% tailoring to 1% within 5 minutes seems a bit fast. Some balance is badly needed here imo.

**Comment by kevingranade** [comment]
Obsoleted by #47186
