### ISSUE TITLE
Commune cannot be generated when accepting Refugee Center's merchant mission.

### ISSUE THREAD

**Issue by Quintovir** [CleverRaven/Cataclysm-DDA#47040]
# Describe the bug

I'm having the same problem as #40352. When I talk to the merchant to start the first mission for the commune I get a debug log.

# Steps To Reproduce

1. Talk to the merchant.
2. Ask if he needs help.
3. Accept mission.

# Expected behavior

A commune location and a tracking marker for it should be generated.

# Screenshots

N/A

# Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: ManjaroLinux; Description: Manjaro Linux; Release: 20.2.1; Codename: Nibia; 
- Game Version: 0.E-9136-gdc59dbd7db [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Blaze Industries [blazeindustries],
    No Fungal Monsters [No_Fungi],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

Crash.log, Debug.log, and save file.

[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5871935/save.zip)

**Comment by PaulBlay** [comment]
Loaded game save, can confirm bug. I did a bunch of teleporting around and 'r'evealing maps and didn't spot any ranches. There was plenty of space where a ranch could be created, though, so maybe the 'create' part of "find and create" is having trouble? 

 DEBUG    : Unable to find and assign mission target ranch_camp_67.

 FUNCTION : cata::optional<coords::coord_point<tripoint, (coords::origin)1, (coords::scale)2> > find_or_create_om_terrain(const tripoint_abs_omt&, const mission_target_params&)
 FILE     : src/mission_util.cpp
 LINE     : 249

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.E-9155-g1319073-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Blaze Industries [blazeindustries],
    No Fungal Monsters [No_Fungi],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by actual-nh** [comment]
@Venera3, any ideas?

**Comment by Venera3** [comment]
It used to be a guaranteed spawn on all overmaps (barring lake shenanigans), that got reduced to about 1/4. The problem seems to be that the mission doesn't actually search the neighboring overmaps. Thank you, I'll look into it. 

(In the meantime you have a one-time, non-transferable coupon to debug-spawn it in without guilty conscience : ? for keybinds -> assign a key to Debug Menu -> press key -> choose `M`ap -> `O`vermap editor -> find a suitable spot and press `s` -> `/` to filter ranch_camp and Enter to plop it down )

**Comment by Venera3** [comment]
Alternatively, you can drop this into your data\json\npcs\refugee_center\surface_staff folder and take the high road.
[NPC_free_merchant_shopkeep.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5876122/NPC_free_merchant_shopkeep.zip)

Funnily enough, you already discovered a ranch camp, southeast from Webster or such, but the mission really wasn't looking at all. Do keep this issue open so that we have a hub for it if someone stumbles upon it before I'm done with my overmap patch ( I expect some more surprise features, tbh).

**Comment by Quintovir** [comment]
Debugging a ranch_camp in works. I completed the first quest (prospectus) and I was able to accept the merchant's next quest.
