### ISSUE TITLE
Insert with nested containers is confusing ('Insert' function of wallet appears broken)

### ISSUE THREAD

**Issue by PaulBlay** [CleverRaven/Cataclysm-DDA#47070]
# Describe the bug

When you examine a wallet in your inventory there is an option to 'i'nsert objects into it. However choosing 'i'nsert can produce an empty list saying there is nothing in your inventory.

# Steps To Reproduce

1. Load save game ( [Narnia.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5883261/Narnia.zip) )
2. Select a wallet from the 'i'nventory. (Try 'wallet' first)
3. Hit [enter] to examine it
4. Choose to 'i'nsert something into the selected wallet
5. (a) Be told "Your inventory is empty" 
    (b) Select some Merch and put it in your selected wallet.

# Expected behavior

You should be able to put Cash Cards, Merch, Dollar bills, Discount cards, etc. into your wallets. And not just when the game feels like it.

# Screenshots

![walletfail](https://user-images.githubusercontent.com/54060142/106054571-1f5e0f00-60e4-11eb-90bd-a227dbb32f85.png)

# Versions and configuration

- OS: Windows x64 8.1
- Game Version: 0.E-9155-g1319073-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    No Fungal Monsters [No_Fungi],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

# Additional context

Which wallets work / don't work is variable, but consistent until they change. i.e. If the 'Stylish Wallet' doesn't work once then it will continue to not work ... until you do something else ... and then it might start working. I have not been able to work out what the 'something else' is.

From loading the attached save ( [Narnia.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5883261/Narnia.zip) ), I have the following results:
* Duct tape wallet ... WORKS
* Large wallet ... WORKS
* Leather wallet ... WORKS
* Stylish wallet ... WORKS
* Wallet ... DOES NOT WORK
* Travel wallet  ...  WORKS (But I forgot to put one in my inventory. There is one on the ground a few tiles away)

This set of results is NOT consistent. All of the wallets <s>(apart from the normal 'wallet')</s> have failed to work at some point.

**Comment by BrettDong** [comment]
Travel wallet has pocket item restrictions:
```json
    "pocket_data": [
      {
        "pocket_type": "CONTAINER",
        "rigid": true,
        "max_contains_weight": "600 g",
        "max_contains_volume": "500 ml",
        "moves": 400,
        "item_restriction": [
          "cash_card",
          "gasdiscount_silver",
          "gasdiscount_gold",
          "gasdiscount_platinum",
          "id_science",
          "id_military",
          "id_industrial",
          "fp_loyalty_card",
          "robofac_test_data"
        ]
```
So you cannot put Merch into travel wallet.

**Comment by PaulBlay** [comment]
@BrettDong Well, that's OK. But also a pain in the backside, because it now means my save file is no use for confirmation.

The screenshot is from the 'Stylish Wallet' which I trust doesn't have the same pocket item restrictions? Even if it does then there's still a bug there because it lets me put in Merch sometimes but not other times.

**Comment by PaulBlay** [comment]
@BrettDong Good news, for my sanity. I now have a save where the normal 'wallet' doesn't work but the others do. I will update the original report in a moment.

**Comment by BrettDong** [comment]
Both wallet and cards are stored in the pants and #46913 forbids the insertion. CC @Jamuro-g

**Comment by BrettDong** [comment]
> I now have a save where the normal 'wallet' doesn't work but the others do.

This time it's because the pants pocket where you put your wallet in is full. Inserting cards into a wallet enlarges the volume of the wallet, and the pocket is full, so the game forbids you inserting anything to the wallet. Dropping the pair of welding goggles, which is placed in the same pocket together with the wallet, solves the problem.

**Comment by PaulBlay** [comment]
@BrettDong Wow. That is super un-intuitive.

How about this, when you insert objects into a wallet (and probably other containers) you wield the wallet first. That prevents any strangeness about wallets not working because they are in too small a space, and is also more realistic. I don't know about you, but I have never tried putting notes into my wallet while it is still in my trouser pocket.

**Comment by BrettDong** [comment]
I think what can be improved here is user interface. Would be better to let player know the reason why some items can't be inserted.

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/bird-litter-cannot-be-inserted-into-a-plastic-bag-git-00efc6d7fe/25823/2

**Comment by Fosheze** [comment]
I like the idea @PaulBlay had of wielding the container before doing anything with it because it makes sense that you can't put a card into your wallet while that wallet is still in your pocket and wielding the wallet first would resolve this issue completely. However from a gameplay perspective it would be fiddly and annoying to have to put your weapon down every time you wanted to interact with your inventory. 

To that point, is it possible to create a pseudo off-hand wielding location which isn't directly usable by the player. This would effectively be a way to wield a second item like a container or an in-progress craft while that item is actively being worked on without having to drop whatever the player was holding before. Whenever whatever action the player was doing with that item is done or canceled the item is automatically unwielded either to the players inventory or the ground (with a message) if the inventory is full. It would basically be abstracting the player setting down whatever they were holding before, working on the item, then picking back up whatever they were holding before without adding a whole bunch of key presses.

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/tac-dump-pouch-doesnt-accept-small-bottles-and-other-items/24983/3

**Comment by PaulBlay** [comment]
I've just found something already in CDDA that I didn't know about.

I had a sewing kit in my inventory, and reloaded it with more thread. Here's the log messages:

```
You reload the sewing kit with thread.
The sewing kit no longer fits in your inventory so you drop it instead.
```

I would view this as a much preferable way of handling inserting items into non-rigid containers.

```
You insert 210 Merchs into the wallet.
The wallet no longer fits in your inventory so you drop it instead.
```

**Comment by wapcaplet** [comment]
The lying "Your inventory is empty" message has bothered me for [quite some time](https://github.com/CleverRaven/Cataclysm-DDA/pull/41122#issuecomment-640235279), since it is almost never literally true (and not just for wallets). It can mean any of several things:

- Container is completely full and cannot hold any more
- You have no items that fit (in the pocket with the most capacity):
  - No items fit in the remaining volume
  - No items fit in the remaining weight
  - No items fit in the maximum length
- You have no items that satisfy the container's pocket type or flag restrictions:
  - No more liquid of the same type (ex., bottle or gallon jug half-filled with water)
  - No items have compatible flags (ex., leather belt that can only hold tools with `BELT_CLIP`)
- (probably other edge cases I haven't thought of)

That would be a lot of special case handling just for an informational message, but it would also be cumbersome to list them all and make the player figure it out. Changing the message to be less false, like "You have no items that can be inserted", would be one alternative, but again forces the player to deduce which of the above cases applies. Unfortunately I don't have a good solution to suggest.

**Comment by moll** [comment]
I've got to agree that the current solution is rather confusing. For example, I thought I'd stash all of the collected mutagen samples in a sack, which should hold both 15L and 15kg. Yet after 4 bovine samples, nothing shows up in the "Insert" menu. Now I've no idea why it's not letting me insert more — individual samples are said to be 6cm long and weight very little... Sure there's a reason, modulo a bug, but that should be communicated clearly, preferably at the of inserting — in the insert menu.

**Comment by moll** [comment]
Hey, what exactly is _not planned_ about this? This issue is about the usability of the insert functionality. Surely usability is something worthwhile to improve...

**Comment by Zireael07** [comment]
It was auto-closed for being stale, I guess. My main problem with the auto-closer is, even if "closed issues are still considered", how are contributors supposed to find actionable ones like this one is, among the sea of simply outdated things?
