### ISSUE TITLE
Unload to ground function similar to "D"rop items. 

### ISSUE THREAD

**Issue by ynemo** [CleverRaven/Cataclysm-DDA#47083]
# Is your feature request related to a problem? Please describe.
Sometimes it is needed to unload a bag with loot, and maybe you prefer not to mess loot with items in your inventory.

# Describe the solution you'd like
Why not add Unload to ground function, similar to "D"rop function.  
The new interface could be like this:
"u" - unload to inventory
"U" - unload to specific tile around player

**Comment by superninjakiwi** [comment]
'u' is used for 'move northeast' by default, so I don't think that 'u' for unload to inventory would happen. However, the need to rifle through things like wallets or backpacks and only take specific items is there; maybe advanced inventory management could solve that problem?

**Comment by Shadefang** [comment]
I don't know about what keybind to put it on (personally I'd probably use the u/U bind but I'm aware not everyone has a numpad) but the ability to easily unload a container onto the ground as opposed to into your inventory is something I've been wanting since I started playing again. You *can* do it through advanced inventory management, but it's rather clunky.

**Comment by superninjakiwi** [comment]
I wasn't actually aware you could do it through advanced inventory management. I assumed something like 'c' would work, but it just says 'you can't put items there!', even on things like backpacks and wallets.

**Comment by Shadefang** [comment]
I was talking about using "c" in AIM. I thought you could but I was wrong. I've not tested it extensively but you seem to only be able to access watertight containers, whether or not you can actually do anything with the container or contents is variable, you can only access 1 at a time, and you can't access nested containers.

**Comment by Nerdy314159265** [comment]
I think this would be a great help, especially with all the new container systems.
It's a pain digging cash cards out of wallets, you either have to pick it up, open the wallet, drop the cash card, drop the wallet, then pick up the cash card or you unload the wallet, then have to dump all the useless items out of your inventory.

I think the container menu is also something that needs to be implemented into the new system.
I'm a little surprised that it released without that support because it can be annoying if you are using containers to organize and manage items to get one specific item (like the wallet example) or a group of items.

**Comment by Night-Pryanik** [comment]
As of 0.F-11086 we have `Unload container` action, unbinded by default.

**Comment by GuardianDll** [comment]
It unload stuff in your inventory, not into the ground

**Comment by Night-Pryanik** [comment]
`Unload container` unloads contents of container on the ground.
