### ISSUE TITLE
Revert Butchering to be possible without a tool with Cutting One

### ISSUE THREAD

**Issue by Froffy025** [CleverRaven/Cataclysm-DDA#47111]
# Is your feature request related to a problem? Please describe.
Butchering is impossible without a tool with Cutting One as of the latest experimental. However, the only available cutting tool for characters with fabrication 0 is a bone shiv, which nearly requires butchering to be an option. You need a bone to get cutting one, and you need cutting one to get bones.
This makes naked and afraid, no skill starts entirely reliant on RNG to forage for a relatively rare bone or chunk of steel, which isn't very fun. Not being able to dig a bone out of a dead creature isn't very realistic, either. 

# Describe the solution you'd like
Remove the requirement of a Cutting One tool in order to butcher and revert to being able to use a flint or sharp rock to perform quick butchery on dead corpses.

# Describe alternatives you've considered
- [S]mashing animal corpses can yield butchery refuse and bones, in order to simulate using your hands to tear out bones, but no usable meat. (Similar to pulping zombies, but yielding something useful rather than just spilled blood everywhere.)
- Allowing dismembering a corpse to use a tool without Cutting, and yield bones.
- Give flint, sharp rocks, glass shards, and glass shivs Cutting One
- Debone option when butchering that doesn't need Cutting
- Revert stone knife to be craftable without Fabrication 3 

# Additional context
Add any other context (such as mock-ups, proof of concepts, or screenshots) about the feature request here.
![image](https://user-images.githubusercontent.com/78222136/106309216-cdc29b00-622f-11eb-962d-c7ca2ddb9211.png)

**Comment by anothersimulacrum** [comment]
I'll let others comment on the feasibility of digging a bone out of a body with no cutting tools to then use as a cutting tool (I am not making a judgement on the possibility of this), but the expected behaviour from starting naked without required skills in the wilderness is death from exposure - if you have no resources (not even clothes) and no skills in the middle of the New England wilderness in spring, that is what happens.

**Comment by Froffy025** [comment]
My argument isn't against death from exposure, and the bone shiv was feasible enough to already be included in the game. I know that you can definitely remove a whole bone from a dead animal with your bare hands, a flint, and some elbow grease with very little skill - and a "-50 butchering" quality remains on the flint item from previous versions, where it was still possible to do this.
This is a very recent removal and seems like an oversight from my perspective.

**Comment by anothersimulacrum** [comment]
It doesn't seem to be an oversight - #46622 #44212 #42739

**Comment by kevingranade** [comment]
We've covered the "sharp rock as a cutting tool" concept previously and it's a non-starter.  It requires a proper edge and that's not changing.

I wouldn't be against bashing, disassembly, or a new no-tools or even-more-limited-tools butchery option yielding bones among other things.

I'm mildly in favor of various broken glass items having a very marginal cutting ability, but if there's broken glass around you can probably round up *some* kind of knife, so it doesn't really seem like it would change anything.

**Comment by Froffy025** [comment]
Cool! If a new "no-tools" butchery or "hack and smash with a rock 'till I get something" feature was added in the base game, I think it'd make starting in the wild way more fun.  Thanks for being concise and not disregarding the alternatives I mentioned!

**Comment by slimeboy460** [comment]
I'd imagine that pulping a corpse should allow you to gain some sort of bone from it. Due to the fact you could probably pull through the flesh with your hands at that point. 

Also, I'd imagine you could break a bone inside of a corpse, then use it to pierce the skin. But I don't imagine I'll be able to test that.

**Comment by slimeboy460** [comment]
> We've covered the "sharp rock as a cutting tool" concept previously and it's a non-starter. It requires a proper edge and that's not changing.
> 
> I wouldn't be against bashing, disassembly, or a new no-tools or even-more-limited-tools butchery option yielding bones among other things.
> 
> I'm mildly in favor of various broken glass items having a very marginal cutting ability, but if there's broken glass around you can probably round up _some_ kind of knife, so it doesn't really seem like it would change anything.

In the case of wilderness survival, (off of memory) you can find broken glass and bottles in bushes. As well as ceramic shards (but I don't imagine ceramic is as good at keeping a sharp edge). So having this including in the game would make the game a lot easier. The trade off should be that you need a glass shiv or a broken bottle to do this, as they don't have the risk of getting caught in the flesh and cutting your hand open.

**Comment by PaulBlay** [comment]
Flint knapping is a non trivial skill, and getting good flint is a non trivial task. 

That said, regular crappy flint in sufficient quantity bashed together will get you flint shards that are super sharp (at least as sharp as broken glass). They won't be substantial enough to butcher a moose, but I don't see why you couldn't butcher a squirrel with one. I'd suggest they be disposable one-use items and it would take a handful to butcher something as large as a dog.

**Comment by BitBite112** [comment]
Hello, I was the guy who opened up the Reddit thread for this today.

Flintknapping isn't hard depending on what technique you use. If you want to shape glassy rock like flint into a knife or other shape it will take a lot of skill through pressure flaking. You'd need stuff like antler or a rather hard piece of wood for that, but you can also just bash off a flake. This flake usually doesn't have a very good shape, but is sharper than steel because it's harder and because of the way it fractures. I've read it has some niche uses in surgery somewhere because of this.
I believe the pressure flaking method is for more control of the shape such as making notches in arrowheads and making a knife as well as making it more durable and able to repair it's durability by pressure flaking it again when it gets dull.
Simply bashing two rocks together would be percussion flaking and is very easy to so for anyone, even a kid.

**Comment by Shadefang** [comment]
I think the point that's being made here is less that "I should be able to butcher something fully with a rock" and more "If it has the quality, why am I hard locked out of using it?" If it has butchering on it it should be usable for butchering. Not quickly, not effectively. All it is is a poorly made tool that has a better chance of shredding a corpse than your fingernails.

As BitBite112 said, something along the lines of a stone chopper should be doable (albeit slowly and relatively ineffectively) by almost anyone. Purely anecdotal evidence here, but I _did_ do that as a small child. simply bashing rocks together to make a kinda sharp rock. I wouldn't say it has cutting quality, but would definitely be enough to break through skin and flesh with some effort.

My personal thoughts: Allow butchering to happen without a cutting tool, but with hefty penalties on what you can get out of it. Make it slow, restrict it to smaller animals (dog and down is what my gut says) and only give a small percentage of bones, meat, and *maybe* fat, but no chances of skin, sinew, etc.  In my eyes this would be a decent representation of effectively pulping a corpse with just enough effort towards precision to get *something* out of it. 
This lets the sharp rock represent what its name implies: an extremely crude effort at knapping. It doesn't take much skill, can't really be called a cutting edge, but enough to do a bit of damage with.  It also allows the stone chopper/knife to remain at the higher fabrication level it currently has, which to me at least seems to be a decent place for vaguely competent knapping.

**Comment by BitBite112** [comment]
Well, it can be called a cutting edge, it'd be able to cut through hide although not as quickly.
Making "Mode I" tools only requires ape like cognition according to this link and from what it looks like these would be very much be able to cut and scrape, although not as effectively as a knife would.

https://blogs.ntu.edu.sg/hss-language-evolution/wiki/chap-20-stone-tools/#:~:text=1.2%20Oldowan%20tools%20(Mode%201),-Mode%201%20represents&text=Tools%20are%20made%20by%20using,and%20lack%20of%20preparation%20involved.

The wikipedia on lithic reduction also mention a method called "projectile percussion" which literally means to just throw the rock on the ground to hope you get something out of it.

**Comment by Shadefang** [comment]
> Well, it can be called a cutting edge, it'd be able to cut through hide although not as quickly.

I was meaning I wouldn't call it a cutting edge as defined in game by "cutting quality" for the same reason a butter knife or hacksaw wouldn't.  Flint/sharp rock already *has* a butchering quality, albeit one roughly on par with a scythe, and should be usable for crude, ineffective, but still doable, butchery.

**Comment by BitBite112** [comment]
But the thing is is that you can use stone tools to cut with, it's sharper than steel after all, not as well of course because of how much more brittle it is, but you can still do a lot with it.
I don't want to be locked out of many crafting recipes early in the game and have to try and get fabrication up to 3 and survival to 5 in order to craft a cutting tool before I can make anything else.

**Comment by PaulBlay** [comment]
That's why I think having flint shards break after some use is both realistic and good for game balance. I used to mess around with flint a lot as a kid - never managed to make a proper axe / spear head. Every time I was getting close 'clink' the thing would split right down the middle. But you could cut just about anything with a good flint shard, until it went blunt or broke.

**Comment by Shadefang** [comment]
> I don't want to be locked out of many crafting recipes early in the game and have to try and get fabrication up to 3 and survival to 5 in order to craft a cutting tool before I can make anything else.

As far as I can tell you only need fabrication 3, not the survival. The point I was making is that, given the way skills in this are set up, a properly knapped stone knife makes sense to be at this higher fabrication level. I wouldn't be completely against it being lowered, but I don't think it's inherently wrong. Allowing basic butchery without a proper cutting implement as a way to get access to bones would open a route to get access to a cutting tool through successful hunting (the bone shiv). This would be in addition to the preexisting methods of attempting to train your fabrication to 3 to learn to make a stone knife, or foraging in hope of a lucky bone or steel chunk.

> That's why I think having flint shards break after some use is both realistic and good for game balance. I used to mess around with flint a lot as a kid - never managed to make a proper axe / spear head. Every time I was getting close 'clink' the thing would split right down the middle. But you could cut just about anything with a good flint shard, until it went blunt or broke.

An interesting thought, but I'm not sure whether there are systems to allow that implemented, and it might be a bit outside the scope of this discussion.

**Comment by BitBite112** [comment]
How about flint be able to be used as a knife with a 1 in 30 chance of bring deleted every time something is crafted with it? I don't have too much experience with crafting anymore since it's been a long time since I played the game, but  this seems like a decent number, does it?

**Comment by BitBite112** [comment]
Ok, better idea: remove the butchering quality, but add in cutting quality. You'd be using cutting more often than butchering, wouldn't you? By the time you succesfully kill an animal you'll probably have fabrication to 3.

**Comment by Fosheze** [comment]
It's been a while since I've dismembered something but I believe you can get bone from that. What if we just made this simple and said that anything with a butchering of 0 or lower can't be used for anything other than dismembering then remove the cutting requirement from butchering. This would allow all of the garbage items to still be able to net you some bone while still only allowing a player to actually butcher something if they have a decent implement. 

Also while I am looking at the item list it looks like some items could have their butchery values revised a bit. For example a glass shiv has a butchery of -18 while a bone shiv has a butchery of 12. I'm not saying that they should be equal but a 30 point swing is pretty huge. Many of the lower value butchering items look like they could use some adjusting in general. I for one know that you can fillet something pretty well with a properly sharpened axe (especially when that thing is your own hand). It should probably be easier to butcher something with a metal axe head (-50 butchering) than it is to do so with a zweihänder(4 butchering).  Also the "Blade" being -38 is pretty low considering it's what you get from disassembling a meat cleaver.

**Comment by PaulBlay** [comment]
> It's been a while since I've dismembered something but I believe you can get bone from that.

I don't think you can? I only remember getting butcher refuse.

**Comment by Fosheze** [comment]
> > It's been a while since I've dismembered something but I believe you can get bone from that.
> 
> I don't think you can? I only remember getting butcher refuse.

Just dug through the code and it looks like you're right. That should probably be added though. If you're hacking limbs off of a corpse then there are going to be at least a few bones sticking out.

**Comment by anothersimulacrum** [comment]
I haven't seen any complaints since https://github.com/CleverRaven/Cataclysm-DDA/pull/50044 was merged. If there are still any, let me know and I can reopen the issue.
