### ISSUE TITLE
The minimap is all black no matter the lighting conditions with the exception of entities (creatures,robots,etc).

### ISSUE THREAD

**Issue by Quintovir** [CleverRaven/Cataclysm-DDA#47171]
# Describe the bug

The minimap is all black no matter the lighting conditions with the exception of entities (creatures,robots,etc). I don't remember changing the settings/options recently.

# Steps To Reproduce

1. Load the game.
2. Check the time of day.
3. Look at the minimap.

# Expected behavior

The minimap should show a pixelated representation of the surroundings.

# Screenshots

![MINIMAPBUG](https://user-images.githubusercontent.com/28264543/106451063-a0eacf80-644b-11eb-9c9b-dc20b861f65c.png)

# Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: ManjaroLinux; Description: Manjaro Linux; Release: 20.2.1; Codename: Nibia; 
- Game Version: 0.E-9331-gdfd58b5939 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Blaze Industries [blazeindustries],
    No Fungal Monsters [No_Fungi],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]

# Additional context

Save file:

[Champlin.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5903588/Champlin.zip)

**Comment by int-ua** [comment]
#47165

**Comment by PaulBlay** [comment]
I can't reproduce that from the save. I have seen this bug, or a similar one, before, though. I am pretty sure that there's a bug report in github somewhere, but I have been unable to find it.

The one I'm thinking about is where large chunks of the mini-map are blacked out. It could be the same if 'large chunks' covered the whole minimap. One thing about that bug was if you walked through the blacked out area it would 'fix' one pixel at a time where you moved.

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/minimap-is-screwed/25848/3
