### ISSUE TITLE
Butchering: bleeding hangs forever

### ISSUE THREAD

**Issue by sumpfralle** [CleverRaven/Cataclysm-DDA#47233]
# Describe the bug

Try to *bleed* the corpse of an animal (as a butchering action).
The action hangs forever:
* the UI is not responding
* sending a `SIGINT` signal (CTRL-C) unfreezes the UI and presents the expected confirmation dialog for quitting the game

Letting this run for some hours does not produce any progress (the game time visible when sending `SIGINT`) stays unchanged.

# Steps To Reproduce

1. place an animal corpse next to a butcher rack
2. select the *bleed* action in the butcher menu

# Expected behavior

The operation should finish within a reasonable time.

# Versions and configuration

 - OS: Linux (Debian testing)
 - Game Version: 0.E-9353-g6f0e582 (#11429)
 - Graphics version: tiles
 - Ingame language: English
 - Mods loaded: default

# Additional context

Attached you find a save game, that was stored during the bleed action. Thus simply loading the save game causes the UI freeze.
[save-hanging-butcher-bleeding.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5928578/save-hanging-butcher-bleeding.zip)

**Comment by mqrause** [comment]
The blood gets frozen as it comes out of the corpse.
https://github.com/CleverRaven/Cataclysm-DDA/blob/553520093fc0c798ca1655e02288b6b8876f8d7b/src/activity_handlers.cpp#L1006-L1009


The frozen blood then causes an infinte loop since it can't be handled.
https://github.com/CleverRaven/Cataclysm-DDA/blob/553520093fc0c798ca1655e02288b6b8876f8d7b/src/handle_liquid.cpp#L102-L107

**Comment by actual-nh** [comment]
Below that one there are quite a few other places with set_item_temperature to 0.00001 * the corpse's temperature. Umm... what? Was someone thinking heat energy?

**Comment by PaulBlay** [comment]
Bleeding (as a butchering action) should be disallowed when the temperature of the corpse is below its blood's freezing point when you start. I suppose you could have bleeding prematurely halt with only partial amounts of blood collected when the air temperature is below that point.

Freezing point* of blood is -2 Centigrade (28 Fahrenheit)
 * Technically, blood doesn't have a freezing point, but -2 is when the liquid plasma freezes and by -3 the liquid in various cells is also frozen. 
Freezing point of acid blood is up in the air because it would vary widely depending on how concentrated the acid is (and what components it has).

**Comment by actual-nh** [comment]
The temperature of the corpse and the blood should, at least initially, be equal. (And I agree that if it's below freezing temperature, bleeding should be rather difficult to even start...)

**Comment by mqrause** [comment]
The temperature of an item is stored as an `int` in 0.00001K, but the method takes the temperature in 1K as an argument. Inside it gets multiplied by 100000 again. There's other places like weather that handle temperature in different units, so awkward things like this are bound to happen.
