### ISSUE TITLE
Island Prison: Better rewards for the prisoner's mission

### ISSUE THREAD

**Issue by Termineitor244** [CleverRaven/Cataclysm-DDA#47295]
# Is your feature request related to a problem? Please describe.
As mentioned in #47282, the rewards for the mission in the Island Prison are basically worthless, they give you a little of food (**A single** can of beans), as reward for going to where a Zombie Hulk is, take his things from a safe in his office, and deliver it to them, this in what is probably a day one mission, so a pretty hard mission, and one in which they ask you to deliver something that opens a a door to the best loot in the whole island, but the only reward you receive is a can of beans and a clue to a way to get out of the prison, the clue is fine, but, a **single** can of beans? When they have a lot of food and other things stored for them? 

# Describe the solution you'd like
They should at least let you commerce with them or contract them as mercenaries, or, well, something, it's a pretty difficult mission and the leader can get the best stuff in the whole island if you give him the ID. And, if you don't give him the ID, those things can be yours, and you can easily take all of their food, I demand a better reward for this mission, at the very least give me a gun, or a set of armor taken from one of the dead guards... But again, I would prefer a little of respect from the prisoners.

**I mainly suggest:**

As a reward, they are ready to commerce with you some of the food they have stored, some of the things from the room that is opened with that ID (Of course they are gonna sell you in an overpriced manner the things that you just basically deliver to them, I mean, they are criminals okay?) like armor or tonfas, they can ask for weapons, armor, or they can give you a repeatable mission to "prove your manliness" killing the zombies from the island for them, in exchange for some money only usable with them...

Another possible reward, and one more in line with a bunch of criminals, is that they could offer to work with you as mercenaries, for a price of course.

# Describe alternatives you've considered
More cans of beans, I mean, one? That isn't enough for even half a day of activity! Give me a gun, the can of beans and a little of respect from the prisoners, and I will call it a day, I want them to at least return some chit chat and not swear me out of their sight just for daring to speak to them.

# Additional context
ping @Night-Pryanik

**Comment by Night-Pryanik** [comment]
The single can of beans as a reward is intended.

> But again, I would prefer a little of respect from the prisoners.

Nope. You're literally **nothing** to prisoners and their leader, and even if you complete their mission, you're still **nothing**, and they have absolutely no reason to give you anything at all. In fact, I added a can of beans as a reward at the very last moment to provide a little help to players, initially there was no reward except for the clue.

Actually now I even want to add a dialogue in which player character furiously asks about such a tiny reward, and it instantly angers the leaders and his band so they become hostile.

> it's a pretty difficult mission and the leader can get the best stuff in the whole island if you give him the ID.

The difficulty of mission is irrelevant here as I was trying to simulate a dialogue between two living persons and not between two game characters, and since it's ok to be fucked up with rewards IRL, even after a difficult job, I made prisoner leader fuck player character with rewards ingame. 

> And, if you don't give him the ID, those things can be yours, and you can easily take all of their food

Go ahead and don't give the ID and take all those things by yourself. 
Or - you don't like the rewards? Kill the quest-giver and take their loot as a reward by force.

**Comment by Termineitor244** [comment]
> Actually now I even want to add a dialogue in which player character furiously asks about such a tiny reward, and it instantly angers the leaders and his band so they become hostile.

Actually, I would very much like that, obviously, as an option, there should be some players/people that don't explode even with that level of discourtesy (high way robbery!).

I accept the can of beans as an intended reward, I mean, I would like to be able to do something with the prisoners, but I understand the reasoning, but I strongly like that proposal of furiously asking what is he/she thinking giving me only that, only for the whole gang to come down on me.

**Comment by ZhilkinSerg** [comment]
You receive whole can of beans. They could've just beat you and leave you in the can instead.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
