### ISSUE TITLE
Start traits don't count towards mutation thresholds

### ISSUE THREAD

**Issue by KittyTac** [CleverRaven/Cataclysm-DDA#47306]
# Describe the bug

As said in the title, starting traits don't give you points towards thresholds. This just doesn't make any sense. E.g if you play as a mutant with lupine traits, you don't get any closer to the lupine threshold. Probably not WAD.

# Steps To Reproduce

1. Make an experiment/lab challenge character.
2. Give them some traits that count towards a specific threshold.
3. Check thresholds with Debug -> Info -> Show Mutation Category Levels, it will be blank.

# Expected behavior

You get pushed closer to a threshold.

# Screenshots

Not needed.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-9314-ga17d18f-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    No Rail Stations [No_Rail_Stations],
    Tankmod: Revived [Tankmod_Revived],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Tankmod: Revived - UndeadPeople Tileset [Tankmod_RevivedUDP]
]

# Additional context

A workaround is giving yourself the traits after starting, using the debug mutate menu. Then they count.

**Comment by actual-nh** [comment]
For cases where a trait, while associated with a mutation "line", is a pretty ordinary one, I can see arguments both ways. If it's specified that the trait is unusual and/or it's a setup like an experimental mutant, I agree that they should be counted (particularly since you'd still need the right serum even if the traits were otherwise enough to push you to checking the threshold).

**Comment by RadHazard** [comment]
> Possibly some of this could be handled by having starting traits counted only for the traits themselves - not, as is the case for subsequent mutations, partially according to what the mutation can lead to and/or its prerequisites?

I don't know, that seems a bit weird to me.  A long tail is explicitly supposed to be halfway to a fluffy tail, and that's what the current category strength algorithm represents.  It'd be weird if you got full threshold points for the long-tailed mutation lines and absolutely nothing for the fluffy-tailed lines just because you started with the tail (especially since you were presumably grew the tail via mutagen anyway).

Perhaps the best way to handle this is to treat starting mutations (i.e. the traits that experimental mutants can get but regular starts can't) as mutations and not inherent traits.  That'd make sense since normal starting traits like strong stomach are presumably just individual quirks and not a sign that you're starting to mutate into a rat or whatever.  It would also fix another longstanding issue/weirdness where experimental mutants can't purify their starting mutations away.

**Comment by actual-nh** [comment]
Note also #48172.

**Comment by wapcaplet** [comment]
Confirmed, still affects version 0.F-4108-gfa916867f5

**Comment by wapcaplet** [comment]
After some digging, I believe this is because the `Character::get_mutations` function (used by `Character::set_highest_cat_level` to determine thresholds) only includes mutations from the `my_mutations` map, and none of those from the `my_traits` map (where all the starting traits are).

**Comment by dseguin** [comment]
@wapcaplet I didn't realize you were working on this until I started. I've got a working PoC in case you're still looking into it: https://github.com/dseguin/Cataclysm-DDA/commit/5daac0b8a528e93c91441993e9ba84a21d7f615d

**Comment by wapcaplet** [comment]
> @wapcaplet I didn't realize you were working on this until I started. I've got a working PoC in case you're still looking into it: [dseguin@5daac0b](https://github.com/dseguin/Cataclysm-DDA/commit/5daac0b8a528e93c91441993e9ba84a21d7f615d)

It looks like you got a lot further than I did. All I accomplished was to learn that a whole bunch of Character functions depend on `get_mutations()`, which does not include any starting mutations. Only `get_base_traits()` returns the starting mutation list.
