### ISSUE TITLE
Uncanny Dodge CBM: incorrect energy cost

### ISSUE THREAD

**Issue by MobiusOblidus** [CleverRaven/Cataclysm-DDA#47416]
# Describe the bug

Uncanny Dodge CBM states its Action Cost as '6J'
However, it's actual Action Cost is '75kJ'

# Steps To Reproduce

1. Spawn an Uncanny Dodge CBM (Sterile)
2. Use an Autodoc to install the CBM (plus Power Storage & a power supply CBMs if required)
3. Charge pawn's Bionic Power
4. Take note of Bionic Power total
4. Activate Uncanny Dodge CBM, and engage in melee combat
5. Pass turns still until your pawn dodges an attack (indicated by moving away from the source of attack by 1 tile)
6. Check Bionic Power total. It will show a power loss of more than or equal to 75kJ per dodge

# Expected behavior

Stated Action Cost should match actual Action Cost, one way or the other.

# Screenshots

![Uncanny Dodge 6J Act Cost](https://user-images.githubusercontent.com/76887621/107572560-57854780-6be4-11eb-8052-427a7e1912ba.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-9555-gfe798ae-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    No Rail Stations [No_Rail_Stations],
    No Fungal Monsters [No_Fungi],
    Bionic Slots [cbm_slots],
    Disable NPC Needs [no_npc_food],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughKills]
]

# Additional context

N/A

Edited: kJ not MJ!

**Comment by anothersimulacrum** [comment]
> However, it's actual Action Cost is '75MJ'

75 kJ (kiloJoule)? 75 MJ (MegaJoule) is about 37.5x the bionic power cap, and 75mJ (milliJoule) is pretty microscopic.

**Comment by MobiusOblidus** [comment]
> > However, it's actual Action Cost is '75MJ'
> 
> 75 kJ (kiloJoule)? 75 MJ (MegaJoule) is about 37.5x the bionic power cap, and 75mJ (milliJoule) is pretty microscopic.

Yes - you're correct, I should have put kJ. Will edit the original text. Thanks!

**Comment by Salty-Panda** [comment]
The listed amount is a passive cost, the same as it used to be with Nanobots.
The energy consumption of looking for incoming bullets is way lower than rapidly moving dozens of kg to the side.

I would suggest a change in the description. Possibly someone could calculate the power needed to quickly shove e.g. 60kg about 30cm to the side.

**Comment by Fosheze** [comment]
> The listed amount is a passive cost, the same as it used to be with Nanobots.
> The energy consumption of looking for incoming bullets is way lower than rapidly moving dozens of kg to the side.
> 
> I would suggest a change in the description. Possibly someone could calculate the power needed to quickly shove e.g. 60kg about 30cm to the side.

The thing is that the power usage doesn't need to come entirely from the bionic and it wouldn't make sense to do so. People being blasted across a room by electricity is an actual thing that happens but it isn't the electricity that is moving them; electricity doesn't have enough physical force behind it to do that even with a large discharge. When you get electrocuted it causes muscles to contract much faster and harder than the body would normally let them. If that happens in the right way it can make your own muscles launch you literally across a room.

It would make sense for this bionic to be using that mechanism in a controlled manner rather than using some much more power hungry schizo tech to do something else. All it would take is some electrodes in the muscles and a processor somewhere which determines what muscles need to twitch and when they need to twitch. This tech already exists in the real world to a much lesser extent. It's used by people with neurological disorders to help them move when their nerves stop being able to control their muscles ([NMES/EMS](https://en.wikipedia.org/wiki/Electrical_muscle_stimulation)). Someone I knew personally had a special leg brace that did exactly that and it really didn't use much power; I don't know the exact power requirements but they could walk normally for a whole day off of a battery pack about the size of a Nokia 3310. Obviously dodging bullets is going to take a bit more juice and doing so frequently would be damaging to the muscles however it would be a shorter duration power requirement and a whole lot less damaging than a bullet. Besides, if you're frequently dodging bullets then you are probably doing something wrong.

**Comment by MobiusOblidus** [comment]
> The listed amount is a passive cost, the same as it used to be with Nanobots.
> The energy consumption of looking for incoming bullets is way lower than rapidly moving dozens of kg to the side.

I agree that one of those listed costs is the passive cost of looking for incoming threats / just being active but not engaging its power. 

But at a glance, I would read the current text as already displaying two separate costs: 6J per action, and 6J per turn (if nothing activates the CBM's 'action', which in this case is a super-dodge.)

So in my head, with current numbers, the cost text should read: "75 kJ act, 6 J/turn"

**Comment by MobiusOblidus** [comment]
> The thing is that the power usage doesn't need to come entirely from the bionic and it wouldn't make sense to do so. 
>...When you get electrocuted it causes muscles to contract much faster and harder than the body would normally let them. If that happens in the right way it can make your own muscles launch you literally across a room.
> 
> It would make sense for this bionic to be using that mechanism in a controlled manner rather than using some much more power hungry schizo tech to do something else. All it would take is some electrodes in the muscles and a processor somewhere which determines what muscles need to twitch and when they need to twitch.
>
> This tech already exists in the real world to a much lesser extent. It's used by people with neurological disorders to help them move when their nerves stop being able to control their muscles ([NMES/EMS](https://en.wikipedia.org/wiki/Electrical_muscle_stimulation)). 
>
> Obviously dodging bullets is going to take a bit more juice and doing so frequently would be damaging to the muscles however it would be a shorter duration power requirement and a whole lot less damaging than a bullet.

This actually sounds pretty great.

So to simulate this in game would adding a small amount of 'Weariness' to the player character per Uncanny Dodge activation work? To simulate muscles being forcibly actuated beyond their normal abilities/safe threshold of use by electrodes & high voltage currents? Equally, the current 75mJ cost-per-dodge could be substantially reduced to both balance the addition of a small Weariness cost to the player, and to reflect that the CBM itself was not putting all of the effort into the action - it's just puppetting the player pawn's own muscles.

**Comment by actual-nh** [comment]
> This actually sounds pretty great.

Agreed.
 
> So to simulate this in game would adding a small amount of 'Weariness' to the player character per Uncanny Dodge activation work? To simulate muscles being forcibly actuated beyond their normal abilities/safe threshold of use by electrodes & high voltage currents? Equally, the current 75mJ cost-per-dodge could be substantially reduced to both balance the addition of a small Weariness cost to the player, and to reflect that the CBM itself was not putting all of the effort into the action - it's just puppetting the player pawn's own muscles.

Weariness and/or Pain, I would think (even if the CBM stimulates the nerves instead of the muscles directly, the muscles may well be protesting...). For current use, probably some Weariness always and some chance of a variable amount of Pain - that would justify cutting the activation cost from 75 kJ to at most equal to the per-turn 5 J cost.

Further on, something can perhaps be done about this completely overriding any Dodge attempts by the character, even ones that would have been successful (also resulting in no training of the Dodge skill, BTW). If something is happening too fast for any "normal" Dodge to work, that's fine, but sometimes it isn't. However, if you failed to dodge, and it wasn't because you ran out of dodge attempts, it'd probably have to do more to fix what you'd screwed up - definite Pain.

Also further on, it doing an Uncanny Dodge should also mess up weapon aiming, unless you were being helped on that by other CBMs.

**Comment by Fosheze** [comment]
> Weariness and/or Pain, I would think (even if the CBM stimulates the nerves instead of the muscles directly, the muscles may well be protesting...).

I agree with the pain. The normal EMS units don't hurt; they're just uncomfortable if you aren't used to it. With this thing twitching you fast enough to dodge a bullet I imagine it would feel like a bad cramp at best.

> Also further on, it doing an Uncanny Dodge should also mess up weapon aiming, unless you were being helped on that by other CBMs.

What about simply applying the "dazed" effect for a few rounds. It tanks your perception and drops dex a bit so it would do a good job at tanking your shooting abilities when active but could still be somewhat mitigated by other CBMs. The description is even still usable for this application as I imagine that having your body suddenly lurch on it's own would leave you a bit shook up. Of course you don't want it to last too long or the CBM starts to look like a negative but 2 rounds should be just enough time for whatever shot you to start getting get another shot off. That way you can't just deliberately sit in the line of fire, aim, dodge the bullet, and immediately shoot back after being shot at.

**Comment by GGgatherer** [comment]
> Possibly someone could calculate the power needed to quickly shove e.g. 60kg about 30cm to the side.
Been there, done that.
https://github.com/CleverRaven/Cataclysm-DDA/issues/37995#issuecomment-602631182

> So in my head, with current numbers, the cost text should read: "75 kJ act, 6 J/turn"
`act` is *initial* activation cost, not proc cost. That one is not stated anywhere except maybe description for some bionics (prob.travel have it).

**Comment by Salty-Panda** [comment]
Sure, but unless you would like to imply installing internal servos in your body, the version with "stimulate muscles with electricity in order to move the body" makes more sense.

**Comment by actual-nh** [comment]
> Sure, but unless you would like to imply installing internal servos in your body, the version with "stimulate muscles with electricity in order to move the body" makes more sense.

Definitely, although the 10 kJ figure may be of interest (with some estimates of muscular efficiency) in figuring up weariness (which goes off of calories burned).

**Comment by Fosheze** [comment]
I'm taking on the activation cost tonight. Leaving this link here so I can find it again when I get home.
https://www.physio-pedia.com/Functional_Electrical_Stimulation_Cycling_for_Spinal_Cord_Injury#:~:text=Denervated%20muscles%20require%20up%20to,used%20parameter%20being%20150%20MA.

**Comment by Fosheze** [comment]
> I'm seeing a figure of 650 for the number of skeletal muscles, but 75 of them would never, as far as I can see, be used in dodging (tongue movements, for instance!), so 575, if going by number of muscles. Given that muscles tend to oppose each other (agonist and antagonist), cut that in half - call it 288. And that's almost certainly still an overestimate! That would be 7.8 kJ/s.
> 
> However... it should really be using nerve stimulation, not direct muscle stimulation, for a lot of it - it's already going to have to do nervous system interfacing to pick up sensory info! You can figure roughly 1 nerve for each recognized skeletal muscle (that's actually one way that muscles are distinguished!). For nerve cuffs, 2.1 mA is a safety limit currently used (https://jneuroengrehab.biomedcentral.com/articles/10.1186/s12984-017-0285-3), with greater (up to 20 in that article) sometimes needed - I suspect due to damaged nerves, scar tissue, and/or nerve cuffs that weren't quite placed correctly. So even if you suppose 30 mA due to the strong reaction needed and/or some direct muscle stimulation, it would be 778 J/s.
> 
> Regarding caloric requirements for this, see https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2806213/ for one source on muscular efficiency - it does vary with metabolism, but it looks like about 20% at a stable caloric intake - only 12 kcal (from that 10 kJ number).

I actually remembered that I know a bio med engineer the other day so I asked him. According to him as long as the electrodes are in the muscle it's self you should be able to get the desired result with as little as 0.5mA at 350mV for a total of 175mW or 175mJ/s per muscle. I like your figure for the number of muscles though. Considering I can't find a better one myself and he didn't have a clue how many would be required exactly I'll just go with that. That gives us a total dodge cost of only 50.4J/s which is rapidly approaching the running cost of 6J/s for the CBM it's self. 

Considering that the per dodge cost is so low, we could assume that the CBM just charges in between activations and then remove the per dodge cost entirely.  Because it takes time to charge up you could make it so that it can only proc once every few rounds or so. Considering that most things don't fire every round this would mean that you would still be fairly safe from one thing shooting at you but you still can't just charge into the waiting arms of a military outposts turrets. This would also help balance out the severe drop in power usage. An alternative for balancing is inflicting pain however it occurred to me that the pain blocker CBM would completely cancel that out and allow you to become Neo with no repercussions. Some sort of effect similar to dazed would work for balancing as well.

**Comment by actual-nh** [comment]
(That figure for the number of muscles is rather of an upper limit, BTW.) Stamina cost will not be handled by just bumping the activity level, as far as I'm aware; maybe something like half that of the **_updated_** mutation UD? If it's activating repeatedly, I'd allow it with the 50.4 J/s cost, provided stamina is high enough (above 1/5 of max?) - but you get dazed for 3 rounds (non-cumulative) each time. If you're only UDing every other round, you get dazed for 2 rounds. If less frequently, 1 round. The more frequently it fires, the harder it is to figure out what's happening and do anything else.

**Comment by Fosheze** [comment]
> EDIT: Dazed may not be the right one currently - the apply message is "The scream dazes you!". A more generalized version (unfortunately would have to wait till after 0.F - string freeze) would be desirable. Stunned is a bit too much, I think; winded is an alternative to consider if it activates too frequently.

That's what I was thinking too. I wasn't planning on putting this in before 0.F anyways because I will need to change the CBM description.

**Comment by actual-nh** [comment]
Oh. Re stamina cost - since it moves you to a different tile (even when a regular dodge could be done and wouldn't on success move you as far as I can tell), the stamina cost should be at least that for a move (in running movement mode, ideally) in any event. (Does it currently use movement points? I'll have to check...)

**Comment by Night-Pryanik** [comment]
It seems that the initial issue was resolved some time ago, as for now bionics UI correctly shows "trigger" value for Uncanny Dodge:
![изображение](https://user-images.githubusercontent.com/11132525/153704724-34f7e30f-700b-4328-9e6e-51c06a5852f9.png)

Should this issue be closed then? Discussions about energy cost to trigger the bionic do have value, sure, but they are unrelated to the original issue itself.

**Comment by Night-Pryanik** [comment]
@anothersimulacrum @Salty-Panda @Fosheze @actual-nh care to create a separate thread with discussions of trigger cost for this bionic?

**Comment by anothersimulacrum** [comment]
I think it is fine to close his, and I don't have intentions to create another issue for that.
