### ISSUE TITLE
Effect overlay sprites appear below character sprite

### ISSUE THREAD

**Issue by acepleiades** [CleverRaven/Cataclysm-DDA#47437]
# Describe the bug

Effect overlay sprites, such as the one that appears for running, bleeding, etc. appear below character sprites.

# Steps To Reproduce

1. Be using a tileset with effect overlays that overlap character sprites (I don't think this happens currently, but it will when this PR for UltiCa gets merged: https://github.com/I-am-Erk/CDDA-Tilesets/pull/519 . This PR overhauls effect overlays).
2. Get the overlay to appear.
3. If it overlaps with the character, character sprite appears on top.

# Expected behavior

The effect overlay should appear on top, and was made to appear on top.

# Screenshots

![misctest](https://user-images.githubusercontent.com/69649956/107711522-8f54c380-6ca6-11eb-9e5a-6a381cacb733.png)

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.E-9488-gb6b83cc-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda]
]

# Additional context

**Comment by esotericist** [comment]
while i can't chase this right this second, i can say that what's happening here is not that the effects are rendering under the character, they are rendering under the *clothing*.

the rendering sequence currently goes:
effects
mutations (which includes bionics), ordered according to their order rules
worn items
wielded item
movement mode

i'm hesitant to flag this as a bug right this moment because it's clearly designed to do it this way, and i dimly recall learning some time back that there are some effects that are meant to be covered by mutations/clothing, but i can't remember offhand which.

i want to try to find a solution for this, though, because it is a highly unintuitive result.

**Comment by xerenogan** [comment]
I'm curious about this one. I'll mess with it a little bit later.

**Comment by acepleiades** [comment]
I had tested without clothing later. It **is** appearing below the character. Here's a screenshot
![nakedman](https://user-images.githubusercontent.com/69649956/107712480-3e45cf00-6ca8-11eb-8f94-96b33272aea3.png)

**Comment by esotericist** [comment]
my mistake, i had forgotten skin color is a mutation (which wasn't the case when this code was written, or when i last worked with it)
