### ISSUE TITLE
Can't get rid of pot smoke

### ISSUE THREAD

**Issue by Salty-Panda** [CleverRaven/Cataclysm-DDA#47479]
# Describe the bug

I smoked a few joints. Pot smoke stays in the car AND forms clouds outside of it for over 4 days.

# Steps To Reproduce

Make a vehicle.
Place roof no all interior tiles.
Place walls/hatches with curtains around the cubicle.
Open all hatches and curtains.
Smoke ( maybe try using smoke grenade? )

# Expected behavior

After opening all hatches smoke will dissipate after some time.

# Screenshots

![image](https://user-images.githubusercontent.com/26396019/107858210-58f87f00-6e33-11eb-82ba-a0580ec83069.png)
Closed or open, clouds spread onto exterior tiles and tiles next to car, but inside, every tile has "thick/swirl of/pot smoke"

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-9555-gfe798ae-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    Mythical Martial Arts [MMA],
    C.R.I.T Expansion Mod [crt_expansion],
    No Fungal Monsters [No_Fungi],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Bionic Professions [package_bionic_professions],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Mythical Martial Arts - UndeadPeople Tileset [MMAUDP]
]

**Comment by Sinanzee** [comment]
This seems to happen whenever I smoke something (cigarette or joint) and pass time automatically (Crafting, working on a vehicle, playing a handheld game etc.). Worth noting however is that it also seems to happen sometimes, though less often, with enclosed buildings as well. The car that I'm driving with which this happens is totally walled in w heavy duty boards and roofs. I'm playing on the latest experimental build of the game and the only mod I have in common w OP are CRIT expansion.

**Comment by OliveChukar** [comment]
Tested on 0.E-9679-gf9fcf55 with core content pack dda only. Spawned two school buses smoked a joint in one and a cigar in the other with both I waited with the wait command until the drug was fully consumed. The buses were both filled with smoke and had smoke leaking out of them as shown in the screenshots others have posted. I waited another 10 hours and the smoke stayed the same. I walked away from the map tile and when I returned the smoke was still there. I moved the buses and it was like the smoke stayed where it was as the bus moved away from it when the buses were moved so that none of the smoke was inside them the smoke immediately dissipated as it should. I also tried smoking a cigar without waiting by just walking around in the bus with it (lit) and it filled the bus with smoke in the same way so I do not think waiting was the problem.

I also tested spawning riot control bots in the buses so they would fill the bus with their sedative gas. The sedative gas did fill the bus and take longer to dissipate then it would in open air but it was within limits of what would make sense for an enclosed poorly vented space.

I tested setting off a smoke bomb in one bus and it acted like it would in open air.

**Comment by Fosheze** [comment]
Alright, who added hotboxing mechanics?

Joking aside the only thing I can see that has changed fields code recently is #47329. The thing that's weird is that it is only having a effect on certain fields. I'm not familiar enough with the code to say why it'd happening but 2 things have stood out to me with those fields so far. Those fields don't have any "qty" set in effects.json where smoke and most other fields do (see below). I would be curious to see if some of the other fields that don't have "qty" set exhibit the same problem.
https://github.com/CleverRaven/Cataclysm-DDA/blob/1f4fa29988df316a2f61d0c4edd07019877e0591/data/json/emit.json#L1-L364

I have also noticed that the "percent_spread" for these fields in field_type.json is 200+ where most other fields have a "percent_spread" in somewhere in the lower double digits. For example normal smoke (fd_smoke) has a "percent_spread" of 10 (see below). The only other thing I can find that has even close to that is "fd_tindalos_gas" at 150 which also seems to never disappear. If I have time I will try changing that value locally tonight and see if it resolves the issue. Those values haven't been changed since they were unhardcoded 2 years ago but changing the field code could have had an effect on outliers like that.
https://github.com/CleverRaven/Cataclysm-DDA/blob/0c167aed8a8686a137ed8e6821ea5e7e31788929/data/json/field_type.json#L1-L1490

**Comment by actual-nh** [comment]
Ping: @Aivean?

**Comment by OliveChukar** [comment]
Just tried changing "fd_weedsmoke" from "percent_spread": 200" to "percent_spread": 20" this seemed to fix the problem. Adding "qty": 2" to "emit_joint_trail" did not seem to do anything.

**Comment by Aivean** [comment]
I could've broken something in #47076. I'll try to take a look ASAP.
