### ISSUE TITLE
proficiency gain and effect seem bugged

### ISSUE THREAD

**Issue by misterprimus** [CleverRaven/Cataclysm-DDA#47566]
# Describe the bug
proficiency gain and effect seem bugged

# Steps To Reproduce
1. Make a player with low proficiencies in everything and low fabrication, but who can craft a longbow and a survival bow.
2. Craft each.
3. Survival bow adds proficiency, but longbow does not. Also, longbow seems to never fail during crafting despite lacking proficiencies.

# Expected behavior
Proficiency gain and failure rate should make sense. Instead they seem to be inverted. Harder crafting jobs that take longer produce no proficiency gain, while simpler ones take less time and give more proficiency gain.

# Versions and configuration

 - OS: Win10x64
 - Game Version: 0.E-9703-gcbe6ac3
 - Graphics version: Tiles
 - Ingame language: Eng
 - Mods loaded: no NPC needs

[Smoke Rise.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5994194/Smoke.Rise.zip)

**Comment by Jamuro-g** [comment]
Can confirm the provided character doesn't gain proficiencies when crafting a longbow.
Made a new char and it works for that one.

**Comment by int-ua** [comment]
> Made a new char and it works for that one.

What works and how exactly?

**Comment by anothersimulacrum** [comment]
Cannot reproduce. It's slow, but after getting back to not needing sleep, and crafting a longbow to 15%, I gain about 0.1% in  both bowery and carving.
I notice the longbow on your workbench is only at 4%, so that's before the point it will even have any chance for you to learn any proficiencies for it.

**Comment by misterprimus** [comment]
> Cannot reproduce. It's slow, but after getting back to not needing sleep, and crafting a longbow to 15%, I gain about 0.1% in both bowery and carving.
> I notice the longbow on your workbench is only at 4%, so that's before the point it will even have any chance for you to learn any proficiencies for it.

I've already crafted a longbow 3-4 times. Just been disassembling them to get components back.

**Comment by anothersimulacrum** [comment]
I think all your focus is just going to your skill:
```
Practiced prof_bowyery 1440 seconds, focused to 10 (focus at 5) pct changed 0.0774722 -> 0.07775
Practiced prof_carving 1800 seconds, focused to 10 (focus at 5) pct changed 0.0204167 -> 0.0206944
Practiced prof_bowyery 1440 seconds, focused to 10 (focus at 6) pct changed 0.07775 -> 0.0780278
Practiced prof_carving 1800 seconds, focused to 10 (focus at 6) pct changed 0.0206944 -> 0.0209722
Practiced prof_bowyery 1440 seconds, focused to 10 (focus at 2) pct changed 0.0780278 -> 0.0783056
Practiced prof_carving 1800 seconds, focused to 10 (focus at 2) pct changed 0.0209722 -> 0.02125
```

**Comment by Fosheze** [comment]
> I think all your focus is just going to your skill: ...

Does focus go to skills and proficiencies separately? If so that doesn't make much sense that you can't learn a proficiency at the same time you are learning the skill even though you would be getting both from the same action.

**Comment by misterprimus** [comment]
> I think all your focus is just going to your skill:
> 
> ```
> Practiced prof_bowyery 1440 seconds, focused to 10 (focus at 5) pct changed 0.0774722 -> 0.07775
> Practiced prof_carving 1800 seconds, focused to 10 (focus at 5) pct changed 0.0204167 -> 0.0206944
> Practiced prof_bowyery 1440 seconds, focused to 10 (focus at 6) pct changed 0.07775 -> 0.0780278
> Practiced prof_carving 1800 seconds, focused to 10 (focus at 6) pct changed 0.0206944 -> 0.0209722
> Practiced prof_bowyery 1440 seconds, focused to 10 (focus at 2) pct changed 0.0780278 -> 0.0783056
> Practiced prof_carving 1800 seconds, focused to 10 (focus at 2) pct changed 0.0209722 -> 0.02125
> ```

Does that make sense, though? Shouldn't it be split up between the two of them?

1. Realistically speaking, like this is real life, how do you improve in one and not the other? I would think the benefit from the activity should go to both of the skills/proficiencies used, no?
2. Why am I never failing in crafting the longbow if I lack virtually all proficiencies and relevant skills? I started crafting longbows at fab 0 or 1 and proficiencies 1%. Shouldn't I be failing often?
3. I seem to gain proficiencies faster for crafting a survival bow in a few minutes than the longbow in a few days. That just makes no sense. Wouldn't it be the other way around, with a person becoming proficient/skilled faster with a more difficult and more time-consuming project? I think I'd get better at car mechanics more if I spent 2 days replacing a car engine than if I spent 2 minutes replacing a windshield wiper.

**Comment by Fosheze** [comment]
> 3. I seem to gain proficiencies faster for crafting a survival bow in a few minutes than the longbow in a few days. That just makes no sense. Wouldn't it be the other way around, with a person becoming proficient/skilled faster with a more difficult and more time-consuming project? I think I'd get better at car mechanics more if I spent 2 days replacing a car engine than if I spent 2 minutes replacing a windshield wiper.

I can see the argument for proficiency gain to be slower the more difficult the task is. If you hand a rookie a box of car parts, a bare frame, give them no instructions, and just say "build it" then odds are you are just going to come back to a box of broken stuff and a frustrated rookie who just knows a few things _not_ to do. It would be better to have them work their way up in difficulty from basic assembly, to rebuilding small engines, to car repair, to large engine rebuilding, and then finally onto a complete car restoration.

Completely agree on 1 and 2 though.

**Comment by misterprimus** [comment]
> > 1. I seem to gain proficiencies faster for crafting a survival bow in a few minutes than the longbow in a few days. That just makes no sense. Wouldn't it be the other way around, with a person becoming proficient/skilled faster with a more difficult and more time-consuming project? I think I'd get better at car mechanics more if I spent 2 days replacing a car engine than if I spent 2 minutes replacing a windshield wiper.
> 
> I can see the argument for proficiency gain to be slower the more difficult the task is. If you hand a rookie a box of car parts, a bare frame, give them no instructions, and just say "build it" then odds are you are just going to come back to a box of broken stuff and a frustrated rookie who just knows a few things _not_ to do. It would be better to have them work their way up in difficulty from basic assembly, to rebuilding small engines, to car repair, to large engine rebuilding, and then finally onto a complete car restoration.
> 
> Completely agree on 1 and 2 though.

I guess I can see this happening if we treat fabrication/skills as knowledge and if we treat proficiencies as muscle memory. I'd gain more muscle memory and less knowledge crafting a bunch of simple bows I already know how to make (less thinking, more doing) and the opposite if I'm crafting something complex (more thinking, less doing), but I should still get more proficiency from a single longbow than from a single survival bow even if proficiency-per-hour is more efficient with the survival bow. As it stands I am gaining almost 0% from the longbow and a bit from the survival bow. So you may be right in theory, but the implementation in the game is still way off.

**Comment by Fosheze** [comment]
> > > 1. I seem to gain proficiencies faster for crafting a survival bow in a few minutes than the longbow in a few days. That just makes no sense. Wouldn't it be the other way around, with a person becoming proficient/skilled faster with a more difficult and more time-consuming project? I think I'd get better at car mechanics more if I spent 2 days replacing a car engine than if I spent 2 minutes replacing a windshield wiper.
> > 
> > 
> > I can see the argument for proficiency gain to be slower the more difficult the task is. If you hand a rookie a box of car parts, a bare frame, give them no instructions, and just say "build it" then odds are you are just going to come back to a box of broken stuff and a frustrated rookie who just knows a few things _not_ to do. It would be better to have them work their way up in difficulty from basic assembly, to rebuilding small engines, to car repair, to large engine rebuilding, and then finally onto a complete car restoration.
> > Completely agree on 1 and 2 though.
> 
> I guess I can see this happening if we treat fabrication/skills as knowledge and if we treat proficiencies as muscle memory. I'd gain more muscle memory and less knowledge crafting a bunch of simple bows I already know how to make (less thinking, more doing) and the opposite if I'm crafting something complex (more thinking, less doing), but I should still get more proficiency from a single longbow than from a single survival bow even if proficiency-per-hour is more efficient with the survival bow. As it stands I am gaining almost 0% from the longbow and a bit from the survival bow. So you may be right in theory, but the implementation in the game is still way off.

The way I see it, skills are technical knowledge while proficiency is familiarity. You can "know" how to do something and still be really bad at it because you haven't done it much before; that is where higher failure chance and longer craft times without proficiency come in. 

I definitely agree that currently something is off because like you said successfully crafting something more difficult should still give you at least as much proficiency as crafting something simple; it should just be less efficient on a proficiency per hour basis. To that end it would actually make sense if proficiency was just a set amount learned per item crafted. That way you are always gaining proficiency but it is less efficient for larger more difficult crafts. It does make sense that you would learn the ins and outs of bowery better by making a bunch of different and easier to make bows rather than spending that same amount of time on a single longbow. However making that longbow should have still taught you something.

**Comment by anothersimulacrum** [comment]
Skill and proficiency gain occur one after the other.
Skill gain occurs, drains focus, and then proficiency gain does.

Currently there is a bug that has it so that proficiencies make you less likely to fail. I need to think of a lower impact bugfix for that.

**Comment by misterprimus** [comment]
> > > > 1. I seem to gain proficiencies faster for crafting a survival bow in a few minutes than the longbow in a few days. That just makes no sense. Wouldn't it be the other way around, with a person becoming proficient/skilled faster with a more difficult and more time-consuming project? I think I'd get better at car mechanics more if I spent 2 days replacing a car engine than if I spent 2 minutes replacing a windshield wiper.
> > > 
> > > 
> > > I can see the argument for proficiency gain to be slower the more difficult the task is. If you hand a rookie a box of car parts, a bare frame, give them no instructions, and just say "build it" then odds are you are just going to come back to a box of broken stuff and a frustrated rookie who just knows a few things _not_ to do. It would be better to have them work their way up in difficulty from basic assembly, to rebuilding small engines, to car repair, to large engine rebuilding, and then finally onto a complete car restoration.
> > > Completely agree on 1 and 2 though.
> > 
> > 
> > I guess I can see this happening if we treat fabrication/skills as knowledge and if we treat proficiencies as muscle memory. I'd gain more muscle memory and less knowledge crafting a bunch of simple bows I already know how to make (less thinking, more doing) and the opposite if I'm crafting something complex (more thinking, less doing), but I should still get more proficiency from a single longbow than from a single survival bow even if proficiency-per-hour is more efficient with the survival bow. As it stands I am gaining almost 0% from the longbow and a bit from the survival bow. So you may be right in theory, but the implementation in the game is still way off.
> 
> The way I see it, skills are technical knowledge while proficiency is familiarity. You can "know" how to do something and still be really bad at it because you haven't done it much before; that is where higher failure chance and longer craft times without proficiency come in.
> 
> I definitely agree that currently something is off because like you said successfully crafting something more difficult should still give you at least as much proficiency as crafting something simple; it should just be less efficient on a proficiency per hour basis. To that end it would actually make sense if proficiency was just a set amount learned per item crafted. That way you are always gaining proficiency but it is less efficient for larger more difficult crafts. It does make sense that you would learn the ins and outs of bowery better by making a bunch of different and easier to make bows than by spending that same amount of time on a single longbow. However making that longbow should have still taught you something.

Might be too much work to have a hardcoded prof gain per item. Perhaps it can be "fixed" by basing it on "base" crafting time, not modified crafting time (modified by proficiency/skill/weariness). That way you can't "game" proficiency gain by crafting while you're tired or unskilled.

**Comment by anothersimulacrum** [comment]
I am fairly sure it is already based on base crafting time.

**Comment by actual-nh** [comment]
A suggestion for how difficulty should affect skill/proficiency gain: multiply [likelihood of failure] by (1 - [likelilhood of failure]). 0 if never getting anywhere OR always succeeding, maximum at 50/50 odds.

**Comment by Saicchi** [comment]
> Skill and proficiency gain occur one after the other.
> Skill gain occurs, drains focus, and then proficiency gain does.
> 
> Currently there is a bug that has it so that proficiencies make you less likely to fail. I need to think of a lower impact bugfix for that.

Would inverting this order if the player skill level is higher than the required for crafting be a valid solution?
For example: if the player has fabrication 3, crafting an item which requires fabrication 2, it would practice the proficiency first instead of the skill.

**Comment by anothersimulacrum** [comment]
It wouldn't solve this, though it would help if their fabrication was level 5. I'm not sure I'm a huge fan of having that weird swapping edge case.

**Comment by Evi-d** [comment]
It's just the effect of the prof_modifier being used as division instead of a multiplication as it was meant to be for originally. 

It's inverted, as (x) and (x)^1 mean completely different things to how things are applied.

The numbers on the recipe at the bottom function from a lognormal distribution. Before you had the ability to offset the skew with a "time modifier" that gave the distribution a negative skew to offset the skew you'll see if you were to craft it originally, this made people believe it was under a normal distribution.

There is a negative lognormal distribution from the proficiency modifier with a "time multiplier" that roughly evened everything out.

There was always a correlation between the two values that had this effect, that's why with proficiencies you always had faster progress gains per tick.

By setting it to its inverted to divide where is dividing your success roll essentially, you the skew towards the direction of failure more and more towards the end of the craft. 

You can just set the skew back to 0 more evenly towards a normal distribution by just using prof_multiplier as multiplication again and it'll just even it all out like it was intended. 

Currently, the skew is shifted towards pushing towards failure rates with the current settings.

The exp gains and such are directly correlated to the same issue, everything is skewed towards one direction that is "x more likely to incur failure" because it sets a new normal value and is set towards the direction of failure rates that increases your failure chances. The "time multiplier" does offset some of this, but not nearly enough as it's essentially cutting down your success rolls too while rolling for less amount of times (but incurs more failures).

It puts the progression loss and item counter effect into full drive because it's being repeatedly triggers due to the failure rates being a multiplier for a higher failure chance than intended.

It's the same issue. The times should be directly linked to the notion of "number of times rolled" rather than ingame time.

I should probably stop ranting about it. There will always be a skew to the distribution, it's just more radically shifted towards failure right now.

**Comment by Mom-Bun** [comment]
Locked due to a particular user spamming issues

**Comment by I-am-Erk** [comment]
Is this issue still valid? We've changed a fair bit of the underlying code since then
