### ISSUE TITLE
The state of volume of bundles (rag, leather)

### ISSUE THREAD

**Issue by Lamandus** [CleverRaven/Cataclysm-DDA#47630]
To be honest, getting rid of the bundles all together would be best. It doesn't make sense that those bundles have less volume then the original rags, especially that high reduction. We are making those rags more dense, can we use it as a heat source, by the energy we are creating?

Just to put it into perspective we are reducing 10 rags á 250 ml (2500 ml) to 750 ml by what force exactly? I mean those bundles still can have a purpose (easier handling, faster transfer from A to B) but such a reduction of volume? I mean we are already saying, we are using the room in our pockets as efficient as possible. Wouldn't make it much "easier" to leave the rags as is? Since it is easier to store 100 single tissues into my backpack than a "block" of it.

**Comment by actual-nh** [comment]
I have been reluctantly forced to learn over the years that putting clothing neatly into a bag fits more of it than if one simply stuffs it (although stuffing is frequently advisable to fill in the cracks). To produce that much compression of rags, I suggest a recipe involving a sealable plastic bag and a straw (to withdraw the rest of the air).

**Comment by wapcaplet** [comment]
See #24175 (the PR that added rag bundles) for rationale.

**Comment by aerrant** [comment]
Rag bundles aren't very necessary, but plank bundles are life savers - it'd be a chore to drag those by the floor otherwise.

If anything, I'd have liked bundles to be automatically disassembled whenever a recipe requires their contents.

The IRL analogy is solid, too: you really can make clothing more compact by organizing it or by using vacuum bags.

**Comment by Lamandus** [comment]
but then we need to see, what the volume is actually about.

is it the actual volume of the object
or is it the volume the item takes away from storing somewhere, making the shown volume bigger than the object itself.

Another take can be, to make those stacks of rags with bigger packages, for example 100 per bundle, so the ground hauling is much much faster. But I don't buy the extreme benefit on volume to be honest. From 2500 to 2000 maaaaybe, but that is less than half the volume.

**Comment by Fosheze** [comment]
As far as the hauling goes bundles are really no longer needed for that for small items now that nested containers are a thing. If you want to haul 500 rags just stick them all in a duffel bag and then you only have 1 item to move. You can also use them directly out of the bag that way. I can still see the point of having bundles for large items like planks because there is no better way to haul them but for small items no one is going to realistically make multiple bundles of exactly 10 rags rather than just stuffing them all in a bag. I've personally been using body bags for this for a while now. 

As far as volume goes, many items do seem to be using the packing volume rather than true volume. For example the bucket has a volume of 5L but definitely doesn't have a true volume of 5L.
https://github.com/CleverRaven/Cataclysm-DDA/blob/2f36cd95908e3da4f13d559a786b07ec81cb5300/data/json/items/containers.json#L534-L541

This is something that should be addressed though because I have seen people in various locations using item weight and volume directly to calculate the item's density and if the volume actually represents the space taken up for packing purposes then those density calculations are all wrong. I can't remember if it was changed recently or not but I believe disassembly used to be based on item volume rather than weight.

**Comment by Lamandus** [comment]
So to speak it is the same with bottles and Jars. The true volume is much lower, but we use the transporting volume for them as well, pots are another example of "but it doesn't take too much room, when you can put stuff in it".
A way to circumvent it in the long run is to make those objects containers even in your bag (not wielding) BUT only for objects that can't be spilled. So puting in rags into the pot/bucket can happen in your bag as well, but liquids should be prohibitted.

**Comment by Fris0uman** [comment]
fixed by https://github.com/CleverRaven/Cataclysm-DDA/pull/60567
