### ISSUE TITLE
Cold Weather should damage/kill all but the hardiest crops

### ISSUE THREAD

**Issue by morthein** [CleverRaven/Cataclysm-DDA#47673]
# Is your feature request related to a problem? Please describe.
I noticed, while managing my faction base, that crops not only made it through cold weather, but actually grew!

# Describe the solution you'd like
I'd like to see the crops turn to withered plants if the temps reach freezing. But not all plants, and not all the time. Plants are very resilient, but they shouldn't grow through winter unless engineered for it.

# Describe alternatives you've considered
Generally, plants die off in the winter, or at least stop growing. This could lead to building green houses, hydroponics, or even seed engineering through applied science with proper equipment to produce hardier seeds that won't die but just stop growing through winter (or some engineered to grow through winter!)

# Additional context
It would be an extra thing we can build (can there ever be enough?) a bit more realistic, and adds a bit more danger. I know some plants, like winter cabbage is already made for cold weather, but the majority of plants should become  withered plants after the temps reach the plant's point-of-no-return. Although they might still drops their seeds along with the withered plant, seeds can withstand being frozen, of course.

**Comment by morthein** [comment]
Perhaps the plants could take damage in cold weather and then become withered plants after they "die".

**Comment by Fosheze** [comment]
There is already code similar to this implemented for plants planted in radioactive areas. The simplest solution would probably be to reuse that same code. You would just need to check temperature as well as radiation when determining weather to kill of plants.

Ideally there would be a system in place that altered growth rates based on temperature though and I'm not sure how that would do outside of the reality bubble. To that end I'm not sure how temperature checking would work outside of the reality bubble period. The temperature would need to be checked on a per tile/plant basis because of your greenhouse point. I don't see any way to do that outside of the reality bubble.

**Comment by Fosheze** [comment]
> For out of reality bubble temperatures you can look for inspiration in item processing https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/item.cpp#L9412

That would work for normal field situations where everything is planted outside but it relies on item flags for special cases which can't be applied to furniture (which I believe crops technically are) during runtime from what I have seen. That would mean that the heated greenhouse example wouldn't work. It would probably be possible to create a pseudo item for each crop when they leave the reality bubble and then apply those flags to the item. Then when the plants reentered the reality bubble they would be updated based on the pseudo item and the pseudo item would be deleted. I seem to remember seeing something very roughly similar done for programming autodocs for surgery in the past. That seems rather performance intensive though, especially for large fields.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
