### ISSUE TITLE
Faction camp - farming has infinite seeds

### ISSUE THREAD

**Issue by morthein** [CleverRaven/Cataclysm-DDA#47672]
# Describe the bug
When attempting to make a friendly NPC plant crops in the farm field of our faction camp, it will look for seeds the NPC can use. It finds it easily enough, you make your choice, then send the NPC. But, the seeds you choose are not missing from the stockpile.

# Steps To Reproduce

1. Make a faction camp
2. expand to a farm
3. get any seeds and make your npc go plant them
4. notice they are not missing, even though you have planted crops now.

# Expected behavior

You shouldn't have infinite seeds.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-9773-gb3f2f0e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Alternative Map Key [alt_map_key],
    Cataclysm++ [Cata++],
    Crazy Cataclysm [crazy_cataclysm],
    No Rail Stations [No_Rail_Stations],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Cataclysm++ - UndeadPeople Tileset [Cata++UDP],
    Crazy Cataclysm - UndeadPeople Tileset [CrazyCataclysmUDP],
    Graphical Overmap [Graphical_Overmap],
    MSX Black Military Cars [UDP_BlackMilitaryCars],
    No Fungal Monsters [No_Fungi],
    Bionic Slots [cbm_slots],
    Disable NPC Needs [no_npc_food],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by A3Digital** [comment]
I have been testing this for a while, and I figured something out.

In order to plant the seeds, they need to be located in the storage zone. And as @morthein mentioned, the seeds are not removed from the storage zone. 
However, if you have any of the same seeds in your inventory, those will be removed. 
Furthermore, if you try to plant the seeds from the storage zone without having any of the same seeds in your inventory, they will simply never be removed hence the infinite seed bug.

**Comment by A3Digital** [comment]
> I have been testing this for a while, and I figured something out.
> 
> In order to plant the seeds, they need to be located in the storage zone. And as @morthein mentioned, the seeds are not removed from the storage zone.
> However, if you have any of the same seeds in your inventory, those will be removed.
> Furthermore, if you try to plant the seeds from the storage zone without having any of the same seeds in your inventory, they will simply never be removed hence the infinite seed bug.
Actually, all seeds that are going to be planted should first be in the storage zone and not in the player's inventory, right?

Just making sure that the bug is the seeds being taken out of the player's inventory instead of being taken out of the storage zone as opposed to the bug being needing the seeds in the storage zone instead of needing the seeds in the player's inventory. Hopefully that made sense.

My apologies, this is my first time ever working with faction camps so I am piecing everything together.

**Comment by A3Digital** [comment]
Here is the code that shows the items being taken out of the player's inventory.
https://github.com/CleverRaven/Cataclysm-DDA/blob/483cd09a897ef22802c759a672deebc721f4dfdf/src/mission_companion.cpp#L729-L739
