### ISSUE TITLE
Predator mutation lines improvement

### ISSUE THREAD

**Issue by RadHazard** [CleverRaven/Cataclysm-DDA#47725]
# Is your feature request related to a problem? Please describe.
Currently, there are several mutation lines that feel underwhelming, not to mention incredibly similar to each other.  Lupine and Feline are practically palette-swaps of each other, with Beast not far behind them.  All three are fairly underpowered and uninteresting post-threshold lines, and as a result they don't see much use outside of RP.  This is in large part because there's really not much post-threshold content for any of them, and what little they do have is almost entirely shared between the three lines.

# Describe the solution you'd like
Post 0.F, I plan on making some general improvements to all of these mutation lines.  My first pass almost certainly won't fully flesh-out each line, but at the very least I hope to make them less punishing and more interesting and distinct from each other.

I've already got a couple ideas of varying feasibility, and as I come up with more I'll add them here:

- [ ] Post-threshold fur mutations that allow shedding in the summer -- Fur is extremely punishing to have right now due to the excessive warmth it provides.  That's a fine downside for a pre-threshold mutation, but it would help make post-threshold more attractive to lessen the downsides after crossing the threshold (similar to how Inconveniently Large becomes Large for post-thresh Ursine mutants).  A summer coat would provide less warmth and equally less protection, though it would still be warmer than no fur at all.
- [ ] Split Carnivore into Carnivore and Obligate Carnivore -- Regular carnivores would suffer a nutrition penalty to eating certain plant-based foodstuffs that they can't digest well (carbohydrates, essentially) but would still be able to eat it.  Some easy-to-digest plant products, like fruits, would be just as enjoyable and nutritious as they are to humans.  Obligate carnivores would be completely unable to eat carbohydrates and would derive less enjoyment out of sweet foods like berries (cats can't taste sweet, after all).  Obligate carnivores may even have a *need* to eat meat, due to them no longer being able to produce certain amino acids.
- [ ] Post-threshold variants of Carnivore/Obligate Carnivore -- these would be more efficient at digesting raw meat (most likely just reducing or removing the existing raw penalty when eating meat to simulate a more efficient digestive system).  Cooked meat will always be more attractive due to the lack of parasites, but this at least should make a full-on animal playthrough somewhat feasible.
- [ ] Corpse-eater mutation -- (dependent on having a muzzle), that lets you eat meat directly from corpses without butchering them first.  This would have all the same penalties/interactions that eating regular raw meat does, it would just make it more convenient to eat on the go.  This should of course remove the same amount of mass from the corpse that you eat, to avoid exploits.  Alternatively, if that proves unworkable it might be possible to simply treat a muzzle as a built-in butchering tool.
- [ ] Claw and Fang variants -- Felines should probably have close to an even split between claw and bite damage.  Lupines should do most of their damage through bites, with very little if any coming from their claws.
- [ ] Tail variants -- Currently fluffy tails provide the best dodge bonus (because long tail is considered both an intermediate mutation *and* the Feline-specific mutation), which is a travesty for anyone who knows how much cats rely on their tails for movement.  The Feline tail should be more specialized toward dodge/movement buffs, while the Lupine tail should be more geared toward social buffs.  Wolf tails should definitely not evolve out of cat tails, nor the reverse.
- [ ] Predator martial art(s) -- An interesting idea I had for post-threshold predators is an inherent predator martial art that they gain on crossing the threshold (or by a specific mutation), similar to biojutsu.  These martial arts would be specialized in not only unarmed attacks but making the most of their natural weapons, to simulate the sort of instinctive effectiveness that predators have with their fangs and claws.  The various mutation lines could even have different martial arts to simulate different predator hunting styles (e.g. wolves would have lots of harrying tactics, while cats are more "pounce-and-kill" on a single target)
- [ ] Cat climbing - cats are great at climbing things with their claws.  Let feline mutants use 'em!
- [ ] Feline speed, Lupine Endurance - the feline family is known to have cheetahs, the speed demons of the animal kingdom.  Post-threshold felines may not be that fast but they could sure use a faster running speed.  Meanwhile, wolves aren't known for excessive speed but they are well-adapted to running for a long time.  They could get a lower stamina penalty for running, or perhaps a faster base movement speed (balanced to ensure that it's not as fast as feline's speed when running).  Both of these movement modes would be quadrupedal, requiring all the paw mutations and also for the mutant to keep their hands empty in order to work.

# Describe alternatives you've considered
Just merging all three into a generic "Beast" line, but that would be boring

# Additional context
The idea here is to give all of the mutation lines a very predatory feel -- if you go post-threshold in any of them, you should be incentivized to run around on all fours, killing animals with your fangs and/or claws and eating them right on the spot.  

Additionally, all the lines should have a distinct sort of feel to them, inspired by their real-life counterparts:
- Felines should be speedy ambush killers, good at pouncing on single targets and tearing them to shreds
- Lupines should be endurance fighters, good at harrying groups of opponents and outlasting them with their stamina
- Beasts are harder to pin down, but one interesting possibility might be to make them more feral than the other counterparts, focusing on being even better at animal-like tasks while suffering much more at human-like ones.  This might be an interesting line to experiment with more drastic mutations, e.g. a full-on quadruped mutation once the limb rework is in place.  Lupines and Felines would have their specializations while remaining humanoid-enough to keep some veneer of civilization, while Beasts would be, well, beasts.

**Comment by chrispikula** [comment]
I really like this idea.  I think something like this would work for cat morphs?
Aka, Ambush Arts:

Unarmed 0: 25% reduction in movement noise, smell.
Unarmed 1: Follow up strike, Offensive (Normal), -60% move cost.
Unarmed 3: Disengage, bonus to getting out of grabs, slight reduced move cost when running away.
Unarmed 4: If follow up strike was a hit, -80% move cost to make an rake attack that has double damage.
Unarmed 5: Additional 15% reduction in movement noise, smell.
Unarmed 7: [Go For The Throat]: Initial On Crit attack on an enemy has a chance to do 1 stun, 1 knockdown.  I was thinking along the lines of an attack that would mute the target, but I couldn't think of anything that would do that.

Aka, when you're good enough, you're 1-hit killing things, but if you screw up, you can run away.  Also a bit of stealth/sneaking, but that's not really a big part of this game yet.

For Lupine:
Harrying Arts:
Unarmed 0: Energetic: 10% move cost reduction when walking, while have not taken a combat action for at least 20 turns.  Must have a visible hostile.  Persists for 5 rounds after last seeing hostile.
Unarmed 0: Enduring: 25% move cost reduction when running, while have not taken a combat action for at least 20 turns.  Must have a visible hostile.  Persists for 5 rounds after last seeing hostile.
Unarmed 3: Howl: While in sight of an enemy, .33% chance per turn per unarmed rank (Max 2%) to howl, causing enemies to have a chance of being stunned.  Stunned enemies may disengage (forget about you).  The maximum chance goes up by .5%/level and to a max of 5% when it's a full moon. 
Unarmed 4: Leader of the Pack: Threshold Lupine NPC's will run with you.  Increased bonuses to the previous 3 by 1% for each follower in the back, with maxes of something like a 20%/35% move cost reductions,  
Unarmed 5: On Crit, chance for knockdown.  If already knockdowned, Stun.
Unarmed 6: Pack: When melee attacking an enemy that another Threshold Lupine NPC is attacking, increased crit chance.  Can trigger the former.
Unarmed 7: [Share the Moon Goddesses Blessing]  Gain the ability to spread werewolf ism to npc followers who like you a lot via conversation.  Doing so reduces your unarmed by 1 via debuff for 1 moon.  This stacks, and expires at the rate of 1/month.  So if you get unarmed to 10, somehow, you could do it 4 times in a moon before your melee would be too low to do it again.  Maybe each time you do it that follower gets another Lupine mutation?  Slow burn, long debuff, but lots of payoff.  Maybe make it so that if it's cloudy/raining the night of the full moon, it doesn't wear off.  :-p  Just to be clear, if the total effective unarmed is less than 7, the conversation option won't happen. 

The idea here is that you aggro large groups of enemies to run after you, but you break them up and then whittle them down with the howling.  Also the ability to outrun them to force them to reposition would be interesting.


For Ursines/Beasts:
Bestia Arts:
Unarmed 0: [In the middle of a cold, dark winter.]  Reduction to cold damage.  When temperatures are below zero, reduced caloric needs.  Increased move costs.  +20% damage for preferred weapon type.  Scorpions could use piercing stingers, bears their massive paw slams, moosemen their sharpened antlers.  Default to blunt, I think.
Unarmed 1: On Crit, Knockback
Unarmed 1: [Don't Wake the Slumbering Bear] On wake from attack when the outside temperatures are below zero, 4x damage, no move speed penalty [due to above], both for 2 hours, followed by 5x caloric requirements for 2 days.
Unarmed 2: Arm Block
Unarmed 3: Leg Block
Unarmed 4: +1 Block attempts, 10% reduction in bash and cut incoming damage.
Unarmed 5: When running, chance to knockdown on hit.  
Unarmed 5: Another passive toughness increase, additional 15% reduction in incoming bash and cut damage,
Unarmed 6: +1 Block attempts, +1 negate incoming crit (if that's a thing?)
Unarmed 7: Roar: When surrounded, chance to roar and stun enemies in range of 3.  Longer stun times when closer to target.  May cause deafness, however I don't know if enemies can be deafened.
Unarmed 8: [The King of the Forest]: Terrifying to behold, some enemies will just not fight you.  Enemies with two bars of health or less remaining have a chance to instead just run away.  If at range 2 or less, will get stunned for 1 round instead.  +1 Block attempts.

This would be the Tanky option, for when you wade into combat and show that you are indomitable.  When the blows rain down, you shrug them  When drawing aggro isn't a downside, it was the plan the whole time.  Just don't be too vainglorious, after all, _winter is coming_.

I think I might have liked this idea too much.

**Comment by actual-nh** [comment]
> I think I might have liked this idea too much.

Chuckle. Some parts of your martial arts ideas might admittedly better fit under the MMA (Mystical Martial Arts) mod instead of "vanilla" - the moon-related ones for Lupine, for instance.

**Comment by Fosheze** [comment]
For lupine you could probably add an ability to toggle the scent map on and off fairly easily. Basically just copy the code for the debug scent map. It could use some prettying up for being used in actual gameplay but it would be functional as is. A lot of these could use some additional unique negative mutations as well because currently this is basically just a flat power boost for them all. An easy example would be color blindness for lupine which reduces perception.

**Comment by RadHazard** [comment]
> For lupine you could probably add an ability to toggle the scent map on and off fairly easily.

I'd be interested in adding scent-based mechanics for Lupine, but I'm not sure how many things actually have "scent" right now.  If it'll take a lot of work to add useful scents in (rather than just being able to smell yourself all the time), that might be better suited for a second pass specifically for Lupines.  For now, I'm looking at mostly doing low-hanging fruit or high-impact changes that can be shared between the trees.

>A lot of these could use some additional unique negative mutations as well because currently this is basically just a flat power boost for them all.

That's intended -- right now, all of these lines are very underpowered compared to more developed mutation lines like Alpha or Ursine or Medical.  Most of these changes will be going in post-threshold, which at the moment gives literally nothing but Predator/Apex Predator for all of these lines (Well, felines get Saberteeth too, but that's it).  I would be interested in adding realistic downsides too, but for the moment I'd prefer downsides that encourage players to move toward the "predator" playstyle rather than being flat nerfs.

**Comment by chrispikula** [comment]
> A lot of these could use some additional unique negative mutations as well because currently this is basically just a flat power boost for them all. An easy example would be color blindness for lupine which reduces perception.

That is true, but I was using the Martial Arts page on the wiki as a reference.  What I've put here is comparable to the more powerful martial arts, I think.  My sketch-boarding included both passives and actives, after all.  At worst I'll accept that I'm within 0.3 orders of magnitude.  :-p

I put the skill requirements higher for them as well as post-threshold would be something that happens later on in a players game, certain starts not withstanding.  Might want to cluster them with an even higher average skill requirement, but that leads to very significant ability bumps on skill-up.

**Comment by actual-nh** [comment]
> That is true, but I was using the Martial Arts page on the wiki as a reference. What I've put here is comparable to the more powerful martial arts, I think. My sketch-boarding included both passives and actives, after all. At worst I'll accept that I'm within 0.3 orders of magnitude. :-p

Some of those on the wiki are currently in the MMA mod, BTW; I (or someone!) really need to look through them and make sure it's up to date...

**Comment by chrispikula** [comment]
> > For lupine you could probably add an ability to toggle the scent map on and off fairly easily.
> 
> I'd be interested in adding scent-based mechanics for Lupine, but I'm not sure how many things actually have "scent" right now. If it'll take a lot of work to add useful scents in (rather than just being able to smell yourself all the time), that might be better suited for a second pass specifically for Lupines.

Maybe an ability to make a long-lasting scent mark?  Sort of like flares for missiles, but instead for enemies who can't see you.  Or possibly as a way to split up large groups of enemies, if prepared beforehand.

**Comment by Fosheze** [comment]
> That's intended -- right now, all of these lines are very underpowered compared to more developed mutation lines like Alpha or Ursine or Medical. Most of these changes will be going in post-threshold, which at the moment gives literally nothing but Predator/Apex Predator for all of these lines (Well, felines get Saberteeth too, but that's it). I would be interested in adding realistic downsides too, but for the moment I'd prefer downsides that encourage players to move toward the "predator" playstyle rather than being flat nerfs.

They do definitely need a boost however, from what I understand, alpha, medical, chimera, raptor, and elf-a are all meant to be the top tier mutagens so they aren't really the power level that you should aim for. That's why you only find a single vial of them in lab finales where you can find many doses of all of the other mutagens all over the place. You would want to be closer to the power level of slime, fish, plant, rat, spider, etc. All of those are currently still better than the predator lines as it is but they also all still have their fare share of negatives.

**Comment by RadHazard** [comment]
Right, I don't intend to step on the toes of the big boys.  Perhaps a better comparison would be Ursine and Mouse -- both are well-developed and have a unique and competitive niches, including major drawbacks that encourage focusing on said niches.  That's the sort of end-goal I'm aiming for with this

**Comment by jagoly** [comment]
This mostly sounds good, but I'm not sure about lupines getting better endurance. I'm fairly sure that humans are already better endurance runners than wolves, afaik we're second only to horses.

**Comment by Fosheze** [comment]
> This mostly sounds good, but I'm not sure about lupines getting better endurance. I'm fairly sure that humans are already better endurance runners than wolves, afaik we're second only to horses.

We actually still beat horses in raw long term endurance. They just get close to us there but can also manage much higher speeds. There isn't anything that really beats us on the long term endurance front though. At the same time that endurance would probably be closer to weariness than stamina. From what I understand, stamina is meant to be more sprinting endurance than long term endurance. A lot us animals can beat us at that.

**Comment by jagoly** [comment]
Maybe lupines could have the ability to pant, boosting stamina regen when not moving or attacking.

**Comment by chrispikula** [comment]
> This mostly sounds good, but I'm not sure about lupines getting better endurance. I'm fairly sure that humans are already better endurance runners than wolves, afaik we're second only to horses.

There's also the Pronghorn Deer which can pace itself at 30km/h for forty minutes.

Now, on the topic of theoretical peak vs average reality.  Sure, if you've got a char who's got a running fanatic compared to the average person today.  The default New Englander with 8's and 9's across the board?  

On the other side of the argument for endurance events, there's the RAAM race for cyclists.  Nearly 5k km, and the record is just under ten days  (You get to choose if you want to sleep, you see).  I don't think anyone would agree that data from that race should be considered an natural peak for bicycle operation in game.

**Comment by Fosheze** [comment]
> Now, on the topic of theoretical peak vs average reality. Sure, if you've got a char who's got a running fanatic compared to the average person today. The default New Englander with 8's and 9's across the board?

Mutating isn't going to change the survivor's level of fitness. Fitness isn't an intrinsic biological trait of any animal so it isn't something that would really be passed on in the mutation. Mutating will change base biological systems but it won't suddenly give a couch potato the physique of Arnold Schwarzenegger in his prime. Comparing the abilities of a wolf that has had to hunt all of it's life to the average 8/9 New Englander wouldn't be a great comparison to see where that person would be post mutation. You would want to use a wolf that was just as unfit as an average New Englander. Fitness it's self is a planned feature from what I have seen so when it does roll around it might make sense to change the rate of fitness gain/loss with mutations but not the fitness value it's self.

At the same time I do agree with you that a Lupine should have a stamina boost over a normal survivor because stamina doesn't represent long term endurance but rather short term sprinting endurance. There are a ton of animals that can beat us in that by a long shot. Long term endurance is more accurately modeled by weariness and I don't think that there is even the ability to modify that with mutations yet.

**Comment by chrispikula** [comment]
> 
> 
> > Now, on the topic of theoretical peak vs average reality. Sure, if you've got a char who's got a running fanatic compared to the average person today. The default New Englander with 8's and 9's across the board?
> 
> Mutating isn't going to change the survivor's level of fitness. Fitness isn't an intrinsic biological trait of any animal so it isn't something that would really be passed on in the mutation. 

I was under the impression that this wasn't the case?  I can't provide any sources, but it was my assumption that most species actually had genetic makeups that would promote muscle growth in spite of a lack of activity.  Bears, Lions, come to mind.  A quick look suggests penguins and barnacle geese as well.

**Comment by souricelle** [comment]
Look at how jacked gorillas get just sitting around eating leaves. Hormones and genetics count for a lot.

**Comment by actual-nh** [comment]
> > Now, on the topic of theoretical peak vs average reality. Sure, if you've got a char who's got a running fanatic compared to the average person today. The default New Englander with 8's and 9's across the board?
> 
> Mutating isn't going to change the survivor's level of fitness. Fitness isn't an intrinsic biological trait of any animal so it isn't something that would really be passed on in the mutation. Mutating will change base biological systems but it won't suddenly give a couch potato the physique of Arnold Schwarzenegger in his prime. Comparing the abilities of a wolf that has had to hunt all of it's life to the average 8/9 New Englander wouldn't be a great comparison to see where that person would be post mutation. You would want to use a wolf that was just as unfit as an average New Englander. Fitness it's self is a planned feature from what I have seen so when it does roll around it might make sense to change the rate of fitness gain/loss with mutations but not the fitness value it's self.

Currently, mutations are capable of affecting Strength (and the other 3 major statistics), healing rate, max stamina, and stamina regeneration rate.

> At the same time I do agree with you that a Lupine should have a stamina boost over a normal survivor because stamina doesn't represent long term endurance but rather short term sprinting endurance. There are a ton of animals that can beat us in that by a long shot. Long term endurance is more accurately modeled by weariness and I don't think that there is even the ability to modify that with mutations yet.

I don't think so either (and the current way that one can affect it, the option WEARY_RECOVERY_MULT, is not as straightforward as it should be - something I'll probably be working on post-0.F).

**Comment by actual-nh** [comment]
> Look at how jacked gorillas get just sitting around eating leaves. Hormones and genetics count for a lot.

On the one hand, I would not describe them as just sitting around - try being in trees. On the other hand, genetics can/does play a role in, for instance, muscular development - but environment counts for a lot also. So it really depends on the alteration/mutation.

**Comment by souricelle** [comment]
https://coach.nine.com.au/diet/gorilla-diet/bcc1267b-d788-4f20-ae3e-7fad9937a11d#:~:text=Gorillas%20are%20actually%20pretty%20lazy,are%20very%20different%20to%20humans'.

https://www.irishtimes.com/news/science/apes-can-be-lazy-and-never-get-fat-we-can-t-how-come-1.3773540

https://blog.usejournal.com/how-does-a-gorilla-get-so-strong-75c68edd3c26

There's plenty here, some of it by a PhD, about why gorillas (and especially testosterone-pumped male gorillas) get so buff without working out. They are very sedentary even compared to humans.

**Comment by Maddremor** [comment]
I'm not a fan of the mutant martial art angle at all. For something to be a martial art, it's implied to be a formal framework to be taught. Learning how to fight on your own is just Brawling, and anything gained from mutations should rather be directly linked to those instead of using a MA as an intermediary.

**Comment by actual-nh** [comment]
> https://coach.nine.com.au/diet/gorilla-diet/bcc1267b-d788-4f20-ae3e-7fad9937a11d#:~:text=Gorillas%20are%20actually%20pretty%20lazy,are%20very%20different%20to%20humans'.
> 
> https://www.irishtimes.com/news/science/apes-can-be-lazy-and-never-get-fat-we-can-t-how-come-1.3773540
> 
> https://blog.usejournal.com/how-does-a-gorilla-get-so-strong-75c68edd3c26

Very interesting! I'll have to take a closer look at it.

> It may or may not be relevant that a typical survivor is essentially reduced once more to a hunter-gatherer lifestyle and most player characters would necessarily be super fit after a couple weeks anyway.

Couple weeks? Some might be. (I've known someone who decided in her late 50s that she was getting out of shape, and was competing in triathlons - as in finishing and not in last place - less than a year later, and apparently her entire family was like that. I do suspect she was the top one of them - we're talking about someone who won the Iron Man in her age group (admittedly early 60s) less than 2 months after a double radical mastectomy...) I'd think longer for most, especially for "super" fit. How much longer? Depends on your definition for "fit" and "super fit".

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
