### ISSUE TITLE
Waterworld

### ISSUE THREAD

**Issue by souricelle** [CleverRaven/Cataclysm-DDA#47734]
# Describe the bug

Started with the Wizard's Vacation scenario, the lake that it created in worldgen was excessively huge.

# Steps To Reproduce

1. Start a character on the Wizard's Vacation scenario in the version listed here
2. Try to sail away

# Expected behavior

The lake should be smaller

# Screenshots

[https://i.imgur.com/8Jqo6z3.png] Excuse the lazy stitching

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-9804-gbc7931f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Stats Through Kills [stats_through_kills],
    No Fungal Monsters [No_Fungi]
]

# Additional context

I anecdotally heard of someone having this issue with an island prison start as well.

**Comment by OliveChukar** [comment]
You should post the save.

**Comment by Fosheze** [comment]
This doesn't seem that large for a lake in CDDA or New England IRL. These aren't mean to be small lakes like you would see in a town park. If I remember correctly one tile in CDDA is meant to be 1 meter and an overmap tile is 24 regular tiles wide. From a little bit of counting and guestimation (I'm to lazy to count it all) it looks like you had around 120 overmap tiles between the island and the shore which gives us 2.88KM. It's hard to find a circular lake in New England IRL like they are in CDDA but if you look at google earth it isn't hard to find New England lakes that are 2.88KM across or more. One of the larger island filled lakes "Lake Winnipesaukee" is over 6km over most of it's length; it's 14km across at it's widest. There are a few other lakes in New England that are around that size as well. If we're using a loose definition of the New England setting then there is also Lake Ontario nearby which is over 50 km across but if someone put that in CDDA then they might as well just put in the Atlantic ocean because no one would be crossing either one in game. 

Also bear in mind that you only traveled west from the island. For all we know the east shore was only a couple of tiles past where the map vision ends. We would need to see the map revealed to see how big your lake actually was. If you post the map we can check to see if there is anything odd but just at a glance this seems pretty normal and intentional.

**Comment by Scintile** [comment]
Similar things can be observed with island prison scenario. You can start in a map with a gigantic lake (im talking something like 90% of the overmap tiles are lake or river)

**Comment by souricelle** [comment]
I went east as well after posting and it was about equidistant

**Comment by Ungen11** [comment]
I'm the island prison start guy OP mentioned, just wanted to clarify that 1. it makes sense lore-wise to build an island prison in middle of a big lake so the prisoners have an even harder time escaping, 2. I finally found dry land and the rest of the map is otherwise normal, so this issue isn't quite game-breaking, just a big pain in the neck to sail away from. I think the lake's size is good for island prison, though it does seem overkill for wizard's secret vacation; I get it, you wanted to be away from civilization so you could study magic in peace, but the lake mapgen seriously overdoes it. I think the wizard's vacation island should provide the player character with a boat or another means of transportation (maybe even a translocator gate, wizard basement style) to explain how you got to the vacation island at all, otherwise the scenario's inherent lake mapgen should be taken down a notch.
