### ISSUE TITLE
Back seat is overpowered, vehicle bed is too cold

### ISSUE THREAD

**Issue by tsulh** [CleverRaven/Cataclysm-DDA#48047]
# Describe the bug

I've been looking at json files of various vehicle beds and seats (while planning a mobile home), and discovered the following:
1. It seems that "back seat" does all that a "seat" does and more (a bit larger storage, comfort of 4, `"BED"` label) while having the same recipe to install it.
2. The "back seat" has `"floor_bedding_warmth": 500` whereas a vehicle part "bed" has `"floor_bedding_warmth": 300` (which is much below `"floor_bedding_warmth": 800` of a mattress placed on the floor).

# Steps To Reproduce

Please see `data/json/vehicleparts/seats.json`, `data/json/vehicleparts/vehicle_parts.json`, and `data/json/furniture_and_terrain/furniture-sleep.json` files.

# Expected behavior

1. Back seat is not better than a regular seat in every aspect. Back seat is unfavorable/unavailable as a driver seat.
2. Back seat is not warmer for sleep than a vehicle bed. A vehicle bed uses an actual mattress, so it should perform at least not worse than a mattress.

To address these issues, I'd like to suggest:
1. For `"seat_back_abstract"`, change ` "categories": [ "operations", "passengers" ]` to ` "categories": ["passengers" ]`, then the back seat won't be as overpowered anymore.
2.  For `"bed"`, change `"floor_bedding_warmth": 300` to `"floor_bedding_warmth": 800`, to match the warmth of a mattress placed on the floor.

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Debian; Description: Debian GNU/Linux 10 (buster); Release: 10; Codename: buster; 
- Game Version: 0.E-10053-g8419da6ffa [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

I might have missed something, e.g., I don't understand very well how damage reduction works for each vehicle part. Also, I'm guessing about what each variable does, so I could be wrong. Thus, I'd appreciate someone verifying my observations and the proposed changes.

**Comment by jtgibson01** [comment]
1. The `categories` field is used for cosmetic filtering when installing parts and has no gameplay effect, so removing the operations category won't change their behaviour.  However, I don't think their behaviour for driving needs to be changed.  "Back" seats are bench seats, and plenty of real-world old-model pickup trucks have bench seats.
2. I'd suggest 700~750 for the `floor_bedding_warmth` of the vehicle bed, to make them slightly inferior to mattresses and justify requiring the player to finding a proper bed somewhere rather than adding yet another deathmobile incentive. =)  I've slept in a camper bed in real life and it was definitely inferior to a full mattress.  I'd also suggest boosting the reclining seat upward to 300~400, since a reclining seat is really quite comfy to sleep in if you're a back-sleeper.  It's only the fact that you can't roll sideways and stay comfortable that makes a reclining seat inferior to a bench/back seat for sleeping on.

**Comment by tsulh** [comment]
> 2\. I'd suggest 700-750 for the `floor_bedding_warmth` of the vehicle bed, to make them slightly inferior to mattresses and justify requiring the player to find a proper bed somewhere rather than adding yet another deathmobile incentive. =)

The vehicle bed requires 1 mattress for installation. Why should it be less comfortable than a mattress? I don't think that's appropriate. Also, the warmth doesn't add that much incentive to looking for a real bed. It's really much easier to find a warm blanket + clothes than to build a base just for the bed. What compels me to build a static base is larger storage and better defenses, and especially the new NPC camp features.



> [edit] If back seats do need to be nerfed at all, I'd suggest making a weariness modifier -- say, 0.9x weariness reduction in a back seat, 1.0x weariness reduction in a seat, and 1.1x weariness reduction in a reclining seat

I'd think sleeping on a bench seat is much more comfy than on a regular seat, and about as comfy as on a reclining seat, because a bench at least is long and flat. I have 0 irl experience with these bench seats in vehicle though.

**Comment by jtgibson01** [comment]
"Warmth" is a factor of both warmth and comfort in the game; a mattress in a vehicle is not as thick as a real mattress "on the floor", even if the crafting ingredients require one -- there's a certain level of abstraction involved in all of the recipes.

For the back seat being comfy, I meant for the weariness modifiers to apply to sitting while driving, not for sleeping.  All sleep should be equally effective at restoring weariness, IMO; sleep is more of a psychological/neurochemical thing than a physiological/electrochemical thing.

**Comment by EvgenijM86** [comment]
It makes sense that backseats would be a better place to sleep in. Just look at the available space:

![backseat](https://user-images.githubusercontent.com/430076/111870316-f176a780-897b-11eb-8c85-ac188d95deb4.jpg)

You can take a full horizontal position if you have several backseats in a row, while frontseats won't allow you that because of how they are separated.

**Comment by jtgibson01** [comment]
Regardless of any changes, the back seat would certainly be a better place to sleep in than the front seat.  But the current 500 for the back seat is pretty much bang on the money relative to a proper 800 for a real bed, IMO, since most back seats aren't the leather luxury seats of a two-lane-wide Lincoln Navigator. ;-)  

I think I'm responsible for people being confused, so I'll break down the issue and clearly state the current "stance".

Problem identified by original poster (@tsulh):
* Back seat (`seat_back`) can store more, costs one "seat" (i.e., is as cheap as a front seat), is equally comfortable to a front seat for driving, works as a vehicle bed, and is better than a vehicle bed.
1. _Stores more_: (Not an issue.)
2. _Costs less_: (Not an issue.)*
3. _Equally comfortable for driving/sitting in_: definitely incorrect behaviour, a bucket seat is more comfortable for driving in.
4. _Works as a bed_: (Not an issue.)
5. _Better than bed_: definitely incorrect behaviour, a flat bed is much more comfortable for sleeping in than curling up in the back seat.

Changes proposed by OP/original poster, to reduce overpowered nature of back seat:
1. **Make it uncomfortable/unsuitable for driving by preventing it from being used for driving.**  I rejected the premise that it cannot be used for driving, but accepted the premise that it could be made more uncomfortable if necessary.
2. **Increase warmth of a vehicle bed to equal a mattress.**  I accepted this, with limitations.

My counter-proposal, with same goal:
1. **Add a feature which makes bench seats less comfortable for restoring weariness**, and/or **contribute additional fatigue while sitting/driving**, in line with the OP's proposition but without making it impossible to drive in them.  Requires code-level support (and game is in feature freeze, so this is long-term).
2. **Increase the warmth of the vehicle bed**, but **slightly less** than a mattress, to make people less inclined to install vehicle beds instead of sleeping in real beds.  The OP counter-proposed based on recipe ingredients but I held firm based on conceptual abstraction. =)
3. **Increase the warmth of the reclining seat** to 400 (still less than a back seat's 500), to make people less inclined to install back seats for non-cosmetic purposes.

Notably, neither OP's nor my propositions actually involved changing the back seat's warmth factor in any way. ;-)

(* The cost of a back seat could be addressed, but it would create a lot of fallout behaviour for tilesets.  I'd actually probably change that one myself, if I had my druthers, but didn't bother to suggest it since it would create a lot of cascading work for a comparatively minor issue.)

**Comment by captainego** [comment]
I started working this issue as a "Good First Issue".  Based on the comments above, and the values for the other seats in the json files I opted to make 2 changes.  

First I changed the floor_bedding_warmth of the vehicle bed to 700.
Second I changed the floor_bedding_warmth of the reclining seat abstract to 350.

Builds are successful and the automated tests pass.

To manually test the change I first tried the following sequence:
Start a new game as a Combat mechanic
Spawn an RV
Spawn 20 clean water and 20 pemmican
Enter the RV
Remove the seat that is in the rear compartment.
Reinstall the seat from the rear compartment as a "Back seat".
Close the doors to the back.
Workout at maximum intensity until the game stops the workout session.  This causes the character to be "Tired".  Drink water until full.
Sleep on the bed.  Note sleep duration of 10 hours.
After wake up drink water and eat pemmican until Hydrated / Sated.
Workout at maximum intensity until the game stops the workout session.  This causes the character to be "Tired".  Drink water until full.
Sleep on the backseat.  Note sleep duration of 10 hours.

I expected that the change would have reduced the required sleep duration.   Since that did not work I searched through the code to find what the floor_bedding_warmth actually did.

Reading the code it appears that floor_bedding_warmth just helps determine if the character is comfortable based on the current temperature effects.

To manually test this I tried the following sequence:
Start a new game as a Combat mechanic
Spawn an RV
Spawn 20 clean water and 20 pemmican
Enter the RV
Remove the seat that is in the rear compartment.
Reinstall the seat from the rear compartment as a "Back seat".
Close the doors to the back.
Use the debug menu to set the temperature (I tested at 16F, 24F, 28F and 32F)
Workout at maximum intensity until the game stops the workout session.  This causes the character to be "Tired".  Drink water until full.
Sleep on the back seat. NOTE that the character becomes comfortable in less than 3 hours in all tested temperatures.
After wake up drink water and eat pemmican until Hydrated / Sated.
Workout at maximum intensity until the game stops the workout session.  This causes the character to be "Tired".  Drink water until full.
Sleep on the bed.  NOTE that the character becomes comfortable in less than 3 hours in all tested temperatures (and it appears to be at approximately the same point as the back seat.

Based on my reading of the code I would have expected to find a temperature where the backseat did not become comfortable but the bed was comfortable.

Are there any ideas on how I can design a test to verify that the changes I have made to floor_bedding_warmth are actually accomplishing the goals of the issue?
