### ISSUE TITLE
Partial disassembly (e.g. one thread from a rag)

### ISSUE THREAD

**Issue by devenv** [CleverRaven/Cataclysm-DDA#48111]
# Is your feature request related to a problem? Please describe.
Disassembling a rag takes a long time and doesn't make sense to get 80 threads when you need only a couple, this feels artificial.

# Describe the solution you'd like
IRL I can pull one thread out of a rag.
option 1: 'a'ctivating a rag would result in a 'partially disassembled' rag and one string?
option 2: fabrication recipe with same results.
option 3: partial disassembly generic system (retrieving only a metal sheet from a fridge instead of disassembling the whole thing would be really cool).

**Comment by jtgibson01** [comment]
Since items have damage levels ranging from 0 to 4 (damage level 5 kills the crab), it could theoretically be possible to damage the item by 20% to receive 20% of its disassembly drops; however, the disassembly stuff is currently predicated on the notion of an all-or-nothing "you fail to recover X" based on the item's current damage level, so if that were implemented, it would definitely shift balance.

I think the optimal solution is a fabrication recipe, with a new recipe behaviour that specifies that a corresponding part should be damaged rather than consumed entirely -- something like:

```
    {"result": "tinder"
    ,"id_suffix": "shaved_from_stick"
    ,"category": "CC_OTHER"
    ,"subcategory": "CSC_OTHER_MATERIALS"
    ,"activity_level": "BRISK_EXERCISE"
    ,"charges": 50
    ,"time": "1 m"
    ,"skill_used": "survival"
    ,"difficulty": 1
    ,"qualities": [ { "id": "CUT", "level": 1 } ]
    ,"partial_components": [ [{"item": "stick, "damage": 1}] ]
    }
```
So with this, you could shave a stout branch up to five times to receive 250 tinder from it -- much less valuable than chopping that stick into wooden fragments, but easily doable in a pinch.  (Obviously the specific balance/result_mult/charges would be subject to tuning.)

But even that would be a bit of a mess to modify the item-search code to work with.  Hm.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
