### ISSUE TITLE
Another item duplication through trading

### ISSUE THREAD

**Issue by trvcic** [CleverRaven/Cataclysm-DDA#48146]
Version: Windows, 0.E-10027-g45f883c (tiles)
[Screenshots here](https://imgur.com/a/5wsG4JZ)
It seems that when you trade part of a stack of items, the npc gets the whole stack. You still keep you didn't trade, duplicating some of it. You can trade back as normal, getting items from nothing. This is different than [#46874](https://github.com/CleverRaven/Cataclysm-DDA/issues/46874), because it doesn't involve invalidly trading both the item, and the pocket that contains the item.

**Comment by k4gi** [comment]
I figure I'll comment on this issue instead of making a new one.
Windows, version 1.B tiles (at least that's what the launcher says), build 11582

Just had the same thing happen, I traded for 3 of my starting NPC's antibiotics and I got a whole stack of 15 while they still have 12 left over.

![Screenshot (39)](https://user-images.githubusercontent.com/26471575/117260648-a284c300-ae92-11eb-8e8c-dcde3f69011b.png)

**Comment by emomicrowave** [comment]
Can confirm. My launcher also says `1.B Tiles, build 11582`. In-game the build is 07c58d9
