### ISSUE TITLE
Smashing a broken side mirror creates undamaged hand mirror.

### ISSUE THREAD

**Issue by Zlorthishen** [CleverRaven/Cataclysm-DDA#48212]
Smashing off a damaged wing mirror from vehicle does not preserve the inherent damage of the part.

When a wing mirror is smashed off a a vehicle with a melee attack from the character, the hand mirror that is dropped is always in pristine condition. Shouldn't the damage level be preserved when the mirror is removed?

# Steps To Reproduce
1) Find a vehicle with a damaged side mirror.
2) Attack the side mirror.
3) The hand mirror that falls is undamaged.

# Expected behavior
1) Find a vehicle with a damaged side mirror.
2) Attack the side mirror.
3) The hand mirror that falls has the same damage level as it had when still attached, perhaps even more damaged.

# Screenshots

![image](https://user-images.githubusercontent.com/79779913/112409077-d9d65080-8ce6-11eb-8dab-9ee1d10a5639.png)

![image](https://user-images.githubusercontent.com/79779913/112409179-038f7780-8ce7-11eb-85a8-9ddb2b9d1f0d.png)

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.E-10134-g9b256f6 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

**Comment by zeropol** [comment]
If I understand correctly all vehicle parts with the UNMOUNT_ON_DAMAGE flag behave this way. At least I tried with bike basket.

The problem is these parts unmount when they are broken, so dropping on unmount a "damaged item to the same level the vehicle part was" would (try to) drop a item with zero or less HP.

One solution may be, when UNMOUNT_ON_DAMAGE items unmount, to drop them with heavy damage.
