### ISSUE TITLE
Rotten meat: The power of Charcoal and Salt

### ISSUE THREAD

**Issue by tyrael93** [CleverRaven/Cataclysm-DDA#4831]
It's something we all discover sooner or later,meat rots and disappears only if it stays on the ground. Putting it in a trunk, in a shelf, in a locker, in an oven, in any container, prevents it from disappearing. This isn't a real problem, right? I mean, what are you going to do with rotten meat? Eat it? oh, I don't think so.
Or maybe not. Turns out you can turn rotten meat in perfectly edible sausages, smoked meat, beef jerky, dehydrated meat and other kinds of recipes that will never spoil.
As I said before, we all know this, but I'm seeing a lot of new opened issues about food rotting, seeing as this went through 0.8 to 0.9 unnoticed. I don't know anything about coding myself, but does anyone have an idea of it could be fixed?

**Comment by mugling** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
