### ISSUE TITLE
[Experimental 3D field of vision] Make flying enemies automatically visible in the UI and in-game.

### ISSUE THREAD

**Issue by ifffrt** [CleverRaven/Cataclysm-DDA#48322]
# Is your feature request related to a problem? Please describe.
It's always such a pain in the ass to use Shift-V to try to find out where the flying wasps with how absolutely opaque messages such as "23 UP_NW" are. Especially with how our characters can supposedly see immediately those flying enemies, seeing those enemies ourselves as players shouldn't be as much of a hassle as it is.

# Describe the solution you'd like
I propose two solutions. One: Explicitly telling the player in the enemies list box how much of a z-level differences there is. So "23 UP_NW" would be "23 UP_NW 1LVL" or something similar. Two: Give players some indication in the ingame world that there are something that are flying above them at that place. Maybe a shadow, or just a little icon warning them that something flying above is there, or maybe if the player is using tilesets just straight up show the player the flying monster even on ground level and give a little icon next to it denoting the difference in z-level.

# Describe alternatives you've considered
That things should be let how they are. But the old system isn't even very realistic as, like I said, the characters can immediately see the monsters, if experimental z-levels are turned on.

**Comment by souricelle** [comment]
A shadow would be super helpful, especially if it animated in tilesets (like a little circle slowly growing and shrinking to represent something moving around up in the air). It would be rad if it also had the little alert symbol on it if the creature could see you.

**Comment by ZhilkinSerg** [comment]
I am confused - you say that your character should be able to see monsters and at the same time your charcater DOES see them in view menu.

**Comment by Zireael07** [comment]
He is confused by the fact IRL we would immediately see the monster, and in game we need to use view menu.

**Comment by ZhilkinSerg** [comment]
Oh, yes - we are only showing things on current z-level (and sometimes a bit of lower z-level with much less details).

**Comment by actual-nh** [comment]
> A shadow would be super helpful, especially if it animated in tilesets (like a little circle slowly growing and shrinking to represent something moving around up in the air). It would be rad if it also had the little alert symbol on it if the creature could see you.

Perhaps a color change of some sort for curses builds? Inverse colors, maybe?

**Comment by Nerdy314159265** [comment]
May I suggest expanding this to allow visibility for areas the player can see or remember but is on a different Z-level?

Currently, when you look at a bridge ramp there is a black void created due to the lack of visibility, or if you are in a helicopter you basically can't see anything without switching to the map and changing Z-levels or using peek and changing Z-levels.

I was thinking that in areas like the bridge, like if hilly ground is ever added, that instead of showing a region of black, then it can show what you remember of the area and what little you might be able to see from the lower level. Those regions could be have a border around them like maybe a blue (as in how the air tiles look) to represent that they are on a higher level.

Then for when you are looking down on an area, you can see everything normally but the lower areas have maybe a red border to represent that they are in a lower area.

This could help with the helicopter situation by allowing you to show the actual ground level with the full vision that you'd get from that height but represent that area as a lower level by effectively showing a border around the helicopter.

Ground enemies on a different Z-level wouldn't need any special handling to make it clear what level they are on. Flying enemies could have a border around their single tile or just their entity to indicate if they are above or below you depending on your height.

Gradients or patterns could be used to show the level of difference between your Z-level and the other area in question. The border turning stronger and stronger, red/blue to up to a cap or maybe the outline could be dashed to different degrees for the same indication.

Only issues that I can see right now are areas where you have 2 visible/remembered z-levels one over the other.

Only other methods, I can think of are more limited to the specific tileset selection as in something like isometric tilesets could use shadows, clearer ramps, and other tricks to show 3D. Or there could even be a real 3D tileset that would allow for easy depth perception by allowing free camera movement.

**Comment by ZhilkinSerg** [comment]
Think about non-tileset implementation first.

**Comment by Nerdy314159265** [comment]
> Think about non-tileset implementation first.

I would think that could be handled in a non-tileset way. It's just borders to the tiles, not the tiles themselves that would be affected.

**Comment by Zireael07** [comment]
> > Think about non-tileset implementation first.
> 
> I would think that could be handled in a non-tileset way. It's just borders to the tiles, not the tiles themselves that would be affected.

Zhilkin raised a very good question. Without using a tileset, all you can use is ASCII characters - so how do you display your 'borders to the tiles'?

**Comment by Nerdy314159265** [comment]
> Zhilkin raised a very good question. Without using a tileset, all you can use is ASCII characters - so how do you display your 'borders to the tiles'?

Would there be no way to put borders around ASCII characters?

**Comment by Zireael07** [comment]
> > Zhilkin raised a very good question. Without using a tileset, all you can use is ASCII characters - so how do you display your 'borders to the tiles'?
> 
> Would there be no way to put borders around ASCII characters?

AFAIK no

**Comment by ifffrt** [comment]
I have one small question: Given the ASCII nature of the curses build, is it an absolutely ironclad rule that on any given tile there can only be one character? If that's the case, can the characters themselves be enlarged or shrunk down to display contextual cues? Can the characters themselves be offset to the corners (such as making the character Z hug the top right corner instead of centered in the middle)?

**Comment by Nerdy314159265** [comment]
Searching for a guide that gives a complete image of what is possible via ncurses or any other curses library is going to cause me to have a stroke (I get that it's an character based library but would it kill the official documentation on these things to show images?).

Perhaps for the curses implementation, the tiles where the height is different could flick between characters used to make borders and lines elsewhere. While not nearly as convenient as a regular static border to the characters, it would still present the same information.

**Comment by Zireael07** [comment]
Another candidate for 'salvageable' label.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
