### ISSUE TITLE
Wrong values on acid_chitin armor pieces

### ISSUE THREAD

**Issue by Salty-Panda** [CleverRaven/Cataclysm-DDA#48363]
# Describe the bug

Biosilicified Chitin as a material has exactly the same parameters as normal Chitin, except for twice acid resistance.
Thus, Biosilicified Chitin armor pieces have the same values as normal ones, but due to the use of "proportional" increasing their weight, encumbrance, etc, they're straight-up worse. 
At least if "proportional" worked properly, seems like it can't change a lot of values.
Right now Biosilicified Chitin pieces are slightly worse than basic ones.

# Expected behavior

Maybe @Venera3 could give suggestions for better values for chitin materials?

# Versions and configuration

b11561

**Comment by souricelle** [comment]
This appears to be intentional. Biosil armor pieces of all kinds protect better because they're thicker, not because the material is stronger. This is also true of the car armor and there's no way that was an accident. The biosilicification process is just so they don't melt themselves with their own acid, it's not for fighting power.

Acid ants have 1 more point of bash armor than their cousins of the same size, but that could be for any number of reasons and doesn't necessarily reflect an inherent extra toughness to their armor.

We could at some point futz with chitin armors and include light and heavy versions in both styles, or we could ditch acidchitin altogether. Maybe they're immune to their own acid because they secrete a wax or something and that doesn't translate to player protection. The armor isn't very good vs enemy acid anyway.

**Comment by Salty-Panda** [comment]
Oh, biochitin vehicle armor is much stronger than normal one, should be fixed

**Comment by Venera3** [comment]
Sorry for the late reply, I did night shifts through the Easter weekend. The way I'd do it is keep the actual armor values as more or less the same as basic chitin, buff the acid and cut protection a bit and add a touch of fire armor to show it having an insulating silicate outer layer. To keep it from being a straight upgrade they could get the same no-repair deal as ESAPI vests use and the harvest list could be updated to tone down the acid chitin drops (with acid ants also dropping normal chitin alongside biosil).

**Comment by actual-nh** [comment]
The no-repair being due to being a bit more brittle?

**Comment by Salty-Panda** [comment]
I would assume that repair process involves replacing destroyed fragments of chitin with new material

**Comment by actual-nh** [comment]
> I would assume that repair process involves replacing destroyed fragments of chitin with new material

You could do a replacement like that, or a partial repair with some variety of glue (partial because the strength of the result would be dependent on the strength _in use_ of the glue). I suppose for larger pieces of armor, it would be reasonable to assume they're already crafted from multiple pieces, and so could be repaired by doing a piece-by-piece replacement as needed.

**Comment by Venera3** [comment]
No repair to show the silicate layer chipping off and you not being able to seamlessly replace it, compromising at least the acid protection (we don't have protection-specific armor degradation or much of an armor damage model, of course, but one can dream).
