### ISSUE TITLE
Mitigated proficiency penalties do not apply correctly to crafting time

### ISSUE THREAD

**Issue by ferociousdork** [CleverRaven/Cataclysm-DDA#48465]
# Describe the bug

Mitigated proficiency time penalties from books do not actually decrease the time to complete the craft. The crafting interface shows the penalties as mitigated, but the "Time to complete" still shows the unmitigated penalty, and crafting itself also uses this value.

# Steps To Reproduce

1. Spawn in a copy of "The Historic Weaponsmith".
2. Set fabrication skill to 9.
3. Give yourself the 'Principles of Metalworking', 'Blacksmithing' and 'Carving' proficiencies, for easier values to calculate with.
4. Open the crafting interface and search for 'zweihänder'. Its base crafting time is 8 hours, the mitigated Bladesmithing time penalty shows as 1.5x, but the time to complete is still 16 hours (using Bladesmithing's unmitigated time penalty of 2x).

# Expected behavior

"Time to complete" should show "12 hours".

# Screenshots

![proficiency_penalty_mitigation](https://user-images.githubusercontent.com/78301810/114274075-0eebde00-9a1d-11eb-81b6-1d78159c9a12.png)

# Versions and configuration

- OS: Windows
    - OS Version: 6.1 7601
- Game Version: 0.E-10367-g47c9250-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
    ]

# Additional context

[recipe::time_to_craft_moves](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/recipe.cpp#L75) uses the raw `time_multiplier` and does not take book bonuses into account. [recipe::proficiency_time_maluses](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/recipe.cpp#L743) looks like it does pretty much what's needed here (modulo `const`-ness).

**Comment by Salty-Panda** [comment]
I tried to fix it by adding `* guy.crafting_inventory().get_book_proficiency_bonuses().time_factor( prof.id );` to the other function
There two problems:
- you have to change 6 or more functions by removing `const` from their Character argument, no idea if that's that bad.
- Character::crafting_inventory() rebuilds `cached_crafting_inventory` on any change of time/moves/position. Using it in `recipe::time_to_craft_moves` makes crafting **terribly slow**. 

I tried to add another function that directly returns `cached_crafting_inventory` without any checks, (that's probably bad, but no idea how to build read-only wrapper or whatever should be used here, but I was prototyping and I assume that the required check invalidating `cached_crafting_inventory` would be called during crafting anyway so it wouldn't cause a problem).
Got fed up with clunky VS, and it trying to recompile the entire repo every time. Also the problem was more complicated than it appeared.

**Comment by eltank** [comment]
Hey there @Salty-Panda. I see you ran into the same issues I did while attempting a fix.
I'm also taking a shot at it in #48650, please feel free to comment.

**Comment by Evi-d** [comment]
Yo, they are all calculated from the normal point, calculate the normal point first.

Proficicienies always give a bonus and mitigation always gives you at best the value at the normal point when they're all at 0x.
