### ISSUE TITLE
bad temper is imbalanced

### ISSUE THREAD

**Issue by Pooshmeu** [CleverRaven/Cataclysm-DDA#48521]
I was roleplaying a lumberjack who would be someone who gets mad at everything easily, so I got the "bad temper" trait, along with 7int, and "hates books" trait.

I just commited suicide because it got ridiculous, 37 ingame days lost for nothing, I mean when I started reading books after 1 hour (ingame time), my focus was already 20.

reading books and upgrading a skill from 0 to 1 took a whole day, from 1 to 2 took 2 days, and from 2 to 3 took about 3 whole days doing nothing but reading.

I took about 12-14 ingames days to craft a longbow, and since I was always with -10 to morale, eveyrthig I would craft would get a 75% slowdown malus, I mean this is ridiculous, I shouldn't take 4x longer to craft an arrow just because my character is a grumpy dude.

I propose that the morale slowdown curve for crafting could be rebalanced, along with the creation of a trait that instead of ever having your character with -10 morale, just makes him more susceptible to bad stuff, and less susceptible to good stuff. he shouldn't take 2 days to craft 10 low-tier arrows just because he's a moody dude.

I know the combo of "hates books" and "bad temper" and "7 int" would slowdown reading times a lot, but it got to a point, gameplay-wise, that is both completely unrealistic and ultra boring. but that's acceptable.

The crafting part though, is too crippling for the character, 12 fucking days to craft a longbow. just because he's grumpy guy.

**Comment by gd-hxy** [comment]
lmao, you said you want to roleplay a lumberjack who would be someone who gets mad at **everything** easily. Just imagine an irritable man will not only lose his temper at reading, but will also lose patience in crafting. For example, the bad mood lumberjack may suddenly give up crafting because he is out of the group, has no hearty food/entertainment or in pain, and so on. The performance in the game is that the manufacturing speed is slower than the average person.
"bad temper" is a balanced trait in my opinion, It will prompt you to pay more attention to your mood values and always find ways(listen to music, eat delicious food, read novel, etc.) to stay optimistic. Which in a normal game is often not taken seriously

**Comment by actual-nh** [comment]
(Also see #48519.) Perhaps both "bad temper" and another called "Irritable" (or something like that) should be available, the latter being - as suggested - no continuous -10 but with even bigger modifications to positive and negative mood modifiers?
