### ISSUE TITLE
Add electrical fans to the game to aid in heat management

### ISSUE THREAD

**Issue by O1OOO1O** [CleverRaven/Cataclysm-DDA#48522]
# Is your feature request related to a problem? 
It is very difficult to keep a character cool during the summer

# Describe the solution you'd like
A set of fans, that can be used to lower the temperature in a given AOE.
Large box fan: a large noisy fan that is electrically powered and sends cool air and a wind effect in a specific directed cone-shaped area of effect. Can be placed and rotated to point the AOE in one of the 8 directions.

Battery-powered oscillating desk fan:
A smaller quieter fan that runs off batteries and creates a more sphere-shaped or moving cone-shaped AOE of wind and cooler temperatures. Less powerful than the large box fan.

Portable mini-fan:
The smallest fan, battery-powered, can even be strapped to your head like a headlamp.  Only cools the space you are standing in, weakest but quietest fan.

# Describe alternatives you've considered
Not having the temperature be so extreme, or having a less negative effect on the character. Implementing better temperatures at night or when in the shade and/or when the wind is blowing.

**Comment by ZhilkinSerg** [comment]
Fans just move the air whether it is hot or cold. They do not change the temperature.

**Comment by Salty-Panda** [comment]
Temperature is lower at night already
Also, the hot status has a very slight debuff

A high level of activity at midday during summer wearing heavy clothing isn't something normal

Staying inside a car significantly lowers temperature, all vehicles has hidden, passive, magical AC

**Comment by Hirmuolio** [comment]
Wasn't wind chill added when wind was added in?

A fan could just be a source of "wind" with the cooling properties of  wind.

**Comment by O1OOO1O** [comment]
Fans can be a source of wind, so long as the wind does the job, that was really what I was envisioning. 

As for "A high level of activity at midday during summer wearing heavy clothing isn't something normal" duh... but A low activity wearing nothing or 0 warmth clothing only, still has cases of my character saying it 'very hot' to 'scorching hot' and "the heat is making you see things" messages. Seeing temps at 99F - 104F, however I am using the desert mod, it being a significant factor isn't unexpected, but I like the mod and would still like some better cooling methods.  It's only day 60 something and still in spring I can only imagine Summer will be far far worse.

**Comment by PatrikLundell** [comment]
Note that when the air temperature is above the body temperature adding a wind makes it worse, not better, as any cooling you've managed to achieve to the local air around your body by sweating is carried away and replaced by hot air, even in the case where the replacement air is dry (if it's saturated with moisture sweating won't help much regardless).

A lot of protective clothing in hot temperatures is, unfortunately, not uncommon in the apocalypse, as the Adam suit has very poor protective properties against zombies. The ways to cool down sufficiently not to suffer serious over heating (pain->severe pain and worse) I've found are to use the magic car AC and, when possible, basements. Eliminate a very small number of zombies, retreat to the vehicle/basement, read a chapter of a book, and then go out for a new session.

**Comment by Igryn** [comment]
> Note that when the air temperature is above the body temperature adding a wind makes it worse, not better, as any cooling you've managed to achieve to the local air around your body by sweating is carried away and replaced by hot air, even in the case where the replacement air is dry (if it's saturated with moisture sweating won't help much regardless).

Sweating would contribute to cooling at least somewhat even if air is hotter than body to some degree ofcourse. Evaporative cooling is surprisingly efective, some people in subsaharan africa still reli on it to basically chase prey to exhaustion and overheating, because they can sweat and thus way more efficient im dissipating heat in such hot environments. It would dehydrate you though, and clothes would prevent evaporative cooling depending on their coverage percentage 

https://youtu.be/826HMLoiE_o

**Comment by Salty-Panda** [comment]
That reminded me, 44880 is in progress, it will partially fix this issue

**Comment by Igryn** [comment]
Idealy some skin mutations like scales and chitin should also limit or get rid of evaporative cooling via sweating because they lack sweat glands

**Comment by PatrikLundell** [comment]
@Igryn That's why I tried to emphasize the wind making it worse. If you've managed to cool down the air around the body you don't want to have it replaced by hot air, as, at some point, the heat added to the body by the new hot air exceeds the heat carried away by evaporation. If the temperature isn't too high and the air replacement rate isn't too high, evaporation can still cool you down more than the heat from the warm air hitting you adds.
I believe there's a deadly weather phenomenon at the edge of the Sahara desert when 50 degree Celsius air with a high wind speed overheats and dehydrates those who can't find shelter in a fairly short time.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
