### ISSUE TITLE
Chitin armor tool listing typo

### ISSUE THREAD

**Issue by Caelum-Updates** [CleverRaven/Cataclysm-DDA#48533]
# Describe the bug
Chitin armor (and variants) have duplicate listings on the "tools required" portion

# Steps To Reproduce
1. Acquire chitin gear recipes
2. Access through crafting interface
3. Read "tools required" portion

# Expected behavior
Single listing of tools required

# Screenshots
![image](https://user-images.githubusercontent.com/78391880/114819729-7b395980-9df0-11eb-8d2b-b8c9d89d1b53.png)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-10389-g4a67b7c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Generic Guns [generic_guns],
    Magiclysm [magiclysm],
    No Rail Stations [No_Rail_Stations],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    Generic Guns - UndeadPeople Tileset [Generic_GunsUDP]
]

**Comment by Saicchi** [comment]
Can confirm on `0.E-10379-g0f86226edf [64-bit]`.
Also applies to other legs, boots and guantlets chitin / biosilicified chitin armour.

I believe this is due to those recipes using `armor_chitin` and `tailoring_leather_small` requirement type, they both require `SEW` level 1.
```json
{
    "id": "armor_chitin",
    "type": "requirement",
    ...
    "qualities": [ { "id": "CUT", "level": 1 }, { "id": "SEW", "level": 1 }, { "id": "LEATHER_AWL", "level": 1 } ],
    "components": [ [ [ "chitin_piece", 1 ] ], [ [ "filament", 1, "LIST" ] ] ]
  },
  {
    "id": "tailoring_leather_small",
    "type": "requirement",
    ...
    "qualities": [ { "id": "SEW", "level": 1 }, { "id": "CUT", "level": 1 }, { "id": "LEATHER_AWL", "level": 1 } ],
    "components": [ [ [ "leather", 1 ] ], [ [ "filament", 1, "LIST" ] ] ]
  }
```

I think the proper solution in to this issue would be in `requirement_data::get_folded_tools_list` insinde `src/requirements.cpp`. Changing it so it won't print duplicate entries or only print the highest requirement if there are multiple duplicates.
