### ISSUE TITLE
Can't add custom faction camp expansions

### ISSUE THREAD

**Issue by krulunio** [CleverRaven/Cataclysm-DDA#48559]
### Describe the bug
I'm working on expanding faction camps trough mod and now I'm trying to add custom expansion for Mansion Camp (specifically, `Mansion_Road_Alt`). When I try to select OM tile with Mansion's entrance, game says: "NPC failed to survey expansion, perhaps there is a vehicle in the way", even tough there is no vehicle.
### Expected behavior
NPC returns and tab with custom expansion shows up in faction camp menu
### Versions and configuration
- OS: Windows 10
- Game version: 0.E-3
- Mods loaded: only my faction camps mod
### Additional context
I know that "vehicle in way" message also shows when game can't find proper mapgen entry, however I checked it and it's not the issue. It's also not problem with OM tile not being a "field", other expansions can be placed outside "field", i.e. on road
[basecamp_mod.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6329259/basecamp_mod.zip)

**Comment by curstwist** [comment]
It's probably looking for a field unless you've defined the OMT's as valid expansion slots.  

Not related to your bug but something to be aware of for mansions:  They share OMT's and have variations of OMTs with the same ID's.  So, if you are using Wild Alt, some of the squares have multiple map layouts and this will really throw off any construction and faction camp blueprints you are making.

I'd recommend something that doesn't involve variations like the movie theater, the mega store, other 3x3 specials or creating a more static mansion special that'll allow for the faction camp (this will make things confusing for the player because they won't know which mansion is the faction capable one).

**Comment by krulunio** [comment]
That's what I did, I specified mansion's entrance as valid OMT, "vehicle in way" message implies that game recognize OMT as valid for expansion (it gives diffrent message for other OMTs).

I know mansions are random, I bumped into this problem with military outposts, however each part of mansion has unique OMT, so it's just matter of  writting mapgen and recipes for every expansion, in every mansion part.

**Comment by curstwist** [comment]
I tried to look at your zip file, are you developing this on a stable build?

I went to load this to look at it and got a start up error.  Looking at your recipe_groups.json, the vanilla files use:
`"id" instead of  `"name"`

It crashes to the desktop.  This is on an experimental build.  #39366 changed the name tag to ID.

**Comment by krulunio** [comment]
Yes, I'm developing on stable, version 0.E-3

**Comment by krulunio** [comment]
I solved the problem: to add custom expansion, I needed to create OMT with same `id` as expansion's `id`.
Since it's not so obvious, I will add information about it to BASECAMP.md later
