### ISSUE TITLE
rocks through objects

### ISSUE THREAD

**Issue by robotic-gamer** [CleverRaven/Cataclysm-DDA#48604]
# Describe the bug

rocks thrown by hand are blocked by various things (chain link fence, bar door etc)
however rocks thrown by sling can go through without issue

# Steps To Reproduce

try to throw a rock by hand though a chain link fence
then try to throw a rock via a sling through the same fence

# Expected behavior

the rock should either be consistently blocked or allowed through

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-10281-ge365124 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Simple_additions [simple_additions],
    Alternative Map Key [alt_map_key],
    C.R.I.T Expansion Mod [crt_expansion],
    Blaze Industries [blazeindustries],
    Stats Through Skills [StatsThroughSkills],
    Bionic Slots [cbm_slots]
]

# Additional context

my understanding of the issue is that projectiles from "gun-like" objects are treated differently then thrown objects. 
The easiest solutions I can think of would be either
 -to allow thrown objects below a certain volume through
-or make certain ammo types not allowed through (such as rocks)

**Comment by OliveChukar** [comment]
Tested on 0.E-10395-g4525b4f [64-bit] with Dark Days Ahead [dda] only no mods. Threw 40 pebbles at a chain link fence all were stopped.  Fired 8 shots from an RPG-7 with three different ammo types and none were stopped.  A small pebble should get past a chain link fence sometimes but hit the wire and stop other times.  RPG-7 shells should always be stopped because they are wider then the holes in the fence.  It looks like the code that handles barriers with holes in them assumes that thrown objects will be large and things shot from guns will be small.

**Comment by anothersimulacrum** [comment]
Something (the sling, probably) needs the `NO_PENETRATE_OBSTACLES` flag.

**Comment by casswedson** [comment]
Fixed by #48764

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/impenetrable-chain-link-fence/26627/3
