### ISSUE TITLE
Automatic Grenade activation when throwing

### ISSUE THREAD

**Issue by Tommy-os** [CleverRaven/Cataclysm-DDA#48645]
# Is your feature request related to a problem? Please describe.
Throwing grenades requires needless micromanagement compared to other throwing weapons.
Current grenade throwing sequence:
1. Equip grenade
2. Activate grenade
3. Throw grenade

Other thrown weapons without activation
1. Throw item, directly from anywhere in inventory

# Describe the solution you'd like
When throwing a grenade or similar activated weapon, a confirmation dialogue should pop-up asking the player whether he wants to activate the grenade right before throwing it.

# Describe alternatives you've considered
Interface options to automatically activate grenades when thrown, for experienced users that do not mind the risk.

# Additional context
Preventing grenades to be activated while inside a container to prevent accidental activation from pressing the wrong button, as activating grenades that are in a players backpack serves no purpose but to (accidentally) kill the player. Or at least giving a prompt before doing so, just like when attempting to walk off a ledge.

**Comment by Hirmuolio** [comment]
Prevention activation within inventory is simple json change. Just add `"need_wielding": true,` in the use action. Some grenade-like items laready have that attribute (for example molotov cocktail).

**Comment by PatrikLundell** [comment]
The suggested change would probably lead to bug reports where people complain that they killed themselves and/or companions/NPCs with thrown grenades, because the target moved closer while the PC performed the equipping and arming actions.

**Comment by esotericist** [comment]
i readily support making grenades needing to be explicitly wielded or otherwise not in storage before attempting activation, and i feel most explosives in general should work this way.

automatically activating the grenade as part of throwing is not going to happen. there are too many moving parts for timing with player interactions for this to work anything like any player would reasonably expect.

as it stands, i just don't see the merit for the primary suggestions offered (but i would totally like to see some safety guards for accidental backpack bombs)
