### ISSUE TITLE
Field of view issue when crossing bridge with vehicles

### ISSUE THREAD

**Issue by mqrause** [CleverRaven/Cataclysm-DDA#48736]
# Describe the bug

When crossing a bridge with a vehicle that isn't open all around, your field of view gets blocked in some places.

# Steps To Reproduce

1. Have a car that blocks your line of sight somewhere around you, for example an armored car.
2. Drive car over bridge. Works best when driving in the direction of blocked view, for example backwards in armored car.

# Expected behavior

No changes to your field of view.

# Screenshots

Vehicle with blocked view in the back, but cameras installed:
moving forward:
![forward](https://user-images.githubusercontent.com/38702195/116821852-e36f9580-ab7b-11eb-91c8-db1d18b8743f.gif)

moving backward:
![backward](https://user-images.githubusercontent.com/38702195/116821881-13b73400-ab7c-11eb-9120-b8050938976f.gif)

# Versions and configuration

- Build 11581
- Windows 10
- no Mods

**Comment by ZhilkinSerg** [comment]
Possibly a cache related issue.

**Comment by GGgatherer** [comment]
Looks like a duplicate of my old issue #42954. There's a save there if someone want to check what's going on.

**Comment by Anaglyphic** [comment]
Can I ask a follow-up here? GG says it's something he knows, but it's also appears as something I thought was a bug and almost filed. It's because of that steady, even pacing and the way the vision cone 'refills' the darkness when backing up, outward pulling in, nice and steady...

It looks very much like driving an ambulance or fire truck at night with the flashing lights on... your main headlights throw forward pretty far, but at the back it's just the 1 or 2 blinking red lights... blinking even and steady.

You made the gif tiny so I cannot see the vehicle details, for my own peace of mind would confirm it's not night and these are not vehicles with emergency lights on? Thanks!
