### ISSUE TITLE
Can't haul/advanced inventory/drop on Freshwater research station bulkhead door tile

### ISSUE THREAD

**Issue by Zeropol** [CleverRaven/Cataclysm-DDA#48745]
# Describe the bug

We are ( at least I am ) unable to haul items, or to put item on, the freshwater research station opened bulkhead doors.

This place is really lovely and while we still can move items through the door by standing on the opened doors tile and use the advanced inventory to move items to one side to the other, it can quickly become boring.

# Steps To Reproduce
- Haul something until you are in front of any "open bulkhead door".
- Being stopped hauling while crossing the door.
Or
- Sit next to the door
- Open advanced inventory -> tile is red
Or
- Get in the door tile
- Drop item
- "You can't place items here"

# Expected behavior
The opened bulkhead door is able to have items on its tile.

# Screenshots
Unnecessary ( unless someone ask ).

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.E-10474-g1ae66c97a0-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context
Additionally, on any bulkhead tiles ( all the station ) : can't deploy furniture !

**Comment by Saicchi** [comment]
Can confirm on `0.E-10474-g1ae66c97a0 [64-bit]`.
This is due to the bulkhead door `t_door_metal_bulkhead_o` having the `NOITEM` flag, which prevents item from being on the terrain. It also has the `BLOCK_WIND` flag even though the door is open.
I don't know why the open door has these flag, but if I were to take a guess, since the definition for `t_door_metal_bulkhead_o` is below `t_door_metal_bulkhead_c`, it was probably a copy-paste.
