### ISSUE TITLE
View with estimated duration of pills taken

### ISSUE THREAD

**Issue by Salty-Panda** [CleverRaven/Cataclysm-DDA#48770]
# Is your feature request related to a problem? Please describe.

Based on food handling skill we can estimate food's time to expire.
We could add view where player could see history of taken drugs and medicine either in form of "X time remaining" or "taken X time ago"

# Describe the solution you'd like

I don't have good idea where to put it UI-wise.
Current `@` is already very clustered, making another window just for that seems forced, unless some other things would be moved there.

Potentially we could make extended effect view separated on ailments and group of possible solutions:
on left side Weakness, on the right an option to take pills or use Radiation Scrubber
on the left "headache" on the right an option to take antiparasitics
on the left Infection, on the right info "you took strong antibiotic 3 hours ago"
Being able to see solutions on the right would depend on player's healthcare skill

Optionally, under `@` in effects tab, there could be information how long ago effect started.

# Describe alternatives you've considered

Some item/Self-Aware mutation/device being able to log those information, the way Self Aware allows you to see your `health`.

**Comment by Anaglyphic** [comment]
That's well thought out. Lots to implement but it's a universal concept; more data at-a-glance is always good.

That would rock. The extended effect view as a UI sub-menu might be hardest, so yea maybe more @ density is the only feasible way? The subreddit has at various times discussed that people always "check" health by activating bandaging or antiseptic, to see the body locations with statuses, and then abort. Don't know if that's a side effect of hating tutorials or what. So something similar where you just directly go to that breakout of all body parts, showing health and status as well as medically and/or drug statuses of what's been ingested and at approximate time.

Do you want something to have estimated duration countdown, til msg 'you no longer feel the effects of <blank>', or to make it more 'discover'-y where you modify med descriptions to include 'effect lasts 8h' and then on the panel says 'took 6.5h ago' Which is more in-the-spirit of cdda?

From a GUI design perspective I'd say, add a 4th column to \@, move effects to top of it, then your put drug and duration and addiction statuese there, and if they can interact from this menu based on healthcare. Course would depend on how many people are playing on tiny screens and/or large fonts, might actually require a submenu.

Hmm I have a suggestion that's drastic. re-appropriate **!**. 

Because, logistically, since Safe Mode Manager is on tilde already by default, why not make Safe Mode toggle backquote? It's by default unmapped. Then with ! freed up, there's your Health Chart sub-panel, to include all the health and drug stats you can populate with, maybe with weary sleep and stamina, every effect you're experiencing (and possibly interact with depending on healthcare level, as above)

It's a thought.

**Comment by WelpThatWorked** [comment]
I've tried a few things. The time since effect start was easy to implement, I've put it on the info box in the middle of the @ menu when you select a particular effect. 

The time to end I'm not so sure about. For those with Selfaware it's simple enough, but for estimation, I'm not sure what the max error should be (fraction of duration/max duration, intensity duration factor or something else?), there's no current way to indicate the applicable skill for a particular effect (though almost all of them are just firstaid?), I'm not sure how to cache the estimated value so that it won't generate a new one each time you open the menu, and I'm not sure it makes sense to estimate many effects anyway. 

So, I'm leaning towards Time since effect started+Good descriptions for labeled drugs(unlabeled drugs make sense not to know the extent of the effects)+No estimation/Only describe time remaining if selfaware or have some other applicable way to measure. 

For the selfaware time remaining, effects that are applied continuously (e.g. lit up, disabled limb) shouldn't have their time remaining shown, as it is perpetually 1-2 seconds. For this I'm ignoring effects that have a max duration of 1-2s, which should only catch the continuous effects, but might cause issues if someone adds something later. 

What it looks like, with selfaware:
![image](https://user-images.githubusercontent.com/9769385/118156274-05fc7c80-b3ce-11eb-9e34-fc882f6ab200.png)

Alternatively, with aprox. durations:
![image](https://user-images.githubusercontent.com/9769385/118156363-1e6c9700-b3ce-11eb-9cbf-78e7c581f3f2.png)

**Comment by Salty-Panda** [comment]
Looks great!

A few thoughts:
Most of effects I had in mind while making this issue are binary in nature. They operate on 100%, then disappear. When you get bitten by snake you instantly receive full effect of the debuff (pain is time-incremental I recall) which disappear after certain time.
When combined with knowledge of their exact duration they start looking very unnatural.

Partially in order to combat that, partially to make it look less gamey I would vote in favor of approximate timers. (Maybe with exception for self aware)

Also, possibly we could add a fuzzification tied to health care skill? 
E.g."effect ends in" part is multiplied by `1 +/- min(6 - health_care,0) / 12`, so with 6 or more we have right estimate, with 0 we would have 50% spread.
^ This feels fishy. Without cache player can open menu 10 times and estimate average value. With cache it could lead to effect still persisting but described as "ends 5 minutes ago"

**Comment by WelpThatWorked** [comment]
I was experimenting with estimate_effect_dur() and that's where I ran into the same issues. The options for what to cache are 
1) The fuzzed remaining time, but the player could still open/close the menu every turn to get a new value. Could kind of fix by adding minimum delay between re-estimation. 
2) The fuzzed original duration, subtracting time elapsed when the window opens. This would make it so the margin of error wouldn't ever narrow, as the error would not change. 
For either option, maybe put some kind of message instead of time for estimations going negative, but I'm not sure how it would be phrased without sounding ominous and unspecific like "You thought this effect would have ended by now". Being new to this project, I'm also unsure where/how to implement a cache (attached to the effect or somewhere else?)

When you say no approximation for selfaware, do you mean on just the time remaining or both?

Thanks!

**Comment by Salty-Panda** [comment]
Self-aware display HP, health, and pains as a number. So effects in seconds wouldn't stand out.

Maybe make it a hard threshold, so the player can tell the effect is"not even halfway done"? Like with food spoiling

**Comment by WelpThatWorked** [comment]
Ok, made it with 50% max error for untrained, calculated from the elapsed + remaining time, plus approximated reading can give a result like so:
![image](https://user-images.githubusercontent.com/9769385/118540478-79232d00-b705-11eb-8864-fdde9966e413.png)
Where actual remaining time is 46 seconds. Or for a longer time span,
![image](https://user-images.githubusercontent.com/9769385/118541823-061ab600-b707-11eb-862c-b938d5e81a67.png)
Where actual time a bit less than 4 hours. 
For estimates <= 0 seconds a special string, 
![image](https://user-images.githubusercontent.com/9769385/118540622-9fe16380-b705-11eb-81e8-26ece52f5836.png)
No cache still, but I think it's fuzzy enough to discourage trying to get the exact value by spamming the menu. Max error will linearly decrease as the skill approaches the threshold.

**Comment by Salty-Panda** [comment]
Looking great

**Comment by Anaglyphic** [comment]
Wow maybe I underestimate the motivation of some gamers, I can't imagine they'd exploit that other than to brag about they were the ones to discover it could be done. ??

It seems there's room for a line for the ignorant or partially-aware to indicate there's a granularity they're missing? "(you'd know more if you were only self-aware, dummy!)" seems a bit aggressive but you get the idea.

Also I get that you're working mostly on panels right now, but as an aside and pardon the noise - what are the thoughts on _thoughts?_ The inner voice intuition for the self-aware? In regards to "You thought this effect would have ended by now".

Is is too much to think a few if( is_self_aware) compares don't eat much cycles, could a self-aware individual then get a msg - not a panel entry I mean sidebar log add_msg_if_player  - when something nears the end, effect_got_checked kind of expiration, _you feel your \<blah\> wearing off._  With the same fuzziness, maybe a secondary _"you_ think _you feel your..."_ since an ignorant who has little self-awareness if they only listened to the inner dialogue msgs will eventually get themselves addicted or overdose.

This may be topic for another thread - but since you're elbow-deep in it already and thinking about this?
