### ISSUE TITLE
Cockroaches, possibly some other insects should have a very high dodge - except when wet

### ISSUE THREAD

**Issue by actual-nh** [CleverRaven/Cataclysm-DDA#48779]
# Is your feature request related to a problem? Please describe.

Cockroaches (and some other insects - possibly to a lesser degree) are capable of very good dodging, thanks to sensory hairs detecting oncoming wind from objects moving at them. (See <http://nelson.beckman.illinois.edu/courses/neuroethol/models/cockroach_escape/roach_escape.html>, for example; from what I remember of a college term paper I wrote, the speed is actually sufficient for them to start running away before a frog's tongue gets out of its mouth...) Exception: When wet. (If you're having trouble hitting a cockroach IRL, try spraying them with an aqueous solution - water, a spray cleaner... They'll be much easier to hit for a bit thereafter.)

# Describe the solution you'd like

Increase the dodge of all cockroaches (except perhaps those with STUMBLES, to reflect disruptions due to mutant anatomy), except when they are wet. Decreasing this when there is significant wind or precipitation (even if not rain) would also make sense.

# Describe alternatives you've considered
Not bothering with the "except when they are wet" part, which will take some C++ work as far as I can tell.

# Additional context
Ping: @Venera3?

This also gives rise to the idea of a cockroach mutation line.

Now going back to lab report grading... sigh.

**Comment by PatrikLundell** [comment]
I don't think the "when wet" logic scales to giant cockroaches. A water droplet can easily cover the whole of a real life size cockroach's hair (and probably most of the other hairs at the same time), and thus block it's ability to sense air currents. A drop on the tip of a hair of a giant cockroach won't have much of an effect on the rest of the hair (which would probably have to have tiny hairs sprouting out from it to be sensitive to air currents anyway). Also, giant size means slower reaction speeds because the signals have to travel longer along the sensor-brain-limbs path, as well as the mass increases faster than the muscle strength (while ignoring issues of oxygen transfer, which can be explained away with the blob, plus issues of using a chitin exoskeleton of those dimensions capable of supporting that weight and hosting muscles capable of moving it).

**Comment by actual-nh** [comment]
> I don't think the "when wet" logic scales to giant cockroaches. A water droplet can easily cover the whole of a real life size cockroach's hair (and probably most of the other hairs at the same time), and thus block it's ability to sense air currents. A drop on the tip of a hair of a giant cockroach won't have much of an effect on the rest of the hair (which would probably have to have tiny hairs sprouting out from it to be sensitive to air currents anyway).

I wasn't really talking about a small drop - more like soaking wet. I am assuming that, while the cerci (things the hairs are on in back) are larger, the individual hairs won't be - just a lot more of them.

> Also, giant size means slower reaction speeds because the signals have to travel longer along the sensor-brain-limbs path

Brain? Take a look at the page I linked. The reflex pathway goes through 

> as well as the mass increases faster than the muscle strength (while ignoring issues of oxygen transfer, which can be explained away with the blob, plus issues of using a chitin exoskeleton of those dimensions capable of supporting that weight and hosting muscles capable of moving it).

To avoid, say, a shoe, the roach has to be running in enough time to get out from under it. If it's about the same size as what's coming toward it, it just needs to move out of the way a bit. I'm not talking about giving them uncanny dodge, BTW - they would not be dodging bullets.
