### ISSUE TITLE
Carnivores can drink soy and almond milk

### ISSUE THREAD

**Issue by gisaku33** [CleverRaven/Cataclysm-DDA#48843]
Carnivores can currently drink soy and almond milks without issues from them being made from plants.

1. Make/mutate a character with the Carnivore trait.
2. Spawn in some almond or soy milk.
3. Enjoy with whatever meat-based alternatives for cookies.

Carnivores probably shouldn't be able to absorb nutrients from almond or soy milks, because they're plant products.

![image](https://user-images.githubusercontent.com/23239811/117906658-5925e080-b2a3-11eb-8aab-7c6ef14c617b.png)

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 07c58d9 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

**Comment by KomandoKartoffel** [comment]
I dunno man, depending on context. 
Maybe not 'cant' per say, maybe if carnivore consume small amount - they wont receive nutrients from it. On consumption of large amount of plant based food in short amount of time, they could get sick instead?

In real life, even lions eat grass from time to time, just to aid digestion. Same thing with giraffes, they eatbones to get the minerals since plants they eat dont provide sufficient amount.

**Comment by KittyTac** [comment]
Carnivores can also eat lettuce and herbs. Should change that I think. Though still allow them to drink tea I think.

**Comment by RelMayers** [comment]
I used flags to fix issue.
#48918

**Comment by anothersimulacrum** [comment]
Not closed for some reason by #48918
