### ISSUE TITLE
Add a cordage blindfold

### ISSUE THREAD

**Issue by KittyTac** [CleverRaven/Cataclysm-DDA#48846]
# Is your feature request related to a problem? Please describe.
No logical reason you shouldn't be able to wrap a few strings of thick cordage around your head, covering your eyes, to help you sleep in the light.

# Describe the solution you'd like
Add a "cordage blindfold" that can be crafted from a few (five should probably be enough) long cordage pieces.

# Describe alternatives you've considered
Innawoods players having unnecessary difficulty making such a simple utility item that, from a realism POV, should be able to be crafted innawoods.

# Additional context
None.

**Comment by LohTek** [comment]
Willing to take issue; have more to discuss though. I would think that wrapping cordage across your face would be extremely uncomfortable and make it difficult to sleep &/or cause bruising to your face. Thoughts?

**Comment by LohTek** [comment]
What if instead of just crudely wrapping twine across your face and eyes, we make use of the proficiency _basket weaving_.

Survival 2
Tailoring 1
Proficiencies basket weaving

10x withered plant
2x short cordage piece OR 2x short string

Desc: A crude blindfold woven from blades of grass with two pieces of string attached to fasten it. Useful for sleeping in dark areas

**Comment by KittyTac** [comment]
Yeah that could be better.
