### ISSUE TITLE
Can't move items between contained, non-rigid holsters if their parent is full

### ISSUE THREAD

**Issue by andrei8l** [CleverRaven/Cataclysm-DDA#48898]
# Describe the bug

Can't move items between contained, non-rigid holsters if their parent is full

# Steps To Reproduce
1. Start with 1x `rilfe_case_soft`, 2x `survivor_vest`, 1x `sig552`
2. Label one of the `survivor_vest` with a `permanent_marker` so you can tell it apart
3. Wear the `rifle_case_soft`, then insert both `survivor_vest` into it, then insert the `sig552` into one of the harnesses
4. Try to insert the `sig552` into the other harness. The item does not even show up in the list

You can reproduce this with any other non-rigid holsters, such as wallets (which can be particularly confusing), etc.

# Expected behavior
I should be able to freely move the items around.

# Screenshots
<details>
<summary>screenshots</summary>

![case1](https://user-images.githubusercontent.com/68240139/118398569-e4b3be80-b661-11eb-8e99-c5dac92adc4d.png)
![case1a](https://user-images.githubusercontent.com/68240139/118398571-e7161880-b661-11eb-845f-9cd4d9a14148.png)

</details>

# Versions and configuration
- OS: Linux
    - OS Version: LSB Version: 1.4; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.E-10536-g3d0463f8bd [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda]
]

# Additional context
This happens because `item_location::parents_can_contain_recursive()` checks whether the parent(s) can contain an additional copy. 
I have an ugly fix, but AFAICT it introduces its own edge cases:
<details>
<summary>patch</summary>

```diff
diff --git a/src/activity_actor.cpp b/src/activity_actor.cpp
index 54e7f0af69..e1310daafd 100644
--- a/src/activity_actor.cpp
+++ b/src/activity_actor.cpp
@@ -2387,7 +2387,7 @@ void insert_item_activity_actor::finish( player_activity &act, Character &who )
         item &it = *holstered_item.first;
         if( !it.count_by_charges() ) {
             if( holster->can_contain( it ) && ( all_pockets_rigid ||
-                                                holster.parents_can_contain_recursive( &it ) ) ) {
+                                                holster.parents_can_contain_recursive( holstered_item.first ) ) ) {
 
                 success = holster->put_in( it, item_pocket::pocket_type::CONTAINER,
                                            /*unseal_pockets=*/true ).success();
diff --git a/src/inventory_ui.cpp b/src/inventory_ui.cpp
index bd2e88f7e3..240e736ea1 100644
--- a/src/inventory_ui.cpp
+++ b/src/inventory_ui.cpp
@@ -364,7 +364,7 @@ bool inventory_holster_preset::is_shown( const item_location &contained ) const
         return false;
     }
     if( !holster->contents.all_pockets_rigid() &&
-        !holster.parents_can_contain_recursive( &item_copy ) ) {
+        !holster.parents_can_contain_recursive( contained ) ) {
         return false;
     }
     return true;
diff --git a/src/item_location.cpp b/src/item_location.cpp
index 7b0022cb37..4b6528382f 100644
--- a/src/item_location.cpp
+++ b/src/item_location.cpp
@@ -812,7 +812,7 @@ bool item_location::has_parent() const
     return false;
 }
 
-bool item_location::parents_can_contain_recursive( item *it ) const
+bool item_location::parents_can_contain_recursive( item_location const &it ) const
 {
     if( !has_parent() ) {
         return true;
@@ -821,6 +821,14 @@ bool item_location::parents_can_contain_recursive( item *it ) const
     item_location parent = parent_item();
     item_pocket *pocket = parent->contents.contained_where( *get_item() );
 
+    item_location it_recursive = it;
+    while( it_recursive.has_parent() ) {
+        if( parent == it_recursive.parent_item() ) {
+            return true;
+        }
+        it_recursive = it_recursive.parent_item();
+    }
+
     if( pocket->can_contain( *it ).success() ) {
         return parent.parents_can_contain_recursive( it );
     }
diff --git a/src/item_location.h b/src/item_location.h
index d0bbcbf75a..9210c01a6b 100644
--- a/src/item_location.h
+++ b/src/item_location.h
@@ -119,7 +119,7 @@ class item_location
         */
         units::mass weight_capacity() const;
 
-        bool parents_can_contain_recursive( item *it ) const;
+        bool parents_can_contain_recursive( item_location const &it ) const;
         int max_charges_by_parent_recursive( const item &it ) const;
 
         /**
```
</details>
i.e. exit early if the item-to-be-inserted is already contained by the holster's parent(s). There's probably an additional issue for holsters than have different min length than their parent(s).

**Comment by Salty-Panda** [comment]
Edge case happens if you consider volume_modifier and weight_modifier.

- Is already inside parent and target can contain it, but you move from dimension toolbelt to normal pouch, total volume/weight of source and target pockets increase, parent can't contain them.

**Comment by Anaglyphic** [comment]
^ I am guessing every OCD packrat has come across some form. But you know how often this one is mentioned?

(watch me paraphrase) "_HEY! Why won't objects in a backpack by themselves that only total up to XXX not fit into YYY when YYY is full ?" (shot of Pocket summary of 2.04 L, 4.10 lbs, 3.0 inches) "Does this fit into an IFAK pouch if you modify the contents while inside another bag? Yep, right up until you add something to it. Even though it's rated capacity is 3.20 L, 8.82 lbs, 8.0 inches! And don't get me started on that RIGID first aid kit box? It's total capacity is 2.46 L, 6.61 lbs, 7.0 inches and it can't accommodate even 2.04 L, 4.10 lbs, 3.0 inches even before you try to add pills into a bottle inside the bag with the i key and it tells me the it can't fit anymore? How does a pill inside a bottle affect the bottle fitting in the kit when the bottle previously fit in the kit!?"_ 

Or something. 

It always works if you remove it from the nested situation, right? in andrei's scenario if you unload the vests from the rifle case, unload the SIG, activate the other vest, and stuff em both back in? Because let's face it, we can pretend that, for immersion, since that's what you have to do if a bag is so near-full you cannot be sure if you can even re-pack it to hold the same amount again.

TBH though this does rear it's head often, maybe there's a motivated coder who thinks it needs to be 'dealt with' regardless what that encompasses, messages explaining why, throwing in repacking routine to help with space modifiers so there's some leeway? I have no idea really.

As a newbie to the project I've read this or a variant of this 36th times...

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
