### ISSUE TITLE
Crude Wooden Arrows/Bolts require Fletching Proficiency despite having no Fletching

### ISSUE THREAD

**Issue by mGuv** [CleverRaven/Cataclysm-DDA#48909]
Currently it is nearly impossible to get started with bow/arrows from a crafting perspective. The learning rate on Fletching from crude wooden arrows is so small that you basically cannot learn it without burning through valuable early resource/time.

The kicker is, Crude ammunition is effectively sharpened sticks, according to their recipe and description.

`A crude pointed wooden shaft with a notch at the back.`

`A crude pointed wooden crossbow bolt with a notch at the back.`

# Steps To Reproduce

1. Make a player with Survival 2 and Fabrication 1
2. Gather/spawn some stout branches
3. Try to craft Crude Wooden Arrow/Bolt
4. Observe that you will fail massively over and over due to lacking the Fletching proficiency
5. Observe that item recipe/description means it is NOT a fletched arrow

# Expected behavior

Crude arrows should be easily craftable with the required survival/fabrication skills. As the item is NOT fletched, I don't see why I need to master Fletching to make a pointy wooden stick. This would enable people very early game to have access to a ranged weapon. I don't see this being a problem as the Crude ammunition isn't very good.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: b4db094 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

# Additional context

Caused by this change that added Fletching to arrows: https://github.com/CleverRaven/Cataclysm-DDA/pull/46467/files#diff-74bcb1076bca7eeafb99c7fb5b3089573987f92358d5af1a71de13bfe5841ab7

Unsure if it was just missed at the time or if the arrow used to be fletched. Strangely the item ID has the word "fletched" in it, despite not being fletched. The learning rate of Fletching was massively reduced on these recipes to stop people grinding Fletching. When really, I think the right solution would be to remove Fletching entirely from Crude Wooden Bolt/Arrow.

**Comment by Anaglyphic** [comment]
Hey good catch. But you can see how that happened, the crude arrow is "id": "arrow_fire_hardened_fletched",

I agree that just removing the requirement is probably the right way, but it didn't actually stop anything right? but since you're already editing and submitting a PR, want to take it a step further? There's a couple things a motivated person could do! Just rambling, but I saw you are motivated, you forked and made a backup within minutes of checkout, and it's not even a game-breaking bug. That is fantastic.

REQS: So fletching preq makes it take 5x more fails? But in that respect it also wants Surv 2 Fab 1, which if both at 0 could take 10x fails and fletch isn't an issue. Wouldn't that be reversed? IRL every 7 year old has stabbed themselves in the hand with a pencil, making a rubber band finger ballista firing pencils at classmates. (and some 17 yr olds too). The construction is the tricky part not grasping what needs doing. It's a stick.

PARTS: Sure, it's more of a common sense thing from living around tools your whole life, but if you've never tried to make a pointy 2' straight stick without having kiln-dried oak dowels from a hardware store at your disposal, you might find it harder than you thought. Speaking of, should someone add a lootable item to mapgen, hardwood and metal dowels to loot from hardware and garden supply stores for whatever else but initially for arrow construction, especially early and mid-game to bring archery back to a viable weapon choices? Yes! Yes I think 'we' should!

DESC: Also, since your PR is sitting there waiting, perhaps another edit, for the descriptions, recipes, etc? Might as well make it obvious later on that this is intentional and not an over-correction to an oversight. Or something. _(Your edit, you decide.)
```
-    "description": "A crude pointed wooden shaft with a notch at the back.",
+    "description": "A crude pointed wooden shaft with a notch at the back, without fletching.",

and
-    "description": "A crude pointed wooden crossbow bolt with a notch at the back.",
+    "description": "A pointy stick used as a crossbow bolt, primitive and inaccurate. No vanes.",
```

**Comment by mGuv** [comment]
> but it didn't actually stop anything right?

Not 100%, no - but it essentially makes the recipe useless as the failure rate is so very high you are unlikely to get any arrows out of it. By the time you can craft it even remotely reliably, they have been out classed by the next arrow, as it's not much harder to craft in terms of ingredients.

> REQS and PARTS

Regarding this, I actually had a much larger/different idea. If the skill is Fletching, why when I fail the arrow do I lose the wooden/arrow head components to? Surely I would have made those totally separate and only messed up the Fletching over and over.

So my idea would be to move Fletching to their own item that is crafted separately and then must be used as a component in arrows. This way you could have different tiered fletching for different arrow types, as well as still supporting making them out of feathers, scrap plastic, etc. This way Fletching becomes totally decoupled from arrows and stops a failed arrow just destroying everything.

I am new to CDDA and developing for it so for a first PR I was aiming to keep it small as possible.

> DESC

I could update the description yes. I was unsure about doing this, as again, I'm new to working on CDDA so was unsure if this would require translations changes elsewhere. I will see what feedback I get on any reviews on the PR.

**Comment by PatrikLundell** [comment]
I've never tried fletching, but I would expect a significant part of the job to be to attach the "wings" to the shaft in a manner that results in a straight flight rather than a curved (or spiral) one. If that's correct, you can't really split the arrow construction, and if you botch the attachment you've probably damaged the shaft.

Changing the description would result in a change to translations, and would result in a string freeze tag. However, since 0.F is currently in the stage where it shouldn't accept any changes until release it probably doesn't matter.

**Comment by mGuv** [comment]
The ones I've seen are literally glued on. You can get a fancy device to apply them equidistantly around the shaft to make sure it flies straight but other than that, you could do it by hand.

And thanks for the follow up on the string part. I'll keep all this mind for the future and monitor my PR.
