### ISSUE TITLE
Food crafted as hot when it shouldn't be

### ISSUE THREAD

**Issue by DalenTalas** [CleverRaven/Cataclysm-DDA#48936]
Crafted food which does not require heating in the preparation (e.g., seeds) is still produced as hot.

# Steps To Reproduce

1. Spawn some grapes. Spawn some salt, sugar, and clean water.
2. Craft some grape seeds and rehydration drink from them. Observe all marked as hot.
3. Spawn some appropriate materials and see if you can make some hot ice cream (didn't try that myself).

# Expected behavior

Food should not violate the laws of thermodynamics when crafted.

# Versions and configuration

    OS: Windows
        OS Version: 10.0 2004
    Game Version: 12fcd38 [64-bit]
    Graphics Version: Tiles
    Game Language: System language []
    Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock]
    ]

**Comment by pehamm** [comment]
Can confirm, including for ice cream. The reason seems to be that the game produces hot crafts if

1. The recipe uses a hotplate
2. The result is a food item without the "RAW" flag

Grape seeds to not have the flag, which is why they come out hot. And yes, the same holds true for ice cream.

Simply removing the second check also leads to incorrect results, like atomic coffee coming out cold. I am not sure this can be fixed without going through foodstuff recipes and manually adding flags.

**Comment by DalenTalas** [comment]
If my memory serves, this is a relatively recent change. I recall food not magically heating up around Jan / Feb this year (took a break from the game between then and now).

**Comment by pehamm** [comment]
You are right, this was added a month ago in #48569 to fix another bug.

**Comment by Salty-Panda** [comment]
> You are right, this was added a month ago in #48570 to fix another bug.

Yup, totally missed this case. 
The function that checks if the recipe uses hotplate should be extended to cover atomic coffee maker.
The check for RAW flag should add a new flag, not use COOKED.

**Comment by SenpaiSlime** [comment]
I swear this happens with ANY recipe, ive been crafting hot sandwiches recently

**Comment by Inglonias** [comment]
The silliest instance of this I have seen is that dropping pruification tablets into water makes it hot somehow. This is a minor thing, but its worth investigating.
