### ISSUE TITLE
Blood has no temperature defined sometimes

### ISSUE THREAD

**Issue by Aerotinge** [CleverRaven/Cataclysm-DDA#48971]
# Describe the bug
When trying to unload blood from a blood draw kit, I am given the following error message:
```
 DEBUG    : Poured item has no defined temperature

 FUNCTION : void item::fill_with(item&, int)
 FILE     : src/item.cpp
 LINE     : 8090
```
# Steps To Reproduce

1. Kill a zombie, draw blood with a blood draw kit.
2. Try to unload blood from the kit to a gallon jug.
3. (Occasionally) The blood in jug, CDDA found it is neither warm nor cold, so made it frozen. Emit debug msg above.
4. <del>And the blood is unable to unload from the jug...</del>NVM, it's frozen.

# Expected behavior
(Also consider taking #41219(Blood overhaul) into account)

The blood draw from a kit should be the same temperature with the body, especially zombies are warm blood(WARM flag)
Also, there should be a limit units within a corpse which allowed blood draw kit to draw. I've draw a few gallon blood from this poor zombie...
More, a corpse had blood drawn should lose its weight. Not sure about butchery>skinning did the similar thing but it should also be like this.
<del>The blood should be able to 'U'nload from a container, since it is liquid.</del>NVM, it's frozen.

# Screenshots
![圖片](https://user-images.githubusercontent.com/6275647/119149240-eb866b00-ba7f-11eb-896c-d7b543651ef5.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.E-3 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
  "dda",
  "no_npc_food",
  "cbm_slots",
  "sees_player_retro"
]

# Additional context

**Comment by Xaleth** [comment]
@Hirmuolio what if the blood changes in temperature? Your PR makes it a constant, it seems?

**Comment by actual-nh** [comment]
> @Hirmuolio what if the blood changes in temperature? Your PR makes it a constant, it seems?

As far as I can tell, only at the time of draw. But testing to make sure it cools down properly in a fridge/whatever is needed.

**Comment by Hirmuolio** [comment]
Yes it just sets the temperature in that moment.
After that it is just a normal item that does normal temperature things.

**Comment by Hirmuolio** [comment]
Also since we are here in the subject of undefined temperatures I'll throw some text in here.

Lets start by what is undefined  temperature in the game.
When item spawns its temperature is set to -0.00001 kelvins. This temperature is impossible to reach in normal situations.
This acts as a marker for the temperature code to tell that this item has noe defined temperature. So the code just sets it to enviroment temperature when it encounters it.

This is not a perfect system. When item with undefined temperature interacts with normal item (mixing liquids is the only case that comes into mind) the result is nonsense temperature.

The proper fix would be to never spawn items with undefined temperatures. Instead the temperature should always be set at the item creation. But going through the code and setting the temperature of every single created item in every single place of code where item is created would be unreasonable amount of work.
And to make things worse items can spawn in undefined places where there really aren't any temperatures. (for example I think map generation adds some items before the map has temperature so the temperatures can't be set).

Maybe the solution would be to require the undeined temperature to be explicitly set when the item is created if the item is of type that has temperature. Trying to spawn temperature eglible item without explicitly setting its temperature would spit out errors. That should get rid of the accidental spawning of items with undefined temperature.

**Comment by actual-nh** [comment]
> Maybe the solution would be to require the undeined temperature to be explicitly set when the item is created if the item is of type that has temperature. Trying to spawn temperature eglible item without explicitly setting its temperature would spit out errors. That should get rid of the accidental spawning of items with undefined temperature.

How would one then specify "ambient temperature"?
