### ISSUE TITLE
Add automatic intermediate changelog

### ISSUE THREAD

**Issue by Cenness** [CleverRaven/Cataclysm-DDA#49006]
# Is your feature request related to a problem? Please describe.
There is no layman accessible changelog for experimentals

# Describe the solution you'd like
Extend current github actions with something like [that](https://github.com/marketplace/actions/generate-changelog-action) or [that](https://github.com/marketplace/actions/release-changelog-builder), or whatever you prefer from [there](https://github.com/marketplace?category=&query=changelog+sort%3Apopularity-desc&type=actions&verification=).

# Describe alternatives you've considered
Decide that it's not really that important or just use `git log`

# Additional context
https://github.com/remyroy/CDDA-Game-Launcher/issues/564

**Comment by actual-nh** [comment]
There is a changelog, although not what you're asking for; I suggest changing the title to "Add automatic intermediate changelog" or something like that.

**Comment by Anaglyphic** [comment]
Hi.

I get your point.  Your alternative _"decide it's not really that important or just use git log"_ is actually what I'd suggest. So what are you asking, how to? I see you got ZhilkinSerg and the frontend creator interested over there? I'll show the long form of what you exampled, so you can see how easy it is to tailor it, although I assume _"layman accessible"_ and referencing remyroy's frontend = an average Windows gamer, so I suppose we should keep it clean and non-technical? (_not that windows people can't be technical, this is more about "hey what's changed since the last experimental I installed?" and not about "what's going on in cdda development?", yes?)_

Anyway yea from the project side there's no reason the Makefile or whatever preferred build system people are using couldn't generate an automated pseudo-CHANGELOG, modify a build script, dump a one-liner into the make / make bininst routine, or even do it manually before packaging, so there'd be _something_ besides the semi-static one I guess? Then said frontend could just display it being the nice little text file it is?

I'll do it by date, I saw you did it by tag in your example. ie. here's the last week.

```
$ git switch master && git pull && git log --since=05/18/2021 \
--simplify-merges --first-parent --author-date-order \
--date='format:%d-%b-%Y' --pretty='format:%ad: %s (%an)'
```
currently dumps:

```
24-May-2021: Merge pull request #49007 from MarlossCDDA/marloss/fix-rot-spawn-chance (Angela Graves)
23-May-2021: Do not announce crafting progress loss when none happened (#48985) (pehamm)
23-May-2021: Merge pull request #49000 from BrettDong/clang-tidy-fix (Zhilkin Serg)
23-May-2021: Merge pull request #48997 from BrettDong/osx-build (Zhilkin Serg)
23-May-2021: Merge pull request #48958 from eltank/no_leatherworking (Angela Graves)
22-May-2021: Change symbols of variants vehicle parts to increase ascii readability (#48896) (Fris0uman)
22-May-2021: Merge pull request #48944 from John-Candlebury/ags-harvest-list-bloodfix (Zhilkin Serg)
22-May-2021: Merge pull request #48966 from Fris0uman/msc_craft (Zhilkin Serg)
22-May-2021: Bump clang version to 12 in GHA build matrix (#48977) (Binrui Dong)
22-May-2021: Merge pull request #48973 from Fris0uman/CMES (Angela Graves)
21-May-2021: Merge pull request #48968 from Fris0uman/tilesets (Angela Graves)
20-May-2021: remove watertight flag from body bags (#48947) (eso)
20-May-2021: Fix removed depressant&stim cap (#47831) (Jamuro-g)
20-May-2021: wash multiselect - fix unselect (#48863) (Roy Berube)
20-May-2021: Fix remote activation for radio-controlled items (#48801) (eltank)
20-May-2021: Fixes #48686 (#48778) (leemuar)
20-May-2021: Fix auto drinking unclean water (#48738) (Eric)
20-May-2021: don't ask for shape selection when there's only one shape (#48734) (mqrause)
20-May-2021: [READY] Adjust problematic monster faction relationships (possible attack without counterattack) (#48077) (actual-nh)
20-May-2021: Dismantle unused legacy migration feature. (#48871) (Kevin Granade)
20-May-2021: Merge pull request #48941 from casswedson/prison-fix (Angela Graves)
19-May-2021: Merge pull request #48901 from casswedson/thickness-fix (Zhilkin Serg)
19-May-2021: [Aftershock] Small fixes (#48931) (Maleclypse)
19-May-2021: Merge pull request #48934 from BrettDong/lang (Zhilkin Serg)
19-May-2021: Merge pull request #48914 from linonetwo/patch-2 (Angela Graves)
18-May-2021: Remove Fletching from Crude Wooden Arrows and Crude Wooden Bolts as they do not have Fletchings (#48910) (mGuv)
18-May-2021: Merge pull request #48920 from casswedson/nerf-manhack (Angela Graves)
17-May-2021: Revert "Removes PROTRUSION flag, so rams can ram more things" (#48913) (eso)
```

**Comment by damien** [comment]
I'm currently working on #52477 and hope to have something ready to review in the next week. I hope to have that work cover needs for intermediate changelogs like the ones described here. :)

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
