### ISSUE TITLE
Warning Query Sanity

### ISSUE THREAD

**Issue by dwarfkoala** [CleverRaven/Cataclysm-DDA#4900]
Now, there's a lot of more interesting actions you can do in the game, and many of which have a warning if monsters or sounds or what have you come nearby and interrupt you, in the form of the warning query.  Now, this is a good thing. If you're digging or making some arrows you obviously want to know there's a zombear about to go and ruin your day, right?  

Now there are a couple of actions that do not create queries, in the hope of not clogging gameplay with thousands of queries. That's usually because the action is too short for something to actually screw you over extensively while you're doing it. Stuff like picking up an item or smashing a corpse.

Now, where's the problem? The problem is that these actions add up, and no queries are applied to them even when they add up. 

Let's say you want to pick up 100 rocks, for reasons, when suddenly, the world erupts into an RNG-fueled apocalypse of epic proportions. Jabberwockies rise from the earth, zombie hulks approach, get up to you, and rip your arms off! A mininuke explodes next to you! You're deafened by the screams of a thousand angry jabberwockies! Tankbots approach and machinegun your legs off!

And your character, smiling happily, does not move from their spot and picks up that last rock, satisfied with a job well done.

Oh yeah, you've got 900 pain and no limbs. And you couldn't do anything to prevent it because there's no warning queries for picking up items. Interface screw at it's finest.

How do we solve this? We can't add queries to these actions, and I think the problem with too many queries is pretty darn obvious. You don't want to be warned every time you pick up an item, every time that you smash a corpse, or, as showcased in Cataclysm Metal Gear Solid by the well known Lazycat, every time you move across a counter, bush, underbrush, young tree, bed, or scale the harrowing heights of Mount Picket Fence.

So how do we solve this and other warning-query related issues? Obviously, we can't add queries for all of the actions that could cause problems, as that would take way too long.

Here's my solution:

Give each action a "time" variable that shows how long it takes. Base whether queries come or not on whether or not the "time" variable surpasses a certain threshold.

Why is this good?

A: It handles all actions in a unified way, so it's less likely that a new action will have problems like picking up items does now.

B: It fixes picking items up and other actions like it. Picking up one item will not trigger the warning queries, but since the "time" variable is calculated based on the total time it would take to complete an action, picking up rocks for 5 minutes would trigger warnings.

C: It doesn't cause excessive queries. On the most, you should see one or two new queries, and they should be in cases that such an action would be necessary.

Changes, criticism, suggestions? Please reply below.
##

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
