### ISSUE TITLE
Make driving skill truly meaningful

### ISSUE THREAD

**Issue by CivilisationDDA** [CleverRaven/Cataclysm-DDA#49018]
# Is your feature request related to a problem?
**The driving skill is practically useless. Disabling it has no meaningful impact on gameplay.**
In theory a low driving skill makes it difficult to steer reliably (*you fumble with the controls*), and increases recoil from firing one-handed weapons. But these are meaningless in practice, for example I have maneuvered through a swarm of zombies and triffids with 0 driving skill character who was drunk. The recoil aspect is mostly meaningless as being in a moving vehicle means you can easily outpace any chasing Z's and take your time to aim.

A 0 driving skill @ can control and steer a 7kg tricycle, 700kg boat and a 7000kg semi-truck. I play stable but presumably a 0 driving skill @ can also control and steer a helicopter?

# Describe the solution you'd like
IMO driving skill should relate to:
- **Ability to take control of different engine types**
- **Reliable steering output depending on vehicle mass**
- **Reliable acceleration (+ve and -ve) output depending on vehicle mass**
- **Aim speed, dispersion and recoil of guns while controlling a moving vehicle**
- **Dispersion of mounted turrets while controlling a moving vehicle**

What this would look in practice with driving skill of:
- 0: Can control manually powered (foot pedals, handrims, oars) vehicles but steering and acceleration input results in unreliable output. So your @ on a bicycle can't travel in a straight line and is occasionaly thrown off because of sudden -ve acceleration (if a seatbelt isn't installed).
- 1: Can reliably steer and accelerate a <50kg vehicle. Can take control of a low power(A-B horsepower) vehicle. Steering and acceleration input results in unreliable output if vehicle is >50kg. So your @ on a dirtbike can't travel in a straight line and is occasionaly thrown off because of sudden -ve acceleration (if a seatbelt isn't installed).
-  2: Can reliably steer and accelerate a <400kg vehicle. Can take control of a medium power(B-C horsepower) vehicle. Steering and acceleration input results in unreliable output if vehicle is >400kg. So your @ in a citycar can't travel in a straight line but can reliably steer and accelerate a quadbike.
- 3: Can reliably steer and accelerate a <1500kg vehicle. Can take control of a medium power(C-D horsepower) vehicle. Steering and acceleration input results in unreliable output if vehicle is >1500kg...
- ...*and so on*...

# Describe alternatives you've considered
- Introduce an odometer vehicle part
- Introduce different vehicle controls: steering wheel, handle bars, yoke/control column, rudder+wheel etc.
- Introduce martial art style training books for floating vehicles, flying vehicles, fuel powered vehicles, steam powered vehicles etc.

# Additional context
- According to the wiki *you fumble with the controls* caps out at driving 4...
- The notion that you can accurately fire an assault rifle one handed over your shoulder while driving is kind of ridiculous...
**Edit:**
- There is also a discrepancy between rapid -ve acceleration through the handbrake vs by repeatedly pressing `2`. Going from 80km/h to 0km/h by hitting `s` will most likely result in a skid but doing so by pressing `2` multiple times  will not.

**Comment by The-Numbers** [comment]
I don't know if i fully agree with your ideas for implementation, but I do agree with the skill lacking meaning. I don't think even an expert level driver would be able to accurately fire a rifle while driving, nor do I think a brand new driver should be perfect at driving. However, i don't know if i agree with making it a level by level requirement to drive. That almost sounds like something that should be gated by proficiency. 

Just because your character has driven a car for hundreds of miles doesn't mean they would be able to perfectly steer a motorized bicycle their first try. They're two very different vehicles that require different skills to operate. 

Similarly, just because you've driven a bike around for tons of miles, you couldn't just get into a big rig and operate it effectively. In real life you need a special license to operate them, and have been trained to do so.

 In order to be able to steer a bus or big rig accurately, you would need prior experience doing so. I think in order for this issue to be solved, proficiencies would need to extend to vehicles, and weight, tire size, engine throttle, etc would need to be taken into account when steering. I don't think it's as much as a black and white issue, but i wholely agree that the current system is somewhat limited.

**Comment by Paperbell** [comment]
Maybe those can be turned into different proficiencies, like vehicles that are proportionally wider/longer with different weight distributions, and the driving skill can also change how fast you learn them.

**Comment by CivilisationDDA** [comment]
@The-Numbers  @Paperbell 
I play stable so I don't have any experience with proficiencies but that would work as well. 
The reason I suggested using vehicle mass was that it is an easy, roughly accurate proxy for all other vehicle attributes but if a more nuaced system can be implemented then I'm all for it.
Basically I would welcome anything that makes it harder to jump in a light vehicle and escape Z's and/or jump in a heavy vehicle and mow down Z's.

**Comment by The-Numbers** [comment]
> @The-Numbers @Paperbell
> I play stable so I don't have any experience with proficiencies but that would work as well.
> The reason I suggested using vehicle mass was that it is an easy, roughly accurate proxy for all other vehicle attributes but if a more nuaced system can be implemented then I'm all for it.
> Basically I would welcome anything that makes it harder to jump in a light vehicle and escape Z's and/or jump in a heavy vehicle and mow down Z's.

No i agree that is a decent bandaid approximation, just i feel like experience with a particular size would be more applicable than straight driving level. I've driven plenty in real life, but i would be absolutely afraid of being told to just drive a bus or long haul truck. I don't think there is an easy permanent solution, but in the short term mass would certainly suffice.

**Comment by jtgibson01** [comment]
Before I start this paragraph, let me just establish that I do think the majority of the idea is good and definitely should go in.  However, I think a presumption of basic competency with any passenger car or bicycle should be a given in the modern world; the only people who are so incompetent as to be completely incapable of operating a modern car are those people who have actively avoided them their entire lives -- i.e., they have a trait that makes them opposed to the use of vehicles... which is already in the game. =)  This presumption of competency also reflects the fact that literally every profession in the game would have to be assigned skill at driving, which is a lot of additional work for something that would probably default at least to level 3 for every profession to begin with.  I do like the notion that certain vehicle types require certain proficiencies -- iI would expect any person to be proficient with all "seat"-based vehicles and any "saddle"-based vehicle without a motor, but a "saddle"-based motor vehicle is another matter, as is a large truck, a vehicle with large blind spots, and a heavy-duty vehicle.

I definitely agree with the principle that larger rigs need much more skill and technique to operate, and fortunately, it's actually quite easy to programmatically determine how hard it is to handle a vehicle: the power of its engine.  A basic soccer dad, no matter how cool he thinks he is, will have no idea how to handle a 900-horsepower W12 Mercedes-Benz S-class at the limit.  Likewise, a big 550 hp truck needs considerable talent to drive.

High *performance* operation (in excess of the weather conditions, or in the shameful "single-operator crash" in excess of their own ability) is what causes crashes: throwing for a chance to fumble controls *every turn* above your competent top speed, *or* if there is a planned change of speed above, say, 5 tiles per second (20 mph/36 km/h).  A failure causes standard fumble.  A critical failure results in a skid.  Thus, I'd suggest that 0 skill conveys basic competency with unpowered "saddle"-based vehicles and powered "seat"-based vehicles which produce under 150 kW of power (200 horsepower), allowing effortless operation of at up to 50% (?) of top speed.  Each additional skill level conveys competency with a *cumulative* +100 kW of power (+130 hp) per level, so 150 kW at level 0, 250 kW at level 1, 450 kW at level 2, 750 kW at level 3, etc.), and increases the top speed by +10% (so at driving 5, you are already capable of handling a vehicle at any speed *during routine straight-line driving* -- but still have a risk of a skid during high-performance braking or acceleration).

I like the notion of a rider throwing himself when braking hard at low skill level, and would actually extend that to every vehicle, where if the seat is belted it simply results in a fumble and skid rather than being thrown -- I once temporarily lost control IRL, under more-or-less closed-course conditions (open lot/no risk of crash), by being pushed up against my door with my seatbelt on when I deliberately tried a high-G acceleration.  (I double-checked the legality and unfortunately it's not legal to hoon around a parking lot even when there is no risk to anyone, so that was the last time I ever practised it.  I imagine I could do better if I tried again, a decade of driving later, but that stuff should definitely be saved for the track. ;-))

I think winter, snow, and rain also need to have more of an effect on gameplay -- and, in fact, "winter driving" might even be a proficiency that most people would lack by default -- but that's a different issue.

**Comment by CivilisationDDA** [comment]
@jtgibson01 
>I think a presumption of basic competency with any passenger car or bicycle should be a given in the modern world
Really? Even in the real world there are plenty of different ways to start the ignition of a vehicle. There is also the real world difference of transmissions and controls. With bicycles a basic competency (assuming you mean theoretical knowledge) is irrelevant as it is a gestalt skill. In case you don't remember what it's like to not be able to ride a bike try a reverse steering bike (https://www.popularmechanics.com/science/a32760740/riding-a-backwards-bike/)

>the only people who are so incompetent as to be completely incapable of operating a modern car are those people who have actively avoided them their entire lives
In other words novices to driving. One can be a novice at any age.

>literally every profession in the game would have to be assigned skill at driving
I disagree. If and when different vehicle proficiencies are added to the game each profession will have them added if specifically relevant. In general though there should be a proficiency point pool.

Regarding the above points I think the Wayfarer trait does need to be split up - currently it blanket restricts the use of controls.

Just to reiterate my understanding of what in-game driving skill relates to in the real world: 
- ability to use specific vehicle controls: simple boolean:y/n,
- ability to produce desired acceleration (how much do I manipulate the accelerator pedal, brake pedal, throttle stick etc.): scales with vehicle mass, engine power, terrain conditions
- ability to steer in desired vector (how much do I manipulate the steering wheel, column stick etc.): scales with vehicle mass, engine power, terrain conditions

**Comment by jtgibson01** [comment]
> > I think a presumption of basic competency with any passenger car or bicycle should be a given in the modern world
> 
> Really? Even in the real world there are plenty of different ways to start the ignition of a vehicle. There is also the real world difference of transmissions and controls. With bicycles a basic competency (assuming you mean theoretical knowledge) is irrelevant as it is a gestalt skill. In case you don't remember what it's like to not be able to ride a bike try a reverse steering bike (https://www.popularmechanics.com/science/a32760740/riding-a-backwards-bike/)

Really!  To draw on my legal background, a presumption is just that: a presumption.  A presumption is rebuttable, but it is a general rule of thumb that cannot be overruled unless specifically proven otherwise, such that a reasonable person (which almost always means "a judge") would believe it on a balance of probabilities.

And basic competency is a *good* presumption:
Population of the United States: 331,449,281 (2020, [Wikipedia](https://en.wikipedia.org/wiki/Demographics_of_the_United_States))
minus Number of U.S. licensed drivers (i.e., basic competency): ~230,000,000 (2019, [Statista](https://www.statista.com/statistics/191653/number-of-licensed-drivers-in-the-us-since-1988/))
minus Number of U.S. minors (who definitely do not have licences): ~73,000,000 (2019, [U.S. Child/Family](https://www.childstats.gov/AMERICASCHILDREN/tables/pop1.asp)), less ~10,000,000 for those aged 16~17 (who are still minors)
Number of U.S. seniors (who may or may not have licences): ~65,000,000 (2020, [U.S. Social Security](https://www.ssa.gov/news/press/factsheets/basicfact-alt.pdf))

Which puts the number of *incompetent* drivers conservatively at 35 million and liberally at *zero*, so splitting the difference and putting it at around 17.5 million means that around 5% of U.S. drivers who *could* be competent at driving are not, making 95% -- the cutoff of statistical significance -- competent at operating a motor vehicle.  Which means that unless the character has a specific trait that makes them incompetent, you can presume they're competent.

Also, at least 97% of cars on U.S. roads are automatic transmissions, with either a start button or a keyed ignition and no special process needed to start them or operate their transmission.  Here I'm of course assuming that a passenger vehicle is literally a light or medium truck or car.


> > the only people who are so incompetent as to be completely incapable of operating a modern car are those people who have actively avoided them their entire lives
> In other words novices to driving. One can be a novice at any age.

But how many people are *actually* novices?  Is anyone being a novice a safe *presumption* to make?  I would never presume a lack of competency.  There are millions of people who use the road every day and, comparatively, millions of road trips that are engaged in without incident.

I think the problem here is you're thinking I mean "proficiency" when I say "competency".  Competency just means that you can do a grocery run without incident.  Attempting to engage in any high performance manoeuvres, you'd discover that the substantial majority of the population is entirely unproficient -- even myself, way back when, when I first got my sportscar.  And that is where I substantially agree with your idea: I think hard accelerations, hard decelerations, and hard turning -- especially if there are lots of zombies visible to cause stress -- should require frequent throws for proficiency, and I think attempting to operate a vehicle that is too big or powerful for you should require frequent throws just for keeping the thing on the road at all.


> > literally every profession in the game would have to be assigned skill at driving
> 
> I disagree. If and when different vehicle proficiencies are added to the game each profession will have them added if specifically relevant. In general though there should be a proficiency point pool.

Except the stats don't lie: by my calculations above, conservatively, at least 90% of the U.S. adult population is competent at using a motor vehicle, and more likely that number is closer to 95%.  That means that 90%~95% of the professions would need to know how to use a motor vehicle, which means that 90%~95% of all classes would be given {"level" 3, "skill": "driving"}, which obviates the need for that function.

If something is the norm rather than the exception, then you should track the exceptions rather than the norm; this saves time and is more memory efficient, if nothing else.

 
> Regarding the above points I think the Wayfarer trait does need to be split up - currently it blanket restricts the use of controls.

Agreed there -- I do think, for instance, one of the roguelike classes ought to be able to operate a bicycle just fine, but would be entirely incompetent with a motorcycle and motor vehicle, for instance.  Those would be different traits.

Wayfarer is good for those few people who have a moral objection to operating motor vehicles, but it doesn't cover the cases of people pulled in from other dimensions, or the Worst Driver-styled scenarios where they *can* operate one but are scared to death of doing it.


> Just to reiterate my understanding of what in-game driving skill relates to in the real world:
>     * ability to use specific vehicle controls: simple boolean:y/n,
>     * ability to produce desired acceleration (how much do I manipulate the accelerator pedal, brake pedal, throttle stick etc.): scales with vehicle mass, engine power, terrain conditions
>     * ability to steer in desired vector (how much do I manipulate the steering wheel, handle bars, control column etc.): scales with vehicle mass, current velocity, terrain conditions

And I agree with all of that. =)  My competency cutoff is just different than yours: being bold (so including the people who *don't* drive, but excepting the moral-objectors and people afraid of cars), I think everyone in America knows how to start any full-sized car or medium (box) truck or lesser, move the automatic transmission from Park to Drive, and move and steer the vehicle in a straight line or in low speed turns.  I think everyone in America knows how to accelerate smoothly, anticipate corners, and come to a complete stop at a desired position.  I think everyone in America knows the rules of traffic (which aren't even a competency needed post-Cataclysm).  I think everyone in America knows where to locate and how to operate the turn signals, headlights, heater, air conditioner, windows, stereo, and dome lights of any vehicle, within five seconds of entering that vehicle.

I do think the skill needs to be modified, substantially, to increase risk of driving at low skill.  Basically, my stance is to take everything you said about "level 3" being the baseline for being able to operate a vehicle <1500 kg, and shift that to "level 0", but apply all of the penalties you proposed at the same progression (rather than shifted left by 3).  A level 0 person may be competent enough to operate a motor vehicle, but is a novice -- even woefully incompetent -- at *performance* driving.

Or, TL/DR:

> ...
> ...
> take control of vehicle in A-B horsepower
> ...
> ...

My only real objection: take control of vehicle in X-Y horsepower.  Unless the "B" threshold of horsepower is around the peak of the range you'd find in a high-end passenger vehicle, it would result in extremely unusual behaviour where a person gets into, say, a modern electric vehicle and is incapable of finding the prominent start/stop button, because the horsepower rating is just too high for them to handle.

**Comment by CivilisationDDA** [comment]
@jtgibson01 
I can see that restricting the ability to take control of vehicles like I originally suggested is pretty skewed towards gamism as opposed to realism. This has been pointed out by other commenters too.
I tend to forget that the game's design document specifically references New England in the US; the stats for the rest of the world are probably way different.

>I do think the skill needs to be modified, substantially, to increase risk of driving at low skill. Basically, my stance is to take everything you said about "level 3" being the baseline for being able to operate a vehicle <1500 kg, and shift that to "level 0", but apply all of the penalties you proposed at the same progression (rather than shifted left by 3). A level 0 person may be competent enough to operate a motor vehicle, but is a novice -- even woefully incompetent -- at performance driving.

This I can agree with - provided two wheelers, boats and aircraft are hived off the driving skill.

**Comment by alph4numb3r** [comment]
I mostly agree with https://github.com/CleverRaven/Cataclysm-DDA/issues/49018#issuecomment-870894478, except for a few things.

Motorcycles should be a separate proficiency, as that requires actual physical experience. It should only take a dozen or so hours of practice to be able to consistently keep it upright and make turns (a.k.a 'principles of motorcycling'), but doing so at speed or in rough terrain would require further practice.

Similarly, I also don't think that just practicing 'driving' will ever make you truly proficient at advanced maneuvers that you have never performed, so those should also be separate proficiencies (though in rough groups, for the sake of everybody's sanity).

However, I do feel like higher driving skill should help with improvising such maneuvers until you have the relevant proficiency (just like how enough crafting skill compensates for the failure chance from missing crafting proficiencies).

As I personally do not have a lot of experience with driving motor vehicles (the blessing of being born in a country where bicycles are king and public transit is quite serviceable), I can't judge what the details should look like, but hopefully these suggestions make sense both in terms of realism and tolerable (though preferably enjoyable) gameplay.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
