### ISSUE TITLE
An idea for solving the wait caused by long hours of operation in multiplayer games

### ISSUE THREAD

**Issue by JXMss** [CleverRaven/Cataclysm-DDA#49028]
# Describe alternatives you've considered
I was wondering if it would be possible to circumvent the boring wait when performing long actions (such as crafting items) under multiplayer by creating new characters or controlling NPCs directly for activities, as if one player was controlling many characters. Allowing the player to switch to another character and operate that character when one character is performing a long action.

**Comment by The-Numbers** [comment]
I don't think multiplayer would ever be worth the development time. I think it would be better explored in a fork.

**Comment by Anaglyphic** [comment]
Hi.

This is not a tech support forum, this is why the downvotes I think. I will answer because it's now searchable, but you probably want to close it.

Sure you _can_, but maybe you shouldn't. And no, not in the same running instance of the game as the character doing the "long" task, that's beyond the scope for now. Just start another instance. And another. And another. You can run as many instances of cataclysmdda as your system resources allow. You could feasibly run 100s simultaneous OpenGL instances without any discernible slowdowns on a modern machine with plenty of RAM. I frequently have half a dozen running... although individually. Having _multiple_ characters access the _same_ world will eventually lead to "interesting" results.

You make instances share the same characters and worlds with --datadir option, but again, if you corrupt everything? You get to keep all the messed-up corrupted game files! And I'm not sure anyone will help you when you do. I highly recommend not using the same character at the same time in the same world. Bad idea. Same goes for installing different versions of cataclysm and pointing them all to the same --datadir. Bad Idea. Use the exact same version for each instance.

Note: If you're a Windows gamer, you might need to make duplicate installs in different directories; Windows is picky at times about running multiple instances of the same executable, I it won't, you just copy your d:\cataclysm to d:\cata2, d:\cata3, etc. and then use the --datadir option on each duplicate to point to the data directory under d:\cataclysm, and it should be fine. If you're the kind of gamer that uses a cdda frontend, I have no idea how.

In linux or osx it's simple enough:

`./cataclysm --datadir ~/cataclysm/shared/` _(and in here is your core/  credits/  data/  font/  gfx/  etc. and all the bits, but the important part being  **save/**)_

Regardless, if you figure it out this will solve your problem re: waiting for "long" processes, but please remember it's not 'if' you corrupt everything it's more like 'when'. I'm sure you've searched the discourse and subreddit on multiplayer already and know. If you care about your game, you would do well to make save/ backups regularly.

I would say "good luck!" but I know where you're headed. It can be fun, so go for it, but don't be mad when it breaks, either.

**Comment by Alex-Folts** [comment]
> Having _multiple_ characters access the _same_ world will eventually lead to "interesting" results.

Access to world at same time could lead to data racing when few instances of the game write into world save file, but this could be fixed if hold world data in database - database server would internally resolve all this stuff. Then you can allow connect to your database server over network and now you have sort of multiplayer. but implementation would require bunch of time, and 3 times more time to test and debug it...

**Comment by kevingranade** [comment]
Any form of shared-instance multiplayer is out of scope for dda. We accidentally support shared-world multiplayer with multiple instances reading from and writing to the same save (see watchcdda.net), and have minor features to better support this, but that is the extent of our interest.
