### ISSUE TITLE
Make buthcer needs butchering qualty,not cutting

### ISSUE THREAD

**Issue by Ali-Anomma** [CleverRaven/Cataclysm-DDA#49068]
# Is your feature request related to a problem? Please describe.
If you start with fabrication 0,you cant train you fabrication above level 1 because lack of cutting tool.
to make cutting tool,you need bone,but butcering bone needs a cutting tool.

# Describe the solution you'd like
Make butchering needs tool with butchering,not cutting;so we can use flints for butchering.

# Describe alternatives you've considered
Make another steeless alternative cutting tool

# Additional context
none

**Comment by Saicchi** [comment]
There are many recipes using fabrication level 0 and level 1 that don't need a cutting tool.
Search for `p:fab` in the crafting menu.

**Comment by Ali-Anomma** [comment]
> 
> 
> There are many recipes using fabrication level 0 and level 1 that don't need a cutting tool.
> Search for `p:fab` in the crafting menu.

[there is the list that things can be crafted on fabrication 0](https://www.cdda-trunk.chezzo.com/skills/fabrication/0)
as you can see,there is nearly nothing to craft without cutting tool or steel.
Also things like flint cannot butcher even they have butchering qualities.

**Comment by Saicchi** [comment]
`pebbles`, `fishing hook`, `bundle of rags/leather/felt/planks/rebars/branches`, `light wooden frame`, `pot helmet`, `spike`, `makeshift crowbar`, `nailboard`...
One of the recipes which I saw that don't use cutting, mostly hammering one, which is given by a rock. Crafting x6 pebbles was enough to bring me to fabrication one, and that is only 7 rocks ( one for the hammering tool ).
At fabrication level 1 I found `wooden frame`, `blindfold`, `duct tape wallet` as one of the easy recipes to make which don't need cutting.

You'll have an easier time finding the recipes through the in-game menu.
Also getting a cutting tool is not hard, there are various starts which give you one, and such tools are abundant in houses and cabins.

**Comment by Ali-Anomma** [comment]
> 
> 
> `pebbles`, `fishing hook`, `bundle of rags/leather/felt/planks/rebars/branches`, `light wooden frame`, `pot helmet`, `spike`, `makeshift crowbar`, `nailboard`...
> One of the recipes which I saw that don't use cutting, mostly hammering one, which is given by a rock. Crafting x6 pebbles was enough to bring me to fabrication one, and that is only 7 rocks ( one for the hammering tool ).
> At fabrication level 1 I found `wooden frame`, `blindfold`, `duct tape wallet` as one of the easy recipes to make which don't need cutting.
> 
> You'll have an easier time finding the recipes through the in-game menu.
> Also getting a cutting tool is not hard, there are various starts which give you one, and such tools are abundant in houses and cabins.
> 
> > Also things like flint cannot butcher even they have butchering qualities.
> 
> Flint has a `-50 butchering` quality. It's clearly not something you'd want to use for butchering.

these are not suitable for wilderness starts because they are relies steel. (except pebbles)
flint is not a butchers choice,but it is needed for extracting bone and crafting a bone shiv.

**Comment by Anaglyphic** [comment]
Hey Ali-Anomma, not sure how - more importantly _what_ - could be done here.
Butchering is a subset of cutting - how can you butcher without cutting?! It doesn't need separation, it's quite connected.

_>> Crafting x6 pebbles was enough to bring me to fabrication one, and that is only 7 rocks ( one for the hammering tool )._

**^This.** Could this be a _"doesn't work my way"_ vs _"this is how the game works"_ kind of complaint? We know in the clothes-on-your-back "another lucky but useless survivor" starts, we need a couple points in some important abilities at the beginning so we do things like building stuff we might not even need or intend to use, other than a stepping-stone to the next item, to increase our skill(s)?

Examining the landscape, poking at trees and flowers and bushes, foraging for edibles, etc. That alone will give your Survival a couple quick levels; grab a flaking rock and mash out a stone chopper. (grab a couple since without knapping you might fail a lot). If you kill even one thing or find a carcass you have a chance of bone and then making a bone shiv/billet/punch and various primitive tools, maybe a stone knife, both bone shiv and stone blade are butchering 11-12? You'll probably find a flint or two just from your digging stick creating a shallow pit for the fire ring too.

OK. How about this - What's your best outcome here? You left that part out. "Another steelless alternative" - so what is that, _exactly_? Another step in an existing construction, like: stout branch -> pointy stick -> wooden knife ? How are you shaping it, sharpening it? With the stone knife you already made? Then wouldn't you just use the stone knife? See the issue?

It sounds like you just want things to be easier, or involve less steps, stepping stones to get to where you need to go. That's probably a different game. Maybe i misunderstand - I'd love to hear your "alternative" to butchering without a proper cutting tool - all I see is me bashing on a carcass with a flaking rock and blood is flying everywhere and there's only 1 portion of usable meat and it's filled with lots of tiny sharp rock shards.

(hyperbole follows) I mean, imagine the absurdity - what if you asked the Magiclysm maintainers to add a cast for it. Spell of Master Butchery! Carcass glows and hovers while being neatly sectioned with Butchering 100 precision, and falls down in neatly sorted piles, primals all portioned by cut and wrapped in paper and tied with butcher twine, any "additionals" cleaned up and made sterile, and all the disgusting viscera teleported away so you don't have to see or smell it. Cause, you know, MAGIC! Do you think anyone would want that? (hyperbole ends)

**Comment by anothersimulacrum** [comment]
I haven't seen any complaints since https://github.com/CleverRaven/Cataclysm-DDA/pull/50044 was merged. If there are still any, let me know and I can reopen the issue.
