### ISSUE TITLE
Segmentation Fault while repairing Molle Pack

### ISSUE THREAD

**Issue by GamerKilroy** [CleverRaven/Cataclysm-DDA#49154]
Hello.

I'm still new to the game, hope this is the correct place to report bugs.
Today i was repairing a Molle pack while in my evac center. Nothing else happening around me, i'm alone fixing my stuff.

Game crashed with Segmentation fault. No other info was provided.
I'm playing on Linux, so i got access to the Terminal that launched the game.
Here's the terminal log.

> The program has crashed.
See the log file for a stack trace.
CRASH LOG FILE: ./config/crash.log
VERSION: 0.E-10395-g4525b4f
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:

    ./cataclysm-tiles(debug_write_backtrace(std::ostream&)+0x49) [0xc365b3]
    ./cataclysm-tiles() [0xc1e7b8]
    ./cataclysm-tiles() [0xc1e93a]
    /lib/x86_64-linux-gnu/libc.so.6(+0x41950) [0x7fd4583b2950]
    ./cataclysm-tiles(item::ammo_required() const+0x1a) [0xdedcf6]
    ./cataclysm-tiles(activity_handlers::repair_item_finish(player_activity*, player*)+0x16be) [0xa623d1]
    ./cataclysm-tiles(std::function<void (player_activity*, player*)>::operator()(player_activity*, player*) const+0x24) [0xa84936]
    ./cataclysm-tiles(activity_type::call_finish(player_activity*, player*) const+0x39) [0xa83c8f]
    ./cataclysm-tiles(player_activity::do_turn(player&)+0x963) [0x1260ceb]
    ./cataclysm-tiles(game::process_activity()+0x4b) [0xcf8977]
    ./cataclysm-tiles(game::do_turn()+0x257) [0xd26ee7]
    ./cataclysm-tiles(main+0x1336) [0x93c05c]
    /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf2) [0x7fd458399cb2]
    ./cataclysm-tiles(_start+0x29) [0xa180c9]

    Attempting to repeat stack trace using debug symbols…
    debug_write_backtrace(std::ostream&)
    ??:?
    log_crash
    crash.cpp:?
    signal_handler
    crash.cpp:?
    ??
    ??:0
    item::ammo_required() const
    ??:?
    activity_handlers::repair_item_finish(player_activity*, player*)
    ??:?
    std::function<void (player_activity*, player*)>::operator()(player_activity*, player*) const
    ??:?
    activity_type::call_finish(player_activity*, player*) const
    ??:?
    player_activity::do_turn(player&)
    ??:?
    game::process_activity()
    ??:?
    game::do_turn()
    ??:?
    main
    ??:?
    ??
    ??:0
    _start
    ??:?
Aborted (core dumped)

Additional information:
OS: Ubuntu 20.10 64 bit
Processor: Inter Core i5-10500 @ 3.10GHz (12 cores)
Graphics: Mesa Intel UHD Graphics 630
240GB SSD

EDIT - After reopening the game and reloading the save, i found my character repairing the item and completing the procedure without further crashes. I lost 0 progress whatsoever.

**Comment by Anaglyphic** [comment]
Hi GamerKilroy.

Yes it is, and thanks for caring enough to report.

As you know, reloading the last save and letting it finish, it'll probably finish w/o a segfault 95% of the time, but then there's those pesky 5% of times it will crash. But if you play cdda you will occasionally see these. Without bughunting I've seen 10 0r 12 just playing.

So yea. Welcome to cdda! :wrench: definitely a WIP. You can leave it open if you want, but these segfaults are well-known.

You're a linux person, although ubuntu so that doesn't necessarily mean you're technical just means you're anti-microsoft. ha.

So don't be offended if you _are_ technical I'm not talking down to you - just being thorough. The game can end up in 'paradox' states at times where two things are both impossible to coincide and yet happening, the code in a sense freaks out because math is code and code is absolute unless told otherwise, and aborts.

In this case "_item:ammo required_" was likely for your sewing kit; you both need more thread and "_repair_item_finish_" you're done repairing... those are in-conflict. _bzzt!_ short circuit! and the game pukes. You reloaded, and this time the RNG rolled less repair failures so you had enough thread, and there's no paradox, your task was completed as it should. The next time there might be more failures and you run out before the exact 100% point, and it tells you your sewing kit is out of charges, but again, no segfault. It's only that very rare instance where two things end up true that shouldn't be that we get into trouble.

There's a lot of these strewn all over the code. It's not very robust at the moment and there's no overall error handler to catch exceptions. It's more about extending the game than making the code solid, but that's FOSS development in a nutshell - people will work on what they want, whenever they want. Unless there's a bounty on something? You get what you get.

Hope that helps. Don't let it discourage you from playing, you can play 10 hours a day and never see another one for months, or you could run into another one before you read this. It's the luck of the draw as it were. But unless it happens during a savegame write, it won't hurt your world or your character, just reload.

**Comment by GamerKilroy** [comment]
Hello.

I am very new to CDDA and i'm loving it thus far, even if i had a few
exceptions pop up here and there.

I am a fullstack dev myself so i am not worried, it is early development
and mostly experimental right now so exceptions are pretty much a garantee.

I thought i'd report this as it is my first time the program just straight
up stopped execution.

I'm looking to get more knowledge about the game in general (for instance,
i never made a vehicle nor used mutations or bionics) and if it keeps me
interested, i'll try and contribute in my spare time.

Kind regards,
- GamerKilroy
