### ISSUE TITLE
The "Flammable Arrow" recipe is absolute nonsense.

### ISSUE THREAD

**Issue by SpadeDraco** [CleverRaven/Cataclysm-DDA#49206]
# Describe the bug

The recipe for flammable arrows calls for 5 random arrows of any type despite producing what appears to be a single, flammable bodkin arrow.

# Steps To Reproduce
1. Open the crafting menu
2. Look up the recipe for flammable arrow
3. Marvel at the fact that you're apparently shooting a giant bundle of random arrows

# Expected behavior

Flammable arrows require a single bodkin arrow to craft, reflect bodkin arrow damage on hit, and produce the same number of bodkin arrows used in the recipe.

# Screenshots
![Flam arrow](https://user-images.githubusercontent.com/61074201/120942192-e6b2ef80-c6ec-11eb-9d72-ab5af9bde796.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 6b9918a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Rail Stations [No_Rail_Stations],
    Useful Helicopters [useful_helicopters]

# Additional context

None

**Comment by eJ0opb** [comment]
Aha ha... actually, it's even worse.  See #40763, which was closed for having similar symptoms to #40761, even though the underlying cause (and therefore fix) is actually different.  TLDR; "flammable arrows" are actually a tool with 5 charges, each one producing a "flaming arrow".  For whatever reason the charges aren't displayed anymore but they're still there.  The easiest "fix" is probably to turn it into a tool with only one charge (and make the recipe only require one arrow).  Tangentially related, flammable arrows don't fit in quivers; might as well fix at the same time if anyone is interesting in fixing this.

**Comment by Anaglyphic** [comment]
:rage4: Love it, helicopter man.

As eJ0opb points out it's just the surface of it. We have to assume some of this is accidental, a holdover from the "olden days" when this was likely the "cost" for making a flaming arrow? Some of it may have been a limitation of the previous method; now that you can transform the arrow part of a flammable could take on the stats of each arrow it was made from.

The 5-for-1 thing could have been a huge weight/volume exploit; since you get back all components when you disassemble, assuming prior you couldn't disassemble it. I know someone is grinning thinking, _"what a great way to carry free weight fuel and rags, and 4x arrows until it's fixed!"_  Oh except it isn't. Because you can't carry but so many. 

Even worse now that we have the pockets system, again it's likely just an oversight, but the volume/length/weight thing WRT flammable arrows won't fit in anything but a golf bag (or rope) including quivers or large quivers. Like explosive arrows. Also this is kind of funny, but since your skill improves while you are constructing them, they can't stack. Every-so-many you'll increase, and therefore value/changes... for example the same flammable arrow built from the exact same aluminium broadheads lamp oil and rags, are valued $28/35/42 with a barter value of 0.08/0.10/0.12... laying on the ground, of course, since I didn't think to spawn a golf bag.

**Comment by actual-nh** [comment]
Ping: @ZhilkinSerg?
