### ISSUE TITLE
[UI] Give players an immediate and more noticeable way to tell if they're controlling a vehicle. Such as changing or inverting the color of the sidebar.

### ISSUE THREAD

**Issue by ifffrt** [CleverRaven/Cataclysm-DDA#49224]
# Is your feature request related to a problem? Please describe.
It's currently very hard to tell at first glance whether your own character is controlling the vehicle or walking around just by looking at the screen. The reticule that comes up when controlling the vehicles is small, and sometimes can even blend in with the color of the background, and depending on zoom level might not even be visible. This have led to many, MANY "oopsies" moments where in the heat of the moment, instead of turning the gas pedal up to run from an enemy, I opened the door and let them in to kill me, or walked right into them instead. 

# Describe the solution you'd like
I have 3 possible solutions:
1) Changing the color of a section of the side bar that's large and hard to ignore. Examples: Giving the minimap a gray background instead of black, or give the entire sidebar an outline that only appears when "vehicle steering mode" is on.
2) Change the background color of the sidebar when driving a vehicle.
3) Invert the colors of the sidebar when driving a vehicle.

# Describe alternatives you've considered
An animated vehicle reticule that's harder to ignore. But that one would be tileset dependent.

# Additional context

**Comment by Paperbell** [comment]
Maybe the reticule could be animated by going from your character and stepping to the normal maximum range if you are standing still?

**Comment by Zireael07** [comment]
@Paperbell: That would be very confusing.

At the very minimum, the reticule shouldn't be white but some other color, yellow or red.

**Comment by Anaglyphic** [comment]
Hi.

Not to _"did you plug it in?"_ troubleshooting 101 you, but did you ever press **}** and look at how you can customize your sidebar? There is an entry for **vehicle**, turn it on and move it's position with **s** to wherever you want it. Then at-a-glance to your sidebar, say just coming back to a savegame, it's immediately obvious you're in a vehicle, if it's in motion and at what speed, forward or reverse, what compass heading you're facing, how much fuel is left, and what your speed/cruise control is set at. It's a blank line when you're not in a vehicle.

**Comment by ifffrt** [comment]
> 
> 
> Hi.
> 
> Not to _"did you plug it in?"_ troubleshooting 101 you, but did you ever press **}** and look at how you can customize your sidebar? There is an entry for **vehicle**, turn it on and move it's position with **s** to wherever you want it. Then at-a-glance to your sidebar, say just coming back to a savegame, it's immediately obvious you're in a vehicle, if it's in motion and at what speed, forward or reverse, what compass heading you're facing, how much fuel is left, and what your speed/cruise control is set at. It's a blank line when you're not in a vehicle.

Yeah I know about that. But what I really needed is an indicator of whether you're steering the vehicle or not, not whether you're inside the vehicle or outside. In the current scheme you can't tell at all if pressing up will make you walk forward (with your feet) or increase vehicle speed, because the vehicle indicator turns on whenever you're inside a vehicle tile itself, not just when you're controlling it. 

Besides, the vehicle indicator is still way too small for my liking. Even if it tells me whether I'm walking or driving at a glance I'd still be liable to glancing over it while in stressful game moments.

**Comment by Anaglyphic** [comment]
Hmm. Yes, _yes_ it does and _yes_ you can. Hey you're lying to me, aren't you? ^.^ Because if you tried it you'd know it does exactly what I said it does, exactly what you're seeking. I _promise_ it provides usable information, the exact information you're requesting. Please give it a try. You can easily tell you're going to move the car, or move your feet, it's in plain text right there... if it says:

`E../F 180°  -32 < -32 mph`

Then _I know_ I've got plenty of fuel, I'm going backwards at a pretty good clip, my current speed is matching my set throttle speed, and pressing 5 or . I'll move 32/4=8 tiles backwards from the compass heading of 180°, so I'll back up straight north, 8 tiles each move, until I turn or hit something or change my speed.

Pressing Up should NOT move the vehicle unless it's already underway. You're thinking like a Windows person. Passing the turn with 5 or . is how you move the vehicle. Up and Down are just throttle controls. Repeatedly tapping Up to move forward is just going to make you crash. Might be fun though.

In your supposed scenario of "not knowing", it's just lack of basic information - if you are at the controls and the speeds are 0 < 0 mph it'll be pretty obvious if the car is started by looking at the controls or the exhaust pipe. And if it's not 0? I guess you're driving!

I get that you might want something different, so you'll argue with whatever I say, you want a white or red flashing box indicator for the movement cursor, maybe the movement speed at the "steering wheel" target, and a bigger one at that, maybe some symbols that can approximate arrows for direction indicators, whatever. Keep in mind what you want might not be possible beyond a certain point. _(pd/ncurses A_ALTCHARSET does not have those, just the menu bars drawing stuff, remember this is a text game even though you're playing it with graphic tile replacements. It has to be universally switched to UTF8/16 ncurses first.)_
