### ISSUE TITLE
Dumb dialogue

### ISSUE THREAD

**Issue by big-smitty** [CleverRaven/Cataclysm-DDA#49276]
# Describe the bug
A lot of the dialogue sounds dumb. One example in the screenshot below but you can find plenty more examples. 
I know it's a low priority item considering 0.f, but I wanted to put this out there in case anyone wanted to take a crack at it.
A guide to adding/changing dialogue is [located here](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/NPCs.md) in case you are a new contributor. I would work on it but I frankly don't have time right now.

# Expected Changes:
Clean up mission/NPC generic dialogue so it doesn't sound like children talking.

# Screenshots
Why include "I don't know what to say" part? That should be removed. 
There are plenty more instances like this where the flavor is broken by dumb dialogue.
![image](https://user-images.githubusercontent.com/85451361/121788999-f320c780-cb86-11eb-9be3-cdb6c99d5dc2.png)

**Comment by Leland** [comment]
Hey @big-smitty, unfortunately, dialog being "dumb" isn't a quantifiable thing – this issue doesn't have a visible way to be _closed_. I'll close this for now (since rewriting dialog will be an ongoing process) but PRs are welcome if you get time in the future to shape those lines to your liking!

As an aside, every line of text in this game was created by a contributor, so I'd recommend being a little more considerate when it comes to opening issues 😊
