### ISSUE TITLE
discrepancy between the ballistic protection of reinforced glass walls and doors

### ISSUE THREAD

**Issue by connorpmartin** [CleverRaven/Cataclysm-DDA#49271]
# Describe the bug

Reinforced glass doors fail to stop bullets, even when shut.

# Steps To Reproduce

Spawn a turret and stand on the other side of 1+ layers of reinforced glass door.
Get shot for full damage.

# Expected behavior

Reinforced glass doors should have similar bullet-stopping behavior to reinforced glass in general.

# Screenshots

![image](https://user-images.githubusercontent.com/55263157/121781646-cc0cca80-cb73-11eb-94b5-342f839cd819.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.E-10134-g9b256f6 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Arcana and Magic Items [Arcana],
    Blaze Industries [blazeindustries],
    Alternative Map Key [alt_map_key],
    Beta National Guard Camp [national_guard_camp_alt],
    No Rail Stations [No_Rail_Stations]
]

**Comment by Theawesomeboophis** [comment]
What are reinforced glass doors based off of? Are they supposed to be bulletproof or just bullet-resistant, because bullet resistance does not mean bulletproof, as bullet-resistant glass can still be broken if shot at many times. It depends on what reinforced glass is based off of, how many panes, layers, etc. If it is meant to bulletproof, this is an error, if it is meant to bullet-resistant, it is most likely too weak.

**Comment by Anaglyphic** [comment]
Hi.

Correct Theawesomeboophis, he's confusing  _reinforced glass_ with ballistic glass. 
_"A large sheet of glass strengthened with steel wiring"_

Think instead of bullet-proof or even bullet-resistant, the stuff you see in school doors, that 5-8mm sheet float glass pre-stressed "safety" with a steel wire mesh inside. It's not meant to stop bullets, it's meant to stop intruders without tools.

IIRC regular non-thick sheet ballistic glass is rated 1-8 per layer, 1 being able to stop slow things like blades and small arms, 3 being able to take a .357 or 4 even Dirty Harry's .44, but beyond that? That's your ass. You think an automatic .556 turret isn't going to chew through lvl 6-7-8 regular ballistic plate in a single burst? You're wrong and also dead! :exploding_head: :boom: :gun: It's sure not going to be stopped by "reinforced glass", not reality not in-game. (As for high-power sniper fare .270/.308./.30-06 frequently go right through... the standard now is mluti-layer protection. There's no guarantee of safety other than not being there.

That's why in banks and places you see that multi-inch ballistic polycarbonate. It's not about stopping _all_ bullets, it's about stopping the first few so you can go _**oh shit!**_ and get down on the floor behind the hidden steel plating, which does stand up to (most) civilian-accessible armaments for an extended period.

So please just tell me you're complaining about being an easy kill for a turret and you don't want this "fixed" because the game is supposed to be difficult. You wanted to hide behind "reinforced glass" to sneak up closer without dying, but, well, it didn't work. You died. Learn from it. That's cdda in a nutshell. How many actual things are indestructible, where you can stand with impunity and engage endless hordes? Nothing. You are not safe, anywhere, ever. Not even solid rock.

This is likely a \#wontfix but maybe someone wants to extend the types of glass to have more ballistic construction options?

**Comment by Theawesomeboophis** [comment]
> Hi.
> 
> Correct Theawesomeboophis, he's confusing _reinforced glass_ with ballistic glass.
> _"A large sheet of glass strengthened with steel wiring"_
> 
> Think instead of bullet-proof or even bullet-resistant, the stuff you see in school doors, that 5-8mm sheet float glass pre-stressed "safety" with a steel wire mesh inside. It's not meant to stop bullets, it's meant to stop intruders without tools.
> 
> IIRC regular non-thick sheet ballistic glass is rated 1-8 per layer, 1 being able to stop slow things like blades and small arms, 3 being able to take a .357 or 4 even Dirty Harry's .44, but beyond that? That's your ass. You think an automatic .556 turret isn't going to chew through lvl 6-7-8 regular ballistic plate in a single burst? You're wrong and also dead!    It's sure not going to be stopped by "reinforced glass", not reality not in-game. (As for high-power sniper fare .270/.308./.30-06 frequently go right through... the standard now is mluti-layer protection. There's no guarantee of safety other than not being there.
> 
> That's why in banks and places you see that multi-inch ballistic polycarbonate. It's not about stopping _all_ bullets, it's about stopping the first few so you can go _**oh shit!**_ and get down on the floor behind the hidden steel plating, which does stand up to (most) civilian-accessible armaments for an extended period.
> 
> So please just tell me you're complaining about being an easy kill for a turret and you don't want this "fixed" because the game is supposed to be difficult. You wanted to hide behind "reinforced glass" to sneak up closer without dying, but, well, it didn't work. You died. Learn from it. That's cdda in a nutshell. How many actual things are indestructible, where you can stand with impunity and engage endless hordes? Nothing. You are not safe, anywhere, ever. Not even solid rock.
> 
> This is likely a #wontfix but maybe someone wants to extend the types of glass to have more ballistic construction options?

If reinforced glass is reinforced with steel wire as in the description, it should be bullet-resistant and not bulletproof if I'm correct, it seems this is intended, but I might be wrong.

**Comment by connorpmartin** [comment]
The problem with the current state of reinforced glass doors is that they can be shot through easily while the surrounding reinforced glass walls cannot. My understanding from the change to reinforced glass is that they are intended to be bulletproof, which is why reinforced glass walls currently reflect small arms fire, seriously slow .223, and do basically nothing to higher power rounds. Reinforced glass doors currently entirely fail to slow .223.

For reference, getting shot with .223 by a security bot through a reinforced glass wall deals roughly 10-20 damage.

If you feel that the current state of reinforced glass is inaccurate, then it would be a good idea to change that. The issue is that there's a pretty heavy discrepancy between the bullet-stopping ability of reinforced glass doors and walls which makes no sense.

**Comment by Anaglyphic** [comment]
Well, it's a game, depends on how reality you want to be, but I can tell you from personal knowledge it won't even stop a 9mm handgun from 20' away from passing though and striking an unarmoured target behind it. You'd be better off crouched down and let the wood absorb the kinetic energy than the glass, you'll just get glass bits in your face to go with the bullet. The 2nd and successive rounds are not slowed at all, since the glass shatters on any impact.

**Comment by Anaglyphic** [comment]
no dude, see it's your _perception_ that's at issue here... the glass clearly states it's reinforced glass; and the description I pasted is the one from on-screen and in the JSON... no where does it say it's intended to stop or mitigate any ballistics.

**Comment by Theawesomeboophis** [comment]
> The problem with the current state of reinforced glass doors is that they can be shot through easily while the surrounding reinforced glass walls cannot. My understanding from the change to reinforced glass is that they are intended to be bulletproof, which is why reinforced glass walls currently reflect small arms fire, seriously slow .223, and do basically nothing to higher power rounds. Reinforced glass doors currently entirely fail to slow .223.
> 
> For reference, getting shot with .223 by a security bot through a reinforced glass wall deals roughly 10-20 damage.
> 
> If you feel that the current state of reinforced glass is inaccurate, then it would be a good idea to change that. The issue is that there's a pretty heavy discrepancy between the bullet-stopping ability of reinforced glass doors and walls which makes no sense.

If they are meant to be bulletproof, this is definitely a bug, thanks for defining the issue in detail.

**Comment by connorpmartin** [comment]
Then I would recommend opening a pull request to decrease the bullet-stopping ability of reinforced glass walls. Right now, it deflects small arms fire and almost negates .223.

**Comment by Theawesomeboophis** [comment]
Please, let's not turn this into an argument, that was not my intention, I was merely wondering what reinforced glass was meant to be, it was more of a question than anything else.

**Comment by Theawesomeboophis** [comment]
It seems that this is a problem with contradictions of how reinforced glass is used, with walls being bulletproof and doors not so.

**Comment by Theawesomeboophis** [comment]
Reinforced glass ( AKA Safety Glass) is not completely bulletproof, but is somewhat bullet-resistant according to the sources I've found, and is also fire-proof, so I believe lowering the bullet resistance of the walls is the best option, as currently, as the OP stated, they are effectively bulletproof, which is not the case in the real world.

**Comment by Anaglyphic** [comment]
Oh dude not an argument, I hope! At least not on my part - I just want to query where people stand on this. If you're willing to defend an idea, then you care, right? But no, it's a game we all love! And it's open source, so we kind of all get some say in it, right? It's not likely to have 10M sales, well, installs, in 2021 is it? I'd fall over dead at 10k active players, I think. 

re: what the glass does at it stands, it's I guess both, actually. Throw a grenade at it... hell, on it... it doesn't do anything. Those "containment pens" on lab lower levels? You can throw 5... that poor turret is toast, but the glass? Unscathed. That's nuts, you'd cause structural damage to the framework even if you didn't break it entirely.  As for one caliber being stopped and another getting through, that shouldn't happen - everything has a durability - you exceed that, it breaks. Doesn't matter if it's a solid rock wall. You can't just shrug off hits unless it's a hardness thing. You bash on a steel door with your wood staff, you're just damaging your staff.

Another issue is, well it's a game - it's not really emulating ballistics. fire your AI .50BMG and it goes right through just about everything, both sides of the reinforced glass, through the wall behind it, shatters a door, and collapses the staircase it hits, as if it was some magical round. Cause, well, game. Ballistic glass usually does poorly on something that large without a penetrator or an AP sleeve... being designed to spread that energy out to stop it from getting through. The physics behind it are fantastic, I mean holy hell it's clear, so clear you can read through it!

This is where we get into the "gameplay vs reality" stuff again. It's everywhere. The people who do the caloric density of food, down to the vitamin load, they'll eventually put in all 9 essential aminos and the 4 pseudo necessary ones, and we'll have a CDDA dietician to deal with... but I don't think these things exist as-it-is for two reasons:

1) again, it's a game. You learn what a game construct can and can't do, depending on your setup, loadout, and probably mods - I mean look at the OPs mod list, he's usuing non-standard mods. There's hundreds of them, I think the GMC is up to 400-ish, right?... the "they" may or may not want ballistic glass, but in the scheme of things trying to hit 0.F maybe this will get back-burnered. But it wouldn't be hard to implement just cloning entries in the JSON, both for a realistic ballistic glass, as well as cdda ones reinforced chitin or transparent superalloy or whatever, cause, yea, game!

2) Devil's Advocate - do you actually want to see ballistic glass? Do you think it would make the game more fun? Or do you think it would be exploited, overused, ruin any attempt at playbalance? Because again, nothing should be safe, ever. It's not that game. You're supposed to feel vulnerable from day 1 to day 2501, even with stats kills & stats skills enabled and you're up to 99/99/99/99, you should still not go to sleep with earplugs in, right? This is a separate issue, but a very important one.

**Comment by actual-nh** [comment]
Glass walls are thicker than glass doors/windows.

**Comment by Theawesomeboophis** [comment]
> Oh dude not an argument, I hope! At least not on my part - I just want to query where people stand on this. If you're willing to defend an idea, then you care, right? But no, it's a game we all love! And it's open source, so we kind of all get some say in it, right? It's not likely to have 10M sales, well, installs, in 2021 is it? I'd fall over dead at 10k active players, I think.
> 
> re: what the glass does at it stands, it's I guess both, actually. Throw a grenade at it... hell, on it... it doesn't do anything. Those "containment pens" on lab lower levels? You can throw 5... that poor turret is toast, but the glass? Unscathed. That's nuts, you'd cause structural damage to the framework even if you didn't break it entirely. As for one caliber being stopped and another getting through, that shouldn't happen - everything has a durability - you exceed that, it breaks. Doesn't matter if it's a solid rock wall. You can't just shrug off hits unless it's a hardness thing. You bash on a steel door with your wood staff, you're just damaging your staff.
> 
> Another issue is, well it's a game - it's not really emulating ballistics. fire your AI .50BMG and it goes right through just about everything, both sides of the reinforced glass, through the wall behind it, shatters a door, and collapses the staircase it hits, as if it was some magical round. Cause, well, game. Ballistic glass usually does poorly on something that large without a penetrator or an AP sleeve... being designed to spread that energy out to stop it from getting through. The physics behind it are fantastic, I mean holy hell it's clear, so clear you can read through it!
> 
> This is where we get into the "gameplay vs reality" stuff again. It's everywhere. The people who do the caloric density of food, down to the vitamin load, they'll eventually put in all 9 essential aminos and the 4 pseudo necessary ones, and we'll have a CDDA dietician to deal with... but I don't think these things exist as-it-is for two reasons:
> 
> 1. again, it's a game. You learn what a game construct can and can't do, depending on your setup, loadout, and probably mods - I mean look at the OPs mod list, he's usuing non-standard mods. There's hundreds of them, I think the GMC is up to 400-ish, right?... the "they" may or may not want ballistic glass, but in the scheme of things trying to hit 0.F maybe this will get back-burnered. But it wouldn't be hard to implement just cloning entries in the JSON, both for a realistic ballistic glass, as well as cdda ones reinforced chitin or transparent superalloy or whatever, cause, yea, game!
> 2. Devil's Advocate - do you actually want to see ballistic glass? Do you think it would make the game more fun? Or do you think it would be exploited, overused, ruin any attempt at playbalance? Because again, nothing should be safe, ever. It's not that game. You're supposed to feel vulnerable from day 1 to day 2501, even with stats kills & stats skills enabled and you're up to 99/99/99/99, you should still not go to sleep with earplugs in, right? This is a separate issue, but a very important one.

Okay, I was not sure you're intentions, I am glad to know it was not argumentive and merely constructive, I believe ballistic glass, if done right, could be useful but not game-breakingly strong, if it were to be implemented, it should probably be rare, I am glad to know people care about this game as much as I do, and I appreciate that ( unlike other fandoms), we can have civilized discussions about things, it is one of the reasons I began playing cataclysm is because of the community.

**Comment by Theawesomeboophis** [comment]
> Glass walls are thicker than glass doors/windows.

Yes, but as stated in the wikipedia article: "Wired glass, as it is typically described, does not perform the function most individuals associate with it. The presence of the wire mesh appears to be a strengthening component, as it is metallic, and conjures up the idea of rebar in reinforced concrete or other such examples. Despite this belief, wired glass is actually weaker than unwired glass due to the incursions of the wire into the structure of the glass. Wired glass often may cause heightened injury in comparison to unwired glass, as the wire amplifies the irregularity of any fractures. This has led to a decline in its use institutionally, particularly in schools."

**Comment by Maleclypse** [comment]
This may be useful to someone in this discussion.   I don't know who. I didn't read it all above.   #48449

But we regularly see discussions on the glass doors, windows and walls.   I think science rooms that would be experiment/subject holding rooms should have ballistic glass, science rooms with a computer but no other equipment should at best have reinforced wire glass and cafeteria rooms should have normal glass.  But labs are drawn in C++ currently so I don't have a desire to fight with that or fight anyone who thinks that setup should be different.

**Comment by faefux** [comment]
> Oh dude not an argument, I hope! At least not on my part - I just want to query where people stand on this. If you're willing to defend an idea, then you care, right? But no, it's a game we all love! And it's open source, so we kind of all get some say in it, right? It's not likely to have 10M sales, well, installs, in 2021 is it? I'd fall over dead at 10k active players, I think.
> 
> re: what the glass does at it stands, it's I guess both, actually. Throw a grenade at it... hell, on it... it doesn't do anything. Those "containment pens" on lab lower levels? You can throw 5... that poor turret is toast, but the glass? Unscathed. That's nuts, you'd cause structural damage to the framework even if you didn't break it entirely. As for one caliber being stopped and another getting through, that shouldn't happen - everything has a durability - you exceed that, it breaks. Doesn't matter if it's a solid rock wall. You can't just shrug off hits unless it's a hardness thing. You bash on a steel door with your wood staff, you're just damaging your staff.
> 
> Another issue is, well it's a game - it's not really emulating ballistics. fire your AI .50BMG and it goes right through just about everything, both sides of the reinforced glass, through the wall behind it, shatters a door, and collapses the staircase it hits, as if it was some magical round. Cause, well, game. Ballistic glass usually does poorly on something that large without a penetrator or an AP sleeve... being designed to spread that energy out to stop it from getting through. The physics behind it are fantastic, I mean holy hell it's clear, so clear you can read through it!
> 
> This is where we get into the "gameplay vs reality" stuff again. It's everywhere. The people who do the caloric density of food, down to the vitamin load, they'll eventually put in all 9 essential aminos and the 4 pseudo necessary ones, and we'll have a CDDA dietician to deal with... but I don't think these things exist as-it-is for two reasons:
> 
> 1. again, it's a game. You learn what a game construct can and can't do, depending on your setup, loadout, and probably mods - I mean look at the OPs mod list, he's usuing non-standard mods. There's hundreds of them, I think the GMC is up to 400-ish, right?... the "they" may or may not want ballistic glass, but in the scheme of things trying to hit 0.F maybe this will get back-burnered. But it wouldn't be hard to implement just cloning entries in the JSON, both for a realistic ballistic glass, as well as cdda ones reinforced chitin or transparent superalloy or whatever, cause, yea, game!
> 2. Devil's Advocate - do you actually want to see ballistic glass? Do you think it would make the game more fun? Or do you think it would be exploited, overused, ruin any attempt at playbalance? 

I just wanted to make the small but important point this is a non issue. Is a 1player game. If someone wants to exploit some items to cheese there way through the game that isn't a problem and should have little affect on development because such players are consciously ruining the game for themselves only, that is there choice.
