### ISSUE TITLE
Tearing down a curtain on an open window closes it.  Again.

### ISSUE THREAD

**Issue by chrispikula** [CleverRaven/Cataclysm-DDA#49301]
# Describe the bug

If you open a window with a curtain, then tear it down, the window is instantly closed.

# Steps To Reproduce

Open a curtain, open the window, tear down the curtain.

# Expected behavior
The window should remain open.

Either that, or we've got some strange windows where the curtain is mounted to the glass, and then the window closing sound should be incorporated into tearing down the curtain if the window is open.

Time isn't a concern at the moment, as open/closing windows is around 1 second. Tearing down the curtain is around 10 seconds.

# Versions and configuration

2021-06-14-1420
Windows 10, tiles

# Additional context

I reported this issue a while ago with #47834
It was fixed in #47837 , found to be a bad fix in #48175 , supposed to be fixed by #47629 , 
It is currently not fixed.

**Comment by ama0** [comment]
That is because #48323 reverted the json fix from #47629. I don't have time right now to fix it.
The fix is reverting this change. I left a comment in `data/json/furniture_and_terrain/terrain-windows.json`
* https://github.com/CleverRaven/Cataclysm-DDA/pull/48323/files#r651375529

I never used the comment feature in files, I just hope it works and you can see what I mean

-----

In case it doesn't:

`"curtain_transform"` should be `"t_window_no_curtains_open"` *not* `"t_window_no_curtains"`
https://github.com/CleverRaven/Cataclysm-DDA/blob/c9cff198c72028ad8e6431bc48be5b9d03efb462/data/json/furniture_and_terrain/terrain-windows.json#L238
