### ISSUE TITLE
Error when NPC is trying to do menial labor

### ISSUE THREAD

**Issue by scraw-darkblade** [CleverRaven/Cataclysm-DDA#49363]
S: Win10
Version: 7fa964e (Tiles)
[Bug - Issue - 49363.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6682486/Bug.-.Issue.-.49363.zip)

Steps to reproduce:
1. You should have a faction camp
2. Ask NPC to do menial labor
3. An error screen will pop up (see below)
4. NPC will not sort things (or at least partially - not verified)
5. NPC will sleep and tell you that there was an error.

Expected behavior
It will run smoothly sorting things without any problems at all.

Additional Notes:
DEBUG    : NPC Florencio Ruff entered infinite loop.  Turning on debug mode

 FUNCTION : void game::monmove()
 FILE     : src/game.cpp
 LINE     : 4664

**Comment by scraw-darkblade** [comment]
Updated - Upload the save file - (Bug - Issue - 49363.zip)

**Comment by ProfoundDarkness** [comment]
So out of curiosity I tried to see if we were having a similar problem...

Firstly on Linux 64 compiled version 0.F-2315-g8bab31e686 I was able to replicate this issue by stepping over to the npc (near the water directly west) then talking to the NPC and waking them up, then telling them to sort out the loot.  Didn't have to wait long for the error.

Next up I checked the NPC's health, no broken legs...  Their encumbrance wasn't very high on the legs either.  Still, I told the NPC to take off their pants, they dropped them on the ground.  They were able to sort the loot out successfully after that.

... Makes me wonder if the actual issue is that encumbrance of the legs on NPCs breaks some of their activities...  I'll link to my recent issue though I'm not sure if they are ACTUALLY related.  If nothing else additional data points to avoid/create the error...  #51394

**Comment by ProfoundDarkness** [comment]
Since I'm curious to explore the NPC code path a bit further, via debug, going to try tracing through and see what I pick up... who knows I might end up with confidence through understanding enough to try something crazy...

Telling the NPC to sort out loot, starting from...
https://github.com/CleverRaven/Cataclysm-DDA/blob/0ab1dd9ba8baa8c66d4f7351ea9c64f198479889/src/do_turn.cpp#L710

attitude is 'NPC_ACTIVITY' to start.  Activity is 'ACT_MOVE_LOOT' Logically no target creature and danger is 0.  Execution arrives in npc::move() at the segment which handles activity assignment.  no stashed activity.  NPC executes a relocation... curiously NPC has 550583 pre-action moves and 550389 post action moves...  That seems like a LOT of moves (comparing with my trace of an NPC with broken leg in combat of 70).

next loop into npc::move()
activity_route[0] = 52-68-0
Destination activity 'ACT_MOVE_LOOT'
enter start_destination_activity()
action set to npc_player_activity (moveloot)
npc::execute_action() -> npc::do_player_activity() 
Activity is NOT multi_type (I think)
into activity.do_turn(), not travel_activity, using legacy call_do_turn.  Wasn't able to examine
that flow in debugger so don't know if it did much, though it certainly didn't change moves.
... strangely not seeing moves change in this section.
https://github.com/CleverRaven/Cataclysm-DDA/blob/142b56a492506ac98682d56f6c0c638efd63f6d5/src/npcmove.cpp#L3305-L3310

I'm at a loss to take my examination further.  My gut says that number of moves on the NPC is the problem, that they shouldn't have so many moves (ie currently in an invalid state).  From the context of the save I'd bet the NPC was doing work near the edge of the reality bubble.  If such a high moves number is reasonable and the do_turn() (including 'legacy') code is apt then maybe a small tweak to the following code?  <shrug>
https://github.com/CleverRaven/Cataclysm-DDA/blob/142b56a492506ac98682d56f6c0c638efd63f6d5/src/npcmove.cpp#L3311-L3313

I don't think my issue and this one are related though I have only the barest inkling on this one.

Aside... NPCs can lead players around?  Neat.
