### ISSUE TITLE
Armor Penetration from martial arts doesn't work.

### ISSUE THREAD

**Issue by Broken27** [CleverRaven/Cataclysm-DDA#49485]
# Describe the bug

Armor Penetration from martial arts doesn't work.

# Steps To Reproduce

Use a martial art+stats than should give you extremely high armor penetration.

(For my tests, i used a modified version of bionic combatives than gives armorpen equal to 100% of perception, and 50 perception). (I tested it with unmodded Niten and 60 Perception as well).

Summon a high armor monster, like a Kevlar hulk

Confirm than your attacks don't cause damage.

# Expected behavior

Martial arts should do what they say they do

# Screenshots

![image](https://user-images.githubusercontent.com/67008253/123657191-dfd15580-d830-11eb-8929-6b11c4deaa6e.png)

# Versions and configuration

Windows 10, using one of the latest experimental builds (3 weeks old or so)

# Additional context

I discovered this while modding and testing some martial arts of my own.

@Hymore246 you are probably interested on this

**Comment by Paperbell** [comment]
I'm also having this happen on an 8STR tiger style with strength scaling modified to be super high. The code and debug mastery phase strike shows that penetration for specific techniques is working, but I can't find anything in melee.cpp or martialarts.cpp that would increase penetration of all melee attacks due to a buff.
