### ISSUE TITLE
Turning on "gun trade names" does not affect some guns.

### ISSUE THREAD

**Issue by carmakazi** [CleverRaven/Cataclysm-DDA#49573]
# Describe the bug

After wondering if Generic Guns had slipped into my save somehow, I found out about the new menu option added somewhere in 0.F.  Switching it back, I found that it left some guns still in their "generic" state.  The ones I have found are:

-M16A4 is still "NATO Burst Rifle"
-Glock 21 is still "Glock Pistol"
-USP .45 is still "USP Pistol"
-1928A1 Thompson is still "Thompson SMG"

I would guess the issue is prevalent, as the only gun that I see correctly revert is the "NATO assault rifle."

# Steps To Reproduce

1. Start new save with "gun trade names" disabled.
2. Spawn yourself some of the affected guns, and a NATO assault rifle as a control.
3. Turn the option off through the menu.
4. See the "NATO assault rifle" revert to an M4 or something, but everything else stays the same.

# Expected behavior

All guns should return to their original names when the "Gun trade names" option is turned on.

# Screenshots
N/A
# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 6616372 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]

# Additional context

As an aside, all of the original guns that are affected by this change no longer appear in the debug spawning menu - only the generalized guns. This is regardless of whether Gun Trade Names is off or on.  I will make a separate issue for this if necessary, but it may be intentional I suppose.

**Comment by anothersimulacrum** [comment]
The items for those guns do not exist anymore, so only the generic version appears in the debug spawning menu, because randomly selecting a variant would make it impossible to find those guns. I guess duplicate entries could be added for all variants when variants are enabled, but I would rather the debug menu just have functionality to select a variant.

**Comment by anothersimulacrum** [comment]
Cannot reproduce. Went around collecting guns with variants, but when I turned the brand names option on, all of them had correct names.
![image](https://user-images.githubusercontent.com/42699974/124392432-6c08d000-dcaa-11eb-80d2-64cde79c8bbd.png)
![image](https://user-images.githubusercontent.com/42699974/124392438-762ace80-dcaa-11eb-963d-5c56a589803b.png)

**Comment by TheMurderUnicorn** [comment]
Just to add a little insight/confirmation, I am also experiencing this issue.  For me it is specifically shotguns that seem to be borked.  
![image](https://user-images.githubusercontent.com/41651793/125543133-b0ff5dcd-592d-4aa3-baca-0f78ae2d217f.png)
![image](https://user-images.githubusercontent.com/41651793/125543155-385d2f2d-3384-46e2-84da-0c221abacc3a.png)

**Comment by anothersimulacrum** [comment]
I believe the issue is that guns that were not explicitly migrated that came into being before variants do not have variants assigned.
e.g. any `sig552`s that existed before the variants did not get migrated to anything, and didn't have variants, so they're now always generic because they don't have the `sig552` variant assigned.
