### ISSUE TITLE
preserving offal and blood

### ISSUE THREAD

**Issue by robotic-gamer** [CleverRaven/Cataclysm-DDA#49672]
# Is your feature request related to a problem? Please describe.
lack of an easy way to preserve offal and blood
# Describe the solution you'd like
the ability to dry offal and blood like meat

# Describe alternatives you've considered
ability to salt blood or offal to make it last longer

**Comment by Aerotinge** [comment]
Do you have a reference of salt blood for preservation?
I was doing blood as food recipes and find no such a similar things.

**Comment by robotic-gamer** [comment]
I based using salt to preserve blood under the idea that high salinity preserves organic material from going bad by creating a poor environment for the bacteria involved.
 the only problem with blood is its high amount of water means you need more salt to preserve it or alternatively boil down the blood into sludge. 
I used the same logic to conclude that you can preserve offal by drying. 
Salting blood probably not in recipe books because it would not taste very good but that doesn't mean you can't do it.

**Comment by Aerotinge** [comment]
> the only problem with blood is its high amount of water means you need more salt to preserve it 

92% of the blood is composed of water. As a reference, 87% of the milk is composed of water.
And you'll need salt-water ratio 0.2:1* to slow it from spoiling significantly.
In CDDA, a portion of blood is 0.3 kg, which means you'll need 50+ portions of salt to preserve 1 blood.
As a reference, a salt water is only 1 portion of salt plus 1 water.
IRL people do not salt blood for reasons, not only because its bad taste nor refrigerators were yet invented. It's inedible.

> or alternatively boil down the blood into sludge.

Correct, this is a common cook recipe in most of cultures with blood as food.
But by drying, you'll leave a thin dark-red coating in the pot. I don't think it will work like milk powder though.

In modern times, the best way to preserve blood is to refrigerate.
Even so, blood added with appropriate industrial preservatives and kept refrigerated at 4 degrees Celsius will still decay in 2 months.

In CDDA, I could say the best way is to find a freezer or refrigerator. Or simply cook and consume it immediately.

**Comment by robotic-gamer** [comment]
@Aerotinge by boil it down to a sludge I meant boil down to a sludge then add salt to preserve.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
