### ISSUE TITLE
Standardize attack/damage messages

### ISSUE THREAD

**Issue by swwu** [CleverRaven/Cataclysm-DDA#4970]
Right now, attack and damage messages are fairly inconsistent. Some of the types:
- listing precisely the quantity of damage (player's melee and ranged attacks)
- listing the attack action, hit message, and missed message (melee attacks made against the player)
- listing the attack action only if it connects without providing a missed message, and omitting damage (player's mutation-based extra attacks, e.g. tentacle arms or horns, bionic attack augmentations)
- listing the attack being made, but not if it connects (turret/robot/NPC ranged attacks vs player)

The cause of this is that attack-related print() calls are more or less scattered all over the code without any kind of guiding principle.

Since I'm rewriting a lot of that code anyways, I'd like to suggest standardizing the way attack messages are done. Every attack can be three messages:
1. The attack is made (e.g. "You swing your sword at the zombie!", or "The robot fires its SMG at you!").
2. The damage dealt by the attack, or the fact that you missed, is reported (e.g. "You cut deeply into the zombie!", or "The robot's shot tears through you!", or "The cliff racer dodges your attack!").
3. Any additional effects, if any, are listed (e.g. "The zombie is stunned!", or "You're paralyzed with fear!").

This could theoretically be extended to _every_ attack, including all attacks in monattack, all martial arts techniques, all mutation-provided special attacks, "attacks" made by certain traps, etc etc.

I have this tagged as a "suggestion" but it's also worth pointing out that nobody else would need to do any extra work. I'm in the middle of rewriting a lot of the code that handles this stuff anyways, and this would be very easy to slot in.
##

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
