### ISSUE TITLE
Trying to hack an electronic gun safe causes a full cold CTD

### ISSUE THREAD

**Issue by Torres84f** [CleverRaven/Cataclysm-DDA#49746]
# Describe the bug

Trying to hack any and all electronic gun safes with my UPS converted electrohack causes a full CTD won't even deliver a crash log just drops the game to desktop

# Steps To Reproduce

1.- Load save provided
2- Try and hack the electronic gun safe in front of you
3.- Hope it's not just a problem on my end

# Expected behavior

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 335ab2a [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Graphical Overmap [Graphical_Overmap],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    DinoMod [DinoMod],
    Crazy Cataclysm [crazy_cataclysm],
    My Sweet Cataclysm [my_sweet_cataclysm],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Crazy Cataclysm - UndeadPeople Tileset [CrazyCataclysmUDP],
    DinoMod - UndeadPeople Tileset [DinoModUDP],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    My Sweet Cataclysm - UndeadPeople Tileset [My_Sweet_CataclysmUDP],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

SAVE HERE!!
[Unus Anus.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6786417/Unus.Anus.zip)

**Comment by Saicchi** [comment]
Can confirm on `0.F-480-g335ab2a05a [64-bit]`
I've even tried dropping the ups electrohack and spawning a new one and it still crashed. The crash log suggests the problem is somewhere in `hacking_activity_actor::finish(player_activity&, Character&)`

**Comment by GoLoT** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/mapdata.cpp#L414

This check assumes there is an examine actor defined for the tile type without null guards. When finishing a hack the game crashes because it tries to compare the type from a nullptr examine_actor with "cardreader".

Tested a quick fix changing that line to `return examine_actor && examine_actor->type == action;` and it allowed the hack to finish properly. I can't create a PR at the moment, if someone wants to make one feel free to do so. If not, I should be able to in a couple of hours.

Also, I don't know if this is uncovering a different underlying issue. Maybe there should always be a default examine actor that does nothing?
