### ISSUE TITLE
Error when installing CBM with installation data

### ISSUE THREAD

**Issue by AdamChirnside** [CleverRaven/Cataclysm-DDA#49752]
# Describe the bug

When installing a CBM with the relevant install data in the inventory, an error occurs.

# Steps To Reproduce

1. Make a character with a sterile CBM item and its install data item (for example, Power Storage).
2. Use an autodoc and choose to install said CBM.

# Expected behavior

# Screenshots

N/A

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 335ab2a [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    Disable NPC Needs [no_npc_food],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex],
    Alternative Map Key [alt_map_key],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    No Rail Stations [No_Rail_Stations]
]

# Additional context

 DEBUG    : Attempted a recipe with no available components!

 FUNCTION : comp_selection<item_comp> Character::select_item_component(const std::vector<item_comp>&, int, read_only_visitable&, bool, const std::function<bool(const item&)>&, bool)
 FILE     : src/crafting.cpp
 LINE     : 1570
 VERSION  : 335ab2a

**Comment by GoLoT** [comment]
Reproduced by trying to install a CBM on an NPC while carrying a CBM + AID item.

It looks like the code is trying to find the AID item checking the map (items around) and the inventory of the target of the CBM installation instead of the installer. Since the NPC is unable to find the AID item the game throws the error message.

Dropping the AID item to the ground allows the NPC to find the item.

Relevant code:
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/iexamine.cpp#L4846

It is checking the patient's inventory. patient->consume_charges() should be p->consume_charges().

I'll try to have a PR ready in a bit.
