### ISSUE TITLE
Nested maps with palettes aren't drawing wall terrain fully

### ISSUE THREAD

**Issue by curstwist** [CleverRaven/Cataclysm-DDA#49788]
# Describe the bug
Basement nested mapgen uses a lot of walls that surround the perimeter of the nested chunk.  They don't seem to be spawning, or only the first tile is being drawn.

# Steps To Reproduce
Spawn in a map.
Hop around some basements and look for nested chunks where the furniture doesn't seem to line up with the walls.

note: debug spawning the chunk will include the walls.
# Expected behavior
full nest placement.
`room_10x10_recording_studio_N` is a good example of a failing nested map chunk.  
The wall symbol "|" does override the same symbol in the palette it references in the nested map gen entry.

# Screenshots
Red circle is a tile of placed wall. the rest never spawned.
![image](https://user-images.githubusercontent.com/39442864/125142066-cf4c9500-e0e4-11eb-9591-d7347b3a0eeb.png)

# Versions and configuration
Newest build checked,  no mods or other changes.

**Comment by jbytheway** [comment]
I discovered the root cause of this issue while working on a related feature.

It's a side-effect of my changes in #48498.  I changed terrain to be placed in the same manner as everything else.  Whereas it used to be that all terrain was placed first, now terrain can be placed after nested mapgen happens, and override the terrain that was placed by the nest.  This will generally happen for all the tiles except the top-left tile because that's where the nest itself is hooked.

I have an idea for a fix.  Looking into it.
