### ISSUE TITLE
NPCs throw their items even when set to not use ranged weapons

### ISSUE THREAD

**Issue by Resok** [CleverRaven/Cataclysm-DDA#49834]
### Describe the bug

Currently NPCs are throwing their entire inventory including equipped weapons that are far better as actual melee weapons.

This includes things like radios, bats, bottles, just about everything I've seen.

### Steps To Reproduce

1. Spawn NPC and force them friendly through debug or other means
2. Tell NPC to not use ranged weapons
3. Engage in combat with zombies (any kind of hostile really)

### Expected behavior

NPCs should never throw away their best melee weapon at a bare minimum unless it's a last resort.
NPCs should not throw items in the first place unless they've been instructed to use ranged weaponry.

### Screenshots

![image](https://user-images.githubusercontent.com/5217673/125180206-3ed98780-e1ac-11eb-8cfe-ac33811fff52.png)

![image](https://user-images.githubusercontent.com/5217673/125180217-66c8eb00-e1ac-11eb-90fb-73e407e6766d.png)

### Versions and configuration

- OS: Windows
- Game Version: aa126fe
- Graphics version: Tiles
- Ingame language: English
- Mods loaded: DDA, Magiclysm

### Additional context

Savegame:

[Vine Hill - TEST.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6796184/Vine.Hill.-.TEST.zip)

**Comment by actual-nh** [comment]
Ping: @KorGgenT?

**Comment by GoLoT** [comment]
Likely related to #47562.
After a quick debugging session it looks like NPCs have a sequence of rules to decide the best available attack. It loops through all items available and evaluates each item for all possible kinds of attacks:
- Unarmed attack: It evaluates weapon efficiency against all enemies in unarmed attack range and keeps the best result.
- Melee attack: It evaluates the weapon efficiency agains all enemies in melee range and keeps the best result.
- Throw: It tests the efficiency if the item is thrown at any enemies in range and keeps the best result.
- Ranged: If ranged attacks are allowed, it evaluates the efficiency of shooting the weapon at targets in range and keeps the best result.

When no enemy is in range and ranged weapons are disallowed the NPC will never find a valid target for unarmed or melee attacks. Since throwing any item will always be better than doing nothing it always chooses to throw the most damaging one (highest DPS) because the alternative is always worse.

I'll have to dig a bit deeper but if I'm right there are two main issues:
- Items are thrown even if the effect will be pretty much useless. A cutoff has to be added. I guess a minimum effectiveness needed for throwing could work but that will probably block throwing rocks and other stuff that's supposed to be thrown.
- Melee attacks are never given an effectiveness as long as the enemies are not in melee range. This means that if a zombie is 2 tiles away, NPCs will never consider melee an option. This prevents NPCs from moving to try to attack the enemies, I think. The fix for this is to evaluate targets if they are out of range but with a penalty for having to move.

**Comment by actual-nh** [comment]
No errors, as in #49830?

**Comment by GoLoT** [comment]
No errores yet, at least with this save.
I see the other issue shows a ranged weapon in the NPC inventory and I'm assuming ranged attacks are enabled. It's possible that the error comes from the NPC deciding to throw the gun and somehow queuing a ranged attack with that weapon.

**Comment by KorGgenT** [comment]
i had put a limiter on the effectiveness rating result in order to limit this exact problem but obviously it's not enough. i'll have to look into this some more soon.

**Comment by actual-nh** [comment]
Perhaps either thrown things should count as ranged weapons for the limit, or it should be possible to tell them not to throw things (particularly melee weapons)?

**Comment by GoLoT** [comment]
Or the other way around. Add an NPC_THROWABLE flag to items so there is more control over what NPCs should think is a good throwing weapon.

Although it would be fun to see an NPC panic and throw a microwave, dishes and anything at hand to a Hulk.

**Comment by KorGgenT** [comment]
i could definitely see thrown weapons being considered ranged weapons for the purposes of the npc rules. i'd like to see if i can determine a more organic way for npcs to determine if a weapon should be thrown or not before resorting to a flag, though.

**Comment by Resok** [comment]
Not sure if it came across in the issue above but the NPCs are also currently ignoring all ranged attack related friendly line of sight rules as well. Thrown items/weapons/etc. are used regardless of if the player or other friendlies are directly in the path of the projectile (note the avoid message above in the screenshot).

Right now the NPCs also throw their weapons even in melee range when attacking with that weapon would clearly be superior. I don't think they're considering the whole throwing my weapon also means I won't have access to that weapon in the future problem either in the case of multiple enemies. Even if - hypothetically, I could kill one enemy at range with my only weapon (with 1 hit this is extremely unlikely due to how low most thrown weapon damage is, outside of grenades), it would mean I couldn't defend myself with it in melee range once other enemies closed on me. I think at the very least it should consider 'what is my best melee weapon AFTER I throw this going to be?' If it's about to be worse than what I have available now, don't throw it.

**Comment by Resok** [comment]
On a related note, one of my NPCs wearing a hard hat keeps removing it and throwing at the enemies also after throwing her ironshod staff at them... lol

**Comment by Resok** [comment]
They also don't appear to be throwing non-damaging entangling items like bolas, nets, etc. Guessing that's because the evaluation doesn't factor in the "TANGLE" flag as a value weight.

**Comment by Xomikadze** [comment]
I find it better to have a separate flag for the weapon suitable for throwing. You can throw anything you want, but it is the weapon designed for throwing that is already a special case. And if you need to add the ability to throw other items, then you can think over their value for the character. For example, stones will have a low value and the NPC will calmly throw them, and for example, a walkie-talkie will have a high value and it is not profitable to throw them yet. It is also naturally necessary to take into account the damage that will be done.

**Comment by actual-nh** [comment]
> Not sure if it came across in the issue above but the NPCs are also currently ignoring all ranged attack related friendly line of sight rules as well. Thrown items/weapons/etc. are used regardless of if the player or other friendlies are directly in the path of the projectile (note the avoid message above in the screenshot).

Well, that's a reason to do some uniting of thrown with (other) ranged weapons.

> Right now the NPCs also throw their weapons even in melee range when attacking with that weapon would clearly be superior.

This is when they're already in melee range (not using a reach weapon, I assume)? That's rather surprising.

**Comment by Resok** [comment]
> > Right now the NPCs also throw their weapons even in melee range when attacking with that weapon would clearly be superior.
> 
> This is when they're already in melee range (not using a reach weapon, I assume)? That's rather surprising.

Correct. While already in melee range with a Zombie I can talk to them, and give them a weapon to use - and they'll immediately throw it.

**Comment by tkulpa** [comment]
If this issue will stretch a bit longer maybe good idea would be to prevent npcs from even throwing stuff when ranged combat is prohibited, much easier quickfix

**Comment by GoLoT** [comment]
> If this issue will stretch a bit longer maybe good idea would be to prevent npcs from even throwing stuff when ranged combat is prohibited, much easier quickfix

That's implemented in #49907 along with some changes that should prevent NPCs from throwing wearable items (i.e. armor) and some other items they shouldn't be throwing. There will be issues still, but for the most part the problems should be fixed when it gets merged.
