### ISSUE TITLE
Do infinitely resurrecting zombies stretch suspension of disbelief? (make zombies take persistent damage)

### ISSUE THREAD

**Issue by Rivet-the-Zombie** [CleverRaven/Cataclysm-DDA#4992]
As has been pointed out on the forums, zombies getting back up after being 'killed' is cool, but the fact that they can do so endlessly seems rather silly. After all, eventually they'd just be a pile of goo and shattered bones, right?

One very simple solution I can see would be to make it so each time a zombie resurrects itself after being defeated, it loses something like 10-25% of its base maximum HP permanently. So eventually it will be 'pulped' in one hit and stay down for good, or else reach a point where its body is too badly damaged to ever stand back up again. An additional layer to this would be if, once they reach that point, they resurrect as something like a 'mangled zombie' with reduced stats overall that continues to degrade each time until it can no longer resurrect.

Anybody else have an opinion on this?
##

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
