### ISSUE TITLE
Vehicles in ASCII mode drawn incorrectly when facing northwest

### ISSUE THREAD

**Issue by Marrim** [CleverRaven/Cataclysm-DDA#49992]
### Describe the bug

Certain pseudographic symbols look flipped 90 degrees when a vehicle is facing northwest.
All other directions work fine. This happens with both default and custom vehicles. Screenshots attached.

### Steps To Reproduce

Spawn a default "Car" vehicle, drive it, face north and start turning left in small angles, you'll see it.

### Expected behavior

Expecting `┌──┐` instead of `└││┌`.

### Screenshots

![car-angles](https://user-images.githubusercontent.com/11006744/126021190-8d3e6ad8-d8c9-469c-8c86-ce294bd09b89.png)
![default-car](https://user-images.githubusercontent.com/11006744/126021198-e2194cfd-6bcb-4241-87a7-924133b437a9.png)

### Versions and configuration

Terminal, Ubuntu 18.04.
Reproduces in stable 0.F and experimental (9658f3d from main menu).
Default mods + StatsThroughKills.

### Additional context
Not much familiar with the game code, but my educated guess would be a rounding error or the case of `>=` instead of `>`. This particular direction is a little more north than west, yet the symbols look as if it's more west than north.

**Comment by actual-nh** [comment]
Confirmed by @definitelynotklip on Discord.

**Comment by definitelynotklip** [comment]
> Confirmed by @definitelynotklip on Discord.

Yup, here's an additional screenshot of my game to show you is not caused by a custom tileset or font.

![unknown](https://user-images.githubusercontent.com/87395743/126024622-57760c34-e8aa-435f-9e10-e32f2d498cb2.png)

- OS: Windows 10 Pro, Version 1909
- Game Version: 0.F-7b88ade (Experimental, July 15th)
- Graphics version: Tiles
- Ingame language: System language [English]
- Mods loaded: dda, cbm_slots, OG_Drugs, speedydex, stats_through_kills, StatsThroughSkills, stamina_regen_buff.

**Comment by Kiyotokadoi** [comment]
This issue has been around for a long time, is it difficult to fix?

**Comment by actual-nh** [comment]
Ping: @Fris0uman?

**Comment by Fris0uman** [comment]
No idea what's going on there. I've seen parts get weirdly jumbled around in tile version too if you drive diagonally save&quit and reload maybe it's related.
