### ISSUE TITLE
Eating one corn cob from a stack turns the entire stack into empty corn cob

### ISSUE THREAD

**Issue by logros13** [CleverRaven/Cataclysm-DDA#50002]
### Describe the bug

Eating one corn cob from a stack turns the entire stack into empty corn cob.

### Steps To Reproduce

Have a stack of corn cobs and (E)at it, the entire stack turns into empty corn cob.

### Expected behavior

Only the one corn cob you ate becomes empty,

### Versions and configuration

- OS: Windows 10
- Game Version: 69074ec [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Alternative Map Key [alt_map_key],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    No Rail Stations [No_Rail_Stations]
]

**Comment by occulti** [comment]
I think the solution to this might be along the lines of #50011 - a specific "transform on eat" or "byproducts on eat" use action that produces a new item rather than transforming the existing and allowing it to be eaten, the current item has a "transform" use action on it to change it into a corn cob if eaten raw.

As far as I can see from testing either eating a corn cob from the (E)at menu or activating it, the transform action is called and transforms the whole stack from one item to the other rather than just the activated item, I'm guessing this is a C++ code thing but I am not familiar with the source code enough to attempt to decipher it myself.

**Comment by actual-nh** [comment]
Additional instance - #51533.
