### ISSUE TITLE
Destroyed Chainlink Fences create rock floor

### ISSUE THREAD

**Issue by definitelynotklip** [CleverRaven/Cataclysm-DDA#50111]
### Describe the bug

Building a Chainlink Fence on top of dirt/grass creates rock floor tiling underneath. Destroying said fence then leaves the rock floor intact, preventing another fence from being built on top of it. This method can be used to create rock flooring where it shouldn't be, however there is no way to replace it with the old dirt/grass tiles.

### Steps To Reproduce

1. Debug a Chainlink Fence on top of dirt/grass.
2. (`s`)mash the fence until it is completely destroyed.
3. (`e`)xamine the tile.

### Expected behavior

1. The dirt/grass tile should not be replaced with rock.
2. If the rock is a foundation for the fence, it should be allowed to be mined or removed.
3. Alternatively, it should accept new chainlink fence construction.
4. If the rock flooring is intended design, there should also be a (`*`) Construction menu option to replace it with dirt using the appropriate tools.

### Versions and configuration

- OS: Windows 10 Pro, Version 1909
- Game Version: a27f801 (Experimental, July 18th)
- Graphics version: Tiles
- Ingame language: System language [English]
- Mods loaded: `dda`, `cbm_slots`, `OG_Drugs`, `speedydex`, `stats_through_kills`, `StatsThroughSkills`, `stamina_regen_buff`.

**Comment by Saicchi** [comment]
Can confirm on `0.F-1000-g6d521443d9`.

**Comment by Marrim** [comment]
This is also true for split rail fences.
Fences can only be built on diggable terrain, so they should leave some kind of diggable tile when destroyed.
However, some care has to be taken to not turn this into an exploit that would, say, let the player create dirt tiles where there should be none. AFAIK, this should not be a problem because most diggable tiles can already be reverted to dirt?

**Comment by Night-Pryanik** [comment]
Duplicate of #48452.
