### ISSUE TITLE
Simplified gun names are no clearer than garbledy letter-number combinations.

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#50137]
# Is your feature request related to a problem? Please describe.
I fully support the argument behind renaming guns to plain, understandable terms, but I do not think we have achieved it yet.

A "NATO assault rifle" is not the worst possible name. It tells me it is an assault rifle, and with a bit of research I can tell it probably uses STANAG clips and 223 ammunition. Overall though it still tells me very little about the gun, and the name is long.

This gets worse when we try to create unique monickers for too many different guns. For example, the SIG552 is now a "NATO assault rifle with burst" while an m16a4 is a "NATO burst rifle". This is not better than before at all: it is almost as confusing and several times longer.

# Describe the solution you'd like
Return to using at least some of the letter number abbreviations, but add a statement about firing mode and about gun shape. For example:
"m4 burst carbine": a standard m4 with burst firing mode
"m4 auto carbine": the m4a1.
"SG burst carbine": sig 552 (would SG 552 burst carbine be necessary? I don't know if there's room for confusion here)
"M16 burst rifle": m16a2 or m16a4
"M16 auto rifle": m16a3

Single shot weapons, whether semiauto or bolt action or other, should be represented just by the class, eg.
"Colt revolver"

This produces a more concise name that carries more useful information to the player at a glance, answering important questions like:
- Is this a gun, or an automatically generated password?
- Can I put this in my pocket?
- What other guns might this be similar to?
- Can i hold one of these in each hand and barge through a doorway firing wildly in each direction

We would similarly want "pistol", "revolver", and things like that to be applied to other categories of weapons. We should keep the names from getting too long. There will be some places where a few different weapons can reasonably be condensed into one and then we'll need a more general name. For example, "NATO auto carbine" might be a good name to encompass the remington ACR, SCAR-L, M27, and M38, which are all pretty similar aside from what modifications they start out with.

# Describe alternatives you've considered
There are other ways these could be split but I haven't thought of any that make sense.

# Additional context
This is adjacent to, but not the same as, adding some of the stats back into things that were made too similar with variants.

**Comment by NotDucc** [comment]
Ok, this makes more sense and I'd be cool with these names. I'll come up with some examples like those when I have the time

**Comment by anothersimulacrum** [comment]
It seems most of this problem is due to the sig 552 - I remember there being talk about that not being something that should actually spawn in New England, so that may be something worth a look at.

**Comment by NotDucc** [comment]
> 
> 
> It seems most of this problem is due to the sig 552 - I remember there being talk about that not being something that should actually spawn in New England, so that may be something worth a look at.

Yep, this was something I read while I was doing some research earlier today, as the 552 is discontinued and has been since 2008. The 553, however, is still being made. The big difference being the ammo used, as it switched to 7.62x39 while still retaining a similar appearance as the SIG 552. I'd say its valid to either scrap it or change the name and make it use 7.62x39, as a SIG 552 isn't going to be found in military barracks.

**Comment by NotDucc** [comment]
Alright, so, I did a little investigating this morning by looking at the files for .223 rifles in 0.F Stable:

The M27 IAR, M38, and HK416 could all be grouped into one rifle, as they all are very close variants to each other in real life. Plus, I believe this is only shown in-game by having the rifles have different attachments. I think making them grouped under the name "M27 Rifle" or something similar would make the most sense, as the M27 is the most popular of the 3 in the US military. Along with this, we already have an H&K rifle that is unique in its own rights, so making it into an "H&K Rifle" would make it confusing.

The SIG 552, the Steyr AUG, and FAMAS could all say their farewells in my opinion. The SIG has been discontinued since 2008 (as previously mentioned) and later models are uncommonly used in the US. The AUG was replaced by the M4 in the US. The FAMAS was either rarely used or never used in the US, and a semi-automatic version of the weapon was noted for being imported to the US in the 80's in limited stock but is now exceedingly rare. Due to these reasons, I don't think people would feel strongly against these weapons leaving the game.

The M231pfw is a strange case, as I would have simply said to merging it with the m16 would make sense if it wasn't for the unique rate of fire, which is commented on in the code itself alongside having a unique "6 bullet full-auto". "M16 Open Bolt" could maybe work? Not the best name, but still helps group it. As for the M16A4 and M16A3, I like the solution of "M16 Burst Rifle" and "M16 Auto Rifle"

The M4CQBR is a bit redundant, as its just a shorter barreled version of the M4A1, so it getting grouped with the M4A1 as an "M4 Assault Rifle" (while retaining the stats of an M4A1) would make perfect sense to me.

Based off of what I read, the OA93 is an AR Pistol, yet we already have a weapon named "AR Pistol"... I don't see why the OA93 couldn't get scrapped and just considered the already in "AR Pistol".

Finally, the ACR and the SCAR-L are very similar and could be grouped into being the "FN SCAR" or something similar, as the SCAR is more commonly used and I think is well-known enough for people who don't even know guns to recognize.

This was just for .223 rifles, I'm sure some other guns could be grouped together (I'm pretty sure we have 7 different glocks, and this hasn't been changed at all). Let me know if this list helps with simplifying the guns a little.

**Comment by anothersimulacrum** [comment]
Talked with @NotDucc on Discord about the guns below:
| id | weight | volume | length | ammotype | modes | dispersion | recoil | damage |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
| acr | 3719 | 3310 | 938 | 223 | [1, 4] | 150 | 0 | -1 |
| h&k416a5 | 3490 | 4957 | 798 | 223 | [1, 4] | 180 | 0 | -2 |
| m27iar | 3710 | 4957 | 798 | 223 | [1, 4] | 180 | 0 | -2 |
| m38dmr | 3710 | 4957 | 798 | 223 | [1, 4] | 125 | 0 | -2 |
| m4a1 | 2880 | 3310 | 758 | 223 | [1, 4] | 180 | 0 | -2 |
| m4_cqbr | 2720 | 3110 | 682 | 223 | [1, 4] | 180 | 0 | -3 |
| m16a3 | 3260 | 5030 | 1003 | 223 | [1, 4] | 150 | 0 | 0 |
| scar_l | 3500 | 4970 | 850 | 223 | [1, 4] | 150 | 0 | -2 |

We settled on the following as guns to be collapsed:
| id | weight | volume | length | ammotype | modes | dispersion | recoil | damage |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
| acr | 3719 | 3310 | 938 | 223 | [1, 4] | 150 | 0 | -1 |
| m16a3 | 3260 | 5030 | 1003 | 223 | [1, 4] | 150 | 0 | 0 |

| id | weight | volume | length | ammotype | modes | dispersion | recoil | damage |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
| scar_l | 3500 | 4970 | 850 | 223 | [1, 4] | 150 | 0 | -2 |
| h&k416a5 | 3490 | 4957 | 798 | 223 | [1, 4] | 180 | 0 | -2 |
| m27iar | 3710 | 4957 | 798 | 223 | [1, 4] | 180 | 0 | -2 |
| m38dmr | 3710 | 4957 | 798 | 223 | [1, 4] | 125 | 0 | -2 |

| id | weight | volume | length | ammotype | modes | dispersion | recoil | damage |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
| m4a1 | 2880 | 3310 | 758 | 223 | [1, 4] | 180 | 0 | -2 |
| m4_cqbr | 2720 | 3110 | 682 | 223 | [1, 4] | 180 | 0 | -3 |

**Comment by I-am-Erk** [comment]
Hasn't this been resolved now?
