### ISSUE TITLE
Make counterattacks actually useful

### ISSUE THREAD

**Issue by Broken27** [CleverRaven/Cataclysm-DDA#50195]
# Is your feature request related to a problem? Please describe.

Since #44533, counter techniques range from completely useless, to actively harmful.

If you are using an slow weapon (like an Estoc with fencing) counters just won't trigger at all, ever, (even if all you do is pausing) due to #45138 (The check to prevent being stunlocked by counter use.)

Even worse, however, are situations where counters actually trigger. Right now counters are just regular attacks, except with the added drawbacks of being triggered without player input, and are also often weaker than regular attacks.

(Since your regular attacks can benefit from your other techniques, and counters often don't have any extra effects).

For example, Bio-justu techniques can give reduced move cost (Measured strike) or extra damage+stun (Biojutsu Impale). Using your move units in a counter instead of in a regular attack is thus strictly inferior.

# Describe the solution you'd like
At the bare minimun, counter attacks have to be at least as good as a regular attack technique of the same style - plus some, to compensate the lack of player input in their use.

This can be done in a variety of ways - extra damage, extra speed, extra accurancy, or wharever other bonus is appropiate for the style.

In particular the counter techniques of styles that use slow weapons, like Fior, Fencing or Medieval swordmanship, _require_ substantial time cost reduction or they just won't trigger, ever.

# Describe alternatives you've considered

#45138 proposes some fixes to counters - in particular i like these two:

-Make counters free move-wise again, but limit the survivor to one counter per turn. That way it's a useful addition that doesn't slow down the player without allowing simultaneously responding to attacks from 5 different enemies.

-Instead of making an automatic attacks, an enemy that attacks the player and triggers a counter would be marked for 1 turn; attacking that enemy would perform the counter. This also requires new effects for the counters, and an overhaul of martial arts; it also steps on the toes of onhit/ondodge/etc buffs.

# Additional context
None

**Comment by actual-nh** [comment]
Melee added because when I looked at the PR's title, I thought of kitchen counters...

**Comment by Zireael07** [comment]
Me too, I think the PR title should be adjusted to make it clear :)

**Comment by Cenness** [comment]
And maybe add an option to toggle counterattacks like a gourmand trait.

**Comment by scorpion451** [comment]
That doesn't address the problem. 

Counters are intended to be strictly superior to normal attacks, and previously most were superior despite being weaker than normal attacks simply because they had no move cost. Now that they are not free, many of them are strictly inferior to regular attacks, actively weakening a character using them. There's few if any situations where it would ever be beneficial to turn them on, when many of them are intended to be signature or capstone abilities that make an otherwise weak style worth using.

**Comment by kevingranade** [comment]
Probably the best option going forward is this suggestion from #45138
`Instead of making an automatic attacks, an enemy that attacks the player and triggers a counter would be marked for 1 turn; attacking that enemy would perform the counter.`

I don't like the retroactive behavior this causes, but the alternative is pretty complicated.

Basically if you have an active counter ability, the attacker would get a "counter opening" effect applied and counter-able attacks would get deferred until your next action.
If your next action is an attack on an enemy with a "counter opening", your attack is processed first, likely interrupting the attack.
With very good skills and the right martial art, multiple counters per turn would be possible.
Once you trigger an action that is not a counter, any deferred attacks are processed before your action completes.
This feels a lot more like a counter system to me, but it's pretty invasive to the turn logic, and it's very likely that players are not going to understand that they have potentially several deferred attacks that are going to trigger as soon as they try to take action.

**Comment by Cenness** [comment]
> 
> 
> That doesn't address the problem.
> 

It doesn't fix it outright you mean. On the other hand, as you said, counter toggle will allow players to be able to use fighting styles in their current form, without being afraid about wasting move points, while maintainers discuss on a correct way to solve that problem. And it can be removed in the PR with a true solution.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do this by itself.
