### ISSUE TITLE
Electronic Gun Safe cannot be hacked

### ISSUE THREAD

**Issue by AdamChirnside** [CleverRaven/Cataclysm-DDA#50289]
### Describe the bug

When trying to hack into an electronic gun safe using either an active Fingerhack CBM or an electrohack, receive the message "You don't have a hacking tool with enough charges!"

### Steps To Reproduce

1.  Load save [Pickett.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6896806/Pickett.zip)
2. Attempt to hack nearby safe

### Expected behavior

Able to use either the CBM or the electrohack to attempt hacking into the safe

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 2b9d8f5 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    Disable NPC Needs [no_npc_food],
    No Rail Stations [No_Rail_Stations],
    Bionic Professions [package_bionic_professions],
    No Fungal Monsters [No_Fungi]
]

**Comment by BHasselaar** [comment]
I can confirm this behavior in the latest experimental 2021-07-27-1347. Started a new world without mods and couldn't hack a electronic safe even with full battery power. Aside from that, many CBMs seem to be malfunctioning, because I never managed to activate neither the ethanol burner nor the battery system.

![image](https://user-images.githubusercontent.com/76605940/127492299-c754bacd-6e71-4b03-9e78-714b221e1a79.png)

**Comment by actual-nh** [comment]
Have you tried "refuel" under the bionics menu?

**Comment by BHasselaar** [comment]
>  Have you tried "refuel" under the bionics menu?

Thanks, I didn't even know that there was such thing as refuel. I tried to `E`at some batteries as the description stated to no avail. And drinking some wine made my power go up, so everything working as intended I hope (not the fingerhack tho), just some misunderstanding on my part.
