### ISSUE TITLE
Split "Stylish" into multiple aesthetic-based traits

### ISSUE THREAD

**Issue by AmarinReyny** [CleverRaven/Cataclysm-DDA#50285]
# Is your feature request related to a problem? Please describe.
Basically, I think that there should be multiple stylish-like traits that cover different aesthetics. The original "stylish" trait could maybe be renamed to "fancy," while new traits could be named things like "punk," or "cowboy," or "cosplayer," or anything else applicable. Having only one "stylish" trait that applies mostly to high society kind of feels... lacking.

# Describe the solution you'd like
Uhh... I don't know what else to put here.

# Describe alternatives you've considered
Iunno? I just think it would be cool to have in-game.

# Additional context
I'd be willing to do some or all of the JSON work, if someone else is willing to do the C++ stuff.

EDIT: Also, someone on Reddit suggested making these traits applicable to weapons, in addition to clothes.

**Comment by AmarinReyny** [comment]
Apparently, my browser had some kind of an error, and caused this to be submitted seconds after I started to type the title. Sorry about that! I'll edit the rest in.

**Comment by Vendidurt** [comment]
My clown suit still registers as Fancy, so everything seems to be working for me!

**Comment by big-smitty** [comment]
I think this might be cool for immersion but it seems pretty overkill for gameplay sake. If specially marked items worked the same as 'fancy' items do now but they were just labeled differently that would be cool.  
That would leave room for special starting traits like 'punk rocker' or 'emo' or 'loves pink' without really burdening the gameplay of characters who don't care

**Comment by UNOwenWasMe** [comment]
Who is going to decide what fits a certain style? Groups have a tendency to split indefinitely into subgroups so the answer will differ depending on who you ask. For example: cyberpunk exists, and goth, and cybergoth is also a thing. Are we including every aesthetic subgroup that has existed? If yes, that would be a lot of work, if no, how to decide which ones, and who will decide?
Right now, you are already able to roleplay in whatever way you want, even without the Stylish trait. 
The only way I personally see this working is to specifically add items like "punk rock jacket" or "emo wig" that leaves the actual clothing up to interpretation, but that introduces an amount of artificiality, namely that items get added solely to make a trait have some kind of noticable yet minor impact. I'm not exactly opposed to that idea in principle, but in the end I believe the payoff would be small, and I think care should be taken not to inflate the item pool with a bunch of specific themed items that makes them feel out of place.
If you start to add tags to certain already existing items, that could disrupt the roleplaying of characters that want to wear those items without the connotation of it looking like or belonging to a certain group or style. Sure, the cowboy hat item is pretty straightforward, but if we have a cowboy trait, that opens the door for an inflation of roleplay traits that don't really alter the gameplay since you can already roleplay however you want.
It also opens the door for the following argument: "if the cowboy character feels happy for wearing cowboy hats, why does my character not feel happy for being able to wear this other specific style of clothing? Or even, why doesn't he feel happy for wearing his own very specific niche style?"
It would be a valid argument to deal with, and that goes back to the subjectivity of aesthetics, and in this case fashion.
For this reason I'd argue that the "stylish" trait accomplishes in essence what it tries to do: it distinguishes between people who care about how they dress and those who don't. It poses its own problems in deciding which items are valid candidates for the 'fancy' tag, but it finds a nice balance of abstraction between 1) not making the distinction at all, and 2) having an infinite amount of traits in order to take every aesthetic group into account.

**Comment by AmarinReyny** [comment]
> Who is going to decide what fits a certain style? Groups have a tendency to split indefinitely into subgroups so the answer will differ depending on who you ask. For example: cyberpunk exists, and goth, and cybergoth is also a thing. Are we including every aesthetic subgroup that has existed? If yes, that would be a lot of work, if no, how to decide which ones, and who will decide?
> Right now, you are already able to roleplay in whatever way you want, even without the Stylish trait.
> The only way I personally see this working is to specifically add items like "punk rock jacket" or "emo wig" that leaves the actual clothing up to interpretation, but that introduces an amount of artificiality, namely that items get added solely to make a trait have some kind of noticable yet minor impact. I'm not exactly opposed to that idea in principle, but in the end I believe the payoff would be small, and I think care should be taken not to inflate the item pool with a bunch of specific themed items that makes them feel out of place.
> If you start to add tags to certain already existing items, that could disrupt the roleplaying of characters that want to wear those items without the connotation of it looking like or belonging to a certain group or style. Sure, the cowboy hat item is pretty straightforward, but if we have a cowboy trait, that opens the door for an inflation of roleplay traits that don't really alter the gameplay since you can already roleplay however you want.
> It also opens the door for the following argument: "if the cowboy character feels happy for wearing cowboy hats, why does my character not feel happy for being able to wear this other specific style of clothing? Or even, why doesn't he feel happy for wearing his own very specific niche style?"
> It would be a valid argument to deal with, and that goes back to the subjectivity of aesthetics, and in this case fashion.
> For this reason I'd argue that the "stylish" trait accomplishes in essence what it tries to do: it distinguishes between people who care about how they dress and those who don't. It poses its own problems in deciding which items are valid candidates for the 'fancy' tag, but it finds a nice balance of abstraction between 1) not making the distinction at all, and 2) having an infinite amount of traits in order to take every aesthetic group into account.

Fair enough. I was just kind of going with a suggestion someone made in comments on one of my Reddit posts, to ask about this stuff on GitHub and see if others would find it worthwhile enough to be made at all, or to see if someone maybe wanted to handle the C++ part of it while I could do the JSON part (since various problems have made learning C++ prohibitively difficult for me). My original idea was to make it as part of a mod rather than asking for its inclusion in vanilla, but... yeah.

Anyway, thank you for your input.

**Comment by UNOwenWasMe** [comment]
Hey, nobody is going to mind an extra mod! Don't let your ideas be dreams, I'd say. A mod that rewards me for roleplaying as a mafia gangster with tommyguns and fedoras, or a junkjard punker with nails bats and rugged gear, sounds cool enough. I just gave my opinions on implementation and it's a matter of knowing what you want to accomplish that isn't already in the game!
