### ISSUE TITLE
Archer's form training shouldn't require focus

### ISSUE THREAD

**Issue by LaVeyanFiend** [CleverRaven/Cataclysm-DDA#50295]
### Describe the bug

Archer's form is based on training muscle groups, but ingame is dependent on mental focus as well.

### Steps To Reproduce

1. Start w/o the Form proficiencies.
2. Try training it with a spawned short bow on a practice target.
3. Progress tanks hard due to being split on both two skills & the proficiency.

### Expected behavior

The skills should drain focus, but the form be independent.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 2b9d8f5 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Bionic Professions [package_bionic_professions],
    Mythical Martial Arts [MMA],
    Bionic Slots [cbm_slots],
    Disable NPC Needs [no_npc_food],
    Stats Through Kills [stats_through_kills]
]

### Additional context

@anothersimulacrum told me to

![image](https://user-images.githubusercontent.com/51099123/127428951-a4258c5c-d4a4-47f6-b8b9-559f65d5de75.png)

**Comment by Marrim** [comment]
Does it care about intelligence? If it does, it should then care about dexterity instead.

**Comment by pehamm** [comment]
Not an expert by any means, but if this about correct form rather than pure muscle power, I would expect it to take focus.

Whenever I did any sport that required clear form, I had to make a mental effort to ensure to keep the form up until it became second nature, and I could feel mentally drained afterwards. If this is purely about "Are your arms strong enough to draw the bow" then this is fine, but the name "Archers form" suggests to me that it should include mental effort and thus drain focus.

**Comment by big-smitty** [comment]
So I'm not an archer but I did the rounds in Tennis, and the form training is pretty similar (at least imho) because you just drill the same thing over and over again.  You don't really think about it, but it takes a small amount of focus. Like if you want to work on a specific issue you just drill over and over while only thinking of that one piece. 
I'm not a pro athlete or anything but it seems reasonable that you don't need tons of focus.

**Comment by AccountAlias** [comment]
Ah, noted; I'll remove focus drain from archery forms in particular
