### ISSUE TITLE
Heating up food doesn't take into account quantity of food being heated, charge-wise

### ISSUE THREAD

**Issue by GGgatherer** [CleverRaven/Cataclysm-DDA#50328]
### Describe the bug

Heating up food takes time proportional to amount of food you're heating but it always takes only 1 charge (or a single heat pack) regardless of amount of food.

### Steps To Reproduce

- make winter start, spawn crapton of tomatoes (or w/e food can be frozen) and a heatpack or hotplate or heat cube, wait till food is frozen, try heating it
- see time passing proportionately to amount (weight? volume? just plain "charge" count? whatever it is, it is working) of food being heated
- see charges used are always 1.

### Expected behavior

Being able to heat only as much food as you have charges available for. I'm not arguing for needless complication along the lines of "while you're charging 4th piece of meat, three previously heated pieces start to freeze", but you shouldn't be able to heat up a full freezer worth of food with one heat pack, or just 1 battery charge.

### Versions and configuration

- OS: Windows 7
- Game Version: 15dd993 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Skills [StatsThroughSkills],
    Bionic Professions [package_bionic_professions]
]

**Comment by VincentRoyceMorgan** [comment]
I haven't tested with an extremely high amount of food, but I was definitely able to heat up 56 frozen pemmican with a single heat pack. So I'm not sure if there's a limit but there's definitely the moment where you can heat a copious amount of food with a single heat pack.
To be completely honest, that does make heat packs more viable, but perhaps they shouldn't be able to heat liters upon liters of food. In real life you could use the heat pack provided with the MRE to heat up everything in the MRE if you so desired. That's because you'd put the things you'd want to heat back into the main MRE package (Or a specialized bag where the heat pack and entree go in together) and heat up multiple things and not just your entree.

**Comment by RenechCDDA** [comment]
With charges removed from food, this is resolved/no longer valid. Every time you select an item to heat up it'll always be selecting up one item and using one item's worth of electrical (charges).
