### ISSUE TITLE
NPCs cause extreme torso bleeding in hostiles in big area.

### ISSUE THREAD

**Issue by ErrorUsernameNotFound** [CleverRaven/Cataclysm-DDA#50331]
### Describe the bug

NPCs piercing/cutting weapon cause extreme torso bleeding for all hostiles in a 8 tile square around them when attacking something (or walking to something to attack it).

### Steps To Reproduce

1. Spawn a NPC.
2. Make sure the NPC has a weapon with cutting/piercing.
3. Spawn debug monsters around the NPC in an square area around the NPC
4. Observe that all debug monsters in the 17x17 tile area around the attacking NPC start bleeding from the torso. 

### Expected behavior

I expect that only the attacked monster/NPC can get the bleeding effect.

### Screenshots

![2021-07-30 (4)](https://user-images.githubusercontent.com/53142838/127670965-7f9829c5-a2be-4578-bb97-bde7c9556396.png)
![2021-07-30 (5)](https://user-images.githubusercontent.com/53142838/127671010-edc80ec4-3316-49ac-9e87-cd9a488e1548.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 15dd993 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations],
    Graphical Overmap [Graphical_Overmap],
    No Fungal Monsters [No_Fungi],
    SpeedyDex [speedydex]
]

**Comment by GoLoT** [comment]
Possibly a side-effect of using `item::effective_dps()` to evaluate melee attack effectiveness in `npc_attack.cpp`.

https://github.com/CleverRaven/Cataclysm-DDA/blob/6f1d7dfd912c48283156356fb4016de44ba301f6/src/item.cpp#L1645

I can't test it right now but it looks like the function is creating two temp creatures using a pointer to the original creature instead of a new one. If I'm right, this will be causing the creatures to take damage each time `effective_dps()` is called. I'm not sure if this is a bug in that function or if it's supposed to be a testing function and evaluation should be handled some other way in `npc_melee_attack `(i.e. using the weapon dps).

**Comment by actual-nh** [comment]
It looks like it was created for the display of DPS vs various standardized monsters, from item.h.

**Comment by KorGgenT** [comment]
*sigh* i knew it. @GoLoT may i assign this to you?

**Comment by GoLoT** [comment]
Yeah, sure. I'll take a closer look tomorrow.

**Comment by kevingranade** [comment]
This issue has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/npcs-are-clothing-shredding-machines-now/26763/9
