### ISSUE TITLE
Use normal distribution instead of dice for to-hit calculation

### ISSUE THREAD

**Issue by swwu** [CleverRaven/Cataclysm-DDA#5034]
Pros:
* It returns a float value, meaning better to-hit/dodge granularity for low-skill characters
* It allows more obvious control over the shape of the to-hit distribution - you can directly specify mean and standard deviation rather than just putting in some dice numbers and hoping it feels right.
* Uses much fewer random numbers - `dice(20, 2)` will actually call `rand()` 20 times, whereas `gaussrandom(30, 5)` using [Box-Muller](http://en.wikipedia.org/wiki/Box%E2%80%93Muller_transform) will call `rand()` exactly twice - once if you optimize it correctly - and will have the same first and second moments.

Cons:
* Will have slightly different distribution shape, but multiple dice rolls (which we currently use) already converge to a normal distribution anyways because of the [Central Limit Theorem](http://en.wikipedia.org/wiki/Central_limit_theorem), so it's guaranteed to be pretty damn close (tm).

**Comment by mugling** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting though check nobody else has made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about the latter consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
