### ISSUE TITLE
Energy consumption of jackhammer

### ISSUE THREAD

**Issue by Menschheit** [CleverRaven/Cataclysm-DDA#50398]
# Is your feature request related to a problem? Please describe.
I don't know if the numbers are right, I said goodbye to physics and chemistry after middle school...
A electrical jackhammer costs 3500 charges to use, which equals to 3500kJ.
A gasoline powered jackhammer costs 10 charges to use, which is 0.01L.
Wikipedia says the heat value of Gasoline is 8,4–8,7 kWh/L so 0.01L gasoline produces about 9* 3600 * 0.01 = 324kJ 

looks like the electric one costs 10 times energy doing the same job. 

# Describe the solution you'd like
change the values

**Comment by Nabo92** [comment]
Also, a gasoline jackhammer would be much more inneficient in converting the gas burned to actual kinetic energy, because combustion engines usually are so, but I don't have the numbers.

**Comment by robotic-gamer** [comment]
quote from Wikipedia on electric motor entry: "Electric motors are much more efficient than the other prime mover used in industry and transportation, the internal combustion engine (ICE); electric motors are typically over 95% efficient while ICEs are well below 50%.". given this a gasoline jackhammer should use about 200 units a run if the electric jackhammer is to remain unchanged. personally I think the charge amount needed should be lowered since from a gameplay standpoint I already favor the pickaxe over the electric jackhammer even when I can recharge it.

**Comment by actual-nh** [comment]
So that would mean the electric jackhammer would be using 3500/20 -> 175 charges per use?

**Comment by ZhilkinSerg** [comment]
Electric jackhammers are fine. Gasoline jackhammer should have 1-1.5 liter gasoline capacity and use 0.5-0.7 liter per hour.
