### ISSUE TITLE
Mi-go biotechnology, patrols, and events.

### ISSUE THREAD

**Issue by Ramza13** [CleverRaven/Cataclysm-DDA#50410]
# New mi-go content
This is a central issue to keep track of and solicit feed back on my new mi-go work.

The underlying feature of the work is a hidden variable called mi-go interest that describes how interested in you as a specimen/agent the mi-go currently are.  Their are several planned ways to increase this:
- Killing mi-go.  The mi-go aren't mad at you killing them, on the contrary they are impressed and more likely to decide you are worth study or incorporation.
- Use of mi-go biotechnology.   The mi-go are all linked by biotechnology far beyond our wildest dreams.  Using this technology carries the risk of being noticed.
- Eating mi-go flesh.  This can very rarely draw attention.  Sometimes the mi-go links can survive the death of the host.
- Flying patrols.  From time to time if the player is outdoors they can see mi-go ships in the sky.  If you can get inside quickly enough it won't notice you.  At lower interest levels it will just take note of you(increasing mi-go interest) and carry on.  At higher levels it may deploy troops.
- Time.  As time passes and the cataclysm culls the weak the mi-go become increasingly interested in anything still surviving. 

# Broad intentions

- Their should be no information provided to the player about mi-go interest increasing, the goal is for mi-go to seem a powerful resource with minimal downsides at first.  Later on the costs start to become clear.  
- Mi-go flesh rots very slowly and will give you calories if you're desperate but the real reason to consider eating it is the chance of a positive effect.  It's more likely nothing will happen or something bad will happen or you'll get sick but if you've got nothing to lose it might save the day.  
- Mi-go biotechnology when used will 95% of the time do something beneficial and powerful.  The last 5% it hits you with something bad but its not as bad as the good is good.  Either way most of the time your mi-go interest increases a little, rarely a lot, and if its high enough a patrol may be heading your way in the near future.
- Avoiding the mi-go delays having to deal with them but live long enough and they will become a real problem.  One of the goals here is to add in some long term danger to spice up the end game.  
- The game is too depressing so add a new hopeful uplifting ending where the player has their loneliness cured and becomes much better than they were before.  All at the minor cost of individuality and any real memory of what you used to be.
- Add a new scenario that sets mi-go interest high right from the beginning.

# Mi-go bio tech
Sometimes when you butcher a mi-go you find strange organ/technologies that seems to still be animated.  Touching these produces a strange sensation and if you don't pull away quickly will effect your biology.  Either your biology is similar to that of a mi-go or as part of how advanced this technology is, the effects are usually positive.  The first time a unit is used a random positive and negative effect is assigned and doesn't change.  At high levels of interest you might have a momentary confusing "conversation" with a vast intelligence.
Current planned effects:
- Morale.  For a long while you just feel happy.
- Focus. You get a large boost to your focus.
- Pain.  Your pain vanished and without any addictive side effects.
- Stats.  For a while some of your stats are increased.
- Fatigue.  You feel more awake.

# Mi-go mutations.  
This part is a little less fleshed out but at higher levels of interest I want to have meat and bio_tech have a chance to mutate the player.  All the levels will hurt your social skills (somehow interacting with beings you can't hear in your head seems a little weird), give you some heat resistance, maybe some other boon?.  At the highest level mi-go's are non hostile unless you attack them but there's a chance from time to time that a special patrol is launched to find you.  It contains a special mi-go unit which does not attack you but instead initiates a telepathic dialog.  

This dialog will only make a little sense at best as you aren't fully synced with the mi-go collective(still have some of that obsolete individual identity) and your answers will only have a minor influence on the outcome.  At the end of the dialog there is a choice given to you.  If you go towards the being you get a game over with an epilogue describing you becoming one of the mi-go, it turns out they are not technically a single species but some of their number started out as separate races. If you resist there is a small chance your body refuses to obey your will and you get the above ending.  Otherwise you get a battle with the unit and its guards.

At present #50178, #49986, and #50408 are part of this effort and I will link future PR's to this.

If you have any ideas or if any of this sounds unbalanced or against lore or needing work let me know.

**Comment by PatrikLundell** [comment]
This make the mi-go sound like just another mycus (but less annoyingly overpowered).

Also, if the mi-go is really multiple species, the units should have multiple appearances, unless assimilation means morphing assimilated units into the standard morphology.

The "bio tech" doesn't make any logical sense. It looks more like a fantasy curse type effect than any kind of technology. It would make more sense if the strange organ burrowed itself into the recipient's body and had a permanent effect (biological CBM's essentially). If so, they might potentially be removable with an autodoc, but require either instructions (from whom?) or very high Health (and Computer?) skill to perform successfully. These organs might also replace some organ(s), requiring the arrangement for technological replacements if removed.
If the bio tech essentially is biological CBMs, I can see some synergy with the Exodii, who might have knowledge about the mi-go and their bio tech (including means of removal and replacements).
Random effects of bio tech also seems more fantasy than tech. I'd rather have the organs have fixed functionality, but with an uninitiated player being unable to identify them (all of them being described as strange organs, unless you've learnt to identify them, which would be done one organ at a time). Some organs might be undesirable for a human (you wouldn't really be interested in "live streaming" your sensory inputs, or functionality to allow you to temporarily [you'd hope] hand over control of your body to "higher authority" or "experts" [regardless of how good those experts would be at e.g. performing dissections]).

**Comment by Broken27** [comment]
Is there any way to deal with Mi-go interest at all after it starts building up?

Killing their patrols will only make it go up more, so it seems like the kind of thing were it can enter a permanent feedback loop unless there is some way to lower it.

**Comment by PatrikLundell** [comment]
The gamey way I can see to lower interest would be to kill the "recruiter" to drop the interest down to some nominal base level, but there's no logical reason for a hive mind to drop significant functionality or knowledge just because a functional unit dies.

The other factor I can think of is time, i.e. that interest would drop over time unless supported by new boosts, but I don't see why a hive mind would forget things over time.

**Comment by Broken27** [comment]
> The gamey way I can see to lower interest would be to kill the "recruiter" to drop the interest down to some nominal base level, but there's no logical reason for a hive mind to drop significant functionality or knowledge just because a functional unit dies.
> 
> The other factor I can think of is time, i.e. that interest would drop over time unless supported by new boosts, but I don't see why a hive mind would forget things over time.

The problem i am seeing is that Mi-go interest seems to assume that the Mi-go have both infinite resources to drop at the player (The more patrols killed, the more patrols are sent) and an infalible way to detect the player location.

Ultimately the Mi-go aren't a major player in the cataclysm, they shouldn't have infinite stuff to launch against a single specimen, regardless of how interesting it may be.

And they shouldn't have a way to perfectly locate where the player is unless they are actively carrying Mi-go tech - So dropping all your Mi-go should decrease their chances of them finding you over time. (Or better yet, distance traveled, but that would be much harder to implement).

**Comment by PatrikLundell** [comment]
I'd prefer if the mi-go was a "normal" race, i.e. not a hive mind. I don't mind advanced communications (e.g. biological radio CBMs for something resembling telepathy, but which actually is detectable [and blockable]), but magically sensing the vibes of their biological CBMs is going too far in my view.

The mi-go are described as slavers, although it isn't specified what they'd want slaves for (as far as I know), and engineering their perfect slaves using their bio tech would seem to be a better option, although the slaves might be test subjects used to determine if there's some useful biological functionality to gain from humans (and, if that's the case, other life forms on Earth). They seem to be opportunistic rather than a massive organization, so losing a tower ought to be a blow to their operations on Earth (not a huge one, but still affecting the local area a little, at least until they've managed to replace it).

**Comment by forwardslashN** [comment]
I have to echo some of the other comments here. I think the effects of the biomods as presented here are more equivalent to a mutation or assimilation. I don't find that idea particularly enticing or interesting, given how prevalent mutations already are in the game. And there is already the blob and the mycus that have the assimilation angle. I like the mi-go to be individuals, maybe with a linked consciousness of some sort, but not a true hivemind.

The mi-go interest is not a bad start, I think, but I it could work in an altered way. Instead of consistently going up, it could decay over time and spike when the player does things that would normally interest the mi-go. Such as install biomods, kill their patrols, etc. Which would lead to retaliation. The mi-go essentially go around enslaving others, and I feel that they would find the player an interesting sample to collect and dissect (much like they do in the works of Lovecraft) rather than to bring in to their fold. The latter angle is more fantastical, thus less desirable.

As far as the biomods themselves go, I like the idea of symbiotes. They would function to boost something in exchange for something else, a lot of the time. Perhaps a symbiote that feeds on positive emotions (draining your mood) while it provides you with additional redundant organ, or some other biological benefit. Or, for example, a symbiote that causes a small degree of pain at all times, but can deaden you to external pain to a degree. But in general, I see biomods as a trade off where you are allowing external organisms to coexist within your body, but this would depend on the biomod. Some mi-go biomods could give only benefits with no drawbacks and some more harm than good (like the faulty CBMs), the problem would be identifying them.

In terms of practical effects, as I've already mentioned, a small drawback and a powerful passive would be my design principle. Bonus points if you install several "compatible" mi-go biomods, they would give an extra benefit of some sort. And I don't see biotech to be compatible with CBMs; the are polar opposites. I don't know if it should be possible to install any mi-go derived biomodification when you have CBMs in your body.

**Comment by Ramza13** [comment]
I may eventually revisit some form of this idea, but in its present form I've been convinced it's not fully ready.  That and with focusing on portal storms I'm not going to be working on this any time soon.
