### ISSUE TITLE
Shelf stable milk rot too fast

### ISSUE THREAD

**Issue by vivi00790** [CleverRaven/Cataclysm-DDA#50519]
### Describe the bug

Generally shelf stable milks should be safe to drink in 3-6 month after produced, and can even last longer keep sealed.
However in my last run, I start at spring day 60 and all shelf stable milks in sealed container are rotten at spring day 72.
![image](https://user-images.githubusercontent.com/6245453/128474006-80fc2d72-80a9-44eb-bffa-563c7524a24b.png)

### Steps To Reproduce

1. spawn at military base warehouse.
2. live 12 days.
3. check the milk.

### Expected behavior

They should last at least one season.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: bc28921 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    C.R.I.T Expansion Mod [crt_expansion],
    流浪大师 [wandering_masters],
    Blaze Industries [blazeindustries],
    Aftershock [aftershock],
    末世強盜 [GOV_BANDITS],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations],
    充实小@的特征 [amplified_players_features],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    末日商人 [Merchant],
    萌化计划 [ProjectKawaii],
    No Fungal Monsters [No_Fungi],
    Clean CBMs [clean_cbm],
    Fuji's Military Profession Pack [fuji_mpp],
    Manual Bionic Installation [manualbionicinstall],
    Portable Autodoc [portable_autodoc],
    Safe Autodoc [safe_autodoc],
    Safe Portable Autodoc [safe_portable_autodoc],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    移除生化槽位 [no_cbm_slots],
    CDDA车辆扩展 [ks_variety_pack],
    专长速成 [sch_easy_proficiency],
    <color_light_blue>减轻疲惫程度</color> [light_weariness]
]

**Comment by Zireael07** [comment]
Shelf stable milk only lasts for months IF refrigerated, and there are no fridges in Cata (no mains power)

**Comment by vivi00790** [comment]
@Zireael07 and others have concern about expiration day of shelf stable milk, FYI

1. from one of Shelf stable milk brand https://silk.com/plant-based-products/shelf-stable/benefits-of-shelf-stable/ 
![image](https://user-images.githubusercontent.com/6245453/128540667-75510d16-2ce7-4259-8a6d-dd6f48f67aa3.png)

2. from wiki UHT milk https://en.wikipedia.org/wiki/Ultra-high-temperature_processing
![image](https://user-images.githubusercontent.com/6245453/128540905-ed158b0a-feeb-477c-95ee-ddff44dcc892.png)

3. from School Nutration Association https://schoolnutrition.org/uploadedFiles/2_Meetings_and_Events/Virtual_Events/ISS/ISS-2021-Shelf-Stable-Milk-FAQ-Online.pdf
![image](https://user-images.githubusercontent.com/6245453/128541109-66167f52-a79c-457c-847d-a42d4af3a128.png)

4. All of above are under non-refrigerated condition, because shelf stable milk is INVENTED to bypass requirement of refrigerater.

5. 12 days is not 1 month, change my mind.

**Comment by occulti** [comment]
Ok, looking at this from a calculation perspective the current "spoils in" for shelf stable milk is set to 2 days and for carton_sealed the "spoil_multipler" for sealed is 0.5, by my calculation the milk should spoil in 4 days (my maths may be wrong on this, feel free to correct me if so).

Taking the above as true and giving the unsealed milk a 7 day shelf life, the spoil_multiplier for the container would have to be 0.023 to get 10 months (around 300 days) - 7 / 0.023 = 304 (this is assuming that spoil-multiplier is a float that can take that many decimal places)

Alternately, the spoil time of unsealed shelf stable milk would have to be set to ~150 days in order to work with the current container.

Currently shelf stable milk is the only comestible to use carton_sealed so the above would work, the question is would this container be used for other items in the future and would this level of preservation when sealed be game breaking?

**Comment by kevingranade** [comment]
I think we could reserve the carton_sealed just for use with shelf-stable milk.

**Comment by Zireael07** [comment]
https://github.com/vivi00790 thanks for the info <3
