### ISSUE TITLE
Broken world generation with mods

### ISSUE THREAD

**Issue by aezakmq** [CleverRaven/Cataclysm-DDA#50636]
### Describe the bug

Mods that add new locations to the map do not allow locations from vanilla cdda to appear normally or in normal numbers

### Steps To Reproduce

1. Activate mod/mods that add locations (Magiclysm, Aftershock, or others)  
2. Start actively exploring the map and try to find laboratories, military outposts, military bunkers, refugee camps, etc (everything that should be in the world without mods)
3. You may be able to find locations in a single instance or find nothing at all
4. If you turn off mods that add locations and play on the vanilla cdda, map generation will be fine

### Expected behavior

Vanilla locations spawn just fine with mods' locations, map generation is mixed with both mods and vanilla spawning their locations in a balanced way (as they should, since neither of these mods blacklist any vanilla locations nor change their spawn rates)

### Versions and configuration

- OS: Windows 10 20H2 19042.1110
- Game Version: d213995 [64-bit]
- Graphics version: Tiles
- Ingame language: Russian 
- Mods loaded: Magiclysm, Aftershock

**Comment by actual-nh** [comment]
Actually, I think Aftershock may remove some vanilla map extras; I don't think Magiclysm is supposed to, however.

**Comment by freijie** [comment]
Noticing same issue,  magiclysm special locations are plentiful but vanilla only has village houses and a few special structures, military facilities almost non-existent. Stable didnt have such issues for me, it had a healthy mix of magiclysm and vanilla locations.
Also could be related to this issue I cannot start in frozen lab in most seeds with magiclysm enabled, location cannot be generated with error message:
![изображение](https://user-images.githubusercontent.com/25095102/128763350-b807b95b-bf75-44cd-bfd6-b357d31f2420.png)

**Comment by SariusSkelrets** [comment]
I noticed that aftershock prevented the generation of the big military base from the overrun scenario 

My guess is that aftershock, gradually becoming a total conversion mod, removes some spawns as they won’t fit in the total conversion

I never noticed any generation problem that could’ve been caused by magiclysm

DDoD blacklists mi-go and lab stuff so don’t use it if you want to start as a captive or experiment

**Comment by actual-nh** [comment]
@Venera3: Would you happen to have run any testing on location generation with mods?

**Comment by actual-nh** [comment]
Ping: @John-Candlebury, @Maleclypse, @Mom-Bun, @KorGgenT?

**Comment by Maleclypse** [comment]
Cannot replicate on - OS: Windows
    - OS Version: 10.0 2009
- Game Version: a27f801 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock]
]
Which is from 7/18.

So the interesting stuff happens with my download from yesterday. 
- OS: Windows
    - OS Version: 10.0 2009
- Game Version: a676db7 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock]
]
When I make this world it soft locks during worldgen for about 10 seconds and then generates.   I quit out and try to generate a new world.  If it succeeds same as before but if it fails every attempt after that fails instantly without the soft lock until I quit all the way out and reload the game entirely.   At which point the cycle begins again of maybe it works on first attempt and if it fails then it fails forever.

**Comment by Maleclypse** [comment]
![AFS last month](https://user-images.githubusercontent.com/54345792/128784107-20200515-b2ed-4973-b86a-df76dd68a316.PNG)


It doesn't look like any of the last month or so of Aftershock PRs could have caused this change.

**Comment by John-Candlebury** [comment]
> I noticed that aftershock prevented the generation of the big military base from the overrun scenario
> 
> My guess is that aftershock, gradually becoming a total conversion mod, removes some spawns as they won’t fit in the total conversion
> 

Aftershock includes no blacklists. If you are noticing a reduction is spawnw its because the mod includes new overmap locations and each new location dilutes the spawns of previously existing ones.

Probably the requirements for the base are too strict, and some Aftershock buildings occupy the same locations. The base would likely spawn given a few more tries.

Also sorry for the comment edit, I misclicked and didnt notice, but I did restore your comment.

**Comment by Maleclypse** [comment]
> Probably the requirements for the base are too strict, and some Aftershock buildings occupy the same locations. The base would likely spawn given a few more tries.


So that's the weird thing I was describing, there haven't been any aftershock location changes in the last month and I have a version of the game from less than a month ago that doesn't have this happen at all.  As of 7/18 you could spawn overrun every single start as far as I managed to test.

**Comment by Mom-Bun** [comment]
Do you have the Aftershock Exoplanet mod enabled? this would be causing the issue if you did

**Comment by aezakmq** [comment]
Thing is, many locations in these mods, including Aftershock and Magiclysm, have not been updated nor their spawn rates were drastically changed for quite a while, it does not seem to be a problem related to mods, something in vanilla code has been changed, highly likely

**Comment by aezakmq** [comment]
> Do you have the Aftershock Exoplanet mod enabled? this would be causing the issue if you did

No, it's a regular Aftershock, not an Aftershock exoplanet

**Comment by Mom-Bun** [comment]
Hi its been a bit and as far as we know, this shouldn't be an issue, a few questions:
1. Are you absolutely sure you only have Aftershock and Magiclysm loaded? 
2. Can we have your save please?

**Comment by aezakmq** [comment]
> Hi its been a bit and as far as we know, this shouldn't be an issue with aftershock, a few questions:
> 
> 1. Are you absolutely sure you only have Aftershock and Magiclysm loaded?
> 2. Can we have your save please?

1. Yes, these 2 mods are loaded
2. https://anonfiles.com/D54am5Cbu1/_rar - save
    https://anonfiles.com/Te77maC0u7/cata_old_save_rar - cdda+save

**Comment by aezakmq** [comment]
> Hi its been a bit and as far as we know, this shouldn't be an issue with aftershock, a few questions:
> 
> 1. Are you absolutely sure you only have Aftershock and Magiclysm loaded?
> 2. Can we have your save please?

1. Yes, these 2 mods are loaded
2. https://anonfiles.com/D54am5Cbu1/_rar - save
    https://anonfiles.com/Te77maC0u7/cata_old_save_rar - cdda+save

**Comment by Mom-Bun** [comment]
Tested on latest build today (bd2ce6b 64-bit to be exact) with vanilla world, no issues, and no issues so far with a world with aftershock loaded (however I had to go to the other overmap to find a refugee center and some military locations, but this could just be bad RNG)

Booting up with MGS is the same, however when doing both it freezes and refuses to load, possible issue overall with competition on overmap locations and where to place them and/or overmap code changes.

I could be wrong about this (Still an incredible novice at C++) but the past things in 30~ days that could've potentially be causing this issue I suspect are:
#48607
#48628
#48627
#47071 (Not sure about this one, its been around recently since January and we've had no issues about it)

As they've all recently touched upon overmap generation recently

**Comment by Venera3** [comment]
Ran a smallish test with Vanilla, AFS, Magiclysm and AFS+Magiclysm:
There definitely is a significant difference in special spawns with AFS, Magiclysm is not significantyl different apart from the Military Base (this might just be an artefact of the smallish sample size, but they have trouble spawning in vanilla already).

| Special | Control (n=275) | AFS (n=291) | Magiclysm (n=309) | AFS + Magiclysm (341) |
|---|---|---|---|---|
| Lab (+Anthill Lab) | 52 (19%) | 19 (6%) | 57 (18,4%) | 25 (7,3%) |       
| Prison (+Lab var.) | 64 (23%) | 22 (7,5%) | 45 (14,5%) | 26 (7,6%) |
| Island Prison | 7 (2,5%) | 24 (7,5%) | 6 (1,9%) | 17 (5%) |
| MilBase | 20 (7,3%) | 5 (1,7%) | 11 (3,5%) | 2 (0,6%) |
