### ISSUE TITLE
Biollante Issues

### ISSUE THREAD

**Issue by dwarfkoala** [CleverRaven/Cataclysm-DDA#5066]
A conversation on IRC led me to test the deadliness of Biollantes. By the time you consider tackling a Biollante, you're probably well equipped to kill it easily, but there are a couple things that feel kinda weird about it.
1. They're incredibly accurate.
   They may be more accurate than a turret, in fact. I debugged a character with 105 dodge and from 7 spaces from it he hit me 7/10 times.
2. They're incredibly good at targeting
   Every single time the biollante bud hit me, without fail it hit my torso. It took about 3-4 damage from my torso every time it hit, and my 105 dodge character quickly succumbed to deadly sap bullets.
3. The sap bullets may or may not work as intended. 
   They did apply a nasty sap disease to me which made my speed drop like a rock, but they also damaged my torso and ripped my clothing. unless this is crazy corrosive acid sap, i'm not sure this is intended.
##

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
