### ISSUE TITLE
Dry ingredients from "frozen_ingredients" have more calories than from non-frozen

### ISSUE THREAD

**Issue by Secret-Cisco** [CleverRaven/Cataclysm-DDA#50744]
### Describe the bug

Most dry recipes have a normal suffixed "frozen_ingredients" version that takes slightly longer to make and requires a dehydrator/smoke like normal plus an additional heat source. The "frozen_ingredients" version's results almost always have more calories (~30% more) despite being made from the same ingredients. (Not dehydrated tofu or milk though)

If you go into the JSON and delete the heat part of the frozen version the results will be the same caloric value in game now.

The result actually does have more calories BUT only if actually crafted from frozen ingredients. If you craft it using **Debug Hammerspace** it has the same calories. The results are (hot) either way.

### Steps To Reproduce

1. Look at dry recipes in game
2. See that they are different

1a. Delete the heating requirement from the frozen version
2a. Look again
3a. They're the same now?

1. Put a corn kernel in a freezer
2. wait several hours for it to freeze
3. dehydrate it with the frozen recipe (no hammerspace)
4. dehydrate normal kernel with normal recipe
5. the frozen one has more calories

### Expected behavior

They should be the same, it's exactly the same ingredient.

### Screenshots

normal:
![image](https://user-images.githubusercontent.com/77130566/129355999-1429ef91-9a25-4962-b06a-80fac72a651f.png)
frozen:
![image](https://user-images.githubusercontent.com/77130566/129356128-34f5ab23-f8ce-4988-83f0-18b795a60299.png)

real cooked from frozen:
![image](https://user-images.githubusercontent.com/77130566/129358068-f08fdec5-988d-4cb4-951d-195a1c06c7bf.png)
cheat debug cooked from frozen:
![image](https://user-images.githubusercontent.com/77130566/129358220-2a3d0444-c32b-4d74-a7f3-69f3a3da47ff.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: ecc6a8f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by jbytheway** [comment]
I suspect this is due to the fact that heating makes the game think this is a cooking recipes, and this that the result is no longer raw food, removing the raw food calorie penalty.

Easy fix would probably be to mark this recipe with the NUTRIENT_OVERRIDE flag, but I'm wondering whether that might not work of the result is still considered not raw.

Alternatively, we might need a new recipe flag to mean "even though it involves hearing, this recipe is not cooking".

**Comment by RenechCDDA** [comment]
Last resolved by https://github.com/CleverRaven/Cataclysm-DDA/pull/65439 although calorie inheritance has been a sporadic problem since this issue was posted.

If this issue should come up in future searches, recipe::hot_result basically just checks if a hotplate is used anywhere in the recipe. If so, the result is heated up and regains the extra calories. (The other side of the check is removes_raw, which compares the components and result to see if the RAW flag is still around.)

I don't think smokers should necessarily count for cooking foods (i.e. outside of the removes_raw) check but if future contributors all agree that's a good idea just slap their itype into recipe::hot_result
