### ISSUE TITLE
Shocker Zombie teleporting

### ISSUE THREAD

**Issue by stelscarrot** [CleverRaven/Cataclysm-DDA#50782]
### Describe the bug

While exploring the lab zombie appears to be teleporting or going through the closed door.
There are a video with all gameplay from encountering it the first time and anything I done before second time. Has to be mentioned, that in the room with two stairs that I used on 7:12 also goes to closed empty room. I hasn't included it on the video because it is a long time before and after I enter there, so by doing so I would have a video with size I can't upload, or it would be spliced, which wouldn't give much of info, but I attached the screenshot of the room. The only teleport is inside this room, and outside there are no means of zombie getting inside it.
It is months in game's time from now that I encountered this, so don't know if there are any info from save that could help, but could share it if needed.

Video: https://youtu.be/4WWuk-1oLwU
0:11 - room below
0:38 - encounter 1
19:50 - encounter 2
23:20 - room above

### Steps To Reproduce

1. Play the game
2. Encounter Shocker Zombie
3. Close the doors

### Expected behavior

Zombies not performing magic trics with moving through solid objects.

### Screenshots

![image](https://user-images.githubusercontent.com/88937756/129451034-28467837-57c9-4def-ac90-d8783c027039.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 (version unknown because windows installed update when I wasn't looking)
- Game Version: 7fec2ef [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by ZhilkinSerg** [comment]
Teleport traps maybe?

**Comment by stelscarrot** [comment]
> Teleport traps maybe?

There was none that could teleport him out there. And the one on screenshot was isolated by closed door. I already explored whole lab, there was no way to zombie to gone this stairs on 19:50.

**Comment by hexagonrecursion** [comment]
Possibly related https://github.com/CleverRaven/Cataclysm-DDA/issues/49787

**Comment by Xindage** [comment]
i'm gonna mentioned that i have already gave up in a save because an iteration similar to that, first ive noticed a dead strong zombie in a migo cage (lab run) them after i revisited that room later he was alive and outside the cell, no idea how he did it thought the glass but i ignored, but after staying almost a week on the last floor of the lab doing armors and reading books, ive noticed that lag increased with the time and after i revisited that floor that had fungal they complete take over all the rooms of that floor, even with doors closed, not sure if it was because spores blowing near walls that caused them to go over doors/wall but now that you mentioned teleporting, this could be the cause. (stable 0.F-2)

**Comment by eltank** [comment]
It's hard to tell what's going on when there's no save file provided, but the "Wandering hordes" option can allow monsters to teleport through doors when they're outside of the reality bubble, so I'd ask whether that option was turned on or not.

**Comment by stelscarrot** [comment]
> It's hard to tell what's going on when there's no save file provided, but the "Wandering hordes" option can allow monsters to teleport through doors when they're outside of the reality bubble, so I'd ask whether that option was turned on or not.

Default settings, so off.

**Comment by eltank** [comment]
Looking at the footage again, it's quite likely that this is the same teleporting bug as #49787, which I just wrote a fix for.

In this image you can see that there's another stairwell up within a 12-tile radius of the one you took. I believe the shocker teleported there because of the wonky stair-finding algorithm.
![image](https://user-images.githubusercontent.com/8000047/133030144-f7753078-6d34-4520-8d06-74c7dfaa8f73.png)

**Comment by hexagonrecursion** [comment]
Sounds like the code that processes NPC and monster movement is separate from the code that implements the rules of movement for the player. Would it make sense to unify them? code reuse -> less code -> less bugs

**Comment by eltank** [comment]
> Sounds like the code that processes NPC and monster movement is separate from the code that implements the rules of movement for the player. Would it make sense to unify them? code reuse -> less code -> less bugs

That makes sense, sure. Unfortunately in practice it's not that easy. Take a look at `game::find_or_make_stairs` and you'll see plenty of special cases that apply only to the player (such as placing rope ladders or taking elevators).
There is something I can do to make the tile search order equivalent (so both npcs and avatar will always land on the same connecting stairwell) and I'll probably do that after the current round of code cleanup that I'm working on.
