### ISSUE TITLE
Nested Pockets Do Not Respect Whitelist

### ISSUE THREAD

**Issue by RockNShoulders** [CleverRaven/Cataclysm-DDA#50801]
### Describe the bug

Whitelisting items has no effect on what gets placed where inside of a pocket.

### Steps To Reproduce

1. Pick a survivor belt.
2. Drop all other items with pockets.
3. Assign whitelist to the various pockets in the survivor belt.
4. Pick up items on the whitelist.

### Expected behavior

Only items whitelisted appear in the appropriate pocket, nothing else. Items are placed in the appropriate pocket based on whitelist.

### Screenshots

![Untitled](https://user-images.githubusercontent.com/88957626/129467312-65fac49b-b824-4d84-9aa2-93fe0accdfb5.jpg)

### Versions and configuration

- OS: Win 10
- Game Version: 2021-08-14-2036
- Graphics version: Tiles
- Ingame language: English

### Additional context

Should have been resolved in https://github.com/CleverRaven/Cataclysm-DDA/issues/45449

**Comment by mqrause** [comment]
I can't reproduce non-whitelisted items going into a pocket, that works as expected. Manual insertion into the container can bypass this, because it assumes you want to bypass it.
As for the second issue, a whitelist by itself is not a priority setting. You need to also increase priority to make whitelisted items prefer that pocket. Though that's something that could be changed.

**Comment by DalenTalas** [comment]
> I can't reproduce non-whitelisted items going into a pocket, that works as expected. Manual insertion into the container can bypass this, because it assumes you want to bypass it.

The behavior I expect in this case is for the insertion to respect the white- / blacklists. I want the medkit in the specific pocket of the backpack, dammit.

**Comment by mqrause** [comment]
> The behavior I expect in this case is for the insertion to respect the white- / blacklists. I want the medkit in the specific pocket of the backpack, dammit.

I think the better fix for that would be to allow pocket selection when inserting items.

**Comment by RockNShoulders** [comment]
Here's a link to me reproducing the problem step by step. To break it down, pockets do not function as intended based on my testing. Related to issue https://discord.com/channels/598523535169945603/598535827169083403/876331559895052298
1. Picking up items without priority leads to random placement.
2. Picking up items with priority works as intended but leads to another problem (see the other ticket)
3. Inserting items leads to all kinds of random results and does not respect whitelist. I don't think this should be intended behavior.

**Comment by mqrause** [comment]
Regarding the picking up in your video, like I said, a whitelist is not a priority. Put a high priority on pockets with whitelists and it works like you would expect.
Everything else looks perfectly normal to me. The scalpel goes where it should and the whitelist excludes all other items from going there. Since that is the only regular pocket - the other ones all require items to clip onto a belt loop which mostly just tools do (compare multitool to mp3 player) - there is no valid pocket available for the other items, which is why you're asked to wield them.

As for inserting, pocket settings are for automatic assignment of pockets. Insertion is not (supposed to be) an automatic assignment, it's you specifically deciding to put an item in a specific place, hence it ignores settings. But like I said before, it's lacking the ability to choose the actual pocket to put it into.

**Comment by RockNShoulders** [comment]
Yup, you're right. I suppose the majority of the problem is the confusing nature of how the game sorts through inventory automatically versus manual insertion. I would say that inserting items to have it ignore whitelist, as you have no way to assign which pocket to put it in, is not an intended behavior
