### ISSUE TITLE
Walking diagonally in the presence of turrets at dusk is a death sentence.

### ISSUE THREAD

**Issue by ifffrt** [CleverRaven/Cataclysm-DDA#50833]
### Describe the bug

For some godawful reason walking diagonally at the time when it was starting to get dark but wasn't quite fully night yet will let turrets see you immediately from as far as 50 squares away. Walking in cardinal directions have no issues whatsoever. 

Also, passing time with Shift-\\ while in range of the turret for some reason also lets it see you like you were walking diagonally.

This issue was encountered during full moon. I haven't tested it during other moon phases.

### Steps To Reproduce

1. Make a new world starting at full moon (2 weeks into the season) and almost night. Or alternatively download the attached save file. [Mortonsville.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6990322/Mortonsville.zip)
2. Pass time until 9:30 PM.
3. Give yourself debug invincibility.
4. Spawn a M2HB turret around 50 squares away.
5. Try to walk directly towards it using left, right, up or down arrow key. See no issues.
6. Try to walk _away_ from it using diagonal keys. Immediately get spotted.

### Expected behavior

Not dying.

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: ee0b7b6 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Graphical Overmap [Graphical_Overmap]
]

**Comment by Fris0uman** [comment]
Because diagonals are longer, turn off "circular distances" if you want all direction to be the same. This is not a bug

**Comment by ifffrt** [comment]
How much longer? I was getting shot at at 50 squares away while walking diagonally, while walking 10 squares from the turrets in cardinal directions does not give this result.

**Comment by Pseudogeist** [comment]
Turrets can't track you if it's dark and you're moving fast enough? I doubt that's intended behavior. Even if it is this is a clear oversight as circular distances is ensuring that diagonals are _equal_, not _shorter_ methods for getting from A to B. If turrets are meant to spot slow moving targets in the dark then they need to account for circular distances.

**Comment by Fris0uman** [comment]
OP said that waiting get them killed too, so I think it's just that it takes time for the turret to shoot and when they move diagonally it takes more time than moving straight.

**Comment by ifffrt** [comment]
> 
> 
> OP said that waiting get them killed too, so I think it's just that it takes time for the turret to shoot and when they move diagonally it takes more time than moving straight.

Only when passing time using the "\" key. Passing time using "." key is completely safe.

**Comment by Fris0uman** [comment]
Did you go prone by pressing " which then made you move at snail speed?

**Comment by ifffrt** [comment]
No.

**Comment by Fris0uman** [comment]
\ is the haul key it doesn't pass time though

**Comment by ifffrt** [comment]
It was Shift-\. I'm playing using key code input mode.

**Comment by Pseudogeist** [comment]
Well, trying to reproduce I've not had any success. Do you know which turret it was? I might have found another bug where if you stand just outside targeting range the turret (M249 CROWS) otherwise non-targets (at least, giant ants) become valid (if they're next to you and in range). It might be a bit broader than that, I'm not sure yet.

**Comment by ifffrt** [comment]
> 
> 
> Well, trying to reproduce I've not had any success. Do you know which turret it was? I might have found another bug where if you stand just outside targeting range the turret (M249 CROWS) otherwise non-targets (at least, giant ants) become valid (if they're next to you and in range). It might be a bit broader than that, I'm not sure yet.

It was the M2HB turret. You could use the save file I provided. It was build 2021-08-15-0301.

**Comment by actual-nh** [comment]
#50497 - related?

**Comment by Pseudogeist** [comment]
Interesting. Yeah, I booted up your save, and indeed this is the case. It could very well be #50497 related. I expect they have <100 move cost, too. It's really odd; I tried spawning a broken bot to wield and yep, I was spotted by the turret, but it's temperamental. It keeps losing track every few turns, even at <120 move cost. Also, it appears it's targeting without seeing. I'm not sure exactly how the turret is detecting the avatar.

Thought I'd test a little more before hitting send: Detection happens when two seconds tick by between your move. If that happens you are detected on the first second, fired at on the second. Therefore, if you have at least 101 move, this will trigger eventually. I debugged in a few soldier ants to test my hypothesis, and yes, it seems that during these two seconds the creature doesn't become omniscient they suddenly see as if it were daytime. I'm using a curses build atm so I can't test with the light overlay, though even if everything suddenly is lit up I doubt the overlay would reflect that. I suspect something in #50068 borked a little.

**Comment by ZhilkinSerg** [comment]
> 
> 
> How much longer?

diagonals are square root of two (~`1.414`) longer.

> I was getting shot at at 50 squares away while walking diagonally, while walking 15 squares from the turrets in cardinal directions does not give this result.

I guess you have been shot at a different tile and at different time, so there are other things to consider besides movement direction - light levels, sight obstruction, etc.

**Comment by Pseudogeist** [comment]
> 
> I guess you have been shot at a different tile and at different time, so there are other things to consider besides movement direction - light levels, sight obstruction, etc.

The only factor is time. Within a certain period of the day (presumably every day) if you pass two seconds (possibly just two, probably more) during a single move then monsters will have visibility as if it were daylight. Walking diagonally stands a far greater chance of triggering this if you use speedydex as you're far less likely to have a move cost above 100 any other way. Without this you may simply put your death down to user error.

**Comment by RenechCDDA** [comment]
I grabbed b781a0e1148674381cebb63569759f1b5e7cd626 which was before the sunrise changes. The issue occurs in that build as well. Cardinal direction moving: no detection. Diagonal movement: Shot about 40% of the time, "Hostile detected."(no further action) about 40% of the time, nothing about 20% of the time.

**Comment by actual-nh** [comment]
@Hillanoko, @jbytheway - any thoughts re this dusk thing?

Pseudogeist: BTW, not my save (just referring to it). I've been looking at the code re light levels, vision, etc quite a bit recently. I was thinking it might have something to do with updates to lighting caches possibly not being in sync - one way to be very visible is if there's light on you that's more than on the surroundings - but I haven't been able to find anything.

**Comment by RenechCDDA** [comment]
I modified the json of the turret locally to see if it was time-based.

Setting the `targeting_cost` to an arbitrarily large value (2000) produces lots of "Hostile detected" (should mean targeting succeeded) but not a single shot. Only happens when moving diagonally. Never detected moving in cardinal directions.

Setting the `targeting_cost` *and* `move_cost` to a minimum value (1), as well as setting the turret's `speed` to 1000. This still results in getting detected **ONLY** when moving diagonally. And of course, you do still get shot at. But not... every turn. In fact, the amount of getting shot at seems to be the same.

I don't think it's time-based...

I'm aware that there is a special return fire function for when the turret is *damaged*, is there one for shooting at unseen targets that it literally shouldn't be able to detect?

**Comment by actual-nh** [comment]
The question then is whether the zombies are a different thing that possibly _is_ time or light-level based (maybe related to #43479), or if movement directions make a difference there. What time of day was this? Did you check at different light levels? IIRC, in-game turrets don't have IR targeting, but I may be incorrect on that; will try to check later on - need to get some work done...

**Comment by Saicchi** [comment]
Have you tried checking the light map to see if you were on a tile with enough light for a turret to see? iirc the threshold is 2.2, where the tile shows up as very dark but you can still be seen from afar with their day vision range.

**Comment by Pseudogeist** [comment]
> 
> 
> Have you tried checking the light map to see if you were on a tile with enough light for a turret to see? iirc the threshold is 2.2, where the tile shows up as very dark but you can still be seen from afar with their day vision range.

Checked the light map, it's reading 7.7. The effect ends at 7.0, and applies all the way through to 10.9. Even so, if turrets etc _should_ be capable of seeing you with this light level, they only do so if you spend more than two seconds performing, be it moving or picking up an item or using long wait. Butchery and reading have the same effect, so I assume any activity would. This is also why you can pass turns safely, but if your move cost goes over 100 then you're at risk. So far, it _only_ occurs when time has ticked over by two seconds.

> 
> 
> I modified the json of the turret locally to see if it was time-based.
> 
> Setting the `targeting_cost` to an arbitrarily large value (2000) produces lots of "Hostile detected" (should mean targeting succeeded) but not a single shot. Only happens when moving diagonally. Never detected moving in cardinal directions.
> 
> Setting the `targeting_cost` _and_ `move_cost` to a minimum value (1), as well as setting the turret's `speed` to 1000. This still results in getting detected **ONLY** when moving diagonally. (No detections at all when moving in cardinal directions) And of course, you do still get shot at. But not... every turn. In fact, the amount of getting shot at seems to be the same.
> 
> I don't think it's time-based...
> 
> I'm aware that there is a special return fire function for when the turret is _damaged_, is there one for shooting at unseen targets that it literally shouldn't be able to detect?

Well, the turrets themselves are terribly unlikely to be the issue as this applies to every monster. NPCs can detect you too. It's avatar only, a monster or NPC moving slower isn't visible to other entities if they travel slowly. It's _definitely_ based on time, the time it takes you perform an action, and it only occurs between certain light levels. The sight range of the creature does not respect the light level and instead seems to see as if it were broad daylight. I'm surprised that 1000 speed behaved like that but at first glance it sounds like a potential bug in monster move/attack code.

> 
> 
> I grabbed [b781a0e](https://github.com/CleverRaven/Cataclysm-DDA/commit/b781a0e1148674381cebb63569759f1b5e7cd626) which was before the sunrise changes. The issue occurs in that build as well. Cardinal direction moving: no detection. Diagonal movement: Shot about 40% of the time, "Hostile detected."(no further action) about 40% of the time, nothing about 20% of the time.

That's a pity. It would have been nice if it was. :( Thanks, I can stop giving myself brain hernias now.



> 
> 
> @Hillanoko, @jbytheway - any thoughts re this dusk thing?
> 
> Pseudogeist: BTW, not my save (just referring to it). I've been looking at the code re light levels, vision, etc quite a bit recently. I was thinking it might have something to do with updates to lighting caches possibly not being in sync - one way to be very visible is if there's light on you that's more than on the surroundings - but I haven't been able to find anything.

Nice thought, I'm not familiar with much code in CDDA yet to really speculate (I'm getting there). Considering we have a nice, even cut off at 7,0 I'm going to run a search on the repo and see if there's any magic happening that relates to vision at this level.

I'm pretty certain #50497 is the same issue. As for #43479 I'm not sure, the fact that the shady zombie is flagged as seeing the avatar makes me dubious. It gave me the idea to test cloudy weather, and indeed, the bug is still present within those ranges, the weather itself doesn't make a difference. Ambient light >7.0 <11.0 is treated as full daylight for seeing the avatar if two seconds or more tick past. That code you pasted may well be the key - I'll check it out, nice one!

**Comment by Pseudogeist** [comment]
Thanks to @actual-nh I've narrowed it down. You can prevent the bug by turning off skip_lightmap on line 968 of do_turn, but there's a reason that's set to true. Anyway, this tells us that it's lightmap related. I was wrong about the 7.0f, too, as further weather testing pointed out and my suspicions after revisiting calendar.cpp. Indeed, this issue likely wasn't caused by #50068 but I was on the right track. The issue appears to be that any function which checks light level in a tile exposed to sunlight will do so very accurately, and so any comparison against the cached lightmap is saying that the tile is lighter than the surroundings. I expect the inverse is also true, so theoretically you could sleep out on the street at midnight and not be seen by any monsters or NPCs for a while after the sun comes up, depending on how and when the cache gets updated.

This problem could be masked by averaging out the difference between the cache and the natural lighting, which would have the bonus that somebody smoking a cigarette wouldn't be immediately obvious to everyone until there was a significant difference between the ambient light and the light emitted by the burning cigarette. This would be nice regardless, but it wouldn't solve the underlying issue and might resurface at some other point and become that much harder to isolate. An elegant implementation of the visibility of light sources at different ambient lighting would probably require more than a simple averaging like `here.ambient_light_at( t ) / g->natural_light_level( t.z ) > 1.01`. That _does_ stop turrets from seeing you based on your move speed, but it also makes smoking completely fine. Lighting a cigarette isn't, which I'm happy about as I didn't realize that was a feature. Lighters do give off a sight more light than cigarettes after all.

I've still not caught the exact caching issue that's causing this behaviour as it's an interaction between a headache-inducing mix of moving parts across multiple source files, including my nemesis calendar.cpp with its' trajectories and cosines such. For anyone following this line 353 in creature.cpp is making the avatar visible as here.ambient_light_at(t) is pulling from the cache which is far too often out of sync with sunlight calculations.

**Comment by jbytheway** [comment]
I don't think we ever compare the light level in a tile with that of its surroundings to determine how visible it is.  This sounds like it's just the lightmap cache being wrong?  Which is not surprising.  It seems like most of our pernicious bugs are always cache-related.

**Comment by Pseudogeist** [comment]
> 
> 
> I don't think we ever compare the light level in a tile with that of its surroundings to determine how visible it is. This sounds like it's just the lightmap cache being wrong? Which is not surprising. It seems like most of our pernicious bugs are always cache-related.

I didn't mean comparing with neighbouring tiles but comparing against ambient light... Which, indoors, would be different I suppose. Most ambient light would only apply at openings I guess and would otherwise be very dark. I don't recall how ambient light is calculated. Distances indoors would be such that you would almost certainly spot someone smoking if they were in there with you unless it was a mall or warehouse or something, which is pretty much a fringe case and could be handled by degrading light emission. It should be handled by that already though... I'll have to test and see whether turrets can spot you at night from a cigarette at close to max distance, I don't believe they should. From what I remember of the code I think a monster may very well spot you from that distance.

Anyway, this bug is definitely due to lightmap cache being wrong. I suspect that the avatar's tile isn't being updated during activities but I couldn't find the root cause so that's merely speculation. I'm a fairly burned out on it and I'm familiarizing myself with all the code so it's slow going.

**Comment by Menschheit** [comment]
Normal movements do update lightmap, so we can assume that the lightmap isn't updated elsewhere (otherwise there would be no issue). At 9:30, it will be darker and darker over time(until reaching curtain level), if the cache is not updated it literally makes every tile "illuminated" compared to natural light level.
![image](https://user-images.githubusercontent.com/28317565/129760872-062a1f04-c6b2-4be2-8cbe-2367a8564b9e.png)
since ambient_light_at checks cache but natural_light_level is real-time

**Comment by Pseudogeist** [comment]
Oh right, I should have thought to check the movement code, too. So, given all the parts in play, it looks to me like the best solution would be to update the cache whenever the natural_light_level changes, which is all the time when the sun is up. Welp, I'll give it a go and hope the overhead isn't too high.
