### ISSUE TITLE
Making lard also made cracklins?

### ISSUE THREAD

**Issue by angryisosceles** [CleverRaven/Cataclysm-DDA#50874]
### Describe the bug

I made a batch of lard, and it also produced a batch of cracklins of equivalent size.

### Steps To Reproduce

- Cook lard. If it matters, I made a batch of 3 on a counter, using a mess kit.

### Expected behavior

I did not expect to also make cracklins. 

### Screenshots

![bonusCracklins](https://user-images.githubusercontent.com/51832925/129953079-582d89d9-d662-496c-a5cb-b245818c8541.PNG)

### Versions and configuration

- OS: Windows 10
- Game Version: e055bd1
- Graphics version: Tiles
- Ingame language: English
- Mods loaded: Default

**Comment by Xpyder** [comment]
I believe when you look at the recipe it says it also produces cracklins as a side effect.

Essentially what you're doing is rendering the fat and removing impurities which float or sink, which since they're edible are the "cracklins".

you can see similar effects when making Fruit Juice (you also get pulp back)

**Comment by KanterDev** [comment]
Cracklins are a by-product of rendering pork fat for lard.

https://www.youtube.com/watch?v=V3-CVLJkMyU&t=209s
