### ISSUE TITLE
Prioritize content description over container description

### ISSUE THREAD

**Issue by Entity-y** [CleverRaven/Cataclysm-DDA#50887]
# Is your feature request related to a problem? Please describe.
Currently, when looking at the description of a container it will show information about the container first and then the description of the contents last.

Whenever I go to read the description of a container I care only about what's inside of it. To get this information I need to scroll all the way down the page when it should be available at a glance.

# Describe the solution you'd like
Reorder the description of contents to be shown first and the description of the container to be last.

**Comment by chrispikula** [comment]
I think having the Home/End key go to the top or bottom would be a better solution.

**Comment by Entity-y** [comment]
While that would be a complementive feature, it would still be more key presses than I'd like and will likely still require me to scroll through the description to get the info I seek.

**Comment by chrispikula** [comment]
It's just that I don't want to see a listing of my ammo first when I look at a gun.  Or batteries in electronics.

**Comment by Entity-y** [comment]
That wouldn't be ideal, I agree. Certain exclusions would have to be made.

I'm mainly talking about nested containers, before nested containers it displayed the contents right at the top of the description. For example a gallon of milk showed the description of the milk first and then the description of the gallon jug.

**Comment by Qrox** [comment]
We can add a new key to the item info menu to inspect contents. I think you can already tell the item info function what info should be printed, so that would be relatively easy.

**Comment by Entity-y** [comment]
I wouldn't mind that, a new key would go in hand with another idea.

Having a key dedicated to inspecting and opening containers such as a wallet or backpack. This would allow for quick and easy access to the contents and could make use of the nested inventory view that's already available on the inventory screen, without the overwhelming presence of the rest of one's inventory.

**Comment by ZeroInternalReflection** [comment]
I'm currently experimenting with some changes to the inventory ui so I figured I'd try out Qrox's idea for a new key to inspect contents.
![Inventory_Keybindings](https://user-images.githubusercontent.com/89038572/130300605-79f41e13-09b6-4b0f-b7f8-94de5e59a046.png)

What I'm currently trying to do with it is:

1. If selected item has no contents, identical to 'e'xamining
2. If selected item has other items inside, loop through them and show the information on each of the items inside

I'm still working on items with multiple things inside (e.g. wallets) and how to present them, but the single-item behaviour seems promising:
![Examine_Contents_Of_Cola](https://user-images.githubusercontent.com/89038572/130300884-9466865a-bead-4f88-ab0a-2d65397944d6.png)

Thoughts?

**Comment by Entity-y** [comment]
So far I like where this is going. Does this only work while inside the inventory menu or will the inspect contents key still function outside the menu?

**Comment by chrispikula** [comment]
It'd be complicated, but what about if there's multiple items, having an up-down arrow selection?  Sort of like the inventory, with < and > arrows to show what's in what (for nested pockets), with highlighting (as per inventory.)

**Comment by ZeroInternalReflection** [comment]
@Entity-y : The way I've currently got it set up, there's a new function item::detailed_contents_info() to collect the information, and I've modified inventory_selector::action_examine() to display it.  So, any menu derived from inventory_selector ('i'nventory, 'd'rop, 'W'ear, 'w'ield, multiclean, etc.) has access to it.  Notably, the 'g'et menu and advanced inventory menu do not have access with this implementation.  The advanced inventory menu should be fairly easy to add (even if copying and pasting the relevant function isn't particularly elegant).  The 'g'et menu looks more complicated, but merging all of that in to inventory_selector is already a longer-term goal.

@chrispikula : I agree that a selection system like that would make sense.  Currently, items with lots of stuff inside are a bit unwieldy:
![Wallet_Contents_TMI](https://user-images.githubusercontent.com/89038572/130330048-a61b4ff1-6df4-4b34-a348-f6e679168690.png)
I'd favour a simple list:
![Wallet_Contents_List](https://user-images.githubusercontent.com/89038572/130330074-f6733601-4023-4e2f-986d-a8e7e39d7f82.png)
with the selected item highlighted and providing the full details.  However, I'm going to need to spend some time familiarizing myself with the window creation system before I could get it to work like that.

Does cataclysm have any ui-focused testing that I should be updating as I work on this?

**Comment by ZeroInternalReflection** [comment]
@Brambor 
If you're envisioning the right panel being a scrollable sequence of:
1. Detailed information on primary result (Contents of the resulting item if it's, e.g. a canned/jarred item)
2. Divider
3. Detailed information on container used if applicable
4. Divider
5. Detailed information on byproducts
Then I'm not entirely convinced yet, but I'll look into it.

**Comment by Brambor** [comment]
@ZeroInternalReflection If you had better idea it would be amazing, however adding another list you have to scroll... Well, as you said, there is too much scrolling already.

It is true, it's not optimal. But it is exactly as I envision 😀.

**Comment by ZeroInternalReflection** [comment]
> @ZeroInternalReflection If you had a better idea it would be amazing, however adding another list you have to scroll... Well, as you said, there is too much scrolling already.
> 
> It is true, it's not optimal. But it is exactly as I envision grinning.

Well, @Brambor , I finally got around to testing out your idea.  I ended up adding a summary at the top so it's obvious that you can scroll down for more information, but otherwise I like it a lot more than I thought I would.

It currently produces a header for everything, even things without byproducts/containers.  It's not particularly useful in this case, and could probably be removed:
![Normal_recipe](https://user-images.githubusercontent.com/89038572/132724080-f02df710-23f4-4560-9f08-634217d85a7f.png)

But when you have a recipe with byproducts or that's in a container:
![Result_in_container](https://user-images.githubusercontent.com/89038572/132724135-dfde32c4-35bb-4207-a707-be8918c6dfba.png)
![Result_with_byproducts](https://user-images.githubusercontent.com/89038572/132724143-d4e8b171-86fa-4f49-8829-0c516b519ae6.png)
It starts to look pretty handy.   It also works if you have both:
![Result_in_container_with_byproducts](https://user-images.githubusercontent.com/89038572/132724263-d0b9583c-af04-41b6-abab-9941a3460c10.png)

I'm a little torn on whether the "container" information should be for "3L Glass Jar" or "3L Glass Jar > Canned Beans".  I think there are arguments for either approach.
I'd also like to differentiate between byproducts (e.g. cracklins with lard) and catalysts (for lack of a better term. e.g. molds that can be reused, water that the cans are boiled in), but I think that'll be a bit more complicated.
There might also be something odd going on in my calculation of liquid quantities.

Are there any complicated edge-case recipes I should be testing out (e.g. recipes with multiple byproducts, things with multiple catalysts)?

**Comment by Brambor** [comment]
@ZeroInternalReflection Amazing! This will clear a lot of frustration when canning that's currently present.

Regarding testing, as someone pointed out, if there are weird recipes, somebody will find out and make a bug report.

Other than that, if you think is ready, I would like to see it in the game ;)

**Comment by ZeroInternalReflection** [comment]
Both #51252  and #51496 have now been merged.  I think together they address all of the specific concerns raised in this issue.  Are there any further comments on this one @Entity-y, or can the issue be closed?
