### ISSUE TITLE
Autolearn recipe requirements

### ISSUE THREAD

**Issue by Menschheit** [CleverRaven/Cataclysm-DDA#51026]
### Describe the bug

While checking if an autolearn recipe can be learned, knowledge level is used for primary skill, but for secondary skills ("skill required") the practical level is used.
![image](https://user-images.githubusercontent.com/28317565/130459689-31891f9d-475d-437e-9e6c-2cbc220efef2.png)
Here in `theoretical_recipe_requirements`.
The function  `compare_skill_requirements` always checks practical level.
I don't know whether it is intended or not, but the inconsistency between primary skill and secondary skills looks weird.

### Steps To Reproduce

Survivor suit recipe can only be learned if practical fabrication level >=6 (and with enough tailoring knowledge of course).

### Expected behavior

Survivor suit recipe can be learned if the player have enough knowledge level of tailoring and fabrication.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 8ab3e72 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by hexagonrecursion** [comment]
I am observing something strange. After reading from 0/0 to fab6/tailor6 I did autolearn some recipes, but not others. I did not autolearn the survivor suit recipe (6/6). I did autolearn the survivor belt recipe (tailor6/fab3). Saving and loading resulted in autolearning the survivor suit recipe.

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: f50b6be [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]


Calls `get_knowledge_level()`

https://github.com/CleverRaven/Cataclysm-DDA/blob/2eb4ed3a68700525ba9eb07a44ba171d5e72808d/src/skill.cpp#L501-L509

Calls `get_skill_level()`

https://github.com/CleverRaven/Cataclysm-DDA/blob/2eb4ed3a68700525ba9eb07a44ba171d5e72808d/src/skill.cpp#L471-L490

**Comment by eltank** [comment]
Fix is on the way.

**Comment by eltank** [comment]
I think `SkillLevelMap::theoretical_recipe_requirements` is a red herring, although it does need fixing.
The real problem is in `character_crafting.cpp`
```
const recipe_subset &Character::get_learned_recipes() const
{
    // Cache validity check
    if( *_skills != *valid_autolearn_skills ) {
```
The equality check there eventually delegates to `SkillLevel::operator==`, which is implemented in terms of practical level and xp, completely not what we want.

**Comment by eltank** [comment]
To clarify further, the bug is not as described in the OP (that autolearn uses practical rather than knowledge levels), but rather the second post. Training the tailor/fab knowledge levels up to 6/6 via reading books does satisfy the autolearn requirements for the survivor suit, but you can't see it in your recipe list without a save/load cycle due to a caching bug.
