### ISSUE TITLE
Ranged Test Suite has more random failures after weak points implemented

### ISSUE THREAD

**Issue by Maleclypse** [CleverRaven/Cataclysm-DDA#51396]
### Describe the bug

I've had to restart a couple of tests for archery and now shotgun failed tests.   My assumption is that sometimes the armored dps is off from the expectation because of weak points in the test monsters armor now.   

### Steps To Reproduce

Make a PR unrelated to ranged weapons.   See more than usual ranged weapon test fails.

### Expected behavior

Tests to throw less false positives.

### Versions and configuration

Literally the current master :)

**Comment by Maleclypse** [comment]
It is entirely possible this is a coincidence that I am attributing to a pattern.

**Comment by Joshua-Chin** [comment]
The archery damage test doesn't reference the debug monster, and armored DPS is calculated from a zombie soldier. Do you have a log for the exact failure?

As a side note, the "Best DPS" does use the debug monster. The recent changes don't cause any bugs, because it weakpoints only effect bullet damage. However, we should probably create a separate monster that's only used for "Best DPS" calculations

**Comment by Joshua-Chin** [comment]
@Maleclypse Are you still experiencing an increase in random failures?

**Comment by Joshua-Chin** [comment]
Looks like it was a coincidence. Please reopen if you are still experiencing this issue.
