### ISSUE TITLE
Issues loading smoking racks and forges

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#51422]
### Describe the bug

There's a couple different issues:

1. Both the smoking rack and the rock forge can hold thousands of units of charcoal, often far more than the player can carry. However, they can only be loaded from the player inventory as opposed to the surroundings. 
2. When you try to load them, first, you are prompted to unload what exists in them, as opposed to being able to just add to the partial load already in existence. 

These two issues together mean that to fully load one you have to pick up all the charcoal you can, insert it, pick up the next load, attempt to insert it, say you don't want to unload, and repeat until you have filled it enough or given it up in favor of electric dehydration.

### Steps To Reproduce

Try to load charcoal into a rock forge, see how irritating it is.

### Expected behavior

I would expect that you could load it from any charcoal in the area, and if it was partially loaded, that it would simply accept enough to be fully loaded in a single action.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: bc28921 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    No Rail Stations [No_Rail_Stations],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    No Fungal Monsters [No_Fungi],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by PatrikLundell** [comment]
I agree it's mildly annoying, but not more than that.

The technical reason is probably that you load the smoking rack as an interaction with the rack rather than an interaction with the tile. Compare that to the charcoal kiln, where you have to interact with it to trigger it to make the product available, but once that's done you can just move the charcoal using AIM and reload the kiln with new raw material using the AIM as well.
The problem with the smoking rack is that it contains multiple "pockets", each of which have a limited size, as opposed to the kiln which only has a single compartment.

However, I wouldn't mind if the smoking rack got rid of the stupid question of whether you want to empty it of coal when trying to reload it. If I remember correctly, there's a separate action to remove the coal already, and if there isn't there ought to be.
