### ISSUE TITLE
Game crashes when putting pressure on bleeding wound.

### ISSUE THREAD

**Issue by Essnato** [CleverRaven/Cataclysm-DDA#51584]
### Describe the bug

The game crashes to desktop when I put pressure on a bleeding wound, this has happened 5 times, it only crashes when the tend would be successful.

### Steps To Reproduce

1. Bleed from any body part including torso and Head
2. Not be holding anything
3. Attempt to put pressure on bleeding wound
4. Repeat until game crashes

### Expected behavior

The bleeding should stop however the game just crashes

### Versions and configuration

Windows 10,
2a05224 (tiles)
English
Aftershock, StatsthroughKills, StatsthroughSkills, BlazeIndustries, GenericGuns, NoNPCneeds, moreBionicProffesions.

### Additional context

[Save and debug.log.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7152991/Save.and.debug.log.zip)
For some reason the crash.log file does not exist
also the save is called The Last Stand Of Everyone

**Comment by ferociousdork** [comment]
This is caused by a division by zero when the bleed effect runs out. Seems to be an unintended side-effect of #51374, which allows intensities to decay to zero (that 0 there used to be a 1):
https://github.com/CleverRaven/Cataclysm-DDA/blob/77f8f60808477a3dcaa1f7e3fdd67e3e1b0aa5b9/src/effect.cpp#L995

The actual division by zero happens here:
https://github.com/CleverRaven/Cataclysm-DDA/blob/77f8f60808477a3dcaa1f7e3fdd67e3e1b0aa5b9/src/player_hardcoded_effects.cpp#L257-L278

**Comment by Venera3** [comment]
Whoops! You can fix it locally in `effects.json`, add the line `"int_decay_remove": false` into the bleed effect. I'll put up a fix in a bit.
