### ISSUE TITLE
Raw edamame rots even as it doesn't show that it is perishable

### ISSUE THREAD

**Issue by atealein** [CleverRaven/Cataclysm-DDA#51594]
### Describe the bug

I had collected some raw edamame, which was not listed as a perishable item and did not have this information in its description either. Few ingame days later I noticed it now has an extra tag as (rotten). The item browser lists that the item spoils in three days, so I think something is missing from the current ingame tags to make the item color/font show it is perishable and fresh or not. 

### Steps To Reproduce

1. Get some raw edamame
2. Wait few days

### Expected behavior

I would expect it to have the light-blue color of the item name as perishable foods and to list in the tags that it is perishable item and how soon it will perish.

### Screenshots

![Screenshot from 2021-09-13 20-40-56](https://user-images.githubusercontent.com/25322782/133138838-544122de-6faa-4b62-a587-4552861a6147.png)
how it is listed compared to other perishable food

![Screenshot from 2021-09-13 20-40-38](https://user-images.githubusercontent.com/25322782/133138870-b6440f11-e83f-4f19-b03e-a95586e1bf6d.png)
the perishable information is missing from the item description

### Versions and configuration

Linux, experimental, version 20bf2de

**Comment by ferociousdork** [comment]
It's a comestible and defines `spoils_in`, which causes it to rot, but it's not considered food as it doesn't define a `comestible_type`. This suppresses the food info box:

https://github.com/CleverRaven/Cataclysm-DDA/blob/e341785f9c4f8ab20acd5c3f7989a4a9851b76ce/src/item.cpp#L4668-L4670

This also disallows eating, although the description implies you should be able to. The consume activity runs but does nothing, because of this `trinary::NONE` being returned (`consume_med` requires `comestible_type` `"MED"`, `eat` requires `comestible_type` `"FOOD"` or `"DRINK"`):

https://github.com/CleverRaven/Cataclysm-DDA/blob/e341785f9c4f8ab20acd5c3f7989a4a9851b76ce/src/consumption.cpp#L1789-L1797

I'd suggest adding `comestible_type` `"FOOD"` to the item. Maybe even disallow such configurations, or is there a valid use-case for leaving out `comestible_type`?

**Comment by atealein** [comment]
There is same problem with soybeans - it lists them under FOOD in inventory, the description states they can be also eaten raw, but they don't appear in the food eating menu at all. They also clearly have the "fresh" tag right now, which means they will be rotting away, but their description doesn't mentions when or that they are perishable.

![Screenshot from 2021-09-13 23-18-29](https://user-images.githubusercontent.com/25322782/133157789-3c19c127-9623-4fb5-b192-5ad1320886e4.png)

![Screenshot from 2021-09-13 23-20-06](https://user-images.githubusercontent.com/25322782/133157902-9ba88cb5-f265-423b-a65c-8e5ddb1f0410.png)

**Comment by RenechCDDA** [comment]
Yeah that's my fault, I was actually just tracking down the cause before I saw ferociousdork's post. I'll put up a PR to fix it in a bit.
