### ISSUE TITLE
Technomancer mana-toolbar is not well-made and does not withstand the punishment of combat.

### ISSUE THREAD

**Issue by Divreus** [CleverRaven/Cataclysm-DDA#51623]
### Describe the bug

Welding an iPad to your magic wrench causes the magic wrench to shatter upon contact with a creature that needs aggressive dismantling.

### Steps To Reproduce

Spawn a mana-toolbar, whack something with it.

### Expected behavior

Well, I certainly didn't expect a deer to do in my hard-earned mana-toolbar.

### Screenshots

![cataclysm-tiles_2021-09-14_16-44-36](https://user-images.githubusercontent.com/32739397/133332519-917c6d6e-195e-481f-8141-d3673ac3968a.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 920a088 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    No Fungal Monsters [No_Fungi],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by actual-nh** [comment]
Either it should indeed be more durable, or the interface should make it clearer that it isn't.

**Comment by Divreus** [comment]
I can only guess that the addition of the glass material to the mana-toolbar is causing the entire thing to shatter when roughed up.

**Comment by anothersimulacrum** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/d978eeb966150794689ea1216d18f00828abc683/src/melee.cpp#L2098-L2124

**Comment by BaumgeistOne** [comment]
I'd go one step further and say that the Technomancer mana-toolbar should never shatter. First of all, the glass part is not used for fighting, second of all, if that part should get destroyed anyways, the weapon should revert to the Technomancer toolbar it was made of, and since that does not seem to be possible at the moment, we should define the item to be made of steel only.
If we are looking for an ingame explanation: The thing is infused with magic, the glass part does not shatter because of that.
