### ISSUE TITLE
Shopkeeper trust and tier lists: Save me from my own aspirations

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#51638]
# Problem

In writing the exodii, I am coming across a problem which I *can* solve with JSON, but the nesting conditionals are rapidly becoming inaccessible spaghetti nobody will ever be able to work with.

Specifically, I need to track a variable for a merchant, let's call it `trust`. As this rises to threshold levels, new itemgroups should be added to the shopkeeper's inventory. I also need to be able to adjust this with dialogue conditionals.

I can do this in JSON, it's a nightmare, but I think this is a mechanic we probably want for every faction anyway.

# Proposed System

1. Add a `faction_trust` variable that is shared by each member of a faction.
- this variable should reset if you die, although if we get legacy games, it should instead be reduced by a set penalty for the next NPCs of your faction. Let's build this feature to work properly with new characters in the same world, since we're starting from scratch.
2. Add dialogue conditionals and effects to `faction_trust`: `u_has_faction_trust` and `u_add_faction_trust` at least.
3. Allow `shopkeeper_item_group` in NPC definition to accept an array of values instead of a single item group, along with a trust threshold for each value, like this:
```
"shopkeeper_item_group": [ 
  { "group": "tier1_items", "trust": 0 },
  { "group": "tier2_items", "trust": 10 }
]
```
Each of these itemgroups should refresh over time just as the default shopkeeper item group does.
4. Add a "strict" boolean to the above lists: if an itemgroup has "strict: true", the shopkeeper will not sell it if trust is below threshold. So if you sell or give a shopkeeper a reality bending CBM, they may hold on to it and refuse to sell it back because it's too valuable to them.

# Further related thoughts

Another shop feature largely unrelated to this - but possibly similar to 4 above in code - is that we should also shops to use blacklists or whitelists to specify what they'll buy. The exodii don't want your salvaged lumber. The free merchants have no way to use your CBMs (for now).

# Desperate plee

If I have to get all this done in JSON conditionals I have no idea how long it will take to finish this PR. Please save me.

**Comment by PatrikLundell** [comment]
It sounds like it would be useful to add code support for this such that the code would sort out what items to offer based on the lists specified in the JSON (and the modifiers controlling access to the lists). This ought to remove the need to essentially copy-paste the same dialog logic between shop keepers since, as noted, it's something we'd want to have for multiple shop keeps.

To make your life harder, though, I'll ask whether we'd want a faction association modifier as well (with and without trust), such that you may open up some limited access inventory with the Old Guard if you've passed a threshold, as long as your trust hasn't fallen below some value, while you might be able to actually interact with Isherwood if you've gained enough trust with them even if you're associated with a faction they really don't like.

**Comment by I-am-Erk** [comment]
> To make your life harder, though, I'll ask whether we'd want a faction association modifier as well (with and without trust), such that you may open up some limited access inventory with the Old Guard if you've passed a threshold, as long as your trust hasn't fallen below some value, while you might be able to actually interact with Isherwood if you've gained enough trust with them even if you're associated with a faction they really don't like.

That would be nice, but it's not something I think a first pass needs.
