### ISSUE TITLE
Multidrop drop amount bugs dropping selection

### ISSUE THREAD

**Issue by estebandellasilva** [CleverRaven/Cataclysm-DDA#51712]
### Describe the bug

Using multidrop you select what you want to drop.

Currently if you try to drop an amount like 1 for example - it stays active if after your first selection with the drop amount.
(use 1 on numpad - all you selections after this will make you drop 1)

Havent found a way to change this selection except by typing in more numbers ( increase drop amount)

Second Problem.

After you have typed in an amount you no longer can deselect stuff you want to drop

If you dont type in anything the feature works normally

### Steps To Reproduce

1. Create a character and get something which stacks in your inventory ( splintered wood, nails, scrap metal) ( i used scrap metal, lumps of steel und chunks of steel found on an airliner crash site)
2. Open drop Menu
3. Type in a Amount to drop below the max Amount
4. Select Multiple Items ( you will see that the amount selection stays enabled for all of you selections)
5. Try to unselect something you selected

### Expected behavior

Before it was that if you typed in an amount to drop it was enabeld only for 1 action. And you could deselect if you accidently selected it
If this is intended a turn of button iss needed for the amount options as currently its not able to be switched off after using it once.

### Screenshots

![image](https://user-images.githubusercontent.com/89189872/133924359-dc45be99-37e7-40c4-b5be-a8225f69ed8d.png)
Typed in 1 on Numpad once - every selection was with 1 for the drop amount - unable to deselect
Only able to increase the drop amount by typing in more numbers.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 09095af [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Monsters [No_Fungi],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by atealein** [comment]
I can confirm this is a problem for Linux version 6725ecf on the curses build. I was playing around to actually find how it works and actually, if you try to type more digits after the 1, it will add them, you cannot delete them, until you are always selecting the entire stack of whichever item stack you pick. - What I mean is if you selected 1 on the first stack, then go and try to write 2 on the second, it will instead select 12, and the third one which had for example (23) items in it and you want to select 3, when you select three it will be actually selecting the entire group (because it was trying to select "123" and that was higher than the stack number so it selected all). And because you can't un-select an item, you have to cancel the entire thing.
