### ISSUE TITLE
Undershirt cannot be cut-up to produce rags

### ISSUE THREAD

**Issue by jeffplata** [CleverRaven/Cataclysm-DDA#51741]
### Describe the bug

The undershirt is apparel made of cotton that should be easily cut with any knife or cutting tools. When activating a knife and choosing cut an item, the undershirt is not listed as an option.

### Steps To Reproduce

1. Spawn an undershirt and a knife.
2. Pickup both.
2. Activate knife.
3. Look at the list of items in the items to cut. Undershirt not listed.

### Expected behavior

The undershirt could be and should be easily cut by cutting tools to produce rags as IRL.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 987101e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Hope [no_hope]
]

**Comment by ProfoundDarkness** [comment]
I haven't sat down to find out for sure but it seems like any item under a certain volume can't be cut up, at least among cotton.  Anything 0.25L volume or less seem to be off limits to cut up.

OK, found a counter example... dust mask.  Out of much of the stuff I have at home base that was the only sub quarter liter fabric item I could find that allowed cutting up.

**Comment by Malorn-Deslor** [comment]
I actually ran into a similar problem with a lot of other clothing. It can be fixed using uncrafting recipes at the moment, but each has to be added individually

#47742

**Comment by ferociousdork** [comment]
The issue here is the weight. The undershirt weighs less than a single rag, hence it cannot be cut up:
https://github.com/CleverRaven/Cataclysm-DDA/blob/25fc438ce9ec3ddcefe028951f20f6be1b6913b6/data/json/items/armor/undergarment.json#L577-L581

https://github.com/CleverRaven/Cataclysm-DDA/blob/25fc438ce9ec3ddcefe028951f20f6be1b6913b6/data/json/items/tool/toiletries.json#L109-L114

Relevant check:
https://github.com/CleverRaven/Cataclysm-DDA/blob/25fc438ce9ec3ddcefe028951f20f6be1b6913b6/src/iuse_actor.cpp#L1449-L1451

**Comment by Malorn-Deslor** [comment]
Perhaps the weight on an undershirt is part of the problem in this case, then. But in other cases it is not.

Btw, this is why I had my disassembly recipes produce thread, meaning that I could keep weight fairly equal.

**Comment by sharkfinsouperman** [comment]
I was asked to add any other items that cannot be cut up, but it seems they're restricted due to a weight restriction.

Is the weight factor consistent? Sport bras can be cut up but leotards and compression tops cannot.

**Comment by ProfoundDarkness** [comment]
... Patchwork cotton clothing parts weigh 0.22lbs, lycra patches are 0.17lbs,  I would expect the weight restriction to be different based on the material you get post cut-up (related to material type of the item).

Compression tops can actually be cut up, being over 0.17lbs (0.20).  Leotards indeed cannot be cut up, makes sense given 0.13lbs.  I haven't actually cut up any lycra items yet so I don't know if it's lycra patches you get but you use patches in repairs and since you use patchwork cotton clothing parts to repair cotton stuff I'm assuming it's lycra patches you get on cut-up.

Weight certainly seems to be the factor though the code itself indicates different items (materials) have different weight cut-up limits.  It's probable you could collect most of the list of interest with a shell script...
