### ISSUE TITLE
NPCs getting stuck trying to path in through a closed window.

### ISSUE THREAD

**Issue by ProfoundDarkness** [CleverRaven/Cataclysm-DDA#51882]
### Describe the bug

It seems like NPC pathfinding is allowing bi-directional use of closed windows when windows can only be opened from one side.

### Steps To Reproduce

1. Load the first included save. 
[DBG_NPC_PathWindow.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7230333/DBG_NPC_PathWindow.zip)

2. Tell NPC to follow (C, f)
3. Step inside
4. close the door
5. Step down diagonal away from the door or directly down to the window then away from it, the NPC will stand near the window until it is opened.
6. If done right, player can open the door and NPC will still be stuck near window.
7. NPC unstuck (usually) when player gets close.

Alternate:
1. Load the second included save (same world/character btw). 
[DBG_NPC_PathWindow2.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7230343/DBG_NPC_PathWindow2.zip)

2. Tell the NPC to sort the items.
3. The NPC will head to the window and stand there.
4. Player can now move freely andthe NPC will be stuck this way until instructed to stop or the player opens the window that the NPC is near.

### Expected behavior

NPCs don't try to path IN through closed windows (not like there are many one way terrain types).  Pathing out is apt since they can open it without smashing or prying or otherwise damaging the window.  This can mean going around for another nearby door or already opened window or walking up to the player and telling them to move.

Oh and yes I've had an NPC decide to try and path through a closed window when a perfectly good open window was one more down.

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.3 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.F-2984-ge6f57792c9 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth]
]

### Additional context

This pops up a surprising amount when I'm out exploring with 2 NPCs (I don't have more yet).  Basically for one reason or another one of the NPCs decides to try coming in through a closed window and then just stands there until I intervene somehow (usually by opening the window).

**Comment by Vendidurt** [comment]
Yes, this happened when I cleared a town of zombies and set my NPCs to cleanup work. Soon all four of them were jammed against windows, politely waiting for me to walk past them, through the already opened door, and open it for them. It compounded when they were set to "close the doors," stranding their partner behind them. Eventually I just set the cleaning zones to the street so I didnt have to literally open every window in a city.

**Comment by ProfoundDarkness** [comment]
Question: Were you doing cleanup like this about 2 weeks ago? Were they messing up then?  Specifically before and including about September 10th.

**Comment by hexagonrecursion** [comment]
Confirmed by using your save file.

![DeepinScreenshot_select-area_20220104161613](https://user-images.githubusercontent.com/52621858/148064747-1be1f812-7234-4a77-b8b5-e9d59bf5a8ec.png)

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: eacb7d9 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth]
]

**Comment by LeahLuong** [comment]
NPC pathfinding is a little wonky in general. Don't get me wrong, I like the inclusion of NPC's & think their pathfinding is fairly decent. Personally, I have an issue where a central assigned seat in a Humvee can't be found by the NPC w/out my intervention; prob an issue w/ equal distance calcs & the algo flipflopping betw/ them. I think that a piecemeal approach to fixing these sorts of problems is likely to generate as many issues as it fixes. A general overhaul needs to be made & there are so many corner cases the problem is overwhelming. There should prob be a thread for collecting as many of these cases as possible for when a general overhaul attempt is made.

Another time, my NPC got stuck betw/ a noxious gas cloud & a Z hulk despite my being able to navigate a clear path by stepping diagonally twice around the cloud. NPC was yelling, "Can't run! Have to fight!" until he got super punched onto my side of the gas.

**Comment by hexagonrecursion** [comment]
> Personally, I have an issue where a central assigned seat in a Humvee can't be found by the NPC w/out my intervention

@LeahLuong Please report this as a separate issue instead of hijacking an existing thread - this makes it easier to keep track of troubleshooting and debugging efforts. You can link the issues together, but they should all be separate threads. Thank you.

> Another time, my NPC got stuck betw/ a noxious gas cloud & a Z hulk despite my being able to navigate a clear path by stepping diagonally twice around the cloud.

same

**Comment by LeahLuong** [comment]
@hexagonrecursion Andrey, I think you missed the point of my post. Creating separate threads is likely to compound this issue (not this particular issue but the greater issue of NPC pathfinding in general) because whomever ends up tackling it won't have easy access to the many corner cases that pop up. I don't have much understanding of this game's code so don't feel qualified to start a centralized thread. I also don't feel like starting a separate thread for each foible I encounter w/ NPC pathfinding. I apologize for "hijacking" the thread & will make no further comment here.

**Comment by RabblerouserGT** [comment]
There's an even worse thing here I've noticed. I've had an NPC smash my window when he tried to pathfind through the window.

I have two theories as to why it was smashed
- the NPC was literally one tile away when I closed the window. Maybe he already had his path "locked in" that he was going onto the window tile and auto-smashed? I'm not familiar with the pathfinding code so I can't rule it out.
- **MOST LIKELY**, in my opinion, it may be because he's the "I wanna set my enemy's house on fire" mission NPC who (I believe) is technically not on your side yet, so he possibly just bulldozes what's in the way of his pathfinding.
