### ISSUE TITLE
Microlab loaded bad ter

### ISSUE THREAD

**Issue by Termineitor244** [CleverRaven/Cataclysm-DDA#51927]
### Describe the bug

 DEBUG    : Loaded bad ter!  ter microlab_generic_hallway_start_east

 FUNCTION : void overmap::unserialize(std::istream&)
 FILE     : src/savegame.cpp
 LINE     : 521
 VERSION  : dbfb247

Bug report upon opening my game after updating from a yesterday build to the most recent one, I suppose related to #51893

### Steps To Reproduce

Load the save file.

### Expected behavior

To not have a bug just for loading my game?

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: dbfb247 [64-bit]
- Graphics Version: Tiles
- Game Language: Idioma del sistema []
- Mods loaded: [
    Futuros Días Oscuros [dda],
    Profesiones Biónicas [package_bionic_professions],
    SpeedyDex [speedydex],
    Atributos a Través de las Muertes [stats_through_kills],
    Sin Crecimiento Fúngico [no_fungal_growth]
]

### Additional context

[Ninja.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7237640/Ninja.zip)

There is another bug happening at loading, already reported in #51856.

This bug is probably related to the automatic testing fail reported in #51923.

**Comment by anothersimulacrum** [comment]
`microlab_generic_hallway_start` overmap terrains need migration.

**Comment by Termineitor244** [comment]
Yeah, similarly to bike_shop_1 into s_bike_shop_1.

**Comment by ProfoundDarkness** [comment]
mkay it seems a pretty good list of broken (missing) terrain:
```
microlab_generic_hallway_start_north
microlab_generic_hallway_start_east
microlab_generic_hallway_start_south
microlab_generic_hallway_start_west
microlab_generic_hallway_north
microlab_generic_hallway_east
microlab_generic_hallway_south
microlab_generic_hallway_west
```

It's not immediately obvious to me what the new terrain types should be from looking at the PR.  It seems like the old method was a seed position (start) and then single hallway path.  The new system is more like roads where things are linked end to end... in those there are no starts, only ends.  Also more options for linking and probably a better sense of connection.

Since I'm not sure how to do a migration in repo I've fallen back on what I do know, mass replace text in my save using grepwin.  Spent some time looking over the changes to files to get some idea of what the old -> new terrain would be.

First I tackled the starts so search for: "microlab_generic_hallway_start_" replace with: "microlab_generic_hallway_end_"  After test loading that those particular errors were gone, still have the regular hallways erroring though...

Next up the regular hallways.  The new hallways are more generic, I had an expectation, building a new world and doing a lab start seemed to confirm...  4 more search and replaces later...
search for: "microlab_generic_hallway_east" replace with: "microlab_generic_hallway_ew"
search for: "microlab_generic_hallway_west" replace with: "microlab_generic_hallway_ew"
search for: "microlab_generic_hallway_north" replace with: ""microlab_generic_hallway_ns"
search for: "microlab_generic_hallway_south" replace with: really ""microlab_generic_hallway_ns"

Save now loads without error.  Now I didn't actually visit one of these sites since I wasn't quite sure where to go.  I don't know if those replacements are apt.  Also as usual I had a backup from beforehand.  I tend to hang onto such backups for a bit too.  Finally I'll be watching for a PR which handles the migration of this issue on the off chance I pick something up.

**Comment by John-Candlebury** [comment]
I'll push a fix tonight, no real need for weird workarounds.
