### ISSUE TITLE
Smashing with Taekwondo Can Result in Wielded Damage

### ISSUE THREAD

**Issue by LeahLuong** [CleverRaven/Cataclysm-DDA#52001]
### Describe the bug

Not sure if it's bug or feature but bashing doors & such can damage wielded items. I thought TKD forced unarmed but my macahuitl took a hit while I was kicking a door down & another time my Winchester was dented while "opening" a sealed display case.

### Steps To Reproduce

1. Wield an item w/ durability.
2. Select TKD as whupass method of choice.
3. ???
4. PROFIT!

### Expected behavior

I expected glorious foot-based destruction free from the worries of damage to my damageables. My character has Tough Feet after all.

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: ZTE; Model: Z833; Release: 6.0.1; Incremental: 20170615.175128; 
- Game Version: 0.F-2 [32-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by anothersimulacrum** [comment]
I would say that it is correct behaviour that smashing terrain/furniture ignores your martial art and uses your weapon.

**Comment by LeahLuong** [comment]
Seems kinda lame that not wielding anything & using TKD results in using your fists to smash things . . .

**Comment by jumjummju** [comment]
Smashing in general ignoring martial arts makes sense. If you're trying to break a door down and you're a judo master, you're not gonna try to flip the door over your hip. Similarly if you're trying to bash a door down it doesn't really matter if you pull off a fancy, proper reverse heel kick or just kick it normally. 

Since the game doesn't model arm and leg strength separately, a taekwondo character can punch as well as they kick or shoulder bash or w/e when smashing furniture, so there's no reason for them to exclusively use their feet if they have a better armored body part or an object to smash the door with.

**Comment by Zireael07** [comment]
@jumjummju: Certain martial arts, such as taekwondo and karate, do *have* moves specifically for dealing with obstacles (bricks, door, whatever)

**Comment by LeahLuong** [comment]
Also, other martial arts don't force unarmed. If this doesn't warrant a functional change, perhaps at least a descriptive one. It sucks to have to find out by damaging whatever you happen to be wielding. Altering the style's description to alert the player to this danger could be helpful.

**Comment by wapcaplet** [comment]
Since #42875, smashing automatically uses your most protected body part, so you don't actually hurt your hands by trying to smash things bare-handed. I don't think smashing is intended to involve martial arts or other combat techniques at all, though I guess it could be revised to do so.

**Comment by LeahLuong** [comment]
So, nude but for a mining helmet results in headbutting everything to smithereens?? That's so metal.

That said, I'd prefer using MA for smashing where applicable or @ least letting the player know somewhere about how smashing works as you explained it.

**Comment by Owlblocks** [comment]
I've noticed that this works with unarmed attacks, too. Even if you're using a kick technique, it could potentially damage your gloves, rather than your footwear. I'm not completely sure how much of a change it would require to the code, but at least in the long run it seems like something to look at.

**Comment by Owlblocks** [comment]
I know it would require a modification to the JSON structure for techniques (to mark which part of the body they use), but it doesn't seem like the rest of the changes would be too big, as they are pretty well isolated from the rest of the codebase.

**Comment by LeahLuong** [comment]
It seems #53954 will rectify this issue so I'll close it for now.

**Comment by NetSysFire** [comment]
Let the PR close the issue automagically with the closing words

**Comment by NetSysFire** [comment]
#42451 also looks vaguely related.
