### ISSUE TITLE
Multiple NPCs manage to split vehicle when disassembling at the same time

### ISSUE THREAD

**Issue by atealein** [CleverRaven/Cataclysm-DDA#52129]
### Describe the bug

I ordered two NPCs to disassemble vehicles in my faction camp and noticed that they often can split it in multiple pieces that still count as the same vehicle but are not actually connected between each other. This is not something that you can do as a player. 

### Steps To Reproduce

1. Define disassemble vehicle zone, get few friendly NPCs with high enough mechanics, give them tools (hacksaw, adjustable wrench, lifting vehicle, etc)
2. Spawn few cars in the vehicle disassembly zone and order both NPCs to disassemble vehicles. 
3. Sometimes when they work on the same vehicle pieces might be split

### Expected behavior

If this is not allowed for players, shouldn't there be some break to prevent NPCs from doing it as well?

### Screenshots

![Screenshot from 2021-10-06 01-08-46](https://user-images.githubusercontent.com/25322782/136115952-ad2f6ee9-afac-4caf-bcd2-aea95c7cf2be.png)
![Screenshot from 2021-10-06 01-05-34](https://user-images.githubusercontent.com/25322782/136115954-4ab0783d-d529-47db-b468-a0dae1ad3de3.png)

### Versions and configuration

- Linux RHLE
- Curses
- Experimental cbd8876

**Comment by TealcOneill** [comment]
Might be a duplicate of #35611, dunno if it's caused by the same thing or not.

**Comment by ProfoundDarkness** [comment]
Not to further muddy the waters but since craft in progress and construction in progress items and constructions were added I've wondered about having a vehicle work in progress?

I **really** don't know much about vehicle stuff at all (not even peeked at the code) but the concept was basically:  If you start a task on a vehicle (add/remove part) that spot on the vehicle becomes a work in progress vehicle part (moves with vehicle) which contains the activity instruction as well as any components required to become the vehicle part (or what you get on removal).  This would make it possible to interrupt and resume activities on vehicles.  Additionally you could only have a single work in progress vehicle location on a given tile which would end up resolving the problem of multiple parts on a tile being removed at the same time.

If desired it could be possible to have multiple NPCs pile on a single activity tile like in construction.  Even though mutliple NPCs couldn't be removing different parts on the same tile they could be removing the same part faster so ends up being close to the same speed in the end.  A bit more out there/future - could use this mechanism to allow NPCs to help with vehicle construction.  The player starts a part then interrupts and moves on while an NPC steps over to complete the work, assuming they have access to apt tools.

For vehicle movement and work in progress...  There are far more parts of a vehicle which could be in progress and not block movement than those which would block movement.  A work in progress engine isn't an engine so it won't supply power.  Same goes for a work in progress tire not counting as a tire.  I could see an argument for any work in progress tire blocking movement... even an argument for any drive train related component work in progress blocking movement.  Though again, there are a lot of parts in progress which logically would not block movement.  Also just to be clear I don't think it would be reasonable to allow a vehicle to be worked on while it's moving.

As for damage...  That's a bit muddy.  The component should be FAR more sensitive to damage than normal, arguably take damage before any other component.  Enough damage done the work in progress part reverts to destroyed part?

Hmm... that got away from me a bit but that's most of the stuff I've had rattling around in my head on the topic for a while.
