### ISSUE TITLE
May be any pocket managmet in a advanced inventory management menu?

### ISSUE THREAD

**Issue by Ixella** [CleverRaven/Cataclysm-DDA#52221]
It seems to me that it would be nice to add to the advanced inventory management menu the ability to extract items from specific pockets and add items to them, as has already been done with the cells around the player. I see it as another hotkey in the advanced inventory management menu for displaying a list of pockets worn by the player, then selecting one of them in the same way as the player selects a specific cell of the earth around him. This should not affect the existing mechanics in any way. Just a convenient way to sort items by containers.

**Comment by ProfoundDarkness** [comment]
More of a meanwhile thing rather than instead of... Something I've been doing is, using AIM, move a container I want to manage to my inventory, move any containers/stuff I might want to pull from to inventory or feet, then on the to be managed container do e (examine?) then i (insert).  Not using AIM to refill/mange containers is such a chore... I only started doing this recently so I have experience the AIM-less way.  I've used it to manage worn clothing a couple of times too.

**Comment by GoodDays13** [comment]
Having the ability to move things between clothes in advanced inventory would make things so much easier. Also, maybe seeing the max length and space remaining in the pocket or clothing you selected too.

**Comment by hexagonrecursion** [comment]
Hello. It sounds like #50015 presents another direction

**Comment by Je55eah** [comment]
I agree and I wrote about it in a comment here just minutes ago: 
https://github.com/CleverRaven/Cataclysm-DDA/issues/55020#issuecomment-1310926228
