### ISSUE TITLE
NPC's issues with backpacks

### ISSUE THREAD

**Issue by Torres84f** [CleverRaven/Cataclysm-DDA#52250]
### Describe the bug

NPC's are not equipping correctly the backpacks I give them, tried with many different backpacks and when you use the trade screen to give them stuff like bandages to carry they're always at ZERO volume capacity so they tell you they don't have room for that even though the backpack is equipped and they carry nothing else.

### Steps To Reproduce

1.- Spawn friendly NPC
2.- Get them naked
3.- Equip them a backpack
4.- It won't add carry volume for them so they won't accept anything else

### Expected behavior

It should add the backpack value to their inventory or at least the pockets available.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 8256058 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    DinoMod - UndeadPeople Tileset [DinoModUDP],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Useful Helicopters [useful_helicopters]

**Comment by atealein** [comment]
I can confirm this behavior, it seems as if they don't count the potential extra volume available in the containers as available when you trade with them.

**Comment by ProfoundDarkness** [comment]
This looks a lot like #52088...  The compile today (I'm on version 825605829) didn't seem to introduce **new** issues getting stuff into NPC inventories for me.  I also swapped one of my NPC's storage around a lot today, including a new backpack and gear.

If you tell them to hold onto items instead of trying to use trade to give them stuff, and they actually have space available, it works.  Even if it shows 0 available volume on trade.  The linked issue has other ideas I had for getting stuff into NPC's inventory.  If that 'hold onto this thing' didn't work, you might have something different going on.

To be more specific to what I think is going on, the issue is that for quite a while, since before I resumed playing experimentals around August, NPCs had 0 available volume in trade.  Now either intentional or bug, trade ALSO didn't count the volume of things you were giving to them (if from your own storage).  Meaning they had 0 volume to start on trade, you give them a bunch of stuff from your storage, they still have 0 volume, it's non-negative, so it works.  With the bug fixes, trade now counts the volume of stuff you are giving them in trade but still doesn't calculate their storage capacity.  Thus you have to get creative to get stuff in their inventory.
