### ISSUE TITLE
Food rots while cooking it

### ISSUE THREAD

**Issue by ZeWoll** [CleverRaven/Cataclysm-DDA#52347]
### Describe the bug

When cooking with old food, the food can become rotten while cooking it, which transitions from edible to instantly inedible in just a few seconds.

### Steps To Reproduce

Try cooking with old food and see how the food quickly becomes rotten in the process of being cooked.

### Expected behavior

Maybe it should stop rotting while cooking? Or just rot slower. Or we could leave it as it is.

### Screenshots

![image](https://user-images.githubusercontent.com/88143686/137716393-f96b6c95-9ac7-41ce-9657-537efbf51d1a.png)
Mac and cheese and the cheese nachos are rotten, but all the other cheese pieces are still just old

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 83a8554 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by atealein** [comment]
I think the "rot while in progress" is an issue, however, that feature was added because previously in progress items weren't rotting at all and people were using them to store indefinitely old food. I think the bigger issue is why is the in progress or resulting item rotting so fast. I think it comes from rot scaling - you have quite fresh nachos and old cheese, producing mac and cheese. The result has shelf life of 10 hours, the nachos have shelf life of 1 day with 21 hours left and the cheese is 4 weeks but spoiling soon. The crafting recipe right now checks which one is the most relatively rotten component (in our case cheese) and then pushes this relative rot to the result. However, if we say "rots soon!" for cheese means it will rot within 1 hour in normal temperature, 1 hour left from 4 weeks is 1/672 or less than 0.15% of the total shelflife time left. Once we switch this to the shelf life of the result - 10 hours for mac and cheese - it translates to 53 seconds. And while you are crafting the next batch, it ticks out and rots.

So I think the bigger issue is how the relative time rot of long-lived items is translated to relative rot to short lived items. It doesn't really make sense from cheese that has at least 1 hour more of shelf life to suddenly transform to less than a minute just because it is mixed with something else (ignoring the temperature processing issue I mentioned earlier), does it?

**Comment by RoyBerube** [comment]
I have a suggestion on how to fix this. This is the code that is setting the rot level: 

https://github.com/CleverRaven/Cataclysm-DDA/blob/3b51b6212ccdf25821d27e9e55c0e84799b56f8a/src/item.cpp#L421-L426

I suggest just multiplying the relative rot level by a ratio - somewhere around .65 seems about right to me. Any craft that would otherwise be about to expire would still have some time remaining before rotting. It is dead simple and will not introduce any bugs.

Think of it as killing off bacteria while cooking, or trimming off undesirable portions of ingredients before crafting the dish.

Any opinions? I don't want to submit a PR on this if the idea is unpopular.

**Comment by I-am-Erk** [comment]
I think another option would be to use how much time the ingredient has left, rather than relative rot; using relative rot doesn't make sense. The rule should be that the product can't have any *longer* than its base rot time, but after that "relative" shouldn't be involved.

**Comment by PatrikLundell** [comment]
Possible logic:

Find the shortest remaining shelf life of all ingredients. If that is longer than the full shelf life of the product, produce a product with a full shelf life.
If the shortest remaining Ingredient shelf life is shorter than the maximum shelf life of the product, use that time as a floor when calculating remaining time for the product.

This would mean you can use somewhat aged long lasting ingredients without it affecting the product in a lot of cases, which may or may not be desirable.

**Comment by I-am-Erk** [comment]
Yep, that's pretty much exactly the algorithm I'd use. Rephrased:
1. Check shortest lifespan of any ingredients. if shortest life > max life of product, break. No further rot adjustments.
2. If shortest life of ingredients < max life of product, use shortest life of ingredients for life of product.
3. (optional) If heat is a part of the recipe, consider extending the life a little bit longer than the shortest life of an ingredient (I suggest doubling)

**Comment by atealein** [comment]
Apologies for stopping the replies and work on this issue, had to take a big break from the game.

I agree with 1 and 2 if no heat/fermenting/etc other type of food processing is involved in the recipe of the final product. 

However, the recipes where you require some thermal processing and so on, should result in a "pristine" food product so to say. Pristine in terms of how long it will take for it to rot. Why? Because all these types of processing food actually destroy the bacteria that are causing the rot. So they won't just "continue" to rot in the resulting product, they will have to develop anew from the contact with nearby air, surfaces, in appropriate temperature and moisture and it will take them again time to spoil the food. 

I can take a soft pumpkin and make soup out of it and that soup won't spoil faster (in the same conditions) than a soup made from a fresh pumpkin. Maybe there are exceptions, but I doubt there are that many. Keep in mind, here I discuss the rotting timer, not the calories content.

**Comment by I-am-Erk** [comment]
Many meats and things don't reset their rot timers so fully on cooking, unless you're cooking them to a very high temperature. However, I don't have strong opinions on how exactly we do it as long as we kill relative rot.

**Comment by PatrikLundell** [comment]
There are (at least) three degradation issues with food:
- Microbial buildup, which can be halted completely with sufficiently high temperatures (which may be higher than cooking usually uses, and which may cause unwanted side effects). Basically a repetition of what I-am-Erk said.
- Toxin buildup from microbial activities. Some toxins are destroyed by heat, but you have the same issue as with the previous point.
- Chemical decomposition, such as e.g. fat going stale due to oxidation (e.g. for fat in things stored in a freezer). This can cause the product to taste bad at least, even when it isn't directly harmful.

However, I don't feel a strong need to have a perfect model, so microbial killing processing being assumed to be perfect and sufficient (when used) is probably good enough.

**Comment by atealein** [comment]
I like the list of issues, Patrik, maybe a future update can make using somewhat old food (but not rotted) to give effects on the final product even when it is processed by heat/acid/etc by 
- lowering consumable calories
- increasing toxin content in the food
- lowering joy

**Comment by brannamm** [comment]
> Yep, that's pretty much exactly the algorithm I'd use. Rephrased:
> 
> 1. Check shortest lifespan of any ingredients. if shortest life > max life of product, break. No further rot adjustments.
> 2. If shortest life of ingredients < max life of product, use shortest life of ingredients for life of product.
> 3. (optional) If heat is a part of the recipe, consider extending the life a little bit longer than the shortest life of an ingredient (I suggest doubling)

This only works when the result item has a lower shelf life than its ingredients. Food preservation recipes (dehydrated meat) would be broken by this because number 2 in that list restricts the life of the product to the shortest life of any ingredient.

I can't think of any sensible way of applying rot to the dehydrated meat recipe other than relative rot as it is now. We could feasibly do relative rot for preservation recipes and the "shortest lifespan of ingredient" method for recipes that have lower shelf lives than their ingredients, but I'm not sure what we'd do with recipes that have ingredients that have both longer and shorter shelf lives than their result.
