### ISSUE TITLE
Bugged Mine / Mineshaft Mapgen - No Exit

### ISSUE THREAD

**Issue by Vzor-** [CleverRaven/Cataclysm-DDA#52517]
### Describe the bug

While playing, I took an elevator down into a mine. Once down I found no way back up. 

### Steps To Reproduce

Default world gen

### Expected behavior

An exit would have been nice

### Screenshots

![Capture](https://user-images.githubusercontent.com/10621658/139354275-8fe2d441-c352-4c6c-9a63-6fc0a6bd84cf.PNG)

### Versions and configuration

- Windows 10
- c9d5870
build type: windows-tiles-x64
build number: 2021-10-17-0638
commit sha: c9d58704a4575e3ba450db2a32edf699b6f402db
commit url: https://github.com/CleverRaven/Cataclysm-DDA/commit/c9d58704a4575e3ba450db2a32edf699b6f402db

### Additional context

[Syracuse.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7438077/Syracuse.zip)

**Comment by avianArsonist** [comment]
if it helps, I've tried to play the bottom of a mine start on an older experimental, and I'm pretty sure all of them except the first one I tried had no way to climb up, so I can confirm that's happening as well

**Comment by ST92** [comment]
Can confirm on build 2021-10-31-0522. Fresh world, first character, first time - no exit or enemies.

**Comment by hexagonrecursion** [comment]
I think this is caused by https://github.com/CleverRaven/Cataclysm-DDA/pull/47790. A part of the jsonified mine -2 floor is overwritten by hardcoded mapgen.

The overwrite always happens, but it is most noticeable when the exit is overwritten.

What you get:
![DeepinScreenshot_select-area_20220111185239](https://user-images.githubusercontent.com/52621858/148976733-c654a382-36cd-41e0-96ff-9ddd84d9d6d4.png)

What you are supposed to get:
![DeepinScreenshot_select-area_20220111185643](https://user-images.githubusercontent.com/52621858/148976752-aaae2762-bdd3-4c60-9a6a-bd5976fb66ac.png)

https://github.com/CleverRaven/Cataclysm-DDA/blob/a34653b199ca53a318fe36a85640b00e9881bbf7/data/json/mapgen/mine/mine_shaft.json#L37-L68

https://github.com/CleverRaven/Cataclysm-DDA/blob/a34653b199ca53a318fe36a85640b00e9881bbf7/src/mapgen.cpp#L5677-L5687

https://github.com/CleverRaven/Cataclysm-DDA/blob/d42f7d25fcff89f42cf5f060f691d17ef83c5500/src/overmap.cpp#L3350-L3353
