### ISSUE TITLE
Reloading containers with liquid doesn't filter possible reloads

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#52530]
### Describe the bug

When I attempt to reload a container that has liquid it shows all possible reload options such as random items and cents from cash cards. Attempting to reload with an invalid item fails but it's very annoying to parse through all local items to find something that matches the container. It's been broken for awhile and definitely wasn't always this way and I haven't seen any issues for this.

### Steps To Reproduce

Attempt to reload a gallon jug with 1 water in it.

### Expected behavior

The gallon jug reload should only show me other waters and not everything else.

### Versions and configuration

Latest experimental

**Comment by RoyBerube** [comment]
I believe this was caused by PR #51027 in item::is_reloadable_helper().

Problem can be reproduced if you have a waterproof container and have matches in inventory. Matches are shown as an ammo type but will fail if you try to reload them. Matches are not being rejected as a valid ammo like they should be.

There is room for improvement in some of the waterproof container logic in that method - introduced from when I was working on multicooker issues in the spring.

Anyway, am working on it but don't have a complete solution figured out yet.
