### ISSUE TITLE
Shotgun speedloader chute not work

### ISSUE THREAD

**Issue by AlexNTFox** [CleverRaven/Cataclysm-DDA#52595]
### Describe the bug

Weapon addon and shotgun speedloader chute not work. Gun don't see not 6, nor 8. They just keeping used shells, menu not open

### Steps To Reproduce

Select Shotgun who support this addon
Unload gun
install speedloader chute
load chute (any type of 12 ammo)
Try to reload with chute

### Expected behavior

I expected it to work the same way as with revolver speedloader, but gun doesn't see these speedloaders

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: a37d197 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    C.R.I.T Expansion Mod [crt_expansion],
    Hair and Skin Color Cosmetics, UDP and MXotto+ version p10 [mxoudpcosmetics],
    Zetsukaze's Hair - 0.E EDIT [zets_hair_extensions_undead],
    Mythical Martial Arts [MMA],
    Rummaging [Rummaging],
    Crazy Cataclysm [crazy_cataclysm],
    Extra Mutated Scenarios [extra_mut_scens],
    Graphical Overmap [Graphical_Overmap],
    Whaleys Hair Mod (UDP Tweaks) [WHALEYHAIR_UDP],
    Graphical Overmap Vanilla Additions [Graphical_Overmap_SDG],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Fuji's Military Profession Pack [fuji_mpp]
]

**Comment by ektoplazm** [comment]
can confirm on

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 70623c6 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    No Fungal Growth [no_fungal_growth],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by tinukedaya** [comment]
This one still doesn't work... I played around with the JSON, but it's above my level of knowledge to fix it. :D 

I can make the speedloaders work, with the `allowed_speedloaders:` field added to the shotgun, but that makes it possible to use the speedloader tube even without the speedloader chute. 

the chute json has the `"magazine_adaptor": [ [ "shot", [ "shot_speedloader6", "shot_speedloader8" ] ] ],` line but this obviously doesn't help. Maybe because the shotguns don't really accept magazines as such? 

So  if there would be a way for the gunmods json to add the  `"allowed_speedloaders": [ "shot_speedloader6" , "shot_speedloader8" ],` line to the gun's pocket definition when the mod is attached ... But maybe it's completely wrong what I wrote here and maybe the problem is somewhere else completely... As I said, that is way above my paygrade... :D
