### ISSUE TITLE
Cannot check contents of USB drives

### ISSUE THREAD

**Issue by Tommy-os** [CleverRaven/Cataclysm-DDA#52636]
### Describe the bug

USB drives are supposed to contain software, however all USB drives show up empty in inventory and laptops offer no interaction to check what is on the drives. I can tell that some drives clearly have something on them as they don't stack with other drives inside inventory screen.

### Steps To Reproduce

1. Find many USB drives
2. Attempt to use laptop/e-ink tablet to see what is on them
3. No interaction exists to check the USB drives, only uploading books onto them is possible

### Expected behavior

Being able to use laptop/e-ink tablet to check contents of USB drives.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0ad2fdd [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Terrorforge** [comment]
Likely introduced by #52419

I suspect this is also the reason I've been unable to find a copy of hackPRO for the last week of playtime - it's not listed in the name any more.

**Comment by Saicchi** [comment]
> Likely introduced by #52419

I've went back to 0.F-2 stable and still couldn't find a copy of hackPro even in a hazardous waste sarcophagus or by checking the loot from 1000 zombies. The USBs didn't contain any software nor did I found any code that spawns them in with software.

Also about them USB sticks not stacking, were they damaged? Even two items with the same shown durability `|\` will most likely have different `damaged` amounts.

By the way laptops and e-ink tablets didn't have code to check inside usb sticks. They could only look inside memory cards, and they didn't use the memory card storage.

**Comment by Terrorforge** [comment]
I found one on a relatively recent run from before that change, in a regional dump. Hell, turns out I have one in my current run. I know, because the practice recipe finds it. It's just called "usb drive" instead of "usb drive > hackPRO". I haven't been able to cross-reference the specific builds, so I admit it may be coincidence, but yours is the only recent change to usb drives I'm aware of, so I thought it was the likely culprit.

Oh, and the reason you're not finding any code for spawning USB drives with software on is probably that it works the other way around; the game spawns the software, and puts it in a USB drive container. The same way it treats e.g. antiseptic.
