### ISSUE TITLE
Missing space between moon phase and temperature on specific moon phase

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#52664]
### Describe the bug

See title. Very minor UI bug.

### Steps To Reproduce

1. Adjust your sidebar configuration to display moon phase (and temperature). Also set it to labels.
![image](https://user-images.githubusercontent.com/59517351/140580619-be28c0f2-e228-423d-b7d6-955452d7ade7.png)
2. Set the time and date so the moon will be waxing crescent.
3. Observe a missing space between the two labels.

![image](https://user-images.githubusercontent.com/59517351/140580719-bf15a69f-07f8-403a-8341-e8f5ea73540f.png)

### Expected behavior

The space would not be missing. All other moon phases display correctly, only waxing crescent is too long, by one character.

### Versions and configuration

- experimental

### Additional context

I *suspect* it is caused by this:

https://github.com/CleverRaven/Cataclysm-DDA/blob/7bcd158f982004c35870ec3bf3332c7e0a64561a/src/panels.cpp#L1880-L1881

**Comment by PatrikLundell** [comment]
Based only on the above, it looks like changing "23" to "24" on line 1881 should shift the placement of the temperature by one column. If the image posted shows the minimum width of the window there is enough space for that. Otherwise the minimum window width should be checked (and checked with a 3 digit temperature, as you'd easily get that when using "freedom units").

Also note that I have no idea if there's an option to display something beyond the temperature, in which case that would have to be adjusted and tested to see that it still fits.
