### ISSUE TITLE
Implement directional item pickup

### ISSUE THREAD

**Issue by Tommy-os** [CleverRaven/Cataclysm-DDA#52662]
# Is your feature request related to a problem? Please describe.
Not being able to pickup items from a specific tile makes looting unbearable. Having to scroll through multiple pages of tiles with items to see where is what is terrible as the order of said tiles changes based on player location.

# Describe the solution you'd like
A dedicated button to loot only from 1 tile. Ideally integrated onto examine as it was prior to https://github.com/CleverRaven/Cataclysm-DDA/pull/51033

# Describe alternatives you've considered
Being able to interact with only a single tile is basic interface functionality.

# Additional context
I have huge stacks of items in my base, I have to now stand directly on top of them (impossible for shelves) to not have to scroll  through a dozen pages of items just to interact with the tile I want.

**Comment by mqrause** [comment]
What's your use case and is that the best solution for that? If the only issue is too many items, using a filter might be a better option.

**Comment by Tommy-os** [comment]
Lets keep it here https://github.com/CleverRaven/Cataclysm-DDA/issues/52663

**Comment by catdach** [comment]
This was of course previously tied to `e`xamine
I'm honestly not sure why it was removed from `e`xamine to begin with. Even if the menu was 

> unfit for the pocket system
> and also a general pain.

The first point seems to have more to do with the menu itself, and not it's connection to `e`xamine. The second point is a matter of opinion.

From a player perspective it has suddenly become much more difficult to do something as simple as pickup an item because of #51033

Also if a new menu was created, why didn't it simply replace what was tied to `e`xamine?

I'm really not sure what #51033 did other than remove functionality
