### ISSUE TITLE
Make dummy and practicing use cordage and string

### ISSUE THREAD

**Issue by danielkwinsor** [CleverRaven/Cataclysm-DDA#52684]
# Is your feature request related to a problem? Please describe.
Duct Tape was not invented until 1942 in WWII.  Prior to this, all cutting, stabbing, melee training happened only on the battlefield.  Only once duct tape was invented could a training dummy be fabricated and practicing take place without danger.  There were advancements made in dummy technology around the early to mid 21st century where dummies were upgraded to be constructible using more advanced, naturally sourced, and sustainable materials like cordage.  However, this is lacking from the game, and the latest technologies ought to be reflected in a game set in the near future.

# Describe the solution you'd like
Training dummy and similar items are craftable using string or cordage.
Practicing against said dummy requires an equivalent amount of cordage or string.

# Describe alternatives you've considered
Learning only on the battlefield
Learning to source and craft duct tape without any violence.

# Additional context
Add any other context (such as mock-ups, proof of concepts or screenshots) about the feature request here.

**Comment by Termineitor244** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/51598#issuecomment-921422620 laid out the making of a dummy, I can make their construction allow strings or cordage (And will do), but for practice you need something to mark the strike points, the original comment suggested duct tape or paint, any other suggestions of what could serve?

**Comment by ElSticker** [comment]
Permanent markers perhaps? They certainly exist and mark things up. Spray paint cans as well. A little more unconventional, but maybe red wine or an equally stain happy fluid (or an actual dye), cotton balls or rags or something, and thread to affix them as target points.

**Comment by danielkwinsor** [comment]
Survival marker too

**Comment by Termineitor244** [comment]
I will work on it to see if I can add the markers (survival one too) and spray paint cans to the same practice recipe! I just need some time to work on other PRs but this should be done by today.

Thanks for your suggestions!

**Comment by danielkwinsor** [comment]
The funny thing is that any knife or cutting tool can be used to write on an object in game :D

**Comment by Termineitor244** [comment]
> 
> 
> The funny thing is that any knife or cutting tool can be used to write on an object in game :D

But you are training with weapons, you will leave many marks in the dummy, even with unarmed, you need to change the strike points from time to time to make a real training.

I tried to add the objects suggested in here, but they are tools with charges, so I can't make the recipe to require only duct tape OR charges from one of these objects, it would ask for both.

I added paint and medical tape for now, and removed the duct tape from the recipe for the light dummy, since it was unnecessary (The strike points are already counted for in the practice recipe).

I will leave it like this since using those tools would require more recipes for the same thing.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
