### ISSUE TITLE
Choosing show contents of container causes game to crash

### ISSUE THREAD

**Issue by Chris-XII** [CleverRaven/Cataclysm-DDA#52748]
### Describe the bug

When attempting to show the contents of any container in which the contents are currently hidden, the game will generate an error report which cannot be dismissed, functionally crashing on the error screen.

### Steps To Reproduce

1. Load into world
2. Try to show hidden contents of any container with an item inside (e.g. first aid kit)

### Expected behavior

Game to not hardlock.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: e79ee6a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

### Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/7516454/debug.log)

**Comment by andrei8l** [comment]
Please upload the save game. I've seen that debug message too but wasn't able to reproduce it reliably. You can dismiss it btw by pressing `I` (capital i).

**Comment by Chris-XII** [comment]
Here's the world I first experienced it with. Also, you are right about being able to use I to dismiss it, previously I had just tried space to dismiss it, but that didn't work for whatever reason. Guess I should have just read more before jumping to the word "crash".
[Hartville - Copy.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7521833/Hartville.-.Copy.zip)

I was also able to reproduce this by just spawning into a world, debugging in a backpack, adding an item to it, hiding and showing it.
[test world - Copy.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7521834/test.world.-.Copy.zip)

**Comment by andrei8l** [comment]
Are you hiding/showing from the item menu or directly from the player inventory/multidrop/whatever else?
<details>
<summary>item menu?</summary>

![Screenshot from 2021-11-11 20-19-10](https://user-images.githubusercontent.com/68240139/141349265-e1d203ae-13b2-4a2a-a98a-0231d9b2c2f5.png)
</details>
or
<details>
<summary>inventory window?</summary>

![Screenshot from 2021-11-11 20-21-35](https://user-images.githubusercontent.com/68240139/141349416-a2f356ca-5b23-415e-bdf2-c71f4335fbb0.png)
</details>
 I can only reproduce the bug through the item menu which should get fixed by the PR above. If you're getting the bug directly from the inventory menu (with the < > keys), please provide a screenshot as it might be related to your specific window size or setup.

**Comment by Chris-XII** [comment]
Yes, it happens whenever I show contents through the item menu. I don't seem to be able to trigger this error through the inventory window itself.
