### ISSUE TITLE
Allow item spawn scaling factor to vary over time

### ISSUE THREAD

**Issue by danielkwinsor** [CleverRaven/Cataclysm-DDA#52750]
# Is your feature request related to a problem? Please describe.
I'm going to infer that the game start a short while after the cataclysm, whether that's days or so.  I want to play in a world where it feels like items are readily available to loot at the start but that they are looted or otherwise inaccessible the longer after the cataclysm you get.

# Describe the solution you'd like
Provide 3 settings for starting items, ending item, and length of time to decrease from start to end.  The settings shall affect only items newly spawned, and not affect current items.

# Describe alternatives you've considered
Removing items from game... EG parked car in the middle of the road, I had a full backpack so I didn't take the 41 things in it.  I come back later, and there's just 3 things and a paper wrapper left.  Clearly this seems less feasible.  Although this example is about looting a car, this ticket should apply to all items, even the ones that zombies are carrying.

# Additional context
I play with item spawn rate at 0.10

**Comment by PatrikLundell** [comment]
It's a near total apocalypse, so there aren't many survivors left to loot anything you left behind. If you have that perspective, things should disappear due to being destroyed by weather over time, but little should be looted, beyond what was looted as part of the collapse (looted malls, vending machines, etc.).
Food already deteriorates, so that part is taken care of. How long does it take for other things to be destroyed? Well, it depends on their materials. Anything made out of paper will probably be useless after a month out in the open, but will be unaffected if kept dry. Anything carried by zombies can't have been looted, as that would require the looter to take out the zombie, and if that happened the loot would be left on the ground, leaving a "naked" zombie that won't drop any loot at all.

That said, there are the occasional survivor, bandits, and virtual scavenger parties from factions. Ideally, they ought to work much like the PC does (I would expect most players to use some kind of approach), i.e. clearing an area of zombies and then picking it more or less clean (making it very obvious that somebody has beaten you to it), with the "clearing the area part" sometimes consisting of looting areas where zombies could be avoided, such as individual houses. Still, the signs of previous looting should be clear (and I doubt any looters lock the doors behind them, so all such places should have some kind of available entry).
However, I assume it would be tricky to implement this kind of looting and have it being performed by specific characters/groups.

**Comment by anoobindisguise** [comment]
Ideally also cars would start missing important parts such as seatbelts, wheels, engines, batteries and so on.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
