### ISSUE TITLE
Backpack recipe requires synthetic fabric sheets and patchwork clothing parts

### ISSUE THREAD

**Issue by Allergic2Bulletz** [CleverRaven/Cataclysm-DDA#52883]
### Describe the bug

Backpack recipe requires synthetic fabric sheets and patchwork clothing parts. There are no recipes that only require one or the other.

### Steps To Reproduce

Not sure what to put here haha
[http://cdda-trunk.chezzo.com/backpack/craft](url) It's the same as the chezzo recipe.

### Expected behavior

I was told that this was a bug in the Discord.

### Screenshots

![image](https://user-images.githubusercontent.com/86386027/142473981-263899c1-aeaa-471e-a8df-68c09ee8ac76.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: f61be52 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    ConFed Support Mod [CONFED_MOD],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex]
]

**Comment by matshou** [comment]
In order to craft the backpack you require:

- 66 synthetic fabric sheets
- 3 patchwork synthetic fabric clothing parts

What exactly is the problem here?

> There are no recipes that only require one or the other.

This has been purposefully defined like so in `tailoring.json` under `tailoring_nylon_patchwork` entry and I don't really see an issue with that. Do you want to say that it is an issue with game balance or that it was not intended to be like this?

**Comment by matshou** [comment]
Ah I think I see what the issue is about. You are saying that the recipe should require **either** synthetic sheets **or** patchwork clothing and **not both** of those items. Looking at other similar clothing recipes I think this issue is valid.
