### ISSUE TITLE
Being stunned doesn't disable the "following items dissolve in water" warning

### ISSUE THREAD

**Issue by Venera3** [CleverRaven/Cataclysm-DDA#52887]
### Describe the bug

When randomly stumbling because of `stunned` would walk the player into deep water the "Following items would be destroyed" prompt appears and allows cancelling the move.

### Steps To Reproduce

1. Get stunned along the water's edge with a non-waterproof electronic
2. Walk around randomly until the prompt appears

### Expected behavior

Being stunned disabling the prompt.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.F-3889-g456519b13d-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by wapcaplet** [comment]
A more serious question is whether being stunned and falling into deep water should lead to potential drowning.

**Comment by PatrikLundell** [comment]
Really two rather different questions. I completely agree that you shouldn't be protected against stumbling into water by carrying unprotected electronics.

Once you fall into the water (because your protective talisman laptop didn't protect you anymore), I would guess the following events depends on the nature of the stunning effect. Falling into water provides a shock effect that in many cases would allow basic survival instincts to kick in and might clear the head, while chemical or electric paralytic effects might remain unaffected.

**Comment by Venera3** [comment]
On some more...testing, it seems that warning prompts in general are allowed - you can't stumble into metal wreckage stunned, either.
