### ISSUE TITLE
Json/mapgen Error Reloading Game

### ISSUE THREAD

**Issue by LeahLuong** [CleverRaven/Cataclysm-DDA#52893]
### Describe the bug

Loading back into my game displays the debug error pasted below & sends me back to the title screen.

Here's some background info: I'm trying to do the lab railways mission for the refugee center doctor, Lyman Easley. He'd previously sent me to this same lab on 1 of his earlier missions, so I'd spent multiple play sessions in this area before w/out mishap. I hadn't completely finished looking but was about 90% there when I decided to save it for later; I'm fairly certain no new download terminal was generated for this mission. I'd previously cleared this lab & there is no railway connection to it but there are ant tunnels on the floor where the map's mission indicator placed (-2, I think). I believe lab railways typically generate on -4 & Lyman mentioned it would be deeper than a normal subway. Something fishy seems to be going on & I have a hunch the new mission has somehow caused this error. I'm hopeful it's just a missing bracket or something.

My .sav is too large to upload here but I'll try to provide the file mentioned in the error report.

### Steps To Reproduce

Unknown steps to reproduce.

### Expected behavior

I expected the game to reload as it usually does. It didn't seem to have any problem saving & quitting during my last play session.

### Versions and configuration

Android 0.F-2 Tiles English vanilla

### Additional context

 DEBUG    : Error: Json error: storage/emulated/0/Android/data/com.cleverraven.cataclysmdda/files/data/json/mapgen/basecamps/modular_field_metal.json:130:109: string not closed before end of line

    "update_mapgen_id": "fbmh_shack4_metal_southeast",
    "method": "json",
    "object": { "place_nested": [ { "c2$��

 FUNCTION : bool main_menu::load_character_tab(bool)
 FILE     : /var/lib/jenkins/workspace/Cataclysm-Android/android/app/jni/src/../../../../src/main_menu.cpp
 LINE     : 1150
 VERSION  : 0.F-2
[modular_field_metal.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/7566874/modular_field_metal.txt)

**Comment by PatrikLundell** [comment]
The file has been corrupted. The good news is that this file is part of the game itself, not the save. The bad news is that something that corrupts game files may very well corrupt the save as well.

Also, please remember to explicitly state that the file uploaded has had its extension changed to allow it to be uploaded to avoid confusion among people trying to understand the problem.

My recommendation:
- Copy the save somewhere else.
- If PC logic works on Android, rename the game folder. If it doesn't, delete it (after double checking that the save(s) has been copied).
- Reinstall the game from scratch using the original name. It's your choice whether to reinstall the 0F-2 version (the download of which you may still have on your phone) or get a newer version.
- Copy the save(s) back.
- Adjust the game settings to match what you did with the now corrupted version.
- See if the save has been corrupted by trying to load it.

It can be noted that the corruption probably wasn't caused by the game, but by something else, as the game doesn't write to those files (the file contains the blueprint for the base camp construction).

**Comment by LeahLuong** [comment]
Reinstallation has seemingly fixed this issue but I haven't done more than successfully load into the game & take a single step to the right. I'll leave the issue open for now because I foresee myself having trouble completing the mission. This may mean changing the thread's title.

Patrik, you probably remember me from another thread a few days ago involving a seg fault & unloading guns. I got 1 of my semi-regular crashes while looking around this lab; the game had no problem reloading @ that time. The file in question had not been edited since I'd reinstalled the game 3 weeks ago, going by its timestamp. & from what I understand, base camps are related to NPC's although there are none in my char's vicinity (AFAIK) nor have I set any base camps during this playthrough. I still think something's up w/ the mission I'm working on & will likely post again once I learn more later today.

**Comment by PatrikLundell** [comment]
I remember.
Someone had a rather similar problem fairly recently, and that person was also lucky enough to be able to recover the save and resume playing after re-installation.

The corrupted file is part of the game installation, not something that is generated by game play, so it should never be written to by the game. It contains blueprints for the construction of one of the base camp options, so it's something available for your use (think cooking recipes, although these generate structures like walls). Actually using them requires at least one companion, but the game doesn't do selective loading (which is good, because that would cause a world of headaches with incompatibilities and crashes caused by load order), so, all of these resources are read by the game upon the loading of a save, which is why the game fails when any of them is corrupted (not fully correct: there are errors that just result in warnings you can just ignore, but those are typically not due to corruption, but due to either hacking or changes to things in the game).

As it stands, I think the corruption is caused by something else on your phone rather than the game itself. "Something else" could be related to the OS (problems with usage of too much memory?), anti virus (I assume phones need that), or anything else that messes around with the file system. It could also be a HW error on the phone causing parts of the "hard disk" (I assume some kind of SD functionality is used) is faulty or flaky. If you have something that checks the integrity of the HW you might want to try that, in particular something that checks the "hard disk".

**Comment by LeahLuong** [comment]
I found a terminal just on the other side of a barracks door I'd previously opened. This terminal falls w/in the diamond-shaped area the map indicator reveals when the mission is assigned. I DL'd from it but Lyman refuses to acknowledge the USB containing the correct data. It's possible the terminal was generated by the previous mission & I didn't notice it before.

So, I opened my debug menu, teleported back to the lab, & spawned a clairvoyance artifact to take a closer look for anything I might've missed. There are no other terminals. There are no connecting subway tunnels to this lab. I noticed another issue regarding this mission was raised last year & it's indicated in that thread the mission is supposed to select the nearest lab w/ a train depot. It didn't do that in my case; I think it merely selected the nearest lab & then failed to activate a train depot terminal because there isn't 1.

Should I open another issue or change the title on this 1?? If change, what would you suggest as a helpful title??

**Comment by PatrikLundell** [comment]
I think the old issue still stands. If it's any consolation, I encountered the same problem with my 0.F-0 character, i.e. being sent to a lab that didn't have any subway depot.

My 0.E2 had similar issues with missing targets (and most all of them that did spawn were not at the level/tile where they should be, but at least they were in the same lab), but in that case terminals spawned directly outside of the refugee center when the quest was assigned. That didn't happen with 0.F-0, unfortunately (although the subway quest worked correctly in 0.E2: it was some other terminal quest that didn't spawn any terminal).

I believe it's possible to debug spawn a USB with the correct data, provided you find the correct name (I had to resort to that when a 0.E2 hub01 mission failed to spawn the mission item in the location where it was supposed to be, and I searched the map files for it in addition to dig through the whole area, so I'm rather sure it was indeed AWOL).

In your case I'd either do nothing about the issue or update the existing issue with a comment that you've encountered it. However, since you can't provide saves it will be of little practical value beyond a nudge.

**Comment by LeahLuong** [comment]
#45973 is a closed issue & only tangentially related. There, the console was missing or destroyed & causing failure on mission assignment. Presumably, the code for assigning this mission was looked @ & repaired but my experience shows otherwise.

**Comment by PatrikLundell** [comment]
Then yes, it's a good idea to make a new issue, although, again, without a save it can probably only serve as a reminder until someone else updates it with a save.

**Comment by LeahLuong** [comment]
Thanks for the help w/ this issue, Patrik.
