### ISSUE TITLE
E-Ink tablet does not recognize nearby books for storing

### ISSUE THREAD

**Issue by ghost** [CleverRaven/Cataclysm-DDA#52920]
### Describe the bug

E-Ink tablet (and laptop) does not recognize nearby books as candidates for storing books, player has to hold books in their inventory for them to be recognized despite standing next to (or over) them.

### Steps To Reproduce

1. use e-ink tablet while standing next to a book
2. can't choose to store said book

### Expected behavior

Being able to store books that the player is standing next to.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 738d25d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Saicchi** [comment]
Resumable activities have a bug where they can't load an `item_location` that is not of the type `Character`, that is, they can only load items in your inventory without an error.

Keep in mind that this issue is still valid, and where it not for this bug, it would have a 6 tiles range just like crafting.

**Comment by AcidAntOnAMinefield** [comment]
I'd probably add to these:
- the fact that the menu closes every time you finish scanning one book, which makes this a ridiculously tedious task to open menu and select options again and again;
- the fact that there is no estimated time for how long a book takes to scan (and yes, every book has its own "time");

**Comment by Saicchi** [comment]
1. Making it popup after you're done scanning a single book is more annoying.
2. Time for scanning is ` 5_seconds * book_weight_in_grams / 5_grams`. Few activities actually tell you how long it will take.

**Comment by AcidAntOnAMinefield** [comment]
> 1. Making it popup after you're done scanning a single book is more annoying.
How is it annoying? The solution to that issue is just making it behave like the game does with eating. "There's nothing left to eat!" but "There's nothing left to scan!" instead, a thing that no one's complained about so far.

> 2. Time for scanning is ` 5_seconds * book_weight_in_grams / 5_grams`. Few activities actually tell you how long it will take.
Yes. And the few that tell you are the ones that are used the most: Crafting, Eating, Reading.

**Comment by Night-Pryanik** [comment]
Fixed by #68880.
