### ISSUE TITLE
NPC Trade Screen broken

### ISSUE THREAD

**Issue by TadhgEomonn** [CleverRaven/Cataclysm-DDA#52935]
### Describe the bug

Does not seem to be a way to move from NPC list to Player list. Result: trading is not possible.

### Steps To Reproduce

Open NPC Trade Screen by choosing trade while conversing with NPC.

### Expected behavior

The screen seems to be redesigned, so I had no expectations.

Best guess for changing selection from NPC to Player and vise versa would be to TAB or Arrow-key in order to toggle from one side of the trade screen to the other.

### Versions and configuration

OS: Win 10
Game version: 55f4f59 (tiles)
Language: English
Mods: DDA, Arcana, Magiclysm, Stats through Skills

**Comment by catdach** [comment]
It's still there, it just doesn't have a default hotkey anymore (presumably because it conflicted with category select that's present in other inventory screens). You can set one manually in the `?` menu while trading (I personally set it to `s`), but it should probably be given some hotkey by default.

**Comment by casswedson** [comment]
I just deleted my `config` folder to test this out, and yes out of the box you can switch between your inventory and a trader's with tab
I guess this has to do with some conflict related to existing keybindings or configuration, but this works by default
![image](https://user-images.githubusercontent.com/58050969/142748757-1f290cfc-b3be-46d4-8084-6e85a1773ed5.png)

**Comment by TadhgEomonn** [comment]
Confirmed: deleting Config folder resets TAB key in trade screen. But why should this be necessary?

**Comment by casswedson** [comment]
As I said something related to existing keybindings or configuration... probably, these kinds of odd interactions are pretty much impossible to predict, the best we can do now is make an issue (edit this one) noting this interaction maybe someone will fix it

**Comment by andrei8l** [comment]
> Confirmed: deleting Config folder resets TAB key in trade screen. But why should this be necessary?

I can't mess with your local keybindings, so the only solution is to add more default keybindings for `SWITCH_LISTS`. I've added `+` to the defaults, but let me know if you have any good ideas.

**Comment by TadhgEomonn** [comment]
I think that following the pattern established by the advanced inventory manager is appropriate, as the new trade screen visually resembles it. User interface should strive for consistency where possible.

**Comment by andrei8l** [comment]
> I think that following the pattern established by the advanced inventory manager is appropriate, as the new trade screen visually resembles it. User interface should strive for consistency where possible.

Isn't this already the case? `TAB` is the default key for switching panes in the AIM too. It just can't be reused if it's already assigned in your local keybindings (i.e. keybindings you've set manually).

**Comment by epsimpson** [comment]
Perhaps the problem is duplicate entries in the local keybindings.Does it need to use both `Next column`/`Prev column` and `Switch lists`?

my keybindings said:

Next column: TAB, LEFT, h, or 4
Prev column: BACKTAB
...
Switch lists: TAB

But none of them worked.

After removing my config folder it changed to:

Next column: LEFT, h, or 4 (removed the TAB from this one)
Prev column: BACKTAB
...
Switch lists: TAB

Now TAB works as expected, but the 4, 6, and LEFT do not.

Shouldn't it be:
Switch lists: TAB, h, LEFT, or 4

and not use `Next/Prev column` at all?

**Comment by andrei8l** [comment]
`Next/Prev column` are used to switch between inventory/worn/map columns that are only shown if your screen is wide enough so the key can't be repurposed without additional changes (ex: force the trade ui panels to always shown only one column)
