### ISSUE TITLE
Grenade pouch and tac vest causing absurd inventory display

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#53044]
### Describe the bug

Wearing the Tac Vest or Grenade Pouch causes the inventory "free volume" and "Volume (L)" values to display absurdly high values. Wearing both actually causes the Volume (L) maximum display to overflow and become negative.

This is presumably caused by #53009, in which is it likely applies to all wearable ammo-type containers.

### Steps to reproduce

1. Spawn Tac Vest and/or Grenade Pouch
2. Wear
3. Look at inventory

### Expected behavior

The effectively infinite volume of ammo containers should not be include in the calculations for inventory volume.

### Screenshots

![image](https://user-images.githubusercontent.com/5107449/143620840-2a27910d-a0ff-4884-9eaa-75d00f2a8a44.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 04d1bce [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots],
    Extra Mutated Scenarios [extra_mut_scens],
    Military Profession Pack [military_professions]
]

**Comment by Hirmuolio** [comment]
It is probably due to the odd pockets.

Pockets without defined size default to 2000000 liters (big default value so pocket without defined size will fit anything inside).

The grenade pouch has container pocket that takes only grenades. Since it accepts only grenades the volume doesn't matter so the pocket has no defined size. So it defaults to 2000000 liters.

Tac vest has one more of such pocket.

Since these are "just normal" container pockets they get added to the carry volume limit. And since the default 20000000 liters is already near the max integer (in ml) limit it rolls over.

The fix would be to set some sensible "max_contains_volume" to these pockets.
Maybe pockets that limit what items can be inserted in them should not count to total carry capacity? Technically their volume is kind of not real since they fit specific items without caring about the size of those specific items.

**Comment by catdach** [comment]
> Pockets without defined size default to 2000000 liters

It may be a good idea to reduce the default pocketsize by at least one order of magnitude, being set to 2000000000 ml might be the cause the overflow due to the maximum stored integer value of c++ being just above it at 2147483647. Probably unnecessary, especially for  this specific issue, but it might be a good way to avoid any unforeseen problems with overflow.

**Comment by ZhilkinSerg** [comment]
Pockets with specific item type filters probably should not contribute to free volume display at all.

**Comment by Terrorforge** [comment]
Yeah, that's kind of a problem anyway. The volume display is often highly misleading because it's counting "free" space in holsters, scabbards and ammo pouches that can't actually be filled any further.

**Comment by bombasticSlacks** [comment]
I ran up against this problem in #52745 originally I didn't want the pockets to interact with the max volume and free volume entries. It was easy to make a pocket with certain characteristics not be added to the displays (total_container_capacity)  however the issue is the items in the pocket still have volume. So if you were only wearing an ammo pouch with 5 shells in it your display would show something like 

Volume(L): .55/0 which is also undesirable. I guess you would have to track what items are stored in such pockets and also ignore their volume when calculating Character::free_space()
