### ISSUE TITLE
Client/server WebSockets structure for tiles to enable WebTiles

### ISSUE THREAD

**Issue by kaosushijin** [CleverRaven/Cataclysm-DDA#53091]
### Is your feature request related to a problem? Please describe.

I run a web-implementation of C:DDA at https://cdda.foxlight.info/ leveraging ttyd @ https://github.com/tsl0922/ttyd.  I've received a lot of positive comments about being able to access Cataclysm through any web browser, but the one drawback most people find is that it does not support tiles.

### Solution you would like.

I'd like to see a rewrite or fork of the tiles code to take advantage of WebSocket to create a WebTiles version of Cataclysm similar to what the Dungeon Crawl: Stone Soup project has done here:

https://crawl.develz.org/play.htm

**Comment by ZhilkinSerg** [comment]
Duplicate of https://github.com/CleverRaven/Cataclysm-DDA/issues/39881

CDDA is much more complex than DCSS, is more actively developed and it was never meant to provide API for custom clients, so that would be a gigantic effort that would also require constant maintenance to support new features.

I would say go with WASM if you want it to run in web-browser.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
