### ISSUE TITLE
Change name of wendigo mutation to something else

### ISSUE THREAD

**Issue by SpeedyDoggo** [CleverRaven/Cataclysm-DDA#53095]
### Is your feature request related to a problem? Please describe.

The wendigo is an important feature of Native American folklore and is often appropriated for cheap horror -- in its folklore, the name isn't even supposed to be mentioned. Currently, there is a mutation tree named for the creature.

### Solution you would like.

Just, change the name. Maybe to something like Leshy (Slavic tree spirit, actually a forest guardian) or Sasquatch, just not what it is currently.

### Describe alternatives you have considered.

I suppose the tree could be removed completely, but I mean, renaming it can't be that hard. (And of course, there's the option to do nothing and continue inappropriately using Native American folklore for the 'cool' value.)

**Comment by Tommy-os** [comment]
But using slavic folklore in this way is ok for you?

**Comment by Zireael07** [comment]
@Tommy-os As a Slavic person I can tell you pre-Christian folklore is just a curiosity, no one really applies much importance to it (unlike e.g. Native American folklore)

**Comment by emomicrowave** [comment]
It indeed seems like depictions of the Wendigo in popculture [aren't really consistent with the Native American idea of the thing.](https://www.backstoryradio.org/blog/the-mythology-and-misrepresentation-of-the-windigo/) In Native American folklore, the wendigo is more representation of evil and greed, than a beast with horns and deer head.

However, looking at the actual mutations in the tree [File 1](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/mods/CRT_EXPANSION/mutations/wendigo_mut_cat.json), [File 2](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/mods/CRT_EXPANSION/mutations/crt_wendigo_mutations.json), everything seems to be vaguely nature-related, such as less scent, faster movement, better hiding, and the mutation process being characterized with a lot of dreams of trees and hunger. 

Two exceptions would be the offensive mutations, which describe bone appendages bursting from your back, or extra bone spurs on one's arms, oozing with acid. These however, seem like they describe a beast, derived from popular depictions of the wendigo, which is again a bastardization of actual native american folklore. Since we have no other elements of said Folklore in the game, it seems easy to just replace the name with something else. An just as accurate depiction would be the celtic [Cernunnos](https://en.wikipedia.org/wiki/Cernunnos), or maybe just use a rough translation such as "Hornbeast".

**Comment by andrei8l** [comment]
Or just assume that the mutation tree is based on the pop-culture "cheap" horror monster rather than its Native American namesake. The zombies (and other monsters) are also based on pop-culture depictions rather than their Haitian/original namesakes.

**Comment by SpeedyDoggo** [comment]
> But using slavic folklore in this way is ok for you? For reference, here's wikipedia entries for each. They are all part of some folklore or mythology.

Yes, I can reference Wikipedia too. I got Leshy from the page "List of Legendary Creatures by Type", which is a great quick reference if you know how to use it and aren't going to grab the first sentence of the creature's article as a 'gotcha.' The difference here is that the creature in question is absolutely NOT meant to be used in this manner -- the name is not meant to be spoken and as emomicrowave pointed out...

> It indeed seems like depictions of the Wendigo in popculture aren't really consistent with the Native American idea of the thing. In Native American folklore, the wendigo is more representation of evil and greed, than a beast with horns and deer head.

So we're not even accurately depicting it, and even from a gameplay perspective, I don't think we should. There's already other mutation trees that have constant hunger as a gimmick. This tree has some unique and interesting features; I like the idea of a forest guardian! Emomicrowave's suggestion of Hornbeast would be a nice change. I suggested Sasquatch BECAUSE it's a US cryptid derived from tall tales and settler folklore, so there's no baggage associated. Glancing through my books on other settler folklore, alternatives could also include the [Hodag](https://en.wikipedia.org/wiki/Hodag) (a cryptid from the northeast US, where CDDA is located I believe) or the [Hugag](https://en.wikipedia.org/wiki/Hugag) (whose depiction in the 2015 edition of Fearsome Creatures of the Lumberwoods seems to be in line with the wanted aesthetic for the mutation tree, though the creature itself isn't actually violent.) Or maybe I'll finally get my wish and see an acropelter in a game? Bandersnatch or rath, to go with the Jabberwocky, could also be an option.

> As a Slavic person I can tell you pre-Christian folklore is just a curiosity, no one really applies much importance to it (unlike e.g. Native American folklore)

Alternatives can be found! Personally, if I saw any pre-Christian Alemannisch folklore make it into a game, I'd be ecstatic, but to each their own, and as above, I went and looked for other, non-Slavic alternatives. :)

> Or just assume that the mutation tree is based on the pop-culture "cheap" horror monster rather than its Native American namesake. The zombies (and other monsters) are also based on pop-culture depictions rather than their Haitian/original namesakes.

It is not cultural taboo to say the names of any other monsters, at least that I'm aware of. A lot of them are also based on existing works of horror that use them in roughly the same capacity as CDDA does (Lovecraft, Junji Ito, The Thing) or are just described/portrayed as monsters. (Lewis Carroll, John Wyndham, a kaiju designed by Koichi Kawakita) That is me actually going through the Hitchhiker's Guide to the Apocalypse monster list. In fact, the zombies and the rat king seem to actually be the only folkloric creatures on that list. (I don't know if there are monsters from CRIT that don't appear, but this is what I saw for the base game.) That said, the idea of a 'living corpse' is not unique to any folklore (revenants and draugr are similar creatures.) The wendigo, in contrast, is specific to its culture, and it's not even being portrayed as what it is, within the bounds of its beliefs.
Not to mention that saying stuff like this perpetuates the silencing and dismissal of Native American culture, which has a....... history. Just because other people are doing it doesn't mean it's okay, and in this case, it's really just a name. Something as small as a name change could make Native players feel much more comfortable; what are the pros for keeping it? Not spending five seconds renaming files and ctr-F'ing to clean up any remaining variables? I'd do it myself and submit a pull request right now, but it's finals weeks and I'm still working through getting my development environment set up. Maybe next week. ;)

**Comment by Zireael07** [comment]
> It is not cultural taboo to say the names of any other monsters, 

Yep, and I agree that the wendigo should go for that reason.

**Comment by andrei8l** [comment]
> That said, the idea of a 'living corpse' is not unique to any folklore (revenants and draugr are similar creatures.) The wendigo, in contrast, is specific to its culture

Man-eating giants exist all over the world too, but your quarrel appears to be specifically with the name and not the properties. And if that's the case then "zombie" is used inappropriately too, along with many other terms.

> and it's not even being portrayed as what it is, within the bounds of its beliefs

That should make it even easier to distinguish between the cultural taboo and the pop-culture reference in the game.

> Not to mention that saying stuff like this perpetuates the silencing and dismissal of Native American culture

No, absolutely not. This argument really weakens your position.

>  what are the pros for keeping it

Removing pop-culture references because they can offend some group on a weak basis is a very slippery slope. I bet there's some culture in the world that has a taboo for every other aspect in the game. Did you know that, in this game, you can drop the Quran in the dirt and rip its pages while binging on alcohol and bacon? When do we stop removing things?

**Comment by SpeedyDoggo** [comment]
> Man-eating giants exist all over the world too, but your quarrel appears to be specifically with the name and not the properties. And if that's the case then "zombie" is used inappropriately too, along with many other terms.

The wendigo is not a man-eating giant. That's the entire issue here. If you want to talk to me about accuracy to folklore, then please show you understand the nature and context of the creatures we are discussing. "Zombie" is an Anglicized loanword from Haitian French/Creole. At the end of the day, it's a dead body walking, and CDDA doesn't use Voodoo in its lore so there isn't even a question of appropriation. 

> No, absolutely not. This argument really weakens your position.

You're proving me right, actually, by dismissing my concerns.

> Removing pop-culture references because they can offend some group on a weak basis is a very slippery slope. I bet there's some culture in the world that has a taboo for every other aspect in the game. Did you know that, in this game, you can drop the Quran in the dirt and rip its pages while binging on alcohol and bacon? When do we stop removing things?

When it's not culturally appropriative. What a person chooses to do in a game is a lot different than literally coding something in. If someone wants to destroy the Quran in their own gameplay........ sure? That only affects themselves? Meanwhile this mutation tree is present in one of the mods shipped with the game itself.
I'm not sure what you're worried about, to be honest. So that name gets changed. What do you think is going to happen next? Talk me through this hypothetical slippery slope you're worried about.

**Comment by LeahLuong** [comment]
What is "cultural appropriation"?? Perhaps you meant "cultural propriety"?? While "zombie" as used in this game isn't culturally appropriate to its etymological roots, I think we can tacitly agree the makers of this game have properly applied the concept as it's widely understood in its memetic sense. I would argue they've done the same thing in naming the wendigo mutation tree. Doggo, you seem to take offense @ 1 but not the other & you cite "cultural appropriation" several times in your explanations but no 1 else is throwing that term around. Could you please define that term??

If, instead, you had actually meant "cultural propriety", please furnish your credential as a cultural gatekeeper. Keep in mind that this discussion is taking place in a forum dedicated to a game we all ostensibly play & so all parties involved are partaking of gamer culture. You may find that gamer culture trumps in matters such as these. The wonderful thing about gamer culture is you can opt out whereas this is not so easily done IRL. Another great thing is that this particular game is so customizable you can choose not to play w/ mods you don't like or even edit the game's files to suit your tastes.

I'm really curious what you mean by "cultural appropriation".

**Comment by SpeedyDoggo** [comment]
> I'm really curious what you mean by "cultural appropriation".

There is a [generally accepted definition that can be found here.](https://www.dictionary.com/browse/cultural-appropriation)

As to why I accept the zombies and not this wendigo business, I'll quote myself: "Zombie" is an Anglicized loanword from Haitian French/Creole. At the end of the day, it's a dead body walking, and CDDA doesn't use Voodoo in its lore so there isn't even a question of appropriation.", "The wendigo is an important feature of Native American folklore and is often appropriated for cheap horror -- in its folklore, the name isn't even supposed to be mentioned." I know I typed a lot and people don't like to read long things, but I feel I've made myself clear that these situations aren't equal.

> If, instead, you had actually meant "cultural propriety", please furnish your credential as a cultural gatekeeper. 

I play this game, will be contributing to the game (mm finals), and am a person with an understanding of the cultural origins of wendigo. I created this discussion to inform and educate others on this topic because I feel it's important to speak up on issues such as these, especially when it's regarding a small change to make the game more respectful of the material in question. If asking for a name change to respect the wishes of Native Americans whose culture this is. While they're not a monolith, [this](https://writingwithcolor.tumblr.com/post/148110282315/seeing-as-you-already-received-an-ask-about-until) [sort](https://midnightparadox.tumblr.com/post/622461305213878272) [of ](https://gardenfog.tumblr.com/post/631304039963967488/im-begging-you-all-to-stop-calling-all-monsters)[thing](https://just-another-hhazbin.tumblr.com/post/653662985236135936/do-you-have-a-link-or-some-direction-regarding-the) [has](https://openjournals.bsu.edu/dlr/article/view/2881) [come ](https://writingwithcolor.tumblr.com/post/133355041681/so-basically-im-writing-a-supernatural-thriller)up in the past and the general opinion is, well, don't use these creatures. Use alternatives. (And yes, I know these are mainly tumblr posts, but please take them as simply hubs for resources and also as firsthand accounts of Native Americans on this topic.)

**Comment by LeahLuong** [comment]
Thanks for the links. If you're going by the definition you provided, this does seem to fit that (conditional on your perspective of "relatively privileged status") although I don't believe you've connected it to a valid argument for why cultural appropriation is wrong in this case. You posit the very name of the creature has some sort of taboo or superstition associated w/ it; I found no such thing in my searches. Did you know that speakers of Algonquian-family languages passed their myths & legends down through oral tradition?? The only reason we know about windigo today is because they were spoken of by pretty much everyone.

Furthermore, this concept of a malevolent spirit going by many different names & guises was not held by just 1 tribe but many spanning a wide geographic region of the northeastern North American continent. The concept may not have even been original to speakers of Algonquian-family languages; tribes & nations in surrounding areas have similar myths & legends. Is it cultural appropriation if it's plagiarized & modified after being appropriated??

You don't seem to be coming @ this w/ a criticism of colonialism so I can only assume you are more in the way of online social-justice activism. Even animals in Algonquian myths & legends have language & agency. Who's to say windigo aren't the oppressed 1's in this picture?? After all, history is written by the victors. There are living descendants of many of the dozens of Algonquian peoples (42 distinct tribes we know of today but there were probably more) but you don't see a lot of windigo running around. It could be seen as a good thing that other peoples are willing to carry on their memory in media other than oral traditions.

> The wendigo, at its core, is not a man-eating giant. That's the entire issue here.

I'm pretty sure that's not the entire issue but I think you could brush up on your lore a little more. Some common characteristics among the many varieties of windigo are their insatiable hunger (sometimes resulting in self-cannibalism), supernatural strength, & large size. They didn't always possess all of these traits but I guess it's hard to maintain consistency across large spaces & times, as well as differences in language while relying on oral traditions as your main source of information transmission. Perhaps some tribes injected their own local flavor to spice things up, somewhat like our own little Cataclysmic tribe has done w/ this meme.

As for those Tumblr links you provided, they seem to simply parrot what you have contributed here. Rather, you are echoing them. I could claim to be Ojibwe Indian here & tell you I'm fine w/ this game's portrayal of my people's legend, wiindigoo. I'm not making that claim but perhaps this shows you how easy it is to masquerade as some1 else online & poison the well. Perhaps you are the 1 masquerading & poisoning, SpeedyDoggo.

In any case, I look forward to your future contributions to this great game. I hope they are more productive & fruitful than this 1.

**Comment by SpeedyDoggo** [comment]
I can see that you've made up your mind about me and will not be listening to anything else I say. I speak from my experience working with members of the Ojibwe tribe, which I was reluctant to cite because they were oral discussions with no public online trace. I understand perfectly how easy it is to lie on the internet, hence my gathering of posts. If I parroted the information in them, then, well, that's how citing my sources works. I don't know what you expected, but if it so bothers you, you can do your own search and get a pulse. I did a surface level search and found only one defeated-sounding post saying it wasn't a big deal vs many, many more that were frustrated at the cultural appropriation, but maybe you'll dig up something more. My keywords were "wendigo tumblr" and "wendigo until dawn" on the Duck Duck Go engine.

Your latest reply shows a lack of understanding of the purpose of citing sources, the inherent connection between colonialism and the appropriation of Native American folklore, and the fact that cultural appropriation takes advantage of existing, often damaging power differentials and is by definition wrong (as opposed to cultural sharing, which is done consensually and with all parties on equal grounds). If you genuinely don't understand these things, then fine; I hope you learn and I hope to see you around after all that. Otherwise, I'd rather not engage with you further; bad faith arguments don't make for productive discussion.

**Comment by Photoloss** [comment]
> cultural appropriation takes advantage of existing, often damaging power differentials and is by definition wrong

If "cultural appropriation" is "by definition wrong" as you claim then you must independently prove that "wrongness" in order to apply the term to a specific occurrence in the first place. If you drop that part of the definition then the term no longer justifies condemnation and you still need to prove that something is actually wrong and requires a change.

So what exactly is wrong with referencing this *fictional* concept in a culture which does *not* adhere to the cited taboo? We are free to speak Voldemort's name (Tom Riddle too), or the many names of the devil, or to [erase the written name of God](https://en.wikipedia.org/wiki/Names_of_God_in_Judaism).

You asked for examples of a slippery slope, well how far do you want to take this in regards to [naming the deceased](https://en.wikipedia.org/wiki/Taboo_on_the_dead#Taboo_against_naming_the_dead)? I'm sure we can find plenty of "marginalised cultures" to claim "appropriation". Do we delay NPC death messages based on in-game time, or real time? Both?

**Comment by LeahLuong** [comment]
SpeedyDoggo, I accept your surrender. You've made it clear through your articulations you'd rather disaffirm my system of beliefs & political ideology, rejecting further reasoned discussion on this topic & perhaps all others. I welcome the oppression points you (willingly or not) donate to me by attempting to silence my narrative. But I won't be silenced & my power will only grow from this encounter. MOOOO! Ah. Ah. Ah.

Your attempts @ logic have failed & so you have resorted to more base tactics such as ad hominem attacks, appeals to authority, & the aforementioned poisoning of the well. I can tell your sense of entitlement will only grow in time. You thought you could strike me down w/ a flick of your wrist but you have only made me more powerful than you could ever imagine. MOOOOOO!!! Ah. Ah. AHHH!

**Comment by Maleclypse** [comment]
I would like to point out that everyone is fighting over an unimplemented mutation category that not only doesn't have any spawn points for it's mutagen or serum, it also isn't implemented enough to go post threshold in.   So Doggo you had to find this via either debug or an uninformed wiki entry and anyone arguing against them is just here to fight some kind of culture war, not actually defend a beloved aspect of the game.

**Comment by kevingranade** [comment]
Closing, @Maleclypse may find the secondary inaccuracy argument compelling, but the primary argument of avoiding it for cultural appropriation or taboo is not.
