### ISSUE TITLE
Reveal sublocation data to players.

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#53139]
### Is your feature request related to a problem? Please describe.

@bombasticSlacks has done an excellent job implementing sublocations and other armor improvements, but I have noticed a problem: sublocation information is poorly communicated to the player.

Consider for example the [chitin arm guards](https://nornagon.github.io/cdda-guide/#/item/armguard_chitin). They cover the lower arms and elbows, at 90% coverage. However, the only way this is communicated to the player is by noting that the total coverage is 36%. This makes it hard to assess how good an armor piece is and especially how it interacts with other armor.

### Solution you would like.

Add the sublocation data to the item UI, probably in a second field below the overall data to minimize clutter.

**Comment by bombasticSlacks** [comment]
I **don't want to convince anyone they shouldn't work on this since I'm already doing a bunch of different things and I'm sure a solution could be found now** however to explain my plan if it doesn't get addressed there are a few things I would like to do/am waiting on and then I was going to actually run the UI design by a friend who is a UI/UX designer for scientific software (which cataclysm isn't _unlike_) and see if I can consolidate and then disseminate some of this information more clearly.

The things I would like to do are make it so material_covers value is applied to hit rolls on sub locations. So on top of the already simulated "you get hit in the lower arm and the hit is absorbed by your chitin arm guards with 90% local coverage", you then have "you get hit in the lower arm and the hit is absorbed by your hard arm guards with 85% local coverage HOWEVER only the nylon is hit not the hard plastic back side" So the chance of a material counting towards absorption should also be depicted which could be a lot of data and therefore might need some clarity.

On top of this @Venera3 is working on generalizing all limbs, so if sub location coverage is displayed to the player there needs to be a way to show to the player the overall distributions for their current limbs. None of it is solidified yet as far as I know but for example if you had digitigrade legs (one additional part on the bottom) you could probably still put shin guards on with 90% coverage of the knees and shins but that's no longer 36% of the leg covered since you have an additional third segment to your limb bellow it. 

Just something for anyone looking to tackle this to consider.

**Comment by Terrorforge** [comment]
#53932 fixed this, but I guess didn't use the proper syntax to auto-close the issue. Closing it manually.
