### ISSUE TITLE
patchwork cotton sheet issue

### ISSUE THREAD

**Issue by flin4** [CleverRaven/Cataclysm-DDA#53178]
### Describe the bug

it takes 8 seconds to get 8 sheets with disassembling a curtain, but 4 and half an hour and another materials to waste to get 4 sheets using recipe in craft menu

### Steps to reproduce

just go and try both of variants

### Expected behavior

maybe 8 hours instead of 8 secs would be more reliable in this case

### Versions and configuration

android, tiles, russian

**Comment by flin4** [comment]
v. cdd2445

**Comment by VoleurVolant** [comment]
In current experimental, so it may be different, it takes 15 minutes to disassemble the curtains and pull the glass intact out of the window, or 9 seconds to pull the curtains down, and I consistently get two sheets out of it either way. It takes one hour with max skill and the sewing proficiencies to _sew_ a single sheet together from scraps by hand, and frankly, that's incredibly low compared to reality; I could probably do that with whipstitch in two or three hours, but it would fall apart the moment a single thread broke, and I've made a ball gown before. My mother, who majored in fashion design and tailoring in actual college, and has sewn custom clothing and storage accessories for 30 of the years since then, says that hand stitching a bedsheet together from scraps in a way that would hold up to abuse just as well as a regular sheet would take her at minimum five hours. I agree that there may be an error here, but it's not even _close_ to the recipe taking too _long._

**Comment by wapcaplet** [comment]
Similar to #49694

**Comment by Michael1993** [comment]
I agree with @VoleurVolant here; in one case you are breaking down a `|| sheet` into 8 equal parts, in the other case, you are sewing together clothing scraps into a bigger thing. The time requirement makes sense in both cases IMO.

**Comment by flin4** [comment]
ok
we know that we can break a curtain into 8 cotton sheets for 8 sec, but also we can cut it up for 2sec into 7 cotton clothing parts wich are needed in quantity of 4 to sew'em together into one clothing sheet that doesn't seem to be something like a bigger thing in this case

**Comment by LeahLuong** [comment]
Sheet be cray cray!

**Comment by Michael1993** [comment]
I vote for this issue to be closed, I think it's covered by the linked issues.

**Comment by wapcaplet** [comment]
Agreed, this is a general problem, more clearly stated in #53059. Closing as a duplicate.
