### ISSUE TITLE
Does clothing/armor encumbrance need a balance pass?

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#53209]
### Is your feature request related to a problem? Please describe.

In the comments of #53070, [Venera3 mentioned](https://github.com/CleverRaven/Cataclysm-DDA/pull/53070#issuecomment-981126396) that armor and clothing should probably have a balance pass regarding overall encumbrance. I think this isn't all that bad an idea, though it is definitely something that is easier said than done. Melee combat is so common that I would bet money that pretty much everyone has gone through it, and everyone has different ideas about how balance should go. I freely admit that I'm mostly thinking about this because I miss the days when torso encumbrance had no effect on melee combat and hit rates. The game certainly got harder for me after #52418 got fixed.

### Solution you would like.

Ideally, we could have some sort of standard or objective measurement for measuring how restrictive clothes are, but outside of someone going to several clothing stores and trying stuff on while measuring range of motion, I don't know how we can do that. And that's before we get to the fact that you can't find the majority of the stuff you'll find in-game at a normal store. 

### Describe alternatives you have considered.

If we can't look to reality for answers here, we can instead just tweak values according to what we would like characters to be able to deal with. If they don't already exist, we can write unit tests that pit characters with various combat skill levels against a number of zombies while wearing various kinds of armor. Then we can tweak encumbrance values until the tests behave the way we would like. I think this is currently the best option open to us if someone were to do this, and the first step to any sort of balance pass here would be to write those tests. 

### Additional context

This issue mainly exists so people can discuss whether this needs to happen and if so, how we should proceed. Something like this shouldn't just be done on a whim. Because this is a balance issue, it probably should be moved over to discussions, so if someone with the ability to do that would do so, that would be nice.

**Comment by Venera3** [comment]
The most sustainable solution I can see is to tie it to the item's material, volume and weight in some dynamic way. The other option is somebody having some ideas, churning through all of `items/` to set everything *just right* and hope that whoever adds items in the future will hold themselves to the concept.

On the less idealistic side, in general armor has a laughably low encumbrance when compared to normal streetwear(Plate's 14 to a stuffed jean's 9), clothing with a lot of pockets generally has very...let's say optimistic min/max encumbrance values (cargo shorts with 7 l of stuff in its pockets coming up to 5 max enc, which is where jeans *start*) and so on.

**Comment by Megadeadly** [comment]
In all honesty, especially for actual armors that aren't fabric, there should probably be some kind of proficiency that decreases the encumbrance of armor as the proficiency increases. Using plate armor as an example, someone who has never worn it before, regardless of their strength, is going to be INCREDIBLY clumsy in a full suit at first, and is going to have trouble swinging their weapons properly.. Someone who is experienced wearing it, on the other hand, could probably literally do cartwheels in full plate, and swing properly. That being said, I have no idea how hard it would be to implement, and just the balancing of doing so alone would be massive. Instead of a proficiency, maybe it could be a per-armor basis of getting used to wearing it, IE getting used to heavy survivor doesn't get you used to anything else not closely related. I think sheathes might have something similar already, where holstering/unholstering with the sheath lowers the move cost to do so over time (not sure, and I don't know the code for it regardless), so maybe that could be modified for the armor skill.

**Comment by Inglonias** [comment]
> The most sustainable solution I can see is to tie it to the item's material, volume and weight in some dynamic way. The other option is somebody having some ideas, churning through all of `items/` to set everything _just right_ and hope that whoever adds items in the future will hold themselves to the concept.
> 
> On the less idealistic side, in general armor has a laughably low encumbrance when compared to normal streetwear(Plate's 14 to a stuffed jean's 9), clothing with a lot of pockets generally has very...let's say optimistic min/max encumbrance values (cargo shorts with 7 l of stuff in its pockets coming up to 5 max enc, which is where jeans _start_) and so on.

I like this idea, but would like to add that if something like this is done, it would probably be best if we also expanded the scale of encumbrance. For instance, we could double the numbers and halve the effects so that things remain consistent and we can have some more granularity.



> In all honesty, especially for actual armors that aren't fabric, there should probably be some kind of proficiency that decreases the encumbrance of armor as the proficiency increases. Using plate armor as an example, someone who has never worn it before, regardless of their ability to handle its weight, is going to be INCREDIBLY clumsy in a full suit at first, and is going to have trouble swinging their weapons properly.. Someone who is experienced wearing it, on the other hand, could probably literally do cartwheels in full plate, and swing properly. That being said, I have no idea how hard it would be to implement, and just the balancing of doing so alone would be massive. Instead of a proficiency, maybe it could be a per-armor basis of getting used to wearing it, IE getting used to heavy survivor doesn't get you used to anything else not closely related. I think sheathes might have something similar already, where holstering/unholstering with the sheath lowers the move cost to do so over time (not sure, and I don't know the code for it regardless), so maybe that could be modified for the armor skill.

Going this route is also an option, but I think that it should be a little less specific. "Heavy armor", "light armor", etc. I also think that if we do this, it should ONLY apply to armor, since the vast majority of humans on Earth wear clothes on a daily basis, and therefore know how to move around in them, but a much smaller percentage wear armor daily.

**Comment by cataclysmsurvivalist** [comment]
I second this. It makes sense that armor slows you down in melee because you will always move more fluidly by wearing little, but armor, regardless of whether it is modern or classical, was always made specifically with the user's mobility in mind. Even medieval steel armor, the most famous example of heavy armor that protects the user at the cost of speed, is still far more mobile than modern portrayals give them credit. They will SLOW you down, but leave your actual dexterity reasonably alone.

In my opinion, encumbrance should be less affected by how clumsy the clothes/armor is to use in general, and more about how uncomfortable they are to use in actual combat. And just like others have recommended in this thread, the encumbrance for specific clothes should go down as your character's conditioning to wearing them in combat improves.

**Comment by Alex-Folts** [comment]
High level of athletic skill could reduce encumbrance for heavy(the one which have high weight) clothes(including light clothes with pockets filled with lead)/armor and weapons. Currently athletic have effect only for swimming but definition of athletic is pretty broad and sports related so it can fit somehow.

**Comment by Photoloss** [comment]
First of all "encumbrance" needs to be split into "weight" and "bulk". 3 cm of solid steel strapped to your forearms, upper arms, thighs and shins will basically not obstruct your range of motion *at all* if you leave the joints uncovered, but most people would be unable to lift that amount of weight. On the flip side a plastic broom handle stuck through your belt weighs almost nothing but makes swinging a sword all but impossible.

Both are hindrances, but their effects are different. They also shouldn't stack directly while multiple bulky items should rapidly ramp up their effects. Weight mostly makes you tire out faster and might slow you down a bit or make sniping more difficult, bulk is responsible for most types of fumbles and also describes the main effects of mouth and eye encumbrance (an open-mouthed mask made of thick solid lead wouldn't really impede your breathing, a thin film of plastic over your mouth and nose will kill you).

> The most sustainable solution I can see is to tie it to the item's material, volume and weight in some dynamic way.

This will not work. Chainmail is the best counterexample as it is made of iron or steel with considerable weight but arranged in a way where it behaves more like soft non-elastic fabric. Even without my proposed split the opening example of thick plated arm/leg guards presents an issue when compared to something like a skintight leather/latex bondage suit. A [hobble skirt](https://en.wikipedia.org/wiki/Hobble_skirt) or wedding dress also fares very poorly compared to jogging pants due to the cut. Worse still I would rate long underwear quite non-restrictive despite being skintight too, and an improvised or poorly fitted plate armour goes on the "outer" layer but will lock down even an experienced wearer quite severely. All in all we'd be looking at a minimum of 2-3 exception flags which every item would need to be audited for, at which point we can just do so for encumbrance or even my split version.

**Comment by Inglonias** [comment]
We already account for weight by the total weight carried by the character. If you want to split that weight by body area, be my guest, though. That would certainly help. Encumbrance is purely about the bulk of the worn clothing.

**Comment by Photoloss** [comment]
> We already account for weight by the total weight carried by the character. If you want to split that weight by body area, be my guest, though. That would certainly help. Encumbrance is purely about the bulk of the worn clothing.

The problem with that is how as I already said slapping on armour to cover rigid sections does not really impede movement via "bulk" *at all*. If we explicitly define encumbrance as only bulk then all the arm/leg guards should have values comparable to tight jeans and any helmet which doesn't cover the ears or neck should be in that range as well. On the flip side large pockets would become useless making inventory management extremely frustrating.

This does not reflect reality. A weight on your forearm is extremely tiring and slows the movement of your arm, that same weight around your waist is almost meaningless. Also the current system is rather all-or-nothing where you can haul a large amount of stuff at no penalty whatsoever then it suddenly nannies you because "overweight" with a setting to outright forbid you from picking up additional items and strict penalties which drain your stamina almost instantly.
