### ISSUE TITLE
Can only pick up frozen liquids with certain conditions

### ISSUE THREAD

**Issue by stelscarrot** [CleverRaven/Cataclysm-DDA#53221]
### Describe the bug

Frozen liquids pick up mechanic is inconsistent

### Steps to reproduce

1. Find frozen water in toilet
2. Try to pick up in g menu
3. You cant
2b. Try to pick up in / menu
3b. You can

### Expected behavior

Either ability to pick up from g menu, or inability to pick it up from / menu

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: c232b41 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by martosss** [comment]
To build up on frozen liquids
You can also have frozen water in a pot and unload that pot => the water goes into your inventory.
You can also pick up frozen blood.

Then, when you decide to heat it up and defrost, the liquid casually stays in in your inventory and can be carried.

Liquids that are frozen get stuck in your inventory - Before you unfreeze you cannot move them in any container, since they're frozen and... I don't know ... so what if they are frozen?

It should be possible to put away that frozen water/blood if you're able to pick it up in the first place.

I think frozen liquids are not meant to be picked up and carried at all. That would make most sense to me(although it's very annoing during winter time).

**Comment by EddiTheBambi** [comment]
> [...]
> Liquids that are frozen get stuck in your inventory - Before you unfreeze you cannot move them in any container, since they're frozen and... I don't know ... so what if they are frozen?
> 
> It should be possible to put away that frozen water/blood if you're able to pick it up in the first place.
> 
> I think frozen liquids are not meant to be picked up and carried at all. That would make most sense to me(although it's very annoing during winter time).

I know this is an old comment but due to the recent activity on ralated issues I though I could clarify this somewhat. I wrote the [original PR](https://github.com/CleverRaven/Cataclysm-DDA/pull/32763) on this and back then containers like bottles used items as "ammo", essentially you would "reload" a bottle with water. Now that containers are more generic I assume the functionality of reloading a bottle with frozen water is broken. You should be able to pick up and manipulate frozen liquids, this part of the game just hasn't received much attention until now. Kudos to @EIIKaO for picking up the torch!

**Comment by EIIKaO** [comment]
@EddiTheBambi Thank you for your explanation, I understand more about the context.
I found your implementation of the feature what breaking frozen liquid to make it carryable with the hammer is very unique and interesting. I have been challenged to make it more practical on current situation( not sure if it will work… ).
