### ISSUE TITLE
Harvesting mutagen samples is extremely stingy

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#53256]
### Describe the bug

The odds of getting a sample while dissecting animals are much too low. Even with health care 10 and a scalpel, I've spent several days dissecting all ~10 cows in a dairy farm and received only a single bovine sample. With a single dose of mutagen requiring 3, that's pretty rough.

This renders even what should be relatively easily acquired mutagens, such as cattle, functionally unattainable, and rare samples like molerat are just complete pipe dreams.

### Steps to reproduce

1. Give yourself health care 10 and a scalpel
2. Dissect a bunch of cows (or other sample-carrying animals)
3. Despair

### Expected behavior

Recipes should have ingredients that are possible to acquire in practice. Here are a few suggestions for how to adress the problem:

- Drop the recipe requirement to 1 sample
- Increase the drop rate, probably all the way to 100%
- Actually, increase it beyond 100%. The rarer monsters especially could stand to drop multiple samples.
- Increase the number of monsters that drop samples. Bovine samples could become "ungulate samples" and be dropped from deer and moose, lupine samples could be dropped by every kind of dog, etc. This might include mutant and/or zombified versions of animals.
- Courtesy of @Venera3: make samples a non-consumable tool when making mutagen, consume it only when crafting serum.

Probably we need to implement multiple of these. 100% drop rate and 1 sample per mutagen would make cattle possible, but molerat samples would still be too rare for troglobite to be remotely practical.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 40e9432 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots],
    Extra Mutated Scenarios [extra_mut_scens]
]

**Comment by Maleclypse** [comment]
Microlabs also should have dozens of samples now.  I'll go check that later tonight and review this.

**Comment by Venera3** [comment]
I think there are some general problems with the mutagen crafting gameplay. Samples are imho a step in the right direction, but they have some teething problems:
- There's no reason to craft basic mutagen if you can craft the serum (and there's like one book that contains one recipe but not the other)
- Instead of a long-time project of tinkering with you phenotype it's pretty much a one-time investment of "batch-craft 20 mutagen, turn it into 10 serums, break your threshold, profit"
- Nothing about it is *hard*, a lot of it is *boring* - scientists drop books like candy, and both bleach and zombies are both in ample supply. This is the part that's made more involved by samples, but they don't play nice with us having no dynamic mob spawns

Things I'd suggest:
- Turn samples into tools for the mutagen, but require a few for each pop of serum as ingredients
- Break up the recipe sources a bit more, and take them out of the sci zed droplists. That whole list could use a thorough pruning, but we have a lot of lab counters that the recipes could reasonably live - when specialized labs become more of a thing we could break it up along those lines.
- Make serums less of a straight upgrade over basic mutagen - reduce the number of traits gained to that of mutagen, or have it roll a secondary category for bad mutations. That should make serums a more surgical investment, made only to break your chosen threshold (and possibly eating up your precious sample stock, per the first suggestion).

**Comment by Terrorforge** [comment]
> Microlabs also should have dozens of samples now. I'll go check that later tonight and review this.

I haven't checked them yet, and I'm on 0.5 item rate so I'm probably not a good judge anyway, but given that there are about a dozen different kinds of sample, isn't "dozens of samples" still only going to work out to like 3 or 4 of any given one? That might be fine if mutagen required a single sample, but scouring an entire microlab to get enough material for just one or two doses still seems a bit unreasonable.

**Comment by Maleclypse** [comment]
> I think there are some general problems with the mutagen crafting gameplay. Samples are imho a step in the right direction, but they have some teething problems:
> 
> * There's no reason to craft basic mutagen if you can craft the serum (and there's like one book that contains one recipe but not the other)
> * Instead of a long-time project of tinkering with you phenotype it's pretty much a one-time investment of "batch-craft 20 mutagen, turn it into 10 serums, break your threshold, profit"
> * Nothing about it is _hard_, a lot of it is _boring_ - scientists drop books like candy, and both bleach and zombies are in ample supply. This is the part that's made more involved by samples, but they don't play nice with us having no dynamic mob spawns
> 
> Things I'd suggest:
> 
> * Turn samples into tools for the mutagen, but require a few for each pop of serum as ingredients
> * Break up the recipe sources a bit more, and take them out of the sci zed droplists. That whole list could use a thorough pruning, but we have a lot of lab counters that the recipes could reasonably live - when specialized labs become more of a thing we could break it up along those lines.
> * Make serums less of a straight upgrade over basic mutagen - reduce the number of traits gained to that of mutagen, or have it roll a secondary category for bad mutations. That should make serums a more surgical investment, made only to break your chosen threshold (and possibly eating up your precious sample stock, per the first suggestion).

I've been hoping someone else would take up breaking up the mutagens and serums into different books and also breaking up the mutagen books to only have two different mutagen strain recipes each.  I support basically all of this.
