### ISSUE TITLE
Zombie Mutation Lines Part 1 - Shockers.

### ISSUE THREAD

**Issue by sleepingdreams** [CleverRaven/Cataclysm-DDA#53260]
### Is your feature request related to a problem? Please describe.

I'm CwasCard#7191 on the official Discord, and I've been thinking up, trying, and failing tmo implement new mutation related content for CDDA. I saw [I-Am-Erk's zombielike mutation ideas on the Cataclysm_DDA subreddit.](https://www.reddit.com/r/Cataclysm_DDA/comments/ootj9o/help_me_think_up_some_mutation_lines/) There's also a lot of interesting stuff in the comments. I'm not good at programming and I don't know the first thing about C++, so I feel like the JSON parts of this is something that'd suit me - if I could _pick up_ some C++ along the way that'd be cool too.

### Solution you would like.

**piezoelectric skin**: your skin generates a trivially small electric charge which may cause you to emit a bit of light once in a while. You gain a little electricity immunity.
I'm not actually sure how to do any of the random stuff noted here. I _can_ do the electric resistance.

-- "**piezoelectric skin**" mutates into arcing skin: you constantly emit light, and once in a while bright flashes come off you which can slightly damage NPCs and monsters adjacent to you.
I can do something that copies-from Mana Luminance or any of the Photophore mutations. I'm not sure how to make the "once in a while" thing - I _think_ I can add an autocast spell with a certain cooldown?

---- "**arcing skin**" mutates into incandescent skin (threshold only): you constantly arc electricity, glowing brightly. You can activate or deactivate zapback, causing mild shock damage to anything adjacent to you.
I can make a spell for this effect, but I'd like it to simulate the incandescent husk field effect as faithfully as possible. Casting a spell every turn is going to slow down the game _a lot._ Would the same ("emit_fields": [ { "emit_id": "emit_shock_cloud", "delay": "1 s" } ],) thing work if I stuck it onto a mutation/enchantment?

-- "**piezoelectric skin**" mutates into piezoelectric control: you can turn your piezoelectric skin on and off, and when on, you emit a constant very low light
This is as simple as copying controlled photophore.

---- **bioadaptive insulation** requires "piezoelectric control" (post threshold): when your piezoelectric skin is disabled, you are immune to electric damage and take reduced damage from heat and acid.

I can do a transforming mutation similar to Hyper Metabolism that gives you armor values/immunity flags.

---- **capacitance gland** requires "piezoelectric control" or "arcing skin" (post threshold). You can emit a short range, powerful blast of electricity and light. It takes a few minutes to recharge and costs some stamina and calories.

The easiest way to implement this would be a spell, again, but I'd like to make it as similar to the shocker zombie attack as possible - mainly for the cooldown. 

---- **focused voltage** requires either "piezoelectric control" or "arcing skin". You can charge batteries held in your hand at a rate of 1 charge per turn, costing 1kcal per charge.

I'm not sure how I would make this work. I know it'd be _some_ sort of C++ that has something like - "If this mutation is active, check if this list of items is in your hand. If an eligible item is in your hand, remove 1 kcal of stored nutrient and restore one ammo to the item."

Apart from the ones I-Am-Erk listed, I think that both branches would have the standard "strongman" mutations - increased strength, toughness, chemical imbalance, etc. In the case of the controlled shocker line, I would like to give it some speed mutations to simulate shocker brutes, higher-order strength mutations and _something_ similar to how EMPs interact with CBMs, but worse. Probably moderate limb damage & high pain. I'd like to do the same with the incandescent husk line - give it speed _reducing_ mutations, but give it more health.

Any thoughts?

### Describe alternatives you have considered.

Not having any of these mutations, which would then lead to a nonexploration of other lines that emulate zombie abilities, like acid zombies, bone zombies, ETC.

### Additional context

If I can get this done, I could probably try the acid line next. My ideal bone line would have an _insane_ amount of C++ required, so I don't think I could do that on my own.

**Comment by Photoloss** [comment]
I'm privately tinkering with a "fragile speedster" version, the husk field is easy via the "emitter" property of enchantments. Zapback can be done via a spell trigger but I can't get a custom damage message to display. For the lightning attack there are two options: fake guns which are kinda janky, and spells which do not seem to get removed if the mutation is purified.

The best I can think of for hand charging in JSON is spawning battery charge or a new battery item.

Also of note is the ability to take damage from water as if it were acid, a skinny dip with *my* Incandescent mutation will outright kill you if you don't have a towel ready at the moment.

Still trying to figure out how to eat batteries without maintaining a custom whitelist of all other edible materials.

And yes incandescence+electric immunity is stupidly OP.

**Comment by estebandellasilva** [comment]
Maybe stupid ... but this looks like it should be able to Charge the CBM PowerStorage?

**Comment by Photoloss** [comment]
> Maybe stupid ... but this looks like it should be able to Charge the CBM PowerStorage?

EMP it more likely. That one's easy.

Actually charging bionic power might be possible via negative spell costs, I don't want to add deliberate extra synergies to an already strong "all the things, all the power" approach.

**Comment by PatrikLundell** [comment]
One way to keep this mutation line from becoming overpowered (in one dimension) would be for it to interfere with CBMs such that post threshold mutation would fry any CBMs, while the early ones would interfere with them (you don't want to get your cyborgified player to get a random mutation and suddenly have everything just fried). If possible, an early mutation might cause intermittent malfunctions, bionic power drain, etc.

**Comment by anoobindisguise** [comment]
Oh neat! I was brainstorming for some zed mutation lines too. I had Hulk done and planned on submitting that when I had the time, and I also planned for shocker - I had in mind a sort of int/dex focused bonus that was fast and needed very little sleep since your nervous system is in "overdrive" thanks to your electric flow. Insulation/total protection from discharge, static charge (hair stands on end all the time!) and eventually lightning powers. 
As far as downsides go I hadn't worked out everything but neurological problems, such as jitters and insomnia (possibly some sort of super-insomnia for shockers specifically, you'll need sleeping pills or chloroform to knock yourself out?) as well as dry skin/really high thirst, all seemed like good ideas to me. I'm really looking forward to implementing zed lines as well.

**Comment by Photoloss** [comment]
>  int/dex focused bonus

Not a fan, zombies are pretty much the opposite of smart and dextrous and stat bonuses grant rather broad benefits which can more easily undermine less combat-powerful lines.

> possibly some sort of super-insomnia for shockers specifically, you'll need sleeping pills or chloroform to knock yourself out?

There's one rather tricky problem here: without immunity any kind of electric field spawn will hurt you and thus probably wake you up within minutes at most. So either players get the option of disabling the field at will (and thus will probably keep it off to save on whatever cost it has) or you can't have any zappy fields prior to gaining immunity to them. With any luck #53135 might add enough granularity to allow meaningful partial immunity and allow sleeping with it.

> really high thirst

I'd save that for one of the others, self-electrolysis would have too many other nasty effects and nothing else consumes water specifically. I wonder if there's a meaningful way to do "low stamina, fast regen" though so you need to "recharge" more often and dart in and out of combat instead of steamrolling through.

> oh, and Large! Since shockers become brutes!

This is the main design splitting point for me. I'm leaning towards a speedy "electricity"-themed line as too many others also turn into tanky brutes, but the most accurate "shocker zombie"-themed line would indeed become very slow, tanky and strong.

Beyond just the shocker line, what else would be "worth" adding? Fire is an obvious one because it's flashy, but acid already overlaps with slime. Then bone would basically be the same as any of the sturdier animals (or going minmax with hooves/talons+chitin), smoke+shady might be interesting and then all the other zombies aren't all that interesting to play as.

**Comment by anoobindisguise** [comment]
Synthetic (mix of kevlar, rust and gasoline lines, based around incorporating inorganic stuff), acid, bone, shocker, hulk are all reasonably distinct. Boomer could be some sort of slow/tanky line with a broad diet and a shiftQY superpower, Shady/nightstalker might be too much like Trog but could have distinctive elements. Grappler and Hunter are two unarmed melee options, could merge those together. Necromancer could be some sort of ultra-high-end mutation but I don't really know if you could get zeds to obey you lol.

**Comment by Photoloss** [comment]
All of those sound like they'd basically equate to pre-threshold mix-and-match critters we already have. What unique features or gameplay elements would those lines offer?

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
