### ISSUE TITLE
New zone feature: Sort items within containers

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#53292]
### Is your feature request related to a problem? Please describe.

Zones are a very useful way to perform mundane actions in a large area. [I am generating a new project entry](https://github.com/CleverRaven/Cataclysm-DDA/projects/47) to expand this using temporary zones, allowing players to do a mundane action in a large area that is temporarily specified and deleted when the job is done. This allows us to create a bunch of new zone activities that would be a bit impractical using the current "persistent" zone interface, just becaues it's annoying to manually create and delete a bunch of zones.

### Solution you would like.

This extends #53290, although it doesn't explicitly require it.

Currently, loot sort zones ignore containers. With dead zombies now functioning as containers, this minor problem becomes more major, preventing us from sorting loot from zombie corpses easily.

I suggest we create a new variant of "loot: unsorted", `"loot: unload & sort"` for loot that we want to remove from containers. At some place in options we should allow some ability to define what is excluded from this, but for default we should exclude liquids (obviously), all sealed containers, and ammunition in magazines. Additionally, I am unsure how many nested container levels we should go up. I would say "full recursion" but this could cause some messiness?

This new sort zone would be the default for area actions, but you could switch in the options section.

### Describe alternatives you have considered.

Another option would be a whole new zone action for "unload all containers" with subsets to include and exclude certain things

### Additional context

This is part of a [larger project](https://github.com/CleverRaven/Cataclysm-DDA/projects/47) that I suspect will have *vast* qol and NPC management implications.

**Comment by PatrikLundell** [comment]
If pulping ends up (risking) damaging items and/or cause pulping to take longer it looks like an "optimal" strategy would be to remove "valuable" items and pulp resisting items in a first pass, pulp all corpses, and then sort out the rest without stress. However, if you've just taken down all the zombies in the area you've got lots of time to pick their corpses clean before there's any risk of them revivifying on you.

I think basic corpse loot sorting shouldn't be too nested, because the more items you have, the longer it takes to load and unload them for hauling (as well as sorting them). However, there are two groups of containers, namely those just used to carry "stuff", and those dedicated to specific sets of "stuff". The first set contains pockets in clothing and backpacks that contain a jumble of items, and the second contains things like MREs, pill bottles, and IFAK pouches.

A major problem with sorting in the open is heat stroke. Heat management is a major problem during the summer, and sorting is an activity that can take a huge amount of time if you're unlucky with your filter (make VERY sure you exclude glass shards!), and you don't have many minutes out in the open before you have to go and cool down. Thus, I'd want to be able to break off when getting hot, not when getting pain from overheating.

**Comment by Paragonid** [comment]
"How many nested container levels we should go up" could be another user setting

**Comment by I-am-Erk** [comment]
Yes ideally we probably just need a setting somewhere for "how recursive".

**Comment by I-am-Erk** [comment]
#53346 adds an automatic unload feature, but I do think we still need an explicit zone for sorting without unloading. The default behaviour for an "unsorted - don't unload" zone should be to ignore containers with things in them, I think, because it's likely not ever the goal for players to sort containers full of stuff into a "containers" pile, but players may wish to stack a lot of stuff, sort it, and then go through containers more carefully. In the future if we can devise some smarter algorithms for sorting containered items, then the second no-unload zone could start using those (eg. If a container has only a single type of item, or items that all go into the same sort zone, sort it where that item goes)

**Comment by bombasticSlacks** [comment]
I think I've done all of the things needed for this at this point, let me know if I should re-open it.
