### ISSUE TITLE
Repeatedly acquiring Reflex Photophore mutation

### ISSUE THREAD

**Issue by Sohex** [CleverRaven/Cataclysm-DDA#53324]
### Describe the bug

Using concentrated mana serum can cause you to gain the Relfex Photophore mutation when you already have it. The issue appears to be related to the fact that the Relfex Photophore can be in the (on) state, that is to say the check for existing mutations looks for "Reflex Photophore", but not "Reflex Photophore (on)".

This appears to be a regression, see https://github.com/CleverRaven/Cataclysm-DDA/issues/46217 and https://github.com/CleverRaven/Cataclysm-DDA/pull/46507

### Steps to reproduce

1. Acquire the Reflex Photophore mutation.
2. Take concentrated mana serum while Reflex Photophore is (on).
3. Lose and regain the mutation.

### Expected behavior

The Reflex Photophore mutation should not be available in the possible mutation pool if it's already been acquired.

### Screenshots

![photophore](https://user-images.githubusercontent.com/1780072/145484854-e8ca6683-1a1b-4a42-875b-5c6d2f4e6727.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 9600194 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Terrorforge** [comment]
Now that you mention it, I've seen the same behavior with Chimera's Hyper-Metabolism and Medical's Normal Human/Violent Monster

I _also_ saw something that looked kind of similar where Ursine Serum kept swapping out which muzzle I had (from ursine to rat and back to ursine), but I have no idea if that's related.

**Comment by Michael1993** [comment]
From the code it seems like there is a big difference between activated (you switch it on) vs. triggered mutations. For example:
`Web Weaver` (and other activated mutations) is handled in code (see [this example](https://github.com/CleverRaven/Cataclysm-DDA/blob/611e3ea7898cd0eba8b1ff7d49e286de870b4524/src/character.cpp#L4672-L4673)). `Web Weaver` also doesn't have a "replacement" entry [in mutations.json](https://github.com/CleverRaven/Cataclysm-DDA/blob/611e3ea7898cd0eba8b1ff7d49e286de870b4524/data/json/mutations/mutations.json#L4547-L4556).

Why is this important info? Well, when checking for mutations, this bit of code:
```
bool Character::has_trait( const trait_id &b ) const
{
    return my_mutations.count( b ) || enchantment_cache->get_mutations().count( b );
}
```
checks if you already have a certain mutation. This works with `Web Weaver` because it's a single mutation. It doesn't work with `Reflex Photophore` because that [is actually two separate mutations](https://github.com/CleverRaven/Cataclysm-DDA/blob/611e3ea7898cd0eba8b1ff7d49e286de870b4524/data/json/mutations/mutations.json#L15-L62) (in a survivor trenchcoat?). The same thing is true for `Normal Human/Violent Monster` and Chimera's `Hyper-metabolism`.

I do not have a fix suggestion for this issue (yet), but I thought I'd share this info, in case whoever tackles this finds it useful.

**Comment by Michael1993** [comment]
I think if all of these mutations referenced their counterparts in their `"changes_to"` section, this would be solved.

My reasoning is that `Character::mutation_ok` uses `has_child_flag` to ensure a mutation is OK (i.e.: you can't evolve `Strong` if your survivor is already `Very Strong`) but all of the triggered mutations have `"valid": false`, meaning they can't get chosen.

**Comment by Maleclypse** [comment]
@MylieDaniels I was looking at this and wondered if your changes you’ve made on how categories work would have impacted this or eliminated it?

**Comment by RenechCDDA** [comment]
@Maleclypse This is a bit late, but I can confirm it is still an issue.

![image](https://user-images.githubusercontent.com/84619419/201464528-d3afe480-8159-48c7-9896-6ec4372c6fef.png)

It seems like you could get around it by obsoleting BIOLUM1 and replacing BIOLUM0's transform with an enchantment. I think you would end up losing the message about it turning off, but it would retain the desired game functionality. (Basically take bio_flashlight's enchantment and change it to `DIALOG_CONDITION - ACTIVE`, then copy over the dialog conditions from the existing one).
