### ISSUE TITLE
In regards to the furniture system in development: the player should be given the option between placing the Fridge down as furniture, or installing it into a vehicle as a regular vehicle part.

### ISSUE THREAD

**Issue by cataclysmsurvivalist** [CleverRaven/Cataclysm-DDA#53349]
### Is your feature request related to a problem? Please describe.

I can tell the devs are testing out how to best implement powered furniture, but even so, some furniture should still be allowed to be installed as vehicle parts like most electric gadgets are. This is a matter of not just gameplay convenience but also immersion; for so long the survivors have been able to put all sorts of heavy duty gear onto their powered supercars, why shouldn't they be able to do it with furniture, powered or not?

### Solution you would like.

The Fridge should be treated as a vehicle part to be installed into any car, but the player could also (a)ctivate it to deploy it as furniture.

**Comment by Fris0uman** [comment]
The whole point of this is to move all the awkward powered vehicle parts to be furnitures like they're supposed to. Making furniture be able to be used as veihcle part is the opposite of what we want and It would be a giant pain code-wise to implement.

**Comment by esotericist** [comment]
standalone refrigerator appliances and devices intended to be installed into vehicles are rather different objects, and we want to reflect the tradeoffs between them (standalone appliances generally having higher capacity and sometimes efficiency, but not being able to be installed in a movable vehicle because they aren't designed for it).

as fris0uman says, the feature request here is the opposite of the goal, and is not going to be happening in the core game.

further, the fact vehicles are too trivial to extend is not justification for further trivialities; we ultimately intend to make vehicles have more tradeoffs go into their construction and modification, we're mostly waiting on other infrastructure to manifest first (including better general support for appliances and stationary power grids).
