### ISSUE TITLE
Turning off the 'Self Aware' mutation does not turn off the ability to see exact Pain numbers

### ISSUE THREAD

**Issue by cataclysmsurvivalist** [CleverRaven/Cataclysm-DDA#53473]
### Describe the bug

If the Self-Aware trait is taken during character creation, turning it off takes away the ability to see health on limbs, but not the exact number of pain. The vague terms for pain thresholds (Distracting, Minimal, Intense, Severe, etc.) aren't used as they would for normal characters, instead it's shown as the exact number.

### Steps to reproduce

1. Make a character with the Self Aware trait
2. Turn 'Self Aware' off in the 'View/Activate Mutations' section
3. Get hurt by any monster

### Expected behavior

When Self-Aware is not turned on, the exact pain number should be replaced with the vague terms as is for characters that weren't created with the Self-Aware trait.

### Versions and configuration

build type: windows-tiles-x64
build number: 2021-12-15-1210
commit sha: 373cf4e8d511e8773f6fbc52fa07c55d8ee2010a
commit url: https://github.com/CleverRaven/Cataclysm-DDA/commit/373cf4e8d511e8773f6fbc52fa07c55d8ee2010a

(I've looked for any guides that told me exactly where the report the game makes in the debug menu goes, but the 'debug' note file I found clearly wasn't it as it was too long, so I went with the game version for this report)

**Comment by Nerdy314159265** [comment]
I don't believe the Self-Aware trait is toggleable (at least not in the latest stable), it seems to be an always on passive with a instant activation that just spits out your overall health.

**Comment by Paperbell** [comment]
Self-aware doesn't seem to be toggling for me, just giving me a health value. 

While I can't reproduce, [`panels.cpp`](https://github.com/CleverRaven/Cataclysm-DDA/blob/1a4af960a871a144b7aa43fe90f7b1198ff59eea/src/panels.cpp#L861) shows that `self-aware` is nullified by `deadened` for hitpoint display, but not pain display.

**Comment by VitreousEyes110** [comment]
I was unable to reproduce this bug in the latest experimental. Created a character with self-aware, removed the trait with debug and instilled pain using both debug pain and a spawned monster, the pain showed an approximate word as it should. It also seems to function properly if the pain is instilled before removing the trait, and if the trait is added via debug instead of during character creations.
![Screenshot (330)](https://user-images.githubusercontent.com/45680256/146302681-6eb7baf0-3468-4d87-b201-9211a8f56fc9.png)
![Screenshot (331)](https://user-images.githubusercontent.com/45680256/146302691-563d4927-3b97-4abc-bf58-dc07126cdead.png)

Game Report:
- OS: Windows
    - OS Version: 10.0 1607
- Game Version: 1a0d064 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by hexagonrecursion** [comment]
> Self-aware doesn't seem to be toggling for me, just giving me a health value.

Same here

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: cfc00fa [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Nerdy314159265** [comment]
I had thought that Self-Aware isn't a toggle, it's a passive with an activation effect like a Blood Filter CBM with passive bonus.

**Comment by wapcaplet** [comment]
It is a bug for the Self-Aware trait to be "deactivatable" like this.
