### ISSUE TITLE
Inconsistent amount of manure used in soft adobe brick recipe

### ISSUE THREAD

**Issue by friendfrog** [CleverRaven/Cataclysm-DDA#53507]
### Describe the bug

I was looking at  chezzo and I noticed that the recipe for soft adobe bricks uses 1x manure with several options for the type. The weight and volume for each of the components is different but the output is the same.

### Steps to reproduce

1. Try to craft an adobe soft brick using different types of manures.
2. Obtain the same size and weight of brick regardless of component used.

### Expected behavior

I'm not sure if the volume or the weight is what is important for making bricks, but the recipe proportions should probably be changed for the lighter items so that they are uniform.

### Screenshots

![image](https://user-images.githubusercontent.com/55005591/146467814-7f8e470d-9674-4500-bba2-61ae0b69dab4.png)
![image](https://user-images.githubusercontent.com/55005591/146468056-ab5af39c-b8a2-447d-8909-f7f9c368a6c4.png)
![image](https://user-images.githubusercontent.com/55005591/146468140-dc8d82b5-c986-4b2b-9cf7-1a1270b083a0.png)
![image](https://user-images.githubusercontent.com/55005591/146468151-8befb0d5-c6e3-45c8-a195-162895839973.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 9fe84e0 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

This probably isn't a difficult fix, I'm willing to make a PR for it but I'm not sure what the values should be changed to!

**Comment by Paprika-H** [comment]
Try verifying it in game, Chezzo can be outdated at times

**Comment by friendfrog** [comment]
Looking at the recipe in game with a fresh install (same version) it's the same. The different components have different weights and volumes than posted above but they're still not right seemingly.
![image](https://user-images.githubusercontent.com/55005591/146472349-f094e51e-e404-463f-b037-6061645e33d7.png)
![image](https://user-images.githubusercontent.com/55005591/146472462-95ab9972-0adf-434a-bc4c-b14cf0aad8fc.png)
![image](https://user-images.githubusercontent.com/55005591/146472486-1af48ceb-78f8-4eed-94ea-3ef85129c015.png)
![image](https://user-images.githubusercontent.com/55005591/146472513-51ff116a-c996-42d7-8b7b-46d3bf61daa4.png)

**Comment by Maleclypse** [comment]
I would standardize on the weight.

**Comment by Max17U** [comment]
As for [https://www.aqua-calc.com/calculate/weight-to-volume](https://www.aqua-calc.com/calculate/weight-to-volume), 0.25L of Manure weights about 0.22 pounds (or 100 gram). So I'd say, for Manure and Cowpie respectively, 0.50L would weight 0.44lbs and 1.0L would be 0.88lbs. About roach dirt, if we're supposed to treat it like manure, it should weight 0.22lbs for 0.25L.
For the recipe, you can change the last part to : `1 Cow Pie OR 2 Manure OR 4 Roach dirt`. 
Now what I don't really understand with that recipe, is why i should need 10L of soil + 1L of Feces or whatever + some water, to make just 1 (ONE) soft adobe brick that's 0.75L in volume. I'm not an adobe brick expert but i don't think that's how it would work. But since there are other inconsistencies i think it was just made to semplify the process, right?
Even if... you can make a wall with only 20 Adobe brick (20 * 0,75L bricks ) 🤣

**Comment by LeahLuong** [comment]
This should prob be moved to P1 status immediately simply to demonstrate the devs can get their $#!7 straight.

**Comment by Max17U** [comment]
> This should prob be moved to P1 status immediately simply to demonstrate the devs can get their $#!7 straight.

P1 status? What do you mean ? Sorry quite new here :)

**Comment by Zireael07** [comment]
He means priority one, and the rest of his comment seems to be $#!7 indeed

**Comment by LeahLuong** [comment]
I hope you're just being sarcastic, Zir. I can tell @ least a couple of people got the joke.
