### ISSUE TITLE
Acid Anthills don't yet spawn 

### ISSUE THREAD

**Issue by Paprika-H** [CleverRaven/Cataclysm-DDA#53517]
### Describe the bug

Acid anthills don't spawn. 

### Steps to reproduce

There's code that specifically states acid anthills don't spawn. 

### Expected behavior

I expect acid anthills to spawn

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 03f9cc1 [64-bit]
- Graphics Version: Tiles
- Game Language: Nederlands [nl]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

Related to #51474 , got permission from Maleclypse to make an issue about it even with the original PR author planning on adding it back so that more people could work on it.

**Comment by jbytheway** [comment]
Since I've let this lack of Acid Anthills go one much longer than I originally intended I will explain a bit more about how I envisioned re-adding them.

I wanted to be able to reuse the existing JSON maps for the non-acid anthill.  But obviously they need different creatures in them.  So, I was planning to take advantage of mapgen parameters to specify the category of ants present.

However, some of the monsters are defined at the OMT level, and there's currently no support for mapgen parameters at the OMT level, so this was waiting on that to be added.

**Comment by Paprika-H** [comment]
> Since I've let this lack of Acid Anthills go one much longer than I originally intended I will explain a bit more about how I envisioned re-adding them.
> 
> I wanted to be able to reuse the existing JSON maps for the non-acid anthill. But obviously they need different creatures in them. So, I was planning to take advantage of mapgen parameters to specify the category of ants present.
> 
> However, some of the monsters are defined at the OMT level, and there's currently no support for mapgen parameters at the OMT level, so this was waiting on that to be added.

No worries! Take your time lmao, I just put this up so that it could get a bit more attention. Sorry if I put any unneeded pressure on you!

**Comment by Inglonias** [comment]
Honestly, I don't miss acid anthills at all. In my experience they're just a giant "no-go" zone on the map, similar to how fungus can be.

**Comment by Paprika-H** [comment]
> Honestly, I don't miss acid anthills at all. In my experience they're just a giant "no-go" zone on the map, similar to how fungus can be.

Biosilicified chitin is some of the most powerful armour you can get
