### ISSUE TITLE
Bandaging while danger near doesn't stop bandaging, even to death.

### ISSUE THREAD

**Issue by morthein** [CleverRaven/Cataclysm-DDA#53644]
### Describe the bug

There's no warnings allowed when bandaging, even while being attacked by zombies, whom can kill you while bandaging, unless you force stop manually.

### Steps to reproduce

1. get some makeshift bandages
2. find some zombies
3. debug wound yourself so you can bandage said wound
4. watch zombies tear you apart.

### Expected behavior

prompts every time you see danger, hear something, or are being attacked.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 00a57e1 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    <color_light_blue>BL9-100%-monster-resilience-version</color> [BL9_100monres],
    Aftershock [aftershock],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Generic Guns [generic_guns],
    DinoMod [DinoMod],
    Alternative Map Key [alt_map_key],
    Crazy Cataclysm [crazy_cataclysm],
    Extra Mutated Scenarios [extra_mut_scens],
    Mining Mod [Mining_Mod],
    More Survivor Stuff [more_survivor_stuff],
    Mythical Martial Arts [MMA],
    No Rail Stations [No_Rail_Stations],
    Cars to Wrecks [cars_to_wrecks],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    Bionic Slots [cbm_slots],
    Disable NPC Needs [no_npc_food],
    Magiclysm No Class Limit [magiclysm_no_class_limit],
    Mutation Changes [Mutation_Changes],
    No Fungal Growth [no_fungal_growth],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

To clarify, if you use your bandage and the moment you use it, something is near, it does prompt. If you are 'using' it and the clock is rolling, and something nears and attacks, it forces you to wait to finish, even if attacked.

**Comment by morthein** [comment]
To clarify, if you use your bandage and the moment you use it, something is near, it does prompt.  If you are 'using' it and the clock is rolling, and something nears and attacks, it forces you to wait to finish, even if attacked.

**Comment by hexagonrecursion** [comment]
I could not reproduce this issue.

I get the following warnings:
* Heard footsteps! Stop consuming?
* zombie spotted! Stop consuming?
* The zombie is dangerously close! Stop consuming?
* Ouch, something hurts! Stop consuming?

Saying yes to any of the warnings does stop the activity.

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: 0.F-4523-g00a57e1f7d [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by morthein** [comment]
Really?  I started a vanilla game, debugged hurting my head, made 'bandages' found a fema camp, got attention, walked a little away and applied the bandage, got one prompt telling me there's a feral human coming, I said ignore, him and his 3 zombies beat me to death with no more prompts.

**Comment by morthein** [comment]
It seems to happen when I begin bandaging while they're not near but in pursuit, once the clock rolls to simulate the bandaging time it takes, it doesn't prompt anymore and they continue to attack me.

**Comment by hexagonrecursion** [comment]
I can reproduce #53658, but I still can not reproduce this.

I *do* get a "... is dangerously close" prompt:

1. I loaded your save
2. Debug bled my left arm for 100
3. [E]ate a bandage (from your save)
4. Selected my left arm
5. The cunning feral (from your save) got close 
5. I got a prompt "The cunning feral is dangerously close! Stop eating?"

The prompt is useless because of #53658, but you are saying there is no prompt at all, which is different and might be a separate bug.

I tested the above while wearing a blindbold (id: blindfold) and a pair of ear plugs (id: ear_plugs) and still got the prompt.

6. If I answer [N]o to several "The cunning feral is dangerously close! Stop eating?" prompts in a row I eventually get a different prompt: "Ouch, something hurts! Stop eating?".
7. Two more presses of [N] get me "You were attacked by a cunning feral! Stop eating?"

Answering [I]gnore instead of [N]o only shows each of the three prompts once, but it does show them.

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: 14aa061 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by morthein** [comment]
does it make a different that I 'applied' and didn't 'eat' (consume) the bandage? 

I use apply and it happens

**Comment by hexagonrecursion** [comment]
Every detail could make a difference. This is why I try to be as specific and exact as possible.

> I use apply and it happens

That did it! I can reproduce your bug now too. Thank you.

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: 0.F-4523-g00a57e1f7d [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by morthein** [comment]
yay!   I never thought about (e) consuming till you said it.   then i was like... !!!  wait a minute!  You're right about detail!  :D

**Comment by stopple** [comment]
this seems very similar to what I just experienced, (a)pplying some antiseptic got me mauled by a feral

[clip here](https://www.youtube.com/watch?v=rYunHdCApIE)

- OS: Windows - OS Version: 10.0 2009
- Game Version: 98a8e80 [64-bit]
- Mods loaded: [Dark Days Ahead [dda],Disable NPC Needs [no_npc_food],No Fungal Growth [no_fungal_growth],Bionic Professions [package_bionic_professions] ]

**Comment by hexagonrecursion** [comment]
I can still reproduce this in f7e3308 - I still get no prompt when [a]pplying a bandage. #54672 did not fix this bug.

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: f7e3308 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by hexagonrecursion** [comment]
# Self-contained 100% reliable steps to reproduce the issue
1. Debug spawn a mi-go [id: mon_mi_go] 25 tiles west of yourself
2. Debug bleed your torso with 10 intensity
3. Debug wish for a bandage [id: bandages]
4. Press a to [a]pply the bandage
5. Helplessly watch as the mi-go kills you

Note: this works regardless of whether safe mode is on or off

**Comment by hexagonrecursion** [comment]
Note: I am sorry. I intended to post $100 bounty on this, but it duplicated due to a technical issue. https://app.bountysource.com/issues/105211069-bandaging-while-danger-near-doesn-t-stop-bandaging-even-to-death I have contacted BountySource. I expect they will refund me $200.

The **real** bounty amount is $100

**Comment by KurzedMetal** [comment]
This bug is quite annoying because happens too often and has a high impact on the player (probably death).

**Comment by mqrause** [comment]
To reiterate what the actual problem is:

1. `Character::get_consume_time`, called in `consume_activity_actor::start` to determine the duration of the activity, currently only has guesses as to how long applying medical items takes. The duration determined here is actually interruptible.
2. `Character::consume` called in `consume_activity_actor::finish` invokes the `iuse_actor` of medical items. I didn't check all the possible actors that can be called here, but at least for the `heal_actor` responsible for bandages, it has the actual duration it needs to apply and also consumes that time (in `heal_actor::use`), which is uninterruptible.

An obvious solution would be to not consume any time in `iuse_actors` and instead have the activity handle it, but the details of how to do that would depend on how and where they can be invoked. The difficulty can range from simply separating medical `iuse_actor` execution from consuming the time to also refactoring all `iuse_actor`s and their invocations to only happen inside activities to not break anything else while fixing this. I'm not familiar enough with that part of the code to tell where in that spectrum it really lies and I also might have missed some other pitfall complicating things. But most likely it lies more on the simpler side.

**Comment by RoyBerube** [comment]
Am working on this; Trioct PR 56781 was on the right track. Moving firstaid for the player and NPCs to the firstaid activity seems to be working. 

It will take some more time to add test cases and do some more fine tuning. Don't want to rush it.
