### ISSUE TITLE
Interrupting applying medical items doesnt' work

### ISSUE THREAD

**Issue by mkrutov** [CleverRaven/Cataclysm-DDA#53658]
### Describe the bug

Interrupting applying bandages or antiseptic etc doesn't work. At all.

### Steps to reproduce

1. Start applying bandage.
2. Get an interruption prompt after selecting the body part to which you apply it ("Zombie spotted. Stop applying?")
3. Agree to the prompt
4. Bandage application is cancelled but time still forwards for next 15 seconds, giving zombie a chance to absolutely decimate you

### Expected behavior

Interruption is immediate.

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: 1.4; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 00a57e1 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Blaze Industries [blazeindustries],
    Disable NPC Needs [no_npc_food],
]

**Comment by hexagonrecursion** [comment]
I can confirm that a non-zero amount of time elapses when a bandaging attempt is interrupted, but it is 1 to 2 seconds - a reasonable span of time for the following sequence of events:
1. The zombie hits you
2. You are interrupted
3. Your turn comes up

* Pain lowers your speed, but even at -50% I still get the same 1-2 seconds
* Extreme weariness likewise did not change the delay either
* Even after putting the bandages in a container with a high "base moves to remove item" stat (hiking backpack: 450 moves) the delay is still 1-2 seconds.

There is a chance the issue is caused by one of the mods you have installed. Could you please try reproducing this in vanilla?

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: 0.F-4523-g00a57e1f7d [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by hexagonrecursion** [comment]
I think I managed to reproduce this now.

1. Position yourself 20 tiles away from a zombie (within vision range, but not too close)
2. Wish for 10 bandages and hold them in your hands
2. Debug bleed your torso
3. [E]at a bandage
4. Select torso
5. The zombie approaches you
6. The game warns you "The zombie is dangerously close! Stop eating?"
7. Select Yes
8. Over a minute passes

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: 0.F-4523-g00a57e1f7d [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by mkrutov** [comment]
Frankly this is absolutely abhorrent in its current state and in my opinion this should have "blocker" status for the release. 

You can't stop an activity while getting hit and getting hit prolongs the activity, therefore you can stand there tyring to 'E'at a bandage *forever*, as in "for 5-10 minutes" sometimes, which almost always leads to you either having `:` torso or just straight up dying to the absolutely minimal threat like a crawling zombie or a decayed zombie.

**Comment by stopple** [comment]
just got absolutely smoked by this

was standing in a street, used antiseptic on a small wound.  feral walked up and hit me 5x while I was using anitseptic.  no stops on spot, close danger, damage received. no mods.

[youtube clip here](https://www.youtube.com/watch?v=rYunHdCApIE)

**Comment by mkrutov** [comment]
@stopple that is different , see issue mentioned earlier here


What I describe happens when you `E`at bandate, not `a`pply it and it give you a prompt (but regardless of prompt choice, action doesn't interrupt).

**Comment by stopple** [comment]
@mkrutov yes, I see that now.  I got no prompt whatsoever.  I'll keep looking to see if I can find the issue in another thread

**Comment by mkrutov** [comment]
@stopple ,
https://github.com/CleverRaven/Cataclysm-DDA/issues/53644 / https://github.com/CleverRaven/Cataclysm-DDA/issues/53703 those two describe your scenario.

**Comment by hexagonrecursion** [comment]
Potentially relevant [comment](https://github.com/CleverRaven/Cataclysm-DDA/issues/53703#issuecomment-1000829258) from a duplicate bug: 

> A clue to why eat and activate behave a little different:
> 
> https://github.com/CleverRaven/Cataclysm-DDA/blob/83b08cc9b683b176bf4d1bfdc2a8fd0cde752dfe/src/game_inventory.cpp#L1086-L1090
> 
> 'E'at creates a menu activity so that when the eat activity is done it comes back to the eat menu again. Activate does not do that.
> 
> I think this explains why 'E'ating gets more interrupt messages. I'm seeing some odd behaviour in where saying yes to cancel still allows the bandage activity to finish.

**Comment by hexagonrecursion** [comment]
I can still reproduce this in f7e3308. #54672 did not fix this bug.

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: f7e3308 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by mqrause** [comment]
The consume activity seems pretty broken to me. When you `E`at a bandage, it first spends the calculated consume time of 15 turns. Once that's done, it asks what limb you want to bandage. So even without any wound you spend 15 seconds. This part is actually interruptible.
If you then select a wound, `Character::consume` will consume the bandage and directly subtract even more time to spend on bandaging (60 turns in the case of a minor bleeding torso), so your character ends up with a large amount of negative moves during which they won't be able to do anything.

Considering all that, it's probably the same for eating food or any other consume activity you start from the `E`at menu, though most of that is likely hardly noticable because it's only very few seconds.

Probably also the same when `a`ctivating a bandage, but I didn't test that.

**Comment by lfaga** [comment]
I am absolutely tired of dying to this bug.

**Comment by kenneth-ellis** [comment]
It's now another month later and I too, am absolutely tired of dying to this bug.
