### ISSUE TITLE
Machine readable stable release list

### ISSUE THREAD

**Issue by AllenJB** [CleverRaven/Cataclysm-DDA#53712]
### Is your feature request related to a problem? Please describe.

There are several Cataclysm launchers available that provide useful features such as automatic backups.

While these launchers use the GitHub API to obtain the latest experimental builds, unfortunately, from my research, neither the v3 API or the v4 GraphQL provide the ability to filter just stable releases. It's theoretically possible to page through the list of releases and pick out the stable ones, but this would likely take many requests due to the number of releases on the Cataclysm project (and may run into API request (rate) limits).

As such the launchers currently hard-code the stable release list.

### Solution you would like.

A machine-readable (eg. JSON) file listing stable builds could be provided by the project.

From my work on a [PR for the remyroy launcher](https://github.com/remyroy/CDDA-Game-Launcher/pull/615), I believe it would be sufficient for this file to contain the same information as the [releases webpage](https://cataclysmdda.org/releases/):

* The release version (as it appears in VERSION.txt in the game files - this allows launchers to identify the installed version)
* A link to the GitHub release
* A list of release downloads
  *  While it would be nice if the JSON explicitly identified each (OS / distribution) download (eg. Win x64 Tiles, OSX Curses, OSX Tiles, Linux Curses, etc), this isn't essential - launchers could work out which file they need from the download filenames as long as the format remains stable.
* (Nice to have, but I don't think essential) The changelog / description for the release as (I would suggest in Markdown format)

The file could either be hosted on the Cataclysm website or in the / a GitHub repo. As long as it resides on a stable URL it shouldn't matter. I would suggest linking to it from the releases webpage so people who don't know it exists can find it.

Some manual work would be initially required to update the launchers, but after that they would be able to use this file to automatically update their list of stable builds so launcher users could download them as soon as the release happens, rather than waiting for launcher maintainers to perform updates. (I would certainly be willing to work on a PR for the remyroy launcher. From what I've seen on the [Catapult Launcher release management code](https://github.com/qrrk/Catapult/blob/master/scripts/ReleaseManager.gd) (and while I'm not familiar with GDScript), I don't think this should take a massive amount of work to update either.

### Describe alternatives you have considered.

Launchers could obtain the latest stable release from GitHub on a periodic basis and use this to build a locally cached stable release list, but this would only work for releases going forward from the install date and if the launcher is reinstalled or a user reinstalls after reformat, they would not have a list of past releases, only the very latest one.

Alternatively: Each launcher project could obtain the latest stable release from GitHub on a periodic basis and use this to build / update their own machine readable stable version list and create a new launcher release or update their own static API file. This would only be able to be reliably used by that one project and any future projects (or anyone who wants to use a stable build list for other purposes) would have to repeat the work.

**Comment by ZhilkinSerg** [comment]
See https://docs.github.com/en/rest/reference/releases how to query API for releases in the repo.

Stable CDDA releases will have `prerelease` set to `false` and experimental CDDA releases will have `prerelease` set to `true` (e.g. compare stable `0.F` - https://api.github.com/repos/CleverRaven/Cataclysm-DDA/releases/tags/0.F and some random experimental `2021-09-21-0417` - https://api.github.com/repos/CleverRaven/Cataclysm-DDA/releases/tags/cdda-experimental-2021-09-21-0417).

Release tag naming scheme is very simple: zero, followed by a point and English character (next character in alphabet counted from previous release).

Since 0.E we have also introduced point releases where we backport bugfixes and some features from experimental branch - a dash and integer number are added to the end of release name.

Our releases (starting from `0.D` as we do not provide earlier downloads) are:

- `0.D`;
- `0.E` - initial release for `0.E`;
- `0.E-1` - first point release for `0.E`;
- `0.E-2` - second point release for `0.E`;
- `0.E-3` - third point release for `0.E`;
- `0.F` - initial release for `0.F`;
- `0.F-1` - first point release for `0.F`;
- `0.F-2` - second point release for `0.F`;
- `0.F-3` - third point release for `0.F`, latest stable release at the moment.

Thus you can query https://api.github.com/repos/CleverRaven/Cataclysm-DDA/releases/latest to get latest release and then deduct all possible future releases using aforementioned release naming scheme.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
