### ISSUE TITLE
Adding granularity to items representing collections

### ISSUE THREAD

**Issue by pjf** [CleverRaven/Cataclysm-DDA#53718]
### Is your feature request related to a problem? Please describe.

As discussed in #53635, we have objects—such as handfuls of nuts, powders, and spices—which really represent a **collection** of smaller objects. While we don't want to model individual nuts or flakes of oregano, we *do* want some way of indicating the size of the granules in the collection.

Having this granularity information means we can do checks like making sure string or mesh bags can't hold things like a handful of sand, and means that having containers for items like spices and powders makes more sense, especially since they already spawn in these containers.

The granule size may also impact rummage/clutter mechanics as suggested in #53657 and elsewhere.

### Solution you would like.

Some sort of JSON attribution on items to indicate the smallest hole size they cannot pass through.

@I-am-Erk has suggested this might go into `phase` attribute, but we may have a dedicated `granule_size` or similar. I'm not familiar enough with the code to have an expert opinion on this.

### Describe alternatives you have considered.

Heaping all of my herbs, spices, and nuts into a big pile under the sink without any containers and bags. :)

**Comment by Alex-Folts** [comment]
Something like: add grid size parameter to non watertight containers and same parameter for powders(non liquid items with charges), and if container grid size > item grid size do not accept item because it will fall through holes in container?

**Comment by I-am-Erk** [comment]
I'm not sure how valuable it would be to track size of individual objects that closely

**Comment by Photoloss** [comment]
The larger ones could probably be converted to single items using longest_side for the particle size and a stack size for the current portions. We already do this for marbles, pebbles and bearings because they are used as individual ammo, food might need an exception to #53631 and some changes to recipe handling so we can easily shell and eat individual nuts.

If longest_side is used to represent grain size then that should definitely be noted in a comment, we do use a tiny max_item_volume on bottles to basically restrict them to liquids which basically is the inverse problem.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
