### ISSUE TITLE
Can't reload partially full magazine with favorited ammo

### ISSUE THREAD

**Issue by mkrutov** [CleverRaven/Cataclysm-DDA#53762]
### Describe the bug

n/a

### Steps to reproduce

1. Get a partially full STANAG 5.56 magazine
2. Get ammo
3. Favorite `*` magazine and ammo
4. Try to reload

### Expected behavior

should allow for reload regardless of favorited status

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: 1.4; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 8b32af6 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Disable NPC Needs [no_npc_food],
    No Bionic Slots [no_cbm_slots]
]

**Comment by Hirmuolio** [comment]
It is most likely caused by the can_combine check here: https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/item_pocket.cpp#L1423
That check requires items to have same favorite status to be stackable.
The ammo stacking requirement for reloading is much less strict than the normal one. It it probably enough to just check that the ammos have same type ID, have same liquid phase and have same components.

**Comment by hexagonrecursion** [comment]
Confirmed

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: f8734ab [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]
