### ISSUE TITLE
Slow evolution rates for monsters down, the Proficiency system is already good enough at slowing down how ridiculous player progress was in the earlier builds.

### ISSUE THREAD

**Issue by cataclysmsurvivalist** [CleverRaven/Cataclysm-DDA#53791]
### Is your feature request related to a problem? Please describe.

Yes, I know evolution rates are up to the player, but the default is too ridiculous as it is, and most people play it in the default. I believe the reason it was raised was because the players were advancing too much and making the game a cakewalk, but now? Not only books have been nerfed (rightfully so, the theoretical/practical divide is a very good system) but we also have proficiencies that slow down how quickly you can craft high-tier equipment.

The game development has done a great job to slow down character progression in a way that doesn't feel artificial or forced while also making it more rewarding than it was before, but monsters are still more ridiculous than ever. Balance goes both ways, and I don't think it's right to just ignore how inflated monster evolution values are just because the players can fix it for themselves.

By the time I noticed it, I was fighting skeleton hulks without even having the time to craft real armor. And my monster evolution is set to 7 at the beginning of every game. While this kind of massive growth rate would be justified long ago, in the time where we could master combat just by reading books, this just isn't the case anymore.

Facing down shocker brutes and necromancer/masters at the end of the first month is simply too ridiculous for most players, and it should be up to high-tier players to increase the monster evolution rate if they want to challenge themselves, rather than low/mid-tier players to increase it to ridiculous amounts if they don't want to get mangled at the end of the first summer.

Take the Pair of Survivor Boots, for example. Requires kevlar, leather, the right tools, a high fabrication/tailoring level, and a lot of proficiencies, and takes almost an entire day. Pretty standard as far as gear goes, by itself, it's nothing too ridiculous.

But think of it when you're trying to craft it without knowing any of the proficiencies needed. First you'd need Cobbling, Principles of Leatherworking, Fabric Waterproofing, Advanced polymer sewing, and Skilled Leatherworking. So either you A) Spend a **lot** of time, like over an entire week, to craft it by itself, or you B) Spend **slightly less** time to master all those individual Proficiencies first, which **by itself** also requires not only resources, but also the right books to allow you to practice until you master them in the first place. Meanwhile, while you spend a week in that crafting bench just trying to make some damn boots, the monsters are getting stronger, and you still need to worry about gathering food. And that's just a single piece of gear! Crafting the entire set not only requires a lot of knowledge and resources to get started, but also take a long time to actually finish.

**For the record, this is not criticism of the Proficiencies mechanics.** In fact, I think they're great! It's another great way to show how much your character is growing throughout the game. And at the same time, **I don't mind that armor, ESPECIALLY advanced armor, takes a long time to be built.** But those mechanics have been made to slow down how much the player advances in a short while, because advanced players have been blowing through the early game too quickly. And they've succeeded, but the devs haven't taken time to realize monster progression doesn't need to be as fast as it was anymore due to this.

I'm not saying to make the game take years to evolve zombies, but... Take it a bit slower, yeah?

### Solution you would like.

It should be up to high-tier players to increase the monster evolution rate if they want to challenge themselves, rather than low/mid-tier players to increase it to ridiculous amounts if they don't want to get mangled at the end of the first summer.

To put this in another way, the game should first be balanced with the mind of giving regular players a challenge, and **then** the changes in the debug options should give highly-advanced players the option to put self-imposed challenges on themselves.

**Comment by Maleclypse** [comment]
So are you suggesting editing the default evolution rate or manually editing all the monster's half lives to be longer?

**Comment by Terrorforge** [comment]
Those would do pretty much the same thing, except the former is much less work, right? Sounds like a no-brainer.

And fwiw, I agree with this change. The intersection of fast evolution and slow crafting means that even if you're working efficiently, zombies start to get _very_ scary right as you're finishing your core setup - and as mentioned, we should probably set the default to account for people who are not working at maximum efficiency.

**Comment by mkrutov** [comment]
@Terrorforge , so if this is a right place to discuss this my 2c.

I think that evolution *speed* is fine as is, but needs more intermediate steps. 

Let's take skeleton evolution line. 

skeletal zombie, halflife 12 days -> skeletal brute, halflife 15 days -> skeletal juggernaut

power jump from SZ to SB is 6x increase in HP and massive increase in their ability to kill players.
power jump from SB to SJ is only 3x increase in HP but much more massive increase in their ability to kill players. 

I don't have exact names to propose here, but I feel like there is a couple steps missing between Brute and Juggernaut, and may be an additional step between skeletal zombie and brute, which would more gradually upgrade the power of those.

**Comment by cataclysmsurvivalist** [comment]
I agree with how it seems like evolution is jumping steps, but even if there was a middle stage between regular and hulks, the speed is still far too overclocked as it is. Zombie brutes showing up _this_ early would still be far too quick for most players to adapt to on default speed.

**Comment by mkrutov** [comment]
Though middle stage implies prolonged evolution, ie in case of skeletons (I'm using them just because they are a straightforward and short evolution line) you have:

ZS -> ZB -> ZJ with mean time of 12+15 = 27 days

If you add more steps making it

ZS -> Zx1 -> ZB -> Zy1 -> Zy2 -> ZJ it won't make same 27 days - every middlestep would/should have 2 week delay built into it.

**Comment by Venera3** [comment]
Keep in mind half-life and monstergroup start/end timers are multiplied by the evolution factor, but growth timers aren't so just slapping a higher evo factor on as default wouldn't work.

I generally agree, with the important caveat that I think earlygame difficulty could use a significant bump, with the later stages being smoother. Since #49279 city centers are pretty much Day1-driveable for a quick smash-and-grab, and in general the first variant of zeds can't do much more than threaten a fresh Evacuee. In my opinion the rough outline should be buffing base zombies in whatever form works, scattering some more basic specials and laying down a defined (and ideally documented) timeline for "canon" evolution rates.

Something along the lines of the first properly deviating zeds (Tier 2) appearing at the two-month mark and the first Tier 3 at the end of summer/early autumn. This would obviously need either a heavy buff of zed numbers or of the low/midtier zombies to keep the game from being over the moment you get your hands on a quarterstaff. Adding to that, both practice recipes and skill gain in general need a serious balance pass if we want to draw out the earlygame phase.

**Comment by SirPendrak** [comment]
I will add my two cents, from a view of many years veteran and rather hardcore player. 

The ratio of "player getting stuf and skills"/monster evolution rate is much harder than it was some time ago (it was possible to get surivor gear in the first week of apocalypse and grind dodge skill to 11 one week later). 

But player still can greatly outrun monster evolution. As time goes and player starts scavenging, he gains new types of weapons, often ones that work differently, they gain options to use traps, use vehicles, use trained animals, use NPC army, use noctovision, use silent weapons and external light source at night etc. 

If you focus only on fighting every day, you will be able to melee almost every zombie in no time. 
If you focus on grinding crafting skills and proficiences, you get better weapons and armor that will compensate for stronger zeds for like a year ahead, paid with 3 months of grind. Lucerne hammer goes BONK. 
And if you go for balanced approach, you can use your most precious resources on stronger threads and renewable resurces on weak threads. And even if from time to time you encounter an enemy youre not prepared to defeat, you dont have to fight everything. 

Right now, game at least tries to pretend making zeds being a challenge outside of first week (unless one rushes unprepared into horde or something). 

BUT IT ALLS MEANS NOTHING!!!11! (Angry rant starts) 
As long as we have super-duper-realistic CROWS trurets filled with thousands of ammo, player can mow down whole cities with only danger being occasional shockers hidding behind a corner or feral militias that were faster to pull the trigger. 
Only after military grade ammo is made rare again, then we can talk about trying to ballance difficulty from evolution tempo. Right now it does not matter if you need 3 shots to kill a brute, or 8 shots to kill a hulk, because you have 24.000 bullets in your evac shelter or in your truck. 

Ehh, old no-name, no-brand turrets were ten times better. If this version of reality can have power armors or rivteh guns, then surerly we dont need to use real world counterparts for everything. Sure, things like AR-15s are popular in USA and should stay as AR-15s in game, but I bet that 99% of players didnt knew what CROWS were before playing the game.

**Comment by cataclysmsurvivalist** [comment]
Hey, thanks for the response from a veteran's POV, it gave me some things to think about in terms of balance. You actually made me more confident in my argument, because it highlights how the difficulty isn't being dealt in the right way in those recent builds. First off, it's as you said, veteran players know how to get enough ammo to mow down hordes, no matter if they're regular zombies or an army of brutes.

So if the devs want to make the game more difficult for older player, then making the zombies evolve faster isn't really a good factor because bullets don't care how tough the zombies are, with the exception of armored variants like the kevlar hulks (and even then they just take more bullets to take care of).

Meanwhile, newer or casual players are getting screwed over because we don't know how to advance and adapt as quickly as older pros, and the fact we don't get enough time to play around before being destroyed by beefed up variants just makes the game frustrating. So the faster evolution that the game is getting now isn't making the game more challenging for players like you, and it's just making it unfun for players like me.

From what I've gathered here, the best way to make the late game more challenging would be to either A) make bullets rarer, to the poin where the player actually needs to spend time and resources to learn relevant Proficiencies and craft his own ammo at least to an extent, or B) nerf bullets (which would be unrealistic, so I greatly doubt the devs will go for that).

Hell, evolution could be _slower_ than what it was before the rate was increased, and it wouldn't change how vets really see the game; a series of challenges to get the biggest, baddest guns and the relevant ammo until they can cruise through cities and dungeons.

**Comment by Asmitha90** [comment]
I agree that the abundance of ammo is a problem to a degree, but for a player that knows what he's doing it won't make much of a difference. The base problem is that most zombies can be killed with m4. Why don't you add zombies that, for example, are immune to bullets (mid/late game spawns)? This would also open up a way for bio weaponry witch isn't a thing in the game which I find criminally missed opportunity. We have all these mutated creatures, etc. Why not extract theyr bio matter and use it to create some sort of acidic weaponry. For example a sludge grenade that would cover the area in solid, some gas base that would make zombies slower/ decreased their hit chance etc. This would greatly increase the variety and progression(make chemistry useful again) + adding difficulty since you can't now just mow down everything with conventional melle/bullets.

**Comment by ido77778** [comment]
I think this discussion was somewhat derailed. Regardless of late-game difficulty, currently evolution is quite harsh due to proficiencies slowing down crafting progression. That's not to say that it's impossible to beat the system; not at all, it's even easy if you play a very optimal and calculated build. The problem is that it discourages interesting but non-optimal play-styles and builds, especially for newer players.

Keep in mind that no matter how you balance a game, hardcore players, who played hundreds upon hundreds of hours, will still come up with optimal strategies. So it's not very prudent to make the game harder for those players at the cost of making it inhospitable for more casual or newer players. I don't mean that the game should be very easy, but that a balance needs to struck between those conflicting demographics. Sometimes it's best to simply accept that certain optimal strategies will continue to exist.

**Comment by sonphantrung** [comment]
Should be obsoleted by #58851
