### ISSUE TITLE
Wild herbs conducts electricity

### ISSUE THREAD

**Issue by Nicals** [CleverRaven/Cataclysm-DDA#53811]
### Describe the bug

Wild herbs are configured to conduct electricity.

### Steps to reproduce

1. Find wild herbs
2. Read item description

### Expected behavior

Wild herbs should not conduct electricity

### Screenshots

![wh](https://user-images.githubusercontent.com/2552707/147485160-7eabc5e6-2028-487d-8752-528fcc19e115.png)

### Versions and configuration

- Version 0.3-F from ArchLinux repo

**Comment by NetSysFire** [comment]
Are you sure about that? I am fairly sure they might actually able to do that irl. For reference, flour conducts electricity ingame, too.

I think it might be dependent on moisture, since it does seem a bit silly to me that dry flour and wild herbs could conduct electricity.

I had a discussion with @kevingranade about just that 6 months or so ago and he cited https://pubs.acs.org/doi/10.1021/ie50136a018 (it appears that this might be paywalled).
