### ISSUE TITLE
Update 2021-12-27-2151(pull request #53805) and later freeze the game

### ISSUE THREAD

**Issue by Proxima-b** [CleverRaven/Cataclysm-DDA#53825]
### Describe the bug

Experimental build 2021-12-27-2151(pull request #53805)  and all later builds have game freezing problem.

### Steps to reproduce

1, Using aforementioned build
2, Open the game
3, Create world with only the provided mods
4, Create character and enter said world.
5, Game freeze.

### Expected behavior

A Fix or a revert.

### Versions and configuration

experimental build 2021-12-27-2151

**Comment by BrettDong** [comment]
Cannot reproduce on Windows 8.1 x64.

**Comment by Cyenthies** [comment]
Win 10 x64. version 0235. Save is attached, just start walking north, past the alien grass, game will then freeze. Game works fine when reverting to 0903. 
[SlowGoing.Clearin.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7782981/SlowGoing.Clearin.zip)
.

**Comment by ArchXII** [comment]
I personally have this issue as well on Windows 10 x64. Debug logs state something about 'no such process' when trying to access certain directories (mostly the mods directory, which isn't in the root but I also don't use mods so it's probably fine) but that all gets written before the crash. It's a hard freeze on 'building the world', and nothing else is written to crash or debug.

I noticed this earlier but didn't write up an issue because I didn't feel I had anything to add due to the lack of logs written about it. If there's anything else I can check to help, I'm happy to give that information. I have currently moved back to 0903 and it's working fine.

**Comment by JyeGuru** [comment]
Did a quick test while testing something else as well, and can confirm this happens, but for me it's before character select.

- `cdda-windows-tiles-x64-2021-12-27-0903` - Works
- `cdda-windows-tiles-x64-2021-12-27-2151` - Freezes on start
- `cdda-windows-tiles-x64-msvc-2021-12-27-0903` - Works
- `cdda-windows-tiles-x64-msvc-2021-12-27-2151` - Works
 
- Extract game into fresh directory
- Start and generate a new world (Next, Next, Ok - all defaults)
- New Character, Random Character
- Freezes before loading the character confirmation screen
![image](https://user-images.githubusercontent.com/5215014/147531986-bdbcd274-d4d2-403f-ad37-eab3d7459cb3.png)
![image](https://user-images.githubusercontent.com/5215014/147531995-4320f24e-fe5f-4b37-ab39-81a4484aa79a.png)

**Comment by BrettDong** [comment]
Probably related to #53103.

**Comment by KittyTac** [comment]
I was just driving and my game froze. It never did before. I think it's related to this.

**Comment by BrettDong** [comment]
Freeze reproduced by creating a new character in a new world. Loading an existing save does not cause a freeze.

![image](https://user-images.githubusercontent.com/21075502/147541668-852408e9-f8c2-40b0-9f62-98d17bf00161.png)

Stuck in a seemingly infinite loop in `std::generate_canonical()`.

**Comment by BrettDong** [comment]
![image](https://user-images.githubusercontent.com/21075502/147543345-71aea8fa-db92-4ad6-ab5c-cf82528446f6.png)

When randomizing new character height, in `normal_roll(double, double)` the program gets into an infinite loop between `normal_roll+171` and `normal_roll+239`.

**Comment by BrettDong** [comment]
I suspect GCC 9.3 generated incorrect assembly code for `normal_distribution::operator()`. Its source code is in `libstdc++-v3/include/bits/random.tcc` around line 1800, and this implementation is identical between GCC 9.3 and GCC 11.2:
```c++
1794    /**
1795    * Polar method due to Marsaglia.
1796    *
1797    * Devroye, L. Non-Uniform Random Variates Generation. Springer-Verlag,
1798    * New York, 1986, Ch. V, Sect. 4.4.
1799    */
1800   template<typename _RealType>
1801     template<typename _UniformRandomNumberGenerator>
1802       typename normal_distribution<_RealType>::result_type
1803       normal_distribution<_RealType>::
1804       operator()(_UniformRandomNumberGenerator& __urng,
1805                  const param_type& __param)
1806       {
1807         result_type __ret;
1808         __detail::_Adaptor<_UniformRandomNumberGenerator, result_type>
1809           __aurng(__urng);
1810 
1811         if (_M_saved_available)
1812           {
1813             _M_saved_available = false;
1814             __ret = _M_saved;
1815           }
1816         else
1817           {
1818             result_type __x, __y, __r2;
1819             do
1820               {
1821                 __x = result_type(2.0) * __aurng() - 1.0;
1822                 __y = result_type(2.0) * __aurng() - 1.0;
1823                 __r2 = __x * __x + __y * __y;
1824               }
1825             while (__r2 > 1.0 || __r2 == 0.0); // <--- INFINITE LOOP HERE
1826 
1827             const result_type __mult = std::sqrt(-2 * std::log(__r2) / __r2);
1828             _M_saved = __x * __mult;
1829             _M_saved_available = true;
1830             __ret = __y * __mult;
1831           }
1832 
1833         __ret = __ret * __param.stddev() + __param.mean();
1834         return __ret;
1835       }
1836 
```

| GCC 9.3 | GCC 11.2 |
|---|---|
| ![gcc-9](https://user-images.githubusercontent.com/21075502/147554202-d69dfee6-8c7a-46f8-a09f-764b7e11a16e.png) | ![gcc-11](https://user-images.githubusercontent.com/21075502/147553962-46d474bd-cbfa-4966-aa8a-9875b488bf0a.png) |

`__r2 > 1.0` corresponds to the `comisd xmmA, xmmB` instruction. In the program compiled by GCC 11, `xmm8` holds a pseudo-random number between `0.0` and `1.0`, and the loop exits because `xmm8` is less than `xmm11` which holds `1.0`. But in the program compiled by GCC 9, `xmm8` holds 2^126 and `xmm2` holds 2^63, and because `xmm8` is always greater than `xmm2`, the program can never escape from this infinite loop.

Reverting to GCC 11.2 solves this infinite loop problem in `roll_normal()`, but reverting to GCC 11.2 also brings the garbage stack trace problem back.

**Comment by GoLoT** [comment]
Does it still fail when forcing the engine to LCG?
`using cata_default_random_engine = std::linear_congruential_engine<unsigned int, 16807, 0, 2147483647>; `
