### ISSUE TITLE
Dynamic reality bubble option

### ISSUE THREAD

**Issue by KittyTac** [CleverRaven/Cataclysm-DDA#53827]
### Is your feature request related to a problem? Please describe.

Currently, e.g fires burn forever and running vehicles don't drain gas when outside the reality bubble. While this is for performance reasons, I have a solution to solve this while not tanking performance all that much on decent computers. This is quite glaring and immersion-breaking.

### Solution you would like.

Make fires, running vehicles you modified or built, and running vehicles you have driven at one point (as well as other slow, continually-changing things) keep a 1-map-tile-large bubble around them. This would allow e.g a burning house to finish burning down and, with wandering hordes on, attract zombies, but a forest fire won't spread outside its map tile. This wouldn't add much of a performance tax, but there could be an option to disable it, or it could be off by default.

### Describe alternatives you have considered.

1. Making the mini-reality-bubbles 1-game-tile-large but that would make burning buildings way less realistic and be much harder to implement I think.
2. Allowing fire to spread outside of the mini-bubble, I think this would hurt performance too much.
3. Leaving as is.

### Additional context

N/A

**Comment by LeahLuong** [comment]
It used to be that exhaust from your vehicle wouldn't dissipate once it left the bubble until you returned. Perhaps something similar could be done w/ the way fire burns now. It's possible pyromaniac players could lock themselves out of games due to overwhelming their processor capacity if fire spread is implemented as the OP suggests. This would still probably be an issue w/ my suggestion, albeit less likely. My suggestion would create scenarios where stuff will only finish burning what's already on fire once outside of the bubble.

I think the 2nd suggestion may be more dangerous to implement. I haven't seen 1 in a while but I have come across running vehicles in my explorations. Generating a new bubble for each 1 of these you come across & don't shut off could grow to be excessively taxing quite quickly.

**Comment by Zireael07** [comment]
Related to #54013?
