### ISSUE TITLE
Thick-Skinned should not be a starting trait or not block bionics.

### ISSUE THREAD

**Issue by Balthasar-eu** [CleverRaven/Cataclysm-DDA#53891]
### Describe the bug

Currently it is possible to select "Thick-Skinned" as starting trait. While the trait gives a very weak cut and bash protection, it also blocks the installation of all intradermal alloy CBMs, which are far more useful. This is currently done without warning and it is not possible to purify starting traits and it seems that all other mutations that would cancel "Thick-Skinned" also prevent bionics. I think the balance and lore perspective of blocking mutated physiology from installing CBMs is fair, but I don't think a starting trait should lock you out of game options without explicitly saying so. Also lore-wise being available as starting seems to imply that thick skin is not an abnormal occurrence in the unmutated population.

I suggest one of three solutions:
1. Allow bionics to be installed together with "Thick-Skinned", like it is in the current stable. "Thick-Skinned" only gives a very minor bonus, so balance wise this might not be problematic.
2. Remove "Thick-Skinned" as starting trait: This would evade the problem entirely.
3. Keep "Thick-Skinned" as starting trait, but add a warning that it disables the use of certain bionics.

### Steps to reproduce

1. Create character with "Thick-skinned" starting trait
2. Get intradermal alloy CBM
3. Be unable to install it

### Expected behavior

See main text

### Versions and configuration

Linux tiles, 24.12.2021

**Comment by Zireael07** [comment]
My vote is for 1

**Comment by anoobindisguise** [comment]
Alloy CBM guy here. There's a reason why this is the way it is.
Bionics can either "conflict" with or "cancel" mutations. The telescopic eyes are an example of "cancelling" as they _remove_ traits rather than being blocked by traits. The alloy CBMs conflict with all these skin traits, rather than cancelling - even though they should only "conflict" with tentacles or weird limbs. This is because they are installed individually. If the alloy CBMs "cancelled" skin mutations and you had thick skin, installing alloy cbms on your legs would remove your thick skin on all other body parts. By using "conflict" the problem is avoided but not in an ideal way.
The solution to this, and I've been wanting to do this for awhile, is to make the CBMs install all as a single discrete group. Probably also with the telescopic eyes and eye protector CBMs. I think these would be best installed as part of the Exodii robotic body to differentiate them from the carbon filament CBM and also to make use of those sprites for the CBMs in Xotto (so that Rubik is no longer naked lmao). After that they can correctly cancel and conflict with CBMs.
There are other issues with CBM conflict/cancels too. The telescopic eyes don't interfere with gastropod eyestalks, and the expanded digestive system should cancel most digestion mutations like carnivore, strong/weak stomach, ruminant, intestinal fortitude, etc.

**Comment by a-chancey** [comment]
Would a pop up before installing any CBM that can block a mutation which would warn the player be possible? Or should this be considered out of character knowledge, as my character wouldn't know that alloy plating would stop me from growing fur when I chug mutagen that prior to the cataclysm, I likely wouldn't have known existed?

Additionally, shouldn't carbon filament prevent size changing and some limb mutations?

At the very least, it might be nice to get a warning on non-removable CBMs like the alloy plating, simply so someone doesn't install the leg plating without realizing it blocks toe talons or something. 

That being said, the conflict system is fantastic for controlling mutations- once I installed dermal plating, I knew I couldn't mutate out of my power armor, so I felt safe taking various serums after going post threshold alpha.
