### ISSUE TITLE
Make the new vehicle fatigue/degradation system optional and possible to turn off

### ISSUE THREAD

**Issue by cataclysmsurvivalist** [CleverRaven/Cataclysm-DDA#54012]
### Is your feature request related to a problem? Please describe.

It really adds very little to the game other than slight frustration. It's not game-breaking but it's such a pointless addition that it should be possible for any player that's not into hardcore immersion to turn off.

### Solution you would like.

Make it possible to turn off vehicle metal fatigue when creating a new world or altering an existent one.

**Comment by Inglonias** [comment]
As a rule, the lead devs on the project are against the ability to turn various features on and off like this, on the grounds that it prevents those features from being improved in the long run (everyone just turns it off and ignores it, like skill rust), and makes debugging more challenging because they need to support the game in more states.

That being said, I believe that this feature CAN be turned off using a JSON mod. Simply setting the `degradation_multiplier` flag for vehicle parts to `0.0` should achieve the desired result.

**Comment by esotericist** [comment]
as inglonias says, we generally don't provide toggle settings for core game features, especially when it's readily possible to use a gameplay mod to adjust the feature to your satisfaction (including to effectively disable it).
