### ISSUE TITLE
Debug assertion when building a faction camp

### ISSUE THREAD

**Issue by hexagonrecursion** [CleverRaven/Cataclysm-DDA#54062]
### Describe the bug

When I tell an NPC to build a faction camp, I get the below error message. Note: the faction camps do still appear to work despite the error.

```c++
 DEBUG    : loading non-main map at (344,254,0) which overlaps with main map (abs_sub = (339,249,0)) is not supported

 FUNCTION : void map::load(const tripoint_abs_sm&, bool, bool)
 FILE     : src/map.cpp
 LINE     : 6647
 VERSION  : eacb7d9
```

### Steps to reproduce

1. Talk to an Ally while in an open field
2. "There's something I want you to do"
3. "Let's talk about the camp"
4. "I want you to build a camp here"
5. Get the above error

### Expected behavior

No debug assertions should be displayed

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: eacb7d9 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

### Additional context

This was originally reported here:

https://github.com/CleverRaven/Cataclysm-DDA/issues/53830#issuecomment-1003140347

**Comment by PatrikLundell** [comment]
I do as well. This started happening fairly recently.

**Comment by moxian** [comment]
Bisected to #53598, which is not surprising in retrospect (it only introduced the debug check, the issue has been there for much longer). cc @jbytheway

The issue is easily reproduced by:

- creating a faction camp
- expanding it (to have, e.g. a farm)
- and finally building stuff in the expansion (by, e.g. tiling the farm)

Here's a simple save with all the prelimiary steps done. Load it and `e`xamine the bulletin board
[Winterpock.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7922780/Winterpock.zip)

**Comment by jbytheway** [comment]
So I added that check because doing that potentially breaks the vehicle cache. It's fine in practice for faction camps because they never place vehicles, and I don't think we will have a 'proper' fix any time soon, so maybe we should just disable the warning.

**Comment by PatrikLundell** [comment]
@jbytheway : Will it remain safe if faction camps start to place appliances? Since they seem to build on the vehicle framework there may be some undesirable side effects from it.
Note that I have no real knowledge about the code, so this is a question based only on what I think I've understood from the discussions surrounding the introduction of appliances.

**Comment by jbytheway** [comment]
Good point; I suspect appliances might cause the same problem.  I don't really understand the appliance code either.
