### ISSUE TITLE
Heroin Dependence and Painkiller dependence backgrounds create 2 separate instances of Opiate Withdrawal.

### ISSUE THREAD

**Issue by ApriamAsh** [CleverRaven/Cataclysm-DDA#54098]
### Describe the bug

Heroin Dependence and Painkiller dependence backgrounds create 2 separate instances of Opiate Withdrawal. This absolutely makes the game unplayable.

### Steps to reproduce

Pick both Heroin Dependence and Painkiller Dependence as backgrounds.

### Expected behavior

They should be compounded into the same Addiction.

### Screenshots

![image](https://user-images.githubusercontent.com/65233052/148392415-742efab5-bd7a-425b-a56f-7310c5c83ad2.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: b748443 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Extra Mutated Scenarios [extra_mut_scens],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro]
]

**Comment by Maleclypse** [comment]
Different types of opiates have different withdrawal timetables and intensities.  While DDA doesn't intentionally model those differences I do find it amusing that they play out that way.

**Comment by PatrikLundell** [comment]
If you take multiple negatives to get points to spend elsewhere you should pay for them, not get a discount because you take the same disadvantage multiple times through different avenues.

Why does it make the game unplayable? When I've taken Heroin Addiction and the trait that makes addiction easier and have worse effects, my characters have been essentially knocked out for 20-30 days, forced to drink unsafe water as the depression makes it impossible to "craft" boiled water. It was worth it, though, after the initial hellish month was survived.

**Comment by NetSysFire** [comment]
Fairly sure it also makes you vomit frequently, so trying to hold or even increase your weight will be very problematic. I did a couple of extreme junkie runs where I picked every addiction you can get and also addictive personality and weight: xs.

This will also result in reduced speed, which means you might have to deal with speed 25 for a while, which is really frustrating.
