### ISSUE TITLE
Zombies have severe Drinking Problems (Zombies can drop Barrels of Alcohol)

### ISSUE THREAD

**Issue by estebandellasilva** [CleverRaven/Cataclysm-DDA#54110]
### Describe the bug

So i was running around with a new character and after i killed a zombie and tried looting it, there was this Barrel full of Whiskey on him. While iam actually quite fond of this find i think its a little but "much".

World was created i think yesterday or the day before and was updated to the latest unstable

### Steps to reproduce

Not exactly sure what to tell you as this iss the first time i have seen this - i was killing zombies and one had a full barrel of whiskey on him.

### Expected behavior

Whiskey barrels not to be found on zombies - unless this iss intended which would be amazing ;D

### Screenshots

![image](https://user-images.githubusercontent.com/89189872/148440415-185f4fce-794e-4678-84f4-d8107f69b0fd.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: d532033 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

**Comment by ERRORCODE509** [comment]
While it is over the top and I love that it's a feature, it would probably be better if it only happened with Crazy Cataclysm active.

**Comment by LeahLuong** [comment]
I seem to have a memory of slaying a crawling Z & finding it was carrying an empty 200L tank. I like to think it was somehow hobbled by it & that's why it was crawling. Perhaps it ripped it from 1 of the troop transports & simultaneously crushed its legs. Or perhaps it doggedly clung to the tank until it was knocked loose by others, only after its legs had been worn to nubs getting dragged by the vehicle. It knew naught but to keep clinging.

W/ your scenario, it makes me think of a rioting feral human who'd looted a liquor store before succumbing completely to the blob's influence. The Z didn't know any better than to hold onto 1 of its last sentient thoughts & its subject: the triumph of loot ill-gotten.

I like that these rare drops can occur & think removing them would diminish the game.

**Comment by estebandellasilva** [comment]
> I seem to have a memory of slaying a crawling Z & finding it was carrying an empty 200L tank. I like to think it was somehow hobbled by it & that's why it was crawling. Perhaps it ripped it from 1 of the troop transports & simultaneously crushed its legs. Or perhaps it doggedly clung to the tank until it was knocked loose by others, only after its legs had been worn to nubs getting dragged by the vehicle. It knew naught but to keep clinging.
> 
> W/ your scenario, it makes me think of a rioting feral human who'd looted a liquor store before succumbing completely to the blob's influence. The Z didn't know any better than to hold onto 1 of its last sentient thoughts & its subject: the triumph of loot ill-gotten.
> 
> I like that these rare drops can occur & think removing them would diminish the game.

As i said if this is intended thats cool - it was kinda weird and unexpected that why i wanted to make sure this is not an oversight.
