### ISSUE TITLE
Remove mi-go scouts from the spawn pool for ambient encounters

### ISSUE THREAD

**Issue by mm04926412** [CleverRaven/Cataclysm-DDA#54127]
### Is your feature request related to a problem? Please describe.

Migo Scouts are faster than the player and have a powerful ranged weapon. As something to run into by accident they are far more dangerous than mobile weapons platforms which make up for their ability to wipe you out instantly are slow and easy to avoid. Anything that is faster than you AND ranged is the kind of thing you should only run into because you proactively sought out the encounter not something that you accidentally bump into on the road when your brain is on auto-pilot. They are a deadly spawn but mostly due to tedium. Normal mi-gos are bad enough but you can at least run away from them after you've accidentally got too close.

### Solution you would like.

Remove mi-go scouts from the spawn pool for the corpse encounter.

### Describe alternatives you have considered.

Make mi-go variants either be faster than you OR have a ranged weapon but not both. Something like the shocker zombie effect instead of a gun would also be a welcome change to the scout.

**Comment by Night-Pryanik** [comment]
I made a fix for your issue, 150 speed was indeed way too fast, not just for scout, but for almost any monster. But I also wanna tell you that your premises are wrong.

> something that you accidentally bump into on the road when your brain is on auto-pilot.

"I didn't take precautions, and monster killed me because of my carelessness. Nerf the monster!" That's how it looks like.

Don't turn your brain to auto-pilot then, problem solved. Who said that roads (and the whole game world) are safe so you can carelessly press the movement button and relax? And even in that case you have a safe mode which by itself could solve your entire problem. Be always on guard, turn safe mode on, make sure you have a large vision range, and you can flee from almost any threat you spot (if you cannot kill it outright).

**Comment by mm04926412** [comment]
I was anticipating a response like that, but my counter is that for the most part that roads are safe in the sense that encunters on them are things you can disenage from by simply not apporaching with a migo locking on to you being the one exception. Having to stay alert at all times during repetetive travel gameplay where that alertness is uneccesary 99% of the time just feels bad and is either something that gets you killed or is psycholigically draining.  If you look at highway hypnosis the brain turning off during long stretches of nothing is kind of inherent to people.
(https://en.wikipedia.org/wiki/Highway_hypnosis)

The migo spawns being somehow marked on the mini-overmap would also solve this, or a reduction in mi-go scout detection range. Honeslty just anything that increases the margin of error for safe mode walking around without having something you can't outrun appear from nowhere.
