### ISSUE TITLE
Cant reload survival bow

### ISSUE THREAD

**Issue by kydsh** [CleverRaven/Cataclysm-DDA#54130]
### Describe the bug

Cant reload in any way,after press "r" simply nothing happens, there is no any output in debug

### Steps to reproduce

1.get bow and arrows
2.try reload
3.get nothing

### Expected behavior

reload

### Versions and configuration

windows 10

2022-01-07-0358

russian language

mods: "dda", "blazeindustries", "aftershock", "crt_expansion", "no_hope", "StatsThroughSkills", "speedydex", "stats_through_kills", "stamina_regen_buff", "crazy_cataclysm", "Graphical_Overmap", "WHALEYHAIR1"

**Comment by new02DAY** [comment]
You don't have to reload bows, just fire.

**Comment by catdach** [comment]
Yeah bows are kinda weird in that you can't "load" them independently from firing them. seems like this has the unfortunate consequence that if you can't fire your bow for **any reason**(not enough STR, not having both hands free, etc.) the message "your bow isn't loaded" will appear in **addition** to the _actual reason_ you cant fire the bow. might be worth a separate issue request.

It is also somewhat strange that you can't load a bow without firing it. bows do have the reload use action, it doesn't appear to do anything so why is it there? You can also spawn in a "loaded" bow via debug menu. It's hard to tell if these are intentional design decisions or not. It would be nice to see how the stats of a bow change when using different ammunition like you can with guns.

**Comment by kydsh** [comment]
> You don't have to reload bows, just fire. EDIT: noticed that the reload error shows up if you don't fulfill the minimum strength requirement (6), so please check if you do.



> Yeah bows are kinda weird in that you can't "load" them independently from firing them. seems like this has the unfortunate consequence that if you can't fire your bow for **any reason**(not enough STR, not having both hands free, etc.) the message "your bow isn't loaded" will appear in **addition** to the _actual reason_ you cant fire the bow. might be worth a separate issue request.
> 
> It is also somewhat strange that you can't load a bow without firing it. bows do have the reload use action, it doesn't appear to do anything so why is it there? You can also spawn in a "loaded" bow via debug menu. It's hard to tell if these are intentional design decisions or not. It would be nice to see how the stats of a bow change when using different ammunition like you can with guns.

yes, I can just shoot through F, I'm sick with the flu, so the strength dropped to 4 and the game wrote to me that you can't shoot without reloading the bow and that you don't have enough strength, thanks for the clarification
