### ISSUE TITLE
Chance of smashing glass weapons needs rework

### ISSUE THREAD

**Issue by ianestrachan** [CleverRaven/Cataclysm-DDA#5417]
As mentioned in #5004 (and I then forgot to make an issue for it until now) the formula for hitting zombies with glass weapons and smashing the weapon is rather silly:

``` C++
if (weapon.made_of("glass") &&
     rng(0, weapon.volume() + 8) < weapon.volume() + str_cur) {
  ...
}
```

(melee.cpp, line 954, melee_special_effects)

The one for when you smash terrain with a glass object is just as bad:

``` C++
if (u.weapon.made_of("glass") &&
            rng(0, u.weapon.volume() + 3) < u.weapon.volume()) {
  ...
}
```

(game.cpp, line 6781, smash)

Both of them basically make higher-volume glass objects less likely to break.

It should be based off some combination of the weight and volume (high volume + low weight = mostly hollow or very thin; low volume + high weight = thick/dense), but I'm not sure what that combination should look like.
##

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
