### ISSUE TITLE
Finding both poisonous and normal food while foraging makes the whole batch poisonous

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#54179]
### Describe the bug

![image](https://user-images.githubusercontent.com/59517351/148657770-c8ab570a-46b4-4f39-9add-b256aab63586.png)

![image](https://user-images.githubusercontent.com/59517351/148657787-760e1202-d1c7-43a1-b3c1-0f235e4a7b71.png)

### Steps to reproduce

This is trickier to reproduce, since finding wild roots while foraging is relatively rare. Maybe modify the JSON a bit so you can only find wild roots. Then it should be trivial.

### Expected behavior

There should be two different batches. In this case I have to throw away everything.

This also happens with poisonous and hallucinogenic mushrooms in the summer.

Someone on IRC confirmed that it happened to them, too.

### Versions and configuration

- experimental

**Comment by Hirmuolio** [comment]
Is the whole stack poisonous or do the two stacks just merge in view?
Try dropping the items from that stack one by one to see if they are all poisonous.

**Comment by NetSysFire** [comment]
![image](https://user-images.githubusercontent.com/59517351/149036992-9d753116-a237-433a-b55c-34b53abb2172.png)

Unfortunately the whole stack is poisonous.

**Comment by NetSysFire** [comment]
![image](https://user-images.githubusercontent.com/59517351/149037395-625612e4-2512-4693-bc86-622cb34670c8.png)

Possibly related. Argh.

**Comment by NetSysFire** [comment]
![image](https://user-images.githubusercontent.com/59517351/149043479-514aca66-e6e9-44ba-8f59-67361da7d8e3.png)

I hereby declare that everything is broken.

**Comment by mqrause** [comment]
This is what happens when foraging:
- items from a group are selected randomly
- multiple of the same item are merged if stackable, so every comestible will spawn as one stack even if you can find multiple of them
- if you find multiple identical items, a message is printed for each find, but they refer to the same item stack
- after printing the message, the item has a chance to turn poisonous or hallucinogenic, but as with the message, you roll poisonous/hallucinogenic for the whole stack, but multiple times depending on how many you find, the more mushrooms you find, the higher the chance you can't eat all of them
- it can't turn hallucinogenic if it's already poisonous, but the other way around is possible

So this is mostly a messaging problem. Printing the message after rolling the poisonous/hallucinogenic chance will make this consistent. I'll PR that later.

Beyond that, this would need adjustments of the item groups, if that's even possible.
```
{ "item": "carrot_wild", "prob": 5, "count-min": 1, "count-max": 2 },
```
For example this entry in the `forage_spring` group will spawn 1-2 stacks of wild roots with a stack size of 3. So you get 3 or 6 wild roots as 1-2 separate but merged item drops. If this could be changed to directly drop one item with 3-6 charges it would avoid the problem of increasing the chances for poisonous/hallucinogenic roots the more you find.

Actually allowing both drops of normal and poisonous/hallucinogenic items would require even more elaborate adjustments of the item groups with entries that directly spawn poisonous/hallucinogenic so they can't merge with normal items anymore.

Instead of messing with the item groups, the best solution would be getting rid of `count_by_charges`, that'd solve this issue, minus the messaging part, because nothing will stack anymore.
