### ISSUE TITLE
Recipe guide for new contributors is outdated

### ISSUE THREAD

**Issue by matshou** [CleverRaven/Cataclysm-DDA#54199]
### Describe the bug

[New Contributor Guide Recipes](https://github.com/CleverRaven/Cataclysm-DDA/wiki/New-Contributor-Guide---Recipes) page on Github does not explain the new JSON schema for recipes. 
It does not include several important keywords such as `reversible`, `using` and `proficiencies`.

### Steps to reproduce

1. Visit [New Contributor Guide Recipes](https://github.com/CleverRaven/Cataclysm-DDA/wiki/New-Contributor-Guide---Recipes) page.
2. Read the page.
3. Compare it to the new JSON recipe schema.

### Expected behavior

I expected the guide to be up-to-date.

### Versions and configuration

- Game Version: `0.F-5097-g4019004d76`

**Comment by casswedson** [comment]
The new contributor guides serve more as a quick start or overview on specific topics, they don't need to be up-to-date with every commit because we have **the maintained** documentation it lives in `doc/`. An improvement to the new contributor pages would be a big "For further reading explore <https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/JSON_INFO.md#recipes> etc."

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
