### ISSUE TITLE
Allow making tin powder out of tin cans

### ISSUE THREAD

**Issue by hexagonrecursion** [CleverRaven/Cataclysm-DDA#54215]
### Is your feature request related to a problem? Please describe.

The game spawns small, medium and large tin cans, but you can't make tin powder out of them. Tin powder is in demand due to the tin powder -> bronze -> brazing rod chain (one of several ways to get consumables for welding).

### Solution you would like.

Add small, medium and large tin cans as precursors to tin powder

### Describe alternatives you have considered.

Allow crafting bronze directly from the cans just like we did with aluminum cans.

**Comment by Alex-Folts** [comment]
Tin cans made of [tin-plated steel](https://en.wikipedia.org/wiki/Tinning), layer of tin very thin we talking about 1g of tin per can, and you need to recover it somehow. It is bad source of tin. 

And the problem is that there is no large source of tin in household items, best you can find is solder on circuit boards, but again it is on scale of 10g.

![img](https://upload.wikimedia.org/wikipedia/en/3/35/TinConsChart.jpg)

**Comment by hexagonrecursion** [comment]
> Tin cans made of [tin-plated steel](https://en.wikipedia.org/wiki/Tinning)

Thank you. I did not know that
