### ISSUE TITLE
What should the names of each armor layer be

### ISSUE THREAD

**Issue by bombasticSlacks** [CleverRaven/Cataclysm-DDA#54273]
### Is your feature request related to a problem? Please describe.

I want to standardize the names of the armor layers. Currently they are JSON flags, in the code, and have a string to enum.
In some cases they are all different. Here is the current values for each:

FLAG | CODE NAME (ENUM) | STRING TO ENUM | IN LAYERING UI | ITEM UI
-- | -- | -- | -- | --
PERSONAL | PERSONAL | Personal | in your personal aura | Personal aura
SKINTIGHT | UNDERWEAR | Underwear | close to your skin | Close to skin
NORMAL | REGULAR | Regular | of normal clothing | Normal
WAIST | WAIST | Waist | on your waist | Waist
OUTER | OUTER | Outer | of outer clothing | Outer
BELTED | BELTED | Belted | strapped to you | Strapped
AURA | AURA | Aura | an aura around you | Outer aura

### Solution you would like.

I'm happy to standardize this but I want some feedback before I go to the bother of changing it across the code base and JSON.  Also as far as I know some changes I made recently are the first time the enum_to_string has been used in C++ or the JSON so it isn't really used currently. 

### As for my opinions
I think the flag, code name and string to enum should be ALL_CAPS

but there should be consistency in the language across these five things. Like maybe belted items should be referred to as belted in game instead of strapped. 

There also in the past was the suggestion for STREETWEAR as the flag for normal since that is more descriptive 

I'm not sure one way or the other on underwear vs close to the skin.

### Describe alternatives you have considered.

Just letting this remain confusing. It's now especially bad since flags are used for overall items in the JSON but enum_to_string is used for specific armor data.

**Comment by pjf** [comment]
If I were to standardise these, it would be to closely match the terms the player sees in the item UI. The reason being that most people play the game first before becoming contributors, and this provides minimal friction going from player → JSON editor → C++ toiler.

So:

- `AURA_PERSONAL`
- `SKIN`
- `NORMAL` (or `STREETWEAR`)
- `WAIST`
- `OUTER`
- `STRAPPED`
- `AURA_OUTER`

**Comment by PatrikLundell** [comment]
"Skin" (and "skintight") is much better than "underwear", as I can easily imagine a skin tight item on the head, but underwear gets silly.

The "waist" "layer" is odd, as it's either a layer that only applies to a single location, or a layer that has a name that implies it's for a single location. In a medieval armor situation I'd assume padding would go on the normal layer, chainmail would to on the "waist" layer, and the plate would go on the outer layer. I can't come up with anything better than "intermediate" for such a layer, though.

**Comment by bombasticSlacks** [comment]
Waist is really only used for belts and is a holdover from pre sublocations. It could be changed but I would say it's out of the scope for now.

**Comment by Terrorforge** [comment]
I think "streetwear" is a terrible name for a layer. For me at least it calls to mind a style of dress rather than a type of clothing, but even beyond that it clashes with the more utilitarian terms, and it's not even accurate, because people generally do not go out on the street without wearing a hoodie or jacket.

I suppose an alternative would be "inner" to contrast with "outer", but I think that risks confusion with the skintight layer.

As for padding/mail/plate, that's a case the current layer system just does not handle very well. The way the recent plate reworks deal with it is to incorporate chainmail voiders in the values for the plate

**Comment by coyo7e** [comment]
I don't like the wordy layer descriptions at all, there's no need to label an "underwear" layer etc. Underneath, Middle, Outer would work fine or something similar, because there simply aren't THAT many layers and if I'm wearing a couple pairs of socks I don't want or need to have them labeled as being on different layers - it adds complexity without adding anything helpful or fun.
