### ISSUE TITLE
Liquid containers auto-filling with random items

### ISSUE THREAD

**Issue by coyo7e** [CleverRaven/Cataclysm-DDA#54332]
### Describe the bug

Noticed this morning that I am having a ton of containers just filling up with no warning, including liquid containers. 11 items in a condom?! I even picked up a water tank and deconstructed something nearby and ended up with a 60L tank full of random junk.

### Steps to reproduce

1. pick up empty liquid container.
2.  pick up items (or insert them manually into container).
3. observe liquid container full of items.

### Expected behavior

Expect (sealable) liquid containers to only hold liquids - no logical reason to be able to fill a condom or water tank with hammers and wrenches and pipe fittings, although buckets and clay pots etc makes sense.

### Screenshots

![image](https://user-images.githubusercontent.com/80022377/149186803-28d34bf7-7f10-404d-8aee-c934a20d122e.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 939ec93 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Graphical Overmap [Graphical_Overmap],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by coyo7e** [comment]
Unfortunately since it seems to prioritize any container in inventory, your workaround means having to manually go in and muss with autofill settings for every piece of clothing and container I might pick up.

**Comment by tinukedaya** [comment]
It's not just liquid containers. I have a first aid kit box in my Duffel bag. And even if the first aid box has priority for the pocket set to 0 and the duffel bag has 1000, if I pick up stuff e.g. rocks, some compression shorts, brass catcher and similar, it goes straight into the first aid box and not to the duffel bag. If it would go into the box once there is no empty space anywhere else I would (partially) understand that. But like this, ignoring the set priority I consider that a **bug**. 

It's very annoying as I have drugs and stuff in the first aid box and have the contents hidden, because I don't want the clutter in my inventory. But that means, that if something else goes into the box, I can't see it and I usually forget it's there and carry the additional weight around . :/ 

And making workaround with whitelist for every single container I find is plain nuts. I just want all the stuff to go straight into the pockets based on priority if possible. And I don't see a valid reason, why rock or shorts, can't go directly into the main duffel bag pocket.
