### ISSUE TITLE
Strength should affect cut and stab damage type as well

### ISSUE THREAD

**Issue by Proxima-b** [CleverRaven/Cataclysm-DDA#54354]
### Is your feature request related to a problem? Please describe.

Reasons why blunt and bladed weapon feels unbalanced:

- Heavily armored monsters usually have higher cut resistance than blunt resistance.
- Special effect "bleeding" caused by cut damage is slow acting and rarely help with the battle.
- **Blunt damage is modified by strength while cut damage isn't modified by any stats. This cause while using bladed weapons, even against unarmored opponents, where they should have distinct advantages over blunt weapon. The performance of said balded weapons still struggle to compete with blunt weapons of the same tier** 
- The fact that many players talk trash about bladed weapons across several DDA communities because of those aforementioned reasons.

### Solution you would like.

- **Make cut damage modified by str so bladed weapon could have better performance dealing with unarmored monsters than blunt weapons.**
- Much more useful special affects causing by CUT damage.

### Describe alternatives you have considered.

- Nerf blunt weapons, but not everyone would be happy about this.

**Comment by Venera3** [comment]
First off, "balance" between weapons/damage types isn't really a consideration, or an argument for change.

*With that out of the way*, the way damage is calculated currently is very inconsistent across damage types - as you mention, strength only comes into play for blunt weapons (where it should affect all damage, realistically), each damage type uses their own schema of skill scaling (which I think could be comfortably done away with, now that weakpoints are a thing), blunt does extra stun (again, weakpoints make it redundant), and blunt damage has an inherent armor piercing that's not documented anywhere so people addinf monsters think they have to make their mobs have lower blunt armor to keep them in line.

**Comment by Proxima-b** [comment]
> strength only comes into play for blunt weapons (where it should affect all damage, realistically)

What should be done to make strengh affect other damage type? If not for the purpose of "balance", it could be for realism.

**Comment by Venera3** [comment]
What I'd do:
- Define the damage type's strength scaling in the relevant skills' skill definition 
- Include `get_arm_str` with the relevant scaling factor in each damage type's calculation
- Remove the damage scaling from skill - the skill already determines weakpoint attack chances and crit rate, both of which are much nicer systems
- Remove the inherent AP from bash (it would need an audit for bash_armor on mobs, but as I said it's almost universally low to begin with)
- Probably do away with the extra stun while we're there (crits already stun)
- *Maybe* roll all the relevant functions into one, but that would need some code magic to always retrieve the relevant skill

**Comment by Terrorforge** [comment]
The bonus bashing damage applies regardless of primary damage type, so it shouldn't be relevant against unarmored enemies. I think cutting weapons just kind of suck? Compare a [mace](https://nornagon.github.io/cdda-guide/#/item/mace) to a broadsword, for example. Their speed is near identical, but the broadsword deals 33 damage split between two types, and the mace deals 40 of a single type. The broadsword does have +2 to hit vs the mace's +1, but that difference becomes pretty small as your skills increase. It also has Parry, which isn't nothing, but in terms of damage it's pretty bad, especially when you consider all the previously mentioned inherent advantages of bashing.

I'm not sure how I feel about strength modifying cutting/piercing damage, though. It doesn't really make sense to me. With edged weapons, the weapon is doing most of the work. And there's an upper limit. If you've run a zombie through with your spear, how is stabbing it even harder going to help? I'm inclined to believe that the existing mechanics are fine, but the weapons and armor values need an audit.

Fwiw, here's my understanding of how these damage types work in real life
Bashing: Low, but consistent. Not significantly impacted by armor.
Cutting: High, but stopped by armor.
Piercing: High, but inconsistent. Does less structural damage than cutting, so either you stab something unimportant and leave the enemy still able to fight, or you hit a vital organ and kill them instantly. Can pierce or circumvent armor.

One solution could be to collapse all the resistance values into a single "armor" stat, and let damage types interact with it different. Let bashing keep the inherent AP and deal low damage otherwise.

Another thing that occurs to me is that they should maybe interact differently with weakpoints? Getting around armor would be more impactful for a dagger than a club. It would make sense to me if for example bashing was a decent all-purpose solution to armored enemies, while piercing starts out pretty bad vs. armor and gets better as your ability to exploit weak points improves.

**Comment by Coseo** [comment]
> First off, "balance" between weapons/damage types isn't really a consideration, or an argument for change.
This seems strange to me. Isn't the entire justification behind the stamina system's implementation and incredible unrealism that it makes for better gameplay? Isn't it the same for the fast healing players experience, or pole weapons not being pretty much always the best option? If "balance between weapons" isn't a consideration, shouldn't reach weapons be a lot stronger?

**Comment by Venera3** [comment]
The force concentrated at the contact point absolutely makes a difference, especially if we're talking about penetration. Bashing weapons' advantage against armor (or bones) is down to them being unable to be deflected by rigid armor - something we can kinda sorta reflect with the different armor types, making the inherent AP redundant. The actual damage values for each weapon are tangential to how the damage is calculated imho.

**Comment by Coseo** [comment]
> With edged weapons, the weapon is doing most of the work
Strength helps a lot with cutting weapons in general. The upper limit for a sword is "you cut clean through" which is such a devastating blow in many scenarios that the fight is over - you'd have to be hitting a non-vital and unimportant area for that to not kill or incapacitate it. Piercing has a much lower "upper limit", in of that it can only affect a much smaller area overall and impaling someone any further than "all the way through". Neither of these is something that its easy to do every time with low strength even against a stationary target, let alone one that you might not have hit at the perfect angle or in a soft / unprotected / thin / etc location. 

That's the "realistic" limit for these damage types regarding only hand-operated melee weapons, as real life cutting weapons can cut all the way through depending on the weapon, circumstances, wielder, location hit, and many other things. Depending on how high the transhuman fiction goes, and the weapon in question either weapon type can actually go beyond - guns are "piercing" weapons but even non-hollow-point regular bullets cause a much bigger wound than the area of the body they hit because they hit so fast that the stuff in front of them they push out of the way shreds through the rest of the body in a cone around them, like a shockwave - the faster you hit, the nastier this effect is, and this would happen with cutting weapons as well, in a slightly different way. I don't think vanilla has any cutting weapons that function like the pistol shrimp's attack, nor have I seen anything to suggest that the attacks by our transhuman characters are implied to be that fast.

In any of those circumstances the upper ceiling goes higher depending on the armor of the enemy you're fighting - the more stuff you have to push through before you can cut clean through or impale them, the more it matters.

In real life, the true "anti armor" tactic in the era when these weapons were prevalent wasn't "grab a one handed mace", it was polearms - generally those with a short spike, a hammer, a blade, or a combination of them - grappling, or cavalry. Blunt weapons were still mitigated to some degree by padded armor, which was generally worn underneath one's rigid or chain armor (or both). 

Additionally, in real life being stronger lets you fight with all of these weapons a lot better in general - you're better at blocking,  its harder to block your blows, its less exhausting, and you can swing and recover from a swing much faster. Good training, form and experience also help a lot with these things of course.

**Comment by Proxima-b** [comment]
> One solution could be to collapse all the resistance values into a single "armor" stat, and let damage types interact with it different.

That is not a good idea. A plate armor and a kevlar armor clearly have very different performance against armor types, which in this case, kevlar deals with pierce damage lot better than plate armor, but not the case with bash damage. A single resistance value would negates this kind of difference.

**Comment by Terrorforge** [comment]
Eh, probably not. Just bouncing around ideas that could avoid the confusion Venera describes.

I also cede the strength point. I could continue to argue that to a human, a stab wound is a stab wound, but if we're talking about disassembling some undead monstrosity by repeatedly punching through its chitinous skin, then yeah it probably matters.

> kevlar deals with pierce damage lot better than plate armor

I don't think this is true, though. Bulletproof vest are notoriously not knifeproof. Stabproof vests exist, but they're only meant for knives. Plate armor is pretty good at deflecting or resisting most piercing attacks short of having the spike of a poleaxe slammed directly into it.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
