### ISSUE TITLE
Add new "butchery" proficiency

### ISSUE THREAD

**Issue by GuardianDll** [CleverRaven/Cataclysm-DDA#54392]
### Is your feature request related to a problem? Please describe.

We need a new butchery proficiency, its unrealistic when random dude with fine knife has same meat, bones and skin output as experienced butcher

### Solution you would like.

adding new proficiency "butchering", "expert butchering", "skinning" and "expert skinning" into the game (but not sure how it must be)

### Describe alternatives you have considered.

not doing it

add only one level of proficiency

**Comment by coyo7e** [comment]
I'd like to see at least some nod to this as well. Having it based on survival is pretty opaque and unrewarding for those who go out of their way to skin and/or properly 'full' butcher corpses - even with 6 skill and a 30 Butchery knife and a plastic sheet and long rope etc, I fail constantly and am at a loss as to why. I'd also appreciate more verbose fail states like field dressing failures where you screw up and puncture an organ while removing the guts, and ruin part of the meat etc.

As it currently sits in experimental, it feels a bit like someone intended to add a proficiency but didn't get around to it.

**Comment by LeahLuong** [comment]
@coyo7e You are kind of overloading the thread here. I think you have some good ideas but you could prob break them out into @ least 3 separate feature requests (or more):

1. More verbose butchery feedback.
2. Coroner profession.
3. Jerky-making construction.

Dogpiling a topic like this makes it less likely to be implemented because whomever takes it on won't have a clear completion state. Breaking problems into smaller parts is an elementary aspect to solving them; adding more parts isn't helpful. What may have started as a good 1st issue for a budding contributor can quickly balloon into something even a seasoned vet of the git would be daunted by when people like yourself flood a topic like this. I hope you see what I mean.

IDK if the smoking rack (found in the '*' menu) can make jerky but smoked meat is pretty much the same thing.

**Comment by chrispikula** [comment]
I'd also suggest two more proficiencies:  Bleeding, and Plucking.  Ideally, Dressing as well, but that's beyond the scope of this bit, and would require butchery mechanics changes.

Bleeding should be pretty easy to acquire, but disastrous if you screw it up.  Plucking is just skinning adjacent, but different.  Can't really skin non-plucked birds, after all.

@LeahLuong if you re-smoke meat, you can get dehydrated meat which is somewhere on the other side of jerky.  I'd expect smoked meat to be something like store-bought smoked salmon.  You can eat it straight, but it's not quite as tough as jerky.
