### ISSUE TITLE
Feature request: Someone add the ability to get human samples from NPCs

### ISSUE THREAD

**Issue by Maleclypse** [CleverRaven/Cataclysm-DDA#54412]
### Is your feature request related to a problem? Please describe.

Players keep asking if they can get human samples from NPCs without resorting to dissection.

### Solution you would like.

I'd love if the player could get human samples once a week from non-mutated follower npc's.  Maybe so long as they have less than 5 mutations?

### Describe alternatives you have considered.

Leaving it with dissecting ferals. Which works.

### Additional context

I'm pretty certain this can be added with EOC's in the dialogue.  Need to look at rubik and see how easy that would be.

**Comment by cataclysmsurvivalist** [comment]
Adding to this, I also think taking samples from dissections (from all kinds of creatures) should have a 100% success rate.

If you're taking samples from human enemies, you can only take 2 before your character gets too depressed to gain any more, and if you're taking it from an animal, it might be a rare one, which makes brewing mutagens far harder than they should be.

You might only be able to find frogs or wolves on occasion, and if you find a low number of them, it will absolutely not be enough for you to craft enough mutagens to cross the threshold. I don't know what the exact number is currently, but from my experience it's a 50/50 chance of you getting a sample or nothing at all. This is extremely infuriating, that you can travel the entire map and do everything right and **still** not being able to get the goddamn serums you need because the game decided to not cooperate with you. And the less said about the beast samples, the better.

A 100% chance would not make the game any easier, because you need dozens of them if you want to become a full mutant, so I have no idea why the odds are so low.

**Comment by Maleclypse** [comment]
It's already at near 100% chance if you have your first aid fully leveled and a scalpel.  To make it easier would probably require C++.

> Adding to this, I also think taking samples from dissections (from all kinds of creatures) should have a 100% success rate.
> 
> If you're taking samples from human enemies, you can only take 2 before your character gets too depressed to gain any more, and if you're taking it from an animal, it might be a rare one, which makes brewing mutagens far harder than they should be.
> 
> You might only be able to find frogs or wolves on occasion, and if you find a low number of them, it will absolutely not be enough for you to craft enough mutagens to cross the threshold. I don't know what the exact number is currently, but from my experience it's a 50/50 chance of you getting a sample or nothing at all. This is extremely infuriating, that you can travel the entire map and do everything right and **still** not being able to get the goddamn serums you need because the game decided to not cooperate with you. And the less said about the beast samples, the better.
> 
> A 100% chance would not make the game any easier, because you need dozens of them if you want to become a full mutant, so I have no idea why the odds are so low.

**Comment by cataclysmsurvivalist** [comment]
> It's already at near 100% chance if you have your first aid fully leveled and a scalpel. To make it easier would probably require C++.

This is news to me, I just got done dissecting over 3 feral humans with a scalpel and a health care level of 6, and only got 1 human sample out of it. Either the game is bugged or it got updated three days ago (the time I last updated) and I missed it.

**Comment by NetSysFire** [comment]
I wonder how it would even work to get a human sample from a NPC. Do you just cut one of their fingers off? Do you take some bits of skin and flesh? Do you cultivate a small sample, which is only a very minor wound to the NPC, somehow so it becomes usable?

**Comment by Zireael07** [comment]
@NetSysFire: Bits of skin/flesh/blood seems most likely.

**Comment by LeahLuong** [comment]
This should prob sour relations a little each time you do it.

"But I only need 3 cm³ of your flesh for my science experiments! Once I make the magic potion incorporating your DNA into mine, we'll both be better off! I promise!"

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
