### ISSUE TITLE
Change how the Saltworks expansion handles salt water to be more realistic

### ISSUE THREAD

**Issue by AmarinReyny** [CleverRaven/Cataclysm-DDA#54419]
### Is your feature request related to a problem? Please describe.

So, Saltworks, as they exist now, are not realistic. As mentioned in the discussion following [another one of my feature requests](https://github.com/CleverRaven/Cataclysm-DDA/issues/54218), there's no feasible way for a post-Cataclysm survivor to channel salt water from a swamp that may or may not exist nearby into an infinite pool of salt water. In addition to being unrealistic, it's also causing hang-ups regarding further reworking of the Saltworks expansion.

### Solution you would like.

As per the suggestion given by @Maleclypse on Reddit:

>So the saltworks water sources need to be turned into depressions that are basically finite puddles of salt water but that could be easily done now and then they could be refilled manually by the player.

### Describe alternatives you have considered.

Pretending that the Blob's alterations to the fabric of reality have somehow made swamps levitate slightly so that gravity can bring the salt water into the Saltworks

**Comment by AmarinReyny** [comment]
Also, if the salt water depressions need to be refilled, then maybe there could be a basecamp mission to retrieve salt water from a swamp? Just kinda giving ideas, here.

**Comment by Maleclypse** [comment]
It actually doesn't require gravity to work differently it would require a PVC pipe buried in a low part of a swamp that's always under water.   It's actually really simple but the unrealistic part is that our recipe system for base camp construction can't calculate the number of pipes needed to the nearest swamp.  Which I'd figured that would get fixed at some point because base camps at that time stated they should be built near swamps.  Anyway thanks for writing this up to help me remember.

**Comment by AmarinReyny** [comment]
> It actually doesn't require gravity to work differently it would require a PVC pipe buried in a low part of a swamp that's always under water. It's actually really simple but the unrealistic part is that our recipe system for base camp construction can't calculate the number of pipes needed to the nearest swamp. Which I'd figured that would get fixed at some point because base camps at that time stated they should be built near swamps. Anyway thanks for writing this up to help me remember.
> 
> edit: I'll see if I can figure out how to make the NPC refill mission work.

No problem. As for the pipes, maybe instead of trying to auto-calculate a direct line to the nearest swamp, you could have a basecamp mission to construct a pipe system in the same way trenches are made? Getting something like that made might also help for making irrigation canals and such, once agriculture is overhauled.

**Comment by Maleclypse** [comment]
> > It actually doesn't require gravity to work differently it would require a PVC pipe buried in a low part of a swamp that's always under water. It's actually really simple but the unrealistic part is that our recipe system for base camp construction can't calculate the number of pipes needed to the nearest swamp. Which I'd figured that would get fixed at some point because base camps at that time stated they should be built near swamps. Anyway thanks for writing this up to help me remember.
> > edit: I'll see if I can figure out how to make the NPC refill mission work.
> 
> No problem. As for the pipes, maybe instead of trying to auto-calculate a direct line to the nearest swamp, you could have a basecamp mission to construct a pipe system in the same way trenches are made? Getting something like that made might also help for making irrigation canals and such, once agriculture is overhauled.

That's far beyond my current abilities. :)

**Comment by AmarinReyny** [comment]
> That's far beyond my current abilities. :)

Huh... Well, who made the trench basecamp missions, then? Maybe they could do something like that, if they think it's worth it.

**Comment by Maleclypse** [comment]
> > That's far beyond my current abilities. :)
> 
> Huh... Well, who made the trench basecamp missions, then? Maybe they could do something like that, if they think it's worth it.

They only play now. Designing the original base camp and working on people’s requests tanked their enjoyment so now they only play.

**Comment by AmarinReyny** [comment]
> They only play now. Designing the original base camp and working on people’s requests tanked their enjoyment so now they only play.

Ah, that's unfortunate. Still, it's good that they're doing what's best for them.

**Comment by PatrikLundell** [comment]
If I was going to somewhere to fetch salt water for future use I wouldn't dump it into a depression in the ground, but store it in tanks. If you pour it into a depression it would probably sink into the ground, and possibly also contaminate it with salt.

Flowing water is a problem as I don't think the game supports it. In principle you'd dig rows of deep pits and they'd get filled by water flowing in from the side (assuming you're not trying to go uphill...), but I don't think digging a deep pit next to water will actually cause the pit to get filled.
What you probably COULD do is to do the work to dig deep pits and then replace the tiles with deep (infinite) water ones, which could either be salt or fresh water. A problem there is that I don't think there is any way for the player to build bridges over these canals.

You could also try something similar to what Maleclypse indicated, i.e. send off someone to dig deep pits, put down pipes in them, fill them up, and then attach a mechanical pump to the pipe at the camp end (that's what they would be supposed to do: I probably wouldn't bother to actually modify any terrain as such, so the pipe wouldn't actually exist, it would just be consumed by the construction missions).
A potential future issue with this approach is that if the camp had its tiles scanned to determine what functionality it provides you'd have to have a salt water pump being a tile distinct from the normal fresh water one, or the scanning would conclude you have another fresh water pump.

A problem with a salt water fetching mission is that you'd have to provide a "tool" to bring the water back. The canning pot is the largest normal container, I think, but when I've fetched water from swamps I've used single tile vehicles with 60L tanks, and I don't think the current recipe logic allows the specification of vehicles (and if it did, it would probably have to list specific blueprints rather than vehicles with the desired properties).
Also note that salt water fetching (and other missions in swamps, such as cat tail harvesting, if that would be implemented) should be reasonably dangerous, given the critters that populate them.

**Comment by AmarinReyny** [comment]
> If I was going to somewhere to fetch salt water for future use I wouldn't dump it into a depression in the ground, but store it in tanks. If you pour it into a depression it would probably sink into the ground, and possibly also contaminate it with salt.

True.

> Flowing water is a problem as I don't think the game supports it. In principle you'd dig rows of deep pits and they'd get filled by water flowing in from the side (assuming you're not trying to go uphill...), but I don't think digging a deep pit next to water will actually cause the pit to get filled. What you probably COULD do is to do the work to dig deep pits and then replace the tiles with deep (infinite) water ones, which could either be salt or fresh water. A problem there is that I don't think there is any way for the player to build bridges over these canals.

If flowing water canals were to be implemented, how would you go about doing it? Depending on the general idea involved, I might have some ideas as to how player-built bridges could work.

> You could also try something similar to what Maleclypse indicated, i.e. send off someone to dig deep pits, put down pipes in them, fill them up, and then attach a mechanical pump to the pipe at the camp end (that's what they would be supposed to do: I probably wouldn't bother to actually modify any terrain as such, so the pipe wouldn't actually exist, it would just be consumed by the construction missions).

If this were to be implemented, do you think it would involve an auto-calculated distance/pipe cost to a selected swamp tile, or do you think it would involve construction of pipelines similar to how trenches are made

> A potential future issue with this approach is that if the camp had its tiles scanned to determine what functionality it provides you'd have to have a salt water pump being a tile distinct from the normal fresh water one, or the scanning would conclude you have another fresh water pump.

I don't see why that would be a problem. Maybe a minor inconvenience, at worst. Then again, I don't know how to code beyond basic JSON editing, so I wouldn't really know.

> A problem with a salt water fetching mission is that you'd have to provide a "tool" to bring the water back. The canning pot is the largest normal container, I think, but when I've fetched water from swamps I've used single tile vehicles with 60L tanks, and I don't think the current recipe logic allows the specification of vehicles (and if it did, it would probably have to list specific blueprints rather than vehicles with the desired properties).

Also true...

> Also note that salt water fetching (and other missions in swamps, such as cat tail harvesting, if that would be implemented) should be reasonably dangerous, given the critters that populate them.

Ah, if only there were a way to account for overmap tiles that have been cleared of monsters...

**Comment by PatrikLundell** [comment]
Water canals: They wouldn't actually provide any flow, but each tile would have infinite water instead. Construction would presumably use whatever logic the remote defense building mission uses (I haven't looked at that code).

Pipe cost: I would either have a fixed cost per overmap tile, or a cost calculated based on the distance for that tile based on (simulated) entry and exit points. The construction would be use the same logic as trenches use.

Salt water pump: Adding a salt water pump/well should actually be a fairly easy JSON task. The problem comes if that isn't used/hasn't been implemented and a save with a pre existing base having it being upgraded to a game version with a change where functionalities are defined by scanning rather than recipe specified functionalities. I.e. if your base has a normal well tile but the recipe specified that it provided salt water, scanning the tiles would show a normal (fresh) water well. I think that transition would be somewhat painful.

**Comment by AmarinReyny** [comment]
> Water canals: They wouldn't actually provide any flow, but each tile would have infinite water instead. Construction would presumably use whatever logic the remote defense building mission uses (I haven't looked at that code).

If we're just talking about canals, then a small wooden bridge made of stuff which player characters can already make via the construction menu (or at least something similar) would probably suffice. There'd probably be no need for any Z-level changes for such a small bridge.

**Comment by PatrikLundell** [comment]
Canal/bridges: Yes, height changes are required to construct actual bridges as the game currently stands. You can just build a floor and pretend there's a canal underneath, but if you'd remove the floor you'd find ground, not water. This is because of how the game currently handles "terrain", rather than how things work in reality.

**Comment by AmarinReyny** [comment]
> Canal/bridges: Yes, height changes are required to construct actual bridges as the game currently stands. You can just build a floor and pretend there's a canal underneath, but if you'd remove the floor you'd find ground, not water. This is because of how the game currently handles "terrain", rather than how things work in reality.

Ah, that makes sense... I take it that there's no way to have certain types of terrain lead to water upon removal?

**Comment by PatrikLundell** [comment]
Correct. You have a "t_whatever" terrain, and explicitly replace it with something else (there is a "t_null" but using that as a tile [as opposed to a null value to compare against] will cause a useless kind of hole in reality). It might be possible to write dismantling/smash definitions to control this, but I'm not sure. Studying how walls and floors are removed might provide a clue that may or may not be useful. Otherwise the best thing I can think of is to see if the trickery used for rugs could be applied.

**Comment by AmarinReyny** [comment]
> Correct. You have a "t_whatever" terrain, and explicitly replace it with something else (there is a "t_null" but using that as a tile [as opposed to a null value to compare against] will cause a useless kind of hole in reality). It might be possible to write dismantling/smash definitions to control this, but I'm not sure. Studying how walls and floors are removed might provide a clue that may or may not be useful. Otherwise the best thing I can think of is to see if the trickery used for rugs could be applied.

You'd know more about that than I would. I don't really have anything to offer, here.

**Comment by PatrikLundell** [comment]
I wrote it as you may want to dig around the JSON to find out if the existing definitions can be used.

**Comment by AmarinReyny** [comment]
> I wrote it as you may want to dig around the JSON to find out if the existing definitions can be used.

Maybe the "ter_set" thing can be used? I'll try experimenting with it later. I may or may not be suffering from carbon monoxide poisoning at the present moment.

**Comment by AmarinReyny** [comment]
So, uh... good news, I guess? Turns out it wasn't carbon monoxide, but other, less dangerous fumes that this body was having a reaction to. I'm still not feeling quite at my baseline, but it's better than it was this morning.

Also, apparently, the docks/bridges/etc. already have their "ter_set" things set to the appropriate water-type terrains, as of the build I'm currently using (95019f2), and upon testing, smashing and deconstructing them results in the specified water-type terrain... so, I guess it already works as-is?

**Comment by PatrikLundell** [comment]
Sounds like good news, yes (apart from the pesky physical world issues...).

Come to think of it, bridges existed before they were raised so vehicles could pass under them, so they probably worked correctly all the time. Thanks for putting in the effort to look at it.

**Comment by AmarinReyny** [comment]
So, with that established, is there a solid plan for how this will be implemented?

**Comment by PatrikLundell** [comment]
No.

Irrigation canals won't be useful at all as it stands currently, and if I were to try to implement a salt water supply I'd go for the pipe route (and ignore that salt doesn't work well with metal pipes) with a dedicated pump at the target expansion, so the bridge tangent would remain an unused tangent. I still haven't tried to look at the remote defenses code to see if it can be used as a model. but will try to do so. Whether that will be successful is currently unknown, though...

**Comment by AmarinReyny** [comment]
> (and ignore that salt doesn't work well with metal pipes)

What about naval brass? I've seen people talking about brazing rods and how bronze is now a big deal for vehicle construction in the latest experimental versions over on Reddit, and with that having been recently done, it doesn't seem to be too far-fetched to think that maybe other metals that aren't steel could also get some more applications.

**Comment by PatrikLundell** [comment]
I think it would be overkill to invent a special kind of pipe for this. It's better to keep it simple than to complicate things with more complexity. Otherwise, I would have gone for plastic (PVC) as Maleclypse mentioned, but, again, I don't think introducing plastic pipes is useful.

**Comment by AmarinReyny** [comment]
> I think it would be overkill to invent a special kind of pipe for this. It's better to keep it simple than to complicate things with more complexity. Otherwise, I would have gone for plastic (PVC) as Maleclypse mentioned, but, again, I don't think introducing plastic pipes is useful.

I mean, there are quite a few things in the game already that exist for only one purpose. Hell, there are things that are in the game that serve **no** purpose, despite their descriptions saying otherwise (there are quite a few examples among the chemicals that can be looted from labs, assuming that hasn't changed since I last updated).

Not only that, but plastic pipes could be used for other things, especially given the plan to add electricity and water supplies to buildings.

**Comment by PatrikLundell** [comment]
Electricity to buildings is "added" by exposing pre existing wiring even in walls that you built yourself (without any wire in the supply list). As far as I understand that PR has been approved.

Also, adding plastic pipes is a fair bit of (JSON) work, as that would involve not only defining them, but also adding construction of them and adding them to a bazillion different loot drop lists.

Also, I'm not aware of any current efforts to add running water, but may have missed it. In addition to that, the pipes for water and the ones for wires are typically of different dimensions.

**Comment by AmarinReyny** [comment]
> Electricity to buildings is "added" by exposing pre existing wiring even in walls that you built yourself (without any wire in the supply list). As far as I understand that PR has been approved.

... Uh... I'm not sure I get what you're describing here. Either way, electricity in buildings is probably getting to be too much of a tangent to be discussed here.

> Also, adding plastic pipes is a fair bit of (JSON) work, as that would involve not only defining them, but also adding construction of them and adding them to a bazillion different loot drop lists.

If it's all JSON, I could probably do it. Granted, I haven't really gotten into loot drop lists yet, but I've been messing around with monster groups and drops in order to tweak things to my liking on my end. Are loot drop lists significantly different from that?

> Also, I'm not aware of any current efforts to add running water, but may have missed it. In addition to that, the pipes for water and the ones for wires are typically of different dimensions.

I made a comment a while ago about it on a weekly Reddit post detailing dev plans going forward and allowing players to ask questions. I asked if buildings would have a water supply, and if so, if there would be a way to automatically purify water as it's being added to the supply. The dev who responded seemed to indicate that building water supplies are going to be added at some point, but that they weren't sure about automatically purifying it.

**Comment by PatrikLundell** [comment]
I'm referring to the PR that added the appliances wiring functionality.

I don't know any details about loot drop lists apart from approximately what they do, as I've never dealt with them myself. However, each location where a new kind of loot should be updated to have it. There's some level of recursion so adding things to a "basic" list allows it to be used by several locations. Again, I haven't looked at that myself.

My insight into the project is purely through the discussion board and git. I haven't seen anything indicating work on running water has started, but I agree things in general are heading in that direction. However, someone has to actually do it.
Personally I'd want a purifier appliance, not an automagic functionality.

**Comment by AmarinReyny** [comment]
> I don't know any details about loot drop lists apart from approximately what they do, as I've never dealt with them myself. However, each location where a new kind of loot should be updated to have it. There's some level of recursion so adding things to a "basic" list allows it to be used by several locations. Again, I haven't looked at that myself.

Understood. Thank you, regardless.
 
> My insight into the project is purely through the discussion board and git. I haven't seen anything indicating work on running water has started, but I agree things in general are heading in that direction. However, someone has to actually do it. Personally I'd want a purifier appliance, not an automagic functionality.

I was thinking it would just be an appliance of some kind that just activates automatically. I don't know if building water supplies would be anything like vehicle water supplies, but it does get kind of annoying that I have to empty a tank of clean water before I can refill it with water. Something that automatically purifies water going in would make it less of a hassle, you know? That said, again, I'm thinking that this is too much of a tangent.

**Comment by PatrikLundell** [comment]
Water cleaning: Definitely a tangent. I know there are real world systems you attach somewhere close to the faucet to purify the water that's in the system to a greater level than the common grid provides. In the game I would guess you could hook up such an appliance to the inlet of a water tank, in which case the water in that tank would be clean.
