### ISSUE TITLE
Welding/brazing rods and wires should be far more common than they are currently.

### ISSUE THREAD

**Issue by cataclysmsurvivalist** [CleverRaven/Cataclysm-DDA#54421]
### Is your feature request related to a problem? Please describe.

The game has moved on to more realism when it comes to metallurgy, but the implementations of welding rods as they are isn't as widespread as they ought to be.

When it comes to vehicles, you need them for pretty much anything, be it installing new parts or repairing old ones, yet the world does not reflect this. Welding/brazing rods are so important to crafting not just for you, but for any would-be mechanic in the post-cataclysm world, that it should be found in pretty much anywhere that vehicles would be worked on. Garages, steel mills, light industries, pit stops, garage sections in military bases, and even some civilian garages should have them, as there are plenty of car enthusiasts that don't actually work as mechanics for a living.

### Solution you would like.

* Welding rods, brazing rods, and welding wires are items that should be found in any area that is also common place for vehicles and/or metallurgical work.
* This includes garages, steel mills, light industries, pit stops, garage sections in military bases, and certain houses with 'like new'-quality cars in them.

### Describe alternatives you have considered.

Alternatively, if the item rate is not increased, perhaps recipes and/or repairs that involve those items could require less of them.

**Comment by Drew4484** [comment]
The scarcity of a resource shouldn't be adjusted based on desire for more of that resource, but rather on evidence of the resource's availability.

From my (subjective) experience, welding supplies (rods/wire/gas) are consumed quickly with large projects and the transition away from metal body panels on vehicles drops the utility of welding at body shops/mechanics. 

Craft shops might be a good source to include, as hobby welding is somewhat common. Likewise, light industry could be a good source if it represents a fabrication shop. Those two in particular may have a larger than average supply of consumables.

**Comment by Alex-Folts** [comment]
Right now welding consumables spawn everywhere where spawns acetylene torch or arc welder. As far as i know most of places where they spawns are places of consumption, i.e. where they are used. Spawn rate need adjustments, noone touched this numbers since initial implementation.

What need to do is spawn them in larger quantities in places where they supplied/distributed. In towns/cities in hardware store, maybe some other places.

**Comment by snipercup** [comment]
Right now the welding_rod_steel spawns in:

```
Mine
garage
military base
aircraft carrier
refugee center (trade /w smokes)
steel mill
craft shop
fire station
junkyard
game basement
light industry
house_detached
diary farm
abandoned barn
urban_35_hospital
mall
microlab
robofachq_static (hub01?)
```

I didn't look at the spawn rate and I didn't look at the other welding rods. From memory the garage can give up to 1000 welding rods. 
There hasn't been another change to the spawn of welding_rod_steel since #53431. Looking at the list of places it can spawn, I would expect it to be in more shops, like alex-folts says. The hardware store is a good start. After that, maybe we can tweak the spawn chance and numbers a little but this requires at least two actions:
1. find out the current spawn chance (debug test the itemgroup)
2. find out the places where you can buy them and amount you can find in reality
