### ISSUE TITLE
Missing links in "New Contributor Guide Locations"

### ISSUE THREAD

**Issue by JonathanLochridge** [CleverRaven/Cataclysm-DDA#54452]
### Describe the bug

https://github.com/CleverRaven/Cataclysm-DDA/wiki/New-Contributor-Guide-Locations
Has links that point to 404 errors.
"adding roofs", "data/json/mapgen/fire_station.jsom" are two I have identified. I may check all the others to see if I can find any new ones.

### Steps to reproduce

1. Open page.
2. click links to useful references
3. get 404 error.

### Expected behavior

I expected to have the links reach a page on the given topic.

### Versions and configuration

tested with opera and Firefox browsers on windows 10.

### Additional context
Addendum:
The mapgen tutorial, specials.json, overmap_connections.json, and overmap_terrain.json are also broken links.
Mapgen tutorial contents may have been integrated into the main mapgen doc page.

**Comment by JonathanLochridge** [comment]
It looks like someone went in and changed some of the links to make them work. But not all of them. Not sure who.
I noticed a secondary issue that the fire station no longer only has 1 variant apparently.
Although, I found it a useful reference. The original reason it was linked may no longer be applicable?

**Comment by silencecoder** [comment]
Dear @ZhilkinSerg, would you kindly update wiki page regarding broken links. It seems Github doesn't provide PR for Wiki pages.

Link '[mapgen tutorial](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/JSON%20Mapping%20Guides/Guide%20for%20beginning%20mapgen.md)' is no longer valid because there are two guides now: 

* [Beginning Mapgen Guide](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/JSON_Mapping_Guides/Guide_for_beginning_mapgen.md)
* [Intermediate Mapgen Guide](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/JSON_Mapping_Guides/Guide_for_intermediate_mapgen.md)


File [data/json/overmap_terrain.json](https://github.com/CleverRaven/Cataclysm-DDA/tree/master/data/json/overmap_terrain.json) was moved to [data/json/overmap/overmap_terrain/overmap_terrain.json](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/overmap/overmap_terrain/overmap_terrain.json) by [(#31582)](https://github.com/CleverRaven/Cataclysm-DDA/pull/31582)
File [data/json/overmap_connections.json](https://github.com/CleverRaven/Cataclysm-DDA/tree/master/data/json/overmap_connections.json) was moved to [data/json/overmap/overmap_connections.json](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/overmap/overmap_connections.json) by [(#31582)](https://github.com/CleverRaven/Cataclysm-DDA/pull/31582)


File [data/json/overmap/specials.json](https://github.com/CleverRaven/Cataclysm-DDA/tree/master/data/json/overmap/specials.json) is currently in [data/json/overmap/overmap_special/specials.json](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/overmap/overmap_special/specials.json), but it might be better to mention the whole folder instead.
