### ISSUE TITLE
New plate armor's protection is not working properly

### ISSUE THREAD

**Issue by Moumix3** [CleverRaven/Cataclysm-DDA#54647]
### Describe the bug

The new plate armor added in 4 recent PRs (high steel, mild steel, medium steel, case hardened, tempered) don't seem to give any protection when worn, according to the "Sort Armor" screen.

### Steps to reproduce

1. Spawn one of the newly added plate armor
2. Look at the item description and see the strange "4%" and "1%" next to each [BODY PART] Protection
3. Equip the armor
4. Open your Sort Armor screen, highlight the armor and look at the protection values which are all 0

### Expected behavior

The protection values should match the values given in the description of the item.

### Screenshots

Sort armor screen: ![image](https://user-images.githubusercontent.com/11393498/150589582-8b580047-15cf-44a4-b3dd-fb00fb6ec461.png)

Description of item with strange percentages (4%, 1%) next to each body part's protection: 
![image](https://user-images.githubusercontent.com/11393498/150589646-72374365-d996-4fdd-b52a-8beacdd3bc2d.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: bb20c4d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda]
]

### Additional context

I think this may be due to an issue with the coverage for each type of material. As noted above, the item description has strange percentages next to each body part's protection which are not present in any other type of armor that I could find (e.g: chainmail, kabuto, ornamental plate armor, etc...).

**Comment by AcidAntOnAMinefield** [comment]
I'd probably add that I think the iinformation that was removed/reworked recently should be re-added, otherwise those numbers make absolutely zero sense without having anything that explains what they pertain to.

**Comment by Moumix3** [comment]
Tagging relevant people: @Drew4484 (JSON side eg: #54535) @bombasticSlacks (C++ side for armor materials, I think? eg: #54470)

**Comment by Drew4484** [comment]
Looking into this, it may just be a display issue since the armor was working correctly in combat.

**Comment by Moumix3** [comment]
> Looking into this, it may just be a display issue since the armor was working correctly in combat.

This would reduce the severity of the issue (functionality is there!), but it's still super confusing in any case ;)

FYI, I did not test combat with those items. Sorry about that :)

**Comment by Drew4484** [comment]
Armor still works fine in combat, this may need some review @dseguin

**Comment by bombasticSlacks** [comment]
alright so now that I have a few minutes to clear it up. This is still a valid bug that the layering armor screen renders protection wrong I'll look into it this evening/tomorrow.

Onto the % numbers:
The reason the old values were removed is that they don't exist anymore for complex armors. The full plates are made of 1% leather, 95% thick steel, 100% chain (which is also steel). So when you are attacked a dice roll between 1-100 is made to see what parts of the armor are hit. You always get the chain since it has 100% coverage but the other two you only get some times.

Worst case scenario is you only get the chain, no leather, no other steel that happens 4% of the time (the red number).

Best case is you get all 3 which since leather is only 1 percent happens 1% of the time (number in green). 

I've thought about adding a "median" protection value where it shows in yellow how protected you would be on a roll of 50 but it would be even more info. At the end of the day your end game armors are just more complicated in how they protect you now. I could add "Best Case:" and "worst case:" to the UI beside the colored %s but nothing else in the menu has that verbosity.
