### ISSUE TITLE
Punctuation/Grammar Typos in Portal Storm Whisper

### ISSUE THREAD

**Issue by coyo7e** [CleverRaven/Cataclysm-DDA#54673]
### Describe the bug

One of the portal storm "whisper" messages has a weird exclamation point outside of some double-quotes and after a period. Additionally, that same message says "but" twice in one sentence, and after re-reading it a couple times I can't make it work, grammatically. Plus you're never supposed to begin a sentence with "but," that's why they're on your rear and not your front! ;)

### Steps to reproduce

1. Sit indoors during portal storm.
2. Wait for messages.
3. Get upset at odd grammar.

### Expected behavior

I expect ramza to be a perfect grammar nazi, two!

### Screenshots

![image](https://user-images.githubusercontent.com/80022377/150649506-6dfe93c5-759d-4955-b42d-8b601dd86d84.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 017f471 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Graphical Overmap [Graphical_Overmap],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Leland** [comment]
This is happening because we format heard sounds with an exclamation mark:

https://github.com/CleverRaven/Cataclysm-DDA/blob/acacbb1daa63bb4e96311786f08829fe4dd09d60/src/sounds.cpp#L628

Evidently we didn't anticipate interior quotations with that line. The simple approach to closing _this_ bug is the removal of ending grammatical marks from the portal whisper snippets. We'll still have the exclamation mark outside the quotation, but at least there won't be duplicates.

https://github.com/CleverRaven/Cataclysm-DDA/blob/e53cf9c14510c5769f47bc6f6ae37025ac25ea45/data/json/snippets/effect_on_conditions.json#L197

**Comment by Night-Pryanik** [comment]
Can't confirm in 0.F-12178
https://github.com/CleverRaven/Cataclysm-DDA/blob/deff4fc79093be7b063b32b53231a9c935eaa71e/data/json/snippets/effect_on_conditions.json#L197
