### ISSUE TITLE
Talking with a EXODI merchant causes a fall underground

### ISSUE THREAD

**Issue by ViachaclauSlepau** [CleverRaven/Cataclysm-DDA#54695]
### Describe the bug

Talking with a EXODI merchant causes a fall underground, a week ago it was working fine.

### Steps to reproduce

1. Go to EXODI merchant
2. click C
3. fall in talk menu

### Expected behavior

Shouldn't fall underground

### Screenshots

![image](https://user-images.githubusercontent.com/48213294/150671112-1e6da09b-f01b-4029-a40c-f39133e1a24c.png)

### Versions and configuration

- OS: Windows 10
- Game Version: unstable-51814ea
- Graphics version: Tiles
- Ingame language: Russian & English
- Mods loaded: vanila

**Comment by waxcatape** [comment]
I can confirm this, observed the exact same bug yesterday on d740104, along with the  #54407 / #54225. Tested on a brand new world, spawned in the exodii base and couldn't reproduce the fall bug. Could it have something to do with Rubik refreshing inventory?

**Comment by ViachaclauSlepau** [comment]
Rubik's CBM inventory refreshe fast too.

**Comment by waxcatape** [comment]
@ViachaclauSlepau did you exploit the inventory refreshing as in #54407? When I first noticed the bug, I'd used the refresh bug to get lots of CBMs and Rubik's shed was completely full, with no place to spawn new wares. Maybe that's why the bug is hard to reproduce.

**Comment by ViachaclauSlepau** [comment]
@ViachaclauSlepau did you exploit the inventory refreshing as in #54407? - No, I drove up to install those assembled in other places and immediately began to fall into the ground when talking from the first appeal to the NPC.

**Comment by Nerezza** [comment]
I'm having this problem too, not sure why. I've never interacted with Rubik before. I've noticed three new things happening during this, however: The bug seems to make me teleport twice, rapidly. The bug also triggers every time I use one of Rubik's dialog options.

First it's teleporting me to some location that I don't recognize. Since I'm with Rubik 1 Z-level up, the teleport leaves me in open air and I slam down into the ground for 100+ damage and potentially drop my weapon due to pain, leaving it I-don't-know-where. Second I'm teleported to a place 12 tiles to the NW of back where I was. For me that's just inside of a wall on the exterior, I can climb down safely from there.

This bug means that right now talking to Rubik breaks all my worn gear and has me using medicines to treat the really painful wounds.

**Comment by ViachaclauSlepau** [comment]
Very similar to what is happening to me. Also, I have already completed Rubik's quest for a cyborg.

**Comment by waxcatape** [comment]
Hey @I-am-Erk, did you hear about this?

**Comment by Maleclypse** [comment]
> Edit: @I-am-Erk tagging in hopes you see this. The original comment was an Eric Andre reference but I realize now it might have come off as super rude. I'm very sorry.

It may be a little while before Erk is able to look at this. No stress, more of an FYI.

**Comment by ViachaclauSlepau** [comment]
https://www.youtube.com/watch?v=fQ8mwISnvrs

**Comment by NetSysFire** [comment]
Is this a paste fail? If not, how is this private video relevant to this issue? I can't open it since it's private

**Comment by ViachaclauSlepau** [comment]
Sorry, opened the video for viewing. When a conversation with Rubik is activated, three teleportations are triggered to places 150-200 cells lower on the map.

**Comment by ViachaclauSlepau** [comment]
https://drive.google.com/file/d/1f6V_HjtDJJy20GotMPUf-RkIjdtXec5a/view?usp=sharing
This is save, this might help figure it out.

**Comment by Nerezza** [comment]
I've been investigating during my playtesting and only just now finally got to reproduce this on my brand new character, because it took 4 RL days to locate the Exodii due to a different faction base generation bug

Now with 100% certainty I can link this bug to Rubik's CBM restocks. The first teleport triggers when Rubik adds CBMs to his store for the first time, after you give him 2 anesthetic. Afterwards every time you trigger a CBM restock (see https://github.com/CleverRaven/Cataclysm-DDA/issues/54407 ) your character is briefly teleported once again.

I also think I was wrong about Rubik also being teleported with you. I think Rubik is being **DELETED** every time this happens, and a new one is being spawned in a turn after you finish your conversation.

**Comment by LeahLuong** [comment]
This reminds me of #54465. There, removal of alien grass following a portal storm was causing the player to teleport.

@Ramza13 Do you think there may be a similar cause here??

**Comment by Ramza13** [comment]
> This reminds me of #54465. There, removal of alien grass following a portal storm was causing the player to teleport.
> 
> @Ramza13 Do you think there may be a similar cause here??

Hmm its possible.  I added code for certain mapgen updates to shift the map/teleport the player away, update the map and out it back.  No time passes so I thought it wouldn't matter but maybe in certain cases you hit open air and follow.  What's weird is that if that is the case I would expect to see this happen with the refugee center missions and other places.  If anyone can provide a save where this can be reproduced I'll be happy to take a look.
