### ISSUE TITLE
Price check on cooking oil

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#54829]
### Describe the bug

I can sell a gallon jug of cooking oil to the refugee center for an absurd amount of stuff, considering how easy it is to get ahold of.

### Steps to reproduce

1. Get a jug of cooking oil
2. Trade it

### Expected behavior

I expected to get maybe $10 of value out of it? I suspect this was just something nobody bothered to correct after its volume was changed at some point.

### Screenshots

![image](https://user-images.githubusercontent.com/2125926/151260391-cb7b3435-052d-4f1d-8797-3507a1d739c4.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 582b193 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    Disable NPC Needs [no_npc_food],
    Fewer Soldier Extras [Fewer_Soldiers],
    No Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations],
    No Vault [No_Vault],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro]
]

**Comment by coyo7e** [comment]
This has bugged me for a while as well, it seems to me like a basic economics issue rather than specific to the item though, there is one NPS who wants 750 merch to follow the player however, most quests in the refugee center reward you like, 4 merch for bringing them a pile of ciggys or some weed, etc.

The sell-price for a lot of stuff seems weirdly high when it's just logically a better idea to sell the oil or vinegar etc to an NPC rather than go through the extra steps of doing quests. I haven't pushed it super hard but most of those refugee quests only give about 4 merch as a reward for items which often are worth several or ten times the amount, or more.

Possibly this could require a deep-dive into market values per unit of most items but I have been avoiding that because it might be a big pain for someone with better things to do, and I keep meaning to read through all the guides to look at it myself so I could just do a quick swipe as someone with nothing better to do.

**Comment by LeahLuong** [comment]
Cleanup on aisle 7??
