### ISSUE TITLE
Basecamp Drop Hammer not working properly in Light Industry faction camp.

### ISSUE THREAD

**Issue by Aerin-of-the-Toast** [CleverRaven/Cataclysm-DDA#54859]
### Describe the bug

When you "Expand base" in the light industry camp into the garage part of the light industry, you can create a Blacksmith Drop Hammer (it's the only thing you CAN do with the garage aside from the "Chop shop" activity). Once built, it unlocks a handful of recipes where you can use the blacksmith drop hammer to make some steel raw resources.
Problem being, the recipes all require hammering 5, which is only available through the "Basecamp Drop Hammer" dummy item. I assume this is supposed to be tied to the "Blacksmith Drop Hammer" furniture, but it is not, making these recipes unusable without debugging in the dummy item.

### Steps to reproduce

1. Make a debug world, start in a light industry.
2. Debug yourself any relevant debug mutations (such as Hammerspace so it doesn't take thirty years), spawn an NPC.
3. Reinforce the windows -> Build a bed -> Expand base -> Choose the garage section of the light industry (as in, the other section of the light industry building you're currently attached to, don't build another garage) -> build a Blacksmith Drop Hammer in the garage.
4. Disable "Debug Hammerspace."
5. Notice that the requirements for "Hammering 5" is not fulfilled, even though it should be by the Basecamp Drop Hammer.

### Expected behavior

The Drop Hammer should give Hammering 5. 
Also, ideally, the Basecamp Drop Hammer should give Anvil 3 as well, since it, quite literally, comes with an anvil, the recipe to make it requires an anvil, and the recipes in the faction camp require Anvil 3, meaning as it is currently, you'd need two anvils. One as part of the drop hammer, and one just... sitting around doing nothing, I suppose.

### Screenshots

![image](https://user-images.githubusercontent.com/75549031/151516620-30a175d5-c8a4-4504-9424-49e4199bdc96.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: bb66027 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

Just for completionist's sake, I tested both sides of the Light Industry (as in, I made a camp in the side with the red carpetting and the side with the green carpetting) and the bug persisted in both, so my guess is the bug lies with the Drop Hammer furniture itself.

**Comment by a-chancey** [comment]
Hm the more I'm thinking about this, the more conflicted I am. These days, large drop hammers seem to be less common than smaller power hammers, which had made researching this difficult, thankfully I have a friend who is a blacksmith and I bounced some questions off of him. 

Here's some examples of drop hammers:

https://www.mediastorehouse.com/granger-art-on-demand/whats-new/kansas-blacksmith-c1943-men-working-small-13214543.html

https://collections.museumsvictoria.com.au/items/778768

https://www.sciencedirect.com/topics/engineering/drop-hammer

By all logical reasoning, a drop hammer _technically_ has some anvil quality to it, on top of a high hammering quality, but as noted in that last linked article, dies are used attached to both the hammer and the anvil to mould the steel to a certain shape. Based on the description, this seems to have flat dies to just flatten steel to workable pieces. 

Drop hammers are heavy, huge, and are built to be aligned with the "anvil" in the base. Additionally, their "anvil" is more of just a solid platform, often with mechanisms to hold a die in place. That's significantly different from the standard anvil, as seen here: https://en.m.wikipedia.org/wiki/Anvil. A drop hammer would be used to either flatten to a sheet or to die hammer the steel into bars. And for some recipes, like the metal sheets or rebar, this would be sufficient. 

Notice the anvils linked above have a rounded end that sometimes comes to a conical point. That is actually a HUGE distinction, because the edges of the anvil and the rounded point are used to shape curves into the metal. They also often have holes in them to hold stages and can have a groove for small dies as well. 

Drop hammers are also different from power hammers, as drop hammers are more for larger pieces of metal, where a power hammer looks more like a hydraulic press that repeatedly hammers instead of compressing. Power hammers can be a bit more of a replacement for an anvil and hammer setup, due to the fact that they have a smaller striking surface, but you'll usually need to finish them manually. Especially something curved or complex and linked like a chain. Though my friend has forged knives entirely with a power hammer, he said getting some of the shapes down are just easier manually.

I would argue a few things with any proposed changes for this:

1) replace the anvil in the recipe for the drop hammer with a heavy frame or something similar. 

1a) possibly require power for the drop hammer. Historical ones are steam powered, modern ones are electric.

1b) add an anvil as something you need to construct in this basecamp separately, like in a field basecamp's blacksmith setup. 

2) change the hammering quality. Hammering 5 essentially implies that it'll do everything that hammering 1-4 would do. You're not going to use a drop hammer to drive nails into wood. A drop hammer is a specific metalworking tool with limited use cases. Perhaps a new DROP_HAMMER or POWER_HAMMER quality would be more appropriate. 

3) add a power hammer, either as part of the new powered appliances, or one similar to the planer/routing table/table saw furniture pieces that require a UPS to power. This will come into play much more when recipes are overhauled to use routines.
