### ISSUE TITLE
Some Gun/weapon improvements

### ISSUE THREAD

**Issue by JonathanLochridge** [CleverRaven/Cataclysm-DDA#54866]
### Is your feature request related to a problem? Please describe.

I feel like there could be more to differentiate different guns. However, most of the differences between guns of the same caliber are too small to really matter on the scale of CDDA simulation.

I also thought of an additional counter that could make NPCs with guns a little easier to handle. Or make them less effective against smarter enemies. 

### Solution you would like.

1- Add a familiarity system for guns or weapons in general. Potentially it might be based on proficiencies in some way or a new system? The small differences between guns can make a significant difference when using a gun type you aren't used to. So, potentially having gun-specific proficiencies could model that. Some guns that have intuitive micro-features could have a shorter time to gain their familiarity. 

2-Make cover effect guns more: Most npcs should prioritize getting to cover if shot at if it exists nearby. Or for some npcs if they spot you wielding a gun. And it should effect how hard it is to get shot.
Currently from what I can tell standing at the corner of a building either gives full or no cover depending on where you stand. So, it only really help grenades.
Also, from what I can tell having a window or other partial barrier between you and a shooter doesn't effect how hard it is for them to hit you.

In gameplay terms this should make the road bandits who fell trees on the road more dangerous. But depending on map design should hopefully give a player more counterplay options against npcs with guns. 

### Describe alternatives you have considered.

-Make aim times less wonky. Communicate them better and make them the primary difference between weapons of the same caliber. 

-Create an analogue to martial arts styles for ranged weapons to represent set of weapons that are familiar. Potentially give additional benefits to aim time or other weapon features. Or maybe additional range on guns that are already higher range?

### Additional context

Potentially, a proficiency/familiarity system could also be used for melee weapons, Although, this might overlap too much with martial arts?

But, I could see someone who used knife spears for a while getting used to using them in particular and judging the kind of force which might break off the blade.

Another option that might be good for melee would be to add additional improvised martial arts other than brawling. They should be worse the formal ones. But having a few styles for weapon types that are auto learned at sufficient skill/usage of the weapon type.

I could also see weapons that have bad to-hit penalties potentially being harder to gain proficiencies. But allow them to adjust their to-hit modifier?

**Comment by LeahLuong** [comment]
You raise 2 problems here & then propose a whole lot of complexity for how to potentially address those problems. Let's look @ the problems.

> I feel like there could be more to differentiate different guns.

The guns in CDDA are based on IRL counterparts, for the most part. Many guns IRL are very similar. The skill progression system w/ various types of guns does model improvements in aiming time, recoil, & accuracy. I'm not sure overlaying a proficiency system on top of this would add much beyond a slight hiccup to fluent firearm usage, from the player's perspective; most guns work in the same or very similar ways. Sure, you could argue that a vet w/ revolvers can single-load rounds faster than a rookie but a speedloader closes that gap faster than any skill difference. You might screw up using a bolt-action rifle the 1st couple of times but it's not like you have to go back to square 1 w/ each type of BA gun you come across. Would players really appreciate a proficiency gained from using Civil War era muskets??

#23720 contains a good discussion of the particulars that've gone into the gunplay of this game. Did you notice #51813 before making this post??

> 2-Make cover effect guns more: Most npcs should prioritize getting to cover if shot at if it exists nearby.

I'm all for this but it's more than 1 issue & not trivial 1's @ that. Balancing firearms is something that has gone on since this game's creation & it might finally be the case they're in a place where we could take steps in this direction. I know the issue of cover has come up many times before but I couldn't locate a specific issue linking it to gunplay beyond the corner calcs you raised. I believe cover percentages for terrain/furniture do play a passive role in determining to-hit chances for bullets but perhaps this could be turned to a more active role during gunfights. What would you suggest??

NPC AI could use some tweaks in general (to say the least) & asking it to conform w/ an unimplemented cover system is prob going too far (to say the least).

Your "additional context" is overloading the thread & similar issues have been raised elsewhere.

**Comment by JonathanLochridge** [comment]
I guess so, I probably should have slimmed it down.
I searched under issues related to cover or guns and didn't find any of those. But I didn't think of searching the PRs. I am going to need to do some more reading over what was considered there.

Although, I guess figuring out if we are in a good place to deal with this is important too.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
