### ISSUE TITLE
Fampmeat

### ISSUE THREAD

**Issue by LeahLuong** [CleverRaven/Cataclysm-DDA#54952]
### Describe the bug

I noticed #51941 before posting & realize this issue may become superfluous once that's fully implemented. That said, I'm having difficulty getting my followers to cook meat, or anything for that matter.

I upgraded my faction camp (AKA "famp") w/ a wood stove. Using the bulletin board, it says the recipe requires 7 charges from the basecamp cooking utensil. I started a fire in the stove as well as stocked a designated firewood source zone but the bulletin board recipe remained unselectable because the heat source was seemingly missing. I went ahead & cooked the 26 chunks of meat myself & distributed them to the famp afterwards but my follower should have been able to do this.

Am I missing something??

### Steps to reproduce

1. Make the famp.
2. Try to cook the meat.
3. ???
4. PROFIT!

### Expected behavior

I expected that fampmeat level would increase, because all other skills can increase in level.

### Versions and configuration

Android 0.F-3 Tiles English vanilla

**Comment by PatrikLundell** [comment]
I don't understand the weird private template you use foe issues, with their useless/completely misleading reproduction and expected behavior sections.

Base camp pseudo furniture currently use one of two types of "charges": tinder and charcoal. Tinder is what powers fireplaces, etc. used for cooking, while charcoal powers things like kilns and forges.

Why tinder? No idea, as it doesn't make much sense, but it's probably the reason for why there is a tinder recipe in the faction camp recipe bundles. It doesn't help that it isn't communicated that faction camp heat sources use tinder as their charges.

**Comment by LeahLuong** [comment]
@PatrikLundell Ah, so I _**was**_ missing something. Thanks for filling me in.

I tend to fit sufficient info into "Describe the bug" & feel it would be redundant to repeat myself in "Expected behavior" & "Steps to reproduce"; this is not always the case & so I do sometimes provide more useful info in those latter sections.

My understanding of #51941 is that it will greatly expand the list of recipes available @ famp by linking tools & qualities to workstations & then populating the list from applicable entries in the player's repertoire. I thought this overhaul might fix the problem I was having w/ my famp stove but, after your clarification, I realize that may not be the case.

I may make this into a feature request in the future because famp cooking seems needlessly arcane.
