### ISSUE TITLE
 Sheets of materials won't be used to repair items

### ISSUE THREAD

**Issue by remuluson2** [CleverRaven/Cataclysm-DDA#54962]
### Describe the bug

You cannot use synthetic sheets, cotton sheets ect. to repair items.

### Steps to reproduce

1. Get a damaged clothing item( for example MOLLE pack)
2. Get materials needed for repair and tools.
3. It will refuse to repair the item due to lack of materialls

### Expected behavior

I expected the sheets of synthetic fabric and cotton sheets to be usable as materials for repair.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 7684355 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth]
]

### Additional context

On additional note, sheets when spawned in look like they are containing items equal to the amount of sheets.
When picking them up they drop to the floor in "correct" form

**Comment by coyo7e** [comment]
I ran into this issue the other day after looting a tailoring basement and putting several thousand sheets of every kind of material into a pile. Seems specific to certain types of fabric - ie synthetic fabric comes to mind.

I solved the issue by just ignoring repairing that type of item, sadly.

**Comment by LeahLuong** [comment]
This looks like a downstream effect of #54308 or #54843. It may be this problem is already known & actively being worked on.

@a-chancey @mqrause What do you think??

**Comment by a-chancey** [comment]
Ok just updated. Seems to be related to synthetic fabric specifically. I could cut up a backpack and get “synthetic fabric” to repair other synthetic items, but my “synthetic fabric sheets” don’t work for repairs  and can’t be cut up to make the smaller pieces. Fabrics are a mess, which is why I’m working on them so much right now. I’ll jump on those either tonight or in the morning if I get a chance.

**Comment by a-chancey** [comment]
Actually, upon further investigation, synthetic fabric (item id "nylon") doesn't appear to spawn anywhere. It is *only* available by deconstructing or butchering specific items.

I'll see what I can figure out later

**Comment by coyo7e** [comment]
> Actually, upon further investigation, synthetic fabric (item id "nylon") doesn't appear to spawn anywhere. It is _only_ available by deconstructing or butchering specific items.
> 
> I'll see what I can figure out later
That may not be totally true, because I know for a fact I haven't cut up anything made of synthetic fabric and I have hundreds in my car right now, which I looted from a tailor basement in a mansion. 

![image](https://user-images.githubusercontent.com/80022377/151904478-ea4b4fbe-459f-47b9-9841-093413610c2c.png)

**Comment by a-chancey** [comment]
Those are synthetic fabric *sheets*. It’s a different item.

**Comment by coyo7e** [comment]
tbh I don't know why it was decided to have so many subcategories of basic materials like this anyway lol

**Comment by a-chancey** [comment]
> tbh I don't know why it was decided to have so many subcategories of basic materials like this anyway lol

Yeah sorry I edited my comment as it came off as rude. 

I’m working on standardizing the fabrics so we’ll have 12”x24” “commercially” manufactured sheets, the crafted equivalent patchwork sheets, each break down to 2 patchwork clothing parts. In turn, those break down to 4 6”x6” patches each (8 per sheet). Scraps are remnants to be broken down for thread or discarded as waste. 

Currently there’s NO size standard, so I did a bunch of research and found average fabric bolt sizes, measured thicknesses and found averages of each of the fabric types. There’s a few exceptions - Kevlar and leather/fur, only because of how pelts vary so much and Kevlar can’t really be patched, it has to be replaced

**Comment by coyo7e** [comment]
> tbh I don't know why it was decided to have so many subcategories of basic materials like this anyway lol

No worries (but I do appreciate the clarification), you mentioned the sheets in the OP so I was looking for them to begin with, which leads into the rabbit-hole of subcategories and figuring out which is what.

I sew a lot IRL and having these tiny patches of fabric/etc is a natural thing but they're generally only used in like quilting and stuff in any case, and are useless unless you are making very small projects or specifically want your garment/project to be particolored etc. Having them be required for repairs makes sense in the theory of "I have a small tear in this garment and don't care what it looks like, so I need a small square of fabric to back the stitching work up and reinforce that area", but it really does add a ton of complexity especially for people who don't do that type of thing a lot IRL, and there are other issues within the UI for it which I'd like t move to a discusso thread some day once I am more comfortable diving into the code for stuff.
