### ISSUE TITLE
Nails are not craftable without having at least one nail

### ISSUE THREAD

**Issue by AlexanderBodnya** [CleverRaven/Cataclysm-DDA#55017]
### Is your feature request related to a problem? Please describe.

A the moment to craft nails you need to have 

> metal fileset OR pair of flatjaw tongs

To craft metal fileset you still need

> metal fileset OR pair of flatjaw tongs

And to craft flatjaw tongs you require

> 1x lump of steel OR 2x pipe OR 2x rebar
> 1x nail

So, to craft a nail you need to have at least one nail, which is kinda strange and begs the question - where human civilization did get the First Nail?

### Solution you would like.

Either add metal tongs as alternative requirement to nail craft or remove nail requirement from flatjaw tongs recipy.

### Describe alternatives you have considered.

Remove flatjaws altogether as they do not serve any purpose and identical to metal tongs

**Comment by coyo7e** [comment]
Flatjaw tongs and "metal tongs" are totally different. The fact that one nail is needed is kind of silly at face but also, using a nail to make a metal casting form to make more nails from, is largely realistic. Without a casting form and a prior item to make the form around, you need a whole raft of equipment and skills to the point that yes, making the first nail was probably a huge ordeal and involved a bunch of PITA work and trial and error - or we could make multiple levels of nails which sounds like an unfun thing to add and be forced to use.

Metal tongs are a food cooking item that you can sometimes use to pick up and grab hot things with for various basic crafting stuff without burning your fingers on some hot stuff, but flatjaw tongs are the burly "pliers" things that a blacksmith uses to hold onto near-molten iron and forge that iron into other things (they also are so large and cumbersome they cannot be used to turn bolts etc..) The BBQ tongs you find on someone's home kitchen counter cannot be used to craft forged items, even though they can be sometimes used to craft basic metal materials.

There are some serious "chicken vs egg" type issues with a lot of metal items however, being able to use a crucible or sand to forge metal items is a real thing, and not outside of basic crafting. Perhaps a basic metal-casting setup which can be crafted via clay and sand etc, could be used in lieu of needing 1 nail?

This comes down to very basic principles. I once had a blacksmith say to me, "the only thing you can smith without a hammer - is a shitty hammer thatyou use to make a better hammer"

**Comment by AlexanderBodnya** [comment]
Fair point about removing flatjaws! IMO the best solution would be to change the required materials for flatjaw tongs craft - use 1 scrap metal instead of 1 nail. I think it's safe to assume that you can make primitive rivet from a small piece of metal.

**Comment by coyo7e** [comment]
Rivets, again, are crazy complex and take a lot of manufactured equipment. Otherwise you have to "hot forge" install them into material - and I cannot see using a glowing red piece of brass or iron and trying to force it into some canvas cloth and then bashing it, without cold-forging equipment. I fucking HATE rivets when I'm doing sewing because they damage the fabric you use them on, and also require a slightly rare and expensive tool and blank "ammo", it's almost impossible to re-use a rivet. Way easier to just stick a iron pin through most non clothing and then bend the ends over with pliers and hammer etc, via cold methods and manual labor.

**Comment by AlexanderBodnya** [comment]
Well, I'm talking from a gameplay perspective - I think it is reasonable that you can use an iron pin and bend it or rivet it in place of a nail (I'm talking like medieval metal rivets not modern factory ones) while crafting flatjaws. I agree that crafting 100 nails with a hammer and a flatjaws in a span of 5 hours is ridiculous, they are definitely should be casted and then sharpened if necessary. I'm pretty sure that you can make a cast for a nail without having one.

**Comment by coyo7e** [comment]
Good luck, and check out that youtube link, that guy is really good at explaining the process and tools and requirements to laymen, and he also fucks it up and you can hear the frustration in his voice as he's demo'ing on camera. Rivets are a high-skill niche thing that takes skill and lots of practise, especially when you get to smaller gauges which are even touchier.

**Comment by Alex-Folts** [comment]
You dont cast nails. You don't cast anything(out of iron) with blacksmithing, you join smaller lumps of iron with blacksmith welding. Casting iron(steel) become possible only in 1800's, while blacksmithing was out there for hundreds of years before, they made everything without casting into mold. Old nails was square because it was easier to forge square rod. This days nails made from long wire.

Thats [rivet](https://upload.wikimedia.org/wikipedia/commons/9/90/Rivet01.jpg), and this is [nail](https://upload.wikimedia.org/wikipedia/commons/0/0c/Clou_127.jpg), it is not a rocket science to make either. I made rivets out of piece of wire, they were look differently but they did the job.

The idea of nail required here is you need a pin, it could be made of nail, it could be rivet, it could be piece of wire, or even bolt. And to make any of those you need something to hold lump of steel while you forging it. 

And to be precise, for forging flatjaw tongs you need something to hold it too in case you make it out of shapeless lump of steel. In game it leads to chicken-egg problem, in reality were used more primitive holding tools made without pin.

Solution could be adding recipe for more primitive holding tool.

**Comment by coyo7e** [comment]
I nerded out last night on fails and learned a lot yeah. It turns out they've been made since as early as like 300 BC, which shocked me. Even in early colonial times in the USA, they had to enact laws to prevent people from burning down structures to collect nails from the ashes though (sounds familiar to cdda lol), and the first nail-machining rig in the americas showed up in the like, 1700s.

https://inspectapedia.com/interiors/Nails_Hardware_Age.php

**Comment by TealcOneill** [comment]
Rebar also isn't craftable without at-least two pieces of rebar. It doesn't matter because you can find rebar all over the place. This is definitely a non-issue if you have all the other stuff for these tongs. Heck, pick up your anvil and smash the nearest wooden wall and tada you have your nail. We definitely do not need a primitive holding tool with how quick and easy this is to make.

**Comment by Zireael07** [comment]
I think it was solved somehow for Innawoods?

**Comment by NetSysFire** [comment]
@Light-Wave how did you solve this in Innawoods?

**Comment by Light-Wave** [comment]
> @Light-Wave how did you solve this in Innawoods?

I made it so that the nail in the 'pair of flatjaw tongs' recipe could be replaced with lumps, chunks, or scraps of metal instead of the nail. 
Compare the recipe for metalworking_tongs in [innawood/recipes/tools_hand.json](https://github.com/CleverRaven/Cataclysm-DDA/blob/4c8ff78d9653f094e22fea36b07eea975d6373e6/data/mods/innawood/recipes/tools_hand.json) with the one in [data/json/recipes/tools/tools_hand.json](https://github.com/CleverRaven/Cataclysm-DDA/blob/7ba369114bddd163cc404816f307a9ccd7c46a51/data/json/recipes/tools/tools_hand.json) for reference.
