### ISSUE TITLE
Disinfectant can sometimes be painful

### ISSUE THREAD

**Issue by chrispikula** [CleverRaven/Cataclysm-DDA#55098]
### Is your feature request related to a problem? Please describe.

So, for things like the alcohol wipes, and various other lower end disinfectants, shouldn't they be painful to apply to wounds?

I saw the recent cattail jelly PR, and it got me thinking that if it the survivor is using lower grade stuff to keep themselves less infected, shouldn't some of those solutions be temporarily, and intensely painful?

### Solution you would like.

The need to scream in agony as I use salt and vinegar to clean my road rash.

**Comment by oosyrag** [comment]
Applying disinfectant to a wound can definitely sting, but it is unlikely to cause any lasting debilitating pain more than a few seconds. Unlike, for example, attempting cauterizing your wound with a soldering iron and failing a couple times before succeeding.

**Comment by chrispikula** [comment]
Oh, that's true, but doesn't the character have a chance to scream or make noise when they are in a large amount of pain?

I will completely admit, the one time I needed to clean road out of my forearm and could only clean it with napkins soaked in vinegar and salt packets, I _screamed_.

**Comment by morthein** [comment]
I'm not sure the reward for this (adding a 'sting' effect) for 5 seconds would be worth the effort.  I know some people are sensitive to cleaning of wounds, but most others aren't and to blanket apply everyone as 'screaming in agony' over using first aid seems like hassle. You'd then have to also adjust the tough trait to ignore this and without it, every time you disinfect (on the fly for example, rather than at home) you'd make noise?  that's death. I wouldn't call myself tough in real life, yet I rarely, if ever, have made a noise cleaning a wound, even mean ones.

So we find ourselves at a weird spot.  Who gets stung, for how long, and based on the crudity of the antiseptic or cleaning agent. If anything, I would adding this as an effect to the pain sensitive negative trait and not blanket everyone.

**Comment by oosyrag** [comment]
You might make more of an effort to grit your teeth and suppress a reaction given the circumstances. 

Perhaps cauterization could cause an involuntary scream? Even then a surviver could just shove their shirt in their mouth and chomp down.

Pain sensitive blacking out from cauterization sounds more interesting to me, but also probably unfun.

**Comment by Venera3** [comment]
You're not getting away with just Resident Evil dumping a flask of disinfectant on it when it comes to bite or similar wounds(irl, I know that's what happens ingame), and proper wound care hurts. Involuntary screaming is eeh, but pain/bleeding/damage would make sense.

Otherwise a bit of a sting would pretty much live somewhere in the single-point pain range, though I could see it as a constant morale penalty for the duration

**Comment by chrispikula** [comment]
I mean, it all depends on the quality of the disinfectant, and how raw the wound is, yeah?  If it's good stuff, it's not going to be much of an issue, that stuff is designed to be fairly safe.

I was thinking stuff like hydrogen peroxide, when applied directly to a fresh wound.  Now, given, we don't have many terrible disinfectants, currently, so this'll likely go nowhere, but if a survivor was bitten and all they had was vinegar, salt water, or, worse, bleach?

**Comment by oosyrag** [comment]
Cauterization already has damage and pain (I think?), so applying damage and pain to cleaning with antiseptic soaked rags and cotton balls should be similar. Or dousing a wound with antiseptic or other yet to be implemented disinfectants.

At risk of derailing the topic but somewhat related, my bigger gripe is knowing instantly what wound is infected or not (deep bites only). I'd like to see all wounds have a chance of infection without being cleaned (multiplied by clothes filthiness). The chances would be significantly lower, but if wounds were to be dressed more frequently it would lead disinfecting become more common, in turn leading to implementing more disinfecting options.

Counter agruement would be that it adds more unnecessary fiddliness, which is significant. Also the way disinfectant works now is that it is a chance to remove infection, rather than reducing the chance to become infected, which would be a significant change.

**Comment by Venera3** [comment]
Cleaning a deep, pocketed needs a lot of whatever you're using to irrigate, time, and depending how the whole thing looks a few draining cuts. The actual "disinfectant" you're using is less of a factor, provided it's reasonably sterile (freshly boiled water works in a pinch), it's mostly about getting all the scum out quickly and without too much tissue damage. 

Yeah, when wounds become their own thing "bite" will probably go away as a category and wounds will just inherit some filthiness data from their attack or something like that.

**Comment by oosyrag** [comment]
From a little additional reading, looks like there is advice against even using hydrogen peroxide (which I assume to be the antiseptic commonly scavenged), as it does damage tissue, like bleach and cauterization, but to a lesser extent. Soapy water seems to be the best for cleaning minor wounds with the least side effects. 

So if infection were a percent chance to happen based on severity/filthiness of wound, I imagine disinfectants would be a percentage multiplier to that, with minor disinfectants like soapy water around 50%, plain water around the 20s, and caustic disinfectants like bleach, antiseptic, and cauterization at 90-100% but causing various amounts of tissue damage (hp), pain, and possibly noise as per OP suggestion. Cauterization would probably be on the lower end of those, as burns can still get infected as well, and cause the most damage and pain. Antiseptic cotton balls and rags could increase the effectiveness or lower (increase?) the pain/damage. 

Would multiple applications stack? At the cost of using more resources, but it seems reasonable and if it was a percentage based system there would always be a small chance remaining. That would take the place of the current percent chance to succeed or fail. But then there would be a transparency issue for the player about how to decide how much is enough.

**Comment by chrispikula** [comment]
I'm pretty sure that the antiseptic we usually find is an actual tube of that white paste-like antiseptic, not H2O2.  That's called out, specifically, as another item, and you can even find the concentrated version in labs.  Can't use that for cleaning wounds, though.  :-p

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
