### ISSUE TITLE
[Suggestion] make an item capable of removing anything without leaving a trace, portable shredder machine

### ISSUE THREAD

**Issue by Braian226** [CleverRaven/Cataclysm-DDA#55117]
### Is your feature request related to a problem? Please describe.

I would like to remove many items lying on the ground without leaving a trace, and I don't always have a 20,000 kg roller truck to do it

### Solution you would like.

This item must be portable, maybe something similar to the portable smoking rack that already exists in the game, it must be able to eliminate anything, from steel to bodies, dirty clothes, glass fragments, etc.
with the sorting zone:  a designated area should be created that allows items to be removed from an area, this would be very useful if one wants to remove a lot of corpses, garbage, broken glass, etc.

### Describe alternatives you have considered.

fire could be said to be an alternative but it doesn't eliminate everything, and it usually goes out and you have to relight it several times to burn items like corpses and other things
I also know that it is somewhat unrealistic that the shredder eliminates "everything" but I think that it is more than anything a necessity, to be able to eliminate things, more than something about realism or not, maybe someone has a better idea, or a simpler idea
### Additional context

this might create games with less bugs if the user is constantly removing trash after looting a city or after facing 100 soldiers and
 remove bodies, MREs, etc, 
This is why i think the item must be portable and easy to carry, to encourage the user to eliminate the garbage and the things that he does not need after a battle or as I said, after a mass looting in a city

sorry for the spelling errors, I'm using a translator.

**Comment by Zireael07** [comment]
Seconding. After all, portable shredders/destructors for various stuff already exist IRL.

**Comment by oosyrag** [comment]
A paper shredder that could be relatively common to find doesn't exactly handle anything besides paper. Wood chippers might be an option. An industrial shredder would not be found outside of a dump or recycling center, not be portable or reasonably constructed by hand, and it's not like it vaporizes things out of existence either.

Alternatives for discussion:
Burning: Already mentioned, logical, and implemented. Could be improved by having common waste products at least burn long enough to destroy themselves. Or perhaps a higher powered furnace type entity that works differently than an open fire.

Compost, for otherwise unusable rotten organic waste.

Automatic decay of items: Main culprits being glass shards, zombie corpses and clothes, and perhaps metals. Unfortunately troublesome as it is unrealistic and vanishing items that a player might remember to go back for later is decidedly bad. Could perhaps be implemented as an option to decay after x days outside the reality bubble without returning into the bubble? Mostly for save game size and performance optimization over simulation accuracy.

Some way to consolidate glass shards into a single entity, pile of glass, that can consist of a variable volume/weight and number of shards? I don't know if that would help performance.

Sounds like a decent candidate as a mod or tool. If it's unrealistic to be implemented in the base game,  just make a "save file cleaner" tool that can be applied  to delete loose items of the users choice with an optional radius around the player.

Otherwise for realism better start enslaving npc survivors to collect all the glass in the city to bring back to your glass smelting sweatshop to make glass sheets.

Which leads me to a more wacky solution: janitor bots? We have functioning automated police bots, why not garbage collection?
