### ISSUE TITLE
Pickup Menu No Items Were Selected

### ISSUE THREAD

**Issue by b3brodie** [CleverRaven/Cataclysm-DDA#55137]
### Is your feature request related to a problem? Please describe.

After opening the pickup menu near items, not selecting any item to pick up and pressing enter gives an error message stating "no items were selected" and keeps the pickup menu open.  This error message seems very unnecessary because if players have not selected any items to pick up, it is almost certainly because they do not want to pick anything up rather than them forgetting to select items.

### Solution you would like.

Remove the error message upon pressing enter in the pickup menu and instead simply close the menu.  This change would allow players to more easily use the menu to view items in a specific tile without having to move their hand to the esc key to close the menu.

### Describe alternatives you have considered.

Add an interface option to enable / disable this error message.

**Comment by oosyrag** [comment]
This doesn't happen for me on Android 0.F-3. Hitting confirm without anything selected in a (g)et menu closes the menu with the message "Never mind."

**Comment by b3brodie** [comment]
Sorry, I should have mentioned that this is on the experimental branch, build version 05d6d4e

**Comment by wapcaplet** [comment]
Confirmed in experimental 0.F-5861-g3111ca2fdf

I believe this is working as intended, because players may expect that pressing Enter will pick up the selected item. The message suggests other keys you can press to select items to be picked up:

![image](https://user-images.githubusercontent.com/238395/152668988-94345296-f98f-448d-a57a-dbe2df9f76cf.png)

@mqrause This appears to be an addition of yours from #55072 if you'd care to comment.

**Comment by mqrause** [comment]
I simply made this the same as the drop menu when I first created the new menu. It's an easy change if people feel it should work differently.

**Comment by martosss** [comment]
If you press ESC to cancel the item selection (instead of RETURN) it should close the window without any messages. That's what I use to look at items on the ground.

As a noob I actually like the feature to get the error message, because it shows you that you didn't actually pick the item. So I respectfully disagree.

**Comment by PatrikLundell** [comment]
I'm with martosss on this one. The typical reason for the failure message in my case is that I selected the line, but not the item on it, so I definitely want the error message (I wouldn't object to an option to disable the warning for power users who trust themselves to always get it right, though, but someone would have to implement it...).

**Comment by martosss** [comment]
Power users can click "?" and change the "cancel" option to be something other than Escape, or just learn to use escape when they want to quickly check things around and Enter when they actually want to pick something.
