### ISSUE TITLE
(a)ctivate nearby containers to (g)et things from them (or insert)

### ISSUE THREAD

**Issue by oosyrag** [CleverRaven/Cataclysm-DDA#55142]
### Is your feature request related to a problem? Please describe.

It is difficult to manage items that are stored in nearby containers. Currently the options are to (w)eild an item, which will let you grab a single thing from inside an adjacent container into your hand, or to take the container into your inventory by weilding or wearing the container itself, which can be cumbersome and fiddly if you're holding something else or the container can't be worn (large cardboard box). Taking the container into your inventory also necessitates additional actions of manually putting the container back afterwards.

The advanced inventory manager does not "see" inside containers. I'd assume the (c) function might be intended to look inside containers, but I was unable to figure out how to utilize it. The message "You can't put items there!" occurred in all the various situations attempted.

Somewhat related storage quality of life issues: ability to manually choose a target location when unloading a container, and the ability to insert items in a container from an adjacent location. Using (a) to use an adjacent container from could open a submenu that includes insert as well as get, similar to other objects that have multiple possible actions like cutting tools.

### Solution you would like.

Adjacent containers as an available (a) use item option, which would open the (g) get item screen as if picking up from the floor, except with the contents of the container to select from instead. Additionally an option to insert would be fantastic as well. This would ideally work with nested containers as well, as long as all valid containers show up in the list of (a) usable nearby items.

### Describe alternatives you have considered.

Allow the advanced inventory manager to "open" a particular container in one of the tabs, to manipulate the items within. See #55020 

### Additional context

Currently on 0.F-3 on Android. I'm new here, so apologies if this has already been addressed or further developed in an experimental build. Or if the (c) function in the advanced inventory manager is supposed to address this and is bugged or otherwise not working properly.

**Comment by martosss** [comment]
As a fellow new player, I completely agree. Your post got me curious to investigate further since I've seen the "c" option randomly work sometimes. Here's what I found:
- Containers that **_cannot store liquids_** are broken and cannot be opened using "C". Example are large cardboard box or plastic bag.
- Containers that **_can &nbsp;&nbsp;&nbsp;&nbsp; store liquids_** can be opened using C. However, you only see the 1st item. (usually a unique liquid) inside. Examples are canning pot or condom.
- 
- The only thing that remotely helps is to unload that container(completely) in your inventory and then manipulate the items. You can do that by using the "Unload or empty wielded item" menu from outside the inventory management.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
