### ISSUE TITLE
Vacuum packing and item compression

### ISSUE THREAD

**Issue by a-chancey** [CleverRaven/Cataclysm-DDA#55144]
### Is your feature request related to a problem? Please describe.

A handful of commercially available vacuum packing solutions exist in real life, yet in game, the vacuum sealer is limited to a few recipes. It was being discussed on discord today so I figured I’d create an issue and share ideas. 

### Solution you would like.

Since we already have a vacuum sealer, here’s my ideas to add functionality to it. I’m not a C++ guy so I’ll try my best with any pseudocode 

We’d need a new field on item definitions for compressed volume, as defining a percentage based on material alone wouldn’t cut it (down filled blanket is considered 100% cotton and would benefit way more than a cotton hat or gloves). A new json flag for “compressed” would probably be needed as well. 

Add few sizes of vacuum-packed bags that spawn. The current source for the one size we have is opening vacuum sealed food you find. Depending on the type of packaging, this would damage it in real life (vacuum packed food if purchased with retail packaging is often in a non resealable bag). Having single use bags and reusable zip closure bags would possibly be overkill, but it’s worth considering. There are, however, various sizes readily available from small food sizes to “holds multiple quilts”. 

Treat them like a standard water tight  container. You can store stuff in it, but then it could be sealed with a vacuum sealer - functionally, it’ll add the compressed flag to the package and it’s contents and the volume calculations could use the compressed volume instead of the standard volume. 

### Describe alternatives you have considered.

I dunno but I’m open to suggestions. Not sure if item flags are loaded at the time pocket volume is calculated so I dunno if it’s even possible.

**Comment by martosss** [comment]
This idea seems reasonable only for clothes, as they are usually candidates for vacuum(I'm not sure if or how it's been already implemented in game). I don't see how you would compress a hammer or a bottle/ battery without damaging the item.

**_Problem A - Volume:_**
Idea 1) A lazy approach if you want to decrease the volume - take the minimum of (weight(in kg)) and (volume(in letres)) fields for the item you want to compress.
- This will compress items that are less dense than water(e.g. clothes) up to water density. It will also leave denser than water items uncompressed, as they... can't be compressed with vacuum?
- Volume data is already available in game, so no extra work to add those "compressed volume" fields to ALL CURRENTLY AVAILABLE ITEMS.
- This will be still slightly inaccurate since you can't compress items that are less dense than water to strictly water density - those items will always be slightly bigger.


Idea 2) Use (1) and on top of that use information about the item material(cotton/wool/rubber/plastic) and based on that multiply the weight of that category of items by a certain coefficient when you compress them.

The formula is volume(V,m³) * density(D,kg/m³) = weight(W,kg).

For example, you know(google) Cotton has density 450 kg/m³, or 0.45kg/L, so if you compress cotton it will have minimum volume V = (weight) / (density 0.45)


- This uses the real-world material density and will be more accurate
- Hopefully still not that hard to implement - just a weight multiplier that you need to apply, based on item material.
- ingame materials are much less than the number of items => less work.


**_Problem B - Length_**
We assume that if you can compress an item, then it is not rigid and its length will also decrease.
Idea 1) Maybe divide length by a fixed amount for each item, assuming that compressed clothes are folded into 1/2 the original length?
Idea 2) Calcualte new length based on Volume and cubic root since 1000 cm³(1 letre) of water, arranged in a cube, has cube sides of (cubic root of 1000), which is 10cm
Idea 3) Disregard item length completely and just count "bag length" to be a fixed value. You can insert a certain volume of items and compress them regardless of their original length(and weight?)
- Maybe you would be limited only by their original volume - you can insert a big blanket and shrink it, but if it's initially bigger than the bag can hold then you're in trouble.

**_Problem C - current game data_**
- some clothes are already "compressed" to their maximum, while some are compressed even more than physically possible!!! A cotton dusk mask weighs 0.17kg, but has volume only 0.10L, whereas normal cotton would have volume of (roughly) at least 0.3L if it weighs that much. So the dust mask is already "hyper compresesd" to unreal volume and it shouldn't be possible to compress it even more, in fact, you should fix those items and increase their volume to at least the minimum physically possible value.
- However, this doesn't matter and can be avoided for now for the purposes of compression - you can keep the volume unchanged if it's already less than the compressed value, and only shrink items that can be shrinked in a physically acceptable way. That shouldn't be that hard to code?

**Comment by chrispikula** [comment]
I'd use a whitelist of materials that could be compressed.  Wool/Cotton are no-brainers, but something like Leather?  Lycra?  Synthetic Fabric?  I don't know.  Plastic?  Probably not.  Others?  Generally not.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
