### ISSUE TITLE
Butchering Clothes

### ISSUE THREAD

**Issue by chrispikula** [CleverRaven/Cataclysm-DDA#55159]
### Is your feature request related to a problem? Please describe.

With the way that clothes are hidden on corpses, now, it is much less obvious that you can use the butcher menu to quickly gather resources from clothes by cutting them up.

This has caused confusion for at least one new player, perhaps more.  

The older crowd knows that this is a thing, but as it stands, new players don't.

### Solution you would like.

I don't know.
Tutorial?
Help Menu?

**Comment by Mikenyes** [comment]
"You can use the (b)utcher menu to cut apart objects in many ways.  If you (b)utcher a corpse, it will no longer be able to reanimate, and you will receive materials based on the corpse's condition, the quality of your tools, your method of butchery and your [applicable skills to butchery, i think survival?].  Many other objects can also be (b)utchered, allowing you to receive materials from quick dismantling."

**Comment by oosyrag** [comment]
Just wanted to chime in here that it was definitely one part of the new player experience that has room for improvement, especially since attempting to dismantle fabrics into thread can take hours compared to cutting one up, and doing so is among one of the first things a new survivor would want to do. It's pretty confusing when dealing with clothes when there are some you can dismantle by hand, some you cant, some things you can (a)ctivate a cutting tool to get a different set of potetial materials from the same item,  or (B)utcher, which seems to be a mix of sometimes cutting and sometimes dismantling, besides the actual action of butchering.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
