### ISSUE TITLE
Focus not correctly trending to target

### ISSUE THREAD

**Issue by stopple** [CleverRaven/Cataclysm-DDA#55165]
### Describe the bug

My character's focus wont rise to the target shown on my morale screen

I noticed multiple times while playing it seemed like my focus was raising very slowly, as I usually walk around at a target of 140, but would always hover mid 60s while playing.  Went to my base and read books over and over, watched a very slow increase to about 95, where it capped out.  Feels like there is a hidden debuff of -50 which is not being shown.

[Vid here](https://www.youtube.com/watch?v=knUdgo5Ot7s)

[Save file here](https://github.com/CleverRaven/Cataclysm-DDA/files/8011070/Feb12022.zip)

### Steps to reproduce

Load save
Read books
Watch focus not reach appropriate target

### Expected behavior

I expect focus should reach (or get close to) target shown on morale screen

### Versions and configuration

- OS Version: 10.0 2009
- Game Version: 64b4f57 [64-bit]
- Mods loaded: [Dark Days Ahead [dda],Disable NPC Needs [no_npc_food],No Fungal Growth [no_fungal_growth],Bionic Professions [package_bionic_professions]]

**Comment by oosyrag** [comment]
Reading books costs focus, as focus is spent to increase skills. The -50 or so is the equilibrium where your focus drain is equal to your focus regeneration. Focus regeneration is higher the lower it is.

You can get focus to the morale number by resting or sleeping, at very roughly an average of 1 focus per minute, so an hour or two.

However, there is little reason to wait for it to reach it's maximum before practicing skills, as it will quickly drain back down to the equilibrium point. IMO, there is only a minor gain from attempting to micromanage focus as it is now by trying to rest in between learning tasks.

However, keeping morale high in general while training skills can have a significant effect by increasing the equilibrium point.

**Comment by stopple** [comment]
> Reading books costs focus, as focus is spent to increase skills. The -50 or so is the equilibrium where your focus drain is equal to your focus regeneration. Focus regeneration is higher the lower it is.

If you watch the video, you can see me disabling survival from progressing before I read 'Through The Lense'

**Comment by martosss** [comment]
I see nothing wrong here - morale is just rising very slowly. You're reading only 7 minutes, and in 7 minutes it's rising by 1(. ...) point ... so ~10 morale/hour increase, given 50 difference to the equilibrium. It's not _that bad_.

Compare this to just standing in one place for 5-10 minutes while you have 100/150 morale and see what happens - you'll probably gain the same - 1-2 points.

I haven't looked at the exact morale refresh rare, but it's definitely quite lower than the rate at which you can drain it while training skills.

For me the problem is that **you can drain morale really fast**. I tried doing the read-craft-read thing, but I drain my morale for 20-30 minutes(from 90 to 25, crafting longbow) and then I have to wait a few hours for it to fill back up again.

Trying to keep it at very high levels isn't worth much(for training skills imho), because you'd be wasting the potential gain from books inbetween, while you read the same of that book, or while you do other things that give you morale (shave, cut hair etc).

In the end I tried finding other things to do(boil water, craft arrows, cook meat...) while the morale is slowly rising. Note that you can pause-resume crafts, so you can use that to stop when your morale gets drained and wait until it replenishes before resuming.

**Comment by LeahLuong** [comment]
There are long-term plans to address the focus system following release of 0.G. See #53372.
