### ISSUE TITLE
Boats randomly leave the player behind

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#55176]
### Describe the bug

Sometimes when traveling in a boat my character will suddenly stop, and the boat will continue moving onwards as if controlled leaving my character in the middle of the water. I seem to be able to still "drive" the boat for a few turns before the game prints an error about the boarded vehicle not being found, then I sink into water.

### Steps to reproduce

I have no clue how to reproduce this. It seems to happen at random, but I have seen it occur in the same spot multiple times. 

### Expected behavior

character shouldn't noclip out of the boat and drown

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 72ce112 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots]
]

**Comment by LeahLuong** [comment]
Where does it keep happening??

**Comment by LeahLuong** [comment]
An in cognito rookie gamer once said:

> I have seen it occur in the same spot multiple times.

I wonder what they could've meant. Perhaps, if we knew, we'd be able to reproduce this bug & have some chance of fixing it.

They also said:

> I have no clue how to reproduce this.

So I guess we'll just have to take stabs in the dark until we get lucky or some1 posts an actually actionable bug report on the same issue. Alas!

**Comment by NetSysFire** [comment]
Such issues can be very hard to debug. Please tone down your sarcasm, which even seems hostile and "you are wasting our time"-like in this case, and be helpful by providing e.g helpful hints how to debug this instead of blaming it on the reporting user.

@anoobindisguise The only debugging hint I can give for now is to create a test world, hopping into a boat and saving after every turn. If the boat leaves you behind on the next turn, exit without saving (alt+f4), re-enter this world and see if it still happens. If yes, attach the save.
Savescumming is generally unsupported and can lead to data loss, which is why you need to use a test world, but I can currently see no better way to control which turn is allowed to pass.

**Comment by LeahLuong** [comment]
@NetSysFire @kevingranade I'm sorry you see my troubleshooting attempt that way. From my perspective, I'm playfully prodding the OP for more info in order to help w/ troubleshooting while simultaneously pointing out the self-contradiction they've posited.

Looking back on the thread, I fail to see where I've given "unsolicited feedback about things other people are posting"; OP generates the thread, I query for more info, OP sidesteps my question, I point @ how their report contradicts their recent reply & reiterate our need for more info. During these exchanges, no 1 else has participated in the thread.

Looking over it today, I really don't see how the 2 of you so misconstrued my intent. NetSys's attempt @ troubleshooting took the same essential tack: prod for more info so we have something actionable to go on. OP has yet to provide that.

If you want to tell me to stop troubleshooting because I'm bad @ it, go ahead. I'm not here to tell you how to run this git but I can say that cutting people off @ the knees before they have a chance to get running is generally bad practice if you want to foster a community where people can grow into effective roles thru practice.

Confucius once said:

"To leave untaught & then kill is cruelty: to ask full tale w/out warning is tyranny: to give careless orders, & be strict when the day comes is robbery: to be stingy in rewarding men is littleness."
