### ISSUE TITLE
Evolution/Mutations in Dark Days of the Dead

### ISSUE THREAD

**Issue by TBearHug** [CleverRaven/Cataclysm-DDA#55189]
### Describe the bug

Not sure if it's an intended feature or not, but various zombies and animals seem to evolve or mutate in the Dark Days of the Dead exclusion mod. I had a winter start and noticed that along with a sea of tough and fat zombies, there are also evolved versions of cop, soldier, and hazmat zombies walking around, like the caustic soldier zombie. Mutant animals and animal zombies also appear, such as spideer and hulking horrors. 

### Steps to reproduce

World generation was mostly default, save for the DDotD exclusion mod. I chose the Sheltered scenario, putting me in the middle of winter. 

### Expected behavior

The mod description says "Only spawn classic zombies (normal zombies and zombie animals) and wildlife." I'm not sure if mutant animals and zombies that drip acid or are described as having a proboscis for a mouth are considered classic.

### Versions and configuration

Version 0.F

**Comment by Hirmuolio** [comment]
#30851 Expluding mosters by whitelist doesn't stop evolution.

**Comment by TBearHug** [comment]
How does the whitelist work? There's definitely less variety of zombies in the game and the human zombies don't seem to evolve more than once.

**Comment by xuvatilavv** [comment]
> #30851 Exluding mosters with whitelist doesn't stop evolution.

I looked into this while updating the whitelist docs, and this seems to be unrelated. The issue here is just unclear `copy-from` inheritance and categorization:
 - `spideer` is directly categorized as `WILDLIFE`
 - `hulking horror` inherits from `barghest`, which inherits from `rot-weiler`, which is categorized `CLASSIC`
 - `Caustic soldier zombie` inherits from `zombie solider`, which is `CLASSIC`

Should be entirely solvable with JSON.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
