### ISSUE TITLE
Antennae Clairvoyance

### ISSUE THREAD

**Issue by LeahLuong** [CleverRaven/Cataclysm-DDA#55205]
### Is your feature request related to a problem? Please describe.

Here's a screenshot of a rare albino penguin, seen thru the bottom of my humvee & a thick layer of pavement (in 0.F-3):

![Screenshot_20220207-193842](https://user-images.githubusercontent.com/91638992/152935996-426cb241-1542-4205-8588-40491be42e35.png)

Does any1 else find it silly my char can know exactly what creature lies beneath the road while driving over it @ 30 mph??

### Solution you would like.

Instead of notifying the player of exactly what's there, there should be a general description of the entity based on its size. &, since there's almost no way of interacting betw/ Z-lvls outside of high explosives, Antennae maybe shouldn't even be able to detect entities on different Z-lvls.

When I 1st encountered this, I almost filed a bug report for the sewage treatment plant where I perceived a scarred Z in the floor; I genuinely thought there was something wrong w/ the mapgen allowing me to see thru the floor as there have been recent reports of this in TCL. Having non-interacting mobs show up on the compass is a nuisance. Peeking staircases pretty much accomplishes what Antennae do w/out having to progress pretty far down a mutation branch.

### Describe alternatives you have considered.

Maybe have a series of tiles entries based on entity size as well as a partial creature description, similar to the generic tile for heat signature given by infrared vision. On that note, having multiple entries for infrared couldn't hurt & those same assets could be recycled & perhaps palette-swapped. After all, the heat signatures for a chipmunk & a whale wasp prob vary drastically but this isn't currently reflected IG.

In exchange for losing Z-lvl perception (or being able to toggle it off), perhaps increase the detection radius on the current lvl. I'm not sure if it scales w/ Perception but Antennae's radius seems woefully small compared to average human night vision. As implemented, 1 would rely on it only as a last-ditch & it does a poor job as a supplement to the other senses.

**Comment by robotic-gamer** [comment]
some thoughts:
- perhaps code could be made for senses like infrared, electrosense and even normal vision could be made so that every creature has a given size in a given sense and how far away it is determines how big it has to be to be visible
- the default for non-normal vision could be some percentage of its normal size while normal vision just uses its physical size
- this could be combined with objects that provide partial cover to result in some mobs appearing hidden unless really close
- this could be used to increase the amount of things like squirrels in forests without there seeming to be too many creatures.
- this could also allow for small animal trapping to be a thing to get meat without having hunt.
- I'm pretty sure antennae vision is only really useful to see what's immediately on the other side of a door.
