### ISSUE TITLE
Display total Environment protection(EP) and armor values in clothing menu and/or character screen

### ISSUE THREAD

**Issue by martosss** [CleverRaven/Cataclysm-DDA#55208]
### Is your feature request related to a problem? Please describe.

I can't see EP (and armor) values for each body part(mouth in particular) unless I dig in the menu with clothing and manually add up all the EP points from separate types of masks/scarves. Early game that means looking at 4-5 different clothes, finding that EP value and then adding it up to the others.

The same applies for total armor/protection of each limb.

### Solution you would like.

1) **Display total EP for each body part** in the clothing re-layering menu and/or in the character sheet(\@).
- This can also be done inside the clothign menu when you scroll(left/right) to inspect only 1 body part - show values for that body part in the bottom left
![image](https://user-images.githubusercontent.com/7064677/152967208-5190381d-5066-40f1-a48a-f3010270a729.png)

1.1)  **Explain the effect of EP** . For example, say "fully protected from thin/./thick smoke", or maybe "less prone to acid"(if that's a thing for other body parts, I still don't know).

Potential benefit - players will have a better idea of how well protected their limbs are and whether they need additional EP/armor - something important when you're trying to stay alive?

### Describe alternatives you have considered.

1) **Display EP near other status info** in the top right(where limb health and speed/focus ... are).
- However, it would be too cluttered to include it there. I think the right place is in the clothing menu.

2) **A separate menu to show only EP and armor** for each limb?
- Probably too much work and ultimately useless, since we already have clothing info menu?
- A separate menu would complicate the decision what clothing to wear, since you'd have to bounce between the 2 menus to look at info.

3) Accumulate all clothing effects per body part - water proof, glare-protected, etc (but this might 
- This can get too cluttered? I was tempted to include it in the "solution I'd like", but I realize now that those effects can stack quite a lot. Still it's a potential option that can be considered, given we have a better way to see per-limb info.

**Comment by AcidAntOnAMinefield** [comment]
The protection values aren't added up the more things you have worn on each limb, ie they don't stack.

Let's say you have 4 items on your torso;
B=Bash | C = Cut | Ba=Ballistic | F=Fire | A=Acid | E=Enviromental
- 9B, 9C, 16Ba, 1F, 1A, 1E. Close to skin
- 1B, 1C, 0Ba, 5F, 3A, 1E. Normal. 
- 4B, 4C, 2Ba, 0.5F, 0A, 10E. Outer. 
- 0 to all stats. Strapped onto.

That doesn't mean you have 14B, 14C, 18Ba, 6.5F, 4A and 12E. This means your protection values against these sources of damage(?) are 9B, 9C, 16Ba, 5F, 3A, 10E. The highest stat from each item is what counts.

This is something someone with a better understanding of the code can interject and correct me if I am wrong but, for example:
- If you have 10 items that all offer 10 bash protection, that doesn't mean you have 100 bash protection. It means that you have 10 chances at protection against Bash damage up to 10 (coverage values also matter.) Your items will not just suddenly become strong the more items you have alongside them. The only exceptions to this rule are Encumbrance and Warmth which *do* add up the more items you wear. (which makes sense, the more clothes you wear, the warmer you become).

I should also add Environmental Protection is not the same as Acid Protection (or Fire, for that matter). You can have an item that gives you 20 Environmental Protection but 0 Acid, meaning you will still take damage from acid, whereas the other way around is also true. Environmental Protection acts against things like the random airborne diseases checks (Influenza, Common Cold), Smoke, Toxic Gas, Tear Grenades and Radiation. 

If we were to have a display of all your individual items stats protection all added up, that would result in erroneous information display to the player. Most of the time, when you examine clothes, you will have that data on them, which tells you what those clothes do. [Faraday Chainmail Suit "fully protects you from electric discharges", or the Phase Immersion Suit (fully protects you from Radiation)]. Some items will also outline that their special values will only work under certain conditions [Clean/Hazmat suit will only fully protect you from radiation if you have a gas mask]. 

However I do agree that we could potentially have a way to display the **Highest** protection value for each worn item per limb, as well as clarification as to what the warmth units mean for new players. 
The way it currently stands, it is very easy for new players to assume that the (-xx) or (xx) in warmth are measured in whichever Temperature unit they play with, when that is not the case.

**Comment by martosss** [comment]
Also, I wasn't sure what exactly Warmth values means, but the important thing is that the total value is display and it's also color coded, so you learn pretty much that green is good, blue/yellow/red is bad.
Now that you make me think about it, Warmth is probably how much heat your body loses. So if my body loses more heat than it can generate I'll get frostbite .. and if I'm generating more heat than I can give out to the environment(because I'm insulated with warm clothes), then I'll start sweating - that makes sense. However, knowing what exactly Warmth means doesn't change your gameplay decisions as long as you know what's "good" and what's "bad". I think the current UI for Warmth is very good.

However, the UI for EP & armor is not good, because I don't know EP & armor values for each limb(whether a sum or the maximum of a single item, doesn't matter, just show me what it is?), so I don't know if I need to put on more armor or not, or whether I need to wear more masks against smoke or not.

**Comment by LeahLuong** [comment]
My understanding of layering armor is the same as yours, mart: each layer provides its protection going inwards. Otherwise, what's the point of CBM armor or innate protection granted by mutation?? This seems to be backed up by discussion in #52789.

If EP values are implemented for display in any menu, please be cognizant of #54756. Replicating UI issues on more interfaces will only make the problem worse.

**Comment by CalKerethi** [comment]
I believe that's the right interpretation for armor layering. For my money, I'd love to have something that looks kind of like this:
```                Cov  Bash   Cut   Bal  Acid  Fire  Env
Kevlar vest     85%   6.0   9.0  15.0   0.0   0.0    0
chainmail vest  95%  10.5  10.5   6.0   0.0   0.0    0
leather vest    90%   3.0   3.0   3.0   0.4   0.2    1
Overall              17.8  20.3  21.2   0.4   0.2    1
Reliability            ++     +     -   +++   +++
```
Those values might fit beside the item name in the existing display, if we allowed it to cut the name off after a certain point ("pair of western boots -> M17 17-rou..."). The aggregate stats, I'm dubious about. I think the ones I put there are kind of okay.

I calculated Overall as the sum of value * coverage for each item, which is kind of useful since it can help you estimate how much less damage you'll take over time in a drawn-out fight, over the course of an entire lab dive, and so on. I based Reliability on some fiddly guesswork using the variance that would probably give a statistician a heart attack, but in general, I would want some measure of how "swingy" (vague hand-waving here) your protection is. What that measure is, I'm not numbers-savvy enough to know.

And even so, this display only goes so far to show you that, for example, a survivor wearing only a Kevlar vest on their torso will take full damage from 3 bullets to the chest out of 20. "Chance to die instantly if a turret sees you before you see it" can be a pretty important statistic in certain circumstances!

**Comment by martosss** [comment]
BTW here's what I found regarding how armor works - https://github.com/CleverRaven/Cataclysm-DDA/wiki/Developer-FAQ#how-armour-protection-is-calculated

I hope it hasn't changed recently(this link is 4 years old )

**Comment by LeahLuong** [comment]
@martosss The 1st thread I linked (above) contains dev discussion from just a couple of months ago. It takes some inference on your part but can give you an understanding of how the armor system works.

**Comment by bombasticSlacks** [comment]
> This is something someone with a better understanding of the code can interject and correct me if I am wrong but, for example:

Hundred percent wrong. Completely incorrect. 

This is on my list of things to add to the game! I'm waiting on some code organization and restructuring stuff out of my control but it is coming. I'm going to add your best case, worst case and median damage protection for each type on each location. 

I'm adding best case, worst case and median since materials on each armor are rolled separately too now (if the materials don't cover the whole suit). 

So basically you will see your defense values if the monster rolled a 0 on its attack (every piece of armor your wearing is hit) and each material roll was a 0 (each material on the armor protects) which is best case,

same but with 100 for the attack and 100 for material (so each material that could possibly be missed and each possible armor that could possibly be missed) this is worst case

same but with 50 for attack and 50 for material (so this is the materials and pieces that cover at least 50% of the time) this is the median protection.

It will just be in the layering menu since it will be a lot of text!

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.

**Comment by bombasticSlacks** [comment]
I'm pretty sure this was completed and is in shown in the body UI.
