### ISSUE TITLE
Extradimensional doppeganger/scaling NPC as a hostile monster.

### ISSUE THREAD

**Issue by Techmind** [CleverRaven/Cataclysm-DDA#55210]
### Is your feature request related to a problem? Please describe.

The end game for CDDA is 'i am overpowered' and nothing can challenge me (good stats/gear/maxes spells in magiclysm/eating a lot mutagens/installing cmbs OR death-mobile).
What if we introduce some sort of 'scaling monsters' ?

### Solution you would like.

I have this funny idea of having 'scaling' monsters, which are basically  another survivor.

In caves of qud there is there is this perk of 'evil twin' and some monsters which can clone you. So you get a chance of having dismembered/espered/sniped to death by your own build (same stats/weapons/resists).

This could work as 'extradimensional doppelganger' or something like this.
Bonus points if it can use death-mobile, will ram into you/could correctly use spell from magiclysm/use mini nuke to fuck-up your base/steal your loot)

Simplest solution is just give him 'mirrored gear', because grenades/sniper rifles/lots of armor and good melee can be as dangerous to you as to regular zombies.

**Comment by LeahLuong** [comment]
Just let your followers use grenades & guns. You can RP it like they're "evil doppelgängers" while you're looking @ the tombstone screen. Extra credit for letting them wield the mininuke laucher!

Alternatively, you can mess w/ worldgen settings to increase difficulty & postpone that "boring" endgame content. I don't think the game needs more "gotcha! you're dead" scenarios that involve coinflipping when you step around the wrong corner.

**Comment by oosyrag** [comment]
So you're looking for something that can kill you so that you can start over? While currently it is possible for you to simply voluntarily start over or impose limitations on yourself to increase challenge, adding something to the game that kills op characters would be involuntary for people who enjoy playing as their op characters.

**Comment by Techmind** [comment]
Nah. i just find it unrealistic that Pc can get overpowered and all other survivors - not really. Imagine there is a survivour who loot/clean-ups nearby aread and have a base a bunch of overppored gear/etc. He will be attacked/stealed from regularly.  But if you make attackers 'weak' they be basically walking 'loot farms'.
Kenshi for example have 'raids' from other groups which scale with your group size & wealth.

**Comment by bombasticSlacks** [comment]
Once Portal Storms are more mature I plan to write cross dimensional sites of interest that will attract other highly geared survivors from all over multidimensional space. These highly rewarding areas would be completely optional but give that PVP itch against other very kitted survivors with no chance for recruiting or negotiating. They would also be timed since the point of interest will stop existing as the portal storm stops.

In a similar vein there is a desire to make more hostile patrols as time progresses. This would include MIGO slaver squads and stuff as well. The tech is being worked on to make all of this possible.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
