### ISSUE TITLE
Bear trap dissapears after captured in it monster is killed 

### ISSUE THREAD

**Issue by MaxD98** [CleverRaven/Cataclysm-DDA#55238]
### Describe the bug

You can place a beartrap and capture zombie or some animal with it. After you kill any monster which has status "Stuck in beartrap" you might notice that your bear trap just disappeared. This problem occurs with buried bear traps too. 
In 0.F-3 any bear trap remains after use. 
But if monster is strong enough to release himself from bear trap (like a zombie brute) the trap also remain and you can place it again. You can also stuck into bear trap and release yourself and this bear trap will not disappear.

### Steps to reproduce

1. Spawn one bear trap and place it on ground.
2. Spawn some zombie or animal which can't avoid traps.
3. Lure them into bear trap.
4. Kill them with weapon or debug option.
5. Notice that your bear trap is now gone.

### Expected behavior

I excepted that bear traps should remain after use. They are obviously durable and shouldn't disappear after one use.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: d065e00 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by robotic-gamer** [comment]
I suspect what is going on is on use the beartrap is made to exist as a status condition on the victim which then turns back to an item at the end of the status effect. thus killing them deletes the status condition and with it the trap. The easiest way to test this would be get something to trigger the bear trap then debug remove the status effect before it wears off. The simplest solution I can think of is to have a bear trap be put immediately into the victims inventory on use rather than after its status condition wears off. to prevent the player from getting trapped by a bear trap and placing it back down before they are free the status effect of bear traps should prevent placing traps.

**Comment by Night-Pryanik** [comment]
> In 0.F-3 any bear trap remains after use.

Looks like it's false memories. Tested on 0.F-3 right now, bear trap disappears too. In fact, code for bear traps didn't changed for 7 years.
