### ISSUE TITLE
Open container in the inventory can contain stuff, cause items to disappear or cause straight crash

### ISSUE THREAD

**Issue by Vilabnotavailable** [CleverRaven/Cataclysm-DDA#55270]
### Describe the bug

I noticed that cdda crashed when i was unloading my casserole pot ( open container, shouldn't contain anything but when wielded ) in my backpack which was containing 5 items ( various water and medic bottles, themself containing stuff ).

so : **1st and primary issue, fixing it would prevent the other from happening at all** :
open container in a backpack ( or in a open container in a backpack ) will contain stuff which are grabbed by the player, which is very annoying because it should not be possible, disorganize the inventory, prevent the player from using cooking devices... 
ex : Backpack < pot < tin can < book
 
2nd issue : item dissapearance, using previous exemple :
unloading the pot will drop the tin can in the backpack as expected, the book **disappear**. it is not dropped on the ground, is no longer in the tin can, do not show up by filtering the inventory

3rd issue : CDDA freeze to death and is no longer responding
unloading an open container containing a lot of things will cause the game to die

ex on the save : Backpack < casserole pot < rag, + full water bottle, + full medic bottle, + tin can < rag, + book

dropping manually each item contained in the pot is not an issue

dropping the pot with all the stuff inside isn't either

unloading the pot, or spilling its content when grabbing it after dropping it, freeze the game

### Steps to reproduce

1 have a ( big enough, pot ) open container in a pocket ( backpack... )
2 grab a small item 
3 observe that it went into the open container, which it shouldn't

2bis grab a smaller open container ( tin can )
3 grab a very small item
4 observe that open container n1 is containing n2 which is containing the last item
5 unload n1
6 find empty n2 in the inventory
7 can't find the last item anywhere

third issue is very hard to reproduce from scratch, but is very consistent from my save 

### Expected behavior

open container in a pocket should not be able to contain stuff which are grabbed by the player

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 03e7363 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Hope [no_hope],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

[no hope_copy_copy.ZIP](https://github.com/CleverRaven/Cataclysm-DDA/files/8043618/no.hope_copy_copy.ZIP)

**Comment by robkuijper** [comment]
Started looking into this, since I'm partially responsible for the new nested container pickup behavior.

The overall issue of open containers was discussed over on Discord; consensus was that it's slightly weird to have (for example) a bucket in a backpack that only takes up space, while it can also contain items.

As per my current implementation the nested pockets have priority over their parents, which will probably need to be the other way around; parents before their children (also makes more sense, since nesting items *should* also result in more movement/time being consumed).

I'll still have to look into the item disappearing, but it might have something to do with the freezing problem.

Nested spilling containers result in an infinite loop in `item_pocket::handle_liquid_or_spill`, since an item gets removed from the pocket, but added to the same pocket again (in your case the problem lies with the tin can and its contents when you unload the casserole pot). I'm currently working on finding a fix to the core of this problem.

**Comment by pjf** [comment]
I may have encountered this (or something adjacent to it) with auto-sort zones. My character sorted my bucket of blanching acorns into the fridge, and then immediately sorted the bucket into the empty containers zone. The blanching acorns are nowhere to be seen.
