### ISSUE TITLE
Making "flintlock guns" realisticaly better, distincting rifles and smoothbore guns, making the latter ones much easier to produce

### ISSUE THREAD

**Issue by Vilabnotavailable** [CleverRaven/Cataclysm-DDA#55283]
### Is your feature request related to a problem? Please describe.

Hi, I quite like the idea of using antique-like blackpowder using guns in a post-cataclysm setting.

Most people interested in 16th-19th century History or just Guns at least roughly know how to use them, build them, and how blackpowder is made. They are also often featured and described in time travelling fiction novel. 

They are great no industrial and chemical infrastrure standing weapons, since they don't require nearly as much advanced equipment and chemistry knowledge to make a working copy and its ammo as it is to produce a modern gun and cartridge ammunitions.

Indeed, making a functionnal copy from salvaged parts is incredibly easy, Smoothbore guns are little more than a piece a wood on which is fixed a pipe with a spark producing device, the latter part is the most complex one, and yet could be replaced by a simple butane lighter. Rifled ones however requires a rifled pipe which is much harder to make without proper equipment.

However in the game they are poorly implemented, incredibly poorly balanced, and looking at json/items/gun/flintlock is very revealing. 

First, you must notice that the gun named "flintlock musket" is a smoothbore gun according to its description and relative stats, yet it is mis-identified as "rifle_flintlock" and is the basic design on which every other flintlock gun is a relative copy of.

   **The actual issues : **

- All flintlock guns are way under ranged, this start with the flintlock musket with a range of 8, while most handguns in game have a range of 13 and beyond. The flintlock pistol is a joke with a range of 2

- The "flintlock rifle" ( id : "longrifle_flintlock ) is an actual rifled gun, it is more accurate and can be used for longer range, but it shouldn't take any longer to reload. Yes they historically did since the bullets had to be forced into the rifling. But anyone with a knowledge of antique guns, and any book featuring them will include the pricinciple of the "minié ball" which came a bit later, this ball make it as easy to load a rifled gun as it was to load a smoothbore one while being compatible with both and about as easy to produce as previous ones, This is the type of balls that a survivor would focus on

- The "flintlock carbine" and "handmade double-barrel flinlock" are rifled guns according to its description, yet are based on the smoothbore flintlock musket statistics ("rifle_flintlock") instead of the actual rifled guns ("longrifle_flintlock" ). which makes them way too much inaccurate.  

### Solution you would like.

I would like to see :

- A clear distinction between smoothbore guns and rifled ones, the latter having better accuracy and better range at the cost of needing actual equipment to produce.

- **Much** lower skill and equipement requirements to produce smoothbore guns, those shouldn't be any more complex to make with salvaged parts than the early pipe gun serie.

- A much needed rebalancing of antique weapons range, and reload times. Smoothbore pistols should be usables with a range of 7 or so. Smoothbore carbines and muskets should have similar or longer range than modern handguns, rifled antique guns should have slightly lower range than modern rifles and shouldn't have longer reload time than smoothbore muskets.

- Antiques and Makeshift guns recipes could be included in a few novels books to make them easier to find.

Extras : A distinction between actual antique gun replicas ( proper flintlock system, lenght and encumbrance differences between smoothbore musket and rifled Pennsylvania guns...  ) found in museum and on reenactor, and simpler survivor made ones.

**Comment by robotic-gamer** [comment]
some thoughts:
- a more renewable way to get the stuff for ammo is needed for them to see use
- because runs that would make them (non-nomadic) can't because it can't be made renewably
- you will quickly run out of ammonia or sulfur to make more black powder
- nomadic runs on the other hand won't really make black powder because they will have looted guns and aren't really set up heavy duty crafting
- as for bullets its probably best to at least of one lead free option exists since lead tends to be a bit scarce and competes with building up a vehicle/base power grid
- one option for shotguns would be flechettes, only uses steel at the cost of needing to craft flechettes .
- for rifled guns one could use copper jacketed steel bullets as a sort of makeshift ap round
- an improvised option for both would be to use scrap copper as either shot or a crude slug
- alternatively casting proper ammo from copper could be used
- lastly precious metals like silver and gold could substitute for copper is desired
- perhaps make blunderbuss ammo represents smoothbore guns while flintlock ammo represents rifled guns?
- the max effective range for antique/makeshift guns should probably be effectively limited by low accuracy rather then hard limited by max range, as this would match up with how they were used for volley fire into formations
- this would mean you could use it practically to soften up a group more easily then a single zombie
- crafting rifling would be fairly difficult but it could be done by first crafting a smoothbarrel
- then have something hard like a diamond on a stick to cut the needed groves into the barrel
-  the makeshift guns would probably tend to use electrical based ignition systems due to its simplicity
- the easiest way to make them use power would probably being able to use charged batteries as a charged tool like you can use a lighter charge to light a cigar.
- alternatively you could just require a lighter charge to light the powder directly
- a good "advanced" blunderbuss would probably be a blunderbuss with a 6 round capacity due to a revolver action that fires using electric charge
- another good blunderbuss would be a one shot pistol
- another option given what's out there would be for a survivor to craft a portable cannon (as big as you can get and still be fireable in someone's hands) to be used in a similar role to a .50 cal rifle (ie anti hard target)
- It would not be overly difficult to craft considering you could craft it by casting metal in clay
- this also leads to the potential for crafting full scale cannons for use as a vehicle weapon
- an alternative to casting metal a temporary cannon can be made from wood reinforced with bands of iron
- the main pro would be easier construction, the main drawback is it would only last a few shots
- another vehicle gun that could be built is a volley gun which would functionally just be a big heavy gun that has a large ammo capacity but has to be reload one at a time

**Comment by DoctorGoat** [comment]
I do like the actual method of wearing a brace of flintlocks and drawing/firing them/dropping them, and I realize now I haven't ever used electromagnetic unit to pull the ones I've dropped to me during a lull in combat and reloading them during that.

A mercury fulminate primer being used instead a black powder dish you light with a fire source would be nice. The mentioned electrical charge method would be good, as well. These could be gun mods for reloading?

**Comment by Vilabnotavailable** [comment]
My point of view on the antique guns would be to fix what we have now first, because it is quite obviously broken.

Every single one of those guns have abysmal range, even the Pennsylvania rifle has a lower range than most handguns.

The description of the historical carbin do not match its performances at all, it is said to be a rifle but it has much worse dispersion than the smoothbore musket. The damages don't make sense either, the historical carbin and the handmade double barrel gun are much less powerful than the pistol.

The easiest recipe to make the antique-like guns, the double barrel handmade one, is requiring much higher level skill and tools than the very similar cartridge pipe gun serie, making them unavailable to craft without previous extensive use of other firearms in game, thus making it very much pointless.

> A mercury fulminate primer being used instead a black powder dish you light with a fire source would be nice. The mentioned electrical charge method would be good, as well. These could be gun mods for reloading?

There are already various blackpowder cartridge with primers in the game such as the 45-70 Government, if you use primers you may as well fully upgrade.

It also kind of defeat the point of relative ease of production.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
