### ISSUE TITLE
Selling items to *some*  Forge Of Wonder give more money than buying them back.

### ISSUE THREAD

**Issue by tranhuulong** [CleverRaven/Cataclysm-DDA#55368]
### Describe the bug

Some Forge of Wonders have different buy/sell rate. Any items sell to some can be buy back relatively cheaper,and is repeatable multiple times thus is exploitable for infinite money. This seem to apply to some other base game's NPC merchants as well.Also, sell value will increase up to around 60-70% at 20 social skill but buying value stay the same, so its even more broken at higher social skill. 

### Steps to reproduce

1. Have some high value item like orichalcum cauldron, or some weapon that sell well.
2. Find a specific Forge/Merchant that have the high sell, low buy rate.
3. Profit (a lot)

### Expected behavior

You know, the usual economy i guess.

### Screenshots

1. The *normal* rate
![Normal rate](https://user-images.githubusercontent.com/75026870/153830163-42e74733-9bc4-4f67-9d1c-da659f179abf.png)
:
2. The *Special offers* rate
![Special rate 1](https://user-images.githubusercontent.com/75026870/153831190-1769ce5c-e21f-45eb-92f2-edf4d34ffa18.png)
![Special rate 2](https://user-images.githubusercontent.com/75026870/153831195-88922e8e-1d3c-4934-9f70-a9b89604ada8.png)

### Versions and configuration

- OS: Windows
    - OS Version: Win 7 [64-bit]
- Game Version: 0.F-3 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Crazy Cataclysm [crazy_cataclysm],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills]
]

**Comment by martosss** [comment]
Making the resell cost(of buying back items you sold to this Wonder) x1.5 or x2 would solve this?

**Comment by catdach** [comment]
A similar issue was reported a while back #46081

Trading is a really weird mechanic that has a whole mess of stuff that affects item prices (for example: social skill, faction standing, player ugliness, and I think perception/intelligence stats)

Identical items being valued differently based on whether you're selling or buying isn't a problem in itself (think of it as haggling with the vendor). The real problem is the constant buying/selling of the same items over and over as an infinite money exploit. (ok selling an item and buying a cheaper _copy_ of it is also a problem, but that's a **lot** harder to solve)

So yeah, the best way to fix this is to track sold/bought items and adjust their prices accordingly.

I'm not familiar with that code but If there is indeed no individual item tracking in place, then I wouldn't expect this to be fixed for a while.

**Comment by Waladil** [comment]
There should probably just be a check that makes an even return the best possibility. 
If (buy price < sell price)
{sell price = buy price}
That way at very high skills you'd be able to evenly swap items of equal value, which would prevent this type of abuse while also being a really good deal

**Comment by catdach** [comment]
That could work.

I could foresee _some_ edge cases where the sell price of items effectively goes down because you get too good at haggling, which would effectively make it harder to trade for items with more fixed value(aka currency items). Optimizing trade between multiple merchants might also become a little wonky. However those are pretty nitpicky issues.

In general it's probably a good idea to limit to how _"good"_ prices can become for the player.

**Comment by andrei8l** [comment]
> If (buy price < sell price) {sell price = buy price}

If you always do this, then you lose the advantages of the social skill and intelligence stat. If you only do it when both parties have the item, then you can game it easily by buying all the stock then selling it back for profit.

**Comment by Maleclypse** [comment]
I'm leaving this open as there are a number of bugs in this space.   There is significant desire for advanced functionality in trade code.

**Comment by andrei8l** [comment]
This was fixed in #57706, though IMHO the Forge Lord should have their intelligence stat nerfed
