### ISSUE TITLE
Game crashing on mac

### ISSUE THREAD

**Issue by Taeltales** [CleverRaven/Cataclysm-DDA#55419]
### Describe the bug

game crashes on launch on OSX

### Steps to reproduce

1. Open the game on mac osx 10.12.6

### Expected behavior

the game's icon will appear in the dock then it will crash

### Versions and configuration

-osx 10.12.6
-0.F-3 Frank-3

**Comment by BrettDong** [comment]
Prebuilt binary in GitHub releases requires macOS 10.15+.

**Comment by BrettDong** [comment]
> Prebuilt binary in GitHub releases requires macOS 10.15+.

The reason for that is dependency libraries (e.g. SDL2) installed from Homebrew package manager on GitHub Actions build machines are targeted to macOS 10.15 or higher.

To make the precompiled version on GitHub releases playable on older macOS systems, one needs change the build process to use Frameworks that targets to older macOS versions instead of pulling dependencies as dynamic libraries from Homebrew package manager, and also tune compiler flags to target macOS 10.12. If anyone is interested, feel free to create a pull request for that.

While that being said, macOS 10.12 support might be broken again once we migrate to C++17. I remember that system libraries in macOS 10.12 lacks support for some functionalities in C++17 standard, so compiled executable may face runtime crashes or even won't launch because of missing symbols.
