### ISSUE TITLE
Flour should require a container

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#55422]
### Describe the bug

In real life, you need to store flour in any container because you can not pick it up from surfaces with your bare hands since it is a very fine powder.

### Steps to reproduce

1. Be naked.
2. Wield some flour.
3. Go get a backpack and put a variety of stuff in, including your flour.
4. Go for a swim in the river and drop the flour in the shallow water.
5. The flour is unharmed and perfectly retrievable.

### Expected behavior

Flour (and other, similar items such as lentils perhaps) should be handled like a liquid. When flour comes in contact with (non-clean) water, it should also become unusable.

This should more or less require the player to actually invest in some containers (a sack or a pot, even a paper bag suffices) for storing such substances.

### Versions and configuration

- experimental

**Comment by estebandellasilva** [comment]
Dunno i think its kinda fun if you think about it ... like pocket sand

**Comment by martosss** [comment]
- IRL, yes, you need bags for everything ... You also shouldn't mix powders in the same bag (think cocaine + flour).

- In-game that is 1 more layer of bags to click through when accessing your powdered gold - is that really what you want? The inventory system is a bit cluttered already, and you want to make it even worse?

I would consider the current state to be a Quality Of Life(QOL) feature, rather than something that needs fixing.

You're always welcome to put all of your powders in (separate!) containers - the game doesn't stop you.

Exercise for homework - try spawning 20 half-full gallon bottles of different liquids(ammonia, bleach, honey, cough syrup) that are not full completely and try to fill completely as many bottles as you can so you "compress" and "tidy" the liquids into fewer bottles and you have more empty bottles to use. Annoying, right? Now do that also with all the powders in game ... That alone should be enough reason not to want this feature.

**Comment by morthein** [comment]
+1 for the water dissolving part.  It is funny that your electronics get damaged but your flour and cornmeal are no prob. :-) Ziploc bags FTW I guess.

**Comment by sulyi** [comment]
Some aspect of this was discussed in #45954.

**Comment by NetSysFire** [comment]
Yeah. Looks like this is essentially a duplicate. Closing in favor of #45954.
