### ISSUE TITLE
Air Filtration System CBM does not block Hazy Cloud debuffs

### ISSUE THREAD

**Issue by alXDraghiciu** [CleverRaven/Cataclysm-DDA#55504]
### Describe the bug

The Air Filtration System CBM blocks smoke and gases but not Hazy Cloud gas. You still get the poisoned debuff when walking inside a Hazy Cloud.

### Steps to reproduce

1. Install Air Filtration System CBM.
2. Walk into a Hazy Cloud field.
3. You will get the prompt: Really step into Hazy Cloud? (Doesn't happen for other gases)
4. You will get Poisoned.

### Expected behavior

Have no penalty for stepping in any gases.

### Versions and configuration

-Game Version: 6149a27 (tiles)

**Comment by PlutusPleion** [comment]
Not sure if this is related but it seems there's only checks for intensity 2,3, and everything else. I think initially it was intended to be be only intensity 1->3 but hazy cloud is intensity 3 while other clouds are intensity 5 which could be why the other clouds aren't giving that message.

```
if( cur_field_type == fd_nuke_gas ) {
            if( !z.has_flag( MF_NO_BREATHE ) ) {
                if( cur.get_field_intensity() == 3 ) {
                    z.moves -= rng( 60, 120 );
                    dam += rng( 30, 50 );
                } else if( cur.get_field_intensity() == 2 ) {
                    z.moves -= rng( 20, 50 );
                    dam += rng( 10, 25 );
                } else {
                    z.moves -= rng( 0, 15 );
                    dam += rng( 0, 12 );
                }
```
```
 {
        "name": "toxic gas",
        "color": "light_green",
        "transparent": false,
        "translucency": 10,
        "effects": [
          {
            "effect_id": "poison",
            "body_part": "mouth",
            "intensity": 5,
```

**Comment by a-chancey** [comment]
I always assumed it was "attempting" but couldn't handle anything more than smoke, like a filter mask vs a gas mask/PBA

**Comment by LeahLuong** [comment]
Yeah, the keywords here are "filter" & "attempt". Filter mask does not protect you from toxic gas & attempt ≠ succeeds. I believe having some environmental protection cuts the severity of the poisoning.

This seems to be working as intended & issue should prob be closed.

**Comment by alXDraghiciu** [comment]
Well then are there any other gases that aren't covered by the AF CBM(I haven't encountered any).

Wouldn't that mean that from a gameplay standpoint, you'd have to carry around a gas mask just for Toxic Gas' sake since the other gases are negated? That's just inconsistent with the rest of the CBM's that instantly protect you from a threat (like the ones that protect you from electricity or fall damage if they still are in the game).

**Comment by a-chancey** [comment]
I’ll have to test if teargas or relaxation gas bypass the CBM,  I haven’t run into them in game while I’ve had it.

**Comment by LeahLuong** [comment]
Blood Filter CBM can clear the poisoned effect seemingly no matter how severe. My char stopped worrying about carrying a mask once they could simply activate the CBM after stepping out of the cloud.

Otherwise, yes, bloated Z's are some of the most dangerous you'll encounter. Their explosion draws the attention of others & the debuff for stats loss lasts a few minutes. The poison dmg stacks can last for days if you get a bad exposure & the only counterplay w/out a Blood Filter seems to be keeping your head as bandaged & disinfected as possible while sleeping as much as you can; a strong healing modifier + the multiplier for being asleep can barely offset the DOT effect. You still might die after an agonizingly long time. Cough syrup & sleeping pills can really help here.

**Comment by alXDraghiciu** [comment]
> 

Oh I forgot Blood Filter was even a thing. Well yes then it makes more sense for it to counter poison.
