### ISSUE TITLE
Corn in silos rots too quickly

### ISSUE THREAD

**Issue by hexagonrecursion** [CleverRaven/Cataclysm-DDA#55540]
### Describe the bug

Corn in silos is currently has a shelf life of 5 days.

### Steps to reproduce

1. Start a new game
2. Check that silos are full
3. Debug time forward
4. The silos are now empty

### Expected behavior

Silos are for long term storage, no?

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: 728eb52 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda]
]

**Comment by Mikenyes** [comment]
The issue is larger than "corn should rot slower", if I may chime in.  Food spoilage times are not based on a comprehensive formula, and not all conditions are accurately represented.  In a silo, corn lasts months if not a year, primarily because multiple sources of spoilage (moisture, oxygen, light, and accessibility to vermin) are reduced.  Currently we only model based on temperature, which is one of the factors not reduced by a silo - the interior of many silos are substantially warmer than the surrounding area, in fact.

**Comment by oosyrag** [comment]
My understanding is that silos are for long term storage of _silage_, not human edible corn.

(Normal) Corn stored in a (normal) silo will rot as fast as corn stored anywhere outside of a fridge.

**Comment by LeahLuong** [comment]
BREAKING: New England farmers, in the the lead-up to the Cataclysm, replaced all their silage w/ nearly-rotten corn cobs. Madmen!

**Comment by oosyrag** [comment]
Did some more reading: A granery, or a grain bin or grain silo, would store tons and tons of processed dried grains, so technically a silo could be interpreted as a grain silo. Apparently they do also store whole dried cobs too. I don't think these are normally found on farms, more likely a processing plant.

So maybe add a dried corn item that lasts for seasons and fill the silo with that instead. Would feed a survivor for literal years though. Might trivialize food as a gameplay mechanic.

**Comment by Inglonias** [comment]
I mean, if that's what would be in the silos. that's what would be in the silos. Food is already plentiful even without that.

**Comment by Croisis** [comment]
Isn't the whole thing caused by incorrect assumptions about the corn types?
I mean I'm not a farmer myself and I have no idea about the New England so feel free to correct me if I'm wrong but it seems to me that there is one layer of misrepresented generalization when it comes to corn that causes this.

Namely that the corn you would find in silos would be of the "dent" type (also known as "field corn"), stored as dried kernels and having a shelf life of potentially years. This type is not really edible raw but is used for ethanol production, animal feed and processed foods (cornmeal etc).

On the other hand the current state of things assume it is "sweet" corn type, which is harvested before it dries up, as whole cobs, is highly perishable and requires prompt cooling once harvested so there is no way it would be stored en masse in any kind of bin outside of a processing plant.

So my two cents would be to have the currently existing corn cobs (id "corn") spawning in the silos replaced with dehydrated corn kernels (id "dry_corn"), which IMHO represents what would actually be stored there IRL.

The question of what is an appropriate quantity of it is another beast though as realistically the dent corn in silos should be found in ridiculous quantities (for CDDA usecase), not just "measly" ~300-350 items but we are talking about 50-1700 metric tons of capacity per silo depending on size (15' - 48' diameter bins) kind of ridiculous. 
The bins we have now with ~10m diameter could hold 400-900 m3 (350-750 tons) each depending on their height.

Ofc you wouldn't always find it full but even a fraction of that would still last one survivor for decades unless flooded or infested or something of that sort which I'm not sure is the kind of realism that is really desired from the balance standpoint.

Ideas?
