### ISSUE TITLE
Fake Fior Feints??

### ISSUE THREAD

**Issue by LeahLuong** [CleverRaven/Cataclysm-DDA#55611]
### Describe the bug

While using Fior di Battaglia & wielding a Lucerne hammer w/ reach attacks, high round strikes don't seem to be granting free miss recoveries.

Here's my message log from a recent battle:

![Screenshot_20220222-194305](https://user-images.githubusercontent.com/91638992/155272794-f0491f97-6a51-4a8d-909a-bcd16704da30.png)

A few turns later (the save message from before appears here):

![Screenshot_20220222-194506](https://user-images.githubusercontent.com/91638992/155272939-c11e9217-d474-41cd-84b7-db338acc1d80.png)

& this 1 shows the hunter leaping & closing the distance in the same turn I made a high round strike:

![Screenshot_20220222-194513](https://user-images.githubusercontent.com/91638992/155273181-37111fb6-b160-432b-a367-ec0090042655.png)

In all cases, I was creating a space of 1 tile before attacking in order to get full damage from the polearm but the Z's were closing that distance & attacking despite getting the technique to proc.

### Steps to reproduce

1. Become a martial artist.
2. Stop. Hammer time.
3. ???
4. PROFIT!

### Expected behavior

Not to brag, I expected the technique to work as advertised, I dare say.

### Versions and configuration

Android 0.F-3 Tiles English vanilla

### Additional context

I haven't used this combo very much so far & will continue to test this but IDK if any other techniques are triggering. My char has mélée lvl 4 so all but Colpo di Grazia are unlocked.

My hunch is that the reach ability of the weapon is somehow interfering. As you can see from the screenshots, the technique is called out but the enemy gets to act before I can take advantage of the free miss recovery high round strikes are supposed to give. I'll have to test this in close range & perhaps w/ other weapons compatible w/ the MA.

**Comment by catdach** [comment]
I think what's happening is that this feint technique only scales down the move cost to %80 of what it would have been if you had hit, so it's not exactly _free_.

The base moves to attack with the Lucerne hammer is 178, %80 of that is about 142. most zombies take _about_ 100 moves for any of their actions, (zombie hunters are quite a bit faster, but we can ignore that for ease of calculation). So if we're in this scenario where we are moving then stabbing, moving, stabbing, repeat; you're move cost when running is around 60, so every time you move + stab/fakestrike takes about 200 moves, which is just enough for the zombie to move and attack you.

**Comment by LeahLuong** [comment]
@catdach Thanks for clearing that up but, if what you say is true, this is still an issue. The description for high round strike should specify it's discounting & not fully eliminating the move cost to feint.

![Screenshot_20220223-160221](https://user-images.githubusercontent.com/91638992/155438625-2b388355-d3bb-44f1-9728-d7d53cda358d.png)

I was testing this w/ a fire axe & getting similar results; the high round strike is not producing free miss recoveries. @ least w/ the axe it was triggering other techniques. I'll go back to the hammer & perhaps open another thread if I can't get other techniques to proc using reach attacks.

**Comment by catdach** [comment]
Absolutely. The implication that it becomes a free move is incredibly misleading. In fact the 20% discount is so minor that it hardly feels like a benefit at all, especially compared to other feints that actually do make misses free.

**Comment by LeahLuong** [comment]
Every survivor auto-learns Brawling which contains an absolutely free feint. The description for it contains the same line found in Fior & likely Niten: free miss recovery. Now that you've pointed it out, I do see the "80% move cost" under high round feint but this is contradicted by the aforementioned line & takes up a small fraction of the screen real estate, comparatively. This issue is further complicated by the entry further up the list, tactical feinting, lacking any move cost. I understand tactical feinting is a buff necessary for the hook & drag technique but this section may have been put together better to give a clearer picture of how these techniques work together to the player.

I'd like to see the buff/debuff techniques grouped & listed together @ the top of every MA info screen; they frequently inform the player of the mode of play conducive to that MA. Additionally, "free miss recovery" isn't really free if there's a move cost associated w/ it & other MA's w/ that tagline actually are free. That line should be removed or amended.

**Comment by a-chancey** [comment]
You're misunderstanding what's going on here. 

The brawling fient is not free. It _only_ provides miss recovery, which, as I stated above, is NOT the same as giving you a "free" miss. 

When you make an attack, you have an attack move cost associated with the weapon (A). If you use a technique, it can apply a percentage multiplier (B, defaults to 100%), and if you miss, a miss penalty (C) that's, as far as I could tell, based on the weapon's weight. This is a number of moves added to the total move cost for swinging. 

So the formula is (A*B)+C if you miss. For Fior and Niten, if a weapon has 140 move speed, a fient would be (140*.80) with no miss penalty, where a brawling fient would be (140*1) with no miss penalty. A technique without a miss recovery technique would be (140*1)+miss penalty.

**Comment by LeahLuong** [comment]
@a-chancey I haven't tried this since 0.D but I think you're wrong about Brawling. I'll have to test this again for my current version but I used to get 3 or more feints in a row w/out enemy action using Brawling. catdach prob has a similar experience w/ this MA or another.

**Comment by a-chancey** [comment]
Then that's a bug related to brawling. 

There are no free misses. You swung. Even a fake strike takes time. There is only exemption to the miss penalty. I was referencing the melee code last night when I explained this, though you're welcome to show me where I misread it. [Here's the relevant block of code that handles missing and miss recovery.](https://github.com/CleverRaven/Cataclysm-DDA/blob/a139c2e8c951359de3c6f8f570e0caf55393894a/src/melee.cpp#L645)

In fact, I even just looked it back up to confirm. [Here's the formula for stumbling so you can do the math yourself if you'd like, or put in breakpoints to debug.](https://github.com/CleverRaven/Cataclysm-DDA/blob/a139c2e8c951359de3c6f8f570e0caf55393894a/src/melee.cpp#L974) It's based on character strength and the weight and volume of the weapon. Higher strength can prevent stumbling with heavy weapons. 

I'm looking at [techniques.json](https://github.com/CleverRaven/Cataclysm-DDA/blob/a139c2e8c951359de3c6f8f570e0caf55393894a/data/json/techniques.json) right now as well. There are 16 techniques that provide miss recovery - which again, only negates the miss penalty. 

[Niten](https://github.com/CleverRaven/Cataclysm-DDA/blob/a139c2e8c951359de3c6f8f570e0caf55393894a/data/json/techniques.json#L1307), [Bojutsu](https://github.com/CleverRaven/Cataclysm-DDA/blob/a139c2e8c951359de3c6f8f570e0caf55393894a/data/json/techniques.json#L314) and [Fior](https://github.com/CleverRaven/Cataclysm-DDA/blob/a139c2e8c951359de3c6f8f570e0caf55393894a/data/json/techniques.json#L822) are the only three martial arts which have a miss recovery technique which also has a move cost factor, it's .8 for each of them. 

Everything other miss recovery runs at 100% move cost. 

But again, maybe I'm just reading the code entirely wrong. Let me know what you find.

**Comment by catdach** [comment]
Ok, so after reviewing the code and doing some testing I think I've figured out a few things. So weapons have a base move cost to attack which is then modified by various things like the player's current speed, melee skill, hand encumbrance, etc. after those modifications call this value `move_cost`. 
-When you hit an attack it costs `move_cost` number of moves. 
If you miss there is a value called `stumble` that [is added to `move_cost`, ](https://github.com/CleverRaven/Cataclysm-DDA/blob/a139c2e8c951359de3c6f8f570e0caf55393894a/src/melee.cpp#L687)
-so it then costs (`move_cost` + `stumble`) number moves
[If you miss but have a mi recovery technique](https://github.com/CleverRaven/Cataclysm-DDA/blob/a139c2e8c951359de3c6f8f570e0caf55393894a/src/melee.cpp#L688) , the [_total_ is divided by 2](https://github.com/CleverRaven/Cataclysm-DDA/blob/a139c2e8c951359de3c6f8f570e0caf55393894a/src/melee.cpp#L689)
-so it then costs ((`move_cost` + `stumble`)/2) number moves. 

To make sure this is accurate I went into the game with a fairly controlled testing environment. basically I spawned in a fresh character, set my melee skill to 4 (that's how high it needs to be for the Bojutsu feint), spawned in a quarterstaff, and wrote down how many moves it took to to swing at child zombies(which I spawned in and fought until I could get a miss). A quarter staff also has quick strike, which hits for less damage but costs half as many moves as a regular hit (just to give an extra point of comparison).
my results were a follows:
    -no style:
        -quick strike: 46 moves, -normal hit: 93 moves, -miss: 119 moves
    -brawling:
        -quick strike: 46 moves, -normal hit: 93 moves, -miss(feint): 59 moves
    -bojutsu:
        -quick strike: 46 moves, -normal hit: 93 moves, -miss(feint): 59 moves

59 is half of 119(rounded down), so brawling is working as expected, but The scaling of 0.8 from bojutsu doesn't seem to have any affect at all. just for kicks I went in to the code for my game and set the scaling for the technique to 0.1, and got the same result. It also doesn't seem to be referenced anywhere inside the [code block that handles a miss](https://github.com/CleverRaven/Cataclysm-DDA/blob/a139c2e8c951359de3c6f8f570e0caf55393894a/src/melee.cpp#L645) nor the code that [generates the `stumble` value](https://github.com/CleverRaven/Cataclysm-DDA/blob/a139c2e8c951359de3c6f8f570e0caf55393894a/src/melee.cpp#L974)

I'm personally fine with miss recoveries working this way **but**:
A: The scaling factors in [Niten](https://github.com/CleverRaven/Cataclysm-DDA/blob/a139c2e8c951359de3c6f8f570e0caf55393894a/data/json/techniques.json#L1307), [Bojutsu](https://github.com/CleverRaven/Cataclysm-DDA/blob/a139c2e8c951359de3c6f8f570e0caf55393894a/data/json/techniques.json#L314) and [Fior](https://github.com/CleverRaven/Cataclysm-DDA/blob/a139c2e8c951359de3c6f8f570e0caf55393894a/data/json/techniques.json#L822) are bugged and don't do anything.
B: This **needs** to be communicated much better to the player than it is currently. 
I had always thought that feints made missing an attack cost 0 moves. because, well, _that's what the game says._ It certainly _feels_ like it takes 0 moves when you're getting to attack an twice as many times at it attacks you. the description of `"this provides a free recovery from a miss"` is kinda terrible (if you were a very observant player that noticed that misses take slightly more moves than when you hit, you _could_ interpret that as meaning "misses will now become the same move cost as hits" _but apparently **that isn't accurate either**_).
I'd suggest changing the description to something like `"makes misses take half as much time"`

**Comment by LeahLuong** [comment]
Good on both of you for the code dives. I did a little testing by punching some Z's to death w/ Brawling & wasn't able to replicate what I remember from 0.D. The best I got was 2 feints in a row but it became obvious pretty quickly feinting was causing time to pass.

Should we @ the author(s) of the respective MA's to let them know about the bugs or simply hope some1 else comes along w/ a fix??

**Comment by a-chancey** [comment]
I think your normal hit value of 93 moves is wrong, the base move count for the quarterstaff is 114 moves. 93 would be the rounded 80% value that knee strike (a block counter) and feint are rated at. 

I just tested it with a Lucerne hammer and Fior di Battaglia. Melee 5, 8s in stats, melee training background to get the martial art. Built from source, with breakpoints in the melee code around that block. My results were different, and it appears Fior works. I'll test Bojutsu tomorrow when I get a chance, but things make a lot more sense after stepping through it. I used a zombie child as a target. 

Swing and hit: 178 moves. 

Miss (no style): 238 moves 

Miss (feint): 101 moves. Calculation below. 

it turns out high round feint's 80% move cost multiplier has already happened prior to this block of code being hit. The move_cost variable on a hit without a modifying technique is 178, but was only 142 on the miss. 

Then the stumble penalty of 64 was added - which was capped at 60 - bringing us to 202.

This was then halved to 101. 

So after going through everything line by line, what's listed in the technique for Fior is accurate, but it's worded confusingly, especially if you're not following along with breakpoints. Giving percentages to the player is actually adding to the confusion here. 

As an aside, avoiding the stumble penalty, is actually covered by Deft, which does not provide miss_recovery as well from what I can tell. 

Maybe the wording for Fior should be changed to something like "reduces base move cost on a miss by 80%. Further reduces total move cost of miss after any applicable penalties by 50%". "Free recovery" is an odd choice of words. Yes, it is "free" as in "costs nothing to you to gain 50% move cost recovery when you miss".

I highly suspect that the calculation is working for Bojutsu as well based on the numbers you had, I'm just going to the gym before work so I need to get some sleep. I ran the numbers on a calculator and they're *really* close to what you have, I just want to confirm in game. I'll report back.

**Comment by a-chancey** [comment]
Ok nevermind. I went in and checked the attack speed calculations with my fior character and their lucerne hammer.

I'm getting 146 as my move cost on both a hit and a miss at full stamina, largely modified by melee skill. There's a place for a move cost multiplier, but at least for Fior, it returned at 1.0.

I don't see anywhere that the 80% move cost on the feint techniques is triggering, just the 50% post stumble penalty reduction from miss_recovery. So yeah, it appears that at least the feint for Fior Di Battaglia is not using the 80% move speed multiplier.

I don't know, however, if this was an intentional change as miss recovery handles halving the modified move cost for all techniques where it applies - and now i'm not sure where the intended 80% move cost factor even should come into play with how complex the attack speed calculation is.

**Comment by catdach** [comment]
> I don't know, however, if this was an intentional change as miss recovery handles halving the modified move cost for all techniques where it applies - and now I'm not sure where the intended 80% move cost factor even should come into play with how complex the attack speed calculation is.

Yeah I have no idea what's intended to happen with this nebulous 80% modifier at this point.

> Should we @ the author(s) of the respective MA's to let them know about the bugs or simply hope some1 else comes along w/ a fix??

It might be worth a new IR that clearly lays out what's going on so they don't have go digging through our comment string, regardless it's probably worth mentioning it to them. Just waiting for someone else to come along and fix it seems like a non-solution. 

I might make a PR to at least change the wording to replace the term "free recovery" to something more accurate.

**Comment by LeahLuong** [comment]
KA101 introduced Niten Ichi-Ryu in 2014. DemAvalon introduced Fior di Battaglia in 2019. SantosValourion introduced Bōjutsu in the middle of last year, 2021. None of these contributors have been active recently & it appears Dem & Santos went inactive shortly after their contributions. KA was so far back I wasn't able to find their last activity.

It seems NIR has been in the game longest & quite stably so & the following contributors simply templated their feints from there. It's possible the only person who has a clear understanding of how exactly these feints should work is long gone. I didn't bother w/ digging into the history of how feints in general have evolved during the game's history.

I'll be happy to see the wording changes for these MA's. @ least the info screen won't be feeding players bad info. Beyond that, I'm not going to pursue this issue further. I imagine the MA is _supposed_ to help w/ more efficient feints but I've no insight to bring on that front.

Thanks for looking into the code & putting in the time, gents.

**Comment by Maleclypse** [comment]
Should this be closed by the merged fix?

**Comment by LeahLuong** [comment]
@Maleclypse @catdach Yes, I'll close it now. It appears it was linked by cat in the PR so I'm not sure why it wasn't automatic.
