### ISSUE TITLE
Hitting hallucinated NPCs don't disappear after damage\can be used as "free" training (also hallucinatios throw real projectiles).

### ISSUE THREAD

**Issue by Techmind** [CleverRaven/Cataclysm-DDA#55638]
### Describe the bug

Attacking hallucinations allows you to skill-up. 
Probably a 'free' way to get good at melee\dodging\throwing\etc.

Not realistic, but probably not that critical.
I don't think that hallucinating a fight with kung-fu master would make me a great fighter.

### Steps to reproduce

1.Start hallucinating.
2.Hallucinate a NPC.
3.Attack NPCs
4.If NPC has throwing knife you actually get real damage from illusory knife and a bleeding)
5. Also shots from hallucination NPC's damage armor.
6.Also destroying npc's clothing will drop real items too.

Get free levels in melee & weapons skill.

### Expected behavior

NPC should disappear after 1st hit/hitting you too(as hallucinated monsters).

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: ea101df [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Arcana and Magic Items [Arcana],
    Blaze Industries [blazeindustries],
    sees-player icon, HitButton_iso [sees_player_hitbutton]
]

**Comment by Techmind** [comment]
[ArcanaMagiclysm_copy2.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8132550/ArcanaMagiclysm_copy2.zip)
See message log, illsuion's knife hit me for 12 dmg.

**Comment by LeahLuong** [comment]
#54307 mentions the fact thrown items from hallucinations can do real damage. That PR also fixed getting training from them although it didn't address this indirect method of gaining skills.

It seems hallucinations will always be something that lags slightly behind the rest of the game's development & generates bugs until some1 steps up to permanently dedicate themselves to chasing this sort of stuff down. dseguin has done a lot of work in this area but I'm unsure they've fully committed to becoming the "hallucinations" person. It's tricky because hallucinations demand deep knowledge of many of the game's systems but it's an area of the game underappreciated by the majority of players.
