### ISSUE TITLE
Real Survivors Wear Their Underwear Out (Click Now!)

### ISSUE THREAD

**Issue by LeahLuong** [CleverRaven/Cataclysm-DDA#55686]
### Describe the bug

Followers who join my faction always need their clothing reordered because their choice of layering complies w/ Real Survivor™ standards. I imagine this issue affects all NPC's whether they're in my faction or not.

### Steps to reproduce

1. Meet Real Survivors™.
2. Look @ them.
3. ???
4. PROFIT!

### Expected behavior

I expected people who survived the apocalypse to have the sense to wear their underwear inside their other clothes. They must know something I don't. Please let me know.

### Versions and configuration

Android 0.F-3 Tiles English vanilla

### Additional context

#32420 corrected this issue for some set NPC's who aren't Real Survivors™. Little did we know, then, how deep the roots of this problem truly run.

**Comment by haveric** [comment]
Do all of your issues need to be this clickbaity sounding? I know I certainly would appreciate them being more succinct so that the issues can be more easily deciphered and solved.

**Comment by robotic-gamer** [comment]
a related issue is that wearing underwear serves no point but to create clutter so going commando makes the most sense.

**Comment by orbayyazanlar** [comment]
Was an issue with F2 as well, but not E as far as I remember.

**Comment by robotic-gamer** [comment]
The problem with clickbait is it distorts/disrupts the logical processing of issues. Essentially it causes via deception to get people to over pay attention to the clickbaited issue and by extension under pay attention to every other issue. This is bad because resources (peoples time) to develop cdda is finite and by using clickbait you are making the allotment of resources more difficult and less optimal then it could be. That being said errors in judgment happens. perhaps you just keep the clickbaityness out of the title so it doesn't get in the way of sorting through issues while still allowing humor in the actual issue?

**Comment by haveric** [comment]
> That being said errors in judgment happens. perhaps you just keep the clickbaityness out of the title so it doesn't get in the way of sorting through issues while still allowing humor in the actual issue?

My main concern is that some/most of the issues are being taken on by people who have not worked on the codebase a lot. It may seem lighthearted to joke about "Real Survivors™", but how would someone new know if that's an actual thing or a joke when we have things like TrueFoodperson, especially when it's in the reproduction steps as how to replicate this issue?

I guess what I'm asking is if you can at least keep the title, describe the bug and steps to reproduce slightly more serious going forward as to not confuse people and help us parse your issues quicker? I understand you're just trying to have fun with it and you can still have some fun with these, but if you could tone it back a bit, that would be extremely helpful.
