### ISSUE TITLE
Crushable Container Conundrum

### ISSUE THREAD

**Issue by LeahLuong** [CleverRaven/Cataclysm-DDA#55765]
### Is your feature request related to a problem? Please describe.

I ran over a bag of Skittles™ in my 7-ton humvee. Somehow, the bag was crushed into non-existence. The Skittles™ popped out completely intact -- all of them -- & I proceeded to crush them w/ my teeth. Yummy!

### Solution you would like.

Non-rigid containers should pass some portion of their dmg on to their contents. This goes for things like plastic bags & pocket-containing clothing made from soft materials. In the above example, the bag prob would have outlived the pulverization of the Skittles™ IRL, equating to a greater portion of the dmg being passed on to the contents due to the container's flexibility & shape.

Rigid containers can also have this dmg-passing capability but should 1st incur some dmg themselves before passing any on. The greater their dmg, the more they become like a non-rigid container.

Whenever a container sustains dmg, there should be a chance for items to fall out. This can happen due to being run over by a vehicle or from collateral dmg during combat. Item size relative to container size & amount of container dmg should govern the probability of falling out. This might mean Skittles™ falling out of bags when they're run over or Skittles™ falling out of your designated ballistic vest pocket when it's torn. This will encourage players to wear a 2nd ballistic vest over their 1st 1 to avoid the loss of Skittles™.

Exceptions to these rules should likely be made for containers containing charges, @ least @ 1st. I'm thinking of batteries, mags, & liquid containers but these could be addressed in a later pass. What happens to software that falls out of USB's??

### Describe alternatives you have considered.

Oh, p'shaw!

### Additional context

Here's some suggested staging for development:

1. Dmg-passing for non-rigid containers.
2. Dmg-passing for rigid containers based on the above.
3. Dmg-passing for pocket-containing clothing based on all above.
4. Dmg-passing for nested containers.
5. Dmg dealt to containers holding charges having various effects, e.g., batteries losing max charge, mags malfunctioning/destroying ammo, bottles leaking liquid, USB's shifting phase polarity of the interface grid for manual control & entering a new paradigm of functionality.

**Comment by catdach** [comment]
Overall I think I like this idea, but it needs to be implemented carefully. Here are some things I'd like to tack on:

Damage to a container should not _automatically_ damage _all_ items in it.
A small tear in my backpack shouldn't shatter every glass vial of mutagen I was carrying around. Perhaps give each item a percentage chance to be hit, based on its volume compared to the total volume of the container. this chance could also increase based on the amount of damage to the container. So a small tear in my survivor harness would usually only hit my gun, not _usually_ damage my extra 30 round mags, and _almost_ never hit my spare 5 round ammo clips. But if my harness gets run over by a car, then pretty much everything is gonna be destroyed. I like having it tied to the volume of the container to deal with large items with relatively small pockets and large-rigid containers holding very small items.

I also like the idea of somehow limiting the volume of items that can be damaged. So if I'm carrying multiple large item like say, 3 metal frames, its more likely for only one to get hit than for all 3, even though they each would have a pretty high chance of getting hit individually. Also if I'm carrying a lot of small items like, 2000 nails, a lot of them could get hit, but it would be extremely unlikely that _all_ of them would be hit. That one sounds pretty difficult to implement though, so I think of it as more of a bonus.

Smaller items should have a higher chance of falling out than larger items. Pretty self explanatory, large things can't fall through small holes. This could probably use the inverse of an items probability to be hit. Could probably use similar scaling probability as well. Larger holes mean larger items are more likely to fall out.

Damage to items should be reduced based on the protection values of the container (where possible). So stuff in a Kevlar backpack doesn't get as banged up as items in a plastic bag or regular backpack. I'm also somewhat concerned about things that serve both the roles of armor _and_ storage, like the scavenger suit and survivor cargo-pants. There are also containers that don't have protection values because they aren't meant to be worn, maybe use the base protection values of their respective materials or something?

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
