### ISSUE TITLE
Weapons damaged from using attached bayonet

### ISSUE THREAD

**Issue by ymber** [CleverRaven/Cataclysm-DDA#55798]
### Describe the bug

My M4 took damage from stabbing a zombie with the bayonet I attached. No corrosive zombies or anything else that would make the behavior appropriate were involved.

### Steps to reproduce

1. Debug in a rifle and combat knife.
2. Attach knife as bayonet.
3. Stab monsters until rifle is damaged from use in melee.

### Expected behavior

Rifles should not be damaged from using an attached bayonet as it was designed for.

### Versions and configuration

Experimental at e0ad823f1f47a78211a509d50932720ef0112f51. No relevant mods.

**Comment by oosyrag** [comment]
Weapon durability and damage is not a particularly granular system. If you whack something with anything, it has the potential to get damaged. I can imagine it as chunks of viscera gumming up the barrel or something.

Otherwise, should guns have the potential to get damaged at all? Would pistol whipping something cause damage to a pistol? Or using a shotgun like a bat?

**Comment by Kamejeir** [comment]
> Or using a shotgun like a bat?

inb4 we a baseball bat hollowed-out to fit a shotgun to become make the latter get the "sturdy" flag and the former dual-purpose

**Comment by ymber** [comment]
Yeah granularity in the durability system is the root of the problem here. You can't use a gun as a bat for long before it doesn't work reliable anymore but you can use a bayonet on it indefinitely without any nontrivial damage to the gun. The weapon durability system doesn't distinguish between these cases.

**Comment by Kamejeir** [comment]
Assuming two conditions here:
1. Every time a weapon melee is made, it is always the bayonet being used.
2. No guns have any block stat, and is therefore never used to block attacks.

then you, ymber, saying:
> but you can use a bayonet on it indefinitely without any nontrivial damage to the gun

Would that not mean that adding the UNBREAKABLE_MELEE flag to any gun along with any bayonet addition (& reverse for removal) be a totally apt solution?

**Comment by bombasticSlacks** [comment]
The bayonet shouldn't take less damage than a normal knife would. This would need C++ code to handle tracking damage on the gunmod itself. There's probably a clever place to hook into durability calcs that would solve it easily. 

> inb4 we a baseball bat hollowed-out to fit a shotgun to become make the latter get the "sturdy" flag and the former dual-purpose

This PR is currently in the works from me 🙂

**Comment by oosyrag** [comment]
No, as bombastic mentioned, if a knife can take damage a bayonet can too. Not to mention damage to the attachment between the gun and the knife, and also the possibility of damage to the gun itself from repeated impacts, even if the bayonet is the main point of impact. If a gun can get damaged by using it as a bat, it should be able to get damaged from using it as a spear too. If anything, all guns should perhaps get the durable melee flag.

**Comment by Kamejeir** [comment]
~~Aye aye, a C++ fix it is then. Into P5 it goes!~~

However, oosyrag,
What I want mention is what bomb said:
> You can't use a gun as a bat for long before it doesn't work reliably anymore

and you say:
> If anything, all guns should perhaps get the durable melee flag.

I wish to politely convey that this would conflict with what I quoted bomb saying, that which I believe to be a pretty agreeable fact.

But for the sake of continuing to develop on the idea, I suggest that whenever the special damage tracking gets implemented, damage acquired from swinging it would make guns need much more maintenance (gaining shooting-related faults) faster.

**Comment by Kamejeir** [comment]
Tho bomb, I'm looking forward to how that "slug slugger"... or whatever you intended to name your shotgun+baseball bat will turn out!

**Comment by oosyrag** [comment]
I meant that as durable_melee for guns by default would be an easy to implement compromise between OPs expected behavior of unbreakable_melee (with a bayonet equipped) and their current no tag chance of taking damage during melee attacks. 

Guns are fairly simple mechanically, they can take quite a bit of abuse and keep working (besides jamming and cleaning maintenances, which are somewhat unrelated to physical trauma). Short of a bent barrel or a broke trigger/firing mechanism, it should still work.

**Comment by Kamejeir** [comment]
Alright, great. We discovered how one would close specifically this issue now: Making adding a bayonet give any gun "DURABLE_MELEE", which I assume won't interfere with anything except melee attacks, as I suspect is hardcoded.

In terms of the more general solution for the long term, items will have to be rewritten to the point where different parts of an item are handled with different durabilities, then use that to make the bayonet be responsible for taking the beating when any melee attacks are performed.

Does this sound about right?

**Comment by Kamejeir** [comment]
Well, if someone has the gusto and skill to pick up even the short-term fix, it may be the case that they would instead be inclined to direct their efforts towards the "actual" fix for something like this.

That person is not among the common contributor here, correct? But the needed change seems very clear for that eventual person to understand, so until then I believe this should be given the (P5 - Long Term) label. Unless, of course, any of you two are brave enough to do it, in which case I applaud you.

**Comment by Kamejeir** [comment]
OP's expected behavior is that guns should not be damaged at all when melee attacking, but we're limited by lack of flexibility in the code at this point, as bomb points out:
> This would need C++ code to handle tracking damage on the gunmod itself.

This is how I would summarize the conversation leading us to understand what work needs to be done:
For an appropriate, long-term solution, items will have to be rewritten to the point where different parts of an item are able to be handled for different durabilities, then use that to make the bayonet be responsible for taking the beating when any melee attacks are performed, then at that point doing something akin to giving it "DURABLE_MELEE".

Does this sound about right?

**Comment by Kamejeir** [comment]
Of course, there's what I believe to be the less intrusive solution for anyone less skilled willing to pick up and close this issue:
Making adding the bayonet give any gun the "UNBREAKABLE_MELEE" flag.

**Comment by Kamejeir** [comment]
Well, you do make a fair point, and I suppose I failed to understand your message.
Should this issue be solved with ``DURABLE_MELEE`` to every gun, or should something be done akin to rewriting items like how bomb suggested be necessary, for a no-compromise fix?
> This would need C++ code to handle tracking damage on the gunmod itself.

**Comment by Kamejeir** [comment]
That leads to another question I have, pardon the meta:
Are issues like this one solved by whoever gets a working fix for them first?

**Comment by oosyrag** [comment]
Hmm... I'm getting a bunch of emails with what seems to be a one sided conversation from Kemejeir, but I'm not seeing anything show up here on this GitHub thread. Is that what happens when someone responds by email?

Anyways regarding "Are issues like this one solved by whoever gets a working fix for them first?", the answer would be yes, but does get a final review by project maintainer to be included. Generally anything that can reasonably be backed up with sources when challenged will get merged, but personally I believe it is better to hash out any potential subjective disagreements in discussion first, rather than just doing it and then having it undone by someone else who feels differently in the future. I myself wouldn't bother doing any work without at least a general consensus, so if it's too subjective or controversial, I'll just drop it. Also changes to C++ code is probably scrutinized more closely than changes to JSON.

**Comment by Kamejeir** [comment]
>Hmm... I'm getting a bunch of emails with what seems to be a one sided conversation from Kemejeir, but I'm not seeing anything show up here on this GitHub thread. Is that what happens when someone responds by email?

I was just indecisive over what to say and deleted my messages, doing three attempts before coming to the conclusion that I didn't really have anything to add to the conversation.
But thanks for the answer for the rest of your reply.
