### ISSUE TITLE
Add nausea to butchering

### ISSUE THREAD

**Issue by oosyrag** [CleverRaven/Cataclysm-DDA#55841]
### Is your feature request related to a problem? Please describe.

Butchering/dissection should induce nausea in the uninitiated, more so than a morale penalty.

### Solution you would like.

Butchering causes nausea without certain skills/traits/proficiencies. Some ideas include butchery proficiency, surgery proficiency/health skill, survival skill, psychopath, or some other form desensitization. (E: Cannibal?)

Pulping is still available as the main option for preventing zombie revival. Indirectly somewhat nerfs tainted tallow/lamp oil.

Desensitization (proficiency?) should not be too difficult to obtain, I'm thinking in the order of 1 or 2 days worth of barfing your way through butchering corpses. 

### Describe alternatives you have considered.

Only the squeamish trait induces nausea when butchering. Alternatively, squeamish can't butcher things at all.

### Additional context

At university, the butchery lab in animal sciences courses is notorious for making students drop out (of the lab at least, if not the major), even though they are there specifically to learn about it. Source: Wife, animal science major, unable to complete butchery lab (also squeamish and averse to blood)

I imagine surgery and cadaver work for med students would be similar.

I also imagine "fresh" rotten zombie corpses would be a magnitude more unbearable.

**Comment by LeahLuong** [comment]
Maybe it's something that could be built into #54392. Personally, I prefer the alternative proposal where butchery causes Nausea for Squeamish chars. That trait's frequently taken because its drawback is so easily managed.

That said, there's quite a lot in the post-Cataclysm world that might preemptively harden 1 to the disgust 1 would experience in butchery. Pulping Z's is akin to slaughter not to mention dealing w/ Z's who are decayed, horribly disfigured, or w/ organs hanging out. Giant bugs & corpse-filled pits are also sources of grotequerie.

**Comment by oosyrag** [comment]
I also realized nausea would prevent butchery completely since there isn't partial progress and barfing would interrupt the task, so it would make more sense as a squeamish disadvantage. Point cost could be adjusted. Would it be too large of an impact on gameplay to not be able to butcher?

**Comment by LeahLuong** [comment]
In that case, instead of causing Nausea, butchery might have a flat % chance of causing your char to puke per attempt, scaled to your progress in gaining the proficiency. This would still interrupt the task but you could still make progress toward gaining (partial) immunity to this effect by making more attempts. Having such a system in place would also make it so particularly gnarly butchery tasks could still come w/ a chance to blow chunks, no matter how steeled your char is.

**Comment by Night-Pryanik** [comment]
> Would it be too large of an impact on gameplay to not be able to butcher?

No, it's perfectly fine both from gameplay and plausibility points of views. 
This is a sort of global and non-removable restrictions like inability to operate vehicles for Wayfarer or inability to read for Illiterate. It's something that will somewhat radically change the gameplay, and that's good.

**Comment by Night-Pryanik** [comment]
> butchery might have a flat % chance of causing your char to puke per attempt, scaled to your progress in gaining the proficiency

As with other activities that have a chance to fail, interrupted attempts of butchery most likely will only make players frustrated and add very little to gameplay, in fact this will add nothing more than an another source of grind. Binary "possible / impossible to butcher" is much better for gameplay since it adds different ways to play.

**Comment by Marrim** [comment]
You could instead make the player puke _after_ they finish butchering.

**Comment by PatrikLundell** [comment]
It can also be noted that a squeamish PC unable to perform butchery can still order companions to use butchery zones, and thus do the work for them. This means that butchery becomes unavailable only to players who are both squeamish and refuse to have companions if squeamish makes butchery unavailable to the squeamish. It would also require the code to block squeamish companions from performing such jobs.

However, squeamish characters would not have the companion work around as an option for CBM extraction from dissection until companions could be ordered to perform that task for them. This would, however, have a limited impact as long as CBMs can be acquired through other means (i.e. trade and loot). If some CBMs would be dissection only, the impact would be limited in a technical sense, but the player may still feel cheated unless it was communicated up front that there is a risk of missing out.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
