### ISSUE TITLE
Add snowplows

### ISSUE THREAD

**Issue by oosyrag** [CleverRaven/Cataclysm-DDA#55843]
### Is your feature request related to a problem? Please describe.

NE gets snow on roads. Snowplows are used to remove snow on roads. Snowplows could also be used to remove zombies from roads. Snowplows are not currently in the game.

### Solution you would like.

Add snowplow as a vehicle part. Maybe spawn them in garages or a new map location? Where does the city keep these things in the summer?

**Comment by NetSysFire** [comment]
Snowplows could possibly be spawned in the same depot (that does not exist yet) as the automated street sweepers.

What would be the advantage of using a snowplow instead of e.g a road roller or some rams?

**Comment by oosyrag** [comment]
No particular advantage, just another potentially useful pre-generated vehicle type that wouldn't be out of place and emphasizes the implication that yes, it does get cold enough to snow here in this setting.

**Comment by a-chancey** [comment]
Could they apply angular force on the collision? Hit them and have them fly to the side at a predictable angle, rather than straight back and randomly to a side, since a snow plow would be angled slightly to clear the snow to a specific lane. 

Most of the ones I've seen (even smaller ones for consumer markets) have been mounted with a shock mount, as well, to minimize damage and react to bumps in the road. 

If we can get the angular push to happen with strong force and give it at most 100% damage, maybe 75% (half way between a tied mattress and a quarterpanel). They're not only angled but curved as well, so they kinda scoop and throw rather than smash. Giving it shock absorber qualities would be nice but possibly a bit OP. 

That'll set it aside from a roller drum which does 500% damage as it's supposed to crush everything in its path to smooth the pavement with its massive weight.

**Comment by LeahLuong** [comment]
In addition to municipal sourcing of snowplows, some private entrepreneurs may offer their services. I'm thinking of people who'd hire out their pickup truck w/ snowplow attachment for clearing the driveways of the more rural areas. Those attachments might be available @ big box hardware outlets or maybe even certain car dealerships.

I can imagine the automated street sweepers might've been reconfigured during winter months for snow clearing duty pre-Cataclysm. Perhaps you'd be able to find snowplows or snowblower attachments @ their depots.

**Comment by a-chancey** [comment]
> In addition to municipal sourcing of snowplows, some private entrepreneurs may offer their services. I'm thinking of people who'd hire out their pickup truck w/ snowplow attachment for clearing the driveways of the more rural areas. Those attachments might be available @ big box hardware outlets or maybe even certain car dealerships.

Yep I looked them up at Home Depot. The one I looked at was about $2k, though they seem to be special order. 

Maybe they could spawn at abandoned warehouses in crates?

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
