### ISSUE TITLE
crafting time for metal armor way to short in contrast to carbonized steel armor

### ISSUE THREAD

**Issue by Shadesmar99** [CleverRaven/Cataclysm-DDA#55951]
### Is your feature request related to a problem? Please describe.

the crafting times of metal armor (for example metal arm guards) are way too low to make any sense.

### Solution you would like.

consistent crafting times for metal armor, or phasing out those pieces of equipment

### Describe alternatives you have considered.

i guess i could ignore my need for consistency and realism to conform to the status quo as an alternative solution....

**Comment by Jarewill** [comment]
That is because those armors are made with completely different methods.
Steel armor is forged, meaning it takes a lot of time to melt down the metals and forge it into a proper shape.
While the metal armor is made from metal sheets hammered into shape and held together by strings.
It makes sense for it to take so little time, since you are basically just hammering a sheet of metal and tying it around with a string.

https://github.com/orgs/CleverRaven/projects/1
> Metal: hammered metal, sewn to jacket/sleeves/etc.

In the armor updates project, it states that metal armor is one of the planned tiers, so I don't see why it should be removed.
Updated, yes, but not removed.

I believe @Drew4484 might have more to say to this.

**Comment by LeahLuong** [comment]
Does any1 know why the emote functionality changed recently or what new rules it follows?? I wanted to drop an emote here but the buttons are missing.

**Comment by Shadesmar99** [comment]
> That is because those armors are made with completely different methods. Steel armor is forged, meaning it takes a lot of time to melt down the metals and forge it into a proper shape. While the metal armor is made from metal sheets hammered into shape and held together by strings. It makes sense for it to take so little time, since you are basically just hammering a sheet of metal and tying it around with a string.
> 
> https://github.com/orgs/CleverRaven/projects/1
> 
> > Metal: hammered metal, sewn to jacket/sleeves/etc.
> 
> In the armor updates project, it states that metal armor is one of the planned tiers, so I don't see why it should be removed. Updated, yes, but not removed.
> 
> I believe @Drew4484 might have more to say to this.

There is also a discrepancy in (forged) steel armor and higher tiers like tempered steel armor. Steel armor takes about 1 day, tempered 2 weeks. Tempered involves chainmail, but those are already prepared chainmail sheets and the higher quality carbonized steel is also prepared beforehand. We already talked about this issue in discord, i just wanted to add this as an issue here, so that it wont get forgotten if Drew gets a heart attack from working too much or something

**Comment by Jarewill** [comment]
I don't know what you are talking about, as the plate armor I see (mild/medium/high carbon steel) takes 5 weeks and 4 days with all proficiencies.
Case hardened plate armor takes 6 weeks and 1 day, and tempered plate armor takes 6 weeks and 3 days.

The latter two make sense to take more time, as they are made using different methods.
Searching for how long tempering steel takes, I get this result:
> Tempering is usually performed at temperatures as high as 950 °C (1,740 °F) for up to 20 hours. The tempering is followed by slow-cooling through the lower critical temperature, over a period that may last from 50 to over 100 hours.

Of course, I am not experienced in metalworking to actually be able to tell if that's correct or not.
Though I do agree that the craft times are really long, but I guess that makes sense since it's very powerful and will last you a long time.
Also the recipes don't take prepared chainmail sheets, or any form of pre-made chainmail armor.
