### ISSUE TITLE
Applying an adhesive bandage shouldn't REDUCE the quality of an existing high quality bandaging

### ISSUE THREAD

**Issue by KurzedMetal** [CleverRaven/Cataclysm-DDA#56027]
### Is your feature request related to a problem? Please describe.

Imagine you got a big hit on a limb, you apply a normal bandage with good quality on the wound to start healing.

Then another zombie comes barely scratch you in the same limb, maybe it damage the bandage a bit, and did another small bleeding cut. I want to stop the bleeding using an adhesive bandage (not just waste another high quality bandage) but since the adhesive one has very poor bandage quality and wants to REPLACE the previous good quality bandaging.

I think something similar can be reproduced with disinfecting items too.

### Solution you would like.

IMO, when applying multiple bandages (actually healing items in general) to a limb, the highest quality effect of each benefit (bandaging, bleeding stopping, disinfecting) should prevail, not just try to replace previous effect no matter what.

If the intention is simulating removing an old bandage, maybe we need a new action for that, but I don't see why anyone would want to remove a good state bandage.

**Comment by DoctorGoat** [comment]
I have, in the past, used band-aids/other cheap bandages to supplement the hold that something llke a hydrocolloid bandage has when it's in an awkward spot. I haven't ever needed to use adhesive bandages irl to help with the hold on a long gauze bandage, but I have used Coban.

It's reusable and supplements gauze/cotton but requires practice to get good at using. I'm not sure how the reusability would function ingame. It could be skipped and still be a significant buff to bandages before you have perfect bandage quality.  

It'd require a check for current bandaging and then be a multiplier/shield from a hit or two since it's tough as heck, I think.

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
