### ISSUE TITLE
Wooden clogs are more protective than combat boots

### ISSUE THREAD

**Issue by remd** [CleverRaven/Cataclysm-DDA#56103]
### Is your feature request related to a problem? Please describe.

Wooden clogs are more protective than made-for-combat Kevlar-reinforced boots for nearly all damage types:

```
"id": "clogs",
"name": { "str": "pair of wooden clogs", "str_pl": "pairs of wooden clogs" },
...
"material": [ "wood" ],
"warmth": 5,
"material_thickness": 4,
"environmental_protection": 1,
"flags": [ "VARSIZE", "WATERPROOF" ],
"armor": [ { "encumbrance": 20, "coverage": 85, "covers": [ "foot_l", "foot_r" ] } ]
```

```
"id": "boots_combat",
"name": { "str": "pair of combat boots", "str_pl": "pairs of combat boots" },
...
"material": [ "kevlar", "leather", "rubber" ],
"warmth": 25,
"material_thickness": 2.5,
"environmental_protection": 2,
"flags": [ "VARSIZE", "WATERPROOF", "STURDY" ],
"armor": [ { "encumbrance": 25, "coverage": 100, "covers": [ "foot_l", "foot_r" ] } ]
```

```
 (current)            Bash     Cut   Balli    Acid    Fire    Elec    Chip
wooden clogs            12       8       8      16       4       8      40
combat boots          5.83    5.83    6.67   11.67    4.17   12.50   20.83
```

### Solution you would like.

I think wooden clogs should have their `material_thickness` reduced:
```
                      Bash     Cut   Balli    Acid    Fire    Elec    Chip
thickness 1              3       2       2       4       1       2      10
thickness 1.25        3.75     2.5     2.5       5    1.25     2.5    12.5
thickness 1.5          4.5       3       3       6     1.5       3      15
```

I suggest a new `material_thickness` of `1`.

I know clogs have a reputation for being very thick and bulky (though I'm not sure how true it is) so perhaps increasing the Feet Encumbrance (currently `10`) is warranted to convey that clogs are still clunky.

### Describe alternatives you have considered.

Clogs don't seem like a good candidate for mixing material types for balance purposes since they are traditionally made entirely of wood. The choice of a single material makes sense and should probably be preserved.

I'm not sure if there is a way to apply flat armor reductions or increases post-calculation via the JSON definition; if there is then the clogs could have their armor reduced without reducing the `material_thickness`.

### Additional context

In-game 'compare':
![clogs-vs-boots](https://user-images.githubusercontent.com/1325809/158238963-12c46566-9a54-4534-ab02-f344983533df.png)

**Comment by remd** [comment]
I'd be happy to make this change but I'm not sure if there is a more appropriate way of balancing this without affecting the `material_thickness` of clogs.

**Comment by PatrikLundell** [comment]
The clogs I've used as a kid consisted of a thick wooden bottom part with leather stapled to the sides of the wood to form a cover for the front of the foot (up to the leg, but nothing covering the heel) and then rubber soles at the bottom of the wooden part. There are also steel toed versions.

While the leather at the top is reasonably thick, the bulk is the wooden part below the foot, which could probably take a lot of abuse before shattering (the thickness is probably similar to two planks on top of each other). It can be noted that attackers would probably hit the top of the clogs rather than the bottom.

I don't think clogs can be modeled properly with the current system, as it would require specifying materials differently between the bottom of the shoe, the front of the foot, and the heel of the foot.

**Comment by avianArsonist** [comment]
Combat boots also seem (as someone who's never worn combat boots), weirdly encumbering for their purpose. They're harder to move in than almost any other commonly lootable footwear, with turnout boots and rubber boots being the only exceptions that come to mind, which doesn't really make sense to me.

**Comment by PatrikLundell** [comment]
4 mm isn't anywhere near the thickness of the wood in clogs that have wood in their soles only. 1-4 cm is more like it, probably down to something like ½ cm under the valve of the foot. However, a realistic armor value is probably more important to a realistic material volume.

You can search the net for e.g. "clogs shoes" to find some images. The all wooden ones (traditional Dutch) probably have some rather decent protection values, so you'd probably have to specify which type you're designing.

**Comment by bananapheasant** [comment]
I was talking about wooden clogs specifically. To be fair i have never tried any. Sure, regular clogs are quite comfortable.

**Comment by schoolcf** [comment]
is kevlar and leather better at stopping a sword or a hammer or a bullet than a block of wood?
probably has more bash protection and maybe cut protection but probably not bullet protection
drop weight on foot w/ clog -> unless the clog breaks, nothing
drop weight on foot w/ boot -> pain

**Comment by bombasticSlacks** [comment]
So to necro this slightly, Sublocations do support different materials and thicknesses.

The foot consists of: "foot_arch_r", "foot_toes_r", "foot_ankle_r", "foot_heel_r"

Also there are like 4 armor items that are made of wood including clogs and 2xarm guards/leg guards. A 2x4 is 50mm thick so woods defense values should probably be *seriously* reduced and then the material thickness be correctly mapped.

**Comment by bouchacha** [comment]
The above discussion seems to confuse 100% wooden clogs (the kind you'd get from just carving):
![image](https://user-images.githubusercontent.com/19356629/179375461-e15431e3-52bd-42c3-87b2-0add6aeda9f0.png)

with these more modern variants with a leather top:
![image](https://user-images.githubusercontent.com/19356629/179375438-4d104aae-716c-4628-a036-7340731f7996.png)

The game seems to contemplate only the first example. Given how thick they are, and the fact that they're made out of solid wood, it actually seems reasonable to expect them to offer higher protection than a military combat boot for most purposes. In fact, their protection from regular wear-and-tear seems to be the main reason why some [Dutch farmers still wear them](https://www.quora.com/Do-Dutch-people-still-wear-clogs-at-all).

But it doesn't seem like their protective benefits would survive a combat situation. It seems like it would be trivial to get the clogs to shatter if you hit them sufficiently hard. So maybe this can be fixed by just adding the opposite of a 'STURDY' flag to the item? (I'm surprised we don't already have this for things like paper leg guards and whatnot) At the same time, this is a shoe made out of solid wood so...

40 encumbrance seems appropriate, everyone seems to agree that you need to get used to them before they even start to get comfortable. And I can't imagine [trying to run in them](https://youtu.be/rs8Oj47H4fw?t=49)...
