### ISSUE TITLE
Using description of recipes ending inside containers show the contained item instead

### ISSUE THREAD

**Issue by Shibimon** [CleverRaven/Cataclysm-DDA#56279]
### Is your feature request related to a problem? Please describe.

When you craft foods ending up in containers as in canning, pickles in jars, etc. the main description of the resulting item only mentions the name and portions of the item contained and not displaying useful stats like satiety, enjoyability, health or calories.
Some of these recipes have versions of them with just one portion out of the container allowing the player to see those stats, but i feel the players would make better use of information about the food they are analyzing to craft in each of the instances instead of seeing redundant and unimportant stats of containers.

### Solution you would like.

The ideal solution would be to display the food stats alongside the ones from the container, but if that's not possible, the stats of the food contained still will be more informative that what is showing now.

### Describe alternatives you have considered.

As a third option at least the D[e]scribe function of the crafting panel should display food stats instead of the container.

**Comment by ZeroInternalReflection** [comment]
The infrastructure is in the code to show both food and container statistics in the crafting recipe  See Pull Request [#51496](https://github.com/CleverRaven/Cataclysm-DDA/pull/51496) for what it looked like.

Unfortunately, it looks like shortly after that PR was merged, parallel development work in the crafting GUI ([#52685](https://github.com/CleverRaven/Cataclysm-DDA/pull/52685)) overwrote a couple of key lines for displaying that information.

Since the change appears to have been accidental rather than a deliberate UI choice, I'm currently testing to see if reverting those lines breaks anything new.
