### ISSUE TITLE
Rigid Oopsies

### ISSUE THREAD

**Issue by bombasticSlacks** [CleverRaven/Cataclysm-DDA#56391]
### Is your feature request related to a problem? Please describe.

After the rigid armor changes some stuff may not work that should.

Please post anything that isn't working bellow and I will fix it, I will also tag relevant issues.

#56384

STUFF TO FIX:

- [x] Fit-over sunglasses 
- [x] Ballistic glasses 
- [x] welding goggles
- [x] safety glasses
- [x] riot & motorcycle helmet w/ visor down
- [x] eclipse glasses
- [x] PBA Mask
- [x] Rain Hood
- [x] Nomad Body Mesh
- [x] Second Skin
- [x] Medical Gloves
- [x] Rubber Gloves
- [x] Hazmat Suit
- [x] Emergency Blanket
- [x] Magic Rings
- [x] Masks
- [x] Jackets (rain, winter, windbreaker etc.)
- [x] Optical Cloak
- [ ] Army pants
- [ ] mil flight helmet 

### Solution you would like.

I'm gonna have to add some additional detain for stuff like wear over sunglasses and gas masks so they can layer but still conflict with each other.

### Describe alternatives you have considered.

Having future sight and knowing everything that will not work well.

**Comment by DustyScales** [comment]
Firefighter PBA Mask and regular Eyeglasses also seem to give a lot of issues

**Comment by TheShadowFerret** [comment]
>I'm gonna make these have custom compliance

I thought we were unhardcoding things 🤔

**Comment by bombasticSlacks** [comment]
> > I'm gonna make these have custom compliance
> 
> I thought we were unhardcoding things 🤔

what would you suggest as a solution?

**Comment by TheShadowFerret** [comment]
> what would you suggest as a solution?

A flag that allows a rigid object to be stacked with others *if* they're not on the same layer. Ballistic/welding goggles move to OUTER layer like the safety glasses and fit-overs, the PBA and helmets have their eye-covering layer moved to OUTER.

**Comment by bombasticSlacks** [comment]
This is a good idea, it can't be a flag since for some items it will be portion specific. For example a bike helmet the top should still follow normal rigid rules even if you can put glasses on under it.  So instead of a flag it should be an armor def entry. 

There are more edge cases to consider. For example an altyn and a gas mask which you would run into issues with. I'm working on a solution but having something people can see to say "this is going to get fixed soon" is important whether or not it is the solution that's settled upon.

**Comment by lfaga** [comment]
"Rain hood" says in the description "This item can be worn with a helmet" but you can't. This is what happens when you implement and unasked for, awkward, unneeded system that adds no gameplay value.

**Comment by TheShadowFerret** [comment]
> "Rain hood" says in the description "This item can be worn with a helmet" but you can't.

Well that one can just be fixed by giving it SOFT, because they are :P

**Comment by bombasticSlacks** [comment]
already done in the linked PR 😄

**Comment by andrei8l** [comment]
A couple more:
Nomad bodymesh and Second Skin (both on an off) are now rigid and can't be worn under (nomad) plate etc.
Hub 01 mantle is rigid but doesn't count for exclusion (side note: it also doesn't seem to apply its warmth and encumbrance)

**Comment by lfaga** [comment]
Can't wear motorcycle helmets with glasses.

**Comment by FayFlightee** [comment]
...Uhh... aren't medical gloves supposed to be worn directly over your hands? It's... rigid.

**Comment by FayFlightee** [comment]
I can't wear armored fingerless gloves with wrist watch? wtf is this?

**Comment by Sathra225** [comment]
Chitin armor and chitin leg guards conflict. Probably because the armor protects 'legs' in general. Leg guards are lower leg and knee only.

**Comment by bombasticSlacks** [comment]
Yeah this one is intentional though the UI for partial armor isn't working. The chitin armor already covers the whole leg you can't wear knee pads or shin guards with it.

**Comment by Naadn** [comment]
The "mask of perfect vision" in Magiclysm works as glasses and only cover eyes. I think it should able to wear with helmets too.
And how about rings? Do gauntlets no large enough to fit a ring under it too?

**Comment by lfaga** [comment]
I still can't wear fit over sunglasses... Build 2022-04-01-0639, weren't this fixes already merged?

**Comment by bombasticSlacks** [comment]
No they are still waiting to be reviewed #56398

**Comment by lfaga** [comment]
Found another one, can't wear hard leg guards, I just have army pants and a union suit. And those are not rigid, I assume.

**Comment by MelacholicMimic** [comment]
The flight helmet faces the same issues as the motorcycle one.  There should probably also be a discussion if helmet wearing profession should start with contacts instead of glasses, at very least for flight helmet.

Additionally, creating a character with X-sighted trait currently ends up with either helmet or glasses getting deleted, apparently at random, if you test it with 'speed king' and 'military pilot'. That should probably get its own issue.

**Comment by bombasticSlacks** [comment]
Fix for glasses so they don't need to swap to contacts is already up. I'll add mil flight helmet too tho

**Comment by sonphantrung** [comment]
Currently, the Special Operator start with Near/Far-sighted still doesn't have glasses

**Comment by OldFriendEr** [comment]
Hi,Ii would like to argue that the tin foil hat should not be rigid.
Also should the Phase immersion suit get padded?

**Comment by Bossrman** [comment]
Given the description, which states "... cloth tucked under it to serve as a makeshift hood. Makes it more comfortable to wear..." I think that the hooded hard hat should be padded

**Comment by Sathra225** [comment]
Just had a bizzare situation in Innawoods with the Chitinous Helmet. Since it is rigid and uncomfortable, but also covers the eyes, the only way I could remove eye uncomfortableness was to wear an eyepatch.

**Comment by Sutremaine** [comment]
Craftables:

Any human armour with 'chainmail' in the name should be able to go under rigid armour.
The Faraday shark suit is also chainmail, and the survivor wetsuit hood has the 'can be worn with a helmet' text.

The solar backpack claims to worn like a backpack, but is listed as an Outer layer instead of being Strapped like other backpacks. Should probably be non-rigid to reflect its intent to be a backpack.
Gold rings should fit under any sort of glove.
Swimming gloves are very flexible.
The grass shirt and skirt should probably be treated like their cotton counterparts even if they are bulkier and less comfortable.
The grass sheet and cloak should definitely be flexible.
~The grass cape is wearable thatch, so that's fine being rigid.~
The chaplet (also grass) could be either rigid or flexible, but it doesn't do anything anyway so why not let the survivor make a fashion statement?
The improvised sleeping bag is a body bag full of straw. There are many reasons you wouldn't wear this (80, to be precise), but rigidity is not a concern.
Plastic bag socks should be wearable with footwear.
The duct tape blindfold should be able to tie around whatever you might be wearing.

Studded leather gloves are a weird one. If they're studded, then the studs could be flat enough to not interfere with proper hand armour. On the other hand, they do stab damage, so really they're spiked gloves.
In the same vein, the armored fingerless gloves are pretty lightweight, but the game doesn't say whether the metal guards are a flat sheet of metal or something bulkier.
Some of the wearable weapons are candidates for not conflicting with proper hand armour -- skewer and impact knuckles are strapped on, the nail and impact knuckles are held in the hand, and the cestus is leather wrapping with a few metal plates.

Lastly, the hooded hard hat. The recipe does call for padding, but this isn't reflected in the materials of the finished item. Might as well fix the base issue?

Uncraftables:

Unfolded poncho, and lamé (foil). The metal in the lamé is woven strands.

**Comment by FayFlightee** [comment]
Aren't bike helmets supposed to be foam padded? In fact the thing's desc said its literally foam helmet. Why is it rigid?

**Comment by kholat** [comment]
Ballistic mask is rigid, like say the firefighter PBA mask, but its not comfortable so you get a debuff for wearing it unless you use like balaclava + something for eyes

**Comment by PVM1234** [comment]
Hello I am playing on stable so this may have been fixed on experimental and i wouldn't have noticed, but the Aura layer seems to be underneath all other layers, which means that the Dream Armor spell will always be uncomfortable. My character is wearing a infiltration body suit so I usually don't have to worry about stuff like this I am pretty sure the spell wasn't intended to make you uncomfortable. I think the best way to handle this would be to make the spell cover the outer, or normal layer since it is summoning medieval armor, kinda like the paladin spell, which just summons a set of plate, but made of dream dross instead of metal. Or maybe the aura should be treated as the outermost layer, so protection spells get hit first, then we could have elemental wards and such without the worry of your armor getting damaged.

**Comment by bombasticSlacks** [comment]
I imagine it has been fixed by now, it's been almost a year. If it hasn't you can file an issue and tag the magyclysm maintainers 😄
