### ISSUE TITLE
Zero-encumbrance clothing should not be "poor fit"

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#56430]
### Is your feature request related to a problem? Please describe.

I feel that poor fitting socks and underwear should still stack with the ones that do fit, simply because their default encumbrance is zero.

### Solution you would like.

Ignore the poor fit flag for clothing whose encumbrance is zero anyway.

### Describe alternatives you have considered.

I actually tried implementing something like this recently. While I was able to get (poor fit) to stop displaying for these items of clothing, they still did not stack with properly fitting clothing.

This may also not be desirable since I don't know how this would interfere with mutated characters of non-standard size, and it may be worth leaving the info in to allow those who want to practice refitting clothing to do so more easily.

### Additional context

This is a small thing, and likely not worth implementing. I just figured I would ask.

**Comment by PatrikLundell** [comment]
In my view they shouldn't stack just because they happen to have an encumbrance value that means it doesn't have any in-game effect at the moment.

Things are going to change over time, and implementing special rules to deal with special cases where no differences in game effects are present means special failures when things are adjusted.

Also, while there may not be any mechanical difference, the game should make it easy to role play that it does, so players can look for upgrades to better fitting clothes or refit what they've got.
