### ISSUE TITLE
Don't make survivor gear out of cotton and leather

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#56494]
### Is your feature request related to a problem? Please describe.

Survivor gear should be made out of the best materials possible. Cotton and leather are not these - in game terms they inferior to many other options in a lot of ways such as defense and breathability.

### Solution you would like.

Lycra, Synthetic Fabric and even basic kevlar should be superior replacements for cotton and leather in the 0.2mm layer of the survivor suits. These materials have better defense and breathability, and I don't see any reason why these should have increased encumbrance, and in fact the leather-replacing ones should likely have reduced encumbrance because leather is a very stiff and difficult material.

### Describe alternatives you have considered.

Alter the properties of cotton and leather such that there is a justifiable reason to use these as part of your best homemade armor.

### Additional context

I can go ahead and push these changes, they're not super difficult to do, I just want to make sure there's not something I'm missing here.

**Comment by Termineitor244** [comment]
I'm of the same mind as you in this, but many of the survivor gear is made out of some cotton/leather based gear (cargo pants, backpacks, etc), so they should conserve some percentage of cotton too since that is what the player is building them around (And it already takes too much time even with these gear as the base, so removing them is not really an option).

**Comment by SirPendrak** [comment]
If survivor gear is meant to represent the best of the best possible handcrafted and customized gear, its strange that its based on standard clothes that are up-armored and have additioal pocekts and waterproof layer added. IMHO they should be made from the ground up using rolls of raw materials. 
Maybe we should split them into two tiers? Survivor stuff that is customized and upgraded existing gear, and "apocalypse suits" that are designed from scratch to be best thing a man can achieve aganist zombie apocalypse?

**Comment by PatrikLundell** [comment]
I agree with SirPendrak that there are two different use cases: one for early/mid game where you improve scavenged normal items with reasonably accessible materials, and one for mid/late game where you customize equipment from scratch (with the attendant long manufacturing process). There might even be room for a spectrum within each of these two groups, so you may have leather reinforced cargo pants at the low end and kevlar reinforced ones at the high end for the first group, as kevlar is a scarce resource.

**Comment by orbayyazanlar** [comment]
Whilst I agree that there can be more high end gear that utilizes lycra and/or military gear, I disagree that kevlar being a scarce source. It is day 39 and I have almost 200 layered kevlar panels at home, all of them scavenged- and I play with 0.5 item spawn with no hope. Neoprene and lycra are much more scarce.

**Comment by PatrikLundell** [comment]
What you can get hold of varies based on your play style and luck (as well of how the game balance happens to lean in the version you're playing). If you're lucky you'll stumble on a basement with large amounts of tailoring materials of all kinds. but if you have to scavenge it off of zombies and from homes it's very slow going. I agree that neoprene and lycra are (potentially) scarce resources as well, though.
Similarly, a number of fire trucks full with gear can shift the materials balance, but, again, it's largely down to luck finding it.

After about a month with standard spawn rate I don't have a single kevlar panel (I think: I did find a basement with tailoring equipment, but don't quite remember what I managed to find). The reason for the zero count is that I haven't actually dismantled anything yet, as I'm holding off doing that until I'm ready to tailor things, since the dismantling yield is based on skills that I hope to improve before that. In my 0.E-0 game the yields were pathetic, with large amounts of the kevlar harvested required for the construction of each single kevlar panel.

But yes, any item known to be made out of neoprene or lycra are mandatory pickups when looting homes (and zombies).
