### ISSUE TITLE
Request: A zone for automatically clearing rubble

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#56500]
### Is your feature request related to a problem? Please describe.

I burned down a building yesterday, and I needed to clear all the rubble manually to pulp the bodies underneath so they wouldn't get back up

### Solution you would like.

We have a zone for mopping up messes. Why isn't there a zone for clearing rubble?

### Describe alternatives you have considered.

More button presses

### Additional context
I'm hoping this already exists and I'm just dumb and can't find it.

**Comment by PatrikLundell** [comment]
Are there bodies underneath the rubble (i.e. invisible to the player when adjacent to the tile), and, if so, can these bodies actually reanimate while buried (as far as I understand bodies within containers can't reanimate until they're removed from the container). I've seen a fair number of undead killed by fire ready to reanimate later, but can't recall having encountered zombies coming out of rubble ruins that I definitely have missed.

Clearing rubble takes a lot of time. Probably enough time for any bodies that can be reanimated to do so before the clearing of a building is complete. You don't want to set a companion or the PC to clean up rubble and then get clobbered to death by reanimating bodies because they're too busy clearing rubble to defend themselves...
Hunger/thirst/tiredness/overheating are also things you're likely to be subjected to when clearing a lot of rubble tiles in one sitting.

**Comment by Inglonias** [comment]
I didn't encounter any hunger, thirst, or energy issues after clearing the bank I burned down. Granted, I was clearing piles of ash, not rocks or metal. Regardless, that's not really a reason not to make this happen - you can interrupt zone actions just fine.
