### ISSUE TITLE
Can't fast-loot loaded contents of items anymore

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#56621]
### Describe the bug

Previously I was able to scan a zombie, find his cell phone, and loot the battery inside it while leaving the cellphone behind. Or just wanted the bullets out of a gun and not the magazine or the gun itself, but now I can't. It only shows the exterior item and nothing else and I have to use the Unload command.

### Steps to reproduce

1. attempt to loot any object loaded with stuff.

### Expected behavior

The previous behavior saved tons of time and should be kept.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22000.556 (21H2)
- Game Version: c1f4cf8 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots]
]

**Comment by andrei8l** [comment]
Being able to see and loot the contents of magazines in the pickup menu was technically a bug, which I fixed in https://github.com/CleverRaven/Cataclysm-DDA/pull/56427. I can probably change this behavior though.

If you're getting this bug with contents in regular pockets, please submit the save file as that is not intended.

**Comment by lfaga** [comment]
> Being able to see and loot the contents of magazines in the pickup menu was technically a bug, which I fixed in #56427. I can probably change this behavior though.
> 
> If you're getting this bug with contents in regular pockets, please submit the save file as that is not intended.

"items in magazine{s, wells} aren't shown anymore (batteries, pen ink, etc)"

You consider this a bug, but truth to be told it was a very VERY handy feature to pick up ammo and batteries without having to go thru the extra steps of picking the gun/device, unloading and then dropping it. That "bug" was an actual QoL improvement. 
Extra steps is not better gameplay, sadly this game seems to tend heavily to extra steps and feature creep.

**Comment by andrei8l** [comment]
The bug was having two code paths for the same thing with one of them relying on deprecated code and not working as expected in 99% of the cases.

I've seen arguments for both sides ([example](https://www.reddit.com/r/cataclysmdda/comments/sd7k7d/is_there_any_way_to_get_rid_of_this_type_of/)) so it's not so clear cut, though I agree that the PR above was not the best solution.

I'm currently considering the best way to fix this without reverting the PR. Why don't you check the commit [above](https://github.com/andrei8l/Cataclysm-DDA/commit/6dd87a7894867d2c9672d9c996b2fb7d87d7eaf0) and see if it works for you?

**Comment by remd** [comment]
> You consider this a bug, but truth to be told it was a very VERY handy feature to pick up ammo and batteries without having to go thru the extra steps of picking the gun/device, unloading and then dropping it. 

You can use "Unload" directly on guns, magazine, electronic devices, etc. without picking them up to remove their contents.

Would being able to unload multiple items at a time from the "Unload" menu be a reasonable compromise? How important is it than unloading can occur from inside the pickup menu?

**Comment by anoobindisguise** [comment]
> > You consider this a bug, but truth to be told it was a very VERY handy feature to pick up ammo and batteries without having to go thru the extra steps of picking the gun/device, unloading and then dropping it.
> 
> You can use "Unload" directly on guns, magazine, electronic devices, etc. without picking them up to remove their contents.
> 
> Would being able to unload multiple items at a time from the "Unload" menu be a reasonable compromise? How important is it than unloading can occur from inside the pickup menu?

It makes a pretty huge difference. One menu vs two. Or sometimes you want to drop the contents of a loaded item directly, such as picking up a bunch of MP3 players and talking dolls and then throwing away the lower quality batteries, that's 2 menus vs 3.

**Comment by remd** [comment]
> It makes a pretty huge difference. One menu vs two.
I'm not sure I'm following you. Unloading an item puts its contents into your inventory. That's a single menu interaction to "pick up" the contents of an item. Using the Pick up menu and toggling the contents of an item or pocket, and then selecting the nested item is also one menu interaction.

As it stands right now Unload requires a menu interaction _per_ item but if we were able to Unload multiple items at once then I'm not seeing the difference between using the Pickup menu to do it vs. the Unload menu. That's why my suggestion is to allow multiple items to be unloaded at once, to provide the functionality that was lost in #56427.

> Or sometimes you want to drop the contents of a loaded item directly, such as picking up a bunch of MP3 players and talking dolls and then throwing away the lower quality batteries, that's 2 menus vs 3.

Again, if we had the ability to unload multiple items at once it would be 2 menu interactions. One menu interaction to Unload all the electronic devices, and then another menu interaction to Drop the batteries you don't want.

**Comment by lfaga** [comment]
> As it stands right now Unload requires a menu interaction _per_ item but if we were able to Unload multiple items at once then I'm not seeing the difference between using the Pickup menu to do it vs. the Unload menu. That's why my suggestion is to allow multiple items to be unloaded at once, to provide the functionality that was lost in #56427 without reintroducing the "bug" that was fixed by that PR.

It's not the same, to unload you need to pick up first the items your are interested (probrably going thru a list and selecting indiviual items) then unloading (once per item or again, selecting from a list of items as you propose) and then dropping the unloaded items selecting from a list of your inventory again. This "bug fix" turned one list selection into at least 3 list selections. The excuse is to "unclutter" the pick up menu... that's what filters are for... just pick up, slash filter "batt", press comma, enter... BAM! all the batteries are in your inventory.

**Comment by remd** [comment]
>to unload you need to pick up first the items your are interested

That's not true.

Notice that the flashlights and first aid kits are in Cupboard 1E, an adjacent tile. They are **not** in my inventory.
![image](https://user-images.githubusercontent.com/1325809/162581398-8397fe54-70db-483c-8df3-e370b52775a5.png)

Unloading the battery from the nearby flashlight never involved picking up the flashlight, my character only looted the battery.
![image](https://user-images.githubusercontent.com/1325809/162581407-7bce3a3e-42b6-4507-abd9-09c4ad8c735c.png)

I am running on game version ba9af2e [64-bit].

**Comment by lfaga** [comment]
> > to unload you need to pick up first the items your are interested
> 
> That's not true.

In the case of batteries you are right, it was a bad example, one thing you could do with the way it was before is to pick from nested container. Gun->Magazine->Ammo, you could pick just the ammo, now you should, unload gun, unload magazine, and then drop the magazine to do the same. It was just a little thing, I know, but why disable a convenient feature, the dev himself said he added special if cases to hide those items, is not that this is a collateral of removing a bug, it was purposely hidden to "unclutter"the pick up list. If there's a big pile of stuff, you gonna get a big pickup list, you can filter... no uncluttering was needed, the whole thing is so silly, that I am getting bored of trying to defend my point.

**Comment by remd** [comment]
> the whole thing is so silly, that I am getting bored of trying to defend my point.

I'm sorry you feel that your position is being attacked; that is not my intention at all. I'm genuinely trying to understand what a compromise would look like that would satisfy all parties. The use of incorrect examples led to some unnecessary back and forth.

> Gun->Magazine->Ammo, you could pick just the ammo, now you should, unload gun, unload magazine, and then drop the magazine to do the same. 

I can see why disallowing this make some sense in the pursuit of realism, since most magazines IRL cannot be unloaded while the magazine is inserted into the gun. But I think convenience/simplicity is probably more important in this case. I support bringing the functionality back (i.e. reverting #56427 or re-introducing the behavior via some other code path).

I will probably not contribute further to this discussion since my attempts to mediate are clearly unproductive and therefore unhelpful. I apologize for derailing things.

**Comment by andrei8l** [comment]
Filtering is useful if you're looking for a specific item (ex `battery`), but if you're just browsing then filtering out the clutter takes a lot of typing (`-pen ink,-battery,-p:liquid,-...`).

You should check out the proposed solution in https://github.com/CleverRaven/Cataclysm-DDA/pull/56630 instead of beating the dead horse here. I've already decided to re-add magazine contents and I think the PR above should be a good compromise for you too.
