### ISSUE TITLE
Allow the CVD machine to coat non-steel weapons

### ISSUE THREAD

**Issue by AmarinReyny** [CleverRaven/Cataclysm-DDA#56678]
### Is your feature request related to a problem? Please describe.

Certain weapons cannot be diamond-coated due to the materials they're made of, such as bronze or iron. I really wanted a diamond khopesh, too...!

### Solution you would like.

I'd like for the CVD machine to be able to coat non-steel weapons.

### Describe alternatives you have considered.

Making steel variations of bronze weapons, and switching all iron weapons to steel (basically what I've been doing in my own self-modded game anyway).

**Comment by Maleclypse** [comment]
```void iexamine::cvdmachine( Character &you, const tripoint & )
{
    // Select an item to which it is possible to apply a diamond coating
    item_location loc = g->inv_map_splice( []( const item & e ) {
        return ( e.is_melee( damage_type::CUT ) || e.is_melee( damage_type::STAB ) ) &&
               e.made_of( material_steel ) &&
               !e.has_flag( flag_DIAMOND ) && !e.has_flag( flag_NO_CVD );
    }, _( "Apply diamond coating" ), 1, _( "You don't have a suitable item to coat with diamond" ) );

    if( !loc ) {
        return;
    }
```
Here in iexamine.cpp is where this would need to be changed.  There may be irl reasons that it only works on steel but assuming that's not the case it should be pretty easy to add additional materials.

**Comment by p4nc4k3z** [comment]
I've done a little research, and it looks like sadly there are IRL reasons that CVD of diamond coating would only work on steel and iron, though the process is very complex.

[This 2020 paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7464996/) goes into why it's so tricky, but does show successfully-created CVD diamonds grown on silicon, steel and iron substrates (fig. 3).  Whether one somewhat-magical lab finale machine could work with two different substrates would be a question for someone more informed than me, but iron seems reasonable, at least.

A [Japanese CVD company's website](https://www.allied-material.co.jp/en/faq/cu_cvd_diamond_hs.html) suggests that copper and aluminum are out though in an explicit Q&A page: "Due to big difference in thermal expansion between Copper and CVD Diamond, it is not possible to deposit CVD Diamond on Copper or Aluminum plate."

And @AtomicFox556 from the linked CR seems to be correct in that bronze doesn't make sense, either.

So!  Adding iron is a straightforward code change, and I'll go ahead and submit it.
