### ISSUE TITLE
Recess and Murky water tiles cannot be removed

### ISSUE THREAD

**Issue by Kantonine** [CleverRaven/Cataclysm-DDA#56804]
### Is your feature request related to a problem? Please describe.

Open air recesses and murky water tiles currently are unable to be removed in any way, blocking potential construction/farming, this is weird as:
1). Recesses are small pits in the ground, and the deeper pits can be (re)filled.
2). Shallow water tiles can be converted to plain dirt through the construction menu

### Solution you would like.

Allow for non cave recesses to be filled in with dirt/outright removed through digging menu or construction menu and add fill water constructions for murky water tiles.

### Describe alternatives you have considered.

dont do this i guess?

**Comment by NetSysFire** [comment]
I can confirm this. You can not dig a pit either to circumvent that. The solution would be to add a recipe to `construction.json` to fill murky water (I would just copy it from the recipe that fills shallow water, maybe use a tiny bit less dirt) and one to fill up the recess, using a bit of dirt. Not as much dirt to fill up a pit, but just a little.

@Night-Pryanik since you added the recesses, would there be a possibility of making them diggable when there is no more water inside?

**Comment by Night-Pryanik** [comment]
Yeah, I think it's possible.
