### ISSUE TITLE
Finished worn smoke items reports providing hyper cut protection

### ISSUE THREAD

**Issue by Golfavel** [CleverRaven/Cataclysm-DDA#56833]
### Describe the bug

Wearing a burnt smoking item (joint roach, cigarette butt, etc) reports giving the character a cut protection amount of "7878097584417308324994076519694336.00"

### Steps to reproduce

1. Light smoke
2. Wear the lit smoke
3. Extinguish the lit smoke (either by waiting or manually)
4. Enter Sort Armor menu
5. Highlight burnt out smoke
6. Examine the ~~health~~ protection benefits

### Expected behavior

The burnt item wouldn't report giving such high cut protection and/or would automatically be de-equipped.

### Screenshots

![Screenshot_20220415_191532](https://user-images.githubusercontent.com/32048635/163656239-f573cf3e-0f80-4c81-a18b-fa8e3eca0dc9.png)

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.4 LTS; Release: 20.04; Codename: focal; 
- Game Version: 5fe200b [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by psuedolet** [comment]
![image](https://user-images.githubusercontent.com/29447613/163694029-54b108ef-b009-4b67-94dd-c1b4e6be3ca9.png)
Reproduced on today's experimental. 
Worn joint roach does not show up in the 'Take off item' menu. Does show up in Inventory and Sort Armor.  
I'm guessing this is due to the joint roach not having defined armor data, despite being worn.
