### ISSUE TITLE
Add ability to copy craft recipes from manual to basecamp crafting list

### ISSUE THREAD

**Issue by BGASM** [CleverRaven/Cataclysm-DDA#56858]
### Is your feature request related to a problem? Please describe.

Current basecamp model restricts crafting missions to recipes declared in their recipe_group, which works fine currently but seems limited in modularity. Any newly added or modded items will need to be explicitly added to recipe_group as the item list grows, and it trivializes tracking down manuals. 

With NPC functions such as ordering them to read a book or to hold seminars, and with the bookbinder activity I think a new process for basecamp crafts can be worked on.

### Solution you would like.

- I think that basecamp upgrades should have an associated field tied to crafting skill levels.
- Each upgrade should have a handful of useful crafts that are unlocked when the upgrade is completed.
- The player can copy recipes they have learned, or have a manual for, to the building's recipe list.

1. For example kitchen_recipes_1 would have a field that limits recipes to skill_used: cooking difficulty: 1.  Any recipes that the player wants to copy over to this building's recipe list would have to be <= these requirements.
2. Continuing to use kitchen_recipes_1 as an example:  it would unlock recipes for tinder, meat_cooked, fish_cooked, boiled_egg, starch, flatbread, veggy_wild_cooked, whether or not the player knew them. It could even unlock a few recipes that were greater than the upgrade's difficulty limit. But you would expect that upgrade kitchen_recipes_2 would unlock primarily difficulty 2 recipes, with a couple difficulty level 3.
3. Finally, the player would be able to copy over any difficulty 1 recipes they have memorized, or have a manual for. Such as gelatin_dessert_vegan, or macaroni_cooked. They would have to ensure that any additional tools/components where accessible in basecamp_storage.

I have been looking over the bookbinder activity code and think that it could be adopted to copy recipes to basecamp buildings, but I need to dig deeper to figure out how the camp would access them. It looks like the code that populates the crafts pulls from the building recipe groups, so some kind of serializable object would need to be made to hold any copied recipes for each building. 

In any case, a design for basecamp crafting that has less items absolutely hardcoded, and allows for modularity seems to be a good way to move forward.

### Describe alternatives you have considered.

1. Populate crafting lists based on manuals stored in basecamp storage.
2. Populate crafting lists based on NPC's highest crafting skill levels.
3. Instead of defining what items are craftable at each basecamp upgrade move that declaration to a flag listed in each item's crafting recipe. When adding new or modded items, one could specify what building should unlock it as a viable craft.

**Comment by PatrikLundell** [comment]
I agree that hard coded recipe population is less than ideal, and like the thought that you'd be able to "populate" the base camp (expansion) with suitable recipes that are either known or written down.

I believe the long term goal is for a more fine grained functionality availability at the base camp (expansion) should determine what you can make, rather than the rather crude set we currently use, but that's probably a significant way off. Another issue is that the current UI is less than ideal for management of a large number of recipes, as everything ends up in a huge list, so the UI would have to be revamped at some time to allow for a larger selection, possibly using a similar layout to the one used by the regular crafting UI (multiple tabs, etc.).

Given the current UI limitations, I think manual selection of recipes one by one would be the most suitable for the time being. However, I don't think player skill level ought to be the determining factor, as companions may be more skilled, and they are the ones who are going to use the recipes and need the skills for the crafting anyway. Thus, I think knowing (of) the recipe should be the factor. Currently I don't think we can get at auto learned recipes companions ought to have, but I think we can live with that deficiency.

One hurdle such functionality would need to pass is to filter out recipes that produce fluids, as the current companion crafting system doesn't handle the placement of the results in containers, so the fluids would just be dumped on the ground. The other would be to determine the criteria for which recipes to permit. I wouldn't tie that to recipe groups at all, but rather to functionality provided by the base camp (expansion).

Technically I think the manually introduced recipes could be stored in a vector in the base camp (expansion) structures, so the hardest part would probably be to make the UI for the recipe selection (again, the list you'd select from might be huge).

Does @I-am-Erk have any comments on this?

**Comment by BGASM** [comment]
A comment on the UI limitations that you mentioned: I like how the message board serves as a central hub for the camp, but I did think that once you unlocked a large number of crafts, they would become a slog to filter through. What if each building had its own board that contained its specific recipes - and the central camp board was reserved for camp-wide missions? I haven't looked through the code enough yet to see how big of a head ache that would be versus tooling additional tabs into the existing UI, but it was a thought I had while trying to think of how I would approach the basecamp if I had stronger programming chops.

**Comment by PatrikLundell** [comment]
I wouldn't like to have to walk to a different place for each expansion: the current tabs to get between then is fine, but it might be tricky to handle getting into recipes for each expansion. Maybe enter a multi tab crafting menu as the PC one if you want to order a companion to craft, and then have to escape out to get to the base/expansion level? I don't know if the widgets used would support that, however.
