### ISSUE TITLE
molotov cocktails can generate hovering fire

### ISSUE THREAD

**Issue by esotericist** [CleverRaven/Cataclysm-DDA#56930]
### Describe the bug

molotovs generate fire in the 3x3 around their landing point regardless of whether or not there's anything to support the fire.

### Steps to reproduce

1. find a building or two with 3 z levels
2. spawn some molotovs and a lighter
3. (optional) be strong enough and adept enough at throwing to toss the molotov at range
4. smash the gutter so the molotov can land on the edge of the roof instead of a tile away from the edge
5. light and toss molotov to edge of roof. this might take a few tries without 3. fulfilled
6. observe magical floaty fire

### Expected behavior

fires should probably not persist unsupported. at the very least, molotovs should not place fires 

### Screenshots

![image](https://user-images.githubusercontent.com/1569754/164085056-713cc971-623b-4d97-8d10-32375b889066.png)

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Debian; Description: Debian GNU/Linux 11 (bullseye); Release: 11; Codename: bullseye; 
- Game Version: ba5e863 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    eso_ui_bits_msx [eso_ui_bits_msx]
]

### Additional context

i know this isn't latest master, or even a super recent one, but i can't find any evidence of any relevant changes in commits since, and this is on my chromebook and updating is annoying. 😝

**Comment by NetSysFire** [comment]
Can reproduce.

Vaguely relevant to #52345, in my opinion it is fine for fire to appear in midair for a second due to the explosion but it should vanish shortly after. Basically physics not being applied on spawn sometimes is the root cause.

While trying to reproduce I also found another unrelated issue since I have both clairvoyance and its super counterpart in my debug world and character, throwing gets super weird when enemies are below you but there is solid ground between you and them, since you do not see the targeting indicator, even when turning off snap to target.

**Comment by esotericist** [comment]
yeah, i'd probably be fine with the fire bursting then vanishing, but just not placing it in the first place seemed more reasonable short term fix to me. i can't find any evidence fire can spread to unsupported locations (other than directly above another sufficiently intense fire, but i think that is close enough conceptually to 'supported')

also yeah, throwing targeting in general gets super weird when z-levels are involved even without enemies. we should probably open a separate report for that.
