### ISSUE TITLE
BUG/Suggestion: Either make trader NPCs NOT investigate sounds or lock them behind reinforced glass.

### ISSUE THREAD

**Issue by Jan-Blasiak** [CleverRaven/Cataclysm-DDA#56990]
### Is your feature request related to a problem? Please describe.

Last time I did the "Traitor" quest for the Merchants, shooting the traitor caused the Merchant behind the locked counter to smash his own window, and run into the corridor, where he now sits, away from his designated location AND his pile of goods for sale.

### Solution you would like.

Either make trader NPCs, preferably all of them for safety sake, NOT investigate sounds or lock them behind reinforced glass/steel bars or other applicable "cages". It's EXTREMELY irritating having to go to the corridor to trade with Merchant.

**Comment by Inglonias** [comment]
I think the simplest solution here is to lock Smokes behind reinforced glass, yeah.

**Comment by Ilysen** [comment]
Smokes actually \*is\* behind reinforced glass, it's just that his weapon (a Halligan bar) has very high bash and can break it. #56195 has been up to fix that, but has yet to be merged.

**Comment by I-am-Erk** [comment]
So, the solution here is probably not to make Smokes pound ineffectually on the indestructible glass. I suggest we set up an effect series for merchants like Smokes, and the doctor on the other side of the room, and probably a few more: drop their movement speed to 0 so that they cannot leave their spot, and add an Effect on Condition that turns that effect off if they're in danger. This will hold them in place and stop them from doing weird things in other situations

For the EoC I'd turn it off if:
- The door opens
- The window is broken
- The merchant takes damage
- The player becomes hostile to the faction

The EoC that makes the merchant mobile could also unlock the merchant's door temporarily, as long as we have a setup that can get them back to their position and re-lock the door later.

**Comment by Maleclypse** [comment]
@Jan-Blasiak I can’t seem to tag you on https://github.com/CleverRaven/Cataclysm-DDA/pull/57072

but it’s been merged and I’m concerned maybe I added your name incorrectly.

**Comment by I-am-Erk** [comment]
I am making some recommendations to push forward for stable release. For this issue, I suggest that we resolve it *in stable only* by:
1. Create a mutation that makes a character unable to move. 
2. Apply that mutation to smokes, the refugee doctor, the broker, Rubik, and any other merchant or similar NPCs that really shouldn't leave their spots.
3. Although the mutation can be kept in the code (it can be handy for mods), it should only be applied to these NPCs in the G-stable release. It should be removed for H-experimental.

**Comment by I-am-Erk** [comment]
Posting this possibly for my own reference:

https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/character.cpp#L3789-L3796

I think easiest is to add a conditional here for "if has trait (no move), skip all this and instead return a speed of 0."

**Comment by Night-Pryanik** [comment]
Fixed by #62439.

**Comment by I-am-Erk** [comment]
Technically, as noted above, that solution is meant to be a stopgap. I plan to remove some of those flags after stable, although the solution is robust enough that I may not be as prompt about it. We can perhaps leave this closed, but we'll need a follow up issue about the actual solutions we need.
