### ISSUE TITLE
Disassembling ammo quantities above 50 results in less materials

### ISSUE THREAD

**Issue by toweroglass** [CleverRaven/Cataclysm-DDA#57082]
### Describe the bug

Naming this issue accurately and succinctly perplexes me. 
Basically, disassembling more than 50 of a stacking item (mostly ammo) will cause the game to resort to the default batch craft limit, 50. But it still will consume your entire stack.

### Steps to reproduce

1. create new world.
2. spawn kinetic bullet puller and 50+ bullets.
3. disassemble all ammo spawned.
4. gain only 50 bullets worth of materials

### Expected behavior

would expect to get the results of what you disassembled.

### Screenshots

![bug](https://user-images.githubusercontent.com/81603517/164943211-ebec3652-640e-4c0c-87da-119b36d72706.png)

this screenshot was in my current game. I took it last night before i logged off, but was able to reproduce in a new save game. version info below is for the new completely modless world i started.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1645 (21H2)
- Game Version: 4f506d1 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by ejseto** [comment]
The problem is in crafting.cpp, line 2591, in Character::complete_disassemble:
`compcount *= std::min( dis_item.charges, dis.create_result().charges );`
The disassembled component count is clamped to, I'm guessing, the default charges of the ammo. It could be changed to:
`compcount *= dis_item.charges;`
But I don't know if that would break anything else.
