### ISSUE TITLE
Rigid mutation armors

### ISSUE THREAD

**Issue by fairyarmadillo** [CleverRaven/Cataclysm-DDA#57177]
### Describe the bug

The jumbled skin mutation counts as rigid armor, which totally prevents the mutant from wearing eyeglasses. You also can't wear even XL rigid armor anywhere on your body, which may or may not be intentional, but seems like it makes the mutation less optimal than may be intended.

### Steps to reproduce

Get jumbled skin
Be unabled to wear glasses
Cry

### Expected behavior

The eyeglasses at least should be wearable with jumbled skin, unsure about the intention with hard armor.

### Screenshots

- OS: Windows
    - OS Version: 10.0.19043.1645 (21H1)
- Game Version: 3e81ac1 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1645 (21H1)
- Game Version: 3e81ac1 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Heitomos** [comment]
Similar to this, the Protective Bark mutation leaves you uncomfortable on every body part, because you aren't wearing something soft underneath your new skin.

**Comment by fairyarmadillo** [comment]
Pinging @MylieDaniels @bombasticSlacks - this seems like an easy fix, but these were recent changes and I'm not sure what the intention was. I could just add padded to everything, but I'm not sure whether phelloderm is supposed to prevent wearing plate mail or what the proper fix for eyeglasses and chimera skin is (should it even be covering eyes at all?).

**Comment by bombasticSlacks** [comment]
So chimera skin probably shouldn't cover the eyes. However for eyes you can set rigid_on_layer or whatever the attribute is that all the eyewear currently has. Only issue with that is depending on what layer that chimera armor is on it might still conflict with eyeglasses. 

Full disclosure feature freeze is coming soon so I've been trying to get a few more goodies into release rather than fixing stuff just yet. 

Also for everything non eyes, padded is just good enough. IMO any of the hard skins should prevent hard armors, though future balance and mutation consideration should keep it in mind.
