### ISSUE TITLE
Inconsistency in loot generation (question)

### ISSUE THREAD

**Issue by GuardianDll** [CleverRaven/Cataclysm-DDA#57209]
### Is your feature request related to a problem? Please describe.

doing stuff for map, i found i cannot use some item groups for my purpose, because the difference between `distribution` and `collection` - for example, i cannot use `allclothes` and `clothing_military` at the same time, because first one generate only 1 item from list, and the second can spawn 5-10 of them at once. I am not entirely sure how i need to solve it - am i need to duplicate some categories for my purpose (coutn it as bad solution, because its hard to maintain them in such case)? ~~copy-from them with opposite entry (will it work?)?~~ of course it doesnt work. Some another solution i dont know?

**Comment by RandDenner** [comment]
All right. Afaict, you have to make new groups based off of the original.
Let's use `clothing_military`  as an example.
```
  {
    "id": "clothing_military",
    "type": "item_group",
    "subtype": "collection",
    "//": "Standard (non-winter) set of clothes worn by soldiers and paramilitary forces.",
    "items": [
      { "group": "clothing_soldier_shirt" },
      { "distribution": [ { "item": "jacket_army_modern", "prob": 50 }, { "item": "combat_shirt", "prob": 50 } ] },
      { "item": "pants_army" },
      { "item": "webbing_belt" },
      { "distribution": [ { "item": "socks", "prob": 95 }, { "item": "socks_wool", "prob": 5 } ] },
      { "item": "boots_combat" },
      {
        "distribution": [
          { "collection": [ { "item": "sports_bra" }, { "item": "boy_shorts" } ] },
          { "distribution": [ { "item": "briefs" }, { "item": "boxer_briefs" }, { "item": "boxer_shorts" } ] }
        ]
      }
    ]
  },
```
You can't just change `"subtype": "collection",` to `"subtype": "distribution",` because in `distribution`, every potential generation in the list must have a `"prob":` assigned to it.
Here's how that would work:

`{ "group": "clothing_soldier_shirt" },` is the first entry:
If you want a 50% chance, the line would change to `{ "group": "clothing_soldier_shirt", "prob": 50 },`

Next is: `{ "distribution": [ { "item": "jacket_army_modern", "prob": 50 }, { "item": "combat_shirt", "prob": 50 } ] },`
this becomes
```
          {
            "distribution": [ { "item": "jacket_army_modern", "prob": 50 }, { "item": "combat_shirt", "prob": 50 } ],
            "prob": 15
          },
```
for a 15% chance.

The next line, `{ "item": "pants_army" },` becomes `{ "item": "pants_army", "prob": 60 },` for a 60% chance.

And so on.

If you copy the other lines:
```
  {
    "id": "clothing_military",
    "type": "item_group",
    "subtype": "collection",
    "//": "Standard (non-winter) set of clothes worn by soldiers and paramilitary forces.",
    "items": [

      all of the various items that are rolled for

    ]
  },
```
Then if you change "collection" to "distribution", it should work.

All the examples of the proper coding you need seem to be in the `clothing.json` file.
I just read it over myself to make this. You can definitely figure it out with some patience.
I hope this helps. Good luck!

**Comment by GuardianDll** [comment]
That was not related to question tbh, but i found i make mountain out of molehill - if i duplicate the whole entry and change it to have a distribution instead of collection, that just mean we will take 2 entries (which is not as bad as i imagine)
Thank you for the help anyways

**Comment by RandDenner** [comment]
I understood.
I think making new copies is the only way.
