### ISSUE TITLE
Automated Ranged weapons training

### ISSUE THREAD

**Issue by FayFlightee** [CleverRaven/Cataclysm-DDA#57261]
### Is your feature request related to a problem? Please describe.

Currently, only the throwing is the auto-trainable skill of ranged weapons by its ranged recipe. While that's perfectly understandable, it would be wonderful if we can have automated ranged weapons training, So we don't need to go through 8 bajillion key presses.

### Solution you would like.

Automatically reloading and shooting held ranged weapon at practice target after a keybind somewhere.

**Comment by FayFlightee** [comment]
> Archery has an in progress PR (#56344), but for firearms... It would be difficult, there are too many, and too many types of ammo too.

Well we're shit outta luck then.

**Comment by TheShadowFerret** [comment]
This would be hard given most practice recipes for these would produce noise, which recipes can't do(atm) and thus should be quiet so we can avoid that logichole.

Handguns: Nailgun, pistol crossbow, mini speargun
Rifles: Crossbows, coilgun, speargun
SMGs: Repeating crossbow
Launcher & Shotguns: Nothing D:

**Comment by FayFlightee** [comment]
> This would be hard given most practice recipes for these would produce noise, which recipes can't do(atm) and thus should be quiet so we can avoid _that_ logichole.
> 
> Handguns: Nailgun, pistol crossbow, mini speargun Rifles: Crossbows, coilgun, speargun SMGs: Repeating crossbow
> 
> The crossbows do use retrievable ammunition like the bows, so they would probably be the best choice.
> 
> Shotguns: Nothing Launchers: Water cannon? 🤷‍♂️ So nothing

Well, I'm saying that for other ranged weapons, instead the automated training is NOT a practice recipe, but indeed letting the character keep shooting their **held** ranged weapon at a practice target and automatically reload when out of ammo. That would avoid the "recipes don't make noise" stuff, but I have no idea how to actually implement the idea.

**Comment by fairyarmadillo** [comment]
Needing a crossbow to practice my rifle skill despite owning a pile of rifles and no crossbows would stretch believability a bit.

**Comment by AmarinReyny** [comment]
> > This would be hard given most practice recipes for these would produce noise, which recipes can't do(atm) and thus should be quiet so we can avoid _that_ logichole.
> > Handguns: Nailgun, pistol crossbow, mini speargun Rifles: Crossbows, coilgun, speargun SMGs: Repeating crossbow
> > The crossbows do use retrievable ammunition like the bows, so they would probably be the best choice.
> > Shotguns: Nothing Launchers: Water cannon? 🤷‍♂️ So nothing
> 
> Well, I'm saying that for other ranged weapons, instead the automated training is NOT a practice recipe, but let the character keep shooting their **held** ranged weapon at a practice target and automatically reload when out of ammo. That would avoid the "recipes don't make noise" stuff, but I have no idea how to actually implement the idea.

Maybe it could be a zone activity? Like, I dunno, set up a target zone, a zone for shooting from, and a zone for ammo, and with all three set up, you could access the ability to automatically shoot at the target zone from the same menu where auto-sorting is accessed from?

**Comment by catdach** [comment]
> > This would be hard given most practice recipes for these would produce noise, which recipes can't do(atm) and thus should be quiet so we can avoid _that_ logichole.
> > Handguns: Nailgun, pistol crossbow, mini speargun Rifles: Crossbows, coilgun, speargun SMGs: Repeating crossbow
> > The crossbows do use retrievable ammunition like the bows, so they would probably be the best choice.
> > Shotguns: Nothing Launchers: Water cannon? 🤷‍♂️ So nothing
> 
> Well, I'm saying that for other ranged weapons, instead the automated training is NOT a practice recipe, but let the character keep shooting their **held** ranged weapon at a practice target and automatically reload when out of ammo. That would avoid the "recipes don't make noise" stuff, but I have no idea how to actually implement the idea.

*sigh* So from my perspective, this isn't really a realistic request. Automatic skill grinding is pretty much relegated to practice recipes. AFAIK practice recipes became a thing specifically to get rid of the tedium of manually throwing rocks at a target to level throwing and similar things that players do to grind early skill levels. Especially since books don't give _real_ levels anymore.

Automatic reloading is probably a no, even if it would only be for when you're training. Mostly because reloading isn't that hard? Like I don't mean to be rude but hen you ask for what is (_usually_) 2-4 keystrokes to be automated, What you're really asking for is for macros to be added to the game (which I think is on an FAQ somewhere but I can't find it). Also if you're trying to practice with your ranged weapons that much, you've probably gone **way** past the point that shooting a practice target will give you any practical amount of XP (You do know that living targets give you more XP right?)

>Maybe it could be a zone activity? Like, I dunno, set up a target zone, a zone for shooting from, and a zone for ammo, and with all three set up, you could access the ability to automatically shoot at the target zone from the same menu where auto-sorting is accessed from?

maybe? That's certainly how DF does it, but that would take a lot of code for new specialized zones. I would honestly wait for macros before trying that solution. Although it does give me an idea...

What about a shooting gallery? like, the ones they have at carnivals and such. Could have a fenced off area with a button that starts spawning some 1HP "enemies" (targets) that disappear after a few seconds. Maybe have that as a camp expansion or something? admittedly that would be a whole ton of work but I think it's at least a decent idea.

**Comment by fairyarmadillo** [comment]
The way that you train in the proper use of a firearm IRL is that you shoot at a target with the firearm you want to get to know. Hobbyists, military folks, and police spend hours and hours on the range so they don't get rusty. I don't think there's going to be a good solution until someone can make the following happen:

1) The practice task would need to be able to use any weapon of the appropriate type, similar to how crafting tasks can use anything with the appropriate tool quality currently.
2) The practice task would need to consume an appropriate amount of ammo relative to the time spent and the gun in question. An SMG would chew through ammo faster than a revolver, even on single fire.
3) The task would need to make an appropriate amount of noise for the gun in question.
4) The task would need to contribute to fouling etc. appropriately, especially as it would be a good idea to use black powder loads in many cases.

This would also fix the issue where melee dummy training requires hyper-specific items rather than working with any weapon of the appropriate category. Yes it will require someone to actually code it, but it's better than hacking together a weird stopgap solution that doesn't make any sense.

I think it's a little weird that crafting is currently a silent activity in general, and implementing this would open the door to doing some interesting things with other crafting jobs. If a crafting job requires a cordless drill or a food processor, shouldn't it make quite a bit of noise?

**Comment by bombasticSlacks** [comment]
Closed by #59520
