### ISSUE TITLE
Lupine primer gives rodent tail

### ISSUE THREAD

**Issue by fairyarmadillo** [CleverRaven/Cataclysm-DDA#57275]
### Describe the bug

I gave an NPC who had long tail some mutagenic catalyst and lupine primer. He had a long tail and it shifted to a rodent tail. His other mutations are furry, long fingernails, and night vision.

Debug shows no other mutagens in his system, just lupine and mutagen. If I understand correctly, this shouldn't be possible.

### Steps to reproduce

Get an NPC with the listed mutations, apply lupine primer and mutagenic catalyst, wait, rat tail.

### Expected behavior

I expected the NPC to get fluffy tail or a different lupine mutation.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1645 (21H1)
- Game Version: d2cecff [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Sinistrem** [comment]
Had a similar issue when using feline mutagens, my rough skin mutated into an Epicuticle. I assumed it was a bug and rolled back to the previous save, only to have it mutate into feathers instead. Since  I  only had feline mutagen in me, I assume currently all branching mutations (tails, skin, etc.) can roll any mutation ignoring your targeted mutagen count.
