### ISSUE TITLE
step on area to give tip in tutorial

### ISSUE THREAD

**Issue by drjoms** [CleverRaven/Cataclysm-DDA#57344]
### Is your feature request related to a problem? Please describe.

Problem: shortcuts are a mess.
You need to be rocket scientist to understand them.
Tutorial creates more issues than solves.

In tutorial you read tutorial message once. And you dismiss it. Forever. And ever. So you want to read it again.
AAAAAND its gone!
https://www.youtube.com/watch?v=-DT7bX-B1Mg

### Solution you would like.

So what I suggest.
Make an area on the floor.
You step on it. Tip message appears. You move away. You come back. Stand on it. Message re-appears.
Thanks

### Describe alternatives you have considered.

take screenshots?
Are there alternatives?

**Comment by drjoms** [comment]
Alternatively break tutorial into parts.

**Comment by Night-Pryanik** [comment]
Major part of tutorial is already made the way you described: you step on a specific tile, and message appears. The thing is, someone (who designed the original tutorial) decided that game shouldn't display tutorial messages more than once. It's literally just one line of code, but I'm not sure whether we should switch to this behavior.

> Tutorial creates more issues than solves.

What type of issues tutorial creates?

**Comment by drjoms** [comment]
> What type of issues tutorial creates?
As new player, when I am forced to start tutorial 10th time to see one of last messages in actual tutorial, which not ONLY takes tonnes of time but it becomes annoying.

To make things worse, existing messages can NOT be ignored.
That means extra click that can't be avoided that gives nothing and wastes time and effort.
Majority of people are not used to use whole keyboard in a game.(albeit it can be argued game is not made for majority anyway, but hey, aim for the moon, you may hit the stars!)

If I was not persistent, I would look at game, fail to complete tutorial and remove the game all together without even starting it.

**Comment by haveric** [comment]
As the person who helped rewrite and update the tutorial, I agree that it has its shortcomings and I think the steps towards solving this are:
1. Tiles on the floor that show messages should be visible and repeatable. Once they are made repeatable, they should be closable via the movement keys (or any key?) in order to keep the flow moving.
2. Fix a couple broken tutorial triggers that still exist.
3. Messages need to drastically be shortened and broken up. We're throwing too much at the player too quickly. Even if we're showing things again, we shouldn't be providing a novel in each one.
4. In order to achieve number 3, the tutorial needs to be expanded, but broken up into learnable areas. I would break this up into a short basic tutorial to get you the initial controls and actions you can perform, with an optional teleporter to the end with an advanced section with individual rooms to learn specific things. (or just different directions for each tutorial, with the basic one leading back to the advanced). A quick way back to the start from any area would also probably be helpful. When there are things that would be a choice, such as weapon type, we should allow people to try out multiple side by side instead of progressing through each.

This is something I'd be willing to tackle in the future, but I got burnt out reading the same tutorial over and over the first time. I also know a lot more about development now though, so I have a much better idea of how I would tackle this. If someone else has more capacity right now and feels comfortable doing any of this, please don't wait for me. I wouldn't mind being involved or providing feedback though when you do, so feel free to reach out on discord if you do.
