### ISSUE TITLE
Beekeeping or renewable source of honey

### ISSUE THREAD

**Issue by Benny-Bear** [CleverRaven/Cataclysm-DDA#57355]
### Is your feature request related to a problem? Please describe.

While discussing mead recipes in the discord, honey came up as not really available to the degree that mead is a viable use of your time with it.
It was also mentioned a source of honey/wax would be great for innawoods.

### Solution you would like.

There's several options that were brainstormed in the discord, and a few questions to go along with them.
Do regular sized bees still exist? If not, what's pollinating everything in cata? As well If mutated large bees are the only thing left and they become a source of honey, will that honey contain toxins?
1.  A craftable box with frames that you can house regular bees in, require some input of some type (flowers, sweet water?, ect) and output honey similar to maple tree taps I suppose?

2. Being able to harvest honey from the overmap bee hives without destroying them, and having them regenerate honey over time. There is a honey scraper item in game already that seems to do nothing, besides being a terrible weapon.

3. Make a bee keeper NPC merchant that has restocks of honey and wax, maybe have it as a traveling merchant to the refugee center or something similar.

### Describe alternatives you have considered.

Would love to hear any other suggestions for this.

### Additional context

![image](https://user-images.githubusercontent.com/29996039/166191114-8bb108b8-f932-4518-8f2d-cd55fde088eb.png)

**Comment by Tearlach** [comment]
If bees of the normal size still exist, there should be wild hives appearing and every spring the ones around should swarm and make new hives. Harvesting these hives should give a bee queen item that rots in a few hours? Placing them in your constructed hive along with sugar water should let a colony take. In the next year they will be able to produce enough honey that you can start to harvest.
You should be able to harvest 2 - 3 times between mid june and mid september. A traditional 10 frame deep box (whatever that is?) will allow you to harvest 80 to 100 lbs of honey.
To support our new bee overlords, we'd need a minimum of two recipes for sugar water of the 1:1 and 1:2 water/sugar ratio. There are more, but seems overkill. Or as an alternative, reduce the yield of the hive with say 50%? and no sugar water required.
We'd need atleast one apiary construction and a bee feeder contraption. The bees would take sugar water from the feeder when in need (due to poor availability of flowers to feed on or having their honey robbed). Sugar water spoils in a few days.
There is a beekeeping suit in the game, not sure if the smokepot is as well. Otherwise we might need to add a recipes for these as well, for the beekeeping suit I'd say we use the medieval variety as I'd assume it would be easier to manufacture for our survivors (and to avoid adding more recipes than necessary). It would consist of a wicker facemask (think a wicker lid) attached to a full body cloth (linen?) suit. Not having these to tend to your beehives should add welts and kill more of your bees (if that is a thing we want to track). More bees would ensure more honey, and when the hive is overcrowded it would swarm (but only in spring) reducing amount of bees by 50% and generating a new hive. Taking honey would reduce bee growth.

I am in no way an expert on anything, I just find bees pretty neat. If someone with some actual experience or knowledge says I'm wrong, I am.

My sources:
https://beekeeperfacts.com/how-long-does-it-take-for-a-new-beehive-to-produce-honey/
https://beekeeperfacts.com/how-many-times-can-you-harvest-honey-in-a-year-is-it-capped/
https://en.wikipedia.org/wiki/Bee_smoker
https://www.heritageacresmarket.com/bee-syrup-mixing-chart/
https://www.seniorcare2share.com/how-long-does-sugar-water-for-bees-last/
https://backyardbeekeeping101.com/feeding-bees-sugar-water/
![beekeeper](https://user-images.githubusercontent.com/4125436/166195276-753555a8-486c-4ca2-a7ef-4254c55139ad.jpg)

**Comment by SamGondra** [comment]
> A traditional 10 frame deep box (whatever that is?) will allow you to harvest 80 to 100 lbs of honey.

Pretty sure this refers to the modern 'Langstroth hive' derived hives (https://en.wikipedia.org/wiki/Langstroth_hive)
They are they ones that allow multiple harvests from a hive, since you can remove the frames (they have to be apart specific distances or the bees won't fit or fix the frames together).
Also fairly sure most of the times you only decap the combs to get the honey out then place the empty comb structure back in the hive because because building a new comb structure takes the bees a lot of energy.

**Comment by Benny-Bear** [comment]
> Pretty sure this refers to the modern 'Langstroth hive' derived hives

Would this type of hive be craftable by a survivor with a book for reference?

**Comment by Atomikkrab** [comment]
A quick google has plenty of DIY build your own beehive stuff, in my opinion it would be a yes, maybe a book on beekeeping might be a good idea

**Comment by SamGondra** [comment]
> Would this type of hive be craftable by a survivor with a book for reference?
Probably - it would be pretty involved though I think, precise distances are needed - the older beehive types are likely better for innawoods stuff, but I have only skimmed the beehive wiki page with what prior knowledge I have.

**Comment by AmarinReyny** [comment]
I'd love for this to be added to the game. Bees are my favorite animals, after all.

I don't have much for suggestions as to how beekeeping/honet harvesting itself would work right now, but I do think that the addition of a couple of apiary map special variants - one overrun with mutated giant bees, and one with non-mutated bees if they still exist in CDDA lore - would go well with the addition of these features.

**Comment by JXMss** [comment]
I actually have a mod with beekeeping in it, but it won't work on the experimental version due to a previous fix (and I haven't found an alternative so far), and due to a game framework issue, it can't detect if the environment the hives are in is suitable for beekeeping.

My solution was to create seed items and planted furniture in the same location, and to use the planting system to change the hives (or rather the "swarm" inside) at regular intervals.
