### ISSUE TITLE
Do not expect bold black to be drawn as dark gray

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#57385]
### Describe the bug

A user just asked for help in the IRC channel, stating they could not see the following colors because they are solid black:  c_black (normal); c_dark_gray (normal); i_black (inverted); i_dark_gray (inverted)

Ignore the black since it is supposed to be invisible, because dark_gray is the actual issue here. https://github.com/kovidgoyal/kitty/issues/197 demonstrates this quite well. Alacritty is affected, too but there is the `draw_bold_text_with_bright_colors: true` option, luckily.

![image](https://user-images.githubusercontent.com/59517351/166433018-877326a2-f199-435b-9852-5be4284e6814.png)

This is a screenshot from kitty, where there is no option to control the behavior. Note the invisible roads, parking lots and weird rivers.

### Steps to reproduce

1. Start the game in either kitty or alacritty.
2. Check your map or any other UI element using dark gray.
3. Go quaff from a fountain or put on a ring of see invisible to be able to see those roads.

### Expected behavior

Dark gray is not bold black. Light blue is not bold blue. There are proper color codes luckily.

Relevant: #880

### Versions and configuration

- experimental

**Comment by PatrikLundell** [comment]
Not sure if it's related, but overmap notes in dark gray show up properly for me, but the note text itself doesn't when the cursor is on the note: it's black on black. Editing the comment shows the info, of course.
I'm using the UltiCa tiles, in case the tile set used matters.

**Comment by NetSysFire** [comment]
The tileset should not matter. If you are using tiles, the problem should not appear at all because this is a terminal specific issue. The SDL stuff is not affected. This is because specific color codes are interpreted in a different way when using specific terminals.

Your mentioned issue may be separate from this one.

**Comment by scy** [comment]
I’m affected by this issue, too. The problem is as old as time itself: Some terminals allowed interpreting the “bold intensity” code `\e[1m` as “bright” instead, giving users 16 instead of 8 foreground colors. However, people who instead enjoy their GUI terminal’s ability to display bold text (like me) will usually ask their terminal to *not* interpret bold as bright – and thus are not able to see some parts of CDDA.

The only option for these users is to enable “interpret bold as bright”, which is usually a global option for the terminal and will therefore make their experience of every other CLI software they’re using worse, but at least they can now see roads and stuff in CDDA. It’s a difficult trade-off.

The real solution would be to either make CDDA output the real “bright” color codes instead of using bold: `\e[30m` is black, `\e[31m` is red and so on, while `\e[90m` is “bright black” (aka dark gray), `\e[91m` is bright red etc.

Maybe introduce some kind of config option for people with terminals that don’t support the 90 to 97 colors so that they’re still able to use bold instead. Heck, make it the default even, I don’t mind.

However, I’m not a ncurses developer and I don’t know how easy it is to make curses actually do the right thing … 🤷‍♂️

**Comment by SJonesy** [comment]
This impacts every terminal emulator that I've tried it in; does anyone handle black with the intensity bit set correctly? I think I'll add dark gray (235?) and update our colors:

![image](https://user-images.githubusercontent.com/1876689/220489041-825b540b-4bac-47c7-9e33-a187e3829992.png)

**Comment by SJonesy** [comment]
Here's how roads will look with 235
![image](https://user-images.githubusercontent.com/1876689/220507869-3f3c910b-14f9-41a3-8374-bd227aa8241e.png)

**Comment by NetSysFire** [comment]
256 colors are supported by every terminal emulator worth using and using dark gray like this should work. Personally I'd maybe make it a tiny bit brighter but it already looks a lot better 👍
