### ISSUE TITLE
Avoid possible epilepsy hazard by keeping Adv Inventory open during brief tasks

### ISSUE THREAD

**Issue by tenth-speed-writer** [CleverRaven/Cataclysm-DDA#57585]
### Is your feature request related to a problem? Please describe.

When performing fast actions with short in-game action times from the Advanced Inventory Screen (such as looting containers), especially when using a bright tileset, the player experiences a severe flashing light effect from the window closing and opening again.

This poses an epileptic seizure hazard.

### Solution you would like.

Don't close or hide the Advanced Inventory Screen if an action the player character takes from the Advanced Inventory Screen requires less than a certain amount of time to pass in-game.

### Describe alternatives you have considered.

The issue is considerably less severe when playing without tiles.

If the above suggestion is difficult or impractical, consider adding an epilepsy hazard notice at game launch and suggest ascii-based graphics or alternative tilesets to users who are sensitive to flashing lights.

**Comment by I-am-Erk** [comment]
This doesn't seem like a tough thing to fix (though that's loaded when AIM and UI are concerned) and I agree it's an accessibility issue for some, though the seizure risk should be low.

**Comment by Jan-Blasiak** [comment]
/confirmed

Though I usually play darker tilesets, I got nauseous few times due to flashing menus and stuff after longer games.

Chewing 5-10 second things causes flashing, moving lots of different stuff via Adv. Menu, shooting with snap-to-target aiming, there are probably few more things I can't remember of the top of my head.

**Comment by I-am-Erk** [comment]
I am inclined to leave this on release blockers because I agree it is a sensory issue for accessibility. However, I am concerned it remains untouched because this is some very hard code. I would really appreciate an educated thought on how difficult this will be to solve, and if it is going to be too hard for stable I will reluctantly defer it.

**Comment by Zireael07** [comment]
Not an epilepsy sufferer, but I agree this is annoying to us healthy folks, and a real problem for sufferers. I think adding a requirement of a minimum action time to AIM close shouldn't be too hard unless there's some weird coupling between the AIM and duration classes preventing the easiest fix (which should amount to just slapping an if)

**Comment by mqrause** [comment]
The menu needs to be closed for activity processing to happen, because the menu itself is an activity. That's what I did with wield/wear from pickup menu and I pretty much copied that from the eat menu. Past me from #53793 says AIM also works like that.
There's also no definite way to distinguish between short and long(er) activities, because many activities don't know how long they'll take beforehand. The only easy option I can think of off the top of my hat is an "epilepsy mode" that simply doesn't automatically reopen menus like that.

**Comment by cathalpern** [comment]
Not being a C++ expert (honestly, am rank amateur, but I know .NET), this looks like it'd be essentially reworking the AIM to have work performed in background task threads... Which seems like an overhaul of the whole menu.
