### ISSUE TITLE
Zombies destroying walls, keycard readers, furniture with loot even with no visuals on the player.

### ISSUE THREAD

**Issue by Sinistrem** [CleverRaven/Cataclysm-DDA#57684]
### Describe the bug

Massive damage to map (Walls, Keycard readers, Loot furniture) even when player or other hostiles are nowhere near.

As seen in screenshots below, zombies were carving entire beelines in concrete, and all that damage happened before I had even seen them for the first time. There were screamers and dogs on the floor below, but no enemies on their own floor. I'm not sure whether screamers scream when they see animals, but they were locked in a room with visuals on dogs, rats and rabbits below them, with no other hostiles.

Additionally I've screenshoted multitude of keycard readers and consoles that were broken by zombies even though there couldn't have been any enemies, In some cases even by zombies isolated in a sealed room, which means they bash readers just based on sound with no visual contact.

I've also added a screenshot of a finale panic room that had a necro zombie inside. The console was broken so I had to use pickaxe to destroy the wall, but by the time I got there every single piece of furniture inside was broken and every single mutagen smashed and spilled on the ground. I'm not sure whether that is a bug, but I don't think that zombies should be able to smash and destroy finale loot. Opening that room only to find everything smashed was disheartening. If that is intended behaviour, maybe remove zombies from the loot rooms with fragile rewards and add extra enemies outside? 
(Interestingly enough, I don't remember seeing so much destruction in loot rooms with scientist zombies inside. Necro zombie specific issue?)

### Steps to reproduce

I'm not sure specific steps are needed, since multitude of destroyed walls and broken keycard readers have been so far a common sight in all TCLs I've visited. But if I were to try and force it I'd:

1. Go to TCL.
2. Descend to lower levels.
3. Either wait for a couple hours or produce loud noises with the entirety of TCL in your reality bubble.
4. Check rooms and doors, taking note of damage even on the floors you haven't visited.

### Expected behavior

According to Maleclypse:

> "I'm pretty certain that monsters aren't supposed to bash down walls unless they can see what is making noise. So even if they hear something making noise they shouldn't smash hard enough to get through reinforced concrete.
> My understanding is that they go towards sound, if they see an enemy and then the enemy disappears they'll bash through walls to get to where they saw the enemy. But if they just hear things, they should run into walls and bounce off and then go wander until they 1. see or 2. hear something with a clearer path."

### Screenshots

General wall destruction:

![smash2](https://user-images.githubusercontent.com/104842796/168409036-ae5ff6e5-6e40-479a-88f8-1bc6a6157b3d.png)
![smash1](https://user-images.githubusercontent.com/104842796/168409037-c3c5ab5c-8cce-4c0c-b44f-baf78454a6f0.png)
![Smash8](https://user-images.githubusercontent.com/104842796/168409025-3f586041-8dfe-4e98-aac9-846618c99ca6.png)
![Smash5](https://user-images.githubusercontent.com/104842796/168409029-e39488d4-0bf4-4530-8e64-284e7ac3539c.png)
![Smash4](https://user-images.githubusercontent.com/104842796/168409031-4528060b-0725-4506-871a-8fae346bc2c3.png)
![smash3](https://user-images.githubusercontent.com/104842796/168409033-c9092f2d-1469-4f7e-a08a-42496803802c.png)

Destroyed keycard readers and consoles in locations where zombies could not see any enemy:

![Smash6](https://user-images.githubusercontent.com/104842796/168409105-c38f3066-0890-4bf3-86a4-9cc8311e0692.png)
![Smash7](https://user-images.githubusercontent.com/104842796/168409104-cd23a18f-65b5-40a9-978a-add5cd55427e.png)

Sealed room with all readers and all furniture inside destroyed (teleported inside to check):

![Inside](https://user-images.githubusercontent.com/104842796/168409163-a75ee4f1-bb89-4042-9a03-6552d0e6e75c.png)

Loot room vandalised by a necro before i could get inside :( 

![Smash9](https://user-images.githubusercontent.com/104842796/168409190-e3d0729a-d50d-4912-b320-52dfc5cb7681.png)

### Versions and configuration

- WIndows 10
- Latest experimental -7c0b8b2 
- Tiles
- English
- Mods: dda, no npc food, no_fungal_growth, package_bionic_professions, blazeindustries, generic_guns.

**Comment by PatrikLundell** [comment]
Making noise tends to be rewarded with noise made by zombies smashing things up. Also, it's long been possible to encounter widespread destruction in labs where hulks have smashed through things (including releasing shoggoths), and I've seen floor disappear in many locations as zombies at a lower level smash up their basement/room, with no chance of visibility even if experimental 3D view had been enabled. Thus, I don't think this is a bug.

However, I agree that it's very disappointing to have your prize trashed before you even get there (happens when you try to find a centrifuge in a hospital unless you get to it early enough that the zombies smashing things up haven't evolved to to more active smashers). Keeping zombies outside of finales and only leave mechanical enemies inside should help (a hulk may still smash through the wall and trash everything, though).

Logically, a mi-go "talking" ought to be capable of driving zombies in a wide area into a frenzy.

My observation of "normal" zombies supports the Maleclypse quote, e.g. gun shots can draw zombies towards a location, but they don't start smashing things up until they see something to attack (and I even have the feeling you need to approach further after they see you for them to bash on the cars they're inside). Note that this may just as well be a proximity thing rather than a visual thing: if the zombies are close enough to see you, they may be close enough to smash things based on ongoing sound cues.

**Comment by Sinistrem** [comment]
The problem is that after a certain period of evolution the amount of hulks and juggernauts gets to the critical mass when any complex you explore is, ahem, "thoroughly pulped" very quickly, before you even have a chance of encountering the culprits. So I'm not sure "It's just what hulks do, deal with it" is a good argument, since eventually the majority of your enemies become hulks of different flavors.

I'm also not sure about gameplay reasons behind making card readers so physically fragile. As a player you never want to bash and destroy them, and zombies tend to destroy them just by sneezing. 
It adds some variety early game when it just means that some card readers are damaged and you usually can just find another door, but it makes late game miserable, especially since mining a single block in TCL can take up to a real life minute and half of the rooms are inaccessible due to damage. 

At least make them easily repairable if the player has high electronics/computer skill, just like you can mend engines in cars.
That way you can just bring some electronic materials with you late game and repair any damaged consoles and card readers.

**Comment by PatrikLundell** [comment]
I'm not aware of having said anything about "deal with it", as I think I've just described how I think it works and that I don't think that's considered to be a bug.

I believe there are a few ways to get past destroyed card readers: cutting through the door (unless these are the invulnerable type, which I don't think they are), dig through the wall, and blow a hole with explosives. That obviously does nothing about the mess that's likely to lie on the other side, but neither does card reader repair.

Another alternative might be the introduction of reinforced card readers in a few select places, along the line of the reinforced vending machines you can encounter. However, I would expect any such card readers to be in locations only where some kind of violence would have factored into the facility location design, which shouldn't be many places, especially given the "lowest bidder crap" vibe of the game.

**Comment by Sinistrem** [comment]
Sorry if I offended you. English is not my native language, so I might've misunderstood you, or misused certain expressions myself.

Yeah I agree that reinforeced consoles/card readers might help somewhat, especially since it would makes sense to install them at high value locations such as loot rooms and armory.

The main problem with getting past locked doors with torch is ammo. The whole oxyacetylene production chain takes horrendous amount of time. Even assuming you magically have all the base materials it would take you about 24 hours of non-stop crafting to make a welding tank which can take down maybe 4 doors, which won't even last you a single TCL, even if you only use it for loot room doors (2 for lab doors, 3 for armory doors).  And perhaps I'm unlucky, but I haven't been able to locate many of them in the wild.

Pickaxe are a viable option which I have been using so far, however the long mining time coupled with the general lag of high density end game location means mining a single door takes over a minute of real time. And because of how noisy it is, it ensures that the other side of the door looks like a mosh pit afterparty.

I also feel like it somewhat devalues your skills and keycards/badges. You level up computers to hack doors, buy/collect Id cards, scrouge for badges to unlock way forward. And then you are welcomed by a broken door realizing you might as well just not bother and use a pickaxe instead. Kinda reminds me of lockpicking, by the time you get locksmith kit and skills high enough to open doors reliably you barely need to open any mechanical doors anymore.

**Comment by PatrikLundell** [comment]
I'm not offended; just wanted to make sure we understand each other.

I get the feeling that the design is going towards slowing progression down (the introduction of proficiencies, for instance), so spending days in preparation for one day of action might be intended (I'm not sure I agree with the approach, but that's beside the point).

I haven't had your experience with lockpicking: I'm using it a fair bit and am nearing perfection. I've never found a locksmith kit, so I'm using home made picks. They rarely get damaged anymore.

I've done one TCL, and I'm probably not going to do another one: they're a maze of key card hunting that doesn't always succeed (some cards were not present in any location reachable with cards found in any reachable locations, despite checking every waste basked and whatnot, and one set was completely useless as there were no card readers for them), and I can't say I'm thrilled with the loot found, as I'm not going the mutation route.

**Comment by ZaricaDemoni** [comment]
Had to cut a lot of doors in the one I explored within the first 10 days in-game, due to security prompting everything in the TCL to break almost every card reader in a few in-game hours. Even worse, after getting through the entire place and cutting doors, I was missing the black card. So the military gear rooms had to be cut, and didn't find it inside any of them.

On the breaking items subject - even without noise or provocation Ive watched undead break things. Mostly cars, being as stealthy as possible you can sometimes catch a group piling onto a car because one zombie hit it, and then the alarm goes off so now the entire town wants to kill this vehicle. And sometimes would break furniture next to them even-though they can walk directly to you in a straight line without damaging things. So they could kind of use a we bit of lowered aggression to furniture and inanimate objects not actively blocking their movement.

As for loot, the black zone tends to have a railway, following it can sometimes in my experience bring you to a fake subway station with a bionics lab hidden inside of it. Just be warned, if you play with dinos you will find augmented and angry dinos everywhere in that railtunnel and lab.

**Comment by PatrikLundell** [comment]
Anything that's placed with a random chance results in a chance that it won't be placed anywhere. I don't think the game has any support for a higher order logic that could keep track of whether something has been placed and place it in a fallback location only if it hasn't been placed elsewhere.

My understanding of zombies smashing random stuff that aren't blocking their progress is that it simulates them stumbling about. You can similarly see them move randomly in a sideways direction. In those cases there is a single smash at something before they stumble on. If that smash sets off an alarm it ought to get the zombies to try to smash their way to the source.

**Comment by MizMahem** [comment]
I just want to chime in and say I experienced this today as well, and it was very frustrating. About half the card readers were busted before I ever got to them, I think I saw maybe *one* get broken while I was on screen, and I had a couple of hulks go through the concrete walls. By the time I go to the lower levels, the ratio was closer to 75-90%. I wouldn't mind the issue if there were only a few I had to bypass or circumnavigate due to this, but at the bottom (and most important) levels it ended up being way to many (I think I had exactly one unbroken black card-key reader).
