### ISSUE TITLE
Clothing made with waterproof plastic layers shouldn't be highly breathable

### ISSUE THREAD

**Issue by actually-a-cat** [CleverRaven/Cataclysm-DDA#57809]
### Describe the bug

It's SOP for our survivors to fit layers of plastic sheeting into their clothing for waterproofing purposes. In a world without perspiration, this makes perfect sense; however, we graduated out of that world a while ago. In reality, plastic clothing is very uncomfortable if you're sweating, but this isn't represented at all in the game, as those clothing items don't actually have a plastic layer and their breathability is good.

### Steps to reproduce

1. Wear kevlar jumpsuit, which is highly waterproof by incorporating a plastic raincoat
2. Be fine in the sun

### Expected behavior

Plastic waterproofing probably shouldn't be a default feature of general-purpose clothing, and when it is included, it should come with appropriate comfort issues. It might be desirable to have a more involved view on water resistance, to represent things like a gore-tex raincoat, which is breathable at the cost of being mostly but not 100% waterproof. High-end crafted gear might use such materials for waterproofing instead of plastic.

### Versions and configuration

Any since #55029

**Comment by fairyarmadillo** [comment]
Aren't there waterproofing sprays and creams IRL? If I was making a survivor suit I'd probably slap a wax or silicone treatment on it rather than gluing plastic to it.

Breathability is a bit weird. I've worn plastic clothing IRL (pants, coats) that covered me completely but was still pretty breathable just by dint of not fitting close to the body. I've mentioned it elsewhere but at least some sweat would evaporate and escape a plastic coat via the sleeves, skirt, and collar.

**Comment by anoobindisguise** [comment]
I forgot to do anything about the raincoat integration with my earlier PR. Removing them altogether may actually be best since they compromise the effectiveness of the armor and the survivor could just wear a raincoat if they really needed to, but they do have the lycra layer which should at least help a little. If the raincoats are removed they'll need added fasteners in their place since I assumed the survivor was repurposing the zipper from the raincoat for the jumpsuits.
