### ISSUE TITLE
Tailoring alternatives need a sanity check

### ISSUE THREAD

**Issue by toweroglass** [CleverRaven/Cataclysm-DDA#57802]
### Is your feature request related to a problem? Please describe.

I know recently recipes were adjusted to use just about any fabric to make basic cloth items. I don't have an opinion on that, but browsing the HHG i'm thinking that the amounts used need to be balanced:
Duster recipe:
![Capture](https://user-images.githubusercontent.com/81603517/169355804-2a1c6d62-e519-405a-9377-ac294f22510f.PNG)

all alternatives are for the exact same quantity. i don't know about how working with different fabrics would differ but within the same material i know that a rag =/= cotton sheets. and the weights/volumes of synth patches, synth sheets, patchwork synth sheets all differ wildly.

### Solution you would like.

I think these need a deep audit to sanity check the alternatives and make sure they make sense. "Sheet" items are much smaller than patches as they allow you to use much more accurate amounts. I assume because you are rolling them off an actual roll of material. so these would need to be increased to be proper, balanced alternatives.

I don't know if the they need to be adjusted to exactly match by volume or some other abstraction of they are worked differently needs to be considered, but I'm certain they shouldn't be one for one.

Also, should rags still be used this way?

### Describe alternatives you have considered.

Not letting you use anything to make anything. I like different kinds of materials having different logical uses and this might be breaking some logic in regards to breathability and things like that.

I refrain from taking a hard stance on changes that have already been approved so recently, but I do feel confident in saying that it needs to be reworked.

### Additional context

First item I happened to click on was the chest wrap. I thought it looked funny so i checked the duster. I'm sure there is a long list of these that need to be looked at.

**Comment by stubkan** [comment]
This is in /data/json/requirements/materials.json

![image](https://user-images.githubusercontent.com/34361592/169570826-6c2db578-d8e3-4307-97ae-d9ad41986a54.png)

I do agree this needs a rework ..   Use more of the smaller components, more of the larger.  

And will making a shirt out of nomex entirely give you protection values?  What happens when you disassemble the shirt?

**Comment by Termineitor244** [comment]
The PR working on fixing at least some of these things is #54256

**Comment by a-chancey** [comment]
#54256 addresses this by removing mixed requirement groups on anything where it would matter. 

Crafted items can't inherit stats/materials from their ingredients, so for items that are enough of a material to impact its stats can only be made with that specific material. You can't make a cotton tshirt out of nomex. If we want a nomex tshirt, it needs to have its own stats

**Comment by toweroglass** [comment]
Apologies if I'm being too lazy to read, did you also address that sheets and patches aren't the same size and need adjusting?

**Comment by a-chancey** [comment]
Yeah I rebalanced all the sizes. Most fabrics have scraps (small remnants), patches (6”x6”) and largely interchangeable “sheets” and “patchwork sheets”, both of which are roughly 12x24 (8 patches in a rectangle for patchwork, sheets are manufactured/woven full pieces of fabric). 

There’s a few outliers - leather and fur replaces sheets with hides and pelts, and Kevlar doesn’t have a patchwork variety. This is due to me reading repeatedly that “damaged or patchwork Kevlar fabric is never as effective as unbroken but trimmed sheets and panels”. Since I couldn’t find just how much less effective *and* there’s no way to influence the final stats of the item based on crafting material, patchwork Kevlar won’t exist until both of those conditions are met. 

Nomex, interestingly enough, can be repeatedly patched with no major issues.
