### ISSUE TITLE
Vehicle shelving weigh 350kg and I think that is a little to much. 

### ISSUE THREAD

**Issue by DramaticHotDog** [CleverRaven/Cataclysm-DDA#57871]
### Is your feature request related to a problem? Please describe.

I LOVE the vehicle building in this game, but vehicle storage has always been a problem. 

The "Vehicle shelving" solves the volume part of the equation but it weighs way too much for being "shelving". I get that It uses 4 cargo carriers in the recipe and it is described as "Several heavy frames," however, I fail to see why that is necessary. 

It becomes more of a problem when you try to make a Boat or an amphibious vehicle that has to float with the extra cargo. 

### Solution you would like.

To make a 4 mm thick steel box capable of holding 1000L you need approximately 186kg of steel. 
_(6 times 1000mm x 1000mm x 4mm steel sheets each weighing 31kg)_

Now we don't need the full box, but we need a bunch of shelves. So a shelving unit capable of holding 1000L should at most weigh about 200kg with reinforcements, ropes, tie-downs and attachment points. If not less. 

**To implement these changes** you would have to change the recipe for the "Vehicle shelving". 
Maby instead of 4 cargo carriers make it 2 cargo carriers and potentially increase the number of ropes, sheet metal, or pipes. 
![Shelf on a car](https://user-images.githubusercontent.com/39046637/169838609-7863247c-399c-49fb-a42c-185c3ca8ea5f.jpg)

**Comment by bombasticSlacks** [comment]
For anyone as confused as I was, it's from blazemod

**Comment by aMegaSloth** [comment]
I don't know about your numbers @DramaticHotDog. It seems like there's an assumption that there's solid steel being used.

I just looked at a home improvement store and found this;
![image](https://user-images.githubusercontent.com/102860442/170174079-c75be18e-bd49-4ed5-9e7c-fd18c348526c.png)


The shelving are certainly heavy duty and I presume is larger than what a cargo shelving is, but similar in style.

The dimensions listed are: 84 inch x 24 inch x 84 inch. that is 169,355 cubic inches, or to about 2.8 cubic meters.

Each shelf is rated 1500 lb, or 680 kg. Since there is no center vertical support, I presume the width can be shrunk, but still keep the same 680 kg shelf rating. The shipping weight is about 140-150 lb, or 70 kg at worst case.

Compared to heavier things that can be mounted;

Heavy-duty frame: 100 kg
200L drum, lets say there's water inside which is a common liquid for mobile bases. 200L == 200 Kg + 20 kg barrel.
Small turbine engine: 113 kg.
