### ISSUE TITLE
Make vehicle degradation optional or remove it

### ISSUE THREAD

**Issue by MoocowTG** [CleverRaven/Cataclysm-DDA#57883]
### Is your feature request related to a problem? Please describe.

With vehicle repairs now consuming resources this feature is no longer necessary. 

This feature doesn't need to exist because it doesn't add any interesting decisions or create interesting gameplay problems that didn't exist prior. Crashing was always punishing and undesirable, and this only adds additional tedium to the repair process by forcing you to part-by-part deconstruct and reconstruct your vehicle to replace an underlying frame.

From a realism standpoint this feature does not hold up either. Welding additional metal to parts (quite a lot of metal given the amounts required for repair) will only serve to strengthen them rather than weaken them, albeit at the cost of some weight.

### Solution you would like.

This feature should at minimum be optional in the same vein as skill rust. It fails to create interesting gameplay problems and fails from a realism standpoint.

### Describe alternatives you have considered.

If it must be kept, parts should be replaceable from the repair menu without needing to deconstruct the whole tile beforehand.

**Comment by Drew4484** [comment]
Additive welding does not necessarily result in a stronger piece of metal, and a garage weld is not going to be the equivalent of a newly cast factory built vehicle frame. IRL, when a frame is damaged, the _entire_ vehicle is typically discarded because of the effort required to restore the original condition.

The gameplay value can be subjective, but personally I enjoy the change. Needing to find supplies means finding a vehicle that works at all is a prize, and the work of making it unique has more value. It means that instead of just driving a tank through the horde,  players are presented with risks: take your vehicle into town and risk damage, or park outside of town and walk or ride a bike in.

**Comment by MoocowTG** [comment]
> The gameplay value can be subjective, but personally I enjoy the change. Needing to find supplies means finding a vehicle that works at all is a prize, and the work of making it unique has more value. It means that instead of just driving a tank through the horde, players are presented with risks: take your vehicle into town and risk damage, or park outside of town and walk or ride a bike in.

The main issue lies in that once you've found a working vehicle and restored it to a suitable point, any collision after that point becomes a point of tedium to repair, and often these collisions are barely within your control. Just recently I drove off a bridge ramp into a horde of dinos that were having a battle one tile from the ramp. They are invisible from the bridge. The vehicle took a ton of damage and can't be restored without days of pilfering other armoured vehicles.

Prior to this change and back when vehicles were more suitable to ramming I've never made a conscious decision to drive through a horde. I don't know what other's playstyles are but as far as I'm aware between "ram through town in your vehicle" or "park it outside" one would only ever choose the former if they intended to ditch the vehicle, so this feature has no bearing on that choice. It only serves to make accidental damage even more frustrating.

**Comment by PatrikLundell** [comment]
I did mow down hordes of zombies (and ants, lots of ants) with a vehicle in 0.E-2 (before the introduction of both degradation and additional supplies needed for most repairs). I now don't hit anything if I can avoid it (and always drive off bridges at minimum or next to minimum speed to be able to avoid almost all collisions).

I don't like part degradation as it adds tedium with no real benefits. Supply consumption is reasonable, although I've considered adding base camp companion crafting for welding supplies due to the frightening speed at which these are used up.
In place part replacement isn't consistently possible due to the fact that you can't remove some of the parts for replacement until you've removed the parts connected to them (everything is connected to the frame, and alternators have to be removed to get at engines, for instance). It doesn't exactly help that frames are frequently damaged parts.

**Comment by MoocowTG** [comment]
> This suggestion was already made and rejected in #54012. I doubt the position of the lead devs has changed much since January. It's been demonstrated that making an unpopular feature optional simply stops all further development of the feature. If everyone plays without it, why bother? The correct solution here is proper game design. Either the original developer agrees that the system has become redundant and asks for its removal, and the senior devs agree, or the feature is changed to make it more relevant.

That is my intention with this issue, in order start a discussion and petition for this feature's removal. I can see no better reasoning for a feature's removal than everyone choosing to play without it. I can mod it out myself, but I think this feature is a step in the wrong direction and harmful to the game as a whole, and now is our chance to remove it before it harms the game as a permanent inclusion.

**Comment by Night-Pryanik** [comment]
> petition for this feature's removal

Just FYI, Kevin said numerous times that this project isn't a democracy, and no amount of petitions will affect the probability of feature removal if he doesn't want it removed.

**Comment by kevingranade** [comment]
> these collisions are barely within your control. Just recently I drove off a bridge ramp into a horde of dinos 

If there is a bug, such as being unable to see down a bridge ramp, we need to address that, not symptoms of the problem.

As for "this doesn't have any impact other than tedium":  
A PR to address the tedium would be welcome, e.g. repair an underlying part, including replacing it, without having to micromanage part removal and re-addition.
This is part of a feature that distinguishes between pre-cataclysm and post-cataclysm vehicle parts. Once that feature is complete, replacing parts from a pre-cataclysm vehicle will tend to be suboptimal, which encourages scavenging whole pre-cataclysm vehicles (and optionally modifying them) instead of rebuiling entire vehicles from scratch.

**Comment by I-am-Erk** [comment]
Commenting just to underscore what so many seem to miss. The solution here is not to remove the feature. We know what this feature is. We want it. It's highly desirable from a balance and incentives perspective, and it wasn't merged in ignorance. If there's a tedium problem with repairs, UI suggestions to fix that would be appropriate. If there's problems hitting something you're not aware of, that also merits an issue post. Petitioning to revert major balance changes because you don't like them isn't ever going to be effective though.
