### ISSUE TITLE
Portal storm options in the options menu

### ISSUE THREAD

**Issue by aMegaSloth** [CleverRaven/Cataclysm-DDA#57989]
### Is your feature request related to a problem? Please describe.

I wasn't sure if this was already planned for 0.G or after since portal storms are probably the newest biggest feature but are there tuning plans to have options to configure them like most world settings?

Figure it is probably a yes, but worth opening an ticket to track this

### Solution you would like.

Seeing configurable options to portal storms like how frequent, duration, intensity outside of JSON editing.

**Comment by Maleclypse** [comment]
Portal Storms will be adjustable via json so that scenarios and even in game effects can adjust their frequency and intensity but as currently planned there will not be a slider that gives direct control.   As a comparison, HP and speed are univesal monster constants that can be adjusted pretty simply with a slider with predictable outcomes.  More complex systems like the portal storms would result in players who moved the slider to a spot that was generally accepted as "exact difficulty" for portal storms and would then be upset when their portal storm experience was higher or lower than what they expected.

**Comment by Night-Pryanik** [comment]
Unlikely. Kevin is against adding more world options, especially if there's already a way to adjust settings via json.

**Comment by PatrikLundell** [comment]
A significant difference between world options and JSON modification is that the latter has to be reintroduced whenever you update to a new experimental version (tedious in the long run, and prone to errors of various kinds), adding additional reluctance to updating (and testing) newer versions.

**Comment by Inglonias** [comment]
This can be accomplished with mods, removing the need to update the JSON nearly as often. I have a mod that does this at https://github.com/Inglonias/Cataclysm-Micro-Mods/blob/main/Fewer_Portal_Storms

**Comment by Night-Pryanik** [comment]
Closing as stale, since stalebot can't do it by itself.
