### ISSUE TITLE
Diary time-of-day gets applied to all entries

### ISSUE THREAD

**Issue by petermorck** [CleverRaven/Cataclysm-DDA#58060]
### Describe the bug

Opening the diary (at least without an accurate clock, don't know if it's different with one) will apply the current approximate time of day (Night, Evening, etc) to all entries.

### Steps to reproduce

1. Open diary and make an entry at some time during the day (without an accurate clock, not sure if it happens with one)
2. Later when some time has passed, e.g. from "Early morning" to "Around midnight", open the diary again.
All entries will now say "Around midnight"

### Expected behavior

The estimated time of day at the time the entry was made should be retained and unchanged.

### Screenshots

Two screenshots of the same diary, first during morning and then later during midnight. The entries were NOT edited between these two points (if that would update the time).
![diary_1](https://user-images.githubusercontent.com/20305709/171287304-ce520d4d-ba5c-4fd7-a7c1-ea1698006b5b.jpg)
![diary_2](https://user-images.githubusercontent.com/20305709/171287317-2d054bdd-1ee1-40bb-a3fd-d047fd77f7e3.jpg)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1706 (21H2)
- Game Version: 9ab7cf1 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Innawood [innawood]
]

**Comment by Inglonias** [comment]
I'm not going to confirm the bug without trying to reproduce the issue, but I think I see what's happening here.

This bug happens because [calendar::get_diary_time_str()](https://github.com/CleverRaven/Cataclysm-DDA/blob/262b7f480a4ebb67508b16e848b8327829701b01/src/calendar.cpp#L866) is using [display::time_approx()](https://github.com/CleverRaven/Cataclysm-DDA/blob/262b7f480a4ebb67508b16e848b8327829701b01/src/display.cpp#L213), which takes no arguments and just tells you what the approximate time is right now.

The fix here would be to make a version of time_approx() that takes the turn the diary entry was created (which is already available in get_diary_time_str) and makes an approximate time string for that.

**Comment by Inglonias** [comment]
Sidenote: If I'm reading the code correctly, you also somehow have the superpower of knowing exactly what time you wrote a diary entry as long as you're wearing a watch, even if you didn't have one while writing the entry. A little strange, but fixing that would be more challenging.
