### ISSUE TITLE
Issues with new main menu

### ISSUE THREAD

**Issue by Night-Pryanik** [CleverRaven/Cataclysm-DDA#58086]
### Describe the bug

- [x] Scrolling down on credits/MOTD to the very end AND further down (for example, press down 3 times after you've scrolled to the very end) make the game require pressing up 3 times before text begins to scroll up;
- [ ] There is no sound of highlighting the menus by hovering the mouse, while manual old-style switching (pressing left or right) produces sound;
- [ ] Popup prompts like when pressing "Delete world" (`Delete world and all world within?`) or `Really quit?` are not mouse-clickable.
- [ ] Tertiary menu options (`Manage world: Foo`) can be pressed by left mouse button, but you can't return to previous menu by pressing right mouse button, like in secondary menus.

### Steps to reproduce

See above.

### Expected behavior

See above.

### Versions and configuration

Windows 10 x64, 0.F-8778.

**Comment by Ezrashaw** [comment]
The scrolling issue is a result of the 'sel_line' variable not being capped at the texts end. I'm writing a pr now which changes both the 'mmenu_motd' and 'mmenu_credits' to vectors instead of plain strings. We really need an internal function like 'fold_and_print_from' that accepts a vector of strings instead of a single string separated by newlines.
