### ISSUE TITLE
Autodoc doesn't advance time while one z-level up.

### ISSUE THREAD

**Issue by Person-Guy1917** [CleverRaven/Cataclysm-DDA#58107]
### Describe the bug

I put my cyborg buddy in the autodoc chair and go up to my car, but the time it takes to finish the procedure doesn't go down unless I'm standing next to the autodoc.
It worked for a while. The autodoc would do its thing and my cyborg buddy would come running upstairs after the procedure. But then it stopped working.

### Steps to reproduce

Put cyborg in autodoc
Go to car one z-level up
Eat delicious food and listen to hard bass and play videogames
Go check on cyborg

### Expected behavior

I expect the autodoc to have advanced time required to finish operation.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.17134.1130 (1803)
- Game Version: 6a66c47 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Stats Through Kills [stats_through_kills]
]

**Comment by PatrikLundell** [comment]
I know that it didn't work when out of the reality bubble when I tried it (0.E-2, I think), but it worked fine to start the procedure on a cyborg companion in one autodoc in a doctor's office and then put my character into the other at the other level. This, I think it's a matter of the reality bubble rather than Z levels.

The description seems to indicate the OP is trying to do this in a lab or possibly a military bunker, and it's quite possible that the car is actually outside of the reality bubble.

To repeat, I suspect this is a reality bubble issue rather than a Z level one. It would be useful if the OP could try the eating and game playing (and possibly hard bass listening, if using a player rather than car stereo) directly above the autodoc, or move the car so that its driver's seat definitely is within 60 tiles of the tile directly above the autodoc.
