### ISSUE TITLE
NPC won't sort faction camp

### ISSUE THREAD

**Issue by YankelMyWankel88** [CleverRaven/Cataclysm-DDA#58173]
### Describe the bug

Telling NPC to sort the faction camp will result in the NPC immediately saying he's done with no work performed. Tried enabling miscellaneous rules to allow npc to pickup items, but then the NPC picks up so many items nearby that he becomes overloaded and makes the bug listed at https://github.com/CleverRaven/Cataclysm-DDA/issues/58163 happen

### Steps to reproduce

Setup multiple zone areas in storage coontainers, cupboards, lockers etc.
Put items relative to zones on the floor inside the evac shelter faction camp
enable miscellaneous rules for NPC to allow picking up items 

### Expected behavior

NPC will pickup items, enough to keep him below his weight limit but functional and move to place them in the various storage zones assigned and organize them accordingly

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.F-3 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

**Comment by andrei8l** [comment]
Please provide your save file

**Comment by YankelMyWankel88** [comment]
[America.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8841077/America.zip)

**Comment by andrei8l** [comment]
You need to a `Loot: Unsorted` zone. Pick up settings do not affect the tidy job.

**Comment by PatrikLundell** [comment]
Expanding on @andrei8l's comment:
Loot sorting currently has the companion (or PC) walk to the items and then teleport them to their destinations rather than actually pick them up and move them, so it's completely disconnected from picking things up, as well as item weights.

Sorting only affects things in Loot: Unsorted zones, so you can safely have piles of things ready for your character without them being sorted away every time a companion is set to sort out things as long as those piles are outside those zones.
