### ISSUE TITLE
Crash to desktop - use in progress disassembly of short string (save game attached)

### ISSUE THREAD

**Issue by matt32106** [CleverRaven/Cataclysm-DDA#58197]
### Describe the bug

when I reactivate this "in progress" job that is 93% complete, cdda crashes to desktop with no error message.
this is 100% reproducible for me.

### Steps to reproduce

1. Load save
2. Use item
3. Choose in progress disassembly of shot string (93%)
4. Wield the in progress ? YES
5. Stop wielding wood axe? STORE IN INVENTORY
6. APP CRASHES TO DESKTOP
7. there is no crash.log file

### Expected behavior

no ctd

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: core-11.1.0ubuntu4-noarch:printing-11.1.0ubuntu4-noarch:security-11.1.0ubuntu4-noarch; Distributor ID: Ubuntu; Description: Ubuntu 22.04 LTS; Release: 22.04; Codename: jammy; 
- Game Version: 5f229e6 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Dark Days of the Dead [classic_zombies],
    Alternative Map Key [alt_map_key],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Stats Through Skills [StatsThroughSkills]
]
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/8841004/debug.log)
[Log Lane Village.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8841008/Log.Lane.Village.zip)

**Comment by toweroglass** [comment]
I was about to write an issue up but I think it's the same issue. I can't really pin point how to reproduce. I've been having the issue when continuing disassembly operations that are at 0%, but when I tried it with something that had progress it worked. 

this has been crashing my game so i just made a brand new world and started a to disassemble something then hit escape instead of wielding it. then when i try to disassemble it the game crashes.
