### ISSUE TITLE
Safe smashing should be an activity

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#58250]
### Is your feature request related to a problem? Please describe.

I got into a doctor's office and there were 4 safes waiting for their prey. It took my strength 5, `homewrecker`-wielding character 162 smashes with 11 `Wait until you catch your breath`'s to take down one safe. That is 368 keypresses, and you have to note when to do what to avoid receiving the pain penalty for overstraining yourself, and avoid smashing the loot that falls from the fallen safe.

### Solution you would like.

`e`xamine safe -> `s`mash it until it's open

### Describe alternatives you have considered.

`s`mash consuming as much time as needed to smash the target down or figure out it's too tough to be smashed.

**Comment by l29ah** [comment]
> with 5 strength you probably would have been better off crafting a makeshift stethoscope. I usually don't smash things unless i know it's fairly likely

it takes a second per smash, while stethoscoping takes half a day and need to be started from the beginning after every distraction

**Comment by toweroglass** [comment]
I don't know the criteria, but sometimes you can stop eat something or drink something and return to it. smashing 162 times takes a lot longer to rest in between and then be completely wiped for the day. also once you have the safecracking proficiency it doesn't take nearly as long.
I'm just talking ideal gameplay so it's irrelevant. I don't think most people would agree this is preferable to just smashing until it's open as most people wouldn't take 162 swings to crack a safe. It would need to be an activity that uses up stamina very quickly and then you will have a half complete disassembly type furniture sitting there that you can't just crack if you wanted to because it is permanently tied to this activity.

**Comment by mkrutov** [comment]
It doesn't have to be deterministic activity though. "Smash till its smashed" is something I'd like to see here as well.

**Comment by toweroglass** [comment]
Would it be a separate key entirely? I use 's'mash for a lot of reasons. Smash a door open, smash a jammed safe, smash a reinforced window, pulp a body, smack the ground to make some noise and draw in mobs in the dark. the first three might be appropriate for that, but in general i don't usually want to begin an activity when smashing a wooden door can take like 2-3 strokes.
