### ISSUE TITLE
Pointlessly convoluted cotton crafting

### ISSUE THREAD

**Issue by dissociativity** [CleverRaven/Cataclysm-DDA#58327]
### Describe the bug

There's no reason to have rag, patchwork cotton sheet and patchwork cotton clothing part as different items with different purposes as it stands.

I understand having a clear cut difference between a patchwork and higher quality cotton sheet for crafting some items, but these currently completely arbitrary units of cotton just make crafting extremely tedious for no gain, as ultimately you're disassembling low quality cotton to get a different type of low quality cotton.

I consider this a bug because remnants of an utterly unfinished tailoring overhaul are still plaguing the game and making a lot of things take substially longer in real-life key presses, with no gain in realism nor gameplay benefit for it.

### Steps to reproduce

The way things are, one needs to disassemble a sheet, then disassemble the patchwork sheet, then the clothing part, then one finally has a rag to craft a bandage.

### Expected behavior

Ideally we just disassemble the sheet, get our patchwork or higher quality units of cotton (cotton sheet), and use that to craft and repair all things cotton without excessive button presses that have no justification.

This is to say we should obsolete "rag" and "patchwork clothing part" since it doesn't really serve any purpose, it would be assumed the character would make the clothing parts out of the patchwork sheets while making the clothing.

I may do this myself when I have time, but I figured the issue worth making in-case others would like to take some of the workload off of my hand, I already had to add these new arbitrary clothing parts to a lot of recipes in the past in order to not make crafting common clothing items immensely painful, there was a time where I'd take apart sheets then suffer from the cold for too long because I couldn't find the elusive "rag" to make wraps to keep myself warm.

### Versions and configuration

Windows 10 x64 
1e56d2a (10/06/22)

**Comment by Zireael07** [comment]
I think differentiating rag vs patchwork piece makes sense (rags are suitable for bandages/towels/ropes etc. but not clothing).

However patchwork sheet vs patchwork piece is imho an unnecessary distinction,

**Comment by Terrorforge** [comment]
Yeah, it's a mess. The whole textile crafting system needs a good seeing-to (#53059).

I believe there are some ongoing efforts to straighten it out, but it's a pretty onerous task since it involves auditing pretty much every single clothing recipe in the game. And it kind of has to be done in one go, because if you do it halfway and then get sidetracked you've just made the problem worse.

It's on the release blocker list tho, so hopefully it gets cleared up for 0.G.

**Comment by anothersimulacrum** [comment]
CC @a-chancey - does https://github.com/CleverRaven/Cataclysm-DDA/pull/54256 do anything to address this?

**Comment by a-chancey** [comment]
If I had answered last night, I would have said it partially addresses it. 

But then my toddler woke up at 2:30am while we're on vacation and I couldn't fall back asleep when she laid back down so I got to work. 

I managed to get rags removed from all of the instances I found in recipes, and migrated rags to cotton patches. 

I finished fixing my failing tests a half hour ago and pushed my commit.

As for the rest of the issue here, see #54256 for more details. Fabric hierarchy is being adjusted and standardized, patchwork clothing parts are gone, and much more.
