### ISSUE TITLE
Make accepted ammo types for various guns easier to understand and make it easier to compare the stats of guns

### ISSUE THREAD

**Issue by geskeca** [CleverRaven/Cataclysm-DDA#58398]
### Is your feature request related to a problem? Please describe.

I think I might not be completely familiar with how guns work in-game and don't know anything about guns IRL, so apologies if I say something that's wrong.

Someone told me that .223 and 5.56 rounds are basically same round, as guns that accept 5.56 will accept .223, but to a player unfamiliar with guns that would be basically impossible to know through the game except by random experimentation since the game does not tell you this.

Some guns use the same type of magazine but accept different rounds, for example you can load a AR-15 that accepts .300 AAC Blackout rounds with 5.56 NATO and only when you try to shoot the gun does it tell you that it can't be fired due to incompatible ammunition, I don't think most players are going to randomly try to shoot their loaded guns with their limited ammunition just to see if it works.

It also makes comparing guns quite difficult if a gun accepts multiple types of rounds, and all the accepted rounds aren't listed on the item description.

### Solution you would like.

Maybe gun descriptions could list all the types of rounds that it is able to fire, and when comparing two different guns it could compare the stats of guns with its various ammo types instead of just the default ammo type?

And when trying to load a gun with a magazine that has wrong ammo type, the game could tell the player that this gun won't be able to fire, before a player goes out and tries to shoot it at a monster.

### Describe alternatives you have considered.

I realize there is a generic guns mod but I like the realistic depth and complexity of this game, as long as there's a way to reasonably learn or infer things.

**Comment by Inglonias** [comment]
The game already tries to do this by coloring various magazines and ammo types in your inventory red and green, though I admit that system is not intuitive and should probably be looked at.

**Comment by fairyarmadillo** [comment]
If I put all these guns and ammunition on a table in front of you, you would be likely to put the wrong bullet in a gun and have a misfire (or worse) happen to you at some point. I personally think it's appropriate to the simulation that the potential for this kind of confusion exists.

An interesting middle ground might be implementing something like this and gating it behind weapon skill or even a proficiency.

**Comment by Griffinhart** [comment]
>Some guns use the same type of magazine but accept different rounds, for example you can load a AR-15 that accepts .300 AAC Blackout rounds with 5.56 NATO and only when you try to shoot the gun does it tell you that it can't be fired due to incompatible ammunition

What should happen in this specific scenario (.223/5.56 in a .300BLK AR-pattern gun) is that it should fail to chamber (5.56 base-to-shoulder length is longer than .300, bolt won't lock up), but CDDA doesn't simulate firearm chambering. As with fairyarmadillo's suggestion, a character with sufficient knowledge should be notified that this puts the gun in a non-firing state.

(The reverse scenario, shooting .300 out of a .223/5.56 gun, should actually blow up the gun and possibly wound the PC.)

**Comment by Griffinhart** [comment]
.223 and .308 are (US) civilian designations/specifications, not used in the US military (there *is* a difference in specification between civilian .223 Remington and 5.56x45mm NATO, as well as between civilian .308 Winchester and 7.62x51mm NATO, but the functional differences are irrelevant in the context of CDDA).

There is no ammo labeled as 12.7x99mm in CDDA, so .50 BMG isn't relevant to the topic at hand.

**Comment by Griffinhart** [comment]
Nothing shows up when searching for "12.7" in HHG or Chezzo's Item Browser, so as far as *ammo names* go, "12.7" doesn't exist in CDDA. It might be mentioned in an item description (IDK if HHG or Chezzo search descriptions), or may be from a mod that isn't packaged with CDDA.

Also, one thing I missed in your previous comment:
>bring out a calculator (program) to convert the numbers yourself.

The problem with this is that the conversions aren't direct math. For example, .223 in \* 25.4 mm/1 in = 5.6642 mm. (This is because .223 Rem naming is basically arbitrary - the cartridge was originally .222 Special, but renamed .223 Remington because - at the time - there were other .222 cartridges. The "5.56" in 5.56x45mm also doesn't refer to any part of the cartridge's dimensions - it's the distance from land to land in the bore rifling.)

Anyways, all of this is incredible minutiae that I don't think is fair to expect any given player to know off the top of their head, even people who are passingly familiar with firearms. CDDA firearms' item descriptions already state magazine compatibility; would it be possible to leverage the same code to state cartridge compatibility?

**Comment by toweroglass** [comment]
It could be information available in the little tutorial screen that you can bring up, but we've got enough information at our finger tips that is getting more thorough everyday. We don't need more bloat right in the item description. I've never handled a gun and have no fascination for them whatsoever, but after playing for many many hours the cartridge compatibility is the least confusing aspect of guns in game.

And before it's mentioned, in CDDA at least, listing magazines is very important because some simply can't be used with particular guns that are chambered for the same ammo.



> I believe I've seen 12.7 on some weapon somewhere, and I believe being able to pair the ammo with the weapon is as important as recognizing the "same" ammo under different names.

I think it's used in Aftershock? It's a shame that HHG doesn't catalog in repo mods the same way chezzo did/does.

**Comment by PatrikLundell** [comment]
It can't be Aftershock, as I've never used it nor looked at it. However, it can be reality, where various vehicle "guns" are described as using 12.7, while I've never seen 0.50, but if that's the case it's not really relevant to the game.

**Comment by natsirt721** [comment]
I haven't used it, but isn't this the sort of issue that the Generic Guns mod (or whatever that turned into these days) was attempting to solve? Paring down all the firearms lingo into something intuitive for non-gun people to use?

**Comment by anothersimulacrum** [comment]
Generic guns migrates all guns to a selected number of "archetype" guns. It also migrates ammo to about 8 types total.
