### ISSUE TITLE
Rebuilt fridge is not smashable or deconstructable

### ISSUE THREAD

**Issue by x-qq** [CleverRaven/Cataclysm-DDA#58401]
### Describe the bug

A fridge rebuilt from an item using "Place Fridge" recipe from the construction menu cannot be smashed or deconstructed

### Steps to reproduce

1. Find "Refrigerator" in some kitchen or another
2. Deconstruct it from build menu ("Deconstruct Furniture") - you get an itemized version of it ("fridge")
3. Now use "Place Fridge" recipe in the construction menu and build the thing.
4. Try smashing the newly built fridge - it does not work (you smash the floor)
5. Try deconstructing the newly built fridge (as in step 2) - it does not work ("You cannot deconstruct this!")

### Expected behavior

1. Rebuilt furniture should be smashable, same as it was in its pristine form
2. Rebuilt furniture should be deconstructable, same as it was in its pristine form

**Also:**

3. Disassembly of itemized fridge requires a drilling quality - I think this should not be the case.
4. Disassembly of itemized fridge takes 5 hours - I think this is too long, 2 hours would be more reasonable

### Screenshots

![fridge](https://user-images.githubusercontent.com/55463047/173401746-69b76054-d2ef-43f2-b0c2-5ee41997aeef.jpg)

### Versions and configuration

- Game version: cdda-linux-tiles-x64-2022-06-12-1440.tar.gz

**Comment by TheShadowFerret** [comment]
1. Smashing
![image](https://user-images.githubusercontent.com/99621099/173403356-f3c4850d-60fa-4805-9dfc-c2559f125a21.png)
2. Converting it to a appliance means you need to pick the "take down appliance" option(which somehow requires bolt turning 2 to do.... 🤔)

**Comment by x-qq** [comment]
The original Refrigerator can be smashed with that character without a problem using a cudgel. Apparently rebuilding it made it sturdier?

**Comment by TheShadowFerret** [comment]
> The original Refrigerator can be smashed with that character without a problem using a cudgel. Apparently rebuilding it made it sturdier?

It also doubles its capacity.... Imma fix that right now.

**Comment by molkero** [comment]
"You don't seem to be damaging the floor." Maybe the appliance cannot be targeted or something.

**Comment by NetSysFire** [comment]
I wonder what happens if you spawn a zombie hulk, will it smash the floor and fall or is the appliance and indestructible obstacle?

**Comment by PatrikLundell** [comment]
For technical reasons, the game makes a distinction between "furniture" and "appliances". The former can support a limited set of functionalities that does not include being powered electrically. The latter can be connected to electrical grids and be powered. Appliances are based on the vehicle framework because the people implementing it could figure out how to make that approach work, but not how to allow "furniture" to be wired up, at least not without more effort than they had available.

Appliances aren't furniture. Fridges you encounter are useless furniture, while placed fridges are appliances that can actually be used. Dismantling furniture and taking down appliances are different orders.
The inability to target appliances is probably not intended, though.

Wouldn't it be glorious with an indestructible washing machine wall? However, a hulk ought to be able to push appliances since they can be dragged.

**Comment by KittyTac** [comment]
Taking down a fridge shouldn't take bolt turning I guess.

**Comment by sonphantrung** [comment]
I think that fridges (as appliances), have the durability of a typical veh part.
