### ISSUE TITLE
Metabolism Mutations' multipliers are wrong

### ISSUE THREAD

**Issue by Xion350** [CleverRaven/Cataclysm-DDA#58411]
### Describe the bug

The mutations Fast Metabolism, Rapid Metabolism, Very Fast Metabolism, and Extreme Metabolism's metabolism_modifiers are very low multipliers.  Fast Metabolism's is 0.5 which I believe means that your body uses HALF the kcals.  I noticed this on a character with Rapid Metabolism which after several days was barely losing any kcals in the debug status, despite eating nothing.  This might also affect the Thirst mutations as well...

https://github.com/CleverRaven/Cataclysm-DDA/blob/9a1002b9442c6bbd02f45f75c9aeab80c1fde1f8/data/json/mutations/mutations.json#L490

https://github.com/CleverRaven/Cataclysm-DDA/blob/9a1002b9442c6bbd02f45f75c9aeab80c1fde1f8/data/json/mutations/mutations.json#L5801

### Steps to reproduce

1. Make a character with Fast Metabolism
2. Note your kcals going down much slower than they should over a few days

### Expected behavior

These are supposed to be negative mutations with their secondary effects (stamina regen) being more of a fringe benefit.  If it's supposed to be faster, shouldn't it be `"metabolism_modifier": 1.5` instead of 0.5?

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1706 (21H1)
- Game Version: 6dc7309 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots],
    Stats Through Skills [StatsThroughSkills],
    Blaze Industries [blazeindustries],
    Alternative Map Key [alt_map_key]
]

### Additional context

It's an easy enough fix, just changing the numbers.  I just want to double check to make sure it is an issue and to figure out what the appropriate numbers should be.

**Comment by Terrorforge** [comment]
They're additive modifiers _to_ the multiplier, not multipliers in their own right. So it's not
[base metabolism] * 0.5 = [bm]/2
It's
[base metabolism] * ([base multiplier (1)] + 0.5) = 1.5[bm]
So if you have one mutations that gives 50% faster metabolism and one that gives 25% it's 1+0.5+0.25=1.75 rather than 1.5*1.25=1.875, altho I'm not sure that's a possible combination right now outside of mods. This is also why the Light eater mod is negative; it reduces you're need to to eat _by_ one third, not _to_ one third.

That's how it's supposed to work, anyway. If it's actually reducing your needed calories in practice, something's fucky. I can't test that right now, but I am running a Fast Metabolism character currently, and her metabolism is definitely reflected in her cardio and stamina, so that part seems to be working at least.

**Comment by Xion350** [comment]
Yeah I went back and tested it on realizing that it might have been other mutations that reduced my kcal needs.  On a base character waiting until midnight from the start:

Starting: 55092
Baseline: 53935
Fast: 53360
Rapid: 53552
Very Fast: 52786
Extreme: 51640

Balancing is another matter.  Rapid is barely a downside considering how much other stuff it gives you and is even less severe than Fast.
