### ISSUE TITLE
Radiation works wrong

### ISSUE THREAD

**Issue by Hirmuolio** [CleverRaven/Cataclysm-DDA#58487]
### Is your feature request related to a problem? Please describe.

The way radiation is implemented is bad.

* Radiation is (sometimes) displayed in mSv. Sv is unit of dose not unit of radiation. The radiation should be measured in something like mSv/h instead.
* Items that radiate when damaged radiate based on their damage level. An item with damage "1" radiates with power of 1. This is not scaled to size/weight in any way nor does it take material into account.
* Items that radiate always radiate at rate of 1/250 g. It does not take material into account.
* Ground and item radiation are sometimes handled at different scales. For suffering the item radiation is divided by 10 while ground radiation is divided by 100 but when you look at them with geiger counter they are both shown as mSv.
* The effects of radiation do not make sense with the geiger counter numbers.
* Geiger ocunter should not be able to measure radiation exposure from person.

### Solution you would like.

Rewrite the system.
Use real units (sivert and sievert/hour) so the numbers have clear meaning.

**Comment by Terrorforge** [comment]
Is there (in real life) any way to measure absorbed dose after the fact? If not, and we're removing the Geiger counter's ability to magically do that, perhaps the player-facing stages of radiation poisoning should be made a bit more granular. Otherwise it feels like it will be very hard to estimate how badly irradiated you are.

**Comment by Hirmuolio** [comment]
There is no way to measure dose after the fact. This is one of the reasons why radiation is such a silent killer.

The only way to measure dose is to carry a meter with you. The meter receives same dose as you and you can read it.

This device is called dosimeter. There is already a radiation badge that is a sort of dosimeter ingame (it changes color after being exposed to X dose). Dosimeter functionality could also be added to (fancy) geiger counter type tool. It can't retroatcively measure the dose but it would show how much dose you received while you had it on.

**Comment by Terrorforge** [comment]
Oh that reminds me; there's a CBM called the "integrated dosimeter". Iirc it's essentially a Geiger counter, so it would need some adjustments with these changes, and should presumably get the actual dosimeter function if/when implemented.

**Comment by Gotdamnmiracle** [comment]
Why noy use the radiation biomonitor as a dose measurement? It's a simple enough scifi concept that I'd reasonably assume something like it could exist in a world of atomic coffee makers.

**Comment by PatrikLundell** [comment]
The atomic coffee maker could probably be constructed using current technology (atomic decay is used to power space probes, so it's a matter of being able to produce enough power in a short time).

In contrast, some kind of scanner that measured the damage caused by previous radiation exposure would somehow measure how much damage the cells have taken. The radio activity doesn't linger: it deposits the energy in the form of damage, not as some kind of poison that can be measured.

**Comment by PatrikLundell** [comment]
Damage can be caused chemically as well as via radiation, so even if you had something that non invasively could measure damage, it still wouldn't detect the cause. Induced radiation levels would likely be below the noise threshold from where you've happened to live and even passed through (and where you're performing the measurement). 

Regardless, the tech level is supposed to essentially be the real world tech plus better batteries and results of that (like power armor and lasers being slightly more advanced). Cyborgs and CBMs are non Earth human tech (and quite possible not human at all), and the mutagens are the result of blob magic, so neither of those count when it comes to setting a tech baseline.
