### ISSUE TITLE
Cotton patch duplication by cutting up shoulder straps

### ISSUE THREAD

**Issue by eturner** [CleverRaven/Cataclysm-DDA#58506]
### Describe the bug

The recipe for shoulder straps is only 3 cotton patches. Yields 18-20 cotton patches by cutting up with a knife.

### Steps to reproduce

Spawn in one shoulder strap and a knife
Cut up shoulder strap
Craft 6 more shoulder straps with results

### Expected behavior

It should not do that lol
Cotton sheets are so cheap now that maybe the recipe should be sheets AND string, instead of sheets OR string. I believe there used to be a disassemble for this too, but I don't assume that's a bug and don't feel strongly about it either way.

### Versions and configuration

Arch linux
cdda-linux-tiles-sounds-x64-2022-06-18-0247
Tiles
English
Default scenario default mods

**Comment by descan** [comment]
I wonder if it should be giving scraps instead of patches - although I don't think it's as simple as that, as it takes 4 scraps to make a patch, so even if it were supposed to produce scraps, 20 scraps would still put you ahead by 2 patches. (Although you only get one thread from each scrap, and it takes 15 per patch, so perhaps not.)

**Comment by hexagonrecursion** [comment]
/confirmed

- OS: Linux
    - OS Version: <unknown>
- Game Version: 97037b0 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by a-chancey** [comment]
I'll look back into this in the next day or so, commenting so I remember to get back to it. 

Iirc the cut up results are more closely tied to a combo of the weight/volume of the item, so I either need to bump up the required items to make it or reduce the item's weight/volume. Patches are smaller than rags were so that may be causing part of the issue

**Comment by strategineer** [comment]
Cutting up shoulder straps no longer produces cotton patches (or anything). This issue can be closed.
