### ISSUE TITLE
Bike Racks Causing Crash

### ISSUE THREAD

**Issue by Consoleable** [CleverRaven/Cataclysm-DDA#58529]
### Describe the bug

Installing a bike rack and then attempting to use it causes warning, examining the vehicle after the warnign causes a crash.

### Steps to reproduce

Install 4 tiles of bike rack on vehicle
Drag bike over to vehicle
try to load bike onto bike rack via the load menu
Trying to interact with the car afterwards causes game crash

### Expected behavior

Install 4 tiles of bike rack on vehicle
Drag bike over to vehicle
try to load bike onto bike rack via the load menu
bike loads with no error

### Screenshots

![image](https://user-images.githubusercontent.com/107653330/174455664-ed49d6c6-e40a-42ab-a7d9-7584be9883d6.png)

### Versions and configuration

OS: Windows
OS Version: 10.0.19043.1766 (21H1)
Game Version: https://github.com/CleverRaven/Cataclysm-DDA/commit/ab490003680fda0330ad643f4753722980cb7fa0 [64-bit]
Graphics Version: Tiles
Game Language: System language []
Mods loaded: [
Dark Days Ahead [dda],
Disable NPC Needs [no_npc_food],
No Fungal Growth [no_fungal_growth],
Bionic Professions [package_bionic_professions],
Translate Complex Dialogue [translate_dialogue],
Stats Through Kills [stats_through_kills]
]
Additional context

### Additional context

DEBUG : Racking task failed. Parent-Vehicle:Electric Car; Found parts size:4

FUNCTION : finish
FILE : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\activity_actor.cpp
LINE : 1137
VERSION : https://github.com/CleverRaven/Cataclysm-DDA/commit/ab490003680fda0330ad643f4753722980cb7fa0

**Comment by a-chancey** [comment]
I probably don't have permissions, but i'll confirm this is still happening with a build from source as of yesterday morning (7/14/2022).

Can't load a boat onto the racks, getting the same error

**Comment by prilr** [comment]
I believe this was fixed recently. At least, I was getting the described crash with a bike in a version from June 25th, and it's no longer present in the latest experimental from Aug 4th.
Couldn't quite pin down what fixed it, though.

**Comment by Twzork** [comment]
Still causing crashes.

**Comment by anothersimulacrum** [comment]
@irwiss I know you've been looking at bike rack stuff, do you have anything to add?

**Comment by irwiss** [comment]
I am messing around bike racks right now and saved aside a savegame that reliably reproduces at least one way to get this debugmsg from vehicle::try_to_rack_nearby_vehicle. [bike-racking-debugmsg.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9438119/bike-racking-debugmsg.zip) - loading that, `e` then `R` will produce the debugmsg mentioned in this issue (not sure if it's the same state since no save game is attached to the issue), but I didn't get to this or racked vehicle merging issues yet.

I do think vehicle::try_to_rack_nearby_vehicle can be significantly simplified; passing in the rack part position and making racks "directional" (like headlights in game, and bike racks irl are) can cut a chunk of complexity in that function, but it needs time to dive into it and i didn't get there yet
