### ISSUE TITLE
gh-pages workflow runs in a loop

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#58524]
### Describe the bug

See https://github.com/CleverRaven/Cataclysm-DDA/actions/workflows/pages/pages-build-deployment, 11k workflow runs for a branch with 160 commits or so. I manually disabled the workflow for now, hoping to stop the loop as cancel would not work.

Credits to perryprog for discovering this and telling me on IRC.

### Steps to reproduce

n/a

### Expected behavior

No loop.

CC @kevingranade

### Versions and configuration

n/a

**Comment by DeeUnderscore** [comment]
Note that the [releases.md](https://github.com/CleverRaven/Cataclysm-DDA/blob/90c1b7b5c1d844592ac34411e178f9c297c64af2/releases.md) page in gh-pages iterates through all the listed releases on Github. It's possible Github schedules a new build for the website whenever the releases list changes, which would be every time a new experimental is pushed. 

This doesn't explain why there's so many failures, though, since experimentals tend to have hours between them.
