### ISSUE TITLE
Read menu get my skills wrong

### ISSUE THREAD

**Issue by matt32106** [CleverRaven/Cataclysm-DDA#58548]
### Describe the bug

In the read menu, CDDA thinks I have mechanics 1:
https://imgur.com/UtW8Uoo.png
But I have mechanics 0:
https://imgur.com/nY8Wtf9.png

### Steps to reproduce

Call the read menu
Look at the Popular mechanics line
Compare to the skills current values

### Expected behavior

Get the right value for the current skill

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: core-11.1.0ubuntu4-noarch:printing-11.1.0ubuntu4-noarch:security-11.1.0ubuntu4-noarch; Distributor ID: Ubuntu; Description: Ubuntu 22.04 LTS; Release: 22.04; Codename: jammy; 
- Game Version: ab49000 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Dark Days of the Dead [classic_zombies],
    Alternative Map Key [alt_map_key],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by G1tR4kt** [comment]
It’s a new mechanic. Practical and theoretical skills. Not a bug.

**Comment by matt32106** [comment]
Read menu says CURRENT value is 1
Skills menu says CURRENT value is 0
BUG

**Comment by G1tR4kt** [comment]
Can you show a screenshot of a skill description for mechanics? If it says that your theoretical knowledge is level 1, it will do so in books menu.

**Comment by matt32106** [comment]
My point is that the read menu says it uses the CURRENT value, not another hidden value. It clearly does not.

**Comment by PatrikLundell** [comment]
The implementation is somewhat odd and the display is somewhat obscure.

The game now has theoretical knowledge and practical knowledge of a skill, and reading books increases the former, but not the latter, which is increased by actually using a skill practically. Practical skill is also subject to decay ("skill rust"), while the theoretical knowledge isn't (as opposed to real life where anything learnt for an exam is wiped from the memory the time the student leaves the examination room).

The skill display shows the practical skill level in blue if it's the same as the theoretical level, and light red if it's lower (it can never be higher).

If you examine a skill by placing the cursor in it, the detailed display of the skill at the top shows both the practical and the theoretical skill level.

It can also be noted that skill requirements for crafting uses the practical skill level, not the theoretical one.

**Comment by matt32106** [comment]
So if I understand correctly, you start with 0 P&T skill. You read a book that brings your Tskill to 1. Then rust occurs which brings your Pskill to 0. You pick up the same book as the first time and then suddenly you cannot train again to level 1 because your theoritical skill is already at one?! If it's not a bug then I don't know what it is.

**Comment by PatrikLundell** [comment]
It's design, not a bug...

After reading the book you're still at a practical skill of 0, because you haven't actually practiced anything by reading. You can read any number of books on weight lifting, but you're not going to build any muscles until you actually train them. However, the reading should improve your ability to train them in a more effective and efficient manner, and so it will be faster than if you just fumble about.
When practicing a craft you increase both practical and theoretical knowledge, but the practical knowledge increases faster than the theoretical one, and so it catches up, and at that point the practical knowledge increase slows down to the slow increase rate of the theoretical knowledge. Thus, reading to increase the theoretical knowledge before you practice it up to that level is faster than pure experience based learning. The designers wanted interleaving of theoretical and practical training to be the most effective way to train something, although the implementation doesn't quite capture that.

Reading to gain theoretical knowledge is capped by the book read, and so will train you only to a given level (but different books training to the same level may contain different recipes, and so may have an additional use and thus value). Practical training likewise is capped as to the level they can train a skill to, which typically is the level above the level of the recipe (so grinding a level 1 recipe can get you to level 2 in both theory and practice, but once there the theory won't go higher, while the same recipe can be used to recover from skill rust). This isn't limited to actual recipes, but also affects things like constructing/repairing vehicles, foraging, and, I think, dismantling items.

You may think whatever you like about the design the core developers came up with to try to emulate real life learning, but as far as I know the implementation matches the design (apart from any actual bugs that might lurk in it). Thus, you can say the design is flawed, but you'd need some rather strong arguments based on real world behavior to get the core developers to change their minds (and past experience indicates that nagging and ranting will cause them to be even more reluctant to listen to that person's arguments).

Note that I'm trying to explain the situation, not express any opinion on the selected design.
