### ISSUE TITLE
Refugee camp spawning right next to refugee camp, along with all the missions and same NPCs.

### ISSUE THREAD

**Issue by descan** [CleverRaven/Cataclysm-DDA#58593]
### Describe the bug

A refugee camp spawned just to the north of the directed-by-evac-shelter camp. I assumed this would be one overrun by zombies, sort of a world-building exercise - instead, I found a direct clone of everyone from the original refugee camp. It wasn't exactly the same - the orientation was different, and the back-bay zombies were different. But I was able to take on the same missions as from the original refugee camp, including clearing the back bay. 

### Steps to reproduce

Load the save, see the two refugee camps right next to each other. Check missions, see some from one, some from the other.

### Expected behavior

There not to be a direct clone of the refugee camp, at least not so close - as I said, I would expect any other camps would be over-run as explanation of why *this* (meaning the one you're directed to) camp is important.

### Screenshots

![image](https://user-images.githubusercontent.com/4212389/174730605-66a2c97f-4bf2-4bc5-b960-58ae7967ccdd.png)
![image](https://user-images.githubusercontent.com/4212389/174730651-86bb4ee3-ae0b-403c-93a4-96bbcd75d07e.png)
![image](https://user-images.githubusercontent.com/4212389/174730680-09855d39-9f81-4f1b-8894-cc11a7195813.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22000.739 (21H2)
- Game Version: d01948f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Alternative Map Key [alt_map_key],
    Translate Complex Dialogue [translate_dialogue],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Generic Guns [generic_guns],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Tamable Wildlife [Tamable_Wildlife],
    No Fungal Growth [no_fungal_growth]
]

### Additional context

I assume something like this is already known, although maybe it just hasn't really happened - what are the chances they'd spawn right next to each other? At any rate, I figured it should at least be noted as something that... While maybe not technically a "bug," is certainly not the most immersive experience.

**Comment by descan** [comment]
(player note: I just noticed that there's a mi-go encampment to the north of the cloned camp, so I assume it's not gonna last all that long. At any rate, the save file, if it's important:
[Bishop Hill.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8946347/Bishop.Hill.zip)

**Comment by PatrikLundell** [comment]
It's a known design issue. It's possible to make these locations unique, but doing so would usually make a significant number of these locations unavailable in most worlds because they get overrun, can be reached only by punching through paths that are overrun by powerful factions, can be reached only by traveling along a very long detour because of intervening water and forests (with no bridges and roads). In addition to that, there is the risk that the walking in a random direction from your starting point (which might not be an evac shelter) simply causes you never to encounter them.

The above is among the reasons these "unique" locations aren't.

What's needed for these locations to actually be unique (in my opinion):
- A guarantee that there aren't any area threats (mycus, triffids, ants, etc.) within a threat area around each of these sites.
- A guarantee there is a road connection between each of these sites, plus better road generation in general so that locations actually are connected. There's a need for a network that allows you to take a detour around an infestation, rather than having the single connection blocked.
- More bread crumbs between the locations so you can actually find them. That situation has been improved gradually, but there's more to be done, especially if you don't start in the evac shelter.

A possibility would be to have the buildings exist in multiple instances but "resolve" only the one first visited into the "real" one, with the others split between "generic" versions (some random people, but not the specific quests), and overrun versions, or possibly version 1, version 2,... of things that need not be fully unique (there ought to be multiple refugee centers constructed, for instance). However, someone would have to implement these things.

**Comment by RAldrich** [comment]
Couple of thoughts:

1. **Sites being overrun.** Is the issue with area threats that the areas don't know about the special site layout, and so you get ants (or whatever) spawning inside the fortifications? I can imagine that the Mycus and Triffids are particularly bad here, in that they cause xenoforming to occur and the NPCs (and also the player) don't really have any capacity to resist that.
2. **Guaranteed access.** Why is this needed? Yes, you want people to be able to access the content that we spend all this time building, but why should it be guaranteed in every world? Like, so what if you have to find a way through a zombie metropolis to get to the center? Isn't that part of the fun of the game? The alternative to making access easier/guaranteed is to make sure the player has access to tools and gameplay elements that let them overcome whatever obstacle is preventing access. And if players want guaranteed access they can always pick a starting scenario that places them there.3
3. **More bread crumbs.** Yes, absolutely needed. More logical mapgen algorithms (as in, conforms to real-world understanding of how cities are laid out and connected) would probably help here too.

**Comment by PatrikLundell** [comment]
1. No, I don't think I've seen any area center sites placed inside a target's borders, but that doesn't matter much when they can appear right next to the border, causing their area to cover most or all of the facility.
Here is an example where a mycus tower has been spawed two tiles outside of the Isherwood far:
![Screenshot (246)](https://user-images.githubusercontent.com/22739822/175804216-6dc77294-8c87-448e-800f-e838e7f6b4e5.png)
The "F" notes show where I've seen Fungaloids (the locations may be a tile off). Complete the circle and you'll find most of the location's area overrun by them.
The mycus is the worst threat both because they cover the largest area and because they destroy the terrain,
2. The problem with having access to a faction cut off (or it being destroyed) is both that you get denied everything related to that faction, and the bread crumb quests to find them being stalled, blocking off the rest of the quest chains. Access to (potentially broken) quest locations is an issue mostly because they deny the player access to the rest of the quests in that chain. The quest location access issue can be worked around by allowing players to park of fail quests so they can proceed with the following ones that are possible to perform, or possibly get alternative locations when it makes sense.
I don't have any problem with quests being hard so you have to return later, but I do have a problem with quests being impossible. If the Necropolis reference is what I think it is, then I've never encountered it, but that's supposed to be an end game quest, so having to fight your way to the location is reasonable (as is other quests that take you through zombie infested territory), but having you fight through only to find that you can't actually perform the quest because the ones you're supposed to talk to have killed themselves against the Mycus is not good.
An early quest that sends you to a heavily zombie infested area, usually requiring dealing with city zombies as well is the blood analysis quest. It suffers from frequent destruction of the target equipment, but has the very good saving grace of having alternative solutions (i.e. finding said equipment on your own elsewhere). Thus, you can be stalled, but won't be blocked forever.
I'm not aware of any starting scenarios that start you in all factions at once...
3. More breadcrumbs in the current situation actually makes the access situation worse, as bread crumbs tend to send you to factions on quests, and if that faction is cut off or destroyed that whole quest chain is cut off.  If it's toward the end of the chain it might not matter that much, but an early dud may largely cripple your questing for the faction.
