### ISSUE TITLE
Ferals- Expanded Loot Diversity

### ISSUE THREAD

**Issue by Gotdamnmiracle** [CleverRaven/Cataclysm-DDA#58607]
### Is your feature request related to a problem? Please describe.

Related to discussion in issue #58581.

Currently ferals only drop what they were wearing and whatever flavor of weapon they were carrying with a few exceptions.

To properly show feral humans surviving in the apocalypse, as well as make them more interesting, what should their drops and loot tables look like?

### Solution you would like.

Things I can think of off the bat...
- Food or drink present on some ferals would be a nice addition as it shows they are not simply starving, but rather scavenging, just like the survivor would.
- Crafted weapons perhaps? I believe the cunning feral carries pipe spears, which implies they are clever enough to modify equipment better for combat. this could include things like javelins, possibly some basic bows and arrows, nailbats, as well as somewhat modified or rudimentary armor (plated leather jacket, tire armor, metal armguards).
- rudimentary traps. As I suggested in the other thread, I believe cunning ferals could set up basic traps to use on the player.
-  Trophies? Not sure if appropriate, but perhaps ferals carrying skulls, necklaces of ears, teeth, or whatever could add to the atmosphere. may be a bit too silly.

### Describe alternatives you have considered.

Ferals not needing to eat due to blob magic and are too stupid to craft due to brain sick.

### Additional context

Added benefit is this is a way to give the player mid weapons and armor that don't get used too often, rather than speedrunning survivor armor and rifles.

**Comment by liminalRoar** [comment]
I am very interested in developing the idea of tiers of ferals. Lesser, primitive ferals dying off early game perhaps, while stronger ones survive and adapt or "evolve". Developing nests to survive in and even hunting in groups.

Some more thoughts but i especially love the idea of some ferals being more neutral to the player and seeking to run and hide rather than engage unless the player gets too close or damages that enemy or any ally. Ferals developing "tribes" similar to scavengers in Rainworld would be very awesome. Not that we need to go so far as having a complex reputation system with various tribes, adding some dynamic behaviours to a faction like this would go a long way towards making them unique. 

Sophisticated ferals could be both highly competent opponents and avoidable as threats if you play your cards right.

**Comment by fairyarmadillo** [comment]
I don't think anything should be done to imply that ferals can form primitive societies. I am not even sure they're making their own tools once they cross the line.

**Comment by toweroglass** [comment]
i think their loot table could be expanded to cover the same things that zombies hold. currently they have just about nothing in their pocket.

but we already have feral soldiers, feral preppers, militia, security, etc.

**Comment by liminalRoar** [comment]
Serious question but with how much Ferals have been expanded on this year is there room for them becoming a dedicated faction themselves? They can be allied with zombies and essentially fight alongside, but i feel like for classification there should be a distinction.
