### ISSUE TITLE
Feral faction separate from Zombie faction

### ISSUE THREAD

**Issue by ghost** [CleverRaven/Cataclysm-DDA#58627]
### Is your feature request related to a problem? Please describe.

Ferals should be represented with their own Faction.

Ferals have been expanded more than maybe any other mob type recently and hopefully feral life will continue to become more... fleshed out.

Inspired from conversation in #58581 and #58607.

### Solution you would like.

Create a new Faction for Ferals. This will be separate from the Zombie faction but functionally the same for now. The Zombie and Feral factions can be allied, and are viewed as the same faction from nearly all in those factions.

This is most helpful in classification and distinction for the player and gameplay.

Depending on how the feral discussion and lore evolves and how enemies are expanded in the future, this could be a useful separation.

### Describe alternatives you have considered.

Possibility of Factions having branches or sub-factions. Where Feral can be a sub-class of the Zombie faction. This could also be useful but probably requires even more work. Not sure which is better long term.

### Additional context

Trying to find all the relevant lore and official info on ferals but it seems a bit sparse still.

**Comment by toweroglass** [comment]
What would this functionally change?

**Comment by descan** [comment]
I'd lean towards this being a good idea (from a player perspective) IF, in the long-term, ferals continue to develop as monsters and as a distinct-but-allied faction. If ferals stay in-line with what they are now (basically zombies that you can't easily butcher), it would add a needless distinction, but if ferals continue to develop in the direction as in those conversations (feral nests, moving/marauding feral bands that loot, etc) then it would make sense.

So a year down the line, if ferals have developed in a distinct direction, this would be a good call. If they haven't? Then this would have been a bad move. (Of course, making this move might well encourage others *to* develop ferals into a distinct faction...)

**Comment by toweroglass** [comment]
ferals are humans and just like npcs they ressurect. if you haven't been bashing them you should.

**Comment by Gotdamnmiracle** [comment]
I don't think there's been any confirmation in the lore that they are "barely more sentient than zombies" and that there's been a lot of speculation about this just because they are implemented functionally as zombies that also can open doors and drop clean clothes. I think that this is a symptom of them being WIP rather than an end product.

**Comment by toweroglass** [comment]
> I don't think there's been any confirmation in the lore that they are "barely more sentient than zombies" 

I've seen devs respond to these same conversations where people proposed them being "tribal" and the consensus seems to be they are not capable of that. they've completely given into the blob and are all aggression. every indication is that they are still alive but have lost their "humanity".

several zombies can open doors. Zombie masters, zombie necromancers, zombie necro-boomers. Opening doors does not a not-zombie make in this game.

**Comment by fairyarmadillo** [comment]
Ferals are just zombies with extra steps. Putting them in their own faction would give people the wrong idea.

**Comment by anothersimulacrum** [comment]
This conversation would do well with a review of the [design document](https://cataclysmdda.org/lore.html). The `Cognition after the Cataclysm` section in particular.

**Comment by liminalRoar** [comment]
I see, that goes much more in depth than https://cataclysmdda.org/lore-factions.html which just mentions "feral" once in passing. I had initially thought the ferals were merely crazed humans that managed to blend in with the zombies, but not realizing they were affected by the same condition just on a different level.

The roster keeps growing a lot, as it should. I think an organized in-game compendium for enemies would help a lot, especially for newer players. We have the factions menu, but i think this can be more developed and clear. I think the distinctions of factions and subfactions could be useful, along with species, and maybe other groups or categorizations in the game.

-Factions - the main group identity something belongs to. (Humans, Zombies, Mi-Go, Triffid, Creature/Animal, etc)
-Sub-Factions - Ferals would be the current prime example i suppose. The are a substantial and unique subset of zombies.

**Comment by Gotdamnmiracle** [comment]
> This conversation would do well with a review of the [design document](https://cataclysmdda.org/lore.html). The `Cognition after the Cataclysm` section in particular.

This document outlines a hierarchical order to ferals. I think it remains feasible that they be organized by the "feral masters" to better execute attacks.

While it may be impossible to form a complex plan, it requires vastly less cognition to execute a command (i.e. "go over there"). This is something that can be easily performed by children before they learn to speak, dogs and some birds, and individuals with damage to parts of their brain (both including whole-brain diseases like alzheimers and trauma to specific locations such as the case study HM).

Other than people not liking it, why would they NOT organize into groups to complete tasks? The zombies already do this in a meta sense.

**Comment by fairyarmadillo** [comment]
Ferals are part of the zombie group. They organize in the same mindless way that zombies do, alongside the zombies. They aren't really distinct entities except that their brains haven't completely turned to goop yet and they lack the advantages that proper undeath provides.

**Comment by Gotdamnmiracle** [comment]
> Ferals are part of the zombie group. They organize in the same mindless way that zombies do, alongside the zombies. They aren't really distinct entities except that their brains haven't completely turned to goop yet and they lack the advantages that proper undeath provides.

Did you read the document? It literally describes ferals as intelligent as NPCs.

**Comment by Gotdamnmiracle** [comment]
Okay. You still didn't answer my question. Why would intelligent ferals not organize others into groups? It's literally one of the most effective survival strategies. And the easiest way to kill a threat.

**Comment by fairyarmadillo** [comment]
Because it hasn't been coded yet. There's long been discussion of giving zombie masters and creatures like the melded task force more complex behavior and ability to direct others.

I assume implementation of NPC-like ferals is similarly waiting on better AI or some kind of NPC monster system. Important stepping stones would be things like monsters being able to direct the activities of other monsters both inside the reality bubble and across the overmap, a better and more reactive horde system, proper use of items by monsters, and dynamic base-building activities.

The cunning ferals are the second variety, the "about a third". They don't make tools, they just have them and know how to use them. They're not the "very dangerous tenth." We don't have those yet because there's a lot of very complex work that would need to be done to get them to do even basic stuff.

**Comment by PatrikLundell** [comment]
Actually, I believe there is a single feral that might actually be the somewhere near the last level, namely the feral child. Similarly, the zombie masters (etc.) could be considered to be the lowest end of "intelligent" zombies (haven't encountered the melded task force).

The reason intelligent ferals wouldn't band together is that they'd not be able to find each other, given how rare they are.

I'd say the "cunning ferals" are within the second category, together with feral security guards. If they're supposed to be within the highest tier, they're probably two orders of magnitude too common.

**Comment by fairyarmadillo** [comment]
> Actually, I believe there is a single feral that might actually be the somewhere near the last level, namely the feral child. 

That's not a feral, it's a mutant that was given too much Alpha mutagen. It's hostile to zombies.

**Comment by PatrikLundell** [comment]
I stand corrected!

**Comment by fairyarmadillo** [comment]
My take is that a good hypothetical example of the third type of feral would be like, you have a military base that's been overrun and most of the soldiers are zombified. A few of them are feral and still have guns, and there's one super intelligent feral that has put on a bunch of stolen medals and calls himself the general and goes around setting booby traps and stuff to defend his base from "the enemy". He might even be able to influence the others a bit and keep them from wandering off, but he's really the only one there who is anything more than a drooling monster. Bonus points if he sets up a phony broadcast to lure in victims like the soldiers in 28 Days Later did.

This is not thematically dissimilar to the mutant child situation in TCL, where he's doing a Lord of the Flies thing with all the other mutant test subjects, and it _is_ confusing to players that different monster types would be exhibiting similar behavior, but I guess it makes sense that the cataclysm would be chaotic and hard to understand.

**Comment by Gotdamnmiracle** [comment]
Alright. I think we're on the same page. What I'd like to see is a small handful of feral enclaves (probably represented by map specials, or as a "boss" at the end of a dungeon, much like the melded taskforce) that are led by an intelligent version of the ferals while the others just populate the hordes to fight you.

Incidentally, I like the idea of the military base you suggested. Really, my only issue is I'd like to see ferals acting less like free agents- as we already have a lot of that. I imagine that, yes, that may change with AI additions.

**Comment by liminalRoar** [comment]
getting into more philosophical, technical questions. What are the reasons most humans become zombies and others become ferals? the design doc only mentions that varying percentages become what they become. One possibility is that the mentally strong or strong in spirit seccumb less and retain slight amounts of personhood or humanity or at least living status. 
Another possibility is that if these affects are intentional by the blob and not mere accident from exposure - than the blob have a different purpose for the ferals, or the ferals are an experiment. Or perhaps the blob uses the way both zombies and ferals are infected and changed as means of experiments to achieve goals, whatever those are.

Either way, they are still distinct branches of the phenomenon.

**Comment by PatrikLundell** [comment]
ALL dead humans become zombies unless prevented from rising (pulping in practice, stuck in enclosed spaced by game mechanics, and post mortem blob purification in theory). Ferals haven't died (yet), but are sufficiently brain damaged or under blob influence to be recognized by zombies as one of their own.

The lore documents indicate why some humans become feral, while other retain more or less sanity (Psycho's are probably just above ferals on that scale).

**Comment by liminalRoar** [comment]
If you see where the document indicates  why some humans become ferals can you quote it? Because i don't see why, just that it happens.

**Comment by Gotdamnmiracle** [comment]
I would concur with above. I think it has less to do with will and fuzzy things like "strength of mind" and much more to do with exposure, genetic predisposition, body size, and possibly proximity to portal event- as the cataclysm itself is a two-ingredient dish, so to speak. I think the difference of the gradient of blob effect is probably a physiological one.

I do stand by my theory though that it may be that the "force" the blob used to cause the cataclysm probably looked a lot like acute encephalitis (killing many folks or making them vulnerable) with some slight activation of certain centers of the brain. My guess is the limbic system and a deactivation/reduced activation of the amygdala.

That makes the most sense to me how you end up with so many mostly intact zombies roaming around. Rather than most people dying of acid rain or portal creatures it was severe swelling of the brain (which is pretty easy to do all things considered. Viruses, bacteria, and fungi manage to do it rarely, but consistently across populations).

**Comment by liminalRoar** [comment]
I don't like the idea that is is will or strength of mind, i am just wondering what the current explanation is, because it didn't seem clear.

**Comment by PatrikLundell** [comment]
Main document linked:
:
> Cognition The blob has a potent, albeit often subtle, effect on human cognition.

In about one quarter of the population, changes are basically unnoticeable.

For about half the population, the blob causes an increase in risk-taking behaviour, ranging from mild unsafe practices all the way to people attacking hordes of zombies with a stick. This effect may be permanent or may be temporary, and resolves at varying speed by person. Some may be strongly enough affected to be almost indistinguishable from ferals, but not aligned with zombies.

The remaining quarter see a heavy increase in aggressive, violent behaviour, often completely out of character. The worst of these, about 1/20 of the population, become “ferals”, a form of living zombie. These ferals are not seen as hostile to zombies, and mutate naturally with time just as zombies do. Ferals still maintain a degree of human intelligence, depending on how severely affected they are… Some can remember tool use, for example. Ferals led to a great deal of confusion over whether the reports of the dead rising were true, as feral behavior is very similar to that of zombies. From an out-of-universe perspective, ferals are similar to “rage virus” zombies as seen in 28 days later, but adapted to our lore, and as such are considered zombies internally.

“Blob psychosis” is an out-of-game term for the increased violence experienced by this quarter of the population. Nobody in game calls it that. Strictly speaking it’s not a psychosis, but that term seems to have stuck in our game discussions.
:

**Comment by Gotdamnmiracle** [comment]
Yep. That can be explained pretty simply physiologically. Increased risk taking and lack of fear are characteristic of reduced amygdala activation.

**Comment by liminalRoar** [comment]
I had read through that, it is rather vague about "why" exactly it affects different ppl different, simply stating that it does. Which was my point. Which is why i was asking before if there is some direction the lore would go (or stating that there is room for how the lore can go) about why ferals differ from Zombies.

It is relatively clear that the zombies are more affected by something than the ferals, but like i said looks like there is room to provide greater detail.

**Comment by liminalRoar** [comment]
My motives for wanting to make this clear are simply that it can explain how ferals were affected differently or less so, hence retaining a living status and some mental capacity. and that that can explain why they would function a little differently than standard zombies. and it can give reason why we should differentiate them a little more. That ferals are not full zombies, or are different enough that their paths and goals differ (even if still nearly non-existant)

**Comment by fairyarmadillo** [comment]
The Blob is operating on a level that is far beyond human understanding. No pseudoscientific explanation for ferality is needed and any given will fall short. An Elder God with transdimensional powers and access to infinite energy found earth and as a result, almost everyone went mad, died, and came back as a zombie. The most high tech labs in the world failed to understand the process even as it happened to themselves and their test subjects. Super advanced cyborgs from an alternate earth barely seem to understand the process any better, chalking it up to their version of Satan despite their enormous technical and medical skills. It's not magic, but it is well beyond any scientific explanation the player would ever encounter.

**Comment by PatrikLundell** [comment]
Again, zombies are affected by something that ferals aren't, namely death. Zombies don't have any real brain functions (which is shown by some of them not even having a brain anymore). The distinction line is between feral and non feral humans.

**Comment by Gotdamnmiracle** [comment]
Seems like a good place for ingame lore to explore. Scientists doing experiments on the mechanism for the increased aggression, etc. I imagine ferals weren't discovered only after the cataclysm.

**Comment by fairyarmadillo** [comment]
The ingame lore exists. The scientists tried their best, came up with nothing, and then died.

**Comment by liminalRoar** [comment]
alright, i dont know why you have to dislike everything of mine. I am simply trying to explore the existance of ferals more and see what options we have for the future of zombies and ferals. I understand if you disagree with my take on it.

**Comment by Gotdamnmiracle** [comment]
> The ingame lore exists. The scientists tried their best, came up with nothing, and then died.

The fully discovered the zombification effect. I know of nothing referencing ferals.

**Comment by fairyarmadillo** [comment]
> alright, i dont know why you have to dislike everything of mine. I am simply trying to explore the existance of ferals more and see what options we have for the future of zombies and ferals. I understand if you disagree with my take on it.

You're making things up which are contrary to established lore. I don't like all of the lore, but it needs to remain consistent.

**Comment by liminalRoar** [comment]
i am proposing suggestions for how to develop things more. Ferals aren't covered much, other than that one section in the doc. And they have recieved a lot of attention in expanding varieties this year. So i would like clear direction for how things are heading,

**Comment by Gotdamnmiracle** [comment]
> > alright, i dont know why you have to dislike everything of mine. I am simply trying to explore the existance of ferals more and see what options we have for the future of zombies and ferals. I understand if you disagree with my take on it.
> 
> You're making things up which are contrary to established lore. I don't like all of the lore, but it needs to remain consistent.

I feel like your interpretation of lore is incorrect and rigid. Really unless one of the main contributors wants to weigh in then no one is any more right or wrong. That's the funny thing about this stuff- it can change.

**Comment by liminalRoar** [comment]
I understand there is a general outline for the game, and aspects which are rather concrete. But factions are still somewhat fluid and that is why i want to weigh in and just give my input that i like the idea of ferals being distinct from zombies (since the original idea is that currently they are represented in game as merely in the zombie faction and are not differentiated in game that i know of)

If you can give me some reasons why you think it is important they are treated the same then i want to hear it. Also i dont mean to start an argument or anything, just looking for helpful dialogue on ideas or counter arguments so thanks again for weighing in.

**Comment by fairyarmadillo** [comment]
> > The ingame lore exists. The scientists tried their best, came up with nothing, and then died.
> 
> They fully discovered the zombification effect. I know of nothing referencing ferals.

There are several lab snippets describing people becoming irrational and even killing each other prior to death, and a series which describes XEDRA's perspective as the Cataclysm unfolded. The news snippets are also illuminating.

**Comment by fairyarmadillo** [comment]
> factions are still somewhat incomplete

You have not adequately demonstrated this. I'm not even sure what you think would be accomplished by splitting ferals out but giving them all the same faction allegiances as zombies. The faction system is just a list of what groups the monster is hostile or neutral to.

**Comment by fairyarmadillo** [comment]
You're describing NPC faction groups, which are different from monster factions. NPC faction groups describe complex political networks with mutable opinion scores. Monster factions are an entirely different system that just defines which monsters are hostile or neutral to each other. Neither ferals nor zombies have an NPC faction group at all.
