### ISSUE TITLE
Artifact Identification & Profession

### ISSUE THREAD

**Issue by deafmole** [CleverRaven/Cataclysm-DDA#58707]
### Is your feature request related to a problem? Please describe.

Artifacts are a fun addition to CDDA and have been for a long time.
However, not knowing what an artifact does, leads to a lot of frustration and/or confusion on the playerside.
And while I absolutely agree that these artifacts should not lose their mystical flair, in practise it just leads to players either trying to find out on the meta-layer, or they end up ignoring them entirely. 
Even moreso: If you survive long enough to get your hands on more than one artifact, the whole ordeal becomes much more micromanagy and results in a multitude of keypresses (to find/grab 'the right' artifact, etc.).

With the recent shift towards Professions, I think it would make sense to be able to identify artifacts.

### Solution you would like.

To identify an artifact, you have to carry it around in your inventory, wield it _and_ study it.
I'm thinking of default values of 30h of carrying, 10h wielding and 20h of active study. 
While that seems a lot, it is still an artifact we know nothing about, nor will we find out what it was used for.
Therefore, the 'identification' of the artifact just tells us, 'how' we can use the artifact to our benefit (or demise).
Similar to the artifacts of 'Roadside Picnic', we will find a use, that was (probably) never intended by its creators.

Ideally I would leave the description vague ~e.g. a simple 'It seems the artifacts makes you stronger' or 'X makes you feel, like you can take on the world.'. I know, we have some descriptions in the log, but those only trigger when picking the artifact up. These vague descriptions would still add to the game, considering we instantly know about stuff like armorvalues - even before we make them. 
With these descriptions added, I would also **not** show changes made by artifacts at all if possible. Say a +1 to Strength doesn't show up on the Charactersheet anymore. Maybe with a questionmark, if the artifact is identified.

I would also love to _name_ an artifact after you have identified it, so the Profession refers to that name (using the generic name while getting it to 100%). The artifact itself has e.g. 'a hollow transparent cube' at the bottom of the description, while the whole 'try and find out'-flavourtext gets removed when it is identified.

Additionally: 
- Give the 'Archaeologist'-start a startingtrait, that helps them cut the time of identifying artifacts by 20-30%. 
- A general Profession of figuring out artifacts could be added, that cuts down time by another 10-15%, when identifying artifacts and can be mastered by any character.

### Describe alternatives you have considered.

Emergency/Naive Implementation:
Actively study an artifact for X amount of time - after that you'll be able to see 'in inventory', 'wielded', 'active'/'rechargable' effects. While that is a rather dull process, it is more easy to implement _and_ it would not litter the Profession-Tab. I would still like the option to at least name the artifact afterwards (although I am not sure if that already is in the game for artifacts). 

Complex Implementation:
The respecting effects of artifacts only get revealed when you interact with it. 
For example only the (immediate) wielding properties get revealed, while you wield it. The active can be studied _or_ tried out. 
And an effect like lifesteal can only get revealed, when it is triggered, etc. 

I guess _'Leaving it, as it is'_ is also an option, but I do not think that artifacts should stay a kind of content, that mostly gets either ignored entirely or makes you close the game to figure out what it does. Especially if you return to your savefile after two weeks and completely forgot what an artifact does, that doesn't just give you an attribute-bonus.

**Comment by PatrikLundell** [comment]
I ignore artifacts because they seem to be "balanced" to have a nominal net zero effect, where the negative effect can be very substantial in exchange for a situational benefit that your play style doesn't even have a use for. Making you take the risk of those unknown negative effects for a prolonged period of time to just find out what it does would push it from the "not worth the trouble" territory into the "stupid to meddle with" area (which obviously doesn't make any difference for me).
I might have been unlucky, but none of the few artifacts I've found have been useful (when looking their effects up), with some just essentially being dead weight, while others being actively harmful without any useful redeeming qualities.

**Comment by deafmole** [comment]
I can see where you are coming from. The thing is: you already circumvented the artifact'mechanic', by looking up the effects. I do not disagree with you however. I would like to see a wider range of artifacts, be it beneficial or detrimental, with respecting +/- weights, trying to reach 0 combined with logarithmic weighting. 

True, it might be scientists instead. I was thinking of older artifacts aswell (not neccessarily caused by the cataclysm), which might clash with current lore. I wrote the Issue after delving into a Amigara Fault mine, so that is why I immediately thought of the archaeologists _and_ because I got 4 artifacts at the same time (two of them with the exact same name).

**Comment by PatrikLundell** [comment]
I circumvented the "artifact mechanic" because I wanted to have some kind of idea what the heck it was about, as they don't make any real world sense. Once I've gotten the gist of what artifacts were, I looked it up, came to the conclusion that they're not worth role playing about, and thus looked up the few others found later as well, which confirmed the impression.

If artifacts would generally be useful, sometimes rather harmless and useless, and catastrophic results extremely rare, plus there was a way to actually get to know the effects (i.e. along the lines of your proposed system) I would use the in-game system.

**Comment by deafmole** [comment]
I didn't mean to offend you with that sentence, so if that phrasing did, I am sorry. And I absolutely get why you did it. I mean so did I and many other players, but that is exactly it: there should not be a need to do that, other than to spoil oneself. 
I absolutely agree with you there, as mentioned above, I would like to see that aswell, that is why i think a first step into that direction would be the ingame option to (partially) identify artifacts. Improvements to artifacts can always be implemented later on. Especially after the content freeze.

**Comment by Gotdamnmiracle** [comment]
As an aside, would it be possible to make it so intelligence is somehow tied to artifact studying speed? That seems intuitive.

**Comment by estebandellasilva** [comment]
Suggestion - you need chemicals + the artifact will behave like an fermting jar or something similar. (doing research and stuff)
You do some testing on it and after some time you can document your observation (repeatable, but you only gain proficency for the first time) - after your testing you can give a guess what the artifact could possibly do - with a chance to misidentify it.

There should be an artifact proficency - which once you have it mastered could at least prevent you from misidentifiying the catastrophic results from artifacts ( ones that could kill you instantly, or cripple you in some kind of way)

**Comment by merrygin** [comment]
I love the idea of expanding on the artifacts and mechanics around them!
I also think that some gear/tools for studying the artifact would be cool, could also be exciting late game loot, or just high level science recipes. If possible, I'd avoid just putting it in a machine, waiting a bit, resulting in an identification. I'd assume that this machine and the associated practical and theoretical knowledge to even understand it should realistically be quite a lot. While that would certainly be a much simpler implementation, it wouldn't have a really immersive researchy/investigaty feel. 

Another route that could be taken is collecting evidence about the nature/origin of artifacts through notes, NPCs, locations the player finds, so more like questlines. Would make the artifacts also feel very special (which then also makes a lot of sense to reflect in their powers). The artifact proficiency could be tied to that, maybe also with some flavourful automatic diary entries to track the observations the player character made. I'd also say that it might be advisable to even lock successful identification behind a full proficiency, so that its not the next best clueless skaterboy that happens to sit around with an artifact for 2 days suddenly becoming a nether-expert :D.

Profession-wise, I could also imagine something like a sciency "paranormal investigator" kind of type that appears to be kinda right about some of the stuff he belived in after all. So the pc knows at least a little bit about this topics, aka is profivient (I didn't delve into the lore docs yet though, so no idea if that fits lorewise).

**Comment by deafmole** [comment]
These different ideas about a startingprofession makes me wonder if it would make sense to differentiate between different kinds of artifacts. So far I have viewed them all to be of some sort of similar origin. I am a vanilla-player, so i never viewed them as something with 'magic' properties. What I am wondering is how to tie artifacts in general into the lore. They seem a bit disconnected from each other. So I am wondering if it would make sense to tie them up with a specific (ancient) faction or the existing factions in the current game instead. That could give a bit of variety aswell, but goes well over what I wanted to address in this issue. 
I don't think the process of analysing an artifact should be something entirely passive without any interaction of the player (like fermenting barrels. That could be made possible in the Exodii-base because of their technological faculty, but from a realism POV it would make much sense for a survivor to do that. 
Using technological apparati would make sense for the active part of analysing however. 
That could vary from different types of artifacts, if we talk about an overhaul.

**Comment by PatrikLundell** [comment]
As far as I understand all artifacts are "magic" from a human perspective, and so can't be understood, only observed.
The idea of artifacts having some sort of origin and thus some sort of themes is interesting, but probably quite a lot of work.
I think all artifacts are of cataclysm origin, as none exist in the current world. Artifacts found in mines and the like only means the cataclysm affected mines as well, and most or probably all artifacts that won't be pried directly from a faction stem from the torn reality period either as items dropped by somethings, or items generated as a result of the warping of reality itself.

**Comment by kevingranade** [comment]
Artifacts being inexplicable is working as intended.
