### ISSUE TITLE
Challenge - Hunted start allows all zombies the ability to wander towards your character without scent, sound, or sight.

### ISSUE THREAD

**Issue by Vostokapollo** [CleverRaven/Cataclysm-DDA#58715]
### Describe the bug

Attempting to play a 16 size 0 distance city start with the hunted challenge scenario, I discovered that it causes zombies around the player to have the same "homing" abilities as the relentless hulk, granting them magical psychic zombie powers.

I tested this with a "Weak Scent" character and ran it with scentmap enabled to see to it that my character was standing where their scent would not spread outside of the building, and the result was zombies pathing to my character within hours of waiting.

I did this experiment again with a character running the "Missed" scenario (still a 16/0 world) and was capable of waiting until nightfall without so much as a shuffling notification.

### Steps to reproduce

Run the Challenge - Hunted scenario and wait in a house in a sizeable town.

### Expected behavior

Only the hulk should be able to magically path towards the player.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1766 (21H2)
- Game Version: e34eeaa [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Extra Mutated Scenarios [extra_mut_scens]
]

**Comment by TryToRemember** [comment]
Cannot confirm. Mob behaviour(s) all as expected. 

Some quick tests; 3x 8/4 and 3x 16/0 worlds. Same mods. https://github.com/CleverRaven/Cataclysm-DDA/commit/e34eeaacc7a51fe8bb1798d662bee648749a70c1 and two others, 1 older _( 714f560 from 03/18 )_ and 1 newer _( 31319f8 from yesterday )_ --  all behave as expected. 

Once I deal with the spawned-within-range aggros, none of the >30 squares mobs can see or smell me. Afterwards, if I stay 5 to 0 noise and seek shady/dark/verydark, especially if I enter a small room (like a BR), once my passing-though scentmap fades I am able to stay 18 (+/-4) hrs before Mister Hulk wants to punch me into next Thursday.

This is likely just bad luck. notabug. RNGs are like that. Further, monster (or anything's) behaviour would not change between scenarios; ie. a shocker brute will glow and spot you and throw electrical arcs across-the-board unless it were redefined, because it's definition is unrelated to scenarios.
