### ISSUE TITLE
Vehicle welding rig does not have enough charge to repair roller drum attached to same vehicle

### ISSUE THREAD

**Issue by jeffplata** [CleverRaven/Cataclysm-DDA#58809]
### Describe the bug

My PC is standing inside the vehicle on the charging station tile (o), diagonally adjacent to the welding rig (&). From this position I can repair the heavy-duty frame (t1) in the front with no problem, but I cannot repair the drum roller on the same tile (t1). The difference is that the frame requires 60 arc welder charges while the drum roller requires 900 charges. I have full large storage battery.

### Steps to reproduce

Please copy the vehicle setup. 

### Expected behavior

Shouldn't the welding rig charge depend on the available vehicle battery charge, which is many times more than enough for the job? 

### Screenshots

![Uploading RDT_20220629_1100166439964691652092806.jpg…]()

![Uploading RDT_20220629_1100221472363008642442035.jpg…]()

### Versions and configuration

    OS: Windows
    OS Version: 6.3 9600
    Game Version: 31319f8 [64-bit]
    Graphics Version: Tiles
    Game Language: System language []
    
Mods loaded: [
                                Dark Days Ahead [dda],
                                    Disable NPC Needs [no_npc_food],
                                        No Fungal Growth [no_fungal_growth],
                                            Bionic Professions [package_bionic_professions]
                                                ]

**Comment by jeffplata** [comment]
Because the images are are not uploading...
![image](https://user-images.githubusercontent.com/29348635/176345825-f72bf333-4021-4ae4-8164-49700e100e8f.png)
![image](https://user-images.githubusercontent.com/29348635/176345921-94269934-8cdf-4b0f-a79a-35fee3745ef2.png)

**Comment by ZeroInternalReflection** [comment]
I can confirm this behaviour on recent experimental.  A vehicle welding rig (with sufficient vehicle battery capacity) can do a repair requiring 300 charges, but not one requiring 900 charges.

It looks like this is the same root cause as #56944 and some similar issues.  The crafting system abstracts vehicle parts/appliances as pseudo items.  The vehicle welding rig is abstracted as an arc welder, with maximum battery capacity of 500 charges.  The crafting screen (`&`) has its own check for whether the vehicle/appliance has enough charges, but it looks like the vehicle repair screen doesn't, so it only sees a maximum of 500 charges, no matter how much is in the vehicle batteries.

The welding rig was not on the list of vehicle parts tweaked in my proposed #56991, but a similar JSON modification allowed me to do the 900 charge repair.

**Comment by jeffplata** [comment]
What is the workaround for this, in terms of JSON?
