### ISSUE TITLE
Disapearing Items on Elevators

### ISSUE THREAD

**Issue by Uplinkedxd** [CleverRaven/Cataclysm-DDA#58815]
### Describe the bug

Items placed on a science lab elevator disappeared when using the elevator. I could successfully use the elevator, but items wouldn't follow me, they'd stay on their respective Z levels, (this worked both top and bottom) but enemies WOULD follow up the elevator.

On one use of the elevator, both the items on the top and bottom of the elevator disappeared. What changed in this particular use is beyond me.

### Steps to reproduce

1. Place random items/corpses on both the top and bottom of the elevator.
2. Go up and down randomly throughout the day.
3. Items have a chance to disappear.

### Expected behavior

Items either stay on their respective levels, or, even better, are transported up and down.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1766 (21H2)
- Game Version: 80d1bee [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Night-Pryanik** [comment]
Can you provide a save?

**Comment by PatrikLundell** [comment]
(Dragged) items used to follow you up (and down), so if they don't something has changed, probably unintentionally.

**Comment by Uplinkedxd** [comment]
https://www.dropbox.com/s/oac6629m0yowhug/Iva.rar?dl=0 let me know if you can get it from here!

And I just tried again, items still do disappear when placed on the elevator and then using it.

**Comment by andrei8l** [comment]
They don't disappear, they're just moved to the "wrong" position due to OM tile rotation. You can enable 3d fov and confirm that they were moved right above the elevator
![Screenshot from 2022-06-30 07-07-33](https://user-images.githubusercontent.com/68240139/176590802-4d97d977-d4de-4495-919f-58d38044c944.png)
There is [some code](https://github.com/Night-Pryanik/Cataclysm-DDA/blob/8dcbfeffad553c8ec52ff980704628a7795ff26e/src/iexamine.cpp#L1191) to handle this case but the range is too small (should be at least 13, or half of a submap + 1). A better solution would be to rotate the coordinates.
