### ISSUE TITLE
Swamp broth

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#58818]
### Describe the bug

Natural swamp resources already provide both water and salt water, exposing a flaw in the recipe and potentially also shallow salt water.

Credits to @x-qq for reporting this on IRC.

### Steps to reproduce

1. Be in a swamp.
2. Be near a salt and normal water tile.
3. You now have 2 of the 3 ingredients necessary for broth, salt water (a substitute for herbs or sauce) and normal water.
4. water + salt water + cattail stalk = broth apparently

### Expected behavior

I know that survival is all about improvising but this seems cheap and unrealistic. It appears that the recipe may potentially imply that you are boiling the salt water until only salt remains but this also problematic due to the time consumed.

Secondly, although the murky swamp water full of organic material may already classify as a vegetable itself, the contamination of the water may still be an issue. Maybe we need murky salt water?

My proposal is to remove salt water from the broth recipe entirely.

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.F-9426-gcb051eb5bae [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

This might be a good first issue.

**Comment by x-qq** [comment]
I did not "report" it and it does not require "fixing". Thank you.

**Comment by Venera3** [comment]
Yeah, salt swamps are one of those ancient things that Just Do Be Like That - there *are* salt water swamps in NE, but they are an exclusively ocean-adjacent biome for obvious reasons. I think removing the salt puddles from the region def would be the right call until we have the sea.

**Comment by Venera3** [comment]
I am not a fan of the balance argument (I'd bet my stack of bone glue that most of the large-scale salt water usage will be that minecrafty salt->bleach "chemistry" recipe) - it would remain eminently lootable in the places it makes sense, and you're not running out of house pantries any time soon for cooking purposes. Using (clean) salt water as "seasoning" is a bit of a stretch, but less than having an inland rainproof salt basin.

Plus "things you take for granted were actually luxurious for 99% of human experience" is a core message of the game in my eyes, but that's a more subjective argument.

**Comment by mqrause** [comment]
I have no idea about the geology of New England, but it's entirely plausible to have a salty water source away from the ocean. There used to be a salty lake around where I live until it got drained some time in the 1800s or so. It formed because there is a layer of rock salt in the ground that got in contact with the ground water. The rock salt slowly getting dissolved in the ground water caused both the formation of the lake itself by lowering the ground in that area and the increased saltiness of its water. That said, I doubt that'd be the case in every swamp everywhere.

**Comment by descan** [comment]
Besides a direct input of salt, like overlying a rock salt outcrop like that, to my knowledge the only other main way to get salty lakes that aren't due to the input of sea salt (as in salt water marshes) are endorheic basins - water comes in, can't go out, evaporates, and it leaves behind its salt. Repeat over time. Eventually you end up with a saltwater lake, or just a salt flat or basin if water stops being inputted.

To my knowledge, there is no such process going on in New England - there aren't any such basins. Such things tend to happen in uplifted areas and dryer, arid regions like the Atacama desert in South America or the Rocky Mountains. 

I'm also not sure if that process would result in a salt water marsh if there was enough water being inputted. I imagine other water-based processes, like erosion of the basin sides, would overpower this process and it'd drain away before it became a non-sea-based salt water marsh.

But I'm no geologist. Or hydrologist. I just play one on Wikipedia :V

**Comment by fairyarmadillo** [comment]
Something I have noticed over the years is that there isn't really much salt in houses. Almost every home in America has one of those 26 ounce things of Morton's salt in a cupboard, so it should be ubiquitous. There's no cuisine on earth that doesn't require it in some fashion, it's dirt cheap, and it's sold in large quantities with infinite shelf life.

I recommend leaving the saltwater pools in Innawood if possible and removing them from main, and also we should greatly increase the rate at which salt spawns in homes. It should be way more common than Ammonia, which is almost a guaranteed find.

**Comment by natsirt721** [comment]
It always rubbed me the wrong way that swamps would have salt and fresh water with such extreme proximity. I'd advocate for removing the salty ponds from swamps and possibly buffing the spawn rate in houses.

As for supply, there's one place you should be able to find truly massive amounts of rock salt - public works departments. The DoT puts an obscene amount of salt on roadways each winter - that has to be stored somewhere. I do know that some aggregate has sand (for better traction) and calcium chloride (for better low-temp melting) added before it goes on the road, but I'm not sure if they store those things separately and mix them as needed or what. I would assume separate storage.
