### ISSUE TITLE
(cool) Food stacks [E]aten from a fridge gets placed in player inventory and immediately spoils

### ISSUE THREAD

**Issue by descan** [CleverRaven/Cataclysm-DDA#58824]
### Describe the bug

When eating certain foods (it doesn't always happen) that are being cooled in a fridge, if the item is in a stack the item is taken out of the fridge and placed in the players inventory after the first item is eaten. Thankfully this first item doesn't get immediately Rotten, but (especially after leaving the Eat menu and going back in) the foodstuff in the players inventory is suddenly rotten.

### Steps to reproduce

1. Have a fridge with cool food stacks (past their "expiration" date?)
2. Attempt to eat them
3. See them placed in player inventory
4. (Possibly): Leave Eat menu, go back in to Eat menu
5. Whoops it's all rotten suddenly, guess you shouldn't have taken it all out of the fridge, dumbass

### Expected behavior

I expect my character to be smart enough not to dump this big stack of tomatoes or meat in their inventory if they're gonna just eat one.

Failing that, I expect a stack of food that's maintained chill-freshness to not immediately, 1 second later, spoil after being taken out of the fridge - a couple of minutes at least before all the bugs descend on it, no?

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22000.739 (21H2)
- Game Version: cc52f60 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Alternative Map Key [alt_map_key],
    Translate Complex Dialogue [translate_dialogue],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Generic Guns [generic_guns],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Tamable Wildlife [Tamable_Wildlife],
    No Fungal Growth [no_fungal_growth]
]

### Additional context

Fridges as a whole seem to behave weirdly, and I can understand if food being good for weeks past their spoil time, almost being in stasis-lock, is not exactly desired. That being said, it's a little silly if you can ruin entire stacks of food by trying to eat one of them, when a sensible person (given the information of "hey if I take ALL this stuff out of this weird refrigerator, it'll immediately go bad") would just... not take the entire stack out of their Magically Preserving Fridge.

I'm also not entirely sure what the cirumstances are where the food is taken out. Food in a container will remain in the fridge. A stack of crops I had also remained in the fridge. But I know it happened with an item of curry. In my current save, I can't actually replicate this behaviour, so I'm not sure what's going on or in what situations the character will grab the whole stack.

**Comment by PatrikLundell** [comment]
It's certainly the case that there are weird cases of food reporting to have a decent time left while in a fridge spoils immediately it is removed.
The intended logic with fridges is that they'll slow the spoiling rate of food, so that milk will last a few days in the fridge, but spoil before the afternoon if in the middle of summer.
What I think happens with these weird fast-spoiling cases is that the decay timer isn't recalculated when the food is removed, so when the age is checked against the creation date the logic finds that at the ambient temperature it should have spoiled a long time ago..
What's needed is to keep track of the progress of the decay as conditions change and have a time stamp for the decay at the time of the last change. You probably don't want to update this for every item sitting in a powered fridge or in a root cellar every time the game accesses them, but you don't want to see that something that had several days left in the morning suddenly is rotten when you wanted to eat it for lunch because the noon temperature is a lot higher than the morning one.

**Comment by Kiael** [comment]
This issue continues to make using fridge appliances very frustrating. Only work around for now is to just never remove anything from a fridge once you put it in there and to only use anything within it as ingredients for cooking nearby.

**Comment by Stadler76** [comment]
/confirmed with a freezer
Took out fresh frozen meat and it was insta rotten.

**Comment by robob27** [comment]
I did some testing with this. I think it has something to do with items in the fridge not getting properly loaded into the reality bubble for processing after a save/load?

- I spawned a fridge/supporting appliances and 2 chunks of meat. I labelled one "test meat" and one "control meat"
- I put "test meat" in the fridge and "control meat" on the ground
- I added some debug messages to print when rot is updated for items. Before save/load, I was able to see both "test meat" and "control meat" having their rot values updated as I waited with the items in the reality bubble:

![image](https://user-images.githubusercontent.com/2104555/189556437-a9186b49-dcdf-4114-aa24-c7d528caccf4.png)

- After save/exit/load, I now see only "control meat" having rot values updated even though "test meat" still exists in the fridge in the reality bubble:

![image](https://user-images.githubusercontent.com/2104555/189556530-6f576f3d-ba2a-4761-8771-54e099244389.png)

- I added some additional information to item debug to make it easy to see the amount of outstanding time to process on an item. Here is the output for "control meat":

**Comment by robob27** [comment]
I [added a debugmsg](https://github.com/CleverRaven/Cataclysm-DDA/commit/ca1e0e96010f2a8f745c1ebd2939101cf04532bf) that seems to confirm that items in the fridge are being properly added to `active_items` on the vehicle while loading a saved game..

![image](https://user-images.githubusercontent.com/2104555/189716754-5edcd3be-a718-4b96-8422-858b8a50591d.png)

![image](https://user-images.githubusercontent.com/2104555/189716859-bcbeed58-2ca9-4571-8afc-a617997d0cab.png)

But still not hitting [a breakpoint here](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/map.cpp#L5307) 🤔

**Comment by robob27** [comment]
I was able to isolate when the vehicle loses the `active_items` after a load. It happens [after this `vehicle::refresh` call in `vehicle::deserialize` in savegame_json.cpp](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/savegame_json.cpp#L3539).

By moving the [manual backfill of the `active_item` cache](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/savegame_json.cpp#L3471-L3484) to _after_ that refresh, the items in the fridge now get processed as expected after a save game load.

I'm not sure why this change is needed yet though, or if it's the right change to make. I'm guessing something changed with `vehicle::refresh` since this used to work with the refresh happening after..
