### ISSUE TITLE
New mutation threshold: Bat Mutation

### ISSUE THREAD

**Issue by Stadler76** [CleverRaven/Cataclysm-DDA#58876]
### Is your feature request related to a problem? Please describe.

Looking at the Bat Wings mutation (currently on the back and planned to become an arm replacement later) and seeing, that there's *only* the beast mutation that get them makes me think, that the game should have a bat mutation too. Especially since beast mutation is a bit too much of other mammals and only minimally a part of the bat mutation.

### Solution you would like.

Instead of tieing bat wings and maybe a couple other mutations that refer to bats to the beast mutation, bat mutation should have its own branch.

### Describe alternatives you have considered.

An alternative would be to not add another mammal mutation to the game and instead modify the beast mutation to become a bit more batty.

### Additional context

See [Common vampire bat - Wikipedia](https://en.wikipedia.org/wiki/Common_vampire_bat) for reference.

**Comment by Stadler76** [comment]
Some ideas of what mutations bats should have (using BAT instead of CHIROPTERINE here for the internal names):
- `BAT_WINGS`
- `BAT_EARS`: Maybe with two steps because those lead to Echolocation, mid step being Pointed Ears aka `ELFA_EARS`
- `SQUEAKY_VOICE`: Byproduct of being able to generate ultrasonic sounds. Another (potential?) requirement for Echolocation.
- `ECHOLOCATION`
- `LONG_FANGS`: Bat teeth. For more painful bites (maybe). Actually `FANGS` with extra long canines poking of of the face a bit more.
- `SHORT_FUR`
- `DARK_SKINNED`: For the dark-brown or black skin tone.
- `SHORT_FOOT_CLAWS` / `CLAWED_FEET`: Minor cut damage.
- `BAT_TAIL`: Mostly bad mutation as it restricts clothing and looks kinda ugly. *Maybe* with a minor dex and/or movement speed bonus because they are meant to 'support flying' (Here: Means movement speed on the ground since the game doesn't support flying, at least not for the player).
- `LIGHTSTEP`, `DEFT`: For the stealth/dexterity part of that mutation branch.

**Comment by Venera3** [comment]
The problem with another "specific kind of mammal" mutation category is -because of the way trait selection on mutation works- we already have heaps of generic mammally traits that are nonsensically locked to *only* one category (Rats and mice are the same damn family, but you couldn't tell that from their traits ingame). The alternative would be to add identical but category locked traits which is makes the things terribly bloaty.

The good news is you can set up a series of trait dependencies either pre- or post-threshhold that pretty much do the same thing as a category. If you include a nonpurifiable step or two you can also lock the survivor to a batty phenotype while staying on beast mutagen.

**Comment by fairyarmadillo** [comment]
There are plans to create more generic (mollusk, mammal, reptile, arthropod) categories, right? And then stuff more specifically tied to orders or families would be downstream? This would be easier to implement after that was done.

Also you gotta call it chiropteran and give it the ability to digest blood. You just gotta!

**Comment by Stadler76** [comment]
> Also you gotta call it chiropteran and give it the ability to digest blood. You just gotta!

I could use that for internal names. But I *think* it is more user-friendly to talk about bat mutagen instead of chiropteran mutagen or chiropteran ears and so on.
And yes: Blood drinking was one idea. I wasn't linking to vampire bats for nothing. But that needs some limits, like: drinking spilled blood vs. drinking fresh blood and so on. On the other hand: one limitation could be the amount of blood you'll harvest from a blood puddle.
Another idea was Entomophagy (dunno, if that's the correct spelling), not for bats alone (think of lizards and batrachian for example). But unfortunately the game doesn't have any 'insect meat' at the time of writing.

@Venera3: I'm not ignoring your concerns, I just haven't a good answer to it so far, but I can say, that I do get your point. And: I've always wondered why there's mouse **and** rat mutation.

**Comment by fairyarmadillo** [comment]
There's a mouse and rat mutation because they're very different animals (not even the same genus!) and a contributor wanted to introduce a mutation that centered around being very tiny. 

Recent changes have somewhat homogenized the gameplay experience, but when it was created, being a tiny little guy that was super good at dodging and basically couldn't wear armor and had to eat junk food 24/7 or it would starve was very cool. Rats on the other hand are big bruisers that used to be super good at tunneling.

In real life, rats are bold opportunists with relatively powerful bites and very high intelligence. They hunt, swim, scavenge, and forage and can fight off animals much larger than themselves. Mice are mostly herbivorous, shy, far less intelligent, a quarter the size and not so good with water. They generally do not hunt and are not particularly good at self-defense, focusing mostly on stealth and escape for survival.

**Comment by Stadler76** [comment]
Ok, thanks for clearing that up @fairyarmadillo.

**Comment by Stadler76** [comment]
Some more random thoughts about the attacks:
>`SHORT_FOOT_CLAWS` / `CLAWED_FEET`: Minor cut damage.

I wanted to give them another attack than just random bites, but scratch thar.
I think it's ok to give them `TALONS` aka Large Talons for now and later, when `ARM_WINGS_BAT` are a thing replace that with a special attack 'spell' where they 'jump' into the enemies face, biting it and incapacitating the enemy for one or two turns because they're clutching their targets head with their wings.

**Comment by Venera3** [comment]
*Compared to a human* (which is where we start for mutagens) both rats and mice are small, furry critters with clawed paws, always-growing incisors and a tail - the mechanical differences are vastly overblown for their similarities. If we ignore thepprpblem of "category granularity", the mechanical problem stays - if bat gets `Short Fur`, `Ugly->Deformed`, `Muzzle`, or similar mammaly traits (and I'd be surprised if Bat *didn't* have those, even if as intermediates) the mutation code has no way of knowing if you got the trait from Bat mutagen and will roll your next trait towards Beast/Lupine/Bear/Feline/Rat/Mouse almost as likely as towards Bat. That was less of a problem when serums were 100% category-locked, but with the new vitamin-based mutation system such trait overlaps got a bit more problematic.

**Comment by Stadler76** [comment]
> That was less of a problem when serums were 100% category-locked, but with the new vitamin-based mutation system such trait overlaps got a bit more problematic.

FYI: PR #58803 fixed that issue.

**Comment by Stadler76** [comment]
And about `Ugly->Deformed`:
Especially `BAT_WINGS`, `BAT_EARS`, `BAT_TAIL`, `BAT_SNOUT` and `BAT_NOSE` should add up more than enough ugliness to make `Ugly->Deformed` more or less redundant. Although some bat lovers and ppl. that care for bats might beg to differ.

**Comment by kevingranade** [comment]
Housecleaning stale issues.
