### ISSUE TITLE
Starting (with) Horse Scenario/Profession

### ISSUE THREAD

**Issue by descan** [CleverRaven/Cataclysm-DDA#58874]
### Is your feature request related to a problem? Please describe.

There're some scenarios and professions where you start with pets, and some you start with a vehicle. It'd be neat if there were a scenario and/or professions where you can start with a horse, tack, and maybe saddle bags.

### Solution you would like.

COWBOYS

### Describe alternatives you have considered.

Maybe some of the pre-existing professions, like Rancher, could start with a horse. It reads like it should, but lacks the Pet: Horse.

### Additional context

COWGIRLS

**Comment by PatrikLundell** [comment]
Note that the ponies in the game have a maximum carrying capacity of 100 kg, which is the naked normal weight of a maximum height character. Your character would have to be rather short (and, obviously not overweight to any significant extent) to not be limited in what it could carry and still ride (with frequent cases of riding to a scavenging location and walking back because of overweight, although you might have wanted that anyway, to use the horse as a beast of burden for loot).

**Comment by descan** [comment]
> Note that the ponies in the game have a maximum carrying capacity of 100 kg, which is the naked normal weight of a maximum height character. Your character would have to be rather short (and, obviously not overweight to any significant extent) to not be limited in what it could carry and still ride (with frequent cases of riding to a scavenging location and walking back because of overweight, although you might have wanted that anyway, to use the horse as a beast of burden for loot).

Mostly I think it'd just be flavourful to *start* with a horse. I feel like by the time I get enough weight on my character to be an issue with a horse/pony (are they considered the same thing in CDDA?) I'll have migrated to a vehicle for loot runs, unless I'm playing a wayfarer.

Gameplay wise, I use horses as scouting. Starting with a horse would make that a little easier, sure, but I'm more interested in the idea of this person fleeing the apocalypse but making sure they got their horse with them.

**Comment by descan** [comment]
That being said, that raises another question - maybe horses should be expanded a little bit. There's a big difference in strength and size between, say, a Shetland and a Clydesdale.

**Comment by PatrikLundell** [comment]
No, there's only a single kind of horse in the game, and it's severely under powered, in my view, which is why I've taken to call it a pony to stress the limited usefulness of it.

I tried to use horses for riding originally, but quickly found that it couldn't carry my average size character when geared up a little. I then tried to use a pair of horses to carry a cart, and it worked for a little while, until they randomly started to escape from their harnesses at the sight of anything that was remotely close to hostile.

It's a pity, as horses could have been useful, in particular for a role of traversing forest terrain where vehicles can't be used.

**Comment by SirPendrak** [comment]
Maybe this idea is questionable, but what about start that lets you begin with actual warhorse? Lets say youre rich historical reenactor. Paying few points for a pet, that might be strong early game but not OP lategame and might die seems fair. It should probably be able to lift arround 200kg or so (A big guy, his armor, his weapons and some bagage, horse armor).

**Comment by descan** [comment]
I don't think that's necessarily questionable, but the problem here isn't balance, it's that horses now are what dogs used to be. There's one horse in the game, period, and it's a scrawny little twink. I guess they cloned him and did a bad job. 

So starting with a warhorse, a big ol' stallion, a Destrier of the ages, wouldn't be a big deal! ... If those existed, which they don't at present.

**Comment by PatrikLundell** [comment]
@descan types (and thinks) faster than I do...
And is modifying it faster as well...

The problem with a war horse is that the game doesn't have that kind of logic. Animals have a small range of possible behaviors, and I don't think any of them match what we'd want. That might be worked around by introducing a new creature that's called a "horse" but isn't, although it still wouldn't have the proper behavior.
I agree with the mentioned breed issue as well, although I think that could be worked around by "simply" adding breeds from ponies to "normal" riding horses, racing horses, and work horses. You'd need quite a fair bit of money (and time) to train a "war horse", but I believe there are some people that actually joust in replica armor (that would be a major pain to use for anything else, given that its sole purpose is to provide maximum protection riding on a horse against another person on a horse aiming a lance at you). Of course, if you've got the means for that you may also have the means for other sets of armor as well, but you wouldn't have more than one set with you at the start.

It would, however, be interesting with a start where the helmet you start with makes the FoV narrowing performed by aiming seem like unrestricted view (narrow slit that doesn't allow you to see up or down beyond what you can achieve by bending at the waist and the helmet attached to the armor so you have to turn the torso to see anything to the sides, plus no or limited protection at the back of the legs and the butt).

**Comment by kevingranade** [comment]
Feel free to PR this,  but it doesn't need an issue.
