### ISSUE TITLE
Portal Storm Dungeons Feedback and Ideas

### ISSUE THREAD

**Issue by Ramza13** [CleverRaven/Cataclysm-DDA#58887]
### Is your feature request related to a problem? Please describe.

#58500 has been merged adding the first version of portal storm dungeons.  Right now they are very basic. 

### Solution you would like.

 I am already working on improvements to the dungeon design, rewards available and system which gives out rewards.  This issue is intended to be a place to discuss and gather feedback on this new feature.

Currently planned:

1. More types of dungeon levels, with better randomization
2. Improve the enemies and enhance the endless hunger to be more of a constant threat, possibly give it dialog of a sort.
3. A lot more rewards.
4. A new way to give out rewards.

I'd love to hear your feedback on what already exists, and any ideas you have for improvements.  I'd love to get some really out there or strange stuff in here like a text adventure level or minigames so far out there ideas are fine.

**Comment by a-chancey** [comment]
I really like them so far, it's a neat concept, except it's randomly instakilling my character.
It seems that the floor has a chance to shift into a ledge, and if this happens below the player, they instantly fall to z-0 (the dungeon says it's level 6), crushing and killing them instantly. It also has a chance to do it when exiting via the portal.

**Comment by NetSysFire** [comment]
This was fixed in #59251

**Comment by a-chancey** [comment]
Hah! of course it was merged a few hours after i pulled latest. disregard, i'll give more feedback after i've updated and experienced them more.

I will say, on the first one, I got to dead tired from the monsters inside and had to spend almost and entire 24 hours sleeping. I passed out drinking water in my car after leaving the dungeon

**Comment by Ramza13** [comment]
> Hah! of course it was merged a few hours after i pulled latest. disregard, i'll give more feedback after i've updated and experienced them more.
> 
> I will say, on the first one, I got to dead tired from the monsters inside and had to spend almost and entire 24 hours sleeping. I passed out drinking water in my car after leaving the dungeon

Yea the reliance on exhaustion and shifting masses as a challenge is partially a placeholder.  I'm looking to make the challenges more specific to the dungeon by improving the endless hunger and maybe adding some other new enemies/traps.  Haven't worked out all the details yet.

**Comment by nullinsky** [comment]
Just adding feedback that the forced Strange Location mission is really annoying. I didn't even realize that it started until the portal storm ended and I failed it. It blemished my otherwise perfect mission record.

An option to start the quest or ignore it would be great. Otherwise, this would continue cluttering up the mission tab.

**Comment by descan** [comment]
First up, I have a save with this issue displayed.

Anyway, this might not be related only to the dungeon, because other things are also not disappearing (I remember seeing an issue about this too) such as monsters and alien grass that only gets partially erased. 

The issue being, the portal storm dungeon seems to have only... partially disappeared? The shadow footprint of the dungeon persists in a square right near my camp. It's been there for weeks - actually it's been there through 1 or 2 other portal storms, so even those after-storm clean-ups are getting rid of it. 

Actually, scratch that - it didn't "partially disappear," it's still there. If you go into debug and go up 6 Z-levels in the map editor, you can see it - plain as day. 
[debug save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9194251/debug.save.zip)

**Comment by Ramza13** [comment]
> First up, I have a save with this issue displayed.
> 
> Anyway, this might not be related only to the dungeon, because other things are also not disappearing (I remember seeing an issue about this too) such as monsters and alien grass that only gets partially erased.
> 
> The issue being, the portal storm dungeon seems to have only... partially disappeared? The shadow footprint of the dungeon persists in a square right near my camp. It's been there for weeks - actually it's been there through 1 or 2 other portal storms, so even those after-storm clean-ups are getting rid of it.
> 
> Actually, scratch that - it didn't "partially disappear," it's still there. If you go into debug and go up 6 Z-levels in the map editor, you can see it - plain as day. [debug save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9194251/debug.save.zip)

I'll try to take a look at this but before I do just to be clear how old a version were you using to make this save?  This sounds like a problem I fixed after portal storm dungeons were released.  If its still happening in current versions thats a big issue.

**Comment by descan** [comment]
> > First up, I have a save with this issue displayed.
> > Anyway, this might not be related only to the dungeon, because other things are also not disappearing (I remember seeing an issue about this too) such as monsters and alien grass that only gets partially erased.
> > The issue being, the portal storm dungeon seems to have only... partially disappeared? The shadow footprint of the dungeon persists in a square right near my camp. It's been there for weeks - actually it's been there through 1 or 2 other portal storms, so even those after-storm clean-ups are getting rid of it.
> > Actually, scratch that - it didn't "partially disappear," it's still there. If you go into debug and go up 6 Z-levels in the map editor, you can see it - plain as day. [debug save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9194251/debug.save.zip)
> 
> I'll try to take a look at this but before I do just to be clear how old a version were you using to make this save? This sounds like a problem I fixed after portal storm dungeons were released. If its still happening in current versions thats a big issue. Thanks

It was in the then-current experimental - the game world itself was no older than a couple real life days. When I said "weeks" I meant in-game weeks.

**Comment by Zachert45** [comment]
Hoping that progress is going well on this front, Its sad to say tackling dungeons is not really worth it in current form due to exhaustion. My main save is dead at this point due to being so exhausted that my character has die from dehydration due to being in a "coma" for 20 plus days. I got out of it once by chugging a gallon of atomic coffee to get some tiredness away, but trying to sleep this off does not seem to be working, cannot get into debug most of the time due to stuck in sleeping to check levels, but it seems to be pushing them past max levels and getting stuck in impossible exhaustion loop.

**Comment by chphilli** [comment]
I seem to have just had the same issue as @descan regarding the portal dungeon not spawning properly. As soon as the storm started, I ran outside, waited to see the "investigate strange location mission", ran over to it. When I stepped on the portal, there was a message "You hear a high-pitched squeal." and then nothing after.

![2023-03-24 18_57_06-Cataclysm_ Dark Days Ahead - d98a4cc](https://user-images.githubusercontent.com/504167/227680084-5eb37307-5707-49c8-a456-6f6eed1b83bf.png)

[Coruscant-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11067760/Coruscant-trimmed.tar.gz)

(This saved game does have a couple of in-repo mods, as well as a personal one that just adjusts a couple of items -- that one at least shouldn't affect anything like this.)

**Comment by Tharn** [comment]
The portal storm event happens too often. If you have portal storms 2 times a week then it 1) makes the event nothing out of the ordinary and 2) regularly disrupts whatever else you are trying to do.

I'd rather see the spawns become more dangerous, the dungeon more difficult and the event cut down to occur only 1/10th of the time at most. It's portal storming more often than it's raining!

Also, rather than supernatural rewards being the norm, another reward could be simply that it ends the portal storm when you finish the dungeon - and when you don't, it could last for several days. Doing the dungeon repeatedly to get a better reward is also an unintuitive mechanic. Currently the shifting layout and lack of danger in there results mostly in tedium, and then doing it several times in succession is more tedium. Have the player only go through (a bigger, better, more dangerous) dungeon once and then force-eject him afterwards.
