### ISSUE TITLE
Allow mutil-select in Hide/Reveal Mission UI for the Faction camp

### ISSUE THREAD

**Issue by DamienRoyan** [CleverRaven/Cataclysm-DDA#58931]
### Is your feature request related to a problem? Please describe.

When hiding unwanted tasks, such as after upgrading an expansion like the Workshop, one must go back and forth to hide all the unwanted missions. 

A Quality of life feature such as multi-select would alleviate this back and forth chore. Adding it for the reveal mission UI too might as well be done

### Solution you would like.

Have the "Hide/Reveal mission" use multi-select, similar to the drop item menu

### Describe alternatives you have considered.

Have the UI not exit after every choice. In the current implementation, you can to choose one thing and then have to go through it all again. Would be better if it let you stay on the UI

**Comment by PatrikLundell** [comment]
I completely agree.

The reason it works the way it does is that the UI infrastructure the functionality is built upon only provides the operation "select a single entry from this set, or abort". Thus, supporting this would require the re-implementation of the UI using different or substantially updated UI tools.
It's not impossible, of course, but you'd have to convince someone capable of implementing it that it's more important than what they'd otherwise implement in that time.

**Comment by DamienRoyan** [comment]
So either I wait for someone to wanna do this. Or I learn c++....

**Comment by PatrikLundell** [comment]
Well, you've called for someone to do it, so that part has been taken care of.
Learning C(++) is the easy part. The hard part is to get some kind of handle on the sets of UI code available within the project. As you point out, there are other UIs that support multi select.
My response was intended to temper your expectations.
