### ISSUE TITLE
New England has a SEVERE housing problem.

### ISSUE THREAD

**Issue by LovamKicsiGazsii** [CleverRaven/Cataclysm-DDA#58946]
### Is your feature request related to a problem? Please describe.

Undead overpopulation is an issue in almost every zombie game.  The towns of New England don't have the capacity to house their once-human residents.

To prove this, I examined two towns of varying sizes and calculated how many people they can house as opposed to their undead population.  I made an excel file (`villagepop.xlsx`), and assigned a square for every building in that particular town. Each square has two pieces of information: housing capacity and amount of zombies.

For clarity, I calculated housing capacity by the number of beds in each tile (1x1 and 2x1 beds mean 1, 2x2 and 3x3 beds mean 2 points).
For undead population, only humanoid zombies and corpses were taken into account (so no zombie dogs).

**Results:**

This is Medfield, a small town with a max. housing capacity of 47 and a zombie population of 71.  33% of them are without a home.

![kép](https://user-images.githubusercontent.com/44979050/177048171-a2b91416-0ad9-4047-9cb4-a106f22092d9.png)

Nearby is the town of Belcherford.  Its housing capacity is just 205, but it has an undead population of 565.  64% of them are homeless.

![kép](https://user-images.githubusercontent.com/44979050/177048248-172c141f-31a1-4ca7-a234-132679279f87.png)

The sample size is small, but I think it's safe to assume that bigger cities have an even larger ratio of 'excess' zombies.

Also, I only calculated the zombies that were inside city boundaries.  Had I calculated any nearby locations (like the bunker near Belcherford or the mass grave next to Midfield), the percentage of homeless zombies would've been even more disproportionate.

### Solution you would like.

The most straightforward solution would be lowering zombie spawns.  Some locations have an absurd number of zeds and need to be audited.

* Zombie spawns at parks are still excessive.
* Workplaces like office towers should probably be empty, considering people have better things to do when the world is falling apart.
* Some houses don't use monster groups properly, causing large spikes in zombies (e.g. `house_detached4`, `house_detached9`).

### Describe alternatives you have considered.

Adding more high-density housing to cities.  I believe Urban Development had one such location.

### Additional context

The excel file:
[villagepop.xlsx](https://github.com/CleverRaven/Cataclysm-DDA/files/9035133/villagepop.xlsx)

**Comment by LovamKicsiGazsii** [comment]
Oops. didn't mean to publish just yet.

**Comment by NetSysFire** [comment]
I could swear I saw a very similar issue in the past but I fail to find it for the life of me. I agree that there is a problem with the zombie population though.

**Comment by snipercup** [comment]
This ties into the lore of course, but you'd have to think about how people were moving during the collapse. I think small towns should have a lower population because we know people often travel to the city for business and return home in the evening. Bigger cities should have more zombies then beds, small villages should have less zombies then beds.

>Workplaces like office towers should probably be empty, considering people have better things to do when the world is falling apart.

Following this logic, the grocery stores should have the highest density population

**Comment by NetSysFire** [comment]
>considering people have better things to do when the world is falling apart

Honestly I think it depends on how quick the world ended. The [lore document (SPOILER ALERT)](https://cataclysmdda.org/lore-background.html) says it has been going on for 15 days, the formal "end of the world" is 5 days before game start. So yes, plenty of people would have been killed in a grocery store. I think there is either a newspaper entry or even scenario description which says something like: "The police were called to a brawl in a grocery store but soon enough the officers were mindlessly involved in that brawl too."
This would inevitably lead to deaths and therefore zombies (and more deaths).

However, I think many would just flee. We already see enough car wrecks on the road, impliying that reckless driving got even worse with the blob psychosis, causing even more deaths. Since the wreckage can block roads, I would actually think some tried to flee on foot, maybe even making little camps (different from those one tile campsites) in progress.

>YES. I wonder why though.

I fail to find a reason for that, too.

**Comment by chrispikula** [comment]
Given how close together villages and towns are in the current map-gen, we could just go with that a large number of people were just at work, or shopping.  There's also a severe under representation of vehicles, and houses are almost all both too small and too large.

I'd just throw the low number of beds down as a side effect of the distance compressing.  Can't represent all the beds, fold-out couches, bunk beds, etc.

Also, how is this supposed to ever be rationalized with hordes, and their endless respawning?

**Comment by PatrikLundell** [comment]
This is the reason I generate worlds with severely reduced spawn ratios. That reduces the number of zombies in congested locations to just insane levels, but it has the side effect of leaving other places too empty.

What I'd like to see is both an adjustment of the number of zombies generated for the default ratio, and an audit of zombie spawns such that different locations are balanced towards a common balance point. There may be some reason for some locations having a heavier presence than normal, as well as there being a reason for a lower presence in others.

Apart from the parks, farm barns and basements tend to contain unreasonably large number of zombies (the latter when they're present only, of course).
Whether the extreme number of zombies at hospitals is a balancing issue or is intended to be written up to that being the place the injured were sent in large numbers (to then die and be zombiefied) can be discussed.

**Comment by PatrikLundell** [comment]
Parks: The last place to go to when rioting and fighting is happening is a place with a lot of belligerent people. Sure, somewhat open ground might be better than narrow streets, but not if there are nasty crowds there as well.

Basements: Sure, it would make sense for people to hide the whole available family in the basement, plus maybe an occasional friend that might be nearby. However, the US has mostly left the 20 kid family phase followed by the introduction of antibiotics behind it, so the number of people down there should be only a handful at most, not a dozen or a score.
I don't buy the argument that the numbers would be augmented significantly by neighbors, given that most basements are empty, which they wouldn't be if the whole neighborhood would rush for the basement closest to each of them with a significant ratio reaching "safety". Also, a significant proportion of the neighbors (and family members) would be among the rioters, rather than among those trying to hide away.

Barns: Doesn't make much sense at all. The only thing barns has going for them is that things outside can't see into them, but they're flimsier than the house that's nearby where curtains could have been drawn to the same hiding effect. People would only start to hide once the fan is spinning and distributing what hit it, so the neighbors would hardly cross kilometers of open terrain for the "safety" of a barn (where the owners probably wouldn't let them in anyway, thinking they're unsafe madmen or more of those tricking illusions).

I could understand if zombies would be gathered by some houses and not others based on the principle of attraction by noises, but that would place them outside, not inside the barn/basement.

**Comment by PatrikLundell** [comment]
Search for "place_monsters" in data/json: 588 hits in 219 files vs 931 hits in 281 files for "place_monster" (which has the former as a subset), so yes, the majority of them seem to be in the absolute format (and some of them in what I think are recently implemented locations).

However, in order for someone to adjust these places, there would have to be some kind of reasonably agreed upon baseline against which to balance things.

**Comment by NetSysFire** [comment]
>which has the former as a subset

You can circumvent that by matching the quote.

```
grep -or place_monster\" mapgen | wc -l
292
$ grep -or place_monsters\" mapgen | wc -l
521
```

So yes. There is a problem. Among the files are a couple of park-related buildings, many residential houses and basements.

**Comment by JonathanLochridge** [comment]
Well, the dirty solution of decreasing spawn rate while making them nastier in some other way might be sensible? Maybe making nastier zombies a little more likely to make up for the reduced numbers?

I would also love to see someone come up with that "reasonable baseline" to use in a zombie pop audit. I am not sure who has enough experience with balancing to be a good option for that?

If we could maybe figure out what the baseline for places that use the right tag then that might be a good start?

**Comment by JonathanLochridge** [comment]
From what I can tell, the new apartments in #63855 are about 3x bigger in tiles used. I am unsure how many beds that will be in practice. But, if the density is the same as the appartment given in that study.
That would mean about 200ish more beds in a town with one apartment of this size.
That would make only 160 of the zeds homeless or 28% if the pop was the same, which is a still a bit high, but not quite as ridiculous. If it was added and made the new pop 725, that would make the homeless population 22%.
Overall, I think if we had about 16 total tiles of appointments on avg. for a town this size that it would make the homeless population pretty reasonable with that approach. Although, 22% is still a lot better than 64%.

**Comment by LovamKicsiGazsii** [comment]
This issue focuses more on the "let's house the homeless" approach rather than culling the excess zeds, which I now believe to be the better solution ultimately. So, in a way #63855 does resolve this issue, just not the root of it.

I do want to have a new issue out -- preferably with a less clickbait-y title -- that would address just that. I'm not sure about a 'reasonable baseline' though; based on experience, it seems there's about... twice as many zombies as available living space?

> Well, the dirty solution of decreasing spawn rate while making them nastier in some other way might be sensible? Maybe making nastier zombies a little more likely to make up for the reduced numbers?

I completely agree. The challenge here is finding how to make zombies more threatening (stronger, faster, tougher) while not taking away the uniqueness of other mutated variants. Also, bullet sponges can be a bit boring.

**Comment by PatrikLundell** [comment]
Reducing the number of zombies while making them nastier does not maintain balance, but rather makes it harder. Faster, in particular, makes the early game much harder, as you can no longer outpace zombies, but have to run away (and repeatedly standing in a corner waiting until the breath has been recovered is very boring), and you have to take them on in a straight fight, rather than hitting them from a distance.
Tougher zombies means you have a big trouble causing any damage to them in the early game, while stronger means you get injured more (requiring boring hiding while recovering, assuming you survived).

Reducing the number of zombies of the current difficulty reduces the tedium of clearing them out, one after another, resting in between each of them. Reducing them a lot reduces the risk of attracting a lot of them at the same time, and thus the risk of getting overwhelmed if you're careless or unlucky (you may run into a gaggle chasing a fox, for instance).

**Comment by JonathanLochridge** [comment]
> Reducing the number of zombies while making them nastier does not maintain balance, but rather makes it harder. Faster, in particular, makes the early game much harder, as you can no longer outpace zombies, but have to run away (and repeatedly standing in a corner waiting until the breath has been recovered is very boring), and you have to take them on in a straight fight, rather than hitting them from a distance. Tougher zombies means you have a big trouble causing any damage to them in the early game, while stronger means you get injured more (requiring boring hiding while recovering, assuming you survived).
> 
> Reducing the number of zombies of the current difficulty reduces the tedium of clearing them out, one after another, resting in between each of them. Reducing them a lot reduces the risk of attracting a lot of them at the same time, and thus the risk of getting overwhelmed if you're careless or unlucky (you may run into a gaggle chasing a fox, for instance).

Interesting points, I definitely agree that speed is much worse for difficulty than sheer number of enemies. Since normal speed enemies give a lot of options for out-manuvering and running away if you can't take them. Which is why the spawn rates for any fast enemies have to be carefully balanced. For awhile wild wasp nest spawns and a couple others were super common. And fast swarms could easily end up in unavoidable death well into the mid game. 
Things like dog zombies are annoying and dangerous fast zombies that aren't terrible. Part of that is the spawn numbers when they do spawn aren't terrible. More dog zombies might be an example of a balance tweak that would make things harder without breaking them on the speed angle.

I could see tougher being an issue. Although, that depends on how that is effected? If you are effectively giving them armor then that would really mess up the balance. More HP when it is a small amount does make fights a bit more gnarly, but I wouldn't expect it to be terrible. I often play with zombie toughness bumped up by 10% or a little more and it isn't too bad.

I personally find trying to recover to be semi-fun since it generally raises tension unless it is mid-game and I am really well stocked. So stronger could be a good option to a degree. The main concern I would have there, is that it might make some of the weaker armors either pointless or almost mandatory. In some ways, I think that kind of approach might work a little better if there was more bad armor available? It seems in practice that most bad armor is either low coverage, or like only 5ish protection maybe. So actual low protection values is mostly for damaged armor. A lot of clothes types items all just have negligible protection now. 
Since that system is more complex. I don't think adjusting strength by that much is a good idea. But a small adjustment could work.

The extra tedium of more damage to heal per zombie, should hopefully be cancelled out by less zombies if the balancing is done well.

Overall, I think Auditing the zombies spawns will do a lot of good though. That together with a slight reduction in overall spawn ratings + a small increase in zombie toughness (And maybe strength)
If we do adjust it, benchmarks will be important.
Overall, we still want the result of a 1 on 1 fight with a basic zombie to be a victory with significant injuries using fists or really early weapons. While using terrain and such or a little better weapons or skills should make coming out with only minor injuries feasible.(unharmed no less than maybe 1 in 4. And a similar rate for serious injuries.)
An actual good early game weapon should still be able to just guarantee a victory if used well against a single zombie.
Overall, I think the threshold for home much harder you can make a single zombie and keep the balance okay is probably around 25-45% if you spread those increases around multiple areas.
When it comes to multiple zombies at once or in short succession:
Currently, this is dangerous early game, but with a window + okay weapon you can often take out 3-4ish with moderate injuries. And 2-3 in the open is going to be really close but you might manage it if you kite well and manage your stamina too.
If 2-3 zombies became like what 4-5 zombies currently are in terms of danger. That would be a significant increase but It would mess up the balance in an obvious way to me. (I may have some more subtle effects though.) This adds a sharper limit of 

So, if we do make zombies harder but less common. We shouldn't reduce their spawn rate to less than 65% of what they were before, or else I am pretty sure the strength increases would destroy the balance early game.  Overall, this seems to imply to me that a 25% increase in scariness for enemies and 25% less would be the most we might push it. 

With that much, that would fix the homeless problem of the tiniest town and make it only 6 people or 12% which is very reasonable. And it would make it to where there were no homeless people.
Honestly, those sorts of effects are more than is needed especially since the apartment PR should be adding a lot more beds realism wise.

Practically, I think a 10-15% increase in toughness with a similar drop in spawn rates is reasonable and would help here. I already play at 10% toughness increased most of the time and it isn't terrible or anything. Although, if you wanted to argue that the difficulty drop by having 15% less zombies is more than the hike by 15% more toughness, we could go for 10 and 15%.

Getting some playtesting of the rough idea from a newer-ish player might be a good idea if we go for that? Or at least some normal playtesting + asking on the discord server if any newer-ish players had tried something similar before and what they thought of it.

**Comment by GuardianDll** [comment]
From Kevin:
> See my reply here as well: https://discourse.cataclysmdda.org/t/lore-rationalizing-why-there-are-too-many-zombies/29245/12?u=kevin.granade
tl;dr we're not going for "each town has the correct number of zombies in it to represent it's former population". That's a nice eventual goal, but right now towns are also the wrong size for that to make sense, and since zombies can't move around to intercept you, there need to be more of them essentially guarding the town from all directions. The goal is to match the amount of threat you encounter when entering a town to what it should be. Now, I'm not going to argue we have a perfect number right now, just that "just dial it down to match the number of houses" is going to end up with the numbers being incredibly low and the threat from zombies being nonexistent. An adjustment needs to start from "ok how many should we have anyway" while taking the above things into account.
