### ISSUE TITLE
We lose the ability to scale fences

### ISSUE THREAD

**Issue by jeffplata** [CleverRaven/Cataclysm-DDA#59032]
### Describe the bug

The ability to climb a fence disappeared.

### Steps to reproduce

Find a fence.
Examine (e) fence.
Nothing happens.

### Expected behavior

Should be given the option to climb a fence.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1766 (21H2)
- Game Version: 4608ba2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by PatrikLundell** [comment]
Note that there are some fences that don't need to be scaled. You can just walk over them with walking taking longer than otherwise (as for other terrain that's difficult to cross). These fences don't react to attempts to examine them.

The fences around farm plots are of this type (barbed wire fences give a warning, but I guess you could ignore that if you wanted to), and the same goes for fences around paddocks. Basically, you can try to walk over a fence, and if that doesn't work you have to climb it by examining it.

Obviously, thinks may have changed such that there actually is a bug there, but I think this ought to be checked first.

**Comment by jeffplata** [comment]
Checked as suggested.
Went to a wire fence. That can't be walked over, ever, but used to be climbed. Made sure not wielding anything. Examined fence. Nothing happened.

**Comment by Smiles-5m1l35** [comment]
Can confirm this is true on latest experimental. 
![image](https://user-images.githubusercontent.com/102507376/177719280-192fa73f-272f-4526-83da-cf9d9b05044f.png)
when pressed nothing happens opposed to the previous prompt allowing you to climb the fence

**Comment by NetSysFire** [comment]
@Night-Pryanik could you look at this please?

**Comment by KHeket** [comment]
And we cant climb over wood fences too. Looks like we fully loosed ability to climb over everything

**Comment by Night-Pryanik** [comment]
Ok, I'll look into this.
