### ISSUE TITLE
Prying furniture / terrain doesn't show "failure": message

### ISSUE THREAD

**Issue by LyranRenegade** [CleverRaven/Cataclysm-DDA#59044]
### Describe the bug

When failing a prying check of furniture it doesn't show the "failure" message as defined in the json.
I don't know if this is the case for all items, but for the custom furniture, terrain I made it's always the case [so never any failure message].
It is also the case with the few vanilla-items i tested:
terrain: t_door_locked_interior
furniture: f_coffin_c

### Steps to reproduce

spawn a closed coffin, try to pry it open with a low-strength character and fail.
no "You pry, but the coffin remains closed." message is shown.

### Expected behavior

i expect the failure message to show

### Versions and configuration

win 7, 
version: 5d5d5bd (tiles)
experimental from 2022-07-04

**Comment by PatrikLundell** [comment]
My current, strong, character occasionally fails to pry open crates with no failure message. My experimental version is a couple of weeks old, and I think this behavior has been present for quite some time before that.

**Comment by Night-Pryanik** [comment]
I found the culprit, it's these lines: https://github.com/CleverRaven/Cataclysm-DDA/blob/414c57e47c7ecc85799dceeb4a2aae5763ae9c6f/src/activity_actor.cpp#L4866-L4870
They were added in #51778.
`breakable` field isn't set for majority of terrain/furniture, and because it's set to false by default, the `handle_failure` function, which should print the failure message, exits very early without printing anything.

**Comment by LyranRenegade** [comment]
awesome!
Would the duration-tag doing nothing in some cases be related to this maybe? (#59045)
