### ISSUE TITLE
Zone changes can fail to take effect immediately

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#59116]
### Describe the bug

I've had it happen several times that I've used custom zones to load things into my vehicle (in particular harvested crops), but then forgotten to deactivate the zones and reenable the unsorted ones. After setting a companion to sort things out, I've found the mistake by seeing them drop items into the vehicle, at which time I've asked them to stop sorting, have corrected the zone settings, and then asked the companion to start sorting again, at which time they continue to drop things onto the now deactivated zones.

### Steps to reproduce

1. Have a vehicle with active Custom zones with no filter in the world tile to the NW.
2. Have the parts from a dismantled vehicle in an Unsorted zone in the world tile to the N.
3. Order a companion to sort out loot.
4. Order the companion to stop as the vehicle parts are dropped into the vehicle rather than their zones (most of them are vehicle parts, of course).
5. Deactivate the Custom zones in the vehicle and activate the Unsorted zones tied to the same tiles.
6. Order the companion to again sort out the loot. The companion hasn't had time to move as the changes are instantaneous.
7. Pull your hair as the bugger continues to sort thing into the now inactive Custom zones.

### Expected behavior

Changes to zone settings should take effect when saved.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1766 (21H1)
- Game Version: 979718d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]
+ JSON "mod" to disable portal storms
+ JSON addition of Workshop recipes for welding supplies.

### Additional context

I'm not sure what's up here, but it's happened several times (there's no cure for forgetfulness) over several experimental versions.

The companion finally realized what he was supposed to do when I've ordered him to stop sorting yet again and waited for him to come close to the PC within the same world tile. After that I ordered him to again sort out loot, and he proceeded to first sort out a pile in the same world tile, then the vehicle Unsorted tiles, and finally the parts from the dismantled vehicle.

I'm not sure if the cause is that several world tiles are involved, or if there may be a need for the PC to move to get caches updated. I think I've moved before ordering the companion to again sort out loot in the past, but can't swear on it.

**Comment by zeziba** [comment]
I have experienced this bug as well.

I play on innawoods though with the same settings otherwise.

Steps:
Create a building zone for anything (large zone size)
Create another building zone.
Start building using the shift+o
Run out of materials or stop construction
Attempt to build again

In the above I picked log walls and pits outside of the wall. The log was were built first as I disable the pits to focus on the wall and to avoid there is a pit spam. 

The game will not be able to finish building any appreciable sized wall as it will get stuck in a loop where it tries to locate the materials and then goes back to the wall section it's building.
As a note small wall sections seem not to have this issue, nor do small zone sizes from my experience.

As a side effect of the above if you manually complete any section of the wall it will auto start working on the construction again as well, do not know if this is intended or not.
