### ISSUE TITLE
Buying from Smokes should drop the bought items on the floor beneath your feet

### ISSUE THREAD

**Issue by Merikona** [CleverRaven/Cataclysm-DDA#59162]
### Is your feature request related to a problem? Please describe.

I just bought 900 or so shards of glass and 100 or so splinters of wood from Smokes, in the refugee center. It tried to put each one of them into my hand, and I spent a long time just pressing enter to drop them individually. 

### Solution you would like.

It would be a wonderful change to instead drop them beneath my feet directly so I won't be stuck in a popup screen after bulk purchases. 

### Describe alternatives you have considered.

Alternative would be not make huge purchases to avoid this issue, waste time holding down the enter key every time, or add an option after purchase to drop everything (1 button press instead of hundreds). I still prefer Smokes just dropping all the items beneath my feet by default though.

**Comment by chrispikula** [comment]
Further thoughts:
Maybe on the counter, instead of on the ground?  It's a poor shopping experience if the teller just dumps your purchases at your feet.

Or a recommendation that you hold a bag, so they go into the bag?  This would be a nice way for them to auto-fill whatever container you're holding.


Ideally, a bunch of loose items should come with a 50c shopping bag or box, but that's probably not happening any time soon.

**Comment by Marrim** [comment]
In an ideal world the solution wouldn't be specific to Smokes. As far as I understand, the problem is that the player is asked what to do when there's not enough inventory space for a new item. And then they suddenly have 1000 new items... If there was a way to just pick an option once (instead of 1000 times), the problem would no longer exist.

Or perhaps we can create an override for items specifically acquired via trade to be automatically dropped if there's no space for them, no query.

**Comment by chrispikula** [comment]
Choosing an option isn't a great solution, as it still takes a long in game & real world time to have items go one-by-one through your hand.  Which is why I suggested a box or a bag.  

Side note, just realized that it'd be kind of thematic for Smokes to give you items in cartons...  :-p
