### ISSUE TITLE
Unable to dig a new shallow pit if adjacent to another shallow pit.

### ISSUE THREAD

**Issue by Oafsalot** [CleverRaven/Cataclysm-DDA#59232]
### Describe the bug

There is some logic problem with digging pits.

If you're adjacent to a shallow pit you can't dig a new pit. You can only dig the pit you are adjacent to deeper.

### Steps to reproduce

Dig a shallow pit with any tool.

While adjacent to that pit activate the tool again and try to dig in any direction other than the first pit.

The game won't let you dig another pit. If you try then you get the error, "You can not build there."

If you now move to a tile that is not adjacent to a shallow pit, but is to the second pit you tried to dig then you're able to dig a new pit there.

### Expected behavior

You should be able to dig a shallow pit in any valid tile regardless of if your adjacent to an existing shallow pit.

I suspect someone inverted the logic for digging pits somewhere.

### Versions and configuration

I'm using the latest experimental build. 2022-07-1306-09.

Bug has been around for a while.

**Comment by andrei8l** [comment]
/confirmed I was aware of this in #57466. The easiest solution is to duplicate the shallow pit definition into the deep pit group (and update the `act_build` test). I've been delaying that because I wanted to migrate constructions to `generic_factory` first but haven't had the time/interest.

You can dig directly from the construction menu though.
