### ISSUE TITLE
Improve Missile Silo Radiation Signposting

### ISSUE THREAD

**Issue by SolventMercury** [CleverRaven/Cataclysm-DDA#59244]
### Is your feature request related to a problem? Please describe.

Currently, the missile silo is a source of radiation, but this isn't made very clear to the player, and it is easy for a player not to realize they are irradiating themselves. Although it's true that a player would expect the missile to be a nuclear missile, a nuclear missile in storage is not a source of enough ionizing radiation to be a risk to personnel, and any other radiohazard is locked behind military keycard doors where a player would not be immediately able to see it, especially given how many doors have keycard locks in the building. This is acceptable in places like toxic waste disposal sites because the presence of such hazards can be assumed, but in the missile silo this is not the case.

### Solution you would like.

There's a number of ways this issue could be resolved, but the common factor is finding a way to tell the player that the site is a source of dangerous radiation. Currently, zombified staff are mostly in either ordinary combat gear or civilian clothes. It might help communicate the hazards of the site to instead place a large number of hazmat zombie spawns in the facility. In discussions it's also been suggested to have some kind of irradiated monstrosities in the facility as well. Obvious nuclear risks could also be placed earlier in the facility, in places a player would be able to see and access without a keycard. If all else fails, there could also just be a sign directly warning of radiohazards being present on site.

### Describe alternatives you have considered.

It might also work to just remove radiation from missile silos.

**Comment by natsirt721** [comment]
The missile and facility are also in perfect condition. If I were in an area with nuclear material and there were signs of destruction, that could be enough of a sign that perhaps the containment structures for the hazards had been breached. As it is, there doesn't appear to be any visible reason that the warhead would be damaged and irradiating the area. Rockets are fragile, and nuclear warheads have [literally fallen out of aircraft without the containment vessels failing](https://en.wikipedia.org/wiki/1961_Goldsboro_B-52_crash); if you can launch the missile, its probably not hazardous.

If there are areas that are intended to store hazardous material (I haven't explored the silo fully), then there should be EXTREMEMLY OBVIOUS signage indicating that. But the signage needs to be before the area is entered, otherwise the sign is clearly in the wrong place.

I'd say take the radiation out entirely, and/or create a variant of the silo that is damaged. Anything else just feels gimmicky.

**Comment by Night-Pryanik** [comment]
> The missile and facility are also in perfect condition.

There is a giant crack in one of the levels, stretched up almost to the missile itself. It might have damaged the missile, hence the radiation.

> if you can launch the missile, its probably not hazardous

You can't launch missile in vanilla anymore.

**Comment by kevingranade** [comment]
Helping stalebot catch up.
 I'm not opposed to this change but we don't need a issue lingering around for a year is just in case somebody notices it.
