### ISSUE TITLE
The breacher load bearing vest has too little pocket capacity for the amount of effort put into making it

### ISSUE THREAD

**Issue by Aeiouuu01234** [CleverRaven/Cataclysm-DDA#59339]
### Describe the bug

The description says:
"This massive vest covered in MOLLE webbing is designed to attach a large number of pouches", and the fact that requires 2 magnets which are not easy to come by, comes into consideration when the **breacher load bearing vest** has only:
**"attach_molle", "size": 8"**
Which is the same size that the normal load bearing vest

I believe that in my personal opinion in should be at least 14 as it is in the heavy load bearing vest or maybe even higher

### Steps to reproduce

check the ammopouch,json

### Expected behavior

i takes 2 days to craft+the time to find the magnets.

Maybe im just ranting, but i think it makes sense

### Screenshots

![Brackets_ojcAsSuV1c](https://user-images.githubusercontent.com/52901609/179374972-fe7871b3-68b3-44d2-8d14-9deda8864089.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1826 (21H2)
- Game Version: cf23f01 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Megafauna [megafauna],
    Deadly Zombie Virus [deadly_bites],
    Tamable Wildlife [Tamable_Wildlife],
    Stats Through Kills [stats_through_kills]
]

**Comment by TheShadowFerret** [comment]
>I believe that in my personal opinion in should be at least 14 as it is in the heavy load bearing vest or maybe even higher

Where would the shotgun go then 🤔

**Comment by AtomicFox556** [comment]
I am the person who added this recipe. The intent here is that it *could* be crafted, but it's only likely worth it if you plan to carry such a specific set of gear in the form of two long arms (or even three, if you also decide to carry one more on your back).

Magnets could be made to spawn in more places if they're too rare, though.

**Comment by Terrorforge** [comment]
The reduced MOLLE capacity is the price you pay for the second enormous holster pocket, so that doesn't strike me as a bug.

However, it's unclear to me why it (and the other LBVs) takes so long to craft. I have no idea how long this would realistically take, but making it 60h with no proficiencies seems way out of line with other recipes. It should probably be more like the [tac vest](https://nornagon.github.io/cdda-guide/#/item/tacvest), which has a base crafting time of 10h, but is also gated behind several proficiencies that add up to about 45h if you lack all of them.
