### ISSUE TITLE
JSON "damage"-flag for items doesn't produce results as expected from the provided range [min, max]

### ISSUE THREAD

**Issue by LyranRenegade** [CleverRaven/Cataclysm-DDA#59378]
### Describe the bug

with this:
{ "item":  "gloves_leather",       "prob": 25, "damage": [ 0, 2 ]  },

you'd expect the leather-gloves to be generated undamaged in 1/3 (?) of all cases.
This however is never the case.

### Steps to reproduce

spawn an item that has the damage-tag with a range that starts at 0.
spawn a million of them, all of them will be damaged.

[Well, i spawned a few 100 of various items all with the same damage-range and never one was undamaged]

### Expected behavior

You'd expect to be able to spawn undamaged items like this as well. 
Would be very handy if it were possible. 

### Versions and configuration

win 7,  
experimental from 2022-07-13-0609
tiles

**Comment by Trioct** [comment]
I think I understand this right. I think the reason is that the min and max damage values [get multiplied](https://github.com/CleverRaven/Cataclysm-DDA/blob/d06b4a2fb38e831b877a4e1da8107b2989ee4e10/src/item_factory.cpp#L3789) by [1000](https://github.com/CleverRaven/Cataclysm-DDA/blob/d06b4a2fb38e831b877a4e1da8107b2989ee4e10/src/itype.h#L1326), and a random number is chosen between 0 and 2000 in your example. From [src/item.cpp](https://github.com/CleverRaven/Cataclysm-DDA/blob/d06b4a2fb38e831b877a4e1da8107b2989ee4e10/src/item.cpp#L783=) (we can ignore the parts I've commented out for the leather gloves example):
```cpp
int item::damage_level( int dmg ) const
{
    //dmg = dmg == INT_MIN ? damage_ : dmg;
    if( dmg == 0 ) {
        return 0;
    //} else if( max_damage() <= 1 ) {
    //    return dmg > 0 ? 4 : dmg;
    //} else if( dmg < 0 ) {
    //    return -( 3 * ( -dmg - 1 ) / ( max_damage() - 1 ) + 1 );
    } else {
        return 3 * ( dmg - 1 ) / ( max_damage() - 1 ) + 1;
    }
}
```
if dmg is 0, return damage level 0, otherwise it's (something >= 0) + 1, so it's a 1/2001 chance of getting an undamaged pair of leather gloves in this example.

Couple examples:
```
<color_c_yellow>|\</color> army pants (poor fit): (min, max) = (-1000, 4000), rng(0, 4000) = 1272
<color_c_yellow>|\</color> pair of boots (poor fit): (min, max) = (-1000, 4000), rng(0, 4000) = 2
```

How were you spawning the item by the way? Through debug spawning I only know how to get undamaged items. Only way I know of is spawning and killing zombies.

**Comment by anothersimulacrum** [comment]
There's a test item group command under info.
