### ISSUE TITLE
Barter Economy Audit?

### ISSUE THREAD

**Issue by descan** [CleverRaven/Cataclysm-DDA#59372]
### Is your feature request related to a problem? Please describe.

I don't know if this is the place to put this, and I definitely know I'm not the person who should run such an audit, but I think it should be noted that the prices of items and their worth to merchants *really* should be audited. Some items are way out of proportion to their worth, like adhesive bandages being x15 the worth of the all-around-better bandages, while others are worth a modest amount but are *so* abundant that they make trading with anything else a joke, like cotton patches. 

### Solution you would like.

As I said, the whole gamut of prices should be looked at, and perhaps some best practices put in place if they aren't already for future items.

### Additional context

Such an audit might need should wait unless/until some sort of supply and demand curve for items is added, the idea of stockpiling "always want" items like non-perishable food and medicines while devaluing other items less the more of that item that they have, and NPCs/factions valuing items differently from each other. (i.e. the Exodii wanting metals, guns, and examples of our knowledge more, the Merchants wanting food and medicine more, while the Hub wanting data and scientific gear more, etc.)

**Comment by Inglonias** [comment]
This is one of those "easier said than done" things. There are a LOT of items in the game, and something like this would most likely be done piecemeal rather than all at once due to the sheer amount of work it would take. Not to mention that in real life all these things would be subjective. Bullets are no good if they don't fit any of the guns you already have, for instance.

**Comment by descan** [comment]
> This is one of those "easier said than done" things. There are a LOT of items in the game, and something like this would most likely be done piecemeal rather than all at once due to the sheer amount of work it would take. Not to mention that in real life all these things would be subjective. Bullets are no good if they don't fit any of the guns you already have, for instance.

Indeed, I didn't write this with the intention of one person doing it in an afternoon. That might be possible for writing up best practices for the future, but even doing a once-over to align things like the bandages thing (items that are strictly worse than another shouldn't be worth more than their superior version) would take a long time, let alone working out an objective way to handle subjective pricing.

I was under the impression that that's what an audit would be - a long-term project of piecemeal fixes that people contribute towards with a common goal, rather than something one person does all on their own all at once.

**Comment by Inglonias** [comment]
You don't have anything to apologize for. Many times issues are made with vague, sweeping suggestions like, oh, I dunno... "Balance the prices of all the books" (#56516) and then nothing happens. You'll note the author on that particular issue is me, so I'm guilty of this too.

**Comment by Maleclypse** [comment]
I appreciate your enthusiasm but please look in the docs folder before building an issue around missing documentation.   POSTAPOC_PRICE_GUIDE.md already exists.  If you wanted to create an issue with a list of items that don't follow that guideline or places that guideline clearly creates perverse incentives that would be helpful.  Thanks!

**Comment by descan** [comment]
Fair enough, guess this is a little out of place then. :P

**Comment by Cimanyd0** [comment]
Looks like both of these two happen to be caused by recent changes. Rags used to have no barter value at all but after the tailoring rework cotton patches are $0.50 which is way too much. There is already an issue about this:  #59129

Originally adhesive bandages were a set with 10 charges. #57968 removed the charges and made the volume and weight fit a single one, but didn't change the description, price, or barter value (`200`) so every individual band-aid is now $2.

Real bandages are also `200` ($2) in the code but have `"stack_size": 9` so it's divided by 9 for $0.22.
