### ISSUE TITLE
The "death_drops" will not change after upgraded

### ISSUE THREAD

**Issue by jeremyAIII** [CleverRaven/Cataclysm-DDA#59379]
### Describe the bug

Now, after a monster has been upgraded, their "death_drops" will still use the list they had before they were upgraded. For example, after a zombie is upgraded to a hulk, the "death_drops" will not be "mon_zombie_hulk_death_drops", but the list they had before they were upgraded.

### Steps to reproduce

1. Create a world about two years later, monster upgrade speed for the default
2. Use the Debug function to move to the lab and kill all monsters
3. Check the Hulk's corpse. Their drops will still be before they upgraded.

### Expected behavior

If "death_drops" has been set, it should be.

### Versions and configuration

-Windows 10
-Version: 2022-07-17-1206

**Comment by PatrikLundell** [comment]
The only reason evolved zombies should drop something different from what they evolved from is because they somehow create extra items themselves (such as the stinger that one zombie has unless fired) or had something happen that caused them to drop some of the items they had originally. It's the same creature that has morphed, but it shouldn't have dropped some items and picked up others over time.

**Comment by jeremyAIII** [comment]
Maybe. But the bug is still need to be fixed.
First, if the zombie evolved into Hulk, due to the size of his body will tear the wearing clothes. This bug will allow him to continue keeping the wearing clothes before it evolved. I think this is the reason why the Hulk's death drops list will be set up to another item group.
And then, if a mod uses a different drop list when a monster evolves, it will not be able to get the drop items of the evolved monster because of this bug. Perhaps the monsters on the mod have intelligence, or like more smart feral human. They will be able to have different drops because of the evolution.

**Comment by PatrikLundell** [comment]
I agree the bug should be fixed.

I also believe the evolved creature drop list should be fixed to remove the clothing that's destroyed, keeping the rest of the stuff.
It's true mods ought be able to override evolved monsters with different drops for mod reasons as well.

**Comment by jeremyAIII** [comment]
I'm glad to see your comment. Let's hope CDDA gets better and better.

**Comment by Terrorforge** [comment]
This is not a bug, this was an intentional change. Monsters retain their death drops when transformed. I can't find the relevant PR just now, but I believe this was implemented to resolve the absurd situation where, for example, a zombie soldier would get turned into a fungal zombie and all its military gear would mysteriously vanish, or a SWAT zombie would become a kevlar zombie and suddenly have military drops.

However, you're right that this can also lead to absurd situations, like a hulk still having clothes. There are lots of complicated ways to find the perfect solution to this, but one of the quicker and easier ones would be to add an override tag so that a particular kind of monster always uses its own death drops, even after transforming.

**Comment by jeremyAIII** [comment]
So that's how it is, I understand. As you said, adding an override tag is a quick and easy way to do it.
I will look forward to updates on this. Thanks again for your comment!
