### ISSUE TITLE
Cars should not stop quickly

### ISSUE THREAD

**Issue by mora145** [CleverRaven/Cataclysm-DDA#59385]
### Is your feature request related to a problem? Please describe.

It is somewhat annoying and unrealistic to see an armored truck reduce its speed from 50km/h to 0 km/h in only 2 seconds. It also applies to cars, and all other vehicles. 

I know that 'brakes' have not yet been implemented as objects on a vehicle, but doing this beforehand could advance some work in the future (if 'brakes' will be added as vehicle parts).

### Solution you would like.

I did some research and determining the braking distance is a bit complicated. But I found a page that can give some insight into this. 

Doing the calculations will depend on the terrain where the vehicle is located, the weight, and of course the speed. 

[Distance brake](https://avtotachki.com/en/tormoznoj-put-avtomobilya-vse-chto-nuzhno-znat/)

### Describe alternatives you have considered.

In case the above cannot be done yet, an increase of the braking time could be implemented according to the current speed of the vehicle only. 

![image](https://user-images.githubusercontent.com/25883820/179442446-3b36f09d-ff4f-434c-94c1-7032cd60f354.png)

This image generally illustrates that. Sorry if it is in Spanish. The titles would be: Speed, Normal Braking Distance, Braking Distance (emergency).

**Comment by liminalRoar** [comment]
I completely agree. Given the limitations on driving in CDDA (view distance, limited speed, turning and movement increments, etc), some small sacrifices on realism for the sake of making it more manageable is worth it.

**Comment by KHeket** [comment]
> I don't like this because it interacts very poorly with the game:
> 
> * When driving a vehicle in real life you don't have a 30 meter visibility range. You can zoom out to get a somewhat longer range, but then many obstacles are too hard to discern on the screen (and the reality bubble max range is 60 meters anyway).
> * Real world vehicles don't swivel around a central position, but are steered with the front wheels.
> * Real world vehicles don't change shape when moving in non cardinal directions.

Dont forget, that real world car dont have 20-30 or more wheels, which will improve car slowing down

**Comment by PatrikLundell** [comment]
Large trucks tend to have a lot of wheels, but are nevertheless worse at stopping than normal cars, so I'm not convinced by @KHeKet's argument: those wheels are attached to vehicles with extreme masses.

**Comment by KrunkySmokin** [comment]
> Large trucks tend to have a lot of wheels, but are nevertheless worse at stopping than normal cars, so I'm not convinced by @KHeket's argument: those wheels are attached to vehicles with extreme masses.

Large trucks also weigh a lot more than normal cars, and are often transporting some manner of cargo that causes that to mess with the braking of a vehicle. If large trucks were 'worse' than normal cars at braking, every car that brake-checks a semi would be a pancake. Besides, more wheels would allow more brake mechanisms to be implemented.

**Comment by PatrikLundell** [comment]
I'm not against a vehicle with insufficient breaking power compared to it's total weight taking longer to stop, but it would first require the introduction of breaks, and then a careful balancing such that it's still playable (i.e. still very much shorter stopping distance than in real life. The "normal" point should be close to what we have today, so overly heavy/overloaded vehicles would be harder to drive, but they'd still be controllable at the minimum speed, as the game imposes an artificial restriction on how slow you can go).

**Comment by mora145** [comment]
> I personally would be open for some calculations depending on weight and speed for stopping distance. I don't think complete realism would work considering other vehicle concessions due to limitations.
> 
> We don't have brakes for vehicles yet, correct? That should really be a component. brakes are one of the most replaced parts on a car. Would be kind of funny to find a nice vehicle but forget to check the brakes and realize it can't stop well and crash into a building. We could have a couple grades and/or types of brakes.
> 
> (Tangential) Even bicycles should need brakes (to effectively stop, since feet _can_ be used. Including caliper brakes and superior disc brakes as options would be good. Eventually expanding bike types commonly found would be great. Road bikes, Mountain bikes, BMX bike, Cargo bikes, maybe a type of "racing" bike, each with their own strong suits.

Good commentary. I think the same. There is also supposed to be a more important use for seat belts; right now they are almost irrelevant because of how easy it is to brake in the two seconds, almost nobody hits a tree or a building because of that, so they are totally overlooked. 

If brakes are implemented to take a car and go at 100km/h it should be very well thought out, so you should make a check of the number of brakes on the vehicle and the state they are in.

**Comment by liminalRoar** [comment]
Do we currently have multiple styles of wheel? i know there are sizes but. Different types of tread could be useful. "all-season" tires, winter/snow tires, offroad, racing, etc. could be useful. These would change how well they perform in different terrain and weather, gas consumption to an extent, and handling and braking.

**Comment by PatrikLundell** [comment]
Yes, you're implicitly putting on the seat belt when using a seat that has one. Presumably all the dummies died off in the cataclysm...

Yes, the wheels do make a difference. It's very noticeable for a bicycle with normal wheels vs off-road ones when traveling off-road, and they do affect fuel consumption and acceleration as well, as far as I understand. The missing component is the breaks, and I agree with @liminalRoar's description of the goal for that.

**Comment by liminalRoar** [comment]
Okay that is great to hear, i wasn't sure how in depth wheels were yet. Obviously you would use a seatbelt for normal driving, but i could see the option being useful (assuming mostly that it takes a small time to attach/detach). 

- Quick escape from close enemies (sure, only takes a few seconds to put on a seatbelt, but every second counts).
- Situations where you are going slower speeds and plan to dive out the window
- If using weapons while driving. That should be more difficult with a seatbelt on.

Would also open up the possibility for cars to have non-functioning seatbelts in need of repair or replacement, where you can drive with them, just with greater risk in the case of a crash.

All that being said, i'm totally fine with it just being something we know the character uses always, but i'm not opposed to making it an action one can choose to do (wearing/not wearing a seatbelt) And making it something you can do manually or "auto use seatbelt when taking control of a vehicle"

**Comment by PatrikLundell** [comment]
You can dive out from a moving vehicle just fine (after dismissing the warning). Taking control of a vehicle without applying a seat belt (when present) would have to be a separate action that shouldn't be the default one (if you find that to be a nuisance, remove the seat belt).

If you (or someone else in the vehicle) isn't wearing a seat belt (because their location doesn't have it or it's broken) they'll be thrown out of the vehicle through the windscreen (if there is one) if the speed is high enough (and whatever you're hitting is sufficiently unyielding, like the concrete shrub in 0.E-2 (and probably earlier).

**Comment by liminalRoar** [comment]
Gotcha, sweet!

**Comment by deafmole** [comment]
I want to add, that if breakdistances would get added(/changed to 'realistic'), that would also lead to a broken autotravel. That can of course be mitigated by additional code, but seems overly complicated for such a minor thing. I always imagined brakes being part of 'vehicle controls'.

**Comment by liminalRoar** [comment]
The biggest difference between real life and CDDA vehicles that i see cannot likely be compensated for. It is just too easy to drive around most everywhere. I'm not sure i'd want it different, and a game like this can only be so realistic. Braking isn't my biggest concern with vehicles.

In a scenario like ours, there would be broken glass, concrete, and shrapnel everywhere in cities and on roads. Most roads would be blocked. The ones that aren't would be guarded, booby trapped, have sections torn up or missing, etc. Those that could be traveled would be nearly impossible to any distance without getting a flat tire. 

Offroad would be far more difficult as well. There are ditches, steep hills, sticks, rocks, holes, mud. So many ways in which a car could get stuck or be unable to pass. 

CDDA will never represent how difficult driving in a post apocalyptic setting would be. Certainly with regular vehicles. Mentioned hazards aside, vehicles are so advantageous because they would be. But perhaps there are good ways to balance them out in regular gameplay while keeping it an enjoyable experience.

Perhaps difficult end game locations that should be traversed without vehicles for one of many reasons. Or areas/enemies that can pose particular threats or target vehicles. Or just entire areas that are inaccessible to them, like pocket dimensions.

**Comment by PatrikLundell** [comment]
I don't see why roads would be significantly more blocked than they currently are. Road blocks from riots?
Who would guard road? There aren't anyone left, and the same goes for booby trapping. The only thing tearing up roads would be cataclysm monsters.

Off-road is easier in the game than I assume it would be in reality, but that shouldn't change until the road network generation actually connects roads to a reasonable extent.

Entire areas inaccessible to vehicles: That describes the subways and labs fairly well (Yes, you can bring a bike down there to speed up travel and haul loot, but it can't be used as protection).

@mora145: There is already a crash system and seat belts. Apart from unsuccessful driving (including resulting from skidding), there is also the case of running into massive monsters and using vehicles as battering rams. I certainly wouldn't want to run into a mi-go tower with a sufficient speed to have a decent chance to crack it without a very good seat belt.

**Comment by anothersimulacrum** [comment]
> I don't see why roads would be significantly more blocked than they currently are.

It's the apocalypse so everyone's getting in their car to flee? Besides that, I haven't done any math to check, but I'd be very willing to be the car to human, and potentially even the car to house ratio of DDA is a fair bit less than the real world - it's another of those demographic issues there is.

**Comment by PatrikLundell** [comment]
Well, I can see no other reason for all the wrecks and broken down cars all over the roads than for them to be left behind by people fleeing. Some of these cars appear outside of "cities", indicating some fleeing people got out of there.

However, if by "blocked" you mean a couple of pile ups with a compact double line of abandoned cars behind it I agree it would be realistic based on what happens when foreseen calamities happen (like hurricanes).

**Comment by liminalRoar** [comment]
This is moreso what i meant. not that the streets would literally be filled up. But there would be more pileups and sections blocked by wreckage and such.

**Comment by mora145** [comment]
The question would be: 

- How hard will the game make it to get around those obstacles with a braking system, and ride around town in the middle of the pile-ups? 
> I think it will make you think twice before entering a city with your best car. (Optionally it talks about the health of the tires. It also makes sense to not want to enter a city that has sharp debris, and not have armored tires.) Logically we don't see debris all over the roads, but we do see debris near buildings or other damaged vehicles. 

- How hard will it be to drive a heavy load vehicle with poor brakes? Does it make sense?
> It makes a lot of sense to me. I would not prefer to enter a city with a huge truck, braking and maneuvering will be very difficult. Of course it is a good idea to use a small vehicle with fast braking. 

- On long distance trips I usually accelerate to more than 80km/h because I know that my car will brake in less than two seconds xD? 
>I usually travel at night. But what would happen if this changed, and instead of 2 seconds it took 8 or 10 seconds and suddenly there was a traffic jam? If I am not wearing my seatbelt, that crash would hurt me a lot. To that I could add the bad condition of the wheels, brakes and the weather. I think I would think long and hard before accelerating so fast after such an upgrade.

The idea is not to break the game, but to add a well-balanced difficulty component that makes us think about what to do next. 

The talk about seat belts makes a lot of sense. In the city we don't want to get stuck if something goes wrong and we need to get out of the vehicle fast.

**Comment by PatrikLundell** [comment]
- Why do I want to travel through towns in the first place?
1. That's the only route. The only road goes to the town, and there are no plains to go around.
2. Gather loot. Having to park outside and run back and forth with a shopping trolley gets tedious very quickly.
- According to reports there are lots of trucks that are stopped on the road and banned from being driven further on the spot due to poor brakes (where I live). Those same trucks tend to be severely overloaded as well, so there are presumably lots of people with experience. I would expect the case to be even more extreme in third world countries.
- My limit is 51 km/h. If it took several reality bubbles to break you'd be forced to slow down to a crawl. The only good thing about that is that it wouldn't cost you game time to use auto drive (assuming it still would work), as you can't go faster anyway.

**Comment by chrispikula** [comment]
There'd also be destroyed buildings spilling onto streets, and whatever havoc hulks vs the military would have caused.

But, yeah, with the range compression due to the reality & vision bubble, I agree that braking should be likewise magnified.  As it's currently wishy-washy, and not a fixed compression amount, I don't know how finding calc's is going to help all that much?

**Comment by kevingranade** [comment]
Closing stale discussion that played out almost a year ago. 
More nuanced breaking is fine,  but as the discussion highlighted,  it's more nuanced,  not just "make it slower".
