### ISSUE TITLE
Inappropriate Quests from Evac Shelter NPCS

### ISSUE THREAD

**Issue by ANickelN** [CleverRaven/Cataclysm-DDA#59430]
### Describe the bug

Evac Shelter starting NPCs seem to give out the incorrect quests, often talking as if they were a member of the Refugee Center.

### Steps to reproduce

Start a new EVAC SHELTER start and talk to the starting NPC, often they will give you a quest that will in some way help the refugee center.

### Expected behavior

Evac shelter survivors should give out the appropriate quests, and not quests that have to do with the refugee center they are not a part of and aren't aware of.

### Screenshots

![image](https://user-images.githubusercontent.com/52714184/179876315-8cada53c-fcc3-4583-bcb5-c455ad00ae2d.png)
![image](https://user-images.githubusercontent.com/52714184/179877203-0dcf4466-9bc7-4cbf-bcf4-9369896eb61c.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1826 (21H1)
- Game Version: b9db130 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by ReynTheLord** [comment]
![image](https://user-images.githubusercontent.com/37010048/179887892-c4c2dc22-2447-4784-ba41-d9091fc4a224.png)
potentially relevant

**Comment by ANickelN** [comment]
>potentially relevant

Seems like the same issue described above, what version was that taken on?

**Comment by DamienRoyan** [comment]
![image](https://user-images.githubusercontent.com/88375697/180185729-77a636e7-73a2-48dd-90bc-a78b5f8b9395.png)
Can confirm. Have never seen this in Refugee Center, but this is definitely not an Evac Shelter NPC mission.

![image](https://user-images.githubusercontent.com/88375697/180186337-6cf80b86-817b-401d-99be-4fd0e8c00c05.png)
I remember this is a Homeless camp mission


![image](https://user-images.githubusercontent.com/88375697/180186741-be70a9c4-8ebd-4104-bd73-2e475e68bc9b.png)
However it seems the normal missions aren't completely gone, because I have this. So it seems the game is pulling missions from the whole roster


- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 2b29aca [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    Bionic Slots [cbm_slots],
    No Rail Stations [No_Rail_Stations]
]

**Comment by DamienRoyan** [comment]
I also had one for adding a gate for the Refugee center and yesterday, one about changing the fence into a wall.

I got frustrated that another Evac NPC had a over advanced mission (1st screenshot) and remembered this issue existed

**Comment by descan** [comment]
I'm also getting these types of missions - the last three starts I've done, have been Logging Camp (?) missions.

**Comment by Maleclypse** [comment]
The two merged PRs working on this plus the documentation fix should mean this is closed.
