### ISSUE TITLE
Tow cable desyncs after save and load

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#59546]
### Describe the bug

After attaching a heavy duty tow cable to my fire engine and towing a cargo van, I found that after saving and reloading my truck would no longer tow the van despite both still having the heavy duty tow cable attached. I found that I could then remove the cable from both vehicles, causing it to be duplicated. Lastly, when trying to drive my cargo van to get it in position to be towed again, I found that its intended speed was set to be over 100 mph and I rapidly accelerated and nearly crashed without realizing it.

### Steps to reproduce

1. Find two vehicles.
2. Connect via tow cable and drive around to confirm tow cable is towing.
3. save and quit.
4. load game again.
5. Attempt to tow the car and fail.
6. Remove the tow cable part from each vehicle, receiving two copies.
7. Attempt to drive the towed car and notice its speed shot through the roof as you start it up instead of being at 0 mph.

### Expected behavior

Tow cable should not destabilize the fabric of reality.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1826 (21H2)
- Game Version: 954e682 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots]
]

### Additional context
I was also super disappointed to find out I couldn't make a convoy of multiple vehicles chained together with tow cables. What structural barriers in place prevent this from happening?
_No response_

**Comment by PatrikLundell** [comment]
I believe I've encountered the duplication on occasion, but not regularly. A wild guess would be that it might happen if the vehicles are further away from each other than the normal maximum distance (such that the cable is on the verge to snap off.

The second issue is always there. Whenever a vehicle has been towed, it's set to a very high speed. You always have to remember to bring the speed down, or you risk a crash. This bug is not related to snapping cables. I don't know where that speed is set and why, nor do I know how to determine when towing is done so the speed should be reset to zero.

There is a couple of reasons you wouldn't want to have a towed vehicle tow a third one:
- The amount of weight a vehicle can manage is limited, so much of the time it wouldn't be able to pull more than (at most) one anyway. You can't fit a vehicle with more than two engines anymore, so you have a hard blocker there.
- It's hard enough to tow one vehicle given how the towed vehicle sways and the density of obstacles you have to navigate around. I can't see you being able to do anything than going in a straight line with any degree of control, and you can't go very far in a straight line before you encounter an obstacle. It might work on a salt flat, but there aren't any of those in the game.

**Comment by epsimpson** [comment]
I just experienced a strange series of tow events while towing wrecks off the road, including the tow cable duplication issue.  I could provide any of 3 save files, and the error messages that preceded them, if requested, to help debug.
1. save file after tow cable attachment (made because I couldn't tow without using cruise control, which seemed buggy).
2. save file immediately after towed wreck crashes into building, destroying vehicle tile where tow cable had been attached, and after `spacebar` through errors.
3. save file after stopping vehicle and removing tow cable, `spacebar` through errors, and seeing heavy duty tow cable (active) on ground.

After all that I found the duplicate tow cable among the flotsam left by crashing the towed wreck.

I'm using:
 - OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.5 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.F-11610-g90fc2e4586 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]
