### ISSUE TITLE
Rework daily_health (and maybe health_tally)

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#59557]
### Is your feature request related to a problem? Please describe.

After doing a bunch of testing and having/reading some discussions in #59505, #59499 and #59547, I've concluded that there are some problems with the health system. The basic player-facing one is that health tends to become locked into a seemingly unbreakable spiral. It can trend upwards, but it's more likely to get stuck trending down. But perhaps a deeper problem is that it's overly complicated, as even experienced devs and have struggled to figure out why it behaves the way it does.

On a quick overview of #57331, the system seems simple enough: store the player's health shifts for the day as daily_health, store the last seven of those as health_tally, take the average of those and add it lifestyle every day. All of that is mostly true, but it's easy to miss that the player's health history is effectively stored three separate times:

1. Daily health is appended to health_tally, as intended and expected.
2. health_tally does not actually store the last seven days of health changes. Every day, when lifestyle is modified, health_tally is treated as if it's the total of the last seven days of health and averaged. lifestyle is increased by health_tally/7, and health_tally is reduced by the same amount. This means that rather than being purged from the tally after seven days, values added to health_tally [asymptotically approach zero](https://www.wolframalpha.com/input?i2d=true&i=Y%3DPower%5B%5C%2840%29Divide%5B6%2C7%5D%5C%2841%29%2Cx%5D). This becomes particularly noticeable with large values; if you manage to get health_tally to -200, then assuming you were otherwise health neutral, it will still be  [-23 a full two weeks later](https://www.wolframalpha.com/input?i2d=true&i=Y%3D-200Power%5B%5C%2840%29Divide%5B6%2C7%5D%5C%2841%29%2C14%5D).
3. And this the big one: daily_health is not reset at the end of the day. Rather, it decays at a rate far slower than the player's ability to add/removed health. Supposedly it decays faster at higher numbers, but I haven't checked the math. Anecdotally it seems to hover around +/- 70. Remember, this number is added to lifestyle _every day_.
I suspect this means daily_health can amplify small health boosts, e.g. if you have +10 every day for a week, daily_health will ramp up and the game will act as if you've had +30 for a week. I think this is what caused me to be gaining ~25 health per day while doing nothing to prompt other than getting plenty of sleep, but I wasn't able to confirm; see my complaints about the debug tools in #59499
What I'm quite sure it means is that if your health changes massively in a day, it becomes very hard to shift. And because there are ways (like radiation) to quickly amass lots of negative health but no equivalent the other way around, this is almost always a massive negative change. For example, if your daily_health hits -200 one day, this is firstly going to torpedo your health_tally; if you aren't maintaining a an effective daily health of around 30+ every single day, you're immediately in the negatives. But secondly, even after days of decay, your daily_health will stay low. I had something like this happen recently, and in testing my daily_health was still at -47 after three days. It would've turned positive faster if I'd tried to get healthy, but as mentioned it's hard to accumulate more than maybe a few dozen positive health per day, so it still would've remained in the negative for days. And of course, that entire time it will continue dropping health_tally further and further, so that even when daily_health turns positive, health_tally will remain negative for a good long while. And unless you were really healthy to begin with, the drop could be very fast. I haven't tested the exact rate, but it's entirely possible that hitting -200 daily_health once condemns you to hit -200 lifestyle and spend weeks recovering from that.

### Solution you would like.

Make daily_health what it sounds like it's supposed to be - a tally of the day's health changes that gets reset at midnight. This would fix most of the comprehension and balance issues immediately.

You could also make health_tally an array that actually holds the last seven days values for daily_health instead of just a total and drop the oldest value every day. The main benefit of this would be comprehension, as I think the current math is actually fine. It _would_ be a little weird if you could irradiate your face off, be sickly for a week, and then magically blast back to normalcy without even trying once the week is up. Sure, in a vacuum the current system ensures you will practically never recover, but if you're actually trying to be healthy it should happen quickly enough.

### Additional context

I wasn't sure whether to classify this as a bug report or a feature request. It seems wrong, but I'm not sure it's unintentional. Either way it's worth having a disvussion about so I guess it goes in the "let's talk about it" category.

**Comment by I-am-Erk** [comment]
Daily_health is definitely meant to reset after adding to the health tally. We should take a look at how the math will shake out once that is fixed.

In general doing that would help health tally work, but it remains brittle based on the assumption we keep health changes fairly small. The health tally problem can be solved by keeping an array of the last seven values for daily health, and instead of reducing health tally by the lifestyle change, we reduce health tally by the oldest value in the array and then remove that value. Basically we remember the specific daily health values and make sure they are removed when they become more than a week old, rather than assuming that the changes are fairly uniform.

**Comment by Monopool** [comment]
I mentioned this in #59505 and have been debating on making a new issue, but I'll just bring it up here as well in a shortened form. Junk food is in dire need of a rework too because some of it is arbitrarily just poison now and practically inedible even if your character is active, maintains healthy weight, etc.

For example, it makes no sense that one serving of ice cream penalizes you directly even if none of the components do (mixing and freezing makes them magically unhealthier). It makes even less sense that it's worse than eating a bunch of pure mayo, heavy cream, butter, syrup, cooking oil, sugar, chocolate bars, milkshakes, shelf stable chocolate drinks, etc. They all lack the negative health penalty, but going through the significant effort of making and freezing ice cream isn't worth it because it suddenly turns into poison.

With the lack of inherently directly "healthy" food, I think "unhealthy" food should be standardized to the new system as well. It shouldn't immediately and directly hurt your health unless it has another reason behind it (ex. atomic energy drinks, methacola, dangerous chemicals, mild toxins like raw potatoes, etc.). Since being overweight or having a lack of vitamins is already covered by the new system, perhaps it might be best to just let them speak for themselves.

If we want to punish people, maybe add a negative health "vitamin" instead for stuff that is heavily processed/preserved to discourage consumption in excess, better match the ratios at which they eat it, and perhaps cap out the amount of health lost at once? Sugar-Loving and Sweet Tooth mutations could reduce/negate it and Junkfood Intolerance could suffer from it worse.

**Comment by Terrorforge** [comment]
The reason I wasn't sure if it was supposed to reset or not is that you explicitly said it _is_ supposed to decay, and if it resets to 0 every 24 hours, I don't really see the point of reducing it slightly every 6 hours.

**Comment by I-am-Erk** [comment]
It's been a very long time since I looked closely at the math, but if it's not decaying to the equivalent of zero then that's the same error and the decay is being calculated incorrectly.

**Comment by Terrorforge** [comment]
The relevant lines of code should be 4354 to 4358 in character.cpp
`if( calendar::once_every( 6_hours ) ) {
        // And daily_health decays over time.
        // Slowly near 0, but it's hard to overpower it near +/-100
        set_daily_health( roll_remainder( get_daily_health() * 0.95f ) );
    }`

roll_remainder is just a rounding function, so I'm pretty sure all that does is reduce daily_health by 5% ever 6 hours

**Comment by I-am-Erk** [comment]
Ah, I  would guess that's old code from before the rework that didn't get removed... There was nothing about daily health decaying in my original concept, mostly because I hadn't closely looked at the code at the time. It can almost certainly be excised, since the role of decay is now played by the health tally system

**Comment by Terrorforge** [comment]
In a [comment](https://github.com/CleverRaven/Cataclysm-DDA/pull/57331#issuecomment-1115160335) on #57331 you said:

"Once we have a few of the proposed health modifiers in place we can remove the thing where daily_health trends towards zero, I believe, and it will instead naturally trend towards a neutral-ish number based on your activities. It might be appropriate in this PR to make daily_health decay slower, like every 6 hours or so." (It seems that previously it did the multiply by 0.95 thing every time update_health was called, which I think would've been every 30 minutes)

Not sure what you were thinking, but I _am_ sure that wrapping my head around this code and math made my head hurt, too, so I get it.

**Comment by I-am-Erk** [comment]
I suspect I had a mistaken idea of how the daily health decay was working in the first place, but it's impossible to tell what Me of the Past may have been thinking. Sometimes, Me of the Past was very clever and Me of the Present is too stupid to see the whole thing, but I think this time Me of the Past just hadn't fully processed all everything. what a goober.

Anyway it is worth a quick safety check but I am *fairly* sure that, unless Daily Health directly affects some other stats, it is now just what I call an `accumulator`, which get used a lot in the slow change systems I've designed - a variable that does nothing except build up in order to change another variable. Accumulators shouldn't need a lot of fancy math, they just accumulate and then reset.

**Comment by Zireael07** [comment]
@I-am-Erk That's why you need comments and design docs in a project this large, so you can tell half a year later what Past Me was thinking when writing this/naming this etc

**Comment by I-am-Erk** [comment]
Well sure but in this case it was past me writing an issue, and then probably going on to talk to a patient in the middle of it and not finishing the issue.

**Comment by Trioct** [comment]
Just felt like looking into it a bit and decided to try to visualize the health system for myself and thought I'd share if maybe anyone finds it useful. I got ahead of myself and accidentally [implemented it](https://github.com/Trioct/Cataclysm-DDA/tree/adjust-health-system). If it's any good, @I-am-Erk can steal it for #59267, or I can make a pr. Whatever.

This is the current system vs the simple 7 day array health_tally and a lifestyle that adds the average every day.
Every day the first 2 weeks are all -10 days, the next week is all +5 days.
<details><summary>Expand</summary><p>

![image](https://user-images.githubusercontent.com/4079502/184606651-3a39b996-5cda-4cc3-84b7-ed53878d780d.png)

</p></details>
And just to show what happens if you manually reset lifestyle to 0 after 2 weeks, keeping everything else the same, to try to visualize the momentum, similar to #59547's scenario:
<details><summary>Expand</summary><p>

![image](https://user-images.githubusercontent.com/4079502/184607577-9454f016-9878-48c1-aef9-e2fe7aa81a03.png)

</p></details>

**Comment by Terrorforge** [comment]
That's interesting and illustrative, bit it's not actually the most realistic test case. There are very few things that give a slight penalty to health, so you're unlikely to consistently be -20 for several days. On the flip side, things like eating food and getting enough sleep have small positive modifiers, so without a penalty you'll trend towards a few points plus without even trying.

So the more relevant case is one day at -200 followed by several weeks at +5.

**Comment by Trioct** [comment]
Sure, I just gave an example. I've tried many different scenarios for myself of course. I think you'll notice that the current method is just a more extreme, sensitive, and longer-affecting version of the simplified version. Like for -200 the first day here's:
<details><summary>+5 for the next 19 days</summary><p>

![image](https://user-images.githubusercontent.com/4079502/184628466-1353f3a1-7c4d-4a3c-aff6-d95a8cc52dc1.png)

</p></details>
<details><summary>+5 for the next 20 days</summary><p>

![image](https://user-images.githubusercontent.com/4079502/184628533-a54a48fd-4ffa-42f5-81d4-aa9b9c52366b.png)

</p></details>
<details><summary>+5 for the next 21 days</summary><p>

![image](https://user-images.githubusercontent.com/4079502/184628570-d4e85362-1f04-48e9-8f97-2c8ba1e7915d.png)

</p></details>
Starting from scratch again here:
<details><summary>+5 for a week</summary><p>

![image](https://user-images.githubusercontent.com/4079502/184628918-aa2a44d5-8412-4dd9-99a1-15331a7d4c4e.png)

</p></details>
And since current uses roll_remainder and therefore has rng:
<details><summary>-5,-4,-3,...,3,4,5 bad run</summary><p>

![image](https://user-images.githubusercontent.com/4079502/184630132-967c8017-86a1-4049-b1a1-72226e1b5d6e.png)

</p></details>
</p></details>

<details><summary>-5,-4,-3,...,3,4,5 good run</summary><p>

![image](https://user-images.githubusercontent.com/4079502/184630197-bff9d661-c32b-4d06-a16d-d86d233c2832.png)

</p></details>

**Comment by Terrorforge** [comment]
Very helpful, thank you. Those graphs seem to show that even with the intended systems, a single bad day can absolutely crater your health in a way that can take weeks if not months to recover from. It'll be less bad because you don't go all the way to -200 and stay there for weeks, but it's still pretty bad.

The root cause is still that it's at all possible to get -200 daily_health basically instantly with no positive effects of remotely the same magnitude. But perhaps there should also be some normalizing effect? It does also seem weird to me that under this system you don't actually have to maintain your healthy habits once you hit the max, so maybe there should be a slight normalizing effect where Lifestyle trends towards 0?

**Comment by fungamer2-2** [comment]
> Very helpful, thank you. Those graphs seem to show that even with the intended systems, a single bad day can absolutely crater your health in a way that can take weeks if not months to recover from. It'll be less bad because you don't go all the way to -200 and stay there for weeks, but it's still pretty bad.
> 
> The root cause is still that it's at all possible to get -200 daily_health basically instantly with no positive effects of remotely the same magnitude. But perhaps there should also be some normalizing effect? It does also seem weird to me that under this system you don't actually have to maintain your healthy habits once you hit the max, so maybe there should be a slight normalizing effect where Lifestyle trends towards 0?

That makes sense, I also think that `lifestyle` should decay towards zero.

**Comment by pjf** [comment]
@Trioct : Those graphs are *awesome*. The simplified system looks so much better in terms of not ending up with ridiculous health scores from eating junk food every day or just getting enough sleep.

@Terrorforge : To be fair, there are iRL ways to [crater your health](https://commons.wikimedia.org/wiki/File:Tickling_the_Dragons_Tail.jpg) in a single day, and I think those are valid.

**Comment by Terrorforge** [comment]
Yeah, but from a gameplay perspective it's extremely punishing. Maybe as we make progress on slowing the game down and find ways to make weeks spent crafting more palatable it'll be okay to make players spend three weeks paying off a single mistake, but as the game currently stands it's kind of unbearable.

Not to mention confusing. Last I played I got stuck in one of these health death loops, and I literally don't even know what I did.

**Comment by fungamer2-2** [comment]
> Yeah, but from a gameplay perspective it's extremely punishing. Maybe as we make progress on slowing the game down and find ways to make weeks spent crafting more palatable it'll be okay to make players spend three weeks paying off a single mistake, but as the game currently stands it's kind of unbearable.
> 
> Not to mention confusing. Last I played I got stuck in one of these health death loops, and I literally don't even know what I did.

Remember that with the current system, dropping your stamina below 25% gives +1 daily health, up to 5 times per day, and not not dropping your stamina below 50% at all during the day gives a -4 penalty to daily health
But that's intended to be changed in #59267
