### ISSUE TITLE
Diary save page dialog

### ISSUE THREAD

**Issue by chrispikula** [CleverRaven/Cataclysm-DDA#59626]
### Is your feature request related to a problem? Please describe.

When editing a page in your diary, and then leaving, you get the option to save or revert.  

In every other Yes/No dialog that I can think of, 'no' is the default option, and hitting either the left or right arrow keys allows a quick transition to yes.  A quick enter makes the selection.  It's automatic, I don't even need to think about it anymore.  

With the diary, it defaults to yes, and utilizing that same muscle memory makes me select 'no' every time I make my first edit.  Sometimes even after the second.

### Solution you would like.

Consistency.  Have the diary default to 'no' don't save, to match other Yes/No dialogs.

Either that, or make it a vertical Save/Revert set of options, so that my left-arrow-enter muscle memory doesn't complete the pattern.  Instead, to revert, you'd need to press up or down.

### Describe alternatives you have considered.

Re-writing my diary index pages yet _again_.

**Comment by PatrikLundell** [comment]
It's not the only one that's "backwards". There's one related to crafting or reading that's also "wrong". Training martial arts vs regular book reading (causing intended single attempt to be continuous, or vice versa)?

**Comment by Qrox** [comment]
The problem is that, unlike other yes or no dialogs, the save dialog actually has 3 options: yes (to save the change), no (to discard the change), and cancel (to return to editing without saving or discarding by pressing `esc`). I'm not sure any muscle memory formed on the yes/no dialog can be seamlessly applied to this dialog, no matter what the default is. For example, someone might form a different muscle memory that pressing enter chooses the "safer" option, and be surprised if pressing enter discarded their change instead.

The best way I can think of is to remove the discard option to a separate hotkey and make the "no" option return you to editing instead, and then we can make the "no" option the default.

**Comment by PatrikLundell** [comment]
A tangent is that there recently was a change to the safe warning dialog, so instead of left (wrap around to the end) + return meaning ignore, it now takes you to a a new option of a safe settings dialog. To make that matter worse, exiting from that dialog cancels the activity, so not only don't I get to a dialog I didn't want to go to, I'm also forced to take the action I didn't want to take. That's logically backwards, as you'd probably want to exclude the thing causing the interruption from interrupting you, but by doing so you're cancelling the activity you was tired of having interruption prompts for...

**Comment by liminalRoar** [comment]
Yeah the safe warning threw me for a loop and still messes with my muscle memory. As useful as the Safe mode manager is, i would prefer a keybinding to open up the Safe mode manager (not one of the options). And exiting that takes you back to the safe mode dialog.

**Comment by chrispikula** [comment]
Yeah, the safe warning dialog has that as well, I forgot in my moment of pique.
