### ISSUE TITLE
Lockpicking results in multiple damaged picks

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#59636]
### Describe the bug

Usually when you're lockpicking by (e)xamining a locked door, you'll use one pick until it breaks and then move on to the next. But sometimes, it'll start using a fresh pick for no obvious reason, and then it never goes back to the original, damaged pick again. This never seems to happen while actively picking, e.g. while grinding up the first few skill levels, so I presume it's triggered by shuffling your bags around or something else that occurs between picking sessions.

### Steps to reproduce

Use lockpicks regularly

### Expected behavior

The game uses up one lockpick fully before moving on to the next.

### Screenshots

![image](https://user-images.githubusercontent.com/5107449/180990068-b7e30769-2142-4ba6-8533-c5edaf8b84ec.png)
The bastard

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1826 (21H1)
- Game Version: 5301287 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots],
    Xedra Evolved [xedra_evolved]
]

### Additional context

This is a comically small problem. The negative effects amount to 0.1L of wasted storage and a slightly fugly'd up inventory, but it does annoy me.

**Comment by PatrikLundell** [comment]
/confirmed

It can be noted that crafting and vehicle construction typically uses undamaged items over damaged when given a choice, so this may be caused by the same logic. Also, it will eventually use the partially damaged pick again, provided you don't have any of a higher priority left, so if you refrain from replacing the damaged, formerly pristine picks once you have enough damaged ones you'll eventually use up those as well. You can store your spares in you vehicle so you can top up should you run out.
And yes, you're not the only one annoyed by this very minor issue while still realizing it's very minor...
