### ISSUE TITLE
Base Mission request - constructable bridge over water/river

### ISSUE THREAD

**Issue by descan** [CleverRaven/Cataclysm-DDA#59651]
### Is your feature request related to a problem? Please describe.

I can manually build a bridge over a river if I need to, with zones or manually tile-by-tile. But doing so does not change the overmap tile the same way ordering them to survey a tile for expansion, or clearing a forest, will do. Therefore I can't auto-drive over my constructed bridge, and I might misplace it if I don't set the notes correctly - the only way to make it treat it like an actual bridge is to edit the map through debug.

### Solution you would like.

I'd love to have the option to use the basecamp features, and order my followers to build a bridge over some number of river tiles (or one at a time, if that's required and the maps can be created as such?), made out of whatever materials. 

### Describe alternatives you have considered.

Allowing the overmap tiles to be edited in a more diagetic way - telling the game "I've changed this tile drastically, please call it X and use it as Y," rather than through the debug menu.

### Additional context

yes i know i can turn my flatbed truck into a boat. which is ridiculous, and should be changed in my books, blither blather.

**Comment by PatrikLundell** [comment]
Interesting idea.

I haven't done any kind of investigations, so some assumptions might be incorrect:
- If you can construct it manually I think it's feasible to do as a basecamp mission.
- I believe such constructions are massive projects, both in terms of materials and in terms of time required. Therefore, I think a single tile at a time at most is the best approach, and it may well be that partial tiles is better. This means you can collect materials for further parts while having companions set on constructing the current one (that's the reasoning behind the Workshop 2 salt water pipe project). Also, it means you can change the set of companions working on the project between sections, rather than lock the crew at the start (you may recruit more companions while the project is ongoing).
- This idea opens up the concept of remote construction projects, not only bridges, but also roads, and what have you. It could expand into a large number of projects, in which case there might be a desire to eventually somehow get them into a UI sub menu.
- I imagine a player wouldn't manually construct bridges as wide as the pre cataclysmic bridges are, so there may be a desire to specify the width, or select a width among a set of provided ones.
- I can think of two approaches to the project. The first one would be a tile by tile one, in which case you'd start with a near side bridge head and may have to specify which direction the bridge should go if you have two possibilities. You'd then add a bridge tile adjacent to that one, etc. until you end with a bridge head at the other side. The other would be to select a start point on a river bank and an end point on the opposite side and have the game convert that into a set of missions (again, similar to the salt water pipe one, but without the ability to do sections in parallel).
- I'd like to see some kind of tile re-evaluation uncoupled from the base camp system. Something along the lines of asking a companion what he thinks the terrain of the current tile consists of. That might not be trivial to implement, though, and might only be applicable to a small set of terrains (e.g. "Do you think this is a plain/bridge/head/bridge/road...?").
