### ISSUE TITLE
kcal on basecamp are being immediately zeroed after "distribute food" mission

### ISSUE THREAD

**Issue by jfferson** [CleverRaven/Cataclysm-DDA#59711]
### Describe the bug

I don't know if there is something intended on it, I know for instance that rot time is something that can cause it, but even if I put food with time as long as seasons, the same thing happens

### Steps to reproduce

I will share my save folder to you so that you can test, I don't know if there is some straightforward way to solve it.

my player is Sydney 'El Diablo' Matlock

[Argos.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/9209448/Argos.tar.gz)

### Expected behavior

I would be able to distribute food to the basecamp and return after some small amount of time and see that the basecamp still has kcals present

### Versions and configuration

Gentoo, 64-bits
Cataclysm-DDA 0.F

mods:
cdda
crt_expansion
StatsThroughSkills
stats_through_kills
speedydex
sees player icon, HitButton_iso
Graphical Overmap
alt_map_key

**Comment by PatrikLundell** [comment]
Failed to repeat.

- OS: Windows
    - OS Version: 10.0.19043.1826 (21H1)
- Game Version: 0.F-10139-g32ee0b1131 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    C.R.I.T Expansion Mod [crt_expansion],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Dark Days of the Dead [classic_zombies],
    No Fungal Monsters [No_Fungi],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    Graphical Overmap [Graphical_Overmap],
    Alternative Map Key [alt_map_key]
]

I located the bulletin board and the food zone, spawned 1000 pemmican, dumped it into the store (via the board).
It was reported to be 440000 calories.
Moved the character out of the reality bubble and back (north for a while and then back).
Checked the board and saw 430000 calories.
Moved north and back again. Checked the board, but saw no change.

How many calories were you dumping? I don't know if there is such a thing as a deficit, but it could be that the companion immediately eats what you put in if it isn't that much. It can be noted that the companion non eating "mod" isn't present, so the companion needs food.

I've verified that the companions are responsible for for disappearing food. I restarted the save, talked to the companions and asked them to follow me, dumped 100 pemmican for 44000 calories into the store, and each of them expressed satisfaction of getting something to eat, leaving 36500 calories in the store, so there was indeed a deficit.

As far as I know, once calories have entered the store they're safe from rot forever. The reduced yield happens when you insert the food.

Thus, I suspect you're simply not storing enough food into the store.

Also "0.F" isn't a version, but but an indication that it's some version from the current development cycle that's up to a year or so old. I'd recommend using the escape-debug menu.-info-generate game report action (I think one step isn't present if you haven't enabled the debug menu to generate a report in the clipboard to post the set of info.

**Comment by jfferson** [comment]
> Failed to repeat.
> 
> * OS: Windows
>   
>   * OS Version: 10.0.19043.1826 (21H1)
> * Game Version: 0.F-10139-g32ee0b1131 [64-bit]
> * Graphics Version: Tiles
> * Game Language: System language []
> * Mods loaded: [
>   Dark Days Ahead [dda],
>   C.R.I.T Expansion Mod [crt_expansion],
>   Stats Through Skills [StatsThroughSkills],
>   Stats Through Kills [stats_through_kills],
>   SpeedyDex [speedydex],
>   Dark Days of the Dead [classic_zombies],
>   No Fungal Monsters [No_Fungi],
>   sees-player icon, HitButton_iso [sees_player_hitbutton],
>   Graphical Overmap [Graphical_Overmap],
>   Alternative Map Key [alt_map_key]
>   ]
> 
> I located the bulletin board and the food zone, spawned 1000 pemmican, dumped it into the store (via the board). It was reported to be 440000 calories. Moved the character out of the reality bubble and back (north for a while and then back). Checked the board and saw 430000 calories. Moved north and back again. Checked the board, but saw no change.
> 
> How many calories were you dumping? I don't know if there is such a thing as a deficit, but it could be that the companion immediately eats what you put in if it isn't that much. It can be noted that the companion non eating "mod" isn't present, so the companion needs food.
> 
> I've verified that the companions are responsible for for disappearing food. I restarted the save, talked to the companions and asked them to follow me, dumped 100 pemmican for 44000 calories into the store, and each of them expressed satisfaction of getting something to eat, leaving 36500 calories in the store, so there was indeed a deficit.
> 
> As far as I know, once calories have entered the store they're safe from rot forever. The reduced yield happens when you insert the food.
> 
> Thus, I suspect you're simply not storing enough food into the store.
> 
> Also "0.F" isn't a version, but but an indication that it's some version from the current development cycle that's up to a year or so old. I'd recommend using the escape-debug menu.-info-generate game report action (I think one step isn't present if you haven't enabled the debug menu to generate a report in the clipboard to post the set of info.

it must be the ammount of food then, thanks for the reply, I was putting less then the ammount of food subtracted

**Comment by PatrikLundell** [comment]
Since this issue has been resolved, it ought to be closed.
