### ISSUE TITLE
Plank crafting recipes are problematic.

### ISSUE THREAD

**Issue by Sathra225** [CleverRaven/Cataclysm-DDA#59808]
### Describe the bug

The current recipes through the crafting menu to get planks are 9 planks from a heavy wooden beam.
A heavy wooden beam is either 2 or 6 logs to make. Using a tool with woodsawing or treecutting of 2 or more to cut planks (axe or wood saw for example) can return up to 10 planks _per log_.

### Steps to reproduce

Use bandsaw to craft planks from heavy wooden beam through crafting menu: 9 planks.
Use a wood axe on 2 logs (best case for wooden beam): up to 20 planks depending on Fabrication skill.

### Expected behavior

I'm...not actually sure which one is wrong. I think if the crafting menu recipes used logs instead of heavy wooden beams it wouldn't be as problematic because that would be a reliable return regardless of skill.
Possibly planks-per-log is a bit high as well with the item action route.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22000.795 (21H2)
- Game Version: d94233a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Innawood [innawood],
    DinoMod [DinoMod],
    Stats Through Kills [stats_through_kills]
]

### Additional context

I'm not really sure how long this disconnect has been in.

**Comment by PatrikLundell** [comment]
A number of construction recipes can take logs as an alternative to planks. That may give another indication of what the log:plank ratio may be intended to be.

**Comment by natsirt721** [comment]
The core issue is that we are comparing crafting recipes - which have constant inputs and outputs, gated by skill and tools - to a specific action attached to an item - which has constant inputs but variable outputs based on skill. 

For reference, the axe plank output is based on a normal distribution, with a mean of (2+fabrication) and a standard deviation of 1, clamped to [0, 10].

At fabrication 0, the average plank-per-log using the axe is a measly 2, and 4% of time time you get 0! At fabrication 8, 50% of the time you'll get 10 logs, and rarely will you get any less than 7. The 2 log -> beam -> plank route using crafting is comparable with the axe action at fabrication 2 when the recipe comes available, and may even 'feel better' to use up to fabrication 3 or 4 due to consistent results.

Personally? I'd get rid of the axe use action altogether. We already have a mechanism for using tools to convert items into other items - the crafting system. Proficiencies give one mechanism for making skill matter when converting inputs to outputs by adjusting failure chance and time spent, but ideally there would be some way to apply variable results to a crafting roll based on skill and proficiencies without causing failures. The math works out the same way, except that we can't craft 0.1 log into 1 plank and apply failure there, and it would be pretty cruel to have a 0 fab character fail to create ANY planks 80% of the time, but get 10 when they do succeed. 

Apart from the facts above (previous paragraph notwithstanding) I'm not sure I have any real ideas on how to resolve this, other than to audit all of the recipes that use planks, logs, and beams, and try to reach some sort of consistency there.

Finally, I think it is acceptable for the longer crafting chains to have lower plank outputs than the shorter ones. Each step is removing material, so a small difference makes sense.

**Comment by Sathra225** [comment]
Yeah, I dunno. Removing the axe action would break Innawoods, and make getting planks much more tedious in general.
Clamping the plank output to 1-4 per log would be nicer, and having the current crafting recipes use logs instead of heavy wooden beams at 4 and 6 or 8 output for manual/power tool gives them more reasonable use.
After all, you make 3m long poles for pikes from heavy wooden beams.

**Comment by Xpyder** [comment]
My inclination would be to change planks recipe to consume logs, and remove getting planks from using an axe on logs as that's the wrong tool to create planks by hand (from what I can tell you need at least a saw and possibly a planer)

Ideally the axe results would be replaced by a split log/firewood item, but that would likely trigger an audit of all items that take planks to see what could reasonably be made from split logs instead of specifically requiring planks.

**Comment by natsirt721** [comment]
> Yeah, I dunno. Removing the axe action would break Innawoods...

I'm not sure mod compatibility should be concern for mainline issues
> and make getting planks much more tedious in general. 

We have batch crafting, it would actually make it much LESS tedious since I could chope 40 logs into planks with a few button presses and a lot of watching. 
>Clamping the plank output to 1-4 per log would be nicer

Agree that we need an audit, not sure that 1-4 per log is the best number.
>and having the current crafting recipes use logs instead of heavy wooden beams at 4 and 6 or 8 output for manual/power tool gives them more reasonable use. After all, you make 3m long poles for pikes from heavy wooden beams.

Agree wholeheartedly.

**Comment by PatrikLundell** [comment]
Removing the ability of tools to cut logs would probably also break the wood cutting zone's ability to cut logs.

**Comment by natsirt721** [comment]
From what I can tell, the zone is there so you don't have to do 3-4 keypresses * n logs to chop all your wood. With crafting this is no longer necessary since you have batch crafting. Although it does make NPCs a bit less useful.

**Comment by PatrikLundell** [comment]
The zone provides both player reduction of key presses and work offloading to companions. I consider the latter to be the more important aspect.

**Comment by x-qq** [comment]
Requiring 6 logs to make a single heavy wooden beam does not make sense.

1 beam is 60L / 36kg of wood.
6 logs are 300L / 180kg of wood.

So the current recipe discards 80% of input material, with a byproduct of just 20*0.25=4L / 20*0.15=3kg of splintered wood.

This is not reasonable and the recipe should be changed to require 2 logs regardless of the tool used.
