### ISSUE TITLE
Sustainable Vacuum-Sealing Solutions

### ISSUE THREAD

**Issue by indigorain** [CleverRaven/Cataclysm-DDA#59829]
### Is your feature request related to a problem? Please describe.

Plastic bags are ubiquitous, but they are not renewable (outside of endless-world-gen raids and forage), despite having casein be a renewable source of plastic. These are nice recipes to have as it is a quick way to indefinitely preserve food, if you have the resources on hand.

MRE packaging and bags is junk and clutter. They don't have any use or purpose after their seal has been broken.

### Solution you would like.

Maybe MRE can be repurposed and reused in vacuum-sealer recipes. They are also very plentiful--like plastic bags.

Looking into plastic bag manufacturing, I think it could be within the means of a survivor, requiring designated 'furniture'. To make a plastic bag, material must first be melted, air blown through it, and then rolled flat. It would require some machinery, but the machines do not seem complex.

### Describe alternatives you have considered.

Alternatively, 'plastic bags' need to be revamped to be more realistic and accurate.

mres packages and bags can maybe be melted down into a plastic chunk (with enough material).

Not all plastic is the same, not all plastic is reusable, and not all plastic will provide good vacuum-sealing.

Alternatively, alternatively, vacuum seal bags/roll of plastic should be an item found on occasion, capable of making a number of vacuum-sealed goods. And the recipes should outright remove the generic plastic bag item.

### Additional context

'Plastic bag' is an inadequately described and utilized item. Plastic bags can contain 6L. They contain potato chips, cotton balls, and jerky. The composition and integrity of these materials are not the same, nor are the sizes.

**Comment by Zireael07** [comment]
Search for 'plastic mold', that was my attempt to give some utility to plastic items around.

Later on there was another discussion centered about the fact that plastic items differ a lot and should probably have different 'materials' in game, but I can't find it either.

**Comment by AtomicFox556** [comment]
I can't imagine why you'd want to manufacture plastic bags from scratch. First of all you'd need specifically polyethylene for that rather than any random kind of plastic; while ethylene could potentially be produced from ethanol and sulfuric acid, then polymerized using a titanium trichloride catalyst, and then extruded into a workable polyethylene film using a bulky purpose-made industrial extruder, this really seems too much of a hassle for manufacturing what is simply trash most of time.

Sourcing polyethylene from other objects that are made out of it but are not plastic bags wouldn't help much either, as you still need the same machinery for processing it into bags.

Polypropylene could also work as a bag material, but I don't see it making the processing step any easier, and manufacturing the material itself is more complicated.

You may want to consider making tin cans (or glass jars) and then sealing food in them as a much easier alternative; cans/jars and canning equipment probably would be possible to make from scratch.

**Comment by Maleclypse** [comment]
It's not currently feasible for the survivor to make their own vacuum sealable bags and it would need significant proof that it could be done.
