### ISSUE TITLE
nested mapgen roof placement issue - basecamps

### ISSUE THREAD

**Issue by a-chancey** [CleverRaven/Cataclysm-DDA#59833]
### Describe the bug

I was working on updating the fire lookout tower basecamp and can't seem to get roofs to place if I have stairs or an open space in the chunk.
https://github.com/a-chancey/Cataclysm-DDA/tree/fire-lookout-tower-garage-fixes
This is the branch with the last chunk of code i had been working on.
I closed the PR for now. I'm just going to find a new location for the two vehicles that had their spawns accidentally axed.

### Steps to reproduce

Check out the branch above, generate a world and place a fire lookout tower.
get an npc and start a base camp. build the migo resin expansion - should take a week and one day.
it'll build around the base of the lookout tower, but won't place any roof tiles, because there's a stairway included in the nested chunk.
Replacing the stairway in the chunk with another ".", the floor with roof, will overwrite the stairs, but will cause the entire area to be roofed properly.

I had even added a new migo resin stair that is flagged as indoor and can support a roof - still wasn't able to get roofs generating.

### Expected behavior

Enclosed areas that contain roof supporting, indoor tiles, even when they contain a staircase or an enclosed gap, should still have a roof placed.

### Versions and configuration

Windows 11
Branch linked above
tiles
english
mods: dda

**Comment by PatrikLundell** [comment]
If this is caused by the logic somehow not playing well with a staircase that's ignored, you might be able to work around it by placing multiple smaller chunks around it, optionally replacing some of the smaller chunks with direct placement of terrain (points and lines).
Obviously not a solution to what seems like a bug, but it might allow you to continue to achieve your objective.

Could the issue be that a staircase produces a "roof" tile in the form of the opening, and this causes the logic to somehow consider the roof portion to be unsupported (and rather than introducing a new unknown in the form of a new tile, I'd try a regular wooden staircase, although I'd expect it to fail in the same way)?
I'd also try to generate the whole structure in a "normal" material in case resin somehow interacts badly with "normal" "roofs". Again, I wouldn't expect that to work either.

**Comment by a-chancey** [comment]
Yeah I tried it with wooden walls, a wooden staircase, and building it in multiple passes. I also left the staircase tile blank. It just seems that when there’s any gap- even an enclosed one, or one with stairs - prevents the roof from generating. If I replace the stairs with a floor? The room is roofed.
