### ISSUE TITLE
I can't paint wooden walls or any other wall, that isn't just a 'wall'.

### ISSUE THREAD

**Issue by Stadler76** [CleverRaven/Cataclysm-DDA#59870]
### Describe the bug

I've taken down a wall by 'Remove Wall' in the shelter and then tried to rebuild it and paint it.
Since there no plain 'Build Wall' option in the <kbd>*</kbd> construction menu I've build a wooden wall. Then I've obtained a paint brush and some white paint through the debug menu and wanted to start painting it, but I can't paint it. Only the 'wall' next to it, which is just a wall, meaning: no wooden wall or metal wall and so on.

Probably the same or at least related issue is, that there's no 'Build Wall' in the <kbd>*</kbd> construction menu. 'Only' 'Build wood wall' and so on, so I can't even construct a paintable wall currently.
Ok, Build Wall requires adding drywall sheets and gypsum to the game, so that's another story.

### Steps to reproduce

1. Build a wooden wall.
2. Get some paint and a paintbrush.
3. Try to paint it.

### Expected behavior

I can paint any wall that I can construct.

### Screenshots

![grafik](https://user-images.githubusercontent.com/13157984/182723588-bfec8517-aebc-4a26-b1e4-197a16b86074.png) ![grafik](https://user-images.githubusercontent.com/13157984/182723609-f3abfe9e-3d34-44ab-82df-8d7ed1883e10.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1826 (21H2)
- Game Version: 0.F-10408-g39605b0c91 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by PatrikLundell** [comment]
The underlying problem is that the game currently doesn't have any support for modifiers on "terrain" apart from graffiti. Instead, said terrain is morphed into a different terrain (white wall, yellow wall, pink wall, etc.). That's sort of possible to support with one or two kinds of wall, but it gets rather cumbersome if it was to be done for every type of wall, and you can't really turn other types of walls into the <color> generic wall either, as that would change the walls other properties as well, not just the color (how hard it is to smash and what it produces when smashed). I believe the situation is the same with carpets.
What's needed is a way to add additional properties to "terrain" that doesn't erase the existing ones. Currently the system supports "terrain" on top if which you can have "furniture", items, and appliances/vehicles, with vehicle/appliance/furniture usually colliding when appearing in the same tile, although furniture can have a NOCOLLIDE flag, but the underlying system supports only a single piece of furniture in a tile.
