### ISSUE TITLE
Fridge appliance doesn't stay on

### ISSUE THREAD

**Issue by Travia21** [CleverRaven/Cataclysm-DDA#59883]
### Describe the bug

I'm not yet sure what the trigger is, but fridges turn off and stored items lose their cold when the fridge is no longer in the reality bubble _sometimes_. Obviously this causes issues with rotting.

Update: It is not necessary for the fridge to leave the reality bubble. It keeps turning off even when farming 1 tile away.

### Steps to reproduce

1. Install a fridge and provide enough solar power/batteries to properly power the fridge 24/7
~2. Get far enough from the fridge to place it outside your reality bubble~
3. Do some stuff, possibly take a few hours to return (It seems this happens 50% of the time)
4. Return and 'e'xamine the fridge to see it's no longer turned on but still connected to the power grid

### Expected behavior

Fridge doesn't turn off when batteries have enough power for the fridge

### Screenshots

![image](https://user-images.githubusercontent.com/3219079/182867044-c0fb0384-80ed-4ff6-83c2-ce3b0503b35f.png)

### Versions and configuration

- OS: Windows 10
- Game version: O.F-e9808ab
- Graphics version: Tiles & Sound
- Ingame language: English
- Mods loaded: DDA, No Fungal Growth, No NPC Needs, Bionic Professions

### Additional context

- I have enough solar panels and battery storage to power ~7 fridges full time
- I have 2 powered lamps running constantly; they don't turn off
- I have an oven, water purifier, autoclave, and electric forge plugged in and usable at all times

**Comment by chrispikula** [comment]
Are the batteries and solar panels in the same map tile as the fridges?  Well, the batteries would be more important, but you get what I mean?

What if there's a grid split by reality bubble, is what I'm wondering about.

**Comment by Travia21** [comment]
No. Everything is contained in a single map grid.

**Comment by PatrikLundell** [comment]
In what seems related, I have a freezer appliance in which some items are frozen, some cold, some at the unmarked temperature, and some are still hot weeks after being placed there. The freezer is on my kitchen expansion, powered by solar panels and batteries on the roof of the same building (and there are a lot of both panels and (full) batteries, so there definitely isn't a lack of power).
As long as items are inside the freezer they seem to be fine, but non frozen items rot immediately when taken out (as an example, I removed some hides to cure them, and they rotted immediately, but I was able to cure the rest of them from inside the freezer. However, that weird behavior exists with normally working RV fridges too (RV because that's what I've used, not because I think it's significant as such)).

**Comment by Travia21** [comment]
Patrik, that is an unrelated issue that has more to do with how rot is calculated. This issue is focused on appliance state and the power grid.
That said, I found the issue that _is_ related to what you're talking about: [#58824](https://github.com/CleverRaven/Cataclysm-DDA/issues/58824)

**Comment by Piddagoras** [comment]
Are the batteries in a proper vehicle or are they the appliance batteries?  I experienced this issue until I installed appliance batteries on the grid, and have not since.

**Comment by J-Duq** [comment]
![image](https://user-images.githubusercontent.com/71032228/199145816-4e1fdcc3-d727-4386-9315-15d808a612f5.png)
I'm having the same issue where my fridges turn themselves off randomly and constantly. I have three fridges plugged in and running (supposedly) at all times, one freezer running, a handful of big equipment like table saws and drill presses plugged in, a recharging foot locker, and three large storage batteries. I'd agree that it's probably a 50% chance that the fridges are off whenever I check them. I check right before bed, right after waking up, any time I walk back into the basement (where this screenshot is showing), and sometimes when I leave the basement. The fridges are the only appliances that turn themselves off, lamps, recharger, and freezer have all been operating as expected. Sometimes only two of the three fridges turn off (instead of all three), but it's not always the same two. I manually swap out large storage batteries, rotating them with ones charging on the roof with a solar array.

Same steps to repro.
Windows 10
version ed92400
build 2022-22-01-0004

**Comment by Antrocon** [comment]
same issue: freezer, fridge, large space heater & standing lamp are getting randomly powered off when PC returns from outside of reality bubble.
my power consumers all on single grid connected via wall wires in basement (lmoe shelter), with 2 fully-charged large storage batteries set as appliances and connected to same grid, with 3 ASRGs connected to same grid + bunch of solar panels & large wind turbines on surface roof connected to grid via extension cord.
net positive during day & low enough drain during night, so 2 batteries should last few days straight even with no power generation, yet switching off happens even when you go out for like 30min. very annoying

- OS: Windows
    - OS Version: 10.0.19044.2251 (21H2)
- Game Version: b7312f8 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Craft Ammo Mags & Belt Links [SD_Magcrafting],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    No Rail Stations [No_Rail_Stations],
    Mining Mod [Mining_Mod],
    Portal Storms Ignore NPCs [personal_portal_storms]
]
