### ISSUE TITLE
Exodii Mission 2 Expansion: Allow NPCs to help you find the warehouse

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#59907]
### Is your feature request related to a problem? Please describe.

See https://github.com/CleverRaven/Cataclysm-DDA/issues/59900

The Exodii missions haven't yet been implemented, and I am worried that my life commitments will keep them out of my reach for a long time. I am posting my plan for their missions in the hopes that someone will help me implement parts of them. If that happens, I would be more than happy to contribute with dialogue and editing and some of the components as I have time.

Of course I may get to this myself, in which case having it written up will keep me from forgetting what I wanted.

See [Mission 2: Find the lost warehouse](https://github.com/CleverRaven/Cataclysm-DDA/issues/59905): this issue expands the mission so that you can ask NPCs from other factions for advice, making the mission much easier and also more interesting.

### Solution you would like.

Follow up refinements to [Mission 2: Find the Lost Warehouse](https://github.com/CleverRaven/Cataclysm-DDA/issues/59905) to be added after the mission is working in base form.

#### Changes to mission offer dialogue
- Rubik suggests you can ask around amongst other scavengers and travellers for clues, they don't mind if word gets out that you're looking for it.
- If you have previously made contact with the Hub, and Rubik knows that, they might slightly hint that you shouldn't go chatting with those guys, but they won't oversell it because they don't want to give you ideas.

#### Talking to other NPCs
You can ask several NPCs for help to find the warehouse. Possible NPCs to ask include: 
- Free Merchant Teamster
- random Free Merchant roadside encounters
- the Arsonist
- one of the Crafters
- one of the Hub mercenaries
- if possible, any randomly spawned NPC might have a chance of discussing this with you.
- Other NPCs in other factions that suit the 'traveller who might know' could be included as well.

You won't always get the right answer but eventually you are guaranteed to:
- The first NPC you ask has a 1/3 chance of having no idea what you're looking for, a 1/3 chance of giving you directions to a different location, and a 1/3 chance of giving you correct directions.
- If you haven't yet received correct directions, the second NPC you ask has a 1/6 chance of having no idea, a 2/6 chance of giving you incorrect directions, and a 3/6 chance of giving you correct directions.
- If you haven't yet received correct directions, the third NPC you ask will definitely give you correct directions.
- Once you have received correct directions, NPCs have a 50/50 chance of either not knowing or giving you incorrect directions

Possible incorrect directions: You may be given directions to an infested LMOE shelter, a different exodii warehouse, a mi-go tower, a FEMA camp, or any of several low-value non-city map specials.

#### Hinting conflict with Hub
- If you tell the hub01 intercom more about what you are looking for, they will ask you some more questions about it. You have the option of sharing more information. Their reaction will depend a bit on how much they trust you already.
- Actual conflict with the Hub will be added in another refinement Issue to this one, just getting the NPC dialogue and directions mechanic in is sufficient for now.

### Describe alternatives you have considered.

I'm not completely sure if the "wrong directions" mechanic is necessary, but I think it is *fun*. There are other ways it could be implemented. For example we could just have a counter of "how many times have you asked for directions without getting the right answer" and if it is 2 or more, you always get the right answer - no change in likelihood on the first two answers.

Rather than giving you directions to a wide range of maps the wrong directions instead could always lead somewhere useless, like a pile of wreckage in the woods or something.

### Additional context

n/a

**Comment by PatrikLundell** [comment]
I think incorrect directions should always lead to other Exodii warehouses (of either kind), because there's little chance of anything else matching the player's (implied) description. You could add malicious misdirection, though, but that would require asking someone who'd be interested in doing so (Hell's Raiders, Psychos, etc., and they seem to be on a shoot at sight basis with you, which is harmful to the prospects of dialog).

I guess you could also have faulty directions, i.e. ones which will lead you to a random position of nowhere, because the person who gave the directions made a terrible job at it, mixing directions up, ramble confusingly and whatnot (there are certainly such people in the real world). If you were able to find those persons again, though, you ought to be able to ask them again and get correct direction (possibly to a different warehouse still), after a lengthy and frustrating dialog session where you check, double check, and triple check the directions. You should get an indication that the initial directions were unreliable, though, as the player ought to detect that the instructions weren't exactly crystal clear.

I'm certainly not against directions to "interesting" locations, but not as part of this.
