### ISSUE TITLE
Houses catch fire much to easily.

### ISSUE THREAD

**Issue by chrispikula** [CleverRaven/Cataclysm-DDA#59927]
### Is your feature request related to a problem? Please describe.

Three seconds with a match, and I can start a house on on fire.

Houses don't start on fire that easily.  Arsonists use accelerant for a reason.  We build houses out of non-flammable things on purpose, so as to not reenact the great city fires of yesteryear.  Drywall, siding, brick, and concrete in larger buildings are all pretty much immune to fire.  Even fabric, if it's been exposed to the outdoors via broken windows is going to have a tough time to ignite if it's gotten wet, and been unable to dry out due to being in a shady room.

### Solution you would like.

Constructions shouldn't start burning until regular fire.  This include if they, themselves, have a small fire on self-same tile.

**Comment by Night-Pryanik** [comment]
Somewhat related: #15537.

**Comment by liminalRoar** [comment]
I don't really know how fire currently spreads in code, but maybe we need some more advanced burn mechanics and fire simulation? No idea how close this is to the current method:

Burn rates for different materials along with a burned percentage for items and constructed objects. Depending on the objects size and material and burn percentage it contributes to the amount of fire on that tile. The amount of fire on that tile determines how quickly it spreads to others. Temperature could play a role to, as well as present liquids and such.

Probably could be simplified a lot. Or maybe all we need it to slow down how quickly objects catch fire.

**Comment by Xpyder** [comment]
this would probably dovetail nicely with needing tinder to start most fires, right now I can just directly light (for example) butchery refuse which while convenient isn't particularly realistic

**Comment by descan** [comment]
> this would probably dovetail nicely with needing tinder to start most fires, right now I can just directly light (for example) butchery refuse which while convenient isn't particularly realistic

From what I understand, tinder *is* simulated in game, but it behaves more like accelerant would than actual tinder - it's not required to *start* the fire (obviously) but a tile with tinder-equivalent will get going into a larger fire quicker than lighting a log on fire. My understanding comes from Discord chats with other devs, who in the same message indicated that most players probably don't know this because it's so subtle and rarely comes up. (I know I mostly use firewood sources for long-term fires and just set things on fire when it's a quick burn, so I don't put any items on the things I'm trying to set on fire to have noticed it being faster/quicker with tinder-equivalents.)
