### ISSUE TITLE
Charging stuff while sleeping/sitting.

### ISSUE THREAD

**Issue by chrispikula** [CleverRaven/Cataclysm-DDA#59931]
### Is your feature request related to a problem? Please describe.

One of the things that everyone really wants to get is a UPS, as keeping all the stuff on the survivor charged is currently a micromanagement pain.  And the UPS code is supposedly a pain.

We also aren't wanting to get power bricks, either, as per the above UPS code being annoying.

So I don't know about other people, but when I'm sitting at a desk, or sleeping in bed, I tend to plug in stuff that needs to be charged.

### Solution you would like.

Having your phone/watch/e-ink pc/flashlight/geiger counter/etc automatically be plugged in and recharged while you sleep or work at a desk would be a decent work-around, yes?

Given the limitations of the engine, and a lack of multi-tile appliances, I'd think the charger(s) should go into the bed, or the chair.

### Describe alternatives you have considered.

None that would be accepted.

**Comment by yoopgim** [comment]
just reading through random stuff and in my opinion it would fit the fleshed out multiverse of C:DDA, though, i would suggest maybe it be a text option rather than completely automatic, as some people might be stingy with power use. also while this seems redundant (take that with a grain of salt sense i found this game randomly less than 2 weeks ago) for most appliances as you could just plug them in before you go to bed, it would help for stuff such as items used as alarms and electric blankets(?)

**Comment by chrispikula** [comment]
It's more that it's an easily forgettable task, that the UI makes extremely annoying to do repeatedly.  It's like remembering to stand up after sleeping in a bed, until that was fixed to automatically happen, rather than have people crawl on the ground in the morning.
