### ISSUE TITLE
Talon UGV killbots spawning on street overmap

### ISSUE THREAD

**Issue by LyleSY** [CleverRaven/Cataclysm-DDA#59961]
### Describe the bug

Early game player spawning near a bank can be gunned down by a Talon UGV with an automatic rifle with no ability to predict or counter the instakill

### Steps to reproduce

Start a new world, spawn near a bank, explore the bank, see a killbot, run and get gunned down

### Expected behavior

I was surprised to see military grade robots with automatic weapons spawning day one in a normal bank. That's not typical in the banks I've seen.

### Versions and configuration

Newest experimental on Mac, running DinoMod but not related

### Additional context

In general IMO, a day one instakill with no counter is not good outside a challenge start

**Comment by anothersimulacrum** [comment]
We should remove them:
https://github.com/CleverRaven/Cataclysm-DDA/blob/3c5939e35be2d7db8341191290498a74133cd76f/data/json/mapgen/bank.json#L81
https://github.com/CleverRaven/Cataclysm-DDA/blob/3c5939e35be2d7db8341191290498a74133cd76f/data/json/mapgen/bank.json#L230

Can probably also remove the `{ "action": "secubots" }` from the computers.

**Comment by x-qq** [comment]
I think they spawn inside buildings, in rooms without windows so they should not bother you unless you go inside the bank yourself.

They also do not instakill you, they do single shot every 4-6 seconds, and while damaging (40-50 dmg) it does not instakill even a naked character.

They are also easy to avoid (make loud, unique noises) and easy to escape from (40 speed, cannot open doors).

But more importantly, they are quite useful because you can kill a good amount of zombies for you if you lead them to a strategic point.

Given all this, I don't think their removal is warranted.

**Comment by anothersimulacrum** [comment]
They don't make any sense, so their removal is warranted.

**Comment by x-qq** [comment]
"When the riots started, some of the banks have fortified their security systems with armed robots to dissuade the looters/rioters" makes a fairly good sense to me.

However, maybe there should be warning posters about them on bank doors/windows.

**Comment by PatrikLundell** [comment]
Having them inside banks won't keep them inside as zombies smash up banks. Had an NPC killed by one as the bot targeted the meteorologist and killed her before I had a chance to prevent it.
