### ISSUE TITLE
Gas mask filters being similar to disposable batteries

### ISSUE THREAD

**Issue by chrispikula** [CleverRaven/Cataclysm-DDA#59964]
### Is your feature request related to a problem? Please describe.

So, currently, gas mask filters can be loaded, individually into gas masks, usually into a set of 100.

I can't think of a single IRL organic or activated carbon filter mask that works this way.  They are all self-contained units, disposable as well.  Maybe there is a particulate filter that uses dozens and dozens of replaceable sheets, but I've not seen it.

Furthermore, they also start degrading once opened, what with the activated charcoal.  ~6 months is what 3M suggests.

As it stands, I can take 10 gas masks that all have 3/100 or 15/100 charges, and somehow squish the filters together into a new gas mask.

### Solution you would like.

Something like the disposable batteries, but also with a slow rate of self-discharge.  NO_RELOAD, NO_RECHARGE tags.  So that 4 or 5 months post apocalypse, you either need to find new, sealed ones on your own, or make makeshift ones, somehow.*

I'm not sure if self-discharge or decay is possible right now, at least without an excessive amount of transforms, which is not the right solution.

The new cartridges, as they are called, would just be inserted to the face masks as they currently are.

New sealed ones should be like the wrapped radiation badge, and create a trash plastic wrapper when opened.  Maybe a plastic wrapper (sealed) instead?

*Making activated charcoal is an exercise left to the reader.

### Describe alternatives you have considered.

Cartridges having model/make, with varying levels of efficacy (no, very hard to code iirc.).
Manufacture locking to match mask to specific filters (no, PPE cartridges are fairly interchangable, at least consumer grade screw-on ones.)
Having to salvage & merge cartridges as a craft (no, at least not with high loss of materials, and even then, eh...)

Mask-using proficiency?  IRL you need training and a fit-test to use a face mask properly.

Other SCBA gear, makeshift or using SCUBA gear?  Those behind the back filter cartridges for make-shift, or a small vehicle/pump/cart that you could use to pump air into yourself via air line, something like jumper cables or tow ropes?  Set it outside the cloud of toxic gas to get breathable air inside?

**Comment by descan** [comment]
I'm not sure if you're aware (I'm only saying this because of "you either need to find new, sealed ones on your own, or make makeshift ones, somehow.*") but it currently is possible, at relatively low skill, to make identical (not make-shift) gas-mask cartridges. It's auto-learn, at fab 2, and only takes 10 charcoal, 2 paper, and either plastic sheeting or a small plastic bottle. It's not in-game hard. 

Seems to indicate that whoever coded gasmasks considered them (or their cartridges) to be relatively simple affairs as a rule. Not sure if that changes anything, or if you want to extend your suggestion towards changing that crafting task.
