### ISSUE TITLE
Wait, am I obese now? Some kind of bar displaying player weight.

### ISSUE THREAD

**Issue by arockperson** [CleverRaven/Cataclysm-DDA#59976]
### Is your feature request related to a problem? Please describe.

It's kind of beating a (un)dead horse to complain about the player weight system. But putting all the problems with the actual mechanics of the system aside, I think the main issue is actually the lackluster way the game _communicates_ what is happening to players.

For example, how is it so easy for a character to go from overweight to obese, or normal weight to underweight... with the player only knowing it once their weight reaches the next level? The player has no way of knowing that their weight is fluctuating without using a scale or a fitness band, besides looking at the different weight descriptors, which aren't nearly granular enough ("overweight" describes both being barely overweight and the precipice of dangerous obesity)

### Solution you would like.

A simple visual representation of the character's weight (relative to height, of course). It could be a widget, or could be revealed when hovering over the weight in the character's sheet.

It wouldn't be super precise, but just a general idea, which would be extremely reasonable. Imagine looking in the mirror every day and seeing yourself at the same weight, until you suddenly are obese.

Think of the sims 2, where a sim's fitness is represented by a bar ranging from muscular to fat. Super simple, but it prevents the issue of eating a grilled cheese and suddenly and unexpectedly becoming fat.

### Describe alternatives you have considered.

Adding more weight levels to give it some much needed granularity. The problem with this, I feel, is that it would run into issues of defining "slightly overweight" "plump" "thick" "skinny", etc. And even if there were twice as many weight levels, you would still abruptly move between them.

### Additional context

As you can see, graphic design is my passion.
<img width="661" alt="amifatornot" src="https://user-images.githubusercontent.com/48835780/183264169-8c3bcaa0-27f6-4a9a-962f-ebe8b2e83168.png">

**Comment by AtomicFox556** [comment]
I think the best way to resolve this would be to add a numerical "% of ideal weight" display somewhere, so that the character's weight could be tracked in up to 0.1 % of ideal weight increments and the player would immediately know if the character needs to consume slightly less or slightly more calories daily.

**Comment by natsirt721** [comment]
Values and percentages imply that there is some way to measure them. Perhaps for self-aware this is appropriate, or a trained dietician with daily access to a scale, but I don't think most people are going to be able to tell how appropriate their weight is except in broad strokes. Your alternative suggestion of increasing granularity is a good start for now. The idea is to increase granularity to the point where changing from one category to the next isn't necessarily a big deal in and of itself, but the player can monitor trends in changes to figure out if they're eating too much or too little.

**Comment by vetall812** [comment]
There is a body mass index value ingame. I think that with growing sidebar development it will be implemented one way or another. 
Or we can add `smart bathroom scale` that will print this value in log.

**Comment by arockperson** [comment]
> Values and percentages imply that there is some way to measure them. Perhaps for self-aware this is appropriate, or a trained dietician with daily access to a scale, but I don't think most people are going to be able to tell how appropriate their weight is except in broad strokes.

I see where you are coming from, but I strongly disagree. Unless the game wants to go REALLY realistic and have the character's perception of their weight come from looking in the mirror and seeing how clothes fit, I think a simple visual representation is a pretty appropriate level of information.

There are other systems in the game that are represented with a bar and I don't think they noticeable detract from realism. For example, body part HP bars. It would be more realistic if by default they worked like they do with deadened (only having a very vague idea of limb HP), but that wouldn't be a good idea.

It might be unrealistic to be able to go, "Oh, looks like I gained a couple of pounds" without having a scale. But it's far more realistic than going "Oh wow, looks like I gained 100 pounds without knowing it".

Additionally, the whole issue of "how does the player character know their own level of fitness" is still present even without the bar. How would they suddenly know that they've gone from "Obese" to "Morbidly Obese"? The care for realism is definitely part of what makes this game so great... but I think once you start trying to make the user interface and controls realistic, that's uncharted territory.

One last thing... I think the poor communication of player weight has caused certain problems with weight to go under the radar. The speed at which the player can gain weight is frankly astounding. You can go from starving (from the weight XS trait) to overweight in 1-2 days.

**Comment by natsirt721** [comment]
> Additionally, the whole issue of "how does the player character know their own level of fitness" is still present even without the bar. How would they suddenly know that they've gone from "Obese" to "Morbidly Obese"?

With an appropriate level of granularity, the thresholds themselves don't actually need to carry relevance. How does a character know when they've gone from Very Hungry to Starving? Or Tired to Very Tired? The answer is; it doesn't matter because those things are abstractions. Weight should be treated no differently, and although it is true that with training and a scale you can determine 'precisely' how your weight stacks up, the character isn't going to be aware of that at all times. At best they can say 'I feel about right' or 'I think I'm getting a bit plump' or 'I can see my ribcage'; this is what the current textual system does. Having a number that indicates to the player exactly where their weight lies is providing too much precision, for the same reason that we don't just print what your limb health, stomach contents, and tiredness levels are numerically on the sidebar.

If you want to replace the textual system with a bar a-la limb health, that's fine. A bar might even be better, then we don't have to come up with a bunch of words on a scale between "XS" and "XL". However, two things.
1. Having a bar that is green in the middle and red at the edges is going to rub against the current bar UX, which is green when full and red when empty. This is a minor concern and with good coloring is probably not even worth considering. The current bars have five segments with three states each for a total of 15 positions; this is probably good enough for a first pass w.r.t. granularity.
2. I don't think most people track their weight on a daily basis, except for maybe bodybuilders and people on dedicated diets, so I am tentatively opposed to moving the display to the sidebar, which IMO is more useful for heads-up-display of information that changes frequently. The fact that character weight is changing fast enough that you are caught by surprise may be indicative that there are other underlying issues with weight gain.
