### ISSUE TITLE
Elevator in Hazardous Waste Sarcophagus doesn't work

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#60068]
### Describe the bug

I have the access code and reactivated the elevator but I cannot ride the elevator down, it only gives me the option of the current floor I'm on. I'm guessing this is because #57811 ?

### Steps to reproduce

1. Spawn in a hazardous sarcophagus access code.
2. warp to a sarcophagus.
3. attempt to use the code on the computer. Be told elevator was reactivated.
4. go attempt to use the elevator.
5. See that it only lets you "go" to [floor 0]

### Expected behavior

I can use the elevator.

### Versions and configuration

latest experimental

**Comment by descan** [comment]
I've had this happen to me too. I was told it was because there was supposedly a quest from the Old Guard to go down into Hazardous Waste Sarcophagus' and that that's why it the elevator wouldn't work (which struck me as a REALLY weird way to code it? That the elevator doesn't work at all, even with the code, until the quest is started?), but I don't see any such quest from the Old Guard in the game.

**Comment by andrei8l** [comment]
The elevators aren't aligned so they can't work anymore after #58840. Their map definitions need to be updated.

**Comment by Night-Pryanik** [comment]
Fixed by #61774.
