### ISSUE TITLE
Dynamic looted map location generation

### ISSUE THREAD

**Issue by RelMayers** [CleverRaven/Cataclysm-DDA#60060]
### Is your feature request related to a problem? Please describe.

There is benefit to having locations on map be looted, however making a hand crafted looted locations is work for map makers and also it creates a repeating look on locations. 

### Solution you would like.

Using algorithm to generate looted location either in mid game or have a tool to generate them and have a human pick some of them to be used might be beneficial to A. Variable look of locations B. More different levels of loot missing / damage to location. Probably using a noise map with gradient would work fine for this. 

### Describe alternatives you have considered.

Stick to current method. 

### Additional context
I'm willing to work on this feature.
Looking forward for a feedback.

**Comment by GuardianDll** [comment]
guess it will be good to have such feature, but i have no clue how it can be emulated properly
decreasing the amount of loot? totally erasing the `IRREPLACEABLE_CONSUMABLE` loot (as loot that is the most important/most valuable)? random bashing the furniture and terrain in random places? explosion holes?
all of them sound good, but must be complex, flexible, and do not cause the feeling "all location were destroyed in the same manner" every time - which is kinda hard to do
You will make a great work if you will finish it tho

**Comment by descan** [comment]
> "all location were destroyed in the same manner" 
To be fair, there's only so many ways *to* destroy a location that makes sense. Looting, fire, and random acts of violence are the only ones I can think of that would be a generic "this building isn't what it used to be" setting for players to find. Looting would be pretty systemic - bashed doors and/or windows, graffiti, opened/damaged/destroyed containers, some of the more obviously useless items strewn across the floor, and valuable stuff taken. Fire would be... Self-correcting. And random acts of violence (from blob psychosis or zombies being zombies) would be like the looting, only with less concentration on containers, and valuable items remaining in the location. 

You can, of course, have other methods of location destruction for more special cases, but those are either handled by the game (craters and impacts) or can be tailor-made by the map maker themselves (for example, a destroyed lab could be a massive crater from some sort of nuclear detonation, which the map-maker could make themselves since it'd be a one-off most likely.)

**Comment by RelMayers** [comment]
I'm waiting for more feedback, in my plan was for this to have loot tables affected accordingly.

**Comment by NetSysFire** [comment]
The No Hope mod has lots of looted buildings which were made by hand.

An algorithm needs to take many things into account, which include distance to the city center or general pre-Cataclysm population for human looting, and zombie population and other monster density for general damage. Zombies will obviously cause more damage when investigating noises than a wandering deer.
It will be a complex task since a locked office inside a say hardware store will be much less damaged than the actual store.

**Comment by Zireael07** [comment]
@NetSysFire not quite. Looting will happen to all buildings pretty much, since there were riots before Cataclysm started. And animals might cause damage but this is about looted (so not just damage, reduced drops too)

**Comment by LovamKicsiGazsii** [comment]
So something like #7892? I agree that an algorithm would work greatly here.
