### ISSUE TITLE
Can't equip elephant armor on pet dinos

### ISSUE THREAD

**Issue by tornikeo** [CleverRaven/Cataclysm-DDA#60097]
### Describe the bug

Pet dinos with elephant bodytype can't be equipped with chitin elephant armor. 

### Steps to reproduce

1. Tame mon_parasaurolophus, with bodytype "elephant".
2. Craft chitin elephant armor and wield it: 
![image](https://user-images.githubusercontent.com/56438982/184315423-5fd3971e-4757-4070-839d-6e400462d210.png)
3. Select to equip the dino with armor: 
![image](https://user-images.githubusercontent.com/56438982/184315486-b5141403-0432-4832-bbd5-070317cc1882.png)
4. Get this error: 
![image](https://user-images.githubusercontent.com/56438982/184315545-8a2361d2-8a01-48b8-afd2-b4ebae9811c9.png)

### Expected behavior

Dino with bodytype elephant does accept the elephant chitin armor.

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 21.10; Release: 21.10; Codename: impish; 
- Game Version: df06cbf [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Innawood [innawood],
    DinoMod [DinoMod],
    Megafauna [megafauna],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

Please ignore the smartphone in my inventory, playing as an innawoods char :) That's another bug.

**Comment by Marcos6226** [comment]
According to the code, he has inherited the **Bear** body type. It may be an overlook, but the owner or maintainers would have to confirm it.

If you want, you can check it yourself. The file path is `data/mods/DinoMod/monsters/dinosaur.json`
Don't forget to follow the trail of `"copy-from" :` lines.

**Comment by Light-Wave** [comment]
Poking @LyleSY

**Comment by LyleSY** [comment]
Yes, I've been meaning to finally make bear variants. Thank you, I'll bump that up on the list

**Comment by ZeldaGaladriel** [comment]
I'm thinking of working on this issue as a first-time contributor. Just to be clear, this dinosaur should be changed to inherit the elephant body type instead of the bear body type, correct?

**Comment by tornikeo** [comment]
I'm not sure - I think you have to do the following:
- add bear body type armors
- add their recipes
- make sure the dino has bear bodytype
- craft bear armor
- equip your dino with bear armor
- ???
- profit

Or something like that. The last step is optional.

**Comment by LyleSY** [comment]
Nice, this should be a good template @ZeldaGaladriel https://github.com/CleverRaven/Cataclysm-DDA/pull/50515

**Comment by ZeldaGaladriel** [comment]
@LyleSY For the most part I've been following your template, making a pets_bear.json that is identical to the other two except for replacing "ostrich" or "elephant" with "bear," and adding a "CSC_ANIMALS_BEAR ARMOR", to recipes.json. But the pets_bear_armor.json is more complicated because the elephant and ostrich have unique leather armor variants. I'm talking about the part starting at line 84 in pets_elephant_armor.json and pets_ostrich_armor.json. Should I come up with unique bear armor descriptions or were you planning on doing that? I do have a few ideas, say a Norse/Germanic theme like the Indian theme of the elephant descriptions.

On another note, I noticed a possible mistake in line 64 in pets_ostrich_armor.json. I doubt the end of the description here is meant to have "This caparison depicts four men in heavy metal armor riddled with bullet marks." when it isn't present in the same version of the armor for elephants.

**Comment by LyleSY** [comment]
Line 64: It is intended, little Australia armor easter egg https://en.wikipedia.org/wiki/Ned_Kelly

Otherwise great. Yes, I think it should have appropriate content for bears. I was thinking about some kind of Game of Thrones reference since there's bears all over that, but I'd love to see whatever you think is fun and makes sense
