### ISSUE TITLE
Allow the picking up of planters

### ISSUE THREAD

**Issue by pantherpusher** [CleverRaven/Cataclysm-DDA#60170]
### Is your feature request related to a problem? Please describe.

I find making planters en mass to be a pain en myass.

### Solution you would like.

I would like the ability to uninstall empty (unsown) planters and pick them up, so that you may put them into a vehicle and transport them elsewhere for use. You can already drag them, so it's not that far of a stretch to move them into the back of a truck.

**Comment by PatrikLundell** [comment]
A technical problem is that planters are "furniture" and "furniture" collide with vehicles when you try to drag it onto them.
The other problem is that planters have larger volume than any cargo vehicle part, and so wouldn't fit anyway.

The first issue could be worked around by allowing planters to be converted into "items" (and back), like e.g. step ladders, but the second problem would remain unless the planter volume was somehow reduced in the item state.

It can also be noted that planters probably shouldn't be possible to be dragged around, as it seems the recipe for them is based on planters with no bottom, where the soil beneath the planter is replaced with planting soil to a significant depth.

**Comment by descan** [comment]
> A technical problem is that planters are "furniture" and "furniture" collide with vehicles when you try to drag it onto them. The other problem is that planters have larger volume than any cargo vehicle part, and so wouldn't fit anyway.
> 
> The first issue could be worked around by allowing planters to be converted into "items" (and back), like e.g. step ladders, but the second problem would remain unless the planter volume was somehow reduced in the item state.
> 
> It can also be noted that planters probably shouldn't be possible to be dragged around, as it seems the recipe for them is based on planters with no bottom, where the soil beneath the planter is replaced with planting soil to a significant depth.

Maybe uninstalling them turns them into something like a "collapsed planter frame," which can be picked up and then installed via construction along with some soil. This item could be smaller in volume, as it would just be like, two Ls of wood that were jointed. You'd hammer them together into the box shape and fill them with soil.

**Comment by PatrikLundell** [comment]
There's little difference between that and dismantling a number of planters, transporting the parts, and then constructing a smaller number of planters out of the parts (because losses are involved). It should be noted that the amount of soil involved is huge, so you're up for many trips (I've done it for my base camp, so I know). Also note that you need pebbles for planters, and the only supply for a significant number of pebbles I know of is planters.

Also, I don't think we currently have any furniture->item->furniture sets of actions that has the "item" step consist of more than a single item, but that might not be a problem.

In order to actually move a whole planter in a vehicle the game would need some kind of logic to allow multiple cargo tiles to act as a combined container (like a flatbed actually acting like a flat bed rather than a number of distinct sections). That would be sufficient for a planter item, while additional logic would be required to allow for the transportation of "furniture".

**Comment by pantherpusher** [comment]
I find the idea of moving the planter as an item to be no weirder than being able to take down a full sized joiner and loading that into a cargo space, the ability to build planters on non-dirt tiles also implies that the planter box does not rely on being placed on dirt, and that it in fact can be used on any surface.

**Comment by PatrikLundell** [comment]
The ability to move planters and place them on non soil surfaces is in conflict with their construction requirements, which either make them rather high, or, more probably, involves replacing the soil beneath the planter with "better" soil. This hints at there really being two different planter constructions involved: the ones with a bottom, and the free land variety that are fixed merged into a single package.

**Comment by pantherpusher** [comment]
well what I'm looking for is a solution to wanting to build a farm on top of an aircraft carrier and not being able to put down soil

**Comment by PatrikLundell** [comment]
The solution (or, rather, work around) I've used to provide materials for planters in a canteen base camp expansion is to dismantle planters, move the soil and pebbles to a vehicles (and nails and planks, but they can easily be gotten elsewhere). Move the components to my vehicle, drive back to base, unload. And repeat. It works, but it's a lot of work, and the soil takes up a lot of space.
