### ISSUE TITLE
Copying books to SD cards should also copy recipies 

### ISSUE THREAD

**Issue by chrispikula** [CleverRaven/Cataclysm-DDA#60198]
### Is your feature request related to a problem? Please describe.

Currently, when you use external storage to download to SD card, it only downloads the books, not the recipes one my have accrued from decrypting and downloading SD cards along the way.

### Solution you would like.

That recipes also get copied, as currently they done.
Original Phone:
![image](https://user-images.githubusercontent.com/22281606/184792474-faeed897-6b02-4383-9c2b-0b35b43f58f8.png)
SD card copy to new AR glasses:
![image](https://user-images.githubusercontent.com/22281606/184792581-25b2da22-da6a-4b33-9754-f49674f16abb.png)

**Comment by chrispikula** [comment]
No, as I don't want to possibly lose my SD-card found recipes.

**Comment by ChromePoptart** [comment]
I've encountered this behavior, too (copying from a device to a clean SD card not also copying downloaded recipes from SD cards) -- it would be great if the downloaded recipes transferred, as well.

**Comment by chrispikula** [comment]
Oh, and likewise, you don't get to copy songs or photos, but since those are 'consumables', that vaguely makes sense.  (But still should be changed.)

**Comment by ChromePoptart** [comment]
Are downloaded songs actually consumable?  I know that the count of photos decreases when one looks at them, but I didn't think that songs are consumed/the count decreases when one listens to them.  I could of course just not have paid that close of attention!

I'm not sure I agree that "consumables" like photos should be transferred.  The argument could be made that doing that would allow a bulk download of a bunch of photos onto one device to be transferred to as many other items as desired, and that, by doing that, their consumable nature is bypassed -- copy 1000 photos to an SD card, download from SD card onto a new device, consume all 1000 photos on new device, download from SD card onto another new device, rinse and repeat.  I suppose this could be alleviated by making it so that:
1. when consumables charges are copied from a device, the consumable charges are deleted from the originating device and "moved" to the SD card.
2. when copying from an SD card to a new device, any consumable charges on the SD card are added to the new device and then deleted from the SD card.

The above applies to songs if they are indeed "consumable," but, if songs persist after listening to them, then they should also be able to be copied between cards and devices, just like books currently are and downloaded recipes should be!

**Comment by chrispikula** [comment]
I was more poking that photos and songs shouldn't really _be_ consumable.  Maybe have their effective boost be based on the quantity found, rather than have them be consumable, but that's stretching into a different issue.

**Comment by ChromePoptart** [comment]
Just tested this:  photos are consumable, but songs are not consumable.  Had an e-ink tablet with 13 downloaded photos and 13 downloaded songs.  All of the 13 photos were gone after one viewing, but the 12 songs persisted through two approximately one-hour sessions of listening to music via the tablet.

My two cents on consumability:  I don't have any true insight into why the decisions were made, but it makes sense to me that photos are consumable and music is not.  The photos don't hold any sentimental or nostalgic value for the player, given that they're just random pictures found on random SD cards -- so, they probably aren't interesting enough to look at multiple times.  However, even if songs are random and not specific to the player's tastes, it's definitely possible to get enjoyment across repeat listenings.
