### ISSUE TITLE
Combat and combat-related activities burn almost no calories and cause almost no weariness

### ISSUE THREAD

**Issue by actually-a-cat** [CleverRaven/Cataclysm-DDA#60223]
### Is your feature request related to a problem? Please describe.

If you go spend a whole day running around smashing zombies with a heavy weapon, pulping corpses, dodging attacks, hauling loot, smashing doors, firing guns, breaking grabs, climbing fences, jumping from roofs, getting smashed into walls, bleeding, choking on smoke, crying, trampling through bushes, crawling through sewers etc. etc. etc.

you will end up less tired and having burned fewer calories than if you had spent that time sitting a desk doing some light crafting. In fact, you'll probably be fresh as can be and ready to grab a shovel and dig a pit.

The activity level system as it currently is doesn't deal with very short periods of very intense effort. Many of the activities listed above take effort, some "extreme", but lasting only seconds (if that) at a time, they add up to about nothing.

### Solution you would like.

Anything done here will have to interact with the upcoming muscle strain system, which I don't fully understand, so I'm not sure. But I feel that at such a short time scale, for individual actions like swinging a weapon, the natural way to model this would be to attach a specific energy cost to every action, rather than trying to multiply a rate by a very short time. Actions could retain activity levels for the purpose of slowing down when weary, but their cost would be predefined.

### Describe alternatives you have considered.

We could probably get away with defining a series of activity levels for short actions that go far above the current "extreme", but that feels like abuse of the system.

I've thought about tying it to stamina (use or recovery) because they are really two sides of the energy expenditure coin, but would that be difficult to make consistent?

### Additional context

Killing several hundred zombies with a fire axe (debug invincibility on, attacking continuously except for breaks to recover stamina), dragging their corpses into piles, and pulping them, all over about 4 hours:
![combat](https://user-images.githubusercontent.com/102094270/184990330-26d72f2c-7c20-45e3-9d4b-3b01b4bf5210.png)

Same character carving sticks ("moderate" activity) for about 4 hours:
![crafting](https://user-images.githubusercontent.com/102094270/184990812-2c126e35-0237-4881-b12d-f2b2d0d3d3c1.png)

Spending the same amount of time doing nothing consumes about 250 calories.

**Comment by anoobindisguise** [comment]
I've experienced this too, as loathe as I am to let it get nerfed I frequently kill a thousand zombies on my first day on a character, granted I usually play a character who is very athletic (good cardio, good dodge, good traits, though not necessarily any weapon skills) so it is an extreme case. Once they really get going and have good armor, maxed skills, and strong weapons, they can sorta just cleave through a whole city in a day, although the zeds haven't caught up yet so it's not surprising they're having an easy time.
On the other hand weariness definitely penalizes melee a little too hard, as the activity system making your attacks take longer - 25%, 66%, 150%? just insanely worse. Definitely means you just straight up do not do much fighting if you're above light weariness and even light weariness is pushing it.
If we're going to address fighting counting as "super weariness" it would be a good time to also make weariness affect it differently, such as increasing stamina costs by such an amount - you can put out the same effort because your life literally depends on it, but it's going to take a ton out of you to do it.
One possible way to do this would be to make activities "hang" for longer. It already seems to work this way with walking and running, after stopping and standing still you still count as Moderate or Active for a bit longer. If all activities stayed for like, 5 seconds after they finished, it would have no effect on crafts but make fighting more consistently a wearying experience.
