### ISSUE TITLE
Advanced AR glasses make your eyes uncomfortable from the armor

### ISSUE THREAD

**Issue by chrispikula** [CleverRaven/Cataclysm-DDA#60251]
### Describe the bug

The `pair of advanced AR glasses` are TOOL_ARMOR, on the outer layer, and are rigid.  In the @ character menu, wearing them gives:
![image](https://user-images.githubusercontent.com/22281606/185171643-aa2f9d57-7ec3-4990-9b1a-eb13e3b3cda0.png)

Wearing a face shield w/ a helmet, sunglasses, swapping the order, none of that has any effect other than removing the AR glasses.

### Steps to reproduce

Spawn a `pair of advanced AR glasses`
Wear them
Feel them rub your eyeballs, making you uncomfortable.
Wonder if there's something soft you can put on your face that'll help, other than a blindfold.

### Expected behavior

I'm... not sure.  This is probably not intended, but their might be an intended solution that I can't see?

### Versions and configuration

Win 10, tiles, 013e053

**Comment by PatrikLundell** [comment]
Well, it's probably intended that they're rigid from the perspective of not being possible to wear concurrently with other stuff, but these things are presumably padded to make them not be uncomfortable to wear from a chafing point of view.
The issue thus seems to be a lack of granularity, where "rigid" both blocks concurrent usage of the location AND makes it uncomfortable to wear without some kind of padding underneath.
I believe the opposite situation was mentioned the other day, where chainmail ought to not be rigid, because it isn't, but also ought to be uncomfortable to wear without anything underneath because the rings would dig into the skin,
