### ISSUE TITLE
Welding Kit unusable for recipies requiring arc welders.

### ISSUE THREAD

**Issue by Aimless-dude** [CleverRaven/Cataclysm-DDA#60261]
### Describe the bug

The welding kit, along with having a grammatically incorrect description- cannot be used as a welding tool in recipes. This is despite the "kit" consisting of an asbestos blanket and an arc welder. In addition, the welding kit is unlootable, and it's crafting recipe cannot use the makeshift arc-welder.

### Steps to reproduce

1. Make a welding kit, from an Arc welder and a welding blanket
2. Load the item with a medium battery
3. Attempt to build any item that calls for an arc welder as a tool

### Expected behavior

The Welding kit, being a regular arc welder and a special blanket, should still be able to be used as a normal arc welder, though honestly? I think the Welding kit is better off removed, or taken a long hard look at, as it's not doing much other than taking up space, it's so called intended function of repairing carbon steel can be done by a makeshift arc wielder on it's own, the crafting recipe is janky and calls for an uncraftable, semi rare item to do.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1826 (21H2)
- Game Version: 915ef22 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Alternative Map Key [alt_map_key],
    Translate Complex Dialogue [translate_dialogue]
]

**Comment by ZeroInternalReflection** [comment]
I can confirm that the welding kit is not usable for crafting recipes requiring welding.  The root cause seems to be in data/json/requirements/toolsets.json.  Welding requirements used in crafting such as "welding_standard" and "welding_alloys" specifically list the arc welder, makeshift arc welder, integrated toolset, and oxy torch as the acceptable tools.

Adding "welding_kit" to the list results in the welding kit being usable in many recipes (it would need to be repeated in several other places):
```
  {
    "id": "welding_standard",
    "type": "requirement",
    "//": "Crafting of steel/iron items or installation of vehicle parts",
    "qualities": [ { "id": "GLARE", "level": 1 } ],
      "tools": [ [ [ "welder", 10 ], [ "welding_kit", 10 ], [ "welder_crude", 15 ], [ "toolset", 15 ], [ "oxy_torch", 2 ] ] ],
    "components": [ [ [ "welding_rod_steel", 3 ], [ "welding_wire_steel", 3 ], [ "brazing_rod_bronze", 3 ] ] ]
  },
```
Resulting in:

![Proof_of_concept](https://user-images.githubusercontent.com/89038572/185238658-c7f85d27-b4fc-4fc3-813b-8bc1150fb08c.png)

I'm betting the longer-term plan is to differentiate different types of welding, requiring a fancier tool for certain types.  However, for now, making the welding kit actually weld makes a lot of sense to me.
