### ISSUE TITLE
Add bare-bones basecamp recipes to other types of basecamp

### ISSUE THREAD

**Issue by jiornojiovanni** [CleverRaven/Cataclysm-DDA#60298]
### Is your feature request related to a problem? Please describe.

The new recipes in the bare-bones camp are REALLY useful, I was able to construct the first part of the workshop in a week from game start, with just one npc. 

### Solution you would like.

Add all (or just a really tiny selection) of the new recipes to the other camps.

Even only the nails and the wooden panels recipes (and maybe the hunting missions) are a massive improvement, as you are able to just order your npcs to work for you instead of doing all the work by yourself which doens't make a lot of sense, especially when you have multiple npcs.

### Describe alternatives you have considered.

Keeping all the manual work for the player.

**Comment by Marcos6226** [comment]
I would love to see this game fully automated.
NPCs doing all the work and players just hunting, cleaning cities and protecting bases.

**Comment by jiornojiovanni** [comment]
There is already a system for this (the jobs inside the basecamp menu), but for me at least It doens't really work properly.

**Comment by PatrikLundell** [comment]
There's a major issue in the form of the basecamp menu, which quickly gets rather unwieldy as you add lots of recipes to it (and there are some people who thing their recipes are so valuable that all of them definitely have to go in there, and since the core teams accepts those additions I assume they agree). Some core team member has expressed an opinion that I interpret boils down meaning that the interface has to be so burdened down as to be broken to get someone to take on the task to update it, rather than keeping the game playable by restricting the overload until someone fixes it.

Thus, there's a need for a major rework of the base camp crafting UI to allow it to support lots of recipes. In my view it ought to be something similar to the PC crafting interface, but those who are capable of implementing such a UI seem to have other priorities.

There are other issues with companion crafting as well. You can't use recipes that craft liquids, for instance, as the liquids would just be poured on the ground, as the functionality that PC crafting uses to pour liquid into containers isn't present in the companion crafting code (and it's buried very deep into the PC crafting and UI code in a way that makes drawing on containers in camp storage zones rather messy to introduce.

It can be noted that most of the recipes in the bare bones basecamp ARE available to other base camps, but only after they have been built up to various degrees. The difference here is that the recipes are made available from the start rather doled out as rewards for expansion.
Eventually I'd like to see recipe availability being restricted by knowledge (which currently isn't possible for base camps), and the available equipment restricting the recipes you can actually use. There is currently a (slow) effort to increase the granularity of equipment capabilities, but it's a fair while until there is a significant distinction between a chemistry lab and a kitchen (not to mention any risk to the player for using the same equipment for the production of toxic chemicals as for cooking of the lunch).
