### ISSUE TITLE
[Idea] Automatic glue mod management

### ISSUE THREAD

**Issue by Light-Wave** [CleverRaven/Cataclysm-DDA#60351]
### Is your feature request related to a problem? Please describe.

Cross-mod interactions is currently tricky to manage.
Let's say you want to add an animist spell to Magiclysm that summons some dinorsaurs from Dinomod, that is only accessible if both mods are loaded. Or let's say you want to create spellcasting dinos.
Let's say you want to make herbalism recipes from Magiclysm autolearn if Innawood is also loaded.
Let's say you want to merge the changes Innawood and TropiCataclysm does to the worldgen if both mods are loaded.
Let's say you want to add any number of other small mod interactions, such as a single line of dialogue, or a slightly altered recipe.

Currently there are two main ways of doing this, both with their flaws.
First, you might create a 'glue' of 'bridge' mod that requires the two or more mods you want to create an interaction between. This has the advantage of being easy to read and doesn't require altering the core json files, but have the disadvantages of cluttering up the mod list, and there is no guarantee that the player will remember to activate it, which can be a problem if the glue mod is used to fix game-breaking bugs that arises due to the mod interaction.
The second way is to try to solve the issues by getting creative. This can include creating dummy creatures, lists, and so on in the core json files, and then have the different mods alter those. It can involve using Event on Conditions to alter the recipes available to the player depending on what mods are loaded. This have the advantage that they don't clog up the mod list, and there is no way the player will accidentally forget to enable these changes. The disadvantage is that they are difficult to implement, difficult to read, and difficult to maintain. Further more, they often require altering the base json files in arcane ways, such as adding an empty list that doesn't do anything.

Neither of these solutions are very good.

### Solution you would like.

Add a category of mod called 'glue' or 'bridge'.
These are hidden in the mod manager used when creating a new world, so you don't see which ones are available, and which ones are currently active.
If all the dependencies of a glue mod is met, then it is automatically added to the list of mods.
If the dependencies ceases to be met, then the glue mod is removed.

Later considerations:
If possible and practical, also run this check when a world is loaded, since new glue mods might have been added since last time that world was loaded. But perhaps that's an issue for later.
It could be meaningful to add a keybind that shows/hides glue mods in the mod manager for debugging purposes. Although the idea is that weather or not a glue mod is installed should not be a decision the player can choose, nor need to worry about.

### Describe alternatives you have considered.

Issue #48589 describes an other approach to the same problem. I think the solution using glue mods might be easier to implement.
PR #58727 tries to make mods compatible without glue mods, but ran into problems that would require either more infrastructure or a glue mod.

**Comment by GuardianDll** [comment]
I remember one small trick from my Rimworld experience - their solution was this:
To make mod A compatible with mod B, mod A can have a folder with name "mod_B_id", that contain all stuff, that mod A need to change inside mod B to work
so, in our case, to make Innawood and Magiclysm compatible, Innawood may contain "magiclysm" folder, that activates, when Magiclysm mod is loaded, and contain edited or brand new recipes for Magiclysm mod.

**Comment by Light-Wave** [comment]
Are you suggesting to add the functionality that if mod_B is loaded, then and only then is the folder mods/mod_a/mod_b loaded?
That sounds like a similar way to solve the same problem that also requires C++ work, and also requires a check to make sure that the mod_a/mod_b folder is always loaded after mod_b is loaded. Otherwise, mod_b would overwrite the changes made in mod_a/mod_b.

If you instead are talking about just having some magiclysm data copied into Innawood without any additinal C++ work, that would probably mean that the magiclysm herblore ceipes always en up being displayed in the crafting window, even if Magiclysm isn't installed. It also means a tiny bit more trouble keeping the Magiclysm and the Innawood/Magiclysm folders synchronized in future updates.

**Comment by ZhilkinSerg** [comment]
> First, you might create a 'glue' of 'bridge' mod that requires the two or more mods you want to create an interaction between. This has the advantage of being easy to read and doesn't require altering the core json files, but have the disadvantages of cluttering up the mod list, and there is no guarantee that the player will remember to activate it, which can be a problem if the glue mod is used to fix game-breaking bugs that arises due to the mod interaction.

There are no flaws in here and this is exactly how it is supposed to work: if someone wants to create a mod that is dependent on several other mods - they can do that.

**Comment by chrispikula** [comment]
> I remember one small trick from my Rimworld experience - their solution was this:

It was actually quite a bit more involved than that.  You could have specific load folders that only activated if other mods were found, but the more common solution was to do conditional patching, as such:

```
<Operation Class="PatchOperationFindMod">
    <mods>
      <li>Dubs Bad Hygiene</li>
    </mods>
    <match Class="PatchOperationFindMod">
      <mods>
        <li>Fertile Fields [1.1]</li>
      </mods>
      <match Class="PatchOperationFindMod">
        <mods>
          <li>Fermenter</li>
          <li>Fermenter (Continued)</li>
        </mods>
        <match Class="PatchOperationSequence">
          <operations>
            <li Class="PatchOperationReplace">
              <xpath>//Defs/Fermenter.FermentDef[defName="Ferment_DBH_Biosolids"]/Product</xpath>
              <value>
                <Product>RawCompost</Product>
              </value>
            </li>
          </operations>
        </match>
      </match>
    </match>
  </Operation>
  ```
(Code copied from DocWorld, w/ permission to edit & distribute.)

In the above example, DocWorld would check to see if you had Dubs Bad Hygiene, then Fertile Fields, then the Fermenter mod, either the base version, or Mile's continue version.  If all of that was true, it'd then alter the product of a machine in the Fermenter mod from Biosolids to RawCompost.  This was because Fertile Fields would, with it's own patches, remove Biosolids from Dubs Bad Hygiene, which Fermenter expected.

Such examples are _many_, and juggling them all was incredibly difficult, which is one reason DocWorld got discontinued.

Now, this method, without using loadfolders, was a bit slower on load, as the game engine would load and logic through files even if they didn't have the specific mods that were looking for, (short circuiting out, of course), but you could target highly specific mod combinations this way without impacting other users gameplay.  It did become standard method, but that's also because Rimworld & Harmony had a unique infrastructure when it came to _detecting_ which mods were loaded, which we, thankfully, ~~won't~~ don't have.

**Comment by PatrikLundell** [comment]
At the very least, the bug report info generation should include automatically added mods, rather than forcing those trying to fault find to figure out that there are additional unlisted mods that sneak in to modify things.

That will cause reporters to think things are wrong and that unselected mods have erroneously snuck into their games if they're completely hidden on mod selection.

**Comment by Nymall** [comment]
I'm leveraging what we currently have a lot right now, and hopefully we can implement something to solve this issue and rectify mod bridges all together. I've created a subfolder holding small mods that enable select content or override for compatibility, using ZZ_ to ensure it is the last in the load order. I'd love to be able to do away with all that.

Going back to rimworld, during mod loading it has a post load phase where it reapplies recipes and changes to mods after all the content is loaded. Xenobiotic patcher, for example, uses this to ensure cross capabilities between mods and that it applies to all mods. At the moment though, mod loading happens once and is systematic - I think an easier solution could be applied directly to the JSON.

For each recipe or item, have a json value that corresponds to the mod the item or recipe depends on. For example, let's say I have a Stonk I want to add to the Chonks Mod. Here's how I see the JSON looking:

`{
        "type" : "COMESTIBLE",
        "required": "stonkmod",
        "id": "stonk",
        "name": { "str": "stonk" },
        "category": "books",
        "description": "You have found a stonk! You should invest this in your chonks.",
        "weight": "15 g",
        "calories" : 0, 
        "to_hit": -3,
        "color": "white",
        "symbol": ",",
        "material": [ "paper" ],
        "volume": "50 ml",
        "petfood": [ "CATFOOD" ],
        "flags": [ "TRADER_AVOID" ]
    }
`

Because the Required line exists, the game would set the item asside and process it after all of the rest of the mods were loaded. if the mod is not on the load list, it would discard the item or recipe. This would, in theory, work for all classes of change. as they would load after everything else is already processed, so you would no longer have to worry about load order.

**Comment by ZhilkinSerg** [comment]
> I'm leveraging what we currently have a lot right now, and hopefully we can implement something to solve this issue and rectify mod bridges all together. I've created a subfolder holding small mods that enable select content or override for compatibility, using ZZ_ to ensure it is the last in the load order. I'd love to be able to do away with all that.
> 
> Going back to rimworld, during mod loading it has a post load phase where it reapplies recipes and changes to mods after all the content is loaded. Xenobiotic patcher, for example, uses this to ensure cross capabilities between mods and that it applies to all mods. At the moment though, mod loading happens once and is systematic - I think an easier solution could be applied directly to the JSON.
> 
> For each recipe or item, have a json value that corresponds to the mod the item or recipe depends on. For example, let's say I have a Stonk I want to add to the Chonks Mod. Here's how I see the JSON looking:
> 
> ```
>         "type" : "COMESTIBLE",
>         "required": "chonkmod",
>         "id": "stonk",
>         "name": { "str": "stonk" },
>         "category": "books",
>         "description": "You have found a stonk! You should invest this in your chonks.",
>         "weight": "15 g",
>         "calories" : 0, 
>         "to_hit": -3,
>         "color": "white",
>         "symbol": ",",
>         "material": [ "paper" ],
>         "volume": "50 ml",
>         "petfood": [ "CATFOOD" ],
>         "flags": [ "TRADER_AVOID" ]
>     }
> ```
> 
> Because the Required line exists, the game would set the item asside and process it after all of the rest of the mods were loaded. if the mod is not on the load list, it would discard the item or recipe. This would, in theory, work for all classes of change. as they would load after everything else is already processed, so you would no longer have to worry about load order.

We already have `dependencies` syntax for `modinfo.json` that allows to specify mod loading order, so all you need is to split your data between several mods and assign proper dependencies - then load order should be handled automatically. You proposed `required` syntax will just move dependency definitions to a lower scope - it is just more easily manageable to define dependencies once on mod level than separately for each entity.

Surely we have some data types that aren't loaded properly yet (e.g. https://github.com/CleverRaven/Cataclysm-DDA/issues/60394), but that's just because `region_settings` and `region_overlay` loading was not yet refactored to behave properly using `load` and `finalize` stages.

**Comment by chrispikula** [comment]
That runs into the issue that the json parser would need to check for required, first, on every single json entry.  Of which there are, nearly 47 thousand in the base game.

Remember, json entries don't have a required order, so the "required" tag could be at the very end, and the "flags" tag could be the first one.  Heck, there's no problem at all if you organize your json tags by line-length. (And, yes, this frustrates me.)

**Comment by Light-Wave** [comment]
> all you need is to split your data between several mods

I guess I'll try that out then. At least until one of us changes our mind about this. ;P
In that case, how about a new category for mods who's only purpose is to make two other mods work together? Such as "Glue" or "Bridge"?

---

As for the discussion about loading folders, I think that might be an even better approach for mod developers. But I'm not clear on how the solution would look. Perhaps if there is a modinfo.json in a sub-folder, then the loader will check the modinfo for requirements, and only load the folder if the requirements are met? Then you would need to make sure that the folder is loaded after all the required mods are loaded. Compared to my suggestion about external glue mods, this sounds like the better and more elegant solution, and the one easier to deal with for modders, but also sounds more difficult to implement.

As for putting requirements on single items, that could work. But I think the folder solution would be just as easy to use since it makes sense to put everything needed for compatibility with an other mod in its own folder. Using the folder solution also sounds potentially less CPU heavy.

**Comment by anothersimulacrum** [comment]
> That runs into the issue that the json parser would need to check for required, first, on every single json entry. Of which there are, nearly 47 thousand in the base game.
> 
> Remember, json entries don't have a required order, so the "required" tag could be at the very end, and the "flags" tag could be the first one. Heck, there's no problem at all if you organize your json tags by line-length. (And, yes, this frustrates me.)

Most of our JSON loading is order independent, and that which isn't is savegame stuff, not game data.

**Comment by chrispikula** [comment]
> > 
> 
> Most of our JSON loading is order independent, and that which isn't is savegame stuff, not game data.

Yeah.  I mean check first, in that it'd have to be the very first thing that the json interpreter checked for, regardless if there were glue mods or not, as they'd have to not be checked over if they were this subtype of entry.  Don't need to parse it and throw an error if the mod isn't loaded, etc.

**Comment by kevingranade** [comment]
This is very much not a workable solution, it invites/ demands proliferation of these glue mods, https://github.com/CleverRaven/Cataclysm-DDA/issues/48589 is a real fix for this sort of thing.
