### ISSUE TITLE
Ability to combine adjoined cargo space in vehicles

### ISSUE THREAD

**Issue by xrogaan** [CleverRaven/Cataclysm-DDA#60433]
### Is your feature request related to a problem? Please describe.

It is currently impossible to move a fridge over large distances (without carrying it). Despite the space available in a cargo truck is more than enough for a single fridge, the way cargo works means that large volume items cannot fit.

### Solution you would like.

The ability to build either a joined cargo, or a partitioned cargo (as current). The joined cargo could be linked in each cardinal direction, selectively. Practically it would mean a _n_ tiles cargo space, which could lead to issues if it were ever broken in two.

### Describe alternatives you have considered.

Linking two cargo space being potentially problematic, have the dropped item automatically spread to another cargo space. Doing so may lock both cargo space from usage, large objects needs to be secured.

### Additional context

I just want to be able to move fridges, whole, to an off grid base.

**Comment by PatrikLundell** [comment]
I think it's tricky to implement (which is not to say I wouldn't want it). My work around is to carry such items while driving. It's not something I'd try in the real world, but on the other side I refuse to use a phone while driving.

**Comment by xrogaan** [comment]
> I think it's tricky to implement

Could you explain why? I mean, the system hasn't been designed for it but we could always have an intermediary item. Like how a mattress can be placed on the ground, a fridge could be placed into a cargo container.

**Comment by PatrikLundell** [comment]
The problem is that the game has support only for single tiles seen in isolation. A vehicle is constructed out of multiple vehicle parts, but each part is confined to a single tile (which it can share with other parts, using vehicle rules).

This also means that items have to reside in a single tile, and can never reside partially in one and partially in another. When you place something in storage, it ends up within that single tile's storage (which can be larger than the volume of a single empty tile: warehouse shelves have a capacity of 3.5 m3, while an empty tile can carry only 1 m3). When you place something in a tile that doesn't have enough (remaining) space to contain it, the game either refuses to accept it being dropped there, or it places it in a neighboring tile with sufficient space (which can be the ground under a vehicle part with storage), and if there is no room at all the item is either just refused to be moved, or it disappears completely because the code severed the tie to where the item came from, but then failed to find the place it should be placed on. That will happen a lot with items that have a volume larger than 1 m3 (because no ground tile can contain them), an issue that has happened with batch crafting.

I'm not saying it is impossible to implement joint storage, but that would require new logic, and it would also require care to ensure that the logic isn't too time consuming to execute, slowing the game down. In principle it might be possible to have the spilling over logic when items are dropped in a vehicle spill over to other vehicle tiles rather than the ground, for instance (and not having things ending up on the ground without you knowing would be a good thing).

We probably have to use intermediate items ("dismantling" "furniture" into items that can then be "constructed" back into "furniture") for quite some time, for instance, as "furniture" and "vehicles" can't coexist in a tile without colliding (with the exception of plant "furniture" that can be driven over, but still collides with "furniture").

I'm using quotes for "furniture" and "vehicles" because those sort of are layers on which things can exist on a tile, and both of them contain things that aren't what the name suggest. Plants in the terrain are "terrain" (mainly trees) or "furniture", for instance, and "vehicles" include both actual vehicles, small "vehicles" such as shopping carts, and the recently introduced appliances.

**Comment by harmonickolobok** [comment]
We already have some multitile doors that open/close simultaneously if you interact with any of their tiles. Would it be possible if we have a single "space" that would just be accessible from any tile of the connected cargo spaces? That space would have size of sum of all cargo space sizes. As a starter bug prevention we could prohibit uninstalling any of the cargo spaces while that unified space isn't empty.
P.S. To somewhat mitigate improved access for items(from any cargo space tile) - move cost of getting an item can depend on fullness of this space.
