### ISSUE TITLE
Magiclysm - Druid healing spell

### ISSUE THREAD

**Issue by Altogolik** [CleverRaven/Cataclysm-DDA#60451]
### Is your feature request related to a problem? Please describe.

Druid should have a normal healing spell, he is a druid (he is almost always associated with healing)
And now he only has a sacrificial healing of others, a useless skill. (for most players).
Druid branch is pretty weak I suggest to make a normal healing

### Solution you would like.

I have several options for solving the problem
1. Replace the skill to a directed skill very fast regeneration (it will be different from the instant healing biomancer, but will heal a little more over time) time of action ~ 20-100 moves heal about 25-30 (maximum)
2. Skill acting on the area, you can apply both to themselves and their allies are also not instant healing.
3. Invokes a totem that exists for some time and gives around itself regeneration.
4. Simply allow him to heal himself too, current skill.

### Additional context

It would make the druid branch more attractive, now there is nothing cool in it except the bow.

**Comment by mark-ik** [comment]
Something like Herbal Medicine: consumes 20 wild herbs and heals a specific part 10-20 health over 50-100 turns while disinfecting wound or purging infection? Also hi, I usually lurk.

**Comment by anothersimulacrum** [comment]
CC @KorGgenT

**Comment by Altogolik** [comment]
> Something like Herbal Medicine: consumes 100 wild herbs and heals a specific part 10-20 health over 50-100 turns while disinfecting wound or purging infection? Also hi, I usually lurk.

It would be weaker than just mana-consuming treatments (not sure it's cool to carry around weed everywhere). 
But the idea of disinfecting the wound and clearing the infection is pretty cool. I think you could make two skills one is just health regeneration, the second is healing herbs that disinfect and cleanse the wound + treatment.
As an option, you can add a skill to collect special healing herbs (the skill itself requires mana) and after they can be used as bandages (but healing, cleansing, disinfecting)

**Comment by mark-ik** [comment]
I worry that casting regeneration with no cost besides mana would make the druid the poor man's biomancer. It's also not very interesting mechanically to me.

Here are three spell drafts with options for effects that would draw upon their use of/affinity to plants as opposed to turning mana into health directly. The first is complicated but the other two seem sensible enough to me.

Photosynthesize

- if in sun, recover health slowly over the course of the spell's duration. You should be able to heal about a third of your limbs' health in ideal conditions at max spell level. 
- high mana cost, like 500 or more.
- a limb's clothing coverage (or encumbrance?) should negatively affect its recovery rate as a proxy for skin exposure.
- increase stamina recovery rate because this is a form of respiration and stamina is basically breath, right?
- could have component cost, like a withered plant or vegetable comestibles.
- maybe increases, decreases, or regulates body temperature, I don't know how plants work I'm realizing

Herbal Medicine (poultice? vulnerary?)

- forages through underbrush (or consumes wild herbs) and produces an amount of herbal medicine that increases as you level up the spell (to a capped amount like 1/10 the amount of herbs required).
- nominal mana cost, rationale is you use mana to sense the right plants to take. Very druidic.
- 5 min to 1 hr casting time.
- usable as bandages with slight regenerative effect over time. Not a lot but enough to keep you going.
- staunches bleeding like adhesive bandage (not great)
- disinfects limb like antiseptic (or hydrogen peroxide if that's worse).

Goodberry

- consumes herbal medicine (or herbs), produces more goodberries as you level up the spell (starts at 1/5th, goes up to input cap)
- higher mana cost perhaps comparable to crystallize mana. Rationale is you put mana in to make the plants grow goodberries.
- longer casting time. Should take one to a few hours depending on spell level?
- comestible with all limb regenerative effect over time, maybe 10-20 health total.
- purges infection like narrow spectrum antibiotics?
- if you eat too many you get a nutritive overload, like if you ate a bunch of multivitamins.

This is a bit OP but you get what I'm saying. Druids would know how to use or emulate plants to heal their wounds, but they might not know how to heal them directly with a spell, or else why bother with the plants? That differentiates the druid and the biomancer, who would manipulate their body to overcome physical trauma.

**Comment by Altogolik** [comment]
For me, the main thing is to make the druid's cure not worse than the biomancer's cure spell (maybe different, but not much worse).
If you do regeneration on the sun, it's obviously worse than just direct healing.
If you can only heal in the woods that's also a big disadvantage.
But if you can pre-create healing herbs (or berries) on the grass or surface, and eat them as needed, this is still more or less convenient (here I think you need the maximum herbs that can be produced at once)
Also an idea came to mind, if the druid can grow vegetables or berries on the ground (this could be another 1 skill on top of healing) this would be another druid virtue which is good.

But if you have to choose I would prefer direct healing (it is the most convenient and not worse than biomancer)

Ideally we could do different skills:
1. Regeneration skill which the druid can use on himself everywhere (slowly healing health)
2. Herbs/berries which the druid can grow in the forest and carry around with him (disinfecting, cleansing, nourishing, maybe a very weak cure)
3. Growing vegetables on the ground (spends a lot of mana, but you can grow your own food and eat it for a few days) Cucumbers, carrots, pumpkins, melons, etc. (grow random nutritious plants)

**Comment by GuardianDll** [comment]
When alchemy will be merged, ill do 2 healing spells
First will consume some new herbs, wouls be cheap and effective
And another will heal you with only mana, but will cost pretty much mana
