### ISSUE TITLE
Molotov cocktail burst into fire when lit

### ISSUE THREAD

**Issue by gettingusedto** [CleverRaven/Cataclysm-DDA#60495]
### Describe the bug

When activating a molotov cocktail to lit it, it burst into fire.

### Steps to reproduce

1. Make a new world
2. Get yourself molotov cocktail and a lighter
3. Wield your molotov and lit it
4. Burn

### Expected behavior

Not exploding on my hand.

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: samsung; Model: SM-A710F; Release: 7.0; Incremental: A710FXXU2CRC2; 
- Game Version: bff870b-dirty [32-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by ANickelN** [comment]
Can't replicate on version:

- OS: Windows
    - OS Version: 10.0.19043.1889 (21H1)
- Game Version: d0f4854-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    No Fungus [No_Fungus],
    Translate Complex Dialogue [translate_dialogue]
]

![cataclysm-tiles_4HEuXHWNZI](https://user-images.githubusercontent.com/52714184/187044708-231af018-0159-402b-bed5-9072e8304782.gif)

**Comment by Hirmuolio** [comment]
I does not blow up immediately. But it does blow up on your hand one turn after activation. If you have some speed penalty maybe it can happen immediately?

But it is bugged still. It should not blow up in hand.

For some reason item::process_tool calls the wrong thing.

**Comment by ANickelN** [comment]
I couldn't replicate that either, I waited a turn or two after lighting it, and it went out, or did nothing.

**Comment by Hirmuolio** [comment]
You are on a too old build. It is like several hours behind master :d.

**Comment by ANickelN** [comment]
/confirmed on version:

- OS: Windows
    - OS Version: 10.0.19043.1889 (21H1)
- Game Version: 1631976-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    No Fungus [No_Fungus],
    Translate Complex Dialogue [translate_dialogue]
]

**Comment by Hirmuolio** [comment]
#60039 is causing this but I can't find why.

Before that the held moltov iuse gets called from here https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/item.cpp#L13275 (this causes the mysterious bool to be false)
After that the held molotov iuse gets called from here https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/item.cpp#L13248 (this causes the mysterious bool to be true)

The reason is that before that change the molotow did not count down charges. Now it does count down charges. And when tool runs out of charges the above thing is called.

But why did it not count down charges before and why does it count down charges now? That is a mystery.
