### ISSUE TITLE
Mayapple becomes just Apple after smoking. Unfair!

### ISSUE THREAD

**Issue by EternalKitten** [CleverRaven/Cataclysm-DDA#60599]
### Describe the bug

After I put my mayapples into the smoking rack they came out as just apples. I was shocked.

### Steps to reproduce

1. Put mayapples into the smoking rack
2. Light the rack up
3. Wait to see the result

### Expected behavior

Mayapples should stay mayapples after you smoke them. They are not actually apples. Like at all.

### Screenshots

![mayapple_controversy](https://user-images.githubusercontent.com/82908191/187505113-71a4b677-bfb4-457a-a42b-88b00c837aeb.png)

### Versions and configuration

2022-08-30-1121 Win 10

### Additional context

![sadmayapple](https://user-images.githubusercontent.com/82908191/187505923-237ca524-9f36-4240-b37e-4e808ab6d3ee.png)

**Comment by PatrikLundell** [comment]
/confirmed

Smoked debug spawned apples, mayapples, and pineapples, resulting in:
"dehydrated fruit, apple (fresh) (10)"
"dehydrated fruit, apple (fresh) (10)"
"dehydrated fruit, apple, pineapple (fresh) (10)"

I'm somewhat surprised, as I would have expected to see "dehydrated fruit, apple, mayapple (fresh) (10)" as that's how pinapples get mangled. When extending the specification of what dried fruit it was beyond the few that were specified at the time, I saw the issue with pineapple but decided not to bother because of the low probability of actually find any fresh pineapples, and the resulting text would just look odd, but not directly misleading. The cause of the odd string wasn't in the vicinity of the JSON files I updated.

I believe this is caused by how something (I don't know if it's a regular expression from some JSON file or actual code) matches strings to generate the name, so "apple" is found both in "apple", "pineapple", and "mayapple" (and you can't go for an exact match, as that could result in issues with plurals).

Further investigation:
You'll transform your mayapples into "dehydrated fruit, apple, mayapple (fresh) (10)" (assuming you smoke 10 of them) by updating data/json/items/comestibles/fruit_dishes.json section for "dry_fruit" to have an entry for mayapples (I tried that locally, and it worked). What really should be done, though, is to update all the applicable sections in that file with the applicable new wild plant stuff that was recently added (but this part missed). I have some vague memory of another file also needing to be updated, although I may confuse it with the corresponding file for veggies. Hm, I think you might want to update irradiated_fruit.json as well (and the corresponding veggie file).

In addition to that, someone may want to locate the logic for matching sub expressions and update it to only return the longer matching string when there are multiple matches.

**Comment by OnTheDouble** [comment]
Hey Patrik I know it's a minor issue and I didn't have my hopes up so thanks for actually looking into it.

**Comment by NetSysFire** [comment]
Author of the PR which introduced mayapples here. Thanks for reporting that bug. I'll add a dedicated dry_fruit entry in #60187 for it.

**Comment by PatrikLundell** [comment]
Thanks for reporting back, @NetSysFire. If you're doing that, could you also take care of the fruit drink recipes I missed when adding the (at the time) remaining fruit and veggies for drying (you'll find that the sections in drink.json are shorter than the corresponding ones in fruit_dishes.json, indicating the ones that probably should be added)?
The easiest way to find where you need to add stuff is probably to search for "conditional_names" in the JSON files (e.g. using Notepad++), as that will give you 100 places out of which most deal with levels of cannibalism.

**Comment by NetSysFire** [comment]
Don't worry. I have vim, grep and forbidden regex knowledge here. I'll manage.

**Comment by EternalKitten** [comment]
#60623 fixed this, tested myself and it works fine. Thanks everyone, I'm closing it now.
![image](https://user-images.githubusercontent.com/82908191/191636597-aa9ee4f5-23a0-4685-8888-ad24ef4aa696.png)
