### ISSUE TITLE
Fused Dragonflies Nerf and Dragonfly Rework

### ISSUE THREAD

**Issue by sadenar** [CleverRaven/Cataclysm-DDA#60667]
### Is your feature request related to a problem? Please describe.

A devcord discussion about high tier mutants generally being broken unequivocally asserted that fused dragonflies are OBVIOUSLY the worst offender.
There is no reason for something that is conceptually supposed to be two mega stage dragonflies fused together into a spawner type monster and crippled in the process to have such high attack, speed and ungodly HP (1100 omg).

### Solution you would like.

The solution to this would be first to heavily nerf this monster, it should not be this quick (its very description says it's struggling with this weight), it should not be this ungodly beefy.

2nd, this is our current mega evolution step of the dragonfly line, but it'd make more sense for this to be a specialized offshoot spawner/monster creating variant leaving us with an evolution tree like this.
![dragonfly tree](https://user-images.githubusercontent.com/16321433/188022639-8a42c0d2-14e7-47d6-836e-2b0122ffd1da.png)

As the tree implies, there is probably space for small size dragonflies, and there is definitely space for a mega dragonfly that follows more the generally intended gameplay of the dragonflies, which is to be ungodly fast harassers that you can probably squash with a few good hits, but larger and more dangerous for late game survivors.

I'd add as a final note that while it should reflect it is two mega variant dragonflies in some of its stats, the crippled and probably unwell state of the united couple should probably be less than the sum of its parts.

### Describe alternatives you have considered.

Keep this mega variant which makes no sense, has obviously broken and nonsensical stats, and keep them as the terrors of the late game wilderness.

**Comment by Venera3** [comment]
100 speed and `STUMBLES` means you can outwalk them unless you purposefully hit every rose bush on the way.

If you have a better way to show "a lot of the mass on this isn't actually important, so hitting it does nothing" than no armor and a deep HP pool I'm open to suggestions.

Turning them into a random offshoot instead of a sure progression is a good idea.

The cut portion of the bump damage could get toned down, along with their melee skill.

>A devcord discussion about high tier mutants generally being broken unequivocally asserted that fused dragonflies are OBVIOUSLY the worst offender.

This is both irrelevant and a tad too sensationalist for an issue.

**Comment by sadenar** [comment]
I had missed the stumble flag, it does make more sense now.

The HP pool makes sense even though I figure that even while representing this, 1100 is still excessive.

I'd say that it should be good for it to not be completely defenseless, but the cut could sure be turned slightly down, and this monster should probably be focused on its egg laying gimmick.

Aside from that, Karol told me that a "small" and giant naiad turning respectfully into a small dragonfly and giant dragonfly would be excessive, is that a feeling shared by others?

Sorry about the sensationalism though, I mostly wrote this issue so it wouldn't just remain as messages lost in the wind in the devcord.

**Comment by Venera3** [comment]
Adding too many samey critters presents a readability issue, especially since a "small" naiad is anything but. I could see a simple 
`dragonfly->giant dragonfly -> (chance of) fused -> eggs -> giant naiad -> giant dragonfly` progression to show the species stabilizing in a new form as the game goes on, with a relatively early mapgen spawn start on naiads to show non-fused forms' offscreen reproduction. It'll leave early waterways relatively safe, but it would be consistent flavor-wise.

You're good, but I recommend reading the PRs adding monsters you find issue with, it usually clears up some confusion and helps differentiate oversights from compromises.

**Comment by Zireael07** [comment]
#65144 seems to be a recent duplicate
