### ISSUE TITLE
Issue when skinning animal corpses to get pelt

### ISSUE THREAD

**Issue by Spacer-1970** [CleverRaven/Cataclysm-DDA#60664]
### Describe the bug

When you skin an animal (e.g a wolf or a moose), with a butchering rack and butchering kit with a high survival skill like lv.6, it says "You fail to harvest: raw pelt" and then immediately says "The corpse is challenging to skin, but you get a good hide from it." or something of the kind but without getting the pelt/hide.

### Steps to reproduce

1.Spawn a butchering rack and a butchering kit using debug mode.
2.Increase your character's survival skill to 6 and above.
3.Spawn in an animal like a wolf or a moose and kill it.
4.Skin the animal corpse using the butchering rack and kit.

### Expected behavior

I expected that the message for harvesting the hide properly would not appear when you have failed to skin the corpse and to increase the chances of getting the pelt/hide because when i skin multiple animal corpses with high survival skill, i fail to get the pelt.

### Screenshots

![Screenshot (292)](https://user-images.githubusercontent.com/92626947/188009928-537e579b-77aa-41ee-a7dd-362517c9d79a.png)
![Screenshot (293)](https://user-images.githubusercontent.com/92626947/188009995-33f61828-be46-420b-a2d0-b534af7cab0b.png)
![Screenshot (294)](https://user-images.githubusercontent.com/92626947/188010093-7a05fdb2-ad43-4dae-bdd9-c353369f891b.png)
![Screenshot (295)](https://user-images.githubusercontent.com/92626947/188010270-2d297529-9d05-4b71-a337-ee7f9021dcf5.png)

### Versions and configuration

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/9473278/debug.log)

### Additional context

[user-default-mods.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/9473313/user-default-mods.txt)

**Comment by descan** [comment]
It's my understanding that pulped corpses do not yield hides or pelts. If that is the case and not me misunderstanding it, then that information should be displayed in the log; "This corpse is too mangled to get a good hide from," rather than the incorrect success message. This would have the added benefit of cluing in players to the idea that pulped corpses can't be skinned - at present, it's not something clearly presented to the player at any point (as evidenced by the fact that I'm not, in fact, sure it IS fact. Factually.)

**Comment by Spacer-1970** [comment]
Yeah, actually when I skin the corpse when it is not pulped, I actually get hides from them. So, yeah I do agree with you @descan  that they should add a message that the corpse is too damaged from pulping to get hide from it to actually give some sort of hint to the player that they should not pulp the corpse if they want hides from them.

**Comment by ChromePoptart** [comment]
> It's my understanding that pulped corpses do not yield hides or pelts.

Huh, well that explains why I got complete failures when trying to skin three Kevlar zombies and one Kevlar hulk with a butchering kit, large plastic sheet, and survival skill of 8.  I thought that it must have been a bug (given the log message implying success) to utterly fail four times in a row after succeeding with other Kevlar zombie corpses nearby -- it must have just been that I had pulped the former four corpses!

I would absolutely agree that the game should display something like 
> "This corpse is too mangled to get a good hide from,"

instead of "The corpse is challenging to skin, but you get a good hide from it."  I was quite confused and frustrated when the above happened to me!
