### ISSUE TITLE
Missing encumbrance warning in item layering menu

### ISSUE THREAD

**Issue by sethsimon** [CleverRaven/Cataclysm-DDA#60693]
### Describe the bug

When wearing a sheath (strapped layer) inside your knee pads (outer layer), even though the encumbrance penalty is applied properly, neither item is highlighted yellow in the item layering menu (`+`) and neither item shows the warning message in the middle column (I would expect it to say something like `wearing your knee pads outside your sheath is adding encumbrance there`).

Layered correctly: 
![cata-layer0](https://user-images.githubusercontent.com/16765166/188218993-c77ed968-c43e-43e8-9487-99985113c54a.png)

Mislayered (sheath selected): 
![cata-layer1](https://user-images.githubusercontent.com/16765166/188219041-6785a165-913c-42b3-81a0-1d7b07b55ae5.png)

Mislayered (knee pads selected):
![cata-layer2](https://user-images.githubusercontent.com/16765166/188219088-806c425f-1e14-4436-9a54-70206bd8aa51.png)

### Steps to reproduce

1. Make a new character.
2. Remove all clothing from your legs.
3. Wear a sheath and knee pads.
4. Observe no penalty when the sheath is worn on the outside.
5. Observe a penalty, but no highlighting or explanation, when the sheath is worn on the inside. 

### Expected behavior

Whenever there's an extra encumbrance penalty, I expect the relevant items to be highlighted yellow in the left column, and the reason described in the middle column.

### Versions and configuration

Linux, last commit is cb944bfe7b5bfbf08296133b7014f412d43d3bbf.

### Additional context

Issue #57888 is also be related as it also deals with layer conflicts.

**Comment by ZeroInternalReflection** [comment]
I can confirm this behaviour in up-to-date experimental.  A sheath below knee pads gives 2 extra encumbrance.  However, I'd call it a bug in the encumbrance calculation rather than a bug in the layering UI.  If you look at the body status menu (`@`-`s`), the knee pads cover only the knees, and the sheath covers only the hip.
![Right_hip--Sheath](https://user-images.githubusercontent.com/89038572/188250937-15ff5f46-82ab-47c0-9e8c-a25487ce365f.png)
![Right_knee--Pads](https://user-images.githubusercontent.com/89038572/188250939-a2095c88-9175-48fa-9aca-c00e34d9fe9e.png)

My best guess right now is that somewhere in the encumbrance calculation code it loses track of subparts and sees a conflict where there isn't one, whereas the layering UI only flags a problem if it sees a subpart conflict.
