### ISSUE TITLE
[Xedra Evolved] Studying spells increases a phantom skill of "nothing"

### ISSUE THREAD

**Issue by TheShadowFerret** [CleverRaven/Cataclysm-DDA#60790]
### Describe the bug

A skill is not set for Xedra Evolved's spells, which generates a phantom skill of "nothing" that does the same function as Magiclysm's spellcraft but cannot be viewed outside of when its level changes.

### Steps to reproduce

1. Spawn in a XE item that teaches a spell, such as ray diagrams.
2. Read until you would level ~~spellcraft~~ whatever XE's equivalent is supposed to be.
3. You learned nothing, literally!

### Expected behavior

~~Not being insulted by the log~~
Levelling a real skill I can view the level of without being in the process of increasing its level.

### Screenshots

![image](https://user-images.githubusercontent.com/99621099/188498365-4911cc53-d184-492e-8ed8-b58e2d9ff463.png)
~While I was reading ray diagrams

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22000.918 (21H2)
- Game Version: 3bfee5a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Xedra Evolved [xedra_evolved]
]

**Comment by Maleclypse** [comment]
Blerg that should all be `"deduction"`

**Comment by MrDraMaster** [comment]
I think this might have already been fixed by something?

I was trying to see whether I read magic.cpp & the JSONs right that you can define the associated skill for each spell (defaulting to spellcraft, of course), so I rolled a default mods + Xedra world, gave myself the "glass dagger paperweight", learned its "Dream Dagger" spell and then read some more, seeing this in my log:
![grafik](https://user-images.githubusercontent.com/37799858/217656020-1571ae71-2077-41f4-bbcc-58187d8f107b.png)

so "reading" the artifact leveled my deduction, not "nothing"
(and the skill did indeed rise to 4 according to @ and I could confirm that Dream Dagger's failure chance was correllated with my deduction level)

experimental version c8bebe2dc0da2e842d6828299680bb0f1a8caeba
