### ISSUE TITLE
Increase amount of craftables in chemistry and fix recipes

### ISSUE THREAD

**Issue by borsek** [CleverRaven/Cataclysm-DDA#60803]
### Is your feature request related to a problem? Please describe.

Currently the state of chemistry crafts in CDDA is somewhat lacking:
- We can craft dynamite without salt or sand which are needed stabilizers for the nitroglycerin, so it doesn't explode in your face.
- we can't craft smokeless gunpowder, which is a combination of nitroglycerine and nitrocellulose, using a solvent to shape it (ether, toluene, acetone, etc.)
- the HMTD craft with citric acid only produces 2 products (compared to 200 with acetic acid), it is an absolute waste, and citric acid is only a catalyst, so it should not realistically impact yield much, only the time needed.
- we have toluene and the nitration mix acids, yet we can't make (MNT/DNT/)TNT.
- we have RDX, yet can't make C1 (similar to C4, but doesn't use advanced plastifiers, only nitrocellulose). Could do as 'improvised military explosives'.
- a lot of recipes requiring liquid ammonia should only require ammonia solution (hexamine, lead azide is completely nonsensical here - would need HN3 not NH3, liquid fertilizer, etc.). If nothing else, aqueous ammonia should be able to be dried with CaO (quicklime), producing slaked lime and liquid ammonia (and maybe water if we go that far).
- extracting ammonium nitrate from commercial fertilizer is bonkers. We have ammonium nitrate pellets, and ammonium nitrate. Which are the same thing, just that pellets can't be used in certain recipes. Converting between them takes forever for no real reason.
- making ANFO (ammonium nitrate fuel oil) takes too long. It's literally pouring an oil over AN and mixing well. It takes 5 mins per liter of the mass, less with a concrete mixer or similar tool and larger batches. 5 min for 5ml volume of the stuff is absolutely bonkers. 

I haven't combed through every nonsensical recipe, be it time or ingredients, but it irks me. So much could be done, we have so many chemicals and locations which provide all the tools necessary for complex chemical synthesis, yet we can do less (and slower) than a crackhead in an RV in the Nevada desert.

Are any of these as they are for some balancing purposes, or did no one get around to fixing/changing them?

### Solution you would like.

Fixed and expanded recipes.

### Describe alternatives you have considered.

Focusing on life and work instead of CDDA.

### Additional context

Can help, am chemist.

**Comment by Terrorforge** [comment]
It's mostly just that very few of us have the expertise. The only reason you're not finding anhydrous ammonia in cleaning cupboards any more is that a different chemist(try nerd?) had the same reaction and went berserk on the files. But as you've noticed, there's still much to do.

It is mostly .json work, so you could probably do a lot of it yourself if you wanted to. Check out [CONTRIBUTING.md](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/CONTRIBUTING.md) for more on that

But if you poke your head into the Discord, or maybe just get lucky with a passing dev spotting this, I'm sure you can find someone who's willing to work on the code side of things if you can provide the necessary expertise to come up with and balance the recipes correctly.

**Comment by borsek** [comment]
Sounds good, I'm not much of a coder, but I've messed with .json data on my end already (added the ASRG as a vehicle power source for my 30-ton... tank?). It'll take me a bit to get into github PR/editing, but I'd gladly add to them myself, just don't want to step on any toes or work on stuff that is in the middle of an overhaul.

Should probably join the discord too, aye.

**Comment by robotic-gamer** [comment]
I have a few suggestions myself: 
- salicylic acid found in willow bark can be converted to phenol by simple dry distillation
- gypsum (CaSO4) found underground or in walls as drywall, can be converted to sulfuric acid by adding hydrochloric acid.
- grinding up eggshells into limestone analog
- guncotton from cotton patches and nitric acid
- nitric acid via running air though an electric arc (Birkeland–Eyde process)
- amphetamine production (from benzene, glycerol, hydrochloric acid, and ammonia) plus various catalysts 
- cheap knockoff cinnamon by mixing flour and Cinnamaldehyde (can be made from toluene and ethanol)
- benzene from phenol and a reactive meatal (aluminum, magnesium etc.)
- hydrogen peroxide from glowsticks
- white phosphorus from bonemeal and charcoal (great potential in incendiary weapons)
- red phosphorus by heating white phosphorus
- phosphoric acid from white phosphorus
- hydrogen peroxide from electrolysis of sulfuric acid (and a small amount of phosphoric acid (stabilizer))
- chloral hydrate (sedative) (from ethanol and hydrochloric acid)
- chloralose (acts like a Barbiturate apperently) (from chloral hydrate and sugar)
- grinding up poppys to be smoked like opium
- solvents as a drug (like drinking alcohol but worse for your health and more additive)
- latex from dandelion
- APEX as a primer for making bullets
- turpentine as an alternative to gasoline or diesel in making napalm
- iodine by distilling commercial salt (not "natural" salt)
- iodine by distilling sweetbread (thyroid glands) (possible to use zombies or mutants as a source)
- melatonin from brains
- epinephrine from adrenal glands (kidneys)
- ammonia solution from distilling protein rich organic material
- baking soda by allowing lye to absorb CO2 from the air before drying
- potassium chlorate (good oxidizer) (from bleach, hydrochloric acid and potassium hydroxide)
- potassium chlorate as byproduct from grinding matches
- replace red phosphorus with potassium chlorate in explosive recipes
- hydrochloric acid via distillation of Dicopper chloride trihydroxide (can be made very slowly by allowing copper to corrode in salt water)
- hydrochloric acid by burning PVC plastic
- a makeshift distiller that is a tool that just gives 1 distilling, (could just be made out of clay and some sort metal pipe, (pipe, copper tubing etc.) idea is to just make a clay pot with a pipe sticking out of it)
- an alcohol brewing recipe that just try's to make ethanol without any regard to taste
- a recipe to make methylated spirits from any weak alcohol, rather than just moonshine
- creating artificial crude oil from wood or coal via Fischer–Tropsch process (can be done inefficiently at 1 atm)
- refining artificial crude oil
- extended gasoline made by mixing gasoline with turpentine and or ethanol
- improvised gasoline by mixing a benzene type compound (benzene, toluene, a trimethylbenzene, etc) with a low amount of something relatively volatile (ethanol, acetone, diethyl ether, methanol, etc)

**Comment by Daved27hundred** [comment]
I've got some coding knowhow and I'm interested in helping, specifically with chemicals that have little to no use ingame. Phenol, acrymalide, toluene and nickel powder all do nothing (though those last two are used to make sedatives, but nothing else) and I was looking for something I could do with them. My chemistry knowledge is too basic to know how to apply them, so I was wondering if you could lend a hand in that department.

**Comment by kevingranade** [comment]
The things outlined in the topic post seem reasonable for the most part (note that "making nitrocellulose" and "making nitrocellulise you can use to reload a firearm cartridge and not expect bad things to happen" are two different things).

However,  this is what is referred to as an omnibus issue,  which causes problems in the future if/when parts of the issue start being implemented. Issues need to work toward a concrete and achievable goal, not list disparate content additions. As you can see in the comments,  this kind of issue has a tendency to grow over time instead of being resolved. 

Feel free to open individual targeted issues covering the topics you mentioned here.
