### ISSUE TITLE
Using (a)ctivate while the item used is in a spillable container causes the game to hang indefinitely

### ISSUE THREAD

**Issue by Plaidstone** [CleverRaven/Cataclysm-DDA#60847]
### Describe the bug

As above. Initially had the issue when starting fires with a mini lighter inside a steel pan, but also tested with the flashlight function on a smartphone, and with the item stored in a regular or stock pot, same results. Obviously this isn't exhaustive testing, but it's not hard to test further (I'm just lazy and tired). Tested on both an existing and a fresh character/world, the former of which is included (I don't know what to include, so I just yanked the whole world out of the 'saves' folder).
[Loose River - Copy.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9523652/Loose.River.-.Copy.zip)

### Steps to reproduce

1. Make a fresh character
2. Debug spawn a smartphone and a spillable container (e.g. a pot or pan)
3. Place the smartphone into the spillable container
4. Activate the smartphone's flashlight app

### Expected behavior

I expected the items to function normally, and not crash the game. Instead, they crashed the game.

### Versions and configuration

Windows 10
Experimental version b5cebce
Tiles (a version of UndeadPeople)
English
Reproduced on a default world (no_npc_food, no_fungal_growth, package_bionic_professions)

### Additional context

As a side note, I discovered this because a steel pan was full of items _while stored in my toolbelt_, which I don't think is supposed to happen. I think autopickup was the culprit, but you can force this situation by storing a held spillable container via the (w)ield menu while it contains items.

**Comment by EIIKaO** [comment]
This hang-up is caused by Infinity loop in `handle_liquid_or_spill`
https://github.com/CleverRaven/Cataclysm-DDA/blob/b1fb6f24448b26be57681212078e725a842f7fd0/src/avatar_action.cpp#L1180

> As a side note, I discovered this because **a steel pan was full of items while stored in my toolbelt, which I don't think is supposed to happen. I think autopickup was the culprit**, 

I agree. May need a different kind of fixes.

> but you can force this situation by storing a held spillable container via the (w)ield menu while it contains items.

This one is relatively easy to occur in usually game play,  reproduce easily and can be fixed now.

The next problem is which solution is better wheter the activated item would stay in their original spillable container or spill out( if that item can be contained in another container, it will be contained; if not, it will be dropped ). In my opinion, the latter should be the expected behavior.
