### ISSUE TITLE
Hub 01 modular defense system coverage design flaw

### ISSUE THREAD

**Issue by AJimmyU** [CleverRaven/Cataclysm-DDA#60855]
### Is your feature request related to a problem? Please describe.

Hub 01 modular defense system with soldier mantle and soldier skirt has a large "hole" on the stomach despite heavily protecting other parts of the body. Problem is not the carrier system itself, but rather the attachments not covering the lower torso making the suit grant top tier protection for all parts except for a 40% lower torso "window", where only the carrier system provides token protection.

What it looks like now, slight exaggeration:

https://img2.wikia.nocookie.net/__cb20130112202556/deadliestfiction/images/8/85/DOOMGuy.png

### Solution you would like.

I would like Hub 01 to close up the abs window so I don't get shot in my guts.

### Describe alternatives you have considered.

Having intentional holes in a nanoprinted combat armor.

**Comment by casswedson** [comment]
> Mantle:
95 on upper torso and shoulders only lacking coverage around the armpits
85 on upper arms the under arms would be partially unprotected
60 on lower torso the sides and towards the waist would be open so that you could still bend freely.

from #53871 https://github.com/CleverRaven/Cataclysm-DDA/pull/53871#issuecomment-1002713472 absolutely intended, I would imagine rooted in a deeper understanding of irl armor than mine
