### ISSUE TITLE
CBM power inconsistencies between generation and storage

### ISSUE THREAD

**Issue by potatoforscience** [CleverRaven/Cataclysm-DDA#60869]
### Describe the bug

Fully refilling the battery system CBM takes 2000 kJ of power.  Fully draining the battery system CBM produces 2 kJ of power. 

### Steps to reproduce

1.  Install a Power Storage CBM and Battery System CBM
2.  Refill the Battery System
3. Empty the stored 100 kJ from the Power Storage CBM
4.  Turn on the Battery System CBM and wait for it to empty.

### Expected behavior

2000 kJ should charge 2000 kJ

### Versions and configuration

- OS: Windows
    - OS Version: 6.1 7601
- Game Version: b1fb6f2 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Useful Helicopters Experimental [useful_helicopters]
]

**Comment by Drew4484** [comment]
Possibly related to #60613.

**Comment by UnicodeTreason** [comment]
Can confirm this behaviour in my existing save. This WAS working fine a few days ago.

1: Battery System has no Fuel
![1](https://user-images.githubusercontent.com/14937219/189280579-55ba0a8f-47db-44cb-8c07-d44a90a65587.png)
2: Refill with 63kJ of "Fuel"
![2](https://user-images.githubusercontent.com/14937219/189280632-1dbb3301-5953-4de9-990a-f809bb94572f.png)
3: Turn on Battery System to refill Bionic Power
![3](https://user-images.githubusercontent.com/14937219/189280644-ca05ed80-9d16-4342-8a76-eeb4b6d973b0.png)
4: Get 43J instead of 43kJ
![4](https://user-images.githubusercontent.com/14937219/189280673-d5270ae7-a77c-4063-a30f-abb8395c39e4.png)
5: Sadness

**Comment by UnicodeTreason** [comment]
Not familiar with this codebase in the slightest, but I see a few "power" related PR's recently that may be related to root cause?

https://github.com/CleverRaven/Cataclysm-DDA/pull/60484
https://github.com/CleverRaven/Cataclysm-DDA/pull/60607

**Comment by UnicodeTreason** [comment]
@Hirmuolio Yeah that'll probably do it. Many thanks for jumping on it so fast.
