### ISSUE TITLE
Player built directional constructions have no "operating side"

### ISSUE THREAD

**Issue by Rustybuckets6601** [CleverRaven/Cataclysm-DDA#60934]
### Describe the bug

When you craft a window with curtains, a door with a peephole, or a reinforced window with shutters, or anything similar, there is no side you can stand from to actually open the window/curtains/peep through the peephole/use the shutters. Not sure if this has been an issue for a while, but it vastly limits base construction creativity.

### Steps to reproduce

1. craft a window frame, then window
2. attempt to open it

### Expected behavior

Crafting any directional construction should allow you to choose which direction is the "operation side", or at least automatically choose the side from where you're standing when you finish constructing it.

### Screenshots

![image](https://user-images.githubusercontent.com/41603426/189553266-53ec2ee2-0ba1-480f-a0b3-ef1f1a825980.png)

![image](https://user-images.githubusercontent.com/41603426/189553272-ac0c2ed1-8340-4f23-b649-b18966e83a1e.png)

![image](https://user-images.githubusercontent.com/41603426/189553276-a3f33eb1-bfd4-4088-8232-2bbd8a8d9137.png)

![image](https://user-images.githubusercontent.com/41603426/189553279-3830d1f3-2c76-4fe8-83e6-b542b3bfd93d.png)

![image](https://user-images.githubusercontent.com/41603426/189553282-6a518801-12b9-4b52-8bc3-677ddb7e15cb.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22000.856 (21H2)
- Game Version: b9c5366 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by ZeroInternalReflection** [comment]
If I remember correctly from testing on #58098, the issue is not that the construction doesn't have an "operating side", it's that the "operating side" is determined by the game trying to figure out which side is "inside".  A freestanding window with no adjacent walls/floor is treated as if all sides are "outside".
I think the first requirement for the "operating side" is that the tile on that side has a roof (i.e. has the "INDOOR" flag)

**Comment by Rustybuckets6601** [comment]
> If I remember correctly from testing on #58098, the issue is not that the construction doesn't have an "operating side", it's that the "operating side" is determined by the game trying to figure out which side is "inside". A freestanding window with no adjacent walls/floor is treated as if all sides are "outside". I think the first requirement for the "operating side" is that the tile on that side has a roof (i.e. has the "INDOOR" flag)

That's very strange, but I guess I'll keep this up because you should still have the option to choose which way to operate it from. Such as making a zombie zoo with shutters.

**Comment by mlange-42** [comment]
@ZeroInternalReflection is correct here, it depends on the tile your character stands on having the `INDOORS` flag.

The reason is probably that explicit facing of doors etc. would require much more effort when makeing mapgen stuff like houses. With the current solution, facing is determined automatically and consistently (as long as there are indoor tiles...).

#60666 is an attempt to let tileset artists make the facing (and operable side[s]) visible.

**Comment by Rustybuckets6601** [comment]
> @ZeroInternalReflection is correct here, it depends on the tile your character stands on having the `INDOORS` flag.
> 
> The reason is probably that explicit facing of doors etc. would require much more effort when makeing mapgen stuff like houses. With the current solution, facing is determined automatically and consistently (as long as there are indoor tiles...).
> 
> #60666 is an attempt to let tileset artists make the facing (and operable side[s]) visible.

Aw damn that's very true, I guess this isn't gonna get changed anytime soon. Thanks for your help fellas.
