### ISSUE TITLE
Distinction between tamed and trained animals 

### ISSUE THREAD

**Issue by ProfaneServitor** [CleverRaven/Cataclysm-DDA#60951]
### Is your feature request related to a problem? Please describe.

Tamed animals are animals that accept presence of humans, while trained animals can do commands like guard and attack. Most friendly animals act like trained combat animals, which is unrealistic and often undesireable. For example, usually you don't want chicken or cats to attack zombies.

### Solution you would like.

A "tame" tag for animals. It would mean that it ignores humans, and treats monsters normally.

### Describe alternatives you have considered.

Animal training system, but I'm not sure how easy or practical it would be to implement.

**Comment by catdach** [comment]
> A "tame" tag for animals. It would mean that it ignores humans, and treats monsters normally.

Maybe I just haven't played around enough with animals, but as far as I can tell; most animals already kinda do that by default. most animals just ignore you unless you get too close, in which case they either become hostile, or run away from you. 

It seems like they treat monsters the same regardless of if they're "tamed" or not. Either attack on sight, or run away on sight. Which seems pretty realistic for untrained animals, considering how much of dog training is "no, don't try to eat the mail man/don't bark at everything that moves"

The current "_taming_" system in the game isn't very deep, you literally just give them food and they'll follow you around. Which really isn't taming nor training at all tbh, but I guess that _is_ what happens when you give animals food.

The idea of a deeper animal training/taming/domestication system has been thrown around few times. It's something that's desired, the problems that I notice are:

1. It would take **alot** of work to implement.
2. People are just busy with other things right now.
3. It probably wont be finished before the next stable, and would probably fall under the current feature freeze.
4. Most players don't seem to have long enough playthroughs to get most of the potential benefits of a realistic animal training system.
