### ISSUE TITLE
Increase solar panel efficiency to more realistic levels.

### ISSUE THREAD

**Issue by TieSKey** [CleverRaven/Cataclysm-DDA#61079]
### Is your feature request related to a problem? Please describe.

This merge: Use Sun irradiance for solar panels #59179

Reduced solar panel output to about half or even less. This change, while a realistic simulation, makes solar vehicles go from inconvenient to almost unusable. 
Default solar vehicles are kind of a joke since 4 regular solar panels won't generate enough power on a summer day to drive to your local grocery store and back.

Observing the numbers:
Regular panels are rated as 50W and advanced as 100W, if we take an irradiance of 1000 as stated in the merge, that's 5% and 10% efficiency cells. A bit on the lower side, specially considering the game tech level.
(Hours of exposure are now more or less correctly handled by the new code.)

### Solution you would like.

Raise efficiency of solar panels.

If we want "current commercial real life" levels, going with 10% for regular and 15% for advanced sounds about right, maybe even a little conservative. This change would almost restore solar vehicle viability to pre-merge levels which are not that great anyway.

If we want a "slightly more advanced" version, going for 15% for regular and 30% for advanced should be reasonable considering the theoretical limits and even current real life tech (really pricy but achievable).

### Describe alternatives you have considered.

Nothing since this is actually more about solar cell efficiency, the solar car is just an example.

But if we want to talk about solar cars. An alternative could be having "chargers" in cities with "swappable batteries" connected to large solar arrays in roofs. Either in their own buildings or as part of some of the bigger houses.

**Comment by actually-a-cat** [comment]
Something to note: vehicle tiles are, conceptually, not the same size as terrain tiles. (Otherwise every car in the game is *humongous*!) I don't think there is an exact standard for that, but they're typically assumed to be closer to 0.5x0.5 m than to 1x1 m. So, while I'm not saying that current values for solar panels are perfect, assuming that a panel is 1m<sup>2</sup> is not a useful starting point. (An idea that has been bouncing around is to make solar panel appliances more productive, but require more than one solar panel item to set up, since their tiles would fit more panel.)

**Comment by TieSKey** [comment]
> Something to note: vehicle tiles are, conceptually, not the same size as terrain tiles. (Otherwise every car in the game is _humongous_!) I don't think there is an exact standard for that, but they're typically assumed to be closer to 0.5x0.5 m than to 1x1 m. So, while I'm not saying that current values for solar panels are perfect, assuming that a panel is 1m2 is not a useful starting point. (An idea that has been bouncing around is to make solar panel appliances more productive, but require more than one solar panel item to set up, since their tiles would fit more panel.)

Mmmm that's a very valid point. 

I guess the steps required to adjust this would be:
* Decide a tech level for solar cells in the game
* Set an efficiency according to that tech level
* Get consensus on average tile size
* Adjust power output of panels (size*efficiency*irradiance)
* Check impact on things depending on solar power: appliances, cars, irradiation plants? (do they use solar power or just some hidden infinite source?)
* Re adjust power output of panels to avoid "breaking" any of the above or introduce new types of panels

**Comment by anothersimulacrum** [comment]
It is pretty safe to assume car panels are on the .5x.5-ish meter scale, and thus that appliance panels could use multiple (4) per a single tile.

**Comment by PatrikLundell** [comment]
If that's the case you'd need to make the panels mounted on roof tops into a different type from those mounted on vehicles, with the rooftop ones being the appliance type and the vehicle ones being the vehicle type. Presumably there'd also be recipes for the conversion of vehicle panels to appliance ones (not sure the conversion would work the other way in real life, but so what...).

**Comment by kevingranade** [comment]
> This change, while a realistic simulation, makes solar vehicles go from inconvenient to almost unusable.

This is pretty much working as intended.

Regarding your steps:
Tech level is now,  so maybe 15%/18% efficiency.
Fixed installation panel size is 1m^2, car panel size is .25m^2
Probably the best target to chase down is Massachusetts' average insolation
`Boston has an average monthly Global Horizontal Irradiance (GHI) of 3.84 kilowatt hours per square meter per day (kWh/m2/day)`
https://www.solarenergylocal.com/states/massachusetts/boston/#positioning

The thing is, I strongly suspect this would actually be a nerf.

**Comment by Tharn** [comment]
In real-world, our efficiency is reaching around 20% for poly and 20-30% (!) for mono cells, currently. So 5%/10% as OP mentioned, or 15%/18% as kevingranade mentioned, are both noticeably less. It's my understanding that advanced solar panels/cells _are_ mono crystal cells.

However, looking at commercial solar panel rated wattages for m² sizes suggests that 100W for 0,25m² is on the generous side.

I'm still not convinced that it would be a nerf. We may be close to realistic, but better efficiency could be used. Where's the fun in prohibiting a playstyle instead of just making it difficult? It's my understanding that the game devs don't want to see any "easy outs" and free energy - fair enough - but with sufficient investment in time, work and materials the player should still feel rewarded. Biodiesel is effectively endless too and farming is much more of a "binary winbutton" as stuff basically grows itself.
