### ISSUE TITLE
Cannot use equipment on bike rack-mounted parasite craft

### ISSUE THREAD

**Issue by DPavonis** [CleverRaven/Cataclysm-DDA#61092]
### Describe the bug

In the past, it was possible for players to mount things like turrets, headlights and other vehicle-appliances onto individual frames, then mount them to a parent vehicle as ersatz modular equipment, but of late this seems to no longer be the case.

I'll admit I'm probably abusing the bike rack system in ways that were probably never intended to be used, so I'm genuinely unsure if what I'm seeing is a bug, or working-as-intended. If the latter, feel free to close this issue.

### Steps to reproduce

1.) Mount a parasite craft equipped with a turret and turret control unit, and/or headlight onto a parent vehicle
1a.) Set turret to automatic
2.) Attempt to fire turret or enable headlight
3.) Be sad as you find you can't

### Expected behavior

That turrets mounted on parasite craft be able to fire, headlights work, and in general anything mounted on a parasite craft work the same as equipment on the parent craft.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2006 (21H2)
- Game Version: a3c6a29 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

Attached is a save containing three vehicles, one intended as a stand-in for a parent vehicle, and two different parasite craft, one equipped with a projectile-based turret and one equipped with a laser-based turret ready to be attached to test.

[Test World.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9593158/Test.World.zip)

**Comment by PatrikLundell** [comment]
A real world bike rack provides just mechanical attachment, but no connection or integration of electrical systems.

Trailers (at least over some size and in some countries) have to be mechanically attached as well as electrically in order for tail and brake lights to function. However, the game doesn't have any functionality for towing trailers (and regular towing is, again, just a mechanical connection).

**Comment by irwiss** [comment]
When was 'the past'? 4 years ago [racked parts, including turrets were made 'unavailable' and removed from parts cache](https://github.com/CleverRaven/Cataclysm-DDA/commit/33f8218489cdaea8ab412f022af79fe95d594429#diff-25c559834fc05e15cc83980e2a74a183f49cfbe404945f8b0a9d29fb8f713039R3893-R3895) and it looks to be by design by mlangsdorf https://github.com/CleverRaven/Cataclysm-DDA/pull/26499

I don't have a strong opinion either way, although I think racked stuff like turrets not being available is more correct.

**Comment by Jarewill** [comment]
Yeah, bike racks don't have any functionality like that in real life.
However a new part could maybe be introduced that allows such connection between vehicles like with trailers.

Having detachable cargo trailers was something I wanted in the game, but the bike rack system didn't allow for 2-tile and wider vehicles to be attached and the towing system wasn't the best last I tried.

So a plug and socket vehicle parts could be introduced, a socket for the car and a plug for the trailer to connect them together.
I am saying "could be" but I honestly don't know how difficult or even feasible this could be.

**Comment by PatrikLundell** [comment]
Depending on when you last tried towing, it might have been improved somewhat. I find you can reliably tow at a speed of 12 km/h as long as you don't have to do too fast turning. Faster than that and you tend to get rear-ended occasionally when you turn or gets slowed down by difficult terrain (resulting in damage to both vehicles, in particular MCs hanging off a bike rack: I've scrapped two or three biked because of that). It can't tow over bridges, though.

I'd guess a trailer would require the implementation of a system that allows for a "joint" in the combined vehicle, and it would also have to cater for two different trajectories for the two segments, possibly pushing the pulling vehicle off course.

**Comment by kevingranade** [comment]
This is working as intended.  Racking vehicles is designed to allow carrying around small utility vehicles,  not making modular vehicle additions.
