### ISSUE TITLE
Mech weapons disappear on load

### ISSUE THREAD

**Issue by Maleclypse** [CleverRaven/Cataclysm-DDA#61175]
### Describe the bug

When you load a game after getting into a mech and saving you will find that it's built in weapon system is gone.

### Steps to reproduce

1. Make a character
2. Spawn the two mechs with weapons
3. Jump into one
4. See it's weapon system
5. save
6. quit and reload
7. Receive following error message ` DEBUG    : Couldn't find the bionic UID for the current bionic weapon.  You will need to reactivate it.

 FUNCTION : void Character::load(const JsonObject&)
 FILE     : src/savegame_json.cpp
 LINE     : 1159
 VERSION  : 25fd53c
`
8. See empty space where mech weapon once was.
9. repeat

### Expected behavior

The guns don't disappear.

### Screenshots

![mechs](https://user-images.githubusercontent.com/54345792/191409542-33bc1a0f-ff8a-410b-a5ff-a637c0bbcf76.png)
Scout
![cmes laser cannon](https://user-images.githubusercontent.com/54345792/191409545-fa9c2131-d6b6-49e4-98b1-d670037cfb2e.png)
![cmes laser cannon gone](https://user-images.githubusercontent.com/54345792/191409543-db99cb57-c25d-40ea-a414-a80cee82e671.png)
Marksmmen 

![marksman weapon](https://user-images.githubusercontent.com/54345792/191409541-94118f83-d8ce-4b92-9b5b-cbfb99e10f0a.png)
![marksman gone](https://user-images.githubusercontent.com/54345792/191409546-f250f5eb-9f4c-4718-82b3-b68a7eb4ef05.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.2006 (21H1)
- Game Version: 25fd53c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

Screenshots come from a friend who experienced the bug, and I've confirmed it.

**Comment by akrieger** [comment]
This feels like it could be my fault. Is there any trickery to spawning a mech / what debug spawn menu do I need to go find it?

**Comment by Maleclypse** [comment]
Spawn monster, search for Mech, only the grunt and specter have weapons I believe.

**Comment by akrieger** [comment]
Dug into it enough to verify it happens on builds before #50143 so it's at least not my fault the way I was thinking.

**Comment by Maleclypse** [comment]
Well that’s good to know at least.

**Comment by akrieger** [comment]
Not trying to be like 'not my problem byeee' but I don't have time to take on fixes other than things I directly broke from that PR and want to indicate to people that they should feel free to investigate this without worry.

**Comment by EIIKaO** [comment]
I enjoy investigating and fixing small bugs, so I investigated the actual behavior of the program in past versions and the history of changes related of this issue.

The behavior of equipping MECH weapons when riding MECH worked since https://github.com/CleverRaven/Cataclysm-DDA/commit/a5b1baa77ad16df125aefbecc87001d40dad8a0f, and in there, the bug already happened( https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2022-05-02-0624 ).

Therefore, this may be due to a failure to identify Mech and bionic weapons in `src/savegame_json.cpp`.

```
    bool has_old_bionic_weapon = !is_using_bionic_weapon() && weapon &&
                                 weapon->has_flag( flag_NO_UNWIELD ) && !weapon->ethereal;
```

Here are my shortsighted solutions.
**a.** Create and add json flag ( like a "MECHANIC_WEAPON" ) to the item, insert code of checking on loading that flag has or not into `has_old_bionic_weapon`'s expression

**b.** Assign variables to MECH weapons ( such `mechwep.set_var( "MECHANIC_WEAPON", "true" );`  ) when riding( `void Character::mount_creature( monster &z )` ) and check them during loading.

These are easy to implement, but in my opinion, it would be preferable for someone with a long-term development vision regarding the mech series to come up with a more planned solution.

**Comment by EIIKaO** [comment]
This is just what I was hoping for, expert solution.

**Comment by Maleclypse** [comment]
Did this get fixed or is it waiting for someone to make use of the diff irwss posted?  Trying to determine if it should be closed.
