### ISSUE TITLE
Return autoturn on function of the power bionics

### ISSUE THREAD

**Issue by KHeket** [CleverRaven/Cataclysm-DDA#61197]
### Describe the bug

After https://github.com/CleverRaven/Cataclysm-DDA/pull/61049 ability to autoturn on of bionics like Cable Charger System or Battery System was deleted. There is some simular new function with "inactive" status of this bionics, but if you, for example, unplag and then plag cable to UPS or CAR again - Cable Charger System will turn off, and you will need to manualy turn it again from bionic menu, but before this update you just set percent at which this bionics will be turned on by itselfs, and you only needed to plug you cable into ups or car

### Steps to reproduce

Load any version before [Cataclysm-DDA experimental build 2022-09-21-1254](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2022-09-21-1254)
Make bionic character and enjoy comfort power system
Load [Cataclysm-DDA experimental build 2022-09-21-1254](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2022-09-21-1254) or later version - and see uncomfortable situation with a lot of unnecessary key pressing

### Expected behavior

I want to see comfortable bionic powering

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2006 (21H2)
- Game Version: 3327a22 [64-bit]
- Graphics Version: Tiles
- Game Language: Системный язык []
- Mods loaded: [
    Тёмные Дни Впереди [dda],
    Отключить потребности у НПС [no_npc_food],
    Без роста фунгалоидов [no_fungal_growth],
    Бионические профессии [package_bionic_professions]
]

**Comment by Fris0uman** [comment]
Maybe powergen bionic should not be togglable at all at this point, since they can be on without producing power there's no reason to turn them off and they should just be always on with no option to turn off.

**Comment by a-chancey** [comment]
> Maybe powergen bionic should not be togglable at all at this point, since they can be on without producing power there's no reason to turn them off and they should just be always on with no option to turn off.

Eh if i forget to unplug my cable charger from my ups and drain my battery because cable charger can't be turned off, i'd be pretty miffed when my gun refuses to fire. Or if my car battery died because i didn't have the gas to keep my car running overnight. There's a handful of reasons to turn them off and on manually - maybe i want to keep gasoline power in reserve for when i need to generate power *quickly*.

Especially metabolic interchange - that one needs to be able to be turned off so you don't burn 20,000 calories in a day.

**Comment by Fris0uman** [comment]
but the recent change is that they don't turn off but are inactive and don't do anything when they pass the off threshold or if your batteries are full

**Comment by a-chancey** [comment]
> but the recent change is that they don't turn off but are inactive and don't do anything when they pass the off threshold or if your batteries are full

Then I might need to make a bug report, cus it’s not working on a build from source that was pulled around 8am. My cable charger was on when I went to sleep, with power saving turned off, since I noticed auto start options were gone. I have metabolic interchange set up with power save to turn off at 50%. 

Cable charger turned off while sleeping with my internal climate control on (was sleeping in the car, didn’t want to put in earplugs so I had the car off). Woke up with 0J of bionic power, a connected jumper cable, and both it and my metabolic interchange were turned off. I had enough calories stored for metabolic, as I was able to turn it and my cable charger back on the moment I woke up. My car storage battery was still at 89%. 

So something is broken currently with them auto starting. 

on top of the bugs, this is currently taking control away from the player, which is a regression. I fail to see what was wrong with the auto start system, other than it wasn’t granular enough. I like the setup for smart engine controller- let me set up a toggle range for each with sliders. Different chargers recharge at different rates and have different availability of fuel - and the rate at which I want to use them is going to vary depending on the situation. Killing the last incandescent husk in an area as his EMP drains my power but I’m relatively safe is different than probability traveling into…fire, and not having enough reserve power to turn on thermal dissipation. In one, I’m fine with the battery or ethanol burner running, in the other, I’m all systems go.

**Comment by Hirmuolio** [comment]
Something weird with sleep. After sleeping (and presumably during sleeping) `veh->discharge_battery( 1 )` fails to discharge battery from the connected vehicle.
