### ISSUE TITLE
Remove "Pair of" for singular pair items

### ISSUE THREAD

**Issue by Sniper27IT** [CleverRaven/Cataclysm-DDA#61220]
### Is your feature request related to a problem? Please describe.

I think that having a lot of apparel using "pair of..." in their name when it's only a singular pair clutters the hud of many menus, like inventory or pick-up, unnecessarily. I think that it's already clear to the player when most apparel items are a pair, and the description menu clearly states if an item covers both pair of limbs.

### Solution you would like.

Simply remove "pair of..." from an item name when it's a singular pair, keep it for plural pairs.
Example:
"Pair of socks" -> "Socks"
"Pair of pants" -> "Pants"
When there's multiple pairs, keep it
"2 pairs of socks"

### Describe alternatives you have considered.

Nothing, leave it as it is. But i think that changing this greatly improves the readability of most menus.

### Additional context

I didn't check the git if this has been previously brought up, i apologize in case.

**Comment by PatrikLundell** [comment]
I agree it would help to find socks in the "s" section rather than realize you'd have to look at the "p" part of the list. However, skipping the "pair" part leads to confusion as to whether it's a single shoe or a single pair of shoes. Restoring "pair" to multiple pairs would make things worse, as you'd now have to look under both "s" and "p" to catch those blasted shoes based on the rather arbitrary condition of whether a single or multiple pairs happen to be present.

From a search perspective, I'd rather see "pairs of XXX" turn into "XXX (pair)", thus getting rid of the annoying "pairs" cluster of things. XXX would have to be in the plural form (e.g. "socks (pair)" and "3 socks (pair)").

**Comment by Sniper27IT** [comment]
> However, skipping the "pair" part leads to confusion as to whether it's a single shoe or a single pair of shoes.
Yeah, that one could be a problem, however, from a "gamification" perspective i think that most players, even new ones, expect that being a pair and not a singular item. Also, if you simply put "shoes" there's should be no problem realizing that it's actually a pair of shoes. Last, the new description snippet that shows the body parts affected by wearing that item are very helpful in this case.





>Restoring "pair" to multiple pairs would make things worse, as you'd now have to look under both "s" and "p" to catch those blasted shoes based on the rather arbitrary condition of whether a single or multiple pairs happen to be present.

This could be one issue; while there's should be no problems in the crafting menu, this thing could be annoying in other contexts like pick-up menu or inventory.

> From a search perspective, I'd rather see "pairs of XXX" turn into "XXX (pair)", thus getting rid of the annoying "pairs" cluster of things. XXX would have to be in the plural form (e.g. "socks (pair)" and "3 socks (pair)").
That's another potential way to deal with this. Even tho i'm not super fond of it, i admit that it could solve this with ease and give less clutter in many menus

**Comment by PatrikLundell** [comment]
I've played at least one game that treats shoes as individual items so one foot can have a shoe and the other not (or e.g. a foot rag). Also, the real world is full of mismatched socks...
