### ISSUE TITLE
NPC with nothing to give still says "Okay, here you go"

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#61268]
### Describe the bug

After persuading an NPC to give me an item, I get a popup saying they have nothing to give. However, they still proceed to the "Okay, here you go" dialogue.

### Steps to reproduce

1. Chat with an NPC with no items
2. Ask for some items
3. Succeed at a Persuade check
4. see "Soandso has nothing to give" popup
5. see "Okay, here you go" dialogue

### Expected behavior

Dialogue is replaced with something like "I would but I don't have anything."

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: ManjaroLinux; Description: Manjaro Linux; Release: 22.0.0; Codename: Sikaris; 
- Game Version: 0.F recent master branch
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by mamiral** [comment]
Hi,
im kinda working on this issue. Have a bit of a hard time since the debug build runs very slow.

1) I have confirmed that this bug exists and is easily reproducible. (Take a mission from NPC and ask for items.)
2) What i have figured out until now:
 - dialog 'trial roll' is successful and NPC is willing to give you an item before the actual check if NPC has anything to give happens and the pop-up msg is triggered at a too late stage in the code.
 - when the pop-up returns NPC thinks they gave you an item.
3) Looking for a place in the code to apply the fix.
