### ISSUE TITLE
activity suit: too good?

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#61335]
### Is your feature request related to a problem? Please describe.

It's been a fairly common sentiment at this point that the activity suit / hub01 enviro suit (activity suit being way more common) is practically mandatory for any character. It is very easy to obtain on day 1 and offers an insane amount of immunities - total protection from acid and shock (the two most deadly "secondary damage" types in the game), immunity to radiation, resistance to fire and immunity to fungal spores. On top of that it has very low encumbrance, only 3 on the nomex parts, yet has a reasonable 2mm Nomex with 100% coverage that makes it more or less the best normal-layer armor in the early game. Survivor kevlar jumpsuits can be a bit better purely defensively but they don't give you immunity to electricity and acid so they aren't even under consideration comparatively. It also uses no power whatsoever unlike the "hypertech" armors such as RM13 or Phase Immersion making it more or less the only reliable means of protection against electricity, and it can be repaired fairly easily through tailoring. The armor's only real weakness is that it is somewhat warm at 40 (which might not even be reasonable, given that the flame-resistant undersuit is also made of 2mm nomex and is itself only 5 warmth - 40 is warmer than a 3mm wetsuit for example)

### Solution you would like.

I don't have a solution, I just want to raise the question of whether the activity suit is too pushed. Nomex IRL is just really that good, being reasonably sturdy and resistant to acids, static discharge, radiation, and fire, so it's not like the activity suit is some kind of super material. But it's just so darn good that it completely homogenizes all armor choices to such an extent that you'd be mad to use anything else and I don't know if that's really healthy for gameplay.

**Comment by Nebnis** [comment]
I would be down to nerfing them if we get more options to give us protection for electricity and acidity. it really sucks that most of them are very emcumbering or extremely hard to craft/find

**Comment by Terrorforge** [comment]
Yeah, the problem with nerfing the activity suit is that it is, as you say, practically mandatory. I'm playing a mutant who can't wear one right now, and it's brutal.

My preferred solution is actually the one I laid out in #58087. The way I see it, the real problem is that you're forced to live in your activity suit 24/7 because there are always, _always_ going to be both acid and electrical zombies _everywhere_. If we rearranged zombie evolution so you could be reasonably sure that, for example, a power substation is going to have electrical zombies but no acid zombies, a lab will have acid but not electrical zombies, and a nursing home will have neither, we could nerf or even get rid of activity suits, because it wouldn't be such a problem that a hazmat suit or faraday mail is kind of awkward, because you'd only have to wear it when you actually needed to.

**Comment by arockperson** [comment]
I think the activity / anbc / whatever other similar things are just a very useful bandaid over the issue that is shock / acid zombies.

Without a 100% acid and elec protection armor, fighting a horde in melee makes taking damage inevitable. Which isn't necessarily a bad thing--but with activity suits in their current state it just means you might as well always wear one. They are so punishing without an activity suit--and so irrelevant with one.

In a perfect world, the player would have to think about how to take down electrical and acid zombies, and they would present an interesting tactical challenge. But currently I feel it's either "oh no they are gonna deal 25 damage to me and inflict tons of pain no matter what" or "they literally cannot hurt me at all because of my suit"

What if there were partial levels of electricity resistance? Taking half damage, or perhaps taking no damage and full stun, or no damage and full/half pain, etc. So you would have to think about taking shockers on but no longer are doomed to take significant damage.

**Comment by John-Candlebury** [comment]
I also think that the very simple way in which electric-acid-radiation protection work are the real problem here. Either you are wearing clothing that makes you fully immune to them or you are completely unprotected. 

Not sure there are problems with the suit stats themselves. especially considering that they degrade rather fast unless you are layering them under very protective clothing. They might also be slightly easy to successfully patch up.

**Comment by fairyarmadillo** [comment]
Acid has always been thematically weird. While chemicals like piranha solution and stuff do exist, most stable acids tend to be dangerous more becayse of acidosis, eye irritation/damage, and fumes. Skin burns are almost always going to be a secondary concern - potentially serious, but not immediately.

With that in mind, what if acid was more like:

1) Mild to severe damage over time on skin contact, but can readily be washed off
2) Causes acrid smoke wherever it burns organic material, blocking line of sight and burning the lungs if you don't have breath protection
3) Incrementally causes acidosis, which can be counteracted by drugs or naturally healed by washing off and leaving the acid. Acidosis would probably function similarly to hypovolemic shock in gameplay terms, though probably with a shorter half-life. There is also room for experimental drugs, bionics, and mutations which could manage acidosis
4) Rain could quickly wash it away and get rid of pools/puddles

If tuned right, this would make acid into less of a cartoon "the ground is hot lava" (though it could still puddle and get on your feet) and more of a thing that forces you to retreat and clean up if there's too much of it around. It might also make acid less comically dangerous to zombies, who currently melt very quickly to their own friendly fire.

Acidproof clothes could still obviate this, but they might be less necessary outside of situations which for one reason or another have a high concentration of acidic enemies, which could have the desired effect of making players more willing and able to use non-armor solutions outside of situations where it's reasonable/expected they'd be specificially suiting up for acid.

**Comment by PatrikLundell** [comment]
I agree with the opinion that it's a problem that all special attack zombies are everywhere, so you always have to wear protection against everything at all times, or suffer unreasonably.
If there was a way in which you could predict what kind of threats you would be up against it would be possible to have equipment tailored to counter that threat, ideally with none of them part of the "standard" set so the default outfit would not contain special protection, but you'd want to change your equipment when up against those specific threats. Special equipment would also confer significant drawbacks, such as encumbrance and heat (although that would be a benefit in the winter and in basement survival).

There is a small part that actually work about right, and that's breathing protection. Using it comes at a stamina cost, so you don't want to wear it most of the time, but it's sufficiently easy to equip and carry that you can have it with you at all times.

**Comment by Terrorforge** [comment]
For context, I want to lay out how (most) acid attacks work:

Firstly, they deal direct damage. This works like pretty much any other damage effect; armor has an acid resist value in exactly the same way it has bash resist. But this damage is universally very low. The activity suit only has _5_ acid armor, and that's enough to render you immune.

But then there's a second check against your environmental protection. If you fail this check, you get the "corroding" damage-over-time effect. This is what actually deals the vast majority of the damage, and the uniformly low env resist of armor that isn't explicitly for CBRN purposes is the main reason activity suits are so much better vs. acid.

I recently learned you can use a towel to wipe the acid off and stop the corroding, but I dunno how practical it is. The corroding effect doesn't last super long so I'm skeptical, but I'm gonna try it out.

(Shoutout to @Venera3 for digging this information up and explaining it to me when I was having trouble with my boots the other day)

> In a perfect world, the player would have to think about how to take down electrical and acid zombies, and they would present an interesting tactical challenge. But currently I feel it's either "oh no they are gonna deal 25 damage to me and inflict tons of pain no matter what" or "they literally cannot hurt me at all because of my suit"

That's kind of how everything works in this game, though. Acid and electricity are worse because they're ranged, but fundamentally you're never okay with taking a little bit of damage. Okay, sure, if you occasionally get impaled by a hunter or batted into a fence by a hulk it's not the end of the world, but as a rule you can't afford to get into a fight unless you're certain you'll be able to avoid 99% of the damage.

I suppose that could be part of the solution? You balance it so that run-of-the-mill acid zombies are stopped by the modest protection of e.g. a Kevlar jumpsuit, but then you have some sort of "acid hulk" equivalent that can punch through anything short of full Hazmat.

> What if there were partial levels of electricity resistance? Taking half damage, or perhaps taking no damage and full stun, or no damage and full/half pain, etc. So you would have to think about taking shockers on but no longer are doomed to take significant damage.

This was actually in the game for a hot second, but I believe it was axed on the grounds that that's not how electricity works.

**Comment by arockperson** [comment]
> That's kind of how everything works in this game, though

It's to a lesser extent with lots of armor (e.g., stuff without 100% coverage / stuff that doesn't fully absorb the attacks you would be dealing with),  but yeah. Along those lines, something that bothers me about how armor is the absurdly crucial breakpoint between "this attack can do 1 damage to me" and "this attack can never scratch me".

For example, with the right set of medieval armor you can spend an arbitrarily long amount of time surrounded by zombies without taking any damage. Get enough toast ems and mineral water and you could last years. Though I don't have any data to back it up, that on its face seems like a ludicrous amount of safety. Surely there is some amount of damage you would take from the force of their attacks even through the padding, and surely after hours of constant attacks the armor wouldn't be holding up perfectly.


This seems to me like a symptom of the game's model for armor and damage being far too inflexible: this attack deals 12 cutting damage, and if you have more than 12 cutting armor, then good for you.

**Comment by Terrorforge** [comment]
> For example, with the right set of medieval armor you can spend an arbitrarily long amount of time surrounded by zombies without taking any damage.

Not any more. There's a suffocation mechanic where if you're getting grabbed by multiple zombies, you start to take torso damage and eventually die as you're crushed by the sheer mass of rotting flesh.

Recent armor changes have also made it substantially harder to become effectively invulnerable. You just don't get 20/20/20 armor with 100% coverage any more. This makes active defense (blocking, dodging, killing/disabling) much more important, and those defenses fail once you run out of stamina and/or start taking damage.

> This seems to me like a symptom of the game's model for armor and damage being far too inflexible: this attack deals 12 cutting damage, and if you have more than 12 cutting armor, then good for you.

What that really comes down is the game's model of damage and injury being too simplistic. The entire concept of "hit points" is a pretty ridiculous way to measure injury to the human body, when you think about it.

There is a desire to move to a more dynamic "wounds" system. I don't know there's even a tentative design for it yet, but I would wager that in such a system the effect of wearing plate armor when mauled by a bear would be to downgrade the effect from "eviscerated" to "bruised" rather than just ignoring it completely.

**Comment by Venera3** [comment]
I don't think restricting special zombie spawns is an actionable solution - even without the ludonarrative problem of "why would blobby only do lightning around offline power sations" either the locations are irrelevant like power stations (so you don't have a reason to invest in protection) or mandatory like labs (so the problem persists, you just made cities even easier).

I think the problem is how fire-and-forget protective gear tends to be - you throw it on and you're golden forever, you don't and you're toast. My suggestion would be to draw out the acid/elec protection spectrum a bit so normal gear is not completely pointless and make the dedicated protective suits less of a sure thing - either make them 90% impervious at best or turn them either unrepairable or flimsy so there's an attritional component to longer fights. A torn hazmat suit is basically just dead weight, after all.

**Comment by Terrorforge** [comment]
There's already a pretty strong implication that set and setting affects zombie evolution. Swimmers turn into webbed zombies, "suggesting some kind of rapid evolutionary adaptation to water". Zombie technicians are found in industrial locations and exclusively evolve into shockers. Zombie soldiers integrate their kit into their bodies and become kevlar zombies. Gasoline zombies exist only near gas stations. Setting a zombie on fire gives it smoke powers.

I also don't see how it fails to solve the problem, because the problem is that it's always correct to wear the activity suit in every situation. Restricting the offending zombie types to certain locations would mean it was often correct to wear something else; problem solved.

Maybe it's also a problem that the only good solution to acid/electrical zombies negates them entirely, but as discussed that's kind of how all defense works in this game as an inevitable result of the vast difference between taking 1 damage and taking 0 damage. Any solution where protection isn't absolute risks being incredibly brutal on players, especially after a bit of evolution and especially for melee characters. Maybe if you implement it more like standard armor where you're like safe from shockers but not husks, that could work.

> turn them either unrepairable or flimsy so there's an attritional component to longer fights.

Okay, but here's the thing: when would you wear your hazmat, then? If we make it a precious, finite resource you would want to only use it when you really need it, right? But there exists no such distinction. There's always acid/electrical zombies. So you either spend your entire life in it, or you never wear it. Same still applies to the 90% idea; either that remains a necessary level of protection and you still have to wear hazmat at all times, or it's not good enough and you never use it.

I don't think these are necessarily bad ideas, but I think they have to be in addition to altered spawns, not instead of. As long as the enemy composition remains roughly the same almost everywhere, we're never getting away from this situation where there exists a single, correct loadout. We could tweak things so the activity suit is no longer part of it, but then we just end up with something else that's "too good". There's never going to be room to strategize and make meaningful choices, and specialized protection like hazmat suits is always going to be either pointless or mandatory.


Also ftr if you wanted incremental electrical protection you'd have to run it past Kevin, because he vetoed it last time. He said it's just not how electricity works, which sounds about right, but I'm not an expert so maybe there's room to argue.

**Comment by arockperson** [comment]
> (so the problem persists, you just made cities even easier).

Is making cities easier really such a bad thing? To be clear, I'm not saying cities shouldn't spawn any acid and electrical zombies, but it should be drastically reduced in most areas that don't have special affinities.

In super late game (over 2 years, say) cities are the most dangerous place in the game, due to how evolution works (the recent changes might have made it more manageable, though). Cities could be a little bit easier and labs and military installations should be WAY harder imo.

Sorry to get off topic, TLDR I think #58087 would be good.

**Comment by robotic-gamer** [comment]
just my two cents but electricity protection could be made more accessible by putting in a close to skin protective suit. ex. like a thermal electric outfit but instead of heating it is just a cotton suit with copper wiring weaved in. for acid protection the player could just coat themselves in some sort of chemical base (wood ash, baking soda, limestone powder etc.) for temporary protection. the easiest way to balance this would be to make protection from acid/electricity get degraded a bit each time it protects you from the damage. this would mean heavy exposure could still get you by just degrading your protection until your vulnerable.

**Comment by Venera3** [comment]
> Zombie technicians are found in industrial locations and exclusively evolve into shockers.

The techie->shocker pipeline is a remnant of shockers' handwave being fritzing out bionics, the upgrade mongroups could use a lick of paint by now. Again, where do you put them if you want to restrict them? Both "acid" and shocks run pretty heavily on Blob Bullshit(patent pending), so building on already existing base affinities or environmental factors is a pretty big stretch.

> Maybe it's also a problem that the only good solution to acid/electrical zombies negates them entirely, but as discussed that's kind of how all defense works in this game as an inevitable result of the vast difference between taking 1 damage and taking 0 damage. Any solution where protection isn't absolute risks being incredibly brutal on players, especially after a bit of evolution and especially for melee characters.

Melee characters getting to yolo into TAB range and from then on ignore a class of enemies that are balanced around their specialities the moment they find a nifty suit is bad design, even if it is comfortable. Monsters already have scaling electricity armor, so something along those lines feels fair enough - both gear attrition or scratch damage would loosen up the binary system, and allow less specialized armor to pick up a bit of the slack.

> In super late game (over 2 years, say) cities are the most dangerous place in the game, due to how evolution works (the recent changes might have made it more manageable, though). 

Super late game is a tiny fraction of game time, so balancing around it should not be a huge priority. Up until the one-year point cities are pretty easy, what with two dozen zombies milling about in city centres.

**Comment by bean-b** [comment]
I'm not quite so sure for electricity, fungal spores etc. but I feel like more clothes should have variable acid protection. What has environmental protection values seems kind of pick and choose at times, and I feel like there are many clothes with no acid protection values that I would much rather be wearing when i got splashed with acid then being naked.

**Comment by sa201213** [comment]
Ahem. Do we have any real equivalents to compare such suit with? Nomex suits protect from fire, yes, but protection from electricity/acid/spores wasn't advertised.

"Protects from everything, cheap and yet is as thin as your underwear" sounds like something from the future.
