### ISSUE TITLE
Game tries? to spawn air and rubble in the same place?

### ISSUE THREAD

**Issue by FractalRecursions** [CleverRaven/Cataclysm-DDA#61435]
### Describe the bug

 DEBUG    : Setting terrain t_open_air at (21,118,1) where furniture is f_rubble.  Terrain is_open_air
If this is intentional, set the ALLOW_ON_OPEN_AIR flag on the furniture

 FUNCTION : bool map::ter_set(const tripoint&, const ter_id&, bool)
 FILE     : src/map.cpp
 LINE     : 2047
 VERSION  : 01d15e7

### Steps to reproduce

Create lab start. Spawn in. Get error message. Occasionally I also get achievements for killing monsters despite not having moved. Screenshot included. Monster kill at spawning in the game.

### Expected behavior

I expect the game to just run without an error message and free kills?

### Screenshots

![Clipboard01](https://user-images.githubusercontent.com/114946279/193643825-6a0a3172-2d6b-495f-a2c6-5cac1e661247.jpg)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.2006 (21H1)
- Game Version: 01d15e7 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by robotic-gamer** [comment]
my guess is their is some sort of crater at the surface in the reality bubble. what I think is happening is that the crater spawns with rubble but in place of the hole in the middle are a bunch of active alien bombs which promptly explode to create the hole. note alien bombs seem to be just be a pseudo item your not really meant to see and are just meant to create organic looking craters/blast damage. the error is occurring when the explosion destroys the floor some debris was on without destroying the debris first. the game then gets a bit confused because debris is not supposed to exist floating in the air. as for the kill, my guess is some unfortunate wildlife spawned a bit too close to the bombs. apparently things those bombs kill count as your kills. can you confirm if there a crater on the surface please?

**Comment by FractalRecursions** [comment]
That sounds sensible. Unfortunately, I never made it out the lab. Some kind of nether horror ate my face. So I cannot confirm your hypothesis. Sorry.

**Comment by PatrikLundell** [comment]
It's not really RNGs being weird but you being unlucky enough to encounter unintended weirdness. These messages started appearing when logic was introduced to allow map makers to specify whether the placement of map features should retain or remove "furniture", and this message was introduced to capture cases where the map generation hadn't applied the new flags (retail/remove), so a fair number of pre existing issues started to become visible.

Unfortunately, without a save and without any other information making it possible to what the affected map feature is it's probably not possible to identify the cause of this particular issue.
It can be noted, however, that the rubble is located at Z level 1, so it's probably some kind of collapsing building, as craters are made into the surface (although a crater possibly could form under a building).
