### ISSUE TITLE
Hobbies should give skills the same way as professions

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#61443]
### Is your feature request related to a problem? Please describe.

Currently the way hobbies award skill points is very confusing for a new player and just generally weird. You're given a value for the skill ("competent"/etc) but this actually gives you *experience* and not real skill points, so it is entirely separate from the way professions award skills (the profession gives you skill points on top of your skill points chosen in the skill point menu). This also means that the skill experience given by hobbies are effectively pointless if you have any points chosen elsewhere in character creation. Like the athletics training given by Marathon Runner is useless if you also picked up some athletics skill elsewhere, because that athletics experience given by the hobby won't even push you up a single skill level.

### Solution you would like.

Ideally hobbies would give you full skill points, and then you would add skill points in a separate menu on top of those. So if you have 4 total athletics from your hobbies and 2 athletics from your profession, then you have +6 on top of your assigned skill points. Currently though you would just have 2-3 athletics because of the way hobby skill XP is nearly useless due to the exponential requirements of skill levels.

### Describe alternatives you have considered.

Literally none of this matters because just use freeform lol. Things are moving towards that anyways (freeform with an estimate of how difficult certain things will be) but IMO that's not a reason to keep the weird incongruous system.

Also, I'm not especially concerned about this ruining balance, because it's correct 100% of the time to choose as few skills as possible in favor of skills and traits due to skills being learnable.

**Comment by Terrorforge** [comment]
> This also means that the skill experience given by hobbies are effectively pointless if you have any points chosen elsewhere in character creation.

That's the point. The idea is that backgrounds should be used to round out a character, not as a way to stack skill bonuses into the stratosphere. It's questionable how well it actually does that, because you're right that skill bonuses at chargen are mostly worthless. However, I think making Backgrounds bonuses stack fully would change that. Starting with 3 points of Fabrication is almost meaningless because you can grind that out in a few hours, but starting with 7 points of Dodging is hella busted.

And we can talk about how balance doesn't matter because you can just do Freeform, but the reality of the situation is that a lot of people have a deep-seated reluctance to do that. I know it doesn't matter, and I still can't bring myself to do it. But more importantly, new players who have no way of knowing what is and isn't busted rely on the points system for guidance. Making this change _will_ result in the average character being stronger.

That said, I don't know if that's necessarily bad? The game is already hard enough for beginners, and easy enough to break for veterans, so I don't know if it's all that harmful to balance. It would give Backgrounds a reason to exist as something other than a convoluted delivery system for Traits. It would make random characters less bland. My main caveat is that maybe Backgrounds bonuses shouldn't stack with each other? The part where being a backpacking camper with first aid training gives you more medical knowledge than an MD is where this concept becomes truly stupid.
