### ISSUE TITLE
Healthy calories should be tied to your height

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#61455]
### Is your feature request related to a problem? Please describe.

Currently the healthy amount of stored kCal for your character is 55,000 no matter how tall or short you are. This isn't true to life.

### Solution you would like.

It should change, probably by the same fraction that your base weight excluding stored kCal changes, change healthy stored kcal whenever a Character is initialized or their height changes.

### Describe alternatives you have considered.

This will cause dramatic height shifts from mutations to cause rapid fluctuations in your healthy stored kcal meaning you might go from healthy to emaciated by becoming large. I don't know if this is good or bad.

**Comment by PatrikLundell** [comment]
Apart from the generic game mutation morphing making no real world sense, preservation of energy considerations ought to result in the existing mass being redistributed on mutation, which ought to both affect the stored calories as it's abruptly converted into "active" tissue (on growth), or blubber (on shrinking), and the number of calories that correspond to the various health ranges. Changing two size steps within a short amount of time may well be lethal.

**Comment by Nebnis** [comment]
I'm also 100% sure this gonna break most of the big mutations because they already have increased calories via other mutations.

**Comment by Terrorforge** [comment]
They have increased stomach size and increased calorie consumption, not increased calorie storage. The healthy/overweight/obese thresholds are still the same, which causes problems with yo-yo dieting. The goal posts remain in the same place, but your total calories shift about twice as fast in both directions, so it becomes really easy to overshoot. So in terms of big mutants, I think this would be a positive mechanical change, and would make intuitive sense as x% body fat is of course more total energy on a larger body.

However, I'm a bit skeptical of tying mechanics to ostensibly cosmetic variables like height, because it creates weird min/maxing incentives. It makes sense in as far as that's how it works in real life, but it gets weird in practice when it encourages players to make every character 2m tall.

**Comment by PatrikLundell** [comment]
The game's ponies provide a drive to make characters as small as possible to be able to ride them while fully geared up. However, that's a very niche application.

I think it would be better to actually make height have effects than to treat it as purely cosmetic, though.

**Comment by Zireael07** [comment]
> I think it would be better to actually make height have effects than to treat it as purely cosmetic, though.

Seconded
