### ISSUE TITLE
Paint should be migrated to a bucket holding liquid paint

### ISSUE THREAD

**Issue by TheShadowFerret** [CleverRaven/Cataclysm-DDA#61479]
### Is your feature request related to a problem? Please describe.

Paint is currently self-contained, with no paint can containing it.

### Solution you would like.

Make paint a liquid that must be held in a can.

### Describe alternatives you have considered.

N/A

**Comment by PatrikLundell** [comment]
Makes sense apart from using a bucket. A bucket has no lid and so can't be carried with contents in it except in the hands, while a paint can can be closed with a lid. That would probably require the introduction of a new container object of a suitable volume.

**Comment by Lasiace** [comment]
A sealed large tin can might work, A gallon would probably be more common than a 3L can, but it's otherwise quite accurate, since paint cans are usually also big tin cans sealed and filled with paint. There's the potential issue of resealability, though, since I'm pretty sure you can put the lid back on paint cans with a hammer rather than needing a whole can sealer.

**Comment by PatrikLundell** [comment]
Paint lids can definitely be put back on, and it's good enough that it keeps the paint in working condition for quite a long time, indicating that it's mostly or completely air tight (or the solvent would evaporate). I'd still not want to carry them on the side or upside down, but I'd expect paint cans placed in a backpack with some care not to fill the backpack with paint (but there might still be some leakage from used cans where the lid doesn't seal it fully).

Not something the game simulates currently. Using gallon jugs might be good enough, though.
