### ISSUE TITLE
Furniture: Generator, Metal Compactors and AC

### ISSUE THREAD

**Issue by Kywi001** [CleverRaven/Cataclysm-DDA#61500]
### Is your feature request related to a problem? Please describe.

Generators: now that we have working furnitures and powergrids, and we have a ton of broken generators ingame, wouldn't be nice to have some of them as an actual working generators?

Metal Compactors: they were working, well, "were", now that we can make powergrids, its probably a good time to bring them back as a furniture.

AirConditioners: please

### Solution you would like.

Generator: have 20L liquid container for Gasoline and if turned on, will give a very fast energy generation while burning gas fast, just like the Generator vehicle.

Metal Compactor: bring back its old usage but now it takes time by itself like how a washing machine takes time to finish without you babysitting it.

AirConditioner: just like the vehicle cooler minus the heat generation.

**Comment by anothersimulacrum** [comment]
Metal compactors were not working, if they come back they should look nothing the same in function, because they were previously magic.

**Comment by Kywi001** [comment]
> Metal compactors were not working, if they come back they should look nothing the same in function, because they were previously magic.

yes, they were magic, thats why I suggested them to take hours like how washing machine takes time to finish and probbably add a huge power consumption too

**Comment by PatrikLundell** [comment]
- Generator: I don't think "furniture" would work, but they should definitely be suitable as appliances.
- Air Conditioner: All of them generate heat in the real world, so the trick is to make sure the generated heat is expelled outside (through the wall or through the "exhaust pipe"). This probably means an appliance implementation would need at least two parts: A cooler on the inside, and an exhaust "in" the wall emulating a wall mounted external part. There is currently no support for appliances working together is fixed combinations, so someone would have to implement that first.
- The metal compactor was very nifty magic indeed. The magic part doesn't come from it being instantaneous, though, but rather from it magically transforming items with varying degrees of impurity into nice full quality ingots etc. Some real world processing would probably take the metal, melt it, separate impurities out of it, and then cast ingots, which would probably be a decently sized industrial process (or quite possibly multiple processes). There's are reasons real world recycling rates are low.

**Comment by Kywi001** [comment]
> * Air Conditioner: All of them generate heat in the real world, so the trick is to make sure the generated heat is expelled outside (through the wall or through the "exhaust pipe"). This probably means an appliance implementation would need at least two parts: A cooler on the inside, and an exhaust "in" the wall emulating a wall mounted external part. There is currently no support for appliances working together is fixed combinations, so someone would have to implement that first.

I wonder if it can be coded as such that cold air comes out in the front side and the hot air comes out of the back side and can be mounted on a special wall that allows AC installations or a window.

> * The metal compactor was very nifty magic indeed. The magic part doesn't come from it being instantaneous, though, but rather from it magically transforming items with varying degrees of impurity into nice full quality ingots etc. Some real world processing would probably take the metal, melt it, separate impurities out of it, and then cast ingots, which would probably be a decently sized industrial process (or quite possibly multiple processes). There's are reasons real world recycling rates are low.

Well, yeah, but we can just reduce the amount of items it can give and/or make it so only steel mills have a permanent fixture of metal compactors, and we just have to find a way to power up the facility just like irradiation plants, this way we can just assume that the said facility have the process automated.

**Comment by robotic-gamer** [comment]
for generators perhaps it would be best if players could craft their own from engines and alternators. ideally there would one for each fuel type (gasoline, diesel, charcoal), the last one should probably require a makeshift steam engine as a part due to the rarity of other types of steam engines.

one last type could be a generator that uses thermocouples like an rtg to generate a very small amount of power when a fire is burning on its tile (like a fireplace). the thermocouples could be made by using different common metals like steel, copper aluminum. the player could take it a step further by crafting a makeshift rtg using scavenged radioactive materials (could be in found small amounts in or around craters (which would give a reason to clear the rubble found around craters), or in larger amounts in toxic waste dumps and hazardous waste sarcophagus). alternatively you could built something by combining a large amount of betavoltaic cells. these kind of generators would generate only a small amount of power but could be run in basements, or inside buildings to power things like a battery charger as an alternative to a hand-crank charger
