### ISSUE TITLE
Game crashes removing nested items at bottom of "Sort Armor" screen, when inventory is full.

### ISSUE THREAD

**Issue by epsimpson** [CleverRaven/Cataclysm-DDA#61527]
### Describe the bug

This is an intermittent error.
When game doesn't crash, it displays invalid data.
My save file almost always crashes before all items are unequipped, so good way to observe the crash itself, but can see the corrupt data even when it doesn't crash.  Hopefully fixing one will fix the other.

My compressed save file is too big, 40.3 MB.  Hopefully my steps to reproduce work.

### Steps to reproduce

1. Create character.
2. Equip with clothes containing pockets, holsters with loaded guns, sheaths with knives, axe ring with axe, rope loop with planks, backpacks with filled containers, etc.
3. Wield an item in hand.
4. Fill pockets to force game to try to unequip to hands, and then ask what to do with item in hands.
5. Type `!` to turn off SAFE mode.  (Seems to make a difference in crash frequencies, but could be statistical.)
6. Type `+` to "Sort Armor".

Order of removal seems to matter, proceed from bottom of "Sort Armor" screen to top.  When the program (inappropriately) moves the pointer away from the bottom item, move it back down to the bottom item.

Basic order of events, once "Sort Armor" screen is open:

9. Select bottom item.
10. Type `u` (unequip)
11. Confirm removal.  INTERMITTANT PROGRAM CRASH WILL OCCUR HERE.
12. If dialog asks how you want to handle previously wielded item then:
a. Observe *no* item selected in left pane and *invalid* data in central pane.
b. Hit `ESC` (drop item unequipped, not item wielded)
c. Observe *correct* item selected in left pane and *valid* data in central pane.
d. Hit `ESC` again (always have to escape twice.  Odd.)
e. Observe item selected inappropriately changed in left pane and valid data for that part in central pane.
13. If no crash at 11 then goto 9.

If you force the game to refresh its view at step 12.a, then the screen will look like 12.c, but you will still have to hit escape twice.  I built up my steps to reproduce by going back and forth between the game and the desktop.  I used the system menu button (looks like the Windows icon on my keyboard) to leave the full screen game.  If I do that and then return to the game, the game will almost always refresh the view, giving the appearance of being at step 12.c.

### Expected behavior

I expect:
1. unequip without crash.
2. no need to escape twice.
3. no need to move selected item back to bottom after bottom item removed.

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.5 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.F-11610-g90fc2e4586 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

No crash.log file was produced.
My compressed save file is too big - 40.3MB.  I have saved it in case someone wants it another way.

[debug.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/9737405/debug.tar.gz)

**Comment by ZeroInternalReflection** [comment]
I can't guarantee this is the same issue that epsimpson was experiencing, but I've found a repeatable crash on `u`nequip in the Sort Armor screen:

1. `w`ield (_not_ `W`ear) a "pair of scrap knuckles" or similar item with the "UNARMED_WEAPON" flag
2. `W`ear clothing/equipment that won't fit in your inventory when it's taken off
3. Go to the Sort Armor screen `+`
4. `u`nequip a piece of equipment that won't fit in your inventory
a. The order does seem to still matter here.  I _think_ the trick is that you're removing the item that character::dispose_item() would try to put your scrap knuckles into.  In the attached save, removing the wrist watch then the messenger bag reliably segfaults
b. The game tries to create a uilist popup asking if you want to stop wielding your scrap knuckles
c. When the uilist is displayed, the game tries to refresh the screen behind the uilist popup
d. This means that the sort armor screen looks at all of your equipment again, when you're halfway through taking an item off and halfway through unwielding an item and putting it in your inventory
e. Segfault.

Crash log:
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/10147150/crash.log)

Save:
[VillageGreen.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/10147152/VillageGreen.zip)

The "UNARMED_WEAPON" flag seems to be key, because if you're _wielding_ an item with that flag, then your character is not considered to have a weapon.  This line here determines the bool "allow_wield" based on whether you have a weapon.  
https://github.com/CleverRaven/Cataclysm-DDA/blob/14736f8a4e542da6cd5907ef8391488a960c7ad5/src/character_attire.cpp#L1342
So, this ensures that you have something to _unwield_ when you try to wield the removed item.
https://github.com/CleverRaven/Cataclysm-DDA/blob/b8eb345316acc323bee6bd6c719429c5e32b080b/src/character_inventory.cpp#L212-L221

I'm not sure what the best way to fix this would be.  It might be simplest to disable update of the sort armor screen while you're in the process of unequipping.  Or perhaps changing the has_weapon() check so the game won't try to unwield what you're holding.  Otherwise, I think a lot of assumptions that the Sort Armor screen makes can't be relied upon, and changing that will be a mess.

**Comment by epsimpson** [comment]
I checked the save file for my original bug report, and that character is wielding scrap knuckles, and by hitting escape every time I ensured the scrap knuckles remained wielded for every container I was trying to unequip.

The only difference I see is my bug was reliably intermittent.  Using the same save file it crashed while removing different pieces of equipment, even though they were always removed in the same order every time, and sometimes didn't crash at all.  However, the fact that the Sort Armor panes contained garbage data when it didn't crash (in my case) suggests perhaps the invalid memory locations being read during the screen refresh simply weren't always sufficient to cause a segfault.
