### ISSUE TITLE
Advanced Inventory Manager reveals unseen tile details

### ISSUE THREAD

**Issue by sparr** [CleverRaven/Cataclysm-DDA#61528]
### Describe the bug

The AIM will provide the name and capacity of terrain, furniture, vehicle parts, even if the player can't see them.

### Steps to reproduce

1. Stand adjacent to an unseen tile
2. Open the AIM
3. Press the direction of the unseen tile
4. See info about the tile, name below the direction words, weight and volume capacity below the direction selection indicator

### Expected behavior

Information is not revealed for unseen (or even not currently visible?) tiles.

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: ManjaroLinux; Description: Manjaro Linux; Release: 22.0.0; Codename: Sikaris; 
- Game Version: ea1e28fdbc [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by robotic-gamer** [comment]
personally I think the player should always be given vison of adjust tiles, at least until more nuance is added to vision. mainly this is that currently vision is all or nothing, ie  you can go from seeing everything on a tile down to a single nail, to failing to see a hulk just one tile further. also the game does not give you limited information (ie making out a humanoid shape in the distance but being unable to tell if its a zombie, npc or even a blank body)

currently preventing vision of adjacent tiles causes a lot of inconsistency with features and leads to a lot of oddities. these includes:
- the feature in the sidebar that shows visible creatures around you will always show entities directly next to you
- the problem with AIM mentioned in this issue
- the fact you can grab items next to you irrespective of vision
- you can move furniture without seeing it

problems even if these were corrected:
- not being able to feel out a tile before you move to it
- being unable to know where melee attacks are coming from even though you should have a fairly good idea even without vision
- being unable to realize your currently trying to walk through a wall because you have nothing for reference only realizing when you study your over map position
- running players not slamming into walls they couldn't see
