### ISSUE TITLE
Reduce root cellar Survival skill requirement

### ISSUE THREAD

**Issue by BlueDragonFire** [CleverRaven/Cataclysm-DDA#61546]
### Is your feature request related to a problem? Please describe.

I play CDDA version 99a3907. I believe that the Survival skill requirement to build root cellars is simply too high to make building one worth it in any way. So far, it is far easier for me to steal a fridge, steal a car battery, and hook them up to a solar panel or even an ASRG. 

The biggest issue thus far for this method is finding a tool with bolt turning 1 and it only takes raiding 2, maybe 3, houses before you find one. 

The biggest issue with a root cellar is that it is inferior to a fridge and reaching Survival 4 has proven more difficult than fabrication 4. You also need a tool with digging of 2 or more to build a pit for it which, while much easier to craft, is far harder to find.

### Solution you would like.

Make root cellars more practical by reducing the Survival skill requirement for construction. Preferably to Survival 2

**Comment by Jerald-of-Libya** [comment]
Stuff that's hard to make doesn't mean it has to be good. Consider: "Why should I weave a straw basket for 20hrs to get some extra storage, if I can just get a backpack or suitcase from an abandoned house in like 5 minutes?"

A working refrigerator is of course going to be leagues better than hole-based cooling. That's just how technology goes.

Whether we like it or not, we usually have to justify with IRL reasoning why we can maybe bump down the requirements. "Like.. I think we can go with digging 1 because my granddad made his own root cellar with just his bare hands." ... or something like that.

**Comment by Zireael07** [comment]
> we usually have to justify with IRL reasoning why we can maybe bump down the requirements

I believe the hardest part of creating a root cellar is actually digging it. So digging 2 but lower survival than it currently is. Survival 3 sounds ok to me.

> The biggest issue with a root cellar is that it is inferior to a fridge

It will always be, modern tech > premodern solutions

**Comment by anothersimulacrum** [comment]
There's no valid rationale for change here.

**Comment by BlueDragonFire** [comment]
> Whether we like it or not, we usually have to justify with IRL reasoning why we can maybe bump down the requirements.

Well in that case the requirement should be lowered further to Survival 1. My reasoning is that if I can create such advanced things such as a full suit of scrap armour or a repeating crossbow with Fabrication **3** (among other lesser skills) then, comparatively speaking, a glorified hole in the ground shouldn't be that complicated because that's what it is. It's a hole in the ground lined with rocks and filled with straw. It's not that complicated compared to what I just mentioned and yet it still requires Fabrication 4 on top of that. Fabrication 4 is enough to create an advanced collapsible solar array and the idea that a hole in the ground needs the same amount of skill and know-how as literal space-age tech is just silly. 

> It will always be, modern tech > premodern solutions

Well, yes you are right. My point is just that, outside of Innawood, the root cellar seems comparatively useless in all circumstances because by the time you get skilled enough to even build one, you already have an ASRG-powered fridge set up  that is better in every way. I just don't think it should require this much effort and knowledge to dig a hole, fill it with bricks, and insulate it with straw.

I once spent an ungodly amount of time grinding Survival in order to build my own in the hopes that maybe it was something like a better fridge considering the effort you had to pour into it only to find out it was absolutely terrible. Bit of a surprise, and a frustrating one at that, but I later learned that CDDA was very, very much based in realism despite its sci-fi aspects leading me to think otherwise.

**Comment by sonphantrung** [comment]
>but I later learned that CDDA was very, very much based in realism despite its sci-fi aspects leading me to think otherwise.

[https://github.com/CleverRaven/Cataclysm-DDA/wiki/FAQ-from-Discord#Game_focus_and_direction](https://github.com/CleverRaven/Cataclysm-DDA/wiki/FAQ-from-Discord#Game_focus_and_direction)

**Comment by PatrikLundell** [comment]
Root cellars have the advantage of having a large capacity (one cubic meter) and not requiring lots of electric power. It can also be noted that they predate (both in the game and in the real world) fridge appliances.
It's also much faster to make one than to find all the things needed to set up a powered fridge, and typically is less risky, since you can usually get the tools needed for a root cellar without wading through hordes of zombies to reach and get the required parts.

Not having build a root cellar, I expect the tricky part to be to construct the roof such that it's thick enough to insulate without collapsing down into the cavity (and you also have to place it somewhere that's above the ground water so it doesn't flood from below).

**Comment by Zireael07** [comment]
> Not having build a root cellar, I expect the tricky part to be to construct the roof such that it's thick enough to insulate without collapsing down into the cavity (and you also have to place it somewhere that's above the ground water so it doesn't flood from below).

Exactly why I wouldn't touch the digging requirement but survival could be lowered.

**Comment by BlueDragonFire** [comment]
> Exactly why I wouldn't touch the digging requirement but survival could be lowered.

This is basically my whole point
