### ISSUE TITLE
Unable to trim string '' to width 0... erro report when trying to craft flatjaw tongs

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#61591]
### Describe the bug

 DEBUG    : Unable to trim string '' to width 0.  Returning empty string.

 FUNCTION : trim_by_length
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\output.cpp
 LINE     : 275
 VERSION  : 64e17c6

gets generated repeatedly when trying to craft flatjaw tongs (hitting space many times does not get through it, but ignore does). When done I get to chose components from 1 and 2, both of which have empty lines.

### Steps to reproduce

1. Gain enough skills and resources to be able to make flatjaw tongs (I have both lumps of steel and chunks of steel, making both variants available, which may or may not be relevant).
2. Try to craft the tongs.
3. Get the message.
4. Successfully craft the tongs anyway.

### Expected behavior

No error message.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.2006 (21H1)
- Game Version: 64e17c6 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Innawood [innawood]
]
+ JSON "mod" to get rid of portal storms
+ Added steel lump crafting recipe to barebones base camp.

**Comment by Ezrashaw** [comment]
Just to confirm, you did this with the 'lump of steel' recipe? I attempted this with my latest linux tiles build and it all worked fine. Maybe you could attach a debug log or save game?

**Comment by PatrikLundell** [comment]
I don't think the addition of the recipe has anything to do with the error message for the flatjaw tongs recipe. The addition works, and I've only added it to the configuration list for completeness (and yes, it's the Innawood specific bog iron lump of steel recipe).

**Comment by Ezrashaw** [comment]
Sorry, I meant the variant but I see now that you tried both? The issue seems to be around rendering text so the recipe variant would be important.

**Comment by PatrikLundell** [comment]
I only have a single flatjaw tong recipe, but it has two variants, both of which produce blank lines:
![Screenshot (261)](https://user-images.githubusercontent.com/22739822/194847713-c71f5247-1539-43aa-926b-af9abf16cf39.png)

![Screenshot (262)](https://user-images.githubusercontent.com/22739822/194847731-f6c230fd-ceb0-44d1-956d-81c9271031a3.png)

I only verified the variant that took two lumps of steel worked (because I don't find any recipe to get chunks from lumps, so the few chunks I have are rather precious).

**Comment by PatrikLundell** [comment]
Could well be that it's been fixed since. I'll try it myself. Thanks for checking it.

**Comment by DSeyka** [comment]
>because I don't find any recipe to get chunks from lumps, so the few chunks I have are rather precious

It's not a crafting recipe, but you can disassemble lumps of steel into chunks of steel.
You can also look through your stuff with a filter "d:chunk of steel" applied to find anything else that can be similarly taken apart.

**Comment by Jerald-of-Libya** [comment]
This is not specific to flatjaw tongs. I recall crafting other things, and getting the same issue.

Main requirement i think is that you have to have enough alternative ingredients to craft the thing so that the selection window pops up:

![image](https://user-images.githubusercontent.com/44783693/194883717-928f39b0-fc02-4084-8d5f-36491f1d6334.png)

Here's me crafting a leather skirt. Notice how the selection window is empty in the middle. That's probably the empty string the error is talking about.

Fortunately it's not much of an issue since the box at the bottom still shows the ingredients.

**Comment by ZeroInternalReflection** [comment]
I haven't had a chance to test this out, but looking at the code, I'm guessing the chain is:
1. When you craft something that has multiple "selections of components" (IIRC that comes about when a single component can be used in multiple places in the recipe), you get a uilist popup to select the set of components you want to use
2. That uilist is set up here: https://github.com/CleverRaven/Cataclysm-DDA/blob/f11519b2b5a8a6f40366e94a4e039dcc5c6d00d6/src/crafting.cpp#L1565
3. The uilist does not have any text for the entry (ideally, it would probably have a quick summary of the selection, but that's probably quite complicated to figure out)
4. When the uilist prints to the screen, it trims it based on the maximum entry length (https://github.com/CleverRaven/Cataclysm-DDA/blob/f11519b2b5a8a6f40366e94a4e039dcc5c6d00d6/src/ui.cpp#L792), which is 0
5. trim_by_length then says "Hey, trimming to 0 means this text will never be printed", which is the error you actually see.

The fix for this is probably:
1. Find a way to say _something_ about a particular selection of components, rather than having an empty, numbered list
2. Have uilist trim based on the space available, rather than the space it expects to use
