### ISSUE TITLE
Makeshift crowbar should have the same size and weight as a pipe

### ISSUE THREAD

**Issue by cdru123** [CleverRaven/Cataclysm-DDA#61594]
### Is your feature request related to a problem? Please describe.

Despite being made simply by hammering a pipe for a few minutes, the makeshift crowbar has roughly only a third of the pipe's volume and weight. Not only that, but it's also shorter by 15cm.

This also has some balance implications, as it gives the makeshift crowbar a high DPS for something that can be made in the first few minutes with no skill requirements, with it being at least as good as the cudgel.

### Solution you would like.

Give the makeshift crowbar the same weight, volume, and length as a pipe.

**Comment by Zireael07** [comment]
It being shorter makes sense since it's bent. Weight and volume however should be similar to pipe.

**Comment by Ezrashaw** [comment]
This might also mean that the standard crowbar would have to have its size increased as well, the crowbar + makeshift crowbar probably are about the same right?
I also don't think it needs to fully be the same as the pipe. Maybe just 3/4?

**Comment by PatrikLundell** [comment]
@Ezrashaw: I don't agree with your logic. A crowbar is the length it is because that's what trial and error has come up with as a suitable length. A makeshift crowbar, meanwhile, gets the length it gets based on whatever the length of the thing you "makeshift" it out of happens to be.
Thus, a makeshift crowbar made by banging on a pipe to bend a bit at the end will end up at a length of a pipe minus the section "lost" by bending, which probably isn't going to be all that much (5-10 cm?). Sure, you could take a hacksaw to it and shorten it, but that would have to be a different object, such as e.g. a "shortened makeshift crowbar" as you don't want to make a hacksaw a mandatory item for the construction of a makeshift crowbar.

**Comment by anoobindisguise** [comment]
If the pipe is sawed in half first (would require metal sawing) then it could be lighter, and that would probably make a more effective prying tool anyways.

**Comment by Ezrashaw** [comment]
> @Ezrashaw: I don't agree with your logic. A crowbar is the length it is because that's what trial and error has come up with as a suitable length. A makeshift crowbar, meanwhile, gets the length it gets based on whatever the length of the thing you "makeshift" it out of happens to be. Thus, a makeshift crowbar made by banging on a pipe to bend a bit at the end will end up at a length of a pipe minus the section "lost" by bending, which probably isn't going to be all that much (5-10 cm?). Sure, you could take a hacksaw to it and shorten it, but that would have to be a different object, such as e.g. a "shortened makeshift crowbar" as you don't want to make a hacksaw a mandatory item for the construction of a makeshift crowbar.

Yes, fair point. I should've made myself more clear there but I do agree with you. I was really attempting to agree with OP that the pipe should be the same (more or less) as the makeshift crowbar but I didn't quite say that correctly. I assume then that we can also increase the "longest_side" for the makeshift crowbar from 45cm (pipe: 60cm) to 50-55cm, also a 45cm crowbar doesn't seem too long from a quick google search. I would also suggest then that the pipe's length is increased to 1m. Google suggests that for prying a door open you need a crowbar at least 2 feet long. Also, more clarity around the properties of the pipe, in terms of how resilient it is, would be nice. 

> If the pipe is sawed in half first (would require metal sawing) then it could be lighter, and that would probably make a more effective prying tool anyways.

I also think that if we do this then it needs to be its own intermediate weapon because IMO getting a early-game tool with hammering is easier than getting one with sawing, and in general starting from nothing in the apocalypse you are more likely to be able to bend a pipe a bit rather than cut a (metal) pipe.
