### ISSUE TITLE
Massive slowdown over the time with seemingly no reason

### ISSUE THREAD

**Issue by Xayrlen** [CleverRaven/Cataclysm-DDA#61620]
### Describe the bug

After 2 and a half seasons of gameplay game became very slow during any prolonged activities like crafting, sleeping and reading over the time with no obvious or known reasons.

### Steps to reproduce

1. Load up a save file;
2. Try crafting/sleeping/building/reading;
3. "Enjoy" your time waiting for all of that.

### Expected behavior

Sleeping alone should never take up to 10-15 minutes of real time. Crafting should also not take the suspiciously same long time depending on the required crafting time.

### Screenshots

Since git won't allow uploads of files more than 25MB here's a link to a google drive with a save file:
https://drive.google.com/file/d/1aJKcuRp3-hSxGt3hp0qLXWtK3KtemL32/view?usp=sharing

### Versions and configuration

OS: Windows 10;
Game Version: c12b0ce;
Graphics Version: tiles;
Game Language: English;
Mods loaded: 
  - Dark Days Ahead
  - Disable NPC Needs
  - No Fungal Growth
  - Bionic Professions
  - Dino Mod
  - No Hope

### Additional context

I've been looking through the other posts and pieces of advice to resolve such as: killing everything with debug, taking down unused/excessive amounts of appliances and dealing with huge item stacks. Even after dealing with everything mentioned before - there was no improvement. In fact, I believe the game is slowing down by itself with passing time alone, since I'ts been nearly a whole season and I've been doing stuff within me in-game shelter.

So right now I'm seeing a huge performance difference, even though there was almost no change to surroundings (except for cleared up an underground greenhouse). Even thought my PC is not a high-end one, I see no plausible reasons for sharp performance drops when surroundings are barely changing. Especially when it was running far smoother than now. 

I believe the game is slowing down by itself with passing time alone, since I'ts been nearly a whole season and I've been doing stuff within my shelter. More so when it was running far smoother than now.

**Comment by anothersimulacrum** [comment]
Perf doesn't seem particularly problematic to me, but I'm running this save on a fairly substantial computer.
Here's a profile. Nothing super substantial, but there look like a few easy leads for minor gains there.
![image](https://user-images.githubusercontent.com/42699974/195420509-829eb4af-6eb1-4bbf-8e97-530316420610.png)

**Comment by robotic-gamer** [comment]
perhaps it would be good to see if the slowdown is localized, ie walk ten or so overmap tiles away and see how fast the game runs there. that way it could be determined if the lag is from some entity in the reality bubble. in my current run I ran into my own significant slowdown, there were seemingly no culprits nearby despite looking in every house and basement. it turned out that some random house without stairs to the roof had a hundred or so chickens on its roof. no idea how a chicken/bird egg got up there in the first place to create them all.

**Comment by Nandorianen** [comment]
I return to play a long session of Cata every year or two, and I always see these slowdowns after awhile. Save file bloat obviously slows down saving and loading speed because nothing ever gets deleted or otherwise cleaned - once you explore something, all the terrain, items, zombies stay with your save, which really discourages exploration.

However, slowdown when passing time seem to be caused by items. especially nearby items. I notice it a lot because I like to hoard all the crafting materials in one place around crafting stations.
Here's how you can test it:
1. Download the latest experimental, hit "Play now" with default scenario.
2. Debug-spawn 5 short cordage ropes, craft a long rope. The recipe requires no skills or tools and takes 45 minutes.
3. Debug-spawn 10000 short cordage ropes, craft a long rope again. Notice the difference with which 5-minute chunks tick.
4. Go about 10 tiles away from the pile of ropes and try to craft a long rope again. It should noticeably speed up.

The difference should be obvious enough even on a good PC. However, the game slows down much more with naturally collected hoards of various items - probably because they have more values assigned to them, like damage, birthday, and such.
When I started to mod items like glass shards and planks to be stackable (or to become ammo type), my experience really improved, even if it messed with some of their functions. Moving thousands of crap items like plastic bags and wrappers away from the main crafting pile also helped greatly.

It would be very nice if someone could figure out why the game spends extra time looking specifically at nearby items during long wait. Might it be related to issues similar to #61380?

Ideally, I think, all identical items should stack, which would get rid of the problem. The code should work around that - handling cases like wielding a single plank from a stack as a weapon, using a single item as a tool instead a whole bunch, damaging single items instead of stacks, and all that. Right now it's the opposite - the players have to work around the limitations of the code. But that's not really sustainable with the way Cata is growing year after year with all the cool content.

**Comment by Zireael07** [comment]
I seem to remember issues requesting easy ways to destroy items (fireplace, shredder etc.), this might help with "naturally collected hoards"

**Comment by robotic-gamer** [comment]
no idea how the game handles crafting but one possible solution would be to create a data "cache" of where stuff probably is to use to craft from the perspective of a single tile. this could be designated by hand as a zone or be done automatically when starting crafting. by creating a cache the game could use it rather then recalculating from scratch. to keep the cache updated the game would need just need to edit it as items enter or leave the tiles seen from the tile crafting is done. what potentially makes this viable is how in long term bases players generally like to use the same specific tile.

on a related note shouldn't save file bloat not effect the speed the game runs for the most part because other then calculating zombie hoard movement it doesn't have to think about anything outside the reality bubble?
