### ISSUE TITLE
Unarmed Skill Learning Issues

### ISSUE THREAD

**Issue by fairyarmadillo** [CleverRaven/Cataclysm-DDA#61682]
### Describe the bug

There are currently several issues with training the unarmed skill in combat.

1) If you go around fighting barehanded, unarmed skill will train extremely slowly compared to how quickly weapon skills train if you use those. 30 unarmed attacks at 0 skill against a dummy got me to 3%, while the same number with a weapon in hand got me to 90% bashing. This was with a naked survivor with 8 in all stats, debug life support and HVAC, and starting with neutral morale and 100 focus both times. In both cases, I used No Style.

2) If you are wearing armor (such as gloves) which confers bonus damage, you train a weapon skill instead of unarmed. In this test I used a pair of chitinous gauntlets and saw zero improvement in my unarmed skill while my bash gained an entire rank. This does not happen if you use a mutation, such as Claws. In that case, you gain no cut experience and a very small amount of unarmed experience.

### Steps to reproduce

1) Make a survivor
2) Go punch something
3) Notice your unarmed training very slowly
4) go hit something with a stick
5) notice your bash training relatively quickly
6) put on some chitinous gauntlets and punch something
7) notice that your bash is training quickly and your unarmed is not moving at all

### Expected behavior

Unarmed skill should learn at a similar rate to other weapon skills, and fighting unarmed while wearing gloves should train unarmed, or possibly a mix of unarmed and whatever damage type the gloves are adding.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.2130 (21H1)
- Game Version: 07a9641 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by anoobindisguise** [comment]
I have also consistently found that it is literally impossible to train unarmed beyond a certain point unless you are wearing specifically scrap knuckles.

**Comment by Nandorianen** [comment]
Can confirm. After training all possible weapons skills to 3 through practice recipes and playing for a season, I've got dodging, bashing, cutting, handguns at 7+. Meanwhile unarmed is at 50% past 3, even though I try to use it the most.
At first I suspected that I just needed to punch more agile zombies to get any improvement (like with dodging). But other weapon skills keep improving on the same zombies. Also punching still drains focus (unlike dodging when it stops training). So yeah, it does improve, only it's way too slow.

**Comment by epsimpson** [comment]
The comment by anoobindisguise is very interesting, since it appears that scrap knuckles are the only "unarmed weapon" you can wield with Tiger Kung Fu and Zui Quan, the two I have now.  In fact, you can wear nail or skewer knuckles to get, and train, piercing damage, and wield scrap knuckles at the same time.

**Comment by Numbuh474** [comment]
I suspect that this is because scrap knuckles are the only unarmed weapons that actually have the `unarmed_weapon` flag.

**Comment by kevingranade** [comment]
Number one is not necessarally a problem.
Number two needs a root cause, if it's just a missing flag that's pretty easy to resolve.

**Comment by fairyarmadillo** [comment]
How is #1 not a problem? Shouldn't all attack skills learn at a reasonably similar rate, and isn't the disparity indicative of an error somewhere?

**Comment by Termineitor244** [comment]
I have personally went and tried to reproduce this bug... /Confirmed

1. The debug dummy monster gives less exp than, say, a normal zombie, both for unarmed and melee (I suppose because of its melee skill of 0), but even when using a normal zombie you can see a notable difference between the exp given by unarmed attacks and using a simple stick, a little too much difference in my opinion.

2. With respect of the unarmed weapons... Huh, I hadn't noticed until now, but you are right, using clothing with attack bonus (melee stats displayed on the item) give you 0 exp for unarmed, and all that exp for the type of damage that your, say, knuckles, are giving you as a bonus... The only exception being items with the [UNARMED_WEAPON](https://nornagon.github.io/cdda-guide/#/json_flag/UNARMED_WEAPON) flag, like the scrap knuckles, which give you the exp for unarmed.

Point number 1 is a personal opinion, but I don't see why training unarmed with real combat should be significantly more difficult (more dangerous yes, more difficult not) than training the proper usage of, say, a sword or sword type weapons.

Point number 2 is a fairly significant bug that I think should be resolved before stable or with a fix patch to stable after release.

With respect to the comments about how to use unarmed weapons... All previously wielded unarmed weapons were transformed into proper wielded weapons (Like the claws), or made into clothing/armor, with a new system in place for all clothing/armor to give bonus to unarmed attacks when wearing them.

About unarmed weapon listing in the martial art description window... I was the one that started converting all martial art weapons into weapon categories, I purposely did not include clothing/armor weapons since they are automatically accepted/used when you use an unarmed martial art, so it is irrelevant to list them when all your clothing can be used as an unarmed weapon (Though listing the more prominent ones in the martial arts menu could be useful, I need to think more about it).

Finally, the idea about placing the unarmed weapons (knuckles basically) in a different crafting listing from the rest is a good one, and it is something I would do in a next PR when I have the time.

As a final note for all uninformed about unarmed weapons... **You do not wield UNARMED WEAPONS, you are supposed to wear them and have your hands free (Do not wield anything)**

**Comment by epsimpson** [comment]
#54313 states that gloves should no longer have the UNARMED_WEAPON flag, and the flag is added temporarily when worn.  It sounds like that temporary flag has been disabled.

It also sounds like the permanent UNARMED_WEAPON flag should be eliminated altogether, and enforced by code (overridden when read in a json file).

The permanent UNARMED_WEAPON flag allows people to wield them and still fight and train "unarmed", which may be doing it wrong, but exploiting that bug was also the only way to increase unarmed damage with better gloves and still gain unarmed experience.  

The permanent UNARMED_WEAPON flag on a held glove may also be the source of bug #61527.

**Comment by Termineitor244** [comment]
AND.... I found it! The problem is with the deletion of the temporal UNARMED_WEAPON flag from the code of melee.cpp when the attack vectors was first introduced, since this flag is the one used to determine in the skill training checks if you train unarmed or an specific damage type skill...

The temporal flag was first introduced in #41209 to make worn gloves count as unarmed weapons for damage bonuses (And skill checks) by @CodeBandit, but was removed with the introduction of attack vectors in #53954 by @Hymore246, attack vectors allow you to receive the bonuses from your worn items in the same way that the temporal flag did, but it does not help with the skill training check that still searches for the UNARMED_WEAPON flag...

I think I can try to resolve this issue today... I will try at the very least.

**Comment by MedievalYeetMachine** [comment]
Seems to still be an issue as of experimental 01-16-0659. Here's 2 problems i found:

1. Wearing hard gloves raises bashing weapons skill (tested chitin and steel mitten gauntlets), soft ones seem to raise unarmed(tested work gloves).
2. Unarmed combat drains focus significantly slower then armed, resulting in way slower xp gain. And even after expending the same amount of focus unarmed skill seems to receive around half the xp bashing gets. 

_*Testing on dummies. Going from 100 to 83 focus took 10 hits with a pipe (1 kill + ~half hp), to do the same unarmed took 23 kills._
While unarmed gaining less xp/focus could be intentional, to bring it in line with melee skill, as it unlocks new MA techniques(at least such reason seems logical), unarmed draining focus a dozen times slower seems to be a bug.
