### ISSUE TITLE
in progress craft disappeared when trying to wield it 

### ISSUE THREAD

**Issue by Warfoniusz** [CleverRaven/Cataclysm-DDA#61724]
### Describe the bug

My character has a splint on his left arm, and I was crafting a survivor duster (it was around 1/4 done).
It left it on the counter when it got too dark, after the lights came back up I tried to (a)ctivate it when it was still on the counter, but the game said that I'm too weak to wield it with one hand.
I dropped my backpack (thought that maybe I carry too much weight on me), tried to wield it and got an error message, which made the craft disappear.

### Steps to reproduce

1. Be unable to wield a craft due to being too weak while having a broken, splinted arm
2. Drop some weight so it allows you to wield it
3. Try to wield the craft

### Expected behavior

I'm not sure what should've happened, except for the game still not letting me wield the craft.

### Versions and configuration

cdda-windows-tiles-x64-2022-10-14-1116

**Comment by PatrikLundell** [comment]
Some items, including in-progress crafts require that both hands are available in order to wield them, and your broken arm knocks out one of the hands.

As far as I've been told (haven't tried it myself yet) the best option is to place the item on top of a work bench, with the second best one is to mark the tile as a crafting zone. You're supposed to be able to resume crafts located in these places without picking them up.
