### ISSUE TITLE
Cant repair broken items

### ISSUE THREAD

**Issue by KHeket** [CleverRaven/Cataclysm-DDA#61756]
### Describe the bug

There is uniqe item called NRE recorder for hub 01 quest. I went with hub mercenary to complite the quest "active noise controle" and electric monsters detroyed my smartphone, mp3 and nre recorder, so I cant abtain the last one no more. And some players can have valuable information on smatrones, like photos or saved books, so there need a way to repair this items, or at least a way to obtain nre recorder from hub, or craft it may be

### Steps to reproduce

Spawn nre recorder and trow mpe grenade into it
See, how uniqe item breaking and you cant obtain another one workable no more

### Expected behavior

Ability to repair broken items or obtain/craft nre recorder after breaking/somehow protect items from damaging like insulating container, or make nre recorder immune to emp blasts

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2130 (21H2)
- Game Version: fa069f8 [64-bit]
- Graphics Version: Tiles
- Game Language: Системный язык []
- Mods loaded: [
    Тёмные Дни Впереди [dda],
    Отключить потребности у НПС [no_npc_food],
    Без роста фунгалоидов [no_fungal_growth],
    Бионические профессии [package_bionic_professions]
]

**Comment by Sammmmm** [comment]
Had the same issue from electricity damage from the same quest.  Was a bit dismayed to find out I couldn't repair the electronics I had on me at the time.

**Comment by Night-Pryanik** [comment]
NRE is now EMP-proof and can be taken again from questgiver if needed thanks to #61811.

**Comment by Raikiri** [comment]
Excuse me, my NRE recorder still broke from a random electric attack, so looks like the fix in #61811 did not work. I also think that the problem is more related to broken state of items that's irreversible rather than to properties of NRE recorders. I think it's really a priority to make the "broken" status reversible because losing all data from a smart phone from a random attack without a way to shield it is just not fun.
