### ISSUE TITLE
Invalid recipe id "scrap_aluminum" on world load

### ISSUE THREAD

**Issue by RundownRhino** [CleverRaven/Cataclysm-DDA#61808]
### Describe the bug

After updating to latest build (`c837fff`), getting this on world load:
```
 DEBUG    : invalid recipe id "scrap_aluminum"

 FUNCTION : obj
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\recipe_dictionary.cpp
 LINE     : 67
 VERSION  : c837fff
```
If I skip it and load the world, everything seems to work fine and the error doesn't reappear on future loads.

### Steps to reproduce

1. Update to latest (`c837fff`) experimental.
2. Attempt to load an old world (mine was created about two weeks worth of builds ago).

### Expected behavior

Even though it only appears once, it would be nice if it didn't happen at all.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2006 (21H2)
- Game Version: c837fff [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

Presumably caused by #61203, since it changed a lot of aluminium-related stuff and got merged yesterday.
Got told on the discord it's worth opening an issue for that even if it turns out to be harmless.

**Comment by snipercup** [comment]
I've seen this too when loading my game

**Comment by Karol1223** [comment]
Hey, so as the author of the aluminum PRs I'll come here and say: yes, I do remember this. I ran into this while making a PR but ended up paying no mind to it as when I tried to check how I could fix it, the error never appeared again. The most likely cause is because the recipe the game considers 'scrap_aluminum' no longer exists as it had an id suffix added and is now 'scrap_aluminum_assorted_scrap' (or whatever way the game adds suffixes, they keep confusing me). I am just about sure this is harmless, will happen only once when updating, and is, frankly, not fixable now that said PR got merged anyway. I'll take the blame as I should have realized the fault prior to submitting the PR as ready.
