### ISSUE TITLE
Water consumption seems way too high (or ambient heat is too high)

### ISSUE THREAD

**Issue by TieSKey** [CleverRaven/Cataclysm-DDA#61854]
### Describe the bug

On a summer day, with an almost naked character (boots, socks and a belt), temp gets to warm and if crafting it can get to overheating. I'm guessing this is affecting thirst since the character gets dehydrated and needs to drink several litters of water through the day.

### Steps to reproduce

1. Make a character and set the date to say summer 60.
2. Have it craft something (I was crafting mutagen).
3. Observe how water consumed to keep dehydration at check amounts to several liters (more than 5).

### Expected behavior

Either temps should be lower or water needed should be lower. Drinking more than 5 liters on just an average summer day while almost naked seems a little excessive. 

Maybe it is the perspiration system that's incomplete and while it drains water is fails to lower temps so it keeps draining and draining?

### Versions and configuration

Build 2022-10-11-1637

**Comment by Fris0uman** [comment]
CDC seems to suggest 1L per hour when it's hot <https://www.cdc.gov/niosh/mining/UserFiles/works/pdfs/2017-126.pdf>

**Comment by TieSKey** [comment]
Mmmm problem is, what is "hot"? Sahara hot? New England US region hot? Siberia hot?
If "cooking" while being naked on a summer day makes you need several liters of water (almost more water than what u can digest in that time), something smells weird.

Again, maybe the problem is the temps being way to high and not the hydration, can't be sure. Reaching "overheated" status just from that activity above smells funny too. By that standards every person without AC in summer is 20 minutes of light activity away of heat stroke and dehydration.

Btw, what is the "unit" for temp displayed in player status? it's ranges are somewhat compatible with C degrees but if that's the case then the ambient temp of that day was 54C (checked with debug) which is truly Sahara level.

**Comment by RAldrich** [comment]
There are two complex systems interacting here. The temperature code is extensive. Most of what you're looking for is in character_body.cpp

It takes into account all sorts of stuff: solar irradiance given the sun angle, the weather, windchill (based on air pressure changes), evaporation of water or sweat. Body temperature values use an arbitrary scale, not Celsius. The value displayed in the body screen is a different scale, also arbitrary and also not Celsius (I don't know why this decision was made).

The important part is the temperature conditions: "Warm, Hot, Scorching" that show up on your various body parts. Those are what make you sweat.

Sweating is defined in `effects.json`

```
 "type": "effect_type",
    "id": "hot",
    "name": [ "Warm", "Hot", "Scorching" ],
    "desc": [ "Your %s feels warm.", "Your %s is hot.", "Your %s is burning up!" ],
    "max_intensity": 3,
    "part_descs": true,
    "base_mods": {
      "//": "thirst is ml / 5 someone doing exercise in the sun burns between 500mL to 1000mL extra an hour as sweat so 1.5 thirst a minute split between 10 body parts",
      "thirst_min": [ 1 ],
      "thirst_tick": [ 60 ],
      "thirst_chance": [ 6 ],
      "perspiration_min": [ 2 ],
      "perspiration_tick": [ 60 ],
      "perspiration_chance": [ 1 ],
      "pain_min": [ 1 ],
      "pain_chance": [ 2 ],
      "pain_max_val": [ -1 ],
      "hurt_min": [ 1 ],
      "hurt_chance": [ -300 ],
      "stamina_chance": [ 2 ]
    },
    "scaling_mods": {
      "thirst_min": [ 1 ],
      "perspiration_min": [ 5 ],
      "perspiration_tick": [ -15 ],
      "pain_max_val": [ 10 ],
      "hurt_chance": [ 200 ],
      "stamina_min": [ -1 ]
    }
```

So this json may be the best place to tweak values.

A warning - tweaking the sweat values is complicated, effected by mutations and body part size, and because evaporation cools you, you could end up changing your ability to thermoregulate. Tweaking just the thirst values seems a bit safer.

**Comment by macrosblackd** [comment]
It seems to me that the issue stems from the fact that being hot is directly consuming water, which if I'm not mistaken, was put in place to simulate perspiration. Now that we have a system to handle perspiration, we should probably look at removing the old simulation of being hot = consume more water, provided that the perspiration system is correctly consuming water.

**Comment by RAldrich** [comment]
I'm not sure I follow you - the effects.json snippet I included above, where the "Warm", "Hot", "Scorching" states are increasing thirst, that IS the perspiration system.

If there is another place where your body temperature is effecting thirst values, I am unaware of it. Could you point me at it?

**Comment by macrosblackd** [comment]
I've only just started playing again after a looong break, but does the perspiration system itself not affect thirst? If not, then just rebalancing the water values is fine, but if it IS affecting thirst, then that would be double-dipping, since the thirst changes from Warm, Hot, Scorching are meant to simulate perspiration (before we had Perspiration).

**Comment by RAldrich** [comment]
There is no separate perspiration system. It cannot be double dipping, because it does not exist. Both perspiration and thirst from perspiring are part of the "Warm", "Hot", "Scorching" effects.

From above:
```
"thirst_min": [ 1 ],
"thirst_tick": [ 60 ],
"thirst_chance": [ 6 ],
"perspiration_min": [ 2 ],
"perspiration_tick": [ 60 ],
"perspiration_chance": [ 1 ],
```

These are decoupled. Increasing the perspiration values will not effect thirst. Increasing the thirst values will not effect perspiration. You can change one or both to tweak the game balance of how dehydrating the act of sweating is.
