### ISSUE TITLE
Crafting salted meat slices with... black gunpowder

### ISSUE THREAD

**Issue by NotSeawhite** [CleverRaven/Cataclysm-DDA#61873]
### Describe the bug

I can somehow make salted meat slices with gunpowders.

### Steps to reproduce

• Find `salted meat slices` in crafting menu
• Observe the `black gunpowder`

### Expected behavior

Not... using the black gunpowder as salt.

### Screenshots

![20221023_092951](https://user-images.githubusercontent.com/52661206/197368314-75e313f4-57ad-484c-9dbb-9881e5e26b72.jpg)

### Versions and configuration

- Game Version: 26a4725 [64-bit]
- Graphics Version: Tiles

**Comment by robotic-gamer** [comment]
I don't think this is a bug, I think its there under the idea of using it as impure saltpeter, that and the saltpeter can be easily separated from the other parts of black gunpowder due to saltpeter being the only water soluble component.

**Comment by TheShadowFerret** [comment]
>Allow using blackpowder for food preservation, due to saltpeter content and other ingredients (sulfur and charcoal) being non-toxic. Amount of blackpowder used is set so that it's never more efficient to make blackpowder from saltpeter first if you want to use less ingredients overall.

#45611

**Comment by NotSeawhite** [comment]
Ah I got it. But wouldn't those require some knowledge? Consuming black powders straight away doesn't sound like a good idea.

**Comment by robotic-gamer** [comment]
> Ah I got it. But wouldn't those require some knowledge? Consuming black powders straight away doesn't sound like a good idea.

not really, the nature/properties of black powder would becomes fairly obvious when the player has some on hand.  all that is assumed is the player knows that sulfur and charcoal are non-toxic. charcoal is fairly obviously non-toxic because of activated charcoal usage in treating poisonings. sulfur can be deduced to being non-toxic due to it not being water soluble (and hence can't be absorbed into the body) and the lack of chemical reactions to the things in the digestive tract that would make it toxic.

**Comment by ZhilkinSerg** [comment]
Works as intended per https://github.com/CleverRaven/Cataclysm-DDA/pull/45611
