### ISSUE TITLE
Adding Ranged Enchantments

### ISSUE THREAD

**Issue by Computer-Engineer-Man** [CleverRaven/Cataclysm-DDA#61871]
### Is your feature request related to a problem? Please describe.

As is, there are enchants to enhance melee damage a variety of ways. I don't see why there shouldn't be enchants related to ranged values. Specifically just from looking at the items ingame the following would be quite useful enchants: ranged damage, aim speed, ranged pierce, critical multiplier, loudness, reload time, etc.

### Solution you would like.

Having ranged values, such as the ones mentioned above, be able to be modified via enchants. 

### Describe alternatives you have considered.

None that I could come up with.

### Additional context

This came up when talking about the nature bow spell for magiclysm after I was considering trying to implement #60435. Having an enchant for natures bow based on your current strength to enhance the bow damage would make sense because natures bow is summoning a bow that is compatible for you.

**Comment by Kywi001** [comment]
There are mods, ammo types and cbms that does that already, and if you want some really fancy gun, there's the gun show Kord and Hub 01's HWP (this one even allows you to mod different types of barrel that accepts different types of ammos).

As for the said magic bow,  you can just implement the same system the composite bows has, where you set it up for low, normal and high that takes less or more of the usual str requirements and does less or more of the normal composite bow dmg.

**Comment by Computer-Engineer-Man** [comment]
I am very curious about what CBM's actually increase ranged damage, after a quick search I couldn't find any, can you list them? 

Regarding making several items with varying strength requirements that was actually the original idea but I feel like rather than having three or four items, one item and one enchantment would be more useful. 

Enchantments would allow for a lot more potential in mods at least. Imagine having 5 or 10 items you want to scale with the player, the current solution is to just triple or quadruple the amount of items with different benchmarks for each item.

**Comment by Kywi001** [comment]
> I am very curious about what CBM's actually increase ranged damage, after a quick search I couldn't find any, can you list them?

There's none, damage depends on the ammo type and gun used, 
unless we get a spell that allow us to materialize a specialized bullet with more damage.

> Enchantments would allow for a lot more potential in mods at least. Imagine having 5 or 10 items you want to scale with the player, the current solution is to just triple or quadruple the amount of items with different benchmarks for each item.

In vanilla, guns are absolutely fine as is, as theyre built for the core gameplay unlike for example, magiclysm where it is balanced around having way way more stats than normal, if you want guns on magiclysm you will end up either dropping them entirely for better spells or using explosives.

While I do think that enchantments on guns is not a good idea for vanilla since we already can improve them using mods, ammo type and cbms,
It is a good idea as a mod to have them still be useful on stuffs with insane difficulty scaling like magiclysm.

I personally don't think anyone would approve of this as a vanilla addition, but you can always try to make a mod for yourself (and it may get included in the game), you may try to take a look on the XEDRA mod spells and make a summonable mods/bullets/guns with better stats than normal.

**Comment by Computer-Engineer-Man** [comment]
I'm primarily thinking of bows versus guns but you make a very good point regarding it not being vanilla friendly. I still think if there are melee enchantments based on melee item attack speed, damage, cost, etc. then it would logically make sense to include ranged enchantments with similar effects. For now I'll close it as the simple reason it does not fit in with vanilla is a valid enough one for me.
