### ISSUE TITLE
excessively large byproduct when making baking soda

### ISSUE THREAD

**Issue by robotic-gamer** [CleverRaven/Cataclysm-DDA#61874]
### Describe the bug

the crafting recipe for baking soda seems to produce far too much quicklime (see screen shot). mass wise for crafting 1 unit the washing soda and limestone combined weigh 0.21kg. by comparison the quicklime weighs 6kg so the recipe clearly seems to be creating a very large amount of calcium from thin air.

### Steps to reproduce

look up the recipe

### Expected behavior

the recipe producing material at a net loss of material relative to the materials inputed.

### Screenshots

![image](https://user-images.githubusercontent.com/78816055/197368837-683dd02b-3631-4d1f-bb64-bd79548edb8f.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2130 (21H2)
- Game Version: 26a4725 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Xedra Evolved [xedra_evolved],
    No Hope [no_hope],
    Aftershock [aftershock],
    Bionic Slots [cbm_slots],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by RenechCDDA** [comment]
/confirmed

Baking soda is turning 8 limestone into 400 quicklime.

Quicklime recipe is turning 50 limestone into 50 quicklime.

This is because quicklime is defined as having a default `count` of 50. 

Baking soda recipe needs to be defined as in JSON_INFO.md

`"byproduct_group": [         // Optional (default: empty). Same as above, but using item group definitions.
  { "item": "item_id_1", "count": [ 1, 4 ] },
  { "item": "item_id_2", "charges": [ 8, 15 ] },`

Set the count/charges to the desired output (presumably 8). 

The following recipes also seem to be affected:

chem_washing_soda, budget_steel_chunk, budget_steel_lump, cotton_ball, cotton_ball_spinningwheel, cotton_ball_by_hand, 

Just took a quick check through the CHEM and OTHER category. Maybe there are other recipes hiding.

**Comment by RenechCDDA** [comment]
Okay, after trying to work on this on my own I've found there's some problems. Items defined in byproduct groups seem to be doubled, they always spawn in default container (no option to specify and it doesn't call/check for the usual item group json which specifies), and some weird stuff with setting ammo.

So, please don't start working using previous comment without being aware that my proposal *doesn't actually work*.
