### ISSUE TITLE
increase stomach digest speed for few trait and different water digesting time

### ISSUE THREAD

**Issue by blablase** [CleverRaven/Cataclysm-DDA#61883]
### Is your feature request related to a problem? Please describe.

using trait fast metabolism and metabolic intercharge make you in a constain state of hunger which also make you thirstier while you have no space in your stomach to intake food or water which led to underfed and thirsty

### Solution you would like.

![image](https://user-images.githubusercontent.com/63102395/197386711-3b0891c1-b14d-4254-83b3-b18a7ab5aa29.png)
![image](https://user-images.githubusercontent.com/63102395/197386753-ece56161-74a3-4efa-9471-5a1f704a7efe.png)

increase food digestion time corresponding to the character trait or maybe it's bionic
and a different water digestion speed

**Comment by Kywi001** [comment]
To be honest, who would install a cbm that makes you even more hungrier when youre already always hungry? That's just a player issue at this point

**Comment by anoobindisguise** [comment]
I recall looking into this wanting to make the expanded digestive cbm digest food faster and found that metabolism actually does speed up digestion, fwiw.

**Comment by blablase** [comment]
> To be honest, who would install a cbm that makes you even more hungrier when youre already always hungry? That's just a player issue at this point

what i meant is increase food digestion time for that not a " cbm that makes you even more hungrier" ofc its a player issue but what i want here i can shove all the food i required because duh think about real life metabolism it make your digestion faster so why cant the logic goes to the cbm it self

**Comment by Kywi001** [comment]
> what i want is increase food digestion time for that not a " who would install a cbm that makes you even more hungrier" ofc its a player issue but what i want here i can shove all the food i required because, duh just think about real life metabolism it make your digestion faster so why cant the logic goes to the cbm it self

This is why you check the volume of the food you eat, if you're lacking in calories, you eat low volume high calorie food like condensed milk, maple syrups and/or other 0.02L foods with high calorie density, you can easily eat 50 maple syrups and gain a minimum of 5k calorie in 1 sittings and still can fit another 50 more maple syrups, instead of eating, lets say, sandwiches where you only get to eat 2 to 4 portions and be full instantly only giving you tops of 5k calories.

 if you're lacking in nutritions, you intake vitamins.
