### ISSUE TITLE
Sweating should inform the player.

### ISSUE THREAD

**Issue by Stone94** [CleverRaven/Cataclysm-DDA#61891]
### Is your feature request related to a problem? Please describe.

Currently the game doesn't notify the player when they are starting to sweat, leaving some players getting dehydrated and dying, or confused and frustrated. When the player starts to sweat it will show up in the @ character menu as a wetness modifier but doesn't tell you what is causing the the moisture buildup.

### Solution you would like.

There should be a message logged that the player is starting to sweat or sweating, or a prompt when major sweating occurs resulting in increased water loss.

### Describe alternatives you have considered.

ignoring the issue.

### Additional context

Will look into adding a fix myself tomorrow, but if anyone else wishes to fix it all the power to you.

**Comment by PatrikLundell** [comment]
The log gets spammed by messages about limbs getting warm, so any solution should not just add additional spam, but rather make sure heating and sweating messaging is handled together somehow. Note that you'd want warnings about getting hot from passing by a fire at a distance you thought was safe has to be clear that you're heating up, not just sweating a little.

**Comment by RAldrich** [comment]
Somewhat related to #61854

Body part heat status ("Warm", "Hot", "Scorching") is literally, in-code the thing that causes you to sweat. Any message about sweating will therefore be 100% redundant with messages about how you're heating up.

I'm wondering if a more elegant (if perhaps more difficult to implement) solution would be to create a "sweat" fluid type, distinct from water (which is what's used to model sweat right now), so that the body graph could display "[sweaty]" instead of "[wet]".

We'd have to figure out a variety of interactions including things like: "what happens when you go swimming while sweaty?" I can imagine tying that into the morale system so that being dirty and sweaty is bad for morale, relative to being wet from a dip in the lake. There would be a lot of edge-cases to iron out though.

**Comment by Kywi001** [comment]
Having the sweat status would be nice for a squeamish character getting negative morale value with varrying levels of sweat.

This would also be a good time to add "taking a bath" using a soap, bathtub or shower or "splash water to self" on a pond, a large water bottle or a few water bottles full of clean water.

Taking a bath or splashing water on self should remove varrying levels of sweat and replace them with wet status that you can use a towel or other cloth material to dry yourself.

With this in mind, sweat status should also increase scent trail production as an added negative and taking a bath reduces scent trail production for a few hours or until you sweat again as an added bonus.

**Comment by Zireael07** [comment]
@Kywi001 Bath/soap has been proposed several times but rejected because it only adds tedium.

Increasing/decreasing scent based on how sweaty you are has also been shot down several times.

**Comment by PatrikLundell** [comment]
As a bit of a tangent, it would be useful if entering water would actually work to cool you down, as there isn't really anything you can do to combat overheating (and there's nothing more to take off when overheating while naked). Neither vehicle magic nor basements are available everywhere.

**Comment by RAldrich** [comment]
Standing in water is definitely supposed to replace the air temperature with the water temperature. Unless I misread the code and that's only when fully submerged. I'll check later.

Thank you for the historical context around soap and bathing. I agree that it could be super tedious.

I think the ability to perspire a fluid other than water could still be very useful, both as UI quality of life thing (so the body graph could make it clear **why** you're wet), and as something mutations could use (sweat slime, or honeydew, or whatever).
