### ISSUE TITLE
Faraday Chainmail Suit is uncomfortable

### ISSUE THREAD

**Issue by AcidAntOnAMinefield** [CleverRaven/Cataclysm-DDA#61910]
### Describe the bug

I crafted a Faraday Chainmail Suit. Apparently it is so uncomfortable, that it is rubbing "uncomfortably" against my characters every single centimeter of being. (See attached screenshot). 

I can understand why it would be somewhat uncomfortable, but this should not be *this* uncomfortable, as this piece of armour, by itself, requires over 200 patches of cotton to craft. It should be, at least, comfortable around the head (including eyes, mouth, ears, lips, nose, chin, moustache, beard, neck, etc), considering there really aren't "Non-Winter" soft clothing alternatives to most of these parts. 

In fact, there are barely any pieces of equipment that are cool enough for the character to wear underneath "hard" equipment in the (questionably broken) game's Summer weather, as even 5 warmth for a pair of hand rags is enough to make your character go crazy and shrivel into a human-shaped raisin in mere hours. 

### Steps to reproduce

1. Spawn a basic survivor;
2. Spawn a Faraday Chainmail Suit (fits);
3. Wear the Faraday Chainmail Suit.
4. Read the 30 lines about how the armour rubs uncomfortably against (specifically) your right finger, your eye lobes, your lips, your ears, and every single existing body part your character may still have available);

For 2 and 3, you can also Spawn an army helmet and a fursuit of sorts (e.g. Dinosaur Suit), and observe that you will wear the army helmet *underneath* the Faraday suit and feel "okay" about it. The same is true about any fursuit: you will essentially be "very comfortable" with the Faraday Suit over it - just disregard that you are overheating and are somewhat encumbered.

### Expected behavior

Considering what was previously mentioned about the armour requiring Cotton to be crafted, most of it should actually be comfortable enough to wear in most places. 

If anything, at least having more 0-warmth alternatives to wear underneath the hard equipment would be welcomed (or reducing the warmth levels of currently existing basic clothes). 

### Screenshots

https://cdn.discordapp.com/attachments/518535867715944448/1034177974435594240/unknown.png

### Versions and configuration

- Windows
- e532171 (2022-10-22-1425)
- Tiles
- English

Mods
- dda

no other mods relevant in terms of items additions/changes/removals

**Comment by Aerin-of-the-Toast** [comment]
It could be given the "PADDED" flag, but it seems the recipe is a mess in the first place. It requires a layer of rubber (which is present in the suits defensive values) but no rubber is present in the recipe. And in the other hand, no cotton or nomex is present in the item despite the recipe requiring one. 

The recipe (and the warmth) of the item needs an audit; it would probably make the most sense to make it out of a hazmat suit +chainmail since hand-crafting a fully rubber suit by hand sounds pretty ludicrous. Then the warmth should be increased to be the same as the hazmat suit (40) since there's no way on earth a full rubber suit wouldn't be extremely hot to wear. Then it can probably be given the PADDED flag, since the rubber layer would count there. 

Maybe the version made from a hazmat suit can be separate from the regular purpose-built Faraday cages (if they spawn anywhere) since a hazmat is probably bulkier and hotter than needed, so a "real" Faraday cage suit could be a bit better in that regard (but not 0 warmth lol).

**Comment by AcidAntOnAMinefield** [comment]
There is rubber in the recipe: Rubber boots, but yeah I agree it's... a silly recipe that has suffered a lot of indirect changes due to changes to systems related to it in-game. 

This particular armour was such an easily exploitable item before the whole breathability thing and the "mandatory layering of clothes" became a thing, it is honestly ridiculous it lasted so many years without being massively nerfed or outright removed. It's probably one of those items that could easily be done away with entirely - or make it so "Faraday Cage Suits" spawn in specific POIs, but nowhere near as "good" protection wise as this is.

**Comment by AcidAntOnAMinefield** [comment]
Reopening / bumping this, if nothing happens, then will open a new issue instead. 

There still are no "soft" things to wear on the eyes. Which makes the Faraday Chainmail Suit essentially unwearable because of it being "uncomfortable". In fact, there are very much no soft things one can wear under this piece of equipment that doesn't lead to the player to suffer from overheating in the summer. 

https://github.com/CleverRaven/Cataclysm-DDA/pull/61066 fixed a few things and makes this piece somewhat worth having again, but at the same time, it is impossible to wear due to the unreasonable debuffs it offers:

a. -2 speed per limb = -24% if you have nothing soft under it. You will always have the penalties on the eyes;

b. "const.: pain." on all of them. On the @ menu all of this shows under "effects."
"Your eyes is uncomfortable. Wearing something soft under your hard armour would help."
