### ISSUE TITLE
Regression in AIM functionality (move all)

### ISSUE THREAD

**Issue by tivec** [CleverRaven/Cataclysm-DDA#61922]
### Describe the bug

When one pane is selected as All and the other is set to any other tile, using the move all functionality will repeatedly spit out the message "No eligible items found to be moved". Spoke to @RenechCDDA about this on the Discord, and we believe it stems from a change in #61839.

### Steps to reproduce

One pane set to All, one pane set to elsewhere, hit the keybind for move all. Message is shown repeatedly.

### Expected behavior

Items should move properly.

### Screenshots

https://user-images.githubusercontent.com/717574/197829939-25533a05-ca48-433c-8412-b4ea791e91bb.mp4

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22000.1098 (21H2)
- Game Version: d7a8a9b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    No Fungal Growth [no_fungal_growth],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations],
    Megafauna [megafauna],
    DinoMod [DinoMod]
]

**Comment by RenechCDDA** [comment]
I now realize the reason it was silently failing is because it iterates over all 9 adjacent tiles and calls liquid_items each time when [A] is the source. Without the popup it just processes without notice, with the pop-up it pops up anywhere from 0-8 times depending on how many tiles are empty. Deleting the pop-up is a simple fix but if we want to retain the added functionality and not silently fail a move all on the player it needs to iterate differently.

Interesting edge case. It's always novel to find something you totally didn't expect in testing.
