### ISSUE TITLE
Magiclysm crystallized_mana generates Zero weight error despite ZERO_WEIGHT flag

### ISSUE THREAD

**Issue by Knut-Aage-Hofseth** [CleverRaven/Cataclysm-DDA#61980]
### Describe the bug

 DEBUG    : Item 'crystallized mana' with zero weight

 FUNCTION : int item::charges_per_weight(const mass&) const
 FILE     : src/item.cpp
 LINE     : 1227
 VERSION  : 41acb30

### Steps to reproduce

Spawn in crystallized mana with debug menu.

Drop on floor.

Pick up.

Read error message.

### Expected behavior

I expect to be able to pick the item up without an error message as the item has the ZERO_WEIGHT flag.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.674 (22H2)
- Game Version: 41acb30 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm]
]

### Additional context

 DEBUG    : Item 'crystallized mana' with zero weight

 FUNCTION : int item::charges_per_weight(const mass&) const
 FILE     : src/item.cpp
 LINE     : 1227
 VERSION  : 41acb30

**Comment by RenechCDDA** [comment]
/confirmed

item::charges_per_weight doesn't check the flag. Although looking at the code... crystallized mana should probably just get a very (VERY) small weight. 0 weight ends up returning `INFINITE_CHARGES`, aka 2147483647 (the maximum for a 32-bit signed integer). I'm not sure this has any gameplay effects but it'd certainly be easier to give this crystallized mana negligible weight (it already has volume!) instead of letting it break something down the line.
