### ISSUE TITLE
Brochures or pamphlets in mailboxes

### ISSUE THREAD

**Issue by Hansendiet** [CleverRaven/Cataclysm-DDA#62066]
### Is your feature request related to a problem? Please describe.

I think that mailbox spawntables could use a bit of a redo. There are currently mostly newspaper pages, flyers, letters and postcards in there, which is perfectly fine, I just think there could be a little more.

### Solution you would like.

Adding advertising brochures/pamphlets for local restaurants, supermarkets, museums or even malls would lead to alot more variety. These pamphlets and brochures could even reveal the map and mark the respective buildings. I also think that these would be a better fit than tourist or trail guides thematically.

One could maybe even add little brochure stands to doctors offices or subway entrances.

### Describe alternatives you have considered.

Leaving it as is, but what can I say, I am passionate for mailboxes.

**Comment by AcidAntOnAMinefield** [comment]
Having each pamphlet being its own thing instead of being a "generic item name" with different descriptions would be fun too, for flavour. For instance:
- the character sheets are all different items (ie they don't stack if they're different), but the newspaper pages and the fliers all stack even when they're completely different text. (I think the survivor notes do as well);
- It would also be nice if we could scan them into the Tablet PC/Phone but that's probably a different kettle of fish.
