### ISSUE TITLE
Allow recipes to be unlocked by Proficiency

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#62123]
### Is your feature request related to a problem? Please describe.

As far as I know, recipes are either learned automatically as a skill level is reached, or through the usage of a book containing the recipe. I believe it would make sense to also allow recipes to be unlocked by learning Proficiencies. Once you're skilled enough at a Proficiency you ought to be able to figure out how to make new items, This would provide a "research light" path of recipe acquisition.

### Solution you would like.

Support an additional field in recipes that would work in parallel with "book_learn" called e.g. "proficiency_learn" that would take a list of proficiencies that would unlock the recipe, which might happen in parallel with both learning it from a book and learning it through the gaining of a skill level.

Note that it wouldn't affect usage of the recipe in any way, just whether you know about it.

### Describe alternatives you have considered.

- Complicate things further by allowing proficiency unlocking to be combined with level unlocking such that you'd have to both learn the proficiency and reach a sufficient level of the primary skill to unlock the recipe. Personally I'd rather have recipes I can't craft show up when appropriate knowledge is gained so I know what to strive for, rather that blindly flailing about trying to increase "random" skills trying to guess what you're looking for may be hidden away, as that may not be obvious (fabrication/applied science/tailoring/mechanics? The one you guessed may well be set as a secondary skill).
- Develop a recipe research functionality where you may gain knowledge of the existence of recipes, but have to experiment to figure out how to make the item unless you have a teacher (such as e.g. a book with the recipe written down). The existence of a recipe might be unlocked by a skill or proficiency, but the usage of the recipe would be blocked until the full recipe is known, which could be done through experimentation (ideally with the possibility of catastrophic failure), or by an optional surpassing of the knowledge skill level with sufficient additional levels. The problem here is coming up with a default system of experiment resource consumption that makes sufficient sense to not have to be overridden for every recipe individually.

### Additional context

This would be particularly useful to the Innawood mod, given the lack of recipe books in that mod, but would also reduce the penalty for being illiterate but resourceful and patient in the base game. You can get more recipes, but it will take more work.

**Comment by Profugo-Barbatus** [comment]
I'm not sure I like this idea at first glance - It would have to be applied sparingly, otherwise its going to turn proficiencies from early crafting penalties/skilled bonuses, to mandates of X hours of practice first. As it stands, I unlock the recipe to craft something with closures before mastering closures, and can then learn it by just trying to make things, over the practice action alone. With this change, I would first have to practice closures to 100%, then I'd unlock the recipes that use closures, *then* I could make the shirt. Its replacing the either/or choice with "You must do X".

If it is applied sparringly, then outside of maybe the most advanced skills, I'd worry it'd degrade into arguing why one recipe using the proficiency is autolearn, and why another is masters only, for a lot of recipes.

I'm ambivalent to the idea of a research/tech unlock process as a whole for recipes, it feels like it'd be just as arbitrary as our current process, but with more steps.

**Comment by PatrikLundell** [comment]
Note that I do not propose the removal of the main route of recipe access, namely via books. It's intended to provide an alternative route to finding the elusive book(s) you're looking for, in addition to providing a route at all for when you don't have/are able to use books.

Research would similarly be applied when you don't have a ready recipe, such as e.g. adaptations to mutant anatomy, and would be bypassed by sufficient general skill even then.
You're unlikely to find any real world books with recipes for e.g. pants adapted to having a tail, and even if you did, I wouldn't want to rely on it being designed by someone actually skilled enough to do it properly (rather than some tail enthusiastic amateur), or adapted to the kind of tail at hand (fluffy horse tail/long thin tiger tail/think lizard tail...).

Another case of a use for recipe development might be the usage of outdated processes.
