### ISSUE TITLE
Arithmetic Percent Problem

### ISSUE THREAD

**Issue by Computer-Engineer-Man** [CleverRaven/Cataclysm-DDA#62133]
### Is your feature request related to a problem? Please describe.

Let me tell you an issue with arithmetic, due to how it can only take integers, this means you cannot easily get a percent of something. 
Imagine you go "I want to get 90 percent of this thing", due to how arithmetic currently exists you need to multiply it by 90 and then divide by 100. 
This means you need two arithmetic to get the percent and three minimum if you want to use it meaningfully. 
In additional context I have provided the finalized arithmetic to get a percent of something.

### Solution you would like.

Having a "percent" and maybe "percent=" or something along those lines in order to quickly do percents with arithmetic. Something like this.

{ "arithmetic": [ { "u_val": "vitamin", "name": "impurities" }, "=", { "arithmetic": [ { "u_val": "var", "var_name": "impurities_soft_cap" }, "percent", { "const": 90 } ] } ] }

Or if you wanted to simply set impurities to 45 percent.

{ "arithmetic": [ { "u_val": "vitamin", "name": "impurities" }, "percent=", { "const": 45 } ] }

### Describe alternatives you have considered.

Having a tool to make the arithmetic functions by being given just a formula.

### Additional context

In the line below I am setting impurities equal to 90% soft cap of impurities. As you can see, it is not pretty.

{ "arithmetic": [ { "u_val": "vitamin", "name": "impurities" }, "=", { "arithmetic": [ { "arithmetic": [ { "u_val": "var", "var_name": "impurities_soft_cap"}, "*", { "const": 90 } ] }, "/", { "const": 100 } ] } ] }

**Comment by andrei8l** [comment]
No need to make it that complicated. We could add `percent` as a keyword for the final parameter, ie.:
`{ "arithmetic": [ { "u_val": "var", "var_name": "impurities_soft_cap"}, "*", { "percent": 90 } ] }`
or better just accept floating point values for `const` directly

**Comment by Light-Wave** [comment]
The reason arithmetic doesn't deal with float is because when I was developing the functionality I read in [CODE_STYLE.md](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/CODE_STYLE.md) that int should be used for everything and float should be avoided. This seemed like a good policy since using floats can cause floating point errors. And worse, these errors may have different behaviour in different architectures. As such, I think using int is safer in general.

All that being said, I can see that being able to use float has its uses, indeed. I think the most reasonable way to implement that is to add an `"arithmetic_float":` functionality, together with a `"const_float":` option. Some new code might also be needed to deal with `var`s that uses floats instead of ints. That way you don't have to worry about incurring floating point errors by accident.

**Comment by Light-Wave** [comment]
Most of the relevant code that would need to be changed is found in [condition.cpp](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/condition.cpp).

**Comment by Computer-Engineer-Man** [comment]
> No need to make it that complicated. We could add `percent` as a keyword for the final parameter, ie.: `{ "arithmetic": [ { "u_val": "var", "var_name": "impurities_soft_cap"}, "*", { "percent": 90 } ] }` or better just accept floating point values for `const` directly

I was literally thinking about that this morning. Having it be a final parameter would be far easier.
