### ISSUE TITLE
Discussion: Lore shift for mutations

### ISSUE THREAD

**Issue by I-am-Erk** [CleverRaven/Cataclysm-DDA#62154]
### Is your feature request related to a problem? Please describe.

Over in the Lore Department, we are constantly working in our sweatshops to figure out ways to tie together the wacky lore of the game in ways that work to tell a coherent story and, more importantly, guide content creation in ways that make intuitive sense so that new contributors can easily figure out if a thing fits the game or not. That last bit is surprisingly tricky at times. Cleaning up and "silo-ing" lore elements makes it easier to figure out how they should work, eg telling us what the difference should be between triffids and mycus.

We have been merging the lore elements of "mutation" with "zombie agent" up to now, because zombies evolve which creates a thematic link. This works and we don't need to throw it out necessarily. However, it doesn't do a great job of informing contributors on what mutations should be and how they should work. Additionally it makes a lot of aspects of the mutation/evolution system feel like a handwave of "blob magic", which is kinda dissatisfying.

### Solution you would like.

It occurred to me today on the lore channel that we could in fact retcon this. It would be at least as big a retcon as changing cbms, although the changes would be more lore and less mechanical.

This is now the second revision of this proposal. For historic value, you can see the original [here](https://gist.github.com/I-am-Erk/7e2ad8f5832242ebc76fd86c624e6e3b).

---

Update 11nov: the current written lore is becoming a bit more solid now, but still up for debate and discussion. There are a few points I want to emphasize:
* Reducing direct involvement of the blob in mutation is a desired feature. We want less implication that the blob cares about your day to day life or the day to day life of zombies, so on the lore end we *like* that part. I apologize if you don't, but there are a lot of really good reasons for this, based largely on the ongoing experience of how people misunderstand the blob.
* Having xedra and pre-xedra do some mutation research prior to the arrival of the blob is also highly desirable. It makes the timeline way more believable, and it allows a ton of new and intriguing lore and artifacts for players to discover. That may be the single most positive aspect of a lore change here regardless of what we settle on. Even if we go on to a different readjustment, now that the advantages of having this in have been thought through, it's still likely we'll settle on something that lets xedra research mutations before the invasion.
* While I'm not married to the current use of portals and dimensions, it's generally a good thing in terms of what it lets us do with our weird netherum wackiness and opens up a bit of design space.
* The mechanism of mutation is going to remain uncertain, although many rules will be laid out. I've got around half a dozen theories that xedra was arguing about, and I'd like to write it such that any of them could be true. One theory is basically the old lore, slightly remixed. So if you don't like the new stuff, there's room to keep the old stuff as your headcanon and the game won't even tell you you're wrong.

---

This proposal establishes that the mutation we see in-game existed as a property before XEDRA discovered XE-037. Prior to the discovery of XE037, mutation was difficult, expensive, and complex. We'll call this "basic" mutation.

#### Early mutation

In early safety experiments trying out portals, early portal researchers pre-XEDRA found that living creatures that cross the portal barrier sometimes come back minutely changed. This led to quarantine procedures but didn't stop experimentation. With time and serendipity, they were able to determine that it was possible to influence this change in small ways. Their early mutagenic rigs would have involved infusing complex chemical cocktails, mixed with exotic matter from other dimensions, into the target organism, usually a mouse.  Then they'd send it careening through interdimensional space on a predefined path laid out for it by researchers. The process was incredibly expensive, and mistakes were fatal, but results could be replicated. Exactly what happened to the target organism wasn't yet determined. Were they bringing back a modified copy of the original, or was the original being changed? Experiments suggested that the subjects, as much as it's possible to tell with a mouse, kept their original memories, and things like radiomarkers persisted most of the time. The leading theories for what is happening suggest that if rapid dimensional shifts take an organism through sufficiently similar adjacent dimensions, it can get mixed with similar copies of itself or other organisms on the same path. If those organisms are too similar, nothing changes, but if there are some differences, the thing that comes back may be an 'average' of the two. Another possibility is that the netherum's imperfect-copying effect generates increasingly chaotic copies of the traveller, and in the right conditions these copies can be merged together on retrieval. There should be additional competing theories with the bottom line being that nobody is quite certain.

As portal tech progressed and XEDRA developed as an organism, advances in dimensional heuristics made it so that the computers that later advanced to become Melchior were better able to plot paths through n-dimensional space to achieve desired results. This made the process more reliable, but less expensive. It also made it possible to predict how to *avoid* mutation, which was considered important for sending human subjects through portals.

#### Practical "basic" mutation

As XEDRA tech advanced towards being able to create Melchior, they also became more confident in their abilities with induced dimensional mutation and gained approval to test it on human subjects. Most did not survive, but those that did again confirmed animal test results: they were, for the most part, recognizably the same people that they had been before the tests. It became plausible that XEDRA might be able to use portal tech to develop a mutated supersoldier. By this point the costs and reliability had reached a stage where prototyping was, if not practical, at least *conceivable*. In another fifty years, we might have rapid-regenerating humans that could survive in a vacuum and eat uranium for food. Or something, but whatever it was it would be cool.

#### Breakthrough

Then came the miracle cure. XEDRA stumbled upon a sample that changed everything: XE037. This proposal doesn't change the basic history of that encounter. Not long after XE037 contamination, XEDRA found certain experimental subjects suddenly became many orders of magnitude more amenable to mutation. What had once required massive inputs of energy and complex mapped paths through dimensions now required a minimal dose of mutagen and a small jolt. The results were now unpredictable, potent, and shocking. The discovery coincided with learning about the XE037 contamination. With a little further research, scientists pinned down that the fundamental mechanism was the same, but something about XE037 contamination in the mutagen target catalyzed the process to happen nearly spontaneously.

This leads to two new categories of mutation: "spontaneous" and "forced".  A spontaneous mutation is rare, happens without mutagen or with simple mutagens, and can activate without dimensional travel (though exposure to a portal still seems to be a common requirement). Spontaneous mutations do not tend to dramatically alter the target's phenotype, but the changes are still huge compared to basic mutation. "Forced" mutation requires complex and exotic mutagens, and requires (at this time) complex dimensional travel. Forced mutation can create enormous phenotypic changes in the target, even changing them to what appears to be a different species.

#### Concerns

Soon after learning about XE037's potentiating effect, researchers began finding out about XE037's *other* effects. Again, this is already laid out in the lore. The following events are unchanged with regards to XEDRA's failed lockdown and blob contamination of the groundwater, but now XEDRA has a bit more of an idea what to expect as the blob spreads worldwide. Random mutations in this modified timeline no longer occur significantly until the portal storms begin: once that happens, all bets are off: portal energy can, in the right conditions, trigger random mutations in targets.

The more they learn about XE037 during their final flurry of research, the more XEDRA scientists become afraid of the implications of its mutation effects. There would be at least many theories circulating, but a few include:
- Does the mutagenic effect work now because living things contaminated with xe037 are in some way already dead tissue? (probably not)
- Does forced mutation bring the target in contact with other dimensions? Could xe037 be using this as a way to travel and infect other worlds? (very possibly) - and if so, is that why it makes it easy for us? (sounds like the sort of thing it digs, my friend)
- Is the creature that comes back the same as the one we sent away? (Your guess is as good as mine)
- Can zombies do this too? How will spontaneous mutations manifest in these creatures? (Hmm. I have my guesses, homie)

As the apocalypse happens, the blob wipes out a lot of the barriers between our world and the netherum/other dimensions. The resulting portal storms and dimensional degradation on earth close the loop and bring mutation back to what we are familiar with. There should be a few late xedra notes about this as well. At some point, we may wish to adjust the mechanics a bit to have portal storms, reality tears, etc help to boost and power up your mutations, or even make them required for thresholds.

#### Comparison to previous version and to current lore

If you read the old version, you'll see that this version merges it with existing lore, with a lot fewer changes. In this version, mutation is something that exists with or without the blob, but the blob amps it up from an unclear and early science to a thing you can do by chugging mad science goop and crossing your fingers. In this model, the blob itself is probably not doing the changing, but that's unclear and the lore should allow for many different possibilities. More likely, you are either being replaced with or mixed with a similar creature from a nearby dimension, and the blob works as a catalyst to make this easy and keep you alive through it. What does the blob get out of it? Well, we'll never know for sure, but personally I like the headcanon that you're helping it reach out to infect other worlds in the process. Thanks, Typhoid Mary.

This does dramatically change the very low level nitty-gritty of how we're proposing mutations work, but I learned from discussions that almost nobody had a good handle on that anyway, so I don't think it's a big loss.

#### Pros:

* Gives XEDRA more agency in their history, and some sciency stuff to do.
* helps our timeline a lot because now we don't have to cram massive scientific advances into a couple years. Mutation research has been going on for decades.
* Clarifies the difference between random mutations and big ("forced") ones a bit - the random ones should keep you recognizable as yourself, while the forced ones could change you dramatically. Growing fur might be random, but getting a set of spider limbs has to be forced, eg.
* The lore is *slightly* less handwavy
* Makes mutant animals and bugs make a lot more sense
* Makes random human mutants make more sense
* No actual game mechanics or items need to change significantly
* Brings mycus mutations together with other mutations under the same lore umbrella as well as mechanical.
* Opens up some very weird lore options like establishing that mutation can cause you to gain and lose memories by copying them with other "travellers". also explains where threshold dreams come from.
* Gives us room for new mutation effects that previously didn't make sense, like having mutants spawn as a product of portal storms, or having tears in reality cause wild mutations among the animal and plant life in the area.

#### Cons:

* Requires rewriting a lot of the lore
* doesn't really make mutations less magic, just makes them a magic that's easier to write limitations on
* The exact lines of what is okay as a "random" vs "forced" mutation are still subjective
* Any time we do a big lore change like this, people are confused for somewhere between three and fifty years, and we will be heralded as monsters eternally by some of them. Now that I've reduced the changes though, I think this will matter less: most of the changes are now in areas I have learned people didn't understand well to begin with.

So the discussion question: What ramifications might this have that we didn't think of in discord discussion? IMO it is mostly a neutral change with some positive aspects in the long term. It adds an element of XEDRA feeling more like they were into some transgressive experimentation *before* xe-037 hit, which I really like, and it doesn't stray far enough from existing lore to be very questionable. It's a big change though, so I'd really like to hear some other opinions before we start redoing dozens or hundreds of lines of snippets.

#### Misconceptions to clear up from feedback

* Note that if you think the current mutation lore is more intuitively understandable and scientific than this, there are high odds you're not deeply familiar with the current mutation lore.
* This isn't a proposal to dramatically redo mutations on the player side. I like the current mechanics, I helped design them. Mechanical changes from this would be downstream, and aside from a few tweaks, would probably be additive rather than changing existing stuff.

### Describe alternatives you have considered.

This doesn't have to change. There's nothing wrong with the current set up. I just think this makes for "cleaner" lore, and has a chance to bring us in other directions. 

There was, as mentioned, a previous version of this that I have now significantly adjusted.

### Additional context

Special thanks to @venera3, Holli, and @RAldrich for helping develop the idea on discord.

Thanks to those that commented helpfully on discord and reddit.

**Comment by GuardianDll** [comment]
First - it seems it opens the doors into chimera stuff, when "this is a dog, it was a dinosaur in another/paralel universe, so now it has 4 meter size and his teeth is bigger than your fist"
Second - yeah, the question about "why it pick the exact X entity to shift into" and "why it do anything at all, instead of, like any another liquid that streamed into your blood flow, cause a significant and usually lethal damage into your organism"
Maybe even the question "why do you need to stream it/do you need to stream it at all?" Can't wait the mutagen cream that you need to apply on your skin :derpy:

**Comment by ducanishah** [comment]
I _LOVE_ this change. I do agree that it would muck with some things, but as a random player who occasionally thinks about contributing, I think this makes for a really elegant system. Clear on how it works, but still broad enough to allow unexpected things to be included.
Random spitballing thoughts:

- When crafting mutagen, maybe samples of inter-dimensional monsters like hounds could serve as catalysts contributing energy, but maybe a "safer" option would be to make portals into a furniture, and allow them to be used as a tool to energize the solution of the mutagen with warp energy. Now mind you, this will involve standing next to an _active portal_, suffusing you with warp energy and potentially spitting nasties out, and, if you don't have the required proficiency in chemistry and physics, could take a long time.
- Body-part targeted mutagens could be a thing. A salve, as you say, could be applied to only a specific part of the body. Of course, there will always be the chance of some totally different body part of your body mutating because the warp is inherently chaotic, but it gives you some control to shoot for "probably an arm mutation, and probably a bear mutation." A downside to this method, I think, would be a higher drain on your health and wellbeing. If mutating is compared to jumping through a portal (only for the sake of this analogy), it would be like only putting part of your body through, then closing the portal: Obviously harder on you.
- The Exodii not wanting to implant heavily mutated people makes perfect sense- maybe they implant something in your arm, but then you mutate your arm, and those cbms they invested in you are now somewhere else in the multiverse, because you overrode them with a bird wing. I also think exodii cbms in general should both protect from warping and mutations and make it harder to do intentionally, as the exodii's whole thing is that they travel through dimensions, so what they make will definitely be designed to resist being warped by interdimensional energy.
- Likewise, I think the Exodii would 100% have purifier on hand and probably be willing to sell it, as they must be familiar with fighting the effects of the warp after traveling through it so many times, and sympathize with anyone affected to it who does not want to be. This would allow players who were unluckily mutated to still have the chance to use cbms if they want, or just revert their mutations. Theirs might have to be a weaker purifier in some way, only able to reverse mutations up to a certain point, with stronger existing elsewhere, just for balance reasons so that they don't completely remove the consequences of sleeping next to an active portal. Another possibility is that there is some kind of side effect of purifier for using it too much, but no matter what, I think with this lore explanation, the exodii should 100% have purifier and be willing to teach the recipe to you, if not sell it to you directly.
- Cross-mutated beasties become a possibility. In the same way we have maps with modular components within them, we could see monsters with some of their parts shifted, say only an arm or leg replaced, by the same token as how player mutation only does piecemeal at a time. Might not want to do that just for the programming and upkeep complexity, but the possibility for at least a special "warp tainted" creature with randomized traits is there.

I think this change would be truly excellent, and I'm sure there are countless more directions it could be taken in, any of which I would be happy to see explored.

**Comment by LyleSY** [comment]
I like the idea of going through portals having some potentially useful effects, and I could see some items emphasizing elements of those effects. Could also allow for things like jumping into a portal while holding a chicken in a pet carrier helping you mutate into a bird and maybe help the chicken mutate into something more like you. I also like the idea that every time you step into a portal, someone else steps out.

**Comment by PatrikLundell** [comment]
The lore change part I disagree with is the pre dimensional mutation research. Standard game/fiction mutations have creatures spontaneously change, while real world mutations change the genome and affects offspring (or give you cancer), although you might be able to trigger existing genetic "blueprints" in a grown organism, such as e.g. cause a new finger to grow out using the existing finger blueprint (some humans are born with 6 fingers on a hand rather than 5 due to some blueprint application issues during development), and some animals have the ability to regrow lost body parts, indicating that it's possible to reactivate blueprints.

Thus, I'd rather see the pre portal research be into regeneration of lost limbs (which seems like it could be possible eventually) that then branched off into mutation research once dimension research showed the appearance of resulting mutations. Presumably, whatever enables the activation of genetic body part blueprints might help activation of mutated body part blueprints that morph body parts (that's probably a bit of a stretch, though) as well as growing new ones.

**Comment by waxcatape** [comment]
A minor point: Don't the changes caused by mutations still have to reflect on the organism's genes? I'm no geneticist, but it seems to me that if you suddenly get a set of spider limbs grown on your body by netherum shenanigans, without genetic changes they are just going to rot away without your body knowing how to maintain them, at best. At worst, you get spider limb shaped cancer. Maybe I'm talking out of my netherum, idk

**Comment by Daved27hundred** [comment]
Question. If mutating helps the blob "travel" in some way, would that make the Exodii or even the Yrax extremely hostile to mutant characters? I could see it causing some interesting situations where you'd need to make a choice between one or the other, since the Exodii would probably see you as a threat on an exponential level.

Maybe there could be a mutant-oriented faction as an analogue to the Exodii?

**Comment by I-am-Erk** [comment]
> How much lore has to be rewritten and how does the "spontaneous" vs "forced" differ from current "pre-" and "post-threshold"?

The spontaneous/forced is more of a lore difference, but in general spontaneous means pre-threshold and available as a random mutation. All threshold mutations would be forced, and many pre-threshold mutations that are sufficiently "weird" as well.

**Comment by I-am-Erk** [comment]
@PatrikLundell 

The proposed system would still not be a genetic-based mutation system. It's not really possible to make our mutations make any sense as a genetic process. It's reasonable that xedra would explore regeneration early on, but I don't think it's something they'd have stumbled upon initially.

@maddremor: I think you were there when I brought this up in discord, but I would like to leave the netherum as a favoured theory for how it works, but also establish that it's a topic of debate among scientists. I don't want a single clear answer because the closer we get to a clear answer, the more we have to shrug and say "it's kinda magic though"... Fundamentally, what we're doing is video game magic and we're just trying to patch it up.

@waxcatape that's... Complex. To avoid a long discussion, assuming your new body parts are recognized as self then all they need is a way to heal and stay alive. Genes will be involved but to call our mutations "genetic" is like saying assembling a computer is programming. Further details will mostly be technobabble (and I look forward to writing it) because, as outlined above, ultimately our system doesn't and will never make a lot of biological sense.

@PatrikLundell I think these changes would make the Exodii mildly less hostile to mutants, because they don't know any more than you do about that possibility. It would be interesting to make the yrax comment on it though.

**Comment by PatrikLundell** [comment]
Your argument is the same as mine, essentially: It doesn't make sense for XEDRA to experiment with "magic" until "magic" has actually been discovered, and game type mutations only appear once dimension experiments show them appearing.
My suggestion with regeneration research as a tie-in to the later dimension experiments would be optional, though, but I maintain that actual mutation research before there is any way to make it do anything doesn't make sense. I'm fine with it appearing before the discovery of/encounter with the blob, though.

Regarding Exodii hostility: I don't think Exodii potential knowledge of potential side effects of mutations should make them inherently hostile towards mutants. If should make them hostile towards mutation aspirations and mutation research, but not towards potentially unwitting victims of others experiments or their own bad luck, as that would be akin to being hostile to people who have recovered from a disease. Those who are warned but won't change track would be a different matter, though. And that's only assuming they have sufficient knowledge or suspicions (and they should have had quite some time during which to gather knowledge and investigate suspicions).

**Comment by NetSysFire** [comment]
More of a general question about the world, but if everything gets meaner, more aggressive and potentially carnivorous, does that mean that a great ecosystem collapse is imminent?
So at some point many species will be extinct, local flora and fauna dies off (due to a myriad of reasons), being potentially entirely replaced by alien equivalents. Maybe the exodii could share how dimensionally unstable versions of earth will eventually look like? By that I mean a couple of decades, if not centuries into the future.

**Comment by I-am-Erk** [comment]
Yes, a total biosphere collapse is imminent. That's actually a good example of why a lore adjustment helps: we frequently have to shoot down the argument that the biosphere won't collapse because blob mutants will just continue adapting until they can survive the worsening conditions. The newer mechanism can make it more readily apparent that mutations that extensive just aren't going to happen.

**Comment by waxcatape** [comment]
@AJimmyU The blob is not the big bad and nobody's fighting against it, not in any way that matters. The overwhelming majority of entities in the game aren't even aware of the blob and the blob itself couldn't care less about your fighting zombies or whatever.

**Comment by I-am-Erk** [comment]
@AJimmyU even outside what waxcatape points out, I have no idea how that has anything to do with this proposal, which does nothing to adjust make the blob any more or less of an antagonist.

**Comment by esotericist** [comment]
> Have you considered that majority of players enjoy having blob as the big bad to fight against?

ah, yes, another person who is trying to pick a fight with the gravity well emanating from jupiter.
