### ISSUE TITLE
just some basic and generic avionics

### ISSUE THREAD

**Issue by jfferson** [CleverRaven/Cataclysm-DDA#62176]
### Is your feature request related to a problem? Please describe.

using multipurpose vehicles (air and land, air and and water) is overly simplified without it

### Solution you would like.

we could have at least some abstracted and generic system, with statistics of flight stability, that works like the "floats" information, and requires enough wing span, according to weight, if you are using aeroengine; and takeoff and stall speeds

**Comment by Kywi001** [comment]
Correct me if I'm wrong, but we don't have planes, but heicopters for air travel, which doesn't really need a wing as it uses rotors with blades instead of jet engines.

And the rotor blades by itself have a range where it can hit something and break completely, and we normally can't modify it without the A&P Mechanics traits that we normally can't get, I mean, we could modify helis but it won't be able to take off.

**Comment by jfferson** [comment]
sorry, you are right, I got confused with the "light aeroengine", on the game you can really only use engines for flight if you have rotors
