### ISSUE TITLE
Vehicles accelerate when turning slightly with "y" or "u"

### ISSUE THREAD

**Issue by Je55eah** [CleverRaven/Cataclysm-DDA#62197]
### Describe the bug

When trying to make gentle steering adjustments, the speed increases.

### Steps to reproduce

drive

### Expected behavior

the speed should remain constant.

### Versions and configuration

Linux and Windows

**Comment by Je55eah** [comment]
Then this is a request, because the ability to turn slightly less than h / l is good and there is no reason it should speed up when doing so. I understand that those are upleft and upright, but it isn't intuitive when driving because the speed is best controlled only with j / k or up / down.

**Comment by PatrikLundell** [comment]
"Accelerate and turn" turns as much as just "turn" (and "decelerate and turn") does. Turning is done in fixed steps (15 degrees, I think). Thus, any perception that "accelerate and turn" somehow turns less than just "turn" is a mistake, possibly caused by the fact that movement has to be done in whole tiles, so "turn and accelerate" may, much of the time, result in additional movement forward but the same movement sideways as just "turn" does, but that's simply a result of the added acceleration not adding sufficient sideways motion to move an additional tile compared to just "turn".

**Comment by Je55eah** [comment]
Okay. Thanks.
