### ISSUE TITLE
Zones from ground to vehicle cargo

### ISSUE THREAD

**Issue by Je55eah** [CleverRaven/Cataclysm-DDA#62201]
### Describe the bug

I tried zones for the first time. Is it supposed to be work if I create a custom zone attached to a vehicle storage space and place the unsorted zone on the ground? I didn't enter any text into the custom zone filter because I read that it would catch everything that way.

My intent is to load 30+ planks and other big objects that don't fit into my inventory. I can do it manually by wielding each item and manually moving them one at a time. I can do it with the advance inventory manager "/"  on the box van I am driving by standing on a shutter door between the storage and the ground, but that doesn't help if I want to move it to a deeper tile within the cargo bay. 

### Steps to reproduce

Pile stuff up on the unsorted zone and try to move it to the custom zone which is attached to a vehicle storage spot. 

### Expected behavior

The stuff actually gets moved onto the vehicle.

### Versions and configuration

Linux tiles 1149

**Comment by andrei8l** [comment]
You haven't actually said what the bug is. I tried your steps to reproduce with 300ec6db71e2b76c6b3bca23f92d9698b57f025b and didn't have any issue:
<details>
<summary>video evidence</summary>

https://user-images.githubusercontent.com/68240139/201509525-6afa8357-28f0-4223-a7cd-d2d4ebb707e9.mp4
</details>

**Comment by Je55eah** [comment]
Interesting. I'll try it again tomorrow. Could the issue be that I was moving planks and other large objects that I could not place in my inventory? I dragged the pile over to the unsorted spot with "\".

**Comment by PatrikLundell** [comment]
Your inventory space should not matter. Also, you don't have to drag the items to the unsorted zone, but can rather paint an unsorted zone over the area your items are located in (assuming there aren't other items you don't want to load in the area).

You still haven't actually described what your problem is, just that you fail to use zones to move stuff. For instance, you haven't said that you actually tried to sort stuff (which is how you actually move items). If I recall correctly, you sort zones by pressing "O" and then select to sort items.

Thus, you ought to fill in the "Steps to reproduce" section properly, by exactly listing the steps you've taken so others can follow those exact steps and either reproduce a bug or understand what step you may have missed.

In addition to this, the zones all have to be on the same Z level, as the zone logic currently doesn't work across levels.

**Comment by Je55eah** [comment]
Update: I tried it again and it worked as expected this time. I can't explain why it didn't work the first time because I followed the same steps as those I shared in the OP. The only difference is that the truck and pile are in a different place on the map this time.
