### ISSUE TITLE
Soler backpacks spawn within apartment towers.

### ISSUE THREAD

**Issue by DoctorBoomstick** [CleverRaven/Cataclysm-DDA#62243]
### Describe the bug

During some casual play this morning, I found a soler backpack on a coat hanger within one of the bedrooms of a 2x2 apartment tower. To my understanding, after consulting the item’s description and use action, the backpack only seems to be used for the charging of the cable charger CBM. Given that CBMs are no longer human tec, it puzzled me as to why an item expressly made to charge said non-human technology would be rubbing elbows with blazers and scarfs on a civilian coat hanger.

### Steps to reproduce

1.	Go make some popcorn and grab your preferred beverage of choice, because this is going to take a while. Butter is optional.
2.	Create a character that starts within an apartment tower.
3.	Poke about until a soler backpack feels like saying hello.
4.	Go refill your popcorn bole and restock your beverage. Pizza and a good movie are recommended.

### Expected behavior

If the backpack is indeed only meant to be used for the powering of a cable charger CBM, than I’d expect its spawns to be restricted as needed and for it not to show up within domestic homes. Otherwise, the pack should be able to charge human gadgetry like smart phones.

### Screenshots

![Screenshot at 2022-11-16 05-36-59](https://user-images.githubusercontent.com/102766473/202109372-68f901a3-6243-4242-878e-c66382bd3acc.png)

### Versions and configuration

- OS: Ubuntu 18.04
- Game Version: 65e5b97
- Graphics version: Terminal
- Ingame language: English
- Mods loaded: dda, Xedra Evolved, Useful Helicopters Experimental, Archana, SpeedyDex, Tameable Wildlife, TropiCataclysm

**Comment by robotic-gamer** [comment]
in past runs I have also encountered solar backpacks in residential locations that made no sense. I just wrote it off because I had aftershock installed. the most likely explanation for this is the solar backpacks being in the civilian/generic clothing drop group for some unknown reason. perhaps solar backpacks could be made to work like a UPS that can self-charge when set up on the ground (like funnels) in the light, or when worn in the light?
