### ISSUE TITLE
Pressurized tanks can't be unloaded

### ISSUE THREAD

**Issue by intergalacticdata** [CleverRaven/Cataclysm-DDA#62260]
### Describe the bug

Pressurized tanks, at least when loaded with hydrogen peroxide, cannot be unloaded. It doesn't show up as an unloaded item and there appears to be no way to remove the liquid from the tank. the tank was loaded simply be reloading, and no prompt was given regarding what to load it with.

### Steps to reproduce

Get a pressurized tank.
Empty the tank if not mpty.
Fill the tank with a liquid (hydrogen peroxide)

### Expected behavior

I don't actually expect a pressurized tank to be so easily refilled and continue to be a pressurized tank.

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Debian; Description: Debian GNU/Linux 11 (bullseye); Release: 11; Codename: bullseye; 
- Game Version: 0.F-12256-g579e201ecc [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by RenechCDDA** [comment]
Technically working as designed. It has `NO_UNLOAD` with the intention that the pressurized liquid ammonia can't be dumped out. #61759 (my PR) further resolved containers not checking this for liquids.

From my conversations with Drew, the intention is that liquid ammonia must be kept in a pressurized container... which is why the pressure tank has these flags (and should have NO_RELOAD added; not sure that would prevent all instances of putting new stuff in them). Ammonia also needs a `NO_DROP` flag so it can't exist outside of containers, but I'm waiting on other ammonia-related PRs to merge before further adjustments.

**Comment by robotic-gamer** [comment]
perhaps liquids that need to be in pressurized containers are classified as being in their own state of matter like "pressurized liquid" as opposed to "gas" or "liquid". this way the pressurized tanks could be explicitly stated to only hold "pressurized liquids" and not regular liquids. perhaps there could be some sort of electric pump that charges of are used to transfer "pressurized liquids" between or just into containers.

mostly unrelated note but butane becomes a liquid around waters freezing point. so in theory using water with the "frozen" flag you could ensure the butane in lighters stay liquid even when cut open. you could then simply pour the butane into a suitable container (say a can of butane that's been modified to have an easy way to pour liquid butane into it) until it is completely full. now you've effectively filled a can of butane with butane found in common lighters.
