### ISSUE TITLE
Bridge Created Unconnected During World Gen

### ISSUE THREAD

**Issue by AgentChunk** [CleverRaven/Cataclysm-DDA#62264]
### Describe the bug

Bridge are sometimes created as a single map square without any ramp connecting to them

### Steps to reproduce

Road connecting to water during world gen

### Expected behavior

Bridge should connect via ramp

### Screenshots

![image](https://user-images.githubusercontent.com/8432264/202467890-f6bed144-8abd-45e5-a2f9-61203dfdc7a4.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22000.1219 (21H2)
- Game Version: 66f52ce [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

Second time I seen this in separate saves same game version

**Comment by AgentChunk** [comment]
[Scranton.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/10032353/Scranton.zip)
save attached

**Comment by robotic-gamer** [comment]
I think this issue has already been submitted awhile ago. I actually submitted an issue awhile ago on this and it was closed due to being a duplicate. relevant issues
#55779
#22133
#46844

personally I suspect this issue should be closed due to being a duplicate. thank you for trying to help bugfix. (personally I actually have no idea how to check for accidentally duplicates like this, beyond just having seen the issues being brought up here for the last while and not submitting issues that I've seen others submit).
