### ISSUE TITLE
Earplugs do not make people deaf.

### ISSUE THREAD

**Issue by Je55eah** [CleverRaven/Cataclysm-DDA#62292]
### Describe the bug

I pressed "$" to go to sleep and discovered that my character is deaf. Earplugs don't work that way. Also, the AR-15 is not very loud, but I put the earplugs in earlier because the game seems to think that it is. 

### Steps to reproduce

wear earplugs.

### Expected behavior

Earplugs should reduce the likelihood of hearing damage from things that are actually loud. 

### Screenshots

![deaf](https://user-images.githubusercontent.com/12481255/202832536-6a41c11a-0235-4ebb-a551-518872369506.png)

### Versions and configuration

Linux experimental 22-11-10-1351

### Additional context

I have worn earplugs for hundreds of hours and I have experience with M16 and the M4.

**Comment by Spaceb0i** [comment]
Earplugs would almost certainly prevent you from waking from sleep from an alarm. While it's a mild oversight that you can't hear _anything_ with earplugs (that I know of), it's not a big deal because you can just take them out. If you're looking for hearing protection that doesn't completely block sound, use Shooter's Earplugs and turn them on.

**Comment by Je55eah** [comment]
I disagree, but whatever.

**Comment by AcidAntOnAMinefield** [comment]
You disagreeing doesn't make it wrong lol. 

As someone who uses Earplugs to be able to (maybe) have a few hours of sleep, I can guarantee you that no matter how loud an alarm is, it won't wake me up if I have my earplugs on. 

In the game, by making you "temporarily deaf" it *is* reducing the likelihood of hearing-related damage - it is most likely a limitation of the way the feature is currently coded as **or** there just isn't any better way (to date) to make it more "realistic". And "Realistic" really depends, because even between earplug brands, some of them are great, others are serviceable, a lot of them are absolute dog crap, others are uncomfortable due to their sizes, and others just outright don't work. 

Mind you, there are several types of them in game:
- Shooter's Ear Plugs (which you turn on and off), which have an audio dampening feature for loud noises and amplifies quieter noises (never actually used them in-game so I don't know if it works or not).

- pair of ear plugs, which are your standard "i really need to sleep" / "i really can't be bothered with my neighbours' argument" off-the-shelf product. 

- makeshift ear plugs, which... yeah.

- attached ear plugs (which you wear and just activate whenever you want to use them);

**Comment by Je55eah** [comment]
It's a game with a lot of strange opinions and your lived experience is clearly different than mine. Which one of our opinions is right? Being deaf is a major tactical disadvantage that should not result from wearing non-electric earplugs. Whatever though.

**Comment by Qrox** [comment]
If we want to be super realistic, we can make earplugs reduce the outside noise by a set amount of decibel (I remember seeing a table of noise reduction at different frequencies on the package of the earplugs I use, but that's probably overkill). It would make some interesting gameplay of weighing protection vs. access vs. alertness. I can definitely attest to missing my alarms due to wearing a earplug though.

**Comment by Zireael07** [comment]
I don't wear earplugs because I am hard of hearing. I am not completely deaf (I can hear e.g. a storm, things making a racket when falling down, speech from very close by, like 1,5m even behind me so I can't lipread) BUT I completely miss any normal alarms, and I have a vibrating alarm clock/wristband for that reason.

But for gameplay purposes, I probably count as effectively deaf and it seems that it matches people's experiences with alarms while wearing earplugs

**Comment by Je55eah** [comment]
Why are there so many people in this comment section who sleep with earplugs? This doesn't seem like a representative sampling. 

On the topic of alertness, how do the mp3 players affect the character?

If the game is going to penalize the player for not wearing earplugs and make the character deaf if they wear them too then they become another point of tedious micromanagement. If earplugs actually detracted from hearing as much as the people here think they do then it would be impossible to forget. My take is that they are impossible to forget, even though they don't eliminate sounds. Likewise, if the gunfire is as damaging as it is thought to be then it would be impossible not to notice. My game experience is that I don't get notices about the loudness of the gun until after I have shot multiple times and then, when I am in the thick of combat, there is no way I would fumble around with earplugs. That notice should come with the first shot. Not, "you hear bang", but "That was loud. Don/wear hearing protection now?" When there are no visible enemies, or after a minute in game without loud noises then the player ought to be prompted about removing the deafening earplugs. Adding and removing them could both be prompted and it could even be automated.

**Comment by anoobindisguise** [comment]
The noise cancelling headgear is silly too - just some rags wrapped around your ears, but makes you totally deaf.
There really should be 3 tiers of "hearing protection". 
Total deafness (you can't hear anything from within what you're wearing)
All sounds dampened (everything is quieter as if you had poor hearing, due to wax or cotton in your ears)
And only loud sounds dampened (shooter earmuffs/plugs)

**Comment by gisaku33** [comment]
Reducing access to full deafness would make sound warning prompts much more annoying to deal with, especially for things like hauling where every single tile you move can cause a warning prompt because of an unseen sound.
