### ISSUE TITLE
Cloth & Leather padded shirts lack HOOD and POCKETS flag despite a hoodie is a component for them

### ISSUE THREAD

**Issue by NotSeawhite** [CleverRaven/Cataclysm-DDA#62338]
### Describe the bug

Padded shirts are missing some flags.

### Steps to reproduce

- Make a padded shirt with a hoodie
- Observe the missing flags

### Expected behavior

Those should have HOOD and POCKETS.

### Versions and configuration

Happens in the latest experimental version

### Additional context

they're gone :(

**Comment by anoobindisguise** [comment]
So the reason for this is a) it can be made with a sweatshirt also (originally it was just the sweatshirt and not even a hoodie) and b) the survivor is removing extraneous bits on the armor to optimize encumbrance - the hood is extra weight but isn't necessary to the armor's function. Likewise the pouch on front shouldn't even be accessible because it is covered in leather.

**Comment by NotSeawhite** [comment]
Shouldn't they at least make byproducts?

**Comment by anoobindisguise** [comment]
again the issue is the sweatshirt has no byproducts to make and there's no way to selectively make byproducts only if you use a specific ingredient, and ultimately I'm not super concerned about 4-5 cotton patches leftover from shearing off the hood and pouch.
