### ISSUE TITLE
Question : are crouching / prone targets  more difficult to hit?

### ISSUE THREAD

**Issue by matt32106** [CleverRaven/Cataclysm-DDA#62412]
### Is your feature request related to a problem? Please describe.

I have the feeling that my prone PC gets hit by gunners as easily as if he was standing. Is that really the case?

### Solution you would like.

Tweak the "to hit" success probability according to the PC/NPC/monster stance. If the "to hit" % is linked to the target's size, then vary the size of the PC/NPC/monster according to stance.

**Comment by DSeyka** [comment]
Best I can tell from reading the code, prone mode makes you move slower, more difficult to see, being able to use bipod at any terrain (otherwise you need to be on a mountable furniture to use it) and gives you melee penalties (to both to-hit and damage). You are not any harder to hit unless you're hiding behind cover, in which case enemies might not be able to see you.
