### ISSUE TITLE
Second quest from refugee center failed to generate overmap location

### ISSUE THREAD

**Issue by FrancoFlesia** [CleverRaven/Cataclysm-DDA#62441]
### Describe the bug

Second mission from the Merchant in refugee center fails to be created.

### Steps to reproduce

1. Complete first refugee center quest (Clear the back room)
2. Accept the second quest from the Merchant

### Expected behavior

I expected the quest to start (it is not available in my mission list)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2251 (22H2)
- Game Version: 0236ecd [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/10100041/debug.log)

This line in the debug file seems to explain the reason the overmap failed to generate:

21:14:30.504 ERROR : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\mapgen.cpp:2785 [apply] In unknown object in add_mapgen_update_func on field, setting terrain to t_region_groundcover (from t_grass) at (13,4) when furniture was f_flower_tulip.  Resolve this either by removing the terrain from this mapgen, adding suitable removal commands to the mapgen, or by adding a suitable flag to the innermost mapgen: either ERASE_ALL_BEFORE_PLACING_TERRAIN if you wish terrain to replace everything previously on the tile or ALLOW_TERRAIN_UNDER_OTHER_DATA if you wish the other items to be preserved

**Comment by PatrikLundell** [comment]
No, that error report is not related to the problem. This type of report happens when the map hasn't specified what to happen when terrain changes clash with items and prompts for that to be updated, but it nevertheless proceeds with the ALLOW... option (as that is how it worked before these flags were introduced).

Instead, the reason is that the code fails to generate a suitable overmap location, which is a problem that's been present for quite some time (years?).
