### ISSUE TITLE
[Innawood] Make Wax Obtainable

### ISSUE THREAD

**Issue by Kantonine** [CleverRaven/Cataclysm-DDA#62469]
### Is your feature request related to a problem? Please describe.

After the initial scramble for basic clothing, I noticed a lack of sources of wax. this means that _everything_ made of canvas except canvas sacks and bags are craftable. 

### Solution you would like.

Add a crafting recipe for wax or wax-like substance. Possibly using wool staples, to extend more usefulness of woolly animals.

### Describe alternatives you have considered.

Re-add the 3x3 overmap beehive as a possible source. It'd also give innawoods players a psuedo dungeon.

**Comment by Zireael07** [comment]
The beehive imho makes perfect sense in Innawoods

**Comment by PatrikLundell** [comment]
I've encountered a couple of beehives in my Innawood game (on an experimental about a month or so old). Are you sure they have been removed, rather than you just haven't explored enough to encounter one?

Not that the beehives are useful to me, as it seems it should be too risky to try to raid one for the time being.

**Comment by Kantonine** [comment]
> I've encountered a couple of beehives in my Innawood game (on an experimental about a month or so old). Are you sure they have been removed, rather than you just haven't explored enough to encounter one?
> 
> Not that the beehives are useful to me, as it seems it should be too risky to try to raid one for the time being.

**Comment by Kantonine** [comment]
Sorry for opening this then
