### ISSUE TITLE
NPC unable to find a tool causes extreme lag

### ISSUE THREAD

**Issue by intergalacticdata** [CleverRaven/Cataclysm-DDA#62644]
### Describe the bug

When assigned to a task, such as disassembling, and unable to find a viable tool, the NPC continually processes the entire area, causing potentially large slow downs.

### Steps to reproduce

Create  largish workshop area - house sized or so.
Create a disassembly zone and place an item in it.
Make sure the NPC doesn't have access to tools.
Assign the NPC to disassemble items through the camp bulletin board.
Attempt a long task and observe.

### Expected behavior

NPC should not continue to process the entire area if no new items have been placed on the floor.

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Debian; Description: Debian GNU/Linux 11 (bullseye); Release: 11; Codename: bullseye; 
- Game Version: ab877e4bed0 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by MochaModifier** [comment]
this issue continues to be an issue - even just one NPC can making just walking an incredibly slow (in real time) action.
![image](https://user-images.githubusercontent.com/38334602/222375018-4f9a5cec-3704-4de7-8f9b-e862431ce30d.png)
Here I tried to heat water up at a fire; and Alleen tried to find a shovel for ditch digging - and did so over 5000 times before I stopped trying to heat water at only 2% progress. I waited several minutes before doing this - and then it took a good minute to actually stop heating the water. 

This is definitely bad behavior. Perhaps NPCs should only look for valid tools every few minutes, rather than every millisecond(?).
