### ISSUE TITLE
Armor and leashes do not drop when a pet is killed.

### ISSUE THREAD

**Issue by DalenTalas** [CleverRaven/Cataclysm-DDA#62705]
### Describe the bug

Subj. All that is left is the sad, tiny corpse of beloved Fluffy.

### Steps to reproduce

1. Get a pet (tried with a pitbull mix).
2. Equip pet with armor and leash.
3. Get pet killed (you monster).
4. Observe no armor or leash lootable from the corpse.

### Expected behavior

Items worn by pets should conform to the laws of matter preservation.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2251 (22H2)
- Game Version: f5eec2f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth]
]

**Comment by DalenTalas** [comment]
> That's strange. #62615 should have been fixed this issue.

Could be that I am behind on updates... Will try to verify later, unless someone beats me to it.

**Comment by oosyrag** [comment]
Confirmed working properly Game Version: e40157c [64-bit]  - k9 officer start, put kevlar dog harness on dog, shot dog, harness is on corpse.

Very strange though since f5eec2f is later than 6e617f6 so you should already have the fix, so if you can re(un)confirm this could be reopened. You made me shoot a dog for this, I hope you feel terrible now.
