### ISSUE TITLE
rigid things shouldn't be "spilled" from liquid containers on pick up

### ISSUE THREAD

**Issue by Brambor** [CleverRaven/Cataclysm-DDA#62779]
### Describe the bug

"Spilling" implies losing the item (at least to me). You don't really "spill eggs" do you?

### Steps to reproduce

1. Have eggs in a coffee mug.
2. Try to put the mug into your inventory.

### Expected behavior

Check if the contained item is ~liquid~ rigid, if it is, say `unload` rather than `spill`.

### Screenshots

![image](https://user-images.githubusercontent.com/13402666/208329788-4ac3ece1-71a3-44e7-86ab-f24abcf77029.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2364 (21H2)
- Game Version: 59756b0 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by NotSeawhite** [comment]
I think it's just a misinformation. But physics still applies to stuffs that is inside something that doesn't have a lid

**Comment by oosyrag** [comment]
This is just nitpicking the definition of spilled. If I have marbles in a cup in my backpack they can absolutely spill out of the cup. Doesn't mean I lost them or unloaded them. Solids can spill.

The wording of the action could use some improvement though. I'm thinking something along the lines of "Allow contents to spill out". "Can't stash while it's not empty" kinda irks me too, since you should be able to, just with consequences.

If it were up to me, I'd just change the interface when trying to pick up an open container with contents to something like the warning for stepping on a visible trap when trying to stash the item. "Contents will spill out. Are you sure? Y/n". Wielding wouldn't show this warning.
