### ISSUE TITLE
After exporting books to sd card, it still shows sd card (clean)

### ISSUE THREAD

**Issue by GeekDuanLian** [CleverRaven/Cataclysm-DDA#62786]
### Describe the bug

As the title.

### Steps to reproduce

1. Generate a `manual book`, a `smartphone` and an `SD-Memory card (clean)`.
2. Use a smartphone to record books, through `Store a book`.
3. Export books to sd card, through `Manage external storage`.
4. See that the name of the sd card is still `SD-Memory card (clean)`.

### Expected behavior

Should it be renamed to `SD-Memory card (books)`?

### Screenshots

![image](https://user-images.githubusercontent.com/6257434/208487299-676afc45-3d9d-439e-9a5f-52df53b04876.png)

### Versions and configuration

latest experimental version.

**Comment by PatrikLundell** [comment]
"Latest experimental version" is a useless version designation. At best, the version you used may still be the latest at the time your report is posted, but it may not be even then.
The proper way to provide Version and configuration information is to use the tools provided by the game to copy the info to the clipboard and the post it into that section of the report.

My description might be slightly off because I've enabled debug functionality for other uses, but in essence you:
- Hit escape to bring up the main menu
- Select debug menu
- info
- Generate game report
It may well be that the second and/and third step aren't required normally.

**Comment by fadybarsoum** [comment]
I also experienced this issue on G release running on Windows through steamdeck's emulation things (proton I think?). Might be related to https://github.com/CleverRaven/Cataclysm-DDA/issues/63786#issuecomment-1445253086 ? So it might already be fixed as part of https://github.com/CleverRaven/Cataclysm-DDA/pull/65248 ?
