### ISSUE TITLE
NPCs: prolonged activities should be auto-resumed

### ISSUE THREAD

**Issue by Antrocon** [CleverRaven/Cataclysm-DDA#62848]
### Is your feature request related to a problem? Please describe.

atm npcs require constant babysitting: you specify the activity for them, they do it until some trigger (lvl up, sleep, etc) and then revert to not doing anything (guarding for camp or following).
if i want npc to study from books, it means constantly resetting their activities 3-8 times a day, which is _very_ tedious and doesn't make sense from irl perspective. similar story with disassembly work, npcs go to sleep and i have to reset their assignments once they wake up.

### Solution you would like.

hence the suggestion: if npc was assigned a prolonged activity (disassembly, study, etc), he should perform it until it's cancelled by player or it cannot absolutely be continued (nothing more to disassemble, no books to study; but not temporarily like sleep or too dark).
additionally, "study from a book" book pickup range needs to be extended to 6 tiles like rest of components; or even better: let npc to auto-switch studying from one book to next one available in defined book storage zone.

### Describe alternatives you have considered.

kill all npcs i guess if they're so stupid :/

**Comment by PatrikLundell** [comment]
- Studying currently require you to select the book to study. Replacing that with some generic "read books you find" would be rather annoying to work around when you're trying to get your companions trained to be able to perform certain tasks.
- No notification of companions stopping to work due to darkness means that they'd just silently twiddle their thumbs until the sun rose again, at which point they'd probably promptly go to bed...

However, it's certainly the case that you'd often want companions to perform tasks until done, such as studying a specific book until they can no longer learn more from it, rather than having it broken off by reading a certain level.

Darkness is an issue unless you're using a floodlight or other permanent lighting. Depending on what phase you're in, you may want to keep your companions busy, meaning working during daylight hours and studying or crafting when it's dark outside, while at a later phase you just want them sort of occupied with something useful without bothering you too much, without a need to cram every bit of usefulness out of them.

**Comment by Antrocon** [comment]
then maybe tie it up to a npc misc rules option? if toggled off, task behaviour stays the same as now; if toggled on, behaviour as suggested here.
with books, same idea: if toggled off, current behaviour; if toggled on, npc will automatically pick & read next available book once original is fully read.
