### ISSUE TITLE
Extra milk from creature disappears if selecting a container that can't store it all.

### ISSUE THREAD

**Issue by FlyingSpaceRhino** [CleverRaven/Cataclysm-DDA#62855]
### Describe the bug

If you milk a creature, then select a container that can't hold all the fluid, the extra milk disappears with no option to use an extra container.

### Steps to reproduce

1. Get tame cow.
2. Get multiple small watertight containers that each can contain less than 40 units of raw milk.
3. Milk the cow
4. Select one of the containers to store the milk in.
5. After the selected container is filled to capacity, any extra milk simply disappears.

### Expected behavior

The player probably doesn't to take the time to get 40 units of milk, just to only keep 12 of it. 
There should be an option to select extra containers to store leftover milk. Or getting less milk should take less time.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2364 (21H2)
- Game Version: af92bd2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by flybye3o6** [comment]
are you able to milk again? i noticed this a long time ago and you could milk again to get the remainder, i thought that was intentional at the time or this was a temp solution for something else latter like there would be skill check involved to determine how much you would get before the animal dries up or dosent want to give anymore, but it would be nice if you could put it into more containers, also would be nice if you could use containers 6 tiles away maybe?

**Comment by Zanthra** [comment]
Like flybye3o6 said, I have also observed that any "extra" milk remains in the cow, and requires and requires you to milk the cow again to get it.
