### ISSUE TITLE
keybind for collapse and un-collapse all containers

### ISSUE THREAD

**Issue by flybye3o6** [CleverRaven/Cataclysm-DDA#62854]
### Is your feature request related to a problem? Please describe.

rigid containers will have items placed in them while looting, meaning that you have to 1 by 1 `U`nload or `<`uncollapse the rigid containers to unload things proper from your inventory after a loot run

### Solution you would like.

keybind for collapse and un-collapse all, same as `> hide contents` and `< show contents` keybinds but for all the containers in an inventory panel your looking at

### Describe alternatives you have considered.

zone Loot: Unload Everything

### Additional context

![image](https://user-images.githubusercontent.com/115079701/209433592-fc0ccbd4-2a08-4635-87d0-31dc791bfff8.png)

**Comment by andrei8l** [comment]
I have a preliminary implementation [here](https://github.com/andrei8l/Cataclysm-DDA/commit/4d4f017cecf884f2e00a659c77ddafaa16e26001), but I have a few questions:

- do you want this to (un)collapse the pockets or just override their status for display purposes only?
- should this (un)collapse recursively, or only the currently visible containers, or only the top-level containers?
- what keybinding do you propose for this?

and the most important question:
- WHY do you want to do this? I can't imagine that it'd be more convenient to uncollapse, manually select all the contents, then drop instead of dropping everything and unloading with a (personal) zone.

**Comment by flybye3o6** [comment]
for WHY different playstyles mostly, i have the unload zones setup but i dont tend to use them also unloading everything isnt a free action it takes time and sometimes that undesirable, i actually use the cardboard boxes to store low volume items to get past a tiles item limit, some of those boxes already have the items i want to keep in them plus items i dont, also i often find food thats gone rotten in firstaid kits
as for wanting to collapse all i have several full tiles that id like to collapse
1. (un)collapse the pockets 2. only the currently visible containers should be fine i dont get rigid containers inside rigid containers too often unless i put them there 3. hmmm thats a pickle i was looking at that, i personally was just going to replace < > only if there is no lag when doing it though

**Comment by anothersimulacrum** [comment]
Linked PR is open still.
