### ISSUE TITLE
Prison faction camp

### ISSUE THREAD

**Issue by oosyrag** [CleverRaven/Cataclysm-DDA#62880]
### Is your feature request related to a problem? Please describe.

A (low security) prison is a pretty ideal existing structure to use as a camp. Lots of space and facilities that could be useful for a group of survivors.

### Solution you would like.

Add prison base camp as an established building camp.

### Additional context

Just adding this issue for my to do list. Of course I wouldn't particularly mind if someone else is interested in tackling it.

**Comment by PatrikLundell** [comment]
I guess you can have two or possibly three variants in a prison location:
- The prison guards run the show, with the (former) inmates as something in the range from second class citizens to slaves. The prisoners may also all have been killed.
- The prisoners run the show, with all the guards dead and disposed of.
- A possibly utopian case of non violent convicts and non sadist guards from a low security prison joining up to face a new and more hostile world. (I'm not implying all prison guards are sadist, but it doesn't take many of those to antagonize the parties).

**Comment by JuVaPereira** [comment]
> I guess you can have two or possibly three variants in a prison location:
> 
> * The prison guards run the show, with the (former) inmates as something in the range from second class citizens to slaves. The prisoners may also all have been killed.
> * The prisoners run the show, with all the guards dead and disposed of.
> * A possibly utopian case of non violent convicts and non sadist guards from a low security prison joining up to face a new and more hostile world. (I'm not implying all prison guards are sadist, but it doesn't take many of those to antagonize the parties).

I can see all three options at the same time. Prisons have yards and blocs, it's just as possible to shock troops wipe out a entire yard bloc while the prisioners took another and the prision guards talk down the rebellion on a third yard block.

This would leave some player agency to decide the fate of this prison or leave for time to solve (maybe another yard blocks have a infestation or they get to a solution as time goes around).

This would not be unrealistic, there's [two](https://en.wikipedia.org/wiki/Esta%C3%A7%C3%A3o_Carandiru) [books](https://www.bookdepository.com/Carcereiros-VARELLA-DRAUZIO/9788535921694?ref=grid-view&qid=1672096956525&sr=1-1) by [Drauzio Varella](https://en.wikipedia.org/wiki/Drauzio_Varella) about the [Carandiru Massacre](https://en.wikipedia.org/wiki/Carandiru_massacre). Even in Varella interviews, he say that the massacre only wasn't bigger because the prison guards talked down the inmates to return back to their cells and blocked the shock troopers from entering other yards.
