### ISSUE TITLE
AMMO with reversible craft will only give default disassembly

### ISSUE THREAD

**Issue by flybye3o6** [CleverRaven/Cataclysm-DDA#62892]
### Describe the bug

ammo with reversible craft will only give the first listed craft items when disassembling 

### Steps to reproduce

make an acid bomb with 2 glass flasks, 2 hydrochloric acid, and 50 plant fiber
disassembly will yield 1 0.5L glass jar, 2 sulfuric acid, 1 short string

### Expected behavior

disassembly returns only the items used in craft
or remove `"reversible": true` from ammo crafts that use a choice of components
or idk something so i can pass uncraft tests

### Screenshots

the craft
![image](https://user-images.githubusercontent.com/115079701/209604019-6ebb2816-2f67-4ddc-b193-159754ea64a7.png)
the resulting item
![image](https://user-images.githubusercontent.com/115079701/209604026-7c8de118-26f7-4b31-8286-33cfb673978a.png)
this causes test failures
![image](https://user-images.githubusercontent.com/115079701/209604258-b881209f-35fa-409f-b1cc-93bc17ac969b.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2364 (21H2)
- Game Version: b3b97e0 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context
changing acidbomb `"type": "AMMO"` to `"TOOL"` gave this result and could be disassembled back into its parts(not a fix)
![image](https://user-images.githubusercontent.com/115079701/209606340-9ad3ce47-3d32-46d5-8522-0065c8081aba.png)
![image](https://user-images.githubusercontent.com/115079701/209606787-a8e8a850-a61e-455e-b695-d8f14c4c09f8.png)

**Comment by mqrause** [comment]
`count_by_charges` items currently don't store their components, so they'll always fall back to default components. That's because there might be issues with distributing components evenly to charges. So there's two ways to solve this.
1. Make ammo not `count_by_charges` anymore. This will happen but probably take a while.
2. Use the improvements from #62498 and #60885 to enforce components to be multiples of charges and then also store components for count_by_charges items. Still means waiting for those, but should be a fairly small change after that. Could also be done independently of those, but might be more issue-prone.

**Comment by flybye3o6** [comment]
quick fix i can do for my needs, its hacky and i dont like it but the molotov cocktail already does this
would be to change acid bomb type to `TOOL` and make a `sling ready acid bomb` and make that `AMMO`
rn ill just wait because i dont need anything until after next stable, and i dont want to add something just to reverse it latter
i was looking for other items effected by this and all i found was baseball, im sure their are other items but its likely to be a small list

**Comment by LyleSY** [comment]
Not fixed yet

**Comment by flybye3o6** [comment]
when this is fixed `"reversible": true` will need to be added back into `acidbomb` recipe
