### ISSUE TITLE
Turkey and Crow despawn when walking into closed gate to follow you.

### ISSUE THREAD

**Issue by GH0573K** [CleverRaven/Cataclysm-DDA#62929]
### Describe the bug

Basically just title, I don't know if this applies to other animals, however it could.

### Steps to reproduce

Walk into Cage or Enclosure.
Let your Pet follower walk into the CLOSED chicken wire gate,
They disappear and go to another plane of existence.

### Expected behavior

They should just be blocked from moving, not vanishing.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2364 (22H2)
- Game Version: 1894579 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by oosyrag** [comment]
Are you sure they're not just on a higher z level? The two animals you mentioned do have the ability to fly.

**Comment by GH0573K** [comment]
@oosyrag negative, I checked. Plus I don't have anything to really fly onto and stay onto.

**Comment by GH0573K** [comment]
oh piss, gotta reopen it

**Comment by PatrikLundell** [comment]
Both creatures are birds capable of flight. I've seen tamed turkeys "disappear" when trying to follow me in various situations. I've found some on the roof and some have just disappeared, and I'm fairly sure they move to a higher Z level. Since they can fly, they don't need to stand on anything.

However, a creature flying over an obstacle to follow the player ought to be capable of returning to the player's Z level, so there's an issue here even if they're not despawning.

It might be relevant to ask whether experimental Z levels were used, as that can affect visibility and potentially pathing. In my case the experimental Z levels were disabled, as that's the default state.

I've since come to the conclusion that turkeys (and any other flying creatures I might tame) need to be tied down to be kept within an enclosure such as a chicken coop (and really anywhere else).
