### ISSUE TITLE
Stealth support.

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#63]
Add a "spotted" and "identified" flag to the monster structure.  Might expand to more flags in the future. "visibility"?
Add a perception check in ??? to determine if the monster is spotted, and another to determine if it's identified.
Augment game::draw_ter() or monster::draw() to either draw nothing, an alternate glyph*, or the actual glyph for the monster.
Also need to augment game::mon_info() to only display spotted/identified monsters.
Need to make sure non-monster glyphs don't appear on this list, need another flag for that?
Same for look_around readout.

*Examples of alternate glyphs: triffid: sapling zombie: corpse
##

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
