### ISSUE TITLE
Framework Idea for Armor

### ISSUE THREAD

**Issue by kacyroush** [CleverRaven/Cataclysm-DDA#63023]
### Is your feature request related to a problem? Please describe.

At present, we no longer have the old system of 'padding', and each piece of armor is an individual item in and of itself, which can cause confusion. This would allow for less confusion in the long run, streamline adding new armor, and allow us to put 'padding' back.

### Solution you would like.

Essentially, actual pieces of armor are now 'mods' for clothing. We can restrict certain pieces of armor with specific values, by example forbidding lycra, spandex, and neoprene, or requiring a specific amount of coverage or thickness. (No putting a cuirass on a belly wrap, or kevlar padded sport bras.) This would also clean up a small number of recipes in the crafting menu, specifically those that combine multiple pieces of armor into a singular unit, as well as allow for a streamlined 'piecemeal' approach. (IE plate-armored arms with light armor elsewhere, for unarmed users.) In addition, I think it might be possible to unify the materials as well, allowing the crafting menu to demand a specific type of ingredient to produce a specific material, and then generate the item from said material. IE using leather patches instead of cotton for a 'pants' recipe produces leather pants, and so on and so forth, even up to using biosilicified chitin for acid-resistant chitin boots. By putting the numbers on the materials themselves, so to speak, it would reduce a great many 'duplicate but different material' recipes in the crafting page, as well.

### Describe alternatives you have considered.

I've given a few other concepts thought, but they all require more work than this would, which is saying something.

### Additional context

I am loathe to try and use specific numbers, but for an example of the material changes, we could say that 'tempered steel' as a material grants, for example, 160% cut, bash, and pierce damage, and 500% cut resistance, 150% bash resistance, and 125% ballistic resistance. (By no means take these as desired numbers.)

Then the 'base' recipe (assuming 'plain' steel) could be something like 10 bash, 10 cut, etc etc etc, and the materials apply their modifiers to the base recipe.

**Comment by ZhilkinSerg** [comment]
`sew_advanced` item is still available and can be used in mods

**Comment by kevingranade** [comment]
I'm pretty strongly against this concept. The padding attachment system you reference in particular was a disaster where the dominant meta was padding and reinforcing and armoring every article of clothing, most of which made no sense.
In addition, making *everything* procedural makes balancing more difficult because you essentially have to use the game code to check the stats of an article of clothing.

Those are the main problems with the overall approach, the problem with this suggestion in particular is you don't address those problems. Without a compelling approach for how tobadress those issues *better than the status quo of enumerating items and recipes*, this is a non-starter.
