### ISSUE TITLE
Basecamp crafting consumes no ingredients

### ISSUE THREAD

**Issue by moxian** [CleverRaven/Cataclysm-DDA#63052]
### Describe the bug

This is pretty much the first time i'm dealing with the basecamp system so apologies if i'm doing it wrong.

I have two NPCs with me. I've set up a basecamp. Assigned both to the camp.
I have a fridge with 34 cattail rhizomes.
I sent one of my npcs to convert the rhizomes to starch (because i'd rather not do it myself).
When they finished, i had the 17 starches (as expected), but also the original 34 cattail rhizomes.

Something something infinite food glitch.

Tangentially: the resulting starch is dropped onto the *floor* where the fridge is, not into the fridge itself. Which is both unfortunate and easy to overlook, but also unrelated to the issue at hand.

### Steps to reproduce

- Load attached savefile
- Inspect the fridge, see 34 cattail rhizomes + 17 starches
- Go to builletin board (bit to the west), ask to make `[B] Cook: Cattail Starch`
- When prompted for the amount, enter the maximum of 17
- `|` -> wait 6 hours until finished
- Inspect the fridge again, see 34 cattail rhizomes + 17 starches + 17 more starches

### Expected behavior

materials get consumed

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2364 (21H2)
- Game Version: ba42c0a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

Savefile: [Winters-starch.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/10376935/Winters-starch.zip)

**Comment by PatrikLundell** [comment]
/confirmed

It's been reported before #58375 (and it was still happening last I played, maybe a month ago). The reason for ingredients to sometimes not get consumed is unknown. Note that it doesn't always happen.

If I know it happens I destroy the ingredients by throwing them into a fire or dump them onto a "trash pile".

My guess is that it's caused by the weird code that first searches and selects ingredients for usage and then searches for ingredients to destroy, and that the second pass somehow doesn't find the items. Usage of the newer item references that include a reference to specific item (stacks) rather than just the item type plus a count might both fix the issue and remove the need for the second search pass.

**Comment by moxian** [comment]
> Note that it doesn't always happen.

The provided save + reproduction steps worked 3/3 times for me so far.

**Comment by PatrikLundell** [comment]
Yes, I don't think it's random, but rather that there are some unidentified conditions that causes items to not be consumed as they should under some circumstances, but not under others. Some food in a location can be consumed while other items are not, for instance. Once the conditions are met, the results seem to be the same for the same save.
