### ISSUE TITLE
removal/alteration of flag depicting holocaust imagery.

### ISSUE THREAD

**Issue by 7erracotta** [CleverRaven/Cataclysm-DDA#63068]
### Is your feature request related to a problem? Please describe.

While the addition of pride flags into the game is very much a step in the right direction, the lesbian "labrys flag" uses imagery that originated in Nazi Germany during the holocaust. the "black triangle" which was used to classify "anti-social" prisoners.  The flag is also associated with terfs.

The inclusion of this flag feels unnerving and strange, as the more common, often more widely used pink and orange lesbian flag is already within the game. 

### Solution you would like.

I'd recommend either having the labrys flag removed, or have its description changed to acknowledge its Nazi symbolism and holocaust origin.

**Comment by 7erracotta** [comment]
im using the latest build, the holocaust reference is both within the description of the variant itself and in the Ultica tileset.

**Comment by andrei8l** [comment]
It's a lesbian symbol today and its history doesn't matter to the game. Don't empower the extremists by reserving arbitrary symbols for them.

**Comment by oosyrag** [comment]
It was MSXotto+, and the labrys flag is a real thing that does look like that. The description accurately describes the appearance of the flag and doesn't make any presumptions about it's meaning or history.

**Comment by Zireael07** [comment]
https://queerintheworld.com/labrys-lesbian-pride-flag/ 

Even the LGBT+ community acknowledges the Holocaust connection and says the flag is problematic (and decreasing in usage) due to that.

According to Wikipedia there ARE other pride flags in use: https://en.wikipedia.org/wiki/Lesbian_flags that do not have the black triangle

@andrei8l: "its history doesn't matter" is a very shortsighted view. Yes, my understanding is that the triangle has been "reclaimed" but the reference makes me uneasy (As a straight person living in a country that had concentration camps built by the Nazi occupiers)

**Comment by andrei8l** [comment]
> @andrei8l: "its history doesn't matter" is a very shortsighted view. Yes, my understanding is that the triangle has been "reclaimed" but the reference makes me uneasy (As a straight person living in a country that had concentration camps built by the Nazi occupiers)

I agree with that, but it's not our place to decide for the people using this symbol.

> Even the LGBT+ community acknowledges the Holocaust connection and says the flag is problematic (and decreasing in usage) due to that.

Your link says "many" people are looking for other flags because this one is trans-exclusionary rather than due to the history of the black triangle. That would be a valid reason to remove it, but it looks like we have pride flags for almost all other LGBTQ subgroups.

**Comment by blacktarheroin** [comment]
If you don't like the flags, just burn them like I do with all the pride flags. If anything this game needs more controversial flags.

**Comment by Zireael07** [comment]
@andrei8l: I linked to a Wikipedia page that shows other flags used by this particular LGBT subgroup. One of those could be used instead without having a problematic historical reference

**Comment by Fris0uman** [comment]
The other more generic lesbian flag is already in by the way. My understanding of the labrys flag is that it is specifically a way to re appropriate the symbols from that time to get them out of the hands of the nazy, there's nothing pro nazy ideology in that flag. Also through the short search I made to make the initial PR it came out that all the lesbian are problematic one way or another.

**Comment by kevingranade** [comment]
The symbolism is blatantly an attempt to re-appropriate the nazi symbolism, not to support nazis.
The objections to this flag cited in the article are incredibly weak, I'm just not buying it being problematic enough to deserve removal.
