### ISSUE TITLE
Tanker trucks

### ISSUE THREAD

**Issue by Shodan14** [CleverRaven/Cataclysm-DDA#63061]
### Is your feature request related to a problem? Please describe.

The largest vehicle-mounted tank in CDDA can hold 200L. [Real-world tanker trucks](https://www.drivingtests.co.nz/resources/what-is-a-tanker-truck/) hold between 5000 and 20,000L. It seems strange to not have any in CDDA.

### Solution you would like.

It would be nice to have small/medium/large (~5000/13,000/20,000L) vehicle tanks represented in the game. 

### Describe alternatives you have considered.

Keep making horrible abominations made out dozens of internal and external tanks.

**Comment by Karol1223** [comment]
This can't really work when empty tiles can only hold 1000 L of items on them. Vehicle parts may not have that limitation but:
- You'd have a vehicle tank item that can hold 5000 L for example when mounted but only 1000 L when in item form and is only 1000 L of volume in itself
- When that tank was to break odds are the game would break with it, or at least give a bunch of scary error messages

**Comment by moxian** [comment]
The real-world tanker trucks are rather big, and would not fit into a single in-game tile. If we were to build a tanker truck in cdda, the liquid-containing part would be something from 2x3 to 4x5 in size. With current 200L parts that translates to 1200L-4000L.
You can add such a tanker truck variant to the game today.

However that is 6-20 individual barrels, which 1) don't mix liquids in them and 2) might be annoying to operate in game.
We could hypothetically have a bigger tank on a truck *if* we somehow had multi-tile vehicle parts. It would then also be reasonable for individual sub-parts be relatively small in item size (existing sheet metal, pretty much), but combine into something that holds 500L - 1000L per tile.

Alas, multi-tile vehicle parts like that sound pretty tricky to implement

**Comment by Shodan14** [comment]
> This can't really work when empty tiles can only hold 1000 L of items on them. Vehicle parts may not have that limitation but:
> 
>     * You'd have a vehicle tank part that can hold 5000 L for example when mounted but only 1000 L when in item form and is only 1000 L of volume in itself
> 
>     * When that tank was to break odds are the game would break with it, or at least give a bunch of scary error messages
> 
> 
> Not saying the idea is bad, just that at the moment this isn't possible and would require quite a bit of code changes to be viable.

I mean even 1000L would be a decent start. I'm not 100% up on the latest fluid handling, but doesn't fluid on the ground just make puddles anyway? I guess if it doesn't spill in a realistic way, just delete the extra and say it got absorbed into the ground or whatever?

**Comment by PatrikLundell** [comment]
The cargo vehicle part is capable of containing half a cubic meter (500L) of stuff. I'm not sure a cubic meter sized tank vehicle part would be good, because it would have to take up a full cubic meter of space to be able to contain almost a cubic meter of fluid, and a cubic meter sized part would likely frequently cease to exist once it's constructed due to the lack of space to place it within the placement spilling distance, which would be rather bad. A part likely can't be larger than what can be fit on top of an empty work bench, or this kind of trouble may be too frequent (and even then, new logic to push stuff out of the way to make room for an item that otherwise couldn't be dropped anywhere might be needed (and then cause a mess when items are displaced out of their sorting zones)).

Also, I don't know if there is any kind of volume accounting for the sum of the volume of parts on a vehicle tile. If there is, there might be issues in that department as well.

**Comment by Zourin2** [comment]
If you consider 'transport tank' to be a container of:
200L-volume per tile
explosive
have variants like most vehicle wall segments
aren't passable tiles
Operate on a 'total per vehicle' status for its condition. If one tile is destroyed, it drains from all tanker tiles.
