### ISSUE TITLE
(modded) big slowdown while crafting

### ISSUE THREAD

**Issue by Devengel** [CleverRaven/Cataclysm-DDA#63072]
### Describe the bug

as i sent my character to sleep, halfway through the night the game slowed down massively, like sleeping in a megacity full of undead.

i am playing in innawood, so wilderness, high performance. etc.

### Steps to reproduce

1.download and open save ingame
2.shift + a to continue the craft in your hand
3.notice the slowdown

### Expected behavior

no slowdown

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2364 (21H2)
- Game Version: c4b3769 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Innawood [innawood],
    Tamable Wildlife [Tamable_Wildlife],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Megafauna [megafauna]
]

### Additional context

[Babylon.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/10390257/Babylon.zip)
here is the save

**Comment by andrei8l** [comment]
Why close? This is a valid and reproducible bug report

**Comment by mqrause** [comment]
/confirmed

My VS profiler is bugging out a bit so I can't give more details, but the slowdown seems to be caused by creature movement taking up 50% of processing time. It's pretty noticeable because time speeds up at around the 90% mark of the craft.

**Comment by zakhad** [comment]
I'm also encountering some something similar but this i suspect is because i'm hallucinating, and it's spawning npc's that can't pathfind out of the freshwater research station as i closed the door upstairs (can they open doors?) I've attached my save, the screenshot with the error is what happened when i reloaded the game, i had some antidepressants while recovering from a drug withdrawal. 

- OS: Windows
    - OS Version: 7
- Game Version: 908472c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
Mods loaded: [
[
  "dda",
  "SD_Magcrafting",
  "StatsThroughSkills",
  "Arcana",
  "MMA",
  "magiclysm",
  "speedydex",
  "no_npc_food",
  "Medieval_Mod_Reborn",
  "blazeindustries",
  "useful_helicopters",
  "Mining_Mod",
  "Dorf_Life",
  "Arcana_Magiclysm_Patch",
  "Tamable_Wildlife",
  "no_hope"
]


[Zakhadia_BigCity.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/10668560/Zakhadia_BigCity.zip)
![image](https://user-images.githubusercontent.com/5264667/217068832-1917f6e9-3b0b-447e-a419-2d04be30bbbb.png)
![image](https://user-images.githubusercontent.com/5264667/217068878-3ddff2fa-970d-490d-bb82-15cf1403c7e0.png)
![image](https://user-images.githubusercontent.com/5264667/217068886-ed92e891-5d09-4cd3-93db-0e64687750db.png)

**Comment by zakhad** [comment]
![image](https://user-images.githubusercontent.com/5264667/217072991-6d3e2b29-d3f8-4b8e-917b-33ed1c6926c7.png)

Upon editing my save file setting the fatigue to 0 so i would wake up, and go upstairs, and unlock the door, lo and behold a npc starts to walk out so it's mission or objective related trying to pathfind outside of a locked location that they can't normally interaction with so the game is constantly re-checking or some such.

**Comment by andrei8l** [comment]
> I'm also encountering some something similar but this i suspect is because i'm hallucinating, and it's spawning npc's that can't pathfind out of the freshwater research station as i closed the door upstairs (can they open doors?) I've attached my save, the screenshot with the error is what happened when i reloaded the game, i had some antidepressants while recovering from a drug withdrawal.

Profiling shows that this is a different issue. Please open a separate bug report for it so it doesn't get lost

![Screenshot from 2023-02-06 22-02-34](https://user-images.githubusercontent.com/68240139/217073425-c56699bd-587d-499f-b0ba-2cfdb1b93b75.png)

**Comment by mqrause** [comment]
Are you sure it's different? The original report is also caused by movement code.

**Comment by andrei8l** [comment]
> Are you sure it's different? The original report is also caused by movement code.

OP is a vision issue

![Screenshot from 2023-02-06 22-22-59](https://user-images.githubusercontent.com/68240139/217077161-051dbf4c-3917-42a8-a557-ee27f4ec34cb.png)

**Comment by mqrause** [comment]
Ah, right, thanks. I only got to `monster::plan` before my profiler bugged out.

**Comment by ehughsbaird** [comment]
This issue appears to be caused because the weather is oscillating between `rain` and `rainstorm`, which have different sight penalties, causing the level cache to be rebuilt each time.
https://github.com/CleverRaven/Cataclysm-DDA/blob/7216560e9acd3cbe7d2976a3489965fb3f481ada/src/weather.cpp#L975-L979
![image](https://user-images.githubusercontent.com/44244083/218336469-61578f6e-3bc3-411f-949e-4c22ba2583b2.png)

Commenting out the code linked above results in a noticeable speedup with this profile:
![image](https://user-images.githubusercontent.com/44244083/218336977-a1b257c5-ebfa-41e4-8a8c-12b53cef1d23.png)

**Comment by ehughsbaird** [comment]
...and it oscillates between those because since 1f8e0a1cb43, the weather updates every turn, instead of waiting till `nextweather`
https://github.com/CleverRaven/Cataclysm-DDA/blob/7216560e9acd3cbe7d2976a3489965fb3f481ada/src/weather.cpp#L944-L947
https://github.com/CleverRaven/Cataclysm-DDA/blob/7216560e9acd3cbe7d2976a3489965fb3f481ada/src/do_turn.cpp#L612-L619
