### ISSUE TITLE
Deconstructing Downspout Overwrites Underlying Terrain

### ISSUE THREAD

**Issue by ChromePoptart** [CleverRaven/Cataclysm-DDA#63188]
### Describe the bug

When "Deconstruct Furniture" is used on a downspout, the terrain tile that is left behind is a pavement tile, even if the tile that was below the downspout originally was grass.

### Steps to reproduce

1. Find a downspout.
2. Use "Look Around" to observe the terrain underlying the downspout is grass.
3. Use "Deconstruct Furniture" on the downspout.
4. Observe that the resulting terrain tile is pavement.
5. Find another downspout with underlying grass.
6. "Smash" the downspout.
7. Observe that the resulting terrain tile remains grass.

### Expected behavior

"Deconstruct Furniture" shouldn't change the terrain tile originally beneath the furniture that is deconstructed.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2486 (21H2)
- Game Version: 5772feb [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Bionic Slots [cbm_slots],
    Portal Storms Ignore NPCs [personal_portal_storms]
]

**Comment by cake-pie** [comment]
Technically, both bash and deconstruct overwrite the terrain. They have to, because the downspout is a terrain tile and not actually furniture -- there is actually no "underlying terrain". It just happens that in the default tileset, the tile for the downspout looks like there is grass under it, and it becomes dirt after bashing, which looks similar. Whereas deconstruct turns it into a flat roof (not actually pavement) -- a mistake which is immediately visually apparent.

https://github.com/CleverRaven/Cataclysm-DDA/blob/c0335423ae9aed250c392a323372d0dc9170c112/data/json/furniture_and_terrain/terrain-roofs.json#L161-L169
