### ISSUE TITLE
Power armor can be destroyed with unarmed attacks

### ISSUE THREAD

**Issue by Raikiri** [CleverRaven/Cataclysm-DDA#63221]
### Describe the bug

I'm using tiger style and sometimes when I attack enemies with it my power armor gets damaged.

I have not seen this happen to other armors, seems to be a power armor exclusive problem.

### Steps to reproduce

1. Equip power armor and tiger style
2. Attack zombies for a while.
3. Note that during slams (?) the armor is occasionally damaged

### Expected behavior

I expect my power armor to not get damaged by my own attacks.

### Screenshots

![image](https://user-images.githubusercontent.com/1657728/213863257-e6197c12-ebf5-4002-ac67-d4df6b5f32c0.png)

### Versions and configuration

current experimental

### Additional context

I don't know whether this is a problem with the power armor or with tiger style specifically that I'm using. This happened to me twice in a row while attacking zombie technician and then with a feral human, so it's unlikely enemy-related.

**Comment by alp7292** [comment]
clothing(and armors) that cover attack vector can be damaged like any weapon when used its very annoying its just better to use unarmed with no gloves and boots as gloves and boots can be damaged but doesnt provide any benefit. i lost a lot of steeltoed boots and tactical gloves  this is of course an issue and needs to be fixed

**Comment by flybye3o6** [comment]
this happens because anything that covers your hands has a chance to take damage in hand to hand combat
iv had this with other full body suits like the faraday chainmail
i couldnt think of a suitable fix other then
- redesign of the armor system so that body parts of armor can break without the whole thing breaking
- remove all full body armor and replace it with armor sets (helm, chest, legs, boots, arms, gloves)
- add a flag so some armors and gloves wont take damage in hand to hand combat, or have a very low roll chance to take damage

**Comment by Raikiri** [comment]
why does have to be damaged at all from your own attacks?

**Comment by ProjectileWaterfowl** [comment]
> why does have to be damaged at all from your own attacks?

Newton's third law. Whenever you hit something with your power armor, the same amount of force is imparted upon it. If you were hitting hard enough that you could theoretically damage power armor, you could then damage *your* power armor by doing so. Though, it could be argued that the limbs could absorb a good bit of that (They aren't being hammered in a vice, after all), that the forces involved aren't usually great enough to damage power armor anyway, etc.

**Comment by Raikiri** [comment]
> Newton's third law. Whenever you hit something with your power armor, the same amount of force is imparted upon it
yeah, great. then following this logic, every time you hit anything with any melee weapon, the weapon should get damaged just as much as your target. yet somehow the problem seems to only arise with armors and unarmed attacks. 

or when you kick somebody in the face with your foot, the foot is supposed to be damaged as much as the said face. no, this is really not how combat works. obviously attacker directs their strikes and concentrates pressure in a way to minimize damage to the attacking implement and to maximize damage on the receiving end.

besides, in the example above i'm punching unarmed people, not other characters wearing power armors.

**Comment by ProjectileWaterfowl** [comment]
> then following this logic, every time you hit anything with any melee weapon, the weapon should get damaged just as much as your target. yet somehow the problem seems to only arise with armors and unarmed attacks.

You're wrong. Melee weapons do follow that logic to the same degree that unarmed attacks do. They are also arguably better designed for such a task, since bladed and piercing weapons are not as focused on dealing damage through pure kinetic force, and blunt weapons tend to be a large and solid piece of steel rather than an advanced suit that has to conform to the body.

> or when you kick somebody in the face with your foot, the foot is supposed to be damaged as much as the said face. no, this is really not how combat works. obviously attacker directs their strikes and concentrates pressure in a way to minimize damage to the attacking implement and to maximize damage on the receiving end.

First off, this is how *physics* works, and last time I checked hand-to-hand combat was subject to that. Second, when I say force, I do not mean damage, I mean kinetic energy. Note what I said about limbs earlier.

> besides, in the example above i'm punching unarmed people, not other characters wearing power armors.

Hit anything hard enough with anything else, and it'll break. Still shouldn't be taking damage in this case since power armor (especially power armored enemies) take tons more than that without any real damage normally.

**Comment by Raikiri** [comment]
I really don't understand what you people are trying to prove here. That it's normal? That it's good for the game? "Not a bug"? "Expected behaviour"?

**Comment by ProjectileWaterfowl** [comment]
I'm answering a question.

> why does have to be damaged at all from your own attacks?

**Comment by alp7292** [comment]
fucking bulletproof armor should not be damaged by hitting a normal flesh zombie with human strenght

**Comment by alp7292** [comment]
bro can you stop beign 🤓 and actually think. a bulletproof vest that can take m240 and  m249 without  getting a single scrath can be damaged by a punch with human strenght. you act like too smart without using common sense

**Comment by alp7292** [comment]
![Ekran Görüntüsü (108)](https://user-images.githubusercontent.com/82234624/214248958-f3cb8c3c-c545-4952-be68-819b2266be50.png)

**Comment by Zireael07** [comment]
>  do you really think a bulletproof vest that can take m240 and m249 without getting a single scrath can be damaged by a punch with human strenght

Power armor is much more than a bulletproof vest. So yes, it shouldn't be damaged (maybe except special effects like the hulk throw)

**Comment by alp7292** [comment]
hulk throw already dameges clothings and armor if it deals enough damage

**Comment by ProjectileWaterfowl** [comment]
> bro can you stop beign 🤓 and actually think. do you really think a bulletproof vest that can take m240 and m249 without getting a single scrath can be damaged by a punch with human strenght. you act like too smart without using common sense

You may understand what I'm saying more if you read. I have answered the question, and have not said that... wait, where did the bulletproof vest part come from? Anyway, haven't mentioned those, nor have I said it should take damage from a punch with regular human strength. All of these have been your own conjurations.

**Comment by alp7292** [comment]
you know i am talking about power armor this issue is about power armor getting damaged by using unarmed and if you say it should be damaged you are wrong

**Comment by ProjectileWaterfowl** [comment]
> you know i am talking about power armor this issue is about power armor getting damaged by using unarmed and if you say it should be damaged you are wrong

Did I say it should be damaged?

**Comment by alp7292** [comment]
then what are you talking about whole page

**Comment by alp7292** [comment]
you just wanted to talk in this issue out of context?

**Comment by Zireael07** [comment]
> Did I say it should be damaged?

Just like others I understood your answer(s) as saying it should be damaged

**Comment by flybye3o6** [comment]
> why does have to be damaged at all from your own attacks?
a tradeoff mostly, as a survival game you manage resources every conflict you lose or risk losing something. when you attack with a weapon that weapon risks taking damage, when you use unarmed your hands are your weapon so you should risk hurting them or damaging whatever is covering them
as it is rn the tradeoff is too much and needs to be reduced by a lot in most cases, but to remove it entirely well you need to explain why that would be the case, and dont just say its because its power armor, there is a lot that could break inside power armor and if anything the user poses the most risk damaging it then any outside force
if the trade off cant be reduced to an acceptable amount like the RNG rolls cant be lowered anymore then sure id accept something like power armor not taking damage from unarmed combat, but there is more then just power armor effected by this and id rather have a fix for all of it then just 1 suit

**Comment by ProjectileWaterfowl** [comment]
I've been explaining *why* armor can take damage in reply to a question about why the possibility it for taking damage at all should be retained (Or, that's at least how I interpreted "why does have to be damaged at all from your own attacks?" as a response). I explained the base physical reasons why it would happen, and below it mentioned a couple reasons why it might not take as much damage while still receiving the same amount of force. Everything after that has maintained the same position, and on the second one I explicitly said it probably shouldn't be taking damage in this scenario.

**Comment by MoonlitRiverlight** [comment]
This could be solved by armor pieces in relevant areas (Hands and feet for attack, arms and legs for blocking, shoulders for smashing, head for heabutts if these are even a thing in martial style.) having a structural integrity value that alters the incoming damage, negating damage up to its assigned threshold, with damage exceeding that value being reduced. (I've had my first activity suit get destroyed in a single blow just after getting it.)
