### ISSUE TITLE
Dynamic Soup Cauldron

### ISSUE THREAD

**Issue by Grubleafeater** [CleverRaven/Cataclysm-DDA#63299]
### Is your feature request related to a problem? Please describe.

Soup recipes are always pretty specific ingame, but they don't need to be. How about letting us use a Cauldron to turn, say, up to 25 liters of ingredients into soup using a equal number of liters of water? 

### Solution you would like.

Cauldron tool that can be placed on a fire and used to cook massive amounts of ingredients as long as the fire remains lit over the timespan, combining all the ingredients into a finished soup that uses the ingredients to calc the total vitamin and calorie value, along with a special 'Soup Suitability' stat the food has to calculate the total joy of the soup.

If it were to be made more complex, there could be multiple KINDS of soup, like porridges, with different suitability for each type and ingredient--if someone were to put chocolate into a meat soup, I'd call them a lunatic, but a chocolate porridge makes a OK amount of sense, for example.

**Comment by PatrikLundell** [comment]
It doesn't fit well with the current food system, as it produces a discrete number of "serves", so you have to provide the exactly correct "volume" of ingredients for a specific number of "serves", and different ingredients may have different "volumes", such that you may need a higher number of one item than another when given a choice it a recipe. It also doesn't fit well with the recipe system, but that might be a lesser issue to deal with. It doesn't help that there is no obvious formula for calculating how much ingredients you need, as recipes involving boiling and water are allowed to consume more volume than it produces to account for losses due to evaporation.

I'm not saying it's a bad idea, just that it's a bad fit with the current system.

**Comment by DSeyka** [comment]
Project Zomboid has a system kind of like proposed one: you have basic "dishes" (soup, stew, salad) to which you can add "compatible" ingridients/spices up to a point which is then cooked or eaten raw, with fun/satiety/hydration stats depending on ingridients and player skill.

While this sounds good on paper, this leads to either painstakingly minmaxing numbers or people just adding random ingridients because they don't care, and just want to fill up hunger meter (or get cooking XP). So basically, it'd require A LOT of work (considering the sheer amount of edible stuff in CDDA) for dubious gains.

**Comment by Grubleafeater** [comment]
I'd say you can handle volume by removing about half the water volume and rounding down to create .25 liter servings overall. *shrug*.
