### ISSUE TITLE
Install 100L and 200L tanks should require a drill

### ISSUE THREAD

**Issue by SurFlurer** [CleverRaven/Cataclysm-DDA#63322]
### Is your feature request related to a problem? Please describe.

2L, 10L, 20L and 60L tanks need a drill to install. But that's not the case for 100L and 200L drums. A brief search revealed that PR #34850 explicitly specified the required tools to install a 100L drum. I don't know why install requirement didn't include a drill. But I believe it should include that.

### Solution you would like.

At least they should all need a drill. Maybe more consistent tools requirements across other aspects, like a wrench and welding tools?

### Describe alternatives you have considered.

Leave it as is.

**Comment by Profit0004** [comment]
Was thinking of why the other tanks would require a drill at all, but after a moment's thought it is because they only have one opening where most 200L drums have 2 openings.   I think the drill requirement on the smaller tanks might be to allow a fuel line to come out of them and still leave one open for fuel intake where the 200L tanks already have that second opening that is threaded for the fuel line (A  2" threaded opening and a  3/4" threaded opening).
