### ISSUE TITLE
Bare Bones Basecamp breaks faction camp talk tree

### ISSUE THREAD

**Issue by cake-pie** [CleverRaven/Cataclysm-DDA#63320]
### Describe the bug

It was intended that NPCs should have different talk options when asked about faction camps depending on whether their current position is a valid overmap tile for starting a camp on:

https://github.com/CleverRaven/Cataclysm-DDA/blob/4b6270c53d386cc07cfab78984d3461e796da3a8/data/json/npcs/TALK_FACTION_CAMP.json#L15-L29

The option to start a camp should only show up when they are on a valid starting tile, otherwise the option to get a dynamically generated list of possible camp starting locations should be available instead.

In practice, the barebones camp is valid anywhere:
https://github.com/CleverRaven/Cataclysm-DDA/blob/4b6270c53d386cc07cfab78984d3461e796da3a8/data/json/recipes/basecamps/recipe_groups.json#L100-L104

Therefore, it is impossible for the second option to show up.

### Steps to reproduce

Go to different locations with a follower NPC; talk to them about faction camps, and never see the option for `TALK_CAMP_SITES`

Delete the barebones camp def from `recipe_groups.json`

Repeat and get the option show up in any location that doesn't allow any other kind of camp.

### Proposed resolution

`TALK_CAMP_SITES` is a dynamic line added in #45178 and was intended to pull from game data (`all_faction_base_types` in `recipe_groups.json`) a list of valid camp starting sites. This seems like it would confer some advantages over `TALK_CAMP_TUTORIAL_BUILDING` which relies on `TALK_FACTION_CAMP.json` being manually updated with new information.

However, in the current state, if you make `TALK_CAMP_SITES` show up it just dumps all the descriptions, including some "duplicates" due to separate entries for different evac shelter designs:
![campstarts](https://user-images.githubusercontent.com/28502722/215251096-c8951775-a519-45c2-9f54-076c23845d59.png)

Ideally each camp type's definition entry in `all_faction_base_types` would have separate name and description fields, so that they can all be pulled dynamically -- the player first gets presented with a list of names to pick from, and is then given the detailed description when they choose one of the options. We'd then be able to migrate all the "hardcoded" `TALK_CAMP_TUTORIAL_BUILDING` content into the corresponding camp type defs, which should be more maintainable than the current arrangement where the tutorial is more prone to becoming outdated.

### Additional context

See also related: #63319

### Versions and configuration

4b6270c

**Comment by PatrikLundell** [comment]
I haven't verified it, but you're most likely correct in that the option became unavailable.

While automatic extraction of alternatives is to be preferred over manual addition to the dialog, there is the problem that there are near duplicates due to the existence of variants of the same building. From a player perspective, an evac center is an evac center, but from the base camp implementation perspective there are 3(?) different variants due to the presence of that many different layout variants. Thus, from a description point of view all of the variants are the same thing, but they have to be the right one for the actual building selected.
As far as I can imagine, this would require some kind of type descriptor that the UI would draw upon, and an variant description that would contain the actual implementation and would refer to the type descriptor for the common parts. I don't know if this would result in less maintenance work, though, but a required reference from the base to a JSON entry for the dialog that might in its turn reference a further JSON entry for common dialog might make it harder to miss to add those parts.
