### ISSUE TITLE
a bug maybe in aftershock

### ISSUE THREAD

**Issue by cnlzn** [CleverRaven/Cataclysm-DDA#63336]
### Describe the bug

In the latest experimental version, when I created a world, I found a bug in aftershock that caused some special terrain in the world not to be generated

### Steps to reproduce

Create a world with only cdda and aftershock, select a character to enter, and the log bar will indicate that some special terrain cannot be generated, such as the refugee center.

### Expected behavior

希望日志不会报错，能正常生成特殊地形

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2486 (21H2)
- Game Version: a7cc07a [64-bit]
- Graphics Version: Tiles
- Game Language: 系统语言 []
- Mods loaded: [
    浩劫余生 [dda],
    余波未尽 [aftershock]
]

**Comment by Maleclypse** [comment]
So what that error is saying is that there are more types of map specials than could be placed on a single map and because of this you might potentially be unable to use certain starting scenarios without multiple attempts to create a world.   It's not just an Aftershock bug and it is unfortunately a problem with the core of our map generation process.   I'm going to close this issue because it is a well known error and get's multiple issues on it regularly.  We appreciate error reports even if they turn out to be duplicates.
