### ISSUE TITLE
Ideas for future PRs 4: Revamp of next year/season scenarios

### ISSUE THREAD

**Issue by Termineitor244** [CleverRaven/Cataclysm-DDA#63349]
### Is your feature request related to a problem? Please describe.

The current scenarios to start in the future (Next year and in winter) seem to me lack they... Suck, they are boring, you just start surrounded by a bunch of heavily mutated zombies, with only a few professions themed around developing something in all the time since the cataclysm, and even they are... Well, not very good. The rest of professions are worst since they spawn like a day one survivor in the worst kind of circumstances.

These scenarios are made even worse because of the fact that the player can change the starting day/season in the world building options...

### Solution you would like.

Change a lot of the "next season/year" scenarios for them to be fun.

Ideas: to start in an isolated, secure location with some crafting gear, and make the character play around the idea of sneaking around and living of what little they can find in a world of evolved zombies, important difference here is that the player would not spawn surrounded, to give them time to decided what to do, pretty basic change I guess, but effective in improving the current scenarios.

Another idea is to make an scenario where the character starts in a walled, "secure" location, an NPC-made survivor camp, but something happened, and the rest of survivors died, you are now alone, hidden in the dumpster/room of repairs, surrounded by survivor/elite survivor zombies in the camp, and with only a few pieces of broken equipment and "garbage" left by your now zombified partners...

Possible professions: 
* Rescued refugee (the basic survivor with no redeeming qualities, a newcomer to the community when it ended).
* Creator of wonders (starts with high tailor/fabrication, understood to be the one/one of the crafters of survivor gear in the base, lacks the gear itself since it was left behind when you made your escape to the garbage, but starts with a needle and thread).
* Elite survivor (starts with high combat skills, as well as a severely damaged weapon and survivor gear, bleeding, and damaged body parts because of the fight with the survivor zombies outside).
* Hardened police officer (starts with damaged police riot gear, some wounds, as well as some skills in combat and medical knowledge).
* Blessed by mutagen (Starts with claws, fangs, animal eyes, maybe some fur and a tail, as well as some medium combat skills, background of being an escaped mutant that joined the camp).
* Scrap survivor (starts with damaged scrap armor and other steampunk clothing, maybe a nord (scrap sword), light wounds, as well as some combat and fabrication skills).
* Drone master (starts with a pair of RC cars, a few RC bombs, a few noise making toys for the RC cars, some cameras, an RC controller, infrared goggles, and good computers and electronics skills).
* Modern age knight (starts with damaged medieval armor, a broken long sword and some melee skills, light wounds).
* Bow/Crossbow junkie (starts with a bow/crossbow, very few ammunition, leather gear, and a few bow/crossbow related items, appropriate skills/proficiencies, and light wounds).
* Road survivor (starts with a generic death mobile parked outside the camp, as well as high skills in mechanics/fabrication/driving, as well as tire armor and steampunk clothing, some wounds and a low combat skill).
*Deranged Survivor (Starts with a barbed wire/nail bat, the killer drive trait, some apocalyptic armor, skills in bashing and melee, maybe a molotov, probably some kind of knife as a seconday weapon/tool of torture).

All combat related professions should have some proficiencies in weakpoints, generally basic biology should be enough, but in some cases, more advanced weakpoint proficiencies are reasonable.

### Describe alternatives you have considered.

To forget these scenarios even exist!

### Additional context

My fourth and final issue of ideas I had while at work, this time concerning the future themed scenarios, this is a big change that I would most likely not do in a good time, since I already have another scenarios to make/improve, but I had many ideas of how I would like to do it if I had the time, I already have the mansion and portal dependent scenarios as things to improve, so this ideas will probably take a good time before they take shape, mainly because I would need to add a new location first, the ruins of a big in scale NPC survivor camp.

**Comment by JonathanLochridge** [comment]
This seems like an interesting idea.

To my knowledge, starting with wounds is generally determined as part of the setup for a scenario rather than the profession.

But, having the starts be in isolated, semi-secure locations. And, making up for that by ramping up the starting difficulty due to having more evolved monsters and such. Seems like a good idea. 

The character ideas overall look interesting.

**Comment by Termineitor244** [comment]
> This seems like an interesting idea.
> 
> To my knowledge, starting with wounds is generally determined as part of the setup for a scenario rather than the profession.
> 
> But, having the starts be in isolated, semi-secure locations. And, making up for that by ramping up the starting difficulty due to having more evolved monsters and such. Seems like a good idea. 
> 
> The character ideas overall look interesting.

Hi! Thanks for your comment, as an answer to it I can say:

You could make a specific character start with wounds or other scenario specific things by using an EOC linked to the profession or a trait given by it (the way I give kill missions to the assassin professions).

Most scenarios situated in the future should give you a nice isolated space given the crazy nature of the evolved monster a year after the Cataclysm, being surrounded by a mutant undead giga horde in the middle of winter while in a wooden cabin is not exactly fun unless your character is superman or something...

I'm glad you liked my random ideas! I hope some day I have the time to implement any of these.

**Comment by JonathanLochridge** [comment]
> Hi! Thanks for your comment, as an answer to it I can say:
 ...
> Most scenarios situated in the future should give you a nice isolated space given the crazy nature of the evolved monster a year after the Cataclysm, being surrounded by a mutant undead giga horde in the middle of winter while in a wooden cabin is not exactly fun unless your character is superman or something...
> 
> I'm glad you liked my random ideas! I hope some day I have the time to implement any of these.

I did a little bit of looking around and found 2 separate delayed time scenarios.
Overall, I feel like one of them kind of has a price that isn't that representative. But, I have been trying to look comparatively to see where it should line up.

### Current features and Cost Analysis

Sheltered gives 3 points and gives the option of starting in a normal shelter or an LMOE shelter, but makes it start in winter and with evolution progression. In contrast, the "safe place" start that has a longer list of safe places you can pick. LMOE is one of them and costs 1 point.
Effectively, that makes "Sheltered" act like giving 3.5 points in value. Because you can only choose 1 good safe spot. So if you manually pick that you are getting something you would otherwise spend 1 point to get +4 points. But, if you randomly pick it there is a good chance of just starting in a normal shelter. It also has a secondary restriction of giving you less profession options. 

Lore wise: those mainly makes sense if you start in an LMOE shelter. Otherwise, they don't there.

Next Summer gives you no points, but starts you in summer in the next year, so any non-preserved food is spoiled + evolution. Those negatives might be balanced out by the naturally available food in the wilderness and starting in a random more remote location. It's list has some of the okay locations from the "safe place" option. But none of the good ones. And a couple dud locations that might come up randomly. Like "field" and "middle of nowhere". Middle of nowhere does guarantee spawning fairly far from a city, so is kind of safe. field will probably spawn out of one, but if you get unlucky might not turn out to be very safe.

### Points of action

Sheltered:
-Add more starting locations from the "safe place" scenario
-Add some more professions that fit the theme overall.
-Overall point value seems about right.

Next Summer:
-Tailor down the list of professions rather than using the normal list
-Add some scenario specific professions
-Adjust it to grant more points. Perhaps 1 point if we make the starting location safer and closer to the bounty of the wilderness. 2 if we opt to keep the lower end of locations to start with.
-Adjust the locations to be more consistent.

New Scenario options:

Winter Is Coming:
A scenario that moves things to late fall but before snow comes,
- 1 week or so till winter hits
- Non-safe location that it is plausible to have lived through summer in. 
- +1 or +2 points, less than starting directly in winter.
-A broader profession list 

Later Survival Community:
Have the player start at a particular faction base later in time, but restrict their starting professions and such to a degree.
Kicked-out Refugee:
-Start in refugee center.
-Be "kicked out" of the refugee center due to lack of supplies or something. Opting to go out and try to scavenge on your own.
-Take some existing professions and modify them to fit this lore.
-Cost  0, with the delayed time bringing in zombies making up for the benefit of starting at this nicer location. Since starting at refugee center without a specific lore at normal start time can already be gotten for -1 point.

A more general one could be made that makes your exact starting faction random and is not as directly tied to it. Your idea could maybe start as a location in this list and maybe be developed into it's own mini-faction built around you starting with them and forked out to it's own scenario once developed enough?

More ambitiously, Major significant factions could have unique scenarios made specifically for starting at each faction base and developing a lore for it. But, I figure starting with just  one first and then maybe doing that later would be more sensible.

### Things I could probably start working on now or pretty soon:
-Make All basic adjustments to "Next Summer" and "Sheltered" scenario
-Create basic form of a "Winter is Coming" scenario
-Begin work on maps for a "wiped out camp" type scenario. Depending on the exact details you give for something like that.
-Create a bare-bones "start at faction base" scenario that would need to be integrated for me to consider it good enough quality to actually be worth mainlining.
### With help or a bit of studying I might be able to do some of these:
-Create new professions to flesh out existing scenarios
-Create new professions for your new scenario.
-Make up some dialogue and such that might be needed to hook a scenario in. I would need someone else to find a way to make sure this only activated if they player chose this scenario. I have no idea how that would be done and if it could be done with just EOCs or if it would need some C++ code to add the functionality.

**Comment by Termineitor244** [comment]
> Several ideas input and analysis of the future scenarios.

Pretty good analysis and ideas! Some comments about them:

- I feel like the points of all scenarios starting the player in the future should give a couple of points as a standard given the nature and difficulty of starting in a world already savaged by zombies by several months, the monsters are big and scary, you will almost always start severely under equipped when compared with a normal character that managed to live until then (Even the professions I suggested in this issue are way behind what a player controlled survivor would normally achieve this late in the game, since you will start only with some clothes and items, not a huge pile of loot and some cleared cities/areas in the vicinity).

- Most future themed scenarios should have better distinctions between them apart from the season in which they start, specially since the player can now decide in the world options how much time has already passed since the start of the cataclysm, so if we are going to have scenarios for the 3 different seasons apart from spring, they should incorporate some unique elements, like starting in the wilderness for the summer one, or having the faction based ones be in winter, or the one in fall being the classic one that starts you in a secluded location, like the LMOE shelters, and having to prepare for winter in that remote location being the "theme" of it along with other things.

- The dialogue part that you mention as needing help I assume is for the faction scenario? That could be done easily with a special trait given by the scenario/professions, and upon which it changes some dialogue/missions from the related faction that you previously had some relationship, this would need some effort to maintain as more NPCs are added and new dialogues/missions are introduced, but it is doable (if somewhat tedious writing all the new lines) using only JSON.

- I could probably create any planed profession in my free time with my cellphone, they are all contained in the same file so they are easier to make/change than mapgen.

- It would help me a lot if you could begin work in a basic map outline of the overrun/wiped out camp, with that done I could probably find some time for the spawning of the map, items and monsters spawns as well as the actual scenario/professions for it, I suggest using an already existing big building (Like the fema camp, the fort, a military base etc.) for reality checks (How much can be done in the small time since the cataclysm started to create a base big enough to protect a considerable number of people) and for practical reasons that is way easier to just adjust/modify something that already exist into a makeshift wiped out base of operations in the apocalypse than making a whole new location from 0.

- Starting at a faction base as someone with a previous relationship with them could probably be done for the refugee center if we use your idea of "kicked out" and limit the changes of dialogue for most NPCs to some greeting/introductory lines, something like:
"Hi! Are you new here? I don't remember seeing you."
"I came from the basement actually, but they forced me out and I now have to wander here."
"Oh, that sucks, but welcome aboard, we were never let in there in the first place."
Something like that, but shorter/longer and adapted to the NPCs in question, the merchant could use more lines given its relationship with the people in the basement (and role as the introductory character of the faction) and the monsters in the back bay (as well as the mission related to them) would need to have been "already cleared" by someone else, so a different introductory mission could be used too.

- I think a NPC faction that is centered around the player should be very story heavy or not done at all, so the most it could be done without a big endeavor is an NPC or two with a story of being saved by you and starting in a secure and resource rich location, allowing you to create from day one that faction as you see fit.

Overall pretty good ideas and analysis!

**Comment by anothersimulacrum** [comment]
Closing per https://github.com/CleverRaven/Cataclysm-DDA/issues/58865#issuecomment-1475384889
