### ISSUE TITLE
Ideas for future PRs 3: Modern Bowman and Incognito Police man/woman professions 

### ISSUE THREAD

**Issue by Termineitor244** [CleverRaven/Cataclysm-DDA#63348]
### Is your feature request related to a problem? Please describe.

More professions can always be good, right? We currently lack a profession making use of the multi-function quiver and the takedown recurve bow, so that is one easily done.

A Police man/woman in incognito, for use in the prison scenarios is also a good idea I think, so you can start with nearly nothing (dressing as a normal convict), but with knowledge and skills from a police background, even a little mission to finish your incognito investigation.

### Solution you would like.

**Modern Bowman:** Like the current bow hunter profession, but with a takedown bow and a multi-function quiver, some modern arrows and a mod or two stored in the quiver, a little more costly than the normal bow hunter, but you start with mod bows, which is pretty good since they are kind of rare at the start of most games.

**Incognito Police man/woman:** A "good/lawful" counterpart to the assassin convicts, an officer/special agent sent to infiltrate the circle of a known and powerful criminal, but that was interrupted by the cataclysm, now you need to search the body of your target for clues and try to escape a prison where it no longer matters that you are incognito, since there is nobody left to care if you are an officer or not... Common skills/proficiencies from the police officer professions, a little mission for flavor, and the police trait to be recognized as such if you find a badge.

### Additional context

Third take of my ideas while at work, this time a couple of new professions, another relatively simple change that I would like to do in the near future.

**Comment by PatrikLundell** [comment]
I'd rather call the second one something like "Undercover cop", because infiltration is really an undercover operation, while being incognito just means you're not advertising who you are, while not really pretending to be someone else. The "cop" part would be to get rid of the annoyingly cumbersome political correctness "man/woman" description (which you actually don't need, so you can go with "Undercover Police" instead).
However, if you're trying to emulate reality, you'd actually need to differentiate between the genders, as prisons typically are gender separated (but the game doesn't really assign or keep genders on zombies, so a zombie may have a male sprite one time you encounter it and the other the next time if you've left the area in the mean time).

**Comment by Termineitor244** [comment]
> I'd rather call the second one something like "Undercover cop", because infiltration is really an undercover operation, while being incognito just means you're not advertising who you are, while not really pretending to be someone else. The "cop" part would be to get rid of the annoyingly cumbersome political correctness "man/woman" description (which you actually don't need, so you can go with "Undercover Police" instead).
> However, if you're trying to emulate reality, you'd actually need to differentiate between the genders, as prisons typically are gender separated (but the game doesn't really assign or keep genders on zombies, so a zombie may have a male sprite one time you encounter it and the other the next time if you've left the area in the mean time).

Good point, thanks for the info! I will use "Undercover Police" instead, English is not my first language so I was unsure of how to call it.
