### ISSUE TITLE
use:action { type: heal } does not respect the "SINGLE_USE" flag

### ISSUE THREAD

**Issue by Standing-Storm** [CleverRaven/Cataclysm-DDA#63345]
### Describe the bug

I'm trying to make a summonable bandage for a spell effect and want it to go away after use. Since comestibles cannot be ethereal and I don't want the player to be able to stockpile psychic bandages, I made it a tool with the heal use_action, but doing so means the item lasts the full duration of the spell and allows multiple bandage actions even though it's set with the flag SINGLE_USE

### Steps to reproduce

1) Create a spell to summon a single-use object, like "Summon Rollmat"
2) Cast the spell, use the summoned item, and notice that the rollmat disappears after use.
3) Copy the rollmat data into a new item and point the spell to that item, change the item's use_action to { "type": "heal", "bandages_power": 8, "bleed": 20, "move_cost": 100 }
4) Cast the spell, notice that you can bandage yourself every turn for as long as the spell duration lasts. 

### Expected behavior

A SINGLE_USE item should be single-use, regardless of what use it's put to.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2486 (21H2)
- Game Version: 690e38e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

My original idea was to have the summoned item last a single turn, but that causes the game to crash when it's used, presumably because it disappears and then the avatar tries to use the no-longer-extant item.

**Comment by cake-pie** [comment]
This turned out to be fairly complex.

In most cases "tool-like" use actions return amount/charges consumed from their `use()` as soon as they are (a)ctivated. Consumed amount must be >0 to even reach the point in the code where `SINGLE_USE` is checked for and handled.

The catch here is that `heal_actor::use()` returns 0. because heal use action is not instantaneous. It assigns a first aid activity that takes time to complete, so whatever resources are being used cannot be consumed immediately upon (a)ctivating, but rather only upon completion of the activity -- and there is even a chance that the activity is cancelled or otherwise cannot be completed.

Which is why
> have the summoned item last a single turn,

won't work, because that's not enough time.
Even if you increase the spell duration, there is still a fair chance that the player uses the item toward the end of its duration and in that case the crash that you experienced can still happen, because the item expired before the first aid activity is complete. This might be the biggest hurdle in the way of what you are trying to achieve.

As for the item getting consumed, normally `heal` expects any consumable to be a medication (comestible). The code that will ultimately delete e.g. bandages when expended is at:

https://github.com/CleverRaven/Cataclysm-DDA/blob/ffde5d5c2e9c06347d34c9c011765d097be146b1/src/activity_actor.cpp#L5759-L5761

This would not require `SINGLE_USE`. But if I understand correctly, your use case prohibits comestibles.

Healing items of tool type are possible if they don't use charges nor get consumed, so some kind of unrealistic/magical item like "gloves of laying hands +5" is feasible to implement. We can't use the existing `SINGLE_USE` checking machinery, because the non-instantaneous nature of first aid activity cannot function if the item is deleted before completion.

I don't think the code supports tools that use charges of ammo, for example some kind of antiseptic wound spray, but I think perhaps that could be implemented without too much difficulty. Not sure if that helps your use case much though.

**Comment by cake-pie** [comment]
#63428 should let you make a `SINGLE_USE` healing tool, but you will still have to contend with the time aspect that causes a crash if the summoned item disappears before the first aid bandaging activity is finished.

**Comment by Standing-Storm** [comment]
Thank you so much for working on this!

> you might have to make it so that your magic bandage take zero time to apply, but I suspect you didn't intend for it to be magical in that way.

This actually work out perfectly for my purposes--I can set the bandage time to 0 actions and count the spellcasting as the effective bandaging time. I'll just increase the item duration a bit (maybe to like 400-600 moves) to provide a buffer to avoid crashes.

**Comment by cake-pie** [comment]
Just to be upfront about the risks: I can't guarantee that there's no additional item handling / inventory juggling time, though. Can the item summoning be set up to require empty hands and guarantee that the magic bandage spawns wielded? That would probably help mitigate/minimize handling time costs.

**Comment by Standing-Storm** [comment]
A summoned item always appears in your hands if they're empty, and I could take the NO_HANDS flag off for that particular spell (it's for a psychic powers mod, so most of the powers I wrote have NO_HANDS set). But that's a good reminder that I should do some inventory testing--set a longer duration and stuff it into a nested container and make sure that I can still use it even with 2 rounds remaining.

(I did see if setting bandage time to 0 moves still crashed the game if the psychic bandage had only one turn remaining, and sadly it does)
