### ISSUE TITLE
you are limited to 4096 items per tile

### ISSUE THREAD

**Issue by alp7292** [CleverRaven/Cataclysm-DDA#63409]
### Describe the bug

you are limited to 4096 items per tile

### Steps to reproduce

get 4097 cotton patch drop it on the ground or vehicle cargo
see that 4096 cotton patch is on the ground and one next to it

### Expected behavior

you shouldnt limited by item count or at least the number should increased

### Screenshots

![Ekran Görüntüsü (127)](https://user-images.githubusercontent.com/82234624/216654978-94d00e1c-6542-4fc6-bfeb-2a0a8b4045a4.png)
![Ekran Görüntüsü (124)](https://user-images.githubusercontent.com/82234624/216655007-5c135f31-939e-4d4f-85fe-a1e0cd2bee03.png)

### Versions and configuration

latest

### Additional context

you shouldnt limited by items per tile or at least its number should be increased not sure how coding works but its number is max 12 bit number. increasing it to 14 bit would be enough 
i am having trouble with storing my tailoring and fabrication items as they dont fit into my vehicle cargo even though it has enough space

**Comment by ZhilkinSerg** [comment]
See https://github.com/CleverRaven/Cataclysm-DDA/pull/35411

**Comment by alp7292** [comment]
ok kevin said "I'm fine with a different limit" so i think 16 bit is good if its too high 14 also someone said that some code is optimized so a bit higher number shouldnt be issue or we need to

**Comment by anoobindisguise** [comment]
One thing that amplifies this issue is that while you can "cheat" the system by putting your hundreds of patches in containers, this creates an obscene amount of slowdown, even if you still only have 4096 items in those bags. For example, try spawning 4096 plastic chunks onto a tile and then examining the tile. This takes a few seconds. Then try putting all those chunks into 4 separate body bags and put the body bags all in one tile. It takes 15-20 seconds to examine the tile.
And all this is because we're trying to avoid using charges, due to the issues with charges, but the issues with *not* using charges are also really extreme when you accumulate large amounts of items (which can *easily* happen with for example fabric patches or scrap aluminum)

**Comment by mqrause** [comment]
> For example, try spawning 4096 plastic chunks onto a tile and then examining the tile. This takes a few seconds. Then try putting all those chunks into 4 separate body bags and put the body bags all in one tile. It takes 15-20 seconds to examine the tile.

That's a different issue that should get it's own report if it doesn't have one yet.

**Comment by alp7292** [comment]
> One thing that amplifies this issue is that while you can "cheat" the system by putting your hundreds of patches in containers, this creates an obscene amount of slowdown, even if you still only have 4096 items in those bags. For example, try spawning 4096 plastic chunks onto a tile and then examining the tile. This takes a few seconds. Then try putting all those chunks into 4 separate body bags and put the body bags all in one tile. It takes 15-20 seconds to examine the tile. And all this is because we're trying to avoid using charges, due to the issues with charges, but the issues with _not_ using charges are also really extreme when you accumulate large amounts of items (which can _easily_ happen with for example fabric patches or scrap aluminum)

i dont think we cheat the system as we obey the laws of physics and if items dont fit in a single tile you are forces to put into the next one and that loading time will be same its a issue of code optimization

**Comment by anoobindisguise** [comment]
> That's a different issue that should get it's own report if it doesn't have one yet.

It's highly related though as the 4096 limit forces you to do this. I've tried storing stuff in warehouse shelves and for many resources you just run out of the 4096 really fast especially with tailoring resources, well before you hit the limit for volume. With charges you can have literal hundreds of thousands of an item with no lag, and there's no need to subdivide the items into containers, but non-charged items force this to happen and cause extreme lag because of their limitations.

> i dont think we cheat the system as we obey the laws of physics and if items dont fit in a single tile you are forces to put into the next one and that loading time will be same its a issue of code optimization

It's not cheating the system logically, as while you could fit over 583,000 cotton patches on a warehouse shelf you can only make use of less than 1% of that space due to the 4096 limit. (if cotton patches were measured with charges, there would be no issue). but it's cheating the "game engine" limitation if that makes sense. Since an item with thousands of sub-items stored inside it is counted as one single item for the 4096 limit.

**Comment by mqrause** [comment]
> It's highly related though

Frankly it is not. What you described is a performance issue, presumably related to containers and inventory selector menus.

**Comment by Qrox** [comment]
We could rename `tile` to `harddrive` and `item` to `file` so that each file occupies at least 1000/4096 liter harddrive space.

**Comment by Zireael07** [comment]
@mqrause That performance issue has been reported several times and apart from saying 'we don't want more charges/more hacks' nothing is happening on that end (#41934, #48937 and probably others)

**Comment by mqrause** [comment]
Those are also different things to what anoobindisguise described.

**Comment by Cenness** [comment]
> Those are also different things to what anoobindisguise described.

It seems you glossed over all mentioned issues in those two. I'll point out just two of them - https://github.com/CleverRaven/Cataclysm-DDA/issues/35292 with quote:
>kevingranade commented on Dec 13, 2020
>Other than Aivean's proposal, this needs pervasive nested item caching, which isn't a reasonable thing to try and shim in before 0,F

With 0.G nearing its release, maybe that caching will finally have a chance at existing?

and second - https://github.com/CleverRaven/Cataclysm-DDA/issues/55654 - closed as stale.

**Comment by mqrause** [comment]
There's a lot of mixing up issues happening here that is not helpful at all. Item limits on tiles, performance of menus, charges yes/no and moving large amounts of items might have some overlap from a player perspective, but are completely different things codewise. Focusing on one of those might make others less noticeable, but will not fix them.

**Comment by Kamayana** [comment]
Can anyone give a reason the limit has to be set at 4096? There should be some kind of sanity limit, yes, but 4096 is very easy to run up against once you do something like make a crafting base with warehouse shelves, and the 4096 limit is very obviously arbitrary and immersion-breaking when you hit it while the shelves say they have plenty of volume left. Kevin's comments on #35411 were from 2019 and the game's changed a lot since then - a 4096 limit does not seem to me to be nearly as unreachable anymore.

Performance definitely starts to slow down when you get a ton of items in one place, but personally I can understand and accept a little slowdown when I'm doing something like keeping huge amounts of junk in one shelf (it's interesting that the AIM is lightning fast even with massive piles; that thing's optimized particularly well). Because of that I don't think slowdown is enough of a reason to not increase the limit - more of a task to work on in the future like has been discussed here already.

**Comment by Cenness** [comment]
>some overlap from a player perspective, but are completely different things codewise

Are you asking for a player that is intimately aware of the game's code? /s (Yeah, I know that there are some)
Users can only perceive symptoms and, if support is lucky, provide sufficient info for a repro.

**Comment by alp7292** [comment]
slowdown due to items is a different issue and it is still a issue event with limit because you are forced to drop items on next tile so slowdown will be the same its a issue with optimization. scope of this issue is a arbitrary item limit causing you to unable to store items you should. i think increasing the limit to 16,383  would solve this current issue.

**Comment by andrei8l** [comment]
> i think increasing the limit to 16,383 would solve this current issue.

So open a PR for it and make your arguments there.

**Comment by alp7292** [comment]
> > i think increasing the limit to 16,383 would solve this current issue.
> 
> So open a PR for it and make your arguments there.

if only i know coding

**Comment by andrei8l** [comment]
> 
> i dont know coding

https://github.com/CleverRaven/Cataclysm-DDA/blob/1c6c4501738a0b31b99bc91bee8a9a6d4fcca9e5/src/game_constants.h#L29

**Comment by alp7292** [comment]
that was simple lol never done pr  before will try

**Comment by kevingranade** [comment]
Do pervasive testing in every area of the game impacted by the limits and state your results in detail.
Until that happens, the answer is no.

**Comment by AideeAmei** [comment]
This has become an issue for me, since welding rods are now separate items. It was generous the previously saved items didn't have their count updated until moved so I could transport them, but putting any more into my vehicle was hell. Now I'm wondering how I can even store them. Small cardboard box can't satisfy the length. Do I need to find or craft tens of backpacks just to store rods?

**Comment by mqrause** [comment]
Welding rods come in welding rod tubes nowadays, so use those.

**Comment by AideeAmei** [comment]
Eventually it stopped being an issue. I can now put more rods into a bag. Tubes are not available in my existing world, I'd have to travel far to have some spawned.
