### ISSUE TITLE
"Clear Back Bay" mission reward in the refugee center is too OP

### ISSUE THREAD

**Issue by LCkanon** [CleverRaven/Cataclysm-DDA#63489]
### Is your feature request related to a problem? Please describe.

The current reward, if you choose the option to take items as a payment, gives you 500$ credit and 25 Merch. A total amount of 625$ This is too much, concidering that you have to do nothing to complete the mission, just bang on the doors of the back bay, the zombies come out and get killed by guards. 500$ is clearly too much money for this mission.

### Solution you would like.

Either make the mission harder, so that you actually have to kill the zombies yourself, or decrease the reward.

### Additional context

![image](https://user-images.githubusercontent.com/124779487/217503762-7762bbc8-9982-497b-a529-366ea4149c67.png)
![image](https://user-images.githubusercontent.com/124779487/217503809-289e87c8-5678-4f7c-8096-694e309155a0.png)

With the 500$  I was able to buy all of the tools and almost all of the materials the guy had to offer, and I still had 174$ left (excluding the Merch).

**Comment by Perset** [comment]
From a balance in video game rewards perspective, it might be too much, but this is also a permadeath game. 

Is six hundred bucks really that big of a deal for the minor inconvenience of risking your life against 10-20 hostile, no-quarter killing machines for the sake of a few relative strangers? I think most missions in this game reward far too little, realistically.

**Comment by Sepentine** [comment]
The mission itself is kinda messed up to begin with. The fact that its in the refugee center means that npcs hear you fighting and get up and move, also means that you can just let the guards take care of it while doing basically nothing. I think it would be better if the zombies were outside the refugee center somewhere inside the fence so that you cant just have the guards shoot them while doing nothing but open a door
