### ISSUE TITLE
Buff Mi-Go Captive Starting option

### ISSUE THREAD

**Issue by Snaaty** [CleverRaven/Cataclysm-DDA#63504]
### Is your feature request related to a problem? Please describe.

The scenario "Challenge - Mi-Go Encampment" offers two starting options of which the "Rescuer" is better in pretty much every way than the "Captive". The two are only 5 points apart, with the captive starting with absolutely nothing in regards to skills or items while the "Rescuer" starts with several important skills on a competent level as well as adequate gear for the winter. 

I understand it is meant as a Challenge, but even just surviving the initial start in the tower is extremely difficult for a captive, only to then struggle against the cold of winter as well as evolved and thus way more dangerous zombies. In my experience the start relies on randomly getting spawned in a room that is close to the exit, as the mi-gos can't really be run from efficiently (as well as the cold and gases slowing you down) while also being impossible to fight for the captive and risky for the rescuer. 

### Solution you would like.

Therefore I suggest to either 
a) give the captive tools to possibly survive the start (skills, items, traits) that are thematically appropriate. Although I have some doubts, that a "Captive" to the mi-gos could start with substantially improved starting gear or traits without ruining the idea of the buck-nacked captive. 
b) increase the points gained for choosing that background. I suggest bumping it up from +2 to +5 (not set on numbers, feel free to discuss)? I feel like creating at least some incentive to chosing this background over its counterpart is needed. 

### Describe alternatives you have considered.

An alternative would be to change the starting location around a bit, to the extent where escaping the tower is a bit easier if you know what you're doing. I don't have any great ideas here, but it is what came to my mind as alternative. I reckon even doing both ( b) from above and this) would still be a good choice.

**Comment by Raikiri** [comment]
Escaping a mi-go camp is perfectly possible, it's just utterly random. Sometimes you have a clear path to a nearby forest with no guards to see you, sometimes there's a guard right next to you as you spawn.

**Comment by Snaaty** [comment]
I agree it is partially the randomness that makes the start difficult. But in this randomness it is quite binary, as there are only two options (1. getting lucky and managing to run away and 2. death) unlike let's say the Really Bad Day start, where I can get lucky depending on the surroundings needing/not needing antibiotics etc. I don't think having early inevitable RNG decide if you get to play the game is engaging though...also I'm not even sure it qualifies as "difficulty", as running away when you get lucky with the rooms/guards is actually quite trivial. Really Bad Day has a strong random component as well but is more varied (thus more fun), as you're dealing with multiple challenges at once. (infection, the fire, no gear,...)

Tbh I'd argue the game is not "business as usual" once you escape as the "captive" background. As you're now in the freezing cold with no clothes/items at all, no skills, proficiencies etc. (that you didn't pay your extra points for) and what I think is typically highly underestimated is that evolved zombies can be significantly more dangerous than the standard ones. Admittedly regular Zs can be a bit of a pushover, but try runnin into town to only get mopped up by the first zombie predator with night-vision.
 In my current playthrough (as "rescuer") I feel I have to be way more careful with the random things that go bump in the night. In a spring playthrough I'd usually just check for the zombie and then be able to dispatch it, but with this start often times I can't take the super-regen zombies like Dissoluted Devourers, Pupating things or Hulks and others. 
Additionally all the perishable food is gone, which adds a slight layer of difficulty as well. Tbf I play only with the "No Hope" mod, so maybe this is not as relevant for a normal playthrough. 
Anyway sorry for the long rant, I am interested in what people have to say about this start! Does anyone except me even play it? :D

**Comment by Solusphere** [comment]
Mi-Go Captive is essentially Start Scum: The Scenario. While this could stand to be improved, I don't think buffing the captive profession is the way to go about it, and frankly, you'd have to buff it a LOT for it to make a notable difference in your odds of escaping the tower.

In my opinion a better option would be to rework the starting mi-go tower such that no mi-go ever spawn in the same chamber as you, and adding some means of distracting or trapping the guards without fighting them. Pheromone seems like an odd weakness for them to have, given that Mi-go are a sentient, technologically advanced alien race and would likely see through such a simple ruse. 

What I think might be cool is giving most of the chambers in the tower multiple doors connecting to adjacent chambers, and allowing the doors to be sealed by smashing a very fragile organ next to them. This would, hopefully, let you seal off a chamber if you and a guard spot each other so you can find another route, or potentially even kite a guard into a different room and trap it there (though given the speed penalties you'll likely be experiencing that seems difficult at best). This would hopefully lead to a more sneaky, systematic approach to escaping, rather than the current strategy of making a mad dash for the exit and hoping you get lucky with guard spawns.

**Comment by Raikiri** [comment]
@Solusphere I agree that buffing a profession to make a starter character viable against mi-go's is just not realistic. Even midgame characters are not safe while assaulting mi-go towers, and it's just not reasonable for a captive to have any chance of fighting them. So giving the player more tools to distract/work around his captors is a much more realistic way to escape (if that's even remotely possible). Maybe adding hulks, portals or other dangerous enemies to distract the guards while the player escapes is another thematic and exploitable opportunity.

That being said, sealing doors can lead to annoying soft-locks that a starting character can't escape. I think a realistic and relatively engaging way would be to generate a path through the tower that has no mi-go's in it, and let the player navigate by carefully listening to sounds in every adjacent room. The escape route should also be mi-go free, and I'm not sure how to justify it.
