### ISSUE TITLE
[MA]Untranslated city name

### ISSUE THREAD

**Issue by waveyl** [CleverRaven/Cataclysm-DDA#63514]
### Describe the bug

![image](https://user-images.githubusercontent.com/22638873/217989930-4ea8b083-29d9-4ecb-ab99-7f57b0beace8.png)

### Attach save file

N/A

### Steps to reproduce

View map.

### Expected behavior

Localized city name.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2546 (22H2)
- Game Version: ffde5d5 [64-bit]
- Graphics Version: Tiles
- Game Language: 系统语言 []
- Mods loaded: [
    浩劫余生 [dda],
    NPC无基本需求 [no_npc_food],
    NPC不受空间风暴影响 [personal_portal_storms],
    禁止真菌增殖 [no_fungal_growth],
    生化职业 [package_bionic_professions],
    马萨诸塞州 [MA]
]

**Comment by PatrikLundell** [comment]
You frequently can't translate location names, as they don't actually mean anything (at least not any longer), or, when they, do, translate into something that's just plain weird in the target language (how would you translate the name in the image, for instance?).

One work around would be to have every location name require translators to provide a local "version" of the name, which would probably generate a lot of "fun" for translators, in particular if names are generated rather than pulled from a file (I don't know what the case is).
However, that would then mean that all the names change when you change the language, which would mess things up rather badly if you try to use a save for bug identification purposes, as the person doing it would have to use whatever (potentially unknown) language and script the player used.

**Comment by andrei8l** [comment]
The issue here is that the name isn't transliterated either so it's potentially unreadable.

Our translation framework supports mod translations so this is just a matter of setting up the .mo/.po files in the MA mod.
