### ISSUE TITLE
Error while trying to craft clay canning pot

### ISSUE THREAD

**Issue by Rajkvn** [CleverRaven/Cataclysm-DDA#63537]
### Describe the bug

After trying to craft clay canning pot near the fire its not possible to wield or activate "In progress" item

### Attach save file

[Innawood-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/10713761/Innawood-trimmed.tar.gz)

### Steps to reproduce

1. Light up a fire near the character
2. Craft clay canning pot with ingridients on the ground

### Expected behavior

The expected outcome will be the successfull crafting (i guess?? lol)

### Screenshots

![clay_canning_pot](https://user-images.githubusercontent.com/108903506/218261150-a1393029-b739-4336-ae72-64c5366c461c.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2486 (22H2)
- Game Version: 7216560 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Innawood [innawood],
    Megafauna [megafauna],
    Mining Mod [Mining_Mod]
]

### Additional context

 DEBUG    : Failed to obtain target item

 FUNCTION : void avatar_action::use_item(avatar&, item_location&)
 FILE     : src/avatar_action.cpp

 LINE     : 1171
 VERSION  : 7216560

**Comment by Rajkvn** [comment]
FIX:
Unequipping waterkin or straw basket seems to fix the issue

**Comment by PatrikLundell** [comment]
It's the straw basket that's causing the problem. It's carried in a hand, which means you're only able to wield things that can be wielded by one hand. That's particularly problematic in Innawood because that's the only container you've got, starting out, and it takes a fair while to be able to craft another one, but it's not an Innawood problem as such.
The waterskin, in contrast, isn't blocking any hand, and so doesn't affect the wielding of large items.

The game doesn't do a good job of indicating the cause of the failure to wield things due to an occupied hand, though.
