### ISSUE TITLE
Disallow un-repairable or un-reinforcable items to show up in the tailor and sewing kit's repair menu

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#63585]
### Is your feature request related to a problem? Please describe.

I need to scroll through a list of unrepairable or un-reinforcable items that are already at full durability when I intend to repair or reinforce items. This would be a QoL improvement to the sewing/repairing/reinforcing menu.

### Solution you would like.

All items that cannot be repaired or reinforced should be filtered out from the repair list when using the tailor or sewing kits

### Describe alternatives you have considered.

I could sort all the items that appear in the repair and reinforcement menu into another pile. This way will be a waste of time, but save me time when scrolling the repair menu.
I could just continue to press 10 keys to get to my item (pgdn->pgdn->pgdn->pgdn->dn->dn->dn->dn->enter->repair until reinforced).

**Comment by PatrikLundell** [comment]
I would rather suggest placing the items that can currently be operated on at the top, rather than hiding everything that can't currently be modified completely. The reason for this is the frustration of trying to find out which illogical item you need to use to repair something. Usually you want to do that when your precious item is damaged, but you may want to use it in advance as well, to figure out whether you actually want to use an item you won't be able to repair easily, or whether to use something you can actually repair.
