### ISSUE TITLE
Allow backing up photos, music and recipes to SD cards

### ISSUE THREAD

**Issue by Solusphere** [CleverRaven/Cataclysm-DDA#63652]
### Is your feature request related to a problem? Please describe.

Currently, the game has a nifty feature where you can backup the contents of a smartphone, tablet, laptop or pair of AR glasses so an external SD-Memory card, which is very handy in the event that the device is lost or damaged. Unfortunately it currently appears to be limited only to scanned books. All non-book data obtained from SD-Memory cards, including recipes, photos and music, is not presently transferable between devices.

### Solution you would like.

Allow the Manage External Storage option of a smart device to backup other data stored on the device, in addition to books.

### Describe alternatives you have considered.

None

**Comment by Raikiri** [comment]
I had to literally ditch a character the other day that was vlogging his whole journey from the beginning. He was wearing a power armor and got attacked by an incandescent husk: obviously he could not be damaged by it, but the smartphone got fried from an EMP pulse. Unfortunately the next character had to be ditched as well because he got slammed into a water puddle and the smartphone got soggy and broke as well. I learned my lesson and now I'm putting all electronics into condoms, but there's no way to protect them from EMP's.

So yeah, would really appreciate if there was a way to back stuff up.
