### ISSUE TITLE
Easier Bulk Charcoal Kilns/Smoking Racks

### ISSUE THREAD

**Issue by Grubleafeater** [CleverRaven/Cataclysm-DDA#63780]
### Is your feature request related to a problem? Please describe.

Currently, we can only smoke 20 liters of material at once, and only make ~3.5k charcoal at once, and each time requires a separate Examine to trigger. Lighting a array of kilns and a array of smoking racks is a time consuming endeavor, though kilns can be automatically loaded and unloaded with sort zones.

### Solution you would like.

How about making it somehow so that adjacent kilns and adjacent smoking racks can be interacted with as a group?

### Describe alternatives you have considered.

Bigger kilns and smoking racks would also help matters. A smoking rack that can handle 100 or even 1000 liters at once would be nice(though probably rejected). And a kiln that can fit 20 logs would also be much appreciated!

**Comment by anoobindisguise** [comment]
OK, so time to reference #62180 again.
The "rule" is 1 kg of charcoal to smoke 1 kg of food, although I've seen sources saying you can get away with less than that to as little as 0.5 kg charcoal per kg of food at cost of taste. In my PR it's about .75 kg per. One unit of charcoal weighs 1040 mg and is 5 ml. So to smoke 1 kg of food (rouuuughly one liter although the charcoal kiln furniture does not let us define this by weight, only volume) you need 750 units of charcoal, or a gallon's worth of charcoal - 75 liters of charcoal for the whole 20 liters of food, which is 15000 units or about 31.20 kg. 

Charcoal production has a theoretical max efficiency of 1:1 pre-burnt wood to charcoal. There is a massive weight loss here because wood is much more dense than charcoal. The efficiency scales with your Fabrication skill (better kiln design) but no matter what you do the rock kiln will always be much less efficient than the metal kiln due to inferior materials. However with 10 fabrication and a metal kiln you can reach industrial levels of efficiency which is 1:1. I raised the max kiln volume to 250 liters, which is 60 planks. Finishing that burn will give you enough charcoal (~50,000 units of charcoal) to smoke just over 60 liters of food, 3 cycles' worth. Oh, and it takes longer, roughly 24 hours which is more realistic than the current fast burn times.

So since you need a fuckton of charcoal to do smoking, I opted not to adjust the 20 liter limit, although it's something that could possibly happen.

**Comment by fractal-coyote** [comment]
What about alternative structures? There is a historic thing used at least in a few places in europe, called a "charcoal pit" aka "clamp". It's basically a giant mound about 10-12 meters in diamater, covered in dirt and left to burn for a long time (about two weeks according to literature on the subject, which is probably way too slow for most players?) after being covered in a layer of dirt.

Something along these lines - a constructable, "disposable" structure that would basically just require someone to scrape the dirt off the top and collect the charcoal left behind - might be a neat alternative, and although slower possibly by a large factor, it would have the advantage of not really requiring a bunch of rocks to build a kiln, and it could be a less labor-intensive version of charcoal production since it wouldn't need to be refilled multiple times a day, at the cost of it potentially catching fire from external flame or maybe enemies/players smashing it accidentally which could cause it to burn down without anything but ash left behind.

Just a thought!

https://hvfarmscape.org/charcoal

**Comment by Grubleafeater** [comment]
I mean, some way to automate smoking food and making charcoal using a zone would also work, come to think of it. I just want to remove the IRL tedium--in game tedium is fine.
