### ISSUE TITLE
Sweet water should be junk food material

### ISSUE THREAD

**Issue by curtislim0110** [CleverRaven/Cataclysm-DDA#63794]
### Describe the bug

Craftable sweet water should be junk food material, otherwise you can eat sugar (and anything craftable as sugar like maple syrup) with no consequences.  The current material for sweet water is currently water.  Dark cola has a similar amount of calories, but it is categorized as junk food.

This mostly makes a difference with the junk food intolerance starting mutation.  Seems to not make sense that a person can be intolerant of sugar, yet mix the sugar with plain water and it's okay to drink.  

### Attach save file

N/A

### Steps to reproduce

N/A

### Expected behavior

N/A

### Versions and configuration

N/A

**Comment by anoobindisguise** [comment]
The issue is that sweet water can also be made of honey, so converting it solely to junk food wouldn't work necessarily. What is "junk food" should also probably be redefined because it is currently entirely arbitrary what is and isn't "junk" (see for example milkshake vs deluxe milkshake, popcorn vs salted popcorn, homemade hot dog vs raw sausage)

**Comment by JonathanLochridge** [comment]
Yeah, well honey is also a form of sugar. Although, it can be good for you since I heard it is supposed to be like anti-microbial and such.

One approach you could take would be to separate out salt and sugar maybe?

Dislikes salt or something might make sense?

If you wanted to have a hardcore option then potential someone could try adding some form of diabetes. That seems difficult to balance game-play wise though. Since it is a bit more complex than can't eat X without morale penalty.

**Comment by fairyarmadillo** [comment]
Processed honey like you'd find most anywhere is literally just sugar. Everything else has almost entirely been cooked out of it.

Raw honey, which is available at specialty shops, farmer's markets, and directly from bees, has some purported health benefits but I don't think most of these are evidence-based.

I think junk food should be eliminated from the game as a concept and replaced with more dietary stuff along the lines of the vitamin system, but that's a major overhaul and would affect several mutation lines. Until then, anything that is purely sugar (or honey or maple syrup) should be junk food.
