### ISSUE TITLE
Finger-Mounted Laser CBM can keep firing with no power

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#63846]
### Describe the bug

The Finger-Mounted Laser CBM consume 30kj per shot. However, if you run out while firing, you can just keep shooting despite not having enough 

### Attach save file

Trivially reproducible

### Steps to reproduce

1. Install Finger-Mounted Laser and necessary Power Storage/Generation CBMs
2. Generate at least 30kj of Bionic power
3. Spawn a bunch of mobs to shoot at
4. Active the finger laser and just start shooting

### Expected behavior

Laser is not able to fire when you don't have enough power for a shot.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2604 (22H2)
- Game Version: f1bc060 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Sky Island [skyisland]
]

**Comment by Hirmuolio** [comment]
Power consumption for bionic weapons seems pretty messed up.

The finger laser has 30 kJ activation cost. 
When you activate the bionic 30 kJ of bionic energy is consumed.
Then 30 kJ of bionic energy is given back to the player because this bionic is not supposed to consume energy.
The laser finger item has no power consumption. So firing it consumes no power and it can be fired without power.
After firing the weapon a special case in `aim_activity_actor::finish` consumes bionic activation amount of energy. But this is completely separate from normal ammo code so it will not prevent empty gun from firing. 

To properly fix:
* Make the bionic actually consume no power on activation.
* Make it possible for weapons to directly consume bionic power. Well they can consume bionic power in c++ but it is not possible to say that in json. Not trivial to fix.
* Remove the old code.

Or a quick hotfix:
* Move the bionic weapon ammo check from `aim_activity_actor::finish` to `Character::fire_gun` so it is behave as if it was consuming normal ammo.

**Comment by Terrorforge** [comment]
I think the activation cost is currently the only place where the power cost is communicated to the player, so ideally squeeze that in somewhere else as well.
