### ISSUE TITLE
Autopickup does not pickup cold/hot items

### ISSUE THREAD

**Issue by AJimmyU** [CleverRaven/Cataclysm-DDA#63841]
### Describe the bug

I have set bandage to autopickup filter, bandage (cold) does not get picked up. Cold/hot item status should be excluded from item name filters.

### Attach save file

N/A

### Steps to reproduce

1. put "bandage" into autopickup filter
2. walk by regular bandage item, see it picked up
3. walk by the another bandage item when weather is cold, see it ignored by autopickup

### Expected behavior

Autopickup should ignore temperature of consumables.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19041.329 (2004)
- Game Version: c8bb90f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Basher6079** [comment]
I think the issue here is with the name of the item changing with temperature. Putting 'bandage' into the autopickup targets items with the exact name 'bandage', but with hot/cold items the names would be 'bandage (hot)' and 'bandage (cold)', respectively. So, you would need to put 'bandage*' into the filter.

As for solutions that _aren't_ workarounds, I think the temperature system would need to be changed significantly, so that hot&cold were modifiers displayed similarly to amount, rather than name changers. Unfortunately, that's a lot of work for an issue that has a simple workaround, so it's unlikely to change any time soon.
