### ISSUE TITLE
0.G Disappearing arrows

### ISSUE THREAD

**Issue by JuGGerNaunT** [CleverRaven/Cataclysm-DDA#63933]
### Describe the bug

Arrows disappear when moving them from hands to hiking backpack.

### Attach save file

N/A

### Steps to reproduce

1. Wield bunch of arrows
2. Unwield them
3. On the popup choose "Store in hiking backpack"
4. Only 1 arrow is actually transferred to the backpack, all other that were in your hands disappear

### Expected behavior

All arrows must be moved to backpack

### Versions and configuration

Last stable 0.G

**Comment by RenechCDDA** [comment]
Unable to reproduce on 0.G /  d6ec466 

Please provide additional details or a reproduction save.

**Comment by JuGGerNaunT** [comment]
Sorry, I can't share my save data. But I recorded a video. Game version is 0.G / https://github.com/CleverRaven/Cataclysm-DDA/commit/d6ec466140839dd70c1a43671eb4a08b007695c2 . Tell me if you need any additional details.
https://user-images.githubusercontent.com/1506510/223196245-aeba0a09-028f-4d71-9bce-b2d2d109b8a4.mov

**Comment by RenechCDDA** [comment]
Still unable to reproduce.

https://user-images.githubusercontent.com/84619419/223215649-f56a3bd3-458a-455b-b3f8-8e9d0aa56c81.mp4

Are you using any mods? Again, a reproduction save *or specific steps* would be incredibly helpful. The reporting form asks for a reproduction save for exactly this reason.

**Comment by JuGGerNaunT** [comment]
- OS: Android
    - OS Version: Manufacturer: samsung; Model: SM-G9550; Release: 8.0.0; Incremental: G9550ZHS3CSA1; 
- Game Version: 0.G [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by JuGGerNaunT** [comment]
[Lucasville-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/10902741/Lucasville-trimmed.tar.gz)

**Comment by JuGGerNaunT** [comment]
No specific steps. I just generate a new world with default settings, then generate custom character with default settings (leave everything as it appear at the start). Then add wooden arrows and hiking backpack via cheats. Then you can see on the video. I dont use any mods, only that comes with the game and enabed by default

**Comment by RenechCDDA** [comment]
The provided save has only 1 arrow remaining, so I assume this is post-bug? I spawned 9 more arrows (for a total of 10), wielded them, then unwielded them and selected store in hiking backpack. I still had 10 arrows.

I am not sure what to say except this might be a platform specific bug? Although that is very unlikely. I will try to reproduce it on android later tonight.

**Comment by JuGGerNaunT** [comment]
Yes, it is post bug save. Originally, I had this issue on OSX. But I reproduced it on Android to share my save file.

**Comment by RenechCDDA** [comment]
/confirmed on **android**

Still unable to reproduce on windows 10/64-bit. Android game report:

- OS: Android
    - OS Version: Manufacturer: samsung; Model: SM-G960U1; Release: 10; Incremental: G960U1UES9FVD1; 
- Game Version: d6ec466 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by mqrause** [comment]
I can't test and confirm this for a lack of Android and OSX, but I suspect the issue lies in this:

https://github.com/CleverRaven/Cataclysm-DDA/blob/ca4e6995d15b8cab7fcba4172a3d11e5d24ba44e/src/character.cpp#L11449

`i_rem` removes the item before the charges of the item are accessed. `item::fill_with` also doesn't guarantee all the charges you pass to it are filled into the container, so there are possibly more situations where charges could be lost, although that might already be ruled out by other conditions. Still not exactly a safe use of `item::fill_with`.

**Comment by XygenSS** [comment]
/confirmed on Experimental Android

- OS: Android
    - OS Version: Manufacturer: Xiaomi; Model: 23046RP50C; Release: 14; Incremental: V816.0.4.0.UMYCNXM; 
- Game Version: 9a2fbc8 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by PatrikLundell** [comment]
I've suffered from something that might be the same a couple of times in the past (half a year ago?). However, I've been too engrossed in the current activities to report it, and my compressed saves are too large to be accepted anyway.

I've picked up arrows from the ground, and the result has been that all the arrows "disappeared". In my case they were dropped on the ground for an unknown reason and could be picked up again (provided I noticed they were dropped).
It's happened at least in two episodes, where picking up an arrow consistently resulted in the whole set silently being dropped on the ground. Since the increased stack could be picked up without problems in all cases, it's probably not a case of an actual lack of space. However, I wouldn't be shocked if it was something stupid like there not being room for the current stack of X plus a new stack of X+1, but I don't have any evidence either.
