### ISSUE TITLE
Unhardcode smoking racks

### ISSUE THREAD

**Issue by Grubleafeater** [CleverRaven/Cataclysm-DDA#63942]
### Is your feature request related to a problem? Please describe.

Bigger smoking racks(or smaller ones) should be possible. I went to try to mod one, only to find that smoking racks are currently hardcoded.

### Solution you would like.

Pull smoking racks to JSON so they can be modded and have smaller/larger ones added to mainline.

**Comment by strategineer** [comment]
The volume of food you can smoke in a smoker is hardcoded in [iexamine.cpp](https://github.com/CleverRaven/Cataclysm-DDA/blob/77852f82eb977b596661608387734d7879c5dd2a/src/iexamine.cpp#L5836). Mills (in the same file) are hardcoded in a similar way.

Would an appropriate fix for this be to add a new json field to furniture, something like `fillable_volume`, and use that field to define how much food you can smoke or how much stuff you can mill at the same time?

**Comment by anothersimulacrum** [comment]
Currently mills and smoking racks use a lot of duplicate code with the hardcoded things changed around. Ideally all that would be extracted to a generic iexamine actor. This is non-trivial.
For this specific request, that would be a solution, and would be relatively trivial. I would consider just using the base furniture volume if possible instead of adding another field, though.

**Comment by kevingranade** [comment]
This is fine to add, we don't need an issue for it though.
