### ISSUE TITLE
Adding a favorited item to auto pickup includes the "*" in the added rule

### ISSUE THREAD

**Issue by nornagon** [CleverRaven/Cataclysm-DDA#64038]
### Describe the bug

When adding an item to autopickup rules via the "Auto pickup" menu item in the inventory, if the item is favorited, the added autopickup rule will be e.g. "* cash card" instead of "cash card"

### Attach save file

N/A

### Steps to reproduce

1. Favorite an item in your inventory with <kbd>*</kbd>
2. Open the item menu with <kbd>Return</kbd>
3. Select Auto pickup with <kbd>+</kbd>
4. Open the auto pickup manager, switch to the Character page, note that the added rule includes the "*".

### Expected behavior

The added rule should match the item selected, the "*" prevents it from doing so.

### Versions and configuration

0.G

**Comment by aahue1889** [comment]
Checking

**Comment by aahue1889** [comment]
I can confirm this issue in 0.G as well 
- here are the specific steps as reported above
----

First, what needs to be done is enabling the Auto-pickup-manager; otherwise you will not be able to access this page

![image](https://user-images.githubusercontent.com/8581536/223873588-18022d16-4ab1-4341-a5ed-4077f66cb454.png)


Favorite an item in your inventory with *

![image](https://user-images.githubusercontent.com/8581536/223873286-1170c6cf-cb15-4429-a693-47785a9606ad.png)

Open the item menu with Return

![image](https://user-images.githubusercontent.com/8581536/223873376-78fad7af-ba95-4464-b2d8-e253831791f5.png)


Select Auto pickup with +


Open the auto pickup manager, switch to the Character page, note that the added rule includes the "*".

![image](https://user-images.githubusercontent.com/8581536/223873750-0957eca8-1602-482e-af73-d1eca0874de1.png)

And I'll also note that the menu also reports the '*' character as well 
![image](https://user-images.githubusercontent.com/8581536/223873862-dc557ecf-0738-436d-a672-e3b17a11ba89.png)

----

I'll start looking at this tomorrow and see if I can produce a fix for this experience.

**Comment by aahue1889** [comment]
Update:

I can see where the issue is happening in code
- the tname funtion appends "* " upon calling it

![image](https://user-images.githubusercontent.com/8581536/224215767-22e83626-6bfc-4399-8df3-44f339001b95.png)


--

Inside we can see this call 
 
![image](https://user-images.githubusercontent.com/8581536/224216385-de35a450-5ff3-4e33-916c-69654410751b.png)
 
and if we look into ASTERISK_POSITION for get_option we see logic for how the * is going to be fed

```

add( "ASTERISK_POSITION", "interface", to_translation( "Favorited item's mark position" ),
         to_translation( "Where to place mark of the favorited item (asterisk): before item's name (prefix) or after item's name (suffix)." ),
    { { "prefix", to_translation( "Prefix" ) }, { "suffix", to_translation( "Suffix" ) } },
    "right"
       );
```


I'm looking for the right spot to make this change that doesn't involve messing with the way tname() works
- I'm likely about the change the logic before tname is called.
