### ISSUE TITLE
Game mechanics question - open door and get hit before I can react, normal?

### ISSUE THREAD

**Issue by matt32106** [CleverRaven/Cataclysm-DDA#64063]
### Is your feature request related to a problem? Please describe.

Sometimes, I open a door with O and a Zombie walks into the now empty door space and hit me before I can react. Is it normal? I mean, except for very fast monsters, they should not be able to both move and hit me in the same round or am I confused?! 

### Solution you would like.

Just want to understand how it works with respect to speed/move... 

### Additional context
Here is an example: https://i.imgur.com/O1Yw4oC.png
I have speed 99, I just opened the door and the slime had time to try to hit me.

**Comment by Reddeh** [comment]
I always assumed its intentional, since interacting would cost "Action Points". Though I agree it makes less sense for an enemy to be able to enter an open doorway that would only be "free" after you spent your action points to open the door. Essentially allowing them to buffer action point usage.

**Comment by AcidAntOnAMinefield** [comment]
This definitely needs to change. Opening a door shouldn't cost an entire turn worth of action points - unless you want to open it as quietly as possible (a mechanic that doesn't exist), ie the slower/quietly you open it, the longer it takes. 

And creatures shouldn't immediately see you either - something that would potentially be fixed in the event a weird "vision radius" thing happened (where creatures only can see towards where they're looking at on the axis, if that makes sense).

Although it still wouldn't address the issue at hand. No creature would immediately jump onto an open door the moment something opens it, there is always the element of surprise for whatever creature may be in a room, *unless it can see through walls*. 
This happens a lot with robots too, which is really frustrating.

**Comment by matt32106** [comment]
why is it not marked as bug + confirmed ?
