### ISSUE TITLE
Magiclysm's Void Mage and over 23 PER sets overmap visible range to 2.

### ISSUE THREAD

**Issue by MoonlitRiverlight** [CleverRaven/Cataclysm-DDA#64082]
### Describe the bug

Having Void Mage attunement and 24 PER or breaks overmap visibility.

### Attach save file

N/A

### Steps to reproduce

1.Grant a player Void Mage.
2.Set PER to 24 or higher.

### Expected behavior

No interaction between them. Or a positive if any.

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 22.04.1 LTS; Release: 22.04; Codename: jammy; 
- Game Version: 9777f4e [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm]
]

### Additional context

Possibly an issue with the "dark eye" bodypart Void Mage gets as base enchant?

**Comment by GuardianDll** [comment]
interesting
24 per
![image](https://user-images.githubusercontent.com/67688115/224142418-7f7a7b00-d74d-4a32-8653-ef85c7b9d889.png)

24 per + void mage attunement
![image](https://user-images.githubusercontent.com/67688115/224142643-4ded77d4-4a6f-41bc-b6d0-8b44ad33b4bd.png)
/confirmed
i actually don't know what's goind on here, but maybe @Venera3 knows about it? the dark eye json is [here](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/mods/Magiclysm/enchantments/Void_Mage.json#L35)

**Comment by GuardianDll** [comment]
\confirmed, yeah

**Comment by Venera3** [comment]
Thanks for letting ne know, I'll look into it.

**Comment by SittingDucken** [comment]
Did some testing. Issue lies with code in [character.cpp](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/character.cpp#L2315)
Applying different night visions leads to increasingly negative overmap vision. Eg adding ursine_vision drops overmap from 2 tiles to 1 tile.
Looking at the "optimal" state of vision being debug_nightvision return of 0.01, and returning a minimum value between 3.5f and our variable calculation. 
So in the lowest state of say PER == 6, we'd actually get a value lower than 3.5f at night when the multiplier is roughly 1. 

With a multiplier of 20 from dark eye, even at PER 1 (.3*20), the resulting 6 will always be higher than LIGHT_AMBIENT_LOW of 3.5f. So that math checks out for magic. We could modify the multiplier down so that PER 1 = 4 at a minimum. A value of about 14. 

Digging further, setting PER to 480 actually leads to similar results. Can map overmap by 2 tiles each. 
So night_vis = 20 is functioning fairly properly and always giving us above Ambient Light. It's when the result is over a certain value that it's problematic. 

What I'm having troubles understanding is why DEBUG_NIGHTVISION value of 0.01 is considered good vision? There's something in that math that I'm not understanding.

That's all to say, problem exists outside of Void Mage dark eyes mutation.

**Comment by SittingDucken** [comment]
Okay, setting the night_vis value between 5 to 8 is a fairly functional state even at low perception. And bumps the upper range of perception. Won't make the decision on that, and will focus on narrowing down why a high perception range total is nixing the overmap reveal.

**Comment by MoonlitRiverlight** [comment]
Given the nature of darkvision, shouldn't the bigger darkvision override the smaller ones? There's no reason in my mind for different sources to stack effects.

Either way, night_vis is interfering with overmap reveal even during the day, which makes no sense.

**Comment by A-Powerful-Mage** [comment]
Has anyone fixed this? Increasing perception should increase night vision, if perception were to change night vision at all.

**Comment by GuardianDll** [comment]
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/67688115/99d6e05f-9454-48f2-ae21-8658ef7f49af)
fixed by #64946 - limb had no default vision defined, so it was overwritten to zero; effect doesn't have this issue
