### ISSUE TITLE
Faraday Chainmail Suit - Uncomfortable.

### ISSUE THREAD

**Issue by AcidAntOnAMinefield** [CleverRaven/Cataclysm-DDA#64207]
### Describe the bug

Was wanting to re-use the old issue but it is closed so a new one it is.

https://github.com/CleverRaven/Cataclysm-DDA/issues/61910

Despite the changes in https://github.com/CleverRaven/Cataclysm-DDA/pull/61066 , there still are issues in regards to this armour. Namely the fact it is uncomfortable in literally every part of your body. This is a bit weird because there are many body parts that do not have any "softer" alternatives to wear underneath this, such as *the eyes*. 
And getting -24% speed and constant (and increasing) pain per **each different limb** is a bit silly. 

### Attach save file

n/a - easy to reproduce

### Steps to reproduce

1. make a new world, create a new character;
2. spawn a faraday chainmail suit and wear it.
3. Notice it is "uncomfortable" (refer to previous issue's Screenshot)
4. open the @ menu and check effects. Notice the number of body parts affected.
5. scramble to find soft things to wear underneath the Suit.
6. Fail to find anything for the eyes because the crafting menu's search function does not allow you to search for things that aren't "head", "torso", "arms", "legs", "feet", "hands." and one does not have the patience to scroll through hundreds of items to figure out there aren't any soft-things that protect the eyes. 
6.1 Realize afterwards that for the other body parts, one has to choose between mostly high-warmth soft gear to wear underneath which makes no sense.

### Expected behavior

I would expect there would either be more low-warmth items *or* we would have the opportunity to use the tailoring kit to pad hard items with soft materials, at the expense of minimal warmth increase and encumbrance, as well as weight and volume.

### Versions and configuration

- windows
- no relevant mods
- ce1081a

### Additional context

I was wanting to re use the older issue but I thought opening a new one would be better. I apologise if it isn't the proper course of action.

**Comment by anoobindisguise** [comment]
So chainmail is really uncomfortable to wear on your skin, in fact it was because of chainmail that something non rigid could also be uncomfortable. It making your eyes and mouth uncomfortable is a separate issue, and eyes shouldn't ever be uncomfortable from worn rigid gear anyways logically speaking but otherwise it is behaving as intended. If we wanted to fix this we could introduce a second type of qt_steel_chain that is not uncomfortable and use that material just for the eyes/mouth since those are more of a "cage" in front of them rather than affixed to them. The foot coverage could also be changed into qt_steel_chain instead of qt_steel - the thinking originally was that the way they needed to clip into your boots to provide full faraday protection precluded them from fitting on metal boots and they wouldn't conflict with the shoe soles as they don't cover there, but it's probably not necessary.

**Comment by AcidAntOnAMinefield** [comment]
Oh I am aware chainmail is uncomfortable as is - not sure if such a thing as a "Faraday Chainmail Suit" exists in real life so I cannot talk about that specifically. 

However, I do not mind it being like that in game for *most* of the body parts - I appreciate it forcing me to go out of my way to find things to wear underneath. It's the eyes, the mouth, and some specific "sub-parts" that makes it weird to deal with (read: "eyebrow", "upper lip", "chin" etc), given that there is no way to search for things that cover those sub-parts specifically, as there is no way to search for things that cover only the eyes or the ears, for example - I assume this is due to them being part of "a limb" instead of them being a limb themselves.

**Comment by anothersimulacrum** [comment]
Nope.
