### ISSUE TITLE
Pillowcases only spawn empty

### ISSUE THREAD

**Issue by JeveGreen** [CleverRaven/Cataclysm-DDA#64228]
### Describe the bug

In the latest 0.H experimental all pillowcases I've found through the last few playthroughs spawn empty. Looting several houses with spawning pillowcases have produced nothing but empty cases.

### Attach save file

N/A

### Steps to reproduce

1. Find a bed with spawned pillowcases
2. Pillowcases are always empty

### Expected behavior

I'd expect a 4-tile bed with three spawned pillowcases to at least have 1 stuffed with a pillow/down pillow.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1466 (21H1)
- Game Version: c50f83d [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Mythical Martial Arts [MMA],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]

### Additional context

This is my first issue submission, so you'll have to excuse me if I did something wrong or stupid.

**Comment by Termineitor244** [comment]
/confirmed with my experiences playing the game in the last days.

**Comment by KHeket** [comment]
Happend to me too. Problem is in https://github.com/CleverRaven/Cataclysm-DDA/pull/63704
Because I loaded lots of versions of the game to test, where this bug was appeared
https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2023-03-11-2246 here pillowcass have pillows
https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2023-03-12-0222 here pillowcases dont have pillows. And I cant understand by the code, what was maded wrong
You can simply congfirme it by teleporting to city and check houses for pillows
@mqrause can you check?

**Comment by mqrause** [comment]
Uh, huh, that's strange. I suspect it's the changes in `item.cpp` and `profession.cpp` from that PR that cause this, but I'm not sure when I'll get a chance to confirm and fix it.
