### ISSUE TITLE
Uzi 9x19mm issue with integrated folding stock

### ISSUE THREAD

**Issue by Bulletfang** [CleverRaven/Cataclysm-DDA#64340]
### Describe the bug

The Uzi 9x19mm has a strange kink right now, it comes as [Uzi 9x19mm] when you first get it, then when you modify its attached wire folding stock it turns into [Uzi 9x19mm+1], this is now with its wire stock folded. Activating it again to unfold its wire stock turns it into [Uzi 9x19mm (folded)]. However, unloading and reloading reverts it back into its stock [Uzi 9x19mm] variant. Unloading and reloading it while it is [Uzi 9x19mm+1] turns it into  [Uzi 9x19mm+1 (folded)].

### Attach save file

Should be easily reporducible, see Steps to reproduce.

### Steps to reproduce

1. Make a player with an Uzi 9x19mm.
2. The Uzi comes with its folding stock integrated, so no modding required.
3. Activate the gun and modify attached equipment.
4. Unload and reload its magazine in its various modes.

### Expected behavior

Reloading doesn't change its attachment indication in the name.
Correct unfolded and folded modes.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2728 (22H2)
- Game Version: c50f83d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Xedra Evolved [xedra_evolved]
]

### Additional context

It's pretty confusing, because its recoil value sometimes doesn't match its folded naming convention, it doesn't seem to have an unfolded naming convention at all.
I made a little diagram because I got really confused trying to make sense of it:
![Illustration](https://user-images.githubusercontent.com/45204409/225961837-ea0dec62-413c-45b7-9203-f6af53d1ab67.jpg)

**Comment by aahue1889** [comment]
Looking into

**Comment by aahue1889** [comment]
I've looked into this and I can repro the issue
- I checked other guns with spawned stocks to see the behavior and the key thing that I am noticing is that the Uzi upon spawn does not have the +1 Mod indicator
- ----

So the expected behavior should be as follows 

![image](https://user-images.githubusercontent.com/8581536/226113928-3b3a2a66-e645-466f-8c55-608de4b0a960.png)

**Comment by aahue1889** [comment]
So my current question now is
- Are built in Mods supposed to have +1 or not? I can't make a change unless I know what the expected behavior is for Built_In_Mods on stocks. (Speaking with Discord Devs)

**Comment by aahue1889** [comment]
Major Delay for an update; but I had an environment issue that I needed to fix first
---

I was able to identify where gunmods are implemented in code;

![image](https://user-images.githubusercontent.com/8581536/226802635-07b9244d-d976-4777-be21-ae67a6238dcc.png)

My next task is identifying a better place to 'repaint' the UI after a gun is folded.

**Comment by aahue1889** [comment]
Alright I finally have a potential fix that I am testing here:


I finally identified the code that was responsible for updating the 'wielding' widget 

-	Instead of including “(Folded)” into the wield widget – The with_collapsed flag is now used to determine if we want to include (Folded)
 
![image](https://user-images.githubusercontent.com/8581536/230180432-a2120609-28d9-4bcf-ac31-b250f53a07b4.png)

Why?
--- 

I don’t believe it was the intent for the Wield Widget to display ‘folded’ – as I have seen with many guns that the widget can’t contain very long descriptions returned from tname(); in the example below the ammunition count has been pushed too far to the right and is no longer visible:

![image](https://user-images.githubusercontent.com/8581536/230180568-099e014a-c175-490a-9f29-9d9eea9bd75e.png)

-	So in order for it to be more friendly for the “wield Widget” I’m using the with_collapsed parameter passed to tname

This meant that I needed to also update the weapname_simple() for the .is_gun() scenario

![image](https://user-images.githubusercontent.com/8581536/230180677-e4e97555-476b-4c04-acde-8000a3ff41d8.png)

**Comment by aahue1889** [comment]
Due to the above fix; doing some more testing with new fixes to see if it has satisfied the strange cases that I was seeing in gameplay
- In particular; activated mods don't read out their transformation text.
