### ISSUE TITLE
Cooking Flatbread at base mission does not consume flour.

### ISSUE THREAD

**Issue by Paramachina** [CleverRaven/Cataclysm-DDA#64360]
### Describe the bug

See title.

### Attach save file

N/A

### Steps to reproduce

1. Set Basecamp and get kitchen upgrade.
2. Fulfill requirements and components for flatbread.
3. Cook flatbread to your follower.

### Expected behavior

Flour should be used for flatbread.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2604 (22H2)
- Game Version: d6ec466 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm]
]

**Comment by notrman** [comment]
Maybe I should create a new issue/bug, but instead I add a comment here.
I am running experimental build 2023-02-26-061 (e6e4825) windows-tiles-x64 (OS version Win 11 Home 22621.1413 22H2).

I set up a faction camp in a fire station and noticed that several missions did not consume all required material.
All mission materials were required to be present in Basecamp Storage in order to be able to start the mission.
However, when the mission was started some material was not consumed, that I expected to be consumed (like actual building materials).
Some materials that I expected should NOT be consumed ("real" tools, like the hammer for the metalworking forge or the butcher knife for the butchering area), was also not consumed - but that is of course as expected.

 - Upgrade camp living quarters (log version) - nails and door hinges were not consumed.
 - Upgrade camp smoking rack and charcoal kiln - rocks were not consumed.
 - Upgrade camp metalworking forge - rocks were not consumed.
 - Upgrade camp fermenting vats - small metal sheets were not consumed
