### ISSUE TITLE
Extension cord breaks when going up stairs, but not down

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#64375]
### Describe the bug

I'm trying to connect the large storage batteries on the underground floor of my LMOE to the solar panels at the top of the little hill thing. If I start at the batteries and go up, "The over-extended cable breaks loose!" as soon as I go up the stairs, but if I start at the solar panels and go down to the batteries it works fine.

### Attach save file

[Magic-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11009684/Magic-trimmed.tar.gz)

### Steps to reproduce

Attempt to connect things on different z-levels, going both up and down.

### Expected behavior

Extensions cords are bidirectional.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2006 (22H2)
- Game Version: 53f9146 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Mythical Martial Arts [MMA]
]

**Comment by Kamayana** [comment]
Confirmed. I'll make sure I fix this in #64334.

**Comment by Kamayana** [comment]
So, while my PR does technically fix this issue, there's actually a wrinkle to it: that particular LMOE submap has stairs that are misaligned across Z-levels - the top stairs are 70, 60, 0, while the bottom stairs are 80, 60, -1, and the player gets teleported over 10 squares when going up or down. Since extension cords are based off of distance from the connection, it throws the distance off by 10 squares. The good news is that extension cords are long enough that they'll still work, so this is still fixed.

I believe that misaligned stairs are a holdover from older versions that didn't worry so much about accurate 3D positioning, and while many of them have been taken out of the game there's still some of them hanging around - the military bunker is another example. Because of this, I think it'd be better to just wait for maps with misaligned stairs to get fixed through gradual map updates, rather than spend the time adding misaligned stair handling to the cable code.
