### ISSUE TITLE
food rotting after player pickup action

### ISSUE THREAD

**Issue by rubenpd** [CleverRaven/Cataclysm-DDA#64404]
### Describe the bug

weird and inconsistent bug about rot timer calculation of food items drop from zombie kills... this issue is just a point where to start doing some investigations after this bug was mentioned on the devcord
![image](https://user-images.githubusercontent.com/42104923/226281879-c6e7e69c-ced6-454f-a4f2-e644e8c0392e.png)

### Attach save file

[Emerald Lake Hills-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11015532/Emerald.Lake.Hills-trimmed.tar.gz)

### Steps to reproduce

load save
kill zombies
hopefully more zombies will yield food items to test this

### Expected behavior

not sure what my stance on the expected behavior is... the food should drop already rotten? or it should stay the condition it was dropped in the first place? 
my main concern is that this leads to players unaware of this behaviour potentially picking up food that rots just a turn later, annoying to seay the least...

### Screenshots

![image](https://user-images.githubusercontent.com/42104923/226282985-927851be-37bf-41f3-ae8c-815456b21cbf.png)

### Versions and configuration

Win 10
2023-03-20-0422
Tiles
English
mod list:[
  "dda",
  "no_npc_food",
  "no_fungal_growth",
  "Tamable_Wildlife",
  "stats_through_kills",
  "speedydex",
  "package_bionic_professions",
  "blazeindustries",
  "rub_reb",
  "No_Person",
  "extra_mut_scens",
  "MMA",
  "translate_dialogue",
  "No_Rail_Stations"
]

### Additional context

A recent PR randomized rot timer of food drops but i don't think it matters for this thing

don't mind the mod loading shouting, it's just a couple of personal JSON changes

**Comment by rubenpd** [comment]
This save is in autumn, so this bug should be applicable to winter starts and advanced in time saves

**Comment by MochaModifier** [comment]
> Previously this would happen if your game start was with days passed since cataclysm. I know the Migo captive start (which starts in winter) makes majority of food, even the long lasting one, behave in this way. I think the "days since cataclysm" setting needs to be included in any tests.

#63639 or some PR related to it is most likely
There's been a few other issues related to this, such as sealed foodstuffs being old or rotting shortly after opening to eat them

**Comment by PatrikLundell** [comment]
I believe this is a long standing issue (at least since 0.E-2). If you kill a zombie and pick up items from it immediately thereafter, it's possible to see the items as fresh by have them rot by the time they appear in the inventory.
My assumption was that the rot processing didn't happen at the time the items were generated, but rather at a later tick.

My typical case was killing a zombie by ramming into it with a vehicle (before vehicles were made too brittle to be used as zombie mowers) and then pick up items from its corpse as the vehicle passed over the corpse. However, I believe I've encountered the issue when looting just killed zombies while on foot as well. Note that I don't have any experience from the time after the variable timing was introduced due to a lack of playing, so my data may be obsolete.

**Comment by andrei8l** [comment]
/confirmed The food on the map does not appear to rot because it's delayed by processing speed (10 minutes). Food on character doesn't follow that logic and gets processed on the next turn.

The easiest solution is to process the items once when they are spawned.

**Comment by Karol1223** [comment]
During my testing I was under the impression this only affected the new lunchbox contents but in a way I am relieved to hear I didn't break anything. Though, to be honest, during that testing any normal food in old itemgroups (such as malted milk balls) spawned fresh so my experience with this bug has been slightly different.

Also can confirm this does not appear to be relevant to time passed since cataclysm - during my testing I spawned on the usual starting day in spring and the bug happened regardless.

**Comment by Karol1223** [comment]
Oh in this case we've got two on our hands. That's fun...
