### ISSUE TITLE
Companion autotasks break when on different z-levels

### ISSUE THREAD

**Issue by TheDarkMaster13** [CleverRaven/Cataclysm-DDA#64577]
### Describe the bug

When a companion is doing work, they will abort the task if the player is not on the same z-level as them.  The player will receive the message, "Companion has completed the assigned task."  

In the case of disassembly work, the companion will immediately stop the task when the player is no longer on the same z-level.  In the case of the cut logs into planks task, the companion will become idle after they finish the log they were working on.

### Attach save file

N/A

### Steps to reproduce

1. Get a companion.
2. Setup a base inside a basement and assign your companion to it.
3. Assign a disassembly zone, set your companion to do disassembly work, put items that can be disassembled in that zone.
4. Wait until your companion starts disassembling something (they may need a screw driver or access to a similar tool).
5. Travel up the stairs out of the basement and take a step.
6. Companion should abort their task claiming it is completed.

### Expected behavior

Companions should be able to continue doing their tasks as normal while the player is not on the same z-level or at least remember they were working on that task until the player returns if all items are unloaded while the player is not on that floor.

### Versions and configuration

- OS: Windows
    - OS Version: 6.1 7601
- Game Version: d6ec466 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Generic Guns [generic_guns]
]

**Comment by PatrikLundell** [comment]
It is a known significant limitation of the current implementation. Suggestions to implement support for multiple Z levels have been made many times, but they eventually get killed off by the stale-bot after a while as nobody have implemented them.

A precondition to support all zone based companion activities on other Z levels is to support zone activity on Z levels other than the current one, which would require both that the zones on other levels are loaded while in the reality bubble but at a different level, and that pathing to/between zones becomes Z level aware, rather than make all calculated based on the current Z level. 3D pathing is probably trickier than 2D pathing.

I wouldn't be surprised if experimental 3D view would have to be finalized and integrated into the base game in order for Z level aware activities could be implemented.

(When it comes to disassembly, my experience is that they'll finish the current disassembly task before giving up, so the problem is that the task to pick up the next item to disassemble can't be performed as the zone is no longer loaded. I's similar with using companions and zones to dig basements: if they've actually started the digging task when you leave the basement they'll finish that tile, but won't start on the next one as the zone isn't loaded. If you leave the basement while they're still en route to the selected digging tile they'll abort when they reach the destination as it's no longer in a loaded zone).
