### ISSUE TITLE
Incorrect description of the 7.62x54R round

### ISSUE THREAD

**Issue by Donecoin33** [CleverRaven/Cataclysm-DDA#64605]
### Describe the bug

The description is incorrect in the "has not been used by militaries for several decades."
7.62x54R is still being actively used by the Russian Military in PKM's, PKP's, PKTM's, and PKB's. It's also being actively used by the Ukranian military in the form of Maxim Machine Guns and the aforementioned Russian weapons (albeit some are stolen). 
7.62x54R is currently being used in the Yemeni Civil War and the Russo-Ukranian War

### Attach save file

N/A

### Steps to reproduce

N/A

### Expected behavior

N/A

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2728 (22H2)
- Game Version: d6ec466 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by DoctorBoomstick** [comment]
I already mensioned this on discord when this issue was first high-lighted, but I’m going to drop this here as a self-reminder/ general comment. I’m currently working on rebalancing cartridge damages as well as doing some other gun related changes, so I’ll probably role a fix for this into that providing that it doesn’t get tackled by someone else.
