### ISSUE TITLE
Random footstep sounds when enhanced hearing CBM is used

### ISSUE THREAD

**Issue by GuardianDll** [CleverRaven/Cataclysm-DDA#64607]
### Describe the bug

The game spawns random footsteps really far away from character, when it uses enhanced hearing CBM and walk is certain spots
![image](https://user-images.githubusercontent.com/67688115/227805497-62b62b8e-38ec-4100-b486-a3e1762b2f5c.png)

### Attach save file

[The Indestructible Fortress-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11073113/The.Indestructible.Fortress-trimmed.tar.gz)

### Steps to reproduce

Open a save
Walk into spots, highlighted below
See phantom footsteps
Turn off Enhanced Hearing CBM
See the lack of footsteps

### Expected behavior

Lack of phantom sounds

### Screenshots

Spots, where you may reproduce the issue:
![image](https://user-images.githubusercontent.com/67688115/227806142-fedbb7fe-9d3f-4682-860f-4b7535ef6ca3.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2728 (21H2)
- Game Version: 4ae79c2 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    SpeedyDex [speedydex],
    Xedra Evolved [xedra_evolved]
]

**Comment by AcidAntOnAMinefield** [comment]
This has been happening for a long time, where the player hears their own footsteps when they step into a tile that is too dark or close to a dim light source (i.e. near a computer screen, evac shelters are good examples of this). 

No need for Enhanced Hearing CBM for this one either.

**Comment by Jan-Blasiak** [comment]
> This has been happening for a long time, where the player hears their own footsteps when they step into a tile that is too dark or close to a dim light source (i.e. near a computer screen, evac shelters are good examples of this).
> 
> No need for Enhanced Hearing CBM for this one either.

I don't think that's the issue, in that case the steps are produced close to the player AFAIK

I have to say that I've experienced similar annoyance.

**Comment by GuardianDll** [comment]
The point is that's they are not close to the player, but on a great distance - first screenshot shows like 10 tiles range bewteen the 'sound source' and me

**Comment by AcidAntOnAMinefield** [comment]
> The point is that's they are not close to the player, but on a great distance - first screenshot shows like 10 tiles range between the 'sound source' and me

Yes, the screenshot also shows broken windows and places where sunlight reaches or at least reduces your night vision to a point where you cannot see in the dark if you are in a bright tile (the "sepia filter" makes it a bit difficult to see but you can still see where the light exists): which is something that messes with the "variable lighting" thing, especially the ones at the north end of the hallway and the southernmost exit where it clearly shows lit tiles (which is in the same location the first screenshot showcasing the far-away sound takes place). Chances are this footsteps thing will only happen to you when there's day light entering the building and causing you to not be able to see the dark squares you can move into, whereas at Night / with things blocking the light sources, that will stop happening even with your CBM turned on.

The enhanced hearing CBM amplifies/gives the player the impression that sounds are louder than they actually are, and this includes your own footstep sounds; ie it makes you more sensitive to sounds, but it does not make you detect the actual sound source more accurately - which is why your own footsteps will sound like they're further away, because from your character's perspective, they are "louder" than normally with the CBM Turned on.

It does the same thing if you wait and there a sound source, for example, a zombie on the other side of a wall is "shuffling." If you have no "enhanced hearing cbm" turned off and wait for 5 minutes, you will see a lot of nearby notifications of its shuffling, and the game will create a sort of square box centered around a radius of the sound's origin. But when you turn it on, the "radius" of the shuffling sounds expands to a much larger box. 

See here, I uploaded a world with a concrete setup to be tested. 
https://file.io/3USKCc7OhNhn

Creating this character and shoved him in a house, a specific house with Lab Access (because those always have those weird "+" shaped "lit" squares in basements for some random reason. 

You will see that I have rearranged the furniture in a horizontal line that's 2 lines thick. This is true for both Z levels 0 and -1. Notice in -1 that there is a + shaped section that has 5 items that your character can see because they have some modicum of light. Step on either of them and notice how the night vision completely goes away.

If you walk up and down on those two specific tiles (any set of two tiles along the lines marked with furniture or "firewood source" markers, you will always see that random hearing nose, with the CBM turned on. You can destroy the furniture if you want, it isn't necessary, i just wanted a permanent marker for which tiles this happens in.

Notice also that the "sound" indicator when you walk up and down between any two of those tiles is always "0" (with or without the CBM turned on, with or without Light Step). 

So yes, there's something wrong with the CBM itself in very specific circumstances. I cannot fully prove that it is strictly due to the lighting, because there is (that I know of) any way to see the variable lighting in dark tiles in actual concrete numbers. But I find it sufficient that it happens in a very specific horizontal line where it just so happens to cross with a + shaped random light source.
