### ISSUE TITLE
Prevent UPS from auto-charging looted smartphones.

### ISSUE THREAD

**Issue by TurtsMcSquirts** [CleverRaven/Cataclysm-DDA#64890]
### Is your feature request related to a problem? Please describe.

I use a UPS to power all of my electronics, and I also have smartphones on autopickup for the high-capacity batteries and SD-Memory cards (which may contain rare crafting recipes) you get from disassembling them. But when I pick a few up into my backpack from dead zeds, they over the course of just a few turns drain my UPS completely, leaving no power for the stuff I actually need it for. Instead, if I want the bits inside, I have to manually disassemble every smartphone when I find it which can be dangerous and easily interruptible, and takes ages compared to bulk disassembling them when I get home. If there's already a way to prevent this, please help.

### Solution you would like.

I had a few ideas as to how this could be solved:

1: Add a toggle to the pocket menu that determines if items inside are charged by a UPS. (Like the auto-insert toggle)

2: Make it so the UPS only charges favorited items.

3: Make it so you have to manually connect items to your UPS before it will charge them.

4: Add a blacklist/whitelist to the UPS itself which determines what it's allowed to charge.

5: Make smartphones use regular batteries until modified by the player.

6: Make smartphones charge much, much slower, giving the player time to put them in a shopping cart or something before their UPS runs dry.

### Describe alternatives you have considered.

Dealing with it. Giving up on the convenience of UPS and switching back to regular batteries for my small electronics (doesn't help with power armor and the like). Stopping picking up smartphones forever. Slowly and manually diassembling every single smartphone in the middle of the street where I find them.

**Comment by chaoticidealism** [comment]
I'd dearly love some kind of solution to this problem, myself. Disassembling smartphones is a good way to get at the SD cards inside, which might have useful data on them. But whenever I pick them up, my UPS drains into them. I have to unload the UPS in order to keep it from doing that, but then of course, if I'm using UPS weapons, I have to put the battery back in if I want to charge them. It's really rather inconvenient. Definitely a quality of life feature that would make life better for UPS users.
