### ISSUE TITLE
PR#59563 miss out usable 3-inch ordnance rifle turret

### ISSUE THREAD

**Issue by Naadn** [CleverRaven/Cataclysm-DDA#64901]
### Describe the bug

I found that PR#59563 didn't add back usable 3-inch ordnance rifle turret as `turret_cannon_3in_ordnance ` when remove it as `mounted_3in_ordnance_rifle` from turret json. So the cannon vehicle can't spawn one on it as PR##45215 intended.

### Attach save file

I found it throught PR#59563 and current vehicle_parts.json

### Steps to reproduce

1. open https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/vehicleparts/vehicle_parts.json
2. search "plugged 3-inch ordnance rifle"
3. there should be a `mounted_3in_ordnance_rifle` vehicle_part on top of it

### Expected behavior

The migration should done correctly

### Screenshots

![image](https://user-images.githubusercontent.com/97841551/230540938-6019e86d-0b28-46c3-a0a2-70676aa7ee51.png)
It remove the original code
![image](https://user-images.githubusercontent.com/97841551/230540971-442e1b2c-848c-4411-8163-e8768614106e.png)
And add it in migration.json
![image](https://user-images.githubusercontent.com/97841551/230541009-030e233c-b0b8-4b92-9f04-384152d2824e.png)
But only add plugged one, not usable one.

### Versions and configuration

Cataclysm-DDA experimental build 2023-04-07-0347

**Comment by irwiss** [comment]
turret parts are generated from all guns without NO_TURRET flag,
that's why plugged variant is still defined manually - it's not a "gun"

you can spawn the entire cannon vehicle from the debug menu and it works/shoots fine
you can spawn the fort from debug menu and it'll spawn the cannon vehicle as well

migration isn't relevant except for when loading older savegames because it migrates the old vparts to the generated ones
