### ISSUE TITLE
Memories can break windows

### ISSUE THREAD

**Issue by Devengel** [CleverRaven/Cataclysm-DDA#64947]
### Describe the bug

Title

### Attach save file

[Depths Of Jupiter-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11184504/Depths.Of.Jupiter-trimmed.tar.gz)

### Steps to reproduce

1.download save file
2.go to sleep (in-game)
3.wake up by memories grabbing you after they destroy the window

### Expected behavior

Them not breaking windows

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2728 (21H2)
- Game Version: 714aa12 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Translate Complex Dialogue [translate_dialogue],
    Xedra Evolved [xedra_evolved],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    Aftershock [aftershock],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Tamable Wildlife [Tamable_Wildlife]
]

### Additional context

maybe this?
https://github.com/CleverRaven/Cataclysm-DDA/commit/69dc0dd3fdbca3e4458795a723eca2f999b36eeb
[group_bash]

**Comment by KHeket** [comment]
It is not memory. You can prove it by caged memory near the window or barricated by items, like on the screenshot
<details>
  <summary>Screenshot</summary>
  
![image](https://user-images.githubusercontent.com/102726167/232341536-aa8c99af-9f45-4c96-9353-55a0774b3739.png)
  
</details>

This is happend to me too and problem is in https://github.com/CleverRaven/Cataclysm-DDA/pull/64603
Because portal storm spawning Involuntary Traveler which is typical npc and will go to the noise source. And because of lots of random noises from everywhere during portal storms and because of crying memory monters - this will trigger npc to walt around or to source of noise and breake any breakable barricades on the way, like windows or furniture. Its easyly reproducable by turning on portal storm and hide in the shelter. This travelers also immune to portal storms effect, but the eat my food and sometimes dropped something. They also love to open my car doors, but previously is can do only persons. 

Maybe if the dont react to sounds - it will solve the problem, or may be remove them, because deadly portal storms became more deadly, because now to survive you need to hide only underground or barricade your house with unbreakable barricades

<details>
  <summary>Proofs</summary>

![Снимок экрана (160)](https://user-images.githubusercontent.com/102726167/232342355-5e9405b3-47fe-4e03-9fd9-9fc7c3da4db2.png)
![Снимок экрана (159)](https://user-images.githubusercontent.com/102726167/232342357-93e7be69-d37f-4833-a294-4392d178851f.png)

</details>
@Ramza13 need your help

**Comment by KHeket** [comment]
@Ramza13 ?
