### ISSUE TITLE
Ropes have inconsistent dissasemble results

### ISSUE THREAD

**Issue by Aimless-dude** [CleverRaven/Cataclysm-DDA#65015]
### Describe the bug

When a rope is assembled by hand from cotton patches, it will disassemble into long strings. This allows the creation of items that need strings without having  to find one. However, when a rope is assembled from the same ingredients, using an Electric Spinwheel, it will, despite saying it will disassemble into long strings, disassemble back into 30 cotton sheets.

### Attach save file

N/A

### Steps to reproduce

1) make a character with at plenty of cotton patches, and an electric spin-wheel.
2) Assemble a Short Rope using a recipes that does not use the spin-wheel. 
3) Attempt to disassemble the rope.
4) observe that it disassembles into 6 long strings.
5-6) Repeat steps 2 and 3 but using the spin-wheel.
7) Observe it disassembles into 30 cotton patches.

### Expected behavior

I expect that these two recipes should make ropes that disassemble into the same thing- either both should give 6 long strings, or both should give 30 cotton patches.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2728 (21H2)
- Game Version: c772e58 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Translate Complex Dialogue [translate_dialogue],
    No Rail Stations [No_Rail_Stations],
    No Hope [no_hope],
    Stats Through Kills [stats_through_kills]
]

**Comment by catdach** [comment]
This is caused by the spin-wheel recipes being flagged as `reversible`, while the manual recipe is not. So ropes made manually have their disassembly defined by the default "uncrafting" recipe for that item, rather than the recipe used to craft them. 

Not sure if this is really a bug or just a quirk of the system.

Note: the display of disassembly _is_ different, but only **after** the item is crafted. (rope made by spin-wheel on the left)
![image](https://user-images.githubusercontent.com/93795131/232349610-c17189f9-da0e-4a5f-bf75-ae1a94a2a51a.png)

The rope made by the spin-wheel doesn't even display a "disassembly" section, forgoing it in favor of "made from:"
