### ISSUE TITLE
balance between certain mutant tails is weird (long vs fluffy)

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#65010]
### Is your feature request related to a problem? Please describe.

The balance between the various mutant tails feels odd. Some of them have other benefits like bonus attacks, but others are just objectively way stronger than other tails. Most notable is Long Tail (feline tail) - 2 ugliness, 2 dodge, vs Fluffy Tail (wolf tail) - 4 dodge, 0 ugliness - it's so much better than the long tail that it's almost comical, especially since cats are generally a lot more agile than dogs. Rodent tail is also just as dodgy as Long Tail but much uglier for no actual benefit.

### Solution you would like.

At the very least Fluffy Tail shouldn't be so much better than Long Tail but I don't know how by how much it should be. Rabbit Tail and Fluffy Tail being specifically non-ugly is weird too.

### Describe alternatives you have considered.

@Venera3 I imagine you're going to limbify these and standardize their balance score boosts, so maybe it should just be left to you?

**Comment by actually-a-cat** [comment]
IMO

make long tail a generic mammalian tail not tied to any particular branch

nerf fluffy tail's dodge to the same as long tail, give it some sort of other dog-themed effect

make a new feline tail that upgrades from long tail and has fluffy tail's current stats

This also fixes the weirdness of lupine mutants getting cat tails on the way to getting their dog tail.

**Comment by fairyarmadillo** [comment]
The rabbit mutation line was conceived as one that is cuter/more attractive than the others, which would explain the 0 ugliness. I am pretty sure you still wind up looking hideous because most mutations have a lot of ugliness, but the idea is that relative to other mutants, a rabbit is small and cute.

I would argue that dog, cat, and rat/mouse tails serve similar enough functions that they should be statistically identical except that most people find rat tails especially ugly.

Rat and mouse tails IRL are also used for temperature regulation, which is why they're hairless. Mice (but not rats) are additionally able to use their tails in a semi-prehensile manner to aid greatly in climbing.
