### ISSUE TITLE
Fused dragonflies enemy has too much HP

### ISSUE THREAD

**Issue by thewhizkids** [CleverRaven/Cataclysm-DDA#65144]
### Describe the bug

The 'Fused dragonflies' enemy appears to have 1100HP,

for reference, Shoggoth, mi-go, Moose, dissoluted devourers, and normal Giant Dragon flies (which evolve to Fused Dragonflies) 
only have 400,200,120,112, and 50 HP respectively. 

Because of the value being so high in comparison to other enemies i believe it to be a typo and that the real value is supposed to be 110HP. (or something greater but still far lower, the current value feels out of line compared to all other creatures in the game)

### Attach save file

N/A

### Steps to reproduce

Make a player with a m4a1/assault rifle.
Shoot fused dragonflies for hundreds of damage.
Watch its health bar when inspecting it barely go down.

### Expected behavior

I expect this entity to have a health pool more in line with other creatures.
Maybe 110 or a couple hundred health at most. but not values higher than shoggoths.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2364 (21H2)
- Game Version: c772e58 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Bionic Professions [package_bionic_professions],
    Xedra Evolved [xedra_evolved],
    No Fungal Growth [no_fungal_growth],
    Blaze Industries [blazeindustries],
    No Fungal Monsters [No_Fungi],
    Bionic Slots [cbm_slots]
]

### Additional context

Hitchhikers guide also shows the fused dragonflies have 1100HP,

**Comment by fairyarmadillo** [comment]
Moose HP does seem off. It's one of the most robust animals in North America and it's only got 120 HP? I know it needs to be killable with a single rifle bullet, but isn't that still a little low?

I agree that fused dragonflies are a bit high for what they are, but I assume the inflated HP value is to reflect that it's two gigantic animals who are stuck together.

**Comment by thewhizkids** [comment]
> Moose HP does seem off. It's one of the most robust animals in North America and it's only got 120 HP? I know it needs to be killable with a single rifle bullet, but isn't that still a little low? I cannot imagine a human killing a moose irl with a baseball bat, but it's actually not all that hard in cdda.
> 
> I agree that fused dragonflies are a bit high for what they are, but I assume the inflated HP value is to reflect that it's two gigantic animals who are stuck together.
> 
> Dissoluted devourers strike me as very underpowered compared to what their description would suggest. Shoggoths have massive regeneration to balance out their low HP values so they're fine.

yeah i was just using a few other random HP values for reference to show how out of line the fused dragonflies are,
a normal 'giant dragon fly' only has 50 hp, the fused dragonfly enemy is just two giant dragon flies in mating process carrying a bunch of their eggs around. even if you combined and doubled their health pools it would not even reach 300.

**Comment by fairyarmadillo** [comment]
Well a giant dragonfly is 40.75kg and fused dragonflies are 800kg, which suggests that they've grown ten times as large before mating (though we never see any unmated ones that size, odd).

I think it might be a good idea to shrink fused dragonflies down substantially, if only because their very poor speed makes them too easy to cheese and get an enormous amount of chitin, meat, eggs, and sinew from.

They should probably also die off after mating season. It's kind of weird how they just hang around forever.

**Comment by Karol1223** [comment]
So for all of this stuff. Fused Dragonflies are only weird because they're supposed to be two fused mega dragonfly variants - and we do not have a mega dragonfly variant ingame. They're supposed to be an abomination. They likely need a touchup but the answer is not to make them smaller or make them weaker - they're supposed to be tanks like this. They're not just two giant dragonflies fused together - they're two dragonflies that grew to about cow size and then fused.

Imo, if anything, we should have normal mega dragonflies to fit the bill but I'll leave this for @Venera3 to properly answer.

**Comment by fairyarmadillo** [comment]
> So for all of this stuff. Fused Dragonflies are only weird because they're supposed to be two fused mega dragonfly variants - and we do not have a mega dragonfly variant ingame. They're supposed to be an abomination. They likely need a touchup but the answer is not to make them smaller or make them weaker - they're supposed to be tanks like this.

I would agree if they posed a reasonable challenge, but as is you can simply walk away while casually taking pot shots at them and they will be completely helpless and bleed out pretty quickly. Since they're fucking _everywhere_ once autumn hits, you basically have infinite access to free food and chitin. Yes it's mutant meat, but this is perfectly edible for many characters and even for natural humans it's a pretty decent supplement. As slow and helpless as they are, you'd think the other mutant predators would be taking advantage and hunting them down.

Furthermore, a dragonfly is a spindly little raptor-style predator, it's not a tank like a beetle or some spiders would be. They shouldn't have huge HP values unless they have the bulk to back that up.

Mega-sized dragonflies with 550+ HP run the risk of swinging too hard in the other direction. There's a reason stuff like the armored centipede is so slow. A flying version of that might cause playability issues.

Giving fused dragonflies very short lifespans would fix many of their issues, and seeing their rotting carcasses all over the place (or encountering the dangerous cocoon enemies they spawn) would help sell the idea that this unnatural explosion of life is unsustainable.
