### ISSUE TITLE
Enemy armor penetration is too high

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#65173]
### Is your feature request related to a problem? Please describe.

Many enemies have ridiculously high flat armor penetration values. The issue is that any amount of flat armor penetration applies to each layer of armor individually, meaning basically anything less than an ESAPI plate or power armor get penetrated like they're not even there.
Example: you are fighting a Giant Wasp, which has an armor penetration of 25 on its sting. You are wearing Light Tempered Plate Armor and a Canvas Aketon and it stings your torso (the aketon has 10.5 cut prot and the cuirass has 22). Due to its armor penetration you have effectively no armor whatsoever and it does full damage. Its bite also has an armor penetration of 20, which means it still does 8 damage to you out of the total 10 its bite inflicts.
Other enemies also possess huge armor penetration values, although even low values such as 5-10 are still extremely strong because they make any armor that isn't individually extremely strong moot. Some examples:
- Brutish Amalgam (15 armor pen on bite)
- Arthropod Mutant (15 armor pen on bite)
- Camo Mutant (25 armor pen on bite)
- Root Runner / Leech Plant (5-15 random on EVOLVE_KILL_STRIKE)
- Unseen Hunter (10 on basic attacks and 30 on its peck)
- Pack Rat and Tunnel Runner (12 on bite)
- Wasp Queen (25/20 like above)
- Giant Wasp Queen (60 on sting and 30 on bite)
- Dire Wolf (10 on bite)
- Anything with the `impale` special attack (8 pen plus 0.5x multiplier)

This leads to armor being almost or entirely useless against certain enemy attacks to a highly illogical extent (you can wear 20 ballistic vests and a giant wasp would still sting you through all of them effortlessly) and forces the player to rely on defenses that bypass the absurd armor pen values, namely blocking, defensive martial arts and the ADS bionic. This also affects bullets - vs a m249 CROWs, anything weaker than 7 armor does nothing against 5.56 rounds, meaning the incidental armor you pick up from sources are vastly diminished since 6 pen becomes effectively 18 pen against 3 layers of armor.

### Solution you would like.

The underlying code responsible for armor penetration could be changed so that penetration is considered against your total armor value, rather than each individual source of armor. Or, all attacks with flat armor pen could be replaced with multipliers, which properly consider each layer of armor - many enemies use multipliers instead of flat values and while I have some gripes with that (such as zombie predators having a multiplier of 0.2 letting them bite you through 4mm of tempered plate armor) it at least doesn't break the rules by making 4 instances of 2mm of armor substantially worse than 1 instance of 8mm armor.

### Describe alternatives you have considered.

I realize many of the above enemies are meant to be absurdly dangerous especially in melee but the way they are made dangerous feels very weird and contrary to expected outcomes (even the best case scenario of tempered medieval plate armor failing to stop many attacks from such enemies) and also the underlying bug with armor penetration amplifying already extremely high base values.

**Comment by fairyarmadillo** [comment]
Why not have apen be "spent" every time an amount of it is applied to an armor layer, the way that damage is "spent" when it's partially absorbed by a layer? I feel like that's what I would expect to happen as a player.

I'm also kind of chuckling at a sting from a wasp having more penetrating power than .50 BMG M2 AP. How fast is that thing going?

**Comment by Venera3** [comment]
Wasps happened in the age of  "haha monolithic 100% coverage goes `but fails to penetrate your armor`" before different layer coverages/sublimbs became a thing, they could probably move down to the low tens.

Layering needing to matter properly is fair.

An important misfeature on the player armor front is damage still being shunted to the shadow realm when absorbed - in reality you're still going to need to deal with the energy of the attack, it just gets dissipated by your armor onto a hopedfully large area. That is kind of held up by bash-lost HP being the same as cut-lost HP, but wounds should open up that design space. The other armor problem is high-end armor pretty much never getting damaged because of the rudimentary durability system, so you don't have any attrition during longer raids in the form of armor faults.

On the monster side high melee skill attackers should get a bonus to hitting less armored spots, especially after bouncing off the main armor a few times analogous to weakpoint hits on monsters. Also keep in mind player armor being absolutely ridiculously high when compared to even late-game monsters, flitting around in 40 bash armor is a completely normal occurrence for a late-game toon and makes the list of monsters who can actually hurt you about ten.

On the design side, AP is a good way to do dangerous critters without veering into one-shot territory or screwing up slower-progressing survivors unduly, an important consideration for things that can spawn in the first month or so.

**Comment by fairyarmadillo** [comment]
Part of this may be down to armor items needing a balance pass. You can get some phenomenal numbers just by visiting a museum, and even chitin and leather do really well, to say nothing of plate mail.

I am also going to be that person and say that the activity suit is ridiculous and maybe we should talk about removing power armor, which is total sci fi nonsense. Plis, we have mech suits, what exactly is the difference?

**Comment by Terrorforge** [comment]
We've had the activity suit discussion before and we'll need to have it again, but let's not get sidetracked by it here.

I feel like a lot of armor is overtuned especially re:coverage , but I think that's largely a product of having a really narrow band of values to work with. Once you factor in blocking, the relevant range is basically just 5-20, maybe even just 5-15. This creates a situation where it's really hard to make any one piece of armor matter without any two pieces immediately hitting the maximum relevant total, and even harder to make those pieces meaningfully different. There's no room for e.g. a breastplate with 30 bash at 90% coverage, because if I'm already wearing the 5-bash aketon I'd need to cover the remaining 10% I might as well throw on a tempered chainmail vest with 13 bash instead and enjoy equal or better protection in virtually every situation other than getting high-rolled by one of the three most dangerous monsters in the game.

Anyway that's kind of a tangent, I think the important thing is that we seem to be in agreement that armor penetration should not work like this.

**Comment by fairyarmadillo** [comment]
> An important misfeature on the player armor front is damage still being shunted to the shadow realm when absorbed - in reality you're still going to need to deal with the energy of the attack, it just gets dissipated by your armor onto a hopedfully large area. That is kind of held up by bash-lost HP being the same as cut-lost HP, but wounds should open up that design space. The other armor problem is high-end armor pretty much never getting damaged because of the rudimentary durability system, so you don't have any attrition during longer raids in the form of armor faults.

Will player damage eventually get this feature too? It could help solve the combat knife problem, where the thing somehow hits harder than most spears or swords despite being relatively tiny and having far less mass and swing force.
