### ISSUE TITLE
No Difference Between 60-Round Magazines for HWP/Exodii Battle Rifle

### ISSUE THREAD

**Issue by halosammy** [CleverRaven/Cataclysm-DDA#65230]
### Describe the bug

I am filing this as a bug because I am under the impression that the current issue is a placeholder that no one got around to fixing.

The 12.3 magazine for the HWP has the following description:

- Physically speaking, this looks like one of the box magazines that the Exodii use for their own guns, but with a more ergonomic design afforded by the Hub's use of modern materials.

On comparison, the HWP variant is neither lighter, shorter, or less bulky. They also have the same flag.

### Attach save file

N/A

### Steps to reproduce

1. Spawn HWP 60-round 12.3 magazine and PA md. 68 Exodii 60-round magazine.
2. Compare item characteristics to notice that they are identical.
3. If necessary, double-check via Hitchhiker’s Guide.

### Expected behavior

Presumably, the HWP magazine’s characteristics would reflect its description. However, I couldn’t provide exact expectations for how this should be fixed on account of the fact that “ergonomic” is a buzzword that can mean plenty of things.

An alternative solution would be just reworking the description to fall in line with gameplay.

### Screenshots

N/A

### Versions and configuration

Build: 2023-04-21-0222

### Additional context

N/A

**Comment by RenechCDDA** [comment]
Yep, should be some simple json bonking. I would suggest lowering the weight, shaving off maybe 100-200 grams. I probably wouldn't touch the volume (it's hard to optimize away thin sheet metal after all), but if one was inclined they could justify it as the HWP magazine being double-stacked. (If the volume is changed, longest_side should also go down to represent its shape becoming more of a cube than a rectangular with double-stacking)

Here is where you would need to change:
https://github.com/CleverRaven/Cataclysm-DDA/blob/cdda-experimental-2023-04-24-1122/data/json/items/gun/robofac_gun.json#L503-L520

and just for comparison's sake, the exodii magazine:
https://github.com/CleverRaven/Cataclysm-DDA/blob/cdda-experimental-2023-04-24-1122/data/json/items/magazine/exodii.json#L22-L40

**Comment by halosammy** [comment]
> Yep, should be some simple json bonking. I would suggest lowering the weight, shaving off maybe 100-200 grams. I probably wouldn't touch the volume (it's hard to optimize away thin sheet metal after all), but if one was inclined they could justify it as the HWP magazine being double-stacked. (If the volume is changed, longest_side should also go down to represent its shape becoming more of a cube than a rectangular with double-stacking)

For the sake of being realistic, how much would double-stacking alter the volume? My kinesthetic sense is genuinely awful.

**Comment by RenechCDDA** [comment]
Not by very much. Remember the volume still needs to be >= 60 rounds worth of ammunition - it's a magazine after all! There's obligatory space at the top (feed) and bottom (spring) which cannot be reduced, and the rounds do not perfectly go from vertically stacked to side-by-side. 

...and I wasn't going to but I went ahead and did some back-of-the-napkin calculations for you. Since the 12.3ln round is essentially ".30-06 but alien .30-06" I calculated the enclosure for 60 of those using the values off wikipedia's infobox. Given a cartridge base diameter of 12mm (width and length), a cartridge height of 85mm, and 0.5mm air+1.5mm of sheet metal on all sides, our existing 60-round single-stack box magazine looks something like 90mm x 16mm x 750*mm = 1.08L.

*(Remember, spring and feed! 30mm added to account for those.)

1.08L is a bit far off of our existing 1.25L magazines, but it's within an order of magnitude so we'll work with it for now.

Now if we double stack that we roughly double the width but reduce the height proportionally or so. I'm just going to assume double width, half height, keeping the 30mm of feed and spring. Which gives us 90mm x 28*mm x 390mm = ~0.98L.

*(Remember, we're adding 2mm of 'dead space' between the air and sheet metal on both sides! We're not doubling the overall width of the magazine, only the rounds inside it.)

~10% is more than I'd expect but this is very much back of the napkin math.

**Comment by halosammy** [comment]
You can’t imagine how grateful I am right now.

**Comment by RenechCDDA** [comment]
I was asked in the discord about this, and I agree: The calculated height of a single-stack magazine is rather absurd (750mm?!). So, I think it's safe to assume that the exodii magazine is already double stacked.

Thus, the double-stacked exodii magazine would be something like:  90mm x 28mm x 390mm = ~0.98L. Let's say 1L, which is already a *very* large magazine. (Longest_side, 390mm or so)

But we want the hub's magazine to be *better*, and how can we make this better? Well, we can assume hub *quad stacked* it. Yes, a real thing. https://www.shootingillustrated.com/media/zwxbgike/kel-tec-cp33-1.jpg

So let's recalculate that. 90mm x 52mm x 210mm = ~0.98L. At this point we're getting essentially no *volume* benefit out of it. However, our longest_side is now 210mm or so. That begins to be pretty reasonable, or at least it can fit into many non-specific magazine pockets.

You also have the option of changing around the `MAG_BULKY` flag to `MAG_COMPACT`, but a 60-round magazine of this caliber is going to be very large (remember, around 1L) so I would not do that.

I leave the specifics to you.

**Comment by halosammy** [comment]
Pull request is up.

https://github.com/CleverRaven/Cataclysm-DDA/pull/65296
