### ISSUE TITLE
Feed NPC from sealed container will not unseal the container

### ISSUE THREAD

**Issue by SurFlurer** [CleverRaven/Cataclysm-DDA#65263]
### Describe the bug

Feed NPC from sealed container will not unseal the container.

### Attach save file

[npcneed-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11302974/npcneed-trimmed.tar.gz)

### Steps to reproduce

1. Load the save.
2. Ask the NPC to "use this item", then select "canned meat ( fresh ) ( hot ) ( 11 )".
3. One charge is consumed, but the large tin can is still sealed.

### Expected behavior

The large tin can to be unsealed.

### Screenshots

![图片](https://user-images.githubusercontent.com/22912139/233823744-4708ca37-486b-4fa4-ba52-9172dd63e5f8.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2846 (22H2)
- Game Version: 0.G-1503-ge8a1eafffb [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by PerfectlyInternal** [comment]
Happens for me on both the latest experimental build and 0.G., looking into it now.

**Comment by PerfectlyInternal** [comment]
I get a segfault too when I make the same changes, but it occurs while removing the item from the inventory, specifically at this line:

https://github.com/CleverRaven/Cataclysm-DDA/blob/69c3dbb431febdff993c92b285e4b8542a06dfa7/src/talker_npc.cpp#L572

One layer down, and the segfault is caused by getting the name of the item for debugging:

https://github.com/CleverRaven/Cataclysm-DDA/blob/69c3dbb431febdff993c92b285e4b8542a06dfa7/src/character_inventory.cpp#L289

item::tname() is checking if the item is null, which somehow results in a read access violation.

https://github.com/CleverRaven/Cataclysm-DDA/blob/69c3dbb431febdff993c92b285e4b8542a06dfa7/src/item.cpp#L6292-L6293

I can't make sense of what's happening here, and I find it quite strange that we have very different errors from the same code changes. Any ideas?
