### ISSUE TITLE
Current game keeps repeating "invalid beta talker" issue despite no NPCs being in range

### ISSUE THREAD

**Issue by JeveGreen** [CleverRaven/Cataclysm-DDA#65313]
### Describe the bug

See title.

### Attach save file

[Cascade-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11330982/Cascade-trimmed.tar.gz)

### Steps to reproduce

Just walking around triggers the error.

### Expected behavior

I guess, not seeing this constant error?

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1466 (21H1)
- Game Version: 01203da [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Bombastic Perks [bombastic_perks],
    Mythical Martial Arts [MMA],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

 DEBUG    : Excessive error repetition detected.  Please file a bug report at https://github.com/CleverRaven/Cataclysm-DDA/issues
            Tried to use an invalid beta talker.

 FUNCTION : actor
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\npctalk.cpp
 LINE     : 1799
 VERSION  : 01203da

**Comment by Proxima-b** [comment]
I can confirm this issue happening

**Comment by CansecoGPC** [comment]
It happens on Linux too since this release, [cdda-experimental-2023-04-26-0000](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2023-04-26-0000)

No error on repetitive actions with previous releases like, [cdda-experimental-2023-04-25-2249](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2023-04-25-2249)

Maybe this latest change #62640 has something to do with it?

**Comment by chaoticidealism** [comment]
Confirmed; happens for me, starting just after starting a new game in the evac center.

- OS: Windows
    - OS Version: 10.0.19044.2846 (21H2)
- Game Version: 01203da [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved],
    Generic Guns [generic_guns],
    DinoMod [DinoMod],
    Megafauna [megafauna],
    Extra Mutated Scenarios [extra_mut_scens],
    Mining Mod [Mining_Mod],
    More Survivor Stuff [more_survivor_stuff],
    Mythical Martial Arts [MMA],
    Translate Complex Dialogue [translate_dialogue],
    Magiclysm No Class Limit [magiclysm_no_class_limit],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by andrenaP** [comment]
OS: Windows 10
cdda-windows-tiles-x64-msvc-2023-04-26-0511
Game Language: Ru
mods:[
  "dda",
  "no_npc_food",
  "personal_portal_storms",
  "no_fungal_growth",
  "package_bionic_professions",
  "magiclysm"
]

**Comment by Elitrom** [comment]
The game told me to report to Github after "Excessive error repetition detected" because this one couldn't stop from popping up:
OS: Windows
OS Version: 22H2
Game Version: 01203da [64-bit]
Graphics Version: Tiles
Game Language: System language []
Mods loaded: [
Dark Days Ahead [dda],
Disable NPC Needs [no_npc_food],
No Fungal Growth [no_fungal_growth],
Bionic Professions [package_bionic_professions],
Bombastic Perks [bombastic_perks],
Portal Storms Ignore NPCs [personal_portal_storms],
SpeedyDex [speedydex],
Stats Through Kills [stats_through_kills],
Stats Through Skills [StatsThroughSkills]
Magiclysm [magiclysm],
]

**Comment by aMegaSloth** [comment]
```
- OS: Windows
    - OS Version: 10.0.19045.2846 (22H2)
- Game Version: 2671deb [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda]
]
```
Evacuee start, NPC within sight.. still happening.

As started before, doesn't happen with build prior.

**Comment by aMegaSloth** [comment]
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/11338329/debug.log)
I figure I might as well attach the debug log for completeness.

**Comment by Saint-of-Grey** [comment]
Well, now you got me investigating.

This very much seems to do with #62640, the json changes in that seem to be running into errorchecking code from the much older #50757, which made sure that poorly written EOCs report errors instead of silently swallowing them. I'm guessing the problem is that the new EOCs are being applied to the generated NPCs you start the game with, which have their own bit of code to set up missions and whatnot.

**Comment by bombasticSlacks** [comment]
For anyone curious the reason this error happens is because the EOC to check for the trait runs every second on everyone including all NPCs and the player.

This *I'm pretty sure* doesn't work at all since the NPCs are the alpha talker for their instances of the EOC. 

Anyways I'm rewriting it to make sense, and fixing the underlying bugs that revealed it.

**Comment by Saint-of-Grey** [comment]
Awesome, I spent 30 minutes bashing m head on a keyboard trying to fix it myself before realizing I don't know that much about EOCs.

**Comment by Proxima-b** [comment]
Still an ongoing issue as of now
