### ISSUE TITLE
Add a bionic operating suite to the hospital

### ISSUE THREAD

**Issue by Waladil** [CleverRaven/Cataclysm-DDA#6531]
Among the issues with bionics is that installation penalties can be too severe, ironically leading to a negation of the entire system of installation penalties.

Player can be permanently debuffed by the installation of a malfunctioning bionic, and player can lose other rare and useful bionics through a botched install. Because these penalties are so severe, it is incredibly foolish to not do everything possible to avoid those penalties. Those penalties /neccesitate/ the abuse of drug binges and the 0 install time of bionics to drop the fail chance as low as possible.

Therefore, ameliorating the worst downsides can allow players to take greater risks, attempting installs of lucky finds earlier rather than being forced to both cache a good find and abuse game mechanics in order to use said lucky find. 

To that end, I propose two things: One, change the "some of your existing bionics are lost!" to "Some of your existing bionics are disabled!" Disabled bionics are non-functional, and may have minor downsides relevant to their old function. For example, a disabled recycler unit would reduce the character's health (because his/her body is no longer as skilled at handling its own waste toxins), damaged subdermal armors would increase encumberance in the relevant areas (lost flexibility), the fusion blaster arm would continue to prevent use of two-handed weapons. Stuff like that (and not all bionics have to carry a disabled penalty. Some might just be dead weight).

The other thing, the larger project, is a bionic operating suite be added to hospitals, difficult to access but highly useful to characters with damaged bionics. The operations performed are very straining on the body, giving hefty amounts of pain, damaging body parts, and increasing hunger and thirst levels over the course of several hours. However, the operations also remove malfunctioning bionics and restore the function of disabled bionics. 

So note that this is not utterly removing all failure penalties. You still need to either have access to or gain access to an operating suite in a hospital (which can be a pretty tough fight and I'd argue for extra special protection around the operating suite), and it still exacts a toll on the player, but the toll is something that can be paid and moved past, rather than a permanent levy. 

Oh, and if this is put in, then we could in good conscience start smacking down the abusive tricks players use to install bionics. Like maybe changing the code to use base int rather than current int, mwahaahaahaa.

An alternate possibility on top of this is to remove the purely-bad malfunctioning bionics entirely and only have disabled versions of working bionics. Not sure how I feel about that, because it could make the professions that start with them suddenly really good, and because having dedicated bad bionics is kinda cool. 
##

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
