### ISSUE TITLE
Bandits drop their guns and throw cans of food around once they run out of more "sufficient" methods of long range combat

### ISSUE THREAD

**Issue by 209CATrus** [CleverRaven/Cataclysm-DDA#65321]
### Describe the bug

In the title. Stumbled upon an ambush, with a sniper and gunner in bushes. Sniper expectedly ran out of ammo, and when i started approaching him, dropped his rifle, switched to a jar of pickled veggies and threw it at me. With 6 damage. Thankfully, the pickled veggies weren't hurt. The second bandit switched from glock (which should technically have ammo) to cream soda can on approach too.

The first screenshot below describes the drop of remington and switch to a jar of pickled veggies by sniper and subsequent damage from throw. Second bandit also switched to can of cream soda.
 
Second screenshot shows the distance of the throw. Just look at it. He barely aimed his rifle, yet managed to hit me with a jar at such distance.

P.S.: I never asked for this

### Attach save file

N/A

### Steps to reproduce

1. Spawn bandit
2. Give him very big gun
3. Give him very big jar of pickles
4. Approach him and see what happens

### Expected behavior

I don't know what to expect, the AI does best it can (or should i say, the best it jar) at defending apparently

### Screenshots

![изображение](https://user-images.githubusercontent.com/26685838/234685060-2e4e866d-6a80-461b-bcc3-943a33931d5f.png)
![изображение](https://user-images.githubusercontent.com/26685838/234687449-f5981638-5490-49bc-9c1b-cc5741ab31f8.png)

### Versions and configuration

Copy from VERSION.txt
build type: linux-curses-x64
build number: 2023-03-01-0054
commit sha: d6ec466140839dd70c1a43671eb4a08b007695c2
commit url: https://github.com/CleverRaven/Cataclysm-DDA/commit/d6ec466140839dd70c1a43671eb4a08b007695c2

### Additional context

N/A

**Comment by 209CATrus** [comment]
![изображение](https://user-images.githubusercontent.com/26685838/234691424-9c1b3f85-8a8e-4f8b-b494-1c597dfd1fa8.png)
He threw that can of cream soda and apparently ran out of ammo. You should probably add more food to bandits

**Comment by 209CATrus** [comment]
![изображение](https://user-images.githubusercontent.com/26685838/234702639-1e2aade2-876c-4101-8727-adb577f4763b.png)
The other bandit threw his carbonated drinks too

**Comment by fairyarmadillo** [comment]
This is a longstanding issue with how enemies prioritize their weapons. The default behavior should weight things that are actually in the weapon category higher than hats and food, but I recall that there's been resistance when this idea has been mentioned before.

**Comment by MochaModifier** [comment]
> This is a longstanding issue with how NPCs prioritize their weapons. The default behavior should weight things that are actually in the weapon category higher than hats and food, but I recall that there's been resistance when this idea has been mentioned before.

On top of that, NPCs can't seem to distinguish between weaponry intended for ranged combat, and weapons better suited for melee.
I.e. NPCs will happily throw their _combat knife_ (often times horribly missing) and then proceed to wield something silly like a spork. 

Adjusting the AI would probably take a bit of work - but it would be nice to maybe deprioritize throwing random objects and melee weapons. I'm guessing the game doesn't discriminate between throwing and firing a high powered rifle- but maybe it should

That, or just disable this behavior for all but a few sensible items (rocks, sticks, weapons explicitly intended for throwing) so NPCs stop wasting time,( or worse, throwing away valuable weapons) in a fight

**Comment by stubkan** [comment]
I think this is because the AI calculates the potential damage for every item/weapon in its inventory - and at some stage, there is no chance for them to shoot you (out of range or blocked) and then the soda can suddenly becomes a viable option at that one specific point with a 5% chance to hit you for 1 damage or whatever, then the npc proceeds to do just that.

I agree with fairyarmadillo there needs to be some kind of block for non weapon items - no sensible person would be throwing their precious collected items out of their inventory.  The only time we see this in media is in the comedy film Shaun of the Dead where he throws his precious record collection at a zombie ineffectually.

This is a longstanding issue for years now, it would be easily fixed by just ignoring any throwing as a viable weapon option during the scan inventory for items damage scan phase and allow it as an option only when it actually makes sense for the npc, when they have a high throwing skill plus an item with the json tag "thrown_damage".  A tag which all throwing weapons have, and soda cans do not have.

Also - giving this item damage scan phase some kind of temporary memory would also greatly mitigate this issue, I think.  If a npc discovers that they have a pistol, then for whatever reason the pistol is blocked (someone moving behind a barrier) they immediately toss the pistol and move into melee and wield their helmet.  However, if they have a temporary weapon memory which is retained for a couple of turns - they can 'remember' that they have a very good pistol, which still is better than a wielded helmet and continue to wield it for a little longer.  During which time, the player may move out of cover or become attackable once again with the pistol.
