### ISSUE TITLE
character creation problem

### ISSUE THREAD

**Issue by harmez7** [CleverRaven/Cataclysm-DDA#65338]
### Describe the bug

talking about the new character creation system not the legacy multi-pool
say: knowledge, offence, defense and social .
they're meant to be a measure to inform the players about the character they're about to create.
if you enable this option `setting > debug > show values for character creation`, you can see exact values for each field.
the problem is it doesnt do a good job at telling the truth
example: weak stomach reduce the lifestyle value by 1 and irreparable also reduces this value by 1 which is not practically correct
because irreparable is a much much stronger negative trait than weak stomach
and many more examples.
back then, we used to tell how strong a trait is based on its point cost/earned and now since there's no point limit anymore it can totally mislead new players from knowing how strong/weak their character is going to be .
i think it's a very important issue and requires a solid fix to stop the misunderstanding.
simply because, having a too strong/weak character kinda ruins the fun, dont you think ?

**Comment by Proxima-b** [comment]
Agreed, I don't think the new system is based on points to do the evaluation
in `data\json\mutations\mutations.json` , irreparable trait has a total of -12 worth of trait point, it makes no sense that it would only reduce the lifestyle by one. 
There must be hidden value somewhere, and that value is not doing a good job representing the actual attributes of a character.

**Comment by anoobindisguise** [comment]
Also spawning as a character who wears highly encumbering gear (Patriot, anyone with high heels) reduces your Defense score quite a bit, despite the fact that you can just... take the clothing off. 

Slow Reader affects your Knowledge but Illiterate does not.
Deaf has no bearing on your Social score.
Flimsy+ and Slow Healer+ have no impact on your Defense.
Skills are worth a shitton of Knowledge so it's better to just take points in Int and forgo knowing things if you want your score to not be Overpowered.
And since it's literally just the number of bad traits you have for your Lifestyle, if you want your Lifestyle to be Average and not like, Powerful or Overpowered you just take a ton of random useless traits again, Heavy Sleeper, Truth Teller, etc so that the score tells you that you're about average.

**Comment by sonphantrung** [comment]
And choosing scenarios from "Extra Mutated Scenarios" mod (like "Aquatic"), makes the Defense weak. I know the line is not-so-useful, but the "Aquatic" mutation adds nothing literally!

**Comment by Proxima-b** [comment]
Maybe the new evaluation system should be jsonfied (into 5 seperate fields maybe) on each mutations, so we can start editing them.
