### ISSUE TITLE
NPC hogging processor time

### ISSUE THREAD

**Issue by caseyc37** [CleverRaven/Cataclysm-DDA#65336]
### Describe the bug

NPC's highest-priority task in basecamp is to build a door.

Basecamp includes no hinges, no wooden panel.

NPC searches for these components repeatedly, taking several minutes of real time just to not-find them a few hundred times while my PC takes a single step.

### Attach save file

N/A 

### Steps to reproduce

1. Create basecamp with NPC
2. Use zone manager to create a blueprint zone to build a door
3. Ensure that the camp contains no hinges, no wooden panels (but plenty of nails and planks so that the empty frame can be built)
4. Give the NPC the priorities: Construction 3, chop logs into planks 2, cut down trees 1
5. Wait until the NPC has built the empty frame
6. Try to walk around camp

### Expected behavior

If an NPC searches the basecamp and does not find the necessary components to complete any task, that NPC should wait for one move's worth of time before searching again.

### Versions and configuration

OS Linux, gentoo
Version 0.G Stable (as of May 3)

**Comment by PatrikLundell** [comment]
No. If a task cannot be completed it should be abandoned and not taken up again until a significant time later (although I would consider it acceptable to retry after having performed some other task, even if that was a short one, so in your case it ought to be after chopping up a log, or, if none is available, after cutting down a tree).

**Comment by RenechCDDA** [comment]
Possibly a duplicate of #64799

Will try to investigate soon, just noting this here before I forget

**Comment by MochaModifier** [comment]
An alternatively desirable behavior would be for the NPC to fail in finding materials, abandon this task permanently, and report to the player.
I think this would be ideal, as it directly informs a player of the problem and gives some indication of what is needed to resolve the situation.
The game can disable relevant zones in order to prevent NPCs re-attempting them.

Checking a board, or taliking to an NPC could lead to a report such as:
"I abandoned construction of shallow pit x16. I abandoned this task because: 
I lacked a tool with digging quality 1 or better. 
I could not find a path to the construction zone.
I will not re-attempt this task until you instruct me to; I have disabled the construction zone for now"

That said, even bare bones or basic tasks such as "dig several shallow pits directly next to the npc, and the NPC is currently holding an entrenching tool" causes this immense drop in performance.

Perhaps an even simpler solution would be to have NPCs only seek out and attempt tasks once per X minutes or hours in game. This won't fix or address issues with NPCs being incapable - but it will prevent NPCs from destroying the games progression of time.

**Comment by caseyc37** [comment]
Any of those possible desirable behaviours will be a distinct improvement. I rescued my game with a save game editor, setting the NPC's job priorities all to 0 and changing the NPC's current activity from ACT_MULTIPLE_CONSTRUCTION to ACT_NULL; the second of those pretty instantly solved the problem on its own (thus verifying, at least to my mind, that the problem lies in the construction action).

It may be worth noting that I had no logs to chop and no tree-cutting zone defined.

**Comment by RenechCDDA** [comment]
Duplicate of #64799
