### ISSUE TITLE
Carry gun on regular zombie dont have magazine nor ammo

### ISSUE THREAD

**Issue by gettingusedto** [CleverRaven/Cataclysm-DDA#65412]
### Describe the bug

For some reason, the guns carried by regular zeds don't have magazines. I get it if it has empty mag, but i dont get when the whole magazine has gone as if they just drop the mag on the ground

### Attach save file

N/A

### Steps to reproduce

1.Kill zombies till you found the one that carried a handgun
2. see that it doesnt have magazine nor ammo

### Expected behavior

Having a magazine, preferably with some ammo inside.

### Screenshots

![Screenshot_20230501-211053](https://user-images.githubusercontent.com/78019001/235469911-64cc4d2b-0af2-4a16-acb1-50e4da831f46.jpg)

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: samsung; Model: SM-A710F; Release: 7.0; Incremental: A710FXXU2CRC2; 
- Game Version: 3010c62 [32-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Xedra Evolved [xedra_evolved],
    Bombastic Perks [bombastic_perks],
    Magiclysm [magiclysm],
    Crazy Cataclysm [crazy_cataclysm]
]

**Comment by TimPollard** [comment]
I'm seeing this as well.

I've had a little look at it, and it appears to be due to how `Item_modifier::modify` in `src/item_group.cpp` calculates random capacities.

Basically if you read `doc/ITEM_SPAWN.md` it says if you set a minimum number of charges, but no maximum it will automatically use the normal maximum for the item, but `Item_modifier::modify` calculates the maximum based on the assumption that the gun doesn't have a magazine (which is obviously then 0).

If you manually set a maximum number of charges it will respect that and then automatically add a magazine if needed.

-----

The easiest, but slightly tedious and error prone, solution is to just set a `charges-max` for each of the guns in `guns_pistol_common_everyday_carry`.

In my opinion the better solution would seem to be modifying `Item_modifier::modify` to calculate max charges based on the default magazine for guns that don't already have a magazine.

I've had a play around with the C code, but I don't perfectly grasp the set up, and I'm not happy with any of the "solutions" I've come up with so far. If someone more experienced with the code-base doesn't fix it before then, I'll have another look at it next week.

**Comment by TimPollard** [comment]
My attempts to fix this last week where embarrassingly bad, but I had another look at it today, and I've managed to creat a pull request that should fix this, _and doesn't segfault_. :-)
