### ISSUE TITLE
Urns and memorial items spawn in bookstore shelves

### ISSUE THREAD

**Issue by CuteCottonCandyCat** [CleverRaven/Cataclysm-DDA#65450]
### Describe the bug

After clearing out a bookstore of its books, I saw that the items recovered included alcohol, a beaded bracelet, and an urn full of ash.

### Attach save file

[Century Village-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11380218/Century.Village-trimmed.tar.gz)

### Steps to reproduce

1. Find bookstore.
2. Find memorial items on shelves that wouldn't be expected in a bookstore.

### Expected behavior

It's expected that bookstores would typically lack human memorial remains.

### Screenshots

![image](https://user-images.githubusercontent.com/46524886/235850886-373a4a74-40cc-42ec-8a68-c5b65310b7f1.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.1555 (22H2)
- Game Version: 5dec493 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Generic Guns [generic_guns],
    Stats Through Kills [stats_through_kills],
    Tamable Wildlife [Tamable_Wildlife],
    No Fungal Monsters [No_Fungi]
]

**Comment by RenechCDDA** [comment]
Bah this is an ugly one with nested groups. You're located in a `s_bookstore_2_east` but even after generating new ones with the map editor several times and viewing them through clairvoyance, nothing of the sort spawns (including in the lockers). I also manually went through the item groups to find any ways this could be possible and was unable to. Just in case my manual search was not exhaustive I used the ingame item group tester to give me examples of all the item groups that spawn in that mapgen and the closest was maple syrup in the snacks groups.

Finally after exhaustively going through the item groups I found the culprit was `mansion_books`. Still couldn't ID the nested group so I went through and again tested the item groups inside `mansion_books`... *exhaustively*......

It stems from `memorial_mansion` being part of `mansion_books`.

https://github.com/CleverRaven/Cataclysm-DDA/blob/2b4ab3d0097f9ead642fba1e1f84aab4e1091e37/data/json/itemgroups/books.json#L579

https://github.com/CleverRaven/Cataclysm-DDA/blob/d7d57c7db7f513ef9cae535cdba511dae0063ab2/data/json/itemgroups/collections_domestic.json#L364-L372
