### ISSUE TITLE
JSON functionality for referencing a "monstergroup" as anothers "monstergroup"s, "monsters" list's, "monster" value

### ISSUE THREAD

**Issue by RadaRadaRada** [CleverRaven/Cataclysm-DDA#6546]
Currently, It is possible to make zombies evolve as one continues to play the game, but that would require an immense amount of work to accomplish and continue to maintain. I would like to suggest an enchantment to current "monstergroup" JSON reading capability, with this example:

```
{
"type":"monstergroup",
"name" : "GROUP_ZOMBIE_T1",
"default" : "mon_null",
"monsters" : [
  { "monster" : "mon_zombie"...},
  { "monster" : "mon_zombie_fat"...},
  { "monster" : "mon_zombie_cop"...},
  ...
},{
"type":"monstergroup",
"name" : "GROUP_ZOMBIE_T2",
"default" : "mon_null",
"monsters" : [
  { "monster" : "mon_zombie_grabber"...},
  { "monster" : "mon_zombie_shrieker"...},
  { "monster" : "mon_skeleton"...},
  ...
},{
"type":"monstergroup",
"name" : "GROUP_ZOMBIE",
"default" : "mon_null",
"monsters" : [
  { "monster" : "GROUP_ZOMBIE_T1", "freq" : 100...},
  { "monster" : "GROUP_ZOMBIE_T1", "freq" : 100, "ends"  :   72...},
  { "monster" : "GROUP_ZOMBIE_T2", "freq" : 100, "starts" :   72...},
  ...
}...
```

Additionally, ability to reference "monstergroup" as a value for "monster" would allow to make monster spawn chance less then 0.1%.
##

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
