### ISSUE TITLE
'Patrol, Follow' orders for Programmable Autopilot non-functional

### ISSUE THREAD

**Issue by veliandev** [CleverRaven/Cataclysm-DDA#65596]
### Describe the bug

When creating a robot to perform patrols or follow the player, if the player accesses the robot through an electronics control unit or remotely using the remote vehicle controller and selects the `Control Autopilot` and chooses `Patrol` or `Follow`, the robot vehicle will instead remain static. It will sometimes beep about an obstruction. The engine will turn on like it is preparing to go, but is seemingly halted by itself.

### Attach save file

[Test World-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11459902/Test.World-trimmed.tar.gz)

### Steps to reproduce

- In the test save, activate the `Remote vehicle controller` in the player's inventory
- Select `Execute one vehicle action`
- Select the provided robot vehicle (ads)
- Select `Control autopilot`
- Select `Follow`

### Expected behavior

When the `Follow` command is triggered, the vehicle should move. When a patrol zone is created and the `Patrol` command is triggered, it should wander about within the zone.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/48538072/238c8bf2-4b74-4cbe-ab4b-d93842f59e4b)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2965 (21H2)
- Game Version: 778a26c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by deepvelocity** [comment]
Confirmed. 
Cause: when [void vehicle::selfdrive( const point &p ) ](https://github.com/CleverRaven/Cataclysm-DDA/blob/93d1f4abe99e5041fd9499865742a3c6591ef2f0/src/vehicle_move.cpp#L1287) is called, it sets is_following to false due to a bug introduced in https://github.com/deepvelocity/Cataclysm-DDA/commit/959332a86574bf09006d4ddebbd35e8a4852dae0

Explanation: initially, the check was to disable autodrive only if there was a part fueled by animal with no animal harnessed. If there was no part fueled by animal, it did not do anything. The commit in question made self_drive fail whenever there was no animal in the vehicle, rendering rest of the logic unreachable. 

When I reverted the change, vehicle started following me and was able to patrol.
