### ISSUE TITLE
Melee weapon balance

### ISSUE THREAD

**Issue by fairyarmadillo** [CleverRaven/Cataclysm-DDA#65634]
### Is your feature request related to a problem? Please describe.

Melee weapon balance is in a constant state of flux as systems and items are added and modified. This is an issue post for sorting out where melee weapons are at with @Tharn and anyone else who wants to jump in.

### Solution you would like.

The current dominating meta appears to be taking a martial art like Eskrima and a lightweight stab weapon with stun, specifically Eskrima+combat knife turns your character into a blender. The low base damage is massively offset by a combination of both weakpoints and enemies generally having worse stab protection than cut. The problem, as I see it, can be broken out into individual issues:

1) Martial art disabling techniques proc very often. Most enemies hover around 100 speed, and a healthy survivor with a lightweight weapon will always outspeed them. Even if stuns are only proccing every third attack, flawless victory is pretty much assured in any one on one fight. I don't know that that in itself is an issue - TWD and other zombie media generally depict a healthy person with a weapon as being able to kill a single zombie without being bitten - but even car-sized enemies like hulks and juggernauts can get stunlocked this way. Realistically a standard human fighting a juggernaut would be relying more on dodging and wearing the thing down than simply battering it into submission with a hand weapon.

2) Cut doesn't have much going for it. https://github.com/CleverRaven/Cataclysm-DDA/issues/59786 proposes a solution that will actually solve a lot of this, because weapons like axes are potentially being hindered by their split damage, while combat knives should be doing cut ~50% of the time. I don't know that this will totally solve the issue of the cut damage type being sort of lackluster, though. 

3) Specific weapons probably need nerfs or buffs, and it's possible we may want to think about how we're figuring out damage for piercing weapons. A spear, for instance, can probably stab someone much harder than a knife because it's two-handed and has much more potential for a longer/harder thrist when attacking with it, but as currently statted, the steel spear only gets 4 more bash and 6 more stab damage per attack than the combat knife, and it's much slower. 

4) Vs. Agile and Vs. Armored might be overweighted in the current DPS tests. The fact is that a reasonably skilled survivor is not typically going to have a hard time hitting agile enemies with anything (see comments to watch a 3 melee survivor with a combat knife destroy an unseen hunter that has 8 dodge), and most enemies are not particularly well-armored. Those that are can be partly circumvented with weak points, which is something that feels great as a player and shouldn't be removed, but we should account for the fact that people are doing it.

### Describe alternatives you have considered.

The above is a scattershot of my vague understanding of the problem as I have observed it as a player and community member, and contradictions/suggestions/arguments are more than welcome. I will update the above section with adjustments or alternative ideas collected in the comments as we go.

### Additional context

Weapon DPS tests, if you're unfamiliar, use a weird formula that is hard to pin down in manual testing. The best results I've found have been to make a character with 10 in every stat and 2 in every skill, then have them look at a weapon and take the average of its best, agile, and armored DPS values. This has so far put me in the ballpark of what the build test tends to get for its DPS numbers.

**Comment by Tharn** [comment]
Good point on endgame survivors not really caring much for vs. Normal and vs. Agile. They similarly don't care much for Stamina cost either, though. They can basically disregard that second row of equations because they're not going to run out even in brawl-type engagements unless they're getting into serious trouble with fast, reliably hitting and throwing enemies.

The following table was taken from 0.G, so if anything has changed stats-wise I'll have to do this again with the current experimental. At a glance, we see that Rapier and War Hammer are outliers in their effectiveness both in DPS and Stamina efficiency. Morning Star, Estoc and Combat Machete are similarly very powerful but trailing a bit behind the top two. Morning Star has the weakest special move set of the bunch. Bludgeons have only Medium Block as well. Zweihänder needs a speed buff, I think, and Falx as I outlined in the other post could be made into a piercing weapon, or even a pierce/cut hybrid. Bo staff, for being a dedicated asian quarterstaff, is just a downgrade to a quarterstaff. Lucerne Hammer is actually... not that far off from reasonable, since slowness is its own serious downside. It's deadly in NPC hands since they don't have stamina, but that's a separate thing and they might, in the long run, gain stamina bars.

The Bludgeon list is also not exhaustive. I added the ones I thought were interesting for comparison's sake. Lemme know if I copied any base values wrong.

![weapon comparison](https://github.com/CleverRaven/Cataclysm-DDA/assets/13466852/cbfdf963-a918-4f78-8aad-88e83d7c1eaa)

**Comment by fairyarmadillo** [comment]
I wouldn't even say endgame. 3 ranks and 10 in stats is enough to reliably hit pretty much anything, and given that it's very easy to get feint and many of the worst-offending weapons cause bleeding, missing attacks just isn't really a big deal most of the time unless you're using something wacky like a sledgehammer.

I spawned a 10 stat 3 skill survivor with no armor and easily stabbed an unseen hunter (8 dodge!) to death in pure darkness without any problem. I didn't even have to drop my bag:

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/94415528/4889e024-b794-4d42-9d85-b1bb207acbde)

I don't think we should be looking at endgame characters at all for this issue. The build tests the game uses assume 4 skill and 10 stats, and most people's experience with the game will be below that. While late-game balance is important, I think it's less of a problem if a guy with 8 skill is able to do some really goofy stuff with a given weapon - of course he is, he's a master.

**Comment by Tharn** [comment]
Yeah, we can go that way. That is my current character, who arguably has not maxed his various damage skills (and they aren't all the same), I think I'll have to do that table anew, now that you mention it.

**Comment by Tharn** [comment]
Tempered Weapons in the latest Experimental version, with a character with 10 stats and 4 in all combat skills.

Interesting to note how certain weapons got a fair bit better as the character's power level increased. The Rapier is less of an outlier in this table. But Falx and Zweihänder are still pitiful.

![tempered weapons experimental](https://github.com/CleverRaven/Cataclysm-DDA/assets/13466852/7f86fcde-701a-45b1-8025-8e889113c4cc)

**Comment by Tharn** [comment]
Same thing for the bashing weapons list (incomplete, may add the rest). We see War Hammer still as a big outlier.

![bashing weapons experimental](https://github.com/CleverRaven/Cataclysm-DDA/assets/13466852/b46eb1fe-ec0e-4885-ac0d-171bd0d97ed1)

**Comment by Tharn** [comment]
I'm thinking - if the goal of a War Hammer wielder is to drive the spike into a thing, the damage as a result should be more around 2/3rds piercing, 1/3rd bashing. The weight of the impact is what does bashing damage, not the actual surface. A War Hammer is like a "war pick", and although you could use the blunt end - that seems like something you'd only do to get a better chance to-hit in certain situations.

I'm also still behind the Falx becoming a Slashing/Piercing hybrid, since it is a forward-curved blade with not particularly great slashing prowess (see Youtube) but the unique ability to do a swinging stab "around" a shield or an arm or item raised in defense of a particular spot.

The Zweihänder, finally, should just be faster. It's big, but it's still a sword. Even large swords are surprisingly light. It should be around 2,2 to 2,7 kg. It's in-game currently at 3,24 kg, making it too heavy for a historically accurate (slender but large) German two-hander.

**Comment by fairyarmadillo** [comment]
Balancing the spread of multi-type damage will be addressed by https://github.com/CleverRaven/Cataclysm-DDA/issues/59786 and is probably not something that needs a temporary PR. I think the scope of the discussion is really better limited to the five or six weapons that allow a low-skill poorly-geared character to steamroll high-end enemies, and the weapons which should be much better but aren't.

**Comment by Tharn** [comment]
The thing is.. low-skill poorly-geared characters don't get into medieval weaponsmithing. I've never been able to craft a proper melee weapon until midgame. The craft gating is much higher here vs. the Unarmed Clothing. My luck with finding good weapons in exhibition cases has been nil, seems pretty low chance in general.

Anyway, Zweihänder and Falx could see some love. And a small nerf to War Hammer. That's really what the dummy character yields. I'm not so sure about the greatness of Estoc and Rapier anymore. They scale the best into lategame, but my only explanation would be that the stats actually do take vulnerabilities learned into account. That's more turning into a general issue with Pierce, as you suggested.

**Comment by Tharn** [comment]
Actually, after giving the dummy character all vulnerability professions and looking at the DPS tests again, there is no difference. Whatever synergy Piercing and vulnerabilities have, they don't show up in these numbers so that's more like an "invisible buff" that I can't quantify.

The first table from 0.G was poisoned in that the character had slightly higher Pierce compared to the other two damage skills. We should not read into that too much, rather look at the other two from experimental.

**Comment by AlexanderCecile** [comment]
I saw someone mention recently, although I can't remember where (the subreddit?), that weapons like the combat knife should probably have the stam (and move?) cost increased since the shorter reach means you need to move more to use it. Making changes to some of the martial arts is a good idea.

**Comment by Terrorforge** [comment]
I wanna point everyone here to [GAME_BALANCE.md](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/GAME_BALANCE.md), which explains the current (nominal) stance on weapon balance. The short version is that speed and to-hit value are determined from relatively objective factors, and then damage is adjusted to make the DPS fit into certain ranges based on the weapon's type. I see two obvious problems:
1) It creates an absurd situation where a weapon that's faster and/or more accurate must necessarily have lower damage
2) There's not a lot of space between categories. A sword is only 20% more damaging than a knife. A halberd is only about 50% more damaging.
And of course these problems are then compounded by the fact that these guidelines aren't always followed. Peruse [expected_test_data](https://github.com/CleverRaven/Cataclysm-DDA/tree/master/data/mods/TEST_DATA/expected_dps_data) and you're sure to find some oddities. Many of these are the result of the accuracy overhaul changing the DPS of weapons, and altering the tests to match the new values instead of adjusting the weapons to match the old values because that was [a massive ballache.](https://github.com/CleverRaven/Cataclysm-DDA/issues/60766#issuecomment-1238046078), which points to another problem with the DPS metric: there's a lot of overhead. I would certainly welcome some kind of system that works this out in a more objective fashion, like the to-hit calculations.

> But it remains an average knife-sized weapon. It makes sense to have that speed. If you increase stam/move cost, that means it simply gets made heavier because the move cost is a function of its weight.

The problem here is that this system itself doesn't make much sense. In as far as "attack speed" is even a real thing, it's not a function of raw weight. A sword and a mace weigh about the same, but the mace is significantly less nimble as a function of its weight distribution - but at this point we're butting up against the fact that two creatures taking turns to deliver one (1) wallop each every 0.X seconds is a fundamentally unrealistic way to represent melee combat in the first place, and I'm not sure what to do about it short of ripping out the entire melee mechanics and replacing them with a round of Street Fighter.

**Comment by fairyarmadillo** [comment]
I have always thought that DPS as a balancing factor was a crappy contrivance that the industry has been cargo culting ever since World of Warcraft, and it was only a thing in WoW because they had to come up with a combat system that worked regardless of how bad everyone's latency was. I don't think it has any place here, and trying to use it has steadily worsened the weapon situation since it was implemented (was it right after 0.E?). It's especially egregious here because it conflicts with the flat damage reduction on armor and has been a contributing factor in the weird ballooning of combat numbers.

I don't think an objective measure of damage is too far out of reach. All we have to do is look at the weapon's primary damage type and make a judgement based on a few factors. Its length, its weight, what sort of weapon it is (improvised, primitive, less-lethal, lethal), and the surface area of the point of impact.

That's not a small job, but it would take us away from using MMO tools to "balance" a single-player game.

**Comment by Terrorforge** [comment]
Yeah, DPS is kind of an odd measure for this game. Not because it's single-player, but because of how the damage numbers and enemy health line up. You're not whaling on a boss for 20 minutes, you're mostly hitting a zombie 1-3 times (hulks notwithstanding). If you're fighting a monster with 50 health, a weapon that deals 50 damage is twice as good as a weapon that deals 45 damage because it kills in one hit instead of two, but 45 damage is identical to 30 damage because it takes two hits either way. It's a breakpoint game, not a DPS game.
