### ISSUE TITLE
Misc maintenance/improvements to innawoods

### ISSUE THREAD

**Issue by RenechCDDA** [CleverRaven/Cataclysm-DDA#65632]
### Is your feature request related to a problem? Please describe.

This is mostly intended for @Light-Wave although other input is welcome. These are all things I plan to resolve myself, I just need direction on the preferred direction.

I'm going to list and number a series of suggestions and then provide my suggested changes in the next category. These have been written down to myself as notes, so some of them might be a bit rough.

1) Ceramic shards can be foraged from the trash_forest group, is this intended? It was added by @Light-Wave originally. https://github.com/CleverRaven/Cataclysm-DDA/blob/9a4259f56731c94ea315baa785d3804af24661dc/data/mods/innawood/itemgroups/trash_and_debris.json#L16

I believe they **may have been** originally added to allow basic butchery without making tools but ceramic shards no longer work for that purpose (cutting 2 is required).

They're a pretty rare find so if they were intended to be used for butchery I think their role can be replaced by sharp rocks (although the cutting 2 requirement being hardcoded is problematic)

2) Wood sawing 2 quality in innawoods requires steel tools(bow saw/wood saw), which means you cannot make screw press/still/**furniture** without massive infrastructure. 

3) The still also requires duct tape. This makes me very sad because duct tape is hard to acquire in innawoods.

4) Can't make spurge seeds from spurge plants

5) Wooden frames/etc require prying 1 to take apart, which requires.... hammer! STEEL hammer. So if you make a mistake on your dinky little vehicle put together with bronze nails you CANNOT take it apart until you get to the 'iron age'.

5a) The only way to make a steerable wheel mount (for a vehicle) needs wire so.... steel is definitely required

6) Bronze chisel for chiseling 2? used for breaking apart some ores into their component bits (manganese dioxide and zinc). Can be useful when someone is skilling into applied science faster than fabrication

7) Access to the fine cutting quality requires at least a bronze knife. Ok, reasonable, but... the bronze knife requires flatjaw tongs (at the least) to make. Very few of the bronze sandcast mold recipes require this. Why does the *knife* require tongs? Surely it can just be poured, cooled, and grinded down to a good edge afterwards?

Flatjaw tongs *require* multiple lumps of steel, although they can be forged with anvil 1(boulder)/hammering 2(stone hammer). It's not totally impossible, BUT....

7a) Fine cutting is required for making spear shafts. These are required to make proper spears, including stone, copper and brone spears.

7b) Spear shafts *also* require some sort of sealing agent (tallow/animal cooking oil/vegetable oil). It can be very difficult to get any of these, as fat/animal cooking oil requires you to kill a **sufficiently large** land animal and vegetable cooking oil requires an enormous investment for a screw press.

8) The ammonia recipe in innawood appears to have been accidentally(?) changed to produce ammonia solution. Ammonia solution has ~~almost no uses~~ (**actually** no uses in innawoods), and innawoods has a lot of recipes expecting you to use liquid ammonia. One of those recipes is glass shards: https://github.com/CleverRaven/Cataclysm-DDA/blob/9a4259f56731c94ea315baa785d3804af24661dc/data/mods/innawood/recipes/other/materials.json#L66-L72

9) No way to make lye/lye powder in innawoods(lye recipes are not autolearned). This+no liquid ammonia means no black gunpowder, no biodiesel

10) Fermentation! Fermentation vats require... 13 small metal sheets oh my god. So that's either 39 straight hours of crafting, or grinding to fabrication 9 and then disassembling a large sheet metal

11) We need some other way to get access to to the oven cooking 2 quality. I wish to make hazelnut cake. My clay pot oven does not allow me to make hazelnut cake.

12) Glass shard recipes requires... pot(requires full steel tools) OR makeshift pot(requires sheet metal...) OR sheet metal(fab 9 AND full steel tools)

### Solution you would like.

1) These are manmade items so I think they shouldn't be forageable. The fact they were added by Light-Wave themself gives me some pause, though.

2) Add a bronze saw OR a "primitive" iron/steel saw which provides this quality, but doesn't require the player to have a full steel production chain+fabrication 7. 

The recipes could be adjusted instead but... there's a *lot* of recipes.

3) The still should probably just get an alternate recipe without duct tape. Easy. (It doesn't make sense to need duct tape when you're building it from scratch either)

4) I don't know if this is an oversight or intentional but seeds can only be acquired from wild foraging, which makes spurge non-renewable. This is only really relevant in innawoods, as the latex-->rubber recipes cannot be learned in DDA. ~~I should probably just google this and find out how it bears seeds~~

5) Perhaps some sort of long tapered stick (to act as a wedge+lever) is appropriate, it's only prying 1 after all. And there's no windows/manhole covers to open anyway, so balance is not really a concern.

5a) I don't know if wooden land vehicles are desired without access to steel, but if  you tame a horse/cow early it'd feel kind of bad not to be able to use them as a beast of burden until the industrial revolution arrives. Foot pedals would still require steel access, although parts like the *sail* (even on land) could possible allow bizarre land vehicles with only bronze, which may not be desirable.

6) Bronze chisel should definitely just be a thing, maybe even a basegame CDDA thing.

7) A comment on the recipe (it was previously an innawoods-only recipe and got moved to DDA a while back) explaining its production process would help, or removal of the tongs requirement. Alternatively the sandcasting part could produce a basic knife without fine cutting, and a separate recipe using grinding/filing could consume it to produce a a knife with an appropriately sharp edge (with fine cutting 1).

7a) Perhaps a recipe change in innawoods is called for?

7b) The oil requirement is legitimate and realistic, but the difficulty of acquiring a single craft of oil is due to a combination of factors. 

For example, hunting rabbits is insanely difficult due to their skittish nature and incredibly high speed - which they can maintain **indefinitely**. A self bow or other ranged weapon is a necessity, but even with them you could spend an entire day chasing down a rabbit and not get a kill.

Vegetable oil seems more reasonable on the face of it, but the existing recipe is for a **very large** screw press that presses a **huge** amount of seeds/paste at once. Maybe some sort of very simple small-scale process (operated entirely by hand with little/no mechanical leverage) should exist.

8) I know it's unrealistic to craft ammonia this way, but this just seems to be an error which needs correcting? (With the edit I am now sure that this is just an error. Ammonia solution actually has no uses whatsoever.)

9) Make the basic lye electrolysis from salt water recipe autolearned. This allows the player to (expensively! electricity is very valuable!) make lye and then process it into lye powder, instead of locking out all of its related recipes.

10) A wooden fermentation vat should be okay I hope?

11) A construction made of fire bricks should be strong enough to withstand the high heats associated with baking.

12) Some alternate way to make glass without going full industrial revolution would be nice, and should be realistically possible? Venice was a major glassmaking industry at the end of the 13th century.

### Additional context

Oh goodness that's a lot of words. I hope this isn't troublesome to go through.

**Comment by Light-Wave** [comment]
1. The idea was that these shards were the result of wild clay being heated by wildfires or struck by lightning. When I added them, I thought the shards were going to be useful, but that might not be the case. Since they cause more confusion that convenience, perhaps they should be removed. I also don't know if cheremic even can from that way.
2. I'm fine with most things that require metalworking. It would be reasonable to make a bronze tool with wood sawing 2 perhaps, but I would like that tool to be added to mainline in that case, and not be unique to Innawood. That being said, I don't like how it is not possible to make vegetable oil without such relatively advanced equipment. I think it would be reasonable to have a slower and less efficient recipe available without the screw press. As for the still, I generally consider alcohol brewing to be after metalworking and during chemistry in the Innawood tech tree.
3. There is talk about changing around how duct tape works, and what needs it. See #65531 for more discussion about that.
4. When you harvest the spurge flower, you get both seeds and the plant. This signals to me that the usable part of the plant is distinct from the part that holds the seeds, and thus not interchangeable. You also get seeds from harvesting plated flowers. See #61101 for when I came to this realization.
5. A prying tool made from bronze would make sense to me. Perhaps a bronze crowbar. But again, I would prefer that to be added to mainline in that case.
6. I generally consider chemistry to be after steel in the tech tree, and I don't want players to be able to bypass the whole process of gaining blacksmithing tools. So I think a better solution would be to lower the chisel level requirement to 1. Although if you end up changing recipes for modded ores, you might also want to push such changes to the mining mod to keep the recipes consistent. 
7. I approve of changing this recipe to not require flatjaw tongs. I could see an argument to reduce the spear shaft requirement to fine cutting 1, but I'm not sure that is necessary. I do think tallow is easy enough to get. Most giant bugs drop mutant fat, and dogs are relatively easy to find and kill for tallow. But as mentioned before, vegetable oil should preferably be made much easier to get, at least in small quantities.
8. Yeah, the changes to ammonia recipes really messed up Innawood endgame progression. I _think_ most important things that used to require ammonia has had alternative ways of getting them introduced. It would be nice if there was an easier and perhaps less efficient way to make ammonia, but I would prefer such things to go into mainline in that case. The ammonia recipe should probably be removed from Innawood, and some of those glass shard recipes should be revised and if possible ported to mainline as well.
9. I didn't notice that lye stopped being craftable. As you said, that recipe should be made autolearned. I agree.
10.  An alternative vat that is completely wooden makes sense to me. Again, I would prefer to see that in mainline in that case. The fact that many effects of the brewing barrel are hardcoded could potentially be problematic, so watch out for that. Alternatively, as I mentioned before I'm fine with brewing being where it is now, after steel and during chemistry in the tech tree.
11. The construction you suggests sounds reasonable. Should be put in mainline.
12. The required tools seems fine-ish to me from a gameplay perspective. But if you can find sources saying other tools can be used instead, feel free to try to push that to mainline. Maybe bronze items would work?

Thank you for taking time for this. :thumbsup:

**Comment by RenechCDDA** [comment]
Thanks for the comprehensive reply!

> 1. The idea was that these shards were the result of wild clay being heated by wildfires or struck by lightning. When I added them, I thought the shards were going to be useful, but that might not be the case. Since they cause more confusion that convenience, perhaps they should be removed. I also don't know if cheremic even can from that way.

There might be some limited circumstances where it can, but fired raw clay without added grog has pretty poor properties and tends to break easily. So I'm going towards *remove* on this one.

> 2. It would be reasonable to make a bronze tool with wood sawing 2 perhaps but I would like that tool to be added to mainline in that case, and not be unique to Innawood. That being said, I don't like how it is not possible to make vegetable oil without such relatively advanced equipment. 

I'll need to do some research on both of these.

>4. You also get seeds from harvesting plated flowers. See https://github.com/CleverRaven/Cataclysm-DDA/pull/61101 for when I came to this realization.

Wow, okay. You are absolutely correct. HHG does not report the seeds coming from planted spurge.... because `seeds` is an optional part of seed_data and defaults to true. Heck. I reported that on nornagon's repo so hopefully that can get cleared up, but you're absolutely right it's not an issue for innawoods or CDDA.

>6. So I think a better solution would be to lower the chisel level requirement to 1. Although if you end up changing recipes for modded ores, you might also want to push such changes to the mining mod to keep the recipes consistent.

These recipes are actually vanilla DDA recipes (neither DDA nor innawoods has any item with chiseling 2 available). https://cdda-guide.nornagon.net/tool_quality/CHISEL

They're somewhat tough minerals, so I'm not sure that lowering them to chisel 1 (stone chisel) is appropriate. In line with your other suggestions (and agreeing that it's appropriate for DDA) I would say a bronze chisel for DDA? 

(I keep saying bronze because *copper* chisels wear out very very quickly. When quarrying for the Giza pyramids the Egyptians had entire foundries dedicated to smelting copper chisels, which constantly needed to be replaced after being used on the hard stone)

>7.  I do think tallow is easy enough to get. Most giant bugs drop mutant fat, and dogs are relatively easy to find and kill for tallow.

Fair enough! I have something of a self-imposed rule not to use "impure"(mutant/tainted) sources. 

>The ammonia recipe should probably be removed from Innawood, and some of those glass shard recipes should be revised and if possible ported to mainline as well.
>9. I didn't notice that lye stopped being craftable. As you said, that recipe should be made autolearned. I agree.

Hm, okay. Looks like just losing the ammonia and glass shard recipe then. Everything else involved with ammonia looks like it should be okay with the reintroduction of lye (although oxidizer powder and subsequently the *2nd* black gunpowder recipe will be present but uncraftable)

>10/11/12.

These will probably be the ones I get in first.

>[PatrikLundell](https://github.com/PatrikLundell): I think there should be a distinction between brewing/fermenting and distillation.

I think the changes to add a wooden fermenting vat should do a lot for this. You'll still be able to ferment yeasts, vinegar, wines, and low-alcohol beverages, but proper distillation will remain locked behind stills with their distilling 2 quality.

Once again, thanks for the responses!

**Comment by PatrikLundell** [comment]
Concerning fat rendering: Yes, I think the appropriate player distinction is to separate fat used for food and fat used for (non food) crafting purposes. That's what I (eventually) did in my Innawood game.

Alcohol: Yes. I agree a wooden vat should be sufficient (although a fully wooden barrel wouldn't hurt, but there seems to be technical hard coding issues with that, and it isn't critical).

**Comment by Light-Wave** [comment]
6. Right now, in order to get chisel 2, you need to craft a polishing stone, which takes several days of hard work. If you introduce a bronze chisel that does not require this tool, then that could potentially change the Innawood game balance a bit. That is not necessarily a bad thing, just something to keep in mind.

The rest  sounds good. 👍

**Comment by RenechCDDA** [comment]
Need to organize the work that still needs to be done, might as well do it as a comment.

- [ ] 1. Remove ceramic shards from innawoods forage list
- [ ] 2. Possible bronze replacement for wood sawing 2 quality, or alternative recipes for things that need it (e.g. furniture)
- [ ] 2b. Vegetable oil still needs investigation.
- [x] 3. No changes needed right now.
- [x] 4. Spurge seeds working as desired and the display issue on HHG was addressed.
- [ ] 5. Some sort of bronze or lower tech prying tool, mainlined if possible.
- [ ] 6. Bronze chisel, ditto to above
- [ ] 7. No changes needed re:tallow. Bronze knife recipe can be changed to remove flatjaw tongs.
- [ ] 8. Remove ammonia recipe, glass shards recipe using ammonia should be removed.
- [ ] 9. make lye recipe autolearned in innawoods
- [ ] 10. Fully wooden fermenting vat.
- [x] 11. Implemented a constructable brick oven.
- [x] 12. Glassmaking recipes were audited for the tools used in them.

**Comment by db47h** [comment]
Just chiming in regarding fully wooden fermenting vats. I've found an archaeological study of 3 large barrels found in France and dated between late 1st and early 4th centuries AD with wooden hoops: https://journals.openedition.org/gallia/5242#tocto1n3. This is in French unfortunately but there's an English abstract. Just for reference, the barrels are about 2 meters high and had a capacity of up to 1200 L.  The overall build is more or less the same as current barrels. As for the hoops, they are all made of split hazel saplings, between 2 and 5cm in diameter and 3 to 3.5m long, curved and tied together using plant fiber strings. The hoops are placed in 4 groups of 2 to 3 hoops (up to 9 hoops total).

BTW, from what I've read, iron hoops did not appear before the 19th century with the advent of industrialization.

This all wood vat would also need a wooden spigot. I wonder if we could bake it into the recipe or take the opportunity to add an item spigot that could be used as an alternative to a water faucet in select recipes.

One last thing, I came here following a discussion on this on discord where someone mentioned https://en.wikipedia.org/wiki/Kvevri. Large clay containers that were buried. I personally like the idea. Also, before Romans adopted barrels around 2nd c. AD, they used amphorae for wine (fermenting-wise it was probably closer to a vinegar-ish grape juice than wine, but that did the job). Any thoughts?

I'm willing to do the PR for the all wooden vat (and spigot), as well as any clay alternative (yes, I'm aware that vats are hard coded ;). Should I open a separate issue for this?

**Comment by Light-Wave** [comment]
That sounds excellent, db47h.
I don't think you need a new issue for that, no. You can have your PR refer to this issue without having it completely resolve the issue.
If you can get those changes into mainline, that would be much appreciated. You would probably have to touch the C++ code a bit, as you mentioned.  Hopefully it won't be too difficult.

**Comment by db47h** [comment]
Will do. Touching the code if needed isn't an issue. Speaking of which, What about the wooden spigot and a clay based alternative for the vat? Amphorae feel too easy to make (or make them have a smaller capacity, say 20L only?), but I find the  Kvevri quite interesting, it would require digging a pit and a bunch of clay to make (~25 to 30 lumps if I take the hydria as a reference).

**Comment by Light-Wave** [comment]
It's my understanding that alcohol fermentation is disrupted my moving the vat around, so anything used for fermentation should be furniture, and not an item. So best to not make any movable amphorae.
The kvevri sounds interesting. It sounds reasonable to add. It could also be useful to have another massive man-made fluid containing piece of furniture in general, just to store lots of clean water. Kevevri sounds useful for that as well.
Wooden spigots seems easy enough to make, I think? Although I'm not sure they would be absolutely necessary for the fermentation process. I would suggest make them autolearned and use them as a requirement for the wooden fermentation barrels.
If I remember correctly, constructed furniture doesn't remember what items was used to craft it, so it will always return the same items when deconstructed. Thus, I think it would be best to leave the existing fermentation vat recipe as-is, using a metal water faucet. If both metal and wood could be used, the game wouldn't know which item to give you when you deconstruct it, which could cause frustration and confusion.

**Comment by db47h** [comment]
Thanks for the feedback. I didn't think about the implication of just making an alternative recipe for the vat as well as adding a wooden spigot in other recipes. I'll start by adding a proper wooden vat with the spigot baked into the recipe. After that, I'll see how to implement other fermenting devices (via a pseudo item I guess?) and go for the Kvevri.

**Comment by db47h** [comment]
Now that I have a better idea of what I'm getting into, I think I have decent-ish plan to implement more fermenting containers, that involves merging these with kegs and adding a "sealable" flag for containers that can be used for fermenting (and maybe separate cheese making from brewery). I'll open a separate issue to discuss this.

**Comment by db47h** [comment]
Back on the initial topic, here are some additional comments:

9/ Lye can be obtained but only as a byproduct of making hydrochloric acid through electrolysis. That's doable, but requires some serious dedication to get there. Also the recipe for lye that requires washing soda would not help much without liquid ammonia.

Sugar is an issue as well: no lye, very little options for sugar besides hunting down aphids for honeydew (renewable?) or waiting to get maple syrup. No luck with bee swarms either for me. Anyhow, building an apiary would be a chicken and egg problem. May be add forest honey to the loot tables of underbrush?

Going from electronics 2 to 3 is kinda hard without crafting useless stuff just for the sake of it since the only craftable recipes at this stage are an electrolysis and a survivor headlamp. And the electrolysis kit is not usable until electronics 3 with access to the batteries. A possible option would be to make the soldering practice recipe improve electronics up to 3. BTW, level 0 to 1 is weird too, just making antennas.

**Comment by db47h** [comment]
Some new recipes requiring rubber hoses have not been updated to be craftable in Innawood (mounted workshop, all variants of spear slings, plus some others that I may not have access to yet). The slingshot is a special case since it may require an actual rubbery thingy.

No mozzarella cheese, which requires a non craftable mesh colander.

**Comment by RenechCDDA** [comment]
> 9/ Lye can be obtained but only as a byproduct of making hydrochloric acid through electrolysis.

That's a good catch, I didn't actually realize this was a thing.

> Also the recipe for lye that requires washing soda would not help much without liquid ammonia.

In my previous posts here I was referring to the lye_by_electrolysis recipe, which is simply 2 salt water, 250 charges of electrolysis kit, and some time.

>Sugar is an issue as well

Lye will help with this situation, but even without lye there still exists the ability to use sugar beet syrup/molasses (sugar beet can be found in the wild in innawood), which is... pretty historical? The pure white table sugar we all know and love is mostly a modern thing.

**Comment by RenechCDDA** [comment]
The lye byproduct from hydrochloric acid was actually added by Light-Wave and is still working as implemented/intended, so I actually think no changes are necessary on the lye front.

**Comment by Light-Wave** [comment]
The intention there was to make the recipe auto learned, not to alter it from mainline in any other way.
Since then the mainline recipe has been altered slightly, while the Innawood version has been left behind.
I have considered going through all Innawood recipes and change them to use copy-from instead, as that might help prevent Innawood recipes to fail to be updated when mainline recipes are altered.

**Comment by RenechCDDA** [comment]
Right, I see what you're saying. It's hard to keep track of this sometimes, since you have to exhaustively compare two parallel histories to see what happened when and why changes were made, etc...

I would caution against using copy-from for recipes, at least for the moment. See: #60257

Do you still want the lye_by_electrolysis recipe(itself) to be autolearned?

**Comment by Light-Wave** [comment]
>I would caution against using copy-from for recipes, at least for the moment. See: https://github.com/CleverRaven/Cataclysm-DDA/issues/60257
Good to know.

>Do you still want the lye_by_electrolysis recipe(itself) to be autolearned?
Yes

**Comment by db47h** [comment]
> > 9/ Lye can be obtained but only as a byproduct of making hydrochloric acid through electrolysis.

I did manage to get some decent amounts of lye that way. So, doable, but this needs some serious infrastructure and dedication (I can't say if this is a bad thing or not). The only real gripe I have with this is that I only found out about the byproduct thing by asking on Discord. (add byproducts to search results in the crafting menu?).

The modular workshop and kitchen units are not craftable either (they need a rubber hose).

I've reached a point where I don't know if some recipes are deliberately not craftable or not, so I won't add more to the list, but if there's anything I can do to help, please let me know.

**Comment by RenechCDDA** [comment]
Byproducts can be searched in the crafting menu, with the `r:` prefix.

**Comment by Light-Wave** [comment]
Lye was meant to be easily craftable, but mainline has moved around and Innawood has not kept up, unfortunately. I think adding the electrolysis recipe as autolearned would solve that issue well enough.

I would prefer for the workshop and kitchen to be craftable as well.
The reason for the rubber hose seems to be to move liquids around, so perhaps make the recipe accept some pipes and pipe fittings as an alternative to a rubber hose. That seems like a reasonable tweak to put into mainline, even. I'd appreciate if you could make that happen.

**Comment by db47h** [comment]
> I would prefer for the workshop and kitchen to be craftable as well. The reason for the rubber hose seems to be to move liquids around, so perhaps make the recipe accept some pipes and pipe fittings as an alternative to a rubber hose. That seems like a reasonable tweak to put into mainline, even. I'd appreciate if you could make that happen.

I'll do it this weekend. We'll discuss the recipe details in the PR

**Comment by Devengel** [comment]
The big crater overmap might need a rebalance, this is just the valuable loot from looting two craters in there. 
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/71761521/1e3fda02-4af1-4e48-aa25-5ec24050900f)
