### ISSUE TITLE
`Hang on a bit…` everytime i run

### ISSUE THREAD

**Issue by gettingusedto** [CleverRaven/Cataclysm-DDA#65666]
### Describe the bug

Whenever im running, `Hang on a bit…` popped up for a brief moment. I don't think it did that in the past.

### Attach save file

N/A

### Steps to reproduce

1. Change the movement mode to run
2. Run around
3. `Hang on a bit…`

### Expected behavior

`Hang on a bit…` not popping up when im running.

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: samsung; Model: SM-A710F; Release: 7.0; Incremental: A710FXXU2CRC2; 
- Game Version: c2f139b [32-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Xedra Evolved [xedra_evolved],
    Bombastic Perks [bombastic_perks],
    Magiclysm [magiclysm],
    Crazy Cataclysm [crazy_cataclysm]
]

**Comment by Qrox** [comment]
Probably related to the recent addition of running animation (#65622). It uses `draw_custom_explosion` which is probably why `hang on a bit` is shown.

**Comment by Rewryte** [comment]
Qrox is right.  "Hang on a bit…" pops up when the game is waiting for an animation to finish playing.  You can speed it up a bit with the "animation delay" setting but it won't go away entirely.

For now I'll prepare another PR which will make the new animations respect animation settings so that you can disable them, but I think a proper long term solution would be to make the pop-up less intrusive or to make animations asynchronous.

**Comment by Termineitor244** [comment]
/confirmed.
