### ISSUE TITLE
Issues with new guns in #64934

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#65824]
### Describe the bug

#64934 introduced some oddities. 
- All guns were changed to have new IDs, which breaks their sprites and sound effects.
- Pretty substantial reductions to damage on most guns. AR-15 went from for example 41 damage to 36 damage with m855 ammo. This happens on the newly dropped AR-15s also. Is something wrong with barrel length calcs?
- Secubots now drop individual 5.56 rounds instead of a stanag mag.

### Attach save file

n/a

### Steps to reproduce

1. Load new experimental.
2. Spawn new guns/ammo.
3. Observe brokenness.

### Expected behavior

I really wish the guns weren't given new IDs. My character's AR-15 from their previous save still works, it still has a sprite/makes shoot/reload sound effects, but it doesn't have a "barrel" mod and has 36 damage instead of 41. New AR-15s are being spawned with an AR-15 barrel but they have only 36 damage too. So... newly spawned guns should just be the existing guns, but with barrel mods most likely, to avoid breaking peoples' soundpacks and tilesets needlessly.

Damage should probably also be the same as it used to be? They were pretty solidly calibrated before and I'm not sure why the identical length barreled guns are losing 10-15% of their damage.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.1702 (22H2)
- Game Version: e565014 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Slots [cbm_slots]
]

**Comment by DoctorBoomstick** [comment]
- The id change was required as migrations wouldn’t have worked, on account of the fact that the guns now require mods to function. As such, I was told to conduct the change to prevent old guns from breaking as it would have been considered a blocker.
- When it comes to the barrel length calculations I plugged in the newly calculated numbers which I was provided. According to the code, a weapon firing .223 from a 395mm long barrel should sit at 39 damage. The reduction is probably due to the fact that, to my knowledge, gun mods haven’t been rigged up to work with the barrel length system quite yet, though it is on the way.
- I don't know what about the changes could have prompted the secubot’s drop changes, so I’ll have to investigate that.

**Comment by carmakazi** [comment]
Seeing a couple small issues with the MDRX, so I'll throw them in this thread instead of making a new one:

-The 16" .308 conversion does not appear to convert the rifle to use AR-10 magazines, defaulting to STANAG. This would likely cause problems if spawned.
-The .300 Blackout kit description references a 20" barrel, which doesn't exist and I don't believe was intentional.

**Comment by DoctorBoomstick** [comment]
@carmakazi, Thanks for pointing out the issue with the .300 AAC Blackout kit for the MDRX. It’s meant to be a 16-inch barrel kit. With regards to the MDRX magazine compatibility, the rifle itself is capable of fitting AR10 magazines by default. I made it this way as when specifying magazine changes from the mod’s end, it caused errors to pop up when trying to spawn pre-converted .308 MDRX rifles.

**Comment by Tread4** [comment]
One more thing - "new" M16A3 (and probably other variants) rifle is having much higher recoil value than the old one (or other comparable guns [caliber, lenght, etc]) making it sub-optimal choice. Was it intentional and based in reality or just smth went wrong?

It could be that value is justified but then it calls for review of values on other guns.
