### ISSUE TITLE
SD Card / Memory Card Tweaks

### ISSUE THREAD

**Issue by Ichthysdekilt** [CleverRaven/Cataclysm-DDA#65837]
### Is your feature request related to a problem? Please describe.

There are a number of issues with how memory cards are handled today. Once read by any device, they are forever marked as read and can no longer be copied to any other device. They then become useless dead weight. This sucks when your laptop gets destroyed by water or electricity and you can't recover the hundreds of saved recipes, songs, pics, etc you had on it (I'm a bit salty). But you're still drowning in useless read memory cards.

For that matter, you cannot transfer recipes, pics, etc from a device back to a memory card. Given that memory cards have taken on the roles of USB drives, external hard drives, and so on, this should be possible.

Vaguely related, one of the failure states of reading memory cards is now the statement that the card is encrypted, which the game then treats as if it were blank. It makes sense that without any specialized tools they would be essentially worthless. However, it would be neat if you could decrypt them using perhaps a laptop and copy of hackpro.

Last and probably least, deconstructing things like smart phones results in getting a memory card, which makes some sense, but it's always pre-read. I imagine this would make more sense to generate as an unread card.

### Solution you would like.

Make the information stored on memory cards reusable / usable by multiple devices.
Make devices able to transfer their memory back to memory cards.
Make memory cards from deconstructed devices unread or contain the device's data, where applicable.
Make encrypted cards hackable using the right tools.
Consider shifting or duplicating the functionality between memory cards and USB drives.

### Describe alternatives you have considered.

Not doing those things and continuing to lose stuff and get salty.

### Additional context

Many thanks to whoever made the change to make memory cards bulk readable!

**Comment by Profugo-Barbatus** [comment]
Encryption being decryptable was made a hard fail state instead of a middleman skill state, for RSI reasons in the same update that gave us bulk reading. A worthwhile trade, IMO, hacking them was just as tedious.

As for file management/data transfer, It'd be nice but I wouldn't have it as "dump back onto memory card" when we already have the interface for device to device transfers - I'm not entirely sure what storage it looks for currently, but never found a compatible device, dunno if it even works. But its there. Good practice to bag up your recipe device and not keep it on you all the same.
