### ISSUE TITLE
Dragonsbreath rounds are ridiculous.

### ISSUE THREAD

**Issue by Daved27hundred** [CleverRaven/Cataclysm-DDA#65836]
### Is your feature request related to a problem? Please describe.

Dragonsbreath shotgun shells and by extension pyrotechnic paper cartridges behave like a flamethrower, they create a line of fire from the player to the target. This is not realistic at all.

Not only do they contain magnesium powder instead of napalm or some other chemical, Dragons breath shells aren’t even used for combat at all. They were developed to be used for remotely starting fires to contain wildfires (Google “Firebreak.”) They should at most create a small fire where you shoot them.

### Solution you would like.

Instead of their current behaviour, I propose that dragonsbreath shells create a small fire on the target location. It’s realistic to their behaviour irl and honestly much more useful and controllable.

### Describe alternatives you have considered.

Removing them entirely? I don’t support doing this but if they need to go they need to go.

**Comment by Nebnis** [comment]
I have been thinking of doing the same thing but im not sure if it is with in my skills. I believe just removing the stream from the shot will make the shells just set the target on fire rather than being a mini flamethrower

**Comment by NetSysFire** [comment]
Ping @kevingranade as one of our resident gun nuts.

**Comment by kevingranade** [comment]
If you look at videos of people using them,  they "dribble" burning magnesium all along the path. I think targeting every tile on the path is fine (though ideally skip several tiles closest to the player),  the problem is the fires are too big. This ties into a very long running feature request for a new tiny fire field to represent a fire just getting started. The new field wouldn't spread,  it would just consume fuel on its tile and grow until it turns into a regular fire field.

This would also be used if you used a lighter or other firestarter on a tile.

**Comment by tenmillimaster** [comment]
Does having them create fire fields also include removing all of their ballistic damage? I am also in favor of this.
