### ISSUE TITLE
Remove or significantly change food irradiation

### ISSUE THREAD

**Issue by fairyarmadillo** [CleverRaven/Cataclysm-DDA#65907]
### Is your feature request related to a problem? Please describe.

Irradiation in Cataclysm renders produce immune to rot forever. This is not how it works in real life.

Food irradiation in real life is a very common practice that can extend the shelf-life of foods without the use of harmful chemicals. However, once food has been irradiated, it no longer contains any ionizing radiation and continues to be an item which is made of food in a world full of hungry microbes and insects.

https://ift.onlinelibrary.wiley.com/doi/full/10.1111/1750-3841.16444#:~:text=The%20shelf%20life%20of%20tomatoes%20can%20also%20be%20increased%20through,temperature%20of%2020%C2%B0C.

This report looks at the most ideal scenario - vacuum-sealed foods. Its findings are that strawberries had their shelf life extended only by 124%, while quartered tomatoes only lasted 54% longer. In Cataclysm, irradiated food isn't even vacuum-sealed, it's just magically immune to germs forever. I'm not sure nuking a banana and then tossing it out on the shelf would really be much help.

https://pubmed.ncbi.nlm.nih.gov/9798162/

This shows that a week or two can be added to vacuum-sealed meat's shelf life, but that even before it reaches a pathogenic stage it still gets really gross pretty quickly. We don't even have irradiated meat in the game.

https://nucleus.iaea.org/sites/diif/Pages/Home.aspx

There also are, to my knowledge, only two gamma irradiation facilities located in all of New England, and I'm not sure either of them do food. Sterigenics is a company that mostly focuses on medical equipment, and their website says that at the locations which do work on food (wherever those are), they only do spices, herbs, and powdered dehydrated vegetables.

### Solution you would like.

The best and fastest way to go is probably to simply obsolete all irradiated food items and make the plant nonfunctional. It's the apocalypse, we don't generally let the player run high-tech industrial equipment which normally takes teams of experts and a lot of electricity, this one exception doesn't make a ton of sense. Pre-Cataclysm irradiated foods would logically exist at game start, but given that the shelf-life extension is not actually all that high, it's probably not worth modeling, especially since for it to really work properly, the player would need to have frozen and vacuum-sealed their food before running it through the chamber, and if they have a freezer and a vacuum-sealer, they definitely don't need irradiated food.

Given that these facilities are vanishingly rare and there might not even be any in New England, it might be best to just remove the plant as well.

### Describe alternatives you have considered.

A more long-term solution, which could be implemented later after the above suggestion was done, might be to have a quest where you get the place staffed and running. The exodii or hub 01 might have the technical expertise to run this location, and could even fight over it, but really it just doesn't seem logical to me - there are far more pressing concerns in the apocalypse, like water, sanitation, medicine, and short-term food security, and long-term food security is much more efficiently handled with pre-atomic methods.

**Comment by sadenar** [comment]
Well I guess that my gripe with irradiated apricots in my latest typo hunt will be rendered moot if this goes through :D #65911

**Comment by anoobindisguise** [comment]
Vac seal only provides 50% spoilage reduction. Rather than convert food to irradiated varieties, the plant could instead change vac sealed bags into ones with a higher spoilags factor, like 90-95%.

**Comment by fairyarmadillo** [comment]
That doesn't sound worthwhile, especially when there aren't irradiation planta in New England, the power's out, and the player isn't an irradiation plant specialist with a team of workers.

**Comment by anoobindisguise** [comment]
This should be reopened as it is still an issue.

**Comment by alexanderglasco-ui** [comment]
The paper linked on beef shelf life actually refutes the point made by OP if you read the article rather than skim the abstract.

In addition, irradiation facilities are not huge, complex monstrosities that require teams of workers. The real truth is that *radiation* is not magic. They have a cobalt-60 source which just *sits there* and you put target material next to it, and that's... it. You can even put it into a trailer.

The article linked is specifically targeting *low* doses of radiation, because people in the 90s were still scared silly of 'evil rays' but higher dosages *can* completely sterilize foods, if done, *as the article mentions*, not in oxygen-permeable bags. https://en.wikipedia.org/wiki/Food_irradiation 

Let's not cherry pick 'research' we don't understand to support our whims - *not* completely sterilizing food with radiation is a political game entitled Euro-American countries play where food security is a given, where corporations with a vested interest in continuing food waste stoke idiotic public fear of a completely safe process. Have you ever wondered why your spices never seem to rot, only lose 'freshness'? This is not how they work in real life. Drying is not sorcery. But people care less about irradiating food that isn't 'squishy', and so *regulations* allow for higher dose irradiation of those foodstuffs. Countries with less food security, like Brazil, have approved larger doses of ionizing radiation in their meats for decades.

**Comment by worm-girl** [comment]
This is a three year old closed issue which is no longer relevant as changes have long since been made to the system it was discussing. If you think something is wrong with how the game currently handles irradiation, you should probably make a new issue or pull request instead of arguing with ghosts in a dead thread.
