### ISSUE TITLE
Wind and water mills don't work

### ISSUE THREAD

**Issue by fairyarmadillo** [CleverRaven/Cataclysm-DDA#65960]
### Describe the bug

Attempting to place any millable object in a water or wind mill via its iexamine results in nothing happening. The grain does not leave your inventory, the mill does not get anything put into it, nothing gets milled.

### Attach save file

N/A

### Steps to reproduce

Build a water or wind mill in a place where it can work.
Get some millable stuff in your inventory.
(e)xamine the mill.
Choose something to go into it.
Nothing happens.

### Expected behavior

The items should go into the mill.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2965 (22H2)
- Game Version: f9caeb7 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

The version info above is a bit outdated. This bug still exists in a version from like six hours ago but my game is compiling so I can't get the copy+paste from there right now. Yes I did test it in both.

**Comment by SurFlurer** [comment]
Cannot reproduce on https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2023-06-02-2119.

I spawned 20 oats, `e`xamine the windmill, "Insert products...", and the oats correctly went into the windmill.

**Comment by fairyarmadillo** [comment]
> Cannot reproduce on https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2023-06-02-2119.
> 
> I spawned 20 oats, `e`xamine the windmill, "Insert products...", and the oats correctly went into the windmill.

Thank you for checking. I took another look and discovered that there is an existing issue with mills where you have to be holding the seeds in order to insert them. If any are at your feet, you'll be able to select them from the prompt, but nothing will happen when you choose them.

Closing this as not a bug, just something that is a bit unclear.

**Comment by evankimori** [comment]
Sorry for commenting on this post-close but I didn't want to make a bug ticket if this issue is already addressed as it may be related.

There is a 'no production issue when the Wind Mill takes input of Roasted Hickory Nuts but no matter how many are inserted: nothing is produced. I am aware of the recipe for Nut Paste > Cooking Oil via other appliances with the Oil Press etc but this option is available for the Wind Mill but my issue is more that the option is there but no production.

Was there a plan to implement Nut Paste production via the WM and is incomplete(?)
