### ISSUE TITLE
Make Stimulants Temporarily Relieve Weariness

### ISSUE THREAD

**Issue by Ichthysdekilt** [CleverRaven/Cataclysm-DDA#66043]
### Is your feature request related to a problem? Please describe.

Currently stimulants only seem to affect rest/tiredness. However, in real life, a gallon of coffee or a bump will cause that weariness to, at least temporarily, go away. Even if it comes back worse afterwards.

### Solution you would like.

Modify stimulants to reduce weariness as well as tiredness. Potentially add in an extra slam of weariness after the stimulants wear off, if you're feeling sadistic.

### Describe alternatives you have considered.

I'm gonna be honest and say that stimulants are basically useless to me as is. My alternative has just been to avoid them altogether.

### Additional context

To borrow from DF, testing these mechanics IRL can be !!FUN!! (extremely hazardous to your health. Please do not use nose candy to test this request... unless you were going to otherwise. I'm not a cop.)

**Comment by martosss** [comment]
I agree, stimulants need more love. I just opened an issue about stimulants and sleep deprivation, whose basic morbid effect isn't affected from stimulants at all. But it makes sense to be, at least to some extent. 

Same goes for weariness. Note that weariness measures how exhausted physically you are from activity, so if you've been lifting weights for 1 hour, drinking coffee might help slightly, but not as much as... for example eating a chocolate bar would? (consuming fast food in game) ... So that might be a way to make fast food a bit more appealing, even though it's detrimental for you in the long run, in addition to stimulants also helping slightly(with diminishing return).

I'm not sure how it can be balanced,though. We dont'want to be able to lift mountains and cross oceans on just non-stop coffee drinking there has to be some mechanic that exhausts you beyond stim.

Maybe making stim have a "perceived" effect on weariness similarly to deprived sleep migt help?
As in every point of stim would improve your perceived weariness by ...0.5-1%?
But if you keep running and drinking coffee you'd go in overdose from stimulants... and keep getting more and more tired to where coffee would hurt you. And then stim would wear out ... and you'd feel even worse because that extra bump of freshness is gone.

**Comment by fairyarmadillo** [comment]
If stimulants had an effect on the action speed penalty but did nothing to affect weariness buildup, they'd be a useful double-edged sword.
