### ISSUE TITLE
Dodging skill should lower the stamina cost of dodging

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#66050]
### Is your feature request related to a problem? Please describe.

Currently dodging always takes 6 * BASE_BURN_RATE stamina as of #64224. However more skilled dodgers should be able to avoid overcommitting and making more precise motions which avoid attacks while expending less energy.

### Solution you would like.

Dodging skill should reduce stamina costs. for example the formula could be (8 * base_burn_rate) / (1 + dodge skill) 
this would be the BASE dodge skill, not the modifiers it gained from dexterity, mutations, etc.

**Comment by martosss** [comment]
This sounds reasonable, if you watch some martial arts movies or train, they teach you how to move more efficiently, expending less energy for each action, so this is perfectly reasonable.
Maybe the formula can be tweaked a bit to give 1-3% dodge bonus instead, making it (8* base_burn) * (1-(dodge_skill)*0.01).

How efficient is a skilled dodger(dodging 7-10)? 10%? 25%?

However, here's a counter argument - it might depend on the skill of your attacker, since to dodge more skilled hits would require more energy, so... a skilled attacker should drain your dodging stamina faster.... tricky...

In general I'd say a small flat bonus to dodging stamina makes sense as a first step - the more you fight, the better you get at all aspects of it, including stamina cost.

**Comment by fairyarmadillo** [comment]
If it was based on the skill of the attacker it would be confusing for the player, as they'd get unexpected results in combat, especially since you're often fighting multiple enemies and you can't tell what anything's melee skill is anyway. Your logic makes sense, but it would feel inconsistent and unfair.

If you watch martial arts and boxing videos, good fighters seem to be capable of evading strikes with very minor movements, so I would think the stamina reduction should be significant, like at least 25% at 10 skill, maybe more.

https://www.youtube.com/watch?v=Sk6nSJ2NJLo Here's a video of the first Muhammad Ali vs Joe Frazier match. This fight went on for fifteen rounds. Each round is three minutes with a one minute rest between. You can see them getting visibly exhausted toward the end, but both fighters are able to keep swinging and dodging for most of the match. This of course would not even be close to possible for an average person.

**Comment by PatrikLundell** [comment]
I don't think the attacker skill should affect the defender's dodge efficiency by much if anything. The result would instead be a higher dodge failure rate (expended energy without any benefit, apart from possibly a degradation of the severity of the hit) as the attacker gets more skilled.

**Comment by martosss** [comment]
> 

OK, good point, I agree. You can't push yourself more than the maximum possible. If you're more skilled you do your best regardless of your opponent, and if the opponent is skilled he just hits you in the face in spite of all your hard efforts.
