### ISSUE TITLE
Bombastic Perks feedback and suggestions

### ISSUE THREAD

**Issue by Ranik-Ortega** [CleverRaven/Cataclysm-DDA#66077]
### Is your feature request related to a problem? Please describe.

I've been playing a good bit the past week with @bombasticSlacks  perk mod and I wanted to create this Feature Request for feedback. Currently CDDA has various progression options. Vanilla game options then Stats through Kills / Skills as additional layers. Bombastic Perks has added a pseudo DnD Feat system or Fallout Perk system. The perk selection so far is a bit limited in variety but are fun choices none the less. I have some suggestions I'd like to provide.

1.Recommended settings: While it's not your responsibility to determine compatibility, what settings are you designing within mind. Vanilla + Bombastic? Vanilla + Stats on Skills + Bombastic? etc etc Some clarification for "recommended settings" in file readme during mod selection would help.  

2. Alternative means of getting XP. Currently the only means of getting XP seems to be killing zombies. It would be interesting to add additional means of gaining XP. Finishing quests, Gaining Skill points, Reaching many different "Unique Locations" etc etc.  

3. Already existing Traits: Some already existing traits makes sense to be addable by Perks. Using the Fallout Comparison, you have starting traits then traits you develop over time. You already have Bloody mess which is straight out of Fallout. However in CDDA a lot of the perks that are only easily acquirable at character creation could be considered candidates for adding over time. Some traits could be easily acquirable while others could be gated behind requirements. EX: Bookworm: Require X many books read. Costs 2 points. This seems like a low hanging fruit to really flesh out the mod. 

4.  Mixed Perks: Some perks that have upsides and downsides. It feels like CDDA doesn't have enough "Trade off" traits or perks.

5. Additional stages of Stat perks . EX: Stronger 2. 2 points, Requires Stronger 1.  // Stronger 3: 4 Points. Requires Stronger 2. At least up to level two. Maybe up to 4 if somebody wants to throw their entire character development into one stat at the cost of everything else. 

6.  Wild Cataclysm: Unique perk for integrating bizarre spawns or map extras / locations. Essentially the CDDA version of Wild Wasteland from Fallout. Recently a lot of weird creatures and elements have gotten retired in commits. This may be an interesting way to bring them back and make the Cataclysm a bit Wilder.

I'll probably try to think of actual perks that could be implemented when I have more time. 

### Solution you would like.

Read above.

**Comment by CatWithFourEyes** [comment]
Small question, can stat boosting perks work like Stats through S/Kills? Without highlighting stat, like artifacts do?

**Comment by bombasticSlacks** [comment]
> Small question, can stat boosting perks work like Stats through S/Kills? Without highlighting stat, like artifacts do?

I don't think so because the goal is to move everything to the artifact system. So, even if we could, I wouldn't be happy with the implementation. Basically the way mutations currently do it is hard coded and only for them. If there is an issue with the way artifacts do it then we should fix that since that is what modders generally have access to.

**Comment by bombasticSlacks** [comment]
> I can understand https://github.com/CleverRaven/Cataclysm-DDA/pull/3 No vanilla traits but can I ask why no multi point perks? Same for https://github.com/CleverRaven/Cataclysm-DDA/pull/5 and at least having a Stronger 2 if not 3 / 4.

Because it's confusing for a player to have unexpected variable costs. Like I said if you want to have variable cost perks you can make your own mod that extends BombasticPerks. 

As for huge stat ups, they are too good to be lifestyle perks, too boring to be playstyle perks.

> And https://github.com/CleverRaven/Cataclysm-DDA/pull/6 was an idea as to how to re-merge those crazy ideas that people have been retiring. To basically put them back in game since they already existed.

You can just add them directly to Crazy Cata. Making people spend a perk point to get a bunch of extra content seems mean. It also means none of that content will be in the 3 OMs near you since they will have already genned.

**Comment by Zireael07** [comment]
Hint: don't use # to list things, as you create unwanted links to old issues/PRs

**Comment by estebandellasilva** [comment]
Dunno if this would be a better CBM but since CBM are mostly exodii stuff i thought it maybe could fit here

A Perk that grants you  a cashcard which is installed in your body ... so you dont have to carry it around (similar to the holdout pocket)

The only thing i am unsure if its actually worth 1 whole point if you compare it to other perks ...

**Comment by bombasticSlacks** [comment]
I believe in vanilla the plan is to remove cash cards entirely and make vending machines only open with crowbar or baseball bat currency.

**Comment by estebandellasilva** [comment]
ah the good old ... "lockpicking" the question is when its going to be removed?
