### ISSUE TITLE
faction_owner lacks documentation

### ISSUE THREAD

**Issue by Procyonae** [CleverRaven/Cataclysm-DDA#66113]
### Is your feature request related to a problem? Please describe.

faction_owner lacks documentation

### Solution you would like.

faction_owner to have documentation, I'm just messing with rooves atm so I've no idea if similar things are missing too

### Describe alternatives you have considered.

Not being lazy, working it out and adding it myself

**Comment by PatrikLundell** [comment]
I don't know what a roove is, although I suspect you're actually referring to roofs and try to apply the leaf -> leaves pluralification rule rather than the standard proof -> proofs pattern (or try to be funny, which doesn't work well on this medium which doesn't convey the tone and where many people doesn't have English as their native language and so are prone to get things wrong, as English is a linguistic train wreck).

**Comment by Procyonae** [comment]
I've literally been born and raised in England I'm just crazy ;D I blame it on the horse stuff I've been doing making my brain go hoof -> hooves so roof -> rooves?

**Comment by PatrikLundell** [comment]
I'd rather say temporarily a bit confused, rather than crazy...

English is a mess. I personally make use of the multiple rules to say (or rather, write) dwarf -> dwarfs when talking about humans subjected to dwarfism and dwarf -> dwarves when referring to members of a fantasy race. I don't think that distinction has any official sanction, though.

**Comment by Procyonae** [comment]
Someone did this at some point yay
