### ISSUE TITLE
"Not enough food stored" when trying to upgrade radio tower basecamp

### ISSUE THREAD

**Issue by kholat** [CleverRaven/Cataclysm-DDA#66144]
### Describe the bug

When trying to do the wooden shack upgrade, despite having enough food the game tells me I do not have enough food stored for the task, but I supposedly have 22 days of calories while the building requires 4 days.

### Attach save file

[Fiskdale-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11725105/Fiskdale-trimmed.tar.gz)

### Steps to reproduce

1. Make a basecamp at a radio station, the version without a building next to the tower.
2. get resources for the wooden shack upgrade
3. get enough food to supposedly do the task
4. get a companion to do the task
5. error for not enough food pops up despite having enough food

### Expected behavior

Should be doable.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2965 (21H2)
- Game Version: ec7537a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Magiclysm [magiclysm],
    No Hope [no_hope],
    No Rail Stations [No_Rail_Stations],
    Bionic Slots [cbm_slots],
    Xedra Evolved [xedra_evolved],
    <color_cyan>Arcana and Magic Items</color> [Arcana],
    <color_cyan>Arcana</color>/Magiclysm Patchmod [Arcana_Magiclysm_Patch]
]

### Additional context

N/A

**Comment by TheEskir** [comment]
I have the same problem with the basic farm shack for the modular field camp, it's just the shack too, I already built the 2nd room upgrade/advanced shed since it would actually let me do that

**Comment by RenechCDDA** [comment]
Confirming this. It's due to the exertion calculations added in #65705.

Because of the way camps work, such *construction* is actually stored as json "recipes" under the hood.

https://github.com/CleverRaven/Cataclysm-DDA/blob/3f9a827fa99838594ad044ca6a8869bfd190dc1d/data/json/recipes/basecamps/base/fbmc_radio_tower/recipe_modular_radio_tower_wood.json#L17-L19

The code doesn't really know how to handle that:

https://github.com/CleverRaven/Cataclysm-DDA/blob/3f9a827fa99838594ad044ca6a8869bfd190dc1d/src/faction_camp.cpp#L4801-L4803

Not sure how it's getting "4 days" either, it should be 40 hours according to the json. Could be related to the mandatory 'break period' for long duration projects.

In any case, what needs to happen is for the UI portion to calculate the calories for you, and tell you exactly how many you need. (and ideally, but out of scope for fixing this, the crafting should take a variable exercise level instead of defaulting to MODERATE_EXERCISE)

**Comment by kholat** [comment]
A tangent question not related to solving the issue but is there a way to kinda "shoehorn it" now as is, somehow, so i can continue the game? Want to try more basecamp and other things but this is... well its totally preventing it. Would it pass the check if i just store a bajillion calories or something?

**Comment by RenechCDDA** [comment]
Yes, the shack upgrade requires 60k and you're at 57k so you only need a bit more.

**Comment by kholat** [comment]
Wow thanks a lot sir! (am very bad at c++)
