### ISSUE TITLE
Pharmacies have too few drugs

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#66176]
### Is your feature request related to a problem? Please describe.

Currently pharmacies spawn drugs 10 per bottle, with 1-3 bottles per shelf in most cases. IRL pharmacies have shelves lined with hundreds of pill bottles and those bottles typically have a couple hundred pills per bottle, both for their "behind counter" prescription drugs and their OTC drugs (have you ever found a multivitamin bottle being sold with only ten vitamin pills in it? or an aspirin container that had 10 aspirins?) 

### Solution you would like.

Drugs should spawn in more realistic quantities. 

### Describe alternatives you have considered.

If balance is a concern (the player can get hundreds or thousands of useful drugs like stimulants, painkillers, vitamins and antibiotics from one store) then "looted" variants could be introduced as pharmacies would potentially be high value targets for rioters, though whether drugs were more valuable than guns and food is debatable.

**Comment by fairyarmadillo** [comment]
Drugs would absolutely be high value targets because they already are in real life. They go to great lengths to safeguard their narcotics and high-value drugs, and in a situation where people were comfortable rioting to steal things, they would not limit themselves to things that they thought they needed. And really this argument applies to every single store in the game. Who ever heard of a clothing store with five pairs of pants in it? It should have dozens, hundreds for department stores, to say nothing of every other kind of garment. A single gas station should have like a year's worth of chips and soda in it.

Selectively applying the argument is going to lead to weird results. Either pharmacies will be so bonkers that players will never want for anything, or they'll wind up like grocery stores where you can actually be reasonably assured that they won't have _any_ food in them because something like 91% of all grocery stores are looted, meaning there's less food in grocery stores than anywhere else. And then why is it only milsurp, grocery stores, and pharmacies that people went after?

I think the game needs a more comprehensive way to apply riot damage and looted items to locations that doesn't require every map to have looted variants, otherwise it's going to be uneven and weird like that. I don't think store inventories should be buffed until that happens, but at that point you could buff all of them.

**Comment by Procyonae** [comment]
You can parameterise nests so you could have looted/unlooted shelf nests etc, it's fairly unused currently but here's a current example of it saving a huge amount of lines on basecamp stuff (look at the files with additions) https://github.com/CleverRaven/Cataclysm-DDA/pull/66240/files
