### ISSUE TITLE
Infrastructure for split coverage between materials on a single (sub)bodypart

### ISSUE THREAD

**Issue by randomtyper** [CleverRaven/Cataclysm-DDA#66184]
### Is your feature request related to a problem? Please describe.

So, there is a thing with plate armor IRL. It rarely, if ever had chain mail that was under main armor and not only covering weakspots. The CDDA plate armors, though, do. Because you can't make it so "the 80% of this body part is covered in 2 mm solid steel, and other 20%  - in chain mail" in the current state of the game. The subparts help only with heavily segmented body parts. But with something like examples from this article: https://en.wikipedia.org/wiki/Mail_and_plate_armour Not really.

This will allow to change the chain mail's protective qualities to be more realistic without hurting the performance of the armors that use both plate and chainmail. Currently chain is essentially equal to the solid plate armor in all aspects per mm. IRL, though, there was a reason why chain was pretty rapidly replaced by brigandines and then solid plate armor. I will just link this test: https://www.youtube.com/watch?v=NGSL7XApz2s Yeah... And that is quality riveted mail. I won't even talk about the butted mail. Essentially, the only things a mail would protect you well from are slice and somewhat blunt. Good stab? Gets into a ring, can split one and go through. Bullet? Slams into a ring, splits, gets through, occasionally pulls some rings with it into the wound, dealing injuries that could be less severe without mail (if you have padding, though, you could hope the split bullet is easier to stop for the padding).

Finally, there is a small request: a high end plate armor that is made to cover the body fully with steel plate only (of varying thickness could be reasonable), like this one: https://collections.royalarmouries.org/object/rac-object-19 Possibly make it take about 1.2-1.5 more time to craft than the tempered steel plate armor with chain weakspot coverings. Just as that pinnacle of pinnacles of armor.

### Solution you would like.

Ability to not only layer the materials, but to split the coverage of body parts between materials. So it is possible for the thick parts to use the most protective materials, and only the weakspots use the weak, but flexible materials. Just as how it was done with some IRL armors.

Then, adjust armors that use both the chainmail and solid plate to only use mail in the gaps and solid plate as main armor.

Then, nerf chainmail to its realistic values (negligible ballistic, "weak, but still better than cloth" stab, passable blunt and solid slash resistances).

### Describe alternatives you have considered.

Make plate armors use no chain mail, instead opting for exposed weakspots or covering them with solid plate of smaller than normal thickness (it was done IRL, see Henry VIII's foot combat armor, I am pretty sure something like that could be practical).

Doing more PRs and ignoring interesting mechanics to be implemented.

### Additional context

None.

**Comment by randomtyper** [comment]
@Drew4484, what do you think?

**Comment by Drew4484** [comment]
> ### Is your feature request related to a problem? Please describe.
> 
> So, there is a thing with plate armor IRL. It rarely, if ever had chain mail that was under main armor and not covering weakspots. The CDDA plate armors, though, do. Because you can't make it so "the 80% of this body part is covered in 2 mm solid steel, and other 20%  - in chain mail" in the current state of the game. The subparts help only with heavily segmented body parts. But with something like examples from this article: https://en.wikipedia.org/wiki/Mail_and_plate_armour Not really.
> 
> This will allow to change the chain mail's protective qualities to be more realistic without hurting the performance of the armors that use both plate and chainmail. Currently chain is essentially equal to the solid plate armor in all aspects per mm. IRL, though, there was a reason why chain was pretty rapidly replaced by brigandines and then solid plate armor. I will just link this test: https://www.youtube.com/watch?v=NGSL7XApz2s Yeah... And that is quality riveted mail. I won't even talk about the butted mail. Essentially, the only things a mail would protect you well from are slice and somewhat blunt. Good stab? Gets into a ring, can split one and go through. Bullet? Slams into a ring, splits, gets through, occasionally pulls some rings with it into the wound, dealing injuries that could be less severe without mail (if you have padding, though, you could hope the split bullet is easier to stop for the padding).
> 
> Finally, there is a small request: a high end plate armor that is made to cover the body fully with steel plate only (of varying thickness could be reasonable), like this one: https://collections.royalarmouries.org/object/rac-object-19 Possibly make it take about 1.2-1.5 more time to craft than the tempered steel plate armor with chain weakspot coverings. Just as that pinnacle of pinnacles of armor.
> 
> ### Solution you would like.
> 
> Ability to not only layer the materials, but to split the coverage of body parts between materials. So it is possible for the thick parts to use the most protective materials, and only the weakspots use the weak, but flexible materials. Just as how it was done with some IRL armors.
> 
> Then, adjust armors that use both the chainmail and solid plate to only use mail in the gaps and solid plate as main armor.
> 
> Then, nerf chainmail to its realistic values (negligible ballistic, "weak, but still better than cloth" stab, passable blunt and solid slash resistances).
> 
> ### Describe alternatives you have considered.
> 
> Make plate armors use no chain mail, instead opting for exposed weakspots or covering them with solid plate of smaller than normal thickness (it was done IRL, see Henry VIII's foot combat armor, I am pretty sure something like that could be practical).
> 
> Doing more PRs and ignoring interesting mechanics to be implemented.
> 
> ### Additional context
> 
> None.

- Chainmail under plate
Currently the only difference between chain and plate is the RIGID/FLEXIBLE, defensively it is identical point for point with solid steel. We'd like to have absorbed damage convert to bash, but that's an idea not a WIP. 
- Sublocations
Right now this system uses the detailed armor layers but doesn't truly represent plate armor. The next version I'm going to be working on will require an underlayer to attach plates (and chain) to, so you'll have more individual pieces and can minmax your coverage over the sublocations.
- Chainmail types
The in-game chainmail is meant to represent 1.2mm welded rings in a four in one arrangement, instead of more historically accurate but weaker butted or riveted ring. This is in part to keep the strength comparable to the solid plate, and isn't well represented by the crafting. ideally we would have an alternative crafting recipe for the sheets that uses an arc welder but that's a *lot* of recipe work. I'd like to add six in one as well but the same recipe work would be needed. 
- Full full plate 
The armor you linked to is an excellent piece, masterful design, but not suitable for regular use. It's an example of 'Tournament Armor', which was typically much heavier (this example is 94lbs) than our current heavy set (approximately 55lbs not including helmet, gauntlets, or any foot protection). Tournament armor would be used for events like jousting (nobody wanted to risk getting killed for a game) or a tournament melee, which was real combat with (typically) blunt weapons. The additional weight, loss of mobility (in suits not made for a king by the finest crafters), and even loss of vision (see the frogmouth helm for an example) was acceptable for a tournament especially as participants did not have to stay in the hot armor for long, nor did the horses have to carry them far in the joust. A set like this would minimize encumbrance but one of the advantages of the chainmail is it allows some additional flexibility around the joints.

It is entirely possible to recreate this kind of armor, but it would be even hotter, nearly twice as heavy, and add even more crafting time. If you want to take and of this on, I'd be happy to help you, just let me know by tagging me in a PR or on Discord.

**Comment by randomtyper** [comment]
>   Right now this system uses the detailed armor layers but doesn't truly represent plate armor. The next version I'm going to be working on will require an underlayer to attach plates (and chain) to, so you'll have more individual pieces and can minmax your coverage over the sublocations.

I think we are misunderstanding eachother a bit. Yes, minmaxing coverage by adding individual plates and chain would be nice, but what I was talking about is allowing for splitting the protection percentages on a specific subpart, so there is no need to always make a 100% covering chainmail layer and instead it is possible to make, say, a piece with 2 mm solid steel that covers 95% of area and only remaining 5% is covered by mail. Instead of 0.8 mm steel on 95% and 1.2 mm chain on 100%. The difference would be much greater with more differing materials, of course.

>   The in-game chainmail is meant to represent 1.2mm welded rings in a four in one arrangement, instead of more historically accurate but weaker butted or riveted ring. This is in part to keep the strength comparable to the solid plate, and isn't well represented by the crafting. ideally we would have an alternative crafting recipe for the sheets that uses an arc welder but that's a _lot_ of recipe work. I'd like to add six in one as well but the same recipe work would be needed.

The thing is that even if chain is welded one, the problem with bullets still stands. Steel plate may ricochet or take on the damage with its structure. At least it will not deform the bullet in a way that encourages fragmentation. But even the best chain will have gaps (unless... this is what you have in mind: ). And even if it is strong enough to withstand bullet head on, the bullet can deform, being of softer material, split on rings and essentially pierce. Be the chain riveted, welded or butted. I would love to link an experimental source, but all videos I have seen either use dollar store butted chain (and we both know it is not representative of good chain) or entirely another type of armor, like lamellar. Or entirely another weapon, like bow and crossbow.

**Comment by randomtyper** [comment]
> * Full full plate
>   The armor you linked to is an excellent piece, masterful design, but not suitable for regular use. It's an example of 'Tournament Armor', which was typically much heavier (this example is 94lbs) than our current heavy set (approximately 55lbs not including helmet, gauntlets, or any foot protection). Tournament armor would be used for events like jousting (nobody wanted to risk getting killed for a game) or a tournament melee, which was real combat with (typically) blunt weapons. The additional weight, loss of mobility (in suits not made for a king by the finest crafters), and even loss of vision (see the frogmouth helm for an example) was acceptable for a tournament especially as participants did not have to stay in the hot armor for long, nor did the horses have to carry them far in the joust. A set like this would minimize encumbrance but one of the advantages of the chainmail is it allows some additional flexibility around the joints.
> 
> It is entirely possible to recreate this kind of armor, but it would be even hotter, nearly twice as heavy, and add even more crafting time. If you want to take and of this on, I'd be happy to help you, just let me know by tagging me in a PR or on Discord.

I kinda need the thicknesses values for that, I guess. Of course, I can guesstimate those based on weight of full set of heavy armor with sabatons, full gauntlets and with thick close helm I am adding with a PR right now. That would result in about 1.5x possible thickness increase, most likely, but I will try to get less approximate numbers through testing. The armor is supposed to be custom anyways. And I will also likely add a lightened full full plate, not of tourney protection standard, but battle-worthy, with thicknesses closer to the more common plate armor.

**Comment by Drew4484** [comment]
> > Right now this system uses the detailed armor layers but doesn't truly represent plate armor. The next version I'm going to be working on will require an underlayer to attach plates (and chain) to, so you'll have more individual pieces and can minmax your coverage over the sublocations.
> 
> I think we are misunderstanding eachother a bit. Yes, minmaxing coverage by adding individual plates and chain would be nice, but what I was talking about is allowing for splitting the protection percentages on a specific subpart, so there is no need to always make a 100% covering chainmail layer and instead it is possible to make, say, a piece with 2 mm solid steel that covers 95% of area and only remaining 5% is covered by mail. Instead of 0.8 mm steel on 95% and 1.2 mm chain on 100%. The difference would be much greater with more differing materials, of course.
> 
> > The in-game chainmail is meant to represent 1.2mm welded rings in a four in one arrangement, instead of more historically accurate but weaker butted or riveted ring. This is in part to keep the strength comparable to the solid plate, and isn't well represented by the crafting. ideally we would have an alternative crafting recipe for the sheets that uses an arc welder but that's a _lot_ of recipe work. I'd like to add six in one as well but the same recipe work would be needed.
> 
> The thing is that even if chain is welded one, the problem with bullets still stands. Steel plate may ricochet or take on the damage with its structure. At least it will not deform the bullet in a way that encourages fragmentation. But even the best chain will have gaps (unless... this is what you have in mind: https://www.pinterest.com/pin/431853051761762697/). And even if it is strong enough to withstand bullet head on, the bullet can deform, being of softer material, split on rings and essentially pierce. Be the chain riveted, welded or butted. I would love to link an experimental source, but all videos I have seen either use dollar store butted chain (and we both know it is not representative of good chain) or entirely another type of armor, like lamellar. Or entirely another weapon, like bow and crossbow.

Additive coverage would be nice, the chain/plate used now is a bit hacky. That might look like material layers using an array, but I'm not the person to ask about that kind of infrastructure. @bombasticSlacks, any thoughts?

Bullet on chain is definitely an issue. A bullet passing cleanly through a ring is effectively a non-issue, the inner diameter of the rings is just barely larger than a 5.56 bullet and even a loose chain pattern would still have multiple obstructing rings inside that diameter, so the bullet will always hit *something*, I would expect contact on at least two rings with three being more likely or all five with larger rounds like ,45 and .308.  If the individual ring holds, it would shed energy to other rings and into the wearer (who is hopefully wearing a padded underlayer) like any other attack, but obviously a ring isn't going to withstand as much force as a slab. If a ring or rings did break, they would still have absorbed a lot of the round's energy, but leave nasty spalling wounds if the underlayer was absent or insufficiently thick. Historically this was an issue with poorly made chainmail, links would be pushed into the skin or break and cause penetrating wounds but the multiple supporting rings would typically hold it relatively close especially with tighter patterns. Lamellar performed much better against ballistic attacks to the point of being used as armor during WWI, so it's definitely possible for a flexible armor to retain some effectiveness against ballistics. Ultimately I think this falls to the 'ballistics to bash' damage conversion we'd like to have. Rather than model individual rings breaking, we could just have a larger amount of damage convert to bashing on flexible armors.

For the implementation of plate armor, the book "The Knight and the Blast Furance" (Alan Williams) was an excellent resource. In it, Williams provides measurements of the thickest point on breastplates for both mounted and infantry troops. These range from late 15th century to late 17th century and are sampled from multiple collections of armor. The lightest were ~2mm and for the most part, the thickest were ~6mm. There are a few heavier examples including a truly massive 8mm plate for a mounted knight made in 1575, so most likely this outlier was an attempt to keep up with improving firearms. In another work, "Bullet Dents - 'Proof Marks' or Battle Damage" (Williams, Edge, Atkins), the following example is used (from a similarly thick piece as mentioned above) 
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/57647637/32f705bf-6865-46e2-9b89-67936c7493ab). The total weight of this breast and backplate is a hefty 21.5kg, 4kg heavier than our chestplate. Limb pieces would be thinner to maintain mobility but even so some very back of the napkin math says that an 8mm plate would be upwards of 32 kilograms when proportionate weight increases across the entire suit are included.

**Comment by randomtyper** [comment]
> For the implementation of plate armor, the book "The Knight and the Blast Furance" (Alan Williams) was an excellent resource. In it, Williams provides measurements of the thickest point on breastplates for both mounted and infantry troops. These range from late 15th century to late 17th century and are sampled from multiple collections of armor. The lightest were ~2mm and for the most part, the thickest were ~6mm. There are a few heavier examples including a truly massive 8mm plate for a mounted knight made in 1575, so most likely this outlier was an attempt to keep up with improving firearms. In another work, "Bullet Dents - 'Proof Marks' or Battle Damage" (Williams, Edge, Atkins), the following example is used (from a similarly thick piece as mentioned above) ![image](https://user-images.githubusercontent.com/57647637/245877696-32f705bf-6865-46e2-9b89-67936c7493ab.png). The total weight of this breast and backplate is a hefty 21.5kg, 4kg heavier than our chestplate. Limb pieces would be thinner to maintain mobility but even so some very back of the napkin math says that an 8mm plate would be upwards of 32 kilograms when proportionate weight increases across the entire suit are included.

I guess foot tourney armor (especially made for a king) would focus more on limb protection, rather than stopping bullets with chestplate, so going full napkin math... 6 mm chestplate with plate gap covers would be about 18-18.5 kg, 2.75 mm extremity armor with plate gap covers would be about 5-5.5 kg (for 20-22 in total), add in plate gauntlets of 2.75 mm thickness (another 1.5-2 kg) and sabatons (2-3 kg). Add in a very heavy helm about 5.7 kg weight... Total weight rolls into 47.2-51.2 kg. Even a bit heavier than Henry's armor. Maybe its chestplate wasn't as thick. A lightened version should be possible. Less maximum protection than combat plate (against threats like bullets), but better protection against weak enemies that could still pierce the weakpoints on the combat plate.

Alternatively, I could just make "full full plate" versions for every plate armor piece. Increase in encumbrance, small increase in weight (thick chain can be heavier than plate that provides similar protection), increase in work times.

Or do both, adding a new superheavy thickness class and "full full plate" armor variants.

Btw, maybe rename mitten gauntlets into just plate gauntlets? Wool mittens have very high encumbrance in game and it is hard to operate weapons like guns in plate mittens, especially if they are covered in chain from inner side. And maybe make it so hand_back and hand_wrist are only covered in monolithic plate, not in combo of mail under steel (both have 100% coverage of subparts anyways).

**Comment by Drew4484** [comment]
The chainmail is more than enough protection against basic zombies, I'm not sure what threat level you're aiming for full protection against. Adding tournament plate sets is an option, but they should be a real pain in the ass to wear and I don't want to add gear that will punish players who invest the time and materials into crafting something that isn't very useful.

 I would say any piece attempting to replace chain with solid metal would be a 10 skill requirement.

Perfectly fine to add variant pieces, the way the armor system is set up there's no downside to wearing each piece independently, so you could use heavier leg protection and lighter arm guards, or even per-side splits since the limb armors are crafted individually. 

Mitten and demi gauntlets are named for specific pieces of gear, the mitten gauntlet has a full articulated plate over the fingers. This encumbers the wearer a bit more but offers excellent protection to the hand and also makes the arm into a very effective club. 
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/57647637/9794d977-05b9-45a2-accf-01c56a18c75e)

The full suit weights are probably my oversight during the initial creation, the higher numbers should be used.

**Comment by Drew4484** [comment]
> > Mitten and demi gauntlets are named for specific pieces of gear, the mitten gauntlet has a full articulated plate over the fingers. This encumbers the wearer a bit more but offers excellent protection to the hand and also makes the arm into a very effective club. ![image](https://user-images.githubusercontent.com/57647637/245963072-9794d977-05b9-45a2-accf-01c56a18c75e.png)
> 
> Not really sure you are reading my comments properly. For gauntlets, I said that renaming the current mitten gauntlets to finger/glove/just gauntlets would be realistic, because actual mitten gauntlets would be very unwieldy, especially if one uses a gun, while in-game "mitten" gauntlets are encumbering, but not as much as one would expect from piece of gear that forces all of your non-thumb fingers to articulate at once. Glove/finger gauntlets can still double as a nice set of steel knuckles, too.
> 
> Example of finger gauntlets:
>  https://medieval-armour.com/medieval-armour/medieval-gauntlets/medieval-finger-gauntlets-3-html
> 
> I am not saying mitten gauntlets weren't used IRL, it's that they were most often used in tourneys, where one only needs to hold a sword/poleaxe/lance for the duration of the round and can allow to take his gauntlets off without much hazard. In the battle, one would need to do much more than just hold and swing his weapon, especially if one is a commander and/or a horseman in the gunpowder era.
> 
> Here is a reiter (armored horseman with pistols as his main weapon) 3/4 suit with a fingered gauntlet, the mitten gauntlet was originally for the left side, though:
> https://collections.royalarmouries.org/object/rac-object-39793
> 
> > The full suit weights are probably my oversight during the initial creation, the higher numbers should be used.
> 
> What about chestplates? 2 mm of metal added/removed relatively to medium chestplate, yet light chestplate is only 2.5 kg lighter, and heavy is whole 7.5 kg heavier.
> 
> The solution may be making medium chestplate weigh 12.5 kg, fits in well with ~5-6 kg per 2 mm of steel.

I will get back to you on this, just been a busy couple of days.

**Comment by randomtyper** [comment]
> I will get back to you on this, just been a busy couple of days.

Mind if we do it in Discord? Github seems to not be a good environment for such discussion. Will DM you if yes.
