### ISSUE TITLE
Military Base Changes

### ISSUE THREAD

**Issue by Procyonae** [CleverRaven/Cataclysm-DDA#66251]
### Is your feature request related to a problem? Please describe.

Mil base stoopid
Me change

### Solution you would like.

Looking to get some discussion on the mil base both from a realism and gameplay standpoint before implementing changes, very open to suggestions and arguments against proposed changes

Current major issues as I see them:
The whole place is too predictable for the reward and the warehouse with the most loot is very easy to scavenge without dealing with the majority if any of the zeds. Why did noone decide to defend the places with all the loot like the warehouse and armoury when shit went down and are instead mostly chilling outside? Why is there so much unused loot lying around in this situation?
The tunnels turn an already easy location to loot into an even easier one by connecting all the loot locations while containing no threat other than the completely avoidable only seemingly defended area which ironically has very little loot.
I don't understand why the mil base has a minefield. I don't understand why it's so close to the wall, I don't understand how the whole place became overrun and walls damaged etc with so much of the minefield still in tact, I just generally don't get it.
Even if the military is fine with all the civvies parking out front for protection I feel like they'd of had to prevent more peeps coming at some point and have to keep them out there with more than just a barbed wire fence bc it's not hard to imagine the civvies trying to break in for supplies. Equally if they're hunkering down it doesn't make much sense that there are random military vehicles parked around not being used as defences or that deserters have tried to escape in.
Minor use of auto roofs.

Changes I'm currently considering implementing:
Randomise the layout probably by making it mutable but while maintaining the same shape of roughly the same size.
Make the big loot warehouse more awkward to access by having it be at z-1 with a road ramp entry facing inwards so you can't just bust the wall down and actually have to deal with some zeds.
Rebalance loot in the warehouse and add zeds, possibly splitting the warehouse into two non adjoined warehouses.
The stocked armoury should be heavily depleted.
If tunnels between the loot havens is realistic them have them be risky and/or partially collapsed.
Remove the minefield or deplete it esp around defence breaches.
There should be no random parked military vehicles.
Add the remaining roofs.

**Comment by GuardianDll** [comment]
I assure you it is really huge task, and really hard also - mil base map is really old, and even if it uses palette for furniture and terrain, whole loot is still placed manually, using coordinates. I think make it mutable is the only way to make it tweakable in any way

**Comment by Procyonae** [comment]
> whole loot is still placed manually, using coordinates

Is manual item placement a big no no now then? The map is at least vaguely OM aligned rn so just shimmying the current coords would be fine but if they want out right replacing that would obv be more work

> I assure you it is really huge task, and really hard also

I'm happy to undertake this just want to make sure peeps are happy with what I'm doing before I start so peeps don't expect huge changes later, planning on leaving this open for like a week before I start probably bc I think this location is contentious for a non faction poi

**Comment by fairyarmadillo** [comment]
The US hasn't used anti-personnel landmines since 1991, I'm not even sure the army would have them ready to go if suddenly they decided they wanted to use them against Americans. A part of me wonders if we shouldn't remove landmines entirely and replace them with IEDs or simpler traps in places like bandit camps.

Modern militaries do use much more powerful anti-vehicle mines, which are generally not set off by people walking over them - it takes the weight of a vehicle usually. It would make sense that the military would have fortified its base against rogue soldiers and militia groups by deploying these, but they would need to be a separate object from the existing land mines.

The military is combat-trained and designed to have a resilient chain of command because its purpose is to survive emergencies. I would think this would mean that groups of less-feral individuals would hold out longer than groups of ordinary civilians, and there'd be a lot of really fierce fighting between loyal and rogue groups. What I'm saying is there should probably be more evidence of wanton destruction in the military bases than elsewhere because these people would have been lobbing ordnance at each other until there was nobody sane left, and maybe even for a while after that. It should look like a warzone because it was one.

**Comment by GuardianDll** [comment]
> Is manual item placement a big no no now then?

It's not a no-no. but having stuff in the loot groups, and connect them into symbols is really simplify further maintenance and updating the location - in case of loot groups they are reusable, and in case some new item would be added, it's really easy to just find an item with similar property, that could be used with it (like if someone want to add a screwdrivers, sticking to hammers would make lot of sense) and add it in respect loot groups, comparing to attempt to find the map itself, find the exact coordinate of a box that contain this tool, and add it here

Same as reusing paletts, but it's much harder i think

**Comment by carmakazi** [comment]
> The US hasn't used anti-personnel landmines since 1991, I'm not even sure the army would have them ready to go if suddenly they decided they wanted to use them against Americans. A part of me wonders if we shouldn't remove landmines entirely and replace them with IEDs or simpler traps in places like bandit camps.

They don't use buried antipersonnel mines, but M18 Claymore mines are still produced and stocked, though only rarely used IRL.  Adding that as an item and coupling it with the tripwire trap that already exists could be an alternative.  And/or do a similar thing with regular frag grenades and other conventional explosives they might have had on hand to convey a little desperation.

I'm not even sure if that's possible to do right now.  Traps have been a pretty underutilized asset for a while.

Either way the "land mine" item is old as hell and I wouldn't mind seeing it reworked into an IED or removed.

**Comment by arggme** [comment]
I'm not sure it would be the desired way to reduce loot, since it would turn the space less interesting, but large portions of homeland military bases have little to do with military operations.  Loot could be reduced by replacing tiles with basics.

I strongly prefer the destruction take however, as if not destroyed I would otherwise might otherwise military bases to be strongholds with survivors.  I have seen many bases built near natural defenses after all
