### ISSUE TITLE
Monster's are not visible if 3d FoV is turned off

### ISSUE THREAD

**Issue by GuardianDll** [CleverRaven/Cataclysm-DDA#66277]
### Describe the bug

it was always a thing, but with tile 3d vision intrioduction it happen to be obvious, but there is some inconsistency between 3d fov option and what you actually see (see the steps)

### Attach save file

N/A

### Steps to reproduce

1. Teleport yourself on a roof in the middle of the city with 3d FoV turned off
2. See you can observe ground perfectly fine, but monsters are invisible for you
3. Turn 3d FoV on
4. Now you can see monsters also

### Expected behavior

Make 3d FoV by default without way to turn it off

### Screenshots

The game with 3d FoV turned off
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/67688115/33d2b625-f0ea-4fdc-83fb-cccd1553deb6)
And on
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/67688115/214afa0f-b036-41b8-ab06-f99555ecf207)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2846 (21H2)
- Game Version: 38bfec9 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved]
]

**Comment by Qrox** [comment]
I think it is supposed to fallback to the old method of displaying colored blocks for the z-level below if 3d fov is off. @Rewryte could you look into this?

**Comment by Rewryte** [comment]
The 3D vision toggle had always determined if you can see a creature on another z-level and vice versa.  I left it untouched because otherwise players would have an unfair advantage of being able to see creatures that cannot see them back.

> I think it is supposed to fallback to the old method of displaying colored blocks for the z-level below if 3d fov is off.

I tied terrain vision to the "vertical range" 3d setting independent of the 3D FOV toggle.  Colored blocks will appear if it is 0.  This give players more options.  Though now that this is mentioned I do see how it can give players a false sense of safety.

> Make 3d FoV by default without way to turn it off

I tried setting 3D FOV to default but it results in tests freezing partway through and never completing with no error message.  Haven't got the time to pinpoint the cause yet.

**Comment by Qrox** [comment]
> I tried setting 3D FOV to default but it results in tests freezing partway through and never completing with no error message.

FYI, the test freeze is caused by NPC placing construction materials in the midair and then losing track of them, and I've got a fix for that. However, setting 3d fov to default also causes the test to fail when checking visibility of enemies in the activity interruption test and I haven't found out its cause yet.
