### ISSUE TITLE
Equipping Nomad Jumpsuit causes error every turn

### ISSUE THREAD

**Issue by b3brodie** [CleverRaven/Cataclysm-DDA#66325]
### Describe the bug

Equipping gear that causes a mutation, such as the nomad armor Well Distributed mutation or the necklaces from XEDRA Evolved Perks, causes an error every turn.

 DEBUG    : Tried to get cost timer of well_distributed but doesn't have this mutation.

 FUNCTION : get_cost_timer
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\mutation.cpp
 LINE     : 638
 VERSION  : c3e2de8

### Attach save file

N/A

### Steps to reproduce

1. Spawn in and equip Nomad Jumpsuit
2. Move

### Expected behavior

Error should not appear due to wearing the item

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3086 (22H2)
- Game Version: c3e2de8 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations],
    Xedra Evolved [xedra_evolved],
    Bombastic Perks [bombastic_perks]
]

**Comment by RenechCDDA** [comment]
cataclysm-tiles.exe!Character::get_cost_timer(const string_id<mutation_branch> & mut) Line 638	C++
 	cataclysm-tiles.exe!suffer::mutation_power(Character & you, const string_id<mutation_branch> & mut_id) Line 240	C++
	cataclysm-tiles.exe!Character::suffer() Line 1832	C++
 	cataclysm-tiles.exe!Character::process_turn() Line 2186	C++
 	cataclysm-tiles.exe!do_turn() Line 636	C++
 	cataclysm-tiles.exe!WinMain(HINSTANCE__ * __formal, HINSTANCE__ * __formal, char * __formal, int __formal) Line 793	C++

Looks to be due to https://github.com/CleverRaven/Cataclysm-DDA/commit/23013e78ff8a9fafd001fa6a3f4386f50a5004ad#diff-bf5b467bdd6a9299e8d832cc97cf93a6aef9b7a5e4f3078e8189cd3f92f8a951

@Venera3
