### ISSUE TITLE
vehicle has repeating non-existant tiles in diagonal position

### ISSUE THREAD

**Issue by martosss** [CleverRaven/Cataclysm-DDA#66390]
### Describe the bug

when you make a vehicle and try to drive it diagonally, sometimes tiles get repeated, even though they shouldn't be there.

### Attach save file

N/A: should be pretty straight forward - make a vehicle that's 2x7 and rotate it diagonally.

### Steps to reproduce

1) make a vehicle that's 2x7, probably happens with other sizes.
2) drive it diagonally

### Expected behavior

the vehicle has the same number of tiles no matter in which direction I drive it. Not more. Not less.
When it's diagonal, tiles that normally share a side should share a corner and be diagonal.

Alternatively, when I'm slightly turning(not at 45 °, but rather at 22.5²), the tiles could be even more shuffled. For example, the frost part of the vehicle could be 1 tile shifted to the side, as long as different parts of the vehicle share at least a corner it should be OK?

### Screenshots

![diagonal vehicle bug](https://github.com/CleverRaven/Cataclysm-DDA/assets/7064677/e9f1ac40-049b-4df1-b5db-b96ca26c0d49)

### Versions and configuration

- OS: Windows
    - OS Version: 6.3 9600 (8.1)
- Game Version: d6ec466 [64-bit]
- Graphics Version: Tiles
- Game Language: System language [] (english)
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

The same thing happens with this vehicle even if I drive it not at 45° angle, but only slightly to the side - the front windshield is repeated and 3 windshields appear, even though I have only 2.

**Comment by irwiss** [comment]
Fake parts are filling gaps https://github.com/CleverRaven/Cataclysm-DDA/pull/56143

**Comment by martosss** [comment]
Ah, fake parts to avoid monsters getting in... shouldn't the 'right' behavior be to allow the same movement diagonally as would be possible if we were in vertical/horizontal position?

In other words, map the "normal" tiles to their diagonal positions and only allow movement between tiles that would be traversible in "normal" position, disregarding the "fake-new" neighboring tiles in diagonal mode? 

A potential problem with this approach is that it could make some normally traversible vehicles untraversible in diagonal mode, maybe? But the current system can still do that if there are fake parts placed instead of nothing? I'm not sure if this is the case, just trying to think outloud.

**Comment by TheRafters** [comment]
The repeating tiles are ugly but far preferable to the monsters slipping through like they used to. 
What is an issue is the edge cases where the fake tiles hamper driving such as the case you mentioned in your additional context leading to situations where you impact things that shouldn't be in range to be impacted or even completely entrap your car by materializing a fake tile on top of an obstacle like a telephone pole or a tree. 

The first case happens because the fake tiles exist for just long enough in the case where you go from slightly turning to straightening out. In the moment where your vehicle returns to straight the fake tiles exist long enough to impact terrain that shouldn't be in range.
The second case has happened while making sharp turns around multiple obstacles, but I can't make it happen on purpose yet.
