### ISSUE TITLE
Allow translators to re-assign shortkeys

### ISSUE THREAD

**Issue by Wuzzy2** [CleverRaven/Cataclysm-DDA#6645]
This is a suggestion regarding the shortkeys of certain menu items.

With “shortkeys” I mean the highlighted letters one finds in serveral parts of the game.  Examples for places where shortkeys appear: item description menu: `<E>`at, `<D>`isassemble, etc., in the main menu, in the auto pickup manager, the vehicle menu. There may be other places as well, but I find those four places the most pressing ones.
Sometimes the only way to access a function is to press the highlighted key. Now there’s a problem: The shortkeys are fixed. If you translate, you are forced to somehow include this key in the text, although it is not part of the word. Also keep in mind there exist languages which do not use the latin script. Not including the letter in the translator would mean the player doesn’t know which key to press.

The solution to this to let translators choose (almost) any shortkey, so they could (for example) choose any character of the menu item string. This can save precious space for translation. (Yes, space is scarce.)

So if the original string is “`<A>`dd”, for example, this means the `A` key has to be pressed. If a translator translates this with “`<H>`inzufügen”, the game will recognize the letter which is enclosed in the less-then and greater-than signs as shortkey and will add a rule if the `H` key is pressed. Of course, the translators would be then responsible for every menu being accessible and that no 2 letters overlap. Therefore, the strings should be commented properly for the translators, for example: “This is a menu item of the pick-up menu. The character in the angled brackets is the key to press. Make sure the shortkeys of the other menu items of this menu do not overlap with this one.”. If there are other keys (possibly fixed keys) which may not be used for the shortkeys, the comment should say so.

**Comment by mugling** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
