### ISSUE TITLE
It's hard to work on Exodii

### ISSUE THREAD

**Issue by fairyarmadillo** [CleverRaven/Cataclysm-DDA#66483]
### Is your feature request related to a problem? Please describe.

The Exodii were introduced a couple years ago to try to and migrate cybernetics away from XEDRA and labs. While many (myself included) enjoyed the old system, I can get behind the idea that different character progression systems should be in different places. But in the years since their release, very little content has been developed for the faction, and this has left bionics in a super awkward place where you get 99% of them by selling cocaine to a single NPC with no risk or effort involved.

I've considered adding content to the faction, but I always hit a wall creatively when I try to get going. Here are a list of things about them that I feel don't currently make as much sense as they could: 

**Implants:** Exodii are depicted as being made mostly of metal with just a few human parts in them, like General Grievous from Star Wars. They have sort of ship of Theseus'd themselves into reverse cyborgs, that is, robots with a few human parts. This is supported by the following descriptions:

Exodii Worker: _A mostly humanoid robot equipped with various construction tools._
Zomborg: _A mix of dead human and even deader technology, this twisted mess of steel and flesh moves like a puppet in the hands of an angry toddler. Its robotic components seem to have shut down, and new bands of flesh have wrapped around them, tugging and pulling them in awkward directions. Bits of metallic skeleton and armor plating jut from its decaying flesh._

This is because their dimension hopping technology can only take a small amount of organic material. I find this explanation a little unsatisfying, and it also causes several problems.

1) Most of the CBMs in the game are small implants designed to interface with an organic human body. The Exodii would have little use for these items, as they don't have human bodies. Why would Rubik have an integrated toolset, bionic claws, shotgun arm, fingerpick, finger lighter, etc. when he and his friends do not have human arms? This isn't just down to replacement limbs either. Many of the other CBMs, like carbon filament, cranial flashlight, muscle augmentation, wired reflexes, etc. are clearly intended for human bodies. Rubik doesn't need a cranial flashlight CBM, he can just bolt a headlamp to his skullplate or whatever he has. CBM technology seems both orthogonal to and redundant with brain-in-a-jar technology.

Now, you could argue that they _used to_ use these things, and now only manufacture them for trade, but that doesn't jive with the fact that dissecting zomborgs is meant to be one of the primary ways that the player can find new CBMs. I also don't see why they'd go to the enormous trouble of maintaining a surgical suite capable of implanting these CBMs into mostly-meat humans.

2) The Exodii sell a lot of clothing, or blueprints to make clothing, which they have no apparent use for. Why does the nomad gear have climate control, when that's already a CBM? Why wouldn't the robots just have coolant pods or something? Why is a robot even wearing clothes? They would just get in the way.

**Personalities and Language:** Rubik is the only point of contact, and he barely speaks English. There's no possible way to learn the Exodii language, which I assume is some kind of alternate-earth Slavic language. This creates a barrier for contributors as it's very difficult to write Rubik's dialog and anything you submit has to get approval from I-am-Erk. It shrinks the player's ability to interact with this faction down to a single guy and you can't write any characters with dissenting opinions, under-the-table deals, or anything else. This isn't an insurmountable issue, but I think it's a large part of why we haven't seen more content for what should be an exciting newish faction for contributors to mess with.

Hub 01, for instance, has the intercom guy, it has the ancilla bar, it has the mercenary in the front office, it has the merchants that pile into the back, and while the interior characters aren't currently interactable, they are slated to play a larger role. The refugee center has the beggars (who are themselves a diverse group with varied opinions), the guards, Smokes, the doctor, the trucker, the refugees which have names and quests and provide services etc. The Exodii have Rubik and Luliya, who can't even talk to the player. 

Another issue here is that the Exodii are written as good guys. They might be isolationist, but if Rubik is representative of the whole (and he has to be, being the only point of contact), then they are good-natured salt-of-the-earth people who have sympathy for the people of the worlds they visit and other than the quadruped thing, don't ever commit any morally questionable actions. Contrast this with Hub-01, the Old Guard, and the Refugee Center, who are all very jealously guarding what little they have and can come off as huge assholes, even though they're also just trying to survive.

**Made-up technology:** The Exodii being from another world and have alternate earth tech, which means that aside from their guns, all of their stuff has to be thingamajigs and whatchamacallits with no actual function. This turns what should be high-value interesting items into cruft and set-dressing. This wasn't as much of a problem with XEDRA lab stuff, because much of it either did have a function, or could be readily understood by the player, or could be deconstructed for useful items.

**It's a small faction:** XEDRA was a nationwide conspiracy involving tens if not hundreds of thousands of workers who were partially integrated with government and corporate structures, giving them a robust footprint in the world. There are obviously way too many labs in each overmap tile currently, but it makes a sort of sense that you can find a subway lab, a TCL, and a central lab in the same state or even county. This organization is to blame for much of what has happened in the world and there was a large-scale gold rush underway to try to capitalize on the new scientific discoveries they'd made.

The Exodii, on the other hand, appear to be like, a couple dozen or maybe a couple hundred people who live in a single fortress. It does not make sense that there are zomborgs scattered across the countryside. If they're losing this many people every time they jump, then how are they still alive at all? Rubik makes no mention of this sort of huge attrition, and seems reluctant to even mention the possibility that people could join. There's also no evidence that any of the Exodii we see are other than the original stock of guys from Russia-2 or whatever their home country is called.

This means that it's pretty unlikely that the player would run into Exodii stuff other than their main fortress, and this is especially problematic when thinking of new areas to place zomborgs. For instance, I've thought of making a location that was a separate Exodii fortress that fell to the Blob and needs to be cleared out so Rubik's guys can salvage its dimensional tech, but in approaching this I immediately ran into the idea that if the faction is shrinking this quickly, then they wouldn't be nearly as successful as they appear.

### Solution you would like.

**Implants:** I think it would be best to reflavor the Exodii as humans who extensively use bionics, and may in some cases have become unrecognizable, but are not a society composed entirely of General Grievouses. The "we can't bring a lot of organic matter" explanation has always been an extremely shaky one, and I don't think it's necessary to justify the faction's existence. If the goal is to make them difficult to join up with, then they can simply be suspicious of outsiders because they know how insidious blob psychosis can be, and they don't know the player from a Hell's Raider.

This is alternate-earth Euro-XEDRA after all. These guys are at least partly composed of government spooks and higher-ups that probably have plenty of experience keeping the public at arm's length.

This solves the twin problem of CBMs and gear not making sense for the faction. If they have members who still have their original skin and limbs, then of course those people would be wearing cyberpunk bodysuits and riddled with small implants. Consider 40k's Mechanicus, many of whom still appear to be largely human, though they have the ability to replace nearly all of their flesh if the need arises.

**Personalities and Language:** This could be solved with language-learning via the proficiency system, which could open the faction up a lot more to the player. This could also be a part of integrating with the faction in the hopes of someday leaving this Earth with them. As for their morality, it's fine if the Exodii are fundamentally decent people, but it'd be nice to see some more shades of gray, and more NPCs would help with that.

**Made-up technology:** I get that to some extent this is necessary, but it'd be nice if the player could eventually learn to do things with these items. Modifying or repairing CBMs is the first and most obvious use, but they also have a lot of devices that appear to be used for power generation or storage that might be fun for the player to play with, and could stand-in for some of the now-obsoleted atomic and other super-science items.

**It's a small faction:** I think this is a place where the faction has been written into a corner. They're aliens, and even rarer than the mi-go. It's extremely hard to justify adding locations for them unless you want to say that 90% of their people die every time they jump, in which case why would they bother?

I suppose one option might be to write in that the faction used to be thousands strong and normally the jumps go smoothly, but this time a catastrophe has struck and the majority of them were lost. This could put the player in a position to try to raid large zomborg sites and recover tech either for the Exodii or Hub-01, and would put the Exodii in a mood to do some recruiting.

### Describe alternatives you have considered.

Exodii appear to be networked via what they call the Great Grey. They use this in lieu of AI technology. It would be interesting if this had a negative effect on their humanity/individuality, especially if the player was ever given even partial access to this network. Imagine if a coprocessor for example gave an additional +1 int while in radio range of the Exodii base or one of its relays. 

Now imagine this is how the martial arts CBM works, or CBMs that give you access to skills or recipes you don't normally possess - you're drawing on the collective knowledge of the community, but carving out parts of your brain to do so. Some of the more drastic CBMs could even penalize you if you were outside of radio range as your ability to think for yourself was diminished. This would create a stark contrast between a collectivist faction and the Hell's Raiders, who seem to be more individualist.

**Comment by anoobindisguise** [comment]
I agree with this heavily. Rubik's dialogue in particular is super hard to mimic and Erk doesn't have enough time to maintain it. It could be worthwhile toning it down somewhat so that Rubik uses some odd phrases and archaic meanings of words but don't lean in quite so heavily into the "you need above average intelligence to immediately get what Rubik is saying" bit. Even if the original Exodii group is mostly Slavic based on the "Mavrik 10-101 power core" description surely there should be a way to communicate with them. (Though that would require them to exist first)
Exodii being almost entirely total conversion borgs like Adam Smasher also limits the number of creative influences the Exodii can draw from. Most cyborgs in existing media are still recognizably human, and the middle ground arguably leads to a greater sense of body horror than an entirely robot body with a human brain piloting it. (I think that cybernetics should lean into body horror heavily! It's one of the coolest parts of mutations). Only the oldest and most long-surviving Exodii should be full conversions as their human parts eventually broke down and failed on them over the decades. Rubik could potentially be one of those, but it should be clear that the rank and file Exodii are just people with a lot of implants. That would also explain why they bother to scoop up bronze armor suits and whatnot, because they personally can make use of them, rather than banking on them being good trade fodder for their next dimension.
Also, Exodii being mostly human isn't incompatible with the "you need implants to survive the jump to a new dimension" bit. The Nether operates on a lot of psychic fuckery and it's not unreasonable to say "you need an implant to keep your self focused during the jump otherwise your psyche will shatter". That said, it's not even necessary that we need to keep that part of the lore.
It would be good to try and get some finer numbers about how many Exodii there are on planet Earth. Is it such that there are multiple nodes who jumped per country or is Rubik's group the only one on Earth? Are there 100s, 1000s of members? How many zomborgs should there be? Do zomborgs come from their feral-powered drones dying, or was it a portal accident? There should be a better answer for the existence of Zomborgs than "it's from Exodii who didn't make the jump" because otherwise like you say the Exodii would just cease to exist from attrition alone.

**Comment by fairyarmadillo** [comment]
The best solution for "what is a zomborg" is the one that allows contributors to create the biggest variety of interesting enemies for the player to fight. Bio-operators for example have been in limbo since the exodii were introduced, but could easily be exodii special forces who wound up dying, and the list of CBMs suggests dozens of abilities that even a zombified and malfunctioning cyborg enemy could have.

**Comment by lcy03406** [comment]
I think the idea of reverse cyborgs is pretty cool, so I would try to solve the problems without changing it to 'human with many CBMs'.

A dimension hopping civilization. What do they need from Earth? How do they reproduce themselves? How would they live everyday?

- Not everyone needs or enjoys to Jump. Their civilization must have some basement worlds in other dimensions. Rubik team runs a dimensional caravan. So the group is small but not recruiting.
- **So it's ok that another Exodii team is fallen and to be explored.**
- They are friendly because they are merchants not pirates. **There are dimensional pirates**, though humans cannot tell whether they are from the same civilization.
- They dont 'speak' language. They communicate with 'integrated radio CBM'. So Rubik's spoken English is wierd **unitl you integrate one**.
- They must need energy and material. But their energy is beyond human knowledge, so Rubik buys cocaine and everything.
- They don't quite understand human technology either. Just like modern human don't know the different best usages for different stones in stone age technology. So Rubik brings bronze junks for sale.
- They sell CBMs. But I'd like to modify the goods list, it should limit to two categoris: 1) low-end cosmetic CBMs, which are easy to make and sell pretty well in most worlds. e.g. tattoo lights. 2) 'threshold' CBMs, which they themselves use. e.g. nuclear arm cannon.
- **They can also sell reverse-CBMs, or, wetware vehicle parts.**

**Comment by fairyarmadillo** [comment]
I don't feel like that really solves the issue of their numbers being unsustainably small or their technology and equipment not making any sense in the context of the game.

**Comment by I-am-Erk** [comment]
I'll be happy to address this tonight or tomorrow morning

**Comment by fairyarmadillo** [comment]
> I'll be happy to address this tonight or tomorrow morning

Thanks for chiming in! I'm glad to hear that you have more planned for the faction.

Would you be willing to budge on the "flesh can't teleport with us" thing? A good alternative could be that raw unshielded exposure to the process drives people batty because their mind gets a glimpse of The Horrors Beyond, but the Great Grey can protect its members. This would allow for some variation in how the Exodii and their zombies are depicted, and would help with the aforementioned gear issues.

I know you've said you're not going to stand in the way of changes but I wouldn't be comfortable doing much with the faction if I knew it was running counter to what you wanted for them.

**Comment by I-am-Erk** [comment]
So, the "can't teleport flesh thing" is about as flexible as it comes because it's obviously not really true, and never has been. It's unclear how much is true (it's not entirely false) but it's also a tactic to keep people from trying to convince them to let them hitch a ride. We can see that zomborgs can make the jump and are not fully metal enclosed, so Rubik's not being honest.

**Comment by anoobindisguise** [comment]
> Size: there are probably a few hundred individuals within the exodii node, they just don't hang out around the base all the time (and aren't all depicted because lag). You'd see more of them in other locations if we get around to adding more missions.

How many zomborgs should be expected to result from dimensional jumps? Like what are your odds of getting killed, 1/100?
Where are all the zomborgs coming from? People trying to bootstrap the remaining bits of Exodii tech left behind to follow them with usually disastrous results? The Nether saying "ooh cool thing" and spitting out a bunch of facsimiles of it into wherever the cool thing was headed?

**Comment by I-am-Erk** [comment]
Zomborgs represent hitchhikers that came along during the jump, there can be as many as we need. I'd like to someday see their numbers boosted by the odd more highly evolved zombie, or weird nether copy of a zomborg or exodii

**Comment by fairyarmadillo** [comment]
> Zomborgs represent hitchhikers that came along during the jump, there can be as many as we need. I'd like to someday see their numbers boosted by the odd more highly evolved zombie, or weird nether copy of a zomborg or exodii, but these should be curated to not be instantly deadly to new characters

Oh like from the homeworld? That makes a ton more sense.

**Comment by I-am-Erk** [comment]
Some furhter clarifications as promised

- why I don't love a language module: part of the goal with the exodii was to work on having a small number of much more fleshed out characters, rather than a host of stubs. In hindsight I see that I shot myself in the foot with that by also making Rubik so idiosyncratic, but in my defense didn't expect to be so persistently unavailable as I've been. Nonetheless, since the Exodii really are meant to be a fairly big faction, I worry a lot about how complex it might be to add the ability to freely talk to them.

That said, we might be able to add a "Rubik translator" module that only works for them, or maybe some very limited translator that has some in game reason to only help with individuals who can speak certain languages that have been programmed into it. Or maybe Rubik can sell you the translator, with Anglic programmed in but you need to trade for or earn extra individual languages? That last one would feel very exodii and might be a really cool option, allowing us to "unlock" particular NPC's as we become ready for it.

- how are the exodii not nice?

Spoilers here. I've been trying to keep from plastering this bit all over the place because it represents the final revelation of the exodii story arc. Don't read on if you plan to play this rather than contribute.
The exodii are survivors taken to extreme. To make it this far they've had to make some hard sacrifices. The most questionable in my opinion is that since they can't build complex software, most of their machinery runs on organic brain matter that has been trained to perform a task. If asked, they'll skirt around this topic or imply that they use animal brains and feel badly but what are you going to do? In reality the main brains they use are of people who they reject for membership in the node. From the moment you meet them, they're assessing to see if you're a possible exodii and if not, if they should use your brain interface to shut you off, take out any blob-affected chunks of your brain, lobotomize you, and hook you up to a quad or worker drone body if you're still functional enough to operate it.

They're already doing this by the time you meet them, with people more obviously far gone. The player will usually represent someone sufficiently useful to be kept around for a long time, but for most players - with their insane risk taking behaviour implying blob effects - the exodii will eventually deem you likely dangerous and, when you've expended your usefulness as a free agent, will terminate your freedom and make you a semi-conscious slave.

It's pretty ugly and many members don't really agree with the practice (including Rubik) so the pathway there will include increasing "outs", especially if you spend some time to befriend any of the speaking exodii. Ultimately though, Rubik would choose their node over you even if they don't agree with the practice, because they're all survivors, and without the node Rubik can't survive.

**Comment by kilozombie** [comment]
If you'd like more locations where Exodii tech can be found, but without the faction literally present, what if some of these hitchhikers have been trying to reverse-engineer the CBM technology? It would be interesting to explore a ramshackle laboratory of totally different make than XEDRA ones, but still developed to try and recreate bionics, so with decent equipment and even some intact prototypes. This might even be a place where the hitchhikers have developed their own prototype interfaces for members of their community who haven't interacted with the Exodii. This could be a really cool way of introducing the player to the faction from an outside view, but without the context--as well as giving them a few bionics to play with if they can figure out how to fix the equipment.

If they came along but the structure/people were damaged irreversibly by the jump, that would give reason for it to be infested with zomborgs along with ramshackle defenses/traps.

**Comment by kilozombie** [comment]
They wouldn't intentionally teleport the people though, either, surely? How did the zomborgs get to this dimension, especially so spread out away from the Exodii? If structures were to come along, I could imagine them taking similar form to the existing pods (?) that drop with Zomborgs in.

**Comment by fairyarmadillo** [comment]
I think the idea is that the exodii either have multiple structures or their base gets dispersed a bit when they hop, and some of the other sites happened to have zomborgs in/around them. A better location idea would be a fallen exodii sub-base, their equivalent of a tiny XEDRA lab or something.

**Comment by I-am-Erk** [comment]
Yes, the plan in fact is to have a few "overrun" sites that the Exodii transported anyway so that they could try to send out recovery teams.

**Comment by I-am-Erk** [comment]
Related side note, if anyone is aware of any other exodii PRs that could use my translations or input, this is an OK spot to let me know as I'm watching the topic. I'm actually going to have a little time in the next few weeks and would love to help get the ball rolling again. Just finished one of MNG's that was getting super old.

**Comment by fairyarmadillo** [comment]
I'm reworking the prototype borgs currently. I think they might work as a lobotomized/enslaved worker who got damaged or malfunctioned and can be restored to humanity with some surgery. I'll ping you when the PR's up.

**Comment by I-am-Erk** [comment]
Hmm, interesting thought. I think we should work together on this. If you're on discord, ping me, but here are some start points if you're not:
- My own thought had been to make prototype cyborgs show up later in the game, as people who were trying to use stolen exodii tech. Most of them were probably already exodized by Rubik, like you, but then added more on their own or with some limited help.
- The dialogue I just added for rubik in #63477 fits with that idea, and makes it sound liek you could be running into groups like that reasonably early on in the game.
- It's also possible that we could have a specific location of an exodii site that was taken over by a third party in the previous dimension, but the teleport was still online and brought them over here. This would be more of a one off than prototype borgs currently fit with, but it would be a super cool location and I can offer some ways Rubik might send you there.

**Comment by I-am-Erk** [comment]
I'll allow this to lapse for now since the solution is linked in another post and I'm currently back and active on Rubik, but if I fade away feel free to reopen it
