### ISSUE TITLE
Cannot make colored text in npc dialogue

### ISSUE THREAD

**Issue by gettingusedto** [CleverRaven/Cataclysm-DDA#66510]
### Describe the bug

I once had an idea to color the one part of the pyromaniac mission text to highlight the fact that you need to bring gasoline. after i covered said part of the text with `<color_yellow>` & `</color>` and ran the game to check it, it does not appear yellow.

### Attach save file

N/A

### Steps to reproduce

1. cover a npc text with the aforementioned `<color_(colorname)> [NPC_Text] </color>` in the json.
2. run the game and check said npc text
3. it does not get colored.

### Expected behavior

The npc dialogue text being colorable.

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: samsung; Model: SM-A710F; Release: 7.0; Incremental: A710FXXU2CRC2; 
- Game Version: 30f23ec [32-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved],
    Aftershock [aftershock],
    cable stuff [cablestuff],
    LuckySlotmachine [luckyslotmachine]
]

**Comment by ZeroInternalReflection** [comment]
I've been unable to replicate this.  Adding colour tags to npc dialogue in the json appears to work properly.  In the tests below, "Emergency" and "Panic" had red tags added, "Help/Tutorial" had yellow added.  The text colour gets changed in both the dialogue selection panel and the message history panel.

![Talking_to_ally](https://github.com/CleverRaven/Cataclysm-DDA/assets/89038572/a05abc8d-50d0-437c-b636-56db2e38df0a)
![Talking_to_pc](https://github.com/CleverRaven/Cataclysm-DDA/assets/89038572/b5329473-aeca-4f4c-b848-b5573faa6f0b)


>NPC dialog window uses multiline_list::print_line which strips color tags from the output text (and does some other color manipulations):

It took me a minute to remember what was going on there, but the remove_color_tags() line is not actually used in the dialogue screen.  It was added as infrastructure so that I could convert some of the character creation screens to multiline_list (which hasn't happened yet, and probably needs some separate work).  The only colour change that multiline_list should be doing to the text is highlighting the selected line.


Can anyone who has run into this issue specify what files/lines they encountered it on?

**Comment by Night-Pryanik** [comment]
Can't confirm on latest experimental as of 10 October 2024.
![изображение](https://github.com/user-attachments/assets/0b227ee6-5042-46af-86ff-df638dee2452)
Closing until reconfirmed.

**Comment by gettingusedto** [comment]
Huh, might have gotten added at some point. Still, it does resolved my issue back then.
