### ISSUE TITLE
Pulping corpses should take more effort

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#66564]
### Is your feature request related to a problem? Please describe.

Currently you can pulp a corpse in just a few seconds, but zombies basically require you to smash or sever their joints and bones such that it's no longer capable of movement. The human body is pretty resilient, and especially being unarmed it seems way too easy to render a zombie non functional and unable to resurrect.

### Solution you would like.

Pulping should take a lot more time, maybe a halfway point between where it is now and the time to dismember a corpse. Stamina requirements should be higher too, as currently you can easily regain stamina while in the act of pulping and that doesn't seem right either.

### Describe alternatives you have considered.

Pulping the corpses also doesn't fix the problem of it being a zombie because the Blob can reclaim pulped biomass eventually, though that's a long term goal and there will need to be a way to automate the process of pouring fuel on the corpses and setting them on fire or whatever it is you're doing to render them unusable.

Pulping mutants probably shouldn't stop them from becoming meat cocoons.

**Comment by GuardianDll** [comment]
At first we need to define what pulping is, what action character perform to pulp, maybe tools they can use

**Comment by fairyarmadillo** [comment]
Time spent should be based on bash or cut damage and corpse size. I don't think the meat cocoon thing is a good idea. There are waaaay too many enemies (and plans to add a lot more density) to really make a change like that a good idea.

Pulping is, at the very least, entirely removing the head. No zombie survives without a brain stem. I imagine doing things like chopping off limbs, severing the spinal column, and just doing enough damage to make the blob "give up" on the body is enough.

So if you've got a fire axe and it's a normal-sized zombie, I feel like that's under a minute of work. If you have a cudgel and it's a hulk, you probably have a much bigger job ahead of you.

**Comment by TheShadowFerret** [comment]
> Pulping is, at the very least, entirely removing the head. No zombie survives without a brain stem.

The headless zombie evolution line partially exists to show that the Blob is *not* dependent on this(see #28643 which added them).

**Comment by fairyarmadillo** [comment]
> > Pulping is, at the very least, entirely removing the head. No zombie survives without a brain stem.
> 
> The headless zombie evolution line partially exists to show that the Blob is _not_ dependent on this(see #28643 which added them).

There are no headless zombies in CDDA. There are brainless zombies, which still possess the lower part of their head, and headless horrors, which evolve from them and have a different structure serving as a head. I always assumed that the fact that we went with those instead of the much funnier headless zombies suggests that a headshot wouldn't do the job, but full decapitation might be a bridge too far for XE037.

I'll grant that the text of the PR suggests otherwise, so maybe I'm wrong.

Realistically, removing a corpse's head would be a fairly simple thing to do. You could twist it off with your hands and maybe a knife without too much effort. Limbs are a bit harder though. Based on Victorian medical records, an expert using the best tools available could do an arm or a leg in like two minutes, or under a minute at the knee/elbow. So it doesn't sound like dismembering is too far off. Maybe it should check your butchering quality for speed if it doesn't already.

I think using a blunt instrument to inflict an equivalent amount of damage would take longer, unless you had a sledgehammer or something and could just Gallagher the corpse's head and torso. You could do it in just a couple swings. Maybe that's where we should start, and from there penalize smashers who have less bash or cut damage.

**Comment by DSeyka** [comment]
Pulping corpses is already a busywork from gameplay perspective though.
I'm afraid all it'll do is force players to waste time and keypresses catching breath.

**Comment by fairyarmadillo** [comment]
Yeah I agree wholeheartedly, and that's why it's been this way for as long as it has.

At the very least, some of the underpinning mechanics would need to be improved, such as the smash key automatically dismembering if that's faster (maybe toggleable with a setting) and maybe smash as a zone activity. The only real change should be the amount of in-game time that passes and energy spent, the playerside experience definitely shouldn't get clunkier.

**Comment by sadenar** [comment]
I'm of the opinion that it would definitely make more sense for more evolved zombies to be more of a pain in the ass to pulp, mostly because:
- They would straight up generally be harder to pulp for example in the armored/brute/hulk lines, it'd probably be way harder to turn a zombie into useless meat the blob wouldn't bother reviving when said zombie is a hulk or a bone boy.
- We could justify it as the blob overall having a more involved/active hold on them, therefore making it harder for its "connection" to the given puppet to be severed
- It would just make more sense in a meta/gameplay perspective to make later Zs harder to permanently get rid off when faced with better equipped, more skilled player characters than making it a pain in the butt to deal with from day 1.

I'd definitely be of the opinion that we should make it harder/easier to pulp specific kinds of zombies, and that a boomer and hulk should not take the same time to prevent their revivification.
