### ISSUE TITLE
Make flammable arrows out of other arrows

### ISSUE THREAD

**Issue by JestSomeone** [CleverRaven/Cataclysm-DDA#66583]
### Is your feature request related to a problem? Please describe.

Currently a flammable can only be made out of wooden bodkin arrows. I don't see a reason for an arrow with a rag attached at the end to need a bodkin arrowhead.

### Solution you would like.

I would like to have the other arrow types to be able to be crafted into Flammable arrows. 
Specifically on of the ones that do not require an anvil to make, like the Makeshift Wooden Arrow

### Describe alternatives you have considered.

Make a flammable arrow not require another arrow. A new recipe that is like making a Makeshift wooden arrow, but with a cotton patch and fuel added on. 

### Additional context

I discovered a fungus bloom next to my house and decided to throw a molotov at it to try and burn it out. It worked well, but there was a portal right next to it, so i wanted to stand further away just in case. I thought to myself "i saw flammable arrow in the crafting menu, i should use those." To my surprise i needed bodkin arrows, which means i needed an anvil and metal. My current base is pretty far away from a town so getting metal is  difficult for me, and as far as i can tell there is no bog iron or iron ore i can collect myself in the wilderness. Also it seems quite silly that this implies that a metal arrow head is required to tie a rag to the end of it.

**Comment by snipercup** [comment]
The recipe was changed in #49871. That PR fixed a bug where you could disassemble flaming arrows into bodkin arrows. 

In order to implement your suggestion:
- Create a recipe that takes different kinds of arrows
- The result of the recipe should reflect the amount of damage that the arrow you used as a component does
- Make sure that disassembling the flaming arrow results in the same arrow as you put in.

A lot has changed since the PR I linked, so maybe it's possible now? If someone know of an example recipe that modifies the result based on the input and disassembles into it's original components that would help. Idk if I'll implement a fix myself, I just wanted to comment this.
