### ISSUE TITLE
Gun damage is too low

### ISSUE THREAD

**Issue by Adamas12** [CleverRaven/Cataclysm-DDA#66594]
### Is your feature request related to a problem? Please describe.

1 bullet of 5.56/0.223 shot within range to the chest should kill the average person almost every time in real life, assuming they have no armour. Assault rifles are all purpose killing machines and are very effective at that, player characters and day 1 zeds should not be taking bullets unarmored and still being able to walk, they should be deceased. 

### Solution you would like.

Based on the design doc of the average person having 8 str, 5.56 or another caliber of a lower size should be chosen to deal as much damage as HP at 8 str, and other calibers should be corrected based on this.

I would like to do this myself but I didn't want to waste my time doing so incase it received a negative reception or was canned. I've also never added to this game or spoken to the core dev team so I thought it would be respectful to post here before making a pull request out of nowhere.

### Describe alternatives you have considered.

Do nothing and continue having shinigami armaments do the same amount of damage stones did when humanity was tribal.

**Comment by Paprika-H** [comment]
A) Firearms are meant to cause casualties, not exactly deaths. As long as a person is injured enough to be out of the fight, it works. 5.56 is essentially designed for that purpose, as trying to kill, and only kill becomes overkill. 

B) The human body is surprisingly resilient, and can survive bullet wounds. Sure, you can very quickly die without medical care, but just because a wound is from a bullet does not mean you hit the ground dead. Also matters where you are hit, as lower torso is very squishy and soft, with no a huge amount of blood flow, and as human body is able to function without a kidney, intestine for a short while, while in the chest, you can very quickly lose blood. 

C) Ammo is already very damaging, as one shot from a 556 rifle can kill a zombie, as combined with the initial damage of the bullet and bleeding out, you can deal a lot of damage.

**Comment by Daved27hundred** [comment]
The zombies in CDDA aren’t people anymore, they’re corpses controlled by something alien that mutates and repairs the body. They don’t need organs or even brains to move and so that shot in the heart won’t be enough to take it down.

hell the reason why they get back up is because you don’t actually “kill” them; you just damage the corpse to the point it can’t move anymore. Pulping makes the corpse impossible for the blob to repair before it rots.

**Comment by Paprika-H** [comment]
> The zombies in CDDA aren’t people anymore, they’re corpses controlled by something alien that mutates and repairs the body. They don’t need organs or even brains to move and so that shot in the heart won’t be enough to take it down.
> 
> hell the reason why they get back up is because you don’t actually “kill” them; you just damage the corpse to the point it can’t move anymore. Pulping makes the corpse impossible for the blob to repair before it rots.

Not to mention that zombies don't feel pain or fear, so something that would cripple a human from a mixture of pain, shock, and injury, will not cripple a zombie

**Comment by kevingranade** [comment]
Citation Needed on several fronts.
1. What's the in- game representation of this anyway? I suspect a "good" hit from a 5.56 round to the torso is going to be pretty close to what you're suggesting after factoring in damage multiplication and bleeding.
2. What are the lethality rates for 5.56 anyway?  Seems like something you could source.

Also, Zombies aren't people.

**Comment by fairyarmadillo** [comment]
Echoing everything said above and adding a couple points for clarity:

The 36 damage you see on Hitchiker's Guide is misleading. Bullet base damage is modified by the accuracy of the shot, which is determined by a roll involving your stats when you attack. You'll see it called out with Good Hit!, Grazing Hit, or other messages. That's 72 damage max according to the listed crit modifier, but I believe the cap is actually higher than that. A 72 damage shot on most basic zombie types, if it doesn't kill them outright, will lead to them bleeding out in a couple of seconds.

NPCs work a bit differently because they have body parts. NPC health can also be lower than zombie health, as it's calculated based on strength and traits. It is easily possible to have under 50 HP and get instantly dropped by a single hit from a 5.56 even if it doesn't reach its full crit potential.

People survive getting shot in war all the time, even in the torso and sometimes the head. Gunshots also very frequently kill by bleeding people and animals out over a few seconds rather than instantly destroying a vital organ.

You raise a valid concern but I think in this case you're lacking some information. I hope this is helpful.

**Comment by Adamas12** [comment]
> A) Firearms are meant to cause casualties, not exactly deaths. As long as a person is injured enough to be out of the fight, it works. 5.56 is essentially designed for that purpose, as trying to kill, and only kill becomes overkill. 
> 
> 
> 
> B) The human body is surprisingly resilient, and can survive bullet wounds. Sure, you can very quickly die without medical care, but just because a wound is from a bullet does not mean you hit the ground dead. Also matters where you are hit, as lower torso is very squishy and soft, with no a huge amount of blood flow, and as human body is able to function without a kidney, intestine for a short while, while in the chest, you can very quickly lose blood. 
> 
> 
> 
> C) Ammo is already very damaging, as one shot from a 556 rifle can kill a zombie, as combined with the initial damage of the bullet and bleeding out, you can deal a lot of damage.

A isn't true,fire arms are not designed to wound, but kill, they are just measured in effectiveness based on lethal and incapacitating wounds. The main design goal when making a bullet and platforms is always fatal lethality but this can be sacrificed for things such as accuracy, mobility and costs if it's determined that it's a decent compromise to it's ability to kill. Casualties was a term created by US military to essentially mean someone who might as well be dead in respect to their ability to participate in warfare, this is more useful as there are multiple ways to disable threats, with killing them being the most effective, and failure to kill them being not ideal but still good if they are incapacitated. For firearms it's ability to kill someone as well as the non ideal incapacitation are called "wounding ability" which works well with the concept of casualties. The development of 5.56 was done in order to make a lightweight rifle that could be used accurately while in automatic firing modes, because being able to shoot one pretty lethal 7.62 semi automatically isn't as good at killing if you can spray a slightly lethal round into someones chest with the same accuracy, this should theoretically increase both the odds of killing by supplementing the shooters accuracy or lack there of with increasing the rate at which lethal bullets are fired and subsequently the rate of killing, and having it be lightweight so that you can have how ever many men you have that can dispatch,
[see 1952 June and 1957 Winter/Spring](https://web.archive.org/web/20040209030852/http://www.thegunzone.com/556dw.html)
And this was done after the compromise of the very lethal 30-06 for the 7.62 in order to have an accurate but similarly lethal semi automatic rifle, it was just reported that automatic rifles were more effective at killing then more damaging rifles because they well they shoot more bullets and most bullets don't hit a target. [info comparing different caliber variables](http://www.krtraining.com/KRTraining/Archive/PracticalRangeSmallArms.pdf)

B well I said in the chest, unarmored people hit in the chest with 5.56 should not be alive. 5.56 goes through a metal helmet at less than 500 meters as shown in the most recent source. The closer the target is to a bullet, the less likely they are to have a clean hole in them as yawing and fragmentation decreases with range due to the effects of change in force/time being lower. 5.56 can kill you with most platforms at 900m or less, for reference, hundred meter sprints are well, 100m. Ofc this is a tile based game and therefore distance is hard to define, but I would imagine that must of the time players are fighting zombies with guns between 50-250 meter, and also getting hit by bullets at similar ranges. Of course zombies are not "alive" but they function on a biological basis, until the blob can stitch them into something that works again they are out of commission. There is also a system in game already for poor hits, which should be used instead of making the expected damage lower, and solid non critical hit from a 5.56 in the chest should kill an average unarmored player character outright based on the ranges I gave. In game I have been hit in the chest numerous times but crows or enemies with guns and did not die,same with leg wounds which usually kill you from blood loss instead of outright killing you. If you got hit in the lower torso in the conditions I mentioned with 5.56 you'll die, at least in cataclysm, your entire digestive system will no longer function as there will be a massive cavity in your lower abdomen, that's death, and massive blood loss. Chest shots are considered insta kill because the blood loss to your brain is so immediate its not worth considering it as a death to blood loss. A stomach shot is just a slower more painful death but you're still dead unless god saved you.

C I feel like I gave enough evidence to show that the damage is much too low.

**Comment by Adamas12** [comment]
> Citation Needed on several fronts.
> 
I cited a couple of sources in my previous comment, and there really isn't much data for the effectiveness of 5.56 in close ranged unarmored combat outside of me looking at specific data on active shootings in the US or something since that is the closest thing there is to very short range use of assault rifles vs unarmored people. If more is needed on the effectiveness of 5.56 and killing people in general I can cite those.
> 1. What's the in- game representation of this anyway? I suspect a "good" hit from a 5.56 round to the torso is going to be pretty close to what you're suggesting after factoring in damage multiplication and bleeding.
> 
Good hits should be as damaging as what I'm suggesting, accuracy of players should be slashed (I know it was just slashed for characters with very low skill) but even when accuracy is not dependant on a humans marksmanship and a gun is aimed perfectly at a target, an M16 will start to have less than 100% expected chance to hit at around 180m and at 250m 1 bullet has a ~50/50 chance to hit, [shown on figure 11](http://www.krtraining.com/KRTraining/Archive/PracticalRangeSmallArms.pdf) Players in cataclysm aren't controlled experiments and should be hitting almost nothing at low levels of marksmanship+a specific weapon skill, and should be hitting 50% as good as controlled experiments at median levels of those aforementioned skills. 
> 2. What are the lethality rates for 5.56 anyway?  Seems like something you could source.
> 
Lethality rates are not something that can be easily sourced actually, because there aren't any controlled experiments where we just kill people, war data that is from the field isn't usually released until years later and isn't accurate to what we are modelling as they are armoured and at up to 10 times the ranges in cataclysm, but what we do know is that in those conditions warfare conditions a hit will more often than not kill you, and less armour and range increases this likeliness, which cataclysm simulates most of the time. There has been a lot of debate specifically over the 5.56 calibers effectiveness but the general consensus concluded by NATO is that it kills if you can shoot, so get a "good" hit, on a target within range in a warefare setting. [Here is another source to show that](https://web.archive.org/web/20131012052014/http://sadefensejournal.com/wp/?p=769). Again, I think that player accuracy should be slashed even more and bullet damage should be increased to better simulate reality. Critical hits should be straight up chopping someone in half or having a bullet yawn and leave plate sized gore hole.
> 
> 
> Also, Zombies aren't people.
Well, they can still bleed out and die like people but and do require some organ functionality to be active, I'm assuming that the blob stitches them back together so to speak so that it can operate it's body on a sensible level, and damage to that body without pupling with cause it to take some time to find a way to reconstruct them, so they still need organs and tissue to be active even if they are essentially puppets and bullets figuratively cut the puppet strings.

**Comment by fairyarmadillo** [comment]
The Las Vegas mass shooter killed 58 people with direct fire and wounded 413 with direct fire using mostly AR-15s (there was also some .308 and a .38, but 5.56 was the majority, also many more were wounded in the incident by other means). He was firing into a crowd from some distance which is a bit different from the circumstances we normally see in the game, accounting for the lower mortality rate.

The Parkland shooter killed 17 and wounded 17 people using an AR-15 at close range. The layout of the school and nature of the event meant that he had a very easy time picking targets, who in many cases were trapped and unable to escape or fight back. He allegedly fired 139 shots, and I'm sure that the 34 people he hit were not shot only once each.

The Allen, Texas mass shooter killed 9 and wounded 7 with an AR-15. This was in a mall under conditions not dissimilar to what a player character might encounter.

The Louisville mass shooter killed 6 and wounded 8 with an AR-15. This was at a bank, again in circumstances similar to what the player might encounter.

A single good hit will in most cases bring a zombie low enough to bleed out within 1 minute, so it seems to me like 5.56 is performing better in the game than it does in real life, and against much more durable targets. Zombies need minimal anatomical integrity to function and cannot feel pain or fall unconscious, so it makes sense that they'd keep attacking until brain death or some equivalent process took them down.

As for its performance against the player and NPCs, it only falls short because trauma can't knock survivors unconscious and hemorrhaging doesn't kill them quite as fast as it should. This is more a problem with the health system than the gun's damage.

Lastly, adjusting the damage on 5.56 would make the most common ammunition in the game obnoxiously lethal. Outside of the early game when the player is forced to take bad shots by the long aim times, guns are _ridiculously_ accurate. A shooter with time to aim will pretty much always land good hits with very little variability in damage. I don't think 5.56's damage is wrong, but it might be appropriate to adjust the math in ranged.cpp to give all ranged weapons more swing, so that even a skilled shooter with time to aim would graze or miss the target but could also get more explosive criticals.

**Comment by kevingranade** [comment]
Summary:
You haven't supported your core assertion that 5.56 torso his are invariably lethal. Your sources revolve around whether the military thought 5.56 was good enough to adopt,  not whether it was invariably lethal.
In-game,  5.56 is already roughly as lethal as you're suggesting it should be, so the insistence that is in need of an increase is also unsupported.

**Comment by Adamas12** [comment]
@fairyarmadillo The reason I didn't bring this up is that it's wrong to simulate a guns damage on a good hit vs active shooting cases because we can't know how many of those shots were "good hits" to the torso or head vs hits in the arm legs or poor hits like grazes or bad area of entry (as well as critical hits) if we applied real life damage to what the game is simulating, and a lot of the time we don't even know how many shots were fired. 

In fact what you brought up further supports the change of making guns less accurate but more lethal, most of these shooters have none to very little training and even NATO themselves think that their forces are in general poor marksmen and can't land a good hit. At the end of the day irl its incredibly difficult to hit a target in a serious situation, only a complete psycho or someone who has trained for years can have perfect control and awareness in combat and place their shots to the chest, and that shouldn't be considered s critical hit, since critical hits are more of incredibly good shot placement and/or unexpected exceptionally good yawn/fragmentation of a bullet.

I suggested slashing accuracy as accuracy is waaaay too high as well, the player should not be making shots better than trained and experienced marksmen. even if they have spent a month shooting zombies. A skilled shooter with enough time to aim and hit a target should always kill that target if they are unarmored.

**Comment by Adamas12** [comment]
> Summary:
> 
> You haven't supported your core assertion that 5.56 torso his are invariably lethal. Your sources revolve around whether the military thought 5.56 was good enough to adopt,  not whether it was invariably lethal.
> 
5.56 is a round developed for NATO to be a lethal munition and thus all of my sources that will feature the military in some capacity, what's important is to find valuable information in sources such as discussions and tests on lethality. Every single source I sent argues that the 5.56 is invariably lethal, and that variable leading to bad results is shot placement (not hitting people in their chest) 

> In-game,  5.56 is already roughly as lethal as you're suggesting it should be, so the insistence that is in need of an increase is also unsupported.

No, it isn't, here's a another [source](https://www.thefreelibrary.com/Small+caliber+lethality%3A+5.56MM+performance+in+close+quarters+battle.-a0158733704)that reiterates my point, if you want more just ask. Studies show that 5.56 is invariable lethal, although I will say that only critical hits result in immediate death if hit in the torso, torso hits will usually lead to inevitable death with with bandaging, player characters shouldn't be able to survive these shots any modern day methods that are simulated in game, outside of armour. There's is an overwhelming amount of evidence and studies into 5.56 specifically due to experience problems with it and all findings show that it is the shooters fault for this, not the caliber.

**Comment by fairyarmadillo** [comment]
#66609 for reference. The problem is that the critical hit system guarantees certain outcomes based on aim rating and the weapon+ammo's dispersion score, meaning that with certain weapons you crit every single time, and with others you will never actually crit. 5.56's dispersion is high enough that it can't actually score critical hits like it's supposed to, resulting in its damage potential being too low. If the issue is properly addressed, it will move 5.56's potential damage up into the 90s or possibly higher, but won't make it do that much on every shot.

**Comment by kevingranade** [comment]
*Your source* disagrees with you:
`When they go to the qualification range, if they hit the target anywhere on the E-type silhouette, the target drops. The reality is that all hits are not created equal--there is a very narrow area where the human body is vulnerable to a single shot if immediate incapacitation is expected. Hits to the center mass of the torso may eventually cause incapacitation as the target bleeds out, but this process takes time, during which a motivated target will continue to fight. While projectile design can make a good hit more effective, a hit to a critical area is still required; this fact is borne out by the Medal of Honor citations of numerous American Soldiers who continued to fight despite being hit by German 7.92mm, Japanese 6.5mm and 7.7mm, or Chinese or Vietnamese 7.62mm rounds. A more realistic mantra might be "One well-placed shot, one-kill."
`

**Comment by kevingranade** [comment]
Actually as that is a definitive source,  I'm closing the issue,  we are totally in line with that report.
