### ISSUE TITLE
Hostile mininuke manhacks make unorthodox pets

### ISSUE THREAD

**Issue by Procyonae** [CleverRaven/Cataclysm-DDA#66758]
### Describe the bug

None of the exploding manhacks appear to be detonating possibly due to #64027 giving them PACIFIST whether deployed by the player, an enemy dispatch or spawned in

### Attach save file

N/A

### Steps to reproduce

1. Spawn a mininuke manhack or dispatch
2. Keep it as a pet forever

### Expected behavior

KABOOM!

They should detonate when near a hostile (potentially only when out of range of their dispatch if that wasn't already a thing)

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/45432782/0e2e373b-c002-4360-bea0-7cf69af646ff)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3086 (22H2)
- Game Version: 42285e4 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations]
]

**Comment by Zephanos** [comment]
I took a little bit of time to look into this to see if I could pinpoint the problem, first thing I tried was removing PACIFIST from the drone flags again but they still wouldn't detonate. After turning on debug mode I found this message was popping up:

![monhackinvalid](https://github.com/CleverRaven/Cataclysm-DDA/assets/106233031/4d195803-9d7a-442b-bcdd-6db155e12448)

which seems to be from this function

https://github.com/CleverRaven/Cataclysm-DDA/blob/f43f0444abd23be29212bf6f548eaa88d9110d73/src/monattack.cpp#L5340-L5348


I don't know C++ well enough to see if anything immediately wrong with these lines but it could also be related to #66161 since use_action for explosives got reworked.

**Comment by Procyonae** [comment]
That could be it, I figured it was unlikely your PR did it without you somehow noticing, I just couldn't find any other relevant ones from a quick search

**Comment by Zephanos** [comment]
All good I'm glad that it pinged me cause I love the dispatch conceptually and I'd hate to see its mechanics bugged. I might take a look at fixing this if I get some free time and someone else hasn't already fixed it in the future, though I am pretty novice when it comes to c++ so it might be a challenging lol.

**Comment by Hirmuolio** [comment]
That is few too many `// HACK: HORRIBLE HACK ALERT!` on the code.

Probably easiest way to fix is to define new grenades that are used by the manhacks only that have same use_action definitions as old grenades. 
So `"use_action": { exploson stuff }` instead of `"countdown_action": { explosion stuff }`.
Some of the item IDs are hardcoded in code so those would need to be updated. But other than that there wouldn't need to be any c++ changes.
