### ISSUE TITLE
Instability is a bad system

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#66768]
### Is your feature request related to a problem? Please describe.

Instability is not good for a variety of reasons.
- It encourages waiting around doing nothing for huge periods of time to get optimal mutations.
- It lets you completely avoid the most negative mutations of any tree. Some mutations are bad enough that they make entire trees unappealing singlehandedly but being able to mutate basically risk free is lame and not at all matching the monsters we see in game. It's also highly unintuitive, such as how you can get Carnivore (-4) as a prerequisite for Predator (3) at low instability.
- It inherently discourages adding "flavor" mutations to the game because every time you get one of those mutations you are set back another 4-8 days. For example if you want to add more intermediate mutations to a tree, it makes it "weaker" because you spend more time changing slowly and then have to sit around twiddling your thumbs to get to the good part. It also makes you doubly "punished" for getting a mutation you don't want, because now you have to wait around a lot longer, which is again super boring. As you get a "bad" mutation, you're more likely to get even more "bad" mutations, when it should probably be the opposite with your body aiming towards some kind of equilibrium point where you can't have too much good without some bad but also won't just keep getting bad and get locked into a downward spiral.
- It makes the system boring. Every mutant homogenizes around the same set of "perfect" mutations: +2 to all stats, pretty, etc, because a lot of the conflicts you get from another tree (like hideous deformity) never happen
- It highly encourages you to rush one of the few specific trees that gives you robust genetics (usually alpha) so that you don't have to spend as long waiting between each mutation. This combos with the above point.

### Solution you would like.

There are so many solutions but I think all of them will require making the current system basically obsolete. Here are some I can think of off the top of my head.
- True random again like before, no instability at all.
- Instability never decays no matter what, but has a different scaling factor of some kind.
- Instability as it is now, but you always have a chance of a bad mutation immediately.
- Mutations always try to balance your "total" at 0 total trait points from mutations.
- Thresholding always requires bad mutations and can't be done with just good ones. Lock more good stuff behind the threshold.
- Make bad mutations prerequisites more often (such as the old removed behavior where you need to go Weak stomach -> nausea -> vomitous in order to turn it around and get Intestinal Fortitude and stop vomiting so much). More "growing pains" mutations.
- More of a reason to stay "pure" such as enemy "malmutators" (like Neqoxecs from DCSS) that give you bad mutations, which means that if you want to use purifier you're best off doing it while already baseline human so you don't have to repeatedly undo your work.
Etc. I'm sure there's a good solution that isn't the current way of doing things.

**Comment by fairyarmadillo** [comment]
I also don't like instability as a system, but let's assume we're not going to rewrite mutations again. Here's my solution:

1) Every neutral or beneficial non-human mutation should raise your minimum instability. It should not be able to decay below this number.

2) At specific breakpoints, you should be forced to take a negative mutation. Purifying this mutation should not be a get out of jail free card.

3) We should consider adding some kind of noncraftable lab-only drug which temporarily grants the effects of Robust Genetics, but does not stack with it. This would stop every mutant from feeling like they need this trait, while not totally obsoleting the trait itself.

Now, people are still going to optimize, and to an extent that's completely fine. Looking at the list of mutations and trying to figure out how to get the best greens and the least bad reds is fun, and it is exactly what XEDRA would have been trying to do in creating their abominations. Similarly, if someone rolls nomad and really feels like they have to purify it off to try to get a less bad negative, then more power to them. That kind of thing is also a reasonable part of the process, and no matter what they do they'll still have some reds.

Additionally, the current system causes purifier and mutagen to take quite a bit of time to work, so even if you just purify off your carnivore or whatever you got, you're still going to have to deal with it for a day or two, or potentially longer if you're waiting for instability to go down. I think that's enough to get the vibe across and successfully challenge the player.

Trying to balance mutations around points is probably not going to work, as points have largely been discarded. True randomness is a recipe for people just getting locked into chugging mutagen and purifier. Relying solely on prereqs is going to go poorly because we've seen that people can abuse mutation types to ensure they get what they want. It would also lead to much more cookie-cutter mutants, which I think should be avoided at all costs.

A lot of the body horror and lifestyle flavor are tied up in the red mutations. Trees and cows are supposed to move super slowly, but they don't because everybody just takes a solid wall of green mutations. Spiders are supposed to be light sensitive, fish are supposed to be thirsty, etc.

**Comment by Maleclypse** [comment]
I've proposed this before and I'll propose it again here.  Bad mutations should always be a possibility and instability should control the chance of you mutating something outside of the category you have vitamins for.

**Comment by Maleclypse** [comment]
~~True random again like before, no instability at all.~~  Not happening I'm pretty certain.

>Thresholding always requires bad mutations and can't be done with just good ones. Lock more good stuff behind the threshold.
>Make bad mutations prerequisites more often (such as the old removed behavior where you need to go Weak stomach -> nausea -> vomitous in order to turn it around and get Intestinal Fortitude and stop vomiting so much). More "growing pains" mutations.
Both of the above are easy to do and require no suggestions or planning but can be assumed to be acceptable right now for anyone who wants to do the work.

**Comment by fairyarmadillo** [comment]
> I've proposed this before and I'll propose it again here. Bad mutations should always be a possibility and instability should control the chance of you mutating something outside of the category you have vitamins for.

Instability was implemented to ensure that people could dip into the system without immediately being handed carnivore, mouth flaps, and deteriorating. If we're not going to stick with that as a design goal then we should probably just get rid of instability.

I think we should keep it though. Making mutation riskier the farther you take it feels better than just giving players non sequitor mutations if they dont find some inane way to pass 3 weeks so it can go back down.

**Comment by Qrox** [comment]
I feel we should have more mixed mutations so people may actually try a new playstyle when they get one instead of immediately chugging a jug of purifier to get rid of a purely bad mutation.

> Every neutral or beneficial non-human mutation should raise your minimum instability. It should not be able to decay below this number as long as you have said mutations

And in addition to this, maybe we can make it so that higher instability makes you more frequently develop small "fluff" mutations that do not severely change your stats but still makes your stats more unstable. It's like investment: you get higher profit by taking higher risks. This may also solve @anoobindisguise's point of adding flavor mutations to the game.

**Comment by fairyarmadillo** [comment]
I don't like fluff mutations, especially not if they're just there to push instability as a mechanic. They're pointless clutter on the mutation panel, they make it harder to visualize what's happening to your character, they're confusing for inexperienced players, and most of all they're prescriptive. It's a very freeform system, trying to dictate every little visual feature of a character in a way players can't control is overbearing and less fun. We don't track freckles, cleft chins, widow's peaks, etc. for these reasons.

**Comment by Raikiri** [comment]
I do like that instability allows the player to mitigate risks when they start their mutation process, but it completely devolves into sleepfest later on if you want to exploit it to the most extent.

In my opinion, the best fix is to only recover instability via special serums (loot only, can't craft) and not over time.

**Comment by MorvarchPrincess** [comment]
I like the concept of beneficial mutations, maybe there's a way to improve them within this system? such as making it cause less instability and take less vitamin, or you just automatically pick up cosmetic ones as a "bonus" along with more functional mutations

**Comment by Standing-Storm** [comment]
There's two things I think that are mostly currently unused that could make instability better.

While I wasn't playing when the system was overhauled, I went back and read a bunch of the discussions and they all involved there being multiple ways to reduce instability, so that the player would have an active choice between waiting (safe, boring, takes forever) and going on some kind of mission to secure a piece of mi-go biotech or contact triffid exiles or find Dr. Maiar's hidden forest lab where he continued his experiments after escaping from XEDRA or whatever (exciting, risky, takes much less time). But no active options were ever implemented, so there's no interesting choices to be made. 

The other is the "vitamin_cost" field implemented in https://github.com/CleverRaven/Cataclysm-DDA/pull/55233 with a default of 100 that every single mutation still uses. It'd be a huge effort to go through and audit the mutations, but if cosmetic mutations had a lower vitamin cost (and thus gave lower instability) it wouldn't feel so annoying to get them, and if mutations that more drastically changed the body had a higher vitamin and thus instability cost, it would be much harder to get only positive powerful mutations with no downsides. 

Better would probably be if vitamin cost and instability were separated and instability were based on how drastically the body was changed while vitamin cost was relatively constant, to prevent people from trying to get the absolute minimum vitamins necessary for a single mutation into their body and then waiting out the instability after a good one.

**Comment by cmugik** [comment]
In the spirit of not overhauling or replacing the system but making a smaller change that might address some of these issues, I have a proposal: Non linear stability gain (as in, the rate at which instability decreases increases as your instability gets higher).

The only reason to continue after the first 1000 genome points is because you are impatient - you get bad mutations, and you still have to wait for all the points to go away start mutating good mutations again, so you'll have to wait twice as long if you want to return to 0.
If there was non linear regain of the genome points, it would mean there's slightly more reason to keep going when you are risking bad mutations, which helps address the issue of all-green mutants, while still allowing people to take it very slowly to only dip lightly into mutation trees.
You would still be risking bad mutations, but by doing so it would allow you a higher long-term RATE of mutation overall, not just a single offset towards more-mutatedness.
I think having a higher rate of mutation overall is a better way to balance the riskiness of mutating while having a depleted phenotype than having what is essentially a one time boost in your quantity of mutations.
A very tentative rate would be something like doubling the rate of stability gain while slightly decreasing the lowest level - for example,
```
|          | WITH RG | WITHOUT RG |
|----------|---------|------------|
| 0-1000   |   10    |     20     |
| 1000-1500|   20    |     40     |
| 1500-2000|   40    |     80     |
| 2000+    |   50    |    100     |
```
This could also just be done as a function of the instability, like (Instability*0.95) every day, (which would be 50 at 1000, but only 25 at 500, meaning that your instability probably would never go back to 0 after you start mutating, but you still have a soft start where you don't end up with bad mutations right away.
It could also be done with different coefficients for different levels of instability.

**Comment by fairyarmadillo** [comment]
No matter what you do, if a way to mutate without getting red mutations exists, people will always pick that. We have to address that issue imo.

**Comment by TrueChevaleresse** [comment]
I'm personally a fan of the idea of more mixed traits. They're more interesting than just becoming stronger or faster or whatnot, and you can still do optimizing for a playstyle with them since many are still more good than bad.

**Comment by cmugik** [comment]
@fairyarmadillo I think a non linear instability decrease addresses that issue - it becomes unfeasibly difficult to mutate more than just a little without getting SOME red mutations if you tune it correctly, especially if you use a decay coefficient of .97 or something.
For example:
mutate your first 15 mutations - you have 1500 instability points. for 1500 to 1000, you have a *.97 daily instability decay, meaning you go 
<details>
  <summary>A lot of steps</summary>
  
Step 1: 1470.0
Step 2: 1440.6
Step 3: 1411.7879999999998
Step 4: 1383.5522399999998
Step 5: 1355.8811951999996
Step 6: 1328.7635712959996
Step 7: 1302.1882998700796
Step 8: 1276.144533872678
Step 9: 1250.6216431952244
Step 10: 1225.60921033132
Step 11: 1201.0970261246935
Step 12: 1177.0750856021996
Step 13: 1153.5335838901556
Step 14: 1130.4629122123524
Step 15: 1107.8536539681054
Step 16: 1085.6965808887433
Step 17: 1063.9826492709683
Step 18: 1042.7029962855488
Step 19: 1021.8489363598378
Step 20: 1001.411957632641
Step 21: 981.3837184799881
Step 22: 961.7560441103884
Step 23: 942.5209232281807
Step 24: 923.670504763617
Step 25: 905.1970946683447
Step 26: 887.0931527749777
Step 27: 869.3512897194781
Step 28: 851.9642639250885
Step 29: 834.9249786465867
Step 30: 818.226479073655
Step 31: 801.8619494921819
Step 32: 785.8247105023382
Step 33: 770.1082162922914
Step 34: 754.7060519664456
Step 35: 739.6119309271166
Step 36: 724.8196923085743
Step 37: 710.3232984624028
Step 38: 696.1168324931548
Step 39: 682.1944958432916
Step 40: 668.5506059264258
Step 41: 655.1795938078973
Step 42: 642.0760019317394
Step 43: 629.2344818931045
Step 44: 616.6497922552425
Step 45: 604.3167964101376
Step 46: 592.2304604819349
Step 47: 580.3858512722961
Step 48: 568.7781342468502
Step 49: 557.4025715619132
Step 50: 546.2545201306749
</details>

This can be very easily tweaked so a player essentially has an "entry" into mutation where they aren't immediately going to get carnivore and mouth flaps, but makes it so waiting to just get good mutations is very unfeasible, and slightly encourages mutating more often without getting rid of the downsides of that (possible bad mutations). 
LMK if you think it's reasonable or has issues - if it seems like it might be worth exploring more I'm sure I could turn it into a PR/code in an hour or two? I haven't read over the relevant sections of the repo but I can't imagine this would be very difficult.
It could also be paired with a non step-based chance of mutating good or bad mutations, but IDK if that's beyond the scope of this discussion. e.g. 0-500 instability has 0% chance of mutating bad mutations because it's very hard to get back there after you first mutate (you can see at the end you're barely losing 10 points a day approaching 500) but afterwards it scales from 0-75% or something (affected by the number of mutations left in a pool as well maybe?) from 500-2000

**Comment by fairyarmadillo** [comment]
I have been talking tl @anoobindisguise about this so I'll ping them. Your idea sounds good to me but I am pretty bad at math.

**Comment by anoobindisguise** [comment]
So I think the best way to salvage the instability system would be to make it be a "tradeoff", where you can have relatively few mutations but have them be good ones, or have many mutations but have them be a mix of good and bad.


One thing we could do is set base daily decay to 100 * ( instability / I50 ). 
(I50 is the variable in mutation.cpp which is set to 2800, the 50% chance of a bad mutation) 
what this does is, if you have ~100 instability, you lose ~4 insta per day. At ~500, it's ~17 insta per day (1 mutation/week). At ~400, it's ~ 14/day. (2 mutations/3 weeks). At 800 instability, you lose 28/day. At 1400 you lose 50/day. Then set "bad mutation chance" to start at like, idk, 500 or something (5 muts "for free") optionally give a minimum bad mut chance of 1/20 or something. Or make only the first mutation free. IDK, balance is hard. If we did "chance of bad mut = 0.02% per point of instability" you'd hit 50% at 25, and the curve would work out differently, but it would mean by 500 insta you have a 10% chance of badmut, but you'd be waiting a painfully long amount of time per mutation if you ever wanted to have like 1-2% badmut odds. Robust genetics could still give a flat negative decay-over-time of like 4/day or something really low. So if you had Robust and *really* wanted to guarantee you just got good stuff you'd be limited to 10 mutations/year.

This would require the vitamin to get some hardcoding (maybe every midnight, apply its daily amount of change rather than doing a decay that compounds every half hour or something) but I think it would lead to a more interesting gamble of good vs bad.

**Comment by fairyarmadillo** [comment]
I think that idea runs into the same problem the current system does, it just has extra steps. We have seen over a year+ of testing that no matter what hurdles you put in their way, players will work incredibly hard to prevent themselves from having fun if it means they can get all green mutations. They will slog through months of waiting, onerous crafting times, and any other obstacle you can think of to wait for their instability to fall off. CDDA players are accustomed to tedium and if the possibility exists to "perfect" their mutation by wasting enough of their IRL time, they will treat it as if it's our design goal, which it isn't.

There's a second undesirable behavior that would come out of the above comment which is that people would quickly figure out where the statistically safe stopping point was, then get to there and stop instead of ever willingly experiencing red mutations.

IMO the only good fix is going to be a system that relies on a quota of X bad mutations per Y good/mixed ones. There are only two systems I can think of that will do this:

**Ratio:** Decide what ratios are desirable for mutant characters. I think 4:1 is a good starting point, so that every fifth mutation will be a bad one no matter what the player tries to do. Under this system, robust genetics could change that ratio to 5:1. There would be no particular need for instability under such a system, but it could be held over as a means to counter people doing the purifier dance by forcing them to live with bad mutations a bit longer.

**Instability floor:** Each mutation could simply add a permanent floor to your instability along with a temporary amount that would eventually decay at whatever rate felt appropriate. Purifying any of these mutations off would change the permanent instability points associated with that mutation into temporary ones. This IMO is a worse solution because it would still reward a very tedious playstyle in a way that isn't good fun or good simulation in and of itself.

**Comment by cmugik** [comment]
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/54971369/f4aa245a-3a89-4555-8e86-ff50d465e9be)
Quick graph I made to demo the decay over time. I started making it before I read your comment and just came here to post and saw it (so I added the "I50 model") - I think it helps visualize the changes in functionality, which for this method is actually relatively low imo, but still better than the current version. 
I also made this version with an instability floor that increases each time (in a way that "pushes" up the curves of the decay models)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/54971369/3bf6e2b6-bace-4167-aa60-2924acb97b35)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/54971369/950e04ab-be4f-4b1e-a9a5-6c6d4e7ae9d2)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/54971369/140c61d1-455a-4e9b-8710-77b289ee0584)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/54971369/ea24cfbd-ead8-4c12-a81d-0fb0ba27cdf4)

**Comment by fairyarmadillo** [comment]
I have witnessed players sitting in their base spamming the button that eats lard and waiting until midnight over and over again for weeks at a time for instability to go down. You might say to each their own, but the players I have seen doing this were complaining about how tedious it was, it's just that the alternative (playing sub-optimally) feels even worse for a lot of players. If a "perfect route" exists, a certain subset of people will not be willing to tolerate anything else.
