### ISSUE TITLE
Repeatedly getting "Setting terrain t_hole at X where furniture is f_rubble. Terrain is_open_air."

### ISSUE THREAD

**Issue by alfredbaudisch** [CleverRaven/Cataclysm-DDA#66822]
### Describe the bug

Playing for the first time, exited the gas station where I started, moved to the north and when I started moving to the west, I get this error constantly. 

It was not only at `(10,114,0)`, but when pressing space to continue, the error keeps popping up for different coordinates.

```
 DEBUG    : Setting terrain t_hole at (10,114,0) where furniture is f_rubble.  Terrain is_open_air
If this is intentional, set the ALLOW_ON_OPEN_AIR flag on the furniture

 FUNCTION : bool map::ter_set(const tripoint&, const ter_id&, bool)
 FILE     : src/map.cpp
 LINE     : 2114
 VERSION  : 96c7690
```

Then when reloading the save game again, I get this one:

```
 DEBUG    : error: item condom cannot fit into pocket while loading: item is too heavy

 FUNCTION : void item_contents::combine(const item_contents&, bool, bool, bool)
 FILE     : src/item_contents.cpp
 LINE     : 705
 VERSION  : 96c7690
```

### Attach save file

[Fay-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12016086/Fay-trimmed.tar.gz)

### Steps to reproduce

Honestly, I don't know whether it's reproducible. I started the game with **everything random**, and as said above, as soon as I left the gas station where I started on and started moving in the world, I got the errors.

### Expected behavior

I'd expect to these errors to not happen in the generated world?

### Versions and configuration

- Windows 10
- v: `96c7690`
- Tiles
- English

### Additional context

- [debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/12016128/debug.log)
- [options.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/12016122/options.zip)

**Comment by RenechCDDA** [comment]
Sounds like #56242 but that should be resolved, and your version is post-fix. (Also not seeing any fires in your save game, so different root cause)

I'm not able to reproduce the error regardless of what direction I move in after loading?

I checked the map coordinates - *something* happened to the house, but it's not happening anymore.

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/84619419/d15c9e0d-23d6-401b-8fe1-289b2ca3891f)

**Comment by anoobindisguise** [comment]
One weird thing about this is that whenever you save and quit with these holes in the reality bubble (they show up most often in collapsed towers, the tcl armory, libraries and 2-floor microlab elevator rooms in my experience) the holes become "sealed" and solid again.
If you try and descend into one of the holes and it isn't over another room (like in collapsed tower you can use the holes to skip to the nanofab room or you can climb into the armory in tcl) it puts you inside solid rock or solid earth instead of an empty space and it becomes impossible to escape because there is a roof over your head so you cannot ascend despite being able to climb down.

**Comment by casswedson** [comment]
gonna /confirm this release blocker, and can someone revert the move from `Proposed Release Blockers to Completed` by the actions bot
