### ISSUE TITLE
Opening crates with integrated toolset uses absurd power

### ISSUE THREAD

**Issue by FlyingVolvo** [CleverRaven/Cataclysm-DDA#66875]
### Describe the bug

The power usage of opening a crate is in excess of 200 kJ  _per crate_

### Attach save file

N/A

### Steps to reproduce

1. Make character with integrated toolset and at least 500 kJ power storage
2. Find a crate
3. Open it
4. See your stored power

### Expected behavior

That opening a crate would not have similar power usage of the probability travel CBM.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.3086 (21H2)
- Game Version: 634a254 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Extra Mutated Scenarios [extra_mut_scens],
    No name () [],
    Translate Complex Dialogue [translate_dialogue],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by rty275** [comment]
The game also defaults to using the toolset over a hammer in the inventory even though they both only have prying 1, which is a waste of power for absolutely zero gain.

**Comment by anoobindisguise** [comment]
Ok so the issue is that for no real reason the crowbar use action is hardcoded to use power for every second spent prying if the tool has a charges_per_use despite the fact that there's no crowbars that use power and it doesn't even make sense for crowbars to use power in basically any case. But also ALSO you can't just replace "CROWBAR" with: { "type": "CROWBAR_WEAK", "ammo_scale": 0 }, because even though it's valid JSON the ammo scale doesn't factor.
`void prying_activity_actor::do_turn( player_activity &/*act*/, Character &who )
{
    std::string method = "CROWBAR";

    if( tool->ammo_sufficient( &who, method ) ) {
        int ammo_consumed = tool->ammo_required();
        std::map<std::string, int>::const_iterator iter = tool->type->ammo_scale.find( method );
        if( iter != tool->type->ammo_scale.end() ) {
            ammo_consumed *= iter->second;
        }
        tool->ammo_consume( ammo_consumed, tool.position(), &who );
        if( prying_nails ) {
            sfx::play_activity_sound( "tool", "hammer", sfx::get_heard_volume( target ) );
        }
    } else {
        if( who.is_avatar() ) {
            who.add_msg_if_player( m_bad, _( "Your %1$s ran out of charges." ), tool->tname() );
        } else { // who.is_npc()
            add_msg_if_player_sees( who.pos(), _( "%1$s %2$s ran out of charges." ), who.disp_name( false,
                                    true ), tool->tname() );
        }
        who.cancel_activity();
    }
}`


This is the responsible code which is really weird because it looks like it should factor ammo_scale. but it doesn't. ????
