### ISSUE TITLE
Kukri tool qualities

### ISSUE THREAD

**Issue by JeveGreen** [CleverRaven/Cataclysm-DDA#66881]
### Is your feature request related to a problem? Please describe.

I recently noticed that despite being a fully functional knife, it only has cutting quality 1, instead of 2 like almost all other knives. This got me thinking that the kukri is also used as a wood cutting tool similar to a hatchet, and should have some ability to cut trees.

### Solution you would like.

Update the kukri's tool qualities, giving it cutting 2 and wood cutting 1.

### Describe alternatives you have considered.

Simply giving the kukri cutting 2 without giving it wood cutting qualities.

**Comment by NetSysFire** [comment]
I have to disagree with that one. It looks like it would handle itself awkwardly enough that cutting with it is complicated same for wood cutting.
As the person who segmented cutting into 1 and 2, I also made e.g katana cutting 1 instead of 2 because it is definitely not made for this and neither is the kukri.

**Comment by fairyarmadillo** [comment]
@NetSysFire I believe you may be mistaken. Kukris are a type of machete specifically designed for camp work. That they also function well as combat knives is sort of an accident of design. They are frequently sold and used as tools for doing all kinds of cutting. You can use them for food prep, cutting wood, cordage, etc. The forward angle makes them better at this, not worse.

https://youtu.be/W5nnATKBAJ0
