### ISSUE TITLE
Add Synthetic Fabric/Nylon padding to Kevlar Firesuit

### ISSUE THREAD

**Issue by Kantonine** [CleverRaven/Cataclysm-DDA#66896]
### Is your feature request related to a problem? Please describe.

The Kevlar Firesuit is only made from Nomex (2mm) and Kevlar (1.3mm+ 90% 1mm). when compared to the other Kevlar jumpsuits available, the Firesuit lacks a 0.3mm layer of synthetic fabric padding.

### Solution you would like.

add a 0.3mm Synthetic Fabric Layer to the firesuit, to bring it in line with other kevlar jumpsuits

### Describe alternatives you have considered.

disregard if necessary, idk if the fire gear is being reworked into something else or not

**Comment by anoobindisguise** [comment]
The firesuit should have something to shield its aramids from UV degradation. It should not be nylon, because while nylon is good for UV protection it sucks when you have to deal with fire. The firesuit should probably be made with leather, which is stiffer but far far more tolerant to fire. That's kind of the price you pay to turn turnout gear into combat capable armor though.
