### ISSUE TITLE
*Many* "Old Lab" spawning on surface(?!)

### ISSUE THREAD

**Issue by RenechCDDA** [CleverRaven/Cataclysm-DDA#66986]
### Describe the bug

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/84619419/26a5f222-1cdf-401a-b1d4-8ce2474be8c3)

### Attach save file

[EFFECTS-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12078676/EFFECTS-trimmed.tar.gz)

### Steps to reproduce

Load save

Behold surface lab

### Expected behavior

Lab of super-secret xedra things should probably be hidden underground like I always remember it being

### Versions and configuration

- OS: Windows
    - OS Version: 10
- Game Version: d7f9f9e1406233997b04190a44b0371ec49e6c27
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations]
]

### Additional context

Probably due to #66876

~~Pre-emptively blaming~~ Requesting the attention of @Procyonae

**Comment by RenechCDDA** [comment]
The development discord says that this was apparently always possible but extraordinarily rare?

However I see **two** of them in my current OM in a new game. And this is the only OM or new game I've loaded since. So very, very suspicious.

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/84619419/d1837ae6-e3ba-48e2-8dfc-c0a9eefc7a2d)

**Comment by RenechCDDA** [comment]
The first one has an anthill *nearby* but.... wow something seems wrong here.

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/84619419/fccb028e-1c60-4e7b-9cbb-126fd8a02b8c)

**immediately downwards**
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/84619419/af2bb52a-ce61-4229-90b6-ccda007be41a)

No anthill tunnels, nothing bisecting it, no presence of ants below the surface:
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/84619419/a1893ff6-e22a-4641-8b15-7930e49ac855)


2nd surface lab in first OM has no ants nearby, at all.

**Comment by Procyonae** [comment]
I don't really get how #66876 would've broke anything when it shouldn't change any existing behaviour but I'll have a look.
Surface "Science Lab"s are just what most labs used to be though and still spawn every maybe like 5 OMs on average idk how you've never seen one before lol.

**Comment by anoobindisguise** [comment]
Lab stairs have been extra super duper broken lately, I know I didn't use to take a flight of stairs upwards into a pool of water (somehow) but it happens in more than 50% of labs at least once now.
You can get multiple labs per OM if you roll separate labs (Ice labs, anthill labs, house basement labs, central labs, prison labs all are separate for the purposes of OM uniqueness).
Ant labs are broken because they don't actually spawn ants in the first level anymore. They used to, but now they don't, no clue when that broke.
Once someone familiar with mapgen makes microlab vaults for Nanofab and Laserguns we can probably finally delete the labs entirely. CVD is not something to worry about, because it's magic and is slated for removal anyways.

**Comment by Procyonae** [comment]
I fixed a case of stairs below ponds but ye they're just kinda broke, they intersect "lab subway"s wrong bc they do om_match_type contains checks for "lab" too so they think they don't need walls

**Comment by alp7292** [comment]
they never removed from surface
