### ISSUE TITLE
Monsters which "use darkness to regenerate" can regenerate in light

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#67027]
### Describe the bug

Monsters who regenerate in darkness, such as the unseen hunter, can regenerate in broad daylight. This is because the check for regeneration requires a light level of less than 10,000 (floodlight) which is brighter than broad daylight by a considerable margin.

### Attach save file

n/a

### Steps to reproduce

1. Spawn an unseen hunter in daylight.
2. Injure it somehow.
3. Observe it "using darkness to regenerate" despite no darkness.

### Expected behavior

They should use darkness to regenerate and can't do that under a heavy duty flashlight or whatever.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.1992 (22H2)
- Game Version: b549de5 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations]
]

**Comment by Hirmuolio** [comment]
I think the equation was typoed.

`static_cast<int>( 50.0 *  std::exp( - light * light / 10000 ) )  > 0`

e^x is always positive for all real numbers.

**Comment by RenechCDDA** [comment]
Sure looks to be bugged, but it's unclear to me what the intended formula is supposed to be.

**Comment by db48x** [comment]
The formula is and isn’t wrong. 

It isn’t a formula to determine _when_ the thing heals, but how much HP it regains. It is true that e^x is always positive, but the formula is cast to an integer. Bright light results in a very small (but positive) number from the formula, which is then rounded to an integer. If the result is zero, then no healing needs to be done. A minor rewrite would make that much clearer.

There is a comment in the code that states that the scaling factor in the formula was chosen so that no healing is done within 20 tiles of a floodlight. A floodlight creates 8000 light in its own tile, which then drops off with increasing distance. 20 tiles away the light level drops to 203, and the formula results in a value less than one at a light level of 203 so the healing does indeed drop to zero at that point.

Unfortunately it appears that daylight at noon in clear weather is a light level of 127.5. This lets the monster heal 10 HP, which is pretty counterintuitive. You can see this on this graph:

![Screenshot from 2024-01-06 09-59-51](https://github.com/CleverRaven/Cataclysm-DDA/assets/228849/fd3957d2-7ed4-49c6-8b1d-56f0ea2571f9)

If the intent is for the thing to only heal in real darkness, then the scaling value needs to change.

It appears that any tile with a light level greater than 10.0 is considered to be “bright”. It goes to “very dark” at 6.0, with “cloudy” and “shady” in between. Tiles at or above 10.0 are drawn in full color. Another part of the code calls a light level of 5.0 “dim”, and indicates that no reading or crafting is possible below that. It is certainly possible to change the formula to scale the damage to zero at a light level of 10.0, which would allow the player to easily see where the monster can heal:

![Screenshot from 2024-01-06 10-27-19](https://github.com/CleverRaven/Cataclysm-DDA/assets/228849/bca7b4bc-7b7a-4c58-9f4e-985615f02a03)

Note however that no tile is ever has a light level less than 3.5, so that cuts off the top ⅖ of the healing range. A small tweak to the formula could fix that:

![Screenshot from 2024-01-06 10-31-31](https://github.com/CleverRaven/Cataclysm-DDA/assets/228849/84645223-520c-4b22-8406-a36172fa7a84)

Note also that the light from a flashlight alone disables this monster’s healing out to about 16 tiles with these formulas. That could be undesirable, but a flashlight generates a light level of 300, so what can we do about it?

I see that there is also a PHOTOPHOBIA effect that kicks in at a light level ≥30.0. We could scale it so that the healing effect kicks in below that same level:

![Screenshot from 2024-01-06 10-37-59](https://github.com/CleverRaven/Cataclysm-DDA/assets/228849/b29499ef-32e3-47d8-8f2a-4e08049f6f75)

Assuming that we don’t want to change how daylight works, that the PHOTOPHOBIA level is acceptable, and that we want the code to be more readable, here is how I would change it:

```c++
if( type->regenerates_in_dark ) {
    const float light = get_map().ambient_light_at( pos() );
    // Magic number 180 was chosen so that healing drops below 1
    // HP at a light level of 30, the same level where PHOTOPHOBIA
    // would start.
    int ΔHP = ( light >= 3.5 ) ? 50 : static_cast<int>( 50.0 * std::exp( - std::pow( light - 3.5, 2.0 ) / 180 ) );
    if( ΔHP > 0 && one_in( 2 ) && heal( ΔHP ) ) {
      add_msg_if_player_sees( *this, m_warning, _( "The %s uses the darkness to regenerate. (%d)" ),
                              name(), ΔHP );
    }
}
```

We could also brainstorm a few more messages, so that we could differentiate a lot of healing in full darkness and a little healing in the partial light from a window or flashlight 10 tiles away.
