### ISSUE TITLE
Fire Axe can be stored in backpack.

### ISSUE THREAD

**Issue by XchiTea** [CleverRaven/Cataclysm-DDA#67041]
### Describe the bug

Fire axe can be stored in a backpack which not in the "can be stored" list.

### Attach save file

pass

### Steps to reproduce

1. Spawn a fire axe and a backpack. 
2. Wear the backpack
3. Pick up the axe

### Expected behavior

The "can be stored" list of fire axe should includes Backpack.

### Screenshots

![11](https://github.com/CleverRaven/Cataclysm-DDA/assets/78393316/74bd2b9f-4c30-4cab-b363-c42b39eee639)

![22](https://github.com/CleverRaven/Cataclysm-DDA/assets/78393316/1aad338b-1bc6-4268-9d21-885715432609)

### Versions and configuration

cdda-windows-tiles-x64-msvc-2023-07-20-0413

**Comment by teapot156** [comment]
That list is just for holsters. Many backpack's have carabineers or compression straps you can insert a long weapon in at the cost of enc and noise.

**Comment by XchiTea** [comment]
Thanks for reply. I checked more backpack. What I don't understand the most is, there are some kinds of "backpack", like Box backpack, Survivor backpack, can hold fire axe too. But the only "backpack" in the list is Hiking backpack.

Then I went over all the pockets can put fire axe in between Hiking backpack and other backpacks. They look very similar to me: Holster, Additional encu, May fall out, some have Noise, etc.

So my suggestion is either delete Hiking backpack in the list, or put all kinds of suitable backpacks in.

**Comment by RenechCDDA** [comment]
The list is automatically generated, based on the pocket type. 

Box backpack doesn't show up on the list because it lacks a `use_action` of type `holster`.

https://github.com/CleverRaven/Cataclysm-DDA/blob/29fe1f2ca17380e594dbd1bc649a9a8c4fb62557/src/item.cpp#L5596-L5599

I hesitate to call this a bug.

**Comment by kholat** [comment]
The "Can be stored in" should probably be reworded to something like "Can be holstered in" or along those lines for more clarity, because the set of all items that something can be stored in is generally bigger than the set of all items that the same thing can be holstered in. But its semantics really.
