### ISSUE TITLE
Scrap Cuirass not repairable, unlike XL or XS Variants

### ISSUE THREAD

**Issue by Dandy1096** [CleverRaven/Cataclysm-DDA#67172]
### Describe the bug

The Scrap Cuirass cannot be repaired, but XL or XS variants can.

### Attach save file

N/A

### Steps to reproduce

1. Obtain crafting recipe of Scrap Cuirass and XL or XS Scrap Cuirass 
2. Scrap Cuirass cannot be repaired, but XL or XS variants can.

### Expected behavior

I suspect that this is an oversight, since the Scrap Cuirass is likely a much older item than the XL or XS variants. It should be repairable using the same items and tools- Bone Needle, Needle, Wooden Needle, Sewing Kit, or Tailor's Kit with Cotton and Budget Steel.

### Versions and configuration

Version 2023-07-20-0251. No mods or alternate configurations.

**Comment by RenechCDDA** [comment]
The issue is that copy-from isn't copying the `repairs_with` field.

Also not sure `repairs_with` is working correctly - it's pointing at budget_steel which defines scrap as a repair item(below) but it's reporting not repairable.

https://github.com/CleverRaven/Cataclysm-DDA/blob/15f392c113c6900d2f930a63d0a957fd66fcf3c8/data/json/materials.json#L355

**Comment by Procyonae** [comment]
Found the problem no tools can repair budget_steel so it needs another mat to provide tools, will make a PR to fix
