### ISSUE TITLE
The protein ration reduces your health

### ISSUE THREAD

**Issue by EternalLaughter** [CleverRaven/Cataclysm-DDA#67288]
### Is your feature request related to a problem? Please describe.

The protein ration bar you mostly find in shelters, have -1 health, and each one you eat reduces your daily health modifier by -1.
I cannot see a reason for this, as the ingredients list is just fruit and vegetable matter 50%/50%.

In addition, new players who i assume often do the default start would eat these, and have no way in-game of knowing these bars were literally worse then junk food! 

### Solution you would like.

I would except them to taste horrible as the text says, and take my morale penalty, without it also being horrible for your health, and have zero negative health effects.

### Describe alternatives you have considered.

If there is a material reason it's this bad for your health, there should at least be some hint in the text of the item, which currently just tells you it tastes horrible, and gives you morale penalties.

**Comment by GlordXd** [comment]
I was also thinking about this,but i guess there are at least two reasons:
1) it was made for sake of the balance, because usually these protein bars are plentiful in the evac shelters,and without the health penalty they're effectively non perishable food that has a good calories value and a really good vitamins value (the morale penalty is not that big if you think about it)
2) the lore reason is (maybe) the fact that something made out of fruit and veggies is non perishable for a reason, maybe there are some not mentioned chemicals in there that make it seem "good" for health because of the vitamins it has,but actually is nearly poisonous because of the said chemicals?

**Comment by NetSysFire** [comment]
I looked at the git blame. @I-am-Erk added them back in 0.E with health -1. Now that the healthiness system was modified in a pretty major way, it will need an update. Maybe Erk could also say if it would be an okay change to make them less unhealthy or if there are indeed harmful chemicals in them.

**Comment by I-am-Erk** [comment]
I don't see any reason to remove the health penalty. Ultimately the penalties on soypelusa bars are meant to be a game balance feature, and are a little bit tongue in cheek. In universe there's nothing wrong with classifying the bars as junk food; we don't know how they're made or what's in them. Being mostly plant matter doesn't make something healthy... See potato chips for example.

**Comment by EternalLaughter** [comment]
I'd still prefer a no health penalty on them, but I'll take the balance and lore reasoning.

**Comment by Snaaty** [comment]
I've played this game for nearly 9 years now and literally never had to eat these protein rations, I don't think balancing them isi an issue at all.  The morale hit is literally the way to balance these things, is it not? I see no reason how protein rations could be detrimental to your health. Anyway just my 2 cents.
