### ISSUE TITLE
[feature request] activating or consuming something while driving should throw a warning message prompt

### ISSUE THREAD

**Issue by Devengel** [CleverRaven/Cataclysm-DDA#67318]
### Is your feature request related to a problem? Please describe.

as title says, i can't be the only one who did this before, right? it's a bad habit. but so far by miracle i haven't died from it. 

### Solution you would like.

title

**Comment by PatrikLundell** [comment]
There are millions of idiots out there doing all kinds of reckless stuff while (nominally) driving without the cars issuing warnings about it (mostly, so far), so I think it's a fairly accurate representation of the real world. The main difference is that the risk of innocent victims resulting from it is a lot lower in the game.

**Comment by teapot156** [comment]
> There are millions of idiots out there doing all kinds of reckless stuff while (nominally) driving without the cars issuing warnings about it (mostly, so far), so I think it's a fairly accurate representation of the real world. The main difference is that the risk of innocent victims resulting from it is a lot lower in the game.

You ever eat a sandwich and drive?

**Comment by PatrikLundell** [comment]
No. I don't use cell phones while driving and drive out right in front people in roundabouts either, but I've had several encounters with such characters, although slamming the brakes has been sufficient to avoid actually having an accident so far.

**Comment by estebandellasilva** [comment]
> > There are millions of idiots out there doing all kinds of reckless stuff while (nominally) driving without the cars issuing warnings about it (mostly, so far), so I think it's a fairly accurate representation of the real world. The main difference is that the risk of innocent victims resulting from it is a lot lower in the game.
> 
> You ever eat a sandwich and drive?

Certain Foods should be treated like an instrument that gets consumed in the process but you eat it over time ... would be fancy (moving to a place and munching a sandwich)

**Comment by TurtsMcSquirts** [comment]
> There are millions of idiots out there doing all kinds of reckless stuff while (nominally) driving without the cars issuing warnings about it (mostly, so far), so I think it's a fairly accurate representation of the real world. The main difference is that the risk of innocent victims resulting from it is a lot lower in the game.

Distracted driving is dumb, sure. But its portrayal in-game isn't relevant to this post. Even if it had anything to do with it, I don't think most people who eat/drink/whatever while driving take both their hands off the wheel and drive in a straight line without stopping or slowing down until they've eaten their entire meal like a player would currently in-game. Even your average idiot would drive better burger in hand than a cdda character. So saying it accurately represents reality isn't even correct.

Like I said, this isn't even within the scope or purpose of the suggestion. The point is you shouldn't be able to accidentally eat an entire bag of popcorn while driving and not be able to stop it, potentially crashing to death due to a minor menuing error in what is intended to be a permadeath game.
