### ISSUE TITLE
Backrooms: Bashing a door frame will cause dirt to appear

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#67321]
### Describe the bug

Caused by:

https://github.com/CleverRaven/Cataclysm-DDA/blob/5743bd77732d468901c2bdf8eac8f77bbbde859f/data/json/furniture_and_terrain/terrain-doors.json#L1968

### Attach save file

n/a

### Steps to reproduce

1. Bash down a door frame in the infinite backrooms
2. Dirt appears.
3. Magic?!

There are likely other instances of this.

### Expected behavior

Carpet appears.

Maybe there is a way to override `t_null` for a mod, so it would resolve to `t_carpet_backrooms` instead of dirt. This would fix other terrain bash results, too.
Plus given the other allowed map extras it may be a feature and not a bug.
Maybe @TGWeaver or @onura46 know.

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 5cca213 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    The Backrooms [backrooms]
]

**Comment by PatrikLundell** [comment]
As far as I know there is no way to bash "terrain" without specifying exactly which terrain should replace it. I agree it would be useful to have means to use context to determine what the replacement "terrain" should be.

One part of the problem is that a tile supports exactly one "terrain" entry, and that is replaced by anything counted as terrain (such as trees, walls, door frames, etc.). Keeping track of what the natural terrain was (including open air) before something was placed on top of it would help partially, but not fully, as you'd really want to smash a door->door frame->appropriate type of floor->original terrain.

I guess one work around would be to append suffixes to "terrain" and have entries with suffixes override the bash resulting terrain by the terrain resulting from stripping off the prefix, along the lines of <standard_door>_<standard_door_frame>_<concrete_floor>_<open_air>, and have constructions somehow being smart enough to build such chains (with the complications that it would need to be able to distinguish between the construction on top of a substrate and the replacement of something with something else).

**Comment by NetSysFire** [comment]
This is specifically about `t_null` and it globally resolves to `t_dirt` no matter what circumstances it looks like. It would be nice to change that e.g per mod or regional settings loaded. So `t_null` would resolve to `t_sand` in the desert mapgen mod (configured via region settings).

A hack you can do to resolve this issue is to overwrite the t_door_frame entirely but this must be done to all used terrain that sets t_null on bash.

**Comment by Procyonae** [comment]
To add to this prior to this issue I thought region settings default_groundcover was specifically for this (I have no idea what it does instead)

**Comment by NetSysFire** [comment]
This does not matter as the bash result is hardcoded per terrain definition. Setting the bash result to t_region_groundcover or t_region_soil or something would be interesting indeed, but my instinct already tells me that it might not like a terrain group. This has to be tested though.

**Comment by Procyonae** [comment]
I meant wherever it does t_null -> t_dirt in the C++ it should do t_null -> default_groundcover (default_groundcover does appear to be used as a fallback in other places)
