### ISSUE TITLE
Fluff proficiencies - art, writing, etc.

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#67320]
### Is your feature request related to a problem? Please describe.

It would be neat to have fluffy proficiencies that don't actually help you with anything, but let you craft various objects that don't have any practical application. Art immediately springs to mind: painting, writing, singing, etc.

### Solution you would like.

Crafting recipes that advance these proficiencies and/or allow you to produce products like paintings and fiction books.

### Describe alternatives you have considered.

Not a necessary feature. Probably can be accomplished via mod, honestly.

**Comment by S0ZDATEL** [comment]
Paintings and writing could be used in trade, maybe? Maybe an NPC could ask you to draw a portrait of them for a reward, to save a memory of them after they die or something... Singing proficiency could mean you have a good voice, and writing could mean you know the way with words, both of which could give you bonuses with NPC impression and persuasion, and maybe writing could help you with lying...

**Comment by ilovehans10** [comment]
> Paintings and writing could be used in trade, maybe? Maybe an NPC could ask you to draw a portrait of them for a reward, to save a memory of them after they die or something... Singing proficiency could mean you have a good voice, and writing could mean you know the way with words, both of which could give you bonuses with NPC impression and persuasion, and maybe writing could help you with lying...

 It could also be cool to make it, so you can craft/paint a "Survivor Portrait", and when you finish the portrait, you can decide who it is of. This would also allow for you to create something to commemorate a survivor you lost at some point if you could choose from survivors that have died.

There could also be a Photography skill so that professional cameras finally had a use other than high quality lenses and memory cards. Possibly a way to print off photos of people and sell those too, or just sell high quality photos in general. Of course not everyone would buy photos, but in places where people are as safe as can be (think refugee center/forge of wonders) there could be specific vendors that want art.

**Comment by MrHrulgin** [comment]
I don't know how feasible it would be, but I'd love this for quest purposes as well as art. Being able to commemorate my journey and review a photo album would be lovely, and I'd imagine plenty of NPCs would like to be able to see how something held up, be it their house, a local landmark, or a person at a different location.
