### ISSUE TITLE
experimental build 2023-07-31-1032 messes up nutrition and calories in crafted food.

### ISSUE THREAD

**Issue by ampersand55** [CleverRaven/Cataclysm-DDA#67339]
### Describe the bug

Items lose calories and nutrients in build 2023-07-31-1032. See attached screenshots.

### Attach save file

N/A

### Steps to reproduce

Compare saves with items with charges in build 2023-07-31-0609 and 2023-07-31-1032.

### Expected behavior

N/A

### Screenshots

![build 2023-07-31-1032](https://github.com/CleverRaven/Cataclysm-DDA/assets/9817636/55657bfb-bc1c-4810-b7c4-f56f9fdb2da2)
![build 2023-07-31-0609](https://github.com/CleverRaven/Cataclysm-DDA/assets/9817636/e5c44bd8-7949-4639-997a-856e34eeb2b4)

### Versions and configuration

N/A

**Comment by mqrause** [comment]
Losing the charges is very much intentional. They got migrated and will drop as an equal amount of singular items upon most forms of interaction with them.

Losing calories and nutrients is a different issue I didn't consider, though. I'll have to see if I can do something about that. Item components are also just items, so they also lose their charges so only one will be considered for calculating nutrients. But they can't really overflow, because they don't exist anywhere. That only affects previously crafted items.

**Comment by Maleclypse** [comment]
Closing this as it’s an unfortunate side effect of a necessary change. There are things that are broken from this change that can be fixed going forward like inline item groups.

**Comment by Kamayana** [comment]
> 

Shouldn't we keep issues caused by charge removal around? mqrause even acknowledged that losing calories and nutrients is an issue. The title could probably be renamed to refer to that specifically, though, since "messing up charges" was intentional.

**Comment by mqrause** [comment]
Yeah, it could be reopened, although admittedly it's a fairly low priority because of the limited scope of items that are affected. Newly crafted ones will work fine after all.

**Comment by GuardianDll** [comment]
I recall Karol was interested into doing some review PR in food field, but they demand #64722 so they won't need to do it twice
(not like i want Karol to do more work, just mention that we can kill two birds with one stone)

**Comment by mqrause** [comment]
> Reopening in case someone decides to undertake finding a patch for stable to stable migrations.

Oh yeah, stable to stable is a thing, too. Guess I'll up the priority on this a little bit.

**Comment by ampersand55** [comment]
This seems to be fixed now.
