### ISSUE TITLE
Inconsistencies in CBM descriptions and slot usage

### ISSUE THREAD

**Issue by TrueChevaleresse** [CleverRaven/Cataclysm-DDA#67405]
### Describe the bug

Several CBM descriptions appear to be out of date or inconsistent. For example:

1. Automated Surgical Scalpels are stated to be implanted in the user's hands. They do not take hand slots, but arm slots. 
2. Electromagnetic Unit is stated to be in the right hand. The bionic takes left arm slots.
3. Directional EMP is stated to be in the right hand. It takes left hand and arm slots.
4. Fingerhack is stated to be in right fingertip. It takes a left hand slot.

### Attach save file

N/A

### Steps to reproduce

1. Look at CBM
2. See mismatch between description and slot usage.

### Expected behavior

Bionic descriptions should match the slots used. If a CBM needs to take up a particular slot (e.g. most auxiliary weapons taking the left hand slot) then the description should be changed; otherwise their slots should be updated (e.g. the scalpels should probably actually take hand slots.)

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/7243560/0fe5d7c4-5761-4786-8593-652f87ed6639)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/7243560/89eeca8e-3b44-41f2-9305-c3673e7e3f05)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/7243560/655ef62d-1ec7-4c22-bf4c-928885813485)

### Versions and configuration

Experimental version 0731

### Additional context

I'll probably go through these exhaustively later. I'm not directly changing anything, because it's unclear where design intent is in most of these cases.

**Comment by ilovehans10** [comment]
With bionics now coming from Rubrik (I think that's how you spell his name) would it make sense to give an option to install it on either side. Then the descriptions could just say the scalpels are implanted in a hand instead of the left/right hand. The installation option interface could remain the exact same except for every bionic that needs to be installed in a body part that has a side would now have "install fingerhack (left)" and "install fingerhack (right)". This would allow for players to not be locked out of bionics because their left hand is a multitool, but the great gray doesn't know how to make a arm cannon that can be installed on the right shoulder.

I know that irl prosthetics have a sidedness and that you can't just go swapping sides. If they are making these bionics to be installed on all sorts of "people", wouldn't it be safe to assume that their designs plan for some flexibility. I guess another solution if we don't want the CBM box(??) to be installed on either side then could there be a left and right variant of each item.

I have been googling for the last couple of minutes trying to figure out how to do an inline spoiler in Markdown, so if someone can let me know how to do that I would appreciate it.
<details> 
  <summary>Spoiler</summary>
I do know that the eventual plan is to turn people into drones, so they might not be super concerned about if someone wants their tool on the other side. Personally, I believe that this change wouldn't break lore and would improve player experience.
</details>


This might be off-topic, and if it is I can move this to its own issue for discussion.
