### ISSUE TITLE
Smoking fish deletes all its calories.

### ISSUE THREAD

**Issue by TurtsMcSquirts** [CleverRaven/Cataclysm-DDA#67411]
### Describe the bug

When I smoke fish with the basecamp charcoal smoker, it comes out with 0 calories. This only seems to happen with fish. When I smoked some human meat earlier it came out fine.

### Attach save file

[Sisyphus, 2023-08-02 6-02AM-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12252843/Sisyphus.2023-08-02.6-02AM-trimmed.tar.gz)

### Steps to reproduce

1. Observe 0 calorie smoked fish already in inventory.
2. Place raw fillets of fish in charcoal smoker, and light it.
3. Wait 5 hours for fish to smoke.
4. Retrieve 0 calorie smoked fish from smoker.

### Expected behavior

For smoked fish to have 260 calories as is listed on [the guide](https://cdda-guide.nornagon.net/item/fish_smoked). Or even have any caloric content at all.

### Screenshots

![Screenshot 2023-08-03 101712](https://github.com/CleverRaven/Cataclysm-DDA/assets/113976440/86422cae-3de4-453a-8fe5-49f5445de8b1)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3208 (22H2)
- Game Version: 5eaa457 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    <color_cyan>Arcana and Magic Items</color> [Arcana],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    No Hope [no_hope],
    Xedra Evolved [xedra_evolved],
    <color_cyan>Arcana</color>/Magiclysm Patchmod [Arcana_Magiclysm_Patch],
    Mythical Martial Arts [MMA],
    Translate Complex Dialogue [translate_dialogue],
    No Rail Stations [No_Rail_Stations],
    Magiclysm No Class Limit [magiclysm_no_class_limit],
    Xedra Expanded No Class Limit [xedra_no_class_limit],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Tamable Wildlife [Tamable_Wildlife],
    Aftershock [aftershock],
    Bombastic Perks [bombastic_perks],
    Extra Mutated Scenarios [extra_mut_scens],
    Mind Over Matter [mindovermatter]
]

**Comment by Brambor** [comment]
I'm guessing the culprit is #67356

**Comment by Brambor** [comment]
I will give this a go!

**Comment by Brambor** [comment]
Can confirm.
The culprit really is #67356
good: b4c5469620
bad: d3a052e9b7

I will try fixing it tonight.

**Comment by mqrause** [comment]
I don't exactly see what could have caused that in #67356. I've seen similar reports before, but I only tested smoking meat and that worked as expected. Fish should behave the same in theory.

**Comment by EerieEpitaph** [comment]
Happens with dehydrated fruits as well. Zero calories when smoked with a smoker.

**Comment by Brambor** [comment]
I didn't have the time. I will be back on the 14th, but somebody should fix it before then ;)

**Comment by devoured-by-incandescence** [comment]
I'm glad this was already here, it was a tough lesson to learn after smoking two whole cows worth to realize that it deletes calories.

I probably don't need to say this but just in case it needs to be mentioned, this isn't just a problem with fish and fruits, it's literally all food that goes through the smoking racks. Vegetables, meat, fish, and fruit are all I tested and everything came out at 0 calories.

At least now I can make a few thousand 0 calorie pemmican, I guess for the novelty?....

**Comment by devoured-by-incandescence** [comment]
> I don't exactly see what could have caused that in #67356. I've seen similar reports before, but I only tested smoking meat and that worked as expected. Fish should behave the same in theory.

Smoking meat doesn't delete its calories, but smoking meat and fish twice to dehydrate, and once for fruits and vegetables to dehydrate, seems to be what deletes calories. Smoked meat from my smoking racks has the expected 402 calories per item, smoking it again to bring it to dehydrated level is what causes the 0 calories issue.

I hope that helps you fix it, because you *are* technically right - smoking meat doesn't cause the issue. But that's because the issue is from the dehydration step. "In theory" at least ;p

**Comment by mqrause** [comment]
I'm not sure what to make of that exactly. The original report here has a screenshot of smoked fish with 0 calories, so there might be other conditions. I'm not currently working on this, but having reliable reproduction steps would be helpful.

**Comment by rtxyd** [comment]
If you spawn smoked fish or dehydrated fish or dehydrated meat from debug mode, or loot from a house, they get right calories, only craft from smoking racks make them 0 calories.

**Comment by devoured-by-incandescence** [comment]
Yeah, I just cheated in my 1.7k dehydrated meat and fruits to go with my
lard. Feels dirty but also I'm kinda sore about how long I spent
dehydrating everything lmao.

You're right, though - smoked fish actually does have 0 calories for me on
first smoking, not sure how I got confused there. But it's definitely the
dehydration process that deleted the calories for meat, veggies, and
fruits. I'm also mostly vanilla, I only have Magiclysm, BlazeIndustries and
Xedra installed currently, but all 3 OP also has. I'll test without the
mods in a true vanilla world and see if it's one of those messing things up
and report back in a few minutes.

**Comment by devoured-by-incandescence** [comment]
Steps to reproduce:

Done with no mods except the default NPC needs and Portal Storms ignore NPCs, and the DDA data set obviously.

1. Set up either a Smoking Rack with the Construction Menu (*) or by spawning in a Metal Smoking Rack (If you couldn't reproduce it with the Charcoal Smoker item, this is why - the bug is only present when smoking on racks.)
2. 
  A. For Calorie-less dehydrated meat, smoke the meat in the smoker once, wait until it finishes, then reload the Smoking Rack or Metal Smoking Rack once and light it again. 
  B. For Calorie-less Smoked Fish, simply put the fish in the Smoking Rack and light with Charcoal. Fish will have no calories.
  C. For Calore-less Dehydrated fish, simply repeat step B again - it doesn't magically gain calories back or anything.
  D. For Calorie-less dehydrated Fruit or Vegetables, simply put the fruit or vegetables into the Smoking Rack and light. I tried with Tomato, Zucchini, Spinach, Bell Pepper, Lettuce, and Potatos. I feel like it's safe to say it's all Vegetables as well.
  E. Bonus Mode - I threw a tofu in there as well, and it also had calories deleted.


To me, it looks like the smoking rack deletes the calories of items you put into it either on the first go as with the fish, or the second (dehydrating) go if it has two smoking stages. Pretty much as OP and I elaborated, but hopefully this was concise and clear enough for anyone to be able to easily reproduce this.

**Comment by Brambor** [comment]
I reproduced it with the OP's reproduction steps.
And pointed to the bad commit (the one that introduced the bug).
I am rephrasing my previous message, if it wasn't clear before.

**Comment by devoured-by-incandescence** [comment]
Yeah, I'm not really sure how my post was any more "reliable steps to reproduce" as requested than OP and your own reply, but hey whatever

**Comment by mqrause** [comment]
All I was saying was that that there were differing and possibly conflicting reports, e.g. smoking vs. dehydrating, and clearing that up can help identifying and solving the problem.

**Comment by devoured-by-incandescence** [comment]
At the very least, the *only* thing the smoking rack is capable of producing worth eating right now is *Smoked* Meat. Everything else smoked and/or dehydrated from it has no calories.

We know the commit that's causing this, which highly makes me doubt we really need reproducible steps anyways. It really shouldn't be too hard to look at what changes to the smoking rack were made with that commit and either roll them back or fix whatever oversight was included. It's probably a stupidly simple 10-minute fix. 

I have absolutely no programming experience or knowledge but I guess I'll take a look and see what I can do to fix that bad commit

**Comment by ampersand55** [comment]
Smoke meat being the exception most likely has do with with cooked meat (which smoked meat inherits from) having calories set to 402 with nutrient override, and not calculated from ingredients.

Dehydrating the smoked meat also yields 0 calories.

**Comment by EternalLaughter** [comment]
As for the meat, only the first part is fine. An uncooked chunk of meat is 301 calories, and smoked, it's 402.
I'm assuming this is because we're able to extract calories from cooked food better then the raw meat?
But, once you run the meat through the smoker a second time to get dehydrated meat, it gets zero calories/vitamin.

The fish fillets though are worse off. Smoked in a smoking rack it causes them to have zero/0 calories, and zero vitamin.
When you dehydrate those fillets through the smoking rack they still have zero calories and vitamin.

Smoking and dehydrating fillet of fish through actual recipes manually yourself, results in fish with normal calories (260 per)
I am again assuming that the difference between raw calories (195) and cooked (260) is normal.

**Comment by rtxyd** [comment]
@mqrause 
https://github.com/CleverRaven/Cataclysm-DDA/blob/3a3d124fce4699c680175298a29c8c4c2600f0c3/src/iexamine.cpp#L5981-L5981
Annotate this line solve the problem, fish get the right calories. But I don't know if there's another issue, I only know how to test the code.

**Comment by mqrause** [comment]
Pretty sure that'd break when you save and load during smoking, because stuff can't have charges anymore. The issue is in `smoker_finalize`, which still assumes charges exist.

**Comment by rtxyd** [comment]
Well, for me that's a temporary solution, at least smoking racks work, if I don't S/L. Hope this can be fix soon,.

**Comment by rtxyd** [comment]
Another try, I change these two line
https://github.com/CleverRaven/Cataclysm-DDA/blob/3a3d124fce4699c680175298a29c8c4c2600f0c3/src/iexamine.cpp#L5930
to ` item result( it.get_comestible()->smoking_result, start_time + 6_hours, it.count() ); `
https://github.com/CleverRaven/Cataclysm-DDA/blob/3a3d124fce4699c680175298a29c8c4c2600f0c3/src/iexamine.cpp#L5947
to ` result.recipe_charges = it.count(); `

This time S/L didn't delete calories.

**Comment by rtxyd** [comment]
@mqrause It seems back to normal, but I am layman of coding, so it need someone professional, or like you to view.
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/65117312/539ee128-1482-4829-a6d0-61f69309b67a)

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/65117312/0698811e-6b29-43fd-8b1b-fd913be0ae5f)

**Comment by Brambor** [comment]
@rtxyd You can make a PR, the automatic tests will run and see if you broken something else, you already shown (I hope) that this bug is fixed. See if #67356 is still fixed. Then I would say it is good.

I assumed the fix would be like you described, but I have no time till tomorrow to try on a PC.

I think you got it ;)

**Comment by Brambor** [comment]
On another note: It would be nice to make a test out of this. But that can be for another PR, if it is made at all.

**Comment by rtxyd** [comment]
OK I'll try making a pull request. If that's broken, the hope is on your side, I am literally a noob.
