### ISSUE TITLE
Cars should roll over downed creatures.

### ISSUE THREAD

**Issue by Froffy025** [CleverRaven/Cataclysm-DDA#67423]
### Is your feature request related to a problem? Please describe.

Crashing into enemies with a car causes too much damage to the car to be a viable tactic, which feels realistic against crowds. However, for smaller groups of enemies, such as lonely zeds or wasps, it should be possible for wheels to roll over and crush them after downing them with a low-velocity impact, with little damage to the vehicle -- but should also destabilize the vehicle. This makes it so that, while still dangerous to drive into crowds, a survivor can be more realistically capable of dealing with smaller scale threats without destroying their car.

### Solution you would like.

If a creature is down and hit by a vehicle, deal bash damage based on the vehicle's weight, rather than velocity. A regular car should probably do enough damage to pulp most zombies that it rolls over. This could also cause low skill drivers to lose control of the vehicle.

**Comment by VladicusMagnus** [comment]
It would be wise to calculate the strength of car parts. Especially those who are facing. As a result, it will be necessary to calculate the details that follow them. Lots of work, zero benefits. The scheme is the same if I am not mistaken.

**Comment by PatrikLundell** [comment]
Dead zombies are gradually damaged and eventually completely destroyed if you roll over them with a heavy vehicle (a bicycle may be too light: I've seen both (non corpse) items remain undamaged as well as taking damage from a bicycle).
Heavier vehicles require fewer passes than lighter ones, while tougher zombies can take a lot of passes to be destroyed completely. I've used that to "clean up" in situations where I want to eliminate a zombies but don't want to get out of the vehicle and risk getting into melee with the zombies that are still in the area (of course, that also means losing whatever items they dropped).

There shouldn't be any pulping if "low profile creatures run over instead of into" would be implemented, as that implies targeting the damage at specific vulnerable parts, rather than damage to random locations based on exactly where the wheels would happen to roll over the body.
