### ISSUE TITLE
Food dehydration costs have become ridiculous

### ISSUE THREAD

**Issue by jake1203n** [CleverRaven/Cataclysm-DDA#67433]
### Describe the bug

It costs 1,980 dehydrator charges and 500 induction hotplate charges to create a single piece of dehydrated meat. This is way too much power to make the recipe useful.

### Attach save file

[FiorGame-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12259615/FiorGame-trimmed.tar.gz)

### Steps to reproduce

Press &
Press /
Type "dehy"
Press enter
Select the recipe
...why would you ever make this?

### Expected behavior

I don't expect a single piece of dehydrated meat to take 2,480 battery charges to make. That's more than two full medium disposable batteries.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/51016048/3191671d-4d1b-410b-bc4a-7a48138081e0)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3208 (22H2)
- Game Version: 6c7384d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Alternative Map Key [alt_map_key],
    Mythical Martial Arts [MMA],
    Aftershock [aftershock]
]

**Comment by GuardianDll** [comment]
It is intended, you can't power 600 watt thing with any amount of this:
![IMG_20230804_121720](https://github.com/CleverRaven/Cataclysm-DDA/assets/67688115/cf26ccee-7ee0-471e-a29b-9087431e6a8a)
Connect it to your grid to use your vehicle batteries, or use alternative methods that do not consume energy, like propane stove

**Comment by jake1203n** [comment]
"you can't power 600 watt thing with any amount of this:"

OK... I can get behind that, but... why does the default configuration for food dehydrators involve being powered by a battery form factor that isn't realistic for everyday use?

When I found this food dehydrator on the shelf in an electronics store, it had a medium battery in it. It has a compartment for medium batteries. Does that not imply that it was intended for use with medium batteries when it was made? If that wasn't ever possible... why is it designed like this to begin with, when it could have been built literally any other way? It doesn't make any internal sense.

**Comment by GuardianDll** [comment]
\> does the default configuration for food dehydrators involve being powered by a battery form factor that isn't realistic for everyday use

Because option to connect different thing to power grid was added like few weeks ago, and not lot of tools was transferred to this mechanic. Also, previous metod was using batteries, because there was no any proped calculations of how much energy this or that recipe require, which made silly stuff like powering hotplate with small battery, which with current changes transformed into this.
It would be fixed eventually, it's just we can't fix all at once in one day, that's why development build exist

**Comment by jake1203n** [comment]
OK - that makes sense. we are having two different conversations here. I'm thinking of what's internally logically consistent for the world, and you're thinking of what makes sense for a development cycle. both are valid! :)

I think based on what you're saying: cooking items should receive a pass to make sure they're using a power form factor that is appropriate for their actual power needs based on recent development. Is that a JSON thing? If so: I can take a look at it.

**Comment by GuardianDll** [comment]
The very best approach would be if someone jump into <https://github.com/CleverRaven/Cataclysm-DDA/tree/master/data/json/items/tool>, and check all electirc tools, and remove their battery slot if they are corded (maybe also add cordless versions where applicable, so we could have, for example, a battery-powered chainsaw, and chainsaw that uses cord) 
JSON is a markup language, created to be readable both for human and for computer, fairly easy to understand if you have basic computer knowledge. It would be great if you'll fix this

**Comment by anoobindisguise** [comment]
It's best to treat the battery as a battery backup in case of a grid hiccup and not a real power source.
So dehydrating ~300 grams of meat is really power intensive, remember that the dehydrator will run for hours and is about 500w. Based on some recipes I've seen for making jerky in a dehydrator the cost is roughly similar to the cost to dehydrate as is, which means the recipe is probably actually too generous for just a single unit of meat (assumption is dehydrated = 2x jerky/smoked cost) however the survivor probably does this stuff at scale which leads to some cost savings (we cannot do batch energy savings due to code reasons)

**Comment by GuardianDll** [comment]
\> It's best to treat the battery as a battery backup in case of a grid hiccup and not a real power source.

I doubt a lot of appliances has internal battery inside them to handle power outrage, and especially replaceable one

**Comment by jake1203n** [comment]
Question: Is there a larger project to standardize power outputs to power inputs? 

The reason I ask is because an ASRG outputs 131W. It would take five of them to power a single food dehydrator. Or fifteen solar panels. As it stands, an ASRG is not capable of powering a real world Xbox Series S.

**Comment by Alm999** [comment]
> The reason I ask is because an ASRG outputs 131W. It would take five of them to power a single food dehydrator. Or fifteen solar panels. As it stands, an ASRG is not capable of powering a real world Xbox Series S.

I believe, the ASRG in the game was modeled after this one: https://en.wikipedia.org/wiki/Advanced_Stirling_radioisotope_generator
It does indeed have an output power of 130W. But it only weights 32 kg. The explanation for the immensely greater mass of in-game ASRG is that it has additional shielding completely preventing nuclear pollution (unless damaged).

The solar panels are a different issue, however. Current solar panels are comically under-powered. Only 50W for 14 kg? Their performance stems from the earlier game balance: before power consumption rework 50W was actually sufficient, but since then the consumption rates have skyrocketed, while power generation stayed the same, so now we have 14 kg solar arrays with an output sufficient to power up a handheld calculator…

**Comment by jake1203n** [comment]
mmm attempting to update this, is nontrivial to my skillset - I gotta go through all the itemgroups and update the starting charges for the items I removed battery compartments for, or it'll throw a ton of errors. But it's being worked on!

**Comment by kevingranade** [comment]
No evidence presented that there's a problem.

**Comment by Zireael07** [comment]
Problem is, afaik, that food dehydrator takes 600W and the batteries available can't power it and it's not an appliance
