### ISSUE TITLE
Grappling hooks should help with more descents.

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#67447]
### Is your feature request related to a problem? Please describe.

I ran across a crater, and I could see a rail line down at the bottom of it. I had a grappling hook on me, and wanted to use it to descend to the bottom of the pit. But when I use the grappling hook at the edge of the pit it (somehow) extends upwards into space, and when I use it on the open air at the edge, I get:  

DEBUG    : Setting furniture f_rope_up at (66,64,0) where terrain is t_open_air (which is_open_air)
If this is intentional, set the ALLOW_ON_OPEN_AIR flag on the furniture

 FUNCTION : furn_set
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\map.cpp
 LINE     : 1726
 VERSION  : 6c7384d

and if I ignore the message, I see the sad remains of my grappling hook at the bottom of the pit.

If instead I step off the edge or climb down off of it, I fall freely to the floor without the grappling hook doing anything.

### Solution you would like.

I'd like it if I could deploy a grappling hook into open air to allow me to descend safely, and/or it would save me if I was going to take a fall.

### Describe alternatives you have considered.

Not doing anything about it.

**Comment by teapot156** [comment]
As they are now it's kind of strange. It's like a portable ladder. 

So you can place it on the ground and use it to climb up as if you were throwing it up there but when you get to the top, it's still stuck below and now can no longer help you climb. I haven't tested it but I think a rope/grappling hook helps you "climb down", so you'd need 2 grappling hooks to successfully climb up and down safely. It'd be great if the item was looked it since it's very cool to run around with one or have one on you when you need it.

**Comment by AmarinReyny** [comment]
Maybe having the grappling hook create a "hook end" and "rope end" when deployed would help with this? And if deployed on an open air tile, it would have the hook end made on that tile, and a rope end on the tile below it. Also, maybe there could be a way to prevent it from falling, as long as the hook end is adjacent to a tile that isn't open air.

It would also be cool if characters could be prevented from falling if they're on the rope end tile (albeit with a risk of losing one's grip and falling), even if it's on open air, so it'd be like using the grappling hook to go to the floor below, instead of immediately falling through all open air tiles and only landing (probably painfully) on whatever ground tile they reach first.

**Comment by EvanBalster** [comment]
I examined the current code for descent with and without grappling hooks while working on https://github.com/CleverRaven/Cataclysm-DDA/pull/68120, which makes it safe to climb down onto a stepladder among other changes.

Climbing down with a grappling hook wielded will cause the player to place the grappling hook on the floor below and descend with zero risk of injury.  This would *seem* to resolve the issue here, *except*...

Iif the grappling hook was *already placed* on the floor below, it does not aid in descent.  A placed grappling hook is almost identical to a downspout and is similarly ignored when climbing down from a ledge.  Furthermore, the placed grappling hook cannot apparently be removed when the player is on the level above.  (See https://github.com/CleverRaven/Cataclysm-DDA/issues/67420)

**Comment by EvanBalster** [comment]
I implemented this in #68190, but withdrew that PR because I'm breaking it into a few separate pieces (code, balance, fixes/features).  My current contribution is #68265, which lays the groundwork for fixing this.

**Comment by EvanBalster** [comment]
PR #68306 addressed this and was merged last month.
