### ISSUE TITLE
MoM: radiation based powers

### ISSUE THREAD

**Issue by ilovehans10** [CleverRaven/Cataclysm-DDA#67451]
### Is your feature request related to a problem? Please describe.

Lack of mods that interact with radiation in major ways.

### Solution you would like.

I just got super irradiated, and I thought to myself it could be cool to make a radiation shielding/radiation vision powers. When I say radiation vision, it would be a way to see where radiation is by having either a Geiger counter sound or some sort of visual cue. I know that any sorry of radiation removal power would probably be op, but that could possibly be balanced by making the character go through a lot of pain all at once, which could be explained as purging all the radiation at once.

### Describe alternatives you have considered.

Possibly including these in a class like Bio/Vitakinesis as some of the powers would be similar to what those allow.

### Additional context

At the end of the day, I know there are the rules for new powers, and I don't believe this idea violates that at all. I am not well versed enough in the spell json yet to do this in a timely manner, so this idea is adoptable. If no one else takes this on, I plan on pursuing it some day, but I am too busy, probably until mid-winter.

**Comment by Standing-Storm** [comment]
It definitely doesn't violate it because the biokinetic power Sealed System provides radiation resistance (which I should make clearer in the description). 

I have an idea for how to include this in Clairsentience (seeing) and Vitakinesis (curing), and I can definitely get to it before midwinter. IIRC visions options are limited without C++ but there's some things I can do.
