### ISSUE TITLE
Roadkill flag for small animals

### ISSUE THREAD

**Issue by kylesjob** [CleverRaven/Cataclysm-DDA#67464]
### Is your feature request related to a problem? Please describe.

It's always a bit weird whenever my big ass car or truck slows down a bit whenever I drive into a squirrel or rabbit.

### Solution you would like.

Instead of pushing them around, give small enough animals a new flag something like Roadkill where vehicles built with normal frames and above _(maybe light frames too? definitely not extra light frames, tho)_ will instant kill anything with that flag and turn it's corpse into butchery refuse, and prevent any damage from occurring to the vehicle.

### Describe alternatives you have considered.

Comparing weight with calcuations on vehicles vs NPCs to check if something can be roadkilled? Would probably make ramming with death mobiles too strong, though.

**Comment by teapot156** [comment]
Yes, just delete the animal.

**Comment by AmarinReyny** [comment]
I kinda feel like something like this should only apply above a certain speed - like, if you're going at a normal driving speed, it would definitely apply, but if you're just inching along at 4 mph, it shouldn't cause any damage unless you're crushing the animal against a wall, and even that probably wouldn't apply due to small enough animals being able to just go under the vehicle anyway.

**Comment by estebandellasilva** [comment]
> I kinda feel like something like this should only apply above a certain speed - like, if you're going at a normal driving speed, it would definitely apply, but if you're just inching along at 4 mph, it shouldn't cause any damage unless you're crushing the animal against a wall, and even that probably wouldn't apply due to small enough animals being able to just go under the vehicle anyway.

Squirrels probably dont care if you drive over them with 1/10/100 mph if the vehicle iss heavy enough it shouldnt matter in this case
The question should actually be do you hit them 100% of the time or not ... or can they pass below the car

**Comment by AmarinReyny** [comment]
> > I kinda feel like something like this should only apply above a certain speed - like, if you're going at a normal driving speed, it would definitely apply, but if you're just inching along at 4 mph, it shouldn't cause any damage unless you're crushing the animal against a wall, and even that probably wouldn't apply due to small enough animals being able to just go under the vehicle anyway.
> 
> Squirrels probably dont care if you drive over them with 1/10/100 mph if the vehicle iss heavy enough it shouldnt matter in this case The question should actually be do you hit them 100% of the time or not ... or can they pass below the car

Yeah, but driving over a squirrel and crushing it underneath the wheel is going to be very different from just bumping into it. That said, I have seen squirrels that were hit (not run over) by cars going about 35 mph, that didn't die immediately, but ended up launched a few feet to the side of the road, where they began flopping around uncontrollably, still definitely alive but probably not for much longer. I kinda felt sorry for them, actually - I'd sometimes debate in my mind whether I'd try to swerve to the side and put them out of their misery, but it was never safe to do so, unfortunately. I've also seen a cat get hit by a car traveling about 45-50 mph, too - we actually stopped to check on that one, in case it was a family pet or something. The cat was alive, but practically frozen in place for a few minutes as we tried to get closer without scaring it, but soon after we got close enough to check on it, it just suddenly bolted off into a field, running faster than I've ever seen a cat run ever before or since then, so it probably wasn't injured _that_ badly.

As for having a chance to go under the vehicle, while that would be a lot more realistic than treating all vehicle tiles as being the same as those with wheels, there's a lot that would need to be in place for it to actually work in a way that makes sense and doesn't cause problems. Like, there would need to be a change in the AI that simulates the typical behavior of animals on roads as cars approach, especially since none of the animals my character has driven nearby in CDDA have ever acted like they would IRL. Also, since certain vehicle tiles may be occupied by player characters/NPCs, there'd have to be some way of letting creatures below the vehicle to exist in the same tile as any creatures/characters inside the vehicle, without crashing the game.
