### ISSUE TITLE
'Smoking rack construction as crafting tool' lazy selection 

### ISSUE THREAD

**Issue by Participation-Trophy** [CleverRaven/Cataclysm-DDA#67513]
### Describe the bug

This occurred in the 0.G stable version, but I was recommended that this should be checked against experimental versions too. I don't have an experimental version to do so, but I provided a save that's hopefully importable for experimental.

The shillelagh recipe only seems to check the topmost smoking racks as a tool with charges for the craft. Other smoking racks within the vicinity with sufficient enough charges are ignored by the recipe. A guess is that the craft checks for the first smoking rack it can find and stops its search there.

### Attach save file

[Testing-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12284666/Testing-trimmed.tar.gz)

### Steps to reproduce

1. Construct a column of smoking racks
2. Look up the shillelagh recipe
3. Fill one smoking rack up with enough charges to satisfy the recipe
4. Notice that the recipe only seems to acknowledge one of the smoking racks and its charges (topmost one in the provided save)

### Expected behavior

The recipe should notice if any other smoking rack fits the criteria of having enough charges and allow the craft if it is. 

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/132187033/1301922f-e407-4b07-8c44-982387f069d6)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3208 (22H2)
- Game Version: d6ec466 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by esotericist** [comment]
reproduced on

- OS: MacOs
    - OS Version: Name: macOS; Version: 14.1; Build: 23B74; 
- Game Version: 0.G-5541-gd1c72bc17c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by RenechCDDA** [comment]
I'm pretty sure this is due to map_cursor::visit_items. Once it finds the first pseudo item the visitor pattern aborts and stops looking.

https://github.com/CleverRaven/Cataclysm-DDA/blob/3c95a24b86217764ebbc3d075805f48783644d22/src/visitable.cpp#L477-L486

**Comment by inogenous** [comment]
Another possible cause of the issue:
1. Part of building crafting inventory calls `inventory::form_from_map`
2. `inventory::form_from_map` has the following checks for pseudo tools from furniture: https://github.com/CleverRaven/Cataclysm-DDA/blob/85926f224a936099bcaf5b10842816231ffc51bf/src/inventory.cpp#L528-L530
3. `inventory::provide_pseudo_item` returns `nullptr` if the crafting inventory already has a tool of the same type: https://github.com/CleverRaven/Cataclysm-DDA/blob/85926f224a936099bcaf5b10842816231ffc51bf/src/inventory.cpp#L354-L358
4. So `inventory::form_from_map` will only get a pseudo tool back in `furn_item` for the first furniture that was examined.
5. The ammo amount being calculated in `inventory::form_from_map` will therefore only be for that furniture.

If the following lines are removed from `inventory::provide_pseudo_item` (so that crafting inventory can contain multiples of each type of pseudo tool), then the problem cannot be reproduced anymore: https://github.com/CleverRaven/Cataclysm-DDA/blob/85926f224a936099bcaf5b10842816231ffc51bf/src/inventory.cpp#L356-L358
But removing that check probably causes other problems, they were likely put there in the first place for a good reason.
