### ISSUE TITLE
Some incentive to clear triffid groves, ant hills, fungal towers, bee hives etc.

### ISSUE THREAD

**Issue by ampersand55** [CleverRaven/Cataclysm-DDA#67531]
### Is your feature request related to a problem? Please describe.

I would like some variety from just doing labs, and I would like some incentive to do more of the content. 

Killing fungals can have the incentive to stop it before it spreads to your base, but otherwise it just it's just too much a hassle and it's easier to just move. Some players use the limit fungal growth mod or disable them entirely.

### Solution you would like.

The most obvious incentive would be rewards in form of loot, preferably something useful and unique than you can't find in other places. Another obvious incentive would be achievements.

**Comment by Zireael07** [comment]
I agree, my tactics when I see one of *those* is to just ... go away. Too much hassle for too little gain.

**Comment by MNG-cataclysm** [comment]
Bee hives have a lot of wax and honey, along with the ultra-healthy royal jelly. Triffids have a lot of wood and plant fiber available. It might not be much, but I guess those two have some loot.

**Comment by ampersand55** [comment]
> Bee hives have a lot of wax and honey, along with the ultra-healthy royal jelly. Triffids have a lot of wood and plant fiber available. It might not be much, but I guess those two have some loot.

The health benefits of royal jelly was removed in #39782 and turned it got turned into actual royal jelly instead of a magic heal all. By the time you can clear a triffid grove you probably won't be in need of wood an plant fiber.

When searching for the above PR, I found that @kevingranade has made several comments about Royal Jelly as a reward in particular, which I presume extends to any reward for hard non-lab content and we should have in mind when giving those rewards. They also confirm that many people feel strongly about there being rewards.

From the above PR:

> [I agree with the royal jelly change, I'm fine with it having some extreme effect, but being a cureall is a really weird one. ](https://github.com/CleverRaven/Cataclysm-DDA/pull/39782#issuecomment-618505596)

From PR "Royal jelly from giant bees mutates you":

> [We're moving away from readily accessible mutagen, this needs at least an intervening crafting recipe.](https://github.com/CleverRaven/Cataclysm-DDA/pull/44643#issuecomment-765742874)

From PR "Add royal jelly in insect mutagen recipe":

> [If you're already a bee, it might induce you to become a queen bee.
Since what you want to bee is a human/insect hybrid that dedicates something less than 90% of their energy to maintaining their reproductive organs, I respectfully suggest that you do not actually want to bee a queen hybrid.](https://github.com/CleverRaven/Cataclysm-DDA/pull/49287#issuecomment-860291106)

They are all rather not in favour of Royal Jelly as a reward, but it isn't shot down outright. 

* They may have some extreme effect, but less powerful than a magical cure all.
* They can't be in a form of readily accessible  mutagen. 
* No hand waving with the loot. We want a strong connection and similar properties as the closest IRL analogues. Royal jelly is used to create queen bees, and has no proven health benefits. 

So, let's just spit ball some possible non-OP rewards that makes some sense with both game-logic and real logic. 

1. What kind of hard overmap "mini dungens" exist? 
2. What are unique for those things respectively? 
3. How can we tie that into something a survivor would want that makes logical sense and is consistent with game lore?

**Comment by estebandellasilva** [comment]
Maybe royal jelly not being a cureall but a thing you can take ... to reset you health to 0 (and also the health modifier) ... so if you current health is negative and you try to improve it that you can start from zero
(but would only apply if health is negative)

**Comment by MNG-cataclysm** [comment]
What if it was set up to where enemy patrols spawn x distance away from the hive, and killing the Queen removes them and keeps any more from spawning?

**Comment by MrHrulgin** [comment]
Yeah, if there was a core object or mob to each of the overworld mini-dungeons that, when killed, would permanently suppress further growth or activity by the threat, that would be a reason to go in and deal with the threat, even in the absence of specific loot.

**Comment by Zireael07** [comment]
@estebandellasilva That would go back to "magic royal jelly" attitude that Kevin wants to avoid

**Comment by estebandellasilva** [comment]
> @estebandellasilva That would go back to "magic royal jelly" attitude that Kevin wants to avoid

You are somewhat right ... but you need to consider that wiping out an ant hive/triffid grove/bee hive iss a considereable effort 
in that regard i dont think an item that only resets your hidden health to zero iss that overpowered + you can even remove the positive effect (so even if you health is positve its set to 0)
The general idea would be to create an item that can help you reset your health (somewhat) - if setting it to zero iss to strong how about halving it (from -100 -> -50 or -70->-35) stuff like that 
something you want to obtain like broad spectrum antibiotics when you are infected

**Comment by Zireael07** [comment]
Such an item would fit the triffids (which are extradimensional) but again we have the problem of what ants/bees would realistically have that would be useful to a survivor, apart from big amounts of honey/syrup...

**Comment by fairyarmadillo** [comment]
The best incentive to exterminate would be if the insects actually sent out foraging parties in a pretty wide radius. I would go to an anthill and kill the queen if it meant protecting my precious sugar.

**Comment by ampersand55** [comment]
I'm afraid that would just disincentivize base-building even further.

**Comment by Skerald** [comment]
Honestly nothing mentioned so far would motivate me to clear any of these locations, except of course killing all fungal creatures. Health honey would do nothing for characters, that can actually clear the hives, unless it acts as a magic potion. I do not think I ever used the old royal jelly, because you usually have more directed cures by that point.

Ants could have a big pile of bodies or bones, that contain somewhat rarer loot. Maybe some ants were introduced before the main cataclysm happened and they ate an entire team of scientists or soldiers. I dimly remember ant hills having such a chamber, but the loot must have been bad, because it has been ages, since I went there. Perhaps they like the taste of zombie scientists etc. Maybe the queen ant or her bodyguards drop superior chitin when butchered. The exodii could tell you, that their jump went partly wrong and some of them along with their cbms ended up in the hive or one of the other locations on the list.

Triffids could have an item, you can position in your fields to speed up crop growth or duplicate seeds or you "plant" it and every day it generates a healthy snack. Perhaps bees stole one of those items and you can find it in their hive? Special triffid seeds could also be nice. Perhaps something like an organic bionic that grafts to your arm or whatever and does something interesting? An item that gives you the ability to shape living wood, to create a base out of a forest.

Fungus could give you an item, that interacts with the remnants of the fungus in the soil to give you map vision over a substantial distance. Perhaps it only does this once, body horror or mind control might be involved.

Some of my suggestions might be a bit out there, but unless clearing these locations gives a permanent advantage, it just is not worth it, since labs offer pretty much everything you could want and are pretty easy to find as well.

**Comment by ampersand55** [comment]
Yea, I think unique and useful loot that late-game characters could want is probably the only incentive that will work and I think you are on the right track with your rewards. 

Some more general suggestions:

* Materials for weapons or armor with associated recipes found in labs? Some sort of upgraded  biosilicified chitin maybe? 
* Mi-go scout towers could have mi-go scout rifles with lots of ammo? 
* Drugs which temporarily increase increase stats, movement speed, attack speed, night vision, skill learning speed, crafting speed etc made from mutant/fungal glands with with associated recipes found in labs. 
* Better pain-killers, bandages, disinfectants. Or a drug of temporary regeneration?
* Something that could be used to power gasoline or diesel engines. 
* Some ingredient for turning tainted meat/fat into non-poisonous and nutritious meat/fat.
* Food as loot has to be really, really, REALLY good for it to be worth it.

**Comment by Skerald** [comment]
Most of those sound interesting, but a few of those are pretty meh.

> Better pain-killers, bandages, disinfectants. Or a drug of temporary regeneration?
The medical supplies we have are already good and if you found a super bandage in a dangerous location, you would probably already have decent healthcare skills, making them superfluous. Same for disinfectants. Better painkillers might be harder to implement, because once you hit a certain point, they will kill you and they are quite common and portable already. A regeneration drug is also pretty meh, unless it regenerates incredibly quickly, since you can usually limp back to base, if you survive the fight.

> Something that could be used to power gasoline or diesel engines.
It is already very easy to get fuel with normal settings and even small engines are more than enough to move even vehicles that barely fit the streets, so better power would probably go unnoticed. On the other hand, if you got an item that made it even easier to get fuel, it would add some desirable QOL, without actually making the character more powerful. Like insert it into a tank or modify it somehow and it generates a trickle of gasoline. No real impact, but it would feel nice.

> Some ingredient for turning tainted meat/fat into non-poisonous and nutritious meat/fat.
If that thing acts as a tool, that would be making a few mutations completely useless and food rarely is a problem. If it is limited, it would be firmly in the "neat" category, not really something you would go out of your way to find it imho.

On their own these probably will not attract players, but if they were used as side loot, they could work.
