### ISSUE TITLE
[feature request] Military robots should return fire regardless if they see their target or not

### ISSUE THREAD

**Issue by Devengel** [CleverRaven/Cataclysm-DDA#67597]
### Is your feature request related to a problem? Please describe.

Title. turrets will shoot back even if they dont see their target, Why not for military robots? i'd imagine their sensors is good enough to pick-up the muzzle flash
Just raided a military outpost. got thousands of military ammo and other goodies with basically no effort

### Solution you would like.

the work is already done. just put `  "special_when_hit": ["RETURN_FIRE", 100]` in their code.

**Comment by Alm999** [comment]
Some questions: if a robot haven't seen the position from which it got attacked, how can it determine where to "return fire"?

Do they have a "Matrix Style" bullet-tracing capabilities or are their self-monitoring sensors that good that they can instantly identify the angle, speed and caliber of the penetrating bullet and "triangulate" (more like "mono-angulate") the shooter's position? Sound and echo-location?

When a sniper shoots is is not  that obvious from where. A full-fledged investigation involving other snipers and their "hunch" on good spots is needed. I think, even turrets having that ability to instantly determine attacker's approximate placement (even if they were shot from a silent bow in complete darkness while being turned to the other side) is cheating. A necessary cheating, yeah (otherwise they are too easy, being immobile), but a cheating none the less.
