### ISSUE TITLE
The item categories of tanks (as in containers) are inconsistent and follows no discernable pattern.

### ISSUE THREAD

**Issue by ampersand55** [CleverRaven/Cataclysm-DDA#67607]
### Describe the bug

Different categories for tanks in the game:

* pressurized tank WEAPONS
* pressurized fuel tank MAGAZINES
* propane tank TOOLS
* scuba tank OTHER
* re-breather oxygen tank is SPARE PARTS
* metal tank a CONTAINERS or whatever category it's content is filled 
* tank top CLOTHING (last one was a joke)

It's hard to find the tanks when you sort your zone by category. 

I wasn't sure whether to categorize this as a suggestion or bug report, but having pressurized tank categorized as WEAPONS can't be intended.

### Attach save file

N/A

### Steps to reproduce

N/A

### Expected behavior

Either:

1. we have everything that's used to reload stuff as MAGAZINES (or create a new category called TOOL MAGAZINES or similar),  or 2. we sort into to where the stuff they reload go, e.g. re-breather oxygen tank as CLOTHES as it reloads the re-breeding mask. 

General metal tanks or pressurized tanks without any associated tool can be containers and take the category of their content.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/9817636/414b4fe4-f91e-415e-af89-4f0366bba5ac)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.14393.6085 (1607)
- Game Version: 2852530 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda]
]

### Additional context

Also, for welding tools:

* Acetylene torch is loaded with a magazine (welding tank).
* Propane torch is loaded with a tool (propane tank).
* Arc welder is loaded with a spare part (battery) or a vehicle part (car battery or storage battery)

Batteries should maybe also be in the same category as tanks, whatever that may be.

**Comment by PatrikLundell** [comment]
Empty tanks should be containers, in my opinion. (partially) Filled tanks should go into whatever category their contents place them in (when not containing multiple kinds), while containers containing mixed contents ought to go into a mixed content container group.
Batteries should probably go into a battery group since they can be used as vehicle parts, "magazines", spare parts, or deployable furniture depending on what you'd like to use them for, so they don't really fit into any of those categories. However, you might want to only place storage batteries into this group and leave "normal" batteries in whatever group they end up in today. It's probably easier to find the normal batteries in a battery group than mixed up with all the stuff that's in their current group, and the logical place to look for batteries would be among batteries.

**Comment by PatrikLundell** [comment]
I'd probably prefer things loaded into things without significant work to mount them and with the purpose of being emptied to be treated as "magazines" (with the exception of batteries and ammunition loaded directly into weapons). I don't think it would be good to separate weapon magazines from other magazines, because there might be situations where something would end up matching both categories (akin to how batteries span categories).

I'd like to see empty pressurized tanks etc. to go into containers if they can be refilled, and into "other" (or "garbage that be recycled as best") if there's no process that allow them to be reused. That's somewhat error prone in that someone who decides to make a recipe to reuse such items should also have to know to update the item category, but I think that's better than to fool the player into thinking there is some use for spent containers that have no further use. I think a number of breathing filters have changed from using filter insets with charges to require the construction of new filters (possible with the spent filter assembly as a component) when they are spent. I wouldn't want those to end up in clothing as they provide no benefit but only disadvantages when spent.

**Comment by PatrikLundell** [comment]
The lists below were produced by loading a fairly advanced save and trundling though all the crafting recipes available.
I was unable to expand rebreather, for an unknown reason. In hindsight I realize I should have move to my normal crafting location to have access to the books for unlearned recipes, but I find I don't remember where that spot was.

Weapon/Magazines:
- 0.5 L pressurized fuel tank
- 2L pressurized chemical tank

Armor (ignoring scabbards and other dedicated "holding stuff" clothing) NO ISSUES SEEN IN THIS SECTION:
- Survivor dry duffel bag (clothing, but it can be worn, so not entirely wrong)
- Survivor duffel bag (ditto)
- Large dry bag (Correctly Containers, mentioned as a contrast to the ones above)
- Purse (correctly clothing, as it is mainly worn)
- Survivor backpack (correctly clothing)
- Survivor dry bag (clothing, but it can be worn, as opposed to the large dry bag)
- Survivor rucksack (correctly clothing)
- daypack (correctly clothing)
- dry bag (correctly clothing)
- golf bag (correctly clothing)
- high-volume rucksack (correctly clothing)
- military rucksack (correctly clothing)
- MOLLE assault pack (correctly clothing)
- MOLLE large rucksack (correctly clothing)
- MOLLE medium rucksack (correctly clothing)
- runner pack (correctly clothing)
- survivor distributed rigging (correctly clothing)
- survivor harness (correctly clothing)
- camera bag (correctly clothing)
- drop leg bag (correctly clothing)
- fanny pack (correctly clothing)
- hiking backpack (correctly clothing)
- large tactical backpack (correctly clothing)
- survivor runner pack (correctly clothing)
- backpack (correctly clothing)
- big pack frame (correctly clothing)
- big trapper pack (correctly clothing)
- deployment bag (correctly clothing)
- leather backpack (correctly clothing)
- messenger back (correctly clothing)
- sling pack (correctly clothing)
- small leg purse (correctly clothing)
- travelpack (correctly clothing)
- wicker backpack (correctly clothing)
- box backpack (correctly clothing)
- duffel bag (correctly clothing)
- jerrypack (correctly clothing)
- leather wallet (correctly containers)
- longarm bag (correctly clothing)
- pack frame (correctly clothing)
- trapper pack (correctly clothing)
- duct tape wallet (correctly containers)
- net backpack (correctly clothing)
- straw basket (correctly clothing, as you "strap" it to a free hand and it provides coverage)
- bindle (correctly clothing, essentially the same argument as for straw basket)
- bookstrap (correctly clothing)
- hide bag (correctly clothing)
- makeshift knapsack (correctly clothing)
- swag bag (correctly clothing)
- tainted hide bag (correctly clothing)

Other:
- aluminum tank (100/200L) (correctly containers)
- steel drum (100/200L) (correctly containers)
- steel keg (correctly containers)
- empty canister (other, currently. I'd like to seem it in containers)
- medium tin can (correctly containers)
- 100/30/50 gallon aquarium (drying) (currently containers. Should they go elsewhere until they're cured?)
- 2.5L canteen (currently containers, should probably go into clothing as they can be worn)
- blood raw kit (currently tools. While it's technically a container, it's mostly a specialized tool, so I think it should remain a tool)
- canning pot (currently tools TBD)
- copper pot (currently tools TBD)
- gallon jug (correctly containers)
- large plastic bottle (correctly containers)
- makeshift pressure cooker (currently tools. Ought to remain there as it's not really suitable for use as a container)
- plastic bottle (correctly containers)
- plastic canteen (currently containers. -> clothing)
- plastic soap bottle (correctly containers)
- small plastic bottle (correctly containers)
- stock pot (currently tools TBD)
- storage battery case (correctly vehicle parts)
- anesthesia kit (currently tools. See blood draw kit)
- bucket (correctly containers: cannot be worn, only carried)
- hip flask (currently containers. -> clothing)
- large waterskin (currently containers. -> clothing)
- oil lamp (off) (correctly tools, while technically a container as well, its primary use is as a tool)
- wooden barrel (correctly containers)
- wooden canteen (currently containers. -> clothing)
- aluminum pot (currently tools TBD)
- bottle gourd (currently containers. -> clothing)
- canvas sack (correctly containers)
- clay bowl (correctly containers)
- clay canister (correctly containers, as opposed to empty canister above)
- clay canning pot (currently tools TBD)
- clay flower pot (correctly others. It doesn't have a capacity to contain anything)
- clay hydria (correctly containers)
- clay jug (correctly containers)
- clay oil lamp (off) (correctly tools. See oil lamp)
- clay pot (currently tools TBD)
- clay teapot (currently tools TBD)
- clay urn (currently tools. Should make it containers, as it can be used to store things other than ash)
- copper pot (currently tools TBD)
- gas mask cartridge (currently spare parts. -> magazines)
- heavy punching bag sack (correctly containers)
- large clay pot (currently containers. Should be the same as other pots...)
- pot (currently tools TBD)
- small waterskin (currently containers -> clothing)
- steel bottle (correctly containers as it cannot be worn)
- steel jerrycan (correctly containers)
- teapot (currently tools TBD)
- toolbox (correctly containers)
- waterskin (currently containers -> clothing)
- canvas bag (correctly containers)
- fire barrel (100/200L) (correctly tools, as it no longer has any storage capacity)
- foil cup (currently containers. Should probably be same as pots)
- gallon jug (correctly containers)
- makeshift copper pot (currently tools TBD)
- makeshift pt (currently tools TBD)
- metal tank (2/60L) (correctly containers)
- plastic jerrycan (correctly containers)
- rebreather oxygen regenerator (currently spare parts -> magazines)
- rebreather scrubber cartridge (currently spare parts -> magazines)
- sealed stomach (correctly containers)
- wearable (professional) camera (correctly clothing, to reinforce notion that canteens should be as well)
- wooden bowl (correctly containers)
- lots of different boxes (correctly containers)
- earthbag (correctly other, as it's a filled container which guides its classification)
- gravelbag (ditto)
- oxygen cylinder (currently spare parts -> magazines)
- oxygen tank (correctly tools, as the name is misleading: it's a medical device with oxygen tank plus mask)
- sandbag (correctly other, see earthbag)

**Comment by PatrikLundell** [comment]
Pots are a marked as TBD because I'm not sure whether they should be tools or containers. Regardless, all of them should be in the same category.

Stripped away the "correct" stuff from the post above, and assumed pots should remain in tools.
The reason I listed everything as I went through it was to allow people to notice things I didn't catch, as well as have an opinion on my reasoning.

Other:
    empty canister (other, currently. I'd like to seem it in containers)
    100/30/50 gallon aquarium (drying) (currently containers. Should they go elsewhere until they're cured?)
    2.5L canteen (currently containers, should probably go into clothing as they can be worn)
    plastic canteen (currently containers. -> clothing)
    hip flask (currently containers. -> clothing)
    large waterskin (currently containers. -> clothing)
    wooden canteen (currently containers. -> clothing)
    bottle gourd (currently containers. -> clothing)
    clay urn (currently tools. Should make it containers, as it can be used to store things other than ash)
    gas mask cartridge (currently spare parts. -> magazines)
    large clay pot (currently containers. Should be the same as other pots, i.e. tools)
    small waterskin (currently containers -> clothing)
    waterskin (currently containers -> clothing)
    foil cup (currently containers. Should probably be same as pots, i.e. tools)
    rebreather oxygen regenerator (currently spare parts -> magazines)
    rebreather scrubber cartridge (currently spare parts -> magazines)
    oxygen cylinder (currently spare parts -> magazines)
