### ISSUE TITLE
Wielding enormous items while driving

### ISSUE THREAD

**Issue by burakutlu** [CleverRaven/Cataclysm-DDA#67669]
### Describe the bug

It is possible to wield heavy items, and they knock you down if you don't have enough strength. However, this is not a problem while driving a vehicle. It should not be remotely achievable. You can wield a fridge/oven/corpse any heavy item with one hand and drive the vehicle with the other.
As far as I know, this bug has existed for a long time.

### Attach save file

n/a

### Steps to reproduce

1. Wield a heavy item
2. Hop on a vehicle
3. Drive to your destination

### Expected behavior

It's not possible to carry a 60kg oven on your back and drive a motorcycle one-handed. The player should be receiving damage and losing control of the vehicle.

### Versions and configuration

- Game Version: Gaiman
- No mods

**Comment by anoobindisguise** [comment]
As long as we can't consolidate storage areas (store a gigantic corpse in your cargo bed for example) and have no dedicated way to support tying stuff to your vehicle beyond manually adding new installation JSON entries this is probably a necessary bit of hackiness IMO.

**Comment by ilovehans10** [comment]
> As long as we can't consolidate storage areas (store a gigantic corpse in your cargo bed for example) and have no dedicated way to support tying stuff to your vehicle beyond manually adding new installation JSON entries this is probably a necessary bit of hackiness IMO.

I have used this bug many times to move big corpses and other furniture that would be difficult to more otherwise. A possible suggestion would be to make some sort of roof rack that works similar to the lifting field provided by MOM. The lifting field has three unique features you can put as massive a thing as you like in it (up to 10,000L I think), it has a weight limit (optional in this use case) but most importantly you can only put one item in it. This would allow for someone to strap a fridge, hulk corpse, or christmas tree on their roof but not abuse having a massive storage space. This could also be implemented so that it starts with maybe 200 L but then if another is installed next to they are combined to a storage capacity of 400 L, so that it isn't OP by giving you too much storage on your electric unicycle.

**Comment by Procyonae** [comment]
While I'm not a fan of the pocket dimension nonsense making it use the same infra as the animal vehicle storages would probably make sense until we have something better

**Comment by GuardianDll** [comment]
![image](https://github.com/user-attachments/assets/634587f6-d5c7-4dff-90f4-12b9057d853b)
