### ISSUE TITLE
give the option for an input field to the start of cataclysm and game

### ISSUE THREAD

**Issue by Devengel** [CleverRaven/Cataclysm-DDA#67674]
### Is your feature request related to a problem? Please describe.

it would be nice, better than clicking random until you hit a desirable number 
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/71761521/fa36318b-ffef-4c3b-b70c-d7da4400edb5)

### Solution you would like.

Title

**Comment by ZhilkinSerg** [comment]
If you want to use specific start date more than once it is better to create a scenario with that date (and optionally share it with other people).

**Comment by Zireael07** [comment]
Yeah, except some very specific scenario that start you next winter it should be possible to set a specific date

**Comment by Paprika-H** [comment]
> If you want to use specific start date more than once it is better to create a scenario with that date (and optionally share it with other people).

I do like randomness in CDDA, I often play with -1 as initial start date. But honestly, this feels clunky. If you want to start a game with slightly evolved creatures, but otherwise normal start day, you have to reroll the dice over and over. Also, I dislike how it just tells you what date you're starting at instead of keeping it a surprise. I quite liked how it worked that way, as I had no chance to reroll if I was starting in the dead of winter, and overall felt less prepared. Was it really necessary to remove it in the first place? I know that maintaining options is difficult and all, but could there not be a mix of the two features?

**Comment by 6DollarSuit** [comment]
> If you want to use specific start date more than once it is _better_ to create a scenario with that date (and optionally share it with other people).

@ZhilkinSerg  but _**how**_ is it better to have to close the game and create/edit a scenario externally and restart the game (or sit there hammering the randomize button for a few minutes until you get lucky), just to start on day 7 of summer for a single character? What reason was there to make it so you could not type it in? It's an incredibly confusing decision, and isn't consistent with the other randomize-via-hotkey options, all of which allow you to edit the result manually (character name, etc).

**Comment by EternalKitten** [comment]
I agree, actual user experience is an afterthought here.
