### ISSUE TITLE
World seeds

### ISSUE THREAD

**Issue by Devengel** [CleverRaven/Cataclysm-DDA#67675]
### Is your feature request related to a problem? Please describe.

it's sad that we don't have the ability to replicate worlds (No, not sharing world files), we can't even see what world randomness is set to

### Solution you would like.

Think minecraft, You put a number, and world gen will always output that specific world, the world would change when mapgen changes, of course. this assumes people have the same world settings (same city size, same city distance, etc)

**Comment by Maleclypse** [comment]
This is impossible with our mapgen system. Because each overmap is generated on the fly as the character approaches it. Not at game start as required for map seeds to work.

**Comment by ZhilkinSerg** [comment]
It was discussed numerous times before on forums, e.g.:

https://discourse.cataclysmdda.org/t/suggestion-storing-reusing-world-seeds/1527/7
https://discourse.cataclysmdda.org/t/save-rng-seeds/13900/3
https://discourse.cataclysmdda.org/t/worldgen/478/2
https://discourse.cataclysmdda.org/t/re-generative-world-feature/1530/13

I agree it would be nice to have (at least for top-level overmap features, if not for lower level mapgen), but somebody needs to actually start working on this - at least do some code research and draft implementation plan, otherwise it would be just another stale issue.

**Comment by MrHrulgin** [comment]
> This is impossible with our mapgen system. Because each overmap is generated on the fly as the character approaches it. Not at game start as required for map seeds to work.

Minecraft only generates chunks as you approach them, and it's possible to show the seed. The newly generated chunks just refer back to the same map seed as was used for the earlier area. Not to say that there aren't other reasons under the hood that it wouldn't work, but the very fact of the overmap being generated as it's visited isn't indicative of its impossibility.
