### ISSUE TITLE
Add an option to get followers to sort items into containers

### ISSUE THREAD

**Issue by AmarinReyny** [CleverRaven/Cataclysm-DDA#67672]
### Is your feature request related to a problem? Please describe.

So, I'm having mixed thoughts about the change from charges to count, but I'm still willing to try it out, at least once the various cooking-related bugs are resolved. That said, after a brief discussion with @Maleclypse, I do have an idea for a feature that could make things easier for some players to adjust to the change - especially those like me, who typically play characters that build multiple basecamps so that my growing nation of followers can start producing goods to help what's left of humanity survive - by making sorting granular loot less of a hassle once it's brought back to base. And that idea is...

### Solution you would like.

... having an option to make followers sort items into containers!

While I'm sure there are a few different ways this could potentially be done, the idea that I have thought of is to add recipes to the crafting menu that involve putting a bunch of small, granular items - like salt, for example - into jars. No creating new items, no recalculating anything. Just taking a jar, and some stuff, and putting said stuff in said jar.

The biggest issue I can see happening with this is the amount of bloat this will add to the crafting menu. However, Maleclypse said he has an idea that might help with that. I have no idea what his idea is, though, but it's probably best for him to describe it anyway.

### Describe alternatives you have considered.

Assigning NPCs to do the storing of items through new zones and jobs, maybe?

**Comment by Maleclypse** [comment]
One idea would be for zones to respect containers when sorting, and that only empty containers get moved to the containers zone.  Second idea was for instead of adding container based recipes for salt in a bag, flask, bottle you would be asked in the start of the recipe "would you like to contain the results of this recipe" similar to what it does when creating liquids at the end of a recipe now.  And that allows you to select any containers in range. So basically it moves the current post recipe function into a start of recipe function.

**Comment by AmarinReyny** [comment]
> One idea would be for zones to respect containers when sorting, and that only empty containers get moved to the containers zone. Second idea was for instead of adding container based recipes for salt in a bag, flask, bottle you would be asked in the start of the recipe "would you like to contain the results of this recipe" similar to what it does when creating liquids at the end of a recipe now. And that allows you to select any containers in range. So basically it moves the current post recipe function into a start of recipe function.

YES.

**Comment by PatrikLundell** [comment]
Implementing container selection into the ingredients selection phase might improve companion crafting of liquids both as a base camp activity and companion order activity. An issue with this is that the current recipe logic only accepts homogeneous selections of entries, i.e. all apples or all oranges, so you wouldn't be able to select one gallon jug and 3 flasks, for instance. Another issue with container selection is that the current component selection process doesn't have any support for the usage partially filled containers (not to be confused with usage of their contents), so you wouldn't be able to elect to top up your 100L drum of battery acid with the newly produced acid.

When it comes to the other issue of sorting, I would suggest containers should be sorted in three groups: empty containers, single stack contents, and mixed contents, where empty containers obviously would go into the containers zone, single stack containers would go into the zone of the contents, while mixed contents would go into a mixed contents zone (where you'd probably would want to sort it).

When it comes to the actual suggestion, though, I'm not sure it's a good game play idea (as opposed to being a good real life strategy), because splitting things up into containers results in creating multiple stacks of items, and that probably results in worse performance than fewer large stacks. Optimizations to stack collation are likely to be reduced in effect by an increase in the number of stacks.
