### ISSUE TITLE
i18n for chinese lang broken since build #1007 (maybe #1048)

### ISSUE THREAD

**Issue by duskgao** [CleverRaven/Cataclysm-DDA#6776]
In Chinese windows7 64bit,if there is MO file in lang\mo\zh_CN\LC_MESSAGES  folder,CDDA will crash with a VC++ runtime error:

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
![cddabug1](https://f.cloud.github.com/assets/6193964/2458183/b0270cd6-af47-11e3-8a9d-2d9fe5fe2f99.png)

If I deleted the lang folder,the English CDDA runs very well!

this bug maybe happened after build 1007(aka  0.A stable) .Someone tested the last working build with chinese MO is build 1048,I am not sure.But all Curses/Tiles build have broken for a longtime.

**Comment by illi-kun** [comment]
It seems that #8759 fixed the issue. I've tested current ```master``` on Win8 and see no crash, it works just fine (well, I actually see only boxes but it happens because I have no Asian fonts on my system).

I'd prefer to close this issue but I wonder to know if there is a reason of appearance of ```validated``` label in the same day when #8759 was landed. @kevingranade do you remember details about that?

**Comment by illi-kun** [comment]
Closing for now, feel free to reopen if it's still an issue.
