### ISSUE TITLE
Portal dungeons remain in the sky after completion

### ISSUE THREAD

**Issue by gisaku33** [CleverRaven/Cataclysm-DDA#67781]
### Describe the bug

After completing a portal dungeon, it will continue casting a shadow onto the ground. I asked about it on the discord and was informed that dungeons remaining was a bug they thought was fixed already, so to make a new report.

### Attach save file

[Rib Mountain-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12386789/Rib.Mountain-trimmed.tar.gz)

### Steps to reproduce

1. Speak to voice, enter portal dungeon.
2. Complete dungeon (I ran through many times, if that matters.)
3. See shadow on the ground.

### Expected behavior

Portal dungeons not stealing my Sun.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/23239811/d7c4b36f-731a-4fd9-8c2c-dd23fa0781f6)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3324 (22H2)
- Game Version: f7061f5 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Xedra Evolved [xedra_evolved],
    Extra Mutated Scenarios [extra_mut_scens],
    Mythical Martial Arts [MMA],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Tamable Wildlife [Tamable_Wildlife],
    Mind Over Matter [mindovermatter],
    Bombastic Perks [bombastic_perks],
    Portal Storms Ignore NPCs [personal_portal_storms]
]

**Comment by yamil-90** [comment]
any news on this? the same happens to me in the latest-ish experimental

**Comment by KHeket** [comment]
The same happens to me, solar panels still give me energy, but character can hide in this black mark

**Comment by KHeket** [comment]
Still have this bug. @Ramza13 can you check pls?

**Comment by KHeket** [comment]
This problem is very annoying and breaks the structure of base, because I have two squares of dark at my base

**Comment by KHeket** [comment]
As example of two portal dungeons in the sky, here is save+screenshot
[1-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13330033/1-trimmed.tar.gz)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/102726167/a03cde26-34c3-4514-a64b-bf1ff5e43890)

**Comment by andrei8l** [comment]
/confirmed still an issue; still haven't tracked it down

**Comment by andrei8l** [comment]
I'm still having trouble reproducing this. Just going through the dungeon is not enough. I've tried it with linux/msvc/mingw builds so it's probably not platform-specific either.

Any more details on how this happened?

**Comment by KHeket** [comment]
> I'm still having trouble reproducing this. Just going through the dungeon is not enough. I've tried it with linux/msvc/mingw builds so it's probably not platform-specific either.
> 
> Any more details on how this happened?

I don't know what is causing it, but in this case I walked 15+ times, killed more, than 90 "better half" monsters, have 2 or more autosaves and than I leave by myself the labyrinth by the teleport-exit at the beginning of the level.  May be something of it is a trigger, I don't know
And also it was natural started portal storm, I am saying this because I remember, that there was a bug, which makes chunks of matter not to drop artifacts, if this monsters spawned naturally, but if you debug spawn chunk of matter and kill it - it will drop artifact. This bug was fixed, but may be you cant reproduce it, if you make portal storm and labyrinth event by debug menu

<details>
  <summary>Zipped save file + game info and log</summary>
[1-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13593077/1-trimmed.tar.gz)

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/13593070/crash.log)

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/13593071/debug.log)


- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: 782cc4d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]
</details>
<details>
  <summary>Screenshot</summary>

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/102726167/a492c42d-b1ff-4bbb-93b4-80c8f6b5bf2c)
  
</details>

**Comment by andrei8l** [comment]
Went through it 20 times. Your character fell asleep 6 times. And still no bug. I need a reproducing save, meaning either from the end of the dungeon or from the start (but with specific instructions). It's still useful information if you can't reproduce after reloading.
