### ISSUE TITLE
No more minecraft like explosion craters

### ISSUE THREAD

**Issue by KHeket** [CleverRaven/Cataclysm-DDA#67803]
### Is your feature request related to a problem? Please describe.

Explosion craters are like minecraft
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/102726167/97c9718b-783a-4883-ac2b-fcbcbf5581c0)
But they should be like in reality
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/102726167/f2a4df4a-ea8b-4847-8408-91d2c3b4be7e)

### Solution you would like.

Add ramps to crater generations. But they are always created by exploding items, so there must be explosion logic rework
It also will remove exploit of the pits, when any not intelligent anemy will fall into pit

**Comment by Karol1223** [comment]
I feel like it's not as simple. Sure real world craters aren't blocky, but they're not cones either. Crater walls can be steep, and they're often irregularly shaped (rare to see a perfect half-orb), so proc-genning that would be tricky.

**Comment by ilovehans10** [comment]
> I feel like it's not as simple. Sure real world craters aren't blocky, but they're not cones either. Crater walls can be steep, and they're often irregularly shaped (rare to see a perfect half-orb), so proc-genning that would be tricky.

Would it make sense to have the top of craters still drop off a tile because too steep, and have lower in the crater have slopes?

The red is roughly what explosion craters seem to look like according to google. With that, I drew the blue lines, which I believe would match up with how the blocks could be drawn to match a rounded crater better. Up near the top it falls as it is steep there, and lower down it slopes as the crater bottoms out. I haven't dealt with tons of explosives, so I am not super accustomed to what a crater made by an explosive looks like, but from what I have seen craters tend to be more wide than deep.
<img width="906" alt="Screenshot 2023-08-21 at 11 53 06 AM" src="https://github.com/CleverRaven/Cataclysm-DDA/assets/20823837/40bcf581-adff-4816-beb9-e4abed061446">
<img width="893" alt="Screenshot 2023-08-21 at 12 05 30 PM" src="https://github.com/CleverRaven/Cataclysm-DDA/assets/20823837/14025f9d-6776-44e9-a5e1-7aeee2f6160d">

**Comment by Karol1223** [comment]
> Would it make sense to have the top of craters still drop off a tile because too steep, and have lower in the crater have slopes?

This is exactly what I had in mind writing my comment, yeah. Though truth be told I'm not an expert in craters nor explosives either, so how realistic this is I can't tell. I just know it *feels* real-er

**Comment by ampersand55** [comment]
Craters should probably look like this:

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/9817636/1eddf529-fcfb-4971-b318-bc959d2dc923)

With an equal amount of "blocks" being green and red.

**Comment by fairyarmadillo** [comment]
My dream of skating in a mininuke crater is drawing closer.
