### ISSUE TITLE
NPC camps don't account for beds

### ISSUE THREAD

**Issue by BakingSoder** [CleverRaven/Cataclysm-DDA#67889]
### Describe the bug

When trying to expand the NPC base camp in an evac shelter it refuses to notice beds that were build manually, no matter their kind, amount or Z level position. There's also no option in the camp menu to build them with the help of NPC, so building manually is the only option available.

### Attach save file

N/A

### Steps to reproduce

1. Make a player spawn at evac shelter.
2. Spawn a friendly NPC and make camp in the shelter.
3. Choose an evac shelter template.
4. Build as many beds as you want, it never will be enough.

### Expected behavior

I expected that it will notice at least the beds that are on the same Z level, but no matter the effort it refuses to expand the base...

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: LENOVO; Model: Lenovo TB-X606X; Release: 10; Incremental: TB-X606X_USR_S300582_2203181205_V9.56_BMP_ROW; 
- Game Version: 8c55459 [32-bit]
- Graphics Version: Tiles
- Game Language: Системный язык []
- Mods loaded: [
    Тёмные Дни Впереди [dda],
    Отключить потребности у НПС [no_npc_food],
    Портальные штормы игнорируют НПС [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Без ж/д станций [No_Rail_Stations],
    Магиклизм [magiclysm],
    Скорость от ловкости [speedydex],
    Слоты для бионики [cbm_slots],
    Характеристики за навыки [StatsThroughSkills]
]

**Comment by Maleclypse** [comment]
> That is by design.
> 
> The field base camp version 2 and the bare bones base camp bypass this restriction (by claiming a sufficient number of beds exists as part of the base camp construction itself), but whoever designed the base camp functionality originally decided it was a good idea to limit the number of expansions available to the gradual construction of the base camp itself, and tie that to the number of beds thus constructed (and, in most cases, ending the construction progress before all 8 expansion slots were "unlocked").
> 
> As you can probably tell from the above, I don't like this artificial restriction...
> 
> There is currently no support for base camps spanning more than a single level: the levels above and below are not reachable by any base camp functionality (nor does zone activities handle more than a single level, with a possible exception for one kind of zone that may have been modified to deal with multiple levels).

I think we've reached a point where you could start getting rid of the limited growth rate faction camps, if you wanted to do so. It's probably unnecessary to maintain both at this point or to at least hide creation of the limited ones in current experimentals so that we can deprecate that type of camp entirely in the next experimental cycle.

**Comment by PatrikLundell** [comment]
All that's needed to be done to remove the effect is to remove the code that checks for the number of beds as a condition for expansion.

I am not 100% sure if the "beds" assigned have any function other than supporting this limit, though, although my suspicion is that it doesn't (how about assignment of companions to camps?). If it doesn't have any other function at all, the base camp recipes ought to get rid of the bed number allocation (that's incorrectly implemented in a number of them anyway, with authors assuming the numbers are absolute rather than cumulative), but that's a larger cleanup effort. Apart from the "beds" allocation, I believe a number of base camp constructions also contain descriptions that imply these constructions being required for expansion.

I can certainly get rid of the blocking code itself in the near future.

When it comes to getting rid of base camp variants, it's really a different issue. Do we consider some of them obsolete, or do we just unchain them?

The bare bones base camp is technically sufficient and capable of providing the same "end result" as most other base camps. with the exceptions I know of being the exact recipe sets provided, the drop hammer NPC only recipes for some (until the drop hammer is made possible to construct normally), and some radio tower variation (when your base is at a tower). There might be some base camp that has some construction that's not possible to construct by the player, although I only know of the case of both livestock expansions (you can't build a roof whose support on one of the supporting side is based on pillars two tiles apart; it has to be at most one tile apart). However, some people want ready made "upgrade paths" rather than designing their case from scratch (with limited player knowledge of what's possible and what's required).

Obsoleting base camps is easy: just remove them from the list of possible base camp, and you can't start a new one, while existing ones can still be upgraded.
