### ISSUE TITLE
"Heavy" weight category

### ISSUE THREAD

**Issue by oosyrag** [CleverRaven/Cataclysm-DDA#67909]
### Is your feature request related to a problem? Please describe.

Despite having no gameplay impact, it is common for players to interpret "overweight" with a negative connotation, even though overweight should be regarded as a neutral term. 

### Solution you would like.

I suggest splitting the "overweight" label range in half, with "heavy" as the lower half and "overweight" as the upper half, with "heavy" hopefully being perceived as more neutral than "overweight" in general. Given that overweight has no gameplay effect to begin with, nothing changes with this except for the way information gets displayed.

### Additional context

Of course, heavy isn't an official BMI category, so if we're strictly following BMI categorizations this is no good. But I don't think it is a good idea to be stuck on an arbitrary system if it is detrimental to clarity or otherwise makes a player uncomfortable enough to ask otherwise.

**Comment by PatrikLundell** [comment]
I don't think politically correct obfuscation terms are helpful, as "heavy" might easily be confused with being muscular or have a broad build rather than having excess fat, which is what the game actually "models". It doesn't exactly help that it's fairly common for games to have slim and broad body types as part of the character generation.

**Comment by GuardianDll** [comment]
can just divide it into "light overweight" and "overweight"

**Comment by oosyrag** [comment]
Oh it's based on fat now? Last I knew BMI was strictly a calculation by weight/height, which was not great. And that was the intent, you can be "overweight" but still fit/muscular. Hence heavy.

**Comment by PatrikLundell** [comment]
In the real world BMI is a crappy one size fits all measurement that's applied as a lazy measurement tool regardless of whether it's a reasonable one for a particular individual. In the game world, however, it's an energy storage measurement only.

**Comment by anoobindisguise** [comment]
Yeah so base weight here, is 12 points of BMI, then you add 1 point of BMI for each point of strength you have.
Then you add BMI from fat, which is the kilogram value of stored calories (7716.17 kcal per kg) vs. your height, to get total bmi from fat. 5 bmi-from-fat is in between normal and healthy. below 3.5 is underweight. above 10 is obese. above 20 is morbidly obese. So for an 8 strength person they start the game at 25 BMI, which is just between their "normal" and "overweight" values.
whereas a 12 strength character starts at 29 BMI, but they're no more overweight or underweight than the 8 strength person. Your readout of under/normal/over/obese is purely determined by stored cal (fat)

**Comment by fairyarmadillo** [comment]
Heavy sounds fatter than overweight to me. I agree with the basic premise of this issue but I think a better solution might be to widen our definition of Normal so that you don't get into overweight quite as easily.

I am not sure the same should be done for underweight as that is something players need a lot of feedback on, as it can spin out of control quickly.

Similarly it occurs to me that a Dysmorphia trait that caused your weight reading to be less accurate might make for an interesting challenge.

**Comment by PatrikLundell** [comment]
I wouldn't like the normal weight range to be extended. I've found it most convenient to try to have my characters being slightly overweight so I don't get the "VERY HUNGRY!!!!" message screaming at me all the time, so I try to stay there and return as soon as I dip into normal.

**Comment by ZhilkinSerg** [comment]
We have 7 following BMI categories:

https://github.com/CleverRaven/Cataclysm-DDA/blob/097fa670377b6b94f472f9f4723585bfc14feda1/src/game_constants.h#L205-L215

I believe these are commonly used BMI category names and I've never seen `heavy` being used, but tbh I've never seen `morbidly obese` either.

**Comment by oosyrag** [comment]
I feel the very hungry/hungry status from being normal or overweight is very artificial. Iirc it was meant to help players not starve to death from lack of calories. I remember complaining about it a few years ago, but since then there were new daily messages added regarding calorie consumption which are nice, so maybe it's time to revisit hungriness too.

**Comment by fairyarmadillo** [comment]
> I feel the very hungry/hungry status from being normal or overweight is very artificial. Iirc it was meant to help players not starve to death from lack of calories. I remember complaining about it a few years ago, but since then there were new daily messages added regarding calorie consumption which are nice, so maybe it's time to revisit hungriness too.

Hunger feedback in general is terrible. All of the messages are still bad and players are still falsely under the impression that they should always eat whenever hungry until their hungry goes away. This has been blamed on other games training them wrong, but I think it's clearly a case of our game not reflecting reality.

Hunger needs to have an impact, you shouldn't be able to starve yourself for days to lose weight with no detrimental effects. Characters should want to eat regularly and there should be good reasons for doing so beyond body weight.

**Comment by Vaskritaya** [comment]
More specifically about this issue, I do think "overweight" could be interpreted by an uninitiated player as a negative status you should avoid due to IRL associations with weight, despite the fact that in this game (and probably an irl survival scenario) having a bunch of stored calories is strictly a benefit until it begins having a noticeable detrimental effect mechanically.

Particularly, "overweight" is something you get a colorful, eye grabbing UI label for, while standard weight is not. This kinda broadcasts to the player that it's something worth paying more attention to than being at normal weight, which I don't really think is good practice. The two thresholds I'm most concerned about are the ones between underweight/normal, and between overweight/obese(?). Furthermore, by the time the UI shows I'm underweight, I'm _already_ in the place I wanted to avoid, with no indication beforehand that I was approaching it besides some of the vague stomach messages you get.

**Comment by Zireael07** [comment]
> overweight" could be interpreted by an uninitiated player as a negative status you should avoid due to IRL associations with weight, despite the fact that in this game (and probably an irl survival scenario) having a bunch of stored calories is strictly a benefit until it begins having a noticeable detrimental effect mechanically.

This problem could be solved by adding/expanding effect descriptions?

**Comment by Zireael07** [comment]
@kdpullen95 I agree that yellow, IRL, is usually associated with warnings and it's confusing to see it on something neutral as Overweight seems to be. Changing it to green would be a simple fix too

**Comment by fairyarmadillo** [comment]
I like the idea of having the colored warnings on a finer gradient than the names, so that overweight starts out green and only becomes yellow at the higher end.
