### ISSUE TITLE
Helicopter horsepower miscalculated 

### ISSUE THREAD

**Issue by Pbprovost** [CleverRaven/Cataclysm-DDA#67911]
### Describe the bug

I noticed that the horsepower calculation for helicopters is using milliwatts when it should be using megawatts, unless the comments are off about what the number represents. This is on line 4254 of vehicle.cpp.

For instance, a 2hp engine shows as 2,000,000 horsepower.

This allows very small motors to fly helicopters. Like a small electric motor flying an Apache.

### Attach save file

N/a

### Steps to reproduce

Fly any helicopter and check the debug of the horsepower. It's a million times what it should be.

### Expected behavior

Should not be able to fly an Apache off a small electric motor.

### Versions and configuration

Latest experimental

**Comment by ZhilkinSerg** [comment]
Is it only a display issue for horse powers or you can actually lift off using some small engine?

**Comment by Pbprovost** [comment]
You can lift off and fly 225 mph with a tiny electric motor because it's calculated as having 2 million horsepower where it checks for lift.

The only part that can fail is where it calculates overall vehicle weight being too heavy for a motor, but I believe that's a different general vehicle code not just flight. You can still get in the air with over 3000lbs on a tiny electric motor.

**Comment by ZhilkinSerg** [comment]
I guess the culprit is in https://github.com/CleverRaven/Cataclysm-DDA/commit/479fa6c4659f4ad17f402f426377caf979f4a91c#diff-25c559834fc05e15cc83980e2a74a183f49cfbe404945f8b0a9d29fb8f713039

It changed watts to milliwatts:

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/16213433/0cd8ab95-6e30-45e7-af83-9871fec4c30d)

1 W is 0.00134102 horse powers, so 1 mW is 0.00000134102 horse powers, but it was changed to 1.34102 horse powers per mW, which is 1 million times bigger than it should be.
