### ISSUE TITLE
Magiclysm container CI failure

### ISSUE THREAD

**Issue by Maleclypse** [CleverRaven/Cataclysm-DDA#67927]
### Describe the bug

```
(all_mods)=> (continued from above) ERROR : src/item.cpp:1601 [ret_val<void> item::put_in(const item &, item_pocket::pocket_type, const bool)] tried to put an item (small_mana_crystal) count (1) in a container (wand_magic_missile_minor) that cannot contain it: pocket unacceptable because holster already contains an item
(all_mods)=> 02:29:46.837 ERROR : src/item.cpp:1601 [ret_val<void> item::put_in(const item &, item_pocket::pocket_type, const bool)] tried to put an item (small_mana_crystal) count (1) in a container (wand_fireball_minor) that cannot contain it: pocket unacceptable because holster already contains an item
(all_mods)=> 02:29:46.849 ERROR : src/item.cpp:1601 [ret_val<void> item::put_in(const item &, item_pocket::pocket_type, const bool)] tried to put an item (small_mana_crystal) count (1) in a container (wand_magic_missile_minor) that cannot contain it: pocket unacceptable because holster already contains an item
```

### Attach save file

N/A

### Steps to reproduce

CI runs

### Expected behavior

CI runs with few rng errors

### Versions and configuration

NA

**Comment by Maleclypse** [comment]
So the more I'm seeing this.  I think the error is that the wand is appearing already loaded.

**Comment by mqrause** [comment]
I already had a bunch of explanations of what's going on with this in #68468, so I'm not gonna repeat it here. But since that PR is an insufficient solution that leaves other bugs I was looking into doing a C++ fix for tools with magazines. Turns out the easy fix for that (handling tools like guns in `Item_modifier::modify`) isn't possible because `item::magazine_compatible` (used in `item::ammo_set`) only checks item restrictions and not flag restrictions. Since at least all the electric tools rely on that it instantly blows up when trying to load those with battery, since there are no compatible magazines. The only reason it didn't blow up for guns, yet, is that apparently none of them use flag restrictions.
