### ISSUE TITLE
overwhelming amounts of anomalous readings from NRE in dungeons 

### ISSUE THREAD

**Issue by Uranoclaire** [CleverRaven/Cataclysm-DDA#67930]
### Describe the bug

Running the portal dungeon for the length of the storm allowed me to acquire 40-something anomalous NRE printouts

### Attach save file

N/A

### Steps to reproduce

1. Create a character with an NRE recorder and decent gear
2. set weather to portal storm
3. enter dungeon
4. run through several times, fighting the creatures as they come, I only know that it's a number of cycles reasonable to do in standard gameplay.
5. turn in printouts for ludicrous profit

### Expected behavior

I would expect anomalous reports to be, while profitable, not be so profitable as to leave you the richest human in the state. Mainly because even if they give you 10 coins for the first one, the HUB would realize pretty quick that these readings are easy to come by for anyone willing to interact with portal storms.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/134988746/e6872d6b-099b-44f5-84ee-588414557598)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3208 (22H2)
- Game Version: a2ad06d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Aftershock [aftershock],
    Bionic Professions [package_bionic_professions],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    <color_cyan>Arcana and Magic Items</color> [Arcana],
    <color_cyan>Arcana</color>/Aftershock Patchmod [Arcana_aftershock_Patch],
    Bombastic Perks [bombastic_perks],
    Extra Mutated Scenarios [extra_mut_scens],
    Mind Over Matter [mindovermatter],
    SpeedyDex [speedydex]
]

**Comment by SariusSkelrets** [comment]
One thing that could work is giving each reading-giving monster their own reading, which would only be accepted a limited time per monster

Assuming each reading is accepted once, It's still 90 HubCoins (4500$ barter value) and likely to increase if someone adds more monsters with significant reality altering powers but it will prevent cheesing the trade system like that and encourages exploration instead of just going in a dungeon

**Comment by Nebnis** [comment]
I think the reasonable fix is just make that hub01 only accepts 1 reading  per storm and they will take most valuable one first. Then we can adjust the amount of coins given per storm.

**Comment by KHeket** [comment]
Dont forget, that your character will be deadly tired, you will need yo sleep for 3+ days, and also there is penalties effects for few days or weeks, if you are traveling via dungeon for too long, and you also can meet dangerous creature after leaving the dungeon, and you will be very weakened to fight it. So yea, nerfing this is good idea, but dont nerf it too strong because of lots penalties and very useless awards

**Comment by KHeket** [comment]
I think, to balance it, it will be good to add nre printout for each completed lvl of dungeon with 5 gold price and make better half to drop something like "portal monster printout" with 2-3 gold price. So, you can still make lots of coins, but it will be balanced with lots of penalties
