### ISSUE TITLE
NPCs that were attacked by Absence during Portal Storm should not be left naked

### ISSUE THREAD

**Issue by TheLightTwist** [CleverRaven/Cataclysm-DDA#67943]
### Is your feature request related to a problem? Please describe.

With the new versions came portal storms. Some people like them, some don't, but there was one big problem with them.
During a portal storm, an Absense enemy appears, which causes all items on the attacked to fall under his feet. The mechanics are interesting, if only NPCs could pick their gear back up afterwards. Imagine how I feel when I have 4 people in my base, and after a portal storm I have to manually put every item back on each of them, one by one, and give them weapons, etc., as well.

### Solution you would like.

A suitable solution, it seems to me, would be the following. You can assign an invisible tag to an item that an NPC uses/wears as clothing or in his inventory, signifying ownership. If you manually exchange items with an NPC, the tag should be erased accordingly. The same should be done if an NPC has taken an item temporarily and then discarded it himself (e.g. a tool for completing a task). The mechanics of how these tags work can be such that if an NPC doesn't think he is in danger at the moment (or for a certain period of time), he will try to pick up his items and use/wear them if he can get to them.

**Comment by I-am-Erk** [comment]
huh. This is an interesting way to highlight important npc issues.

I wonder if the 'favourite' system we use as players could be refactored up to the Character level (if it is not already) and then we could have NPCs favourite their gear as part of the Absence attack, and be scripted to pick up favourited gear? Being able to get NPCs to favourite their gear and weight that gear more important would be a very useful feature in other settings.

Otherwise though, we may need a dirty hack for this like stopping Absense from working on NPCs.
