### ISSUE TITLE
Allow automatic gas pumping.

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#68]
Add an option to latch the gas pump when pumping gas, which will make gas continue pumping if you walk away.  This would spawn a "pump hose" item that would "click" when it's finished, and you'd 'e'xamine it to disconnect.  Failing to do so would tear the hose off the pump, triggering a massive gasoline spill and disabling the pump.  Possibly damaging the vehicle as well.
##

**Comment by kevingranade** [comment]
A lot of this has been implemented with the jumper cables infrastructure, should be much easier to add now.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
