### ISSUE TITLE
Long hang when entering some areas.

### ISSUE THREAD

**Issue by Nitro-Carwash** [CleverRaven/Cataclysm-DDA#68018]
### Describe the bug

When entering a particular region of my city, the game hangs for about 20 seconds before resuming.

### Attach save file

[Friday Harbor-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12530618/Friday.Harbor-trimmed.tar.gz)

### Steps to reproduce

After opening the save, walk south.

### Expected behavior

No hang.

### Screenshots

https://github.com/CleverRaven/Cataclysm-DDA/assets/76269976/55b65ddc-acc5-47b0-9bcc-bcb3939647f2

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1586 (21H2)
- Game Version: 53869b2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved],
    Alternative Map Key [alt_map_key],
    Mythical Martial Arts [MMA],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    <color_cyan>Arcana and Magic Items</color> [Arcana],
    <color_light_green>Cataclysm++</color> [Cata++],
    <color_yellow>Mythical Martial Arts - Mods Extension</color> [MMA_Mods_Extension],
    <color_cyan>Arcana</color>/Magiclysm Patchmod [Arcana_Magiclysm_Patch],
    <color_cyan>Arcana</color>/<color_light_green>Cata++</color> Patchmod [Arcana_Cata++_Patch],
    Mind Over Matter [mindovermatter],
    Culinary Days Ahead [culinary_days_ahead],
    Miscellaneous Magiclysm Expansions [demon_spider_a],
    No Bionic Slots [no_cbm_slots],
    SpeedyDex [speedydex]
]

**Comment by RenechCDDA** [comment]
I profiled this after it came up on discord

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/84619419/04543fbb-3818-4b3b-ab41-fcef968b6176)

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/84619419/6beba25a-0e4f-4f4c-9845-eadceb8d39f2)

**Comment by Kamayana** [comment]
Pausing partway through the lag spike, it appears to be cash cards that are causing problems:

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6759778/771260b7-9875-4a55-9bff-3e12f4ff4615)

If I unpause and pause again, the contents size just keeps growing:

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6759778/71e8a56b-e4f8-4e61-b7aa-a52c55e1210e)

I found a card in the southwest corner of the office building northwest of the saved position that's behaving very weird, lagging the game when I open the pickup menu and *really* lagging if I try to pick it up.

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6759778/763fcf40-f30a-40d1-9510-2b71423fd850)

I wonder if a migration pocket is wigging out.

**Comment by oosyrag** [comment]
I have experienced similar freezes on the aircraft carrier, probably related. Freezes occur in specific repeatable locations. During the game, I noticed cash cards failing charge migration errors while playing and when loading the game on or near the carrier.

The specific error - https://discord.com/channels/598523535169945603/642349261320880128/1140114795480223754 (By someone else who ran into it on the carrier)

[Canyon_Creek-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12532581/Canyon_Creek-trimmed.tar.gz)

I hope this is the right save. Head south beyond the stairs to experience the freeze. It happens in various other spots on the carrier, but this one is the longest and I notice it the most. It also happens when heading north past the stairs. Walking around normally after the lag recovers is normal, until moving far away enough and coming back.

**Comment by Kamayana** [comment]
Yeah I think there's something weird going on with cash card charge migration from #60885. It's possible it only affects cash cards that are generated to sit out on the map in the open, since cash cards inside wallets seem to be working fine.

**Comment by oosyrag** [comment]
Any way to find and nuke these cards out of the save file directly? I'm not looking forward to hunting them down in game...

**Comment by RenechCDDA** [comment]
> After actually picking it up, a huge number of cash cards spilled out onto the ground:

That's amazing, but would suggest this is not actually an issue that needs to be solved as it's a one-time migration issue, if I understand.

**Comment by RenechCDDA** [comment]
Now that I think of it, cash cards are not comestibles. So I guess @mqrause should be mentioned so they can give any input if they have any.

**Comment by mqrause** [comment]
From what I understand, cash cards shouldn't have charges but be a container with money in the pocket. So I would guess there is some broken way to spawn them that causes them to have charges. And because #60885 made charge migration the standard behavior, they get duplicated instead of just axing the charges.
A simple kinda-not-really-hotfix could be adding cash cards to the charge removal blacklist, so they won't be migrated at least. But that's just a poor bandaid for whatever real issue is behind this.

**Comment by RenechCDDA** [comment]
So in that particular map the spawn is on the loffice_tower_7 mapgen, using the office_palette palette, and the cash cards appeared from the office_supplies item group spawn.

Not seeing many ways it could go wrong, but the office_supplies group uses the old method of defining item groups which might be part of the problem?

palette entry:
`      "r": [ { "item": "office_supplies", "chance": 65, "repeat": [ 1, 10 ] } ],`

office_supplies entry:
`[ "cash_card", 5 ],`

**Comment by mqrause** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/a677ef2fd1d2b55534e85f451f13a9b542f9d921/src/item.cpp#L317-L320

Seems to be that `rand_charges` entry in the cash card definition.

**Comment by huix11** [comment]
thank you
