### ISSUE TITLE
Smartphones are 5 cm in length, smartphone cases are 18 cm.

### ISSUE THREAD

**Issue by ampersand55** [CleverRaven/Cataclysm-DDA#68028]
### Describe the bug

Smartphones are 5 cm in length, smartphone cases are 18 cm. #67995.

### Attach save file

N/A

### Steps to reproduce

N/A

### Expected behavior

Smartphones and smartphone cases should be equally long. 

18 cm seems very big for a smartphone case. E.g. iPhone 14 , and Samsung Galaxy S23 are all a little over 14 cm. 

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.14393.6085 (1607)
- Game Version: f07f373 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda]
]

### Additional context

Also the smartphone case doesn't fit in an armband pouch anymore, and those are generally designed specifically to hold a smartphone.

**Comment by marimarigi** [comment]
Once some professions have clothing that fits a smartphone (of a realistic length), I'm going to set the length of it. I thought it would not be a problem to set length of smartphone cases first.
Smartphone cases are actually designed for iPhone 14. Because I read an article that said it is a best seller in the USA this year.
