### ISSUE TITLE
M249 bipod gets detached along with scope.

### ISSUE THREAD

**Issue by oosyrag** [CleverRaven/Cataclysm-DDA#68107]
### Describe the bug

The unremovable m249 bipod gets removed when detaching a high end scope with red dot, instead of the red dot.

### Attach save file

[Canyon Creek-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12582565/Canyon.Creek-trimmed.tar.gz)

### Steps to reproduce

Detach high end scope gunmod from wielded m249.

### Expected behavior

Scope and red dot are removed.

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: OnePlus; Model: HD1900; Release: 12; Incremental: Q.202303230244; 
- Game Version: 2c8ae07 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

It still happens when the red dot is removed first.

**Comment by Bobtron** [comment]
[Leamington.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13040031/Leamington.tar.gz)
Reproduced this issue on the latest experimental, compiled on Mac OS X. (Ran into a bunch of errors loading the save file, maybe because its from android)
Error looks like it happens even without attaching the red dot sights, and it happens for (all?) guns with integrated bipod, such as the m240
