### ISSUE TITLE
Nerf/remove/edit/update/transfer to mod shadow lieutenant or make its death rewardable

### ISSUE THREAD

**Issue by KHeket** [CleverRaven/Cataclysm-DDA#68100]
### Is your feature request related to a problem? Please describe.

Adding such monster is fun and insterting, even for lore, but its also bad with next list of reasons, because this creature is:
fast
Invisible in shadow
Have high regeneration
Have lots of hp
Have very high speed
Always teleports to you, even if you drive car at high speed
Spawning enormous number of amalgamations, half of wich is acidic and can also acid damage you throhg acid proof clothes
Destroing usefull plants and threes, which are used to feed up the player
Will find and spawn at you like simple script
After survival - you will have lots of territory, littered by ressuractable amalgamations

Its very far from realism. Even with sci fi atmosphere of the game. It ok for MoM or magiclism, but not for vanilla. Its will not be fun, realistyc and good for vanilla

To make amalgamations - you need energy, you need flesh, you need matter, because amalgamations are spawning from dead creatures. You cant just make monsters from air

### Solution you would like.

There is few solutions, one or few of which should be realized:
1) Nerf stats of shadow lieutenant to make it more killable. Creatures shouldnt be fast, tough and deadly with spells at once at least in vanilla
2) Nerf amount of amalgamations. If its some magic or artifact power - its should not spawn TONS of amalgamations, even artifact, which you can fing in game - have charges. So, is shadow lieutenant can spawn only 10-20 amalgamations - it will be quite good, because if its power going from artifact - it will be realistic nubmer for it. If its going from its own power - 10 monster will be enough, because you need a lot of energy to materialize creature, even if you are using materials from surroundings, like grass, trees, plants and etc, even if you are 100-1000+ aged creature, you cant make matter from nowere
If shadow lieutenant summoning amalgamations from portals - opening portals is also energy consuming for creature, so in this case its also should be nerfed
3) Make its rewardable. This creature just cant spawn such lots of monster by its own power, it should have artifact, and, like chunks of matter - transform into artifact upon death. Its should drop few artifacts with is power. Like, 1 artifact, witch will destroy plants in radius, 1 artifact with invisibility in shadow, 1 artifact with summoning creatures
Or, as variant - it can spawn 1 artifact with oppisite of power. We have artifact effect with tree growing, so, if the powers of shadow lieutenant is its own - it will be good, to spawn artifact upon its death, wich will spawn trees and brushes. Its also solves problem with trees, wich you cant grow, and lots of removed by shadow lieutenant plants
4) Make it spawn unresurrected kind of amalgamations or simular creatures, because it big pain to walk around and looking for this dead bugs, and they also can destroy you base and animals after ressucreating
5) Remove ability to destroy plants and trees. It can just detroy for no reasone lots of valuable plants, bushes and trees, some of with cannot be replanted
6) Make this creature be located, like other monters, dont spawn it from air. Like already existed monsters. 
Or make shadow lieutenant be marked at map like portal storms
"Shadows around you starts shaking, you feel the dark became more dense"
And after that message you will have mark at map, where the shadow lieutenant have spawned, and you can fight it, or you can run from it. Because it also have no reason, why shadow lieutenant know where you are
Yes, it can hunting for you to transform you into shadow lieutenant for blob army, but knowing, where is your victim - is also magic

### Describe alternatives you have considered.

Leav all as it is, but for now - its just very dangerous and very very annoying. Because shadow lieutenant for now:
Hard to kill
Very fast
Spawning from nowere
Spawning lots of creatures, wich will ressurect, and you should clear the area in future
Disturb you from making night tasks
Creating super dangerous situations, like making you shining at night, and zombies can kill you
Destroing cars, plants and structers, and amalgamations make the same, and also they can kill your npc and farm animals

**Comment by ZhilkinSerg** [comment]
They are WIP I think

**Comment by RenechCDDA** [comment]
I am pretty happy with how they've been doing, although there are some tweaks I have in mind. "Make killing them rewarding" is certainly not one.

**Comment by Nebnis** [comment]
Ye i think the most egregious thing is how often they spawn amalgamations and how soon they show up in the game. Amalgamations by themselves are incredibly deadly creatures then on top of it, you will get tons of them surrounding you. It makes no sense this specific unique deadly liutment target you either. It feels too "gamey" for lack of better words.

I think you talked about making it only spawn after certain creatures are killed which feels better overall. Something like 5~10 necromancer/lich kills or some equal evolution down the line.

**Comment by KHeket** [comment]
> I think you talked about making it only spawn after certain creatures are killed which feels better overall.

I think, there is one more realism variant. How do shadow lieutenant can targetly find you? You are just human, like lots of others, and you dont have any speacial smell or energy, than others. And as a good variant - make the shadow lieutenant trigger only when you have artifact in inventory. It good solution for few reasons:

1) Artifacts have speacial energy, smell, aura, that can attract shadow lieutenant to you. That why he can know, where are you, even in dark
2) It will make behavior of shadow lieutenant predictable for skillfull players
3) If you want to go to night raid - you can just leave artifacts at base, so shadow lieutenant will not make ultra deadly random early situation, will not spread his pets aound your base and will not eat lots of usefull plants
4) If you have artifact - so you are most likely skillfull enough and have good weapon and armor, because to obtain it - you should survive portal storm and kill chunk of matter, or you should successfully raid a lab, or be lucky and skillfull enough to find and kill amigaras in mine cave, or even find a big standart mine cave, which have very low chance of artifact in the end of lond cave labirint, or you should find and complete very-very rare temple, which can't be complete without needable cbms

And it will be also a realistic reason, why shadow lieutenant targeting you, but not others survivors? Blob army needs special, powerfull lieutenants, and hunting random human dont worth it, because its better for them to raid hell raders bases or survivors camp, or hub 01 mercenaries, but when shadow lieutenant smell a power of artifact - it can understand, that the holding it person is speacial, because the reasons above
5) And because this annoying encounter have no reward - you should be able to avoid it. Because as for now, only profit from it is only lots of amalgamations for dissecting
6) Its easy to code
7) Its very new and low skill player friendly

**Comment by ADekema** [comment]
I don't like the idea of a blob lieutenant hunting you for artifects. Why would the blob care about artifects much less create a creature to be attracted by them.

Instead of focussing on realism I think it would make more sense if the lieutenant was full on supernatural/eldritch. We are talking about a potentially transdimentional hyper evolved zombie.  Think making it a full on boogyman that hunts the night and summones shadowy reflections of other hyper evolved zombies in perellel dimentions. Some ways to do this would be:

1. Replace the amalgamations with shadowy reflections of highly evolved zombies from a differant blob dimention. These should be more evolved than the zombies we have in game currently so they could be proper alien. Maybe make a shadow version of a hulk or skeletal juggernaut as a hint what the shadows are. They should also be able to just like the lieutenant be able to see you wherever you are. These should meld away after they die.

2. Make the lieutenant and shadows go through physical objects. 

3. Make the shadows and lieutenant afraid and be damaged by light. 
 
4. Make sure many of the shadows have reach grabs and pull. Also create one that can do a weak electric attack.

5. Remove the dead plant feature. I didn't appreciate portal storms turning my crops into alien grass. I also don't appreaciate the shadow destroying my orchered.

These changes would create a very different dynamic. You can keep yourself safe by having a light source. Just remember that the shadows will accumilate intp a horde just waiting on the edge of the light and if you get to close they will pull you into the darkness and tear you apart. If you are using a flashlight in the woods to keep them at bay, you have to pray you don't get zapped and your flashlight destroyed by a electric shadow. If you made a campfire you better have enough fuel to last the night before you are surrounded on all sides and you won't get any sleep becease you need to keep the fire lit. And if you stay indoors you will have to stay away from the walls where the shadows hide. You might have a torch but those only last two hours  so you better find another solution before than.

It also gives the lieutenant a obvious weakness that a talented player could exploit. You could potentially trap the lieutenant in a  building if the sun rises and it has to stay inside. You could block it path with few well placed lightsources to corner or even trap it. It might also be interesting to have flashbangs and dragonbreath shells do damage to it becease they produce so much light.

It would also fix the problems of destruction of structures, plants and vehicles. It would mean that it wouldn't leave a mess to clean up.

**Comment by RenechCDDA** [comment]
> 1. Replace the amalgamations with shadowy reflections of highly evolved zombies from a differant blob dimention.

I don't want to make it too deadly, but that's just my personal opinion. It could definitely use something other than amalgamations, but they are a nice tie-in and already existed. I am open to hearing about ideas though.

>2. Make the lieutenant and shadows go through physical objects.

Can be done, but I see few cases where this would be useful as the design is based around *not* chasing you into enclosed areas. Enclosed areas also become very much "statchecks", where you both get into melee and pummel each other until one is dead. I would like to avoid such design.

(I am not super happy with the current binary design where speed is the determining factor and it either is faster than you or isn't, but it is... something. I need to look into making an EoC which teleports it away after it takes some damage, so that running it down at least requires several *attempts* as opposed to just one and then wailing on it.)

>Make the shadows and lieutenant afraid and be damaged by light.

Again, can be done. A "afraid of light" flag for monsters was added shortly during/afrer its PR, and I should just look into that.

>Remove the dead plant feature. I didn't appreciate portal storms turning my crops into alien grass. I also don't appreaciate the shadow destroying my orchered.

It cannot destroy crops. It can destroy *wild plants*, but that is fully intentional. It is one of the many, many things that is killing the Earth. More specifically, it is reshaping the blob infection which is already there and spread throughout the ecosystem.

Thematically speaking it *probably should* kill crops... but I am personally okay with the idea that it does not. I agree that it would be very frustrating as a player if my fields were destroyed by this thing.

>You can keep yourself safe by having a light source. [...]

Yes, all fine scenarios! I have been interested in a possibility where it will just follow you (and won't attack) if you have a light source, waiting for the light to go out. But that would require pretty major changes to how the AI decides between attacking/moving/doing nothing.

**Comment by Nebnis** [comment]
> I don't want to make it too deadly, but that's just my personal opinion. It could definitely use something other than amalgamations, but they are a nice tie-in and already existed. I am open to hearing about ideas though.

You could use the [tainted shadow](https://cdda-guide.nornagon.net/monster/mon_tainted_shadow) or shadow creatures? They feel more thematic than amalgamations and less deadly too, you could even maybe make an alt version and crank up their attacks a bit too. I really dislike amalgamations being used, they are too deadly, more so than zombie evolutions with all their massive amount of speed+armor+damage they come with, I would even agree with zombie evolutions instead like liches and skeletons. 

> (I am not super happy with the current binary design where speed is the determining factor and it either is faster than you or isn't, but it is... something. I need to look into making an EoC which teleports it away after it takes some damage, so that running it down at least requires several _attempts_ as opposed to just one and then wailing on it.)

This is something interesting you could make, maybe is it possible to teleport him after he takes damage and then keep his hp for next time you fight him? Then you could crank up his hp pool and reduce some of his defenses and speed. The player would have the choice of whittling him down and running a risk of dying or just running away like usual. The fight would become less of a stat check or cheesing and more of a putting up a fight.

**Comment by ADekema** [comment]
> You could use the [tainted shadow](https://cdda-guide.nornagon.net/monster/mon_tainted_shadow) or shadow creatures? They feel more thematic than amalgamations and less deadly too, you could even maybe make an alt version and crank up their attacks a bit too. I really dislike amalgamations being used, they are too deadly, more so than zombie evolutions with all their massive amount of speed+armor+damage they come with, I would even agree with zombie evolutions instead like liches and skeletons.

I just typing exactly this in my reply before you beat me to it. I completely agree. I would still make a few new shadow creatures that are a bit stronger than the ones in game. Also make them part of the zombie instead of nether faction to avoid wierd agro.




> Yes, all fine scenarios! I have been interested in a possibility where it will just follow you (and won't attack) if you have a light source, waiting for the light to go out. But that would require pretty major changes to how the AI decides between attacking/moving/doing nothing.

I think it should attack you even if you have a lightsource. This would create a dynemic where the shadows it spawns can´t get to you on account of the light but they still surround you on all sides. Meaning that if the light goes out for any reason you get swarmed from all sides. So you might be trapped in in the woods or a room next to fire until the sun rises or get suddenly swarmed becease a electric enemy fried your flashlight.



> Can be done, but I see few cases where this would be useful as the design is based around _not_ chasing you into enclosed areas. Enclosed areas also become very much "statchecks", where you both get into melee and pummel each other until one is dead. I would like to avoid such design.

The shadow only appears if you are in the forest or a field, right? So if you spot it you will always be outside and if you go into a enclosed area that is the players own decision. So if players get trapped in a enclosed space by the shadow and hurt/killed becease of it than that is becease of their own mistakes which cataclysm DDA is all about. I also dislike the idea of the shadow leaving you alone just becease you wend inside. This would make it way to easy to just go inside somewhere and sleep until morning when it goes away. 

If the shadows are afraid of light than a player in a enclosed space isn´t forced to engage in melee as long as they have a light/firesource. Being in a enclosed place would even be adventages as unlike when you use a lightsource outside you don´t have to worry about anything spotting you from afar. You would only be forced into melee if you didn´t have a light or firesource or you run out of power/fuel which I would blame on the player not design.
