### ISSUE TITLE
Guilty about Howling Waif

### ISSUE THREAD

**Issue by BlazingRoach** [CleverRaven/Cataclysm-DDA#68114]
### Describe the bug

So I've noticed that whenever I kill a howling waif my character feels guilty. But my character has already gotten over killing zombie children. I'm just wondering if that's supposed to happen or if that's a bug. Tested it with another character and found that the same thing was happening there.

### Attach save file

N/A

### Steps to reproduce

1. Kill a lot of zombie children
2. Get over it
3. Kill Howling Waif
4. Cry

### Expected behavior

I imagine that since a howling waif is just another child zombie I should probably feel the same emotions when killing it as any other zombie child.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.2134 (22H2)
- Game Version: 38e387c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots]
]

### Additional context

Not sure if this applies to any other child zombie types.

**Comment by PatrikLundell** [comment]
Could it be that zombie child types are (erroneously) treated separately when it comes to overcoming emotions, so you'd have to kill enough of each particular type? If that was the case ankle biters (and other variants) would also be their own pool.

**Comment by Karol1223** [comment]
> Could it be that zombie child types are (erroneously) treated separately when it comes to overcoming emotions, so you'd have to kill enough of each particular type? If that was the case ankle biters (and other variants) would also be their own pool.

I believe that is how it is handled, yeah. I've noticed something like that with anklebiters back in the last experimental cycle but never bothered to report or reproduce it.

**Comment by Papaya-Plan** [comment]
It makes sense to me that after killing 100 children, you're not really gonna care anymore. And it shouldn't matter if half of them were regular zombie children and half of them were waifs. So the function for applying guilt after killing something should check for the total amount of similar monsters you've killed, instead of just that kind of monster.

Obvious (to me) solution: Add a new JSON property: "guilt_category". When a guilt-causing monster with a guilt_category is killed, check the total number of all monsters with the same guilt_category to calculate guilt effects. But I'm not sure what the best way to implement that would be.

I can easily figure out the worst ways: Either iterate through the list of all kind of monsters the player has killed, and check the numbers of monsters in the same category. Or, even worse, check all existing monsters, find the ones in the same category, then check how many of each the player has killed.

Ideally, the game could just quickly access a list of all monsters in a given category: func("zed_child") -> [list of relevant zombies] (which might just be zombie children and howling waifs, actually?). That wouldn't be too hard to just make a JSON for, but also I'm pretty sure that's a bad idea don't do it. Ideally, when the game is parsing the JSON, it stores a table-thing somewhere, and each time it finds a monster with a guilt_category, it adds that category to the table, if not present, and then adds that monster to that category. Then you've got a quick and easy way to check relevant monster kill counts for the spell_effect::guilt function.

Or you could just hardcode it to check how many waifs you've killed when you kill a child, or vice-versa, but that seems hacky.

**Comment by PatrikLundell** [comment]
If possible, zombie children could draw from an abstract base monster that has the guilt-inducing property (possibly 'a' guilt inducing property string, if there are more guilt inducing critter groups, like e.g. zombiefied parents or close friends), and then use copy-from to define all other zombie children variants. All of them would probably have the same size (small) and a common loot table (as they presumably all were regular children before zombiefication, rather than having different types representing different groups of children, unless you want something specific like a youth correction center zombie).

This is basically a slight modification of what @Papaya-Plan suggested.

**Comment by Papaya-Plan** [comment]
Most kinds of zombie children don't cause guilt;  base zombie children and howling waifs are the the exception, not the norm. It would be odd to feel less guilty be killing things that don't make you guilty to begin with. The only other guilt-inducing child I can find is a plant zombie from TropiCataclysm. Other guilt categories I can find would be hatchlings from DinoMod, and possibly humans (If you've killed enough NPCs to stop caring, then killing a panicked person probably won't bother you either. I don't know if you can desensitise yourself to killing people, though).

I think there's been discussion in the past about other monsters inducing guilt (e.g. cats and dogs), and you could potentially have some characters need to get used to hunting wild animals to survive, but also not be incapable of ever getting used to it either. So, potential categories for "pet species" and "wild animal".
