### ISSUE TITLE
Old Guard Rep's Exodii Recon is Impossible to Complete

### ISSUE THREAD

**Issue by gettingusedto** [CleverRaven/Cataclysm-DDA#68152]
### Describe the bug

Me and some people had some issue with Old Guard Rep's Exodii Recon mission. From what i found in the mission doc
im starting to think that mission is impossible to complete cuz
```Missions with goals MGOAL_GO_TO and MGOAL_GO_TO_TYPE behave differently depending on whether the player gets them from an NPC or from another source (e.g. from a starting scenario):

    When given by an NPC the mission is an escort quest: to complete it the player has to talk to the quest giver while standing at the destination. Note: make sure to set the quest giver to follow the player or the mission will be impossible to complete.
    Otherwise the mission is simple traversal - to complete it the player only has to reach the destination.
```
Since the mission require the rep to follow the player into the exodii place and the rep can't follow the player, it makes the mission practically impossible to finish. Debug Teleporting the old guard rep and myself into the exodii place completes the mission.

### Attach save file

N/A

### Steps to reproduce

1. Go to the refugee center and find the old guard rep,
2. Do/debug mission complete the first 2 old guard rep missions,
3. Do the third mission normally, see that it doesn't complete.
4. Make the old guard follow you (through debug mind control) and debug teleport them into the mission marker.
5. go back into the exodii place and talk to the old guard rep
6. see that the mission is completed.

### Expected behavior

Not needing the old guard rep being there to complete it.

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: samsung; Model: SM-A710F; Release: 7.0; Incremental: A710FXXU2CRC2; 
- Game Version: f12487c [32-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved],
    Aftershock [aftershock],
    cable stuff [cablestuff],
    LuckySlotmachine [luckyslotmachine],
    Mind Over Matter [mindovermatter]
]

### Additional context

Oddly enough, Rubik has a similar mission to give the player, which is to check out the Hub 01 place. That mission works as expected than the old guard rep one. I wonder why...

**Comment by I-am-Erk** [comment]
The mission shouldn't be an escort mission, it should be like rubik's where they ask you to go to the hub and report back. It lists `"goal": "MGOAL_GO_TO",`, while Rubik's use mgoal_go_to_type, which may be part of the difference; go to type may not expect escort.

If your guess is right, the solution would be either to change it to go_to_type (which might cause problems since it's supposed to be a breadcrumb). However, I see that the teamster missions use go_to and I don't think they're having this problem.

It would also be possible to use variables to circumvent this. If you have the variable 'met rubik' and have this quest active, then you should be able to talk to the old guard rep and turn in the quest. That would be pretty easy to add.

**Comment by gettingusedto** [comment]
From what i noticed between old guard rep's mission and rubik's mission, rubik gave the mission a bit differently than the old guard rep; in a sense that the mission rubik given does not go through the default way of npc giving missions. The teamster also did what rubik did and just don't use the default mission briefing thing.

**Comment by I-am-Erk** [comment]
That's entirely possible. The old fashioned mission interface has a lot of automatic bits

**Comment by MrDraMaster** [comment]
you have to talk with the rep about the robots before you can turn in the mission, iirc, so that makes it seem weird since after you go to meet Rubik & return to the rep, the first screen only shows the "I'm not done yet" option for the mission

but then you can talk with the rep about the robots and _that_ completes the mission requirements proper and allows you to turn it in

(I just completed the mission yesterday)

**Comment by gettingusedto** [comment]
@MrDraMaster It is confusing because the old guard rep tells you to recon the place, not make first contact. So the way this can be fixed is to either rewrite the dialogue so it clearly tells you to make first contact with the exodii, or make the darn marker trigger.
