### ISSUE TITLE
Learn languages ​​using cdda

### ISSUE THREAD

**Issue by wangy9451** [CleverRaven/Cataclysm-DDA#68179]
### Is your feature request related to a problem? Please describe.

In the previous version, a function was added to switch the current language back to English instantly by pressing a key. I have actually used it for a while and think this function needs to be improved:

### Solution you would like.

There are many texts on the interface that have not been successfully converted.

It should be able to be set up so that two different languages ​​can be switched to each other, instead of only being able to switch back to English. In other words, you can set language a to Japanese and language b to Chinese.

The switching between the two languages ​​should be set to automatic switching, that is, you can choose to switch every few rounds or every few seconds. On the other hand, you should also be able to switch manually, but not by pressing a button. Instead, it switches to language b when you hold it down, and switches back to language a when you release it.

This function is very powerful for language learning and game text translation, but unfortunately it is not perfect. I hope that professionals can improve it and help more people who like cdda but need to learn languages.

**Comment by AlbertNewton** [comment]
Is the keybind actually to switch back to English, or is it just to switch back to the system default language?
If the former, that's bad and ought to be changed to be the system default language. And if it switches back to system default, it would be a clear improvement to have another keypress switch it back.

**Comment by wangy9451** [comment]
> 鍵綁定實際上是切換回英語，還是只是切換回系統預設語言？ 如果是前者，那就不好了，應該將其更改為系統預設語言。如果它切換回系統預設值，那麼再按一次按鍵將其切換回系統預設值將是一個明顯的改進。

It's not a default language, but switching between language a and language b. It's a pity that I don't have programming ability yet.

**Comment by KHeket** [comment]
I am using this usefull function to for russian/english version, because same mode manger dont work correctly at any langeuges except english, I have few good ideas

To easily implement this feture, you can add in option for "additional langeage". As example. You make english as deffault langeage and russian as additional. Game will run at english by default, but after pressing change language button - in will be changed to english. So you can make the game very comfy just by this function. You can make chineze language by default and english as additional, so the game will run at chinize and after pressing the key it will changing to english

What is about to make also function to let the game recognize two languages at once? I dont know, how it will be easily to make it recignize all langeuges, but, I think - it will be not that hard to make it work with two langeuges at once. As example
You make english as default language and russian as additional, and when you will type knife or "нож" (knife in russian) - the game will find this items no matter, is english or russian langeage is active at the moment

**Comment by KHeket** [comment]
This super feature was added by @MarcusAseth , I dont now, will he answer, but I will hope that he can make some more super usefull updates

**Comment by MarcusAseth** [comment]
> This super feature was added by @MarcusAseth , I dont now, will he answer, but I will hope that he can make some more super usefull updates

I went back to learning japanese and 3d graphics so I don't have the mind to focus on programming as well, so I won't be the one doing this, but feel free to.
The reason I had originally choose English as "fixed primary language" was because the game is originally made in english, and translations are not necessarily literal, so each already diverge from the english a bit. So if you take a chinese translation that diverge a bit from the source english and compare to a japanese translation that diverge a bit as well, you might be comparing two pieces of text that have significant differences and getting more confused than anything. For this reason, I thought of that as not useful and haven't implemented it that way on purpose.
That said, if I where to implement it (which I'm not because my mind is not into programming right now), for simplicity sake I would keep two variables for "language A" and "language B" - when the language is changed from the option, the language stored in "Language B" slides over to "Language A" and "Language B" takes the new language set. 
So one would simply need to select "Japanese" and apply, then open the options again and change to "Chinese" and apply again, and the function would work with those two without the need of figuring out how to add more options or cluttering the option menu for a feature that's this niche ;)
