### ISSUE TITLE
Avoid getting the exploded Boomer bile in your eyes.

### ISSUE THREAD

**Issue by mikkatenka** [CleverRaven/Cataclysm-DDA#68209]
### Is your feature request related to a problem? Please describe.

The explosion when killing Boomer puts bile in your character's eyes, limiting his ability to dodge and block.
Nowadays, you'll magically end up covered in bile, which is undodgeable.
In my opinion, if you protect your eyes with your arms or turn your head away when you finish off Boomer, you won't get bile in your eyes.

### Solution you would like.

There is a chance to dodge Boomer's bile using the dodge skill.

### Describe alternatives you have considered.

This can be avoided by wearing goggles or a hood.

**Comment by RenechCDDA** [comment]
Seems unreasonable to dodge an explosion.

**Comment by PGR-14** [comment]
> Seems unreasonable to dodge an explosion.

I think it's more about "looking" away to avoid being blinded, not the damage or anything.

**Comment by fairyarmadillo** [comment]
You should absolutely be able to avoid getting the stuff in your eyes, especially when you're the one causing the enemy to burst.

**Comment by oosyrag** [comment]
It's enough junk to cover a 9 sq ft radius in bile, you're getting a bucket of the stuff on you.

**Comment by fairyarmadillo** [comment]
Nobody said it wasn't getting on you. We're talking about specifically getting it into both of your eyes and blinding you every single time for the same duration no matter what you do.

**Comment by oosyrag** [comment]
It's a layer of slime dripping off your head, imagine it doesn't need to get into your eyes to blind you.

**Comment by Kywi001** [comment]
Quite easy to implement a way to "stop getting biles in your eyes"
There should be a function ingame to
1. Waiting will make the player try to wipe the bile off when wearing:
- Swimming Goggles
- Safety Glasses
- Snow goggles
- Welding Mask
- Helmets with Visors or Visor inserts
- other eye protection that are considered closed off. (This doesn't include Sunglasses and other glasses as bile could still flow down your eyes from your forehead and/or masks with eye holes, for obvious reasons)
2. When waiting without eye protection, and when you have a clean towel in your inventory, the player should try and wipe the eyes clean (just a QoL instead of needing to go to the inventory to activate this function)

**Comment by Zireael07** [comment]
If this is about "don't get bile in eyes", the title of this issue should be changed. Dodging bile won't happen for reasons @oosyrag mentioned

**Comment by mikkatenka** [comment]
Bile is not slime. It can be treated with eye drops.
I want the characters to do their best.
Avoid because you know something will fly in your face.
There is also a hood on the head, so please use it.
I wish there was a countermeasure in-game.
I'll close this because my conversation skills are poor.

**Comment by Zireael07** [comment]
Poor conversation skills or good conversation skills, the proposal makes sense and should be reopened.
