### ISSUE TITLE
[Market exploit?] High price berries, despite having bushes full of them near centre in their own field

### ISSUE THREAD

**Issue by NickEmbased** [CleverRaven/Cataclysm-DDA#68263]
### Is your feature request related to a problem? Please describe.

This is my first time posting. I found that price for the berries is absurdly high, you can easly exploit trading to get a LOT of money that you can almost all items from a trader in a single day. This feels quite wrong, and all other ways to get money are getting largery uneffective.

1.Wait for the summer
2.Go Outside and gather full backpack of berries
3.Trade guns and ammo for a resourse that is (infinite) around.

AND also it does not make sense that centre buys food for big price, however they have own field that is (barely) protected and have berries, bushes and trees that are not harvested, evne though it would be safe since its really close to the enterance

### Solution you would like.

1.Change the price of berries and other things you can get that depends on the season.  
[BEFORE]
Social skill [1]
Currect price ~3$ per bush. [0.58$] per berry. Any season.

[AFTER]
Social skill [1] 
Price ~0.05$ per bush. [0.01$] per berry.  Summer.   OR completlely priceless.
Price ~2$      per bush.[0.87$] per berry.   Autum, Spring.
Price ~6$      per bush. [1.16$] per berry.  Winter.

### Describe alternatives you have considered.

2.Harverst all plants in field around centre so it will make sence that they gathered AND ate all of it

3.Just nerf (change) the price of berries without implementation of dynamic prices.

4.[Make plants around centre unharvastable since they are property of centre?]

### Additional context

132$ just for 5 minutes of work. Only berries.
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/77558147/9123882b-7d4c-43da-b79e-458b48d027b4)

**Comment by KHeket** [comment]
This prices is good for refuge center, but Rubik and hub should buy them for lower prices. 
Hub have their own greenhouse undergraund, and you can get profit from them by nre records =Rubik dont need food, as I can understand. So he can accept looted items
But for Refuge center it good prices because:
1) They have a lot of people in the center, they need a lot of food. By lore there is also basement under the center with more peoples
2) Gathering food is dangerous because of portals, portal storm, blob lieutenant, mutant plants, animal and insects, zombies and zombified animals. You are only wan super figher with hub armor, cbms and cool mutations, but for a common person its easy to die in this deadly surroundings
3) Even for 132$ you will buy very low amount of items. And you need to gather a lot more to buy enough items
4) Even if you sell so much food, that you can buy all items from trader - this amout of food will be for 40 peoples at surface and for more peoples at besement, so they will eat this amount of food for 2-4 days or less

**Comment by Kywi001** [comment]
Dont forget that, there are ways to get thousands of merch passively with followers and certain NPC camps, so I dont really see issues with this, but yes, I do agree that berries should get their price nerfed given that, if your calculations are correct, MRE being 15$ per sealed package, 3$ per bush sounds way too expensive for some handful of berries and that you can get around 500 berries just auto foraging and auto moving in a forest forba few hours

**Comment by NickEmbased** [comment]
Hi @KHeket. Continuing discussion with your comment i would like to say:

Centre has own fields that is shown on the minimap. Those fields contain hungreds of bushes and tress and protected (not fully) by metal fence. If there will be a zombie or a portal storm they can literally just run in the building within minutes.
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/77558147/84762561-d97c-44e0-8dd9-351e56e6bf9c)

Create new character select "Scared and naked" (Zero starting items) and "Safe place" scenario with centre option (Also select Summer). And from day 1 starting fully naked and without anything you can buy: Glock 21, 16 bullets and a mag, machete and a welder (and still you will have 47$ left) from a 10 minutes work of gathering (infinity) berries. 

And as Kywi said other ways to get tons of money requires some work but this one is available for everyone and you dont have any requirments

**Comment by KHeket** [comment]
> 10 minutes work of gathering (infinity) berries

They are not infinity, you can gather berries once a season at summer. Once a autumn you can gather rose hips, which are much more sparse than summer berries

> 10 minutes work of gathering (infinity) berries.

10 minutes of irl time, but few hours of ingame, because without finding backpack - you will need to make lots of moves. And you can also easily loot this items in cities/speacial structers

This number of bushes is nothing for 40 peoples at the center and lots of people undergraund I think, if you gather all this berreis and sell it too trader - they can live eating it for ~7 days

And as I sad, if you dont look at this situation as a just a game, but as a reality - its quite good precies for food. In every apocalypse-like story food one of the most expensive items.

Dangerous surroundings, portal storms, zombies, zombie animals, mutant etc - food became more expensive

And dont forget, that every day zombies, mutants and all creature became more powerful because of evolution, and fortal storm became more long lasting, so the danger is encreasing every day

And in apocalypse, where almost all the people died - there is lots of free loot, you can even play without buying anithing from reafuge center - price of items lowering

Cataclysm not going in the balance way, its going in realism way

**Comment by NickEmbased** [comment]
@KHeket fair enough, i think we both have solid points. I do agree with some of yours points that make sense, some of mine points were not discussed however. But sure i think there is no more need to discuss, since we heard each other points, so conclussion. And if you are the one who do it and you think that price is fair then you can close this, if not, we can get other people's opinions on this

**Comment by KHeket** [comment]
On the other hand - I cant unerstand, where refuge center get such lot of things weekly
Rubick - have portal techology and access to the other worlds and portal dungeons, may be he can craft cbms by himself, he can also have free workers
Hub 01 - may be they can have nanofabricator techology and they also dont sell tons of items
But refuge center weekly getting lots of insruments and big amout of resorses, 5000-10000-20000+ welding rods summary, such number of rods you will gather from 4-5-10 special locations

Before balancing the prices we need to understand, where do the Smoke get all this items
It their own storage? Not best Idea to trade limited and extremely important resources
Gathering from other locations? As I sad previously - the planet is becoming more dangerous every day, and you will need to make longest trips because of running out of resources in nearby locations. So, each trip is a risk of death. And resourses will be more valuable in that way
Or may be something else? Some kind of interaction with portals? Gifts of God? I dunno

**Comment by ashGlaw** [comment]
Making the plants around the refugee center pre-harvested makes good sense to me. I'm surprised there's no farming going on out there

**Comment by NickEmbased** [comment]
@ashGlaw  makes sence 👍
