### ISSUE TITLE
clay kiln and rock forge makes coal (not charcoal) disappear

### ISSUE THREAD

**Issue by misterprimus** [CleverRaven/Cataclysm-DDA#68371]
### Describe the bug

I was playing a game where I happened to have come across a bunch of coal at a mine and also had charcoal available, all nearby. Reloading the Clay Kiln (constructed object) with Coal just made the coal disappear. Charcoal seems to work correctly, however.

### Attach save file

[Lemay - old-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12745268/Lemay.-.old-trimmed.tar.gz)

### Steps to reproduce

1. Build a Charcoal Forge or Clay Kiln.
2. Have Charcoal and Coal nearby.
3. Try to reload it with the coal.
4. Coal will disappear.

### Expected behavior

Just as with Charcoal, Coal should be loaded into the forge/kiln and tracked in its inventory. It should not just disappear, unless used of course.

### Screenshots

![disappearingcoal](https://github.com/CleverRaven/Cataclysm-DDA/assets/45959491/e1e3f730-3b37-46d0-b565-65847f6bd5c8)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3448 (22H2)
- Game Version: ae14681 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

I suspect this has not been caught yet because Coal is an extremely unlikely fuel to be used for these purposes given that it usually spawns in mines which are medium danger, low reward raiding targets. Furthermore, Charcoal is extremely easy to make to the point where it's often faster to just make it than to transport it back to base.

**Comment by FATM0USE** [comment]
might be related to [#68371  ](https://github.com/CleverRaven/Cataclysm-DDA/issues/68371) where coal was moved to its own ammo type to prevent use in cooking recipes

**Comment by RenechCDDA** [comment]
Yeah looks like this change is due to coal being separated out into its own ammo type in #67621, as FATM0USE was trying to say.

`reload_furniture` takes only a single itype for ammo, by calling furn_t::crafting_ammo_item_type. That function returns the **default** ammo type.

https://github.com/CleverRaven/Cataclysm-DDA/blob/5621850411c36baca2978f8779cf4579723cdfd1/src/iexamine.cpp#L4420

The default ammo type for the charcoal forge is charcoal, **because that is the first ammo type listed** 
https://github.com/CleverRaven/Cataclysm-DDA/blob/5621850411c36baca2978f8779cf4579723cdfd1/data/json/items/tool/metalworking.json#L99

**Comment by ObsessiveArtist** [comment]
Just like to add that rock forges loaded with coal don't count as charcoal forges for the purpose of steel recipies etc when loaded with coal - I'm guessing its related to this issue. Rip easy innawoods start.

**Comment by gearhand** [comment]
Should forge and kiln be allowed to mix charcoal and coal inside, or there must be only one type of fuel at any point in time?

**Comment by nornagon** [comment]
oh dang @katemonster33, jinx i guess
