### ISSUE TITLE
Fermenting vat bug

### ISSUE THREAD

**Issue by adiosmi-go** [CleverRaven/Cataclysm-DDA#68463]
### Describe the bug

Can't put the wort into the keg and need to restart the game to be able to do that, and 7 days later the wort are disappeared

### Attach save file

N/A

### Steps to reproduce

Read description

### Expected behavior

Works properly

### Screenshots

![Screenshot_20231002_180054](https://github.com/CleverRaven/Cataclysm-DDA/assets/119608104/9a12d94b-e3f7-49f1-8ec7-674c132092fa)

### Versions and configuration

Sep 17 2023 experimental android

**Comment by AmarinReyny** [comment]
Question: Was the fermenting vat on the same overmap tile as a faction camp or expansion thereof, or on Z-levels above or below such tiles? I've experienced a variety of bugs seemingly caused by overmap tile changes due to faction camps and expansions, and one of those bugs is that, if I put stuff in a fermenting vat, start the fermentation process, save, exit the game, open it back up, and load the save, upon checking the vat, I'll find that the vat is empty.

**Comment by adiosmi-go** [comment]
The vat is in the sewer level, I usually don't create faction. I also
suspecting that leaving the reality bubble could trigger such bug
