### ISSUE TITLE
The rooves probably should be made bashable

### ISSUE THREAD

**Issue by gettingusedto** [CleverRaven/Cataclysm-DDA#68527]
### Is your feature request related to a problem? Please describe.

I do find it pretty odd that houses' rooves are one of those terrains that got exempted from being bashable. You would think the shingles rooves would be easily bashed with a sledgehammer.

I don't live in america and see how their rooves are made, but i bloody doubt the US houses' rooves would be *that* tough to the point of not being able to be bashed open by a sledgehammer or strong enough bash weapons.

### Solution you would like.

Make the rooves bashable.

### Describe alternatives you have considered.

Not doing so and assume USA solved roofing.

**Comment by PatrikLundell** [comment]
The plural of "roof" is actually "roofs". While "loaf" becomes "loaves", "proof" becomes "proofs". English is a linguistic train wreck with many cases of multiple parallel variations of what should be a single pattern.

As to the actual subject, yes, roofs ought to be bashable.

I suspect this is caused by the weird internal logic that causes ceilings to be part of the floor tile (a result of a 2D origin, I think), so bashing a roof would result in also having to modify the tile below to reflect that the ceiling is now gone or broken.
