### ISSUE TITLE
There's noticeably lack of electric car recharging stations

### ISSUE THREAD

**Issue by gettingusedto** [CleverRaven/Cataclysm-DDA#68611]
### Is your feature request related to a problem? Please describe.

You would think with electric cars being more common these days, there would be places for them to charge the electric cars in the cities and such, but there's no such electric car recharging stations.

### Solution you would like.

(nonfunctional) Electric car recharging stations spawned around the state.

### Describe alternatives you have considered.

Not doing so.

**Comment by oosyrag** [comment]
They're usually found in existing parking lots, so that would be a good place to add them.

**Comment by PatrikLundell** [comment]
While it would be more realistic to have recharging stations in garages and parking lots, they're only cosmetic unless you can take them down and hook them up to your own grid, and they would provide a useful functionality only if they were able to draw from the grid by depleting stored energy and charge the batteries of the vehicle hooked up to it fully (or until the energy supply ran out). I don't know if the CBM charging logic might be useful as a pattern here, but it ought to work in a similar manner.

The current jumper cables allow you to equalize battery charge, so adding another battery to the grid makes it take longer to fully charge.

My work around is to use a large vehicle (luxury RV preferred, if any can be found) as a charging station by fitting it with lots of solar panels (that's why the vehicle should be large) and storage battery cases. I'd then swap out batteries as they get charged and insert depleted ones.

**Comment by kevingranade** [comment]
Stale bot got redirected, cleaning up.
Yes add them, no we don't need issues to track every single hypothetical thing it's feasible to add to the game.
