### ISSUE TITLE
Fabric Cut should be merged back into Cut again.

### ISSUE THREAD

**Issue by McFrugal** [CleverRaven/Cataclysm-DDA#68653]
### Is your feature request related to a problem? Please describe.

There is no reason to require special tools for cutting fabric in this game.  The only reason IRL to require a smooth edge is for precision sewing, so that you waste little material, have a snug fit, and make inner seams that are neat and tidy.  Precision sewing is not needed for any clothing in a survival situation, as you can simply sew farther away from a rough edge and wasting material is generally to be expected anyway.

It's very unrealistic to require scissors to cut fabric.  Tailors frequently do it with their bare hands and teeth!
I know this whole thing started from concerns over being able to cut kevlar with unrefined tools, but simply put kevlar is not that special.  It's not made of steel, it is a strong fabric that is resistant to stretching and thus impacts, it is not resistant to cutting.

### Solution you would like.

All Fabric Cutting tools should simply be Cutting tools, all recipes that require Fabric Cut should require Cut again.

**Comment by oosyrag** [comment]
I don't think this is unreasonable, but I'd be quite interested in seeing a video of a tailor going at it with their teeth.

**Comment by a-chancey** [comment]
hi, I’m the guy who introduced fabric cut. 

Recipes are written - and times are written - as a best case scenario, using appropriate tools. Just as importantly, the weights of the final products are roughly the sum of the weights of the input ingredient, minus any scrap byproducts.

The definition we agreed upon here for fabric_cut is cutting tools that are appropriate for cutting basic fabrics into complex patterned shapes. Scissors and razor sharp blades fit the definition. Knives, which have to be dragged while applying pressure, pull the fabric and and stretch and deform it, impacting your cuts. 

I’ll accept a knife as a substitute on simple crafts using only a knife - but they’ll need a separate recipe and a longer crafting time, and possibly requiring a flat surface. A knife alone is either going to result in a poor fitting product if you trim at the same speed, or it will damage and waste more material while also taking longer to get results equivalent of a pair of scissors. How much longer will a knife take? That’s for someone else to figure out because I’m not fucking doing this again. 

And then there’s Kevlar, because it actually is special. The fabric_cut2  quality is for specialty tools - namely Kevlar shears, because Kevlar and nomex require specialized tools. Using regular scissors with a beveled edge can snag the threads in the weave, disrupting the integrity, vastly reducing the protective capabilities of the fabric. Shears snap the threads and remove this problem. This is ballistic protection we’re talking about - not negligible protection from cotton.  

But to remove fabric cut and revert it to cut? Yeah, no. 

You’re not even going to remotely have a chance of convincing me you are trimming fabric to make gloves using a zweihänder. You’re definitely not using a circular saw, a wood axe, a bread knife, or an electric carver. All of those things have at least Cut_1.

**Comment by McFrugal** [comment]
Funny, you said on reddit to do the exact thing I just did here, as if the OTHER devs get to decide.  Yet here you are, claiming absolute authority on the matter.
Let's put aside your deception and egotism, it's not important.  It has to pass the "realism" test you said.  Well, this implementation doesn't.  If kevlar is the only glaring problem then make its recipe require "kevlar cut".

**Comment by oosyrag** [comment]
In case you're misunderstanding, a-chancey does not have merge permissions, so it would indeed be up to "other devs" (as in anyone who wants to do the work, including you), to make this change, and "other devs" (as in the project maintainers who have merge rights) to accept the PR.

A-chancey is however decidedely the absolute authority on their own PR as far as the reasons for which they introduced the changes goes, which were previously accepted.

**Comment by a-chancey** [comment]
When I said I'll accept, I meant I'll accept the reasoning. As the guy who did the most recent overhaul and audit, lots of folks tend to run PRs by me, since I still happen to be around. I don't have merge permissions, but still have a bit of clout due to the amount of work I spent researching and rebuilding the system. Yeah there's flaws, but many are limitations of the crafting system in general. Saying "just undo your work" isn't constructive criticism, since all it does is revert back to more of the problems the system had before. 

And the comments I made regarding needing its own recipe with a longer time to craft is something that was relayed to me very early in the audit by folks who _do_. 

I'll rephrase what I know I said on Reddit and was told on discord: recipes should be written at their fastest time, using the given set of tools. Improvised tools would be slower and require a second recipe to be written.

Scissors will always be faster and more accurate than a combat knife, trowel or _a piece of metal wreckage_. The recipe should reflect the proper tool for the job. It now does.

If someone else wants to write up simplified recipes for some stuff using specific knives, be my guest, but CUT (includes axes, metal wreckage, and the circular saw) and CUT2 (includes the electric carver) are not appropriate qualities to determine if a tool should be used for tailoring.

**Comment by McFrugal** [comment]
It's being changed to take longer with inappropriate tools, instead of being impossible?  That's fine then.

**Comment by PatrikLundell** [comment]
It is not _being changed_. What @a-chancey said is that if someone (probably you yourself) would put in the work to produce all these alternative recipes it would be reasonable to accept them (under the assumption the recipes were reasonable, of course: a stupid example of an unreasonable recipe would be one that produced the same result in the same time using inferior tools).

**Comment by McFrugal** [comment]
So, tailoring is fundamentally broken because of a bad PR that introduced an unnecessary extra layer of complexity onto all of the recipes to fix a realism problem with a single material, and all the active developers refuse to do anything about it?  Do understand the situation correctly?

**Comment by oosyrag** [comment]
Not exactly. It's not so much refusing to do it as it is a matter of finding someone who's interested enough to do it over the things they themselves want done. You're the person who cares the most at this point, so you're the best bet. If you don't, then the next best thing is waiting until someone else wants to do it.

**Comment by AnotherSeawhite** [comment]
So well... There's a difference between cutting and fabric cutting. The former is when you don't have to cut something with precision for a good result, and the former is when you *have* to be precise, because of size and stuff.

Box cutters, scissors, X-Acto knives, and scalpels have both cutting level of 2 and fabric cutting of 1. Fabric level of 2 is when something stronger is needed to cut specific fabric without making the entire thing to fall apart, kevlar for example. You can't cut kevlar with regular office scissors without ruining the whole thing. Even stab vests use kevlar for protecting the user from getting stabbed.

For example, disassembling a window curtain requires a cutting level of 1, since it's very large and you just have to slice it. However disassembling cotton sheets requires cutting level 2 since you're cutting it into smaller pieces, and cutting it with a large blade would be hard. Patchwork cotton sheets don't require fabric cutting but cutting level of 2 to make. Making gloves requires fabric cutting since you don't want gloves that can't fit your thumb.

It's more of 'appropriate tools required to make this' rather than 'extreme realism because screw you'. Would tailors be able to make a sweatshirt by just tearing the ingredients with their hands?

**Comment by PatrikLundell** [comment]
If you consider the crafting to be _fundamentally broken_ because the crafting system cannot currently handle a single recipe taking different amount of time depending on which tools you use, then yes, it's broken. It's one of many deficiencies (it also cannot make a single recipe have different amount of effort depending on the tools used, so mining with a jackhammer is as strenuous as mining with a pick axe).

This is a community project, so the _active developers_ are the people to decide to contribute things on their own. As @oosyrag mentioned, people work on what they want to work on, so unless you can convince others that your issue with this is also their issues with this you'll likely have to do it yourself.

There is a bounty system where you can offer money for people to implement stuff, but I don't think it really works, as you'd typically have to offer rather large sums for it to be worth it for someone to put in time into implement (and test!) things just for the money.

**Comment by a-chancey** [comment]
I'd also like to state what should be obvious: the game is balanced around default settings, not 0 city size and reduced item spawn, the settings which OP is using but neglected to mention when they complained they can't find a fabric cutting tool.

Their initial proposed solution is "revert the changes and use cut instead of fabric cut", which is oversimplified and wrong. It wasn't even "add fabric_cut to more tools, these should have it", it was "there is no obvious reason why a box-cutter knife has it, but a multitool doesn't" - so here it is: box cutters use replaceable razor blades irl (and should be updated to reflect that in game). Razor blades and craft (xacto) knives share the same bevel angle - and xacto knives are the _most_ appropriate cutting tools for a handful of fabrics. 

Again, not every tool suitable for cutting is suitable for *precise trimming*, and until the crafting system can support either damaging the item, item faults, or increase crafting time properly - and by that last one, I was told this means using inappropriate tools should only impact the portion of time that those tools would be in use. A flat multiplier won't work because you're not cutting fabric the entirety of the time required by the recipe. This is why I wasn't allowed to implement sewing machines with a flat bonus - if I wanted to do that, I need to know how much time is spent stitching, and how much faster it is to stitch by machine, then factor out _each recipe individually_. Same goes for slowing down complex recipes based on *one* inferior tool.

In an ideal world where we've rewritten recipes into routines and updated the crafting system, I'd personally suggest that we rework tool qualities so that negative qualities are valid, but increase the period of time for the steps they're used.

**Comment by McFrugal** [comment]
You're confusing me with the person you spoke to on reddit.  I never posted in that thread, I was an observer that decided to do something about it.  My argument is that requiring fabric_cut for anything other than kevlar is overcomplicated and wrong.

**Comment by Termineitor244** [comment]
> You're confusing me with the person you spoke to on reddit.  I never posted in that thread, I was an observer that decided to do something about it.  My argument is that requiring fabric_cut for anything other than kevlar is overcomplicated and wrong.  You can in fact implement sewing machines, you just have to put in the work.

This is a voluntary project, so you don't get to tell someone that "you just have to put in the work", they have already contributed in a great way to the tailoring crafting, gave reasoning behind their changes and was discussed and approved, they have already put in the work.

The proposal for more easy/rough tailoring crafts for when you only have a knife and need to cover yourself from the cold is workable, and, as long as the crafts are simple and take more time than with proper tools, it would be probable to see them merged.

That said, the way you are behaving in this thread is not going to motivate many people to work on it, since you are attacking a great rework of the tailoring system that has already been merged and is seen as in line with reality and the direction of the game, one that took itself serious and took time, a loot of time, because I remember how much it took for it to be finished and merged, there is already much work behind the current tailoring crafts, more can always be done, of course, but reverting it (wanting to remove the fabric cutting quality, which is central for the reasoning behind the changes that were made to the recipes) I think is a dead end for any argument you want to make.

**Comment by McFrugal** [comment]
I mean, I was told earlier that if I wanted it to be changed I needed to do it myself, so that's basically saying for me to put in the work?  Yeah it's voluntary for them to put in the sewing machine changes, I don't see why that invalidates what I said.  I know I've been a bit hostile but it really does look very stupid to me that you can't use a knife to cut fabric to make clothing.  Calling it great work is... well, that's wrong.  It left a noticeable hole in the crafting system.  I would call that mediocre to good work, and needed to be fixed in a decent time span, not left in its current state for, what, two years according to the reddit thread?

If it rendered tailoring too complicated to change afterwards then that is a good reason to revert the changes on its own.  You need to leave space for future development.

**Comment by a-chancey** [comment]
It’s getting really hard to bite my tongue, but I’d rather not get banned from the repo. The fact is, we have limitations in the crafting system that prevent inappropriate tools from being substituted at a penalty. Even if it could, the game doesn’t know what percentage of a tailoring craft is cutting, so it wouldn’t know how much longer it takes.

I wanted to add sewing machines to make tailoring faster. I was told if I wanted to do that, I needed to figure out what time portion of the recipe is actively sewing, then find out how much faster sewing machines would be, and then factor out only the saved sewing time into a copied recipe from the original. 

If I didn’t want to do that, I could learn C++ so I could completely write a new crafting system to use routine based steps among other things. Then I was told it would be the better use of my time to do that anyways, because I’m already going to have to create new recipes _and_ figure out how long various steps take. Unfortunately, that was out our scope for the audit, and after 3000+ line edits in it, I was pretty burned out. 

But hey, go ahead and make the PR that removes fabric cut. Make sure to include an explanation as to why it’s just as fast to use a pair of scissors to trim fabric for a shirt as it is to use a circular saw. I’d also include an explanation as to why a wood axe or a six foot zweihänder is suitable for crafting gloves - and still just as fast as using scissors. If it’s not, then you’ll need to adjust the recipes accordingly for speed. Also include an explanation as to why you are no more likely to destroy a 6” square patch of nylon with an electric carver than you are with a pair of scissors.

or wait, should electric carvers and swords not have CUT tool quality? Because I’m pretty sure they cut things. 

I certainly left room for growth and refinement, we don’t have drafting and patterning implemented yet, nor do we have fitting with measuring tape. We also don’t have faults or customization, fabric glue, rotary cutters, sewing machines, industrial upholstery, and more. 

what’s being asked is to gut any progress made towards a more realistic tailoring system. Do tailors tear fabric with their hands? Yeah, but they’re not regularly tearing an entire T-shirt’s worth of parts out of a bolt of fabric. 

The way people complaining make it sound, you’d think I added fabric_cut to one tool, didn’t add spawns for it, and then fucked off forever, making tailoring impossible. You’re making this seem like scissors or xacto knives aren’t found in almost every single kitchen in every single city house. If your house somehow doesn’t have one, go next fucking door and you’ll find a pair. Or check some first aid kits in an evac shelters, stores, or a plethora of other places for medical scissors. Hell, go check a mine parking lot for a box cutter knife.

**Comment by Drew4484** [comment]
There's a very good reason we have tool qualities and variable levels per tool. If you want more recipes to be craftable at lower requirements, add more tool options, or a third secret thing, please make a PR with your evidence instead of trying to revert something that was already accepted.
