### ISSUE TITLE
Speaking of Brawling...

### ISSUE THREAD

**Issue by JeveGreen** [CleverRaven/Cataclysm-DDA#68703]
### Is your feature request related to a problem? Please describe.

One move I always find myself frustratingly lacking in Brawling is the ability to shove something. It's the basic move of many wannabe bullies and fighters, just shoving someone back.

### Solution you would like.

I'd imagine this as a technique that is learned at Melee 1, same as when you autolearn Brawling. It would obviously not do much damage, if any at all, but the important part is the shove itself, in that it pushes your opponent back a tile. This could be very useful in a variety of situations, either to push enemies off of ledges, or into traps, or even break out of grabs. Like a budget Brutal Strike that is very situational.

### Describe alternatives you have considered.

Alternatively, it could be learned at Unarmed 1, and be an exclusively unarmed technique, for desperate times. But you can obviously shove someone with a stick just like you can your hands, so I guess it'd have to be a question of game balance.

**Comment by Termineitor244** [comment]
The reason behind why Brawling does not have melee techniques (in contrast with their unarmed techs) is because that's the only way for the techniques from the weapon itself to fire when using the style, and even with unarmed techniques, a tech that pushes your enemy away would be useful... Occasionally, as can be seen with Aikido and other similar styles, if your techniques have a tendency to push your enemy around, that ends up pushing your enemies when you have rather fight them up close, and a technique that makes very little damage and pushes your enemy away from you is not very useful when you want to kill that enemy.

**Comment by JeveGreen** [comment]
> and a technique that makes very little damage and pushes your enemy away from you is not very useful when you want to kill that enemy.

So maybe it should be treated like the Rapid Strike technique: It's quicker than most attacks, allowing you some breathing room, without the damage output of most martial arts. I mean, there are a number of martial arts, including Taekwando and Tai Chi, which allows you to shove your enemies around with significant damage output. Maybe this could be the hidden ace of Brawling?

**Comment by Termineitor244** [comment]
> > and a technique that makes very little damage and pushes your enemy away from you is not very useful when you want to kill that enemy.
> 
> So maybe it should be treated like the Rapid Strike technique: It's quicker than most attacks, allowing you some breathing room, without the damage output of most martial arts. I mean, there are a number of martial arts, including Taekwando and Tai Chi, which allows you to shove your enemies around with significant damage output. Maybe this could be the hidden ace of Brawling?

I don't think brawling needs a hidden ace, since it's supposed to be pretty bare bones in purpose as a self-taught style...

That said, I'm not particularly against the idea of putting a knock back only technique to the style, I have to remind you that the style already has the "Power hit" unarmed tech, which stuns and gives knock back to the enemy, but requires a critical hit, a knock back only tech would probably need to be conditioned, I just added an onpause little buff to the style so you could ask for it as a condition for the new tech to trigger, so the character does not knockback everything that stands in its way.

And remember, brawling should ideally be late in learning things in comparison to the rest of styles, so a technique of this kind should probably be learned with unarmed 3 at minimum, it would be still pretty useful even then.

**Comment by fairyarmadillo** [comment]
This is unneeded, there are already plenty of ways to shove enemies and it's more often annoying than not.
