### ISSUE TITLE
problem with mill, next...

### ISSUE THREAD

**Issue by watcherPlayer** [CleverRaven/Cataclysm-DDA#68701]
### Describe the bug

1. a new problem with the windmill, if you put 65 units of wheat, the output will be 975 flour, this is the calculation according to the description in the wheat itself, but the result is 32175

1. incredibly long unloading from the mill, it took me more than 5 minutes of real time (I'm tired of waiting I closed the game, full time in game ~330000 game seconds ~91 game hour ^^), by the way this applies not only to the mill, it also takes quite a long time to get out of the smoking rack, it seemed faster before

1.  if mill wild rice
```
DEBUG    : calc_rot_while_processing called on non smoking item: dry wild rice (fresh)

FUNCTION : calc_rot_while_processing
FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\item.cpp
LINE     : 7969
VERSION  : 356bfe5

```
4. the problem starts after 4 units

### Attach save file

[Magenta-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12920952/Magenta-trimmed.tar.gz)

### Steps to reproduce

1. put wheat
2. start mill
3. get product

### Expected behavior

None

### Screenshots

![console](https://github.com/CleverRaven/Cataclysm-DDA/assets/145836319/55902f76-160a-407f-95ab-5bb36d869696)

### Versions and configuration

- OS: Windows
    - OS Version: 6.1 7601
- Game Version: 356bfe5 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills]
]

**Comment by PatrikLundell** [comment]
Please don't write bug reports that bunch together a number of different issues, as that makes issues hard to track and bug reports hard to close.
It's reasonable to e.g. report a large number of typos, as that's the same kind of problem, but here you're listing 3 different issues (I don't know what point 4 is meant to describe).

The reason it takes much longer to move large numbers of items now than it did before is that charges were removed, so instead of one item that happens to have a lot of charges, you now have the same number of items that you had charges before. The time it takes to move items mostly depends on the number of items. This is an explanation for why it takes longer, not necessarily an indication that I think that change was a good one.

**Comment by RenechCDDA** [comment]
Right so the problem is that we're calling `get_milled_amount` inside the for loop for the map iterator, and thus we get a *factorial* amount of results. So for 15 wheat we get 1800 flour, because 15 wheat makes 225 flour and it *iterates*, deleting one and going through the loop again, counting results, ends up going 225 + 210 (14 wheat!) + 195 + etc etc etc = 1800.

https://github.com/CleverRaven/Cataclysm-DDA/blob/078a7b43be36c11f2431bf52f5f00d2d41c9a53a/src/iexamine.cpp#L5939-L5944

I actually don't know how to really resolve this cleanly. My suggested approach is probably to iterate through once, get the results and push them back into a vector or map structure (do the math/calculate the resulting products/etc) and *then* iterate through the actual items on the tile, delete them, and *then after both of those* to actually place the resulting items.

**Comment by RenechCDDA** [comment]
I hate everything to do with this, but anyway, here's one potential approach (with big giant disclaimers that it itself has issues) for this problem:

https://github.com/CleverRaven/Cataclysm-DDA/compare/master...RenechCDDA:Cataclysm-DDA:mill_fix_take_2

@ehughsbaird provided various (better than mine) ideas in regards to the map helper function: 
https://discord.com/channels/598523535169945603/598535827169083403/1163841279252250775
```cpp
std::map<itype_id, int> map::item_count_at( const tripoint_bub_ms &pos )
{
    std::map<itype_id, int> ret;
    for( const item &it : i_at( pos ) ) {
        auto ret_iter = ret.emplace( it.typeId(), 0 );
        ret_iter.second->second += it.count();
    }
    return ret;
}
```

...and dealing with the the problem of assigning rot:
https://discord.com/channels/598523535169945603/598535827169083403/1163882271430942780
```cpp
map<id, float[6]> products;
map_stack items = it_at(pt);
// Figure out how many results we should create
for( item &it : items ) {
    auto product = products.emplace( milled product of it, {0,0,0,0,0} );
    product.first->second[rot_bucket_of( it )] += quantity of milled product based on it.count();
}
// Erase all the items on this tile
items.clear();
// Place the results
for( [id, amount] : products ) {
    // Round down amount, then place that many items
    for( int i = 0; i < amount.size(); ++i ) {
        // Create the item we're going to place
        item to_place = item( id );
        // Set it's rot percentage to the appropriate level for the bucket
        to_place.set_rot_pct( rot_pct_from_bucket( i ) );
        // Place the necessary amount of items
        add_item( to_place, floor( amount[i] ) );
    }
}
```
```cpp
// [0, 20) => 0, [20, 40) => 1, [40, 60) => 2, [60, 80) => 3, [80, 100) => 4, [100, inf) => 5
int rot_bucket_of( const item &it ) {
    int rot_pct = rot percentage of item, 0 = totally fresh, 100+ = totally rotten
    return clamp( rot_pct / 20, 0, 5 );
}
// 0 => 10%, 1 => 30%, 2 => 50%, 3 => 70%, 4 => 90%, 5 => 110% 
int rot_pct_from_bucket( int bucket ) {
    return ( bucket * 20 ) + 10;
}
```

Also a general thank you to them for answering various questions that came up.

**Comment by watcherPlayer** [comment]
[PatrikLundell](https://github.com/PatrikLundell) I'm sorry, I'll try to do a better job of sharing notes in the future.

I am grateful to you for explaining the reasons for such a long time to unload containers, I do not consider this a bug, but in this case it is very noticeable, it was probably better for me to use the github 'Github Discussion' mechanism

Regarding point 3, this clearly relates to the problem of mills and can be fixed along with the calculation error, although now, after your comment, I think that it was probably correct to file this as a new bug... well, if necessary, I can redo it as needed. .. redo?

4 point applies to 1

**Comment by PatrikLundell** [comment]
The way I would do it (which isn't guaranteed to be the best one) would be to write a separate report for the wild rice issue and update this report to just cover the incorrect calculation of the results. Someone else may have a different suggestion, though.

**Comment by watcherPlayer** [comment]
ok I'll do that
