### ISSUE TITLE
Clothing Mods

### ISSUE THREAD

**Issue by PGR-14** [CleverRaven/Cataclysm-DDA#68726]
### Is your feature request related to a problem? Please describe.

I think I should be able to add some stuff to clothing, kind of like the MOLLE packs but more substantial, & not just for storage.

### Solution you would like.

Adding some stuff, for instance:

- Custom parts for survivor gear: You choose what's on the gear, I.E. the survivor belt: how many clips, what holsters, tool attachments, etc.
- Patches: Increases Encumbrance, but gives some more protection
- Armor(?) inserts: You should be able to put in custom stuff, like some Kevlar lining on a leather jacket
- Cutting off some stuff: Maybe cutting off the cuffs of a shirt or something? IDK
Just a few ideas, feel free to expand

### Describe alternatives you have considered.

As always, not doing it.

**Comment by GuardianDll** [comment]
it is extremely complicated idea with a lot of edge cases, and the result would be constantly abused (see clothing modification mechanic)

**Comment by Alm999** [comment]
Personally I would like to rip pockets from clothes (possibly to decrease encumbrance, but also to better organize inventory). Obviously, some would be opposed to this, as this move could be seen as an exploit to circumvent the "Hoarder" trait (no pockets -- no problems!), but I don't see it as an issue. Just remember: one can just use armor/clothes that do not have pockets in the first place (e.g. arming pants or aketon), or just fill pockets with lightweight junk, and both moves are allowed.

**Comment by kevingranade** [comment]
This concept has a long history, we had clothing mods like this that you could apply and remove, the problem is that "the same" clothing mod, for example "added insulation" is actually very different based on what kind of item it was added to, and outside of either a set of item-spcific mods, which is more trouble than it's worth, a complex system for procedurally determining the stats of all added mods, which AFAICT is more trouble than it's worth, or some other not-yet-clearly-articulated system, it's not coming back.

Basically, unless you have such a system in mind and can explain how it works and addresses all the issues of clothing mods, which I barely touched on here, don't make an issue about it.
