### ISSUE TITLE
[Mind Over Matter] Ephemeral riftwalker teleporting an NPC also affected player character

### ISSUE THREAD

**Issue by gisaku33** [CleverRaven/Cataclysm-DDA#68733]
### Describe the bug

Ephemeral riftwalker teleported a hostile NPC as I was riding on my bike on the other side of a house, both the NPC and I got warped next to each other.

### Attach save file

[Moroni-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12964907/Moroni-trimmed.tar.gz)

### Steps to reproduce

1. Spawn NPC and ephemeral riftwalker.
2. Have ephemeral riftwalker teleport NPC.

### Expected behavior

Only the character being targeted should be teleported.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/23239811/dbb7230c-ffe0-403f-b774-1ea588cd4951)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/23239811/46cea394-e6e8-46d6-8860-4f570cb4cb44)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3570 (22H2)
- Game Version: cfcc682 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Xedra Evolved [xedra_evolved],
    Mythical Martial Arts [MMA],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Tamable Wildlife [Tamable_Wildlife],
    Mind Over Matter [mindovermatter],
    Bombastic Perks [bombastic_perks],
    Portal Storms Ignore NPCs [personal_portal_storms]
]

**Comment by Standing-Storm** [comment]
The specific thing that causes the teleport is in this damage type EoC:

>  

    "type": "effect_on_condition",
    "id": "EOC_TELEPORTING_DAMAGE_TELEPORT",
    "condition": {
      "and": [
        { "math": [ "_damage_taken", ">", "0" ] },
        { "not": { "npc_has_flag": "TELEPORT_IMMUNE" } },
        { "not": { "npc_has_flag": "DIMENSIONAL_ANCHOR" } },
        { "not": { "npc_has_flag": "TELESTOP" } }
      ]
    },
    "effect": [ { "npc_cast_spell": { "id": "teleport_blink", "min_level": 10 } } ]
  
Where npc here means "[the person who takes the damage](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/JSON_INFO.md?plain=1#L1197)." The damage is delivered through the rifterwalker's special attack, [found here](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/mods/MindOverMatter/monsters/monster_special_attacks.json). 

[I had a problem with this EoC before](https://github.com/CleverRaven/Cataclysm-DDA/issues/67527) but adding the "_damage_taken", ">", "0" solved that. But it sounds like this EoC is getting universalized somehow, since in the previous bug, t was being applied on all hits no matter what kind of damage was done.
