### ISSUE TITLE
Surgery recovery/sorenees

### ISSUE THREAD

**Issue by oosyrag** [CleverRaven/Cataclysm-DDA#68845]
### Is your feature request related to a problem? Please describe.

Thought it was a little silly in my playthrough - hmm I got hurt, might as well spend half a day getting cut open to install a bunch of bionics to force myself to sleep and heal, and come out of it in mint condition.

### Solution you would like.

Have a stacking pain modifier that lasts a day or three per bionic operation. I'm thinking in the range of 5-20 pain per install, possibly scaling with the number of bionic slots the cbm uses. Or it could decay over time depending on severity.

This is very roughly analogous to mutation instability in terms of adding a "soft" cooldown to cbm installation. Although I honestly don't particularly like the instability system, but that's another topic.

**Comment by Maleclypse** [comment]
Possibly something that could be added but likely only after the game play loop has slowed down.

**Comment by KHeket** [comment]
I think, this should be introduced after bulk cbm installing. Its stupid to cut open a patient 10 times to install 10 bionics and, when you can cut open a person one time and install everything in, what will be more time, anesthesia and painless effectively

**Comment by oosyrag** [comment]
I'm not so sure about the benefits of bulk installation (outside of player convenience). Installing a bionic eye and armored leg plating at the same time literally wouldn't result in savings of anything.

Not that I'm against bulk installation for player convenience, but I think the pain penalty (if it were implemented) would still be based on the number/size(/invasiveness) of bionics installed and bulk installations wouldn't make a difference in that regard.

**Comment by KHeket** [comment]
> Installing a bionic eye and armored leg plating at the same time literally wouldn't result in savings of anything.

As example. You need to install 1 eye cbm, 5 torso cbms and 1 leg cbm
Rubic/surgeon/autodoc will spend 1-1,5-2 portions of anesthesia, instead of 7, so it will be less time to make the player to "sleep", yes, Rubick anesthesia is infinity, but I am explaining this thoughts to justify time saving 
And because there is 5 cbms will be implanted in torso - it will will require less time, 1 time period for eye, 1-1,5-2 (because of bulk installing) time periods for torso and 1 time period for legs
And the same for pane, you will have 1 "unit" of pain for eyes, 1-1,5-2 "units" of pain for torso (because there is no need to cut open your torso 5 times) and 1 "unit" of pain for legs
