### ISSUE TITLE
Add washboard alternatives

### ISSUE THREAD

**Issue by oosyrag** [CleverRaven/Cataclysm-DDA#68858]
### Is your feature request related to a problem? Please describe.

I've never seen a washboard in my life, here on the West Coast of the US. Are they still a thing in New England?

I'd like to be able to use a sink or a bathtub to wash clothes instead.

### Solution you would like.

Move the wash item use action from washboard/sponge/washing kit to the sink, bathtub, or washing machine (or possibly any large, open, liquid container) as interactable furniture, with water, soap, and potentially sponge as required tools.

Add soapy water as a soap option for washing.

### Describe alternatives you have considered.

 Alternatively put the use action on soaps, with nearby sink/tub/container, soap, sponge, as tool requirements.

Per discord comment - rather than obsoleting washboards just add the ability for sinks ect to wash things. Makes sense to me!

### Additional context

As a parent, I still do hand wash items often despite the availability of washing machines. Either when something doesn't call for a whole load, or when the item is so soiled I wouldn't want to contaminate the rest of the dirty laundry. No washboard is involved, just a tub or sink, yet I like to consider the washing job decent enough. As long as there is a hard surface to press against and a basin to contain the soapy water, a soft item can be scrubbed against itself effectively. Honestly I think even the just floor would be suitable enough, for the kinds of filth we're talking about in game.

**Comment by Daved27hundred** [comment]
it's a grooved wooden board that you scrub things on. the makeshift one ingame probably looks like this.
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/56202842/804fe9ef-8c19-4175-9551-67d20a5a8c8b)

**Comment by oosyrag** [comment]
I'm aware it is a thing that exists (at least in history). It just seems really unnecessary! Also while it's not hard to make, it just bugs me that I have to make one at all to wash clothes. And it's kinda bulky and doesn't exactly fit in a pocket... just annoying overall.

**Comment by gettingusedto** [comment]
then why not just add more ways to wash clothes and not obsolete the washboard? cuz obsoleting it sounds rather unecessary imo.

**Comment by PatrikLundell** [comment]
People of the past weren't stupid: they used washboards for a reason, namely that they needed something to scrub the clothing against to actually rub away the dirt, rather than just soak items in water, slosh the items around a bit, and call it a day (although that's what top loaded washing machines do...).
If you want another old time washing method you'd bash the clothing with something hard on a hard surface (while wet, of course).

**Comment by toweroglass** [comment]
my brother's wife is from ecuador and she really hates spending money at the laundromat and insists on washing clothes at home. with a washboard.

you could wash items against themselves but it would be super inefficient. which i think is something most CDDA players can appreciate. those minutes add up.

This item is the least of my worries and usually when i've got the basics down and can take a deep breath it's one of the first things i make, but i've often thought it should be possible to quickly carve up a cutting board instead of bashing stuff for a plank. it seems like a decent analog.
