### ISSUE TITLE
Ferals should always drop the weapon they fought you with

### ISSUE THREAD

**Issue by morethananotion** [CleverRaven/Cataclysm-DDA#68882]
### Describe the bug

Whether or not ferals drop the weapon they wielded seems to be determined by item spawn scaling setting. With 1.00 they will always drop it, but when playing with lower values, such as 0.25 (the world from the screenshots uses this value) it's pretty much not gonna happen.
I'm not a dev, but from a quick glance it might be connected to this issue [68775](https://github.com/CleverRaven/Cataclysm-DDA/issues/68775).

### Attach save file

[Knight-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13126681/Knight-trimmed.tar.gz)

### Steps to reproduce

1.1 Spawn in a world with default item spawn scaling value
1.2 Spawn a gun
1.3 Spawn a feral variant
1.4 Pop the feral
1.5 Guaranteed weapon drop. - **Working as intended!**

2.1 Spawn in a world with lowered item spawn scaling value
2.2 Spawn a gun
2.3 Spawn a feral variant
2.4 Pop the feral
2.5 No guaranteed loot. - **NOT Working as intented!**

### Expected behavior

It would make sense (to me) that if they have a weapon to attack you with, they should drop it when killed, regardless of the loot scaling settings. 

### Screenshots

![test1](https://github.com/CleverRaven/Cataclysm-DDA/assets/20268959/72b0a8d8-0521-481a-8804-d8d0b6b4e1fb)
![test2](https://github.com/CleverRaven/Cataclysm-DDA/assets/20268959/5ec8483f-f34d-4188-9b1b-b520dea1c37d)
![test3](https://github.com/CleverRaven/Cataclysm-DDA/assets/20268959/ea906b59-e1f6-4adb-95e5-9c122354499a)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2965 (22H2)
- Game Version: b6ae18b [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by GuardianDll** [comment]
it is not possible to make some items ignore the spawn scaling

**Comment by Termineitor244** [comment]
We currently lack a way to guarantee an item spawning/dropping with different spawn scaling values, your request, more than a bug, would be better accommodated as a feature request, requesting for flags/mechanism for either guarantying a drop/spawn no matter what (To ignore the spawn scaling values), or, more difficult, for a system of (really) wielded items for monsters, which would allow other things such as disarming them with martial arts.

Either way, this is not really a bug I think.

**Comment by morethananotion** [comment]
Your answer seems pretty conclusive, but I'd still argue it should be treated as a bug, especially as the game becomes more and more realistic. Although I don't really care as long as someone tries to fix it some time later. Should I close this issue?

**Comment by Termineitor244** [comment]
Well, the reason I'm not sure if it would be taken as a bug is because I remember that the game is supposed to be balanced around standard spawns settings (monsters/items/etc.) so monsters not always dropping their items with lower settings could be seen as "Working as intended".

You can leave the issue open if you want, but if its closed by one of the main devs for the aforementioned reasons then I would suggest to open a feature request asking for what would be necessary for this to not happen, i.e. a flag for spawns/drops or the mentioned monster wielding mechanic, the flag should be easier so opt for that.

**Comment by morethananotion** [comment]
Yeah I get your point. Whatever is "working as intended" in the context of a game engine logic is probably not the same "working as intended" in the context of gameplay expectations. I'll leave it open, see where it goes

**Comment by toweroglass** [comment]
eh, if i'm playing on lower loot spawn i don't really want guaranteed anything. if something like this were implemented it would just change the game balance as we know it.

**Comment by kholat** [comment]
I personally way prefer the way it works now. The point lowering loot setting is... to lower the amount of loot, who would've thought. If you make more and more guaranteed drops then the loot scarcity setting loses its value.

**Comment by morethananotion** [comment]
I get that this will simplify finding a weapon a lot, but it's just not consistent now. If you kill a bandit wielding a machete, he's gonna drop it regardless of your loot settings. And from gameplay point of view ferals are psycho, zombified bandits. But sure, arguement could be made that bandits have self-preservation instincts and ferals don't.
Here are some ways I think it could be balanced (might add more points if I think of something else):
1. This one's simple - make the weapons they drop have shitty durability conditions. It is already somewhat like that in the base game, but it we could tune it down even more. 
2. A bit more insane - maybe rework the lore about ferals so that they have their weapons fused with their body by the blob. That way you're gonna need to butcher them in order to get a hold on their weapon. But again it should still have shitty durability regardless.

**Comment by G0BL1N** [comment]
I think you're viewing this from a wrong point of view - the behavior you're describing doesn't only apply to ferals, it applies to every single monster in a game, not even just ones with high-probability loot. For example, Z-9's have 40% drop rate of kevlar dog harness. From a realistic point of view, you could say that in 60% Z-9's armor gets destroyed in combat or something like that, but you still should expect to get kevlar armor from a kevlar-armored dog fairly often. Otherwise, what makes them Z-9, if not their armor? Same applies to zombie soldier which drop combat knife with 80% chance. Because they're not zombie soldiers if they don't have combat knives fairly often. Heck, even default zombies are almost guaranteed to drop clothes, which is what we would expect from a clothed zombified human. And all this goes to hell if you fiddle with drop rates.
The only difference with feral zombies is that they are using their weapons, and that's why they have 100% drop rate of those in the game by default. If you're lowering drop rates - you gotta expect to get less loot, even if it actually doesn't make a lot of sense.
Bandits and other humans are not nearly as common as ferals, so it's fine for humans to be coded differently to other enemies, and it's fine for them to be inconsistent like that, I think. Humans are inconsistent to other creatures in cdda in _a lot_ of ways. It's not just a "better feral", even from a gameplay perspective.
I don't think making humans consistent with other monster's drop rates is something this games needs, but it seems to me like it would be a lot easier to just apply drop rate multiplier to human drop, to make it more consistent. It would be the literal opposite to what you're asking, but it would remove inconsistency.

> This one's simple - make the weapons they drop have shitty durability conditions

This is not something that would solve the problem - it would need to be solved first, and then this would a be a patch for people with low drop rates to calm them down. Don't think it'll help, though, even almost completely destroyed items could still be repaired. If someone wants to see less loot, they usually want to see less loot, not loot with low durability. Besides, it would make other people unhappy, because now their pipes come broken because of some weirdos with 0.25 drop rate.

> A bit more insane - maybe rework the lore about ferals

Makes no sense from a lore point of view and is not something anyone would want, IMO.

> Probably not gonna happen - make it an option you could toggle upon world gen

This is actually the most reasonable one - a toggle to make 100% drop rate loot guaranteed regardless of drop rate settings. Still, someone has to put their time into doing it and supporting it moving onward, and this doesn't seems like something people really want.

**Comment by morethananotion** [comment]
> Otherwise, what makes them Z-9, if not their armor?
I always imagined it was the specific breed the police use in their line work. Like german shepherds or whatever. Maybe they still have their badge, so that's how you know they are ex-police dogs. But I don't really know if it explicitly says in the monster description that they have armor. Still, it could be explained that their armor was damaged in combat, like you said, or even in combat that happened before you encountered them. 
> zombie soldiers have no knives on lower item scaling settings
This is the type of inconsistency I'm okay with, since they are not actually using them in combat. Some of it could probably be justified by how good combat knives are in the event of cataclysm, so some survivors/bandits might have stolen them. You know, one lures the zombie, the other snatches the knife from behind. Doesn't make much sense in military bases, highly populated areas and etc. yet I'm not bothered by it precisely because z-soldiers don't use it to kill you.  
> This is not something that would solve the problem - it would need to be solved first, and then this would a be a patch for people with low drop rates to calm them down. Don't think it'll help, though, even almost completely destroyed items could still be repaired. If someone wants to see less loot, they usually want to see less loot, not loot with low durability. Besides, it would make other people unhappy, because now their pipes come broken because of some weirdos with 0.25 drop rate.
Fair point. What do you think about making lowered item spawn scaling affect durability of the weapons you get (from ferals only, obviously)? Yes, you could still repair them, but the materials used for the repairs would also be much sparser. And rarely (depending on the actual item spawn scaling value) you would get the same durability you would get normally. So basically, with 0.25 scaling, 3 out of 4 times you would get very shitty ones, but with 1 out of 4 times you would get the same durability as if you played with 1.00 scaling.
> it seems to me like it would be a lot easier to just apply drop rate multiplier to human drop, to make it more consistent. It would be the literal opposite to what you're asking, but it would remove inconsistency.
I don't think it would, you simply can inspect what armor humans are wearing and what weapons they are holding. Not getting it would kind of ruin the point of fighting them.
> Makes no sense from a lore point of view and is not something anyone would want, IMO.
Yeah, it probably doesn't. I'm not all that familliar with the lore. Actually while we are on topic, do you know whether ferals crafted/got their weapons before or after they got infected with blob? If first, could it not be hypothetically suggested that the blob would somehow physically force them to use such weapons, either by fusing them with their hands or by making them hold it so tight that you would have to cut the actual arm for them to release it?
> Still, someone has to put their time into doing it and supporting it moving onward, and this doesn't seems like something people really want.
Yeah, that's why I think it's unlikely we'll see this one.
