### ISSUE TITLE
Resource not properly consumed in faction camp upgrades

### ISSUE THREAD

**Issue by chsh-8912** [CleverRaven/Cataclysm-DDA#68919]
### Describe the bug

When starting an upgrade of a faction camp, some resources listed in the requirement are not removed from the storage.

For example, when upgrading camp's canteen expansion with some planters, only planks are consumed. OTOH, the amount of soil, nail, and pebbles in the storage areas remain untouched.

So a working hypothesis is that components with charges are not handled correctly.

### Attach save file

[Wabasha-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13173173/Wabasha-trimmed.tar.gz)

### Steps to reproduce

1. Load the attached save file.
2. Examine the basecamp bulletin board adjacent to the player character. 
3. Navigate to <NW> expansion tab. The "build some planters" upgrade description should display the required v.s. available resources as components.
4. Activate the "build some planters" upgrade with any NPC.
5. Inspect the resources left. An easy way might be to wait until upgrade completion and check description of the next "build some planters" upgrade.

### Expected behavior

All resources listed as the requirement of the upgrade should be removed from the storage.

### Screenshots

Before upgrade:
![Screenshot 2023-10-25 222122](https://github.com/CleverRaven/Cataclysm-DDA/assets/149038457/523188b4-3348-4744-ac5c-ced59ce6331c)

Next upgrade (after the aforementioned upgrade completes):
![Screenshot 2023-10-25 222323](https://github.com/CleverRaven/Cataclysm-DDA/assets/149038457/8aa469ee-f353-4025-86a8-14049e53224e)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.2428 (22H2)
- Game Version: d6ec466 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by PatrikLundell** [comment]
I suspect it's the same of the long standing issue of base camp companion crafting sometimes not consuming resources.

Crafting and construction uses a weird logic whereby the task first checks for resources, then then allocate resources to the companion, and then does another pass where it again checks for resources and removes ones corresponding to the ones allocated. For some reason the second search pass doesn't always match up with the first one.

There is a newer item handling type that contains references to the specific items, but the logic used for base camps uses the older type that just has a copy of the objects, which is why there's a need for a second search.
