### ISSUE TITLE
Invisible vehicle parts, illegally split vehicles, "Tried to access invalid map position" spam, "No display part at mount (0, 0)" loop when standing in certain spots

### ISSUE THREAD

**Issue by AkdoolTheSlimy** [CleverRaven/Cataclysm-DDA#69132]
### Describe the bug

So, I made my entourage of followers deconstruct some vehicles in our new garage, and I think they accidentally broke something. After they were done, the vehicles were split, in that parts weren't connected physically but on the vehicle examination page, they existed on the grid. I noticed, while trying to bash them out of existence, that I could "examine" some invisible spaces next to the vehicles, and it would bring up the page as though they were invisible vehicle parts. On the examine page, that same space was defined as empty. At the time, I didn't think much of it. I bashed and broke the remaining frames, then dragged the invisible spaces away. Closed the game. Reloaded. 

Later I received an error message telling me to write a bug report due to an excessive number of error messages. Now, normally I ignore error messages by reflex, but in this case, when I exited and reloaded, opting NOT to ignore them, I realized that every single time I moved or a turn passed, I got the "Tried to access invalid map position" error. Further, I tried to find the "invisible vehicles," and while I failed to do so, I found that if I walked into the right space (somewhere near the northern area of the military base's garage), I'd get slammed by the "No display part at mount (0, 0) error. No matter how many times I press space to continue, THAT one never goes away until I press i to ignore.

Overall, I suspect that it's a bug caused by followers dismantling vehicles, made worse when I tried to "clean" the mess up.

### Attach save file

[Save Part 2.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/13261138/Save.Part.2.zip)
[Save Part 3.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/13261139/Save.Part.3.zip)
[Save Part 1.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/13261140/Save.Part.1.zip)

### Steps to reproduce

To see the error messages on my game, just walk anywhere and you'll see the first one. The second error triggers when you walk on certain spaces in the northern part of the military base, presumably where I left the "invisible vehicles." I saved on a spot where I got the looping error.

To recreate the bug in a new game, I'm not sure how, but I'd try recruiting a large number of followers and telling them to deconstruct vehicles in a zone flagged by the zone manager until glitches happen.

### Expected behavior

I expect that the game wouldn't spam errors, or tell me itself that it's broken. Nor do I expect invisible vehicle parts or accidentally splitting vehicles in half.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3570 (22H2)
- Game Version: 089f33e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Bionic Professions [package_bionic_professions]
]

### Additional context

It is worth noting that the newest game update broke my game completely, so the version of the game that I'm playing is a few hours behind it. It's still recent enough that I suspect this issue still applies, though. It's a difference of a day at maximum.

Also, due to the size of my save file, I've had to split it into pieces. The upload limit here is 25 mb, and my save is 55 mb total. If you extract the three zips and merge the "Save" folder, though, it should work fine. The directories should line up properly. Apologies for the inconvenience! Let me know if there are issues or if there's a better way you'd prefer me to upload them.

**Comment by Vaskritaya** [comment]
You can generate a minimized save archive using the debug tools at the bottom of the pause menu. The full save is typically not necessary

**Comment by AkdoolTheSlimy** [comment]
[Desperado-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13263302/Desperado-trimmed.tar.gz)

**Comment by AkdoolTheSlimy** [comment]
There we go! Hopefully that does the trick. Should be the save archive above.

**Comment by PatrikLundell** [comment]
There is a long standing bug with vehicle dismantling using multiple companions. The bug is caused by the usage of array indices into the vehicle array to refer to the part under dismantling, but other parties dismantling parts can modify the array before the companion is done, causing the index to now refer to a different part.

This used to result in rare crashes when a companion was trying to remove its part when another companion had already removed the last part and the vehicle was removed completely. However, the same faulty logic should also result in frames being removed more frequently, and that, in turn, probably results in the parts sitting on that no longer existing frame not being displayed. It certainly did result in the splitting of vehicles in the past.

I tried to fix it at the time but failed due to my inability to trace how a weird vector of numbers into which dismantling info was placed was unpacked again. One of the core developers tried to fix the problem but gave up due to lack of time after running into problems which he realized were probably due to issues with testing rather than the modification.

The work around for the problem is to never have more than one character dismantling a single vehicle, and since you can't control what vehicle companions will try to dismantle it means never set more than one companion on vehicle dismantling (in the same reality bubble: it should be safe to have companions dismantling vehicles sufficiently far apart to ensure that they will work on different vehicles as no two dismantling zones would be accessible from any location).

**Comment by AkdoolTheSlimy** [comment]
At least it's a known issue! Thank you for the reply and for suggesting a workaround,

**Comment by CoroNaut** [comment]
I've experienced all these error numerous times. It should probably not be a stale issue. At the very least, handling the error before it pops up the debug error screen would be a much better solution than just making another issue on it and waiting for another month.
