### ISSUE TITLE
Vehicle beds should be capable of holding a human corpse

### ISSUE THREAD

**Issue by Golfavel** [CleverRaven/Cataclysm-DDA#69159]
### Describe the bug

Human corpses take 62.5L, vehicle beds can hold a maximum of 50L

### Attach save file

N/A

### Steps to reproduce

1. Acquire a vehicle that has a bed
2. Attempt to place a corpse into the bed
3. Wonder how people normally sleep

### Expected behavior

You can fit a human into a bed, dead or not

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.6 LTS; Release: 20.04; Codename: focal; 
- Game Version: e497f5a [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Slots [cbm_slots],
    Tamable Wildlife [Tamable_Wildlife],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Disable NPC Needs [no_npc_food],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

This is mainly due to the ambulance; shoving a friendly's corpse into the boxes next to the bed is not the most considerate method of transporting a human.

**Comment by NetSysFire** [comment]
There is a technical problem here: Imagine you lie down in a vehicle bed irl. You'd occupy more than two spaces of our vehicle beds due to the sheer size (and length) of a human body and there are no mechanics for single large objects to spill over into an adjacent space. A vehicle beds volume of 50l seems somewhat realistic, without doing research, but if you find evidence they are larger, I encourage you to patch this and PR your changes.

**Comment by PatrikLundell** [comment]
It can also be noted that "containers" intended to host (living) humans don't have any mechanism to exclude human usage while being used as a storage space. With the logic above, you'd need to introduce that, so you can either store stuff on your vehicle seat/bed/..., or use it to actually host a living creature (and then presumably also exclude ones too large to fit).

**Comment by fairyarmadillo** [comment]
> There is a technical problem here: Imagine you lie down in a vehicle bed irl. You'd occupy more than two spaces of our vehicle beds due to the sheer size (and length) of a human body and there are no mechanics for single large objects to spill over into an adjacent space. A vehicle beds volume of 50l seems somewhat realistic, without doing research, but if you find evidence they are larger, I encourage you to patch this and PR your changes.

I don't agree with this. A human sleeping only takes one tile (a seat works, for instance!), so a corpse should be about the same.

Bodies should also fit in trunks.

**Comment by NetSysFire** [comment]
As I said, if you have good data on the size of vehicle beds and trunks, keep in mind that we work with tiles, which can be quite tricky when it comes to measurements with real world data like in this case, you may want to PR them or at least present them here so someone else can work with that.

If vehicle beds and trunks still turn out too small, as I said, again, there may need to be a spillover mechanic and in that case I would propose renaming this issue to a feature request of said mechanic.

**Comment by fairyarmadillo** [comment]
> As I said, if you have good data on the size of vehicle beds and trunks, keep in mind that we work with tiles, which can be quite tricky when it comes to measurements with real world data like in this case, you may want to PR them or at least present them here so someone else can work with that.
> 
> If vehicle beds and trunks still turn out too small, as I said, again, there may need to be a spillover mechanic and in that case I would propose renaming this issue to a feature request of said mechanic.

https://www.autonationdrive.com/research/articles/trunk-space-battles-of-midsize-sedans.htm

This link says that most sedan trunks are about 16 cubic feet, which is ~450 liters. We represent a car trunk as two tiles, so each should hold 225 liters.

For trucks, we can use the Ford F-150, which is one of the most popular trucks on the road and comes in a variety of sizes.

https://www.boballenford.com/research/ford-f-150-cab-bed.htm

Bob Allen Ford says that the shortest F-150 bed, the 5.5 footer, gives 52.8 cubic feet of storage, or roughly 1495 liters. We represent small trucks as having 4 bed tiles, so each should have about 373 liters, rounding down. I suspect that's a conservative measurement, as the top of a truck bed is open and you could theoretically stack stuff higher than the rim, but that's a discussion for another time.

So the problem is that trunks and beds in the game ought to hold more stuff. They have been around for a very long time and I am guessing their current storage values were simply arbitrarily chosen and could do with an audit.

This passes the smell test, too. I could easily fit a living or dead person and a bunch of groceries in a sedan trunk, and you could heap many bodies in the back of a pickup IRL.

**Comment by pwalsh0** [comment]
This is similar to "cannot put armchair in van". Literally unplayable. /s
