### ISSUE TITLE
Gun drops have generic names despite "Show gun brand names" set to "true", doesn't change back

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#69211]
### Describe the bug

I get "M4 carbine" and "7-round hunting shotgun" despite having the setting toggled to show brand names, and they don't change when I flip the setting on and off.

This only appears to affect new drops; my MDRX changes names when I toggle the setting, but the M4A1 I found is stuck as an "M4 carbine"

### Attach save file

[Mindssachusetts-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13310962/Mindssachusetts-trimmed.tar.gz)

### Steps to reproduce

Set show brandn maes to true and teleport to a gun store, I guess.

### Expected behavior

Gun names respect your settings.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/5107449/0ab1e824-6911-4ab7-843f-4f8199400ea8)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/5107449/2cf90a8c-9d73-4f16-9de7-2a8c6b02368f)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3570 (22H2)
- Game Version: b399fbb [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mind Over Matter [mindovermatter],
    Bionic Slots [cbm_slots],
    Stats Through Kills [stats_through_kills],
    Massachusetts [MA]
]

### Additional context

I did update this on a running save, but that probably shouldn't matter because why would this happen in the first place?

**Comment by GuardianDll** [comment]
/confirmed
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/67688115/4dee7f89-3afe-479e-9f76-93b1d5ff526f)
------
Oddly enough, reloading the save fix it
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/67688115/ce30119c-6fe6-402b-b6ae-531089b53a73)

but then issue returns back
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/67688115/030e57fc-b277-48f5-bd1c-24aa44ea7b6c)

**Comment by RenechCDDA** [comment]
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/84619419/02e148ba-feea-467e-b2a7-103836f31ce9)

It looks like the type is being constructed with variant weights defaulting to 0 elsewhere.

**Comment by RenechCDDA** [comment]
Oh it's almost certainly the item factory.

https://github.com/CleverRaven/Cataclysm-DDA/blob/1e95dbc190b9bdb0bcf004d6fe4a044720c7f7e3/src/item_factory.cpp#L2708

```diff --git a/src/item_factory.cpp b/src/item_factory.cpp
index e75dcf8fd7..6044748d4a 100644
--- a/src/item_factory.cpp
+++ b/src/item_factory.cpp
@@ -2705,7 +2705,7 @@ void itype_variant_data::load( const JsonObject &jo )
         alt_color = color_from_string( jo.get_string( "color" ) );
     }
     optional( jo, false, "ascii_picture", art );
-    optional( jo, false, "weight", weight );
+    assign( jo, "weight", weight, false );
     optional( jo, false, "append", append );
     optional( jo, false, "expand_snippets", expand_snippets );
 }
```

This patch appears to work, but should be reviewed by someone more experienced with the factory/template magics.

**Comment by RenechCDDA** [comment]
That makes two of us.

**Comment by ehughsbaird** [comment]
For arithmetic types:
They `support_relative` https://github.com/CleverRaven/Cataclysm-DDA/blob/1e95dbc190b9bdb0bcf004d6fe4a044720c7f7e3/src/generic_factory.h#L671 and `support_proportional` https://github.com/CleverRaven/Cataclysm-DDA/blob/1e95dbc190b9bdb0bcf004d6fe4a044720c7f7e3/src/generic_factory.h#L678

When handling proportional, it will read a floating-point type https://github.com/CleverRaven/Cataclysm-DDA/blob/1e95dbc190b9bdb0bcf004d6fe4a044720c7f7e3/src/generic_factory.h#L753
and debugmsg if the scalar is `<= 0` or `== 1`, otherwise it will multiply the previous value by the scalar.

When handling relative, it will read the same arithmetic type https://github.com/CleverRaven/Cataclysm-DDA/blob/1e95dbc190b9bdb0bcf004d6fe4a044720c7f7e3/src/generic_factory.h#L803
and add that value to the previous value.

If it's not doing relative/proportional, it just does a straight read.
https://github.com/CleverRaven/Cataclysm-DDA/blob/1e95dbc190b9bdb0bcf004d6fe4a044720c7f7e3/src/generic_factory.h#L828
https://github.com/CleverRaven/Cataclysm-DDA/blob/1e95dbc190b9bdb0bcf004d6fe4a044720c7f7e3/src/generic_factory.h#L850

This is the same as assign, but assign:
1. Returns false when it fails to read (which is used in... 3 places?)
https://github.com/CleverRaven/Cataclysm-DDA/blob/1e95dbc190b9bdb0bcf004d6fe4a044720c7f7e3/src/assign.h#L69
2. Can check if the value is in a certain range
https://github.com/CleverRaven/Cataclysm-DDA/blob/1e95dbc190b9bdb0bcf004d6fe4a044720c7f7e3/src/assign.h#L72
3. Will complain if you read a value that's the same as the previous value
https://github.com/CleverRaven/Cataclysm-DDA/blob/1e95dbc190b9bdb0bcf004d6fe4a044720c7f7e3/src/assign.h#L76

I think 3 is a little misguided (what if I want to explicitly protect a value from changing?), but it looks like assign just does what optional does, but adds some extra checks. For the sake of readability, I think it should just forward to optional.
