### ISSUE TITLE
when using a gun with a bayonet attached, and using krav maga, when meleeing an enemy, it doesnt cause them to bleed and other stuff

### ISSUE THREAD

**Issue by tw1st31337** [CleverRaven/Cataclysm-DDA#69334]
### Describe the bug

when using a gun with a bayonet attached, and using krav maga, when meleeing an enemy, it doesnt cause them to bleed and other stuff (like staggered and such)

### Attach save file

N/A

### Steps to reproduce

1. teach a man krav maga
2. give a man a gun with a bayonet
3. make sure the "firing mode" is set to the bayonet
4. attack a creature 
5. see its not bleeding :(

### Expected behavior

i expected it to start a bleed

### Versions and configuration

OS: windows 11
game version: 2a70d7f
graphics: tiles
language: english
mods: dda, no_fungal_growth, personal_portal_storms, classic_zombies (with bleeding turned on), speedydex, stats_through_kills, StatsThroughSkills, Tamable_wildlife

**Comment by Terrorforge** [comment]
Can't confirm. With a properly modified DDoD I can Down zombies and make them bleed just fine:
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/5107449/d16db04a-40b2-4a5a-a64b-2087eab79f75)

I think there are a couple of things happening here. Firstly the stunning technique, Cheap Shot, doesn't work on zombies. Your character simply won't use it.

Secondly, the downing technique, Takedown, is throw that doesn't use your weapon. This means you deal much less damage, and you don't inflict bleeding because you're not dealing pierce damage. This is what's happening when you see "You force the zombie to the ground for [less than 10] damage", which in my experience is all the time. I think Krav Maga is pretty disappointing these days for this reason; you end up just tossing enemies around doing chip damage instead of just stabbing them to death, which is super dangerous when fighting groups.

Thirdly, even though you're not using the weapon, you're still bound by its attack speed. Rifle melee attacks are very slow (200+ moves) and it seems that as a result, when you down a zombie while wielding a rifle it usually has time to get back up before your next attack. If you look Sometimes it lines up just right, though:
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/5107449/05260d2d-cedd-4d9a-8657-191fd56bf746)

(P.S. you don't need to set the firing mode to "bayonet" to attack with the bayonet. That mode is for aiming the reach attack - which bayonets no longer have, which means it's entirely useless. I'm gonna submit a bug report to have it removed.)

**Comment by tw1st31337** [comment]
> Can't confirm. With a properly modified DDoD I can Down zombies and make them bleed just fine: ![image](https://user-images.githubusercontent.com/5107449/282484085-d16db04a-40b2-4a5a-a64b-2087eab79f75.png)
> 
> I think there are a couple of things happening here. Firstly the stunning technique, Cheap Shot, doesn't work on zombies. Your character simply won't use it.
> 
> Secondly, the downing technique, Takedown, is throw that doesn't use your weapon. This means you deal much less damage, and you don't inflict bleeding because you're not dealing pierce damage. This is what's happening when you see "You force the zombie to the ground for [less than 10] damage", which in my experience is all the time. I think Krav Maga is pretty disappointing these days for this reason; you end up just tossing enemies around doing chip damage instead of just stabbing them to death, which is super dangerous when fighting groups.
> 
> Thirdly, even though you're not using the weapon, you're still bound by its attack speed. Rifle melee attacks are very slow (200+ moves) and it seems that as a result, when you down a zombie while wielding a rifle it usually has time to get back up before your next attack. If you look Sometimes it lines up just right, though: ![image](https://user-images.githubusercontent.com/5107449/282489136-05260d2d-cedd-4d9a-8657-191fd56bf746.png)
> 
> (P.S. you don't need to set the firing mode to "bayonet" to attack with the bayonet. That mode is for aiming the reach attack - which bayonets no longer have, which means it's entirely useless. I'm gonna submit a bug report to have it removed.)

alr, thanks for explaining
