### ISSUE TITLE
[MoM] Show when Drain is less than 15 but more than 0

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#69416]
### Is your feature request related to a problem? Please describe.

Drain only becomes visible to the player once they accumulate 15 of the vitamin and the first level of debuff is applied.

If the player isn't familiar with how Drain works, this gives the false impression that the player has no drain whatsoever once the effect disappears. If the player _is_ familiar with the mechanics of drain, it's still unclear when you're done waiting and/or using Centering Meditation, which is annoying.

### Solution you would like.

Add another level of the "Drained" vitamin overdose, active between the values of 1 and 14, that has (virtually) no other effect than to alert the player that their Drain level is greater than 0.

### Describe alternatives you have considered.

Just leave it and allow it to be mysterious, but I don't really see the point of that. Not knowing whether or not you're completely free of Drain doesn't really add anything to the gameplay or atmosphere, it's just a niggling annoyance. Nor is it consistent with the game's design in general; Spent Phenotype fills basically the same function as my proposed solution, alerting the player that while they're not in danger of negative mutations, their Instability has not entirely dissipated.

**Comment by MrHrulgin** [comment]
This would be really valuable to me, as I had no idea what Drain actually was or did. I never saw any result (probably due to mostly dying before Drain had a visible effect) and so had discounted it as a specific mechanic, assuming it was adding exhaustion or something. Having a visible effect visible earlier would have helped me know that it was something that might be a concern one day.
