### ISSUE TITLE
STILL possible to mutate out of prerequisite mutations without losing the mutation they're prerequisites for

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#69417]
### Describe the bug

I decided to follow up a course of Plant mutagen with a course of Chimera, and my new Jaundice replaced my Phelloderm without getting rid of Protective Bark.

### Attach save file

[Mindssachusetts-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13367579/Mindssachusetts-trimmed.tar.gz)

### Steps to reproduce

1. Give self Protective Bark (and thus by necessity Phelloderm)
2. Mutate Jaundice

### Expected behavior

If you lose a prerequisite for a mutation, you should lose that mutation as well.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3570 (22H2)
- Game Version: 1e95dbc [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mind Over Matter [mindovermatter],
    Bionic Slots [cbm_slots],
    Stats Through Kills [stats_through_kills],
    Massachusetts [MA]
]

### Additional context

I know this has been reported in various ways in the past, but I can't find those reports so I figured I'd make a new one in case those were considered closed.

**Comment by fairyarmadillo** [comment]
Just for context, jaundice is a step below phelloderm, not part of chimera. You were mutating backwards toward a base skin mutation so that you could then swap over to rashy skin and begin the chimera line.

I'm looking at the mutation types of all the involved mutations and I don't see any issues, so I think we genuinely do just need a line or two in the mutation code to check for lost prerequisites whenever a character gains or loses a mutation.
