### ISSUE TITLE
Are recipe times in the crafting menu supposed to be unreliable and inconsistent? 

### ISSUE THREAD

**Issue by Montimorency** [CleverRaven/Cataclysm-DDA#69637]
### Is your feature request related to a problem? Please describe.

Actual cafting times even for simple items have an unclear and irregular relationship to what is listed in the crafting menu. 

Game Version: 0.G Gaiman stable [64-bit]

If this report prefigures bug fixes or features added in 0.G experimentals, please disregard.

### Solution you would like.

I would expect printed crafting times to be more precise and consistent. The examples included below demonstrate that changes in skill, proficiency, morale, hunger, or other variables over the course of crafting cannot meaningfully be implicated in these disparities, which are inexplicable and mislead the player. Whereas if crafting times are designed to be totally unreliable as point estimates, or perhaps are randomized, this should be communicated to the player. 

### Describe alternatives you have considered.

1. Eliminate precise estimates of duration in crafting and disassembly and give ballpark numbers or qualitative descriptors that will minimally differentiate between ten minute and ten hour projects. 
2. Reduce variability with skill/proficiency.
3. Reduce variability with iterations over the same recipe. 
4. Report a time range at the confirmation prompt that falls within a 95% confidence interval.

### Additional context

One example: 

### deluxe omelettes [Culinary Days Ahead]

**First Attempt**

List: 6 minutes, 7 seconds
Actual: 8 minutes, 43 seconds

**Second Attempt**

List: 6 minutes
Actual: 8 minutes, 30 seconds

**Third Attempt**

List: 6 minutes, 7 seconds
Actual: 8 minutes, 45 seconds

No resting, eating, drinking, or moving in between crafts. Same ingredient selection. Performed with Food Handling: 4 immediately after breakfasting in the morning. 

Second example (without crafting, just list time): 

### Polishing stone 

With Fabrication: 2. Lack of proficiency: 7.1x

**NIGHT**
Focus: 31
Tired
Hydrated & Satisfied
List time: 5 days, 21 hours 

**DAY** (after sleep)
"You're up and going rather quickly, and all the little aches from yesterday are gone"
Focus: 108
Fresh
Hydrated & Satisfied
List time: 6 days, 2 hours

Reported crafting times in bed right before sleep and right after breakfast.

Third example: 

### Distaff & spindle

With Fabrication: 2. Lack of proficiency: 2x

**First Attempt**

Crafting from Wield.
List time: 12 minutes
Actual time: 17 minutes

**Second Attempt**

Workbench. 
List time: 12 minutes
Actual time: 10 minutes.

The second attempt immediately followed the first. 

No gloves were worn or items wielded during any crafting, so manipulation penalties play no role (not that it should matter as long as the condition is kept constant across trials).

A character with 12 Intelligence was used.

Similar irregularities are observed with disassembly times.

**Comment by RenechCDDA** [comment]
You are correct that there is a (negative) modifier for simply working with it with your hands, and that workbenches(etc) provide faster crafting. You are also correct that this is not communicated to the player.

I guess the way to communicate this is to say that the crafting time displayed in window is the nominal/normal time, and display a message when crafting begins depending on the crafting location.

e.g. "Crafting this ham sandwich while wielding is slow" or "Crafting this ham sandwich is faster because you prepare the craft on the nearby workbench".

**Comment by Montimorency** [comment]
> You are correct that there is a (negative) modifier for simply working with it with your hands, and that workbenches(etc) provide faster crafting. You are also correct that this is not communicated to the player.

What about the seemingly random variation within the same workspace?

**Comment by RenechCDDA** [comment]
> What about the seemingly random variation within the same workspace?

I do not have access to that mod and I can only guess that you may have had a *minor* crafting failure during it, which can cause you to lose a randomized amount of progress. (Major failures make you lose components as well.)

If you can reproduce crafting time variation with the same conditions using known content, please share it.

**Comment by Montimorency** [comment]
> If you can reproduce crafting time variation with the same conditions using known content, please share it.

The mod item is functionally equivalent to the base game deluxe egg food items. 

This kind of irregularity can be reproduced with seemingly any crafting recipe. Low-skill and short-duration items can especially emphasize the lack of a rhyme or reason for the discrepancies. 

### Boiled egg

**First Attempt**

List: 10 minutes
Actual: 14 minutes, 18 seconds


**Second Attempt**

List: 10 minutes
Actual: 15 minutes, 20 seconds

**Third Attempt**

List: 10 minutes
Actual: 14 minutes, 19 seconds

**Comment by RenechCDDA** [comment]
I'm not able to reproduce on experimental. Attempts to craft boiled egg:

Nothing wielded previously:
10 minutes, 2 seconds

10 minutes, 9 seconds (thirst -1% speed)

Already wielding an item, taking a penalty:
14 minutes, 26 seconds (in hands)

14 minutes, 24 seconds (in hands)

**Comment by Montimorency** [comment]
I performed the same tests on the latest experimental. The variation was tighter than yours. 

I tried again porting my 0.G world over. This time there was zero variation no matter how many attempts I made. Even after waiting some hours, there was maybe a second's worth of variation on some instances. There was variation between subsequent days and under austere needs statuses, to be clear.

While overall the answer to my original concern almost certainly lies in the stable code, I do wonder why I saw no variation on the ported world (not that I dislike that).

**Comment by PatrikLundell** [comment]
As has been mentioned (and not listed in the metrics provided), minor and major failures will extend the time taken (with loss of materials as well, in the latter case). If the risk of failure is very high the time can increase dramatically. I don't think the estimate makes guesses about the time lost due to failures, but only the time it takes with no failures while accounting for the various multipliers caused by lack of proficiencies.

I speculate that you may also experience a reduced time if proficiency gains speed up the process during the task. There might also be other effects that might improve the speed in the middle of the crafting (such as no longer being poisoned, in pain, or improved mood). Note that I don't know how it's coded, but I would expect the estimate to be based on the crafter's properties at the time the craft is initiated without any attempt to predict how things would change during the crafting process itself.

**Comment by Montimorency** [comment]
The point of the multiple serial trials on something quick and basic such as "boiled egg" was exactly to demonstrate that what you describe couldn't be playing a role. The discrepancies from list times, and the variation between instances, are too great and erratic to be explained by appeal to these factors.

But the results in the experimental pretty conclusively demonstrate that there is a difference in code between stable and experimental dramatically affecting the craft time discrepancy, so the issue may be moot.
