### ISSUE TITLE
Monster pathing does not respect circular distances

### ISSUE THREAD

**Issue by RenechCDDA** [CleverRaven/Cataclysm-DDA#69643]
### Describe the bug

https://github.com/CleverRaven/Cataclysm-DDA/assets/84619419/7a27d680-aac4-443d-833b-a0194c9e0f23

At multiple points in this video the swimmer zombie moves vertically in additionally to horizontally. Despite this, they do not significantly lag behind the player.

### Attach save file

[Pawnee Station-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13439301/Pawnee.Station-trimmed.tar.gz)

### Steps to reproduce

Load given save, replicate movements in video

### Expected behavior

Monsters' move cost should follow the same rules as the player

### Versions and configuration

- OS: Windows
    - OS Version: 10
- Game Version: 02f75a2 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Translate Complex Dialogue [translate_dialogue]
]

**Comment by RenechCDDA** [comment]
This appears to be due to some 'stumbling' code inside mon::move (and not mon::stumble)

https://github.com/CleverRaven/Cataclysm-DDA/blob/02f75a2231393db391d883b357d93b5e26757cb4/src/monmove.cpp#L1323-L1338

**Comment by CoroNaut** [comment]
A swimmer zombie has speed 90 compared to a regular zombie's 70. So moving in a straight line, I expect to move 1 tile away from the swimmer every 10 tiles. This is exactly what I see when I put 2 parallel horizontal walls spaced apart with a 1 tile gap, without fail (this removes the possibility of a stumble). This is also what I see when going diagonal with 1 tile gap. If we use a 2-tile or greater gap, the monster is able to stumble. Since a stumble is unintentional, if the monster moves diagonally north or diagonally south towards the player on the horizontal strip, it could be like tripping forward. If a human were to trip forward, they may speed up to catch themselves before they fall. This can be the same for zombies.

Overall, I had noticed that movement in specifically 2-tile gap when going perfectly horizontal or perfectly diagonal allows the monster to move at about speed 91.5 to 92, rather than 90. This does suggest a small speedup. 

However, I think it would be more effective to do an analysis on the probability of a monster moving in each direction compared to where they would be without stumbling, and get your effective speed given stumbling that way. I'm definitely not qualified for that though. I just did a very small brute-force method of just leading the zombie through hallways for a few minutes.

My very simple solution is to just take away some move points if the monster stumbled, perhaps 2/100's of a move if the monster stumbles diagonally when intending to go perfectly horizontal. Similar for diagonal travel, etc. But this would effectively slow all stumbling monsters, so I'm not sure if there would need to be a balance change for them.

I modified your save file to include these 1-2 tile gaps courses for the zombies:
[Pawnee Station-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13444151/Pawnee.Station-trimmed.tar.gz)

![Untitled](https://github.com/CleverRaven/Cataclysm-DDA/assets/24307650/3f72bdfd-5b34-472e-b8a6-ba88da9238b0)
