### ISSUE TITLE
Amputees can take a huge beating due to being hit in limbs that don't exist

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#69647]
### Describe the bug

I tried the "One legged man in an ass kicking contest" challenge for shits and giggles. I noticed that my character was surprisingly resilient because half of the times I would be hit, no damage would be dealt, as the limb that was hit did not exist.

### Attach save file

N/A. Trivial to reproduce

### Steps to reproduce

1. Make a player with one or more limbs missing. The more, the better for reproducing the bug
2. Find a zombie. Get them to hit you.
3. Note that you are taking very little damage. The only effect is pain.

### Expected behavior

I would expect that if a limb cannot take damage because it is missing, damage is transferred to the torso. 

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: 02f75a2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Fewer Soldier Extras [Fewer_Soldiers],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Lonely Evac Scenario [Lonely_Evac]
]

### Additional context

If your character is missing both of their arms, their ability to fight back and therefore exploit this behavior is quite limited. It's still kind of strange.

**Comment by ZhilkinSerg** [comment]
Duplicate of #69575

**Comment by MNG-cataclysm** [comment]
#69575 was fixed. Considering this is a duplicate issue, we should probably close this one too.

**Comment by fungamer2-2** [comment]
If it helps at all, I would like to point out that the leg stub body parts have a `hit_difficulty` value of 10,000, and the arm stubs have a `hit_difficulty` of 1,000,000 (this is found in `mutation_limbs.json`)

And when selecting a body part to be hit by a melee attack, the weight is multiplied by "hit_roll ^ hit_difficulty" (`hit_difficulty` is the exponent)
https://github.com/CleverRaven/Cataclysm-DDA/blob/f2e04fa51a58c876665d5d2de9fb447b77a7d66e/src/anatomy.cpp#L226-L228


So, maybe the reason why other parts are mainly not being hit is because its hit_difficulty value is so high that it causes that part to have a large weight in the list, which is why it seems to only ever select that part and not others.
My suggestion would be changing the `hit_difficulty` value

**Comment by MNG-cataclysm** [comment]
I thought that hit difficulty worked inversely to what you've described. I'll go an fix that.
