### ISSUE TITLE
Refugee Center Doctor MIssion - Analyze Zombie Blood  can not complete

### ISSUE THREAD

**Issue by Cddaplayer** [CleverRaven/Cataclysm-DDA#69727]
### Describe the bug

Refugee Center Doctor MIssion - Analyze Zombie Blood can not be completed.
After putting a blood draw kit of zombie blood in the centrifuge, the centrifuge report keeps saying: Normal people's blood, no disease found. Can not save data in USA disk, mission stuck.

### Attach save file

NA

### Steps to reproduce

-Take "Refugee Center Doctor MIssion - Analyze Zombie Blood  can not complete
-Follow the directions, find the centrifuge in hospital
-Take zombie's blood in the blood draw kit
-Drop blood draw kit in a centrifuge
-Analyze

### Expected behavior

I am expecting to proceed this task, centrifuge screens should show something like "zombie blood found", and the data should be able to save in USB diskbe saved

### Versions and configuration

d7bcff2 64 bit

**Comment by PatrikLundell** [comment]
Are you completely sure you haven't drawn your character's blood instead, by accident?

My first attempt to solve it would be to empty the kit and try again with a new zombie (and make sure it's actually a zombie, rather than a feral, which might be another possible source of confusion).

Since you were lucky enough to find a working centrifuge in the hospital (they're usually smashed) it should be easy to retry. It can also be noted that since you didn't attach a save nobody can investigate your issue for you (nor did you provide the requested configuration info. The game can provide that for you by pasting it into the paste buffer. This is accessed from the escape menu (I can't give the exact instructions as I've activated debug info in my game, which adds an additional menu layer)).

I finished the quest a week or two ago with no issue beside having to find an alternative centrifuge location, so if there is an issue is should have been introduced fairly recently.

**Comment by Rabadash94** [comment]
Maybe you made a mistake and used an autodoc.

**Comment by Cddaplayer** [comment]
Hi Guys, thank you very much for the reply.
I am pretty sure there is an issue. The kit was emptied and I took blood from over 20 zombies (different types) and there always be the same result.
I think it is an issue of that experimental version. I will download the latest experimental version and test this mission again.
Have a great day.

**Comment by PatrikLundell** [comment]
You can compress and attach a save to allow others to look into it. There's an option to produce such a save under the escape menu. If you don't, you're more or less on your own (basically someone else will have to have the same issue and provide a save for the problem to be identified).

**Comment by Cddaplayer** [comment]
Hi Patrik

Here is a saved file that might help. 

I have the blood kit in my bag, and zombie blood in it. You can start testing this issue. There is a problem: I also tried to add blood into the centrifuge without a kit (already tried with kit) but now I can not clean out the blood. If you are able to take the splitted blood out, I think the test could take place.
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/13464395/save.zip)

Thank you again,

**Comment by PatrikLundell** [comment]
Thanks for the save. I think the issue is that you probably need fresh blood, not rotten blood.

You can remove fluids with a mop, so I debug spawned one and removed the blood splattered on the centrifuge, but didn't check first if that's an issue or not. You can also remove sludge trails with a mop, and I would assume it also works on acid, although I haven't tried that.

I tried to analyze the blood you had, and it indeed showed up clean.

Next I emptied the kit, and found you had a second one, so I emptied that one too, just in case, went to a nearby zombie (rotten), drew blood and went back to the centrifuge, analyzed it, and got the same result.

Then I emptied the kit, debug spawned a regular zombie (the type shouldn't matter), debug killed it, and drew its blood (I didn't pulp it first, but I don't think that matters), tested the blood, and finally got the desired report.

So: You'll have to empty your blood draw kit, locate and eliminate a new zombie, draw its blood, and analyze it. I think you have to do that before the blood rots, as I believe it rotted for me as I was hunting for a working centrifuge in the past.

For the game, it seems there should be a different message for rotten blood stating that it's rotten and cannot be analyzed, rather than (I assume) fallback to claim the blood is of the normal human variety.

I don't know where the relevant code lies, so I'll leave it to those who do to fix the issue (after checking if assumption is correct).

**Comment by Cddaplayer** [comment]
Hi Patrik, thank you for the testing.

For the scenario you mentioned, I also have tried a few times using freshly killed and butchered zombies around me and analyzed by centrifuge, same issue. If you notice in the save file I provided, the blood kit in my bag is just from a zombie I killed a few rounds ago. Plus, if the blood is rotten, it will show a bracket with (Rotten) in it, which is not.

Glad to hear that when you debug a zombie it works well with its blood. It has to be something different between the zombie you debugged and dozens of zombies I killed. If you don't mind, you can try to use my weapon to kill any zombie in the building (I am pretty sure there is still a lot), and test their blood. I assure you the test result will still be "Normal blood not disease found".

Thank you for your help

**Comment by PatrikLundell** [comment]
No, it still works correctly correctly:
- Empty both kits as well as the bottle with blood, and clean away the blood on the centrifuge.
- Hunt down a zombie (brainless, happened to be the case I encountered).
- Kill it (using your tool rather than a weapon...)
- Draw blood from the corpse.
- Pulp it out of habit.
- Return to analyze the blood.

I wouldn't be surprised if the game got confused somehow by your multiple blood draw kits. However, I emptied both the bottle and the kit with rotten blood to test your fresh sample, and it was still reported to be without pathogens, so there is something else there as well.

Note that the steps I listed above were the ones I used, rather than the minimum set that's actually required. Some parts might not be required.

**Comment by Cddaplayer** [comment]
Thanks.
"However, I emptied both the bottle and the kit with rotten blood to test your fresh sample, and it was still reported to be without pathogens, so there is something else there as well."

So does that mean there is still a bug?

**Comment by PatrikLundell** [comment]
Yes. There appears to be two issues:
- Rotten blood seems to be reported as normal, when it should be reported as degraded and not possible to analyze.
- Your fresh blood as well as "fresh" blood I drew from a rotten zombie were reported as normal for some unknown reason. Whether that's caused by the game confusing the blood with rotten blood in the bag still carried (and also when it was previously carried), blood in the bottle (again also remaining after it had been emptied), or something else is unknown.
