### ISSUE TITLE
Allow player to prioritize a component in disassembly if they would not already receive all the components

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#69839]
### Is your feature request related to a problem? Please describe.

Currently, disassembling an item yields components based on the items damage, This is fine, but what If I really needed just that one component and I just barely missed out getting it because the item was slightly damaged.

I like the idea of losing components based on skill as well, I made a separate feature request for that: #69838

### Solution you would like.

It would be nice if the player could select a specific component from the disassembly to prioritize at the expense of losing more of the other components. 

### Describe alternatives you have considered.

Just living with the fact I can't prioritize components that I _want_.

**Comment by Brambor** [comment]
You could order all the components by the priority you wish to obtain them. There could be default ordering and it could remember your ordering.

**Comment by PatrikLundell** [comment]
Damaged components are damaged somewhere, and you can't just wish the damage away to somewhere else where you don't care about the damage.

It's a different issue with your other suggestion, where it ought to be possible to prioritize cannibalizing a particular component at the expense of others when you lack the ability to get them all without damaging something due to a lack of skill (or, for that manner, the manner of the item construction: if you have to cut through something, the cut has to be placed somewhere, and there's not always a convenient seam you can unravel).

**Comment by CoroNaut** [comment]
As far as I know, the game currently has no way to tell _where_ an item/enemy was damaged. If I attack a moose and only get head shots, surely there should be no brains left.

So basically, its a role-play thing until item/monster damage is modeled in much finer detail. You are right that damaged items and damaged _somewhere_. Where is it? Nobody knows. But you can role-play that you tried to only head shot the moose so you can maximize the amount of meat you get from the main body. If it's an item like a television that's damaged, it could be just the screen that isn't salvageable, so why should that stop you from getting the plastic chunks out of it?

Until the damage to an item or monster can be placed onto the individual components themselves, I think it's probably fine to role-play it.

**Comment by PatrikLundell** [comment]
The current system or randomly succeeding in recovering components is a crude model of damage existing somewhere.

I struggle to find a case where you caused the damage and thus selected what parts to damage, with the only exception being combat damage. In most cases you're trying to get stuff out of damaged equipment because it was damaged when you found it.

**Comment by CoroNaut** [comment]
It isn't about the player causing the damage. we don't have any way to know what caused the damage, let alone where the damage actually is, because it isn't coded.

**Comment by CoroNaut** [comment]
I gotta admit I was also thinking that specifying exactly what components are damaged for each individual item was probably never going to happen. That's why I'm suggesting we allow this feature simply as a role-playing option. I'm thinking we can provide a slightly better experience for players. Trying to disassemble items to get maybe that one more power converter or a little more plastic chunks at the expense of disregarding the rest of the object would add quality of life. 

I brought up the moose as an example to show how role-playing this would work. That's if this system of prioritizing components was already implemented, I could role-play that I tried to get all headshots, and therefore was able to prioritize the meat and scraps of meat. 

Components wouldn't be damaged randomly though. Even without this feature, role-play would still suggest that the slime filled lab had lots of damaged items from bashing. If a zombie bashes a television on the outside, the copper wire inside really shouldn't be affected all that much. The big screen should however be completely shattered. Items around a lot of electrical zombies would have more electrical components fried, etc. My argument would then be that randomly damaging every component doesn't make the best of sense, and that the player could assign some amount of cause to an items damage.
