### ISSUE TITLE
Enhancement of Crafting System with Experimentation/Innovation Mechanism

### ISSUE THREAD

**Issue by whyes17** [CleverRaven/Cataclysm-DDA#69855]
### Is your feature request related to a problem? Please describe.

The current system confines most recipes to pre-existing knowledge or written instructions. This often leads to a dire need for books, which may not always be accessible depending on the playthrough. Furthermore, the process of learning how to create something shouldn’t always be about finding and following a step-by-step guide. A fundamental understanding of underlying principles of a craft should allow us to reach our desired goal of, such as the creation of a tool or item.

For instance, someone with a grasp of carpentry doesn't necessarily need a detailed schematic to construct a table or stool. Simply having a conceptual understanding of what a table or stool is should suffice for them to create one. This approach can somewhat remedy the dire need for books for playthrough that the player may not have access to such resources.

Auto learned recipes are the current solution to this concept, but it is very unintuitive , not very immersive/realistic and does not cover the issue i mentioned.

### Solution you would like.

The proposed system would allow the player to choose certain materials and a certain function (such as prying, cutting, hammering, piercing, digging, etc...) and then put some time into trying to think up of items they could create that would relate to what they want.
The player should also be able to contemplate on what improvements they could make to certain items or how they could combine separate items together to make a new item.

For example, picking up a stick and trying to see if they can somehow make a better weapon with it, leading up to things like a makeshift spear or a knife spear ( by performing the same process with a knife).

The process of experimenting and inventing new items would be dependent on both the player’s current knowledge of the relevant subject (or proficiencies) and their intelligence score , and could even be possibly locked behind "inspirations" (this last part is just a fun addition i thought would be cool).
by inspirations i mean encountering certain scenarios/enemies/items/situations or having performed certain actions (crafting/using other items or dissecting or reading about a certain topic) or maybe even the use of stimulants could be integrated into the inspiration.

The process of innovation or experimentation would require time and focus as their resource and may not have a guaranteed outcome , since it is just experimentation and not practice (practice is honing your skill, experimentation is trying to conceptualize and realize new potentials).

The more on point the player is with their chosen items/materials/proficiencies/knowledge to contemplate upon, the more likely they are to succeed at coming up with an idea, but less likely to find other possible outcomes with their chosen items (narrowing the focus).
For example, for the mentioned knife spear, if the player only chooses a stick, they are much less likely to come up with a knife spear (if any craft at all) , but if they choose a stick and a knife , they are suddenly much more likely to think of a knife spear. add  duct tape or strings to the group and the chance would be even further increased (while further reducing the chance for other items).

So trying to advance a skill only through self learned experience and experimentation would require a considerable amount of focus and time compared to the current implementation of skill progression (reading books and crafting their recipes).
This process would result in a makeshift version of an already existing tool, giving intelligence builds the same bit of early game advantage that other builds possess by allowing them to bypass some of the waiting time that are imposed by the rng based nature of loot from world.

While the current system of auto-learned recipes and gaining knowledge from books would still be a part of the game, the proposed system would provide an alternative way for players to learn and invent items they didnt have access to before, and in my opinion, all auto learned recipes  (which contain almost all of the current makeshift recipes) should only be (partially) auto learned when the player has points spent into their respective skill during the character creation and not be auto learned when a player with lower skill advances to a higher skill threshold , since auto learning recipes on level up is akin to having your character suddenly gaining perfect knowledge on random items they have never encountered or tried to make, which is weird.

Books would still act as a faster and more reliable/foolproof way of advancing your knowledge and crafting capabilities and most unique and complex recipes would still be locked behind books and written instructions, but if we are trying to make the game as immersive and realistic as possible , i think having an improvisation and experimentation mechanic is very much needed.
In short, you shouldnt have to re invent the wheel, but you should be able to if you desire to do so.

This mechanic would give the player more agency on the direction that they are going to progress within their crafting skills and even possibly shortcut their way by progressing through their preferred route towards the higher levels of their skill by focusing their efforts on the section that they prefer to specialize in rather than reading books on topics they might not really care about .

### Additional context

This system would not only enhance player involvement with their characters skill advancement, but also introduce a more gradual introduction to new craftable items.
It would also reintroduce a sense of discovery for new items without making the players (specially newer ones) feeling overwhelmed.
In addition, it would reduce the need to search for books as a mandatory progression gateway, which can be annoying in certain playthroughs.
This system could also apply to cooking, allowing players to think up new dishes they could make from the ingredients they currently have, or even applied science and dissection/weakpoint (and some of the currently non functional lab equipments), allowing the player to think up of items that can be particularly effective against certain enemy/enemytype.

Lastly, since the game is set in an apocalyptic world where not much makes sense as it used to anymore, it would be great if the player had the opportunity to make items that people didn’t really think they would need before the apocalypse!
This could open up the way for addition of new item recipes that would not make sense for a world before the apocalypse, further enhancing the game’s realism and immersion while opening up a way to introducing lorefriendly ways of adding post apocalyptic crafts.

**Comment by vivyir** [comment]
i'm a big fan of this suggestion! the autolearning mechanic is really a bit of an obstacle every time i decide to do games based around roleplaying but then this random makeshift item i want to improvise is locked behind a specific skill level i'd have to get to. books work for complex recipes as mentioned but they're still major obstacles if you can't find them.

as for the solution i mainly want to summarize and cement everything already mentioned.

everything could be bundled up into a "ponder" action (name to be decided?) where then you could either focus on trying to make a specific tool with a specific quality (like cutting, prying etc) and then afterwards you'd select the items to experiment with and try to make something out of.

or you could go the other route; don't look for a particular tool quality, rather just select the items you want to mess around with and do that (up for discussion on the ui/ux); it'll end up with a lower chance of discovering recipes but if you're lucky or have high intelligence or all other variables that would be accounted for, you'll figure out some recipes that use the given items as components.

another addition i have is we could most likely calculate the discovery recipes at runtime rather than making json entries for it; with enough fiddling around it'd be possible to come up with a formula for recipe discovery that takes into account the craft difficulty, the proficiencies, the skill level required and intelligence that we can use over the generated entries. on world launch we can enumerate all the recipes and only take into account the important things in recipes (skill level required, craft difficulty and components plus the result of course) and then in the ponder code we can search based on those

these are all just ideas and speculation but this mechanic would make crafting much more fun. instead of going to the hitchhiker's guide to check what book you need to craft an item you could theoretically do a fully blind playthrough using just your intuition, not to mention all the roleplaying possibilities that come with it!
