### ISSUE TITLE
Autopickup shouldn't grab containers just because there's a single item on the autopickup list inside.

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#69862]
### Is your feature request related to a problem? Please describe.

Have autopickup set to grab something that's often alone in zombie's pants pockets, like a cell or smart phone. Walk around, and find that you've grabbed an entire pair of filthy ski pants instead of the cellphone you wanted. Or a whole wallet instead of the cash card, and so on. From testing, if autopickup grabs something that's the only item in a container it'll grab the container as well. This is fine if it's a light plastic bag, but if it's a pair of pants or other piece of heavy clothing, it's very inconvenient. 

### Solution you would like.

Have autopickup ignore containers when using autopickup unless it would be necessary to contain the item on the auto-pickup list, as in the case with liquids (or, one day, powders, assuming how they're handled gets updated.) 

### Describe alternatives you have considered.

1. Leaving it alone and leaving us to dump random garments, bags, pill bottles, boxes, and wallets whenever we're sorting inventory after a looting run. 
2. Setting some volume/weight limit on the container size that'll come with, or a setting to set personal preference for containers.

**Comment by CoroNaut** [comment]
Quantities of items in the hundreds or more take _a lot_ of moves to haul them, pick them up, or put them down. like, about 10 in-game minutes to move 1,000 citric acid from one spot to another. So it is definitely handy to keep these high amount items in a container, which can be moved in seconds. I can imagine if you have auto-pickup on in a lab and all of the sudden spend 5 minutes picking up that random powder stack you came across and having tons of zombies swarm in before safe mod activates. So definitely make it an option to ignore containers rather than be default.

As a general caution: Taking items out of containers that can produce large stacks like painkiller pills or powders also provides a general slowdown when working with the stack. I made an issue for that: # 69577.

Similarly to your issue, If you have ammo in your auto pickup list, and theres ammo inside a magazine inside a zombie's pocket, it won't be picked up. I'd prefer an option to also allow unloading magazines (or more general option for unloading containers).
