### ISSUE TITLE
Fire Performer still gives High Adrenaline, but the trait is unselectable

### ISSUE THREAD

**Issue by Consoleable** [CleverRaven/Cataclysm-DDA#70028]
### Describe the bug

High Adrenaline now has mutation threshold requirements, but Fire Performer background still lists it.

### Attach save file

Character Creation experimental 2023-12-06-1516

### Steps to reproduce

Select Fire Performer background
High Adrenaline is visible in traits, but cannot be selected
High Adrenaline isn't in Character Description

### Expected behavior

Either fire performer should provide a working high adrenaline trait OR it shouldn't mention it at all. 

### Versions and configuration

Character Creation experimental 2023-12-06-1516

**Comment by NetSysFire** [comment]
First of all you did not fill the versions and configuration section as expected. And your "uploaded" file was never uploaded but consider just linking to the file in our git tree instead.

**Comment by Consoleable** [comment]
> First of all you did not fill the versions and configuration section as expected. And your "uploaded" file was never uploaded but consider just linking to the file in our git tree instead.
I don't know how to do that since its not part of a save file and i dont know how to do the link thing you were talking about. I'd like to know how but i dunno where to go or how to figure it out.

**Comment by NetSysFire** [comment]
You do not need to provide a save for that but your versions. Do not just put an ordinary version string there since mods and the environment matter a lot. The instructions are there when you create the issue, which instructs you to go to the debug menu -> info -> create game report (r).

Omitting those without a good reason is likely to get your issue misinterpreted. For now it is fine but think about that next time.
