### ISSUE TITLE
Change cooking to warn about cooking with rotten ingredients

### ISSUE THREAD

**Issue by bug-sniper** [CleverRaven/Cataclysm-DDA#7007]
I sometimes cook without knowing how rotten my ingredients are. This sometimes causes the result to be rotten immediately after making it, wasting time and ingredients. To fix this, it would be a good idea to
1. Display how rotten an ingredient is during ingredient selection.
2. Revert rotting of selected ingredients during cooking equal to the cooking duration.
3. Warn if the player is not a saprovore and all valid choices are rotten.
4. Maintain rottenness proportions rather so that food that has been left out longer than the result's time of perishing is not perished. Otherwise, you cannot make rhubarb pies with rhubarbs that are still ok without having the pies be rotten when you make them, and you can make jerky out of rotten meat with toxins that shouldn't go away with heat.
##

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.

**Comment by victorsegall** [comment]
I think this should go back into the pool. I know that Saprovore is in play from watching YouTube LPs, but I've accidentally wasted craft cycles on rotten ingredients, and I've also hit the exception error that happens when used ingredients are currently being disposed of in the cooking fire because they're rotten.

Seems, in concept, that a player query is needed, with the rotten ingredients differentiated like variable ingredients are.

There's also related player exploits here. The example I've found is that sealed stomachs can be crafted with rotten stomachs.
