### ISSUE TITLE
A way to prioritize charging vehicle battery

### ISSUE THREAD

**Issue by gettingusedto** [CleverRaven/Cataclysm-DDA#70125]
### Is your feature request related to a problem? Please describe.

It would be neat to have a way to prioritize charging my EV battery.

### Solution you would like.

Something like an EV charging station or similar implement.

### Describe alternatives you have considered.

Not doing so.

**Comment by CoroNaut** [comment]
Additonally, fuel stations, apartment parking lots, and just regular large parking lots could be outfitted with EV charging stations. Probably have a 10-20% or so chance for them to appear. Most vehicles aren't electric as far as spawning rates go. Perhaps someone could look at the current state of EV charging infrastructure IRL for it.

**Comment by MrHrulgin** [comment]
I like the idea of EV charging stations for additional flavor, but they wouldn't serve much gameplay purpose except perhaps as a place where you're likely to find EVs abandoned by their owners. All current tech EV charging stations are connected to the municipal grid for their charging purposes, which means that charging your car isn't possible at the point that the game is set. The most you'd find is a dead terminal and a heavy duty charging cable (perhaps less lossy than the heavy duty jumper cable?)

**Comment by PatrikLundell** [comment]
My understanding is that recharging stations for private use are capable of being fed by private solar arrays even when the external grid is down, so it ought to be possible to take down such a charger and move it to your base (assuming, of course, they were implemented in the game). I further believe these aren't fast chargers, but rather intended to recharge vehicles over many hours. Note that I don't actually know these things for a fact.

In the mean time it's possible to use recharging stations and drop your swappable storage batteries in these for recharging, although you'd probably want several stations used in parallel.

A major problem with using jumper cables is that they equalize the power level on all batteries in the connected networks rather than transfer charge in one direction, so if your base batteries are low you may end up recharging those from your vehicle initially before slowly topping up everything in parallel from the solar arrays.

**Comment by CoroNaut** [comment]
Charging a vehicle whether it is supplied by the infrastructure before the cataclysm or after will take hours. However, the first 80% of that charge is much faster than getting to 100%. This would need a significant re-work of how the electrical system works. 

Source: [tomsguide](https://www.tomsguide.com/news/how-long-does-it-take-to-charge-an-electric-car-what-you-need-to-know). 

> The good news here is that charging to 80% is a lot easier than charging to 100%, and not just because you’re adding less power to the car. 
Have you ever noticed how a lot of tech companies advertise fast charging speed up to the 80% mark? That’s because the more power your battery has, the slower it charges, and 80% is the point where charging speed nosedives. Even rapid chargers, which can offer insanely fast recharge speeds, slow to a near-trickle as you edge closer to 100%.
Trying to reach 100% can add a few extra hours onto your total recharge time, so it’s just not worth doing unless you absolutely have to. The fact you’re keeping the battery in better health is just an added bonus.

Note that it says that it charges _slower_ when it gets more and more charge, which as stated above, isn't how things work in-game right now. I would assume this also requires that the source of the power be equivalent to an already-full battery? Assuming the car and source battery are equivalent, charging an electric vehicle past 50% if your source has only 50% charge would be impossible, and getting from 40 to that last 50% would take many many hours. That even assumes the source battery has 50% charge the whole time, which it won't, it will obviously deplete to fill the car. So getting to even 15% would take a long time.

Apparently there are also different chargers with different speeds as well: 

> Level 1 (slow) charging: Slow, or Level 1 charging means your charging speed is under 7kW. Typically these chargers are around 3kW, though 5kW slow chargers do exist. Slow chargers utilize alternating current (AC), and can take anything from several hours to a few days to fully recharge a car.
Level 2 (fast) charging: This covers the 7kW to 22kW range, and can recharge your car’s battery much faster than a slow charger. While they are not particularly “fast”, they will typically recharge your car in a few hours. Though, as ever, it’s all dependent on which car you have. Fast chargers also use AC power.
Level 3 (rapid) charging:  Rapid charging is the fastest type of electric car charging available, and includes speeds upwards of 50kW. There’s no hard limit on what constitutes a ‘Rapid’ charger, and there are chargers out there that can offer up to 350kW speeds. They are rare, and very few cars can actually handle that much power.

These three types of chargers would be neat to have as well. Standard apartment building parking lot might have two level 1 chargers. A gas station between towns might have a level 2 charger. Then the nuclear power plant might have a level 3.

Swappable battery storage cases for the win, swap batteries between trips away from home. Love the idea of having EV chargers though.
