### ISSUE TITLE
Make getting anvils easier again

### ISSUE THREAD

**Issue by physics-enthusiast** [CleverRaven/Cataclysm-DDA#70182]
### Is your feature request related to a problem? Please describe.

Steel anvils are now unusually difficult to obtain, requiring one to get lucky with a roughly 1 in 10 chance to spawn in light industry or find a railroad track somehow. 

### Solution you would like.

Given steel smiting has been a thing since at least the industrial revolution, and iron smiting much longer than before, there should be at least some kind of (possibly time consuming) means of obtaining anvil 3 quality with raw steel. After all, the ancient peoples were able to craft anvils usable for weaponsmithing and toolmaking without needing drill presses or railroad tracks and whatnot.

**Comment by fairyarmadillo** [comment]
Ancient people had entire communities who spent generations building the infrastructure to make high quality iron forging possible. It took them thousands of years to be able to even begin to attempt it. Modern people do not have anvils lying around all over the place.

Even so, you can make one easily out of a railroad rack and an angle grinder, and there's a guaranteed way to access one in the blacksmith's workshop.

**Comment by physics-enthusiast** [comment]
With the accessibility of power tools even post-Cataclysm, it should be possible to jumpstart this process considerably, no? There are several videos online detailing how to make anvils from blocks of steel, drills and angle grinders, although in all fairness I'm not familiar enough with the metalworking industry to judge if these would withstand the rigours of extended toolsmithing.

**Comment by actually-a-cat** [comment]
> With the accessibility of power tools even post-Cataclysm, it should be possible to jumpstart this process considerably, no? There are several videos online detailing how to make anvils from blocks of steel, drills and angle grinders

You're just describing the existing recipe to make an anvil from a piece of railroad track. If you can think of other examples of large blocks of high-quality steel that are or should be present in the game, including them as alternatives to the track should be reasonable.

**Comment by physics-enthusiast** [comment]
Would a recipe with a regular cordless drill instead of a drill press taking ~10x the time be reasonable?

**Comment by fairyarmadillo** [comment]
I don't think cordless drills can go through tempered steel.

You're right that we could use more railroad track-like objects, though. The steel mill should have steel beams in it, at the very least. We could also use a steel-frame construction site, such as an unfinished hospital or municipal building.

**Comment by actually-a-cat** [comment]
The steel mill has railroad tracks. Not that it necessarily shouldn't also have beams, but it's already a source of anvils.

**Comment by fairyarmadillo** [comment]
> The steel mill has railroad tracks. Not that it necessarily shouldn't also have beams, but it's already a source of anvils.

Oh nice.

Other places I can imagine finding an anvil or something that could be used to make one: The reenactor fort (if it's even still in), a more well-stocked junkyard, we could make one of the little island cottages be blacksmith-themed (they're usually pottery themed currently, rural people get up to all kinds of hijinks though), and any farm with horses - I believe farriers still commonly use anvils in their work. Isherwoods could also have one that they'd let the player use if they became friendly.

More long-term, we could create a new kind of preexisting wall that has stronger bash resist and potentially drops a steel beam segment if destroyed, then start placing those at the corners in preexisting buildings where they'd make sense. Parking garages, the research center, and hospitals come to mind. Clever players could find a way to smash them out, or they could jackhammer the thing or look for a place where a bomb has already exposed what they need.

**Comment by KHeket** [comment]
> large blocks of high-quality steel that are or should be present in the game, including them as alternatives to the track should be reasonable.

For blacksmithing you don't need factory made high quality extra durable metal like we have in rail roads tracks. You are working with heated metal, very flexible. Lots of blacksmiths in past didn't have access to at least half good metal, they didn't have knowledge, technologies, instruments, that have our character, but they can also make good blacksmith things

I can understand need of extra durable anvil in recipes with using **power hammer**, yes, its logical, because power hammer in big and powerful machine, but in blacksmithing only power is in your hand with hammer, and instruments, and its enough for all blacksmith recipes

Also don't forget, that two more ways to make a good anvil is
1) Make big anvil mold and fill it with melted metal
2) Make it like in medieval (a little similar) - raw iron ore was smelted in a chimney shaped furnace into a spongy bloom and then wrought (beaten) into a workable shape and alloy. The first iron anvils were simply very large blooms worked into a block with at least one flat surface.
In this case you can use metal objects and have benefit. Ore can have impurities, what will make metal worse, but when you will use modern already cleared from impurities metal objects - your anvil will be much more better

**Comment by Karol1223** [comment]
> Make big anvil mold and fill it with melted metal

Making a proper solid anvil this way that does not have empty spaces inside it is not anywhere near easy. Casting steel is something far more difficult than people seem to give credit to, and nobody has made any steps towards implementing it accurately.

You can already cast bronze anvils, but I'm not 100% sure how accurate that is either. Casting bronze *is* easier, but casting a sufficiently big solid block of bronze probably would be easier said than done regardless.

**Comment by fairyarmadillo** [comment]
@Karol1223 Would it be acceptable to assume that a poor quality cast iron anvil would still be usable for lower grades of steel? This is outside my wheelhouse when it comes to rl knowledge.

I know hardware stores irl sometimes sell anvils, but I've heard hobbyists saying they're cast iron and unreliable for high quality stuff.

**Comment by KHeket** [comment]
> Making a proper solid anvil this way that does not have empty spaces inside it is not anywhere near easy.

I didn't anywhere say, that it is easy. I said, that its possible. And 
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/102726167/15f431f4-26f0-4465-bcd7-09aa0bd42cbc)
And making big metal items via molding without empty space is not that hard with proper skill, knowledge and instruments. You also don't need to have anvil big in size
Bronze is harder to make, thats why irl you will not see any of it in blacksmith workshops

**Comment by Karol1223** [comment]
> @Karol1223 Would it be acceptable to assume that a poor quality cast iron anvil would still be usable for lower grades of steel? This is outside my wheelhouse when it comes to rl knowledge.
> 
> I know hardware stores irl sometimes sell anvils, but I've heard hobbyists saying they're cast iron and unreliable for high quality stuff.
> 
> This would help provide a sense of linear progress as characters started with a boulder, moved up to a crap cast iron anvil, then finally progressed to making or finding a proper one. I think people really get a kick out of that kind of progression.

This is way beyond my scope of knowledge, most blacksmithing stuff I've done was constantly reviewed by @Drew4484 because I am simply not knowledgeable enough (and so I opted to instead annoy Drew to review it and make sure I wasn't making mistakes) - what I do know is that the last time I touched blacksmithing the idea of casting steel was summarized as something along the lines of "hell yeah, we want it, but nobody did anything to implement it properly". 

I think you know my opinion on the linear progression from rock to steel - that's something I firmly believe should be kept in Innawood. Some limitations you will not go past without straining the realism (but do note that I am not sure whether this is one of them!). The problems of anvils being difficult crafts have been, in my eyes, fully resolved by the addition of spawns of them in the world. I do not believe that it should EVER be easier to create your own tools than to loot them. The world has an overabundance of tools irl, and with the population diminished by the Cataclysm they'd be a way better source than trying to play Minecraft.

**Comment by fairyarmadillo** [comment]
> I think you know my opinion on the linear progression from rock to steel - that's something I firmly believe should be kept in Innawood. Some limitations you will not go past without straining the realism (but do note that I am not sure whether this is one of them!).

I'm not suggesting we add anything unrealistic for purposes of gameplay, nor am I saying that hand crafting your own f-15 tomcat should be easier than stealing one from an unmanned airfield. It's just that many people want to have the ability to progress that way outside of Innawood and we ought to include it if it's reasonable to do so, even if it's less than ideal.

**Comment by Karol1223** [comment]
> I'm not suggesting we add anything unrealistic for purposes of gameplay, nor am I saying that hand crafting your own f-15 tomcat should be easier than stealing one from an unmanned airfield. It's just that many people want to have the ability to progress that way outside of Innawood and we ought to include it if it's reasonable to do so, even if it's less than ideal.

And for the record - that I fully support. I am of the opinion that if the players want to go the extra mile to bushcraft stuff, they should be allowed to do so - but I also do believe that we should properly simulate the difficulty of going that extra mile (this is all under the assumption that allowing the players to do so is realistic in the first place, but for the purpose of this let's assume it is). This is why for example I locked the recipe for alloying bronze behind a book - you won't get proportions for alloying come to you in a dream just because you're more experienced with blacksmithing, so prior to that casting bronze was unrealistically easy.

The problem with steel casting is that many people would like for it to just be making a sandbox, drawing a shape in the sand, and pouring steel in there, which just doesn't work. Back when I worked on #67139 I read into cast tools and... it's really not simple. I ended up taking an "artistic liberty" to allow the tongs to be cast, but they really should not be (or rather they should be, but the resulting item should become damaged as it's used for crafting - which we can't simulate). There were several hoops to jump to simulate realistic steel casting, and I just opted not to touch it at all because it's more work than I can afford to do nowadays. @Drew4484 offered to help me with his knowledge on it, but I'm not convinced proper steel casting would not involve C++.

**Comment by physics-enthusiast** [comment]
What about forge-welding chunks of steel together? [This wikipedia page](https://en.wikipedia.org/wiki/Anvil#:~:text=The%20basic%20process%20involved%20forge%2Dwelding%20billets%20of%20wrought%20iron%20together%20to%20produce%20the%20desired%20shape.%20The%20sequence%20and%20location%20of%20the%20forge%2Dwelds%20varied%20between%20different%20anvil%20makers%20and%20the%20kind%20of%20anvil%20being%20made.) seems to suggest that it would be possible for at least wrought iron anvils, although not exactly what one would call "easy".

**Comment by Drew4484** [comment]
I'll refer to the notes I left on the original discussion so I'm not just repeating myself: https://github.com/CleverRaven/Cataclysm-DDA/pull/64595#issuecomment-1506525069 and https://github.com/CleverRaven/Cataclysm-DDA/pull/64595#issuecomment-1506660157. The TL;DR is that a cast anvil is worse than a forged one, and forging a proper anvil is hard *but* pays off as it will last longer and require less mechanical energy from the person crafting, as well as saving fuel for reheats.

You absolutely can cast an anvil, it will be of lower quality. Forge welding an anvil is preferable, but without serious industrial equipment it is extremely labor-intensive (imagine a dozen people with sledgehammers pounding a near-melting chunk of metal into the shape of an anvil before it cools too much and will have to start over).

Casting in general is fine for making parts and tools but will always be inferior in terms of strength and durability when compared to forged items.

If you're playing in the core game, go find an anvil, if you're playing Innawoods, get used to not having access to the output of modern industry.

**Comment by TheShadowFerret** [comment]
In the event you can't find an anvil/railroad track, the ubiquity of aluminum foil in kitchen cabinets & copper tubing from sinks & showers allows casting a bronze anvil without lots of searching to get rare spawns

**Comment by physics-enthusiast** [comment]
Fair enough, conceding on the balance aspect. As for the limits of bushcrafting, is a monthslong or yearlong project retracing the historical development of metalworking something a lone survivor could feasibly achieve?
Maybe something along the lines of:
Anvil 1 + Hammer + Lots of metal sheets + Strong heat/Arc welder -> Metal crucible
Large container + Refractory material of some kind -> Casting bucket
Large container + Refractory + crucible + piping + source of HHO/Propane/Acetylene -> small makeshift foundry
Multiple small makeshift foundries running in tandem + Casting bucket/Hole in the ground(?) + metalworking tongs -> Crude anvil (Anvil 2) and chance of serious injury
Anvil 2 + Hammer + Chunks of steel and/or other source of raw material + Strong heat/Arc welder -> Trip hammer
Anvil 2 + Trip hammer + Water wheel/Steam engine/Electric motor nearby + Strong heat/Arc welder +  Lots of steel + Lots and lots of time -> Drop hammer
Anvil 2 + Drop hammer + Steam engine/Electric motor nearby + Source of heat + Chunks of steel -> Anvil 3

@Drew4484 @Karol1223 @fairyarmadillo any thoughts on if this would be realistic?

**Comment by Drew4484** [comment]
> Fair enough, conceding on the balance aspect. As for the limits of bushcrafting, is a monthslong or yearlong project retracing the historical development of metalworking something a lone survivor could feasibly achieve?
> Maybe something along the lines of:
> Anvil 1 + Hammer + Lots of metal sheets + Strong heat/Arc welder -> Metal crucible
> Large container + Refractory material of some kind -> Casting bucket
> Large container + Refractory + crucible + piping + source of HHO/Propane/Acetylene -> small makeshift foundry
> Multiple small makeshift foundries running in tandem + Casting bucket/Hole in the ground(?) + metalworking tongs -> Crude anvil (Anvil 2) and chance of serious injury
> Anvil 2 + Hammer + Chunks of steel and/or other source of raw material + Strong heat/Arc welder -> Trip hammer
> Anvil 2 + Trip hammer + Water wheel/Steam engine/Electric motor nearby + Strong heat/Arc welder +  Lots of steel + Lots and lots of time -> Drop hammer
> Anvil 2 + Drop hammer + Steam engine/Electric motor nearby + Source of heat + Chunks of steel -> Anvil 3
> 
> @Drew4484 @Karol1223 @fairyarmadillo any thoughts on if this would be realistic or at least theoretically possible? 

Realistically no, without access to industry. You're not going to be welding, capturing/refining gasses and obtaining the necessary chemical/mineral resources is way out of scope. Consider that civilization existed for thousands of years before these things were available and achieving modern industry only came about with global connections. A thousand of the best engineers can't make chromium appear if there isn't a source.

**Comment by Zireael07** [comment]
Strongly doubt anything beyond first two lines is realistic for a single survivor

E: Oh I see Drew already answered

**Comment by PatrikLundell** [comment]
Someone suggested being allowed to use the Isherwood anvil, which is reasonable once they have one, given that one of their missions is to provide them with an anvil...
