### ISSUE TITLE
Discussion: Incomplete features should be toggleable in stable

### ISSUE THREAD

**Issue by physics-enthusiast** [CleverRaven/Cataclysm-DDA#70295]
### Is your feature request related to a problem? Please describe.

A bit of a controversial topic, so if this isn't the place to discuss it please do let me know and I'll take it down. The general justification I hear for not permitting certain features to be turned off in the main branch is that the annoyance will motivate someone to fix/improve it and not stagnate. However, setting aside features considered "complete", should it not at the very least be the responsibility of whomever introduces a mechanic to leave it in a playable state? The most relevant example being of course portal storms.

### Solution you would like.

As a compromise, if a contributor themselves defends a issue with something they introduced with some variation of "implementation is half-complete", players should be able to turn it off in the stable releases. That way, experimental can continue to be used for its intended purpose of playtesting new unfinished features, while people who just want to play the game can stay on stable. Then, the incentive for trying unpolished changes and giving feedback will be access to the rest of the new content as opposed to the ability to derive enjoyment from CDDA.

### Additional context

[This reddit comment](https://www.reddit.com/r/cataclysmdda/comments/11pjvwy/comment/jbz7adv/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button) would be an example of a defence of existing problems with promises of future changes. No hate on u/Ramza13, I understand the desire to add cool new things for the sake of emergent gameplay, but in it's current state a toggle is sorely needed. I know that there's some kind of rework ongoing at the moment, the issue is that (arguably) it never should have gotten to this point in the first place.

**Comment by CoroNaut** [comment]
I like this idea of having experimental game play elements as options in stable. Perhaps have them disabled by default. Then, if they get more invested, they can turn them on to see what's in the pipeline for features to come. Not only that, but pre-release phases could be quicker to complete. Instead of removing unfinished features and patching or doing a mad dash to complete them, toggleable features would be a nice middle ground.

I also have a tangent to this. Game balance is a bit wacky and seems to be a point of contention right now. The player having the ability to modify and tailor their experience to how they like seems to be the direction the game is going. I'm sure we could focus more on the player experience, thus your suggestion of allowing or disallowing features. Players can create their own balance with features like portal storms. Of course, it is a high-risk, high-reward scenario that maintains balance, whether on or off.

**Comment by ZhilkinSerg** [comment]
Nor feasible, nor desirable.

**Comment by physics-enthusiast** [comment]
> Nor feasible, nor desirable.

Care to elaborate?

**Comment by RenechCDDA** [comment]
Your suggestions are completely misunderstanding how any of this works.

PRs are merged when they are in an acceptable state.

Stables are released when they are in an acceptable state.

If there are issues with a specific PR or a specific thing that should block stable, **please bring them up**. Don't ask for everyone to do 10x more work for no reason.

You can comment on specific PRs the same way you commented here.

If you want to suggest a blocker for the upcoming 0.H stable (the tracker is at https://github.com/orgs/CleverRaven/projects/14/ ) then comment in the related issue, post it in the official discord's channel dedicated to such suggestions, or post about it on the official discourse forum.

**Comment by ZhilkinSerg** [comment]
> > Nor feasible, nor desirable.
> 
> Care to elaborate?

The thing you are asking for cannot be implemented and we do not want it to be implemented.

**Comment by Maleclypse** [comment]
Toggles allow players to break their games in ways that the player cannot solve.  For example in stable there are in repo mod functions tied to the eoc that controls when portal storms occur. If the player could toggle off portals that would require duplicate code from the mod creator as they couldn’t use what already exists. This duplication could result in slowing processing down for everyone. You can still break that by grabbing third party mods that remove portal storms from firing but that’s the peril of third party mods. 
the idea of when something is ready for prime time is elusive and often requires more time than originally anticipated. Your example item was in acceptable state for stable and only through massive amounts of playtime was a decision made that “huh, there’s a better way to implement this”.  If you’re suggestion had existed we’d likely still be working on a global portal storm model instead of localized portal storms.
