### ISSUE TITLE
Force generation of all major quest locations on character creation rather than on quest trigger, pending the full map rework

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#70313]
### Is your feature request related to a problem? Please describe.

I get really frustrated when I get hours into a run and a quest location fails to generate because there's already too much worldgen out there.

### Solution you would like.

At the moment the character is created, spawn all major quest locations. If worldgen is going to fail to generate them all, retry until a successful setup is found, and only then put the character into the world. These are the keystone locations; having them be further away because the player traveled a bunch in the "wrong" direction is better than them not existing at all.

### Describe alternatives you have considered.

Waiting for a more complete map rework.

**Comment by Procyonae** [comment]
With there being priorities for special placement now there's no need for things to "fail to generate because there's already too much worldgen out there", they fail bc the way placement attempts work are dumb and the number of attempts is tied to the max that can spawn in a 180x180 OM, which in the case of UNIQUE and GLOBALLY_UNIQUE specials (which pretty much all major quest locales in question should be) there's currently either 0 or 1 attempt per 180x180. The way to fix this is to separate occurrences into attempts and actual number of placements based on those that succeeded, or better still in the long run for the placement to just take into account more restrictions that prevent placement such as the preexisting terrain parts of the special can be placed on (field, forest etc), necessary connections (making sure if it wants a road to the south there's space for that) etc (I don't know what it does rn but from a considerable amount of map testing it doesn't work well, several unique or big maps are set to always attempt placement and yet are still very rare.
Currently I have this open PR #69765 where I'm trying to expand the priority usage but the tests are failing to place things given low priority despite the fact that if you run the game a human could easily find loads of places per 180x180 OM to fit the map post gen while abiding to the restrictions the map has, the placement attempts are just incredibly basic. With the motels for example I could get around this by bumping up the occurrences of each motel from [ 0, 2 ]/[ 1, 2 ] to say [ 3, 4 ] but then when the placements get lucky a ridiculous number of motels could spawn on one 180x180 OM (Having some way to make groups of specials with shared occurrences would also be great to reduce the total range in this type of situation and also allow variations on UNIQUE and GLOBALLY_UNIQUE specials)

**Comment by Procyonae** [comment]
I also don't get what you mean by "having them be further away because the player traveled a bunch in the "wrong" direction is better than them not existing at all.", if the maps fail to gen going in any direction will still try to spawn them. The issue I think you mean is it can succeed in placing the map but you don't explore the full 180x180 OM and say continue exploring in a set direction and never find it. This issue is solved by more breadcrumb trails to revealing "keystone" maps and nothing to do with them not spawning. (I want to add some random roadside NPCs to this affect at some point when I get around to it)
