### ISSUE TITLE
Add a option to modify period of merchant getting new item in their stock

### ISSUE THREAD

**Issue by martinrhan** [CleverRaven/Cataclysm-DDA#70334]
### Is your feature request related to a problem? Please describe.

Currently, to its just too long time for merchants to get new items. I don't want to wait for 5 days.

### Solution you would like.

Add an option in world settings, that can modify the length of time period.

**Comment by Maleclypse** [comment]
Wouldn’t be a world option but someone could potentially add jsonized refresh times on merchants and then creators and modders could impact refresh times.

**Comment by CoroNaut** [comment]
What do you mean by "Wouldn't be a world option"? It could easily be a multiplier for refresh times rather than a flat slider for the time between refreshes. When set to 1x for example, all jsonized refresh times would be accurate, if the player sets it to 0.5x, then it could halve those jsonized refresh times. This allows for a player editable option, and increased modder impact on those times for specific merchants.

**Comment by andrei8l** [comment]
`restock_interval` already exists
https://github.com/CleverRaven/Cataclysm-DDA/blob/a4a6785e6348327b73c5be35aa6fdb37c1bfbe92/doc/NPCs.md?plain=1#L81

**Comment by physics-enthusiast** [comment]
> `restock_interval` already exists
I assume @martinrhan meant a player-adjustable slider or setting (as opposed to modder/dev-adjustable json option) similar to the monster evolution rate multiplier?

**Comment by RenechCDDA** [comment]
No reason for this to be player-accessible.

**Comment by CoroNaut** [comment]
Sure, the individual times for specific merchants restocking probably shouldn't be accessible, but a multiplier slider as well? In the new geography changes, where points of interest are going to be much further apart, we could increase the default restock times to match the new world size. Then having an option in world settings for restocking would be even better.

In the new geography changes, we could assume the average distance between settlements to be something around 65km. If someone drove this at 20 km/h, it would take 3 hours. Average walking speed is about 4.5–4.8 km/h, which results in about 14 hours. Note that these are the times in the new changes where points of interest are spread out _much further_ than they are now. I can't find any specific information on how spaced out they are currently, but points of interest are _much_ closer. Taking 5 days to restock if the settlements are even 20km apart is quite a lot. Issue #70285 talks about interaction between camps; this could determine their tech level in relation to each other. Two settlements with lots of supplies could probably travel faster. A multiplier slider would be equivalent to how these traders are traveling, by foot, bike, motorcycle, or car. 

Having this be player accessible seems reasonable, since it is in line with the other multiplier options for difficulty.
