### ISSUE TITLE
Players can no longer "fit" into wheelchairs and drive them

### ISSUE THREAD

**Issue by 7erracotta** [CleverRaven/Cataclysm-DDA#70369]
### Describe the bug

You can no longer sit in and drive a wheelchair

### Attach save file

N/A

### Steps to reproduce

1: Select a profession that starts your character with a wheelchair.
2: Try to ride the wheelchair

### Expected behavior

I expected my character to fit into the wheelchair.

### Versions and configuration

Latest Experimental. 2023-12-22-0719

**Comment by Icantthinkofanameforthis** [comment]
This ones sort of a yes and no. 
Lets start off with ya you cant move onto the wheelchair to be able to drive it.
You can however fold the wheelchair then unfold it so its on your position then you can press ^ to start driving it around.

Further note for people checking this i used the para-amputee (no legs) profession to check this since the quadruple amputee (no arms or legs) lets go of the controls when they try drive it since they have no arms and thus no ability to push the hand rims.

Would like to also mention being on the wheelchair now gives a cramped space debuff.

**Comment by fairyarmadillo** [comment]
My mistake. Thank you for catching this, I'll submit a PR to fix it in the morning.
