### ISSUE TITLE
Remove Mutagenic Catalyst

### ISSUE THREAD

**Issue by fairyarmadillo** [CleverRaven/Cataclysm-DDA#70398]
### Is your feature request related to a problem? Please describe.

I (sort of) understand why we split primer and catalyst as vitamins, but after watching people be constantly confused by our present system over on reddit and elsewhere, I have a question - why is catalyst its own item? All I can guess is that it's a legacy from back when mutagen used to work differently, but untyped mutagen was practically useless even back then. Now it's actively detrimental to the play experience and there is no reliable way for us to communicate this to the player that doesn't totally break immersion by feeding them information their character would have no way of knowing. Even worse, we've done exactly that, and it clearly isn't working.

So we're spending a lot to have catalyst, but unless I'm mistaken, we aren't really getting anything for it.

### Solution you would like.

Unless there's some reason I'm not understanding why it absolutely has to be this way, why don't we just rename primer to something like infusion (a common term for injectable drugs) and put a bunch of catalyst vitamins in it, then obsolete the catalyst itself, or perhaps make it some optional thing that could be crafted if there's still some edge case use for it? It would be pretty easy to implement and would lead to a lot less confusion for players.

There are a ton of other problems with the current implementation, but this stands out as a big one to me.

edit: Per the comments, it sounds like the way to go is to do away with catalyst as a vitamin and combine its function with primer. This will be slightly trickier than simply obsoleting the item, but doesn't sound terribly complicated.

### Describe alternatives you have considered.

I would just do this myself but I wanted to ask whether there was a good reason not to first.

### Additional context

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/94415528/56639d31-617b-442c-99d6-e042477d3a82)

This was just a cursory search, but I see questions like this popping up once a week, and the sense I get is that a lot of people don't even want to engage with the system because it's obscure and confusing in an out-of-character way. I don't consider this ideal.

**Comment by CoroNaut** [comment]
Untyped mutagen is only good with the robust genetics trait. 

As far as I know, the help section on "radioactivity and mutations" hasn't been updated significantly in years similar to the now dead wiki. Not to mention the rest of the help categories. At the very least, it could be explained there. If even that help system has been forsaken, then perhaps an in-game readable book or computer entries like how the smart vehicle controller manual works. There are quite a few systems that are introduced but not really explained.

**Comment by actually-a-cat** [comment]
I agree that it's confusing, but if you want to delete catalyst, you should also get rid of the `mutagen` vitamin altogether and rework mutation mechanics to only work off primer. There is no fixed ratio of primer to mutagen that will be effective for any character, it depends too much on preexisting and available mutations and random rolls, so whatever you put in will eventually cause unmanageable imbalances under some circumstances. Right now a skilled player can correct them by managing their intake of mutagen/primer/catalyst, if it's all in one item they can't and will be stuck either waiting it out or using a chelator to start from scratch.

There is one feature that would be lost: using primer without catalyst for its passive stat boosts rather than mutation.

**Comment by fairyarmadillo** [comment]
> I agree that it's confusing, but if you want to delete catalyst, you should also get rid of the `mutagen` vitamin altogether and rework mutation mechanics to only work off primer. There is no fixed ratio of primer to mutagen that will be effective for any character, it depends too much on preexisting and available mutations and random rolls, so whatever you put in will eventually cause unmanageable imbalances under some circumstances. Right now a skilled player can correct them by managing their intake of mutagen/primer/catalyst, if it's all in one item they can't and will be stuck either waiting it out or using a chelator to start from scratch.

Can do.

> There is one feature that would be lost: using primer without catalyst for its passive stat boosts rather than mutation.

That's a good thing IMO. I don't really think people should be using mutagen to get temporary passive stat boosts, especially risk-free like this. They should be using it to turn into Cronenberg monsters. Mutagen is concentrated blob matter with foreign animal DNA in it, you shouldn't be putting that into your body without dramatic and permanent consequences.

**Comment by fairyarmadillo** [comment]
>It would be nice to have something to explain the system if we remove mutagenic catalyst or not.

I will update it when I put this together, assuming there are no strong objections from the dev team.

**Comment by actually-a-cat** [comment]
> If we really want to have temporary stat boosting drugs, and I'm not sure that we do, we can probably have them come from a source that isn't such an obviously bad idea. 

Oh, this reminds me - the reason why serums were renamed to primers was because of a plan to use the name for a new class of items - #53141

**Comment by fairyarmadillo** [comment]
Oh yeah I forgot about that. I still think primer is a bad name, as it doesn't describe the function of the item at all, but if I think of a better one I can propose that.

Those proposed serums also sound like they'll provide the temporary stat buffs you mentioned, so we probably don't have to worry about players losing access to doing that via primer without mutating.

**Comment by Maleclypse** [comment]
Does untyped mutagen mutate you randomly if you take it without primer?  If not I think that's a fair fix.  I understand it wouldn't likely be a good thing for the PC in most cases but it's at least something that makes sense to long term players.

**Comment by fairyarmadillo** [comment]
> Does untyped mutagen mutate you randomly if you take it without primer? If not I think that's a fair fix. I understand it wouldn't likely be a good thing for the PC in most cases but it's at least something that makes sense to long term players.

Catalyst doesn't, regular mutagen does. If we get rid of catalyst as a vitamin, then catalyst as an item could be changed to be a higher-dose version of random mutagen.

Implementing that without removing catalyst as a vitamin would only make the present situation worse without addressing any of the issues. New players would be even more confused, primer would still be a risk-free buff, primer being on a separate decay timer would still cause gigantic bottlenecks incentivizing the player to stand in a field and do nothing ( similar to #66768 ).

**Comment by KeremBabaG** [comment]
I think we should communicate how it works better to the player instead of outright removing it

**Comment by fairyarmadillo** [comment]
> I think we should communicate how it works better to the player instead of outright removing it

We already perfectly communicate all information and it doesn't work. People have been confused for two years. Additionally, CoroNaut has outlined several issues with its implementation that I feel are best addressed by removing it.

To be clear: Removing Catalyst isn't going to remove any content from the game. You will still go to labs, dissect monsters for samples, do complex chemistry to cook up the recipes, and drink or inject the chemicals to begin your transformaton. It will just streamline a process which is currently needlessly complicated. Instead of having to take primer and catalyst, you will just have to take primer.

**Comment by Procyonae** [comment]
I'd still be down for a full reversion of how mutagen works personally but at least this would make the system less confusing for new and returning players alike.

**Comment by Vaskritaya** [comment]
I'm neutral regarding this change, but I do feel it's worth mentioning this could have balance impacts. Crafting probably isnt too big of a deal, I'd have to assume you can pretty easily just throw mutagen materials into the primer recipes or whatever. The bigger impact would be to labs, since any mutagen stuff you find would be guaranteed to work out-of-the-box, without needing other resources to make it work. 

No idea if this would actually have a meaningful impact, no idea if it would be a good or bad balance change. Just felt worth mentioning since I hadn't seen it brought up.

**Comment by Terrorforge** [comment]
While we're at it, I don't really see the point of having "[Type] Mutagen" and "[Type] Primer" as separate items, either. Crafting primer is a trap option right now because it just uses wastes samples, but even if it wasn't it just adds another step to the process for no particular reason. I think we can get rid of primers altogether and go back to just having various flavors of "mutagen", just with the new time-delayed mechanics.

> I still think primer is a bad name, as it doesn't describe the function of the item at all

It sets you up, "primes" you, for mutation. Then you have to use a catalyst to "catalyze" the reaction and actually start mutating. It's still a bad name because nobody intuits that that's what it means, but it is technically an accurate description of how it's meant to work.

> No idea if this would actually have a meaningful impact, no idea if it would be a good or bad balance change. Just felt worth mentioning since I hadn't seen it brought up.

I think this would be a positive change, because mutagen loot is super disappointing at the moment. There's not that much upside to lucking into a bunch of primers because catalysts are quite rare, so you still need to track down all the tools and recipes and grind up the skills to make mutagen from scratch anyway.

**Comment by kevingranade** [comment]
In short we're keeping the catalyst/primer split.
