### ISSUE TITLE
Damage message and health display not registering damage

### ISSUE THREAD

**Issue by Dunkhan** [CleverRaven/Cataclysm-DDA#7041]
I am particularly upset about this one I play one monster spawnx10 and itemsx0.5, with delete world on. So dying from bugs is not appreciated.

I am not sure how reproducable this is, and I stupidly forgot to screenshot.

What happened:
While exploring a lab I ran into a turret, it shot me. The damage message said "The shot reflects off the thin skin". My health bars did not change. I walked up and smashed the turret with an axe. It shot me many times. Every time the same message and the health bars did not change. I thought this was strange but thought maybe my armour was simply tougher than I thought. I was wearing a kevlar vest, leather body armour, hard arm and leg guards, and a survivor helmet. Everything reinforced.

I went further, discovering two more turrets, each time with the same damage message on hit and no change to health bars. Whilst approaching the third turret I dropped dead. On the death screen all my health bars were still full.

This is all the information I can give, I hope someone can track this down. I will attempt to reproduce it myself as well.

**Comment by mugling** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
