### ISSUE TITLE
The evac shelter terminal could be replaced by a bulletin board with evac info on it.

### ISSUE THREAD

**Issue by gettingusedto** [CleverRaven/Cataclysm-DDA#70441]
### Is your feature request related to a problem? Please describe.

I was thinking about the evac shelter terminal the other day, and i realized that a bulletin board with the same info from the terminal could done the same task evac terminal do. 

It feels rather excessive to use a computer terminal for it when a bulletin board with a bunch of the same info can do the task as well, unless im missing another function the terminal might be implied to have.

### Solution you would like.

Replace the computer terminal with bulletin board or similar implements.

### Describe alternatives you have considered.

Not doing so.

**Comment by db48x** [comment]
Don't forget that the terminal is also a light source.

**Comment by Qrox** [comment]
From a lore perspective, the terminals could have had other purposes such as communication, registration, and whatnot, but lost those functionalities after the network was down (which does raise the question of where the terminal power comes from after the power grid is down). Still, a bulletin board (or some pamphlets) sounds like something an evac shelter would have in case the terminal is also broken.

**Comment by db48x** [comment]
Atomic battery in the foundation.

**Comment by PatrikLundell** [comment]
There is no atomic battery, and given how the government in this world bungles every procurement and cuts corners that shouldn't be cut (not saying it's too different from the real world), there is no way they'd actually spend money on sophisticated emergency power solutions that surely never will be used.

There is a solar panel on the roof, but, again, it would cost money to make a setup that automatically switched over autonomous mode when connection to the external power grid was lost.

If someone implements a switch they ought to first check what happens when the player turns it into a bare bones base camp. I don't know if the bb info gets lost or not.

**Comment by db48x** [comment]
> There is a solar panel on the roof, but, again, it would cost money to make a setup that automatically switched over autonomous mode when connection to the external power grid was lost.

Actually, that would be a COTS solution right there, while an RTG would not be. Granted it would cost slightly more. Someone should add a storage battery to the building somewhere.

**Comment by CoroNaut** [comment]
I definitely agree that there wouldn't be an atomic battery on site, but a solar panel and battery just for a computer and the antenna sounds right. I wouldn't doubt it if the "light source" from the computer was intentional from the day it was introduced. Light is very valuable for early game. I would hardly see a bulletin board being updated on a regular basis, which makes the computer even more reasonable. From a very quick search on automatic power switches, I think it would be reasonable to assume that shelters had one. If we are sure that the government was 100% set on only warfare, advancement, etc, then sure, no power switch. That would be interesting to put into lore, the fact that no official deemed it necessary to maintain evac shelters or build new ones.
