### ISSUE TITLE
Recipe difficulty needs rebalanced

### ISSUE THREAD

**Issue by nonymous** [CleverRaven/Cataclysm-DDA#7045]
From discussion on the forum, there is some agreement that some recipes are out of balance.  Linking skill to difficulty means that without rebalancing some recipes, higher levels are unattainable without reading, as intended, but some of those (e.g. Dog Food) are probably not intended to be impossible to self intuit.

I took a look into the recipes.json, and the first thing that strikes me, since it's near the top, is that disassembly is always diff 0.  This means one can't expect to reach level 2 through disassembly.   Usually this would be expected, but should we be able to reach higher levels by deconstructing more complex gear?  

I'm told there's destructive disassembly.  Here's a scenario for what I think is a balanced approach where we make diff of diassemble laptop 4:

Survivor has electronics 0
disassembles laptop (diff 4)
gains skill
recovers at best electronics scrap and plastic chunks (because he sucks @ elec)

another:

Survivor has electronics 4
disassembles laptop (diff 4)
gains skill
likely to recover all parts available

another:

Survivor has electronics 5
disassembles laptop (diff 4)
gains no skill (been there, done that)
very likely to recover all parts available

Thoughts?

(edit: grammar, spelling)
##

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
