### ISSUE TITLE
NPC companion seems to prefer going through player instead of going around

### ISSUE THREAD

**Issue by gettingusedto** [CleverRaven/Cataclysm-DDA#70510]
### Describe the bug

When me and my companion clearing up a mass grave full of zeds with knife spears, i noticed that my companion just complains at me to "get out from their way" despite we're in a spacious field and can just go around me. To clarify what npc setting is used, it's mostly what the default setting is now, except i turned off the "pulp corpses" option off.

### Attach save file

N/A

### Steps to reproduce

1. Get a npc companion and give them a melee weapon.
2. Get to a field and spawn in a bunch of zeds
3. Fight said zeds alongside the npc
4. See that they sometimes complains about you being on their way in some occasion.

### Expected behavior

Them going around me instead of trying to go through me. It's not like the field and road that confined of a place.

### Screenshots

Some of the log from the mass grave fight.
![Screenshot_2023-12-30_01-28-26_1](https://github.com/CleverRaven/Cataclysm-DDA/assets/78019001/e98fe505-8849-4c80-8677-3acf943dbd38)

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: samsung; Model: SM-A710F; Release: 7.0; Incremental: A710FXXU2CRC2; 
- Game Version: 394f235 [32-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    GUT's Contents Compendium [gut_contents_compendium],
    GUT's Unhinged Stuff [gut_unhinged_stuff],
    GUT's Tweak Compendium [gut_tweaks_compendium],
    Bombastic Perks [bombastic_perks]
]

### Additional context

Maybe it could be them complaining about me being in their spear line of attack, but it's hard to tell.

**Comment by PatrikLundell** [comment]
It's a long standing issue. companions complain incessantly about you or each other being in their way. Presumably their path finding is based on terrain alone, and so can't deal with creatures in their way (obviously they can decide on a location to path to based on the location of a target (location or creature), but the usage of said path seems to lack any ability to be adjusted based on creatures blocking the path).

This issue is "worked around" for many ordered tasks by simply dropping the task (set multiple companions to unload a vehicle, and you'll typically find some of them claiming to be "done" because others are standing in tiles they wanted to path to or through, even when there are available nearby tiles that can access the same storage tiles).

**Comment by fairyarmadillo** [comment]
Why don't we just check if there's a character in the tile in could_move_to()?

**Comment by Procyonae** [comment]
Relevant piece of code (I have no idea what it does just stumbled on it while doing something else) https://github.com/CleverRaven/Cataclysm-DDA/blob/5a22c1ca9c160bb36ebe4c83b212f644f09fd910/src/pathfinding.cpp#L225-L232

**Comment by fairyarmadillo** [comment]
Despite what the comment says, I can't see any code in that entire file which would cause NPCs to not want to path through the player.
