### ISSUE TITLE
[Innawood] Steel recipes using Hematite overrides Mining Mod version, Black Sand is Useless

### ISSUE THREAD

**Issue by Kantonine** [CleverRaven/Cataclysm-DDA#70610]
### Is your feature request related to a problem? Please describe.

The Innawood Crafting recipe to make Steel from Hematite overrides the Mining Mod Recipe, leaving black sand without a use

### Solution you would like.

Add a way to use Black Sand from mining mod back in? maybe some form of mod interaction?

### Additional context

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/91917075/33e541bd-be9a-4fd1-a2b9-f2473bdc6670)

**Comment by PatrikLundell** [comment]
The default naming for recipes is the name of the product, and there can only be one of those in the game. However, it's possible to create multiple recipes that yield the same product if the additional recipes have extensions.

Vanilla cases of this is the set of recipes to process various kinds of grain without tools and with tools (with the latter taking less time). A fairly old case is the companion only drop hammer set of recipes.

My recommendation (which carries no official weight whatsoever) would be for the mining mod to make the effort to be mod combination friendly by making most or all of the recipes that aren't intended to override vanilla ones using extensions.
However, it wouldn't go amiss if the Innawood mod did the same for any recipe that's intended to play nice with vanilla recipes that may appear in the future. Note that some recipes are intended to replace vanilla ones, and thus would have to have the same name, while some may make sense in vanilla but aren't present currently, in which case I might argue for the addition of an extension so that when/if a vanilla recipe appears, you'd end up with two recipes and hopefully questions as to why there are two, prompting the removal of the redundant (and possibly slightly different) recipe, or the overriding of the new vanilla recipe when a replacement is warranted.

Again, those are just my thoughts.

**Comment by Karol1223** [comment]
Isn't Mining Mod a third party mod? If so, that's not really that concerning and is 100% something the third party mod dev should take care of

**Comment by Kantonine** [comment]
> Isn't Mining Mod a third party mod? I can't find it in the files. If so, that's not really that concerning and is 100% something the third party mod dev should take care of

id also like to say however is that plenty of the items from mining mod got proper integration into Innawood afaik, the recipes for them included for the most part, with only some minor changes, like the copper production recipe giving platinum, while the mining mod version doesn't. so to say its an issue with mining mod is odd in my honest opinion.

**Comment by Karol1223** [comment]
If Innawood integrates most aspects of Mining Mod, there shouldn't be a need to use both. In such case, Innawood (being the official and supported mod) overriding a third party mod isn't a concern with Innawood, is it? Its an issue with Mining Mod, which isn't mainline.

**Comment by Kantonine** [comment]
sure, but it doesn't help that the recipes for hematite smelting got carried _straight_ from Mining Mod!

data/mods/innawood/mining/recipes/smelting.json (Innawood)

Mining_Mod/recipes.json (Mining Mod)

"Hematite has around 70% yield of iron, total yield here is just over 69% at 3500 grams of steel.  Estimated 2% carbon content has minimal effect on these numbers.  Magnetite has around 80% yield, but ironsand isn't pure magnetite."

it seems that Black Sand/Ironsand/Magnetite Sand should be in when its mentioned like this
