### ISSUE TITLE
Vehicle-mounted water purifier limited in charges

### ISSUE THREAD

**Issue by SeanMirrsen** [CleverRaven/Cataclysm-DDA#7075]
As reported here: http://smf.cataclysmdda.com/index.php?topic=6061.0

The vehicle-mounted water purifier (inside a FOODCO kitchen buddy) doesn't have the entire battery capacity of the vehicle at its disposal - instead it just draws 100 charges, and then deposits the leftovers back into the battery(ies). The problem is that the large metal tank, for instance, holds more than 100 units of water, so you can't purify the water in the tank even though you may have more than enough available power to do so.

From game.cpp, game::pickup

```
    if(menu_items[choice]==_("Use the water purifier?"))
    {
        //Will be -1 if no battery at all
        item tmp_purifier( itypes["water_purifier"], 0 );
        // Drain a ton of power
        tmp_purifier.charges = veh->drain( "battery", 100 );
        if( tmp_purifier.is_tool() ) {
            it_tool * tmptool = dynamic_cast<it_tool*>((&tmp_purifier)->type);
            if ( tmp_purifier.charges >= tmptool->charges_per_use ) {
                tmptool->use.call( &u, &tmp_purifier, false );
                tmp_purifier.charges -= tmptool->charges_per_use;
                veh->refill( "battery", tmp_purifier.charges );
            }
        }
        return;
    }
```

Wouldn't it be better if the `tmp_purifier` got ALL the battery charges from the vehicle, since it then deposits the charges back anyway?
##

**Comment by Xpyder** [comment]
For the Foodbuddy purifier I think a better solution would be to have it store dirty water and then over some period of time purify that and deposit it into the vehicle's water tank.  Since it has a 400 cargo capacity, Is there any way to have it consume water charges from containers you store in it?  If not then maybe add a tank to it's construction and let purify from that.

Long term I'm hoping we get unified liquids tanks that we can store different types of liquids in.  If so you could have it automatically move dirty water to clean water tanks as it purifies.

**Comment by eliotcougar** [comment]
Problem 1: Purification of water in the vehicle tank is instant no matter how much water is there (purifying water from inventory takes time)
Problem 2: It uses too little battery
Since we actually got unified liquids tanks...
I support @Xpyder solution: It should require both dirty water and clean water tanks... It should work continuously like a minifridge, drain battery (quite a lot) and slowly transfer water from one tank to another... If there's no free space in the clean water tank it will overflow and spill clean water on the ground... It should probably require some work, tools and time in order to change which tanks are used as a source and sink (i.e. manually reconnecting water tubes)
Disabling the ability to purify water in vehicle tanks using FOODCO Kitchen Buddy is also realistic... Right now it's quite overpowered...

**Comment by Xpyder** [comment]
To be clear, I don't think the water purifier should overflow and spill, and I do think you should be able to flip it on and off.

But working over time, and pushing water between tanks internally seems to make the most sense to me.  Perhaps, if the new tank system supports it, the water purifier could be something that's attached to a particular tank, like a funnel.

@mugling

**Comment by Leland** [comment]
Tanks and purifiers were overhauled quite a bit. Can anyone verify that this is still an issue?

**Comment by eliotcougar** [comment]
@Leland I'm not sure if the original issue in the first post is present (it's hard to spawn 60L tanks full of water in debug menu and install them), but I still have the issue with purification being instant and taking too little power (??? charge/L), compared to boiling water in the cooking menu (12 charges/L)...
Another issue I think is quite annoying is that water purifier doesn't transfer clean water to another tank... If you have a 60L tank with a funnel on top, and you purify it, it will not collect water again until it's empty... And there is no easy way of transferring liquids between two vehicle tanks, only between the tank and a carried container and back...

**Comment by Xpyder** [comment]
With the new changes to multi-liquid tanks and the way funnels work, I'd suggest changes to the vehicle mounted water purifier as follows:

 - Must be installed onto a tank, like a funnel
 - Turned on/off from the controls like a recharger or fridge
 - If water is available in the vehicle, purifies the water over time until it's matched tank is full, consuming both power and dirty water

Does this approach seem reasonable?

**Comment by Xpyder** [comment]
It's outside the scope of this issue, but a possible approach for the portable water purifiers might be when you activate them you choose a container and then a tile, and have them set up a tile (similar to the funnel) and work over time until finished (like a kiln).

The kitchen buddy version of this would just take the water container and hold onto it until it was finished

**Comment by kevingranade** [comment]
If #21095 is working as described, this is addressed.

**Comment by Mooses2k** [comment]
This appears to be fixed. Using a FOODCo allows purifying an entire 60L tank at once.

**Comment by Night-Pryanik** [comment]
Ok, closing then. If this still an issue, feel free to ping me.
