### ISSUE TITLE
Scrapper NPC quest asks for "soldering wire", but it's not called that anymore.

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#70817]
### Describe the bug

The NPC text and quest description asks for "soldering wire", but the item he wants is called "solder." No particular issue with the NPC's text being a bit more vague, but the quest description should ask for the item by its exact name.

### Attach save file

N/A

### Steps to reproduce

Check the quest text/description

### Expected behavior

The quest description should ask for the item by its exact name.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: 2a67568 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Translate Complex Dialogue [translate_dialogue],
    Alternative Map Key [alt_map_key],
    Bombastic Perks [bombastic_perks],
    Extra Mutated Scenarios [extra_mut_scens]
]

**Comment by NthTech** [comment]
Can confirm. Started a new game with no mods besides the default rebalancing mods, namely Disable NPC Needs, Portal Storms Ignore NPCs, and Slowdown Fungal Growth. 

Debug mode spawned the scrapyard and cycled scrapper quests until receiving the solder one. Here are the parts that refer to soldering wire rather than just solder.
![Screenshot 2024-01-10 131620](https://github.com/CleverRaven/Cataclysm-DDA/assets/2877787/d9afc611-c7c7-4d34-9aee-c9518670486b)
![Screenshot 2024-01-10 131652](https://github.com/CleverRaven/Cataclysm-DDA/assets/2877787/4627afa8-3bf1-432e-af11-a87dd71f1fbc)

**Comment by ANickelN** [comment]
/confirmed
The wording could probably be changed to accurately reflect what he wants you to get.
