### ISSUE TITLE
Refugee center NPC after being recruited  cant follow player 

### ISSUE THREAD

**Issue by ynemo** [CleverRaven/Cataclysm-DDA#70867]
### Describe the bug

Romelia Hunter, Merc, could join player for 750 merch.
But Romelia is standing in closed room, so she cant follow player after beeing recruted. 

### Attach save file

[Leonard-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13922916/Leonard-trimmed.tar.gz)

### Steps to reproduce

Talck with Romelia Hunter, she is standing in refugee ceter doctors room.
Ask here to join for 750 merch.
She is stuck in closed room. 

### Expected behavior

Probably she must stand in main hall. 

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/24881844/7adb51d8-2ccf-432d-bbd6-b117ffdfc83d)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.2715 (22H2)
- Game Version: 2a67568 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by Icantthinkofanameforthis** [comment]
Thing you just got a bad spawn like theyre suppose to be in the room next to the doctor

also for easier testing use scenario Safe Place with starting location Refugee center

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/70473120/17565366-d0f5-4143-a463-37c1e0ee6944)

**Comment by ynemo** [comment]
btw it happens to me second time. Both times refugee center was N oriented

**Comment by EIIKaO** [comment]
The bug seems to have occurred because the mercenaries were incorrectly set to spawn point at inside the wall.
https://github.com/CleverRaven/Cataclysm-DDA/blob/b3a8e973ef563f3a8fd31ae0eed06640444d8aab/data/json/mapgen/refugee_center/refugee_center.json#L314-L319

Mercenaries always spawn inside the walls of the refuge center( "x": 49, "y": 3 ) in any direction, but in that case they will be taken out of the walls. I am not sure how this direction of pushed is handled ( when facing south, they are put out at the bottom left, as you can see below pic, and when facing east, they are put out at the bottom right, and south, they are put out at the top left, but in these case, they are next room of the doctor's small room, can be escorted out ), but when facing north, they are put out directly below, so they are relegated to the doctor's small room.
![20240115a](https://github.com/CleverRaven/Cataclysm-DDA/assets/109350502/feddedb5-1287-45ef-ac8d-d61cae0b36cc)

That is, changing from "x": 49, "y": 3 to "x": 48, "y": 5 would always spawn on the chair in the next room ( in any direction ), as suggested above comment.
