### ISSUE TITLE
Choose destination for autopickup

### ISSUE THREAD

**Issue by Nandorianen** [CleverRaven/Cataclysm-DDA#7094]
Example 1. I am looting a store with a wheelbarrow or a shopping cart. I can use AIM to pick stuff up and put it into the shopping cart, but I still have to do it manually.
Example 2. I have loads of heavy stuff (logs, machine parts) that are so heavy I can't carry it normally, I have to move it from one tile to another via AIM.

If I could open AIM and set one of the currently opened panes as a destination for the autopickup, it will mean much less repetitive tedious manual work. Especially if autopickup also works on adjacent tiles, as suggested in another topic. Imagine: you just walk from the forest to your soon-to-be-built home and all the logs are automatically rolling with you.
##

**Comment by DavidKeaton** [comment]
auto-pickup will get an overhaul from my nested containers PR, just for the books. :-)

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
