### ISSUE TITLE
Advanced Inventory Management limitations - access to tiles under vehicles

### ISSUE THREAD

**Issue by Nandorianen** [CleverRaven/Cataclysm-DDA#7097]
Items can happen to lie inside and outside vehicle on the same tile. With AIM you can only access the ones inside. You can pick those outside by 'e'xamining them.

AIM needs a switch to access both.

**Comment by Ygdrad** [comment]
This is still an issue. For example, I was displacing an inconveniently large pile of crafting materials into my new mobile base and since the square with the door only holds 150 volume the rest of the pile of items decided it would phase through the floor and end up under the vehicle leaving me with no choice but to try to move the whole of my materials stockpile through the (e)xamine menu.

Instead of having items magically fall through the floor, where they can no longer be accessed through AIM, could they not be counted as still in the vehicle but unsecured, making them drop out/under if the vehicle was moved?
