### ISSUE TITLE
Options for AIM behavior - selecting same tile

### ISSUE THREAD

**Issue by Nandorianen** [CleverRaven/Cataclysm-DDA#7098]
When AIM generated message "same tile" if I tried to select the same tile, it was very annoying. Now, when AIM switches panes, it is less annoying, but still confusing. Would be nice if there were an option to change this to do absolutely nothing. I like to keep inventory pane on the right at all times, but can never remember which tile is selected on the left, so I just hit required direction, which very often happens to be the same that was already selected, which switches panes.
##

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
