### ISSUE TITLE
[MoM] Not learning new teleporter spells even though requirements are met.

### ISSUE THREAD

**Issue by Fox-Ball** [CleverRaven/Cataclysm-DDA#71023]
### Describe the bug

So I meet the requirements for both transpose and spacial vortex yet have not got notification or practice spell to contemplate them. I technically now meet the requirement for gateway as well but I am going to give it time to see if that one functions correctly. I am on day 74 starting and left it on the default day of 61 picking the 

### Attach save file

[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/13967261/save.zip)

### Steps to reproduce

I'm not sure how to reproduce I'm not even sure what caused it.

### Expected behavior

Learn the contemplation recipes in the craft menu to obtain the spells.

### Versions and configuration

English
Windows 11 64bit
exp 2024-01-14-0248
Mods: Magiclysm, Mind over Matter, Xedra Evolved, Bombastic Perks, Crazy Cataclysm, Mythical Martial Arts, Disable NPC Needs, Portal Storms, Slowdown Fungal Growth, SpeedyDex, Stats Through Kills, and Tamable Wildlife.

**Comment by Standing-Storm** [comment]
Working as intended: 
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/120433252/a61278e9-5967-4aef-ad5a-0c2be746ffbf)

There's a list of effects that prevent the EoCs from triggering, usually stuff like "being asleep" or "having a broken leg" or "starving" or "being covered in boomer bile", the kind of things that make it very difficulty to have any sort of insight about how to better use your powers. After #70226, I added the unhappiness of eating protein bars to that list, since as that PR says 

> Protein bars now give character a psychological trauma

So, I waited a few in-game days for the protein bar effects to fade, and as soon as that happened:
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/120433252/6dc7738d-0c5c-42a5-944d-f838d4ee8cab)

I'll add some more info into the Readme about needing to be in a good mood, well fed, etc., to trigger learning powers.

**Comment by Fox-Ball** [comment]
Maybe that was it? I was eating the protein bars. Not so much at the beginning. I must not have had my powers at a high enough level to get an insight. I thought I checked the learning eoc and didn't see anything about protein bars, I generally do my best to keep my character in good spirits. Maybe it is the "bad_food_ennui" one. I still have to learn Oubliette and Breach which I don't meet the requirements for atm.

**Comment by Standing-Storm** [comment]
The protein bar effect is called `bad_food_ennui` so maybe that's why you missed it. Try waiting out the protein bar unhappiness and see if that fixes it.
