### ISSUE TITLE
Horizontal scaling for all menus

### ISSUE THREAD

**Issue by Nandorianen** [CleverRaven/Cataclysm-DDA#7103]
I'm playing with 12/24 font and 159x42 terminal width/height on 1920x1080 resolution.

Crafting menu takes full-screen, but it is divided disproportionally: about 20% for list of items, about 30% for recipe details and about 50% for item details. This looks pretty good, although I'd make recipe vs item details about 40%-40%.

However, inventory screen is divided badly: ~25% for item list, ~30% for equipped items, the rest of the menu to the right is empty. And I often have problems with long item names not fitting in (especially packed rotten food).

Advanced Inventory Management screen's proportions are okay, but its borders are about 15% short of the game window's border on each side. So AIM can be widened considerably to better deal with long item names.

Construction screen can afford to expand even more. It currently takes only about half of the window's width and already it has problems with long names in the list.

Armor re-layering screen can do with expanding horizontally and vertically. It currently can't fit more than 3 tag description for any item and can have problems with fitting long names into the lists (especially if the item is damaged).

View bionics list and, probably, some other menus I have little experience with, can and should scale better.
##

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
