### ISSUE TITLE
Reloading Overhaul 

### ISSUE THREAD

**Issue by Holli-Git** [CleverRaven/Cataclysm-DDA#71094]
### Is your feature request related to a problem? Please describe.

Reloading as it currently is requires a separate recipe for each and every ammo type, which can cause a lot of bloat to the crafting menu. It'd also be nice to have some more customization in handloads, such as making -P ammo and failing to cycle or making some proof test cartridges for shits, giggles, and destroying a gun.

### Solution you would like.

On activating a reloading menu (or adding in a reloading bench) you'd be greeted with a menu. You'd select the cartridge, the powder type and charge, and the bullet type. 

Using incorrect powder types such as fast burning propellent in a cartridge not meant to handle the pressure could cause catastrophic gun failure. It could also remove the mixed smokeless powder, as now you can reload with any powder and with the appropriate drawbacks. Also makes black powder and matchhead powder rounds.

For powder loads, one could load some extra spicy rounds for emergency situations, or underload some rounds if they want a quieter gun. Of course both with appropriate drawbacks, such as failure to cycle or gun blow ups.

Bullet type could just be some recipe involving copper/lead/steel, or it could be replaced by crafting recipes for bullets, such as making .44 Magnum JHP bullets before needing to load them into a cartridge.

It could also open the way for differing qualities of handloads, such as a low-skill survivor having very inconsistent powder charges, leading to overpressure or underpressure ammo when they did not intend to, or squib rounds that cause the barrel to be obstructed and the gun made unusable. The inconsistency amounts would be drastically reduced at higher skill levels, but still present.

Issues:
I can see a few issues with this system. Major one being a lot of infrastructure. It'd need to have formulas for bullet velocity from powder amount and type, individual tracking of round attributes, different effects relative to other aspects such as an overloaded hollow point failing to properly expand from being underloaded, just a lot of work to make the system work as a whole. It could also be confusing for players, as new players may not know they even can reload as the recipes for ammo are mostly removed, or older players who are confused on where the recipes all went. 

### Describe alternatives you have considered.

Putting ammo recipes into nested groups.

**Comment by Paprika-H** [comment]
> An overhaul would be cool, but unless somebody steps up to figure out how to code all of it not much will get done. A more feasible way to deal with this would be to just nest ammunition into categories like so:
> 
> Rifle Ammo -> Caliber -> X, Y, Z Pistol Ammo -> Caliber -> X, Y, Z
> 
> Nesting is not too difficult to learn, there is a lot of examples of the more complicated nests at this point to draw information from.

Read the "Describe alternatives you've considered"

**Comment by GuardianDll** [comment]
nesting is bandaid, it doesn't help much
in theory some EoC stuff can be made to handle it, and it won't even be bad

**Comment by XygenSS** [comment]
Problem with this is that the player now kind of has to learn *a lot* of things to reload bullets properly. I can see it being overwhelming especially for people who aren't familiar or don't care about guns in general.

**Comment by IdleSol** [comment]
My most used phrase: I apologize for the quality of the text. Deepl translate is used.

The cartridge consists of
- bullet
- cartridge case
- powder
- primer

Now, let's imagine each cartridge, as a set of pockets in which you can put the corresponding items.

As part of the game. Still need to add a pocket for copper (I don't know why it's used, it's in the recipe) or some additional features (ignition). Or move this to the recipe for the bullet itself, the powder and the cartridge case.

Here's an example: 5.56 NATO tracer, reloaded.
- bullet 5.56 x1
- cartridge case 5.56 x1
- powder (normal or black or mixed or something else) x17
- small rifle primer x1
- copper x1
- incendiary x2

Each pocket has a quantity limit. 
For powder from 1 to 25. There are limits beyond which the cartridge is inoperable: 15 and 20. Less than 15 is a misfire, more than 20 is a cartridge rupture. Bullet damage = base value + (17 - powder value). Or - 2 at 15 and + 3 at 20. 
With special pockets (incendiary), I don't know what to do. I don't know much about firearms.

What we need:
- The ability to roll up the pocket and pretend that the pocket is not a pocket, but a regular item.
- the ability to change the name of the pocket, depending on its contents.
- The ability to unfold the pocket, to disassemble and equip cartridges.

The pocket can be a fake object or a cartridge case.
The casing is probably the best option, as it immediately sets the format for the bullet caliber and powder used.

For the fake item, additional steps are required. So that a pistol casing does not attempt to insert a grenade launcher bullet.

What it should look like. The ammo machine is an activatable item.

1. Activating the machine gives access to the ammo equipping menu.
2. Choice to equip a new cartridge or disassemble a ready-made one (sorting the displayed items).
3. All cartridges appear as pockets. Depending on the selected components, the name of the result is determined. If something is not selected from the basic components or you cannot close or get a blank cartridge.
4. The number of cartridges is selected and the amount of time required for the job is calculated. You can agree and start working or decline and return to the menu
5. Exiting the cartridge equipping menu, stops the cartridge from appearing as a pocket.

With errors of nested pockets and arbitrary destruction of items, to deal with later.
