### ISSUE TITLE
Terrain tiles on different z level no longer drawing.

### ISSUE THREAD

**Issue by amadcow4u2** [CleverRaven/Cataclysm-DDA#71185]
### Describe the bug

Z-level terrain is no longer drawing graphically.  Experimental Z-levels are disabled.

### Attach save file

N/A

### Steps to reproduce

1. Create a new world at evac center with experimental z-levels disabled.
2. Climb to roof.
3. z-0 terrain tiles are 'visible' when moused over, but graphics are not revealed.
4. Peeking down will reveal the tiles, and they will be visible from memory afterwards.

Alternatively, fly around in a helicopter.

### Expected behavior

Terrain tiles graphics should be drawn, expected behavior still works in 2023-12-18-0506.  Experimental Z-levels functioning a bit oddly too, but peeking seems to be working properly.

### Screenshots

Before peeking and after peeking.  ''Below: Grass" is visible in both screenshots.
![beforepeek](https://github.com/CleverRaven/Cataclysm-DDA/assets/42590653/dc46dcde-8e95-4e44-9d2a-702768d96826)
![afterpeek](https://github.com/CleverRaven/Cataclysm-DDA/assets/42590653/84c0909a-4ecb-4290-b0cb-54661952db4e)

From top of apartment building, before and during peek.
![zlevels odd](https://github.com/CleverRaven/Cataclysm-DDA/assets/42590653/a1f9234c-4121-42d1-81db-4773c147b1ad)
![zlevels peek](https://github.com/CleverRaven/Cataclysm-DDA/assets/42590653/48bb787f-f876-43dd-8e21-020d9dde3cbc)

view from z-5 in 2023-12-18-0506 with FOV off and no map memory

![z5 expected](https://github.com/CleverRaven/Cataclysm-DDA/assets/42590653/5b92d5f4-2771-4af9-93d9-8d4f8cba01bd)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3930 (22H2)
- Game Version: 31e4c0e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

Possibly related to https://github.com/CleverRaven/Cataclysm-DDA/pull/70957 ?  Just a wild guess.

**Comment by Qrox** [comment]
Probably caused by #70301? It checks the visibility cache of other z-levels, which probably causes it to not count z-levels below as visible with `FOV_3D` off until the tiles are memorized after looking down. I think the proper fix would be not showing any tiles outside the current z-level, including those memorized, if `FOV_3D` is off. @Rewryte what are your thoughts?

**Comment by amadcow4u2** [comment]
Just to clarify, FOV_3D on is only drawing terrain one z-level down.  FOV_3D off is drawing terrain zero z-levels down.  From a gameplay and visual standpoint I think terrain should be visible through open air regardless of the FOV setting.  Only gray looks terrible.

**Comment by Qrox** [comment]
What is the value of your `Vertical range of 3D field of vision` setting?

**Comment by amadcow4u2** [comment]
this is from z5 with FOV 10.  Nothing visible.  A month ago and a year ago terrain was drawing fine with or without FOV_on
![fov10z5](https://github.com/CleverRaven/Cataclysm-DDA/assets/42590653/f153cb16-ec6d-49ab-95da-97d6efb4923c)

**Comment by Qrox** [comment]
I did some testing, and when climbing up ladders the visibility is not updated before moving horizontally, but apart from that it is mostly working as expected since turning `FOV_3D` off makes the player character have no, well, FOV, in the z-direction.

When `FOV_3D` is on, terrain visible to the player character within the FOV range is displayed correctly, although the limited line of sight and the distance fog may have made it appear to not show much terrain.

It might indeed look more visually appealing before when all terrain is drawn, but do note that the game is supposed to draw the terrain from the perspective of the player character, not from the perspective of the monitor, so the previous behavior is actually incorrect and I don't think we can really support it.

Maybe we can make it so that the player character sees more terrain below when they are at the edge of a building, but that's a different matter not related to rendering.

**Comment by Rewryte** [comment]
Thanks everyone for testing.  Looks like some of the visibility caches aren't updating properly when experimental 3D is off.

On my end, disabling the `fov_3d` check in `map::build_seen_cache` solves most of these issues.  There are still some dark spots that should not be there so likely another cache is involved somewhere else.

On this matter, I think it's time we properly define what each 3D setting does.  Currently, "Experimental 3D FOV" largely governs creature visibility while "Vertical range of 3D FOV" controls terrain.

> I think the proper fix would be not showing any tiles outside the current z-level, including those memorized, if `FOV_3D` is off.

> I think terrain should be visible through open air regardless of the FOV setting. Only gray looks terrible.

I think it would be desirable for players to be able to have 3D terrain regardless of 3D character visibility.  We could rename the settings so that they accurately reflect what they do.  Code that checks for 3D terrain visibility, such as `map::build_seen_cache` in this case, should check for `fov_3d_z_range == 0` instead of `fov_3d`.

**Comment by Qrox** [comment]
> I think it would be desirable for players to be able to have 3D terrain regardless of 3D creature visibility.

It seems strange to me that anyone would want to see terrain below without also seeing the creatures there. Sounds like option for option's sake to me. In my opinion a single option to control the vertical view range is sufficient and the `FOV_3D` option can simply default to on and be removed. If the player doesn't want 3D vision they can set `3D_FOV_Z_RANGE` to 0 to revert to the legacy colored blocks display.

**Comment by Rewryte** [comment]
> In my opinion a single option to control the vertical view range is sufficient and the `FOV_3D` option can simply default to on and be removed. If the player doesn't want 3D vision they can set `3D_FOV_Z_RANGE` to 0 to revert to the legacy colored blocks display.

That works too I guess.  If anything, switching things up lets us get more feedback from the player base to see if they like the changes.  Was the 3D-as-default issue fixed?  I might have been out of the loop.

**Comment by Qrox** [comment]
Not yet. The player activity interruption test is still failing when 3D FOV is on, but only when running all tests and succeeds when run on its own, and the map/avatar are already reset before the test, so I really have no idea what could be causing the failure.

**Comment by Rewryte** [comment]
Looks like fixing that would precede any settings changes then.  In favor of hotfixing this issue first?  Should only take a line of code.

**Comment by Qrox** [comment]
Yeah, a hotfix would be nice.
