### ISSUE TITLE
The Commune is weirdly choosy about their blankets. Don't they know there's an apocalypse happening?

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#71215]
### Is your feature request related to a problem? Please describe.

They want 25 blankets for bedding. Ok, that's fine. I can do that. But they won't take down-filled blankets, they won't take electric blankets, or fur blankets, nor quilts or patchwork quilts, or rolled sleeping bags, or mattresses, or anything. Most quests, I can deal with the NPC being hyper-specific in their needs, but there are so many bedding options, and they're so picky.

### Solution you would like.

I'd like them to be open to accepting any item that would reasonably be considered bedding.

### Describe alternatives you have considered.

I could continue to use the debug menu to just cheat in blankets to replace all the other bedding I found that they just won't accept.

### Additional context

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6834262/ef0f1ce9-59f5-41d1-b5fb-bdb385541829)

**Comment by RenechCDDA** [comment]
I remember helping someone with the syntax for fixing this, maybe their PR got staled?

**Comment by GuardianDll** [comment]
our documentation and use cases about MGOAL_FIND is suprisingly poor. Can you point me what should be done to fix it?

**Comment by Cenness** [comment]
This?
https://github.com/CleverRaven/Cataclysm-DDA/blob/de8a47fff6b615d3caf911a54b5e801d9c6f5cc9/data/json/npcs/lumbermill_employees/lumbermill_missions.json#L105
https://github.com/CleverRaven/Cataclysm-DDA/blob/de8a47fff6b615d3caf911a54b5e801d9c6f5cc9/data/json/npcs/lumbermill_employees/lumbermill_missions.json#L109-L117

**Comment by GuardianDll** [comment]
oh, still doesn't allow dynamic amount of different items
damn

**Comment by PatrikLundell** [comment]
It's definitely not a "Good First Issue" as it requires the introduction of new logic.

What I think you'd need is some logic that says you need 25 items from a new "blanket" group and any item belonging to the "blanket" group would be counted as one such item.
Also note that such logic would only work for equivalent items, where the ratio is 1:1.
It might be possible to extend such a logic to include unequal items, provided the grouping syntax allowed for ratios (which would probably have to be integral). However, it would be rather difficult to convey to the player how many of the group items you have collected if you include items with mixed ratios.

It can be noted that such a group logic might be useful for crafting, allowing you to preserve e.g. offal of mixed types, rather than hope that you can keep them in the freezer until you've collected enough of them to preserve them using the existing single type recipes (fruit/berries might be a better example as they tend to come in 250 ml standard packages that should have a 1:1 ratio).

**Comment by Cenness** [comment]
Looks like MGOAL_FIND_ITEM_GROUP is what should fix this, but no idea if it actually works. Haven't found any example in code

**Comment by GuardianDll** [comment]
need to check does it even works at first

**Comment by MNG-cataclysm** [comment]
MGOAL_FIND_ITEM_GROUP doesn't work, I tried it already some time ago when I was making the lumbermill NPCs.
