### ISSUE TITLE
Mossberg 500 Field and Mossberg500 Security have identical stats despite having different barrel length

### ISSUE THREAD

**Issue by Fox-Ball** [CleverRaven/Cataclysm-DDA#71233]
### Describe the bug

Mossberg 500 Field and Mossberg500 Security have identical stats despite having different barrel length. 
28 inches and 18.5 inches respectively according to the in game description.

### Attach save file

[Connorsville.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/14045629/Connorsville.zip)

### Steps to reproduce

N/a

### Expected behavior

They should have different stats since the barrels are of different length.

### Screenshots

![Screenshot 2024-01-24 203416](https://github.com/CleverRaven/Cataclysm-DDA/assets/141479832/8b5ca189-7f27-44bb-8bdf-0a7ef5552c35)

### Versions and configuration

Experimental cdda-windows-tiles-sounds-x64-2024-01-14-0248

**Comment by Icantthinkofanameforthis** [comment]
Well theyre not wrong.

Seems the field one needs its stuff changed since its stats say barrel length 18 in. instead of the 28 it mentions in the description unless the description itself is wrong due to a typo like hitting the 2 instead of a 1.

Also looking at the security one it says 18.5 in the description while the stats just say 18 so not sure if thats due to it rounding down or didnt put it in correctly.

**Comment by carmakazi** [comment]
This issue can be traced all the way back to https://github.com/CleverRaven/Cataclysm-DDA/pull/49732

This was well before barrel length mattered beyond the item's size and length, to be fair to the author at the time, but what happened is that the variant system was (overzealously, in my opinion) used to collapse "similar" firearms into one, for the benefit of people who are not gun enthusiasts who enjoy that level of fidelity.  Because the Mossberg 500 Field and Security both have the same ammo capacity, they are now variants of each other.  However, this means that they are essentially the same item barring the name and description, and there is no way to make them have different stats as long as they are variants.

This is not the only gun with this problem.  The ACR .223 takes AR-15 uppers last I knew.

> Seems the field one needs its stuff changed since its stats say barrel length 18 in. instead of the 28 it mentions in the description unless the description itself is wrong due to a typo like hitting the 2 instead of a 1.

The description is not a mistake, the Field model typically has a long 28 inch barrel.  This was overlooked at the time the two guns were merged.

The two proper ways to correct this that I see are:
1. De-variant-ize the two guns and give the Field its proper 28 inch barrel.
2. Add the ability to have stat modifiers on a specific gun variant, so that the Field may have a longer barrel and new size/weight, but still be a variant.
