### ISSUE TITLE
Nerf heal speed, but not linearly

### ISSUE THREAD

**Issue by fairyarmadillo** [CleverRaven/Cataclysm-DDA#71318]
### Is your feature request related to a problem? Please describe.

Healing times were adjusted a while back to make healing take longer, but I think it's gotten out of hand again as updates have introduced some power creep. You can boost your healing speed by:

Raising health care skill. This has actually gotten harder and is fine.

Multiple levels of the wound care proficiency. These cost nothing but time and a single infinitely re-usable bandage to unlock. You don't even need books. This is one of the big ones.

A comfortable chair/bed.

Decent bandages: It's really easy to create boiled makeshift bandages, but you kind of don't need to. Improvements to zombie loot over the years have made regular bandages super common.

Lifestyle: It's really easy to stay at "feeling good" or "feeling very good" even if you're eating lots of junk food and doing drugs. Exercise counts for a ton and it's kinda hard to play without getting exercise.

Antiseptic: This is another big one. You used to have to actively make cattail jelly or luck into proper antiseptic, but now you're always carrying hundreds of alcohol wipes, and anyone can make antiseptic-soaked cotton balls to stretch supplies much farther, plus there's peroxide everywhere. This isn't really a bad thing, but it means after like your first week, if you know what you're doing, you are never wanting for supplies, likely have one if not two proficiencies, and have a high lifestyle bonus.

At that level, with no healing traits, you can recover from like one | of health to full in an afternoon without even going to sleep.

### Solution you would like.

Flatly debuffing heal speed might work, but we shouldn't make things too obnoxious for players who only know how to do the bare minimum. Halving overall heal speed might make our week 2 superdoctor have to sleep to get back to full HP, but it would leave a new survivor badly wounded for days if all they had was makeshift bandages.

A debuff on the lifestyle bonus, making wound care proficiencies require a book and a lot more practice (possibly on real wounds, in a nonrepeatable fashion), reducing the heal speed bonus on low quality antiseptics, reducing the cumulative bonus from multiple sources, or similar things might slow down the superdoctor without negatively impacting unprepared characters too much.

Slowing healing speed the more HP was lost might also fix the issue. So if you're missing one bar of HP, you can bounce back in a day, but missing four bars is a bad time.

### Describe alternatives you have considered.

I know there's a wound system in the works, but that's far enough off that a quick fix here would improve the game in the meantime and keep the regeneration traits from feeling as lame as they currently do.

**Comment by Standing-Storm** [comment]
> Slowing healing speed the more HP was lost might also fix the issue. So if you're missing one bar of HP, you can bounce back in a day, but missing four bars is a bad time.

I'd like to toss some support behind this solution. It would help smooth out the difference between 1 HP left (walk it off, you'll be fine tomorrow after you bandage it) and 0 HP left (days or weeks of low activity waiting for your broken limb to heal)

**Comment by fairyarmadillo** [comment]
> > Slowing healing speed the more HP was lost might also fix the issue. So if you're missing one bar of HP, you can bounce back in a day, but missing four bars is a bad time.
> 
> I'd like to toss some support behind this solution. It would help smooth out the difference between 1 HP left (walk it off, you'll be fine tomorrow after you bandage it) and 0 HP left (days or weeks of low activity waiting for your broken limb to heal)

This also feels like a fun place for mutations and magic to affect healing. Imagine for example a plant mutant having a reduced overall healing time, but a flatter heal time/damage ratio.

**Comment by Venera3** [comment]
The healthcare scaling (and the entire skill, if we're being honest) could just be axed, for a start.

The impact of bandages/antiseptic is also on the overtuned side, especially since health got cheap to get to amazing, and the profs are a bonus to the care level, not getting them to workable.

**Comment by Rokharn** [comment]
How about to create game setting to change global healing factor from world options? It's can be useful for newbies and for veterans as well. Current perks to change it have some limits.

**Comment by fairyarmadillo** [comment]
> How about to create game setting to change global healing factor from world options? It can be useful for newbies and for veterans as well. Current perks to change it have some limits.

There are already traits for this.

> The healthcare scaling (and the entire skill, if we're being honest) could just be axed, for a start.
> 
> The impact of bandages/antiseptic is also on the overtuned side, especially since health got cheap to get to amazing, and the profs are a bonus to the care level, not getting them to workable.

Reducing the ability to get super awesome health would be great. I think adding macronutrients would do it, but raise your hand if you want to be the one to handle that lol

**Comment by ZhilkinSerg** [comment]
> How about to create game setting to change global healing factor from world options? It can be useful for newbies and for veterans as well. Current perks to change it have some limits.

https://github.com/CleverRaven/Cataclysm-DDA/blame/b3a2e0d98cd04c32ba08189a0c01fde277626764/data/core/game_balance.json#L65-L71

**Comment by Nebnis** [comment]
>Slowing healing speed the more HP was lost might also fix the issue. So if you're missing one bar of HP, you can bounce back in a day, but missing four bars is a bad time.

I was thinking about this the other day and might be a really good middleground

I thought about some numbers, for now they are a bit random.

75~100% slightly wounded= Bruises and cuts, heal in 1 day with any bandage
50~75% wounded= Bites and gashes, takes 2 days of best quality bandages/antiseptic/health or 4 of worse
0~25% badly wounded=Grievous cuts, takes 3~4 days of best bandages/antiseptic/health or 8 of worse

This way, people who are just starting the game with no skills won't get so badly crippled with nothing on them if they pick a few fights but at same time will punish people who aren't careful.

While i agree that the current system feels  a bit too magickey and overblown, i kinda feel that there is need to be a good middleground because if we went with the actual times, my dog feet bite took 1 month to heal(i was limping all the way) and my nephew broken hand took 4 months. He didn't even break his hand too badly. 

I always attributed the heal speed due to the blob magic/portal storm bullshittery, but doesn't mean we should be going from nearly dead to full hp with just a single nap and a curtain wrapped on my feet. There should be a bigger enphasis in using actual first aid kits and medicine rather than makeshift.

**Comment by IdleSol** [comment]
Where can I see what and how it affects a character's healing?

In general, I agree that the healing rate should be reduced. But I don't see an option that won't hurt the early stage of the game. Other than reducing mob damage in the first week, which is pretty weird.

**Some ideas.**

**Bandages** - don't increase healing speed. They reduce the chance of wounds getting infected (or inflamed) due to dirt getting in, during the healing process.

**Antiseptic** - either does not accelerate or accelerates slightly. Designed to cleanse wounds of dirt, infection, spores(?).

**Proficiency**. Wound Care and Wound Care Expert. Speed wound care: bandages, antiseptic may be splints. It is possible to reduce the quality (not increase !) of treatment by 1 step, from the quality of materials.

**What it might look like**

A wound is:
- chance of infection (already realized)
- chance of bleeding (already realized)
- chance of contamination. The chance of foreign objects getting into the wound: dirt, fibers, germs, spores (?). Let it be 20%.  It is checked at the moment the damage is inflicted. Yes, 20 hits for 1 damage, with a 99% chance of bringing dirt into the wound.
- Chance of recontamination. This is the chance that a foreign object will enter the wound, but after the fight is over. Let it be 5% with a check every 5 minutes.

If contamination occurs, then after some time (~ one hour, maybe better 2 hours) inflammation or infection (1d2) can begin.

If there is a desire, it can be divided into stages:
- latent infection, overt infection
- initial stage of inflammation / inflammation / severe inflammation / suppuration / necrosis.
And the detection of latent and initial stages, tied to the skill level of medicine.

Then:
Bandage - stops bleeding and reduces the chance of recontamination. Conditionally -1% for the quality of the bandage. Dressing quality is good = 0% for contamination.

Antiseptic - cleans the wound and removes contamination. Should not prevent recontamination. Here we get a contradiction, as it is displayed in the character window. This implies that it is still active. So either remove it from the window and everything related to it. Or add the inability to get contamination while the wound is treated with antiseptic.

**Comment by kevingranade** [comment]
Yea that seems like an extreme outcome,  the intent is more like (subject to adjustment,  but we need this level of detail at a minimum)
Minor damage (say one bar of health missing) should resolve in an evening with good care and a day if ignored.
Notable damage (about two bars damage) should resolve overnight with good care, two days of rest with no meaningful health care, 3-4 days if ignored.
Major damage (three bars) should resolve with a full day of rest and good care,  2-3 days of rest but poor healthcare, and 5-6 days if ignored.
Severe damage (four bars) should resolve with several days of full rest and good health care, 4-5 days of rest but poor health care,  and a week+ if ignored.

So far this has one data point,  "I can heal from |.... to ||||| in one afternoon after <implied but not specified criteria are met>"

At a minimum this needs "do these specific things (debug menu is OK) then this is the result".

IDEALLY something as far reaching as this would have a half dozen or more of those examples that could then be codified into a test case that's used as the acceptance criteria for the fix.
