### ISSUE TITLE
[MoM]Balance/limit amount of powers/classes players can learn.

### ISSUE THREAD

**Issue by Nebnis** [CleverRaven/Cataclysm-DDA#71345]
### Is your feature request related to a problem? Please describe.

It feels that the survivor powerlevels can easily spiral out of control by how fast you can learn new classes. Maybe there could be some limitation like how mutations have? Specially because even if you don't spend time learning more from the others, you still greatly benefit from the passive effects  and the basic spell levels

### Solution you would like.

Maybe there should be a hard limit dictated by metaphysics? Every 2 points, increase a class for a total of 5 at 10 metaphysics. Those awakened buffs could be reserved for a class that you could specialize and lock into your character. Let's say you learn a few  spells and then you become awakened. Then we could have a jack all trade class that can't level spells past 6 or don't learn advanced ones.

Lore could be like if your mind becomes too crowded to absorb so much psionic skill. It would help characters feel a bit more unique and could even have rewards for mastering a class fully

**Comment by Standing-Storm** [comment]
There is already an exponentially decreasing chance to learn new paths based on how many you know: 

For matrix crystals, the chance to gain the first is 100%, the second is 55%, the third is 31%, the fourth is 17%, the fifth is 10%, the sixth is 5%, the seventh is 3%, the eighth is 1.6% and the ninth is 1%.

For portal storm awakenings, the formula is more generous but it can roll any possible path including ones you already have, so the formula gives 72% chance to awaken the second path but it's actually 64% (72% * 8/9). The chance of a third path is 40% (51% * 7/9), and so on. 

In addition, under the new power learning system, you can only learn one new power per learning period spread across all of your paths, rather than being able to concentrate on a specific path to level. 

If you want to pick multiple paths at character creation to skip this, that's your business and I'm not going to limit it. 

> . Then we could have a jack all trade class that can't level spells past 6 or don't learn advanced ones.

Something like this will eventually be the case (You will have to actively choose to be able to learn the higher-level powers, and it will come with consequences) but it requires all the infrastructure to be in place first.

**Comment by Nebnis** [comment]
I see, i already have 4, so i guess i got a bit lucky, though with how often you can find crystals and portal storm happens, those percentages still feels generous. Unless i'm being lucky with finding crystal clusters and outcrops too :P. Would maybe be nicer if the storms actually gave you a random crystal rather than randomly give powers? This way i would have a choice of learning new powers when i explore rather than being imprinted automatically.

Thank you for the hard work storm, this is really an amazing mod and felt like dropping a piece of feedback after trying a bunch.

**Comment by Standing-Storm** [comment]
Thank you!

Part of the MoM lore is that portal storms gave a bunch of humanity powers--the week straight of massive portal storms that caused the actual Cataclysm is where all of those feral psions come from.  In a sense, portal storms do give you a random crystal, since those crystal outcroppings are supposed to be the scars left behind by past portal storms.  It's just that for game limitation reasons (no way to add extra outcroppings to areas where portal storms might be happening when you're not there), they don't occur during game-time.

> Unless i'm being lucky with finding crystal clusters and outcrops too :P

I do hear some people complaining that MoM stuff is so unobtrusive that they don't feel like they can ever find it, so it's hard to tell where the balance point is. Four paths is about the upper limit of what I think should be reasonable for someone who doesn't spend all of their game time chasing down new power sets (past that, you're churning through a LOT of matrix crystals or time in portal storms to unlock anything new).

**Comment by Rokharn** [comment]
> I see, i already have 4, so i guess i got a bit lucky

Previously I had used ~14 unsuccessful to getting 3rd... Plus to find it I traveling a lot. So yes, you are lucky. Average MoM 
office 'lab' have from 2 to 3 crystal (not easy place for sure), sometimes just one at average loot settings. It can have even just a zero for more hardcore settings. Crystal clusters often have zero crystals from enemy loot, sometimes just a black ones, very rarely colored ones as loot, even more rare just on the ground. At least this is my experience.

By the way, all this time I believed that a portal storm can only awaken the first power once, after which the option should not be available.
