### ISSUE TITLE
Fix/obsolete until fixing meat overgrown labs because of fps killer 

### ISSUE THREAD

**Issue by KHeket** [CleverRaven/Cataclysm-DDA#71349]
### Describe the bug

#68593 added the meat labs, but because of tons of amalgams and breathers, which spawning overtime little breathers again and again, and, maybe, I don't know, there can be other fps killing factors, but its **impossible** to comfortably go through this labs and also **impossible** to walk at the surface, when this kind of lab is under you, because game became ultra slow, I didn't ever see more laggy place than this kind of labs, and meat labs also are few(2/3/4) time laggy, than most lagging labs, I had lesser lags with TCL facilitys full filed with blobs

### Attach save file

n/a

### Steps to reproduce

Reveal map, teleport to labs, find meat lab, try to wait inside or at surface of this lab for few minutes, or just walk at the surface - see the turtle speed of the game

### Expected behavior

Don't have anomaly fps slowing zones in the game

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3930 (22H2)
- Game Version: 56c9082 [64-bit]
- Graphics Version: Tiles
- Game Language: Русский <color_dark_gray>(92,2%)</color> [ru]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by Nebnis** [comment]
Until the game can handle this kind of design, i feel breathers and slimes do more harm than good to this game. Their ability to multiply needs to be throttled somehow, like never more than a bunch.

**Comment by ZhilkinSerg** [comment]
Do you have a savegame with that lab below?

**Comment by ZhilkinSerg** [comment]
We should try to make these monsters blind

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/16213433/16b231d1-b253-4c8b-949b-70257d5714ca)

**Comment by Nebnis** [comment]
Would making them check for noises be better cpu wise? And blind

**Comment by John-Candlebury** [comment]
Want to mention that breathers are already blind, if they are processing vision info theres another underlaying bug here.

**Comment by ZhilkinSerg** [comment]
Actually there is no check for monster flag `SEES` in `sees` function.

**Comment by Maleclypse** [comment]
@akrieger this looks like the kind of thing you might be interested in.  If not my apologies.

**Comment by akrieger** [comment]
I don't know what hope there is here. There's hundreds of breathers, which are not friendly to swarmers and other enemies in the lab which can see. The monster planning logic doesn't have the ability to intelligently sort monsters by distance (or at least, doesn't yet), and all the time spent in monster::sees is spent accessing the LRU cache to check point to point visibility (which is going to be swarmers * breathers large, which is... a lot). Even raising the limit on the seen cache doesn't help because there's just _so many checks_ happening and each check is relatively expensive (map lookup and list splice combined).

**Comment by kevingranade** [comment]
Hrm, possibly add some firewalls between areas? If they have walls/doors between them #68097 should keep them from having to check for reachability constantly.
I've tried to figure out sorting by distance several times, but the problem is perversely when a monster is in a room where it can't see anything but has a path to them, in which case it will check closest first, but still end up checking everything, so the sorting ends up being pure overhead.

**Comment by kevingranade** [comment]
Just checked with Candlebury and there's no real reason that the breathers should be antagonistic to the other creatures, so we can probably just shuffle around some factions (with a variant breather if nothing else?).

**Comment by kevingranade** [comment]
Yea confirmed in perf
![Screenshot from 2024-06-18 16-24-40](https://github.com/CleverRaven/Cataclysm-DDA/assets/860276/78336dfb-e83c-48ff-933d-4c51a761f67d)
Looking at changing factions so they aren't hostile to each other.

**Comment by akrieger** [comment]
It'll help by like, 1/3, which is a lot but it's still pretty darn slow.

**Comment by kevingranade** [comment]
Yea testing bore out your prediction, so I cut the number of breathers that spawn in there pretty drastically too, resulting in it being fairly snappy:
![Screenshot from 2024-06-18 18-17-06](https://github.com/CleverRaven/Cataclysm-DDA/assets/860276/d3f3a793-5153-4c11-8823-8e64529712ee)
