### ISSUE TITLE
Unable To Construct "Dig Downstair"

### ISSUE THREAD

**Issue by Pugglee** [CleverRaven/Cataclysm-DDA#71381]
### Describe the bug

Despite having all that is needed for the recipe and being on ground that can be dug up I can't dig downstair

### Attach save file

[Pedro.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/14107811/Pedro.zip)

Should work on a fresh save file

### Steps to reproduce

1. make a player with 5 fabrication and 3 survival.  2. spawn in a hammer, wood saw, pickaxe, shovel, 90 nail, 18 planks, and 2 heavy wooden beams. (materials for the recipe) 3. Find dirt and attempt to dig downstair. 

### Expected behavior

I expected to be able to dig downstair

### Versions and configuration

- OS: Windows 11  -Game Version: Experimental Build 2024-01-31-0419  -Graphics Version: Tiles  -Ingame Language: English  
- Mods loaded: dda, bionic slots, disable npc needs, slowdown fungal growth.

**Comment by PatrikLundell** [comment]
/confirmed

- Construction menu: "You can't build that"
- Zone construction: "The required items are not available to complete this task"
- Built a shallow pit (as it used to be a step in the downstair production process).
- Construction menu: "You can't build that"
- Zone construction: "The required items are not available to complete this task"
- Dig a pit (I think that was a step in the process)
- Construction menu: "You can't build that"
- Zone construction: "There is something blocking the location for this task"

The failure is probably cause by recent changes:
The line
`      [ [ "rope_natural", 1, "LIST" ] ]`
in construction.json entry constr_dig_downstair doesn't generate any displayed tool requirement.
Spawning a long rope doesn't fulfill the requirement, and changing the line to `[["rope_30", 1]]` lists a long rope with a charge of 1 as a requirement, but a spawned long rope doesn't satisfy it (possibly because of the removal of charges?).

**Comment by Myfharad** [comment]
Still unable to dig down as of March 2nd

**Comment by osuphobia** [comment]
I think I located the reason.
The old Construction recipe list
`[ [ "rope_makeshift_30", 1 ], [ "rope_30", 1 ], [ "vine_30", 1 ] ] `
as one of the components required, while the new recipe list
`[ [ "rope_natural", 1, "LIST" ] ]`
as a tool required, but rope_natural doesn't work that way.
The solutions of this problem could either be:

- Move
`[ [ "rope_natural", 1, "LIST" ] ]`
from tools required to components required,

- Or remove
`[ [ "rope_natural", 1, "LIST" ] ]`
and add
`[ { "id": "ROPE", "level": 2 } ]`
to qualities required.

Result:

<img width="1186" alt="components" src="https://github.com/CleverRaven/Cataclysm-DDA/assets/78858975/9cc4ed04-8dd7-4984-9a94-3e3555085d35">

<img width="1107" alt="qualities" src="https://github.com/CleverRaven/Cataclysm-DDA/assets/78858975/e9926d17-1d59-4908-bab7-90e56a819bf1">

**Comment by osuphobia** [comment]
Tracked the change log, in https://github.com/CleverRaven/Cataclysm-DDA/pull/69822 `[ "rope_30", "vine_30", "rope_makeshift_30" ]` is moved from components to tools required in dig_downstair, mine_downstair and mine_upstair.
Then https://github.com/CleverRaven/Cataclysm-DDA/pull/71087 replaced [ "rope_30", "vine_30", "rope_makeshift_30" ] with rope_natural.
As mentioned in the PR above, rope_natural is not defined as a tool, but a component in material.json, so simply adding it to tool-requirement result in nothing.

**Comment by Consoleable** [comment]
Confirmed still an issue as of march 10th
