### ISSUE TITLE
Why do I know how fully charged all batteries are?

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#71390]
### Is your feature request related to a problem? Please describe.

This isn't a frustration, but I walked up to a body, and it had two batteries in its pocket. I knew instantly and instinctively exactly how much charge was in each battery, down to the 1/3 of a percent. This suddenly struck me as weird. Why do I know this? There's no in game reason I can see for this instinctive understanding. Likewise with most sealed liquid tanks and containers. Knowing that a tank of propane is at (58926/60000) is more useful, perhaps, than (nearly full), but is unrealistically specific, given that it's sealed in a tank. 

### Solution you would like.

Batteries you find might have an unknown charge level until plugged into a device that shows how much charge remains. A headlamp or other item that dims as charge decreases might get you a rough idea of remaining power, while an e-ink PC, laptop, or electric tool that had a battery indicator could show within a % or two. If you're using the item when the battery runs out, you know it's dead. When it's been recharged you know it's full. Barring specific powers over electricity (CBM, mutation, magic, whatever), you'd never know the specific units of free-floating battery charge. 

This would have fairly large impacts on how tool energy usage would be shown on crafting recipes. You might have a sense that a recipe would require your cordless drill to have enough charge support an hour's worth of crafting with it, but not the specific number of charges required. Similarly, it would solve the mishmash of heating types being a giant block of various amounts of charges in the recipes. Knowing that a recipe takes 2 charges from an acetylene cooker, but 4 charges from a gasoline cooker, but 50 charges from a military mess kit... it's kind of a mess. Clarifying that down to X amount of time on Y tools would streamline the crafting menu, while still making clear what's needed.

It would probably also require an update of the [R]eload menu to make clear, when inserting a tool magazine into a tool, how long you think that tool magazine will let the tool function for. The level of specificity you get might be tied to your skill level? Someone with Fabrication 7 probably has a much better sense of how long a battery will work for in a tool than someone with no skill at all.

### Describe alternatives you have considered.

Leaving it alone. Obfuscating electric charge and liquid levels in sealed tanks seems like a lot of work.

**Comment by Vaskritaya** [comment]
I feel like this is one of those videogamey abstractions that are best to be made for the sake of gameplay. Consider how many batteries you find in homes and the like. Are you really going to grab them, go to your base, and sit there going (U)nload, (r)eload, (D)rop in the pile for good/bad batteries 30 times in a row? Only recently are we able to scan several SD cards at once, and I definitely don't want to go back before that in terms of design.

As for obscuring containers so you might have a "steel jerrycan (half-full of gasoline)" or "plastic bottle (completely full of water)", it's an interesting idea, but I don't think it would add much for the amount of work involved. Sure, it's silly to know that you have exactly 3162 units of gas in a can, but its definitely the easiest implementation development-wise and least annoying implementation player-wise.

Information related to the available use time of a tool could actually be pretty helpful for things you use in the field, since it's not particularly easy to intuit what charges mean for them. Things like jackhammers or propane torches come to mind.

**Comment by pjf** [comment]
In my mind every battery either has one of these, that lets you tell the charge by touching it:
<details><summary>Click for image</summary>

![batterycheck](https://github.com/CleverRaven/Cataclysm-DDA/assets/12072/a9f4b8fd-800c-4410-9743-75e41c067368)

</details> 

Or are shaped like one of these, that lets you tell the charge by licking it:

<details><summary>Click for image</summary>

![9v-rechargeable-battery-700mah-3-2091693973](https://github.com/CleverRaven/Cataclysm-DDA/assets/12072/414d8ef3-2467-4935-ada4-403ff7530ea1)

</details>

And we just abstract away the battery licking that survivors do that every opportunity.

**Comment by PatrikLundell** [comment]
Also note that using recharging stations is already a chore, given that it takes forever to recharge storage batteries, so you have to check them daily to see if they're fully charged yet so you can replace them with (more or less) depleted ones. Making you blind in that situation would be really bad.

I don't see any reason to degrade game play for the sake of realism in this case.

**Comment by kholat** [comment]
I imagine them having the powerCheck duracell patent that was a big deal but now nobody cares https://tedium.co/2021/01/20/on-battery-power-meter-history/

good enough
