### ISSUE TITLE
Improve charge-counts for tools and comestibles

### ISSUE THREAD

**Issue by cSep** [CleverRaven/Cataclysm-DDA#7140]
To give the world a realistic feelm comestibles and tools should be found with varying charges. This gist explores how to swiftly implement a solid enhancement.
https://gist.github.com/cSep/10281412

To start, i poked through the json for charge usage examples and created scenarios for each of them. They are linked below, to explore exactly what the implementation has to do.

In the process this little bit of json emerged: https://gist.github.com/cSep/10279358 it is intended to bridge from the item.type to the droptable which defines the actual curve from which charges are derived.

i found chargables in different categories. https://gist.github.com/cSep/10279954 has scenarios to obtain initial charges for each of them. let me know what i missed!

here's lore and data for the dropcurves https://gist.github.com/cSep/10282383
##

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
