### ISSUE TITLE
Error while turning cube van

### ISSUE THREAD

**Issue by nornagon** [CleverRaven/Cataclysm-DDA#71451]
### Describe the bug

```
 DEBUG    : no display part at mount (-5, 4)

 FUNCTION : vpart_display vehicle::get_display_of_tile(const point &, bool, bool, bool, bool) const
 FILE     : src/vehicle_display.cpp
 LINE     : 64
 VERSION  : f2cdb18
```

### Attach save file

[Laporte-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14146631/Laporte-trimmed.tar.gz)

### Steps to reproduce

Got in a cube van and turned it. Using NeoDays as my tileset.

### Expected behavior

No error message?

### Versions and configuration

- OS: MacOs
    - OS Version: Name: macOS; Version: 14.3; Build: 23D56; 
- Game Version: f2cdb18 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by RedMisao** [comment]
I've getting these errors when finding broken cars in roads. Gotta post a picture and the debug info next time it happens.

**Comment by PatrikLundell** [comment]
Failed to reproduce from the save. I believe the tileset used is Ultica (whatever the default is, anyway), so it could be tileset related.

**Comment by nornagon** [comment]
I was using NeoDays


j

**Comment by IdleSol** [comment]
```
DEBUG    : no display part at mount (-2, -4)

 FUNCTION : vpart_display vehicle::get_display_of_tile(const point&, bool, bool, bool, bool) const
 FILE     : src/vehicle_display.cpp
 LINE     : 64
 VERSION  : 2013584
```

- OS: Windows
    - OS Version: 10.0.18362 (21H1)
- Game Version: 2013584 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Stats Through Kills [stats_through_kills]

[Suisun City-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14220646/Suisun.City-trimmed.tar.gz)

Yes. I'm using Ultica. I'm assuming this bug cannot be reproduced from a save.

**Comment by RedMisao** [comment]
> I've getting these errors when finding broken cars in roads. Gotta post a picture and the debug info next time it happens.

Welp I forgot to take debug info. I'm using brownlinkedbears for reference. 

![no display part at mount](https://github.com/CleverRaven/Cataclysm-DDA/assets/95231551/72d2bddd-9728-4f7f-a80b-b7150fc4c8e0)
![no display part at mount 2](https://github.com/CleverRaven/Cataclysm-DDA/assets/95231551/68e9ce03-a4f4-4653-957f-9ade6fe2b2f0)

**Comment by IdleSol** [comment]
I found a way to reproduce this error. And I was right, it cannot be reproduced from a save.

The reason is broken parts and their display when turning. There is a feature in the game that duplicates car parts when driving diagonally. The error occurs when it tries to duplicate a broken car part. Or when something interacts with that part.

**Steps to reproduce.**

1. Create a world and a character
2. Create a coupe car without damage: `debug menu`-`v`-`s`-`y`-`1`
3. Grab something heavy (mace) and start breaking the left door, until it is red (\ . door).

![test 1](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/6499123e-f4f1-496f-81b1-dd374078f945)

4. Get in the car and start driving. Make a 360 degree turn. Notice there are no errors.
5. Stop and make a save.
6. Break the door down to a gray state (XX door).

![test 2](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/6a5176fd-0bc4-4eca-95f7-868b9ee5e422)

7. Repeat step 4. Get an error with coordinates 0,-2. This means X=0, Y=-2 or two squares to the left of the seat with the driver (0,0). This is where the duplicate door should be located.

![test 3](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/90eb49fa-0fee-4ffd-9f46-0e116a051e05)
![test 4](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/f1772c4e-e695-424a-9adf-afaf83495cc3)
![test 5](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/e27c8887-a664-4ef8-83f7-084b61ff8358)

8. Exit the game without saving. Close the game client. (or alt+f4)
9. Load the game and save from step 5.
10. Repeat step 6.
11. Save the game and exit to the main menu
12. Load the save and repeat step 4. Note that there is no error.

**There are also additional errors.**

When doing step 4, pay attention to the HP of the door and its duplicate. So the door itself, will be almost broken, and the duplicate will be whole.

![test 6](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/68dd394f-7f0b-4424-abab-ad582e896f87)

But if you do a save and load, the duplicate will have the correct amount of HP. It's also possible to go out of range. Apparently the function doesn't use the current strength value. Is it from memory or cache?

I hope the topic is still being watched.

**Comment by IdleSol** [comment]
The error is still occurring.
