### ISSUE TITLE
Manual reading doesn't work.

### ISSUE THREAD

**Issue by FayFlightee** [CleverRaven/Cataclysm-DDA#71458]
### Describe the bug

Tried to read the manual, the time just goes on and on without skill gained. Seem to work and not work randomly.

### Attach save file

[Nightmare-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14150473/Nightmare-trimmed.tar.gz)

### Steps to reproduce

1. Get a manual that can raise skill higher than you currently have.
2. Try to read.
3. Time goes on with nothing gained. If it works normally, sometimes it randomly cut off mid way.

### Expected behavior

I just want to be able to read book properly.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3930 (22H2)
- Game Version: abfbd86 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Extra Mutated Scenarios [extra_mut_scens],
    Translate Complex Dialogue [translate_dialogue],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by PatrikLundell** [comment]
/confirmed

Loading the save I initially didn't have any problems with Read Once (which is what I usually do), but read until next level just kept passing time, auto eating and drinking, until a message about excessive errors showed up (Ignored), and later the damnable portal mess started.
However, I've had one case where read until next level passed normally, i.e. regular reports about gains being reported.

The excessive errors message is probably not relevant here, as it appears on successful reading sessions as well.

I don't see it fail when I have the PC eat/drink sufficiently before starting to not have the auto ingestion interrupts kick in.

Disabling the zones and then have the character read until gaining a level is very slow and interrupted by eating (for some reason), until the portal mess attacks.

I suspect auto ingestion is causing the issue, possibly by discarding all progress made but not recorded/reported when the ingestion interrupt kicks in. However, given how slow progress is, I cannot rule out thirst having an effect. Drinking until satisfied makes the process go faster, but it might just be a matter of the stomach being filled up with water, thus delaying the eating.

Moving away from the zones and any possible food causes the reading session to take about the same time as if the PC has satisfied the water and food needs before starting. Thus, I would expect this to be caused by auto ingestion.
