### ISSUE TITLE
Multiple errors in JSON data

### ISSUE THREAD

**Issue by WarBarista** [CleverRaven/Cataclysm-DDA#71495]
### Describe the bug

In attempting to create the character, i get a lot of errors connected to elements' id, name, description, type and copy-from being invalid/misplaced in JSON data

### Attach save file

[Профетс-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14156513/-trimmed.tar.gz)

### Steps to reproduce

1. Create new world
2. Attempt to create a character
3. get the errors

### Expected behavior

I haven't noticed any severe problems yet, but error is error, so it shouldn't appear

### Screenshots

![Снимок экрана (63)](https://github.com/CleverRaven/Cataclysm-DDA/assets/73230104/e1e9205f-1eb9-4276-b837-de789579b405)
![Снимок экрана (66)](https://github.com/CleverRaven/Cataclysm-DDA/assets/73230104/49f5fcd0-e67a-45e0-a8ec-9ddc2afe71b2)
![Снимок экрана (68)](https://github.com/CleverRaven/Cataclysm-DDA/assets/73230104/b0afdd13-6240-4d27-8be2-abc698733ec9)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.3007 (22H2)
- Game Version: e286c6e [64-bit]
- Graphics Version: Tiles
- Game Language: Системный язык []
- Mods loaded: [
    Тёмные Дни Впереди [dda],
    Отключить потребности у НПС [no_npc_food],
    Портальные штормы игнорируют НПС [personal_portal_storms],
    Медленный рост фунгалоидов [no_fungal_growth],
    Aftershock [aftershock],
    Разум над материей [mindovermatter],
    Развитая XEDRA [xedra_evolved]
]

**Comment by RenechCDDA** [comment]
Invalid. You modded locally and broke it then tried to load again without reloading the game. Not an issue with our distribution.

**Comment by RenechCDDA** [comment]
I apologize, it appears I was mistaken. I believed you had locally modified the Bombastic Perks mod which caused this error, because I saw that the enchantment ID was written in Cyrillic (we do not use Cyrillic script normally). This appears to be a real error related to localization.

**Comment by RedMisao** [comment]
This happens for me too. It is very reproducible as it always happens **only** after I edit any mod (*) json and make mistakes, such as a missing comma between } {, so the game can't start. I fix the mistake, delete the world, make a new one and I get the same "Invalid or misplaced field name "copy-from" in JSON data" on `art_robe` `copy-from`, every time.

This is after deleting a comma
![1](https://github.com/CleverRaven/Cataclysm-DDA/assets/95231551/5aa78d00-1d5f-4362-be95-4f42402afb2f)


This is after re-adding the comma, saving the file, deleting the world, creating a new one and going to New Game -> Custom Character
![2](https://github.com/CleverRaven/Cataclysm-DDA/assets/95231551/0498ef61-2263-46f1-bee0-586f452e0cf1)


The error happens before the "Loading files" window (this one)
![3](https://github.com/CleverRaven/Cataclysm-DDA/assets/95231551/affc6a7f-1a5a-4660-8b15-77b9d58abe00)


(*) I just tried to replicate it with a barebones world, no mods. It did not happen:

After deleting a comma before the Survivor profession
![4](https://github.com/CleverRaven/Cataclysm-DDA/assets/95231551/dc76e56b-f2f3-4c35-af7a-f56e4f2f9370)


After re-adding the comma, saving the file, deleting the world, creating a new one and going to New Game -> Custom Character
![5](https://github.com/CleverRaven/Cataclysm-DDA/assets/95231551/dbf34791-d36a-4871-ab8e-5a373e478fc5)


This has been happening to me since at least the 0.G experimentals. Not sure if it's relevant, but I use [Fris0uman's launcher](https://github.com/Fris0uman/CDDA-Game-Launcher/releases). It did not happen to me before 0.G, which coincides when I switched launchers.

Here's my version and config

- OS: Windows
    - OS Version: 10.0.19044.2965 (21H2)
- Game Version: 17e0ee6 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Touhou Professions [Touhou]
]

**Comment by RenechCDDA** [comment]
> This happens for me too. It is very reproducible as it always happens **only** after I edit any mod (*) json and make mistakes, such as a missing comma between } {, so the game can't start. I fix the mistake, delete the world, make a new one and I get the same "Invalid or misplaced field name "copy-from" in JSON data" on `art_robe` `copy-from`, every time.

This is unrelated, the loading process freaks out when you abort in the middle of it, you just need to restart the game. There's an issue for it, somewhere.

**Comment by RenechCDDA** [comment]
The JSON error stuff should be solved by #72316, which means all issues here have been addressed. For real this time.
