### ISSUE TITLE
Quest light retrieval and Item Spawn Scaling Factor

### ISSUE THREAD

**Issue by IdleSol** [CleverRaven/Cataclysm-DDA#71528]
### Describe the bug

There is no MISSION_ITEM flag on quest items

### Attach save file

[North Abington-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14164757/North.Abington-trimmed.tar.gz)

### Steps to reproduce

1. Load the save (Item Spawn Scaling Factor = 0.10)
2. Take the mission
3. Move to the location of the mission
4. Look at the contents of the wooden box.
4.1. If the quest items are there, repeat 1..4.
5. Load the save
6. Change Item Spawn Scaling Factor = 1
7. Repeat 2..4

### Expected behavior

Adding the MISSION_ITEM flag to quest items.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.18362 (21H1)
- Game Version: a8c6408 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]

### Additional context

I was sure it had been done a long time ago. Or was I just lucky to be getting these things?
#58225
#63030

**Comment by IdleSol** [comment]
No generation of EMP grenades in the first HUB quest. Is this a bug or is this situation acceptable? Do you need a new report?

**Comment by PatrikLundell** [comment]
There's a difference between unique quest items and normal quest spoils.

The Kord is a unique(?) item that should be available at a specific quest location, whereas the EMP grenades are nice spoils of a quest, but not required to succeed with the quest. You can definitely argue that the quest spoils should be guaranteed loot, but it's not critical for the ability to fulfill the quest.

If the Light Retrieval quest is the ruined tower one I can mention that I've failed to get the quest item at a standard spawn rate (yes, I'm sure it didn't exist, as I searched the save files for it to make sure it didn't exist before giving up and debug spawning it). A speculation is that it might potentially get destroyed by cave-ins. Note that this happened a year or a few ago.

As far as I can see, the reports referenced only resulted in an improvement on the Kord specifically, but nothing was mentioned about dealing with other cases of unique loot.

Searching for the MISSION_ITEM flag in the JSON files (not in mods) only finds it attached to the kord and the prototype I/O recorder. However, there might be other mechanisms available to ensure the spawning of special items (such as lab finales) that doesn't involve flagging the items themselves (e.g. by otherwise making sure the number of items specified aren't affected by scaling in some way). Note that both of the marked items should be found on the "corpses" of "creatures" as opposed to being found on a map.
However, I think there's a Hub01 mission where you retrieve an item off of a body (it used to be the body itself), and that case probably would benefit from a flagged item (as I don't think that item has any other use, as opposed to general purpose grenades).
It's quite possible there are other "unique" quest items that ought to be looked at.

**Comment by IdleSol** [comment]
Aren't these unique items?
https://cdda-guide.nornagon.net/item/template_armor
https://cdda-guide.nornagon.net/item/template_photonics

>A speculation is that it might potentially get destroyed by cave-ins. Note that this happened a year or a few ago.

I agree, but if there is a way to go back to the hub and say " it's gone". Thus completing the quest. At this point, it's all about luck. You got lucky and you passed. Bad luck and the quest is impossible to finish.

>Note that both of the marked items should be found on the "corpses" of "creatures" as opposed to being found on a map.

You're wrong. When you take the quest to the ruined tower. There's a small wooden box in the basement. There should be two templates in that box. The location is always the same.

If I remember correctly, this was done to guarantee the appearance. I assume that later, there were changes related to the attached items and the chance of appearance. Which again affected the chance of appearance. Or maybe I'm wrong. My language skills are pretty poor. And this was two years ago?

**Comment by PatrikLundell** [comment]
I don't know about the template armor (as in I don't actually know), but regardless, the comment about quest spoils was referring to the EMP grenades.

The prototype I/O recorder is the second object I referred to, not the template_photonics one (which doesn't have the flag).

The case where the tower quest item was missing was quite some time ago, yes. When I did the quest a couple of months ago it was successful.

The JSON reference you provided leads to a description of the chunk with the items appearing with a weight of 100. However, I don't know if these weights are absolute of affected by spawn scaling.

**Comment by IdleSol** [comment]
<b>1. First quest. Return Field Data</b>

<b>Problem</b>: The dialog claims that the scientist took the EMP grenades with her.
<i>Dr. Prado left the building with a handful of EMP grenades.</i>

https://github.com/CleverRaven/Cataclysm-DDA/blob/bcd1145b9461cacc537668e20c2d87c7ca522c3b/data/json/npcs/robofac/robofac_intercom/robofac_intercom_missions.json#L266

If the player changes the world parameter: Item Spawn Scaling Factor (ISSF). Then grenades may not appear.

<b>To confirm</b>: set ISSF = 0.01 and take the quest. Result, at the place of the doctor's death, there will be only the doctor's corpse and Hub 01 modular defense system.

The solution to this problem: add an EMP grenade when generating terrain.

Replace this line
https://github.com/CleverRaven/Cataclysm-DDA/blob/bcd1145b9461cacc537668e20c2d87c7ca522c3b/data/json/npcs/robofac/robofac_intercom/robofac_intercom_missions.json#L233

To this one
```
        "item": { "@": [ { "item": "corpse_generic_female" }, { "item": "grenade_emp" } ] },
```

This guarantees the appearance of the grenade and makes the claim that the doctor took the grenade with him true. And with ISSF = 1.0, instead of two grenades there will be three grenades, which is not critical.

**Comment by IdleSol** [comment]
<b>2. Third quest. Light retrieval</b>

<b>Problem</b>: If the player changes the world parameter: Item Spawn Scaling Factor (ISSF). Items may not appear:
- nanofabricator template (silicon photonics)
- nanofabricator template (UHMWPE)

The first item needed to complete the quest. Without it, the quest becomes impossible to complete.

The second item is required to unlock the HUB01 equipment upgrade. I don't know if there is an alternative way to unlock it. I suspect there isn't.

<b>To confirm</b>: set ISSF = 0.01 and take the quest. Go to the basement of the tower. Make sure the small wooden box is empty.

<b>The solution to this problem:</b> add the MISSION_ITEM flag

nanofabricator template (silicon photonics)

https://github.com/CleverRaven/Cataclysm-DDA/blob/442d063355f5ae5a546517815d522b08c0a96ec0/data/json/items/generic.json#L2039
```
    "flags": [ "TRADER_AVOID", "MISSION_ITEM" ]
```

nanofabricator template (UHMWPE)
https://github.com/CleverRaven/Cataclysm-DDA/blob/442d063355f5ae5a546517815d522b08c0a96ec0/data/json/items/generic.json#L2051

```
    "flags": [ "TRADER_AVOID", "MISSION_ITEM" ]
```

Make sure that these items appear regardless of the ISSF value.

P.S. I've been making changes to my version of the game. No errors occurred. Grenade and templates appeared at issf=0.01.
