### ISSUE TITLE
Bionics and Mutation. Remove auto letters

### ISSUE THREAD

**Issue by IdleSol** [CleverRaven/Cataclysm-DDA#71537]
### Is your feature request related to a problem? Please describe.

Improved gameplay

### Solution you would like.

I suggest disabling auto letters. At least for passive bionics and mutation.

**Comment by SariusSkelrets** [comment]
The auto letters got the benefit of not needing to manually assign letters to all that stuff. I prefer my active mutation to automatically use some obscure letter instead of none

A better solution would be allowing one of such letters be unassigned. Bionics in particular would benefit the most from that

I don't need half of the letters taken by power storage and their installation is usually early compared to the better stuff so they tend to take all the letters. Letters that you can't reassign if the new one is already taken

By the way, it would help if you defined "improved gameplay"

**Comment by IdleSol** [comment]
Does it make any sense to assign a letter for passive mutation/bionics?

If we're talking about active. I didn't suggest removing the ability to assign a letter. I'm suggesting removing the automatic assignment.

I prefer to assign letters that are comfortable to me. Rather than using the ones the game assigns.

>By the way, it would help if you defined "improved gameplay"

In terms of mutation and bionics management. The right letters on the right abilities. More order.

The second step would be to allow activation via the "use items" menu ("a"). But that would be a separate topic.

P.S. I apologize for the quality of the text. Deepl translate is used.

**Comment by fairyarmadillo** [comment]
Auto letters are good. Being able to optionally assign letters is better. Taking away auto letters and only having manual letters would be very annoying.
