### ISSUE TITLE
Aluminum items cannot be repaired using expected materials

### ISSUE THREAD

**Issue by Shockbound** [CleverRaven/Cataclysm-DDA#71556]
### Describe the bug

Aluminum items (e.g. aluminum bat) will only accept aluminum welding wire as a valid repair material, which is inconsistent with aluminum vehicle repairs and other metallic items.

### Attach save file

[The void behind the dryer-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14174062/The.void.behind.the.dryer-trimmed.tar.gz)

### Steps to reproduce

1. Gather aluminum materials from the list below:
- aluminum foil
- scrap aluminum
- chunk of aluminum
- 1L aluminum ingot
- aluminum brazing rod
- aluminum welding rod
2. Acquire a damaged aluminum item, such as an aluminum bat.
3. Activate a tool that that is capable of repairing the item from step 2, such as a makeshift arc welder.
4. Attempt to repair the item from step 2.

### Expected behavior

I expected that chunks of aluminum would be used to repair aluminum items because repairs for aluminum vehicles and other metal items require chunks.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/48227653/1a824d04-ee12-453e-9ab5-824f969e17d4)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/48227653/8d9e48d8-a6ab-475b-abca-15ff24ae84c2)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3930 (22H2)
- Game Version: 3706e56 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

It's strange that repairing aluminum only works with one type of aluminum welding ammo, as uses of welding ammo in other contexts consider all three types as viable for the task at hand.

**Comment by Karol1223** [comment]
This is intended. When I worked on aluminum I asked Kevin, and he said that it should not be possible to repair items with chunks or scraps. I am pretty sure that there was a reason I chose welding wire as opposed to brazing rods or welding rods, but it may also be that it's not possible to specify three separate items a material can be repaired with (that's why I'm not closing this as invalid - if someone wants to add C++ support to have multiple items be valid for repairs, be my guest)
