### ISSUE TITLE
Camera drones and overmap survey

### ISSUE THREAD

**Issue by tornikeo** [CleverRaven/Cataclysm-DDA#71564]
### Is your feature request related to a problem? Please describe.

[You **can** survey local landscape around using a commercial camera drone + an android app or a VR headset](https://www.dji.com/fi/camera-drones). 

So why don't we?

### Solution you would like.

Original approach (now scrapped, see below):
- New robot, `camera drone`. 
- As an item, it is UPS-charged.
- Upon activation you can `deploy it as a decoy` or `survey landscape`. 
We focus on second:
- `survey landscape` should require 90% or more charge level and and reveal some moderate amount OMTs around you.
- This action should take around 10-15mins and should occupy the PC for the duration (like crafting). 
- If PC gets disturbed, the drone should get lost or break after fall.
- else you get your drone back as an item, with low charge.
- It is assumed that PC uses their smartphone or (laptop) to extract data from drone - so having one should be required.

Current approach:
- Create the drone as an unmanned 1x1 vehicle, with drive-by-wires and rotors (done)
- Make sure it can fly up and down, just like a helicopter
- Allow 'attaching' your center of vision to the drone's chassis (or something similar)

### Describe alternatives you have considered.

Finding a laptop with an offline, highly-detailed google-earth maps to reveal an absurd amount of OMTs around you... but that'd be unrealistic. Right?

### Additional context

I hate wasps and being unable to see where I am.

**Comment by fairyarmadillo** [comment]
The code can almost certainly just be copied over from the tree_communion activity that plant and elf-a mutants get. It would be a matter of changing the area revealed from a forest to just tiles surrounding the player, with battery drain as appropriate. Bonus points if there's a proficiency for operating a drone, weather penalties, and bad things can happen to it, especially if the player can go and get it.

We don't really use the driving skill for much. That seems like it'd be appropriate for piloting a drone.

**Comment by Inglonias** [comment]
I like this idea a lot.

> Finding a laptop with an offline, highly-detailed google-earth maps to reveal an absurd amount of OMTs around you... but that'd be unrealistic. Right?

It's worth noting that something similar to this was proposed in #70353 (in that case it was a map of tall buildings for most of New England, which is something aircraft pilots would have) but it would lock the game up for several minutes while it generated overmaps, which was a major concern.

You can also download maps from some old-style lab computers, though that feature is very much no longer required considering how many other ways there are to map the immediate area.

**Comment by tornikeo** [comment]
@Inglonias What would be your thoughts about instead of making this into an a single-use item, instead make this camera drone into a foldable, 1 tile remotely controlled flying vehicle? I fee like that's an achievable thing, no?

**Comment by fairyarmadillo** [comment]
It would also not be a one use item. You would set it up and fly it around as an activity and then get it back at the end unless something interrupted you or it broke.

It would not be very useful just flying around in the local area because the reality bubble is stuck to the character. In fact it probably wouldn't be appropriate to do it that way at all as it wouldn't make any sense that it would be trapped within like 30 tiles of the player. You can try using an RC car if you want to see how limited this currently has to be.

It makes sense for the car because it's just a little toy with no cameras or anything. Not so much for a drone.

**Comment by harakka** [comment]
I'm in favor of the vehicle approach because there's the remotevehcontrol item and ROTOR, REMOTE_CONTROLS and ENHANCED_VISION vehicle flags. Should be pretty quick to slap together a test vehicle to see if this is doable with the functionality we already have in the engine.

**Comment by Inglonias** [comment]
I think that creating a remote controlled flying vehicle that can just fly around and do stuff in the reality bubble is easier than adding the ability for it to survey the overmap for you.

**Comment by harakka** [comment]
With ENHANCED_VISION you don't need anything special for surveying, just fly it up and and you get the same effect as player does when climbing higher up with binoculars in inventory.

**Comment by fairyarmadillo** [comment]
> I think that creating a remote controlled flying vehicle that can just fly around and do stuff in the reality bubble is easier than adding the ability for it to survey the overmap for you.

Yeah but it's also way worse. And what exactly would it do? It can't see far and it can't move far because the bubble is small enough that being able to do either would reveal the bubble edge. It also can't center the camera because then you wouldn't see zombies walking up and attacking you.

**Comment by harakka** [comment]
Either way of doing this requires some code changes, but if you can implement switching player POV to the drone vehicle when remote controlling, then almost everything else is already there in vehicle code. From a quick test, I think the only other thing missing is that remote control currently lacks support for going up and down.

**Comment by fairyarmadillo** [comment]
You can't do that for the reasons I outlined above, unless you're also going to code a dynamically reshaping and extending reality bubble that will follow the new vehicle but keep the player's own bubble intact.

I wouldn't even know where to begin.

**Comment by fairyarmadillo** [comment]
Drones don't just fly straight up from where you're standing IRL.

**Comment by db48x** [comment]
They certainly _can_ fly straight up and gain an elevated view of the surroundings, but I suspect the player would expect to be able fly them some distance. I think that a quarter mile is a common range, isn’t it? And usually the range is most limited by the radio’s broadcast power rather than the fuel or battery power on the drone. After the cataclysm there’s really no reason not to mod your drone for longer controllable range at the expense of draining the battery faster. On the one hand players may be disappointed if they cannot fly their drone more than 60 meters away, but on the other hand that very disappointment may make it more likely that multiple reality bubbles are supported in the future.

I’ve only glanced at the code, but adding reality bubbles around multiple locations (the player plus a drone, for example), might not be all that hard. There’s a bunch of nonsense, but ultimately it seems pretty simple. There is a single list of spawned monsters. The AI for all of those monsters is run once per turn. Then, it despawns any monster that is too far from the player. This removes it from the monster list, storing it in the overmap instead. When the player moves, monsters that are too far away are despawned (`game::despawn_nonlocal_monsters`) removing them from that list. Likewise, monsters that are now in range are spawned (`map::spawn_monsters`) adding them to that list.

So the only necessary change appears to be making those methods consider the range to two points (the player and the drone), instead. One complication is that monsters are handled in a coordinate system centered on the player. When the player moves left, all the monsters are shifted to the right so that the player is still at 0,0 in that coordinate system. That makes the current distance test easy, but complicates it if you want multiple bubbles.

Of course there may be other complications, and I don’t think it would be a good idea to have a single pull request that both adds drones and adds multiple reality bubbles. I say add the drone now and multiple reality bubbles later.

**Comment by fairyarmadillo** [comment]
> Of course there may be other complications, and I don’t think it would be a good idea to have a single pull request that both adds drones and adds multiple reality bubbles. I say add the drone now and multiple reality bubbles later.

I am telling you it straight up doesn't work. Have you ever tried to use a remote vehicle in this game? They're incredibly limited. I feel like I'm taking crazy pills.

Making them a foldable remote vehicle is at this stage a terrible implementation and would also block doing it properly via an activity. Doing it as an activity would also allow NPCs to do it as well, which would be a neat function for them.

**Comment by esotericist** [comment]
@fairyarmadillo i need to ask that you please dial back your tone; you're coming across as rather aggressive and demanding. and this is on top of some previous tone/communication style issues re: authoritative-sounding positions; you haven't been making good impressions lately.

in my opinion, a single tile vehicle is the right starting point. this gets you something that you can immediately start testing and using, even if it doesn't do everything desired, and can be iterated on with further improvements afterwards.

things of note:
*  we already intend to increase the reality bubble radius a fair bit. it's very like that's going to happen in this experimental cycle, following the branch for stable.
*  we already intend to have some degree of dynamic reality bubble adjustment, long term, to allow for things like sniping to happen at coherent distances
*  view centering can be solved independent of everything else, even if still constrained by the current reality bubble (for now)
*  being an activity is actually orthogonal to the device being a vehicle; remember we want npcs to be able to control vehicles, too. that would almost certainly be an activity, fundamentally.

**Comment by fairyarmadillo** [comment]
Sure thing.

**Comment by Inglonias** [comment]
My main concern with the vehicle implementation is losing track of the thing, and/or what happens if it runs out of power in mid air. Do we have code for airborne vehicles to fall to the ground in that case? I've seen carts make crashing noises forever and seriously lag the game out before in #56477 .

And as for losing track of the thing, fairy isn't exactly wrong about remote controlled vehicles being limited by the camera.

I also agree that this issue is very much unlikely to be the catalyst for multiple reality bubbles. Even if it were easy to implement (it's not, to put it lightly), we would have to deal with some astonishing performance issues.
