### ISSUE TITLE
[Xedra Evolved] The EOC "EOC_XE_GOT_A_SPELL_LVL" chance might be too low

### ISSUE THREAD

**Issue by Naadn** [CleverRaven/Cataclysm-DDA#71636]
### Is your feature request related to a problem? Please describe.

I have play 3 major mod (Magiclysm, Xedra Evolved and MoM) that use spell system at lot at same time, and have leveled tons of "spells". But for now I only occur that EoC to learn new Dreamer/Eater spell once. To learn those two classes' spell I basiclly have to do it the old way : looking for "spellbook"

I really want to learn new spells by PR#[69586](https://github.com/CleverRaven/Cataclysm-DDA/pull/69586)'s way. I hope the probability can a bit highter.

### Solution you would like.

Maybe change the probability form 1/16 to 1/10.

### Additional context

The only time `EOC_XE_QUEUE_LEVELING` happened is when I was Exercise, how? Isn't it suppose happen when sleeping?

**Comment by GuardianDll** [comment]
chance is this low specifically because there is still an option for reading artifacts presented
and this option would be presented until i adress all issues new system has - mainly inability (and inpractice) to use spells when they have low lvl.
I don't know why EOC_XE_QUEUE_LEVELING is run when you exercise, it's probably a bug, and it would be better to link it to character_wakes_up event anyway
