### ISSUE TITLE
Favorite item sprite in a pile.

### ISSUE THREAD

**Issue by S0ZDATEL** [CleverRaven/Cataclysm-DDA#71637]
### Is your feature request related to a problem? Please describe.

As of now, if you have more that one item on the same tile, it shows only the most recently added item (as far as I know), without checking for anything to select an item to display.

### Solution you would like.

It would be nice if an item marked as "favorite" by the player would have priority, so if you have a pile of items and one of them is favorite, it would be the one displayed.

### Describe alternatives you have considered.

Maybe add a special icon to the pile that shows 'there is a favorite item here". Just like we have a green plus sign to show there are more than one item, maybe we could have a similar icon for piles containing favorite items, display a star in the corner or something. Or maybe instead of adding a new icon just alter the plus one, for example, if there is a favorite item, the plus should be yellow instead of green.

### Additional context

Maybe it would be nice to mark favorite items even if they are not in a pile, just so the player have an easier time locating their dropped items.

**Comment by Inglonias** [comment]
Right now, favorite items have a `*` added to the front of their name. As far as I know, no other items have that. Therefore, if you filter by `*`, you will find favorite items very quickly.

**Comment by S0ZDATEL** [comment]
> Right now, favorite items have a `*` added to the front of their name. As far as I know, no other items have that. Therefore, if you filter by `*`, you will find favorite items very quickly.
> 
> I do like the idea of favorited items taking priority when rendering sprites, though.

Oh, I thought it was just an indicator and not part of the name. You know, like it wouldn't make sense to search for "++" for reinforced items or ">" for non-empty containers.

**Comment by noulolhaha** [comment]
IMO, adding * to the item's name only really helps when you already know roughly where the item is. One time I spent an IRL hour trying to find the backpack I dropped in a lab, because some piece of broken glass was rendered instead of my backpack.

Also, when there are no favorite items in a pile, it should render the biggest one, not the most recently dropped one, so bullet casings and what not don't render instead of larger, more important items, and so that if you don't make the habit of favoriting important items, you aren't out of luck.

I'm new to contributing to CDDA, but I'm going to try and add this. Wish me luck!
