### ISSUE TITLE
Review “Proboscis” mutation 

### ISSUE THREAD

**Issue by Coach-mdl** [CleverRaven/Cataclysm-DDA#71643]
### Is your feature request related to a problem? Please describe.

Proboscis mutation has a number of issues, one of which it shares in common with hummingbird beak, this being that nectar cannot cannot be consumed as picking the flower seems to override the option to drink from the flower.

There’s also a number of foods that aren’t considered liquid. This is mostly anything with the name “soup” attached to it, though there are some exceptions such as maple syrup, sauces and jams which while thick and may take some time, could be consumed. There’s likely many more as it’s an old mutation. I may open a separate discussion to put any offending food items I come across.

### Solution you would like.

To solve the issue of not being able to drink nectar, when the mutation is active, drinking from the plant should take priority. As a bug, picking the flower greatly offends me. Nectar itself also doesn’t seem to be liquid, as it couldn’t consume the nectar from the one flower I could drink from. I can’t remember what flower but it was a red flower like salsify in the Ultica tile set.

Many foods in the game aren’t considered liquid. We can assume any from the “drinks” category are safe but things such as woods meat soup and maple syrup cannot be consumed with the mutation. Raw eggs could be cracked and consumed too. Perhaps some of the soft fruits and other things could be impaled and slurped from the inside, maybe even live creatures if you’re brave enough. One far fetched suggestion could be to allow the food processor to liquefy food as an option for those with power. Mmmm, liquefied cheeseburger. Also don’t forget to add calories to nectar.

The proboscis mutation is a post thresh big mutation and genetic chaos really wants me to be a bug, so how about some more bug related things to the proboscis. Is it sharp? If it is, I have an overweight friend in my camp and I’m sure he wouldn’t mind if I “borrowed” a few of his calories. Drinking from corpses could also be nice. This only applies if it’s like a mosquito proboscis rather than a more peaceful creature. Proboscis could be left broad or it could be separated into carnivore and herbivores versions.

### Describe alternatives you have considered.

Another method could be to bring the nectar item back. It could even have some neat uses for things like beekeeping in the future.

NPCs not being able to craft fluids has forced me to be the chef this time.

### Additional context

Hopefully some of what I said is helpful. Maybe instead having a “drinks” section in crafting, there could be a liquid section. Not necessary at all though. Also I hope none of this came across as rude.

**Comment by fairyarmadillo** [comment]
I think proboscis is reasonable as a severe consequence of mutating, but the main thing that both mutations are intended to do (drink from flowers) makes no sense for a human-sized mutant. Even a tiny mutant would not be able to get an appreciable amount of sustenance out of a flower.

The ability to drink from flowers should be removed entirely. It could be added back for special triffid flowers, but certainly you shouldn't be able to waltz up to a bluebell and get anything out of it, no matter how your mouth is shaped.

Proboscis could also give insects access to an acid barf attack (like the Brundlefly), or serve as a gateway to being able to safely drink mutant blood from corpses like #70797 can. The idea that you're not quite sure what kind of mouth or diet you'll wind up with as an insect could be pretty interesting.

IMO we should nix hummingbird beak entirely. The mechanics of it don't make any sense at human scale, and unlike proboscis I don't see it offering anything interesting for the player to do. #70443 pretty much removes Bird's ability to rely on melee weapons, so their beak is extra important. Different beaks with different capabilities might be cool, but giving them one that forces a savescum is kinda wack.

We could also add a "SLURRY" tag to some solid foods that would make them drinkable via proboscis. Oatmeal, yogurt, that kind of thing. Crafting recipes to crack raw eggs into a glass or throw a bunch of meat and water in a food processor would be reasonable, too.

We've discussed giving Insect different "paths" post-threshold, but I'm not sure how @Venera3 wants to proceed there. Ideally I'd love to see it if insect could gain some kind of affinity with butterflies, ants, roaches, or bees, and the ability to do something interesting if they had taken or lucked into one of those mutually exclusive paths - maybe this would involve doing something outside of the typical mutation system. I'm imagining triffids ignoring a horrible butterfly mutant who shows up to drink from their huge flowers and pollinate for them, and it'd be cool if you could chill with the bugs like Apis does.

The ultimate dream would be using pheromones to induce bees or roaches to follow you around, because emerging from a manhole and unleashing a swarm of roaches to do battle with the zombies in your hometown would be hilarious.

**Comment by Venera3** [comment]
Yeah, the flower stuff is not really reasonable barring some *special* flowers for very special bees I swear I will get around to someday. On the other hand bot Hummingbird Beak and Proboscises are things that exist and could be the endpoint of mutations, restricting you to liquid food only in return for your, uh, mothy powers.

> Different beaks with different capabilities might be cool, but giving them one that forces a savescum is kinda wack.

Nothing ever forces you to savescum, and "oh no people will want to alt+f4" is not a counterargument to anything. Single mutations get to be downgrades, as long as they make sense for the category and are set up in a flavorful way.
Plus that tongue should be an aight manipulator, even if the grip is shit.

**Comment by fairyarmadillo** [comment]
If there's some corner case use for it then that's better, but using RNG to take away a major part of a character's toolkit and giving them an unpurifiable less than nothing in return as a "reward" for engaging in a system that takes many hours of IRL work, even if they do everything right, is not going to create a good player experience. "I didn't get what I wanted" is very different from "I can't fight monsters or eat food anymore."

**Comment by Venera3** [comment]
Don't do mutation attacks, limb attacks won't use the old system.
Go through limb-gated techs (with dummy ersatz vectors until those get limbed)./

**Comment by fairyarmadillo** [comment]
> Don't do mutation attacks, limb attacks won't use the old system. Go through limb-gated techs (with dummy ersatz vectors until those get limbed)./

I've done something similar in #70797 with fangs and vampire fangs. They're currently using integrated items that grant the techs through their item jsons via #70214 . I figured beaks would do the same thing, but if they're gonna replace the mouth part, maybe I should learn how that works.

Are fangs going to replace the mouth part? I can go that route there too.

**Comment by Coach-mdl** [comment]
I should add that the proboscis mutation doesn't cancel out other mouth mutations like fangs and mandibles. The wiki also says proboscis is a post thresh bug mutation, I'm not sure if you're supposed to get post thresh mutations from genetic chaos, please correct me if I'm wrong.

The views on nectar are reasonable, the only way I could see it being viable as a full food source is if you're tiny or drinking from particularly sizeable flowers (Megaflora mod when?). That being said a mood buff from it would make sense, bar the other special flowers you have in mind. It would give a reason to grow some flowers. Next I'll be getting mood buffs from flying in people's faces, crawling on them when they sleep and crawling all over their screens. I'll never be able to get through an open window again.
