### ISSUE TITLE
Milling is still broken

### ISSUE THREAD

**Issue by Montimorency** [CleverRaven/Cataclysm-DDA#71652]
### Describe the bug

No nutrition. See image (using wheat). 

### Attach save file

[Orleans-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14228472/Orleans-trimmed.tar.gz)

### Steps to reproduce

Tested on a windmill. 

1. Place a windmill. 
2. Add 10 wheat, barley, or other grain to the windmill. 
3. Mill. 
4. Meanwhile, make flour with the same crop(s) using a manual or food processor crafting recipe. 
5. Compare the output of the two methods. Milled products have near-zero calories and nutrition. 

### Expected behavior

Milled flour should have the same nutrition as crafted flour using the same inputs.

### Screenshots

![mill](https://github.com/CleverRaven/Cataclysm-DDA/assets/151707610/1852d961-bc2a-41a3-b47c-41281f871966)

### Versions and configuration

- OS: Windows
     - OS Version: 7 SP1
- Game Version: [74d1b75] [64-bit] 
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: 
     - Dark Days Ahead [dda],
     - Disable NPC Needs [no_npc_food],
     - Portal Storms Ignore NPCs [personal_portal_storms],
     - Bionic Professions [package_bionic_professions],
     - Alternative Map Key [alt_map_key],
     - Extra Mutated Scenarios [extra_mut_scens],
     - Blaze Industries [blazeindustries],

### Additional context

I see this was purportedly fixed a few months ago, but perhaps it came undone. 
https://github.com/CleverRaven/Cataclysm-DDA/pull/68676

**Comment by NthTech** [comment]
Was able to reproduce on 74d1b75, using a fresh character with no mods. Wheat milled in windmill resulted in 0 kcal flour which baked into 3 kcal flatbread, Wheat crafted in crafting menu with food processor resulted in 33 kcal flour which baked into 244 kcal flatbread.

Archive attached for additional reference.
[defaultTest-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14228679/defaultTest-trimmed.tar.gz)

**Comment by PatrikLundell** [comment]
/confirmed

- Spawned 10 buckwheat with about 450 kcal each (according to UI)
- Milled in windmill
- Debug waited
- Got killed by zombie while removing the flour (no interruption...)
- Reloaded and redid the first three steps
- Debug killed the blasted threat
- Looked at the flour and found it to claim to contain 3 kcal
- Debug spawned 10 more buckwheat and cut it up with a blender
- Saw that each flour was claimed to contain 30 kcal, which matches the original calorie content (since you get 15 flour per unit of buckwheat).
- Thus, the windmill output seems to be a factor of 10 off.
-
