### ISSUE TITLE
Old foods spoiling "soon!" hides more useful information.

### ISSUE THREAD

**Issue by MrHrulgin** [CleverRaven/Cataclysm-DDA#71663]
### Is your feature request related to a problem? Please describe.

Some (old) oatmeal can be spoiling soon as compared to fresh oatmeal, but that might still be two weeks away. It's far less useful to see "soon!" in the Consume item menu than it is to see how long the item actually has, especially when it's not actually that soon.

### Solution you would like.

Rather than showing "soon!" for all old foods, just show the actual time to spoil.

### Describe alternatives you have considered.

leaving it alone, and telling from context in the menu when (old) things will spoil.

### Additional context

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/6834262/6688762b-c40e-4f00-860a-55768ebff53b)

**Comment by fairyarmadillo** [comment]
I'm sure this has come up before. To some extent the Soon! is probably intentional, because you don't know down to the minute or even the day when a piece of bread is going to get moldy.

I think the way to go here would be to put a maximum on when soon! can pop up, so that the time left can never be more than like a week.

**Comment by kevingranade** [comment]
It is intentional that the exact time is not displayed. 
If you understand how the existing system works and have a cogent argument for when "soon" gets displayed,  feel free to pr it.
