### ISSUE TITLE
 The game crashes with the BombasticPerks.

### ISSUE THREAD

**Issue by AndruxaXD** [CleverRaven/Cataclysm-DDA#71690]
### Describe the bug

I tried to create a new character, there was an error about something with the perks 
( without the BombasticPerks mod the game works )

### Attach save file

N/A

### Steps to reproduce

N/A

### Expected behavior

N/A

### Screenshots

![Снимок экрана 2024-02-11 213735](https://github.com/CleverRaven/Cataclysm-DDA/assets/76068850/fc886a2c-f0f9-4699-97d4-a3ccb7e079eb)

### Versions and configuration

OS: Windows 11 Pro
OS Version: (23H2)
Game Version: https://github.com/CleverRaven/Cataclysm-DDA/commit/eb9cacd70e0a2b6ac996e9cf2d316c6f3ad339fd [64-bit]
Graphics Version: Tiles
Game Language: Russian [ru]
Mods loaded:
  "dda",
  "no_npc_food",
  "personal_portal_storms",
  "no_fungal_growth",
  "bombastic_perks"

### Additional context

[crash and debug log.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/14233251/crash.and.debug.log.zip)

**Comment by RenechCDDA** [comment]
This appears to be the same error as #71495. I'm looking into it.

**Comment by IdleSol** [comment]
I think I found the cause. Although I don't understand why it's causing the problem.

First of all, this problem is only on Russian localization. (Checked: English, Chinese (I think) and Ukrainian localizations. No problems.

Therefore, the reason is in the localization file.

I paid attention to the following lines:

```
#. ~ Mutation name
#: data/mods/BombasticPerks/perks.json
msgid "Easy Sleeper"
msgstr "Лёгкое засыпание"
```
and

```
#. ~ Mutation name
#: data/json/mutations/mutations.json
msgid "Practiced Sleeper"
msgstr "Лёгкое засыпание"
```

I assumed it was causing a conflict. But I don't see why it should cause one. It's a translation.

I can't in the local copy change the translation file. But I can change the line that requires translation.

https://github.com/CleverRaven/Cataclysm-DDA/blob/e79add682fa19d849623333a3b902d5b6f9da452/data/mods/BombasticPerks/perks.json#L238

```
    "name": { "str": "Easy Sleeper 1" },
```

After the change, the game launches with no errors.
