### ISSUE TITLE
Allow leather armor to be both plated and boiled.

### ISSUE THREAD

**Issue by cataclysmsurvivalist** [CleverRaven/Cataclysm-DDA#71757]
### Is your feature request related to a problem? Please describe.

While this would make the armor somewhat heavier, ultra-reinforced leather armor does have a basis in reality and is as historical as its two non-combined variants. Boiled, reinforced leather armor would be especially useful for a post-cataclysm world, given the steel and modern chemical processes needed to improve the leather are easier to come by, it would not be that much more cumbersome than non-upgraded leather armor, and it would serve as medium gear when neither light nor heavy would be preferrable.

### Solution you would like.

Allow the player to either create boiled, reinforced leather armor from scratch through a recipe that is a mix of both the boiled and the reinforced ones, or allow one to be upgraded using the ingredients missing from the other.

Also, while I am using boiled reinforced leather armor here to emphasize my point, a shorter title like 'medium leather armor' or 'tempered leather armor' for this hypothetical gear would also be preferrable.

**Comment by Zireael07** [comment]
Just to clarify, you're referring to _courbouilli_?

**Comment by cataclysmsurvivalist** [comment]
I did not have a singular type of leather armor in mind because I'm pretty sure a survivor could have the idea of making one even without a book on historical armorsmithing (_"I can boil leather to make it sturdy andI can reinforce it with metal to make it stronger, SO WHAT IF I DO BOTH AT ONCE"_) but if French armor is the best representative of the type, naming the combination of the two as such could be for the best.

Again, I would personally prefer if it didn't require a book recipe like most historical armor (and also if the name didn't break away from the 'leather' theme naming of the rest of the gear set) but it wouldn't bother me too much if it did require the manual.

**Comment by fairyarmadillo** [comment]
We have boiled leather armor already, which represents cuir bouilli, and I don't see how you could add anything to that which would be meaningfully more protective. It's already as bulky as armor can reasonably be before it starts slowing you down too much.

You're sort of describing brigandine, which is metal plates affixed to fabric or leather. The leather was not boiled when used for brigandine because its softness gave it better properties than a hard material would have. 

Our game uses canvas as the base material for brigandine, but if you want a leather version, that's what the armored motorcycle jacket, armored leather vest, and hardened versions of both of those are.
