### ISSUE TITLE
Redheads and Red Dye

### ISSUE THREAD

**Issue by sadenar** [CleverRaven/Cataclysm-DDA#71919]
### Is your feature request related to a problem? Please describe.

So I translate stuff and I did most of the Red hair settings so far interpreting it as "Red" as the kind of flashy, obviously artificial dye that pink, purple, green and blue already are meant to be that'd you expect a punk artist to die their mohawk with.

Except that today I remembered that gingers exist, and looking further into it, it doesn't seem we make it very clear whether this is actual flashing RED hair or somebody having the "natural" red hair belonging to the real world range of hair colors that black, white, gray, blond and brown are representing.

### Solution you would like.

Change all the current Red hair settings into Ginger, or Redhead as it seems in English it's contentious whether Ginger is derogatory or not.

Alternatively, create two categories, one for "natural" and one for "artificial" red

### Describe alternatives you have considered.

Keep it ambiguous, but I don't see this as a major change that will disturb much of anything.

**Comment by Standing-Storm** [comment]
Just shows how our experience shapes perception--as a redhead I never even considered that red hair in the character creator meant flashy artificial dye, I always assumed it was natural red hair (so another vote that it's ambiguous, from the opposite direction).

**Comment by PatrikLundell** [comment]
The hair colors you select on character creation all used to be (I don't know if it's changed since I created my latest character) ones that occur naturally, and so the redheads ought to be the natural color as well.

Now, if there's support for artificial coloring (beyond changing the natural one into another one occurring naturally) those probably should be worded in ways indicating that they're artificial (henna, vibrant red, etc.). A third set might be mutant coloring.

**Comment by MNG-cataclysm** [comment]
I suppose that the red hair trait exists in a state of superposition; it represents both natural and artificial coloring depending on what the player used to obtain it. Natural hair color is the natural red, while the dye gives a bright neon color.
