### ISSUE TITLE
few seeds in farm supply store 

### ISSUE THREAD

**Issue by ynemo** [CleverRaven/Cataclysm-DDA#71935]
### Is your feature request related to a problem? Please describe.

Curently we have one or few seeds per stack in farm supply store 
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/24881844/0dd128d0-bb71-4970-9010-4af33408c051)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/24881844/f32a4bd1-5e6b-4c2e-b2db-b3c3c48220dc)

### Solution you would like.

I suppose seeds shold be sold in some kind of packet. And there should be about 25-100 seeds in one packet.

**Comment by fairyarmadillo** [comment]
> I suppose seeds shold be sold in some kind of packet. And there should be about 25-100 seeds in one packet.

One "seeds" is already 25-100 seeds in most cases. It's enough to sow an entire tile, then pick out all the failures to let the healthy plants grow, not one plant. That's why you can get many crops from one planted tile and not just one.

I haven't been in a farm supply store, but I suspect the seeds there should be much more heavily weighted toward corn. It's not a garden supply store.

I've also read that seed corn from places like these IRL is not safe to eat, because it's already been sprayed with chemical fertilziers and pesticides. Is that true?

**Comment by ynemo** [comment]
> One "seeds" is already 25-100 seeds in most cases. It's enough to sow an entire tile, then pick out all the failures to let the healthy plants grow, not one plant. That's why you can get many crops from one planted tile and not just one.

sry i dont get what you just said. 1 seed is one plant in CDDA. How can you plant 25-100 plants in the first generation from one seed?

**Comment by fairyarmadillo** [comment]
> sry i dont get what you just said. 1 seed is one plant in CDDA. How can you plant 25-100 plants in the first generation from one seed?

This is incorrect. "Seeds" is a pile of seeds. A planted crop is not a single plant, but a few meters square patch of tilled earth filled with as many plants as will reasonably fit in it. That's why you get many stalks of wheat from a single planting, and not one. That is why seeds have descriptions like "A pile of dried whole oats, ready for planting.", and why the base seed item has a note in its description: "//": "Note that in most cases this item typically represents many seeds, enough to fill an entire tile with plants.",

See: https://github.com/CleverRaven/Cataclysm-DDA/pull/65924 etc.

**Comment by Consoleable** [comment]
Grocery stores are heavily looted, so it makes sense that farm supply stores are missing a lot of the expected contents. That said, it would be nice if there were at least a remote possibility of bulk seeds/kernels/nuts for potentially jumpstarting a farm, since that's a reasonable expectation from the overmap tile, and this is one of the rural tiles, which seem to have a characteristic of being slightly less ravaged.

**Comment by fairyarmadillo** [comment]
I think the general problem in the world would be less looting and more a lack of stuff on the shelves due to the supply chain being nonexistent for the last four weeks and probably not great for the last 3 months. We all remember how fast stuff ran out in 2020.
