### ISSUE TITLE
add foreign books exodii merchandise 

### ISSUE THREAD

**Issue by tornikeo** [CleverRaven/Cataclysm-DDA#71947]
### Is your feature request related to a problem? Please describe.

Knowledge is valuable. Yes, guns are valuable too, but there's absolutely no need to exodii **not** to snatch books from one of the worlds, and travel with them, learn stuff from it, and sell them.

We already have that with those nomad blueprints, so here's my suggestion on what we should add to their merch:

### Solution you would like.

Add obscure and unrealistic martial arts books, a very good candidate is **bionic martial arts**, for example. We should also add some books or journals about history of the parallel worlds (these should be mostly generated by AI).

### Describe alternatives you have considered.

Not doing this

### Additional context

I like exodii, but they should be more like interdimenentional garbage collectors, and should have tons of crap lyong around for sale. I'd like an opinion of @I-am-Erk  on this.

**Comment by fairyarmadillo** [comment]
We should not add any "AI" generated content to the game.

**Comment by tornikeo** [comment]
@fairyarmadillo 
Curious how youd even enforce that AI restriction, but sure, I guess. 
I don't get it then, how do players find the nomad blueprints useful if it's unreadable (I mean, it should be, based on how you described it, no)?

**Comment by fairyarmadillo** [comment]
> A simple printed pamphlet with clear illustrations and very few words describing how to make what appears to be a jumpsuit designed to survive the long-term wear and tear of exploring the apocalyptic wasteland, with a lot of storage capacity.  The directions do not offer much guidance beyond the plans themselves; this will take a little skill to interpret.  There seems to be room within the directions to make a simpler, lighter version, or a leather-reinforced version.

It's mostly just pictures.

**Comment by fairyarmadillo** [comment]
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/94415528/724b11e7-9cd4-4cfc-9b70-da3383dc1c62)
Here's a pattern for a dress, for instance, written in German. I don't speak any German but I could make this item using these instructions.

**Comment by tornikeo** [comment]
@fairyarmadillo Oh, well. That actually gave me a very good idea. See #71950 . I think that languages should be made into learnable proficiencies. This includes rubik's anglic too, although I don't know what it would take for him to spend time teaching you his language lol

**Comment by DoctorBoomstick** [comment]
I had an idea similar to this, but in place of books, they could offer up some pictures they’d snapped of different worlds while traveling. My only issue with making that a PR, and by extension, this is that there’s little reason, from what I understand, for the Exodei to have not just digitised any useful books possible. I don’t believe they’re an interdimensional dump truck lugging around everything they see; they’re the equivalent of taking what they need aboard a lifeboat and setting sail while the main ship sinks.

**Comment by IdleSol** [comment]
>I don’t believe they’re an interdimensional dump truck lugging around everything they see

They took bronze armor and weapons. It's useless to them. But useful for bartering in the new world. Which means they can take other things. The main thing is that these things must have value to be bartered.

Beads for the natives.

**Comment by fairyarmadillo** [comment]
Is it useless to them? Cyborgs can wear armor just fine.

**Comment by IdleSol** [comment]
They can. I hope I'm choosing the right words.

In a world with bronze, they didn't arrive naked. They must already have armor and weapons. We can even buy a sample firearm. Will they replace "modern" armor with bronze armor? Will they take bronze spears instead of rifles? Or for a simple comparison, instead of a steel spear?

**Comment by PatrikLundell** [comment]
Well, the Exodii don't need the bronze armor in our world, because there is better stuff available, but if they'd arrived in a neolithic society they definitely would have had use for it.

They have a fairly large life boat (or fleet of boats), but there's still limited space, so they bring only what's potentially usable. If they arrived at the bronze age world using more sophisticated equipment, some of that was probably destroyed, lost, or worn out, so they topped it up with the best the local environment could provide. The lower tiers of equipment is now ready for sale and replacement with the best the C:DDA world can provide (where reliable ability to use it in whatever world comes next is an important part in determining what's "best": a fantastic power armor that requires a particular non rechargeable power source wouldn't cut it, for instance).

I would expect the books you sell to the Exodii to be either uploaded to their brain banks (if containing knowledge) or read for entertainment, but not be brought over the next jump (books tend to be made out of organic materials as well, and so would be prone to damage anyway).

**Comment by tornikeo** [comment]
@PatrikLundell Hah - parallel world Ipads (made by pear inc.) with scanned books on them? 😄

**Comment by PatrikLundell** [comment]
That's something an Exodii might bring in its personal allowance, but I don't think they'd be willing to sell it. It would, after all, be a unique item, in the proper sense of the word.

**Comment by tornikeo** [comment]
I'm no professional in electronics, I just don't see how replacing a charging cable, given vast quantity and knowledge of electronics, should be considered an issue. It is, after all, an Ipad. If it weren't an Ipad, then yes, but the premise is that.

**Comment by PatrikLundell** [comment]
It's not the cable or brick, but the socket. I guess someone with enough equipment and expertise could create a plug that fits into a proprietary Apple socket, though.

**Comment by IdleSol** [comment]
>Well, the Exodii don't need the bronze armor in our world, because there is better stuff available, but if they'd arrived in a neolithic society they definitely would have had use for it.

That's a possibility.

That's the way I envision it. They arrived in the bronze world, but could not get enough material to cover all the available volume. So to avoid traveling empty, they took things with them to sell. Those glass beads for the natives. Not too bad to throw away, and if possible, they can be exchanged for useful things.

>If they arrived at the bronze age world using more sophisticated equipment, some of that was probably destroyed, lost, or worn out, so they topped it up with the best the local environment could provide.

This implies that Exodii cannot repair and create new equipment.

P.S. Organic materials and Exodi, this is too big a hole in the lore.

**Comment by PatrikLundell** [comment]
The Exodii can presumably repair and create equipment, but only if they have access to the raw materials. They probably can't get hold of iron from a bronze age world. If they are staying long enough in a world they might be able to establish mines and get the materials that way, but I don't think they stay that long before having to move on.

**Comment by db48x** [comment]
I rather like the idea. Maybe Rubik just has a handful of books that he acquired right before they left the previous world. He’s finished scanning them and he can either sell them to a local rube, or he can leave them behind when they all depart. Maybe a few of them are just literature. Make them all unique so that they don’t ever generate in random loot.
