### ISSUE TITLE
"Offense" score: strength matters too much?

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#72001]
### Is your feature request related to a problem? Please describe.

Currently during character creation you will hit an Offense of "Overpowered" with 12 strength and 8 dex, with no skills and no weapons (base survivor). This seems wrong.

### Solution you would like.

Obviously raw stats should play the biggest role, since they're static-ish. Skills should come second and starting gear should be last place in terms of importance - while starting with an ar-15 makes the early game much easier it doesn't teach you how to fight. Skills matter a lot, by 6 melee with Brawling I'd personally rate a 6 strength char stronger than a 14 strength char with no skills. 

The upper range of "overpowered" should probably be set such that it requires good skills and good stats (say an athletic football player or fencer) or inhumanly good stats (14/14 str/dex or >14 str etc)
What is our "average"? 0 skill 8 str survivor with no weapons? For a typical player that means zombie food.

### Describe alternatives you have considered.

Character "poweredness" estimation is pretty bad as a whole, for example Irreparable is worth the same amount of Lifestyle as Truth Teller, so in our current estimation a character with Truth Teller has just as powerful a Lifestyle as one with Irreparable, despite that being blatantly not the case.

**Comment by fairyarmadillo** [comment]
All of the power scaling in chargen is wonky IMO. It would be better if each skill/stat had the following, which could be appended to their description while they were highlighted in chargen:

Stats:
0 - Unusable
1-2 - Extreme Inability
3-4 - Very Bad
5-6 - Poor
7-8 - Untrained
9-10 - Average
11-12 - Practiced
13-14 - Adept
15-16 - Very Good
17-18 - World-class
19-20 - Unparalleled

Skills
0 - Never Tried
1-2 - Basic Familiarty
3-4 -  Working Knowledge
5-6 - Professional
7-8 - World-class
9-10 - Master

These numbers would help players understand the kind of character they were building, rather than an arbitrary measure of over/underpowered, which is something that isn't really super meaningful in a game this open-ended. If I want to make Michonne from The Walking Dead, I can look at these descriptors and come up with something like

Strength 12 - Practiced
Dexterity 14 - Adept
Perception 10 - Average
Intelligence 10 - Average

Blades 5 - Professional
Dodge 4 - Working Knowledge
Survival 3 - Working Knowledge
Social 5 - Professional (She was a lawyer before the outbreak!)
Unarmed 3 - Working Knowledge
Marksmanship 3 - Working Knowledge
Driving 1 - Basic Familiarity
Food Handling 2 - Basic Familiarity

Introvert
Light Step
Parkour Expert
Fleet-footed
Terrifying
Tough
Outdoorsman
Bad Temper
Indefatigable
Nomad

That's a rather powerful character, but _I know that._ I knew going in I wanted to make a badass wandering swordfighter with few weaknesses. Instead of the game suggesting to me that I'm going to somehow ruin the experience for myself, it instead helped me figure out what Michonne's stats would be and guided me toward making a reasonable approximation of the character I had in my head.

I assume most people are making up their own characters or just statting themselves, rather than recreating fictional ones, but adding these descriptors would serve as better guidelines than the present system of over/underpowered imo. If we don't want to get rid of those over/underpowered readouts, they'd still be helpful for players to know just what kind of experience they were setting themselves up for. It would also help players understand how powerful certain mutations or bionics were.

**Comment by anoobindisguise** [comment]
> In that light, how would you concretely implement the assertion

When I said this I mean mostly in terms of "how many zombies can I kill by standing in one spot holding down tab until I die". 14 strength obviously has a huge amount more potential than high skill low stat guy even though they perform similarly on day 1.

That said the number of skill points that are worth 1 stat point is probably like. Somewhere between 5-10, in terms of overall difficulty rating. It's difficult though because they're incomparable quantities, one can change and the other cannot. I think it'll be a lot easier once we implement strength training, since "weeks to get +2 strength" and "weeks to get +5 melee skill" become more comparable of values.
