### ISSUE TITLE
[Inline EOC] Automatically assign an ID to inline EOCs

### ISSUE THREAD

**Issue by PipeYume** [CleverRaven/Cataclysm-DDA#72017]
### Is your feature request related to a problem? Please describe.

I noticed that many inline EOCs are only used within one EOC and are not called in other EOCs. 
In this case, specifying an ID for inline EOCs doesn't seem necessary.

So I wonder if It is possible and appropriate to automatically assign an ID to inline EOCs?
By this way, when writing some EOC-related usage, one only needs to write:
```
"condition": ...
"effect": [...]
```
without having to manually define an ID each time.

### Solution you would like.

If the inline EOC has an ID, then just load that ID. ( this EOC can be used in other EOCs)

If the inline EOC doesn't have an ID, then automatically assign a particular ID. ( this EOC  is only used in this specific context and not intended to be called elsewhere, so you don't need to consider its usage outside of this context )

This particular ID can be `INLINE_[the id of parent eoc]_[inline EOC count]`
eg. If the parent eoc is `EOC_TEST` and it has two inline eocs inside.
Then the assigned id of these two inlined eocs are "INLINE_EOC_1", "INLINE_EOC_2".

Changing the order of inline EOCs only affects queued inline eocs since they are executed several ticks later.
Therefore, a reminder is needed to specify the EOC's ID in queue_eocs/queue_eoc_with.

**Comment by Ramza13** [comment]
So I did consider this quite a bit when creating them.  

Best I can remember it there was a problem with queued eocs.  If you have the EOC id "AUTO NAMED 1" queued up somewhere or saved anywhere in another command to use it then any change at all to the EOC that would cause it to be now named "AUTO NAMED 2" will cause issues.  

It might be possible to allow this for EOCs that are never queued and always used right away, I don't remember if there are any other issues I encountered and the basic structure has changed since I first considered the issue.  Just something to consider for any solution
