### ISSUE TITLE
Cooldown on NPCs repeating barks

### ISSUE THREAD

**Issue by fairyarmadillo** [CleverRaven/Cataclysm-DDA#72027]
### Is your feature request related to a problem? Please describe.

It would be really nice if NPCs would limit repeating certain barks too often. Specifically the "excuse me you're in my way" gets repeated way too often if you have two or more NPCs set to follow you at 2 or 4 paces.

### Solution you would like.

Even if there was just like a 20 second cooldown on saying it that kicked in for a while after the second or third time, it would reduce a lot of noise clutter. I understand that the NPC is complaining about new pathing problems each time, but logically a person would probably space their complaints out a bit.

### Describe alternatives you have considered.

N/A

**Comment by PatrikLundell** [comment]
The base problem is that the pathing frequently doesn't reevaluate the path when the PC or other companions are in their way even when there are perfectly valid paths and target locations available.
Another problem is that they do block each other and won't let them through when it would make sense for them to do so (it doesn't make sense when the complainer complains because it insists it want to hog the occupied tile for itself).
