### ISSUE TITLE
Makeshift pot not sutible for carrying water

### ISSUE THREAD

**Issue by Bullk9ng** [CleverRaven/Cataclysm-DDA#72110]
### Describe the bug

Cannot collect water with a makeshift pot (Level 1 containing quality).

### Attach save file

[Mullan-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14467015/Mullan-trimmed.tar.gz)

### Steps to reproduce

Collect water from a shallow pit in the ground which contains water using a makeshift pot.

### Expected behavior

Was hoping I could collect water with a makeshift pot (Level 2 boiling quality) for boiling. 

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Debian; Description: Debian GNU/Linux 12 (bookworm); Release: 12; Codename: bookworm; 
- Game Version: 9eaa5d4 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by PatrikLundell** [comment]
You've misunderstood the situation.

The reason you can't fill the pot in your inventory with water is that it's not a closed container, so its contents will be spilled when placed in it.
In order to use an open container (like a bucket and, of course, your pot) to carry liquids you have to wield it first.

I loaded your save, wielded the pot, and successfully scooped up water into it.

**Comment by Bullk9ng** [comment]
Ah! Great, thanks for that PatrikLundell.
