### ISSUE TITLE
Construction uses all usable components instead of choosing one

### ISSUE THREAD

**Issue by SSpook** [CleverRaven/Cataclysm-DDA#72182]
### Describe the bug

When constructing stuff from the construction menu all different kinds of components are consumed for a single construction instead of just using a single type of item.  This can lead to a lot of wasted materials depending on the recipe used.

### Attach save file

[Debugga-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14492281/Debugga-trimmed.tar.gz)
Cancel construction, notice materials obtained.

### Steps to reproduce

1. Find a construction recipe with multiple possible components, for example "Build Palisade Wall".
2. Obtain materials for the construction,for example 3 logs and a steel chain.
3. Obtain an alternative components usable for the recipe, for example a barbed wire, 2 short ropes, 3 short vines.
4. Start construction.
5. Notice how all available kinds of materials are used up to the amount used in the recipe, in this case only a short vine left unused.
6. (Optional) Cancel the construction and find the materials used.

### Expected behavior

Expected to use only one type of material.
Expected to be able to choose which material to use. 

### Versions and configuration

Game version: 0fa4b09

### Additional context

An error message pops up when finishing "Start Vehicle Construction" recipe with multiple materials, consuming one of all the materials and no vehicle appearing.

**Comment by PatrikLundell** [comment]
/confirmed

- Loaded the save
- Looked at the ground beneath the character and found nothing.
- Cancelled construction and saw a bunch of construction materials appear beneath the character's feet.
- Brought up the construction menu and saw that all items alternatives for the palisade fence was present.
- Looked at the stuff at the characters feet and saw it seemed to match the set of alternatives.
- Started construction and saw the pile of stuff at the character's feet disappear.
- Interrupted construction and verified nothing remained at the character's feet.
- Cancelled construction and again got the materials back.

I believe it's a new behavior both to get materials back when cancelling construction and to consume all alternatives on construction. Also, not asking for which alternative to use in construction is new.

I also checked a recipe (bird food) by spawning two alternatives (barley and bread), dropping both on the ground and created bird food. In this case I was asked to make a choice (bread), and when the crafting was done the alternative (barley) remained on the ground, so the issue seems to not affect crafting.

**Comment by PatrikLundell** [comment]
Thanks for that investigation. You are correct, and I have screwed up the code when I changed it to avoid used containers.
It turns out the function call that was replaced by the "same" call was a version that has item selection built into it, while the one used instead doesn't.
I'll get on to try to fix it.
