### ISSUE TITLE
Items dropped onto a tile containing a container containing such items should be auto-inserted

### ISSUE THREAD

**Issue by XygenSS** [CleverRaven/Cataclysm-DDA#72267]
### Is your feature request related to a problem? Please describe.

In my static base, I often use containers to better organize loot & to circumvent the 4096 items per tile limit. For example, I have a large metal box named 'Electronics' where I store all my electronic crafting bits, like circuit boards and amplifiers.

The problem is that, as I accumulate more loot, occasionally I have to do a little bit of clean-up and insert new items into their respective containers. There are no ways of automating putting items into containers.

### Solution you would like.

If an item is dropped onto a tile, it should look for existing containers that already contain more of itself. For example, a cotton scrap should look for containers containing cotton scraps.

If there is an eligible container with volume and weight limit left over it should auto-insert into that container.

Otherwise the item should simply be stored on the tile, as per usual behavior.

This should also work when sorting out loot with zone-action.

### Describe alternatives you have considered.

If it is intended that you need to put some conscious effort into keeping your loot-pile in an orderly and organized fashion, I propose making such function an automated process that functions much like a zone-action instead of mandating so many button-presses from the player. That way you only need to invest *ingame-time* into organizing your base instead of *irl-time*.

**Comment by PatrikLundell** [comment]
Changing the dropping behavior is NOT a good approach, both because inserting items into containers should take additional time (which can be lethal in some cases), and there are also cases where you don't want to add more to a container for one reason or another (such as a container of stuff you want to carry with you, and thus both may want to keep the weight down and to retain free space for additional loot).

That doesn't mean I don't want a good way to add stuff to containers, just that the default behavior shouldn't be changed.
A zone parameter might be useful:
- No container related activity: Current behavior
- Top up containers: Would add loose items moved to the zone into containers already containing that kind of item until full (and then continue on to the next container, if present).
- Merge container contents: As top up containers, but also move the contents out of source containers into the containers to top up, leaving the empty source containers behind for potential sorting into the empty container zone. There are a number of potential pitfalls here:
  - The current stupidity of moving containers containing the target item into existing containers of the item (currently afflicting pick up of e.g. bags of salt).
  - Exclude sealed containers: You don't want to break seals for this.
  - Date of expiration for food is a problematic case.
  - This can take extremely long time, as emptying a container into another isn't modeled, but instead you move one item at a time (e.g. 100 units of salt), so sorting out the stuff resulting from looting a dozen homes can take days.

Note that the above doesn't address the case of tossing different somewhat similar kinds of stuff into a common container.
