### ISSUE TITLE
Ocular Zombies have an anomalously high difficulty rating of 120

### ISSUE THREAD

**Issue by Inglonias** [CleverRaven/Cataclysm-DDA#72276]
### Describe the bug

Ocular zombies (added in #70749 ) have an abnormally high difficulty rating of 120, likely due to its VERY high sight range.

### Attach save file

N/A.

### Steps to reproduce

Spawn an ocular zombie or look at it on the [Hitchhiker's guide](https://cdda-guide.nornagon.net/monster/mon_zombie_ocular)

### Expected behavior

A difficulty level that is somewhat analogous to the monster's actual threat level 

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.3155 (23H2)
- Game Version: 7d3234e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Inglonias Scenarios and Professions [Inglonias_Scenarios]
]

**Comment by Maleclypse** [comment]
Isn't there a difficulty override field?  Or did y'all discuss that in discord?

**Comment by Inglonias** [comment]
...is there? That would make my life a lot easier.

**Comment by Inglonias** [comment]
We have the ability to add to the difficulty rating. It is unclear if we can put a negative number there, and it is also unclear to me what effect the PR will have on the calculated difficulty.

**Comment by Inglonias** [comment]
I just tried it locally - it appears that using a negative number in the `diff` field for a monster does nothing.

**Comment by Alm999** [comment]
It must be noted that currently "ocular zombies" also have 7 in melee **and** 7 in dodge. Oh, and some token armor coupled with above-base speed (80 instead of 70). Given that this upgrade is the first tier (basically, any regular zombie can turn into one), I'd say these are very dangerous in early game. Maybe not the "zombie hulk" level of danger, but still.

I'd say they are somewhere "smoker zombie" level of danger.
