### ISSUE TITLE
Standing lamp causing power outages

### ISSUE THREAD

**Issue by BlueDragonFire** [CleverRaven/Cataclysm-DDA#72272]
### Describe the bug

Attaching a standing lamp to your power grid will, at random, cause a power outage with ALL other electrical appliances it is attached to. For example, connecting a battery to a freezer and connecting the freezer to a lamp, once you turn it on and it triggers, it will turn off both the lamp AND the freezer.

Usually this happens when restarting the game, savescumming, or when walking far enough away and then coming back to it. My setup, in particular, is also on the second floor of a building in case that matters.

### Attach save file

[Warren City-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14547845/Warren.City-trimmed.tar.gz)

### Steps to reproduce

1. Create a standard power grid.
2. Attach a standing lamp to the grid or another appliance and turn it on.
3. Savescum, save & quit, or walk away from the square you are in until it disappears from the minimap.
4. Come back and the lamp and anything it is connected to should be off

### Expected behavior

The lamp should not deactivate either itself or other appliances

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Linuxmint; Description: Linux Mint 20.3; Release: 20.3; Codename: una; 
- Game Version: dd1adff [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    No Skill Rust [perfect_memory]
]

**Comment by pwalsh0** [comment]
Is this what makes all my npcs stop reading as well?

**Comment by BlueDragonFire** [comment]
> Is this what makes all my npcs stop reading as well?

I have no idea on that one, unfortunately

**Comment by PatrikLundell** [comment]
@pwalsh0: Check whether your characters are no longer lit up by the lamp(s) they're supposed to be lit up by. If the lamp(s) is off, this may well be the same issue.

There have been issues with companion lighting on different Z levels where checking lighting failed because the lighting cache didn't include that Z level (I believe that was reverted to not check lighting when 3D view became mandatory, though). This means there may be other reasons for your issue, so you ought to check it.

I've looked at the save and saw that the fridge and freezers were turned of, as well as the lamp, but the charging station was still active. Turning them back on, wandering away beyond the reality bubble (along the street to the south) and back again did not disable anything, but that only means it didn't fail this time and that I'm unable to confirm it.
Also tried to wander off to the NE, but, again, the error didn't occur that time either.

**Comment by BlueDragonFire** [comment]
Checking my medical menu does not show the "Lit Up" status like it does when holding a flashlight, but I'm still able to read and craft just fine.

Didn't even know the fridge was off, thanks. Aside from that, I have since connected the overhead light directly to the batteries using an extension cord. Since then, this bug has basically disappeared. I'm not sure why that is, but I'm going to take a shot in the dark and say it may not be the lighting cache or Z level that is the problem, though I could very well be wrong.

For now, though, I haven't had an outage since I connected the lamp directly to the batteries so that is probably an important note.

**Comment by PatrikLundell** [comment]
I have an unsubstantiated guess that it might have something to do with different things being in different submaps.

An overmap terrain tile is the unit the player sees on the overland map, which is 24*24 submap tiles. However, the reality bubble operates with submaps, which are 12 * 12 submap tiles, and there are 2 * 2 of those within each overmap terrain tile, so your "base" gets loaded into the reality bubble in a piecemeal fashion. The appliance code has to handle that is some way, and it seems to usually succeed, but not always.
