### ISSUE TITLE
[Magiclysm] Nature's Bow/Improved Nature's Bow will not reload

### ISSUE THREAD

**Issue by MoonlightKitty26** [CleverRaven/Cataclysm-DDA#72307]
### Describe the bug

For whatever reason, attempting to reload the bows with arrows does nothing, thus making them useless. 

### Attach save file

[Gerton - Copy - Copy - Copy - Copy-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14551738/Gerton.-.Copy.-.Copy.-.Copy.-.Copy-trimmed.tar.gz)

### Steps to reproduce

1. Attempt to reload either bow (Normal variant is already summoned in the save)
2. Select arrow type 

### Expected behavior

The bow should be reloaded and ready to fire, and one arrow is removed from the player's inventory as all ammo does.

### Screenshots

![Screenshot (124)](https://github.com/CleverRaven/Cataclysm-DDA/assets/136929186/65d53318-6a54-487f-8b6b-252bed3fd91d)
![Screenshot (125)](https://github.com/CleverRaven/Cataclysm-DDA/assets/136929186/9db1305c-b3ad-4e3d-a1db-60da5e195a13)
![Screenshot (126)](https://github.com/CleverRaven/Cataclysm-DDA/assets/136929186/6553bb63-3238-45f5-b5f9-f1a4cc31215d)
![Screenshot (127)](https://github.com/CleverRaven/Cataclysm-DDA/assets/136929186/45780383-82bf-44bb-b8de-1f2775fd231e)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4046 (22H2)
- Game Version: 03b2540 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mythical Martial Arts [MMA],
    <color_yellow>Mythical Martial Arts - Mods Extension</color> [MMA_Mods_Extension],
    Bombastic Perks [bombastic_perks],
    Magiclysm [magiclysm],
    Magiclysm Revamp and Additions [magicrevamp],
    Miscellaneous Magiclysm Expansions [demon_spider_a],
    Magiclysm No Class Limit [magiclysm_no_class_limit],
    Aftershock [aftershock],
    Xedra Evolved [xedra_evolved],
    No Bionic Slots [no_cbm_slots],
    Mind Over Matter [mindovermatter],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Extended Freeform [Extended_freeform],
    Japanese Folklore [Jap_folklore]
]

**Comment by osuphobia** [comment]
Bows and slingshots, with the flag RELOAD_AND_SHOOT, work in a different way from guns.
Bows do have pocket property restricted to arrows, but arrows are not held in the "magazine" of a bow, instead you automatically take out an arrow from your quiver every time you shot.
Trying to reload a bow in advance is a waste of effort now, at least for the PC. NPCs do reload arrows to the "magazine" aheadly.
Repeating crossbow, as an exception, doesn't have the flag RELOAD_AND_SHOOT, so it works in the same way as a regular gun.
There were discussions https://github.com/CleverRaven/Cataclysm-DDA/issues/71819 about this topic, but the change has not yet been confirmed and implemented.

For druid_recurve bow, the only difference is that it has the flag NO_UNLOAD, so pressing `f` and canceling the shot will leave the arrow in the "magazine" rather than putting it back to your quiver. Loaded the save, it works as intended.

**Comment by marilynias** [comment]
> Bows and slingshots, with the flag RELOAD_AND_SHOOT, work in a different way from guns. Bows do have pocket property restricted to arrows, but arrows are not held in the "magazine" of a bow, instead you automatically take out an arrow from your quiver every time you shot. Trying to reload a bow in advance is a waste of effort now, at least for the PC. NPCs do reload arrows to the "magazine" aheadly. There were discussions #71819 about this topic, but the change has not yet been confirmed and implemented.

Didn't even know that you could "reload" bows. Does it make sense to hide the reload option for bows from the player (if at all possible)?
I would agree with the issue that its confusing that reloading the bow is an option in the menu, but you are not meant to manually reload it.

**Comment by osuphobia** [comment]
> > Bows and slingshots, with the flag RELOAD_AND_SHOOT, work in a different way from guns. Bows do have pocket property restricted to arrows, but arrows are not held in the "magazine" of a bow, instead you automatically take out an arrow from your quiver every time you shot. Trying to reload a bow in advance is a waste of effort now, at least for the PC. NPCs do reload arrows to the "magazine" aheadly. There were discussions #71819 about this topic, but the change has not yet been confirmed and implemented.
> 
> Didn't even know that you could "reload" bows. Does it make sense to hide the reload option for bows from the player (if at all possible)? I would agree with the issue that its confusing that reloading the bow is an option in the menu, but you are not meant to manually reload it.

Reload hotkeys let you choose the default set of ammo for your RAS weapons, banning hotkeys will make it a hell, you need to choose which arrow to shoot every time. Since RAS weapons have already been banned from auto-re-aiming due to an unsolved problem, no one will use bows then :(

I'm trying to port over solutions from CBN, RAS weapon issues are solved properly there.
