### ISSUE TITLE
Alcohol wipes are too dense

### ISSUE THREAD

**Issue by bveuille** [CleverRaven/Cataclysm-DDA#72343]
### Is your feature request related to a problem? Please describe.

Currently, I can fit 200 alcohol wipes in a single prescription bottle, for a total of 0.20L and 1.00kg. This means that the alcohol wipes have 5 times the density of water, which seems excessive.

### Solution you would like.

I don't have any physical alcohol wipes to measure, but I'd say like anything organic they should have about the same density as water. Keeping the current weight, this would mean multiplying the volume by 5, from 5g/1ml to 5g/5ml per wipe. I don't think the weight should be reduced, it's already very small.

**Comment by oosyrag** [comment]
My Clorox wipes I happen to have on hand says 75 wipes/559g, or 7.45. Folded one up into a rectangle about 1cm/2cm/5cm, so about 10ml, without smooshing it hard enough to make a big mess.

Google says rubbing alcohol density is 0.785 g/mL, so numbers seem to check out. I'm hesitant to make the PR to increase weight/size of a common item like this though since I feel like it has the potential to cause a great disturbance in existing saves. Exploding pockets and shelves!

**Comment by bveuille** [comment]
Thanks for your work !
