### ISSUE TITLE
[MoM] Exodii Psychics

### ISSUE THREAD

**Issue by lapis413** [CleverRaven/Cataclysm-DDA#72376]
### Is your feature request related to a problem? Please describe.

The Exodii are other survivors, ones who travel from world to world while ensuring their brains stay intact in their metal shells; there's no reason some of them couldn't be psychic. 

### Solution you would like.

They might be an alternate source of crystals and dust, as well as recipes making use of them (they probably know how to make the dust potions, but they're unlikely to have figured out matrix tech).

Additionally they may have figured out some additional powers, in particular anything having to do with bionic power and electrokinesis, but they could be another source of powers you can only study, rather than stumbling across normally. Maybe they could also help teach you to accelerate the learning process (as it can be a bit slow under the new system if you have enough paths)

### Describe alternatives you have considered.

The Exodii not having any psychics, or them existing but not wanting to talk to you.

**Comment by PGR-14** [comment]
Perhaps they know about it & can tell you some lore, but they're in other places, where they're more useful

**Comment by Standing-Storm** [comment]
> particular anything having to do with bionic power and electrokinesis

This was definitely my idea for any powers interacting with bionics, since no one else would know them. 

There have been repeatedly talks in the planning stages of the Exodii sorting you into essentially "trust tiers" that determine how willing they are to work with you and what missions they give you, and I had a similar idea that the Exodii would sort psions into threat tiers based on their path and power within that paths--being very wary of Nether Attunement effects, the Exodii would mostly stick to lower-Difficulty powers. The tier system hasn't yet been implemented, though. 

Also, Rubik wouldn't be a psion, so there would be some fun interactions there since a theoretically Exodii psion wouldn't speak English (and telepathy doesn't cross language barriers), so you'd have to figure out how to get your point across to someone who speaks Finno-Korean or Modern Standard Khazarian or something.

**Comment by andrewhr** [comment]
Just as a quick note, IMO psionics seems a more "plausible" think for the "brains in a jar" vibes, at least with how current CBMs work. I.e. "keep the brain, so you're still somewhat human, so you still somewhat interact with Nether or whatever makes psionics possible". That makes them more psionics heavy than suggested in this thread, I know, so sorry for the little rambling / derail :)

**Comment by lapis413** [comment]
> Also, Rubik wouldn't be a psion, so there would be some fun interactions there since a theoretically Exodii psion wouldn't speak English (and telepathy doesn't cross language barriers), so you'd have to figure out how to get your point across to someone who speaks Finno-Korean or Modern Standard Khazarian or something.

This is an interesting point; telepathy can't cross language barriers, but if anyone developed some method of communicating regardless of that, it would make sense for that to be an Exodii telepath. Having them be wary of psychics is fun, and does help address the question of "why isn't every one of them psychic"
