### ISSUE TITLE
Full-screen android issue

### ISSUE THREAD

**Issue by Srcwya** [CleverRaven/Cataclysm-DDA#72399]
### Is your feature request related to a problem? Please describe.

![Screenshot_20240314-225717~2](https://github.com/CleverRaven/Cataclysm-DDA/assets/160199087/0f65278e-e493-4bde-8123-6ab5d5e992f1)
The android buttons are necessary for opening the keyboard.

### Solution you would like.

A simple deadzone where the game does not register your touch
![Screenshot_20240315-003824~2](https://github.com/CleverRaven/Cataclysm-DDA/assets/160199087/494ee287-1f4b-47be-acb3-9bf1e81bbe36)

### Describe alternatives you have considered.

Workaround i found currently inside the game. Using one finger on screen by quickly tapping and holding, and another finger scrolls the android buttons
![Screenshot_20240315-003824~3](https://github.com/CleverRaven/Cataclysm-DDA/assets/160199087/6d89ba96-9f89-4105-bd5a-b292ae74622d)

**Comment by Srcwya** [comment]
Forgot to mention, doing the workaround activates the "zoom out" gesture

**Comment by katemonster33** [comment]
this seems pretty doable. we will probably do the dead zone thing on all 4 screen edges. maybe i can do another change i was thinking - swipe up from bottom edge to open the keyboard, ive seen some other android apps do that.

**Comment by Srcwya** [comment]
Its better the option between the deadzone our your idea so everybody gets satisfied

**Comment by oosyrag** [comment]
Are there any leads to get non full screen working/fixed??

**Comment by HudsonMC16** [comment]
Linked commit doesn't appear to fix this issue. If I'm understanding this correctly, this issue was referencing the behavior of the android keyboard when using OS gesture navigation. In order to bring up the keyboard, it requires two "back" gestures and both are registered as swipe inputs to the game (moving the character). I can confirm this is still an issue in the latest experimental release.

**Comment by oosyrag** [comment]
Reopening - Feature request is for an activation deadzone for the on screen joystick, which does not currently exist. (Not to be confused with the existing joystick deadzone size setting, which is the amount the joystick needs to be moved before triggering an input)

Alternative solution currently available: Turn off force fullscreen - the softkeys will always be available without swiping. This option is currently only available on first run - clear the app data cache or reinstall.

I would also eventually like to be able to call the on screen keyboard by other gestures, such as two finger tap, but I'll open another issue for that some other time.

**Comment by katemonster33** [comment]
My mistake, I mixed this up with a different issue. We can reopen but I feel there is some risk involved with it, just because we haven't done something like this before and Android represents a very wide array of hardware and weird use cases. Now that force fullscreen is no longer needed to play the game, I think we need some more words on why exactly this is needed beyond just it being a "nice to have" thing.

**Comment by oosyrag** [comment]
Can't feature requests be nice to have things?

**Comment by katemonster33** [comment]
Of course, that's why I said we can reopen it, I am just explaining what would make me personally interested in taking on this task.

**Comment by HudsonMC16** [comment]
Yeah, maybe this issue is too specific, in it being a feature request at all. To me, the issue is calling the android keyboard is currently not implemented in an ideal manner. Even with force full screen off, if you're using gesture navigation (default in all recent versions of Android), you still must swipe at least once and that swipe registers as input to the character, to just bring up the keyboard. I'm not an android dev, but just based on my observations, it is possible to bring up the keyboard at will, because the app can bring it up when a text entry field is present? Making that a mappable option in the keybindings menu would be a reasonable first step, I think?
