### ISSUE TITLE
Please fix sugar

### ISSUE THREAD

**Issue by Montimorency** [CleverRaven/Cataclysm-DDA#72421]
### Describe the bug

Some time ago, sugar was reduced in weight from 5g to 2g, in an attempt to improve its density. But the calorie count was never reduced from 19 to 8, and other sugar-linked bits of code such as the "sugar_standard" food requirement  - "One unit [10u sugar] provides ~200kcal; chosen to match one unit of molasses" - were never made coherent. 

To be clear, this inaccuracy is a problem, as it low-key broke all recipes dependent on sugar, and it paralyzes work with any such. 

### Attach save file

Sugar

### Steps to reproduce

Sugar

### Expected behavior

So how do we fix it? 

The general information on density of sugar found on the Internet is suspicious. For one thing, there is a big mystery in how table sugar could be half as dense as sucrose, when table sugar is chemically just sucrose.

I have a sack of typical Domino sugar, a staple American brand. The dimensions are fully 170x120x100 mm, holding a net weight of 1810 g. Thus the minimum density, including packaging volume, would be 1810 g/2040 ml. That would indicate a density of 0.9 g/ml, only a little higher than most sources indicate, but still less than typically-available fresh water.

And yet, sugar will readily sink in water, as [this video](https://www.youtube.com/watch?v=ZmWYG7qh0QA) demonstrates. This  should be a widely-familiar phenomenon that demonstrates the direction of sugar's density relative to water.

Is it that bulk granulated sugar is radically less dense - half as dense - than a given molecule of it? 

Whatever the case may be, it is up to the community to fix sugar. 

### Versions and configuration

Sugar

**Comment by RedMisao** [comment]
For the sake of clarity, I will refer to sugar = saccharose = glucose + fructose, and "table sugar" as the white, refined commercial product we all know.

> For one thing, there is a big mystery in how table sugar could be half as dense as sucrose, when table sugar is chemically just sucrose.

This is because table sugar is not just sugar, it's crystallized sugar plus air between the crystals, see

![Sugar_2xmacro](https://github.com/CleverRaven/Cataclysm-DDA/assets/95231551/1b6cb624-7c9a-4070-a37c-5b4df9832f12)
(from wikipedia)

> And yet, sugar will readily sink in water, as [this video](https://www.youtube.com/watch?v=ZmWYG7qh0QA) demonstrates. This should be a widely-familiar phenomenon that demonstrates the direction of sugar's density relative to water.

I'm inclined to say this happens because when you add table sugar to water, there's a change or shift of volume, from the bulk table sugar to the individual crystal. So the density "increases" as the volume for each piece of sugar decreases, while the mass stays the same.

If calories are already set based on the mass (and thus it got corrected by reducing the mass of sugar), then there's nothing wrong. However, if the calories are set based on density (and it didn't get corrected when the mass was reduced) or that value was ported from molasses or something else, then yeah it should be audited for mass instead.

**Comment by Montimorency** [comment]
> This is because table sugar is not just sugar, it's crystallized sugar plus air between the crystals, see

A great point explored on [this page](https://chemistry.stackexchange.com/questions/139386/density-range-of-table-salt) with regard to table salt, but which I find somewhat unsatisfying, since from what I can find table sugar granules should be similar in size to table salt granules - yet table salt above enjoys a bulk density of nearly 65%, whereas table sugar would seem to fall between 50-57% based on available info. The microscopic shape of these substances is not dramatically different either. At salt's ratio a unit of sugar should be almost exactly as dense as water. 

Keeping the calories aligned to the weight is ultimately the most important thing. But the **quantity relationship** to the vast majority of recipes is important too. 

The complicated approach would be to find or produce an empirical test for a unit density of sugar. [For example](https://www.youtube.com/watch?v=ZFwaU9is74g), this individual is using a tablespoon to weigh out 18 grams, but the load is rounded, not level, and we don't know if it's a standard spoon. 

There's also my sack of sugar described above, which indicates at least a 0.9 relative density before netting out the packing material. 

If we prefer to keep sugar at a fractional relative density, then the simplest thing to do would be to raise the weight to 4 and the volume to 5 to make one game unit of sugar nominally equivalent to a teaspoon. 4:5 is the most popularly-cited ratio given for a teaspoon of sugar, which at least is close to the original intent as I interpret it. Due to game imprecision and rounding, a ratio of 0.9 or higher would require a density of 1 in practice. (It was due to rounding that we had 19 calories to 5 grams originally, since a gram of simple sugar has an energy density of 3.87 kcal/g.)

Another option would be to **restore** the weight to 5 g and increase the volume to 6 ml at that ratio. As far as I know, the game had the weight of "5" for sugar since at or near the beginning, until two years ago or so. 

My own current preference would be to set a 1:1 rounded ratio for sugar at the restored weight (5:5). We need a systematic solution more than we need a maximally accurate one, though.

**Comment by I-am-Erk** [comment]
> To be clear, this inaccuracy is a problem, as it low-key broke all recipes dependent on sugar, and it paralyzes work with any such.

Can you clarify this? Knowing what's broken downstream would help to figure out a solution.

The current stats for sugar make it just over half an imperial teaspoon, 3mL. I agree this is an odd amount to consider a unit of sugar and I'd prefer it to be 5mL, but as you can see in your PR that may have downstream ramifications that are gonna be a pain to solve. You can try to solve those if you want.

However, the mass of granulated sugar should definitely be based on the mass of granulated sugar, not of purified sugar crystal density. Under those values, 3mL of sugar should indeed be 2.5 grams, or 5mL should be around 4.2g. The problem, IMO, is not so much the grammage as it is the calories, as your last comment there seems to identify.

I think the ideal solution here is to set a unit of sugar to be 5 mL, 4.2g, and 16 kcal, and then fix the errors that result. The secondary fix would be to set it to 3ml, 2.5g, and 10kcal, but that's likely to cause a lot more breakage in recipes which is probably worse.

Your current fix doesn't, IMO, fix any of these, as it sets it to a unit that's not really standard in the game region (6mL) in order to keep up with the kcals, but as you can see, still causes knock on problems in volume. I wouldn't call that *wrong* per se, as long as you fix the volume issue, but it might be best to just set it to a logical measurement right off the bat. People are going to be writing recipes based on how many tsp of sugar are needed, by and large.

**Comment by GuardianDll** [comment]
Timeline: originally sugar was 5g and 3 ml, and used materials `powder` and junk, which made it's target density 1.05, and factual density 1.66 (sugars have density 1.59)
while fixing it, i think i initially tweaked values to be in line with target density 1.05, but then added `sugar` material to cover it's density, without revisiting changed values, which was my mistake
while 5 ml sound like a nice round number, i don't really know would it work good with recipes, since i am not very good cook irl, and i have a suspision that sugar is used not by volume, but by weight.

**Comment by I-am-Erk** [comment]
We'd have to check recipes to see but, if our recipes pay attention to quantity at all, I'd be surprised if they were written with grams in mind. Actually, I'd be more surprised if it was consistent in the slightest, but most US and Canada based recipes are volumetric.

**Comment by Montimorency** [comment]
A standard teaspoon is 5 ml though, not 3. 

I can confirm for sure that sugar weighed "5" in late-stage Cooper, the oldest version of the game I still have access to. In the available archived source code on the Cooper release page, from exactly 9 years ago, the weight is "56" and the volume "1", which is not interpretable to me, but there were fewer than three dozen recipes using sugar at the time, compared to 114 now, and a quick review suggests to me most of them have since been reworked in their inputs. 

In other words, 5-gram sugar units are the standard on which basically all our sugar-reliant recipes were built with. Moreover, the existence of the sugar_standard food requirement makes this explicit. While a new edict could change this at any time, it was clearly intended by devs relatively-early in game development that a game unit of sugar be equivalent to 5 grams. 

```
"id": "sugar_standard",
    "type": "requirement",
    "//": "One unit provides ~200kcal; chosen to match one unit of molasses",
    "components": [
      [
        [ "sugar", 10 ],
```

There is indeed a problem with the item group sugar_jar_glass_sealed_10_120 in increasing sugar volume - 120 units of sugar are 360 ml currently -  but this should only cause problems with existing saves, the problems being an error message that can be dismissed, and leakage of sugar should any affected containers be interacted with. There should not be any disturbance with ongoing spawns, as debug testing the item group demonstrates that these jars (0.5 L) will from now on spawn with to capacity with sugar, which is the appropriate behavior. 

If it's really a big deal, I could also go to the SUS jsons and reduce the specified 120 unit spawn ceiling to 83 (0.006*83 = 0.498).

**Comment by I-am-Erk** [comment]
Ugh. Well, if you feel confident that our sugar recipes are standardized to this, it's fine to keep it. I think then you should add a comment to the json like:

```
"//": "Our recipes have been standardized to use 5 mg of sugar",
```

so that on a future pass it's clear why the value is what it is, and then you'll need to track down the storage errors in the PR.

**Comment by Montimorency** [comment]
OK, I went the conservative route just in case and merely added two overflow conditionals. No more errors on existing.
