### ISSUE TITLE
[Mind Over Matter] Far Hand spell can damage/kill NPCs without them becoming hostile

### ISSUE THREAD

**Issue by NafenX** [CleverRaven/Cataclysm-DDA#72467]
### Is your feature request related to a problem? Please describe.

As the title says. I had started on a new character who was a telekinetic Loner (Hates being near people) but I started with an NPC in my starting cabin unfortunately. I saved and used Far Hand to move the NPC out of the cabin and noticed that no damage seemed to occur and the NPC didn't become hostile, so I slowly used Far Hand to drag him away from the cabin by a couple of map tiles or so.

As I was finishing getting him into the right spot, he died because apparently it had been doing damage to him the whole time assumingly whenever the forced pull movement was blocked by obstacles. I see this as an issue since it doesn't really make sense that an NPC would have absolutely zero reaction from being dragged around with mind powers if they were also taking on a lot of damage.

### Solution you would like.

In my opinion, the best behaviour would be for the game to instead warn you before casting the spell that you're potentially about to hurt an ally. If the player confirms and chooses to go through with the spell, then any damage from the force movement should either trigger the NPC to yell at the player to knock it off, or even just make the NPC hostile. I don't know enough about NPCs in Cataclysm yet to know how they generally operate, but it seemed a bit silly to me that the NPC just flat out didn't react to being slowly killed!

**Comment by RedMisao** [comment]
I _believe_ spells not aggro-ing monsters and NPCs is a bug from the spellcasting system in general, not limited to specific MoM spells or the spell effect `directed_push`. Any direct damage spell casted in front of a neutral NPC will not cause them to become hostile, run away or anything.
Because they sometimes blurt "lemme bandage myself real quick" and stuff like that, my guess is that they don't recognize who casted the spell. This is very exploitable when dealing with NPCs.
With monsters they're usually already hostile or prone to become so when the avatar gets in range to cast anything, so it's usually not noticeable that they don't recognize who's throwing them fireballs, instead that there's something they hate/fear nearby.
