### ISSUE TITLE
Add craftable iron anvil in innawood mod

### ISSUE THREAD

**Issue by pushard** [CleverRaven/Cataclysm-DDA#72498]
### Is your feature request related to a problem? Please describe.

I was playing innawood mod last year and now in a new run found, it is impossible to craft iron anvil any more :( only bronze is availble but I have no bronze.
![изображение](https://github.com/CleverRaven/Cataclysm-DDA/assets/102854708/aa750dae-6b8e-40a3-842c-af36a2e17f9e)

### Solution you would like.

Make alternative way to craft iron anvil in innawood mod as it was before. I see no reason to craft iron anvil only from the crude anvil which is crafted from the railroad track as ancient people wasn't using any of railroad tracks :) 

### Describe alternatives you have considered.

Maybe add crude anvil in innawood mod, craftet from the 40 lumps of steel?

**Comment by IdleSol** [comment]
In my opinion. The best solution is to automatically learn the recipe for creating chunks of bronze. And switching to using bronze tools.

There are too many problems with creating a steel anvil.

https://github.com/CleverRaven/Cataclysm-DDA/issues/72208#issuecomment-2007075330

![Bronze anvil](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/971e10b5-dc2f-4ae5-bfee-93c1f3903f58)
![Steel anvil](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/be55d2e9-6b4d-4f29-9102-91cfa1184878)

**Comment by osuphobia** [comment]
> In my opinion. The best solution is to automatically learn the recipe for creating chunks of bronze. And switching to using bronze tools.
> 
> There are too many problems with creating a steel anvil.

On closer inspection, I would say that the blacksmith/redsmith system of dda has never been well-balanced, and perhaps due to misperception, some inappropriate changes were introduced lately.

A typical example is the bronze anvil. Back to 0.G, bronze anvil had Anvil 2, with a weight of roughly 5lbs. 5lbs is a weight of jewelers anvil, which, as its name suggests, is used by jeweler, silversmith, and watchmaker, not blacksmith.

The weight of bronze anvil was then modified to 26kgs, with its Anvil level raised to 3, to fit its usage intended. But I strongly doubt that a bronze anvil can aford any heavy work, as it is as brittle as crude cast iron. Leave it Anvil 2 is more reasonable, but on the other hand, most of the recipes requires Anvil 3, that would make bronze anvil a lame thing. As mentioned before, making it easier for low-spec tools and weapons to be made could be a better choice.

As for the recipe for creating chunks of bronze, the question is, do you think a random US high schooler would know the correct percent composition of bronze alloy?
The components needed for chunk of bronze in dda are:
- tin powder (12) OR aluminum foil (371) OR aluminum powder (29) OR 2 aluminum cans OR 1 scrap aluminum
- 1 chunk of copper OR copper (50)

and IRL, lead, as well as silicon, manganese, etc, may also be a component in some type of bronze.
If you cast a piece of bronze without planning, you may get a piece of "leaded brass" whose physical and chemical properties are quite different from the typical bronze you want. Therefore, learning the correct recipe from a book is not meaningless.

See also:
https://www.anvilfire.com/21centbs/Selecting-an-Anvil.php
https://www.gsa.gov/real-estate/historic-preservation/historic-preservation-policy-tools/preservation-tools-resources/technical-procedures/bronze-characteristics-uses-and-problems

One more thing:
"Real" blacksmiths anvils mentioned in anvilfire, or the "london pattern" anvil exsits in dda, are all European things in the history. With a less Eurocentrism POV, you will realize that ancient people in the world had different type of anvils. Though adding variants to dda is another topic.

**Comment by pushard** [comment]
Yes you are right, just in innawood now it is impossible to craft steel anvil at all :(

**Comment by IdleSol** [comment]
@osuphobia 

I don't know anything about blacksmiths. I'm not going to argue about the details.

But I do see a few problems. The main and most annoying (to me personally) problem, is not being able to make a set of tools, without books and the tools themselves.

The second problem, is the emphasis on realism. That's not a bad thing. If only it wasn't selective.

Consider a level 3 hammer. If we drop the realism, it could be made from a recipe for a homemade hammer. And that would solve a lot of problems.

But if we look from the point of view of realism, this hammer is not suitable (or suitable but with limitations) for blacksmithing. Because it is an ordinary hammer for hammering nails.

The solution is to make some assumptions. The simple option is that every schoolboy knows how to get bronze. (An alternative recipe with more material and time consumption). The more complex one, is to add new tools to break the reverse loops.

The right one, is to audit existing tools. To build a sequence of getting and fixing errors in recipes. But who's to say that this is first necessary (and will be accepted), and second, what exactly is an error and what is not?

**Comment by IdleSol** [comment]
@pushard 

A temporary solution is to fix the file yourself:

/data/json/recipes/other/materials.json
line 335

```
 {
    "result": "scrap_bronze",
    "type": "recipe",
...

    "batch_time_factors": [ 90, 4 ],
    "book_learn": [
```
to
```
    "batch_time_factors": [ 90, 4 ],
    "autolearn": true,
    "book_learn": [
```
This will give access to making chunks of bronze.

**Comment by pushard** [comment]
@IdleSol 
Thank you for this code, but I'm afraid it will not help me to craft steel anvil with anvil 3 :) 
in the Innawood, it is nearly impossible to survive without steel weapon/armor and guns near the Mi-go towers :(

**Comment by osuphobia** [comment]
@pushard 
```
  {
    "type": "recipe",
    "activity_level": "MODERATE_EXERCISE",
    "result": "anvil",
    "id_suffix": "by_steel_chunk",
    "category": "CC_OTHER",
    "subcategory": "CSC_OTHER_TOOLS",
    "skill_used": "fabrication",
    "difficulty": 3,
    "time": "4 h",
    "autolearn": true,
    "qualities": [ { "id": "HAMMER", "level": 2 } ],
    "tools": [ [ [ "crucible", -1 ], [ "crucible_clay", -1 ] ], [ [ "forge", 150 ], [ "oxy_torch", 30 ] ] ],
    "proficiencies": [ { "proficiency": "prof_metalworking" }, { "proficiency": "prof_blacksmithing" } ],
    "components": [ [ [ "steel_chunk", 160 ], [ "steel_lump", 40 ], [ "frame", 4 ], [ "hdframe", 2 ] ] ]
  },
```
Add this to \data\json\recipes\recipe_others.json after the exisiting anvil recipe to get the old recipe.

**Comment by pushard** [comment]
@osuphobia thank you very much :)

**Comment by NetSysFire** [comment]
CC @Light-Wave

**Comment by pushard** [comment]
@osuphobia Hi, sorry for disturbing you, can you please point me where is Hammer reciepe is? :) I've found that crafting a steel hammer require now Hammer lvl 3 tool :) 
I should play different game :(

**Comment by IdleSol** [comment]
data/json/recipes/tools/tools_hand.json

https://github.com/CleverRaven/Cataclysm-DDA/blob/54d9f4c977adbe9c5f564402cf6e384cc5d49724/data/json/recipes/tools/tools_hand.json#L304-L322

**Comment by pushard** [comment]
@IdleSol wow amazing! I got the idea :) Thank you!

**Comment by PGR-14** [comment]
Oh yeah, relating to this, you can't make flatjaw tongs w/out flatjaw tongs (At least in the base game), so we should probably fix that

**Comment by NetSysFire** [comment]
Please make that a separate issue.

**Comment by pushard** [comment]
> Oh yeah, relating to this, you can't make flatjaw tongs w/out flatjaw tongs (At least in the base game), so we should probably fix that

well I've hound some cooper and tin wile exploring and craft flatjaws tongs the hard way. I mean getting ore for bronze was difficult in crates and I had to save/load some times because was falling hard :( anyway I agree, some iron/steel tools should be accesable in Innawood without the bronze.
