### ISSUE TITLE
Artificial Night Generator CBM also make player invisble

### ISSUE THREAD

**Issue by Paramachina** [CleverRaven/Cataclysm-DDA#72525]
### Describe the bug

Artificial Night Generator CBM also make player invisble like Cloaking System CBM.

### Attach save file

N/A

### Steps to reproduce

1. Turn on Artificial Night Generator CBM and check effects.

### Expected behavior

I dont think it make player invisible too.

### Screenshots

![스크린샷 2024-03-21 194113](https://github.com/CleverRaven/Cataclysm-DDA/assets/73211033/4af43ff0-156a-423f-912a-bb3af437e2b2)
![스크린샷 2024-03-21 194254](https://github.com/CleverRaven/Cataclysm-DDA/assets/73211033/59243816-0a60-4770-b756-e0198dc1e53f)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.3235 (23H2)
- Game Version: 4fdf92b [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by RenechCDDA** [comment]
Thank you for the report, but as far as I can tell this is completely intentional.

[This commit](https://github.com/Fris0uman/Cataclysm-DDA/commit/4fc91e92079e9a3bbd37d294a987abed0666fb7d) by Kevin implements the night generator and it very specifically makes `sees_u` (does this creature see you) return false. The invisibility has been there since it was added.
