### ISSUE TITLE
Add option to turn off selection of components listing during crafting

### ISSUE THREAD

**Issue by Icantthinkofanameforthis** [CleverRaven/Cataclysm-DDA#72663]
### Is your feature request related to a problem? Please describe.

I was making a nomad bodymesh and it gave me 16 different choices how i wanted my threads to be set out and spent about 10 minutes deciphering what was different about each choice

### Solution you would like.

As the title suggests give an option to not have the selection of components list not show up and let me pick normally even if it looks like the same option shows up 2 or more times with different amounts

### Describe alternatives you have considered.

leaving it i guess

### Additional context

Try explain to me how this is easier to go through than before this was implemented and ive had lists far larger than this XD

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/70473120/95736539-e8ef-4e66-93be-ec409d0d412f)

**Comment by PatrikLundell** [comment]
I suspect one of the reasons for the existence of this weird collation is that you otherwise can end up with a situation where you can't finish your component selection because an earlier choice used up all of a component that was the only possibility for a later one.

Ex: Choice between chunks of steel or lumps of steel selecting lumps, leaving you without a sufficient number of lumps for a later component selection where lumps are the only option (or the other options weren't available from the beginning).
