### ISSUE TITLE
Accurizing firearms is too simple

### ISSUE THREAD

**Issue by mikegogulski** [CleverRaven/Cataclysm-DDA#7266]
Taking a gun from fully repaired to accurized should not be as simple as taking, say, a rain coat from fully repaired to reinforced, only using a firearm/gunsmith repair kit instead of needle and thread. Accurization is a much more involved process.

New items needed:
- Bench rest (make from pipes, plastic chunks, clamps welder, screwdriver, drill; find in gun shops and marksman houses)
- Epoxy (superglue won't do! find in hardware stores and handyman houses)
- Vise (make from scrap/steel, forge, chisel, drill; find in hardware stores and handyman houses)
- Precision clamps (as vise)
- Dremel/Proxxon tool set (find in gun/hardware stores and handyman houses, requires batteries; can be substituted by integrated toolset)
- Magnifying lamp (find in handyman houses; make from whatever; can probably be substituted with an existing vision-related bionic)
- Calipers (makeable/findable)

I notice in the JSON that the gunsmith repair kit and firearm repair kit have essentially the same capabilities, so this might be an area to differentiate them, perhaps by adding the clamps, calipers, Dremel and magnifying lamp to it.

See, e.g. https://en.wikipedia.org/wiki/Accurizing and https://en.wikipedia.org/wiki/Rifle_bedding

(Source: dad was a shooter)
##

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
