### ISSUE TITLE
Mutations give "buff" stats instead of "base" stats

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#72698]
### Describe the bug

Currently when you mutate a stat-boosting mutation such as Strong, it gives you the stats in the form of a stat buff (like bionics) instead of a base stat. This is important, because for stats base vs buff has many important distinctions. For strength for example, this influences your disease resistance, HP, and BMI-from-strength (muscle bodymass). 

### Attach save file

n/a

### Steps to reproduce

0. Make a character.
1. Mutate Strong.
2. Observe your strength stat is 9 (8) instead of 9 (9). 
3. Observe your HP and bodymass also didn't increase.

### Expected behavior

Mutations should raise the base stat. EDIT: This is how it used to work before a recent enchantmentfication of the mutations.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/56016372/66c5aeba-4461-46af-bbb0-f8f9f2577d27)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4170 (22H2)
- Game Version: dd4e109 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Slots [cbm_slots],
    Portal Storms Ignore NPCs [personal_portal_storms]
]

**Comment by kevingranade** [comment]
I'm not at all sure mutations should increase the base stat. Your mutation that "let's you lift heavier objects or swing a stick harder" does not necessarily also make you tougher to damage or more disease resistant.

**Comment by anoobindisguise** [comment]
> I'm not at all sure mutations should increase the base stat. Your mutation that "let's you lift heavier objects or swing a stick harder" does not necessarily also make you tougher to damage or more disease resistant.

so are you figuring they're increasing muscle strength in a way that doesn't increase mass or something? i assumed the mutations were causing you to grow more muscles, which should have mass of some kind.

**Comment by kevingranade** [comment]
Biomechanics could be adjusted,  muscle efficiency could be adjusted,  bulk could be adjusted but not impact lean body mass in the same way as regular muscle building.
It could increase muscle mass, but the changes could be offset because it's non- human muscle mass.

**Comment by ADekema** [comment]
Some of the discriptions of mutations make it pretty clear that your muscle mass is visually increasing. I think the problem might be that states influence some things they shouldn´t. Strength for example shouldn´t have any impact on your discease resistance. Might want to make those things a function of health and some specific traits.

**Comment by Hyperseeker** [comment]
> It could increase muscle mass, but the changes could be offset because it's non- human muscle mass.

Unless this non-human muscle mass is also ultralean, ultralight, absolutely-permeable, and transparent, it should either:

1. Have the same effect as human muscle mass (which translates into base strength increase)
2. Be described as being somehow different from what one would expect when they hear "muscle mass"

Sure, "you're now stronger" could be interpreted in a variety of ways, some of them magical, but few of them can pan out as alternatives to good ol' muscle growth without extra justifications and/or effects.

Is it muscle density? Your mass may not increase, but you should probably gain HP still because, as far as the current HP system goes, it's the amount of damage a limb can suffer being becoming unusable and requiring medical attention; denser muscles mean more/harder tissue to damage before functionality drops to 0%.

Is it tensile modulus? Probably an increase in metabolism in order to support the (likely) increased microdamage from all the stretching the muscles could do now. (Not that the game's modelling muscle growth, but, you know, reality and all that.)

Unless your muscle tissue's being replaced and/or augmented by actual alien tissue? Which sounds like a health hazard, and maybe an immune response waiting to happen.

And if that doesn't happen? I thought this game was supposed to be cosmic horror. If none of them above happens, then there's absolutely no downside to the gained strength, at least for the "human-tier" mutations such as Strong. But in this case, why doesn't Strength add *mass*, the one thing that makes human strength definitely-*human*?

What I'm saying this: the fact that some mutations which are definitely supposed to increase muscle mass don't is probably an oversight, and not something to argue over just because it's the current status quo.
