### ISSUE TITLE
Unnecessary use of granular containers

### ISSUE THREAD

**Issue by Uwuewsky** [CleverRaven/Cataclysm-DDA#72738]
### Is your feature request related to a problem? Please describe.

After the introduction of the pocket system, many items began to spawn inside a nested boxes/bags.

This resulted in a cluttered interface. Sometimes it is not clear what exactly is stored in the container because of the deep nesting. And manually selecting each cookie from refrigerators to put it in one stack is tedious.

![tape2](https://github.com/CleverRaven/Cataclysm-DDA/assets/99945024/99529070-e92f-4193-9fd6-be9ba5c3b84c)
---
Those 25 lines could have been one.

![tape3](https://github.com/CleverRaven/Cataclysm-DDA/assets/99945024/635e4ce0-fac3-41fc-ae15-eb3eac177a63)
---
Materials (duct tape) do not stack, it can't even be stacked manually. And sometimes it introduces new bugs #71090.

![tape1](https://github.com/CleverRaven/Cataclysm-DDA/assets/99945024/78f3d5da-1088-4a0b-a3ff-8712e842be57)

### Solution you would like.

These small plastic pillboxes and cardboard rolls have no value on their own. All micro-level containers can be removed (except liquids, powders, sealed containers?). Drugs in medicine cabinets can be unpackaged, food in refrigerators can be unboxed.

### Additional context

Performance issues with actions on thousands of individual items have been fixed? In the latest version, the character no longer picks up thousands of cotton scraps for an in-game hour. So I don't think picking up a dozen alcohol wipes from the first aid kit instead of picking up a single pack of wipes will have any major impact.

**Comment by Drew4484** [comment]
Sometimes it is hard to see what is in a container without opening a container. This is an IRL bug that has been marked Critical severity but has not yet been resolved.

**Comment by Maleclypse** [comment]
```
These small plastic pillboxes and cardboard rolls have no value on their own. All micro-level containers can be removed (except liquids, powders, sealed containers?). Drugs in medicine cabinets can be unpackaged, food in refrigerators can be unboxed.
``` 
This solution is not desired by the direction set by senior devs.  Since there is no alternative solution suggested I'm closing this.

**Comment by Uwuewsky** [comment]
So there's nothing to discuss here? Fine, whatever.

**Comment by esotericist** [comment]
> So there's nothing to discuss here? Fine, whatever.

if you started out looking for ways to improve containers' impact, ui improvements, quality of life, etc, that would have been worthwhile. actually getting rid of the containers is a non-starter, though. we like the containers, and we want the containers.

**Comment by andrei8l** [comment]
> 
> Those 25 lines could have been one.
> ## ![tape3](https://private-user-images.githubusercontent.com/99945024/318234504-635e4ce0-fac3-41fc-ae15-eb3eac177a63.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4NjEwMjEsIm5iZiI6MTcxMTg2MDcyMSwicGF0aCI6Ii85OTk0NTAyNC8zMTgyMzQ1MDQtNjM1ZTRjZTAtZmFjMy00MWZjLWFlMTUtZWIzZWFjMTc3YTYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMxVDA0NTIwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1ZWUyZTM5OTVkYTMzNjIyYTFjZDAyYmZhMzMwY2JkMTY3MjI3NzQyOGQwM2E0Y2ZjMWNmMDExNDE1NGY5MmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-NDX3C_ZE9QRtRunxvO2ZTZha1KkQXqxD8u2P9BDYMw)

/confirmed This specific case looks like a bug. It should have said ` > 22 tampons / 23 items`. Can you share the save file?

**Comment by Maleclypse** [comment]
Reopening as a bug issue.

**Comment by esotericist** [comment]
> /confirmed This specific case looks like a bug. It should have said ` > 22 tampons / 23 items`, unless I'm misreading the screenshot. Can you share the save file?

there are 23 tampons in there, inside 23 plastic bags, inside one box. it's a presentation misfortune, but not actually erroneous.

**Comment by andrei8l** [comment]
> but not actually erroneous.

it's an oversight in #70766 and its predecessor #63579. The infrastructure is already there and it's just not plugged in.

**Comment by esotericist** [comment]
> > but not actually erroneous.
> 
> it's an oversight in #70766 and its predecessor #63579. The infrastructure is already there and it's just not plugged in.

i suppose since you wrote that code you'd know more about whether it was failing to behave as intended than me, but even if so, i don't think this issue should be reclassified as a bug (especially since the topic of this issue was more expansive). either a new issue or a pr should be opened, instead.

**Comment by ZhilkinSerg** [comment]
> And manually selecting each cookie from refrigerators to put it in one stack is tedious.

Don't put them in one stack

**Comment by Uwuewsky** [comment]
> if you started out looking for ways to improve containers' impact, ui improvements, quality of life

which is what I propose to improve all this by removing small unnecessary containers, I don't see any reason why this is a non-starter.

---
@andrei8l yes, as esotericist already say, this is a box with bags. ~~this screenshot is from a week old build~~ these boxes with the same label also spawn in the latest versions in the bathrooms of houses. here's a minimal example, this box in inventory:
[Paullina-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14814709/Paullina-trimmed.tar.gz)

---
I put everything in one stack so I can see the total amount of loot without calculating the number of bandages in each package from two pages of menus.

**Comment by esotericist** [comment]
> which is what I propose to improve all this by removing small unnecessary containers, I don't see any reason why this is a non-starter.

it's a non-starter because it's an element of verisimilitude that the team -- and a sufficiently large number of our players -- finds pleasing. we HAVE made adjustments to too many nested containers when it's *truly* problematic in the past -- a rare occurrence -- but when the basic containers make sense/things are obviously stored in them for a reason, they aren't optional as far as we're concerned.

so again: if you want to pursue ways of making it present better, or play smoother, that's up for discussion. "get rid of the 'unnecessary' containers", especially when you're defining them as ones we consider necessary, is just not going to go anywhere. 

to give a more concrete example of things that can happen, you mention:

> And manually selecting each cookie from refrigerators to put it in one stack is tedious.

i agree. this is tedious. we have had a number of discussions about this, and would like to implement a more convenient 'compacting containers' feature, which lets you put a bunch of the same stuff in one container without micromanagement.

the truth is, most of us don't actually *like* micromanagement any more than you do. so the goal is to have the detail without the labor. it just takes a while to get there, because these processes aren't easy to design and engineer. it's just we consider a bit of this kind of micromanagement in the interim a necessary evil for the simulation elements we want to have.

accordingly, i urge you to approach this from the standpoint of "how do we make what we have play better", not "let's get rid of stuff that doesn't currently play as well as i'd like". 

and finally, to be more firm as a member of the senior dev team: no, removing the containers you mentioned isn't an option, please don't attempt to debate it further, it isn't going to be constructive.

**Comment by GuardianDll** [comment]
\> Those 25 lines could have been one.
yes, if it was 23 tampons in a single bag, but it is 23 tampons in 23 different bags, it's an issue of itemgroup, not UI

**Comment by esotericist** [comment]
> > Those 25 lines could have been one. yes, if it was 23 tampons in a single bag, but it is 23 tampons in 23 different bags, it's an issue of itemgroup, not UI

since andrei was the one that did a lot of the item contents summary logic in the first place, if he thinks he can clean this up, i'm inclined to believe him.

**Comment by GuardianDll** [comment]
i mean this particular case, if we have something like "23 boxes with 30 rounds inside", then it is what Andrei says

**Comment by Uwuewsky** [comment]
ok, this issue is going nowhere. aaand the issue with that box, I think it was taken into account.
