### ISSUE TITLE
Save/load cycle turns open air into the floor/ roof

### ISSUE THREAD

**Issue by SSpook** [CleverRaven/Cataclysm-DDA#72758]
### Describe the bug

Saving and loading a game after finishing a "Dig out pit completely and remove anything remaining" results in the newly produced open air to turn into walkable terrain if the open air is in the reality bubble.

### Attach save file

[Plattsmouth-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14818374/Plattsmouth-trimmed.tar.gz)
Walk to shelter, wait 30 min, save+load.
Or wait 30 min, walk to shelter, save+load.

### Steps to reproduce

1. Get a shovel.
2. Dig until you produce open air.
3. Save and load.
4. Examine where you digged.

### Expected behavior

Expected to produce a hole.
Expected the hole to not disappear.

### Versions and configuration

Game version 22c8112

### Additional context

Using the debug menu to change terrain into t_open_air seems to produce the same results.

**Comment by PatrikLundell** [comment]
/confirmed

Loaded save, followed instructions (had to look at the map to figure out that "the shelter" was to the NW).

It's presumably the same weird logic that closes up holes at the collapsed office tower and other places where cave-ins occur. Wouldn't be shocked if the map::add_roofs operation (buried beneath map::load) is involved, but my guess is that the cave-in (and digging) logic fails to transform the terrain affected below from one containing a roof (which then is "repaired") to one that doesn't have a ceiling and thus doesn't have a roof. Furthermore, it may well be that the ceiling less terrain corresponding to the one with the ceiling doesn't exist in many cases.

Note that tinymap can't affect the terrain of the Z level below since it only support a single Z level.
