### ISSUE TITLE
Allow NPCs to lend social skills

### ISSUE THREAD

**Issue by fairyarmadillo** [CleverRaven/Cataclysm-DDA#72775]
### Is your feature request related to a problem? Please describe.

If the player has an NPC companion nearby, they should be able to optionally use their social skills for barter and dialog rolls if they're higher. If a gruff and ugly killer has a bombshell elf mutant friend, it makes sense that they'd let the elf do the talking.

This could encourage the player to bring NPCs with diverse skills along with them to help with tasks they're specialized for rather than always going it alone and trying to get good at everything themselves. Having more reasons to care about NPCs and bring them along into potentially dangerous places seems like a good way to expand their usefulness and create more interesting stories.

### Solution you would like.

Add a toggle in the NPC's behavioral rules menu that will allow them to assist with speech and barter rolls if their skills are higher, and make it so that trades and dialog choices made this way train the NPC and not the player.

Without a substantial rewrite, randomly generated NPCs would still be using their opinion of the player character to determine the difficulty of persuade/intimidate/lie checks - this seems fine to me, as in the above example, the beautiful elf might be very convincing, but they are still obviously taking orders from someone who might be a lot less appealing.

### Describe alternatives you have considered.

This could potentially also be done for hacking. Lockpicking and dissecting come to mind too, though maybe those would be better done via simply ordering the NPC to carry out the task.

**Comment by PatrikLundell** [comment]
I'm all for the ability for companions to assist the PC with all kinds of tasks. The current dialog system doesn't have that many checks, but it sure would be good if it contained inherent support for companion assisted skill checks.

The stuff below concerns the similar but distinct improvement of ordering companions to perform more tasks.

When it comes to other support from companions, direct orders is probably the best way to go. I can imagine how automatic lock picking would go down:
- PC action on door: pick lock.
- Companion with best lock picking skill: Task completed.
- What? Nothing happened.
- Scratch head. Figure out that the companion doesn't have any lock picks.
- Sigh and hand over the lock picking set to companion.
- Try the action again.
- Companion: Out of my mfing way you a*hole!
- Companion: Excuse me fellow survivor, but could you let me through?
- And 100 additional instances of the above.
- Move PC.
- Wait.
- Wait.
- Wait.
- Realize the companion won't perform the task because you broke it when moving away.

Probably better to introduce a companion order mechanism whereby you can order the performance of a task and designate the target for it and the companion would then go to the target and perform the corresponding action on it (and fail if the actions available doesn't include the ordered one, like e.g. picking the lock of something that doesn't have a lock or an unlocked door).
Another possibility would be to order the companion to act on a target, select the target, and then select from the actions that target provides. That should remove the case where you order an action that isn't valid for the target.

The set of potential ordered tasks would probably be every interaction the PC can perform. Note that this may lead to infrastructure change needs when ordered actions take time as the PC should be able to move around and act while the companion performs its task.

**Comment by fairyarmadillo** [comment]
Good point about lockpicking lol. I think the dialog stuff would be pretty easy to implement though, and it'd be great if people were more motivated to travel around with an RPG party.
