### ISSUE TITLE
Can we get a key to repeat the last (a)pply choice?

### ISSUE THREAD

**Issue by ArikVhedrovix** [CleverRaven/Cataclysm-DDA#7278]
I really like the command to repeat the last crafting recipe and use that all the time. Can we get something similar for the apply command? I think this could be useful for situations like:
-using my stack of 15 bandages more quickly
-"toggling" my flashlight off and on with a single button
-applying my crowbar over and over to force that door
-using my sewing kit, when I plan on going until my stuff is fitted and reinforced
Those are really the examples that spring to mind, I am sure there are many more.

**Comment by narc0tiq** [comment]
This has some overlap with #574, too.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
