### ISSUE TITLE
Folded vehicles that can act as containers maintaining contents

### ISSUE THREAD

**Issue by Procyonae** [CleverRaven/Cataclysm-DDA#72818]
### Is your feature request related to a problem? Please describe.

Rn containers can't maintain contents when folded/unfolded

### Solution you would like.

Me to stop forgetting about and finish https://github.com/CleverRaven/Cataclysm-DDA/compare/master...Procyonae:Cataclysm-DDA:DeployableSuitcase?expand=1 which adds a roll along suitcase foldable vehicle as an example use case

**Comment by Kywi001** [comment]
Huh? Why would a folded container be able to keep it's contents? Or should it be able to be folded when it has something inside it?

For example, Foldable wire basket, you can fold it because it's collapsible, you cannot collapse it if it's filled.

**Comment by PatrikLundell** [comment]
A foldable bike dumps the contents of its wire basket on the ground when folded, which makes sense.

It would make sense for a "foldable" (in reality more a case of deployable) suitcase to retain its contents if the "folding" just means the wheels and handle are folded, and thus the overall size of it would remain essentially the same and it's a matter of converting it between a carried item and a dragged/pushed vehicle.
I can certainly see the appeal of a deployable suitcase that can be undeployed and lifted between levels rather than using a folding shopping trolley where you have to fold it and carry all the stuff up the stairs individually before unfolding it and refill it.

It would require some additional logic to allow a distinction between foldable and deployable.

**Comment by Procyonae** [comment]
I'll admit this was mainly as a fun challenge to myself but you can already distinguish the two, the suitcase item used here is a container with a pocket the same size as it's unfolded version and has handling for if the pocket size doesn't match the cargo etc.

The intended use case is as Patrick says, instead of using a shopping cart to collect lab loot for example (a common practice) then having to take everything out and drag it up the stairs, instead you'd just pick up/"fold" this wheeled suitcase and redeploy it at the top.

'Folded' is a pretty arbitrary descriptor for any vehicle you can pick up through some means, skateboards being a prime example

**Comment by Kywi001** [comment]
If that's the case, imo, no reason to implement this.

Unless if they revamp carried weight to also affect speed cost of moving, then I can see it being usable like:
1. Suitcases are using hand and arm encumburance (like a briefcase)
2. Deploying it allows you to "drag" it (still as a worn item but without the encumburance penalty and it's total weight being reduced by a lot)

Otherwise... Large cardboard box literally does what youre asking of

**Comment by Procyonae** [comment]
> If that's the case, imo, no reason to implement this.

Well maybe I want functional wheelie suitcases for when I get around to adding a realistically sized civilian airport and don't care what your cardboard box can do

**Comment by PatrikLundell** [comment]
Dragging a container item is a lot slower and tiring than pulling/pushing a wheeled "vehicle" of the same weight.
