### ISSUE TITLE
Long-term rewards for living good

### ISSUE THREAD

**Issue by Nandorianen** [CleverRaven/Cataclysm-DDA#7285]
As was pointed out on the forums long time ago, current morale system has too short a time-span to really invest in. You get an immediate boost when you need it, then lose it in a few minutes. You wait for half an hour for penalties to go away. That's pretty much it.

Health system works in a similar way, as I understand it. Regular passive shifts that push your health to default 0 make it worthwhile to eat your vitamins to compensate for immediate health loss from bad food and that's pretty much it. If you are have disease immunity, you can forget about that too.

In my opinion, caring for your character's well-being should have incentive beyond roleplaying, which is not much of an incentive (you can dramatically roleplay tetris all you want, this will not add any more depth to the game itself).

There are few main things to consider. First is time-span. When something is too brief, it can be ignored. Second is whether or not the problem will go away by itself at all. If things will just go back to normal by themselves given time, you are less inclined to worry about them. Thirdly, the severity of bonuses and penalties. If they are negligible, you will ignore them.

Then there are various systems to talk about. First of all, the morale system. Proper morale should combine short-term boosts and penalties (like from tasty stuff or getting hit) with long-term things (like from knowing you have a safe haven and supplies, eating properly, being generally content and successful). There are ton of things that can contribute to your mood: from wearing comfortable (maybe also non-encumbering and of proper warmth) clothing to in-universe roleplaying (maybe you always wanted to kill zombies or be a knight / ninja / dinosaur). Random mood modificators that partially define your day after you wake up (or multiplier from first things that happen when you wake up) are also an option. No-one likes to be rudely awaken by a zombie bear bashing its way through your windshield, especially if you can't get to sleep afterwards.

Next in line is health system. It could benefit from being more severe and more stable. Random shifting that tend to push your health to 0 are not interesting. It would be much more interesting if there were more severe and definitive consequences. Get healthy food with good variety - stay healthy, feel more fresh and alive, heal faster, get mood bonuses, maybe even bonuses to stats on high levels. Eat junk with little variety, smoke a lot, abuse drugs, sleep on the cold floor - get worse, get more diseases, feel like shit, get morale penalties, get stat penalties. Now that would give me a real reason to seek out and cook food instead of stacking something long-lasting and ignoring everything else. This would make me feel my vitamins are not an immediate medkit against unhealthy food, but a useful addition to my lifestyle. To make this work properly positive effects should probably be capped. Something like only one food type per day works, only one or two vitamins doses, etc.

Then there's the HP. and medications. It was already suggested that instant healing is not very good. It's like magic potions. Healing without proper treating / medication should take a very long time, often stagnating or even getting worse depending on what your problem is. Proper healing should improve both your chances for a more beneficial sleep and rate of HP regeneration.

Discuss?
##

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
