### ISSUE TITLE
Allow very tall people to fit through empty window frames

### ISSUE THREAD

**Issue by DragonWizard23** [CleverRaven/Cataclysm-DDA#72868]
### Is your feature request related to a problem? Please describe.

I tried playing as a very tall character for the first time today and I like how he can't fit through open windows. However, after removing the window from the frame, I expected him to be able to fit. 

### Solution you would like.

I would like very tall characters to be able to fit through empty window frames. 

### Additional context

Here is what I picture house windows as. I can understand a tall person not being able to squeeze through it when opened, but the opening doubles in size when the glass is removed. 
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/151102088/65d55894-0cf2-42f0-b05a-0a3fbaa111d3)

**Comment by Nebnis** [comment]
I still don't see how someone very tall won't be able to go through either. They would just squeeze their heads or legs first. 

I can imagine someone very obese not fitting though.

**Comment by fairyarmadillo** [comment]
This has been suggested many times. The entire point of the large size category is that you're big. You aren't just a stretched out man, you're Shaq or Andre the Giant. These people have wider shoulders and broader bodies than normal.

Large sized creatures being unable to fit through windows is intended. Changing this behavior would allow boomers and mi-go to go through windows, which would make it much harder to escape from many enemies. Being large has many benefits, this is one of the tradeoffs.

There are also not multiple different window sizes, and adding them would make navigation a lot more confusing.

**Comment by DragonWizard23** [comment]
@fairyarmadillo Thank you for the feedback. I did not realize that "very tall" has the same effect as the "large" mutation. Like you mentioned, I thought it meant mildly exceptional height, like 6'3" or so.

**Comment by fairyarmadillo** [comment]
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/94415528/9fb0e02a-6038-48d7-9e19-887a866601b2)

No, it's literally a giant. I didn't just call it "gigantism" as there's been a push to de-medicalize trait names, but it is the same sort of largeness that big mutants get, except without some of the benefits as vanilla humans aren't well adapted to being that big.

**Comment by DSeyka** [comment]
"Inhumanely tall" would be a better name for this trait, I think.
It implies there is a difference between regular humans and the ones with the trait, and rightfully so.

**Comment by PatrikLundell** [comment]
Note that the normal size selection goes up to 2 meters (between 6'6" and 6'7").

It might be reasonable to increase the normal size range a little to include basketball player length, as those individuals presumably are at the very top end of how tall a human can get and still function comparatively normally (not saying they're not having issues with a lot of stuff simply because it's not sized for them).

However, an abnormally large character won't fit into the game lore wise, as mutants are a post cataclysm phenomenon (yes, there are people who are abnormally large today, but they're all(?) suffering from fairly severe problems because of it, and so would have significant problems with a post cataclysm living (beyond the usual).

**Comment by kevingranade** [comment]
Chargen *mostly* targets "normal" characters anyway, so it's very likely that evicting "very tall" from chargen is the right move.
