### ISSUE TITLE
Too many gimmick tshirts

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#72878]
### Is your feature request related to a problem? Please describe.

Subjectively I currently believe there are way way way too many "gimmick" tshirts. Our shirts currently spawn as the following: `political meme t-shirt, My Little Nazgûl t-shirt, Matt Berry t-shirt, doom song t-shirt, Boba Fetch t-shirt, mouse portal, t-shirt, Ceiling Cthulhu, t-shirt, pumpkin time, t-shirt, portal to the cat dimension, t-shirt, forbidden robot t-shirt, Down with Swordocracy t-shirt, Black Phillip t-shirt, theme park parody t-shirt, activities for children t-shirt, baseball t-shirt, football t-shirt`
This is way too silly and basically all of them are obscure internet humor or fictional memes. These show up everywhere, on everyone, when in real life most people just wear plain tees.

### Solution you would like.

These need to be far less common. (In my opinion). Personally I would prefer for all of these to be consolidated into "meme t-shirt" with a generic description and made relatively rare. And primarily on children, who conveniently have their own loot pool. I remember in middle school a couple people wore rage face tshirts but I cannot recall the last time someone's tshirt had a joke on it in real life. Then again I have shitty memory so. Variants should probably be pretty generic in general and not hyper specific like this.

### Describe alternatives you have considered.

IDK lol. Maybe I'm the only one who cares about this

**Comment by Vaskritaya** [comment]
note there's also tshirt_text, which seems relevant.

interestingly, while sports related shirts seem to be covered with the baseball/football tees, there's no inclusion of band tshirts and the like. when it comes to tshirts that aren't just plain shirts, i feel like those would be way more represented than the sorts of niche graphic tees.

my suggestion would agree with your idea to consolidate it down into one or two more generic joke tshirt, and then maybe add generic variants for other more common varieties like band merch, political tees, university branded tees, etc. Things that are believable to see around, rather than all shirts exclusively being either totally plain or hot-topic tier reference humor.

**Comment by MelacholicMimic** [comment]
Item variants feel too random in general. If you see stockings in real life, there's a >90% chance they're going to be black or white, yet if you pick up 20 random stockings in the game, it looks like you just murdered a pride parade that also included colorblind people.

**Comment by kevingranade** [comment]
Feel free to adjust the weights to make the very specific shirt/stocking/whatever variants be 1% of the total and 99% be the super common solid colors, but no we're not getting rid of the variants.
