### ISSUE TITLE
lag when NPC crafts

### ISSUE THREAD

**Issue by bateau-de-coal** [CleverRaven/Cataclysm-DDA#72896]
### Describe the bug

5 seconds per turn when a specific NPC crafts.

### Attach save file

[Hackberry-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14900916/Hackberry-trimmed.tar.gz)

### Steps to reproduce

Let Garrett work on the brigandine.

### Expected behavior

No significant lag.

### Versions and configuration

os: ubuntu
build type: linux-curses-x64
build number: 2024-04-06-0205
language: german
modes: default

**Comment by PatrikLundell** [comment]
That kind of reports have been made in the past, although I failed to locate any of them.

I suspect it's caused by the crafter being ill (e.g. sneezing from cold or wheezing from asthma). However, I saw no lag when loading the save and walking around for a little. Dreama has hay fever, but, as mentioned, I saw no lag. I also set Garrett on progressing the brigandine, and then walked around a bit. Again, I saw no lag.
