### ISSUE TITLE
The base metabolism of characters is too high

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#72902]
### Describe the bug

Characters appear to have overly high metabolisms.
A standard character (default settings, 175 cm, 8 str, no XXXL/XS trait, no fast metabolism) weighs ~170 lbs at a BMI of 25. Their base metabolism is about 3500 kcal/day, at rest. This seems wildly too high, probably close to by a factor of 2. If the character lies in bed doing literally nothing all day long that's their caloric expenditure, which is far beyond anything normal for a human.

### Attach save file

n/a

### Steps to reproduce

1. Spawn a default character.
2. Use debug "check game status".
3. Observe high bmr. 

### Expected behavior

at-rest caloric expenditure should not be as high as that.

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/56016372/fb4fa18b-8f8c-42e7-b7fa-ef0fad727325)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4170 (22H2)
- Game Version: 7fece1f [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Slots [cbm_slots],
    Portal Storms Ignore NPCs [personal_portal_storms]
]

**Comment by Nebnis** [comment]
[https://www.hollandandbarrett.com/the-health-hub/weight-management/fitness/exercise/what-is-bmr/#:~:text=Most%20people's%20BMR%20is%20between,around%2C%20talking%2C%20or%20exercising.](url)

Basal rate for average person should be between 1000 to 2000

**Comment by Vane79** [comment]
You know what? Active exercise upping caloric intake to 8x is WILD. Look at this calculator here. It shouldn't be more than 3x. 
![изображение](https://github.com/CleverRaven/Cataclysm-DDA/assets/36656584/b9593501-a1bf-442b-9f7b-188f4cf13aad)
If an average man would need to eat 8x calories after a day of physically straining work, that'd be like 12000kcal, which is nearly a week's worth of food for an average male. Societies would collapse.

**Comment by kevingranade** [comment]
Weird, it's almost like the game lets you maintain a way-too-high activity level for most of the day and that results in extreme calorie expenditure.
![Screenshot from 2024-04-15 14-28-20](https://github.com/CleverRaven/Cataclysm-DDA/assets/860276/b4ae7c50-9b81-4eb1-9f60-8dd4f003db17)

We're working on this, the fix is your character needing to take breaks to even things out, not artificially reduce the amount of calories expended because you don't like the outcome of running full tilt all day.

This is an entirely separate issue from BMR getting evaluated in what looks like an erroneous way resulting in too-high calorie expenditure when at rest.
