### ISSUE TITLE
Melee combat should be more wearying

### ISSUE THREAD

**Issue by anoobindisguise** [CleverRaven/Cataclysm-DDA#72911]
### Is your feature request related to a problem? Please describe.

Currently I very frequently take an unskilled character and kill over 1000 zombies every day. This probably should not be possible. The issue is that fighting doesn't make you very weary. You can easily go 6-8 hours before you finally reach Light weariness and start getting speed debuffs.

### Solution you would like.

Ideally engaging in prolonged combat (fighting zombies whenever I have stamina available, only pausing to regain it and treat any wounds) should make you as weary as quickly as prolonged extreme activity (digging a deep pit) which sees you become Lightly weary from fresh after about 2 hours or so.

### Describe alternatives you have considered.

Idk. How long did medieval soldiers fight on the battlefield? How was their effectiveness compromised as a result? I don't know. It seems like the most pertinent IRL equivalency though.

**Comment by Procyonae** [comment]
Worth reading #72733 if you missed it

**Comment by Procyonae** [comment]
Were just checking you were aware of it

**Comment by fairyarmadillo** [comment]
Add an "explosive" activity level for:
1) Melee attacks
2) Dodging
3) Blocking
4) Jumping and gliding
5) Throwing
6) Shooting a bow
7) Taking a hit
8) Resisting a grab

Make this activity level orders of magnitude more taxing than the current highest one, enough so that even though most of these activities last only a second or two, after a couple dozen enemies, you're pushing into moderate weariness. Allow weapon proficiencies (and maybe add one for wrestling, dodging, etc) to step the explosive activity level down to something in-between it and extreme, so that late-game characters can deal with the tankier threats around without immediately getting blown out. This would simulate practiced fighters keeping their cool and not wasting energy with pointless movement.

Fighting for your life is largely an anaerobic activity that tends to favor survival over all else, and adrenaline (actual adrenaline, not the trait) leaves you feeling completely blown out, shaky, and weak after it passes. Anyone who's been in a self-defense situation can tell you it's extremely draining.

**Comment by IdleSol** [comment]
Could you please specify: character stats, traits and proficiencies (weak points). What kind of weapons do you use? Do I understand correctly that we are talking about the first day of the game?

**Comment by I-am-Erk** [comment]
I think we can do something using muscle burn levels to affect weariness. It's just a few steps away still
