### ISSUE TITLE
Loading a save from 0.G causes player to become permanently emaciated.

### ISSUE THREAD

**Issue by anselmusCA** [CleverRaven/Cataclysm-DDA#73033]
### Describe the bug

Loading a save from 0.G causes player's weight to change from normal to emaciated, which cannot be fixed by eating or debug.

### Attach save file

[0.G.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/14973060/0.G.zip)

### Steps to reproduce

Load save file in experimental.

### Expected behavior

I expected player stats would not change.

### Versions and configuration

OS: Debian Bullseye
Game version: cdda-experimental-2024-04-14-1503 4a328a6
Graphics version: tiles

**Comment by RenechCDDA** [comment]
You're badly underweight (36844 kcal of the 55000 that was considered healthy) when loading the save in 0.G, you're emaciated when loading the game in 0.H. In both cases it can be resolved normally, by eating. Debug also handles it normally, making you no longer emaciated if stored kcal are increased to a healthy level.

Seems fine to me?

**Comment by NetSysFire** [comment]
It feels like it should somehow be migrated though

**Comment by anselmusCA** [comment]
> You're badly underweight (36844 kcal of the 55000 that was considered healthy) when loading the save in 0.G, you're emaciated when loading the game in 0.H. In both cases it can be resolved normally, by eating. Debug also handles it normally, making you no longer emaciated if stored kcal are increased to a healthy level.
> 
> Seems fine to me?

Interesting, because that contradicts everything that I'm seeing; my weight is normal in 0.G. Anyway, the issue was only reported at NetSysFire's suggestion; I've already moved on with a new game.

**Comment by kevingranade** [comment]
> It feels like it should somehow be migrated though

How? Was the stored calories scale changed, or were the messages just changed?
If it's the latter you can't do a migration, it's the same state being described a different way, with the former you can potentially track down what the scaling is and update it, but it's not clear that that's what's happening.

To track that down you could presumably use this savegame and bisect when the transition occurs.

**Comment by RenechCDDA** [comment]
Yes, the calculation changed in #60597. It used to be that every character (regardless of size, height, etc) had 55,000kcal as their target healthy value. The character in the provided save is above the average height (182cm vs 175cm) on top of already being underfed, which is why they shift from "Not underweight (barely)" to "Emaciated" on changing version. The target changed and it *exacerbated their existing lack of stored calories*.

It should be noted that that PR also changed when the display showed that you were underweight. It is not that the character wasn't underweight before, theywere. It just didn't tell you until they had hit a mere **25,000 stored kcal**.
