### ISSUE TITLE
ImGui option request

### ISSUE THREAD

**Issue by KHeket** [CleverRaven/Cataclysm-DDA#73047]
### Is your feature request related to a problem? Please describe.

Few ideas to improve new ui

### Solution you would like.

1) Set option to default
There is million options, and you can in experiments turn off some needable option, and you need to set all to default
2) Search option
There is million ImGu options, and sometimes its hard to find what you need
3) Make option to set transparent level of windows, because it make not comfortable to do something in windows, when you have lots of bright items/windows with words/or something else behind it

**Comment by ZhilkinSerg** [comment]
There are Dear ImGui built-in style and configuration menus available in Dear ImGui Demo Screen:

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/16213433/36f0f3df-01b2-43fe-bfdd-729b3cb89ede)

If you want any changes to them - they might need to go into upstream repo.

**Comment by katemonster33** [comment]
Yeah what Zhilkin said. All the code for the demo UI is in imgui_demo.cpp and we could technically rip that to pieces if we really wanted to, I probably won't update it much unless there's very big upstream changes. The suggestion is a nice thought but I really don't see us being able to tackle this, just because running ImGui with tons of little user-specific options was never the focus of the work and could break things. But I'd be willing to consider specific cases if it can be proven it doesn't cause regressions

**Comment by KHeket** [comment]
Did I understand you right, if I want some changes to ImGui, I should open issue in https://github.com/ocornut/imgui/issues ?

**Comment by katemonster33** [comment]
no, i'm saying that those options should probably not be touched because they could break things. if we think certain options are a value add to the user, then I think we could create a more specific issue detailing which option we want to see in the game.

right now this is too broad to really act on. I simply cannot add all ImGui options into CDDA, it will break everything.

**Comment by KHeket** [comment]
Set to default and search option is not necessary for me, but transparency of windows makes my eyes harder to work with this new pop up windows style

And I find out, how to fix it, just set here alpha level to 255 and made old style color
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/102726167/35b904d5-c42b-43db-9c26-bcf3b7dd7270)
