### ISSUE TITLE
Problems with auto-moving

### ISSUE THREAD

**Issue by IdleSol** [CleverRaven/Cataclysm-DDA#73062]
### Describe the bug

During the automatic movement, I encountered three types of bugs

1. **Incorrect path construction**

Instead of moving in a straight line, the game tends to use roads.

For example.
If you move on foot
![1](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/4374d6ed-c7ca-4e8e-9378-9d9c9ad51289)
If you ride a motorcycle
![2](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/b92310c8-2182-4703-acbb-92c146165850)

It's a clear field. With a patch of tall grass. Why would the game suggest a longer path?

These screenshots are not the most representative example. Sometimes the detour is even longer.

2. **Speed reduction**
When using vehicles, the speed is reduced to 6 km/h in some locations. On the road, in the field or elsewhere.

3. **360 degree turnaround**
Encountered only when driving on vehicles. Moving along the laid route, the transport makes a 360 degree turn. After that it continues to move along the route. Attempts to repeat the car movement on the same section pass normally.

4. **Another reminder**
19 km/h? Why is that so slow?

### Attach save file

N/A

### Steps to reproduce

N/A

### Expected behavior

N/A

### Versions and configuration

cdda-windows-tiles-x64-2024-04-16-1009 and earlier versions

**Comment by ZhilkinSerg** [comment]
> Why would the game suggest a longer path?

Move cost for roads is smaller than for off-road overmap terrains (fields, trails and dirt roads):
https://github.com/CleverRaven/Cataclysm-DDA/blob/73b6cf73b988b5f1289863e4f507bff8f5b2afdb/src/overmapbuffer.cpp#L868-L885

You need to use wheels with bigger `offroad_rating` on your vehicle if you want to move off-road.

**Comment by ZhilkinSerg** [comment]
> When using vehicles, the speed is reduced to 6 km/h in some locations. On the road, in the field or elsewhere.

Autodrive has speed limits. Read here - https://github.com/CleverRaven/Cataclysm-DDA/blob/73b6cf73b988b5f1289863e4f507bff8f5b2afdb/src/vehicle_autodrive.cpp#L40

**Comment by IdleSol** [comment]
Thank you.

>Move cost for roads is smaller than for off-road overmap terrains (fields, trails and dirt roads):

And how does this manifest for vehicles? A character that spends more moves. What does the vehicle spend? It travels 19 km/h on asphalt and travels 19 km/h in a field. What's the point? Does it affect fuel consumption?

I know that for some vehicles, there is a maximum speed limit. But that threshold is higher than this 19 kilometers per hour. So what's the point of going down the road?

**Comment by PatrikLundell** [comment]
The reason auto driving speed is limited is because it's hard to make a robust feature that doesn't do the Tesla thing and crashes into something it can't recognize.
Acceleration and (to a lesser extent) deceleration are tricky to predict exactly how large they'll be. A miscalculation results in the vehicle ending up in a different location from where it was predicted to be, thus disrupting the whole path, possibly to the extent that a recalculated path no longer have enough safety margin to an obstacle.
In addition to the issues with the path itself, you also have to deal with the fact that the vehicle doesn't occupy a single tile, but rather several tiles in a configuration that morphs based on the orientation.

You need to slow down when facing obstacles in order to ensure the vehicle ends up exactly where it was intended to end up. There are already issues with partial tile displacement sideways (move one tile sideways every X tiles forward), and you'd compound that if the movement forward is also in partial tiles so you'd have to predict when those partial tiles end up in an extra tile of movement.

If I understand it correctly, the fuel consumption is indeed higher off-road. I also believe (without knowing) that the path finding's road preference is a result of a calculation based on the vehicle's performance over different kinds of terrain without accounting for the limited speed the travel can actually be performed at, so if the travel logic was able to actually travel at maximum safe speed the road would be faster.

Making a 360 degree turn for no reason would obviously be a bug. Making a 360 degree turn due to a mobile obstacle might not be, although it seems odd.

Personally I'm amazed this dog speaks, rather than complaining about the deficiencies in it's speech.

However, if someone steps up to try to improve the logic it would be great.

**Comment by IdleSol** [comment]
I realize that using a dynamic velocity value, is additional complexity and calculations. That's why the calculation uses 3 tiles per move.

But we have some interesting parameters. Acceleration, braking and top speed off-road. They depend on wheels, engine and maybe something else. But clearly above 3 tiles per stroke. Why aren't we targeting them?

Let's say the turns are complicated. Straight sections. Conditionally 5 tiles * 5 moves = 25 tiles or ~1 OMT. Straight sections, in the representation of the function responsible for building the route. That is, sections where there are no turns. And if we go straight, let's add speed. And this speed will be calculated so that the car could stop completely in 1 turn.

Total, turns we pass the old way with 1-3 tiles per turn. Straight sections - 5...8 tiles per turn.

Some tests from the game

| Vehicle name | Acceleration (characteristic), km/h | Acceleration (characteristic), tile/turn | Acceleration (real), km/h | Braking, km/h | Speed, km/h |
| :-- | :--: | :--: | :--: | :--: | :--: |
motorcycle (road) | 54 | 8 | 54 | 54..64 | -
motorcycle (field) | 54 | 8 | 28 | 51..53 | 72
motorcycle (tall or long grass) | 54 | 8 | 8 | 20 / 32 | 20 / 32
|  | | | |  |  |
coupe (field) | 26 | 4 | 26 | 45...54 | -
coupe (road) | 26 | 4 | 16 | 43...48 | 118
coupe(tall or long grass) | 26 | 4 | 6 | 37..41 | 33..57

The spread is most likely due to rounding. It depends on what initial speed the braking starts at. Or it's just a bug. For areas with high and long grass. Apparently they have different effects. But since they are intermixed with each other, it's hard to say for sure.

Summary.

We have a section of straight path for which we know the road characteristics. We can calculate the braking. For a motorcycle, that's 8 tiles per stroke. So we can go up to 54 km/h. Or 20/32 if it's long grass sections. And for the coupe, 35-40 km/h.

**Comment by IdleSol** [comment]
I don't know if anyone needs this. And maybe it's already implemented, but I don't know about it.

I suggest adding some tools to test path building and automatic movement.

1. Highlighting the current OMT. For example, using monochrome colors. Or other marking of OMT boundaries.
2. Color visualization of the constructed path. Colored tiles are overlaid on top of the tiles. For example, of blue color. They denote the path on which the player or transport will move. In general, this is the path that is built in driver.omt_path (if I understood correctly). Ideally, we will have a strip of width from 1 tile to the width of the transport.

Obstacles are highlighted in a separate color, red.

3. Ariadne's thread. This is the analog of the 2nd point, but it is built only for the part of the car with coordinates (0,0). It is highlighted with a different color (gold, from the golden Ariadne's thread).
The main difference, it's always one tile wide. For easier perception of the path. Relevant if the transport begins to make loops or "twitch" left-right.

Additionally, you can specify control points: the points of the beginning and end of movement for 1 move. As well as the angle of rotation at these points.

Something like that.
![Example](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/79b65585-fefa-4852-8ac2-f6fd54267420)

4. Adding the possibility of automatic movement with confirmation. That is, it's automatic movement, but requiring confirmation from the user every n moves (on OMT boundaries?). Would allow better response to strange car behavior. Or analyze the constructed path.

**Comment by Uwuewsky** [comment]
Yes, the difference in path costs between roads and fields looks a bit high. It would be nice to change the formula a little since off-road driving isn't that punishing regardless offroad rating of your vehicle.
![road1](https://github.com/CleverRaven/Cataclysm-DDA/assets/99945024/2b662935-d4b0-44e8-ad0a-6b3145afc51c)

**Comment by IdleSol** [comment]
![1](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/28c752e4-c6c8-43af-91d8-58ae33fdcf20)
Is a hayfield considered not driveable?

[Госпорт-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15066185/-trimmed.tar.gz)

**Comment by ZhilkinSerg** [comment]
> Is a hayfield considered not driveable?

Check `travel_cost_type` field in overmap terrain definition. Some terrains are `impassable`.

**Comment by IdleSol** [comment]
If I understand correctly

https://github.com/CleverRaven/Cataclysm-DDA/blob/a60d305954dc305990b83df1c521790bc245be8f/data/json/overmap/overmap_terrain/overmap_terrain_agricultural.json#L149-L157

https://github.com/CleverRaven/Cataclysm-DDA/blob/a60d305954dc305990b83df1c521790bc245be8f/data/json/overmap/overmap_terrain/overmap_terrain_agricultural.json#L25-L31

https://github.com/CleverRaven/Cataclysm-DDA/blob/a60d305954dc305990b83df1c521790bc245be8f/data/json/overmap/overmap_terrain/overmap_terrain.json#L28-L34

Nowhere is the `travel_cost_type` parameter specified. And that's why this OMT is considered impassable?
