### ISSUE TITLE
Objects hanging in the air

### ISSUE THREAD

**Issue by IdleSol** [CleverRaven/Cataclysm-DDA#73073]
### Describe the bug

While playing the game, I came across the "lost backpack" event. It was at z=1 level.

![test 1](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/08c92d58-dc67-48a1-b73d-ca632b14a9ca)

Notice. The backpack hangs in the air and does not fall down.

### Attach save file

[Госпорт-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15011037/-trimmed.tar.gz)

### Steps to reproduce

N/A

### Expected behavior

Hanging items falling to the ground. Neater placement of items appearing by events.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043 (21H1)
- Game Version: cdda-experimental-2024-04-16-1009 73b6cf7 [64-bit]
- Graphics Version: Tiles
- Game Language: Русский <color_dark_gray>(90,3%)</color> [ru]
- Mods loaded: [
    Тёмные Дни Впереди [dda],
    Отключить потребности у НПС [no_npc_food],
    Портальные штормы игнорируют НПС [personal_portal_storms],
    Медленный рост фунгалоидов [no_fungal_growth]
]

### Additional context

After destroying the flower underneath, the backpack fell to the ground. Does the flower serve as a support for the upper level?

**Comment by KHeket** [comment]
Meet this bag too several times, I get floating items by throwing into them rock or glass shards, it make them drop down

**Comment by PatrikLundell** [comment]
The flower does not serve as a support. However, it's destruction may well trigger the call to an operation that checks if anything above doesn't have any support and thus should fall, even though no support was actually removed.

The error, however, lies in whatever places an item. It's probably some kind of map special that places the item on a location without the selection of which locations it can be placed on being coordinated with the placement (possibly because the location has been updated such that there isn't anything supporting that location anymore).
Item placement does not support items to "gravity" checks, but rather assumes that the placement has been selected to be in a legal location (adding checks may well slow down the game too much).
