### ISSUE TITLE
Using a metal bucket as a simple brazier

### ISSUE THREAD

**Issue by halfelftwink** [CleverRaven/Cataclysm-DDA#73187]
### Is your feature request related to a problem? Please describe.

The title says everything. If you think about it, a brazier is just a worse bucket. It doesn't really make sense to be crudely bashing a sheet of metal in to hold a fire if I've already got a nice bucket.

### Solution you would like.

We should have the ability to start fires in buckets without burning the base down. Maybe give it a spot in the Appliances part of the construction menu.

**Comment by KaleProgram** [comment]
Maybe, my one concern is that the brazier is made from sheet metal which is about 100cm^2 according to its profile which is a significantly larger surface area than the bucket which is 25cm. While I don't imagine that would have any practical downside as its just meant to contain a fire, I could see a brazier made from a bucket harder to keep going due to limited air flow unless it is modified it in some way.

Also of course it needs to be metal.

**Comment by halfelftwink** [comment]
That's true, that's true.
You could punch or drill a couple small holes around the side to help with the air flow problem. Gameplay wise I think it'd make good sense. You have a way more portable fire pit with the trade off of it not lasting quite as long.

**Comment by KaleProgram** [comment]
I really like the idea of a portable fire pit that you make with fire or survival skill
