### ISSUE TITLE
ImTUI does not support CJK

### ISSUE THREAD

**Issue by mmyjona** [CleverRaven/Cataclysm-DDA#73205]
### Describe the bug

ImTUI does not support CJK(use libncurses instead of libncursesw)  [see issue](https://github.com/ggerganov/imtui/issues/48). So the ncurse version cannot display popup correctly. Maybe we should fallback to ncurse popup in CJK langs before it's fixed by upstream?

### Attach save file

N/A

### Steps to reproduce

1. lanuch game
2. change to CJK lang
3. trigger any popup

### Expected behavior

Show popup text
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/1235078/8ec53729-f9fb-406f-bd50-0f21a963672d)

### Screenshots

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/1235078/53ad9ae7-d79c-48f2-a92f-8431155b566d)

### Versions and configuration

latest experimental

**Comment by mmyjona** [comment]
It seems to be a known issue based on previous pr [72579](https://github.com/CleverRaven/Cataclysm-DDA/pull/72579)

**Comment by katemonster33** [comment]
You're mostly correct about the underlying issue - for ImTui we need to have some special code that bypasses the need to cache all the CJK character textures, all the code that is the underlying reason for this issue was written with graphical drawing in mind, and since we are drawing with ASCII we need to come up with something else.

If I understand properly, ImFont::RenderText in imgui_draw.cpp needs special handling walled off by '#ifdef IMTUI' that takes all the characters intended to be drawn and just puts them on the screen without checking if they are in the texture cache
