### ISSUE TITLE
Adding Hydroelectric Power and Water Resources at early day

### ISSUE THREAD

**Issue by IoIqq** [CleverRaven/Cataclysm-DDA#73210]
### Is your feature request related to a problem? Please describe.

Do you had played Project Zomboid? When playing CDDA, I've noticed that during the early in-game dates, all residential sinks are devoid of water (while toilets still have some), and so far, I haven't come across any 'lights' or corresponding switches inside game buildings (does this mean people didn't need lighting before the apocalypse?)

### Solution you would like.

①For virtual houses generated in the world, install pendant lights or wall lamps either on the walls or ceilings.
②In the earlier stages of the in-game date, ensure that the houses have access to water and electricity（not only toile！）.
Maybe these will not work someday，but it should have

**Comment by GuardianDll** [comment]
power grid is dead, lack of electricity is direct reason there is no power in houses and all pumps are not active

**Comment by kevingranade** [comment]
As guardian says,  this is working as intended. The power grid is down, water towers are empty.

**Comment by XygenSS** [comment]
This is a closed issue but I would like to clarify rq. Things have been steadily going wrong ingame for a few months as violent riots spread. Default calendar game start begins 2 weeks after things started getting very bad and evacuation orders were sent out. The grid has been down for a good few days or more and municipal water systems lost pressure. Toilets still have water because the cistern above the bowl retains water until flushed.

**Comment by IoIqq** [comment]
> This is a closed issue but I would like to clarify rq. Things have been steadily going wrong ingame for a few months as violent riots spread. Default calendar game start begins 2 weeks after things started getting very bad and evacuation orders were sent out. The grid has been down for a good few days or more and municipal water systems lost pressure. Toilets still have water because the cistern above the bowl retains water until flushed.

No, I also mean that indoors, there should be something that resembles a 'chandelier' or, correspondingly, a switch for it.

**Comment by IoIqq** [comment]
> As guardian says,  this is working as intended. The power grid is down, water towers are empty.

No, I also mean that indoors, there should be something that resembles a 'chandelier' or, correspondingly, a switch for it，not just 'table lamps'.

**Comment by GuardianDll** [comment]
there is enough courage to live in existing buildings, since they are, well, already built, comparing to your own place
it would be good to add some switches and ceiling lamps indeed, i think i saw PR that adds some, but it doesn't sound like something issue named `Adding Hydroelectric Power and Water Resources at early day` talks about

**Comment by IoIqq** [comment]
> there is enough courage to live in existing buildings, since they are, well, already built, comparing to your own place
> it would be good to add some switches and ceiling lamps indeed, i think i saw PR that adds some, but it doesn't sound like something issue named `Adding Hydroelectric Power and Water Resources at early day` talks about

should I set up a new issue for this idea？

**Comment by XygenSS** [comment]
> No, I also mean that indoors, there should be something that resembles a 'chandelier' or, correspondingly, a switch for it.

Ceiling lights should be a seperate feature suggestion/PR. Technically we do have ceiling lights already but not in appliance form.

Switches for the appliance powergrid is a great suggestion but should be a seperate feature suggestion.

**Comment by IoIqq** [comment]
> Ceiling

ok！I get it！thank you
