### ISSUE TITLE
Places where I can't build scaffolding but should. And places where I can but shouldn't

### ISSUE THREAD

**Issue by IdleSol** [CleverRaven/Cataclysm-DDA#73324]
### Describe the bug

I've encountered several places where I can't build scaffolding. I don't know what exactly fails the test.

Normal tile, nothing on it. There is no ceiling (or it is invisible). So I assume that there is either a bug in the map generation here, or a bug in one of the `pre_special` validation functions.

And also places where I could have built scaffolding. But I shouldn't have, because there were foreign objects there.

The modified `constr_scaffolding_pipe_up` construction was used for testing. Construction time and required materials were reduced (1 minute and 1 pipe).

The save number corresponds to the description paragraph and screenshots

1. You can't build scaffolding on tiles. It occurs where there are a lot of trees. I encountered a field on OMT, but it had a group of trees, a row of which had construction problems. Maybe something with the crowns of the trees?
![test 1-1](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/ad3fc930-6e53-4799-8cc9-191536c70533)   ![test 1-2](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/f577ad60-953b-4e41-aae9-ac34b647386f)

2. Tall grass. In my opinion this is a mistake. In terms of the game, maybe not.
![test 2](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/7a50d766-56c9-4a23-8f60-97e70b1c170f)

3. Bamboo. Can be built. So can the next paragraph. I consider it a mistake because you can't build on most other plants.
![test 3](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/9b870248-de72-42b0-8f30-f4b5bb224cde)

4. Fern.
![test 4](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/4039163d-8ca6-43eb-ba45-0f3f25b6f487)

5. Mi-Go roof. You can build on most tiles. But there are some where you can't.
![test 5](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/ca2795b9-082f-4380-999c-ba7239fa5b67)

6. Fortified Fort. The area above the entrance. No scaffolding may be built.
![test 6](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/b0aa9aa9-799b-4e03-a8e5-a988e00d3da9)

7. Sewage Treatment Plant
![test 7-1](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/7755f761-42b1-4633-b251-f4799d2947f4)
![test 7-2](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/3cb8d0e0-f86c-4df1-af9d-f4de4db75398)
![test 7-3](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/314a9ed2-18c7-4165-be0d-4622afe58f00)

8. Wind Turbine. Construction on level 9. But you can't climb them.
![test 8-1](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/2bc77bbf-aa5b-4ab7-846b-97cf1bf0c699)
![test 8-2](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/2e318a88-222a-46df-915a-927f5a3e205b)

### Attach save file

[1.test-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15138264/1.test-trimmed.tar.gz)
[2.test-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15138265/2.test-trimmed.tar.gz)
[3.test-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15138266/3.test-trimmed.tar.gz)
[4.test-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15138268/4.test-trimmed.tar.gz)
[5.test-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15138269/5.test-trimmed.tar.gz)
[6.test-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15138270/6.test-trimmed.tar.gz)
[7.test-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15138352/7.test-trimmed.tar.gz)
[8.test-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15138272/8.test-trimmed.tar.gz)

### Steps to reproduce

n/a

### Expected behavior

n/a

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043 (21H1)
- Game Version: cdda-experimental-2024-04-27-0815 7e7510c [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

You can't build on upturned dirt. I don't think it's a mistake, but maybe you have a different opinion.
Fungal bed. Can we build on it? You can't build on it now.

**Comment by PatrikLundell** [comment]
Thanks.
I'll look at it tomorrow.
It's most probably an issue with the pre_special definitions. I can't rule out issues with some pre_specials themselves, but it might be a matter of an unsuitable set of them.

**Comment by PatrikLundell** [comment]
1. Very lucky/unlucky placement. There are sewage pipes below ground here. The single support check fails because there's not enough support from below (the scaffolding would presumably crash through the ground).
2. Tall grass does not have the "FLAT" flag, which causes the empty check to fail. This is a very common check...
3. Bamboo has the "FLAT" flag, except for the tall bamboo (somewhat like tall grass).
4. Fern has the "FLAT" flag. The reason you can't build on plants is that the empty check rejects places with items on them, and plants are generally items. Grass, bamboo, and fern are terrain, in contrast.
5. It's the single support requirement kicking in again. There are walls beneath the two accepted tiles, but a roof at the level below for the others.
6. Single support again. There's wall under the legal tiles, but a space under the others.
7. Sewage under the illegal tiles in the first case. Glass walls under the second case legal tiles, while rooms under the illegal ones. Wall and door under the legal ones in the last case, with rooms under the others.
8. The construction issue is again due to the single support requirement. The issue with not being able to go up seems to be a bug in the game: The code assumes the map goes up to and including Z=10, but you can't actually go higher than Z=9. You can't look up to Z=10, and the debug functionality to modify the map doesn't allow me to look at Z=10 either.
Something is wrong in the game. #73353 produced.

I'm still considering whether to remove the support requirement or whether to tell the player about it.
I'm not going to do anything about bamboo/grass/fern, as that's a standard construction check. If you think that should be changed, feel free to write a suggestion or bug report (this is a borderline case between the two).
