### ISSUE TITLE
Exploit: boiled bandages produce clean water too fast

### ISSUE THREAD

**Issue by Brambor** [CleverRaven/Cataclysm-DDA#73333]
### Describe the bug

When making `boiled makeshift bandages`, you can make 100 clean water as a byproduct in under 20 mins (it says it makes 1 but it makes 2 portions). Making 50 clean water directly would take 3 hours and 21 minutes.

While the batch bonus on `clean water` is 20%, it is 95% with `boiled makeshift bandages`.

### Attach save file

N/A

### Steps to reproduce

Look at the recipes

### Expected behavior

Adding filty bandages to water doesn't make it clean faster.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4291 (22H2)
- Game Version: 0.G-9005-g6700088ca4-dirty [64-bit] master was 2e32db95af
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by Brambor** [comment]
Maybe just make the water a tool? Don't produce any clean water?

**Comment by GuardianDll** [comment]
i believe to make \*boiled\* makeshift bandages, one would need to boil the water, and then hold the bandages in this thing for a while. Since the recipe uses 9 bandages (total volume 144 ml), i don't think making water as a tool would be sufficient - making whatever amount of boiled bandages using only 1 water (tools do not allow to require more than one item presented), and with the very fact you can disinfect cotton bandages by boiling and then get clean water is rather odd, i'd recommend ~~remove the recipe and item entirely~~ make it always return generic water
i'd also ping @Venera3 since they may have a professional, doctor opinion about it

**Comment by Venera3** [comment]
You can go with 10mins or so of boiling time to get them clean and return x-1 units of generic water. I'd also make it use clean water while we're at it.

**Comment by Brambor** [comment]
> You can go with 10mins or so of boiling time to get them clean and return x-1 units of generic water. I'd also make it use clean water while we're at it.

I like the subtle change that boiling bandages will no longer be possible without a container to put the clean water into.
