### ISSUE TITLE
stamina regains when dodge enemy attacks

### ISSUE THREAD

**Issue by mikkatenka** [CleverRaven/Cataclysm-DDA#73349]
### Describe the bug

checked stamina when dodging, it wasn't decreasing.
bugs since this version "Cataclysm-DDA experimental build 2024-02-04-0113"

### Attach save file

N/A

### Steps to reproduce

1.launch the latest version
2.dodging will regain stamina

### Expected behavior

stamina will gradually decrease while dodging

### Screenshots

![a](https://github.com/CleverRaven/Cataclysm-DDA/assets/145435211/56c7c137-d0cd-4d99-848f-32f6ca3e235d)

### Versions and configuration

OS: Windows
experimental build 2024-04-27-2312

**Comment by osuphobia** [comment]
This case is similar to the one I found https://github.com/CleverRaven/Cataclysm-DDA/issues/73287.
https://github.com/CleverRaven/Cataclysm-DDA/blob/f4014754b95e5260e13d5876c84972c735041ed6/src/character.cpp#L1932-L1948
The difference is, this dodge thing is caused by https://github.com/CleverRaven/Cataclysm-DDA/pull/70828 where @anoobindisguise accidentally forgot to add the minus sign (only in get_dodge(), other functions affected are fine AFAIK), and the RAS weapon one was there for ages.
