### ISSUE TITLE
Bow Shooting Takes Too Long

### ISSUE THREAD

**Issue by Alm999** [CleverRaven/Cataclysm-DDA#73354]
### Describe the bug

It seems after https://github.com/CleverRaven/Cataclysm-DDA/pull/73305 bow shooting time has been broken.

My character has 10 marksmanship and 10 archery:
![bows_01_stats](https://github.com/CleverRaven/Cataclysm-DDA/assets/125039757/2beccc87-2930-4ea3-af4e-cfc513e81f8e)
However, it takes 344 moves to shoot an arrow without even aiming:
![bows_02_initial_aiming_(target)](https://github.com/CleverRaven/Cataclysm-DDA/assets/125039757/c55ae139-2ba4-42f9-95ee-9fc06f8d061d)
And after spending ~90 moves gaining steadiness it still takes 277 moves (~2.8 seconds) to just release an arrow.

Another test, now with actual enemy. Initial readiness:
![bows_04_initial_aiming_(enemy)](https://github.com/CleverRaven/Cataclysm-DDA/assets/125039757/49b72756-11d5-4ede-92d2-c19dad49d3e9)
And after getting aiming to the "Precise Aim" level it still takes 269 moves (~2.7 seconds) to just release the arrow:
![bows_05_full_steadiness_(enemy)](https://github.com/CleverRaven/Cataclysm-DDA/assets/125039757/877d6a99-eebf-4170-b8dd-651d0d6eae0c)

Even if we assume these ~270 moves are spent loading another arrow for second shot (https://github.com/CleverRaven/Cataclysm-DDA/pull/73305 mentioned), moves still do not add. This bow takes 50 moves to load:
![bows_06_bow_stats](https://github.com/CleverRaven/Cataclysm-DDA/assets/125039757/4bc3f568-64b2-4ee4-bb57-6f12c6ef62e3)
and the quiver takes 20 moves to fetch an arrow from:
![bows_07_quiver_stats](https://github.com/CleverRaven/Cataclysm-DDA/assets/125039757/baf73dfc-f527-4833-aae1-cecc28a70cc7)
So, total moves spent to reload shall be around 70, not 270. So, where are those additional 200 moves come from?

Addition: even after disabling the "Reaim after firing" option, I still get the 269 moves to shoot without spending any time aiming, so these 269 move are not related to reloading.

### Attach save file

[Skyforest-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15141771/Skyforest-trimmed.tar.gz)

### Steps to reproduce

1. Wield a bow and wear a quiver.
2. Try aiming at target with "f" key.
3. Observe the amount of moves required.
4. Actually shoot to witness that indeed these movees were spent and ~3 seconds have passed.

### Expected behavior

I expect a character to be able to release an arrow in approximately 10 moves (0.1 second) -- standard human reaction time, AFAIK -- after his/her bow is loaded and aimed at target/enemy. Or, perhaps, ~23 moves or so (the same amount that is needed to pull the trigger of M16A1 rifle in-game).

I also expect 70 moves (20 to get an arrow and 50 to insert it) to be spent getting a bow initially readied to shoot (i.e. after the "f" button has been pushed to aim but before the aiming interface appears).

### Screenshots

See bug description.

### Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: cdda-experimental-2024-04-28-0239 ed85b64 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

N/A

**Comment by osuphobia** [comment]
It's not broken.
The main reason that it takes a long time to shoot is you put that many arrows in your quiver.
![reloadtime](https://github.com/CleverRaven/Cataclysm-DDA/assets/78858975/898869ce-4cdc-4519-bc91-431d8e67a8cb)
The reload time from your quiver(249) is even longer than from the ground(113).
![reloadtime2](https://github.com/CleverRaven/Cataclysm-DDA/assets/78858975/574334d1-5861-4dca-944b-3e48bdf95721)
If you left only one arrow in your quiver, the reload time also reduced to 53 moves.
![firetime](https://github.com/CleverRaven/Cataclysm-DDA/assets/78858975/d23ac8b0-5e9e-4994-a8a9-f2db02651307)
Plus, the basic time needed to fire your bow is 95, so all the moves needed is 344.
The time needed to shoot didn't change, you just didn't notice you need that much time to shoot with a quiver.
Again, left only one arrow in your quiver, below is the time needed after the PR:
![shoottime2](https://github.com/CleverRaven/Cataclysm-DDA/assets/78858975/e2797bed-5fd7-4b07-83ca-00be6673acab)

**Comment by Alm999** [comment]
> It's not broken.

Thank you. The character tries to get all 52 arrows just to load one and then put the rest (51) back into the quiver.

Now I see that this is **definitely** broken. The calculated moves to draw an arrow should be per arrow, not for the whole bulk.

Also as I understand right now the character first aims the bow and only then!!! takes an arrow and loads it. How can anyone aim a bow without loading an arrow first? Does the bow just hangs in the air in the same position while the character inserts the arrow?

**Comment by osuphobia** [comment]
>The calculated moves to draw an arrow should be per arrow, not for the whole bulk.
Well, if you consider it as broken, at least it was not broken by me :)

About the order of aiming and shooting, it's not that important if you see it as a whole. The real thing is, to change the function so you don't get every single move "refunded" when deciding not to shoot and walk away. But I didn't find a way to do it properly right now, so just did a port over. Might be less realistic, but still much more intuitive IMO.

**Comment by Alm999** [comment]
> Well, if you consider it as broken, at least it was not broken by me :)

Yes, if anything, your patch hes helped expose weirdness in loading calculations.

I suppose, there is a code that adjusts item access time based on item size. And as 52 arrows are not really 52 individual items but rather a single "arrow" with 52 charges, this code "adjusts" the time based on the combined "item" mass/volume/whatever.

**Comment by cosmo-naut** [comment]
It seems as though there are two separate issues:

A quiver taking longer to draw an arrow when there are many arrows, and shorter to draw when there is only one, is also a bug because it does not accurately reflect reality.

The bow being aimed fully and then having an arrow is a bug, because that is not how bows behave in real life.
_Caveat: You could technically argue that a component of aiming is to first eye off the target before even raising your weapon, and I'm sure there are archers that could do this, however the common interpretation of aiming a bow is that there is an arrow notched and the string is drawn_

Perhaps one of the inconsistencies is that bows are being treated somewhat similar to firearms

**Comment by natsirt721** [comment]
I don't think the caveat holds here - presumably you're already eyeing down your target and have a loose range estimate on the order 10's of yards by the time you decide to draw on it.  That's not something you're taking multiple seconds to assess, its going to be an intuition-based estimate that you start consciously assessing range from. Not to mention that range is not the only component of aiming, especially against a moving target. With auto-reaim on though, it seems unfair to penalize the character for drawing another arrow if the player's intention is to stop firing. 

Frankly I don't see why bows can't be reloaded like any other firearm. All of them already have the two-handed fire flag, so it isn't unreasonable to assume that 'loading' the bow means 'arrow in hand' or even 'nocked but not drawn'. That would make this whole problem moot. 

It does make archery mains slightly more annoying since you have to manually (r)eload after every shot but that seems like a reasonable tradeoff for consistent interaction.

**Comment by osuphobia** [comment]
@cosmo-naut 
The way bow works before the PR:

1. Pressing f to choose the arrow and immediately reload with it.
2. Steady your aim or fire your bow, then the moves needed for reloading is consumed at once.
3. Not to shoot and quit the aim ui, with your bow unloaded immediately.

In step two, there were two bugs. The first one is, if you press f to enter the aim ui, then immediately quit it without any aiming action, you were supposed to get all the moves "refunded". The functions were wrote in that way, but failed to do so, thus you were losing moves by simply entering the aim ui. That's why auto re-aiming was banned for RAS weapon.
The second one is, if you aim at an adjacent tile and try pressing `.` to steady your aim, since that it can not be steadier, you just wait for one turn. Then, despite that there is an arrow notched, the moves needed for reloading is not consumed, firing your bow or quitting the aim ui will not consume the moves either.

Also, for all the other firmarms without RAS flag, simply quitting the aim ui do not mean you give up shooting, nor is the aiming progress lost. All that things makes it annoying to fight with RAS weapons.

There were a lot of discussions about this issue, yet no one did move on and implement their plan. So I choosed an existing solution.
As I mentioned above, it's not that important if you see it as a whole. Just need to change the function so you don't get every single move "refunded" when deciding not to shoot and walk away. I am trying to make it more consistent, but I don't think the situation at this point is worse than before. Like, many of you just didn't know exactly how much time is needed to shoot your bow, right?

**Comment by osuphobia** [comment]
> > Well, if you consider it as broken, at least it was not broken by me :)
> 
> Yes, if anything, your patch hes helped expose weirdness in loading calculations.
> 
> I suppose, there is a code that adjusts item access time based on item size. And as 52 arrows are not really 52 individual items but rather a single "arrow" with 52 charges, this code "adjusts" the time based on the combined "item" mass/volume/whatever.
> 
> I believe this also affects staff sling and its "rock" ammunition.

Maybe `item_handling_cost` is the function responsible?
https://github.com/CleverRaven/Cataclysm-DDA/blob/91763a378a1f3e163be63520578c0a3b380bb169/src/character.cpp#L7286-L7293

**Comment by Alm999** [comment]
> This is 4-5 extra moves per arrow, some what reasonable I think, taking an arrow out of 50 arrows should cost more time. Cap it at like 50 moves for RAS weapon would be a solution.

Yes, it seems that this function is the culprit. However, arrows in a quiver are not interlocked so there shall be little to no difference between getting an arrow from nearly full or almost empty quiver.

The main issue is "**charges**". Right now we do not have 52 arrows in the quiver. We have a **single really big arrow with 52 charges** and each time a character tries to get this arrow (s)he spends the amount of moves needed to fetch that big arrow.

Charges are causing a lot of issues and I believe this is one of them. Either the "it.volume()" function needs to be re-written to accept X amount of charges as an argument to correctly retrieve the volume of X arrows instead of all of the bulk, or arrows (and possibly other ammunition) shall be "discharged". The later will also fix character's miraculous ability to hold 125 rocks (or shall I say "**rock (125)**"?) in her/his hands like a juggler.

**Comment by Alm999** [comment]
> mv += std::min( 200, it.volume( false, false, charges_in_it ) / 20_ml );

Oh, maybe the function can already accept charges via **charges_in_it** argument… Maybe in this case this agument has to be set to 1 (because we are getting just one arrow to load).

**Comment by osuphobia** [comment]
When reloading, you need to obtain the ammo and reload it.
https://github.com/CleverRaven/Cataclysm-DDA/blob/5d07bebaca4782e40cec7690d455bb01d2e102c9/src/item.cpp#L11532-L11534
In `item_reload_cost()` everything goes well, `qty` is passed to `charges_in_it` to correctly calculate penalties.
https://github.com/CleverRaven/Cataclysm-DDA/blob/5d07bebaca4782e40cec7690d455bb01d2e102c9/src/item_location.cpp#L720
But in `obtain_cost()`, or more exactly, when calculating obtain cost from container, `qty` is lost, so `charges_in_it` is -1, thus penalties is counted by the volume of the whole bulk.
