### ISSUE TITLE
Shattering already shattered armor

### ISSUE THREAD

**Issue by DragonWizard23** [CleverRaven/Cataclysm-DDA#73351]
### Describe the bug

While I really like what #72974 adds, I think it is missing a check for already shattered armor. I've discovered that it is possible to shatter armor twice and I think this is a bug (though the very shattered armor idea sounds interesting). 

### Attach save file

[2024-03-31-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15140717/2024-03-31-trimmed.tar.gz)

### Steps to reproduce

1. Make a player and spawn some zombie cops. 
2. Attack the zombie cops with a decent amount of damage (I've been using a USMC bayonet). 
3. Eventually, you will shatter their armor. If this happens twice, you've successfully replicated this issue!

### Expected behavior

I did not expect to be able to shatter armor that has already been shattered, at least not without a secondary level of shattering. If there are plans to add a second level of shattering, I would suggest that we use "fractured" as the first level and "shattered" as the second level. Shattered sounds like a maximum level of breakage, beyond which no further damage could apply. 

### Screenshots

![Screenshot (398)](https://github.com/CleverRaven/Cataclysm-DDA/assets/151102088/ca93a5c3-c4a1-4b97-afcb-366e5f220199)
The log message containing the 1st and 2nd shattering. 

![Screenshot (399)](https://github.com/CleverRaven/Cataclysm-DDA/assets/151102088/b481d4d5-f0bb-4827-8e77-1f3835b45358)
Interestingly, "shattered" is not capitalized, but "Heavy Bleeding" is. 

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.3447 (23H2)
- Game Version: 4551df2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

This does not cause the game to crash.

**Comment by osuphobia** [comment]
![cc803b4601ed7994af97638fe0bc202](https://github.com/CleverRaven/Cataclysm-DDA/assets/78858975/215872be-e895-47fc-b8ba-dabb8bf52dfd)

It turns out that shattering already shattered armor is not the only problem of this content.
We are using a stable sorting algorithms for weakpoint sorting, so the order will not be changed if two wps in one weakpoint set have the same coverage.
As you can see in the pic above, armour_plate_bullet/armour_plate_melee and armour_shattered all have 40 coverage, so we can only check armour_shattered when the former wp did not pass the RNG.
And when you got wp_skill high enough, a wp with 40 coverage is unlikely to fail the check. 
Something like coverage 50 and coverage_mult 0.8 will have the same effect, but can get rid of this problem.

![画像1](https://github.com/CleverRaven/Cataclysm-DDA/assets/78858975/8f03806f-b3d7-4480-be24-1b0386fa3fe3)
![画像2](https://github.com/CleverRaven/Cataclysm-DDA/assets/78858975/834fa94b-d3c2-4c36-a59e-d9a03b6d7836)
![画像3](https://github.com/CleverRaven/Cataclysm-DDA/assets/78858975/1a80307d-74f1-4f07-a0ba-52a12d465bb9)

Another thing is not relevant to the PR in question but also annoying.
That is, there might be something wrong with our weakpoint sorting:
They should be sorted by coverage, but it's not working properly.
If I get it right, it's sorted for every weakpoint set, but when there are duplicate weakpoint ids, the latter one just replace the former one, so the coverage of the weakpoint is changed but it's not got sorted again?
Or it's only sorted in the weakpoint set, not between? Anyway, they should be all sorted by coverage, otherwise we may get weakpoints with low coverage never being picked.
