### ISSUE TITLE
Looted Libraries instead of Burning/Burned Libraries:

### ISSUE THREAD

**Issue by AzyWng** [CleverRaven/Cataclysm-DDA#73363]
### Is your feature request related to a problem? Please describe.

Some discussion on the Cataclysm Discord suggests that libraries often spawn with a burned/burning variant.

It confuses me a little that only libraries seem to have this variant, and, not, for example, office towers or gas stations. In between people using molotov cocktails and zombies that can burst into flames on death, I can accept that there are fires in buildings in the Cataclysm - I'm just confused as to why it's only libraries getting this treatment.

### Solution you would like.

Instead of libraries having a burned variant, have a looted variant instead. Similar to pharmacies or grocery stores, I can see some people seeking out and looting these places since what they contain is valuable.

### Describe alternatives you have considered.

Have a chance for fires to spawn through overmap specials or similar. In between the aforementioned people using molotov cocktails or other incendiary devices, or electrical fires and gas leaks in the aftermath of a massive disaster, it's plausible for more fires to have started.

Alternatively, remove burned libraries entirely. This is much less work than making new variants of maps or an overmap special for random fires.

**Comment by Inglonias** [comment]
I also find it a little silly that libraries are the only variant of buildings that can spawn actively on fire. Either add this feature to all city structures or remove it and find some other way to apply gameplay balance to a building whose literal, IRL purpose is to put every book you could possibly want in one place for free.

**Comment by Vaskritaya** [comment]
I don't think I've seen one spawn actually on fire, or at least never noticed it. If that's the case, i'd agree that there should be a very small chance of any given building being on fire, although it should be a vanishingly low chance. What are the odds a building just so happens to be starting to burn down right as you come across it? Already damaged variants should be more common, though still quite rare.

As for balance, it's a weird one. I feel like the game has been leaning more towards realism than gamey forms of balance, and libraries happening to be special buildings deserving of extreme countermeasures runs counter to that, imo.

I feel the most sane way to balance things without breaking realism would be to have most libraries be the typical local libraries you find in america. On the smaller side, terribly underfunded, with a more narrow stock that leans heavily towards books useless to a survivor like fiction and history. Chuck in some cds or floppy disks, maybe. Larger public or university libraries could appear in larger cities, and contain a greater assortment of useful books, as well as useless relics like microfilm projectors or city records.

**Comment by Inglonias** [comment]
> As for balance, it's a weird one. I feel like the game has been leaning more towards realism than gamey forms of balance, and libraries happening to be special buildings deserving of extreme countermeasures runs counter to that, imo.

It was necessary at the time to prevent survivors from trivializing the early game - Skills used to be a single level rather than theoretical and practical levels, and crafting times used to be much shorter, since you had to do it in one sitting and couldn't set aside something that was half-complete - a crafting time of more than twelve hours would basically result in death if you tried to do it.

The end result was that in earlier versions of the game, a survivor could raid a library, take every book they needed, go home, read all the combat related books, and become an expert in every weapon known to man in a matter of days or weeks.

This is much less of a problem now - certainly worth another look.

**Comment by Maleclypse** [comment]
Looted libraries are already a variant.  Gunstores, groceries and I think pharmacies also have looted/destroyed variants.  The vandalized variants need a chance to be on fire probably.  Anyway all locations need this treatment, every body complains about it but nobody really adds the content.  Partially though that's due to the fact that we'd rather have this on a city level determination so that city A is lightly damaged and 90% of buildings in it have at most some busted windows, to City B major riots which would have tons of looted structures, all the way to City C kaiju attack total destruction with fires and craters all around.
