### ISSUE TITLE
[CR] Leg ammo pouch discussion

### ISSUE THREAD

**Issue by DragonWizard23** [CleverRaven/Cataclysm-DDA#73417]
### Is your feature request related to a problem? Please describe.

I am seeking input on how the leg ammo pouch should be changed. Its description says that it holds two magazines, but its pockets are not holsters, allowing for multiple magazines to be stored in each pocket. 

### Solution you would like.

I think there are a couple of ways we can rectify this, but I'm not sure which is the best option. 
~A) We can turn the two existing pockets into holsters, so only two magazines can be stored, matching the description.~ This is overly limiting and doesn't match the US market. Instead, it has been suggested that we let each pocket hold two 5.56 30-round NATO magazines.  
~B) Alternatively, we could do option A and add option B as a new item, e.g. "high-capacity leg ammo pouch".~

### Describe alternatives you have considered.
We could split the leg ammo pouch into two items: pistol caliber (.9mm, .40, .45, maybe .22) and rifle caliber (.223/5.56mm and/or .308/7.62mm). The pistol caliber version would mostly be found among police forces and would have six holsters for pistol magazines. The rifle caliber version would be more suited for military, possibly a 2x2 magazine pouch. 

### Additional context

Here are a couple examples of real-world leg ammo pouches. The first one holds 6 .40 mags, the second one holds 6 30-round M4 mags, but I think it would be bulkier than 2 encumbrance. The final one holds two 30-round M4 mags. 
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/151102088/ed119a8d-4695-41b8-b09c-138c9666ce5a)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/151102088/09dfbdbd-be8b-454d-8f51-a53f54172952)
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/151102088/91b98b68-7383-44f5-abb6-08425e9bb32e)

**Comment by ExplosiveRunes** [comment]
An alternate solution could simply be to change the language in the description to more accurately reflect the pouches actual capacity, something like "A fabric ammo pouch that can be strapped to your leg. It has two pockets, each large enough to hold most rifle magazines."

**Comment by DragonWizard23** [comment]
Hi ExplosiveRunes, thanks for the comment! That would fix the difference between the description and behavior. However, we already have the drop leg pouch and drop leg bag for leg storage. I think it would be beneficial to differentiate the leg ammo pouch from those other options, by specializing it for magazines. The leg ammo pouch has a quick time to remove items (40 moves) which is similar to holsters/specialized storage options, while the drop leg bag has 100/120 moves and the drop leg pouch is 80 moves.

**Comment by Hyperseeker** [comment]
Leg pouches for magazines commonly feature multi-magazine capacity per pocket. This is also common for chest rigs and other similar tactical equipment. This is intentional, though I'm not clear on the design considerations behind it.

Notably, two-magazine rifle pouches are a staple of the MOLLE II modular equipment system: the set of US Army gear that started off the whole "MOLLE pouches" trend. You can see them being listed in [the purchase description](https://ciehub.info/spec/PD/CO-PD-02-02N.pdf) and shown (albeit in a very-limited capacity) in [the operator's manual](https://ciehub.info/ref/TM/10-8465-236-10_2013-06-20.pdf). [Here](https://smithssurplusandsupply.com/product/m4-double-mag-pouch-ocp/) is what one looks like in the flesh, as it were. One of the photos depicts the pouch from the side; it's hard to tell unless you know what you're looking at, but those are two M4 magazines (what the game refers to as STANAG magazines), side-to-side, in the pouch.

I've genuinely struggled to find a small-capacity leg magazine bag while modelling those for [Armory](https://github.com/FrontierMods/Armory). This tells me that such "high-capacity" bags (like the third one, which is from a popular tactical brand Condor) are common and popular. Going out of your way to reduce their capacity would be going against one of the desired goals of the game: realism.

Also, for what it's worth, there's a reason 7.62mm NATO magazines are incompatible with 5.56mm NATO magazines IRL: the former are longer because their cartridges are longer, so pockets for the latter would not accomodate them. So, saying the leg bag fits most rifle magazines would not be exactly true. (Or, well, it could *maybe* fit *one* 7.62 magazine, depending on the design of the pocket.)

**Comment by DragonWizard23** [comment]
Hyperseeker, thanks for the detailed post! The operator's manual is a really interesting find. 

I did a bit of in-game testing, and the leg ammo pouch currently holds up to 12 Sig Pro .40 12 round mags, or 2 STANAG 30 round mags, with quite a bit of extra space in the pockets. 

> Also, for what it's worth, there's a reason 7.62mm NATO magazines are incompatible with 5.56mm NATO magazines IRL: the former are longer because their cartridges are longer, so pockets for the latter would not accomodate them. So, saying the leg bag fits most rifle magazines would not be exactly true. (Or, well, it could maybe fit one 7.62 magazine, depending on the design of the pocket.)

Thanks for pointing that out! I did some Google-Fu (well, actually Bing but whatever) and was able to find [a two-mag pouch for 7.62mm](https://tacticaltailor.com/fight-light-7-62-6-8x51-double-mag-pouch/), but 5.56mm double pouches were definitely the most common. Single mag 7.62 pouches were more prevalent than double 7.62 pouches. 

I'll update the initial post with your feedback.

**Comment by Hyperseeker** [comment]
I've just read through the updated suggestion.

> The pistol caliber version would mostly be found among police forces and would have six holsters for pistol magazines

FYI: the pouch you provided as an example of this is actually intended for 40mm grenades. It would hold pistol magazines no problem, sure, but that's not its intention, which is reflected in its design. A multi-magazine pistol pouch could be made a lot more-compact.

In my research for Armory, what I've seen the most of was pistol magazine pouches as a belt accessory. This includes MOLLE pouches (worn on belts such as [this one](https://www.blackhawk.com/tactical-nylon/gun-belts/foundation-series-black-belt-with-cobra/P1628178.html), which I may or may not have chosen for Armory due to a recommendation of it as a duty belt) and belt pouches (worn on belts such as [this one](https://patrolstore.com/collections/police-and-security-belts/products/peter-jones-50mm-leather-belt-double-pronged-buckle) or [this one](https://patrolstore.com/collections/police-and-security-belts/products/op-zulu-uniform-comfort-belt)). There is a good variety of non-MOLLE belt pouches which isn't at all represented in the game.

[This](https://www.recoilweb.com/wp-content/uploads/2022/02/drop-leg-mag-pouch-4.jpg) is a common loadout I've seen on a MOLLE belt. It features a large variety of pouches that have so far been only seen mounted on a plate carrier (ballistic vest) or a load-bearing vest. You may notice that it features, among other things, two pistol-magazine pouches. MOLLE II features pistol-mag pouches (both old, for the previous-issue M9, and new, for the current-issue M17/M18), too, but I haven't yet seen their use on a belt. (So far, I've only seen deployed soldiers with non-MOLLE belts on, to which non-MOLLE belt pouches were sometimes mounted.)

The way I see it, drop leg pouches like the one(s) we're discussing are uncommon, and where they exist, they exist on the civilian market only. Even then, I've seen far-more belt loadouts (either augmenting a plate-carrier/LBV loadout or on their own) than leg rigs like that one. So, while they most-certainly exist, they seem to be out of favor with both tactical-gear enthusiasts and professional law-enforcement officers (such as SWAT members). My research indicates that the plate carrier/LBV and the belt are the focal points of modular pouches and holsters, not leg rigs.

As such, as far as augmenting the avatar's ability to carry ammo, I would suggest looking towards belts and belt pouches (both MOLLE and non-MOLLE, in that order). For one, the base game doesn't even have pistol-magazine pouches. The closest the base game gets is the ankle ammo pouch, which is specifically stated to hold a single small magazine; even then, its capacity is large-enough to accomodate an SMG magazine after the relatively-recent magazine size audit, as the ankle pouch clearly hasn't been audited in a while.

For what it's worth, there exist a variety of leg rigs, but most of them focus on providing

* a holster
* pockets for rifle magazines
* a pouch for emergency medical supplies (think IFAK/AFAK)
* PALS webbing to hold additional pouches

Check out [Condor](https://condoroutdoor.com/collections/leg-rigs) and [HSGI](https://www.highspeedgear.com/tactical-gear/additional-platforms/drop-leg-rigs) to see the variety of choices. The only rigs with pistol magazines are usually rigs that also provide rifle-mag and/or utility pouches.
