### ISSUE TITLE
Analyzing the perfomance of hot dogs

### ISSUE THREAD

**Issue by GuardianDll** [CleverRaven/Cataclysm-DDA#73502]
### Describe the bug

While playing the game, i made a lot of hotdogs, put them all in the same vehicle tile, and found my PC needs at least two seconds to open AIM with said hotdogs
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/67688115/a79449aa-6558-40a3-b07e-656026929b97)
Perfomance analyzer shows enormous amount of hits in uncraft components
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/67688115/2e8b945c-6f91-4fbe-af5a-9a5378eca5ca)
Further discussion and @RenechCDDA making suggestions is [here](https://discord.com/channels/598523535169945603/598529174302490644/1236041870518521876), tho i barely undestand where exactly the problem is, but i guess the game, for some reason, scan all the food to check their disassembly components

### Attach save file

[Freedom-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15209322/Freedom-trimmed.tar.gz)

### Steps to reproduce

open the save file
open AIM pointing to south west ↙
notice the lag

### Expected behavior

no lag

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4291 (22H2)
- Game Version: cdda-experimental-2024-05-01-0547 5590543 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Work in Progress Limb Stuff [limb_wip],
    Mind Over Matter [mindovermatter]
]

**Comment by MNG-cataclysm** [comment]
This has to be one of, if not the most ridiculous error I've ever heard of.

**Comment by RenechCDDA** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/64321d67f81ae7a0ac1fa75e26921d3e734bb73f/src/advanced_inv_area.cpp#L287-L292

So basically the problem is here. As AIM starts assembling its stacks, it checks items against every existing item in every stack. In the provided save, there are ~600 hot dogs laying around in a pile of 482 and then two piles of ~50. So once the pile of 482 is assembled in <100ms, the remaining piles start getting assembled... one item at a time. So it picks up one new hot dog, checks it against **482 existing hot dogs** and makes the very expensive component comparison for each of them. And then it does it again. And again. And again. Until it has checked it against all 482 of the existing hot dog stack, before deciding to put it in a new stack. Repeat for hot dogs 2-52.

What I do not understand is **why** it insists on doing it against every item in the stack. Since these stacks  were already built by AIM, we already know that they will not stack once we hit the first one which doesn't stack.

It is a very deliberate design decision, and it's easy enough to tear down, but *why*?

**Comment by akrieger** [comment]
Or we can make `get_uncraft_components` 1000% cheaper.
