### ISSUE TITLE
Hydration pack change 5/5/2024

### ISSUE THREAD

**Issue by DaniBergson** [CleverRaven/Cataclysm-DDA#73535]
### Describe the bug

The recent change to hydration packs from a hard container to a soft container have them no longer able to fit inside of hydration pack pockets in various backpacks when filled. Base size remains 3.01L when empty, but when filled with its capacity of 3L, size expands to 6L and the hydration pack no longer fits inside the hydration pack pocket. This causes the hydration pack to either migrate pockets to allow it to remain carried, or to fall to the ground if there is insufficient space on the character. 

### Attach save file

N/A

### Steps to reproduce

Put a hydration pack in a backpack with a hydration pack pocket.
move to a source of liquid and refill the hydration pack. 
hydration pack should move locations to the main pocket of the backpack or fall on the ground

### Expected behavior

hydration pack in a hydration pack pocket would remain in the pocket empty or filled. 

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4291 (22H2)
- Game Version: eefe407 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    Alternative Map Key [alt_map_key],
    Bombastic Perks [bombastic_perks],
    Extra Mutated Scenarios [extra_mut_scens],
    Mythical Martial Arts [MMA],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by RenechCDDA** [comment]
Introduced by #73458: https://github.com/CleverRaven/Cataclysm-DDA/commit/90d66204e052b13f72eb832ca85e426d7a4b3d16#diff-3b5e77af241361f4c6322380af7aa240969fb06f9715a21b8bdd283a38a337f2L1599

Simple one line change to return `"rigid": true,` to it.

**Comment by Hyperseeker** [comment]
That assumes the bladder is meant to be rigid, as some Camelbak-produced can be (including [this 3-liter rigid reservoir](https://www.camelbak.com/shop/hydration-reservoirs/crux-3l-reservoir/CB-1228.html)).

I've touched upon [why this isn't necessarily the case](https://github.com/CleverRaven/Cataclysm-DDA/issues/73508#issuecomment-2094548892), given that (1) MOLLE packs have a designated hydration-bladder pocket in them, (2) soldiers spawn with said bladder. Both of these points imply that the bladder could well be the [MOLLE II hydration bladder](https://ciehub.info/equipment/loadbearing/MOLLE2/HydrationSystem.html), and both of the models that exist under this designation ([Hydramax](https://www.mcguirearmynavy.com/products/gi-molle-ii-hydramax-hydration-system-carrier-3l-bladder) and [Storm](https://www.ozarkoutdoorz.com/products/hydration-storm-carrier-and-bladder-molle-ii-foliage-green-new)) are decidedly flexible. (Coincidentally, the Storm one has a clear print of Camelbak on it. One can understand how the military-specific bladder could get its "civilian" name.)

This only leads to me believing that a proper solution would be a reasonable adjustment to the volume of an empty `camelbak` (roughly 250 mL, as mentioned in my comment linked above) and to the volume of the pockets in packs, MOLLE or otherwise.
