### ISSUE TITLE
[MOM] Teleport NPCs w/ gateway

### ISSUE THREAD

**Issue by PGR-14** [CleverRaven/Cataclysm-DDA#73580]
### Is your feature request related to a problem? Please describe.

If I can teleport a bandit to the void, why can't I teleport someone to an attuned location?

### Solution you would like.

Simple, add a spell to teleport someone else who is friendly

### Describe alternatives you have considered.

Not doing it.

**Comment by PGR-14** [comment]
What are the other ways?

**Comment by PGR-14** [comment]
Perhaps you could use the non-UI version for the NPCs? Make it two options (Like w/ thermogenesis) for Self & NPC, then put the regular spell as self, then the bare-bones _teleport version for the NPC

**Comment by Standing-Storm** [comment]
That would essentially require converting the entire power over to EoC as above, since the infrastructure to store multiple possible destinations would all need to be in place to properly store the location variables, and even in that case the location variables would not actually be associated with the destinations in the translocation menu. At that point, I might as well remove the translation functionality entirely and make it entirely EoC-based,

Which I might still do since it's not linked to furniture then and it's more like memorizing a location, but a halfway solution introduces new problems.
