### ISSUE TITLE
Make Fleet-Footed no longer a possible starting trait, introduce 2 new traits for increased walking and running speed.

### ISSUE THREAD

**Issue by SomeGuyIGues** [CleverRaven/Cataclysm-DDA#73617]
### Is your feature request related to a problem? Please describe.

The typical survivor has 100 speed, or moves exactly 1 tile per second. This currently means you are slightly slower than a zombie runner or dog, requiring you to either run or evade using houses, vehicles or other terrain to your advantage. With the current changes to pain, gaining 11 pain is sufficient enough to become slower than a feral human, which now requires you to run to outpace. However, with fleet-footed these problems are completely mitigated, and you can leisurely walk away from your problems without too much thought or strategy. This is to not mention how useful fleet-footed is for logistics or for the entire run of a standard game, making it is arguably one of the most powerful starting traits in the game.

Which is why I want fleet-footed removed as a possible starting trait, restricting it to only mutations. However, to supplement starting traits that affect speed, I propose two new starting traits. Trekker, and Sprinter.

### Solution you would like.

Trekker: "You know how to get the most out of your pacing. 5% faster walking speed on even ground." 

Sprinter: "Through a combination of good genetics, intense training and grit, you are able to outrun your competition. 15% faster running speed on even ground."

### Describe alternatives you have considered.

- Change the variables a bit, maybe sprinter increases running speed by 10% instead of 15%.
- Change the name of the traits. Trekker -> Powerwalker, speedwalker, longstrider, etc.
- Don't implement this feature request.
- Make a PR myself, if I'm willing to learn C++.

### Additional context

Quick is also extremely questionable. 10% faster... everything? Okay, seems legit.

I also understand that if these traits were to be added, they will stack with fleet-footed and road runner. I say, let the players be fast.

**Comment by fairyarmadillo** [comment]
These feel like they could be proficiencies, though they'd be ones every single player immediately rushed if they weren't difficult to acquire.

As proficiencies they could be tied to hobbies or professions for chargen, too.

**Comment by SomeGuyIGues** [comment]
I can see Trekker being a proficiency, but not Sprinter. I interpret Sprinter as due to the avatar having several biological and physiological such as leg length and muscular strength, is partially attributed to genetics. While everyone can increase their running speed with training, not everyone can become an Olympics sprinter.

**Comment by anoobindisguise** [comment]
Fleet Footed is a super duper strong trait, but it basically singlehandedly sets your Defense to Overpowered. So at least the game is acknowledging it's very good.

**Comment by IdleSol** [comment]
It's not a trait that's strong. It's the zombies are slow. However, the character is also slow.

1. The `speed` parameter, it's not actually speed. It's action points. The character's speed is action points divided by the move cost. Or speed = `speed` / move cost
The following examples are based on a flat surface, with a standard movement cost of 100 action points. And `speed` != speed.

- Standard character (`speed`=100). Speed = 100/100 = 1 tile per second. 
- A character with the fleet-footed trait: 100/85 = 1.176 tile per second. Actual speed increase: 17.5%, instead of the 15% from the description.
- A character with the quick trait (+10%): 110/100 = 1.1 tile per second (+10%).
- A character with the quick and fleet-footed trait: 110/85 = 1.29 tile per second (+29%).

Let's look at the opponents:
- zombie (`speed` = 70): 70/100 = 0.7 tile per second (-30%).
- zombie runner (`speed` = 105): 1.05 tile per second (+5%).
- zombie hunter (`speed` = 110): 1.1 tile per second (+10%).
- mi-go (`speed` = 120): 1.2 tile per second (+20%).
- tadpole constrictor (`speed` = 200): 2 tile per second (+100%).

Bottom line, a zombie runner is only fast compared to a normal zombie. If you compare it to a human, it walks with a normal walk.

2. I wanted to convert speed in game to speed in reality here. But that requires assumptions (tile size in meters?).

So I will focus on relative values. The Internet says that the average speed of a person walking at a normal walk is 1.4 meters per second. If he walks at a fast walk, it's 1.9 meters per second. An untrained person running 10 kilometers per hour or 2.8 meters per second. This is for average distances of about a kilometer.

Or relative to normal walk with some rounding: 1:1.35:1.9. Or +35% to speed for fast walk + 90% to speed for running.

In game, this means that the `move cost` for running is equal to 52...53 action points (currently 50, as long as you have stamina). This coincides. (100/1.9 = 52.6)
Fast walk speed: 74 action points. (100 / 1.35).

From there, the fleet-footed trait is just a habit of moving a little faster than a normal walk. So I don't agree that it shouldn't be available at the start.

**Comment by ADekema** [comment]
Getting walking speed behind a proficiency would be good. Running speed should probably be some combination of a proficiency and a trait. Think getting a 10% bonus from genetics and getting a possible 10% running speed bonus from a proficiency. You could also supstitue running proficiency with the athletics skill.

A walking or running proficiency should probably also slightly reduce stamina cost as a experienced ¨walker¨ or ¨Runner¨ would be moving more efficiently.
