### ISSUE TITLE
Segmentation fault when heating up an item using RV kitchen

### ISSUE THREAD

**Issue by ArneFjotland** [CleverRaven/Cataclysm-DDA#73657]
### Describe the bug

A segmentation fault occurs whenever I heat the item pickled fish in my RV kitchen unit.

### Attach save file

[Energy-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15282164/Energy-trimmed.tar.gz)

### Steps to reproduce

Get in the RV-unit, heat up the pickled fish supplied from the fridge using the oven.

### Expected behavior

self-explanatory.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.3447 (23H2)
- Game Version: aee9514 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/15282168/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/15282169/debug.log)

**Comment by EvaShark** [comment]
/confirm. same issue with normal appliance ovens in my main game and a test world
[DEBUG-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15316881/DEBUG-trimmed.tar.gz)

**Comment by EvaShark** [comment]
To be clear, I'm pretty sure this is affecting heating up items with any appliance or tool that has a menu, which just leaves passive heating with fire or the like, which isn't ideal.

**Comment by toweroglass** [comment]
now i'll never eat my fruit pancake (old) (frozen) right before they rot!

**Comment by ShnitzelX2** [comment]
For those concerned, this bug was introduced in #72514, I checked the releases and it started in 2024-05-09-1357.  #73740 was intended to fix seg faults and must not have caught all of them, since I ran into this bug in a recent build and others have too. Pinging @yuganxia 

In my case: when using an oven's hotplate to reheat an uncontained OR contained "dried rice (frozen)", the game crashes. Using an RV kitchen unit yields the same result. The new functionality introduced in #72514 works fine.

It doesn't seem like the PR took into account built-in hotplates in furniture/VPs. Using e.g. a pot as a batch cooking tool isn't accessible from (e)xamining e.g. an oven or hotplate; you have to specifically activate the cooking container. Also, using a pot at an oven or kitchen unit gives the message "You don't have proper heating source".
