### ISSUE TITLE
A "cuppa" problems

### ISSUE THREAD

**Issue by JeveGreen** [CleverRaven/Cataclysm-DDA#73682]
### Describe the bug

Horrible pun aside, this is a double entreé for two different bugs about two different teas.
1st, dandelion tea brewed from actual dandelions share the same nutritional value as when brewed from a tea bag, which is inconsistent with their actual values. I'm not sure if this is a bug or not, but I feel like it should be called out.
2nd, for some reason, chamomille tea isn't consumed upon consumption, nor does it seem to rehydrate you... This might be related to an old bug, where if you consumed the tea off of the floor, the same thing would happen, except now it happens when inside a container.

### Attach save file

- OS: Windows
    - OS Version: 10.0.19043.1466 (21H1)
- Game Version: c5f9a51 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    Bombastic Perks [bombastic_perks],
    Mythical Martial Arts [MMA],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

### Steps to reproduce

1. I craft my chamomille tea
2. I drink my tea
3. My tea is still there, and now I'm sleepy

### Expected behavior

For my tea not to be there once I'm 'eepy.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1466 (21H1)
- Game Version: c5f9a51 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    Bombastic Perks [bombastic_perks],
    Mythical Martial Arts [MMA],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by EternalLaughter** [comment]
I can confirm the Dandelion nutrition issue, they are the same whether  you make it from teabags, or real dandelions.
The chamomile tea is also confirmed, it does not get drunk\consumed, and gives no thirst quenching, atleast in the UI, as your thirst "meter" and fullness stays the same.

Interestingly, the tiredness effect of drinking it works, as i held down the button and promtly became deadly tired, heh.

**Comment by TealcOneill** [comment]
Unless I'm missing something none of the teas have alternate versions depending on whether it was made with fresh ingredients or bags. I don't know why dandelion would be special. It doesn't seem worth it to differentiate them with what will be in actuality minute differences.
As for the chamomile tea; I had no issues drinking spawned tea, tea made from spawned leaves, or spawned bags, or when drinking from any kind of container.

**Comment by JeveGreen** [comment]
> Unless I'm missing something none of the teas have alternate versions depending on whether it was made with fresh ingredients or bags. I don't know why dandelion would be special. It doesn't seem worth it to differentiate them with what will be in actuality minute differences.

The reason they're different recipes is because you need a certain level of survival skill to know how to brew tea from foraged dandelion roots, whereas tea bags are self-explanatory.

**Comment by TealcOneill** [comment]
Yes, I understand that. What I'm saying is that all of the tea recipes, both from bag and leaf, provide the same output with no nutritional difference.

**Comment by JeveGreen** [comment]
> Yes, I understand that. What I'm saying is that all of the tea recipes, both from bag and leaf, provide the same output with no nutritional difference.

There are some differences depending on whether you use bags or leaves, but they are miniscule. On the other hand, foraged dandelions are full of nutrients, whereas the tea bags are basically just flavored tea? I mean, making a batch of dandelion and burdock tea gives you lots of nutrients... I dunno what else to say.

**Comment by TealcOneill** [comment]
I get what you mean but most tea leaves have more nutrients than their dried counterparts. Dandelions in game are noted as having more nutrients because one person thought that was a cool/useful thing. If you just want to create a new recipe for fresh dandelion tea then I would say go for it. 
My main thought on differentiating them is that then you'll want to make the other fresh teas different and you'll have to come up with nutrient values for each of them before you can do so. Maybe it's worth it but I dunno. Follow your heart :ok_hand:

**Comment by TheMurderUnicorn** [comment]
Dandelion tea does not inherit information because of the NUTRIENT_OVERRIDE flag, which in my opinion it should not have and I'll change that, this will let it have variable calorie/vitamins based on whether you use fresh ingredients or a teabag.  

As for the chamomile, I could not replicate this, both debug chamomile and chamomile I crafted myself were consumed normally.  I didn't see anything in the file that would lead me to think this would happen, and the only recent change I saw was to its price, which would not affect this I assume.
