### ISSUE TITLE
Incorrect game loading

### ISSUE THREAD

**Issue by IdleSol** [CleverRaven/Cataclysm-DDA#73845]
### Describe the bug

I got several error messages during the loading process. But I assume that they are the result of an error during game loading, which has specific conditions of occurrence and does not cause an error report.

If you create a world with the Limb stuff mod and then delete it (world). Then loading a new world without the mod, leads to the following reports.

```
 DEBUG    : invalid body part id "arm_wing_bird_l"
 DEBUG    : invalid body part id "arm_wing_bird_r"

 FUNCTION : const T& generic_factory<T>::obj(const string_id<T>&) const [with T = body_part_type]
 FILE     : src/generic_factory.h
 LINE     : 482
 VERSION  : cdda-experimental-2024-05-16-0649 d435fb1
```
```

 DEBUG    : invalid sub body part id "arm_wing_bird_lower_r"
 DEBUG    : invalid sub body part id "arm_wing_bird_lower_l"

 FUNCTION : const T& generic_factory<T>::obj(const string_id<T>&) const [with T = sub_body_part_type]
 FILE     : src/generic_factory.h
 LINE     : 482
 VERSION  : cdda-experimental-2024-05-16-0649 d435fb1
```
These reports appear at the martial arts finalization stage or somewhere around there. (finalizing/recipe groups or martial arts).

I assume that the game is accessing data from the mod. But since it is disabled, it gets an error. The question is, why is it trying to access it?

### Attach save file

n/a

### Steps to reproduce

1. Create a world with the Limb stuff mod
2. Select to create a new character (new game / custom character)
3. Wait for the download to complete
4. Exit the character customization menu to the main menu
5. Delete the world
6. Create a new world, but without the mod
7. Select to create a new character
8. Get an error while loading

### Expected behavior

n/a

### Versions and configuration

cdda-windows-tiles-x64-2024-05-16-0649

**Comment by GuardianDll** [comment]
> If you create a world with the Limb stuff mod and then delete it

it is something you shouldn't do, it is expected that removing mods cause errors

**Comment by IdleSol** [comment]
But I don't delete the mod from the world, I delete the world and create a new one

**Comment by Qrox** [comment]
Sounds like some data are not properly unloaded before loading the new world.

**Comment by GuardianDll** [comment]
huh; okay, that's one is my fault, sorry for this

**Comment by AdamBrezik** [comment]
I got the same line in a different error message. Each time I kill a zombie child:
 DEBUG    : invalid monster type id "mon_zombie_bio_op"

 FUNCTION : const T& generic_factory<T>::obj(const string_id<T>&) const [with T = mtype]
 FILE     : src/generic_factory.h
 LINE     : 482
 VERSION  : cdda-experimental-2024-10-27-0438 d515611

Weird it'd go to bio operator, since it's a zombie child. I think I'm not sure about the limb mod - I don't think I had this in any world, but I had a world previously that had bionic slots mod and I also removed that one and now I'm playing on a new world without any mod removing as wrongly suggested beyond.

I got this error since a certain update a few weeks back. I even reverted the update and played on that one version that didn't produce this error for a while because it killed the fun for me so much, but since many interesting issues were fixed lately, I had to go for a newer version and now I'm receiving this all the time when killing zombie children ONLY.
