### ISSUE TITLE
Why can't I open the garage door?

### ISSUE THREAD

**Issue by IdleSol** [CleverRaven/Cataclysm-DDA#73879]
### Describe the bug

This one is very similar:
- #72965
- #67285

The difference is that it doesn't open.

I haven't found any patterns. Some doors open, others don't. In the main world, I have a neighborhood in which not a single garage door opens.

Is this a bug or am I not meeting some conditions? Like it was with wooden doors and electronic locks.

### Attach save file

[test-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15349273/test-trimmed.tar.gz)

### Steps to reproduce

Create a world and go open garage doors.

### Expected behavior

That I can open any garage door or get an explanation as to why I can't open it. More detailed than “nothing happened.”

### Screenshots

![pict](https://github.com/CleverRaven/Cataclysm-DDA/assets/155764584/ac6f0f97-920d-45d1-8a84-b33b9f626e2d)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043 (21H1)
- Game Version: cdda-experimental-2024-05-16-0649 d435fb1 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by PatrikLundell** [comment]
/Confirmed

It doesn't work with t_wall_wood beside the mechanism, but does work with t_concrete_wall. Debugging shows the mechanism is neither open nor closed when operated by a wooden wall. I've hacked the wall to concrete and gotten the mechanism to work, but it doesn't work when hacked back to a wooden wall.

Ah, the issue lies in gates.json. There "gate" types are defined, and they list the walls they work with. Wooden walls only work with barn doors.
This is a poor design in my view. These things ought to work with everything that have the "WALL" flag, as the current design means you're severely restricted in which kinds of materials your garages may be made out of (standard wall, concrete, brick, adobe brick, str concrete, s concrete, rock. Some of these also supports color versions, although I think some colors are missing (no P for concrete)).
