### ISSUE TITLE
add poisoned arrows

### ISSUE THREAD

**Issue by sotha1** [CleverRaven/Cataclysm-DDA#73935]
### Is your feature request related to a problem? Please describe.

no.

### Solution you would like.

create a way to add poison to arrows

### Additional context

already exists in the game flame arrows and monsters with poison, so, why not poisoned arrows?

**Comment by PGR-14** [comment]
As in magiclysm? I believe there is a poison arrow

**Comment by TheShadowFerret** [comment]
When the majority of fights last under a minute in ingame time + nearly all monsters fight to the death & so won't succumb later, I'm not sure of the player's utility of poison arrows(outside of magic/supertech)

**Comment by sotha1** [comment]
> As in magiclysm? I believe there is a poison arrow

yes

**Comment by sotha1** [comment]
> When the majority of fights last under a minute in ingame time + nearly all monsters fight to the death & so won't run away to succumb later, I'm not sure of the player's utility of poison arrows(outside of magic/supertech for the instant effects setting in)
> 
> ~Cyanide arrows when~

but, if the ingame battles takes a little while, why does fire arrows exist?

**Comment by PatrikLundell** [comment]
As mentioned, the most effective poison darts used by humans take longer to take effect than most game fights last. In addition to that, it's questionable if zombies are affected by poison. I guess it would be possible to use for hunting (like the real world version is) and for hit-and-run attacks on bandits.
However, it's fairly difficult to book a flight to South America for a frog hunt expedition.

**Comment by PGR-14** [comment]
> As mentioned, the most effective poison darts used by humans take longer to take effect than most game fights last. In addition to that, it's questionable if zombies are affected by poison. I guess it would be possible to use for hunting (like the real world version is) and for hit-and-run attacks on bandits. However, it's fairly difficult to book a flight to South America for a frog hunt expedition.

There are some mutant poison frogs (I think, but you could also add your own), so you could probably do something w/ them.

**Comment by PatrikLundell** [comment]
Well, cane toads are poisonous as well, but you won't be able to extract a good arrow poison from them. You really need the top of the line here.

**Comment by natsirt721** [comment]
This seems like something that would be extremely useful vs. NPCs or high power enemies, but I don't think the current "reality bubble" mechanics (as I understand them) support this. I'd be happy to be proven wrong on this.

On the realism side, as a New England native I don't think we have many sources of natural poisons (or a native culture of using them, anyway). So likely these would have to be either blob-induced poisons or pharma products. Not asserting that either are impossible or that I am an expert on northeast USA biotoxicology, just another barrier to entry. 

Frankly, I think it would be a good idea to add poison arrows (if the materials to create them are available), even if they are totally useless. IMO its ok to have things that are ineffective but practical to fabricate, because people (players) in stressful situations might choose to make these things if they are able without considering their effectiveness. And if they do fully consider their effectiveness, it will encourage novel playstyles based on the weapons so used. 

IMO this game in its descriptions provides an incredible amount of information that helps the player make reasonable choices, which in many circumstances might not be known by all survivors. I understand why this is (we're playing a game, after all) but I don't think it should be a reasonable critique for adding things that plausibly could be made bout would be relatively ineffective. Again, assuming that there is a reasonable source of poison that a survivor has access to - that I'm still not convinced of

**Comment by IdleSol** [comment]
We have a poison wasp. It decreases the player's parameters. Theoretically, you could use it to weaken opponents. Less speed, less damage, and so on.

But most enemies are either already dead or have a different biology. I don't think poison should have any effect on them. That leaves us with humans and animals that aren't dead or haven't started mutating yet.

Fighting against humans. If they stop throwing cans and do start shooting (or have they?). Trying to poison them is a pretty stupid idea. We have no way to covertly poison them before the fight.

Fighting against beasts. The main problem is to catch up and shoot the animal with a poisoned arrow, which will slow it down so it can be caught up. But if you have already caught up with it, then kill it. And what to do with the poisoned meat?

All in all, I don't see a situation in which it would be useful. But as already said, you don't have to add only useful things.

The game has it:
- wasp venom gland
- concentrated venom

I would suggest using glands. Something like squeeze poison from the gland onto the arrow. Get a poison arrow.

Concentrated poison, it's too complicated a recipe to make. To use it for poison arrows. I'm assuming poison arrows are an early game weapon.

**Comment by ADekema** [comment]
There has been a discussion before and I did a bit of research out of curriosity. Basic finding is that it is completely feasible for a survivor to make thier own. Hunter gatherers without access to metal in the jungle can make various plant and animal poisons for arrows. There are also plenty of poison sources in the area the game is set in and already in game. New england has plenty of poisonous plants and there are already many sources of poisons in game:

-Gaint spiders
-Wasps
-Bees
-Triffids
-Rattle snake
-Poisonous mutants
-Fungicide
-Herbicide
-Insecticide

I also have to make a point about on what poison should work in cataclysm dda. It should work against mutants just fine. The reason is that the player can get just as mutated as any other creature in game via mutagens or other means and unless they have specific poison resistance mutations they are just as suseptible to poisons as a normal human. There is also the fact that gaint insects are still suseptible to insecticide which seems a intentional design choice. So from what I can see mutants should be just as suseptible to poison as normal creatures unless they have mutated specific immunities agianst it. Otherwise the poison resistance mutations should be scraped and every post threshold player should be given immunity to all poisons.

I also think that poison should work for low level zombies. The logic is the same as for bleeding. Low level zombies bleed becease there biology is almost the same as their living couterparts. So they should bleed normally and poisons should still kill or incapacitate them. Intermediate evolution zombies bleed far less becease their biology and anatomy is differant. Not differant enough that it is completely differant so they still bleed somewhat but far less. By the same token they should be very resistant to poison and require much more to get the same effect. Highly evolved zombies are indeed so differant that they don´t bleed and most poisons don´t do anything to them. Baring maybe some highly or specifically engineert poisons from the triffids or Mi-go or specifically evolved poisons from mutants that hunt zombies that hoped in from a adjesent dimention or the nether.
