### ISSUE TITLE
Craftable refuse

### ISSUE THREAD

**Issue by fairyarmadillo** [CleverRaven/Cataclysm-DDA#73955]
### Is your feature request related to a problem? Please describe.

Item counts are a big problem for performance and storage, and there's so much junk in the game (plastic wrappers, cardboard boxes, fabric scraps, etc) that require an unfun amount of micro to clean up.

### Solution you would like.

What of there was a way to make plastic, aluminum, cardboard, and paper items into plastic refuse, aluminum refuse, cardboard refuse, and paper refuse, which used charges instead of count so they could be easily gotten rid of?

I think the easiest way to do this would be to add a sorting zone called "trash disposal" and another called "garbage". A new sort action could be added called "gather up garbage" which would pull all trash-flagged items from the "trash disposal" zone, convert them into the appropriate type of refuse according to their material and weight, and place them in the garbage zone.

Refuse items could perhaps be used in place of cardboard/paper/scrap in some recipes, but mostly they'd be easy to haul off and dump somewhere.

### Describe alternatives you have considered.

Conversely, sorting zones could be updated to use whitelisting and priority settings like pockets, which would also allow the player to quickly sort unwanted items into a single pile, but that sounds like more work. Either way, some kind of solution to this issue would be very welcome.

**Comment by Maddremor** [comment]
We are moving away from using charges overall, so converting items just for that reason isn't really going to happen. When it comes to disposal, you can just throw all the unwanted items on a brazier and set them on fire.

**Comment by fairyarmadillo** [comment]
That only works for burnable things.

**Comment by Hyperseeker** [comment]
The thing about burning something (or, for that matter, crushing it under the wheels of a heavy vehicle) is that it should leave refuse of its own. I've never seen a plastic bottle burn up so completely, it leaves nothing behind, outside of temperatures where barely anything else would survive, either.

My point being: trash (or at least what the player considers trash) should be removable. Either the game acquiesces to its current mechanic of "You can remove something from existence completely and entirely", or it should implement a way for the removed items to produce refuse when destroyed in any way. One of these ways is realistic, and the other is coherent with the current mechanics.

**Comment by IdleSol** [comment]
I burn or crush with special transport (4 wheels in one row).

But as I understand it, the main reason is not how to destroy. The problem is how to sort the many different items. The only thing they have in common is that the player considers them garbage.

1. Conditionally, we have the mechanics of favorite (`*`). Is it possible to make a trash mechanic (`t` or `g` or `#`) based on it? All items marked with this sign will be placed in a special zone (if they are containers or are in them, they will be automatically taken out of them with subsequent movement through the zones).

In general, analogous to the corresponding zones in RimWorld or Dwarf Fortress.

2. Or go further and extend the mechanics of suffixes and prefixes. Where any letter (or a symbol), can be assigned as a suffix/prefix. Then using custom zones, you can do sorting. For example, by symbols: !, @, #, $ and so on. As a result, you can get the sorting you want. (One symbols limit?). The main difference is that in this case, there will be no automatic release of containers.

3. In addition to the first points. You could add a new part of vehicles: Destroyer 3000. Everything that is placed in it is destroyed (immediately or not, doesn't matter). Vehicles, because you can bind a zone to it. So it could also be furniture: a trash can. If necessary, add energy consumption. And put it in a separate mod, if there are reasons why it can't be in the main game. It will make it easier to destroy things, but not by much. Since getting into a vehicle and driving over things is not a very difficult task.

**Comment by Maddremor** [comment]
Regardless, sneaking charges back is not going to be an option here. No matter how you deal with it, if you want to remove some items you have to designate them to be removed somehow, be it by putting them in a fire, making a custom sorting zone, or having some special keybind in the inventory screen.

**Comment by kevingranade** [comment]
The solution to your problems are a ui extension,  charges are a red herring.

**Comment by PatrikLundell** [comment]
Using the current system, I would create a zone out by my vehicles with a custom filter adding new items as they're identified as "trash". I'd then run over the zone with a vehicle from time to time to dispose of the stuff there.

**Comment by ADekema** [comment]
I think it would be good to add two refuse zones. One normal refuse zone where the player just dumps items. Another burnable refuse zone where the player will put items that are burnable. 

It should also be possible to have realistic ways of dealing with trash while getting rid of items for performence. One way would be allowing us o burry items. You simply dig a deep pit and dump items in it to it´s volume and then cover it. Another option could be a special trash pile furnature that can be made of any items as long as it has a certain volume. Simulating the player just dumping items somewhere and leaving it be. Bonus points if the trashpile furnature is burnable so you can get rid of it.
