### ISSUE TITLE
Reoccuring segfault when attempting to dissect an ant

### ISSUE THREAD

**Issue by Karol1223** [CleverRaven/Cataclysm-DDA#73985]
### Describe the bug

Try to dissect an ant and BOOM

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/68503002/c78fbc92-677d-4d39-8d17-90f0653d703d)

Unspeakable evil

### Attach save file

1. Savefile in question - [Legally Distinct Jurassic Park-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15388510/Legally.Distinct.Jurassic.Park-trimmed.tar.gz)
2. Crash log in question - [crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/15388497/crash.log)
3. Third party mod that might be required to open the save (probably not, but I warned you) - [CDDA-ProjectPangaea.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/15388492/CDDA-ProjectPangaea.zip)

### Steps to reproduce

1. Open the save, you're standing on an ant
2. ``B`` and choose dissect
3. Cry

### Expected behavior

Segfaults are famously bad for your health

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.3593 (23H2)
- Game Version: cdda-experimental-2024-05-19-0559 140db31 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Project Pangaea [ProjectPangaea],
    Stats Through Kills [stats_through_kills]
]

**Comment by ehughsbaird** [comment]
The same bug is shown in https://github.com/CleverRaven/Cataclysm-DDA/issues/73978

**Comment by IdleSol** [comment]
Confirmed.

The problem is this: an old corpse that is in the process of transforming into a meat cocoon. This transformation ends while the corpse is being dissected, which causes an error.

You can try smashing the corpse and then you can complete the dissection without error. Or wait about 30 minutes, during this time you will see the transformation of the corpse into a cocoon.

I don't know what is responsible for turning the body into a cocoon. EoC? But if it can be set somehow, I think there will be no problem with repeating this error in a new world without mods.

The solution is to stop the corresponding timer if butchering or dissection of the body is started.
