### ISSUE TITLE
document: incorrect title mapgen_id hierarchy in Terrain/Furniture Examination Actions 

### ISSUE THREAD

**Issue by cosing** [CleverRaven/Cataclysm-DDA#73995]
### Describe the bug

https://github.com/CleverRaven/Cataclysm-DDA/blob/970efaabd3ea0a9b18111238467a4d0f875e4989/doc/EXAMINE.md?plain=1#L95-L105

'### `mapgen_id`' hierarchy does not match, should be 4 '#' as with other optional

### Attach save file

unnecessary

### Steps to reproduce

Visit the URL:
<https://docs.cataclysmdda.org/TESTING_YOUR_CHANGES.html>

### Expected behavior

Should be changed to ####, I think here as not present as a type field, keeping the #### hierarchy will confuse users

### Versions and configuration

website

**Comment by cosing** [comment]
I'm not sure if I should just post an issue, but it doesn't look like it's possible to create new discussions, and my search of mapgen_id didn't reveal that anyone had asked a similar question.

This is just a very minor issue.

**Comment by NetSysFire** [comment]
We have discussions disabled because (1) github does not make it possible to see a feed of new discussion activity in the repo (2) more moderation effort needed where we already are quite short on people.

Please consider fixing this one yourself. Go into the file you linked, click edit, it will automagically fork and open an editor for you, it really is trivial.
