### ISSUE TITLE
Mortar recipe is too hard to get

### ISSUE THREAD

**Issue by dead-letter-office** [CleverRaven/Cataclysm-DDA#74015]
### Is your feature request related to a problem? Please describe.

Currently the only source for the Mortar recipe is in Concrete Constructions, a pretty uncommon book.

In reality, the recipe is usually printed on the back of the bags of cement needed to make it.

### Solution you would like.

The knowledge of how to make mortar from cement is simple, widespread, and usually found on bags of cement. The recipe should probably be autolearn.

### Describe alternatives you have considered.

Make it possible for containers to have recipes printed on them.

**Comment by NetSysFire** [comment]
I looked and unfortunately it does not look like you can have containers, the sacks containing the cement, be also a book. Making it autolearn should be fine for now.

**Comment by IdleSol** [comment]
Or add a new item to the bags of cement. This item would be a book containing a recipe. Let's call it a label.

```
    "id": "cement_bag",
    "type": "item_group",
    "container-item": "bag_durasack",
    "items": [ { "item": "material_cement", "count": 2800 }, { "item": "label", "count": 1 }]
```
+
```
    "id": "label",
    "type": "BOOK",
...
```

**Comment by IdleSol** [comment]
And this way doesn't work. Because there's either cement or a label in the bag.

**Comment by IdleSol** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/de4ec39f57b1be19b9975e42971671b609c37bf9/data/json/itemgroups/supplies.json#L103-L108
Change to
```
  {
    "id": "cement_bag",
    "type": "item_group",
    "subtype": "collection",
    "container-item": "bag_durasack",
    "items": [
      { "item": "material_cement", "count": 2800 },
      { "item": "cement_bag_label", "count": 1 }
    ]
  },
```
https://github.com/CleverRaven/Cataclysm-DDA/blob/9e4e759b5d1f28c14e99ae8fce849007d21d66f6/data/json/recipes/other/parts_construction.json#L658-L671
Change to
```
  {
    "type": "recipe",
    "activity_level": "NO_EXERCISE",
    "result": "mortar_build",
    "category": "CC_OTHER",
    "subcategory": "CSC_OTHER_OTHER",
    "skill_used": "fabrication",
    "difficulty": 2,
    "time": "10 m",
    "autolearn": false,
    "book_learn": [ [ "concrete_book", 2 ], [ "cement_bag_label", 1 ] ],
    "tools": [ [ [ "concrete_mix_tool", 50 ] ] ],
    "components": [ [ [ "material_cement", 50 ] ], [ [ "material_sand", 150 ] ] ]
  },
```
diff: `"book_learn": [ [ "concrete_book", 2 ], [ "cement_bag_label", 1 ] ],`

https://github.com/CleverRaven/Cataclysm-DDA/blob/de4ec39f57b1be19b9975e42971671b609c37bf9/data/json/recipes/recipe_others.json#L2-L17
Change to
```
  {
    "type": "recipe",
    "activity_level": "NO_EXERCISE",
    "result": "concrete",
    "category": "CC_OTHER",
    "subcategory": "CSC_OTHER_OTHER",
    "skill_used": "fabrication",
    "difficulty": 4,
    "time": "30 s",
    "batch_time_factors": [ 80, 2 ],
    "autolearn": false,
    "book_learn": [ [ "concrete_book", 4 ], [ "cement_bag_label", 1 ] ],
    "qualities": [ { "id": "CONTAIN", "level": 1 } ],
    "result_mult": 2,
    "using": [ [ "concrete_materials_dry", 1 ] ]
  },
```
diff: `"book_learn": [ [ "concrete_book", 4 ], [ "cement_bag_label", 1 ] ],`

And add a new file, with the expectation of expanding the range of labels: 
/data/json/items/book/container_label.json
```
[
  {
    "id": "cement_bag_label",
    "type": "BOOK",
    "category": "manuals",
    "name": { "str": "Cement bag label", "str_pl": "Cement bag labels" },
    "description": "The label provides instructions for making mortar and dry concrete mix",
    "weight": "10 g",
    "volume": "10 ml",
    "price": "0 USD",
    "price_postapoc": "1 cent",
    "material": [ "plastic" ],
    "symbol": "?",
    "looks_like": "recipe_lab_elec",
    "color": "blue",
    "skill": "fabrication",
    "required_level": 1,
    "max_level": 1,
    "intelligence": 6,
    "time": "1 m"
  }
]
```

All that's left is to find someone who will correct my mistakes and create the appropriate PR.

Tested on game version 2024-05-22-0335. Took apart pallets of sacks.
Problems:
- Too many labels. There are 64 pieces from one pallet (64 bags with 1 label each). Potentially cluttering up player storage / very common recipe. But it won't help you develop production skills. Probably nothing wrong with it?
- I don't know what needs to be changed to allow this label to be disassembled into 1 piece of plastic, instead of 0 sheets of paper.

**Comment by natsirt721** [comment]
I think autolearn is appropriate - given the breadth of other autolearn recipes (for better or for worse) this one doesn't strain credulity.
