### ISSUE TITLE
Weather should affect mood directly

### ISSUE THREAD

**Issue by Nandorianen** [CleverRaven/Cataclysm-DDA#7410]
Little things really make the difference. If you can enjoy a good candy, why aren't you enjoying such fundamental things like a nice sunny day? Good weather should elevate your mood up to a point, the longer you are outside. Bad weather should make you a little more miserable. Obviously everything is good in moderation: in a really hot summer shade is more welcome than direct sun, while sunny morning in the winter is a nice surprise. Traits should affect this. Obviously, light-dependent or light sensitive. Outdoorsman should work like optimistic in regards to weather mood (maybe with bigger numbers). The opposite to outdoorsman could also be made - to represent urban softies who can't imagine a day without all modern comforts.
##

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
