### ISSUE TITLE
Larger crafting radius

### ISSUE THREAD

**Issue by PGR-14** [CleverRaven/Cataclysm-DDA#74118]
### Is your feature request related to a problem? Please describe.

It's just really annoying that I can't craft w/ something that's not even 15 tiles away (Especially in places like basecamps).

### Solution you would like.

A: Increase the crafting radius
B: When in a faction camp, allow all items in the camp to be used

**Comment by ZhilkinSerg** [comment]
`PICKUP_RANGE` is a compile time constant, so you can easily increase it on your side, compile and play the game with a different value:

https://github.com/CleverRaven/Cataclysm-DDA/blob/cd60b6bee00738e13e3957f56995428126a8c71e/src/game_constants.h#L66-L70

**Comment by PGR-14** [comment]
Ok, but also, why is it so small? Just want to know.

**Comment by kevingranade** [comment]
In reality you tend to arrange your work area to minimize travel time,  but instead of a complex system to track time spent based on distribution of tools and components, we just restrict the work area to a sensible size.

There are also impacts on hand performance. Iterating across a very large area with many items in different locations can be very costly.
