### ISSUE TITLE
Jumper cable and funnel have plus 1 to melee?

### ISSUE THREAD

**Issue by Maleclypse** [CleverRaven/Cataclysm-DDA#74131]
### Describe the bug

Jumper cable and funnel have plus 1 to melee?

### Attach save file

[Paden-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15450227/Paden-trimmed.tar.gz)

### Steps to reproduce

Spawn in jumper cable and funnel, note they have plus 1 to hit.

### Expected behavior

Negatives to hit

### Screenshots

![Jumper cable and funnel plus 1 to hit](https://github.com/CleverRaven/Cataclysm-DDA/assets/54345792/2b807942-b473-4698-8995-fca09f61624c)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.3593 (23H2)
- Game Version: 0.G-9851-g9e58e8a2e4 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Work in Progress Limb Stuff [limb_wip]
]

**Comment by Karol1223** [comment]
I am honestly more impressed with 4 bash on a 150g piece of plastic when it comes to the funnel tbh

**Comment by RenechCDDA** [comment]
Jumper cable to-hit calculation is:

Base: -2
Grip: -3 ( -1 due to bad grip)
Length: -1 (+2 due to 3-foot length, used as a flail)
Striking surface: -2 ( -1 due to line hit, this one's hard to judge for me. Presumably you'd want to only hit with the actual jumper)
Balance: -1 ( +1 due to good swinging. It's weighted at the end, which is useful for swinging)
