### ISSUE TITLE
New night vision goggle attachments have multiple issues

### ISSUE THREAD

**Issue by rselias** [CleverRaven/Cataclysm-DDA#74230]
### Describe the bug

When turned on, enhanced night vision goggles draw 250 watts, and will drain their batteries incredibly quickly.

For comparison, night vision goggles draw 140 mW, the panoramic night vision goggles draw 180 mW, and the IR goggles draw 1 W. The Hub 01 recon headgear draws 375 mW in night vision mode and 1 W in IR mode. The ENVG's 250 W power draw is a massive outlier.

The ENVGs are based on the AN/PSQ-42, which uses 4x 1.5V batteries and advertises a 7-8 hour battery life. By my napkin math, if those had a 250 W draw, they'd drain an entire battery pack in under five minutes. CDDA batteries are different, but this is still obviously a mistake. I suspect it's a typo, and the power drain was supposed to be 250 mW. (That is probably unrealistically low, though, as it's both NV and IR. I'd expect it to have a higher drain than IR goggles, just not 250 times higher.)

### Attach save file

N/A

### Steps to reproduce

Spawn in enhanced night vision goggles and a battery. Turn them on, wait for one minute, and watch them drain 10-12 power.

### Expected behavior

I would expect them to drain at most 1-2 power in one minute.

### Versions and configuration

-OS: Pop!_OS 22.04
-Game version: cdda-experimental-2024-05-31-1919 cef5d70
-Graphics version: Tiles
-Ingame language: English
-Mods loaded: dda, no_npc_food, personal_portal_storms, no_fungal_growth

**Comment by rselias** [comment]
Also, there's a bunch of other issues with the new NVGs.

The normal night vision goggles are described as being older generation double-tube goggles, but a comment in the code indicates they're based on the AN/PVS-7, which is single-tube. Not sure which is accurate.

Normal night vision goggles have the nvg_good effect, giving them +12 vision, while the panoramic and enhanced night vision goggles only have nvg_normal with +9 vision. This makes no sense -- shouldn't it be the other way around? I can see an argument for the panoramic goggles having a better vision bonus than the enhanced goggles, given their real-life counterparts have a much wider field of view. But there's no way the normal NVGs should be better than either. Right now the GPNVGs are objectively worse than the normal ones in every way. The ENVGs are too, except they have IR vision to redeem them.

...They have IR vision, right?

No, they don't. The flag isn't working. Not sure why. The normal infrared goggles with the same flag work fine. The night vision enchantment doesn't seem to conflict with the IR_EFFECT flag, given you can wear active NVGs and IR goggles at the same time, and they both work. Which is another bug - activating goggles attached to a helmet doesn't check to see if you already have a rigid item in the outer eyes layer, so you end up being able to have multiple rigid items equipped occupying the same space.

Paging @b0bhat

**Comment by b0bhat** [comment]
Thanks for bringing these issues up @rselias, I admit I should've checked my values before committing. I'll create a PR with the fixes.

For the ENVG power draw, that is indeed a typo, should be mW and not W.
The NVG's description should be changed to single tube.
NVG should have nvg_normal, GPNVG should have nvg_good. 

The ENVG should have nvg_normal with IR vision but I think due to no inherit flag on the helmet slot the flag does not work (since the nvg is an item in the pocket rather than being worn). The inherit flag causes some other problems with persistent effects lasting after the battery runs out, so I think a fix could perhaps be just increasing the range of its nv effect above the GPNVG instead of true IR, or removing the item for now. 

I'm not sure how to fix that last issue. I think rigid should block other rigid items but maybe the check only checks worn items which the nvgs aren't.
