### ISSUE TITLE
Extradimensional containers count against vehicle tiles volume limit

### ISSUE THREAD

**Issue by Vsevolod-Shustov** [CleverRaven/Cataclysm-DDA#74330]
### Describe the bug

title

### Attach save file

[City View-trimmed.tar.gz](https://github.com/user-attachments/files/15589377/City.View-trimmed.tar.gz)

### Steps to reproduce

1. Attempt to fit into bucket seat (two tiles to the east) and fail
2. Drop oversized wooden box (assigned to V key) from lifting field, attempt to fit into bucket seat and succeed

### Expected behavior

Vehicles are not made of 5-point anchors

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3448 (22H2)
- Game Version: b8f906a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Mind Over Matter [mindovermatter],
    Extra Mutated Scenarios [extra_mut_scens],
    Mythical Martial Arts [MMA],
    Bionic Slots [cbm_slots],
    vs_personal_mod [vs_personal_mod]
]

**Comment by toweroglass** [comment]
obviously standing-storm can correct me if i'm wrong, but the lifiting field isn't extradimensional. it's being held aloft by psionic powers.

**Comment by Standing-Storm** [comment]
Yeah--in this specific case this makes sense. The box is just floating next to you, it would still take up space if you're trying to fit into a car seat.

**Comment by Vsevolod-Shustov** [comment]
So, more micromanagement for the micromanagement god? Just to _checks notes_ get in and out of the car?

**Comment by natsirt721** [comment]
See #74348 and #74263

**Comment by emixa-d** [comment]
>Yeah--in this specific case this makes sense. The box is just floating next to you, it would still take up space if you're trying to fit into a car seat.

What if the box float outside the car, e.g. above the roof or something? (Depending on the vehicle configuration and whether doors are open or close, this assumes the lifting field is treated as a "can be done through walls" thing.).

Some limitations apply -- if there is a roof, you shouldn't be able to reach into your loot fridge. Unless perhaps you use TK to move the items, similar to how force push/pull works? Or TP to teleport the item into your hand/the fridge, I don't know if that's something psions are supposed to be able to do. Or (assuming open doors) distort space to make the distance between your hand and the fridge shorter, similar to stutterstep. Then inventory management can potentially cause nether attunement and has a calorie cost.

>So, more micromanagement for the micromanagement god? Just to checks notes get in and out of the car?

It's not just a micromanagement thing. Because of this issue, you can't bring your household fridge (*) filled with loot with you if the vehicle has no storage space with room for 601.475L  (think: drop fridge in storage space, then move to seat). (At least in the roofed case.)

(*) replace by whatever is the latest meta

**Comment by kevingranade** [comment]
Mod author clarified that it is correct behavior as the box in question shares the player tile.

**Comment by emixa-d** [comment]
> Mod author clarified that it is correct behavior as the box in question shares the player tile.

They haven't had a chance to consider my proposal yet (or possibly they had but just ignored it, dunno), where I propose something that's in line with both Standing-Storm's remark and the behaviour that the OP appears to desire. I can imagine Standing-Storm deciding that my proposal isn't something psions can do (or something that psions could do but isn't worth implementing in-game), but they haven't done so yet.

**Comment by Standing-Storm** [comment]
> What if the box float outside the car, e.g. above the roof or something? (Depending on the vehicle configuration and whether doors are open or close, this assumes the lifting field is treated as a "can be done through walls" thing.).
> 
> Some limitations apply -- if there is a roof, you shouldn't be able to reach into your loot fridge. Unless perhaps you use TK to move the items, similar to how force push/pull works? Or TP to teleport the item into your hand/the fridge, I don't know if that's something psions are supposed to be able to do. Or (assuming open doors) distort space to make the distance between your hand and the fridge shorter, similar to stutterstep. Then inventory management can potentially cause nether attunement and has a calorie cost.

To implement this, I think that would require that #66452 be fixed and the lifting field become a concentration power (my intention ever since I implemented it), and then driving would take up a concentration slot (or maybe two). So it's not outside the capabilities of telekinesis, but it's outside the current ability of the game to model it.
