### ISSUE TITLE
Introduce extension of u_has_item that allows items in the vicinity

### ISSUE THREAD

**Issue by PatrikLundell** [CleverRaven/Cataclysm-DDA#74451]
### Is your feature request related to a problem? Please describe.

While doing testing I encountered the occupied lumbermill and its missions. The manager asked for drive belts, and I debug spawned them, but they weren't recognized as present until I cleared out the inventory and picked them up.
This got bad when the mission was for blankets, as I can't pick up that many blankets (but quilts worked, as they're not monstrously large).

### Solution you would like.

The introduction of a new extended directive that looks for items in the vicinity not owned by others, so the items can be e.g. in a vehicle trunk, or hauled. Obviously, missions ought to be updated to use the new directive when reasonable, especially when the bulk of items requested is large.

### Describe alternatives you have considered.

A work around would be to use the structure used by the Tacoma farm. The disadvantage with that is that it doesn't seem to support alternative sets of items (blankets, quilts, fur blankets,... for the lumbermill task).

Another alternative would be to extend the syntax used by Tacoma to support alternative sets of items and shift missions to use that syntax.

**Comment by GuardianDll** [comment]
> missions ought to be updated to use the new directive
It would also require to make an effect that would be able to remove said items from the player or the ground, or transfer their ownership at least

**Comment by zachary-kaelan** [comment]
Isn't this what `u_map_run_item_eocs` [does](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/EFFECT_ON_CONDITION.md#u_map_run_item_eocsnpc_map_run_item_eocs)? Particularly with `manual` or `manual_multi`.

**Comment by GuardianDll** [comment]
this one allow to search items on the ground, but it doesn't allow to specify how much of said items is needed to be, doesn't allow to deliver items to NPC (because when this effect is run, we swap our beta talker from NPC we talk to items we search), and it doesn't allow to search items both in character inventory and on the ground

In theory it can be improved to the level where it could solve this, i honestly think only issue 3 might need to be solved, other stuff might be resolved from the json side (like we can just delete said items instead of giving them to NPC?)

Oh, and also MGOAL_CONDITION is a condition, when u_map_run_item_eocs is effect, also need to think the ways to connect two, but at that point one could just move the entire winning condition to EoC and just use `finish_mission`

**Comment by GuardianDll** [comment]
We got u_has_items_sum and u_consume_item_sum since this issue was made, and i even have a code that improves it to allow to use ranges, in <https://github.com/CleverRaven/Cataclysm-DDA/compare/master...GuardianDll:Cataclysm-DDA:better_f_consume_item>
However, while consuming charges around the character is just a matter of using use_charges() functions, items do not really have such ability, and i am not aware of the way how to make it - my attempt in aforementioned branch failed completely

**Comment by PatrikLundell** [comment]
I would guess the logic behind the operations to find and consume items for crafting ought to be usable, either through the operations themselves or through reuse of their logic.
For crafting it is a two step process: first items are tallied within the reachable range, then a selection of components takes place (via the UI or automatically via logic, in particular when there is only a single possible match), then there is a second pass (after the go ahead has been given to actually perform the task), during which essentially the same logic is applied in a consumption phase where items are removed as they're encountered until the selected count has been removed. Actually this part is a two step process for some categories of items, as desirable targets are removed first, and undesirable ones only in a further pass making up for the lacking number (undesirable items are currently essentially containers with liquids and poisonous food).

**Comment by GuardianDll** [comment]
That what Snup (aka mqrause on github) told me and even showed me the code
But as you can see in my branch, it didn't work

**Comment by PatrikLundell** [comment]
I'm trying to look at the code, but I'd like to know where it fails, and, ideally, if you have a suitable save available.

The "where does it fail" question is basically if everything fails, or if it's only the item removal (which it sounds like from your description). If it's the latter case, I would assume the condition.cpp part works.

**Comment by GuardianDll** [comment]
You are right, when i say "i failed" i mean "specifically part of code that supposed item being removed from the map, afar from player, doesn't work"

I don't have the save file, but you can test it by running next eoc (that i have in this branch because i used it for tests):
```json
  {
    "type": "effect_on_condition",
    "id": "AAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "effect": [
      { "u_consume_item_sum": [ { "item": "blanket", "amount": 2 }, { "item": "fur_blanket", "amount": 2 } ] },
      { "u_message": "DONE" }
    ]
  },
  ```
then spawning blankets around, and activating said eoc via debug - game - activate eoc
You will see that the game would not remove any blankets around you, despite code being compilable

**Comment by PatrikLundell** [comment]
I've gotten a bit, but not sure if it's all the way.
- added add_msg in parallel with add_msg_debug to get the output as normal game feedback, for easier examination.
- assigned the result from the consume_items calls to lists, and then printed the size of the list in the add_msg output.
- You seem to be very close. Changing "1" to "count_desired" in the calls to consume_items seems to do the trick.

I haven't tested extensively, and you'd probably need some test case with a larger number of items. Also, I've only tested with a single pile.

**Comment by GuardianDll** [comment]
hmm? for <https://github.com/CleverRaven/Cataclysm-DDA/compare/master...GuardianDll:Cataclysm-DDA:better_f_consume_item#diff-dbaa22c0fa33ea5e52a18f1ce46db9dcd13311330a9e5130fff6bdf18d67629bR3520> it was intended to use count_desired, i omitted it for test purposes, but for <https://github.com/CleverRaven/Cataclysm-DDA/compare/master...GuardianDll:Cataclysm-DDA:better_f_consume_item#diff-dbaa22c0fa33ea5e52a18f1ce46db9dcd13311330a9e5130fff6bdf18d67629bR3544> it is absolutely necessary to remove items one by one, since user has more of this item than quest require, and we need to not overshoot amount to subtract
tho there is surely a more elegant way to do it than remove items one by one

**Comment by PatrikLundell** [comment]
I don't really see why you'd want to remove items one by one. It should be sufficient to reduce the desired number with what you just managed to remove.
If, for some reason, you actually need to remove items one by one, you'd need to add a loop to do it.

Anyway, yes, it does indeed seem like you were a hair's width from getting there (I may have missed something, of course).

**Comment by Procyonae** [comment]
I'm tired and only skim read this but MGOAL_FIND_ITEM already does this so it's C++ logic is probably useful
