### ISSUE TITLE
cooking oil should spawn in houses

### ISSUE THREAD

**Issue by martinrhan** [CleverRaven/Cataclysm-DDA#74478]
### Is your feature request related to a problem? Please describe.

I am looking for cooking oil to lubricate my gun, but they don't spawn in ordinary houses, this is not realistic.

### Solution you would like.

add cooking oil spawn in houses.

**Comment by EternalLaughter** [comment]
Cooking oil (animal\vegetable) is something that spawns just fine for me in houses, RNG depending.
What version of the game are you running?

**Comment by martinrhan** [comment]
> Cooking oil (animal\vegetable) is something that spawns just fine for me in houses, RNG depending. What version of the game are you running?

I am playing newest experimental. I searched more than 10 houses and never see cooking oil.

**Comment by EternalLaughter** [comment]
> > Cooking oil (animal\vegetable) is something that spawns just fine for me in houses, RNG depending. What version of the game are you running?
> 
> I am playing newest experimental. I searched more than 10 houses and never see cooking oil.

Unless there's a bug in newest experimental that stops this from spawning, this sounds more like RNG to me, and that you'd like the % chance for it to be increased because it should be super common?

https://cdda-guide.nornagon.net/item/cooking_oil
https://cdda-guide.nornagon.net/item/cooking_oil2

You can see the loot locations at the bottom, which lists all the places it can spawn and the % chance.
