### ISSUE TITLE
Seamless transition from map to look around & from look around to map

### ISSUE THREAD

**Issue by Brambor** [CleverRaven/Cataclysm-DDA#74470]
### Is your feature request related to a problem? Please describe.

I want to see something in memory beige. The something is quite far. I find it instantly on the map. Then I awkwardly move the view to it in the Look around.

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/13402666/ff8c40f3-55e2-413f-aee8-7cf46d162881)

### Solution you would like.

Keybinding on the map that transitions the view from the map to Look around on selected tile.

Keybinding in look around to transition to map in selected overmap tile.

Note: map > look around. The overmap tile is 24x24, it should transition to the look around at one of the centre tiles. I prefer the 12th by 12th tile (top-left centre). Making it always select the same offset within the tile allows for some more utility.

An example is figuring out OMT borders. I know I have to press `7` 11 times to be in the upper left corner of OMT. I would use this for camp expansions that need to be aligned to OMT. Makes it easier for me to know where I need to set the zone to clear forest and such.

After that, I need to make zones. Maybe just making zones snapping to OMT would be better for my use case.

![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/13402666/75871b1d-926a-42e4-8a88-88d59eb2b38b)

**Comment by Procyonae** [comment]
> An example is figuring out OMT borders

You can see OMT borders by doing (bind debug menu) -> debug menu -> `m`ap -> `M`ap editor -> ( Move your cursor to the OMT you care about ) -> edit `o`vermap
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/45432782/8ed2666c-1340-402d-b191-acad68c0e844)

**Comment by dominic-dimico** [comment]
This would be nice.  Although, your character's memory of places they have visited is already so good and so accessible, that this almost feels like they are astral projecting to the location and exploring it in real-time (as you, the player, scroll around), instead of remembering it all instantaneously as the game's mechanics would suggest.

Realistically, if I were trying to get a visual memory of a faraway location, I'd at least have to give up some attention to my immediate surroundings and take a couple of seconds to conjure the memory.  It's not something that could easily be done in the heat of battle.

**Comment by Brambor** [comment]
This is a game. We don't want to bother the player with these small nuances and just assume they could get the information (about far away places) eventually when they have free time or they could have learned the information if free time in advance. As a QoL we don't withhold the information until they have free time or if they forgot to prepare before driving etc.

**Comment by CoroNaut** [comment]
May I suggest that if the player has the "Topographagnosia" trait, that this feature be disabled for them? The rationale being that they generally couldn't remember where locations were because of their focal brain damage as the trait description. They wouldn't be able to remember where things were on a map. 

As an alternative, perhaps if they have this trait, upon 'looking around' from map view, their camera could be randomly placed within 5-10 OM tiles of where they wanted to look. Thus having them scroll at least a little bit to fully 'remember' the area.

I'm also thinking that players with this trait could be stopped from going too far away from their character when navigating in map memory, but that is out of the scope of this issue.

**Comment by Brambor** [comment]
> May I suggest that if the player has the "Topographagnosia" trait, that this feature be disabled for them? The rationale being that they generally couldn't remember where locations were because of their focal brain damage as the trait description. They wouldn't be able to remember where things were on a map.

I don't want to do that. But I am not stopping you, if you want to do it.

There is some super special case when you aren't supposed to be able to open the map with a message "You are lost" or something. I hope I didn't break that. I suggest looking into that in regard to your idea.
