### ISSUE TITLE
Allow Fruit Sugar Refining using Potassium Hydroxide

### ISSUE THREAD

**Issue by Kantonine** [CleverRaven/Cataclysm-DDA#74547]
### Is your feature request related to a problem? Please describe.

While looking at the recipe for refining sugar from various fruits, i noticed that the recipe uses sodium hydroxide lye powder only, with no option to use potassium hydroxide powder instead. This makes the acquiring of sugar from fruit difficult.

### Solution you would like.

Allow Potassium Hydroxide to be used in place of Lye powder, possibly needing more to achieve the same results

**Comment by Maleclypse** [comment]
If it's a real method used to produce sugar from fruits then it can absolutely go in game.  Just do your best to mirror actual production values, byproducts and equipment needs.

**Comment by AudBobb** [comment]
I was doing a bit of research into ways to extract sugar while trying to mass produce it in game for alcohol production. After doing like an hour of searching various terms related to extracting sugar from fruit, and reading, everything led back to this one paper, where the use of hydroxide was a step to adjust the Ph of the juice. 

https://patents.google.com/patent/US6387186B1/en

This patent references a 'conventional' method, 'A', and n new method proposed by the patent, 'B'

A) The conventional beet sugar manufacturing process involves cleaning the beets, slicing them into cossettes, extracting juice from the cossettes by diffusion, purifying the juice by liming and carbonation, concentrating the juice by multiple effect evaporation, multi-stage boiling of concentrated juice in pans, separation, washing, and drying the sugar.

>Liming and carbonation is a process used to purify cane juice and produce granulated sugar. In this process, lime or milk of lime is added to the juice and carbonated at a specific temperature.

The relevant part of this process being 'liming and carbonation', where lime (calcium carbonate mineral, not the fruit) is added to carbonate and acidify the mixture.

B) macerating beets or pieces thereof; mechanically separating juice from the macerated beets; and membrane filtering the separated juice, producing a retentate and a permeate. The present invention makes use of mechanical means, such as vacuum filtration, for separating juice from macerated beets, as opposed to the simple diffusion process that is used in prior beet processing technology to obtain juice from cossettes.

I'll admit, this is where things start to go a little over my head and I really had to read this closely, but it seems like several processes had been proposed to remove the need for the liming process due to the extra manufacturing steps for lime, and waste products it produced, but all of them involved very fine filtration methods. Relevant paragraph below

>Conventional dead-end filtration is incapable of separating sucrose from macromolecular impurities in beet juice. Several methods of using microfiltration and ultrafiltration for purification of juice with reduced lime use have been reported, but these methods generally involve inserting microfiltration or ultrafiltration membranes into the conventional beet process at one or more points.

And that's where the proposal for using hydroxides comes in, specifically sodium hydroxide in this paper. It's a proposed alternative to calcium carbonate for pH neutralization of the juice.

>The juice is then neutralized by the addition of aqueous sodium hydroxide 42, preferably to a pH of at least 7, in neutralization tank 43. This pH adjustment helps prevent the inversion of sugars which takes place at elevated temperatures. Other chemicals may be also be used for pH adjustment, e.g. liquid potassium hydroxide or granular sodium carbonate.

So any appropriate chemical could be used for pH adjustment it sounds like

I'm not really sure where I'm going with all of this, but I couldn't find any documentation on what this recipe in the game was modelled on, so figured I'd document it here I guess. 

In reality, this recipe seems like it really needs some more tools involved based on the steps in this process, particularly a high quality filter, a screw press, a cutting implement or food processor. It also seems like any process that could be done by hand in the game would not be terribly efficient.
