### ISSUE TITLE
After merging 74348, XXXL Start cannot use vehicles at all

### ISSUE THREAD

**Issue by molkemon** [CleverRaven/Cataclysm-DDA#74552]
### Describe the bug

Since the change introduced in https://github.com/CleverRaven/Cataclysm-DDA/pull/74348, starting with the XXXL trait makes you unable to enter cars, even naked. Before the change, it would be cramped but possible, sometimes even with backpack on (depended on the seat and how full the backpack was). 

Char is 170cm, I'm not quite sure on the weight, it is above 150kg though. I have about 495kcal stored currently, according to formula introduced with the recent BMI changes (https://github.com/CleverRaven/Cataclysm-DDA/pull/60597), this means 64kg of pure fat, I'm not clear on how much everyting else (skeltal etc) weights though. I'm pretty sure I'm not above 200kg though, and 200kg people can definitly use cars.

Tagging @feinorgh since it was his PR.

### Attach save file

[Mason County-trimmed.tar.gz](https://github.com/user-attachments/files/15846688/Mason.County-trimmed.tar.gz)

### Steps to reproduce

Make XXXL char (I made mine 170cm), try to enter car. 

### Expected behavior

Fat people can drive cars.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4412 (22H2)
- Game Version: cdda-experimental-2024-06-15-0832 175eae4 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex],
    Disable NPC Needs [no_npc_food]
]

**Comment by molkemon** [comment]
Yes, but don't forget that those 200kg on a fat person is not only fat. As I said, in my save, my "fat" is only 64kg, the rest of it is normal body stuff. Now I still don't know how much my character actually weights, I just know it is above 150kg, but I don't expect by much. Still, it's "only" 64kg fat, not 200.

**Comment by feinorgh** [comment]
That's true, but very roughly speaking any human body will have about the same density as water. At the very extremes that does not hold but for most cases it won't make much difference.

I've looked up dimensions of car seats in general, and a rough calculation seems to indicate that any car seat by itself (say around  50×50×75 cm) can fit anywhere from 150-190 L, not counting leg room and head room. Some of this space will be taken up by the steering wheel for the driver.

I think a relatively simple solution would be to increase the volumes of car seats in the JSON files, and set the value so that it feels realistic and practical.

For realism, it should not be possible to enter a seat with a military rucksack on your back, or if the character is huge or greatly obese. But most fat characters, and most tall characters, should be able fit into a car seat.

**Comment by PatrikLundell** [comment]
"Anyone could fit into a trailer truck..." but apparently not a prison transport: #74559.

The car seat volume discussion is garbage: it's a huge difference between storing things onto a seat and placing ones butt onto one. In the former case you have to place all the stuff into a fairly shallow depression, while in the latter you place the person's butt onto the seat (and fat people may indeed have trouble with spill over if there isn't enough room to the sides), the legs in front of it (where you could otherwise store more stuff than on the seat itself), and most of the driver above the butt, and thus above the seat, not in it.
A very tall person may indeed get issues with the lack of headroom (and leg room, if the seat cannot be moved back far enough).
Thus, a car seat's storage capacity is largely decoupled from its driver size capacity. The latter is more due to factors such as leg room, roof height and general size of the seating area, none of which are modeled by the game. You could possibly try to make guesses about the room available based on the name of the vehicle, or by introducing vehicle interior space classifications to vehicles (that would have to work with custom vehicles, including the customization of normally cramped vehicles to fit large people.

**Comment by feinorgh** [comment]
Currently the comparison for both storage space and whether a character fits into a seat is determined by the "size" property of seats. If I understand it correctly the "size" property models both the size of the vehicle part itself, and how much it can store, which would roughly hold true for square boxes, but likely not for much else. Some big vehicle parts cannot store anything at all, while others are are meant to function as storage space themselves.

For instance, a table may take up 20 L space, but you can probably "store" much more on it (say, a 60 L metal tank).

A car seat may take up 85-95 L of space itself, but as @PatrikLundell mentioned, how much you can store in the seat, and how big a person can fit in that seat in a given car should realistically be two different things. I've personally put an empty 210 L plastic watering container in a passenger seat in a small car.

One technical solution would be to add explicit "storage volume" to the vehicle parts that need them, especially seats, and provide a separate check depending on the type of car for how large a character can use a seat, and with what difficulty.

I'll make some attempts to model this.

**Comment by anoobindisguise** [comment]
I've been having the same issue.

**Comment by Zireael07** [comment]
I believe the offending PR was reverted?

**Comment by feinorgh** [comment]
> I believe the offending PR was reverted?

It was removed from inclusion in 0.H, but remains in experimental.

**Comment by RenechCDDA** [comment]
Resolved by #74981
