### ISSUE TITLE
Map falls apart after update

### ISSUE THREAD

**Issue by Void-Seeker** [CleverRaven/Cataclysm-DDA#74683]
### Describe the bug

With cdda-experimental-2024-06-19-1355 db4fb60 provided save file loads correctly, but on latest update map is corrupted, character is inside the wall, their vehicle is inside a wall, it's a mess.

### Attach save file

[Квойн-trimmed.tar.gz](https://github.com/user-attachments/files/15909417/-trimmed.tar.gz)

### Steps to reproduce

1. Load provided save file in latest version (cdda-experimental-2024-06-20-0230 c0e4c91) and in cdda-experimental-2024-06-19-1355 db4fb60

### Expected behavior

Not corrupting the map, i guess...

### Screenshots

![Катаклизм: Тёмные дни впереди — cdda-experimental-2024-06-20-0230 c0e4c91_001](https://github.com/CleverRaven/Cataclysm-DDA/assets/11269938/b97691ed-2f16-44ac-bff3-8bcbbc2a990e)
![Катаклизм: Тёмные дни впереди — cdda-experimental-2024-06-19-1355 db4fb60_001](https://github.com/CleverRaven/Cataclysm-DDA/assets/11269938/905722ca-e552-4399-bbd6-a74448db37e1)

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Linuxmint; Description: Linux Mint 21.2; Release: 21.2; Codename: victoria; 
- Game Version: cdda-experimental-2024-06-20-0230 c0e4c91 [64-bit]
- Graphics Version: Tiles
- Game Language: Русский <color_dark_gray>(89,3%)</color> [ru]
- Mods loaded: [
    Тёмные Дни Впереди [dda],
    Отключить потребности у НПС [no_npc_food],
    Портальные штормы игнорируют НПС [personal_portal_storms],
    Медленный рост фунгалоидов [no_fungal_growth],
    иконки видит-игрока, бег, приседание, кровотечение для retrodays [sees_player_retro],
    Характеристики за навыки [StatsThroughSkills],
    Характеристики за убийства [stats_through_kills],
    Скорость от ловкости [speedydex]
]

### Additional context

[config.zip](https://github.com/user-attachments/files/15909574/config.zip)

**Comment by Void-Seeker** [comment]
After messing around I've determined that the version that breaks the map is cdda-experimental-2024-06-19-1857 e4840ea. Last working one is cdda-experimental-2024-06-19-1635 5f78795.

**Comment by PatrikLundell** [comment]
/Confirmed

It seems a number of overmaps are rotated compared to what they should be.
It can be noted that the facility is a mess of different rotations inherently, both when loaded with an old exe and a new one, so the cause seems to be that something rotates some of the overmaps again, not that the rotations are specified incorrectly with the new exe (the west side consists of east sections with a rotation of 1, the east side consists of west sections with a rotation of 3, the facility itself has a rotation of 3, and the parking area has a rotation of 2).

It's also raining monsters with the new exe (monsters spawned up in the air).

**Comment by Void-Seeker** [comment]
Yeah, it's really weird that monsters respawned on the new version. That locaation was mostly cleared of monsters, there shouldn`t be many monsters left, especially on the surface. Monsters respawning on already cleared location might be separate issue.
