### ISSUE TITLE
Tacoma: blanket mission should accept all kinds of blankets

### ISSUE THREAD

**Issue by Antrocon** [CleverRaven/Cataclysm-DDA#74726]
### Describe the bug

Takoma mission 'Find 25 blankets' currently only accepts 'floral blankets', without mentioning specific type of blanket anywhere. I guess it's a legacy remnant from earlier releases when 'blanket' was a specific item, not a flavoured group.
In any case, given the mission description, it should accept all kinds of blankets: floral, sports, weighted, down-filled, etc. all blankets function the same after all and it's not a 5-star Hilton they're trying to establish.

Alternatively, adjust mission description to require specific type of blanket

### Attach save file

N/A

### Steps to reproduce

1. Accept 'find 25 blankets' tacoma mission. read mission offer description, how they need blankets for new refugees, etc. notice no mention of specific blanket type
2. scourge some various blankets, 25 total
3. bring all to foreman, try to give in: unable
4. debug spawn 'blanket' item, 25 count. notice actual item name 'floral blanket'
5. give in mission: success

### Expected behavior

all types of blankets are accepted

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4529 (22H2)
- Game Version: cdda-experimental-2024-06-19-1635 5f78795 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bombastic Perks [bombastic_perks]
]

**Comment by PatrikLundell** [comment]
There are two classes of blanket in the game: different items (regular, down, weighted, etc.) and variants of items (floral, and other decorative versions of the regular blanket).
Due to how the logic works, the game is not set up to be able to collect items of different kinds to get the required number of items (I don't know if it's impossible: it MIGHT be possible to devise some convoluted logic to sum things up). However, if variants are treated as different from each other the logic is broken, as the quest was written (to accept regular blankets only) when there weren't variants. Thus, floral and polka dots (if there is such a variant) SHOULD both be counted as regular blankets and thus be grouped together. If that's not the case, the item count logic is either faulty or the wrong version of it is used in the quest.

There is another quest written differently that accepts blankets OR quilts OR down blankets OR... for about 5-6 items, but that logic requires all of them to be of the same kind (not a combination). Also, it's broken in that it requires all the items to be in the PC inventory, and blankets are damned bulky, so they won't fit (quilts worked).

**Comment by GuardianDll** [comment]
Lack of save file attached here suddenly made my work much harder

**Comment by PatrikLundell** [comment]
Yes, it's a general problem that reporters think they don't need to provide any save file because the issue is fully repeatable, while ignoring the fact that setting up the conditions may in fact require a fair bit of work, which, in itself, might discourage people from actually investigating and fixing the problem..
