### ISSUE TITLE
Artisan Gunshow Doesn't Generate

### ISSUE THREAD

**Issue by flashing-blades** [CleverRaven/Cataclysm-DDA#74881]
### Describe the bug

When asking Cory about the mission, an error occurs and the gunshow fails to generate

### Attach save file

[Poplar Hills-trimmed.tar.gz](https://github.com/user-attachments/files/16088710/Poplar.Hills-trimmed.tar.gz)

### Steps to reproduce

1. Create world with MoM
2. Find Artisans
3. Ask Cody for Quest
4. Fail to generate

### Expected behavior

The gunshow is supposed to generate, as it is vital to the completion of the mission.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4529 (22H2)
- Game Version: 4f065b5 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mind Over Matter [mindovermatter]
]

**Comment by flashing-blades** [comment]
Well, that's weird. It's not consistent with when it generates, but as far as I can tell, MoM has something to do with it. All the unmodded worlds I tested worked without a hitch, but some've the modded ones failed.

**Comment by Standing-Storm** [comment]
MoM World: Failed to generate 2 out of 10 times
World with Xedra Evolved and Magiclsym: No failures (out of six)
Vanilla world: No failures (out of six)

Not sure if there's a problem or if this is within the bounds of random failure, since there's nothing in MoM that touches either the gun show or the artisans (maybe it's because of the large amount of map specials MoM adds?). However, if #73925 raised the LIXA search radius to 800, maybe the same should be done for the gun show (it's currently at 400)

**Comment by GuardianDll** [comment]
I suppose #74885 should fix this, but if it was not, i will reopen it
