### ISSUE TITLE
place_variables in mapgen broke recently

### ISSUE THREAD

**Issue by LyranRenegade** [CleverRaven/Cataclysm-DDA#74971]
### Describe the bug

I narrowed down the issue I had in #74861 {which I closed to open this one]
To the fact that place_variables in mapgen doesn't work as advertised anymore.

IN mapgen.md
https://github.com/CleverRaven/Cataclysm-DDA/blob/6389b8b4965e08d5ae9d495eddbbae6f47d3ac2b/doc/MAPGEN.md?plain=1#L681

It is stated that the z-part of the variable will be the one corresponding to the one concerning the mapgen.
This is no longer the case.. it will always be "10".
Adding a "z" value doesn't make any difference, it will always be 10.

### Attach save file

N/A

### Steps to reproduce

Put this in any old mapgen that's not on z-level 10
```
            "place_variables": [
                { "name": "HA_LEVEL0_TEST_LOC_0",           "x": 11, "y": 16 },
                { "name": "HA_LEVEL0_TEST_LOC_1",           "x": 11, "y": 16, "z": -1 }
            ]
```

add a debug eoc
```
    {
        "type": "effect_on_condition",
        "id": "EOC_HA_DEBUG_TRACE_LOCATION_VARIABLE",

        "effect": [
            { "message": "HA_LEVEL0_TEST_LOC_0: <global_val:HA_LEVEL0_TEST_LOC_0>" },
            { "message": "HA_LEVEL0_TEST_LOC_1: <global_val:HA_LEVEL0_TEST_LOC_1>" }
        ]
    },
```
run the eoc from debug menu once you are at the omt of the the location 

see how in both cases the z-value is "10"

### Expected behavior

expected is that the z-level has the value of the mapgen 
and
that filling in a number for the z-component in place_variables optionally adjusts the z-level by that amount [as in the docs]

### Versions and configuration

win7
06460ed (tiles)

**Comment by PatrikLundell** [comment]
I failed to repeat the issue using a just downloaded and compiled Master.

The "version" reference you give is 3 weeks old, and I believe I've seen a PR fixing what's probably is the same issue sometime in the recent past, although I failed to find that PR.

My test was done on the mi-go portal, and the Z levels printed by your EOCs were 0 and -1 respectively, which is what's expected.

Thus, I suggest you try to perform the test on a recent game version and close the issue if it turns out to be fixed. If it's somehow not fixed, please add a comment to that effect so we can proceed in trying to figure out what's wrong.

**Comment by LyranRenegade** [comment]
awesome it was already fixed indeed !
