### ISSUE TITLE
[Modded] Massive slowdown when unwielding any item

### ISSUE THREAD

**Issue by meelock** [CleverRaven/Cataclysm-DDA#75098]
### Describe the bug

First, I want to make it clear that this bug appears to only be occuring in my modded instance and not when I tested the same scenario in vanilla. The slowdown is experienced whenever unwielding any item, and makes the game run approximately 1/4 as fast.

### Attach save file

[!!!Knolls-trimmed.tar.gz](https://github.com/user-attachments/files/16292602/Knolls-trimmed.tar.gz)

### Steps to reproduce

1. wield an item
2. unwield it
3. experience a 1/4 times slowdown.

### Expected behavior

No slowdown after unwielding an item.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4651 (22H2)
- Game Version: cdda-experimental-2024-07-18-1929 83ac2a2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Aftershock [aftershock],
    <color_cyan>Arcana and Magic Items</color> [Arcana],
    <color_light_green>Cataclysm++</color> [Cata++],
    <color_light_red>Secronom</color> [secronom],
    <color_light_red>Secronom+ Lore Expansion</color> [secronom_lore_expansion],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Medieval Mod Reborn [Medieval_Mod_Reborn],
    MST Extra [MST_Extra],
    <color_cyan>Arcana</color>/<color_light_green>Cata++</color> Patchmod [Arcana_Cata++_Patch],
    <color_cyan>Arcana</color>/Aftershock Patchmod [Arcana_aftershock_Patch],
    <color_cyan>Arcana</color>/Magiclysm Patchmod [Arcana_Magiclysm_Patch],
    <color_light_blue>Lighter Weariness</color> [light_weariness],
    Mythical Martial Arts [MMA],
    <color_yellow>Mythical Martial Arts - Mods Extension</color> [MMA_Mods_Extension],
    Vampiric Stuff [vamp_stuff],
    Vampiric Stuff + Arcana Mod Extension [vamp_stuff+arcana],
    Dorf Life [Dorf_Life],
    Tankmod: Revived [Tankmod_Revived],
    Blazemod - Vehicle Additions Pack [blazemod],
    Miscellaneous Magiclysm Expansions [demon_spider_a],
    No Bionic Slots [no_cbm_slots],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Translate Complex Dialogue [translate_dialogue],
    Bombastic Perks [bombastic_perks]
]

### Additional context

[mods.tar.gz](https://github.com/user-attachments/files/16293058/mods.tar.gz)

**Comment by John-Candlebury** [comment]
This will be impossible to confirm with a third party modlist that extensive. Try to remove all but the mods that come with the game and see if the issue persists.

If it doesnt theres nothing we can do about it.

**Comment by meelock** [comment]
This only started occuring in the last day, so I assumed it was base game related, but was unable to reproduce it with just base game without any content mods.

**Comment by meelock** [comment]
This issue also doesn't appear to affect new games, only preexisting ones.

**Comment by meelock** [comment]
Confirmed that this issue does not occur in versions before https://github.com/CleverRaven/Cataclysm-DDA/commit/db3435138781937e9e0e999abbaa53f1d3afb5b7.

**Comment by PatrikLundell** [comment]
I doubt that PR is the cause because the modified code is executed at save loading only. Specifically, it deals with loading of item_locators in the save. That part can possibly be slowed down marginally, because the code fix introduces and loads a smallmap when reading JSON data.
Also note that it doesn't change saving of the JSON data, so new games are saved in the same wonky format old saves are (saving the reality bubble relative coordinate of the item referenced regardless of whether the item is inside the bubble or not. Note that this results in the correct location, but to access it you need to translate things to a map around that location, rather than trying to use the current reality bubble and then give up because the item isn't inside the bubble).

Regardless, we'd have to be very lucky to be able to find issues without the ability to reproduce them (the lucky case is basically getting enough info to be able to figure out where in the code to look, and then be able to spot the problem based on inspection). Slow execution is even worse, as it tends to be an aggregate of different things. A sudden change may be caused by someone adding a new check the caller (and possibly the author as well) doesn't is expensive. You typically need to do performance analysis to track down performance issues, and that requires access to a test case as well as someone able to use such tools.

**Comment by RenechCDDA** [comment]
Patrik, check out the profiling at https://github.com/CleverRaven/Cataclysm-DDA/issues/75085#issuecomment-2238841352. Definitely running outside of the save/load cycle

**Comment by PatrikLundell** [comment]
OK. I think you have a compelling argument, and I'm willing to admit I may be wrong. The change seems to be in a more widely used operation than I thought.

I'll try to investigate this.
