### ISSUE TITLE
Allow NPCs to give players nicknames and comment on their names.

### ISSUE THREAD

**Issue by zachary-kaelan** [CleverRaven/Cataclysm-DDA#75107]
### Is your feature request related to a problem? Please describe.

While it's always funny to see NPCs in games say a stupid name, it can make it more difficult to take the NPCs seriously. Players that take a randomly generated name are given a random nickname, but it would feel more organic if they were granted that nickname at some point by an NPC.

### Solution you would like.

If the player's name is set manually, it checks against the full list of nicknames and first/last names used for random generation. If it matches a nickname or matches close enough, NPCs use that name. If it matches a normal name, NPCs randomly grant them a nickname at some point during dialogue. If it doesn't match, a silent intimidation check is done to see if the NPC says some variation of, "What the hell kind of name is that? I'm not calling you that. I'm going to call you X instead". Any NPC that meets them will also adopt any nickname they have given the player. If two NPCs that have given the player nicknames meet, the one that sticks depends on intimidation or favor or something. If the player doesn't like a nickname, they can murder the NPC that gave it to them.

**Comment by Little-119** [comment]
Probably overcomplicated to implement, and (if having NPCs react realistically to silly nicknames is the/a goal) it's a player's own fault if inputting silly things into a singleplayer game gives them silly results.

If this is implemented, Liam from Friends to the End should be given the special case of not granting the player a nickname--He's known the player so long that it can be assumed that their friend group is where their nickname comes from (or would have)

**Comment by kevingranade** [comment]
Big no from several angles.
If you're using a randomly generated name, having a NPC use it is de facto not a problem, it's something you opted into.  If you don't like that, stop using random names? You can also just hit reroll on the name if you don't like it IIRC.

Your proposed solution doesn't even address this, it's just substituting one random name selection for another? The NPC would be pulling from the same list of names as the random name assignment at character creation, right?

Treating someone differently because they have an unusual (i.e. not on the name list) name is a big problem. Imagine someone uses (or is even randomly assigned) their actual name (or the name of someone they know) for their character name and it triggers this, we are having a NPC insult the PLAYER's name, that is very not cool.  I'm sure it's unintended but there's also a hint of racist behavior here. Ethnic minorities have their names called out like this constantly, and it's not because "the name is weird", it's because the person calling it out is looking for an excuse to highlight the "other-ness" of the target.
