### ISSUE TITLE
Segfault on unloading bottle of antacid tablets

### ISSUE THREAD

**Issue by AzyWng** [CleverRaven/Cataclysm-DDA#75156]
### Describe the bug

Got a segmentation fault when attempting to unload a bottle of antacid pills (specifically, one that only had one pill inside) while possessing other bottles of antacid pills.

### Attach save file

[Summers-trimmed.tar.gz](https://github.com/user-attachments/files/16327241/Summers-trimmed.tar.gz)

### Steps to reproduce

1. Get several bottles of antacid pills that are not full - and one bottle with only one pill.
2. Unload the bottle of antacid pills that only has one pill.
3. Crash.

### Expected behavior

I expected the single antacid pill to transfer to one of the bottles with more antacid pills, without crashing.

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: EndeavourOS; Description: EndeavourOS Linux; Release: rolling; Codename: rolling; 
- Game Version: cdda-experimental-2024-07-21-1759 9e39260 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

[pills crash.zip](https://github.com/user-attachments/files/16327225/pills.crash.zip)

**Comment by PatrikLundell** [comment]
/Confirmed

Happened with both the single pill and 4 pill bottles (the two I've tried so far).

**Comment by inogenous** [comment]
The savegame has the antacid-pill-bottles inside a steel pan, which itself is in the backpack. When unloading the single pill bottle, this will cause the steelpan to spill its contents. This spilling, in turn, invalidates the `item_location` and the `item`. Normally, the items would spill to inventory, but since all eligible pockets are full, the pill bottles will spill from the steelpan onto the ground. 

Having the pillbottles inside the steelpan like that should not be possible since the steelpan is a spillable container, but apparently it is, and that's possibly a separate issue.

#75299 resolves the segfault, and adds a user-shown message when spilling items from the steelpan (`The plastic bottle falls out of the steel frying pan`).
