### ISSUE TITLE
Game freeze near FEMA camp with Only Wildlife mod

### ISSUE THREAD

**Issue by cknight828** [CleverRaven/Cataclysm-DDA#75212]
### Describe the bug

I try to reach FEMA camp and CDDA freeze when Only Wildlife is enabled.
Teleporting  to the camp also cause freeze.

### Attach save file

[nomonster-trimmed.tar.gz](https://github.com/user-attachments/files/16362605/nomonster-trimmed.tar.gz)

### Steps to reproduce

1. Load attached save
2. go one step north

### Expected behavior

Player should be able to reach FEMA camp without freeze

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Debian; Description: Debian GNU/Linux 12 (bookworm); Release: 12; Codename: bookworm; 
- Game Version: cdda-experimental-2024-07-24-0510 a24a4db [64-bit]
- Graphics Version: Tiles
- Game Language: システム言語 []
- Mods loaded: [
    コア - Dark Days Ahead [dda],
    削除 - NPCの欲求 [no_npc_food],
    変更 - NPCに無害なポータル嵐 [personal_portal_storms],
    変更 - 真菌増殖抑制 [no_fungal_growth],
    削除 - モンスター [Only_Wildlife]
]

**Comment by PatrikLundell** [comment]
It seems the code is in a loop trying to spawn monsters.
It seems to be in an infinite loop trying to spawn some specific kind of monster (a list of one entry).
MonsterGroupManager::GetResultFromGroup doesn't decrement the quantity parameter, and the loop continues until it has been reduced to a non positive number...
For some reason the entry.is_group branch doesn't reduce the quantity while the other branches do.
It claims to have found a monster but then delivers an empty list, thus bypassing the logic intended to decrement the count when nothing was found. Some default value is placed in the list, so something is still returned, but the value doesn't decrement.

The loop seems to be in mapgen.cpp operation map::place_spawns.

How to fix this mess? I don't know. That's probably for someone who understands how this convoluted mess is supposed to work (decrease quantity if spawn_details is empty, rather than if a monster is claimed not to be found?).

**Comment by cknight828** [comment]
It seems the game will freeze only when tries to spawn GROUP_VANILLA with density field. The group is used with density field in FEMA camp and homeless camp.
