### ISSUE TITLE
The documentation is wrong about milling syntax

### ISSUE THREAD

**Issue by Karol1223** [CleverRaven/Cataclysm-DDA#75293]
### Describe the bug

While working on #74364 I realized that our documentation about milling syntax has not been updated after #71677 got merged and changed it.

### Attach save file

N/A

### Steps to reproduce

Just... read the documentation for milling syntax, see that it's talking about something else entirely than what we use nowadays.

### Expected behavior

It's cool when the docs are helpful.

### Versions and configuration

N/A

### Additional context

@PatrikLundell would it be alright to ask you to help with this, given you were the author of the PR that changed the syntax? I know you have your hands full with mapgen nowadays, so no rush, I am just pinging you here to let you know about the issue.

**Comment by PatrikLundell** [comment]
Asking in a civilized manner (like this) should always be an option. Demanding or not accepting a reasonable rejection would be a different thing altogether, especially if it was rude.

I haven't looked at the documentation yet, but I assume you're correct. Documentation is something I tend to forget about and only occasionally remember that it should be updated (in particular since I expect documentation to be outdated and incomplete, and so only refer to it as a source of some possible background).

I don't actually have my hands full with mapgen, as that task is complete (apart from the bugs that keep cropping up, and potentially things missed that haven't been discovered yet).

I'll take a look at it.
