### ISSUE TITLE
"?" and blanks in ui

### ISSUE THREAD

**Issue by bateau-de-coal** [CleverRaven/Cataclysm-DDA#75362]
### Describe the bug

"?" and blanks in ui

### Attach save file

happens on new game that has no save

### Steps to reproduce

open the game, settings > keybindings

### Expected behavior

ui to be displayed normally

### Screenshots

![Screenshot from 2024-08-01 12-44-37](https://github.com/user-attachments/assets/6b037c59-b856-48b1-9740-4d56d5de320a)

### Versions and configuration

ubuntu
build type: linux-curses-x64
build number: 2024-08-01-0347

**Comment by bateau-de-coal** [comment]
![Screenshot from 2024-08-02 10-54-12](https://github.com/user-attachments/assets/d2c2a9a4-8e92-4bd8-bd0e-a55f05ac346f)
This is the imgui demo screen.

Language has been set to English and German. UI was displayed incorrectly in either case.

**Comment by l29ah** [comment]
I observed this when i built cataclysm with gcc-14. Reverting to gcc-13 fixed that for me.

**Comment by Muffindrake** [comment]
![2024-08-05T14:21:20,749410698+02:00](https://github.com/user-attachments/assets/98fc001e-edeb-44fd-9ca8-f2d70a80f4cc)
Terminal is kitty 0.35.2 under wayland. Same problem. Tried to build current HEAD, but it shows the same problem, even in xterm 393:
![2024-08-05T15:48:23,575625139+02:00](https://github.com/user-attachments/assets/40daa588-86e8-40c8-aa2e-733994d2d4db)

Broken with both clang-18.1.8 and clang-19.1.0_rc1
Version: cdda-experimental-2024-08-05-1158 35e37f33e8
Libraries: glibc 2.40, ncurses 6.4_p20240414

**Comment by alef** [comment]
@bateau-de-coal 
> This is the imgui demo screen.

That will be fixed by #75905

**Comment by juur** [comment]
I doubt it helps, but, if I hard code this line, inside src/third-party/imtui/imtui-impl-text.cpp around line 232 in ImTui_ImplText_RenderDrawData():

`cell.ch = col1;`

to be

`cell.ch = 'a';`

and hard code chwidth to 1, my broken UI elements render per below, before this, i also get random ?s everywhere so the game is unusable under ncurses. This feels like something in the RenderText() function - which looks complicated custom UTF8 processing - isn't working properly 

![image](https://github.com/user-attachments/assets/a4f2e0fd-6af8-4252-99aa-a546d0b22eae)

**Comment by jkoudys** [comment]
> @bateau-de-coal
> 
> > This is the imgui demo screen.
> 
> That will be fixed by #75905

Doesn't seem like it did. I built against 8d2ad4c0ed09a349476179fad4f4ba9c87eb5b10 (commit on master from this morning) and it has the same issue. Some menus, like keybindings or the imgui demo show with ? and blanks. Other pop-ups like the exit "are you sure?" prompt or the resume-crafting, waiting-how-long, menu are also blank. Others, like the safe mode manager, work just fine.

I'm running Chromeos with this inside a Debian Bullseye chroot. Same issue either from the Chromeos terminal, SSH'd in from another terminal, or run from xterm in xfce4. Happens at any terminal resolution.

**Comment by db48x** [comment]
Ah, this was a fun one. Fixed it:

![Screenshot from 2024-08-29 05-44-37](https://github.com/user-attachments/assets/9c0f98e0-0c33-43ac-9dd5-0904186e21d7)

I used a really great debugger called Pernosco to track this down. It’s an omniscient debugger. Instead of stepping through the program one line at a time, you can click on a line number and it gives you a list of every time that line was ever run. If you click on the value of a variable, it can track that value backwards through the program, showing you a list of every line where the value changed or was copied. 

@juur had already found that the values in the drawlist were wrong, so I started there. col1 had a value of 0xFF9696FF, which does not look much like a character to me. Tracing that backwards, I could easily see that it is indeed an RGBA color. The `ImDrawList::AddText` method writes this value into the drawlist, which probably makes a lot of sense for ImGui. But it’s supposed to be a character here. Here’s what I was looking at in the debugger:

![Screenshot from 2024-08-29 05-47-08](https://github.com/user-attachments/assets/e5dc2bd9-8807-4e6c-8b21-821370ee0af1)

Can you spot the bug? 

<details>
<summary>Spoilers!</summary>
The orange marks on each line tell you which ones were run; very useful when there are conditions and loops. Or in this case, ifdefs. Somehow IMTUI wasn’t defined so we're running the normal ImGui code here. Oops! Luckily that’s an easy fix.
</details>

PR incoming.

**Comment by khuey** [comment]
One additional thing that you might find helpful about the Pernosco UI in this case: that the line numbers are grayed out means no executable code was associated with that line by the compiler. Further evidence that it was ifdefed out.
