### ISSUE TITLE
Refugee Center Guards Do Not Rotate Positions

### ISSUE THREAD

**Issue by MNG-cataclysm** [CleverRaven/Cataclysm-DDA#75651]
### Describe the bug

The guards in the refugee center are supposed to rotate positions every two hours, but they don't do that. Instead, they remain in the same position indefinitely.

### Attach save file

[Catahoula-trimmed.tar.gz](https://github.com/user-attachments/files/16621133/Catahoula-trimmed.tar.gz)

### Steps to reproduce

1. Go to the refugee center.
2. Wait around for two hours.
3. Observe that the guards do not move.

### Expected behavior

I expected that the guards would move around based off of the time.

### Screenshots

N/A

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.3880 (23H2)
- Game Version: cdda-experimental-2024-08-12-2352 12bb7da [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

I suspect that this might be caused by `place_variables` in mapgen definitions not working somehow, as copying the EOC structure and using it with different variables (placed with EOC-based `u_location_variable`) works.

**Comment by PatrikLundell** [comment]
Provide a save at the refugee center for people to verify, rather than expecting others to spend time creating a game, find the refugee center, and get there in order to perform a "trivial" verification.

Also, I think you're wrong in your assertion: According to my memory of looking at this in conjunction with spam resulting from the EoC failing to move dead guards, ONE guard is moved every two hours, with different guards tied to different times. Thus, in order to actually check this, you'd have to check the location of every guard (debug clairvoyance and screenshot might do it unless you can memorize all of their locations) and wait two hours before making a new check (if you debug pass time I'd suggest waiting "properly" for some time after that, since some things seem to take a number of turns to catch up after a debug wait).

**Comment by MNG-cataclysm** [comment]
So, with this new information, I retested the EOC and it worked.
