### ISSUE TITLE
using a too high mapgen weight will silently ignore the chunk

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#75741]
### Describe the bug

The desert region does cool mapgen things to dry out the rivers and lakes. For an unknown reason, they have reverted to default and have no visible changes applied to them except the changed overmap symbol.

The mod is obsoleted so why do I bother making an issue? Because I ripped the relevant parts out of the mod to achieve a similar goal and keep running into this issue. I have been at it for 2h yesterday to try and figure it out but to no avail.

### Attach save file

n/a

### Steps to reproduce

Important: As of writing, the mod does not load due to an oversight. The fix is trivial and waiting to be merged in #75727. You must apply this fix to be able to test.

1. Create a desert region world (mod is obsoleted, so you either unobsolete it manually or edit the world mod list directly)
2. Search for a river or lake
3. It is full of water and has no changes applied.

### Expected behavior

The rivers and lakes are dried out.

For your convenience, here are the relevant files:

https://github.com/CleverRaven/Cataclysm-DDA/blob/700bbd76fdb96fbd9a598170f77f01ad45c0ba1d/data/mods/desert_region/overmap/desert_overmap_terrain.json#L147-L227

https://github.com/CleverRaven/Cataclysm-DDA/blob/d63de4e1604c5d0f44cba15c1ef7f03031a6d971/data/mods/desert_region/mapgen/waterbody.json#L3-L46

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: cdda-experimental-2024-08-10-1416 c50cb75 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Desert Region [desertpack]
]

### Additional context

@Procyonae halp, but I heard you are still on vacation or something

**Comment by PatrikLundell** [comment]
Heh! It seems the cause is trivial to fix (once you've stumbled upon the solution). Try to remove two zeroes from the weight the first mapgen  in waterbody.json so the number fits into a 32 bit integer. I'd check other files for any similar issue.

![Screenshot (625)](https://github.com/user-attachments/assets/b37d1ecb-7a90-4a97-a94d-b425af368978)

**Comment by NetSysFire** [comment]
I think the actual actionable thing to do is to have an error when the weight exceeds the limits.

**Comment by PatrikLundell** [comment]
I agree. The compiler probably warned about the risk of downsizing, and all such instances ought to have checks rather than just ignoring the warnings or hard coding conversions.
Weights exist in a lot of places, so there are a fair number of sanity checks needed for a full coverage.
It's possible it might be useful to introduce a down_cast operation that performs checks and issues error reports with a default message overridden by a string parameter for easier handling of integers read from JSON.
