### ISSUE TITLE
Player character drops their weapon when grabbed

### ISSUE THREAD

**Issue by bird-ee** [CleverRaven/Cataclysm-DDA#75810]
### Describe the bug

Grab attacks cause the player to think they are missing an arm when their arm is otherwise "preoccupied" with being grabbed. This seems like an oversight

### Attach save file

N/A

### Steps to reproduce

1. Fight a zombie
2. Zombie grabs the player
3. Player drops their weapon

### Expected behavior

1. Fight a zombie
2. Zombie grabs the player
3. Player does not drop their weapon

### Versions and configuration

N/A

**Comment by Kantonine** [comment]
Not a bug, Intended behavior from the grabbing system

**Comment by bird-ee** [comment]
How could that possibly be intended behavior?

**Comment by Terrorforge** [comment]
It's hard to use large, cumbersome weapons while wrestling with a zombie. You can wield a knife or handgun just fine, but swinging a fire axe would be very difficult. That's what this mechanic simulates.

It may seem weird that you _always_ drop the weapon, but that depends on your strength, the weight of the weapon, and the strength of the grab. There does in fact exist a middle ground where you can still use the weapon, but with a penalty.

**Comment by bird-ee** [comment]
Seems to me like the player should receive penalties to using whatever weapon is deemed too difficult to use while grabbed

If the player wanted to disarm an enemy, they would need to use specific martial arts techniques or rare/fragile weapons. It's really difficult to believe that a literal zombie could do it just by lunging at you

**Comment by Terrorforge** [comment]
I told you, that's already a feature. Grabs apply various melee penalties, so depending on your strength and the weapon there exists a middle ground where you can hold on to your weapon and keep using it again with reduced efficacy.

Also idk what you're imagining when you hear "grab", but IMO when ~150lbs of dead flesh hangs itself from your neck and tries to both crush you to death and bite your throat out, dropping your weapon (or otherwise losing control of it) seems like a very possible outcome.

**Comment by bird-ee** [comment]
That doesn't seem possible at all to me. Only a direct injury or pain should have any affect on the player's grip of their weapon. If the grab isn't damaging or painful, I don't see how their hand should magically unclasp

**Comment by Terrorforge** [comment]
Have you ever been grabbed in real life? Like genuinely manhandled by someone who is actively trying to pin you down? It does not do wonders for your grip strength. Squeezes your muscles in odd ways, puts you in all sorts of weird angles. And especially since we're talking about longer implements (you can almost always use a knife), there's gonna be all sorts of weird leverage happening. Not to mention the surprise factor of being yanked around.

And even if the weapon isn't literally wrenched out of your hands, it can still be rendered unusable. Like if you're wielding a halberd and a zombie pins one of your arms against your chest, or the halberd against your chest, you might still technically be holding the halberd, but you're not gonna be able to make meaningful attacks with it. This is currently represented by making the character drop the weapon. _Maybe_ there would be some merit to representing it in a more granular fashion, but I don't really see the point. You'd basically be doing unarmed damage even though you're wielding a weapon, and the correct solution would still be to drop it and draw a lighter weapon. So it would functionally be the same as forcing you to drop your weapon, except it would be a lot loss clear what the problem is.

**Comment by bird-ee** [comment]
There is already a 70% modifier for many long weapons.

**Comment by bird-ee** [comment]
Additionally, if grabs are going to be so punitive, it's pretty obvious that there needs to be some further interaction options. If attacking while grabbed with any weapons is going to deal unarmed damage, then perhaps attacks that are weakened to this state should also be a grab break attempt. Similar to grip strength, your characters' actual physical ability is unaffected by whether or not a zombie is grabbing a part of their body or not. That strength should be going somewhere, such as fixing the problem.

Infinite kiting isn't a very interesting gameplay mechanic

**Comment by kevingranade** [comment]
The alternative here is you hold onto the weapon, become unable to use it, and suffer a penalty to even your unarmed attacks because you're dividing your efforts between retaining your weapon and attacking and/or defending.

That doesn't help anyone, so we didn't do it that way.  It's less that you're physically forced to drop the weapon than it becomes absolutely pointless to retain it to the point where your character does it automatically.

Tit for tat balance isn't how things work, there are potential adjustnents we could make to grappling, but just throwing out, "there should be additional countermeasures" with no rationale behind them isn't productive.
