### ISSUE TITLE
Multimag

### ISSUE THREAD

**Issue by GuardianDll** [CleverRaven/Cataclysm-DDA#75859]
### Is your feature request related to a problem? Please describe.

There was a lot of talk about it, but #75361 showed clearly that we need a **multimag**

### Solution you would like.

Multimag, in this topic, means an ability for item to hold multiple magazines of type MAGAZINE and MAGAZINE_WELL - for starters would be enough only this, ability to shove multiple batteries into flashlight at once - but for the future it would need to be expanded to accept multiple different ammo types also, like for pneumatic weapon, that uses both physical ammo and air simultaneously

**Comment by kevingranade** [comment]
Two issues here.  As you point out when we've said multimag in the past we usually mean multi-ammo such as "projectiles and also charges of air pressure".

The second thing is I disagree that we need to support items that hold multiple batteries, we've intentionally streamlined tools that accept batteries to where they just accept a single battery pack of a reasonable size base don their use case, not multiples of the same size of battery.  Accepting two "light_battery_cells" instead of bumping the capacity up to one "medium_battery_cell" isn't a particularly meaningful difference, and it brings complexity to both the infrastructure and how players handle loading batteries into tools.
