### ISSUE TITLE
Silk items?

### ISSUE THREAD

**Issue by Bone-blood-moss** [CleverRaven/Cataclysm-DDA#75954]
### Is your feature request related to a problem? Please describe.

Why don't we have silk items or Material? We have giant spider webs And silk pajamas are pretty common.   

### Solution you would like.

Silk items, Silk Material, Silk rope. Our survivors should be able to harvest webs to make Shirts and other pieces of clothing. Just Imagine Reinforced Silk jumpsuit.

### Additional context

Was fighting spiders and Thinking about Insect mutations Then saw the webs thought about it.

**Comment by PatrikLundell** [comment]
Silk is made from silkworms, not spiders. There are various attempts to use spider silk to produce things, but it's not on any industrial scale, and a lot of it seems to be geared towards genetically modified creatures to produce the raw proteins rather than the silk threads (proteins in milk is one approach).

Now there are, obviously, not any attempts to make use of giant spider silk, as such creatures don't exist, but I'd expect it not to be that much easier than using regular spiderweb.

**Comment by Bone-blood-moss** [comment]
I doubt our survivor is trying to farm spider silk. The main problem with real life spider farms spiders is Spiders are cannibals. But the spider mutant or survivor with Mass of spider webs around them Could harvest some Silk. Spider mutant can Even use their own. Spider silk is Much stronger than silk worm silk. When you Have over 3 feet worth of spider silk. I'm pretty sure a survivor would use silk in some way. Some clothing something.

**Comment by Zireael07** [comment]
As Patrik said, spider silk use isn't really a thing IRL. We could probably make an exception for spider mutant's own silk, but the rest is just unusable from a practical POV

**Comment by kevingranade** [comment]
Once the silk is spun into a web it's incredibly difficult to impossible to harvest, which is why as Patrick said, no one is following that approach. You're basically talking about trying to reinvent textile processing with a novel material, plus one that might have very inconsistent properties.

This is a non-starter.
