### ISSUE TITLE
Contrast of the time played in the save loading menu is very poor

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#75974]
### Describe the bug

![image](https://github.com/user-attachments/assets/47094637-4bd8-406c-8bb0-29f319cd6167)

### Attach save file

n/a

### Steps to reproduce

1. Try to load a world.
2. See that active entries have this very poor contrast.

### Expected behavior

Better contrast. This is how it looked before the imgui uilist:

![image](https://github.com/user-attachments/assets/470e0f35-4735-44b8-8ff3-31332a5839d4)

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: cdda-experimental-2024-08-26-0429 18b13f1 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

Good first issue because this seems as simple as changing a color.

**Comment by ZhilkinSerg** [comment]
I think it is not as easy it looks from a glance.

The string (and color in it) was not changed since last year:

![image](https://github.com/user-attachments/assets/b9acfd6b-b3c8-42fd-8920-53d7bfedd347)

So, the real issue is "color not inverted properly in imgui menus" (e.g. light_blue should become white when on dark blue background).
