### ISSUE TITLE
Cannot install an armored training dummy for some cryptic reason

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#75973]
### Describe the bug

It's greyed out even though i got all the requirements.

### Attach save file

[2024.08.21.zip](https://github.com/user-attachments/files/16750160/2024.08.21.zip)

### Steps to reproduce

* load the game
* `*`
* `/dumm`
* see you can't build it

### Expected behavior

Being able to build it.

### Screenshots

![](https://tinystash.undef.im/il/2hyUB7jjjbquu5hTUjzwvHSZuqWChniQsvK7MhCZ6Jqv6TYGTQe5NrJb6UVjJwqHZnn9vipa4jmpLD51R6RXUGCg.png)

### Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: 52d2b5f44b-dirty [64-bit]
- Graphics Version: Curses
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by HadeanLake** [comment]
summon @NetSysFire for moderating spam comment above

**Comment by l29ah** [comment]
seems like armored training dummy can't be installed on pavement or concrete, only on grass

**Comment by PatrikLundell** [comment]
It should be possible to address by adding a "pre_note" of e.g. "Needs diggable terrain to secure it" or something similar. You might also be able to infer such a requirement from the fact that you need a digging tool to install it, but an explicit message is better.

It's a general problem with construction: they can have fairly elaborate requirements that aren't communicated at all, so notes should probably be used a lot more frequently. A fair amount of room for notes would help to promote the provision of descriptions that cover more of the requirements.
Note that it's not possible to generate notes automatically in general, because requirements can involve code (sure, the code could be bundled with snippets, but then you'd end up with a bundle of disjointed snippets in many cases).
