### ISSUE TITLE
Spell casting menu will always choose the 1st option

### ISSUE THREAD

**Issue by Cddasurvivor** [CleverRaven/Cataclysm-DDA#76042]
### Describe the bug

In the most recent experimental as of this posting if you cast any spell on your spell list it will choose the spell at the top of the spell list over anything you select even if you make a custom hotkey for that spell.

### Attach save file

N/A

### Steps to reproduce

1)Create a character

2)Learn multiple spells such as learning Spider Climb.

3)You have the Spider Climb spell and the Magus Rune spell for being in the Magus school.

4)Your spell list is:

a)Magus Rune
b)Spider Climb

5)Use Spider Climb and it will cast Magus Rune.

6)Change the hotkey of Magus Run to a lower letter like z.

a)Spider Climb
z)Magus Rune

7)Cast Magus Rune and it will cast Spider Climb instead.

### Expected behavior

Should cast the spell you select but will always pick the spell highest on the list of spells.

### Screenshots

N/a

### Versions and configuration

Experimental 2024-8-30-0021

**Comment by JohnHenryEton** [comment]
My menu is not casting the first, but is casting wrong spells. 
One of two specific spells, actually, depending on what I'm trying to cast it either attempts to cast Nature's Bow or Dream Dagger.

**Comment by Molgador** [comment]
Downgrading my game version to before the 2024-08-29-0114 release fixed it for me, so I'd guess it has something to do with #75624

**Comment by Shibimon** [comment]
I have arround 20 spells and its changing ALL of them to other spells when clicking/cursor select/shortcut press is consistent in that run of the game and using that spell will allways cast the same other wrong one, but closing and opening the game seems to sometimes switch the wrong spells for other different wrong spells.
Not super sure if it has something to do with it but since the new style of menus is breaking parts of the game descriptions (like spells descriptions upon trying to learn them, or the time it will cost to butcher options something) has inconsistent behavior and sometimes i have to roll the mousewheel to be able to move the highlight select, my guess is its at least closely related to this.

**Comment by JohnHenryEton** [comment]
> Downgrading my game version to before the 2024-08-29-0114 release fixed it for me, so I'd guess it has something to do with #75624

This fixes the issue for me as well.

**Comment by Torres84f** [comment]
Yeah same thing happening to me

**Comment by ThePotatomancer** [comment]
Alright so I debugged and looked into it, the problem seems to be specifically in handle_action, the spell list returns a selected index, but the spell list in the ui with the hotkeys is sorted, while the one in handle_action that it references with get_spells is not. I will open a pr to fix it, probably by switching handle_action to use a new get_sorted_spells instead of get_spells
