### ISSUE TITLE
Bird Wings mutation does not make it so you "won't take fall damage under any circumstance"

### ISSUE THREAD

**Issue by Alithsko** [CleverRaven/Cataclysm-DDA#76099]
### Describe the bug

There's a dangerous description mistake in the Bird Wings mutation, it does not eliminate fall damage, it makes your fall damage about 40% lower, this mutation's description has not been updated to reflect this change which easily can cause older players and newer players alike to insta-kill a likely large investment character

### Attach save file

Happens on every save file easily

### Steps to reproduce

This is a description issue

### Expected behavior

Simply, the mutation's functionality is not as advertised in a very dangerous way

### Screenshots

The description 
![image](https://github.com/user-attachments/assets/513c3b9b-2cf9-42ee-895d-05e859f79bb1)
Warning Prompt says it "seems safe" falling would hurt badly, but their mutation would eliminate fall damage according to the description right?
![image](https://github.com/user-attachments/assets/f11d6539-b80b-49de-b848-af7d571489ed)
Immense damage, causing instant death due to obsolete information, or on death's door if more sturdy or lighter, but with broken legs and a dangerous location survival isn't looking good
![image](https://github.com/user-attachments/assets/090b2a1a-aac3-4a17-98f9-af5d66c0b9fd)
Debug to remove bird wings for comparison
![image](https://github.com/user-attachments/assets/f5265b4e-e811-439e-bc8d-6fc47370d2b1)
![image](https://github.com/user-attachments/assets/4b150a77-9a89-410c-946a-46a7e91101b1)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4780 (22H2)
- Game Version: 6b4c4d9 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    Bombastic Perks [bombastic_perks],
    Stats Through Kills [stats_through_kills],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by Night-Pryanik** [comment]
Original description of the mutation stated that you `will not take falling damage under any circumstances.` Gliding with wings PR (#70479) changed description to mention that `you can glide from ledges and will take less damage if you fall`. Limb stuff mod PR (#70721) changed description for vanilla version of mutation back to the original while moving the "glide from ledges" description to mod's version of the mutation. I'm not sure why it was done since "glide from ledges" description fits the vanilla version too - in vanilla you still can glide from edges and take less damage if you fall with this mutation.
