### ISSUE TITLE
Plugging a smart lamp into a grid/vehicle and turning it on causes segfault

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#76245]
### Describe the bug

As title, turning on a smart lamp while it is plugged into a grid or vehicle will cause segfault

### Attach save file

[TESTING-trimmed.tar.gz](https://github.com/user-attachments/files/16911053/TESTING-trimmed.tar.gz)

### Steps to reproduce

1. Get smart lamp
2. Get a vehicle or grid with power
3. Plug in the smart lamp
4. Turn on smart lamp
5. Segfault fun

### Expected behavior

No segfault when turning on a lamp. Lamp deserves to be lit! LAMP!

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4651 (22H2)
- Game Version: cdda-experimental-2024-09-04-0626 0c909b2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

[crash.log](https://github.com/user-attachments/files/16911049/crash.log)

**Comment by PatrikLundell** [comment]
/Confirmed

It blows up in item.cpp operation item::update_link_traits when trying to use `get_use("link_up")->get_actor_ptr()` when get_use returned a null pointer. The item in question is the turned on smart lamp.

The problem is caused by the operation being called with the turned on smart lamp, while the "link_up" action is defined on the turn off version.
Hacking the JSON to add "link_up" to the turned on version causes the game to say the lamp is turned on when turned on.

Electric carver has the action on both the off and on versions.
Same for:
- eink_tablet_pc(_on)
- laptop(_screen_lit)
- mp3(_on)
- smart_phone(_music/_flashlight)
- electric_lantern(_on)
- diving_flashlight_variable(_on_hi/_on_med/_on_low)
- heavy_flashlight(_on)
- lightstrip(_inactive)
- electric_masonrysaw_(on/off)
- large_space_heater(_on)
- small_space_heater(_on)
- radio(_on)
- elec_chainsaw_cord_(on/off)
- electric_blanket(_on)
i.e. all items having more than one version and the "link_up" action.

Given the precedents, it seems the action should be defined in all versions of the item. PR upcoming...
