### ISSUE TITLE
Sleep aids from adjacent tiles are not considered

### ISSUE THREAD

**Issue by failboat78** [CleverRaven/Cataclysm-DDA#76253]
### Describe the bug

The player benefits from certain items in the same tile when sleeping, e.g. teddy bear or quilt or blanket. 

However most beds have more than one tile - and only items in the same tile are considered. So the quilt in the adjacent tile seems to do nothing. This is especially obvious with the larger beds.

### Attach save file

N/A trivial

### Steps to reproduce

Sleep in a bed, but not in the same tile as items like blanket.

### Expected behavior

Items on the bed should contribute to sleeping utility.

Considering items in adjacent tiles is an obvious fix that would work in most cases except for the ludicrous room-sized beds in mansions.

### Versions and configuration

N/A

**Comment by CoroNaut** [comment]
I mean, any sleep aids you could ever use could just be on the same tile as where you decide to sleep. If the character wants to use a rolled up sleeping bag, a blanket, etc, they do. I'm not sure there's any reason to consider adjacent tiles. 

The 2x2 beds in most houses are meant for 2 people, and lay long-ways, each taking up 2 bed spaces. You can consider it a queen or king size bed. All tiles in the game are roughly considered to by 1 meter by 1 meter. and humans are often 2 meters tall, so they require 2 bed spaces. Would you want to steal that quilt from your partner on the other side of the bed? Since the character is only 1 tile, we just roleplay that they actually lay down and use the blanket on their side of the bed.

Given this, there isn't really a solid mechanic or roleplay reason to consider adjacent tiles.

**Comment by failboat78** [comment]
Yes you are right - it's very easy to just move the items to the tile and then sleep.

The problem is this is not obvious and will catch out new players.

**Comment by CoroNaut** [comment]
The only thing that blankets are even for is to help keep warm. If it is not freezing temperatures wherever you're sleeping, then sleeping on the floor with nothing is exactly the same as sleeping in bed with all the blankets/pillows and anything else you can think of. So adjacent tiles would be useless if a single blanket is the only thing that really affects your sleep.

Perhaps, alongside your request for sleep aids from adjacent tiles to be considered, you could advocate for those aids to actually have more of an effect. How about a mood buff upon waking up if you sleep comfortably? Or even a mood debuff by just sleeping on the floor for years without problems and even maybe giving you the 'bad back' trait or something. Until there is more mechanics here, I don't think there's an argument here.

**Comment by failboat78** [comment]
There is some kind of buff already I believe - the teddy bear increases comfort?

**Comment by CoroNaut** [comment]
Ahh, the plushies are a sleep aid as well as the pillow. My bad. I was wrong thinking that the only sleep aid was a blanket, even worse, the blanket isn't even a sleep aid lol. So that could definitely be updated. 

The code to get a sleep aid during sleep is here, it actually only checks to see if there is a single sleep aid before returning `true`. So perhaps another thing advocate for is to consider more sleep aids at any given time. As for your issue, It would be decently easy to expand the search to adjacent tiles here. 

https://github.com/CleverRaven/Cataclysm-DDA/blob/772b0e9b0d285fba27fa71b907c8f6de8d30964b/src/sleep.cpp#L77C1-L110C2

Also, a neat suggestion. Perhaps include a `+1` (negative) trait that requires 5+ sleep aids to allow the user to comfortably go to sleep, otherwise chronic nightmares and restless sleep or something.

**Comment by kevingranade** [comment]
There's no clear rationale for why a player would *expect* bedclothes to be applied if adjacent, or how it improves anything,  just put the bedclothes you want to use where you sleep.

On the contrary,  I'm concerned that if we start doing too much automatically players will start expecting it everywhere or possibly not even noticing why effects are kicking in because they're happening at a distance.
