### ISSUE TITLE
Blood draw kit gives error every time I draw toxic acidic blood from acidic zombie

### ISSUE THREAD

**Issue by CoroNaut** [CleverRaven/Cataclysm-DDA#76275]
### Describe the bug

As title, see picture for in-game error and debug.log for trace. It ends up working anyways, and the blood goes into the blood draw kit all the same. 

### Attach save file

[TESTINGTWO-trimmed.tar.gz](https://github.com/user-attachments/files/16920446/TESTINGTWO-trimmed.tar.gz)

### Steps to reproduce

1. Spawn blood draw kit
2. Spawn acidic zombie
3. Try to collect toxic acidic blood

### Expected behavior

There shouldn't be an error when collecting toxic acidic blood

### Screenshots

![image](https://github.com/user-attachments/assets/8d87531b-9aa5-4057-be03-5b66b6b96058)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4651 (22H2)
- Game Version: cdda-experimental-2024-09-07-0110 e398be1 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

[debug.log](https://github.com/user-attachments/files/16920452/debug.log)

**Comment by Night-Pryanik** [comment]
I think #67382 is the culprit.
Previously drawing blood from acidic zombie generated acidic blood, and then function exited.

This change
https://github.com/CleverRaven/Cataclysm-DDA/pull/67382/files#diff-99adfdaa9690fab771878f30cd5fe3b30b0d4e87f994e1d4176cf3331fcd906fL4646
made it so draw kit drew acidic blood and immediately after that it tried to put "default" blood in vacutainer, but can't do this because it can't mix default blood - `blood` in the error message - and acidic blood.
