### ISSUE TITLE
NPCs ignore sounds while they are outside the players FoV

### ISSUE THREAD

**Issue by dev-dsp** [CleverRaven/Cataclysm-DDA#76317]
### Describe the bug

I've noticed this for several weeks now, updating periodically. Not sure if it's a known bug.
It works perfectly at night. Just blow something up, wait 30 minutes, and then go to the nearest Z party. They suddenly start running towards the explosion.

### Attach save file

N/A

### Steps to reproduce

1. Go to the nearest city full of Zs
2. Attract just one Z so that he can see you
3. Move ~15-20 tiles away from the city
4. Kill the pulled Z with something loud
5. Walk around again away from the city (note some Zs still may go to the sound source) 
6. Wait until nobody is running towards you
7. Go back to the city
8. Suddenly a horde of Zs rushes (esp. funny when it's the night and they run past you) to the place from where you were shooting the first one

### Expected behavior

I expect that once they hear the sound, they rush to it, even if you don't see them.

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Gentoo; Description: Gentoo Linux; Release: 2.15; Codename: n/a; 
- Game Version: cdda-experimental-2024-09-08-2121 515ac7b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mind Over Matter [mindovermatter],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex]
]

**Comment by CoroNaut** [comment]
I believe you are giving the behavior of the reality bubble. It is a limited area around the player in which zombies and npc's are active. Outside the reality bubble, the zombies are there, just not actually being animated or interactive. When the explosion creates the loud noise, all the zombies in the reality bubble can hear it. When you move away fast, a lot of zombies would simply leave the reality bubble and go dormant, but keep their memory. When you move back, they activate and continue walking towards the explosion.

The reality bubble acting this way is intended and intentional. For every tile that we extend the reality bubble, the actual tiles that are calculated go up, which means its harder on the CPU. This isn't configurable.

**Comment by PatrikLundell** [comment]
The size of the reality bubble is nominally a 60 tile radius around the PC. "Nominally" because terrain is loaded in 12 * 12 tile chunks, and some things depend on whether the terrain is loaded, while others use a fixed radius. This means the bubble may reach up to 71 tiles in some directions at times and for some purposes.

**Comment by dev-dsp** [comment]
Indeed doesn't look like a bug, probably just me changed play style /shrug.
