### ISSUE TITLE
Problem with removing automatically generated zone

### ISSUE THREAD

**Issue by AmmoMSN** [CleverRaven/Cataclysm-DDA#76401]
### Describe the bug

I talk with npc and press "build camp here". It is automatically generate 10+ zones in my main home
automatically generated zone have markers which are bothering me  
I cannot manage automatically generated zones in zone manager(Y)
I try to forget/remove camp it is not help, markers of automatically generated zones still active, I cannot hide it.

How to remove automatically generated zone from my home?

### Attach save file

[Zugdidi-trimmed.tar.gz](https://github.com/user-attachments/files/16989835/Zugdidi-trimmed.tar.gz)

### Steps to reproduce

read description

### Expected behavior

How to remove automatically generated zone from my home?

### Versions and configuration

Win 10
v. 5d5ef55
Rus lang

**Comment by PatrikLundell** [comment]
I don't understand Russian, and thus can not determine which of the zones might be generated automatically and which may be preexisting. Last time I made a base I was prompted to generate zones, although I've had erroneously placed auto generated companion investigation zones placed in the Livestock expansion in the past.

I HAVE had similar issues with my own zone indicators appearing in the wrong location at some point, probably after leaving and returning, but have not reported the issue. I suspect it has to do with rotation not being handled properly somewhere, and it could indeed be in conjunction with the tile being designated as a base.

Anyway, I did find a way to get rid of improperly placed zone indications (i.e. ones in locations other than the zones they were supposedly indicators for):
- Find what the character for the zone you want to erase indicators for is (.e. by creating zones and toggle them until you find a match).
- Create a zone of that type covering all the indicators of that type you want to get rid of.
- Toggle the zone on and off. Since there's no other actual zone connected to the characters, this will remove the characters.
- Remove the zone.
- Repeat the above for each offending letter.
