### ISSUE TITLE
Spike Strips 

### ISSUE THREAD

**Issue by DukePaulAtreid3s** [CleverRaven/Cataclysm-DDA#76485]
### Is your feature request related to a problem? Please describe.

Currently @GuardianDll is in the process of removing Riot Turrets from police roadblocks. (#76467 ) I propose that they be replaced with spike strips.

### Solution you would like.

Spike strips are used by police in the real world, to either slowly deflate or immediately pop a suspects tires during a chase. I believe they should be a furniture/terrain that destroy tires when driven across, and otherwise deal some damage to zeds that walk on them.

### Additional context

https://en.m.wikipedia.org/wiki/Spike_strip

**Comment by CoroNaut** [comment]
As an alternative to it being a construction, I'm wondering if it could be made like how tents are. Perhaps activating a spike strip item would span it 10 tiles in front of the player in a direction, and interacting with it would roll it back up.

**Comment by GuardianDll** [comment]
i think it's pretty okay to have them as traps yes
write a report if you find what is lacking to implement them

**Comment by kevingranade** [comment]
I do think spike strips would be usable as a fairly ineffective trap, but I don't expect police to have them deployed anywhere in notable numbers, and definitely not at roadblocks.

**Comment by DukePaulAtreid3s** [comment]
> I do think spike strips would be usable as a fairly ineffective trap, but I don't expect police to have them deployed anywhere in notable numbers, and definitely not at roadblocks.

Why not at roadblocks? They are designed specifically for the purpose of stopping vehicles.

**Comment by XygenSS** [comment]
I think they're deployed only when necessary (like during a car chase) and recovered after use to prevent collateral damage.

You could find them in roadblocks just in undeployed form in a police car. Or you could find them in police station armories.

**Comment by CoroNaut** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/Lore/lore-background.md#year-0-the-current-irl-year-1
> January: The Blob reaches satisfactory global-level groundwater saturation and makes the decision to commence the concentration and replication phase. For the next few weeks there is a gradual rise in violent crime, and occasional reports of strange mutations and weird animal sightings in the wild, but little attention is paid.

> February: First reports of people rising from the dead, XEDRA immediately makes correct assumptions about what's up as they've been experimenting on the Blob and recognize its effects. The US government assumes it's a controllable outbreak and tries to squelch reports to avoid classified information getting out. A very successful counterintelligence campaign makes YouTube reports of zombies and ferals into a high-quality prank that has caught on among the meme community. After all, any time a video comes out, an undoctored version surfaces not long after.

> March: Nations that are already unstable start to see riots, as passive Blob infection causes people to become more violent - some outright feral. A few small wars break out. Thanks to word spreading via the internet, people around the world generally realize something is amiss, but the US government and other allied international intelligence agencies continue to work hard on squashing it. At first it's not hard, because the places it's happening are places where the tipping point was reached sooner.

> April 10: A national state of emergency in the US is finally declared as the government realizes control is impossible. At this point riots are widespread and the police forces are unable to keep it under control. Military forces are deployed but the Blob psychosis means their response is irrationally violent and they do not follow the correct protocol. On top of that, those less affected by the Blob psychosis are simply overwhelmed by masses of rioters and with hordes of now risen undead mixed in.
Taken from `doc/Lore/lore-background.md`

> April 30: Canonical date of game start.

This outlines that riots were breaking out city-wide as ferals and other creatures started to come out into the light. It was the response of the government to keep this contained in cities that had a massive outbreak. Riot turrets to keep those infected citizens inside the city would definitely be right choice to contain the outbreak. If we get rid of those, it is perfectly reasonable to put spike strips down to stop potentially infected but still sane humans from escaping the containment. I realize riot turrets would not be widely available at all, but not putting spike strips down would just be deliberate neglect...

**Comment by GuardianDll** [comment]
You missed that these are not got deleted, they were replaced by policemans

**Comment by CoroNaut** [comment]
Yes they are being replaced by ferals, but they are so much less effective than a turret that it can just be treated like any other zombie horde. If I approach riot turrets in my armored motorbike in full survivor gear, medium-armored, I'd be deathly afraid of turrets and go around. Ferals are just another walk in the park. The difficulty is almost completely wiped, which is fine, but spike strips add to the realism.

My main point was for spike strips being placed. it just doesn't make sense that they wouldn't be there. I'd believe they are available at almost every police station besides very small towns and it just wouldn't make sense to not place them down. Their whole thing is containment until it becomes clear that containment was impossible from the beginning. Heck, there are military roadblock mine fields at bridges, those are a HEAVY deterrent. But a spike strip at a regular police roadblock? It just seems reasonable.

**Comment by kevingranade** [comment]
Please cite a source showing that police use spike strips at roadblocks.

My issue is that this does not sound like a use case for spike strips, let me know if you have sources that say otherwise.

**Comment by CoroNaut** [comment]
https://globalnews.ca/news/10603184/creston-rcmp-arrest-roadblocks-spike-belts/
https://thenelsondaily.com/2024/07/man-in-custody-following-high-speed-chase-near-creston-rcmp/
They tried to get the guy with a spike strip initially, but it failed. They then set up a few roadblocks with spike strips in front. He hit the spike strip while approaching the roadblock, and they quickly surrounded him.
From second link:
> With roadblocks already in place, highway traffic was stopped in both directions as spike belts were deployed.

> RCMP said the suspect approached one of the roadblocks, drove over a spike belt, and continued driving a short distance before his vehicle was disabled near West Creston Road and Highway 3.

> RCMP said the suspect then fled into the nearby marshlands, where, after an hours long search, the suspect was brought into custody without further incident.

The issue is a suggestion/discussion for an alternative to riot turrets at roadblocks. its not like adding spike strips would be a terrible item to add to the game.. Its a niche fun role-play thing, and its not like the survivor can't just replace their tires if they didn't see the roadblock before hitting the spike strips. Not to mention laughing at some zombies that step on it. Also, armored wheels could be immune, making them useless anyways. But anyways, I like the idea. If it doesn't get added, oh well.

**Comment by kevingranade** [comment]
That's again,  "targeted effort to stop one vehicle", not,  "we have a roadblock to halt all traffic and we put spike strips in front of it".

> The issue is a suggestion/discussion for an alternative to riot turrets at roadblocks.

The issue here is they aren't really even targeting vehicles, everything is anti-personnel and deterrence based. if you want an alternative to riot turrets, you need something they would actually use,  not do something random. 

> Its a niche fun role-play thing

Ig it's not something that would really happen it detracts from the world instead of adding to it.

**Comment by CoroNaut** [comment]
> it's not something that would really happen. It detracts from the world instead of adding to it.

We don't have an IRL example of a worldwide zombie outbreak, so I couldn't say anything for certain. Its just that with the lore saying that they wanted containment. People are losing their minds and rioting and probably trying to escape the city by any means necessary for their own survival... Sure, it may not be a full-time deployed spike strip, but for the instance where a car is barreling down the road at high speed? I can't imagine they would leave a gaping hole in their roadblock where any vehicle fast enough could just zoom by. Nobody is supposed to get through a roadblock except for people without the proper clearance anyway. The people who want to pass could just radio in to the roadblock, and they would just pick it back up, or just approach slow.

> The issue here is they aren't really even targeting vehicles, everything is anti-personnel and deterrence based. if you want an alternative to riot turrets, you need something they would actually use, not do something random.

I would hardly say that keeping a spike strip deployed while the officers kept up with the radio and their orders is something random. As an alternative, I could suggest we bring back the police robots or taser manhacks instead since we are looking for an anti-personnel solution. A police robot that could just sit at a roadblock and seek escapees in the forest would definitely be useful. A taser manhack even more so to actively approach and disable people walking up. I wouldn't expect a citizen to just walk down the road towards a police roadblock knowing full well that they want to keep a containment on the city. Therefore, a citizen taking a vehicle and just driving past quick would be ideal, sure they may get pitted down the road, but they could then escape on foot. You still got much farther than just waltzing up to the roadblock with a molotov or gun.

**Comment by kevingranade** [comment]
I disagree with both spike strips making sense to place at roadblocks and with the concept that the removed turrets need to be replaced with anything in particular.  There's a roadblock, there are ferals and/or zombies wandering around, that's fine for the moment and we don't need a reflexive "replace A with B" response.

What needs to happen to make this consistent is design work, what are the roadblocks for, who is placing them (local police, national guard, sheriffs, citizens?), and what is the normal procedure for that group accomplishing that task.

**Comment by IdleSol** [comment]
![pict1](https://github.com/user-attachments/assets/28264c07-377f-4ef5-bae3-7a76a8814a19)

mx_bandits_block
https://github.com/CleverRaven/Cataclysm-DDA/blob/7ee3ce7282067c3f81b1684f9db94b0d67c6a52e/data/json/mapgen/map_extras/bandits_block.json#L171
