### ISSUE TITLE
[Martial Arts Mastery] Getting insane damage numbers randomly

### ISSUE THREAD

**Issue by Fox-Ball** [CleverRaven/Cataclysm-DDA#76533]
### Describe the bug

Not sure what is happening I will randomly do damage numbers up words of 100x what it normally would be, not very often but often enough it is noticeable. 

### Attach save file

[Save + Mods.zip](https://github.com/user-attachments/files/17048916/Save.%2B.Mods.zip)
I have cata++ and Arcana as well, they don't come packed with CDDA so just drop the folders in the "mod" folder into you own "mod" folder. Can just delete them when you are done with the save.

### Steps to reproduce

Warp down from the sky island and attack things it is bound to happen.

### Expected behavior

Not to be doing upwards of 100x times the damage I should be doing, I can maybe understand 3x-4x but 100x, crazy.

### Screenshots

![Screenshot 2024-09-18 145346](https://github.com/user-attachments/assets/3473ae4d-45ee-4d4d-bf4f-dd4254c0ea49)

### Versions and configuration

cdda-windows-tiles-sounds-x64-msvc-2024-09-18-0731

Look at screenshots section for list of mods. I doubt it is one of the other mods since none of them should be touching anything related to your martial arts mod.

**Comment by GuardianDll** [comment]
Do you just have `Execution` perk?

**Comment by Fox-Ball** [comment]
> Do you just have `Execution` perk?

I do not have either of the execution perks.

**Comment by Molgador** [comment]
![insight](https://github.com/user-attachments/assets/1254aecf-6d9e-44e0-895a-bc7c2226e588)

My guess lol, I think I saw this hit close to 100000 at one point

**Comment by John-Candlebury** [comment]
I gave this a test run to check it out, I got a lot of errors realted to loading ARCANA and its enchantment effects. There might be some enchantment in the mod that further enhances melee damage and is making the numbers go wild consistently.

Otherwise I think this is just the Psychic Sea doing what is supposed to. I'm surprised you can consistently get thousands of stacks of insight without attacking anything, although the culprit here is probably "Sixth sense" granting you insight on enemies you cant see and fight.

I'll look into reducing the range in which insight accumulates and capping the amount of insight Sixth Sense can grant as a fix.
