### ISSUE TITLE
The Implementation of Hub-01’s Nanofabricator

### ISSUE THREAD

**Issue by DukePaulAtreid3s** [CleverRaven/Cataclysm-DDA#76550]
### Is your feature request related to a problem? Please describe.

As a big project to work on throughout the coming months; I want to do something actually worthwhile, which is allowing the player to use Nanofabricator Templates through the Hub intercom. 

### Solution you would like.

This is a discussion about the implementation, balancing, and gatekeeping of this ability from the player. Functionally, it should be able to be implemented in a similar manner to the current process of giving the Hub items to reverse engineer, but I am much more concerned about how/when this function would become available to the player.

### Describe alternatives you have considered.

Not doing this, or just adding a Nanofabricator to the bottom of the Hub.

### Additional context

Current gatekeeping idea is that the player must A.) have completed Light Retrieval, and B.) Have a high rep with the Hub-01 Ancillary. 
If possible, I would prefer that each template only has to be given to the Hub once, then the player can commission them similarly to armor. This would require Nanomaterials and Exchange Coins, and would be completed at the speed of a Nanofabricator.

**Comment by PatrikLundell** [comment]
The whole schtick with the template is that it's single use. It's unbalanced that you'd be able to effectively use it an unlimited number of times only when applied in one specific fashion (and through one specific faction, locking out access to this avenue to those who ally to opposing faction(s)).
I'd say it's good enough to get guaranteed and comparatively easy access to a nano fabricator through this path. If you want the templates to no longer be locked to a single use it should be unlocked for all usages (leaving only the rare materials to be a production bottleneck).
Note that I won't object to a fixed number of missions from this (or some other suitable, if there are any) faction that would yield a limited amount of nano materials and/or templates. It's the locked in unlocking that bothers me, not access to limited advantages.

A faction able to build a nano fabricator is probably able to modify it to record the fabrication steps (thus bypassing the single use restriction and violating EULA's and probably a bunch of laws nobody is enforcing anymore), so it makes sense from a technological point of view, but it doesn't work well from a game balance point of view.

**Comment by DukePaulAtreid3s** [comment]
> None of the extant factions are *building* a nano-fabricator or modifying it heavily enough to bypass the single-use limits.
> 
> Given enough interest and resources (unlikely), Balthazar or the exodii might crack the DRM directly on a case-by-case basis.

So, just so I am understanding correctly, I inferred from the Light Retrieval mission that Hub-01 has the technology to either copy or reuse templates, as once they decode the UHMWPE routines, they can make as much of that material as they want. Is this true, or did I misunderstand something?

**Comment by PatrikLundell** [comment]
They want a template for some reason, but I interpret this to be to investigate the product, rather than the template, and later provide access to some items. Thus, it would be reverse engineering rather than template copying or reuse, in my interpretation. Once they've reverse engineered the material they can presumably create their own reusable templates for items made out of that material. That doesn't necessarily carry over to templates using other materials.

**Comment by IdleSol** [comment]
It sounds like:

1. Quest to find the nanofabricator (gives a marker on the target)
2. Clear the location
3. Deliver our specialists
4. Guard (connect defense mode mod?)
5. Return the specialists along with the disassembled nanofabricator ( 5 seats + 1500 liters of luggage?, i.e. create transport for the mission)
6. Get the use of the nanofabricator. Materials and templates are not included in the contract.

**Comment by kevingranade** [comment]
Hub can NOT reverse engineer, copy, or otherwise bypass the need to retrieve one template per item produced. That's a hard line.

The hub interaction with the nanofabricator would be nothing but operating it on your behalf and having interest in buying some templates.

Practically speaking the benefit of them operating it for you is changing the location where you pick up the items, and potentially allowing you access to use templates or materials they acquired elsewhere. We might akso maje operating the nanofabricator in situ mire complex, which would increase the relative benefit of hub handling it.

**Comment by John-Candlebury** [comment]
I just want to warn that the nanofabricator lab is the subject of the next big Hub 01 quest and work you do on that is likely to get reverted. 

I would greatly appreciate help in other aspects of the faction.
