### ISSUE TITLE
Fire Hardened Wooden Spear and Normal Have Same Stats

### ISSUE THREAD

**Issue by LowIncomeNeighborhood** [CleverRaven/Cataclysm-DDA#76715]
### Describe the bug

Fire hardened spears are noteably for durable and effective than one you whittled. I imagine this is just a bug.

### Attach save file

[Albany-trimmed.tar.gz](https://github.com/user-attachments/files/17176817/Albany-trimmed.tar.gz)

### Steps to reproduce

1. Try a wooden spear
2. Try a fire hardened one
3. Same

### Expected behavior

The Fire-Hardened should be a marked improvement

### Screenshots

![image](https://github.com/user-attachments/assets/254bf69b-8e9a-4c63-abeb-b662b821e842)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.4169 (23H2)
- Game Version: cdda-experimental-2024-09-27-2210 ef6b53a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by Vaskritaya** [comment]
The distinction seems to have been made in #61482. Quoting the included design doc/summary:

> Note about untreated wooden spears: No longer require fire hardening (but still allow it for faster crafting as an option). Fire hardening wooden spears doesn't really increase durably or damage, evidence suggests it was only done to take a 2 hour job and get it done in about 45 minutes instead. Source: https://arstechnica.com/science/2016/05/turns-out-fire-hardened-spears-arent-as-badass-as-we-thought/
This does mean a wooden spear will be craftable right out of the gate with a cutting tool and make a solid starter weapon if you’re willing to grind a few levels in fabrication and whittle the spear for two hours.

It seems the identical stats are intentional, as the argument is that fire-hardening has pros and cons that don't result in a measurably improved spear beyond the associated production time.

**Comment by Holli-Git** [comment]
This is on purpose, the difference between the two is in the crafting times, not the stats.
