### ISSUE TITLE
Gun shots should hit easily even without aiming

### ISSUE THREAD

**Issue by martinrhan** [CleverRaven/Cataclysm-DDA#76779]
### Is your feature request related to a problem? Please describe.

Imagine a zombie is very close to you, you draw your gun, what will you do next? You probably just shoot without aiming and it is unlikely to miss. However, the currently mechanism of calculating hit chance is not sensible. You will miss every single shot if you don't aim, even if the zombie is very near to you.

### Solution you would like.

We should modify the calculation.

**Comment by PGR-14** [comment]
It's been bugging me for quite some time too. The only way for you to miss those shots is if you were using a pepperbox revolver. The benefit/debuff from distance isn't too realistic.

**Comment by PatrikLundell** [comment]
The problem is that this "point blank will almost always hit" logic only applies to targets taking no countering actions. Zombies and animals coming straight at you would probably be fairly easy to hit, but a human seeing the draw is another issue. Thus, you'd need separate logic for ignorant and thinking targets (would a mi-go realize it's a weapon?...).

**Comment by RedMisao** [comment]
Very close is what, one meter away? Two meters? Are those translating into one, two tiles away ingame?
If you mean from point blank to one meter away, then I agree. Hit chance should drastically decrease beyond that point on.
However (and this is a big if), this is assuming the character is already facing the target, which isn't represented at the moment.

**Comment by Zireael07** [comment]
@RedMisao Tiles are a vague size, around a meter to meter and a half or so

**Comment by kevingranade** [comment]
Selecting a target takes *literally* no time since you might want to use the UI to look at your options before actually aiming and firing at a target.  The situation you describe where you draw/wield your gun then hit f -> f to fire at the selected target is you drawing the gun and pulling the trigger the instant it clears the holster, not even pointing it at your target. *Even then* the way the system is written you sometimes hit anyway.

If you want "quick draw but at least attempting to hit the target" you're going to want to either hit '.' once to spend a fraction of a second pointing your gun at your target, or hit 'a' for the *minimal* amount of aiming before firing, both take a small fraction of a second for most characters and guns.

A side note is even at extreme close range, pointing a gun vaguely in the direction of an opponent and pulling the trigger is still a ridiculous thing to do since you don't want to just graze the target, you want a good center of mass hit, so you're not aiming for "a half square meter cross section", you're actually aiming for a several square inch area in the center of your target's chest.
