### ISSUE TITLE
[CR] Tag system for Overmap terrain?

### ISSUE THREAD

**Issue by vache** [CleverRaven/Cataclysm-DDA#7681]
Currently, there is "is_river" and "is_road" and "check_ot_type" and "check_ot_type_road" and all sorts of instances of that paradigm.  A tag system could alleviate some of these troubles, a bridge could have the "ROAD" and "RIVER" tags so they could apply in both situations.  Railroad crossings could have the "ROAD" and "RAIL" tags similarly.  Buildings with built in parking lots/road connections (like hotels, schools, etc) could have the "ROAD" tag so that roads actually connect to them instead of ending in a cul-de-sac or sidewalk.

Thoughts?
##

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.

**Comment by Night-Pryanik** [comment]
Good idea indeed, but the discussion is stalled for years, so closing for now.
