### ISSUE TITLE
crafting formula logic 

### ISSUE THREAD

**Issue by martinrhan** [CleverRaven/Cataclysm-DDA#76942]
### Is your feature request related to a problem? Please describe.

Currently, many recipe are like 
8 ItemA or 8 ItemB
To make the item of this recipe, I must use ItemA only or ItemB only. I cannot use mixure of both such as 5 ItemA and 3 ItemB.

### Solution you would like.

Change all recipes like this to
8 (ItemA or ItemB)

**Comment by PatrikLundell** [comment]
The problem is that it's tricky to do in the general situation. Sure, it's not too hard to imagining taking 3 of A and 5 of B to get 8 of Whatever, but it gets a lot trickier when it's 3 of A or 8 of B, as there's not even an integer ratio between them, so there is no mix that can be done without either losses or gains.

**Comment by RenechCDDA** [comment]
This isn't actionable unless you have some idea for how it should work.

**Comment by IdleSol** [comment]
I have an idea. But it would require changes to the code. It could potentially be beneficial. It may not. I lack the knowledge to evaluate. (I'm talking about the old idea of time dependence on the tools used).

When you select a recipe, you open a new window. The window is divided into two parts.

**Part 1**. Refers to the required tools. It is divided into additional parts, depending on the tool groups. And it displays all the tools. The player can select the required tools. Optional: for tools with charges, select the amount of charge to be used.

The game should check that at least 1 instrument is selected in all subgroups. And for charges, check that the required number is selected. (Or leave it as it is now, when you can start cooking on an electric stove, then on a fire, and then on a gas stove.)

**Part 2**. Refers to materials. We divide it into parts again. And let the player choose what he will use. But be sure to check that the correct amount is chosen.

In cases where the recipe specifies different amounts (10 regular threads or 3 Kevlar threads). We calculate the ratio with rounding up, but not more than specified. From the example above, the Kevlar thread comes in at 3.3 regular threads. So 1 Kevlar thread will replace 4 regular threads, two Kevlar threads will replace 7, and 3 will replace 10.

If we add color selection: red or green, as well as we will dynamically change the required amount depending on the selected. Then the player will be able to orient what the game wants from him. (Or we set conversion formulas and check all recipes for their compliance).

I guess a more specific example is needed? Soldering iron https://cdda-guide.nornagon.net/item/soldering_iron
https://github.com/CleverRaven/Cataclysm-DDA/blob/6153d6042f0159352fede6440cff99e42e2dd6d1/data/json/recipes/tools/tools_electronic.json#L407-L415

In the upper half of the window responsible for tools. Create two drop-down lists.
- First list: tools with CUT quality
- Second list: tools with SCREW quality

The list lists all tools of suitable quality that are nearby.

Optionally, tools with quality higher and time modifier 0.9 (for example).
Optionally, tools with quality lower and a time modifier of 1.2 and a failure chance modifier of x2.

Display time and chance of failure in the window header or at the top. Dynamically change from the selection.

But I would put this in a separate discussion... if someone will take up the implementation. My personal opinion: not all tools with better quality should speed up production. 

The player should select the required tool. For visualization: the `d`rop menu of things.

The part responsible for materials will be located below.
Again we divide it into drop-down lists. In this case for 5 pieces. With the last three everything is simple, there is only one type of material. Optionally make an automatic selection.

Let's look at the first line with the required materials: `[ [ "e_scrap", 2 ], [ "glowplug", 1 ] ]`

We have two positions with different quantities. We need 100% of the material. For each item we calculate the weight of one unit.

The player must choose materials and their quantity so that the sum is greater than or equal to 100%. Let's leave him the possibility to choose more than necessary. That is, we will not evaluate the reasonableness of the player's choice. If he uses 10 instead of 1 piece, that's his problem. (Because I don't know of a simple way to evaluate the reasonableness of the choice. After all, if two different materials are used, you can get 116.6% (2 out of 3 + 1 out of 2 = 90% + 50%))

The player chooses a material and a quantity. The game counts the sum of the weights and indicates the percentages for that item in the header of the drop-down list.

Going back to the example. The player has chosen an electronic component of 1 piece. Game: 50%. Player chose 2 components game: 100%. Player chose both items, game: 200%.

Redundancy can reduce the chance of failure or offset the requirement of additional materials in the event of failure. That is, those 200% could remove the requirements of an additional component if a failure occurs and the game specifies them as necessary (I'm not versed in this mechanic, so I don't know how it works).

After selecting all components, you need to click confirm or cancel. Or press `enter` or `esc`.

**Comment by PatrikLundell** [comment]
Selecting exactly which tools to use would not only introduce additional tedium, but would also introduce significant problems for the current code, as well as removal of those tools from parallel use,
The current selection process doesn't allow for specification of which matching item (tool or material) to use, but only what item it is. The later execution phase then performs a similar search to the one used to present materials to be selected, and then removes items as they're found by the search. A change to specify exactly what to use would likely require a rework of the whole complex to use item_location references rather than items (or if it is item ids).
In addition to that, you'd potentially get a huge churn when you have to select 2 thread from this location, 1 from this, etc.
And finally you'd have to change the in-process items to incorporate both the tools used, and keep track of where they were taken from, as well as code to return them after use (and handling of the possibility that they can't be returned, because the location they came from is no longer available or in range).

IF you were to handle material usage of dissimilar rates, you should always "round" up, or you'd create something out of nothing. At least for larger stuff, you'd probably want to introduce a system to generate left overs as by-products. That would likely require new JSON structure work and an extensive effort to fill that out, unless you can somehow reuse deconstruction data.

IF you were to allow for specification of extra components for usage in case of failures, you'd again need to introduce new systems to consume extras from within the in-progress item before resorting to asking (which is resolved automatically for companion crafting), as well as a way to return the leftovers (and you'd introduce churn if you don't try to return it to its original location(s), but as a pile beside the product).

Usage of better tools resulting in faster or less strenuous work is desirable, but this problem hasn't been solved. The current work around is separate recipes.
When it comes to tools qualities, I don't think higher quality than required should matter. A possible future change might be to allow for some inferior quality tools to be used at the cost of increased time, but that would, again, require changes to the system.

Note that it has been proposed as a long term goal to allow for recipes to be multi stage to better capture aspects such as a e.g. powered saw only being used for certain stages, and thus only require power for the time of those stages rather than the whole time, the amount of effort required for different stages varying (including if it's possible to select between powered and unpowered tools stage recipe parts), and idle time (such as waiting for bread to rise or bake).
I'm not aware of any progress being made in this direction, however.
