### ISSUE TITLE
Innawood now unplayable because of inability to cure tainted hide

### ISSUE THREAD

**Issue by KHeket** [CleverRaven/Cataclysm-DDA#76979]
### Is your feature request related to a problem? Please describe.

Now its impossible to make leather items in time in Innawood because of #76891 . After some time of playing - there will spawn in most cases only zombie animals, and regular, alive animals with hides became extremely rare, and drop very low amount of hides

### Solution you would like.

Few ideas to solution
1) Make tainted hides cureable again. The reason of the update was "animals are rotten", but zombie(rotten) moose, zombie(rotten) deers and other zombie animals are fast and stronger, than there alive analogs. So this mean, that that they are not worse, than alive analogs, so they are not rotten. Zombies in game are not the classic, rotten zombies from most of zombies universe, its just rebuilded dead bodies by blob, so they are alive monsters, like in Dead Space. They also dying in most cases from bleeding, so they have have heartbeat and circulation of the blood, and they also are detected by infrared glasses, so they have body temperature, so they are similar to alive necromorphs from Dead space. Zombies also have ability to  regenerate, so they will heal fast any damages of their hides
2) Make alive animals more regular, because they are very rare in early game, and extremely rare in late game. And also in this case make zombie animals more slower and weaker, if they are "rotten". Rotten animal, with rotten skin, rotten muscles, rotten bones and bone marrow, rotten sinews and other organs cant be more stronger, than its live variant. And also remove the regeneration from zombies, it they are rotting
3) Or make curing of tainted hides harder because of damages, or increase the required amount of tainted hides to craft cured hide because of damage of tainted hides, because character need to find undamaged piece 

### Describe alternatives you have considered.

Leave all as it is and make Innawood unplayable

**Comment by Holli-Git** [comment]
This is not an appropriate solution to the issue. Tainted hide would be heavily damaged, not just rotten, but malformed, uneven, damaged with cuts, etc. This issue is a bit emotional, innawoods isn't "unplayable", it just adds an extra challenge to it. Reacting like this makes it more likely for someone to not take this seriously. If there is an issue with innawoods and zombie animals, I suspect it to lie with the lore of innawoods and if zombie animals should exist in it.

**Comment by Maleclypse** [comment]
There are a ton of solutions to this problem that range from: Tame animals fast enough so they breed.  Create a faction camp and use it's hunting function. Make changes in Innawoods spawn groups that make them appropriate to innawoods but it is neither unplayable nor something that needs to be reverted which is why this issue was closed.  Wild hyperbole is not helpful in issues.

**Comment by Zireael07** [comment]
I suspect the best way to act would be to change Innawoods spawn groups
