### ISSUE TITLE
Super slow sleeping near the furniture

### ISSUE THREAD

**Issue by KHeket** [CleverRaven/Cataclysm-DDA#77026]
### Describe the bug

If you sleep near the table/anvil and other furniture - the game will go super slow
I think, its because character have lying position
![image](https://github.com/user-attachments/assets/a6c75261-4a30-4fe7-bda9-0865462fbadb)
And game checking every turn character 

### Attach save file

[1-trimmed.tar.gz](https://github.com/user-attachments/files/17358121/1-trimmed.tar.gz)

### Steps to reproduce

Load save
Sleep in shelter, check, that speed of sleeping is fast
Alt+f4
Load save again
Move table right to the shelter, like at screenshot below
Sleep
See slow down of sleeping, and you will need to wait for few minutes

### Expected behavior

Normal speed of sleep everytime

### Screenshots

lags
![image](https://github.com/user-attachments/assets/7e8e2404-b7f2-4ccd-b251-b970be664ddc)

After I move table 1 tile away - the sleeping going by normal fast time
![image](https://github.com/user-attachments/assets/b1c32905-834b-42d8-a05d-793f70242c9b)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.5011 (22H2)
- Game Version: cdda-experimental-2024-10-11-2113 405e875 [64-bit]
- Graphics Version: Tiles
- Game Language: Русский <color_dark_gray>(92.2%)</color> [ru]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Innawood [innawood]
]

**Comment by osuphobia** [comment]
#73552 might be relevant?

**Comment by sparr** [comment]
Loading your save does not give me the game state from your screenshots. I tried with and without your config. I see a big hollow square of pit, and can't drag the table to the left of the shelter because of the pit.

If I drag the table to the north of the shelter, I don't see any difference in sleeping speed, it seems normally fast with and without moving the table.

![image](https://github.com/user-attachments/assets/ddf45457-bb5c-40ad-a507-99aa38445298)

**Comment by KHeket** [comment]
> If I drag the table to the north of the shelter, I don't see any difference in sleeping speed, it seems normally fast with and without moving the table.

I have performance issue 
![image](https://github.com/user-attachments/assets/cd3a573d-1053-4a74-91a0-061c6d645ff1)
![image](https://github.com/user-attachments/assets/1dbaa089-5f63-4f6a-8d1a-8c13ca9ed08c)

**Comment by PatrikLundell** [comment]
When I confirmed the issue I too failed to move the table to the west of the shelter, and ended up dragging it to the north of it instead, which was sufficient to cause the issue to appear. That was done using the master code as it stood at that time (freshly downloaded and compiled).

However, if some people see it and some don't, we might be faced with an OS/compiler issue. The original report, as well as my confirmation, was using Windows and MSVC (I assume the packaged experimentals for Windows are using MSVC, anyway).

**Comment by sparr** [comment]
I should have specified. I am using clang on Linux. Another user on Discord who is able to reproduce #73552 is using MSVC.

**Comment by PatrikLundell** [comment]
I was trying to profile it, and it seems the time is largely spent in calls to different interpretations of the template cast_horizontal_zlight_segment, in which the time largely is spent in `expf`, whatever that is (trying to expand that asks for an assembly file).
The largest user within the template is the line `last_intensity = calc( numerator, this_span->cumulative_value, dist );` which is largely due to it being in a loop over distances within a loop over distance of the outer loop.
About 70% of the time was spent in the cast_zlight template (shadowcasting.cpp), which is the caller of the template interpretations above.

I don't know if anyone can draw any useful conclusions of the above, though.
