### ISSUE TITLE
Can't craft 00 Shoot, reloaded.

### ISSUE THREAD

**Issue by LeSHi4** [CleverRaven/Cataclysm-DDA#77136]
### Describe the bug

I have all tools for craft "00 Shoot, reloaded" but can't craft it.
(I see this bug very long time maybe half of year)

### Attach save file

[TeST.zip](https://github.com/user-attachments/files/17440040/TeST.zip)

### Steps to reproduce

1.) Open craft menu &;
2.) Go to ammo;
3.) Try to create 00 shot, reloaded.

### Expected behavior

I expect to create ammo :)

### Screenshots

![00_ammo](https://github.com/user-attachments/assets/f79913c7-e9b1-47a3-9180-8b9870b7c7dd)

### Versions and configuration

- OS: Windows 11 24H2;
- Game Version: 79b8ed9 - x64;
- Graphics version: Tiles, sound;
- Language: English, Russian.

**Comment by LeSHi4** [comment]
Sorry it's my firs bug report extra information:
Game 0 x64 version

**Comment by RenechCDDA** [comment]
Somehow, ~~Palpatine~~ #65679 returned.....

**Comment by RenechCDDA** [comment]
It's the "Any_water" requirement in the shot forming group. I am looking for a better way to prevent this in the future, previous attempts clearly did not work

**Comment by osuphobia** [comment]
> It's the "Any_water" requirement in the shot forming group. I am looking for a better way to prevent this in the future, previous attempts clearly did not work

https://github.com/CleverRaven/Cataclysm-DDA/pull/74357/files#diff-cddeee0a3483306adb27d8c84f153a8536fdb09b8aacc76e3e3f11e0509e74e8

It was changed in this PR, I think it's intended that it's used as tools rather than components.

https://github.com/CleverRaven/Cataclysm-DDA/blob/fad5181c66080016ba6d765a295a21082d8b49e4/data/mods/MindOverMatter/recipes/recipe_requirements.json#L83-L100

Also there is a similar requirement in MoM that was not changed to use `Any_water`.
