### ISSUE TITLE
The sound rules of the safe mode manager does not work.

### ISSUE THREAD

**Issue by Nebnis** [CleverRaven/Cataclysm-DDA#77253]
### Describe the bug

Adding rules to ignore or allow sounds doesn't seem to work under any circumstance, i have tried every sort of way but i can't ignore this frog screaming while i sort my loot for instance. White list, black list, distance, it does not matter. I feel like this has never worked for as long i can remember.

![image](https://github.com/user-attachments/assets/6caff2e9-17c6-4375-91d3-1c75e436e66d)

![image](https://github.com/user-attachments/assets/aab1fbc2-ae82-46cd-8e21-242f84d7df82)

### Attach save file

[Broadrat-trimmed.tar.gz](https://github.com/user-attachments/files/17477036/Broadrat-trimmed.tar.gz)
If you want to load my save [install this mod](https://github.com/user-attachments/files/17477358/CDDA-Extra-Lives.zip) in your data mod folder

### Steps to reproduce

1. Add a rule for any enemy making sounds in the safe manager
2. Game doesn't recognize the sounds to ignore or allow it

### Expected behavior

i would expect for that frog singing to his gf to not annoy me while i sorting or doing anything else.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.5011 (22H2)
- Game Version: cdda-experimental-2024-10-21-1656 888e34a [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Extra Lives - Extended [extra_lives_extended],
    Bionic Slots [cbm_slots],
    Extra Mutated Scenarios [extra_mut_scens],
    Mind Over Matter [mindovermatter]
]

**Comment by RenechCDDA** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/issues/77481#issuecomment-2456677056

**Comment by IdleSol** [comment]
Your saves refused to load on 2 out of 3 versions of the game (fresh and October 1). Only using version 2024-10-21-1656 helped to load. And that with errors.

If I understand correctly, you want to make the character ignore noise? Then you need to open the distractions manager:  Main menu (`Esc`) - `7` Distractions manager
![1](https://github.com/user-attachments/assets/66a80cf0-c52d-41e7-9ad6-4ea8d5b96188)

And disable the noise.

You are working with the safe mode manager, which manages the enabling of that mode. I have a rule * for noise. Since 0.F. But I don't remember what it does or if it works at all.
