### ISSUE TITLE
New material. Thermal insulation

### ISSUE THREAD

**Issue by IdleSol** [CleverRaven/Cataclysm-DDA#77293]
### Is your feature request related to a problem? Please describe.

I'm creating a mod for personal use. At the moment, I'm dealing with creating armor and clothing. In the process, I've touched on materials.

For most materials, resist values are greater than 0. And that's great when it comes to creating some new armor or clothing.

But this is bad when it comes to creating a winter version of the same garment. And the easiest way to describe the problem is to use the example of a winter jacket. The thickness of my jacket is about 2 centimeters.

Let's take any material presented in the game with a protection of 1 per 1 mm layer. Then this jacket would give a protection of 20 units. A little more and this protection would be equal to the protection of broken ESAPI plates. Of course in reality it will not give any protection.

And here is an example of a winter jacket implemented in the game:
https://github.com/CleverRaven/Cataclysm-DDA/blob/3edfea11c7f1cb319c4587691900d28c9472e111/data/json/items/armor/coats.json#L3437

The material is 1 millimeter thick. Can anyone believe that a 1 millimeter thick jacket will protect you from the cold?

The solution is quite simple, add materials for thermal insulation. Which will not affect the protective properties. And maybe in the future, they will add `warmth` value depending on the thickness. The same way protection is determined now.

I've solved it for myself. But after some thought, I decided to raise this topic for general discussion.

### Solution you would like.

What I suggest.

1. Add materials without protective properties (or with minor protective properties: approx. 0.1). The name of which contains: insulation or lining.
2. Use these materials to modify existing things. Give them more realism.
3. optional. Recipes to create such materials and modify existing recipes. While this would be unnecessary in my opinion, it would also be more realistic.
4. optional. Modification of recipes for disassembling existing things to obtain insulation and then use it in the creation of new warm things.

### Describe alternatives you have considered.

Leave everything unchanged

### Additional context

Here is an example of the material I use in my mod:

<details><summary>Details</summary>

```
[
  {
    "type": "material",
    "id": "thermal_insulation",
    "name": "Thermal insulation",
    "//": "based on nylon",
    "density": 1.15,
    "specific_heat_liquid": 1.7,
    "specific_heat_solid": 1.7,
    "latent_heat": 42,
    "soft": true,
    "chip_resist": 7,
    "breathability": "AVERAGE",
    "repaired_with": "null",
    "dmg_adj": [ "ripped", "torn", "shredded", "tattered" ],
    "bash_dmg_verb": "ripped",
    "cut_dmg_verb": "cut",
    "//1": "Nylon reacts poorly to flame (it melts) but is hard to light. Doesn't break down easily unless exposed to a high-intensity fire.",
    "burn_data": [
      { "fuel": 0.05, "smoke": 1, "burn": 0.01 },
      { "fuel": 0.05, "smoke": 2, "burn": 0.03 },
      { "fuel": 0.15, "smoke": 5, "burn": 0.5 }
    ],
    "resist": { "bash": 0, "cut": 0, "acid": 0, "heat": 0, "bullet": 0 },
    "repair_difficulty": 2
  }
]
```
</details> 

And this is what it looks like:
![1](https://github.com/user-attachments/assets/688b2a0e-d544-476b-9271-92d5267b5cfe)

**Comment by Hyperseeker** [comment]
I believe [this jacket](https://www.tennierindustries.com/product/layer-5-jacket/) to be the basis of the one you're highlighting. It's a [level 5](https://ciehub.info/clothing/CW/ECWCS/GEN3/Level5.html) (cold weather, but not extreme cold weather) [jacket](https://ciehub.info/clothing/CW/ECWCS/GEN3/Level5.html) from the [third-generation Extended Cold Weather Clothing System](https://ciehub.info/clothing/CW/ECWCS/GEN3.html). (It could also be a level 6, given that we're in New England.)

By the looks of it, it's supposed to be insulating, but not too much, and to be worn with layers of previous levels underneath. So... maybe 2 mm? Maybe a bit more?

The only thing that says to me `warmth: 50` is the [level 7 parka](https://ciehub.info/clothing/CW/ECWCS/GEN3/Level7.html), which *is* supposed to be thick, since it's the clothing for the harshest of colds in which the Army is expected to operate.

Not arguing for or against the suggestion, just my two cents on how thick the item is supposed to be.

**Comment by kevingranade** [comment]
Noted,  someone can do that,  but this kind of broad suggestion isn't what issues are for,  they need to be specific and actuals both to avoid confusion and so it is feasible to implement and then close the issue in a timely fashion.

**Comment by IdleSol** [comment]
Doesn't the game have any plans for further development? Is all that's left are the problems? Or how do you propose to describe something new?

No, some talented author will just come along. He's gonna write a quest story. And what will he hear in response?

A lot of text, keep it short. Or do it yourself. Or your proposal should be reduced to one specific sentence. Which we can immediately correct and close the thread.

If anything, I don't expect an answer. Those were rhetorical questions.

**Comment by AudBobb** [comment]
I think ideally, the discussions tab would be the place for these kinds of suggestions, both this one and the medicine one you posted a week ago, but no one seems to check there or use that feature, so :shrug:

**Comment by kevingranade** [comment]
> He's gonna write a quest story. And what will he hear in response?

If it's a story that's detailed and feasible to implement,  they're going to hear tips on doing so and on story/game fit, if they proceed to implement it everything is great.  If it's not a story but a concept of a story,  it will be closed,  those are a dime a dozen and we don't need more. If they just drop a narrative and don't implement it,  it will be closed,  stories are a done a dozen,  we don't need more,  we need implementation. 

It can be productive to hash out vague suggestions and unfinished ideas,  but github issues is simply not a place for that kind of discussion.  We have discord and discourse for that.
Github discussions has poor to nonexistent moderating features,  which is why we aren't using it.
