### ISSUE TITLE
Pocket 'Set priority' input box was hidden

### ISSUE THREAD

**Issue by DPurple** [CleverRaven/Cataclysm-DDA#77290]
### Describe the bug

When set priority for pockets, the input box was hidden under current pocket setting menu

### Attach save file

no save needed

### Steps to reproduce

Enter any 'pocket settings'
Select 'Set priority' for any pocket

### Expected behavior

Input box should in top layer

### Screenshots

![cap](https://github.com/user-attachments/assets/b2cb0e18-7ba5-4046-a0a4-ffa622ddd9d6)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.5011 (22H2)
- Game Version: 3edfea1 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Extra Mutated Scenarios [extra_mut_scens],
    Fancy dress [fancy_dress]
]

**Comment by IdleSol** [comment]
Confirmed. cdda-windows-tiles-x64-2024-10-24-0244

Most likely the same reason as with the search bar.

**Comment by RDeckard** [comment]
FTR, the scope of this problem is probably more extensive, as it also occurs e.g. the _zone selection screen_ from the **Zone Manager**.

### Step to reproduce: (default keybindings)

1. Open the Zone Manager (press `Y`)
2. Add a new zone (press `a`)
3. User the filter (press `/`)

### Screenshot

The filter window, while being active, is not on the top layer:
![image](https://github.com/user-attachments/assets/09c1ca98-1764-4a71-bcff-38e7055a91ca)

**Comment by marilynias** [comment]
should be fixed with #77863

**Comment by Brambor** [comment]
> FTR, the scope of this problem is probably more extensive, as it also occurs e.g. in the _zone selection screen_ from the **Zone Manager**.

 - This is already fixed by #77863
 - The OP will be fixed by #78453
