### ISSUE TITLE
Placing an OMT through overmap editor lags the game

### ISSUE THREAD

**Issue by Milopetilo** [CleverRaven/Cataclysm-DDA#77341]
### Describe the bug

Whenever spawning anything in through the overmap editor, the game slows to a crawl.

### Attach save file

N/A

### Steps to reproduce

Open the overmap editor, press `s` or `t` to open the placing menu, select anything, try moving it around, witness slowdown.

### Expected behavior

The game to keep running at normal speed, maybe slightly slower.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.5073 (22H2)
- Game Version: cdda-experimental-2024-10-24-2254 12b4e6c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by Procyonae** [comment]
Relevent function https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/overmap_ui.cpp#L1457 and it's call https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/overmap_ui.cpp#L2131

This is pretty annoying and has existed since before I started afaik, I've tried making it invalidate/redraw both ui_adaptors only as needed and copied the more convoluted chrono based blinking and scroll timeout stuff from [display()](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/overmap_ui.cpp#L1835) with no noticeable difference
