### ISSUE TITLE
Aluminum Tank (100 L) installation doesn't require a drill

### ISSUE THREAD

**Issue by Maarifrah** [CleverRaven/Cataclysm-DDA#77505]
### Describe the bug

Every vehicle tank in the game (including the roof-mounted variant of the 100 L tank) requires a drill in order to install except for the aluminum tank 100 L. I don't see any reason that this one should be any different and suspect that it's just a minor oops.

### Attach save file

N/A

### Steps to reproduce

1. Go to a vehicle.
2. Examine the vehicle
3. Filter for tank
4. See that the Aluminum tank (100 L) doesn't require a drill while the other tanks do!

### Expected behavior

Tools required: cordless drill (100 charges) OR drill press (50 charges) OR hand drill OR power drill (100 charges). (These charges are taken from the roof-mounted variant of this same part).

### Screenshots

![oKIbD9A](https://github.com/user-attachments/assets/3802e7e1-59ce-40ac-b220-e3b6340582f1)

### Versions and configuration

Windows 10
build type: windows-tiles-x64-msvc
build number: 2024-10-23-0605
English

**Comment by Procyonae** [comment]
There's a few other oddities with the tanks from a skim read if anyone wants to do more than a 1 line fix (this was just what jumped out on a skim through I haven't looked for reasoning anywhere and have never welded anything big, it could all be justifiable):
- Being able to mount 200L tanks on cloth rooves
- Requiring bolt turning on some but not all the ones which expect drills
- Not requiring nuts and bolts for any of those
- I'm not sure why it's specifying drills rather than just the drilling quality unless that doesn't use the right amount of charges
- I don't really understand why the ones being welded also need drilling
