### ISSUE TITLE
Infinite chamomile tea

### ISSUE THREAD

**Issue by Numbuh474** [CleverRaven/Cataclysm-DDA#77525]
### Describe the bug

I have a jar full of chamomile tea that doesn't consume if drunk, but gives the tiredness effects. Unknown reproduction steps.

### Attach save file

[River Bend-trimmed.tar.gz](https://github.com/user-attachments/files/17605823/River.Bend-trimmed.tar.gz)

### Steps to reproduce

There's a jar of chamomile tea on the shelf to the left of the character. Try consuming it?

### Expected behavior

I expect drinking tea causes it to disappear from the container it was drunk from.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.5011 (22H2)
- Game Version: 0.H-232-g69aa044fc3 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bombastic Perks [bombastic_perks]
]

**Comment by TheIssueFairy** [comment]
I'm getting infinitely consumable sleeping pills in my game, maybe this is related?

**Comment by IdleSol** [comment]
- #69507

**Comment by TRScheel** [comment]
> I'm getting infinitely consumable sleeping pills in my game, maybe this is related?

I can confirm this bug

**Comment by TRScheel** [comment]
I narrowed down the issue. It is any item with type `COMESTIBLE` and a use_action of type `effect_on_conditions`

These are the only items that have this combination:
`chamomile_tea`
`pills_sleep`
`poppy_sleep`

The issue exists here https://github.com/CleverRaven/Cataclysm-DDA/blob/41efa553278e30c052d1b2f010347287a9f1a91f/src/iuse_actor.cpp#L5733-L5737

When the comestible is in the player's inventory, it correctly returns 1 to consume it. When it is not, that `if` fires and returns 0.

I didn't see any other comestible with an `effect_on_conditions` which leads me to believe the issue is the `comestible`<>`effect_on_conditions` combination, not this specific LOC. 

With that in mind, I propose the solution to this is to modify those three items to match `poppysyrup`'s use_action. In this code snippet you can see the difference between `poppy_sleep` and `poppysyrup`

 https://github.com/CleverRaven/Cataclysm-DDA/blob/41efa553278e30c052d1b2f010347287a9f1a91f/data/json/items/comestibles/med.json#L1521-L1562
 
I'll test that modifying the `use_action` works properly for those three items and submit a pull request for that in the morning unless someone can let me know about any follow-on effects `FLUSLEEP` has that I am unaware of.

Additionally, if it is intended for comestibles to be able to have `effect_on_conditions` then that function will have to be modified to properly decrement the item's count when used. If it is not intended for comestibles to have `effect_on_conditions`, then I recommend that `std::optional<int> effect_on_conditons_actor::use( Character *p, item &it, const tripoint_bub_ms &point )` fails in some way when attempted to be used by a comestible. From the looks of things, a `debugmsg` and short circuit at the top of the function should suffice. I will need guidance from someone more familiar with the project to decide on which path to take.
