### ISSUE TITLE
chunk loader

### ISSUE THREAD

**Issue by blablase** [CleverRaven/Cataclysm-DDA#77563]
### Is your feature request related to a problem? Please describe.

when you just want to go on an adventure alone or with 1 or 2 and place the rest at home but want them to do something that is productive that is not related to the faction camp

### Solution you would like.

something that keep the base loading, some time the freezer and the items inside it isn't working properly freezer is on but the items is rotten because it's still normal temperature when you leave the place

a chunk loader for the npc to craft thing at base or read book or mining or constructing or dissembling something,

 or use some kind of calculator then you will get the time that you leave the base till the time that you return for the book it's how much xp the npc gain with that amount of time, the progression for the crafting construction mining and dissembling

**Comment by Holli-Git** [comment]
While having stuff still operate while unloaded is wanted, just having the game render it is a poor implementation. There is already quite a few ways this is done with catchup code. If something lacks the catchup code, it is more appropriate to file a bug report specifically about that, instead of a vague feature request which boils down to "improve the thing". The latter is not helpful at all.
