### ISSUE TITLE
iGUI in character creation broken

### ISSUE THREAD

**Issue by Mer1ck** [CleverRaven/Cataclysm-DDA#77636]
### Describe the bug

The GUI when you attempt to exit character creation does not function. It appears when attempting to exit or close the CDDA window, and the Yes/No options cannot be selected. I've tried using keyboard, mouse, and shortcuts, and am unable to select "yes" or "no" on the popup.

### Attach save file

N/A

### Steps to reproduce

Create World
Start to create Custom Character
Attempt to exit via closing the window or Alt + F4
Bug should occur

### Expected behavior

You should be able to select either option and leave character creation/quit the game

### Versions and configuration

OS: Windows 11
Game Version: 19807c7
Graphics: Tiles

**Comment by ZhilkinSerg** [comment]
@andrei8l While we can consider the original issue resolved, `Alt+F4` is not handled properly now (at least on Windows):

1. Pressing `Alt+F4` in character creation menu shows Y/N prompt:

- - pressing `Y` closes game window instead of returning back to main menu.
- - pressing `N` returns back to character creation. Then if you then press `ESC` to come back to main menu - you receive another Y/N prompt and if you press `Y` game window would be closed.

2. Pressing `ESC` in character creation menu (when not pressing `Alt+F4` at any time beforehand) shows Y/N prompt:

- - pressing `Y` returns back to main menu as expected;
- - pressing `N` returns back to character creation menu as expected.

***

Similar wrong behavior is in other menus, e.g. if you open any popup in Settings menu (say, default name) and use `Alt+F4` there, nothing happens at first, but if you then press `ESC` to close popup and then hit `ESC` again to close Settings menu and return back to main menu, game window would be closed instead.

It looks like exit signal is pending and handled once current ui loop is finished.

**Comment by RenechCDDA** [comment]
> Similar wrong behavior is in other menus, e.g. if you open any popup in Settings menu (say, default name) and use Alt+F4 there, nothing happens at first, but if you then press ESC to close popup and then hit ESC again to close Settings menu and return back to main menu, game window would be closed instead.

Which settings menu is this? I can't reproduce.

**Comment by ZhilkinSerg** [comment]
One of these:

![image](https://github.com/user-attachments/assets/e39a14a4-2b9e-480e-91f2-54c9f7da419a)
![image](https://github.com/user-attachments/assets/71cd470f-b299-4570-88e6-2f237aae4b30)
