### ISSUE TITLE
Crushed by debris from bomb 60 tiles away

### ISSUE THREAD

**Issue by ShnitzelX2** [CleverRaven/Cataclysm-DDA#77786]
### Describe the bug

I was testing walls in the latest experimental, and when I blew up a 100L bomb next to some t_strconc_wall, the PC got buried under nonexistent rubble.

### Attach save file

[Tillman-trimmed.tar.gz](https://github.com/user-attachments/files/17721632/Tillman-trimmed.tar.gz)

### Steps to reproduce

1. Ignite 100L barrel bomb
![image](https://github.com/user-attachments/assets/4141b6d3-ee72-48a0-8f92-502ca1526c6f)
2. Teleport 60 tiles west, then wait 5 minutes
3. Observe this
![image](https://github.com/user-attachments/assets/50fb3d8d-281d-44f8-bd70-9263a0ab965b)

PC is injured but unmoved
![image](https://github.com/user-attachments/assets/e8c99e65-6239-461f-9033-b32d88b78dd7)

PC is also stuck in rubble
![image](https://github.com/user-attachments/assets/0cb8ecb9-acaf-43ee-b960-2efe15f450be)

### Expected behavior

The radius that a 100L barrel bomb damages terrain in is about 9-10 tiles, so the PC shouldn't be falling or getting crushed by rubble.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.5011 (22H2)
- Game Version: b8a6d08 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

I will check recent experimentals to make sure this wasn't my fault

**Comment by ShnitzelX2** [comment]
The "falling debris" bug is not present in 2024-11-08-2315 and is present in 2024-11-10-1921, so somewhere between there

The "You fell down a ledge!" bug was present in 2024-11-08-2315, but it also doesn't appear to do anything

**Comment by PatrikLundell** [comment]
I suspect the fresh appearance of falling debris is an illusion caused by the RNG producing debris now but not a bit earlier, but I can't rule out that something actually happened to make a change to whether debris fell on the original (pre teleport) tile or not.
However, the basic bug is that the code evaluates the PC as if it was at the original location, because it was looking for a character at the corresponding bubble coordinates in the map used to evaluate the explosion, but getting the coordinates of the PC. A PR to fix this has been made.

And the PC is no longer reported to fall down a ledge either.

The bug report description and save made it easy to track down and fix the issue.
