### ISSUE TITLE
Guidelines for behavior of primitive ranged weapons

### ISSUE THREAD

**Issue by ampersand55** [CleverRaven/Cataclysm-DDA#77799]
### Is your feature request related to a problem? Please describe.

There are guidelines for the damage of bows:

https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/GAME_BALANCE.md

But nothing with regards to their range, accuracy, attack speed, usability or relative effectiveness compared to guns or melee weapons. 

There are also other types of ranged weapons, such as crossbows, staff slings, slingshots, the atlatl spear thrower and throwing weapons such as throwing sticks, war darts and throwing knifes.

If the guideline for archery damage would be applied to the atlatl and most other throwing weapons would deal too much damage.

---

A quick calculation:

From GAME_BALANCE.md:

> Base damage is calculated from momentum by taking momentum in Slug-foot-seconds, multiplying by 150 and subtracting 32. 

According to [wikipedia ](https://en.wikipedia.org/wiki/Spear-thrower)(https://en.wikipedia.org/wiki/Spear-thrower) a spear thrower can throw a spear 150 km/h. An atlatl spear weighs 230 grams, which would translate to a momentum of 2.154 slug foot/s and a damage of 291.2 ([calculation on wolfram alpha](https://www.wolframalpha.com/input?i=%28230+grams+*+150+km%2Fh%29+%2F+%281+slug+foot%2Fsecond%29+*+150+-+32)).

Just for reference/comparison:

* A professional baseball pitcher throwing a baseball-like 150 gram object 100 mph would do 194.1 damage.
* An elite javelin thrower throwing a 800 gram javelin at 100 km/h would do 717.4 damage. 

I'm not saying that there necessarily has to be the same damage calculation for all primitive ranged weapons. 

### Solution you would like.

I would like some sort of guidelines for the things mentioned. Range, accuracy, attack speed, some sort of measure of general "effectiveness" to evaluate how good a ranged weapon is, similar to how there's guidelines for melee weapons. I think one metric could be: While standing still, on average, how much damage would one be able to inflict on a charging monster before it got within melee range?

I also think primitive ranged weapon accuracy could be buffed across the board, if nothing else for the sake of verisimilitude. If I were a new player and feral humans would consistently hit me with rocks from 5 range, I would expect that I could do the same. But a 8/8/8/8 player with 10 throwing skill only has ~~49%~~ (EDIT: 51%) hit chance against the debug monster while standing right next to it.

**Comment by harakka** [comment]
> If I were a new player and feral humans would consistently hit me with rocks from 5 range, I would expect that I could do the same. But a 8/8/8/8 player with 10 throwing skill only has 49% hit chance against the debug monster while standing right next to it

We have tests for feral accuracy from given ranges, they should match player throwing with same skill. If it doesn't that's a bug.

**Comment by IdleSol** [comment]
Player with 8/8/8/8. Throwing skill: 3.

1. Target: debug monster. Distance between player and monster 5 tiles.

- 7 stones out of 10 hit the monster and did damage.
- 10 out of 10 hit
- 6 out of 10

2. Target: mon_feral_human_pipe.

Distance at the start of combat, 10 tiles.
Distance between player and monster at first throw: 6 tiles.
Feral came close to the player. During the entire journey, he made only 1 hit (from a distance of 5).

It took 15 rocks to kill a feral. Of those, 12 of them did damage: from 1 to 12. More often around 8 to 9.

So I'd say the player throws stones faster and better than the wild.

**Comment by ampersand55** [comment]
When I actually throw the rock I seem to do hit more than what the aim window display would suggest. 

But then there's an error in the display window and a huge disparity between simply throwing things, and using weapons that use the throwing skill. 

An 8/8/8/8 character with 5 throwing skill can fairly consistently hit the debug monster at range 16(!) only costing 60 movement. That's  7/0.6 = 11.67 dps!

For comparison, a Ruger 10/22 rifle at range 16 using precise aim would do 16 damage in 402 moves, 16/4.02 = 3.98 dps if all shots it at 82%.

**Comment by kevingranade** [comment]
> Base damage is calculated from momentum by taking momentum in Slug-foot-seconds, multiplying by 150 and subtracting 32.

That guideline is quite misleading and I agree it needs to be clarified.  That damage is a ceiling rather than base damage, i.e. that's what you can achieve with a critical hit, not the pre-critical base damage.

The reality is that an atlatl dart or a javelin is going to have much higher momentum and therefore much higher base damage (though I have issues with some of your sources) than an arrow but due to the realities of landing a hit with a javelin or an atlatl. You're not going to be able to count on reliably generating critical hits. This cuts damage output by an order of magnitude.

> According to [wikipedia ](https://en.wikipedia.org/wiki/Spear-thrower)(https://en.wikipedia.org/wiki/Spear-thrower) a spear thrower can throw a spear 150 km/h. An atlatl spear weighs 230 grams, which would translate to a momentum of 2.154 slug foot/s and a damage of 291.2 ([calculation on wolfram alpha](https://www.wolframalpha.com/input?i=%28230+grams+*+150+km%2Fh%29+%2F+%281+slug+foot%2Fsecond%29+*+150+-+32)).

I couldn't follow the link to the Wikipedia reference to check the rationale or spear weight, so I found this paper https://www.nature.com/articles/s41598-023-40451-8 showing *up to* 25 m/s for a 200g atlatl dart. So right off the bat this 150 km/h figure seems suspect.  From the context I can see it looks like this figure came from a national level atlatl competition.  Your character isn't a national level athlete specialized in this specific sport. Also it's likely we're talking about throwing for distance vs aimed throws,  these are two different contexts you can't really compare. Maximum power throws impair accuracy to the point of uselessness,  throwing at a target is going to have a much reduced achievable momentum.
The lower figure drops the base damage to a still quite high 136, which is quite a lot of damage, but again that's assuming a critical hit and isn't particularly achievable with an atlatl or javelin.

>    A professional baseball pitcher throwing a baseball-like 150 gram object 100 mph would do 194.1 damage.

The damage formula we use for a bladed projectile is OBVIOUSLY not the same one we would use for a blunt object.  Please think at least a little about the realities here. Again,  your character also isn't a professional baseball pitcher.

As for the issue,  yes it would be nice,  but if we accepted issues for every piece of documentation we could potentially add we'd have double the issues.

**Comment by ampersand55** [comment]
> I couldn't follow the link to the Wikipedia reference to check the rationale or spear weight,

The Economist article simply states:

> The atlatl serves to amplify the hurler's arm movement in a way that allows a stone-tipped spear to be propelled at speeds of well over 150kph.

The article cite the World Atlatl Association, John Whittaker (anthropologist at Grinnell College, Iowa), and (John Shea, archaeologist at Stony Brook University in New York State). But the 150kph figure is not directly attributed to anyone of them. 

> The damage formula we use for a bladed projectile is OBVIOUSLY not the same one we would use for a blunt object. Please think at least a little about the realities here. 

Still, a feral throwing rocks will out-dps the bladed projectiles. 

I was quite clear that I didn't expect the same damage calculation for all primitive ranged weapons. 

>  Again, your character also isn't a professional baseball pitcher.

I used the higher bound for ranges as it's easier to find those numbers. I would also think a higher bound is more relevant to game balance as survivors can go beyond human capabilities with mutations and cbms. 

> As for the issue, yes it would be nice, but if we accepted issues for every piece of documentation we could potentially add we'd have double the issues.

I think it's particularly important to document weapons for the following reasons:

1. Many character builds are centered around using a specific weapon or class of weapons, so weapon balance directly influence how many play the game, often opting for the most effective weapons.
2. Primitive weapons are particularly important as they are very much directly tied to the survivability of your character. New players will have wildly different experiences depending on whether they choose a more effetive or less effective starting weapon.
3. As I've noted in this final issue #77827 (which I promise will be the last one I make regarding primitive ranged weapons!), a lack of guidelines has allowed for two very different systems of throwing weapons to co-exist in the game.
