### ISSUE TITLE
Constructing dirt floor, which costs nothing, magically makes a shingle roof appear above

### ISSUE THREAD

**Issue by NetSysFire** [CleverRaven/Cataclysm-DDA#77855]
### Describe the bug

CC @PatrikLundell because roofs.

### Attach save file

n/a

### Steps to reproduce

1. Have fabrication 3.
2. Construct a dirt floor, which requires no materials at all.
3. Notice there is a shingle roof over your head now.

### Expected behavior

No magic shingle roof.

By the way, why can dirt floors be smashed? Its dirt. It should say there is nothing to smash.

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: cdda-experimental-2024-11-14-1240 65b3721 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

Hey @PatrikLundell, is it intended that roofs can no longer be built right above you? Building one always attempts to place the roof terrain on z-level 0, where it makes no sense at all. Even climbing on your constructed wall does not help as the construction menu will not use ingredients from right below you.

**Comment by PatrikLundell** [comment]
I believe you should be able to smash dirt floors, because there might be a cellar beneath it, in which case you should be able to smash a hole down to it.

It is indeed intended that you'd have to make your way up to the level of the future roof to be able to build it, and your building materials would have to be in reach, which means you can't extend your arms 3 meters down to pick stuff up, but rather would have to haul it up, where it would be available using the normal materials search.
There are (at least) two ways to get up so you can build something at higher levels:
- Build up stairs, which works for a single level only. You should then be able to stand at the top and build from there.
- Set up scaffolding and build from there. Since they can be built upwards you'd be able to build as high as you like (but it uses a huge amount of materials).
- Ramps might work, if the top tile gets you up to the roof level.

The rest I will have to look at, probably tomorrow, as no, magic roofs should have been abolished.

**Comment by PatrikLundell** [comment]
/Confirmed

Weirdly, a bizarre looking contraption containing the Nunez couple teleported in, and this happens in a save where my character hasn't yet been able to reach the Refugee Center (all paths blocked so far, except 30 or so tiles of city).

This is a first response, as I intend to continue to look into it.
