### ISSUE TITLE
Anti-fungal Drug Spawning Issue

### ISSUE THREAD

**Issue by realcoolguy** [CleverRaven/Cataclysm-DDA#78008]
### Describe the bug

There seems to be a spawning issue with anti-fungal drugs not spawning (or my runs have been beyond BEYOND unlucky).

I enjoy the fungal infection start a lot!  I've now upped the spawn rate to 1.5x normal for items after getting frustrated at not finding a single tablet.  I have cleared 6 pharmacies and 8 doctor offices (including the locked room or locked safes) with these settings.

This over the course of 4 characters.  Hundreds of home bathrooms searched too.  Not a single tablet.  I'm about to resort to the debug mode to edit some in since something seems broken with worldgen.

Can anyone verify that spawns of anti-fungal drugs still work on the current experimental?

I assume anti-parasitic drugs are in a similar spawn rate?  I have come across literally hundreds of tablets of that but 0 anti-fungal.

Thanks for anyone who takes a look at this.  It may just be incredible RNG factors at play.

### Attach save file

NA - it's trivial to provide saves with empty anti-fungal pharmacies but I have gone through several now with increased item settings.  

### Steps to reproduce

Increase Item spawn rate.  Teleport to a pharmacy (which seems to have the highest chance of having some).  Observe 0 anti-fungal drugs over and over.

### Expected behavior

Anti-fungal drugs should appear and they are not.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.4460 (23H2)
- Game Version: cdda-experimental-2024-11-15-0512 0f2c155 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Martial Mastery [perk_melee_system],
    Extra Mutated Scenarios [extra_mut_scens],
    Bombastic Perks [bombastic_perks],
    Mythical Martial Arts [MMA],
    Stats Through Kills [stats_through_kills]
]

**Comment by TheMurderUnicorn** [comment]
Okay, so to unpack what's going on -- Firstly, antifungals ARE spawning in both pharmacy layouts on the most recent version here's the version details. - OS: Windows
    - OS Version: 10.0.19045.5011 (22H2)
- Game Version: bbc0d00 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda]
]

Okay, and then for the actual issue - 
antifungals spawn via the drugs_pharmacy group, which calls the drugs_rare group, which is where the antifungals can be chosen as the rare spawn.  When drugs_pharmacy is called, it has a 1/5 chance to spawn rare_drugs.  Then, there's a 1/10 chance of spawning antifungals.  IE: each call to the drugs_pharmacy group has a 2% chance of spawning antifungals, the same odds as spawning antiparasitics, prozac, thorazine, etc.

There are two pharmacy layouts, pharm and pharm1.  pharm has a row of lockers in the rear, in both side rooms, each of which contain potential spawns for anti-fungals.  Each of these L's uses the above itemgroup:
![image](https://github.com/user-attachments/assets/98f0027c-1dec-4cc1-997d-18a4c1f38e04)

Due to the heavy amount of L's, this version is significantly more likely to spawn antifungals, and if you debug spawn it, almost every layout will contain some antifungals.
![image](https://github.com/user-attachments/assets/6ea9db85-1aa9-4a31-a673-51c2948f2037)

In the second layout, each of these x's spawns the same thing as the above L's, though you will notice there are significantly fewer in this map layout. 
![image](https://github.com/user-attachments/assets/ba852d84-420d-4f60-b8e3-d546d00f939b)
As a result, it is noticeable less likely for antifungals to spawn in this map location.  I found that they only appeared in every 3-4 layouts, but that's just anecdotal/low sample size since I only spawned like 15 total in testing.
However, they are capable of spawning here: 
![image](https://github.com/user-attachments/assets/d4bcd257-ac0d-4c19-96da-b3c893dab04a)

And then just to show that it works, testing the drugs_pharmacy group above:
![image](https://github.com/user-attachments/assets/2a24ca12-f1c8-4873-a6da-7176b1e34ec0)



So, anyway, TLDR: They do spawn, you have been unlucky, and the second mapgen layout is not exactly brimming with antifungals.  While I object to them being treated as "valuable" drugs, antifungals are, in fact, less common medications and they don't actually have a basic over the counter version.  People who need antifungals in the US are typically required to get a prescription, especially for the pill form of medication.  You can find some antifungal creams over the counter, however, pill versions or even high value/concentration ketoconazole cream would likely require a prescription.  And for the purposes of our fungal issues in game, they would likely require the pill form of medication, not a topical cream.

I am disappointed that I spent so much time on this and found nothing to fix x_x but yes, that is the situation, hopefully this addresses your concerns.  If we wanted to change something, I think that rare drugs should be a higher chance to spawn in the back room of the pharmacies, as there is essentially no other mapgen location that consistently can spawn rare drugs, and the odds (20%) of hitting that group in this mapgen is a bit sad.

ALSO: if you look at the itemgroup spawn list, you'll see things like acetaminophen is cluttering this group, and absolutely should not be spawning behind locked doors in a pharmacy.  It's not taking a slot per se, since you still have the 1/5 chance to hit the rare drugs group, but it hurts me to see them behind the locked doors/counters.

**Comment by realcoolguy** [comment]
What's funny is I teleported myself to 4 more pharmacies (0 pills found at my 150% settings) after I posted this to make sure I wasn't crazy.  RNG is a hell of a drug it seems. 

Thanks for confirming they're still there.

**Comment by TheMurderUnicorn** [comment]
np, as I started testing it I really did think something was wrong, that's why I looked into it so thoroughly, the 2% chance isn't unreasonable, and antifungals are relatively rare in a pharmacy compared to something like antibiotics or painkillers (just statistically, irl) but having them NOT appear in so many debug spawns was alarming.  It's a shame I didn't actually find anything that needed changing to justify the time investment, but yeah, it seems not great and their groups kind of suck, I just don't have the patience to rework nested itemgroups/it's not strictly necessary.
