### ISSUE TITLE
Reduced performance

### ISSUE THREAD

**Issue by IdleSol** [CleverRaven/Cataclysm-DDA#78092]
### Describe the bug

I did an experiment. I took two versions of the game:
- cdda-windows-tiles-x64-2024-08-01-0043
- cdda-windows-with-graphics-x64-2024-11-23-0704

I loaded the game from August 1. I set item spawn scaling factor = 0.01. Then I created a world and a character. Started with Liam. And made a save.

Savings copied to the game from November 23.

Each version of the game had a save loaded and a standby mode enabled until dawn (19 hours and 59 minutes). (And video recording was enabled).

The duration amounted to:
- 48 seconds for the August version
- 77 seconds for the November version.

The difference 77/48 ~ 60%. Which is quite significant.

Repeating the experiment (new start: additionally removed character stuff and changed the language to English): 65 seconds vs. 95 or ~46%. 

### Attach save file

I'm not sure it's needed. But just in case, this is the full archive:
[test.zip](https://github.com/user-attachments/files/17879388/test.zip)

### Steps to reproduce

n/a

### Expected behavior

n/a

### Versions and configuration

cdda-windows-tiles-x64-2024-08-01-0043
cdda-windows-with-graphics-x64-2024-11-23-0704

**Comment by NetSysFire** [comment]
In another issue you mentioned you use wine/proton despite being on linux and you already had *at least* one weird issue because of just that. While I generally believe you, intentionally poking the hornets nest by using a compatibility layer such as wine makes some of your issues borderline invalid in my opinion as these can very well be influenced by it. Either stick to using linux by using our linux builds or use a real windows. As Procyonae already confirmed this one it is fine but I want you to stop submitting bug reports where you use this setup as these can just be plain wrong as I explained. You should also re-test the ones you already submitted with that setup.

And again, I literally use the same distro as you and the CI artifacts, the AUR package and the in-repo package (0.H is in testing btw) all work flawlessly. There is absolutely no reason to use wine here.

**Comment by Vaskritaya** [comment]
> 
> And again, I literally use the same distro as you and the CI artifacts, the AUR package and the in-repo package (0.H is in testing btw) all work flawlessly. There is absolutely no reason to use wine here.

Additionally, if the issue is access to a launcher. there are also linux compatible launchers in the AUR like catapult (via catapult-bin)

**Comment by IdleSol** [comment]
Okay, no reports.

**Comment by NetSysFire** [comment]
I didn't say to stop reporting entirely, I told you to use a supported setup we actually support.
