### ISSUE TITLE
Can't build any type of roof over doorway

### ISSUE THREAD

**Issue by Myfharad** [CleverRaven/Cataclysm-DDA#78202]
### Describe the bug

I can't build a roof over a doorway, I tried maybe just the door frame and no, I tried with no doorway and that's a no too since a roof needs something to support it. 

### Attach save file

[New World-trimmed.tar.gz](https://github.com/user-attachments/files/17944133/New.World-trimmed.tar.gz)

### Steps to reproduce

1. open build menu and type roof
2. try to build any type of roof over a doorway

### Expected behavior

for the doorway to support having a roof on top just as every other building in cdda does.

### Screenshots

![roof](https://github.com/user-attachments/assets/c57f524a-c550-44b8-8a24-20fbefbf2bc4)
![roof2](https://github.com/user-attachments/assets/f04e7630-cf24-4317-8e66-9d439550b56b)
I tried with both 1st and final stages of a doorframe and both don't work.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.5131 (22H2)
- Game Version: d16889e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Triffid, Fungus and Ant Remover [myf_monsters_removal],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex]
]

### Additional context

as per #78151 I was told that no wall or door has a roof over it's head now when building one, but a few updates ago I built a door and walls which had a roof support tile above it, now they do not. So realistically I expect there to be a way to build a roof tile above a door way

**Comment by PatrikLundell** [comment]
The rules for supporting a roof demand that there is support from (at least) two sides for tiles that don't have support from below (and only walls provide that). Thus, you probably have to build a roof on top of the wall on the other side of the door first.
An alternative is to build roofs on top of the back of the house and then fill in the roof until you reach the door from the back.

However, I think there may still be something wrong here, as walls below and to the side should help, according to the rules, so the implementation of the rules may be lacking. I'll take a look at it.

It can be noted that there are sensible looking buildings in the game that can't be constructed by the player because of the restrictions the support logic places (such as overhangs over entrances).

I'm not a fan of the support logic, but haven't been able to figure out an alternative model that will have an acceptable performance during a large scale destructive event (such as a fire consuming a building, or a powerful explosion doing the same).
