### ISSUE TITLE
Isolated Artisans (and other factions) desperately need ways to rebuild trust

### ISSUE THREAD

**Issue by Terrorforge** [CleverRaven/Cataclysm-DDA#78306]
### Is your feature request related to a problem? Please describe.

I made a small mistake; tried to climb over the fence outside Cody's shop, and because of the muscle memory of answering the climb prompt I accidentally agreed to take the reputation hit. Now neither she nor Jay will sell me almost anything. Even after doing both the Kord and fabricator software quests, they won't give me the time of day. I asked around on Discord, and there don't seem to be any way to un-piss them off.

This feels pretty silly, both from an in-universe and from a gameplay perspective. In-universe, an infraction as small as climbing over someone's fence without permission should not be grounds for a lifetime ban, and it especially should not be enough to outweigh perhaps the two biggest favors anyone has ever done for you. In terms of gameplay, a simple missclick should not rob you of access to any entire faction. There really needs to be some way to undo the damage.

### Solution you would like.

For a first time minor infraction, there could be the option to simply apologize to the faction leader and regain standing.

Negative trust could trend towards zero over time as bygones become bygones.

Trust could build slowly from small interactions like trading or even just striking up a conversation (I believe Rubick and the Exodii currently work like this).

In order to prevent players from intentionally abusing these forgiveness mechanics, a total tally of infractions could be kept. Ideally I think people would let you get away with tiny dumb crimes (like climbing over a fence) indefinitely if the infractions are spaced out and they like you otherwise and they only get really pissed about more serious crimes like stealing and assault, but a simple "five strikes and you're out" rule would work as an initial implementation.

**Comment by kevingranade** [comment]
They really don't,  just pay attention to what you're doing.

There is some interest in some kind of forgiveness system as outlined in #73570 but fundamentally this will not fix the issue you are outlining, because if you are careless enough to accidentally hit yes on a clear warning popup you're either going to do it again, in which case a forgiveness system isn't going to help,  or you're capable of just not reflexively hitting y to prompts without reading them,  in which case you don't really need a forgiveness mechanic.

It's very telling you think *five* infractions is a reasonable starting point, that's an absurdly high number that basically means NPCs are pushovers that don't actually care about their rules.

Just to be clear here,  I would expect one of the *reasonable* reactions to ignoring no tresspassing signs to be the faction immediately opening fire on you. I.e. setting up turrets that shoot anything that crosses the fence.
