### ISSUE TITLE
[Xedra] Wearing the electronic Halo breaks the save file

### ISSUE THREAD

**Issue by b3brodie** [CleverRaven/Cataclysm-DDA#78329]
### Describe the bug

[Xedra Evolved] Wearing electronic halo permanently breaks the save.

### Attach save file

[xedra_test.zip](https://github.com/user-attachments/files/18001856/xedra_test.zip)

### Steps to reproduce

1. Make a world with Xedra Evolved loaded
3. Debug spawn inventor's Halo
4. Wear inventor's halo
5. Save and quit the game
6. Load the save again

### Expected behavior

Save should not be bricked.

### Screenshots

![broken save](https://github.com/user-attachments/assets/de97fb9a-943d-4107-8145-d1f0e3f9a5aa)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.5131 (22H2)
- Game Version: 7e0339c [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Xedra Evolved [xedra_evolved]
]

**Comment by GuardianDll** [comment]
Possible reason: serialization code in <https://github.com/CleverRaven/Cataclysm-DDA/blob/943529c055b84ce672098ada6b8623d4b9bea121/src/magic_enchantment.cpp#L714> lacks `jsout.end_array();`
No one saw it, including me, probably because only items actually use this serialization, and there is only few items that use special_vision
