### ISSUE TITLE
Make mp3 player reloadable again

### ISSUE THREAD

**Issue by KHeket** [CleverRaven/Cataclysm-DDA#78435]
### Is your feature request related to a problem? Please describe.

Its very uncomfy to charge mp3 players via plug in function, because in this way there is a lot of excess key presses

### Solution you would like.

Make mp3 player reloadable by battery again, or make it at least ups by default to make it rechargeable automatically, when you place in in vehicle cargo with battery charger

**Comment by moxian** [comment]
If you google "mp3 player", almost all of the results have internal batteries and are not reloadable, so that's probably a no-go.

Making it UPS sounds reasonable.  
Making vehicle battery charger (or perhaps recharging station) work on electronic devices with cables also sounds like something that'd minimize keypresses without affecting balance.

**Comment by Maddremor** [comment]
Having stuff run on UPS proper is not great since we want to move away from that system (I don't have the details, but it's pretty gnarly on the code side), but having it take power in a recharging station makes perfect sense to me. I'm not sure what the latest flavoring is, but the recharging station sort of is a power strip with a bunch of power cables to recharge whatever.

**Comment by Maleclypse** [comment]
I could see some settings being possible similar to the cbm charging settings like automatically plug in when PC is controlling a vehicle with batteries higher than 25% and the personal electronics are lower than x%. But that's a suggestion and not a bug report and not a guarantee others will approve it.
