### ISSUE TITLE
Weather stuck at lightning storm/snow | No Hope

### ISSUE THREAD

**Issue by drmcstsr** [CleverRaven/Cataclysm-DDA#78678]
### Describe the bug

Weather stuck at lighting storm/snow no matter how much time passed. This bug persists in all the worlds that i create over a span of several experimentals. This bug only occurs with no_hope enabled.

### Attach save file

[Furnace Woods-trimmed.tar.gz](https://github.com/user-attachments/files/18212552/Furnace.Woods-trimmed.tar.gz)

### Steps to reproduce

1. enable no_hope
2. mapgen
3. char creation
4. evil-ass weather all year long

### Expected behavior

normal weather

### Versions and configuration

- Latest Artix Linux
- 41efa55327 tiles
- mods: no_hope

**Comment by Procyonae** [comment]
No Hope purposefully has crappy weather https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/mods/No_Hope/region_overlay.json#L64

**Comment by Night-Pryanik** [comment]
Actually I just wanted some more rains to pour down in the world. Having constant lighting storm or snow is not intended. Maybe something broken since I added that change in the mod.

**Comment by Procyonae** [comment]
Ugh I think the overlay is initialising a complete weather_generator rather than tweaking the existing one so it's defaulting a load of values and the defaults are complete nonsense
https://github.com/CleverRaven/Cataclysm-DDA/blob/25aabc1850e7d79a7914d289292e661f3bf30b99/src/weather_gen.cpp#L341-L346
