### ISSUE TITLE
System calendar easter eggs.

### ISSUE THREAD

**Issue by Rivet-the-Zombie** [CleverRaven/Cataclysm-DDA#8148]
Since we're in the habit of adding temporary additions for holidays, like special professions and such, how about making the game check your system's current date and apply those changes automatically? We could keep a separate .json of holiday stuff that would just get moved into the game on the specified date, then automatically disappear afterwards.
##

**Comment by Asmageddon** [comment]
Strikes me as something that people would want to play on other dates as well. Maybe keep them enabled for a week or two, at least?

**Comment by KA101** [comment]
Seasonal events in games typically last for a week or so, yeah.  We didn't bother with 'em this year, though, and I didn't see anyone really missing them though.  :-/

**Comment by Asmageddon** [comment]
Adding an extra option to seasonally enable professions shouldn't be an immense amount of work, and it's a nice small touch IMO. Perhaps also some recipes.

**Comment by mugling** [comment]
A source of potentially evil bugs, *"only occurs on third tuesday of the month"*

**Comment by codemime** [comment]
Agreed. The idea is very good, but the game is still way to bugged (after two years since then) to introduce it.

**Comment by Asmageddon** [comment]
They don't need to involve complex code with potential for breakage.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
