### ISSUE TITLE
Busy loop checking for XBox controller. SDL, 0.A-1744(+). bug?

### ISSUE THREAD

**Issue by WareXD** [CleverRaven/Cataclysm-DDA#8149]
Windows, WinXP, x86, SP3
Experimental, SDL, 0.A, 1744(+) // cataclysmdda\cataclysmdda-0.A-1744
XBox controller haven't installed on this machine.

Busy loop checking for Xbox controller. Procmon shows many attempts to access the registry key:
HKLM\System\CurrentControlSet\Control\DeviceClasses\ {ec87f1e3-c13b-4100-b5f7-8b84d54260cb}

![wtfrapidlyaccess360xboxcontrloller](https://cloud.githubusercontent.com/assets/8077681/3487683/63b22076-0496-11e4-8c8f-1ddfa61386d1.png)

Is this bug?

*P.S. sorry guys, if the question is asked in the wrong place. i am not very good speaking english and simply trying to help. Because every time game is crashed i'am become sad :).

**Comment by mugling** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
