### ISSUE TITLE
Fix signal handler

### ISSUE THREAD

**Issue by elfring** [CleverRaven/Cataclysm-DDA#8417]
The functions "[erase](http://invisible-island.net/ncurses/man/curs_clear.3x.html)" and "[exit](http://pubs.opengroup.org/onlinepubs/9699919799/functions/exit.html)" do not belong to the list of [async-signal-safe functions](https://www.securecoding.cert.org/confluence/display/seccode/SIG30-C.+Call+only+asynchronous-safe+functions+within+signal+handlers).
I guess that a different program design will be needed for your function "[exit_handler](https://github.com/CleverRaven/Cataclysm-DDA/blob/4079fcfeb82ef2aea4e64ba69dd2125136c68b1f/src/main.cpp#L326)".
##

**Comment by kevingranade** [comment]
Instead of calling exit(), follow this article https://www.cons.org/cracauer/sigint.html

Instead of calling clear(), invoke the ncurses clean up handler as mentioned here https://stackoverflow.com/questions/44084793/handle-signals-in-ncurses

The windows terminal cleanup calls are probably also a problem.
