### ISSUE TITLE
Windows Development Environment

### ISSUE THREAD

**Issue by macrosblackd** [CleverRaven/Cataclysm-DDA#8442]
I'm creating this as a general discussion on getting the initial Windows development environment up and running.

One of the very first things I would like to put forward as something to adopt is packaging the '3rdparty' directory that (most of) the C::B (Code::Blocks) build targets are looking for.  Failing that we should create and include a script (python, powershell, etc) to set up the environment by going out and downloading the required libraries and setting them up.

Another thing I would like to see is the Windows developers as a group deciding on what the 'standard' environment should be going forward. I'm not necessarily talking about choosing between MinGW, cygwin, C::B or VS, but more along the lines of dependency structure and standardizing the the various build/make targets to use that structure.

A big reason I would like to see these is because every time a Windows developer would like to contribute, they either spend a ton of man-hours trying to decipher the various ways of setting up their environment successfully (with various levels of success) or they give up trying and move on to another project. I understand that the project was initially 'nix based, and that a good chunk of the active developers are using some flavor of linux, but just reading over the forums you will find several posts from people trying to get the environment up and running to be able to contribute.

I am currently fiddling around with figuring out which dependencies are actually needed to build and then run. It looks like there is a combination of using the VC targeted dependencies and the MinGW targeted dependencies. I have tried each one independently without success, it wasn't until I grew frustrated and just unziped all the packages into the 3rdparty folder that I found some success. I honestly am not sure if C::B is compiling the game for x64 or x86 at this point.
##

**Comment by NickTaylor-** [comment]
With my CMake patch (#11674), you can compile under VS with CMake, and it works. I'm currently in the process of writing the documentation for how to do it, but its basically dump all the .lib into dep/lib and all of the includes into dep/include.

**Comment by macrosblackd** [comment]
Nick, would it be possible to get this compiling under CLion?

**Comment by NickTaylor-** [comment]
Already does, at least when I tested it. Are you unable to get it working?

**Comment by macrosblackd** [comment]
I haven't actually given it a try - work has been hell - but CLion
will be what I use when I have some time available again.

**Comment by NickTaylor-** [comment]
Yeah, last I checked it worked. Only issue with native Windows building is it seems to run much slower, but I'm not sure if that's on this side, or if the Windows libraries are just slower.

**Comment by macrosblackd** [comment]
I'm trying to set up my mingw-w64 environment to compile 64bit, where do I put the different libraries?

**Comment by macrosblackd** [comment]
In your cmake patch, you mentioned having CMAKE download the libraries. After checking to see if it's possible (it is), we can point to a static version to download and the file will always be there. I think adding the ability to set up the environment automatically would be a great option to have included in cmake.

**Comment by drbig** [comment]
I'd be happy for us to have more Windows developers. If nothing else these people could help when dealing with Windows-exclusive bugs.

Have a look at `COMPILING.md` - I'd love to see a guide there on setting up a Windows dev env that doesn't require proprietary software. Given that at least in the Unix world one can go about building such env in a myriad of ways I'd assume you could make a general Windows guide and then provide some more specific setups.

Also: Cygwin is really a separate platform from Windows, and we could use some dedicated maintainers there too.

**Comment by i2amroy** [comment]
I've got Cygwin as a secondary setup on my computer, and it's rather easy to set up and compile on; but last I knew it doesn't support SDL at all (or at least not to the ability that 10+ hours of my works could get it working on) so it's limited to curses builds only.

**Comment by CIB** [comment]
@i2amroy Have you tried cross-compiling from cygwin? This would produce native windows executables and the SDL dependencies could be installed the same way they're installed on the linux cross-compiler (assuming that works)

**Comment by NickTaylor-** [comment]
I'm currently updating the documentation to reflect the new changes to CMake, and it will currently work with any development environment that CMake support (VS, Code::Blocks, Eclipse, etc.).

As for the auto-download of dependencies, with the amount of time I have to work on this at the moment (I have exams right now), probably isn't going to happen. CMake doesn't include anything to process zip files, and most pre-compiled Windows dependencies are zipped, and my efforts to get an external tool to do it reliably (PowerShell) have been unfruitful.

I will submit a pull request with my updated documentation, which includes using pre-compiled dependencies, as well as building the dependencies from source, as soon as I have fully tested my documentation. 

As it currently stands as well, some of the pre-compiled libraries are 32-bit only, so they need to be compiled rather than just downloaded. Although I may compile them myself, put them in a repo and link to it in the documentation as a download. I know that the project doesn't want to have any dependencies includes in the source, but I imagine having them separate would not be an issue.

**Comment by i2amroy** [comment]
>Have you tried cross-compiling from cygwin? This would produce native windows executables and the SDL dependencies could be installed the same way they're installed on the linux cross-compiler (assuming that works)

That's what the majority of the 10+ hours was spent doing. :P It compiles great... up until the very end where it starts to throw large number of errors about having to shorten random things because the space allocated in-code for them isn't large enough. It's the same error you would get if you were trying to compile a 64-bit program on a 32-bit compiler, but it showed up in 64-bit Cygwin as well. It's also one of the least helpful compilation errors in existence, so I was basically forced to just take random shots at fixing it until me and the internet ran out of possible fixes.

**Comment by CIB** [comment]
@i2amroy Aw, too bad. So compiling for windows from linux is literally easier? The world we live in. ^^

**Comment by DavidKeaton** [comment]
@i2amroy first thing I thought of was some weird limitation in `.text`, not sure if this is what you were meaning. :-)

**Comment by drbig** [comment]
This does seem to be doable: CLion + working cmake files + instructions on getting the dependencies in in COMPILING.md. Of course the long-term health of that would require someone paying attention (so basically a chicken-and-egg problem).

**Comment by macrosblackd** [comment]
Biggest issue seems to be getting cmake working correctly for all the different environments. There seems to be limited success with non-tiles builds, but getting the rest is a pain.

**Comment by karlnp** [comment]
Yeah... I'm not sure why exactly we keep running into problems with -Os builds (or release builds, in other words) so that's the real sticking point. I'm happy to keep plugging away at it.

**Comment by karlnp** [comment]
The CMake files should be working if you can get the environment & libraries in order, at least. The COMPILING-CMAKE file works reasonably well as long as you don't mind working in a terminal to compile.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
