### ISSUE TITLE
Feature request: Additional book colors

### ISSUE THREAD

**Issue by Waladil** [CleverRaven/Cataclysm-DDA#8577]
Now that we need to pre-skim books to know whether they need to be read or not, it'd be nice to have an extra colored distinction between books that are completely read and books that are completely unread.

Actually I'd like a lot of colors, for things to be very clear at a glance. The above is the most important, since it allows players to quickly sort useless from new. But below I'm gonna write out what I'd like to see for a full set of distinctions.
1. Unskimmed
2. Contains learnable skills & recipes
3. Contains learnable skills (no recipes)
4. Contains learnable recipes (no skills)
5. Contains skills with a minimum requirement over your skill level & new recipes
6. Contains skills with a minimum requirement over your skill level (no recipes)
7. Contains no new information
##

**Comment by hbnix** [comment]
As a relatively new player, I find book colours to be extremely helpful. However, there are three cases in which they are little misleading currently I think:

1) Martial arts manuals are coloured useless. E.g. 'Complete Krav Maga' on a character that does not know this style yet.

2) Skill books are coloured useless if skill requirement is not yet met and the book does not contain any recipes. E.g. 'The Complete Home Repair Guide' (construction 5 -> 8) on a character with construction skill below 5.

3) Some skill books appear coloured incorrectly for characters with extremely low intelligence. E.g 'Computer World' (computers 0 -> 1) is coloured useless for character with computers 0 at Int 4. Reading it *does* improve computers to 1, even though the intelligence requirement of 5 is not quite met, so should be blue no?

**Comment by DangerNoodle** [comment]
I would like to ask for an opinion on a possible idea.

Personally, rather than the harder to determine issue of new colors and whether they have merit, my only proposal is for books that have recipes, but are too high a level to earn experience from.

Specifically, simply changing these books from yellow to magenta, so they are consistent with other books that are not yet a source of experience. The reasoning is that most players will prioritize ability to raise skills over available recipes to learn.

And now that books can no longer grant recipes from reading, this further makes experience from books more desirable and accessible, relative to recipes (mainly by making the latter less accessible). As such, being able to tell whether a book can advance your skill level might be more desirable than being able to tell whether there are recipes available to learn.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
