### ISSUE TITLE
Can we have separate modifier (spawn rate) in menu regarding animal life?

### ISSUE THREAD

**Issue by Stoukeer** [CleverRaven/Cataclysm-DDA#8605]
Like we have for zombies. Seriosly those hordes of coyotes, foxes, squirrels and other stuff ruins (well at least for me) the survival effect. What's the point in hunting and trapping, when you can just open the door of your house and shoot 12 dogs and have supply of food for a month. With menu modifier new players will be okay because, well they don't need to touch it so the number of animals around will be like right now. But more experienced players can lower the numbers and:
- Trapping becomes relevant, so if you want to continue eat meat - place the traps around your house and check them regularly
- Hunting is a thing now! Grab your trusty Remington700 (or bow if you like it that way) and go find a deer (or bear)
- Survival skill becomes even more relevant because now you need to not rely solely on meat, but look for wild vegetables, berries and mushrooms
- Cooking skill and general looting becomes more relevant because well, less meat - more variety in your everyday ration (or more reasons to go to loot stores and basements) and more reasons to cook better food (that gives you more nutrition)
- Visual improvements. You don't need to spend half an hour everyday to clear thousand corpses of critters around your house, so your home will be your home and not a junkyard/animal cemetery.

Thoughts?
##

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
