### ISSUE TITLE
More conditionals for mapgen json's

### ISSUE THREAD

**Issue by Lap** [CleverRaven/Cataclysm-DDA#8697]
It would be useful to let json map plots have more flexible spawning based on certain game/world settings:

For example, some locations, like "bandit_camp," become very low risk treasure hordes when players play without NPC's. Ideally, the game would detect whether NPC's were on before even loading the json file and load a modified version, or the json file itself could specify to only spawn a horde of zombies instead of the three NPC's, giving this location a challenging, overrun feel. Or perhaps it would just scale down the loot.

There are probably some other world/game settings that might be beneficial to let json's access, but npc generation was the first that came to mind.

This might be a moot point if #8662 or another branch adds Lua based map plots, but I don't know if that is ever going to happen.
##

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
