### ISSUE TITLE
Deadbolts for doors

### ISSUE THREAD

**Issue by narc0tiq** [CleverRaven/Cataclysm-DDA#8918]
As discussed in IRC, when playing with NPCs they have the annoying tendencies to steal things from your houses, and also to attack you in your sleep or immediately upon wake-up. It seems that, as NPCs become more useful to play with, there should be a way to bar them from passing through some doors.

Enter the deadbolt. As a construction menu item, it would change a wooden door into a wooden door with deadbolt, which you could then close twice to lock the deadbolt and prevent NPCs or players from just walking in. A player could use a crowbar to break through a deadbolted door (though NPCs should only do this if they're explicitly thieves... which ours aren't smart enough for yet).

The only obvious problem is how does the game tell which side of the door the deadbolt is on. I'm positing that it should be whichever side of the door the player was on when they installed it, but you'll have to mark that somehow in the world so the game doesn't forget it.
##

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
