### ISSUE TITLE
Major physical disadvantages

### ISSUE THREAD

**Issue by Prezombie** [CleverRaven/Cataclysm-DDA#8984]
One armed: You lost an arm a few years ago. You're used to it now. two handed weapons are useless, you can't carry something in your offhand, and it takes longer to change clothes. Most crafting is slower, and you have a harder time driving vehicles. And the HP bar for that limb is gone, but mobs still have a chance of "hitting" that spot.

One Legged: You lost a leg a few years ago. Start with a prosthetic leg. 
With a prosthetic leg: running has a chance of falling if you're on uneven terrain. Walking speed is slower. With a pegleg, the penalties are doubled, but you're able to craft it at the start. (it's a quickly carved stick. Assume that the prosthetic base is grafted on, I guess.)
Wielding crutches in [one|both] hands [halves|nullifies] the movement penalties, but they make lousy weapons.
HP for leg is lower, but half of hits to it damage only the prosthetic (if equipped).
All the leg-based advantages are grayed out.

Wheelchairs are in the game now/soon, they open a new level of self-imposed challenges for jaded players.

Paraplegic: Numb below the waist. Start with a wheelchair. Not much chance of survival, but that's the fun of the challenge.

Movement speed -75-90% (maybe a difficulty options setting, Paraplegic movment speed is 1/x normal, x varies from 4 to 20), sound +200% (you need to crawl everywhere)
Leg damage doesn't hurt, no pain penalties, but no infection warnings.
Driving skill, mechanic skill +2 (your wheelchair is a vehicle, and it has been your friend for a while)
All the leg-based advantages are grayed out.
Can't use bikes (duh)
Can't use vanilla cars, you need to modify them to be usable with several sticks and a bunch of duct tape for them to be drivable in your condition.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
