### ISSUE TITLE
Bug (2093) - unable to plant marloss seeds

### ISSUE THREAD

**Issue by EpicMarble** [CleverRaven/Cataclysm-DDA#9025]
Was playing in a world started in 2053 and I decided to go for a fungal flower on the map to get some marloss berries. I only found marloss seeds on the bushes instead of the berries (out of 10+ bushes) and I tried to plant them, but unfortunately they don't appear in the seed planting menu. When I eat the seeds it gives a warning telling me I could plant them in a mound instead of eating (implying that they should be plantable). Just tested it in 2093 and it is reproducible there. 

On a side note, eating the seeds gives the same effects as the berries so I tried getting a marloss bush to spawn that way. It worked and when I checked several of them for seeds / berries, they only give berries. I would think that any marloss bush should spawn the same ratio of seeds and berries so that might be a bug as well.

**Comment by mugling** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
