### ISSUE TITLE
Batter fried fish are too generous

### ISSUE THREAD

**Issue by Headjack** [CleverRaven/Cataclysm-DDA#9115]
Batter Fried Fish, or my BFF, gives 6 portions that are 28 Nutrition each. This takes 3 fillets and, like, 1 flour. Fillets normally cook to 26 or so Nut, so this is pretty great.

While I think most cooking is to stingy on increasing nutrition or enjoyment, BFF is clearly broken. it should probably give three portions at somewhat higher Nut. Even still, it probably isn't enjoyable enough to pay for the bread which the flour could be used for. Food recipes in general should be buffed, since a lot of the time it's just simpler and stronger to make Cooked Meat or Bread or whatever is most boring, since you hardly care about tiny enjoyments and need Nutrition constantly.

But yeah, sorry to see it go, but probably not intentional.
##

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
