### ISSUE TITLE
Butcher action displays incorrect time it seems

### ISSUE THREAD

**Issue by ArikVhedrovix** [CleverRaven/Cataclysm-DDA#9127]
I am using v.db05e8a Windows Console Experimental.

I noticed that butchering a zombie seems way too fast. At character speed of 100, with a rapier which has a butcher value of 16, and Survival skill level 2; I have been seeing time elapsed values as low as 7 and as high as 100 when butchering. That means my guy can butcher a corpse in less or the same time as it takes for him to take a single step. It takes him 250 to take an aspirin. I tried butchering near some enemies and they got in several attacks. The elapsed turn time for that was displayed as 23 even though the zombies were able to close with me over several squares and attack a few times. So I guess the display time is incorrect?
![capture1](https://cloud.githubusercontent.com/assets/5952322/4341018/9901f588-4034-11e4-9224-e3af04828dc5.PNG)
![capture2](https://cloud.githubusercontent.com/assets/5952322/4341019/9f90bb96-4034-11e4-9b65-436b7b53e5f4.PNG)
![capture3](https://cloud.githubusercontent.com/assets/5952322/4341023/a4bc1e30-4034-11e4-958d-3082b970b4ad.PNG)
##

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
