### ISSUE TITLE
Icelab's temperatures are ignored by items

### ISSUE THREAD

**Issue by Barhandar** [CleverRaven/Cataclysm-DDA#9162]
Additionally, icelabs drop temperature even on surface.

**Comment by Barhandar** [comment]
Something went broke between then and now: the crutch now *only* applies if player is on ice_lab tile, one step away and everything rots like usual.

**Comment by kevingranade** [comment]
I don't follow, that sounds like it's working as expected, we don't have
any code to alter behavior based on proximity to an ice lab, just whether
you're in it or not.

**Comment by KA101** [comment]
>I don't follow, that sounds like it's working as expected, we don't have any code to alter behavior based on proximity to an ice lab, just whether you're in it or not.

Thing is, perishables that you put somewhere should spoil based on their location--such as a minifridge--not on yours (since they're not on your person).

Basically, the primary emergent use of ice labs was as a giant walk-in fridge/freezer.  This ruins that.  It'd be as though the minifridge didn't slow spoilage because food in it continued to track and spoil based on your position.

**Comment by kevingranade** [comment]
I see what I was missing, it does not apply if the player is not  there,
even though the items are.

**Comment by Barhandar** [comment]
>I see what I was missing, it does not apply if the player is not there, even though the items are.

And applies if the player is in the lab tile, but items are not. Ergo: incorrectly uses player position instead of correctly using item's.

**Comment by Barhandar** [comment]
The issue has been long fixed by #11782. Overarching problem that required the bypass to be made, items not being able to take local temperature into account, requires a separate issue. Closing.
