### ISSUE TITLE
Cutting material outputs

### ISSUE THREAD

**Issue by Barhandar** [CleverRaven/Cataclysm-DDA#9259]
It's a suggestion, feel free to discuss.

It would probably require a bit of code, and I don't even know if JSON/whatever is used to parse it allows associative arrays, but the idea is as follows:

Allow material variable accept not only material names, but also numbers, i.e. `"material" = ["leather"=5,"cotton"=3]`.
For compatibility's sake, if it doesn't have amounts specified, proceed as currently, return the arbitrarily chosen material with amount equaling volume.
If only one material has amount and the other(s) do not, return that amount of that material, and volume amount of arbitrarily chosen other material.
If all materials have amounts, return all of materials in specified amounts.

This way, jsons and mods don't require extensive modification, one can specify how much material item is 'made' from and returns when cutting, and problems like 'SWAT armor returns 52 rag' are solved. Along with all "volume is higher than amount of required materials, need disassembly recipe or it will become infinite resource source" issues.
##

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
