### ISSUE TITLE
Item overflow suggestion

### ISSUE THREAD

**Issue by Mshock777** [CleverRaven/Cataclysm-DDA#9320]
When tile volume is 10(5)% of max volume, next item instead goes to random nearby tile. When all 9 tiles are 10%, tile in the middle will then accumulate stuff until 20%. And so on.
Also, it's funny that medium corpse has volume of 18.75 liters, when human body is 65. It would make sense to increase it to volume of 250(62.5l), so it won't technically fit in beer keg. it will still fit in barrels,
but not in canvas bag, which strangely has volume of 60.
(Also, plastic bag can contain 24 volume, is it a typo?)
(And why not make some trees accept small amount of items, at least young one?)
##

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
