### ISSUE TITLE
time taken to move items with advanced inventory is not consistent

### ISSUE THREAD

**Issue by gcaliber** [CleverRaven/Cataclysm-DDA#9392]
It takes more than twice the amount of time to move items with "move all" compared to moving them individually.
##

**Comment by Oskar636** [comment]
This is still pretty inconsistant, but the values that @gcaliber stated are diffrent now ( or diffrent because I didn't have quick ). I'm 100% sure I noticed some items moving with only 3 seconds but when I finished testing others and tested the first ones again I moved them per 6 seconds. And moving with move all takes 12 seconds on every item. Quick allows you to move an item ( 100 nails in this example ) 11 times in 60 seconds, so works correctly. And it allows you to move the nails 5 times in 54 seconds with the " , " .

**Comment by Leland** [comment]
Closing in favor of #19850 due to more recent discussion
