### ISSUE TITLE
ownership system?

### ISSUE THREAD

**Issue by jcd000** [CleverRaven/Cataclysm-DDA#9555]
inspired by this post: http://smf.cataclysmdda.com/index.php?topic=8022.0

we have currently no way to know to whom items belong.
what if items had also an ownership attribute?

how this helps: 
- mainly with npc interactions as we then could:
  - stop honest npc's stealing the player's stuff.
  - make 'thieving' npcs
  - allow npc's to own stuff not in their inventory
  - allow the player to steal these (with repercussions)

perceived problems:
- determinining when a player discards something, rather than just leaving it on the ground/storing it somewhere
  -> maybe solved with ownership expiring if outdoors and enough time has passed
- others i did not see

all in all, it should be helpful as we are building up npc's and factions.
##

**Comment by Dunkhan** [comment]
We have zones now where you can designate a zone and say auto pickup should be disabled. Why not just extend this mechanic to allow marking a home zone. This could help with NPCs overburdening themselves as well.

Behaviour: While in home zone friendly/following NPC will sleep without being told, will drop things they dont currently need, and will not pick up things unless they need them. e.g. if he has a bow and there are arrows on the ground he will grab them, but he will not pick up leather patches and string.

The zone mechanic is not hard but the NPC AI integration might be more complex, I don't know if they have a concept of 'need' and 'want'

**Comment by kevingranade** [comment]
Yea, they already don't pick things up unless they think they need them, so
that doesn't help much.

**Comment by Dunkhan** [comment]
I just read through the need function in the npc.ccp file and something else is happening. One thing that they will always pick up is thread. I could not work out why. 

Additionally they never pick up food. My companions all seem to die eventually as well although it may not necessarily be starvation.

**Comment by Coolthulhu** [comment]
May be infection. I don't think they understand how to fix their infected wounds at the moment.
I enabled infection when I simplified bite function and it may have been too early. I'll probably disable it with a hack - properly fixing it would require them understanding how to disinfect and knowing how to ask the player for meds.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.

**Comment by ZhilkinSerg** [comment]
Fixed in #29834
