### ISSUE TITLE
Allow spawning packs of monsters of various composition in a single spawn call

### ISSUE THREAD

**Issue by GlyphGryph** [CleverRaven/Cataclysm-DDA#958]
Allow a spawn call to be able to several monsters near each other, instead of just one, but as part of a single spawn call and a single entry in a standard monster group. These groups of monsters (which we will call packs from here on in, to distinguish them from the 'monster groups' we have already) should pull from a definition that states the composition of a pack in terms of size and composition, though the actual details should have an element of chance. Some hypothetical examples, to clarify, follow:

Dogs and wolves always spawn in packs of three to seven enemies.
Groups of normal zombies spawning in place of specials in classic mode. This is the only "special" for Classic mode, and spawns a tightly clustered pack of 3-10 zombies.
When Necromancers spawn, they have the chance to spawn with several "bodyguard" skeletons.
When Rust Eaters spawn, they almost always spawn in groups, and these will have a chance of containing a Junk Gluttons, but only ever one Junk Glutton at most.

As such, the definition should probably involve something like:
    rust_pack: ["junk_glutton", 0-1, "rust_eater", 3-7]
To spawn a group that has 0 to 1 Junk Glutton and 3 to 7 rust eaters. "rust_pack" can then be added to the normal monster spawn list, and when a rust pack is spawned, it creates the several monsters needed.

Might want to also consider a percent spawn model - as is, that will always result in a 50% chance of junk glutton, which might not always be appropriate.
    rust_group: ["junk_glutton", 25%, "rust_eater" x 3, "rust_eater", 75%, "rust_eater", 75%, "rust_eater", 75%, "rust_eater", 75%]
Of course, I could also just do
    rust_glutton_group: ["junk_glutton", 1, "rust_eater", 3-7]
    rust_group: ["rust_eater", 3-7]
and then have the normal spawn chance for each individual groups.

The actual implementation isn't as important as the resulting feature.
##

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
