### ISSUE TITLE
Post-threshold category mutation locking

### ISSUE THREAD

**Issue by i2amroy** [CleverRaven/Cataclysm-DDA#9668]
So I was reading some of the recent mutation stuff and this idea popped into my head, what if we locked category bound mutations of a post threshold category against being purified? You would still be able to remove them through mutating new traits that canceled them out, but they would no longer be able to be removed through purification (ideally this would even revert back to the locked traits if the canceling mutation was purified away).

Lore wise the basic idea is that purifier is pushing you back towards the baseline by suppressing the mutation causing ooze, but once you cross the threshold you are far enough mutated that that is your new "baseline", so purifier won't suppress it. (Maybe only lock the category traits the player currently has on threshold breaking? Sort of the act of breaking the threshold being what "sets" the new baseline?) I feel like the idea might further impress a bit of the idea of thresholds being a permanent, fundamental transformation in the character than they currently are. (Code-wise I think this would be as simple as pushing all of the mutations that match the threshold category into the list of "traits" the player took at chargen, but I'd have to look closer to be sure).

I'd particularly like to hear from @KA101 on this idea, but if some others want to chip in as well on what they think that would be sweet.

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
