### ISSUE TITLE
lab final can spawn disconnected from all other rooms

### ISSUE THREAD

**Issue by gcaliber** [CleverRaven/Cataclysm-DDA#9726]
I had a lab final like this. I had to jackhammer my way from the last up/down stairs to the middle tile which was otherwise surrounded by rock.

 <%%
%L%
%%%

Also, lab final doesn't spawn up stairs so if the only down stairs on the floor above goes into it you need a rope to get down and back up safely.
##

**Comment by vityav** [comment]
Confirming this issue still exists as of a world built on August 23 (from a git version compiled that date), but since this part of the map may not have been generated yet, could be as recent as a git version compiled September 7. Had two lab finales with no stairs and no access other than teleporting.

**Comment by Leland** [comment]
Closing this in favor of the master science lab issue #10958.
