### ISSUE TITLE
More uses for computer skill

### ISSUE THREAD

**Issue by Shoes01** [CleverRaven/Cataclysm-DDA#9739]
What if there were some items, like the power helmet, that allowed players with a high enough computer skill to program modules for the helmet. Like a weather reading module, or an alarm clock, or anything else. Here are a list of random points:
- USB sticks could have some of these modules on them.
- Programming modules would be a time consuming process, maybe even chunked up. Like you would need to program an interface, drivers, UI, and those could be the different steps. This of course would just be obfuscation, but each piece could take a few hours of coding; chunking it allows a player to code a little bit over the course of a few days.
- When a player would fail, maybe they would get a "there are 12 bugs remaining", and each time they tried to program the module again, the number would go down. Or up, because you know, that happens.
- Some items that could be programmed to do things are : jail broken phone, jail broken bionic, variety of robots and turrets, anything powered really...
- Modules would be item independent, and items would be flagged as being "X module programmable"

I picture this programming thing to work like gun mods, but on electronics, and created using only computer skill. I don't necessarily plan on doing this anytime soon, but I wanted to share it regardless!
##

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
