### ISSUE TITLE
Player must not use rotten ingredients when cooking

### ISSUE THREAD

**Issue by jarmush** [CleverRaven/Cataclysm-DDA#9879]
In game, when i have chunk of meat(fresh) and chunk of meat(rotten) in inventory and craft "cooked meat", I get "cooked meat(rotten)"

But IRL i'm not idiot! I will never start to cook rotten meat when i have fresh meat. I think player must not use rotten ingredients in crafting.
##

**Comment by eliotcougar** [comment]
This is a good one for someone to look into again after 2 years... Since so much have been done to the crafting interface... It would be good to make different freshness items to appear in the "choose item to use" menu after you start crafting... It would be a big Quality of Life improvement in exchange for a couple of additional if statements...
The workaround right now is to take the fresh produce out of the fridge before crafting in order for it to appear as a separate entry in the menu (inventory vs nearby)...

**Comment by jarmush** [comment]
Two years passed... OMG...

**Comment by Leland** [comment]
Yeah, this is an old one.

Cooking with rotten ingredients should most likely just be completely disabled.

[#20210 mentions](https://github.com/CleverRaven/Cataclysm-DDA/issues/18303#issuecomment-246543408):

> "Rotten items are consumed without asking. This can't be easily fixed in a way that would still allow using rotten components for anything non-hardcoded (say, plant mutant wanting a rotten soup)."

Which is true, but I think in the immediate we should just hardcode a prevention for rotten stuff. There's just no point.

**Comment by jarmush** [comment]
there is a point if you gonna grind your cooking skill and not gonna eat it

**Comment by Leland** [comment]
Closing per reasoning outlined in https://github.com/CleverRaven/Cataclysm-DDA/pull/19562#issuecomment-263901947. Rotten food crafting should definitely still be allowed (e.g mutants, crafting vinegar, etc).

Additionally, as far as I can tell, fresh food *is* preferred in crafting. With an inventory of both rotten meat chunks and fresh meat chunks, crafting cooked meat chunks is done with the fresh ones first, each time.

If, however, cooking with rotten food first can actually happen (i.e my testing wasn't thorough enough) I'd recommend opening up a new issue ("Use fresh ingredients before rotten when crafting"). This issue is both very old and about disallowing crafting rotten food entirely.
