### ISSUE TITLE
Hiding under tables/beds

### ISSUE THREAD

**Issue by Snaaty** [CleverRaven/Cataclysm-DDA#9897]
First off, I know the string freeze is there, but still I wanted to post this idea somewhere to get some feedback (and perhaps even advice on how it could be done).

The idea being:

 By examining tables or beds you get a prompt if you want to hide under them. Hiding under a table reduces your vision to two(or three?) squares of sight around your position. The tricky part is, that only monsters that step on those squares you can see can see you as well. 

Hiding under the bed (might take a little longer, and can't be done by large ppl. or mutants) leaves only a radius of one square. 

I am not sure how e.g. tunring on a flashlight should increase that radius.

The purpose of that functionality would be to give the player an alternative to "fight or flight" when he gets spotted: He may also try to hide and wait it out!
Regarding balance, abusing this has to be avoided (duh), if the monster can see you crawling under that table/bed, your chances of not being discovered should be minimal. I am not sure as to how well the sense of smell is developed in zombies, if it will break the usefulness of this feature or not.

For the technical questions: I imagine the basic infrastructure is available for reducing the players vision range, but what about making that player "invisible" to monsters unless they are within that range? 
Actually, while thinking about it I realize that there's a good number of technical complications.. :/

Anyway, tell me what you think, and if it is even remotely realistic or if it's never going to happen due to complicatedness.
##

**Comment by illi-kun** [comment]
### This issue was closed as it appears inactive.

Reducing open issues to those which are (or will) be actively worked upon helps us focus our efforts. This issue has not been deleted - it still appears in searches and if it contains relevant information you are encouraged to continue to link to it.

### If this issue was a bug
It should be reopened if it can be reproduced in the current build. You can obtain the most recent copy [here](http://dev.narc.ro/cataclysm/jenkins-latest/). Please check there is not a more recent report of this bug before doing so. If no more recent report exists you should continue the discussion in this issue.

### If this was a feature request
If the consensus was that the idea was good you could consider submitting an implementation via a PR. If you want to comment further please do so here as opposed to opening a new issue. Before posting check nobody has already made the same point and consider whether your comments are likely to lead to an implementation. If you have doubts about either consider instead [voting](http://iv.cataclysmdda.com:8111/all) for the issue

### If you want to work on this issue
Then either assign it to yourself or if you are unable to do so claim it via adding a comment. Please don't assign others or make a general request for action.
